### ISSUE TITLE
[Bug]: Menu instance events not firing when instance is used as context menu for Tray on Linux

### ISSUE THREAD

**Issue by kroko** [electron/electron#28837]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.2 LTS, GNOME 3.36.8 @ X11

### What arch are you using?

x64

### Expected Behavior

* A Menu instance is created and reference is kept around.
* For the instance `menu-will-show` and `menu-will-close` listeners are added.
* The instance is used to set Tray context menu.
* Clicking on Tray icon, that opens context menu, should fire `menu-will-show` and `menu-will-close`

Roughly the code goes along the lines of

```js

import {
  Menu as ElectronMenu,
  Tray as ElectronTray
} from 'electron';

export class MyTrayManagerClass {
  // keep around
  #trayMasterObj = null;
  #trayMenuObj = null;

  // bind
  constructor () {
    this.handleMenuWillShow = this.handleMenuWillShow.bind(this);
    this.handleMenuWillClose = this.handleMenuWillClose.bind(this);
    // ...
  }

  someMethodA () {
    this.#trayMasterObj = new ElectronTray(/* ... */);
  }
  
  // set contect menu
  someMethodB () {
    const menuTemplate = [/* ... */];

    this.#trayMenuObj = ElectronMenu.buildFromTemplate(menuTemplate);

    this.#trayMenuObj.on('menu-will-show', this.handleMenuWillShow);
    this.#trayMenuObj.on('menu-will-close', this.handleMenuWillClose);

    this.#trayMasterObj.setContextMenu(this.#trayMenuObj);
  }

  handleMenuWillShow () {
    console.log('handleMenuWillShow');
  }

  handleMenuWillClose () {
    console.log('handleMenuWillClose');
  }

}
```

### Actual Behavior

* Clicking on Tray icon, that opens context menu, does not fire `menu-will-show` and `menu-will-close` on GNU userland.
* The exact same code works on macOS Catalina 10.15.7

### Additional Information

Electron documentation [is clear](https://www.electronjs.org/docs/api/tray#event-click) about how to manage changes in Tray context menu on GNU userland 

```js
 // Call this again for Linux because we modified the context menu
  appIcon.setContextMenu(contextMenu)
```

I am developing an app where values for some `MenuItem`'s in Tray context menu are changing based on remote data (not real time, but ~10 times a minute) and thus I am calling `setContextMenu` quite a lot - also in situations where end user might have Tray menu opened.

It is not that dynamic that `setContextMenu` for Tray should be replaced with all that frameless BrowserWindow stuff that would take role of being menu. The native menu is desirable.

The app was first done on macOS where behaviour is desirable. 1) On macOS, once the tray menu is opened, it _freezes on the values that were set at the moment the menu was opened_, which is OK and desirable, even when `setContextMenu` is fired during the time while the menu is open. 2) If that was not the case, events fire on macOS and could be used to _freeze manually_.

However on GNU (Ubuntu using GNOME3.36.8@X11) calling `setContextMenu` while the context menu is open, rerenders the menu "in place on screen" - resulting in dimension jumping, flickering, disappearing, reappearing etc.

It would be possible to avoid this _flickering while open_ issue on GNU if there was a way to detect that context menu attached to tray is currently open. Either by property, getter or two events (opened, closed).

Such two events already exist, they just do not work on the platform. If they did work, then issue with flickering due to changing values while open is _solved_ ... by not changing them 😄  If menu is open, `setContextMenu` is delayed until next `menu-will-close`, opening tray menu is snapshot of values as they were at the moment of opening, same as in macOS.

**Comment by raksooo** [comment]
I can confirm that this is still happening on 16.0.4.
