### ISSUE TITLE
[Bug]: nativeTheme.shouldUseDarkColors not working on linux

### ISSUE THREAD

**Issue by makerio90** [electron/electron#28838]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Expected Behavior

returning true (i use dark mode)

### Actual Behavior

returning false, regardless of color scheme.

**Comment by Nokel81** [comment]
I have run into this as well on electron@14.2.9

**Comment by Hubro** [comment]
This is probably my biggest annoyance in my day to day life. I have pretty much every application following my system wide dark mode preference at this point, *except* my browser and all my Electron applications, *which is like half of my applications*.

Is this something Electron won't support before Chromium supports it natively? I feel like that could take a *long* time.

It would be amazing if Electron could implement support for the (now standardized) Freedesktop system-wide dark mode preference:

https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.impl.portal.Settings.xml#L34

It doesn't seem like it would be a lot of effort. The logic would basically be:

- If running in Linux
- If "org.freedesktop.appearance.color-scheme" is available (dbus)
- Then use the value of "color-scheme"
- Listen for changes to the value and re-apply above logic

**Comment by Nokel81** [comment]
This is certainly still an issue

**Comment by makerio90** [comment]
fuck that bot

**Comment by dbrgn** [comment]
Related issue (newer, but with more technical details): https://github.com/electron/electron/issues/33635

**Comment by Danik1601** [comment]
https://github.com/electron/electron/issues/33635#issuecomment-1502215450
