### ISSUE TITLE
[Bug]: Cannot redeclare block-scoped variable 'screen' occurs on vscode typescript intellisense but then it works when running the app

### ISSUE THREAD

**Issue by kimlimjustin** [electron/electron#28833]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21.04 x86_64 5.11.0-16-generic

### What arch are you using?

x64

### Expected Behavior

Everything works fine

### Actual Behavior

These errors occur on vscode intellisense when using `screen.getPrimaryDisplay().workAreaSize.width` in typescript file:
- Cannot redeclare block-scoped variable 'screen'. ts(2541) [1, 35]
   > lib.dom.d.ts[19667, 14]: 'screen' was also declared here.
- Property  'getPrimaryDisplay' does not exist on type 'Screen". ts(2339) [9, 35]

### Additional Information

Although there're problems occured from vscode typescript intellisense, there's no problem when running the application

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by kimlimjustin** [comment]
I tried Electron Fiddle but it use JavaScript and I can't find how to switch to typescript instead of javascript. On my case, this happens when I use TypeScript instead of JavaScript.
Anyway, you can find my code on [GitHub](https://github.com/kimlimjustin/xplorer) too!

Thanks!

**Comment by miniak** [comment]
This is not an Electron issue.
