### ISSUE TITLE
[Bug]: Change Fa to Pr (in localization) 

### ISSUE THREAD

**Issue by miko-github** [electron/electron#28835]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04 LTS

### What arch are you using?

x64

### Expected Behavior

**Farsi** not is language in world :thinking: 
we are have **Parsi**, but **Arabic** not have **P** sound, then change with **F** sound, then they are call **Parsi** (**Persian** Language) to **Farsi**, but **Farsi** is **incorrect** and **Parsi** is **correct** (**Persian**)

change **Fa** to **Pr** as **Persian**(**Parsi**) :hugs: 

thank for reading :heart: 

### Actual Behavior
in localization change fa to pr
:heart:

### Additional Information

:heart: :medal

**Comment by nornagon** [comment]
Where are you seeing **Fa**?

**Comment by miko-github** [comment]
> Where are you seeing **Fa**?

in localization,

**Comment by miko-github** [comment]
in [here](https://www.electronjs.org/docs/api/locales) :hugs:

**Comment by nornagon** [comment]
@miko-github unfortunately that list is in reference to the IANA standard language codes, defined here: http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry, which is beyond the control of this project.
