### ISSUE TITLE
[Bug]: Transparency does not work on Ubuntu (Black background instead)

### ISSUE THREAD

**Issue by kimlimjustin** [electron/electron#28834]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21.04 x86_64 5.11.0-16-generic

### What arch are you using?

x64

### Expected Behavior

Having a transparency background.

### Actual Behavior

Black background instead.

### Additional Information

This might be a duplicate of #15947, but the issue is closed by the bot saying the version reported is not longer supported. I use the latest version, 12.0.5 and this issue still exists tho...

**Comment by Curve** [comment]
Can confirm this.

**Comment by PhieF** [comment]
same problem the only way to handle this is to disable hardware acceleration but I need hardware acceleration

**Comment by Curve** [comment]
> same problem the only way to handle this is to disable hardware acceleration but I need hardware acceleration
> the electron team always end closing issues related to that without fixing it...

For me disabling Hardware Acceleration doesn't even fix it

**Comment by afflerbach** [comment]
See [#25153](https://github.com/electron/electron/issues/25153#issuecomment-843688494) for a possible workaround.

**Comment by Curve** [comment]
> See [#25153](https://github.com/electron/electron/issues/25153#issuecomment-843688494) for a possible workaround.

Also did not work in my case

**Comment by kimlimjustin** [comment]
> > same problem the only way to handle this is to disable hardware acceleration but I need hardware acceleration
> > the electron team always end closing issues related to that without fixing it...
> 
> For me disabling Hardware Acceleration doesn't even fix it

Same here!

> the electron team always end closing issues related to that without fixing it...

Agree, as I saw from the electron issue, this issue has been here since version 4, and now it's 14 but not fixed yet.
