### ISSUE TITLE
[Bug]: minWidth doesn't work if minHeight is not assigned and vice versa.

### ISSUE THREAD

**Issue by kimlimjustin** [electron/electron#28832]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21.04 x86_64 5.11.0-16-generic

### What arch are you using?

x64

### Expected Behavior

minWidth works fine even though minHeight is not assigned and vice versa

### Actual Behavior

minWidth doesn't work if minHeight is not assigned and vice versa

### Additional Information

Screenrecord:

https://user-images.githubusercontent.com/61906684/115988520-5e690700-a5e4-11eb-9edb-37fd94f46e3f.mp4

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to put the code you used to make your screen recording into a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.

**Comment by kimlimjustin** [comment]
Here it is: https://gist.github.com/kimlimjustin/afcea41066b5f1be0bc7c286f0cc4f10 
Btw, I found out that this happens when frame is set false
