### ISSUE TITLE
[Feature Request]: electron playback video format problem

### ISSUE THREAD

**Issue by 1056824847** [electron/electron#28845]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The video tag of electron can only support some formats, and there is no way to play some local video files. Can I support more video formats?

### Proposed Solution

At present, I play the video in this way: https://github.com/Kagami/mpv.js/, but I have to introduce the libmpv file, and the Linux support is not very good

### Alternatives Considered

https://github.com/Kagami/mpv.js

### Additional Information

null

**Comment by nornagon** [comment]
We have no plans to support video codecs beyond what Chrome supports.
