### ISSUE TITLE
[Bug]: window.open a pdf url,  call window.print() block the window

### ISSUE THREAD

**Issue by neusc** [electron/electron#28844]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.0

### What operating system are you using?

Windows

### Operating System Version

windows 10 version 1809

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

window.open a pdf url,  call window.print() and select the option of print to pdf, then save pdf to local disk and window can work normally instead of blocked.

### Actual Behavior

the pdf can save to local disk normally, but current pdf window blocked, other tabs work normally.

**Comment by codebytere** [comment]
Duplicate https://github.com/electron/electron/issues/28848
