### ISSUE TITLE
[Bug]: Cannot get a file path from a save dialog with * and simple name (Windows)

### ISSUE THREAD

**Issue by bpasero** [electron/electron#28850]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19042.870

### What arch are you using?

x64

### Expected Behavior

A file path can be retrieved from the file save dialog.

### Actual Behavior

An error shows "The file name is not valid"

![image](https://user-images.githubusercontent.com/900690/116086742-6ab29a00-a6a0-11eb-9d0b-1fc0d0b20210.png)

### Testcase Gist URL

https://gist.github.com/1fd53f68835a6b320a97eda5005e109b

### Additional Information

Steps:
* run the fiddle
* from the dropdown select "All Files"
* in the input field type "whatever"
* hit OK

**Comment by codebytere** [comment]
@bpasero this is intended behavior: https://github.com/electron/electron/blob/aaf03765ed9da4f4d70101a5b35ffc086816ac87/shell/browser/ui/file_dialog_win.cc#L137-L155. Files saved with the `All Files` wildcard filter need to have an extension added - none will be automatically added
