### ISSUE TITLE
BrowserWindow: Does not activate on app startup on macOS

### ISSUE THREAD

**Issue by vraravam** [electron/electron#28857]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.2.3

### What arch are you using?

x64

### Last Known Working Electron version

11.4.3

### Expected Behavior

When I start Ferdi (which is based on Electron), the main window should show up.

### Actual Behavior

When I start Ferdi (which is built on Electron), the process starts up - ie I can see Ferdi when I do "Cmd+Tab", but it shows up with no windows open. When I subsequently shift focus to another running application, and then shift back, then the Ferdi window opens up. 

This was NOT the case with electron 11.4.3 - the only change in the codebase is the electron upgrade from 11.4.3 to 12.0.5

**Comment by codebytere** [comment]
@vraravam if you'd like for us to triage this, you must provide a reproducible test case that we can run ourselves, which demonstrates clearly that this is an issue with Electron and not your own app. Please do so or we will close this issue within 10 days.

**Comment by vraravam** [comment]
Closing - since there was some other stuff going on in my local. Thanks for the prompt response.
