### ISSUE TITLE
[Bug]: WebView Tag Blank Page After Facebook Login

### ISSUE THREAD

**Issue by jrxcorp** [electron/electron#28865]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

macOS

### Operating System Version

macOS  Big Sur

### What arch are you using?

x64

### Expected Behavior

Run normally

### Actual Behavior

After logging into Facebook through webView, the page is blank. When I change the UserAgent to an older version of Chrome, the page works again. What can this be? Remembering that with any UserAgent through the BrowserView Facebook normally works, only through the WebView that does not work.

**Comment by sergiop38** [comment]
I have a similar error. I use Ubuntu 20.10,  Electron 12.0.5 and Node Js v14.16.0.
Electron freeze if I try to login on Facebook . Same problem if on Google I click on Twitter's login link. In this case the only message is
`SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.", source: internal/worker.js (82)`

I'm sure it worked a few weeks ago

**Comment by pushkin-** [comment]
I think I'm getting this too. On Windows - nothing specific to Facebook or webview:

main.js:
```
import { app, BrowserWindow } from "electron";

(async () =>
{
	await app.whenReady();
	const win = new BrowserWindow();
	await win.loadURL("https://example.com");
	win.webContents.openDevTools();
})();
```

running that shows a crash in devtools:

>Uncaught ReferenceError: SharedArrayBuffer is not defined
    at VM95 worker.js:82
    at NativeModule.compileForInternalLoader (VM10 loaders.js:283)
    at nativeModuleRequire (VM10 loaders.js:312)
    at VM94 worker_threads.js:9
    at NativeModule.compileForInternalLoader (VM10 loaders.js:283)
    at nativeModuleRequire (VM10 loaders.js:312)
    at VM93 inspector.js:30
    at NativeModule.compileForInternalLoader (VM10 loaders.js:283)
    at NativeModule.compileForPublicLoader (VM10 loaders.js:225)
    at loadNativeModule (VM50 helpers.js:35)

**Comment by sergiop38** [comment]
I resolved with this trick: 
`app.commandLine.appendSwitch('disable-features', 'CrossOriginOpenerPolicy')`

node v14
electron v13.1.6

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
