### ISSUE TITLE
[Bug]: "mainWindow.isMaximized()" always return false, in spite of using "mainWindow.maximize()"

### ISSUE THREAD

**Issue by jiqiangzhu** [electron/electron#28864]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

It can makes client window maximize when use command 'mainWindow.maximize();',and the result of 'mainWindow.isMaximized()' should be true.

### Actual Behavior

The result of 'mainWindow.isMaximized()' is false after I use command 'mainWindow.maximize();'

### Additional Information

/*main.js*/
const { app, BrowserWindow, ipcMain, globalShortcut, dialog } = require('electron');
const isDev = require('electron-is-dev')
let mainWindow;
// let mainWindowId;
process.env['ELECTRON_DISABLE_SECURITY_WARNINGS'] = 'true'

ipcMain.on("changeWinSize", function (event, args) {
  console.log("操作----------", args);
  if (mainWindow) {
    switch (args) {
      case "minimize": //最小化
        if (mainWindow.isMinimized()) {
          return;
        }
        mainWindow.minimize();
        break;
      case "close": 
        mainWindow.close();
        break;
      case "max": 
        mainWindow.maximize();
        break;
      case "restore":
        mainWindow.setContentSize(1024, 680);
        mainWindow.cen
        break;
      case "fixedOnTop":
        if (!mainWindow.isAlwaysOnTop()) {
          mainWindow.setAlwaysOnTop(true);
        } else {
          mainWindow.setAlwaysOnTop(false);
        }
        break;
      default:
        break;
    }

  }
});

ipcMain.on("openFolder", async (event, args) => { 
  let fileReturn = await dialog.showOpenDialog({ "title": "Choose Music DirPath", properties: ['openFile', 'openDirectory', 'showHiddenFiles', 'createDirectory ', 'multiSelections'], defaultPath: args })
  if (!fileReturn.canceled) {
    event.reply('asynchronous-reply', fileReturn)
  }
});

app.on('ready', () => {
  mainWindow = new BrowserWindow({
    width: 1024,
    height: 680,
    transparent: true,
    webPreferences: {
      nodeIntegration: true,
      enableRemoteModule: true,
      contextIsolation: false,
      webSecurity: false,
    },
    titleBarStyle: 'customButtonsOnHover',
    frame: false,
    resizable: true,
  })
  mainWindow.setMenu(null);
  const urlLocation = isDev ? 'http://localhost:3000' : 'dummyurl';
  mainWindow.loadURL(urlLocation);
  mainWindow.setMaximizable(true);
  mainWindow.maximize();
  console.log("isMaximized true or false------------", mainWindow.isMaximized());
})

if (isDev) { 
  app.whenReady().then(() => {
    const ret = globalShortcut.register('Alt+F12', () => {
      mainWindow.webContents.openDevTools();
    })

    if (!ret) {
      console.log('registration failed')
    }

    console.log(globalShortcut.isRegistered('Alt+F12'))
  })
}

**Comment by pushkin-** [comment]
does it work if the `isMaximized()` call happens on a `setTimeout`?

**Comment by mlaurencin** [comment]
@jiqiangzhu I attempted to isolate your issue by placing it in [this Fiddle gist](https://gist.github.com/b73b9363c41a1699b328d3d6e58e085e) and commented out the portions that were possibly not contributing. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Are you still seeing your problem when using the uncommented code in the gist?

If you are only seeing it occur when the commented code is used, could you please provide the additional code you use to send those events?

**Comment by jiqiangzhu** [comment]
> @jiqiangzhu I attempted to isolate your issue by placing it in [this Fiddle gist](https://gist.github.com/b73b9363c41a1699b328d3d6e58e085e) and commented out the portions that were possibly not contributing. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Are you still seeing your problem when using the uncommented code in the gist?
> 
> If not and you are only seeing it occur when the commented code is used, could you please provide the additional code you use to send those events?



> @jiqiangzhu I attempted to isolate your issue by placing it in [this Fiddle gist](https://gist.github.com/b73b9363c41a1699b328d3d6e58e085e) and commented out the portions that were possibly not contributing. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Are you still seeing your problem when using the uncommented code in the gist?
> 
> If not and you are only seeing it occur when the commented code is used, could you please provide the additional code you use to send those events?

**Comment by jiqiangzhu** [comment]
> > @jiqiangzhu I attempted to isolate your issue by placing it in [this Fiddle gist](https://gist.github.com/b73b9363c41a1699b328d3d6e58e085e) and commented out the portions that were possibly not contributing. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> > Are you still seeing your problem when using the uncommented code in the gist?
> > If not and you are only seeing it occur when the commented code is used, could you please provide the additional code you use to send those events?
> 
> > @jiqiangzhu I attempted to isolate your issue by placing it in [this Fiddle gist](https://gist.github.com/b73b9363c41a1699b328d3d6e58e085e) and commented out the portions that were possibly not contributing. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> > Are you still seeing your problem when using the uncommented code in the gist?
> > If not and you are only seeing it occur when the commented code is used, could you please provide the additional code you use to send those events?

It's Ok when I use your gist!

**Comment by jiqiangzhu** [comment]
> > @jiqiangzhu I attempted to isolate your issue by placing it in [this Fiddle gist](https://gist.github.com/b73b9363c41a1699b328d3d6e58e085e) and commented out the portions that were possibly not contributing. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> > Are you still seeing your problem when using the uncommented code in the gist?
> > If not and you are only seeing it occur when the commented code is used, could you please provide the additional code you use to send those events?
> 
> > @jiqiangzhu I attempted to isolate your issue by placing it in [this Fiddle gist](https://gist.github.com/b73b9363c41a1699b328d3d6e58e085e) and commented out the portions that were possibly not contributing. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> > Are you still seeing your problem when using the uncommented code in the gist?
> > If not and you are only seeing it occur when the commented code is used, could you please provide the additional code you use to send those events?

use "const urlLocation = isDev ? 'http://localhost:3000' : 'dummyurl';
  mainWindow.loadURL(urlLocation);" ,"mainWindow.isMaximized()" always return false

**Comment by jiqiangzhu** [comment]
> > @jiqiangzhu I attempted to isolate your issue by placing it in [this Fiddle gist](https://gist.github.com/b73b9363c41a1699b328d3d6e58e085e) and commented out the portions that were possibly not contributing. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> > Are you still seeing your problem when using the uncommented code in the gist?
> > If not and you are only seeing it occur when the commented code is used, could you please provide the additional code you use to send those events?
> 
> > @jiqiangzhu I attempted to isolate your issue by placing it in [this Fiddle gist](https://gist.github.com/b73b9363c41a1699b328d3d6e58e085e) and commented out the portions that were possibly not contributing. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> > Are you still seeing your problem when using the uncommented code in the gist?
> > If not and you are only seeing it occur when the commented code is used, could you please provide the additional code you use to send those events?

My git warehouse is "https://github.com/jiqiangzhu/KugouByReact.git"

**Comment by mlaurencin** [comment]
@jiqiangzhu Unfortunately even with [this updated gist](https://gist.github.com/mlaurencin/b73b9363c41a1699b328d3d6e58e085e), I am unable to reproduce the issue. I removed the use of the ternary operator to avoid issues caused by non-Electron elements (it has been split into two lines that can be commented and uncommented instead however).

If this code is not recreating your issue, would you be able to provide a standalone testcase with only the code needed to reproduce your issue? It looks like some of the code in your repository may not contribute to the issue, so creating a test without those lines can help to narrow down the problem.

**Comment by jiqiangzhu** [comment]
> @jiqiangzhu Unfortunately even with [this updated gist](https://gist.github.com/mlaurencin/b73b9363c41a1699b328d3d6e58e085e), I am unable to reproduce the issue. I removed the use of the ternary operator to avoid issues caused by non-Electron elements (it has been split into two lines that can be commented and uncommented instead however).
> 
> If this code is not recreating your issue, would you be able to provide a standalone testcase with only the code needed to reproduce your issue? It looks like some of the code in your repository may not contribute to the issue, so creating a test without those lines can help to narrow down the problem.

I got it ! It always return false when I set up window property transparent  true. Thank you so much for taughting me creating a test without those lines can help to narrow down the problem !

**Comment by bruceauyeung** [comment]
looks like this bug still exists.
electron version: 17.1.1 32bit
os:win7, win10
`mainWindow.isMaximized()` always return false, in spite of using `mainWindow.maximize()` if browserwindow was created with transparent=true and scale rate of  screen is greater than 100%
@codebytere
