### ISSUE TITLE
[Bug]: Electron builder zip url not working

### ISSUE THREAD

**Issue by mitmelon** [electron/electron#28871]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Windows

### Operating System Version

8.1

### What arch are you using?

x64

### Last Known Working Electron version

12.0.5

### Expected Behavior

Accurate bundling process with window distribution exe file in dist folder

### Actual Behavior

During electron bundling using electron builder  the downloading url=https://github.com/electron/electron/releases/download/v
2.0.5/electron-v12.0.5-win32-x64.zip size=83 MB parts=8 is not downloading.

I tried the download url directly on browser https://github.com/electron/electron/releases/download/v
2.0.5/electron-v12.0.5-win32-x64.zip but this url does not exist... Nothing is found on the link to download. Thats why the error is comming up...

This is a bug which should be corrected.

`   writing effective config  file=dist\builder-effective-config.yaml
   rebuilding native dependencies  dependencies=bufferutil@4.0.3 platform=win32
arch=x64
   rebuilding native dependency  name=bufferutil version=4.0.3
   packaging       platform=win32 arch=x64 electron=12.0.5 appOutDir=dist\win-un
packed
   Unpacking electron zip  zipPath=undefined
   downloading     url=https://github.com/electron/electron/releases/download/v1
2.0.5/electron-v12.0.5-win32-x64.zip size=83 MB parts=8
   retrying        attempt=1
   retrying        attempt=2
   retrying        attempt=3
  ? part download request failed with status code 403
github.com/develar/app-builder/pkg/download.(*Part).doRequest
        C:/Users/develar/Desktop/app-builder/app-builder/pkg/download/Part.go:12
6
github.com/develar/app-builder/pkg/download.(*Part).download
        C:/Users/develar/Desktop/app-builder/app-builder/pkg/download/Part.go:67

github.com/develar/app-builder/pkg/download.(*Downloader).DownloadResolved.func1
.1
        C:/Users/develar/Desktop/app-builder/app-builder/pkg/download/downloader
.go:155
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        C:/Users/develar/Desktop/app-builder/app-builder/pkg/util/async.go:68
runtime.goexit
        c:/go/src/runtime/asm_amd64.s:1374
  ? C:\xampp\htdocs\BFS\node_modules\app-builder-bin\win\x64\app-builder.exe exi
ted with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=

                                                     Error: C:\xampp\htdocs\BFS\
node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTR
ON_BUILDER_CANNOT_EXECUTE

                                                         at ChildProcess.<anonym
ous> (C:\xampp\htdocs\BFS\node_modules\builder-util\src\util.ts:243:14)

                                                         at Object.onceWrapper (
events.js:422:26)

                                                         at ChildProcess.emit (e
vents.js:315:20)

                                                         at maybeClose (internal
/child_process.js:1051:16)

                                                         at Process.ChildProcess
._handle.onexit (internal/child_process.js:287:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.`

**Comment by MarshallOfSound** [comment]
@mitmelon This is a bug in electron-builder not an issue on our side, It is trying to download an Electron 12.0.5 zip file from the 2.0.5 release (looks like some substring slicing issues).

**Comment by mitmelon** [comment]
Ooohhh... I see... Will have to pay a visit to electron builder then..  Thanks for the clearifications...
