### ISSUE TITLE
[Bug]: Disabling hardware acceleration causes scrollbars to be always displayed on macOS

### ISSUE THREAD

**Issue by KishanBagaria** [electron/electron#28875]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.3 – 14.0.0-nightly.20210426

### What operating system are you using?

macOS

### Operating System Version

macOS 11

### What arch are you using?

x64

### Expected Behavior

Scroll bar should disappear automatically

https://user-images.githubusercontent.com/1093313/116310724-00951480-a7c8-11eb-88e7-719b1632d459.mov

### Actual Behavior

Scroll bar doesn't disappear automatically

https://user-images.githubusercontent.com/1093313/116310772-0f7bc700-a7c8-11eb-959b-f93c76655943.mov

### Testcase Gist URL

https://gist.github.com/5177bd322c024b97eb7103bdb0fb994d

### Additional Information

<img width="780" alt="Screenshot 2021-04-28 at 2 19 24 AM" src="https://user-images.githubusercontent.com/1093313/116310855-28847800-a7c8-11eb-8e37-632f5e889a52.png">

"Show scroll bars" should be set to "Automatically based on mouse or trackpad"

**Comment by codebytere** [comment]
@KishanBagaria does this also happen if you disable it in Chrome proper? We basically just plumb directly to Chromium for this:

https://github.com/electron/electron/blob/dc7fa1d9f1ae3001b6863fb5c1a22220beae51ce/shell/browser/api/electron_api_app.cc#L1122-L1134

**Comment by KishanBagaria** [comment]
Ran `chromium --disable-gpu`, opened the index.html file and unfortunately yes, same issue with Chromium.

<img width="726" alt="Screenshot 2021-04-28 at 4 11 04 AM" src="https://user-images.githubusercontent.com/1093313/116321499-cc295480-a7d7-11eb-9a7a-8b2728085ceb.png">

Do you want me to file this on https://bugs.chromium.org/p/chromium/issues/entry?

**Comment by MarshallOfSound** [comment]
Yep, if you think this is a bug in Chromium you should raise on the upstream tracker.  Be aware it's possible this is currently working as intended and raising upstream doesn't mean they'll accept it as a valid bug 👍

**Comment by KishanBagaria** [comment]
Done: https://bugs.chromium.org/p/chromium/issues/detail?id=1203703
