### ISSUE TITLE
[Feature Request]: Show consistent + relevant information in the "About" Dialog - irrespective of OS

### ISSUE THREAD

**Issue by vraravam** [electron/electron#28879]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, when I run an electron-based app in Windows, this is the about dialog: 
![windows-ferdi-about](https://user-images.githubusercontent.com/69629/116334099-4961c300-a7f2-11eb-8af9-fd5a4f5207af.png)

Whereas in macOS, this is how it shows:
<img width="276" alt="Screen Shot 2021-04-28 at 7 00 11 AM" src="https://user-images.githubusercontent.com/69629/116334479-e91f5100-a7f2-11eb-86da-7d68bde0d419.png">

### Proposed Solution

Please show the following information in the about dialog:
1) app version
2) electron version
3) node version
4) architecture (x86 vs arm)
5) platform/os
6) app website

### Alternatives Considered

The information is present in the debug info, but that is not intuitive for a lay-user.

Other alternative would be for each app that builds on top of Electron to then have their own secondary about dialog (in settings or somewhere similar), where this information is exposed. If this is not consistent, it will not give a good user experience.

### Additional Information

Not sure what other additional information I can provide.

**Comment by MarshallOfSound** [comment]
The "about" dialog you say appears on linux/windows is not a core part of Electron, it is constructed by the app not by us.  Took a few seconds to find the relevant code in the app you came from: https://github.com/getferdi/ferdi/blob/develop/src/lib/Menu.js#L1023-L1028

The macOS about dialog is something built in to macOS and therefore supported via the Electron API.  You can configure what information appears in that panel with `setAboutPanelOptions` --> https://www.electronjs.org/docs/api/app#appsetaboutpaneloptionsoptions

There are also fallback implementations of the about panel for Windows and Linux available via `app.showAboutPanel()`
