### ISSUE TITLE
[Bug]: TRX withdraw error

### ISSUE THREAD

**Issue by Vidic88** [electron/electron#28886]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

2.8.1

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

I enter the adress to deposit to from Eidoo for TRX and transfer goes through

### Actual Behavior

As soon as I enter the adress in Eidoo, it says invalid adress / only for TRX, so I can't withdraw my TRX

**Comment by Prinzhorn** [comment]
> ### Electron Version
> 
> 2.8.1

Is this a typo? There has never been an Electron 2.8.1 and if there were, it would be very old and unsupported.

This sounds like a support question for Eidoo (https://eidoohelp.zendesk.com/hc/en-us) and not like a bug in Electron.
