### ISSUE TITLE
[Bug]: document.hasFocus() returns true for all windows opened on startup

### ISSUE THREAD

**Issue by bpasero** [electron/electron#28897]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

macOS

### Operating System Version

11.2.3

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

`document.hasFocus()` is only `true` for the window that has focus.

### Actual Behavior

Ever window reports `document.hasFocus()` to be `true` right after opening.

### Testcase Gist URL

https://gist.github.com/16e6fc829febd0cab115dfd0850a31be

**Comment by deepak1556** [comment]
It is a side-effect of https://github.com/electron/electron/pull/25292, where we put the `webContents` to focus after load url if it was not hidden on creation.
