### ISSUE TITLE
[Bug]: Debugging connection was closed. Reason: Render process gone.

### ISSUE THREAD

**Issue by RajuKale** [electron/electron#28896]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

2.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

When we have are trying to loading big size audio file getting this error. File size is almost 150MB.
While it is working for less than 100 MB files.
It should load the big size files as well.

### Actual Behavior

When we have are trying to loading big size audio file getting this error. File size is almost 150MB.
While it is working for less than 100 MB files.

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you’re still experiencing this issue in Electron 10.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by RajuKale** [comment]
Thanks for your reply.
I have updated the electron version from 2.0.2 to 12.0.1 but getting some errors.
Please let me know I also need to update the angular application as well ? As it is also using older version 2.
Can we have a live call so I can share my screen and show the issue.
Thanks in advanced.

**Comment by mlaurencin** [comment]
Would it be possible for you to make a standalone testcase with only the code from your Electron application necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.  

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

Unfortunately, we can only address issues related to Electron, and not Angular. So I am changing the label to `blocked/need-repro` label until a testcase is provided. After you make a testcase, please link to it in a follow-up comment.

**Comment by codebytere** [comment]
Closing as no response was provided. However, we can always re-open this should more information come to light.
