### ISSUE TITLE
[Bug]: globalShortcut won't register single quote or back quote correctly on different keyboard layouts (Windows 10)

### ISSUE THREAD

**Issue by iAbadia** [electron/electron#28900]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 2004

### What arch are you using?

x64

### Expected Behavior

When registering the back quote or single quote, the keystroke that triggers the event should be the same that was used to register it.

Ideally, the event would trigger when pressing the key that was registered only while using the keyboard layout that was being used when the key was registered. In other words, If I register back quote using UK layout and switch to US layout, the back quote should not trigger the event. 

### Actual Behavior

When I register the back quote (`) the event triggers when pressing the **back quote** using the **US layout**, it also triggers when pressing the **single quote** using the **UK layout**.

When I register the single quote (') the event triggers when pressing the **single quote** using the **US layout**, it does not trigger when pressing either the **single quote** or **back quote** using the UK layout.

### Testcase Gist URL

https://gist.github.com/iAbadia/88c01d9be1dc6fc9f4a32653e0a3b550

### Additional Information

This was found while using Terminus, a issue was filed there to follow this bug. After investigation I found the culprit was not Terminus but electron.

https://github.com/Eugeny/terminus/issues/3742

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.

**Comment by iAbadia** [comment]
Thanks for the explanation!

I've created this gist registering a Back Quote with globalShortcut to log a single string when pressed. You'll see the behaviour is undexpected, as described above.

https://gist.github.com/iAbadia/88c01d9be1dc6fc9f4a32653e0a3b550

**Comment by wongjustin99** [comment]
Noticing this with a JIS keyboard and the following keys: 

Ctrl+[
Ctrl+]
Ctrl+_
Ctrl+^

None of those are detected even though I am pressing them.

**Comment by mathieulj** [comment]
Using a slightly more complex gist, I seem to be seeing a much wider issue: https://gist.github.com/d00a4fe3fd457026504fde19748cfea7

In that gist, I bound all the non-alphabetic characters on an ANSI keyboard (using a modifier that ensures no conflicts with other apps). Switching to different layouts on a Win10 machine, I get swapped keys that can't be explained by the layout differences. Some of those seem to be trying to honour keyboard layouts whilst others seem to be 🤷.

```md
                            |                           event.code (key) that actually triggers it                           |
| globalShortcut binding    | En-US            | Fr-Ca            | Norwegian         | En-Uk              | German           |
| :------------------------ | :--------------- | :--------------- | :---------------- | :----------------- | :--------------- |
| CommandOrControl+Shift+-  | Minus (-)        | Minus (-)        | Slash (-)         | Minus (-)          | Slash (-)        |
| CommandOrControl+Shift+=  | Equal (=)        | Equal (=)        | Minus (+)         | Equal (=)          | BracketRight (+) |
| CommandOrControl+Shift+[  | BracketLeft ([)  | BracketLeft (^)  | Equal (\)         | BracketLeft ([)    | Minus (ß)        |
| CommandOrControl+Shift+]  | BracketRight (]) | BracketRight (¸) | BracketLeft (å)   | BracketRight (])   | Equal (´)        |
| CommandOrControl+Shift+\  | Backslash (\)    | Backslash (<)    | Backquote (|)     | IntlBackslash (\)  | Backquote (^)    |
| CommandOrControl+Shift+;  | Semicolon (;)    | Semicolon (;)    | BracketRight (¨)  | Semicolon (;)      | BracketLeft (ü)  |
| CommandOrControl+Shift+’  | Quote (')        | Backquote (#)    | Quote (æ)         | Backslash (#)      | Quote (ä)        |
| CommandOrControl+Shift+,  | Comma (,)        | Comma (,)        | Comma (,)         | Comma (,)          | Comma (,)        |
| CommandOrControl+Shift+.  | Period (.)       | Period (.)       | Period (.)        | Period (.)         | Period (.)       |
| CommandOrControl+Shift+/  | Slash (/)        | Slash (é)        | Backslash (')     | Slash (/)          | Backslash (#)    |
| CommandOrControl+Shift+`  | Backquote (`)    | Quote (`)        | Semicolon (ø)     | Quote (')          | Semicolon (ö)    |
```

**Comment by mathieulj** [comment]
This is a somewhat complex issue especially so because of cross platform internationalization. Other platforms (ex. macOS) don't have APIs available to bind keyboard layout specific keyboard events (ex. related https://github.com/electron/electron/issues/19747). Worse still, some keyboard layouts have "Dead" keys that don't produce a character on their own (they require a second keypress) and non ascii characters which chromium doesn't support.

**Comment by eric-imgtec** [comment]
Can you please reopen the issue and come up with a fix for the use cases that can be fixed? (non dead keys, on the OS that support it) and make some users happy. Isn't it better to have a few users happy rather than none?

Like the OP I could benefit from the fix that @mathieulj mentioned as I'm trying to use ``Ctrl+` `` hotkey in Tabby for a UK keyboard on Windows 11.

**Comment by mlaurencin** [comment]
@eric-imgtec Please open a new issue and include instructions for reproducing the problem. If you are experiencing the exact same problem, then you are free to link this issue in your additional information section.

A fix was not included in this thread, rather the broader scope of the issue was illustrated, so unfortunately it will still be difficult to resolve.
