### ISSUE TITLE
[Bug]: Web GL is not supported

### ISSUE THREAD

**Issue by qq273681448** [electron/electron#28947]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.0.0+

### What operating system are you using?

Windows

### Operating System Version

windows 7

### What arch are you using?

ia32

### Last Known Working Electron version

12.0.5

### Expected Behavior

Web GL is not supported

console error：Context missing

### Actual Behavior

Web GL is not supported

console error：Context missing

**Comment by matthijsgroen** [comment]
How can it not be supported? I am building a webgl app right now...

**Comment by miniak** [comment]
what does the chrome://gpu page show?

**Comment by miniak** [comment]
WebGL support is provided by Chromium, which has a GPU driver blacklist. You can try ignoring it `app.commandLine.appendSwitch('ignore-gpu-blacklist')`, however this can cause stability issues. Other than that there is nothing we can do about it being or not being supported on Electron side.
