### ISSUE TITLE
[Bug]: Electron doesn't start from automated startup script

### ISSUE THREAD

**Issue by sts-ryan-holton** [electron/electron#28950]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11

### What operating system are you using?

Other Linux

### Operating System Version

Raspbian

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

11

### Expected Behavior

I expect Electron to launch on start up after plugging in a custom sh script in my `rc.local` file

### Actual Behavior

Electron doesn't seem to start when executed from `rc.local` from a sh file, see attached:

My script doesn't run. I can verify that my rc local file is indeed running and my sh file is running, but Electron is never launched, what am I doing wrong?

- I've got a command to execute a script that runs in `rc.local` which is:
  - `sh '/home/pi/Desktop/cockpit-tv-monitor/start.sh'`

- The contents of `start.sh` is:

```
#!/bin/sh
# start-jammer.sh
# navigate to the home directory, then to this directory, then execute python script, then back home

cd /
cd home/pi/Desktop/cockpit-tv-monitor
echo "about to run npm run start" > /tmp/rc_test.txt
npm run start
```

I am getting the echo, but `npm run start` seems to never launch my electron app, and this command is essentially an alias which runs `electron .`

**Comment by Prinzhorn** [comment]
This sounds like an issue on your end and not like a bug in Electron. You can use other channels to get help: https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support

My guess is npm is not available in your script, depending on how it was installed.

```
echo `which npm` > /tmp/rc_test.txt
```

also try starting Electron directly

```
./node_modules/.bin/electron .
```

**Comment by MarshallOfSound** [comment]
Electron also won't start headlessly, if your script isn't running with an active display session it won't be able to start.  Closing as per above though, this isn't an issue with Electron rather an issue with your specific setup

**Comment by sts-ryan-holton** [comment]
@MarshallOfSound I'm not running Electron headlessly, it's connected to a monitor and is running Node JS 10.x and NPM 7.x on the Raspberry Pi 3, I'm also running Raspbian Full OS, meaning there is a GUI, so regardless of whether I have a monitor connected, this should still run.

I'll try the `./node_modules/.bin/electron .` and report back 👍

**Comment by sts-ryan-holton** [comment]
@Prinzhorn my `rc.local` after adding `echo `which npm` > /tmp/rc_test.txt` outputs `/usr/local/bin/npm` on startup, so it can access NPM just fine.

Also, adding `./node_modules/.bin/electron .` doesn't launch the script, I've even tried adding a `sleep 5` to my shell script to prevent it executing straight away.

My environment launches the application just fine if I manually run in my terminal either `npm run start`, `electron .` or `./node_modules/.bin/electron .`

What's the recommendation here?

**Comment by Prinzhorn** [comment]
Is there an error message? That'd be a great place to start

```
npm run start 2> /tmp/rc_test_err.txt
```

> What's the recommendation here?

Maybe you can find someone on Discord or one of the other support channels listed here https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support to help you debug this. Unless there is evidence that this is an Electron bug. If so then an error message would be a great start.
