### ISSUE TITLE
[Bug]: Image Caching Problems

### ISSUE THREAD

**Issue by AlanSean** [electron/electron#28959]
You can close it. Thank you

I achieved my goal by modifying the FILE protocol

protocol.interceptFileProtocol

**Comment by weiweiwei256** [comment]
> You can close it. Thank you
> 
> I achieved my goal by modifying the FILE protocol
> 
> protocol.interceptFileProtocol

Can you show the details of modifying thi FILE protocol?  I have the same problems.  thank you.

**Comment by AlanSean** [comment]
> > You can close it. Thank you
> > I achieved my goal by modifying the FILE protocol
> > protocol.interceptFileProtocol
> 
> Can you show the details of modifying thi FILE protocol? I have the same problems. thank you.


```
html
<img src="xxx.jpg?xxx=xxxx" />
```

```
protocol.ts
import { protocol } from 'electron';
export function setProtocol(): void {
  protocol.interceptFileProtocol('file', (req, callback) => {
    callback({
      url: encodeURI(req.url)
    });
  });
}

```
