### ISSUE TITLE
[Bug]: Tray tooltips on GNU, bugs, inconsistencies, a summary.

### ISSUE THREAD

**Issue by kroko** [electron/electron#28956]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Other Linux

### Operating System Version

Multiple latest LTS, please see below.

### What arch are you using?

x64

### Expected Behavior

`.setToolTip('MyNiceAppName')` method should produce tooltip on DEs that support it.

### Actual Behavior

App I'm working on is "Tray app"
 - uses `.setApplicationMenu(null)`

My observation is that on outmost setups tooltip shows up, but it contains package.json name not the name as set via `.setToolTip('MyNiceAppName')`. 

that is
- not `MyNiceAppName`,
- but `my-pkg-cryptic-name`

All setups below used AppImage which was integrated via [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher), x64.

- Kubuntu
  - 20.04.2 LTS Focal Fossa (**KDE Plasma 5**, X11) : **`my-pkg-cryptic-name`**
- Linux Mint
  - 20.1 Ulyssa Cinnamon (**Cinnamon**, X11) : **`My-pkg-cryptic-name`** (yes, sentence case)
  - 20.1 Ulyssa MATE (**MATE**, X11) : **no tooltip** (other tray services (network, sound, time widgets, etc) have tooltip)
- Xubuntu
  - 20.04.2 LTS Focal Fossa (**Xfce + Xfwm**, X11) : **`my-pkg-cryptic-name`, and on newline one word - `icon`** (other tray services (network, sound, time widgets, etc) have tooltip, in one line, no additional random txt)
- Ubuntu
  - 20.04.2 LTS Focal Fossa (**GNOME 3**, X11) : **no tooltip, as expected** (because gnome, no items in tray have tooltips)
  - 18.04.5 LTS Bionic Beaver (**GNOME 3**, X11) : **no tooltip, as expected** ( -- || --)
  - 16.04.7 LTS Xenial Xerus (**Unity 7**, X11) : **no tooltip, as expected** (unity 7 does not have tooltips in tray, and this is depr anyways)

### Additional Information

Related to this https://github.com/electron/electron/issues/28131, but I tried generalising it in this ticket.

At some point I will also try some other extra DEs. And also non Debian distros, but IMHO results will match these, as it is about DEs / shells.

**Comment by kroko** [comment]
One vey of avoiding `my-pkg-cryptic-name` and having `MyNiceAppName` is to set

```js
const pkg = require(path.resolve(__dirname, 'package.json'));
// ...

  linux: {
    // https://github.com/electron/electron/issues/28956
    executableName: pkg.productName,
   // ...
  }
```
in electron builder config.

That at least produces a static tooltip that is meaningful. If some does not need dynamic tooltips and the tooltip can be just one word without spaces (spaces in exec name imho is evil 😄 ) it's a quick workaround.

**Comment by Kilian** [comment]
You can also specify a `productName` that includes spaces, capitals etc in your package.json and my understanding is that it will use that when available :)

**Comment by kroko** [comment]
@Kilian although we really are in second decade of 21st century I'd suggest not using spaces in *NIX executable names 😄

**Comment by Vovan-VE** [comment]
I suppose it should be here.
![tray-icons-tooltip 3](https://user-images.githubusercontent.com/1166581/151306582-d1f9b595-1ea5-4d02-a260-a47c39894ef3.gif)

Apps on the picture in order: Space, Mailspring, Skype, Slack, Discord. They are all displaying literally "icon" tooltip for years since a tooltip was introduced. The tooltip is surely never displayed anything else.

Ubuntu 20.04, XFCE 4.14.
In previous Ubuntu 18.04 + XFCE I don't remember exactly: either it was the same, or there was no tooltip.

**Comment by Vovan-VE** [comment]
Finally, it's now much better on XFCE (4.16). Thank you, people!

![image](https://user-images.githubusercontent.com/1166581/190963324-ebcbf423-560d-4292-bc7e-b9cbfc309393.png)
