### ISSUE TITLE
[Bug]: Add sandbox recommendations to the security document

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#28955]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.6

Should the [security document](https://github.com/electron/electron/blob/master/docs/tutorial/security.md) mention turning on sandboxing? It currently doesn't.

**Comment by erickzhao** [comment]
Makes sense to me, especially referring to https://github.com/electron/electron/issues/23506
