### ISSUE TITLE
[Bug]: BrowserWindow Height and Width validity check issue when other than int is given as height or width

### ISSUE THREAD

**Issue by RutvikRana** [electron/electron#28954]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

new BrowserWindow(height:145.5,width:200.5)

It Should Create Window With 145 or 146 height and 200 or 201 width.

### Actual Behavior

new BrowserWindow(height:145.5,width:200.5)

But It Show Bigger Screen ( Maybe Default Or Maybe 1455 and 2005 size IDK)

I Know Doc Says It's Integer But There Should Be Some Kind Of Ceil or Floor Should Happen In This Case By Electron Itself.

**Comment by sofianguy** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone test case with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
Closing as no response was provided. However, we can always re-open this should more information come to light.
