### ISSUE TITLE
[Bug]: Memory leak with asar

### ISSUE THREAD

**Issue by TimoshN** [electron/electron#28962]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

7, 8, 9, 10, 11, 12, 13

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2

### What arch are you using?

ia32

### Last Known Working Electron version

6.1.12

### Expected Behavior

freed memory on close BrowserWindow.

### Actual Behavior

main process memory usage constantly grow up and never freed.

### Additional Information

My app have one always active BrowserWindow and perioditically open new BrowserWindow. After some times window close automatically. Main process open alot of file descriptors to app.asar. About 300 for 1 hour of app usage ( creating new BrowserWindow every 30sec and close it after 2min). and use ~300mb.

**Comment by pushkin-** [comment]
Dupe of [this](https://github.com/electron/electron/issues/21586)?

**Comment by TimoshN** [comment]
I am not sure. With asar memory leak far more noticeble then without asar

**Comment by gpetrov** [comment]
Any progress on this?

We see double memory usage just by running from ASAR. Not really related to browserWindows being open and closed.
The double memory usage is for both and the main and the renderer processes.
There must be something fundamentally wrong with asar and requiring modules from it. Probably the buffer memory never gets cleared.

This is quite an issue for us and we are considering dumping the asar usage just because of it.

**Comment by dsanders11** [comment]
This should be fixed in versions v12.0.11 and v13.1.1 by #29293. @TimoshN, can you try one of those versions and confirm the leak is fixed?

**Comment by MarshallOfSound** [comment]
Edit on the above, it went out in v13.1.2

**Comment by dsanders11** [comment]
@MarshallOfSound, I was going off of the release notes for v13.1.1, I guess those are off?

**Comment by TimoshN** [comment]
sadly, but no.

**Comment by dsanders11** [comment]
@TimoshN, apparently it didn't make it into v13.1.1, sorry about that. Could you try v13.1.2?

**Comment by TimoshN** [comment]
@dsanders11 Yes. v13.1.2 fix it. Works like a charm now!

**Comment by dsanders11** [comment]
Thanks for confirming.
