### ISSUE TITLE
[Bug]: SyntaxError

### ISSUE THREAD

**Issue by GingkathFox** [electron/electron#28960]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.6

### What operating system are you using?

macOS

### Operating System Version

macOS Mojave 10.14.6

### What arch are you using?

x64

### Expected Behavior

Electron works properly, and no issues are found.

### Actual Behavior

My app doesn't work because of this internal error:

```
SyntaxError: Unexpected identifier
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:89)
    at electron/js2c/renderer_init.js:117
    at electron/js2c/renderer_init.js:101
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:105)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)
```

**Comment by codebytere** [comment]
Closing as this appears to be bug in your app, and not with Electron itself. If you believe this to be a bug in Electron, please submit an issue with full reproducible steps that demonstrate this to be an issue with Electron.
