### ISSUE TITLE
[Bug]: Freezes when I get a notification

### ISSUE THREAD

**Issue by ChromaCat248** [electron/electron#28964]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.6-1

### What operating system are you using?

Other Linux

### Operating System Version

output of uname -a: "Linux Henry 5.11.16-arch1-1 #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000 x86_64 GNU/Linux"

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

1. Get a notification
2. App continues to run fine

### Actual Behavior

1. Get a notification
2. App freezes, requiring a force quit

App still runs, but I am unable to interact with it (e.g. typing in a textbox or clicking a button)

### Additional Information

Only tested with Discord and Element

**Comment by codebytere** [comment]
@ChromaCat248 please submit this issue to Discord/Element, since as of now this is not a demonstrable issue with Electron itself. If they feel it to be our issue, please submit a new issue with full reproducible steps so that we may begin to triage.
