### ISSUE TITLE
[Bug]: Unable to detect Cmd+C/V/X

### ISSUE THREAD

**Issue by will-stone** [electron/electron#28966]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0-beta.18

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

13.0.0-beta.13

### Expected Behavior

The <kbd>cmd + c</kbd> keyboard event is captured. For example, in the provided gist, this is logged to the console.

### Actual Behavior

<kbd>cmd + c</kbd> does not log anything. Nor does <kbd>cmd + x</kbd> or <kbd>cmd + v</kbd>. However it seems all other keyboard events are logged, e.g. <kbd>cmd + b</kbd>

### Testcase Gist URL

https://gist.github.com/will-stone/b0baae4c6db206026316e09c83d7451f

### Additional Information

I just wanted to say thank you very much to the Electron team. It's a great project and I've really enjoyed the 4+ years I've been using it. Keep up the good work 🙂

**Comment by VerteDinde** [comment]
Hey @will-stone, thanks for reporting this issue! (and for the kind words! 🙂)

I think the issue that you're hitting may be fixed upstream in Chromium, but needs to be brought down to our next beta. I can repro your issue on beta.13, but can no longer reproduce it in the latest Chrome roll here: https://github.com/electron/electron/pull/28660 These changes were introduced in beta.14, which matches with what you reported here.

I'll ping you directly as soon as these Chrome changes are merged in and we cut a new beta with those changes merged in. I'll keep this issue open until that happens and you confirm the new beta fixes your issue 🙇‍♀️ 

Thanks so much again for reporting! We really appreciate it.

**Comment by VerteDinde** [comment]
@will-stone 13.0.0-beta.21 was just released! https://github.com/electron/electron/releases/tag/v13.0.0-beta.21

Could you let me know if this fixes the issue for you?

**Comment by will-stone** [comment]
That did indeed fix it. Thanks @VerteDinde 😄
