### ISSUE TITLE
Drop event firing after DragEnd in <webview>

### ISSUE THREAD

**Issue by tylerstalder** [electron/electron#2897]
With frequent drag and drop events I'm seeing drop events fire after associated dragEnd event fires. Currently this is in a react app, using react-dnd but I've been able to reproduce the issue when running this jsfiddle in an Electron webview. I haven't been able to reproduce in Chrome or in Electron itself. To cause it on my current 15" macbook I need to very quickly move elements, but on slower machines it can happen on the first drag and drop sequence.

http://jsfiddle.net/phmccqhk/

Steps:
1. Open fiddle in an Electron webview (I'm doing this by forcing the route in our app) `window.location.href = 'http://jsfiddle.net/phmccqhk/'`
2. Open Dev Console
3. Quickly and repeatedly drag `test` divs from left to right into red square.
4. Watch log for `Drag End -> Drop -> Drop -> Drag End` sequence

Versions:
Electron: 0.33.1
Mac OSX: 10.10.5

Seems like it could be related to:
https://github.com/atom/electron/issues/1276
https://code.google.com/p/chromium/issues/detail?id=412373

**Comment by zcbenz** [comment]
> Seems like it could be related to:
> #1276
> https://code.google.com/p/chromium/issues/detail?id=412373

Yeah it is an upstream Chromium bug.

**Comment by mkscrg** [comment]
Here's a standalone repro for this issue: <https://gist.github.com/mkscrg/707c5c0d3d3e12e03baa>

@zcbenz do you think this is the same Chromium issue ([412373](https://code.google.com/p/chromium/issues/detail?id=412373))? If not we'll report upstream!

**Comment by zcbenz** [comment]
Yeah it should be the same one.

**Comment by javan** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=412373 is fixed and it's working correctly for me in Electron 1.7. Maybe be fixed in 1.6* too. Can probably close this issue now.
