### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'user' of undefined     at __puppeteer_evaluation_script__:1:61

### ISSUE THREAD

**Issue by STRAGE05** [electron/electron#28987]
I use
SimpleInstaBot and this error pops up. What kind of error could it be? How to fix? 
Here is a screenshot of the error - https://user-images.githubusercontent.com/71008701/116987434-bb954480-acd7-11eb-9264-b00627a049ad.png

**Comment by Prinzhorn** [comment]
This is the issue tracker for the Electron framework. See https://github.com/mifi/SimpleInstaBot/

**Comment by MarshallOfSound** [comment]
Closing as per above
