### ISSUE TITLE
[Bug]: No resource with given URL found, DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by arthurpankiewicz** [electron/electron#28993]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^11.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.2.3

### What arch are you using?

x64

### Expected Behavior

- location.reload() or electron reload shortcut to work in prod
- sourcemap to load in prod

### Actual Behavior

For production (mac dmg) builds of my electron app, I am unable to trigger `location.reload()`, connect to `redux-dev-tools`, and the sourcemap fails to load.

When the app is loaded, the console warns that it cannot load the sourcemap:
![Screen Shot 2021-05-04 at 3 56 09 PM](https://user-images.githubusercontent.com/9858612/117014604-40408c80-acf1-11eb-8c94-965e39b1d0d1.png)

The `index.html` in the sources says the resource cannot be loaded:
![Screen Shot 2021-05-04 at 3 56 57 PM](https://user-images.githubusercontent.com/9858612/117014725-5bab9780-acf1-11eb-957e-9a800cac51fd.png)

Executing `location.reload()` causes the app to crash with a white screen and no console logs (this command works in electron dev builds).

My electron code is contained in `electron/index.electron.js` and the relevant snippets are:
```js
const options = {
    icon: join(__dirname, '../src/common/assets/app-icons/png/256x256.png'),
    webPreferences: {
        nodeIntegration: false,
        preload: join(__dirname, "preload.js")
    }
};
// ...
mainWindow = new BrowserWindow({
  ...options,
  ...windowOptions
});
// ...    
const startUrl = process.env.ELECTRON_START_URL || url.format({
    pathname: "file://../build/index.html"
});
// ...
mainWindow.loadURL(startUrl);
```

The relevant `package.json` snippets:
```json
"homepage": "./",
"scripts": {
  "electron-build:mac": "rm -rf dist/ && yarn build && electron-builder -m",
},
"build": {
    "appId": "appId",
    "extends": null,
    "files": [
      "dist/**/*",
      "build/**/*",
      "node_modules/**/*",
      "src/common/assets/**/*",
      "public/*",
      "electron/**/*"
    ],
    "directories": {
      "buildResources": "./src/common/assets"
    }
  },
"devDependencies": {
  "electron": "^11.3.0",
  "electron-builder": "^22.9.1"
```

The only thing I can confirm in dev is that running `location.reload()` successfully reloads the app.

Thanks :)

### Additional Information

The same problems exist for linux and windows builds

**Comment by bnb** [comment]
@FStefanni hi, your gist doesn't currently work because of dependency resolution. If you're still interested, if you (or someone else) could update it, that'd be great.

**Comment by FStefanni** [comment]
hi,

sorry, too much time passed. No more using electron at the moment: it was for work so until I have to use it again, I have no time to spend on this.

Regards.
