### ISSUE TITLE
[Bug]: window.navigator.languages & accept-language header only show one default language

### ISSUE THREAD

**Issue by Kilian** [electron/electron#28992]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

ubuntu 18.04

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

When a user has multiple languages installed, browsers will show `navigator.languages` as an array with multiple entries, for example `['en-US', 'en']` and use both in the `Accept-Language` header: `Accept-Language: en-US,en;q=0.5`

I would expect Electron to use the same set of languages in both locations.

### Actual Behavior

Only the singular first default language is used even if the OS supports multiple languages.

### Testcase Gist URL

https://gist.github.com/ed7c5e67cc37d6826e81cad2c7a27534

### Additional Information

This gist gets `window.navigator.languages` and prints it. For most OS this would be a list containing both `['en-US', 'en']` but only `en-US` is shown.

**Comment by Prinzhorn** [comment]
Related https://github.com/electron/electron/pull/15532

> However, this behaviour has changed, (it also follows the HTML spec). The language preferences are obtained through the preferences list that chrome maintains. The user has to set these language preferences manually, through the settings menu.
For an electron app, there's no way to set these preferences. Besides, being a desktop app, it seems reasonable for the app to follow the users desktop language preferences.

This is what I'm seeing in Chromium:

![Selection_877](https://user-images.githubusercontent.com/679144/117031588-037c9180-ad01-11eb-9068-67f96edb639d.png)

This does not come the OS level, it is entirely configured inside Chromium and differs from what I have configured in Firefox.

**Comment by Kilian** [comment]
Both Firefox and Chrome definitely take their initial values from the OS-supported level of languages, or at least throw them in the mix. 

Case in point: I'm gonna assume you didn't add both "English (United States)" _and_ "English" yourself. Those get installed together at an OS level, and your browser took that as a basis.

**Comment by dsanders11** [comment]
@Kilian, this seems to work as expected on macOS. If I add another language to my 'Preferred languages' in `System Preferences -> Language & Region`, it shows up with your Fiddle gist.

Since you specifically mention Ubuntu, it looks like the [Electron hook for `GetPreferredLanguages` in Linux](https://github.com/electron/electron/blob/44491b023ac2653538b7ac36bb73f3085a938666/shell/common/language_util_linux.cc#L11-L15) is a no-op, and has a comment about no API existing to use. That looks like the spot to fix it if you have an implementation to use.

**Comment by Kilian** [comment]
@dsanders11 Oh I have to check that. I have a video by a customer that has this exact same problem on MacOS, but maybe it got fixed in the mean time.
