### ISSUE TITLE
Less Lag

### ISSUE THREAD

**Issue by KalbokoHD** [electron/electron#28990]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I've been playing it for awhile but whenever I press anything I feel like it's so delayed like if I try to move my tetrimino
it's would be delayed

### Proposed Solution

Lower the Graphics just like in tetris friends there's low graphics

### Alternatives Considered

N/A

### Additional Information

N/A

**Comment by codebytere** [comment]
Closing as this is not an actionable enhancement for us. If you have specific reproducible instances where you think Electron itself is causing lag that you can demonstrate with a gist or repository we're happy to reopen and continue to triage this.
