### ISSUE TITLE
[Bug]: Native drag and drop icon cannot use SVG icon

### ISSUE THREAD

**Issue by kimlimjustin** [electron/electron#29007]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21.04 x86_64 5.11.0-16-generic

### What arch are you using?

x64

### Expected Behavior

SVG Icon could also be loaded too

### Actual Behavior

![image](https://user-images.githubusercontent.com/61906684/117102503-ae915780-ada2-11eb-9359-1e7a92a9a5e9.png)

**Comment by MarshallOfSound** [comment]
Duplicate #9642
