### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by abhishekmatta999** [electron/electron#29012]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.0.0

### What operating system are you using?

macOS

### Operating System Version

macOs catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

I'm using 
electron: 11.0.0
electron-updater: 4.3.5
electron-builder: 22.10.5

So electron builder quitAndInstall() method is installing the new version but it is not relaunching the app
Here's my code:

`autoUpdater.on('update-downloaded', (info) => {
  dialogOpts.message = 'New Version of application is available'
  dialogOpts.detail = `Update available: New version ${info.version} is available`
  dialog.showMessageBox(dialogOpts, (response) => {
    if (response === 0) {
      autoUpdater.quitAndInstall()
    }
  })
})`

Whenever I'm manually closes the app the version is there but it is not automatically relaunching the app. Any suggestions to this?

### Actual Behavior

autoUpdater.quitAndInstall() - should install and relaunch the new app

**Comment by MarshallOfSound** [comment]
`electron-updater` and `electron-builder` are not supported, sanctioned or maintained by the Electron team.  Issues with `electron-updater` should be raised on their repository, using the builtin `electron.autoUpdater` is the officially support auto update solution
