### ISSUE TITLE
[Bug]: In case of Multiple browserViews only one of them is interactable

### ISSUE THREAD

**Issue by pOoOf** [electron/electron#29015]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^11.0.1

### What operating system are you using?

macOS

### Operating System Version

MacOs Big Sur, 11.0.1

### What arch are you using?

x64

### Last Known Working Electron version

None, tried in 12.0.0 also

### Expected Behavior

I have added two BrowserView to BrowserWindow using addBrowserView method on BrowserWindow's instance

Ideally, both the browser views should be interactable but I can focus and enter text in only one of the browserviews
Other browserview won't event respond to click events.

### Actual Behavior

![Screenshot 2021-05-05 at 7 58 01 PM](https://user-images.githubusercontent.com/5319600/117157419-36478800-addc-11eb-9e44-7a2d54afc092.png)

Browserview in the left is working fine, but on the right, it is frozen, nothing happens on clicking

### Repo URL to reproduce this issue

https://github.com/pOoOf/electron-test

### Instructions to start server
This works with node 12
```
nvm use 12
yarn
yarn start
```

**Comment by Kilian** [comment]
The left browserview is at x: 0, y:0 and works and the right browserview is offset and doesnt work, which makes me thing this is a duplicate/fixed by https://github.com/electron/electron/pull/28984

**Comment by pOoOf** [comment]
Hey @Kilian i tried the new version of electron containing the fix(v13.0.0-beta.22)

But now, the app is crashing immediately after it opens
this is the repo if you want to repro this issue
```
https://github.com/pOoOf/electron-test
```
Let me know if I am doing anything wrong.

**Comment by Kilian** [comment]
@pOoOf Can you make an isolated example in https://www.electronjs.org/fiddle ?

**Comment by pOoOf** [comment]
@Kilian thanks for pointing me to fiddle, it was really easy to experiment with different electron versions to check in which version code is working and found that in `v12.0.0`, the code is working fine but in v13.0.0-beta.20, the app crashes as soon as it starts
Although my problem is solved, I have added the code to a gist just so you can debug
here is the gist url.

https://gist.github.com/2c2a31d03637cad81b6a309b27e856c0

let me know if there is any problem in accessing the gist.
Thanks
