### ISSUE TITLE
How does the main process communicate with the page mainWindow.loadURL(load_url)  ? This page is a remote link 

### ISSUE THREAD

**Issue by glk-hll** [electron/electron#29038]
How does the main process interact with load_ URL, this page communication, this load_ URL is a remote link. I can't use ipcrender in this remote link page.

The remote link page is installed with electron, and the source code is as follows:
```javascript
 const ipcRenderer = require('electron').ipcRenderer
```
It will prompt "fs.existsSync is not a function".

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by glk-hll** [comment]
OK，thanks ! I didn't find the Chinese community. What should I do?

**Comment by 569202812** [comment]
> 好，谢谢 ！我没有找到华人社区。我该怎么办？

我是中国的，加下联系方式讨论吧
