### ISSUE TITLE
[Feature Request]: Windows ARM32 build

### ISSUE THREAD

**Issue by Qiangong2** [electron/electron#29040]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Certain older devices such as the Surface RT, raspberry pi 2 under iot core, and 4GB windows arm64 laptops perform poorly with electron apps (or not at all)

### Proposed Solution

A Windows ARM32 Build of electron would perform better on these devices

### Alternatives Considered

The only alternative really is to upgrade the device, which isn't always an option

### Additional Information

This would help immensely with getting electron apps usable on lower end WoA devices.

**Comment by miniak** [comment]
Surface RT does not support Win32 apps. Windows IoT Core only supports UWP apps. Also Chromium only supports ARM64.
