### ISSUE TITLE
[Bug]: Slow IO performance in Electron

### ISSUE THREAD

**Issue by seb-mtl** [electron/electron#29051]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

8.5.5

### What operating system are you using?

macOS

### Operating System Version

MacOS Big Sur 11.3.1 (20E241)

### What arch are you using?

x64

### Expected Behavior

Given is a custom function called `writeFiles`, which executes `fs.copyFile` for around 500 files. The function takes around 4 seconds to execute. 

```typescript 
function writeFiles(files: string[]) {
     return performFileAccessCheck(files)
     .then(() => ... copy files ... );
}
```

### Actual Behavior

If the same function is executed by Electron in the BrowserWindow context, the function takes more than 60 seconds. I profiled both, the execution under node-cli and within Electron. Below are the results. As you can see from the Electron profile, there are thousands of `splitPath`, `nextTick`, `copyFileOut` executions.

## node-cli sample

Partial snapshot of the profile of node. A clean call-stack with the expected function calls

![image](https://user-images.githubusercontent.com/12844423/117373794-f3e48080-ae99-11eb-8197-236cd50e83cc.png)

## Electron

In node however, the function `performFileAccessCheck` takes much longer and contains way more sub-calls.

![image](https://user-images.githubusercontent.com/12844423/117373814-fcd55200-ae99-11eb-9867-0dbd6d6ac1a1.png)

Close-up of the Electron profile:

![image](https://user-images.githubusercontent.com/12844423/117373829-03fc6000-ae9a-11eb-89f9-5454f4c102b1.png)

**Comment by MarshallOfSound** [comment]
@seb-mtl Are you copying files out of the apps ASAR file here? Can you provide a code sample that reproduces the slow down you're seeing?

Also a shot in the dark, but can you update your Electron benchmark to use `require('original-fs')` instead of `require('fs')`.  Assuming your FS logic isn't doing anything ASAR related using the unpatched `original-fs` module should directly match Node.js perf

**Comment by seb-mtl** [comment]
@MarshallOfSound All file operations are executed on standard files on the volume, nothing is read from the ASAR file. I haven't heard of `'original-fs'` before. Are there some docs available for what the patched `fs` module in Electron does? It certainly sounds very promising, so I have to make some changes in my code and will try it out and report, otherwise I will setup a MVCE repo

**Comment by MarshallOfSound** [comment]
No our patches to `fs` are literally just for asar support 👍

**Comment by seb-mtl** [comment]
It fixed it, you saved my week, thanks so much! The function is around 5-10 times faster. Is this behaviour, or `original-fs` mentioned somewhere in the docs? I couldn't find anything

**Comment by MarshallOfSound** [comment]
Raised a docs issue, closing this one out
