### ISSUE TITLE
[Feature Request]: Hope sending electron classes will copy values and prototype by contextBridge

### ISSUE THREAD

**Issue by canvascat** [electron/electron#29055]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

preload.js
```js
const { contextBridge, desktopCapturer } = require('electron');
contextBridge.exposeInMainWorld('desktopCapturer ', desktopCapturer );
```
renderer.js
```js
(async function() {
  const sources = await desktopCapturer.getSources({ types: ['window', 'screen'] });
  console.log(sources.map(source => source.thumbnail.getSize()));
})();
```
Uncaught (in promise) Error: Illegal invocation: Function must be called on an object of type NativeImage.
![image](https://user-images.githubusercontent.com/31235016/117415470-ef2bd500-af4a-11eb-8257-971da120c92d.png)

### Proposed Solution

Hope sending electron classes will copy values and prototype.

### Alternatives Considered

get size in preload.js
```js
async function getDisplaySources() {
  const sources = await desktopCapturer.getSources({ types: ['window', 'screen'] });
  console.log(sources);
  return sources.map(({ thumbnail, name, id }) => ({ name, id, size: thumbnail.getSize() }))
}
contextBridge.exposeInMainWorld('getDisplaySources', getDisplaySources);
```

### Additional Information

https://www.electronjs.org/docs/api/context-bridge#api-functions

> Keys must be supported using only "Simple" types in this table. Values must be supported in this table. Prototype modifications are dropped. Sending custom classes will copy values but not the prototype.

**Comment by MarshallOfSound** [comment]
> Hope sending electron classes will copy values and prototype.

> Keys must be supported using only "Simple" types in this table. Values must be supported in this table. Prototype modifications are dropped. Sending custom classes will copy values but not the prototype.

As documented this is a technical limitation and is impossible to achieve in any reasonable way, you should implement your own serialization / cloning logic for custom classes if you want to send them over the bridge / over IPC.
