### ISSUE TITLE
[Bug]: White Corners on Window using Vibrancy

### ISSUE THREAD

**Issue by TurnipTotSoftware** [electron/electron#29061]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0-beta.20

### What operating system are you using?

macOS

### Operating System Version

11.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Naturally, the window's borders should be rounded, with nothing obscure protruding amongst them--And they should stay that way _after_ maximization, like so:
![Screen Shot 2021-05-07 at 2 48 02 PM](https://user-images.githubusercontent.com/83843298/117511979-8d1ba180-af43-11eb-99f6-5163877619f4.png)

### Actual Behavior

But, for some weird reason, after (and while) the window is maximized, weird looking white corners appear on every point of the window's border radius...
![Screen Shot 2021-05-07 at 2 49 47 PM](https://user-images.githubusercontent.com/83843298/117512201-074c2600-af44-11eb-9f20-3017207cbea5.png)

### Testcase Gist URL

https://gist.github.com/TurnipTotSoftware/74db97bee9b29183006fd1204cfff746

### Additional Information

This glitch also happens after my Mac sleeps for a bit...
Hopefully this problem is an easy fix!

Good day👍

**Comment by codebytere** [comment]
@TurnipTotSoftware opened a PR that should ameliorate the issue!
