### ISSUE TITLE
[Feature Request]: The app module has events to listen for when reinstalling

### ISSUE THREAD

**Issue by FE-linmu** [electron/electron#29063]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The electron application internally depends on the.exe file, and both the electron application and the .exe file are in process.APP module has no event to monitor the exit of the current Electron application if it is installed again without upgrading.This causes the .exe file to fail to exit properly.

### Proposed Solution

The APP module can listen in 'quit' or other events.When listening, kill the.exe file in the process.

### Alternatives Considered

The user creates an empty BrowserWindow and kills the.exe file when new BrowserWindow close event is triggered.

### Additional Information

My English is not very good, I am looking forward to your early reply.

**Comment by nornagon** [comment]
Sorry, I'm not sure I quite understand what you're getting at. There's already an `app.on('quit')` event: https://www.electronjs.org/docs/api/app#event-quit, is that enough for your use case?

**Comment by MarshallOfSound** [comment]
As the reporter has not responded to the request for additional information this issue will be closed.  If further information can be provided at some point in the future, comment on this issue with the requested information and if appropriate the issue will be reopened.
