### ISSUE TITLE
[Bug]: Zoom in doesn't work in Windows

### ISSUE THREAD

**Issue by kimlimjustin** [electron/electron#29065]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home Single Language 10.0.18363 N/A Build 18363

### What arch are you using?

x64

### Expected Behavior

`Ctrl` + `+` Could zoom in electron app

### Actual Behavior

`Ctrl` + `+` Could not zoom in electron app wherareas `Ctrl` + `-` could zoom out electron app

**Comment by kimlimjustin** [comment]
Update: not working on Ubuntu 21.04 too!

**Comment by jkleinsc** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by kimlimjustin** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance! Your help is appreciated.

https://gist.github.com/kimlimjustin/c7711271d66a434c8b49e379c0a7e588

This bug occurs on basic electron structure too!

**Comment by Araxeus** [comment]
"Zoom In" is `'Ctrl'+'Shift'+'='` as you can clearly see in the menu (and it always was)

![image](https://user-images.githubusercontent.com/78568641/118064613-04b65a00-b3a4-11eb-8463-e88e825c12ed.png)

**Comment by kimlimjustin** [comment]
> "Zoom In" is `'Ctrl'+'Shift'+'='` as you can clearly see in the menu (and it always was)
> 
> ![image](https://user-images.githubusercontent.com/78568641/118064613-04b65a00-b3a4-11eb-8463-e88e825c12ed.png)
> 
> > and yeah it works

Eh, okay, my bad, I got it wrongly, thanks!

**Comment by SandeshGyawali** [comment]
My app just zoomed out itself to the maximum limit it could. I tried zooming in with each shortcut keys they provided, nothing worked. Then I tried shortcut key to reset the zoom with 'ctrl'+'0' and it seems to work. Zooming in did not work, but reset zoom worked.  
![Screenshot 2024-08-01 111541](https://github.com/user-attachments/assets/416a531e-415a-4d63-b843-1ae9b69e9f44)
