### ISSUE TITLE
[Bug]: Autoplay policy is not respected inside webviews

### ISSUE THREAD

**Issue by Jelmerro** [electron/electron#29064]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0-beta.20 and older

### What operating system are you using?

Other Linux

### Operating System Version

Fedora, Ubuntu, Mint

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

I expect the autoplay policy to also work inside webviews.

### Actual Behavior

It doesn't work. I think the webpreferences on the browserwindow should be enough to set this, but even if it's somehow not enough, setting them on the webview directly definitely should, but doesn't. Video is autoplayed in the webivew regardless of the configured policy. It does work in iframes and in the browserwindow anywhere else, just not inside webviews.

### Testcase Gist URL

https://gist.github.com/8ffa3b630b3215d4f72a0065fde84908

**Comment by nornagon** [comment]
I think this is intended behavior: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/webaudio/audio_context.cc;l=195-196;drc=176246919ed7b6884c79b3eb7d83f4c3ae88dbdb

setting it to `document-user-activation-required` works.

**Comment by Jelmerro** [comment]
Could you be more clear what makes you think that the current default works? Currently it's now set to ALWAYS autoplay inside frames, instead of being able to control it with this setting. Is there any other way to prevent autoplay inside webviews? Because as I tried to make clear in the original post, the setting doesn't seem to affect the playback inside webviews, even if you set it to disabled.

**Comment by Jelmerro** [comment]
@nornagon I have updated the fiddle https://gist.github.com/8ffa3b630b3215d4f72a0065fde84908 with the value you suggested, and as I already mentioned in the parent issue, it doesn't work. I don't recommend assuming stuff like this works, just because the code says so, and it doesn't help the Electron project to simply close issues like this based on an assumption. Hopefully this issue can be reopened, or a different way could be suggested to make this work for webviews.

**Comment by nornagon** [comment]
@Jelmerro I tested this before making the comment. Your fiddle doesn't display the same behavior because you have written `autoplaypolicy` instead of `autoplayPolicy`, which I corrected when I was testing.

**Comment by Jelmerro** [comment]
Of course it's something silly like that, thanks for clarifying this.
