### ISSUE TITLE
[Bug]: Preload dynamic loading error

### ISSUE THREAD

**Issue by crcms** [electron/electron#29070]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu: 20.04

### What arch are you using?

x64

### Last Known Working Electron version

12.0.5

### Expected Behavior

Error in dynamic require module package in Preload.js, errorMessage: Cannot find module

### Actual Behavior

I have a need, I want to have a unified preload public file, and each window has its own specific preload processing, so I need to call a specific preload based on the opened window. My current approach is to provide a public preload.js , And then load another specific preload script according to specific startup parameters, example:
```js
const config = {
        'name': 'markdown',
        'file': path.join('file://',__dirname,'../plugins/markdown/index.html'),
        'preload': path.join(__dirname,'../plugins/markdown/markdown.js'),
}
const win = this.windows.create(config.name,{
    show: true,
    webPreferences: {
        preload: path.join(__dirname,'main_preload.js'),
        // Here, the preload script required by the current window is passed through process.argv
        additionalArguments: [`--preload=${config.preload}`,`--plugin=${config.name}`],
    }
})
```

// mian_preload.js
```js
// Some global settings
const plugin = {
    hideWindow() {
        ipcRenderer.send('hideWindow')
    },
    showWindow() {
        ipcRenderer.send('showWindow')
    }
}
contextBridge.exposeInMainWorld(
    'api',
    {
        plugin: plugin,
    }
)

// ... something

// Independent setting loading
let preload: string
let pluginName: string
process.argv.forEach((val, index) => {
    if (val.indexOf(`--preload`) > -1) {
        preload = val.split(`=`)[1]
    } else if (val.indexOf(`--plugin`) > -1) {
        pluginName = val.split(`=`)[1]
    }
})

if (preload) {
    // Note: At this time, in the require() function, if it is a preload variable, it will cause the load to be invalid
    // But if it is a manually entered string path, it can be executed correctly

    // 1. effective
    // let result = require(`../plugins/markdown/markdown.js`)(new Plugin())

   // 2. invalid
    let result = (preload: string) => {
        return require(preload)(new Plugin())
    }

    console.log(result(preload))
}

```
Error Example:
```text
VM75 renderer_init.js:93 Unable to load preload script: /home/Develop/code/javascript/el/el/dist_electron/preload.js
(anonymous) @ VM75 renderer_init.js:93
VM75 renderer_init.js:93 Error: Cannot find module '/home/Develop/code/javascript/el/el/plugins/markdown/markdown.js'
    at webpackEmptyContext (kernel_sync:2)
    at result (preload.ts:85)
    at eval (preload.ts:87)
    at Module../src/kernel/preload.ts (VM76 preload.js:108)
    at __webpack_require__ (VM76 preload.js:20)
    at eval (preload.ts:1)
    at Object.0 (VM76 preload.js:119)
    at __webpack_require__ (VM76 preload.js:20)
    at VM76 preload.js:84
    at Object.<anonymous> (VM76 preload.js:87)
```

Expand the console error message, in main_preload.js after webpack parsing
```text
    let result = (preload) => {
        return __webpack_require__("./src/kernel sync recursive")(preload)(new Plugin());
    };
    console.log(result(preload));
```

I also found some other solutions, such as using session for preloads
[#14012](https://github.com/electron/electron/issues/14012)
But session does not solve my current difficulties, what I need is session sharing

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
