### ISSUE TITLE
[Bug]: unity hub 不显示托盘图标，并且出现状态栏，不能在官网通过unity hub来安装

### ISSUE THREAD

**Issue by BoyceLig** [electron/electron#29078]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

国外版最新

### What operating system are you using?

Windows

### Operating System Version

win10  21h2

### What arch are you using?

x64

### Last Known Working Electron version

0

### Expected Behavior

重启好多次 不管用，打开后显示状态栏，从官网下载unity，点击unity hub安装也不管用。托盘状态栏没有hub图标。

![image](https://user-images.githubusercontent.com/49801599/117625015-2945e280-b1a8-11eb-993e-f6165d066e6a.png)

### Actual Behavior

打开软件，没有弹窗，再打开一次，弹出窗口。

**Comment by codebytere** [comment]
Please feel free to report this to Unity - this is not a demonstrable problem with Electron itself.
