### ISSUE TITLE
[Bug]: Linux webContents print silent not working Electron 12.0.0

### ISSUE THREAD

**Issue by tomaspiaggio** [electron/electron#29074]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Centos 8

### What arch are you using?

x64

### Expected Behavior

`win.webContents.print` should print a non blank page when configured in silent mode in linux.

### Actual Behavior

`win.webContents.print` doesn't print anything.

### Testcase Gist URL

https://gist.github.com/tomaspiaggio/0c0d259d88256b81794f6f1430b3e260

### Additional Information

I've encountered this problem both on Ubuntu 18.04 and Centos 8. It works both on Windows 10 and macOS 10.15.7. 

The printer I'm using is a Brother QL-800 (thermal label printer, 62mm x 100mm). The OSs have the correct drivers, and the printer is set to default. I've tried setting the device name manually on the print options unsuccessfully.

**What's the problem?**

The `win.webContents.print` does not work on linux when configured on silent mode. 

I've replicated the problem on two other printers (another QL-800, and a QL-700)

**Why do I think that this is an electron bug?**

- When I set silent to false, it works
- Printing test prints directly on the printer works fine
- Print to pdf works
- `window.print` works 
- behaviour changes between linus and windows/macos

On previous versions (11.1.1), the printer inconsistently printed blank pages, which threw me off even more than this. 

Please do tell me if I'm doing anything wrong, or if you can't replicate the problem. 

Thank you in advance.

**Comment by tomaspiaggio** [comment]
For anyone experiencing the same problem on linux, I wrote a quick workaround as I have a close deadline. However, I think this should be patched.

Disregard the callback hell, it's only a minimal demonstration for people with the same issue.

```typescript
import {unlink, writeFile} from "fs";
import path from "path";
import {randomBytes} from "crypto";
import {execFile} from "child_process";
import {app, WebContents} from "electron";

async print(webContents: WebContents): Promise<void> {
   // setting pdf size for correct print layout
   const pdfBuffer = await webContents.printToPdf({
      pageSize: {
         width: 62000,
         height: 100000
      }
   });

   // creating a random name for a temp file
   const randomName = randomBytes('16').toString('hex')
   const tmpFilePath = path.join(app.getPath('temp'), `${randomName}.pdf`);

   return new Promise<void>((resolve, reject) => {
      // writing the newly generated pdf to the file system
      writeFile(tmpFilePath, pdfBuffer, err => {
         if(err) reject(err);
         else {
            // printing the file using the linux print command "lp"
            // Write your own arguments on the following list. These were mine.
            execFile('lp', [tmpFilePath, '-o', 'media=62mm', '-d', 'Brother_QL_800'], (error, stdout) => {
               unlink(tmpFilePath); // fire and forget: won't throw error if deletion is not successful
               if(error) reject(error);
               else resolve();
            });
         }
      });
   })
}
```

This should also work on mac BTW.

Hope it helps someone.

**Comment by codebytere** [comment]
Duplicate https://github.com/electron/electron/issues/29334
