### ISSUE TITLE
[Feature Request]: Support Google Meet screen sharing extension

### ISSUE THREAD

**Issue by rimonhanna** [electron/electron#29081]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.x - 12.x

### What operating system are you using?

macOS

### Operating System Version

macOS 11.3

### What arch are you using?

x64

### Last Known Working Electron version

8.x

### Expected Behavior

Google Meet screen sharing to work when the website is loaded in an electron wrapper

### Actual Behavior

Google Meet just shows an error that my browser doesn't support screen sharing

So apparently the below chrome extension is needed for Google meet screen sharing to work, screen sharing used to work on older versions of electron <= 8.x because it used to use chrome instead of the bare bones chromium which included the extension, I tried loading this extension in my electron project, but it turns out electron doesn't support all the extension APIs needed for this to work :/

https://github.com/chromium/chromium/tree/master/chrome/browser/resources/hangout_services

**Comment by anonrig** [comment]
If you want to support Google Meet, I recommend just changing the session user agent for the meet.google.com domain to Safari. It would be much easier, and much safer to just add Google-owned extensions to preinstalled ones.

**Comment by MarshallOfSound** [comment]
Electron 12 is no longer supported and therefore this issue is no longer relevant on the latest Electron releases

**Comment by virtualsapiens** [comment]
Is there any plan to address this in the roadmap?
