### ISSUE TITLE
[Bug]:  PDF containing hyperlinks don't work when clicking on them

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#29091]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

The link should be opened in the current window.

### Actual Behavior

Nothing happens.

### Testcase Gist URL

https://gist.github.com/80a9108e271ca83c82cc4a8772e371fc

### Additional Information

When the PDF is loaded, try to click on the link (https://www.youtube.com/watch?v=KFPtxCDUPqs&feature=youtu.be)

**Comment by nornagon** [comment]
This functionality in the pdf extension depends on the `chrome.tabs` API, which we don't yet fully support.

Ref https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/pdf/browser_api.js;l=93?q=navigateInCurrentTab
Ref https://github.com/electron/electron/pull/27917

**Comment by richpixel** [comment]
Is there a way to have the link open in a new window? Thanks.
