### ISSUE TITLE
[Bug]: Electron crash when call qt gui

### ISSUE THREAD

**Issue by HuangDeFa** [electron/electron#29112]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

macOS

### Operating System Version

macOs  Majave 10.14.6 

### What arch are you using?

x64

### Expected Behavior

I would like to use the ffi-napi to call a dylib that builded by qt , then invoke the lib method should open a dialog(qt gui). 

The code like:

JS part
`
const {Library:FFLib} = require('ffi-napi')

const lib = FFLib("resource/vendor/libdyLibDemo.dylib",{
         "test":['void',[]],
     })
lib.test()
`

QT part

`
#include <QApplication>
#ifdef __cplusplus
extern "C" {
void test(){
    char *argv[0] = {};
    int argc = 1;
    qDebug() << "start checkLib";
    QApplication a(argc, argv);
    QDialog dl;
    dl.setWindowTitle("Test Win");
    dl.show();
    dl.raise();
    dl.exec();
}

#ifdef __cplusplus
}
#endif

`****

### Actual Behavior

when use ffi-napi to call the lib method ,the native qt dialog can show but  electron seems  unresponsive , the menus disappear except the app name and the paste operation can not work for input element , then  click the app name in menu bar it will crash or  unresponsive 

### Additional Information

As I test that , once run ffi-napi to invoke dylib method which in native qt part create QApplication (
the code like
`void test(){
   QApplication a(argc,argv);
}`
),  in electron main process will make crash. 

If someone hit this case , please kindly comment the solution , thanks advance.

**Comment by jkleinsc** [comment]
Thanks for reaching out!

Given the warning from [ffi-napi](https://www.npmjs.com/package/ffi-napi):
```WARNING: node-ffi-napi assumes you know what you're doing. You can pretty easily create situations where you will segfault the interpreter and unless you've got C debugger skills, you probably won't know what's going on.```,  you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
