### ISSUE TITLE
[Bug]: Auto updater consumes 100% percent CPU when waiting on user password

### ISSUE THREAD

**Issue by tmoschou** [electron/electron#29119]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.6

### What operating system are you using?

macOS

### Operating System Version

Big Slur 11.3.1

### What arch are you using?

x64

### Expected Behavior

I have several apps that use electron (Slack, Draw.io, Visual Studio Code, Atom), every time there is an update, a dialog pops asking for admin/sudo password to install. The update dialog should *not* consume 100% CPU. 

### Actual Behavior

The app process runs at 100 percent CPU while waiting for user input confirmation. This happens quite frequently as I use many electron app that have frequent updates, and the high CPU happens for extended periods of time as I am not always present at my computer when the auto update pop up happens.

### Additional Information

This appears to be a problem with an underlying dependency on [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac) that Electron uses however it would appear that library is no longer maintained - See https://github.com/Squirrel/Squirrel.Mac/issues/256#issue-750706358.

There is also a related issue in Squirrel, and comment by jspahrsummers (original author I believe), that he has not worked on with the code base in 6+ years and no longer familiar with it - See  https://github.com/Squirrel/Squirrel.Mac/issues/247#issuecomment-757210176 

An example of an update popup dialog below:
![Screen Shot 2021-05-12 at 5 35 36 pm](https://user-images.githubusercontent.com/5567550/117940700-7e205f00-b348-11eb-8520-9985ce154ef4.png)

Below a screenshot of `htop` showing Atom running at 100%.
![Screen Shot 2021-05-12 at 5 47 49 pm](https://user-images.githubusercontent.com/5567550/117942582-5c27dc00-b34a-11eb-9cf7-397930c7e4cd.png)

Below is the output from `sample 9096` showing a profile of Atom
[Atom_2021-05-12_174109_EbSY.sample.txt](https://github.com/electron/electron/files/6464575/Atom_2021-05-12_174109_EbSY.sample.txt)

Other related issues:
  - https://github.com/microsoft/vscode/issues/95534

**Comment by codesimplicity** [comment]
Just to confirm that I've seen this for various application on various Macs: Slack, WhatsApp, Epic Games.
As mentioned in the VS Code issue, a workaround is to `chown` the application but this obviously has security implications!
