### ISSUE TITLE
[Bug]: webview's DOM operations do not execute when the webview is out of the viewport

### ISSUE THREAD

**Issue by praneetrohida** [electron/electron#29113]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

macOS

### Operating System Version

11.2.3

### What arch are you using?

x64

### Last Known Working Electron version

5.0.13

### Expected Behavior

Whenever a webview is loaded but not inside the viewport, DOM operations triggered inside the webview should work as expected.
We have a list of webviews in a scrollable container. The DOM operation we are performing is window.scrollTo(). The operation is triggered using IPC set up in the preload script.

### Actual Behavior

The IPC event is received immediately by all the webivews, but DOM operations performed in the handler do not get executed for the webviews that are out of the viewport. They all are executed together when those webviews are brought into the viewport.

### Testcase Gist URL

https://github.com/praneetrohida/electron-webview-dom-events-issue

### Additional Information

I noticed the same thing happening with webview.capturePage()
The promise returned by the capturePage() function does not resolve until the webview is brought into the viewport by scrolling down.

In the example, notice that when clicked on the Scroll to End button, only the first webview scrolls initially. The rest of the webviews scroll when the viewport is scrolled and they are brought into the viewport.

This bug was initially reported for Electron 8 [here](https://github.com/electron/electron/issues/22720)

**Comment by nornagon** [comment]
Does `backgroundThrottling` affect this behavior?
