### ISSUE TITLE
[Bug]: Electron 12: socket immediately closed after connection

### ISSUE THREAD

**Issue by andeb91** [electron/electron#29124]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Build 19042

### What arch are you using?

x64

### Last Known Working Electron version

11.4.5

### Expected Behavior

Once I call connect on a net.Socket to connect to existing named pipe, it remains connected until the creator of named pipe doesn't close it.

### Actual Behavior

Once I call connect on a net.Socket to connect to existing named pipe, it immediately end and close the connection also if the creator of named pipe doesn't close it.

**Comment by jkleinsc** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by andeb91** [comment]
After investigating over it all night, I apologize for opening this issue but is not directly related to Electron itself but it depends on Node.js. I would like to explain the solution if someone other will encounter this problem.
Upgrading Electron, also need to upgrade Node.js;  Electron 11.4.5 uses Node 12.x and not setting the option 'allowHalfOpen' on net.Socket creation has not the same effect that making the same thing on Node 14.x used in Electron 12.0.6.
So by default  'allowHalfOpen' is set to false in both Node versions but in 14.x once the reader reads once, the socket has been closed. To avoid this this option must be set to true.

**Comment by jedwards1211** [comment]
@andeb91 is the need to use `allowHalfOpen: true` for windows named pipes documented anywhere?
