### ISSUE TITLE
[Bug]: Notification highlight of panel icon does not work for Signal in Wayland

### ISSUE THREAD

**Issue by physkets** [electron/electron#29176]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux kernel version 5.12.3

### What arch are you using?

x64

### Expected Behavior

The Signal desktop application that uses electron recently updated to v12, and so allows using the Wayland back-end in linux, by setting the options: `--enable-features=UseOzonePlatform --ozone-platform=wayland`.

When using the X11 back-end, new messages would result in the icon in the panel/task-bar to light-up with an orange tinge.

### Actual Behavior

New messages or notifications do not result in the icon getting an orange tinge.

Also reported here:
https://github.com/signalapp/Signal-Desktop/issues/3411#issuecomment-840392341

**Comment by vially** [comment]
According to https://github.com/swaywm/sway/issues/3375#issuecomment-451713653 Wayland doesn't support window urgency (which is what was being used in X11/XWayland to highlight apps in the task-bar).

So unless GNOME/Mutter and/or KDE/Plasma already provide a mechanism for implementing this *for native Wayland apps*, it may not be possible to fix this in Electron until support lands on the compositor side first.

**Comment by physkets** [comment]
Okay, I've opened a new issue at their end:  
https://gitlab.freedesktop.org/wayland/wayland/-/issues/209

**Comment by physkets** [comment]
According to the closing comment on that issue:

> Some compositors may implement it via the new xdg-activation protocol.

And this is the tracking issue for the implementation of `xdg-activation` in KDE Plasma:  
https://invent.kde.org/plasma/kwin/-/issues/39
And from the same link, it would seem that GNOME already has support for it.

I am unsure if applications have to do anything different in order to use it.

**Comment by physkets** [comment]
Bump.

**Comment by paolomainardi** [comment]
Bump

**Comment by littlewu2508** [comment]
Same issue here
