### ISSUE TITLE
[Bug]: Google Drive does not load inside webviews

### ISSUE THREAD

**Issue by praneetrohida** [electron/electron#29189]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.6

### What operating system are you using?

macOS

### Operating System Version

11.2

### What arch are you using?

x64

### Expected Behavior

When loading https://drive.google.com inside a webview, the Google Drive home page should be visible

### Actual Behavior

The webview is blank and reloading the webview does nothing

### Testcase Gist URL

https://gist.github.com/e474113b345cc6d8ae5cdf5bf1b536b7

### Additional Information

In our app, reloading the webview actually crashes the whole app when drive.google.com is loaded in the webview. I could not reproduce the crashing behavior in the gist; but still, the bug that the URL doesn't load is reproducible

**Comment by nornagon** [comment]
Bisected to https://github.com/electron/electron/compare/v10.0.0-beta.2...v10.0.0-beta.3.

It looks like the webview content is still _loading_, it's just not _painting_. #29919 seems related.

**Comment by canvas104** [comment]
`app.commandLine.appendSwitch('disable-features', 'CrossOriginOpenerPolicy');` can solve
