### ISSUE TITLE
[Question] Intercept Response Body Electron

### ISSUE THREAD

**Issue by Stanley-GF** [electron/electron#29192]
I'm searching to intercept response body / response text using Electron. 
Example: 

```js
// My Request Interceptor,
....onHeaderReceived(..., {

    const responseBody = details.responseText;
    console.log(responseBody); 

});
```

And I will get the response of the request (in my console)
```json
{
 "userid":1929192192,
 "username":"Stanley",
 "courses_count":19,
 "teachers_count": 12
}
```
I searched in the documentation and I didn't found. 

Can somebody help me?

Regards
- Stan

PS: I asked on stackoverflow and nobody answer me

**Comment by akoskm** [comment]
Hi @Stanley-GF, have you found a solution to this?
