### ISSUE TITLE
Security Issue : nghttp2 dependency appeared as vulnerability on protecode with CVSS => 10

### ISSUE THREAD

**Issue by moulinierf** [electron/electron#29205]
When we package an electron App with Electron Builder,
Electron Builder retrieves the electron binaries 
![Capture d’écran 2021-05-18 151206](https://user-images.githubusercontent.com/39991826/118657122-7a2e8a00-b7eb-11eb-88e7-206a84f1f513.png)
 and when check the electron.exe generated with protcode 2020.12-1 
 protcode detects a vulnerability with the version of nghttp2
![Capture d’écran 2021-05-18 152614](https://user-images.githubusercontent.com/39991826/118659287-756ad580-b7ed-11eb-858b-358fe19f54be.png)
After investigation it seems that this dependency is present in two electron dependencies and the vulnerable version is 1.34.0 or 1.36.0
![Capture d’écran 2021-05-18 151224](https://user-images.githubusercontent.com/39991826/118659711-db575d00-b7ed-11eb-970e-129bd17493e3.png)
this dependency seems to be retrieve from the module dugite
![Capture d’écran 2021-05-18 152758](https://user-images.githubusercontent.com/39991826/118660568-9aac1380-b7ee-11eb-9dd3-c11bef7ed015.png)

So in this state, we can't deliver any application following protecode result needed with our build workflow.
Is it possible to have an electron binaries with a version of nghttp2 updated.

Regards

**Comment by nornagon** [comment]
Electron 12 ships with nghttp2 v1.41.0.
