### ISSUE TITLE
[Bug]: http2 can cause SIGPIPE on client close

### ISSUE THREAD

**Issue by codebytere** [electron/electron#29206]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

master

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu

### What arch are you using?

x64

### Last Known Working Electron version

11.4.6

### Expected Behavior

When I create a http2 server, do nothing, and close it, the child process exits cleanly.

### Actual Behavior

The spawned process exits with a `null` status code as a result of a SIGPIPE.

### Testcase Gist URL

https://gist.github.com/codebytere/8a8586d5c58399f23f9398ce763ee218

### Additional Information

Caused by https://github.com/nodejs/node/pull/30854 - though what specifically in there i'm not yet sure.

This also _only_ happens on Linux.

**Comment by nornagon** [comment]
It seems like this is an upstream bug...? Should this be reported against nodejs/node?
