### ISSUE TITLE
[Doc Error]: the sample code in the "Electron - BrowserView" Chinese documentation was mistranslated

### ISSUE THREAD

**Issue by linying1991** [electron/electron#29224]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hello, the sample code in the "Electron - BrowserView" Chinese documentation was mistranslated, but I don't have permission to change it, could you please confirm and correct it? (The content is machine translated)
https://www.electronjs.org/docs/api/browser-view#%E7%A4%BA%E4%BE%8B

# error (now)
![QQ截图20210519091225](https://user-images.githubusercontent.com/38310238/118742176-769a1200-b882-11eb-885e-8c883bdb0644.png)
# correct
![QQ截图20210519091743](https://user-images.githubusercontent.com/38310238/118742502-1bb4ea80-b883-11eb-86e9-54aa65d8115a.png)

### Proposed Solution

Need to be handled by the administrator

### Alternatives Considered

none

### Additional Information

none

**Comment by Prinzhorn** [comment]
> but I don't have permission to change it

There should be a button "Improve this doc" (on the English version) on every documentation page. It will link to the markdown here https://github.com/electron/electron/blob/master/docs/api/browser-view.md
There is an edit button. You can edit the markdown and then submit a pull-request to the Electron team so that they can merge your changes.

![Selection_888](https://user-images.githubusercontent.com/679144/118808732-18812500-b8aa-11eb-8a10-ead1109ac352.png)

![Selection_889](https://user-images.githubusercontent.com/679144/118808749-1ae37f00-b8aa-11eb-9c92-8b5739f7f14d.png)

**Comment by Prinzhorn** [comment]
Other languages are actually in a different repo https://github.com/electron/i18n/blob/master/content/zh-CN/docs/api/browser-view.md

So this could be kept open as a feature request to properly link the "Improve this doc" button for other languages.

**Comment by linying1991** [comment]
I use Crowdin for translating documents.
But the part in the screenshot (code example) cannot be modified
![Snipaste_2021-05-19_22-32-37](https://user-images.githubusercontent.com/38310238/118831581-78032300-b8f2-11eb-87d0-18b62807bebb.png)
@Prinzhorn

**Comment by Prinzhorn** [comment]
I recommend you report that to the https://github.com/electron/i18n repo. It looks like maybe it was possible to edit code blocks at some point and now it isn't anymore but this code block is broken now.

**Comment by linying1991** [comment]
okay, thank you very much!
