### ISSUE TITLE
[Bug]: A white box is shown on Twitter when app is minimized while software keyboard is up

### ISSUE THREAD

**Issue by dalegg** [electron/electron#29238]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

1. On a touch-capable Windows Desktop device, install Twitter from the store
2. Tap into the username field (or any other edit control) to invoke the software keyboard
3. Minimize Twitter (this should put focus back on the desktop and cause the SIP to dismiss)
4. Restore Twitter
Expected: Full UI is visible

### Actual Behavior

There is a white rectangle occupying the part of Twitter where the software keyboard was when Twitter was last open.

### Additional Information

I've investigated this from the Windows side. The software keyboard sends events to the foreground application when it shows and hides with occlusion information. Windows.UI.ViewManagement.InputPane or Windows.UI.ViewManagement.CoreInputView are the APIs used. However, when the application is minimized and in the background, it won't receive these events. This white rectangle that is drawn on the app needs to be cleared when the viewport changes.

**Comment by zcbenz** [comment]
@dalegg It is possible that Chromium did not correctly handle the related events, but it is also possible that Twitter is manually handling the software keyboard events and made some mistakes. So before debugging the bug, I think we should do more experiments:

1. Do other Electron apps in Windows store have this issue?
2. Does `electron https://twitter.com` have this issue?
3. Could Twitter team make a minimal app to reproduce this issue? (If the Twitter team can help.)

**Comment by dalegg** [comment]
Thanks for looking at this @zcbenz! I could repro this with Discord, Teams, Spotify, Twitter, Instagram, Skype which led me to believe this was an Electron issue. Teams has since fixed this issue for their app. 

I just checked electron twitter.com and this does NOT have the bug. Does that indicate the issue is in some other component?

**Comment by zcbenz** [comment]
Thanks for testing, it does look very likely an Electron/Chromium issue.

Can you also try if the standalone versions of those apps work correctly? I wonder if the problem only happens when the app is packaged for Windows store.

**Comment by dalegg** [comment]
The standalone versions of the apps are resized and/or repositioned when the software keyboard shows, so there is no white rectangle. 

Do you think you could point me to where I might start investigating a fix? And secondly, what is the best way to test the fix? Do I build a minimal app that will repro the bug, fix the electron/chromium change, and then rebuild the app using the new version of electron?

**Comment by zcbenz** [comment]
Before looking into this bug, I think you have to build a minimal app to reproduce it, otherwise there is no way to know whether the fix works. Also this bug may only happen when the app runs as AppX package, so you might want to take a look at https://github.com/felixrieseberg/electron-windows-store when making the minimal app.

The software keyboard code in Chromium is:
https://source.chromium.org/chromium/chromium/src/+/main:ui/base/ime/win/on_screen_keyboard_display_manager_input_pane.h

So after having a way to reproduce the bug, you can build Electron from source code and then start debugging the code.
