### ISSUE TITLE
[Bug]: Full Screen not recognized from maximized window

### ISSUE THREAD

**Issue by Klak031** [electron/electron#29239]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10 10.0.19042 Build 19042

### What arch are you using?

x64

### Expected Behavior

I have function that compare screen size to window size and when window is not maximized everything works fine.
### Actual Behavior

When you go full screen (F11) from maximized state, window is 16px smaller in width and height and is not recognized as full screen. When a window is not maximized for example and I go full screen my window outer size is equal to my screen size 2560 x 1440, but when a window is maximized, and I go full screen my window size is 2544 x 1424 and is not recognized as full screen. 

### Additional Information

I am using react 17.0.2 with electron

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
