### ISSUE TITLE
Windows Error: webContents.print(): Invalid deviceName provided!

### ISSUE THREAD

**Issue by sujiewen** [electron/electron#29258]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5,11.3.0,12.0.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

12.0.7

### Expected Behavior

Window Set printer dynamically

code:

    let printCon = { silent: true, printBackground: false, ...printOptions }
    log.log('url = ' + strUrl + '\n printCon=' + JSON.stringify(printCon))

    try {
      // did-finish-load
      printWindow.webContents.on('did-finish-load', () => {
        log.log('did-finish-load')
        printWindow.webContents.print(
            printCon,
          (success, failureReason) => {
            log.log('success=' + success + ' failureReason =' + failureReason)
            if (callback) {
              callback(success ? null : failureReason)
            }
          }
        )
      })

### Actual Behavior

Windows Error: webContents.print(): Invalid deviceName provided!
mac is working

![截屏2021-05-20 下午4 22 17](https://user-images.githubusercontent.com/1973318/118950086-725a1b80-b98c-11eb-8764-e13b7a41b018.png)

### Additional Information

code:

    let printCon = { silent: true, printBackground: false, ...printOptions }
    log.log('url = ' + strUrl + '\n printCon=' + JSON.stringify(printCon))

    try {
      // did-finish-load
      printWindow.webContents.on('did-finish-load', () => {
        log.log('did-finish-load')
        printWindow.webContents.print(
            printCon,
          (success, failureReason) => {
            log.log('success=' + success + ' failureReason =' + failureReason)
            if (callback) {
              callback(success ? null : failureReason)
            }
          }
        )
      })

**Comment by kerattila** [comment]
I can confirm, v15.x is also affected.
