### ISSUE TITLE
[Bug]: Inline style not working

### ISSUE THREAD

**Issue by kimlimjustin** [electron/electron#29257]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21.04 x86_64 5.11.0-16-generic

### What arch are you using?

x64

### Expected Behavior

All style applied using inline style works fine.

### Actual Behavior

Styles applied using inline style not working.

### Testcase Gist URL

https://gist.github.com/kimlimjustin/43d85a59dfd7d61354500a453b4743e6

### Additional Information

The style works if apply using inspect element

**Comment by nornagon** [comment]
This is because of the default content-security-policy in Fiddle. Removing the `<meta>` tags makes it work again.

This is expected behavior.
