### ISSUE TITLE
[Bug]: node and globals not available in iframes when nodeIntegrationInSubFrames is enabled, in electron 12.0.8+

### ISSUE THREAD

**Issue by gpetrov** [electron/electron#29259]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.8+

### What operating system are you using?

Windows

### Operating System Version

WIndows 10

### What arch are you using?

x64

### Last Known Working Electron version

12.0.7

### Expected Behavior

Node is no longer available in iframes when nodeIntegrationInSubFrames is available.
`process` and `require` should be available as globals

This happens in Electron 12.0.8 and up.
Works all fine in Electron 12.0.7

probably related to https://github.com/electron/electron/pull/29093

@codebytere 

### Actual Behavior

`process` and `require` are no longer available as globals

**Comment by gpetrov** [comment]
Any progress or confirmation on this @codebytere ?
Is it an intentional change or a bug?

It does have a pretty big impact on our code base, so we have to know if we have to rewrite everything or wait for fix as we are stuck now on 12.0.7 because of this.

**Comment by gpetrov** [comment]
@codebytere  after a lot of debugging, discovered the problem!

Seems that reading the `iframe.contentWindow` before the iframe load event, causes the iframe to not load node.
This started from Electron 12.0.8+

So this is the troublesome code:

```js
iframe.src = "iframe.html";

//Add to dom - now the iframe starts loading
document.body.appendChild(iframe);

//if reading the contentWindow before the iframe load event - node is not loaded in the iframe!
frameWindow = iframe.contentWindow;
```

Here is a demo project showing the problem. if you disable `frameWindow = iframe.contentWindow;` by commenting it out then it all works fine

[iframe_node_bug.zip](https://github.com/electron/electron/files/6681213/iframe_node_bug.zip)

**Comment by codebytere** [comment]
@gpetrov yes this is intended behavior now - the way this code was written previously caused illegal access errors in V8 itself, which could also create side effects. it's specific, though, to setting the src for the iframe later - from the original PR body:

> Fixes an issue where illegal access error would be thrown by the V8 isolate in some circumstances where an iframe was loaded and its source set later when Node.js integration is enabled in subframes. This was happening because if an iframe is created and a source is not set, the iframe loads about:blank and creates a script context for the same. We don't want to create a Node.js environment here because if the src is later set, the JS necessary to do that triggers illegal access errors when the initial about:blank Node.js environment is cleaned up.

Avoiding this being the case should ameliorate associated issues.

**Comment by gpetrov** [comment]
Thank you @codebytere you are absolutely right! This helped me find bad code we had there for some time it seems!

I wonder if maybe `contentWindow` should have equals to undefined before src is set, but I guess it has to do with chrome setting it to `about:blank` per default.
