### ISSUE TITLE
[Bug]: setImmediate stops working randomly in v11.3.0+ after reloading the app

### ISSUE THREAD

**Issue by sergiou87** [electron/electron#29261]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.3.1 (20E241)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

~~11.3.0~~ 11.2.0

### Expected Behavior

`setImmediate` still responds.

### Actual Behavior

I haven't managed to get this into a simple sample app. I will try, but wanted to share what happens in [GitHub Desktop](https://github.com/desktop/desktop) in case it's clear to someone what the problem is. If you want to reproduce it yourself, you'll need to use the [latest beta](https://github.com/desktop/desktop#beta-channel).

Basically when I start the app, invoking `setImmediate` works perfectly. However, if I reload the app at some point (pressing Cmd+R from the Dev Tools) and then I start switching between apps, at some point, randomly, `setImmediate` stops working. It's like the thread/runner/event loop is blocked.

In the video below, **which was recorded AFTER I reloaded the app**, you see the following:
1. `setImmediate` works at the beginning, showing the alert.
2. Also you see how I get my list of repositories when I click on the top left button.
3. Then I start switching quickly between the GitHub Desktop window and the Dev Tools, while I show/hide the list of repositories.
4. At some point, the list of repositories is empty... that means `setImmediate` doesn't work.
5. In the console, I try to run exactly the same `setImmediate` command and I don't get an alert.

https://user-images.githubusercontent.com/1083228/118969072-f00e2f00-b96c-11eb-868b-03f0d26cac7d.mp4

### Additional Information

As you can see, I can't reproduce the issue 100% reliably. I'm quite sure it doesn't happen in 11.1.1, because I've used that one for quite a long time. However, I tested what you see in the video with 11.2.0 ~~and 11.3.0~~ and I couldn't reproduce it.

**EDIT:** today (8-jun-2021) I managed to repro this behavior in 11.3.0, after 2 weeks using the app intensively. As of today, I'm not sure which version broke this, but seems like 11.4.0 makes it much much easier to reproduce it.

Looking at the [release notes of v11.4.0](https://github.com/electron/electron/releases/tag/v11.4.0), #27582 is the one that seems more suspicious to me.

I could reproduce it with 11.4.0, 11.4.4 and 11.4.7 (the latest version of v11), but I haven't tested other versions in between, nor anything out of v11 (like v10, v12 or v13).

I'll try to write a Fiddle that reproduces the issue

**Comment by sergiou87** [comment]
I just managed to reproduce this in v11.3.0 after we bumped it in desktop/desktop#12279

No idea for how long the bug has been there, but it seems 11.4.0 made it much much easier to reproduce 🤔

**Comment by nornagon** [comment]
I assume you're talking about calling `setImmediate` in the renderer process, not the main process?

**Comment by sergiou87** [comment]
Yes! In this case the problem presents in the renderer thread, in a callback from a `ResizeObserver`: https://github.com/desktop/desktop/blob/9630999f5e32f9aef4c3a0ae54ba88153aa6b588/app/src/ui/lib/list/list.tsx#L300-L304

I haven't tried if the same happens in the main process, but I can check if that helps.

**Comment by nornagon** [comment]
It would be great to check if this happens in 12.x or 13.x, there have been a couple of fixes in this area recently.

**Comment by sergiou87** [comment]
Testing this on 12.x or 13.x is a bit more challenging than expected, since I can only reproduce this behavior in the GitHub Desktop app.

In any case, I tested calling `setImmediate` from the main process while the app is in this state, and that works. Does that mean anything?

I'm gonna try and debug this a bit more 🤞

**Comment by nornagon** [comment]
The main process and the renderer process have extremely different characteristics when it comes to calling Node functions like setImmediate, so I wouldn't take much heart from the fact that it works in the main process.

**Comment by codebytere** [comment]
@sergiou87 https://github.com/electron/electron/pull/28957 was merged into [v11.4.5](https://www.electronjs.org/releases/stable?version=11&page=2#11.4.5) and fixed some related issues - does this make a difference for your case?

**Comment by sergiou87** [comment]
Nope, I tried up to 11.4.7 and still can reproduce the issue 😞 

I just built GitHub Desktop with 13.1.7 and was able to reproduce it too:
![image](https://user-images.githubusercontent.com/1083228/126633194-422effd4-85fb-4ec1-a9db-5f66e64e11f1.png)

Again, `setImmediate` wouldn't work in this case 😕
