### ISSUE TITLE
[Bug]: CORS preflight requests get cancelled when connecting though auth proxy and app is using webrequests listeners.

### ISSUE THREAD

**Issue by marekharanczyk** [electron/electron#29265]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14

### What operating system are you using?

Windows

### Operating System Version

Window 10, but all system are affected

### What arch are you using?

x64

### Last Known Working Electron version

7.X.X

### Expected Behavior

CORS preflight request completes successfully after proxy authentication happens.

### Actual Behavior

CORS preflight request get cancelled immediately after 407 response is received from proxy server, no renegotiation of connection with generated token happens to allow proxy to allow request through.

### Additional Information

This bug requires specific env configuration to reproduce:
1. Setup electron to use proxy that requires authentication.
2. Launch an app that registers electron WebRequest api listeners (for example header ones).
3. Make that app open a page that will issues CORS request that will trigger network layer to send CORS preflight message to destination server (for example specific XHR request).
The bug is a side effect of adopting to chromium network servification changes.

**Comment by t57ser** [comment]
I think that is the same issue as: https://github.com/electron/electron/issues/25758

**Comment by marekharanczyk** [comment]
Yep, it is the same.
