### ISSUE TITLE
[Bug]: Crash during start when using parameters containing a colon

### ISSUE THREAD

**Issue by matschek** [electron/electron#29275]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10, 20H2

### What arch are you using?

x64

### Expected Behavior

User defined parameters should not crash electron.exe.
I.e., all of these should be valid calls from the command line:
```
app.exe param1:foo
app.exe --param1:foo
app.exe --param1:foo --param2
app.exe --param1:foo param2
app.exe test=dummy foo=bar
app.exe param1:foo param2
app.exe param1:foo --param2
app.exe test=du:mmy foo=bar
app.exe test="du:mmy" foo=bar
```

### Actual Behavior

starting with parameters can crash the process, which exists with error level -1 without any output.
Per trial and error it seems to trigger the issue when one parameter contains a colon AND at least one more parameter is following.
From the examples above, the last 4 examples crah:
```
app.exe param1:foo param2
app.exe param1:foo --param2
app.exe test=du:mmy foo=bar
app.exe test="du:mmy" foo=bar
``````

### Additional Information

Code whas been reduced to a single file
```
console.log("This is line 1 of the code");
console.log("arguments: %o", process.argv);
process.exit();
```
When this file is invoked with node.exe the code works as expected, parameters can contain a colon. 
The bug shows when invoked with the electron wrapper, or with the .exe generated per "electron-forge make".
In this case, no output and no error message is generated

Console-Copy:
```
C:\electron-test\test-app>node src/index.js param1:foo param2
This is line 1 of the code
arguments: [
  'C:\\Program Files\\nodejs\\node.exe',
  'C:\\electron-test\\test-app\\src\\index.js',
  'param1:foo',
  'param2',
  [length]: 4
]

C:\electron-test\test-app>node_modules\electron-prebuilt-compile\node_modules\electron\dist\electron.exe src/index.js param1:foo param2

C:\electron-test\test-app>node_modules\electron-prebuilt-compile\node_modules\electron\dist\electron.exe src/index.js param1:foo

C:\electron-test\test-app>
This is line 1 of the code
arguments: [
  'C:\\electron-test\\test-app\\node_modules\\electron-prebuilt-compile\\node_modules\\electron\\dist\\electron.exe',
  'src/index.js',
  'param1:foo',
  [length]: 3
]

C:\electron-test\test-app>
```

**Comment by pushkin-** [comment]
expected behavior. See [this](https://github.com/electron/electron/issues/25270)

**Comment by MarshallOfSound** [comment]
Closing as per above

**Comment by matschek** [comment]
Can you please specify which windows flaw is addressed with this behaviour? The question keeps unaswered in the linked thread.
And wouldn't it be helpful to quit the application with an error message which tells the user that it stops due to a possible attack?
A _silent_ death of a thread is not what I'd call "expected behaviour"
