### ISSUE TITLE
[Bug]: Crash. EXCEPTION_ACCESS_VIOLATION_READ when shutting down the app

### ISSUE THREAD

**Issue by Glebka** [electron/electron#29274]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19042 (928)

### What arch are you using?

x64

### Last Known Working Electron version

9.x

### Expected Behavior

App doesn't crash

### Actual Behavior

App is crashing sometimes when user quits the app (if I understand thee crash report correctly).
Sentry logged 34k events of this type.

### Testcase Gist URL

N/A

### Additional Information

Please see crash report (stack trace) - https://gist.github.com/Glebka/41f6e626be941846c891cadbf3046bb2/

**Comment by nornagon** [comment]
Would it be possible for you to attach the raw minidump from this crash?

**Comment by Glebka** [comment]
Hello  @nornagon 
Unfortunately, no. Our Sentry instance doesn't store original minidumps.
