### ISSUE TITLE
[Bug]: Rendering not updating the web page when hidden behind other windows (OBS-related)

### ISSUE THREAD

**Issue by AxelTerizaki** [electron/electron#29280]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.7

### What operating system are you using?

Windows

### Operating System Version

10.0.19041

### What arch are you using?

x64

### Expected Behavior

One of my users is trying to use OBS on my app to stream it. When my Electron app isn't visible on screen, it should refresh its view in OBS.

 

### Actual Behavior

When the app is behind other windows, it doesn't seem to update on OBS. For the example, my app is a media player, and my user wants to capture the playlist view : it doesn't update when switching to a new song when my app isn't visible on his screen.

### Additional Information

I'm not sure if this is a OBS or Electron issue, but I'm posting it here for now in hopes someone has an idea. I was thinking it might be Chromium-related, like it doesn't try to render an updated view of the page it's on as long as it's not visible to save on CPU/GPU. Is there a chromium switch I could use perhaps?

Thanks in advance if you have any idea on how to fix this.

**Comment by pushkin-** [comment]
probably dupe of [this](https://github.com/electron/electron/issues/28255) - or same cause anyway

**Comment by nornagon** [comment]
Does `--disable-features=CalculateNativeWinOcclusion` fix the issue for you?

**Comment by AxelTerizaki** [comment]
> Does `--disable-features=CalculateNativeWinOcclusion` fix the issue for you?

That totally worked, yes!

`app.commandLine.appendSwitch('disable-features','CalculateNativeWinOcclusion');`

This worked just fine for me. Thank you. I'll close the issue then.
