### ISSUE TITLE
[Bug]: capturePage  the web page becomes a transparent background.

### ISSUE THREAD

**Issue by 82318179** [electron/electron#29289]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

Windows

### Operating System Version

win10 20H

### What arch are you using?

x64

### Expected Behavior

I want the result to be the same as that rendered by a web page, but it is actually a transparent color.

### Actual Behavior

After the screenshot, it is transparent, but the original web page has a background color.

Test URL：http://www.icq100.com/html/2021-05/14/content_51343198.html

The picture produced by the screenshot is transparent. like follow
![00](https://user-images.githubusercontent.com/25976728/119228298-f35c1300-bb44-11eb-9d78-0a33b593038e.jpg)

but the page like 
![QQ截图20210522213211](https://user-images.githubusercontent.com/25976728/119228351-35855480-bb45-11eb-9f60-b44c685668c1.png)

the code like this 
`    let imageBuffer = await this.webContents.capturePage().then(async (image) => {
      fs.writeFileSync(filepath, image.toPNG(), (err) => {
        if (err) {
          console.log('writeFileSync_Err:', err);
        }
      });
      //return image.toDataURL(); //返回base64编码
      return image.toPNG();
    });`

How can we ensure that the screenshot is consistent with the web page, rather than transparent?

**Comment by nornagon** [comment]
This is the intended behavior. If you want to force a background color then add `html { background-color: white }` to the page's CSS.
