### ISSUE TITLE
[Bug]: Failed to load native addons even if statically linked librotobuf.a ( v3.5 ) to native addons. 

### ISSUE THREAD

**Issue by vijaykumbhani** [electron/electron#29285]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 16.04

### What arch are you using?

x64

### Expected Behavior

Hi All,

Found the election using **libprotobuf-lite.so.9.0.1** v2.6.1 process address space. 
`cat /proc/18484/maps | grep "libproto"
7f3fdaf08000-7f3fdaf38000 r-xp 00000000 fd:00 40246                      /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9.0.1
7f3fdaf38000-7f3fdb137000 ---p 00030000 fd:00 40246                      /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9.0.1
7f3fdb137000-7f3fdb138000 r--p 0002f000 fd:00 40246                      /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9.0.1
7f3fdb138000-7f3fdb139000 rw-p 00030000 fd:00 40246                     /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9.0.1`

Created native addons using google protocol buffer library v3.5.0. native addons statically linked **libprotobuf.a** v3.5.0. 
While loading native addons. electron looks **libprotobuf-lite.so.9.0.1** v2.6.1 instead of statically linked  **libprotobuf.a** v3.5.0. 

Do not know, is there a way to tell electron do not to looked symbols **libprotobuf-lite.so.9.0.1** while loading specific native addons. 

posted the same question on StackOverflow  https://stackoverflow.com/questions/67604227/runtime-failed-to-load-node-js-native-addon-which-linked-by-protocol-buffer-stat

Thanks in advance 

### Actual Behavior

Hi 

if we statically linked static library to native addons while compile time building. it should look from native addons instead of loaded another version library.

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
