### ISSUE TITLE
[Bug]: Tray title bold ANSI code does not work

### ISSUE THREAD

**Issue by sdegutis** [electron/electron#29288]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

Latest

### What operating system are you using?

macOS

### Operating System Version

macOS 10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

```js
const RED = '\033[31;1m';
tray.setTitle(`${RED}stuff`);
```

This should be bold.

### Actual Behavior

It's no different than without the bold code (`;1`).

**Comment by sdegutis** [comment]
Oh, I see. It's just a darker red when it's bold.

https://github.com/electron/electron/blob/master/shell/browser/ui/cocoa/NSString+ANSI.mm#L45

Why not use NSAttributedString's normal way of doing bold?

You already have NSFont, you'd just need to rewrite it with: `font = [fontManager convertFont:font toHaveTrait: NSBoldFontMask]`.

This needs `fontManager` via: `NSFontManager *fontManager = [NSFontManager sharedFontManager];`

**Comment by nornagon** [comment]
Here's the code that handles this: https://github.com/electron/electron/blob/a855aa34d939625c00b309dacd9dcdeef98d855e/shell/browser/ui/cocoa/NSString%2BANSI.mm#L13

Indeed, it doesn't do anything to change font traits to bold, it only changes colors.

I'm going to close this in favor of #29313, since I think they represent the same work.
