### ISSUE TITLE
[Bug]: FileOpenDialog seem to be slow in development mode

### ISSUE THREAD

**Issue by WellWells** [electron/electron#29307]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.9

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1

### What arch are you using?

x64

### Expected Behavior

FileOpenDialog should be callback immediately after I click open.

### Actual Behavior

There is some delay in development mode no matter I use file input (DOM) or electron dialog

### Additional Information

Hello guys.

While I am using DOM element <input type="file"> to trigger open dialog, or ipc communication between main and renderer to trigger the dialog.showOpenDialog event.

The popup showed up immediately.
However onchange event or electron showOpenDialog callback seem to be a 2~5 second delay.

This delay will disappeared after I run electron-packager to build executable file.
Is this delay exist or a bug in development mode?

**Comment by WellWells** [comment]
This issue I am not sure it's my computer's problem or something else....
I have no idea what I've done.... It seems to be fix.

**Comment by ZpWaitingForSunshine** [comment]
I have this problem too.  But my case only happens when the computer is turned on.
