### ISSUE TITLE
BrowserWindow and BrowserView  webContents capturePage  image width become  0

### ISSUE THREAD

**Issue by 82318179** [electron/electron#29306]
` await this.webContents.capturePage().then(async (image) => {
      let { width, height } = image.getSize();
      console.log('aaaa:', width, height);
    });`

Use BrowserWindow and BrowserView  webContents capturePage ,  When the page is minimized, or the page is not at the top and is blocked by other programs, the height and width of the screenshot become 0

but in  webview  ,When the page is minimized, or the page is not at the top and is blocked by other programs, the height and width of the screenshot is OK . 

Use BrowserWindow and BrowserView  webContents capturePage , When the page is minimized, how to ensure that the screenshot is still normal?

**Comment by NemoAlex** [comment]
This problem bothers me too.
Need help.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by nornagon** [comment]
Additionally, we require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
