### ISSUE TITLE
[Bug]: language in docs about "can only be called before app is ready" is confusing

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#29315]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

The docs ([example](https://www.electronjs.org/docs/api/app#appdisablehardwareacceleration)) use language like:
>This method can only be called before app is ready.

The standard way of doing is:
```
callSpecialMethod();
await app.whenReady();
```

However, how do I actually know that my app isn't ready when calling that special function?

All I know is that I haven't yet awaited `whenReady`, but could the promise returned by `whenReady` already be resolved because the `ready` event fired, and so I'm actually calling the function after the app is ready, but just before I check the `whenReady` promise?

Is what's meant by that language really that I need to call these functions synchronously in the main method, and the `ready` event is guaranteed not to fire before my main method has exited?

Should the docs be updated to clarify that if that's indeed the case?

### Actual Behavior

n/a

**Comment by nornagon** [comment]
Yes, this verbiage in the docs means that the method must be called synchronously during the first "tick" of JS in the main process. Happy to review PRs to improve the docs on this point :)

**Comment by erickzhao** [comment]
bump

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump
