### ISSUE TITLE
[Bug]: Geolocation does not work on Mac

### ISSUE THREAD

**Issue by YeetOrBeYate** [electron/electron#29314]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

When permission is granted, calling `navigator.geolocation.getCurrentPosition()` would return a position object.

### Actual Behavior

Only returns a timeout error, `{ code: 3, message: 'timeout expired' }`.

### Additional Information

I've done the following to make sure my Google Maps key is valid:

1.) Created a fresh google maps api key

2.) Visited this page to enable geolocation services https://console.developers.google.com/apis/library/geolocation.googleapis.com

3.) Set the GOOGLE_API_KEY in my main.j file

`process.env.GOOGLE_API_KEY = 'myapikey'`

4.) Called navigator functions to check for permission(always granted in my attempts) before requesting the location. The only result I get back is the code 3, timeout expired error. 

```
function handlePermission() {
  navigator.permissions.query({ name: 'geolocation' }).then(function (result) {
    if (result.state == 'granted') {
      report(result.state);
      navigator.geolocation.getCurrentPosition(revealPosition, noPostiion, { timeout: 120000 });
    } else if (result.state == 'prompt') {
      report(result.state);
      navigator.geolocation.getCurrentPosition(revealPosition, positionDenied, geoSettings);
    } else if (result.state == 'denied') {
      report(result.state);
    }
    result.onchange = function () {
      report(result.state);
    }
  });
}

function report(state) {
  console.log('Permission from alertPreload ' + state);
}

function revealPosition(position) {
  console.log('position?', position)
}
function noPostiion(error) {
  console.log('No position for you', error)
}


handlePermission();
```

**Comment by raphaelschaad** [comment]
I'm able to get geolocation on macOS Big Sur with this API. However, unlike in earlier versions of macOS, **there is no user prompt when first requesting location**. Instead, the request just fails. If you manually open Sys Prefs and give the app permission, the requests return correct results.

**Comment by raphaelschaad** [comment]
bump
