### ISSUE TITLE
[Bug]: Can't simulate custom storage quota

### ISSUE THREAD

**Issue by cawa-93** [electron/electron#29319]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.9

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 19042.572

### What arch are you using?

x64

### Expected Behavior

Open Devtools. Application > Storage and enable "Simulate custom storage quota". I set it to `0.1` MB. 
When this limit is exceeded will be returned DOM Exception `QuotaExceededError`

### Actual Behavior

Data continues to be stored successfully.

![зображення](https://user-images.githubusercontent.com/1662812/119492709-e7dc3800-bd4e-11eb-8148-a1f3f175d726.png)

```js
navigator.storage.estimate()

{
    "quota": 100000,
    "usage": 864943,
    "usageDetails": {
        "caches": 321792,
        "indexedDB": 422753,
        "serviceWorkerRegistrations": 120398
    }
}
```

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by cawa-93** [comment]
@nornagon https://gist.github.com/4c1793bf1df43f041872af870decb5a9

**Comment by nornagon** [comment]
@cawa-93 thanks for the detailed repro! With this, I'm able to confirm the behavior you're describing.

Electron's behavior seems to match Chrome's, though. This screenshot was taken in Chrome devtools:

![image](https://user-images.githubusercontent.com/172800/123139852-7e158380-d40b-11eb-87b6-f52bec867712.png)

So this is either intended behavior, or an upstream bug. Consider reporting against Chromium: https://crbug.com/new

I'm going to close this for now as blocked/upstream, but happy to reopen if it turns out there's some action we can take.

**Comment by cawa-93** [comment]
@nornagon Hmm.... I have tested [this codepen](https://codepen.io/cawa-93/pen/yLMdrOz?editors=1010) in Google Chrome v91.0.4472.114 and Edge v91.0.864.54. And in all browsers I get `QuotaExceededError` as expected ...

**Comment by nornagon** [comment]
@cawa-93 interesting. One of the instructions there is to "open the codepen in debug mode" -- how does one do that? I can't find any obvious UI in codepen that looks like it would do that.

**Comment by cawa-93** [comment]
@nornagon **[This](https://cdpn.io/cawa-93/debug/yLMdrOz/LDkmdnpPxyyA) is direct link to debug mode**. You should see clear web page with my demo without codepen interface. 

If this link not work:
1. You must [sing up](https://codepen.io/accounts/signup/user/free). 
2. You need to fork my example into your account. In the lower right corner you will find the "Fork" button.    
  ![зображення](https://user-images.githubusercontent.com/1662812/123749067-b0b4f580-d8bd-11eb-8a28-d2f4a3eb2226.png)
3. Finally, in fork open drop-down menu i  In the upper right corner and select "Debug mode"
  ![зображення](https://user-images.githubusercontent.com/1662812/123749359-038ead00-d8be-11eb-9e4e-28a3459bbb4e.png)

**Comment by nornagon** [comment]
Thanks for the instructions, I was able to reproduce the QuotaExceededError behavior in Chrome. Loading the Codepen debug view directly in Electron & running the same steps produces no error, so I'm reopening this as confirmed.

**Comment by nornagon** [comment]
This might be an unintentional side-effect of our intentional hack to allow unlimited storage: https://github.com/electron/electron/blob/d3c1f10e33622f760ec0fc91d880b578da066076/shell/browser/special_storage_policy.cc#L20-L22 (called from https://source.chromium.org/chromium/chromium/src/+/main:storage/browser/quota/quota_manager_impl.cc;l=1063;drc=c14f6f4b9c44fe479a8d004576b42723b2a5feb6)

**Comment by shadow-light** [comment]
Does Indexeddb get purged when there is a QuotaExceededError thrown? I had a user who lost all there data when they used by their disk space. Indexeddb had been wiped when they reopened the app.

**Comment by AnweshGangula** [comment]
i'm facing the same issue. I'm noticing that the `navigator.storage.estimate()` still returns the actual available space and ignores the simulated value. But when the file is actually downloaded, it does respect the simulated value and block the download beyond the simulated size.
