### ISSUE TITLE
[Bug]: setAlwaysOnTop can cause fullscreen  app  can't cover taskbar 

### ISSUE THREAD

**Issue by chenxiao1990** [electron/electron#29317]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

ia32

### Expected Behavior

other fullscreen app  should be cover taskbar.

### Actual Behavior

My window setAlwaysOnTop(true, "pop-up-menu", 1), other app fullscreen could not cover taskbar . 
eg , chrome ! press F11 taskbar is over,  when i delete  win.setAlwaysOnTop(true, "pop-up-menu", 1) , press F11 chrome fullscreen well.
I have three windows computers , there's only one cause this bug.

### Testcase Gist URL

https://gist.github.com/chenxiao1990/a6d010d77103c92ef88bb74cd616ab58

**Comment by chenxiao1990** [comment]
This problem can be solved by enabling or shutting down windows functions, old components, check DirectPlay and restarting the computer.

But I don't think every user can operate like this.

**Comment by chenxiao1990** [comment]
I test use Qt( gui frameword with c++) , set window top.  It doesn't effect chrome fullscreen, taskbar is covered.
So I still suspect that electron's topwindow is incompatible with part of win10.

**Comment by CiriousJoker** [comment]
Sometimes, Electron windows (Spotify, Discord etc.) grab attention, which makes it so the Taskbar desn't slide out of view. Is this the same issue or smth unrelated?

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by chenxiao1990** [comment]
Testcase Gist URL
https://gist.github.com/chenxiao1990/a6d010d77103c92ef88bb74cd616ab58
