### ISSUE TITLE
[Bug]: PDF viewer displays blank pages on Windows

### ISSUE THREAD

**Issue by zadam** [electron/electron#29326]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2

### What arch are you using?

x64

### Expected Behavior

PDF viewer should display content of the PDF file.

### Actual Behavior

![image](https://user-images.githubusercontent.com/617641/119561748-dc682b80-bda5-11eb-8a4a-66a96cc3e6a8.png)

All PDFs are affected.

Interestingly PDF viewer displays number of pages correctly so it seems to read the PDF file, but then fails to render it.

There does not seem to be anything of interest in the console.

This bug seems to affect Windows specifically, on Ubuntu the PDFs are rendered correctly.

**Comment by ailin92** [comment]
I have this exact same problem.

**Comment by Simolation** [comment]
This is really annoying as this (probably) also prevents printing generated PDFs directly in the renderer. For example, when loading the https://printjs.crabbly.com/ page in electron I am unable to print the PDF examples. The other examples do work

**Comment by nohhhon** [comment]
hhlesbian.84367754'

Thats a huge amount of electricity..
https://www.instagram.com/p/B1BARz3pIWQ/?igshid=15ihvdyc02zxz

**Comment by KasperSommer** [comment]
It works on MacOS but fails on Windows...

**Comment by Simolation** [comment]
> It works on MacOS but fails on Windows...

For me, the same issue was also on macOS

**Comment by VerteDinde** [comment]
Testing gist here: https://gist.github.com/80a9108e271ca83c82cc4a8772e371fc

Can confirm this is not working on 13.0.0 stable, 14 betas or master. Seems like it broke in 13.0.0-beta.14, likely due to a change in this Chromium bump: https://github.com/electron/electron/commit/66a22187233edbf33030d69458975531852fc858

**Comment by webdevmario** [comment]
I also have this issue on Windows. Using Electron 13.1.2. It works again if I simply switch to 12.0.10.

**Comment by VerteDinde** [comment]
The root cause is an unhandled crash happening in `SendMetadata()` within DocumentLoadComplete - it seems like this is caused by changes in the Chromium roll convering to stringUTF16. Working on a fix.

**Comment by VerteDinde** [comment]
👋 🙂 This fix should appear in 13.1.4 and 14.0.0-beta.9. If the issue persists, let me know!
