### ISSUE TITLE
[Feature Request]: Extend 'open-url' event to Windows and Linux

### ISSUE THREAD

**Issue by jmrossy** [electron/electron#29336]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The open-url event is very useful for deeplinking. It works well on Mac but Windows and Linux need somewhat complex workarounds to enable deep-linking.

### Proposed Solution

Extend the event support to Windows and Linux

### Alternatives Considered

Do nothing - keep inconsistent solutions for Mac vs Windows vs Linux

### Additional Information

Related issues / projects:
https://github.com/electron/electron/issues/18586
https://github.com/electron/electron/issues/6537
https://github.com/electron/electron/issues/2707
https://github.com/electron-userland/electron-builder/issues/623
https://github.com/electron-userland/electron-builder/issues/1552
https://github.com/oikonomopo/electron-deep-linking-mac-win

**Comment by MarshallOfSound** [comment]
Unfortunately this is a limitation of the OS, there is no native concept of "please tell this application to open this URL" on Windows / Linux.  The URLs are passed via command line arguments and therefore it relies on single instance locks and parsing that command line.  There isn't a _safe_ and _generic_ way to do this, trust me I tried --> https://github.com/electron/electron/pull/8052

The current way of making each app parse it's own URLs is unfortunately the only viable option

**Comment by jmrossy** [comment]
@MarshallOfSound Okay thanks for the response

**Comment by RohanNegiUI** [comment]
Hi @MarshallOfSound,

Could you please share the way to handle deep link URL when windows app for the first time?
