### ISSUE TITLE
[Bug]: spell checker isn't downloading the dictionary in versions 11.0.0 +

### ISSUE THREAD

**Issue by rileycirrus** [electron/electron#29348]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home version 20H2 build 19042.985

### What arch are you using?

x64

### Last Known Working Electron version

10.4.7

### Expected Behavior

Electron downloads the dictionary to the dictionaries folder in appdata/Roaming/Electron/Dictionaries

### Actual Behavior

Electron does not download the dictionary, and nothing can be found in the dictionaries folder.

### Additional Information

This works fine on versions before 11.
I have done a fair bit of testing with versions on this and I think one version is downloading the dictionary to the root directory as well  ("appdata/Roaming/Electron",  not sure which, I will update if i find it)

**Comment by tyson-sh** [comment]
Also experiencing this.  Hoping for a fix as this is seriously holding my app back.

**Comment by rileycirrus** [comment]
Is this potentially caused by Chrome starting to use the windows dictionary?
https://www.theverge.com/2020/5/28/21273934/microsoft-google-chrome-edge-chromium-spellcheck-improvements

**Comment by hwallis93** [comment]
I'm also very interested in getting this fixed

**Comment by AndreThompson-Atlow** [comment]
Having some issue with this as well, had to pull spell check out of my app for now. Hopefully this gets resolved as soon as possible, i'd rather use electron 12+ than 11.
