### ISSUE TITLE
[Bug]: navigator.serial.getPorts() returns an empty list if device is unplugged and replugged

### ISSUE THREAD

**Issue by gniezen** [electron/electron#29366]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

Ubuntu

### Operating System Version

5.4.0-73-generic #82~18.04.1-Ubuntu

### What arch are you using?

x64

### Expected Behavior

`const existingPermissions = await navigator.serial.getPorts();` should return a list of serial ports for which permission has already been granted, even when a device has been unplugged and plugged back in again.

### Actual Behavior

The list is empty, even when the same code works in the browser (Chromium v90.0.4430.93).

### Testcase Gist URL

https://gist.github.com/gniezen/34950a5fa84dcf000e2b55a8d599ecd6

### Additional Information

To reproduce using gist:

- Replace `usbVendorId` and `usbProductId` with that of your test device.
- Click the `Connect` button. It should show up in the port list on the main console.
- Click the `Get Ports` button. It should show the existing permission in the developer console.
- Unplug and re-plug the device.
- Click the `Get Ports` button. It should show the existing permissions, but returns an empty list.

**Comment by gniezen** [comment]
@jkleinsc Anything more I can do to have someone take a look at this?

**Comment by nornagon** [comment]
@gniezen does this also happen in Chromium?

**Comment by gniezen** [comment]
@nornagon No, this works as expected in Chromium. I think it's because Electron handles the permissions instead of Chromium, see https://github.com/electron/electron/issues/22478 for details.

**Comment by jkleinsc** [comment]
@gniezen #30209 should fix this issue.

**Comment by gniezen** [comment]
Awesome, thanks @jkleinsc ! :pray:
