### ISSUE TITLE
Text in Electron apps is blurry when KDE Plasma (with Wayland) display scaling is used

### ISSUE THREAD

**Issue by mystiquewolf** [electron/electron#29367]
Below are screenshots from Authy and VS Code with KDE Display Scale set to 125% on 1920x1080 screen.

![authy-1](https://user-images.githubusercontent.com/16529989/119867263-5f17f480-bf26-11eb-83b7-6ef3c02888e9.png)
![authy-2](https://user-images.githubusercontent.com/16529989/119867267-5fb08b00-bf26-11eb-81b0-96792893267c.png)
![vs-code](https://user-images.githubusercontent.com/16529989/119867269-60492180-bf26-11eb-9348-e13c853bbff2.png)

**Comment by mystiquewolf** [comment]
Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-17-generic
OS Type: 64-bit
Graphics Platform: Wayland
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by vially** [comment]
Are these Electron apps running as native Wayland apps or are they running through XWayland?

**Comment by mystiquewolf** [comment]
They seem to be running via XWayland.

**Comment by MrSwedish** [comment]
is not electrons fault, there is a wayland version, i dont know how to use it

**Comment by mystiquewolf** [comment]
Electron 12 contains native Wayland functionality. You can use this in newer versions of VS Code by passing `--enable-features=UseOzonePlatform --ozone-platform=wayland` via the command line / .desktop file.
I am closing this bug.
