### ISSUE TITLE
[Bug]: Unable to Bind to Next or Previous Track Events on M1 Mac Touch Bar

### ISSUE THREAD

**Issue by FerrisThomasSXM** [electron/electron#29376]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.9

### What operating system are you using?

macOS

### Operating System Version

MacOS Big Sur 11.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I should be able to bind to events from the Mac Touch Bar for Previous and Next track via the globalShortcut.register method with the MediaNextTrack and MediaPreviousTrack arguments. 

### Actual Behavior

globalShortcut.register on MediaNextTrack, MediaPreviousTrack, and MediaPlayPause appears to be unable to bind to those touch bar events. 

Logs to the console show the binding for CommandOrControl+A show the binding was successful, whereas the three Media controls were not.

### Testcase Gist URL

https://gist.github.com/5789ab9f3e5cf7641daee681231f8671

**Comment by martpie** [comment]
I can confirm it happens on intel macbooks as well.

**Comment by has-n** [comment]
Can confirm this doesn't work for VolumeUp or VolumeDown as well. It does work for VolumeMute though. 

MBP 2019 running Big Sur.
