### ISSUE TITLE
If an error occurs in main.js, atom-shell does not output that error but instead reports that the app is invalid.

### ISSUE THREAD

**Issue by Twipped** [electron/electron#294]
Even when launching from the command line, any JS error occuring in main.js is internally trapped, preventing debugging.  Instead, you get the following:

![screenshot 2014-05-12 09 38 03](https://cloud.githubusercontent.com/assets/231157/2947232/fc3162d0-d9f3-11e3-9b8c-a5f22460e757.png)

The error is not reported in the console.

**Comment by huvber** [comment]
I still have this problem so I think isn't close. There are someway to let atom-shell show wich is the error?

**Comment by chemdemo** [comment]
Just delete this line:
``` js
require('crash-reportor').start();
```

**Comment by tundrax** [comment]
I get the same error often on startup. The reason, for me usually, is requiring non-existent file or module name typo in require method:
```javascript
var a = require('./wrong-path');
```

**Comment by danShumway** [comment]
+1 This is a bug - an incorrect require statement isn't really the same as an invalid app, which makes this error deceptive at best.

The attached commit seems to just manually detect when a module isn't found and then still throw the same error, regardless. Is there something I'm missing? It seems like what you want to detect is if one of the key modules is missing (ie main.js), but this looks to report the same error regardless of which require statement goes wrong.

Absent of a more in-depth solution, could the error message be modified to mention require statements in some way?  This can be a pain in the neck to debug if you don't already know that a script error can trigger this.
