### ISSUE TITLE
[Bug]: Silent print pdf not working

### ISSUE THREAD

**Issue by ailin92** [electron/electron#29403]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1 

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise build no. 19041

### What arch are you using?

x64

### Expected Behavior

When I print a pdf using print({ silent: true, printBackground: true }) } I expect for it to work and print without showing dialog box of printing options, but use the default print configuration.

### Actual Behavior
It does not print but remains stuck if default print option is print. If I set it to Microsoft Print to Pdf, it prints an empty doc.

 If I use executeJavaScript('window.print({ silent: true, printBackground: true })'), it prints but it is not silent. This problem exists only with pdf.
I updated electron version to 13.0.0 but there the pdf view does not work also, it stucks showing blank pages, so I had to downgrade. 

Silent pdf printing  is a very important feature and I have seen other people asking about it, but still no solution.

**Comment by codebytere** [comment]
Duplicate https://github.com/electron/electron/issues/29334
