### ISSUE TITLE
[Feature Request]: Stacktrace for uncaughtException handler

### ISSUE THREAD

**Issue by c3er** [electron/electron#29418]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I like to obtain the stacktrace of the original error in the `process.on("uncaughtException", ...)` handler to output it somewhere.

```js
process.on("uncaughtException", error => {
    console.error(error) // <-- How to get the stacktrace where this error originated?
    electron.app.exit(1)
})
```

### Proposed Solution

An additional property `error.stack` or an additional parameter for the uncaughtException callback method

### Alternatives Considered

I don't know an alternative. If there exists any method for for obtaining and outputting the stack trace in the case of an uncaught exception in the main process, I'd be happy.

### Additional Information

Currently used Electron version: 13.0.1

**Comment by MarshallOfSound** [comment]
All `Error` objects in javascript have a `stack` property already.  E.g.

![image](https://user-images.githubusercontent.com/6634592/120234323-95968d80-c20c-11eb-8c2b-c9da724abc8e.png)

Sounds like what you want

**Comment by c3er** [comment]
Thanks! Somehow, I missed this.
