### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ibalaji777** [electron/electron#29417]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.10

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

Electron missing letter while print webview only in production but development version working perfectly

### Actual Behavior

Electron missing letter while print webview only in production

**Comment by miniak** [comment]
Electron 3 is not supported for a very long time already. Please create a new issue if you can still reproduce your problem on a current version, with proper repro steps and a title.
