### ISSUE TITLE
[Bug]: Electron Chrome can't save custome device

### ISSUE THREAD

**Issue by dming4** [electron/electron#29428]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.03

### What operating system are you using?

Ubuntu

### Operating System Version

16.0.4

### What arch are you using?

x64

### Last Known Working Electron version

11.03

### Expected Behavior

1: toggle device toolbar
2: add custom device, eg kk
3: select the added emulated device and display normal
4: close electron and restart app
5: the custome device disappearance

Want to know why can't save the custome config in electron chrome? thx.

### Actual Behavior

the custome device should display

**Comment by MarshallOfSound** [comment]
This is currently expected behavior, devtools preferences are stored in-memory and are therefore reset each launch

**Comment by dming4** [comment]
@MarshallOfSound
I try in another machine, it's ok, it can save, no other config.
Want to know what caused this behavior, some cant save,  some can't.
Development is very inconvenient, if i want save this config, how should i do?

**Comment by dming4** [comment]
I must add custom device again(below steps) when the  app restart, It's very troublesome

1: toggle device toolbar
2: add custom device, eg kk
3: select the added emulated device and display the custom device
