### ISSUE TITLE
[Bug]: IndexedDB is slower after updating to version 9 ~ 13

### ISSUE THREAD

**Issue by hamidrezakks** [electron/electron#29427]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0

### What operating system are you using?

macOS

### Operating System Version

Catalina

### What arch are you using?

x64

### Last Known Working Electron version

8.5.0

### Expected Behavior

Well I expected faster DB in higher version but it's the opposite!

### Actual Behavior

Indexeddb is very slow after version 9, I think you have changed storage system since I'm not able to downgrade to version 8.

### Additional Information

I've checked chrome and it was fast, but in electron you can easily say that DBs and storages are slower in start up,
And I guess it has a throttle in it!

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by luox12** [comment]
I encouter the same problem, The writer performance of indexeddb in electron(avg 300/s) is 20x slower than in chrome(avg 7k/s), both in version 9.x and 13.x.

**Comment by hamidrezakks** [comment]
@codebytere can you please check this issue?
It's significantly slower than chrome.
Please test it in built version not dev. (I used MacOS build on Big Sur)

This link can be used to compare indexeddb:
http://nparashuram.com/IndexedDB/perf/index.html

**Comment by luox12** [comment]
please reopen this issue.

**Comment by Yoryky** [comment]
I meet the same problem. in some win7 system it will take 60seconds to store data. but in other win7 system it may just need 2 seconds to store data.
