### ISSUE TITLE
[Bug]: Low FPS then using blur() or scroll page

### ISSUE THREAD

**Issue by gygyti** [electron/electron#29420]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

ia32

### Last Known Working Electron version

13.0.1

### Expected Behavior

I expected that blur () and changing the positions of elements with CSS would not slow down the program 

### Actual Behavior

on my site I am using both blur () and positioning of elements with CSS at the same time.

if I use app.disableHardwareAcceleration (), then the FPS drops to 15-20.

if i don't use app.disableHardwareAcceleration () then most of the site works fine (although images are blurry) however when using blur () and changing the position of elements with CSS the FPS drops to 2-5.

I would like to use app.disableHardwareAcceleration () because this way the images on the site are not blurry and clear, it only remains to raise the FPS with blur ()

**Comment by gygyti** [comment]
ok, the problem with blur on image we can fix with --disable-gpu-rasterization
but the prblem with very low FPS when you scroll on use blur() on elements still actual

**Comment by nornagon** [comment]
This is not an Electron bug; we don't do anything that could affect the performance of the blur effect. Further, it is unsurprising that graphics operations get slower when you turn off hardware acceleration.

If you can reproduce the issue in Chromium, consider filing a bug there: https://crbug.com/new
