### ISSUE TITLE
[Bug]: fs.writeFileSync inconsistently writes 0x00 bytes.

### ISSUE THREAD

**Issue by camhart** [electron/electron#29434]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Using fs.writeFileSync should write the appropriate value, or error out if it fails.

### Actual Behavior

When writing data to a file using fs.writeFileSync, 0x00 bytes are written instead of the actual string's bytes.

### Additional Information

Unfortunately, I'm not able to replicate this on any of my machines.  But a client's machine running my electron application will randomly write a 0x00 byte for each character, instead of the actual character's byte when using fs.writeFileSync.  My application is a long running application that's frequently in the background (system tray)...  it writes to this file specifically once every hour or so the device is turned on.  So far the "bug (writing 0x00 bytes) seems to happen once every week or two.

I understand that this likely can't be fixed simply by what I'm providing, but I'm sharing it in the hopes that anyone else experiencing the same problem can find the ticket and collaborate.  I also understand it could be a hard drive related issue as well.

**Comment by gpetrov** [comment]
this happen to me only when using the fs.writeFile async functions and because probably those ran on the same file at the same time, so I got 0 bytes files as result.

Are you sure you don't have something similar?

**Comment by camhart** [comment]
@gpetrov I'm using the sync version, and it's only being called from one place within my main process.  My naive understanding is node runs code in a single event loop, so it shouldn't be possible for multiple instances of the same code to be writing to it at once.  I'll keep thinking on this though, perhaps I'm missing something.  Thanks for the thoughts!
