### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by InvokerFury** [electron/electron#29433]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

ubuntu 18.04

### What arch are you using?

ia32

### Expected Behavior

Hi Sir,

i have a system ubuntu 18.04 glibc 2.27.. but my apps error when i try to run it, said glibc 2.28 not found.. 
would you suggest me what version should i use to compile my apps that can run in ubuntu 18.04 with glibc 2.27 ..

thanks

### Actual Behavior

Hi Sir,

i have a system ubuntu 18.04 glibc 2.27.. but my apps error when i try to run it, said glibc 2.28 not found.. 
would you suggest me what version should i use to compile my apps that can run in ubuntu 18.04 with glibc 2.27 ..

thanks

**Comment by vladimiry** [comment]
Consider recompiling the native dependencies on ubuntu-16.04 (the respective env on GitHub Actions comes with glibc 2.23). See here https://github.com/vladimiry/ElectronMail/issues/389#issuecomment-812237648 how to test which module depends on which glibc version.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
