### ISSUE TITLE
[Feature Request]: NSHelpManager API / openHelpAnchor method

### ISSUE THREAD

**Issue by Maxime117** [electron/electron#29432]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It would be super to be able to call the `NSHelpManager` method `openHelpAnchor` on darwin platforms.

### Proposed Solution

```
shell.openHelpAnchor(anchor[, book])
  anchor String - Location of the desired text.
  book   String - Help book name (e.g 'com.mycompany.surfwriter.help'). When not specified, all installed help books are searched.
  ```

### Alternatives Considered

Allow `shell.openPath` to handle a html-like anchor
```
shell.openPath("/Users/maxime/my-super-project/Super.help#AnchorName")
```

### Additional Information

`openHelpAnchor` documentation: https://developer.apple.com/documentation/appkit/nshelpmanager/1500908-openhelpanchor

**Comment by MarshallOfSound** [comment]
This is a _really_ limited and platform specific use case and IMO would be better served by building a small native node modules rather than adding this to the set of Electron core APIs.
