### ISSUE TITLE
[Feature Request]: Find/search text in the page using regular expressions

### ISSUE THREAD

**Issue by Jelmerro** [electron/electron#29435]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to search inside a webview using regular expressions.

### Proposed Solution

Give the `options` object of [this API](https://www.electronjs.org/docs/api/webview-tag#webviewfindinpagetext-options) a new boolean key to toggle regular expressions (regex). I know there are different flavors of regex, but even just the JS one would be really welcome.

### Alternatives Considered

Just searching for text, but that's not always enough. For example, I'm working on a browser using Electron that is inspired by Vim, which means users expect to search using regular expressions instead of plain text. I've wanted to implemented this for a while, but sadly the API doesn't provide an option for it.

### Additional Information

I decided to open an issue only now, because [someone has requested this to be implemented](https://github.com/Jelmerro/Vieb/issues/202) in the project, so I know it's not only me who wants this :wink:

**Comment by nornagon** [comment]
The underlying Chromium APIs do not support this, unfortunately, so this is not something we can add.

**Comment by Jelmerro** [comment]
That's really unfortunate, any other way you recommend implementing this, maybe a package that does this? Or should I build this from scratch if I want this?

**Comment by vladimiry** [comment]
Very bad news. I was hoping this gets enabled one day.
