### ISSUE TITLE
[Bug]: Electron window overlap input method candidate popup in macOS when setAlwaysOnTop(true, 'screen-saver')

### ISSUE THREAD

**Issue by TangKe** [electron/electron#29459]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

all version

### What operating system are you using?

macOS

### Operating System Version

11.3

### What arch are you using?

x64

### Expected Behavior

Show the input candidate popup above the Electron app window.

### Actual Behavior

Show the input candidate popup below the Electron app window, 
<img width="1028" alt="截屏2021-06-01 下午8 24 26" src="https://user-images.githubusercontent.com/1138688/120322828-6caeef00-c317-11eb-86f5-ce240c1f20c2.png">
Try to build a macOS native app, and set the NSWindow.level = NSWindow.Level.screenSaver, the candidate popup show correct
<img width="590" alt="截屏2021-06-01 下午8 25 45" src="https://user-images.githubusercontent.com/1138688/120322970-9405bc00-c317-11eb-8052-5b5b58eeb5ce.png">

### Testcase Gist URL

https://gist.github.com/f4d58e47448eea5e67a09cdb6b3434c4

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Please make a standalone testcase with only the code necessary to reproduce the issue. For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by TangKe** [comment]
@codebytere test case link already provided. You must use the Chinese pinyin input method provided by macOS system.

**Comment by nornagon** [comment]
I think this is working as intended—you've set your window to appear on the 'screen-saver' layer, but the IME window is in a layer below that. Unfortunately this is an OS limitation and not something we can change.

**Comment by TangKe** [comment]
> I think this is working as intended—you've set your window to appear on the 'screen-saver' layer, but the IME window is in a layer below that. Unfortunately this is an OS limitation and not something we can change.

@nornagon But same configuration(NSWindow.level = NSWindow.Level.screenSaver) in macOS native app build by Xcode has different behavior. pls see my last attached screenshot

**Comment by nornagon** [comment]
Ah, hm. Thanks for the clarification. I'll reopen this.

**Comment by YanZhenn** [comment]
This bug still exists in version 26.0.0,, please fix it ========
