### ISSUE TITLE
[Bug]: Black Video When getUserMedia with chromeMediaSourceId === window.getMediaSourceId()

### ISSUE THREAD

**Issue by phanmn** [electron/electron#29458]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

macOS

### Operating System Version

macos BigSur 11.4 

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

12.0.9

### Expected Behavior

I'm using this function to capture my window (window which start app), it work ok on Windows (same electron version) but not working on mac
```js
 await navigator.mediaDevices.getUserMedia({
    video: {
      mandatory: {
        chromeMediaSource: 'desktop',
        chromeMediaSourceId: sourceId,
      },
    })
```
`sourceId` value === `window.getMediaSourceId()`

### Actual Behavior

Black video

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by phanmn** [comment]
Hi @nornagon , here is a gist for Electron Fiddle for testing
https://gist.github.com/6a812cbcb20afab1ea4f72cb53f62cb9

**Comment by nornagon** [comment]
Thanks. Here's a simplified version that doesn't use `remote` or the third-party module `electron-context-menu`: https://gist.github.com/925744c7c67347d67c5b29e91c31e37e

Bisected to https://github.com/electron/electron/compare/v13.0.0-beta.20...v13.0.0-beta.21. The Chromium roll in that range seems like the likely culprit: https://github.com/electron/electron/pull/28660.

**Comment by nornagon** [comment]
Adding `app.commandLine.appendSwitch('disable-features', 'WindowCaptureMacV2')` works around this issue for now.
