### ISSUE TITLE
[Bug]: Notifications fail to trigger "click" when clicked in Windows 10 Action Center

### ISSUE THREAD

**Issue by The-MAZZTer** [electron/electron#29461]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4, 12.0.9, 13.0.1, 14.0.0.beta2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 1909 and 21H1

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

When clicking a notification which has moved into the Windows 10 action center, the click event should be triggered, matching the behavior seen in Google Chrome HTML5 notifications.

### Actual Behavior

For both HTML5 (renderer) and main process notifications, the click event is not triggered.

### Testcase Gist URL

https://gist.github.com/80b5d6b46d1ad5a1ed64d514c3cad710

### Additional Information

The "close" event triggers when a notification is moved into the action center, both HTML5 (renderer) and main notifications do this. I did not test Chrome to see if it does this or not. Either way it is odd behavior from my perspective and I could easily see it being related to this bug.

You can test Chrome's behavior using the following method:
1. Open any page where you have previously granted notification permissions (you can see it in the lock icon popup).
2. Open the dev tools and run:

    var notification = new Notification("Test");1
    notification.onclick = function() { alert("!"); }

3. Test clicking the notification on the desktop as well as in the action center. Both times the alert will display in the browser window properly.

**Comment by vilic** [comment]
Surprisingly no one seems to care about issue...

**Comment by gpetrov** [comment]
Well it will be great if it gets picked up by the team...

We are experiencing the same issue and it is pretty annoying.

Considering to move away from the native notifications just because of this.

**Comment by indutny-signal** [comment]
Looks like electron needs to wait for app activation and handle `ActivationKind.ToastNotification`. See:

* https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Notifications.ToastNotification?view=winrt-22000#remarks
* https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.onactivated?view=winrt-22000#Windows_UI_Xaml_Application_OnActivated_Windows_ApplicationModel_Activation_IActivatedEventArgs_

**Comment by The-MAZZTer** [comment]
Hey electron team I am working on an electron app for my employer and they are interested in when this bug will be resolved as it impacts core functionality of our application (we want to notify the user when important events happen and take them to a details page when the notification is clicked).

I am digging through some of the linked issues and it looks like a fix/rewrite may have been merged into "development" branch but is not actually publically released yet.

Are there any updates you can share? Is there a timeline for merge of the fix into a release build? Is there a plan to release it with a specific Electron version I should look out for?

Thanks.

**Comment by aplex** [comment]
This problem is still present in electron 19.0.8. Any updates on resolution, or good workarounds?

**Comment by annd22** [comment]
> This problem is still present in electron 19.0.8. Any updates on resolution, or good workarounds?

@aplex 
You can set the `toast` tag of notification template like this: 
```
 <toast launch="protocol://params" activationType="protocol">
```
`protocol` here which is your custom protocol:
```
app.removeAsDefaultProtocolClient('app');
app.setAsDefaultProtocolClient('protocol');
```
And when you click the notification at actions center, it will trigger the callback function with the argument is `protocol://params`
Note: I'm currently push notification with https://github.com/NodeRT/NodeRT

**Comment by major697** [comment]
Still not working in Electron: 28.2.3 and WIndows 10

**Comment by freddy-daniel** [comment]
Any updates?

**Comment by Dedicatus546** [comment]
is it fixed? i can't trigger click event when i click notification modal, it will create a default electron window...

version @42.5.0

😫😫😫😫😫
