### ISSUE TITLE
[Bug]: electron-updater does not handle client certificates

### ISSUE THREAD

**Issue by BluSunrize** [electron/electron#29460]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 18.04

### What arch are you using?

x64

### Last Known Working Electron version

-

### Expected Behavior

Attempting to use autoUpdater on an URL that has an _optional_ client cert (using HAProxy), it should either be allowed to ignore it, or at least trigger the `select-client-certificate` event.

### Actual Behavior

The event is not triggered, making it impossible for me to provide a certificate.

Instead, the following error is thrown:
```
15:29:30.474 › Error: Error: net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

This makes it seemingly impossible to use the autoUpdater on a server that features optional (or mandatory) client certs.

**Comment by nornagon** [comment]
Electron's autoUpdater uses Squirrel.Mac / Squirrel.Windows under the hood: https://www.electronjs.org/docs/api/auto-updater#platform-notices

The http requests that those tools make as part of their operation are not made through the Chromium / Electron network stack, and so cannot be intercepted by the usual tools.

This is unfortunately not something we can easily change, so I'm going to close this issue as wontfix.
