### ISSUE TITLE
Hang in renderer when pressing context menu key and waiting

### ISSUE THREAD

**Issue by bpasero** [electron/electron#2947]
This is a good one: Press the keyboard context menu key in Atom (or use the on screen keyboard on Windows to trigger it) and wait for 30 seconds. You will see a dialog popping up that the editor is unresponsive.

Cannot reproduce by just using the mouse for the context menu!

**Comment by brenca** [comment]
I can reproduce this on Windows 10 too.

**Comment by wfsm** [comment]
Any update?
