### ISSUE TITLE
[Bug]: printToPdf fails/hangs after a window close during print

### ISSUE THREAD

**Issue by anderklander** [electron/electron#29485]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

Windows

### Operating System Version

windows 10.0.19041, verified on macOS as well

### What arch are you using?

x64

### Expected Behavior

printToPdf should work regardless of if a previous ongoing printToPdf has been aborted.

### Actual Behavior

After closing a window that has an ongoing printToPdf, a second printToPdf on a new window hangs (not resolving or throwing error).

### Testcase Gist URL

https://gist.github.com/d4kris/c079ca193d1373dd3579a3a400381c70

### Additional Information

Might be timing dependent if it hangs or thows "Failed to generate PDF", so you might need to modify the timeout at main.js:66 so printing har started but is not finished.

**Comment by VerteDinde** [comment]
Hey @anderklander, thanks for reporting this issue! Could you add a bit more information to the bug here? I'm not sure if I can reproduce exactly what you're seeing - did this work in a previous version of Electron?

**Comment by anderklander** [comment]
Hi! Not sure if it worked in previous versions (will check!), but reproducing with the gist and electron fiddle was easy for my colleagues, just make sure the first print call has not resolved before the close()-call on the window. Did you get to "2nd Printed"? 

If a (browser)window is destroyed/closed while performing printToPdf, subsequent printToPdf-calls fail/hangs even if they are called on another window. Wildly guessing some kind of re-use issue or missing cleanup when the window is destroyed.

**Comment by anderklander** [comment]
Tested previous Electron versions:
13. fail
11. fail
10. fail  
9. Pass! 

(Pass means 2nd printed but not 1st printed)
So this was working on Electron 9! @VerteDinde

**Comment by codebytere** [comment]
Closing as working now.
