### ISSUE TITLE
Update from 5.x to 11.2.3, the fse.copy() function failed sometimes in our app. 

### ISSUE THREAD

**Issue by hz0324** [electron/electron#29489]
Our app is a book reading app. We updated the version of electron from 5.10 to 11.2.3 last month. 
We have got a lot of complaints about "can not add new books to the library sometimes." after the update.
Our team member has encountered the same problem once, but we cannot reproduce it afterward.
Right now, we have narrowed down the problem to following functions fse.copy().

It seems like, on 11.2.3, fse.copy() will stop working sometimes, without any error or warning.  It's like the app doesn't have the permission to perform the operation.  On 5.x, the same code works perfectly.

Here is more information.
1.Not everyone will encounter this BUG.
2.For some people, they can temporarily solve this problem by restarting the app.
3.For some people, even restarting the app will not solve this problem.
4.This bug only found on Windows OS.

Does anyone know why this is? what should we do?
Thanks.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by hz0324** [comment]
@MarshallOfSound I believe this is a bug, we just can not reproduce it consistently.
