### ISSUE TITLE
[Bug]: showCertificateTrustDialog doesn't work

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#29490]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Show the dialog

### Actual Behavior

Doesn't show

### Testcase Gist URL

https://gist.github.com/91a3fc7c756f67116686c273f8971604

**Comment by panther7** [comment]
Still doesn't works, Electron 32.
