### ISSUE TITLE
[Bug]: setWindowOpenHandler freeze when calling window.open('url')

### ISSUE THREAD

**Issue by lishid** [electron/electron#29509]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.9/13.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 1909

### What arch are you using?

x64

### Expected Behavior

BrowserWindow still functional and interactive.

### Actual Behavior

BrowserWindow freezes and becomes non-interactive.

### Testcase Gist URL

https://gist.github.com/lishid/214ea7598dd9589a3f6d7d5e5594848f

### Additional Information

Clicking a link with "_blank" works correctly, but calling `window.open('https://some-url.com')` doesn't.

**Comment by roryabraham** [comment]
I am experiencing this as well on `12.0.0`, `13.0.0`

**Comment by nornagon** [comment]
This appears to have been fixed in 14.x, somewhere in the range https://github.com/electron/electron/compare/v14.0.0-nightly.20210413...v14.0.0-nightly.20210426

**Comment by sps-gold** [comment]
This is a blocker for my application, any comments when can we expect a release with this fix

**Comment by nornagon** [comment]
@sps-gold we make releases regularly, there should be a 13.1.5 in the next day or so.

**Comment by sps-gold** [comment]
hi @nornagon, sorry for asking again. however as its critical to my application so I am following https://www.electronjs.org/releases/stable closely and unfortunately 13.1.5 is not released yet. 
May I know if where can I ask/find out tentative date for its release, thanks

**Comment by sps-gold** [comment]
I can now find 13.1.5 under github releases
https://github.com/electron/electron/releases/tag/v13.1.5 
page. Also if I try to fetch [latest stable](https://github.com/electron/electron/blob/main/docs/tutorial/electron-versioning.md) I get 13.1.5. So looks good.
However should I still wait to for it to be listed under following before using in production?
https://www.electronjs.org/releases/stable

**Comment by sps-gold** [comment]
no issues, its now listed under stable as well
