### ISSUE TITLE
[TESTING] Bug Bot Issue

### ISSUE THREAD

**Issue by erickzhao** [electron/electron#29503]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0-alpha.10

### What operating system are you using?

Other Linux

### Operating System Version

Linux fedora 5.13.12-200.fc34.x86_64

### What arch are you using?

x64

### Last Known Working Electron version

14.0.0

### Expected Behavior

Should work without error.

### Actual Behavior

In browser console:
```
VM111 renderer_init:81
TypeError: SharedArrayBuffer is not a constructor
    at VM115 worker:96
    at NativeModule.compileForInternalLoader (VM10 loaders:312)
    at nativeModuleRequire (VM10 loaders:341)
    at VM114 node:worker_threads:11
    at NativeModule.compileForInternalLoader (VM10 loaders:312)
    at NativeModule.compileForPublicLoader (VM10 loaders:252)
    at loadNativeModule (VM92 helpers:40)
    at Module._load (VM89 loader:805)
    at Function.c._load (VM108 asar_bundle:5)
    at Function.o._load (VM111 renderer_init:29)
```

### Testcase Gist URL

https://gist.github.com/clavin/0b9f10737f395d36185c71b67c925a49

### Additional Information

...

**Comment by ckerr** [comment]
/bugbot test 11.0.2 12.0.0 10.1.6 linux win32

**Comment by ckerr** [comment]
/bugbot test 11.0.2 12.0.0 10.1.6 linux win32

**Comment by ckerr** [comment]
/bugbot test linux win32 https://gist.github.com/ckerr/d39a473ee00bc5425a2eb4222f48542e

**Comment by ckerr** [comment]
/bugbot test linux win32 https://gist.github.com/ckerr/d39a473ee00bc5425a2eb4222f48542e

**Comment by ckerr** [comment]
/bugbot test linux win32 https://gist.github.com/ckerr/d39a473ee00bc5425a2eb4222f48542e

**Comment by ckerr** [comment]
/bugbot test linux win32 https://gist.github.com/ckerr/d39a473ee00bc5425a2eb4222f48542e

**Comment by ckerr** [comment]
/bugbot bisect linux d39a473ee00bc5425a2eb4222f48542e 11.0.0 11.4.10

**Comment by ckerr** [comment]
/bugbot bisect d39a473ee00bc5425a2eb4222f48542e 10.0.0 11.4.10

**Comment by ckerr** [comment]
https://gist.github.com/ckerr/d39a473ee00bc5425a2eb4222f48542e

**Comment by ckerr** [comment]
/bugbot test https://github.com/electron/electron/issues/29503#issuecomment-885045257 win32 linux

**Comment by ckerr** [comment]
#

**Comment by ckerr** [comment]
/bugbot bisect 642fa8daaebea6044c9079e3f8a46390 8.0.0 15.0.0-nightly.20210719

**Comment by ckerr** [comment]
/msg bugbot test  https://gist.github.com/642fa8daaebea6044c9079e3f8a46390 win32 linux

**Comment by ckerr** [comment]
/msg bugbot test 642fa8daaebea6044c9079e3f8a46390 win32 linux
