### ISSUE TITLE
[Bug]: Node-API native module show non-context-aware  in renderer process

### ISSUE THREAD

**Issue by xland** [electron/electron#29518]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

Do not throw errors

### Actual Behavior

throw errors

### Additional Information

Node-API' doc said:
`All Node-API addons are context-aware, meaning they may be loaded multiple times. `
But the renderer process throw errors
```js
electron/js2c/asar_bundle.js:5 
Uncaught Error: Loading non-context-aware native module in renderer: 
'\\?\D:\project\electron-book2-demo\addonElectron\src\addon\build\Release\addon.node', 
but app.allowRendererProcessReuse is true.
```
My addon's code
```c
#include <node_api.h>

namespace demo
{
    napi_value Method(napi_env env, napi_callback_info args)
    {
        napi_value greeting;
        napi_status status;

        status = napi_create_string_utf8(env, "world", NAPI_AUTO_LENGTH, &greeting);
        if (status != napi_ok)
            return nullptr;
        return greeting;
    }
    NAPI_MODULE_INIT()
    {
        napi_status status;
        napi_value fn;

        status = napi_create_function(env, nullptr, 0, Method, nullptr, &fn);
        if (status != napi_ok)
            return nullptr;

        status = napi_set_named_property(env, exports, "hello", fn);
        if (status != napi_ok)
            return nullptr;
        return exports;
    }
}
```

**Comment by xland** [comment]
`All Node-API addons are context-aware, meaning they may be loaded multiple times.`
is in this document:
[https://nodejs.org/dist/latest-v14.x/docs/api/n-api.html](https://nodejs.org/dist/latest-v14.x/docs/api/n-api.html)

**Comment by xland** [comment]
I know I can set `app.allowRendererProcessReuse = false;` to avoid this error.
but `app.allowRendererProcessReuse` will be removed in the future.
So I think this is a bug.

**Comment by xland** [comment]
Sorry It's my fault.

**Comment by Tombliboo96** [comment]
@xland Hello, may I ask how you solved this problem at that time? I am encountering the same problem now.
