### ISSUE TITLE
Lint against dangling promises

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#29521]
As part of the node 16 upgrade unhandled promise rejections are dispatched as unhandled exceptions and therefore bring down our test runner.  It turns out, we uh, have a lot of these unhandled rejections throughout our tests.  We'll fix the _expected_ ones as part of the Node 16 upgrade but their are countless others than _could_ happen that we should fix ASAP as a follow up.

The [`no-dangling-promises`](https://github.com/electron/electron/pull/new/no-dangling-promises) branch contains the work required to enable the new linting rule.  Running it reveals ~556 errors.  To fix each error we need to either:

#### A. Handle the promise

Either by awaiting it or returning it

#### B. Mark the promise as unrejectable

In some cases a promise is known to never reject, for instance `app.whenReady()` will never reject.  In those cases we can mark the promise return value as `void`.  E.g.

```js
void app.whenReady().then(() => {
  // ... do stuff
});
```

Please only do this if the promise is 100% unrejectable, not just "unlikely to reject".  If it's theoretically possible it one day rejects, just do (A) and handle the promise

**Comment by icestatiozebra** [comment]
Makes sense to me.  I am going to say my prayers now to Jesus Christ-My Lord and Savior... I would be glad to discuss comments regarding Jesus.

**Comment by MarshallOfSound** [comment]
We have this now
