### ISSUE TITLE
[Bug]: Windows explorer restart does not respect BrowserWindow skipTaskbar setting

### ISSUE THREAD

**Issue by ben-polinsky** [electron/electron#29526]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5 / 13.0.1 

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19H2 (18363) and Windows 10 2004

### What arch are you using?

x64

### Expected Behavior

When restarting (or stopping and starting) Windows Explorer, Electron should respect a BrowserWindow's skipTaskbar: true value and not display an icon in the taskbar.

### Actual Behavior

When a BrowserWindow has skipTaskbar set to true and Windows Explorer is restarted, an icon appears in the taskbar. 

### Testcase Gist URL

https://gist.github.com/not-the-car/94ea2fa217d064b23cbe1f5893f3f2bf

### Additional Information

I've provided the fiddle above, but all you need to do is set skipTaskbar to true and restart Explorer through the Task Manager to reproduce.

**Comment by nornagon** [comment]
@zcbenz is this even possible to do? It looks like the current method uses a COM method to remove the icon from the task bar on window construction. How would we detect the explorer.exe restart?

I don't think this issue is "beginner friendly" at all.

**Comment by zcbenz** [comment]
The tray icon implementation is already doing it, all tray icons are recreated when explorer is restarted:
https://github.com/electron/electron/blob/main/shell/browser/ui/win/notify_icon_host.cc#L65-L67

**Comment by nornagon** [comment]
Ah, TIL! That's a handy point of reference.

**Comment by not-the-car** [comment]
I'll attempt to build from source and get a fix in. We'll see how it goes.

**Comment by bruceauyeung** [comment]
problem still exists in electorn 17.0.1 
os:windows 7, windows 10
any plans ?

**Comment by lyswhut** [comment]
Any news?

After restarting explorer, `skipTaskbar` and `setThumbarButtons` will be invalid.

To reproduce:
After setting the above options, open the task manager, find it and restart
![image](https://user-images.githubusercontent.com/20365169/193490232-1b54c5e7-1c8a-4ca7-9fab-8fed4200bec3.png)
Then you need to re-call `win.setSkipTaskbar(true)`, but `win.setThumbarButtons` is no longer valid (although calling it returns true)

**Comment by 6xiaoxin** [comment]
You can try setting "parent: mainWindow. win" in the child window.
