### ISSUE TITLE
The icon and title of my application will change in runtime

### ISSUE THREAD

**Issue by PH8919** [electron/electron#29525]
Hi,
I have used electron v1.6.1 to implement my application on linux platform. Recently I found the icon disappear and the title changes to 'index.html' in the task panel when I do some operation in my application. But I didn't have any code to modify the icon and title in my application except for initialization.
Setting icon using parameter of BrowerWindow like below:
 ` mainWin = new BrowserWindow({
        minWidth: 800,
        minHeight: 600,
        width: 1280,
        height: 768,
        show: false,
        frame: false,
        icon: `${__dirname}/resources/images/logo.png`
    });`
Setting title by '**productName**' in package.json.

**Comment by Prinzhorn** [comment]
> electron v1.6.1

>  electron-bot released this on Feb 21, 2017

:eyes:

**Comment by baconbrad** [comment]
This is a super old version so it is recommended to upgrade. I do not know the specific title behavior of this version but it is likely how Chromium handles navigating to a page with no page title set. Additionally there is a `title` parameter available for `BrowserWindow` and `window.document.title` also works for setting the title.

**Comment by PH8919** [comment]
@Prinzhorn @baconbrad 
We used **redhat6.6** as our server stably, which is set up several years ago and hard to be upgraded because of some reasons, so we are limited to use electron v1.6.1 and the later version can't work on this linux version. Now the previous issue confused me.

**Comment by zcbenz** [comment]
You can use the `page-title-updated` event to prevent the web page from updating the window title.
