### ISSUE TITLE
Can electron desktop application upload to server and run as a website? like accessing pages using url ?

### ISSUE THREAD

**Issue by Thalinda** [electron/electron#29530]
now as far as i can see this is a dumb question yet i  have to verify this can desktop application that build using electron upload  to sever and run as website without much changes like accessing url's and staff ? can we do that

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
