### ISSUE TITLE
[Bug]: Electron throwing an error of not being able to build an image from icon.ico

### ISSUE THREAD

**Issue by SirReadsALot** [electron/electron#29545]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### What arch are you using?

x64

### Expected Behavior

I expected the electron app to work fine after I ran `npm run dist` using electron-builder
also this is the icon code I put in main.js

`icon: "./build/icon.ico"`

### Actual Behavior

It throws an error that it cannot make an image from "./build/icon.ico"

![assets-1](https://user-images.githubusercontent.com/72465167/120830745-dfb2a280-c56f-11eb-8959-8bd949e5cb73.png)

I tried doing something different like:
`const path = require("path")`
`icon: path.join(__dirname, "build/icon.ico")` but this didn't work 

and `icon: "build/icon.ico"` didn't work either

**Comment by zcbenz** [comment]
This issue does not look like an bug of Electron, please seek help from the community of electron-builder instead.
