### ISSUE TITLE
[Bug]: Using setDevToolsWebContents results in DevTools window with no menu triggering

### ISSUE THREAD

**Issue by bedney** [electron/electron#29543]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

unknown

### Expected Behavior

A fully functional DevTools window,  including menus.

### Actual Behavior

No pulldown menus will show in Devtools, either 'right click' menus or menu triggers in Devtools. Since much of the functionality of Devtools is behind menus (right clicking to set conditional breakpoints, navigate to open files that don't currently have a tab, to restart the stack when debugging, enable/disable/clear breakpoints, etc. this is quite a crippling situation.

### Additional Information

At first, I thought this might be related to #10862, but now I'm not sure.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by bedney** [comment]
@codebytere -

Here's a little test case I did up as a super simple Electron project. I didn't use Electron Fiddle but I can redo it using that if you prefer.

The electron.js file contains the JavaScript demonstrating the bug. Do an `npm install` and then `npm run start` and you can see the issue: none of the true 'right click' menus work in Devtools (the little Devtools popups work, but my guess is that those are not 'native platform' constructs). So, for instance, trying to right click on the `<body>` element does not produce a menu.

I have put a flag in the code in `electron.js` called `useCustomDebugWindow`. It is initially set to `true`. If you flip that to `false`, then you'll see that the code does **not** try to use a 'custom window' for Devtools and instead just does the default. The right-click menus are fully functional now.

Thank you for taking a look at this! I really appreciate it!

Cheers,

-Bill

[customdebugwindow.zip](https://github.com/electron/electron/files/6643175/customdebugwindow.zip)

**Comment by bedney** [comment]
@codebytere -

Is there more I need to supply to keep this issue open? I really didn't want it to be auto-closed.

Thanks!

Cheers,

- Bill

**Comment by nornagon** [comment]
Here's a gist version of the above repro, further reduced: https://gist.github.com/1e0b64ea1071d92b92d03e99052bae44

I can reproduce this.

**Comment by bedney** [comment]
Thank you @codebytere and @nornagon !!
