### ISSUE TITLE
[Bug]: Cut, copy and paste keyboard shortcuts in a Devtools Console will cause Electron to crash

### ISSUE THREAD

**Issue by bedney** [electron/electron#29558]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur, version 11.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

unknown

### Expected Behavior

Cut, copy and paste keyboard shortcuts to work in the Devtools Console to work as they normally would.

### Actual Behavior

Using any of these keyboard shortcuts (on the Mac, Cmd-X, Cmd-C or Cmd-V) cause Electron to completely crash, exiting with the following message:

```
Cannot read property '0' of undefined (undefined)
```

Note that cut, copy and paste work correctly if accessed via the right-click menu.

**Comment by codebytere** [comment]
@bedney can you please provide a reproducible sample of what you ran to cause the error? I can't reproduce this as is.

**Comment by bedney** [comment]
Note that this happens outside of the Devtools context as well (in my application) (which is obvious to me now since it's a global menu handler ;-) ).

**Comment by bedney** [comment]
On further investigation, it turns out that we had a handler that catches uncaught exceptions and exits the process.

So... my bad.

Sorry for the noise @codebytere.

(slinks off with tail between his legs...)
