### ISSUE TITLE
[Bug]: Printtopdf fails if no printing device is set up in Windows

### ISSUE THREAD

**Issue by yusefhassan** [electron/electron#29572]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 20H2

### What arch are you using?

x64

### Expected Behavior

WebContents printToPDF should work even if there is no printing device configured in the operating system.

### Actual Behavior

When the user does not have any printing device configured in his operating system (neither printers, nor "Microsoft Print to PDF"...), when calling printToPDF function the application freezes (no error message is displayed).

I have tested it on Windows, Mac and Linux, and it only happens on Windows.

### Testcase Gist URL

[https://gist.github.com/a8e5af265be79ac22326a10670240abe](https://gist.github.com/a8e5af265be79ac22326a10670240abe)

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by yusefhassan** [comment]
Hi, I have just added the testcase Gist URL.

**Comment by zcbenz** [comment]
Can you check if 12 and 14 versions also have this problem?

**Comment by yusefhassan** [comment]
Yes, I just tested, Electron 12.0.11 and 14.0.0.-beta.1 have the same problem.

**Comment by vtumi** [comment]
up

**Comment by vtumi** [comment]
Electron 6.1.9 is work.
Electron > 7.0 have the same problem.

**Comment by SinLT** [comment]
I have the same problem.

**Comment by deng81416754** [comment]
I have the same problem.
