### ISSUE TITLE
[Feature Request]: Add frame / controls on frameless window child

### ISSUE THREAD

**Issue by jpneey** [electron/electron#29579]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am working on a frameless and fullscreen Electron App.I am initializing a browser window with the following configuration:
```
let window = new BrowserWindow({
    resizable: false,
    fullscreen: true,
    minimizable: false,
    frame: false
})
```
This works well unless the app opens a link of a `PDF file` on` a new tab`(which will create a new child window in electron). Since the `BrowserWindow` is `frameless `and `fullscreen`, the PDF page is also `fullscreened `and `frameless `thus `closing the child window hard`. One way to close it is using` ALT + f4` or hovering the window on the taskbar and clicking x after Alt + tab on it's preview on Windows 10.

Right now, I'm catching all links that opens on a new tab end embedding it inside a div on my main app with an iframe so they can still benefit from the custom controls I've written.

### Proposed Solution

Have a way to instruct electron to add the custom controls / parameters on child windows

### Alternatives Considered

Have a setting to add controls on all child windows if `fullscreen` and `frameless` is used

### Additional Information

This is not limited on PDF pages, any link opened on a new tab inherits the main window's framelessness. It would be nice if we can have control or override the parameters on for window children

**Comment by MarshallOfSound** [comment]
This is already possible, see https://www.electronjs.org/docs/api/web-contents#contentssetwindowopenhandlerhandler you can override the window options for child windows 👍
