### ISSUE TITLE
Docs website is missing images

### ISSUE THREAD

**Issue by OmgImAlexis** [electron/electron#29580]
This didn't seem to fit any of the issue templates given.

The two images in this document are missing on the site and return a 404.

https://github.com/electron/electron/blob/main/docs/tutorial/performance.md#1-carelessly-including-modules
https://www.electronjs.org/docs/tutorial/performance#1-carelessly-including-modules

**Comment by RaisinTen** [comment]
PR: https://github.com/electron/electron/pull/29592
