### ISSUE TITLE
[Bug]: Messages bug

### ISSUE THREAD

**Issue by RobloxCurry3ef** [electron/electron#29587]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

3.1.0

### Expected Behavior

I expected to click load more messages and see the messages.

### Actual Behavior

I clicked load more messages and nothing happened.

**Comment by codebytere** [comment]
> I expected to click load more messages and see the messages.

I have no idea what this means - please provide a reproducible sample and screenshots to illustrate the issue or we will be forced to close it as insufficient to triage. Thank you for your cooperation!

**Comment by nornagon** [comment]
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).
