### ISSUE TITLE
[Bug]: JS Error when quitting app

### ISSUE THREAD

**Issue by roryabraham** [electron/electron#29584]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.8

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.4

### What arch are you using?

x64

### Last Known Working Electron version

9.2.0

### Expected Behavior

The app closes without error.

### Actual Behavior

When closing the app via `CMD + Q`, we got this error:

![image](https://user-images.githubusercontent.com/47436092/121132484-0ed24980-c7e6-11eb-8782-d4eb09e829da.png)

Sorry, no Gist because I don't _really_ understand how to consistently reproduce this error. But we have only a small amount of Electron-specific code, 90% of which is right [here](https://github.com/Expensify/Expensify.cash/blob/47a08e0f653b87860b1b020e5ebe898ebc20a0a8/desktop/main.js). The PR that fixed the problem for me is right [here](https://github.com/Expensify/Expensify.cash/pull/3416), and it seems like something that I _probably_ shouldn't have to do, but I'm not sure.

### Additional Information

We're using Electron at Expensify as part of our [cross-platform React Native rebuild of our front-end product](https://github.com/Expensify/Expensify.cash). Last week, [I updated our Electron dependency from `9.2.0` to `11.4.8`](https://github.com/Expensify/Expensify.cash/pull/3361), and [this error](https://github.com/Expensify/Expensify.cash/issues/3388) started happening. I was able to fix it via [this small PR](https://github.com/Expensify/Expensify.cash/pull/3416), but given that this wasn't happening in `9.2.0`, I wanted to report it in case it is in fact a bug.

My (layman's) understanding of the problem at hand is that:

1. Synchronous request is made from renderer process -> main process
1. User quits the app, and the main process destroys the browserWindow
1. The main process isn't dead yet, and it tries to process the request from the renderer process. It calls `browserWindow.isFocused()`, but the browserWindow is destroyed, so it doesn't work

So I fixed it by first calling `browserWindow.isDestroyed` before trying to call `browserWindow.isFocused`. Is this the expected behavior or a bug?

**Comment by pushkin-** [comment]
I'm not on the Electron team, but it seems correct that you have to check `isDestroyed()` before invoking methods on the destroyed window.

**Comment by roryabraham** [comment]
Yeah, that's what I've found – I'm just wondering if that's expected or if the Electron team wants to make things a bit easier by adding that check internally in some functions. For example, `browserWindow.isFocused()` should always be false if the window is destroyed, and it would be nice if it just returned false instead of throwing an error.

**Comment by Lefttechy1** [comment]
****

**Comment by MarshallOfSound** [comment]
The window being destroyed, and the window not being focused are inherently different states depending on the implementation in question.  Hiding the fact you're trying to use a destroyed window isn't ideal so I don't think we're gonna change that behavior.  In general if you can't guarantee the lifetime of the window you're using, you have to check `isDestroyed` before using it.

**Comment by roryabraham** [comment]
Thanks!
