### ISSUE TITLE
[Bug]: Windows10: shell.trashItem fails with "Failed to create FileOperation instance"

### ISSUE THREAD

**Issue by dscalzi** [electron/electron#29598]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 21H1 (OS Build 19043.985)

### What arch are you using?

x64

### Last Known Working Electron version

~~12.0.10~~ Deletes worked on 12.0.10 until I upgraded. Now reverting still produces the issue.

### Expected Behavior

shell.trashItem should move the file at the specified path to the recycling bin without failure.

### Actual Behavior

shell.trashItem fails in all cases with the error message: Failed to create FileOperation instance. The path to the file is correct and a file exists at the path.

### Testcase Gist URL

https://gist.github.com/dscalzi/240bfd99d0de37efcc700d240133db5a

### Additional Information

~~As noted, the exact same code functioned correctly on version 12.0.10. I am unable to complete an upgrade to v13 due to this issue.~~

Edit: After switching back to electron 12.0.10 on fiddle I am getting the same issue. I'm not sure why.. I am able to delete the file fine through the file explorer. The error message isnt very descriptive either.

I have only tested on Windows 10.

**Comment by dscalzi** [comment]
Possibly related? https://github.com/electron/electron/pull/28748

**Comment by zcbenz** [comment]
Do old versions <= 11 work?

**Comment by dscalzi** [comment]
@zcbenz no it did not work in 11 (had to switch back to shell.moveItemToTrash for 11).

Not sure why it's failing.. is anyone able to try this on an up to date windows machine..?

**Comment by nornagon** [comment]
#28787 is in v13.0.0+ and v12.0.6+ so it doesn't seem likely that that PR is related.

**Comment by nornagon** [comment]
I think this is a dupe of #28831.

**Comment by nornagon** [comment]
Duplicate of #28831

**Comment by dscalzi** [comment]
@nornagon This is not a duplicate of that issue. The error messages are completely different. Change the file path to `D:\\DeleteMe\\this.txt` in my gist and you still get `Uncaught (in promise) Error: Failed to create FileOperation instance`

Please reopen...

**Comment by dscalzi** [comment]
Perhaps to bring some clarity to this a more useful error message could be added, ie exactly what went wrong (stacktrace) such that the FileOperation instance could not be created..?

**Comment by lishid** [comment]
I can repro as well. Only happens in renderer process. The error message is also `Failed to create FileOperation instance`.

I'm working around this issue with an IPC to main process instead.

**Comment by nornagon** [comment]
Hm, it looks like this happens when `CoCreateInstance` fails: https://github.com/electron/electron/blob/0cb5631b0b5de09878bb0d9f6cb36d146b23b7a9/shell/common/platform_util_win.cc#L357-L359

it seems that call has nothing to do with the path, so perhaps it's related to COM access from the renderer...?

**Comment by sytolk** [comment]
I can confirm that this happened in renderer process only. Like temporary solution you can move this operation in main process: https://www.electronjs.org/docs/api/ipc-main

**Comment by nornagon** [comment]
Perhaps the built-in method should delegate to the main process, too.

**Comment by jordanamr** [comment]
Can confirm

**Comment by alexanderkasten** [comment]
Problem still exists for me

**Comment by dscalzi** [comment]
Any update?

**Comment by bkervaski** [comment]
> Any update?

You can just ipc the operation over to the main process, works fine.  It's just the renderer that is being blocked from that type of file op.

**Comment by dscalzi** [comment]
Wondering if the documentation should just be updated noting that shell.trashItem only works in the main process? If so this can be closed.

**Comment by fabiospampinato** [comment]
This is a pretty big issue IMO, now every app that gracefully moved stuff to the trash just stopped being able to delete files under Windows.

**Comment by fabiospampinato** [comment]
I'm not sure why but after moving the function call to the main process I'm now able to delete files from regular folders (e.g. the desktop) again, but I have a folder in the local machine mapped into the Windows VM and it still fails to delete fails into that.

**Comment by dscalzi** [comment]
Still an issue to the best of my knowledge. Can only trash an item in the main process

**Comment by CodeSmith32** [comment]
This is still an issue as of electron 20.0.0.
Again, it works fine in the Main process.

If this is not along the immediate roadmap, then *please* at least remove access to it from the Renderer process and clarify in the docs that it's only accessible from the Main process. Right now, the functionality is plain broken on Windows, which is definitely a bug, **and it becomes much worse if a developer writes and tests an app on a non-Windows machine but afterward releases it for Windows.**

**Comment by CodeSmith32** [comment]
Bump:

I've confirmed this is still an issue as of Electron 22.2.0.

**Comment by dscalzi** [comment]
Any ideas?

**Comment by dscalzi** [comment]
AFAIK still an issue

**Comment by benbowler** [comment]
Yes this is still an issue 22nd August

**Comment by sytolk** [comment]
bump
