### ISSUE TITLE
[Bug]: Keytar behavior change

### ISSUE THREAD

**Issue by rpatrick00** [electron/electron#29593]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.1

### What operating system are you using?

macOS

### Operating System Version

10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

12.0.5

### Expected Behavior

Our app uses keytar to store a large number of credentials in the Native OS's credential store (e.g., keychain on MacOS).  We load all of the credentials at startup and store any changed values at each save.  This works fine in electron 12.0.5. 

### Actual Behavior

When we tried to upgrade to 13.1.1, the user is prompts _n_ times to enter their password (where _n_ matches the number of credentials they have in their project--which could be hundreds).

While prompting the user because the app wants access to the credential store is reasonable, prompting for every single credential lookup is not.  Is there a way to eliminate the multiple prompts?

**Comment by MarshallOfSound** [comment]
`keytar` is a third party module and not directly supported or maintained by the Electron project.  Any issues with that module should be raised on it's issue tracker rather than ours
