### ISSUE TITLE
print function

### ISSUE THREAD

**Issue by tiitremmel** [electron/electron#296]
How to print current page?
window.print() does nothing. Any suggestions?

**Comment by kirubasankars** [comment]
+1 for this feature

**Comment by macdasi** [comment]
+1

**Comment by gabguy** [comment]
+1

**Comment by manyeung** [comment]
+1 for this feature

**Comment by MarshallOfSound** [comment]
@kirubasankars @macdasi @gabguy Can you guys not see that this issue is resolved in #599 ?

**Comment by macdasi** [comment]
@kirubasankars from which version ?

**Comment by blowsie** [comment]
A useful link for anyone reading this ticket
https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsprintoptions
