### ISSUE TITLE
[Bug]: Setting BrowserView size before loading URL has no effect

### ISSUE THREAD

**Issue by rayanry9** [electron/electron#29607]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 2004

### What arch are you using?

x64

### Expected Behavior

```
const { BrowserView, BrowserWindow } = require('electron')

const win = new BrowserWindow({ width: 800, height: 600 })

const view = new BrowserView()
view.setBounds({ x: 0, y: 0, width: 300, height: 300 })
view.webContents.loadURL('https://electronjs.org')

win.setBrowserView(view)
```

Expected the view to be loaded into the window.

### Actual Behavior

The BrowserView is not loaded by the renderer.

**Comment by rayanry9** [comment]
@zcbenz it actually has effect.. if i open devtools of the browserView after the win.setBrowserView() , the view will be loaded perfectly

**Comment by nornagon** [comment]
In fiddle form for easy reproing: https://gist.github.com/e422f7fddcb89a95a1ad9c638647e6db
