### ISSUE TITLE
new warning in main: Not implemented reached in virtual bool base::PowerMonitorDeviceSource::IsOnBatteryPower

### ISSUE THREAD

**Issue by ckerr** [electron/electron#29614]
[2212055:0609/095801.855559:ERROR:power_monitor_device_source_stub.cc(11)] Not implemented reached in virtual bool base::PowerMonitorDeviceSource::IsOnBatteryPower()

**Comment by dsanders11** [comment]
Maybe related to #29291?

**Comment by codebytere** [comment]
Looks like this [isn't implemented on Linux](https://source.chromium.org/search?q=PowerMonitorDeviceSource::IsOnBatteryPower&ss=chromium) - we should probably either return false for Linux and update docs

**Comment by ckerr** [comment]
So there are at least two things going on here.

One is that https://github.com/electron/electron/pull/26494 added public support for this function in Electron. :+1: on updating the docs to reflect that it's not supported on Linux. (It's already returning `false`, albeit with a NOTREACHED() warning when warnings are enabled, via power_monitor_device_source_stub.cc)

Second is that upstream is reaching this codepath on its own as of https://chromium-review.googlesource.com/c/chromium/src/+/2769179 (Merged Mar 25) which now ensures that IsOnBatteryPower() is called from PowerMonitor::Initialize(), which wasn't the case before.

I added a tracer `abort();` before the NOTREACHED warning to force a more explicit backtrace. That build crashes as soon as it's started:

```
#5 0x7fdac3b4e864 abort
#6 0x56125b070b39 uv__cancelled
#7 0x56125ef9a941 base::PowerMonitor::Initialize()
#8 0x56125c7397b3 content::ContentMainRunnerImpl::RunBrowser()
#9 0x56125c73956f content::ContentMainRunnerImpl::Run()
#10 0x56125c7372ec content::RunContentProcess()
#11 0x56125c7373cc content::ContentMain()
#12 0x56125b0864c7 main
```

Maybe this part should be reported upstream? If I'm reading this correctly, any debug Linux build of Chromium would also hit this error.

**Comment by ckerr** [comment]
As an aside, there exists a way to query this that should work on all our supported Linux platforms, even back to the oldest releases -- we can query the `OnBattery` property of the `org.freedesktop.UPower` object on the system bus:

```
dbus-send \
  --print-reply \
  --system \
  --dest=org.freedesktop.UPower \
  /org/freedesktop/UPower \
  org.freedesktop.DBus.Properties.Get \
  string:org.freedesktop.UPower \
  string:OnBattery
```

(Translated into pseudo-English: "Hello Linux, please ask org.freedesktop.UPower, which is on the system bus, the value of its OnBattery property".) I've confirmed this works on all the Linux platforms Electron supports (Debian 8, Ubuntu 14.04, Fedora 24):

![dbus-send-upower-on-battery-debian-8](https://user-images.githubusercontent.com/70381/122331309-3a49e800-cefa-11eb-8ced-bbcc58692b16.png)
![dbus-send-upower-on-battery-ubuntu-14 04](https://user-images.githubusercontent.com/70381/122331314-3cac4200-cefa-11eb-8ffb-36a0b80bb386.png)
![dbus-send-upower-on-fedora-8](https://user-images.githubusercontent.com/70381/122331318-3e760580-cefa-11eb-9806-11870eaadc1c.png)

In each of these cases, the property returned `false` because my battery was charging.

So, I think we can implement this for at least ourselves. Chromium also supports openSUSE 13.3, which I haven't tried yet but II I'd expect the same results there. If so, maybe upstream would also be interested in a `power_monitor_device_source_linux.cc` for this.
