### ISSUE TITLE
[Feature Request]: nativeImage webp support

### ISSUE THREAD

**Issue by Araxeus** [electron/electron#29619]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

nativeImage currently support only jpg and png

### Proposed Solution

nativeImage should also support webp format
([svg](https://github.com/electron/electron/issues/9642) and gif could also be nice)

### Additional Information

webp is used by many in 2021 (github, google, apple, whatsapp, etc..) and getting more popular by the day
this could help many people

**Comment by nornagon** [comment]
Unfortunately the underlying APIs we are using here are not the same ones as present in the renderer process (specifically, `gfx::PNGCodec` and `gfx::JPEGCodec` in Chromium), and there's no equivalent webp decoder. So adding this sort of support is not trivial.

nativeImage in Electron is a somewhat niche API, and the encoding/decoding parts are only really used for app and tray icons. Do you have a particular reason to store your app's icon as webp?

If icon storage isn't your use case, can you expand on what you'd expect to use this for?

**Comment by BlackHole1** [comment]
update: chromium has implemented webp codec: https://chromium.googlesource.com/chromium/src/+/4567513517c7648de73cf007bb71eb4edf72bfd4

**Comment by codebytere** [comment]
Closing this as it's not an expectation in the near or intermediate future. Chromium implemented _partial_ codec logic for webp: `Encode,  but we need `Decode` and so there's no path forward here now. If something changes, happy to reconsider.
