### ISSUE TITLE
[Bug]: Initially setting resizable to false will maximize the border

### ISSUE THREAD

**Issue by whaoa** [electron/electron#29623]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.10

### What operating system are you using?

Windows

### Operating System Version

Windows 10 2004 (19041.985)

### What arch are you using?

x64

### Last Known Working Electron version

11.4.2

### Expected Behavior

When I call `win.setResizable()` before executing `win.maximize()` when maximising the window, the window can be maximized normally.

### Actual Behavior

Sorry, my English is not very good, I hope you can understand what I want to express

I created an Electron App through [vue-cli-plugin-electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder).

When I create an `frameless` window using `frame: false`, I Call `win.setResizable()` before executing `win.maximize()` When you maximize the window, a border appears around webContent.

Testing `v11.4.2` seems to be the last normal release, but this version also has the same problem with double-clicking the drag-and-drop area.

Here [#25746](https://github.com/electron/electron/issues/25746) seems to have a similar problem.

### Additional Information

my code:

```javascript
const win = new BrowserWindow({
    width: 800,
    height: 600,
    frame: false,
    resizable: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      // Use pluginOptions.nodeIntegration, leave this alone
      // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration for more info
      nodeIntegration: !!process.env.ELECTRON_NODE_INTEGRATION,
      contextIsolation: false
    }
})

ipcMain.handle('max', function (event) {
    win?.setResizable(true)
    win?.maximize()
})

ipcMain.handle('unmax', function (event) {
    win?.unmaximize()
})
```

v11.4.2:

![image](https://user-images.githubusercontent.com/62391436/121475049-85926100-c9f7-11eb-8186-e6664004997a.png)

v12.0.10

![image](https://user-images.githubusercontent.com/62391436/121475288-cb4f2980-c9f7-11eb-8061-7e7157570c9b.png)

**Comment by whaoa** [comment]
This doesn’t seem to be a problem in version 12.0.0

**Comment by weifeiyue** [comment]
I encountered the same problem and hope it can be fixed soon @zcbenz
