### ISSUE TITLE
[Feature Request]: Can contextBridge.exposeInMainWorld support functions with custom properties?

### ISSUE THREAD

**Issue by Qrysto** [electron/electron#29624]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently if you pass a function with custom properties through `contextBridge.exposeInMainWorld`, the funciton goes through but its properties won't. For example:

```
// In preload script
function test() {
  console.log('works')
}
test.x = 1;
contextBridge.exposeInMainWorld('api', {
  test: test
})

// In main world
api.test(); // works
console.log(api.test.x) // undefined
```

### Proposed Solution

Make `contextBridge.exposeInMainWorld` keep all function properties when passing functions through the bridge

### Alternatives Considered

None

### Additional Information

None

**Comment by MarshallOfSound** [comment]
This is not technically possible or supported.  It's effectively the same as a custom prototype and therefore it's dropped when going over the bridge.

Simple objects can be transferred, or literal promise / function values.  We won't support modifications to complex objects like functions
