### ISSUE TITLE
[Bug]: backgroundThrottling: false causes window to become unresponsive after restoring

### ISSUE THREAD

**Issue by AndrewMuise** [electron/electron#29646]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.11

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 20H2

### What arch are you using?

x64

### Expected Behavior

`backgroundThrottling: false` will not prevent a window from receiving clicks or being draggable, regardless of options used to create the window

### Actual Behavior

When adding `backgroundThrottling: false` to a transparent, frameless and unfocusable window, the window will become undragable and not respond to clicks

### Testcase Gist URL

https://gist.github.com/AndrewMuise/055317f183ead7e65f6eb05129882021

### Additional Information

From the gist reproduction steps are as follows

1. Note that hovering over the buttons changes the background colour, you can drag the window by grabbing inside the border and moving around
2. Click the `Minimize` button. the window will minimize and restore after 2 seconds
3. Hover effects still work, `Quit` will close the application. you can still drag the window by dragging around the body
4. Focus any other window, like selecting this very window
5. Returning to the fiddle, you will now be unable to drag the window, or interact with the buttons, however the hover will still change the background colour

**Comment by OwnageBanana** [comment]
In addition to that gist, swapping out :


  ipcMain.on("minimize-me", () =&gt; {    mainWindow.minimize()    setTimeout(() =&gt; mainWindow.restore(), 2000)  })


with 



  ipcMain.on("minimize-me", () =&gt; {    mainWindow.hide()    setTimeout(() =&gt; mainWindow.show(), 2000)  })



Should not prevent clicks on the window following the repo steps in this issue, though if you have it in the app dock, I found right clicking the icon can cause the same issue
