### ISSUE TITLE
[Bug]: focusable:false BrowserWindow still makes OSX try to focus it

### ISSUE THREAD

**Issue by ibc** [electron/electron#29644]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0 ... 27.0.4

### What operating system are you using?

macOS (2019, Intel and M1)

### Operating System Version

BigSur 11.2.3 ... Sonoma 14

### What arch are you using?

x64 and ARM

### Last Known Working Electron version

none

### Expected Behavior

These are the steps to reproduce:

- Run a Electron application that opens two `BrowserWindow`:
  - `window1` should have `focusable: false` in its `BrowserWindowOptions`.
  - `window2` should have `focusable: true` in its `BrowserWindowOptions`.
- Have 2 spaces in OSX:
  - Space 1 should just contain `window1` window and should not contain any other window of any other app.
  - Space 2 should contain `window2` and any other app window (Chrome for example).
- Be in space 2 and ensure `window2` does NOT have the focus.
- Switch to space 1.

Expected Behaviour:

- OSX should switch to space 1 and stay there, and OSX top bar should show "Finder" (since there isn't any focusable app window in space 1).

### Actual Behavior

- OSX switches to space 1 and **immediately** switches back to space 2 and focuses our `window2` (which was created with `focusable: true`).

### Testcase Gist URL

Using the `visibleOnAllWorkspaces` option is a simple way to demonstrate this. Electron Fiddle gist:

https://gist.github.com/78a51f4678cb61f0fac901f91f3d9ed4

(see video below in [comments](https://github.com/electron/electron/issues/29644#issuecomment-859712978))

### Additional Information

It looks like, even if `window1` was created with `focusable: false`, this is just known by Electron. OSX seems to **not** know it. So AFAIS this is what it happens:

- Let me insist that, before switching from space 2 to space 1, the focus should NOT be in our `window2` but in any other app window (let's say Chrome).
- When user switches to space 1, OSX tries to find and focus a Chrome window in space 1.
- However there is no Chrome windows in space 1 so OSX tries to find any other suitable window to focus it.
- And it finds our `window1` which was created with `focusable: false`. However it looks like OSX doesn't know about it and tries to focus it anyway.
- So our Electron app gets the focus, it realizes that `window1` is not focusable and gives the focus to any other Electron window (our `window2`), and hence it switches back to space 2 again (ping-pong visual effect here).

I've confirmed that the scenario I describe above works fine (as expected) in other native apps: they can display "windows" that allow click events but do never get the focus and do not make OSX feel that they can be focused.

**Comment by AndrewMuise** [comment]
I can confirm this is also an issue on 11.x.x as well

**Comment by samuelmaddock** [comment]
The problem occurs when a focusable window exists in one space while an unfocusable window exists in another. If the workspace with the unfocusable window contains no other application windows, the focusable window in the other workspace will steal focus.

Using the `visibleOnAllWorkspaces` option is a simple way to demonstrate this. Electron Fiddle gist: https://gist.github.com/78a51f4678cb61f0fac901f91f3d9ed4

https://user-images.githubusercontent.com/1656324/121722213-272ab880-cab3-11eb-8012-9e5505202f08.mov

**Comment by ibc** [comment]
Is there any news or at least some feedback/comment about this issue?

**Comment by nikcheerla** [comment]
bump ... has anyone looked into this issue yet? Are there any quick fixes?

**Comment by ibc** [comment]
Same behavior in Electron 19

**Comment by ibc** [comment]
Bump. This issue is reproducible with all versions of Electron including last one.

**Comment by AndrewMuise** [comment]
For my use case making all the windows unfocusable worked out, but that might not be a viable solution for others. It's definitely still an issue

**Comment by ibc** [comment]
Hello developers, any news? or at least any comment or whatever? this issue is real and has basically been completely ignored since reported 2 years ago.

**Comment by ibc** [comment]
Bump. This issue is reproducible with all versions of Electron including last one.

**Comment by ibc** [comment]
Bump again. This issue is reproducible with all versions of Electron including last one.

**Comment by ibc** [comment]
Despite I've tried everything it is impossible to make an Electron app NOT steal the focus when clicking on a non `focusable` window. It looks like indeed the non `focusable` window doesn't get the focus, but the Electron app gets the focus anyway **even if there is no other `focusable` window in the app**.

Anyway I assume I should give up because this properly documented (STR included) issue hasn't got any comment from devs in 3 years.

**Comment by ibc** [comment]
I'm closing this issue because it's mac OS behavior (terrible behavior in my opinion). The exact same issue can be reproduced with a simple Cocoa app. The rationale is the following:

1. I'm in space 1, where Safari is the active app.
2. I swipe to space 2, where Safari doesn't have a window.
3. macOS thinks "oh no, the currently active app doesn't have a presence in the new space, I have to find another app to activate!".
4. macOS sees that there's a single app which has a presence on space 2, so it **activates** it!
5. My app is activated, and thinks "ok, I've been activated, so I need to find a window which I can give keyboard focus to".
6. The non-focusable window cannot be it, because it has `canBecomeKeyWindow` overridden to `false`, so it must be the other window which has `canBecomeKeyWindow = true`. Ok, let's make this the key window!
7. But now macOS sees that the window that's becoming the key window is in another space! So macOS switches to the space that contains the key window.
