### ISSUE TITLE
[Bug]:  Electron Fail to install on FreeBSD11 due to broken URL

### ISSUE THREAD

**Issue by Spikkels** [electron/electron#29643]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.8

### What operating system are you using?

Other (specify below)

### Operating System Version

FreeBSD 11

### What arch are you using?

x64

### Expected Behavior

Electron version should install.  URL should not be broken when installing electron.

### Actual Behavior

I am getting the following 404 error when trying to install electron with react-devtools on FreeBSD 11.
The link is broken. Please fix. 

HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/release/download/v11.4.8/electron-v11.4.8-freebsd-x64.zip

To reproduce run the following command on FreeBSD11.
yarn add react-devtools electron --dev

**Comment by nornagon** [comment]
We don't support freebsd.
