### ISSUE TITLE
Copy files or images in app to the system pasteboard

### ISSUE THREAD

**Issue by songuu** [electron/electron#29640]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

when i use clipboard writeBuffer to copy files or images in app to the system pasteboard, it didn't work.

### Proposed Solution

It should be in system pasteboard.

### Alternatives Considered

I don't konw how to make it work.Is there any other way to achieve it?

### Additional Information

.

**Comment by zcbenz** [comment]
Please use the `clipboard.writeImage` API to write images. For writing files, it is currently not supported, please check https://github.com/electron/electron/issues/9035 for more information.
