### ISSUE TITLE
[Feature Request]: Add SMTC Media Length support

### ISSUE THREAD

**Issue by cryptofyre** [electron/electron#29658]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Microsoft recently introduced the ability to specify the song length and seek bar for media items that will show when pressing media keys on Windows 10 and I noticed that Electron apps or any Chromium based app for that matter lacks proper SMTC media length.

ex.
Non Functioning (Electron):

![image](https://user-images.githubusercontent.com/33162551/121789736-07bc8a00-cb9e-11eb-904e-adfff8a73cb0.png)

Functioning (UWP):
![image](https://user-images.githubusercontent.com/33162551/121789766-48b49e80-cb9e-11eb-83e0-05c15c23f3ab.png)

### Proposed Solution

I'd like to see Media Length be provided to the Windows SMTC data it sends as it would provide a lot of third party apps to get the information of the media that is currently playing. I'm not sure how this is implemented within standard Electron or Chromium for that matter i'm not really sure how to go about with a solution unless its possible just an option in the API that hasn't been populated.

### Alternatives Considered

I was planning on using this [node module](https://www.npmjs.com/package/@nodert-win10-20h1/windows.media) but it appeared too difficult and not really viable in the way i'm using everything else.

### Additional Information

Possibly adding the ability to manually add SMTC data within the main process would be a nice touch too. Keep up the great work!

**Comment by MarshallOfSound** [comment]
> or any Chromium based app for that matter lacks proper SMTC media length.

This functionality is provided by Chromium and if the same issue exists in Chrome you should raise a bug upstream. (crbug.com)
