### ISSUE TITLE
[Bug]: Electron sometimes displays a white bar of about 10px in fullscreen mode.

### ISSUE THREAD

**Issue by meteor199** [electron/electron#29659]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.11

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1 (19043.1052)

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

Not show white bar

### Actual Behavior

Electron sometimes displays a white bar of about 10px in fullscreen mode.

Steps to reproduce:
1. When creating a window, set `maximizable` and `resizable` to false.
```
  mainWindow = new BrowserWindow({
    frame: false,
    maximizable: false,
    resizable: false,
    width: 600,
    height: 800,
  });
```
2. Set these two to `true` later, and then call the `maximize` method 

```
  mainWindow.setResizable(true)
  mainWindow.setMaximizable(true);
  mainWindow.maximize();
```
![image](https://user-images.githubusercontent.com/21106029/121804097-50944180-cc77-11eb-8a53-7cb2ae62feac.png)

### Testcase Gist URL

https://github.com/meteor199/issue-electron-white-border

**Comment by zcbenz** [comment]
The "Electron Version" and "Last Known Working Electron version" are the same.

Can you clarify which version of Electron is having this bug, and which versions are working fine?

**Comment by meteor199** [comment]
Sorry, I have changed the issue. I tried 6.x, 12.x, 13.x, all have this problem

**Comment by sertxudev** [comment]
Also shows a black border at left, right and bottom.
![image](https://user-images.githubusercontent.com/22801379/122033707-117a0380-cdd1-11eb-8c68-8f8eb43ca4b0.png)

**Comment by ez5393ez** [comment]
Remove working wire services

**Comment by ez5393ez** [comment]
Delete
