### ISSUE TITLE
[Bug]: Electron vs ES6 conflicts

### ISSUE THREAD

**Issue by murtazaali1999** [electron/electron#29657]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

It should allow me to import all es6 modules

### Actual Behavior

Im trying to use ES6 with electron. When I build my project it doesnt even allow me to import es6 modules

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by murtazaali1999** [comment]
@MarshallOfSound, This is my reference:
![b2](https://user-images.githubusercontent.com/61330248/121861656-6e16e900-cd13-11eb-987b-978021219621.PNG)
![b1](https://user-images.githubusercontent.com/61330248/121861618-66574480-cd13-11eb-9b35-c5e22491dd49.PNG)
![sniper](https://user-images.githubusercontent.com/61330248/121862007-d665ca80-cd13-11eb-9c34-45a5c1b03e92.PNG)

It occurs when I'm creating a project standalone on Electron and Js. I npm install Electron's latest version and try to use Import, As it is part of E6 module. I've tried using the solutions on the web and on GitHub but still couldn't find the correct solution. Yesterday I created a Vue + Electron app. That issue was not existent. I also provided evidence above. I think I saw 2 or maybe 3 GitHub users post this issue on Electron's repo. I can send you the files via email. The main problem in my opinion relies on the loader of electron-js. Aside from that issue, It doesn't allow to directly import, e.g: 
I have to Import like this

import imagemin from './node_modules/imagemin/index.js'; 
Instead of 
import imagemin from './imagemin';

**Comment by zcbenz** [comment]
Can you provide a minimal app that does not use any third party modules to reproduce the problem? It is possible that this is not a bug of Electron, but caused by the modules you used in your app.

**Comment by murtazaali1999** [comment]
@zcbenz, This is the link to the mini-app:
https://drive.google.com/file/d/1YQ0wCcHGG2i2ZVqXJ8U6znODzVzd0QkD/view?usp=sharing

**Comment by zcbenz** [comment]
The URL requires permission to access. can you upload the app to https://gist.github.com instead?

**Comment by murtazaali1999** [comment]
https://gist.github.com/murtazaali1999/acdb564f0b66eb30afd484d08d23eca9

**Comment by murtazaali1999** [comment]
Has it been resolved ?
