### ISSUE TITLE
The using-selenium-and-webdriver tutorial is outdated

### ISSUE THREAD

**Issue by DrNio13** [electron/electron#29652]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7 (19H114)

### What arch are you using?

x64

### Expected Behavior

After cloning Quick Start example `https://github.com/electron/electron-quick-start`, building the binaries and following the testing guide of Electron for WebDriverIO (https://www.electronjs.org/docs/tutorial/using-selenium-and-webdriver#setting-up-with-webdriverio code is copy-paste Electron docs #setting-up-with-webdriverio and only changed the path to the binary of Electron browser ) 

      // test.js
      const webdriverio = require('webdriverio')
      const options = {
          host: 'localhost', // Use localhost as chrome driver server
          port: 9515, // "9515" is the port opened by chrome driver.
          desiredCapabilities: {
              browserName: 'chrome',
              'goog:chromeOptions': {
                  binary: '/Users/myUser/code/electron-quick-start/out/electron-quick-start-darwin-x64/electron-quick-start.app/Contents/MacOS/electron-quick-start', // Path to your Electron binary.
                  args: [/* cli arguments */] // Optional, perhaps 'app=' + /path/to/your/app/
              }
          }
      }
      
      const client = webdriverio.remote(options)
      
      console.log(client);
      
      client
          .init()
          .url('http://google.com')
          .setValue('#q', 'webdriverio')
          .click('#btnG')
          .getTitle().then((title) => {
              console.log('Title was: ' + title)
          })
          .end()

I would expect that the selected Electron Browser would be opened, navigate to google.com etc.

### Actual Behavior

Executing the script with `node test.js` causes an error 
`.init()
     ^
TypeError: client.init is not a function
    at Object.<anonymous>`
  

### Additional Information

Initially the issue, after debugging with `console.log(client);`, was -> `Promise {  <rejected> Error: Required option "capabilities" is missing`. Renaming "desiredCapabilities" to "capabilities" still does not work.

**Comment by zcbenz** [comment]
I think this is because our documentation is outdated, I have no experience with WebDriverIO so the best way to solve this is to seek help from the community of WebDriverIO .

**Comment by erickzhao** [comment]
@DrNio13 For what it's worth, there's an incoming PR that updates the WDIO docs: https://github.com/electron/electron/pull/29240
