### ISSUE TITLE
[Bug]: cannot trigger ondataavailable when recording for the second time

### ISSUE THREAD

**Issue by Seeker98** [electron/electron#29654]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0, 12.0.8

### What operating system are you using?

Windows

### Operating System Version

windows 10 2004

### What arch are you using?

x64

### Expected Behavior

recording can be performed everytime.

### Actual Behavior

the recording can only work the first time it is called after the app launches. for the second or later, event 'ondataavailable' cannot be triggered

### Testcase Gist URL

https://gist.github.com/a65c6e10ee68daf11701e041cc9f5e96

**Comment by Seeker98** [comment]
`let recorder;    
async testStart() {
      desktopCapturer
        .getSources({ types: ["window"] })
        .then(async (sources) => {
          console.log(sources);
          for (const source of sources) {
            if (source.name == "electron-vue-template") {
              try {
                navigator.webkitGetUserMedia(
                  {
                    audio: false,
                    video: {
                      mandatory: {
                        chromeMediaSource: "desktop",
                        chromeMediaSourceId: source.id,
                      },
                    },
                  },
                  (stream) => {
                    recorder = new MediaRecorder(stream, {
                      mimeType: "video/webm;codecs=vp9",
                    });
                    recorder.onerror = (err) => console.log(err);
                    recorder.onwarning = (w) => console.log(w);
                    recorder.onstop = () => console.log("stop record.");
                    recorder.ondataavailable = (e) => {
                      console.log(e);
                      if (e.data && e.data.size > 0) {
                        console.log("active data");
                      }
                    };
                    recorder.start(500);
                    console.log(recorder);
                  },
                  () => {
                    console.log("failed");
                  }
                );
              } catch (e) {
                console.log(e);
              }
            }
          }
        });
    },
    testStop() {
      recorder.stop();
    },`

**Comment by nornagon** [comment]
Here's a modified gist that works on 13.x+: https://gist.github.com/25f2e17ad4b783b8459948069aa34079

**Comment by nornagon** [comment]
This seems to work fine in 12.0.8 and 11.3.0. Perhaps the bug was mistyped and those were the "last known working versions"? However, it does seem broken in v13 and v14.

Bisected two separate times to different ranges:

- https://github.com/electron/electron/compare/v13.0.0-beta.20...v13.0.0-beta.21
- https://github.com/electron/electron/compare/v14.0.0-nightly.20210413...v14.0.0-nightly.20210426

In particular, https://github.com/electron/electron/compare/v13.0.0-beta.20...v13.0.0-beta.21#diff-fe6a1a2d1e3d95d29276ea59bef798d726b09ddf785412d98ab58d8fd5a55968 stands out to me. The same patch is also present in the v14 range: https://github.com/electron/electron/compare/v14.0.0-nightly.20210413...v14.0.0-nightly.20210426#diff-fe6a1a2d1e3d95d29276ea59bef798d726b09ddf785412d98ab58d8fd5a55968

cc @codebytere who wrote that patch

**Comment by Seeker98** [comment]
Hello, I again put your fiddle into electron fiddle using v13.1.1, and I act as follows:
1. Click 'run' on the top left of electron fiddle app.
2. In the opened window, open developer tools and click 'record window'.
(Now i can see in the console logs 'got sources', 'got stream', etc. and 'active data' bursting out continuously indicating ondataavailable event is kept being triggered)
3. Click 'stop recording' and see in the console 'stop record'.
4. click 'record window‘ again, and see in the console only messages like 'got sources', 'got stream', 'found screen recorder', but no 'active data' messages coming out.
![QQ截图20210618094034](https://user-images.githubusercontent.com/26476171/122492938-4ed0d200-d019-11eb-9882-f2c2fad0f46d.png)

**Comment by Seeker98** [comment]
I couldn't guess which part may cause this problem, so if you need any info about my running env, please comment and i'm willing to provide info.

**Comment by nornagon** [comment]
@Seeker98 yes, that's the behavior I also observed. I see that behavior in v13.0.0-beta.21 and later, but v13.0.0-beta.20 behaves differently.

**Comment by Seeker98** [comment]
@nornagon I again tried multiple versions of electron: 11.3.0/12.0.8/13.0.0beta20 and 21/13.1.1/14.0.0beta7. Our fiddle behaved exactly the same, failing on the second time under all versions mentioned above(win32-x64). Now I really got confused on how to deal with this.

**Comment by nornagon** [comment]
Hm, yeah, it's definitely working fine for me on v12.0.8 (on macOS):
![image](https://user-images.githubusercontent.com/172800/122597538-58aa0380-d020-11eb-9920-234b7bd97915.png)

**Comment by Seeker98** [comment]
Ah...Our production env is limited to windows and, I thought it may related to processor (My pc is AMD ryzen) and I tried on collegue's intel pc but still the same with following frustrating results...
![QQ截图20210619171625](https://user-images.githubusercontent.com/26476171/122637646-719add80-d122-11eb-852e-a6dbfbdd0307.png)
![QQ截图20210619171729](https://user-images.githubusercontent.com/26476171/122637647-72337400-d122-11eb-926a-99f4c0f3e732.png)
![QQ截图20210619171818](https://user-images.githubusercontent.com/26476171/122637648-72337400-d122-11eb-8fdf-230afdf3f211.png)

![QQ截图20210619171541](https://user-images.githubusercontent.com/26476171/122637644-7069b080-d122-11eb-9356-bb4992401eaa.png)

**Comment by nornagon** [comment]
Interesting, so this might be broken on 11.x and 12.x but only on windows? :/

Is there any version of Electron that _does_ work correctly on Windows? If so, would you be able to try using Electron Fiddle's bisect feature? View > Toggle Bisect Helper, then click the "Bisect" button in the toolbar. Enter the last known-working version and the first known-broken version and report back here on the range that Fiddle gives you at the end of the bisect process.

**Comment by Seeker98** [comment]
Well, I bisected in fiddle and it says: https://github.com/electron/electron/compare/v3.1.13...v4.0.0-beta.1
One thing that need to be mentioned is that, from some version in the middle, the api desktopCapturer.getSources changed from callback to async function, that is: 
earlier version: desktopCapturer.getSources( { types: ["window"] }, async (err, sources) => { //execute something })
later version: desktopCapturer.getSources( { types: ["window"] } ).then(async sources => { //execute something })
remarks:
1. parameter 'sources' are used same in callback or then
2. from my opinion, this bug is unrelated to this change of api, as in both v3.1.13 and v4.0.0-beta.1, the earlier version of api is used but behaved differently.

**Comment by nornagon** [comment]
v3 and v4??? Those versions are ancient history! Is this bug really that old? It doesn't work for you in any version newer than v3.1.13?

**Comment by Seeker98** [comment]
OK, I took another research and now explain on it.
While wandering on github for similar projects, i accidentally found that v8.0.2 is also available without bug, so i tried with fiddle bisect and the separator is 8.5.5/9.0.0-beta.1.
To make sure the accuracy, i downloaded multiple versions from 8.0.2 to 8.5.5, and versions tested in this range all worked quite well. 
However, still there are weird things happened: for example, suppose v8.0.2 works well, but behaviors between different runs may differs, that is, maybe i run the demo for the first time, it works well, but the second time i run the demo, it fails, and possibly i restart Fiddle application for a few times, it works again.
I know this may really sound weird or like some kind of joke, but it did happened and i did not change code or settings during the whole process, and i would state that, i am willing to help with any operations or tests, to deal with this problem.
remarks: i tested at least 1 version in each of the big versions from 3 to 14. only <3 and 8 worked well during the process.

**Comment by RuidongLiu** [comment]
Hi @Seeker98, I can reproduce the bug on v17.4.0. Do you mind sharing some ideas if you find any workaround for this? Thank you :)
