### ISSUE TITLE
[Bug]: webview partition causes protocol link association pop up

### ISSUE THREAD

**Issue by aleksey-hoffman** [electron/electron#29660]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.10

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1 19043.1023

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

To not cause the protocol link pop up

### Actual Behavior

Setting a custom partition to a webview causes the Widows protocol link association pop up in production when the window containing this webview is created:

![image](https://user-images.githubusercontent.com/61761672/121809351-20dc3e00-cc65-11eb-94f6-3def22e1b8ef.png)

It might be caused by the custom `app://` protocol created by the [electron-builder-plugin](https://github.com/nklayman/vue-cli-plugin-electron-builder). It seems the pop up is triggered by the "app" link.

I'm setting a custom partition name, because otherwise the `will-download` listener created by `windows.quickViewWindow` overwrites the  `will-download` listener created by the `downloadManager` since they are both using the default session partition (if I understand the problem correctly):

`windows.quickViewWindow`: 
- https://github.com/aleksey-hoffman/sigma-file-manager/blob/47ce65bdac78e5c9b17315f16623d40d81dcf1bb/src/electronMain.js#L233

`downloadManager`: 
- https://github.com/aleksey-hoffman/sigma-file-manager/blob/79cfc58c90f72979ef7ffc97251fd390c1147aa2/src/electronMain.js#L516
- https://github.com/aleksey-hoffman/sigma-file-manager/blob/79cfc58c90f72979ef7ffc97251fd390c1147aa2/src/utils/downloadManager.js#L133

### Testcase Gist URL

Commit causing the issue:
https://github.com/aleksey-hoffman/sigma-file-manager/commit/47ce65bdac78e5c9b17315f16623d40d81dcf1bb

## To reproduce:

1. Download the project
```
git clone https://github.com/aleksey-hoffman/sigma-file-manager.git
cd sigma-file-manager
npm install
git checkout 47ce65b
npm run electron:build
```

2. Install the built app from `./dist_electron`
3. During the app launch you can see the pop up

The window containing this webview is created on `app.ready` event. The pop up appears when the window gets created:

https://github.com/aleksey-hoffman/sigma-file-manager/blob/47ce65bdac78e5c9b17315f16623d40d81dcf1bb/src/electronMain.js#L698

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this bug? We don't have enough resources to debug your whole app, it seems that the bug is not in Electron, but caused by third party code.

**Comment by aleksey-hoffman** [comment]
@zcbenz I was able to reproduce it with this code:

```js
let window1 = null
let window2 = null

electron.app.on('ready', async () => {
  createWindow1()
  createWindow2()

  setTimeout(() => {
    console.log('trigger window 1 download')
    window1.webContents.downloadURL('https://github.com/electron/electron/issues/29660')
  }, 1000)
})


function createWindow2 () {
  window1.webContents.session.once('will-download', downloadHandler1)
  window2.webContents.session.once('will-download', downloadHandler2)

  function downloadHandler1 (event, item, webContents) {
    console.log('window 1')
  }
  function downloadHandler2 (event, item, webContents) {
    console.log('window 2')
  }
}

function createWindow1 () {
  window1 = new electron.BrowserWindow()
  window1.webContents.session.once('will-download', downloadHandler1)
}

function createWindow2 () {
  window2 = new electron.BrowserWindow()
  window1.webContents.session.once('will-download', downloadHandler2)
}

function downloadHandler1 (event, item, webContents) {
  console.log('window will-download handler 1')
}

function downloadHandler2 (event, item, webContents) {
  console.log('window will-download handler 2')
}

```

When the `setTimeout` runs, I see the following `console.log()` messages:

```
trigger window 1 download
window will-download handler 1
window will-download handler 2
```

**Comment by aleksey-hoffman** [comment]
@zcbenz I was able to reproduce it with this code:

```js
let window1 = null
let window2 = null

electron.app.on('ready', async () => {
  createWindow1()
  createWindow2()

  setTimeout(() => {
    console.log('trigger window 1 download')
    window1.webContents.downloadURL('https://github.com/electron/electron/issues/29660')
  }, 1000)
})


function createWindow2 () {
  window1.webContents.session.once('will-download', downloadHandler1)
  window2.webContents.session.once('will-download', downloadHandler2)

  function downloadHandler1 (event, item, webContents) {
    console.log('window 1')
  }
  function downloadHandler2 (event, item, webContents) {
    console.log('window 2')
  }
}

function createWindow1 () {
  window1 = new electron.BrowserWindow()
  window1.loadURL('app://./quickViewWindow.html')
  window1.webContents.session.once('will-download', downloadHandler1)
}

function createWindow2 () {
  window2 = new electron.BrowserWindow()
  window2.loadURL('app://./quickViewWindow.html')
  window2.webContents.session.once('will-download', downloadHandler2)
}

function downloadHandler1 (event, item, webContents) {
  console.log('window will-download handler 1')
}

function downloadHandler2 (event, item, webContents) {
  console.log('window will-download handler 2')
}

```

When the `setTimeout` runs, I see the following `console.log()` messages:

```
trigger window 1 download
window will-download handler 1
window will-download handler 2
```

As you can see from the log, the will-download event triggers event handlers of both windows

If I specify a separate partition for each window, the problem with shared event handlers gets resolved, but I get the 2nd problem mentioned above - the link association pop up in production build on launch

```js
window1 = new electron.BrowserWindow({
  webPreferences: {
    partition: 'partition1',
  }
})
window2 = new electron.BrowserWindow({
  webPreferences: {
    partition: 'partition2',
  }
})
```
