### ISSUE TITLE
[Bug]: missing spawn event when starting a child process

### ISSUE THREAD

**Issue by romain20100** [electron/electron#29664]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Build 19042

### What arch are you using?

x64

### Expected Behavior

When running the provided script with electron, a "spawn" event should be emitted.

### Actual Behavior

No "spawn" event is emitted.

### Additional Information

The issue form only lets me fill a single OS but I have reproduced the issue on MacOS Catalina as well as on Windows 10.

Electron version:
- Windows: 13.1.2
- MacOS: 12.0.8

Tested NodeJS versions: 16.2.0, 15.12.0

Until I or someone else transforms this in a working gist, I've reduced the bug to this extremely simple snippet of code.

```js
// spawn-bug.js

const { spawn } = require('child_process');

const { app } = require('electron');

function startChild() {
  const child = spawn('cmd', ['/?'], { stdio: 'inherit' });
  // For linux/macOS, use this instead
  // const child = spawn('ls', ['-h'], { stdio: 'inherit' });
  child.on('error', (e) => console.log(`"error" event\n\n${e.stack ?? e.message}`));
  child.on('spawn', () => console.log(`"spawn" event.\npid=${child.pid} exitCode=${child.exitCode}`));
  child.on('close', () => console.log(`"close" event.\npid=${child.pid} exitCode=${child.exitCode}`));
}

if (app) {
  console.log('Running as electron app');
  app.whenReady().then(startChild);
} else {
  console.log('Running as node script');
  startChild();
}
```

Execute it with either node.js or with electron.

```sh
node spawn-bug.js
# OR
node_modules/.bin/electron spawn-bug.js
```

When executed with node, the child process successfully emits a "spawn" event.
But when executed with electron, it does not.

**The child process should either through an "error" or a "spawn" event before emitting a "close" event.**

Possibly related issues: #28492 #24329

**Comment by codebytere** [comment]
@romain20100 this event was added in v14.17.0, which [as you can see here](https://github.com/electron/releases) is only included in some of the latest nightlies of Electron. Older versions won't emit this event.
