### ISSUE TITLE
[Bug]: HTML select tag not rendering the dropdown

### ISSUE THREAD

**Issue by sertxudev** [electron/electron#29665]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.x & 15.x

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro version 21H1

### What arch are you using?

x64

### Last Known Working Electron version

13.1.2

### Expected Behavior

When you add a select tag to your HTML and you click on it should open a dropdown with the options.

![image](https://user-images.githubusercontent.com/22801379/121824219-ccf44800-ccaa-11eb-967d-0e1f4543a03a.png)

### Actual Behavior

Beyond version 13.1.2 when you click the select but no dropdown appears.

![image](https://user-images.githubusercontent.com/22801379/121824232-f6ad6f00-ccaa-11eb-961f-ed4508111dbd.png)

### Testcase Gist URL

https://gist.github.com/4573db9b87615a897a731b573a16ae1e

### Additional Information

Electron v13.1.2 uses Chromium 91.0.4472.77
Electron v14.0.0-beta.1 uses Chromium 92.0.4511.0

Maybe this issue has something to do with Chromium 92.0 and beyond?

For the Testcase I used the default code adding a simple select to the HTML.

```html
<select name="select">
    <option value="value1">Value 1</option>
    <option value="value2" selected>Value 2</option>
    <option value="value3">Value 3</option>
</select>
```

**Comment by soumyag123** [comment]
Hey ! I want to work on this issue . Can you suggest me how to get started ?

**Comment by sertxudev** [comment]
Hi @soumyag123, I found in the docs how to get started with Pull Requests (https://www.electronjs.org/docs/development/pull-requests), but I never set up a C environment so I cannot help you with that, sorry.

**Comment by nornagon** [comment]
Possibly related: https://github.com/electron/electron/pull/28938

**Comment by sertxudev** [comment]
The pull request #28938 was merged on 3 May, I just tested with v14.0.0-nightly.20210430 (released on 30 Apr) and v14.0.0-nightly.20210503 (released on 3 May, after the merge).

With v14.0.0-nightly.20210430 it's working as it should, with v14.0.0-nightly.20210503 it's not working.

So @nornagon is right, the bug is there.

**Comment by sertxudev** [comment]
Now it's working as it should. Tested on v15.0.0-nightly.20210618 with Windows 10.

Thanks @codebytere, awesome work.

**Comment by tonyxforce** [comment]
and now its a problem again

**Comment by create3000** [comment]
It turns out that as of version 31.0.0 the problem appeared again. All 30.*.* versions are OK.

**Comment by pacocoursey** [comment]
We're seeing reports of this being broken on macOS now (also mentioned in https://github.com/siyuan-note/siyuan/issues/11929) – can anyone else reproduce this reliably?
