### ISSUE TITLE
Nothing is fucking working

### ISSUE THREAD

**Issue by Xy4neX** [electron/electron#29678]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

3.1.0

### Expected Behavior

2 days ago no messeges showed up. Now i cant even do anything.

### Actual Behavior

nothing works

**Comment by codebytere** [comment]
If you are having issues please open a fully complete issue template.
