### ISSUE TITLE
[Bug]: Reading login items with app.getLoginItemSettings() causes network volumes to mount

### ISSUE THREAD

**Issue by isnotgood** [electron/electron#29704]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0-beta.5

### What operating system are you using?

macOS

### Operating System Version

11.4 (20F71)

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

Listing login items via `app.getLoginItemSettings()` doesn't cause any side-effects.

### Actual Behavior

When the network volumes are in the login items list, listing them via `app.getLoginItemSettings()` causes connection dialogs to pop-up. 

### Additional Information

The issue comes from chromium and I created [CL 2964074](https://chromium-review.googlesource.com/c/chromium/src/+/2964074) to fix it.

**Comment by nornagon** [comment]
Thanks for the link to the CL! We can consider backporting it once it's landed upstream.
