### ISSUE TITLE
[Bug]: getFileIcon gives broken image on higher resolution display

### ISSUE THREAD

**Issue by aajahid** [electron/electron#29718]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version 20H2, OS BUILD: 19042.1052, Windows Feature Experience Pack 120.2212.2020.0

### What arch are you using?

x64

### Expected Behavior

Supposed to show icons/images properly as of bellow - ( it works fine when I change my monitor "Scale and Layout" settings to 100% ).

![image](https://user-images.githubusercontent.com/1908862/122127259-c0abee80-ce54-11eb-82c6-f7533828fc12.png)

### Actual Behavior

But the images comes broken as bellow when the display "Scale and Layout" settings set to the recommended "150%" settings.

![image](https://user-images.githubusercontent.com/1908862/122127513-17192d00-ce55-11eb-9a8d-dc0053719c10.png)

### Additional Information

If this helps anyhow - its a 4k 27 inch LG monitor. 3840x2160 resolution. Images works fine when I set the "Scale and Layout" to 100%. But if I change it to 150% ( which is recommended by windows ) those images comes as broken.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Augus** [comment]
This problem can be reproduced, I think this issue should not be closed. 🥲

**Comment by nornagon** [comment]
@Augus if you are able to provide a repro as requested in https://github.com/electron/electron/issues/29718#issuecomment-861923107, please do so! We cannot reasonably address this without a repro.

**Comment by erikjalevik** [comment]
I had a user report the same issue on Windows on an external monitor with the refresh rate set to 144Hz. He said it went away after he changed the monitor refresh rate. Even after setting it back to 144Hz, it was then fine.

No repro though I'm afraid.

**Comment by doublesupercool** [comment]
Just to clarify the above, I am the user, and it appears to be related to OPs original point: UI scaling in Windows 11 (not refresh rate). If I start the app at 125% UI scaling, icons will be corrupted. If I start at 100% UI scaling (and then change the scale), the icons will be fine.
