### ISSUE TITLE
[Bug]: window.isMaximized() is false when window is not focused

### ISSUE THREAD

**Issue by HesamSe** [electron/electron#29728]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 1809

### What arch are you using?

x64

### Expected Behavior

I open a browser window and set it maximize.
```
const window = new BrowserWindow({
    // ...options
});
window.maximize();
```

If I run the code below when window is focused, isMaximized is true.
```
const focusedAndMaximizedWindow = BrowserWindow.getAllWindows()[0];
console.log(window.isFocused()); // returns true
console.log(window.isMaximized()); // returns true
```
Now I unfocus the window and run the code again, isMaximized is false.
```
const unFocusedAndMaximizedWindow = BrowserWindow.getAllWindows()[0];
console.log(window.isFocused()); // returns false
console.log(window.isMaximized()); // returns false
```

### Actual Behavior

Expected behaviour: `isMaximized()` should be true whether the window is focused or not.
```
const unFocusedAndMaximizedWindow = BrowserWindow.getAllWindows()[0];
console.log(window.isFocused()); // returns false
console.log(window.isMaximized()); // returns true
```

**Comment by dsanders11** [comment]
@HesamSe, can you still reproduce this on current versions of Electron? If so, can you please provide a gist or full reproduce steps, including how you are unfocusing the window? I am not able to reproduce.
