### ISSUE TITLE
[Feature Request]: Kinetic scrolling for ozon wayland backend

### ISSUE THREAD

**Issue by toger5** [electron/electron#29730]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Scrolling on a wayland desktop like sway/gnome shell using a touchpad does not give the native scrolling feel. The code editor does not keep the momentum.

### Proposed Solution

Use momentum/kinetic/inertia scrolling implementation from ozone
### Additional Information

Firefox is a good example on how this can look like.
For wayland the kinetic scrolling is supposed to be part of the toolkit (in this case electron)
Even though it sounds counter intuitive that this is not part of the input driver. The reason for that is, that the toolkit might want to have audible or visible differences between the cases where the user is actively scrolling or when there is just momentum left in the scrolling motion but the user already released his fingers.

It seems like this is indeed already part of ozone.
https://bugs.chromium.org/p/chromium/issues/detail?id=763791

**Comment by MarshallOfSound** [comment]
This needs to be implemented / supported upstream, that crbug you linked is what you should be following.  Electron will pick it up when support is landed upstream and ozone is enabled by default.
