### ISSUE TITLE
[Bug]: The select-bluetooth-device callback is not called after disconnecting from a device

### ISSUE THREAD

**Issue by Bunagana** [electron/electron#29747]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.1

### What operating system are you using?

macOS

### Operating System Version

macOs Big Sur v11.4

### What arch are you using?

x64

### Expected Behavior

The select-bluetooth-device callback should be called after disconnected and attempting to connect to a device. 
1. Connect to a device
2. Disconnect
3. Attempt to connect (bluetooth.requestDevice does not prompt the select-bluetooth-device callback)

### Actual Behavior

The select-bluetooth-device callback is not called when calling await navigator.bluetooth.requestDevice after a disconnect.

Thanks for your help.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by Bunagana** [comment]
Hi @codebytere! Please find the gist at https://gist.github.com/Bunagana/30b522f5d7a4f8b71eabcb111fa3fd5d
Thank you for your help.

**Comment by Bunagana** [comment]
Hi @codebytere, thank you for your help. I just tested v13.1.3 and I can no longer reproduce the issue. I think the issue may have been fixed by https://github.com/electron/electron/pull/29611.
