### ISSUE TITLE
[Bug]: App hijacks focus from `win.previewFile` since v12.0.9

### ISSUE THREAD

**Issue by EtienneLem** [electron/electron#29758]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.9

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

12.0.8

### Expected Behavior

When using [`win.previewFile`](https://www.electronjs.org/docs/api/browser-window#winpreviewfilepath-displayname-macos), it is expected that pressing spacebar or escape would dismiss the preview window.

### Actual Behavior

Nothing happens, or rather your app is still receiving the shortcuts and the preview window is not.

### Additional Information

Given the very small [v12.0.9](https://www.electronjs.org/releases/stable?version=12#12.0.9) update, it would be safe to assume that #29235 is responsible for this regression.

Not sure if relevant, but:

**Before**
When calling `win.previewFile` it used to trigger a `blur` followed by an immediate `focus` event on `window`:

<img width="165" alt="CleanShot 2021-06-17 at 14 09 45@2x" src="https://user-images.githubusercontent.com/436043/122451016-b0d7fb80-cf75-11eb-83f2-f9672f41d93e.png">

**Now**
When calling `win.previewFile` it triggers this pair of events 4 times in a row:

<img width="188" alt="CleanShot 2021-06-17 at 14 08 50@2x" src="https://user-images.githubusercontent.com/436043/122450921-96058700-cf75-11eb-8be4-7ab4c2650474.png">

**Comment by nornagon** [comment]
https://github.com/electron/electron/pull/29235 looks like a possible culprit. cc @deepak1556
