### ISSUE TITLE
[Bug]: clipboard.writeHTML(someElement.innerHTML) does not work outside of renderer.js

### ISSUE THREAD

**Issue by anzbert** [electron/electron#29753]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Using clipboard.writeHTML in preload.js with contextbridge, or with contextbridge and ipcRenderer to ipcMain in main.js, should work as normal, when exposed to renderer.js. 

### Actual Behavior

When I pass the clipboard function to renderer.js in preload.js, writeText produces the expected result, but writeHTML leaves the clipboard empty. 
writeHTML works only as expected when required in renderer.js (without contextisolation and with nodeintegretaion, which is no longer recommended)

`
// in renderer.js

// 1st test
electron.copyText(someElement.innerHTML);

// 2nd test
electron.copyHtml(someElement.innerHTML);

// in preload.js
const { clipboard } = require("electron");

contextBridge.exposeInMainWorld("electron", {
  copyHtml: (data) => {
    clipboard.writeHtml(data); // ends up with nothing in clipboard...
  },
  copyText: (data) => {
    clipboard.writeText(data); // works fine !!  clipboard contains <p>Test</p>
  },
});
`

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by anzbert** [comment]
my bad. i made a mistake that i cant even reproduce.
