### ISSUE TITLE
[Bug]: Printing is not working at all

### ISSUE THREAD

**Issue by megakraken** [electron/electron#29759]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 7 SP1 incl. latest patches

### What arch are you using?

x64

### Expected Behavior

Calling [webContents.print()](https://www.electronjs.org/docs/api/web-contents#contentsprintoptions-callback) with the absolute minimal set of options and an existing device as returned from [contents.getPrinters()](https://www.electronjs.org/docs/api/web-contents#contentsgetprinters) should add the document to be printed to the printer's print queue and subsequently trigger the printing of said document.

```
const options = {
  silent: true,
  deviceName: 'My-Printer',
}
await win.webContents.print(options);

```

### Actual Behavior

The call to [win.webContents.print](https://www.electronjs.org/docs/api/web-contents#contentsprintoptions-callback) just silently returns, indicating success, yet no document is ever added to the printer's print queue and no document is ever printed.

### Additional Information

The printer in question is working fine with every other application, so it is definitely not a printer or driver or operating system issue.

**Comment by codebytere** [comment]
Duplicate https://github.com/electron/electron/issues/29759
