### ISSUE TITLE
[Bug]: Segfault when loading `https://google.com` into a `BrowserWindow` on macOS

### ISSUE THREAD

**Issue by erickzhao** [electron/electron#29768]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

v13.0.0-beta.14

### What operating system are you using?

macOS

### Operating System Version

Catalina 10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

v13.0.0-beta.13

### Expected Behavior

The Google homepage loads and the app quits successfully with an `app.quit()` call.

### Actual Behavior

The BrowserWindow is able to load `https://google.com`, but the app crashes with signal `SIGSEGV` before the `app.quit()` line is ever reached.

<details><summary>Full output from the Fiddle testcase</summary>
<pre>
Saved files to /var/folders/bh/cgb8q_9x5s73jn7p_rzy82bm0000gp/T/tmp-87456-1sWncTW6NGEd
Electron v13.0.0-beta.14 started.
Received signal 11 SEGV_MAPERR 000000000008
 [0x000111263cb9]
 [0x000114859c33]
 [0x00011487558b]
 [0x7fff6ce495fd]
 [0x000000000000]
 [0x0001143cd02b]
 [0x0001143ca02e]
 [0x000110f68b8c]
 [0x0001143c9cf6]
 [0x00011122438c]
 [0x000111236c15]
 [0x000111237b7f]
 [0x00011126fddc]
 [0x00011126c422]
 [0x00011126f60f]
 [0x7fff32bb0d52]
 [0x7fff32bb0cf1]
 [0x7fff32bb0b0b]
 [0x
7fff32baf83a]
 [0x7fff32baee3e]
 [0x7fff3524a1d8]
 [0x0001112703ee]
 [0x00011126f14b]
 [0x00011123808f]
 [0x00011120fadc]
 [0x000111254998]
 [0x000111254bb6]
 [0x00011126ab08]
 [0x7fff6ce55109]
 [0x7fff6ce50b8b]
[end of stack trace]
Electron exited with signal SIGSEGV.
</pre>
</details>

### Testcase Gist URL

https://gist.github.com/erickzhao/0ad9d48fdfec2a99d92450dc06d26fa0

#### Affected versions

This bug affects the latest stable (v13.1.2), beta (v.14.0.0-beta.3), and nightly (v15.0.0-nightly.20210609) releases.

#### Generality

This bug affects the `loadURL` APIs for both BrowserWindows and BrowserViews.

#### Affected domains

I've only been able to reproduce this bug on the Google search engine so far.

Things that broke:
* https://google.com
* https://google.ca
* https://www.google.com/search?q=electron

Domains that I've tested that are unaffected:

* https://github.com
* https://twitter.com
* https://electronjs.org
* https://web.dev
* https://mail.google.com
* https://translate.google.com
* https://source.chromium.org/chromium

#### Platform specificity

We encountered this bug when helping a community member out on our Discord server. @-malept was unable to reproduce the bug on Linux, so I'm guessing that this is a platform-specific bug.

cc @xenics-pro

**Comment by nornagon** [comment]
Possibly https://github.com/electron/electron/issues/29343#issuecomment-863832234

**Comment by erickzhao** [comment]
@nornagon Seems like that's the underlying culprit! Didn't find that issue before filing yesterday. Seems like all the info I have is already on the other issue. I'll close this one now. 🙇
