### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by wangfpp** [electron/electron#29772]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Can Electron's server only run on the C drive?
I installed the app on the D drive and found that the running directory of the service is on the C drive

### Proposed Solution

server runing install drive

### Alternatives Considered

none

### Additional Information

none

**Comment by VerteDinde** [comment]
Hey @wangfpp, thanks for reporting this issue! We use this issue tracker for specific bugs within Electron - this seems more like a question for how you can run your Electron app. I'd recommend checking out our community Discord for answers to your question - you can join it here:  https://discord.gg/electron

Thanks!
