### ISSUE TITLE
[Feature Request]: SiriKit Shortcuts is coming to macOS

### ISSUE THREAD

**Issue by gaodeng** [electron/electron#29775]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

checkout this WWDC2021 video  Meet Shortcuts for macOS  https://developer.apple.com/videos/play/wwdc2021/10232/   

### Proposed Solution

n/a

### Alternatives Considered

n/a

### Additional Information

n/a

**Comment by nornagon** [comment]
Hi there, thanks for the feature request.

Can you expand a bit on what you would hope such a feature would accomplish? A few examples would be helpful.
