### ISSUE TITLE
[Bug]: Setting the BackgroundColor to the BrowserView doesn't work on Windows

### ISSUE THREAD

**Issue by ddramone** [electron/electron#29778]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.*,  12.*,   13.*

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

`setBackgroundColor()` should set the background to the browser view. 

### Actual Behavior

The content of the BrowserView is still transparent.

![image](https://user-images.githubusercontent.com/2891206/122588825-d7726100-d05f-11eb-93d2-935eb93801c8.png)

### Testcase Gist URL

https://gist.github.com/ddramone/712a2fde2757736c9dbf6c3e7e0aa18b

### Additional unusual behavior:

I tried to remove the background color from the parent BrowserWindow.  As a result

* **BrowserView that is fully visible** in the screen _(right)_ picks up its own background. But it is blended through the renderer content. 

* Another **BrowserView that is partially visible** on the screen _(left)_ still doesn't pick up its own background.

see the screenshot:

![image](https://user-images.githubusercontent.com/2891206/122589135-2d470900-d060-11eb-8ef2-ec4aa53a240e.png)

--- 
_figma.com is the example that doesn't have the background color to the document body._

**Comment by weifeiyue** [comment]
when can it be fixed? This bug has affected the progress of my project 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by weifeiyue** [comment]
how about this bug?

**Comment by codebytere** [comment]
Please be patient. We are a small team and there are thousands of issues.

**Comment by weifeiyue** [comment]
😭😭😭😭how about this bug?
