### ISSUE TITLE
[Bug]: ERR_NO_SUPPORTED_PROXIES when use proxyRules with auth

### ISSUE THREAD

**Issue by Buminta** [electron/electron#29797]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

macOS

### Operating System Version

BigSur

### What arch are you using?

x64

### Expected Behavior

I hope It's working

### Actual Behavior

I'm use
```
var my_proxy = "http://account:pass@ip:port";
      var ses = session
        .fromPartition("persist:session02");

      ses.setProxy({
        proxyRules: my_proxy,
        proxyBypassRules: "<-loopback>"
      });
```
However I had an error here!
```
(node:71555) electron: Failed to load URL: https://google.com with error: ERR_NO_SUPPORTED_PROXIES
(Use `Electron --trace-warnings ...` to show where the warning was created)
```

Please help me!

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by Buminta** [comment]
I'm share my proxy in here for that. U can use it for check!
https://gist.github.com/b742038d533508746458741dfea49c3b

**Comment by nornagon** [comment]
`proxyRules` doesn't support authentication. See https://www.electronjs.org/docs/api/session#sessetproxyconfig for allowable options.

**Comment by Buminta** [comment]
@nornagon You're joker?

I'm finding auth Handle in here, And It's working >p:

```
app.on('web-contents-created', (e, wC) => {
  wC.on('login', (event, webContents, authInfo, callback) => {
    if(authInfo.isProxy) {
      callback('user', 'pass');
    }
  }) 
});
```

**Comment by nornagon** [comment]
Yep, handling the login event works fine, but the proxy config doesn't accept user/pass as part of the URL.
