### ISSUE TITLE
Blank/disconnected dev tools before calling loadUrl

### ISSUE THREAD

**Issue by iamcal** [electron/electron#298]
If you open dev tools before calling `loadUrl()`, it will appear blank and broken. Calling it again later 

Works:

```
mainWindow.loadUrl('http://www.github.com');
mainWindow.openDevTools();
```

Fails:

```
mainWindow.openDevTools();
mainWindow.loadUrl('http://www.github.com');
```

Also fails:

```
mainWindow.openDevTools();
mainWindow.loadUrl('http://www.github.com');
mainWindow.openDevTools();
```

Works correctly:

```
mainWindow.openDevTools();
mainWindow.loadUrl('http://www.github.com');
mainWindow.closeDevTools();
mainWindow.openDevTools();
```

The dev tools must be opened _after_ the first call to `loadUrl` to correctly bind to the browser.

**Comment by jarrodek** [comment]
To reduce confusion there could be a warning message from the main process that trying to attach devtools when WebContents is not loaded. You would probably avoid questions/issues like this in future.
