### ISSUE TITLE
[Bug]: On windows 7，when run a Electron exe in .bat file，as "start electron-vue-demo-1.exe" in .bat file, Occasionally failed, the exe does not run. 

### ISSUE THREAD

**Issue by zhangxr2** [electron/electron#29804]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

windows 7

### What arch are you using?

ia32

### Last Known Working Electron version

very earlier, 2.0.4

### Expected Behavior

regardless of on windows 7 or  on windows 10,  run a Electron exe in .bat file，as "start electron-vue-demo-1.exe" in .bat file, success every time.

### Actual Behavior

On windows 7,  ia32 or x64,  when run a Electron exe in .bat file，as "start electron-vue-demo-1.exe" in .bat file, Occasionally failed, the exe does not run. 
When on windows 10,  run a Electron exe in .bat file，as "start electron-vue-demo-1.exe" in .bat file, success every time.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use. In particular, please avoid any dependencies that are not required to reproduce the behavior (e.g. Vue).

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by zhangxr2** [comment]
I have tried Electron Fiddle，but Electron Fiddle can not reproduce my issue。Because my develop machine is windows 10 system，when I install Fiddle in windows 10，it can not build a exe which can run on win7. I build a exe through Tasks-->Package Fiddle...

But I can describe the issue  in detail below。
（1）clone electron-quick-start
（2）add a little log in main.js as follows.

`// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')
const path = require('path')
console.log("enter main.js")
function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
  console.log('end in create window')
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0)
    {console.log("in activate, before createWindow")
      createWindow()
    }

  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
console.log('end of main.js')`


（3）in package.josn , add "build": "electron-builder --ia32 --x64" and   "devDependencies": { "electron-builder":"^20.19.2" } as follows:
`{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build": "electron-builder --ia32 --x64"
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^13.1.4",
    "electron-builder": "^20.19.2"
  }
}`

  (4) npm run build，generate win-ia32-unpacked folder in dist folder。
（5）copy win-ia32-unpacked folder to a windows7 32bit system，place win-ia32-unpacked inside C:\Program Files\ ,
        then run  electron-quick-start.exe in cmd, the application's browserWindow can not show every time, it occasionally failed,failed ratio is about  1/10.

Do you have some idea about this issue ? @nornagon

**Comment by nornagon** [comment]
Unfortunately the info you've given so far isn't really enough to make any kind of determination about what the issue might be.

When you say the application doesn't show the browser window every time—is the app crashing? Are the processes present in the task manager but the window isn't shown? Are you seeing this on multiple Win 7 machines or only one? Are there any log messages printed? Can you try running with `--enable-logging` to see if that shows up anything?

**Comment by zhangxr2** [comment]
（1）When run electron-quick-start.exe in cmd using .bat file, the command is "start start electron-quick-start.exe" , the application doesn't show the browser window，the phenomenon is，the first log 'enter main.js' does not show in cmd.  no log is show in cmd.

(2) when the window is not shown, the process is absent in  the task manager。 but I have used Procmon.exe to catch process log。The process has tried to start，but it exit soon，exit log is “ Process Exit		SUCCESS	Exit Status: -1073741819, User Time: 0.0000000 seconds, Kernel Time: 0.1404009 seconds, Private Bytes: 14,737,408, Peak Private Bytes: 14,905,344, Working Set: 17,080,320, Peak Working Set: 17,313,792” 

（3）I have tested on window 10（64bit），windows 7（64bit）and windows 7（32bit）system。on windows 10， the  browser window show every time，there is no problem。
on windows 7（64bit），some times failed，failed ratio is about  1/20.
on windows 7 (32bit), ，some times failed，failed ratio is about  1/10.

**Comment by nornagon** [comment]
Exit status -1073741819 is 0xc0000005, which is the code for a segmentation fault / access violation, so it sounds like the app is trying to boot but crashing.

Could you try collecting a crash dump? You can collect one by adding the following snippet to your main process code, before app.whenReady:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by zhangxr2** [comment]
![image](https://user-images.githubusercontent.com/14310627/124101582-1659db00-da92-11eb-9b91-c3cc986eb2c5.png)

I add  the snippet in main process code, before app.whenReady.
but when the browserWindow occasionally does not show, there is  no crash report. as below picture:
![image](https://user-images.githubusercontent.com/14310627/124102548-0abae400-da93-11eb-8ecd-e6ace2052f13.png)

I think out that，this is normal。my first log  【console.log("enter main.js") 】didn't print out，so the code below 【console.log("enter main.js") 】also didn‘t execute。 so there is no crashReport。
@nornagon

**Comment by zhangxr2** [comment]
I want to provide some additonal message to you. @nornagon .  I want to show you my source project
[win7-occassically-does-not-run.zip](https://github.com/electron/electron/files/6761301/win7-occassically-does-not-run.zip)

In this zip,  “aaa.bat”  is my bat file ,aimed at testing electron-quick-start.exe.
  in this source projuect，“npm run build” to generate  “dist/win-ia32-unpacked”  folder. Then copy  “win-ia32-unpacked” folder under  “C:\Program Files\“ folder  on windows 7 (32bit) system ; then  copy   “aaa.bat” to   “win-ia32-unpacked” folder;  then test.

**Comment by zhangxr2** [comment]
who has some idea about this issue??
