### ISSUE TITLE
Can I load a URL? such as https://google.com 

### ISSUE THREAD

**Issue by bbhxwl** [electron/electron#29829]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Can I load a URL? such as https://google.com #576

### Proposed Solution

Can I load a URL? such as https://google.com

I don't want to load my local asp.net core file because it's not easy to update. I want to load my asp.net core program on the network. What should I do.

### Alternatives Considered

Can I load a URL? such as https://google.com

I don't want to load my local asp.net core file because it's not easy to update. I want to load my asp.net core program on the network. What should I do.

### Additional Information

Can I load a URL? such as https://google.com

I don't want to load my local asp.net core file because it's not easy to update. I want to load my asp.net core program on the network. What should I do.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
