### ISSUE TITLE
[Bug]: Dev Tools Network Throttling Drop Down Is Huge

### ISSUE THREAD

**Issue by dsanders11** [electron/electron#29832]
In `v15.0.0-nightly.20210617` onward, the drop down for choosing a network throttling mode in dev tools is rendering very large and to the side in macOS Big Sur.

I bisected this issue to having changed in 85718349c, which was a Chromium roll.

<img width="647" alt="Screen Shot 2021-06-21 at 10 42 53 PM" src="https://user-images.githubusercontent.com/5820654/122870461-8cb44b80-d2e2-11eb-9c62-21fd737bedb0.png">

**Comment by nornagon** [comment]
I can't repro this on Catalina (10.15.7).

Do you perhaps have your screen scaling set to something unusual?

Does Chrome Canary exhibit the same behavior?

**Comment by dsanders11** [comment]
> Do you perhaps have your screen scaling set to something unusual?

Not that I'm aware of. Resolution is set to "Default for display".

> Does Chrome Canary exhibit the same behavior?

It does not.

**Comment by nornagon** [comment]
Hoping this might be fixed in the next Chromium roll then.

**Comment by dsanders11** [comment]
Tested with the latest CI build for the next Chromium roll and it's back to normal, so closing this issue.
