### ISSUE TITLE
[Bug]: Notification from main process doesn't allow custom sound file on macOS

### ISSUE THREAD

**Issue by YeetOrBeYate** [electron/electron#29843]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

I should be able to pass a mp3 file to a notification constructor and when the notification is shown my custom sounds plays instead of the default

### Actual Behavior

My notification shows, but its ignores the path/string of the sound I passed and plays the default macOS notification sound. 

I know the path/string/mp3 I'm passing it is valid because I'm able to listen to it using mac's afplay terminal command like so: `afplay /Users/kylecorbin/Documents/Github/folderName/projectName/extraResource/app.mp3 `
but passing the same string to the new Notification constructor results in nothing. 

### Additional Information

Heres the actual code: 

      const notificationOptions = {
        title: 'New Item!',
        body: 'New items text',
        sound: "/Users/kylecorbin/Documents/Github/folderName/projectName/extraResource/app.mp3"
      }
      const newMessage = new Notification(notificationOptions)

      newMessage.show()

With this configuration new notifications incorrectly use the default macOS notification sound

**Comment by nornagon** [comment]
I think your sound file needs to be in a particular location: https://www.electronjs.org/docs/api/notification#playing-sounds

**Comment by YeetOrBeYate** [comment]
@nornagon 

From the docs: 'Be sure that the sound file is copied under the app bundle (e.g., YourApp.app/Contents/Resources)'

My mp3 file is located in MyApp.app/Contents/Resources/extraResources/app.mp3 so I believe I have it in the correct location. Here's my package.json adding that folder to the bundle

    `"build": {
        "appId": "com.example.someName",
        "productName": "SomeName",
        "extraResources": [
          "./extraResource/**"
        ],`

I used that terminal command in the above post in nodejs's exec command and wired that to a button in electron and I was able to play the mp3 at runtime no problem:

Accessing the mp3 file
`const sound = path.join(__dirname, '..', '..', '..', 'extraResource', 'app.mp3')`

Helper function to build terminal command
`const macPlayCommand = (soundPath, volume = 0.5) => `afplay \"${soundPath}\" -v ${volume}``

Function to run the command
`const playSound = async (soundPath, volume = 0.5) => {
  try {
    await exec(macPlayCommand(soundPath))
  } catch (error) {
    console.log(error)
    throw error
  }
}`

When a button is clicked my preload tells the main process to play the sound 
`ipcMain.on('sound:play', (e, item) => {
  playSound(sound)
})`

Since I can run the mp3 on fresh installations, I believe I have the correct file location. Please reopen

**Comment by nornagon** [comment]
@YeetOrBeYate I don't think the fact that `afplay` can run it means it's in the correct location, but it being under `Contents/Resources` seems like it should be fine.
