### ISSUE TITLE
[Bug]: Notification toast crash on windows

### ISSUE THREAD

**Issue by allgcc** [electron/electron#29854]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.9

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Expected Behavior

Normal display notification

### Actual Behavior

Electron somtimes crash, we haven't repeat it, but got crash report. 

Below is crash dump from windbg, seems it crash at DesktopNotificationController::CreateToast() :

*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*************************************************************************
***                                                                   ***
***                                                                   ***
***    Either you specified an unqualified symbol, or your debugger   ***
***    doesn't have full symbol information.  Unqualified symbol      ***
***    resolution is turned off by default. Please either specify a   ***
***    fully qualified symbol module!symbolname, or enable resolution ***
***    of unqualified symbols by typing ".symopt- 100". Note that     ***
***    enabling unqualified symbol resolution with network symbol     ***
***    server shares in the symbol path may cause the debugger to     ***
***    appear to hang for long periods of time when an incorrect      ***
***    symbol name is typed or the network symbol server is down.     ***
***                                                                   ***
***    For some commands to work properly, your symbol path           ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: $ntdllsym!_CONTEXT                            ***
***                                                                   ***
*************************************************************************
Unable to load image \\?\D:\aDrive\resources\app.asar.unpacked\node_modules\@ali\dt-nde-win32-ia32\dt-nde.win32-ia32.node, Win32 error 0n2
*** WARNING: Unable to verify timestamp for dt-nde.win32-ia32.node
***** OS symbols are WRONG. Please fix symbols to do analysis.

Unable to load image C:\Windows\SysWOW64\ole32.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for ole32.dll
*** WARNING: Unable to verify timestamp for filter_installer_biz.dll
*************************************************************************
***                                                                   ***
***                                                                   ***
***    Either you specified an unqualified symbol, or your debugger   ***
***    doesn't have full symbol information.  Unqualified symbol      ***
***    resolution is turned off by default. Please either specify a   ***
***    fully qualified symbol module!symbolname, or enable resolution ***
***    of unqualified symbols by typing ".symopt- 100". Note that     ***
***    enabling unqualified symbol resolution with network symbol     ***
***    server shares in the symbol path may cause the debugger to     ***
***    appear to hang for long periods of time when an incorrect      ***
***    symbol name is typed or the network symbol server is down.     ***
***                                                                   ***
***    For some commands to work properly, your symbol path           ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: nt!_CONTEXT                                   ***
***                                                                   ***
*************************************************************************

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.Sec
    Value: 2

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on D-V8511BF9-1643

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 26

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 1345

    Key  : Analysis.System
    Value: CreateObject

    Key  : Timeline.Process.Start.DeltaSec
    Value: 1237

CONTEXT:  (.ecxr)
eax=00000280 ebx=00000500 ecx=00000000 edx=001803fc esi=149b1f48 edi=14ba90dc
eip=02cab9f3 esp=0010e638 ebp=0010e688 iopl=0         ov up ei pl nz na po cy
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210a03
aDrive!electron::DesktopNotificationController::Toast::GetHeight [inlined in aDrive!electron::DesktopNotificationController::CreateToast+0x103]:
02cab9f3 8b411c          mov     eax,dword ptr [ecx+1Ch] ds:002b:0000001c=????????
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 02cab9f3 (aDrive!electron::DesktopNotificationController::Toast::GetHeight)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 0000001c
Attempt to read from address 0000001c

WRONG_SYMBOLS_TIMESTAMP: 5708a73e

WRONG_SYMBOLS_SIZE: 180000

FAULTING_MODULE: 77be0000 ntdll

ADDITIONAL_DEBUG_TEXT:  
You can run '.symfix; .reload' to try to fix the symbol path and load symbols. ; Followup set based on attribute [Is_ChosenCrashFollowupThread] from Frame:[0] on thread:[PSEUDO_THREAD]

STACK_TEXT:  
0010e638 02cab9f3 aDrive!electron::DesktopNotificationController::CreateToast+0x103
0010e690 02caacc9 aDrive!electron::DesktopNotificationController::CheckQueue+0x59
0010e6a8 02caae6e aDrive!electron::DesktopNotificationController::AddNotification+0x11e
0010e6d8 02caf081 aDrive!electron::Win32Notification::Show+0x121
0010e748 02bc6d7a aDrive!electron::api::Notification::Show+0x1fa
0010e8d0 02bc8231 aDrive!gin::internal::Dispatcher<void +0xd1
0010e8fc 02bc8141 aDrive!gin::internal::Dispatcher<void +0x31
0010e934 03710ebc aDrive!v8::internal::FunctionCallbackArguments::Call+0xec
0010e9a0 037109b1 aDrive!v8::internal::`anonymous namespace'::HandleApiCallHelper<0>+0x121
0010ea10 037107df aDrive!v8::internal::Builtin_Impl_HandleApiCall+0xaf
0010ea5c 037106ff aDrive!v8::internal::Builtin_HandleApiCall+0x2f
0010ea78 02d98677 aDrive!Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit+0x37
0010ea94 02d44606 aDrive!Builtins_InterpreterEntryTrampoline+0xc6
0010ead0 02d44606 aDrive!Builtins_InterpreterEntryTrampoline+0xc6
0010eb0c 02d44606 aDrive!Builtins_InterpreterEntryTrampoline+0xc6
0010eb60 02d44606 aDrive!Builtins_InterpreterEntryTrampoline+0xc6
0010eba8 02d42918 aDrive!Builtins_JSEntryTrampoline+0x58
0010ebc4 02d4273b aDrive!Builtins_JSEntry+0x5b
0010ebf0 0359ad3a aDrive!v8::internal::`anonymous namespace'::Invoke+0x21a
0010ece4 03599ac0 aDrive!v8::internal::Execution::Call+0x90
0010ed30 04453bb0 aDrive!v8::Object::CallAsFunction+0x160
0010eddc 0fb29734 dt_nde_win32_ia32!NJSFileUploadTaskCallback::OnNotify_on_node+0x1c4
0010ee50 0fb292fa dt_nde_win32_ia32!OnNotify_cb+0x8a
0010ee90 030531ec aDrive!uv_process_async_wakeup_req+0x1c
0010ee9c 030539a5 aDrive!uv_run+0x1e5
0010f6e8 02c8671b aDrive!electron::NodeBindings::UvRunOnce+0xab
0010f76c 03541c1c aDrive!base::TaskAnnotator::RunTask+0x12c
0010f800 035401f8 aDrive!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl+0x168
0010f8b8 0353fdd3 aDrive!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork+0xb3
0010f930 0371e66b aDrive!base::MessagePumpForUI::DoRunLoop+0x5b
0010f974 01372ce2 aDrive!base::MessagePumpWin::Run+0x42
0010f994 01c0fe9e aDrive!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run+0x7e
0010f9c8 0193ef9d aDrive!base::RunLoop::Run+0x8d
0010fa20 04980455 aDrive!content::BrowserMainLoop::MainMessageLoopRun+0x75
0010fa6c 0208c31e aDrive!content::BrowserMainRunnerImpl::Run+0xe
0010fa78 01dc089f aDrive!content::BrowserMain+0xdf
0010fad4 01dbcc31 aDrive!content::ContentMainRunnerImpl::RunBrowser+0x251
0010fb14 02d37802 aDrive!content::ContentMainRunnerImpl::Run+0x112
0010fb5c 01fc940d aDrive!content::RunContentProcess+0x3ed
0010fc5c 01fc8faf aDrive!content::ContentMain+0x2f
0010fc7c 02b8184c aDrive!wWinMain+0x2dc
0010fd24 03c5e48a aDrive!__scrt_common_main_seh+0xf8
0010fd70 766a338a kernel32+0x1338a
0010fd7c 77c19902 ntdll+0x39902
0010fdbc 77c198d5 ntdll+0x398d5

FAULTING_SOURCE_LINE:  C:\projects\src\electron\shell\browser\notifications\win\win32_desktop_notifications\desktop_notification_controller.cc

FAULTING_SOURCE_FILE:  C:\projects\src\electron\shell\browser\notifications\win\win32_desktop_notifications\desktop_notification_controller.cc

FAULTING_SOURCE_LINE_NUMBER:  332

SYMBOL_NAME:  ntdll_wrong_symbols!5708A73E180000

STACK_COMMAND:  .ecxr ; kb ; ** Pseudo Context ** Pseudo ** Value: 60528a18 ** ; kb

BUGCHECK_CODE:  5708a73e

EXCEPTION_CODE_STR:  5708A73E

EXCEPTION_STR:  WRONG_SYMBOLS

PROCESS_NAME:  ntdll.wrong.symbols.dll

IMAGE_NAME:  ntdll.wrong.symbols.dll

MODULE_NAME: ntdll_wrong_symbols

FAILURE_BUCKET_ID:  WRONG_SYMBOLS_X86_TIMESTAMP_160409-065454_5708A73E_ntdll.wrong.symbols.dll!5708A73E180000

OSPLATFORM_TYPE:  x86

OSNAME:  Windows 7

FAILURE_ID_HASH:  {050e7b6a-a64a-f805-9eef-ad9b0ce90e91}

Followup:     MachineOwner
---------

**Comment by VerteDinde** [comment]
Hey @allgcc, thanks for reporting this issue! Could you provide a small repro of the issue that we could take a deeper look at? Or if that's not easily possible (and I understand it may not be), could you include the original crash dmp file so we can take a closer look? It's a little hard to take action on what you provided here, so any more information you can provide would be helpful. Thanks!

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by fuwenchun** [comment]
@VerteDinde @sofianguy issue #29054 has the same issue, and i include the original crash dmp file.
