### ISSUE TITLE
[Bug]: Windows Defender real-time protection causes slow boot for utility processes

### ISSUE THREAD

**Issue by c3er** [electron/electron#29868]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 21H1

### What arch are you using?

x64

### Expected Behavior

The first file, referenced by `index.html` (loaded by `main.js`) loads as fast as the files after the first file or at least much faster.

### Actual Behavior

The `main.js` loads a file `index.html` that itself references a style sheet and a JavaScript file:

```js
function createWindow() {
    _mainWindow = new electron.BrowserWindow()
    _mainWindow.loadFile(path.join(__dirname, "index.html"))
    _mainWindow.on("closed", () => _mainWindow = null)
}
```

The style sheet that is referenced first takes around 1.7 seconds to load while following files take only like 1ms to load. The start up time of my Electron app is delayed by this 1.7s because of this. I don't know where this delay comes from and how to fix this in the user code.

See the output of my test application:

```
$ npm start

> electron-performance-issue@1.0.0 start D:\electron-performance-issue
> electron .


Loading: file:///D:/electron-performance-issue/app/index.html (14 ms since last load)
Loading: file:///D:/electron-performance-issue/app/index.css (1775 ms since last load)
Loading: file:///D:/electron-performance-issue/app/index.js (0 ms since last load)
```

I considered using Webpack but

- The [electron-webpack-quick-start](https://github.com/electron-userland/electron-webpack-quick-start) uses old dependencies and I didn't manage it yet to get it running with current versions
- I like to keep out this additional dependency and configuration effort

### Additional Information

I made a repository with the minimal code for this issue: https://github.com/c3er/electron-performance-issue

**Comment by nornagon** [comment]
I don't see nearly as big of a spread. On macOS:

```
Loading: file:///Users/nornagon/work/repro/29868/app/index.html (298 ms since last load)
Loading: file:///Users/nornagon/work/repro/29868/app/index.css (62 ms since last load)
Loading: file:///Users/nornagon/work/repro/29868/app/index.js (2 ms since last load)
```

On Windows (in a VM):

```
Loading: file:///Z:/work/repro/29868/app/index.html (18 ms since last load)
Loading: file:///Z:/work/repro/29868/app/index.css (245 ms since last load)
Loading: file:///Z:/work/repro/29868/app/index.js (1 ms since last load)
```

I'm not sure why it's the _second_ file on Windows and the first on Mac, but ~300ms seems par for the course for loading a fresh renderer.

Perhaps you could record a trace of the load? Run the app with `--trace-startup=* --trace-startup-file=trace.json --trace-startup-duration=5`, then attach `trace.json` here.

**Comment by c3er** [comment]
Here is the file [trace.zip](https://github.com/electron/electron/files/6704897/trace.zip) containing `trace.json`. Uploading a JSON file directly is not supported by GitHub. 😂

Note: I had to add the parameters to the start script in `package.json`. When I tried to append the arguments to `npm start` the `trace.json` was not generated.

**Comment by nornagon** [comment]
Thanks. It looks like launching the GPU process is probably what's taking a second or so:
![image](https://user-images.githubusercontent.com/172800/123178406-f98f2900-d43b-11eb-8aad-823715000f8a.png)

Does this also happen in Chrome? Try e.g. downloading [Chrome Canary](https://www.google.com/chrome/canary/) and launching it with a url as the first argument on the command-line. You can pass `--trace-startup` and all the rest to it as well to get a trace file.

**Comment by c3er** [comment]
Here is a the [trace.zip](https://github.com/electron/electron/files/6705302/trace.zip) from Chrome Canary. Chrome starts very fast on my machine, both with a an internet URL (google.com) and a local file (the index.html of the [reproduction app](https://github.com/c3er/electron-performance-issue))

**Comment by nornagon** [comment]
Interesting, looks like Chrome only took ~8ms to launch the gpu process:

![image](https://user-images.githubusercontent.com/172800/123180247-c51d6c00-d43f-11eb-9da6-46b38b07512a.png)

I'm not sure what the discrepancy here could be :/

**Comment by c3er** [comment]
Maybe some Windows security feature?

For the case that more information about my system could help:

- Windows is set to German language and locale (de_DE)
- GPU is GeForce GTX 290
    - Driver version 27.21.14.5167 (NVIDIA 451.6)
- CPU is Core i7 4790K (Haswell) at 4 GHz
- Mainboard is Z97-PRO GAMER
- RAM: 24 GB DDR3

Is it maybe possible to deactivate GPU-Acceleration in Electron? It would be a workaround at least and if it helps I wouldn't mind too much for [my application](https://github.com/c3er/mdview).

**Comment by nornagon** [comment]
You could try with `--disable-gpu` and/or `--in-process-gpu`. Are you running any antivirus software?

**Comment by c3er** [comment]
It now runs only a little faster with both flags and also each flag only:

```
$ npm start

> electron-performance-issue@1.0.0 start D:\eigene dateien\devel\web\electron-performance-issue
> electron . --in-process-gpu --disable-gpu --trace-startup=* --trace-startup-file=trace.json --trace-startup-duration=5


Loading: file:///D:/electron-performance-issue/app/index.html (14 ms since last load)
Loading: file:///D:/electron-performance-issue/app/index.css (1628 ms since last load)
Loading: file:///D:/electron-performance-issue/app/index.js (1 ms since last load)
```

[trace.zip](https://github.com/electron/electron/files/6705396/trace.zip) of this run.

**Comment by nornagon** [comment]
hm, looks like it's now taking a long time to load some utility process (network process maybe?)

![image](https://user-images.githubusercontent.com/172800/123182512-7920f600-d444-11eb-85c6-301a0baa965c.png)

Do you see the same behavior with Electron 11, 12 or 14?

**Comment by c3er** [comment]
I saw the bad performance in older Electron versions. I'll provide more information in the coming days when I have time again.

**Comment by c3er** [comment]
I missed the question about anti virus!

I only run Windows Defender. My Windows Smart Screen is turned off.

**Comment by aochagavia** [comment]
This could be related to Windows Defender's real-time protection. I recently experienced slow startup and opened a question on StackOverflow (you can see it [here](https://stackoverflow.com/questions/67982430/windows-defender-slowing-down-electron-startup)). It turns out that disabling Windows Defender's real-time protection gave me the expected startup speed.

The mysterious thing is, though, that other apps like VSCode open quite fast on my machine, even with Defender's real-time protection enabled. Maybe it is possible to build your application in such a way that Defender doesn't get in the way.

**Comment by c3er** [comment]
@aochagavia

> This could be related to Windows Defender's real-time protection.

You're right! I just tried turning off the real time protection and the delay was gone.

@nornagon Do you have Windows Defender activated on your Windows VM and do you see the same behavior with activated Windows Defender?

Can the Electron team do anything about it or do we have to live with this annoyance until Microsoft does a Change in Windows Defender that could help? If so, would a new issue describing this problem better or is this issue here still appropriate?

> The mysterious thing is, though, that other apps like VSCode open quite fast on my machine, even with Defender's real-time protection enabled. Maybe it is possible to build your application in such a way that Defender doesn't get in the way.

I don't find that mysterious at all. VS Code is a very widespread application that has almost certainly a working certificate. Not to mention that VS Code is produced by Microsoft itself.

> Maybe it is possible to build your application in such a way that Defender doesn't get in the way.

The thing that I observed is, that the `index.html` loaded by the `main.js` loads very fast. Only the first file referenced by the `index.html` gets this delay. As mentioned above, I considered using Webpack but I don't like this for reasons also mentioned above.

My short-term workaround now is to add the development and installation path of my app to the Windows Defender exclusion list. But this can obviously only be workaround and not a solution to this problem.

**Comment by c3er** [comment]
@nornagon

> Do you see the same behavior with Electron 11, 12 or 14?

The other Electron version (14 and down to 9) behave the same. Though the delay is a little smaller with the old versions.

```
$ npm start

> electron-performance-issue@1.0.0 start D:\electron-performance-issue
> electron . --trace-startup=* --trace-startup-file=trace.json --trace-startup-duration=5


Loading: file:///D:/electron-performance-issue/app/index.html (14 ms since last load)
Loading: file:///D:/electron-performance-issue/app/index.css (1425 ms since last load)
Loading: file:///D:/electron-performance-issue/app/index.js (1 ms since last load)
```

Here is the trace file for Electron 9: [trace-9.4.4.json.zip](https://github.com/electron/electron/files/6721191/trace-9.4.4.json.zip)

**Comment by nornagon** [comment]
Hm, I don't know enough about Windows Defender to be able to form a hypothesis as to what might be causing this issue, and whether there might be an Electron-side change that could mitigate it. One thing to try might be to check if a codesigned app exhibits the same behavior, see https://www.electronjs.org/docs/tutorial/code-signing#signing-windows-builds for docs.

**Comment by c3er** [comment]
> One thing to try might be to check if a codesigned app exhibits the same behavior, see https://www.electronjs.org/docs/tutorial/code-signing#signing-windows-builds for docs.

Thanks, but I self-sign [my app](https://github.com/c3er/mdview) for a while already with no effect.

I have the problem that Google Chrome and Windows Smart Screen don't like some EXE files from the Evil Internet and I read somewhere that self-signing might help if the app is downloaded often enough. I'm afraid, my app is very far away from this threshold if it even really exists. I don't want to pay an annual fee for a hobby project.

**Comment by nornagon** [comment]
I'm going to close this for now as it's unclear that this is anything outside of the ordinary for Windows Defender, and so there's no clear action for us to take. If we learn otherwise I'm happy to reopen.

**Comment by facuparedes** [comment]
> This could be related to Windows Defender's real-time protection. I recently experienced slow startup and opened a question on StackOverflow (you can see it [here](https://stackoverflow.com/questions/67982430/windows-defender-slowing-down-electron-startup)). It turns out that disabling Windows Defender's real-time protection gave me the expected startup speed.
> 
> The mysterious thing is, though, that other apps like VSCode open quite fast on my machine, even with Defender's real-time protection enabled. Maybe it is possible to build your application in such a way that Defender doesn't get in the way.
> 
> Btw, I setup a [repo](https://github.com/aochagavia/ElectronSOQuestion) which prints timings to the console, which I found quite useful for debugging. Maybe it can be of use for people interested in investigating this issue.

Hey! Did u find a fix? Visual Studio Code, Discord, and Spotify have a very low startup time. Disabling Windows Defender's real-time protection improves my app startup by up to 90%, It's amazing! However, we cannot ask users to disable windows defender real-time protection or ask them to add the executable file to their excluded list.

**Comment by sibyl666** [comment]
@facuparedes Did you managed to solve it? When I disable real-time protection my app startup speeds up 90% as you said.

**Comment by sibyl666** [comment]
@nornagon Hey, Is there any news on this?

**Comment by pmatula** [comment]
> 

I'm worried that no one is working on it.

**Comment by c3er** [comment]
I just filed a bug report via the Windows **Feedback Hub**:

> ## Windows Defender causes startup delay in some Electron.js apps
> 
> See also this bug report in Electron.js issue tracker: https://github.com/electron/electron/issues/29868
> 
> The startup delay was observed in self written Electron.js apps. If the directory containing the Electron.js executable is in the Windows Defender exclusion list or the real time protection is turned off at all, the app starts up without delay. This delay is between 1.5 and 3 seconds. See the above linked Electron.js issue for more details.
> 
> I also made a repository containing the minimal amount of code to reproduce this issue: https://github.com/c3er/electron-performance-issue

A suggest to all who are affected by this issue to do the same.

(Maybe the Electron team, that belongs at least indirectly to Microsoft, and the Windows Defender team should work together?)

**Comment by pmatula** [comment]
> 

Can you share a link to the issue? So we can upvote it. :-)

**Comment by c3er** [comment]
> Can you share a link to the issue? So we can upvote it. :-)

Sorry, didn't thought about that.

https://aka.ms/AAfnseb

So, please upvote this🙂

**Comment by pmatula** [comment]
> Author

Cool, for whatever reason (maybe because I'm on Windows 11?) I can't access your feedback.

**Comment by sibyl666** [comment]
@pmatula Make sure you are logged in to your account ın feedback hub. I wasn't able to access it without logging in.

**Comment by xland** [comment]
#32375

**Comment by grafanauser** [comment]
same issue here. 
- in an old windows 10 VM with windows defender disabled. 
  - portable.exe starts within 5-10s.
  - win-upacked exe: starts even faster
- On my current non-vm windows 10 system:
  - portable.exe: it takes already 20-40s for the electron-builder splash screen to appear. closing the app and starting it again does not speed up the start up at all (maybe 10s less). Using "useZip":true even triples (!) the startup time (120s).
  - win-unpacked exe: takes 20s+ on first startup. On consecutive startups it appears almost instant

**Comment by blling** [comment]
Hi guys, i do not see the solution, how to speed up?

**Comment by metkm** [comment]
@blling If you don't see the solution then there is no solution sadly. Maybe try buying a certificate from Microsoft.

**Comment by herrbasan** [comment]
Would signing an Electron app actually prevent Defender from doing what ever it is doing to slow down the startup ? Would be nice if someone who has done that to confirm.

**Comment by max-sistemich-kisters** [comment]
@herrbasan No, unfortunately signing the binary doesn't change the slow startup time.
