### ISSUE TITLE
[Bug]: Link error for native c++ modules

### ISSUE THREAD

**Issue by TanninOne** [electron/electron#29893]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home (19042)

### What arch are you using?

x64

### Expected Behavior

The native module in the testcase gist should be able to link.
The problematic part is the function v8::ArrayBuffer::GetBackingStore()

### Actual Behavior

Linking fails with the error
`error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cd ecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ) re ferenced in function "void __cdecl foobar(class v8::FunctionCallbackInfo<class v8::Value> const &)" (?foobar@@YAXAEBV?$FunctionCallbac kInfo@VValue@v8@@@v8@@@Z) [c:\Work\repro_bug_arraybuffer\build\foobar.vcxproj]`

### Testcase Gist URL

https://gist.github.com/TanninOne/d321ab1676798647cf672f08e78b88d8

### Additional Information

Building the same module for node 14.17.1 works fine.

The error message, although cryptic, is correct: the header and link library shipped do not seem to match. the header declares GetBackingStore like this:
`std::shared_ptr<BackingStore> GetBackingStore();`
but the library exports this:
`?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@__1@std@@XZ`
which demangles to
`public: class std::__1::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void) __ptr64`

so as far as I understand it the namespace is different and thus the linker doesn't find the function.
node.exe version 14.17.1 otoh exports
`?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ`
aka
`public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void) __ptr64`

which matches the declaration in v8.h exactly.

With prior versions of electron (up to 12 I think) we could use the deprecated function GetContent to get at the content of an ArrayBuffer but that function has been removed so until this is fixed, if I'm not completely mistaken, any native module that requires access to the content of an ArrayBuffer, including helper libraries like nan or nbind and all modules that depend on _those_ will be broken.

**Comment by miniak** [comment]
I ran into the same issue. I ended up changing my API to use node::Buffer instead

**Comment by miniak** [comment]
https://github.com/nodejs/node/blob/master/src/node_buffer.h

**Comment by MarshallOfSound** [comment]
This is a deliberate change that I think we're still in the process of fully documenting / supporting.

Basically for this _one_ API you have to build against libc++ rather than whatever standard library you happen to be using for your native module.  There's a long story for why this is the case but it comes down to standard library's not actually being standard.

See https://github.com/electron/electron-rebuild/pull/703 for a draft of supporting this in electron-rebuild.

**Comment by nornagon** [comment]
Just a note: I'd recommend that all native modules use N-API and avoid nan, for this kind of reason. C++ ABIs are very difficult to stabilize. N-API is explicitly designed as a stable ABI target. https://nodejs.org/api/n-api.html

**Comment by TanninOne** [comment]
@miniak Thank you for the suggestion, unfortunately this particular use of ArrayBuffer is in a foreign library (nbind) which I'd rather not get too deep into

@MarshallOfSound that makes sense, I found a bit after I posted this that the __1 namespace is appended to prevent accidentally linking to the wrong std implementation. Still weird that it works linking against node.
Also: I'm working with windows and msvc, I don't expect I can just use libc++ instead of the shipped standard libraries?
Is the solution here to switch to clang?

@nornagon I'm definitively moving my modules to N-API piece by piece but it takes time as I can't invest too much time into it.

**Comment by MarshallOfSound** [comment]
> Is the solution here to switch to clang?

Yep, using the same clang + std library that Electron uses to build is the safest way to build native modules that interact with the std library.

**Comment by kjvalencik** [comment]
@miniak Thanks for sharing that `Buffer` works. As a workaround, an `ifdef` could be used when compiling for Windows and Electron to first construct a Buffer [from the `ArrayBuffer`](https://github.com/nodejs/node/blob/4e1181761dd10a4c9afa707e28c13248bf0fc05f/src/node_buffer.h#L69-L72) and then use `node::Buffer::Data` to get the contents.

Is there a `#def` that can be used for checking the Electron version?

**Comment by kjvalencik** [comment]
I ended up adding the following to my `node-gyp` config:

```js
{
        'variables': { 'runtime%': 'node' },
        'conditions': [
            ['runtime=="electron"', { 'defines': ['NODE_RUNTIME_ELECTRON=1'] }],
        ]
}
```

And using the follow `#if`

```c++
  #if _MSC_VER && NODE_RUNTIME_ELECTRON && NODE_MODULE_VERSION >= 89
    v8::Local<v8::Object> local;
    node::Buffer::New(isolate, buffer, 0, buffer->ByteLength()).ToLocal(&local);
    return Neon_Buffer_Data(isolate, base_out, local);
  #else
    #if (V8_MAJOR_VERSION >= 8)
        auto contents = buffer->GetBackingStore();
        *base_out = contents->Data();
        return contents->ByteLength();
    #else
        v8::ArrayBuffer::Contents contents = buffer->GetContents();
        *base_out = contents.Data();
        return contents.ByteLength();
    #endif
  #endif
```

Not the most elegant or low cost solution, but hopefully that works as a stop gap while my users migrate to Node-API.

Is there a `#def` that can be used to tell if the module is being built for electron? My solution was a bit convoluted.

**Comment by somanuell** [comment]
> ```c++
> v8::Local<v8::Object> local;
>     node::Buffer::New(isolate, buffer, 0, buffer->ByteLength()).ToLocal(&local);
>     return Neon_Buffer_Data(isolate, base_out, local);
> ```

I don't understand that code. What is Neon_Buffer_Data? Where does go the node::Buffer::New result?

**Comment by kjvalencik** [comment]
@somanuell That's a sample of the [neon project](https://github.com/neon-bindings/neon) source. `Neon_Buffer_Data` is a very small helper that gets the contents of the buffer:

```c++
  *base_out = node::Buffer::Data(obj);
  return node::Buffer::Length(obj);
```

The result of `node::Buffer::New` goes into `local` and then `node::Buffer::Data` can be used to get the buffer data out.

**Comment by mmomtchev** [comment]
@VerteDinde, I find the decision to build Electron on Windows using a C++ runtime that it just out of beta instead of the MS C++ runtime highly unusual - but there is probably a good reason for it. But in this case, I suggest that you also include this runtime along the `node.lib` DLL import library so that native modules can link with it. Currently, if I want to port my native Node.js addon to Electron I have only two choices and both are horrible:
* Reimplement the APIs that use `std::shared_ptr` as some people in this thread did
* Recompile the clang `libc++` for Windows

All of this renders the port of a native Node.js addon to Electron a huge undertaking and completely destroys the dream of simply launching `electron-rebuild` and going for a cup of coffee.

**Comment by mmomtchev** [comment]
@VerteDinde Or as a plan B, I can suggest you a very ugly kludge that gets the job done with almost no modifications:

Patch `v8/src/api/api.cc` to include a second form of `GetBackingStore` that returns a raw pointer then make `NAN` use this second form. You don't need a `shared_ptr` for the use that `NAN` makes of it in `TypedArrayContents`. It is horrible, but it will allow you get working a ton of native Node.js addons while changing two lines of code.

**Comment by dogeFu** [comment]
I use node::Buffer::new  api to replace v8 api to solve this problem.But it's not easy when you have third library that use those api.Hope there will be more wasy way to do it.

**Comment by lygstate** [comment]
A possible solution is just diable this v8 api and forcing using to always using  node::Buffer::new instead, or
mock this v8 api to use node::Buffer::new instead in released v8 header, so the issue will be gone

**Comment by GitMurf** [comment]
@dogeFu / @lygstate could you please guide me in how I could replace to use `node::Buffer::new` instead of v8 api? I have been trying to figure this out for weeks! Thank you so much!

**Comment by GitMurf** [comment]
> @VerteDinde Or as a plan B, I can suggest you a very ugly kludge that gets the job done with almost no modifications:
> 
> Patch `v8/src/api/api.cc` to include a second form of `GetBackingStore` that returns a raw pointer then make `NAN` use this second form. You don't need a `shared_ptr` for the use that `NAN` makes of it in `TypedArrayContents`. It is horrible, but it will allow you get working a ton of native Node.js addons while changing two lines of code.

@mmomtchev could you explain this a little further on how I could do this? I am simply trying to get node-canvas to work with Electron and having issues with NAN and `GetBackingStore`. Thanks so much!

**Comment by dogeFu** [comment]
@GitMurf  for example, replace v8::ArrayBuffer::GetBackingStore()->Data()  with node::Buffer::Data(). Just Replace API that has link error when you build project.

**Comment by GitMurf** [comment]
@dogeFu thank you so much for the quick reply! I couldn't get what you suggested to work but I am very very inexperienced at trying to mess with dependencies (especially native ones as I am not a c++ guy). The following code is the one giving me the problem and I am not sure how to update this in `nan` accordingly. The culprit is: `data = static_cast<char*>(buffer->GetBackingStore()->Data()) + byte_offset;`

Thanks so much for your help!

![image](https://user-images.githubusercontent.com/64155612/203895550-87b23da4-eedd-4471-86a3-afe4461a08d4.png)
