### ISSUE TITLE
[Bug]: Opening https://google.com through mainWindow.loadURL causes crash on MacOS

### ISSUE THREAD

**Issue by mesner** [electron/electron#29898]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0,13.1.4

### What operating system are you using?

macOS

### Operating System Version

Replicated on High Sierra and Big Sur

### What arch are you using?

x64

### Last Known Working Electron version

12.0.12

### Expected Behavior

The google homepage displays and electron does not crash.

### Actual Behavior

The google homepage displays momentarily before crashing with the following in the command line:
```
/Users/imesner/Library/Application Support/electron-quick-start/Crashpad
[0625/151416.249225:WARNING:crash_report_exception_handler.cc(240)] UniversalExceptionRaise: (os/kern) failure (5)
/Users/imesner/Documents/projects/electron-quick-start/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/imesner/.npm/_logs/2021-06-25T19_14_16_337Z-debug.log
```
[2021-06-25T19_14_16_337Z-debug.log](https://github.com/electron/electron/files/6718375/2021-06-25T19_14_16_337Z-debug.log)
[a9dd4755-9632-4846-a961-6c5ab9a1f7ac.dmp.zip](https://github.com/electron/electron/files/6718379/a9dd4755-9632-4846-a961-6c5ab9a1f7ac.dmp.zip)

### Testcase Gist URL

https://gist.github.com/3789d550b0a1577807892c92630ae59f

### Additional Information

log and pending crash dump attached.  No completed crashpad dumps were created

**Comment by Buminta** [comment]
Hey Bro. Google's blocked your useragent. You can change UserAgent for that.

**Comment by vladimiry** [comment]
See https://github.com/electron/electron/issues/29343#issuecomment-863832234

**Comment by codebytere** [comment]
Closing in agreement with @vladimiry comment above - see that issue for updates.
