### ISSUE TITLE
[Bug]: MacOS window shadow incorrect when using vibrancy

### ISSUE THREAD

**Issue by holmesal** [electron/electron#29894]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.4

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4

### What arch are you using?

x64

### Expected Behavior

When using a vibrancy view (`vibrancy: 'under-window'`) with `transparent: true`, window shadows are rendered correctly when...

1. Transitioning to Mission Control.
2. Switching between workspaces.

### Actual Behavior

Window shadows shrink when Mission Control is opened:

https://user-images.githubusercontent.com/1147390/123418733-ae9b2000-d5b9-11eb-8d2b-da74dc11002f.mp4

Window shadows get stuck in the incorrect state when switching windows via Mission Control, and then switching back:

https://user-images.githubusercontent.com/1147390/123418593-83183580-d5b9-11eb-8bcf-7bb9a41d3bfa.mp4

### Testcase Gist URL

https://gist.github.com/35b62a31e1c2d43eea4557d6295c420f

**Comment by robin-fowler** [comment]
am seeing the same problem on 15.2.0

pretty sure this was fixed at one point and has now returned
