### ISSUE TITLE
[Bug]: Frameless window can't receive events on elements with `-webkit-app-region: drag` (Windows only)

### ISSUE THREAD

**Issue by oleg-slapdash** [electron/electron#29891]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home

### What arch are you using?

x64

### Last Known Working Electron version

Tested everything till 8.X, nothing works

### Expected Behavior

When a user clicks on input (without dragging) with `-webkit-app-region: drag` the input is focused and a click event is passed through to JavaScript. Same as MacOS. Alternatively, please provide a workaround.

### Actual Behavior

If an input (or any element) is marked with `-webkit-app-region: drag` it does not receive any events when the user clicks/drags it.

### Testcase Gist URL

https://gist.github.com/1db66b2afe7e7f5f5c4a93fc788705f4

### Additional Information

Works amazingly on MacOS, does not work on Windows.

**Demo Windows:**
![2021-06-24 22 19 35](https://user-images.githubusercontent.com/73438352/123360703-c338d300-d53b-11eb-9f14-8d75d8853eb1.gif)
**Demo Mac:**
![2021-06-24 22 19 05](https://user-images.githubusercontent.com/73438352/123360717-c764f080-d53b-11eb-8a30-97f12972e46c.gif)

**Comment by weifeiyue** [comment]
When will this version be released?

**Comment by nornagon** [comment]
Unfortunately this is an OS limitation and is not possible to work around on Windows. Per the note here: https://www.electronjs.org/docs/api/frameless-window#draggable-region you can try marking the input with `-webkit-app-region: no-drag`.

**Comment by oleg-slapdash** [comment]
@nornagon Thank you for replying, 

First of all, if this is an OS limitation, then this behaviour should be documented (it is not documented at this point). In addition to that, can you please point me to where this limitation stems from? It seems like win32 API has a way to detect clicks on the title bar, etc.

Adding `-webkit-app-region: no-drag` to the input is not really a bug fix since the end goal is to have a frameless window that contains only input and it is draggable (like Spotlight on Mac). Making the input non-draggable makes the app not useful at all. The goal is to have an input window that can be dragged. Maybe you have a better workaround?

Thanks!

**Comment by nornagon** [comment]
The difficulty is in figuring out which events to allow the OS to handle and which events to capture and prevent the OS from handling. Perhaps it is more clear if you imagine dragging to select text in the input box. Windows's event loop requires that we pass the mousedown event to Windows when it falls inside the non-client area, otherwise it will not process the subsequent mouse move events as drags.

**Comment by oleg-slapdash** [comment]
@nornagon Thank you for the clarification. Maybe it is possible to pass through only click/mouse down events? Right now it is impossible to detect ANY mouse events when the user clicks on the draggable area. It could be a good stopgap solution to pass click events to JS when the user clicks on the draggable area. If that is also impossible, maybe have an event handler in the main process? All I need to make it somewhat work is to know that the user clicked on a draggable input. If I know that, I can provide some basic UX like focusing the input.

**Comment by czzonet** [comment]
same problem
