### ISSUE TITLE
[Bug]: Second of two successive HTTP requests is not executed (Ubuntu)

### ISSUE THREAD

**Issue by ValentinSteiner** [electron/electron#29901]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

* Electron 13.1.4
* Ubuntu 16.04, Ubuntu 20.04 x64

### Synopsis

I'm making two successive HTTP requests immediately after each other: the second one is fired when the response of the first one comes in. However, the second HTTP request is not made right away, but "hangs" until other traffic pushes it through.

### Expected Behavior

When running the reproducer, the DevTools console should print

```
CONNECT 0
1st HTTP request: 200
2nd HTTP request: 200

CONNECT 1
1st HTTP request: 200
2nd HTTP request: 200

CONNECT 2
1st HTTP request: 200
2nd HTTP request: 200

..
```

### Actual Behavior

The second request does not go through immediately. Instead, it is fired as soon as the next 1st request is made.

```
CONNECT 0
1st HTTP request: 200

CONNECT 1
2nd HTTP request: 200
1st HTTP request: 200
2nd HTTP request: 200

CONNECT 2
1st HTTP request: 200

CONNECT 3
2nd HTTP request: 200
1st HTTP request: 200

CONNECT 4
2nd HTTP request: 200
1st HTTP request: 200

..
```

### Testcase Gist URL

https://github.com/ValentinSteiner/bug-successive-http-requests

### Additional Information

* It seems to be some sort of timing error, I've seen it work differently upon app startup as opposed to later.
* If the second connection is not established right away, it is pushed through on the next 1st HTTP request.
* I first noticed the issue when using the request library. To drill down, I switched to the native http module, the error remained.
* The issue may have to do with accessing a local HTTP server. Running against a server on the internet works most of the time.
* The issue only appears if we read the response body in myreq.js (by attaching a handler to the 'data' event).
* The bug is NOT reproducible on Windows 10, macOS 10.13.
* The bug is reproducible on Ubuntu 16.04, 20.04.
* Note that running `node client.js` exhibits the correct behavior.

### Workaround
* Delaying the second request using `setTimeout` is a workaround to get the desired behavior.

**Comment by que1414** [comment]
> ### Danh sách kiểm tra Preflight
> * [x] Tôi đã đọc [Nguyên tắc đóng góp](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) cho dự án này.
> * [x] Tôi đồng ý tuân theo [Quy tắc Ứng xử](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) mà dự án này tuân thủ.
> * [x] Tôi đã tìm kiếm trình [theo dõi vấn đề](https://www.github.com/electron/electron/issues) cho một yêu cầu tính năng phù hợp với yêu cầu tôi muốn gửi nhưng không thành công.
> 
> ### Phiên bản Electron
> 13.1.4
> 
> ### Bạn đang sử dụng hệ điều hành nào?
> Ubuntu
> 
> ### Phiên bản hệ điều hành
> 16.04, 20.04
> 
> ### Bạn đang sử dụng vòm nào?
> x64
> 
> ### Phiên bản Electron làm việc được biết đến cuối cùng
> _Không phản hồi_
> 
> ### Hành vi mong đợi
> Bảng điều khiển DevTools sẽ in
> 
> ```
> CONNECT 0
> 1st HTTP request: 200
> 2nd HTTP request: 200
> 
> CONNECT 1
> 1st HTTP request: 200
> 2nd HTTP request: 200
> 
> CONNECT 2
> 1st HTTP request: 200
> 2nd HTTP request: 200
> 
> ..
> ```
> 
> ### Hành vi thực tế
> Yêu cầu thứ hai không được thực hiện ngay lập tức. Thay vào đó, nó được kích hoạt ngay sau khi yêu cầu đầu tiên tiếp theo được thực hiện.
> 
> ```
> CONNECT 0
> 1st HTTP request: 200
> 
> CONNECT 1
> 2nd HTTP request: 200
> 1st HTTP request: 200
> 2nd HTTP request: 200
> 
> CONNECT 2
> 1st HTTP request: 200
> 
> CONNECT 3
> 2nd HTTP request: 200
> 1st HTTP request: 200
> 
> CONNECT 4
> 2nd HTTP request: 200
> 1st HTTP request: 200
> 
> ..
> ```
> 
> ### URL Gist của Testcase
> https://github.com/ValentinSteiner/bug-successive-http-requests
> 
> ### thông tin thêm
> * Nó dường như là một số loại lỗi thời gian, tôi đã thấy nó hoạt động khác khi khởi động ứng dụng trái ngược với sau đó.
> * Nếu kết nối thứ hai không được thiết lập ngay lập tức, nó sẽ được đẩy qua yêu cầu HTTP thứ nhất tiếp theo.
> * Lần đầu tiên tôi nhận thấy vấn đề khi sử dụng thư viện yêu cầu. Để đi sâu hơn, tôi đã chuyển sang mô-đun http gốc, lỗi vẫn còn.
> * Sự cố có thể liên quan đến việc truy cập máy chủ HTTP cục bộ. Hầu hết thời gian hoạt động đối với một máy chủ trên internet.
> * Sự cố chỉ xuất hiện nếu chúng tôi đọc nội dung phản hồi trong myreq.js (bằng cách đính kèm một trình xử lý vào sự kiện 'dữ liệu').
> * Lỗi KHÔNG thể tái tạo trên Windows 10, macOS 10.13.
> * Lỗi có thể tái tạo trên Ubuntu 16.04, 20.04.
> * Lưu ý rằng việc chạy `node client.js`thể hiện hành vi chính xác.
> * Trì hoãn yêu cầu thứ hai bằng cách sử dụng `setTimeout`là một giải pháp để có được hành vi mong muốn.

**Comment by ValentinSteiner** [comment]
I came across https://github.com/electron/electron/issues/10570, which seems to describe the same issue. It was not resolved, and closed in 2019.

**Comment by nornagon** [comment]
This smells like a libuv / event-loop-integration issue. cc @codebytere

**Comment by ValentinSteiner** [comment]
The error is also tied to DNS lookups, as already indicated in https://github.com/electron/electron/issues/10570.

The error only occurs when the host is given as a domain name. The error does not occur when using an IP address.

| Host specification                      | Reproducible? |
| ---                                     | --- |
| const URL = "http://localhost:7070";    | REPRO  |
| const URL = "http://127.0.0.1:7070";    | no repro  |
| const URL = "http://example.com:7070";  | REPRO, but slightly less pronounced *  |
| const URL = "http://1.2.3.4:7070";      | no repro  |

(*) The first pair of requests fails, but subsequent request pairs are completed more reliably than in the localhost scenario. There still are execution hickups in subsequent request pairs, but most pairs are executed correctly.

**Comment by ValentinSteiner** [comment]
The error is still present in the current stable version 15 as well as in the nightly build.

**Comment by ValentinSteiner** [comment]
This rather nasty bug seems to have been fixed a few versions ago:

```
Electron 15.5.7 still shows the problem
Electron 16.0.0 still shows the problem
Electron 17.4.11 still shows the problem
Electron 18.3.15 still shows the problem
Electron 19.0.0 works correctly
Electron 19.1.1 works correctly
Electron 20.3.0 works correctly
Electron 21.0.1 works correctly
```

I couldn't find anything that might have caused it to be fixed in Electron 19's release notes, though.
