### ISSUE TITLE
[Bug]: autoUpdater is awfully undocumented

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#29908]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

macOS

### Operating System Version

macOS Mojave 10.14.6

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

The autoUpdater module is arguably one of the most critical ones, so it must be documented decently.

### Actual Behavior

It's awfully undocumented.

### Testcase Gist URL

N/A

### Additional Information

The main issue I have with the docs for autoUpdater is that autoUpdater relies on a server to tell it if there's an update available, but what the server should actually do is **completely undocumented**, which is a major issue.

I've looked at the code behind `update.electronjs.org` too but that's also pretty vague, like:

- What should happen when no update is available? Is returning a 404 ok? Will that lead to an exception, an "error" event, an "update-not-available" event...?
- What's the actual expected format of the JSON object returned by the server? Is only a "url" property pointing to the file to download enough? The types for the arguments passed to the callback for the "update-available" seem to be wrong too, like they say the release notes and the release date are always available, but even `update.electronjs.org` doesn't return all of that kind of information so that can't possibly be available under all circumstances.
- According to [this line](https://github.com/electron/update.electronjs.org/blob/5d6fc08374e14fba84e94dc1c70e1e19cbcbcf53/index.js#L264) the server should return a zip file for mac, does it just not work if a DMG is returned? What if I'm building the zip or dmg with electron-builder vs electron-forge, any differences there?
- According to [these lines](https://github.com/electron/update.electronjs.org/blob/5d6fc08374e14fba84e94dc1c70e1e19cbcbcf53/index.js#L272-L274) it seems like the update for Windows can have whatever extension, which doesn't sound right to me, what's the expected format here?
- According to [this line](https://github.com/electron/update.electronjs.org/blob/5d6fc08374e14fba84e94dc1c70e1e19cbcbcf53/index.js#L280) an exe for Windows should work, but what kind of exe are we taking about, would an NSIS build work? What about portable builds? What about zip files like for mac? And again what if I'm generating this stuff with electron-builder vs electron-forge, any differences/details to be aware of?
- [Here](https://www.electronjs.org/docs/latest/how-to/updates/) it says pretty unequivocally that builds must be code-signed. [Here](https://www.electronjs.org/docs/latest/api/auto-updater/) it only mentions that mac builds should be code-signed. Who's right?
- Also if I'm running an x64 build for mac under rosetta, is it ok to have the server return me an arm64 update?

Basically in order for this to be decently documented there should be a very clear documentation of what the server should return when an update is found and when an update is not found, and what exact builds one must use when using electron-builder and when using electron-forge. 

With the current state of the documentation working with autoUpdater is just awful.

---

I have other issues with autoUpdater too:

- [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows/issues/1469) seems not-maintained anymore, what's the plan here, will Electron transition to something else? Is the built-in updater expected to just stop working at some point?
- [Here](https://www.electronjs.org/docs/latest/api/auto-updater/#windows) it says "make sure you do not try to update your app the first time it runs" which is just _ridiculous_. Obviously that sentence shouldn't be necessary to being with. But also what does that even mean, will the app crash if I try to do that? Will "checkForUpdates" throw an error? Will I get an error somewhere else?
- There seem to be some drama around `electron-builder`, which seems to be purposefully not mentioned in the docs where `electron-forge` is mentioned. IMHO as a user I want to either see that mentioned and considered everywhere electron-forge is mentioned, or I want to see a page saying very clearly why I shouldn't be using electron-builder at all, the current state of the matter is just confusing.
- What about Linux, is there any plan to eventually support (some builds for) it? Is it never going to be supported? Is Linux considered a second-class platform or are there just not enough resources to support it too?

---

Basically the current state of the matter with regards to autoUpdater is pretty awful. Ideally I'd like to see very clear documentation around it, and a sample boilerplate Electron app that just auto-updates using the auto-updater perfectly.

**Comment by fabiospampinato** [comment]
@kevinsawicki on a thread from 5 years ago said:

> on mac it expects a JSON response if their is an update or a 204 response when their is no update. The windows auto updater requests a RELEASES plain text file and then parses that for assets to download and update to.

Jeez what a mess. Who knows what the format of these things is or even if that's up-to-date information.

Some decent documentation on this stuff is really needed.

**Comment by fabiospampinato** [comment]
On another thread from the years ago @anaisbetts said:

> Pro-Tip, anywhere in Squirrel.Windows that you can put a HTTP URL, you can also put just a regular path to a folder. This makes testing updates much much easier, because you can just set your dist folder as the update URL

Which sounds definitely worth mentioning in the docs.

**Comment by fabiospampinato** [comment]
Another tidbit of information from @anaisbetts from the past:

> You can't call checkForUpdates unless you're an installed app

So portable builds aren't self-updatable it seems. Which sounds like a significant limitation.

I wonder now how I should detect from the app if that's a portable build or not.

**Comment by fabiospampinato** [comment]
> I wonder now how I should detect from the app if that's a portable build or not.

To which @anaisbetts on the same thread suggested:

> Call that method and see if it throws :)

Which isn't great 😂

**Comment by fabiospampinato** [comment]
Apparently an alternative to that is:

> The canonical way to detect if you are a Squirrel-installed app if you're not into that is:
> fs.existsSync(path.resolve(path.dirname(process.execPath), '..', 'update.exe'));

Which I guess works only for Squirrel.Windows and not Squirrel.Mac though. Prodding the filesystem isn't great, but I guess it should be fine if it works.

**Comment by fabiospampinato** [comment]
@MarshallOfSound said the following in another random thread:

> Honestly speaking, electron-builder is **not supported** by the Electron maintainers, there is nothing we can do to support that package and electron-builder has actively moved off of tooling that we provide and support. Things like electron-osx-sign, electron-packager and electron-forge are all effectively guaranteed to work with the Latest Electron things like structure changes and new architectures / features, we can't make any guarantees about electron-builder.

> If you want to use electron provided and supported tooling, electron-builder isn't the right path for you.

Even having that copy/pasted in the docs somewhere (especially if the /all endpoint of the docs is revived so that people can actually search and find stuff) would be really valuable I think.

**Comment by fabiospampinato** [comment]
Also things would be much clearer if things like `electron-forge` got moved to the `electron` organization from the `electron-userland` organization, where `electron-builder` resides too.

Also `electron-forge` has been in a weird beta cycle since 2018, if that's the recommended think, and building electron apps is a fundamental thing, it better get out of beta at some point or people are going to be confused about it at best.

**Comment by fabiospampinato** [comment]
Commenting on some things @MarshallOfSound said in another thread:

> I don't personally understand the "losing users to auto update not working" comment because every electron app I've ever worked on uses electrons built in auto updater perfectly fine

I mean it's obvious that there are people using electron-builder, and if that's completely unsupported by the maintainers eventually it may break or transitioning to the built-in autoUpdater may break things.

Also just adopting autoUpdater is not trivial, it requires a server and what that server should do is entirely undocumented, which already makes this not "perfectly fine". Like even the official "update.electronjs.org" to me seems to have a pretty vague asset selection logic, it could potentially instructs applications to download the wrong file just because of how non-precisely it selects it.

Also it seems like Windows apps should hit a different endpoint on the server, that's not documented in the docs, it's not documented in the repo of the official "update.electronjs.org" thing either, who knows what that "RELEASES" format even looks like, the current situation is far from being "perfectly fine" IMO, it's very easy to get this wrong.

> in fact I've only seen and heard stories of that updater being flawed / not being enterprise appropriate / bricking users and making their apps not update. 

Some flaws are even mentioned in the documentation, like the docs say that for some reason if you check for updates the first time the app launches the thing may crash essentially, which I would consider a fairly significant flaw, which wasn't documented from the get go. It would appear more in general that `checkForUpdates` may throw and that's an important thing not mentioned in the docs at all.

I can also see how apps may fail to update just because how undocumented the server is, it's very easy to get this wrong and have the server return an unsupported format to the app, because who knows what the supported formats actually are.

> I believe it's effectively misinformation from builders docs and good SEO for the name "electron builder" that results in people using it. 

As a user of electron-builder I would say that the following factors definitely contributed to having me using electron-builder:

- electron-forge has been in beta since 2018 and electron-builder has 10k+ stars on github, this already pretty heavily pushed me toward electron-builder. Like there's literally a "🚨 🚧 WARNING 🚧 🚨" heading in electron-forge's repo.
- It doesn't/didn't say anywhere in the docs that electron-builder shouldn't be used, or for what reason. As far as the user is concerned both electron-forge and electron-builder are under the same github organization.
- electron-updater, which is meant to be working with electron-builder, doesn't require a server and it's fairly straightforward to make it work because the documentation on it exists and it's written well, compared to the built-in autoUpdater which is largely undocumented.

So I don't think it's just SEO stuff, to the eyes of the users electron-builder+electron-updater are just easier to use.

**Comment by groundwater** [comment]
I am closing and locking this because it's not an acceptable way to use this issue tracker. While there are legitimately good points within, burying those within what is otherwise a long rant is unproductive.

It sounds like the updater story for Electron has been super frustrating, and I agree that sucks. I don't think anyone set out to ruin your or anyone else's day this morning. The folks working on Electron are balancing a lot of competing priorities. 

@fabiospampinato you have some good points within, but we get to set the terms of how you engage on this issue tracker. You are welcome to re-post individual feature-suggestions, or bugs with well-defined repro steps, in the appropriate repositories as long as you can omit the salty commentary.

**Comment by groundwater** [comment]
Migrated to #29943
