### ISSUE TITLE
[Bug]: GetDefaultDownloadDirectory doesn't honour the user-defined Downloads directory

### ISSUE THREAD

**Issue by albertvaka** [electron/electron#29909]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

main

### What operating system are you using?

All OSes.

### What arch are you using?

All archs.

### Last Known Working Electron version

N/A

### Expected Behavior

[`ElectronBrowserClient::GetDefaultDownloadDirectory()`](https://github.com/electron/electron/blob/main/shell/browser/electron_browser_client.cc#L1013-L1019) is hardcoded to return `~/Downloads`. However, this might not be the actual downloads directory path (eg: if the user has changed it or on OSes which translate user directory names).

The proper way to get the current user's downloads directory is OS-dependent:
- On Linux it is set in the env var `$XDG_DOWNLOAD_DIR` 
- On Windows it is returned by [`SHGetKnownFolderPath`](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath) passing in `FOLDERID_Downloads`
- On MacOS it is returned by [`URLForDirectory`](https://developer.apple.com/documentation/foundation/nsfilemanager/1407693-urlfordirectory) passing in `NSDownloadsDirectory`

### Current Behavior

`~/Downloads` is [hardcoded](https://github.com/electron/electron/blob/main/shell/browser/electron_browser_client.cc#L1013-L1019).

**Comment by nornagon** [comment]
Let's copy Chrome here.

Linux: https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/chrome_paths_linux.cc;l=141-143;drc=c14f6f4b9c44fe479a8d004576b42723b2a5feb6
Mac: https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/chrome_paths_mac.mm;l=139-141;drc=ab27aae23a8bc0cb91ed21ee150d8b8862148006
Win: https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/chrome_paths_win.cc;l=71-97;drc=7d43b4b2250aac2829f8fa7eb6603bb299399b13
