### ISSUE TITLE
Playing web-unsupported video codecs

### ISSUE THREAD

**Issue by vjarskee** [electron/electron#29903]
I have read a lot lately, trying to somehow make a video player on Electron, but all the answers were outdated and inoperative, so I would like to know how things are now and if there is a solution

I tried: 
Webchimera.js - Outdated non-working solution, prebuilt version doesn't work, sources won't compile
MPlayer - A working solution if you don't need player control. I need

Perhaps there is a solution to live-decode video using ffmpeg without losing control over playback? I will be glad to suggestions

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
