### ISSUE TITLE
[Bug]: Windows: img src with URL.createObjectURL does not work when launched from a '\\' network share path 

### ISSUE THREAD

**Issue by mmasdivins** [electron/electron#29916]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 20H2

### What arch are you using?

x64

### Expected Behavior

When loading a src img with URL.createObjectURL(blob) in a '\\' network share path the image should show without any problems.

### Actual Behavior

When executing the app from '\\' network share path and we load the src img with URL.createObjectURL(blob) the app crashes with an exit code 3.

### Additional Information

Hi, I'm running into a problem similar to [#12268] (https://github.com/electron/electron/issues/12268) where, when launching the app from a '\\' network share path, when loading and image with the URL. createObjectURL (blob) the app crashes with exit code 3. 

As with the issue [#12268] to reproduce the error, create a shortcut to launch an application directly from the server path (\\SERVERNAME\appdir\appname.exe). If you use the associated drive letter in Windows (e.g. drive letter E:\ being mapped to \\SERVERNAME resulting in E:\appdir\appname.exe) it will work.

I have a webservice from which I request the image, the response is a blob that I load into the src of <img/>, looking at the logs, the blob is the same in '\\' network share and in local, it crashes at the moment that I load the img on 'src'.

**Edit:**
Here I attach the Crashpad zip
[Crashpad.zip](https://github.com/electron/electron/files/6731526/Crashpad.zip)

**Comment by mmasdivins** [comment]
For more information it happens the same if I do the following:
`          var reader = new FileReader();
          reader.readAsDataURL(imgResponse);
`
On the second line.

**Comment by nornagon** [comment]
Please attach a crash dump. You can collect them by adding the following snippet to your main process code, before app.whenReady:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by nornagon** [comment]
See also https://github.com/electron/electron/issues/21029

**Comment by mmasdivins** [comment]
> 
> 
> See also #21029

The workaround proposed in this issue crashes the app when I execute the line **readAsDataURL**, see my [comment ](https://github.com/electron/electron/issues/29916#issuecomment-869584910)


I've uploaded the crash dumps.

**Comment by nornagon** [comment]
Hm, interesting, looks like the crash is due to a bad mojo message:

```
Received bad user message: Non committable URL passed to BlobURLStore::Register
```

The source of that error is [here](https://source.chromium.org/chromium/chromium/src/+/main:storage/browser/blob/blob_url_store_impl.cc;l=82;drc=98f465d27454f40690199ed1c32ab0ce2f8f3230), and [this](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/child_process_security_policy_impl.cc;l=1259-1308;drc=c14f6f4b9c44fe479a8d004576b42723b2a5feb6) is the logic for deciding if a URL is committable.

**Comment by mmasdivins** [comment]
I see, I will take a look into it. On another note how did you do to analyze the crash dumps?

**Comment by nornagon** [comment]
@mmasdivins [electron-minidump](/nornagon/electron-minidump) is how I usually do it! WinDbg is also a good tool, you can find info about loading the Electron symbols into WinDbg [here](https://www.electronjs.org/docs/development/setting-up-symbol-server#using-the-symbol-server-in-windbg)
