### ISSUE TITLE
[Doc] Update ipcMain page with nodeIntegration and contextIsolation

### ISSUE THREAD

**Issue by viking-cat** [electron/electron#29911]
Sorry if this ends up at the wrong place but here is a bit of feedback on the documentation.

**Background**
I ran into issues with ipcMain and could resolve it within a reasonable time but only because I could remember hearing about it from several discussions online. I noticed that the relevant documentation doesn't mention and/or reference these settings in a clear and obvious way. So here is my improvement suggestion:

**Improvement**
Update the ipcMain page with information regarding the following settings:
- nodeIntegration
- contextIsolation

One or both settings are a precondition for that feature (_I am not completely sure on the details_).

I would personally expect the following information:
- Something attention grabbing (_blinking rainbow text?_)
- Introduction to the settings
- When to use them
- Potential issues
- Example on how to change them

Parts of this information could be located on a different "settings" page but I would at least expect some basic information that grabs your attention and introduces you to these preconditions.

document: https://www.electronjs.org/docs/api/ipc-main

**Comment by nornagon** [comment]
hm, I'm not sure exactly what problem you're describing here regarding nodeIntegration and contextIsolation. Those options have no particular relationship to `ipcMain` that I can see—the nodeIntegration and contextIsolation settings affect the _renderer process_ but the `ipcMain` API is a _main process_ API.

I see the example at the top of the ipc-main documentation doesn't mention anything about how to get access to Electron APIs in the renderer process, but that isn't particular to the `ipcRenderer` API, that's true of all Electron APIs and is described (perhaps not that well) in the ["Getting Started" section of the docs](https://www.electronjs.org/docs/latest/get-started/process-model#the-renderer-process) as well as being shown in many examples, including [electron-quick-start](/electron/electron-quick-start).
