### ISSUE TITLE
[Bug]: BLuetooth paired devices are not persistent in browser level for navigator.bluetooth.getDevices()

### ISSUE THREAD

**Issue by bierzorutas** [electron/electron#29910]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

1.-Open electron app.
2.-Pair BLE device with navigator.bluetooth.requestDevice() , etc etc.
3.-Close electron app.
4.-Open electron app.
5.-Navigator.bluetooth.getDevices() should return a list with the paired device in step 2.

### Actual Behavior

1.-Open electron app.
2.-Pair BLE device with navigator.bluetooth.requestDevice() , etc etc.
3.-Close electron app.
4.-Open electron app.
5.-Navigator.bluetooth.getDevices() returns an empty list.

### Additional Information

Navigator.bluetooth.getDevices() works if app remains open, but when app is closed an reopen the Navigator.bluetooth.getDevices() always return empty array.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
