### ISSUE TITLE
[Feature Request]: macOS: Support webpageURL parameter in handoff API

### ISSUE THREAD

**Issue by 1akshat1** [electron/electron#29926]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi,

My team is trying to support universal linking in our application. Currently, in order to receive a handoff event from the browser, the application needs to listen to `continue-activity` event which provides `type` and `userInfo`. As per the Apple documentation [here](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/Handoff/AdoptingHandoff/AdoptingHandoff.html#//apple_ref/doc/uid/TP40014338-CH2-SW10), the browser sends the app an `NSUserActivity` object with an `activityType` value of `NSUserActivityTypeBrowsingWeb`. The `webpageURL` property contains the URL the user was visiting, while the `userInfo` dictionary is empty. 

To provide a smooth handoff our application needs to know the URL the user is navigating from. Therefore, it would be great if the `webpageURL` parameter is exposed in `continue-activity` event. 

### Proposed Solution

The `NSUserActivity` object contains the `webpageURL` property which is set during the handoff process. 
I don't have any experience with Objective C but I believe the `webpageURL` property on the `userActivity` object can be allowed to pass [here](https://github.com/electron/electron/blob/da2baabb96161ea08a15820451f9374d63b4d678/shell/browser/mac/electron_application_delegate.mm#L161) to make it accessible.
https://github.com/electron/electron/blob/da2baabb96161ea08a15820451f9374d63b4d678/shell/browser/mac/electron_application_delegate.mm#L161

### Alternatives Considered

-

### Additional Information

The application needs to know the URL from where the user is navigating to provide a customized handoff experience.

**Comment by nornagon** [comment]
This seems reasonable & fairly straightforward to implement! One challenge here is that the existing API doesn't follow our [API guidelines](https://github.com/electron/governance/blob/master/wg-api/best-practices.md), in particular, it uses positional arguments instead of a "details" object as [recommended](https://github.com/electron/governance/blob/master/wg-api/best-practices.md#how-will-this-api-be-extended-in-the-future). Probably the best way to extend this API is to add a "details" object as a 2nd parameter to the event, and put `webpageURL` inside that details object, to allow for future extension without resorting to a long list of positional arguments.

**Comment by 1akshat1** [comment]
@nornagon Makes sense. This should help add any other properties from `NSUserActivity` that might be needed in the future. I can create a PR for this.

**Comment by RaisinTen** [comment]
The PR opened to resolve this issue, https://github.com/electron/electron/pull/30042, did not use `Fixes: https://github.com/electron/electron/issues/29926` in the description, so this issue didn't get closed automatically when the PR landed. I'm closing this issue now but feel free to let me know if this still needs to stay open.

... and thank you for the contribution @1akshat1! :)
