### ISSUE TITLE
[Bug]: desktopCapturer.getSources does not get Electron

### ISSUE THREAD

**Issue by ghli2** [electron/electron#29931]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] #33833
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0+

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro build 19042.1052

### What arch are you using?

x64

### Last Known Working Electron version

12.0.0-beta1

### Expected Behavior

`desktopCapturer.getSources({ types: ['screen', 'window'], fetchWindowIcons: true });` should return every screen and visible window, including the electron window that ran it.

### Actual Behavior

`desktopCapturer.getSources(...);` Gets other windows, but not the Electron window that ran it.

### Testcase Gist URL

https://gist.github.com/ghli2/1fac4cfeb05db557baf2bd60d9b60899

### Additional Information

It worked fine 11.4.9 and before, as well as 12.0.0-beta1, but not in several versions between 12.0.0-13.1.3 that I've tested

**Comment by nornagon** [comment]
I can't reproduce this.

![image](https://user-images.githubusercontent.com/172800/123713096-86fdbf00-d828-11eb-9c12-b41e56d08ffb.png)

**Comment by phwang4** [comment]
![v12 0 12](https://user-images.githubusercontent.com/36900725/123829360-0393aa80-d8c8-11eb-96eb-2f48df6d69ca.png)
![vLatest](https://user-images.githubusercontent.com/36900725/123829370-055d6e00-d8c8-11eb-9d71-10650654a815.png)

The electron window shows up in v12.0.12 just like with @nornagon but the dev tools aren't showing up.

Also tested with the latest electron build (v13.1.4) and am able to reproduce the error.

**Comment by nornagon** [comment]
Seems to work after reloading the main page, so perhaps this is a timing issue & you're calling `getSources` before the devtools window is open?

![image](https://user-images.githubusercontent.com/172800/123860517-db617700-d8da-11eb-950f-ac11d93cf7e2.png)

**Comment by ghli2** [comment]
Sorry, the devtools window isn't important at all, I've just ran it with the devtools open so much that it didn't even register to me that it wasn't needed in a minimally working error reproduction. The "Screen Picker" window is what I'm concerned with.

Regarding timing, The `getSources` call is in the `DOMContentLoaded` event listener, so the "Screen Picker" window should be there when `getSources` is called.

It looks like you can't reproduce it on 12.0.12 but I could, so maybe it has to do with an external interaction with `getSources`, but I wouldn't have any idea what's causing it or how.

## Has screen picker
![11 4 9](https://user-images.githubusercontent.com/31703918/123980522-39e42f00-d987-11eb-9d1b-4426ad080988.PNG)
![12 0 0-beta1](https://user-images.githubusercontent.com/31703918/123980524-3a7cc580-d987-11eb-97ed-98c6aa95df3c.PNG)

## Does not have screen picker
![13 0 0](https://user-images.githubusercontent.com/31703918/123980557-41a3d380-d987-11eb-95ba-e4d56b64e877.PNG)
![13 1 4](https://user-images.githubusercontent.com/31703918/123980560-41a3d380-d987-11eb-8241-1a7c4d89bda7.PNG)
![12 0 0](https://user-images.githubusercontent.com/31703918/123980562-41a3d380-d987-11eb-899b-83256fe998c6.PNG)
![12 0 2](https://user-images.githubusercontent.com/31703918/123980563-423c6a00-d987-11eb-9a53-490735500be0.PNG)
![12 0 12](https://user-images.githubusercontent.com/31703918/123980564-423c6a00-d987-11eb-9213-f1fbbec86462.PNG)

**Comment by nornagon** [comment]
@ghli2 hm, weird. If you refresh the page does the Electron window show up?

**Comment by VerteDinde** [comment]
@nornagon @ghli2 Digging into what could be causing this, but I can also reproduce on my Windows desktop (Windows 10). However, where it's broken for me is a little bit different - it works consistently for me until `13.0.0-beta.14`, after which I can no longer see the Electron window as a capture source. On E `12.0.12`, it's working as expected.

@ghli2 If it's not too much trouble, could I ask you to try `13.0.0-beta.13` and `13.0.0-beta.14` and see if the former works and the latter does not? That might help narrow down if it's A) a race condition or B) something that broke in our Chrome roll upgrade in beta.14. 🙂 I'll keep digging into the issue on our side

**Comment by ghli2** [comment]
@nornagon It doesn't look like refreshing helps.

@VerteDinde Neither `13.0.0-beta.13` nor `13.0.0-beta.14` work for me.

![13 0 0-beta13](https://user-images.githubusercontent.com/31703918/124017115-f51ebf00-d9ab-11eb-86a5-017f31c92c1f.PNG)
![13 0 0-beta14](https://user-images.githubusercontent.com/31703918/124017113-f4862880-d9ab-11eb-8bfe-fbe27c2b4771.PNG)

**Comment by phwang4** [comment]
It might be a race condition. I tested it again with all the versions @ghli2 tested.

Ran them all 3 or more times with the following results:

worked:
12.0.0.beta.1 (3/3)
11.4.9 (3/3)
12.0.2 (3/6 screenPicker occasionally doesn't appear)
12.0.0 (4/5 didn't work the first time but does afterwards)

didn't work:
13.0.0 (0/3)
13.1.4 (0/3)

**Comment by DanielMcAssey** [comment]
I have started to get this on 18.0.0-beta.5, I havent tried earlier versions of 18, however 17 works fine

**Comment by CliffReimers** [comment]
> I have started to get this on 18.0.0-beta.5, I havent tried earlier versions of 18, however 17 works fine.
> 
> EDIT: To clarify I am on Windows

Seeing this on 18.0.0 as well, on Windows 10.

**Comment by CliffReimers** [comment]
Updated gist with electron 18.0.2: https://gist.github.com/CliffReimers/7644121cdef8a18f79381851359590d7
Does not find Screen Picker window on Windows.

**Comment by samgabriel** [comment]
This is a blocker for an update from 11 for us

**Comment by CliffReimers** [comment]
> This is a blocker for an update from 11 for us

It's a blocker for us as well, but it works fine on 17.x.

**Comment by samgabriel** [comment]
We tried it with Version 17.0.0, 17.1.1, 17.2.0, 17.3.0, 17.4.1, 17.4.2 and trying to capture VSCode always fails to show the window on the list

**Comment by nornagon** [comment]
Hm, possibly relevant: there's a `add_current_process_windows` parameter to NativeDesktopMediaList that we're not currently setting: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/media/webrtc/native_desktop_media_list.h;l=29-31;drc=494bf1e595e8ec1560a1c18c6eb55e9851208dc1

Added by https://source.chromium.org/chromium/chromium/src/+/f507c5362a3058955d21775ae039fbcbd8d69793

**Comment by Akrome** [comment]
> Hm, possibly relevant: there's a `add_current_process_windows` parameter to NativeDesktopMediaList that we're not currently setting: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/media/webrtc/native_desktop_media_list.h;l=29-31;drc=494bf1e595e8ec1560a1c18c6eb55e9851208dc1
> 
> Added by https://source.chromium.org/chromium/chromium/src/+/f507c5362a3058955d21775ae039fbcbd8d69793

I'm upgrading from Electron 15.X to 19.0.3 and my screenshotting is also broken. Even fixing the change when the invocation now has to come from main process instead of rendering, I'm getting an exception when I try to screenshot as per documentation using chromeMediaSource of "desktop" and I think you are right on the money. It's possible the new parameter crashes the interop call. I tried the workaround mentioned by Cliff with chromeMediaSource of "screen" but that doesn't work for me (due to problems with my code, now with the workaround itself).

**Comment by ForesightImaging** [comment]
> We've found a workaround that allows us to record our own electron window by using webContents.getMediaSourceId instead of desktopCapturer.getSources.

this worked for 19.x

**Comment by ProdigyView** [comment]
Any further updates on this?

**Comment by himanshurajora** [comment]
Any updates on this?
