### ISSUE TITLE
[Feature Request]: Use new 'Mica' material for BrowserWindow vibrancy in Windows 11

### ISSUE THREAD

**Issue by MehediH** [electron/electron#29937]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

At the moment, [`setVibrancy()`](https://www.electronjs.org/docs/api/browser-window#winsetvibrancytype-macos) for `BrowserWindow` only supports macOS. Windows 10 has had a similar material called Acrylic, but Electron is yet to add support for it.

### Proposed Solution

With Windows 11, Microsoft is introducing a more performant material dubbed Mica. 

From [Microsoft:](https://docs.microsoft.com/en-us/windows/apps/design/style/mica)

> Mica is an opaque, dynamic material that incorporates theme and desktop wallpaper to paint the background of long-lived windows such as apps and settings. You can apply Mica to your application backdrop to delight users and create visual hierarchy, aiding productivity, by increasing clarity about which window is in focus. Mica is specifically designed for app performance as it only samples the desktop wallpaper once to create its visualization.

The new Mica material is a prominent part of the Windows 11 visual design. Adding support for Mica to `setVibrancy()` in Electron would greatly elevate the design of many apps, and enable the visual look of Electron apps to be in line with modern Windows experiences. 

### Alternatives Considered

The following libraries currently allow apps to use Acrylic as an alternative to `vibrancy` in Windows 10:

* https://github.com/Seo-Rii/electron-acrylic-window
* https://github.com/AryToNeX/Glasstron

### Additional Information

N/A

**Comment by paulobrien** [comment]
Good plan, it definitely makes a lot of sense to support this in Electron natively.

**Comment by codebytere** [comment]
Interesting! i can try to poke into this if i have some time :)

**Comment by codebytere** [comment]
hey folks - put up a PR to get this added into Electron.

**Comment by MehediH** [comment]
hi @codebytere, this is amazing -- thank you so much! After having a quick look over the code for the PR, it seems this is adding Acrylic support for vibrancy. 

Can we expect Mica support in the future? Having an option to choose between Acrylic and Mica for vibrancy would be ideal. I am not sure if Microsoft even provides the APIs for implementing Mica on Win32 apps yet, so I understand if it's simply not possible to add Mica support yet :)

**Comment by itsme-alan** [comment]
Mica for long lived surfaces and Acrylic for short lived surfaces is how Microsoft's documentation recommends to use them.

**Comment by codebytere** [comment]
@MehediH yeah that's the constraint for now sadly - Mica isn't yet available for Win32 apps yet! Once it becomes possible i'd plan to update that codepath to take it into account and allow you all to select it :)

**Comment by MehediH** [comment]
@codebytere Understood. Thank you for the work on this!!

**Comment by riverar** [comment]
I wrote those Acrylic hacks; they are not supported by Microsoft and introduce a number of problems. DO NOT use them in mainline Electron.

Mica _should_ get supported APIs soon. Perhaps as part of that effort, the Acrylic path will get documented. (I'm connected to the team and will continue to be a very loud squeaky wheel.)

**Comment by thomassth** [comment]
I think the latest MS edge uses Mica already, so electron should be able to tap into the same API?

**Comment by XFaonAE** [comment]
I was able to make mica myself in electron with vuejs

You can also do this fairly easily,

First, in the main process, get the desktop wallpaper `i used "wallpaper" from npm for this` and send it to the renderer
Next from the renderer make this setup:
```html
<div class="wrapper">
    <img src="your desktop wallpaper" class="mica-source" />
</div>
```

Now with js, set the src to the desktop wallpaper.

Next add events in the main process and pass all of this info to the renderer
```js
{
    displayWidth: ...,
    displayHeight: ...,
    windowPosLeft: ...,
    windowPosTop: : ...,
}
```

Now, set margin top of the img to windowPosTop and the margin-left to windowPosLeft, you also need to set width and height of the img to displayWidth and displayHeight
 finaly, set overflow hidden to the div and set a width and height;

**Dont forget to blur the img to 100px and opacity to 0.2 with css**

**IMPORTANT NOTICE** Make sure the img's margin-top and margin-left are updated when the window is moved via events

**EXAMPLES** (this is from my framework)
![My Framework Running Mica](https://github.com/XFaonAE/test/blob/master/axeri-xfaon.png?raw=true)

I just hope one day electron will support window snap so I can have that supported in my titlebar

**Comment by XFaonAE** [comment]
> API available with `dwmapi.dll` for win32.
> 
> ```
> enum DWMWINDOWATTRIBUTE
> {
>     DWMWA_MICA_EFFECT = 1029
> };
> 
> enum DWM_MICA_PREFERENCE
> {
>     DWMWCP_FALSE = 0,
>     DWMWCP_TRUE = 1
> };
> 
> DWM_MICA_PREFERENCE preference = DWMWCP_TRUE;
> DwmSetWindowAttribute(hWnd, DWMWA_MICA_EFFECT, &preference, sizeof(preference));
> ```
> 
> Just not documented and define in `dwmapi.h`.

Where exacly is this code supposed to go? Isn't electron JS?

**Comment by supertiger1234** [comment]
Could someone make an electron lib for now?

**Comment by Brouilles** [comment]
The `dwmapi.dll` workaround don't work anymore on latest Windows 11 build. So no solution.

**Comment by Brouilles** [comment]
New DWMWA_SYSTEMBACKDROP_TYPE in 22523 SDK, public Win32 API for Mica.
Also for Acrylic.

**Comment by Brouilles** [comment]
@mitchchn Can you share the code of your native module?

**Comment by alexmercerind** [comment]
> @mitchchn Can you share the code of your native module?

@Brouilles, I don't know if this will be helpful but I assume very same process will be done for Node / electron.js.

https://github.com/alexmercerind/flutter_acrylic/blob/f0aebf9b49d412bd050cf1ca136137b21feba61c/windows/flutter_acrylic_plugin.cpp#L181-L251

I had made library for Flutter...I handled mica for both older & newer (DWMWA_SYSTEMBACKDROP_TYPE) WIndows 11 builds.

Setting negative `MARGINS` with `DwmExtendFrameIntoClientArea` did the trick for me. It allowed mica to fill whole client area of the window. `WS_EX_NOREDIRECTIONBITMAP` was removing window content completely. 

![](https://github.com/alexmercerind/flutter_acrylic/raw/assets/mug8J4efWu.gif?raw=true)

**Comment by Brouilles** [comment]
![image](https://user-images.githubusercontent.com/1573282/171946253-2a9c6a90-a5db-4377-a18f-89ee50195108.png)

I am working on a package. Mica for ElectronJS. Because it apparently not planned to be added soon in the main Electron project.

**Comment by XFaonAE** [comment]
> ![image](https://user-images.githubusercontent.com/1573282/171946253-2a9c6a90-a5db-4377-a18f-89ee50195108.png)
> 
> I am working on a package. Mica for ElectronJS. Because it apparently not planned to be added soon in the main Electron project.

wow, thats impressive, wish u luck mate! also u might as well recommend users to remove the menubar and the default titlebar, clearly it would be better to write their own yk

**Comment by sudo-carson** [comment]
I was able to get Mica/Acrylic working in an Electron fork but I ran into a few issues.

- Electron disables resizing and maximizing for windows with `transparent: true`, which is required for acrylic effects to work.
- `titleBarStyle: hidden` breaks acrylic effects. I'm not sure how exactly Electron hides the titlebar in a way that breaks it, but I've gotten Mica working with hidden titlebars in another project using these window styles:
  - `style = WS_CLIPSIBLINGS | WS_CLIPCHILDREN | WS_SYSMENU | WS_SIZEBOX | WS_MAXIMIZEBOX | WS_MINIMIZEBOX | WS_VISIBLE`
  - `style_ex = WS_EX_WINDOWEDGE`

**Comment by sylveon** [comment]
transparent: true is not required for the effects to work. In my experience, simply not setting a background color to the web page and ensuring every element on top does not use a non transparent color is sufficient. Not using transparent: true also allows window snapping and shadows to keep working.

**Comment by sudo-carson** [comment]
> transparent: true is not required for the effects to work. In my experience, simply not setting a background color to the web page and ensuring every element on top does not use a non transparent color is sufficient. Not using transparent: true also allows window snapping and shadows to keep working.

Sure enough, setting `backgroundColor: '#00000000'` in JS and `background: unset !important` for `<html>` and `<body>` gave me a resizable window!

![image](https://user-images.githubusercontent.com/61946759/180585252-f8e9b586-749f-4929-83a3-383aef2a4d6a.png)

Though the titlebar is missing (even with `titleBarStyle: 'default'`), the window cannot be moved with `-webkit-app-region: drag`, there is a ~6px space of nothing at the top of the window, and any titleBarStyle other than `default` breaks it completely:
![image](https://user-images.githubusercontent.com/61946759/180585546-95336929-9a37-4f07-b6b3-93ed429204ef.png)

**Comment by KorbsStudio** [comment]
Sadly, Glasstron has been discontinued recently by it's developer, I'm trying to maintain it now.
However, the they never got around to adding Mica support. So that I need to look into myself.

**Comment by aleversn** [comment]
Thank you for your email. I've received your message. If your message requires a reply, I will sooner get in touch with you. Best RegardsPeichao LaiFuzhou University

**Comment by GregVido** [comment]
if you are using windows 11, you can use https://www.npmjs.com/package/mica-electron ;)

**Comment by KorbsStudio** [comment]
> if you are using windows 11, you can use https://www.npmjs.com/package/mica-electron ;)

I tried this, didn't work out sadly.
Could be a strange issue with my end, unsure.

**Comment by GregVido** [comment]
what is your windows 11 version ?

**Comment by KorbsStudio** [comment]
> what is your windows 11 version ?

21H2

**Comment by GregVido** [comment]
> > what is your windows 11 version ?
> 
> 21H2

And if you update windows to 22h2 and try with last version of mica electron, no work too ?

**Comment by Cuppachino** [comment]
> 

I'm on 22H2 and the package doesn't work for me unfortunately.

**Comment by aleversn** [comment]
Thank you for your email. I've received your message. If your message requires a reply, I will sooner get in touch with you. Best RegardsPeichao LaiFuzhou University

**Comment by Stanzilla** [comment]
> I was able to get Mica/Acrylic working in an Electron fork but I ran into a few issues.
> 
> * `titleBarStyle: hidden` breaks acrylic effects. I'm not sure how exactly Electron hides the titlebar in a way that breaks it, but I've gotten Mica working with hidden titlebars in another project using these window styles:
>   

That's the bummer here, any way to get mica to work with a hidden title bar?

**Comment by d-o0o-b** [comment]
![image](https://github.com/electron/electron/assets/83477674/287555ba-169e-42e2-aea0-c928603d2f98)
It might be help you!
