### ISSUE TITLE
[Bug]: PLEASE let us suppress the NAGGING pop-up screen on any login

### ISSUE THREAD

**Issue by herop** [electron/electron#29940]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.9

### What operating system are you using?

Other Linux

### Operating System Version

Operating System: Garuda Linux KDE Plasma Version: 5.22.2 KDE Frameworks Version: 5.83.0 Qt Version: 5.15.2 Kernel Version: 5.12.12-arch1-1-surface (64-bit) Graphics Platform: X11 Processors: 8 × Intel® Core™ i7-8650U CPU @ 1.90GHz Memory: 15.6 GiB of RAM Graphics Processor: Mesa Intel® UHD Graphics 620

### What arch are you using?

x64

### Last Known Working Electron version

n.a.

### Expected Behavior

NOT appaering.

[![Electron-Nag-Screen](https://user-images.githubusercontent.com/658323/123801407-c89a7280-d8d9-11eb-8a9f-87ea388b268d.png)](url)

### Actual Behavior

Please help me prevent this.
And yes, I looked up solutions thoroughly.

[![Electron-Nag-Screen](https://user-images.githubusercontent.com/658323/123801407-c89a7280-d8d9-11eb-8a9f-87ea388b268d.png)](url)

Thank you very much in advance,
Jochen

### Additional Information

That happened with:
1. Arco-Linux Gnome, from one V of electron for month'
2. Garuda-Linux Gnome (likewise)
3. Garuda-Linux (see desc. above) starting today

**Comment by VerteDinde** [comment]
Hey @herop, thanks for reporting this and using Electron!

From your initial description, I'm not really sure what your error is or what you're trying to do here. Are you saying that these windows appear when you're trying to open other Electron apps? Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue, or include a video of you experiencing the problem?

Stand-alone test cases or videos make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-info label for this reason. After you make a test case or video showing us the issue, please link to it in a followup comment.

Thanks!

**Comment by herop** [comment]
Thank you very much for your reply.
After each and any login, this window just pops up.
And this without any call or interaction from my side.
It just appears and I need to close it.

**Comment by nornagon** [comment]
This is a distro or setup issue; Electron does not decide to launch itself. There's no action for us to take here, so I'm closing this issue. This should be raised with the distro.
