### ISSUE TITLE
[Bug]: Record full screen apps with electron is not possible

### ISSUE THREAD

**Issue by hagaiovadia** [electron/electron#29965]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.6

### What operating system are you using?

macOS

### Operating System Version

 macOS Mojave, macOS Catalina 10.15.7, macOS Big Sur

### What arch are you using?

x64

### Expected Behavior

The app will record all the screens.

### Actual Behavior

Hi all,
I'm trying to record the screen on macOs.
I have the following issue:
1. My terminal is on Full screen mode in mac
2. I open the screen recorder application I wrote in electron
3. Only the terminal is being recorded but not other windows that I swipe to them in my mac, while Im recording.

I have used the following code in main process:
```
let mainWindow: BrowserWindow | null = null;
const mainWindowSetting = {
    visibleOnFullScreen: true,
    show: false,
    width,
    height,
    fullscreen: platform === 'win32',
    transparent: true,
    useContentSize: true,
    frame: false,
    alwaysOnTop: true,
    hasShadow: false,
    resizable: false,
    movable: false,
    minimizable: false,
    icon: getAssetPath('icon.png'),
    webPreferences: {
      nodeIntegration: true,
      enableRemoteModule: true,
      contextIsolation: false,
    },
  };
mainWindow = new BrowserWindow(mainWindowSetting);
  mainWindow?.setAlwaysOnTop(true, "floating", 1);
  mainWindow?.setVisibleOnAllWorkspaces(true, {visibleOnFullScreen: true});
  mainWindow?.setFullScreenable(false);
  mainWindow?.maximize();
  ```

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by linkvxl** [comment]
@hagaiovadia 最后怎么样了

**Comment by hagaiovadia** [comment]
@linkvxl @codebytere 
It was an issue on my code base, not related to electron specific.
I tried to capture a window instead of a screen, so changing this code, ```types: ['window', 'screen']```  to ```types: ['screen']``` fixed the issue.
old code:
```
    const options = { types: ['window', 'screen'] };
    const sources = await desktopCapturer.getSources(options);
    // getting source with ID in options
    const fullScreenSource = sources[0];
```

new code:
```
    const options = { types: ['window', 'screen'] };
    const sources = await desktopCapturer.getSources(options);
    // getting source with ID in options
    const fullScreenSource = sources[0];
 ```
