### ISSUE TITLE
[Bug]: Symbol not found with RTCDispatcher

### ISSUE THREAD

**Issue by liandne** [electron/electron#29975]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.12

### What operating system are you using?

macOS

### Operating System Version

Catalina 10.15.7

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

4

### Expected Behavior

Can load my `.node` file  and get it work.

### Actual Behavior

Unable to load preload script: /Users/liandne/Documents/dev/demo/main/preload/index.js
(anonymous) @ electron/js2c/renderer_init.js:93
electron/js2c/renderer_init.js:93 Error: dlopen(/Users/liandne/Documents/dev/master/build/osx/electron/lib/Debug/electron-sdk.node, 1): Symbol not found: _OBJC_CLASS_$_RTCDispatcher
  Referenced from: /Users/liandne/Documents/dev/master/build/osx/electron/lib/Debug/electron-sdk.node
  Expected in: flat namespace
 in /Users/liandne/Documents/dev/master/build/osx/electron/lib/Debug/electron-sdk.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5)
    at Module.load (internal/modules/cjs/loader.js:935)
    at Module._load (internal/modules/cjs/loader.js:776)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:33)
    at Module.require (internal/modules/cjs/loader.js:959)
    at require (internal/modules/cjs/helpers.js:88)
    at Object.<anonymous> (/Users/liandne/Documents/dev/demo/main/preload/sdk/index.js:4)

### Additional Information

My sdk was a wrapper of webrtc , and it has not import `RTCDispatcher.h/mm` file.
When i import `RTCDispatcher.h/mm` to build it , it got more ERROR such like "xxxx has been defined in both A and B".
And the interesting thing is, when I switch version from 12 to 4 , it just works.

**Comment by nornagon** [comment]
We don't export the `_RTCDispatcher` symbols. Broadly, we only export v8, libuv and nodejs symbols. This is working as intended.
