### ISSUE TITLE
webSecurity: false doesn't allow access to cross-origin child windows

### ISSUE THREAD

**Issue by nornagon** [electron/electron#29970]
Test Fiddle: https://gist.github.com/10465071dd6fcd731eabfcc4608ff87a

#### Expected behavior:

With `webSecurity: false`, `nativeWindowOpen: true` and `--disable-site-isolation-trials`, this should work:

```js
const child = window.open('http://example.com')
// ... wait for child to load ...
console.log(child.location.href) // should be able to access properties of the child window
```

#### Actual behavior:

Attempting to access the child window throws:
```
Blocked a frame with origin "file://" from accessing a cross-origin frame
```

This behavior doesn't seem to have changed since 4.x, so it's not a regression.

**Comment by belerweb** [comment]
any progress?

**Comment by SuperKirik** [comment]
Hey, any progress?

**Comment by SantiiRepair** [comment]
Yo any progress?
