### ISSUE TITLE
[Bug]: electron upgrade from 10.4.7 to 12.0.7，preload js cannot read other script(Vue) of HTML 

### ISSUE THREAD

**Issue by aaaaaajie** [electron/electron#29977]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

macOS

### Operating System Version

11.2.1

### What arch are you using?

x64

### Last Known Working Electron version

10.4.7

### Expected Behavior

preload script can read html import other script.
For example: 
    html `<script src="../../node_modules/vue/dist/vue.min.js"></script>`
    preload.js `new Vue()`

### Actual Behavior

preload.js throw error: vue is not define

### Additional Information

main.js
```js
const win = new BrowserWindow({
                title: "title",
                width: 800,
                height: 500,
                center: true,
                webPreferences: {
                    plugins: true,
                    preload: path.join(__dirname, "/preload.js"),
                    scrollBounce: true,
                    enableRemoteModule: true,
                    nodeIntegration: true
                }
            });
            win.loadFile(path.join(__dirname, "/index.html"));
```
index.html
```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../resources/app.css">
    <script src="../../node_modules/vue/dist/vue.min.js"></script>
    <script type="text/javascript">
        console.log(111)
        console.log(Vue)
        console.log(222)
    </script>
</head>

<body>
    <div class="vue-app">
        <div class="need-restart-banner" v-if="isNeedRestart">
            <span v-html="i18n.__('preferences.restartText')">您修改的需要<code>重启</code>才能生效</span>
        </div>
    </div>
 </body>
```

preload.js  throw error: Vue is not define
```js
window.onload = function () {
    console.log(Vue)  // Vue is not define
    new Vue({
        el: '.vue-app',
        data: {
            searchText: '',
            navMap: navMap,
            navList: navList,
            i18n: i18n,
            navData: {
                private: {
                    enable: preferences && preferences.defaultLoadUrlEnable || true,
                    url: preferences.defaultLoadUrl
                },
                hotkey: {
                    app: Hotkey.getShowHideMainWindowKey(),
                    // screenCapture: common.mHotkey.getScreenCapture()
                }
            },
            hotkeyPlaceholder: {
                text: 'Type shortcut',
                key: '',
                value: ''
            },
            isNeedRestart: operational.isNeedRestart
        },
        methods: {
         ......
        }
   }
```

**Comment by dsanders11** [comment]
I believe this is the correct behavior. The documentation regarding the preload script says: "Specifies a script that will be loaded before other scripts run in the page." I believe it's expected that the preload script would run before the scripts in your `index.html`, which is why `Vue` is not defined.

**Comment by aaaaaajie** [comment]
> I believe this is the correct behavior. The documentation regarding the preload script says: "Specifies a script that will be loaded before other scripts run in the page." I believe it's expected that the preload script would run before the scripts in your `index.html`, which is why `Vue` is not defined.
Thank you. If so, I have a few other questions based on this question:

1.  In the version before Electron 12, my above behavior can run normally, then why can't I do it later? Is this behavior prohibited after upgrade?

2. The window object in Preload is accessible and entered in the window.onload function, indicating that Preload can access elements in HTML

My understanding of the steps should be:
1. Create a window, preload preload.js, but window.onload is not running
2. Load the HTML
3. Introduce and run the Vue script
4. Run the window.onload function of preload.js
The VUE should already be loaded at this point, because the window.onload event is executed after the VUE script is loaded

Looking forward to your reply, thank you!

**Comment by dsanders11** [comment]
@aaaaaajie, apologies, I didn't notice the `window.onload` in your example.

You are probably running into [context isolation](https://www.electronjs.org/docs/tutorial/context-isolation) which was [enabled by default in v12](https://www.electronjs.org/docs/breaking-changes#default-changed-contextisolation-defaults-to-true). There are some examples in the docs on how you might rewrite your code to work with context isolation using `contextBridge`. You could also set `webPreferences.contextIsolation` to `false` for the `BrowserWindow` to restore the original behavior (not recommended)

**Comment by aaaaaajie** [comment]
Thank you very much for your answer, it is very useful for me, great, I will carefully read the content related to this parameter

**Comment by aaaaaajie** [comment]
MacOS is successful by setting contextisolation = true, but this problem still occurs in Windows 10. Is it necessary to configure different platforms for different platforms?

**Comment by aaaaaajie** [comment]
> @aaaaaajie, apologies, I didn't notice the `window.onload` in your example.
> 
> You are probably running into [context isolation](https://www.electronjs.org/docs/tutorial/context-isolation) which was [enabled by default in v12](https://www.electronjs.org/docs/breaking-changes#default-changed-contextisolation-defaults-to-true). There are some examples in the docs on how you might rewrite your code to work with context isolation using `contextBridge`. You could also set `webPreferences.contextIsolation` to `false` for the `BrowserWindow` to restore the original behavior (not recommended)

MacOS is successful by setting contextisolation = true, but this problem still occurs in Windows 10. I have read the relevant documents and tried to use some parameters, but it still hasn't been solved. Is it necessary to configure additional parameters for inconsistent platforms?
