### ISSUE TITLE
Electron Icon changed while build

### ISSUE THREAD

**Issue by zeankundev** [electron/electron#29999]
I was trying to make a video editor with an icon like this and exported it as an ico.
<img src="https://user-images.githubusercontent.com/58360911/124355090-a5552780-dc39-11eb-81b2-fea7eb15760c.png" width="35">
And when I ran `npm start`, it ran perfectly with the icon.
But suddenly when I try to run `npm run build` and the build was succesful, somehow the icon changed like this.
![image](https://user-images.githubusercontent.com/58360911/124355113-c6b61380-dc39-11eb-860c-7d3dd7036d7c.png)
Anyone know how to do this?

**Comment by kkanekii** [comment]
can I get code for the logo part? I'll help you out

**Comment by zeankundev** [comment]
Sure but the project hasn‘t any repo here. It is just local file

**Comment by kkanekii** [comment]
Mhm copy pasta the logo code

**Comment by zeankundev** [comment]
I will send the code via email

**Comment by kkanekii** [comment]
nay, let it be

**Comment by zeankundev** [comment]
I finally know it! Now it is fixed!

**Comment by kkanekii** [comment]
great!
