### ISSUE TITLE
[Bug]: The webContent can not focus properly and the input does not work properly after calling print()

### ISSUE THREAD

**Issue by whaoa** [electron/electron#29998]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 2004 (19041.985)

### What arch are you using?

x64

### Last Known Working Electron version

11.4.9

### Expected Behavior

Call `window.print()` in the render process, and after closing the print window, the page regains focus and all elements work fine.

### Actual Behavior

When I call `window.print()` in the render process, it triggers the `blur` event of the `window`, but the `window` does not trigger the `focus` event when the print window is closed, which causes the `input` element in my page to not `focus`. When I try to switch the window so that the application loses focus and then switch it back, the `input` element works fine.

### Additional Information

I tried to listen for `blur` and `focus` events in `BrowserWindow`, unlike the render process they are both triggered normally, then I tried to call `webContent.focus()`in the `focus` callback of the `BrowserWindow`, but it still doesn't work. 

After trying I found that this problem started after version 12 and is still present in the latest version 13.1.4.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by whaoa** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance! Your help is appreciated.

Thanks for your reply, I reproduced the problem with electron-fiddle using version 12.0.0, here is the gist of the relevant code: 
[Github Gist](https://gist.github.com/whaoa/020b02d54cffcac8d1c2d9764a6218b8).

**Comment by stevenfuhr** [comment]
Possibly related to #19977

**Comment by pushkin-** [comment]
seems to repro in v22

**Comment by pushkin-** [comment]
bump
