### ISSUE TITLE
[Bug]: Load http image in webview that has https content(url) loaded

### ISSUE THREAD

**Issue by mehtaVishwa1996** [electron/electron#29992]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

2

### Expected Behavior

I want to load an http image over https url in webview.

### Actual Behavior

When I am trying to load an http image in webview that has a https url loaded, it throws me following error

Mixed Content: The page at 'https://www.zygal.io/ (url hosted on https)' was loaded over HTTPS, but requested an insecure element 'http://49.248.73.8:41402/... (some image hosted on http)'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

I have all options set on my webview tag as follows -
`<webview src="https://www.zygal.io/" webpreferences="contextIsolation=false, webSecurity=false, allowRunningInsecureContent, allowDisplayingInsecureContent" nodeintegration enableremotemodule disableWebSecurity></webview>`

Also have set options while calling browserWindow as follows - 
```
new BrowserWindow({
		webPreferences: {
			devTools: true,
			nodeIntegration: true,
  			contextIsolation: false,
                       enableRemoteModule: true,
                       webviewTag: true,
                       webSecurity: false,
                       allowRunningInsecureContent: true,
                       allowDisplayingInsecureContent: true
		}
	});
```

**Comment by VerteDinde** [comment]
Hey @mehtaVishwa1996, thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks so much!

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
