### ISSUE TITLE
[Bug]: setWindowOpenHandler error

### ISSUE THREAD

**Issue by dachuanhouhou** [electron/electron#30017]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.3

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

ia32

### Expected Behavior
```
//this is webview config

let webviewAttributes = {
        webpreferences: "contextIsolation=false, nativeWindowOpen=true", 
        enableblinkfeatures: "PasswordReveal",
        plugins: true,
        enableremotemodule: true,
        nodeintegration: false, 
        allowpopups: true,
        customExtra: params,
        disablewebsecurity: true,
        // partition: 'persist:ppb',
        preload: file://${app.dPath}/render-webview.js,
};

//this is listener:
newTab.webview.addEventListener("dom-ready", (event) => {
        let webContentsId = newTab.webview.getWebContentsId();
        if (webContentsId && ALLOWPOPUPS_SYSTEM.includes(params.url)) {
          const newTabWebContents = webContents.fromId(webContentsId);
          newTabWebContents.setWindowOpenHandler((WOH)=>{
            return {action: "allow"};//now window not open
          });
        }
}
```

### Actual Behavior

console:The window open handler response must be an object, but was instead of type 'undefined'.

**Comment by dachuanhouhou** [comment]
Can anyone help？

**Comment by aaaaaajie** [comment]
> Can anyone help？

I don't have the answer, but I recommend you format your code so that people can read it quickly and help you

**Comment by dachuanhouhou** [comment]
> > Can anyone help？
> 
> I don't have the answer, but I recommend you format your code so that people can read it quickly and help you

sorry!I have formatted the code。

**Comment by nornagon** [comment]
> The window open handler response must be an object, but was instead of type 'undefined'.

This means that the function given to `setWindowOpenHandler` is written incorrectly. It must always return an object. This is not a bug in Electron; it's a bug in your app.

**Comment by dachuanhouhou** [comment]
> > The window open handler response must be an object, but was instead of type 'undefined'.
> 
> This means that the function given to `setWindowOpenHandler` is written incorrectly. It must always return an object. This is not a bug in Electron; it's a bug in your app.
### I have return an object. the error still exists.
newTabWebContents.setWindowOpenHandler((WOH)=>{
    return {action: "allow"};//now window not open
});
```

**Comment by nornagon** [comment]
Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by lzdyes** [comment]
very amazing!

i checked source code:
```ts
WebContents.prototype.setWindowOpenHandler = function (handler: (details: Electron.HandlerDetails) => ({action: 'allow'} | {action: 'deny', overrideBrowserWindowOptions?: BrowserWindowConstructorOptions})) {
  this._windowOpenHandler = handler;
};

WebContents.prototype._callWindowOpenHandler = function (event: Electron.Event, details: Electron.HandlerDetails): BrowserWindowConstructorOptions | null {
  if (!this._windowOpenHandler) {
    return null;
  }
  const response = this._windowOpenHandler(details);

  if (typeof response !== 'object') {
    event.preventDefault();
    console.error(`The window open handler response must be an object, but was instead of type '${typeof response}'.`);
    return null;
  }

  if (response === null) {
    event.preventDefault();
    console.error('The window open handler response must be an object, but was instead null.');
    return null;
  }

  if (response.action === 'deny') {
    event.preventDefault();
    return null;
  } else if (response.action === 'allow') {
    if (typeof response.overrideBrowserWindowOptions === 'object' && response.overrideBrowserWindowOptions !== null) {
      return response.overrideBrowserWindowOptions;
    } else {
      return {};
    }
  } else {
    event.preventDefault();
    console.error('The window open handler response must be an object with an \'action\' property of \'allow\' or \'deny\'.');
    return null;
  }
};
```

That looks right.

But when I try setWindowOpenHandler:
```ts
this.webContents.setWindowOpenHandler(({ url, referrer, postBody }) => {
  return { action: 'deny' };
  // return { action: 'allow' };
  // return {};
  // return null;
  // return;
});
```
all return console log
```
The window open handler response must be an object, but was instead of type 'undefined'.
```
This is very strange

**Comment by freeloopmko687** [comment]
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance! Your help is appreciated.
### this is demo link
https://gist.github.com/dachuanhouhou/37055f48d16c97dc4e6f47b241a8898f

**Comment by dachuanhouhou** [comment]
> > Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> > Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> > I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.
> > Thanks in advance! Your help is appreciated.
> 
> ### this is demo link
> https://gist.github.com/dachuanhouhou/37055f48d16c97dc4e6f47b241a8898f

This is also my account

**Comment by nornagon** [comment]
This looks like a problem with `remote`, which is [no longer supported](https://github.com/electron/electron/issues/21408). I'd recommend moving that logic to the main process.

**Comment by seefl** [comment]
// window.open The release build environment gets null
 window.open('https://github.com','github')
 
win.webContents.setWindowOpenHandler(({ url,frameName }) => {
    log.info(frameName)  // The parameter is equal to''
    if(frameName == ’github‘){
     // Don't go here, why
      return {
        action: "allow",
        overrideBrowserWindowOptions: {
          module:true,
          width,
          height,
        },
      };
    }else {  
    // 打开浏览器
      shell.openExternal(url);
    }
    return { action: 'deny' }
  });
