### ISSUE TITLE
How do I continue debugging Electron after using app.relaunch()？

### ISSUE THREAD

**Issue by aaaaaajie** [electron/electron#30018]
```js
app.relaunch();
app.exit();
```
Debug console disconnected. Is there a way to continue debugging the main process？Trouble you 😊

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by aaaaaajie** [comment]
> Thanks for reaching out!
> 
> The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.
> 
> I hope this helps!

ok,I'm trying
