### ISSUE TITLE
[Bug]: Windows 7 frame is shown on load with frame: false and resizable: false

### ISSUE THREAD

**Issue by facuparedes** [electron/electron#30024]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Windows

### Operating System Version

Windows 11 build 22000.51

### What arch are you using?

x64

### Expected Behavior

Show just a white (or a custom background color) window. Like this initial screen:

![image](https://user-images.githubusercontent.com/25681464/124545625-c5364800-ddff-11eb-9cf1-ae8c7635adeb.png)

The screenshot was taken without **frame: false** and **resizable: false**:
```
const { app, BrowserWindow } = require('electron');

function createWindow () {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
  });

  win.loadFile('index.html')
}

app.whenReady().then(() => {
  createWindow();
})

app.on('window-all-closed', function () {
  app.quit()
})
```

### Actual Behavior

Windows 7 style frame is shown for a second when I create a BrowserWindow with **frame: false** and **resizable: false**

![image](https://user-images.githubusercontent.com/25681464/124544355-5657ef80-ddfd-11eb-99b2-524d2c37e33f.png)

### Testcase Gist URL

https://gist.github.com/facuparedes/97e6238ce8d5e132a0f03b4de3eb84a0

### Additional Information

Maybe related to #30022

I found on Google a post made on 2019/04/11 about the issue: https://discuss.atom.io/t/windows-7-frame-is-shown-on-load-win-10/64339

However, that forum was deleted, so we can't see the full page. We can only see this: https://webcache.googleusercontent.com/search?q=cache:wB91NYnTYAIJ:https://discuss.atom.io/t/windows-7-frame-is-shown-on-load-win-10/64339+&cd=1&hl=en&ct=clnk&gl=ca

_(Extracted from that URL)_

> When frame is set to false, an old windows native frame is shown just before app is loaded.
> 
> ![image](https://user-images.githubusercontent.com/25681464/124544825-442a8100-ddfe-11eb-86eb-039c300765a3.png)

A workaround: set **resizable: true** _(or remove it)_ and then change that with **setResizable()**. Like this:
```
const { app, BrowserWindow } = require('electron');

function createWindow () {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    frame: false,
  });

  win.setResizable(false);
  win.loadFile('index.html')
}

app.whenReady().then(() => {
  createWindow();
})

app.on('window-all-closed', function () {
  app.quit()
})
```

_Note at the **win.setResizable(false);** line._

Although this workaround fixes this issue, #30022 persists.

**Comment by geroale** [comment]
Same issue here

**Comment by snaildos** [comment]
Any progress?

**Comment by snaildos** [comment]
Seems that v16.0.5 fixed the issue for me.

**Comment by snaildos** [comment]
Update: it hasnt.

**Comment by Fabio286** [comment]
I know, it's ugly but the only workaround (i hope temporary) i found that works in my case to hide this bug is call `windows.minimize()` just after instantiate `BrowserWindow` and `mainWindow.focus()` after window creation.

```js
const isWindows = process.platform === 'win32';

async function createMainWindow () {
   const window = new BrowserWindow({
      width: 800,
      height: 600,
      frame: false
   });

   if (isWindows) 
      window.minimize();

   // ...

   return window;
}

// ...

app.on('ready', async () => {
  mainWindow = await createMainWindow();

  if (isWindows)
     mainWindow.focus();
});
```

**Comment by gpetrov** [comment]
This is really annoying bug, it happens also on child windows with just `frame: false`
Two workarounds exists indeed - either setting transparency: true or delaying the show till the window is ready to show.

The problem with those workarounds is that they introduce a delay of 200-400ms to the user, so when he clicks on a button to show a popups - for a while nothing happens ... and then suddenly the new windows is visible. So this is really a bad UX.

Btw this also happens in the latest Electron 18

Please @codebytere or @VerteDinde address this issue.

**Comment by rzhao271** [comment]
My PR likely doesn't fix this issue considering this issue has been there since 13-x-y, whereas #30760 was introduced in 14-x-y.
