### ISSUE TITLE
[Bug]: Transparent window and shadow is shown on load with frame: false

### ISSUE THREAD

**Issue by facuparedes** [electron/electron#30022]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Windows

### Operating System Version

Windows 11 build 22000.51

### What arch are you using?

x64

### Expected Behavior

Show just a white (or a custom background color) window. Like this initial screen:

![image](https://user-images.githubusercontent.com/25681464/124545625-c5364800-ddff-11eb-9cf1-ae8c7635adeb.png)

The screenshot was taken without **frame: false**:
```
const { app, BrowserWindow } = require("electron");

function createWindow() {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
  });

  win.loadFile("index.html");
}

app.whenReady().then(() => {
  createWindow();
});

app.on("window-all-closed", function () {
  app.quit();
});
```

### Actual Behavior

A transparent window with a shadow is shown when a BrowserWindow is created with **frame: false**. After a while, html is loaded.

![image](https://user-images.githubusercontent.com/25681464/124547279-47277080-de02-11eb-83dd-1bf76f6e7cca.png)

### Testcase Gist URL

https://gist.github.com/facuparedes/0ad564fd2475074742faed478b7da3a1

**Comment by Levminer** [comment]
Yes I can confirm this bug too in my app on Windows 11 (https://github.com/Levminer/authme)
```
	window_splash = new BrowserWindow({
		width: 500,
		height: 550,
		transparent: true,
		frame: false,
		alwaysOnTop: true,
		resizable: false,
		webPreferences: {
			nodeIntegration: true,
			enableRemoteModule: true,
			contextIsolation: false,
		},
	})
``` 
And yes #30024 workaround not fixing it.

**Comment by Levminer** [comment]
Hey @facuparedes 
I think this was a problem with Windows 11, not Electron. After updating to the latest build (22000.65) I can't reprodue this issue. I think this is closable

**Comment by facuparedes** [comment]
Hey @Levminer 
I tried this bug and #30024 in latest Windows 10 and Windows 11 (22000.65), and both have the issues.

#30024 was confirmed by @erickzhao on Discord

I think both issues are related

**Comment by Levminer** [comment]
@facuparedes Okay I think after the pc goes to sleep this bug vanishes. Very strange.

**Comment by geroale** [comment]
Same issue here

**Comment by facuparedes-litebox** [comment]
bump

**Comment by facuparedes-litebox** [comment]
bump

**Comment by pushkin-** [comment]
repros in Electron 21. Wonder if [this PR](https://github.com/electron/electron/pull/35365) helps with this
