### ISSUE TITLE
[Bug]: After I packaged the python environment with CONDA, the call failed in electron

### ISSUE THREAD

**Issue by duuliy** [electron/electron#30025]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

window10

### What arch are you using?

x64

### Expected Behavior

After I packaged the python environment with CONDA, I ran the package locally, and SQLite3 executed normally, but failed in electron

### Actual Behavior

After I packaged the python environment with CONDA, I called the python file in electron and reported an error SQLite3

Error: Command failed: cd C:\Users\duuliy\Desktop\electron+react\public\resources\3.8-test && python.exe ../../interface.py 2
Traceback (most recent call last):
    import sqlite3
  File "C:\Users\duuliy\Desktop\electron+react\public\resources\3.8-test\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\duuliy\Desktop\electron+react\public\resources\3.8-test\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3:

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by linonetwo** [comment]
I also want to package python package with electron, can you provide an example repo, or your opensource project URL?

**Comment by linonetwo** [comment]
@duuliy Hi, can you share some information?

**Comment by duuliy** [comment]
> I also want to package python package with electron, can you provide an example repo, or your opensource project URL?

I didn't use electron to package python. I used Conda to package the python runtime and then use it in electron
