### ISSUE TITLE
[Bug]: Upgrade to 13.1.5 causes website cookies to become invalid

### ISSUE THREAD

**Issue by aaaaaajie** [electron/electron#30027]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.1.3

### What operating system are you using?

macOS

### Operating System Version

MacOS 11.2.1

### What arch are you using?

x64

### Last Known Working Electron version

10.1.3

### Expected Behavior

Auto login!

### Actual Behavior

Every time you launch the app, you stay on the login page

### Additional Information

This is a very confusing bug. Since the project is very early, I have forgotten which version of Electron was packaged at that time, but it can be confirmed that it is one of the two versions of 4.0 and 10.1.3. Here is my scenario:

1. Create a browserwindow and the value of loadURL is an external website
2. The website has already done the operation of setting cookies and can log in automatically
3. In the web chrome browser, cookies are remembered by default, and you can always log in automatically
4. Start the App in electron and log in to this external website
5. Exit the App
6. Start the app again
At this time, I found that the page was not automatically logged in, but it jumped to the login page again, which was not the result I expected!

**Comment by aaaaaajie** [comment]
I don’t know if I have described it clearly, or if it’s a bug in the past. I guess it may be related to a certain strategy of electron, or it may be related to my machine, because it meets expectations on most machines.

**Comment by aaaaaajie** [comment]
Sorry, I’ve been troubled for a long time, I can only trouble you all, I look forward to getting answers from you

**Comment by VerteDinde** [comment]
Hey @aaaaaajie, thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue, either a test repo or a gist with Electron Fiddle? Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I know making a test case for auth may be a bit tricky, but even a video or any logs you can provide would be helpful. 

One thing you could try: 13.1.0 added support for experimental cookie encryption: https://www.electronjs.org/releases/stable?page=2#13.1.0 You could try downgrading to 13.0.1 and then upgrade back to 13.1.0 to confirm whether or not it might be related.

I'm adding the blocked/need-info label for now. After you make a test case or add any of the information above, please link to it in a followup comment and I can remove it.

Thanks!

**Comment by aaaaaajie** [comment]
> Hey @aaaaaajie, thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue, either a test repo or a gist with Electron Fiddle? Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I know making a test case for auth may be a bit tricky, but even a video or any logs you can provide would be helpful.
> 
> One thing you could try: 13.1.0 added support for experimental cookie encryption: https://www.electronjs.org/releases/stable?page=2#13.1.0 You could try downgrading to 13.0.1 and then upgrade back to 13.1.0 to confirm whether or not it might be related.
> 
> I'm adding the blocked/need-info label for now. After you make a test case or add any of the information above, please link to it in a followup comment and I can remove it.
> 
> Thanks!

Thank you! This case not every machine can restore the scene, but I am trying to recreate the scene using Elctron Fiddle,I will add more information later,thank you again for......

**Comment by aaaaaajie** [comment]
It never happened again...
