### ISSUE TITLE
[Bug]: Traffic lights re-appear in fullscreen on macOS

### ISSUE THREAD

**Issue by antoineduban** [electron/electron#30026]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.5

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina version 10.15.7 

### What arch are you using?

x64

### Last Known Working Electron version

11.2.0

### Expected Behavior

Creating a `browserWindow` with `titleBarStyle: "hidden"` , then going into full screen mode, then setting a browserView on the window, should not change the way traffic lights are displayed.

### Actual Behavior

When using a `browserWindow` with `titleBarStyle: "hidden"` , going into full screen, and then setting a `browserView` on that window, the traffic lights will re-appear.

### Testcase Gist URL

https://gist.github.com/45f0a58d69bec2834535e57768363572

### Additional Information

It also is problematic because after leaving the full screen, we end up with 2 sets of traffic lights, but that is just a consequence of the initial bug I think:
![image](https://user-images.githubusercontent.com/15836571/124578993-06097d80-de4f-11eb-8790-7d3fba48846d.png)

**Comment by clavin** [comment]
Doing a manual bisect, this broke some time [between 13.1.2 and 13.1.3](https://github.com/electron/electron/compare/v13.1.2...v13.1.3).

**Comment by clavin** [comment]
For the `14-x-y` line, this broke between [14.0.0 beta 5 and beta 6](https://github.com/electron/electron/compare/v14.0.0-beta.5...v14.0.0-beta.6).

Looking at that short list, it looks like the likely culprit of this issue is #29628 (https://github.com/electron/electron/commit/f4ed98c43b43b6937573d9cd9fe0d5029e3621b1).
