### ISSUE TITLE
WeChat scan code login, after scanning the code, it will be redirected to the callback address. At this time, if the electron access address is changed, this item will be refreshed, and then all statuses will be reset. I have confirmed that the current address is the redirected address, but follow-up All operations are reloaded

### ISSUE THREAD

**Issue by zhangtaiwei** [electron/electron#30038]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

WeChat scan code login, after scanning the code, you will be redirected to the callback address, and you can access normally

### Actual Behavior

No response to redirection after code scanning authorization

**Comment by nornagon** [comment]
This is not the right place to report WeChat bugs.
