### ISSUE TITLE
[Bug]: setBrowserView shows the traffic light when fullscreen

### ISSUE THREAD

**Issue by quanweibai** [electron/electron#30037]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.4

### What operating system are you using?

macOS

### Operating System Version

11.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

when the browserWindow is fullscreen, use setBrowserView Api to switch to another page, the traffic light should not be show unless i left the fullscreen to normal window.

### Actual Behavior

when use setBrowserView, the traffic light always show when window is fullscreen.  the traffic light will cover on my page.

![企业微信截图_ef6f844d-4887-44d7-9084-473dbac84802](https://user-images.githubusercontent.com/3831666/124724074-3e3bb980-df3e-11eb-87f5-a46594b430c5.png)

**Comment by sofianguy** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone test case with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
Fixed by https://github.com/electron/electron/pull/30114
