### ISSUE TITLE
[Bug]: Using `titleBarStyle` to anything except `default` breaks the `documentEdited` status indicator on macOS

### ISSUE THREAD

**Issue by nathanlesage** [electron/electron#30039]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

12.0.7

### Expected Behavior

Using any of the documented `titleBarStyle`s such as `hiddenInset` allows me to use `setDocumentEdited(true)` on a `BrowserWindow` instance yielding a black dot inside the "close" button of the window to indicate that the document inside the window has been edited.

### Actual Behavior

Using a `titleBarStyle` of any documented value *except* `default` breaks the `documentEdited` indicator in the "close" button on macOS. Irrespective of the value of the `documentEdited` flag, the black dot indicator does *not* appear.

### Testcase Gist URL

https://gist.github.com/b7a57c14511499bbec3da70be76b567f

### Additional Information

You can test out how this works by commenting/uncommenting the `titleBarStyle` value I've added in the gist.

> The "last known electron version" has been sourced from the version VS Code currently uses, and they use a titleBarStyle of hidden. That works flawlessly.

**Comment by nornagon** [comment]
Bisected to https://github.com/electron/electron/compare/v13.0.0-nightly.20210129...v13.0.0-nightly.20210201. #27489 seems like the likely culprit. cc @zcbenz
