### ISSUE TITLE
 App is not functioning properly after minimize the app in mac Catalina 10.15.7

### ISSUE THREAD

**Issue by AlyArman07** [electron/electron#30041]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.5

### What operating system are you using?

macOS

### Operating System Version

Catalina 10.15.7

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The app is basically counting time; in the foreground, this is working perfectly but when the app is minimized the time counting should work correctly.
Thanks!

### Actual Behavior

The app is basically counting time; in the foreground, this is working perfectly but when the app is minimized the time counting isn't slow found the wrong counting time.
Thanks!

**Comment by nornagon** [comment]
@AlyArman07 can you try running your app with `--disable-features=IntensiveWakeUpThrottling` and let me know if the issue persists?

**Comment by AlyArman07** [comment]
> @AlyArman07 can you try running your app with `--disable-features=IntensiveWakeUpThrottling` and let me know if the issue persists?

Thanks for your time
finally **backgroundThrottling:false**  resolves the issue
