### ISSUE TITLE
Unable to load other pages after restarting the app

### ISSUE THREAD

**Issue by aaaaaajie** [electron/electron#30048]
I think it's a problem of use,I expect to be able to load the URL I want to jump to after restarting the app
Described as follows:
main.js
```js
import * as storage from "electron-json-storage"
import {BrowserWindow} from "electron";
const win = new BrowserWindow({
        title: oem.originTitle(PKG.title),
        width: 800,
        height: 600,
        webPreferences: {
            nodeIntegration: false,
            plugins: true,
            contextIsolation: false,
            preload: path.join(__dirname, "preload.js"),
            enableRemoteModule: true
        }
    });
const url = storage.getSync("signInfo")?.url || "https:/www.google.com";
win.loadURL(url) // restart after url still is google.com
```

preload.js
```js
import * as storage from "electron-json-storage"
import { remote } from "electron"
function restartApp(){
    storage.set("signInfo", { url: "https://coders.worktile.com" }, function(error){
           if(!error){
                remote.app.relaunch();
                remote.app.exit(0);
           }
    })
}
```

For more information： 
Electron fiddle js demo: https://gist.github.com/aaaaaajie/655bfbf8e4aaa51dad1b5f12a940e36f

I'm looking forward to your help😄

**Comment by aaaaaajie** [comment]
Whether this is related to the life cycle of the app and whether the storage has been destroyed

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? In particular, a repro that doesn't use `electron-json-storage` (or any other 3rd-party modules) would be ideal.

Thanks in advance! Your help is appreciated.

**Comment by aaaaaajie** [comment]
> Thanks in advance! Your help is appreciated.

Whenever I receive a reply is the happiest moment.
This is indeed my real example. If we do not use electron-json-storage, the result may be different from the real case, but I try my best not to use a third party module to completely reproduce it

**Comment by aaaaaajie** [comment]
Sorry, maybe I didn't express the meaning clearly in my code, I need to spend some time on you to read my new description:

1. While creating the window, add preload.js(with a restart function)
main.js
```ts
import * as storage from "electron-json-storage"
import {BrowserWindow} from "electron";
const win = new BrowserWindow({
        title: "electron",
        width: 800,
        height: 600,
        webPreferences: {
            nodeIntegration: false,
            plugins: true,
            contextIsolation: false,
            preload: path.join(__dirname, "preload.js"),
            enableRemoteModule: true
        }
    });
const url = storage.getSync("signInfo")?.url || "https:/www.google.com";
win.loadURL(url) // restart after url still is google.com
```
2. Load an HTML containing the restart button
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
    <title>Hello World!</title>
  </head>
  <body>
    <div class="root">
      <button class='restart' @click="restartApp">restart</button>
    </div>  
  </body>
</html>
```
3. Click the restart button and call restartApp() in preload.js. I need to change and save the URL to be loaded in main.js before restarting
preload.js
```js
const storage = require('electron-json-storage')
const { remote } = require('electron')
const path = require('path')
window.onload = function () {
  new Vue({
    el: '.root',
    methods: {
      restartApp() {
        console.log('into...')
        storage.set('signInfo', { url: 'https://coders.worktile.com' }, function (error) {
          if (error) {
            console.log(error)
            return;
          }
          remote.app.relaunch({
            args: ["--relaunch", path.join(__dirname, "main.js")]
          })
          remote.app.exit(0)
        })
      }
    }
  })
}
```
4. Restart and load the changed URL
main.js
```js
const url = storage.getSync("signInfo")?.url || "https:/www.google.com";
win.loadURL(url) // restart after url still is google.com
```
Because I don’t fully understand the life cycle after restarting the App, and I can’t monitor it on the console, I chose electron-json-storage to cache the URL I changed before restarting the App. The final result did not meet my expectations: restart After loading the new URL, but the old URL is still loaded

**Comment by aaaaaajie** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? In particular, a repro that doesn't use `electron-json-storage` (or any other 3rd-party modules) would be ideal.
> 
> Thanks in advance! Your help is appreciated.

demo: https://gist.github.com/aaaaaajie/655bfbf8e4aaa51dad1b5f12a940e36f

**Comment by nornagon** [comment]
> demo: https://gist.github.com/aaaaaajie/655bfbf8e4aaa51dad1b5f12a940e36f

How does this demo save the URL between launches? It looks like it assigns a value to `app.url` (??), but that won't be persisted.

**Comment by aaaaaajie** [comment]
> > demo: https://gist.github.com/aaaaaajie/655bfbf8e4aaa51dad1b5f12a940e36f
> 
> How does this demo save the URL between launches? It looks like it assigns a value to `app.url` (??), but that won't be persisted.

I understand that you are right, but my original version of the code is indeed like this. In the current version, I chose to save the data with the help of electron-json-storage. After restarting, I can access the modified URL.

old version code:
preload.js
![image](https://user-images.githubusercontent.com/36189354/125147392-70773200-e15d-11eb-91f4-fbb34374a186.png)

main.js
![image](https://user-images.githubusercontent.com/36189354/125147411-9f8da380-e15d-11eb-9b32-a54efa788782.png)

**Comment by aaaaaajie** [comment]
This is not very good behavior, but this is old code and works fine

**Comment by aaaaaajie** [comment]
Sorry, I have found the reason. It is caused by persistence, and it has nothing to do with electron itself
