### ISSUE TITLE
[Question]What will cause console.error "focus-change for guestInstanceId:x"? 

### ISSUE THREAD

**Issue by dogeFu** [electron/electron#30045]
This error shows when I call window.open() in a page which has a <webview> tag.However,I wrote a single example but it didn't show again.So I guess there are other reasons that cause this error. 

The source code shows  that guestInstanceID was wrong. Any Idea what goes wrong?

```
//guest-view-manager.ts
ipcMainInternal.on(IPC_MESSAGES.GUEST_VIEW_MANAGER_FOCUS_CHANGE, function (event: ElectronInternal.IpcMainInternalEvent, focus: boolean, guestInstanceId: number) {
  const guest = getGuest(guestInstanceId);
  if (guest === event.sender) {
    event.sender.emit('focus-change', {}, focus, guestInstanceId);
  } else {
    console.error(`focus-change for guestInstanceId: ${guestInstanceId}`);
  }
});
```

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
