### ISSUE TITLE
How does Electron get the information of the shortcut (.lnk)

### ISSUE THREAD

**Issue by cnblogco** [electron/electron#30046]
Create a shortcut icon through the program, get the parameters behind the target address of the shortcut icon, what API can be obtained, please。
![JC~1P4~}BM(O%W2Q~05L4LE](https://user-images.githubusercontent.com/53510577/124854484-f9656080-dfd9-11eb-8f1c-0f9a061b1a14.png)

**Comment by cnblogco** [comment]
![JC~1P4~}BM(O%W2Q~05L4LE](https://user-images.githubusercontent.com/53510577/124854453-ef436200-dfd9-11eb-988d-1114da16ad5e.png)

**Comment by cnblogco** [comment]
Is there an official API to access shortcuts

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by cnblogco** [comment]
> Thanks for reaching out!
> 
> The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.
> 
> I hope this helps!

It seems that there is no detailed documentation, do you also have a detailed link
