### ISSUE TITLE
[Bug]: PDF files Show As a Blank 

### ISSUE THREAD

**Issue by WeMissing** [electron/electron#30061]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6 , 14.0.0-beta12

### What operating system are you using?

Windows

### Operating System Version

 Win7 and Win10

### What arch are you using?

ia32

### Expected Behavior

Displaying a PDF document Ok

pageCode :

<iframe src='/static/libs/PDF.js/web/viewer.html?file=./sourceDoc.pdf' width='100%' height='100%'></iframe>

It's Ok On Chrome Browser!

### Actual Behavior

Show PDF with PDF.js！
pageCode :

<iframe src='/static/libs/PDF.js/web/viewer.html?file=./sourceDoc.pdf' width='100%' height='100%'></iframe>

Show Ok with Chrome Browser! But Show Blank with electron！

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by nornagon** [comment]
BTW, we recently had a similar report: #29326, but it was fixed in 13.1.4.

**Comment by VerteDinde** [comment]
Hey @WeMissing! This is the testing gist for Electron Fiddle that I was using to fix the issue that @nornagon mentioned above. Please feel free to modify it if that makes creating a repro easier for you 🙂  Happy to take a look once you have a repro: https://gist.github.com/80a9108e271ca83c82cc4a8772e371fc

**Comment by WeMissing** [comment]
Hello,PDF File Show all right when I remove some BrowserWindow's params：
nodeIntegration: true,
nodeIntegrationInSubFrames: true,
nodeIntegrationInWorker: true

This issue Can Be closed，sorry！

**Comment by VerteDinde** [comment]
No worries, and thanks for the update! 🙂 Glad it's working for you now
