### ISSUE TITLE
webview loadURL not working

### ISSUE THREAD

**Issue by nami-cagla** [electron/electron#30062]
**Preflight Checklist**
 

- [x] I have read the Contributing Guidelines for this project.
- [x]  I agree to follow the Code of Conduct that this project adheres to.
 - [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Electron Version**
^12.0.1

**What operating system are you using?**
Windows

**Operating System Version**
Windows 10 20H2

**What arch are you using?**
x64

**Last Known Working Electron version**
_No response_

**Expected Behavior**
When loadURL(https://google.com) is fired, the webview would load URL and the screen will redirect to Google.

**Actual Behavior**
The did-finish-load event gets fired after loadURL(https://google.com) and returns the new url (google.com) as the e.target.src,
however, the page does not redirect to google.

**Testcase Gist URL**
_No response_

**Additional Information**
_No response_

**Comment by linonetwo** [comment]
upgrade to v14beta

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by nami-cagla** [comment]
I have confirmed that loadURL is working, sorrry for the inconvenience, it was an error in my part. Thank you!
