### ISSUE TITLE
[Bug]: backdrop-filter: blur() not rendering correctly

### ISSUE THREAD

**Issue by qjack001** [electron/electron#30077]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

When using the CSS property `backdrop-filter: blur(5px)`, it is expected that the element blur everything behind it. In the screenshot below (taken on Chrome), I have positioned a `<div>` over some text and applied the following CSS:
```css
background: rgba(238,238,238,.5);
backdrop-filter: blur(5px);
```

<img width="250" alt="Chrome screenshot" src="https://user-images.githubusercontent.com/19389660/125180749-9f6bc300-e1b2-11eb-8740-b76221b44af5.png">

The text that appears behind the `<div>` is blurred, properly.

### Actual Behavior

Running the same code in Electron, the following is produced:

<img width="250" alt="Electron screenshot" src="https://user-images.githubusercontent.com/19389660/125180743-92e76a80-e1b2-11eb-957a-ad27504056ad.png">

There is a strange pseudo-blur glow effect, but no actual blur. Increasing the blur to anything above 9px seems to disable the effect completely.

### Testcase Gist URL

https://gist.github.com/qjack001/3be55e930964a343138bdb82fae3c7b0

### Additional Information

I have entered "N/A" under last version that worked because as far as I can tell, this has never been fixed. [Issue #19765](https://github.com/electron/electron/issues/19765) raised the issue 2 years ago, but was auto-closed without being addressed. [Another issue](https://github.com/electron/electron/issues/28506) was created a few months ago, but was closed because it was specific to transparent windows (where I believe this _cannot_ be done). In my case, I am using a regular (non-transparent) window.

**Comment by nornagon** [comment]
I can't reproduce this. Here's what I see when I run the gist:

![image](https://user-images.githubusercontent.com/172800/125369422-0e6f2600-e331-11eb-8078-3903a1962e74.png)

This looks the same as your "correct" image.

**Comment by qjack001** [comment]
Interesting. Perhaps this is a Big Sur related bug (as it looks like you are on an earlier version)? 
What info in particular do you need here?

**Comment by nornagon** [comment]
Ah interesting, I assumed that since there was an earlier report from several years ago that it wouldn't be Big Sur-specific, but indeed I can reproduce on Big Sur (on an M1).

![image](https://user-images.githubusercontent.com/172800/125670682-a5c9a5d2-11fa-45d7-8384-214e58363420.png)

**Comment by nornagon** [comment]
Specifying `backgroundColor: 'white'` in the BrowserWindow options works around the issue.

**Comment by qjack001** [comment]
Ah, so perhaps it *was* treating it as a transparent window. I appreciate your help @nornagon, your solution fixes the issue for me.

**Comment by codebytere** [comment]
This also may be specific to M1 - i can't repro running Big Sur on a 2019 MacBook Pro:

<img width="580" alt="Screen Shot 2021-07-15 at 7 39 19 AM" src="https://user-images.githubusercontent.com/2036040/125782158-bccddff4-dcb1-4c7b-bff2-b1b03fba06d2.png">

**Comment by nornagon** [comment]
Great, let's roll with that then :)
