### ISSUE TITLE
[Bug]: Electron 12+ doesn't enumerate video devices on Raspberry Pi

### ISSUE THREAD

**Issue by otociulis** [electron/electron#30079]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0+

### What operating system are you using?

Other Linux

### Operating System Version

Linux raspberrypi 5.10.44-v7l+ #1429 SMP Fri Jun 25 10:02:49 BST 2021 armv7l GNU/Linux

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

Any 11.x version (e.g. 11.4.10)

### Expected Behavior

When enumerating media devices in Development tools it should return list of attached video devices including Raspberry Pi Camera (https://www.raspberrypi.org/documentation/hardware/camera/) as in Electron 11, e.g.:

```
navigator.getUserMedia({video:true, audio: false}, console.log, console.error)
navigator.mediaDevices.enumerateDevices().then(console.info)
```

should return

```
0: InputDeviceInfo
deviceId: "47ef784e26fbc434d692d664585ad0cb556615e26970ae5f443a7023a34ea9ab"
groupId: "9cb9996be375abf59e2c8e0b18000fd7b51036e4a828cdf03b78de81e76c4fa6"
kind: "videoinput"
label: "mmal service 16.1"
3: InputDeviceInfo
deviceId: "f65b860f280c22bbe7788eb4673fdbc931e7d1a4f542be18c101fe4e0ed8c440"
groupId: "524fb3cc8d5171a3c9c7a9085a3bb2dd0c6cf1e8e70afb4d14bc325a0a726f42"
kind: "videoinput"
label: "bcm2835-isp"
4: InputDeviceInfo
deviceId: "2375ced2e8b40f70ed18a6baeb25897804afd1cb2b16e6e2a0e3b0ef8e3062d3"
groupId: "a41e38016eeb59881450324212f79c0a5728ca5c4f034ba1db848580badba3ce"
kind: "videoinput"
label: "bcm2835-isp"
```

### Actual Behavior

When executed on any version above Electron 11.x first call to `getUserMedia` reports following error:
```
DOMException: Requested device not found
```

and second call will return only audio devices if there are any attached.

### Additional Information

I tried same snippet of code in Raspberry `chromium-browser` (Version 88.0.4324.187 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)) and it enumerates video devices properly.

**Comment by erikian** [comment]
I've just lost some hours trying to figure out why the camera module worked without issues on Raspberry's Chromium but not on Electron. Looking forward for this fix.

**Comment by erikian** [comment]
FWIW, still not working as of Electron 17.0.0.
