### ISSUE TITLE
[Bug]: canPaste is true when clicking on windows/linux and false on macOS

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#30070]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home 20H2

### What arch are you using?

x64

### Expected Behavior

When listening for `context-menu` event in the main process. I expect `params.editFlags.canPaste` to get `false` consistently across all platforms.

### Actual Behavior

The value is `true` on Windows/Linux and false on macOS.

### Testcase Gist URL

https://gist.github.com/indutny-signal/e3e61f941f8969c42825b593ffa88e7c

### Additional Information

The test case has a link that can be right-clicked to get the `context-menu` with unexpected params. It is triggered only if there is an `<input autofocus/>` in the same html page as `<a/>` or any other focused input.

**Comment by nornagon** [comment]
Here's the logic for that flag: https://github.com/electron/electron/blob/4db7221c7da219116e4287278f446c76ab6d3f89/shell/common/gin_converters/blink_converter.cc#L446-L453
