### ISSUE TITLE
[Bug]: How to prevent tamper proofing of electron application

### ISSUE THREAD

**Issue by flamecopper** [electron/electron#30072]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Hi there, below is the tampering check of the application, all i have to do is to change the != of the application to == and the application can execute successfully, is there a way to mitigate this issues?

### Actual Behavior

12363:        const r = new Set;
13452:                    c = Buffer.from("YmFzZTY0", "base64").toString(),
13461:                    const r = i(17),
13463:                        f = s.readFileSync(${t}${d}).toString(${m});
13465:                        const t = r.publicDecrypt(p, Buffer.from(f.toString(c), c)).toString();
13466:                        a.checksums[${l}] == t ? (n.default.warn("tamper 05.")) : e()

I have already decompiled the asar.app and compiled back the asar application

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
