### ISSUE TITLE
webview.loadURL not working when element is cloned

### ISSUE THREAD

**Issue by TechStudent11** [electron/electron#30078]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Windows

### Operating System Version

20H2

### What arch are you using?

x64

### Expected Behavior

When I clone a webview element and use the loadURL method, it should change the URL and load whatever I passed in.

### Actual Behavior

The loadURL method throws an error and doesn't work.
Error:
```javascript
Uncaught TypeError: webview.loadURL is not a function
    at createNewTab (renderer.js:40)
    at renderer.js:71
    at Array.map (<anonymous>)
    at renderer.js:70
```

**Comment by jkleinsc** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by TechStudent11** [comment]
Um okay so for some reason it works again... welp, closing time...
