### ISSUE TITLE
[Bug]: Transparency/backgroundColor no longer working

### ISSUE THREAD

**Issue by t57ser** [electron/electron#30082]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0-beta.12

### What operating system are you using?

Windows

### Operating System Version

10.0.19042 Build 19042

### What arch are you using?

x64

### Last Known Working Electron version

13

### Expected Behavior

Window should be transparent

### Actual Behavior

Open a window with transparency enabled and delete the dom, the window will be white instead of transparent.
**Also seems like settings the backgroundColor property has no longer an effect.** I always see a white window

```
const {app, BrowserWindow} = require('electron')
const path = require("path");

function createWindow () {
	const mainWindow = new BrowserWindow({
		transparent: true,
		frame: false,
	})

	mainWindow.loadURL('https://example.com')
	mainWindow.webContents.openDevTools()
}

app.whenReady().then(createWindow)
```

### Testcase Gist URL

https://gist.github.com/e124340107f6c4a3ade8b36d98a16b9a

**Comment by sachetsharma1** [comment]
I see the same issue in 13.0.1
