### ISSUE TITLE
[Bug]: session.setProxy() seems to ignore bypassProxyHosts

### ISSUE THREAD

**Issue by rpatrick00** [electron/electron#30080]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.11

### What operating system are you using?

macOS

### Operating System Version

10.15.7

### What arch are you using?

x64

### Expected Behavior

`session.resolveProxy()` to not return the proxy for URLs whose hostname pattern match an entry in the `bypassProxyHosts` parameter passed to `session.setProxy()`.

### Actual Behavior

`session.resolveProxy()` always returns the proxy--even for URLs whose hostname matches an entry in `bypassProxyHosts`.

### Testcase Gist URL

https://gist.github.com/rpatrick00/c4d95145348168b99e5256f266f388b4

### Additional Information

Maybe I am just doing something dumb in this test.  

I am trying to get `BrowserWindow.webContents.session.setProxy()` to work properly on Linux in an attempt to resolve a network connection timeout issue I have trying to download a CSS file with icon fonts referenced in index.html.

**Comment by nornagon** [comment]
The option is named `proxyBypassRules`.
