### ISSUE TITLE
macOS crash because of Kernel Panic

### ISSUE THREAD

**Issue by ankur4747github** [electron/electron#30108]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.3.2

### What operating system are you using?

macOS

### Operating System Version

macOS 10.16.0 CPU:  Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (x64), 12 cores

### What arch are you using?

x64

### Last Known Working Electron version

10.3.2

### Expected Behavior

OS Should not crash 

### Actual Behavior

Mac os crash was caused by Zenith Messenger Helper (Rendere
and it's randomly crashing on macOS 10.16.0  because **Kernel Panic**
it's a cross-platform application so it's working perfectly on Windows OS and macOS below Big Sur Version.. its random crash unable to reproduce 

After OS crash its shows because of our renderer process

**Logs:-** 
Panic(CPU 10, time 192912923548962): NMIPI for spinlock acquisition timeout, spinlock: 0xffffff86c8b212d0, spinlock owner: 0xffffff86c81a7da0, current_thread: 0xffffff86c81a7da0, spinlock_owner_cpu: 0xa
RAX: 0xffffff86b0eabb20, RBX: 0xffffff93768c9878, RCX: 0x0000000000000080, RDX: 0x0000260400000000
RSP: 0xffffffa0e6913aa0, RBP: 0xffffffa0e6913ae0, RSI: 0xffffff86c81a7da0, RDI: 0xffffff93768c9878
R8:  0xffffffa0e6913c60, R9:  0xffffff801bae40e0, R10: 0x0000000000ffffff, R11: 0x0000000000000000
R12: 0xffffff86c81a7da0, R13: 0x0000000000000000, R14: 0x000026051de2528e, R15: 0xffffff86b0eabb20
RFL: 0x0000000000000082, RIP: 0xffffff801baa0fca, CS:  0x0000000000000008, SS:  0x0000000000000010
Backtrace (CPU 10), Frame : Return Address
0xffffffa08ed8cf80 : 0xffffff801bbc4ccb 
0xffffffa08ed8cfd0 : 0xffffff801ba32bdd 
0xffffffa0e6913ae0 : 0xffffff801baa10d4 
0xffffffa0e6913b10 : 0xffffff801bae2930 
0xffffffa0e6913b30 : 0xffffff801bae4119 
0xffffffa0e6913be0 : 0xffffff801bae4612 
0xffffffa0e6913c50 : 0xffffff801bae368a 
0xffffffa0e6913d10 : 0xffffff801bae75c5 
0xffffffa0e6913d50 : 0xffffff801bff92f4 
0xffffffa0e6913d70 : 0xffffff801bff93de 
0xffffffa0e6913db0 : 0xffffff801c0528bd 
0xffffffa0e6913e30 : 0xffffff801c04dcc5 
0xffffffa0e6913ee0 : 0xffffff801c04daf1 
0xffffffa0e6913f40 : 0xffffff801c13fc9e 
0xffffffa0e6913fa0 : 0xffffff801ba331f6 

Process name corresponding to current thread: Zenith Messenger Helper (Rendere
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20F71

Kernel version:
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
Kernel UUID: 52A1E876-863E-38E3-AC80-09BBAB13B752
KernelCache slide: 0x000000001b800000
KernelCache base:  0xffffff801ba00000
Kernel slide:      0x000000001b810000
Kernel text base:  0xffffff801ba10000
__HIB  text base: 0xffffff801b900000
System model name: MacBookPro15,1 (Mac-937A206F2EE63C01)
System shutdown begun: NO
Hibernation exit count: 18

System uptime in nanoseconds: 192912923573289
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000af740a483e43
  Sleep   : 0x0000a0c92843e27b 0x00000000757e2c0c 0x0000a044caa046d8
  Wake    : 0x0000a0c949e3918b 0x000000007580a6d2 0x0000a0c945ef47c8
last started kext at 135767100022934: >AudioAUUC	1.70 (addr 0xffffff7fb6620000, size 12288)
last stopped kext at 134881443997129: >!UAudio	405.39 (addr 0xffffff7fb65a6000, size 315392)
loaded kexts:
com.paragon-software.filesystems.ntfs	90.5.15
com.Cylance.CyProtectDrvOSX	1
>AudioAUUC	1.70
@filesystems.afpfs	11.3
@nke.asp_tcp	8.2
>!APlatformEnabler	2.7.0d0
>AGPM	122.1
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
@fileutil	20.036.15
>!ATopCaseHIDEventDriver	4050.1
>!AHIDALSService	1
@kext.AMDFramebuffer	4.0.5
@kext.AMDRadeonX4000	4.0.5
@kext.AMDRadeonServiceManager	4.0.5
>!AUpstreamUserClient	3.6.8
>!AGraphicsDevicePolicy	6.3.3
>!A!IKBLGraphics	16.0.4
@kext.AMD9500!C	4.0.5
@AGDCPluginDisplayMetrics	6.3.3
>!ABridgeAudio!C	140.4
>pmtelemetry	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
|IO!BSerialManager	8.0.5d7
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>!A!ISlowAdaptiveClocking	4.0.0
>!AMuxControl2	6.3.3
>!A!IPCHPMC	2.0.1
>!AGFXHDA	100.1.433
>!A!ICFLGraphicsFramebuffer	16.0.4
>AGDCBacklightControl	6.3.3
>!AThunderboltIP	4.0.3
>BridgeAudioCommunication	140.4
>!AAVEBridge	6.1
>!AMCCSControl	1.14
>BCMWLANFirmware4378.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4355.Hashstore	1
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.100.11
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!ABCMWLANBusInterfacePCIeMac	1
@filesystems.apfs	1677.120.9
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	311
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
>usb.cdc.acm	5.0.0
>usb.serial	6.0.0
>!UAudio	405.39
$SecureRemotePassword	1.0
@kext.triggers	1.0
>!AHIDKeyboard	224
>!AHS!BDriver	4050.1
>IO!BHIDDriver	8.0.5d7
>!AActuatorDriver	4440.3
>!AMultitouchDriver	4440.3
>!AInputDeviceSupport	4400.35
@kext.AMDRadeonX4100HWLibs	1.0
@kext.AMDRadeonX4000HWServices	4.0.5
@kext.AMDSupport	4.0.5
|IOAVB!F	940.4
@plugin.IOgPTPPlugin	985.2
|IOEthernetAVB!C	1.1.0
@!AGPUWrangler	6.3.3
|IOSlowAdaptiveClocking!F	1.0.0
>!AGraphicsControl	6.3.3
|IOAccelerator!F2	442.9
|IO!BHost!CUARTTransport	8.0.5d7
|IO!BHost!CTransport	8.0.5d7
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
@!AGraphicsDeviceControl	6.3.3
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
>!ABacklightExpert	1.1.0
|IONDRVSupport	585.1
|IOGraphics!F	585.1
>!ASMBus!C	1.0.18d1
>!UMergeNub	900.4.2
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc.ecm	5.0.0
>usb.cdc.ncm	5.0.0
>usb.!UHub	1.2
>!AThunderboltDPOutAdapter	8.1.4
>!AThunderboltPCIUpAdapter	4.1.1
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!AThunderboltPCIDownAdapter	4.1.1
>!AThunderboltDPInAdapter	8.1.4
>!AThunderboltDPAdapter!F	8.1.4
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssI2C	3.0.60
>!A!ILpssDmac	3.0.60
>!ABSDKextStarter	3
|IOSurface	290.8.1
@filesystems.hfs.encodings.kext	1
>!ABCMWLANCoreMac	1.0.0
|IOSerial!F	11
|IO80211!FV2	1200.12.2b1
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
>IOImageLoader	1.0.0
>corecapture	1.0.4
>!AXsanScheme	3
>!AThunderboltNHI	7.2.8
|IOThunderbolt!F	9.3.2
>usb.!UVHCIBCE	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCI	1.2
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOTimeSync!F	985.2
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.5d7
|IOReport!F	47
|IO!BPacketLogger	8.0.5d7
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.120.2
|IOUSBMass!SDriver	184.121.1
|IOSCSIBlockCommandsDevice	436.121.1
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.121.1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1
panic(cpu 0 caller 0xffffff801c2a153d): "Spinlock acquisition timed out: lock=0xffffff86c8b212d0, " "lock owner thread=0xffffff86c81a7da0, current_thread: 0xffffff86b0eabb20, " "lock owner active on CPU 0xa, current owner: 0xffffff86c81a7da0, time: 192912923593279"@/System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.121.3/osfmk/i386/locks_i386.c:541
Backtrace (CPU 0), Frame : Return Address
0xffffffa06e543ad0 : 0xffffff801ba8e0dd 
0xffffffa06e543b20 : 0xffffff801bbd4f33 
0xffffffa06e543b60 : 0xffffff801bbc552a 
0xffffffa06e543bb0 : 0xffffff801ba32a2f 
0xffffffa06e543bd0 : 0xffffff801ba8d8fd 
0xffffffa06e543cf0 : 0xffffff801ba8dbf3 
0xffffffa06e543d60 : 0xffffff801c29d81a 
0xffffffa06e543dd0 : 0xffffff801c2a153d 
0xffffffa06e543e10 : 0xffffff801bbba135 
0xffffffa06e543e30 : 0xffffff801baaef56 
0xffffffa06e543e60 : 0xffffff801baddc9f 
0xffffffa06e543f20 : 0xffffff801bbb0fb3 
0xffffffa06e543f60 : 0xffffff801bbce5aa 
0xffffffa06e543f80 : 0xffffff801bbc4ccb 
0xffffffa06e543fd0 : 0xffffff801ba32bdd 
0xffffffa0e6103da0 : 0xffffff801bae73ae 
0xffffffa0e6103e00 : 0xffffff801c04fe5f 
0xffffffa0e6103f00 : 0xffffff801c04eed6 
0xffffffa0e6103f40 : 0xffffff801c13fc9e 
0xffffffa0e6103fa0 : 0xffffff801ba331f6 

Process name corresponding to current thread: Zenith Messenger Helper (Rendere

**Comment by jkleinsc** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by miniak** [comment]
Electron 10 is not supported

**Comment by erickzhao** [comment]
Possible duplicate #27332

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
