### ISSUE TITLE
Is it posible to change BrowserWindow settings depending on the current route?

### ISSUE THREAD

**Issue by dekadentno** [electron/electron#30106]
Greetings. I'm not sure if this is the right place for the question: 
is it possible in Electron to set some `BrowserWindow` settings depending on the current route?
e.g. `maxWidth` and `maxHeight` should be 800x600 on `/login` and 1600x1200 on `/dashboard`

I understand that the window is created with `createWindow()` after all settings are set and I cannot be sure if they can be manipulated from the code like on the example above.

Thanks

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
