### ISSUE TITLE
[Bug]: Silent Printing not working?

### ISSUE THREAD

**Issue by KirstLMCG** [electron/electron#30107]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.2 LTS

### What arch are you using?

x64

### Expected Behavior

I expect the print dialog **_not_** to appear when pressing print.

### Actual Behavior

The print dialog shows.

### Additional Information

This is the code I have seen used, but it does not work. I cannot find any further docs on this and I have seen people in the past report it as a bug, but I can't find what the actual issue is and any work arounds.

```
const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  });

  mainWindow.webContents.print(
    {
      silent: true,
      printBackground: false,
      deviceName: "HP_DeskJet_4100_series_A6BABF_test",
    }
```

**Comment by codebytere** [comment]
Duplicate https://github.com/electron/electron/issues/29334
