### ISSUE TITLE
[Bug]: Freezing on bulk session creation

### ISSUE THREAD

**Issue by jakobjj0** [electron/electron#30110]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 10.0.19042 Build 19042

### What arch are you using?

x64

### Last Known Working Electron version

-

### Expected Behavior

Sessions being created, without any freezing or lags

### Actual Behavior

All BrowserWindows fully freeze  for about 10 seconds and worst case, end up crashing the app.  

### Testcase Gist URL

https://gist.github.com/jakobjj0/eb83674c890f0b897d802c694f25d9a7

### Additional Information

It seems like the "fromPartition" process doesnt use Promises, so its not possible to run it asynchronously.

**Comment by nornagon** [comment]
5000 sessions is a lot of sessions! What's your use case for creating that many sessions?

NB, `session` objects are not deletable, and persist for the lifetime of the app. They're also quite heavyweight, and creating one involves disk I/O amongst other nontrivial operations.

Ideally we still wouldn't crash in this situation, though—would it be possible to attach a crash dump? You can collect them by adding the following snippet to your main process code, before app.whenReady:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by jakobjj0** [comment]
Something like testing lots of proxies simultaneously. 
Another solution would be to add proxy to net requests without having to use sessions.

Also forgot to mention, seems like every session creates a Preference file in the appdata/roaming folder of the project. Haven't found a way to disable it yet. 

And the crashing rarely happens, not able to trigger it right now.
