### ISSUE TITLE
[Bug]: Windows setIgnoreMouseEvents(false) doesn't work with transparent BrowserWindow

### ISSUE THREAD

**Issue by aluo-lmi** [electron/electron#30116]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19041.1052

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

Setting `setIgnoreMouseEvents(false)` on a BrowserWindow that has been opened with `frame: false, transparent: true` on Windows should make the window not ignore mouse events in transparent areas. This is the behavior seen on MacOS.

### Actual Behavior

Transparent areas of a BrowserWindow that has been opened with `frame: false, transparent: true` still ignore mouse events after setting `setIgnoreMouseEvents(false)` on the window

### Testcase Gist URL

https://gist.github.com/b52f026c763057f97f745fade82758fd

### Additional Information

Is this the expected behavior on Windows? I noticed that loading a contentful page into the transparent window on Windows behaves as expected - any content (buttons, background, etc) will not ignore mouse events with `setIgnoreMouseEvents(false)` but any transparent/non-contentful areas will. Opening this issue as it does not match the behavior when running on Mac, where the entire transparent window does not ignore mouse events with `setIgnoreMouseEvents(false)` regardless of content

Repro steps: 
1. Start gist project - observe a transparent window is created (with a small canvas border for visibility)
2. On Mac, observe the transparent window is not clickable through. On Windows, observe the transparent window is entirely clickable through

**Comment by aluo-lmi** [comment]
Update on this bug report - I think this may be the expected behavior on Windows, it seems making a window entirely transparent will make clicks go through the window, see SO : https://stackoverflow.com/questions/6165136/ws-ex-transparent-what-does-it-actually-do . 

I have decided to work around this by setting a minimal opacity background on the BrowserWindow and this works nicely. 
`window.setBackgroundColor('#01FFFFFF');`
Given this info, maybe this bug can be closed as not an issue. Thanks

**Comment by Seraphli** [comment]
Same here. Electron version 14.
Another issue is here.
https://github.com/electron/electron/issues/30744
