### ISSUE TITLE
[Feature Request]: Ability to open links in a WebContents from the main process

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#30123]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

`webContents.setWindowOpenHandler(handler)` exists as a way to handle links clicked in the renderer process.

I'm writing a library which needs to open links from the main process. Currently I delegate handling opening links to the user of the library through a custom API. However, reusing the existing logic for `setWindowOpenHandler()` would be ideal.

### Proposed Solution

```ts
interface WebContents {
  runWindowOpenHandler(options: WindowOpenOptions): void;
}

interface WindowOpenOptions {
  url: string;
  frameName: string;
  features: string;
  disposition: string;
  referrer: string;
  postBody?: PostBody;
}
```

### Alternatives Considered

No other ideas come to mind at the moment.

### Additional Information

I still need to dig into the Chromium code to see how feasible this is and whether any public APIs exist for such a feature.

**Comment by nornagon** [comment]
I'm not sure I understand what the idea here is... the window open handler is only for `window.open`, which doesn't make sense from a main-process context.

**Comment by samuelmaddock** [comment]
> 
> 
> I'm not sure I understand what the idea here is... the window open handler is only for `window.open`, which doesn't make sense from a main-process context.

It's also called for activating `<a href="..." target="_blank">` links, right? From the main process, I want to open a link with the same code path where the user can filter based on the `disposition` and other params.

**Comment by nornagon** [comment]
a `target=_blank` link still hooks up `opener` and such, which i don't know if it makes sense to do when initiating from the browser?

**Comment by samuelmaddock** [comment]
Closing this as I no longer need this.
