### ISSUE TITLE
Electron's powerMonitor.getSystemIdleTime() is giving always 0 in windows Machine

### ISSUE THREAD

**Issue by iamarman07** [electron/electron#30126]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

11.2.2

### Expected Behavior

powerMonitor.getSystemIdleTime() should provide the idle time but giving always 0 

### Actual Behavior

powerMonitor.getSystemIdleTime() should provide the idle time based idle status

**Comment by nornagon** [comment]
Our implementation of `getSystemIdleTime` is a direct call to Chromium's API:

https://github.com/electron/electron/blob/4db7221c7da219116e4287278f446c76ab6d3f89/shell/browser/api/electron_api_power_monitor.cc#L137-L139

so it's unlikely that this is a bug in Electron.

**Comment by AlyArman07** [comment]
Thanks @nornagon 
any other workaround for idle time fetching?
