### ISSUE TITLE
[Bug]: showOpenDialog with openDirectory can not choose folder

### ISSUE THREAD

**Issue by cike8899** [electron/electron#30125]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Windows

### Operating System Version

windows 10 version 19041

### What arch are you using?

x64

### Last Known Working Electron version

11.4.1

### Expected Behavior

I can choose a folder

### Actual Behavior
![image](https://user-images.githubusercontent.com/8089971/125601599-618c935c-902d-4019-bbc2-ca11f47ca18f.png)

```
      const { filePaths } = await remote.dialog.showOpenDialog(
        remote.getCurrentWindow(),
        {
          title: intl.formatMessage({ id: 'open' }),
          properties: ['openDirectory']
        }
      )
```

I can only select files, not directories.
In version 11.4.1, I can select the directory normally

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

Thanks in advance! Your help is appreciated.

**Comment by cike8899** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Thanks in advance! Your help is appreciated.

[gist reproduction demo](https://gist.github.com/a4c097c1a0e2ad182f73d8212103909e)

If I write the code in proload.ts, I can open the directory normally

preload.js

```
  async chooseFolder() {
    return await remote.dialog.showOpenDialog(remote.getCurrentWindow(), {
      title: 'open',
      properties: ['openDirectory']
    })
  }
```

renderer.js

```
  const selectPath = async () => {
      const electron = window.electron
      const { filePaths } = await electron.chooseFolder()
    }
```

**Comment by knownasilya** [comment]
I have a similar issue, but I specify `properties: ['openFile', 'openDirectory'],` and on macOS I can choose files or folders, but on Windows it only allows me to choose folders.

**Comment by nick-d-dev** [comment]
is this being work on in any capacity?

im using the latest version (17.x at the time or writing) and trying to select a folder from main, only lets me select a file, on both mac and windows

**Comment by knownasilya** [comment]
Yeah, still a bug...

**Comment by MarshallOfSound** [comment]
@knownasilya Can you please confirm what Electron version this is still confirmed to be a bug on.  I just tested and:
* (a) the fiddle doesn't even run on Electron 21 so I updated it to handle the removal of `remote`
* (b) it definitely works now 🤷 


See gist for Electron 21

**Comment by renegadevi** [comment]
I still have this issue on 22.0.0. This issue only appear for me when running in kiosk-mode.

```js
dialog.showOpenDialog(global_window, {
    properties: ['openDirectory']
})

**Comment by knownasilya** [comment]
not stale
