### ISSUE TITLE
[Feature Request]: How to create a BrowserWindow which Larger Than Screen in Windows and Linux

### ISSUE THREAD

**Issue by WeMissing** [electron/electron#30154]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to transform html file to picture with BrowserWindow's capturePage function，but when the page is higher than screen‘s height,I can't get the full content of the page！

### Proposed Solution

I want create a BrowserWindow which Larger Than Screen In Windows And Linux

### Alternatives Considered

none

### Additional Information

none

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by kkanekii** [comment]
can I have the code of what you have tried so far?

**Comment by WeMissing** [comment]
thanks for your attentions,my code  :

		  let html2Picpath = path.normalize(data.picpath);
		  let html2picUrl = data.htmlurl;
		  let html2PicwinParams= {
		    show: false,
			frame: false
		  };
		  let capRect = {};
		  if(typeof(data.width) != undefined && typeof(data.height) != undefined && !isNaN(data.width) && !isNaN(data.height)){
			  html2PicwinParams.width = parseInt(data.width);
			  html2PicwinParams.height = parseInt(data.height);
			  capRect.width = parseInt(data.width);
			  capRect.height = parseInt(data.height);
		  }
		  if(typeof(data.x) != undefined && typeof(data.y) != undefined && !isNaN(data.y) && !isNaN(data.x)){
		  	  html2PicwinParams.x = parseInt(data.x);
		  	  html2PicwinParams.y = parseInt(data.y);
			  capRect.x = parseInt(data.x);
			  capRect.y = parseInt(data.y);
		  }
		  const html2Picwin = new BrowserWindow(html2PicwinParams);
		  html2PicwinParams = null;
		  if (html2picUrl.indexOf('https:') != 0 && html2picUrl.indexOf('http:') != 0 && html2picUrl.indexOf('file:') != 0) {
		    html2picUrl = "file://" + path.resolve(html2picUrl);
		  }
		  commtools.mkdirsSync(path.dirname(html2Picpath));
		  if (fs.existsSync(html2Picpath)) {
			fs.unlinkSync(html2Picpath); 
		  }
		  if (html2Picwin.webContents.listeners('did-finish-load').length > 0) {
		    html2Picwin.webContents.removeAllListeners('did-finish-load');
		  }
		  html2Picwin.webContents.on('did-finish-load', async() => {
			html2Picwin.capturePage(capRect).then(image => {
				let extname=path.extname(html2Picpath);
				extname = extname.toLowerCase();
				let imageBuffer;
				if(extname.indexOf('png')>0){
					imageBuffer = image.toPNG();
				}else if(extname.indexOf('jpg')>0 || extname.indexOf('jpeg')>0){
					imageBuffer = image.toJPEG(100);
				}else if(extname.indexOf('bmp')>0){
					imageBuffer = image.toBitmap();
				}else{
					!connectFlag || socket.write(JSON.stringify({result: false}));
					html2Picwin.destroy();
					return;
				}
				fs.writeFile(html2Picpath, imageBuffer, (error) => {
				  if (error) {
				    !connectFlag || socket.write(JSON.stringify({result: false}));
				  } else {
				    !connectFlag || socket.write(JSON.stringify({result: true}));
				  }
				  html2Picpath = imageBuffer = null;
				});
				html2picUrl = extname = null;
				if (html2Picwin.webContents.listeners('did-finish-load').length > 0) {
				  html2Picwin.webContents.removeAllListeners('did-finish-load');
				}
				html2Picwin.destroy();
			}).catch(e => {
				!connectFlag || socket.write(JSON.stringify({result: false}));
				html2Picwin.destroy();
				return;
			});
		  });
		  html2Picwin.loadURL(html2picUrl);

**Comment by kkanekii** [comment]
I don't think I will be able to help you over here, thank you very much for your patience
