### ISSUE TITLE
How to delay the startup of electron？

### ISSUE THREAD

**Issue by glk-hll** [electron/electron#30166]
With the same set of program settings, most computers start normally, only a few computers will appear black screen after startup, and can't open the console.

**Comment by seb-mtl** [comment]
Can you add the missing information from the bug report template?

- Operating System + Version
- Electron Version
- Machine Architecture
- Graphics Card

If you have access to a machine that indicates a black screen, try to start the application with `--disable-gpu`.

**Comment by glk-hll** [comment]
@seb-mtl I'm asking how to make the electron program delay starting when it starts up？thanks!
Operating System：`Windows x64`
Electron Version `"electron": "8.2.5"`

**Comment by seb-mtl** [comment]
It depends on what you are trying to do. A "delay" can mean many things. Do you need it for debugging purposes? In that case you can start Electron with [--inspect-brk](https://www.electronjs.org/docs/tutorial/debugging-main-process#--inspect-brkport).

If that's not enough, please explain exactly what you need.

**Comment by glk-hll** [comment]
@seb-mtl After setting openAtLogin to true, how to delay the startup of electron program？
Because the normal self startup of electron program will conflict with other programs, resulting in the black screen of my program

**Comment by seb-mtl** [comment]
Understood. I don't have a solution for now but this seems to have been reported in other repos as well. [Here](https://github.com/vector-im/element-web/issues/15486) and [here](https://github.com/vector-im/element-web/issues/14620).

> We have this problem about on 80 Windows 10 computer, whether within the domain or on the RDS Server 2016.

**Comment by seb-mtl** [comment]
For the delay, you could invoke your process with an argument that you will check during startup again. This means, you can detect if your application got started by the OS during startup or the user. If you detect the argument, e.g. `--autostart`, you delay the start through a timer.

**Comment by glk-hll** [comment]
@seb-mtl  First of all, thank you for your reply. How to detect whether the application is started by the operating system or by the user during startup? And what you said -- is autostart mentioned in the official document?

**Comment by seb-mtl** [comment]
You can set the argument how the OS will execute your application during login. That way you can set your own argument and detect it during startup.

```
app.setLoginItemSettings({
  openAtLogin: true,
  path: updateExe,
  args: [
    '--processStart', `"${exeName}"`,
    '--process-start-args', `"--this-is-my-own-arg"`
  ]
})```

**Comment by glk-hll** [comment]
@seb-mtl Can I get the value of `-- process start args` by using `process. argv` ? Are `path` and `args['-- processstart'] required?

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
