### ISSUE TITLE
[Bug]: crypto.Hash.update very slow compared to node

### ISSUE THREAD

**Issue by sebastianrath** [electron/electron#30176]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4 (20F71)

### What arch are you using?

x64

### Expected Behavior

I am using [crypto.Hash.update](https://nodejs.org/api/crypto.html#crypto_hash_update_data_inputencoding) to generate the sha256 hash of a part of a file. You can find the code [here](https://github.com/Snowtrack/SnowFS/blob/4a2bfbdb352af1578fbf96c87d5d522e1c376f48/src/common.ts#L74-L90).

When the function is executed directly __**through node**__ on 1GB file it takes around 1.5 seconds to execute, as outlined below.

![Screen Shot 2021-07-17 at 10 00 38 PM](https://user-images.githubusercontent.com/12844423/126053831-1b71b7e3-82fa-412d-80f3-de564251ae77.png)

Furthermore you see a close-up of the `update` call here: Around **2.49ms** per call.
![Screen Shot 2021-07-17 at 10 25 37 PM](https://user-images.githubusercontent.com/12844423/126053845-74bf0f01-9667-48d6-b9ed-ac42f47c6e6c.png)

### Actual Behavior

If I execute the same function on the same file inside Electron the overall graph looks very similar:

![Screen Shot 2021-07-17 at 10 20 51 PM](https://user-images.githubusercontent.com/12844423/126053865-1812d209-7ffd-4c36-8d99-40ef624e17df.png)

But different Electron versions show different runtimes. Instead of 2.5ms, both Electron versions are considerably slower:

**Electron 8.5.5:**
![Screen Shot 2021-07-17 at 10 42 17 PM](https://user-images.githubusercontent.com/12844423/126053980-63c2245a-becd-43dd-b1da-4753c7485289.png)

**Electron 13.1.6:**
![Screen Shot 2021-07-17 at 11 21 50 PM](https://user-images.githubusercontent.com/12844423/126054569-094f2074-1f1a-43db-87f6-1139d298740e.png)

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by seb-mtl** [comment]
Here is the example fiddle. Before you start though, please set the path to a file > 1GB.

Afterwards, save the following file and execute directly in node.


```

const path = require('path')
var crypto = require("crypto");
var fs = require("fs");

const filename = "put path to huge file in here, e.g. 1gb <";

function getPartHash(filepath) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash('sha256');

    const fh = fs.createReadStream(filepath, { autoClose: true });

    fh.on('data', (d) => {
      hash.update(d);
    });

    fh.on('end', () => {
      resolve({ hash: hash.digest('hex'), start: -1, end: -1 });
    });

    fh.on('error', reject);
  });
}

function runTest() {
    var t0 = Date.now();
    getPartHash(filename)
        .then(() => {
            console.log(`Time in ms: ${Date.now() - t0}`);
        })
}

runTest()
```
