### ISSUE TITLE
 [Bug]: Frameless transparent BrowserWindow on Windows OS has transparent space below it when height is less than 60px

### ISSUE THREAD

**Issue by dlofran2** [electron/electron#30171]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.14

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Versions 1909

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

`BrowserWindow` should not have extra space below when height is less than 60px.

### Actual Behavior

When a `BrowserWindow` is less than 60px there is a transparent, draggable space below the rendered elements.  

### Testcase Gist URL

https://gist.github.com/dlofran2/511aba740646150bc15d58c8d4627e2f

### Additional Information

- `app.disableHardwareAcceleration()` will fix the issue but am wondering if there is a solution other than that.
- Currently on a Mac machine, but this code is the exact same as I tested on my Windows machine where I could reproduce the issue.

**Comment by fanchenio** [comment]
This bug can still be reproduced in the latest version
