### ISSUE TITLE
[Bug]: script load error, but success in the browser

### ISSUE THREAD

**Issue by ishowshao** [electron/electron#30178]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.x

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.2.3

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

normally, every <script> load success

### Actual Behavior

main.js,  `mainWindow.loadURL('https://...') // load url from online, a Vue spa project`
this url works well in browser(chrome 91.0, same mac)
but
in electron 13.1.x, chunk-vendors.js load fail **very high probability** **only in prod build**
i debug production app by open my.app --args --remote-debugging-port=8315
there is no chunk-vendos.js 
![image](https://user-images.githubusercontent.com/2149069/126057769-edf201f3-0ab0-4b4b-8625-4411a9d89584.png)
but 
![image](https://user-images.githubusercontent.com/2149069/126057795-5a7fe494-35d8-49aa-96a6-816d43731c65.png)
there is script tag in index.html

script.onerror fired with no message

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by ishowshao** [comment]
I'm sure this is your bug
