### ISSUE TITLE
[Bug]: Video TexImage renders extremely slow when OOP raster is disabled (Chore, Chrome Cherry-pick)

### ISSUE THREAD

**Issue by koush** [electron/electron#30173]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

9.4.4

### Expected Behavior

Video textures from software decoders render at 5fps when OOP rasterization is disabled.

This is an upstream bug Chrome that I spent a few weeks tracking down. I would like this Fix in electron because it's a major performance regression that has kept me from upgrading from version Electron 9.

Here's a site that demonstrates the problem on Chrome < 93.
https://koush.github.io/webcodecs/

Here's the bug report on Chrome's issue tracker:
https://bugs.chromium.org/p/chromium/issues/detail?id=1227921

Here is the confirmed fix:
https://chromium.googlesource.com/chromium/src/+/5487040a284a0cbac172520052e7b54c8e48596e

### Actual Behavior

Video textures from software decoders should render smoothly.

**Comment by nornagon** [comment]
Created https://github.com/electron/electron/pull/30203 to backport this to 13.x.

**Comment by koush** [comment]
Thanks, can you kick off a point release for 13.x?

**Comment by nornagon** [comment]
Fixed in 13.1.8.
