### ISSUE TITLE
[Bug]: Unable to use local paths

### ISSUE THREAD

**Issue by akash07k** [electron/electron#30180]
### Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

20 H2

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

We should be able to use local resources or there should be some way around.

### Actual Behavior

For example, when I try to use this code:
let { Howl, Howler } = require("howler");
let path = require("path");
let sound = new Howl({
    src: [path.join(__dirname, "sound.wav")],
});

sound.play();

I get following error:
main_window:1 Not allowed to load local resource: file:///path_to_sound_to.wav
If I use webSecurity: false then it works fine, but it should work without disabling web security too.
Or there should be some way around.
I searched a lot, but couldn't find any way.
Please help

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by akash07k** [comment]
Thanks, I'll try asking on community sites. btw, do you know the fix?
> Thanks for reaching out!
> 
> The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.
> 
> I hope this helps!
