### ISSUE TITLE
Expose `partition_key` in cookies.get/set APIs

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#30189]
Refs: https://chromium-review.googlesource.com/c/chromium/src/+/3012034

**Comment by nornagon** [comment]
What do you imagine the API for this looking like?

**Comment by MarshallOfSound** [comment]
I would imagine adding a new property to both the set/get APIs which maps to the `PartitionKey()` of the canonical cookie.  We can safely send it in and out of JS using the `Serialize` and `Deserialize` methods of `SchemefulSite`
