### ISSUE TITLE
[Feature Request]: allow webview.send to send to iframes enabled via nodeintegrationinsubframes

### ISSUE THREAD

**Issue by ryankashi** [electron/electron#30207]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, there is no way to use the Webview.send method to a preloaded script running inside of an iframe of a webview.

As it stands now, webview.send can only send messages to the webview directly. None of the iframes located inside of the webview can be communicated to via webview.send, however they ARE able to communicate to the rendererprocess via their own respective ipcRenderer.sendToHost methods.

### Proposed Solution

Allow webview.send to specify which process inside the webview it wants to send the message to, defaulting to the baseline webview source.

### Alternatives Considered

I believe this may be possible to do with webcontents.sendToFrame, while passing in the frameid, located inside of Webframe.routingId however this is extremely clunky and requires you to enable the remote module for access inside of the renderer process which is not desired

### Additional Information

Preload scripts can only be ran inside iframes located inside webviews via the nodeintegrationinsubframes tag.

**Comment by miniak** [comment]
@ryankashi can you please provide feedback on the linked PR?
