### ISSUE TITLE
[Bug]: "second-instance" event fires with requestSingleInstanceLock() even if the 2nd instance is a different app/version

### ISSUE THREAD

**Issue by marcelblum** [electron/electron#30219]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.15

### What operating system are you using?

Windows

### Operating System Version

windows 10 20H2

### What arch are you using?

x64

### Expected Behavior

`second-instance` event should only fire if the user attempts to run the same packaged exe file more than once. Likewise, `requestSingleInstanceLock()` should only return `false` if there is another instance of the same exe file, or at least the same version of the app, running.

### Actual Behavior

`second-instance` event is fired if any electron app with the same package.json `name` launched even if it's a different `version` of the same app from a different exe in a different location, and even if one of the instances is actually not even packaged but rather running in dev mode via electron.exe. And `requestSingleInstanceLock()` returns `false` even if a different version of the same app is already running. At the very least this adds an annoyance to testing for the developer but also poses issues if end users for example want to compare different versions of the same app side by side.

### Additional Information

I can of course prevent the uber confusing behavior of a double click to an old version of my app focusing an already running instance of my new app by checking if `commandLine[0] === process.argv[0]` but this still results in the old version not launching at all in this situation if it too is doing the standard `requestSingleInstanceLock()` check, unless there's a solution I'm missing?

**Comment by marcelblum** [comment]
Thinking about this some more, I guess in theory as a workaround I could do something ugly like
```
app.on('second-instance', (event, commandLine, workingDirectory) => {
   if (commandLine[0] === process.argv[0]) {
      app.releaseSingleInstanceLock();
      require("child_process").spawn(commandLine[0], flagThatTellsOtherVersionOfMyAppToNotRequestLock, {detached: true});
      app.requestSingleInstanceLock();
   } else {
      //normal handling here...
   }
}
```
but, not ideal!

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by marcelblum** [comment]
Ok I'll put a demo together shortly, but I just want to make sure you're not misunderstanding, there's no 3rd party dependency involved here, I'm talking about a bug with the Electron native `app.releaseSingleInstanceLock()` and `app.on('second-instance'...`. This can't be repro'd in a Fiddle because it requires 2 packaged apps to test.

**Comment by marcelblum** [comment]
Hello here is a demo for Windows: https://github.com/marcelblum/electronissue30219

1. clone the demo repo and run `npm install` which will package 2 different versions of a demo Electron app, MyAwesomeApp1.0 and MyAwesomeApp4.0.
2. run `\MyAwesomeApp1.0\out\MyAwesomeApp 1.0.0-win32-x64\MyAwesomeApp 1.0.0.exe` to launch one of the demos
3. with `MyAwesomeApp 1.0.0.exe` running in the background, try to run `MyAwesomeApp4.0\out\MyAwesomeApp 4.0.0-win32-x64\MyAwesomeApp 4.0.0.exe`

Expected behavior: both apps can run side by side simultaneously because they are different exe files with different version numbers in different paths

What actually happens (bug): `app.requestSingleInstanceLock()` erroneously returns false in `MyAwesomeApp 4.0.0.exe`, presumably because the check only looks at the `package.json` `name` field and not the version number or the executable name/path.

**Comment by andymartinwork** [comment]
I've done a bit of reading up on this here:

https://github.com/electron/electron/issues/15304

and here:

https://stackoverflow.com/questions/61924529/how-does-electron-determine-application-identity-for-requestsingleinstancelock

The code is inherited from Chromium.
It's possible to get around this by setting a TMPDIR environment variable, or by changing the package name in package.json with a script. I will be editing the package.json for my beta build, as I feel it's safer.
