### ISSUE TITLE
[Bug]: When compile electron as Windows DLL, DevTools is not working

### ISSUE THREAD

**Issue by alexey1966** [electron/electron#30226]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.10.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

3.0.9

### Expected Behavior

It's possible to open and view UI application

### Actual Behavior

GPU process crashes and dev-tools process can't be created. If I run application with --disable-gpu --disable-software-rasterizer --no-sandbox flags, everything works properly. Probably, the problem is related with new Chromium policies which prevent us from modifying starter code and load electron+chromium as dll.

We use custom exe to prevent our application from Hijacking.

**Comment by alexey1966** [comment]
The next entry point we use for dll:

#ifndef KL_DISABLE_EXPORTS
extern "C" __declspec(dllexport) int RunWithArgs(HINSTANCE instance,
                                                 wchar_t* cmd,
                                                 int argc,
                                                 wchar_t** wargv,
                                                 void* windows_sandbox_info) {
  return DllLoader(instance, cmd, argc, wargv, windows_sandbox_info);
}
 
extern "C" __declspec(dllexport) int RunWithCommandLine(HINSTANCE instance,
                                                        wchar_t* cmd,
                                                        void* windows_sandbox_info) {
  return DllLoader(instance, cmd, 0, nullptr, windows_sandbox_info);
}
#endif

**Comment by Katiemmnl** [comment]
> `[Katiemmnl@gmail.com](Microsoft.com) `
