### ISSUE TITLE
[Bug]: Electron does not respect Windows' "Run: Minimized" property

### ISSUE THREAD

**Issue by v-sviridov** [electron/electron#30234]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 build 19043.1110

### What arch are you using?

x64

### Last Known Working Electron version

-

### Expected Behavior

Application starts in "Minimized" mode.

### Actual Behavior

Application starts in "Normal window" mode.

### Additional Information

Preconditions:
1. Build minimal "HelloWorld" application.
2. Create shortcut on Desktop

Steps to reproduce:
1. Right click on "HelloWorld" icon which is located on Desktop
2. Click "Properties"
3. Click "Shortcut" section
4. Click "Run"
5. Select "Minimized" option
6. Click "Apply" button
7. Click "Ok" button
8. Open "HelloWorld" application again

Actual result:
Application opens in "Normal window" mode

Expected result:
Application opens in "Minimized" mode

Notes: 
How "Minimized" works in others apps (Google and Microsoft apps) https://www.loom.com/share/d5607cc607c74a7aab551bb61d7d7bb6

**Comment by clavin** [comment]
Can confirm that Electron does not respect the "Run" property of a shortcut when it is set to "Minimized" or "Maximized". I believe this only applies to shortcuts as it is under the "Shortcut" tab in the properties window.

**Comment by v-sviridov** [comment]
"Maximized"  works correctly. "Minimized" does not work.
