### ISSUE TITLE
[Bug]: Child BrowserWindow modal on macOS does not respond to setBounds()

### ISSUE THREAD

**Issue by poisonReact** [electron/electron#30236]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.2.3

### What arch are you using?

x64

### Expected Behavior

Offset of the modal window by the specified coordinates

### Actual Behavior

The modal window is always centered on the parent window

### Testcase Gist URL

https://gist.github.com/poisonReact/e9c72d23dfdbee59fc61e27a36e2236e

**Comment by codebytere** [comment]
@poisonReact that's not the way parented modals work or have ever worked - they are centered by macOS. If you try running this on Catalina you'll see it was flush to the top of the window and also unmovable - Big Sur centered it so it _looks_ like it should be its own discrete window but it's not.

You can either
1) Not parent this window 
2) Make it not a modal
