### ISSUE TITLE
[Bug]: incorrect position of traffic lights with custom titlebar

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#30230]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4

### What arch are you using?

x64

### Last Known Working Electron version

v13.0.0-nightly.20210129

### Expected Behavior

Traffic lights are drawn at a `y` delta of 6px from the NSWindow top position

### Actual Behavior

Traffic lights are drawn at a `y` delta of 3px from the NSWindow top position

### Testcase Gist URL

https://gist.github.com/deepak1556/5a186ac86082ab07616cc8503bd1a531

### Additional Information

This first regressed in v13.0.0-nightly.20210201 which points to https://github.com/electron/electron/pull/27489

To verify:

* Open the above app with working version
* Open accessibility inspector
* Check the y position of ElectronNSWindow
* Check the y position of minimize button
* Repeat the above steps for regressed electron version

/cc @zcbenz

**Comment by zcbenz** [comment]
We need to update the default position depending on the macOS version:
https://github.com/electron/electron/blob/3cb06457c4d980fff680248556832301f55af15f/shell/browser/native_window_mac.mm#L1801-L1803
https://github.com/electron/electron/blob/3cb06457c4d980fff680248556832301f55af15f/shell/browser/ui/cocoa/window_buttons_view.mm#L53-L55
