### ISSUE TITLE
[Bug]: Child BrowserWindow modal on macOS has no close, minimize, maximize buttons

### ISSUE THREAD

**Issue by poisonReact** [electron/electron#30232]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.2.3

### What arch are you using?

x64

### Expected Behavior

Child BrowserWindow should have close, minimize, maximize buttons like this:
![103443332-e35f9780-4c66-11eb-891f-d340ab140605](https://user-images.githubusercontent.com/54484694/126612752-e9e11db9-4c30-4deb-a949-50ad2010fe3f.png)

### Actual Behavior

Doesn't have those buttons
![Screenshot 2021-07-22 at 11 49 31](https://user-images.githubusercontent.com/54484694/126613265-3aaf1b1d-46c8-4525-a654-be7513b02c25.png)

### Testcase Gist URL

https://gist.github.com/poisonReact/8d370173538877fa7b0c0f6b02136624

**Comment by codebytere** [comment]
This is intended behavior: macOS Big Sur changes the UI for parented modals but the behavior remains the same.

On Catalina:

![a2791a40-e022-49c6-8d64-2c8493a0254e](https://user-images.githubusercontent.com/2036040/126648800-1ab578e0-9086-4c67-9fdf-34eecd0076fa.jpg)

On Big Sur:

<img width="868" alt="Screen Shot 2021-07-22 at 3 14 47 PM" src="https://user-images.githubusercontent.com/2036040/126648811-0d9740d3-b696-440f-be72-242d66752fc4.png">

Neither have an option to close via traffic light buttons - they're not supposed to. You'll need to call `window.close()` just like you would before Big Sur for this type of child window.

**Comment by SuperKirik** [comment]
@codebytere Hello !

I did not quite understand why it is supposed to be intended behavior ?
If so, how such a window without Close button can be closed at all ?

**Comment by xRyen** [comment]
@SuperKirik Hey

I made a walkaround with a context menu for mac user. So if you're on a mac you can just right click and select "close window" to close child windows that have no traffic light buttons. If you don't know the command to close the window it's:

`childwin.close()`

Hope that'll help you!

**Comment by VanDeny** [comment]
> This is intended behavior. macOS Big Sur changed the UI for parented modals but the behavior and appearance of traffic lights remains the same.

So do I understand it correctly that intended behavior is that user won't be able to close modal window? Oh

**Comment by charise-arter-sony** [comment]
I had this issue today. I just changed modal into false and made sure closeable was true.  I had to do this for the app to work properly on macOS.
