### ISSUE TITLE
[Bug]: Button labels in File choosers are untranslated on Linux in e14

### ISSUE THREAD

**Issue by Kilian** [electron/electron#30247]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 18.04

### What arch are you using?

x64

### Last Known Working Electron version

13.1.7

### Expected Behavior

The buttons in a (native) file dialog read "Cancel"  and "OK"

### Actual Behavior

The buttons in a native file dialog read `gtk-cancel` and `gtk-ok`.

### Testcase Gist URL

https://gist.github.com/Kilian/3de5f404d90d9b12ccaec817fdc4d6da

### Additional Information

Main window has a file input, click it to open the File chooser. Test on Ubuntu between 14.x and 13.x to see the difference. Probably caused by https://github.com/electron/electron/pull/19159

Electron 13.1.7:
![Selection_999(158)](https://user-images.githubusercontent.com/41970/126761063-a5361b8f-d057-406e-bb45-c71d48224b16.png)

Electron 14.0.0-beta.16
![Selection_999(156)](https://user-images.githubusercontent.com/41970/126761068-d6377aee-79f9-47a8-a3b5-f2a96578fda8.png)

**Comment by tristan957** [comment]
Could you tell me how to run the repro gist and I can take a look?

**Comment by tristan957** [comment]
One thing to test in your environment is running the example with GTK_USE_PORTAL=1 *and* not setting the variable at all and seeing if that makes a difference for you.

**Comment by tristan957** [comment]
gtk-cancel = https://docs.gtk.org/gtk3/const.STOCK_CANCEL.html
gtk-open = https://docs.gtk.org/gtk3/const.STOCK_OPEN.html

**Comment by Kilian** [comment]
> Could you tell me how to run the repro gist and I can take a look?
@tristan957 You can open it in [fiddle](https://www.electronjs.org/fiddle)!

**Comment by tristan957** [comment]
It seems like a mistake to have shipped with this bug. I have no clue how Electron internationalization works. If someone could inform me how to get a translated string out of the electron infrastructure, I could fix this. Until then, #19159 should be reverted.

**Comment by tristan957** [comment]
From #gtk with regard to using GTK_STOCK_*...

```
Well. Step one is just stop. Step two is they need to do translations. No way around it
```

**Comment by codebytere** [comment]
@tristan957 working on a fix for this which should be up within a few days.

**Comment by tristan957** [comment]
@codebytere would appreciate a ping when you have a PR up just so I can learn for myself what the proper fix is.

**Comment by codebytere** [comment]
@tristan957 just opened it at https://github.com/electron/electron/pull/30888
