### ISSUE TITLE
[Bug]: crypto.scryptSync is not a function

### ISSUE THREAD

**Issue by dougLSM** [electron/electron#30240]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Version	10.0.19043 Build 19043

### What arch are you using?

x64

### Last Known Working Electron version

13.1.7

### Expected Behavior

crypto.scryptSync function should not return key:

`  const crypto = require('crypto');

  const algorithm = 'aes-192-cbc';
  const password = 'Password used to generate key';
  const key = crypto.scryptSync('whatever', 
  'gfggfg', 32);

  const iv = Buffer.alloc(16, 0); 
  const cipher = crypto.createCipheriv(algorithm, key, iv);
  let encrypted = cipher.update('some clear text data', 'utf8', 'hex');
  encrypted += cipher.final('hex');
  console.log(encrypted);`

### Actual Behavior

error returned when running function: crypto.scryptSync is not a function

### Additional Information

Node.js v14.15.1
Next.JS next@10.2.3 (no typescript)

I've seen other comments here and Stackoverflow.  Most state something about an older version not having the function (" released in NodeJS v10.5.0")

Any insight appreciated.

**Comment by codebytere** [comment]
@dougLSM i ran
```
const crypto = require('crypto');

const keyExample = crypto.scryptSync('GeeksforGeeks', 
                                     'gfggfg', 32);
console.log("The key in the form of buffer is:",keyExample);  
const keyExample2 = crypto.scryptSync('GFG_ARTICLE', 'GFGGFG', 64, { N: 512 });
console.log("The key in the form of buffer is :",keyExample2);
```

with no issue on 13.1.7. Please provide a more complete repro or this issue will be closed - yours above errors with `Error: Invalid key length`

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
