### ISSUE TITLE
[Bug]: the performance of indexeddb in electron is slow than chrome

### ISSUE THREAD

**Issue by luox12** [electron/electron#30258]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

the performance of indexeddb in electron should same with chrome

### Actual Behavior

But the actual is 20+ slower

### Testcase Gist URL

https://github.com/luox12/indexeddb-test

### Additional Information

https://github.com/luox12/indexeddb-test

**Comment by MarshallOfSound** [comment]
In my tests on macOS `throughput` is identical, 2500~ ish on both Chrome and Electron.

Is the difference you're seeing specific to Windows 7?

**Comment by luox12** [comment]
> In my tests on macOS `throughput` is identical, 2500~ ish on both Chrome and Electron.
> 
> Is the difference you're seeing specific to Windows 7?

I only tested on window 7, Is there any implementation difference between windows 7 and macOS？

**Comment by hamidrezakks** [comment]
Hi @MarshallOfSound 
You have to check the build version
Dev version has the same performance

I can share our app repo if you need to investigate it more.

**Comment by hamidrezakks** [comment]
And I'm using macOS by the way.

**Comment by hamidrezakks** [comment]
@clavin what kind of info do you need, I can share my repo if it helps.
