### ISSUE TITLE
[Bug]: desktopCapturer.getSources() only detecting one screen, where screen.getAllDisplays() reports two

### ISSUE THREAD

**Issue by SteveYurka** [electron/electron#30257]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Edition: Windows 10 Home, Version: 21H1, OS build: 19043.1110

### What arch are you using?

x64

### Expected Behavior

desktopCapturer.getSources() should always return the correct amount of screens, eg 'Screen 1' and 'Screen 2' on a two monitor setup.

desktopCapturer.getSources() and screen.getAllDisplays() should always report the same number of screens.

### Actual Behavior

This laptop is using a two screen setup, the laptop screen and one additional monitor. When running desktopCapturer.getSources() only the screen set as the primary monitor can be found, and it's reported as 'Entire screen'. However when running screen.getAllDisplays(), both displays are found. I'm not sure why getSources() reports 1 display while getAllDisplays() reports 2.

When running the app on my personal computer (different to the laptop setup), it correctly reports having 'Screen 1' and 'Screen 2' in a two monitor setup.

The Operating System Version is referencing the laptop where the issue is occurring.

### Additional Information

It possibly seems like this is occurring on laptops, based on the comments/posts in #https://github.com/electron/electron/issues/22364 reporting the same issue.

I dumped the contents of screen.getAllDisplays() and desktopCapturer.getSources() into a log file:

**screen.getAllDisplays() reports:**

```
[2021-07-26 16:16:49.507] [info] 
{
  id: 2480450848,
  bounds: { x: -1920, y: -167, width: 1920, height: 1200 },
  workArea: { x: -1920, y: -167, width: 1920, height: 1160 },
  accelerometerSupport: 'unknown',
  monochrome: false,
  colorDepth: 24,
  colorSpace: '{primaries_d50_referred: [[0.6526, 0.3252],  [0.3303, 0.5945],  [0.1482, 0.0772]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}',
  depthPerComponent: 8,
  size: { width: 1920, height: 1200 },
  displayFrequency: 59,
  workAreaSize: { width: 1920, height: 1160 },
  scaleFactor: 1,
  rotation: 0,
  internal: false,
  touchSupport: 'unknown'
}
[2021-07-26 16:16:49.511] [info]  {
  id: 2528732444,
  bounds: { x: 0, y: 0, width: 1920, height: 1080 },
  workArea: { x: 0, y: 0, width: 1920, height: 1040 },
  accelerometerSupport: 'unknown',
  monochrome: false,
  colorDepth: 24,
  colorSpace: '{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}',
  depthPerComponent: 8,
  size: { width: 1920, height: 1080 },
  displayFrequency: 60,
  workAreaSize: { width: 1920, height: 1040 },
  scaleFactor: 1,
  rotation: 0,
  internal: true,
  touchSupport: 'unknown'
}
```

**desktopCapturer.getSources() reports:**

```
[2021-07-26 16:16:49.539] [info] 
{
  name: 'Entire Screen',
  id: 'screen:3:0',
  thumbnail: {
    toPNG: '[function] function toPNG() { [native code] }',
    toJPEG: '[function] function toJPEG() { [native code] }',
    toBitmap: '[function] function toBitmap() { [native code] }',
    getBitmap: '[function] function getBitmap() { [native code] }',
    getScaleFactors: '[function] function getScaleFactors() { [native code] }',
    getNativeHandle: '[function] function getNativeHandle() { [native code] }',
    toDataURL: '[function] function toDataURL() { [native code] }',
    isEmpty: '[function] function isEmpty() { [native code] }',
    getSize: '[function] function getSize() { [native code] }',
    setTemplateImage: '[function] function setTemplateImage() { [native code] }',
    isTemplateImage: '[function] function isTemplateImage() { [native code] }',
    isMacTemplateImage: false,
    resize: '[function] function resize() { [native code] }',
    crop: '[function] function crop() { [native code] }',
    getAspectRatio: '[function] function getAspectRatio() { [native code] }',
    addRepresentation: '[function] function addRepresentation() { [native code] }'
  },
  display_id: '2480450848',
  appIcon: null
}
```

note: The display_id of the 'Entire screen' correctly matches the Primary Monitor's display_id

**Comment by deepanshushukla** [comment]
@SteveYurka  Is this issue resolved?

**Comment by Galkon** [comment]
Seeing this on electron 31

**Comment by guanjiaming** [comment]
我的电脑上出出现了这种情况，版本为22.3.27

**Comment by guanjiaming** [comment]
我的电脑上也出现了这种情况，版本号为22.3.27；当我连接另一个同型号的显示器时，就识别正常了；或者将外接显示器设置为仅在外接显示器上显示，才能正确显示到。

**Comment by ajieun** [comment]
Is this problem solved? I also have this problem on my win11 laptop.
