### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [electron/electron#30256]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 

### What arch are you using?

x64

### Expected Behavior

When I click the print button the HTML element print as PDF document.
### Actual Behavior

When I click the print button I get the dialogue preview before print.

![222795873_294853262433606_6344040780056049236_n](https://user-images.githubusercontent.com/74948380/126908230-2072d6b6-7787-412d-9df2-c4e9666a505e.gif)

### Additional Information

Dear Support Team, 

I am building desktop app with React, Electron and React-to-print package.

### In my main.js
`win.webContents.print({ silent: true });  // doesn't work`

**Comment by codebytere** [comment]
Dup of https://github.com/electron/electron/issues/29334
