### ISSUE TITLE
Laggy rendering when Nvidia GSYNC is enabled

### ISSUE THREAD

**Issue by felicienfrancois** [electron/electron#3026]
Tested with latest Nvidia drivers with a GSYNC enabled screen (2440 \* 1440, aspect ratio 1).
In Nvidia control panel, when enabling GSYNC for windowed apps I get a huge framedrop in Electron apps (when rendering new pages, moving the mouse, resizing window, css transition and animations).

When testing with the following benchmark http://www.kaizou.org/tools/kaizoumark/, I get 60 fps without gsync (and smooth animation) and 10/15 fps when GSYNC is enabled (and laggy animation).

This setting has no effect on Chrome, even with 4 windows runing the benchmark in split screen.
I have an identical `chrome://gpu` page on Chrome and Electron

**Comment by paulcbetts** [comment]
We've heard reports of this too

**Comment by etiktin** [comment]
According to GSYNC's [FAQ](http://www.geforce.com/hardware/technology/g-sync/faq#q5) you can disable it per game. If you disable it for Electron, does everything works as expected?
If it does, then maybe we (or each app that encounters this issues) can contact NVIDIA and ask them to disable it for now (they disable it for certain games).

**Comment by felicienfrancois** [comment]
@etiktin If I disable it for Electron, everything works as expected, But I have to disable it for each Electron App.
I don't know if NVIDIA can creates a rules that would apply to all Electron apps (when binary have been renamed and its resources edited)

**Comment by etiktin** [comment]
> If I disable it for Electron, everything works as expected

Awesome :) So if customers contact support about this issue we at least know how to assist them.

> I don't know if NVIDIA can creates a rules that would apply to all Electron apps

It's not ideal, but I think for now it's fine that each app maker (that got complaints about GSYNC), ask NVIDIA to disable it for their app.

**Comment by bording** [comment]
As I mentioned on #2767, this is definitely still a problem on the latest version of electron.

**Comment by eedahl** [comment]
I have this issue in both Atom and vscode

**Comment by codebytere** [comment]
Closing due to abandonment.

**Comment by lacymorrow** [comment]
Still an issue

**Comment by iamisti** [comment]
still an issue
