### ISSUE TITLE
[Bug]: require is not defined in webview tag

### ISSUE THREAD

**Issue by jostinsu** [electron/electron#30264]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.5

### What arch are you using?

x64

### Last Known Working Electron version

11.1.1

### Expected Behavior

![image](https://user-images.githubusercontent.com/9781079/126992788-5a212140-34f9-49a2-8deb-a8ce514ec490.png)

<img width="273" alt="wecom-temp-394af9881cf4199f43b806bbe0a75482" src="https://user-images.githubusercontent.com/9781079/126992555-8f120ec2-f5b8-4626-984b-e6c586371107.png">

can use require function in webview tag

### Actual Behavior

![image](https://user-images.githubusercontent.com/9781079/126992854-db0063c2-7f0b-481b-aacf-aced9458be7b.png)

Uncaught ReferenceError: require is not defined

**Comment by xiaofangqie** [comment]
maybe u can try this:

webview.setAttribute("webpreferences", "contextIsolation=false");

**Comment by jostinsu** [comment]
it work, thanks xiaofangqie
