### ISSUE TITLE
[Bug]: MacOS internal warning when using clipboard.readHTML()

### ISSUE THREAD

**Issue by JasonYeMSFT** [electron/electron#30279]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

macOS

### Operating System Version

11.4

### What arch are you using?

x64

### Expected Behavior

Getting html contents in clipboard if available. Otherwise, get empty string indicating that there is no content in html format.

### Actual Behavior

When calling clipboard.readHtml() from main process, it outputs two "warning" like messages about some string encoding issue.

For example,

2021-07-26 15:02:45.359 Electron[31421:23685909] Incorrect NSStringEncoding value 0x8000100 detected. Assuming NSASCIIStringEncoding. Will stop this compatibility mapping behavior in the near future.
2021-07-26 15:02:45.359 Electron[31421:23685909] Incorrect NSStringEncoding value 0x8000100 detected. Assuming NSASCIIStringEncoding. Will stop this compatibility mapping behavior in the near future.

### Additional Information

To reproduce the issue, clone electron-quick-start, set version to 13.1.2, and then copy paste the following code into the main.js

```js
setInterval(async () => {
  try {
    console.log("** read html")
    const hd = clipboard.readHTML();
  } catch (err) {
    console.log(err);
  }
}, 1000);
```

run electron and monitor the main process console output.

The 2nd half of the string infers that this API may break at some point.

**Comment by codebytere** [comment]
@JasonYeMSFT hmm - i'm also running 11.4 and the default fiddle with
```
setInterval(async () => {
    try {
      console.log("** read html")
      const hd = clipboard.readHTML();
    } catch (err) {
      console.log(err);
    }
  }, 1000);
```

added to the main process and see no such logs:

<img width="765" alt="Screen Shot 2021-07-27 at 9 16 08 AM" src="https://user-images.githubusercontent.com/2036040/127112136-8011f9c5-c39a-4f23-afc3-156bae66225f.png">

**Comment by JasonYeMSFT** [comment]
@codebytere you may need to change contents in the clipboard. Could you trying running electron with that and then copy the following text?

```
() tgus afbykaywe ()
./bkyorlfahkj “awefa”
```

**Comment by JasonYeMSFT** [comment]
Maybe it is because of TextEdit (the built-in mac text editor). I copied the text from there which adds something in html format to the clipboard.

**Comment by nornagon** [comment]
I also can't reproduce this with @codebytere's example when copying text from TextEdit.

That said, we delegate all our clipboard operations to Chromium, so I believe this is likely an upstream issue. Does it still happen on 14.x?

**Comment by JasonYeMSFT** [comment]
@nornagon I tried v14.0.0-beta16 and it still reproduces. Did you copy exactly the string I provided from TextEdit? Our application uses clipboard a lot. Even though not causing any functional issue, the warning message makes our main process output very messy. Is there a potential way to suppress it?

**Comment by nornagon** [comment]
@JasonYeMSFT 
![image](https://user-images.githubusercontent.com/172800/127531505-d4249778-0a44-4d10-8216-9b0a7f52d017.png)

**Comment by JasonYeMSFT** [comment]
Hmmm. I'll try to get another mac machine to see if I can reproduce there. I will close this issue if I cannot.

**Comment by JasonYeMSFT** [comment]
Just curious, are you using M1 mac or Intel chip mac?

**Comment by JasonYeMSFT** [comment]
I happened to get access to someone's new M1 macbook air and this issue still reproduces.
