### ISSUE TITLE
[Bug]: Aspect ratio not respected on maximise/zoom on Mac M1 , gets extra width equivalent to window title bar

### ISSUE THREAD

**Issue by wasitshafi** [electron/electron#30277]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

macOS

### Operating System Version

macOs Big Sur version 11.2(20D64)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Aspect ratio should be maintained if we maximise  window.

### Actual Behavior

I have created a new BrowserWindow with ```fullscreenable: false```  & ```win.setAspectRatio(1)``` so that window shouldn't be able to have 'full screen mode' to make sure it maintains aspect ratio of 1, while once i  click on maximise button or double click on title bar it looses aspect ration of <b>1</b> as window width increases(28px) equivalent to height of window title bar(title bar is not hidden/auto-hide mode).Every time i resize window with cursor, it always maintains aspect ratio.

### Testcase Gist URL

https://gist.github.com/wasitshafi/68086a64c780040628aea3c071350390

### Additional Information

I have also tried to use ```event.preventDefault()``` on maximize event, but found later it's not working on  maximize/minimize unlike close event whose default behaviour can be prevented.

**Comment by codebytere** [comment]
hi @wasitshafi - Electron Fiddle requires a reproducible sample that runs in the Fiddle app itself. For example - yours should look like this: https://gist.github.com/4f9d1e9a9ded5614126bc89e045925e0. This was of course not hard to correct but in the future it will help us a lot for you to do this :)

**Comment by wasitshafi** [comment]
Hi! @codebytere, thanks for your response have a look at Electron Fiddle App Gist - https://gist.github.com/wasitshafi/62e2189d0e698dfdd55d979bfbac102e
Demo:
![Electron_Issue#30277](https://user-images.githubusercontent.com/32488541/127221069-d5992a42-1564-4eda-9313-66290a177d6c.gif)

**Comment by codebytere** [comment]
@wasitshafi thanks for the update! https://github.com/electron/electron/pull/30305 should fix the issue.

**Comment by wasitshafi** [comment]
> @wasitshafi thanks for the update! #30305 should fix the issue.

@codebytere You're welcome
