### ISSUE TITLE
[Feature Request]: How to get localStorage directly from session like cookie ?

### ISSUE THREAD

**Issue by zilchhu** [electron/electron#30282]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

session object has cookie object, but does not have localstorage object .
If i want to access localstorage , i have to use webcontents executeJavascript, this is not useful in a situation that i want to get localstorage from partition   

### Proposed Solution

add localStorage object like cookie to session 

### Alternatives Considered

add fromPartition method to webContent

### Additional Information

.

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
