### ISSUE TITLE
[Bug]: Crash in content::WebContentsImpl::GetNativeView()

### ISSUE THREAD

**Issue by t57ser** [electron/electron#30287]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.985

### What arch are you using?

x64

### Expected Behavior

No crash

### Actual Behavior

Crash

![grafik](https://user-images.githubusercontent.com/10595986/127132915-fe3f483b-2d98-43a6-b312-cb85f372f125.png)
[7c96ff3a-53d7-4590-9456-ced7be095744.zip](https://github.com/electron/electron/files/6884422/7c96ff3a-53d7-4590-9456-ced7be095744.zip)

### Additional Information

Considering the crash log is mentioning "UpdateDraggableRegions". I assume the crash is happening when using drag/drop api (standard browser feature within renderer) and then closing the window. 
The crash happened for the following case:
(app behavior)
- User drags element (standard drag/drop js code is used here)
- Some condition is fullfilled (app logic)
- Window is closed
- => crash

**Comment by t57ser** [comment]
Seems to work in 13.1.2
Crashes in 13.1.3
I assume this introduced the bug: https://github.com/electron/electron/pull/29734 since the commithas something related to UpdateDraggableRegions which is also mentioned in the crash log

**Comment by codebytere** [comment]
@t57ser thanks - got a PR up to fix!
