### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rodolphonetto** [electron/electron#30281]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19043.1110

### What arch are you using?

x64

### Expected Behavior

After installing johnny-five and serialport I do a rebuild and the application should not crash, I really don't know what to put here, it should just not crash =/

### Actual Behavior

After installing johnny-five and serialport I do a rebuild and thn the application crashs after showing `Repl Initialized`, I read that this is a problem about `process.stdin`  and I need to use that code as this post says https://t.co/hZqNxE99si?amp=1

```var Readable = require("stream").Readable;  
var util = require("util");  
util.inherits(MyStream, Readable);  
function MyStream(opt) {  
  Readable.call(this, opt);
}
MyStream.prototype._read = function() {};  
// hook in our stream
process.__defineGetter__("stdin", function() {  
  if (process.__stdin) return process.__stdin;
  process.__stdin = new MyStream();
  return process.__stdin;
});
```

But that code gives me that error 

```
Uncaught TypeError: Cannot redefine property: stdin
    at process.__defineGetter__ (<anonymous>)
    at eval (webpack-internal:///./src/main.js:35)
    at Module../src/main.js (app.js:1460)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.1 (app.js:1617)
    at __webpack_require__ (app.js:849)
    at checkDeferredModules (app.js:46)
    at app.js:925
    at app.js:928```

### Testcase Gist URL

_No response_

### Additional Information

_No response_

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
