### ISSUE TITLE
[Bug]: Electron Desktop app opening external URL - with Oauth shows blank screen

### ISSUE THREAD

**Issue by harish-madugula** [electron/electron#30310]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^9.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

hey there, 
trying to use a login dialog with Microsoft oAuth, 
please try typing **user profile** and click on sign in. 
**the expected behaviour is to open the OAuth link in the same app, as a new window and show the login screen, but the current app is showing a blank red screen. **

below is the code snippet, 

`"use strict";

// Mod of Electron
const electron = require("electron");
var path = require("path");

// Module that controls the application
const app = electron.app;
const Menu = electron.Menu;
const Tray = electron.Tray;

// Module to create window
const BrowserWindow = electron.BrowserWindow;

// Global declaration so that main window is not GC
let mainWindow;

// Close all windows closed
app.on("window-all-closed", function () {
  if (process.platform != "darwin") {
    app.quit();
  }
});

// Execute after completion of initialization of Electron
app.on("ready", function () {
  // Main screen display. You can specify the width and height of the window
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: false,
    },
    backgroundColor: "#B4160B",
  });
 
  mainWindow.loadURL("https://fullscreenbotdemo.z13.web.core.windows.net/");

  // Close the application when the window is closed
  mainWindow.on("closed", function () {
    mainWindow = null;
  });
});
`

### Actual Behavior

mainWindow.loadURL is opening the app which is a chatbot and typing **user profile** gives us a dialogue with a button sign in.

In a normal browser, we are using target="_blank" to open it in a new tab, but in the electron app, its a blank screen in-app browser.

Are there any other ways to do this or, any workarounds instead of loadURL??

thanks in advance

**Comment by nornagon** [comment]
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).

**Comment by gavan1** [comment]
This is still an issued with ver 34.

If this wasn't prematurely closed we might have as it actually solved.
There is a lack of documentation on how to solve oauth login redirects... One might wonder why this isn't even working?
