### ISSUE TITLE
[Bug]: The path to the extension in 'loadExtension' must be absolute

### ISSUE THREAD

**Issue by SirReadsALot** [electron/electron#30324]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### What arch are you using?

x64

### Expected Behavior

so I basically tried loading an extension through sessions
I did these 2 things:
`win.webContents.session.loadExtension("%LOCALAPPDATA%/Google/Chrome/User Data/Default/Extensions/cmlbeiacmcbdiepcenjmhmkclmffbgbd/1.0.33_0").then(console.log("The extension is loaded!"))`
and 
`const os = require("os")`
`win.webContents.session.loadExtension(`C:/Users/${os.userInfo().username}/Google/Chrome\User Data/Default/Extensions/cmlbeiacmcbdiepcenjmhmkclmffbgbd/1.0.33_0`).then(console.log("The extension is loaded!"))`

I expected Electron to load in the extension from both of those directories but the actual behaviour is said below

### Actual Behavior

after doing `electron .` it right away throws an error that says 
`(node:15324) UnhandledPromiseRejectionWarning: Error: The path to the extension in 'loadExtension' must be absolute`, 
even though the path IS absolute.

**Comment by nornagon** [comment]
You have to expand `%LOCALAPPDATA%` yourself; the `%` syntax is a cmd quirk and not recognized by other systems, generally.

**Comment by SirReadsALot** [comment]
@nornagon 
I also tried doing `const os = require("os")
win.webContents.session.loadExtension(C:/Users/${os.userInfo().username}/Google/Chrome\User Data/Default/Extensions/cmlbeiacmcbdiepcenjmhmkclmffbgbd/1.0.33_0).then(console.log("The extension is loaded!"))`

but this also threw the same error, how do I fix it then?
even putting my computer's name instead of using the OS module didn't work

**Comment by nornagon** [comment]
The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.
