### ISSUE TITLE
What is the problem with the black screen after the electron starts up automatically?

### ISSUE THREAD

**Issue by glk-hll** [electron/electron#30338]
detailed process:
The black screen appears after the electron is started. Press the shortcut key `commandorcontrol + F8` to open the console, but the `globalshortcut.register ('commandorcontrol + F8 ')` event is triggered. Under normal conditions, manually open the program, and everything is normal.

"electron": "^13.1.7",
"electron-builder": "^22.10.5",
"OS": Windows10 64bit

**Comment by clavin** [comment]
Hi!

I can't get the black screen to appear following your steps. I can't find documentation for the Control + F8 shortcut on Windows 10. This may be a problem with other software on your computer.

I am going to close this issue for now. If you figure out this is a bug with Electron, feel free to open a new issue using the 🐛 Bug template.
