### ISSUE TITLE
[Bug]: electron 在win7打包的客户端下偶发性会白屏

### ISSUE THREAD

**Issue by www5255977** [electron/electron#30348]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.4.0

### What operating system are you using?

Windows

### Operating System Version

windows 7 

### What arch are you using?

x64

### Last Known Working Electron version

10.4.0

### Expected Behavior

我希望 所有 electron  打包的客户端 不要产生白屏

### Actual Behavior

当前偶发性的 electron  打包的客户端在开启的时候界面全部白屏  并且有错误输出 Exception thrown during bootstrapping
Error installing extension 'extensions::SafeBuiltins'.
[6108:0730/163552.511:FATAL:v8_initializer.cc(95)]
[4840:0730/163552.836:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read propert
y 'instance' of undefined", source: devtools://devtools/bundled/devtools_app.htm
l?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@85104d2dfc
96eac92da3f8019998debdcc240d0d/&can_dock=true&toolbarColor=rgba(223,223,223,1)&t
extColor=rgba(0,0,0,1)&experiments=true (1)

### Additional Information

相关环境  vue 2.0 webpack

**Comment by tsoil** [comment]
nb 写中文

**Comment by Ronbb** [comment]
https://github.com/electron/electron/issues/28487
