### ISSUE TITLE
Problem with the UNDELEGATE

### ISSUE THREAD

**Issue by Fokia84** [electron/electron#30358]
Hi,
I'm using Crypto.org chain Desktop wallet v0.2.2 on a Mac with OSX El Captain.
I've connected my Ledger NanoX; I've some deledated CRO and I want to undelegate but I receive this Error:

![screen](https://user-images.githubusercontent.com/84899680/127696199-85024816-2973-4467-b51d-b5f3d82fad70.jpg)

What's the problem?

Thanks in advance,
Giacomo

**Comment by Fokia84** [comment]
![screen](https://user-images.githubusercontent.com/84899680/127696300-d9b6fddc-2709-4593-a9d9-55af663e3c1a.jpg)
[screen.pdf](https://github.com/electron/electron/files/6909422/screen.pdf)

**Comment by MarshallOfSound** [comment]
This appears to be an issue with a specific Electron app rather than Electron itself
