### ISSUE TITLE
Questions about quitting and closing...

### ISSUE THREAD

**Issue by MRayermannMSFT** [electron/electron#30357]
I have some questions related to quitting and closing which I can't seem to find clear answers for in the docs/am seeking clarification:

1. For a MenuItem with [role](https://www.electronjs.org/docs/api/menu-item#roles) `quit`, is that the same as having the MenuItem invoke `app.quit()`?
2. For a MenuItem with [role](https://www.electronjs.org/docs/api/menu-item#roles) `close`, is that the same as having the MenuItem invoke `browserWindowInstance.close()`?
3. Is clicking on a window's X/red circle/close button the same as `window.close()`?
4. After `app.quit()` is called:
    1. Is the order in which windows are tried to be closed deterministic?
    2. Are windows tried to be closed in parallel or one after another?
    3. If one after another, then if a window fails to close (for example via `preventDefault` on its `close` event), then does Electron still try to close subsequent windows?

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
