### ISSUE TITLE
[Bug]: macos more than 10.5, T、there is no appropriate version of Mine to build window application

### ISSUE THREAD

**Issue by zmheang** [electron/electron#30368]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

lasted

### What operating system are you using?

macOS

### Operating System Version

macOs 11.2

### What arch are you using?

x64

### Expected Behavior

There is no appropriate version of Mine to use

### Actual Behavior

There is no appropriate version of Mine to use

**Comment by clavin** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
