### ISSUE TITLE
[Bug]: v10.1.2 electron-v10.1.2-darwin-arm64.zip is gone? 

### ISSUE THREAD

**Issue by kafka-yu** [electron/electron#30365]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

It should be able to do packing.the 

### Actual Behavior

![image](https://user-images.githubusercontent.com/3942409/127815250-e3ff2e0b-09b7-4d31-b10b-7d7145d0c53e.png)

### Additional Information

I've checked for v10.4.7, which also has this issue. Any reason that the arm64 file is missing?
Thanks

**Comment by ckerr** [comment]
I _think_ Electron 11 was the first release branch that included darwin-arm64 support. That's at

https://github.com/electron/electron/releases/download/v11.0.0/electron-v11.0.0-darwin-arm64.zip
