### ISSUE TITLE
[Bug]: chrome-error://chromewebdata eror page is not customizable

### ISSUE THREAD

**Issue by zwd759648544** [electron/electron#30369]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.3

### What operating system are you using?

macOS

### Operating System Version

windows&mac

### What arch are you using?

x64

### Last Known Working Electron version

11.4.3

### Expected Behavior

chrome-error://chromewebdata  发生错误的时候 能够支持定制或友好提示的页面

### Actual Behavior

chrome-error://chromewebdata  发生错误的时候 没有给一个可以定制或友好提示的页面，是个空白页面表现很不友好

**Comment by ckerr** [comment]
Google translate:

## Expected Behavior

chrome-error://chromewebdata 发生错误的时候 能够支持定制或友好提示的页面

> chrome-error://chromewebdata When an error occurs, a page that can support customization or friendly prompts 

## Actual Behavior

chrome-error://chromewebdata When an error occurs, it does not give a page that can be customized or friendly, it is a blank page and it is very unfriendly

**Comment by nornagon** [comment]
Ref https://github.com/electron/electron/pull/25128

**Comment by zerooverture** [comment]
An imperfect solution is to modify the page in preload by matching `chrome-error://chromewebdata`
