### ISSUE TITLE
[Bug]: webview cannot receive message via postMessage if create webview element while parent element is display: none

### ISSUE THREAD

**Issue by zhaozhongyu** [electron/electron#30367]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.2.1

### What operating system are you using?

Windows

### Operating System Version

windows 10.0.19041

### What arch are you using?

x64

### Last Known Working Electron version

null

### Expected Behavior

try to create webview and postMessage via $0.contentWindow.postMessage, it should receive message 

### Actual Behavior

can not receive message if create webview element while parent element is display: none

### Additional Information

![image](https://user-images.githubusercontent.com/8148957/127836083-950c317e-4926-4968-8619-cad80be34ed4.png)

**Comment by clavin** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by miniak** [comment]
This is by design
