### ISSUE TITLE
[Bug]: Cannot open external links from pdf file

### ISSUE THREAD

**Issue by Abdallah-Hussien** [electron/electron#30377]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

ia32

### Expected Behavior

I created a new electron project from [electron-quick-start](https://github.com/electron/electron-quick-start)
I tried to view a pdf file with internal links (to another page in the same file) & external links (to normal link or webpage)

![electron issue](https://user-images.githubusercontent.com/87116208/127983356-be453d16-6bc4-4521-ab50-4dd01c7b3256.png)

### Actual Behavior

The external links are not clickable (not navigate to the required page). but the internal links are clickable & navigate to the required page.

**Comment by nornagon** [comment]
This is fixed by https://github.com/electron/electron/pull/30069.
