### ISSUE TITLE
[Feature Request]: Can add the 'did-redirect-navigation' event listener to webview tag as webContents?

### ISSUE THREAD

**Issue by Aaronphy** [electron/electron#30378]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

In our product ,we should listen the redirect event of the url in the webview tag.

### Proposed Solution

We hope that webview has the dom event listener just like:https://www.electronjs.org/docs/api/web-contents#event-did-redirect-navigation 

### Alternatives Considered

I have no idea 

### Additional Information

nothing

**Comment by miniak** [comment]
@Aaronphy can you please provide feedback on the linked PR?
