### ISSUE TITLE
[Bug]: Devtools element inspector crashes with 3221225477 errno.

### ISSUE THREAD

**Issue by olexme** [electron/electron#30379]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise, Windows Server 2016

### What arch are you using?

ia32

### Last Known Working Electron version

9.4.0

### Expected Behavior

Be able to inspect any HTML on 32 bit builds.

### Actual Behavior

The 32bit electron versions crashes while inspecting some deeper nested HTLM elements.
The [electron-quick-start fork example ](https://github.com/olexme/electron-quick-start.git) provided contains minimum scarp of Angular Material page (e.g https://material.angular.io/components/button/overview) to crash the electron. The example contains only HTML elements without any styling and fonts. The app crashes while inspecting the most nested SPAN element inside the BUTTON. It can be done either using DevTools "arrow DOM inspector", or in DOM tree opening and clicking the most nested SPAN element.

### Testcase Gist URL

https://github.com/olexme/electron-quick-start.git

**Comment by nornagon** [comment]
Please attach a crash dump. You can collect them by adding the following snippet to your main process code, before app.whenReady:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by olexme** [comment]
Crashdumps attached here :
[Crashpad.zip](https://github.com/electron/electron/files/6928819/Crashpad.zip)

**Comment by olexme** [comment]
I've just checked v13.1.8 - the error doesn't exist anymore there.

**Comment by deepak1556** [comment]
Fixed by https://github.com/electron/electron/pull/29474
