### ISSUE TITLE
[Question]: how to compress a folder faster in electron

### ISSUE THREAD

**Issue by luhc228** [electron/electron#30396]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.15

### What operating system are you using?

macOS

### Operating System Version

macos 11

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

12.0.0

### Expected Behavior

I am a  beginner to use electron to build a app.

Now I use the [gulp-zip](https://www.npmjs.com/package/gulp-zip) to compress a folder which is about 500M in an electron app. It took about three minutes to completely compress the folder. When I write a `index.js` to run the same code and run `node index.js`, it only took about one minute to completely compress the folder.

My code is [here](https://github.com/appworks-lab/toolkit/blob/release-next/main/npm/dependency/createCustomGlobalDepsDir.ts)

I want to know that if there is a memory limit in the electron or other reason.

I hope you can give me some help.

### Actual Behavior

none

### Testcase Gist URL

https://github.com/appworks-lab/toolkit/blob/release-next/main/npm/dependency/createCustomGlobalDepsDir.ts

**Comment by clavin** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
