### ISSUE TITLE
[Bug]: webContents from -add-new-contents return incorrect UserAgent in page

### ISSUE THREAD

**Issue by gucheen** [electron/electron#30395]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 7, Windows 10, MacOS

### What arch are you using?

x64

### Last Known Working Electron version

13

### Expected Behavior

After set custom useragent with `session.defaultSession.setUserAgent` or `webContents.setUserAgent` to the webContents from `-add-new-contents` event.
`window.navigator.userAgent` should return the custom userAgent.

### Actual Behavior

`webContents.getUserAgent()` return the correct custom userAgent. `window.navigator.userAgent` return the default Electron userAgent, however.
This webContents was created by `-add-new-contents`.

### Testcase Gist URL

https://gist.github.com/698483e171934fba009ab6f2ebdbd586

**Comment by miniak** [comment]
@gucheen `-add-new-contents` is private API, why are you using it?

**Comment by gucheen** [comment]
> @gucheen `-add-new-contents` is private API, why are you using it?

As mentioned in https://github.com/electron/electron/issues/28374#issuecomment-851267270, currently `setWindowOpenHandler` is't able to set `newGuest`(or add a `webContents` parameter in event callback).

This makes some trouble when someone use `const window = window.open()` in a webpage.
