### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dongshihao666** [electron/electron#30408]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.0.0

### What operating system are you using?

macOS

### Operating System Version

macOs 11.4

### What arch are you using?

x64

### Last Known Working Electron version

12.0.0

### Expected Behavior

![image](https://user-images.githubusercontent.com/29971202/128295285-864ef597-ac01-426f-8200-bc629ce5f126.png)
![image](https://user-images.githubusercontent.com/29971202/128295314-0f58559d-92cf-4ede-b4e8-877c632026ef.png)
![image](https://user-images.githubusercontent.com/29971202/128295334-94d2c2df-74e1-4d61-9f7c-167a632401d2.png)

Error reporting using ipcmain

### Actual Behavior

进程通讯失败

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
