### ISSUE TITLE
[Bug]: Mouse doesn't work for frameless browserwindows

### ISSUE THREAD

**Issue by Jelmerro** [electron/electron#30402]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0-beta.18

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 34

### What arch are you using?

x64

### Last Known Working Electron version

13.1.8

### Expected Behavior

Frameless windows should have mouse interaction, similar to regular windows.

### Actual Behavior

Every single regular mouse event is completely ignored, on all levels thinkable. Selection doesn't work, double-clicking doesn't, input fields don't work, and even custom events on the window/body don't fire at all.. The keyboard does work as expected, so the app is not frozen and hasn't crashed.

### Additional Information

No gist needed, just add `"frame": false` to any basic electron app to break all mouse functionality when using the latest beta.

**Comment by clavin** [comment]
Thanks for the bug report! I was able to repro this on Electron's quick start example, only edited to add `frame: true`.

Did a manual bisect, this broke some time between [v15 nightlies 2021-06-18 to 2021-06-21](https://github.com/electron/electron/compare/v15.0.0-nightly.20210618...v15.0.0-nightly.20210621).

**Comment by ckerr** [comment]
I've confirmed that reverting https://github.com/electron/electron/pull/29721 fixes this problem, though of course doing so unfixes 611.

Interestingly, 29721 got backported [to 12](https://github.com/electron/electron/pull/29799) and [to 13](https://github.com/electron/electron/pull/29800) back in June; but happily, the latest stables in those branches **do not** have this regression. In addition to not stable builds, this also may be a useful clue about what's causing the regression in the nighlies, e.g. maybe FramelessView::ResizingBorderHitTest() is being reached via a different codepath now.

**Comment by ckerr** [comment]
I did a little more testing -- bisecting not just the repro, but also the patch in Patching #29721 into 14.0.0-beta.4 results in a working build, while patching @29721 into 14.0.0-beta.5 results in the unclickable bug described here.

Looking at https://github.com/electron/electron/compare/v14.0.0-beta.4...v14.0.0-beta.5, by far the most likely candidate to me looks like the https://chromium-review.googlesource.com/c/chromium/src/+/2485774 refactor that was part of https://github.com/electron/electron/pull/29594. My guess is there's some code path that triggered the `OnSizeConstraintsChanged()` call at https://source.chromium.org/chromium/chromium/src/+/main:ui/views/widget/widget_delegate.cc;l=321;drc=d71b784f527b3a422850a53787662a9722d465b1 in 14.0.0-beta.4 that's no longer being tickled in v14.0.0-beta.5.

**Comment by ckerr** [comment]
@Jelmerro is right that it only takes a few seconds to make a repro for this, but in case anyone's doing review on #30447 and wants to test it in fiddle, https://gist.github.com/ckerr/60f98574e1ba63cede54f6799669d596 is a pre-rolled testcase -- it's the quick-start template with `frame: false` added.

To repro, try clicking on any of the words to highlight them. If they're clickable, it works.

**Comment by Hacksore** [comment]
@IZUNA894 I have this same issue in https://github.com/Hacksore/overlayed on windows 11.

I've even tried on `13.x`, `15.x`, and even `16.0.0-beta.7` and still see the same issue where my mouse won't be picked up in a `BrowserWindow` with `frame: false` and `transparent: true`.

I'm wondering if we should open a new standalone issue for this.

**Comment by IZUNA894** [comment]
@Hacksore  yes , we should open it as a new issue. 
meanwhile , while working on it , i found more bugs in it , for example menu accelerators are not working. i had to used global shortcuts for it. but they are not what exactly i want. so i had to compromise with my app functionality.

electron still needs lot of testing and debugging.

**Comment by Hacksore** [comment]
@IZUNA894 I actually found that my issue was caused by applying the css property `-webkit-app-region: drag;` to the whole window which was what was stealing the focus of the mouse.

Is this possibly the same issue you have as well?

**Comment by IZUNA894** [comment]
@Hacksore  no i didn't use any css at that point. Is this css comes by default and i have  to remove it? if yes please specify how?
thanks in advance!
