### ISSUE TITLE
 [HTTPError]: Response code 403 (Forbidden) unabale to install electron in proxy server

### ISSUE THREAD

**Issue by skyshine999** [electron/electron#30409]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

6.0.0

### Expected Behavior

able to install electron 12.0.2

### Actual Behavior
NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0'
then it's showing that [HTTPError]: Response code 403 (Forbidden)
[HTTPError]: Response code 403 (Forbidden)
    at EventEmitter.<anonymous> 
    at EventEmitter.emit (events.js:196:13)
    at EventEmitter.emit (domain.js:494:23)

### Additional Information

i try this command npm install electron@12.0.2 --dev

**Comment by nornagon** [comment]
This is not a bug with Electron, this is a problem with your network environment.
