### ISSUE TITLE
[Bug]: Documentation & TypeScript Types inaccuracte for `set systemPreferences.appLevelAppearance`

### ISSUE THREAD

**Issue by nathanlesage** [electron/electron#30413]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.8

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

After attempting to reset the appLevelAppearance from either `light` or `dark` to using the operating system appearance does not work by setting it to `unknown`. That gave me a "conversion error".

Taking a look into the source code for the `systemPreferences` API, one can see that there are in fact _three_ possible ways of setting the `appLevelAppearance` – light, dark and one being undocumented – namely the `null` value:

https://github.com/electron/electron/blob/4703dc0a1d812a0ad66c764868352e62ea69968c/shell/browser/api/electron_api_system_preferences_mac.mm#L44-L47

In fact, the `appLevelAppearance` can successfully be reset by using the following line of code:

```js
systemPreferences.appLevelAppearance = null
```

I tested this and it worked out of the box.

### Actual Behavior

However, upon trying this and set the appLevelAppearance to `null`, it turned out the Electron types (used for TypeScript) give me an error. But they do *not* give me an error using the wrong value of `'unknown'` which throws the above-mentioned "conversion error".

I recommend the following updates:

1. Update the Electron typings so that the `appLevelAppearance` setter accepts `null` as a valid property to set the app-level appearance to `nil`
2. Update the documentation to reflect that you can reset the `appLevelAppearance` at runtime by setting it to `null`

Further, I think it might be more appropriate to consolidate getter and setter and, instead of returning "unknown" return the JavaScript representation of `nil`, namely: `null` (or even `undefined`). Alternatively, the setter might accept `unknown` and convert that internally to `nil`.

**Comment by nathanlesage** [comment]
bump

**Comment by MarshallOfSound** [comment]
This is a limitation of typescript itself (see https://github.com/microsoft/TypeScript/issues/2521)

It's not possible for a getter and setter of a property to have incompatible types (which our API does).  In order to be TS compliant you can use the `setAppLevelAppearance()` and `getAppLevelAppearance()` methods which are typed correctly
