### ISSUE TITLE
[Bug]: Running Electron + React app on browser giving error window.require() is not a function on the Chrome browser, but working as desktop app

### ISSUE THREAD

**Issue by nitschandel** [electron/electron#30411]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

macOS

### Operating System Version

macOs Big Sur | Version 11.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I expected using electron JS with react will have a single code base and will work both as web application and desktop application. But its not working as web application on the browser.

### Actual Behavior

Requirement - Run electron app in browser as well as in pc using single code base.

Problem Facing - Able to run in pc as a desktop application but when running localhost:3000 in a browser(Chrome in my case) facing some issue related to the window.require . Tried multiple solutions on the web but no success as of now.

Use Case - Using ipcMain and ipcRenderer to communicate between React application and main.js file in electron js for pc application only. (In browser I need to run this as a simple web application without electron feature(ipcMain and ipcRenderer communication) but I need the application to run in the browser as well using single code base)
Browser Image:
![N2WQ7](https://user-images.githubusercontent.com/7268350/128336133-57a4fb5a-ff75-4803-9b78-8bd7ab61972f.jpeg)

Package.json:
{
  "name": "electron-react-redux",
  "version": "0.1.0",
  "private": true,
  "main": "main.js",
  "dependencies": {
    "@material-ui/core": "^4.12.3",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "pouchdb": "^7.2.2",
    "pouchdb-find": "^7.2.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.4",
    "react-scripts": "4.0.3",
    "redux": "^4.1.1",
    "redux-saga": "^1.1.3",
    "uuid": "^8.3.2",
    "web-vitals": "^1.0.1"
  },
  "devDependencies": {
    "concurrently": "^6.2.0",
    "electron": "^13.1.7",
    "electron-packager": "^15.3.0",
    "wait-on": "^6.0.0"
  },
  "scripts": {
    "start": "concurrently cross-env BROWSER=none node server 'yarn react-start' 'wait-on http://localhost:3000/ && yarn electron-start'",
    "build": "yarn react-build && yarn electron-build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "react-start": "BROWSER=none react-scripts start",
    "electron-start": "ELECTRON_IS_DEV=1 electron .",
    "react-build": "react-scripts build",
    "electron-build": "electron-packager ./ --overwrite"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

### Additional Information

As I'm new to electron js please help me with some valuable input. If someone has faced and resolved this issue please guide me in the right direction.

If the question is not cleared or anything else is required please let me know.

**Comment by MarshallOfSound** [comment]
You're trying to use Electron APIs from a browser, this is simply a thing doesn't doesn't exist.  Electron APIs can only be loaded inside an Electron app, there is no way to use them other places (such as your browser)

**Comment by nitschandel** [comment]
So how do we build an electron app, running along side the React web application using a single base code and calling APIs to store data in redux?
