### ISSUE TITLE
[Bug]: des-ede3 cipher missing from Electron v13

### ISSUE THREAD

**Issue by luispureza** [electron/electron#30428]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.8

### What operating system are you using?

macOS

### Operating System Version

Catalina (10.15.7)

### What arch are you using?

x64

### Last Known Working Electron version

12.0.15

### Expected Behavior

Cipher `des-ede3` should be supported. It was working on Electron v12.0.15 and I couldn't find any announcement of it being deprecated.

Oddly, this file exists: https://github.com/electron/electron/blob/v12.0.16/patches/boringssl/expose_des-ede3.patch, and so does this: https://github.com/electron/electron/blob/main/patches/boringssl/expose_des-ede3.patch. This one doesn't, though: https://github.com/electron/electron/blob/v13.1.8/patches/boringssl/expose_des-ede3.patch.

It just looks like support for this cipher was introduced sometime during v12.x and never got backported to v13.x.

### Actual Behavior

Cipher `des-ede3` is not supported anymore. The following code:

```
import crypto from 'crypto';
...
crypto.createCipheriv('des-ede3', crypto.randomBytes(24), null);
```
fails with:
```
Error: Unknown cipher
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:103:19)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:123:10)
```

**Comment by codebytere** [comment]
Opened a PR: https://github.com/electron/electron/pull/30453

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/30453
