### ISSUE TITLE
[Bug]: Child windows' width increases when it is restored after restoring the parent window if its width was close to the minimum

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#30429]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7, 11.4.10

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

When I minimize a child window, minimize the main window, and then restore the main window, I expect that when the child window is restored, it retains the same size from before.

### Actual Behavior

The width of the child window roughly doubles.

### Testcase Gist URL

https://gist.github.com/fce159fd81d3d8692e943723e73cda0b

### Additional Information

The gist above is using Electron 11, but here is the Electron 13 version:

1. start main.js
2. open window
3. shrink the child window's width to the minimum and minimize child window
4. minimize parent window
5. restore parent window
6. observe that the child window's width increased

main.js:
```
const {app, BrowserWindow } = require('electron')

async function createWindow () {
  const mainWindow = new BrowserWindow({ webPreferences: { nativeWindowOpen: true }});
  mainWindow.on("closed", () => app.quit());

  await mainWindow.loadFile('index.html');

   mainWindow.webContents.setWindowOpenHandler(() => {
    return {
      action: "allow",
      overrideBrowserWindowOptions: {
        parent: mainWindow
      }
    }
  });
}


app.whenReady().then(() => {
  createWindow()
  
  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

index.html:
```
<button onclick="window.open('https://google.com', 'a')">Open Window</button>
```

![windowsize](https://user-images.githubusercontent.com/6374473/128425117-c082bde5-ae61-4d8a-ae8b-c03cbce3ca29.gif)

When the window is non-resizable, it's worse because when you move the window, the bounds snap back to what they were, but the content bounds stay large and so the content gets cut off.

**Comment by clavin** [comment]
I wasn't able to reproduce this on 13.1.7, but was able to on 11.4.11.

I did notice that on 11.4.11 when I minimize the child window it turns into this tiny floating control box near the task bar:

<img width="167" alt="Screen Shot 2021-08-06 at 8 47 16 PM" src="https://user-images.githubusercontent.com/9995434/128585543-6470660b-efcb-45a7-9f1a-9f5150706072.png">

When I maximized the parent window the child window was still the same width as the little floating control thing (which is bigger than the child window's actual minimum width). Additionally, when I went to resize the child window after performing this bug, I did see it snap to the old smaller width for a moment before continuing where I was dragging.

**Comment by pushkin-** [comment]
@clavin That's just how child windows work on Windows - they turn into a tiny floating control. That should happen in Electron 13 too unless you were using the same `new-window` code which is broken in Electron 13 right now, and so the `parent` property that I set won't be respected there.

**Comment by pushkin-** [comment]
repros with latest stable (21)

**Comment by pushkin-** [comment]
can't repro in v22 or v21
