### ISSUE TITLE
[Feature Request]: How to customize the system tray

### ISSUE THREAD

**Issue by promotion-xu** [electron/electron#30433]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to customize the system tray, but the Tray can't do it
So Do we have the way to dot it?
![image](https://user-images.githubusercontent.com/36992764/128461989-c5d848be-7723-48e0-af9f-1a66b74e953a.png)

### Proposed Solution

I hope Electron can provide not only a contextMenu but also support the customize elements

### Alternatives Considered

I hope Electron can provide not only a contextMenu but also support the customize elements

### Additional Information

![image](https://user-images.githubusercontent.com/36992764/128461989-c5d848be-7723-48e0-af9f-1a66b74e953a.png)

**Comment by promotion-xu** [comment]
tray.setTitle, how to set color in this method  or it provide sth to support to set color in title. 
someone know it?

**Comment by clavin** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
