### ISSUE TITLE
[Bug]: App logo is broken on Window's notification

### ISSUE THREAD

**Issue by YeetOrBeYate** [electron/electron#30441]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^13.1.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro version 20H2

### What arch are you using?

x64

### Expected Behavior

Electron should open a notification with the app logo and application name in the top line, and all other information passed into the title and body

### Actual Behavior

The Icon has a blue background to it that is not present in the task bar or anywhere else in the app. Even when passing in custom xml, the icon stays and has a blue background.

This is the custom xml I'm passing in to attempt to override the wonky app logo:

`  
  <toast>
    <audio silent="true" />
    <visual>
      <binding template="ToastGeneric">
        <text>New Item!</text>
        <text>Body text</text>
        <image placement="appLogoOverride" hint-crop="circle" src="${testIcon}"/>
      </binding>
    </visual>
  </toast>`

According to Microsoft's documentation this is the correct way to remove the default app logo and substitute your own.
https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/adaptive-interactive-toasts?tabs=xml#app-logo-override 
Unfortunately in this case, it does not override as needed and still shows an icon with a blue background.

I guess overall, I need 2 questions answered:
Why is electron adding a blue background to my app's png in the notification and no where else?
Why is electron ignoring the custom xml?

attached are the app logo as it sits in the taskbar, and the offending notification made from my custom xml. Keep in mind the notification icon has a blue background whether I pass in custom xml or not.
![Screenshot (10)](https://user-images.githubusercontent.com/40674349/128567742-a9ab9b5c-619e-43b8-a017-d65742af2dbc.png)
![Screenshot (9)_LI](https://user-images.githubusercontent.com/40674349/128567761-b0219558-7a91-4238-a19e-2369d6593c7b.jpg)

**Comment by VerteDinde** [comment]
Hey @YeetOrBeYate, Thanks for reporting this and helping to make Electron better! (Also, I love your handle 😄 )

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by YeetOrBeYate** [comment]
@VerteDinde Unable to reproduce in a gist since I cannot set an application's icon without making a bonafide distribution. 

I can however report that the gist to test notification's does create a similar bug where there is _no icon_ at all in a standard notification. Is it possible Electron is using a library to make Window's notifications? It seems as though what ever is generating the template for notifications is:

1.) Not responding correctly to images without a background(Hence the blue background added to my icon in the first shot)

2.) Not responding to xml that is supposed to override a Windows notification's default icon

3.) In this gist's case, not applying an icon(electron's default icon) at all

Seems like whatever template/generator electron is using is inconsistent

Gist: https://gist.github.com/YeetOrBeYate/ab94e2d1ef91738b8b2de131650c1e5d
