### ISSUE TITLE
[Bug]:  Win7 & Win10 - Receive Touch Messages

### ISSUE THREAD

**Issue by simann** [electron/electron#30454]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

Windows

### Operating System Version

Windows 7 & Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

-

### Expected Behavior

On windows 7 and windows 10 receive all the touch events.

### Actual Behavior

On windows 7 its working as expected.

On windows 10, electron receives the touch but the window hook wont receive it.

### Additional Information

I created an c++ application to capture all Keyboard, Mouse  and Touch actions.

Basically im listening on the following messages with the window hooks "WH_KEYBOARD_LL" & "WH_MOUSE_LL":

- WM_LBUTTONDOWN
- WM_LBUTTONUP
- WM_RBUTTONDOWN
- WM_RBUTTONUP
- WM_MOUSEMOVE
- WM_MOUSEWHEEL
- WM_MOUSEHWHEEL
- WM_TOUCH
- WM_KEYDOWN
- WM_KEYUP

The touch messages i get on my hp pro x2 are recognized as move, lbuttondown and lbuttonup:

![image](https://user-images.githubusercontent.com/28533890/128707824-8a28aa11-e836-48b9-bc5f-ed3f029f2729.png)

On the windows 7 machine i get all the messages <- working as intended

On the windows 10 machine the behaviour is really strange. If i click on an BrowserWindow i dont get any messages.
A Click on an empty space on the Desktop gives me the message.

It looks like the electron application fetches the above mentioned messages and doesnt report them back in the hook chain? Maybe there is an "CallNextHookEx(...)" missing?

Can anyone confirm?

Greetings
Simon

**Comment by VerteDinde** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
