### ISSUE TITLE
Opening the Developer Tools panel breaks Reload and Force Reload buttons.

### ISSUE THREAD

**Issue by EdMSL** [electron/electron#30455]
### Electron Version
13.1.8
### OS
Windows 10 20H2
### Arch
x64
### Last Known Working Electron version
7.1.9

I am creating an application using Electron with Webpack, TS, React and Redux. I work on two PCs, at home and at work. There was a problem on my home PC that I didn't notice right away. When it came to working on the front-end part, I noticed that when opening the Develooer Tools, the Hot Module Replacement stops working for me, as well as the Reload and Force Reload buttons in the Electron menu.
I solved the HMR problem by adding
```javascript
if (module.hot) {
  module.hot.accept();
}
```
to the mine and renderer files, but if a compilation error occurs, then after fixing it, or if I change some in non-React files, in the console appears
```
[HMR] Cannot apply update. Need to do a full reload!
[HMR] Error: Aborted because ./src/renderer/containers/MainScreen/index.tsx is not accepted
Update propagation: ./src/renderer/containers/MainScreen/index.tsx -> ./src/renderer/containers/App/index.tsx -> ./src/renderer/renderer.tsx
    at applyHandler (http://localhost:8085/build/renderer.js:60091:31)
    at http://localhost:8085/build/renderer.js:59807:21
    at Array.map (<anonymous>)
    at internalApply (http://localhost:8085/build/renderer.js:59806:54)
    at http://localhost:8085/build/renderer.js:59781:24
    at waitForBlockingPromises (http://localhost:8085/build/renderer.js:59737:55)
    at http://localhost:8085/build/renderer.js:59779:22
```
and after that the window should restart, but it doesn't. Also, this cannot be done through the reset buttons of the Electron menu, as I wrote above. When pressed, nothing happens.
I ran the build from under a different user, but the Developer Tools panel does not open there at all.
If I not open DevTools, all works fine.
But the thing is interesting because there are no such problems on a working PC.
All packages are identical, nodejs of the same version, Windows 10, run as administrator.
The problem is somewhere in the PC, but what exactly I cannot understand. Could anyone have had such a problem or have any ideas?

**Comment by EdMSL** [comment]
I have another older project with electron 7.1.9. When I update it to 13.1.8 the same problem occurs.

**Comment by EdMSL** [comment]
app.close() not work too. On both PC's. On Linux all good.

**Comment by xinre** [comment]
hello, did you solve this problem？ I also appear this problem

**Comment by EdMSL** [comment]
> hello, did you solve this problem？ I also appear this problem


There were two different problems. The first one with HMR I solved by adding react-refresh-webpack-plugin. I deleted
```javascript
if (module.hot) {
  module.hot.accept();
}
```
from main and render files, added this to webpack config:
```javascript
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
...
plugins: [
        ...
  !MAIN ? [
      new webpack.HotModuleReplacementPlugin(),
     process.env.FAST_REFRESH && new ReactRefreshWebpackPlugin(),
  ] : [],
],
```
and added new rule:
```javascript
rules: [
  {
    test: /\.(ts|js)(x?)$/,
    exclude: /node_modules/,
    use: [
      {
        loader: 'babel-loader',
        options: {
          plugins: [
            env.FAST_REFRESH && require.resolve('react-refresh/babel'),
          ].filter(Boolean),
        },
      },
      {
         loader: 'ts-loader',
      }
     ...
```
The second one with ```app.quit()``` I solved by adding closeDevTools method before it:
```javascript
window.webContents.closeDevTools();
app.quit();
```
