### ISSUE TITLE
[Bug]: did-start-loading event fired when an iframe is loaded when calling loadURL and navigating

### ISSUE THREAD

**Issue by dklemm** [electron/electron#30479]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.9

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.1

### What arch are you using?

x64

### Expected Behavior

when calling `loadURL('http://some-url-with-iframes')` or navigating web pages `webContents.on('did-start-loading')` and `webContents.on('did-stop-loading')` events should fire only page in the main frame starts and stops loading and not an iframe.

### Actual Behavior

webContents did-start-loading and did-stop-loading are trigger for all frames.

``` console
did-start-loading
did-start-navigation MainFrame: true InPlace: false  Url: https://js-72nsee.stackblitz.io/
did-stop-loading
did-start-loading
did-start-navigation MainFrame: false InPlace: false  Url: https://www.example.com/
did-stop-loading
```

### Testcase Gist URL

https://gist.github.com/f3bebdc200d6511c8ad07fbba53639a8

### Additional Information

Re-opens issue  https://github.com/electron/electron/issues/22182

This isssue is best observerd by navigating directly to the url using loadURL, there is some inconsistency in this occuring on reload, back, forward and in page navigation.

**Comment by codebytere** [comment]
@dklemm this is intended behavior - our documentation does not specify mainframe-only or make any associated guarantees. On our end, we just map to Chrome's upstream logic.
