### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Manunarasingh** [electron/electron#30488]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

12

### Expected Behavior

Wanted to check how many instances are running and control the number of instances running in one Operating system. Let us say I wanted to allow only two instances only running in one System. I am not able to do this.

### Actual Behavior

Only one and remaining can block. Or open for any number of instances. We are not able to control only two instances like that.
Example:
const { app } = require('electron')
let myWindow = null
    
const gotTheLock = app.requestSingleInstanceLock()
    
if (!gotTheLock) {
  app.quit()
} else {
  app.on('second-instance', (event, commandLine, workingDirectory) => {
    // Someone tried to run a second instance, we should focus our window.
    if (myWindow) {
      if (myWindow.isMinimized()) myWindow.restore()
      myWindow.focus()
    }
  })
    
  // Create myWindow, load the rest of the app, etc...
  app.on('ready', () => {
  })
}

**Comment by miniak** [comment]
This sounds like a niche use case, I don’t think this is something we want to support in Electron core. You can always write a node module with custom logic.
