### ISSUE TITLE
[Feature Request]: Expose ability to check if the the app or window is hidden

### ISSUE THREAD

**Issue by mitchchn** [electron/electron#30485]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It's possible to check if a window is visible with `BrowserWindow.isVisible()`.

But there is no way to tell if a window is _hidden_ (e.g. after calling `BrowserWindow.hide()`) or if the entire app is hidden (e.g. after calling `app.hide()` or using CMD-H).

### Proposed Solution

Add one or both APIs:

1. `BrowserWindow.isHidden(): boolean` - whether the window is hidden. (Might work on all platforms?)
2. `App.isHidden(): boolean` - whether the app is hidden. (Mac-only, likely.)

### Alternatives Considered

`BrowserWindow.isVisible()` is close, but it also returns `true` if the window is occluded, which is not the same as it being hidden by the OS.

### Additional Information

These APIs would be particularly useful to apps that have long-lived tray icons and need to change their behaviour base don the hidden state of the main window.

I'm happy to take a crack at adding this if it seems like a good idea.

**Comment by miniak** [comment]
@mitchchn does macOS have API to check if an app is hidden?

**Comment by mitchchn** [comment]
I've added this in in https://github.com/electron/electron/pull/32155.

**Comment by RaisinTen** [comment]
@mitchchn @miniak does this issue need to stay open, now that https://github.com/electron/electron/pull/32155 has landed? This wasn't closed automatically because the PR description used `Refs` instead of `Fixes` in the description.

**Comment by mitchchn** [comment]
This is fixed now, yes.
