### ISSUE TITLE
[Bug]: URI Scheme used to open Electron Application when using app.setAsDefaultProtocolClient lost after calling autoUpdater.quitAndInstall()

### ISSUE THREAD

**Issue by ryankashi** [electron/electron#30486]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

When opening an electron application via the protocol scheme set by `app.setAsDefaultProtocolClient`, the opening URI is stored by windows inside of process.argv of the main process. For example, `your-protocol://my_arguments` can be found in `process.argv` of the main process.

If the Electron autoUpdater executes `autoUpdater.quitAndInstall`, upon restarting, this opening protocol should still be present in the main process `process.argv` variable.

### Actual Behavior

Upon calling calling `autoUpdater.quitAndInstall`, the URI used to open the Electron application is no longer available inside of the main process' `process.argv` variable. This causes undesired outcomes for applications that auto-update prior to launching.

This has not been checked with Mac OS on the `app`  `open-url` event however I expect to see the same issue

**Comment by MarshallOfSound** [comment]
This is not a bug, this is expected behavior.  Calling `quitAndInstall` completely terminates the current session of your application and then launches your new install, with no arguments.  If you need to persist state across relaunches you need to store it on disk and read it on relaunch
