### ISSUE TITLE
[Feature Request]: Delete button for showSaveDialog

### ISSUE THREAD

**Issue by ocavue** [electron/electron#30519]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

On macOS, native applications will show a file dialog when you try to save or close a new file. But there is a subtle difference between the dialogs in these two cases. When you try to close a new unsaved file, there will be a header and a delete button. 
By pressing the delete button, users can close this file without saving it.
Check the snapshot below for an example from the built-in `TextEdit` application.

 
![CleanShot 2021-08-13 at 20 27 18](https://user-images.githubusercontent.com/24715727/129356988-0af07429-fabe-4ce3-86be-38a8307dc575.png)

I like this design and I also want to show a delete button. But I can't implement it with `dialog.showSaveDialog`. The dialog created by Electron is like this:

![image](https://user-images.githubusercontent.com/24715727/129356640-a917f1fd-35d4-4809-bdcd-3ef062766671.png)

### Proposed Solution

Add a new option to `showSaveDialog` to show this delete button. Add a new field in the returned object to represent if this button has been click.

Since `showSaveDialogSync` returns `String | undefined`, I don't think there is any way to add a new return value with compatibility guaranteed.

### Alternatives Considered

Add two new API: `dialog.showSaveBeforeDeleteDialog` and `dialog.showSaveBeforeDeleteDialogSync`. They will do same things to `showSaveDialog` but with a delete button.

### Additional Information

I'm using macOS 11.4.

Please correct me if there is any easy way to achieve this kind of design without changing Electron itself.

**Comment by miniak** [comment]
You can do this b creating a simple node module, which calls then [`NSSavePanel API`](https://developer.apple.com/documentation/appkit/nssavepanel?language=objc)

**Comment by codebytere** [comment]
Some macOS document-based apps show this panel when a dirty document window is closed - they use private APIs to do this and so it isn't something we're able to support at this time. Should that change, we're happy to take a look again.
