### ISSUE TITLE
[Feature Request]: Quick start repository or tutorial with typescript

### ISSUE THREAD

**Issue by chouzz** [electron/electron#30518]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi, I am  **typescript** developer and new to **electron**, I have found there is a quick start repo in readme, but it's **javascript**, considering the popularity and advantages of typescript, I think it will be nice if you can provide a typescript-based quick start repo or tutorial.

### Proposed Solution

Provider an typescript-based quick start repo or tutorial in readme.

### Alternatives Considered

If we can't provide a quick start repo, maybe we can write the tutorial in typescript in official documents.

### Additional Information

None.

**Comment by chouzz** [comment]
Sorry, already found: https://github.com/electron/electron-quick-start-typescript, maybe you can put this link in readme?

**Comment by MarshallOfSound** [comment]
We unfortunately can't link to _everything_ from the README, looks like you found it OK though 👍
