### ISSUE TITLE
Project: Release Notes V2

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#30516]
One of the big issues folks have with upgrading Electron is being able to easily tell (a) what has changed between the version they're on and the version they're upgrading to and (b) whether those changes impact them.

Currently the solution to (a) is to check the releases notes of every version between vCurrent and vNext.  This works reasonably well for upgrades within the same major version of Electron but falls apart when crossing the major version boundary.  This is because fixes / features in vN might not be in vN+1 and vice versa due to how we maintain branches in parallel and backport changes.

In order to solve this problem in a way that actually solves the underlying issue for electron app developers I'd like to outline a series of changes to how we handle release notes.

* [ ] Release notes should not be included in GitHub releases, the notes are inaccurate best and completely wrong at worst.
* [ ] The release notes generation code should be pulled out of `electron/electron` and moved to `clerk` such that you can fire an API request and obtain release notes between two versions.
* [ ] GitHub Releases should contain links to a new release notes service on https://releases.electronjs.org powered by the Clerk release notes service

The new release notes service in clerk is specced out here: https://github.com/electron/clerk/issues/66

**Comment by nornagon** [comment]
> fixes / features in vN might not be in vN+1

This seems like a failure of our backporting policy IMO. Upgrading should never remove features (unless those features were intentionally removed & the removal was listed in breaking changes, etc.)

**Comment by MarshallOfSound** [comment]
> This seems like a failure of our backporting policy IMO. Upgrading should never remove features (unless those features were intentionally removed & the removal was listed in breaking changes, etc.)

Not necessarily, our version system is non-linear, such that 13.3.0 might contain fixes not in 14.0.1 literally because it was released _after_ it.  It isn't a failure in backport policy, it's just an unchangeable That's How Time Works problem 😄
