### ISSUE TITLE
[Bug]: Significantly longer app start time in Electron 11+

### ISSUE THREAD

**Issue by JannisX11** [electron/electron#30529]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 21H1 19043.1165

### What arch are you using?

x64

### Last Known Working Electron version

10.x.x

### Expected Behavior

The electron window used to open instantly, and was ready to go in 1.5 seconds or less depending on the app

### Actual Behavior

Since Electron 11, Browser windows take at least an extra second, which usually doubles the start time for simple applications to around 3 seconds. Often the browser window opens early but then shows a white empty screen for 1-2 seconds.

### Testcase Gist URL

https://gist.github.com/d5069d74920c5757d6c683e90d6ef6c8

### Additional Information

The attached electron fiddle is pretty much the default, I can reproduce the issue in any electron project setup.

**Comment by bundyo** [comment]
Seems disabling hardware acceleration shortens the white screen time.

**Comment by bundyo** [comment]
Also using the switch --use-gl=desktop, which should switch off the ANGLE GL abstraction.

**Comment by JannisX11** [comment]
This is still the case and can be reproduced in the latest release, beta, and alpha version.

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump

**Comment by gpetrov** [comment]
Bump
