### ISSUE TITLE
[Proposal]: app ready should not fire  without handler that waits for on ready or .whenReady() usage

### ISSUE THREAD

**Issue by frank-dspeed** [electron/electron#30533]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

nightly

### What operating system are you using?

Other Linux

### Operating System Version

nightly (Google Fuchsia Kernel)

### What arch are you using?

x64

### Last Known Working Electron version

-

### Expected Behavior
electron-main.cjs;
```js
'use strict';

const { error } = console;
const electron = require('electron');
const scheme = 'app';
import('./electron-main.js')
  .then((m) => {
    electron.protocol.registerSchemesAsPrivileged([
      {
        scheme,
        privileges: {
          standard: true,
          secure: true,
          allowServiceWorkers: true,
          supportFetchAPI: true,
          corsEnabled: true,
        },
      },
    ]);
    m.load(electron);
  })
  .catch(error);
```
does not error with:

Error: protocol.registerSchemesAsPrivileged should be called before app is ready

### Actual Behavior
electron-main.cjs;
```js
'use strict';

const { error } = console;
const electron = require('electron');
const scheme = 'app';

import('./electron-main.js')
  .then((m) => {
    electron.protocol.registerSchemesAsPrivileged([
      {
        scheme,
        privileges: {
          standard: true,
          secure: true,
          allowServiceWorkers: true,
          supportFetchAPI: true,
          corsEnabled: true,
        },
      },
    ]);
    m.load(electron);
  })
  .catch(error);
```
does error with:

Error: protocol.registerSchemesAsPrivileged should be called before app is ready

## Behavior Analyzed
It looks like the app ready event gets fired even without a listner but it should be listner bound.
i did not find the code at present that is related to that behavior but. It looks like it is related to any process event like ```process.nextThick()``` so the event is already fired as soon as the JS Stack is Empty the first time.
As that is the time and event when ```import()``` gets executed.

Current Behavior Flow.
1. require app 
2. wait for first empty JS Stack (process.nextThick)
3. fire app ready.

Expected Behavior Flow
1. require app
2. wait till a listner is registered for ```on(''ready")``` or ```electron.whenReady()``` gets called
3. fire app ready.

## Why?
As you can see in the example it is else impossible to use dynamic import a standard JS feature in the CJS context that allows importing CJS and ESM

sure we can complain that require would work but that would work only for CJS out of my view it is Suprising behavior that it fires without waiting if the app instance is already configured.

**Comment by vladimiry** [comment]
> the app ready event gets fired even without a listner but it should be listner bound

The documentation says otherwise:

https://www.electronjs.org/docs/api/app#event-ready

> Emitted once, when Electron has finished initializing.

**Comment by frank-dspeed** [comment]
@vladimiry your correct but that is not a helpfull comment but your right lets view that out of documentation perspective.

**Comment by vladimiry** [comment]
https://github.com/electron/electron/blob/main/default_app/main.ts shows how to preload stuff.

**Comment by frank-dspeed** [comment]
@vladimiry thanks for trying but i think you do not understand the problem but if you want to help you can search for the place that fires the ready event in the codebase.

**Comment by vladimiry** [comment]
I was trying to help by trying to highlight the fact that the proposal you posted doesn't make sense. Locating something for you is not something I'm ready to do at the moment, same as continuing the discussion. Have a good day.

**Comment by miniak** [comment]
The proposal does not make sense AFAIK.

**Comment by frank-dspeed** [comment]
@miniak Do you not see the Example? what did i do wrong i got code that is 100% CJS code and i need to place code before my dynamic imports that means i can not use dynamic import. Where does that make no sense? I Do not understand that ignorance but i accept it.

**Comment by frank-dspeed** [comment]
@miniak at last it is needed to solve

- [ ] https://github.com/electron/electron/issues/21457

**Comment by Kyza** [comment]
Maybe I can clarify. When using ESM, by the time the code inside the module executes the app is already ready. This means you are forced to use CJS for some functions in Electron that need to be executed before the app is ready.

IMO this fits better as a bug report rather than a proposal.

**Comment by frank-dspeed** [comment]
@Kyza that is not correct we can even abstract esm usage as even when CJS is dynamic imported it is already none working.

and that it is none working is not logical there should be a clear async user inited event that tells electron that the configuration is done. And after that he can fire his Ready event and block the other commands.

**Comment by miniak** [comment]
> @miniak Do you not see the Example? what did i do wrong i got code that is 100% CJS code and i need to place code before my dynamic imports that means i can not use dynamic import. Where does that make no sense? I Do not understand that ignorance but i accept it.

@frank-dspeed sorry about that, I should have replied a more meaningful explanation. We cannot change AFAIK when the app is considered ready. We are getting a notification from Chromium that the main loop is about to get started where we fire the app `'ready'` event. A lot of things can only be configured before that, such as passing commandline switches to Chromium.

**Comment by frank-dspeed** [comment]
@miniak thanks for explaining that.  And your correct it needs no additional time investment the whole electron concept is brooken the devtools protocol will replace it on the long run anyway. As soon as Project Fugu is more well known.

**Comment by ajoslin103** [comment]
I sure wish this would be re-opened....  protocol.registerSchemesAsPrivileged may be just fine, but whatever is calling it is broken.  Fix the Docs, or Fix the Code...

The Docs [1] say how to use the protocol.registerSchemesAsPrivileged and doing it exactly as specified in main.js

```
const { protocol } = require('electron')
protocol.registerSchemesAsPrivileged([
  { scheme: 'foo', privileges: { bypassCSP: true } }
])
```

Which fails with:

Error: protocol.registerSchemesAsPrivileged should be called before app is ready

1.  https://www.electronjs.org/docs/latest/api/protocol#protocolregisterschemesasprivilegedcustomschemes
