### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by spoorun** [electron/electron#30535]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0

### What operating system are you using?

Other Linux

### Operating System Version

Manjaro Linux, with Wayland, KDE Plasma 5.22.4, KDE Frameworks 5.84.0

### What arch are you using?

x64

### Expected Behavior

Create a web app using Nativefier
Create a .desktop file
Run the .desktop file on a Linux desktop with Wayland (& KDE?)

Enable Wayland by including: "Exe=[....yourapp] --enable-features=UseOzonePlatform --ozone-platform=wayland"

Expect icon to work correctly in taskbar, the window decoration and the start menu

### Actual Behavior

Icon works in the taskbar, but not the window decoration or in the start menu etc...

### Additional Information

I found the problem, not sure how to code the fix, but the problem is fairly simple, it appears.

To fix the problem, I opened the 'package.json' file that Nativefier created 
at [your-app]-linux-x64/resources/app/package.json

I changed the line 'name' to match EXACTLY (case sensitive) the name of the .desktop file (excluding the .desktop suffix).

It works.

In my case Nativefier had previously written:
"name": "aaisp-nativefier-7fc0f9",
Even though my app was named AAISP.
My .desktop file was named AAISP.
I changed that line in package.json to:
"name": "AAISP",

The problem is that WMClass does not work in Wayland.
In Wayland the appid is used.
In nativefier the appid appears to be set by package.json. 
It does not follow the app name, and obviously does not follow the .desktop file name (since that is not yet known).

RESOLUTION:

1) When creating nativefier, offer Wayland users (and others) the ability to set the app-id at creation time, with a --app-id option.
2) Now that the majority of major Linux distributions are using or about to use Wayland by default, document how to use Nativefier for Wayland; e.g. set app-id, name your .desktop file with the exact same name as app-id, and 
add "-enable-features=UseOzonePlatform --ozone-platform=wayland" to the exe line in the .desktop file.

**Comment by MarshallOfSound** [comment]
`Nativefier` is not an Electron provided tool, you can find the `Nativefier` repo here --> https://github.com/nativefier/nativefier
