### ISSUE TITLE
[Bug]: Media keys not working with globalShortcuts on macOS 11

### ISSUE THREAD

**Issue by AxelTerizaki** [electron/electron#30543]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

macOS

### Operating System Version

Big Sur 

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

`globalShortcut.register('MediaPlayPause', ...)` should be working and pressing that key should trigger the callback in the function.

### Actual Behavior

The Music app starts (if not previously started) when this key is pressed.

None of the other media shortcuts seem to work.

### Testcase Gist URL

https://gist.github.com/AxelTerizaki/3e9c08586f7912f347e44e26ad25c3d0

### Additional Information

I tried a few things while fiddling.

I added my app to System Preferences > Security & Privacy > Input Monitoring, but to no avail. I also added the electron.app fiddle downloaded there just to make sure.

Protip: move `~/Library/Application Support/Electron Fiddle/electron-bin` to your home directory and create a symlink from there to the electron fiddle folder in app support so you can browse to the electron-bin folder and add the electron.app to security and privacy. Finder won't allow you to browse through `Library` by default, it's hidden.

There are numerous issues on this topic, namely #24052 where adding the app to input monitoring apparently works with Electron 8. It might be a regression but I am not quite sure : Electron 8 isn't available through fiddle. I went as far back as 11.4.11 and couldn't get it to work.

Note : I tested this on an Apple Silicon but it likely affects Intel versions too.

Any help would be appreciated! :)

**Comment by codebytere** [comment]
@AxelTerizaki this should be fixed by my PR which just merged but FYI you can see older versions of Fiddle like so:

<img width="1092" alt="Screen Shot 2021-08-17 at 7 51 35 PM" src="https://user-images.githubusercontent.com/2036040/129776139-21791323-3b4d-470d-b844-b1224e62c9ad.png">

**Comment by AxelTerizaki** [comment]
@codebytere oh, my bad, I missed that checkbox! 

Thanks for the quick fix, can't wait for the release :)
