### ISSUE TITLE
[Feature Request]: add Timing Animation Like Cubic-Bezier in CSS for Height,width,x,y of RendererProcess 

### ISSUE THREAD

**Issue by RexNext** [electron/electron#30553]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

 i want to move a frameless window to new position, by an animation and timing like Cubic-bezier , 
like a css command 
```
 transition:  cubic-bezier(0.55, 0.055, 0.675, 0.19);
``` 
if we can use this feature in electron , we have an revolution in electron apps .. 

### Proposed Solution

i don't have any idea

### Alternatives Considered

setTimeInterval ? maybe 

### Additional Information

nothing

**Comment by MarshallOfSound** [comment]
This is a not a feature that any major OS supports, the closest is on macOS where we support the `animate` boolean toggle for `setBounds`.

https://www.electronjs.org/docs/api/browser-window#winsetboundsbounds-animate

This isn't a thing we can reasonably support for other OS's

**Comment by RexNext** [comment]
you are wrong , we can make something like that in vanillajs ... please have more attention about it . 

https://user-images.githubusercontent.com/66295368/130270501-117628af-846f-4bbf-b417-929ae827013a.mp4
