### ISSUE TITLE
[Bug]: Toggling `documentEdited` moves `hiddenInset` traffic lights to the `hidden` position and back once the window is blurred

### ISSUE THREAD

**Issue by nathanlesage** [electron/electron#30564]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.9

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.5.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Toggling the `documentEdited` status on a Browser window with `titleBarStyle: 'hiddenInset'` simply sets the black dot indicating an edited document and not move the traffic lights around.

### Actual Behavior

When the `documentEdited` status is toggled, the traffic lights move from the `hiddenInset` position to simply the `hidden` position (that is: slightly less inset).

Interestingly, once I blur the window and re-focus it (i.e. by moving another window on top of it) this resets the traffic lights back to the hidenInset position while retaining the black dot. When the `documentEdited` status is then toggled again, the traffic lights again move to the `hidden` position, and back to `hiddenInset` once the window is blurred.

## Instructions for the Testcase

1. Run the gist in Electron fiddle on either an ARM64 or Intel Mac
2. Click the "Toggle documentEdited Status"-button
3. Observe that the traffic lights move further into the corner of the window and a black dot appears
4. Blur the window (e.g. by clicking on the Desktop, activating another application, etc)
5. Observe that the traffic lights move back to the correct position while the black dot is being retained
6. Click "Toggle documentEdited Status" again
7. Observe the same behavior, now without the black dot

### Testcase Gist URL

https://gist.github.com/166ffcd98c950e6e97fec05ae4f2683b

### Additional Information

I believe this to be a regression bug directly related to a previous issue of mine: https://github.com/electron/electron/issues/30039

That issue has been fixed with this PR: https://github.com/electron/electron/pull/30322

The previous bug from issue 30039 has been fixed in Electron 13.1.8, but that also introduced the moving around of the traffic lights.

**Comment by codebytere** [comment]
Caused by https://github.com/electron/electron/pull/30393 - I'll look into this today.
