### ISSUE TITLE
[Bug]: On Linux window is not maximized when restored

### ISSUE THREAD

**Issue by andreldm** [electron/electron#30575]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.2.0

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Expected Behavior

With a single instance application such as [andreldm/electron-quick-start](https://github.com/andreldm/electron-quick-start), when a minimized window is restored, if it was maximized it should be restored as such.

### Actual Behavior

Maximized windows when restored go back to their "normal" state.

### Additional Information

- Desktop: Xfce 4.16
- I cannot reproduce this bug with Chromium (92.0.4515.131)
- This is a follow-up of #9281 and https://github.com/microsoft/vscode/issues/130932.
- While working on a reproducer, I noticed that listeners to the window's `minimize` and `restore` events didn't work.
- I'm not sure if I'm looking at the right place but it seems like Chromium's [restore function](https://source.chromium.org/chromium/chromium/src/+/main:ui/views/widget/native_widget_aura.cc;l=711;drc=7c87736d27b223ec3b90c1ecf71cb830e45a8d41) sets the window state to normal unconditionally, instead of keeping tracking of the previous state.
- Running from terminal `xdotool search --limit 1 'Hello World' windowactivate` restores the window maximized as expected.

**Comment by zcbenz** [comment]
The `restore` API is supposed to bring a maximized window to normal size, instead of bringing a minimized window to previous state. The name `restore` came from the win32 API with the same name, so it looks confusing.

I'm merging this to https://github.com/electron/electron/issues/526.

**Comment by pushkin-** [comment]
@zcbenz You're not talking about the `BrowserWindow::restore` API are you? Because those [docs](https://www.electronjs.org/docs/api/browser-window#winrestore) say:
>Restores the window from minimized state to its previous state.

Which directly opposes what you said.

Should [this](https://github.com/electron/electron/issues/20540) related issue be closed? I'm not calling `restore` anywhere. I'm just relying on Windows+D in Windows 10.

**Comment by dsanders11** [comment]
I made a test gist for this, and can confirm it fails on Linux, but works fine on Windows and macOS: https://gist.github.com/488ba64240ccc17dee680a98343551fd

**Comment by andreldm** [comment]
Still reproducible with electron 21.0.1.

**Comment by andreldm** [comment]
Reproducible with both 21.3.3 and 22.0.0.

Sigh, this auto stable flagging is annoying, can anyone disable it for this issue?

**Comment by BABA983** [comment]
Met this problem on 13.6.9.

**Comment by zcbenz** [comment]
I have submitted a patch to Chromium to fix this:
https://chromium-review.googlesource.com/c/chromium/src/+/4252946

I will backport it to Electron after received some reviews.
