### ISSUE TITLE
Add Support to screen module for getting the PPI of screens

### ISSUE THREAD

**Issue by francoislaberge** [electron/electron#3057]
This would be super useful for doing responsive design that takes into considering the physical size of the screen in addition to just the pixel density.

**Comment by zcbenz** [comment]
Does the `scaleFactor` attribute of `display` work for you?

```js
require('screen').getPrimaryDisplay().scaleFactor
```

**Comment by francoislaberge** [comment]
As far as I know that is equivalent to window.devicePixelRatio in browsers. It's either 1 (older screens), 2-3 (retina type screens).

It does not contain physical unit size info. Concretely a 13" and 15" MacBook Pro would return the same scaleFactor but they have a different amount of pixels per square inch.

**NOTE:** I changed the DPI in the title to PPI which is more correct (See [DPI vs PPI](https://99designs.com/designer-blog/2013/02/26/ppi-vs-dpi-whats-the-difference/))

My use case is for displaying things on the screen that are the same size as in reality. For example you could render a quarter on the screen and hold one up to the screen and it would match in size no matter what the computer screen if I had the correct info. Having this information in general is going to lead to some very interesting responsive design possibilities like: choosing text rendering attributes based on legibility that factors in this extra information, or being able to compare your hand size to a basketball players, or buy shoes and see how things look at real world sizes in front of you.

**Comment by francoislaberge** [comment]
@zcbenz This is how by the way you'd calculate the correct PPI on Mac's, I'm sure there is an equivalent API in other OSs (well hopefully).
http://stackoverflow.com/a/12589799

**Comment by francoislaberge** [comment]
@zcbenz I have started to prototype this out in user space via a module called ```lifesized```, it comes downloadable demos and is already functioning on macs (with fallbacks on Windows/Linux for now):
https://github.com/francoislaberge/lifesized

Checkout the demos if you have time, I think they are fun.

**Comment by francoislaberge** [comment]
[npmjs.org/lifesized](http://npmjs.org/lifesized)

**Comment by etiktin** [comment]
I like the idea. If it works you can do some pretty cool stuff with it.
I'm not sure it's possible to get the real physical dimensions on Windows (see discussion on http://stackoverflow.com/questions/3019346/is-there-a-way-to-determine-the-physical-size-of-the-monitor).

**Comment by francoislaberge** [comment]
Thanks for the link, will read up on it once I get a VM setup for windows.

**Comment by etiktin** [comment]
You can get one for free here: https://dev.modern.ie/tools/vms/mac/

**Comment by StoneCypher** [comment]
It's very possible.

https://msdn.microsoft.com/en-us/library/dd144877%28VS.85%29.aspx `HORZSIZE`/`VERTSIZE` for physical size, and `HORZRES`/`VERTRES` for native physical (ie, not what it's currently running, but what it's capable of) resolution.

**Comment by nornagon** [comment]
This appears to be available as `devicePixelRatio`, but not as `window.devicePixelRatio`, which breaks sigma.js: https://github.com/jacomyal/sigma.js/blob/5738398039fae43543cf6a4ceb1126be39234177/src/utils/sigma.utils.js#L613-L624

**Comment by nornagon** [comment]
... nevermind, that's not what's happening at all.

**Comment by nornagon** [comment]
Aha, [this](https://github.com/jacomyal/sigma.js/blob/80e8d61d9218d4259b4dd480fb2d8a340806ccc3/src/sigma.export.js#L7-L20) is why sigma.js is breaking.

**Comment by paulcbetts** [comment]
@nornagon If you want to be more explicit about detecting Electron:

```js
let isElectron = 'type' in process;
let isMainProcess = (process.type === 'browser');
```

**Comment by francoislaberge** [comment]
@nornagon Yeah, as far as I can tell from extensive research, it's not possible to figure out the DPI/PPI using just browser APIs.

**Comment by StoneCypher** [comment]
@francoislaberge - sorry, what do you mean by "just using browser APIs?"

it looks like you had a mac-specific solution.  is the windows-specific solution i offered you not nearly the entire rest of the job?

**Comment by StoneCypher** [comment]
like ... surely it isn't the case that electron has no access to the underlying OS APIs?

**Comment by francoislaberge** [comment]
@StoneCypher Right, definitely you can access platform specific APIs using native modules or doing a PR to Electron itself. This became a lower priority for me, but I'm certainly interested in it, might revisit in the future.

**Comment by codebytere** [comment]
Given that it's currently not possible to implement such a feature in a cross-platform way, and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!
