### ISSUE TITLE
[Bug]: webContents.print when silent is true deviceName is not effective

### ISSUE THREAD

**Issue by wwwfkszcom** [electron/electron#30590]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.9

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

when silent is true  if deviceName not empty  is with deviceName settings for printing
options  copies  setting  can take effect

### Actual Behavior

printWindow.webContents.print({
      silent: true,
      printBackground: false,
      deviceName: deviceName,
    }, (success, errorType) => {
      if (!success) {
        console.log(errorType)
      }
    })

when silent is true  deviceName is not Not effective
when silent is true  copies is not effective too

**Comment by rajatshrm648** [comment]
hi @wwwfkszcom , I want to work on  this bug

**Comment by codebytere** [comment]
Duplicate https://github.com/electron/electron/issues/30340
