### ISSUE TITLE
[Bug]: setting Accessibility through Swift returns 'attributeUnsupported'

### ISSUE THREAD

**Issue by godbout** [electron/electron#30644]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7, macOS Big Sur 11.5.2

### What arch are you using?

x64

### Expected Behavior

as per the doc (https://www.electronjs.org/docs/latest/tutorial/accessibility/#macos), setting the Accessibility through Swift:

```swift
guard let pid = NSWorkspace.shared.frontmostApplication?.processIdentifier else { return nil }
let axApp = AXUIElementCreateApplication(pid)
        
let manualAccessibility = true
let error = AXUIElementSetAttributeValue(axApp, "AXManualAccessibility" as CFString, manualAccessibility as CFTypeRef)
```

expected behavior: error returned is equal to `.success` (0)

### Actual Behavior

actual behavior: error returned is `attributeUnsupported` (-25205)

Accessibility is not set for the Electron app.

### Additional Information

see more blah blah on https://github.com/electron/electron/issues/30567

**Comment by godbout** [comment]
definitely still affecting.

**Comment by MarshallOfSound** [comment]
@godbout I believe our documentation may be out of date / wrong.  Can you try using the `AXEnhancedUserInterface` attribute instead of `AXManualAccessibility`

**Comment by godbout** [comment]
as far as i remember, the Electron framework responds to `AXEnhancedUserInterface` too yes, but it's been known around people dealing with Electron and the macOS AX API to avoid `AXEnhancedUserInterface` because of multiple bugs in macOS related to it, and it usually breaks windows managers and other stuff.

anyways i've went around the issue on my side. if you guys think this issue is not important or shouldn't be fixed, i guess you can close it. thanks Samuel.
>

**Comment by MarshallOfSound** [comment]
🤷 `AXManualAccessibility` should fire it too.  https://cs.github.com/electron/electron/blob/ff0517be3e00b7a1a80fb56bd97d12c26d620f7f/shell/browser/mac/electron_application.mm#L178-L191

Not sure why one would, and the other doesn't give that code path 🤷
