### ISSUE TITLE
[Bug]: Y8 Browser screen is white

### ISSUE THREAD

**Issue by satria2809** [electron/electron#30641]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

i dont know

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

i dont know

### Expected Behavior

Litterly the screen of y8 brower is empty, just a white screen
![Issue](https://user-images.githubusercontent.com/89185347/130027822-cbedec9f-75da-4d98-b1f1-7b1860313ffe.png)

### Actual Behavior

Litterly the screen of y8 brower is empty, just a white screen
![Issue](https://user-images.githubusercontent.com/89185347/130027822-cbedec9f-75da-4d98-b1f1-7b1860313ffe.png)

### Additional Information

Litterly the screen of y8 brower is empty, just a white screen
![Issue](https://user-images.githubusercontent.com/89185347/130027822-cbedec9f-75da-4d98-b1f1-7b1860313ffe.png)
i did't doing anythink

**Comment by MarshallOfSound** [comment]
This appears to be an issue with a specific Electron app rather than Electron itself.  Please report it to the maintainers of that application
