### ISSUE TITLE
[Bug]: frame: false has an invisible navbar in macOS

### ISSUE THREAD

**Issue by franciscop** [electron/electron#30655]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.5.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When the `frame: false` option is passed to the `new BrowserWindow()` options, all of the window is a canvas for HTML that is clickable.

### Actual Behavior

The top ~20 pixels of the frameless window is not clickable, and doesn't have events. It's as if the title bar was there, but invisible. This is the code:

```js
const { app, BrowserWindow } = require("electron");

app.on("ready", () => {
  const child = new BrowserWindow({ frame: false });
  child.loadURL("https://github.com");
  child.once("ready-to-show", () => {
    child.show();
  });
});
```

See a recording of the bug in action, expected the whole icon/button to be hoverable+clickable but seems like something is "covering" them:

https://user-images.githubusercontent.com/2801252/130335574-d3c9b9a4-e949-4af2-8150-6bde52196cf2.mp4

### Testcase Gist URL

https://gist.github.com/franciscop/20a6fbd380ad10678e512f14c76be125

### Additional Information

Something interesting is that, playing with the option `titleBarStyle` you can get one version where this particular issue is fixed (BUT it requires you to show the buttons on hover, which of course it's an impossible requirement in many cases, so it's still a bug):

```js
const { app, BrowserWindow } = require("electron");

app.on("ready", () => {
  const child = new BrowserWindow({
    frame: false,
    // We don't want the buttons, but at least this makes more real estate clickable?
    titleBarStyle: "customButtonsOnHover"
  });
  child.loadURL("https://github.com");
  child.once("ready-to-show", () => {
    child.show();
  });
});
```

See how now you can hover on all the elements, BUT it also displays the buttons on hover:

https://user-images.githubusercontent.com/2801252/130335667-7106286f-2203-417f-99c9-68e8a832abdc.mp4

I tried `hidden` and `hiddenInset` but they oddly enough do show the controls and they still have the previous issue as the commented here originally (or even worse in the case of `hiddenInset`).

Related bugs:
- [This bug in menubar](https://github.com/maxogden/menubar/issues/172) is definitely the same thing.
- I found [another slightly related](https://github.com/electron/electron/issues/26720) but probably different bug since it's in a different platform, so I believe it might be a different thing (the video linked is dead so cannot verify).

### Code dive-in

I'm way out of my depth here, but it seems [this line of code](https://github.com/electron/electron/blob/main/shell/browser/native_window_mac.mm#L357) is the one making the title bar transparent when `frame: false`:

```c++
  if (transparent() || !has_frame()) {
    // Don't show title bar.
    [window_ setTitlebarAppearsTransparent:YES];
    [window_ setTitleVisibility:NSWindowTitleHidden];
```

And then [this conditional](https://github.com/electron/electron/blob/main/shell/browser/native_window_mac.mm#L1479) makes it "visible" if it's not `customButtonsOnHover`? Maybe? (as I said, unfortunately I can report the bug but not sure if I follow the correct code for the bug here):

```
  if (title_bar_style_ == TitleBarStyle::kCustomButtonsOnHover)
    [buttons_proxy_ setVisible:visible];
  else
    InternalSetWindowButtonVisibility(visible);
```

**Comment by zcbenz** [comment]
This is a duplicate issue of https://github.com/electron/electron/issues/5723.
