### ISSUE TITLE
[Bug]: Support for Windows 11 Insider Builds

### ISSUE THREAD

**Issue by haneenmahd** [electron/electron#30657]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0-nightly.20210820

### What operating system are you using?

Windows

### Operating System Version

11 Insider Build

### What arch are you using?

x64

### Last Known Working Electron version

14.x

### Expected Behavior

The App Should work just fine and smooth.

### Actual Behavior

Electron based apps like `vscode`, `GithubDesktop`, `Figma`, `Framer` experience a slow perfomance on windows 11 Latest Insider Build.

**Comment by zcbenz** [comment]
Hmm all browsers on Windows 11 seem to be slow, it seems to be a problem of Windows itself.

**Comment by haneenmahd** [comment]
Maybe Windwos Defender Is causing the problem.
But, Microsoft Edge seems to be super faaast 🔥 .

**Comment by steveodds** [comment]
I initially only noticed this with vscode but Microsoft Teams is also slow and sluggish with Windows 11. It seems to be an issue with accessibility options being triggered, especially on laptops. Launching vscode and Teams while passing the following option, '--disable-renderer-accessibility' seems to provide a temporary solution. But if any of the apps end up reloading their windows you end up with the same issue, being forced to close and start them again from the commandline.

**Comment by steveodds** [comment]
> 
> 
> I tried clearing all the cache files, And now it works for apps like Framer Desktop, Figma Desktop.

I think I'll try this, has it held up in the past few days?

**Comment by haneenmahd** [comment]
Yes, it worked fine.

**Comment by nitrog0d** [comment]
Electron apps are still laggy in Insider Builds, including VSCode.

**Comment by theolivenbaum** [comment]
Is this still an issue?

**Comment by MelchiorKokernoot** [comment]
Yes.

**Comment by haneenmahd** [comment]
I don' think this is mostly because of Electron, cause as far as I have understand this is only happening because Windows Defender is running in the background and I think it uses more cpu/do more tasks when using an Insider version. This prevents some apps (especially electron apps to slow down).

If anybody is still experiencing issues with electron apps on Windows 11 or Windows 11 Insider, please comment down?
