### ISSUE TITLE
[Bug]: All electron apps freeze periodically on linux

### ISSUE THREAD

**Issue by Rasie1** [electron/electron#30654]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

v13.2.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux 5.4.131-1-MANJARO

### What arch are you using?

x64

### Expected Behavior

Functional VS Code, Google Chrome, Vivaldi, Skype and dozens of other apps that are based on electron.

### Actual Behavior

All electron applications periodically freeze every 10 minutes for 10-20 sec. This is terrifyingly annoying

### Additional Information

This issue was closed and not resolved https://github.com/electron/electron/issues/21415
There are workarounds that involve turning off half of your CPU functionality, which is less desired than experiencing this bug.

From what I read this happens to i7-8550U (and possibly some other intel processors) users

**Comment by Rasie1** [comment]
As it was said, only graphical part freezes while app works and even creates popups

**Comment by Rasie1** [comment]
This is a GPU-related bug that happens only on certain linux kernels not exclusively with Electron apps, so I'll close this

**Comment by Gavin152** [comment]
@Rasie1 have you been able to resolve this somehow? I'm also running manjaro with 5.10.60 kernel and experienced the same behavior after upgrading to electron 13.2. For now, I downgraded back to 13.1.9, but I'd be interested in how you solved it!

**Comment by Rasie1** [comment]
@Gavin152 yes. I switched back to 4.19 kernel from 5.4 and never experienced this again. 

It affects other apps (for example, alacritty), did they change rendering behaviour in 13.2? Because otherwise, electron version shouldn't affect this

I also wanted to see if it works with latest kernel someday, if anyone already did this, would be great if they post the result.

**Comment by Gavin152** [comment]
Huh, that's interesting. I've been on the 5.x kernel for a while now and the problems appeared, after I updated yesterday and somehow seem to affect my electron apps (slack, ferdi, teams) predominantly. I didn't have too much time for investigation, though.

**Comment by cmosig** [comment]
> @Gavin152 yes. I switched back to 4.19 kernel from 5.4 and never experienced this again.
> 
> It affects other apps (for example, alacritty), did they change rendering behaviour in 13.2? Because otherwise, electron version shouldn't affect this
> 
> I also wanted to see if it works with latest kernel someday, if anyone already did this, would be great if they post the result.

I am on 5.10.59 and still experience this issue :(

**Comment by Bubblbu** [comment]
I'm on 5.10.61-1-MANJARO and also experiencing these issues with my electron apps like slack, rambox, signal (installed via snap) but also codium (AUR). I'm also on a Thinkpad T14s AMD which requires a kernel version >5.8 which means I can't downgrade to 4.19.

any ideas?

**Comment by Gavin152** [comment]
**[POSSIBLE SOLUTION]**
So, I found the cause of the issue on MY machine. It was **not** the electron version, **not** the kernel version, but instead dunst (my notification daemon/manager), which failed to properly get started via my i3config. What I suspect caused the freezing behavior was, that the apps in question wanted to push a notification to the queue (or however this is implemented in the background) but weren't able to reach dunst and ran into a timeout. In any case, manually starting dunst fixes the behavior.

**Comment by Bubblbu** [comment]
Confirming that the notification service was also the issue on my system.

Enabling the notification widget on Manjaro KDE resolved the issue.

**Comment by baelter** [comment]
How can I confirm if this is the case for me? (on 5.15.0-48 ubuntu 22.04.1)
