### ISSUE TITLE
Request for WTFs - unloading node modules

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#3065]
Currently, Electron maintains the node.js behavior of never unloading any module ever for the lifetime of the process. While this makes 100% sense in the server-side scenario, in a Desktop app it would make more sense if modules could be be subject to garbage collection. While I don't have the evidence, I suspect that _many_ modules are loaded once, then never touched again. What do you think about this:

1. Convert the main module cache into a `WeakMap`
1. Create a second structure which is a fixed-size array of { Module Path => Module} values
1. Whenever `require` is called:
  * Search the array for the item - if found, put it at the front
  * If it is *not* found, add it to the list at the front
  * Remove all items that fall off the end of the fixed size

This has the effect of ensuring that the last N modules that have been require'd don't end up getting continually loaded / GC'd / loaded / GC'd.

Since this feature will probably break software, we'll almost certainly make this an opt-in thing, at least until we can see:

1. Whether it actually even helps any
1. How bad it will break software

@zcbenz thoughts?

**Comment by zcbenz** [comment]
You can probably just clean the module cache once your app is loaded, like this:

```js
require('module')._cache = {};
```

This won't break most apps, and clears memory immediately.

**Comment by zcbenz** [comment]
I just realized Node is mirroring the cache object like this:

```js
require.cache = Module._cache
```

So in order to clear all caches we need to manually delete every member for the object:

```js
var Module = require('module');
for (var filename in Module._cache)
  delete Module._cache[filename];
```

**Comment by etiktin** [comment]
Is it really that significant? What's the total size of modules Slack loads?

**Comment by paulcbetts** [comment]
Currently we've got 651 node modules:

```
paul@psamathe:~/code/tinyspeck/slack-winssb% npm ls | wc -l
     653
```

**Comment by maxogden** [comment]
This strikes me as something that can be done in userland by monkeypatching require (e.g. https://github.com/maxogden/node-repl/blob/fcefbf0b0f04bae25fd78fd33716f3ca242c7f45/bin.js#L15-L20)

**Comment by paulcbetts** [comment]
@maxogden It can be probably done by hacking node.js's module stuff, but if we find out it doesn't cause problems and it provides a benefit, it should probably just be built-in

**Comment by maxogden** [comment]
@paulcbetts sounds good unless the hack turns into technical debt that prevents electron from upgrading to newer node versions in the future (kinda like how apm still uses node 0.10)

**Comment by zcbenz** [comment]
I'm closing this since few people is interested in this and no one is going to work on it.
