### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JuanIrache** [electron/electron#30653]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.7

### What operating system are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

x64

### Last Known Working Electron version

4.2.6

### Expected Behavior

WebGL works (specifically mapbox-gl)

### Actual Behavior

Crashes with error "Failed to initialize WebGL"

### Additional Information

Works well in Windows 10 and MacOS (Intel and arm builds)

The problem was already discussed here: https://github.com/electron/electron/issues/19234

**Comment by JuanIrache** [comment]
To reproduce:

> $ git clone https://github.com/JohnMLarkin/MapBox_Electron_Demo
> $ npm install
> $ npm start || electron .

**Comment by zcbenz** [comment]
Chromium now does not look really into graphics issues on Windows 7, so I'm afraid there is nothing we can do on Electron's side. I'm closing this issue as won't fix.
