### ISSUE TITLE
[Bug]: showOpenDialog with openFile and openDirectory only selects directories in Windows

### ISSUE THREAD

**Issue by knownasilya** [electron/electron#30651]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Setting `openFile` and `openDirectory` on showOpenDialog should let you select files and folders.

Example:

```js
const result = await dialog.showOpenDialog(mainWindow, {
      properties: ['openFile', 'openDirectory'],
      filters: [{ name: 'Default', extensions: ['json', 'geojson', 'zip'] }],
    });
```

### Actual Behavior

On macOS this works just fine, but in windows it only shows you directories.

### Testcase Gist URL

https://gist.github.com/cb3c9b92ea846a6de459f05adc031ceb

**Comment by codebytere** [comment]
@knownasilya this is known behavior and a platform limitation. Windows only lets you select one or the other, but not both at the same time.  See [documentation](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/ne-shobjidl_core-_fileopendialogoptions)

```
FOS_PICKFOLDERS
Present an Open dialog that offers a choice of folders rather than files.
```
