### ISSUE TITLE
[Bug]: capturePage doesn't work for a hidden browser view since version 13.0.0-beta.21

### ISSUE THREAD

**Issue by zeeker999** [electron/electron#30666]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0-beta.21 and newer
12.0.0-beta.21 and newer

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

11.x

### Expected Behavior

A screenshot should be captured successfully

### Actual Behavior

A zero-sized image is returned instead.

### Testcase Gist URL

https://gist.github.com/d4051b57412bf289d3a812d5387179fe

### Additional Information

* `createBrowserView3` works fine with electron 12.x.y on Mac OS X. 
* `createBrowserView2` doesn't work with electron 12.0.0-beta.21 and newer
* `createBrowserView3` doesn't work with electron 13.0.0-beta.21 and newer
* The only difference between createBrowserView2 and createBrowserView3 is the createBrowserView3 loads `about:blank` before loading the target page.
* Periodically reloading the page and capturing the page will break page loading completely, further loading requests will never be finished,  and setting app.allowRendererProcessReuse to false doesn't help.

**Comment by LuoJinghua** [comment]
find a workaround for this issue:
* v12 - browserView.webContents.incrementCapturerCount() before capturing the page, browserView.webContents.decrementCapturerCount() after it(this is optional)
* v13+ - browserView.webContents.incrementCapturerCount() before capturing the page, browserView.webContents.decrementCapturerCount() must be removed.

@codebytere

**Comment by miniak** [comment]
Could it be caused by #27883

**Comment by zeeker999** [comment]
> Could it be caused by #27883?

I don't think so. I did attach to the process and manually step into the method, the visibility state is correct.

**Comment by sanperrier** [comment]
I think related to this bug in chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=999305&q=incrementCapturerCount&can=2

Current workaround we are using in our project (painful and hacky):
* on `Windows`:
  * not really needed, just in case
    ```
    app.commandLine.appendSwitch('disable-renderer-backgrounding');
    app.commandLine.appendSwitch('disable-background-timer-throttling');
    app.commandLine.appendSwitch('disable-backgrounding-occluded-windows');
    ```
  * `backgroundThrottling: false`
  * `incrementCapturerCount()` just once
  * instead of minimizing or hiding and just move window offscreen (this is painful and tedious, especially for windows with parent-child relations)
* on `MacOS`:
  * really needed, especially last line:
    ```
    app.commandLine.appendSwitch('disable-renderer-backgrounding');
    app.commandLine.appendSwitch('disable-background-timer-throttling');
    app.commandLine.appendSwitch('disable-backgrounding-occluded-windows');
    ```
  * `backgroundThrottling: false`
  * `incrementCapturerCount()` just once

Out testing shows that with that workaround:
* `requestAnimationFrame()` works just fine
* `CSS animations and transitions` work
* `IntersectionObserver` works
* `document.visibilityState` stays `visible` (but on `MacOS` it switches `visible -> hidden -> visible` if window becomes occluded)

**Comment by sanperrier** [comment]
> find a workaround for this issue:
> 
> * v12 - browserView.webContents.incrementCapturerCount() before capturing the page, browserView.webContents.decrementCapturerCount() after it(this is optional)
> * v13+ - browserView.webContents.incrementCapturerCount() before capturing the page, browserView.webContents.decrementCapturerCount() must be removed.
> 

Can you test, that `incrementCapturerCount()` really increments `visible_capturer_count_`?
`isBeingCaptured()` always returns `false` for hidden windows in `14.2.6`

**Comment by zeeker999** [comment]
The incrementCapturerCount() is no longer working due to upstream changes and needs some changes to make it work again. The visible capturer count is reverted to the previous value just before returning to the javascript world, so the isBeingCaptured() always returns false.
 
```c++
base::ScopedClosureRunner WebContentsImpl::IncrementCapturerCount(
    const gfx::Size& capture_size,
    bool stay_hidden,
    bool stay_awake) {`
  ....
  return base::ScopedClosureRunner(
      base::BindOnce(&WebContentsImpl::DecrementCapturerCount,
                     weak_factory_.GetWeakPtr(), stay_hidden, stay_awake));
}
```

> > find a workaround for this issue:
> > 
> > * v12 - browserView.webContents.incrementCapturerCount() before capturing the page, browserView.webContents.decrementCapturerCount() after it(this is optional)
> > * v13+ - browserView.webContents.incrementCapturerCount() before capturing the page, browserView.webContents.decrementCapturerCount() must be removed.
> 
> Can you test, that `incrementCapturerCount()` really increments `visible_capturer_count_`? `isBeingCaptured()` always returns `false` for hidden windows in `14.2.6`
> 
> @zeeker999

The incrementCapturerCount() is no longer working due to upstream changes and needs some changes to make it work again. The visible capturer count is reverted to the previous value just before returning to the javascript world, so the isBeingCaptured() always returns false.
 
```c++
base::ScopedClosureRunner WebContentsImpl::IncrementCapturerCount(
    const gfx::Size& capture_size,
    bool stay_hidden,
    bool stay_awake) {`
  ....
  return base::ScopedClosureRunner(
      base::BindOnce(&WebContentsImpl::DecrementCapturerCount,
                     weak_factory_.GetWeakPtr(), stay_hidden, stay_awake));
}
```

**Comment by zeeker999** [comment]
With the following changes, the incrementCapturerCount() works as intended and the isBeingCaptured() return true now. But I don't know whether this is the correct fix.

```diff
diff --git a/shell/browser/api/electron_api_web_contents.cc b/shell/browser/api/electron_api_web_contents.cc
index c1d28e24c2..ed5e744623 100644
--- a/shell/browser/api/electron_api_web_contents.cc
+++ b/shell/browser/api/electron_api_web_contents.cc
@@ -3006,8 +3006,9 @@ void WebContents::IncrementCapturerCount(gin::Arguments* args) {
   // get stayAwake arguments if they exist
   args->GetNext(&stay_awake);

-  ignore_result(
-      web_contents()->IncrementCapturerCount(size, stay_hidden, stay_awake));
+  auto handler =
+      web_contents()->IncrementCapturerCount(size, stay_hidden, stay_awake);
+  ignore_result(handler.Release());
 }
```

**Comment by zeeker999** [comment]
The change was introduced by commit 22a70eb8036.
