### ISSUE TITLE
[Bug]: use __non_webpack_require__ in BrowserWindow

### ISSUE THREAD

**Issue by tofutree23** [electron/electron#30672]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 pro 20H2

### What arch are you using?

x64

### Last Known Working Electron version

11.4.11

### Expected Behavior

I am using electron using typecript based react. I was able to use the node modules of the electron side in another react project in webview through __non_webpack_required__ until 11.4.11. However, it is not possible to use it with the required is not defined error at the moment.

nodeIntegration, nodeIntegrationInWorker, nodeIntegrationInSubFrames all set to true, and the nodeIntegration: true was added to the webview, but still the required is not defined error appears.

How can I fix it?

### Actual Behavior

Reference error: require is not defined

**Comment by miniak** [comment]
You need to disable contextIsolation

**Comment by miniak** [comment]
https://github.com/electron/electron/blob/main/docs/breaking-changes.md#default-changed-contextisolation-defaults-to-true

**Comment by tofutree23** [comment]
I forgot to explain that part. It is already disabled.
