### ISSUE TITLE
[Feature Request]: Re-enable fitToPageEnabled option for print and printToPDF

### ISSUE THREAD

**Issue by dattn** [electron/electron#30674]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron scales my html content down, to fit into the paper/page size.
I want it to print the page without any scaling.

After some research, i've found the following pull request, which added a new option "fitToPageEnabled":
https://github.com/electron/electron/pull/20436

But this has been removed again with the following pull request:
https://github.com/electron/electron/pull/21906

Is there a reason this has been removed again ? Is there some other way to completely disable scaling for printing and pdf generation?

My current code looks like this:
```javascript
win.webContents.print({
    printBackground: true,
    margins: {
        marginsType: 'none'
    },
    fitToPageEnabled: false,
    scaleFactor: 100
})
```
This does scale the page down to fit the page, which i'm trying to avoid.
                       

### Proposed Solution

Add a "fitToPageEnabled" option to print and printToPdf

### Alternatives Considered

Ignore Printer Paper size setting when an @page css rule is defined ?

### Additional Information

Tested with **electron 13.2.1** on **Ubuntu 20.04**

**Comment by Hedwig188** [comment]
I am also interested in this feature. IE has a "shrink to fit" setting, it would be nice to have it in Electron print APIs so the apps developer no longer needs to do our own calculation to make the dynamic html fit to the page.

**Comment by codebytere** [comment]
This is unfortunately due to its removal in the relevant codepaths upstream by Chromium. Should they bring it back, so will we - but in the meantime, we will adhere to their options settings.
