### ISSUE TITLE
[Bug]: Login item APIs try to mount network volumes

### ISSUE THREAD

**Issue by alanruttenberg** [electron/electron#30670]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

unknown

### What operating system are you using?

macOS

### Operating System Version

Macos 10.15.7

### What arch are you using?

x64

### Expected Behavior

Apps built on electron do not mount network volumes unless that is their purpose.

### Actual Behavior

On launch an Electron application tries and fails to mount a network volume from my local network three times when the volume is unavailable, displaying a dialog 
>"There was a problem connecting to the server XXX. The share does not exist on the server. Please check the share name, and then try again" 

which must be acknowledged each time with a click on "OK". Depending on the network the timeouts before the dialog is presented can be as long as 30 seconds. The same thing happens once on exit. There is no reason the application should care about any machine on my network other than the one it is running on. 

At first I thought this was a [Microsoft Teams bug](https://answers.microsoft.com/en-us/msteams/forum/msteams_other-msteams_topother/how-to-stop-teams-from-trying-to-access-other/53cbaa79-ff3f-4e47-882c-801e9d64d5a5)  but on view of samples in Activity Monitor (attached) I suspected it might be the Electron Framework, so I tried to replicate the bug using another application: Tockler. That application exhibits the same behavior. Attached is a  of the call tree shown by Activity Monitor. While the dialog is presented the application shows as "not responding" in activity monitor.

Using Little Snitch to force local network accesses to affirmatively confirmed it appears that the process requesting the connection is MacOS NetAuthSysAgent.

![Screen Shot](https://user-images.githubusercontent.com/241934/130537906-ec0d5739-fac2-4d80-9f3e-4665d936933b.png)

**Comment by zcbenz** [comment]
This had been fixed in upstream and we need to backport the fix:
https://chromium.googlesource.com/chromium/src/+/d23a60c7cf17683b17c8a941b66056b4f1eb7cc0

**Comment by AJAYK-01** [comment]
> This had been fixed in upstream and we need to backport the fix:
> https://chromium.googlesource.com/chromium/src/+/d23a60c7cf17683b17c8a941b66056b4f1eb7cc0

Hey @zcbenz , I'm a beginner, and would like to work on this issue.
I went through the chromium commit link that you mentioned and found the change in it to use "kLSSharedFileListDoNotMountVolumes" and the same line in the electron repo as well using the older code from the chromium commit

Could you guide me as to how to proceed from here if possible? Is making that change in the line the way to go?

**Comment by RaisinTen** [comment]
The change has already landed in all supported versions of electron. For reference, the oldest release line, 17-x-y, runs on the following version of chromium:
https://github.com/electron/electron/blob/4a000a5e8b86fd0276e7653ed27a1c4e7054b579/DEPS#L17-L18
and the file already has the change needed to fix this issue : https://source.chromium.org/chromium/chromium/src/+/refs/tags/98.0.4758.141:base/mac/mac_util.mm;l=82-86:
```mm
      // kLSSharedFileListDoNotMountVolumes is used so that we don't trigger
      // mounting when it's not expected by a user. Just listing the login
      // items should not cause any side-effects.
      ScopedCFTypeRef<CFURLRef> item_url(LSSharedFileListItemCopyResolvedURL(
          item, kLSSharedFileListDoNotMountVolumes, nullptr));
```
 @alanruttenberg I'm closing this issue now but feel free to let me know if this is still an outstanding issue.
