### ISSUE TITLE
[Bug]: Setting the BackgroundColor to the BrowserView doesn't work on Windows

### ISSUE THREAD

**Issue by weifeiyue** [electron/electron#30700]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

ia32

### Expected Behavior

BackgroundColor to the BrowserView  is ok

### Actual Behavior

BackgroundColor to the BrowserView is not working

### Testcase Gist URL

https://gist.github.com/weifeiyue/3ddde0d19ce942957af6983049fa2764

### Additional Information

```js
const { app, BrowserView, BrowserWindow } = require('electron')

app.on('ready', () => {
  const win = new BrowserWindow({ width: 1000, height: 600 })

  const view1 = new BrowserView()
  win.addBrowserView(view1)
  view1.setBackgroundColor('#FFFFFF')
  view1.setBounds({ x: 0, y: 0, width: 800, height: 600 })
  view1.webContents.loadURL('https://electronjs.org')

  const view2 = new BrowserView()
  win.addBrowserView(view2)
  view2.setBackgroundColor('#FFFFFF')
  view2.setBounds({ x: 200, y: 0, width: 800, height: 600 })
  view2.webContents.loadURL('https://design.google/')
})

```
<img width="508" alt="WX20210826-004703@2x" src="https://user-images.githubusercontent.com/19370201/136980651-ad4ac589-ea1c-422b-bdce-6f1757f52c10.png">

**Comment by weifeiyue** [comment]
#https://github.com/electron/electron/issues/29778

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/30777

**Comment by weifeiyue** [comment]
> Closed by #30777

This did not fix my problem @

**Comment by weifeiyue** [comment]
@samuelmaddock
can you help me?

**Comment by samuelmaddock** [comment]
I'm unable to reproduce this with v13.2.2 on an x64 device, but I haven't been able to test ia32. I'll reopen for now.

**Comment by weifeiyue** [comment]
@samuelmaddock i have update the demo & gist , you can check it out, it is not ok in x64 or ia32
