### ISSUE TITLE
[Bug]: allowRendererProcessReuse: true breaks window reload

### ISSUE THREAD

**Issue by aleksey-hoffman** [electron/electron#30710]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0-beta.23

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

The default `allowRendererProcessReuse: true` should not break window reload

### Actual Behavior

Sometimes the window breaks on reload when `allowRendererProcessReuse === true` (default value).

I noticed this after removing override `allowRendererProcessReuse = false`.

### To reproduce: 

Reproducible at least in `v12.0.0` - `14.0.0-beta.23`

- Focus the window
- Reload the window multiple times by pressing `Ctrl + Shift + R` (wait until it loads every time). After 0 - 10 reloads the window will break and stop loading mid way (the further reloads might fix it temporarily until it breaks again).

### Testcase Gist URL

https://github.com/aleksey-hoffman/sigma-file-manager/commit/5d842a9cfd070c43f395fff98cf08aec79c74b87

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by aleksey-hoffman** [comment]
@codebytere I cannot reproduce it in a barebone Electron app or Electron fiddle.

All I know so far is that changes to `allowRendererProcessReuse` in v14.0.0 broke `BrowserWindow.reload()` (or `Ctrl + Shift + R`). The regular `F5` reload keeps working when you press it within the developer tools window.

**Comment by aleksey-hoffman** [comment]
@codebytere I cannot reproduce it in a barebone Electron app or Electron fiddle.

All I know so far is that changes to `allowRendererProcessReuse` in v14.0.0 broke `BrowserWindow.reload()` (or `Ctrl + Shift + R`). The regular `F5` reload function loads the window properly (you need to press it within the developer tools window).

**Comment by aleksey-hoffman** [comment]
@codebytere I cannot reproduce it in a barebone Electron app or Electron fiddle.

All I know so far is that changes to `allowRendererProcessReuse` in v14.0.0 broke `BrowserWindow.reload()` (or `Ctrl + Shift + R`). The regular `F5` reload (triggered within the developer tools window) function loads the window properly without causing the error shown above.

**Comment by aleksey-hoffman** [comment]
@codebytere I just found out that the issue is caused by `electron.BrowserWindow.getFocusedWindow().reload()`

 Here's the line in my app:
 
 https://github.com/aleksey-hoffman/sigma-file-manager/blob/8401af78678b25d5ec9825671b3d8d6ab1dc2e27/src/electronMain.js#L606
 
It was working in versions below `v14.0.0` and after the upgrade the window reload breaks when I focus the renderer window and press `Ctrl + Shift + R`

**Comment by aleksey-hoffman** [comment]
@codebytere I just found out that the issue is caused by both `electron.BrowserWindow.getFocusedWindow().reload()` and `app.allowRendererProcessReuse`

It seems that everything is working in all latest Electron versions if there's `app.allowRendererProcessReuse = true` override but as soon as you remove it, the  `electron.BrowserWindow.getFocusedWindow().reload()` function breaks the window reload. The issue happens when I focus the renderer window and press `Ctrl + Shift + R` a few times.

Here's the line causing the issue in my app:
 
https://github.com/aleksey-hoffman/sigma-file-manager/blob/8401af78678b25d5ec9825671b3d8d6ab1dc2e27/src/electronMain.js#L606

**Comment by codebytere** [comment]
@aleksey-hoffman thanks! We still need a standalone reproducible sample though. Your app is fairly complex and it's not quite clear what "break" means or what other configurations I'd need to make when triaging this since i can't reproduce it in stock Fiddle and it's not seen in our tests.

**Comment by aleksey-hoffman** [comment]
@codebytere unfortunately I cannot reproduce it in a minimal app. I will close the issue for now
