### ISSUE TITLE
[Bug]: MenuItemConstructorOptions selector property undocumented (including no TypeScript types).

### ISSUE THREAD

**Issue by dimitropoulos** [electron/electron#30719]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

I searched the documentation [here](https://www.electronjs.org/docs/api/menu-item/history) for versions 6-15.

### What operating system are you using?

macOS

### Operating System Version

n/a

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

- the docs mention the `selector` property of `MenuItemConstructorOptions` and it's function
- the appropriate TypeScript types have this property

### Actual Behavior

I get a typescript error when I define the following:

```ts
const editMenu: MenuItemConstructorOptions = {
  label: `${MNEMONIC_SYM}Edit`,
  submenu: [
    {
      label: `${MNEMONIC_SYM}Undo`,
      accelerator: 'CmdOrCtrl+Z',
      selector: 'undo:',
    },
  ]
}
```

Because the `selector` type has not been defined.

Then, when I search the docs for what this value is, I don't find any information.

### Additional Information

I searched the source code itself for usages, and found https://github.com/electron/electron/blob/f9c6f9af8307b44255621628341f2850f16f186e/lib/browser/api/menu-item.ts#L66-L67 and https://github.com/electron/electron/blob/main/shell/browser/ui/cocoa/electron_menu_controller.mm#L432 to be the main places where this is used.

It is also referenced in https://github.com/electron/electron/issues/1001 and https://github.com/electron/electron/issues/2268, so I at least know it likely does in fact exist.

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

If you cannot find specific current documentation that mentions this `selector` property and its function, then it is most likely a private API that cannot be accessed. I am marking this issue as `blocked/need-repro` for this reason, but if you can find another piece of current documentation that contradicts this, then please link it in a follow-up comment.
