### ISSUE TITLE
Electron set `openAtLogin: true` occasionally, a black screen appears and no operation can be performed !

### ISSUE THREAD

**Issue by glk-hll** [electron/electron#30711]
OS:
```bash
 Windows10 
```

Graphics card：
```bash
NVIDIA Quadro P2200
```

```bash
  "electron": "^13.1.7",
  "electron-builder": "^22.10.5",
```
Display resolution：
```bash
5760*1200
```

My program runs webgl related things，

**Comment by glk-hll** [comment]
And this situation is intermittent. There are other programs that start with my program. It took me almost a week to solve it.

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.
