### ISSUE TITLE
How can I execute a Rust binary in background while the Electron app run?

### ISSUE THREAD

**Issue by ceoshikhar** [electron/electron#30727]
Hey,

I am not sure if this is the right way to find help for my problem but I have tried every other way. Here is the situation, I have a binary written in Rust. It's a simple server. 

Let's assume the binary is called `server`. I have tried to use `spawn`, `exec`, `fork` from `child_process` inside `main.ts` (electrons main process).

I have even tried to create a separate `server.js` which executes the binary and tried to execute `server.js` from `main.ts` but it doesn't work.

An express server inside `server.js` works just fine while the electron app is also running. But if I have an express server and executing the binary inside `server.js`, the express server works but binary does not.

Note: I even created a small test rust binary which creates a `foo.txt` on execution to check maybe my `server` rust binary has some issues and I found out that my binary code doesn't work. Also to note, if I do `node server.js` then it succesfully runs the binary but the same doesn't happen when invoked from electrons main process.

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by vyrzdev** [comment]
@MarshallOfSound if its gonna appear on peoples searches just try and answer the question buddy <3

This post is gonna take the same amount of space on the internet regardless of if you shut it down :9
