### ISSUE TITLE
[Bug]: run .exe, .node can not be recognized on individual Windows 10 Enterprise Edition LTSC

### ISSUE THREAD

**Issue by aochuangkeji** [electron/electron#30723]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

7.3.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise Edition LTSC

### What arch are you using?

x64

### Expected Behavior

Normal operation

### Actual Behavior

Uncaught Exception:
Error:The specified module could not be found.
\\?\C:*****\opencv4nodejs.node

### Additional Information

It runs normally on Windows 10 enterprise edition and reports an error on Windows 10 enterprise edition LTSC

**Comment by MarshallOfSound** [comment]
Electron 7 is EOL, please update to a supported version of Electron

**Comment by aochuangkeji** [comment]
Electron 13.2.2 has the same problem

**Comment by aochuangkeji** [comment]
Electron 13.2.2 has the same problem

**Comment by aochuangkeji** [comment]
> Electron 7 is EOL, please update to a supported version of Electron

But electron 13.2.2 has the same problem

**Comment by miniak** [comment]
@aochuangkeji you haven't provided sufficient repro steps, how are we supposed to help you?
