### ISSUE TITLE
[Bug]: crashReporter upload dump file to server fail

### ISSUE THREAD

**Issue by wscj** [electron/electron#30726]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.16

### What operating system are you using?

Windows

### Operating System Version

1903 and 1709

### What arch are you using?

ia32

### Last Known Working Electron version

11.4.11

### Expected Behavior

After exec `process.crash()` in the devtool, the dump file can be upload to my server.

### Actual Behavior

The dump file did't upload to my server, v12 and v13 electron has this bug.

### Testcase Gist URL

https://gist.github.com/88e92030347e622061f169d3e5df1612

**Comment by diegogangl** [comment]
Not 100% sure it's the same bug, but I can replicate something like this in Linux.

OS: Fedora 34 (5.13.12)
Electron: 13.2.2
Node: 14.17

Reporting fails with  `uploadToServer: true`, but works if it's set to false (creates the dump). This is the error I get:

```
Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
```

I noticed a file does get created, but looks like electron doesn't like it and removes it right away.

**Comment by nornagon** [comment]
We are switching to Crashpad in Electron 16, as breakpad is deprecated. Electron 15 has support for this with the `--enable-crashpad` flag. Could you try this in Electron 15 with `--enable-crashpad`? You can either pass it on the command line, or enable it in your app at startup with

```
const { app } = require('electron')

app.commandLine.appendSwitch('enable-crashpad')
```

**Comment by diegogangl** [comment]
Thanks @nornagon, it seems to work. It's definitely sending something, though I don't have a crashpad server to test the payload

**Comment by nornagon** [comment]
Great to hear. I'm going to close this out as we don't plan to address issues with Breakpad. This will start working with Electron 16 :)

**Comment by Maopy** [comment]
> I add `app.commandLine.appendSwitch('enable-crashpad')` and try with Electron 15 beta1, it has create the dump file, but it still didn't upload the file to my server. @nornagon

Same problem with Electron 13.5.1

**Comment by wscj** [comment]
谢谢来信，祝生活愉快。
