### ISSUE TITLE
[Bug]: transparent window is click through on windows 8.1

### ISSUE THREAD

**Issue by abacaj** [electron/electron#30744]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.11

### What operating system are you using?

Windows

### Operating System Version

Windows 8.1

### What arch are you using?

x64

### Expected Behavior

On windows versions > 8.1 this works and the window is transparent but not click through:

```
  mainWindow = new BrowserWindow({
    transparent: true,
    frame: false,
    alwaysOnTop: true,
    resizable: false,
    maximizable: false,
    hasShadow: false,
    fullscreen: true,
    show: true,
  });
```

### Actual Behavior

On windows 8.1, the transparent window is default click through (any click on the body will click through to the application below it). Clicking on a button works but there is no way to make the window itself not click through + transparent.

There does not seem to be any way to fix it, i.e make the window transparent but not click through.

Have tried:

```
mainWindow.setIgnoreMouseEvents(false);
```

### Testcase Gist URL

https://gist.github.com/abacaj/88bd4ab1b2d28422184f1610e8f930a4

### Additional Information

The only fix I can find is to set a background-color on the body element, i.e `background-color: #ffffff` but this defeats the purpose of a transparent window.

Can provide screenshots if necessary, but the issue is pretty self explanatory.

**Comment by abacaj** [comment]
Found this issue which is the opposite of what is expected in my bug above: https://github.com/electron/electron/issues/1335

**Comment by abacaj** [comment]
Came up with: `background-color: rgba(255,255,255,0.01)`

But obviously, it adds a subtle but noticeable tint to the window:
![image](https://user-images.githubusercontent.com/7272343/131235811-b1ab382b-6a7a-49f5-83db-b5799d81b88a.png)

I hope there is a better way.

**Comment by Seraphli** [comment]
same here on Windows 10
I use this template
https://github.com/cawa-93/vite-electron-builder
and just add
```
frame: false,
transparent: true
```
And the window is click through. But the same setting is not click through on MacOS.
So how can I set the window not click through on Windows?
