### ISSUE TITLE
Whenever i start the discord bot silent it just showes me a gray screen and thats all its like frozen

### ISSUE THREAD

**Issue by RVYT** [electron/electron#30743]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

It starts but its gray and frozen

### Actual Behavior

its starting usualy but not anymore

### Testcase Gist URL

https://github.com/Flam3rboy/discord-bot-client

### Additional Information

ITS BROKEN

**Comment by TacticalModz** [comment]
Same problem here.

**Comment by Dyrgo** [comment]
> ### Preflight Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.
> 
> ### Electron Version
> 12.0.0
> 
> ### What operating system are you using?
> Windows
> 
> ### Operating System Version
> Windows 10
> 
> ### What arch are you using?
> x64
> 
> ### Last Known Working Electron version
> _No response_
> 
> ### Expected Behavior
> It starts but its gray and frozen
> 
> ### Actual Behavior
> its starting usualy but not anymore
> 
> ### Testcase Gist URL
> https://github.com/Flam3rboy/discord-bot-client
> 
> ### Additional Information
> ITS BROKEN

Same problem

**Comment by codebytere** [comment]
Please report this to the app itself unless this can be specifically demonstrated to be a problem with Electron.

**Comment by ZM0KIE** [comment]
Same problem here, just installed it from the windows installer.

**Comment by MelvinSGjr** [comment]
same problem, try with the vpn

**Comment by YogTandel23** [comment]
same problem here
