### ISSUE TITLE
[Bug]: BrowserWindow backgroundColor doesn't work in Electron 14 and 15

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#30759]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0-beta.11

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1, macOS 11.5.1

### What arch are you using?

x64

### Last Known Working Electron version

14.0.0-beta.10

### Expected Behavior

Creating a BrowserWindow with the `backgroundColor` option results in the new window displaying that color behind the transparent WebContents.

### Actual Behavior

Creating a BrowserWindow with the `backgroundColor` option results in the new window displaying a white background color behind the transparent WebContents.

### Testcase Gist URL

https://gist.github.com/4256f388d41ef0d974645a11ab72b1fe

### Additional Information

The problematic version was discovered using Electron Fiddle's bisect feature.
https://github.com/electron/electron/compare/v14.0.0-beta.10...v14.0.0-beta.11

#30136 seems related

I'm not seeing this behavior in a testing build of current `main` (8007d018749cd1038c755d86335e4fd89cd8f2ef).

I'm looking into a fix, will update as progress is made.

**Comment by codebytere** [comment]
@samuelmaddock this appears to only be happening within a certain range 🤔 it works properly on `16.0.0-nightly.20210726` and beyond.

**Comment by andmm** [comment]
Same bug here on 14.0.0 final on win 7.

**Comment by samuelmaddock** [comment]
> @samuelmaddock this appears to only be happening within a certain range 🤔 it works properly on `16.0.0-nightly.20210727` and beyond.
> 
> [v16.0.0-nightly.20210726...v16.0.0-nightly.20210727](https://github.com/electron/electron/compare/v16.0.0-nightly.20210726...v16.0.0-nightly.20210727)

It's fixed after the introduction of https://github.com/electron/electron/pull/30193

**Comment by samuelmaddock** [comment]
This works: https://github.com/electron/electron/blob/dd7aeda6fbcd72de4029f946a57e6c96d8abfba7/shell/browser/api/electron_api_web_contents.cc#L1373-L1378

This does not work:
```diff
-rwhv->SetBackgroundColor(web_preferences->GetBackgroundColor()); 
+rwhv->SetBackgroundColor(SK_ColorRED);
```

🤔🤔🤔

**Comment by samuelmaddock** [comment]
Sometimes on startup, you can see the correct background color set, then immediately gets replaced with a white background color. I believe initially it shows the native window color followed by the RenderWidgetHostView's background.

Setting the background to transparent allows the native window's background color to show up:
```
rwhv->SetBackgroundColor(SK_ColorTRANSPARENT);
```

#30193 may have actually broken `web_preferences->GetBackgroundColor()` causing it to always return a background color value of `0` (fully transparent). On Electron v16, the "fixed" background color we're actually seeing is the background of the native window.

**Comment by samuelmaddock** [comment]
The white background color is coming from the page background color defined in Blink: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/exported/web_view_impl.cc;l=3049-3058;drc=98898daa2e8f46ff098cea1f2e218f8a8266c838
```cpp
  // Use the page background color if this is the WebView of the main frame.
  if (MainFrameImpl())
    return page_base_background_color_;
```

To update this color, we need to call `WebContents::SetPageBaseBackgroundColor()`. This was reverted in #30136 which we'll need to pay special attention to with a fix.

**Comment by samuelmaddock** [comment]
#30777 will solve the problem for Electron 14 and 15. `main` will need a separate PR since the WebPreferences refactor makes the code quite a bit different.

**Comment by andmm** [comment]
I gotta say something... it's concerning when a project the size of electron can't keep a simple API working across major versions. This is not the first time. Last time for me was the 'ready-to-show' event on the main window wasn't firing as it should. This is the basic API of electron... it has to keep compatibility between versions... this is a project backed by a billionaire corporation. Wtf is happening here

**Comment by jkleinsc** [comment]
@andmm your comment was deleted as a violation of the Electron Code of Conduct. You may consider this an official warning.

Please do not interact with the project for 24 hours. After that, please look through your open issues and edit them to ensure they're entirely on-topic, and we can continue the discussion here about the best way to go forward.
