### ISSUE TITLE
[Bug]: Incomplete v14.0.0 release notes

### ISSUE THREAD

**Issue by Prinzhorn** [electron/electron#30767]
I haven't followed the release very closely but I'm confident this is not it: https://github.com/electron/electron/releases/tag/v14.0.0

![Selection_966](https://user-images.githubusercontent.com/679144/131545822-dee41116-c0f0-4825-b73a-7d76c61fa62b.png)

**Comment by pushkin-** [comment]
you're saying that there should be more release notes? I believe last time this happened, it took some time for it to get filled out with the rest of the notes for whatever reason. - like a day or so

**Comment by Prinzhorn** [comment]
> you're saying that there should be more release notes?

Like a hundreds fixes and stuff? Basically all 25 betas accumulated. Compare with 13 https://github.com/electron/electron/releases/tag/v13.0.0
