### ISSUE TITLE
[Bug]: Frameless window displays frame while opening

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#30760]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0-beta.25

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1

### What arch are you using?

x64

### Last Known Working Electron version

14.0.0-beta.3

### Expected Behavior

Opening a frameless window and immediately revealing it (instead of waiting for `ready-to-show` event) shows no content inside of the window.

### Actual Behavior

Opening a frameless window and immediately revealing it (instead of waiting for `ready-to-show` event) shows an older style window frame with no content inside.

| 14.0.0-beta.3 | 14.0.0-beta.5 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1656324/131413708-cc472e02-21d7-4fc8-9a6b-ca38391b7911.png) |  ![image](https://user-images.githubusercontent.com/1656324/131413746-ac2e389f-1528-4f60-886b-25a93ef8e217.png) |

https://user-images.githubusercontent.com/1656324/131413659-18c2ea6c-d1c4-489f-8182-ae19cba51bcb.mp4

### Testcase Gist URL

https://gist.github.com/4256f388d41ef0d974645a11ab72b1fe

### Additional Information

This may not be a bug, but I felt that displaying the frame while the window is opening was maybe not intentional.

**Comment by samuelmaddock** [comment]
Setting backgroundColor to `#00000000` (alpha included) shows this until the window is resized:

![image](https://user-images.githubusercontent.com/1656324/131576965-0570fd1c-67a6-46bc-9cd6-7424cc1b5e78.png)

**Comment by aleksey-hoffman** [comment]
I also noticed this issue after upgrading to `v14.0.0`

**Comment by aleksey-hoffman** [comment]
I also noticed this issue. It's reproducible in `v14.0.0 - v15.0.0-beta.1`

**Comment by mustafaabobakr** [comment]
Hi 
Any news on this?

**Comment by codebytere** [comment]
Bisected to [14.0.0-beta.5](https://github.com/electron/electron/compare/v14.0.0-beta.3...v14.0.0-beta.5)

**Comment by mustafaabobakr** [comment]
> Bisected to

Hi, am using v16.0.4 should I downgrade to v13 ?

**Comment by deepak1556** [comment]
Reopening for https://github.com/electron/electron/pull/33599

**Comment by deepak1556** [comment]
Although there is a user facing workaround, it is worth investigating why this code path regressed with the chromium roll bisected in this range https://github.com/electron/electron/issues/30760#issuecomment-1025586864

**Comment by Tarrowren** [comment]
I also noticed that the actual size of the window is a turn smaller than it looks. When dragging the scrollbar with the mouse you often accidentally click on the window zoom.
![1](https://user-images.githubusercontent.com/35626141/171562345-3990b719-77f9-432b-8548-a859c6f64147.gif)
![2](https://user-images.githubusercontent.com/35626141/171562677-0d6c48b1-63a8-44da-995f-4d60d5e0d148.gif)

**Comment by infinnie** [comment]
> I also noticed that the actual size of the window is a turn smaller than it looks. When dragging the scrollbar with the mouse you often accidentally click on the window zoom.
![1](https://user-images.githubusercontent.com/35626141/171562345-3990b719-77f9-432b-8548-a859c6f64147.gif)

But it’s been so since Electron 13.x.

**Comment by rzhao271** [comment]
Bisected to https://github.com/electron/electron/commit/172ac2501330c64c2a33c1004e05eb23f9658903.
Though a lot of things happened during that roll: https://chromium.googlesource.com/chromium/src/+log/92.0.4511.0..93.0.4530.0?n=10000&pretty=fuller

**Comment by deepak1556** [comment]
@pushkin- https://github.com/electron/electron/issues/30024 is not a dupe although they share the same root cause of how the style `WS_THICKFRAME` presence impacts `WS_CAPTION` for frameless windows. Also, https://github.com/electron/electron/pull/35189 currently does not address it. It only tries to restore the behavior of frameless window which are resizable to how it was before the chromium roll https://github.com/electron/electron/issues/30760#issuecomment-1191738739
