### ISSUE TITLE
[Bug]: windows overlay control loss hover effect

### ISSUE THREAD

**Issue by weifeiyue** [electron/electron#30764]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 1909

### What arch are you using?

ia32

### Expected Behavior

![2](https://user-images.githubusercontent.com/19370201/131465320-9409423d-ca68-49ce-b318-eb9c2700f04d.gif)

### Actual Behavior

![1](https://user-images.githubusercontent.com/19370201/131465334-04df5820-0609-41a5-9e45-ee4f8ff70760.gif)

### Testcase Gist URL

https://gist.github.com/weifeiyue/b4128f21d8d9e4b9da4cef61038281c4

### Additional Information

```js
const { BrowserWindow, app } = require('electron')

app.on('ready', () => {
    const win = new BrowserWindow({
        width: 800,
        height: 600,
        titleBarStyle: 'hidden',
        titleBarOverlay: true
    })
    win.loadFile('index.html')
})
```

just load a file, it will loss hover effect 
```js
win.loadFile('index.html')
```

**Comment by weifeiyue** [comment]
@jkleinsc can you help me? 😭😭😭

**Comment by mlaurencin** [comment]
Thank you for reporting this. This looks to be an issue also being tracked upstream in Chromium [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1218921&can=1&q=component%3AUI%3EBrowser%3EWebAppInstalls%3EWindowControlsOverlay%20hover). Once a fix is introduced there, we'll look to incorporate it as well.

**Comment by weifeiyue** [comment]
@mlaurencin thank you for the reply 😊

**Comment by tctg-bryan** [comment]
@mlaurencin it seems this was fixed about a month ago on the chromium side - any idea when it will be fixed in electron?

**Comment by mlaurencin** [comment]
@tctg-bryan  Unfortunately, this fix causes another bug to occur. An [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1271293#c1) was created that was subsequently marked as Won't Fix, so another possible solution needs to be explored.

**Comment by mlaurencin** [comment]
I have summarized the current state of this issue here https://github.com/electron/electron/issues/32360. I am going to close this issue so that future developments can be directed to that one thread, but this one will still serve as the original reference.
