### ISSUE TITLE
[Bug]: persistent high cpu usage

### ISSUE THREAD

**Issue by bruceauyeung** [electron/electron#30763]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.2.0 32bit version

### What operating system are you using?

Windows

### Operating System Version

Windows 7 Pro Service Pack 1 64bit

### What arch are you using?

ia32

### Last Known Working Electron version

unknown

### Expected Behavior

normal cpu usage

### Actual Behavior

background: 
this windows 7 runs on  KVM 
it has simulated CPU: intel core processor (haswell, no TSX, IBRS)
we use electron + nod-ffi-napi + some dlls to build an instant message client.
we also launched a qt5 instance in this renderer process.
today i noticed that renderer process was consuming lots of cpu when i think it should be very idle,
process explorer shows there are 2 threads consuming cpu badly, and these 2 threads are doing things very similarly.
please let know if you need any information else.
 
![image](https://user-images.githubusercontent.com/1210201/131431704-803a0d1c-21ed-4567-8ce1-ac199fcab253.png)

**Comment by aleksey-hoffman** [comment]
I'd suggest you create an new empty Electron app on the same system and then open a new renderer window without any content and check the CPU usage to make sure the problem is caused by Electron and not some function in your code.
