### ISSUE TITLE
[Bug]: enableRemoteModule option falsely removed from documentations and .d.ts  as of Electron v14

### ISSUE THREAD

**Issue by nomagick** [electron/electron#30789]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

macOS

### Operating System Version

20F71

### What arch are you using?

x64

### Last Known Working Electron version

13.2.1

### Expected Behavior

enableRemoteModule being a member of type WebPreferences.

### Actual Behavior

enableRemoteModule NOT being a member of type WebPreferences.

### Additional Information

Might related to 5b205731f6ff77372656f0c85c52b703ec523e6f

Although remote was removed from the core modules.

The `enableRemoteModule` of `WebPreferences` is still relevant and required when using '@electrion/remote'

**Comment by daidi** [comment]
+1, need to be fixed

**Comment by phonegap100** [comment]
+1, need to be fixed

**Comment by MarshallOfSound** [comment]
`@electron/remote` is effectively a third party module, we should not have type support in the core `electron` types for an external package.  The types should be provided / modified by the `@electron/remote` package.  Please raise this issue there.

**Comment by noseratio** [comment]
So `enableRemoteModule` is still in Electron v14, there but the TypeScript type def is now missing from `electron.d.ts electron.d.ts`. I'm `as electron.WebPreferences` cast as a simple workaround for now, ugly but works:

```TypeScript
  const window = new electron.BrowserWindow({
    webPreferences: { 
      plugins: true, 
      nodeIntegration: true, 
      contextIsolation: false,
      enableRemoteModule: true, 
      backgroundThrottling: false,
      webSecurity: false 
      // need the cast because "enableRemoteModule" is missing from Electron 14 type defs
    } as electron.WebPreferences, 
    // ...
  });
```

**Comment by nomagick** [comment]
> So `enableRemoteModule` is still in Electron v14, there but the TypeScript type def is now missing from `electron.d.ts electron.d.ts`. I'm `as electron.WebPreferences` cast as a simple workaround for now, ugly but works:
> 
> ```ts
>   const window = new electron.BrowserWindow({
>     webPreferences: { 
>       plugins: true, 
>       nodeIntegration: true, 
>       contextIsolation: false,
>       enableRemoteModule: true, 
>       backgroundThrottling: false,
>       webSecurity: false 
>       // need the cast because "enableRemoteModule" is missing from Electron 14 type defs
>     } as electron.WebPreferences, 
>     // ...
>   });
> ```

The check on `enableRemoteModule` has always been on the `@electron/remote` side.
This walkaround will work on the current `@electron/remote` version `v1.2.1` but may break on their next release.

https://github.com/electron/remote/pull/72

**Comment by noseratio** [comment]
> The check on `enableRemoteModule` has always been on the `@electron/remote` side.
> This walkaround will work on the current `@electron/remote` version `v1.2.1` but may break on their next release.

@nomagick, I create this window from the main (node) process. Unless I force `enableRemoteModule: true` as above, inside the renderer (browser) I get this:

```text
@electron/remote is disabled for this WebContents. Set {enableRemoteModule: true} in WebPreferences to enable it.
```

What's the proper way of dealing with this?

**Comment by noseratio** [comment]
> `@electron/remote` is effectively a third party module, we should not have type support in the core `electron` types for an external package. The types should be provided / modified by the `@electron/remote` package. Please raise this issue there.

@MarshallOfSound, maybe I'm missing something, but I create this window from the *main* process (that naturally doesn't import use `@electron/remote`):

```TypeScript
const window = new electron.BrowserWindow({
    webPreferences: { 
      plugins: true, 
      nodeIntegration: true, 
      contextIsolation: false,
      enableRemoteModule: true, 
      backgroundThrottling: false,
      webSecurity: false 
      // need the cast because "enableRemoteModule" is missing from Electron 14 type defs
    } as electron.WebPreferences, 
    // ...
  });
```

Without the `as electron.WebPreferences` workaround, I'm unable to specify `enableRemoteModule: true` in TypeScript.  And if I don't specify it, then in the *renderer* process (where I do import  `@electron/remote`), I'm getting this error

```text
@electron/remote is disabled for this WebContents. Set {enableRemoteModule: true} in WebPreferences to enable it.
```

Looks to me like we still need a proper definition for `enableRemoteModule` independently of `@electron/remote`?

**Comment by Mami16glcn** [comment]
> start

**Comment by nornagon** [comment]
See electron/remote#72.
