### ISSUE TITLE
[Bug]: Electron app crashes on M1 macOS after closing the app

### ISSUE THREAD

**Issue by ojbz** [electron/electron#30786]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.2.1

### What operating system are you using?

macOS

### Operating System Version

macOS 11.4 (20F71)

### What arch are you using?

x64

### Expected Behavior

After quitting app, app should close normally.

### Actual Behavior

Electron app crashes on M1 macOS after quitting the app.
the crash looks like...

`Code Type:             X86-64 (Translated)
Parent Process:        ??? [1]
Responsible:           LF Talk2 [37641]
User ID:               501

Date/Time:             2021-08-23 17:38:49.861 +0900
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Anonymous UUID:        A360964D-8586-2AF2-D557-1D2D0CAB739D

Sleep/Wake UUID:       4A1522C4-8562-485B-8705-3557139BF69F

Time Awake Since Boot: 41000 seconds
Time Since Wake:       13000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [37641]

VM Regions Near 0:
--> 
    __TEXT                      102381000-1023d1000    [  320K] r-x/r-x SM=COW  

Application Specific Information:
Calling windowShouldClose: on the delegate for the ElectronNSWindow 0x7f8526d4c8f0

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   com.github.Electron.framework 	0x000000010a815274 ElectronInitializeICUandStartNode + 1218580
1   com.github.Electron.framework 	0x000000010a6fcb84 ElectronInitializeICUandStartNode + 69924
2   com.github.Electron.framework 	0x000000010aed97cf v8::internal::baseline::BytecodeOffsetIterator::UpdatePointers() + 8975
3   ???                           	0x00000078000b23b8 ???
4   ???                           	0x0000007800049541 ???
5   ???                           	0x0000007800049541 ???
6   ???                           	0x00000078000475fb ???
7   ???                           	0x0000007800047383 ???
8   com.github.Electron.framework 	0x000000010af4e50b v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle< v8::internal::Object>, v8::internal::Handle< v8::internal::Object>, int, v8::internal::Handle< v8::internal::Object>*) + 667
9   com.github.Electron.framework 	0x000000010aeac4e3 v8::Function::Call(v8::Local< v8::Context>, v8::Local< v8::Value>, int, v8::Local< v8::Value>*) + 579
10  com.github.Electron.framework 	0x000000010dacdcb3 node::CallbackScope::~CallbackScope() + 2003
11  com.github.Electron.framework 	0x000000010dacdfb6 node::MakeCallback(v8::Isolate*, v8::Local< v8::Object>, v8::Local< v8::Function>, int, v8::Local< v8::Value>*, node::async_context) + 182
12  com.github.Electron.framework 	0x000000010a82a6cc ElectronInitializeICUandStartNode + 1305708
13  com.github.Electron.framework 	0x000000010a70d817 ElectronInitializeICUandStartNode + 138679
14  com.github.Electron.framework 	0x000000010a705eee ElectronInitializeICUandStartNode + 107662
15  com.github.Electron.framework 	0x000000010a7060e9 ElectronInitializeICUandStartNode + 108169
16  com.github.Electron.framework 	0x000000010a7c41fc ElectronInitializeICUandStartNode + 886684
17  com.github.Electron.framework 	0x000000010a8751bd ElectronInitializeICUandStartNode + 1611613
18  com.apple.CoreFoundation      	0x00007fff2041cd89 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
19  com.apple.CoreFoundation      	0x00007fff204b8748 ___CFXRegistrationPost_block_invoke + 49
20  com.apple.CoreFoundation      	0x00007fff204b86c5 _CFXRegistrationPost + 454
21  com.apple.CoreFoundation      	0x00007fff203ee024 _CFXNotificationPost + 795
22  com.apple.Foundation          	0x00007fff21086dc8 -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
23  com.apple.AppKit              	0x00007fff234046db -[NSWindow _finishClosingWindow] + 124
24  com.apple.AppKit              	0x00007fff22e94db0 -[NSWindow _close] + 347
25  com.github.Electron.framework 	0x000000010a8675ab ElectronInitializeICUandStartNode + 1555275
26  com.github.Electron.framework 	0x000000010a718246 ElectronInitializeICUandStartNode + 182246
27  com.github.Electron.framework 	0x000000010a77082f ElectronInitializeICUandStartNode + 544207
28  com.github.Electron.framework 	0x000000010bc9ec3c v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5950908
29  com.github.Electron.framework 	0x000000010ec56b60 v8::internal::compiler::GetI32WasmCallDescriptorForSimd(v8::internal::Zone*, v8::internal::compiler::CallDescriptor*) + 3675040
30  com.github.Electron.framework 	0x000000010a7c5799 ElectronInitializeICUandStartNode + 892217
31  com.github.Electron.framework 	0x000000010a875354 ElectronInitializeICUandStartNode + 1612020
32  com.apple.AppKit              	0x00007fff22ee2209 __19-[NSWindow __close]_block_invoke + 153
33  com.apple.AppKit              	0x00007fff22ee2163 -[NSWindow __close] + 284
34  com.apple.AppKit              	0x00007fff22d7170b -[NSApplication(NSResponder) sendAction:to:from:] + 288
35  com.apple.AppKit              	0x00007fff22d715af -[NSControl sendAction:to:] + 86
36  com.apple.AppKit              	0x00007fff22d714e1 __26-[NSCell _sendActionFrom:]_block_invoke + 131
37  com.apple.AppKit              	0x00007fff22d713e8 -[NSCell _sendActionFrom:] + 171
38  com.apple.AppKit              	0x00007fff22d7132e -[NSButtonCell _sendActionFrom:] + 96
39  com.apple.AppKit              	0x00007fff22eb02b9 __29-[NSButtonCell performClick:]_block_invoke + 64
40  com.apple.AppKit              	0x00007fff22eaff7d -[NSButtonCell performClick:] + 697
41  com.github.Electron.framework 	0x000000010a875eaa ElectronInitializeICUandStartNode + 1614922
42  com.github.Electron.framework 	0x000000010a86752a ElectronInitializeICUandStartNode + 1555146
43  com.github.Electron.framework 	0x000000010a70e670 ElectronInitializeICUandStartNode + 142352
44  com.github.Electron.framework 	0x000000010aed97cf v8::internal::baseline::BytecodeOffsetIterator::UpdatePointers() + 8975
45  ???                           	0x00000078000b23b8 ???
46  ???                           	0x0000007800049541 ???
47  ???                           	0x0000007800049541 ???
48  ???                           	0x0000007800049541 ???
49  ???                           	0x0000007800049541 ???
50  ???                           	0x0000007800049541 ???
51  ???                           	0x00000078000475fb ???
52  ???                           	0x0000007800047383 ???
53  com.github.Electron.framework 	0x000000010af4e50b v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle< v8::internal::Object>, v8::internal::Handle< v8::internal::Object>, int, v8::internal::Handle< v8::internal::Object>*) + 667
54  com.github.Electron.framework 	0x000000010aeac4e3 v8::Function::Call(v8::Local< v8::Context>, v8::Local< v8::Value>, int, v8::Local< v8::Value>*) + 579
55  com.github.Electron.framework 	0x000000010dacdcb3 node::CallbackScope::~CallbackScope() + 2003
56  com.github.Electron.framework 	0x000000010dacdfb6 node::MakeCallback(v8::Isolate*, v8::Local< v8::Object>, v8::Local< v8::Function>, int, v8::Local< v8::Value>*, node::async_context) + 182
57  com.github.Electron.framework 	0x000000010a82a6cc ElectronInitializeICUandStartNode + 1305708
58  com.github.Electron.framework 	0x000000010a7858ea ElectronInitializeICUandStartNode + 630410
59  com.github.Electron.framework 	0x000000010a773a29 ElectronInitializeICUandStartNode + 557001
60  com.github.Electron.framework 	0x000000010a77406d ElectronInitializeICUandStartNode + 558605
61  com.github.Electron.framework 	0x000000010a7b459a ElectronInitializeICUandStartNode + 822074
62  com.github.Electron.framework 	0x000000010bea383c v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 8067516
63  com.github.Electron.framework 	0x000000010a7b48db ElectronInitializeICUandStartNode + 822907
64  com.github.Electron.framework 	0x000000010c1f0351 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 11527377
65  com.github.Electron.framework 	0x000000010c1f2825 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 11536805
66  com.github.Electron.framework 	0x000000010c1faf4e v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 11571406
67  com.github.Electron.framework 	0x000000010c1f2825 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 11536805
68  com.github.Electron.framework 	0x000000010c1ec954 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 11512532
69  com.github.Electron.framework 	0x000000010c20bf65 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 11641061
70  com.github.Electron.framework 	0x000000010c049bfc v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9796988
71  com.github.Electron.framework 	0x000000010c061ed6 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9896022
72  com.github.Electron.framework 	0x000000010c099ee0 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10125408
73  com.github.Electron.framework 	0x000000010c0964c2 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10110530
74  com.github.Electron.framework 	0x000000010c0996ff v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10123391
75  com.apple.CoreFoundation      	0x00007fff204276dc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
76  com.apple.CoreFoundation      	0x00007fff20427644 __CFRunLoopDoSource0 + 180
77  com.apple.CoreFoundation      	0x00007fff204273ba __CFRunLoopDoSources0 + 242
78  com.apple.CoreFoundation      	0x00007fff20425dc8 __CFRunLoopRun + 897
79  com.apple.CoreFoundation      	0x00007fff20425380 CFRunLoopRunSpecific + 567
80  com.apple.HIToolbox           	0x00007fff288c5ab3 RunCurrentEventLoopInMode + 292
81  com.apple.HIToolbox           	0x00007fff288c5815 ReceiveNextEventCommon + 587
82  com.apple.HIToolbox           	0x00007fff288c55b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
83  com.apple.AppKit              	0x00007fff22b506f2 _DPSNextEvent + 864
84  com.apple.AppKit              	0x00007fff22b4eec5 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
85  com.apple.AppKit              	0x00007fff22b41239 -[NSApplication run] + 586
86  com.github.Electron.framework 	0x000000010c09a586 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10127110
87  com.github.Electron.framework 	0x000000010c0991db v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10122075
88  com.github.Electron.framework 	0x000000010c0632af v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9901103
89  com.github.Electron.framework 	0x000000010c03590c v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 9714316
90  com.github.Electron.framework 	0x000000010b9bcda1 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 2928417
91  com.github.Electron.framework 	0x000000010b9be522 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 2934434
92  com.github.Electron.framework 	0x000000010b9ba424 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 2917796
93  com.github.Electron.framework 	0x000000010ae12ea7 electron::fuses::IsCookieEncryptionEnabled() + 5721719
94  com.github.Electron.framework 	0x000000010ae129a8 electron::fuses::IsCookieEncryptionEnabled() + 5720440
95  com.github.Electron.framework 	0x000000010ae11af6 electron::fuses::IsCookieEncryptionEnabled() + 5716678
96  com.github.Electron.framework 	0x000000010ae11be2 electron::fuses::IsCookieEncryptionEnabled() + 5716914
97  com.github.Electron.framework 	0x000000010a6eba26 ElectronMain + 134
98                                	0x00000001023827e6 0x102381000 + 6118
99  libdyld.dylib                 	0x00007fff20349f5d start + 1`

**Comment by Jelmerro** [comment]
Last time I had the opportunity to check on an M1 mac, this was still happening, but I am unsure as to which Electron version it was. Either 18 or 19, but given the lack of updates I would expect this to still be an issue. Maybe @ojbz could confirm this.

**Comment by jnehlmeier** [comment]
Also happens on Intel CPU in macOS Ventura 13.1 using for example https://github.com/evolus/pencil/tree/v3.1.1

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Pencil [87456]
Path:                  /Applications/Pencil.app/Contents/MacOS/Pencil
Identifier:            vn.evolus.pencil
Version:               3.1.1 (3.1.1)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-01-04 11:33:07.4057 +0100
OS Version:            macOS 13.1 (22C65)
Report Version:        12
Bridge OS Version:     7.1 (20P2059)
Anonymous UUID:        672D364C-82BE-40DC-BEB8-FB41377DBDE6

Sleep/Wake UUID:       EABB8481-6722-4EDD-8DB0-E2B045EA1116

Time Awake Since Boot: 73000 seconds
Time Since Wake:       65136 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000130
Exception Codes:       0x0000000000000001, 0x0000000000000130

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [87456]

VM Region Info: 0x130 is not in any region.  Bytes before following region: 140737486839504
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      shared memory            7fffffe8e000-7fffffe8f000 [    4K] r-x/r-x SM=SHM  

Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   Electron Framework            	       0x115608357 ElectronInitializeICUandStartNode + 1770775
1   CoreFoundation                	    0x7ff8111bb3f4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 137
2   CoreFoundation                	    0x7ff81125543a ___CFXRegistrationPost_block_invoke + 88
3   CoreFoundation                	    0x7ff811255389 _CFXRegistrationPost + 536
4   CoreFoundation                	    0x7ff81118e919 _CFXNotificationPost + 735
5   Foundation                    	    0x7ff811fc8f2c -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
6   AppKit                        	    0x7ff814c58761 -[NSWindow _finishClosingWindow] + 124
7   AppKit                        	    0x7ff81461476b -[NSWindow _close] + 336
8   Electron Framework            	       0x1155fa6bb ElectronInitializeICUandStartNode + 1714299
9   Electron Framework            	       0x11548969c ElectronInitializeICUandStartNode + 202844
10  Electron Framework            	       0x115488ad0 ElectronInitializeICUandStartNode + 199824
11  Electron Framework            	       0x117c8540e v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10786094
12  Electron Framework            	       0x117c8451e v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10782270
13  Electron Framework            	       0x117c8586e v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 10787214
14  Electron Framework            	       0x11557c054 ElectronInitializeICUandStartNode + 1196564
15  Electron Framework            	       0x11557c26e ElectronInitializeICUandStartNode + 1197102
16  Electron Framework            	       0x1154e1be1 ElectronInitializeICUandStartNode + 564641
17  Electron Framework            	       0x1154e201e ElectronInitializeICUandStartNode + 565726
18  Electron Framework            	       0x1154f925a ElectronInitializeICUandStartNode + 660506
19  Electron Framework            	       0x11863047b _TIFFSwab64BitData + 5067515
20  Electron Framework            	       0x11864ae93 _TIFFSwab64BitData + 5176595
21  Electron Framework            	       0x11868c95e base::mac::CxxPersonalityRoutine(int, _Unwind_Action, unsigned long long, _Unwind_Exception*, _Unwind_Context*) + 3678
22  Electron Framework            	       0x11868bb22 base::mac::CxxPersonalityRoutine(int, _Unwind_Action, unsigned long long, _Unwind_Exception*, _Unwind_Context*) + 34
23  Electron Framework            	       0x11868c0ef base::mac::CxxPersonalityRoutine(int, _Unwind_Action, unsigned long long, _Unwind_Exception*, _Unwind_Context*) + 1519
24  CoreFoundation                	    0x7ff8111c5b98 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
25  CoreFoundation                	    0x7ff8111c5b47 __CFRunLoopDoSource0 + 157
26  CoreFoundation                	    0x7ff8111c5921 __CFRunLoopDoSources0 + 212
27  CoreFoundation                	    0x7ff8111c459b __CFRunLoopRun + 929
28  CoreFoundation                	    0x7ff8111c3b80 CFRunLoopRunSpecific + 560
29  HIToolbox                     	    0x7ff81ab08766 RunCurrentEventLoopInMode + 292
30  HIToolbox                     	    0x7ff81ab08576 ReceiveNextEventCommon + 679
31  HIToolbox                     	    0x7ff81ab082b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
32  AppKit                        	    0x7ff81430ff33 _DPSNextEvent + 909
33  AppKit                        	    0x7ff81430edb4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
34  AppKit                        	    0x7ff8143013f7 -[NSApplication run] + 586
35  Electron Framework            	       0x11868d116 base::mac::CxxPersonalityRoutine(int, _Unwind_Action, unsigned long long, _Unwind_Exception*, _Unwind_Context*) + 5654
36  Electron Framework            	       0x11868bb92 base::mac::CxxPersonalityRoutine(int, _Unwind_Action, unsigned long long, _Unwind_Exception*, _Unwind_Context*) + 146
37  Electron Framework            	       0x11864c1ea _TIFFSwab64BitData + 5181546
38  Electron Framework            	       0x118616681 _TIFFSwab64BitData + 4961537
39  Electron Framework            	       0x1177be885 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5777829
40  Electron Framework            	       0x1177c02e2 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5784578
41  Electron Framework            	       0x1177bc05a v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5767546
42  Electron Framework            	       0x116511ba3 cdef_copy_rect8_16bit_to_16bit_sse4_1 + 10290339
43  Electron Framework            	       0x11651163b cdef_copy_rect8_16bit_to_16bit_sse4_1 + 10288955
44  Electron Framework            	       0x11651000b cdef_copy_rect8_16bit_to_16bit_sse4_1 + 10283275
45  Electron Framework            	       0x116510909 cdef_copy_rect8_16bit_to_16bit_sse4_1 + 10285577
46  Electron Framework            	       0x115457e06 ElectronMain + 134
47  Pencil                        	       0x104764d36 0x104764000 + 3382
48  dyld                          	    0x7ff810db7310 start + 2432

```

**Comment by mqliutie** [comment]
any updates?
