### ISSUE TITLE
[Bug]: Postinstall script failed with: RequestError: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Qi2013** [electron/electron#30793]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.2.3

### What operating system are you using?

Ubuntu

### Operating System Version

docker/node:12

### What arch are you using?

x64

### Last Known Working Electron version

8.5.5

### Expected Behavior

I can install the project dependences including electron with "npm ci" on my local machine. I expect the same will happen in the giblab ci pipline. The gitlab runner uses the same docker image of node. 

### Actual Behavior

> electron@13.2.3 postinstall /builds/viewer/node_modules/electron
> node install.js
RequestError: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/builds/viewer/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/builds/viewer/node_modules/@electron/get/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm verb lifecycle electron@13.2.3~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle electron@13.2.3~postinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/builds/viewer/node_modules/electron/node_modules/.bin:/builds/viewer/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle electron@13.2.3~postinstall: CWD: /builds/viewer/node_modules/electron
npm info lifecycle electron@13.2.3~postinstall: Failed to exec postinstall script
npm verb teardown shutting down workers.
npm info teardown Done in 0s
npm verb stack Error: electron@13.2.3 postinstall: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:400:28)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:400:28)
npm verb stack     at maybeClose (internal/child_process.js:1055:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid electron@13.2.3
npm verb cwd /builds/viewer
npm verb Linux 3.10.0-1127.19.1.el7.x86_64
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "ci" "--verbose"
npm verb node v14.17.5
npm verb npm  v6.14.14
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@13.2.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@13.2.3 postinstall script.

### Additional Information

I thought it was a proxy problem. Howerver, my local machine is behinde the same proxy and we have set the variable in the runner.  And electron 8.5.5 works fine, electron 11 already does not work.

I also tried to set:

    - npm config set strict-ssl false
    - npm cache clean --force
   
They did not work.

**Comment by sambaran69** [comment]
I am getting the same error on Mac (macOS 11.6) when i try to install react-devtools - `yarn global add react-devtools`. There is no corporate firewall and I have tried fixing it by setting `strict-ssl` to `false`.

**Comment by Acanguven** [comment]
`export NODE_TLS_REJECT_UNAUTHORIZED=0` solves the problem

**Comment by wangjbo** [comment]
> 
 can i code the line export NODE_TLS_REJECT_UNAUTHORIZED=0  in which file？

**Comment by nornagon** [comment]
Looks like this is a local configuration issue, not an Electron issue, so I'm closing this.
