### ISSUE TITLE
[Bug]: Crash in WebContents::RenderFrameHostChanged on line CHECK_EQ(web_frame->render_frame_host(), old_host)

### ISSUE THREAD

**Issue by be-dcodeit** [electron/electron#30807]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0

### Expected Behavior

Electron should not crash

### Actual Behavior

Electron crashes in method `WebContents::RenderFrameHostChanged` on line `CHECK_EQ(web_frame->render_frame_host(), old_host);`

### Additional Information

Crash Details:
![image](https://user-images.githubusercontent.com/4749907/131809004-03584d1f-3de8-425c-8736-d5045d2a9fa4.png)

Stack Trace:
[stacktrace.txt](https://github.com/electron/electron/files/7097139/stacktrace.txt)

The issue seems to happen when frequently opening /closing BrowserWindows, however we haven't been able yet to find a small reproducible example.

**Comment by be-dcodeit** [comment]
Thanks for preparing the fix.
Is there an ETA for an Electron 14 patch version that includes this fix?

**Comment by MarshallOfSound** [comment]
Fixed in #30820
