### ISSUE TITLE
[Bug]: Not showing the login screen

### ISSUE THREAD

**Issue by FlimGithub** [electron/electron#30805]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 

### What arch are you using?

x64

### Last Known Working Electron version

3.1.0

### Expected Behavior

it would show login screen so i can troll my friends

### Actual Behavior

It wont show LOGIN SCREEN

### Additional Information

*

**Comment by soulcyber** [comment]
not showing login screen
