### ISSUE TITLE
[Bug]: Unable to resize undocked dev tools window in Electron 14 (Windows OS)

### ISSUE THREAD

**Issue by rooklift** [electron/electron#30803]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

**14.0.0** (broken around **v14.0.0-beta5**)

### Operating System Version

Windows 10 version 20H2

### What arch are you using?

x64

### Last Known Working Electron version

v14.0.0-beta3

### Expected Behavior

Launch Electron itself. Open the dev tools. After undocking it, it should be resizable.

### Actual Behavior

On Windows it is not resizable.

(Someone tells me that, if it was already undocked, they had to dock it and undock it again to see this effect.)

**Comment by rooklift** [comment]
Checking previous releases, I found that:

* It worked in v14.0.0-beta.3
* It was broken by v14.0.0-beta.5

I wasn't able to check beta4 since it didn't seem to have any assets.

**Comment by codebytere** [comment]
@rooklift yep, bisected it to that earlier today. I believe it's related to some changes around resizabilty.

**Comment by codebytere** [comment]
@rooklift yep, bisected it to that earlier today. I believe it's related to some changes around resizability that came through in a chromium roll and will keep digging.
