### ISSUE TITLE
Electron app showing whitescreen issue in windows 7 32 bit 

### ISSUE THREAD

**Issue by ibalaji777** [electron/electron#30810]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

8.2.5

### What operating system are you using?

Windows

### Operating System Version

windows 7 ultimate 32 bit

### What arch are you using?

ia32

### Last Known Working Electron version

8.2.5

### Expected Behavior

electron works smooth in 64 bit .

### Actual Behavior

Electron app showing white screen issue on windows 7 ultimate 32 bit operating system ,it does not throw any error.

### Additional Information

Tested :32bit production Electron app works in  windows 10 operating system
white screen issue : same app i run into windows ultimate 7 32 bit operating system shows white screen only

**Comment by pushkin-** [comment]
Electron 8 isn't supported anymore.
How many cores does your machine have? I've had issues like this on single core machines.

**Comment by clavin** [comment]
Thank you for reaching out!

Electron 8 has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.

**Comment by ibalaji777** [comment]
> Thank you for reaching out!
> 
> Electron 8 has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.
> 
> If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.
> 
> Thanks in advance! Your help is appreciated.

can you suggest which electron version support 32 bit?

**Comment by miniak** [comment]
@ibalaji777 all Electron versions still support 32-bit Windows
