### ISSUE TITLE
[Bug]: gpu-info-update event emitted multiple times with app.getGPUInfo('complete')

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#30827]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0-beta.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H1

### What arch are you using?

x64

### Expected Behavior

`gpu-info-update` event fires once during application startup.

In an event listener, calling `app.getGPUFeatureStatus()` should return the finalized status.

### Actual Behavior

If `app.getGPUInfo('complete')` is called after app ready, `gpu-info-update` emits multiple times.

Calling `app.getGPUFeatureStatus()` during any of these events doesn't guarantee the state is finalized yet.

### Testcase Gist URL

https://gist.github.com/samuelmaddock/f7b29e8848fe44626b2acf1015d4148f

### Additional Information

I'm reporting this as a bug because I wasn't expecting this behavior. If this behavior is normal, let's update the documentation to reflect that so there are no surprises for others.

My goal was to get the finalized state for `app.getGPUFeatureStatus()` which is difficult to know when `gpu-info-update` emits more than once.

**Comment by codebytere** [comment]
@samuelmaddock how do you think this might be better communicated? `gpu-info-update` would instinctually indicate to me that there was a new emit every time the info was updated 🤔

**Comment by samuelmaddock** [comment]
@codebytere I was thinking it might make sense to mention that `gpu-info-update` will be emitted multiple times after [`app.getGPUInfo('complete')`](https://github.com/electron/electron/blob/main/docs/api/app.md#appgetgpuinfoinfotype) is called.

**Comment by samuelmaddock** [comment]
Maybe we could emit a details object with `gpu-info-update` which includes the state of [`GpuDataManager::IsEssentialGpuInfoAvailable()`](https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/gpu_data_manager.h;l=63-64;drc=52065ae2371187db43d9db56b47bd10fd1305b39).

**Comment by samuelmaddock** [comment]
I'm not particularly concerned about this issue anymore, just going to close for now 🤷
