### ISSUE TITLE
[Bug]: Transparent window with vibrancy has no border

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#30833]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

Broken as soon as 13.0.0-beta.2

### What operating system are you using?

macOS

### Operating System Version

macOS 11.5.1

### What arch are you using?

x64

### Last Known Working Electron version

12.1.0

### Expected Behavior

Window has a border when setup with the following options:
```ts
const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    frame: false,
    transparent: true,
    vibrancy: 'sidebar',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })
```

![image](https://user-images.githubusercontent.com/1656324/132056850-23a8a259-f2f1-4b63-9f0a-3f4a1d0506de.png)

### Actual Behavior

Window has no border.

![image](https://user-images.githubusercontent.com/1656324/132056886-48ee3a30-81b2-4389-8661-a78e4eb4af51.png)

### Testcase Gist URL

https://gist.github.com/1e22e2eb30c846d29ee2c581db03f4e2

**Comment by codebytere** [comment]
@samuelmaddock looks like this is resultant of an SDK bump: https://chromium-review.googlesource.com/c/chromium/src/+/2633748 that was rolled in between `13.0.0-nightly.20210209` and `13.0.0-nightly.20210210` - I don't think there's any recourse here.

**Comment by mitchchn** [comment]
@codebytere I was able to restore the border on transparent windows by setting the background color of the NSWindow to white. (The transparency still works.)

I think this regression is related to the recent background color changes in Chromium but can be fixed on the Electron side with the above workaround.
