### ISSUE TITLE
[Bug]: Reloading the window breaks redux dev tool

### ISSUE THREAD

**Issue by nraskoti** [electron/electron#30839]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

macOS

### Operating System Version

Mac OS Catalina and Mac OS Big Sur

### What arch are you using?

x64

### Expected Behavior

Redux dev tool should work even after reloading the electron window.

### Actual Behavior

`Store not found` on reloading the electron window. But works again on closing and reopening of dev tools.

### Additional Information

Works again on closing and reopening of dev tools.

**Comment by freddiehaddad** [comment]
Can confirm same behavior on Linux (Ubuntu 21.10).  Doesn't seem like a Mac OS specific issue.
