### ISSUE TITLE
[Bug]: When opening the Client, nothing loads

### ISSUE THREAD

**Issue by CaptainBHH** [electron/electron#30842]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

Newest (i think)

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

When I open it I expect for the client to be normal and just show me discord.

### Actual Behavior

It opens up, but nothing loads. Its just a blank screen. [Preview](https://i.gyazo.com/7c58675608bd3d1d146c0b4ab824277e.png)

**Comment by compteccharan** [comment]
same
![image](https://user-images.githubusercontent.com/82565257/132165299-4567f311-7087-4de6-9045-6639e6043638.png)
