### ISSUE TITLE
[Feature Request]: Recent documents api for linux

### ISSUE THREAD

**Issue by razzeee** [electron/electron#30846]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

https://www.electronjs.org/docs/latest/tutorial/recent-documents/ only speaks of windows/macOS and it does indeed seem to be missing on linux desktops.

But not because it's not possible, as electron even has https://www.electronjs.org/docs/latest/tutorial/linux-desktop-actions/ which is using the needed api, as far as I can tell.

The specification can be found here:
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions

### Proposed Solution

Write to the .desktop file whenever the api gets called on linux

### Alternatives Considered

Not sure there's an alternative other then to not do this.

**Comment by razzeee** [comment]
Did some reseach and it turns out .desktop files are the wrong approach, we would need to do this via https://docs.gtk.org/gtk3/class.RecentManager.html

But integration into gnome shell is not done/planned. I will try to talk to the design team.

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
