### ISSUE TITLE
[Bug]: it wont load when I open it

### ISSUE THREAD

**Issue by foato** [electron/electron#30843]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

idk

### Expected Behavior

Hoping it would work

### Actual Behavior

It doesnt load 

### Testcase Gist URL

https://github.com/Flam3rboy/discord-bot-client/releases/tag/3.1.0

**Comment by stackedstacker** [comment]
same with me bruh

**Comment by ammardomaa** [comment]
its is not opening
