### ISSUE TITLE
[Feature Request]: Prevent Power Naps

### ISSUE THREAD

**Issue by oltreseba** [electron/electron#30859]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

In macOS there are two different concepts:
* App Nap -> that is: in some situation macOS put some apps to sleep (use less cpu) and wake them up when the user interacts with them
* System sleep -> that is: when the entire device sleep. (lid close, low battery, device not used for a while, etc).

I want to do the first (App Nap), but not the second. (i.e. I want my sync app to keep sync while the device is active, but not preventing it from sleeping).

It looks like `powerSaveBlocker.start('prevent-app-suspension')` seems to do both even if the name suggests that's just going to prevent the app suspension, and not the entire system suspension (maybe `prevent-app-suspension` is unfortunate naming?).

if `powerSaveBlocker.start('prevent-app-suspension')` is supposed to only prevent App Naps, then this is a bug, because it is actually preventing the system from sleeping.

### Proposed Solution

Add another level to `powerSaveBlocker.start` that will only prevent App Naps without preventing the system from sleeping.

### Alternatives Considered

Maybe using exec to set some commandline flag into the app or build a small native component that disable power naps for the app.

**Comment by nornagon** [comment]
I think a native component might be the best way to go about this. The `powerSaveBlocker` API is a small wrapper around the underlying WakeLock code in Chromium, and unfortunately there are no more fine-grained options provided by that API. See https://github.com/electron/electron/blob/eb955af459b560d633aad0f0e8b018a5aab32071/shell/browser/api/electron_api_power_save_blocker.cc#L29-L32

and https://source.chromium.org/chromium/chromium/src/+/main:services/device/public/mojom/wake_lock.mojom;l=8-26;drc=612d14c8a9ad56b0f873a7c69b43da34d3ef31d8

**Comment by enjikaka** [comment]
The WakeLock API releases the lock when a document is no longer "fully active". That means that the acquired lock will release when minimizing windows, changing tabs etc. 

I believe that using this for powerSaveBlocker is incorrect. Applications playing music in the background or relying on BLE or similar would expect the lock to not release when the app is minimized.

https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API#listening_for_wake_lock_release
https://w3c.github.io/screen-wake-lock/#handling-document-loss-of-full-activity

Demo: https://wake-lock-demo.glitch.me/

**Comment by nornagon** [comment]
@enjikaka the `powerSaveBlocker` API in Electron is independent of any document, so shouldn't have that issue.

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would consider that but in the meantime I'm going to go ahead and close this.
