### ISSUE TITLE
[Bug]: Too slow to load and refuse to access

### ISSUE THREAD

**Issue by JAChiu1633** [electron/electron#30866]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

10

### Expected Behavior

Discord Bot Client refuse to load

### Actual Behavior

White screen and grey screen

### Testcase Gist URL

https://discord.com/developers/applications/884761776737099816/information

### Additional Information

I reload it didn't work

**Comment by codebytere** [comment]
Please report this upstream to Discord.
