### ISSUE TITLE
[Bug]: Don't show security warning for localhost

### ISSUE THREAD

**Issue by shadow-light** [electron/electron#30880]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

19.10

### What arch are you using?

x64

### Expected Behavior

There should not be a security warning about insecure loading of resources via plain HTTP when requested from **localhost**.

### Actual Behavior

```
This renderer process loads resources using insecure
  protocols. This exposes users of this app to unnecessary security risks.
  Consider loading the following resources over HTTPS or FTPS. 
- http://127.0.0.1:8000/@vite/client
- http://127.0.0.1:8000/src/init.ts
- http://127.0.0.1:8000/node_modules/vite/dist/client/env.mjs

[around 100 more lines ommitted]  

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
```

Since Vite loads every component separately, this warning spams the browser console, making it very hard to identify actually relevant warnings.

### Additional Information

This issue was raised in https://github.com/electron/electron/issues/13186 but it was closed without discussion regarding localhost. So just wanted to confirm whether there is actually a known security risk loading from localhost, or whether these should be silenced for localhost?

`ELECTRON_DISABLE_SECURITY_WARNINGS=true` is not a desirable solution as it silences other important security warnings too.

Having these warnings not appear after packaging also doesn't help, as it is during development that reading the console messages is most useful.

**Comment by nornagon** [comment]
We already filter out `localhost`, so filtering out `127.0.0.1` seems like a reasonable addition 👍

**Comment by shadow-light** [comment]
Ok great, so it is just 127.0.0.1 then. Thanks for the quick PR
