### ISSUE TITLE
[Feature Request]: Support  GmSSL

### ISSUE THREAD

**Issue by WeMissing** [electron/electron#30883]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Now Connect Https By SSL，But some website create https server by GMSSL,so can't Connect GMSSL website 

### Proposed Solution

add GmSSL Feature:
https://github.com/guanzhi/GmSSL

### Alternatives Considered

not

**Comment by nornagon** [comment]
Chromium and thus Electron uses BoringSSL. Changing this is beyond the scope of the Electron project.
