### ISSUE TITLE
[Feature Request]: environment variable to enable wayland support and get rid of individual --enable-features=UseOzonePlatform --ozone-platform=wayland flags

### ISSUE THREAD

**Issue by pshirshov** [electron/electron#30897]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently Wayland support in Electron needs to be turned on on per-app basis with `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags. 

This is very inconvenient: we have to repeat this chore for every single Electron app, we need to take care of CLI aliases, etc, etc.

Without these flags Electron apps look blurry and are almost unusable when fractional scaling is on.

### Proposed Solution

Electron should read these options from an environment variable, like `ELECTRON_OPTS`,  this way the user would be able to turn on Wayland support globally. 

### Alternatives Considered

Alternatively Electron may support environment variables like 

`ELECTRON_OZONE_PLATFORM`
`ELECTRON_ENABLE_FEATURES`

**Comment by vchernin** [comment]
For what it's worth this is progressing slowly but surely upstream. [Ozone/X11 is on by default in Chromium](https://twitter.com/maksim_sisov/status/1431272534356471964), so hopefully the work to enable Ozone/Wayland will keep progessing, so it's enabled by default in Electron.

But yes an environment variable would be handy in the meantime.

**Comment by ghost-420** [comment]
With this, a global `flatpak override` to make all Flatpak'd software using Electron default to Wayland would be possible.

**Comment by ghost-420** [comment]
With this, a global `flatpak override` to make all Flatpak'd Electron software use Wayland by default would be possible.

**Comment by B1773rm4n** [comment]
What is the status here?

**Comment by DeedleFake** [comment]
> With this, a global flatpak override to make all Flatpak'd Electron software use Wayland by default would be possible.

And a global override to activate the experimental client-side decorations, too, which is quite useful on GNOME, despite the bugs (#33161).

**Comment by qguv** [comment]
To run under Wayland, most electron applications need special flags to be passed at launch.[^1] This is a big headache for Linux distribution package maintainers and full-time Wayland users. Many apps don't respect `$XDG_CONFIG_HOME/electron-flags.conf`—for these applications, an environment variable may provide a decent, global alternative to manually patching `.desktop` entries and throwing wrapper scripts in `/usr/local/bin` whose sole purpose is to pass `--enable-features=UseOzonePlatform --ozone-platform=wayland`.

[^1]: These applications will run in XWayland if the flags are not passed, which looks awful on high-dpi screens, or when scaling is enabled, or when accessibility tools are used. There are also limitations for things like screen sharing, multiple displays, desktop notifications and alerts, window compositing, etc.

Allowing these to be configured with an environment variable would go a long way toward making it easier to configure electron applications to behave property under Wayland.

Of course, the ideal situation would be for Electron to enable proper Wayland support by default, but as long as users are going to have to manually ask electron apps to run under Wayland, I think it's worth making this a global setting.

For these reasons, it would be very nice to see support for environment-based configuration of OzonePlatform.

**Comment by eddy-geek** [comment]
Related: recently merged #34937 added flag `--ozone-platform-hint=auto` , which at least allows moving back and forth between wayland and X11.

**Comment by pshirshov** [comment]
Still bad and not what we all need.

**Comment by gianni-rosato** [comment]
I'm going to second that this is a huge issue. I use a display with fractional scaling, so Wayland is a necessity & it'd be nice for apps to "just work" instead of jumping through these hoops. X11 is dying, Wayland is gaining market share, something should be done.
