### ISSUE TITLE
Possible to build electron with more codecs?

### ISSUE THREAD

**Issue by redbullzuiper** [electron/electron#30901]
Is it possible to build a custom Electron dist with more codecs? I have tried to set the `proprietary_codecs` to `true`. However, I dont see any codecs being added, just the usual ones.

I want to make it possible to play `.avi` files. Encoding them to `mp4` takes to long as these files can be as large as 30GB!

Any suggestions on how to do that?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Electron Discord](https://discord.com/invite/electron).
