### ISSUE TITLE
[Bug]: Double click on electron.exe with error will close the console and have a running process in the beackground 

### ISSUE THREAD

**Issue by YaminoYuki** [electron/electron#30907]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.4.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 1909

### What arch are you using?

x64

### Expected Behavior

After calling yarn package (electron-forge package ) and getting electron.exe in out/app-name-win32-x64 if the user double clicked on the .exe and error happened (for example we have a missing argument) , the console opened and show the error message without closing immediately so the user will be able to close the console by themself and no background process will be running . currently this is the case if the user runs the .exe from the command line or from a .bat file  

### Actual Behavior

If an error happened: there are required arguments (as an example) a console window appears and disappears immediately  without showing what the error is, moreover if the user tries to delete the .exe, they are not able to, since it is running in the background. This is not the case when running from cmd: the user will be able to see the error :[missing arguments] and they will be able to close the console by themselves.

**Comment by stevenfuhr** [comment]
That probably means an uncaught exception is thrown. You could handle such a case with `process.on('uncaughtException', listener)`, handle the error accordingly and close the process.
Although this shouldn't be used to generally handle all exceptions...

**Comment by YaminoYuki** [comment]
@stevenfuhr  
Thanx for your answer, yes it was an exception in one function, but if this shouldn't be used to generally handle all exceptions , is there a reason for that? and what is the better approach to handle uncaught exceptions  here? I mean if I was able to find out the cause of an exception and handled it, what about other exceptions which I might not know about ..shouldn't be a general method for such cases ?

**Comment by YaminoYuki** [comment]
However, process.on('uncaughtException', listener) didn't work for me
