### ISSUE TITLE
[Bug]: tray icon will eventually disappear when packed in asar archive

### ISSUE THREAD

**Issue by deermichel** [electron/electron#30911]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.1.0 (though same on current master)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 2004

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

On Windows, we load an *.ico image for Tray via:
```js
new Tray(nativeImage.createFromPath('someIcon.ico'))
```

After the `%temp%` folder on Windows got cleared (let's suppose some internal housekeeping), the tray icon remains unchanged.

### Actual Behavior

After clearing `%temp%`, the tray looses its image. A transparent placeholder remains and other tray actions (e.g. opening a context menu) still work.

### Additional Information

This is only the case when loading the icon from an asar archive. The reason is that [`ReadICOFromPath`](https://github.com/electron/electron/blob/8532e1239ec929e31b764ffcd314c8db3e09a19f/shell/common/api/electron_api_native_image.cc#L89) will extract the icon to a [temp file](https://github.com/electron/electron/blob/fb539f15d03859bdc783533b8fced155f6828437/shell/common/asar/archive.cc#L389) using the `Archive::CopyFileOut` method. 

While this is useful in the usual case (temporary extracted files should be deleted at one point), it's not viable for tray icons as the image will disappear when the file gets removed - at least on Windows.

Possible solutions:
- add note to Tray docs (or nativeImage) to exclude tray images when using asar archives (e.g. via `--unpack-dir`)
- or: for the explicit case of tray icons, extract these images to a "persistent" path - however, cleanup needs to be provided in some way

cc @zarubond

**Comment by Nantris** [comment]
This no longer appears to be an issue. Every time the app is started the `.ico` is written to a new temporary path now.
