### ISSUE TITLE
[Bug]: API and Documentation Conflate macOS Vibrancy and Translucency

### ISSUE THREAD

**Issue by elsiehupp** [electron/electron#30910]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

Latest

### What operating system are you using?

macOS

### Operating System Version

macOS 11.5.2

### What arch are you using?

x64

### Expected Behavior

The Electron API and documentation should clearly distinguish between [Translucency and Vibrancy](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/translucency/), two related features of macOS that are, indeed, not the same thing. Translucency is translucency, blending, and translucent blurring, while Vibrancy is the change in coloration of individual interface elements, both to indicate the difference between foreground and background applications and to implement the Big Sur feature "wallpaper tinting". Individual user-interface elements can use either, neither, or both Translucency and Vibrancy.

### Actual Behavior

The Electron API and Documentation seemingly conflate Translucency and Vibrancy. See, for example, [the merge that introduced the feature](https://github.com/electron/electron/pull/7898). Translucency and Vibrancy both seem to be set using the same method, either in [the `BrowserWindow` constructor](https://www.electronjs.org/docs/latest/api/browser-window/#new-browserwindowoptions):

> `vibrancy` String (optional) - Add a type of vibrancy effect to the window, only on macOS. Can be `appearance-based`, `light`, `dark`, `titlebar`, `selection`, `menu`, `popover`, `sidebar`, `medium-light`, `ultra-dark`, `header`, `sheet`, `window`, `hud`, `fullscreen-ui`, `tooltip`, `content`, `under-window`, or `under-page`.

or with [the `win.setVibrancy(type)` method](
https://www.electronjs.org/docs/latest/api/browser-window/#winsetvibrancytype-macos):

> type String | null - Can be `appearance-based`, `light`, `dark`, `titlebar`, `selection`, `menu`, `popover`, `sidebar`, `medium-light`, `ultra-dark`, `header`, `sheet`, `window`, `hud`, `fullscreen-ui`, `tooltip`, `content`, `under-window`, or `under-page`. See the [macOS documentation](https://developer.apple.com/documentation/appkit/nsvisualeffectview?preferredLanguage=objc) for more details.

Note that, per the linked Apple document, `under-window` and `under-page` refer not to Vibrancy but rather to Translucency, via the `blendingMode` property:

> ### Choosing a Translucency Effect for Your View
>
> For visual effect views you create yourself, use the `blendingMode` property to specify how and where you want the translucency applied.
>
> Behind-window blending uses the content behind the window as the background for your visual effect view. Behind-window blending makes your entire window stand out above other windows and apps on the desktop. Sheets and popovers use behind-window blending.
>
> In-window blending uses the window’s content as the background for your visual effect view. Typically, you use in-window blending with scrolling content, so that the scrolled content remains partially visible under other parts of your window chrome. Toolbars always use in-window blending.

It's also unclear from the Electron API and documentation how one applies macOS Translucency to individual elements.

And it's unclear whether macOS `behind-window` translucency depends on the use of a [Transparent Window](https://www.electronjs.org/docs/latest/api/frameless-window/#transparent-window) in Electron. ([Previous implementations](https://github.com/arkenthera/electron-vibrancy) did.)

The Electron API and documentation for Translucency and Vibrancy should more closely match the Apple API and documentation for Translucency and Vibrancy in order to avoid ambiguity and confusion. For example, the Electron application Caprine [uses the word "Vibrancy" to refer to both](https://github.com/sindresorhus/caprine/blob/24aacdc844f8df9ce702989a1efb0f56e752a082/readme.md#vibrancy), a mistake that is quite reasonable given the existing Electron API and documentation. When [one aspect of Electron "Vibrancy" is not working in an application](https://github.com/sindresorhus/caprine/issues/1701) the conflation of Translucency and Vibrancy makes the distinction harder to diagnose and discuss. (Note that I am not reporting the linked Issue as an Electron bug but rather as an illustration of the conflation of the two terms.)

**Comment by BitesPotatoBacks** [comment]
@elsiehupp I agree 100% with this!

**Comment by elsiehupp** [comment]
This issue still appears in the Electron documentation.

**Comment by elsiehupp** [comment]
This issue still appears in the Electron documentation.
