### ISSUE TITLE
[Bug]: Devtool window can't resize

### ISSUE THREAD

**Issue by zh99998** [electron/electron#30917]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10 version 21h1

### What arch are you using?

x64

### Last Known Working Electron version

13.3.0

### Expected Behavior

devtool window can resize by drag window border

### Actual Behavior

devtool can't resize

**Comment by rooklift** [comment]
Presumably the same as #30803
