### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by azhengyongqin** [electron/electron#30926]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 20H2

### What arch are you using?

x64

### Last Known Working Electron version

10

### Expected Behavior

After closing the BrowserWindow, need to close or destroy the embedded BrowserView.

### Actual Behavior

The BrowserView cannot be closed using the following code either
```js
browser.removeBrowserView(view);
browser.setBrowserView(null);
view = null;
browser.close();
```
`browserView` does not provide a `close()`or `destroy()` method
`browserView.webContents` also does not provide a `close()` or `destroy()` method

When I open and close `BrowserWindow` several times, the `electron.exe` process is added infinitely in the system task manager

**Comment by codebytere** [comment]
Duplicate https://github.com/electron/electron/issues/29626
