### ISSUE TITLE
[Bug]: v14.0.0 break unresizable frameless windows

### ISSUE THREAD

**Issue by Fndroid** [electron/electron#30923]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows10 21H1

### What arch are you using?

x64

### Last Known Working Electron version

13.x.x

### Expected Behavior

Before v14.0.0, frameless window can be dragged by setting ` -webkit-app-region: drag;` no matter `resizable` is true or false.

### Actual Behavior

After upgrade to v14.0.0, frameless window could not be dragged unless resizable is true.

### Testcase Gist URL

https://gist.github.com/Fndroid/4d89afd65c4e36b901a627c051558b65

### Additional Information

this does not happen in macOS

**Comment by codebytere** [comment]
See https://github.com/electron/electron/pull/30809
