### ISSUE TITLE
[Bug]: during when it is reading

### ISSUE THREAD

**Issue by jperrim** [electron/electron#30922]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows version 10

### What arch are you using?

x64

### Expected Behavior

It reads every word and the whole number. 

### Actual Behavior

 When reading the book the program has difficulty with numbers. It stops midway through the number and then either jumps the next few words or the whole following sentence. 

### Additional Information

It also does it on my mobile devices as well, my phone and my tablet.

**Comment by jperrim** [comment]
Did you all do anything about this problem? is it something that cannot be fixed and one just has to live with it?

**Comment by codebytere** [comment]
@jperrim it's not at all clear what this has to do with Electron? what is "the book"? what is "the program"? what numbers? what words?
