### ISSUE TITLE
 winPDF.loadURL(pdfPath) can preview the pdf if "pdfPath" is a pdf file, but webContents.print() can only print a blank page. 

### ISSUE THREAD

**Issue by fengxiangge** [electron/electron#30947]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.5.0 or 14.0.0

### What operating system are you using?

Windows

### Operating System Version

window 10

### What arch are you using?

x64

### Expected Behavior

winPDF.loadURL(pdfPath); winPDF.webContents.print({},callback)
can print a correct pdf to local or printer.

### Actual Behavior

let winPDF = new BrowserWindow({
      useContentSize: true,
      resizable: true,
      webPreferences: {
        webSecurity: false,
        nativeWindowOpen: true,
        nodeIntegration: true,
        plugins: true
      },
    })
     pdfPath = 'https://www.jianshu.com/print.pdf'
      winPDF.loadURL(
        pdfPath
       );
       winPDF.webContents.on('did-finish-load', () => {
          winPDF.webContents.print(
            {
              silent: true,
              printBackground: true,
            },
            (success,errortype) => {
              console.log('success',success)
              if (!success) console.log('errorType',errortype)
               winPDF.close()
            }
          )
      })

if param is a pdf ,like this:winPDF.loadURL(pdf) is OK, I can see the pdf in BrowserWindow,
but winPDF.webContents.print() is wrong.It print a blank page.
if  winPDF.loadURL(param),param is a html or web page ,it can print correctly.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by fengxiangge** [comment]
[print.txt](https://github.com/electron/electron/files/7167118/print.txt)
code like this.

**Comment by fengxiangge** [comment]
https://gist.github.com/fengxiangge/3034d283c8cbd27dde6ffc671f32d055

**Comment by ben-yocum** [comment]
Complete minimal repro [here](https://github.com/ben-yocum/electron-28828-repro). 

main.js has all the significant js:

```javascript
const {app, BrowserWindow} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow();

  mainWindow.loadFile('dummy.pdf');

  mainWindow.webContents.on('did-finish-load', () => {
    mainWindow.webContents.print();
  });
}

app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  })
});
```

Usage: 

```bash
# In Windows 10
git clone https://github.com/ben-yocum/electron-28828-repro.git
cd electron-28828-repro
npm install
npm start

# When pdf print dialog opens, choose a printer and attempt to print.
# Job is sent to printer but never printed. My Canon printer stalls. Other printers may print a blank page or throw an error.

# Alternatively, choose to print to Microsoft Print to PDF.
# The resulting document has filesize 0 and cannot be successfully opened by any pdf viewer.
```

**Comment by sengokyu** [comment]
**webContents.printToPDF** are the same. Just a blank page I can get.

Here is a minimal reproduce code.

```js
const { writeFile } = require("fs/promises");
const { app, BrowserWindow } = require("electron");

const OUTPUT_PDF = "out.pdf";

const createWindow = () => {
  const win = new BrowserWindow();

  win.webContents.on("did-finish-load", () => {
    win.webContents
      .printToPDF({
        pageRanges: { from: 3, to: 3 },
      })
      .then(async (buf) => {
        await writeFile(OUTPUT_PDF, buf);
      });
  });

  win.loadFile("test.pdf");
};

app.whenReady().then(() => {
  createWindow();
});
```

I would like to print a pdf file without user interaction.

**Comment by sengokyu** [comment]
I have the repository https://github.com/sengokyu/electron-issue-30947 to reproduce the issue.

### Electron version

20.0.0-nightly

### Operating system version

Ubuntu 21.10

### What arch are you using ?

x64

### Expected Behavior

A pdf file is output. It's content to be https://github.com/sengokyu/electron-issue-30947/blob/main/input.pdf

### Actual Behavior

Blank page pdf file is output.

**Comment by pushkin-** [comment]
The other thing of note is that the callback passed into `print` never gets called.

**Comment by pushkin-** [comment]
@codebytere In my case, that doesn't resolve it. I'm printing the PDF seconds after we loaded the page. Should I create a separate issue, or should they be merged?

**Comment by pushkin-** [comment]
still repros in latest stable (21)

**Comment by bigsergoya** [comment]
Any updates? Still active on 23.1.0. @codebytere I've tried to call print manually, with delay (setTimeout(..) / blur event of window). But no luck. Maybe you can advise me something please?

**Comment by pushkin-** [comment]
@codebytere Can the latest version tags be added to this if it helps with tracking? Thanks. This is causing pain points for my customers.

**Comment by pushkin-** [comment]
bump

**Comment by overrider** [comment]
bump

**Comment by overrider** [comment]
The below code, no matter whether i keep the setTimeout, remove it, or adjust it, will only print a blank page. If i cancel the print dialog, and then click on the Chromium Print Icon to re-open the dialog, it will print correctly. Any clues or workarounds would be helpful!

`setTimeout(() => {

    let printWindow = new BrowserWindow({
        show: true,
        //width: 1366,
        //height: 768,
        //fullscreen: true,
        useContentSize: true,
        webPreferences: {
            nodeIntegration: false, // it's safer to disable nodeIntegration
            //contextIsolation: true, // protect against prototype pollution attacks
            //enableRemoteModule: false, // turn off remote
        }
    });

    printWindow.loadFile("test.pdf");

    printWindow.webContents.on('did-finish-load', () => {

        setTimeout(() => {
            printWindow.webContents.print({ deviceName: "_4BARCODE_4B_3044B", silent: false, copies: 1, pageSize: "A5", landscape: false }, (success, failureReason) => {
                if (!success) {
                    console.log(`Failed to print: ${failureReason}`);
                }
            });
        }, 5000);
    });



}, 2000);`

**Comment by 1339240789** [comment]
bump

**Comment by cndinx** [comment]
28.1.3 
This problem persists. Is there any way to solve it?

**Comment by Jaifroid** [comment]
Bump. There is no Print Preview in `webContents.print()` in Electron 29.3.1. However, I don't get a blank page when I print, I do get the contents, at least if I print to PDF.

**Comment by xxaff** [comment]
bump

**Comment by overrider** [comment]
bump

**Comment by marc-thomas** [comment]
bump.

Similar issue.. If i set `show: true` - I can click print and then it prints properly.

But I cannot print silently - I don't even get a blank page printed - timeout doesn't work.

**Comment by saifudheen9745** [comment]
bump.

Having the same problem here...

**Comment by scottcorgan** [comment]
Bump, same exactly issue. Prints html just fine.

**Comment by heaxo** [comment]
bump.

Having the same problem here...

Is there a solution to this problem?

**Comment by malyanoff** [comment]
bump, stuck with the same issue using Electron 36.2.0

**Comment by RaoufX21** [comment]
bump still same issue
