### ISSUE TITLE
[Bug]: could not retrive file path from clipboard readBuffer

### ISSUE THREAD

**Issue by liuyisnake** [electron/electron#30949]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 1909

### What arch are you using?

x64

### Expected Behavior

want to retrive file path from clipboard, but could not get from readBuffer
```
clipboard.availableFormats();  // return ['text/uri-list']
clipboard.has('FileNameW'); // return true
clipboard.has('FileName'); // return true
clipboard.readBuffer('FileNameW'); // return Uint8Array(0) []
clipboard.readBuffer('FileName'); // return Uint8Array(0) []
clipboard.readBuffer('FileNameW').toString('ucs2').replace(new RegExp(String.fromCharCode(0), 'g'), ''); //return ''
```

### Actual Behavior

retrive file path from clipboard readBuffer

### Additional Information

package.json

```
 "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.60",
    "@electron-forge/maker-deb": "^6.0.0-beta.60",
    "@electron-forge/maker-rpm": "^6.0.0-beta.60",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.60",
    "@electron-forge/maker-zip": "^6.0.0-beta.60",
    "@electron-forge/plugin-webpack": "6.0.0-beta.60",
    "@typescript-eslint/eslint-plugin": "^4.0.1",
    "@typescript-eslint/parser": "^4.0.1",
    "@vercel/webpack-asset-relocator-loader": "1.7.0",
    "copy-webpack-plugin": "^9.0.1",
    "css-loader": "^6.0.0",
    "electron": "^14.0.0",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "^2.20.0",
    "fork-ts-checker-webpack-plugin": "^6.0.1",
    "node-loader": "^2.0.0",
    "style-loader": "^3.0.0",
    "ts-loader": "^9.2.2",
    "typescript": "^4.0.2",
    "url-loader": "^4.1.1"
  },
  "dependencies": {
    "electron-settings": "^4.0.2",
    "electron-squirrel-startup": "^1.0.0",
    "mqtt": "^4.2.8",
    "robotjs": "^0.6.0",
    "webtorrent": "^1.5.5",
    "webtorrent-hybrid": "^5.0.0"
  }
```

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
