### ISSUE TITLE
[Bug]: GLIBC dependency version change

### ISSUE THREAD

**Issue by umerkk** [electron/electron#30956]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.3

### What operating system are you using?

Other Linux

### Operating System Version

CentOS 7

### What arch are you using?

x64

### Last Known Working Electron version

11.4

### Expected Behavior

We recently upgraded to Electron 13 and CentOS 7 is among our supported Linux versions. It looks like the  Electron 11 was using the correct & standard GLIBC & GLIBCXX versions that CentOS support out of the box.
But after the upgrade of Electron 13 it seems like it is (or a dependency) is using a newer version of GLIBC & GLIBCXX that is not compatible with CentOS out of the box and require users to update their GCC & Glibc (which isn't ideal).

I would like to ask, is there a specific change that resulted in this usage of newer versions, or is it a side effect?

The normal error we get in Terminal logs is "GliBCXX is not found" when we run the app built using a newer electron-builder' version.

We use prebuilt Electron binaries from the GitHub release page (using Electron-Builder).
Any help here would be appreciated/

### Actual Behavior

Should run with standard glibc library.

**Comment by vladimiry** [comment]
Are you sure you get еру "GliBCXX is not found"-like error from @electron but not from some native modules/dependencies?
Did you try to drop prebuilds use and compile the native modules at your side?

**Comment by umerkk** [comment]
Yeah it actually came from keytar.
