### ISSUE TITLE
[Feature Request]: Request screen sharing permission

### ISSUE THREAD

**Issue by gilles-yvetot** [electron/electron#30967]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am not sure but I think we use to be able to ask for the screen sharing permission on macos. I don't see it anywhere in the docs? Would that something we could have? Did we have it before and it is not supported anymore?

### Proposed Solution

Request screen sharing permission the same way we ask for Microphone or Camera permission

### Alternatives Considered

No idea

**Comment by codebytere** [comment]
@gilles-yvetot it's not implemented in a clean way in Chromium right now (there's no direct API exposed to do so) and has a lot of edge cases we'd prefer not to add to core. Until that's the case we would prefer not to add this, but I wrote a native Node.js module a bit back that should solve your need: https://github.com/codebytere/node-mac-permissions.

**Comment by gilles-yvetot** [comment]
@codebytere understood. Thanks a lot. I'll start using your lib :)

**Comment by gilles-yvetot** [comment]
@codebytere I have a question and could not find an answer anywhere. I  figured you might be the one person who knows the answer. My electron app starts chrome at some points. And it looks like I need permissions for my electron app for chrome to inherit them.
Is there a way to start a process on its own without having to get the parent process permissions?
