### ISSUE TITLE
Do we want to add a link here for GOMA access or an explainer of what GOMA is? Sorry, I just see the empty parens and wanted to make sure

### ISSUE THREAD

**Issue by soffieprincess07** [electron/electron#30968]
Do we want to add a link here for GOMA access or an explainer of what GOMA is? Sorry, I just see the empty parens and wanted to make sure

_Originally posted by @VerteDinde in https://github.com/electron/electron/pull/30528#r689721001_

**Comment by soffieprincess07** [comment]
> Do we want to add a link here for GOMA access or an explainer of what GOMA is? Sorry, I just see the empty parens and wanted to make sure
> 
> _Originally posted by @VerteDinde in [#30528 (comment)](https://github.com/electron/electron/pull/30528#r689721001)_

**Comment by VerteDinde** [comment]
Closing this - if you'd like to file an issue, could you please fill out our issue tracker? 🙂  Thanks!
