### ISSUE TITLE
[Bug]: maximize behavior exception in case of aspectRatio setting

### ISSUE THREAD

**Issue by BlackHole1** [electron/electron#30979]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.0.0 ~ latest (All versions)

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.5.2

### What arch are you using?

x64

### Expected Behavior

After setting the aspectRatio, maximize and unmaximize events can be listened to normally.

```ts
mainWindow.setAspectRatio(16 / 11);
mainWindow.setFullScreenable(false);

mainWindow.on("maximize", () => {
    // ....
});

mainWindow.on("unmaximize", () => {
    // ...
});
```

1. Click maximize button in Window
2. trigger `maximize` event
2. move Window or use `mainWindow.center()` function
3. Click maximize button in Window
4. trigger `unmaximize` event

### Actual Behavior

After setting the aspectRatio and maximizing, unmaximize will never be triggered after dragging the window.

```ts
mainWindow.setAspectRatio(16 / 11);
mainWindow.setFullScreenable(false);

mainWindow.on("maximize", () => {
    // ....
});

mainWindow.on("unmaximize", () => {
    // ...
});
```

1. Click maximize button in Window
2. trigger `maximize` event
3. move Window or use `mainWindow.center()` function
4. Click maximize button in Window
5. trigger `maximize` event (No matter how many times the maximize button is clicked, unmaximize will never be triggered)

https://user-images.githubusercontent.com/8198408/133363284-1287082a-d5d3-4555-bedf-6a0fde4e46fe.mp4

### Testcase Gist URL

https://gist.github.com/BlackHole1/b67e544cfbb397f6bd53ea8ab7008b8c

**Comment by BlackHole1** [comment]
I analyzed the source code and there are three areas found to be causing this problem

> The first and second are the root causes

1. It forgets to determine if `AspectRatio` is currently set. and NSWindow's isZoomed method, also did not go to determine `AspectRatio`: https://github.com/electron/electron/blob/664a452fb68cce4addfa7bf06a27bbceb1035edb/shell/browser/native_window_mac.mm#L611-L622

2. There is also a problem with the calculation logic when resizable is equal to false, Because here too the `AspectRatio` is not taken into account: https://github.com/electron/electron/blob/664a452fb68cce4addfa7bf06a27bbceb1035edb/shell/browser/native_window_mac.mm#L615-L621

3. Never trigger the `windowWillResize` method. This behavior explains why the maximize button does not respond when clicked multiple times. When the maximize button is clicked again after maximizing, only the `windowWillUseStandardFrame` and `windowShouldZoom` methods are triggered, and then no other methods are called. I suspect the problem is: https://github.com/electron/electron/blob/664a452fb68cce4addfa7bf06a27bbceb1035edb/shell/browser/ui/cocoa/electron_ns_window_delegate.mm#L62-L93

I'm trying to fix it, but have no idea where to start, as I'm completely unfamiliar with Objective-C and mac development. If you can provide me with an idea, I can try to fix it.

I looked at the git blame and found that you guys are supposed to be the main maintainers of this feature, so I'm cc'ing here:

@30607 @samuelmaddock @codebytere

**Comment by codebytere** [comment]
@BlackHole1 i'm working on this as we speak!

**Comment by BlackHole1** [comment]
> @BlackHole1 i'm working on this as we speak!

This is great! I'm just in time to learn how I should go about fixing this problem.
