### ISSUE TITLE
Loading non-context-aware native module in renderer

### ISSUE THREAD

**Issue by pratikom18** [electron/electron#30982]
Uncaught Error: Loading non-context-aware native module in renderer: '\\?\G:\Random-User-Generate\electron-serialport\node_modules\@serialport\bindings\build\Release\bindings.node', but app.allowRendererProcessReuse is true

**Comment by Prinzhorn** [comment]
https://github.com/electron/electron/issues/18397

**Comment by codebytere** [comment]
See https://github.com/electron/electron/issues/18397

**Comment by gigmelepcha** [comment]
Do we have a solution for this ?
