### ISSUE TITLE
[Bug]: enumerateDevices lost some virtual cameras at production build

### ISSUE THREAD

**Issue by mlnchk** [electron/electron#30986]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS BigSur 11.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

```navigator.mediaDevices.enumerateDevices()```

should return all devices, including virtual cameras, as Chrome does

### Actual Behavior

Device list is incomplete and does not include virtual cameras.

### Additional Information

I can't reproduce this behavior at local and dev builds, but this bug exists on production build. In my case "Krisp Virtual camera" is lost, but it reproduces with other virtual devices at other machines.

I use `file://` and camera permissions are granted.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by nornagon** [comment]
You might also try on newer versions of Electron.

**Comment by hengshanMWC** [comment]
Has it been solved?
