### ISSUE TITLE
[Bug]: Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by Thomasfds** [electron/electron#30983]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 21H1

### What arch are you using?

x64

### Last Known Working Electron version

13.1.8

### Expected Behavior

I updated Electrons to have the latest fixes and thought all of them are working fine.

Now none of the Electron related commands are working.

### Actual Behavior

I just updated electron from version `^ 13.1.8"` to `"^14.0.1"` and since then I can't run any Electron-related commands.

I get the following error:

```
node:internal/child_process:412
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at Object.<anonymous> (E:\Developpement\Electrons\nightmareLauncher\node_modules\electron\cli.js:7:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}
```

Do you have any idea where it might come from? I have node `v16.9.1`

**Comment by BlackHole1** [comment]
This is not an electron bug, it should be a problem with your local cache.

see:
    * https://github.com/nodejs/node/issues/19965#issuecomment-380750573
    * https://stackoverflow.com/a/62044109/6596777
    * https://npm.community/t/issue-npm-errno-4094/2284

**Comment by SESA475978** [comment]
I am seeing below error while executing power platform actions from git.
It happens for all actions, even tried with different git account and on different Powerapps environment.

  Error: failed: spawn UNKNOWN
  Error: failed: spawn UNKNOWN
  Error: failed: Error: spawn UNKNOWN
  Error: failed: Error: spawn UNKNOWN

Any suggestions ?

**Comment by RamkumarNG** [comment]
how to solve the issue??

**Comment by BlackHole1** [comment]
@SESA475978 @RamkumarNG Can you provide a reproduction gist?

**Comment by Beboz1** [comment]
I have this problem too with electron then tried nwjs and got the same error can anybody help
