### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Rajat1657** [electron/electron#30997]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.0 Latest

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 10 Home Single Language Version	21H1 Installed on	‎27-‎07-‎2020 OS build	19043.1202 Experience	Windows Feature Experience Pack 120.2212.3920.0

### What arch are you using?

x64

### Last Known Working Electron version

3.1.0

### Expected Behavior

There should be a login screen

### Actual Behavior

black screen
![Screenshot (2438)](https://user-images.githubusercontent.com/83265028/133557447-fd9bc8ab-054f-4a9d-8e5f-7607710a6f18.png)

**Comment by trungpro200** [comment]
same as here
look like the server got something wrong :/
