### ISSUE TITLE
[Bug]: my macOS language is chinese, but electron 9.4.x navigator.language return "en-US", electron 9.3.2 return "zh-CN" is right

### ISSUE THREAD

**Issue by En777** [electron/electron#30998]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.4.2

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4

### What arch are you using?

x64

### Expected Behavior

navigator.language return "zh-CN" is right.

### Actual Behavior

navigator.language return "en-US"

**Comment by nornagon** [comment]
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).
