### ISSUE TITLE
[Bug]: Error: Must specify either 'file' or 'files' option

### ISSUE THREAD

**Issue by codingedgar** [electron/electron#30992]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur

### What arch are you using?

x64

### Expected Behavior

types to work

```typescript
type Item = ({
    /**
     * The path to the file being dragged.
     */
    file: (string[]) | (string);
  } |  {
    /**
     * The paths to the files being dragged.
     */
    file: (string[]) | (string);
  }) & {
    /**
     * The image must be non-empty on macOS.
     */
    icon: (NativeImage) | (string);
  }

startDrag(item: Item): void;
```

```typescript
event.sender.startDrag({
  file: filePath,
  icon: icon
});
```
```typescript 
event.sender.startDrag({
  files: filePaths,
  icon: icon
});
```

### Actual Behavior

```
A JavaScript error occurred in the browser process

Error: Must specify either 'file' or 'files' option
at IpcMainImpl.<anonymous> (/Users/edgarrodriguez/Documents/projects/control-electron/src/main.dev.ts:403:20)
at IpcMainImpl.emit (events.js:315:20)
at IpcMainImpl.EventEmitter.emit (domain.js:483:12)
at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
at Object.emit (events.js:315:20)
at Object.EventEmitter.emit (domain.js:483:12)
```

![image](https://user-images.githubusercontent.com/10213241/133517800-b3e6f209-fe91-42e4-9bb4-f4067853bc40.png)

### Additional Information

https://github.com/electron/electron/blob/00d0265782f3bb52c7d623f70bd99480bcd96262/shell/browser/api/electron_api_web_contents.cc#L2877

https://github.com/electron/electron/blob/4d89174b4187067a1f91f44f48c4234720fd24fa/docs/api/web-contents.md#contentsstartdragitem

**Comment by codingedgar** [comment]
My workaround so far is to use declaration merging:

```ts
// declarations.d.ts
declare module 'electron' {
  interface Item {
    file?: string[];
    files: string[];
  }
}
```

**Comment by BlackHole1** [comment]
Can you attach an example of gist? From the code, it looks like it should be caused by your incoming value not existing:

https://github.com/electron/electron/blob/00d0265782f3bb52c7d623f70bd99480bcd96262/shell/browser/api/electron_api_web_contents.cc#L2854-L2856

**Comment by codingedgar** [comment]
> Can you attach an example of gist? From the code, it looks like it should be caused by your incoming value not existing:
> 
> 
> 
> https://github.com/electron/electron/blob/00d0265782f3bb52c7d623f70bd99480bcd96262/shell/browser/api/electron_api_web_contents.cc#L2854-L2856

It is a typescript error, the type of Item does not have a property called "files" just "file" but "files" is required if i pass an array.

**Comment by BlackHole1** [comment]
Can you provide a gist demo? I'd be happy to fix this
