### ISSUE TITLE
Embedding Meteor

### ISSUE THREAD

**Issue by wizonesolutions** [electron/electron#310]
Do you have any tips as to how I would go about running Meteor inside Atom Shell? https://meteor.com. Would I have to build the app in Meteor itself, bundle it, and then expand the bundle inside the Atom Shell app or something?

**Comment by martineboh** [comment]
Love to see how this goes.

**Comment by paulcbetts** [comment]
This might be better for https://discuss.atom.io/c/atom-shell

**Comment by martineboh** [comment]
@paulcbetts Thanks

**Comment by SeriousM** [comment]
@paulcbetts Thanks

**Comment by sircharleswatson** [comment]
@wizonesolutions & everyone else. I've created a boilerplate for Electron + Meteor. You can read about it here: https://sircharleswatson.github.io/2015/04/30/Electrometeor-Build-Desktop-Applications-With-Electron-Meteor.html

And you can check it out on GitHub here: https://github.com/sircharleswatson/Electrometeor
