### ISSUE TITLE
[Bug]: context property missing on WebFrame instance

### ISSUE THREAD

**Issue by Treverix** [electron/electron#31009]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

13.3.0

### Expected Behavior

I expect to access and modify a html frame context (window object) from the preload when contextIsolation is set to false for the browser windows like it worked with version 13.3.0.

```js
    // Create the main browser window.
    this.mainWindow = new BrowserWindow({
      width: 1800,
      height: 900,
      minWidth: 1100,
      minHeight: 800,
      frame: false,
      webPreferences: {
        nodeIntegration: true,
        contextIsolation: false,
        preload: path.join(__dirname, 'MyPreload.js'),
        webSecurity: false,  // required for handling local filesystem resources in chromium
      }
    });

```

### Actual Behavior

It fails after upgrading electron from 13.3.0 to 14.0.1. The following code now crashes because `frameWindow` is now undefined. The `context` property is not there anymore. 

```ts
  static addContextMenuHandler(event: IpcRendererEvent, args: any) {

    // @ts-ignore
    const frameWindow:Window = webFrame.findFrameByRoutingId(args.frameRoutingId).context;

    frameWindow.addEventListener('contextmenu', async (e) => {
      e.preventDefault();

     // ...
   }
```

### Additional Information

Knowing that `context` was not documented (anymore?), this was the only way I know of to access an html frame context so that I can, like here, add a context menu listener (and solve other problems). Why HTML frames? It's a tool that we use for maintaining an old web application that (partially) still uses frames.

**Comment by MarshallOfSound** [comment]
`context` was an implementation details and a security flaw, using it broke expectations around context isolation and that entire `webFrame` module was refactored to correctly maintain isolated worlds.

It was never documented and therefore will not be added back
