### ISSUE TITLE
[Feature Request]:  Could electron automatically generate code for contextBridge and Ipc when using nodeIntegration = true?

### ISSUE THREAD

**Issue by delebash** [electron/electron#31002]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently setting nodeIntegration = true lets your node modules just work.  It is simple and I think it should stay this simple.  However, it is my understanding that nodeIntegration = true is very insecure unless you are only running local code.  The current method of using contextBridge and setting up Ipc is really a pain.  Would it be possible to have electron handle/generate internally the code necessary for contextBridge  and Ipc?  In this manner nnodeIntegration = true would still be simple and just work and be secure.

### Proposed Solution

Automatically handle behind the scenes all necessary contextBridge  and Ipc render functions so that we can continue to use nnodeIntegration = true.  In this way it still keeps it simple to use your node modules but also fixes the security risk of the current nnodeIntegration = true  method.

### Alternatives Considered

I do not have any alternative suggestions.

**Comment by MarshallOfSound** [comment]
This is not as simple as it might seem.  First, putting things over IPC automatically means "should be async" and not all code / node_modules are written to be async.

Also just putting things over IPC / contextBridge does not inherently make it "secure".  If you expose an IPC message that let's you run `child_process.spawn`, you may as well have not enabled context isolation / sandboxing at all.

The IPC bridges you expose should be carefully thought out and as minimal as possible, accepting limited to no user input and sanitizing / validating the arguments along the way.

**Comment by delebash** [comment]
Thank you for the explanation.  Would it be possible for you to make a wrapper around a function that does all of the contextBridge Ipc stuff.   This we can be selective on what we expose but is still makes it easier for developers.

So if I want to require fs.  I could do something like fs= electroncontextBridge(require(fs)).  You could even limit that down to specific methods.  So if I want to expose all of fs we can use a wildcard like * otherwise we can specify each method that we want to use.  So if we want to use fs.copy or fs.create we can wrap those in the elctroncontextBridge and then pass in an array of fs methods to allow and everything else is excluded.  In this way someone cannot call fs.delete since we did not expose that.  I think a solution like this would really make easy.  One of my reasons for using electron is that it was easy to use node modules for the web.  Now it is not so easy.

**Comment by MarshallOfSound** [comment]
You missed the primary point, exposing ANY fs API over the bridge would he unsafe as it gives unrestricted access to all files on your disk.  Your exposed API surface needs to be beyond minimal

**Comment by delebash** [comment]
So what you are saying is that we should no longer be able to have a Delete button on ta render page and have it delete the file using fs.delete?

**Comment by miniak** [comment]
@delebash if you are only running local code, you can just disable context isolation. If you are running remote content, then you need to carefully design the APIs exposed using the context bridge.
