### ISSUE TITLE
[Bug]: ContextIsolation changes page behavior and breaks protonmail login

### ISSUE THREAD

**Issue by Jelmerro** [electron/electron#31018]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

any 15.x.y-beta, including beta.7

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 34

### What arch are you using?

x64

### Last Known Working Electron version

14.0.1

### Expected Behavior

Logins of Protonmail inside webviews should work and decrypt messages after login or show a message that the password was incorrect, regardless of the webpreferences of the webview.

### Actual Behavior

On Electron 14 it works as expected, you can login and it all works. The same is true for Electron 15, but ONLY if you have enabled contextIsolation. I can't do that for my project as I need to overwrite existing window properties, and since the contextBridge doesn't allow this I have contextIsolation disabled. This isn't a big issue, as I only run a specific set of preloads inside the webview, but for some odd reason the protonmail login gives this vague error of "invalid character", that I can ONLY reproduce with contextIsolation disabled using the 15 betas. It does not happen in Chromium, it does not happen when enabling contextIsolation and it did not happen in Electron 14 and earlier, where you could just sign in.

### Testcase Gist URL

https://gist.github.com/Jelmerro/65c3cabe4ac91461f382f6b15361b7b5

**Comment by Jelmerro** [comment]
@sofianguy also happens in all stable versions of 15 and 16. Are there any details the team needs to start work on this? It seems like a fairly serious bug that changing the contextIsolation flag alone would interfere with the browser experience...

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Jelmerro** [comment]
There is already a fiddle in the top comment, it's this one:
https://gist.github.com/Jelmerro/65c3cabe4ac91461f382f6b15361b7b5
Just trying to login with any credentials will give an "invalid character" error, which ONLY happens with contextIsolation disabled.

**Comment by nornagon** [comment]
@Jelmerro the fiddle includes ProtonMail, which is too large of a dependency for us to analyze in a reasonable amount of time. Please provide a reduced test-case which isolates the problem.

**Comment by Jelmerro** [comment]
You are right, I apologize for making it seem as if it could have been caused by Protonmail, it's not. It's because somehow disabling contextIsolation changed the window function atob to a JS node implemented version instead of a native one.
![image](https://user-images.githubusercontent.com/1696674/149214205-ee22ab38-ee2e-4af4-a21d-6acffa3d8e4f.png)
The error you see is thrown here, in the node atob implementation, which is not used if contextIsolation is enabled:
![image](https://user-images.githubusercontent.com/1696674/149214813-e4494f4d-85a9-43a6-abb8-7f7aba57f3c2.png)
It can apparently be reproduced by calling atob with whitespace characters, but the real question is why a different atob implementation is used when contextIsolation is toggled. At least for now I can override atob myself to fix this, but I think a more ideal solution is that Electron would always use the native atob instead of the node version, even if contextIsolation is disabled. What are your thoughts @nornagon?

**Comment by Jelmerro** [comment]
@nornagon Sorry for tagging you, but so far you are the only to respond. Just want to report that this is still an issue even in the latest electron versions. The exact issue is that the atob and btoa functions are not the same when contextIsolation is enabled/disabled, which breaks certain websites by spitting out the "invalid character" error, which is not in line with spec. Please let me know if you still need additional info from me or if I can help any other way to get this fixed, as currently it's completely impossible to login to protonmail with any Electron-based app that cannot use contextIsolation.

**Comment by codebytere** [comment]
@Jelmerro could you include an Fiddle please as requested above, which demonstrates an incorrect return value from the Node.js implementation?

**Comment by codebytere** [comment]
@Jelmerro could you please include a Fiddle as requested above where the Node.js implementation errors and the Chromium version does not?

**Comment by Jelmerro** [comment]
I just finished this, but I'm not sure if this really demonstrates the issue. The issue is that btoa and specifically atob do not accept everything that real browsers accept, so they error out on pages that make use of that (including proton, but that's just one example, it also breaks soundcloud). https://gist.github.com/7e6422665528b0f88b8b83c9dc93f35f

**Comment by daief** [comment]
Node.js implementation errors when the input contains `\n` or `\r`, but native atob of browser is ok.

```js
// Node.js implementation
atob('\n\r');

// Uncaught InvalidCharacterError: Invalid character
//    at __node_internal_ (node:internal/util:493:10)
//    at atob (node:buffer:1247:13)
```

Browser is ok.

```js
atob('\n\r'); // ''
```
