### ISSUE TITLE
[Bug]: Window Controls Overlay has bottom border when `disableHardwareAcceleration`

### ISSUE THREAD

**Issue by cawa-93** [electron/electron#31025]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

- 14.0.1
- 15.0.0
- 16.0.0-nightly.20210921
- 18.0.0-nightly.20220118

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21H1 Build 19043.1165

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

Expected controls without border
![зображення](https://user-images.githubusercontent.com/1662812/134018264-9976c73d-3226-4939-9abc-ac2f1cad37d8.png)

### Actual Behavior

Controls has black bottom border 
![зображення](https://user-images.githubusercontent.com/1662812/134018077-0ca35fa0-0df5-4de1-aba9-3c4156f41ecf.png)

### Testcase Gist URL

https://gist.github.com/2b4c2171fc64899bb394d0e83896f853

### Additional Information

Only if `app.disableHardwareAcceleration()` was called

**Comment by cawa-93** [comment]
Relevant for v15.0.0

**Comment by wenhui-pds** [comment]
When the computer zooms to 125%,Controls has black bottom border。

**Comment by cawa-93** [comment]
Still relevant for 18.0.0-nightly.20220118

**Comment by hrj303662813** [comment]
When will this bug be fixed？
Please~~~

**Comment by hrj303662813** [comment]
when the windows is not the maximum size status,Controls has black bottom border.

**Comment by cawa-93** [comment]
It seems was fixed in 17.1
