### ISSUE TITLE
process.env APPDATA undefined

### ISSUE THREAD

**Issue by HC1988** [electron/electron#31059]
My application is running with electron version 3.1.13. When I use process.env to get APPDATA, it is undefined. My operating system is Windows 7 32-bit. My application is set to start automatically when the PC starts. Why does this happen and how to fix it .
@MarshallOfSound

**Comment by BlackHole1** [comment]
Please use `app.getPath("appData")`, see: https://github.com/electron/electron/blob/v3.1.13/docs/api/app.md#appgetpathname

### Additional Notes:

1. Please follow the issues specification. see: https://github.com/electron/electron/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml
2. 3.1.13 is no longer in the maintenance list, please use the newer version

**Comment by MarshallOfSound** [comment]
Closing out as per above, please use a supported version of electron
