### ISSUE TITLE
[Bug]: Calling removeBrowserView() in any way disables dragging using other BrowserViews on macOS

### ISSUE THREAD

**Issue by devinbinnie** [electron/electron#31068]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6

### What arch are you using?

x64

### Last Known Working Electron version

Unsure

### Expected Behavior

BrowserViews containing draggable areas should continue to function normally regardless of other BrowserViews being removed using `removeBrowserView`

### Actual Behavior

BrowserViews containing draggable areas cease to function on macOS once `removeBrowserView` is called.

### Additional Information

Calling `setBounds` on any view seems to restore the functionality.

Reproduction using `electron-quick-start` here: https://github.com/devinbinnie/electron-quick-start/tree/remove_browser_view_issue

**Comment by codebytere** [comment]
@devinbinnie in the future where possible could you please provide reproducible samples as Electron Fiddles? it's much easier for us - that's what the "Testcase Gist URL" is for.

**Comment by devinbinnie** [comment]
> @devinbinnie in the future where possible could you please provide reproducible samples as Electron Fiddles? it's much easier for us - that's what the "Testcase Gist URL" is for :)
> 
> Gist Version: https://gist.github.com/0a53108546ef22e4d03e1b6dea55a79a

Absolutely, apologies for the inconvenience. Thanks so much for the quick fix :)
