### ISSUE TITLE
[Bug]: not starting

### ISSUE THREAD

**Issue by YchampionOP** [electron/electron#31061]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

should show to login

### Actual Behavior

blank screen

### Testcase Gist URL

??

### Additional Information

none

**Comment by miniak** [comment]
what is not starting? if you have an issue with a particular app, please report it there. If you have an actual issue with Electron itself, please file a proper bug report with repro steps.
