### ISSUE TITLE
[Bug]: fs.state callback can't use isFile() or isDirectory() check file type

### ISSUE THREAD

**Issue by yuuki80code** [electron/electron#31060]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0-beta.3

### What operating system are you using?

Windows

### Operating System Version

windows 10 19042.1052

### What arch are you using?

x64

### Expected Behavior

fs.stat()  callback isFile return file is file or directory

### Actual Behavior

fs.stat()  callback isFile not work,not a function

**Comment by VerteDinde** [comment]
Thanks for reporting this! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a follow up comment.

Thanks in advance!

**Comment by miniak** [comment]
@yuuki80code can you please add a proper title to the issue?

**Comment by yuuki80code** [comment]
> Thanks for reporting this! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a follow up comment.
> 
> Thanks in advance!

https://gist.github.com/b7c4516ba24a210a893dc6c268d0e63d   this is test code

**Comment by BlackHole1** [comment]
After testing, we can confirm that this is an electron bug.

see:

<img width="530" alt="图片" src="https://user-images.githubusercontent.com/8198408/134448888-44f27061-429f-4091-a608-c2f93b768cba.png">

<img width="538" alt="图片" src="https://user-images.githubusercontent.com/8198408/134448908-b924dce2-62fb-4193-94dd-34b505d3808b.png">

The problem should be in the exposeInMainWorld method, electron does not assign back the prototype chain of the method

**Comment by yuuki80code** [comment]
> After testing, we can confirm that this is an electron bug.
> 
> see:
> 
> <img alt="图片" width="530" src="https://user-images.githubusercontent.com/8198408/134448888-44f27061-429f-4091-a608-c2f93b768cba.png">
> 
> <img alt="图片" width="538" src="https://user-images.githubusercontent.com/8198408/134448908-b924dce2-62fb-4193-94dd-34b505d3808b.png">
> 
> The problem should be in the exposeInMainWorld method, electron does not assign back the prototype chain of the method
> 
> ### Update
> I checked the documentation and found that this is the expected behavior of electron, see: https://github.com/electron/electron/blob/bb6dc99d9d23de34e002ee86f8692ad148793528/docs/api/context-bridge.md#parameter--error--return-type-support
> 
> <img alt="图片" width="1040" src="https://user-images.githubusercontent.com/8198408/134449440-7cb4dee9-7466-414a-90ac-28e710f99664.png">

How should I modify it?

**Comment by BlackHole1** [comment]
Related discussions:

* https://github.com/electron/electron/issues/23506#issuecomment-780176437
* https://github.com/electron/electron/issues/29055#issuecomment-834218519

## There are two solutions to your problem:

### 1

```javascript
// preload.js
contextBridge.exposeInMainWorld('isFile', (path, cb) => {
    fs.stat(path, (err, data) => {
        if (err) {
            return cb(err);
        }

        cb(undefined, data.isFile())
    });
});

// renderer
isFile (f.path, (err, result)=> {
    if (err) {
        console.log(err)
    } else {
        console.log(result)
    }
});
```

### 2

use IPC

**Comment by yuuki80code** [comment]
it can resolve my problem,thanks

**Comment by 6250** [comment]
чт, 23 сент. 2021 г., 14:01 yuuki ***@***.***>:
