### ISSUE TITLE
Mac arm64 build fails with 404 error

### ISSUE THREAD

**Issue by xvaultwallet** [electron/electron#31074]
Trying to build for arm64 fails with the following error:
 cannot resolve https://github.com/electron/electron/releases/download/v1.6.2/electron-v1.6.2-darwin-arm64.zip: status code 404

**Comment by miniak** [comment]
arm64 support was added in Electron 11.

**Comment by 6250** [comment]
чт, 23 сент. 2021 г., 09:17 xVault.dev ***@***.***>:
