### ISSUE TITLE
[Bug]: process.versions.modules returns incorrect value "98" in Electron 15.0.0

### ISSUE THREAD

**Issue by marcelblum** [electron/electron#31076]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version 21H1 build 19043.1237

### What arch are you using?

x64

### Last Known Working Electron version

14

### Expected Behavior

Expected 89 as per https://github.com/electron/node-abi/blob/master/abi_registry.json, or at most a number <= 93 which is the latest Node abi

### Actual Behavior

returns 98

### Additional Information

To repro simply `console.log(process.versions.modules)`

**Comment by BlackHole1** [comment]
This is as expected, see:

https://github.com/electron/electron/blob/c3e6746fa940e68d0fbee14d08262854e47b1577/build/args/all.gn#L5

https://github.com/nodejs/node/blob/c7da13c7c408f76fd7511365ec0de88135ee066e/doc/abi_version_registry.json#L4

**Comment by MarshallOfSound** [comment]
`node-abi` is slightly out of date due to an automation issue, should be fixed shortly 👍
