### ISSUE TITLE
[Bug]: Multi-Screen Window Placement API not working

### ISSUE THREAD

**Issue by jjeff** [electron/electron#31103]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

macOS

### Operating System Version

Big Sur

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

With experimental features enabled, Electron (via Chrome 93+) should be able to use the new Multi-Screen Window Placement API to place windows onto various screens.

### Actual Behavior

While most of the API appears to work (e.g. `window.getScreens()`), any calls to `requestFullscreen({screen: someScreen})` will only fullscreen the window on its current screen.

### Testcase Gist URL

https://gist.github.com/jjeff/078e07a2e6efd589365717e81094bbd6

### Additional Information

[Multi-screen Window Placement API](https://www.chromestatus.com/feature/5252960583942144) is currently in prerelease, but it will ship with Chrome 97.

More in the gist comment:
https://gist.github.com/jjeff/078e07a2e6efd589365717e81094bbd6#gistcomment-3891934

Some thoughts from Michael Wasserman:
https://github.com/michaelwasserman/window-placement-demo/issues/2

**Comment by jjeff** [comment]
Marginally related: https://github.com/electron/electron/issues/30249

**Comment by oott123** [comment]
Can we reopen it?
