### ISSUE TITLE
[Bug]: BrowserView not always painting content after upgrading from 13.4.0 to 14.0.0

### ISSUE THREAD

**Issue by eFail** [electron/electron#31109]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 20H2

### What arch are you using?

x64

### Last Known Working Electron version

13.4.0

### Expected Behavior

I created the simplest "Hello world" app possible to demonstrate this regression in Electron (see attached Gist --switch it back and forth between Electron v14.0.0 and v13.4.0 to test).

The main BrowserWindow has a single button.  When clicked, it opens another BrowserWindow that displays content in a BrowserView.  You can keep clicking the main window button over and over again to open secondary BrowserWindows.

The expected behaviour is that whenever a secondary window is opened, its content renders.

### Actual Behavior

On Electron v13.4.0, the secondary window instances ALWAYS render their content.

On Electron v14.0.0, something regressed.  Most of the time, secondary windows open blank.  Only occasionally do they succeed in rendering their content.

I looked at the change log for Electron 14, and the commit that looks most likely to have caused this regression is #29919. @codebytere 

### Testcase Gist URL

https://gist.github.com/eFail/463f35452c3f25a9d08d4feea20d4a37

### Additional Information

BrowserView definitely seems to be the root cause of the issue seen here.  If I remove it and tell the secondary BrowserWindow to load the markup directly, then the content always renders properly.

_No response_

**Comment by codebytere** [comment]
@eFail i just ran your repro with 50 windows in a row and all painted successfully - this is happening on 14.0.0 exactly? Also the issue my commit fixes was caused by Chromium - my change compensates for that change.

**Comment by eFail** [comment]
@codebytere: Yes, with `v13.4.0` there is no repro.  Can open the second window infinite number of times and it always works.  If I change to `v14.0.0` in `package.config` and do an `npm install`, it then starts to repro.

If I remove `BrowserView` from the equation and load the markup on the window itself, then there is no repro.  So something changed in `BrowserView` between `v13.4.0` and `v14.0.0` to cause this.

**Comment by sssooonnnggg** [comment]
Same problem

**Comment by DillonHHH** [comment]
Quick Update:

` app.whenReady().then(() => {
    // In the main process.
    const { BrowserView, BrowserWindow } = require('electron')

    const win = new BrowserWindow({ width: 800, height: 600 })

    const view = new BrowserView()
    win.setBrowserView(view)
    view.setBounds({ x: 0, y: 0, width: 300, height: 300 })
    view.webContents.loadURL('https://electronjs.org').then(() => {
        if (view.webContents.isPainting)
            console.log('good')
        else
            console.log('bad')
    })
    //win.loadURL('https://electronjs.org')
}) `

reports good even though the webview is clearly not painting

**Comment by WaitGodot** [comment]
I found add code below can fixed.
`view.webContents.on('did-finish-load', () => {
			view.setBounds({
				x: 0,
				y: 0,
				width: 800,
				height: 600
			});
		})`

**Comment by felixrieseberg** [comment]
Just chiming in here: I've seen this while consulting, so I do believe that we still have an issue here (repros from 14.0 on all through 16.0, Windows only).

**Comment by matt-way** [comment]
I am having similar problems on 17. Moving browserviews to different windows causes painting issues (changing workspaces and bag again mac causes correct painting to occur). I feel like there is a deeper bug wrt this.
