### ISSUE TITLE
[Bug]: it doesn't show anything when opened

### ISSUE THREAD

**Issue by HrcxBlaze** [electron/electron#31110]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

newest version

### What operating system are you using?

Windows

### Operating System Version

20H2

### What arch are you using?

x64

### Last Known Working Electron version

idk

### Expected Behavior

it should show login with token

### Actual Behavior

![image](https://user-images.githubusercontent.com/89057304/134629832-b43f5a53-bec0-4e39-a38e-93944cd87100.png)
and sows this

### Testcase Gist URL

https://github.com/Flam3rboy/discord-bot-client

### Additional Information

no more info

**Comment by fatihmuhammad849** [comment]
where is the answer?
