### ISSUE TITLE
[Feature Request]: BrowserView can  send messages to each other

### ISSUE THREAD

**Issue by bei-yang** [electron/electron#31111]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I used Browserview before, but it didn't send messages to each other, so I used iframe

### Proposed Solution

BrowserView can send messages just like BrowserWindow

### Alternatives Considered

Use iframe instead of BrowserView

**Comment by samuelmaddock** [comment]
There are a few existing solutions to this which you could try out for your application:
- MessagePorts https://www.electronjs.org/docs/tutorial/message-ports
- BroadcastChannel https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API

With these, you can communicate directly between any frames within a WebContents.

**Comment by bei-yang** [comment]
> There are a few existing solutions to this which you could try out for your application:
> 
> * MessagePorts https://www.electronjs.org/docs/tutorial/message-ports
> * BroadcastChannel https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API
> 
> With these, you can communicate directly between any frames within a WebContents.

thanks,bro
