### ISSUE TITLE
[Bug]: clipboard.writeBuffer() regression

### ISSUE THREAD

**Issue by henrit** [electron/electron#31115]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

macOS

### Operating System Version

10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

14.0.1

### Expected Behavior

`clipboard.writeBuffer('rawFormat', Buffer.from('content'))` should write `content` into the clipboard as `rawFormat`.

### Actual Behavior

`clipboard.writeBuffer('rawFormat', Buffer.from('content'))` no longer places a `rawFormat` entry on the clipboard.

Instead, the data is being ["pickled"](https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-pickling/explainer.md#pickling-for-async-clipboard-api) to ensure it cannot seamlessly interact with native apps, which is appropriate for web pages, but not for electron apps.

This regression occurs on all platforms.

### Testcase Gist URL

https://gist.github.com/fd9dbdc151ab219f80ed1512ff964f39

### Additional Information

This is happening as a fallout of Chromium [removing support for its Raw Clipboard API](https://bugs.chromium.org/p/chromium/issues/detail?id=1217643).
Chromium's ui::ScopedClipboardWriter class is no longer exposing a mean to set raw data on the clipboard.

This sneaked past the tests in [api-clipboard.spec.js](https://github.com/electron/electron/blob/main/spec/api-clipboard-spec.js#L120) because the clipboard.read/readBuffer methods are "unpickling" data from the clipboard, which means that in isolation, using .writeBuffer() and .readBuffer() together appears to work.

The [fiddle linked](https://gist.github.com/henrit/fd9dbdc151ab219f80ed1512ff964f39) is using .writeBuffer() with .readText() to break that symmetry and expose the problem.

On older Electron builds (14.0.1 on Mac/Linux, 13.4.0 on Win), running the fiddle then pressing the "copy" and "paste" buttons in order will populate the text area.  
On Electron 15.0.0, the text area doesn't get populated. 

Inspecting the clipboard using external tools will show formats such as `com.web.custom.format0` on Mac, `application/web;type="custom/format0"` on Linux, and `Web Custom Format0` on Windows instead of the expected platform-specific plain text format.

**Comment by henrit** [comment]
I intend to propose a PR to tackle this a bit later, probably today.

**Comment by jkleinsc** [comment]
Fixed by:
- #31116
