### ISSUE TITLE
`beforeUnload` not triggering when closing app 

### ISSUE THREAD

**Issue by adsapientiam** [electron/electron#31128]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

11.0.0

### Expected Behavior

A function holding an axios requestor sends its content to the express database as it is triggered with "beforeunload" when the app closes.

### Actual Behavior

These methods in my React app's main component used to work and is supposed to as this follows what said here: https://stackoverflow.com/questions/39084924/componentwillunmount-not-being-called-when-refreshing-the-current-page. However, transplanting my app to a webpack template made this not work. 

Nonetheless it is able to work if an error triggers at the end of the `onUnload` function, most likely because the debugger stops every other process.

```javascript
    onUnload(){
        axios.post("http://localhost:2999/calendar/unload", {days:this.useCalendarData, subjects:this.userSubjects, lastWeekErase:this.lastWeekErase})
        .catch(err=>{console.log(err)})

        // if an error here triggers the debugger, the previous code of the function will run
    }
      
    componentDidMount() {
        window.addEventListener("beforeunload", this.onUnload)
    }
    
    componentWillUnmount() {
        window.removeEventListener("beforeunload", this.onUnload);
    }
```

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
