### ISSUE TITLE
[Bug]: Building fails with harfbuzz 3.0.0

### ISSUE THREAD

**Issue by darix** [electron/electron#31129]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.4.0

### What operating system are you using?

Other Linux

### Operating System Version

openSUSE Tumbleweed + Gnome 41

### What arch are you using?

x64

### Expected Behavior

it builds

### Actual Behavior

```
FAILED: obj/skia/skia/SkPDFSubsetFont.o          
g++ -MMD -MF obj/skia/skia/SkPDFSubsetFont.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DS
../../third_party/skia/src/pdf/SkPDFSubsetFont.cpp: In function 'sk_sp<SkData> subset_harfbuzz(sk_sp<SkData>, const SkPDFGlyphUse&, int)':
../../third_party/skia/src/pdf/SkPDFSubsetFont.cpp:74:5: error: 'hb_subset_input_set_retain_gids' was not declared in this scope; did you mean 'hb_subset_input_set_flags'?
   74 |     hb_subset_input_set_retain_gids(input.get(), true);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~            
      |     hb_subset_input_set_flags
../../third_party/skia/src/pdf/SkPDFSubsetFont.cpp:77:5: error: 'hb_subset_input_set_drop_hints' was not declared in this scope; did you mean 'hb_subset_input_set_user_data'?
   77 |     hb_subset_input_set_drop_hints(input.get(), false);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     hb_subset_input_set_user_data
../../third_party/skia/src/pdf/SkPDFSubsetFont.cpp:78:19: error: 'hb_subset' was not declared in this scope; did you mean 'subset'?
   78 |     HBFace subset(hb_subset(face.get(), input.get()));
      |                   ^~~~~~~~~
      |                   subset            
```

This bug has the reason why this API was remove

https://github.com/harfbuzz/harfbuzz/issues/3216

**Comment by ckerr** [comment]
Hey, thanks for reporting this.

Skia is an upstream project and, while 13.4.0 is supported, I suspect the easiest path would be to try using a newer version of Electron, since it likely has newer upstream snapshots where skia may have fixed this issue. Have you tried this with Electron 15.0.0 or a recent nightly / alpha / beta?

**Comment by darix** [comment]
well it seems signal-desktop wants 13.x . https://github.com/signalapp/Signal-Desktop/blob/development/package.json#L247

is there any automated way to check an electron app code base if it would work with a newer release?

**Comment by PF4Public** [comment]
If anyone's interested, I've built 13.6.2 and 13.6.3 against harfbuzz-3.1.1:
```
# ldd /usr/lib64/electron-13/electron | grep harf
	libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007fe87f11e000)
	libharfbuzz-subset.so.0 => /usr/lib64/libharfbuzz-subset.so.0 (0x00007fe87cffb000)
# equery b /usr/lib64/libharfbuzz.so.0
 * Searching for /usr/lib64/libharfbuzz.so.0 ... 
media-libs/harfbuzz-3.1.1 (/usr/lib64/libharfbuzz.so.0.30101.0)
media-libs/harfbuzz-3.1.1 (/usr/lib64/libharfbuzz.so.0 -> libharfbuzz.so.0.30101.0)
```

I had to partially apply following:
* [Roll src/third_party/harfbuzz-ng/src/ cc9bb2949..8c0c217b5 (159 commits) ](https://github.com/chromium/chromium/commit/b289f6f3fcbc33da759c560939ea8e49647de479)
* [Roll HarfBuzz from 2.6.4 to 2.8.2-147](https://github.com/google/skia/commit/66684b17b382fdfe6cc3d18bbbe46658115e8628)
* [Ease HarfBuzz API change with feature detection](https://github.com/google/skia/commit/51d83abcd24aae1b2e8e653f26af531c58b59a45)

Actual patches are as follows:
* [harfbuzz_roll.patch](https://github.com/PF4Public/gentoo-overlay/blob/aea52d8d1b71884bd031d2e45d2129aabfeb3102/dev-util/electron/files/harfbuzz_roll.patch)
* [skia_harfbuzz_roll.patch](https://github.com/PF4Public/gentoo-overlay/blob/aea52d8d1b71884bd031d2e45d2129aabfeb3102/dev-util/electron/files/skia_harfbuzz_roll.patch)
* [skia_harfbuzz_api.patch](https://github.com/PF4Public/gentoo-overlay/blob/aea52d8d1b71884bd031d2e45d2129aabfeb3102/dev-util/electron/files/skia_harfbuzz_api.patch)

PS: It is actually working (vscode screenshot):
![image](https://user-images.githubusercontent.com/10319700/144488258-1578b443-d63b-4560-99ba-bc1ba24f079c.png)
