### ISSUE TITLE
[Bug]: Recent Documents not working

### ISSUE THREAD

**Issue by kimlimjustin** [electron/electron#31120]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22000.194

### What arch are you using?

x64

### Expected Behavior

The recent documents show up when right-clicking on the app icon.

### Actual Behavior

Nothing shows up when I right-clicking on the app icon, only `Electron`, `Pin to Taskbar` and `Close all windows` option despite the code is the one I copied from the documentation.
![image](https://user-images.githubusercontent.com/61906684/134761603-91e2871e-93f5-4001-add9-32e497dec7bd.png)
options

### Testcase Gist URL

https://fiddle.electronjs.org/launch?target=electron/v15.0.0/docs/fiddles/features/recent-documents

### Additional Information

![image](https://user-images.githubusercontent.com/61906684/134761628-fbd9e33a-6355-41f0-a71b-99471411f959.png)

I pulled the code from the documentation `Launch` button without modifying any code and the recent documents not showing up.

However, apps like VSCode showing up the recent documents, IDK why? is the documentation not up to date?

**Comment by AB-Jeet** [comment]
May I work on this issue ??

**Comment by codebytere** [comment]
@kimlimjustin you need to register the application, see: https://github.com/electron/electron/blob/c0e72bd3357c1edaff30087307690d4a113bd01a/docs/tutorial/recent-documents.md#L75-L83

**Comment by fras2560** [comment]
@codebytere can you expand upon what needs to be done to register the application?

I am running into an issue where the list is not populated on only windows. I am using electron-forge and it seems a file association is made. I can right click open with on a file with the extension. It does not appears in the recent documents list though. Works fine on Mac
