### ISSUE TITLE
Breakpoints don't work after calling 'preventDefault' on a WebContents 'will-navigate' event

### ISSUE THREAD

**Issue by maxbrunsfeld** [electron/electron#3114]
Refs https://github.com/atom/atom/pull/9101

### Steps to repro:

1. Create an `index.html` with a `debugger`:

```html
<html>
<head><title>Electron</title></head>
<body>
  <script>
    setInterval(function() {
      debugger;
      console.log("Hello");
    }, 1000);
  </script>
</body>
</html>
```

2. Create a `main.js` that prevents navigation:

```js
var app = require('app');
var BrowserWindow = require('browser-window');

var mainWindow = null;

app.on('window-all-closed', function() {
  app.quit();
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    'auto-hide-menu-bar': true,
    'use-content-size': true,
  });
  mainWindow.loadUrl('file://' + __dirname + '/index.htm');
  mainWindow.focus();

  mainWindow.webContents.on('will-navigate', function(event) {
    console.log('cancel will-navigate event!');
    event.preventDefault();
  });
});
```

3. Run `electron main.js`, open the dev tools, and see the breakpoint working.

4. Attempt to reload with `command-r`, and see that the breakpoint stops working.

/cc @nathansobo
/cc @thomasjo

**Comment by ar7em** [comment]
There is a workaround with this bug for now – to use https://github.com/sindresorhus/electron-debug and toggle Developer Tools after page reload.

**Comment by zcbenz** [comment]
Unable to reproduce in 0.37.8 anymore.
