### ISSUE TITLE
[Bug]: URL passed into additionalArguments crashes renderer

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#31168]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1

### What arch are you using?

x64

### Last Known Working Electron version

13.5.0

### Expected Behavior

Passing a URL into `additionalArguments` does not crash renderers.
```ts
const mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    preload: path.join(__dirname, 'preload.js'),
    additionalArguments: [ 'https://foo' ]
  }
})
```

### Actual Behavior

Passing a URL into `additionalArguments` does crash renderers.

### Testcase Gist URL

https://gist.github.com/samuelmaddock/c05879cc1efd83d384001b60eeff3d24

**Comment by codebytere** [comment]
Bisected to https://github.com/electron/electron/compare/v14.0.0-beta.3...v14.0.0-beta.5

**Comment by samuelmaddock** [comment]
> @samuelmaddock also looks like this only happens with http(s) urls? Tried with some other arbitrary args (e.g. `--my-magic-arg=foo`) and no issue or crash 🤔

That's the same behavior I observed as well. In my application I've switched to JSON-encoded args to avoid the issue for now.

e.g.
```ts
additionalArguments: [
  JSON.stringify({ url: 'https://foo' })
]
```

**Comment by simo-an** [comment]
I found that the additionalArguments's item contains ' : ' , the window will crash. The url is just an exception.

Like:
```
additionalArguments: ['1:1', 'https://baidu.com']
```
My electron version is '18.1.0'

Is there any suggestions to fix this issue?

Now, I use the temporary method like use `btoa` to encode it.

**Comment by pushkin-** [comment]
I can still reproduce the crash. @samuelmaddock
