### ISSUE TITLE
[Bug]: Preload can't access guest window variables

### ISSUE THREAD

**Issue by Nashorn** [electron/electron#31170]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

macOS

### Operating System Version

10.15.7 Catalina

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

11.0.0

### Expected Behavior

preload.js should be able to access variables on the window object of guest page

### Actual Behavior

The variables that the guest page assigns to window is not present/visible or accessible (undefined) in preload.js

### Testcase Gist URL
https://gist.github.com/Nashorn/637ed70c8e840d2aec26d21f5dcbb8dd

### Additional Information

Example guest page that loads into webview assigns a simple variable to the window object:
```
window.someVar = {}
```

In preload.js, at some later time, (not during load or DOMContentLoaded), trying to access [someVar] returns undefined,
in preload.js:
```
console.log(global.someVar); // undefined
console.log(window.someVar); // also undefined
```
This previously worked in Electron 11 until upgrading to v12.0.0 and higher. Is there a new way to access variables on the guest window ?

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! This may be an issue with the changed `contextIsolation`default in Electron 12. When creating your main and guest windows, can you try adding `contextIsolation: false` to your window options and see if that solves the issue?

If that doesn't work, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by Nashorn** [comment]
Will build a test case today in electron fiddle, thanks for your help

**Comment by Nashorn** [comment]
Here is the gist i built in Electron Fiddle:
[Preload can't access guest window varaibles](https://gist.github.com/Nashorn/637ed70c8e840d2aec26d21f5dcbb8dd)

**Comment by Nashorn** [comment]
Previously worked in every electron but broke in v12.0.0 and on. I've tried v13,14,15 etc and still did not work.
Works in v11 and lower.

**Comment by Nashorn** [comment]
> Thanks for reporting this issue! This may be an issue with the changed `contextIsolation`default in Electron 12. When creating your main and guest windows, can you try adding `contextIsolation: false` to your window options and see if that solves the issue?
> 
> If that doesn't work, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance!

Here is my webPrefs, i've experimented with that too, did not work:

```
webPreferences : {
      plugins: false,
      webSecurity:false,
      nodeIntegration:true,
      allowEval: true,
      contextIsolation:false,
      allowRunningInsecureContent:true,
      webviewTag:true,
      preload: fs_path.join(__dirname, 'preload.js'),
      enableRemoteModule: true,
      nodeIntegrationInSubFrames:false,
      experimentalFeatures:true,
      scrollBounce:true,
      worldSafeExecuteJavaScript:false
    }
    ```

**Comment by Nashorn** [comment]
Should the **blocked/need-repo** status label on this be removed @VerteDinde ?

**Comment by miniak** [comment]
@Nashorn you need to remove or fix the CSP
> "Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-rQ85L1F79h7kLs/FJOlG3a1TEhRcsdD1opvhuY9gRto='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by miniak** [comment]
When I fix the CSP issue, your sample works. The relevant change to this was done in Electron 12: https://www.electronjs.org/docs/latest/breaking-changes/#default-changed-contextisolation-defaults-to-true

**Comment by Nashorn** [comment]
I'll verify this fix and get back to this thread.

**Comment by Nashorn** [comment]
I was able to comment out the CSP in meta tag and it did work. Thats understandable. But i created a new gist to replicate my software more precisely. **The problem is accessing the global window variables of the pages loaded inside the webview tag.**

See Fiddle:
[Accessing global window variables in webview from preload.js](https://gist.github.com/Nashorn/3dc47925816aac52ef588874e1b51d25)

GIST:
https://gist.github.com/Nashorn/3dc47925816aac52ef588874e1b51d25

So in our companies application, we are using a layout.html which have areas for toolbars, address bar and trays, and a webview tag in the main area (like a browser) that loads external websites into it. These sites have no CSP and they are all owned by us.

**The problem is accessing the global window variables of the pages loaded inside the webview tag.** This previously worked until Electron v12. Am i configuring something wrong? Currently our app heavily depends on this and the workaround is to stay on v12 until it's fixed.

Any solution?

**Comment by Nashorn** [comment]
UPDATE: Resolved.
in Electron v12 and up, webpreferences attribute on webview tag needs to be set:

```
<webview style="border:1px solid black;" id="browser" src="some-external-webpage.html" 
    webpreferences="contextIsolation=false, webSecurity=false, nodeIntegration=false, allowRunningInsecureContent, javascript=yes"  
    disablewebsecurity preload="./preload.js"></webview>
    ```
