### ISSUE TITLE
[Bug]: qbitorrent

### ISSUE THREAD

**Issue by SAN9212** [electron/electron#31172]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12

### What operating system are you using?

Other (specify below)

### Operating System Version

unraid 6.9.2

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

12

### Expected Behavior

add torrent using electorrent see the added torrent in qbitorrent

### Actual Behavior

cant see any torrent in qbitorrent anymore only see the added torrents in electorrent

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! It sounds like the bug you're reporting is specific to Electorrent. Please report this bug to that repo directly and they can address it.
