### ISSUE TITLE
[Bug]: BrowserView setBounds does not work for negative (x,y) values

### ISSUE THREAD

**Issue by phytemit** [electron/electron#31186]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

13.1.1

### Expected Behavior

BrowserView's setBounds method allows to set content being rendered off screen, using negative values for (x,y).

### Actual Behavior

Since version 13.2.2 (also tested on 14.X, 15.X) negative values passed to setBounds (x,y) are treated as (0,0).

### Additional Information

Just try to render any web page in BrowserView, use setBounds with negative (x,y).

**Comment by BoyWULiWei** [comment]
我在linux下也出现同样的问题，请问你该问题找到解决办法了吗？

**Comment by phytemit** [comment]
No, issue remains.

**Comment by phytemit** [comment]
Issue remains

**Comment by phytemit** [comment]
Checked Electron 22. Issue fixed.
