### ISSUE TITLE
[Bug]: Build failed TypeError: 'insert_comments' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by luyahan** [electron/electron#31183]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Linux p9-plct 4.15.0-144-generic #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

Build pass 

### Actual Behavior

luyahan@p9-plct:~/source/electron/src/out/Release $ ninja -j52
[4342/76430] ACTION //tools/metrics:histograms_xml(//build/toolchain/linux:clang_x64)
FAILED: histograms.xml
python3 ../../tools/metrics/histograms/merge_xml.py --output histograms.xml
Traceback (most recent call last):
  File "../../tools/metrics/histograms/merge_xml.py", line 211, in <module>
    main()
  File "../../tools/metrics/histograms/merge_xml.py", line 207, in main
    histogram_paths.ALL_XMLS + [histogram_paths.UKM_XML]))
  File "../../tools/metrics/histograms/merge_xml.py", line 193, in PrettyPrintMergedFiles
    MergeFiles(filenames=filenames, files=files, should_expand_owners=True))
  File "/home/luyahan/source/electron/src/tools/metrics/histograms/histogram_configuration_model.py", line 268, in PrettifyTree
    return HISTOGRAM_CONFIGURATION_XML_TYPE.PrettyPrint(histograms)
  File "/home/luyahan/source/electron/src/tools/metrics/histograms/../common/models.py", line 507, in PrettyPrint
    return self.GetPrintStyle().PrettyPrintXml(self._ToXML(obj))
  File "/home/luyahan/source/electron/src/tools/metrics/histograms/../common/pretty_print_xml.py", line 95, in PrettyPrintXml
    return self._PrettyPrintMinidom(tree)
  File "/home/luyahan/source/electron/src/tools/metrics/histograms/../common/pretty_print_xml.py", line 108, in _PrettyPrintMinidom
    etree_root = etree_util.ParseXMLString(raw_xml)
  File "/home/luyahan/source/electron/src/tools/metrics/histograms/../common/etree_util.py", line 99, in ParseXMLString
    raw_xml, ET.XMLParser(target=ET.TreeBuilder(insert_comments=True)))
TypeError: 'insert_comments' is an invalid keyword argument for this function
[4393/76430] ACTION //third_party/libaom:libaom

**Comment by luyahan** [comment]
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
```
luyahan@p9-plct:~/source/electron/src/out/Release $ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
attrs (20.3.0)
beautifulsoup4 (4.6.0)
certifi (2020.12.5)
chardet (4.0.0)
click (6.7)
cloud-init (19.1.8)
colorama (0.3.7)
command-not-found (0.3)
configobj (5.0.6)
cryptography (2.1.4)
devscripts (2.17.12ubuntu1.1)
distro-info (0.18ubuntu0.18.04.1)
elementpath (2.3.2)
fail2ban (0.10.2)
gpg (1.10.0)
html5lib (0.999999999)
idna (2.10)
importlib-metadata (3.7.3)
Jinja2 (2.11.3)
jsonpatch (1.32)
jsonpointer (2.1)
jsonschema (3.2.0)
keyring (10.6.0)
keyrings.alt (3.0)
language-selector (0.1)
lxml (4.6.3)
MarkupSafe (1.1.1)
netifaces (0.10.4)
oauthlib (3.1.0)
paramiko (2.0.0)
petname (2.2)
pip (9.0.1)
progressbar (2.3)
pyasn1 (0.4.2)
pycrypto (2.6.1)
pyelftools (0.24)
pygobject (3.26.1)
pyinotify (0.9.6)
pymacaroons (0.13.0)
PyNaCl (1.1.2)
pyrsistent (0.17.3)
pysha3 (1.0.2)
python-apt (1.6.5+ubuntu0.7)
python-debian (0.1.32)
python-magic (0.4.16)
pyxdg (0.25)
PyYAML (5.4.1)
requests (2.25.1)
requests-toolbelt (0.8.0)
requests-unixsocket (0.1.5)
scour (0.36)
SecretStorage (2.3.1)
setuptools (54.1.2)
simplejson (3.13.2)
six (1.15.0)
snapcraft (2.43.1+18.4.1)
ssh-import-id (5.7)
systemd-python (234)
tabulate (0.7.7)
typing-extensions (3.7.4.3)
ubuntu-advantage-tools (27.2)
ufw (0.36)
unattended-upgrades (0.1)
unidiff (0.5.4)
urllib3 (1.26.4)
webencodings (0.5)
wheel (0.30.0)
zipp (3.4.1)
```

**Comment by codebytere** [comment]
Please use https://github.com/electron/build-tools and report further issues there.
