### ISSUE TITLE
[Bug]: webrtc screen/window capturer cannot capture other app without creating mainWindow first

### ISSUE THREAD

**Issue by chenzx** [electron/electron#31182]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina

### What arch are you using?

x64

### Expected Behavior

I'm using electron's desktopCapturer to do app window capture  & then stream it to mediasoup webrtc server.

However, i find that desktopCapturer can only be used to capture other app's window AFTER mainWindow is created, which means I have to click once on electron app to activate(?)

I try to use desktopCapturer directly without creating any renderer window, that is to say, try to use it in headless CLI mode, but failed.

```
ReferenceError: navigator is not defined
```

Can i do app window screen sharing without click on electron?

### Actual Behavior

see description above.

**Comment by chenzx** [comment]
my js code using screenCapturer API and mediasoup client lib:

```
//https://www.electronjs.org/docs/api/desktop-capturer
const { desktopCapturer } = require('electron')
const mediasoup = require('mediasoup-client');
const socketClient = require('socket.io-client');
const socketPromise = function(socket) {
  return function request(type, data = {}) {
    return new Promise((resolve) => {
      socket.emit(type, data, resolve);
    });
  }
};
//signaling is based on https://github.com/mkhahani/mediasoup-sample-app:
const webrtcServerUrl = 'http://127.0.0.1:3000';

let socket;
let device;
let producer;

desktopCapturer.getSources({ types: ['window', 'screen'] }).then(async sources => {
  for (const source of sources) {
    console.log(source);
    if (source.name === 'myapp') {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({
          audio: false,
          video: {
            mandatory: {
              chromeMediaSource: 'desktop',
              chromeMediaSourceId: source.id,
              minWidth: 1280,
              maxWidth: 1280,
              minHeight: 720,
              maxHeight: 720
            }
          }
        })
        await handleStream(stream)
      } catch (e) {
        handleError(e)
      }
      return
    }
  }
})

async function loadDevice(routerRtpCapabilities) {
  try {
    device = new mediasoup.Device();
  } catch (error) {
    if (error.name === 'UnsupportedError') {
      console.error('browser not supported');
    }
  }
  await device.load({ routerRtpCapabilities });
  return device
}

async function handleStream (stream) {
  console.log("handle stream")
  const opts = {
    path: '/server',
    transports: ['websocket'],
  };
  socket = socketClient(webrtcServerUrl, opts);
  socket.request = socketPromise(socket);
  const routerRtpCapabilities = await socket.request('getRouterRtpCapabilities');
    //Note: latest chrome version doesn't support H264 anymore! use VP8;
  device = await loadDevice(routerRtpCapabilities);
  const data = await socket.request('createTransport', {
    forceTcp: false,
    rtpCapabilities: device.rtpCapabilities,
  });
  if (data.error) {
    console.error(data.error);
    return;
  }
  const transport = device.createSendTransport(data);
  transport.on('connect', async ({ dtlsParameters }, callback, errback) => {
    socket.request('connectTransport', { dtlsParameters })
      .then(callback)
      .catch(errback);
  });

  transport.on('produce', async ({ kind, rtpParameters }, callback, errback) => {
    try {
      const { id } = await socket.request('produce', {
        transportId: transport.id,
        kind,
        rtpParameters,
      });
      callback({ id });
    } catch (err) {
      errback(err);
    }
  });

  transport.on('connectionstatechange', (state) => {
    console.log("state: "+state)
    switch (state) {
      case 'connecting':
        break;
      case 'connected':
        break;
      case 'failed':
        transport.close();
      break;
      default: break;
    }
  });
  
  const track = stream.getVideoTracks()[0];
  const params = { track };
  //if ($chkSimulcast.checked) 
  {
    params.encodings = [
      { maxBitrate: 100000 },
      { maxBitrate: 300000 },
      { maxBitrate: 900000 },
    ];
    params.codecOptions = {
      videoGoogleStartBitrate : 1000
    };
  }
  producer = await transport.produce(params);
}

function handleError (e) {
  console.log(e)
}
```

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.
