### ISSUE TITLE
[Bug]: high CPU usage after app quit/exit/close

### ISSUE THREAD

**Issue by josephernest** [electron/electron#31195]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10, Windows 7

### What arch are you using?

x64

### Expected Behavior

Expected: the app should close, and the `electron.exe` process should not be there anymore.

### Actual Behavior

Actual behaviour: after app termination, `electron.exe` process is still running, with very high CPU (25% on my 4-core computer), even if it does not anything anymore.

I use:

```
ipcMain.on('close', (event) => {
        browserWindow.close();
    });   

app.on('window-all-closed', () => {
    jsonstorage.set('abc', { a: 1, b: 2, c: 3}, function() { 
        app.quit(); 
    });
});
```

The bug is present with version 4.2.12 but also 10.4.7.

**Comment by EthianWong** [comment]
I have same problem (WindowsOS / electron: v12.0.6)

**Comment by EthianWong** [comment]
I have same problem (WindowsOS / electron: v12.0.6)

**Comment by sircharlo** [comment]
Same for me on my electron app; this has been happening randomly for many months now. The process completely locks up one cores (13% in my Task Manager). I'm at a loss to explain what causes this. I searched for a way to debug, but came up short so far.
