### ISSUE TITLE
[Bug]: Let's Encrypt root CA isn't working properly 

### ISSUE THREAD

**Issue by leonekmi** [electron/electron#31212]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0
Reproduced on Electron 12, 13, 14

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux rolling

### What arch are you using?

x64

### Expected Behavior

The request to `https://letsencrypt.org` (or any Let's Encrypt secured website) should work in the main process as the certificate chain seems valid.

### Actual Behavior

It doesn't work in the main process. However, it works in the renderer (with standard Fetch API) or in Node 16.5 REPL (also with Axios).

### Testcase Gist URL

https://gist.github.com/fc9cc8d91df7d02f211698f9aceb0087

### Additional Information

I think it's probably related to the recent expiry of DST Root CA X3 but strangely enough, it's working properly on the renderer and in a single Node app?

My understanding is that by default, Node.js uses a capture of the Mozilla trust CA, could it be that the Electron one is unsynced?

**Comment by StephenSorriaux** [comment]
Hi,

Exact same problem since the DST Root CA X3 expiration today.

**Comment by paulr113** [comment]
Hello,
I'm experiencing the exact same problem. This seems to be an urgent issue.

**Comment by shdunning** [comment]
Ditto.

**Comment by MangoPreme** [comment]
Experiencing the same issue right now.

**Comment by franelj** [comment]
Same on Electron 11

**Comment by guldil** [comment]
Same problem with an old electron 8.0 app, we didnt change anything since one year and it stop working today :
```
$ (node:17196) UnhandledPromiseRejectionWarning: Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
    at TLSSocket.emit (events.js:200:13)
    at TLSSocket._finishInit (_tls_wrap.js:792:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)
(node:17196) UnhandledPromiseRejectionWarning: Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
    at TLSSocket.emit (events.js:200:13)
    at TLSSocket._finishInit (_tls_wrap.js:792:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)
(node:17196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:17196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
$```

i already renewed my certifcate...

**Comment by BarryCarlyon** [comment]
Same issue on Windows node v14.18

Also regenerated the server cert. No joy

**Comment by laurent22** [comment]
Is there any alternative to Let's Encrypt that could be used while the problem is being worked on?

**Comment by mchiron** [comment]
For those that have this problem and control of the server, you might want to change to your certificate for one that is still valid. If your acme client allows you to change CA, you can try ZeroSSL ACME Certs to replace your current LetsEncrypt. Since ZeroSSL signing certificate has not changed, it might work where your current LetsEncrypt one won't (Note that I did not test this).

**Comment by leonekmi** [comment]
One dirty workaround I found was to create a CA array and add it to the `ca` array of the https, tls agent like this:

```
export const ISRGCAs = [`-----BEGIN CERTIFICATE-----
MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
-----END CERTIFICATE-----`];

// Then further in the code

import {Agent} from 'https';

const agent = new Agent({ca: ISRGAppendedCAs});

// Use it in your https wrapper like got, axios, etc.
```

**Comment by aaclayton** [comment]
Related thread with some findings: https://community.letsencrypt.org/t/issues-with-electron-and-expired-root/160991

**Comment by aaclayton** [comment]
Follow up on my prior message, the proposed approach there has worked properly with two modifications: removing the `=` in the `--preferred-chain` argument and doing a hard restart of nginx (rather than a reload) to force the new certificate live (I don't know why reload did not work in this case).

```
sudo certbot certonly --nginx -d <domain> --preferred-chain "ISRG Root X1"
sudo service nginx restart
```

Hope this solution helps others to obtain a valid shortened certificate chain until the long term issue is resolved at the Electron level.

**Comment by doesdev** [comment]
Well, this is a particularly disastrous bug. Certificate chain is completely valid by every metric and using every client... except Electron. Problem is the same in 16.0.0-alpha.2 even. Node client is fine, all browsers we've tried on Windows and Mac, OpenSSL, every SSL checker I've run it through reports all is healthy and good across the certificate chain. All certificates freshly re-generated.

We're pretty much DOA at the moment.

**Comment by laurent22** [comment]
Thanks @aaclayton, that fix seems to work fine for us.

**Comment by nathanlesage** [comment]
I tried @aaclayton's fix but my Electron app still refuses. I'm on Electron 14.0.0 and the server is using an Apache. I just force-renewed the certificates using the ISRG root as a preferred chain root, incl. restart and all that yadda yadda, but unfortunately unsuccessful.

**Comment by jviotti** [comment]
We (Postman.com) have a potential fix. Running some further tests and sending a PR if it all goes fine.

**Comment by socratese** [comment]
Also experiencing this issue.. anyone else spend a while debugging to realise it was electrons fault?

**Comment by khypsos** [comment]
For those who still have the problem. 

We were using the full chain containing the certificate --> the R3 --> the new X1

We just removed the X1 from the full chain and like pure magic electron is back on again :) 

Hope it helps

**Comment by jviotti** [comment]
Here is the PR: https://github.com/electron/electron/pull/31213. It seems to work fine for us but if you could also give it a spin, that would be great!

**Comment by leonekmi** [comment]
Removing the last certificate present in `fullchain` and reloading/restarting the webserver seems to work as a quick'n'dirty fix.
Tested on Apache and Nginx.

**Comment by nathanlesage** [comment]
@benmordecai Yeah they stopped shipping Certbot updates via APT a while ago, I had to notice as well. They now offer snap packages. Just follow their instructions [here](https://certbot.eff.org/lets-encrypt/debianbuster-apache) to update to the newest version

**Comment by MrPrimate** [comment]
FYI If you're using Caddy the following worked for me:

```
domain.com {
    reverse_proxy localhost:3000
    tls {
        issuer acme {
            preferred_chains {
                root_common_name "ISRG Root X1"
            }
        }
    }
}
```

I had to remove my current certificates, and restart caddy.

**Comment by Ciberusps** [comment]
If u use `axios` for requests temporary workaround might be to disable SSL, works fine for us as a temporary solution until fix
P.S. electron@11.4.3
```
const agent = new https.Agent({
  rejectUnauthorized: false,
});

axios.defaults.httpsAgent = agent;
```

**Comment by guldil** [comment]
I solved the problem by buying a $15 certificate after two and a half hours of fruitless searching. Users of my application have been blocked for too long... Now i cant wait one year for a fix !

**Comment by sudhamab** [comment]
replacing the cert worked for us also

**Comment by Nicd** [comment]
> Follow up on my prior message, the proposed approach there has worked properly with two modifications: removing the `=` in the `--preferred-chain` argument and doing a hard restart of nginx (rather than a reload) to force the new certificate live (I don't know why reload did not work in this case).
> 
> ```
> sudo certbot certonly --nginx -d <domain> --preferred-chain "ISRG Root X1"
> sudo service nginx restart
> ```
> 
> Hope this solution helps others to obtain a valid shortened certificate chain until the long term issue is resolved at the Electron level.

If you are using the acme.sh client like I am, it also supports the preferred chain option in recent versions, see here for how to set it up: https://github.com/acmesh-official/acme.sh/wiki/Preferred-Chain

Setting "ISRG Root X1" as the preferred chain and restarting nginx allowed the Atom editor to connect to my service again.

**Comment by datacosmos** [comment]
We have the same problem. 
However ubuntu 20.04's  certbot version is too old for the preferred-chain cli parameter. 
But removing the last cert (Issuer: O = Digital Signature Trust Co., CN = DST Root CA X3) inside the file /et/letsencrypt/live/{domain}/fullchain.pem helped!

But this is only a temporary workaround - after the next renewal one have to manually edit the chain again?

Is there a patch which can be applied?

**Comment by MarshallOfSound** [comment]
Although this has been closed, we still need to backport the original PR to ~5 branches and ship 5 new releases (12, 13, 14, 15, 16).  You can monitor those as we kick them off at https://releases.electronjs.org

They should be out (if nothing goes wrong) in ~3 hours.

**Comment by cata-code** [comment]
This is what worked for me:

- `sudo apt purge certbot python3-certbot-nginx`
- comment out all certificate lines in the nginx conf files of your websites
- `sudo nginx -t`
- `sudo service nginx restart && sudo service nginx status`

Then you need to install the dreadful snap and certbot, and then generate a new certificate with the `preferred-chain` option, which is only available on the new versions of `certbot`

```
sudo install snap
sudo snap install core
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
sudo certbot --nginx --preferred-chain "ISRG Root X1"
```

Now electron understands letsencrypt certificates.

**Comment by jlongster** [comment]
What's the release cadence of Electron (i.e. when will these backports be released)?

**Comment by molant** [comment]
@jlongster soon.
You can see [this comment](https://github.com/electron/electron/issues/31212#issuecomment-931641110) and real time status in https://releases.electronjs.org/

**Comment by jlongster** [comment]
I had an old tab open that didn't have those comments; sorry and thanks!

**Comment by paulrosania** [comment]
Thank you for the incredible hustle to get this fix out the door! We're super thankful. ❤️

**Comment by Delagen** [comment]
@molant Where can I monitor when is npm packages appeared in registry ?

**Comment by Name-less** [comment]
> Here is the official Let's Encrypt statement: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
> 
> I tried using this solution...
> 
> > Follow up on my prior message, the proposed approach there has worked properly with two modifications: removing the `=` in the `--preferred-chain` argument and doing a hard restart of nginx (rather than a reload) to force the new certificate live (I don't know why reload did not work in this case).
> > ```
> > sudo certbot certonly --nginx -d <domain> --preferred-chain "ISRG Root X1"
> > sudo service nginx restart
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this solution helps others to obtain a valid shortened certificate chain until the long term issue is resolved at the Electron level.
> 
> ... but my version of certbot (0.31.0) does not support the --preferred-chain option. Since I am running debian 10, 0.31.0 is the latest version.

You can use the last version of certbot using snapd to install it (https://certbot.eff.org/lets-encrypt/debianbuster-apache.html)
You will have the version 1.19.0 on your debian 10 OS

It work for me, and after launching 
certbot --nginx --preferred-chain "ISRG Root X1" 
Everything was ok on my electron app :)

**Comment by AbdeenM** [comment]
Not sure if this the right issue to post the solution too cause there are various issues related to the expiry but here goes.

The expired certificate "DST Root CA X3" seems to be used by default to sign timpstamps, etc. for your systems config for my case it was trying to build an electron standalone app, after sometime of researching this, this is what i came up with (Am using a windows OS but you should be able to reflect for your respective OS):

1. Select `Run` from the `Start menu`
2. Search for `certlm.msc` and open it
3. On the left panel tab you will find directories that hold your systems certificates and their respective functions, what we are interested in is "DST Root CA X3" so navigate to `Trusted Root Certification Authorities`, now on the left open `Certificates`
4. You should be able to see your "DST Root CA X3" certificate, right click and select `Properties`.
5. By default you will find that it is `Enable only the following purposes`, select the `Disable all purposes for this certificate`
6. Click Apply then OK.
7. Restart your machine

For other OS users essentially you want to find your machines "DST Root CA X3" and disable it or delete the choice is yours, once done restart your machine so it takes affect, your machine will automatically fallback to next signing chain.

Hope it helps!

**Comment by dmitriy-komarov** [comment]
Not only Electron is affected.

Here is a dirty workaround for Node apps which stopped getting correct response from servers with buggy Let's Encrypt certificates:

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';`

add it before any network request to such servers.

I place this here due to this thread is in the top of Google search results by "nodejs letsencrypt" keywords.

**Comment by Nicd** [comment]
@dmitriy-komarov Don't do that. That will disable certificate verification entirely and your requests will be insecure. Instead wait for Electron patch, apply it yourself, or apply one of the server side workarounds.

**Comment by popod** [comment]
Thank you for this fix!

As @guldil and to fix the problem as soon as possible for our users, we've bought another certificate and this fix this cert validation error! We will release an update of our application in a near future to completely get rid of this.

But could someone explain to me why a Let's Encrypt certificate which seems to be valid and works when accessed from a browser is not trusted with electron ? (why electron was not ready for that planned expiration? Is this a bug in electron or does electron using an older version of OpenSSL which seems to have a bug with certificate validation? or else... ?)

I know that perhaps this is not the good place to ask for explanations, but I think that this could be useful for others.

Thanks in advance for the explanations!

**Comment by nathanlesage** [comment]
@popod Basically all LE certs have the following chain:

`Website (cert that you use on your server) --> R3 (the main cert LE uses) --> ISRG Root X1 (the new and valid root) --> DST Root CA X3 (the old one that expired).`

The DST root is still in the chain because of backwards compatibility (since certificates need to be provided to a device with an update, which old devices don't get anymore).

There is a flag in OpenSSL called `X509_V_FLAG_TRUSTED_FIRST`. If that flag is *not* set, OpenSSL will follow the *full* chain and attempt to verify *every* certificate in the chain. It will encounter the DST root and detect (correctly) that it's not valid anymore. If the flag *is* set, however, this instructs OpenSSL to stop checking once it encounters a correct and valid root cert.

This flag is set on most implementations, but for Electron it has been missed. The linked PR that includes the fix simply sets this flag.

**Comment by vmartins** [comment]
> Here is the official Let's Encrypt statement: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
> 
> I tried using this solution...
> 
> > Follow up on my prior message, the proposed approach there has worked properly with two modifications: removing the `=` in the `--preferred-chain` argument and doing a hard restart of nginx (rather than a reload) to force the new certificate live (I don't know why reload did not work in this case).
> > ```
> > sudo certbot certonly --nginx -d <domain> --preferred-chain "ISRG Root X1"
> > sudo service nginx restart
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this solution helps others to obtain a valid shortened certificate chain until the long term issue is resolved at the Electron level.
> 
> ... but my version of certbot (0.31.0) does not support the --preferred-chain option. Since I am running debian 10, 0.31.0 is the latest version.
> >     
> >   

1. update the certbot to the last version using [snap](https://snapcraft.io/docs/installing-snapd/) ([certbot instructions](https://certbot.eff.org/lets-encrypt/ubuntubionic-apache))
```
$ sudo snap install core
$ sudo snap refresh core
$ sudo apt-get remove certbot
$ sudo snap install --classic certbot
$ sudo ln -s /snap/bin/certbot /usr/bin/certbot
```
2. renew & replace the certificate
```
certbot certonly --apache -d www.yourdomain.com --preferred-chain "ISRG Root X1"
service apache2 reload
```

**Comment by Aymkdn** [comment]
>     1. update the certbot to the last version using snap
> 
> ```
> $ sudo snap install core
> $ sudo snap refresh core
> $ sudo apt-get remove certbot
> $ sudo snap install --classic certbot
> $ sudo ln -s /snap/bin/certbot /usr/bin/certbot
> ```
> 
>     1. renew & replace the certificate
> 
> 
> ```
> certbot certonly --apache -d www.yourdomain.com --preferred-chain "ISRG Root X1"
> service apache2 reload
> ```

It's exactly what I did, but I still have R3 in the chain...
If I do:
>  openssl s_client -connect assistant-api.kodono.info:443 -servername assistant-api.kodono.info

It returns:
> Certificate chain
> 0 s:CN = assistant-api.kodono.info
>   i:C = US, O = Let's Encrypt, CN = R3
> 1 s:C = US, O = Let's Encrypt, CN = R3
>  i:C = US, O = Internet Security Research Group, CN = ISRG Root X1

If I try to manually remove the R3 cert from the fullchain,pem file, then Apache doesn't want to start. If I remove the X1 cert, Apache starts normally. 

I need this R3 to be removed all together.

Any idea?

**Comment by Nicd** [comment]
R3 is the intermediate certificate and it is required for the certificate chain to work. Why do you want to remove it? Your certificate verifies correctly for me.

**Comment by Aymkdn** [comment]
Yeah looks good now! Thanks @Nicd

**Comment by shaoran** [comment]
> Here is the official Let's Encrypt statement: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
> 
> I tried using this solution...
> 
> > Follow up on my prior message, the proposed approach there has worked properly with two modifications: removing the `=` in the `--preferred-chain` argument and doing a hard restart of nginx (rather than a reload) to force the new certificate live (I don't know why reload did not work in this case).
> > ```
> > sudo certbot certonly --nginx -d <domain> --preferred-chain "ISRG Root X1"
> > sudo service nginx restart
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this solution helps others to obtain a valid shortened certificate chain until the long term issue is resolved at the Electron level.
> 
> ... but my version of certbot (0.31.0) does not support the --preferred-chain option. Since I am running debian 10, 0.31.0 is the latest version.

Same problem here, I ended up installing miniconda and then using `certbot` from miniconda.

```console
# as root

bash Miniconda3-latest-Linux-x86_64.sh -b -p py3/
source py3/bin/activate
conda create -n certbot certbot -c conda-forge
conda activate certbot
certbot delete
cerbot ... --preferred-chain "ISRG Root X1"
```

I needed to delete the certificate first, because the `--preferred-chain` option did not work with the `renew` command.

MQTT Explorer is now able to connect to my broker again.

**Comment by TitanRob16** [comment]
Totally annoying. I've tried every command in this thread to no avail. I've still got the "unrecognized arguments: --preferred_chain=ISRG Root X1" error from certbot on a Debian system.

**Comment by s-a** [comment]
@datacosmos Yes, but nevertheless you are right! I am stupid. Thanks for confirmation 😅

**Comment by alielmajdaoui** [comment]
> For those who still have the problem.
> 
> We were using the fullchain.cer containing the certificate, the R3 and the new ISRG Root X1
> 
> We just removed the X1 from the fullchain.cer and like pure magic electron is back on again :)
> 
> Hope it helps

works well!

Please consider removing the same cert from the chain.pem file as well to prevent this error:

> Renewal configuration file /etc/letsencrypt/renewal/example.com.conf produced an unexpected error: fullchain does not match cert + chain for example.com!. Skipping.

**Comment by cappicard** [comment]
> One dirty workaround I found was to create a CA array and add it to the `ca` array of the https, tls agent like this:
> 
> ```
> export const ISRGCAs = [`-----BEGIN CERTIFICATE-----
> MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
> TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
> cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
> WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
> ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
> MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
> h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
> 0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
> A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
> T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
> B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
> B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
> KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
> OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
> jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
> qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
> rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
> HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
> hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
> ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
> 3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
> NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
> ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
> TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
> jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
> oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
> 4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
> mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
> emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
> -----END CERTIFICATE-----`];
> 
> // Then further in the code
> 
> import {Agent} from 'https';
> 
> const agent = new Agent({ca: ISRGCAs});
> 
> // Use it in your https wrapper like got, axios, etc.
> ```
> 
> _Note that you cannot expand with `tls.rootCertificates` unless you remove some certs that cofuses resolution_

This suggestion is what I am using. In my case, it's with the version of Electron provided by Expo.

**Comment by 33246K44** [comment]
Not really a coder but. If this helps..:
const https = require('https');
const fs = require('fs');

// Assuming ISRGCAs contains the ISRG Root X1 certificate string
const ISRGCAs = fs.readFileSync('isrgrootx1.pem', 'utf8');

const agent = new https.Agent({ ca: ISRGCAs });

const options = {
  hostname: 'letsencrypt.org',
  path: '/',
  method: 'GET',
  // Pass the custom agent to the request
  agent: agent
};

https.request(options, (res) => {
  console.log('statusCode:', res.statusCode);
  res.on('data', (d) => {
    process.stdout.write(d);
  });
}).on('error', (e) => {
  console.error(e);
}).end();
