### ISSUE TITLE
[Bug]: it litterally just doesnt work, it's a screen with 2 text boxes and the word "add" with some dropdown things at the top

### ISSUE THREAD

**Issue by ThatRedDragon** [electron/electron#31226]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

i expected to be able to see the server my bot was in, to talk in it, and to see other's messages, and to see channels, just basically a regular discord client but logged into a bot

### Actual Behavior

its just a few dropdown menus and 2 text boxes

**Comment by miniak** [comment]
This does not seem like an Electron issue
