### ISSUE TITLE
[Bug]:shell.openExternal can't open a windows directory which contains chinese charactors

### ISSUE THREAD

**Issue by hayword-wang** [electron/electron#31223]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 1803 Version 2019.05.28

### What arch are you using?

x64

### Last Known Working Electron version

9.0.0

### Expected Behavior

shell.openExternal open the directory 'D:/测试'

### Actual Behavior

`shell.openExternal('D:/测试')`
`Uncaught (in promise) Error: Failed to open`

**Comment by miniak** [comment]
Electron 9 is not supported. Please file a new bug in case you can still report this issue on a supported version of Electron,
