### ISSUE TITLE
[Bug]: Updated NPM Packages missing in NPM registry

### ISSUE THREAD

**Issue by Delagen** [electron/electron#31224]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows

### What arch are you using?

x64

### Last Known Working Electron version

15.0.0

### Expected Behavior

15.1.0 succcessfully installed from npm

### Actual Behavior

missing package in NPM package registry

### Additional Information

Need version with fixed LetsEncrypt bug https://github.com/electron/electron/issues/31212

**Comment by Delagen** [comment]
@MarshallOfSound where are packages?

**Comment by MarshallOfSound** [comment]
The issue comment I left explains quite succinctly that we're working on getting these releases out.  15.1.0 hit a snag but should be out shortly, raising new issues doesn't help.  Trust me if anyone knows when a release fails, it's the people running it ...

As mentioned elsewhere you can track release progress at https://releases.electronjs.org

**Comment by Delagen** [comment]
Mentioned pages shows nothing usefull. It doesn.t show even why 14.1.0 is available, but 15.1.0 not. Only usefull info on that is version of included node.js

**Comment by MarshallOfSound** [comment]
![image](https://user-images.githubusercontent.com/6634592/135651557-c587f0c8-12dc-465b-9f5c-3dbed1f5c6cb.png)

Can you not see that the release is still running / being re-run? I do not believe their are any authentication barriers on that.

Direct link to the release https://releases.electronjs.org/release-build/ROLfK_9Pz

**Comment by Delagen** [comment]
This section appeared recently. Supported already contains version 15.1.0, and no other info. How can I understand, that something releasing under 15-x-y is 15.1.0 release? Link from 15.1.0 shows only changes and info about how to install with error as in npm no prefix v in version

**Comment by MarshallOfSound** [comment]
> How can I understand, that something releasing under 15-x-y is 15.1.0 release?

Click it? It shows you the version it is releasing. E.g.

![image](https://user-images.githubusercontent.com/6634592/135658182-e5ea27c7-af50-4819-8e32-741defd11c18.png)

> Supported already contains version 15.1.0 ... Link from 15.1.0 shows only changes and info about how to install with error as in npm no prefix v in version.

That version should not have been listed under "Supported" yet, unclear why that happened.  That said as soon as clicking it shows npm install instructions it _should_ work.  E.g. as of right now

![image](https://user-images.githubusercontent.com/6634592/135658358-2734fa95-662e-4072-85b5-e899896af7d7.png)

> Also in another thread stated that release will be available in 3 hours, but after 12 hours it still be unreleased

The other thread quite clearly said "if nothing goes wrong", most of the Electron maintainers operate off of PST or EST, we dealt with the issue first thing this morning.

**Comment by Delagen** [comment]
Are you really sure that I cannot click it?
![image](https://user-images.githubusercontent.com/783335/135660476-11e874e6-4a93-44fa-95d3-ce2468c8e659.png)
