### ISSUE TITLE
[Bug]: ZWJ Emoji broken in Electron 15.1.0 Arch Linux

### ISSUE THREAD

**Issue by Clansty** [electron/electron#31251]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux 5.14.8-zen1-1-zen

### What arch are you using?

x64

### Last Known Working Electron version

15.0.0

### Expected Behavior

eg. paste the [Transgender Flag Emoji](https://emojipedia.org/transgender-flag/) anywhere, like in the console.

It should display as a single emoji.

It works properly in Electron 15.0.0 and Chrome.

![It works properly in Electron 15.0.0](https://user-images.githubusercontent.com/18461360/135713219-89b99661-5dc6-4a74-82e0-8012c6b4c46a.png)

### Actual Behavior

It display as two emojis in v15.1.0

![example](https://user-images.githubusercontent.com/18461360/135713237-bbc29952-0ecf-4d5a-a683-7877f583fc05.png)

**Comment by CoelacanthusHex** [comment]
Same issue here. Electron 15.1.0, Arch Linux, Linux 5.14.5-zen2-1-zen

**Comment by Clansty** [comment]
bump

**Comment by dobkun** [comment]
shilled award
