### ISSUE TITLE
Why not fix  #30340  bug?

### ISSUE THREAD

**Issue by wwwfkszcom** [electron/electron#31261]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

 webContents.print when silent is true deviceName is not effective 
It's been months and it's still unresolved

### Proposed Solution

  Hope to fix as soon as possible

### Alternatives Considered

  Hope to fix as soon as possible!

**Comment by MarshallOfSound** [comment]
Raising issues asking about other issues is inappropriate, please refrain from doing so
