### ISSUE TITLE
Additional Palm Sign ($) throwing error during installation of electron

### ISSUE THREAD

**Issue by ahmadfaizan965** [electron/electron#31263]
I used the **COPY BUTTON** in code section to copy the installation command, it copied ``` $ npm install --save-dev electron ```

since the terminal already have the palm sign ($) so it would be better it the copied text excludes the sign.

thank you.

![electron issue](https://user-images.githubusercontent.com/69793423/135753931-bf5332ae-a09f-484e-8ecc-b343d726a98b.png)

**Comment by codebytere** [comment]
@ahmadfaizan965 please feel free to open this on the electron website repo - this is not the right place for this issue.

**Comment by ahmadfaizan965** [comment]
@codebytere okay, thanks.

**Comment by codebytere** [comment]
@ahmadfaizan965: https://github.com/electron/electronjs.org-new
