### ISSUE TITLE
[Bug]: "GPU process exited unexpectedly: exit_code=34" error in electron.js on scrolling paginated page on Windows 10

### ISSUE THREAD

**Issue by alokmahor** [electron/electron#31319]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

never worked on preview version also

### Expected Behavior

App should not become full white or full black on scrolling a page when items are getting loaded via REST api call in pagination.

### Actual Behavior

Application become full black or full white when I scroll down when more items loads via REST API call in paginated page on Windows 10. Application is working fine on MacOS.

exact error is 
```
[11668:1006/200834.224:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=34
[11668:1006/200834.225:ERROR:command_buffer_proxy_impl.cc(328)] GPU state invalid after WaitForGetOffsetInRange.
```

**Comment by Thetiso** [comment]
the same

**Comment by Blizzard-liu** [comment]
> ### Preflight Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.
> 
> ### Electron Version
> 15.1.1
> 
> ### What operating system are you using?
> Windows
> 
> ### Operating System Version
> Windows 10
> 
> ### What arch are you using?
> x64
> 
> ### Last Known Working Electron version
> never worked on preview version also
> 
> ### Expected Behavior
> App should not become full white or full black on scrolling a page when items are getting loaded via REST api call in pagination.
> 
> ### Actual Behavior
> Application become full black or full white when I scroll down when more items loads via REST API call in paginated page on Windows 10. Application is working fine on MacOS.
> 
> exact error is
> 
> ```
> [11668:1006/200834.224:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=34
> [11668:1006/200834.225:ERROR:command_buffer_proxy_impl.cc(328)] GPU state invalid after WaitForGetOffsetInRange.
> ```
> 
> ### Testcase Gist URL
> _No response_
> 
> ### Additional Information
> _No response_

你好 请问解决了吗

**Comment by Blizzard-liu** [comment]
> same to

你好 请问解决了吗

**Comment by Blizzard-liu** [comment]
> the same

你好 请问解决了吗
