### ISSUE TITLE
[Bug]: preload script not executed in about:blank iframes

### ISSUE THREAD

**Issue by jirisliva-nw** [electron/electron#31313]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.6.1

### What operating system are you using?

macOS

### Operating System Version

macOS 11.2.3 (20D91)

### What arch are you using?

x64

### Expected Behavior

When create BrowserWindow or Webview with option `nodeintegrationinsubframes` then execute specified preload in every iframe. 

```
const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      nodeIntegrationInSubFrames: true,
      preload: path.join(__dirname, 'preload.js')
    }
  })
```

Webview
https://www.electronjs.org/docs/latest/api/webview-tag/#nodeintegrationinsubframes

BrowserWindow
https://www.electronjs.org/docs/latest/api/browser-window/#new-browserwindowoptions

### Actual Behavior

Specified preload script is executed in all iframe except __"about:blank"__ iframes.
(iframe without defined `src` attribute).

Other options like `nodeIntegration`, `contextIsolation` has no impact to this.

### Testcase Gist URL

https://gist.github.com/jirisliva-nw/4e58430964de0370ea4cfd9189184194

### Additional Information

As I know from Chrome Web Extensions that offers content-scripts to be executed in every iframe.
```
"content_scripts": [
  {
    "matches": [
      "*://*/*"
    ],
    "all_frames": true,
    "match_about_blank": true,
    ..
  }
]
```
But to execute content-script also in "about:blank" iframes there is extra option `"match_about_blank": true`.

Could be this somehow connected to behavior of preload scripts in Electron (since it seems to be same kind of isolation).

**Comment by gdavidkov** [comment]
I think that this issue is caused also by this PR
[fix: illegal access errors with nodeIntegrationInSubFrames](https://github.com/electron/electron/pull/29169) causes the incorrect behavours.

**Comment by Kallenju** [comment]
Happening in Electron 21.0.0.

**Comment by miniak** [comment]
> Happening in Electron 21.0.0.
This is not a supported version

**Comment by Kallenju** [comment]
@miniak 
Happening in Electron 22. It is a supported version.
