### ISSUE TITLE
[Bug]: 32 Bit Version : Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by kurtisane** [electron/electron#31316]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 

### What arch are you using?

ia32

### Last Known Working Electron version

11.0.3

### Expected Behavior

No loading Errors and regular use of the application

### Actual Behavior

We are running into issues with our 32Bit Version. The exact same stuff with 64 Bit works without any issues.

The errors that we see are the following: 
![errors-console](https://user-images.githubusercontent.com/22451592/136202285-f61ba542-70b2-4ca7-a9f6-5ef951b1a36e.png)

This happens right after the application is launched.
We are outputing a "tracelog" : 
[tracelog.txt](https://github.com/electron/electron/files/7293708/tracelog.txt)

![events](https://user-images.githubusercontent.com/22451592/136202742-73ff5c23-7dab-4299-b896-1bf861cf4a59.png)

Due to the error that we encounter the tracelog stops earlier than the 64 Bit version.

We are using the asar packaging and our 32 Bit Version is not able to start properly. We have tested all of this without the asar packaging and it works. 

Currently we are really confused since actually nothing changed in our code and we did not update anything.

Any advice what the issue could be or how we could gather more information ?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
