### ISSUE TITLE
[Bug]: ipcRenderer.sendSync without a return value never returns and locks up the renderer

### ISSUE THREAD

**Issue by andycreeth** [electron/electron#31321]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19042 Build 19042

### What arch are you using?

x64

### Last Known Working Electron version

Unknown - issue is present on electron 12 (lowest currently supported version)

### Expected Behavior

Using `ipcRenderer.sendSync` to invoke a main process handler without a return value should return `undefined` or produce an error.

### Actual Behavior

Using `ipcRenderer.sendSync` to invoke a main process handler without a return value takes an extremely long time or never returns.

### Testcase Gist URL

https://gist.github.com/4ed82ddea62d2ff21996c8db94a66a25

### Additional Information

About the minimal test case provided:
- The setTimeout to delay the IPC call by 10 seconds seems necessary to induce a complete lockup that never returns.  If you remote the timeout and instead make the IPC call right away, it will return after about 6.5 seconds (instead of the <1ms it takes when you provide a return value).
- There is a text input in the renderer.  You can type into this box to verify that the renderer is responsive before the IPC request fires.  Once the IPC request fires, you will no longer be able to type into the box as the renderer becomes unresponsive (thread is blocked by never returning ipc call).
- If you provide a return value in the handler (null for example) it will resolve this issue and the function will return in <1ms (just uncomment the line in the main process to try).

Using `sendSync` without a return value is a bit of an edge case, but can be useful when a sync request is important for ensuring order of operations, and the return value isn't needed.

There are 2 obvious workarounds to this issue:
- Set a return value, i.e. `e.returnValue = null`
- Use `invoke`/`handle` to ensure order of operations using async IPC

**Comment by miniak** [comment]
This is not a bug, it's a feature. The `e.returnValue` can be assigned asynchronously like this:
```
ipcMain.on('test', e => {
  setTimeout(() => {
    e.returnValue = 'Hello World!';
  }, 1000);
});
'''

**Comment by andycreeth** [comment]
Yeah it seems like a warning/exception when the handler is missing entirely might make it easier for people to spot if they have a typo in the channel name or something.

Thinking about it and I'm not sure there is anything additional that can be done for my case specifically - these are the pitfalls of synchronous interprocess communication (especially in a single threaded environment like JS), and the docs do make it pretty clear that asynchronous communication should be preferred whenever possible (which is good).

In my case I had moved from calling something with `send` to `sendSync` as part of resolving a race condition, and it wasn't immediately clear to me why a handler that worked fine asynchronously couldn't also be called synchronously.  Anyway, I do appreciate you looking into this and thinking about potential solutions.

**Comment by andycreeth** [comment]
@miniak Great - I'm positive this will help other devs avoid confusion in the future.  Thank you for the PR 🙏

**Comment by nornagon** [comment]
We could also trap the GC of the event and return the IPC with an exception, which would hang the renderer for a while but not indefinitely?
