### ISSUE TITLE
[Bug]: shell.openExternal can't open a windows directory which contains chinese charactors

### ISSUE THREAD

**Issue by hayword-wang** [electron/electron#31347]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 1803 Version 2019.05.28

### What arch are you using?

x64

### Last Known Working Electron version

15.1.0

### Expected Behavior

shell.openExternal open the directory 'D:/测试'

### Actual Behavior

shell.openExternal('D:/测试')
Uncaught (in promise) Error: Failed to open

**Comment by terry2010** [comment]
maybe it's your encoding error?  your js file is UTF-8 encoding , chinese windows system is ANSI,   you could chang your file name to gbk to fix this problem

`
var iconv = require("iconv-lite");
var str='D:/测试';
var rawStr = iconv.encode(str, 'gbk').toString('binary');
shell.openExternal(rawStr )
`

**Comment by xxxace** [comment]
> 

hi! i do the same things as your reply but it don't works

rawStr is D:/²âÊÔ

![image](https://user-images.githubusercontent.com/60084325/188593953-418d843b-fdfd-409b-abf4-f509392d985a.png)

`
let rawStr = iconv.encode('D:/测试', 'gbk').toString('binary');
console.log(rawStr)
shell.openExternal(rawStr)
`

**Comment by terry2010** [comment]
> > 
> 
> hi! i do the same things as your reply but it don't works
> 
> rawStr is D:/²âÊÔ
> 
> ![image](https://user-images.githubusercontent.com/60084325/188593953-418d843b-fdfd-409b-abf4-f509392d985a.png)
> 
> ```
> let rawStr = iconv.encode('D:/测试', 'gbk').toString('binary');
> console.log(rawStr)
> shell.openExternal(rawStr)
> ```
> 
> electron version: 20.0.2

there is many character encodings could show chinese charact, eg. gbk , big5 &etc   ， some psychos even use windows-31J

so.maybe you should try more encoding

**Comment by wh201906** [comment]
bump

**Comment by wh201906** [comment]
bump

**Comment by wh201906** [comment]
bump

**Comment by wh201906** [comment]
bump

**Comment by wh201906** [comment]
bump
