### ISSUE TITLE
[Bug]: electron show white screen, did-finish-load never fired, neither did other events [Windows]

### ISSUE THREAD

**Issue by belloyang** [electron/electron#31343]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

8.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 OS build: 19043.1237

### What arch are you using?

x64

### Last Known Working Electron version

4.0.0

### Expected Behavior

The app should render properly and DevTool should be able to locate the entry file `angular-main.ts`

### Actual Behavior

The electron app shows a white screen. none of the events are being triggered, including `did-finish-load`, `did-fail-load`, `did-navigate`, etc.
Strangely, in a normal situation, I'm always able to find the entry file such as `angular-main.ts`, and all the other ts files. In the case when the app shows a white screen, I can't find any ts files from DevTools. and index.html appears to be blank.

### Additional Information

I'm not sure if this is the right place to post this issue. 
I've been stuck with this issue for many days, If any of you could possibly shed some light for me on this issue, I would highly appreciate it!
The same code base can render and run properly on macOS and Linux system, but it just won't render on windows for some reason.
If I removed all the components and keep only a simple angular component, it can render correctly.
My project is set up to use electron-forge for building and packaging. 
The app is started by `electron-forge start` command. 

my entry file electron-main.ts:
```
import { app, BrowserWindow } from 'electron';
import { enableLiveReload } from 'electron-compile';


let mainWindow: Electron.BrowserWindow | null;

const isDevMode = process.execPath.match(/[\\/]electron/);

if (isDevMode) enableLiveReload();

const createWindow = async () => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    }
  });

  // and load the index.html of the app.
  mainWindow.loadURL(`file://${__dirname}/index.html`);

  // Open the DevTools.
  if (isDevMode) {
    mainWindow.webContents.openDevTools();
  }

  mainWindow.webContents.on('did-fail-load', () => {
    console.log('did-finish-load');
  });
  mainWindow.webContents.on('did-start-navigation', () => {
    console.log('did-start-navigation');
  });
  // Emitted when the window is closed.
  mainWindow.on('closed', () => {
  
    mainWindow = null;
  });
};

app.on('ready', createWindow);

// Quit when all windows are closed.
app.on('window-all-closed', () => {
  
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
 
  if (mainWindow === null) {
    createWindow();
  }
});


```

index.html: 

```
<!DOCTYPE html>
<html lang="en" style=" min-height: 100% !important;height: 100%;">
  <head>
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' https://fonts.gstatic.com;">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link  ref="stylesheet" type="text/css" href="./styles.css" title="Default Styles" media="screen">
   
  </head>
  <body style="margin: 0; " >
    <App/>
  </body>
  <script>window.exports = module.exports</script>
  <script src="../node_modules/reflect-metadata/Reflect.js"></script>
  <script src="angular-main.ts"></script>
</html>
```

**Comment by belloyang** [comment]
I found this is related to the usage of native module in my code.
```
export const myNativeModule = require('./build/Release/my_native_module.node');
```
if I commented out this line, the Electron app would be able to render properly, otherwise, it doesn't render anything but showing a white screen. and there is no any source file can be located from DevTool.
This seems very strange. Could anyone please explain what's happening here or share some thought? why exporting a native module from a library can cause electron app to be blank, even if this native module is not being imported at all...

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you're still experiencing this issue in Electron 13.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
