### ISSUE TITLE
[Bug]: getAppPath() returns C:\Windows\System32 in production

### ISSUE THREAD

**Issue by omermutlu29** [electron/electron#31341]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Hello everyone,

I have a project which is developed electron and react. I used auto-launch to open app when system startup. Also I have config.json file and I use it in root component in React side. 

The question is that: 
I am trying to find auth.json in my component in Root component. 
When I start application manually, getAppPath function returns correct path. For example : C:\Users\...\..\auth.json ->it is OK for me. 
But when system startup and program run by system same function returns c:\Windows\System32\auth.json. In addition I am getting error about write permission in this case. 

So anyone can help me about this situation? 
What is the best way the get correct app name? 

Thank you.

### Actual Behavior

When system startup I want to get auth.json path like this : C:\Users\Userasd\Local\AppData\Programs\etc..\auth.json

![ss](https://user-images.githubusercontent.com/21954959/136412169-e10ae0f8-6b77-451d-af3a-5ad5937a8aa7.png)

![tempsnip](https://user-images.githubusercontent.com/21954959/136413371-4c279784-192b-47d4-b4ad-c2f99f12e797.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you're still experiencing this issue in Electron 13.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.
