### ISSUE TITLE
[Bug]: moveToApplicationsFolder does not use the conflict handler function

### ISSUE THREAD

**Issue by gilles-yvetot** [electron/electron#31353]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.1

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.6

### What arch are you using?

x64

### Expected Behavior

Check out the repro repo I attached. Build the app.

`app.moveToApplicationsFolder` only executes its default behavior

### Actual Behavior

`app.moveToApplicationsFolder` should take into consideration the conflict handler

### Testcase Gist URL

https://github.com/gilles-yvetot/electron-bug-repro

**Comment by codebytere** [comment]
It _does_ take the conflict handler into account - if the application is running but not present in the destination folder it will still move it.
