### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by hcarsten** [electron/electron#31379]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

We a creator of parental control systems currently we are using various technologies to prevent access to none age appropriate content.
We are evaluating various technologies to create a custom browser. The main issue here is to pre-filter any URLs before they are downloaded. The filter engine is accessible via an API but has to be called before the final HTTP call is made. Additionally or alternatively the final content rendering needs to be postponed till the API result can be used to allow / deny the data.
As of the single threaded nature of JavaScript we already had the same problem within browser extensions we built.

So the main question is if Electron might be eligible or appropriate to create a "filtering" custom browser ?

best

Carsten  

### Proposed Solution

have a way to prefilter URLs before they are touching the network

### Alternatives Considered

important a have blocking API

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
