### ISSUE TITLE
[Bug]: Electron segfaults when saving a PDF with forms after editing any fields

### ISSUE THREAD

**Issue by sigaloid** [electron/electron#31373]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

"electron": "^15.1.1"

### What operating system are you using?

Other Linux

### Operating System Version

5.10.70-1-MANJARO

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

PDF should save correctly (or at least, not offer to save with edits; wonder if the chromium PDF editor can be configured to not offer that button, if for some reason saving cannot be done)

### Actual Behavior

Process segfaults when I try to save "with [my] changes". (Not when trying to save without changes, though)

### Additional Information

https://github.com/sigaloid/electron-pdf-crash

https://user-images.githubusercontent.com/69441971/136713869-ca4b9355-46fb-4444-b23d-6b824b99bdea.mp4

Shows how saving "without [my] changes" does nothing but saving "with [my] changes" segmentation fault's.

index.html is pretty minimal to reproduce. Just a single iframe with a src pointing to a PDF that has forms.

https://github.com/sigaloid/electron-pdf-crash/blob/main/index.html

A solution would be to configure Chromium to not allow saving edited forms, if this isn't supported. Just some way of hiding the button, I suppose.

Additional info and debugging in this issue (thanks @abitofevrything) https://github.com/zadam/trilium/issues/2205

PS: You can replicate this by [cloning this](https://github.com/sigaloid/electron-pdf-crash) and trying it yourself, or I can run it with some sort of debugging enabled to get any logs necessary.

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/32512
