### ISSUE TITLE
[Feature Request]: Added support to show the Window SNAP box on windows 11 for frameless windows

### ISSUE THREAD

**Issue by XFaonAE** [electron/electron#31372]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I would like to trigger to Windows 11 window snap system on my framework

**My FrameWork**
![My FrameWork's Title Bar](https://i.imgur.com/tvvtvGp.png)

**Native Windows 11 TitleBar**
![Native TB](https://i.imgur.com/NvOkh6k.png)

You may notice mica is working on my electron framework, it is electron but I just simulated mica just incase someone though the images were mistaken

### Proposed Solution

I would like an API function that can call the window snap flyout on command in a specific location
Here is an API concept

```ts
// THIS IS TYPESCRIPT

// ... App on ready code

const window = new BrowserWindow({});

window.loadURL("AxeriFramework UI Loader source");

ipcMain.on("callSnap", (event, msg: any) => {
    window.displaySnap(x, y, ...location of restore button so that it knows when to hide snap if the button is not hovered);
});

// ...
```

### Alternatives Considered

I have found no results or solutions

### Additional Information

Latest version of Electron

**Comment by aleksey-hoffman** [comment]
I would love to have this API for my Electron app as well. 
The "window controls" API is not flexible enough to replace a custom title bar.

### API functions
```js
electron.app.showWindowsControlsSnapLayoutsOverlay({x, y})
electron.app.hideWindowsControlsSnapLayoutsOverlay()
```

**Comment by XFaonAE** [comment]
Sadly we cant open issues to the WINAPI

**Comment by XFaonAE** [comment]
> https://www.electronjs.org/docs/api/frameless-window#windows-control-overlay

There are many issue such at the fact that hovering the buttons has no effect, the colors do not change

**Comment by XFaonAE** [comment]
Alright, guys i found something, in the electron hit test, the developers need to send a LRESULT of 9, and bam, you can cause the win snap layout
