### ISSUE TITLE
[Feature Request]: Backport upstream cursor fix on ozone/wayland (Electron 13)

### ISSUE THREAD

**Issue by cynecx** [electron/electron#31371]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron 13 is based on Chromium 91 therefore has an issue affecting text-selection and the cursor on wayland.

See https://bugs.chromium.org/p/chromium/issues/detail?id=1202986.

A fix was included in Chromium >=92 (https://chromium.googlesource.com/chromium/src/+/6212b4b9b4cec7ce1c7110b88120d4e82dc1172f).

This is more or less affecting VSCode since it's on Electron 13.5.1.

### Proposed Solution

It would be great if this [patch](https://chromium.googlesource.com/chromium/src/+/6212b4b9b4cec7ce1c7110b88120d4e82dc1172f) could be backported.

### Alternatives Considered

Do nothing.

**Comment by RaisinTen** [comment]
Hi! Electron v13 is not supported anymore. Currently, the only supported versions are v17, v18 and v19. All of these use a version of Chromium > M92, so we can safely say that the supported versions contain the patch you are asking for, so I'll close the issue.
