### ISSUE TITLE
Remove usage of USE_X11

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#31382]
With https://github.com/electron/electron/pull/30814 [ozone](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/ozone_overview.md) platform is the default on linux.

- [x] Replace `GlobalShortcutListenerX11` with `GlobalShortcutListenerOzone`
- [ ] Refactor `electron::GlobalMenuBarX11` https://chromium-review.googlesource.com/c/chromium/src/+/2317185
- [ ] Isolate `electron::EventDisabler` for `OZONE_X11`
- [ ] Replace `electron::WindowStateWatcher` via hook from `DesktopWindowTreeHostPlatform::OnWindowStateChanged`
- [x] Add ozone platform initialization hooks [1](https://chromium-review.googlesource.com/c/chromium/src/+/3186490/4/chrome/browser/chrome_browser_main_extra_parts_ozone.cc), [2](https://chromium-review.googlesource.com/c/chromium/src/+/3186490/4/chrome/browser/ui/views/chrome_browser_main_extra_parts_views_linux.cc)

/cc @electron/wg-upgrades

**Comment by wallentx** [comment]
Just a passerby question: wouldn't this force wayland as a dependency for all electron apps on Linux?

**Comment by jkleinsc** [comment]
@wallentx Ozone supports both X11 and Wayland:
As noted [here](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/ozone_overview.md#linux-desktop-x11-waterfall):
>Chrome/Linux uses X11 Ozone backend by default

**Comment by codebytere** [comment]
Chromium removed the `USE_X11` define in https://chromium-review.googlesource.com/c/chromium/src/+/3290415, which I temporarily reverted in the latest roll: https://github.com/electron/electron/pull/31986

**Comment by deepak1556** [comment]
We can define `USE_X11` in https://github.com/electron/electron/blob/4609d4cb7add2a1f1d721c831c6837e6ba77ce63/BUILD.gn#L549 until the refactor is complete instead of reverting the upstream commit.

```
 defines += [ "USE_X11=1" ]
```

**Comment by primeos** [comment]
Apparently Electron's legacy `USE_X11` usages are currently breaking Ozone/Wayland: https://github.com/electron/electron/issues/32436#issuecomment-1032338114 (just as an FYI to document/track it here as well).

May I ask if this issue is still progressing / how best to proceed with this?
@ckerr you've self-assigned #32436. Are you already working on it or are there other Electron contributors that we could/should ping for help?

**Comment by ckerr** [comment]
Fixed by https://github.com/electron/electron/pull/33355
