### ISSUE TITLE
[Bug]: Crash when create child window visible on all workspace

### ISSUE THREAD

**Issue by Godwin-sys-php** [electron/electron#31383]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15

### What arch are you using?

x64

### Last Known Working Electron version

14.0.0

### Expected Behavior

I want to have a window without frame that appear on all workspace when a notification arrived, a notification window that can be bigger than a native notification. The notification landing is listened by socket.io in the render process that sends an ipc event to the main process with this createWindow function:
```
function createWindow () {
  // Create the browser window.
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule:true,
      webSecurity: false,
    },
  })

  //load the index.html from a url
  win.loadFile("build/index.html");

  ipcMain.on('notification', (event, arg) => {
    const notificationWindow = new BrowserWindow({
      width: 800,
      height: 400,
      frame: false,
      webPreferences: {
        nodeIntegration: true,
        contextIsolation: false,
        enableRemoteModule:true,
        webSecurity: false,
      },
    })
  
    notificationWindow.loadFile('public/notification.html')
    notificationWindow.setVisibleOnAllWorkspaces(true, {visibleOnFullScreen: true});
    notificationWindow.setFullScreenable(false);
  })
}
```

### Actual Behavior

When I create the window, the app crash, and freeze.
The main window loses his frame and freeze. The notification window appears on all workspace but the web content freeze (button are disabled and text is not selectable)

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
