### ISSUE TITLE
[Bug]: { resizable: false, maximizable: true } window is not maximizable

### ISSUE THREAD

**Issue by ArthurLobopro** [electron/electron#31384]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I created a BrowserWindow with these options { resizable: false, maximizable: true } and expected a no resizable and maximizable window

### Actual Behavior

The window is not maximizable

### Testcase Gist URL

https://gist.github.com/f8bceadb39efdae142bf08ff6ef8e4ba

**Comment by XFaonAE** [comment]
You cannot maximize the windows when resize is disabled because maximizing is considered as a resize action

**Comment by zcoding** [comment]
still not working

**Comment by ArthurLobopro** [comment]
Still not working when I add `{ resizable: false, maximizable: true }` in the BrowserWindow constructor. I tested in version `22.0.1` (currently latest). But adding `win.setMaximizable(true)` after instance the BrowserWindow it works correctly.
