### ISSUE TITLE
Dock relaunch app method

### ISSUE THREAD

**Issue by mqliutie** [electron/electron#31391]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

We have a old app,  which name is `Old` and icon is `old icon`.

Now we develop new app using electron.

Old app upgrade to the new app. After upgrading need quid and restart. 

The app icon and appName on the dock are **still old** unless I click dock icon to start the App the name and icon will be changed to the newest.

So in my code I want to start the app by click dock icon. I tried to write some `applescripts` code, but this code need some system permissions. If user don't allow I can not start the app by `applescripts`.

It will be very nice If electron can support this method.

### Proposed Solution

I am frontend developer, I don't know how to do.

### Alternatives Considered

 I tried to write some `applescripts` code, but this code need some system permissions.

**Comment by MarshallOfSound** [comment]
This can (and should) be implemented outside of Electron core (as you noted via an applescript implementation)
