### ISSUE TITLE
[Bug]: If the iframe is added dynamically, the preload script isn't been called

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#31395]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.5.2

### What operating system are you using?

Windows

### Operating System Version

Window 10 10.0.19043.1266

### What arch are you using?

x64

### Last Known Working Electron version

12.0.7

### Expected Behavior

The preload script should be called on every iframe if the nodeIntegrationInSubFrames is set to true.

### Actual Behavior

The preload script is called only if the iframe is available at the DOM.

### Testcase Gist URL

https://gist.github.com/e066bd4edbfec848ae6bfaa5985efe68

### Additional Information

I've tested all versions and this bug emerge in version 12.0.8. I think the following PR
[fix: illegal access errors with nodeIntegrationInSubFrames](https://github.com/electron/electron/pull/29169) causes the incorrect behavours.

**Comment by gdavidkov** [comment]
@codebytere Hi, any update on this?

**Comment by codebytere** [comment]
@gdavidkov yes - the reason behind this is outlined in the original PR and the need for which remains. The issue is not that you added the ifram dynamically - it's that the src needs to be set _to something other than about:blank_ in order for the preload script to run. To achieve your goal, you could instead modify your existing Fiddle:

```js
// renderer.js
setTimeout(() => {
  var iframe = document.createElement('iframe');
  document.body.appendChild(iframe);
  iframe.src = "./page2.html"
}, 5000)
```
```html
<!-- page2.html -->
<body>Foo</body>
```
