### ISSUE TITLE
[Bug]: Css animation freeze 

### ISSUE THREAD

**Issue by welcome14** [electron/electron#31399]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.2

### What operating system are you using?

Windows

### Operating System Version

windows 7, windows 10

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

I report the [`link`](https://github.com/electron/electron/issues/9719) of a previous unresolved bug, I find myself having to scroll an element like "marquee" with a transalteX type animation, but randomly freezes occur and the animation is blocked for a few ms.

I tried the same animation with a simple html page using chrome and it all turns out very smooth.

Thinking the problem was some call via IpcMain / Render, I tried to disable everything but didn't fix the situation.

Has anyone found the solution to this problem?

### Actual Behavior

css animation freeze

**Comment by troncoso** [comment]
I believe I'm running into this issue as well. I throw up a loading overlay while waiting on an Ipc call to return from main, and I find that the spinning animation is very choppy. I replaced the Ipc call with a simple timeout and the animation was smooth. To hopefully add some new information to this issue, I am seeing this on macOS Big Sur
