### ISSUE TITLE
[Bug]: PDF download button doesn't work

### ISSUE THREAD

**Issue by quanglam2807** [electron/electron#31396]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.2 | 15.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 11.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

14.1.1

### Expected Behavior

Clicking on PDF download button triggers save dialog.

### Actual Behavior

PDF download button doesn't work

### Testcase Gist URL

https://gist.github.com/7fc5a276a83dfff6a36d9a9bbb86d7b4

### Additional Information

This used to be fixed with https://github.com/electron/electron/pull/24946.

Tested with 14.1.1, 15.0.0 & 15.1.2. It seems like it's broken starting with v15.

**Comment by codebytere** [comment]
Hmm - it's working in v16 so i'm not quite sure what's up but i'll look.

**Comment by Brouilles** [comment]
Same problem here.

**Comment by thenightex** [comment]
Any updates on this or is updating to 16+ the only option? Doesn't work on any platform on v15.5.0

**Comment by codebytere** [comment]
Updating to 16+ is the only option at this point, sadly.
