### ISSUE TITLE
[Bug]: Uncaught illegal access when nodeIntegrationInSubFrames is true and iframes nested

### ISSUE THREAD

**Issue by WindTraveler** [electron/electron#31394]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.2.2

### What operating system are you using?

macOS

### Operating System Version

10.15.3

### What arch are you using?

x64

### Last Known Working Electron version

8.5.5 

### Expected Behavior

No `Uncaught illegal access` error in console and the html page is rendered normally

### Actual Behavior

This issue is very similar to https://github.com/electron/electron/issues/27457.

The differernt thing is that my html page has one ifarme element which has many sub iframes inside.
![image](https://user-images.githubusercontent.com/13325131/136934749-aca69bbd-b3df-4160-9842-401b106f92e9.png)

When I try to remove some sub iframes such as sub iframe3 by using redux dispatch function, the error `Uncaught illegal access` occurs :

![image](https://user-images.githubusercontent.com/13325131/136935896-e967357a-5329-4af7-8cef-6f2487524a79.png)

And the outside iframe gets empty:
![image](https://user-images.githubusercontent.com/13325131/136935665-1b561430-98be-4362-9db0-000d958215dd.png)

This is my browser window options:
```
const mainWindow = new BrowserWindow({
    width: 376,
    height: 667,
    webPreferences: {
      nodeIntegration: true,
      nodeIntegrationInSubFrames: true,
      contextIsolation: false,
      enableRemoteModule: true,
    }
  });
```

What a pity I can not reproduce the issue in a simple demo.
Thanks in advance @codebytere.

**Comment by gpetrov** [comment]
@WindTraveler is this maybe solved in later updates? Maybe with: https://github.com/electron/electron/pull/29093
Can you confirm?

**Comment by codebytere** [comment]
This should have been solved in https://github.com/electron/electron/pull/29093
