### ISSUE TITLE
[Bug]: Notifications API, when notification hides before being clicked, and the clicked when in sidebar, electron notification click event does not fire anymore

### ISSUE THREAD

**Issue by XFaonNX** [electron/electron#31390]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.2

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

When notification isn't clicked until it gets sent to the sidebar, and then clicked again, the notification click even should stay active.

### Actual Behavior

Click even does not fire when in sidebar

**Comment by VerteDinde** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by DinerIsmail** [comment]
@VerteDinde I don't think there's a need for a gist on this, the actual Notification example in Electron Fiddle shows the same behaviour described above on Windows 10/11.
