### ISSUE TITLE
[Bug]: WebviewTag interface not exported 

### ISSUE THREAD

**Issue by praneetrohida** [electron/electron#31405]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.2

### What operating system are you using?

macOS

### Operating System Version

Big Sur

### What arch are you using?

x64

### Last Known Working Electron version

11.1.2

### Expected Behavior

electron used to export an interface called 'WebviewTag'. It was useful for typing the webview instance refs.

### Actual Behavior

The interface is not exported anymore.

**Comment by praneetrohida** [comment]
I was having trouble accessing the namespace, but I think that's just a problem with my webpack setup.

**Comment by Y2zz** [comment]
> I was having trouble accessing the namespace, but I think that's just a problem with my webpack setup.

It seems to have nothing to do with webpack configuration

**Comment by pietrovismara** [comment]
@Y2zz any luck solving the issue?

**Comment by Sharcoux** [comment]
The module "electron" has no exported module Electron nor WebviewTag. How did you do that?
