### ISSUE TITLE
[Bug]:webgl render video chromium-89.0.4389.128 waitable_event_win.cc WaitableEvent::TimedWait(const TimeDelta& wait_delta) no return

### ISSUE THREAD

**Issue by 1515guo** [electron/electron#31403]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.16

### What operating system are you using?

Windows

### Operating System Version

win10 19042.985

### What arch are you using?

x64

### Expected Behavior

No problem ，Non-blocking

### Actual Behavior

The main thread is blocked in chromium-89.0.4389.128  waitable_event_win.cc WaitableEvent::TimedWait(const TimeDelta& wait_delta) no return
![Snipaste_2021-10-12_19-17-59](https://user-images.githubusercontent.com/42996533/137050743-802798cd-734b-432d-a543-49bd7181f3a2.png)
![Snipaste_2021-10-12_19-15-55](https://user-images.githubusercontent.com/42996533/137050745-e8b5c257-cd44-4baa-ac14-17ffb7a3b08a.png)
![Snipaste_2021-10-12_19-18-18](https://user-images.githubusercontent.com/42996533/137050748-835220ac-90ef-4b40-8aa9-dfe7b81c63ee.png)

**Comment by clavin** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone test case with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a reply.

Thanks in advance! Your help is appreciated.
