### ISSUE TITLE
[Bug]: Message box is not immediately usable after `app.whenReady()`, returns junk until next tick.

### ISSUE THREAD

**Issue by mathieulj** [electron/electron#31402]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

`>= 14.0.0-beta.1`

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6

### What arch are you using?

x64

### Last Known Working Electron version

13.5.2

### Expected Behavior

- A message box is visible
- the promise is resolved only when a button is clicked
- the response contains the button index
- there is a log in the console `You must have clicked a button, and we actually waited for it...`

### Actual Behavior

- A message box comes up but is not visible long enough for anything to happen (you can see it if you step through the code while debugging)
- the promise is immediately resolved (doesn't wait for a button click).
- the response contains -1000 as a button index
- there is a log in the console `Dialog is borked...`

### Testcase Gist URL

https://gist.github.com/mathieulj/57a99af7f4d6bba2df74ab2479a6d96f

### Additional Information

In the actual app I found this issue, we have a native module using Neon. After this bug is hit, our `EventQueue` no longer works (fails to send silently) which leads me to believe some internal V8 state other than the alert might be affected.

**Comment by mathieulj** [comment]
I built from source to confirm. This indeed showed up with the chromuim dep bump commit. Something else interesting I noticed while testing some more; it seems the event loop is blocked or deadlocked after this bug has occured. Adding a `console.log` in a `setInterval(..., 5);` outputs more than once before `app.whenReady` but then doesn't log again after `app.whenReady` yet the app does not quit when we `app.quit` and no `setTimeout` callbacks execute after we hit the bug (even if set after the bug is hit).

**Comment by ckerr** [comment]
I was sure this was due to the microtask changes in that Chromium roll that @clavin mentioned, but now am even more confused because this WFM with any Electron version on Linux, (possibly) meaning that it's a macOS-specific change. The only macOS-specific change I see in that commit range is https://github.com/electron/electron/commit/4073599f59023360fbaff0a6e90f34dc26246338 but at first glance it doesn't seem a very likely candidate :confused:

**Comment by mathieulj** [comment]
I can confirm that the symptoms do seem to be a mac specific and that the chromium version bump is when the bug started occurring. The commit before the chromium bump (https://github.com/electron/electron/commit/9cf71d72abf97c7583b200063915aa9c8fb23e15) does not exhibit the bug and the chromium commit does (https://github.com/electron/electron/commit/2eb3bddb05b6efc92e36c22ed55c37021d84276a). Hence the other commits in that range are not the original source at least for me.

**Comment by Vishal1419** [comment]
Today, I tried this and it works perfectly fine with setTimeout:

```
app.whenReady().then(() => {
  setTimeout(() => {
    showMoveToApplicationsDialog(); // this function shows a dialog
  }, 0);
});

```

 So, I guess, we have a temporary solution and may be some hint to fix the issue.
