### ISSUE TITLE
[Bug]: crashReporter doesn't generate crash dumps when running through Rosetta (built for amd64, runs on arm64)

### ISSUE THREAD

**Issue by Xano** [electron/electron#31413]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.6

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.5.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

1. call in main.js: crashReporter.start( { submitURL: '', uploadToServer: false, ignoreSystemCrashHandler: true } );
2. require native module;
3. provoce crash in native module;

Expected: crash dump is generated

### Actual Behavior

crash dump doesn't generated

### Additional Information

problem exists only when electron is launched through Rosetta

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you're still experiencing this issue in Electron 13.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by Xano** [comment]
I checked with electron 13.1.7 just now - same results
