### ISSUE TITLE
[Bug]: BrowserView broken since v13.5.0

### ISSUE THREAD

**Issue by exander77** [electron/electron#31424]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.5.0

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Last Known Working Electron version

13.4.0

### Expected Behavior

```
const win = new BrowserWindow({ width: 800, height: 600 })

const view = new BrowserView()
win.setBrowserView(view)
view.setBounds({ x: 0, y: 0, width: 300, height: 300 })
view.webContents.loadURL('https://electronjs.org')
```
Example from documentation should open BrowserWindow with BrowserView with electronjs.org website.

### Actual Behavior

Everything stays blank.

### Additional Information
https://newbedev.com/electron/api/browser-view

Broken up to current v15.1.2.

Possibly related to: https://github.com/electron/electron/pull/31047

_No response_

**Comment by exander77** [comment]
I am using ElectronJS for around a month and a half, but I can't seem to get the hang of the problems with the project. I can't seem to select the appropriate version as for example silent print to a specific printer does not work in any supported version. And for example this issue. BrowserView is recommended over WebView, yet it does not work consistently, predictively or at all, see: https://www.electronjs.org/docs/latest/tutorial/web-embeds

**Comment by clavin** [comment]
Thanks for the report! I was able to reproduce this on Ubuntu 20.04. Here's a bit more information I dug up:

This seems to have broken between [versions `v14.0.0-nightly.20210413` and `v14.0.0-nightly.20210426`](https://github.com/electron/electron/compare/v14.0.0-nightly.20210413...v14.0.0-nightly.20210426). The PR that broke it was also backported to the `13-x-y` line which broke between [versions `v13.4.0` and `v13.5.0`](https://github.com/electron/electron/compare/v13.4.0...v13.5.0).

I confirmed that https://github.com/electron/electron/pull/31047 did **not** cause this bug.

I actually narrowed it down to https://github.com/electron/electron/pull/30887, which is a backport of https://github.com/electron/electron/pull/29600, which causes this bug.

**Comment by exander77** [comment]
Great work narrowing it to actual PR. Btw, one in 100 attempts or so, the BrowserView actually rendered for me. That's when I started digging that maybe my code is actually ok.

**Comment by SpacingBat3** [comment]
> Great work narrowing it to actual PR. Btw, one in 100 attempts or so, the BrowserView actually rendered for me. That's when I started digging that maybe my code is actually ok.

From my tests, `BrowserView` is unable to set its bounds unless there's some timeout for the window to appear – this is what I believe is why it does work in some cases when `webContents` is ready to add a `BrowserView`. I'm still not certainly sure what exactly could cause this bug, but as the workaround the one could just load the `BrowserView` after some timeout to increase its chance to load properly.

For an example, a patch for the `BrowserView` example code in Electron Fiddle could be like:
```diff
24c24
<   view.setBounds({ x: 0, y: 0, width: 300, height: 300 })
---
>   view.webContents.on("did-finish-load", () => view.setBounds({ x: 0, y: 0, width: 300, height: 300 }))
```
This will make the `view` to set its bounds after the page loads.

**Comment by estepona** [comment]
> > Great work narrowing it to actual PR. Btw, one in 100 attempts or so, the BrowserView actually rendered for me. That's when I started digging that maybe my code is actually ok.
> 
> From my tests, `BrowserView` is unable to set its bounds unless there's some timeout for the window to appear – that could be why it does work in some cases when `BrowserView` is ready to be able to change its bounds. I'm still not certainly sure what exactly could cause this bug, but as the workaround the one could just set the bounds of the `BrowserView` after some timeout to increase its chance to load properly.
> 
> For an example, a patch for the `BrowserView` example code in Electron Fiddle could be like:
> 
> ```diff
> 24c24
> <   view.setBounds({ x: 0, y: 0, width: 300, height: 300 })
> ---
> >   view.webContents.on("did-finish-load", () => view.setBounds({ x: 0, y: 0, width: 300, height: 300 }))
> ```
> 
> This will make the `view` to set its bounds after the page loads.

I can confirm the original issue persists in electron v19.0.10. *electron.org works* fine, but *google.com* wouldn't work. The above answer solves the problem for me.

**Comment by SebastienWae** [comment]
bump!

This issue is still affecting me on Linux, but I can't reproduce it on macos.

**Comment by Hinaser** [comment]
I mitigated this issue by defering page load as follows.
```javascript
const win = new BrowserWindow({ width: 800, height: 600 })

const view = new BrowserView()
win.setBrowserView(view)
view.setBounds({ x: 0, y: 0, width: 300, height: 300 })
// Move 'loadURL' execution to another event loop context.
setTimeout(() => view.webContents.loadURL('https://electronjs.org'), 0);
```

**Comment by akshay-aravind** [comment]
I am getting this issue with the latest electron version.

**Comment by j0hnm4r5** [comment]
I too am still getting this issue in v25.3.2, on Ubuntu 20.04

**Comment by safinaskar** [comment]
Original bug ( https://github.com/electron/electron/issues/31424#issue-1026534933 ) still reproducible with Node 18.13, Electron 26.2, recent Debian Linux sid and with wikipedia.org as test page.

Workaround in https://github.com/electron/electron/issues/31424#issuecomment-978494007 still works
