### ISSUE TITLE
[Bug]: Cookies no longer being set on localhost in Electron v15

### ISSUE THREAD

**Issue by jurelik** [electron/electron#31438]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS Mojave 10.14.6

### What arch are you using?

x64

### Last Known Working Electron version

14.1.1

### Expected Behavior

I want cookies to be set in electron when connecting to a server running on localhost.

### Actual Behavior

With the new Electron/Chrome update, cookies are no longer being stored. I tried different SameSite & Secure settings without any luck. I have no issues in Electron v14 with the cookies set to SameSite='none' & Secure=false.

### Testcase Gist URL

https://gist.github.com/6331477cd1c79a9570346e1828cb1cb3

### Additional Information

Also including the server code which serves the cookie to the electron app:
```
var express = require('express')
var app = express()
var session = require('express-session')

app.use(session({
  secret: 'secret',
  resave: true,
  saveUninitialized: true,
  cookie: {
    sameSite: 'none',
    secure: false
  }
}));

app.get('/', function (req, res) {
  res.end('hello world')
})

app.listen(4000, () => {
  console.log(`Example app listening at http://localhost:4000`)
})

```

**Comment by baconbrad** [comment]
Can confirm bug is in 15.3.1 but not 14.2.1.

**Comment by baconbrad** [comment]
Seems the bug exists on 16.x too.

**Comment by JakubMrowca** [comment]
Could you do something about it? You have ended support for version 14 that supported this.

**Comment by akbayt** [comment]
Same for 17.4.3

Is there any workaround? I have to test my app locally.

**Comment by patchworkfish** [comment]
Has anyone found a work around building/testing with localhost servers, or have you all had to use a hosted https server for development?

Confirming issue still persists in v19.0.0.
Electron does not store cookies where `secure: false,`.

Assumed it must have been an electron code change ony storing cookies with `secure:true`, but not found any mention in the change logs up to v19.0.0.
