### ISSUE TITLE
[Feature Request]: Set ELECTRON_USE_REMOTE_CHECKSUMS from `.npmrc`

### ISSUE THREAD

**Issue by naineshsolanki-lmi** [electron/electron#31431]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Starting with Electron 15 consuming custom electron binaries from a custom mirror requires setting the `ELECTRON_USE_REMOTE_CHECKSUMS` environment variable, otherwise the checksum match fails.

Specifying environment variables is cumbersome across all dev and CI hosts. 

### Proposed Solution

If the electron installer script also looked at the `.npmrc` it would be a one time configuration option for the project and wouldn't require additional step (of setting env variable) during dev host setup.

@electron/get allows setting the mirror options this way.

### Alternatives Considered

Other option could be an npm package config, which would also work.

@electron/get also allows setting the mirror options this way.

**Comment by Ninglo** [comment]
I also encountered the same problem, is there any progress now?
