### ISSUE TITLE
[Bug]: Ubuntu freezes when a SMB/Samba share has been mounted and showOpenDialog is called

### ISSUE THREAD

**Issue by rasgo-cc** [electron/electron#31449]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.2.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Expected Behavior

Being able to select a file after showOpenDialog is called and the dialog is opened.

### Actual Behavior

The dialog opens and Ubuntu freezes. The only way to recover from it is by restarting the machine (currently doing a `Alt + Prt Scr + REISUB`) as everything becomes unresponsive.

### Additional Information

I wasn't able to get any debug info. At least I get no error logs. Please let me know if there's some better way to debug this.

This has been tested on Windows too, and no issues there.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
