### ISSUE TITLE
[Bug]: MediaMetadata is not working on electron v15

### ISSUE THREAD

**Issue by anonymouscatcher** [electron/electron#31448]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS

### What arch are you using?

x64

### Last Known Working Electron version

13

### Expected Behavior

I updated my electron version to v15.0.2 but noticed that Metadata is not working anymore....

```js
    window.navigator.mediaSession.metadata = new window.MediaMetadata(metadata);
```
NOTE: it was working on v13.0.1

### Actual Behavior

.

### Additional Information

.

**Comment by staniel359** [comment]
Still an issue (v16.0.4)

**Comment by alirezavlz** [comment]
@codebytere also I can confirm it’s still an issue.

**Comment by staniel359** [comment]
Clarification: I'm using mutiple `BrowserView`s in `BrowserWindow`.
It's working in `BrowserView` but not in `BrowserWindow`.
