### ISSUE TITLE
[Bug]: Window capturer adds black border in the video stream under certain conditions

### ISSUE THREAD

**Issue by ZeroMax-dev** [electron/electron#31445]
### Electron Version

11.1.1 and 15.1.2 (pretty sure this is contained in all the latest versions)

### Operating System

Windows 10 version 21H1, build 19043.1237

### What arch are you using?

x64

### Last Known Working Electron version

?

### Expected Behavior

1. Start capturing a window with `desktopCapturer` and `getUserMedia` and display the `MediaStream` in a `video` element.
2. If the width and height specified in `getUserMedia` (or at least their aspect ratio) match exactly with the window dimensions the resulting `MediaStream` should show exactly the content of the window without any black borders. (If the aspect ratio doesn't match with the window then black borders are added either left/right or top/bottom.)

![x2](https://user-images.githubusercontent.com/3961753/137463121-31cb7db4-0d41-46f0-8ad6-403b3ca264b4.png)
_Figure 1:_ The window on the front is the original, the window in the background is a `BrowserWindow` with the same size as the original window, with the video element covering the whole area.

### Actual Behavior

When the original (captured) window is _maximized_ and loses focus the capturer for some reason adds a black border around the window contents in the video track. This border has nothing to do with the borders mentioned before, that are added to match the aspect ratio. The border is added at the top, left and right, but not at the bottom.

![x1](https://user-images.githubusercontent.com/3961753/137464747-47cea01e-b260-4b4d-91d7-9e3c6b318523.png)
_Figure 2:_ The original (captured) window is in the background (maximized) and thus does not have focus. The video track that is produced from it suddenly has borders around it.

If we focus the MS Paint window again, the border disappear and we are back to _Figure 1_. The dimensions of the video track do not change, instead the window contents are padded with blackness, making them smaller.

This behaviour can also be observed when the captured window does have focus and you are hovering its minimize/maximize/close buttons (in this case the borders disappear automagically again after few seconds) and when the captured window has focus and you hover your mouse over an app in the taskbar (making the thumbnail preview appear).

This only happens when the captured window is maximized, if it is in a non-maximized state the black border does not appear under these conditions.

This behaviour is very glitchy and it becomes very apparent during longer window share sessions. Because the black borders appear under such specific conditions finding a workaround is very hard. Trying to check for all these specific conditions to scale/cut off the borders is not feasible.

### Testcase Gist URL

https://gist.github.com/ZeroMax-dev/1d4a1c0a37d1385bd9350885c6204a21

### Additional notes

Because the captured window needs to be maximized this issue is best reproduced with a second screen. For most of my time I thought the black borders were always there because they only disappear when i couldn't see the video.

**Comment by spi96** [comment]
@ZeroMax-dev @sofianguy Hi! Do you possibly have any update on it? I experienced the same on Windows. The min/max height/width are set correctly, but the extracted image from the video stream contains a black left/top/right border. On MacOS this issue does not come up.

**Comment by ZeroMax-dev** [comment]
bump

**Comment by ZeroMax-dev** [comment]
bump

**Comment by parthkakadiya** [comment]
bump

**Comment by ZeroMax-dev** [comment]
bump
