### ISSUE TITLE
BrowserView: Pixel value shows when I resize a browserWindow which embedding browserViews

### ISSUE THREAD

**Issue by paulyu12** [electron/electron#31456]
Electron version: V11.3.0
Nodejs version: V14.16.0
Platform: Windows 10/11
Arch: x64

When I try to resize or move a browserWindow, the pixel values show at the upper right corner of the browserView. How can I hide them ?

Code of creating browserView is following:
```
new BrowserView({
            webPreferences: {
                enableRemoteModule: true,
                nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION,
                webSecurity: true,
            },
        })
```

Screenshot is following:
![image](https://user-images.githubusercontent.com/14888724/137662381-3e2568f1-49b7-43aa-8290-1b0243790018.png)

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
