### ISSUE TITLE
[Bug]: executableWillLaunchAtLogin is always true when app is installed per-machine

### ISSUE THREAD

**Issue by ragauskl** [electron/electron#31450]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.15

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042

### What arch are you using?

x64

### Expected Behavior

app.getLoginItemSettings([options]).`executableWillLaunchAtLogin` (as per documentation) will be true if app is set to open at login and its run key is not deactivated. Therefore if no entries in registry are found for the application to be launched on startup or if entries are disabled - the value should be false

### Actual Behavior

When electron application is installed per-machine (in  "C:\Program Files\App_Name") executableWillLaunchAtLogin is always true, even tho there are no registry keys for the application to run on startup. executableWillLaunchAtLogin  returns correct value only when installed per-user

**Comment by olegyadrov-bluescape** [comment]
As of November 2022 it is still broken.
