### ISSUE TITLE
Keys are not propagated to webview drop event

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#3146]
Using latest Electron, modifier keys don't seem to be set correctly in `drop` events that occur within a `webview` tag. From within the web-view:

```
window.addEventListener('drop', (e) => console.log(`Shift inside: ${e.shiftKey}`))
```

But from the parent renderer:

```
webView.addEventListener('drop', (e) => console.log(`Shift outside: ${e.shiftKey}`))
```

Then perform a drop with the shift key held. You'll see `false` inside the web-view and `true` outside.

**Comment by zcbenz** [comment]
This is an upstream bug, I have reported it to https://crbug.com/545315.

**Comment by xywz** [comment]
Fixed in upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=545315#c9.

**Comment by xywz** [comment]
Fixed.

**Comment by zcbenz** [comment]
Thanks for following up, I'm closing this issue now.
