### ISSUE TITLE
[Bug]: drive.google.com not loading and crashing Electron on accounts.google.com

### ISSUE THREAD

**Issue by exander77** [electron/electron#31463]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.2

### What operating system are you using?

Ubuntu

### Operating System Version

21.04

### What arch are you using?

x64

### Expected Behavior

Google Drive should work including Google Accounts login.

### Actual Behavior

When loading drive.google.com URL the first time nothing happens and when trying the second or third time it crashes electron.

Issued inside DevTools for my WebView element:
```
webview.loadURL('https://accounts.google.com/ServiceLogin?service=wise&passive=true&continue=http%3A%2F%2Fdrive.google.com%2F%3Futm_source%3Den&utm_medium=button&utm_campaign=web&utm_content=gotodrive&usp=gtd&ltmpl=drive');
webview.loadURL('https://accounts.google.com/ServiceLogin?service=wise&passive=true&continue=http%3A%2F%2Fdrive.google.com%2F%3Futm_source%3Den&utm_medium=button&utm_campaign=web&utm_content=gotodrive&usp=gtd&ltmpl=drive');
webview.loadURL('https://accounts.google.com/ServiceLogin?service=wise&passive=true&continue=http%3A%2F%2Fdrive.google.com%2F%3Futm_source%3Den&utm_medium=button&utm_campaign=web&utm_content=gotodrive&usp=gtd&ltmpl=drive');
```

**Comment by vladimiry** [comment]
@exander77 it just saves @electron maintainers time when the complete main script gets added to the report.

**Comment by Shroom2020** [comment]
Bump.
I've noticed this issue too - it happens on multiple pages, actually, but I don't know what the other one is.
