### ISSUE TITLE
[Bug]: Windows with vibrancy have a white background instead of being see-through

### ISSUE THREAD

**Issue by leolabs** [electron/electron#31461]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6

### What arch are you using?

x64

### Last Known Working Electron version

13.5.2

### Expected Behavior

When I set the `vibrancy` option on a new BrowserWindow (e.g. to "popover"), the window's background should reflect this.

<img width="838" alt="CleanShot 2021-10-18 at 22 25 54@2x" src="https://user-images.githubusercontent.com/541628/137801784-5ba70aba-40c0-4dec-a112-d770d7db24ec.png">
 

### Actual Behavior

The window's background stays white. Adding `transparent: true` to the options makes the background work as expected but removes the title bar.

<img width="820" alt="CleanShot 2021-10-18 at 22 26 48@2x" src="https://user-images.githubusercontent.com/541628/137801905-ad88db6f-2aa7-4f42-bb15-829eb2581fa4.png">

<img width="827" alt="CleanShot 2021-10-18 at 22 28 01@2x" src="https://user-images.githubusercontent.com/541628/137802078-0b7854fe-4de1-49d5-8d44-18cf78b3739a.png">

### Testcase Gist URL

https://gist.github.com/bbc333443f77ce4a6061d43eddf67fd4

### Additional Information

This might be related to #30993

**Comment by BitesPotatoBacks** [comment]
@leolabs Is this happening with all vibrancy options? For example, if you try ```appearance-ui```? I see in your test case, you are using the vibrancy type```window```, which is a type of vibrancy that seems to act as a system-theme based solid color with desktop tinting capabilities, but it does _not_ enable translucency

(Who knows about Swift or ObjC, but aleast in ElectronJS, that’s how ```window``` works).

I do see in your post you mentioned this issue happens with ```popover``` as well (correct?), but was just curious!

 👍

**Comment by BitesPotatoBacks** [comment]
@leolabs hmm strange hopefully some devs can get on this then

**Comment by craftzdog** [comment]
Same on electron@15.2.0

**Comment by leolabs** [comment]
I don't have any experience building Electron from source, but if there's anything I can do to help, please let me know :)
