### ISSUE TITLE
[Bug]: shell.openExternal not work at ubuntu21.04

### ISSUE THREAD

**Issue by eeeeeio** [electron/electron#31485]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Ubuntu

### Operating System Version

ubuntu21.04

### What arch are you using?

x64

### Last Known Working Electron version

15.2.0

### Expected Behavior

run shell.openExternal(url)
open a file

### Actual Behavior

run shell.openExternal(url)
log
`
xdg-open - opens a file or URL in the user's preferred application

Synopsis

xdg-open { file | URL }

xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.
`

then nothing happen

but its work when I use childProcess.exec('xdg-open ' + url)

url is a file path

**Comment by andersk** [comment]
This might be #28436?

**Comment by LindirQuenya** [comment]
I am having the same problem. Here's a gist, generated by electron fiddle.

https://gist.github.com/5fb97f76b4a83861673125a921ab88be

**Comment by LindirQuenya** [comment]
This issue is still present in electron v21.0.1.

**Comment by zanzara** [comment]
This issue is still present in electron v21.1.0

**Comment by LindirQuenya** [comment]
This issue is still present in Electron v25.3.0 and v26.0.0-beta5 on Ubuntu 23.04.

**Comment by LindirQuenya** [comment]
> This might be #28436?

Based on the error message, I would assume that it isn't. It looks like electron is invoking `xdg-open` incorrectly.

**Comment by LindirQuenya** [comment]
Still present in 27.0.2 and 28.0.0-alpha.4 on Ubuntu 23.04. Same behavior - `openExternal('/home')` fails with an error message, `openExternal('file:///home')` works fine. Is this expected behavior? Are we not supposed to be able to put file paths directly into `openExternal`?

**Comment by LindirQuenya** [comment]
After inserting some logging into `xdg-open`, it looks like electron isn't passing it any arguments in the first case? In the second case it is passed `file:///home`.

**Comment by BlackHole1** [comment]
bump

**Comment by mnvr** [comment]
Was able to reproduce the issue in Ubuntu 24.04 LTS.
