### ISSUE TITLE
[Bug]: InitializeSandbox() called with multiple threads in process gpu-process.

### ISSUE THREAD

**Issue by robinchrist** [electron/electron#31491]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

Kubuntu 20.04 

### What arch are you using?

x64

### Last Known Working Electron version

13.5.2

### Expected Behavior

No GPU error should occur

### Actual Behavior

```
git clone git@github.com:electron/electron-quick-start.git
cd electron-quick-start
npm ci
npm start
```
logs an error in the console:
```
[75521:1020/155427.230064:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Same thing happens for Electron 14.0.0 (probably all other 14.X.X versions).
Electron 13.5.2 works:
```
git clone git@github.com:electron/electron-quick-start.git
cd electron-quick-start
npm ci
npm install --save-dev electron@13.5.2
npm start
```

**Comment by ckerr** [comment]
works without error message for me in 14.0.0-beta.11, but I see it in -beta.12.

Diffs between those two versions: https://github.com/electron/electron/compare/v14.0.0-beta.11...v14.0.0-beta.12

**Comment by deepak1556** [comment]
Upstream issue https://bugs.chromium.org/p/chromium/issues/detail?id=1112159 , this would be specific to particular GPU driver, best to attempt this with chromium on same device and follow-up on the upstream issue.

**Comment by Kilian** [comment]
This started happening on my device (Intel Iris graphics, so pretty common) with 17.0.0-alpha.4. Alpha 3 works fine so I bet its related to the chromium 98 upgrade. Figured I'd make note of it anyway.

**Comment by SuperSonicHub1** [comment]
Also having this issue. Can I somehow force Electron to use an older version of Chromium?

**Comment by savannidgerinel** [comment]
I am running into this on all of Electron 16.x. Tested today on 16.0.5.

**Comment by jcubic** [comment]
Same issue, Fedora with Dell Inspiron laptop using builtin graphic card. I've updated dependencies and tried to run my demo app.

**Comment by jcubic** [comment]
I've installed version electron@12 it seems that version works fine.

**Comment by ckerr** [comment]
From upstream thread:

> Thanks for posting the driver information. Yeah you can ignore the error for now, it essentially means we can't currently sandbox your GPU process because the GPU driver is starting threads. Everything should still work normally.

**Comment by nornagon** [comment]
Closing this as it is an upstream issue, and further, not actionable by us.
