### ISSUE TITLE
[Bug]: allowing macOS camera permission is not persistent

### ISSUE THREAD

**Issue by sunknudsen** [electron/electron#31490]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

v15.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Developing app that streams video from webcam to HTML5 video tag.

When I run app, I am asked to allow camera permission on macOS.

Once allowed, I expect camera permissions to be persistent.

Following code runs in renderer process.

```javascript
let camera
const devices = await navigator.mediaDevices.enumerateDevices()
devices.forEach((device) => {
  if (device.kind === "videoinput") {
    camera = device
  }
})
constraints = {
  audio: false,
  video: {
    deviceId: {
      exact: camera.deviceId,
    },
  },
}
stream = await navigator.mediaDevices.getUserMedia(constraints)
video.srcObject = stream
video.setAttribute("playsinline", true)
video.play()
```

### Actual Behavior

I am asked to allow camera permission each time I run app or reload window.

**Comment by miniak** [comment]
These permissions are handled by the OS, the issues is most probably related to the app identify (signing, etc.)
