### ISSUE TITLE
input is not working in second browserView[Bug]: 

### ISSUE THREAD

**Issue by w3cways** [electron/electron#31510]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^13.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10 Professional 18363.1256

### What arch are you using?

x64

### Last Known Working Electron version

^13.0.0

### Expected Behavior

input can work in second browserView .

### Actual Behavior

input is not working in second browserView

1. in mainWindow ,create first browserView
2. create second browserView, and set second browserView focus

in first  browserView input is working
![image](https://user-images.githubusercontent.com/6859510/138232590-91edc828-f872-4144-8e25-3d8a640beb89.png)

in second browserView ,input can't be focused and can't enter anyting , even I set the input focused and set second browserView webcontents focused

![image](https://user-images.githubusercontent.com/6859510/138233236-206e5cb2-eb28-4d01-a49a-c4223572c564.png)

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
