### ISSUE TITLE
[Bug]: In Windows, Clicking on maximize button and then minimizing the window and focusing with alt+tab, aspect ratio breaks.

### ISSUE THREAD

**Issue by lakshya-munjal** [electron/electron#31511]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 v21H1

### What arch are you using?

x64

### Expected Behavior

I had set the max-width and max-height of the window when creating a new object using BrowserWindow. When I click on Maximize button, it grows to it maximum size, after that minimize the window. Now use Alt+Tab to bring window into focus, the size of the window should be same.

### Actual Behavior

After using Alt+Tab to bring window to focus, window width grows more than the maximum width defined.

### Testcase Gist URL

https://gist.github.com/lakshyamunjal/c7ac335bbb7ca83d485b2d22bc4f527f

**Comment by pushkin-** [comment]
I can repro on Windows 10 with Electron 21 though when maximizing, the window doesn't actually fill the entire monitor for some reason (though still appears to be in a maximized state)

**Comment by pushkin-** [comment]
repros in v23

**Comment by pushkin-** [comment]
seems to repro in v26
