### ISSUE TITLE
[Bug]: No longer possible to set insecure cookies

### ISSUE THREAD

**Issue by t57ser** [electron/electron#31553]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15, 16

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.985

### What arch are you using?

x64

### Last Known Working Electron version

14

### Expected Behavior

Cookie setting succeeds

### Actual Behavior

It is no longer possible to set an insecure cookie
```
session.cookies.set({
	name: "testcookie",
	value: "testvalue",
	domain: ".testdomain.com",
	path: "/",
	url: "http://testdomain.com",
	secure: false,
}).then(() => {
	console.log("setting cookie success");
}).catch((e) => {
	console.error(e);
});
```
returns: [Error: Setting cookie failed]
Removing the "secure: false" returns: [Error: Cannot create a secure cookie from an insecure URL]

### Testcase Gist URL

https://gist.github.com/t57ser/a34dfe9579b856e6e765b59fb8d215cb

**Comment by VerteDinde** [comment]
@t57ser Opened an PR to fix the issue with setting insecure cookies on a secure URL. 🙇‍♀️ 

Just to clarify, I think the second part of your issue ("Removing the "secure: false" returns: `[Error: Cannot create a secure cookie from an insecure URL] ") is expected behavior? When I changed the URL from `http://testdomain.com` to `https://testdomain.com`, setting the secure cookie works. I don't think we'd want to set a secure cookie from an insecure URL. But let me know if you disagree or I missed a portion of the bug :)

**Comment by t57ser** [comment]
Yes but that would imply that the default for secure is true, I'd assume that you have to explicitly set secure: true.
But that happens because of what i explain later, the secure flag will be set to true because no_restriction is set, it is part of the internal code of electron. So not specifying a secure option does not default to true.
You might be confusing "removing secure:false" to mean "secure:true" but what i mean is
```
{
	name: "testcookie",
	value: "testvalue",
	domain: ".testdomain.com",
	path: "/",
	url: "http://testdomain.com",
}
```

**Comment by t57ser** [comment]
Happens here: https://github.com/electron/electron/blob/5461e6bf8ca31b113c948d0de98b66986f5121ed/shell/browser/api/electron_api_cookies.cc#L306

**Comment by VerteDinde** [comment]
Ah, okay yes, I see the disconnect now - I was assuming that a default of `secure: true` was the correct behavior. Will look into this and fix it, thanks!
