### ISSUE TITLE
[Bug]: Cannot find module 'electron-updater'  

### ISSUE THREAD

**Issue by langching** [electron/electron#31552]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

8.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

8.1.1

### Expected Behavior

Cannot find module 'electron-updater'  

### Actual Behavior

Cannot find module 'electron-updater'

**Comment by Alecyrus** [comment]
install it first

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment above](https://github.com/electron/electron/issues/31552#issuecomment-949922946). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
