### ISSUE TITLE
[Feature Request]: Custom window.prompt / alert Middleware

### ISSUE THREAD

**Issue by Awendel** [electron/electron#31560]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

window.prompt is not implemented and may break websites that rely on the feature
window.alert etc. are also subpar compared to e.g. Google Chrome implementation

### Proposed Solution

Offer middleware API to define Custom behaviour of these APIs.
The default can stay how it is but it might be good to define custom functions that those window calls then get routed to.

### Alternatives Considered

I know it's not too important for the content of the App but for things like building an In-App browser etc., the experience is currently a lot worse than Google Chrome and similar.

**Comment by miniak** [comment]
Duplicate of #26160

**Comment by HQidea** [comment]
> But would this also work for window.prompt / window.confirm?
> 
> Since they essentially "block" the UI thread,
> 
> would the logic then be, that I send a sync ipc req, then the main processes "freezes" the browserwindow / browserview, awaits a response, then "unfreezes" the browserwindow and returns the input?

But how can I implement to freeze the browserwindow or WebContentsView?
