### ISSUE TITLE
[Bug]: tray icon disappears after several seconds even if I declare `tray` to be global.

### ISSUE THREAD

**Issue by YongzeYao** [electron/electron#31564]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Tray Icon would stay in the tray. 

### Actual Behavior

Tray Icon disappears after several seconds.

### Additional Information

```js
const { app, Tray, nativeImage } = require('electron');
const path = require('path');

let tray = null;

app.whenReady().then(() => {
  const icon = nativeImage.createFromPath(
    path.join(__dirname, './assets/icon.png')
  );
  tray = new Tray('src/assets/icon.png');
  tray.setTitle('Attention App');
});
```

**Comment by jtvberg** [comment]
I have the same problem with the same code.

Electron 15.0.3 (though I see the same with 12 and 14)

macOS Monterey 12.0.1 (doesn't work on Catalina 10.15.7 either)

x64

No other dependencies but Electron.

Tray disappears with this code:
```
const { app, Tray } = require('electron')

let tray = null
const createTray = () => {
  tray = new Tray('./iconTemplate@2x.png')
  tray.setToolTip('AppName')
}

app.whenReady().then(() => {
  createTray()
})
```

What I did note is that if I add a menu to it, it does not disappear (this works):
```
const { app, Tray, Menu } = require('electron')

let tray = null
const createTray = () => {
  tray = new Tray('./iconTemplate@2x.png')
  tray.setToolTip('AppName')
}

const createMenu = () => {
  const menu = Menu.buildFromTemplate([
    {
      label: 'Quit',
      click() {
        app.quit()
      },
      accelerator: 'CommandOrControl+Q',
    }
  ])

  tray.setContextMenu(menu)
}

app.whenReady().then(() => {
  createTray()
  createMenu()
})
```

Just for kicks, I tried adding a browserWindow that was set to not show, added a basic index.html for it load and it still disappears without a menu attached.

**Comment by jtvberg** [comment]
Ok, so this is interesting...
If I add this to my code, the tray doesn't get garbage collected:
```
app.on('activate', () => {})
```

I have another app that uses a tray icon that doesn't disappear so I started with that and eliminated code until it did.
I have confirmed that the below works even though the app event is empty:
```
const { app, Tray } = require('electron')

let tray = null
const createTray = () => {
  tray = new Tray('./iconTemplate@2x.png')
  tray.setToolTip('AppName')
}

app.whenReady().then(() => {
  createTray()
})

app.on('activate', () => {})
```
