### ISSUE TITLE
[Bug]: Wrong value from getPath("userData")

### ISSUE THREAD

**Issue by weedz** [electron/electron#31565]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0-beta.3

### What operating system are you using?

Other Linux

### Operating System Version

Linux pop-os 5.13.0-7614-generic #&#x2060;14\~1631647151\~21.04\~930e87c-Ubuntu

### What arch are you using?

x64

### Last Known Working Electron version

15.3.0

### Expected Behavior

From the documentation for `app.getPath("userData")` (https://www.electronjs.org/docs/latest/api/app#appgetpathname):
> The directory for storing your app's configuration files, which by default it is the appData directory appended with your app's name.

So `app.getPath("userData")` in the linked gist should be `~/.config/test-electron`.

### Actual Behavior

`app.getName()` returns the correct name from package.json but `app.getPath("userData")` returns `~/.config/Electron`.

### Testcase Gist URL

https://gist.github.com/weedz/ad42b854df4e5bc411d18e48ae1c91df

### Additional Information

Found this issue which might be relevant https://github.com/electron/electron/issues/30112.

Same result in the following devcontainer https://gist.github.com/weedz/c962d69078391115635772b279264c02.

**Comment by deepak1556** [comment]
@clavin this is now addressed in https://github.com/electron/electron/pull/31668
