### ISSUE TITLE
[Bug]: --ignore-certificate-errors command-line flag no longer works

### ISSUE THREAD

**Issue by kriswest** [electron/electron#31596]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.1288

### What arch are you using?

x64

### Last Known Working Electron version

unknown, probably around 11

### Expected Behavior

`--ignore-certificate-errors` command line switch doesn't appear to work anymore. Its still listed in documentation here:
https://www.electronjs.org/docs/latest/api/command-line-switches#--ignore-certificate-errors

It no longer appears in the Chromium reference here (and I think they've contemplated dropping it since 2017):
https://peter.sh/experiments/chromium-command-line-switches/

However, `--ignore-certificate-errors-spki-list` does appear to work (but is not listed in the docs):
https://peter.sh/experiments/chromium-command-line-switches/#ignore-certificate-errors-spki-list

### Actual Behavior

Command-line switches in the documentation do actually work ;-). 

If this one is out of your control, remove it and replace with the alternative `--ignore-certificate-errors-spki-list` flag. You might also refer to https://www.electronjs.org/docs/latest/api/app#event-certificate-error as a better way to handle certificate errors.

**Comment by kriswest** [comment]
> It might not be listed but it definitely still exists and functions:

I'll try and find time to test with Electron Fiddle. It's not working for us anymore, where `--ignore-certificate-errors-spki-list` is (in Electron 13.3.0)

**Comment by ckerr** [comment]
If you're testing it out with Electron Fiddle, it could be very helpful to know in which release (especially nightly, alpha, or beta) where it stopped working.

**Comment by rppig42** [comment]
It doesn't work in Electron 16 too.
