### ISSUE TITLE
[Bug]: [97258:1026/120955.772050:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.

### ISSUE THREAD

**Issue by raphael10-collab** [electron/electron#31590]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Last Known Working Electron version

13

### Expected Behavior

No ERROR

### Actual Behavior

When running the electron-react app I get this error message.

If I downgrade Electron from version 15 to version 13 the error disappears.
The problem starts to appear from version 14

### Additional Information

    97258:1026/120955.772050:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.

**Comment by ckerr** [comment]
Agreed. Closing as a dupe
