### ISSUE TITLE
[Bug]:  remote.systemPreferences.getUserDefault('AppleActionOnDoubleClick', 'string')

### ISSUE THREAD

**Issue by wonkyungup** [electron/electron#31604]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.6.0

### What operating system are you using?

macOS

### Operating System Version

Mac OS BigSur 11.6

### What arch are you using?

intel mac

### Expected Behavior

var dbClickAction = remote.systemPreferences.getUserDefault('AppleActionOnDoubleClick', 'string')
console.log(dbClickAction)

// result
result

### Actual Behavior

Big Sur, remote.systemPreferences.getUserDefault('AppleActionOnDoubleClick', 'string') seems to return the empty string ("") by default.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
