### ISSUE TITLE
[Bug]: getSize & getBounds does not return the correct value in  enter-full-screen & leave-full-screen events

### ISSUE THREAD

**Issue by KiranNiranjan** [electron/electron#31603]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.1

### What operating system are you using?

Windows

### Operating System Version

Window 10

### What arch are you using?

x64

### Expected Behavior

In `enter-full-screen` & `leave-full-screen` events the values returned from `getSize` & `getBounds` should be correct

### Actual Behavior

In `enter-full-screen` the value of width and height are returned with the previous state instead of the size matching display 

```
mainWindow?.on('enter-full-screen', () => {
    const [width, height] = mainWindow.getSize();
    // width here is 400  instead of screen width ex: 1920
    // height here is 400 instead of screen height ex: 1080
  });
```

```
mainWindow?.on('leave-full-screen', () => {
    const [width, height] = mainWindow.getSize();
    // width here is 1920  instead of app default width ex: 400
    // height here is 1080 instead of app default height ex: 400
  });
```

**Workaround**
Using `setTimeout` to fetch the values from `getSize` & `getBounds` returns the correct values

```
mainWindow?.on('enter-full-screen', () => {
    setTimeout(() => {
       const [width, height] = mainWindow.getSize();
      // width here is 400  instead of screen width ex: 1920
      // height here is 400 instead of screen height ex: 1080
    }, 500)
  });
```

Note: This issue only happens on Windows OS and works perfectly on macOS

### Testcase Gist URL

https://gist.github.com/KiranNiranjan/7dfdc2a3ef9770c70886b5fcad9e817a

**Comment by ckerr** [comment]
FWIW the values are also correct on Linux both in the reported version (14.0.1) and in main:

> on leaving 800 600
on entering 1920 1200

So probably not in the views code shared by the GTK and Windows builds :thinking:
