### ISSUE TITLE
[Bug]: Cannot load url when set proxy

### ISSUE THREAD

**Issue by sonlv10** [electron/electron#31609]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0

### What operating system are you using?

macOS

### Operating System Version

Mac os

### What arch are you using?

x64

### Expected Behavior

I can load url https://www.ipaddress.my/ but not https://github.com/

### Actual Behavior

electron: Failed to load URL: https://github.com/ with error: ERR_TUNNEL_CONNECTION_FAILED

### Additional Information

`const fbBrowser = new BrowserWindow({ 
        width: 400, 
        height: 600, 
        show: false,
        webPreferences: {partition: 'persist:fbwebviewsession',sandbox: true, nodeIntegration: true}
    })
    proxyConfig = {
        host: '65.21.56.241',
        port: '49200',
        type: 'http',
        user_name: 'user49200',
        password: '5HFaeWdeko',
        isCheck: false
    }
    
    session.fromPartition('persist:fbwebviewsession').setProxy({proxyRules:`${proxyConfig.type}://${proxyConfig.host}:${proxyConfig.port}`}).then(() => {
        fbBrowser.loadURL('https://github.com/')
    })`

**Comment by zcbenz** [comment]
As the error `ERR_TUNNEL_CONNECTION_FAILED` said, it failed because the proxy failed to do the connection, from the existing information we are unable to determine whether this is an issue of Electron.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
