### ISSUE TITLE
[Bug]: crypto.hkdf "Deriving bits failed"

### ISSUE THREAD

**Issue by panva** [electron/electron#31634]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

v15.3.0

### What operating system are you using?

macOS

### Operating System Version

Darwin C02CX0K5MD6V 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

`crypto.hkdf` and `crypto.hkdfSync` work as documented[^1]

[^1]: https://nodejs.org/api/crypto.html#cryptohkdfdigest-ikm-salt-info-keylen-callback

### Actual Behavior

```
crypto.hkdfSync('sha256', 'foo', '', '', 32)
// Uncaught Error: Deriving bits failed
//    at Object.hkdfSync (node:internal/crypto/hkdf:140:35)
crypto.hkdf('sha256', 'foo', '', '', 32, console.log)
// [Error: Deriving bits failed]
```

**Comment by codebytere** [comment]
@panva This is unfortunately not an expectation since Electron uses BoringSSL and Node.js uses OpenSSL. BoringSSL supports a smaller subset of algorithms as as such sometimes there are disparities - I'll take a look but can't promise this is something we're able to fix.

**Comment by panva** [comment]
I'm aware that not all digests would be available but the basic functionality can be achieved with the available digests.

**Comment by codebytere** [comment]
@panva the issue is that a large number of the underlying functions are not available.

https://github.com/nodejs/node/blob/cbfe5b46293f81431a6aa2f495584c904dc891cf/src/crypto/crypto_hkdf.cc#L100-L135

* EVP_PKEY_HKDF
* EVP_PKEY_CTX_set_hkdf_md
* EVP_PKEY_CTX_set1_hkdf_salt
* EVP_PKEY_CTX_set1_hkdf_key
* EVP_PKEY_CTX_add1_hkdf_info
* EVP_PKEY_HKDEF_MODE_EXTRACT_AND_EXPAND

Are not available to us.

**Comment by TakamiChie** [comment]
I have also encountered this problem.

Specifically, it is confirmed that this error occurs when executing the `auth()` method of the module `express-openid-connect`.
- https://github.com/auth0/express-openid-connect

However, this module works fine in NodeJS 18.x. For this reason, we believe that it is a problem with NodeJS 16.x shipped with Electron.
Both Node 16.14.2 shipped with the Latest release and 16.15.1 shipped with nightly have the following errors:

```
Error occurred in handler for 'oidc_connection': Error: Deriving bits failed
    at Object.hkdfSync (node:internal/crypto/hkdf:140:35)
    at module.exports.signing (...\node_modules\express-openid-connect\lib\hkdf.js:31:14)
    at ...\node_modules\express-openid-connect\lib\transientHandler.js:58:29
    at Array.forEach (<anonymous>)
    at new TransientCookieHandler (...\node_modules\express-openid-connect\lib\transientHandler.js:57:13)
    at auth (...\node_modules\express-openid-connect\middleware\auth.js:31:21)
```

I don't think Electron can partially use Node 18.x, is there a response that Electron users can take to this issue?

**Comment by codebytere** [comment]
@TakamiChie : https://github.com/electron/electron/issues/31634#issuecomment-956075779

this is not a problem with Node.js being broken. It simply uses functionality that is *incompatible* with the fork of OpenSSL, BoringSSL, that is in Electron. I can try to talk to the BoringSSL maintainers about it but that's the best we can do.

**Comment by KishanBagaria** [comment]
@TakamiChie you can use https://www.npmjs.com/package/@peculiar/webcrypto instead of the crypto module exported by Electron, might require forking express-openid-connect

**Comment by codebytere** [comment]
Good news! BoringSSL enabled support for HKDF - once the current Chrome roll lands I can open a PR to re-enable it.
