### ISSUE TITLE
[Bug]: Accelerator shortcuts using numpad not correctly displayed in menus

### ISSUE THREAD

**Issue by Billiam** [electron/electron#31638]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.3.0

### What operating system are you using?

Other (specify below)

### Operating System Version

 Windows 10 19043.1288, and 5.10.68-1-MANJARO #1 SMP PREEMPT Wed Sep 22 12:29:47 UTC 2021 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

When using menu key accelerators like `Ctrl+num5`, the shortcut displayed in the menu should indicate that shortcut uses the numpad, like:

`<action> Ctrl+Num5`
or
`<action> Ctrl+NumPad5`

### Actual Behavior

Accelerator shortcut listed displayed as `Ctrl+5`, which implies that the key to use is the non-numpad number instead.

### Testcase Gist URL

https://gist.github.com/e61219b841ec5f06f05ed7fef5b84317

### Additional Information

![electron_DUJDnF6uAn](https://user-images.githubusercontent.com/242008/139494980-3074d9d1-117c-44ea-b25f-e393bf9565eb.png)

**Comment by codebytere** [comment]
Is this intended behavior? I've not seen this displayed with `Ctrl+Num5` on any native macOS or Windows application before.

**Comment by Billiam** [comment]
It's not a very common shortcut, but here's Windows app MPC-BE's pan and scan menu:
![6qvdsgI](https://user-images.githubusercontent.com/242008/140183480-e7441298-50d2-43d3-98c1-f2dfa13321d0.png)
