### ISSUE TITLE
[Bug]: Closing Electron Window printing the PDF causes SIGSEGV

### ISSUE THREAD

**Issue by exander77** [electron/electron#31635]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Ubuntu

### Operating System Version

21.10

### What arch are you using?

x64

### Expected Behavior

Windows closes without crashing the application.

### Actual Behavior

Crashes with:
```
/path//node_modules/electron/dist/electron exited with signal SIGSEGV
```

### Testcase Gist URL

https://gist.github.com/c149f480e2ae5ac86b1c6a156dfe2ad3
### Additional Information

I open a new Window with WebView that contains PDF, initiate printing. Printing works fine. But when I close the window after printing, the application crashes with SIGSEGV.

**Comment by zcbenz** [comment]
Can you check if this crash also happens on older versions of Electron?

**Comment by exander77** [comment]
@zcbenz I went to my oldest Electron version in Electron-Fiddle 12.0.0 and it crashes as well.

**Comment by exander77** [comment]
It works in the beta version of 16. Was it fixed? Will the fix be backported to 15? Because it erases cookies when upgraded from 15 to 16... so I hate to upgrade.

**Comment by exander77** [comment]
Had to move to 17 and it crashes again.

**Comment by exander77** [comment]
No, it crashes with 16 as well. Probably some fluke.

**Comment by exander77** [comment]
The supplied gist doesn't trigger it on all versions, but my production code does.
Is there a way to install some segfault handler so the app survives and only window crashes?
I can now confirm that this does in every version of the electron, but gist only reproduces it on some for some reason.

**Comment by exander77** [comment]
Can I at least disable it and open the file by the associated program?

**Comment by exander77** [comment]
This is such a mess.

My end game workaround, for now, is that I am launching a separate process to open PDFs. It limits the number of crashes of that process and there is no difference if it crashes on close or just closes.

Otherwise, this is present in all versions of the Electron, sometimes it seems that you need to have more data loaded in the process to trigger this.

**Comment by zhangriyueming** [comment]
same here. 13.5.2 works fine.

**Comment by exander77** [comment]
@zhangriyueming My workaround with spawning another electron process for PDFs is ugly, but it works. I use electron fetch to make the request, download the file to tmp and open the downloaded file in a new electron process. Even if the window crashes, it doesn't matter.

**Comment by personalizedrefrigerator** [comment]
I'm experiencing this with Electron 26 (Ubuntu 23.10). My current workaround is to close the window in a `setTimeout` 1000ms after printing completes.
