### ISSUE TITLE
[Bug]: setShape([]) does not clear shape in Linux

### ISSUE THREAD

**Issue by wjps** [electron/electron#31642]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21.10 X11

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

Calling the BrowserWindow setShape call with an empty list should clear any previous shapes and allow drawing to the full window, as described in the documentation.

### Actual Behavior

setShape([]) appears to disable drawing to any part of the window, causing the contents of the window to disappear from view.

### Additional Information

The call works as expected on Windows 10 but not on Linux.

**Comment by zcbenz** [comment]
Can you check if it worked in older versions of Electron?

**Comment by wjps** [comment]
I've checked a few older versions, 13.x 14.x and the behaviour is
unchanged.

**Comment by wjps** [comment]
Ok here's a test case, hopefully it should be self explanatory. Unfortunately it's not possible to test for success or failure programmatically.

https://gist.github.com/a226a90506d15840aaae6f52d66fbc6e

**Comment by PolymerCo** [comment]
Having the same issue on Electron 12.0.6 on Linux

**Comment by PolymerCo** [comment]
For anybody looking for a workaround, shapes can be set to be larger than the size of the window. It appears to have the effect of 'clearing' the shape so to speak:

```ts
setShape([x: 0, y:0, width: 9999, height: 9999])
```

May not work in all cases however
