### ISSUE TITLE
[Bug]: The context-menu is sometimes selected unintentionally

### ISSUE THREAD

**Issue by exceedsystem** [electron/electron#31641]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Other (specify below)

### Operating System Version

OpenSUSE 15.3(Kernel 5.3.18-59.27-default)

### What arch are you using?

x64

### Expected Behavior

Context menu selection should be done when you explicitly click on an item.

### Actual Behavior

When there are many items in the context-menu and the corner of the menu is not next to the mouse cursor, the menu item may be selected unintentionally on Linux systems due to the mouse button up event.

![Peek 2021-10-31 11-19](https://user-images.githubusercontent.com/70489172/139567782-44bd7855-fda3-4c29-9b28-c3d9a6a55ee7.gif)

### Testcase Gist URL

https://gist.github.com/d9cca97cbfb450d0ad151b193aaf6a98

### Additional Information

- Related: microsoft/vscode#113175

- My display(DELL S3221QS) pixels are not square.
  ```bash
  xdpyinfo | grep -B2 resolution
  screen #0:
    dimensions:    3840x2160 pixels (702x400 millimeters)
    resolution:    139x137 dots per inch
  ```

- This issue is still occurring even if I fix the DPI to 120 or 144 in `.Xresources` or `xorg.conf`'.

- I don't have this problem on my other Debian Linux system (Apple cinema LED display/2560x1440 pixels, 96x96dpi).
However, the same problem occurred when I forced the DPI to change to "137" in ".Xresources".

**Comment by exceedsystem** [comment]
Additional information.

> My display(DELL S3221QS) pixels are not square.

The above information may not be correct.
However, instead of the auto-detected DPI, I tried calculating the DPI from the viewalable-image-size of the LCD panel and manually setting it in xorg.conf(20-nvidia.conf), but that didn't solve the problem.

Get the viewable image size of the display.

```bash
xrandr | grep -w connected
DP-2 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 697mm x 392mm
```

Calculating the actual DPI.

```bash
DPI X: 3840 / (697 / 25.4) ≈ 140
DPI Y: 2160 / (392 / 25.4) ≈ 140 
```

Set calculated DPI into "20-nvidia.conf".

```bash
Section "Device"
    blah blah blah
    # Added DPI setting here
    Option         "DPI" "140 x 140"
EndSection
```

As a result.

```bash
xrandr | grep -w connected
DP-2 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 697mm x 392mm

xdpyinfo | grep -B2 resolution
screen #0:
dimensions:    3840x2160 pixels (697x392 millimeters)
resolution:    140x140 dots per inch
```

**Comment by nmggithub** [comment]
This issue still persists in VSCode and it appears to be upstream here: https://github.com/microsoft/vscode/issues/113175. Please look more into this.

**Comment by ckerr** [comment]
I used https://gist.github.com/d9cca97cbfb450d0ad151b193aaf6a98 to try & reproduce the issue, but I'm not sure what I'm looking at -- things seem to be working as expected and it's not clear to me from @exceedsystem's gif where the issue is. Could someone help me to understand what exactly is going wrong, and how to reproduce it?

**Comment by francesco-gallo** [comment]
> I used https://gist.github.com/d9cca97cbfb450d0ad151b193aaf6a98 to try & reproduce the issue, but I'm not sure what I'm looking at -- things seem to be working as expected and it's not clear to me from @exceedsystem's gif where the issue is. Could someone help me to understand what exactly is going wrong, and how to reproduce it?

The problem is that right clicking the mouse, the menu appear directly under the pointer, so releasing the right click will also click the element directly under the pointer.

**Comment by zzeitt** [comment]
bump

**Comment by aldelaro5** [comment]
bump

**Comment by deepak1556** [comment]
@exceedsystem thanks for the minimal repro, however I am unable to recreate the issue on my system (Ubuntu 22.04 via Parallels VM running on 15.4inch Macbook pro) with the following custom display configs. Also I am using the trackpad to test.

```
> xdpyinfo | grep -B2 resolution
screen #0:
  dimensions:  2560x1600 (474x296 millimeters)
  resolution: 137x137 dots per inch

> xdpyinfo | grep -B2 resolution
screen #0:
  dimensions:  1680x913 (445x242 millimeters)
  resolution: 96x96 dots per inch
```

Is there any other configurations to change that would help us repro the issue ?

**Comment by francesco-gallo** [comment]
@deepak1556 VirtualBox, Lubuntu 18.04 guest, on "full screen mode" the problem doesn't happen to me, on windowed it does

`screen #0:
  dimensions:    1920x985 pixels (508x261 millimeters)
  resolution:    96x96 dots per inch
`

**Comment by deepak1556** [comment]
Still unable to repro,

https://github.com/electron/electron/assets/964386/0df7187c-93fe-4e23-947f-c35c33e48076

**Comment by francesco-gallo** [comment]
On "full screen mode" (without bug) i stil have 96x96 resolution,

`screen #0:
  dimensions:    1920x1080 pixels (508x286 millimeters)
  resolution:    96x96 dots per inch
`

but setting 200x scaling i get it again

`screen #0:
  dimensions:    960x540 pixels (254x143 millimeters)
  resolution:    96x96 dots per inch
`

(note that on 200x the contextual menu gets too big to fit vertically)

**Comment by francesco-gallo** [comment]
On your case, the menu appears exactly on the pointer's edge
![image](https://github.com/electron/electron/assets/5757805/0b2704e0-c156-44d5-8104-ed55645033b2)

With the issue, it appears slightly under

1920, full screen, 96x96, 100x scaling
![image](https://github.com/electron/electron/assets/5757805/2b8552cb-7327-4c03-9fa7-ff55b2af874b)

1920, full screen, 96x96, 150x scaling
![image](https://github.com/electron/electron/assets/5757805/98a8f411-1f97-474a-9855-98a12c23f6b1)

Since in your case the menu is always placed correctly, I don't think any change of resolution will ever be able to reproduce the bug

**Comment by exceedsystem** [comment]
@francesco-gallo

I also use LXDE.

```sh
echo $XDG_CURRENT_DESKTOP
LXDE
```

**Comment by deepak1556** [comment]
Tried LXDE with 1920x1080 , 144dpi. Can you check if anything else is missing, unable to repro still


https://github.com/electron/electron/assets/964386/6e8e1c6c-7771-4c1f-847b-4e55714810ef

**Comment by francesco-gallo** [comment]
No idea, only thing I saw is that sometimes the pointer is placed on the margin, sometimes a bit more on the right (causing the issue), and always on the same X coordinates (i.e. on mouse coord x = 5 or x = 14 I always get the issue)
Try to spam right click to see if you, too, get a x coord with the problem (there is not difference between white space or text)

![photo_6028210303763855754_y](https://github.com/electron/electron/assets/5757805/1fd73a96-bce1-42bb-a0a1-cb11332a6ab1)

![photo_6028210303763855753_y](https://github.com/electron/electron/assets/5757805/4b10c66f-07cf-42b6-a77f-baca24683981)

**Comment by cas--** [comment]
I am seeing the context menu issue with VSCode but this gist does not replicate that issue. I tried Electron 15, 18 & 22.

I did note that the OP mentions 'sometimes' and requires clicking the mouse many times. Whereas on VSCode this is consistently a problem when zoom level is not zero and the middle of the context menu ends up near the mouse cursor. I would be concerned that the OP has a subtly different issue that is not central to the VSCode issue.

**Comment by exceedsystem** [comment]
From the way the problem occurs, I guess the impression that the pixel positions are off due to errors (e.g., floating point errors, rounding errors) in the calculation of the coordinates for displaying the popup.

However, I am not sure if it is an Electron issue or a GTK or other issue.

**Comment by exceedsystem** [comment]
Incidentally, a quick question to GPT-4 about possible causes yielded the following responses.
I hope this is helpful.

> List some possible causes of context menu pop-up misalignment and menu item activation in Electron applications.
>
> 1. Mismatched Electron versions: If the Electron version used in the main process doesn't match the version used in the renderer process or the version used in a preload script, inconsistencies may arise, leading to misalignment and activation issues in context menus.
> 
> 2. Incorrect CSS styles: If the CSS styles applied to context menu components or their container elements are incorrect or clashing, it might cause misalignment and activation issues.
> 
> 3. Inaccurate positioning calculations: If the calculations used to position context menus based on click events or screen coordinates are incorrect, this might lead to misaligned pop-ups.
> 
> 4. Conflicting event listeners: Multiple event listeners for events like 'contextmenu' or 'click', both in the main and renderer process, can lead to unexpected activation or deactivation of menu items.
> 
> 5. Failure to prevent default behaviors: If the default behaviors of events like 'contextmenu', 'mousedown', or 'mouseup' are not explicitly prevented, the native context menu may interfere with the custom context menu in Electron applications.
> 
> 6. BrowserWindow configuration issues: Misconfiguration of BrowserWindow settings, such as frameless windows, transparent backgrounds, or interactions with webPreferences, can cause context menu display issues.
> 
> 7. Scaling and zoom issues: Context menu misalignment can occur if the application window's scaling or zoom factor is not considered when positioning the menu.
> 
> 8. Incompatible packages or libraries: The use of outdated or incompatible Node.js packages or libraries in your Electron application can cause unexpected behavior, including context menu issues.
> 
> 9. Bug in Electron: There might be a bug in the Electron framework itself causing the context menu misalignment and activation issues. In such cases, it is recommended to check the Electron issue tracker for a similar issue or report a new one with relevant details.
> 
> 10. Race conditions or timing issues: If the context menu is being initialized, modified, or destroyed while the user is still interacting with it, this can lead to misalignment and menu item activation issues.
> 
> 11. Operating system or platform-specific issues: There might be platform-specific differences or issues related to specific operating systems, display settings, or input devices that could cause context menu problems in Electron applications.

**Comment by deepak1556** [comment]
@francesco-gallo the relevant code for creating the menu is at https://github.com/electron/electron/blob/93024be3b26ff66a7978ba278990a0a0f55bc9d3/shell/browser/api/electron_api_menu_views.cc#L21-L59

**Comment by francesco-gallo** [comment]
What I meant was, what is the fastest way to setup a ready dev env

**Comment by deepak1556** [comment]
Fastest would be to use a [codespace ](https://github.com/electron/electron/blob/main/.devcontainer/README.md) but the issue might not repro in that case, for local dev flow you can use the [build-tools](https://github.com/electron/build-tools#getting-the-code-and-building-electron)

**Comment by francesco-gallo** [comment]
I manage to build electron, now I can launch "e launch [path-to-example]" and "e debug [path-to-example]", now I need only to attach and breakpoint on the code

**Comment by francesco-gallo** [comment]
I'm having a lot of difficulties in debugging smoothly electron, since I can't see the variables, the mouse get constantly captured, and every step is painfully slow.  
I arrived in the method

```
gfx::Point X11ScreenOzone::GetCursorScreenPoint() const {
  absl::optional<gfx::Point> point_in_pixels;
  if (ui::X11EventSource::HasInstance()) {
    point_in_pixels = ui::X11EventSource::GetInstance()
                          ->GetRootCursorLocationFromCurrentEvent();
  }
  if (!point_in_pixels) {
    // This call is expensive so we explicitly only call it when
    // |point_in_pixels| is not set. We note that absl::optional::value_or()
    // would cause it to be called regardless.
    point_in_pixels = GetCursorLocation();
  }
  // TODO(danakj): Should this be rounded? Or kept as a floating point?
  return gfx::ToFlooredPoint(
      gfx::ConvertPointToDips(*point_in_pixels, GetXDisplayScaleFactor()));
}
```

**Comment by francesco-gallo** [comment]
@exceedsystem can you check if you get a misaligned pointer on chromium? Do you have a multimonitor setup? Do you work in a virtual machine?

**Comment by exceedsystem** [comment]
@francesco-gallo 

>can you check if you get a misaligned pointer on chromium?

How can I check it?

>Do you have a multimonitor setup?

No, my environment is not multimonitor.

>Do you work in a virtual machine?

Yes, but I have Windows virtualized on linux, not Linux.

**Comment by aldelaro5** [comment]
bump, I still get this in pretty much every Electron app even when they get actively updated

**Comment by teobouvard** [comment]
Bump, issue still occurs.

**Comment by YalandHong** [comment]
bump
