### ISSUE TITLE
[Bug]: Download filename will be cut up to the first comma

### ISSUE THREAD

**Issue by alefoll** [electron/electron#31662]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 21H2 (22000.282)

### What arch are you using?

x64

### Last Known Working Electron version

latest 11, aka 11.5.0

### Expected Behavior

Downloading a file with a comma in name should return full filename.

### Actual Behavior

When the request is filtered with `onHeadersReceived`, the filename is cut up to the first comma.

### Additional Information

The issue was first reported in #29346 but was closed because it was unable to reproduce it.

http.txt

```
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Disposition: attachment; filename="foo,bar.txt"
Content-Length: 3

foo
```

Serve via ncat on port 1337

```shell
ncat -l 1337 < http.txt
```

Minimal Electron code:

```js
const {app, BrowserWindow} = require('electron')

function createWindow () {
  app.on('session-created', session => {
    session.webRequest.onHeadersReceived((details, callback) => {
      callback({ responseHeaders: details.responseHeaders });
    });
  });

  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  })

  mainWindow.loadURL('http://localhost:1337/')
}

app.whenReady().then(createWindow);
```

**Comment by codebytere** [comment]
hey @alefoll i had a few minutes to look into this today and popped up a PR here: https://github.com/electron/electron/pull/31669
