### ISSUE TITLE
[Bug]: HTMLInputElement.webkitdirectory is broken on Windows and Linux

### ISSUE THREAD

**Issue by sohobloo** [electron/electron#31663]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

12.0.7

### Expected Behavior

Execute the following example on MDN will list all the paths in the selected directory.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory#result

### Actual Behavior

No result.

### Testcase Gist URL

https://gist.github.com/sohobloo/34ebf5e2b94f1e445888442cb8bb9598

**Comment by codebytere** [comment]
@sohobloo can you please elaborate on the issue? I ran the repro and see this with both 12.0.7 _and_ 15.3.0:

<img width="920" alt="Screen Shot 2021-11-02 at 3 07 56 PM" src="https://user-images.githubusercontent.com/2036040/139863325-b8dce8cd-311d-4d88-8c5d-5d07d8f6a91b.png">

**Comment by codebytere** [comment]
@sohobloo in the meantime - that area of the code was followed by a larger refactor in https://github.com/electron/electron/pull/30663 which fixed it, so v16 and beyond work as expected.

**Comment by codebytere** [comment]
Closing as resolved in supported versions.
