### ISSUE TITLE
Not Opening 

### ISSUE THREAD

**Issue by GamerZingerBurger1** [electron/electron#31660]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

I expected it to open

### Actual Behavior

It didnt open and was just on grey screen

**Comment by marshmello1YT** [comment]
Well, It Happened To Me Too Annoying Isn't It?
