### ISSUE TITLE
[Bug]: accessing window.localStorage in preload script clears localStorage in webviews

### ISSUE THREAD

**Issue by Kilian** [electron/electron#31689]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0-beta.6

### What operating system are you using?

Ubuntu

### Operating System Version

18.04

### What arch are you using?

x64

### Last Known Working Electron version

15.2.0

### Expected Behavior

`localStorage` data is preserved even when accessing `localStorage` in a preload script of a `webview`.

### Actual Behavior

Accessing `localStorage` in the preload script clears out the `localStorage` for the page. 

Subsequent loads without the `localStorage`-accessing code in preload will show the localStorage data has been saved, but as soon as you access `localStorage` in the preload script it will be cleared as far as the page is concerned.

This exists in all 16.x versions.

### Testcase Gist URL

https://gist.github.com/Kilian/a82a276fc842b01c836f8dea14adb6f1

### Additional Information

This fiddle runs 16.0.0-beta.6 though all 16.x versions exhibit this behaviour.

Reproduction steps:

1. Launch the app. The devtools for the webview is opened.
1. In the devtools navigate to the "application" tab, and in the side bar click open "localStorage" under "storage" and select "https://polypane.app".
1. See that it says "polypane-seen-release" with a value. Change that to any other value, and add a random new localStorage entry as well.
1. Close the app and restart it. Navigate back to the applications tab. See that the localStorage value you added is gone, and the "polypane-seen-release" value has been reset (the site sets this on load when empty) - the localStorage has been cleared before load.
1. Close the app again, and now comment out the single line in the preload.js script. 
1. Start the app again. See that your changes from step 3 are now visible.
2. Close the app, uncomment the single line in the preload.js script and restart the app to show localStorage is reset again.

You can repeately do the last three steps and see the results are the same each time. Accessing localStorage in the preload script somehow prevents the actual localStorage data from being available to the page.

You can follow the same steps for 15.x versions and see that step 4 shows the correct localStorage data still.

**Comment by ckerr** [comment]
This works in electron-v16.0.0-nightly-20210803 and is broken in electron-v16.0.0-nightly-20210804.

https://github.com/electron/electron/compare/v16.0.0-nightly.20210803...v16.0.0-nightly.20210804

**Comment by MarshallOfSound** [comment]
Could also be #30311, we should revert whichever change caused it if we can't fix it.  This has happened before and it's _super_ annoying when you don't realize what's happening.  E.g. last time it was in Chromium https://bugs.chromium.org/p/chromium/issues/detail?id=1015126

**Comment by ckerr** [comment]
@MarshallOfSound's guess was right, it is #30311 that broke it. I'll put up a PR to revert since we're getting close to 16.0.0.

Also CC @miniak in case he wants to have another go at this, since 30311 still seems like a good idea IMO

**Comment by miniak** [comment]
@ckerr I will investigate it later and try to re-land the refactoring if I can avoid the regression.

**Comment by rocka** [comment]
This is still happening to me on `electron@16.0.7`, with exactly same reproduction steps (i.e. https://gist.github.com/Kilian/a82a276fc842b01c836f8dea14adb6f1) and behavior.

**Comment by justindarc** [comment]
This is also still happening on every version of 16 as well as `17.0.0`. Any chance this can be re-opened?

**Comment by justindarc** [comment]
A little more detail about this regression as it seems that the issue can be worked around by wrapping the `localStorage` calls in a `setTimeout(fn, 0)`. The fact that a 0ms `setTimeout` is sufficient to work around the problem makes me think there's internally an order of operations regression where the preload script is being incorrectly executed before it should be since this hack essentially moves the `localStorage` access to the next tick of the run loop.

preload.js:
```
// This will incorrectly clear all prior localStorage data:
const foo = localStorage.getItem('foo');

// This will correctly access prior localStorage data as expected:
setTimeout(() => {
  const bar = localStorage.getItem('bar');
}, 0);
```

**Comment by miniak** [comment]
Does it mean that #30311 can be re-landed as it didn't cause the regression?

**Comment by justindarc** [comment]
Oh, I'm sorry. I might be mistaken. I just realized that this issue is specific to `<webview>`. The issue I've observed with this exact same broken behavior is for `BrowserWindow`.

**Comment by vraravam** [comment]
ping for freshness

**Comment by schontz** [comment]
This is still an issue.
