### ISSUE TITLE
[Bug]: Getting an code execution error while 1st launch on double click: "FFMPEG.dll is missing"

### ISSUE THREAD

**Issue by Manunarasingh** [electron/electron#31688]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

7.0.0

### Expected Behavior

app should launch without an any exception 

### Actual Behavior

The user encounters the error when he tries to install an application but the setup fails saying FFMPEG.dll is missing.
<img width="458" alt="exception" src="https://user-images.githubusercontent.com/12546630/140028664-79d80398-68e2-4601-a4ba-518090712be6.PNG">

**Comment by xmsz-stu** [comment]
any update?

**Comment by kevinjterry** [comment]
I'm seeing the same thing.
