### ISSUE TITLE
[Bug]: --js-flags not recognising -r flag from nodejs

### ISSUE THREAD

**Issue by Vishal1419** [electron/electron#31684]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey Version: 12.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Running this command works on nodejs:
`node -r dotenv/config server.js`

So, a similar command on electron should work:
`electron . --js-flags="-r=dotenv/config"`

### Actual Behavior

I am using dotenv for a long time, but today I came across preload. So, I gave it a try on node.js project and it worked fine. Now, I want to do the same in electron project, but passing --require flag is directly not allowed. So, I tried to use --js-flag as mentioned here: https://www.electronjs.org/docs/latest/api/command-line-switches#--js-flagsflags

So, my command looks something like this:
`electron . --js-flags="-r=dotenv/config"`

But I am getting an error:
`unrecognized flag -r:dotenv/config`

**Comment by tim-tx** [comment]
Nothing from `node --help` seems to work in `--js-flags`. The docs suggest looking in `node --help` and `node --v8-options` for things to pass to `--js-flags`. But if you do `electron --js-flags='--help'`, you see what is apparently the output of `node --v8-options` only.

**Comment by joshuafcole** [comment]
Seconding this -- as usage of [package exports](https://nodejs.org/api/packages.html#conditional-exports) becomes more common, not being able to specify user conditions (via the --conditions node option) will negatively impact electron's cross compatibility with the rest of the ecosystem.

**Comment by joshuafcole** [comment]
bump

**Comment by youginil** [comment]
bump.
`npx electron --js-flags="--enable-source-maps" .`
`Error: unrecognized flag --enable-source-maps`
