### ISSUE TITLE
[Bug]: <webview> transparency broken

### ISSUE THREAD

**Issue by miniak** [electron/electron#31686]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.2.0 / 15.3.0 / 16.0.0-beta.6

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

14.0.0 / 15.0.0-beta.2

### Expected Behavior

`<webview>` element should support trasparency. Check the included Fiddle sample.

### Actual Behavior

`<webview>` element transparency is broken

### Additional Information
[webview-transparency.zip](https://github.com/electron/electron/files/7464785/webview-transparency.zip)

<img width="912" alt="Screen Shot 2021-11-03 at 1 55 47 AM" src="https://user-images.githubusercontent.com/1281234/139971477-2077f353-c17c-417f-9f13-9c5c52139efa.png">
<img width="912" alt="Screen Shot 2021-11-03 at 1 55 53 AM" src="https://user-images.githubusercontent.com/1281234/139971481-49f8afa5-3024-46ba-9339-33c492ba3677.png">

Related to:
https://github.com/electron/electron/blob/2a2a1a834c7072226e9368f36fe0d22a125803f0/shell/browser/api/electron_api_web_contents.cc#L1461

It regressed in this ranges:
- https://github.com/electron/electron/compare/v14.0.0...v14.0.1 (probably #30819)
- https://github.com/electron/electron/compare/v15.0.0-beta.2...v15.0.0-beta.3 (probably #30777)

**Comment by miniak** [comment]
The code was also changed by #31003

**Comment by zcbenz** [comment]
Can you check if https://github.com/electron/electron/pull/31685 can fix this?

Also @VerteDinde.

**Comment by miniak** [comment]
@zcbenz it does not fix this particular issue

**Comment by miniak** [comment]
This issue is quite a big blocker for us due to how we use <webview> the bridge our legacy AngularJS based part of the app with new ReactJS based UI

**Comment by miniak** [comment]
@codebytere #31685 is not fixing this bug
