### ISSUE TITLE
[Bug]: BUG that is not available on the Mac 

### ISSUE THREAD

**Issue by daweiyong** [electron/electron#31698]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

All versions

### What operating system are you using?

macOS

### Operating System Version

All Mac

### What arch are you using?

ia32

### Last Known Working Electron version

no

### Expected Behavior

Use a Chinese input method on the MAC, lose the focus, then click Tray to display the client, then enter the text, the text ran to the outside

### Actual Behavior

Use a Chinese input method on the MAC, lose the focus, then click TRAY to display the client, then enter the text, the text ran to the outside

### Additional Information

It is definitely a bug
![image](https://user-images.githubusercontent.com/20884900/140098971-386c22f3-9375-40fb-b5c4-a014eed479b6.png)

**Comment by miniak** [comment]
@daweiyong the title "BUG that is not available on the Mac" is confusing

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
