### ISSUE TITLE
[Feature Request]: Enable or document use of native Windows Spell Checking API

### ISSUE THREAD

**Issue by jeremyspiegel** [electron/electron#31703]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

As Chrome is now using the Windows Spell Checking API, I'm wondering if it's possible to use it in Electron?

I added Finnish (a language that sounds like it won't work with Hunspell: https://bugs.chromium.org/p/chromium/issues/detail?id=783151) on Windows 10 but don't see it in `session.defaultSession.availableSpellCheckerLanguages` in a basic Electron 15.3.0 fiddle. The red underlines in a basic textarea in that app also indicate it's spell checking in English.

The docs at https://www.electronjs.org/docs/latest/tutorial/spellchecker suggest that Electron is expected to still be using Hunspell on Windows.

I tried adding `app.commandLine.appendSwitch('enable-features', 'WinUseBrowserSpellChecker,WinUseHybridSpellChecker');` but that didn't seem to have any effect (though it didn't cause a crash for me as found in https://github.com/electron/electron/issues/25276).

### Proposed Solution

Enable/document use of the Windows spellchecker instead of Hunspell.

### Alternatives Considered

I realize it's possible to disable Electron's built-in spellchecker and `webFrame.setSpellCheckProvider(language, provider)` to implement this outside of Electron, but with it being built into Chrome it seems like something that would make sense for Electron to use.

**Comment by MarshallOfSound** [comment]
The native windows spellchecker is enabled in a "hybrid" way in the exact same way as it would be in Chromium.  Spellcheck requests are sent both to the OS spellchecker and to hunspell.
