### ISSUE TITLE
[Bug]: Trying 16.0.0-beta.6 and remote stopped working

### ISSUE THREAD

**Issue by exander77** [electron/electron#31704]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0-beta.6

### What operating system are you using?

Ubuntu

### Operating System Version

21.10

### What arch are you using?

x64

### Expected Behavior

Remote should work the same way as v 15.

### Actual Behavior

```
node:electron/js2c/renderer_init:73 Error: @electron/remote is disabled for this WebContents. Set {enableRemoteModule: true} in WebPreferences to enable it.
```

**Comment by MarshallOfSound** [comment]
Please do not raise multiple issues across multiple repositories.  The `remote` module is in a separate repo now and raising issues here will not help https://github.com/electron/remote/issues/94
