### ISSUE TITLE
[Bug]: Won't fire input event with Sogou IME and Baidu IME

### ISSUE THREAD

**Issue by asd281533890** [electron/electron#31707]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.3

### What operating system are you using?

Windows

### Operating System Version

window 10 19042.1288

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

Input events like input, keydown, compositionstart, compositionupdate, compositionend would be fired correctly.

### Actual Behavior

Sougou IME:
> Only fire keyup event.
![搜狗输入法](https://user-images.githubusercontent.com/46190356/140269738-88086849-e1bd-42de-beaf-ba72f56e31d7.gif)

Baidu IME:
> Only fire keyup event too.
![百度](https://user-images.githubusercontent.com/46190356/140269845-7006e7c0-fb0c-489e-b1ca-07cf287c96b4.gif)

Microsoft Pinyin IME:
> All input events are fired correctly
![微软拼音输入法](https://user-images.githubusercontent.com/46190356/140269902-dcccd6ea-27fb-4afa-ac6c-71529ff2e69d.gif)

I have tested both in electron 11.4.3 and 15.2.0, and they can all be reproduced.

### Testcase Gist URL

https://github.com/asd281533890/cant_fire_input_event

**Comment by ckerr** [comment]
Hey @asd281533890 I'm a little confused by the version numbers you listed here. You listed 15.2.0 as the 'last known working version' but from  your comment it sounds like you're saying it's broken in both 11.4.3 and 15.2.0.

Does 15.2.0 have this issue as well?

**Comment by asd281533890** [comment]
> Hey @asd281533890 I'm a little confused by the version numbers you listed here. You listed 15.2.0 as the 'last known working version' but from your comment it sounds like you're saying it's broken in both 11.4.3 and 15.2.0.
> 
> Does 15.2.0 have this issue as well?

15.2.0 have this issue as well, I filled in the 'last known working version' wrong, my English is not very good, forgive me.

**Comment by codeingforcoffee** [comment]
I ve got the same question, I use sougou IME's memo(witch using keyboardEvent: paste), works well in v13.6.7, but failed in 14.x and 16.x

**Comment by zhipengzuo** [comment]
it seems sougou pinyin will not send CompositionStart,CompositionEnd event in electron , is there any other option?

**Comment by li-junpeng** [comment]
> it seems sougou pinyin will not send CompositionStart,CompositionEnd event in electron , is there any other option?

I'm the same, have you solved it?
