### ISSUE TITLE
Not Allowed to load local resource. AngularJS

### ISSUE THREAD

**Issue by ijawadkh** [electron/electron#31706]
I have some images in local resource , I am trying to load that images to angularJS page but i am getting the error  "Not Allowed to load local resource" . here is the code below. local resource path is fine.
        <div>
            <button class="btn btn-primary" ng-click="getFile()">Display Image</button>
            
        </div>
        <div></div>
        <div>
            <ul id="grid" class="grid">
                <li class="grid-item" ng-repeat="item in ListOfImages">
                    <img ng-src="{{item.imagePath}}"/>
                </li>
            </ul>
            
            
        </div>

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
