### ISSUE TITLE
[Bug]: getLoginItems returns partial paths for unquoted paths with spaces

### ISSUE THREAD

**Issue by bitdisaster** [electron/electron#31710]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10  19042.1288

### What arch are you using?

x64

### Expected Behavior

Have a registry entry in the HKLM Run key like this:
`C:\\Program Files\\App1\\app1.exe`

call API like this
`app.getLoginItemSettings({ path: `C:\\Program Files\\App2\\app2.exe`, args: [] });`

It should return an empty array.

### Actual Behavior

Have a registry entry in the HKLM Run key like this:
`C:\\Program Files\\App1\\app1.exe`

call API like this
`app.getLoginItemSettings({ path: `C:\\Program Files\\App2\\app2.exe`, args: [] });`

It returns an array with the following object:
```
{
      name: 'App2',
      path: 'C:\\Program Files\\',
      args: [' Files\\App2\\app2.exe'],
      scope: 'machine',
      enabled: true
}
```

### Testcase Gist URL

https://gist.github.com/bitdisaster/07fd945ac87eff9032c91b6fa1e30649

### Additional Information

With unquoted paths, the API is splitting and spaces and assumes the first part is the full path and the rest of the path are arguments. This is also most likely the root cause for issue #31450

**Comment by bavulapati** [comment]
Might be related to  #31960
