### ISSUE TITLE
The vm module of Node.js is deprecated in the renderer process and will be removed

### ISSUE THREAD

**Issue by JonathanLydall** [electron/electron#31724]
As per https://github.com/electron/electron/pull/26087, use of the `vm` module in the renderer process has been deprecated and will be removed.

Our product uses the `vm` module in the renderer quite extensively as we provide a JavaScript API for basic tasks. In particular, that we can pre-populate certain variables / methods is particularly useful.

We are not relying on it as a "sandbox" for security reasons, but it's nice that users can't just access objects like `window`, `document`, `require` as it discourages them from potentially interacting with our app in a way we haven't explicitly decided to support and avoids us having to worry about unintentionally breaking their scripts with some change outside of our API.

Is it possible that instead of this being removed completely, it is instead is unavailable by default and then people like us can choose to opt-in in some way?

Alternatively, can anyone suggest an alternative way for us to achieve a way of exposing a "controlled" global variable scope for user scripts?

**Comment by miniak** [comment]
@JonathanLydall can you share some code how you use to `vm` module to help us understand better what you are doing and how you can refactor possibly refactor it to avoid using `vm`?

**Comment by JonathanLydall** [comment]
@miniak, thanks for your attention, below is a simplified version of how we use it. Also be aware that the `context` object often contains functions which interact with the rest of the SPA running in the renderer process.

```typescript
export class SandboxJavascript {
    private static vm = require("vm");

    private static contextObject: any;
    private static context = SandboxJavascript.vm.createContext(SandboxJavascript.contextObject = {});
    private static cache = new Map<any, { script: any, sourceCode: string }>();

    public static evaluate<TReturn>(stringToEvaluate: string, context: any): TReturn {
        const script = new this.vm.Script(stringToEvaluate);
        return script.evaluateInContext(this.vm.createContext(context));
    }

    public static evaluateWithCaching<TReturn>(stringToEvaluate: string, context: any): TReturn {
        if (!this.cache.has(stringToEvaluate)) {
            let script = null;
            try {
                script = new SandboxJavascript.vm.Script(`(function() { ${stringToEvaluate} })()`);
            } catch (e) {
                console.warn(`Failed to evaluate:\nfunction run() {${stringToEvaluate}}\noutput = run();`);
                console.warn(e);
            }

            this.cache.set(stringToEvaluate,
                {
                    script: script,
                    sourceCode: stringToEvaluate
                });
        }

        const cacheEntry = this.cache.get(stringToEvaluate);

        try {
            const contextObject = SandboxJavascript.contextObject;
            for (const key of Object.keys(contextObject)) {
                delete contextObject[key];
            }

            for (const key of Object.keys(context)) {
                contextObject[key] = context[key];
            }

            return cacheEntry.script.evaluateInContext(this.context);

        } catch (e) {
            console.warn(`Failed to evaluate:\nfunction run() {${cacheEntry.sourceCode}}\noutput = run();`);
            console.warn(e);
            console.debug(context);

            return null;
        }
    }
}
```

**Comment by ckerr** [comment]
What is the timeline for its removal?

**Comment by jjeff** [comment]
Maybe a good compromise would be to add a [fuse](https://github.com/electron/fuses) for this? And/or allow the use of VM in preload?

More background: Right now, many of us are using [Bytenode](https://github.com/bytenode/bytenode) as a way to distribute compiled binaries to obfuscate/protect/hide code in our Electron apps. Here's [an article I wrote about this](https://www.jjeff.com/blog/2021/4/27/creating-javascript-binaries-for-electron). And here's a repository showing an [example Electron build using Bytenode with Webpack](https://github.com/spaceagetv/electron-bytenode-example).

Removing VM in the renderer would negate this method for distributing and loading V8 binaries. I'm not sure what the alternatives would be.

**Comment by petef19** [comment]
+ 100 to be able to use the VM in  preload

**Comment by gpetrov** [comment]
any news on this? Will the vm module be removed in the renderer or not?

It should be at least available in the preload as the rest of the node modules

**Comment by WHK102** [comment]
Any update for this important feature? proprietary applications created in electron will be unsupported.

**Comment by KaKi87** [comment]
Hello,
I've got this warning although I am not directly using a module by that name, how can I find out what's using it ?
Thanks

**Comment by JonathanLydall** [comment]
Yes, this is still an issue.

![image](https://user-images.githubusercontent.com/1290262/194324838-65957ef7-d7e7-4771-9f36-0a11b5a75f15.png)

**Comment by JonathanLydall** [comment]
bump

**Comment by jaredrethman** [comment]
bump

**Comment by gpetrov** [comment]
Bump

**Comment by petef19** [comment]
bump

**Comment by JonathanLydall** [comment]
Bump

**Comment by gputto** [comment]
Bump

**Comment by repeato-qa** [comment]
Bump. We also need a solution.

**Comment by couturecraigj** [comment]
Bump

**Comment by mnn888** [comment]
Bump

**Comment by Stitch-cc** [comment]
bump

**Comment by JonathanLydall** [comment]
bump

**Comment by mnn888** [comment]
bump

**Comment by gittyup2018** [comment]
Why is the vm module being deprecated/removed at all? Is there a replacement? I use 
the bytenode module that actually compiles source code to binary code and runs in the vm and actually
protects the code unlike obfuscation which is basically useless for actual source code protection.

**Comment by JonathanLydall** [comment]
Bump.

**Comment by mnn888** [comment]
bump

**Comment by jjeff** [comment]
Nudge. It feels like people are looking for both:

1. an alternative solution for those of us who are implementing code optimization/obfuscation solutions like Bytenode in the rendering process, **AND**
2. some clarity about whether and when this functionality might actually be dropped from Electron.

Some guidance from the Electron dev team would be much appreciated. Thanks!

**Comment by JonathanLydall** [comment]
Bump.

**Comment by jjeff** [comment]
Nudge. For any Electron dev stumbling across this issue, read here: https://github.com/electron/electron/issues/31724#issuecomment-1967441705

**Comment by gputto** [comment]
Bump.

**Comment by huangxiaobin001** [comment]
When I use the <webview> tag, this warning appears after packaging, and the webview tag is removed

**Comment by cyraid** [comment]
Also wondering about alternative ways for including proprietary code? (other than obfuscation)

**Comment by RitchieMatt** [comment]
Bump

**Comment by samuelmaddock** [comment]
I was not involved in the decision behind adding a deprecation warning, but I do have some insight into why using `vm` is inadvisable within Electron's renderer process. It's relatively easy to find ways to crash your application and not so easy to fix this within Electron.

```js
// run from preload script with `nodeIntegration: true`
require('node:vm').runInNewContext(`
  setTimeout(() => {
    console.log('renderer process will crash before this is logged');
  }, 100);
`, { setTimeout });
```

DOM APIs within [Blink](https://www.chromium.org/blink/) have [metadata](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/bindings/script_state.h;l=27-77;drc=eef993ddb3be1b252bbe542f44da114fd2553c7c) associated with each [v8::Context](https://chromium.googlesource.com/chromium/src/third_party/+/master/blink/renderer/bindings/core/v8/V8BindingDesign.md). When Node creates a new v8::Context (e.g. `vm.runInNewContext`), Blink won't be aware of that context and can thus crash when using certain DOM APIs.

-----

If a new context is needed, the current safe way of accomplishing this in the renderer process would be to use a combination of [contextBridge](https://www.electronjs.org/docs/latest/api/context-bridge) and [webFrame.executeJavaScriptInIsolatedWorld](https://www.electronjs.org/docs/latest/api/web-frame#webframeexecutejavascriptinisolatedworldworldid-scripts-usergesture-callback). Isolated worlds are new v8::Contexts which Blink is aware of and are much less likely to crash given their established use in Chrome extension's architecture.

If the tradeoffs of this approach are insufficient for applications, the Electron team is always open to PRs or [RFCs](https://github.com/electron/rfcs)! 🙇

**Comment by dopry** [comment]
@samuelmaddock I'm okay with that risk and it is important for our product. We should at least have a fuse for this or it should be left alone. We're building desktop apps that don't connect to the web or load external content and shipping with everything signed. That how we address injection related security risks. Future work means nothing for me if electron removes features we need for our app to run without a viable replacement.

**Comment by petef19** [comment]
> @samuelmaddock I'm okay with that risk and it is important for our product. We should at least have a fuse for this or it should be left alone. We're building desktop apps that don't connect to the web or load external content and shipping with everything signed. That how we address injection related security risks. Future work means nothing for me if electron removes features we need for our app to run without a viable replacement.

+ 1, same scenario here

**Comment by JonathanLydall** [comment]
A key aspect of our product is use of "macros" (powered by the VM module) for users to arbitrarily extend the product's behaviour within the scope of what our "macro" API allows. As our product uses local only content, there is no security concern, but we do want to deter users from using "unsupported" ways of interacting with our product such that we remain free to change all other aspects of our it without fear of breaking user scripts.

What we particularly like about the VM module is that it allows us to control what's available on their "global scope" allowing us to essentially have a facade where user scripts work against our blessed API which we ensure remains consistent between updates to our product, while we free to change the implementation of said interfaces however we see fit.

Another benefit is not exposing certain functionality that users should absolutely not be using (like being able to interact directly with the DOM), so that we are able to change the DOM between product versions without fear of breaking user scripts. This is not for security reasons, just for deterring users from interacting with our product in unsupported ways.

If there is an alternative way for us to achieve the same thing, then I'm not particularly attached the VM module, otherwise, it's essential to our product that it remains available, despite potential risks.

**Comment by JonathanLydall** [comment]
Bump.

**Comment by mnn888** [comment]
Bump

**Comment by gpetrov** [comment]
Bump

**Comment by samuelmaddock** [comment]
Hey folks, I've updated the warning to now state:

> The vm module of Node.js is unsupported in Electron's renderer process due to incompatibilities with the Blink rendering engine. Crashes are likely and avoiding the module is highly recommended. This module may be removed in a future release.

It's no longer considered deprecated. However, if the module ends up causing issues for normal usage of Electron, we're reserving the possibility of removing it.

For developers depending on the `vm` module in the renderer process who are concerned with the possibility of removal, I'd encourage looking into whether the [ShadowRealms proposal](https://github.com/tc39/proposal-shadowrealm) might work for your project. It has limited support in Chromium/Electron already and can be tested by adding a command line flag:
```js
app.commandLine.appendSwitch("js-flags", "--harmony-shadow-realm");
```

Otherwise, interested contributors could also investigate what it would take to make the `vm` module compatible with Blink such that crashes wouldn't occur. The [Design of V8 Bindings](https://chromium.googlesource.com/chromium/src/third_party/+/master/blink/renderer/bindings/core/v8/V8BindingDesign.md) guide would be a good starting point for that.

Hope this helps clear things up!

**Comment by gizzye** [comment]
It seems ShadowRealms doesn't support CJS so here's a base you can expand on. It creates an iframe to get a new context.

```javascript
Context = function (_global = {}) {

    let iframe = document.createElement('iframe');
    document.head.appendChild(iframe);

    for (let k in _global)
        iframe.contentWindow[k] = _global[k];

    return new Proxy(function (code) {
        return iframe.contentWindow.eval(code);
    }, {
        get: function (T, K, R) {
            return iframe.contentWindow[K];
        },
        set: function (T, K, V) {
            return iframe.contentWindow[K] = V;
        }
    });
};

context = new Context({
    require: require,

    // what's global in our context will automatically be exported to renderer process context, you can remove if you don't need it
    global: new Proxy({}, {
        get: function (T, K) {
            return global[K];
        }, set: function (T, K, V) {
            global[K] = V;
            return context[K] = V;
        }
    })
});

context.a = 1;
context.b = 2;

// don't forget //# sourceURL 
console.log(context('console.log(a + b); //# sourceURL=test.js')); // 3```

**Comment by fpaut** [comment]
Hi,

Maybe not related, but similar with Advanced Rest Client when trying to export data. Screen become empty, and developper tool notify "The vm module of Node.js is deprecated in the renderer process and will be removed".

![Image](https://github.com/user-attachments/assets/b019bb87-f69b-495d-b8b3-af81588d5cc2)

Tryed to update nvm / nodejs v23.10.0 but no improvement

**Comment by uplg** [comment]
> If you use `require('node:vm')` instead of just `require('vm')` then you won't get this warning any longer.

This is clearly a hackfix, the "vm" check is there but not handling this because it's just an informative warning, and suppressing it by changing the import string is just hiding something under the carpet, not fixing it, so if that happens to break, you will have to understand why (if it's you, you may recall, but someone else, no.)

The question is basically this, vm bytecode may be used for code protection (but don't provide that much protection), bytecode in preload might not be needed as it's mostly "wiring". And ShadowRealm is mostly to "handle" the "separation/make hard to access" part, not at all tiny code protection.
