### ISSUE TITLE
How I can get result of event in browserView?

### ISSUE THREAD

**Issue by silvathebest** [electron/electron#31725]
How I can get result of event in browserView?
I have: 
```javascript
browserView.webContents.injectedScript('
  let btn = document.createElement("button")
  btn.innerHTML = "Click Me"
  btn.addEventListener("click", function () {
    return "Button is clicked"
  })
  document.body.appendChild(btn)
').then(r=> console.log(r))
```
What I need to do to get "Button is clicked" after click on button in main process and add to variable?

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
