### ISSUE TITLE
[Bug]: app.relaunch() fails to restart app - It only exits.

### ISSUE THREAD

**Issue by alex-drocks** [electron/electron#31726]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19043	

### What arch are you using?

x64

### Last Known Working Electron version

15.2.0

### Expected Behavior

app.relaunch() should restart the Electron application as expected.

### Actual Behavior

The application only quits. It does not relaunch the app as it should.

### Testcase Gist URL

https://github.com/alex-drocks/electron-15.3.0-win10-x64-app-relaunch-fails

### Additional Information
For documentation I read this: https://www.electronjs.org/docs/latest/api/app#apprelaunchoptions

I have a production build using Electron v15.2.0 in which the app.relaunch() function still works as expected.
I also tried to use Electron v16 beta to see if it was fixed later in beta releases.

Testcase URL is a copy of the `electron-quick-start` where I jsut added a button in the renderer process to trigger the app.relaunch() function.

**Comment by alex-drocks** [comment]
Please note that I tried packaging my electron app and it DOES work when packaged! Wierd.

**Comment by baconbrad** [comment]
I have cloned and tested your testcase and I am getting the expected behavior on 15.3.0. Does your packaged version still work in the same directory as your Electron dependency `dist` directory?

**Comment by alex-drocks** [comment]
I'm not sure I understand what you mean by the same directory because when packaged it goes into the "out" dir by default with Electron Forge. So I suppose, it is a completely different folder than in dev mode.

Although I can confirm, that it works correctly on my Mac...

I'll do some more testing on my windows machine, but I have already tried deleting the node_modules completely. I'll post back when I have more info. Thank you

**Comment by alex-drocks** [comment]
So I've tried a clean install of npm dependencies again. Then, messed around in the node_modules/electron/dist folder as I was trying to figure out what you meant. I tried placing my packaged .exe file beside the electron.exe file in the dist folder and tried running that without success. I don't see why it would have been useful.

I can now confirm these things:
- on Mac the app.relaunch works as expected in dev mode and also in production builds.
- on Windows, app.relaunch only works in production builds but not in dev mode.

**Comment by alex-drocks** [comment]
I found the problem: 
It is caused by a third-party electron library named "electron-reloader"

```Javascript
//auto-reload on save
if (isDev) {
    try {
        // You have to pass the module object so we can read the module graph and figure out which files belong to the main process.
        // The try/catch is needed so it doesn't throw Cannot find module 'electron-reloader' in production.
        require('electron-reloader')(module);
    } catch {
        //return
    }
}
```

If I comment out the previous lines, the app.relaunch works perfectly.

**Comment by alex-drocks** [comment]
I found why it was doing that. For some reasons, the number of default arguments in proccess.argv seems to have changed in some Electron version.

I was doing app.relaunch({args: process.argv.slice(1).concat([--myarg])});
Then in my startup script of the main process, I was referencing the second argv in the array which was not valid anymore.

I solved it by fixing my argv array index referencing.

Now i use this:  app.relaunch({args: [activeFdFolder.key]});

I also notived that even if I pass an empty array like so : app.relaunch({args: []}); the argv[0] is always going to be the executable path

**Comment by azwalzaman** [comment]
I'm facing the same issue. The app reloads in production but not in development. I'm using Electron `23.2.1` with Electron Forge

**Comment by juxnpxblo** [comment]
same issue here in electron 22.2.0 with electron-forge. it was working until just recently.

restarting works fine on prod, but in dev the application never comes back (although I can still see some electron processes running on task manager, and I am unable to npm start my app again until I manually close them)

```
export const restart = () => {
  app.relaunch();
  app.exit();
};

app.on('window-all-closed', () => {
  app.quit();
});
```
