### ISSUE TITLE
[Feature Request]: Propagate abort of AbortSignal from renderer to main

### ISSUE THREAD

**Issue by xmedeko** [electron/electron#31737]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I use electron with context isolation. The render process (`BrowserWindow`) invokes some abortable code (`fs, child_process.exec, fetch, ...`) in the main process by IPC. I would like to have an Abort button in the `BrowseWindow` which would be able to abort the code running in the main process.

### Proposed Solution

I would like to send `AbortSignal` by `ipcRenderer` and got it (or some proxy of it) by `ipcMain`. When the renderer process invokes `AbortController.abort`, then I expect the signal in the main process fires `aborted` event, too.

### Alternatives Considered

I've created workaround code which generates a GUID for AbortSignal in the renderer process, and render communicated with the main process with that signal GUID.  The main process creates it's own AbortController for every new signal GUID. (GC is handled by `FinalizationRegistry`). I may provide it if you are interested.

**Comment by xmedeko** [comment]
@miniak Yes, I've made a solution already, see **Alternatives Considered** in the original post. Peeking at the `remote` module it's a bit similar solution. (But no need to set up anything).

AFAIK either my solution or digging in `remote` is not simple and it would be **much more convenient** do have something build in.

Maybe some kind `ObjectRegistry` either build in or as a separate, safe module?

**Comment by grafanauser** [comment]
remote module should not be used anymore. It would be nice to have a solution for this without having to rely on complex workaround like tracking multiple requests and their abort signals via multiple ipc calls.
