### ISSUE TITLE
[Feature Request]: provide a way to compile from tar balls instead of git checkouts

### ISSUE THREAD

**Issue by TimB87** [electron/electron#31736]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am compiling electron on CRUX (linux) for a while now, however, having to pull git repositories is not really convenient.

There are no instructions to build from tar balls, just from git checkouts, so my understanding that this is currently not supported?

### Proposed Solution

Provide instructions and prepare the repository to be built stand alone from tar balls, not including git repositories.

### Alternatives Considered

I store a checkout for chromium and electron over nfs on a zfs pool. This is however very unperformant and requires a lot of work on the ports maintainers side, also we don't use git for our ports so this is no way near possible to put into an official repository that way.
This is just a work around to get it compiled and working, a real soltuion would be to have tar balls that actually allow you to build it, too (chromium works from a tar ball, why not electron?)

### Additional Information

I dunno, let me know if I can provide more information, but please consider doing that, electron is the only port out of around 1000 that I maintain which absolutely needs a git checkout to be compiled from.

CRUX is a source based distribution. While packing the binary version certainly would work I still prefer to build it myself.

**Comment by ckerr** [comment]
Hi @TimB87,

I usually don't close tickets out-of-hand but I think it makes sense here because of the combination of this being a pretty limited use case _and_ the incredible complexity involved with building Chromium from a source tarball. If you're building it already you understand how large the codebase is -- I don't know if one could just tar it up after the `sync` step and expect it to work right after tarring/untarring.

You might ask around in [the Electron Discord](https://discord.com/invite/electron) and see anyone there has tried something similar?

Good luck!

**Comment by TimB87** [comment]
Hi @ckerr 
Thanks for taking the time to reply!

I totaly understand your points and will try to seek help at the discord channel.

Maybe this could still be a long term goal..? 
I feel like it would help most linux distros (and thus, more people than obvious at first glance) to get a better electron package and avoid hacks like storing git checkouts.
