### ISSUE TITLE
[Bug]: On macOS my Electron application windows appear to not be showing at retina resolution

### ISSUE THREAD

**Issue by simonw** [electron/electron#31775]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

My application should render at retina resolution on my MacBook Pro

### Actual Behavior

My application appears to be rendering at half of retina resolution - it looks blurry. Here's a screenshot:

<img width="1056" alt="Datasette__temporary__plugin_directory_and_New_Issue_·_electron_electron" src="https://user-images.githubusercontent.com/9599/140993047-12518d5a-0ddb-4c9f-ac7d-3ccf752aa057.png">

### Additional Information

My application can be downloaded from https://datasette.io/desktop

It is open source - the full Electron application source code is available at https://github.com/simonw/datasette-app

**Comment by miniak** [comment]
That's weird, Electron has supported Retina displays on Mac for a very long time. I've just tried your app on the 2019 16" MacBook Pro on Catalina 10.15.7 (19H1519) and it works correctly.

**Comment by miniak** [comment]
It can only reproduce it when set this manually via Get Info in Finder
<img width="377" alt="Screen Shot 2021-11-10 at 12 24 38 AM" src="https://user-images.githubusercontent.com/1281234/141021720-8d3d474e-4f40-44c9-893b-0e0d71a556ab.png">

**Comment by ckerr** [comment]
> It can only reproduce it when I set Open in Low Resolution manually via Get Info in Finder

@miniak if you can reproduce this, could you fire up a test gist in Electron Fiddle and walk backwards to see when this issue was introduced?

**Comment by simonw** [comment]
Huh - on my computer that option was indeed checked. I have no idea why, I didn't even know it was an option!

Maybe I somehow managed to toggle it with keyboard shortcuts at some point.

I'm closing this issue - I'll re-open it if I get any reports from my users that they are seeing the same behaviour, but it looks to me like this was a problem that was unique to my computer.
