### ISSUE TITLE
[Bug]: Flicker when changing BrowserView

### ISSUE THREAD

**Issue by Hans-Halverson** [electron/electron#31776]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6

### What arch are you using?

x64

### Last Known Working Electron version

13.6.1

### Expected Behavior

Changing BrowserViews (due to a call to `browserWindow.setBrowserView`) should switch views without flickering.

Video of BrowserView not flickering in 13.6.1:

https://user-images.githubusercontent.com/17801728/140996046-473ab166-212c-4463-bd4d-d803d13a9aca.mp4

### Actual Behavior

BrowserView flickers/flashes white when changing BrowserViews.

Video of BrowserView flickering when changing BrowserViews (or calling setBrowserView with the existing BrowserView):

https://user-images.githubusercontent.com/17801728/140996553-807db1c8-ebae-4161-9d98-6607ac0a012c.mp4

### Testcase Gist URL

https://gist.github.com/Hans-Halverson/2f2153d357502845ff6d39fb7b224a36

### Additional Information

I tracked this down further in Electron Fiddle and it appears to have been introduced between `v14.0.0-nightly.20210519` and `v14.0.0-nightly.20210520`. A likely culprit is [the commit](https://github.com/electron/electron/commit/039f3d5cd29711a623894fdbae036f28b5cb8c63) in this range for upgrading the chromium version.

**Comment by mckravchyk** [comment]
On Linux it seems to not occur. I have not noticed it either in my app or in the fiddle, version 15.2.0

However, there's flicker (on Linux) if the BrowserView is added / rendered for the first time.  So in a browser-like application, if a tab was opened in the background, it would flicker once when switching to it for the first time.
