### ISSUE TITLE
can we have dockable developer tool bar for webview in atom - Browser-Plus

### ISSUE THREAD

**Issue by skandasoft** [electron/electron#3177]
I found it will be nice to have a dockable developer toolbar when using the webview. Here is the issue raised in browser-plus(atom package)

https://github.com/skandasoft/browser-plus/issues/40

**Comment by zcbenz** [comment]
It is not possible with what we have now, in Chromium the webview is implemented as a browser plugin, and the docked devtools is implemented as native view, there is no way to mix them up.

**Comment by zcbenz** [comment]
I'm reopen-ing this since there are popular requests on this feature.
