### ISSUE TITLE
[Feature Request / Documentation]: How to diagnose memory issues?

### ISSUE THREAD

**Issue by Scalahansolo** [electron/electron#31770]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

My team and I are starting to work through some high memory usage issues that we're having with our application. While searching around the net on how to bet identify and start to deal with high memory in Electron, I have come up mostly empty on where to get started. I have also asked this question over on SO without much success.

https://stackoverflow.com/questions/69827243/how-to-properly-debug-electron-memory-issues

Without going to that post... The crux of the issue is that my app shows it's using significantly more memory that what is showed within the Chrome dev tools. Not only that, but my app's memory grows over time, which indicates a leak somewhere. 

Obviously there are many apps out there that perform really well running on electron, but how they got to that point is mostly a black box.

### Proposed Solution

Improved documentation and/or tooling for addressing address high memory issues / memory leaks within Electron. 

### Alternatives Considered

In this case, I would've hoped that there would be blog posts / other SO posts on this topic, but have come up short there.

**Comment by Scalahansolo** [comment]
That all sounds good. I'll jump into the Discord and see what I can find / ask there. 

With that said, I've read those docs, and they are a good starting point. I guess the biggest concern I have is... why does the Chrome Devtools memory page show a JS heap size that is so significantly smaller than what would be shown in something like Activity Monitor?

**Comment by mfranzs** [comment]
Hey @Scalahansolo - did you ever find a solution to your question about the discrepancy between the JS heap size usage vs the Activity Monitor usage? Pointers would be highly appreciated!
