### ISSUE TITLE
[Bug]: webContents.executeJavaScript will never execute/fail when no content has been loaded.

### ISSUE THREAD

**Issue by markleutloff** [electron/electron#31792]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2

### What arch are you using?

x64

### Expected Behavior

Promise returned by webContents.executeJavaScript should be rejected when no content has been loaded.

### Actual Behavior

Promise returned by webContents.executeJavaScript will not fail when no content has been loaded. 
The promise will  only then succeed or fail once content has been loaded.

### Additional Information

When a window has been opened and **no content** has been loaded yet (dom-ready event has not been fired, no loadUrl, or similar has been called), all executeJavaScript calls will wait until the content has been loaded.

Which is a problem as the Promise returned by executeJavaScript will not resolve or reject until the content is ready.
I would expect an immediate rejection or an exception to be thrown.

Workaround for this is to wait for the dom-ready or similar event to fire and only then use executeJavaScript.

**Comment by MarshallOfSound** [comment]
What you consider unexpected behaviour is currently explicitly intended behaviour.  If you want to know if the page is loaded before calling `executeJavaScript` you will have to determine that state yourself via events

**Comment by asd281533890** [comment]
- Workaround 1:
  In the preload of the webcontents: ```ipcRenderer.on('channel', () => { ... })```. In the main process: ```webcontents.send('channel')```.

- Workaround 2:
  In the main process: ```webcontents.loadURL('javaScript:window.xxx()')```. If the webcontents type is webview, you can use ```webview.src = javaScript:window.xxx() ``` in the render process.
