### ISSUE TITLE
Cache paths aren't consistent with `docs/tutorial/installation.md`

### ISSUE THREAD

**Issue by donaldnevermore** [electron/electron#31790]
In `docs/tutorial/installation.md#custom-mirrors-and-caches` it says, "A typical cache might look like this":

```
├── httpsgithub.comelectronelectronreleasesdownloadv1.7.9electron-v1.7.9-darwin-x64.zip
│   └── electron-v1.7.9-darwin-x64.zip
├── httpsgithub.comelectronelectronreleasesdownloadv1.7.9SHASUMS256.txt
│   └── SHASUMS256.txt
```

But when I install Electron v15.3.1, the cache looks like this:

```
├── 523ee27feac8b931299c79e78b7ca4f365aa3f7069fff666cae93c7fb9ff2fee
│   └── electron-v15.3.1-win32-x64.zip
```

When did this change happen? Should we address this in the docs?

**Comment by donaldnevermore** [comment]
OK, I'll do it.

**Comment by thiwatx33** [comment]
https://github.com/electron/electron/issues/31790#issue-1050609780
