### ISSUE TITLE
[Bug]: Transplant to the Uos system(under aarch64),the renderer crash.

### ISSUE THREAD

**Issue by RubberFeng** [electron/electron#31793]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.0.2

### What operating system are you using?

Other Linux

### Operating System Version

20

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

no

### Expected Behavior

renderer run normally

### Actual Behavior

electron run the main.js,and renderer crash soon!
[coreuos-PC1636622098.zip](https://github.com/electron/electron/files/7519497/coreuos-PC1636622098.zip)

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `12.x.y`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
