### ISSUE TITLE
[Bug]: Visual glitches with frameless windows while screensharing

### ISSUE THREAD

**Issue by mkarp** [electron/electron#31807]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.1

### What operating system are you using?

macOS

### Operating System Version

12.0.1

### What arch are you using?

x86 (Intel)
arm64 (including Apple Silicon)

### Expected Behavior

I expect an Electron app to always render the latest content while screensharing in Zoom.

### Actual Behavior

What happens is that content is partially drawn in an Electron window. Some areas of the window show the up-to-date content, while others seem to show the previous state.

* The issue resolves itself with the next event that causes the app to redraw (user interaction, remote sync event etc.)

* It happens only while screensharing. I can reliably reproduce it while screensharing in Zoom, and our customers reported the same behaviour with Microsoft Teams and Google Meet.

* It happens only in a frameless Electron window. We can't reproduce this issue with the same application running in a window with a default macOS title bar.

I've recorded a video demo to help showcase the issue.

[![Electron frameless window issue when screensharing](https://img.youtube.com/vi/JrrInNTNN00/0.jpg)](https://www.youtube.com/watch?v=JrrInNTNN00)

Please check https://github.com/mkarp/electron-screensharing-issue-demo for a demo Electron project and more information.

### Testcase Gist URL

https://github.com/mkarp/electron-screensharing-issue-demo

**Comment by codebytere** [comment]
@mkarp do you have any information around how long this has been happening? e.g. ha this ever worked for you or did you only notice it after an upgrade at some point?

**Comment by mkarp** [comment]
@codebytere First time our users have reported it around November 2020, so a year ago. We've been on either Electron 9 or 11 at that point, it's difficult to recall exactly which version. It was around the same time we launched our app publicly and got real-world usage, so I can't tell whether a particular update caused it because we have no real data before that 😞.

**Comment by mkarp** [comment]
I've tried to use Quart Debug with this issue, and it seems like the frameless window doesn't get repainted. Check out this gif: when I click on the last orange slide, the click is registered (you see a circle around the mouse pointer), however the app doesn't respond and there's no yellow flash; when I hover over the system scroll bar, then the window is repainted and you see a yellow flash.

![2021-11-12 16 41 57](https://user-images.githubusercontent.com/318902/141494398-d1dc381b-ee84-4b17-acd2-e029b0121860.gif)

**Comment by mkarp** [comment]
We've hacked a temporary "fix" by adding an almost transparent 1x1px block that flickers every 250ms and causes the window to repaint. It's very hacky, but works as a workaround for now. 

For a demo, I've added a slightly larger red rectangle that flashes every 5 seconds, in the end of this gif you can see here how it resolves a glitch:

![2021-11-12 18 08 48](https://user-images.githubusercontent.com/318902/141518850-ecbfa4af-8436-42c0-b711-3d8b46aac25d.gif)

**Comment by JohnWeisz** [comment]
If it helps, I didn't see this issue in 12, but seeing it in both 16 and 17.

OS is Windows 10.

**Comment by JohnWeisz** [comment]
In my case, disabling GPU rasterization fixed the problem, without noticeable performance loss:

```
// main process
app.commandLine.appendSwitch("disable-gpu-rasterization");
```

The flags `disable-gpu-compositing` or just simply `disable-gpu` also fix it, but they come at a noticeable performance cost if your app is heavy on visuals.

**Comment by qroft** [comment]
I am having a similar problem, though my hardware is "slightly" different :)
So i am working on a Raspberry Pi 400 creating my first Electron app on it.

It is a simple web browser that calls a remote website.
At the start, the website renders perfectly.
But it has an other sub-page that has no background-color defined in its CSS because i want it to be transparent.

**When i call that sub-page, there where transparency is, you can see the content from the first page.**

Even with the stuff suggested in here, i could not put it to work.
But at least i am now very sure that it has to be something with the way that the computer / Raspberry renders stuff.

I will now see if i can use other flags to see if i find a workaround.

**Comment by JohnWeisz** [comment]
bump - still not fixed
