### ISSUE TITLE
[Bug]: ipcRenderer.sendSync() with 'REMOTE_BROWSER_GET_BUILTIN' channel without listeners

### ISSUE THREAD

**Issue by seb-mtl** [electron/electron#31809]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

8.5.5

### Expected Behavior

I expect the application to start up.

### Actual Behavior

During the startup, I execute the following code in the renderer process:

```typescript
    import { app } from '@electron/remote';
    [...]
    const path: string = app.getPath(name);
```

The app freezes and prints this error message into the `Main` log

```
WebContents #1 called ipcRenderer.sendSync() with 'REMOTE_BROWSER_GET_BUILTIN' channel without listeners.
<node_internals>/electron/js2c/browser_init.js:161
```

These are the web preferences of my `BrowserWindow` in the main file:

```
    webPreferences: {
      devTools: isDebugVersion,
      webSecurity: false,
      contextIsolation: false,
      nodeIntegration: true,
      nodeIntegrationInWorker: false,
      nativeWindowOpen: true,
      allowRunningInsecureContent: !!(serve),
      scrollBounce: true,
      webviewTag: true
    },
```

**Comment by miniak** [comment]
https://github.com/electron/remote#api-reference

**Comment by Alexie81** [comment]
Thanks, but please resolve this bug... if you can.

**Comment by Modjular** [comment]
If you're coming from before v14.x.y, `@electron/remote` has to be installed separately now, and there are a few more initializations to do in the main process:

```javascript
  // from Main process
  import * as electron from 'electron';
  import * as remoteMain from '@electron/remote/main';
  remoteMain.initialize();
  // ...

  const window = new electron.BrowserWindow({
    webPreferences: { 
      plugins: true, 
      nodeIntegration: true, 
      contextIsolation: false,
      backgroundThrottling: false,
      nativeWindowOpen: false,
      webSecurity: false 
    } 
    // ...
  });

  remoteMain.enable(window.webContents);
```

Credit: https://stackoverflow.com/a/69297584/5530689

**Comment by Alexie81** [comment]
Hello! This is the best solution for thia probdlem! It is working ! Thx

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 25, 2022 at 22:25, Tony ***@***.***> wrote:   


If you're coming from before v14.x.y, @electron/remote has to be installed separately now, and there are a few more initializations to do in the main process:
  // from Main process
  import * as electron from 'electron';
  import * as remoteMain from ***@***.***/remote/main';
  remoteMain.initialize();
  // ...

  const window = new electron.BrowserWindow({
    webPreferences: { 
      plugins: true, 
      nodeIntegration: true, 
      contextIsolation: false,
      backgroundThrottling: false,
      nativeWindowOpen: false,
      webSecurity: false 
    } 
    // ...
  });

  remoteMain.enable(window.webContents);
Credit: https://stackoverflow.com/a/69297584/5530689
