### ISSUE TITLE
[Bug]: Mouse cursor is freezing for few milliseconds when show transparent window (on an integrated GPU)

### ISSUE THREAD

**Issue by Maqsim** [electron/electron#31802]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.2.0

### What operating system are you using?

macOS

### Operating System Version

12.1 Beta (21C5021h)

### What arch are you using?

x64

### Expected Behavior

Window should be shown and mouse cursor doesn't get freezing at that moment

### Actual Behavior

I have a overlay window with this options:
```
overlayWindow = new BrowserWindow({
    alwaysOnTop: true,
    y: 0,
    x: 0,
    width: display.bounds.width,
    height: display.bounds.height,
    frame: false,
    show: false,
    transparent: true,
    roundedCorners: false,
    webPreferences: {
      sandbox: true,
      nodeIntegration: false,
      contextIsolation: true,
      preload: OVERLAY_WINDOW_PRELOAD_WEBPACK_ENTRY
    }
  });
```

Later, on some event I do show this window via `.show()` and exactly at that moment my mouse cursor gets freezing for few milliseconds. 

**Interesting note:** The freezing duration relates to size of the window. If i create 20x20 px window then all goes well. I think it depends on how many 'transparent' pixels Electron renders. If I have transparent window, but with non-transparent html body background it works as expected.

### Temporal solution
Putting `app.disableHardwareAcceleration();` reduces freezes significantly

### Additional Information

I have the old 2015 macbook pro 13" with Intel Iris Graphics 6100 1536 MB

That's why disabling hardware acceleration helps a little bit.

**Comment by Deuscx** [comment]
same issue. any update?
