### ISSUE TITLE
Disable flag on chromium enable-table-ng 

### ISSUE THREAD

**Issue by sturla78** [electron/electron#31810]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hello,
i have update the electron app to the latest version, and i have discovered a strange behavior with the table border, some line of the table are displayed with different size. Searching on internet i have discovered that setting the flag enable-table-ng to false resolve the issue (i have test on chrome using chrome://flags/#enable-table-ng).

There is similar workaround that can be apply to the electron app ? I have search in the command line capability https://github.com/electron/electron/blob/main/docs/api/command-line-switches.md  but this setting is not present.

Thanks in advance.

### Proposed Solution

Possibility to set the flag enable-table-ng when using electron app

### Alternatives Considered

Alterative way in order to display correctly the border size of the tables.

**Comment by miniak** [comment]
looks like this flag is going away in Chromium 96
https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/flag-metadata.json;l=2697-2699?q=enable-table-ng&ss=chromium

**Comment by sturla78** [comment]
Thanks miniak for the info. 
This means that i must wait a fix on the chromium side ? There isn't the possiblity to access to the chromium flags using electron ?
