### ISSUE TITLE
Window frame is ignored when calculating window size on Linux

### ISSUE THREAD

**Issue by Tyriar** [electron/electron#3183]
On Ubuntu 15.04
`mainWindow = new BrowserWindow({width: 800, height: 600});`
and
`mainWindow = new BrowserWindow({width: 800, height: 600, 'use-content-size': true});`
create a window of the exact same size on Ubuntu. This is incorrect according to the [API docs for BrowserWindow](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions):

> - use-content-size Boolean - The width and height would be used as web page's size, which means the actual window's size will include window frame's size and be slightly larger.

**Comment by zcbenz** [comment]
On Linux the window frame is drew by window manager and X Window just ignored window frame when doing size related operations. So it is a mess to make things right around window frame and current we just ignored that in Electron.

**Comment by codebytere** [comment]
Closing due to abandonment.
