### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 4ebupelya** [electron/electron#31835]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

idk

### Expected Behavior

does not start

### Actual Behavior

Dontdoes not start

### Additional Information

![image](https://user-images.githubusercontent.com/94371118/141784696-a0a9291f-5ac4-4298-a35f-3b1e6fd53d48.png)
help

**Comment by ckerr** [comment]
Hi @4ebupelya,

This appears to be a bug report about Discord Bot Client 3.1.0, which _is_ an app that uses Electron, but you'd probably be better off reporting this to the developers / maintainers of that app. 

Good luck!
