### ISSUE TITLE
[Bug]: window.webContents.send causes flickering command line windows when app is focused

### ISSUE THREAD

**Issue by PurpleHorrorRus** [electron/electron#31866]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Insider Build

### What arch are you using?

x64

### Last Known Working Electron version

15.3.1

### Expected Behavior

No command line windows should appear after loading and emitting data to render process.

### Actual Behavior

Strange command line windows open and close instantly after window.loadURL and a single emit with window.webContents.send when the application window has focus. 

### Additional Information

```javascript
const window = new BrowserWindow(params);
window.show();
window.loadURL("http://localhost:3000");
window.webContents.send("any-event-name");
```

**Comment by quanglam2807** [comment]
I encountered the same problem with Windows 11.

**Comment by liuxini** [comment]
I had the same problem on Windows 10 with electron 16.0.5
