### ISSUE TITLE
[Bug]: Vibrancy + Transparent background still broken on macOS on 16.0.0

### ISSUE THREAD

**Issue by theolivenbaum** [electron/electron#31862]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.0.1

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

Window does not have a white background when vibrancy is set to under-window + transparent background is used on macOS

### Actual Behavior

Window with vibrancy and transparency enabled is rendered with a white background, at random

### Additional Information

We're still hitting random issues with Electron where creating a window with vibrancy + transparent body will result in a white background. I was hopeful that the 16.0.0 release would have fixed this as it was mentioned in the changelog, but seems like the issue persists.

I've tried to narrow down to a reproducible case, but didn't manage to do so - I've observed all these variations across executions:

- Window opens with correct vibrancy effect, and it works without issues
- Windows opens with correct vibrancy effect then goes white after ~4 seconds - consistently after ~4 seconds
- Window opens with correct vibrancy, stays without issues, but loses after some time of switching between apps
- Windows open with effect already not working and a white background

I've already tried all suggestions from previous issues like #30993 or #31461 . The window is created with vibrancy set to under-window, has a transparent background and the webpreferences also has a transparent background set. As it works sometimes, I assume the options here are correct.

My guess is that this is somehow related to #31019: Electron is using somehow the background color of the HTML body. As we initially load the window with about:empty, then navigate to our url, the transparent background logic might be loading the incorrect background color at random times and breaking the transparency/vibrancy effect from there on. 

I also don't know if #31722 is already merged on the 16.0.0 release - happy to test if not the case once it is again!

**Comment by theolivenbaum** [comment]
Managed to reproduce it here: https://gist.github.com/theolivenbaum/db9f93cf9aa4e8d1e7a5c879f1d745cc

**Comment by codebytere** [comment]
This issue has changed behavior as of https://github.com/electron/electron/compare/v17.0.0-beta.2...v17.0.0-beta.3, which i narrowed down further to the Chromium roll. It now won't change to transparent _at all_, instead staying green for the duration.
