### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by prats-dev** [electron/electron#31872]
Just installed a MacOS Disk tool called Space Radar, and its icon is utterly similar to Electron JS icon..
<img width="102" alt="Screen Shot 2021-11-17 at 10 37 21" src="https://user-images.githubusercontent.com/89698602/142165727-ac8360b0-b93f-4d51-82fb-76f8566eed86.png">
.

**Comment by codebytere** [comment]
@prats-dev yes - that's what happens when someone makes an Electron app and doesn't change the default logo.
