### ISSUE TITLE
[Bug]:  renderer process crashed on Windows 7

### ISSUE THREAD

**Issue by oppo-flow** [electron/electron#31873]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.14

### What operating system are you using?

Windows

### Operating System Version

window7  (Windows 6.1.7601)

### What arch are you using?

ia32

### Last Known Working Electron version

12.0.0

### Expected Behavior

This process does not crash 

### Actual Behavior

The rendering process crashed.

OS Version: Windows 6.1.7601 (24441)
Report Version: 104

Crashed Thread: 12492

Application Specific Information:
Fatal Error: EXCEPTION_BREAKPOINT

Thread 12492 Crashed:
0   TeamTalkNew.exe                 0x1d79175           logging::LogMessage::~LogMessage (logging.cc:885)
1   TeamTalkNew.exe                 0x530b6a1           blink::ReportFatalErrorInMainThread (v8_initializer.cc:95)
2   TeamTalkNew.exe                 0x4539ddd           v8::Utils::ReportApiFailure (api.cc:504)
3   TeamTalkNew.exe                 0x3d8c561           [inlined] v8::Utils::ApiCheck (api.h:144)
4   TeamTalkNew.exe                 0x3d8c561           v8::V8::ToLocalEmpty (api.cc:1062)
5   TeamTalkNew.exe                 0x34c921d           [inlined] v8::MaybeLocal<T>::ToLocalChecked (v8.h:10953)
6   TeamTalkNew.exe                 0x34c921d           blink::V8ContextSnapshotImpl::CreateContext (v8_context_snapshot_impl.cc:364)
7   TeamTalkNew.exe                 0x1c81ee2           blink::V8ContextSnapshot::CreateContextFromSnapshot (v8_context_snapshot.cc:30)
8   TeamTalkNew.exe                 0x1c81c67           blink::LocalWindowProxy::CreateContext (local_window_proxy.cc:216)
9   TeamTalkNew.exe                 0x1a13fb5           blink::LocalWindowProxy::Initialize (local_window_proxy.cc:142)
10  TeamTalkNew.exe                 0x3778c97           [inlined] blink::WindowProxyManager::GetWindowProxy (window_proxy_manager.h:45)
11  TeamTalkNew.exe                 0x3778c97           blink::Frame::GetWindowProxy (frame.cc:272)
12  TeamTalkNew.exe                 0x1a01aad           [inlined] blink::ToV8ContextEvenIfDetached (v8_binding_for_core.cc:777)
13  TeamTalkNew.exe                 0x1a01aad           [inlined] blink::ToScriptStateImpl (v8_binding_for_core.cc:731)
14  TeamTalkNew.exe                 0x1a01aad           [inlined] blink::ToScriptState (v8_binding_for_core.cc:794)
15  TeamTalkNew.exe                 0x1a01aad           blink::ToScriptStateForMainWorld (v8_binding_for_core.cc:798)
16  TeamTalkNew.exe                 0x28c8bce           blink::WebLocalFrameImpl::MainWorldScriptContext (web_local_frame_impl.cc:1022)
17  TeamTalkNew.exe                 0x3ce5125           extensions::ScriptContextSet::GetMainWorldContextForFrame (script_context_set.cc:99)
18  TeamTalkNew.exe                 0x1d603a0           [inlined] extensions::`anonymous namespace'::GetExtensionFromFrame (extension_frame_helper.cc:104)
19  TeamTalkNew.exe                 0x1d603a0           extensions::ExtensionFrameHelper::DidCommitProvisionalLoad (extension_frame_helper.cc:333)
20  TeamTalkNew.exe                 0x3ce294f           content::RenderFrameImpl::NotifyObserversOfNavigationCommit (render_frame_impl.cc:5088)
21  TeamTalkNew.exe                 0x3ce1dd7           content::RenderFrameImpl::DidCommitNavigation (render_frame_impl.cc:4190)
22  TeamTalkNew.exe                 0x1ea0195           blink::LocalFrameClientImpl::DispatchDidCommitLoad (local_frame_client_impl.cc:496)
23  TeamTalkNew.exe                 0x19e6914           blink::DocumentLoader::CommitNavigation (document_loader.cc:2041)
24  TeamTalkNew.exe                 0x19e4161           blink::FrameLoader::CommitDocumentLoader (frame_loader.cc:1261)
25  TeamTalkNew.exe                 0x19e35ef           blink::FrameLoader::CommitNavigation (frame_loader.cc:1104)
26  TeamTalkNew.exe                 0x19e312d           blink::WebLocalFrameImpl::CommitNavigation (web_local_frame_impl.cc:2334)
27  TeamTalkNew.exe                 0x1f2a41e           content::RenderFrameImpl::CommitNavigationWithParams (render_frame_impl.cc:3220)
28  TeamTalkNew.exe                 0x1f2a1b5           [inlined] base::internal::OptionalStorage<T>::OptionalStorage (optional.h:171)
29  TeamTalkNew.exe                 0x1f2a1b5           [inlined] base::internal::OptionalBase<T>::OptionalBase (optional.h:236)
30  TeamTalkNew.exe                 0x1f2a1b5           [inlined] base::Optional<T>::Optional (optional.h:476)
31  TeamTalkNew.exe                 0x1f2a1b5           base::internal::FunctorTraits<T>::Invoke<T> (bind_internal.h:498)
32  TeamTalkNew.exe                 0x28f75ef           [inlined] base::internal::InvokeHelper<T>::MakeItSo (bind_internal.h:657)
33  TeamTalkNew.exe                 0x28f75ef           [inlined] base::internal::Invoker<T>::RunImpl (bind_internal.h:710)
34  TeamTalkNew.exe                 0x28f75ef           base::internal::Invoker<T>::RunOnce (bind_internal.h:679)
35  TeamTalkNew.exe                 0x21cb6f8           [inlined] base::OnceCallback<T>::Run (callback.h:101)
36  TeamTalkNew.exe                 0x21cb6f8           content::RenderFrameImpl::CommitNavigation (render_frame_impl.cc:3102)
37  TeamTalkNew.exe                 0x21cabc5           [inlined] base::internal::OptionalStorage<T>::OptionalStorage (optional.h:171)
38  TeamTalkNew.exe                 0x21cabc5           [inlined] base::internal::OptionalBase<T>::OptionalBase (optional.h:236)
39  TeamTalkNew.exe                 0x21cabc5           [inlined] base::Optional<T>::Optional (optional.h:476)
40  TeamTalkNew.exe                 0x21cabc5           content::NavigationClient::CommitNavigation (navigation_client.cc:39)
41  TeamTalkNew.exe                 0x1f9d235           [inlined] base::internal::OptionalStorage<T>::OptionalStorage (optional.h:171)
42  TeamTalkNew.exe                 0x1f9d235           [inlined] base::internal::OptionalBase<T>::OptionalBase (optional.h:236)
43  TeamTalkNew.exe                 0x1f9d235           [inlined] base::Optional<T>::Optional (optional.h:476)
44  TeamTalkNew.exe                 0x1f9d235           content::mojom::NavigationClientStubDispatch::AcceptWithResponder (navigation_client.mojom.cc:1000)
45  TeamTalkNew.exe                 0x1f9cded           content::mojom::NavigationClientStub<T>::AcceptWithResponder (navigation_client.mojom.h:203)
46  TeamTalkNew.exe                 0x3a16e7c           mojo::InterfaceEndpointClient::HandleValidatedMessage (interface_endpoint_client.cc:528)
47  TeamTalkNew.exe                 0x3990c42           IPC::`anonymous namespace'::ChannelAssociatedGroupController::AcceptOnProxyThread (ipc_mojo_bootstrap.cc:945)
48  TeamTalkNew.exe                 0x3990b33           [inlined] IPC::`anonymous namespace'::ChannelAssociatedGroupController::SendMessageOnPrimaryThread (ipc_mojo_bootstrap.cc:743)
49  TeamTalkNew.exe                 0x3990b33           base::internal::FunctorTraits<T>::Invoke<T> (bind_internal.h:498)
50  TeamTalkNew.exe                 0x3990ab5           [inlined] base::internal::InvokeHelper<T>::MakeItSo (bind_internal.h:637)
51  TeamTalkNew.exe                 0x3990ab5           [inlined] base::internal::Invoker<T>::RunImpl (bind_internal.h:710)
52  TeamTalkNew.exe                 0x3990ab5           base::internal::Invoker<T>::RunOnce (bind_internal.h:679)
53  TeamTalkNew.exe                 0x3657b6b           [inlined] base::OnceCallback<T>::Run (callback.h:101)
54  TeamTalkNew.exe                 0x3657b6b           base::TaskAnnotator::RunTask (task_annotator.cc:163)
55  TeamTalkNew.exe                 0x3656147           base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl (thread_controller_with_message_pump_impl.cc:351)
56  TeamTalkNew.exe                 0x3655d22           base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork (thread_controller_with_message_pump_impl.cc:264)
57  TeamTalkNew.exe                 0x3d29231           base::MessagePumpDefault::Run (message_pump_default.cc:39)
58  TeamTalkNew.exe                 0x1d1864d           base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run (thread_controller_with_message_pump_impl.cc:460)
59  TeamTalkNew.exe                 0x1a4687c           base::RunLoop::Run (run_loop.cc:131)
60  TeamTalkNew.exe                 0x1c1d6d7           content::RendererMain (renderer_main.cc:260)
61  TeamTalkNew.exe                 0x2e47fef           content::RunOtherNamedProcessTypeMain (content_main_runner_impl.cc:585)
62  TeamTalkNew.exe                 0x2e485fc           content::ContentMainRunnerImpl::Run (content_main_runner_impl.cc:937)
63  TeamTalkNew.exe                 0x20cfcbc           content::RunContentProcess (content_main.cc:372)
64  TeamTalkNew.exe                 0x20cf85e           content::ContentMain (content_main.cc:398)
65  TeamTalkNew.exe                 0x2c920bb           wWinMain (electron_main.cc:212)
66  TeamTalkNew.exe                 0x3d56ab9           [inlined] invoke_main (exe_common.inl:118)
67  TeamTalkNew.exe                 0x3d56ab9           __scrt_common_main_seh (exe_common.inl:288)
68  kernel32.dll                    0x7592343c          BaseThreadInitThunk
69  ntdll.dll                       0x779a9801          __RtlUserThreadStart
70  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 9976
0   ntdll.dll                       0x7798f901          ZwWaitForSingleObject
1   KERNELBASE.dll                  0x758d1628          WaitForSingleObjectEx
2   kernel32.dll                    0x75921193          WaitForSingleObjectExImplementation
3   kernel32.dll                    0x75921147          WaitForSingleObject
4   TSafeDoc2.dll                   0x5511ec51          <unknown>
5   TSafeDoc2.dll                   0x553fb7d8          [inlined] <unknown>
6   TSafeDoc2.dll                   0x553fb7d8          <unknown>
7   ntdll.dll                       0x779a9801          __RtlUserThreadStart
8   ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 14008
0   ntdll.dll                       0x7798f989          ZwRemoveIoCompletion
1   KERNELBASE.dll                  0x758c7784          GetQueuedCompletionStatus
2   TeamTalkNew.exe                 0x31bef6d           sandbox::BrokerServicesBase::TargetEventsThread (broker_services.cc:219)
3   kernel32.dll                    0x7592343c          BaseThreadInitThunk
4   ntdll.dll                       0x779a9801          __RtlUserThreadStart
5   ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 12756
0   ntdll.dll                       0x7798f901          ZwWaitForSingleObject
1   KERNELBASE.dll                  0x758d1628          WaitForSingleObjectEx
2   kernel32.dll                    0x75921193          WaitForSingleObjectExImplementation
3   kernel32.dll                    0x75921147          WaitForSingleObject
4   TeamTalkNew.exe                 0x39ff1d9           base::WaitableEvent::Wait (waitable_event_win.cc:69)
5   TeamTalkNew.exe                 0x3d29294           base::MessagePumpDefault::Run (message_pump_default.cc:55)
6   TeamTalkNew.exe                 0x1d1864d           base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run (thread_controller_with_message_pump_impl.cc:460)
7   TeamTalkNew.exe                 0x1a4687c           base::RunLoop::Run (run_loop.cc:131)
8   TeamTalkNew.exe                 0x1a4639a           base::Thread::Run (thread.cc:311)
9   TeamTalkNew.exe                 0x29ba549           base::internal::ServiceThread::Run (service_thread.cc:15)
10  TeamTalkNew.exe                 0x1a462b0           base::Thread::ThreadMain (thread.cc:382)
11  TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
12  kernel32.dll                    0x7592343c          BaseThreadInitThunk
13  ntdll.dll                       0x779a9801          __RtlUserThreadStart
14  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 5192
0   ntdll.dll                       0x7798f901          ZwWaitForSingleObject
1   KERNELBASE.dll                  0x758d1628          WaitForSingleObjectEx
2   kernel32.dll                    0x75921193          WaitForSingleObjectExImplementation
3   kernel32.dll                    0x75921147          WaitForSingleObject
4   TeamTalkNew.exe                 0x37e0237           base::WaitableEvent::TimedWait (waitable_event_win.cc:107)
5   TeamTalkNew.exe                 0x37de7c6           [inlined] base::internal::WorkerThread::Delegate::WaitForWork (worker_thread.cc:36)
6   TeamTalkNew.exe                 0x37de7c6           base::internal::WorkerThread::RunWorker (worker_thread.cc:344)
7   TeamTalkNew.exe                 0x144cfd4           base::internal::WorkerThread::RunPooledWorker (worker_thread.cc:223)
8   TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
9   kernel32.dll                    0x7592343c          BaseThreadInitThunk
10  ntdll.dll                       0x779a9801          __RtlUserThreadStart
11  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 13628
0   ntdll.dll                       0x7798f901          ZwWaitForSingleObject
1   KERNELBASE.dll                  0x758d1628          WaitForSingleObjectEx
2   kernel32.dll                    0x75921193          WaitForSingleObjectExImplementation
3   kernel32.dll                    0x75921147          WaitForSingleObject
4   TeamTalkNew.exe                 0x37e0237           base::WaitableEvent::TimedWait (waitable_event_win.cc:107)
5   TeamTalkNew.exe                 0x37e00df           base::internal::WorkerThread::Delegate::WaitForWork (worker_thread.cc:36)
6   TeamTalkNew.exe                 0x37de624           base::internal::WorkerThread::RunWorker (worker_thread.cc:320)
7   TeamTalkNew.exe                 0x144d014           base::internal::WorkerThread::RunBackgroundPooledWorker (worker_thread.cc:230)
8   TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
9   kernel32.dll                    0x7592343c          BaseThreadInitThunk
10  ntdll.dll                       0x779a9801          __RtlUserThreadStart
11  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 5076
0   ntdll.dll                       0x7798f901          ZwWaitForSingleObject
1   KERNELBASE.dll                  0x758d1628          WaitForSingleObjectEx
2   kernel32.dll                    0x75921193          WaitForSingleObjectExImplementation
3   kernel32.dll                    0x75921147          WaitForSingleObject
4   TeamTalkNew.exe                 0x37e0237           base::WaitableEvent::TimedWait (waitable_event_win.cc:107)
5   TeamTalkNew.exe                 0x37e00df           base::internal::WorkerThread::Delegate::WaitForWork (worker_thread.cc:36)
6   TeamTalkNew.exe                 0x37de624           base::internal::WorkerThread::RunWorker (worker_thread.cc:320)
7   TeamTalkNew.exe                 0x144cfd4           base::internal::WorkerThread::RunPooledWorker (worker_thread.cc:223)
8   TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
9   kernel32.dll                    0x7592343c          BaseThreadInitThunk
10  ntdll.dll                       0x779a9801          __RtlUserThreadStart
11  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 12112
0   ntdll.dll                       0x7798f989          ZwRemoveIoCompletion
1   KERNELBASE.dll                  0x758c7784          GetQueuedCompletionStatus
2   TeamTalkNew.exe                 0x3814495           [inlined] base::MessagePumpForIO::GetIOItem (message_pump_win.cc:800)
3   TeamTalkNew.exe                 0x3814495           base::MessagePumpForIO::WaitForIOCompletion (message_pump_win.cc:773)
4   TeamTalkNew.exe                 0x3814332           [inlined] base::MessagePumpForIO::WaitForWork (message_pump_win.cc:764)
5   TeamTalkNew.exe                 0x3814332           base::MessagePumpForIO::DoRunLoop (message_pump_win.cc:746)
6   TeamTalkNew.exe                 0x147a4d1           base::MessagePumpWin::Run (message_pump_win.cc:80)
7   TeamTalkNew.exe                 0x1d1864d           base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run (thread_controller_with_message_pump_impl.cc:460)
8   TeamTalkNew.exe                 0x1a4687c           base::RunLoop::Run (run_loop.cc:131)
9   TeamTalkNew.exe                 0x1a4639a           base::Thread::Run (thread.cc:311)
10  TeamTalkNew.exe                 0x1a462b0           base::Thread::ThreadMain (thread.cc:382)
11  TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
12  kernel32.dll                    0x7592343c          BaseThreadInitThunk
13  ntdll.dll                       0x779a9801          __RtlUserThreadStart
14  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 13376
0   ntdll.dll                       0x7799018d          ZwWaitForMultipleObjects
1   ntdll.dll                       0x779bf6ae          TppWaiterpThread
2   kernel32.dll                    0x7592343c          BaseThreadInitThunk
3   ntdll.dll                       0x779a9801          __RtlUserThreadStart
4   ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 14152
0   ntdll.dll                       0x77991f76          ZwWaitForWorkViaWorkerFactory
1   ntdll.dll                       0x779bfa9d          TppTimerpSet
2   kernel32.dll                    0x7592343c          BaseThreadInitThunk
3   ntdll.dll                       0x779a9801          __RtlUserThreadStart
4   ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 12608
0   ntdll.dll                       0x7798f901          ZwWaitForSingleObject
1   KERNELBASE.dll                  0x758d1628          WaitForSingleObjectEx
2   kernel32.dll                    0x75921193          WaitForSingleObjectExImplementation
3   kernel32.dll                    0x75921147          WaitForSingleObject
4   TeamTalkNew.exe                 0x39ff1d9           base::WaitableEvent::Wait (waitable_event_win.cc:69)
5   TeamTalkNew.exe                 0x3d29294           base::MessagePumpDefault::Run (message_pump_default.cc:55)
6   TeamTalkNew.exe                 0x1d1864d           base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run (thread_controller_with_message_pump_impl.cc:460)
7   TeamTalkNew.exe                 0x1a4687c           base::RunLoop::Run (run_loop.cc:131)
8   TeamTalkNew.exe                 0x1a4639a           base::Thread::Run (thread.cc:311)
9   TeamTalkNew.exe                 0x1a462b0           base::Thread::ThreadMain (thread.cc:382)
10  TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
11  kernel32.dll                    0x7592343c          BaseThreadInitThunk
12  ntdll.dll                       0x779a9801          __RtlUserThreadStart
13  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 11000
0   ntdll.dll                       0x7798f901          ZwWaitForSingleObject
1   KERNELBASE.dll                  0x758d1628          WaitForSingleObjectEx
2   kernel32.dll                    0x75921193          WaitForSingleObjectExImplementation
3   kernel32.dll                    0x75921147          WaitForSingleObject
4   TeamTalkNew.exe                 0x39ff1d9           base::WaitableEvent::Wait (waitable_event_win.cc:69)
5   TeamTalkNew.exe                 0x3d29294           base::MessagePumpDefault::Run (message_pump_default.cc:55)
6   TeamTalkNew.exe                 0x1d1864d           base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run (thread_controller_with_message_pump_impl.cc:460)
7   TeamTalkNew.exe                 0x1a4687c           base::RunLoop::Run (run_loop.cc:131)
8   TeamTalkNew.exe                 0x20e3b2e           blink::scheduler::WorkerThread::SimpleThreadImpl::Run (worker_thread.cc:166)
9   TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
10  kernel32.dll                    0x7592343c          BaseThreadInitThunk
11  ntdll.dll                       0x779a9801          __RtlUserThreadStart
12  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 12276
0   ntdll.dll                       0x7798f901          ZwWaitForSingleObject
1   KERNELBASE.dll                  0x758d1628          WaitForSingleObjectEx
2   kernel32.dll                    0x75921193          WaitForSingleObjectExImplementation
3   kernel32.dll                    0x75921147          WaitForSingleObject
4   TeamTalkNew.exe                 0x39ff1d9           base::WaitableEvent::Wait (waitable_event_win.cc:69)
5   TeamTalkNew.exe                 0x37e00f9           base::internal::WorkerThread::Delegate::WaitForWork (worker_thread.cc:34)
6   TeamTalkNew.exe                 0x37de624           base::internal::WorkerThread::RunWorker (worker_thread.cc:320)
7   TeamTalkNew.exe                 0x144d054           base::internal::WorkerThread::RunSharedWorker (worker_thread.cc:237)
8   TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
9   kernel32.dll                    0x7592343c          BaseThreadInitThunk
10  ntdll.dll                       0x779a9801          __RtlUserThreadStart
11  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 11280
0   ntdll.dll                       0x77991f5d          ZwWaitForKeyedEvent
1   ntdll.dll                       0x77a183f6          RtlSleepConditionVariableSRW
2   kernel32.dll                    0x759a53e7          SleepConditionVariableSRW
3   TeamTalkNew.exe                 0x3634fe5           [inlined] base::ConditionVariable::TimedWait (condition_variable_win.cc:45)
4   TeamTalkNew.exe                 0x3634fe5           base::ConditionVariable::Wait (condition_variable_win.cc:30)
5   TeamTalkNew.exe                 0x36349f3           content::CategorizedWorkerPool::Run (categorized_worker_pool.cc:302)
6   TeamTalkNew.exe                 0x1382553           content::`anonymous namespace'::CategorizedWorkerPoolThread::Run (categorized_worker_pool.cc:75)
7   TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
8   kernel32.dll                    0x7592343c          BaseThreadInitThunk
9   ntdll.dll                       0x779a9801          __RtlUserThreadStart
10  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 13872
0   ntdll.dll                       0x77991f5d          ZwWaitForKeyedEvent
1   ntdll.dll                       0x77a183f6          RtlSleepConditionVariableSRW
2   kernel32.dll                    0x759a53e7          SleepConditionVariableSRW
3   TeamTalkNew.exe                 0x3634fe5           [inlined] base::ConditionVariable::TimedWait (condition_variable_win.cc:45)
4   TeamTalkNew.exe                 0x3634fe5           base::ConditionVariable::Wait (condition_variable_win.cc:30)
5   TeamTalkNew.exe                 0x36349f3           content::CategorizedWorkerPool::Run (categorized_worker_pool.cc:302)
6   TeamTalkNew.exe                 0x1382553           content::`anonymous namespace'::CategorizedWorkerPoolThread::Run (categorized_worker_pool.cc:75)
7   TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
8   kernel32.dll                    0x7592343c          BaseThreadInitThunk
9   ntdll.dll                       0x779a9801          __RtlUserThreadStart
10  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 11908
0   ntdll.dll                       0x77991f5d          ZwWaitForKeyedEvent
1   ntdll.dll                       0x77a183f6          RtlSleepConditionVariableSRW
2   kernel32.dll                    0x759a53e7          SleepConditionVariableSRW
3   TeamTalkNew.exe                 0x3634fe5           [inlined] base::ConditionVariable::TimedWait (condition_variable_win.cc:45)
4   TeamTalkNew.exe                 0x3634fe5           base::ConditionVariable::Wait (condition_variable_win.cc:30)
5   TeamTalkNew.exe                 0x36349f3           content::CategorizedWorkerPool::Run (categorized_worker_pool.cc:302)
6   TeamTalkNew.exe                 0x1382553           content::`anonymous namespace'::CategorizedWorkerPoolThread::Run (categorized_worker_pool.cc:75)
7   TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
8   kernel32.dll                    0x7592343c          BaseThreadInitThunk
9   ntdll.dll                       0x779a9801          __RtlUserThreadStart
10  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 13392
0   ntdll.dll                       0x77991f5d          ZwWaitForKeyedEvent
1   ntdll.dll                       0x77a183f6          RtlSleepConditionVariableSRW
2   kernel32.dll                    0x759a53e7          SleepConditionVariableSRW
3   TeamTalkNew.exe                 0x3634fe5           [inlined] base::ConditionVariable::TimedWait (condition_variable_win.cc:45)
4   TeamTalkNew.exe                 0x3634fe5           base::ConditionVariable::Wait (condition_variable_win.cc:30)
5   TeamTalkNew.exe                 0x36349f3           content::CategorizedWorkerPool::Run (categorized_worker_pool.cc:302)
6   TeamTalkNew.exe                 0x1382553           content::`anonymous namespace'::CategorizedWorkerPoolThread::Run (categorized_worker_pool.cc:75)
7   TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
8   kernel32.dll                    0x7592343c          BaseThreadInitThunk
9   ntdll.dll                       0x779a9801          __RtlUserThreadStart
10  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

Thread 11812
0   ntdll.dll                       0x77991f5d          ZwWaitForKeyedEvent
1   ntdll.dll                       0x77a183f6          RtlSleepConditionVariableSRW
2   kernel32.dll                    0x759a53e7          SleepConditionVariableSRW
3   TeamTalkNew.exe                 0x3634fe5           [inlined] base::ConditionVariable::TimedWait (condition_variable_win.cc:45)
4   TeamTalkNew.exe                 0x3634fe5           base::ConditionVariable::Wait (condition_variable_win.cc:30)
5   TeamTalkNew.exe                 0x36349f3           content::CategorizedWorkerPool::Run (categorized_worker_pool.cc:302)
6   TeamTalkNew.exe                 0x1382553           content::`anonymous namespace'::CategorizedWorkerPoolThread::Run (categorized_worker_pool.cc:75)
7   TeamTalkNew.exe                 0x1b7bbd2           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:111)
8   kernel32.dll                    0x7592343c          BaseThreadInitThunk
9   ntdll.dll                       0x779a9801          __RtlUserThreadStart
10  ntdll.dll                       0x779a97d4          _RtlUserThreadStart

### Additional Information

[log.txt](https://github.com/electron/electron/files/7553149/log.txt)

**Comment by ckerr** [comment]
Hey @oppo-flow, you're saying this broke sometime between 12.0.0 and 12.0.14, is that correct?

The suggestion @codebytere made above is the best option, since it would let maintainers do testing on any version, including testing a fix to confirm that it's fixed.

In addition to that, would it be possible for you to bisect between 12.0.0 and .14 to see which version broke this?

**Comment by miniak** [comment]
Electron 12 is not supported anymore

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
