### ISSUE TITLE
[Bug]: The string "g" is truncated in the tray menu.

### ISSUE THREAD

**Issue by wonkyungup** [electron/electron#31889]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.6.0

### What operating system are you using?

Windows

### Operating System Version

Window 10 version 1909

### What arch are you using?

x64

### Last Known Working Electron version

13.6.0

### Expected Behavior

"Settings"  

### Actual Behavior

"Settings"
g spelling is cut off at the bottom
![스크린샷 2021-11-18 오후 4 55 23](https://user-images.githubusercontent.com/34180230/142375155-73132ffd-8c18-406a-aea1-1d9e3e6aa641.png)

**Comment by wonkyungup** [comment]
this is my code
<img width="507" alt="스크린샷 2021-11-18 오후 5 00 03" src="https://user-images.githubusercontent.com/34180230/142375535-f7f8561b-5465-45a8-b5e3-973eac2d55b2.png">

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug by checking your test against different OSes and Electron versions.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by wonkyungup** [comment]
I made it with an electron fiddle, but I don't know how to pass it, so I leave the code.

Os: Window 10
Electron Version: 13.6.0

[Main Process (main.js)]
// Modules to control application life and create native browser window
const {app, Tray, Menu, nativeImage} = require('electron')

function createTray () {
  tray = new Tray(nativeImage.createFromPath(''))
  const contextMenu = Menu.buildFromTemplate([
    { label: 'ggggggggggg', click: () => {
        console.log('click')
      }
    }
  ])
  tray.setContextMenu(contextMenu)
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createTray()
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.

**Comment by wonkyungup** [comment]
https://gist.github.com/50929766212edb4a127c112d214e696d


I hope it gets resolved as soon as possible
