### ISSUE TITLE
[Bug]: will-prevent-unload doesn't fire for BrowserView

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#31882]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I expect that will-prevent-unload will fire when closing a BrowserView with a page that cancels the beforeunload event

### Actual Behavior

will-prevent-unload never fires. It only fires for BrowserWindows.

### Additional Information

I am reopening [this issue](https://github.com/electron/electron/issues/27722) since it doesn't appear to have been fixed. Maybe this was an intentional decision as part of the [linked PR](https://github.com/electron/electron/pull/28382).

1. start main.js
2. in the devtools, execute: onbeforeunload = (e) => { e.preventDefault(); e.returnValue = false; }
3. Close the window.
4. The window does close, but the will-prevent-unload handler never executes
```
const { app, BrowserWindow, BrowserView } = require('electron')

async function createWindow () {
  const win = new BrowserWindow();
  const view = new BrowserView();

  view.setBounds({x: 0, y: 0, width: 600, height: 600});
  win.setBrowserView(view);

  await view.webContents.loadURL('https://google.com')
  view.webContents.openDevTools();

  view.webContents.on("will-prevent-unload", (e) => {
    e.preventDefault();
  });
}

app.whenReady().then(createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
});
```

**Comment by codebytere** [comment]
@pushkin- from the PR:
> However, this change makes it such that the event will be emitted for BrowserViews but will not be respected - I've chosen not to tie the BrowserView lifecycle to its owning BrowserWindow should one exist per the specification. Either way this is undefined behavior, and the alternative would be to wait until all associated BrowserViews for a BrowserWindow had their webContents destroyed, and given that a BrowserView doesn't need to be associated with a BrowserWindow this would ultimately be more confusing for end users.

We _could_ emit the event but per the above commentary it would be a lie basically which is why we chose not to emit `will-prevent-unload`. We might in the future come back to this and find a better solution but for now this isn't something that we're able to address effectively.
