### ISSUE TITLE
Debugging Electron on MacOS via VSCode (or XCode)

### ISSUE THREAD

**Issue by greggman** [electron/electron#31886]
I'm sorry to ask this here but, given this is the team that makes Electron and now both Electron and VSCode are effectively by the same company (I know, different teams). In any case.

Is there anyone here that is developing Electron with VSCode and has been able to get VSCode to debug Electron, even if just a unit test vs the entirety of Chromium? I'm on MacOS 12 on an Intel based Mac and have had no luck. lldb-mi just hangs on the first continue/step-in/step-over).  I know Electron is basically Chromium + Node and the Chromium repo has some docs on using [VSCode to debug Chromium](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/vscode.md) but they seem out of date and asking on the Chromium team it seems like no one is using VSCode to debug Chrome on MacOS

I thought maybe someone here were both products are by the same company, maybe there is a chance someone is debugging Electron (the C++ parts) vs VSCode and can share their `launch.json` and build settings `gn args` and which debugging plugin they're using.

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
