### ISSUE TITLE
[Feature Request]: Can I copy webcontents or browserview ?

### ISSUE THREAD

**Issue by colining** [electron/electron#31892]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

So here is I assumed scenario。

1. User  is browsing the website in electron APP
2. User can click a button,and It' will popup a new window with the page user use now
3. the old window will be still there

so It's like 

- old Browser window
   - old browser view
     - old webcontents
click
- new Browser window
   - new browser view
     - new webcontents

and old webcontents is same as new webcontents

I'm not sure it's a problem need to ask , cause the webcontents is read-only in the BrowserWindow

### Proposed Solution

Imaginary solution

ipcRenderer send webcontentID

ipcMain reseive webcontentID

and then

create new BrowserWindow

create new BrowserView

and next

newBrowserview.webContents = webContents.fromId(webcontentsID) 

### Alternatives Considered

I'm not sure It has the solution to this case but I'm very curious about  the following thing

1. why webcontents is read-only
2. If we need to clone a page, how can we do
3. The reason why I want to copy webcontents is that I think If we popup a new window through clone webcontents,  there is no loading time.

**Comment by lzdyes** [comment]
is an interesting feature
