### ISSUE TITLE
[Bug]: BrowserWindow.focus freezes UI after window switching

### ISSUE THREAD

**Issue by rppig42** [electron/electron#31891]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0/16.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2

### What arch are you using?

x64

### Last Known Working Electron version

10.2.0

### Expected Behavior

1. after opening this app, open another app like chrome and wait. Make sure this electron app is totally invisible. (by doing this, you can maximize the chrome window
2. after hearing a beep sound, reopen this electron app
3. expected to see the countdown is going on

### Actual Behavior

on step 3, you can see that the countdown is frozen

### Testcase Gist URL

https://gist.github.com/c85dcd5d7bfb9353a980629beb8a4c1e

### Additional Information

this issue can be reproduced in variety windows machines

**Comment by pushkin-** [comment]
Does it update after you trigger a repaint? This reminds of other issues I've seen.

**Comment by rppig42** [comment]
@pushkin- it updates after click anywhere outside the app. Do you have any clue to this issue?

**Comment by pushkin-** [comment]
I feel like I've seen a more similar issue, but [this one](https://github.com/electron/electron/issues/28255) comes to mind

**Comment by sm-will** [comment]
@rppig42 this gist repro case is great...I've been fighting this bug but had a hard time figuring out exactly the repro case because my app has 5 windows.

Adding `app.commandLine.appendSwitch('disable-features','CalculateNativeWinOcclusion');` to line 2 of main.js in this gist fixes the issue for me (or running electron with flag `--disable-features=CalculateNativeWinOcclusion`) against the repro and also on my app.

**Comment by semireg** [comment]
Does anyone know if this affects 17?

**Comment by Slapbox** [comment]
I'm not sure, but I think we're seeing this in 17 and 18 on Windows 11.
