### ISSUE TITLE
[Feature Request]: Sandbox error at start-up (feature request for additional guidance in Quickstart guide)

### ISSUE THREAD

**Issue by jasonpolites** [electron/electron#31905]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am new to Electron.. in fact, this is the first time I've tried to get it working. My starting point was the [Quickstart](https://www.electronjs.org/docs/latest/tutorial/quick-start), however I ran into a number of issues and it wasn't clear what the recommended way to resolve was.

After `npm install` of electron, and making the relevant change to `package.json`, executing `npm start` resulted in the following:

```
 error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
```

OK.. no problem...

```
sudo apt-get install -y libgtk-3-0
```

Let's try again.. `npm start`

```
error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
```

Hmm... ok.. no problem...

```
sudo apt-get install -y libgbm-dev
```

Third time's a charm... `npm start`

```
[2530:1118/145422.546758:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /<REDACTED>/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
/<REDACTED>/node_modules/electron/dist/electron exited with signal SIGTRAP
$ [2532:0100/000000.737452:ERROR:zygote_linux.cc(646)] write: Broken pipe (32)
```

I'm not really sure how to fix that. I mean.. `chown` inside `node_modules` would likely make progress, but at this point it feels like I'm doing something wrong, but I have not much clue what.

### Proposed Solution

Perhaps some specific environment setup guidelines (which system packages are required etc) to mitigate these initial setup issues. Alternatively perhaps some crowd-sourced (common) setup errors (assuming my issues are not isolated to me)

### Alternatives Considered

Manually hacking through each error I guess?

### Additional Information

Not sure how relevant (probably very?), this is being done in WSL on Windows 10 (Version 1 apparently), running Ubuntu-20.04

**Comment by MarshallOfSound** [comment]
> Not sure how relevant (probably very?), this is being done in WSL on Windows 10 (Version 1 apparently), running Ubuntu-20.04

Running Electron in WSL isn't really supported as it's a mostly headless environment, it's missing a large amount of the windowing libraries required.  I think this works substantially better in WSL2 but still has a lot of edge cases which Electron will not be actively supporting.  Just run the windows version of Electron on windows instead of the linux one through WSL
