### ISSUE TITLE
[Bug]: Folder contains special characters (å) and startup crashed

### ISSUE THREAD

**Issue by qwerchuan** [electron/electron#31908]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows11 version 22000.346

### What arch are you using?

x64

### Last Known Working Electron version

13.0.0

### Expected Behavior

Normal start

### Actual Behavior

gpu-process-crashed

### Additional Information

[Crashpad.zip](https://github.com/electron/electron/files/7569258/Crashpad.zip)

**Comment by qwerchuan** [comment]
Win10 got the same results

**Comment by bavulapati** [comment]
Might be the same as #30966

**Comment by nornagon** [comment]
Duplicate of #30966
