### ISSUE TITLE
[Bug]: Focusing a webview too early doesn’t work, and prevents it from being focused later

### ISSUE THREAD

**Issue by andersk** [electron/electron#31918]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1, 17.0.0-alpha.2, 18.0.0-nightly.20211118, older versions at least as old as 3.0.0

### What operating system are you using?

Other Linux

### Operating System Version

NixOS 21.11

### What arch are you using?

x64

### Expected Behavior

If I create a webview and call `webview.focus()` from the `did-attach` handler, the `did-navigate` handler, and immediately after appending the element to the DOM, it should be focused. Indeed, any one of these three calls ought to suffice.

```js
const webview = document.createElement("webview");
webview.src = "webview.html";
webview.addEventListener("did-attach", () => {
  webview.focus();
});
webview.addEventListener("did-navigate", () => {
  webview.focus();
});
document.body.append(webview);
webview.focus();
```

### Actual Behavior

The webview is not focused, as measured by a CSS `:focus` rule inside the webview.

### Testcase Gist URL

https://gist.github.com/andersk/a6eedbbd034037dbfa94526b81fda930

### Additional Information

Workarounds:

* If I delete the `webview.focus()` calls in the `did-attach` handler and after appending the element, but keep the `webview.focus()` call in the `did-navigate` handler, that successfully focuses the webview. (Of the 2³ = 8 combinations of deleting or keeping each call, this is the *only* one that works.)
* Or, if I run `webview.shadowRoot.querySelector("iframe").focus()` from the `did-navigate` handler, that successfully focuses the webview.
* Or, if I change the `did-navigate` handler to `document.activeElement?.blur(); webview.focus()`, that successfully focuses the webview (even though `document.activeElement === webview` evaluates to `true` beforehand).

**Comment by andersk** [comment]
Still broken in v20.3.0, but seems fixed in https://github.com/electron/electron/compare/v21.0.0-beta.5...v21.0.0-beta.6 and https://github.com/electron/electron/compare/v22.0.0-nightly.20220908...v22.0.0-nightly.20220909.

**Comment by githoniel** [comment]
Still broken in v20.3.4

**Comment by andersk** [comment]
Since this seems fixed in Electron 21 which is now the oldest supported release, I think this can be closed.
