### ISSUE TITLE
[Bug]: app.setBadgeCount doesn't work on macOS

### ISSUE THREAD

**Issue by oalfroukh** [electron/electron#31935]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.6

### What arch are you using?

x64

### Expected Behavior

Using `app.setBadgeCount(5);` on macOS should add badge for the app icon.

### Actual Behavior

There is no badge that appears, at the same time when I console `app.getBadgeCount()` the result is `5`

### Additional Information

I tried to set a badge for the `quick app`, this is my code: 

```
const { app, BrowserWindow } = require("electron");

function createWindow() {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  });

  mainWindow.loadFile("index.html");

  app.setBadgeCount(5);
  console.log("getBadge:", app.getBadgeCount());
}

app.on("ready", createWindow);

```

**Comment by codebytere** [comment]
@oalfroukh can you say a little more about what you're seeing? I can't reproduce with your parameters, and see the correct output on Big Sur with 16.0.0:

<img width="1160" alt="Screen Shot 2021-11-22 at 7 21 00 PM" src="https://user-images.githubusercontent.com/2036040/142914778-dcb4b843-4e19-4504-8d1e-49a37055590c.png">

**Comment by MarshallOfSound** [comment]
This will probably because you didn't give permission for the app to show badges, on Catalina and above it's a permission-only thing.

![image](https://user-images.githubusercontent.com/6634592/142936458-3a4feb64-cb54-406f-9d2a-fb86f00caca3.png)

**Comment by oalfroukh** [comment]
Thank you so much @MarshallOfSound, the permissions of notifications fixed the issue.
