### ISSUE TITLE
[Bug]: notification.timeoutType='never' is useless

### ISSUE THREAD

**Issue by yiyong98** [electron/electron#31951]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

Windows

### Operating System Version

win7

### What arch are you using?

x64

### Last Known Working Electron version

16.0.1

### Expected Behavior

use  Class: Notification to show notification in win7 and win10 forver until the user click

### Actual Behavior

use Class: Notification to show notification in Win7 and Win 10 ,but in Win7,  notification.timeoutType='never' is useless. after 5 second ,the notification will be close.
and when i use HTML5 API ,the Notification.requireInteraction won't be support
how can i show notification forver until the user click? 

### Testcase Gist URL

https://gist.github.com/4875e0cd7cf4f3370ff43f583c030fe0

**Comment by yiyong98** [comment]
in win10 ,the notification will be close after 6min,even though i set notification.timeoutType='never'

**Comment by VerteDinde** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by yiyong98** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance!

https://gist.github.com/4875e0cd7cf4f3370ff43f583c030fe0
