### ISSUE TITLE
[Bug]: My application traps after running about 6 days.

### ISSUE THREAD

**Issue by wuleibobo** [electron/electron#31952]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.9

### What operating system are you using?

Other Linux

### Operating System Version

Linux x64 3.10.0-957.el7.x86_64

### What arch are you using?

x64

### Last Known Working Electron version

13.1.9

### Expected Behavior

Electron runs well for long time.

### Actual Behavior

My application traps after running about 6 days.

### Additional Information

My application traps after running about 6 days.

[Mon Nov 22 09:05:55 2021] traps: application[13499] trap int3 ip:5555baaf78bf sp:7ffd26fd5d60 error:0 in application[5555b7f38000+6463000]

Software environment:
Electron: 13.1.9
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 3.10.0-957.el7.x86_64

Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz
MemTotal:       32727852 kB
MemFree:         7031688 kB
MemAvailable:   20751548 kB
Buffers:          330568 kB
Cached:         13183732 kB
SwapCached:            0 kB

**Comment by VerteDinde** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
