### ISSUE TITLE
[Bug]: SVG translate3d GPU problem? translation is too laggy

### ISSUE THREAD

**Issue by Drunkar** [electron/electron#31965]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home 21H2

### What arch are you using?

x64

### Expected Behavior

Smooth drag rendering as in chrome.
![chrome](https://user-images.githubusercontent.com/1223433/142980383-815807a6-38f9-4570-9a16-52e1b99966f3.gif)
![chrome](https://user-images.githubusercontent.com/1223433/142980393-496d6979-1efd-4a01-8f99-e1964abc9e8f.png)

### Actual Behavior

It requires about 1 seconds system call on every frame of rendering.

![electron](https://user-images.githubusercontent.com/1223433/142981306-56901a6d-292e-4c3e-a1cb-d5d5e7e9aa39.gif)
![gpu_enabled](https://user-images.githubusercontent.com/1223433/142981394-850d63c9-9dc4-45d8-b5af-6430b2278e97.png)

After I disabled gpu acceleration (adding `app.disableHardwareAcceleration();` to `main.js`), the result was the same.
So I guess there are some gpu call bugs in translate3d. My code was a modified code of google blockly's Javascript generator demo. (The test case is in the gist URL).
Blockly adds `translate3d()` css when drag. This causes the differences between chrome. https://github.com/google/blockly/blob/master/core/workspace_drag_surface_svg.js#L89

![gpu_disabled](https://user-images.githubusercontent.com/1223433/142981501-ab29ee57-2632-4316-b67b-e4e1255ab9a0.png)

I enable `sandbox`, but the result was the same.

```
const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: false,
      enableRemoteModule: false,
      contextIsolation: true,
      sandbox: true
    }
  });
```

### Testcase Gist URL

https://gist.github.com/Drunkar/ec42d499cc147e950cd395381830e40e

### Additional Information

I'm using NVIDIA GeForce RTX 2060 and the latest driver (472.47).
I tried in my m1 apple silicon mac, but the result was the same. (chrome was smooth and electron was laggy).

**Comment by jkleinsc** [comment]
@Drunkar can you try this with 16.0.2?  I was able to reproduce in 16.0.1, but the issue appears to be resolved in 16.0.2

**Comment by Drunkar** [comment]
Thank you, @jkleinsc 
I tried both 16.0.2 and 16.0.3, but the issue still exists both in windows and macOS.
I opened the index.html in testcase gist, but the translations are still too laggy. If it's in chrome, it's really smooth.

**Comment by Drunkar** [comment]
What I tested was:
clone electron quick start repo:
https://github.com/electron/electron-quick-start

then replaced `index.html`. After that,

```
npm install
npm install --save-dev electron@16.0.2
npm start
```

I confirmed it's 16.0.2 via developper tool console:
`navigator.userAgent.match(/Electron\/([\d\.]+\d+)/)[1]`
