### ISSUE TITLE
[Bug]: App freezes short after start. Resizing the window helps.

### ISSUE THREAD

**Issue by fabian0310** [electron/electron#31968]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

don't know

### Expected Behavior

App does not freeze.

### Actual Behavior

In rare cases my electron app freezes shortly after the launch, when I click a button which should load a new page. If this happens only the background is shown. If I resize the window just a little, the app works fine again.

I tried debugging with the DevTools, but the DevTools also freeze.

I tried disabling the hardware acceleration but that did not help.

What can I do to solve this issue?

**Comment by fabian0310** [comment]
Destroyed the splash screen before showing the MainWindow. By showing the MainWindow before destroying the splash screen, the problem doesn't occure anymore.

**Comment by eric-burel** [comment]
Hi, very same issue, we can repro starting Electron 11, any idea why this happens? This is specific to Windows 10 as far as I can tell, it doesn't happen on Linux. I will try your fix, but that's still weird. Could it be because there is no visible window for an infinitesimal amount of time when you show after destroying the splash?
