### ISSUE TITLE
[Bug]: Auto-scaling problem when the window is transparent and borderless

### ISSUE THREAD

**Issue by GreedyWhale** [electron/electron#31962]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 1809 

### What arch are you using?

x64

### Expected Behavior

The window displays correctly and maintains the set size

### Actual Behavior

The window will get smaller and smaller。

1. Set the window to
    - frame: false
    - transparent: true
2. listen to the window 'close' event and prevent it from closing
3. Make the window minimized
4. Click the close button in the taskbar
5. Type `mainWindow.show()` in the console to make the window appear
6. Repeat steps 3,4,5 and the window will get smaller and smaller

### Testcase Gist URL

https://github.com/GreedyWhale/electron-testcase-window-zoom-out

### Steps

1. git clone git@github.com:GreedyWhale/electron-testcase-window-zoom-out.git
2. cd electron-testcase-window-zoom-out
3. yarn install
4. yarn start
5. click Minimize button
6. close window from Taskbar
7. Type in the console `mainWindow.show()`
8. Observe that the window size will become smaller, repeat steps 5, 6, and 7, the window will become smaller and smaller

**Comment by famingyuan** [comment]
try calling restore api before show.

**Comment by GreedyWhale** [comment]
> try calling restore api before show.

Calling app.restore first, then app.show does solve the problem, but if you try a few more times (and don't forget to close from the taskbar), the window will still get smaller and smaller even if app.restore is called first

**Comment by TheCoder76-Codes** [comment]
Hello @GreedyWhale,
I was recently experiencing the same problem. I had a tray set up with a menu to re-open my app, but every time it would make the window smaller.
I was using Electron version 16.0.3, and Windows version 21H1. I found a solution using `window.close()`. I have added my code below:

On window minimize, the app closes and creates a tray.
```
window.on('minimize', function (event) {
        event.preventDefault();
        app.isQuiting = false;
        tray = createTray();
        window.close()
    });
```
Create a tray using a createWindow function (I used the same `createWindow` function as found in the Electron docs.
```
function createTray() {
    let appIcon = new Tray(path.join(__dirname, "rocket.ico"));
    const contextMenu = Menu.buildFromTemplate([
        {
            label: 'Activate LaunchPad', click: function () {
                createWindow()
                tray.destroy();
            }
        },
        {
            label: 'Exit LaunchPad', click: function () {
                app.isQuiting = true;
                app.quit();
            }
        }
    ]);
    appIcon.on('double-click', function (event) {
        window.show();
    });
    appIcon.setToolTip('Launchpad');
    appIcon.setContextMenu(contextMenu);
    return appIcon;
}
```
Finally, some logic to stop the app from quitting when the window is closed.
```
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin' && app.isQuiting) app.quit()
})
```
I hope this helps!

**Comment by famingyuan** [comment]
> Hello @GreedyWhale,
> I was recently experiencing the same problem. I had a tray set up with a menu to re-open my app, but every time it would make the window smaller.
> I was using Electron version 16.0.3, and Windows version 21H1. I found a solution using `window.close()`. I have added my code below:
> 
> On window minimize, the app closes and creates a tray.
> ```
> window.on('minimize', function (event) {
>     event.preventDefault();
>     app.isQuiting = false;
>     tray = createTray();
>     window.close()
> });
> ```
> Create a tray using a createWindow function (I used the same `createWindow` function as found in the Electron docs).
> ```
> function createTray() {
>     let appIcon = new Tray(path.join(__dirname, "rocket.ico"));
>     const contextMenu = Menu.buildFromTemplate([
>         {
>             label: 'Activate LaunchPad', click: function () {
>                 createWindow()
>                 tray.destroy();
>             }
>         },
>         {
>             label: 'Exit LaunchPad', click: function () {
>                 app.isQuiting = true;
>                 app.quit();
>             }
>         }
>     ]);
>     appIcon.on('double-click', function (event) {
>         window.show();
>     });
>     appIcon.setToolTip('Launchpad');
>     appIcon.setContextMenu(contextMenu);
>     return appIcon;
> }
> ```
> Finally, some logic to stop the app from quitting when the window is closed.
> ```
> app.on('window-all-closed', () => {
>     if (process.platform !== 'darwin' && app.isQuiting) app.quit()
> })
> ```
> I hope this helps!

is it the same issue? the problem is auto scaling when right click the close menu on the taskbar.

**Comment by TheCoder76-Codes** [comment]
> is it the same issue? the problem is auto scaling when right click the close menu on the taskbar.

Short answer, yes.

I was originally using the `window.hide()` and `window.show()` methods, which produced the problem described above. Every time the `window.show()` method was called (after the window was hidden), the window would re-size to a smaller version of itself. This was the same issue that GreedyWhale was experiencing.

**Comment by GreedyWhale** [comment]
> Hello @GreedyWhale, I was recently experiencing the same problem. I had a tray set up with a menu to re-open my app, but every time it would make the window smaller. I was using Electron version 16.0.3, and Windows version 21H1. I found a solution using `window.close()`. I have added my code below:
> 
> On window minimize, the app closes and creates a tray.
> 
> ```
> window.on('minimize', function (event) {
>     event.preventDefault();
>     app.isQuiting = false;
>     tray = createTray();
>     window.close()
> });
> ```
> 
> Create a tray using a createWindow function (I used the same `createWindow` function as found in the Electron docs).
> 
> ```
> function createTray() {
>     let appIcon = new Tray(path.join(__dirname, "rocket.ico"));
>     const contextMenu = Menu.buildFromTemplate([
>         {
>             label: 'Activate LaunchPad', click: function () {
>                 createWindow()
>                 tray.destroy();
>             }
>         },
>         {
>             label: 'Exit LaunchPad', click: function () {
>                 app.isQuiting = true;
>                 app.quit();
>             }
>         }
>     ]);
>     appIcon.on('double-click', function (event) {
>         window.show();
>     });
>     appIcon.setToolTip('Launchpad');
>     appIcon.setContextMenu(contextMenu);
>     return appIcon;
> }
> ```
> 
> Finally, some logic to stop the app from quitting when the window is closed.
> 
> ```
> app.on('window-all-closed', () => {
>     if (process.platform !== 'darwin' && app.isQuiting) app.quit()
> })
> ```
> 
> I hope this helps!

Thanks to your solution, I used another method to solve this problem.

I would use.

```diff
+ mainWindow.minimize();
+ mainWindow.setSkipTaskbar(true);
- mainWindow.hide();
```

instead of `mainWindow.hide();`

When I want the window to appear.

```javascript
mainWindow.setSkipTaskbar(false);
mainWindow.show();
```
