### ISSUE TITLE
[Bug]: getLoginItemSettings not returning correct args

### ISSUE THREAD

**Issue by skandaswamygit** [electron/electron#31960]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Windows

### Operating System Version

20H2

### What arch are you using?

x64

### Expected Behavior

getLoginItemSettings() should return the correct "launchItem.args" parameter within the launchItems array, after executing the following code.

`  app.setLoginItemSettings({ openAtLogin: true, args: ['--arg1'] });`

Result: 
{
  name: "electron.app.Electron",
  path: DEFAULT_EXE_PATH,
  args: [
   **'--arg1'**
  ],
  scope: "user",
  enabled: true,
}

### Actual Behavior

getLoginItemSettings **NOT** returning the correct "launchItem.args" parameter within the launchItems array. **Note that the args array alone is coming empty.** 

`app.setLoginItemSettings({ openAtLogin: true, args: ['--arg1'] });`

Result: 
{
  name: "electron.app.Electron",
  path: DEFAULT_EXE_PATH,
  **args: [
  ],**
  scope: "user",
  enabled: true,
}

Also, when I try the following,

`app.setLoginItemSettings({ openAtLogin: true, args: ['--', '--arg1'] });`
 
I was able to get the output as follows
Result:
{
  name: "electron.app.Electron",
  path: DEFAULT_EXE_PATH,
  args: [
    **"--arg1",**
  ],
  scope: "user",
  enabled: true,
}

### Additional Information

1. As per the electron API documentation example at https://www.electronjs.org/docs/latest/api/app#appsetloginitemsettingssettings-macos-windows, I should be able to pass the arguments with "--" prefix
2. Unit tests found under [electron-main\spec-main\api-app-spec.ts](url) all seem to pass the arguments without the "--" prefix.
3. I am able to obtain the correct args if I pass the argument name without the "-" or "--" prefix. 
4. The registry entry is properly saved as `DEFAULT_EXE_PATH --arg1` when executing the setLoginItemSettings API call as shown above.
5. I need the getLoginItemSettings to return the correct args to determine whether the minimize functionality is selected or not. We don't presently use a config or local cache to store user preferences hence relying on the API.

**Comment by Fndroid** [comment]
Same issue here.

Besides, if I quote the launch path with `"`, `launchItems` returns an empty array.

If not using quotes, spaces in app name will be split and `args` become wired.
![image](https://user-images.githubusercontent.com/16091562/148004031-b6746c04-527e-4467-9c96-d93f8d21661a.png)
![image](https://user-images.githubusercontent.com/16091562/148004109-2738e563-cfad-4c0a-8250-727f97dbd1a0.png)

**Comment by RGdevz** [comment]
same

**Comment by Oxalin** [comment]
According to the both message, we need to open a new issue.
