### ISSUE TITLE
[Bug]: When i run it, it shows up but it is blank. there is nowhere to input the token.

### ISSUE THREAD

**Issue by H46K3RL0L** [electron/electron#31976]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.10

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 19042.1237

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

a gui to pop up asking for a bot token to login.

### Actual Behavior

the window remains gray and nothing happens

### Additional Information

It shows up as just a gray area, nothing else except the top bar.

**Comment by DarkShardGamer** [comment]
This project is discontinued and you will no longer receive support. This is also bannable as it breaks a ToS
