### ISSUE TITLE
[Bug]: 打包之后双击exe文件没反应，任务栏有个图标

### ISSUE THREAD

**Issue by oyeaono** [electron/electron#31985]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^15.2.0

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Last Known Working Electron version

^15.2.0

### Expected Behavior

正常运行
Google translate: normal operation

### Actual Behavior

双击打包后的exe文件没有反应，没有启动窗口，右下角也没有图标，只有任务栏有个app的图标
Google translate: There is no response after double-clicking the packaged exe file, there is no start window, and there is no icon in the lower right corner, only an app icon in the taskbar

**Comment by huyinghuan** [comment]
这大概率应该不是bug，，代码有问题。。。

**Comment by oyeaono** [comment]
> 这大概率应该不是bug，，代码有问题。。。

开发环境没问题。。。

**Comment by miniak** [comment]
Your bug report is insufficient for us to investigate it. There are no repro steps and the description is vague.

**Comment by oyeaono** [comment]
> 您的错误报告不足以让我们对其进行调查。没有复制步骤，描述也很模糊。

就是开发环境都正常，然后使用electron-packager打包之后打包成功，但是双击程序.exe 文件没反应，系统任务栏有app的图标

**Comment by miniak** [comment]
In that case you might need to report this to https://github.com/electron/electron-packager instead

**Comment by oyeaono** [comment]
> 在这种情况下，你可能需要将此情况报告给https://github.com/electron/electron-packager代替

好的，谢谢

**Comment by PasserbyFluid** [comment]
同样遇到这样的问题，但是复现的概率很低。不知道是系统问题还是软件问题，之前WeChat也遇到过
