### ISSUE TITLE
[Bug]: Chromium is setting DBUS_SESSION_BUS_ADDRESS=disabled:

### ISSUE THREAD

**Issue by not-my-profile** [electron/electron#31981]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

Other Linux

### Operating System Version

Debian GNU/Linux 10

### What arch are you using?

x64

### Expected Behavior

Electron does not set the environment variable `DBUS_SESSION_BUS_ADDRESS=disabled:`.

### Actual Behavior

Electron sets the environment variable `DBUS_SESSION_BUS_ADDRESS=disabled:`.

### Additional Information

I was wondering why attempting to open links in VS Codium & Signal was failing with:

> Firefox is already running, but is not responding. To use Firefox, you must first close the existing Firefox process, restart your device, or use a different profile.

As it turns out this is because Electron is for some reason setting the environment variable  `DBUS_SESSION_BUS_ADDRESS=disabled:` which makes e.g. `firefox http://example.com` fail because to open a new link [Firefox uses DBus](https://utcc.utoronto.ca/~cks/space/blog/unix/FirefoxDBusRemoteControl?showcomments).

I reproduced this with [electron-quick-start](https://github.com/electron/electron-quick-start) by adding a `console.log(process.env.DBUS_SESSION_BUS_ADDRESS);` to `main.js`. Before running `npm start` the environment variable is not set but running the applications prints `disabled:`.

Apparently this is caused by Chromium: https://codereview.chromium.org/2861163002

**Comment by jkleinsc** [comment]
@not-my-profile as noted [here](https://source.chromium.org/chromium/chromium/src/+/main:content/app/content_main.cc;l=261?q=DBUS_SESSION_BUS_ADDRESS&ss=chromium), you can work around this by setting `DBUS_SESSION_BUS_ADDRESS="autolaunch:"` before launching Chromium/Electron.  If you have further questions about this I'd recommend asking at [the Electron Discord server](https://discord.com/invite/electron).
