### ISSUE TITLE
[Bug]: All windows lose their content, when the child window is refreshed, with certain webPreferences

### ISSUE THREAD

**Issue by RaNtSinE** [electron/electron#31983]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Last Known Working Electron version

14.1.1

### Expected Behavior

If you use `preload` or `nodeIntegration: true`, `contextIsolation: false` and `nativeWindowOpen: true` in `webPreferences`, then the content should not disappear.

### Actual Behavior

When using these `webPreferences`, content disappears when the child window is refreshed.

### Testcase Gist URL

https://gist.github.com/RaNtSinE/0e35a5068d6bc73b5a7e3365339ec2ab

### Additional Information

To reproduce the bug, you must click on the "open" button, then in any way update the opened child window, for example like in the attached gif file
![Child window bug](https://user-images.githubusercontent.com/45504704/143204390-661a12a0-a642-4eb4-83e4-b71b6702e034.gif)

**Comment by jyd519** [comment]
`contextIsolation: false`  causes this problem.
