### ISSUE TITLE
[Bug]: File open and save dialog cannot open on Linux KDE since Electron 14

### ISSUE THREAD

**Issue by Clansty** [electron/electron#31997]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14, 15, 16

### What operating system are you using?

Other Linux

### Operating System Version

Linux PROGYNOVA 5.15.4-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 21 Nov 2021 21:34:35 +0000 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

13.6.2

### Expected Behavior

```js
dialog.showSaveDialogSync(getMainWindow(), {
        title: 'Choose save path',
        defaultPath: path.join(app.getPath('desktop'),
            formatDate('yyyy-MM-dd') + '.csv'),
        filters: [{
            name: 'Comma-separated values (CSV)',
            extensions: ['csv'],
        }],
    })
```

Save file dialog popup

### Actual Behavior

Nothing happened, terminal output:

```
[66476:1125/204240.240014:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed
```

### Additional Information

```
❯ neofetch
                   -`                    clansty@PROGYNOVA 
                  .o+`                   ----------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 5.15.4-zen1-1-zen 
               `+oooooo:                 Uptime: 9 hours, 22 mins 
               -+oooooo+:                Packages: 1336 (pacman) 
             `/:-:++oooo+:               Shell: zsh 5.8 
            `/++++/+++++++:              Resolution: 1080x1920, 2560x1440 
           `/++++++++++++++:             DE: Plasma 5.23.3 
          `/+++ooooooooooooo/`           WM: KWin 
         ./ooosssso++osssssso+`          Theme: Breeze Light [Plasma], Breeze [GTK3] 
        .oossssso-````/ossssss+`         Icons: breeze [Plasma], breeze [GTK2/3] 
       -osssssso.      :ssssssso.        Terminal: konsole 
      :osssssss/        osssso+++.       Terminal Font: Hack 10 
     /ossssssss/        +ssssooo/-       CPU: Intel Xeon E5-1650 v2 (12) @ 3.900GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce GTX 960 
  `+sso+:-`                 `.-/+oso:    Memory: 9947MiB / 15932MiB 
 `++:.                           `-/+/
 .`                                 `/                           
                                                                 
```

**Comment by madosuki** [comment]
I've got same issue on Electron 16.0 on Debian 11.

**Comment by vchernin** [comment]
@tristan957

**Comment by tristan957** [comment]
@vchernin let me look into this...

**Comment by tristan957** [comment]
@vchernin https://gitlab.gnome.org/GNOME/gtk/-/blob/3.24.30/gtk/gtknativedialog.c#L584

submitting a PR lol

**Comment by tristan957** [comment]
Does this assertion happen in the async code path for you?

**Comment by Narcha** [comment]
Looks like #31152 can be closed as well.
