### ISSUE TITLE
[Bug]: hasShadow Boolean (可选) - 窗口是否有阴影. 默认值为 true

### ISSUE THREAD

**Issue by qingyou730** [electron/electron#32028]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.1

### What operating system are you using?

Windows

### Operating System Version

new version

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

[Bug]: hasShadow Boolean (可选) - 窗口是否有阴影. 默认值为 true  在window中无效果

### Actual Behavior

[Bug]: hasShadow Boolean (可选) - 窗口是否有阴影. 默认值为 true  在window中无效果

### Additional Information

[Bug]: hasShadow Boolean (可选) - 窗口是否有阴影. 默认值为 true  在window中无效果

**Comment by VerteDinde** [comment]
Thanks for reporting this and helping to make Electron better! It looks like your expected and actual behavior listed are the same - is there a bug happening here, and if so, can you add additional information on the error you're seeing vs what you expected to see?

It's also hard for us to take action on this issue without any code samples; would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!
