### ISSUE TITLE
[Bug]: Error 3221225477

### ISSUE THREAD

**Issue by unutilisateurdegoogle** [electron/electron#32027]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0-beta. 12

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19043. 1348

### What arch are you using?

x64

### Last Known Working Electron version

No versions.

### Expected Behavior

This is the log : 
```

Publish
Saving files to temp directory...
Saved files to C:\Users\ADMINI~1\AppData\Local\Temp\tmp-4728-2Veqoh3W4Z4Q
Electron v13.0.0-beta.12 started.
#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 000000A4227FEDC0
1: 00007FF7F6BD1B1F node::OnFatalError+76287
2: 00007FF7FA2AB18A Cr_z_zError+2601562
3: 00007FF7F5FE1DE0 v8::Isolate::Initialize+736
4: 00007FF7F6A8A3C2 IsSandboxedProcess+540674
5: 00007FF7F59E9C9F std::__1::__vector_base<v8::CpuProfileDeoptFrame,std::__1::allocator<v8::CpuProfileDeoptFrame> >::__alloc+91199
6: 00007FF7F59E09AB std::__1::__vector_base<v8::CpuProfileDeoptFrame,std::__1::allocator<v8::CpuProfileDeoptFrame> >::__alloc+53579
7: 00007FF7F633594E uv_timer_set_repeat+686990
8: 00007FF7F63398C6 uv_timer_set_repeat+703238
9: 00007FF7F633547C uv_timer_set_repeat+685756
10: 00007FF7F5F8235F cppgc::SourceLocation::Current+1265855
11: 00007FF7F5F81036 cppgc::SourceLocation::Current+1260950
12: 00007FF7F591ECA6 cppgc::NameProvider::HideInternalNames+36262
13: 00007FF7F881A4C2 Cr_z_deflate+4717378
14: 00007FFA6ACE7034 BaseThreadInitThunk+20
15: 00007FFA6B2A2651 RtlUserThreadStart+33
Electron exited with code 3221225477.
```

### Actual Behavior

It gives me the error 3221225477 and it crashes. (The program)

**Comment by jkleinsc** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug by checking your test against different OSes and Electron versions.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
