### ISSUE TITLE
The application doesnt load it only shows gray [Bug]: 

### ISSUE THREAD

**Issue by Danialnerd** [electron/electron#32036]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.10

### What operating system are you using?

Windows

### Operating System Version

windows 21H1

### What arch are you using?

x64

### Last Known Working Electron version

this is the first time im using this so ive never had it functioning

### Expected Behavior

i excepted it to let me paste my bot token so i can use the bot from the inside

### Actual Behavior

it doesnt load and only shows a gray color 
![image](https://user-images.githubusercontent.com/95187507/143783136-8fd9fd61-e017-47d3-9f3c-363dfcde65be.png)

**Comment by queckly** [comment]
same

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
