### ISSUE TITLE
[Bug]: Can't get smaller height

### ISSUE THREAD

**Issue by Ademking** [electron/electron#32038]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

![image](https://user-images.githubusercontent.com/12462188/143810738-e4a78726-9e56-46ab-b535-6eb43b804351.png)

### Actual Behavior

I can't get smaller height... It's always the same.

**Comment by jkleinsc** [comment]
This is intended behaviour.  Windows have minimum size constraints and as documented [here](https://www.electronjs.org/docs/latest/api/browser-window#winsetsizewidth-height-animate), the window will snap to its minimum size.
