### ISSUE TITLE
[Bug]: doubleclick can't maximize window when set tranparent:true frame:false

### ISSUE THREAD

**Issue by famingyuan** [electron/electron#32039]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.8

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Expected Behavior

when I doubleclick a drag area , I hope the window will be maximized.

### Actual Behavior

window can't be maximized

### Additional Information

I test this in electron fiddle with electronV13.1.8 .

```
// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')
const path = require('path')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    frame:false,
    transparent:true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()
  
  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.

 ```

```html
 
    <div class="abc">aaaaaaaaaaa</div>
 
    <style>
      body{
        background: #fff;
        border: 2px solid red;
      }
      .abc{
        background:blue;
        height:300px;
        -webkit-app-region: drag;
      }
    </style>
  
```

I hope the window will be maximized  when i doubleclick the draggable area . it can't work.

But when I set transparent to false , It works .  But I need the transparent.

**Comment by FatShen3** [comment]
same issue 😭

**Comment by iiiMaximus** [comment]
same issue

**Comment by pushkin-** [comment]
should this be closed as a dupe of [this](https://github.com/electron/electron/issues/32502)
