### ISSUE TITLE
[Bug]: inside of window is not aligned with the frame

### ISSUE THREAD

**Issue by TopGamerPro16** [electron/electron#32037]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 verson 21H2, build: 22000.3198

### What arch are you using?

x64

### Expected Behavior

I was expecting for the mouse to work right and the window to be inside the frame.
<img width="587" alt="ice_screenshot_20211128-155240" src="https://user-images.githubusercontent.com/71800648/143787527-ef587c15-cdd4-4db0-8b2d-278f748254db.png">
i dont think the black space in the bottom and right is normal.

### Actual Behavior

window is dettached (it moves with the mouse, but it is a little separated from the frame)

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
