### ISSUE TITLE
[Bug]: Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by oyeaono** [electron/electron#32031]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Windows

### Operating System Version

win19

### What arch are you using?

x64

### Last Known Working Electron version

16.0.2

### Expected Behavior

正常运行

### Actual Behavior

程序打包之后运行，控制台报错Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
js css文件加载失败，界面无法显示
vue + electron

代码
// splash.js
const path = require('path')
const {
  BrowserWindow, Menu, app,
  protocol
} = require('electron')
const Common = require('../utils/common')
const loadPath =
  app.isPackaged
    ? `file://${__dirname}/splash.html`
    : 'http://127.0.0.1:8080/#/splash.html#/splash'

const preload =
  app.isPackaged
    ? path.join(__dirname, '/preload.js')
    : path.resolve(__dirname, '../src/preload.js')

new BrowserWindow({
      width: Common.LOADING.WINDOW_SIZE.width,
      height: Common.LOADING.WINDOW_SIZE.height,
      useContentSize: true,
      show: true,
      maximizable: false,
      frame: false,
      transparent: true,
      resizable: false,
      center: true,
      autoHideMenuBar: true,
      alwaysOnTop: true,
      icon: 'assets/icon.png',
      titleBarStyle: 'hidden',
      webPreferences: {
        contextIsolation: true,
        preload: preload,
        enableRemoteModule: true,
        nodeIntegration: true,
        skipTaskbar: false,
        webSecurity: true
      }
    })

// vue.config.js
module.exports = {
  pages: {
    index: {
      entry: 'src/main.js',
      template: 'public/index.html',
      filename: 'index.html'
    },
    splash: {
      entry: 'src/renderer/splash/main.js',
      template: 'public/index.html',
      filename: 'splash.html'
    }
  },
  pluginOptions: {
    electronBuilder: {
      preload: 'src/preload.js'
    }
  },
  lintOnSave: false,
  publicPath: process.env.NODE_ENV === 'production' ? './' : '/'
}

**Comment by oyeaono** [comment]
![1638026414(1)](https://user-images.githubusercontent.com/48094421/143687097-319f9dab-3d4c-4909-ad54-792d8cca2588.jpg)

**Comment by oyeaono** [comment]
<img width="731" alt="1638026664(1)" src="https://user-images.githubusercontent.com/48094421/143687214-bb1ecf4f-1096-4a57-ab08-0c687a363459.png">

我看打包后的文件路径多了   app://   导致的加载失败

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. 

This seems be a question about Vue specifically; looking at your code, I think you need to change how your paths are resolved. I would recommend trying the [Vue forum](https://forum.vuejs.org/) to answer your specific question. There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by oyeaono** [comment]
这不是vue的问题啊，vue里根本没有app://路径，这是用了electron之后打包成exe应用之后出现的问题，为什么给我关了。。

**Comment by oyeaono** [comment]
> 感谢您联系并记录此问题！因为我们将问题列表视为团队的待办事项，所以我们会关闭作为问题的问题，因为它们不代表需要完成的任务。
> 
> 这似乎是一个关于 Vue 的问题；查看您的代码，我认为您需要更改路径的解析方式。我建议您尝试使用[Vue 论坛](https://forum.vuejs.org/)来回答您的具体问题。[Discord](https://discord.gg/electron)中还有很多乐于助人的人，他们应该愿意为您指明正确的方向——我们有许多积极的帮助渠道和导师，以及可以帮助您的开发人员。

这不是vue的问题啊，vue里根本没有app://路径，这是用了电子之后打包成exe应用之后出现的问题，为什么给我关了。
