### ISSUE TITLE
win.loadFile (local file) is stuck if application is called by Windows service

### ISSUE THREAD

**Issue by RonnyRen** [electron/electron#32044]
Hi Electron team,
How are you going?
 I ran into a strange problem with the almost version (15.3.1). 
Code snippet:
Main.js
`     win = new BrowserWindow({
            show: false,
            webPreferences: {
                enableRemoteModule: true,
                contextIsolation: false,
                nodeIntegration: true,
            },
        });
         win.loadURL('file://' + __dirname + '/core/download.html');
        require("@electron/remote/main").enable(win.webContents);
`
Download.html
`<!DOCTYPE html><html lang="en" ng-app="acdAgent"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Test</title></head><body >
<script src="download.js"></script>
</body></html>`

Download.js
`const remote = require('@electron/remote');
            let win = remote.getCurrentWindow();
            const app = remote.app;
           app.exit(0);
`
It worked well if running the application with command line: I saw the application launched (process in Task manager) and exit.
It didn't work if calling the application with Windows service.: I saw the application launched (process in Task manager)  but never exit.
I tired on Windows Server 2012, 2016 and 2019, all of them don't work. Before upgrading Electron, both command line and Windows service worked well with Electron v8.1.1.

What extra configuration should I configure? I tried some related to safety, none worked. Is there a workaround to fix it? Or how could I know what happened when it was stuck? 
Could you please help provide some suggestions or ways to debug it? Thank you in advance.

Thanks,
Ronny

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by RonnyRen** [comment]
Hi John,
Thanks for your response. I did a try with more versions. Both command line and Window service call work in Electron 13.6 version no matter using old remote syntax or using new module @electrion/remote. When I used Electron 14.0, Windows service call didn't work, I guess it is related to a breaking change about remote module was actually removed in Electron 14.0. please help confirm if it is a bug related to this breaking change or other features, or new Electron version don't allow Windows service call in the future because of secure issue.
