### ISSUE TITLE
[Feature Request]: Implement getLastFocused* helper functions

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#32051]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There are some convenience functions available that are good because they avoid unnecessary bookkeeping at the app level and don't require passing extra arguments around to third-party modules that live outside of the code that does the bookkeeping, like BrowserWindow.getAllWindows, BrowserWindow.getFocusedWindow and webContents.getFocusedWebContent.

IMO at least a couple more could be added, I propose:

- BrowserWindow.getLastFocusedWindow: this returns the last window that got the focus, accounting also for when windows are opened and closed/destroyed (like it shouldn't return a destroyed window).
- BrowserWindow.getLastFocusedWebContent: same as the other one, but for webcontents.

### Proposed Solution

Implementing those funcitons.

### Alternatives Considered

Doing the tedious manual bookkeeping myself.

### Additional Information

Example use case: an app protocol is triggered (like myapp://foo), assuming the main process forwards those requests to the window, which window should it forward it too? Probably the last focused one IMO.

**Comment by MarshallOfSound** [comment]
This is relatively application specific and is easily implementable as a stack data structure in userland code.  Just listening for `close`, `focus`, `blur` and `web-contents-created` events should be enough to implement the system you want.  Electron shouldn't IMO be implementing helper methods just for convenience, it's just more maintenance burden for us.
