### ISSUE TITLE
[Feature Request]: App "browser-window-closed" event

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#32050]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There's already a "browser-window-created" available from the "app" object, but the symmetric one for when a window is closed is not provided.

### Proposed Solution

Implement a "browser-window-closed" event.

### Alternatives Considered

Tracking that for each window individually, which is ok for my use case, but being able to use a "browser-window-closed" would be a bit cleaner.

**Comment by fabiospampinato** [comment]
It may be nice to have a "browser-window-destroyed" too.

**Comment by RaisinTen** [comment]
Why do you want to track these events? Do you have a use case in mind?

**Comment by fabiospampinato** [comment]
The utility of those events is similar to the utility of the "close" event on each window, sometimes you want to do something when windows are closed.

An example use case could be keeping track of all the windows opened, or keeping track of the last focused window, but done in a non-leaky way where the window being opened or the code that opens it don't have to know that that bookkeeping is even happening.

**Comment by RaisinTen** [comment]
That seems reasonable. For this use case, I think we just want to expose one event listener that would forward destroy calls to the BrowserWindows because that would guarantee that the window actually got closed unlike the case of calling close, which might eventually fail to close the window.

**Comment by miniak** [comment]
```
app.on('browser-window-created', (event, window) => {
  window.once('closed', () => {
    console.log('window closed')
  })
})
```

**Comment by fabiospampinato** [comment]
@miniak By that reasoning you don't _need_ `browser-window-created` either. A `browser-window-closed` event would make some code cleaner compared to the example snippet you provided.
