### ISSUE TITLE
[Bug]: `process.exit()` or `app.exit()` does not exit the app instantly after the ready event is emitted

### ISSUE THREAD

**Issue by RaisinTen** [electron/electron#32060]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

macOS

### Operating System Version

12.0.1

### What arch are you using?

x64

### Expected Behavior

The app should exit with the error code set to `1`.

### Actual Behavior

The app exits with the error code set to `0`.

### Testcase Gist URL

https://gist.github.com/RaisinTen/ced9932fd0d76dd30ec72758bc18bc51

### Additional Information

I couldn't reproduce the issue on Parallels Linux.

**Comment by codebytere** [comment]
@RaisinTen dug into this a tiny bit and it looks like what's happening is that the first call is slow, so it trips down into the second call and then that's the exit code you end up seeing.

If you modify your repro to 
```js
const { app } = require('electron');

function tearDown(err) {
  if (err) {
    console.error(err);
    process.exit(1);
  }
}

process.on('uncaughtException', tearDown);

app.on('ready', () => {
  throw 'An uncaught exception!';
});
```

you'll find it _does_ exit with 1.

**Comment by RaisinTen** [comment]
@codebytere yes, exactly! The Node.js documentation for `process.exit()` - https://nodejs.org/api/process.html#processexitcode says:
> The process.exit() method instructs Node.js to terminate the process **synchronously** with an exit status of code.

The synchronous nature of the function should prevent any sort of race conditions of this sort, right?

**Comment by codebytere** [comment]
Ah ok! Our code for this is [here](https://github.com/electron/electron/blob/bec47f54f419f6b910da8bc999a52d91e3b9d53b/shell/browser/browser.cc#L94-L117) - i can try to dig in a little more 🤔

**Comment by RaisinTen** [comment]
Sent a fix: https://github.com/electron/electron/pull/32831!

**Comment by RaisinTen** [comment]
bump

**Comment by sanperrier** [comment]
@RaisinTen, you can use `process.reallyExit()` - it is undocumented, but works

original `process.exit()` in Node 18 looks like this:
```
function exit(code) {
    process.off('exit', handleProcessExit);

    if (code || code === 0)
      process.exitCode = code;

    if (!process._exiting) {
      process._exiting = true;
      process.emit('exit', process.exitCode || 0);
    }
    // FIXME(joyeecheung): This is an undocumented API that gets monkey-patched
    // in the user land. Either document it, or deprecate it in favor of a
    // better public alternative.
    process.reallyExit(process.exitCode || 0);

    // If this is a worker, v8::Isolate::TerminateExecution() is called above.
    // That function spoofs the stack pointer to cause the stack guard
    // check to throw the termination exception. Because v8 performs
    // stack guard check upon every function call, we give it a chance.
    //
    // Without this, user code after `process.exit()` would take effect.
    // test/parallel/test-worker-voluntarily-exit-followed-by-addition.js
    // test/parallel/test-worker-voluntarily-exit-followed-by-throw.js
    nop();
  }
```
