### ISSUE TITLE
[Bug]: BrowserWindow.webPreferences.additionalArguments cannot contain a "\" (broken since v14.x.y)

### ISSUE THREAD

**Issue by reZach** [electron/electron#32064]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version 20H2

### What arch are you using?

x64

### Last Known Working Electron version

13.3.0

### Expected Behavior

I expect that I am able to pass in a string into **additionalArguments** that contains a "\\". This functionality is no longer working in v14.0.0 (I also tested and see that it is broken in v16.0.0 as well).

**Sample snippet (full repo is in "Additional Information" section)**
```js
let win = new BrowserWindow({
    width: 800,
    height: 600,
    title: "Title",
    webPreferences: {      
      additionalArguments: ["test"], // okay      
      additionalArguments: [`path:${app.getPath("userData")}`], // breaks
      preload: path.join(__dirname, "preload.js")      
    }
  });
```

### Actual Behavior

I piggy-back off of additionalArguments in order to send a filepath to code that executes in the preload script.

_I expect this to work_
```js
let win = new BrowserWindow({
    width: 800,
    height: 600,
    title: "Title",
    webPreferences: {      
      additionalArguments: [`path:${app.getPath("userData")}`],
      preload: path.join(__dirname, "preload.js")      
    }
  });
```

### Additional Information

Problem file in repo exists **@app/electron/main.js**

**Steps to repro**
```
git clone https://github.com/reZach/bad-upgrade.git
cd bad-upgrade
npm i
npm run dev
```

**Comment by reZach** [comment]
@jkleinsc checking in - has there been any progress on this?

**Comment by Arkellys** [comment]
I have a similar problem with Electron `19.0.4`, except it's not the `\` that breaks it but the prefix used.

```js
additionalArguments: ["test\\"] // Works
additionalArguments: [app.getPath("userData")] // Works
additionalArguments: [`appFolderPath=${app.getPath("userData")}`] // Doesn't work
```
I managed to make it work only when I write the prefix starting with a specific pattern, either `X:` or `--` (like the other arguments):

```js
additionalArguments: [`X:${app.getPath("userData")}`]
additionalArguments: [`P:ath=${app.getPath("userData")}`]
additionalArguments: [`--appFolderPath=${app.getPath("userData")}`]
```

Is it a bug or is there a reason for that?
