### ISSUE TITLE
[Feature Request]: Command line flag to force a more conservative memory usage

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#32065]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

V8 allocates a significant percentage of the heap (I'd say ~30%/15MB eyeballing it) for potential future use, and Blink seems to be doing the same (it seems with much higher absolute numbers), especially if there's a large amount of RAM available in the system.

Since the behavior of those engines was designed with the browser in mind, and since my app is most definitely not a browser and I have much more knowledge/guarantees about its future memory needs, would it be possible to expose some kind of command line flag or API for forcing a more conservative memory usage?

IMO memory usage is something that people complain the most about Electron apps, having some more levers to pull in that regards would be beneficial. Currently I can only try to use efficient data structures and fix memory leaks, but Electron just seems to allocated a lot of memory just in case, and I currently have no control whatsoever on that.

### Proposed Solution

I'd like to have a command like flag or some kind of API for this.

Something like `--force_conservative_memory_management` or `app.forceConservativeMemoryManagement` or something.

### Alternatives Considered

I can't think of any reasonable alternative.

**Comment by miniak** [comment]
Feel free to open a PR addressing this issue
