### ISSUE TITLE
[Bug]: Support for extending the interfaces of event emitters

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#32067]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

macOS

### Operating System Version

Monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Some objects extend EventEmitter: BrowserWindow, WebContents, app, so naturally they can be used to emit custom events too, that's pretty convenient.

When emitting custom events though the interface of those objects must be extended in order to have proper type checking.

Given the way those objects are defined in electron.d.ts I'm not sure they can be extended via declaration merging, if it's possible I'm not sure how to do it.

### Actual Behavior

I can't figure out how to extend those objects in order to add a custom event to them.

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by fabiospampinato** [comment]
@jkleinsc So are you saying that they can be extended but I've just been unable to do that?

I'm asking because if that's not the case then this is a bug, if that's the case sure, my bad, I'll look again at the documentation to try to find a solution to this.

**Comment by miniak** [comment]
you can do this
```js
const { EventEmitter } = require('events'):
class FooBar extends EventEmitter {
}
```

**Comment by fabiospampinato** [comment]
@jkleinsc @miniak can this be reopened?

As I said it doesn't look like the list of events is extendable, I tried the following:

```ts
declare namespace Electron {
  class BrowserWindow extends NodeEventEmitter {
    on(event: 'foo', listener: any) : this;
    once(event: 'foo', listener: any) : this;
    addListener(event: 'foo', listener: any) : this;
    removeListener(event: 'foo', listener: any) : this;
  }
}
```

And still TS doesn't recognize the event when writing code like this:

```ts
import {BrowserWindow} from 'electron';

const mainWindow = new BrowserWindow({
  width: 800,
  height: 600
});

mainWindow.on ( 'foo', () => {} ); // Still error
```

**Comment by fabiospampinato** [comment]
My bad, I had to write it as an interface:

```ts
declare namespace Electron {
  interface BrowserWindow extends NodeEventEmitter {
    on(event: 'foo', listener: any) : this;
    once(event: 'foo', listener: any) : this;
    addListener(event: 'foo', listener: any) : this;
    removeListener(event: 'foo', listener: any) : this;
  }
}
```
