### ISSUE TITLE
[Bug]: Some windows no longer render on Windows 7 with Electron 13.6.1 and above

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#32072]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.6.1

### What operating system are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

x64

### Last Known Working Electron version

13.6.0

### Expected Behavior

Patch version update does not change window rendering behavior on any OS

### Actual Behavior

Windows 7 fails to render some windows after upgrading to 13.6.1

### Testcase Gist URL

N/A

### Additional Information

I can't find any pattern in settings for these windows so far. They're secondary and tertiary windows of the application. For some reason the primary window renders without issue.

The issue also affects the taskbar previewer as seen here - the "Settings" window is not rendered. Checking window size/position - and re-centering the window make no difference.
![image](https://user-images.githubusercontent.com/6835891/144164735-48df69dc-0b71-4d90-b11c-f043fe746b87.png)

I manually "bisected" Electron versions and arrived at 13.6.0 as the last known good version.

I feel all but certain the cause is #31550

**Comment by Slapbox** [comment]
Bump. I'm concerned about not being able to upgrade our project past 13.6.0 due to this issue.

**Comment by deermichel** [comment]
@Slapbox If this is caused by the PR you referenced, please try a newer version with the fix from https://github.com/electron/electron/pull/31768 (e.g. latest v13). Otherwise, please provide a repro fiddle.

**Comment by Slapbox** [comment]
@deermichel thanks for the update! This is indeed fixed in `13.6.9`.

**Comment by deermichel** [comment]
Great, thanks for the update!
