### ISSUE TITLE
[Bug]: dialog will not work as expected when  the parent is undefined / null 

### ISSUE THREAD

**Issue by idanwork** [electron/electron#32073]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.3

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7, macOS Monterey 12.0.1

### What arch are you using?

x64

### Last Known Working Electron version

13.6.3

### Expected Behavior

using _dialog.showMessageBox_ with parent = _null_ / _undefined_, any dialogs should be "owned" by the application and should be visible regardless if any browser window exist.

```dialog.showMessageBox(null, { message: "this is a message box"});```

This used to work in V13

I saw this behaviour also in the *Electron-Fiddle* - see "Additional Information"

### Actual Behavior

when calling _dialog.showMessageBox_ with parent = _null_ / _undefined_  the application will pulsate the icon in the dock but the app will not show dialog at all (on macOS Monterey there' a flicker as if a dialog is shown but closes immediately) 

The app hangs and can only be closed using "Force quit"

### Testcase Gist URL

~~https://gist.github.com/idanwork/dc63d1eb0bc5f6bd9f4c4881dd44cd14~~
Updated gist 18 Jan 2021 with Electron 16.0.7 
https://gist.github.com/idanwork/fd500de39a18617f3346d722b5faecb1

### Additional Information

Funny, I tried to download and run _Electron Fiddle_ and experience the same issue when I tried to run it from the "downloads" folder, it probably tried to popup the _"I can move myself to the applications folder..."_ message

I looked at the release notes for the major versions 14, 15, 16 I didn't see breaking change regarding this,
also in the doc I see the _BrowserWindow_ is still optional param
https://www.electronjs.org/docs/latest/api/dialog#dialogshowmessageboxbrowserwindow-options

**Comment by idanwork** [comment]
Looks like I've missed something in the release notes, 
seems like it's resolved in electron 16.0.4

**Comment by jaydoherty** [comment]
I am having this same issue on 15.3.4. 
```
dialog.showMessageBox(null, options); //works fine on Windows 10, but crashes on MacOS Big Sur
dialog.showMessageBox(new BrowserWindow(), options); //works fine on both Windows and MacOS
```
Should I just upgrade to 16.0.4?

**Comment by idanwork** [comment]
I started writing more info then noticed that I use different overload (with only the options) so this may be your case:
```typescript
dialog.showMessageBox({
		type: "question",
		message: "some title",
		detail: "some message",
		buttons: ["Button 1", "Button 2"],
		defaultId: 1
	})
```
Also I wasn't sure if you need to actually send something in the options in your example it's empty (no message) might worth a shot if it has something required there.


More info,  generally I see this issue is not recurring with Electron 16.0.4 => 16.0.7,
I saw it on working on with Electron 16.0.4 on multiple macOS systems like Catalina/Bigsur (some are non-dev computers if this helps you in any way).

Just did a retest with Electron 16.0.7 on:
1. M1 - Monterey 12.1  (non - dev machine)
2. X64 Catalina 10.15.7 (dev environment)
And got the dialog as expected.

**Comment by jaydoherty** [comment]
I tried out a few of your suggestions but I still always see this issue on my machine. I re-ran the test on 16.0.7 using the code you suggested:
```javascript
app.on('ready', () => {
  dialog.showMessageBox({
    type: "question",
    message: "some title",
    detail: "some message",
    buttons: ["Button 1", "Button 2"],
    defaultId: 1
  });
});
```

More info: I see the dialog flash on screen for less than 1 second (faster than I can click on it) and then disappear, after that Electron shows a completely unresponsive blank BrowserWindow, and I have to force quit. After reading your original post again, I tried downgrading to Electron 13 and that fixed it. However, I'd really rather not do that.

Last known working version of Electron: 13.6.7
Tested and not working: 16.0.7, 15.3.5, 15.0.0, 14.2.4, 14.0.0

My Operating System: MacOS 11.6 Big Sur (I only have one Intel Macbook Pro to test this. I do also use a Windows 10 desktop for some development, but it is running fine with none of these issues)

**Comment by idanwork** [comment]
@jaydoherty ohh, One more thing I didnt mention is that this dialog only comes out when the app is packaged and not with the "electron" executable

**Comment by idanwork** [comment]
Hi @jaydoherty sorry for bumping again, 
I was able to reproduce the error using latest electron-fidlle 

I narrowed the issue down so it happens only if the showMessageBox is called before awaiting browserwindow to load,

```javascript
// Modules to control application life and create native browser window
const {app, BrowserWindow, dialog} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  })

  return mainWindow.loadURL("https://www.electronjs.org/fiddle")
}

app.whenReady().then(() => {
  init();
})

async function  init(){
  await createWindow()

  // If this will be before the createWindow the app will hang
  const r = await dialog.showMessageBox({ type:"question", 
   message: "Will it work?", 
   buttons: ["Yes", "Also Yes but in Blue"], defaultId: 1});
  
  console.log("Value",  r)
}

app.on('window-all-closed', function () {
  app.quit()
})

```

this worked for the sample case,

Anyway you were right about something still off in this behaviour

I've uploaded a gist where the error could be repro, 
https://gist.github.com/idanwork/fd500de39a18617f3346d722b5faecb1
