### ISSUE TITLE
[Bug]: globalShortcuts not working on windows with a game in foreground

### ISSUE THREAD

**Issue by doublep21** [electron/electron#32078]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.6.3

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Expected Behavior

globalShortcuts not working on windows with a game in foreground: working?

### Actual Behavior

globalShortcuts not working on windows with a game in foreground : not working

**Comment by Araxeus** [comment]
Here is a fiddle gist to test globalShortcuts
https://gist.github.com/Araxeus/d0c0597f2b979e5565d2dbc27c93275d
