### ISSUE TITLE
[Bug]: keyup handler in renderer after globalShortcut yields different results on Windows vs Linux/macOS

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#32071]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.12 through 16.0.3

### What operating system are you using?

Other Linux

### Operating System Version

Windows 7/10 vs Linux Mint 20.1/macOS 10.13

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

A keyup handler after a global hotkey press should yield the same results. For example, given the global hotkey <kbd>Ctrl+Shift+Z</kbd> - upon lifting the <kbd>Z</kbd> key a `keyup` handler should show the `event.key` to be `"Z"`.

### Actual Behavior

Upon lifting the Z key:

- **Windows `keyup`**: `event.key === "Z"`
- **Linux `keyup`**: Does not fire until an additional key is released (for example, <kbd>Shift</kbd> and then will show `event.key === "Shift"`

### Testcase Gist URL

https://gist.github.com/9baf20af9b9974397df1fcb5fdcbe093

### Additional Information

I've been unable to test macOS thus far, so I'm not sure which behavior is anomalous.

Is this behavior expected? If not, is it potentially fixable - or are there OS-level limitations preventing that possibility?

**Comment by Slapbox** [comment]
@codebytere any thoughts on this issue? Is this behavior unexpected? 

The odd man out, so to speak, is Windows, so maybe `platform/windows` would be more appropriate?

**Comment by Slapbox** [comment]
Anybody at least know the intended behavior so we determine if this is a bug or a feature request?

----

Similar to this issue: https://github.com/electron/electron/issues/26301

I don't necessarily think `globalShortcut` needs keyup/down handlers, but the fact that the `renderer` process `keyup` behavior differs when you use a `globalShortcut` to show a browser window, makes some things so tough. 

We still haven't found any way to implement our features that doesn't have weird edge cases.

**Comment by Slapbox** [comment]
Bump. Can anyone comment on which behavior is correct and which is aberrant?

**Comment by Slapbox** [comment]
Friendly bump. Can any maintainers comment on which behavior is the intended and which is unintended? @codebytere?

**Comment by Slapbox** [comment]
Friendly bump. Does anyone know which the intended behavior is?

**Comment by Slapbox** [comment]
I'm still curious about which behavior is correct. It would be great to see this fixed.

**Comment by Slapbox** [comment]
Probably not stale. I haven't tested 20.x and above yet but it wasn't resolved last time I specifically tested it (`18.x.x`)

**Comment by Slapbox** [comment]
Haven't tested in a while since we were forced to majorly alter our code to work around this - but I have no reason to believe this is fixed.

**Comment by Slapbox** [comment]
Not stale; though not ever likely to be addressed I think.

**Comment by Slapbox** [comment]
Not stale.

**Comment by Nantris** [comment]
This remains an issue which makes certain behaviors impossible to implement across all supposedly supported platforms.

**Comment by Nantris** [comment]
@ckerr is it possible re-open this? And is there any way to know if this is an Electron issue versus a Chromium one? There's simply no way to work around this issue that I can see given that `keydown`, `keyup`, `keypress`, and `electron-localshortcut` all fail to detect this event.
