### ISSUE TITLE
Backport WebHID API support to Electron 13

### ISSUE THREAD

**Issue by Alex-us** [electron/electron#32087]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Need access to the new experimental WebHID API for communicating with HID devices for Electron ver 13

### Proposed Solution

Backport feature #30213  that allow WebHID APi usage to Electron ver 13

### Alternatives Considered

No alternative solutions

**Comment by miniak** [comment]
Electron 13 is only getting security fixes now.
