### ISSUE TITLE
[Feature Request]: How can I easily view "window.electron.invoke ()" ? Can it be in devtool-network?

### ISSUE THREAD

**Issue by zhangbaojia** [electron/electron#32096]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Before that, I used HTTP request to complete the data reading, which is very convenient to view through devtool network。 now, I changed to IPC"window.electron.invoke ()". Can I still check it through  devtool-network?Or other?

### Proposed Solution

now , ipc request is the text view:
![20211203175917](https://user-images.githubusercontent.com/19427334/144583612-b6c44023-4061-434c-b94e-b480218ef1e8.png)

### Alternatives Considered

HTTP：
![20211203175151](https://user-images.githubusercontent.com/19427334/144583659-f0ab2247-5290-4a4a-bfb1-92dade39b923.png)

### Additional Information

How to view IPC requests in devtool-network?

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
