### ISSUE TITLE
[Bug]:  "Transparent :true" causes win.hide() to fail

### ISSUE THREAD

**Issue by tsoil** [electron/electron#32090]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.4.6 , 11.4.8,13.1.9

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

	options: {
                ...
		transparent: true,
	}
       execute win.minimize(), then win.hide()
       I want the window to disappear

### Actual Behavior

Taskbar also has this window

**Comment by ckerr** [comment]
Hey @tsoil, thanks for reporting this!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use. That way, maintainers triaging bug reports can go straight to testing the same bug you're describing, without having to write a testcase themselves, which can be both time-consuming and has more potential points of failure if the maintainer writing the testcase misunderstands your report.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
