### ISSUE TITLE
[Bug]: The code cannot execute properly after the window is minimized

### ISSUE THREAD

**Issue by aa494661239** [electron/electron#32095]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 企业版 LTSC

### What arch are you using?

x64

### Last Known Working Electron version

10.1.3

### Expected Behavior

When a camera is used to collect videos, the video is still collected after being minimized

### Actual Behavior

When a camera is used to capture video, the video will blink after the video is minimized

### Additional Information

I opened two Windows, one of which wrote the code of video collection. I used a third-party video stream collection component, which collected the video stream and sent it directly to other devices. When this capture window is minimized, the video seen by other devices flashes.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `10-x-y`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
