### ISSUE TITLE
[Bug]: Autocorrect does not work properly on macOS with text replacement

### ISSUE THREAD

**Issue by alex-taffe** [electron/electron#32101]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12.0.1 (21A559)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

On macOS, under system preferences>keyboard>text I have shortcuts setup to replace things like `ill` with `I'll`, `im` with `I'm`, and `id` with `I'd`. Across the system this works as expected. If I type things such as illegal, imagination, or identification, they all type fine. If I type one of those words, then press space, it replaces it properly.

### Actual Behavior

In any Electron based app, including Slack and Mattermost, it overly aggressively applies my shortcuts. For example, if I type `illegal`, it will correct it to `I'llegal`. Similarly, `immediate` will be corrected to `I'mmediate`. I filed a bug with Mattermost last year, but this seems to be an issue with Electron as a whole https://github.com/mattermost/desktop/issues/1410

### Additional Information

Every other app on the system except ones based on Electron are fine with this, including Google Chrome

**Comment by mitchchn** [comment]
Hey @alex-taffe. I've been looking into similar issues related to text replacements in Chromium/Electron but I can't reproduce the one you've described.

With the following settings on macOS 12:

<img width="780" alt="Screen Shot 2021-12-03 at 3 55 56 PM" src="https://user-images.githubusercontent.com/7342119/144671758-73c57581-6346-4b60-b3b7-2ea5fd2e92dd.png">

Both Electron (16.0.2) and Chrome (96) only replace "ill" if it's followed by a space or punctuation, and they don't try to replace "illegal".

The only thing that seems a bit off is that the auto-correct pop-up appears too quickly in the middle of typing, when it should have a bit of a delay:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/7342119/144672213-7877d804-3318-4e68-a614-52f00369e5e0.png">

I think the delay can be fixed upstream, but I'd love to know any more details that would help reproduce this issue.

**Comment by alex-taffe** [comment]
The weird thing is it doesn't always happen for me. Right now it's not doing it (on any text). Next time it does it (usually at least once a week), I'll see what I can do to get replication steps

**Comment by alex-taffe** [comment]
It started happening again. This is on Slack 4.22.1 (51c35f8efc67c664be880f0c0172f00b88a0d9fa@1638874045 (App Store)). It seems to have to do with not being the first word in the string as well as typing speed. If it's the first word I type, it's fine. If I type the word super slowly, it's fine. Additionally, when typing `idiot` here, I type `id` and only the the letter `i` actually appears. The `d` isn't there. Typing the second `i` makes all 3 letters appear. If you type it quickly, it gets corrected to `I'diot`
https://user-images.githubusercontent.com/6820226/145245913-ae44d5b1-40ee-4b80-a5a7-35b04a92b7d5.mov

**Comment by codebytere** [comment]
@alex-taffe or @mitchchn could you perhaps provide a reproducible Fiddle sample?

**Comment by alex-taffe** [comment]
As in jsfiddle.net? I've never done any development with electron before, just using production electron apps such as Mattermost and Slack

**Comment by codebytere** [comment]
As in https://github.com/electron/fiddle, sorry! you can create and export standalone runnable gists.

**Comment by alex-taffe** [comment]
To be honest, I'm not an electron nor js dev, so I'm not really sure where I'm looking to pull this together nor do I have the time to learn it

**Comment by alex-taffe** [comment]
Still an issue in Slack

**Comment by MarshallOfSound** [comment]
> Still an issue in Slack

Please file a ticket with the Slack support team, not directly with the Electron project and if appropriate it will get fielded down to my team at Slack who will _then_ raise an issue (with a repro fiddle and such)
