### ISSUE TITLE
[Bug]: Drag And Drop files to BrowserWindow just doesn't work

### ISSUE THREAD

**Issue by D3W10** [electron/electron#32100]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro  -  21H2  -  22000.348

### What arch are you using?

x64

### Last Known Working Electron version

13.6.1

### Expected Behavior

The application should react to the javascript event `OnDrop` but instead it ignores it completly.

```
// The onDrop event is never triggered
document.getElementById("filesDragAndDrop").addEventListener("drop", () => {
    e.preventDefault();
    // Code
});
```

### Actual Behavior

The event should be run with no problems making `event.dataTransfer.files` accesible.

**Comment by D3W10** [comment]
It still happens on 17 and 18

**Comment by nornagon** [comment]
It works fine, you haven't overridden the `dragover` event which is required for the `drop` event to work correctly. e.g. https://gist.github.com/baaccc1de177d6f3d6ce582d2cc7ea87

see https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/File_drag_and_drop

**Comment by D3W10** [comment]
@nornagon Yeah, that was the issue, I had the `dragover` event there but I removed the `e.preventDefault()` from there making it not to work. Sorry for taking your time with such a easy problem.

**Comment by Slapbox** [comment]
@nornagon sorry to comment here as this isn't exactly the same issue, but should drag and drop to an Electron window that's running in development mode work? It works fine in our packaged application, but we can't drag and drop to the development version which makes debugging certain behaviors quite difficult.

**Comment by nornagon** [comment]
@Slapbox there shouldn't be any difference. This gist works fine for me in unpacked mode: https://gist.github.com/110b00b5ace7c7b3d285a976dc9be4b1

**Comment by Slapbox** [comment]
Weirdly that gist works for us too, on the same machine I had a problem on. I wonder what it could be.

I really appreciate you taking a look. If I discover the cause I'll certainly update here.
