### ISSUE TITLE
[Bug]: x86 electron cannot be installed on an M1 Mac

### ISSUE THREAD

**Issue by theicfire** [electron/electron#32119]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.3

### What operating system are you using?

macOS

### Operating System Version

12.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

14.2.2

### Expected Behavior

- Run `arch -x86_64 /bin/bash`
- Run `npm install --arch=x64 electron@15.3`
- Run `file node_modules/electron/dist/Electron.app/Contents/MacOS/Electron`

You'll notice the arm64 version was installed, but I expected the x86 version to be installed.

### Actual Behavior

The arm64 version was installed.

### Additional Information

This worked fine in 14.2.2:
- Run `npm install --arch=x64 electron@14.2.2`
- Run `file node_modules/electron/dist/Electron.app/Contents/MacOS/Electron`

A workaround that helped me:
```
rm -rf /tmp/fake_sysctl
mkdir /tmp/fake_sysctl
echo "echo 0" >> /tmp/fake_sysctl/sysctl_always_x86
ln -s /tmp/fake_sysctl/sysctl_always_x86 /tmp/fake_sysctl/sysctl
chmod a+x /tmp/fake_sysctl/sysctl
PATH=/tmp/fake_sysctl/:$PATH
```

This was inspired by noticing this PR: https://github.com/electron/electron/pull/29953

I believe that it is that PR that caused the regression. I'm trying to get this script to output "0" and it doesn't seem to matter if I'm running in rosetta mode or not:
```
// Try running with arch -x86_64 node test.js, and you'll still see "1" on the output
const childProcess = require('child_process');
const output = childProcess.execSync('sysctl -in sysctl.proc_translated');
console.log(output.toString());
```

**Comment by poiru** [comment]
This was just fixed by #32266.
