### ISSUE TITLE
[Bug]: Unresponsive event never seems to fire

### ISSUE THREAD

**Issue by schontz** [electron/electron#32118]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

I have the following handler in Electron:
```javascript
  browserWindow.on('unresponsive', () => console.log('unresponsive'));
  browserWindow.on('responsive', () => console.log('responsive'));
```

And something like this in my HTML

```html
<script>
function hang() {
  for (let i = 0; i < 9999999; i++) console.log(i);
}
</script>
<button onclick="hang()">Hang</button>
```

- The app becomes unresponsive and my CPU goes through the roof while the loop runs. 
- Expected behavior: `unresponsive` event is fired.

### Actual Behavior

The `unresponsive` event never fires.

**Comment by schontz** [comment]
Works in newer versions.

**Comment by salujaharkirat** [comment]
@schontz this does not work on the latest version of the electron. I tried with a minimal example where I call `process.hang` from the dev tools but the `unresponsive` is not fired

**Comment by schontz** [comment]
The unresponsive event if for the Chromium web browser, not for the main node process. Hanging the node process will cause it to hang, and it would not be notified of Chromium events.

**Comment by salujaharkirat** [comment]
@schontz i have been encountering a few issues where my electron application in production freezes for a few users randomly. I feel that the main process gets stuck somewhere. In order to debug this I need an event to add as a log so that we actually are aware of what’s causing the unresponsive-ness. Currently it is a black box. For the same reason I was thinking of using the unresponsive event to get the log and as temp fox restart the application. If you can share any insights on how I can approach this it will be really really helpful.

**Comment by schontz** [comment]
There are tools like sentry.io that could be useful for finding the issue. Unresponsiveness is not part of the main process, so it does not apply. Best of luck.

**Comment by rmnbrd** [comment]
Hello @schontz, 
We would be interested to know how you managed to trigger this `unresponsive` event on your side.
Thanks!

**Comment by schontz** [comment]
@rmnbrd Quick and dirty:

1. Open dev tools
2. Run in console: `onclick = () => while (true) console.log(new Date())`
3. Close dev tools
4. Click anywhere in your app
5. Listen for CPU fan 😉
