### ISSUE TITLE
[Bug]: Duplicate PipeWire screencast portal dialogs in Electron 16

### ISSUE THREAD

**Issue by vchernin** [electron/electron#32117]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16

### What operating system are you using?

Other Linux

### Operating System Version

Any Linux on Wayland

### What arch are you using?

x64

### Last Known Working Electron version

v15.3.3

### Expected Behavior

Screencasting works with one working PipeWire/Portal dialog as in previous releases.

### Actual Behavior

When screencasting with an app on Electron 16 duplicate PipeWire/portal prompts are shown. This specific issue does not occur with Chromium 96 (upstream to Electron 16), or in Electron 15.

Tested on Jitsi Meet Electron (now Electron 16) and this [demo app](https://github.com/hokein/electron-sample-apps/tree/master/desktop-capture).

In Jitsi Meet Electron there is an endless loop of prompts [as shown here](https://github.com/jitsi/jitsi-meet-electron/issues/677#issue-1068967622). The many prompts can also lead to [crashes](https://github.com/jitsi/jitsi-meet-electron/issues/677#issuecomment-986197541) (possibly due to the portal being overwhelmed).

In [the demo app](https://user-images.githubusercontent.com/38842733/144923535-ce9f6545-5ac3-4c59-95b2-adba8d1ee750.mp4) I only see up to 2 portal prompts, but typically only one is usable at a time, and even after accepting both prompts it's not guaranteed to work.

This was reported on both GNOME and KDE Plasma Wayland.

### Additional Information

Note: This is a different issue than https://github.com/electron/electron/issues/30652. https://github.com/electron/electron/issues/30652 is about the app itself creating an unnecessary dialog. With #30652 screencasting is still reasonably usable. However, this issue effectively makes screencasting unusable (depending on the app it seems).

Test demo with Electron 16:
```
git clone https://github.com/hokein/electron-sample-apps
npm install -g electron@16
electron ./electron-sample-apps/desktop-capture --enable-features=WebRTCPipeWireCapturer
```
Electron 15 instead:
```
npm install -g electron@15
electron ./electron-sample-apps/desktop-capture --enable-features=WebRTCPipeWireCapturer
```

With Jitsi Meet Electron simply install it (e.g. with Flatpak), start a new meeting and screen share.

**Comment by joshua-stone** [comment]
I can confirm that this doesn't work on my system either.

https://github.com/flathub/org.jitsi.jitsi-meet/issues/39#issuecomment-1002190308

**Comment by monosoul** [comment]
Happens with Slack in Fedora 35 as well

**Comment by vchernin** [comment]
So with `v17.0.0-beta.6` the portal dialog doesn't even appear anymore. With `v16.0.7` the bug is still the same as above, you get too many dialogs.

@grulja by any chance, do you have ideas what to test/look for here? This is a recent PipeWire regression with Electron 16 (stable) and now 17 (beta) too.

**Comment by monosoul** [comment]
BTW, screen sharing in Chromium doesn't work for me at all: when I try to share a screen with PipeWire from Wayland, Chromium just crashes. I reported this bug [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1290566).

**Comment by vchernin** [comment]
The original bug reported here is fixed (electron 16 created extra dialogs)
