### ISSUE TITLE
[Bug]: Application crashes with EXCEPTION_ACCESS_VIOLATION_READ

### ISSUE THREAD

**Issue by juniopereirab** [electron/electron#32120]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.3

### What operating system are you using?

Windows

### Operating System Version

Windows 8 NT 6.3.9600 17415

### What arch are you using?

x64

### Expected Behavior

Application does not crash on Windows 8 and 7

### Actual Behavior

Application crashes

### Additional Information

I am making a fancy notifier. 

Basically I have an external API which is connected with my Electron Application using Websocket Protocol. Every a certain amount of time my API checks if a new order has arrived and if it does the API make an EMIT call to Electron App.

When the electron app receives that event, it calls that event from renderer process to the main.
And the main process restore or minimize the window with the notification sound.

<img width="576" alt="Captura de Tela 2021-12-06 às 21 44 41" src="https://user-images.githubusercontent.com/17153869/144945430-b8121736-4088-4047-a089-d71bc2ef8be4.png">

I setTImeout the restore function because at [#21614](https://github.com/electron/electron/issues/21614) this was the cause of this bug. But the bug persists anyway.

I have configured a integration with BugSplat to see a potencial cause for this errors. And that's what I've got.

## Stack Key 
electron.exe!void base::ObserverList<blink::MemoryUsageMonitor::Observer,0,1,base::internal::CheckedObserverAdapter>::AddObserver(class blink::MemoryUsageMonitor::Observer *)(271) 

## Exception Code 

EXCEPTION_ACCESS_VIOLATION_READ

## Function 

electron.exe!void base::ObserverList<blink::MemoryUsageMonitor::Observer,0,1,base::internal::CheckedObserverAdapter>::AddObserver(class blink::MemoryUsageMonitor::Observer *) 

## Location 
observer_list.h(271)

## Explanation 
EXCEPTION_ACCESS_VIOLATION_READ

<img width="1070" alt="Captura de Tela 2021-12-06 às 21 37 16" src="https://user-images.githubusercontent.com/17153869/144944749-a6657e91-eeba-4205-9e2b-dc74f8b71bff.png">

And also a lot of others information

<img width="1080" alt="Captura de Tela 2021-12-06 às 21 38 07" src="https://user-images.githubusercontent.com/17153869/144944846-f8e1c4fa-ba7f-4131-ad39-b9ec11792b6b.png">

<img width="1080" alt="Captura de Tela 2021-12-06 às 21 38 29" src="https://user-images.githubusercontent.com/17153869/144944893-f74d9158-853d-49bc-b1e9-ff13158a2e3c.png">

<img width="1069" alt="Captura de Tela 2021-12-06 às 21 39 33" src="https://user-images.githubusercontent.com/17153869/144944975-82b5b212-bb4e-4ac9-8a6c-86801d1072bb.png">

**Comment by juniopereirab** [comment]
It happens that on Preload file, I use path.join() function to get a audio file, and use the Audio() constructor from JavaScript to play a sound.
And I think the preload file was trying to access the audio's folder and emit this error, crashing the application.

**Comment by juniopereirab** [comment]
After a lot of work around this problem, I figured out that the Electron App crashes when I call the function "play()" from an HTML Audio Element... At the renderer process it occurs. 

I try to use the "sound-play" library at the main process but I had no success.

**Comment by codebytere** [comment]
Fixed by https://github.com/electron/electron/pull/32046
