### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by panguclick** [electron/electron#32121]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.15

### What operating system are you using?

Windows

### Operating System Version

Windows 10 IMAGE_VERSION:  1.4.7.33

### What arch are you using?

x64

### Expected Behavior

electron crash，use windbg info

CONTEXT:  (.ecxr)
rax=0000000000000000 rbx=0000005aa13fe210 rcx=000064dc01ecda70
rdx=0000005aa13fe210 rsi=0000005aa13fe0b0 rdi=000064dc0495ad20
rip=00007ff7b84a31ea rsp=0000005aa13fe050 rbp=000064dc047862c0
 r8=0000000000000000  r9=000064dc0461aaa0 r10=0000000000ff0000
r11=0000000000000000 r12=0000005aa13fe210 r13=0000000000000002
r14=000064dc01ecdab0 r15=000064dc01ecd980
iopl=0         nv up ei pl nz na po nc
cs=0033  ss=0000  ds=0000  es=0000  fs=0053  gs=002b             efl=00010206
____!electron::AutofillPopupView::AcceptSelection+0x8a:
00007ff7`b84a31ea 488b10          mov     rdx,qword ptr [rax] ds:00000000`00000000=????????????????
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ff7b84a31ea (____!electron::AutofillPopupView::AcceptSelection+0x000000000000008a)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000000
Attempt to read from address 0000000000000000

PROCESS_NAME:  ÕÐÉÌËæÐÐ.exe

READ_ADDRESS:  0000000000000000 

ERROR_CODE: (NTSTATUS) 0xc0000005 - 0x%p            0x%p                    %s

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000000000000000

IP_ON_HEAP:  000035350a6476e5

FRAME_ONE_INVALID: 1

STACK_TEXT:  
0000005a`a13fe050 00003535`0a6476e5     : 00003535`09ae96cd 00007ff7`b854afaa 00007ff7`bccd813e 00000000`0000000c : ____!electron::AutofillPopupView::AcceptSelection+0x8a
0000005a`a13fe058 00003535`09ae96cd     : 00007ff7`b854afaa 00007ff7`bccd813e 00000000`0000000c 00000000`00000000 : 0x00003535`0a6476e5
0000005a`a13fe060 00007ff7`b854afaa     : 00007ff7`bccd813e 00000000`0000000c 00000000`00000000 010064dc`02f01ad4 : 0x00003535`09ae96cd
0000005a`a13fe068 00007ff7`bccd813e     : 00000000`0000000c 00000000`00000000 010064dc`02f01ad4 00007ff7`b91400b5 : ____!Builtins_KeyedStoreIC_Megamorphic+0x50a
0000005a`a13fe070 00000000`0000000c     : 00000000`00000000 010064dc`02f01ad4 00007ff7`b91400b5 00000000`0000000c : ____!`string'+0x1e
0000005a`a13fe078 00000000`00000000     : 010064dc`02f01ad4 00007ff7`b91400b5 00000000`0000000c 00000000`00000000 : 0xc

SYMBOL_NAME:  ____!electron::AutofillPopupView::AcceptSelection+8a

MODULE_NAME: ____

IMAGE_NAME:  ÕÐÉÌËæÐÐ.exe

STACK_COMMAND:  ~0s ; .ecxr ; kb

FAILURE_BUCKET_ID:  NULL_POINTER_READ_c0000005_________.exe!electron::AutofillPopupView::AcceptSelection

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  1.4.7.33

FAILURE_ID_HASH:  {2491c795-4e3f-bafe-e12e-2e3e97ab61be}

Followup:     MachineOwner
---------

### Actual Behavior

Close browserveiw then crash

**Comment by Kilian** [comment]
Please update your ticket with a reproduction and description of the actual and expected behavior, then feel free to re-open the ticket.
