### ISSUE TITLE
[Bug]:  Broken link issue: #32121

### ISSUE THREAD

**Issue by tinubaby** [electron/electron#32122]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows10

### What arch are you using?

x64

### Expected Behavior

In https://www.electronjs.org/community , when we click on get started-(quick start guide), it should open the documentation.

### Actual Behavior

When we click on the quick start guide in https://www.electronjs.org/community, " Page Not found" is shown. The link is broken

**Comment by Kilian** [comment]
Thanks for mentioning. Moved to correct repository.
