### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by conaticus** [electron/electron#32125]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I have recently discovered that it would be a useful feature to be able to filter directories based on whether they were empty or not in an electron dialog.

### Proposed Solution

I had in mind the ability to set this in the `filters` option in the `showOpenDialog` function. It would then be set like so:

```js
await dialog.showOpenDialog({ filters: [
    { hideNonEmptyDirectories: true }
]})
```

### Alternatives Considered

The only current alternative I have to this is to send an alert if the directory selected in the dialog choice is not empty, which of course is not ideal.

**Comment by miniak** [comment]
We can only support attributes that have a corresponding native OS API, which this does not have.
