### ISSUE TITLE
[Bug]: fs.promises.readFile doesn't resolve under playwright

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#32132]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Expected Behavior

When run `node test.js` (electron under playwright) I expect the resulting `document.body` to be equal to the one from `yarn start`.

### Actual Behavior

`fs.promises.readFile` never resolves so the `document.body` isn't updated.

### Testcase Gist URL

https://gist.github.com/indutny-signal/609177f4f6fb041f01ac1516f9f2e20f

**Comment by indutny-signal** [comment]
FWIW, `fs.readFile`'s callback isn't called either.

**Comment by indutny-signal** [comment]
Now that I dig into it, it appears that all electron versions (starting at least from 11-x-y) are affected. I wonder if it is a playwright bug instead?

**Comment by indutny-signal** [comment]
What seems to be important is that playwright should be connected to inspector port. If I just start the app with the port open - it will work fine.

**Comment by lerouxb** [comment]
@indutny-signal can you elaborate on what you mean by "If I just start the app with the port open - it will work fine."? I seem to be experiencing the exact same problem.

**Comment by indutny-signal** [comment]
@lerouxb this is not a fix, but rather an observation. Playwright starts electron with an inspector open on some port. Unless something connects to that port and issues the commands the playwright issues the app works fine without hanging.
