### ISSUE TITLE
[Bug]: Node addon worked expectively within nodejs, but doesn't work within electron.

### ISSUE THREAD

**Issue by faust21** [electron/electron#32137]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux kylin-W515-PGUV-WBY0 4.19.71-6-kr990

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Work as nodejs worked.

### Actual Behavior

Work expectively.

### Additional Information

I'm so confused, and worked for it few days.

I wrote a node-addon compile with node-gyp. It do the follow things:

1. Load ffmpeg static library and open a rtsp or local file.
2. Convert the frame to rgba color to arraybuffer and call to electron's main process.
3. The renderer process handle the data event and render the data to the canvas element.

In nodejs it works.

```
    int status = avformat_open_input(&pFormatContext, url, NULL, NULL);
    if (0 != status) {
        av_log(NULL, AV_LOG_ERROR, "ffmpeg open error: %s\n", av_err2str(status));
        return status;
    }
```

But in electron, the above codes always return `Protocol not found`.
The nodejs version and electron's node version in same major number.

And one wired thing: no that issue in mac m1.

The node-gyp configuration:
```
{
    "targets": [{
        "target_name": "ffmpeg",
        "sources": ["src/ffmpeg/api/addon.c", "src/ffmpeg/api/ffmpeg.c"],
        "include_dirs": [
            "/home/my/ffmpeg_build/include"
        ],
        "libraries": [
            "-L$$PWD/../lib/ffmpeg-kylinux-aarch64",
            "-lavformat",
            "-lavcodec",
            "-lavutil",
            "-lswscale",
            "-lswresample",
            "-lx264",
            "-lx265"
        ]
    }]
}
```

**Comment by miniak** [comment]
Make sure you are building your module correctly https://www.electronjs.org/docs/latest/tutorial/using-native-node-modules
