### ISSUE TITLE
[Feature Request]: BrowserWindowProxy 

### ISSUE THREAD

**Issue by jinshaopu** [electron/electron#32134]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Windows

### Operating System Version

windows10

### What arch are you using?

ia32

### Expected Behavior

const win=window.open()  //get a BrowserWindowProxy object .
win.print()
win.close()//dosn't wait for print over

### Actual Behavior

win.close() should wait for print over

**Comment by miniak** [comment]
Make sure you have `nativeWindowOpen: true`, as `BrowserWindowProxy` is going away #29405

**Comment by jinshaopu** [comment]
thank you.I found my problem @miniak
