### ISSUE TITLE
[Bug]: "Couldn't load plug-in" but only in Windows Dev build.

### ISSUE THREAD

**Issue by NatoBoram** [electron/electron#32144]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^11.4.6

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22000.194

### What arch are you using?

x64

### Expected Behavior

Loading `ppapi-flash-path` should work in these platforms:

* Windows dev
* Windows prod
* Linux dev
* Linux prod
* MacOS prod

### Actual Behavior

It works in these platforms : 

* [ ] Windows dev
* [x] Windows prod
* [x] Linux dev
* [x] Linux prod
* [x] MacOS prod

On Windows, in dev mode, I have this message:

![image](https://user-images.githubusercontent.com/10495562/145515355-10f74d7f-2f7e-4bd9-86af-3e2ebcaf4245.png)

### Testcase Gist URL

https://github.com/BlablalandFun/blablaland-desktop/pull/15

### Additional Information

"dev" mode is using `electron ./dist/main.js`. "prod" mode is using `electron-builder`.

Here's the important bits of the most-working version I could get.

```typescript
function getPluginPath(pluginName: string): string {
  const pluginPath = electronIsDev
    ? path.join("plugins", getPluginPlatform(), process.arch, pluginName)
    : path.join(process.resourcesPath, "plugins", pluginName);

  if (!fs.existsSync(pluginPath)) {
    console.log(pluginPath);
    throw new Error("Le plugin n'existe pas ou n'est pas trouvable.");
  }

  return pluginPath;
}
```
```typescript
const { pluginPath } = getPlugin();
if (process.platform === "linux") {
  app.commandLine.appendSwitch("no-sandbox");
}

// Add Flash Player
app.commandLine.appendSwitch("ppapi-flash-path", pluginPath);
app.commandLine.appendSwitch("disable-http-cache");
```
```typescript
const window = new BrowserWindow({
  title: "Blablaland",
  width: 1280,
  height: 720,
  // fullscreen: true,
  useContentSize: true,
  show: false,
  autoHideMenuBar: true,
  webPreferences: {
    devTools: true,
    plugins: true,
    contextIsolation: true,
  },
});
```

In other issues, people are just misconfiguring their plugin path or the window builder, but in my case it works in prod but not in dev. Also I have binary data from the file.
```log
Hello Electron! pluginPath: plugins\win\x64\pepflashplayer.dll
The file is valid: <Buffer 4d 5a 90 00 03 00 00 00 04 00 00 00 ff ff 00 00 b8 00 00 00 00 00 00 00 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 31340038 more bytes>
```
```yaml
extraResources:
  - "./assets/**"
  - from: "plugins/${os}/${arch}"
    to: "plugins"
    filter:
      - "**/*"
```
I did test manually hard-coding paths to the `.dll`, both for the `ia32` and `x64` version. Invalid path raises the correct error and valid paths show the "Couldn't load plug-in" message.

**Comment by NatoBoram** [comment]
Bump

**Comment by seitbekir** [comment]
> Have you done `app.commandLine.appendSwitch("ppapi-flash-version", "32.0.0.371");` for example?

Yes, I did. But it is still `Couldn't load plug-in` message in the middle of the object

![image](https://user-images.githubusercontent.com/7370602/219655283-e5bcafe0-b93e-4e7e-83bf-bd782a6e4e03.png)

**Comment by ClaytonTDM** [comment]
bump

**Comment by lazuee** [comment]
The cause of the problem is that you've used `app.commandLine.appendSwitch` after `app.whenReady`:

```js
// Wrong
app.whenReady().then(() => {
  app.commandLine.appendSwitch("ppapi-flash-path", pluginPath);
  app.commandLine.appendSwitch("disable-http-cache");

  createWindow();
});
```

```js
// Correct
app.commandLine.appendSwitch("ppapi-flash-path", pluginPath);
app.commandLine.appendSwitch("disable-http-cache");

app.whenReady().then(() => {
  createWindow();
});
```
