### ISSUE TITLE
dam

### ISSUE THREAD

**Issue by thewhen** [electron/electron#32149]
I tried giving it an hour and seeing what happens, but nothing at all. The page stayed like this.

![image](https://user-images.githubusercontent.com/82514638/145666628-8e2a6751-e690-4e89-8e8e-44a92eaebdd3.png)

**Comment by Slapbox** [comment]
This isn't a bug report. Please follow the template or close your issue; or wait for a maintainer to close your issue in January when they return.

**Comment by thewhen** [comment]
My mistake, got it.
