### ISSUE TITLE
[Bug]: webview new-window not work

### ISSUE THREAD

**Issue by QMangoJ** [electron/electron#32145]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS BigSur 11.6 

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0

### Expected Behavior

i expect webview new-window event work

### Actual Behavior

webview new-window not work

### Additional Information

    const webview = document.querySelector('webview');

    if (webview) {
      webview.addEventListener('new-window', e => {
        debounce(this.openWebView(e), 1000, { leading: true, trailing: false });
      });
    }

**Comment by QMangoJ** [comment]
> nativewindopen

okay,  i tried，but it dosen't work, please check, thank you much.

 <webview
            partition="persist:bes"
            id="extension-view"
            style={{ width: '100%', height: '600px' }}
            preload={preloadSrc}
            webpreferences="contextIsolation=false,**nativeWindowOpen=no**"
            src={pageSrc}
          />

**Comment by wangxueliang** [comment]
new BrowerWinodw(webPreferences: {
            nativeWindowOpen: false
        }
    };)
   also add

**Comment by ZerroRt** [comment]
> 

it works on me, thx :D

**Comment by miniak** [comment]
`nativeWindowOpen` has been removed in latest Electron, you need to stop depending on it.
