### ISSUE TITLE
[Bug]: Programs built with "requireAdministrator" configuration cannot run correctly under the super Administrator account

### ISSUE THREAD

**Issue by justdoit366** [electron/electron#32143]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.2.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 1809

### What arch are you using?

ia32

### Expected Behavior

I built the executable file with the following configuration.
![admin3](https://user-images.githubusercontent.com/40790377/145513926-2b0c1633-7777-4ef3-9c0e-6e19d1bfb786.png)
Then when I start the program with the local administrator account, the UAC permission window will pop up. After selecting Yes, the electron window will be displayed correctly. As shown below：
![correctly](https://user-images.githubusercontent.com/40790377/145513836-c172ed8b-1dcd-48b2-a679-8ff75516f1f9.png)
My program is the simplest demo program, the code is as follows
![Code](https://user-images.githubusercontent.com/40790377/145514020-aa983127-245f-426e-ac64-a9a38ae973ec.png)

### Actual Behavior

However, when I start the same program with the Administrator account, the UAC permission window does not pop up, and the electron window is not displayed normally. as follows
![admin1](https://user-images.githubusercontent.com/40790377/145514060-84e56eff-768f-425f-a725-bf4a4bd15897.png)
![admin2](https://user-images.githubusercontent.com/40790377/145514066-bc5b4ef4-fa7e-4e47-9b81-384a19bbb4fa.png)
I don't know why this is happening. Is it because of the request for administrator rights? However, the Administrator account itself has administrator rights.

### Additional Information

I don't know if there is any difference in the Administrator account. According to my observation, it is displayed in the procexp64.exe that under the Administrator account, a process is missing. As follows：
![observer](https://user-images.githubusercontent.com/40790377/145514293-2fbd16e5-2fc2-448e-8f00-7a143f89e5cc.png)
If anyone knows how to fix this problem, please let me know, thank you very much!

**Comment by justdoit366** [comment]
The project is electron-quick-start that I used to test the problem.

**Comment by miniak** [comment]
Running elevated is not supported by Chromium
