### ISSUE TITLE
Not Using remote in modern Electron

### ISSUE THREAD

**Issue by manngo** [electron/electron#32151]
I have an Electron application which I have built mostly from following tutorials. I’m not really clear on the whole main/renderer thing but I think I have an idea.

In my `main.js` file I have something like this:

```js
const {app, BrowserWindow, Menu, MenuItem, shell, ipcRenderer, protocol, ipcMain} = require('electron');
```

From what I can understand, I then need to pass them over to my render process which I have in the script `pager.js`.

In my Electron render process `pager.js` I have used:

```js
const electron=require('electron');
const { ipcRenderer, shell, remote } = electron;
const {app,BrowserWindow,dialog,Menu,MenuItem}=remote;
```

It all worked well enough in the past, but, since upgrading Electron, the whole thing falls apart. I’m now on version 16, and I have learned that `remote` has been deprecated to the point of extinction. I suppose I should have updated my app more often.

I have gone through dozens of web sites all offering some sort of solution, but they all tell me something different. They all recommend something like `require("@electron/remote")`, and various incantations of `enable()` and `initialize()`. I’ve tried whatever I could understand, but in the end, nothing works.

I get the impression that using `remote` is discouraged, and that even `@electron/remote` is considered a workaround, but I just want to get the app working again. I also get the impression that all of this should be done using IPC.

What is the most straightforward way of replacing the old `remote` with something that works?

**Comment by Kilian** [comment]
The electron issue tracker is not a support channel. For help, join our Discord! https://discord.com/invite/H6uTh7m
