### ISSUE TITLE
[Bug]: Cannot enable wayland support in the development environment

### ISSUE THREAD

**Issue by thep0y** [electron/electron#32157]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

Other Linux

### Operating System Version

Linux thepoy-PC 5.15.7-arch1-1

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

Can use flags`--enable-features=UseOzonePlatform --ozone-platform=wayland` to enable wayland support

### Actual Behavior

```
$ ./node_modules/.bin/electron --enable-features=UseOzonePlatform --ozone-platform=wayland

Electron 16.0.4 - Build cross platform desktop apps with JavaScript, HTML, and CSS
Usage: electron [options] [path]

A path to an Electron app may be specified. It must be one of the following:
  - index.js file.
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.

Options:
  -i, --interactive     Open a REPL to the main process.
  -r, --require         Module to preload (option can be repeated).
  -v, --version         Print the version.
  -a, --abi             Print the Node ABI version.
[56141:1212/172713.274621:ERROR:cursor_loader.cc(114)] Failed to load a platform cursor of type kNull
[56176:0100/000000.362612:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is egl, ANGLE is 
[56176:0100/000000.291505:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
/home/thepoy/Develop/electron/emark/node_modules/electron/dist/electron exited with signal SIGSEGV
```

**Comment by vchernin** [comment]
Are you using a Wayland session (`echo $XDG_SESSION_TYPE)? 

Are you using Nvidia? If so try adding `--disable-gpu-sandbox`

**Comment by thep0y** [comment]
```shell
$ echo $XDG_SESSION_TYPE
wayland
```

I am using Intel UHD630, and when I use flag`--ozone-platform=wayland`, electron can run with wayland without error.
