### ISSUE TITLE
[Bug]: while running several applications, only the most recent electron-based application window is shown in GNOME overview

### ISSUE THREAD

**Issue by ilippert** [electron/electron#32158]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

current versions in jitsi and signal

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 35: 5.15.6-200.fc35.x86_64

### What arch are you using?

x64

### Expected Behavior

I use Fedora 35, Gnome via wayland.

In the gnome overview, each application's window should be shown in a smaller version.

### Actual Behavior

![Screenshot from 2021-12-12 12-37-29](https://user-images.githubusercontent.com/20518297/145710998-13f2f00f-7cfb-475f-b42f-6ec3724c2332.png)

In the gnome overview, the small electron-based applications windows show mostly the content of the most recently used electron-based application. the screenshot illustrates that the signal window shows the content from the mattermost window.

### Additional Information

Well, it is the first time I report an issue here. I report it here because I guess electron is responsible for the issue, as it does not happen with the other applications.

**Comment by vchernin** [comment]
Nvidia on EGLStreams? What mutter version?

**Comment by ilippert** [comment]
does not appear anymore
