### ISSUE TITLE
[Feature Request]: adopt to Monterey new feature QuickNote

### ISSUE THREAD

**Issue by iyangdidi** [electron/electron#32159]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

MacOS Monterey has new feature QuickNote. Our product is written with electron, I'm trying to adopt to QuickNote for our app.
1. I there is no QuickNote related information for electron
2. QuickNote is quite similar to handoff, I use setUserActivity to create a UserActivity with the webpageURL, the url can be detect add added to QuickNote app, but
    a. 'continue-activity' never called when I click the links added to QuickNote
    b. for QuickNote for IOS/MacOS native we can add 'title' for UserActivity, but I can't find the surportive for electron

Here is my setting for QuickNote
1. Add <key>NSUserActivityTypes</key> to info.plist
2. Create UserActivity when when new window opened with our contents to view (it's an url which can be visited from browser too).
3. setup the listener for 'continue-activity' to deal with the UserActivity

My question:
1. Is electron support QuickNote?
2. If it is
    a. how to set the title?
    b. why 'continue-activity' never called?

### Proposed Solution

Add support for QuickNote

### Alternatives Considered

Add support for QuickNote

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
