### ISSUE TITLE
[Feature Request]: Electron for Android

### ISSUE THREAD

**Issue by privatedev11** [electron/electron#32150]
I posted this a while ago on #27695 and was told the Electron codebase couldn't handle this, but I've had a different idea of what it could be.

Maybe it could be a really simple webview interface coded in Java instead of node.js

There could be a separate IDE for it, embedded into Fiddle or an addon for Android Studio and/or intellij idea

**Comment by JonathanTreffler** [comment]
I think this is still beyond the scope of electron (I am not a maintainer, so they know better). You could code such a java app for a personal project easily, but it would not be polished enough for an official electron project. Also, i don't think the current build system for electron apps could handle Java and I don't think you would want to have two completely separate build systems for one application.

**Comment by privatedev11** [comment]
I wonder if there would be a way to run Linux applications as a android app, as android is based on Linux. This way,  you could build your app for Linux and run it on android.
________________________________

**Comment by JonathanTreffler** [comment]
No that is not feasible, the Linux Desktop is much more than the Linux Kernel and most of these outer layers are not used by Android.
So while it is technically possible to run Linux Apps on Android it requires heavy modification to the Android OS and pretty much nobody does it. (the only prebuild Android Fork I know that does it is JingOS).

**Comment by privatedev11** [comment]
I understand
________________________________
