### ISSUE TITLE
[Bug]: webFrameMain executeJavaScript doesn't work sometimes

### ISSUE THREAD

**Issue by Tipwheal** [electron/electron#32164]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey

### What arch are you using?

x64

### Last Known Working Electron version

15.3.0

### Expected Behavior

I write some code like this:

1. given a web page with an iframe, iframe and the page url is in **different origin**
2. setup listener in main process(`ipcMain.on`) and wait for message from renderer
3. use preload to inject some code into iframe and mainFrame(the web page)
4. both frames send message via `ipcRenderer` to main process when preload executed
5. after received message from renderer, main process retrieve webFrameMain by `[processId, routing]` provided in event params
6. main process call webFrameMain.executeJavaScript immediately, for every frame that send message to main process

What's expected:

1. The code passed by executeJavaScript to be executed in each frame(the web page and iframe)
2. executeJavaScript asynchronously return execution result of passed code.

### Actual Behavior

1. The code didn't executed in iframe sometimes. Just mainFrame work as expected
2. webFrameMain.executeJavaScript.then(res) got res `null` when execute in the iframe.

extra info was provided in Additional Information

### Testcase Gist URL

[https://gist.github.com/b7714f0812e293339b9a2a08807cf795](https://gist.github.com/b7714f0812e293339b9a2a08807cf795)

### Additional Information

1. if use setTimeout to delay the execution, it **maybe** work in iframe. I tried to delay 10ms、20ms、...200ms and record success rate(test 100times):

| delay | success rate |
| ---- | --- |
| 10ms | about 70% |
| 20ms | about 85% |
| 30ms | about 90% |
| 40ms | about 95% |
| 100ms| about 97% |
| 200ms | 100% |

2. `webContents.sendToFrame` also has similar issue, renderer process **maybe** not receive message even it can successfully send message to main process
3. If preload send message after iframe 'DOMContentLoaded' event, `executeJavaScript` always success
4. After page and iframe fully loaded, just reload iframe(in console, using location.reload()), executeJavaScript works as expected.

**Comment by canvas104** [comment]
```
frame.executeJavaScript(`setTimeout(()=>document.body.style.background = 'black')`)
    .then(res => {
      console.log('res', res);
    })
```
how about use setTimeout inside? what is success rate？
