### ISSUE TITLE
[Bug]: Alt+ click on URL triggers download dialog since e14

### ISSUE THREAD

**Issue by Kilian** [electron/electron#32165]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14+

### What operating system are you using?

Ubuntu

### Operating System Version

18.04

### What arch are you using?

x64

### Last Known Working Electron version

13

### Expected Behavior

When alt-clicking a URL in an Electron app, a new window opens (and this can be prevented by Electron).

### Actual Behavior

When alt-clicking a URL in an Electron app, a save as... download dialog is shown for the linked page (and this can not be prevented).

### Testcase Gist URL

https://gist.github.com/9873724d6cbdb791d63ce28cf33dfc70

### Additional Information

instructions: run the gist with 13 and alt-click a link, observe a new window is opened. Then run the gist with 14 or later and observer a save as... dialog is opened.

This is the likely culprit: https://github.com/electron/electron/pull/29318

**Comment by Prinzhorn** [comment]
I'm seeing the same thing and was expecting `setWindowOpenHandler` to be called with `disposition === 'save-to-disk'`, but the handler is not invoked. I assume that would be the correct place to deny the save dialog? If that's not the right situation, then when is `'save-to-disk'` actually ever triggered?

**Comment by Prinzhorn** [comment]
Still repros in v22.0.0-alpha.1. Weirdly enough it sometimes takes like 5 seconds for the dialog to appear, I don't remember it being like that originally.

**Comment by Prinzhorn** [comment]
Still repros in 22.0.0 and 23.0.0-alpha.3
