### ISSUE TITLE
[Bug]: Icon is GTK but the icon is custom

### ISSUE THREAD

**Issue by zeankundev** [electron/electron#32170]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.3 Focal Fossa

### What arch are you using?

x64

### Expected Behavior

I was trying to set the icon to this.
![icon](https://user-images.githubusercontent.com/58360911/145956576-40225b7f-8d28-4a79-83a5-124f08b99b28.png)
Here is my clear code.
```js
const createWindow = () => {
    const win = new BrowserWindow({
      width: 1024,
      height: 600,
      icon: 'assets/icon.png'
    })
  
    win.loadFile('index.html')
    win.setMenuBarVisibility(false)
}
```
The path is correct.
 

### Actual Behavior

While running and deploying the app, the icon somehow changed to this.
![image](https://user-images.githubusercontent.com/58360911/145956856-c403b621-573c-4d89-8fb6-d67d9f740ab9.png)
And this isn't what I expected.

**Comment by Kilian** [comment]
Gnome uses the icon from the .desktop file. Check where you create and set that during packaging, and make sure it references the correct icon.

**Comment by zeankundev** [comment]
LIke what code should I enter in the main process?

**Comment by Kilian** [comment]
@zeankundev It doesnt happen in the main process. Check out our docs on application distribution: https://www.electronjs.org/docs/latest/tutorial/application-distribution The tools mentioned there take care of creating that .desktop file.

**Comment by zeankundev** [comment]
So what should I do? The docs doesn't have the thing regarding to the issue

**Comment by Kilian** [comment]
Read the docs, pick a tool, follow their docs for packaging, package and install your app and Gnome will know how to pick up that icon.
