### ISSUE TITLE
Frameless window height cannot be lower than 39 on Windows

### ISSUE THREAD

**Issue by virtuecoder** [electron/electron#32171]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 1909

### What arch are you using?

x64

### Expected Behavior

Window height should be 25

### Actual Behavior

Window height is 39

### Additional Information

```
const { app, BrowserWindow } = require('electron');

app.on('ready', () => {
  const win = new BrowserWindow({
    width: 400,
    height: 25,
    frame: false,
    show: false,
    thickFrame: false,
  });

  win.loadURL('https://github.com').then(() => {
    win.webContents.executeJavaScript(
      'document.body.innerHTML = innerHeight;' +
      'document.body.style.boxShadow = "inset 0 0 0 1px lightblue";');
  });

  win.once('ready-to-show', () => {
    win.show();
    win.setSize(400, 25);
  });
});
```

**Comment by Slapbox** [comment]
You can't create a window any smaller than that on Windows, I believe. That's been my experience since many many versions back.

**Comment by virtuecoder** [comment]
Even for the frameless one? If that's the case it must be documented somewhere. Any reference?

**Comment by Slapbox** [comment]
I don't know if it's documented anywhere, this is just my personal experience.

On Windows 7, the smallest Notepad can get is 158px by 45px

![image](https://user-images.githubusercontent.com/6835891/146079434-e1e88ad8-9bfe-4f74-9d32-870257992cf4.png)

**Comment by virtuecoder** [comment]
But the one on the picture has a frame. In my example the window is frameless.

**Comment by miniak** [comment]
@virtuecoder not using a proper title for your bug makes it much less likely to be noticed and fixed.

**Comment by Slapbox** [comment]
@virtuecoder if I'm interpreting this correctly, it seems like the minimum window height should not be 39px, but 29px - so maybe this is a limitation of Electron itself on Windows.

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics

**Comment by virtuecoder** [comment]
Your interpretation does not seem correct because the window height is forced to 39 not 29 px.
This document from Microsoft does not make clear if the minimum height of 29 applies to frameless windows as well.

**Comment by virtuecoder** [comment]
I found the following work around, which might work in my case https://github.com/electron/electron/issues/32302

**Comment by Slapbox** [comment]
Not stale.

**Comment by Slapbox** [comment]
Not stale.

**Comment by Slapbox** [comment]
Not stale, but also maybe not an issue that can be addressed. Could anyone from the Electron team comment?

**Comment by FushimiYuki** [comment]
I met the same question. Anybody Help?

**Comment by virtuecoder** [comment]
The work around I found is using setShape function of BrowserWindow and passing to it an array with the expected rectangle shape.
https://www.electronjs.org/docs/latest/api/browser-window#winsetshaperects-windows-linux-experimental

**Comment by Slapbox** [comment]
If it's generally possible to do this, then I think it should not require any jumping through hoops.

I think the issue should be re-opened to provide matching behavior across platforms, since it seems this is not a hard limitation of Windows.

**Comment by FushimiYuki** [comment]
> The work around I found is using setShape function of BrowserWindow and passing to it an array with the expected rectangle shape. https://www.electronjs.org/docs/latest/api/browser-window#winsetshaperects-windows-linux-experimental

thanks! This works.
