### ISSUE TITLE
[Bug]: Electron crashes when recording on the Performance tab of Dev Tools (on macOS, M1)

### ISSUE THREAD

**Issue by theolivenbaum** [electron/electron#32207]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.0.1

### What arch are you using?

x64

### Last Known Working Electron version

16.0.0

### Expected Behavior

Should be able to use the performance tools to profile an Electron app.

### Actual Behavior

Opening the Performance tab on Electron and clicking on record crashes electron, crash message is:

````
objc[78957]: task_threads failed (result 0x10000008)
````

Seems similar to #28472 but as this is a newer version, I think probably something new.

### Additional Information

To be clear, running an Electron app compiled for x64, using Rosetta on an M1 laptop.

**Comment by theolivenbaum** [comment]
This reproduces on Electron Fiddle with an empty project, on 16.0.4, but not on 16.0.0

On Electron Fiddle, I observe this on the console:

`````
Electron v16.0.4 started.
[80744:1216/131619.972478:ERROR:platform_shared_memory_region_mac.cc(205)] mach_vm_map: (ipc/send) invalid msg-header (0x10000010)

Electron exited with signal SIGTRAP.
`````

**Comment by VerteDinde** [comment]
Hey @theolivenbaum, thanks for reporting this issue and thanks for doing a bisect as well! 

Sorry, do you happen to have a repro link we could use to bisect a bit further? I tried to use a starter Fiddle project on both the x64/Rosetta and arm64 builds of Fiddle, but I unfortunately wasn't able to repro the crash by opening the Performance tab and clicking record. Here's a gist of the project I was using, in case I missed anything: https://gist.github.com/80bf5d2d4ddbe0a57ff735e1e5787d6f . If there's anything I missed or something specific I could try in the gist, let me know!

<img width="930" alt="Screen Shot 2021-12-16 at 9 53 17 PM" src="https://user-images.githubusercontent.com/4624411/146496211-a1cdca6f-cefa-4e99-81aa-a993e75f0a05.png">

**Comment by theolivenbaum** [comment]
For me it reproduced with the empty Fiddle project, didn't have to do anything special.

**Comment by codebytere** [comment]
Duplicte of https://github.com/electron/electron/issues/29627
