### ISSUE TITLE
[Feature Request]: Document Chromium's policy engine

### ISSUE THREAD

**Issue by shacharz** [electron/electron#32203]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Chromium has this "policy engine" (my name for lack of a better one) which allows it to read registry keys on certain paths and resolve that into a configuration change in the browser.
Chrome supports it - https://chromeenterprise.google/policies/
Edge supports it - https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies

I believe Electron also support it, it's just undocumented but I'm not sure.

### Proposed Solution

If the feature exists document it, if it doesn't exist create this functionality to support all those flags listed in both Chrome and Edge's policies.

### Alternatives Considered

For certain policies there is no alternative.
e.g: https://chromeenterprise.google/policies/#WebRtcUdpPortRange

**Comment by shacharz** [comment]
Anyone has any information whether this chromium functionality got stripped in Electron or it still exists ?

**Comment by nornagon** [comment]
We don't support this.

**Comment by shacharz** [comment]
@nornagon Thanks for the reply, would the project accept a PR that adds support for this ?

**Comment by nornagon** [comment]
@shacharz possibly; I'd recommend going through the [API spec process](https://github.com/electron/governance/blob/main/wg-api/design-spec-process.md) for a new API of that size first though.
