### ISSUE TITLE
[Feature Request]: Backport fix for text input performance regression to v16

### ISSUE THREAD

**Issue by chase** [electron/electron#32239]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

This bug has been fixed in Chromium 97, but it has massive impact on performance when using any sort of large input field, most noticeable in rich text fields: https://bugs.chromium.org/p/chromium/issues/detail?id=1271918

Related issues:
https://discuss.prosemirror.net/t/performance-issue-with-chrome-v96/4208
https://github.com/ianstormtaylor/slate/issues/4699
https://jira.atlassian.com/browse/CONFCLOUD-73213

### Proposed Solution

The fix is this commit: https://chromium.googlesource.com/chromium/src/+/d5496a43253193e7aefc658e4fde871ec146542b

It simply reverts: https://chromium.googlesource.com/chromium/src/+/4f6e94d8d4e491c1119b447fe530450684ea701e

### Alternatives Considered

Wait for the next stable release.

**Comment by jkleinsc** [comment]
- main will get this fix via #31986
- 17-x-y will get this fix via #32030
- 16-x-y will get this fix via #32352

**Comment by jkleinsc** [comment]
Closing this issue as all affected branches have the fix applied.
