### ISSUE TITLE
[Feature Request]: How do I fix my application to the desktop

### ISSUE THREAD

**Issue by wdlnydhcg** [electron/electron#32246]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want my app interface to be fixed to the desktop,like a desktop calendar application ,but I can't find an API that provides this functionality. Am I missing it, or does Electron not support it?

### Proposed Solution

Does electron have an API for this function？

### Alternatives Considered

Using DLL is not able to achieve？

**Comment by wdlnydhcg** [comment]
i try use _setIgnoreMouseEvents_  _setAlwaysOnTop_ ，But it's not what I wanted

**Comment by wdlnydhcg** [comment]
I used the attribute type= 'desktop' to fix my problem, but this prevented me from listening for window events。

**Comment by wdlnydhcg** [comment]
> I used the attribute type= 'desktop' to fix my problem, but this prevented me from listening for window events。

and windowOS not support

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
