### ISSUE TITLE
[Feature Request]: webFrame.locateInDOM()

### ISSUE THREAD

**Issue by mckravchyk** [electron/electron#32249]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Suppose that in the current frame there are multiple iframes. I want to locate an iframe element by its frame routing id. There's no way to do that.

For instance I want to get an iframe's position relative to its parent frame. To achieve that I would need to send an IPC call to the parent frame and get the iframe's element position and send it back to the subframe. The problem is that the parent frame is unable to locate the iframe element in DOM given its routing id.

### Proposed Solution

`webFrame.locateInDOM()`

Returns the reference to the element which contains the frame if the frame is represented by an element in the current's frame DOM (i.e. if it's a direct descendant iframe of the current frame). Otherwise returns null.

### Alternatives Considered

There's a very limited alternative available: if the iframe element has a name and assuming that each iframe has a unique name, it's possible to identify it (by getting its name) by calling `webFrame.executeJavaScript('window.name');` - then it's possible to query it in DOM with the name. In my app I'm dealing with third party webpages so it does not help much, many iframes do not have a name.

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
