### ISSUE TITLE
[Bug]: Electron 16.0.5 cannot enable webviewTag in nativeWindowOpen sub window

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#32252]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

Windows

### Operating System Version

10 version 19043

### What arch are you using?

x64

### Last Known Working Electron version

16.0.4

### Expected Behavior

When a sub window opened with `webviewTag` set to true, the webview in sub window should works correctly

### Actual Behavior

In the subwindow, the `webviewTag` option is not actually enabled and webview is not working

### Testcase Gist URL

https://gist.github.com/72a8040c33a7deeebdfe88d409d8ca0b

### Additional Information

In the testcase, type following command in devtool console and press enter:

```js
w = open('./index.html')
setTimeout(() => {
    w.document.querySelector('webview').addEventListener('dom-ready', (e) => console.log(e))
    w.document.querySelector('webview').reload()
}, 100)
```

The console will open a subwindow, but in the subwindow the webview did not load, and the console throws error `w.document.querySelector(...).reload is not a function`

![image](https://user-images.githubusercontent.com/8194131/146691461-36d0ec6c-d1d8-4b90-80f9-15081aaeac62.png)

**Comment by KochiyaOcean** [comment]
I think it should be related to https://github.com/electron/electron/pull/32108/files

**Comment by codebytere** [comment]
cc @miniak @zcbenz

**Comment by zcbenz** [comment]
The previous behavior was actually a security bug, the `new-window` event does not have the ability to override the webPreferences, it only reuses the WebContents created by Chromium, so the passed `webPreferences` is actually ignored. The code used to work because the child window inherited the `webviewTag: true` from parent window directly, which was a bug instead of expected behavior.

The correct way to do it is to use `webContents.setWindowOpenHandler` API instead:

```js
  mainWindow.webContents.setWindowOpenHandler(() => {
    return {
      action: 'allow',
      overrideBrowserWindowOptions: {
        webPreferences: {
          webviewTag: true
        }   
      }   
    }   
  }); 
```
