### ISSUE TITLE
[Bug]: Discord Bot Client not loading for me, can someone help?

### ISSUE THREAD

**Issue by RevArcs** [electron/electron#32268]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.6.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I tried downloading it 4 times, but one was a .ZIP file. There maybe some glitches that happened recently to my Bot Client.

### Actual Behavior

Blank screen

### Additional Information

So I was creating a bot for my discord bot so I can try to login in to it, but it never loads. I tired waiting for minute, hours but still not loading. So can someone tell me how to fix this so I can try to login to my bot? (Twist: I downloading them twice and redownloading it but still didn't work.)

And it just displayed a blank screen, when I opened it.

Screenshots:
![image](https://user-images.githubusercontent.com/85590713/147007437-db3ab250-26e3-4b5c-a807-d2d01d8704a9.png)
![image](https://user-images.githubusercontent.com/85590713/147007569-d12932b9-d874-4c0a-806e-09fbab5c29cf.png)

**Comment by marshasyourip** [comment]
please help me i have the same problem
