### ISSUE TITLE
[Bug]: Mac OS: Launching external command line tool to record audio does not work

### ISSUE THREAD

**Issue by stoefln** [electron/electron#32263]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.2.3

### What operating system are you using?

macOS

### Operating System Version

10.15.7 (Catalina)

### What arch are you using?

x64

### Expected Behavior

When I spawn a process to record audio via "rec" command line tool (part of [sox](http://sox.sourceforge.net/)) I don't get an error but an empty file is recorded (even 5 seconds long, but no audio in there). Since I also didn't find any other option of recording audio in electron under Mac OS ([there seems to be a known bug](https://www.electronjs.org/docs/latest/api/desktop-capturer#caveats)) it almost seems this is a permission problem.
When I execute this command via node.js CLI this works perfectly fine:
`rec --channels 2 temp.aiff trim 0 00:05` (<- expected behaviour: 5 seconds audio with signal)

### Actual Behavior

Empty audio file is created

**Comment by stoefln** [comment]
Bump

**Comment by MarshallOfSound** [comment]
This is a TCC permissions issue, your app needs to have system recording capabilities in order for processes spawned under it to have recording capabilities.

**Comment by stoefln** [comment]
@MarshallOfSound thanks for explaining, but what's TCC?
