### ISSUE TITLE
[Bug]: Windows adding a pixel to window.outerWidth

### ISSUE THREAD

**Issue by ncfausti** [electron/electron#32274]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 8

### What arch are you using?

x64

### Expected Behavior

window.resizeTo(800, 600);
window.outerWidth; // 800

### Actual Behavior

window.resizeTo(800, 600);
window.outerWidth; // 801

### Additional Information

#2952

**Comment by xinyii** [comment]
https://stackoverflow.com/questions/42710882/css-border-1px-appear-as-0-667px-or-1px-depending-on-the-computer-display-res

It may be related to the zoom of your display settings.
