### ISSUE TITLE
[Bug]: Electron app won't die even after calling app.quit()

### ISSUE THREAD

**Issue by hydroflame** [electron/electron#32277]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10, 11

### What arch are you using?

x64

### Expected Behavior

When calling app.quit() the whole process should die.

### Actual Behavior

Ok, I have this really weird issue

I have a game on Steam that uses electron.

The issue comes when closing the app.  I use 

    app.on("window-all-closed", app.quit);

Now for most people this works fine. But I have quite a few report saying that the app does not die and they need to open the task manager to kill the rest.

I believe we have narrowed down the issue to something related to `openExternal`, because the game does have link to documentation on the web.

It seems that opening links via openExternal makes Steam consider that the game is not fully closed even after `app.quit()`

Right now I'm not totally sure what the root cause is, hence why I'm opening this bug report.

It could be that my electron app is really not closed properly, however I've tried everything under the sun to make it die when all windows are closed.

It could be that steam detects that electron opened a different app and considers it part of the program.

So my question is 2 fold.

Does `openExternal` make the electron main process consider the opened browser as part of it's own?

Does `app.quit` (or `process.exit`) kill everything everything? or could there be a strange edge case where some subprocess is still included?

### Testcase Gist URL

https://github.com/danielyxie/bitburner/blob/dev/electron/main.js

**Comment by BryantS11** [comment]
Try writing it like this:
`app.on('window-all-closed', () => {
app.quit();
});`

**Comment by hydroflame** [comment]
Already did that.

**Comment by TommyBacco** [comment]
Check if you're experiencing the same with electron 17.0.0

**Comment by ckerr** [comment]
Hey @hydroflame, thanks for reporting this.

This testcase is not one that the maintainer team will usually triage:

```js
const { app, dialog, BrowserWindow, ipcMain } = require("electron");
const log = require("electron-log");
const greenworks = require("./greenworks");
const api = require("./api-server");
const gameWindow = require("./gameWindow");
const achievements = require("./achievements");
const utils = require("./utils");
const storage = require("./storage");
const debounce = require("lodash/debounce");
const Config = require("electron-config");
```

The maintainer team is pretty small and usually does not have the bandwidth to triage / debug third-party code. Would it be possible to write a standalone testcase based off https://github.com/electron/electron-quick-start that uses _only_ Node / Electron APIs without extra code?
