### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Comkiled** [electron/electron#32272]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro, version 21H1

### What arch are you using?

x64

### Expected Behavior

Hello everyone,

i got a weird problem, after building my application with electron-builder, thus I'm not even sure if this is the correct place for this issue.

I do output my application as a portable for Windows, asar packaging is activated, but I unpack all my workers with "asarUnpack" from electron-builder.

As far as I understand the build process, first output of the build process is a so called "win-unpacked" folder with an .exe file, resources folder and some other folders. When I start the .exe file in the "win-unpacked" folder, yet everything works as expected.

### Actual Behavior

The 2nd part of the build process will then give me a small portable .exe file without any folder accompanying.
When I start this .exe file, the same folder as the one in the first build step ("win-unpacked") will be created temporarily somewhere in AppData/Local/Temp/xxxx folder. But in this case, my application does not work anymore, but throws JS errors, stating that the "threads" module (a module I use for Workers - This module uses Node's worker_threads), which should be imported into the worker, could not be found. The threads module is located somewhere inside the asar-package node_modules folder as a dependency.

After the first build step this reference stays available, the worker locates the "threads" module inside the asar package and imports it successfully, thus everything works as expected. After outputting and then starting the portable .exe file, it seems as if this reference is broken, although the temporarily created folder inside "AppData/Local/Temp/xXxxXX" is exactly the same folder in size and amount of data as the one from the first build step.

Maybe anyone of you has a suggestion, what my problem might be.

Edit 1: I am not using any bundler for my backend code. So the problem is not associated with bundling.
Edit 2: 
- Node version: 16.13.1
- electron-builder version: 22.14.5
- threads.js version: 1.7.0

Edit 3:
In order to reproduce this error:
1. package.json:
```
{
  "name": "workertest",
  "version": "1.0.0",
  "description": "",
  "main": "build/main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "npm run buildElectron && electron .",
    "buildElectron": "tsc",
    "buildAndOutputPortable": "set NODE_ENV=production && npm run buildElectron && electron-builder"
  },
  "author": "",
  "license": "ISC",
  "build": {
    "appId": "de.worker.test",
    "directories": {
      "output": "workerTest"
    },
    "files": [
      "build/**/*",
      "package.json"
    ],
    "win": {
      "target": "portable",
      "artifactName": "workerTest.exe"
    },
    "asarUnpack": [
      "build/workers/testWorker.js"
    ]
  },
  "devDependencies": {
    "electron": "^16.0.5",
    "electron-builder": "^22.14.5"
  },
  "dependencies": {
    "threads": "^1.7.0",
    "tslib": "^2.3.1"
  }
}
```
2. tsconfig.json:
```
{
    "compilerOptions": {
      "target": "es6",
      "module": "commonjs",
      "moduleResolution": "node",
      "noEmitOnError": true,
      "lib": ["es2017", "dom"],
      "strict": true,
      "esModuleInterop": false,
      "allowSyntheticDefaultImports": true,
      "experimentalDecorators": true,
      "importHelpers": true,
      "outDir": "build/",
      "sourceMap": true,
      "inlineSources": true,
      "rootDir": "./"
    }
  }
```
3. main.ts:
```
import { app, BrowserWindow } from 'electron';
import { spawn, Worker } from 'threads';

let testWorker : any = undefined

function createWindow () {
    const win = new BrowserWindow({
      width: 800,
      height: 600
    })
  
    win.loadFile('index.html')
}
async function start() {
    if(!testWorker) {
        testWorker = await spawn(new Worker('workers/testWorker'))
    }
    app.whenReady().then(() => {
        createWindow()
      })
}
start()
```
4. testWorker.ts:
```
import { expose } from 'threads';
import { Observable, Subject } from 'threads/observable';


const bufferData: Array<any> = [];
const subject = new Subject();
let initialTimestamp: number;


const storeDataFunctions: any = {
    add(value: any) {
      if (bufferData.length === 0) {
        initialTimestamp = value.timestamp;
        value.timestamp = 0;
      } else {
        value.timestamp = value.timestamp - initialTimestamp;
      }
      subject.next(value);
      bufferData.push(value);
    },
    dataStream(): any {
      const observable = Observable.from(subject);
      return observable;
    },
    bufferData(): Array<any> {
      return bufferData;
    },
  };

expose(storeDataFunctions);

```
4. index.html:
```
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
  <meta name="Description" content="Put your description here.">
  <base href="./">

  <style>
    html,
    body {
      height: 100%;
      width: 100%;
      margin: 0;
      padding: 0;
      font-family: sans-serif;
      background-color: #ededed;
    }
    body {
      display: flex;
      flex-direction: column;
    }
  </style>
  <title>pxt-ui-app</title>
</head>

<body>
  Hello world
</body>
</html>
```
5. folder structure:
```
  project-name/
  |- workers
      |- testWorker.ts
  |- package.json
  |- index.html
  |- main.ts
  |- tsconfig.json
```

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
