### ISSUE TITLE
[Bug]: Using showMessageBoxSync before the ready event has finished causes problems since electron v14

### ISSUE THREAD

**Issue by stefansundin** [electron/electron#32281]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

macOS

### Operating System Version

11.6.1

### What arch are you using?

x64

### Last Known Working Electron version

13.6.3

### Expected Behavior

Using `dialog.showMessageBoxSync` should show a message box and block until the user has clicked the button.

Example:

```javascript
app.whenReady().then(() => {
  // This works in Electron v13.6.3 but causes problems on Electron v14.0.0 and later versions:
  dialog.showMessageBoxSync({
    message: 'Hello world',
  })

  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  })
  mainWindow.loadFile('index.html')
})
```

### Actual Behavior

The dialog shows for a split second but closes automatically. The `index.html` file isn't loaded properly, the browser window just remains white.

### Testcase Gist URL

https://gist.github.com/stefansundin/9009ed19202ef571ecdb10da4a3603ca

### Additional Information

The issue can be worked around with a `setTimeout`:

```javascript
app.whenReady().then(() => {
  setTimeout(() => {
    dialog.showMessageBoxSync({
      message: 'Hello world',
    })

    const mainWindow = new BrowserWindow({
      width: 800,
      height: 600,
    })
    mainWindow.loadFile('index.html')
  })
})
```

**Comment by codebytere** [comment]
@stefansundin looks like this stops happening as of v17.0.0-beta.3, still looking into why and if we can backport a fix

**Comment by stefansundin** [comment]
I can confirm that this appears to be fixed in v17. Feel free to close this issue.
