### ISSUE TITLE
[Bug]: ionic electron Error blob

### ISSUE THREAD

**Issue by salemdomain** [electron/electron#32297]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.9

### What operating system are you using?

macOS

### Operating System Version

10.13

### What arch are you using?

x64

### Expected Behavior

to allow uploading image from capacitor-electron://

### Actual Behavior

Refused to connect to 'blob:capacitor-electron://-/72d107ae-1e8b-49c0-82b5-4462b629eaa9' because it violates the following Content Security Policy directive: "default-src capacitor-electron://* 'unsafe-inline' devtools://* 'unsafe-eval' data:". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
zone.js:1523 Refused to connect to 'blob:capacitor-electron://-/72d107ae-1e8b-49c0-82b5-4462b629eaa9' because it violates the document's Content Security Policy.

### Additional Information

hi,

Does anyone know what the cause of this error?

Refused to connect to 'blob:capacitor-electron://-/72d107ae-1e8b-49c0-82b5-4462b629eaa9' because it violates the following Content Security Policy directive: "default-src capacitor-electron://* 'unsafe-inline' devtools://* 'unsafe-eval' data:". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
zone.js:1523 Refused to connect to 'blob:capacitor-electron://-/72d107ae-1e8b-49c0-82b5-4462b629eaa9' because it violates the document's Content Security Policy.

am trying to upload image and converting the blob to base64 for live reviewing the image, but i get the above error after selecting the image, i have tried to add <meta but no luck, can anyone help?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
