### ISSUE TITLE
[Bug]: process.versions.electron is undifined

### ISSUE THREAD

**Issue by daihere1993** [electron/electron#32291]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.2.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

`process.versions.electron` should have a string value just like the description of https://www.electronjs.org/docs/latest/api/process#processversionselectron-readonly.

### Actual Behavior

`process.versions.electron` is undefined.

![image](https://user-images.githubusercontent.com/17445018/147459266-3c135feb-a6da-4b0b-ba91-a88b35baa273.png)

### Testcase Gist URL

N/A

### Additional Information

As title, electron has been installed but `process.version.electron` is undefined.

More background: I'm using `electron-builder publish` command with "http_proxy", but find out `process.version.electron` is undefined which lead to can't run into following if condition.

https://github.com/electron-userland/electron-builder/blob/a94532164709a545c0f6551fdc336dbc5377bda8/packages/builder-util-runtime/src/httpExecutor.ts#L520

I'm not sure it is a bug or there were some operations I'm missing during electron installation. Please help to clarify it, thanks in advance.

**Comment by robertpatrick** [comment]
@daihere1993 Unfortunately, I don't think this is that simple.  In Electron 16.0.5 (where the `electron-publisher` is still failing from behind a proxy server), `process.versions` does include electron once the app is initialized.  

![Screen Shot 2021-12-27 at 10 45 01 AM](https://user-images.githubusercontent.com/31662131/147491364-c0445464-6bc5-4722-ae59-7b11148b83df.png)

`electron-publisher` runs at build time when the electron app itself is not running so my belief is that test is not valid for build-time execution.  My feeling is that this is a bug in `electron-builder` and should be handled there.

**Comment by daihere1993** [comment]
@robertpatrick  yeah, you are right. Seems the `process.versions.electron` only exists after the app initialized. I'll close this issue due to my misunderstanding.
