### ISSUE TITLE
[Bug]: Could not start audio source error on mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [electron/electron#32299]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

Ubuntu

### Operating System Version

Linux Jacob 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

Code given in docs should work :

```js
// In the renderer process.
const { desktopCapturer } = require('electron')

desktopCapturer.getSources({ types: ['window', 'screen'] }).then(async sources => {
  for (const source of sources) {
    if (source.name === 'Electron') {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({
          audio: {
            mandatory: {
              chromeMediaSource: "desktop",
              chromeMediaSourceId: id,
            },
          },
          video: {
            mandatory: {
              chromeMediaSource: "desktop",
              chromeMediaSourceId: id,
            },
          },
        })
        handleStream(stream)
      } catch (e) {
        handleError(e)
      }
      return
    }
  }
})

function handleStream (stream) {
  const video = document.querySelector('video')
  video.srcObject = stream
  video.onloadedmetadata = (e) => video.play()
}

function handleError (e) {
  console.log(e)
}
```

### Actual Behavior

It doesn't work instead gives error : 
```
> DOMException: Error could not start audio source
```

If we change audio to `false` then it gives different error :

```
> DOMException: Error starting screen capture
```

### Additional Information

The same is working on Windows seamlessly.

**Comment by TheRafaelFarias** [comment]
Some update on this? I tried with node 14.19.0 and I'm having the same problem

**Comment by TheRafaelFarias** [comment]
Some update on this? Its march and nobody said anything

**Comment by Shubham-Kumar-2000** [comment]
Yes I got a [solution](https://gist.github.com/guest271314/53e00c6765aa256362fb52c08e82d189).

Its basically a workaround.

First execute this on installation : 
```
pactl load-module module-remap-source master="$(pactl list | grep -A2 '^Source #' |  grep 'Name: .*\.monitor$' | awk '{print $NF}' | tail -n1)" source_name=virtmic source_properties=device.description=Virtual_Microphone
```

Then in your `renderer` process : 

```js
const system = await ipcRenderer.invoke("getOs");
      console.log({ system });
      if (!system) {
        throw new Error("System not supported");
      }

      const constraints = {
        audio: false,
        video: false,
      };

      if (system === "linux") {
        let devices = await navigator.mediaDevices.enumerateDevices();
        // console.log({ devices });

        devices = devices.filter(
          (device) => device.label === "harmonize_desktop"
        );
        if (devices.length === 0) {
          throw new Error("Please reinstall the application");
        }

        const device = devices[0];
        constraints.audio = {
          deviceId: {
            exact: device.deviceId,
          },
        };
      }

      if (system === "windows") {
        constraints.audio = {
          mandatory: {
            chromeMediaSource: "desktop",
            chromeMediaSourceId: id,
          },
        };
        constraints.video = {
          mandatory: {
            chromeMediaSource: "desktop",
            chromeMediaSourceId: id,
          },
        };
      }

      newStream = await navigator.mediaDevices.getUserMedia(constraints);
```

Finally in the `main` process : 

```js
ipcMain.handle("getOs", () => {
  const platforms = {
    win32: "windows",
    linux: "linux",
    darwin: "macos",
  };
  return platforms[process.platform];
});

```


Well I haven't completed the `macOS` implemention yet thus have excluded that.

**Comment by TheRafaelFarias** [comment]
Didn't worked for me. ``await navigator.mediaDevices.enumerateDevices();`` only returns the camera and the audio and not the applications

**Comment by kei49** [comment]
I faced the same errors on MacOS Big Sur Version 11.6.8 with electron 20.0.3. Any solutions?

**Comment by kei49** [comment]
I found the caveats about this restriction on the Electron official docs

> navigator.mediaDevices.getUserMedia does not work on macOS for audio capture due to a fundamental limitation whereby apps that want to access the system's audio require a [signed kernel extension](https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/KernelExtensions/KernelExtensions.html). Chromium, and by extension Electron, does not provide this.
It is possible to circumvent this limitation by capturing system audio with another macOS app like Soundflower and passing it through a virtual audio input device. This virtual device can then be queried with navigator.mediaDevices.getUserMedia.

https://www.electronjs.org/docs/latest/api/desktop-capturer#caveats

**Comment by PDKSophia** [comment]
I have the same problem，does anyone have a solution?

#### Electron Version
21.3.0

#### My Code
```js
if (this.systemAudioStream) {
  this.systemAudioStream.getTracks()?.forEach((track) => {
    track.stop();
  });
}
const systemAudioStream = await navigator.mediaDevices.getUserMedia({
  audio: {
    mandatory: {
      chromeMediaSource: 'desktop',
    },
  },
  video: {
    mandatory: {
     chromeMediaSource: 'desktop',
    },
  },
});
  
systemAudioStream.getVideoTracks()?.forEach((track) => systemAudioStream.removeTrack(track)); 
this.systemAudioStream = systemAudioStream;

log.info('init system audio stream success');
```

It doesn't work instead gives error :

> DOMException: Error could not start audio source

**Comment by wreper12** [comment]
I am also having the same issue, it works perfectly fine on windows but on Ubuntu it does not work, the regular microphone can be assessed but anything from desktopCapturer.getSources does not work.
**Electron Version:** 
22.0.0

**Comment by Lalg28** [comment]
I'm already having the same error with Electron 22.0.0 and MacOS Ventura 13.2 🥲

**Comment by vvillaluna** [comment]
Having same error here but it's working fine on other machines. It might have to do something on the hardware or audio drivers installed on a machine.

**Comment by akshiii** [comment]
Ive spend 2 days on this, and still no solution to this, It always throws the same error, could not start audio. But it does not even start video 
`const stream = await navigator.mediaDevices
      .getUserMedia({
        audio: true,
        video: {
          width: {
            max: 1080,
          },
        },
      })
      .then(
        (st) => {
          videoRef.src = st;
          setMyStream(st);
        },
        (err) => {
          console.log(err);
        }
      );`
