### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by peterleezzzZflps** [electron/electron#32298]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.5

### What operating system are you using?

macOS

### Operating System Version

big sur 11.6

### What arch are you using?

x64

### Expected Behavior

Chinese display is abnormal

### Actual Behavior

I use xterm.js to write the webshell front-end style, node as the back-end service, it is normal when I run npm run electron:serve, but when I npm run electron:build generates .dmg and start the program, the webshell displays Chinese exceptions. How can I solve it?

log:
> ls
???.py ???.js ???.jl

**Comment by peterleezzzZflps** [comment]
The node service is started using electron's main.js

**Comment by zidoa2423** [comment]
it just gets stuck
in the lodaing screen

**Comment by peterleezzzZflps** [comment]
At first, I can think of it as a card, but after I tested it many times, the effect is still the same. But if I use the terminal to start the program, the Chinese can be loaded normally.

**Comment by peterleezzzZflps** [comment]
> 它只是卡 在加载屏幕中

At first, I can think of it as a card, but after I tested it many times, the effect is still the same. But if I use the terminal to start the program, the Chinese can be loaded normally.

**Comment by peterleezzzZflps** [comment]
> 它只是卡 在加载屏幕中

At first I can think it is loading, but after I test it many times, the effect is still the same. But if I start the program using the terminal, the Chinese can be loaded normally.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
