### ISSUE TITLE
[Bug]: ready-to-show  multiple firing

### ISSUE THREAD

**Issue by tsoil** [electron/electron#32294]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.6

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

Only trigger once

### Actual Behavior

 multiple firing

### Additional Information

main.js:

``` ipcMain.on("openSchedule", (evet, link) => {
    if (schedule) {
      schedule.webContents.send("getURL", link);
      schedule.center();
      schedule.moveTop();
      schedule.focus();
      return;
    }
    .....
    schedule = new BrowserWindow({
      title: "date",
      width: 850,
      height: 600,
      minHeight: 600,
      minWidth: 850,
      center: true,
      frame: false,
      show: false,
      transparent: false, // 透明
      resizable: true,
      webPreferences: {
        webviewTag:true,
        webSecurity: false,
        contextIsolation: false,
        nodeIntegration: true,
        enableRemoteModule: true,
      },
    });
    schedule.center();
    schedule.moveTop();
    schedule.on("closed", () => {
      schedule = null;
    });
    schedule.on("ready-to-show", () => {
      console.log("send-ok")
      if (schedule) {
        schedule.webContents.send("getURL", link);
        schedule.show();
      }
    });
  });
```

render.js:
 
```...
   <webview id="webview" :src="link"></webview>
 ...
    electron.ipcRenderer.on("getURL", (event, url) => {
            this.link = url;
          });
 ```

**Comment by tsoil** [comment]
change link

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `16-x-y`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
