### ISSUE TITLE
Parent window support in BrowserWindow

### ISSUE THREAD

**Issue by triplekdev** [electron/electron#323]
Please add a support for `browser-window` to have first element as a parent for modal, same with `dialog.showMessageBox(parent, { .. })`

**Comment by EhsaanF** [comment]
Is this gonna add to Electron soon?

**Comment by KevinMartin** [comment]
+1

**Comment by KevinMartin** [comment]
Would be nice to see something like the following screenshots on Mac/Windows.

Mac:
<img width="1440" alt="screen shot 2015-10-09 at 10 02 11 am" src="https://cloud.githubusercontent.com/assets/510957/10435849/9851c472-70f0-11e5-9d1b-63381dd7ef76.png">
<img width="1440" alt="screen shot 2015-10-09 at 10 02 16 am" src="https://cloud.githubusercontent.com/assets/510957/10435848/984297ae-70f0-11e5-931d-6d8010e79907.png">

Windows (via @EhsaanF):
![image](https://cloud.githubusercontent.com/assets/510957/10435839/8a0c1de0-70f0-11e5-8953-c80b472f460d.png)

**Comment by daguej** [comment]
+1, this would be very useful to give apps a more native feel.

**Comment by erickmonteiro** [comment]
+1

**Comment by tufik2** [comment]
+1000. I want a dialog when i can put personal HTML is good for  configuration panels.

**Comment by shrimpwagon** [comment]
+1

**Comment by ricardomatias** [comment]
+1

**Comment by logidelic** [comment]
I think this is important for a few reasons, but here's one: In a typical web application, you can expect the browser window to be "large" simply because it needs to be big enough to display most/all web pages. An application's window size, on the other hand, might be very small if it makes sense for the given application. However, in this case, a web-style ("lightbox") dialog cannot be used since the window is too small to display it.

**Comment by bpasero** [comment]
@zcbenz I assume the child window does not share any of the VM context of the parent window? Does it  get a fresh VM context as if I was opening a full new browser window?

**Comment by zcbenz** [comment]
@bpasero The child window is an independent BrowserWindow instance just like normal top-level ones.

**Comment by triplekdev** [comment]
@zcbenz Atlast! thanks!

**Comment by sourceskyboxer** [comment]
I like modal-able window - Oh my god - I sleep too late :+1: 
Please add feature more!
I am very excited to create own application by electron.

Electron is very better and stable. I am very proud that I have tested electron demo application how do I understand like features of electron example showMessageBox and more more.

Wow Electron is very richer than NW.js NW.js has no showMessageBox Poor NW.js!!!

Now I am starting with development with electron and full-support for HTML5 and pepper-flash via allowScriptAccess via ExternalInterface for Chrome, Electron and NW.js

Please don't forget to add in embed / object of pepper flash plugin
"parem" "allowScriptAccess" than you can call from externalinterface to javascript example show browserWindow.

Thanks for adding features......
