### ISSUE TITLE
[Feature Request]: Allow not to save the user data

### ISSUE THREAD

**Issue by Naozumi520** [electron/electron#32300]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I'm creating a project using "puppeteer-in-electron", with the module I can use puppeteer in electron just like chrome browser.
However, unlike the puppeteer with chromium, electron will storage the user data as default. I have asked in the discord server and it seem there's no way to disable it as default. the only solution is use `clearStorageData()` every time.

### Proposed Solution

Add an options `SaveUserData` to `BrowserWindow` with bool will be great.

### Alternatives Considered

Or empty path like `app.setPath ('userData', "")` also looks good.

**Comment by nornagon** [comment]
You probably want an [in-memory session](https://www.electronjs.org/docs/latest/api/session#sessionfrompartitionpartition-options).
