### ISSUE TITLE
[Bug]: Unable to create very small frameless windows; minimum size enforced

### ISSUE THREAD

**Issue by ivanggq** [electron/electron#32302]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H1

### What arch are you using?

x64

### Expected Behavior

I should be able to create very small frameless windows, e.g. 1x1 pixels, or even 0x0 pixel windows. There shouldn't be any minimum size enforced for such windows.

### Actual Behavior

I am not able to create very small frameless windows (e.g. 1x1 pixels). There is a minimum size enforced for such windows, which seems related to the standard titlebar / frame thickness.

The minimum window size is different depending on the monitor DPI setting:

- on a monitor with 100% DPI, the standard titlebar height is 39 pixels and the minimum window height enforced by Electron is 39 pixels
- on a monitor with 150% DPI, the standard titlebar height is 56 pixels and the minimum window height enforced by Electron is 56 pixels
- on a monitor with 300% DPI, the standard titlebar height is 103 pixels and the minimum window height enforced by Electron is 103 pixels
- etc.

A side effect of this bug is that if the window is created on a monitor with DPI 300% for example, if is is moved to a monitor with 100% DPI, the window gets resized to the minimum height for the 300% DPI monitor, which is 103 pixels height, instead of 39 pixels. This seems like an incorrect DPI scaling behavior by itself, but seems related to this minimum size issue.

### Testcase Gist URL

https://gist.github.com/55c3068a02db0252260ce426ca41ffaf

### Additional Information

<img width="1811" alt="ScreenshotWindows" src="https://user-images.githubusercontent.com/48165365/147789488-830cc02c-65fe-4e61-addb-554517109b67.png">

Issue is also reported as https://github.com/electron/electron/issues/23200, but this ticket got closed. Also, I believe my ticket is providing more information, this is why I opened a new one.

It seems like using the frame thickness as the minimum size makes sense for framed windows, but it doesn't for frameless windows. It seems like the minimum size logic is assuming framed windows only.

**Comment by Dooobi** [comment]
I have noticed the same issue a few days ago.
Hopefully there will be a fix for it soon.
In the meantime i also use `window.setShape(...)` as a workaround:
```javascript
app.on('browser-window-blur', (event, win) => {
    console.log('browser-window-blur event');
    win.setContentSize(1, 1);
    win.setSize(1, 1);
    win.setMinimumSize(1, 1);
    win.setShape([{
      x: 0,
      y: 0,
      width: 1,
      height: 1
    }]);
  });
```
Calling `setSize` and `setShape` should do the trick.
Even though the window is still bigger than 1px because of this issue, it really looks and feels like it's only 1px because of the `setShape` call.
It makes it so that only 1px of the window is visible and mouse events outside of this pixel will fall through to the window behind.

**Comment by andy-asana** [comment]
> I have noticed the same issue a few days ago. Hopefully there will be a fix for it soon. In the meantime i also use `window.setShape(...)` as a workaround:
> 
> ```js
> app.on('browser-window-blur', (event, win) => {
>     console.log('browser-window-blur event');
>     win.setContentSize(1, 1);
>     win.setSize(1, 1);
>     win.setMinimumSize(1, 1);
>     win.setShape([{
>       x: 0,
>       y: 0,
>       width: 1,
>       height: 1
>     }]);
>   });
> ```
> 
> Calling `setSize` and `setShape` should do the trick. Even though the window is still bigger than 1px because of this issue, it really looks and feels like it's only 1px because of the `setShape` call. It makes it so that only 1px of the window is visible and mouse events outside of this pixel will fall through to the window behind.

When I try this, my window loses its shadow. This means that if there is another window behind my window that is the same color, they will look 'merged together' and it is impossible to tell where one starts and the other begins.

I tried manually setting `hasShadow: true` to the window constructor, but that doesn't seem to make a difference.

Any thoughts?

Thanks!
