### ISSUE TITLE
[Bug]: Electron crashed when playing videos or music (Windows 7 Professional with Service Pack 1 x64)

### ISSUE THREAD

**Issue by wifi-left** [electron/electron#32306]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 7 Professional with Service Pack 1 (x64)

### What arch are you using?

x64

### Last Known Working Electron version

<=13.5.2

### Expected Behavior

Play the music or videos.

### Actual Behavior

Electron programs crashed when playing videos or music on Windows 7.
The program did not report any errors.
Only appears: "This program has stopped working and is looking for a solution".
And then the programs crashed.
It won't happen on Windows 10.

**Comment by codebytere** [comment]
Fixed by https://github.com/electron/electron/pull/32046
