### ISSUE TITLE
[Bug]: Custom menu style and vscode editor also have this problem

### ISSUE THREAD

**Issue by ksBking** [electron/electron#32310]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^16.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 IoT 企业版 LTSC

### What arch are you using?

x64

### Expected Behavior

When I click the minimize button of the custom menu, I use IPC to send a message to minimize the window. When I click the program of the taskbar to display the window again, when the mouse does not move into the window, the style of the minimize button I clicked last time is not the [hover] of CSS, but the default style.

### Actual Behavior

When I click the minimize button in the custom menu, I use IPC to send a message to minimize the window. When I click the program in the taskbar again to display the window, when the mouse does not move to the window, the style of the minimize button I clicked last time is still [hover] of CSS. When the mouse moves to the window, the style of the minimize button will return to its original appearance.

### Additional Information
![Snipaste_2022-01-02_20-50-40](https://user-images.githubusercontent.com/54195058/147876299-ccf9dcf3-9def-4cca-afe2-74ec9d0eb981.png)

![Snipaste_2022-01-02_20-38-46](https://user-images.githubusercontent.com/54195058/147876063-2b422a68-bb73-49a6-9d20-b1558c0b194e.png)
![Snipaste_2022-01-02_20-38-58](https://user-images.githubusercontent.com/54195058/147876081-dc8e39a5-fe46-46a0-9afc-7ad62f6aac2d.png)
![Snipaste_2022-01-02_20-40-47](https://user-images.githubusercontent.com/54195058/147876085-28e16487-5608-47e8-952f-05c0499e963c.png)
![Snipaste_2022-01-02_20-41-13](https://user-images.githubusercontent.com/54195058/147876090-aec63eb5-6341-417f-aaef-f79f0a21e991.png)
![Snipaste_2022-01-02_20-41-26](https://user-images.githubusercontent.com/54195058/147876095-10aea08c-71c7-4060-8dde-07bd277f4b51.png)
![Snipaste_2022-01-02_20-41-56](https://user-images.githubusercontent.com/54195058/147876102-b651c5a1-73ae-4af5-a53b-263358e05a3f.png)

**Comment by Clark312** [comment]
I have issues of trust hacking and I'm trying to get my coin back

**Comment by Clark312** [comment]
@Clark312

**Comment by Clark312** [comment]
![Uploading 3F093D16-8B65-4FD5-BF31-8DE91AC1C9F2.png…]()

**Comment by Clark312** [comment]
![44F36BFD-6226-4EF6-9102-630573859009](https://user-images.githubusercontent.com/95451648/147882108-d16790ce-cae9-493c-aaed-73130d521cdc.png)
![04849E02-4FE7-4679-A9D0-AF13DBC8757D](https://user-images.githubusercontent.com/95451648/147882109-fbc618b1-7bb4-45c2-957e-2217d0d95a2b.png)
![94A1FC65-4C23-4839-9592-83295CB2ADE0](https://user-images.githubusercontent.com/95451648/147882110-aebae568-0f16-4e8d-bba3-642dc084fb3e.png)
![9DA3C26B-205C-49B1-BDE1-1DA7C6B47C4E](https://user-images.githubusercontent.com/95451648/147882113-643993cd-c3ca-4e0c-8cc4-7aa0e80c1a8c.png)
![497FD27B-910A-4BDF-805C-81CCB962BB6D](https://user-images.githubusercontent.com/95451648/147882115-01011f94-2687-4cf0-93f7-df566b88ab3a.png)
![007F2AA9-B2EF-4571-B778-B73E80DECC20](https://user-images.githubusercontent.com/95451648/147882116-321b9aab-f811-4804-b027-c8dba1c7a7a2.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
