### ISSUE TITLE
[Bug]: Electron fails to build in some Windows configurations due to misnamed .patch file

### ISSUE THREAD

**Issue by vulture** [electron/electron#32323]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19042.1415

### What arch are you using?

x64

### Last Known Working Electron version

13.0.0

### Expected Behavior

Electron builds from scratch

### Actual Behavior

Electron doesn't build. This error shows up instead:
```
  ...
  Applying: Convert Electron ProcessSingleton changes to patch
  Applying: fix: expose DecrementCapturerCount in web_contents_impl
  Applying: add ui::ScopedCliboardWriter::WriteUnsafeRawData
  Applying: feat: Add data parameter to ProcessSingleton
  Applying: fix: mas gate private enterprise APIs
  Patch failed at 0111 fix: mas gate private enterprise APIs
```
Attempting to apply this patch manually with verbose flags shows the following:
```
c:\...\electron\src> git apply electron\patches\chromium\mas_gate_private_enterprise_APIs --verbose
Checking patch base/enterprise_util_mac.mm...
error: while searching for:
DeviceUserDomainJoinState AreDeviceAndUserJoinedToDomain() {?
  static DeviceUserDomainJoinState state = [] {?
    DeviceUserDomainJoinState state{false, false};?
?
    @autoreleasepool {?
      ODSession* session = [ODSession defaultSession];?

error: patch failed: base/enterprise_util_mac.mm:168
error: base/enterprise_util_mac.mm: patch does not apply
```

### Additional Information

The offending PR seems to be this: https://github.com/electron/electron/pull/31482

The extra `?` on the end of the verbose failure log is indicative of extra `\r` when the tools expect only `\n` and will error if git is in a configuration to check out files in CRLF mode. This was apparently a problem previously identified and fixed here: https://github.com/electron/electron/pull/14789
```
# `git apply` and friends don't understand CRLF, even on windows. Force those
# files to be checked out with LF endings even if core.autocrlf is true.
*.patch text eol=lf
```
However, this fix only works if patch files are named `*.patch`. In this case, the patch file was named without `.patch`, so the fix doesn't work, and it causes builds to fail. The fix is likely to rename `patches/chromium/mas_gate_private_enterprise_APIs` to `patches/chromium/mas_gate_private_enterprise_APIs.patch`.

**Comment by vulture** [comment]
Created a PR here https://github.com/electron/electron/pull/32324 if you want to use it; otherwise feel free to close the PR!

**Comment by VerteDinde** [comment]
Ah thanks, @vulture, your PR looks great! Appreciate you catching this issue as well, sorry for the trouble 😄
