### ISSUE TITLE
[Bug]: The entire app won't load

### ISSUE THREAD

**Issue by PotetoeLord** [electron/electron#32320]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

latest

### What operating system are you using?

Windows

### Operating System Version

windows 10.0.19042

### What arch are you using?

x64

### Expected Behavior

for the application to load up

### Actual Behavior

did not just on a screen of greyish black

### Additional Information

![error bruh](https://user-images.githubusercontent.com/97060554/147975742-847d33f0-b2ae-4caa-b184-31aa5b387067.PNG)

**Comment by VerteDinde** [comment]
Hey @PotetoeLord! You seem to be having an issue with Discord specifically - I'd report your issue to Discord directly, rather than here, since they will have more information about their specific version of Electron and client 🙇‍♀️
