### ISSUE TITLE
[Bug]: How can Count the per Mouse Click and Keyboard Press in Electron and nextjs but not focused only apps globally get all keyboard and mouse click event 

### ISSUE THREAD

**Issue by dipaksavaliya04** [electron/electron#32336]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

20.04.3

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

15.0.0

### Expected Behavior

 Count the per Mouse Click and Keyboard Press in Electron and nextjs but not focused only apps globally count keyboard and mouse click event  

### Actual Behavior

 Count the per Mouse Click and Keyboard Press in Electron and nextjs but not focused only apps globally count keyboard and mouse click event  

### Additional Information

 I have tried also iohook package but not used inside nextjs rendered and also try window.addEventListener event and browserwindow.getAllwindow() on electronjs .
 
 Count the per Mouse Click and Keyboard Press in Electron and nextjs but not focused only apps globally count keyboard and mouse click event  
 
 
 Please let me know about this solution

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
