### ISSUE TITLE
[Bug]:  electron run execSync/spawnSync/elecFileSync without “windowsHide: true” option has different Behavior before/after pack the sofeware

### ISSUE THREAD

**Issue by terry2010** [electron/electron#32334]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

Windows

### Operating System Version

windows 10 2020h1 / windows 7 latest

### What arch are you using?

ia32

### Last Known Working Electron version

16.0.4

### Expected Behavior

run execSync/spawnSync/elecFileSync always quitly

I create a demo in : https://github.com/terry2010/electron-bug-has-cmd-window

and it works as Expected  when I use electron version 15.3.0 

### Actual Behavior

after pack the soft, electron run execSync/spawnSync/elecFileSync always show a black cmd windows.
version 17.0.0 alpha5 has this problem too

### Testcase Gist URL

git@github.com:terry2010/electron-bug-has-cmd-window.git

### Additional Information

I create a demo in : https://github.com/terry2010/electron-bug-has-cmd-window

**Comment by Prinzhorn** [comment]
Not sure why it worked before, but don't you need `windowsHide: true` option?

> Hide the subprocess console window that would normally be created on Windows systems. Default: false.

https://nodejs.org/api/child_process.html

**Comment by terry2010** [comment]
> Not sure why it worked before, but don't you need `windowsHide: true` option?
> 
> > Hide the subprocess console window that would normally be created on Windows systems. Default: false.
> 
> https://nodejs.org/api/child_process.html

thank you very much , I got my problem fixed .

maybe I should change title to :  "electron run execSync/spawnSync/elecFileSync  without  `windowsHide: true` option has different Behavior  before/after pack the sofeware" ?
