### ISSUE TITLE
Unable to request the audio stream of the specified application/window

### ISSUE THREAD

**Issue by pavel-vorobyev** [electron/electron#32335]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21h

### What arch are you using?

x64

### Expected Behavior

I'm requesting screen share sources like so:
`desktopCapturer.getSources({ types: ['screen', 'window'], fetchWindowIcons: true })`

then I'm requesting source's stream like so:
```
const constraints = {
      audio: {
        mandatory: {
          chromeMediaSource: 'desktop',
          chromeMediaSourceId: sourceId
        }
      },
      video: {
        mandatory: {
          chromeMediaSource: 'desktop',
          chromeMediaSourceId: sourceId,
          minWidth: 1280,
          maxWidth: 1280,
          minHeight: 720,
          maxHeight: 720
        }
      }
    } as MediaStreamConstraints

    navigator.mediaDevices.getUserMedia(constraints).then(stream => {
      onSuccess(stream)
    }).catch(e => {
      console.log(e)
      onError?.('unknown', e)
    })
```

It should provide the audio stream of the selected application/window, not of the entire system.

### Actual Behavior

It doens't provide the audio stream of the selected application/window. It provides the audio stream of the entire system - sounds from all applications.

**Comment by ma3ve** [comment]
any solution?
