### ISSUE TITLE
[Feature Request]: Add a new style to titleBarStyle

### ISSUE THREAD

**Issue by fangwei18** [electron/electron#32351]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, I'm using `titleBarStyle: 'hiddenInset'` option. I custom the style of the header, but the controls on mac only appear where the mouse hovers over that area, it would be great if the controls can also appear when not hovered.

The controls disappear when not hovered by the mouse:
![image](https://user-images.githubusercontent.com/45305818/148261610-133903b6-c5b1-40f3-8efd-92c3d9066db8.png)

### Proposed Solution

Expected

![image](https://user-images.githubusercontent.com/45305818/148261922-b31aebee-9204-40aa-8e90-8818abecdf37.png)

### Alternatives Considered

![image](https://user-images.githubusercontent.com/45305818/148261938-b0f97586-b88e-43e5-b9aa-994dfcaf5dfb.png)

**Comment by miniak** [comment]
Cannot reproduce

**Comment by haanamomo** [comment]
If you set `titleBarStyle` to `hiddenInset` and add a white header , then these three buttons will disappear and only show when the mouse hover on it.
