### ISSUE TITLE
[Bug]: BrowserWindow.showInactive Will Restore Maximized Window

### ISSUE THREAD

**Issue by dsanders11** [electron/electron#32373]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0-alpha.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

`BrowserWindow.showInactive` should not restore a maximized window

### Actual Behavior

`BrowserWindow.showInactive` does restore a maximized window

### Testcase Gist URL

https://gist.github.com/9f2c69b089f2155859bb0b439aefb668

### Additional Information

The provided gist is a test so it should be runnable by `bugbot`. I've confirmed the behavior on Windows, macOS seems unaffected, I haven't tested Linux.

~@ckerr, could you test Linux? It might be similar to #32350 where it affects both Windows and Linux but not macOS.~

Root cause may be upstream in Chromium, `ShowInactive` in Electron just passes through to `ShowInactive` on the widget, there's really no logic present.

**Comment by dsanders11** [comment]
I've confirmed this is a Windows-only issue, and opened a CL on Chromium to fix it: https://chromium-review.googlesource.com/c/chromium/src/+/3371573

I'll see what they say about the CL, and if it is approved I'll make a PR on Electron with a patch.

**Comment by AbhiramL** [comment]
Hi, Im a beginner in github and was wondering if this is beginner friendly? I have experience in c++ but if this isnt beginner friendly can you direct me to issues in this project that I can help out with? Thanks a lot.

**Comment by dsanders11** [comment]
Hi @AbhiramL! This issue isn't very beginner friendly, it involves upstream changes to Chromium, and I'm already working it. Electron has a "beginner friendly" label for issues, you can try looking at the list of issues with that label here: https://github.com/electron/electron/issues?q=is%3Aopen+is%3Aissue+label%3A%22beginner+friendly%22
