### ISSUE TITLE
[Bug]: On macOS, opening child window causes fullscreen parent window to become black and unresponsive

### ISSUE THREAD

**Issue by EvanHahn-Signal** [electron/electron#32374]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.1

### What arch are you using?

x64

### Expected Behavior

Users can return to a fullscreen parent window without the app going black and becoming unresponsive.

### Actual Behavior

https://user-images.githubusercontent.com/69474926/148465330-f2c8403c-65ba-4e74-8999-d7c7d844df60.mp4

Set up an app that spawns a window, then spawns a child subwindow. See [this sample app](https://gist.github.com/EvanHahn-Signal/69b6e39ab20ea9905383cf4829329ed7).

Then, as a macOS user:

1. Start the app.
2. Make the main window fullscreen.
3. Open the sub-window. It should also open fullscreen.
4. Switch back to the main window. (You can do this by closing the sub-window, or simply switching macOS Spaces.)

 

### Testcase Gist URL

https://gist.github.com/EvanHahn-Signal/69b6e39ab20ea9905383cf4829329ed7

### Additional Information

- I've reproduced this on macOS Monterey 12.1, but it was happening on prior macOS versions.
- I don't know, but I don't believe this to be a recent regression or change with macOS upgrades.
- I haven't tested this on other operating systems.

**Comment by BlackHole1** [comment]
I have just tried it on my computer and there is indeed a problem.
I would like to add a few additional points of information in response to this current issue

> I will add a few additional points of information

#### Versions Info

This problem exists for all versions from `electron@13.0.0-beta.2` to `18.0.0-nightly.20220106`

#### It is normal to open sub-windows first

1. Start the app
2. Click `Open sub-window`
3. Make the _main_ window fullscreen.
4. Make the _sub_ window fullscreen.

The above steps will not cause problems

#### Remove parent or disable fullscreen in sub-winodw, no problem

```js
subWindow = new BrowserWindow({
  width: 400,
  height: 300,
  webPreferences: {
    preload: path.join(__dirname, "preload.js"),
  },
  // parent: mainWindow,
});
```

```js
subWindow = new BrowserWindow({
  width: 400,
  height: 300,
  fullscreen: false, // or fullscreenable: false,
  webPreferences: {
    preload: path.join(__dirname, "preload.js"),
  },
  parent: mainWindow,
});
```

The above code will not cause problems

#### Description of the situation after the black screen

1. <kbd>Command</kbd> + <kbd>Q</kbd> not working
2. Black screen persists after execution of `location.reload()`
3. Not activated: `window.addEventListener("click", console.log)` will never trigger a callback

**Comment by BlackHole1** [comment]
Nothing to do with time competition, as I tried the following code and still had problems

```js
subWindow = new BrowserWindow({
  width: 400,
  height: 300,
  show: false,
  fullscreenable: false,
  webPreferences: {
    preload: path.join(__dirname, "preload.js"),
  },
  parent: mainWindow,
});
subWindow.loadFile("sub-window.html");

subWindow.on("ready-to-show", () => {
    subWindow.setFullScreenable(true);
    setTimeout(() => {
      subWindow.show();
    }, 5000);
})
```

**Comment by EvanHahn-Signal** [comment]
I can no longer reproduce this so I'm going to close. Thanks to whoever fixed it!

**Comment by trevor-signal** [comment]
This bug is now again present and reproducible via the provided gist on Electron v25.4 and v26.

**Comment by weibinzhu** [comment]
can reproduce in v19.1.9

**Comment by yairz-q** [comment]
can reproduce with electron 30.4.0
