### ISSUE TITLE
[Bug]: will-navigate event doesn't fire for same-page navigations

### ISSUE THREAD

**Issue by rzhao271** [electron/electron#32371]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19043.1415

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

When clicking on a link of type `<a href="#">link text here</a>`, the `will-navigate` event is emitted.

### Actual Behavior

When clicking on a link of type `<a href="#">link text here</a>`, the `will-navigate` event is **not** emitted. Instead, `did-navigate-in-page` is emitted, but the navigation has already completed by then.

### Testcase Gist URL

https://gist.github.com/rzhao271/db5a33e5b332bc5f292f049be6c404a1

### Additional Information

A use case of detecting when `will-navigate` is emitted for same-page navigations is to be able to prevent those navigations from happening, especially when there is other code to execute instead.

Currently, in VS Code, we mitigate links with same-page navigations within the codebase by removing the `href` attribute entirely 
and using click handlers instead, such as for https://github.com/microsoft/vscode/commit/69d1ad8c65c9fa412fdf9f29abaab1f950be447f and https://github.com/microsoft/vscode/commit/d477eb1ee30fda8b17e2290e2b79207f1d366047.

To fix this bug most likely requires a Chromium patch. I verified in the gist that the `will-redirect` event is not emitted for `#` links.
I also think that one reason that `will-navigate` is not called is because `WillStartRequest` is not called for same-page navigations: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/navigation_request.cc;l=2012;drc=73a504d9c4206b06598fc62da68407a4a6b703b4;bpv=1;bpt=1. 
We might also have to comment out the following loop: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/navigation_request.cc;l=5552-5559;drc=73a504d9c4206b06598fc62da68407a4a6b703b4, 
especially if that loop causes an early return on the following function, which would then result in the navigation throttles not picking up the event: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/navigation_request.cc;l=5443-5448;drc=73a504d9c4206b06598fc62da68407a4a6b703b4;bpv=1;bpt=1.

Though there is a mitigation for this issue above, it implies that we must search for all potential `#` links. With VS Code, since there are third-party extensions, we're currently unable to programmatically check for when `#` links are being called from those extensions. If `will-navigate` was emitted for same-page navigations, then we can run `preventDefault` on all links of that form in a single event handler in the main repository, in a similar way as https://www.electronjs.org/docs/latest/tutorial/security#13-disable-or-limit-navigation.

**Comment by pushkin-** [comment]
This appears to be by design as per the [docs](https://www.electronjs.org/docs/latest/api/web-contents#event-will-navigate):
>It is also not emitted for in-page navigations

**Comment by pushkin-** [comment]
repros in latest stable (21)

**Comment by MarshallOfSound** [comment]
Per @pushkin- above, this is by design `will-navigate` only occurs for full navigation cycles, not in-page navigations
