### ISSUE TITLE
[Bug]: The first call of `loadFile`/`loadURL` takes 2 seconds

### ISSUE THREAD

**Issue by AlttiRi** [electron/electron#32375]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

Windows

### Operating System Version

21H1

### What arch are you using?

x64

### Expected Behavior

The first call of `BrowserWindow.loadFile`/`BrowserWindow.loadURL`  takes up 100 ms ideally, or at least up to 300 ms.

### Actual Behavior

The first call of `BrowserWindow.loadFile`/`BrowserWindow.loadURL`  takes 1.8-2.3 seconds.

See the more detailed results: https://github.com/electron/electron/issues/32375#issuecomment-1010608115

### Testcase Gist URL

https://gist.github.com/AlttiRi/d51f33beef067b54689fecf4fe5d46fa

Use `node exec-npm-start.js`, or `node exec-electron-dot.js` for profiling.

UPD:
The new version of the test gist: https://gist.github.com/AlttiRi/ddff57964472f3c4ccc3eb0dacf2073b

### Additional Information

I use the hello world example project: https://github.com/electron/electron-quick-start#to-use

The first HTML rendering (`loadFile`), or site opening (`loadURL`) is too slow — it takes ~2 seconds.

```js
    console.time("load");
    await mainWindow.loadFile("index.html");
 // await mainWindow.loadURL("https://google.com"); // or
    console.timeEnd("load");
```

It works the same way on my main OS, as well as on a clear virtual machine.

**Comment by AlttiRi** [comment]
When I tested Electron 2 years ago (an example application) the first appearance of the window took ~200 ms, then plus 200-300 ms for content HTML rendering. 
400-500 ms total is to see the HTML.

**Comment by AlttiRi** [comment]
There is a very weird thing: with `npm start` `loadFile` works by 500 ms longer that when I use `electron .`

WTF?
It should be absolutely the same thing, since:
```json
"scripts": {
  "start": "electron ."
}
```
However with  `npm start` `loadFile` takes ~2 s, with `electron .` —  ~1.5 s.

**Comment by danielehrhardt** [comment]
Same here.

**Comment by AlttiRi** [comment]
In comparison:

 - Neutralino.js takes 700 ms from the program start to show the rendered HTML.

- NW.js takes 450-500 ms.

**Comment by ckerr** [comment]
Possibly a Windows-specific issue?

Tested on Ubuntu 21.10 in electron-fiddle using https://gist.github.com/dd17cf4029111970cf964736d4ba65f6, which is the standard quick-start fiddle + the `mainWindow.loadFile()` call has been bookended with `console.time()` + `console.timeEnd()`.

Result for me in the latest 16-x-y is: 

> Electron v16.0.6 started.
load: 3.464ms

And in the latest 15-x-y:

> Electron v15.3.4 started.
load: 3.39ms

**Comment by Prinzhorn** [comment]
@ckerr your Fiddle is missing an `await`, so you're not actually timing the time it takes for it to load just the time the `loadFile` call takes

**Comment by AlttiRi** [comment]
Make `createWindow` function `async` and use `await` before `mainWindow` call as it is in my example, or
```js
console.time('load')
mainWindow.loadFile('index.html')
  .then(() => console.timeEnd('load'))
```

**Comment by AlttiRi** [comment]
I have updated comments above and the example gist.

Use `node exec-electron-dot.js`, or `node exec-npm-start.js` for benchmarking.

**Comment by AlttiRi** [comment]
Well... 

`node exec-npm-start.js` (Electron 16.0.6):
```
[exec start][npm start] 6
[data] 865

> electron-quick-start@1.0.0 start
> electron .

[data] 959

[data] 1036
[log][Code executing started...]

[data] 1106
[log][mainWindow.loadFile/loadURL called...] 73

[data] 3116
[log][mainWindow.loadFile/loadURL completed] 2011

[data] 3117
[log][Code executing completed] 2084
```
**More than 3.1 seconds** from the start of the hello world program to show HTML!

Rechecked on VM, the same thing is (but slower — 3.4 s total).

---

With `node exec-electron-dot.js` (the old Electron 7.1.1, installed globally):
```
[exec start][electron .] 6
[data] 84

[data] 150
[log][Code executing started...]

[data] 206
[log][mainWindow.loadFile/loadURL called...] 56

[data] 1606
[log][mainWindow.loadFile/loadURL completed] 1401
[log][Code executing completed] 1457
```

The old Electron is twice faster with the same code (1600 ms vs 3100 ms).

- 200 ms vs 1000 ms to load all things.
- 1400 ms vs 2100 ms to render HTML (`loadFile`).

---

Also I remember that two 2 years ago when I tested the hello word example it rendered with ~300 ms (500 ms total). However it was a bit different code (I doesn't not it now).

---

NW.js right now loads within ~500 ms, in comparison.

**Comment by danielehrhardt** [comment]
> Well... 
> 
> `node exec-npm-start.js` (Electron 16.0.6):
> ```
> [exec start][npm start] 6
> [data] 865
> 
> > electron-quick-start@1.0.0 start
> > electron .
> 
> [data] 959
> 
> 
> [data] 1036
> [log][Code executing started...]
> 
> [data] 1106
> [log][mainWindow.loadFile/loadURL called...] 73
> 
> [data] 3116
> [log][mainWindow.loadFile/loadURL completed] 2011
> 
> [data] 3117
> [log][Code executing completed] 2084
> ```
> **More than 3.1 seconds** from the start of the hello world program to show HTML!
> 
> Rechecked on VM, the same thing is (but slower — 3.4 s total).
> 
> ---
> 
> With `node exec-electron-dot.js` (the old Electron 7.1.1, installed globally):
> ```
> [exec start][electron .] 6
> [data] 84
> 
> 
> [data] 150
> [log][Code executing started...]
> 
> [data] 206
> [log][mainWindow.loadFile/loadURL called...] 56
> 
> [data] 1606
> [log][mainWindow.loadFile/loadURL completed] 1401
> [log][Code executing completed] 1457
> ```
> 
> The old Electron is twice faster with the same code (1600 ms vs 3100 ms).
> 
> - 200 ms vs 1000 ms to load all things.
> - 1400 ms vs 2100 ms to render HTML (`loadFile`).
> 
> ---
> 
> Also I remember that 2 years ago when I tested the hello word example it rendered with ~300 ms (500 ms total). However it was a bit different code (I doesn't have it now, it was from the guide on the site).
> 
> ---
> 
> NW.js right now loads within ~500 ms total, in comparison.

I can confirm this. My clients reported this as customer. After i update electron to newer version.

**Comment by AlttiRi** [comment]
### About the starting time (before `loadFile` call):

I have installed the new version of Electron 16.0.6 globally on VM
and now starting time reduced from 1 second to 200 ms (if I use `node exec-electron-dot.js`, instead of `node exec-npm-start.js`).

```
[exec start][electron .] 7
[data] 113


[data] 205
[log][Code executing started...]

[data] 294
[log][mainWindow.loadFile/loadURL called...] 92

[data] 2259
[log][mainWindow.loadFile/loadURL completed] 1966
[log][Code executing completed] 2058
```
(`loadURL` is still ~2 seconds.)

---

So, that is the problem with `npm start`? 
Why is slower x4 times by 800 ms on any version?

---

Okay, the output of `node exec-npm-start.js` starts with:
```
[exec start][npm start] 6
[data] 865

> electron-quick-start@1.0.0 start
> electron .

[data] 959


[data] 1036
[log][Code executing started...]
```

**So, that `npm start` does for ~800 ms before it calling `electron .`?**

**Comment by xland** [comment]
How about this issue's progress?

**Comment by xland** [comment]
Is anyone working on this Issue?

**Comment by woshidamaomao** [comment]
How about this issue's progress?

**Comment by xland** [comment]
@ckerr 
Has this issue been ignored?

**Comment by Tarrowren** [comment]
This is a problem caused by antivirus software

![image](https://user-images.githubusercontent.com/35626141/174512432-a7ee5093-bfe5-49d3-a83d-52219801d526.png)

Add to whitelist

![image](https://user-images.githubusercontent.com/35626141/174512182-ab3209ca-4e36-4885-8c2d-6b5f05fc01c9.png)

**Comment by xland** [comment]
@Tarrowren , 兄台，你的两张图的代码貌似是一样的。

**Comment by Tarrowren** [comment]
> @Tarrowren , 兄台，你的两张图的代码貌似是一样的。

Right, just add the folder to the whitelist.
For production, you only need to provide the certificate, no need to let the user add the whitelist manually

**Comment by xland** [comment]
@Tarrowren 

Chould you test with these code :
```js
const {app, BrowserWindow} = require('electron')
function createWindow () {
  console.time("load")
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  })
  mainWindow.loadFile('index.html')
  mainWindow.once('ready-to-show', () => {
    console.timeEnd("load")
  })
}
app.whenReady().then(() => {
  createWindow()
})
```

It usually take 2 seconds on my pc.

**Comment by Tarrowren** [comment]
> @Tarrowren
> 
> Could you test with these code :
> 
> ```js
> const {app, BrowserWindow} = require('electron')
> function createWindow () {
>   console.time("load")
>   const mainWindow = new BrowserWindow({
>     width: 800,
>     height: 600,
>   })
>   mainWindow.loadFile('index.html')
>   mainWindow.once('ready-to-show', () => {
>     console.timeEnd("load")
>   })
> }
> app.whenReady().then(() => {
>   createWindow()
> })
> ```
> 
> It usually take 2 seconds on my pc.



![image](https://user-images.githubusercontent.com/35626141/174516915-88af5318-0c6f-4bb7-bcc2-179efcd105e0.png)

I suggest you test it yourself, it is not difficult to add a whitelist. Of course it's okay to turn off the antivirus software. 😀

**Comment by xland** [comment]
@Tarrowren 

Thanks very much.

You know it is impossible to edit or shutdown the antivirus software in some of Chinese company.

**Comment by xland** [comment]
@Tarrowren 

Did you mean Windows Defender?
I try to close Windows Defender or add exception to Windows Defender on my personal pc.
it can not reduce the time consumption.

**Comment by xland** [comment]
Someone said  submiting executable file to MS Defender Team would solve this issue,
I'm not sure.
https://stackoverflow.com/a/68121212

**Comment by AlttiRi** [comment]
bump

**Comment by xland** [comment]
bump

**Comment by herrbasan** [comment]
Here is my question, how does VS Code solve the problem? It is not plagued with the slow startup times as other Electron based apps. From what I understand, you can't really sign an electron app, you can only sign the installer. So I wonder if MS is just sneaky and has whitelisted VS Code in the Defender database?!

**Comment by pushkin-** [comment]
bump

**Comment by Achilles822** [comment]
Same here.It's a big problem.

**Comment by xland** [comment]
bump

**Comment by max-sistemich-kisters** [comment]
@herrbasan FWIW, the VS Code binary itself *is* signed.

I tried signing my own binary (not the installer), but it didn't fix the problem.
I also tried to not load a file from the file system (which could trigger a virus scanner), but just a hardcoded HTML string from memory like this:

```
splash.on('show', async () => {
  await splash?.webContents.loadURL('data:text/html;charset=utf-8,! Content loaded !');
})
splash.show()
```

That didn't fix the problem either, but at least there is *some* benefit with this approach: we show the window as early as possible and only start loading the URL when the window is already shown. Until then the windows is blank, but I think the earlier feedback is worth it.

**Comment by max-sistemich-kisters** [comment]
bump

**Comment by PI-YWT** [comment]
Is there a solution to this problem?

I'm using the Electron 30.0.7 version..

In my case **loadURL** was delayed by about 20 seconds on Windows10 PC.
**loadURL** worked much faster on other Windows11 PC.
I don't know the exact reason, but Windows11 PC has better specifications.

**Comment by mankeheaven** [comment]
bump

**Comment by he-jialin** [comment]
bump.
I've noticed that windows opened using `window.open()` in the renderer process load very slowly, while they run quite fast in the local development environment of Electron.

**Comment by rizaldirnm** [comment]
bump
