### ISSUE TITLE
[Bug]: Websocket error ERR_CONNECTION_CLOSED in renderer process but not in main process

### ISSUE THREAD

**Issue by Seraphli** [electron/electron#32387]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 LSTC 1809

### What arch are you using?

x64

### Expected Behavior

Connect to a localhost server with URL "wss://localhost:42224/Location". This URL works in Chrome, whether using the page that creates ws client or using console to create ws client.
And this works in the main process.
```
let socket = new WebSocket("wss://localhost:42224/Location");
```
or
```
const WebSocket = require('ws');
const socket = new WebSocket("wss://localhost.newworldminimap.com:42224/Location");
```
After a few seconds, I check the readyState and it returns 1.
But when I try to run this in the renderer process, it returns
```
WebSocket connection to 'wss://localhost:42224/Location' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
```
I tested in the script or console. All return the same error.

### Actual Behavior

Should be able to connect to websocket server in renderer process as same as in Chrome.

**Comment by VerteDinde** [comment]
Hey @Seraphli, thanks for reporting this issue! Would it be possible for you to make a standalone test case that reproduces the issue? Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that we as maintainers can use. If you have your script, sharing that would be helpful as well.

Sorry for the trouble, I know making a repro isn't always easy - we've just found having a small repro ensure everyone's looking at the same issue, it removes all unnecessary variables from debugging, and it can also provide the basis for automated regression tests to make sure this doesn't break again.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment. Thanks in advance!

**Comment by Seraphli** [comment]
I have taken some time to create a test case for wws connection. I find out that there is no problem with a simple server. But I can not get to modify the server that has a problem in electron but work well in the browser. So I guess it is not a bug in wss connection, but a problem in the environment. I notice in the broswer when I check the security tab, I can find the wss connection has certificate information. But in electron, the connection is labeled unknown.
But when I create a test case the certificate always shows unknown whether in electron or in Chrome. Because I have used a self-signed certificate, I can not find the exact reason for this error.

**Comment by Seraphli** [comment]
I find out it might be caused by CORS. Is there still a way to control CORS in electron?

**Comment by Seraphli** [comment]
I have resolved this issue.
I try to dump netlog, and find out the error is the same as 
https://stackoverflow.com/questions/37883759/errorssl-client-socket-openssl-cc1158-handshake-failed-with-chromedriver-chr
so after adding
`app.commandLine.appendSwitch('ignore-certificate-errors');`
this issue is resolved.
