### ISSUE TITLE
[Bug]: additionalArguments are no longer the last arguments sent to the window. 

### ISSUE THREAD

**Issue by humble-cburnham** [electron/electron#32384]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1

### What arch are you using?

x64

### Last Known Working Electron version

13.6.6

### Expected Behavior

Under version 13.3.0 the additionalArguments I used to create a window would get appended to the end of the `process.argv` list. 

```
  const Window = new BrowserWindow({
    webPreferences: {
      additionalArguments: ['myTestArgument'],
    },
  });
```

In the window that opens I would see the arg as the last item in the list. I could access it easily with an `window.process.argv.slice(-1)`

```window.process.argv
(18) ['C:\\Users\\Chris\\work\\####\\node_modules\\electron\\dist\\electron.exe', '--type=renderer', '--user-data-dir=C:\\Users\\Chris\\AppData\\Roaming\\####', '--app-user-model-id=###', '--app-path=C:\\Users\\Chris\\work\\###', '--no-sandbox', '--no-zygote', '--field-trial-handle=1820,5394663563312905764,1805328865772920322,131072', '--disable-features=PlzServiceWorker,SpareRendererF…SitePerProcess,WinRetrieveSuggestionsOnlyOnDemand', '--disable-gpu-compositing', '--lang=en-US', '--device-scale-factor=1', '--num-raster-threads=4', '--enable-main-frame-before-activation', '--renderer-client-id=4', '--mojo-platform-channel-handle=2904', '/prefetch:1', 'myTestArgument']
```

### Actual Behavior

At some point `/prefetch?1` is getting moved to the final argument. 

The additionalArguments are still present, but they are no longer the last arguments in the list.

My process.argv looks like
```
window.process.argv
(18) ['C:\\Users\\Chris\\work\\####\\node_modules\\electron\\dist\\electron.exe', '--type=renderer', '--user-data-dir=C:\\Users\\Chris\\AppData\\Roaming\\###', '--app-user-model-id=###', '--app-path=C:\\Users\\Chris\\work\\###', '--no-sandbox', '--no-zygote', '--field-trial-handle=1820,5394663563312905764,1805328865772920322,131072', '--disable-features=PlzServiceWorker,SpareRendererF…SitePerProcess,WinRetrieveSuggestionsOnlyOnDemand', '--disable-gpu-compositing', '--lang=en-US', '--device-scale-factor=1', '--num-raster-threads=4', '--enable-main-frame-before-activation', '--renderer-client-id=4', '--mojo-platform-channel-handle=2904', 'myTestArgument', '/prefetch:1'
```

### Testcase Gist URL

https://gist.github.com/humble-cburnham/c5b0f199205095bc1eb76d66ce95fc99

### Additional Information

The documentation says "A list of strings that will be appended to process.argv in the renderer process of this app" which I interpreted to mean that they would always be the last items in the argv. 

I'm not sure my assumption is correct, and I've refactored my code to be explicit with argument names and to search the argv list instead of assuming that things would be at the end. 

Looks like it was introduced in 14.0.0

**Comment by ckerr** [comment]
This isn't happening for me on Linux. Gist tested on Ubuntu 21.10 with Electron 16.0.5 and 14.0.0.

It _is_ happening for me on Windows. Works in 14.0.0-beta.3 and is re-ordered in 14.0.0-beta.5. (Looks like 14.0.0-beta.4 did not get released)

https://github.com/electron/electron/compare/v14.0.0-beta.3...v14.0.0-beta.5

**Comment by ckerr** [comment]
Note: it's windows-only because the upstream code that appends that argument is Windows-only:

https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_process_host_impl.cc;l=3237?q=render_process_host_impl.cc&ss=chromium

**Comment by ckerr** [comment]
Not sure if this is is related or a red herring, but https://github.com/electron/electron/blame/172ac2501330c64c2a33c1004e05eb23f9658903/shell/common/api/electron_api_command_line.cc#L45 was part of https://github.com/electron/electron/pull/29594 which landed inbetween beta 3 and beta 5 and modifies how args are appended

**Comment by miniak** [comment]
IMO application could should definitely not rely on the order of the arguments

**Comment by miniak** [comment]
Closing, if you don't agree we can consider re-opening.
