### ISSUE TITLE
[Bug]: Non-focusable window doesn't accept clicks

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#32383]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0-beta.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 21H2
Windows 10 version 21H2 build 19044.1415

### What arch are you using?

x64

### Last Known Working Electron version

17.0.0-alpha.3

### Expected Behavior

BrowserWindow with `focusable: false` set accepts mouse clicks in the WebContents.

https://user-images.githubusercontent.com/1656324/148589896-0d13a8ba-874d-4bf5-9f8b-595a58241326.mov

### Actual Behavior

BrowserWindow with `focusable: false` does not accept any mouse clicks in the WebContents.

https://user-images.githubusercontent.com/1656324/148590347-376d7813-e453-47dd-93a5-208f060a9d24.mov

### Testcase Gist URL

https://gist.github.com/samuelmaddock/86794f65af5225c0620b20aae49aff9a

**Comment by samuelmaddock** [comment]
Changes to `LegacyRenderWidgetHostHWND` cause the window messages for clicks not to be properly captured. The upstream commit causing this behavior is https://chromium.googlesource.com/chromium/src/+/c9f0bd6dab7ec93c8b14f179917a12b51eb662c1%5E%21/

Here's a stack trace for left-clicking in the window with `focusable: true`. The point where HWND messages are captured differs.

| 17.0.0-alpha.3 | 17.0.0-alpha.4 |
| --- | --- |
| ![devenv_2022-01-10_15-07-17VGO5](https://user-images.githubusercontent.com/1656324/148846812-27d95c34-060f-476a-88cb-a52545f30df8.png) | ![devenv_2022-01-10_15-12-17sHhe](https://user-images.githubusercontent.com/1656324/148846829-7e2222b7-d46f-44ea-a6ed-583d43bbeb4f.png) |

Removing the added `WS_EX_LAYERED` window style resolves the issue.

**Comment by samuelmaddock** [comment]
Chromium bump to 98.0.4758.9 includes the fix commit which will be released in v17.0.0-beta.3.

**Comment by ckerr** [comment]
@samuelmaddock nice sleuthing!

It looks like v17.0.0-beta.3 is being generated right now. When it's released, can you test to confirm this fix?

**Comment by samuelmaddock** [comment]
Confirmed fixed in v17.0.0-beta.3 🎉
