### ISSUE TITLE
[Bug]: does not exist sender from context-menu

### ISSUE THREAD

**Issue by yunjimmy** [electron/electron#32391]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^16.0.4

### What operating system are you using?

macOS

### Operating System Version

macOs Monterey  12.1 Apple m1 pro

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

```
webContents.on('context-menu', (e, params) =>  {
 e.sneder  //  sender type: WebContents 
});
```

### Actual Behavior

```
webContents.on('context-menu', (e, params) =>  {
 e.sneder  //  sender does not exsit  'context-menu' event 
});
```

### Additional Information

If you log in, "sender" exists.
However, the type does not support it.

![image](https://user-images.githubusercontent.com/93508630/148725303-5cb632b0-e4af-490b-892b-701e1d118012.png)

**Comment by miniak** [comment]
@yunjimmy you have typos in your code snippets :) `e.sneder`

**Comment by miniak** [comment]
Basically all events, this is not specific to `context-menu` have a `sender` property, which is currently not documented.
Those events either don't even have the `event` argument listed or it's this one:

```ts
type GlobalEvent = Event & { returnValue: any };

namespace Electron {
  interface Event extends GlobalEvent {
    // Docs: https://electronjs.org/docs/api/structures/event
    preventDefault: (() => void);
  }
}
```

**Comment by miniak** [comment]
@yunjimmy, @VerteDinde we should probably create a new bug for this generic issue.

**Comment by miniak** [comment]
Maybe we should discuss this in the @electron/wg-api

**Comment by yunjimmy** [comment]
@miniak  I don't know when the documentation will proceed, but thank you for your detailed explanation.
