### ISSUE TITLE
[Bug]: ses.on('will-download') fired twice in webview 

### ISSUE THREAD

**Issue by jinshaopu** [electron/electron#32428]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

Windows

### Operating System Version

windows10

### What arch are you using?

ia32

### Last Known Working Electron version

???

### Expected Behavior

in the "web-contents-created" event   
contents.session.on("will-download", (event, item, webContents) => {
      ....
      log.log("====================================================");
      if (mkdirsSync(fileCacheDir)) {
         item.setSavePath(downfileName);
      }
}
this event fired once when the <a/> link is clicked 

### Actual Behavior

this event fired twice

**Comment by jinshaopu** [comment]
i found the reason .my app has two webview has been set the evnent handler  .when i has three webview added the event handler.if fired once more

**Comment by codebytere** [comment]
Closing in light of the above.
