### ISSUE TITLE
`npm start` starts x5 times longer (by 800 ms) than `electron .`

### ISSUE THREAD

**Issue by AlttiRi** [electron/electron#32432]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

Windows

### Operating System Version

21H1

### What arch are you using?

x64

### Expected Behavior

The application start (before JS code executing of `main.js`) with  `npm start` is the same as when I run `electron .` (Electron is installed globally) and it takes ~200 ms.

### Actual Behavior

The application start takes ~1000 ms (1 second).

This log
```
> electron-quick-start@1.0.0 start
> electron .
```
appears after 800 ms after I exec `npm start` .

### Testcase Gist URL

https://gist.github.com/AlttiRi/d51f33beef067b54689fecf4fe5d46fa

Use `node exec-npm-start.js`, or `node exec-electron-dot.js` for profiling.

### Additional Information

I have noted it already here: https://github.com/electron/electron/issues/32375#issuecomment-1010845256

**Comment by miniak** [comment]
`npm start` will always be slower and there is nothing we can do about it.

**Comment by AlttiRi** [comment]
Well, yes. It's NPM's issue.

With:
```json
  "scripts": {
    "start": "node 1.js"
  },
```

and `1.js`:
```js
console.log(1);
```

---

`npm start` takes 800 ms to print `1`.

While `node 1.js` prints it almost instantly (130 ms),

**Comment by AlttiRi** [comment]
Tested yarn (`npm install --global yarn`).

It works much faster than NPM.

---

Here is the result for yarn (`node exec-yarn-start.js`):
```
[exec start][yarn start] 7
[data] 201
yarn run v1.22.17

[data] 254
$ electron .

[data] 372


[data] 465
[log][Code executing started...]

```
While npm (`node exec-npm-start.js`):
```
[exec start][npm start] 8
[data] 1060

> electron-quick-start@1.0.0 start
> electron .


[data] 1201


[data] 1342
[log][Code executing started...]

```

---

Note: yarn installed with `corepack enable` starts by 100 ms longer that `npm install --global yarn`.

**Comment by AlttiRi** [comment]
OK, I have created NPM issue for this: https://github.com/npm/cli/issues/4413
