### ISSUE TITLE
[Bug]: Windows 10/11: Electron 16 doesn't start up under certain graphics hardware configurations

### ISSUE THREAD

**Issue by scottnonnenberg-signal** [electron/electron#32440]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

Windows

### Operating System Version

Window 10 Enterprise 64 Bit 1909, Windows 10 21H2, Microsoft Windows 11 Business 22000, 

### What arch are you using?

x64

### Last Known Working Electron version

15.3.2

### Expected Behavior

Start up with no problem, window visible, renderer code running.

### Actual Behavior

Not starting up at all, or starting up only with `--disable-gpu` flag, or only starting up after graphics driver has been upgraded.

In most cases, users are saying that the app starts up, with five running processes, but no window. One user reported a blank screen. No logging from Signal Desktop code. You can see the user reports here:

- https://github.com/signalapp/Signal-Desktop/issues/5726
- https://github.com/signalapp/Signal-Desktop/issues/5721
- https://github.com/signalapp/Signal-Desktop/issues/5738

Several users ran into this on Signal Desktop 5.27.0 where previous version of Signal Desktop didn't have problems. The major change is the upgrade from Electron 15 to Electron 16.

An example of the output we got from one of our users with `--enable-logging`:

```
[43300:0111/223036.911:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[43300:0111/223036.912:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 1 time(s)
[43300:0111/223037.141:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[43300:0111/223037.141:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 2 time(s)
[43300:0111/223037.357:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[43300:0111/223037.357:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 3 time(s)
[43300:0111/223037.397:INFO:CONSOLE(33)] "The vm module of Node.js is deprecated in the renderer process and will be removed.", source: node:electron/js2c/renderer_init (33)
[43300:0111/223037.784:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[43300:0111/223037.784:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 4 time(s)
[43300:0111/223037.866:INFO:CONSOLE(33)] "The vm module of Node.js is deprecated in the renderer process and will be removed.", source: node:electron/js2c/renderer_init (33)
[43300:0111/223038.037:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[43300:0111/223038.037:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 5 time(s)
[43300:0111/223038.278:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[43300:0111/223038.278:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 6 time(s)
[43300:0111/223038.382:WARNING:gpu_process_host.cc(996)] Reinitialized the GPU process after a crash. The reported initialization time was 0 ms
```

Also:

```
[18796:0106/130403.410:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[18796:0106/130403.724:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[18796:0106/130404.043:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
(node:26628) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Signal --trace-deprecation ...` to show where the warning was created)
[18796:0106/130406.831:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[18796:0106/130407.327:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[18796:0106/130407.812:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
```

A variety of different graphics hardware was involved:

- NVIDIA GeForce RTX 3060 Laptop GPU
- Intel UHD Graphics 620
- Intel UHD Graphics 630
- Intel HD Graphics 4000

**Comment by PauIGB** [comment]
got the similar issue on Ubuntu 20.04.3 LTS for electron 16.x verisions:

**Comment by VerteDinde** [comment]
Thanks for reporitng this @scottnonnenberg-signal! We're looking into it now - I unfortunately don't have any of the affected hardware that you reported, but we're looking for more people that do. Will see if we can narrow down what changed in Electron 16 that could have caused this.

**Comment by VerteDinde** [comment]
@scottnonnenberg-signal Debugging a bit further - do you happen to have the (broken) driver versions for some of your affected users? For your NVIDIA/Intel users, do you know if they're using Optimus (and if so, does disabling Optimus fix the white screen)?

**Comment by mwrona92** [comment]
@VerteDinde Here's the driver version. Not sure what Optimus is 🤔 

<img width="200" alt="mmc_2022_01_14_10_400_455_Macaw" src="https://user-images.githubusercontent.com/46519886/149556933-7a0a3700-2421-4af7-b986-1d25d02a819c.png">

**Comment by BrunoBernardino** [comment]
I have the same issues as @PauIGB above. `--disable-gpu` did work for me (though the error log keeps showing). Here are my machine's internal details:

```
$ uname -r
5.8.0-63-generic
```

```
$ sudo lshw -c video
 *-display                 
       description: VGA compatible controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 mode=2880x1800 visual=truecolor xres=2880 yres=1800
       resources: iomemory:600-5ff iomemory:400-3ff irq:152 memory:601c000000-601cffffff memory:4000000000-400fffffff ioport:3000(size=64) memory:c0000-dffff memory:4010000000-4016ffffff memory:4020000000-40ffffffff
```

```
$ inxi -G
Graphics:  Device-1: Intel driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.13 driver: fbdev unloaded: modesetting,vesa resolution: 2880x1800~90Hz 
           OpenGL: renderer: Mesa Intel Xe Graphics (TGL GT2) v: 4.6 Mesa 21.0.3
```

Let me know if there's anything else I can share to help.

**Comment by spogulis** [comment]
> @scottnonnenberg-signal Debugging a bit further - do you happen to have the (broken) driver versions for some of your affected users? For your NVIDIA/Intel users, do you know if they're using Optimus (and if so, does disabling Optimus fix the white screen)?

HP elitebook 845 g7 with i7 cpu - using only integrated graphics and the latest gpu driver.

**Comment by nornagon** [comment]
Is this possibly related to https://github.com/electron/electron/issues/30966? The failures look somewhat similar.

Also, could we perhaps get a crash dump?

**Comment by BrunoBernardino** [comment]
@nornagon it _might_ be, but in my case I have no unicode characters anywhere in the tree (`/usr/bin/signal-desktop` is where my signal runs from). As for the crash dump, are you looking for a specific file or log? Or something generated with a specific command?

**Comment by VerteDinde** [comment]
Thanks @scottnonnenberg-signal! Sorry, Optimus is a new feature of certain NIVIDIA drivers that allows for auto switching of the GPU, depending on a few factors [(linked here)](https://wiki.archlinux.org/title/NVIDIA_Optimus). I wasn't sure of that GPU auto-switching might be a factor here, so wanted to see if it was activated or not when you mentioned an NVIDIA driver.

**Comment by mwrona92** [comment]
@VerteDinde Happy to help if you help me get crash dumps

**Comment by VerteDinde** [comment]
@mwrona92 Absolutely! Sorry, I should have included instructions! 🙂  You can collect them by adding the following snippet to your main process code, before app.whenReady:

```
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```
Then reproduce the crash, zip up the crash dumps directory and attach it here. Appreciate your help!

**Comment by Jacobus52999** [comment]
I've seen this happen recently for clients running our electron based app on Azure VMs, particularly Windows 10 Enterprise 20H2 (OS Build 19042.1110) VM. The VM is a D2s V3 Spec (2vcpu & 8 GB of memory.). Managed to replicate this in our own Azure cloud so perhaps that'll be useful for you to collect more crash dumps

**Comment by miniak** [comment]
We are hitting this as well. It looks like Electron 16 does not properly recover from GPU process crashes.

**Comment by miniak** [comment]
Seems to have happened in this range https://github.com/electron/electron/compare/v16.0.0-alpha.7...v16.0.0-alpha.8

**Comment by miniak** [comment]
We also found out that it got fixed here https://github.com/electron/electron/compare/v17.0.0-alpha.3...v17.0.0-alpha.4

**Comment by miniak** [comment]
This might be related [3152735: Always use SwANGLE on Windows and Linux](https://chromium-review.googlesource.com/c/chromium/src/+/3152735)

**Comment by miniak** [comment]
We could try #33892, but this does not address the root cause, which is the incorrect handling of GPU process crashes / fallback to SW rendering.

**Comment by miniak** [comment]
This might help #33892

**Comment by miniak** [comment]
@scottnonnenberg-signal can you please try `app.commandLine.appendSwitch('disable-features', 'MediaFoundationAsyncH264Encoding')`?
