### ISSUE TITLE
[Bug]: Iframe preload doesn't load (in certain case)

### ISSUE THREAD

**Issue by theArina** [electron/electron#32453]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 19042.1415

### What arch are you using?

x64

### Last Known Working Electron version

I just know that 15.0.0 acts the same

### Expected Behavior

Every preload of any iframe loads every time.

### Actual Behavior

Iframe's preload loading is prevented by following sequence of events (meaning that preload couldn't load at all, and there's no errors):

1. Inside preload add event listener 'DOMContentLoaded'
2. Inside callback send message to the webview ('ipcRenderer.sendToHost')
3. On catching it (with 'ipc-message' listener) send message back ('webview.send')
4. Catch it back in the our preload with 'ipcRenderer.on'
5. Inside callback send 'postMessage' to all iframes (recursively)
6. See that one of them isn't always (!sometimes it is, but rarely) loading

The url we're looking for would be:
`https://www.eventbrite.com/checkout-external?eid=96116339559&parent=https%3A%2F%2Fwww.eventbrite.com%2Fe%2Fbuilt-to-spill-tickets-96116339559&modal=1&aff=oddtdteb`

First we thought that iframe might be not ready yet for recieving post messages (and somehow sending one there is destroying something and causing the issue) and it still looks like it, however if we remove even one event of this event chain, the bug won't be reproduced. For example if we'll send post message on 'DOMContentLoaded' straightaway or for example if we only send ipc message back on webview event 'dom-ready'.

I added comments to my gist example so it could be easier to understand what's going on, but of course ask me anything regarding the issue, I'll try to explain it better.

### Testcase Gist URL

https://gist.github.com/theArina/20ba29aaadc928c9a0fb37e1472a6bb1

### Additional Information

All you need to do in the gist after starting app is press green button, then you'll see in devtools console that needed url isn't logged (please try to run it few times, it's not always reproduces, but almost always).
In the comments you'll see the instructions of how to see how it should work normally (or of course you could just comment everything in preload exept logging location).

**Comment by rr13k** [comment]
Is there any progress? Is it happening here

Previous correct version V9.4.4

**Comment by theArina** [comment]
@rr13k, I guess it's to rare and tricky to debug idk.

**Comment by theArina** [comment]
@rr13k, eventually we've decided to use webContents.sendToIframe() method instead of postMessage(), it's working fine.

**Comment by aquade** [comment]
We had to create a work around by calling [executeJavascript ](https://www.electronjs.org/docs/latest/api/web-frame-main#frameexecutejavascriptcode-usergesture) on every frame (main and child frames) to run a script that verifies if the context bridge created by the preload script is there. If it's not there then the injected script reloads the frame to force it to load. We've observed around 10-15% of all child frames we load don't initially load the preload script. Reloading the frame does cause it to load however it's a really janky solution. This behavior has been around as far back as Electron 9 but after 12 it starting happening more frequently, it still occurs on the most recent version of Electron.

**Comment by YanLIU0822** [comment]
> 

I have the same issue here. The iframe in the page does not load the preloads every time. I would like to know the reason for this issue. Could you tell me the reason?

**Comment by pratyushtiwary** [comment]
Here's a patch I've found incase anyone faces this issue in future:
```js
// patch to get preload js working for iframes with DOMContentLoaded (issue: https://github.com/electron/electron/issues/32453)
function reloadIframesAfterContentLoad(iframes) {
  // reload iframes once the content is loaded
  // this for some reason correctly triggers preload.js inside iframes
  iframes.forEach(iframe => {
    iframe?.contentWindow?.addEventListener('DOMContentLoaded', () => {
      iframe.contentWindow.location.reload();
    });
  });
}

// handle initial load iframes
const iframes = document.querySelectorAll('iframe');

reloadIframesAfterContentLoad(iframes);

// handle dynamically injected iframes
const mutationObserver = new MutationObserver(mutations => {
  const iframes = [];

  mutations.forEach(mutation => {
    const addedRecords = [...mutation.addedNodes];
    iframes.push(
      ...addedRecords.filter(addedNode => addedNode.tagName === 'IFRAME')
    )
  });


  reloadIframesAfterContentLoad(iframes);
});

mutationObserver.observe(document, {
  childList: true,
  subtree: true
});
```

Add this in preload js and it should correctly load preload js inside iframes with DOMContentLoaded listener attached to window
