### ISSUE TITLE
[Bug]: electron some css style not draw on win7

### ISSUE THREAD

**Issue by rodchen-king** [electron/electron#32454]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.3

### What operating system are you using?

Windows

### Operating System Version

win7

### What arch are you using?

ia32

### Expected Behavior

Dom and css can show succesfully.

### Actual Behavior

Some css style not draw. The dom background is white, but middle part not draw css style.

![image](https://user-images.githubusercontent.com/19780441/149325184-58feedde-071c-4759-9aa4-30eeb01b96a1.png)

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
