### ISSUE TITLE
[Bug]: macOS transparent window font shadow residual

### ISSUE THREAD

**Issue by lyswhut** [electron/electron#32450]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.x/14.x/15.x/16.x

### What operating system are you using?

macOS

### Operating System Version

macOS 11

### What arch are you using?

x64

### Expected Behavior

MAC OS transparent windows should not have font shadow residue

### Actual Behavior

On the Mac OS platform, there will be font shadow residue on transparent windows

### Testcase Gist URL

https://gist.github.com/5112851712bcd11e7045921fee1cbbf7

### Additional Information

This is a long-standing issue, previously related issue:
- https://github.com/electron/electron/issues/14304
- https://github.com/electron/electron/issues/21173

![image](https://user-images.githubusercontent.com/20365169/149276756-55789261-f884-4898-8213-e8504f56cabb.png)

**Comment by xiajingren** [comment]
Any progress?

**Comment by lyswhut** [comment]
bump

**Comment by xiajingren** [comment]
bump

**Comment by boubacardabo** [comment]
bump
