### ISSUE TITLE
flake: <webview> tag loads devtools extensions registered on the parent window 

### ISSUE THREAD

**Issue by codebytere** [electron/electron#32461]
> <webview> tag loads devtools extensions registered on the parent window 

has been commonly flaking on WOA recently:
- https://github.com/electron/electron/pull/32441/checks?check_run_id=4795823418
- https://github.com/electron/electron/pull/32442/checks?check_run_id=4797509771

cc @jkleinsc

**Comment by jkleinsc** [comment]
This has been flaky for a while
https://github.visualstudio.com/electron/_test/analytics?definitionId=48&contextType=build.

I'm going to skip this test on WOA
