### ISSUE TITLE
[Bug]: setAsDefaultProtocolClient sets wrong command

### ISSUE THREAD

**Issue by TanninOne** [electron/electron#32463]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Build 19043

### What arch are you using?

x64

### Last Known Working Electron version

13.1.2

### Expected Behavior

`app.setAsDefaultProtocolClient(protocol, process.execPath, [path.resolve(process.argv[1]), '--arg']);`
to work as expected.

### Actual Behavior

electron will put quotes around the entire list of arguments instead of each individually (if necessary), so the generated command is something like

"C:\example\node_modules\electron\dist\electron.exe" "c:\example --arg" "%1"

which then leads to an error "Unable to find Electron app at c:\example --args".

### Testcase Gist URL

!!! Please note that by the nature of setAsDefaultProtocolClient this testcase will make a systemwide setting!

https://gist.github.com/a1f2fdbe04624b6f7a6877a89581143c

### Additional Information

This was almost certainly introduced by the "fix" for https://github.com/electron/electron/issues/32141

**Comment by ckerr** [comment]
This sounds plausible, both the bug report and the triage work that you did to track down the likely problem.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

**Comment by nornagon** [comment]
Related to #31710 maybe? cc @bitdisaster

**Comment by TanninOne** [comment]
> This sounds plausible, both the bug report and the triage work that you did to track down the likely problem.
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

I added a testcase to the original post.

**Comment by TanninOne** [comment]
@ckerr repro was added
