### ISSUE TITLE
[Feature Request]: Hook for executing arbitrary code on updates before installing them

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#32477]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

A pretty basic security check for self-updating apps is checking that downloaded updates are properly signed by the developer, so that issues where the update server gets compromised and all existing users get compromised as a result get eliminated.

This is different from code signing, which in any case is not even supported under Linux.

### Proposed Solution

There should be a way to execute code between when updates are downloaded and when they are installed, and a way to manually trigger the actual installation:

- Executing code before installing would allow for computing the hashes on the download updates, hashes to be checked against a signed file containing all hashes the app accepts.
- Triggering the actual installation manually is necessary otherwise if the app is going to install the update anyway on restart the signature check is useless.

### Alternatives Considered

I'm not aware of any possible alternatives.

**Comment by MarshallOfSound** [comment]
This kind of request / feature needs to be in the underlying updater tech (Squirrel) not in Electron core.  For instance on Windows Electron isn't even responsible for downloading the update, it's all done via `Update.exe`
