### ISSUE TITLE
[Question] With `contextIsolation` enabled, am I allowed to import anything from `electron` in renderer process?

### ISSUE THREAD

**Issue by pie6k** [electron/electron#32479]
I need an answer to a very basic question:

If I have `contextIsolation: true` - am I allowed to import ANYTHING in renderer from electron (even 'safe' thing)?

Right now I get crash `TypeError: fs.existsSync is not a function`. It confuses me - do I have something wrong with my build pipeline (using parcel) or am I doing something that is simply not allowed? It happens even if I only import typescript types (in dev mode).

eg. From clipboard docs https://www.electronjs.org/docs/latest/api/clipboard it says:

> Process: Main, Renderer

It suggests me I can use it in both processes. But is it 'conditional' on context isolation being disabled or not - cannot find it clearly stated in docs? 

If it is not allowed - fine, I get it - I simply have to pass anything I need in preload, done. 

I understand security consequences and I don't want to disable context isolation. 

I'd rather expect a clear, instant crash error message `you shall not import me in your renderer process`, 

```ts
// node_modules/electron/index.js
if (renderer) throw new Error('nope');
```

rather than quite 'internal' error. It is especially annoying if I import types only or if I import some file both on main and renderer side, but only use electron apis on main 'switch' case. 

If the answer to above question is yes - I think simply throwing informative error instantly would save a lot of time to a lot of people. (especially as a lot of materials online are based on outdated API or rules of electron)

Another annoying use case is:

```ts
// file-used-in-both-renderer-and-main.ts
import { electronThing } from 'electron';

function doStuff() {
  if (isRenderer) {
    // do nothing
  } else {
    electronThing.stuff();
  }
}
```

Above code is safe. It is not using electron apis on renderer side, but is handy as a one utility used in both processes.

In above, I'd expect no crash until I try to use any electron API in renderer and or eg `electronThing` simply being undefined on renderer side.

**Comment by miniak** [comment]
@pie6k you can still call `require` in the preload script, but then you have to use `contextBridge` to expose your APIs to the webpage context instead of just assigning them to `window`. You cannot use `require` in the webpage context with `contextIsolation`.

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by miniak** [comment]
@pie6k if you have a specific documentation improvement in mind, then please create a specific feature request or ideally a PR addressing the issue
