### ISSUE TITLE
Google Chrome's New Context menu for windows 11 in electronjs ?

### ISSUE THREAD

**Issue by PREKNOWLEDGEWEB** [electron/electron#32488]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Google chrome had recently added custom context menu for windows 11 but electronjs still had the old context menu
this is the new context menu in google chrome
![image](https://user-images.githubusercontent.com/83751707/149669986-bcefa4b6-0b01-4d04-9b8e-a5ff04bd5154.png)

### Proposed Solution

New Context menu

### Alternatives Considered

./

### Additional Information

Please add this menu style if possible.

**Comment by deermichel** [comment]
+1, setting the Chrome flag via commandLine doesn't change the style

**Comment by PREKNOWLEDGEWEB** [comment]
they did'nt added it yet

**Comment by MarshallOfSound** [comment]
This is available in the newest Electron versions
