### ISSUE TITLE
[Bug]: Bug about Electron's dependency on libatk-bridge-2.0.so.0

### ISSUE THREAD

**Issue by Abbyzhoum** [electron/electron#32503]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.3

### What arch are you using?

x64

### Last Known Working Electron version

16.0.7

### Expected Behavior

It is expected that the global installation of electron is successful, and the output shows the version.
Please let me know if there is any progress, thanks a lot.

### Actual Behavior

Hello！
This is my first try,After installing electron globally, check the version of electron. oh！An error is reported, and the error message is displayed.

`/usr/local/lib/node_modules/electron/dist/electron: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory`

### Additional Information

![20220117183125](https://user-images.githubusercontent.com/38661489/149755010-3576e67c-b4f3-40fa-9fe6-09648b0ec5b6.png)

**Comment by BlackHole1** [comment]
execute:

```shell
sudo apt-get install -y libatk-bridge2.0-0 libgtk-3.0 libasound2
```

**Comment by Abbyzhoum** [comment]
> 执行：
> 
> ```shell
> sudo apt-get install -y libatk-bridge2.0-0 libgtk-3.0 libasound2
> ```


`
After I executed the command, check the version of electron again, and still got an error.
`

![5519](https://user-images.githubusercontent.com/38661489/149862863-ad2f2dba-c333-4e77-892f-0953d2c41308.png)

**Comment by BlackHole1** [comment]
It seems to be because you are using a mini-ubuntu distribution

**Comment by Abbyzhoum** [comment]
> It seems to be because you are using a mini-ubuntu distribution
> 
> > sudo electron -v

Hi, forgot to thank you!
Also I tried it and it still doesn't work.🤣
![342](https://user-images.githubusercontent.com/38661489/149894242-4905cf89-57d0-4ffb-bf2b-0738245e60c4.png)
.

**Comment by BlackHole1** [comment]
try `electron -v --no-sandbox`

**Comment by Abbyzhoum** [comment]
> try `electron -v --no-sandbox`

Yeah, I tried it and it worked, thanks a lot. You are awesome!

**Comment by Abbyzhoum** [comment]
Thanks a lot!

**Comment by Abbyzhoum** [comment]
Thanks a lot!
