### ISSUE TITLE
[Bug]: setKiosk on Mac doesn't work as expected when there are multi monitors

### ISSUE THREAD

**Issue by nkbai** [electron/electron#32501]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

macOS

### Operating System Version

macOS BigSur 11.6

### What arch are you using?

x64

### Expected Behavior

BrowserWindow.setKiosk(true) works as expected when there is only one monitor. but if there are two monitors, I can use 
 command+tab   to switch process.

### Actual Behavior

BrowserWindow.setKiosk(true) works as expected when there is only one monitor. but if there are two monitors, I can use 
 command+tab   to switch process.

**Comment by nornagon** [comment]
I can't reproduce this behavior on macOS 12.1 using the following code: https://gist.github.com/0c4bfb9a4253ff696648559729903f07 and an external monitor attached to my laptop.

Are there further conditions needed to produce this behavior?

**Comment by mstfdmrsln** [comment]
You can use this if your application does not needed to other monitors:

```
otherMonitorWindow = null;
screen.on('display-added', (event) => {
let displays = screen.getAllDisplays();
  let externalDisplay = displays.find((display) => {
    return display.bounds.x !== 0 || display.bounds.y !== 0
  })
  otherMonitorWindow = new BrowserWindow...
        x: externalDisplay.bounds.x + 50,
        y: externalDisplay.bounds.y + 50,
        width: externalDisplay.size.width,
        height: externalDisplay.size.height,
        ..
        ..
        otherMonitorWindow.load('empty-content-html-file.html')
        otherMonitorWindow.setMenu(null);
        otherMonitorWindow.maximize();
})
```

**Comment by nkbai** [comment]
This may seem like a no-go,  I can still switch Windows using command tabs at setkiosk (True)
