### ISSUE TITLE
[Bug]: Media Information not showing on Windows 10

### ISSUE THREAD

**Issue by osmestad** [electron/electron#32518]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.5.1, 13.6.7, 14.2.4, 15.3.5, 16.0.7, 17.0.0-beta.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 (Pro 20H2 and others)

### What arch are you using?

x64

### Last Known Working Electron version

12.2.3, 13.5.0

### Expected Behavior

When using keyboard media keys a OS Media Information overlay should pop up (showing track information, album cover and play control buttons). Worked up till Electron 13.5.0  and works in current Chrome (97).

### Actual Behavior

From Electron 13.5.1 and up the Media Information overlay is not displayed. (The keyboard media keys do work though.) Only tested last patch of each major version.

### Testcase Gist URL

https://gist.github.com/b19bc801bd50597c8eeedaf29f0efa2a

### Additional Information

Steps to reproduce:
1. Click "Play" on media in webpage (using Chrome example in the Gist)
2. Trigger Pause using keyboard media keys (Next and Previous have same problem)

This looks very similar to: #30860, there the example URL loaded is for video, here it is audio, but otherwise it looks the same. Created new issue to add details as that one is closed.

(Checking "Obsolete" in Fiddle Electron Settings is needed to load the last working 12 version.)

Update: added test results for 13.5.0 and 13.5.1

**Comment by Araxeus** [comment]
I'd like to expand on this:

1. This didn't use to happen (it worked completely fine a few months ago, even on electron 12)

2. The media session OSD shows up when changing the volume, but NOT when using any other media key (play/pause/next/previous)
   Important note: chrome/edge/spotify etc do show the media OSD when using the media keys, as it is expected

3. the OSD is really bugged on Electron fiddle when not using the latest electron version
   with electron 14: (no media information including play/pause status)
   ![image](https://user-images.githubusercontent.com/78568641/155178703-3c8971f0-c902-4ad7-8683-9c638d90830e.png)
   with electron 17: (play/pause status and media information is updated)
  ![image](https://user-images.githubusercontent.com/78568641/155178630-22815080-857e-4851-91d7-490f3ee7157c.png)
  // test case: https://gist.github.com/581fd5d38496621e5cd9a6020b68438f

**Comment by Araxeus** [comment]
@codebytere why did you close this?

this wasn't fixed, you can try the gist with the latest electron version, if you press any media key it won't show the osd
