### ISSUE TITLE
Question/Help - How to build electron with chromium hardware acceleration on ?

### ISSUE THREAD

**Issue by rexn8r** [electron/electron#32513]
Hi

Need help from electron expert on hardware acceleration in my electron app.

My electron app is build using Electron 16.0.4 (as per package.json)
"devDependencies": {
    "electron": "^16.0.4",
    "electron-builder": "^22.14.5"
  },

When i build my app for linux x64 as well as arm64 and run it on the appropriate linux PC and try to play 4K video, my app doesn't use hardware acceleration and video is choppy and drops frame.

my x64 PC has Intel graphics and arm64 device is Jetson nano and both have graphics drivers installed.

I tried following switches but it made no difference;

On x64 PC:
app.commandLine.appendSwitch('enable-accelerated-mjpeg-decode');
app.commandLine.appendSwitch('enable-accelerated-video-decode');
app.commandLine.appendSwitch('ignore-gpu-blocklist');
app.commandLine.appendSwitch('enable-native-gpu-memory-buffers');
app.commandLine.appendSwitch('enable-gpu-rasterization');
app.commandLine.appendSwitch('enable-oop-rasterization');
app.commandLine.appendSwitch('disable-gpu-driver-bug-workarounds');
app.commandLine.appendSwitch("use-gl", "desktop");
app.commandLine.appendSwitch("enable-features", "VaapiVideoDecoder");

On arm64 PC:
app.commandLine.appendSwitch('enable-accelerated-mjpeg-decode');
app.commandLine.appendSwitch('enable-accelerated-video-decode');
app.commandLine.appendSwitch('ignore-gpu-blocklist');
app.commandLine.appendSwitch('enable-native-gpu-memory-buffers');
app.commandLine.appendSwitch('enable-gpu-rasterization');
app.commandLine.appendSwitch('enable-oop-rasterization');
app.commandLine.appendSwitch('disable-gpu-driver-bug-workarounds');
app.commandLine.appendSwitch("use-gl", "desktop");

so need help from an expert on how to resolve this issue? if i need to build electron with custom switch turned on for chromium, then how do i build it?

any guidance would be highly appreciated.

thanks
rex

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
