### ISSUE TITLE
[Bug]: BrowserWindow size/bounds incorrect when dragging the window from a scaled display to a non-scaled display

### ISSUE THREAD

**Issue by limacheb** [electron/electron#32516]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10, verion 21H2

### What arch are you using?

x64

### Last Known Working Electron version

15.3.4

### Expected Behavior

The size set initially to the BrowserWindow shall be maintained after dragging the BrowserWindow from a scaled display to a non-scaled display

###  The test environment includes two diplays:

1. The laptop display (primary) which is scaled with 125%
2. An extended regular display.

**Screenshots of the display settings page:**  

![image](https://user-images.githubusercontent.com/87860728/149904987-f611c719-6f78-4455-8ee6-7832c367f116.png)

![image](https://user-images.githubusercontent.com/87860728/149905145-03571771-b0a1-4d30-abb7-af5243630cb7.png)

<br>
<br>

### Steps to reproduce

The test application is the regular 'Electron Hello World' application.  
Additionally the application shows the BrowserWindow bounds.  

Start the test application.   
The BrowserWindow constructor sets the width to 800 and the height to 600.
```
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })
```
The application shows up on the primary display as follows:  
![image](https://user-images.githubusercontent.com/87860728/149905837-8851b67c-2d79-40f7-a779-a4a915d72d88.png)

Drag the application onto the secondary display.   
The size gets now 25% larger (width is 1000, height is 750), which is wrong.  
![image](https://user-images.githubusercontent.com/87860728/149906027-63846ee7-e24f-4cd5-bcb6-2225b560ef21.png)

Further dragging the application between the two displays does not change the size anymore (it remains 1000 * 750).

### Testcase Gist URL

https://gist.github.com/272f5fa1ad5f363acfa1a753f87200ef

**Comment by mlaurencin** [comment]
Manually closing as https://github.com/electron/electron/pull/33231 fixes this issue
