### ISSUE TITLE
[Bug]: textarea emits mouse events when typing while hovered with a mouse cursor in a BrowserView

### ISSUE THREAD

**Issue by devinbinnie** [electron/electron#32520]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

macOS

### Operating System Version

macOS Monterrey

### What arch are you using?

x64

### Last Known Working Electron version

Unknown, reproduces all the way back to Electron v12, potentially farther

### Expected Behavior

1. On a Mac, run the attached Gist
2. Using the Developer Tools, in the console type `monitorEvents(document.querySelectorAll('#post_textbox')[0])` and press Enter
3. Hover over the textarea with your mouse and, without moving the mouse, start typing
4. The console should log key and input events only

### Actual Behavior

The console seems to log a bunch of mouse events, such as `mouseout` and `mousemove`, when the mouse is completely stationary.

### Testcase Gist URL

https://gist.github.com/devinbinnie/06a7a7c42b8ad4d0eb5309075bc82b70

### Additional Information

This only seems to occur when the BrowserView's y-offset is set to something >~30-40. If you set the offset to 0, this doesn't seem to occur. I've got it to happen with as low as 20, but it seems less consistent.

On its own this doesn't seem to be a huge issue, but in our app (Mattermost) we were noticing it having very significant affect on performance, as React seems to fire listeners on those events and recalculate state/style causing a lot of performance issues.

I'm looking into solutions for the other issues as well but it would be nice to eliminate the root trigger of this.

Only seems to reproduce on macOS, not any other OSes.

**Comment by zcbenz** [comment]
I can reproduce this issue, but it seems very likely a Chromium bug, so debugging it takes lots of time and I don't think we can look into it any time soon.

**Comment by devinbinnie** [comment]
> I can reproduce this issue, but it seems very likely a Chromium bug, so debugging it takes lots of time and I don't think we can look into it any time soon.

Thanks for looking. The reason I filed here though is that it doesn't reproduce on the Chrome browser, haven't tried Chromium.

**Comment by devinbinnie** [comment]
Hey, just curious if anyone has been able to look into this? We have a customer that is severely affected by this issue since it's causing huge performance problems for them. Thanks in advance :)
