### ISSUE TITLE
[Bug]: subclasses of BrowserWindow do not show up in BrowserWindow.getAllWindows() on macOS

### ISSUE THREAD

**Issue by mitchchn** [electron/electron#32522]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

A custom subclass of `BrowserWindow` should be counted in `BrowserWindow.getAllWindows()` 

```ts
class CustomWindow extends BrowserWindow {
  constructor() {
    super()
  }
}
const mainWindow = new CustomWindow()

console.log(BrowserWindow.getAllWindows())
```

### Actual Behavior

On macOS, the custom window does not appear in the list returned by `BrowserWindow.getAllWindows()`. On all other platforms, it does.

### Testcase Gist URL

https://gist.github.com/5cb2a8c6436b058e970b7d50e0338126

**Comment by nornagon** [comment]
Electron doesn't support subclassing of BrowserWindow (or any other provided class).
