### ISSUE TITLE
[Feature Request]: overlay colour setting for modal browser window

### ISSUE THREAD

**Issue by alexandr-bbm** [electron/electron#32521]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Platform: macOS

When using `new BrowserWindow({...opts, modal true})` it is opened with overlay which colour depends on OS theme:

Light theme:
![image](https://user-images.githubusercontent.com/11938458/149979407-cf369ca2-3b8d-48cf-9a6e-0ba9f11a59f8.png)

Dark theme:
![image](https://user-images.githubusercontent.com/11938458/149979441-23a91a26-70d6-41fd-af4e-866825498576.png)

This causes bad UI for applications without theme support.

### Proposed Solution

As far as I investigated, it is impossible to control overlay colour for modal browser window with current API

I'd like to ask if it is possible, and add such setting if so.

Is it is not possible, I think it makes sense to include information about OS theme dependent coloured overlay to the docs page: https://www.electronjs.org/docs/latest/api/browser-window#modal-windows

### Alternatives Considered

Alternative is not to use new browser window for modals and achieve it by JS in main window. However, in some applications it is desired to have a new window for the sake of security.

**Comment by miniak** [comment]
This is how modal windows look like on macOS, nothing we can do about it AFAIK
