### ISSUE TITLE
[Bug]: app moves to left or up by about 20px when setting zoom from 100% to 200%

### ISSUE THREAD

**Issue by Addeo** [electron/electron#32531]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

The application must resize itself when the popup opens (so that it does not go beyond the visibility of the screen), so the application must not go beyond the visible border of the screen.

### Actual Behavior

The application behaves incorrectly if you set the zoom from 100% to 200%, more precisely, it moves to the left or up by about 20px and stops.

### Additional Information

  ```
  function resizeElectron() {
      const width = document.body.scrollWidth;
      let height = document.body.scrollHeight;

      if (document.body.clientHeight < 100 && height === 100) {
         height = document.body.clientHeight;
         const ipcRenderer =
           window.require && window.require("electron").ipcRenderer;
         if (ipcRenderer) ipcRenderer.send("resize", { width, height });
         return;
       }
       window.resizeTo(width + 20, height + 20);
    }
    resizeElectron();
    let timerId = setInterval(resizeElectron, 100);
     return () => {
      clearInterval(timerId);
    };
    ```
    It's good working in macOS and other Windows

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by AbhiramL** [comment]
Can I help out? I am a beginner in github but have c++ experience

**Comment by anubhav2102** [comment]
Hey! Can i work on this issue?
Thanks!

**Comment by ckerr** [comment]
@anubhav2102 it's not currently claimed by anyone. PRs are always welcomed!
