### ISSUE TITLE
[Bug]: electron13.6.3 app crash on win7.

### ISSUE THREAD

**Issue by rodchen-king** [electron/electron#32532]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.3

### What operating system are you using?

Windows

### Operating System Version

win7

### What arch are you using?

x64

### Expected Behavior

app will not stop working.

### Actual Behavior

app stop working.
![image](https://user-images.githubusercontent.com/19780441/150105794-fc3bbfaa-2c18-4bfe-a996-55ae37abf334.png)

And i found the alllication error.

![image](https://user-images.githubusercontent.com/19780441/150105897-bc3df3c4-863d-4487-b406-99b66ef21014.png)

error message:
错误应用程序名称: 新美心POS程序.exe，版本: 1.1.1.0，时间戳: 0x61a6c849
错误模块名称: 新美心POS程序.exe，版本: 1.1.1.0，时间戳: 0x61a6c849
异常代码: 0x80000003
错误偏移量: 0x02d71d5a
错误进程 ID: 0xaf8
错误应用程序启动时间: 0x01d80cbaafdc62b5
错误应用程序路径: C:\Users\Administrator.PC-202112301328\AppData\Local\Programs\electron-quick-start\新美心POS程序.exe
错误模块路径: C:\Users\Administrator.PC-202112301328\AppData\Local\Programs\electron-quick-start\新美心POS程序.exe
报告 ID: 49124444-78bd-11ec-b99e-6cf049873644

### Additional Information

In my application. There are following function. I dont konw how to fix it. Is ther any solution or idea?

- dll
- node printer
- websocket
- disable gpu on win7

**Comment by VerteDinde** [comment]
Hey @rodchen-king, thanks for reporting this issue! Sorry, it's a bit hard for us to debug this without seeing code and getting a bit more information from you.

Could you please attach a crash dump to help us get more information? You can collect them by adding the following snippet to your main process code, before app.whenReady:

```
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```
Then reproduce the crash, zip up the crash dumps directory and attach it here.

If you can pretty consistently repro this (it looks like you're using Electron Quick Start), would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? That would ensure everyone's looking at the same issue.

I'm adding the blocked/need-info label for this reason. After you have the crash dump and/or make a test case, please link to it in a followup comment.

Thanks so much!

**Comment by Joursion** [comment]
same issue in electron@20,  and rollback electron@12 worked for me.
