### ISSUE TITLE
[Bug]: securityScopedBookmarks is not working for a new created file

### ISSUE THREAD

**Issue by MatteoTasinato** [electron/electron#32544]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.1 (21C52)

### What arch are you using?

x64

### Expected Behavior

Working on a MAS application.

pick a file using `dialog.showSaveDialog` and `securityScopedBookmarks = true`
At the next application start, I'm automatically reading this file using `startAccessingSecurityScopedResource` and the `bookmark`

### Actual Behavior

If the `showSaveDialog` picks file was existing then EVERYTHING WORKS

If the `showSaveDialog` picks a not existing file the method is correctly creating a new empty file at the path (correct) but when I m opening the app I m getting this error in console:

`Error: Error invoking remote method 'read-novel': Error: bookmarkDataIsStale - try recreating the bookmark`

### Additional Information

I want to repeat that picking an existing file everything works well.

From my point of view, it's like if `dialog.showSaveDialog` is correctly returning a `scope bookmark` but this is referring a something else.

This is the reason why I think is a bug, probably related with the creation of the fresh file

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by MatteoTasinato** [comment]
thanks codebyter for your answer.

I'm trying with Electron Fiddle but it's not possibly to replicate the problem on it cause the securityScopedBookmarks are created just on a compiled MAS (sandbox) application.

In case could help I can prepare a small compiled build runnable on your mac and attach the gitlab source code.

let me  know how I can you and the team, thanks

**Comment by MatteoTasinato** [comment]
In order to help you to investigate the error, I prepared a small application and two short videos.

The application is very simple and has just two buttons:
1. save allows you to pick a filesystem path and creates the bookmark
2. load uses the bookmark and try to read the file

As you can see in the video if you try to reopen a fresh file created using the `dialog.openSave` it will fail to show the console error.

https://user-images.githubusercontent.com/25204538/150615748-d685edec-d2d7-4c99-92ab-37d8f25b314b.mov
https://user-images.githubusercontent.com/25204538/150615741-f67d98d0-c04f-45e2-9220-ae54455b73ff.mov

I'm posting here just the three methods involved, to replicate it you need to run a MAS compiled application

App
```
export const App = () => (<div>
        <button className='m-8' onClick={() => readFile()}>LOAD</button>
        <button className='m-8' onClick={() => selectPath()}>SAVE</button>
    </div>)
```

Render process
```
export const selectPath = async () => {
    const [filePath, bookmark] = await ipcRenderer.invoke('pick-path',)
    console.log({ filePath })
    console.log({ bookmark })

    return filePath
}
export const readFile = async () => {
    const path = getAppSettings('path')
    const bookmark = getAppSettings('security-scoped-bookmark')

    console.log({ path })
    console.log({ bookmark })

    const response = await ipcRenderer.invoke('read-path', path, bookmark)
    console.log(JSON.stringify(response))

    return null
}
```

**Main Process**
```
    ipcMain.handle('pick-path', async () => {
        const { filePath, bookmark } = await dialog.showSaveDialog({ securityScopedBookmarks: true })

        setAppSettings('path', filePath)
        if (bookmark) { setAppSettings('security-scoped-bookmark', bookmark) }

        return [filePath, bookmark]
    })

    ipcMain.handle('read-path', (_event, projectPath: string, bookmark: string) => {
        let response = null
        let stopAccessingSecurityScopedResource = app.startAccessingSecurityScopedResource(bookmark)

        try {
            novel = require('fs').readFileSync(projectPath)
        } catch (err) {
            return err
        }

        stopAccessingSecurityScopedResource()
        return response
    })
```

**Comment by MatteoTasinato** [comment]
hey, there is anyone here?
