### ISSUE TITLE
[Bug]: Changing the title of the DevTools window doesn't work

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#32545]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.3

### What operating system are you using?

macOS

### Operating System Version

Monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

N/A

### Expected Behavior

The following line of code should be able to change the title of the DevTools window, I think:

```js
window.webContents.devToolsWebContents.executeJavaScript ( 'document.title = "New title...?"' );
```

But nothing happens. 

I can change the title of a regular Chrome DevTools window by opening the DevTools for that and executing that code, so I'd expect it to work for Electron too.

Moreover when I retrieve the title of the window I get "DevTools", while in reality the title is something like "Developer Tools - http://etc.", so the title of devtools windows inside Electron seems to be configured from elsewhere.

### Actual Behavior

Nothing of interest happens.

### Testcase Gist URL

https://gist.github.com/fabiospampinato/0f65253043ff55a695d6d2d5a26e9f3d

**Comment by fabiospampinato** [comment]
This doesn't work either:

```
window.webContents.devToolsWebContents.executeJavaScript ( 'document.querySelector ( "title" ).textContent = "asd"' );
```

**Comment by flyyuan** [comment]
market

**Comment by dorelm** [comment]
what worked for me is setting the devtools window title at a delay after creation -
 
let newDevToolsWindow = new BrowserWindow();
window.webContents.setDevToolsWebContents(newDevToolsWindow.webContents);
window.webContents.openDevTools({ mode: "detach" });

setTimeout(() => {
  newDevToolsWindow.setTitle("DevTools Title");
}, 3000);

**Comment by fabiospampinato** [comment]
It'd be nice to get a workaround that just works without downsides.

**Comment by Elendiar** [comment]
It would be nice. I have few devtools windows in dev, for main renderer, and 2 for hidden windows.

**Comment by fabiospampinato** [comment]
It'd still like this become easier to do.

**Comment by klossner** [comment]
This is still a problem in the current version, 23.1.3.
I'm working around it with the settimeout hack suggested by dorelm.

**Comment by jenniferteaa** [comment]
Hello!
I would like to work on this, Kindly let me know if i can get started

**Comment by flyyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
