### ISSUE TITLE
[Feature Request]: Possible RISC-V Support

### ISSUE THREAD

**Issue by XieJiSS** [electron/electron#32551]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Since the release of Electron v16.0.0, the underlying V8 version has come to 9.6, with Node.js 16.9.1. V8 has started to support RISC-V architecture since 9.0, and Node.js also starts to support RISC-V target in `v16.x` and `v17.x` releases.

Currently, the compilation process of Electron.js targeting `riscv64gc` fails early with the output `UNKNOWN Machine architecture: riscv64`.

### Proposed Solution

Is there any plan for Electron.js to support RISC-V (or specifically, `riscv64`) architecture? I can confirm that Node.js 16.13.1 (applying PR https://github.com/nodejs/node/pull/41566) can build on `riscv64gc` and pass all tests.

Here at PLCT Lab, we're already working with V8 to support the RISC-V arch. We can provide ssh access to SiFive Unmatched boards (run on `riscv64gc` cores), as well as prebuilt `riscv-gnu-toolchain` for `x86` cross-compiling & QEMU emulation.

> Note that for Node.js v16.13.1 (patch applied), there are still a few test cases that will fail in QEMU environment, due to the incompatiblility of QEMU itself. I can confirm that all test cases can pass on real `riscv64gc` boards.

### Alternatives Considered

We're currently providing CI for Node.js and V8 (see: https://ci.rvperf.org/). If you find this helpful, we can provide help with creating a build job for Electron.js on the CI.

**Comment by miniak** [comment]
@XieJiSS Chromium needs to support this as well

**Comment by nornagon** [comment]
This is beyond the scope of the Electron project until such a time as Chromium supports RISC-V.

**Comment by XieJiSS** [comment]
@nornagon @miniak AFAIK, Chromium support for RISC-V is currently done by openSUSE developer Andreas Schwab, see https://build.opensuse.org/repositories/openSUSE:Factory:RISCV/chromium .

**Comment by yingmanwumen** [comment]
RISC-V support is really needed, could you consider it again, please?

**Comment by ryao** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1443443

Things appear to be changing in upstream chromium. They have merged a RISC-v target and have a tracker bug for additional issues.

**Comment by kxxt** [comment]
I managed to get electron 22 and Code OSS running on Arch linux riscv64(without sandbox). https://github.com/felixonmars/archriscv-packages/pull/2806 

Could riscv64 support be considered?

Here are the test logs. I have to apply the following hack to disable the sandbox, which might caused some tests to fail.

Replace out/Release/electron with:

```bash
#!/bin/bash

exec /home/kxxt/electron22/src/chromium-mirror/out/Release/electron-real --no-sandbox $@
```

tests 2109
pass 2076
fail 33

Full test log is here: https://bin.garudalinux.org/?6aa76271955fc226#DUEdA4djE4Aqak3Kfzruo5gc8nyVSniBkC7B6vTL19rG

**Comment by XieJiSS** [comment]
FYI: unstable third-party riscv64 support can be found in https://github.com/riscv-forks/electron with 28-x-y branch buildable.

**Comment by kxxt** [comment]
I am starting to publish electron riscv64 unofficial releases for electron 28 and 29 at https://github.com/riscv-forks/electron-riscv-releases/releases
