### ISSUE TITLE
[Bug]: if BrowserWindow set transparent true，setOpacity will cause the page to freeze when the computer does not have a discrete graphics card

### ISSUE THREAD

**Issue by CahierX** [electron/electron#32555]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.1

### What operating system are you using?

Windows

### Operating System Version

windows 10 pro 20H2

### What arch are you using?

x64

### Expected Behavior

 setOpacity should work fine

### Actual Behavior

setOpacity not available working properly

### Testcase Gist URL

https://gist.github.com/fd1080b1e11b06980d07dcd21daa8d63

**Comment by CahierX** [comment]
After four seconds, the input cannot input and the page is stuck

Uploading 屏幕录制2022-01-21 上午9.57.29.mov…

**Comment by VerteDinde** [comment]
Hey @CahierX, thanks for reporting this issue! I wasn't able to reproduce this issue on Windows 10 without a discrete graphics card. Could you share your graphics card information, and we can see if we can track this down?

**Comment by smartguy1196** [comment]
@VerteDinde I'd also ask for processor model, if it is onboard/integrated graphics

**Comment by CahierX** [comment]
> 嘿@CahierX，感谢您报告此问题！如果没有独立显卡，我无法在 Windows 10 上重现此问题。能否分享一下你的显卡信息，我们看看能不能查到？

I can reproduce the problem on both computers, both using the **Microsoft Remote Display Adapter**;
this one I disabled Intel(R) HD Graphics 4600 and NVIDIA Geforce GTX 9600M using **Microsoft Remote Display Adapter**;
![image](https://user-images.githubusercontent.com/31394482/153108615-a904195d-1b04-4de3-930a-17e3cd796153.png)
another one
![image](https://user-images.githubusercontent.com/31394482/153108624-02b69b8f-ecc7-4a3f-a5de-d4e9210c58de.png)

**Comment by smartguy1196** [comment]
Wait a minute. In the first one you disable the Intel on board and the GPU?

The Microsoft remote adapter is for Remote Desktop. Are you aren't accessing the machine via RDP?

How did you do that?

**Comment by CahierX** [comment]
> Wait a minute. In the first one you disable the Intel on board and the GPU?
> 
> The Microsoft remote adapter is for Remote Desktop. Are you sure you aren't accessing the machine via RDP?
> 
> RDP will have an effect on rendering.
> 
> How did you do that?
> 
> EMERGENT EDIT: FOR CLARITY, DO NOT DISABLE THOSE LAST 2. THOSE ARE NOT GRAPHICS CARDS. _**PLEASE LEAVE THEM ALONE.**_ THOSE ARE YOUR CPU DRIVERS

I use RDP to control my computer, I tried not disabling the other two drivers, and the problem will not reproduce, so I can be sure that there is no other display driver when using RDP.

**Comment by smartguy1196** [comment]
My understanding of GPU drivers might be limited, but I think this is a limitation with RDP. I don't think the RDP adapter driver is designed for that kind of usage. I will take some time to look into this.

Also out of curiosity, why are you disabling the integrated graphics driver to begin with? Is that not unnecessary?

**Comment by smartguy1196** [comment]
So this kind of issue _apppears_ to be attached to running RDP headlessly. Here's a [similar problem with NoMachine](https://forums.nomachine.com/topic/transparent-windows-on-headless-host). While this particular bug isn't like yours, many other headless RDP bugs do exist.

I'll continue looking into this to see what else I can find, but I might be limited by the fact that I don't have a spare Windows Machine to run tests on.

I'll add steps later for someone to pick up my work, if I run into a wall.

**Comment by CahierX** [comment]
> My understanding of GPU drivers might be limited, but I think this is a limitation with RDP. I don't think the RDP adapter driver is designed for that kind of usage. I will take some time to look into this.
> 
> Also out of curiosity, why are you disabling the integrated graphics driver to begin with? Is that not unnecessary?
> 
> What is your intended use case?
> 
> EDIT: by last 2, I meant the devices in your last 2 images. Those are the CPU drivers I was talking about

The bug I found while debugging the program remotely on the server. 
After a little troubleshooting, I finally found that this bug was triggered when there was no integrated graphics driver and only the RDP driver.
So I tried to disable other display drivers on my PC. In order to reproduce this bug, the final program reproduced

**Comment by CahierX** [comment]
> 
I looked at this forum and he had the same problem as mine  [similar problem with NoMachine].(https://forums.nomachine.com/topic/transparent-windows-on-headless-host)

**Even though the apps are showing as black or white screen I can still see that buttons are clickable.  For example, I estimated where the “Play” button is for Spotify window and clicked around that general area and the music will start playing even though the app itself is transparent. I’ve attached screenshot to show these scenarios:**

This is also my problem.

**Comment by smartguy1196** [comment]
I unfortunately can no longer provide help, as I do not own any retail keys for Windows to setup a VM and validate my theory. 

If someone wants to pick up where I left off:

- [ ] Get a Windows VM up and running (recommend using retail keys for VMs, because otherwise if you accidentally delete the VM, you lose the product key)
- [ ] Install, config, and setup RDP.
- [ ] Disable integrated and hardware GPU drivers
- [ ] Reproduce issue in Electron
- [ ] Also recommend testing other transparent software to ensure it isn't just an issue with Electron/Chrome.

However, I am like 95% certain this is an issue with RDP and not Electron/Chrome. If that is true, there isn't a fix this as RDP's driver appears to be closed source with no API...

One thing you can do is to ensure that you have dummy plugs setup for keyboard, mouse, and video plugged in. Most remote services (like RDP), don't like it when you don't have these peripherals plugged in. [Chrome Remote Desktop has an issue where it doesn't provide a mouse pointer if there is no hardware mouse plugged in](https://superuser.com/questions/962422/chrome-remote-desktop-with-windows-10-headless-nas-no-physical-mouse-attached)

Alternatively, you can also take advantage of [your dedicated GPU by **using any of _these answers_ as workarounds to your first use case**](https://superuser.com/a/1657683/964239). However, I am pretty sure that all of these solutions require a windows server license key.

**Comment by smartguy1196** [comment]
@Seraphli the electron dev team will need more diagnostic info. A screenshot of device manager and a repro-gist would be necessary. Also provide status of each graphics driver. The issue will only be like OP's if the GPU drivers are disabled. If any of your GPU drivers are disabled, provide your monitor-plug configuration (are they plugged in directly to a hardware GPU or are they connected to the motherboard). I would also add more data about your hardware build. CPU is important here.

**Comment by Seraphli** [comment]
@smartguy1196 This issue gives me inspiration. I finally find the real problem. I paste the gist here.

https://gist.github.com/Seraphli/dd746ead586cc4199fc249701cfadc87

In my situation, after I add the `app.disableHardwareAcceleration();`, the page freeze problem appeared.
Remove that line, everything works fine. I use a website to test the issue. You can see after setOpacity, the banner gif freezes.

System info
```
Processor	AMD Ryzen 9 3900X 12-Core Processor               4.00 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Enterprise LTSC
Version	21H2
Installed on	‎2/‎13/‎2022
OS build	19044.1586
```

**Comment by smartguy1196** [comment]
@CahierX does Seraphli's solution apply to you?

**Comment by CahierX** [comment]
> app.disableHardwareAcceleration();

This doesn't work for me, and my demo didn't add app.disableHardwareAcceleration().

I tried adding disableHardwareAcceleration and removing it in the demo and it didn't work
