### ISSUE TITLE
[Feature Request]: Add partitionName attribute to Session class. 

### ISSUE THREAD

**Issue by pnegahdar** [electron/electron#32557]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When accessing a `Session` there is no great way to get the partition name. This is useful when a message passes you the `wc` and you want to get the matching session without keeping references to the session around. 

### Proposed Solution

Add a `session.partitionName` attribute to the `Session` class. 

### Alternatives Considered

You can keep track of sessions you create on creation and create an in memory mapping of partitionNames to sessions you know about.

**Comment by nornagon** [comment]
Not an unreasonable request, but the specific use-case you mentioned is addressed by [`webContents.session`](https://www.electronjs.org/docs/latest/api/web-contents#contentssession-readonly) instance property.

**Comment by codebytere** [comment]
Closing as this is addressable by existing means for the requested use case.
