### ISSUE TITLE
[Bug]: Screen recording software can cause the UI of Electron-based programs to go blank.

### ISSUE THREAD

**Issue by YamatoRyou** [electron/electron#32584]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.5.2 (as Element)

### What operating system are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

x64

### Expected Behavior

n/a

### Actual Behavior

When using Mirilis Action! for screen recording, some Electron-based desktop software, such as:
Delta Chat 1.24.x for Windows
Element for 1.9.x for Windows

Their UI sometimes becomes blank. Only restarting the above program can restore it at this point.
From what I've observed, currently the interface only has a chance to go blank when opening the window from the tray icon.
The UI occasionally flickers slightly if the screen is recorded with the window save open.
This only seems to happen: when Mirilis Action! is launched for the first time since the computer was turned on.
After reproducing it a few times it doesn't seem to happen anymore unless the computer is restarted.

### Additional Information

Related issue:
https://github.com/deltachat/deltachat-desktop/issues/2426

Mirilis Action! Homepage:
https://mirillis.com/en/products/action.html

**Comment by easyWebDev-yt** [comment]
##big

**Comment by zcbenz** [comment]
Thanks for reporting this, but I'm afraid this is not something we can fix on our side, the screen recorder is a total black box to us so we don't know how it works and whether it is a bug in Electron at all. I'm closing this as won't fix.
