### ISSUE TITLE
Av1 video codec support

### ISSUE THREAD

**Issue by rexn8r** [electron/electron#32587]
Does chromium bundled with electron support Av1 video codec which is royalty free?

Thanks
Rex

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by rexn8r** [comment]
The problem electron team is no one answers questions and how tos? And points to community link where you can either place bugs or feature requests.

This is the second time I am left without any help on electron forum and no one answers on discord as well.

Very disappointed and left with no choice but to scrap the plan to develop something with electron
