### ISSUE TITLE
[Bug]: `requestSingleInstanceLock`'s TypeScript definition is incorrect

### ISSUE THREAD

**Issue by ocavue** [electron/electron#32582]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

macOS

### Operating System Version

N/A

### What arch are you using?

x64

### Expected Behavior

According to the documents, `requestSingleInstanceLock` should accept an optional argument `additionalData`. 

### Actual Behavior

The TypeScript definition doesn't have this argument.

![image](https://user-images.githubusercontent.com/24715727/150618850-f9390702-54a9-49cf-b3b4-7f371ea3aeb1.png)

**Comment by Vagnerweb21** [comment]
``<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>HTML</title>
  
  
  

  
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <td><a link href=" " </a>
    <img src="/storage/emulated/0/Download/HTML_free-file (2).png 
  " alt="" width="104" height="142"></td><td><a link href=" " </a>
    <img src="/storage/emulated/0/Download/JAVA_free-file (2).png
  " alt="" width="104" height="142"></td><td><a link href=" " </a>
    <img src="/storage/emulated/0/Download/CSS_free-file (4).png
  " alt="" width="104" height="142"></td>
  
  <script src="main.js"></script>
</body>
</html>
<!DOCTYPE html> 

<html> 

<head> 

    <title>POWER CODING</title> 

    <style> 

        body{ 

            margin:10px; 

        } 

        .header{ 

                padding: 10px; 

                background-color:#455e64; 

                text-align: center; 

               } 

          .header h2{ 

            color: White; } 

              /*===============[Nav CSS]==========*/ 

              .nav{ 

                background-color:#243238; 

                padding: 5px; 

                } 

              

              .nav li{ 

              list-style: none; 

              display: inline-block; 

              padding: 8px; 

               } 

           .nav a{ 

            color: #fff; 

           } 

            

          .nav ul li a:hover{ 

            text-decoration: none; 

            color: #7fffd4; 

           } 

              .lside{ 

                 float: left; 

               width:100%; 

               min-height: 440px; 

               background-color: #f0f8ff; 

               text-align: center; 

              } 

           .rside 

           { 

            text-align: center; 

            float: right; 

            width: 100%; 

              min-height: 440px; 

             background-color:  #c1cdcd; 

           } 

           .footer{ 

             height: 44px; 

                background-color:#455e64;  

            text-align: center;  

            padding-top: 10px;} 

 

            .footer p{ 

                color:  #8fbc8f; 

            } 

 

    </style> 

</head> 

<body> 

<div> 

    <div class="header"> 

      <h2>POWER CODING</h2> 

    </div> 

             

        <div class="nav"> 

            <ul> 

                <li><a href="#">HTML</a></li> 

                <li><a href="#">CSS</a></li> 

                <li><a href="#">JAVA</a></li> 

                <li><a href="#">EDITOR</a></li> 

                <li style="float: right;"><a href="#">CURSOS ONLINE</a></li> 

                <li style="float: right;"><a href="#">SIGN-UP</a></li> 

            </ul> 

        </div> 

      

       

        <div style="height:440px"> 

            <div class="lside">    

                <p>  <textarea cols="65" rows="15">    
<!DOCTYPE html> <html> <body> <h3>An Ordered List Example</h3> <ol> <li>Sida</li> <li>Robert</li> <li>gabriel</li> </ol> <h3>Letters list Example</h3> <ol type="A"> <li>Margarethy</li> <li>junior</li> <li>Vagner</li> </ol> <h3>list Example</h3> <ol type="a"> <li>Ane</li> <li>Lurdes</li> <li>Ramon</li> </ol> <h3>Roman numbers Example</h3> <ol type="I"> <li>Damiana</li> <li>Roberta</li> <li>Benedito</li> </ol> </body> </html>  
               
   </textarea> </p> 

            </div> 

         

            <div class="rside">  
<!DOCTYPE html> <html> <body> <h3>An Ordered List Example</h3> <ol> <li>Sida</li> <li>Robert</li> <li>gabriel</li> </ol> <h3>Letters list Example</h3> <ol type="A"> <li>Margarethy</li> <li>junior</li> <li>Vagner</li> </ol> <h3>list Example</h3> <ol type="a"> <li>Ane</li> <li>Lurdes</li> <li>Ramon</li> </ol> <h3>Roman numbers Example</h3> <ol type="I"> <li>Damiana</li> <li>Roberta</li> <li>Benedito</li> </ol> </body> </html>  
               

               
 </p><div class="footer"></div><td> <a link href=" "</a>
<img src="/storage/emulated/0/HtmlTutorial/JavaScript/left_arrow.png
" alt="left" width="74" height="72"> </td> 

           <td> <a link href=" "</a>
<img src=" /storage/emulated/0/HtmlTutorial/JavaScript/right_arrow.png
" alt="height " width="74" height="72"></td>

    <p>    </div> 

       

       <div class="footer"> 

        <p>©<strong>Copyright &#9824;  vagnerweb21@gmail.com</strong></p> 

    </div>     

 </div> 

</body> 

</html>
