### ISSUE TITLE
[Bug]: The version of electron in package.json is 16.0.6,  and the actual installed version is 16.0.7

### ISSUE THREAD

**Issue by Abbyzhoum** [electron/electron#32589]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows 11  version 22000

### What arch are you using?

x64

### Last Known Working Electron version

16.0.7

### Expected Behavior

I hope install the 16.0.6 electron version in package.json.

### Actual Behavior

I have used npm cache clean to clear the cache, but the 16.0.7 version is still installed
When I use the 16.0.7 version of electron, I get stuck in `node install.js`, and it has been timed out and cannot be installed. When I changed Taobao's mirror source address  `https://npm.taobao.org/mirrors/electron/16.0.6/`，the mirror source did not have the 16.0.7 version of the electron mirror, so I changed the electron version in package.json to 16.0.6, deleted the dependencies and reinstalled, still version 16.0.7

### Additional Information

![01](https://user-images.githubusercontent.com/38661489/150711332-d066c24d-e6bd-4768-9e06-1b3e385836cd.png)
![02](https://user-images.githubusercontent.com/38661489/150711345-ad837b91-560c-4b0c-82af-5994293526e0.png)

**Comment by Prinzhorn** [comment]
> so I changed the electron version in package.json to 16.0.6, deleted the dependencies and reinstalled, still version 16.0.7

Did you also delete your `package-lock.json`? That's probably where the 16.0.7 still is in.

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by Abbyzhoum** [comment]
> > 所以我将package.json中的电子版本更改为16.0.6，删除了依赖项并重新安装，仍然是版本16.0.7
> 
> 你是否也删除了你的`package-lock.json`这可能是16.0.7仍然存在的地方。

Yes, I deleted the package-lock.json file, when trying to install the dependencies, it still installs 16.0.7, not the 16.0.6 version in package.json.

![detail](https://user-images.githubusercontent.com/38661489/150893317-228d9786-e5ad-476d-840a-c152f54299c6.png)
