### ISSUE TITLE
dialog.showMessageBoxSync can't work on macOS

### ISSUE THREAD

**Issue by XRenSiu** [electron/electron#32590]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

`dialog.showMessageBoxSync({ type:'warning' })` should block the process until the message box is closed, and returns the index of the clicked button.

### Actual Behavior

`dialog.showMessageBoxSync({ type:'warning' })`  CANNOT block the process and returns -1000.

### Testcase Gist URL

https://gist.github.com/XRenSiu/6b4e53ce1337c95292273090e9046d82

**Comment by codebytere** [comment]
@XRenSiu have you tried this on Big Sur too? I can't repro it on Big Sur and don't have a 12.0 device around to test right now. If we could potentially verify whether this is specific to a version of macOS that would be very helpful.

**Comment by XRenSiu** [comment]
> @XRenSiu have you tried this on Big Sur too? I can't repro it on Big Sur and don't have a 12.0 device around to test right now. If we could potentially verify whether this is specific to a version of macOS that would be very helpful.

macOS 11.6.1 also has this question and returns -1000.

**Comment by zcbenz** [comment]
I can't reproduce on an Intel MacBook too, I wonder if it only happens for arm64.

**Comment by VerteDinde** [comment]
I'm not sure why, but I can reproduce this on both an ARM Macbook and an Intel Macbook, both running Monterey 12.0.1. 

Interestingly, I can reproduce this up to 16.0.7 and on all 17 alphas and betas until 17.0.0-beta.3. Beginning on 17.0.0-beta.3, the dialog box works as expected: https://github.com/electron/electron/compare/v17.0.0-beta.2...v17.0.0-beta.3

@XRenSiu Can you confirm that the behavior is fixed for you when running 17.0.0-beta.3 or higher? I can dig into the commits there and see what fixed it, we may have inherited a bug fix from Chromium.

**Comment by codebytere** [comment]
@VerteDinde confirmed for me as well, i can reproduce on an Intel Macbook running Monterey 12.0.1 until `v17.0.0-beta.3`

**Comment by XRenSiu** [comment]
Electron v17.0.0 works for me on both an ARM MacBook and an Intel MacBook

**Comment by codebytere** [comment]
Closing as v17.0.0 is no longer supported and this now works.
