### ISSUE TITLE
[Bug]: minWidth no longer working

### ISSUE THREAD

**Issue by t57ser** [electron/electron#32608]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0-beta.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.985

### What arch are you using?

x64

### Last Known Working Electron version

16

### Expected Behavior

Setting minWidth for a browserWindow during creation should work

### Actual Behavior

minWidth does not work (minHeight does)

```
const { app, BrowserWindow } = require("electron");

function init() {
	let browserWindow1 = new BrowserWindow({
		show: true,
		minWidth: 500,
		minHeight: 500,
	});
}

app.on("ready", () => {
	init();
});
```

Note: It works when using browserWindow1.setMinimumSize(500, 500);

**Comment by codebytere** [comment]
Looks like this regressed in https://github.com/electron/electron/compare/v17.0.0-alpha.3...v17.0.0-alpha.4 and within that, https://github.com/electron/electron/commit/b6f8a1686fcaa758a93b7d37b695e38bd5111eae seems like the likely culprit

**Comment by CezaryKulakowski** [comment]
I can confirm that it's definitely not caused by https://github.com/electron/electron/commit/b6f8a1686fcaa758a93b7d37b695e38bd5111eae. My change modifies file `ui/views/win/hwnd_message_handler.cc` which is being compiled only on Windows and the regression with `minWidth` can be observed also on macOS.

**Comment by nornagon** [comment]
lol found it, it's this:

![image](https://user-images.githubusercontent.com/172800/151062401-1b1e3c0c-984e-4ac7-ba39-47c7472190b3.png)

`||` short-circuits, `|` does not.
