### ISSUE TITLE
Make is possible to check whether file is downloaded via dragging in "will-download" event

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#32601]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Windows

### Operating System Version

Version 10.0.19044.1469

### What arch are you using?

x64

### Expected Behavior

Maybe in the "will-download" event we should have more information whether it is a regular download or triggered by dragging.

### Actual Behavior

The file is saved to the dragged folder and also the will-download is fired.

### Testcase Gist URL

https://gist.github.com/e857a13eaaab3d58fe7b01fe469a508a

**Comment by zcbenz** [comment]
I'm marking this as a feature request since we should not change existing behavior, and I think it would be nice to be able to distinguish dragging from normal downloads.

**Comment by codebytere** [comment]
Unfortunately at this point it's still not possible to distinguish between the two in Chromium, and we're not likely to consider a solution that requires patching. As a result, I'm going to close this out for now as a `wontfix`. Should something change, happy to reconsider!
