### ISSUE TITLE
[Feature Request]: Update TitleBarOverlay Color

### ISSUE THREAD

**Issue by SquitchYT** [electron/electron#32615]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I need to update the color of titleBarOverlay on Windows

### Proposed Solution

have a function to update color of title bar overlay

### Alternatives Considered

Say that is just impossible in the docs

**Comment by theolivenbaum** [comment]
Any updates on this? 
We're also interested in a way to change the color after the window is created, for the same reasons as [this question from StackOverflow](https://stackoverflow.com/questions/69190603/electron-change-titlebaroverlay-color-and-titlebaroverlay-symbolcolor-at-runtim)

**Comment by byzhangkui** [comment]
Our app can change backgroud with different colors or imges, so we need update the color of titleBarOverlay on Windows too.

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/33066
