### ISSUE TITLE
Add support for showing hidden files in dialog

### ISSUE THREAD

**Issue by luin** [electron/electron#3262]
There's no option to show the hidden files in the [dialog.showOpenDialog](https://github.com/atom/electron/blob/master/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options-callback) currently. Here is an example:

![image](https://cloud.githubusercontent.com/assets/635902/10814931/dffb1758-7e63-11e5-98f1-5ff1a56fd596.png)

BTW, is it possible to add a description in the dialog (just like the text "Choose a custom SSH key..." in the above image)? Tried the `title` option but it seems not showing at all (OS X).

**Comment by manovotny** [comment]
Just curious... Does OS X's built in hotkey command, `⌘ CMD` + `⇧ SHIFT` + `.`, show the hidden files?

For reference: http://apple.stackexchange.com/questions/186376/hotkey-to-show-hidden-files-and-folders-in-file-open-dialog

**Comment by davej** [comment]
> BTW, is it possible to add a description in the dialog (just like the text "Choose a custom SSH key..." in the above image)? Tried the title option but it seems not showing at all (OS X).

The title should show in the titlebar if the dialog is not attached to a `browserWindow`.

**Comment by bengotow** [comment]
I think the behavior of the `title` field is correct. Mac OS X exposes a native API for adding custom views to the bottom portion of the open/save dialogs, but I doubt Electron can support that in a generic way.

@manovotny :  `command-shift-.` does work to show hidden files.

**Comment by jgrosso** [comment]
How about `dialog.showSaveDialog`?
