### ISSUE TITLE
[Bug]: LINUX sandbox browserview new Date().getTimezoneOffset() always 0

### ISSUE THREAD

**Issue by sbtuoersuo** [electron/electron#32629]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.5.0

### What operating system are you using?

Other Linux

### Operating System Version

linux

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

 LINUX sandbox browserview new Date().getTimezoneOffset()

### Actual Behavior

 LINUX sandbox browserview new Date().getTimezoneOffset() always 0

**Comment by nornagon** [comment]
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).
