### ISSUE TITLE
[Feature Request]: Ignore X-Frame-Options

### ISSUE THREAD

**Issue by wslp12** [electron/electron#32630]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

![image](https://user-images.githubusercontent.com/26638889/151134204-35657cab-47c7-468a-af39-7bb969688b55.png)

`Refused to display 'https://accounts.google.com/' in a frame because it set 'X-Frame-Options' to 'deny'.`

The cause of the above error was found, and a solution was also found.
https://github.com/electron/electron/issues/426

But when I update the Electron version to ^16.0.4 or higher, it does work,

![image](https://user-images.githubusercontent.com/26638889/151134884-c4a35da2-5e3c-4acf-a69e-ffd3bf52cefe.png)

Even if you click the login button, only the above error is output without any response.
(Refused to frame 'https://accounts.youtube.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://accounts.google.com".)

I wonder if there is a new security issue following the Electron version update.

### Proposed Solution

```
 // We set an intercept on incoming requests to disable x-frame-options
  // headers.
  win.webContents.session.webRequest.onHeadersReceived({ urls: [ "*://*/*" ] },
    (d, c)=>{
      if(d.responseHeaders['X-Frame-Options']){
        delete d.responseHeaders['X-Frame-Options'];
      } else if(d.responseHeaders['x-frame-options']) {
        delete d.responseHeaders['x-frame-options'];
      }

      c({cancel: false, responseHeaders: d.responseHeaders});
    }
  );
```

### Alternatives Considered

I think a new solution to the Electron version update has been suggested, so where can I find it?

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

It looks like you might need to tweak the `Content-Security-Policy` headers as well as/instead of the `x-frame-options` header.

I hope this helps!
