### ISSUE TITLE
[Bug]: On Windows, Transparent Windows Don't Fire "maximize"/"unmaximize" Events

### ISSUE THREAD

**Issue by dsanders11** [electron/electron#32633]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0-beta.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

A transparent window should fire "maximize" and "unmaximize" events when maximized and unmaximized.

### Actual Behavior

Transparent windows do not fire "maximize" and "unmaximize" events.

### Testcase Gist URL

https://gist.github.com/1a157df991fe3e9bf34c9c2d50e1acf1

### Additional Information

This is a continuation of #23275, and #12854 before that, so it's a long-standing issue. Those issues have aged out, so opening this one to continue tracking the issue. I didn't see any open issues covering it.

`BrowserWindow.isMaximized()` works correctly for maximized transparent windows since #26586, so it's just the events which aren't firing.

**Comment by Ryan-Ashton** [comment]
Same issue for me.

**Comment by codebytere** [comment]
@dsanders11 see: https://github.com/electron/electron/pull/28207

**Comment by codebytere** [comment]
@dsanders11 see: https://github.com/electron/electron/pull/28207

**Comment by dsanders11** [comment]
@theolivenbaum, it's released in 17.0.0, but hasn't been released on older versions yet.
