### ISSUE TITLE
[Bug]: signalR  AbortController is not defined

### ISSUE THREAD

**Issue by bbhxwl** [electron/electron#32639]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v1.4.13

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Expected Behavior

Use signalr for communication.

### Actual Behavior

signalr.min.js:16 Uncaught ReferenceError: AbortController is not defined
FetchHttpClient @ signalr.min.js:16DefaultHttpClient 
@ signalr.min.js:16HttpConnection 
@ signalr.min.js:16HubConnectionBuilder.build 
@ signalr.min.js:16(anonymous function) 
@ leadspeech.html:57

**Comment by miniak** [comment]
v1.4.13 is not supported for a very long time already.
