### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Notkeltan** [electron/electron#32636]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi, While working in Obsidian (An Electron Application) It would be incredibly helpful to be able to work on separate monitors on the one Vault (Pretty much a wiki app). Though to do this I have to put my notes at risk of corruption or loss with janky work arounds.
From what I understand they are unable to implement a floating windows feature due to Electron restraints. In other applications floating windows have been a mainstay of my interaction and workflow.
Though, I'm too in love with Obsidian to ever leave. So for now I'll work with what I've got.

### Proposed Solution

As mentioned previously floating windows would provide exactly the solution that is needed. 

### Alternatives Considered

Since this is a feature request I can not think of any alternatives. Though I have tried to think. All other solutions I have are suboptimal and put files at risk.

### Additional Information

I'm not very knowledgeable in the programing world. I don't want to come off as one of those guys thats like "Hey you stink code monkey! Now go make me hal 900."

Thank you for the work you do and providing resources for free. You truly are paving the future. And the software that uses Electron is shaping our world.

Thank you x1000

**Comment by nornagon** [comment]
Not sure what the issue is that Obsidian is having, Electron definitely supports multiple windows so I don't think this is an Electron limitation.
