### ISSUE TITLE
[Bug]: Electron stuck in a loop of broken imports

### ISSUE THREAD

**Issue by Nectres** [electron/electron#32640]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.7

### What operating system are you using?

Windows

### Operating System Version

Windows 11 21H2

### What arch are you using?

x64

### Expected Behavior

Electron should import the module and run the application

### Actual Behavior

I have a dependency 'env-paths' which seems to be a ES Module.
I write my electron code in TS and when i compile, if i set the module to 'commonjs'

My `index.js` (entry point) cannot require `env-paths` and results in :  [ERR_REQUIRE_ESM] 

If i set type: "module" in my package.json and try to run, Electron cannot require my `index.js` to start the app and results again in `[ERR_REQUIRE_ESM]`

If possible, can i make Electron import a ES module?

**Comment by codebytere** [comment]
Electron does not currently support ESM.
