### ISSUE TITLE
i am not ablw to open discord bot client [Bug]: 

### ISSUE THREAD

**Issue by Hecker123s** [electron/electron#32659]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

windows 10	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz Installed RAM	8.00 GB (7.81 GB usable) 	64-bit operating system, x64-based processor 

### What arch are you using?

x64

### Last Known Working Electron version

10

### Expected Behavior

to login my bot account

### Actual Behavior

login page is blank

**Comment by miniak** [comment]
This is a Discord client issue, please report it there.
