### ISSUE TITLE
[Bug]:  node: command not found

### ISSUE THREAD

**Issue by smz8023** [electron/electron#32658]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12

### What operating system are you using?

macOS

### Operating System Version

12.0.1

### What arch are you using?

ia32

### Last Known Working Electron version

12

### Expected Behavior

exec(`node ${process.cwd()}/dist/server.js ${JSON.stringify(arg)}`,{});

### Actual Behavior

node: command not found

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
