### ISSUE TITLE
[Bug]: Browser always crashed when use 3rd modules.

### ISSUE THREAD

**Issue by dohooo** [electron/electron#32662]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.8

### What operating system are you using?

macOS

### Operating System Version

Mac OS 12.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

16.0.8

### Expected Behavior

`node-usb` packages does not crash in clear Electron.

### Actual Behavior

When i call functions that regist by contextBridge.exposeInMainWorld, The WebView always crashed.

The functions include `node-usb`.

### Testcase Gist URL

https://gist.github.com/dohooo/a82149deed15c3e94c71aa8c0ac1c264

### Additional Information

This sounds a lot like a `node-usb` Packages problem, but my gut tells me it's not normal for Electron because the error message is too subtle.

**Comment by nornagon** [comment]
Please attach a crash dump. You can collect them by adding the following snippet to your main process code, before app.whenReady:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by dohooo** [comment]
@nornagon 
[crashes.zip](https://github.com/electron/electron/files/7962531/crashes.zip)

**Comment by dohooo** [comment]
Since #62 issue has been solved, Now you can upgrade to the following latest version,
```
"electron": "^16.0.8",
"usb": "^2.1.0"
```

**Comment by codebytere** [comment]
<details>
<summary>Stacktrace</summary> 

```
#
# Fatal error in ../../v8/src/objects/tagged-impl.h, line 90
# Debug check failed: kCanBeWeak || (!IsSmi() == HAS_STRONG_HEAP_OBJECT_TAG(ptr_)).
#
#
#
#FailureMessage Object: 0x7ffee0dd8e30
0   Electron Framework                  0x0000000122e0bd89 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x0000000122d213a3 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework                  0x0000000124aaec9d gin::(anonymous namespace)::PrintStackTrace() + 45
3   Electron Framework                  0x00000001244e6f36 V8_Fatal(char const*, int, char const*, ...) + 326
4   Electron Framework                  0x00000001244e69d5 v8::base::(anonymous namespace)::DefaultDcheckHandler(char const*, int, char const*) + 21
5   Electron Framework                  0x0000000120117a2f v8::internal::Object::VerifyApiCallResultType() + 383
6   Electron Framework                  0x000000012011782e v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 974
7   Electron Framework                  0x0000000120115734 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 1748
8   Electron Framework                  0x0000000120113393 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 483
9   Electron Framework                  0x0000000120112f1d v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) + 109
10  ???                                 0x0000003d07edeab8 0x0 + 262126037688
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
```

</details>

**Comment by dohooo** [comment]
So is there any way I can move this forward?  I don't think I can solve this "bug" by myself.

**Comment by codebytere** [comment]
Uh, ok so - I did some very quick spelunking and found that the line causing the crash is [this one](https://github.com/node-usb/node-usb/blob/master/src/node_usb.cc#L124). Not sure why the handlescope would kill it but i would try reporting this upstream.

**Comment by dohooo** [comment]
Oh my god, thank you very much for your help, hope to see this problem solved one day, is there anything else I can do to help?
