### ISSUE TITLE
[Bug]: window reference from window.open does not have preload script executed

### ISSUE THREAD

**Issue by t57ser** [electron/electron#32661]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0-beta.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.985

### What arch are you using?

x64

### Last Known Working Electron version

14.1.1

### Expected Behavior

var win = window.open("https://www.google.com");
win.hello

value should be accessible if defined in preload script

### Actual Behavior

The value is undefined. If trying to manually access it later it will be defined, probably because the preload script is executed at a later time.

### Testcase Gist URL

https://gist.github.com/t57ser/be7947cd051cdedf1e03c31100785042

**Comment by t57ser** [comment]
Works with 14.2.3.
Does not work with 14.2.4
My guess is this caused it: https://github.com/electron/electron/pull/32325

**Comment by t57ser** [comment]
I am pretty sure that caused it, it fits the comment https://github.com/electron/electron/blob/94d4a07fa2399eb6e64fc941bc73c7d644ad559d/shell/renderer/electron_render_frame_observer.cc#L93-L95
Due to later initialization it is not available immidiately. @zcbenz

**Comment by zcbenz** [comment]
Yeah the late initialization is intended, because we have to wait for the main process to pass options otherwise there will be security issues.

So we can not really fix this bug, and adding a new config seems to be the only option. But the config would be a renderer-wide flag to ignore checks from the main process and have new windows always inherit web preferences from their parents, it introduces security problems and I don't think we can get it approved.

**Comment by t57ser** [comment]
Is this only related to https://github.com/electron/electron/blob/94d4a07fa2399eb6e64fc941bc73c7d644ad559d/shell/renderer/electron_render_frame_observer.cc#L90-L92
or are there more security concerns than nodeIntegration?
My assumption would be that security of such things should be in the hands of the developer (same as activating nodeIntegration in the first place), but I don't know all the implications of it.
Maybe a secure solution would be to have a flag that only allows instant initialization if nodeIntegration is set to false. In that case it would still not be possible to switch it for a child window but it at least allows having the instant initialization in case the parent is already secure.

I'm also in the process of trying out other possible workarounds but there doesnt seem to be anything due to its synchronous nature. The easiest thing to do would be to delay the return value of window.open in the parent but that would require a way to pause the renderer in some way. Currently this is only possible via ipcRenderer.sendSync which doesnt work if the child runs in the same domain since they will reuse the renderer and both will hang.

I'm surprised this was seen as a patch rather than a breaking change as this breaks all synchronous usage cases.
Currently it still works with about:blank but not by intention https://github.com/electron/electron/blob/94d4a07fa2399eb6e64fc941bc73c7d644ad559d/shell/renderer/electron_render_frame_observer.cc#L99-L104

**Comment by zcbenz** [comment]
Hmm a switch that only works when nodeIntegration is turned off should have no security issues, but it is still a new API that for a corner case, and I think it would receive questions on why should such API be added instead of having the app working around the corner case.

Sorry my change brought a breaking change, but it is a security issue that has to be fixed, and I couldn't find any alternative solution.

**Comment by t57ser** [comment]
Currently it is needed for the use of various 3rd party apps.
A very simple use case:
```
var win = window.open("");
win.document.write(someHTML);
win.print();
win.close();
```
Here the print is overwritten in the preload to have custom print logic.
Another use case is the interception of window.open and window.close to notify the host / have custom logic.
For example this is needed to workaround the following issue: https://github.com/electron/electron/issues/28625
There are more use cases but these are just some simple examples.

I would be happy with any workaround or hack but at the moment I can not find any way to solve this.
The printing example still works at the moment as it navigates to about:blank but I am concerned how to solve this in the future once this is no longer supported.

Another workaround I tried was using
`Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, milliseconds)` before returning the window reference.
Though this throws the following: Uncaught TypeError: Atomics.wait cannot be called in this context.
As far as I know it would not work anyway as that too would block the child process if it runs under the same renderer.
I assume this goes for any webassembly based solution as well.
I don't think that there is any way to wait until the correct window reference exists in the parent.


Reading through the chromium issue again and https://github.com/electron/electron/blob/94d4a07fa2399eb6e64fc941bc73c7d644ad559d/shell/renderer/electron_render_frame_observer.cc#L87-L89
Does this imply that the behaviour will be fixed once chromium changes the initial navigation?
See: (https://bugs.chromium.org/p/chromium/issues/detail?id=1215096)
```
The synchronous about:blank commit for window.open() is no longer
  ignored. Since this is the last case of a navigation getting ignored,
  this means we don't ignore any committed navigations anymore. This
  also means the browser-side listeners (e.g. WebContentsObserver's
  navigation related functions) will now be notified of this navigation
```

**Comment by zcbenz** [comment]
Thanks for the examples. Since the preload option is parsed in the main process, the preload scripts set by `setWindowOpenHandler` API or passed in the feature string of `window.open` are not possible to run synchronously. So with an option to retreat back to old behavior, it can only run preload scripts inherited from the parent window, and its documentation would be very long to cover all the cases, I don't think it can get enough love to get passed.

I'll see if I can work out a decent API to cover your use case.

> Does this imply that the behaviour will be fixed once chromium changes the initial navigation?

Yes I think so, but I believe Chromium would need a few refactorings to achieve it so it won't happen anytime soon.

**Comment by t57ser** [comment]
Thank you for the support. My biggest fear was the about:blank case anyway since those are the most important use cases.
If this won't break in the future but rather the behavior might get fixed instead, this is already great news.

I am aware of the preload script issue but this isn't a big problem since the preload script could check for the use case it runs in, meaning it should not be necessary to have different preload scripts for different use cases, but I understand that having a flag would cause confusion among users. Though this is already causing confusion for the about:blank case. See: https://github.com/electron/electron/issues/32136

Maybe the setWindowOpenHandler could throw a warning in case someone tries to modify properties that can not be modified at the time (like preload and nodeIntegration), since it should already be known if the navigation is going to about:blank.
Of course this behavior could also just be documented. 
I would imagine that any api or flag would then just run the same path.

In any case thanks for the help, at least there is some hope that chromium will fix this in the future.
