### ISSUE TITLE
Regression: libvk_swiftshader.so contain debug information on Linux

### ISSUE THREAD

**Issue by fxha** [electron/electron#32669]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.3.6, 16.0.8

### What operating system are you using?

Other Linux

### Operating System Version

Linux x64

### What arch are you using?

x64

### Last Known Working Electron version

15.3.4, 16.0.7

### Expected Behavior

`libvk_swiftshader.so` shouldn't contain debug information in production builds, as in the previous builds.

### Actual Behavior

`libvk_swiftshader.so` contains debug information in production builds and has a size of ~120MB (4MB before), which increase the distribution size and cost.

Edit: `chrome_crashpad_handler` also contain debug information.

**Comment by codebytere** [comment]
cc @nornagon ref. https://github.com/electron/electron/commit/71c8dd70281e385f06b2740d859393a6663d3d14

**Comment by lights0123** [comment]
`chrome_crashpad_handler` was supposed to be stripped with #32549 (backport of #32540), but that PR tries to strip a binary called `crashpad_handler` instead.

**Comment by codebytere** [comment]
@lights0123 it's only called `chrome_crashpad_handler` on macOS. On Linux it is called  `crashpad_handler`.

**Comment by deermichel** [comment]
I can confirm that everything is configured properly now; we just need to kickoff new releases.

**Comment by lights0123** [comment]
@codebytere no?

```bash
❯ wget https://github.com/electron/electron/releases/download/v17.0.0/electron-v17.0.0-linux-x64.zip
electron-v17.0.0-linux-x64.zip     100%[================================================================>]  94.77M  89.3MB/s    in 1.1s    

2022-02-03 00:42:31 (89.3 MB/s) - ‘electron-v17.0.0-linux-x64.zip’ saved [99370922/99370922]
❯ unzip electron-v17.0.0-linux-x64.zip
❯ file chrome_crashpad_handler 
chrome_crashpad_handler: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=98d3be7e8c7ac9110cb07010313260a150fed208, with debug_info, not stripped
```

It's also in the zip manifest:
https://github.com/electron/electron/blob/5513e66982d920594c491fd3eae4c0d33625c19f/script/zip_manifests/dist_zip.linux.x64.manifest#L6

> I can confirm that everything is configured properly now; we just need to kickoff new releases.

 electron-v18.0.0-alpha.1-linux-x64.zip is still affected even though it was released after your comment—was there something pushed that wasn't included in its build?
