### ISSUE TITLE
[Bug]: Cancelling print causes electron to crash

### ISSUE THREAD

**Issue by t57ser** [electron/electron#32684]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0-beta.9

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.985

### What arch are you using?

x64

### Expected Behavior

No crash should happen, print gets cancelled

### Actual Behavior

Calling window.print() and then clicking on the cancel button crashes electron

**Comment by VerteDinde** [comment]
Hey @t57ser, thanks for reporting this issue! We have a PR in flight to fix this issue: #32632

I'll close this issue once that PR is landed and backported into 17 🙇‍♀️

**Comment by siebertm** [comment]
@VerteDinde this has not yet been backported to 17, shall this be reopened? That issue is blocking a release or ours, as our customers kinda want to print stuff all the time 🤷 

Anything I can do to help / speed this up? (I dont trust my C++ enough for handling electron codebase though)
