### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by projektorius96** [electron/electron#32682]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

Windows

### Operating System Version

Windows Home 10 Windows Feature Experience Pack 120.2212.3920.0

### What arch are you using?

x64

### Last Known Working Electron version

16.0.7

### Expected Behavior

Expected dynamic import to work, however only __require works :

**preload.js**
```javascript
    contextBridge.exposeInMainWorld('myAPI', {
        __require(file){
            require(file);
        },
        __import(file){
            import(file).then(({default: defaultImport})=>{
                return defaultImport;
            }).catch((error) => 'An error occurred while loading the component dynamically');
        },
    })
```

### Actual Behavior

When `__require` for require() works fine, but using `__import` for dynamic import() DevTools gets broken with the following pop message (cited): "DevTools was disconnected from the page. Once page is reloaded, DevTools will automatically reconnect"

Worth to mention my main app process from which I upload preload.js script solely based on commonjs i.e. I do require('express') not esm import . Could it be related ? Thanks .

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by projektorius96** [comment]
Hi, sorry for taken so long, although I've experienced some buggy behaviour last days with Playwright whilst testing, actually I even even issued a potential bug https://github.com/microsoft/playwright/issues/11886 if interested . ]]


Here is a [case reproduction](https://github.com/projektorius96/electron-dynamic-import-bug) for a follow-up . Please refer to /README.md & /tests/COVERAGE.md for guidelines .

Thank you.

**Comment by projektorius96** [comment]
@ckerr Unfortunately , time and energy to get things done are scariest resources ([cited from](https://github.com/electron/electronjs.org/issues/5905), all credits to @jkleinsc) .
