### ISSUE TITLE
[Bug]: TypeError on DevTools opened

### ISSUE THREAD

**Issue by cawa-93** [electron/electron#32699]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Версія	21H2 / 25.‎06.‎2021 / 19044.1466 / Windows Feature Experience Pack 120.2212.3920.0

### What arch are you using?

x64

### Expected Behavior

There should be no mistakes in a clean start

### Actual Behavior

Every time you open the devtools, an error appears:
```
[15612:0201/142647.592:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read properties of undefined (reading 'instance')", source: devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@2bee2cb92d553708966882df183bb533ac105e7c/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (1)
```

### Testcase Gist URL

https://gist.github.com/42a79e0eb3ba26f80841ed6976b3e168

**Comment by codebytere** [comment]
Please follow this at https://github.com/electron/electron/issues/32702
