### ISSUE TITLE
[Bug]: `mainWindow.webContents.openDevTools` modes no longer work

### ISSUE THREAD

**Issue by codebytere** [electron/electron#32702]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0-beta.3

### What operating system are you using?

macOS

### Operating System Version

12.2

### What arch are you using?

x64

### Last Known Working Electron version

17.0.0-beta.2

### Expected Behavior

`mainWindow.webContents.openDevTools()` should be able to pass `{mode}` to set a specific dock position.

### Actual Behavior

`mainWindow.webContents.openDevTools()` `mode` value no longer has any effect.

To reproduce, add:

```
mainWindow.webContents.openDevTools({ mode: 'bottom' })
```

to `createWindow` in the default Fiddle. Observe that it opens on the right side instead of the bottom.

### Additional Information

Error originates [here](https://github.com/electron/electron/blob/b0f315a637b05bc445fc7e6084baa840891c1207/shell/browser/ui/inspectable_web_contents.cc#L589-L592)

This was introduced in this [roll](https://chromium.googlesource.com/chromium/src/+log/98.0.4706.0..98.0.4758.9?n=10000&pretty=full), which contained this [roll](https://chromium.googlesource.com/devtools/devtools-frontend/+log/1b5567f78aca..b6f648d8921e?n=10000) and is almost certainly a result of [this CL](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3264212) which removes legacy globals. We'll need to find an alternative way to fix this, or patch devtools to bring back the globals.

**Comment by Bartel-C8** [comment]
Same warning/error here as in #32699 , but just to note that that error even occurs when calling `mainWindow.webContents.openDevTools()` without (`mode`) arguments!

**Comment by 7ombie** [comment]
I'm having the same issue (macOS Monterey ARM), but nothing useful to add.
