### ISSUE TITLE
[Bug]: Browserview disappear after setBounds

### ISSUE THREAD

**Issue by Seraphli** [electron/electron#32733]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 LSTC 1809

### What arch are you using?

x64

### Expected Behavior

In the test case, the view should show after step two.

### Actual Behavior

In the test case, the view didn't show after step two. Call `setbounds` break the view.

### Testcase Gist URL

https://gist.github.com/Seraphli/335769afe77fc9fe2dd8e896eb9e7ab8

**Comment by codebytere** [comment]
In your repro, you've removed the browserview and then set bounds on the removed view. This is fixed by adding the view back before your final step 2 call to `setBounds`.

**Comment by codebytere** [comment]
@Seraphli anytime! let me know if you have other issues and i can try to look into them :D
