### ISSUE TITLE
[Bug]: Devtools performance source navigation broken in Electron 17.0.0

### ISSUE THREAD

**Issue by lishid** [electron/electron#32746]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2

### What arch are you using?

x64

### Last Known Working Electron version

16.0.8

### Expected Behavior

Take a performance snapshot with some amount of JS code executing. Click on a function block, and use the link in the summary tab below to navigate to the source code corresponding to that function.

Expected behavior is to have the devtools navigate from `Performance` tab to the `Sources` tab and scroll to the location where that line/col number in that file.

### Actual Behavior

Nothing happens. Devtools does not navigate from Performance to Sources.This happens regardless of whether the file has a sourcemap or not.

In addition, sourcemaps are also not respected and the raw (compiled/bundled) js file line/col is shown rather than the actual location of the mapped function position. In my case, it's showing "app.js:1:xxxxxx" rather than "sourcefile.ts:xx:yy".

Fortunately the sourcemap bug does not affect console logs, and console messages and exception traces are properly mapped.

Both issues are new since Electron 17.
Current workaround is to downgrade to 16.0.8.

**Comment by Bartel-C8** [comment]
Confirmed here as well with Electron 17 on MacOS!

**Comment by lishid** [comment]
Quick status update:
- Electron 16.0.10 still no issues.
- Electron 17.1.1 still broken.
- Electron 18.0.0-alpha.5 is also broken.

**Comment by Bartel-C8** [comment]
Still an issue in 17.2.0 . 
Actually, this is a blocker for me to upgrade Electron, as I often rely on using this feature (in development).

**Comment by lishid** [comment]
I'm seeing this issue resolved in 18.0.3. Anyone else can confirm?

**Comment by Bartel-C8** [comment]
Works for me as well in 18.2.0 . So presumably Chromium related?
Now v18 is released, the need for (bugfix in) v17 dropped for me as well.
