### ISSUE TITLE
[Bug]: cssOrigin in insertCSS seems to have no effect

### ISSUE THREAD

**Issue by porst17** [electron/electron#32748]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Mojave

### What arch are you using?

x64

### Expected Behavior

According to the docs, passing the `{cssOrigin: 'user'}` option to `insertCSS` should prevent websites from overriding the inserted CSS. E.g. if the CSS `body { background-color: red; }`  is inserted with `{cssOrigin: 'user'}` and the page has the style `body { background-color: white; }` set, the CSS with origin `user` should take precedence and the page's background color should be red, not white.

### Actual Behavior

The inserted CSS is overridden by the CSS specified by the page regardless of what's set a `cssOrigin`. In the example, the background is white, not red.

### Testcase Gist URL

https://gist.github.com/123ece0690d7eaf93aff72966f8dcf18

### Additional Information

I tried to triage this issue using electron-fiddle. However, the behavior seems wrong in all (tested) versions down to v7.0.0 where this feature has been introduced.

**Comment by nornagon** [comment]
I think this is expected behavior: https://www.w3.org/TR/css3-cascade/#cascade-origin

![image](https://user-images.githubusercontent.com/172800/152593441-1a3a45da-46c7-452b-8d22-d74c35f5271d.png)

i.e. !important UA > !important user > !important author > author > user > UA

which is to say, add `!important` to your style and it should function how you expect :)

**Comment by nornagon** [comment]
I've opened #32753 to clarify the documentation on this point.

**Comment by porst17** [comment]
Yeah, seems like I've been misled by the docs. That link to the W3C clarifies it for me. Putting it in the docs makes sense.
