### ISSUE TITLE
[Bug]: First click on the icon of a tray menu option has no effect

### ISSUE THREAD

**Issue by berkon** [electron/electron#32759]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

Unknown. Issue can be reproduced with Electron 15.x as well.

### Expected Behavior

When clicking the icon of an option inside a tray menu, the corresponding action should be carried out (same as if the text label would be clicked).

### Actual Behavior

When clicking the icon of an option inside a tray menu:

![image](https://user-images.githubusercontent.com/28842661/152644717-fcc76afa-4a1e-4bfd-b436-bd24f6829edf.png)

nothing happens at the first click. Only after clicking a second time, the action is carried out. When clicking on the text label of that option, the action is carried out immediately. It is not required to perform a double-click (two clicks in fast succession). The second click also works when waiting a few seconds between both clicks.

### Testcase Gist URL

https://github.com/berkon/tray-icon-doubleclick-issue-demo

### Additional Information

The issue can also be seen in MS Teams's tray menu. Here the first level does not have icons at all an thus works fine, but when going to the "Status" submenu the same issue shows up (first click does nothing). Here it is important not to click, but just to hover the "Status" menu option, so that the submenu opens without clicking.

**Comment by berkon** [comment]
Issue still exists in 17.4.0 and 18.0.3.

**Comment by berkon** [comment]
bump

**Comment by frankz61** [comment]
this issue still exist in electron 22.3,  how to avoid this question. 
should i make a browserwindow to draw a menu instead it......
