### ISSUE TITLE
[Bug]: Linux ARM64 - App dies silently with SIGTRAP if /data is not writeable

### ISSUE THREAD

**Issue by levitemkin** [electron/electron#32754]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.8

### What operating system are you using?

Other Linux

### Operating System Version

Custom distro

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Application should log that the location is not writeable. Or, don't require the files in /data/xdg_config.

### Actual Behavior

Application dies with SIGTRAP, without printing out a message.

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to either provide reproduction steps or make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. If you make a test case, please link to it in a follow-up comment, or if you determine reproduction steps, similarly include them in a follow-up comment.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
