### ISSUE TITLE
[Bug]: darwin-arm64.zip is broken.

### ISSUE THREAD

**Issue by sprout2000** [electron/electron#32757]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v17.0.0 and v18.0.0-alpha.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.2 with APFS (case-sensitive)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

unknown

### Expected Behavior

Download and extract `electron-x.x.x-darwin-arm64.zip` from [the release page](https://github.com/electron/electron/releases), and double-click Electron.app to start it.

### Actual Behavior

I get a message that the App is broken and it doesn't work.

<img width="372" alt="Screen Shot 2022-02-05 at 16 04 00" src="https://user-images.githubusercontent.com/52094761/152632780-18afce09-b178-427e-8203-0e15ad63397b.png">

### Additional Information

I used Google Chrome and Apple Safari to download the files.

**Comment by MarshallOfSound** [comment]
You need to right click + open it as it is not codesigned, either that or use the npm package which removes the quarantine bit which prevents this check
