### ISSUE TITLE
[Bug]:  webcontents.savePage(path, 'HTMLComplete') saves the html file but not the js and css files

### ISSUE THREAD

**Issue by fatwolf** [electron/electron#32771]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

Windows

### Operating System Version

WIN10 20H2

### What arch are you using?

x64

### Expected Behavior

Like this https://gist.github.com/codebytere/53c778864f931bcf1b524685d7ce8ea2 and  #32696 

When I use the packaged application of electron-build, when I call the savepage api,
  const p2 = path.join(__dirname, '2.html')
  await mainWindow.webContents.savePage(p2, 'HTMLComplete')

should generate  2.html file and a folder with css and js

### Actual Behavior

only generate  2.html   Folders with css and js are not generated

In development environment it is work normal

**Comment by smartguy1196** [comment]
I would not recommend using async... await... pattern

You don't get _clean error handling_ with it. I would instead nest the savePage calls in `Promise.then(( result )=>{})` statements:

```
mainWindow.loadFile( 'index.html' ).then(()=>{

  const p1 = path.join(__dirname, '1.html')
  const p2 = path.join(__dirname, '2.html')
  const p3 = path.join(__dirname, '3.html')

  const save = mainWindow.webContents.savePage;

  save( p1, 'HTMLOnly' )
    .then( ()=>console.log( 'HTMLOnly Success' ) )
    .catch( err => console.log( 'HTMLOnly Failure:\n' + err )

  save( p2, 'HTMLComplete' )
    .then( () => console.log( 'HTMLComplete Success' ) )
    .catch( err => console.log( 'HTMLComplete Failure:\n' + err )

  save( p3, 'MHTML' )
    .then( () => console.log( 'MHTML Success' ) )
    .catch( err => console.log( 'MHTML Failure:\n' + err )

}).catch( err => console.log( err ) )
```

to make it friendlier with your process.exit statement...

```
mainWindow.loadFile( 'index.html' ).then(()=>{

  const p1 = path.join(__dirname, '1.html')
  const p2 = path.join(__dirname, '2.html')
  const p3 = path.join(__dirname, '3.html')

  const save = mainWindow.webContents.savePage;
  const run = ( arg_array, callback ) => {
    const args = arg_array.shift() //this and...
    save( ...args )
      .then( () => console.log( args[1] + ' Success' )
      .catch( err => console.log( args[1] + ' Failure:\n' + )
      .finally( () => arg_array.length ? run( arg_array, callback ) : callback() ) //...this make the promise behave like a forEach loop with the addition of a callback to run when the loop finishes
  }

  run([
    [p1, 'HTMLOnly'],
    [p2, 'HTMLComplete'],
    [p3, 'MHTML']
  ], ()=>{
    //some callback code to be run upon completion...
    ...
    process.exit( ... )
  })

}).catch( err => console.log( err ) )
```

**Comment by fatwolf** [comment]
> I would not recommend using async... await... pattern
> 
> You don't get _clean error handling_ with it. I would instead nest the savePage calls in `Promise.then(( result )=>{})` statements:
> 
> ```
> mainWindow.loadFile( 'index.html' ).then(()=>{
> 
>   const p1 = path.join(__dirname, '1.html')
>   const p2 = path.join(__dirname, '2.html')
>   const p3 = path.join(__dirname, '3.html')
> 
>   const save = mainWindow.webContents.savePage;
> 
>   save( p1, 'HTMLOnly' )
>     .then( ()=>console.log( 'HTMLOnly Success' ) )
>     .catch( err => console.log( 'HTMLOnly Failure:\n' + err )
> 
>   save( p2, 'HTMLComplete' )
>     .then( () => console.log( 'HTMLComplete Success' ) )
>     .catch( err => console.log( 'HTMLComplete Failure:\n' + err )
> 
>   save( p3, 'MHTML' )
>     .then( () => console.log( 'MHTML Success' ) )
>     .catch( err => console.log( 'MHTML Failure:\n' + err )
> 
> }).catch( err => console.log( err ) )
> ```
> 
> to make it friendlier with your process.exit statement and loopable...
> 
> ```
> mainWindow.loadFile( 'index.html' ).then(()=>{
> 
>   const p1 = path.join(__dirname, '1.html')
>   const p2 = path.join(__dirname, '2.html')
>   const p3 = path.join(__dirname, '3.html')
> 
>   const save = mainWindow.webContents.savePage;
>   const run = ( arg_array, callback ) => {
>     const args = arg_array.shift() /*                                                this and... */
>     save( ...args )
>       .then( () => console.log( args[1] + ' Success' )
>       .catch( err => console.log( args[1] + ' Failure:\n' + )
>       .finally( () => arg_array.length ? run( arg_array, callback ) : callback() ) //...this...
>       
>       /* ...make the promise behave like a forEach loop
>       with the addition of a callback to run
>       when the loop finishes */
> 
>   }
> 
>   run([
>     [p1, 'HTMLOnly'],
>     [p2, 'HTMLComplete'],
>     [p3, 'MHTML']
>   ], ()=>{
>     //some callback code to be run upon completion...
>     ...
>     process.exit( ... )
>   })
> 
> }).catch( err => console.log( err ) )
> ```

After trying, this has nothing to do with this problem, then catch did not catch any errors

**Comment by smartguy1196** [comment]
It's for debugging. It isn't a fix, just a diagnostic method.

**Comment by smartguy1196** [comment]
have you tried writing to a different directory? Perhaps it's a permissions issue?

**Comment by fatwolf** [comment]
> 您是否尝试过写入其他目录？也许这是一个权限问题？



> have you tried writing to a different directory? Perhaps it's a permissions issue?

yes i wrote to different directories  If a electron-build program is used, no matter which directory it is written in, it will only produce html files, but not the corresponding css and JS files.

**Comment by smartguy1196** [comment]
Oh I see. Your English at the top wasn't super clear.

So no issue at all by running the gist with "electron ." or "npm start" in a developer environment.

Perhaps electron-builder is packaging it under system privileges. [Have you tried raising the execution level with `"requestExecutionLevel": "admin"`](https://www.edwardbeazer.com/run-electron-applications-with-admin-privileges-in-windows/)?
