### ISSUE TITLE
addEventListener on a select

### ISSUE THREAD

**Issue by Marvbudd** [electron/electron#32772]
I'm a newby. I have created a project starting with the electron forge. Added module support because I need xslt-processor, and solved most issues talking between the main.js, through index.js, and the V8 index.js where most of my presentation code lives. I'm not a js/DOM expert and that is probably where my problem lies. I'll start by posting just the snippets of the code that I think are relevant hopeing the problem is simple.

Here is the problem:

In my index.html I have a select drop down:

```<body>
  <div id="main" class="container">
    <header class="header">The Budd Family
    </header>
    <div id="selectDiv" class="contentLeft">
      <div id="tableDiv"></div>
      <div id="playerDiv" class="bottomLeft">
        <form id="tableSort">
          <label for="selectSort">Filter:
            <select name="selectSort" id="selectSort">
              <option value="1" selected="true">By Date</option>
              <option value="2">By Person</option>
              <option value="3">By Location</option>
              <option value="4">By File</option>
              <option value="5">By Source</option>
              <option value="6">Audio Only</option>
              <option value="7">Video Only</option>
            </select>
          </label>
```

In index.js, which is the script referenced from the above .html I have this:
```
const $selectSort = document.querySelector('#selectSort')
$selectsort.addEventListener('change', getItemsList())
function getItemsList() {
  BURRITO.sendToMain( BURRITO.req.ITEMSGETLIST, $selectSort.value )
  BURRITO.whenItemsRender().then( (tableBody) => {
...do the processing of tableBody
    } else {
      console.log('No tdElements in getItemsList!!!')
    }
  }).catch((error) => {
    console.log('Error in whenItemsRender!', error)
  })
}
```
When the page loads, getItemsList() runs once (good), but when I select a different value in the drop down and click the handler does not run. 

I have instead tried this:
```
$selectSort.addEventListener('change', () => {
  BURRITO.sendToMain( BURRITO.req.ITEMSGETLIST, $selectSort.value )
  BURRITO.whenItemsRender().then( (tableBody) => {
.... same as above
```
And the result is that the handler never runs on page load, but when changing the selection it DOES run properly.

Is this some weird issue with a page loading sequence? Should I move the addEventListener call to a different place? I don't know how to debug this but any bump in a profitable direction will be greatly appreciated.

Marvin

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
