### ISSUE TITLE
[Feature Request]: support chrome.tabCapture extension API

### ISSUE THREAD

**Issue by josh83abc** [electron/electron#32788]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hello! I am the developer of a popular DJ app (https://you.dj). For 5 years I have been using NWJS for the desktop version of my webapp. However NWJS is not reliable enough and I finally decided to make the big switch to Electron! At the beginning it was so refreshing to work with such a high quality project, everything works great BUT **one important feature is missing**!!

My DJ app can RECORD and LIVE STREAM the video and audio played by the DJ. An essential for a DJ app. With NW.JS and the ChromeOS version of my app, I am using the chrome.tabCapture API and it works great! https://developer.chrome.com/docs/extensions/reference/tabCapture/

HOWEVER **on Electron, apparently chrome.tabCapture is missing**, you only have chrome.desktopCapture, which is actually another API in Chrome. Anyway, I started to use chrome.desktopCapture on Electron BUT the audio is not recording. I am on mac. The documentation indeed mentions : "navigator.mediaDevices.getUserMedia does not work on macOS for audio capture due to a fundamental limitation whereby apps that want to access the system's audio require a signed kernel extension. Chromium, and by extension Electron, does not provide this."

I know that capturing the system audio is a pain on MacOS and SoundFlower seems not to work anymore on latest MacOS version. BUT that's not what I want to do, **I want to capture the audio of the tab only, not the system audio!** That's exactly what tabCapture does! 

So maybe there was a misunderstanding on your side, but chrome.tabCapture and chrome.desktopCapture are not duplicated APIs and tabCapture should not be removed!! 

Now my DJ app can't record or stream the audio which is a HUGE BLOCKER. I am stuck and I am afraid I will have to stick with the horrible NW.JS again. I was so close... 

Please help me.
Erik

### Proposed Solution

Add chrome.tabCapture

### Alternatives Considered

Using chrome.desktopCapture (= desktopCapturer) but the tab audio can't be captured, only the system audio. BUT it can't doesn't work on MacOS or Linux, as mentioned in the electron documentation. Which is a bummer!

**Comment by smartguy1196** [comment]
Always found it annoying to find workarounds for this. Especially when trying to get desktopCapture to capture the app on the _correct_ monitor

**Comment by Connum** [comment]
This is exactly the reason why I have to stick to NWJS for a project needing to record video and audio from a single tab. It would be nice to get some feedback from the maintainers.

**Comment by nornagon** [comment]
We now support capturing a tab with `session.setDisplayMediaRequestHandler`: https://github.com/electron/electron/blob/main/docs/api/session.md#sessetdisplaymediarequesthandlerhandler, which could be a workaround for this. Specifying a `WebFrameMain` as the video or audio stream will capture a tab.

**Comment by codebytere** [comment]
Closing as achievable per https://github.com/electron/electron/issues/32788#issuecomment-1331302467

**Comment by Anutim** [comment]
> Closing as achievable per [#32788 (comment)](https://github.com/electron/electron/issues/32788#issuecomment-1331302467)

I don't think it is?

https://developer.chrome.com/docs/extensions/reference/api/tabCapture
As mentioned here, upon obtaining the audio stream it won't be played for the user unless they pass the stream to a new AudioContext. Been trying to replicate this behaviour in Electron with no luck.
Setting enableLocalEcho to true results in an echo regardless of what I pass to getDisplayMedia, and I'm not managing to get the audio playing in any other way.

Passing it to another window is also giving me odd behaviour.
It's behaving as if the audio stream gets layered ontop of itself repeatedly, getting louder and louder.
This is my code, and unless I'm being stupid, I don't think there's anything that's in there that should result in this?
```
mainWindow.webContents.setAudioMuted(true);
audioWindow.webContents.session.setDisplayMediaRequestHandler((request, callback) => {
    callback({ audio: mainWindow.webContents.mainFrame, enableLocalEcho: false });
})
```
(Run once post windows being created)
```
const stream = await navigator.mediaDevices.getDisplayMedia({ video: false, audio: true});
const audioContext = new (window.AudioContext || window.webkitAudioContext)();
const source = audioContext.createMediaStreamSource(stream);
source.connect(audioContext.destination);
```
(Run once in the audio window post dom-load)

Would love if I'm just being stupid however, and that there's a good way to do this.
Setting the volume by modifying the gain this way seems like the ideal way to go about it, and is also how pretty much all Chrome extensions I could find for setting per-tab volume seem to go about it.

EDIT: autoGainControl in the audio property of getDisplayMedia was enabled by default and caused it. So playing audio through another instance does work fine.
Point still stands though on the tabCapture behaviour (seemingly, unless I'm an idiot again) missing.
