### ISSUE TITLE
[Feature Request]: Hi, I see electron has ffmpeg.dll file, how can I use the ffmpeg.dll in Electron like use ffmpeg.exe?

### ISSUE THREAD

**Issue by MoConWu** [electron/electron#32814]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi, I see electron has ffmpeg.dll file, how can I use the ffmpeg.dll in Electron like use ffmpeg.exe?
Just like create a video's thumbnail.
[https://ffmpeg.org/ffmpeg.html](https://ffmpeg.org/ffmpeg.html)

### Proposed Solution

I want use ffmpeg.dll like use the ffpmeg.exe API.

### Alternatives Considered

ffpmeg.exe

### Additional Information

[https://ffmpeg.org/ffmpeg.html](https://ffmpeg.org/ffmpeg.html)

**Comment by nornagon** [comment]
We don't support this.

**Comment by MoConWu** [comment]
> We don't support this.

thanks!

but if we don't support this, why we have the ffmpeg.dll file? what was the file's works?

**Comment by MoConWu** [comment]
> Could you word this better? I feel like this is likely gonna get closed due to lack of effort.
> 
> I'm interested in an actual response from the devs though
> 
> Does any of this help?
> 
> https://www.google.com/search?q=ffmpeg+electron&oq=ffmpeg+electron&aqs=chrome..69i57j0i512j0i22i30l5j69i60.3672j0j7&sourceid=chrome&ie=UTF-8

I am so sorry for my bad words.

I mean, I want to use ffmpeg to compress thumbnails, or make videos, just like ffmpeg.exe can support a lot of command lines, because I see there is a ffmpeg.dll file, I want to know how ffmoeg.dll is this file  Use, why is there this file, can I use ffmpeg.dll in the development of electron without downloading ffmpeg.exe?
