### ISSUE TITLE
PDF viewer broken when enabling PDF unseasoned feature

### ISSUE THREAD

**Issue by daniel-koc** [electron/electron#32824]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

PDF viewer working with PDF unseasoned feature

### Actual Behavior

PDF viewer not working when chrome_pdf::features::kPdfUnseasoned enabled

### Additional Information

Background
Currently Chromium is in the process of migrating the PDF viewer off the Pepper API. Chrome is dropping support for Pepper (currently scheduled for June 2022). The PDF viewer is migrated  to alternative solution called PDF unseasoned (https://docs.google.com/document/d/1olIb-1IFVqP2fLTq0eAdW-aL-K2dDDZGDe5mZgHGfO8).
Problem
When enabling PDF unseasoned (by setting chrome_pdf::features::kPdfUnseasoned enabled by default) then the following occurs when opening a PDF: "Failed to load PDF document". Very soon Chromium is dropping pepper, which will cause PDF viewer to stop working. 
One of the issues we observed is freezing when trying to inject Node into the PDF frame.

**Comment by codebytere** [comment]
@daniel-koc could you please attach a small [Fiddle](https://github.com/electron/fiddle) repro to make triaging this easier?

**Comment by codebytere** [comment]
Resolved in latest releases.
