### ISSUE TITLE
[Bug]: Import Certificate doesn't set SSL Trust bit in nssdb (app.importCertificate)

### ISSUE THREAD

**Issue by tn185075** [electron/electron#32825]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.1.4

### What operating system are you using?

Ubuntu

### Operating System Version

20.04.3 LTS

### What arch are you using?

x64

### Expected Behavior

On running this command,
``` bash
certutil -d sql:$HOME/.pki/nssdb -L
```
expected
``` text
cert-name CT,,
```
The second & third trust bits can be anything. The first one needs to have trust flag. Reference for trust bits:
![image](https://user-images.githubusercontent.com/68643107/153117517-22fd0e4f-c438-4323-9782-cd1169e8c4ba.png)

### Actual Behavior

Certificate is added to nssdb without proper trust attributes.
On running the following command:
```bash
certutil -d sql:$HOME/.pki/nssdb -L
```
Output:
```
cert-name ,,
```

### Testcase Gist URL

https://gist.github.com/tn185075/cf34e2157a69721fb29f9cf7418ee14a

### Additional Information

Note that the certificate we used is in .p12 format, and is a self signed one.

**Comment by tn185075** [comment]
https://github.com/electron/electron/issues/32816

Closing the linked issue.

**Comment by tn185075** [comment]
Any update?

**Comment by dsanders11** [comment]
@tn185075, any updates would be left here in the issue. If there aren't any comments, there aren't any updates. 🙂 

I'm not sure if this is a valid bug - the docs don't say anything about which trust bits will be set. I think this might be more of a feature request than a bug.

**Comment by tn185075** [comment]
The docs won't say anything about this, but I have seen in source code on the trust bits being set here. That's the reason behind marking this as bug.

`Importing certificate should surely help us trusting any certificate signed using that authority`, similar to how we import our own authority in Chrome.

https://github.com/electron/electron/blob/main/shell/browser/api/electron_api_app.cc#L625-L626

**Comment by dsanders11** [comment]
Thanks for the extra context and linking the code. You're right, the code does look like it intends to set the trust bits.

I'll ping @deepak1556 just to confirm that is the intended behavior. I don't have a good understanding of the mechanisms involved here, but I'll point out this extra bit of context from the original comment as it may be relevant ("Note that the certificate we used is in .p12 format, and is a self signed one.")

@tn185075, could you create an [Electron Fiddle](https://www.electronjs.org/fiddle) gist which reproduces the issue end-to-end? You can't add a `.p12` in the fiddle, but you could include it in say PEM in `main.js`, then dump it to `.p12` format in a temp file, and import it. Then you could execute `certutil -d sql:$HOME/.pki/nssdb -L` via the `child_process` module and find the relevant certificate. I know that sounds like a lot of work, but a fully end-to-end fiddle makes it significantly more likely that we will be able to fix the issue.

**Comment by tn185075** [comment]
sure @dsanders11. will work it out when I find time.

**Comment by deepak1556** [comment]
It is a bug that the CA certs are not trusted after import, there has not been much of a change for the api at `//electron` but it is very likely the problem is at `//electron/shell/browser/certificate_manager_model.cc` is broken with chromium rolls. Also, worth bringing back this test https://github.com/electron/electron/blob/4bdb50eeee95bd1853123e974b369c5fd1303843/spec-main/api-app-spec.ts#L484 when investigating this issue.

**Comment by tn185075** [comment]
@deepak1556  would appreciate if you can try and find solution before I can make it up in a fiddle, as I need to create different cert set again.

**Comment by deepak1556** [comment]
I can look into this next week, so if anyone else wants to tackle this before that, feel free to!

**Comment by tn185075** [comment]
@deepak1556 did you try that?

**Comment by tn185075** [comment]
bump!

**Comment by deepak1556** [comment]
Sorry I don't have plan to look into this bug anytime soon, please use https://github.com/electron/electron/issues/32825#issuecomment-1067844548 as starting point for others investigating this bug.

**Comment by tn185075** [comment]
bump!

**Comment by jscottPTC** [comment]
Any updates on this?  This might be causing a problem we are running into.  Electron doesn't seem to send any kerberos token in its requests when run in Ubuntu 22.04.  We believe it has to do with the server certificate not being trusted.  We are able to import the certificate via 'app.importCertificate' with a success result.  Kerberos auth seems to work fine in our electron app on Windows 10.

**Comment by tn185075** [comment]
bump!

**Comment by tn185075** [comment]
bump!

**Comment by tn185075** [comment]
Bump
