### ISSUE TITLE
[Bug]: session.defaultSession.getBlobData(payload.blobUUID) always pedding

### ISSUE THREAD

**Issue by inu1255** [electron/electron#32830]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.985

### What arch are you using?

x64

### Expected Behavior

`session.defaultSession.getBlobData(payload.blobUUID)` can resolve a buffer

### Actual Behavior

`session.defaultSession.getBlobData(payload.blobUUID)` always pedding

### Additional Information

I use `electron.protocol.registerStreamProtocol` and upload a FormData with blob like this 
``` javascript
document.body.innerHTML = `<input type="file"/>`;
document.body.firstElementChild.onchange = () => {
  var file = document.body.firstChild.files[0];
  var f = new FormData();
  f.append("file.jpg", file);
  const xhr = new XMLHttpRequest();
  xhr.open("POST", "/seeeeea");
  xhr.send(f);
};

```

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you’re still experiencing this issue in Electron 14.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by visualgui823** [comment]
util 16.0.8 it's not fixed
