### ISSUE TITLE
[Bug]: ERROR:node_controller.cc(585)] Trying to re-add dropped peer

### ISSUE THREAD

**Issue by arjunj132** [electron/electron#32843]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Debian GNU/Linux 11 (bullseye)

### What arch are you using?

x64

### Last Known Working Electron version

16.0.8

### Expected Behavior

The app to run without any errors or warnings.

### Actual Behavior

After using for about 30 sec - 1 min, and closing the app, an error appears:

```
[6852:0209/175149.954223:ERROR:node_controller.cc(585)] Trying to re-add dropped peer DB591276DC66D33E.81417C41674CCD8B
```

The numbers aren't always the same, the same error (`Trying to re-add dropped peer`) always happens.

### Testcase Gist URL

https://gist.github.com/8348f95ed6431b5131c6c289928221f9

**Comment by ckerr** [comment]
Looks like this is a debug message in [`mojo/core/node_controller.cc`](https://source.chromium.org/chromium/chromium/src/+/main:mojo/core/node_controller.cc;l=598?q=Trying%20to%20re-add%20dropped%20peer&ss=chromium)

**Comment by ckerr** [comment]
Looks like this is a DVLOG message in [`mojo/core/node_controller.cc`](https://source.chromium.org/chromium/chromium/src/+/main:mojo/core/node_controller.cc;l=598?q=Trying%20to%20re-add%20dropped%20peer&ss=chromium), and I think those are only enabled when DCHECKs are enabled...?

@arjunj132 is this E 17.0.0 binary one that you got just via `npm install`, or did you download it from somewhere? I'm trying to understand why you're seeing debug messages in a production build.

**Comment by arjunj132** [comment]
Sorry, it looked like I didn't install it properly, so I installed it again and now it is not popping up.

**Comment by billpriest** [comment]
I'm seeing this on 
DISTRIB_ID=Pop
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Pop!_OS 21.10"

The installed version is google-chrome-stable installed today (2/24/2022 EST).
google-chrome-stable --version
Google Chrome 98.0.4758.102

md5sum google-chrome-stable_98.0.4758.102-1_amd64.deb 
9d0f7d7eeb70761fcfcab209bc20bd98  google-chrome-stable_98.0.4758.102-1_amd64.deb

[1593045:4:0224/154224.950060:ERROR:node_controller.cc(585)] Trying to re-add dropped peer FAC01C8B4338B000.48736E19A77A822D
[1593045:4:0224/154224.951176:ERROR:node_controller.cc(585)] Trying to re-add dropped peer 3ED24D64D2753903.F80EA253C34D1255
[1593045:4:0224/154225.186225:ERROR:node_controller.cc(585)] Trying to re-add dropped peer B72AD5C4C192A3C7.4C457ABB6DEA7781
[1593045:4:0224/154225.443243:ERROR:node_controller.cc(585)] Trying to re-add dropped peer 8DFE23EABD15BB4B.2D0CBB8B414BC833
[1593045:4:0224/154325.262978:ERROR:node_controller.cc(585)] Trying to re-add dropped peer F1A24AA3969C862F.4D4550FFC0F6893C

**Comment by G-Harmon** [comment]
I am using chrome's debug logging for the first time. I see this as well. The logging flags I added were: ` --log-level=1 --enable-logging=stderr`

Google Chrome | 98.0.4758.102 (Official Build) (64-bit)
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | Linux
JavaScript | V8 9.8.177.11
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
Command Line | /usr/bin/google-chrome --log-level=1 --enable-logging=stderr --enable-crashpad --flag-switches-begin --flag-switches-end

```
[3025411:4:0225/110440.125659:ERROR:node_controller.cc(585)] Trying to re-add dropped peer D768B872DCA415DE.C596F4A083E0DE27
[3025411:4:0225/110447.011822:ERROR:node_controller.cc(585)] Trying to re-add dropped peer 8005FDD8C5DA90AD.151E4D19D65138B4
[3025411:4:0225/110532.665095:ERROR:node_controller.cc(585)] Trying to re-add dropped peer 2A99831D90FDFAB.B7E1EF61EFDA14F3
```

**Comment by arjunj132** [comment]
Hmm... Just found out it's happening again:

```
[20907:0227/164150.437331:ERROR:node_controller.cc(585)] Trying to re-add dropped peer F0A63201AC49F874.4F20FC8E35D410E3
[20907:0227/164213.984025:ERROR:node_controller.cc(585)] Trying to re-add dropped peer B9D47C98971B9602.3F14B05B5D32F0F8
```

**Comment by someburner** [comment]
Also happening here. ubuntu 21.10.1, gnome, amd driver.

**Comment by Mavrosogas** [comment]
[1300:1736:0309/202833.110980:ERROR:node_controller.cc(585)] Trying to re-add dropped peer 8B5F09DF1E84CEC7.223CB1EAA89118D7
[1314:4:0309/202833.111269:ERROR:node_controller.cc(585)] Trying to re-add dropped peer 8B5F09DF1E84CEC7.223CB1EAA89118D7

Im also getting the same error and it is driving me nuts
Is there a way to remove the message from prompting on my terminal even without solving it?

**Comment by boutetnico** [comment]
I'm also seeing these errors on latest Electron 17.1.2.

**Comment by mollthecoder** [comment]
I have this issue on electron 17.1.2 linux.
Arc: ARMv7
As far as I can see from all of these comments it's only happening on linux. Correct me if I'm wrong.

**Comment by DarkGuy10** [comment]
Same error on electron 17.1.2 linux (manjaro)

**Comment by ajoslin103** [comment]
[18254:0409/124351.991391:ERROR:node_controller.cc(585)] Trying to re-add dropped peer 9111ED4E31732AA5.EBBF6D9FD4DA976B

after closing a window in my "electron": "^17.2.0" project on mac os 12.3

**Comment by mollthecoder** [comment]
Is it only Unix platforms? I don't see it happening in Windows.

**Comment by torakiki** [comment]
Same here, a customer on Mint 21, when doing some action it triggers this error and the page becomes blank.
If it can help the issue showed up when we migrated from electron 16.0.2 to 16.0.8 so for me the latest working version was 16.0.2

**Comment by davidhaley** [comment]
`[main] [19210:1010/110227.790942:ERROR:node_controller.cc(585)] Trying to re-add dropped peer D69AAAD367E1980D.29A44C0B3C4FD113`

Electron: 17.0.1

**Comment by raphael10-collab** [comment]
I'm experiencing the same error `ERROR:node_controller.cc(585) Trying to re-add dropped peer` with:

    Electron 17.2.0
    O.S. : Ubuntu 22.04

How to solve the issue?

**Comment by ha-mulan** [comment]
same here
`ERROR:node_controller.cc(585) Trying to re-add dropped peer`
```
Electron 17.2.0
O.S. : Ubuntu 18.04
```

**Comment by Mavrosogas** [comment]
I found the solution but if neglected to contribute so my memory is a bit fuzzy. If I remember correctly I used a different browser either opera or chrome and the bug didnt occur. I hope that helps

**Comment by mollthecoder** [comment]
bump

**Comment by mollthecoder** [comment]
bump

**Comment by laux98** [comment]
Same error in ubuntu 22.04

**Comment by mollthecoder** [comment]
bump
