### ISSUE TITLE
[Bug]: Electron Docs website is unusable (in Chrome) currently. Cannot scroll down.

### ISSUE THREAD

**Issue by 7ombie** [electron/electron#32845]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 1.0

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

12.0.0

### Expected Behavior

The Electron Docs website consistently permits scrolling up and down when the main text scrolls past the end of the viewport.

### Actual Behavior

The page has recently developed an issue where you can sometime scroll down, but other times the page will continually jump back up a bit, so you cannot get past that part of the page.

Sometimes the page will scroll normally, but only until the text (really, the H1 at the start of the document) hits the top of the viewport, beneath the banner (it's obvious from the scrollbar that there's plenty of content below the fold).

Everything worked fine till recently, and still works fine on Safari, but is broken in Chrome Stable and Canary.

I tried resizing my viewport, giving it tons of room, stuff like that, but it didn't help.

I looked at the CSS a bit, but it seems to be a JS thing.

### Testcase Gist URL

https://www.electronjs.org/docs/latest/api/command-line-switches

### Additional Information

This should be pretty easy to replicate (if it's not specific to my machine in some way). It happens more often than not, so just surf the docs in Chrome a little.

**Comment by 7ombie** [comment]
P.S. I've had this issue since yesterday evening at least, maybe a day or so longer.

**Comment by miniak** [comment]
cannot reproduce

**Comment by qexat** [comment]
Had the same issue.
OS: Ubuntu 21.10
Browser: Chrome 98.0.4758.80 (64-bits)

**Comment by qexat** [comment]
Cannot reproduce extensionless. Might be an extension that causes the bug

**Comment by 7ombie** [comment]
I only have *AdBlocker for YouTube* and *TamperMonkey* (with no scripts running). In any case, I tried it on Chrome Canary (stock), and it happened there too (and is still happening).

I thought it may have something to do with the default font-sizes in the Chrome settings. Mine is set to **Medium (Recommended)**, but I tried setting it to **Small** and **Large**, but it was still happening.

My display is 2650x1600, but only 13.3 inch, so I use it at effective resolutions of 1680x1050, 1440x900 or 1280x800 (depending what I'm doing). Maybe that has something to do with it, but Chrome reports the effective resolution of the viewport, so it shouldn't make a difference.

**Comment by James-Livesey** [comment]
Also happens to me, too. Tested it in a guest profile on Chrome, and the bug still is present.

```
Debian GNU/Linux 11
Linux volt 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
Google Chrome 98.0.4758.80 (Official Build) (64-bit)
```

**Comment by mist8kengas** [comment]
Bug gets fixed if you resize the browser window to hide the index.

**Comment by 7ombie** [comment]
Disabling JavaScript also works, but you need to leave DevTools open.

**Comment by qexat** [comment]
> Disabling JavaScript also works, but you need to leave DevTools open.

Yes, because it's a JavaScript-related bug. It happens because of the weird behavior of an event.

**Comment by 7ombie** [comment]
> Yes, because it's a JavaScript-related bug. It happens because of the weird behavior of an event.

Sorry, I should've been clearer. I wasn't trying to figure out the problem. I was just sharing a simple way to access the pages while they're still broken (for anyone else who ends up here).

**Comment by mist8kengas** [comment]
I believe the bug is related to the `onscroll` event the page listens to on the header element

**Comment by 7ombie** [comment]
This appears to be fixed now. I confirmed with one other user that had the same issue, and they also reported that it's working again. Happy to close. Thanks, guys.
