### ISSUE TITLE
[Bug]: Fiddle in Inter-Process Communication Documentation not working and code missing an import

### ISSUE THREAD

**Issue by ClemensDinkel** [electron/electron#32867]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

16.0.8

### Expected Behavior

Fiddle in the Electron Documentation at  https://www.electronjs.org/docs/latest/tutorial/ipc#pattern-3-main-to-renderer should load successfully and should include "ipcMain" in the imports of "main.js".

### Actual Behavior

Fiddle will not load and when copying the code manually running the code will result in an Error since "ipcMain" is missing in the import of "main.js".

### Additional Information

Couldn't find a seperate issue board for the documentation, so I posted this here.

**Comment by SteffRainville** [comment]
Had the same problem following the web based IPC tutorials on 17.0.1
