### ISSUE TITLE
[Bug]: BrowserView loadURL(process.env.WEBPACK_DEV_SERVER_URL) cann't click

### ISSUE THREAD

**Issue by YunSmile** [electron/electron#32866]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows10

### What arch are you using?

x64

### Last Known Working Electron version

17.0.0

### Expected Behavior

const { BrowserView, BrowserWindow } = require('electron')

const win = new BrowserWindow({ width: 800, height: 600 })
win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)

const view = new BrowserView()
win.setBrowserView(view)
view.setBounds({ x: 0, y: 0, width: 300, height: 300 })
view.webContents.loadURL(process.env.WEBPACK_DEV_SERVER_URL+'#/message')

this BrowserView has a button, I can click

### Actual Behavior

this BrowserView has a button, I cann't click

**Comment by RaisinTen** [comment]
That's not valid code because I get this error when I run it:
```
App threw an error during load
Error: Cannot create BrowserWindow before app is ready
```
It means that the `ready` event must be emitted by the `app` object before the `BrowserWindow` ctor can be called.

Also, this needs some more info, like what is `process.env.WEBPACK_DEV_SERVER_URL` supposed contain? It appears to be `undefined` in my current setup.
