### ISSUE TITLE
[Bug]: In Discord Bot Client not appears the Token Login of the BOT

### ISSUE THREAD

**Issue by J-YT2021** [electron/electron#32878]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Last Known Working Electron version

3.1.0

### Expected Behavior

![image](https://user-images.githubusercontent.com/81887664/153738144-68039b32-00d6-443f-bb95-bf7255ba4bb0.png)

### Actual Behavior

The screen of the Token Login not appears me. Just I see a black screen and I don´t know why.

**Comment by andreisefutaucelMare** [comment]
i ts for all this, i ts pached...
