### ISSUE TITLE
[Bug]: e.getFileName Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by TrofinSorin** [electron/electron#32875]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Electron 17.0.0
Node v 14.14.0
"electron-builder": "^22.14.13",
 "electron-devtools-installer": "^3.2.0",
 "electron-notarize": "^1.1.1",
 "electron-packager": "^15.4.0",
 "electron-rebuild": "^3.2.7",
    
### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Last Known Working Electron version

-

### Expected Behavior

Opening the app with .exe or .dmg should work.

    
  
    

### Actual Behavior

The build works either with npm run package or with electron-packager.

Whe i try to start the app in ubuntu or .exe in Windows i get this error.
`A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Function.e.getFileName (/home/user/Desktop/MyProjects/App/Web/electron-react-boilerplate-linux-x64/resources/app/release/app/dist/main/main.js:2:127933)`

    
I'm using this boilerplate: https://github.com/electron-react-boilerplate/electron-react-boilerplate
I have "main": release/app/dist/main/main.js in package json
I followed different issues, i added "homepage": "./", removed react scripts. 

I see it goes to this minified code
`(var i=0,o=n.length;i<o;i++)if((e=n[i].getFileName())!==__filename){if(!t)return;if(e!==t)return}},Error.captureStackTrace(i),Error.prepareStackTrace=r,Error.stackTraceLimit=n;return 0===e.indexOf("file://")&&(e=o(e)),e}
`

On stackTraceLimit

I can't understand why it's not working. 
The app is working perfectly in dev mode.

build from package.json:
` "build": {
    "productName": "appName",
    "appId": "org.erb.appName",
    "asar": true,
    "asarUnpack": "**\\*.{node,dll}",
    "files": [
      "dist",
      "node_modules",
      "package.json"
    ],
    "afterSign": ".erb/scripts/notarize.js",
    "mac": {
      "target": {
        "target": "default",
        "arch": [
          "arm64",
          "x64"
        ]
      },
      "type": "distribution",
      "hardenedRuntime": true,
      "entitlements": "assets/entitlements.mac.plist",
      "entitlementsInherit": "assets/entitlements.mac.plist",
      "gatekeeperAssess": false
    },
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "target": [
        "nsis"
      ]
    },
    "linux": {
      "target": [
        "AppImage"
      ],
      "category": "Development"
    },
    "directories": {
      "app": "release/app",
      "buildResources": "assets",
      "output": "release/build"
    },
    "extraResources": [
      "./assets/**"
    ],
    "publish": {
      "provider": "github",
      "owner": "electron-react-boilerplate",
      "repo": "electron-react-boilerplate"
    }
  },`
 
  
Thank you for help.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by usmansharif525** [comment]
@TrofinSorin, did you find any solution?
I am facing the same issue...
