### ISSUE TITLE
consulting: Are there any libraries that add screen reader support which are compatible with js/electron?

### ISSUE THREAD

**Issue by king-dahmanus** [electron/electron#32873]
This is really not an issue, just a consulting topic. Please suggest any js library that allows for nvda support to electron apps, same way that freecodecamp announces the alerts or gmail/skype. I'm asking this to suggest using it to discord's accessibility team, so I'm really not a developer. The result shal be auto announcing of incoming discord messages in the current dm, among other things that are faster/more pleasant with screen reader support instead of the default usage of sapi

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electronjs) a try.

I hope this helps!
