### ISSUE TITLE
[Feature Request]: Support for scaling window control buttons under macOS

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#32876]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Apps like Discord simply scale window control buttons (the semaphore) on macOS with the zoom level, as that's the easiest thing to do to make sure the UI stays consistent at any zoom level, otherwise ensuring that the window control buttons don't look weird is tricky.

The problem is Discord is just rendering their own macOS-like buttons, while in practice we want the real buttons to be rendered, as those behave subtlety differently (slight different style, they get colored when hovered inside a non-focused window, hovering over the green button renders a popover etc.).

### Proposed Solution

macOS seems to support rendering scaled in/out window control buttons, or at least that seems to be the case looking at this screenshot of the app Transmission:

<img width="1440" alt="Screen Shot 2022-02-12 at 16 54 30 (2)" src="https://user-images.githubusercontent.com/1812093/153720667-2fc0e022-9dc2-4e65-880f-9147ea5c94d7.png">

So it'd be nice if Electron could expose APIs for doing just that, with an arbitrary zoom level, under macOS.

### Alternatives Considered

Well macOS' window control buttons can't really be reimplemented on the app's side with 100% fidelity. I'm not sure what an alternative solution for apps like Discord could be.

**Comment by miniak** [comment]
This is unfortunately not supported by macOS and we cannot implement it.

**Comment by miniak** [comment]
We can keep this open for a while in case somebody else has an idea how to do this.

**Comment by fabiospampinato** [comment]
@miniak if it's not supported by macOS how can that window display scaled down buttons? Are only some fixed scalings supported?

**Comment by miniak** [comment]
@fabiospampinato those are special popup windows or something that have smaller window control buttons and they are fixed size
