### ISSUE TITLE
[Bug]: Devtools opened at bottom for browserView webcontents is not fully visible

### ISSUE THREAD

**Issue by tushar-ghadge** [electron/electron#32880]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 

### What arch are you using?

x64

### Expected Behavior

When devTools is opened with mode:"bottom" , it should be able show view without hiding the bottom views. For eg. in network tab, user should able to scroll till last entry in the table and that should be clearly visible.

### Actual Behavior

![image](https://user-images.githubusercontent.com/12984605/153824335-a4374015-42f5-4e7a-b852-bc1d559b5ce9.png)
- Currently devTools for browserView webContents is not fully visible while trying to scroll at fullest. View is cutting from bottom for last few entries and view. Same happens with other dev tools tab.

### Testcase Gist URL

https://gist.github.com/b1238af9836d6c034c1ff4ec2e22564b

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you’re still experiencing this issue in Electron 14.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.
