### ISSUE TITLE
[Feature Request]: Incomplete display of edges due to rounded corners

### ISSUE THREAD

**Issue by weartist** [electron/electron#32887]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I found that on mac, electron will come with rounded corners, at which point the edges will not show completely if the component with the border is close to the edge. Is there any way I can simply deal with this problem?

![image](https://user-images.githubusercontent.com/17105034/153867701-8ffe9eec-1d62-432b-a0a2-08138d7536d4.png)

![image](https://user-images.githubusercontent.com/17105034/153867658-cc9f4b08-f444-432d-ba0b-a74e60ab7bdd.png)

### Proposed Solution

Whether it can be set to automatically adapt rounded corners for internal views (if available)

### Alternatives Considered

I can draw a rounded corner internally with the same value as the self-contained rounded corner, but I'm not sure if others have the same need, and if so, we can provide

**Comment by Sagargupta16** [comment]
Can you Assign me this issue I can help resolving it... Thanks.

**Comment by nornagon** [comment]
You might be looking for the `roundedCorners: false` BrowserWindow option.
