### ISSUE TITLE
[Feature Request]: get env of main process on renderer process

### ISSUE THREAD

**Issue by Zack921** [electron/electron#32883]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

![image](https://user-images.githubusercontent.com/32858043/153842457-1c3815d7-a954-4b8c-9b8b-458c567b307c.png)
![image](https://user-images.githubusercontent.com/32858043/153842557-a6824008-4956-4bec-a28b-406f2681b9ab.png)

### Proposed Solution

hi~how can i get env of main process on renderer process?

### Alternatives Considered

-

**Comment by ckerr** [comment]
Hey @Zack921, if I'm understanding the question correctly, this feature would best be added in your code by adding IPC code to communicate between the main and renderer processes. https://www.electronjs.org/docs/latest/api/ipc-main has documentation on how this can be done and includes some sample code on how to implement a simple IPC call.

**Comment by ckerr** [comment]
Oh, also, you may want to check out [the Electron Discord server](https://discord.com/invite/electronjs)! There are a lot of people writing Electron apps there, and they're a great resource for figuring out how to get around Electron's features!

**Comment by Zack921** [comment]
> Hey @Zack921, if I'm understanding the question correctly, this feature would best be added in your code by adding IPC code to communicate between the main and renderer processes. https://www.electronjs.org/docs/latest/api/ipc-main has documentation on how this can be done and includes some sample code on how to implement a simple IPC call.

thanks~I solved the problem by `electron/remote`
![image](https://user-images.githubusercontent.com/32858043/154013471-6cbac3da-200c-4882-a981-07a05f7a8724.png)
