### ISSUE TITLE
[Feature Request]: Why Electron open a new window is 100 times slower then NW.js

### ISSUE THREAD

**Issue by xland** [electron/electron#32882]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron：
https://user-images.githubusercontent.com/2980915/153837042-dcaf1568-43ed-4cd8-a5f6-0996cc111a8d.mp4

NW.js：
https://user-images.githubusercontent.com/2980915/153837181-3fe16a82-eb77-49cd-8c1f-f58ca7f65855.mp4

Electron Code
```js
const { app, BrowserWindow,ipcMain } = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences:{
      nodeIntegration:true,
      webSecurity:false,
      contextIsolation:false,
    }
  })
  mainWindow.loadFile('index.html')
}

ipcMain.handle("newWin",()=>{
   let win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences:{
      nodeIntegration:true,
      webSecurity:false
    }
  })
  win.loadFile('index.html')
})
app.whenReady().then(() => {
  createWindow()
})
```
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <button id="btn">open a new window</button>
    <script>
          document.getElementById("btn").addEventListener("click", () => {
            let {ipcRenderer} = require("electron")
            ipcRenderer.invoke("newWin")
          })
    </script>
  </body>
</html>
```

NW.js Code
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <button id="btn">click create a Window</button>
    <script>
      document.getElementById("btn").addEventListener("click", () => {
        nw.Window.open(
          "file:///E:\\nwjs\\nwjs-sdk-v0.61.0-win-x64\\index.html",
          {},
          function (new_win) {
            new_win.show();
          }
        );
      });
    </script>
  </body>
</html>

```

### Proposed Solution

Optimize please.

### Alternatives Considered

none.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by xland** [comment]
I know this issue will be closed immediately.
But please check it.
It is realy a problem.
@codebytere

**Comment by xland** [comment]
#32375
