### ISSUE TITLE
[Bug]: Frameless windows don't have OS's open/close/minimize/maximize animation

### ISSUE THREAD

**Issue by jcv8000** [electron/electron#32899]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 (21H2 build 22000.493)

### What arch are you using?

x64

### Last Known Working Electron version

17.0.0

### Expected Behavior

In 17.0.0, my frameless window would have the Windows 11 "pop in" and "fade back" animations when the app starts/exits

![17-0-0](https://user-images.githubusercontent.com/12619113/154007671-140a5f04-d84f-4fdb-b263-5d5a475db1a9.gif)

(I don't think the Windows Vista-looking frame that pops up matters. When I make the window wait to show until `dom-ready` that issue goes away, and that's how my actual application does it)

### Actual Behavior

As of 17.0.1 the frameless window instantly appears/disappears on start/exit (I'm pressing Alt+F4 to close the window in both gifs)

![17-0-1](https://user-images.githubusercontent.com/12619113/154007826-1b3bdbaa-a40c-4f8e-86e2-d3bd9cd481ec.gif)

### Testcase Gist URL

https://gist.github.com/jcv8000/c587ff1c069b0324ad5d9aecb633754f

### Additional Information

I uploaded the files in a gist, but all I had to do to test this was download the quick-start and add `frame: false` to the BrowserWindow options

**Comment by wheezard** [comment]
I have the same issue. It also doesn't play animation when I minimize the window.

**Comment by LitileXueZha** [comment]
Same problem on WIndows 10 x64, Electron v17.1.0

**Comment by rmill777** [comment]
Issue is still there on v18.0.1

**Comment by wheezard** [comment]
On v18.1.0, the issue has been resolved for me.
