### ISSUE TITLE
[Bug]: Using RTL system language causes view.setBounds() x value to start on the right

### ISSUE THREAD

**Issue by nicolepeverley** [electron/electron#32891]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

When using an RTL (right-to-left) system language on Mac setting an x value for `view.setBounds()` starts on the left, not the right. To reproduce change your system language to Hebrew. (https://support.apple.com/en-ca/guide/mac-help/mh26684/mac)

<img width="1197" alt="Screen Shot 2022-02-14 at 11 30 27 AM" src="https://user-images.githubusercontent.com/43253618/153933068-e29552ca-50f7-4841-a335-ab2f80b19521.png">

### Actual Behavior

When using an RTL (right-to-left) system language on Windows setting an x value for `view.setBounds()` starts on the right instead of the left. This can be reproduced by changing your system language to Hebrew. (https://support.microsoft.com/en-us/windows/manage-display-language-settings-in-windows-219f28b0-9881-cd4c-75ca-dba919c52321#ID0EBD=Windows_10)

<img width="888" alt="ElectronRTLSetBounds" src="https://user-images.githubusercontent.com/43253618/153932373-f46d72cc-7849-4e5a-8e4d-392bf5a1516c.png">

### Testcase Gist URL

https://gist.github.com/nicolepeverley/14ef9ec9548dd9891a694e7d4c756db4

### Additional Information

Not sure if the expected behavior for RTL languages should have the x value start from the right, however it should be consistent across operating systems.

**Comment by VerteDinde** [comment]
Confirmed, going as far back as Electron 14.0.0.
