### ISSUE TITLE
[Bug]:  setBackgroundColor does not work for window

### ISSUE THREAD

**Issue by wslp12** [electron/electron#32898]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

window11, window10

### What arch are you using?

x64

### Last Known Working Electron version

x

### Expected Behavior

```
mainWindow.addBrowserView(view);
view.setBounds({
  width: 800,
  height: 600,
  x: 0,
  y: 0
})
  view.setBackgroundColor("#FF000000")
```
The background color needs to be black.

### Actual Behavior

The view's background color is not black.

### Testcase Gist URL

https://gist.github.com/yunjimmy/b1fd47ff8e23a38c079bf087f8cc3ba6

### Additional Information

In the case of MAC, the black view's background is black, but in the case of windows, it is not.

**Comment by PranshVaishnav** [comment]
Can I work on this issue.

**Comment by yunjimmy** [comment]
> Can I work on this issue.

plaese
