### ISSUE TITLE
[Bug]: `webPreferences.disableDialogs` does not disable `window.print()`

### ISSUE THREAD

**Issue by lyswhut** [electron/electron#32925]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

14.x/15.x/16.x/17.x

### What operating system are you using?

Windows

### Operating System Version

windows 10 21H1

### What arch are you using?

x64

### Expected Behavior

`webPreferences.disableDialogs` will disable all dialogs when `true`

### Actual Behavior

When `webPreferences.disableDialogs` is `true`, calling `window.print()` will still pop up the print dialog

### Testcase Gist URL

https://gist.github.com/f7ff2b7b03e7d83afffcb09d17d673af

**Comment by codebytere** [comment]
"dialogs" here refers to javascript dialogs, like alert and confirm. That setting doesn't affect `window.print()`

**Comment by lyswhut** [comment]
@codebytere Since `window.print` also pops up a system dialog, why not classify it into dialogs, see the following code:

```js
// renderer.js

window.print()
setInterval(() => {
  window.print()
}, 100)
```

For apps that load external websites, in order to ensure the consistency of the UI, it is necessary to prevent (or subscribe) external websites from calling APIs that can pop up native windows (such as `window.alert()`, `window.print()`, etc.)

**Comment by lyswhut** [comment]
@codebytere Since `window.print` also pops up a system dialog, why not classify it into dialogs, see the following code:

```js
// renderer.js

window.print()
setInterval(() => {
  window.print()
}, 100)
```

For apps that load external websites, in order to ensure the consistency of the UI, it is necessary to prevent (or subscribe) external websites from calling APIs that can pop up native windows (such as `window.alert()`, `window.print()`, etc.)
