### ISSUE TITLE
[Bug]: The click event will time out in notification even with the 'never' timeoutType.

### ISSUE THREAD

**Issue by Naozumi520** [electron/electron#32923]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Expected Behavior

with the code it should print out 'clicked' when the user close or click on the notification. 
```js
function stayOverlay() {
  const newNotification = new Notification({ title: 'title', timeoutType: 'never' })
  newNotification.on('click', () => {
    console.log('clicked')
  })
  newNotification.show()
}
stayOverlay()
  ```

### Actual Behavior

It prints out 'clicked' yes, but only if you click immediately. After 6 seconds it will times out even though the notification is still here, but it can't detect if the button is clicked or not anymore.

**Comment by mlaurencin** [comment]
https://gist.github.com/mlaurencin/0f0c925f2e136c09fb44d97d13c8d291

**Comment by Naozumi520** [comment]
bump

**Comment by Naozumi520** [comment]
Cool
