### ISSUE TITLE
[Bug]: getPrinters method bug on Ubuntu 18.04

### ISSUE THREAD

**Issue by DHVPP** [electron/electron#32930]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

18.04

### What arch are you using?

x64

### Last Known Working Electron version

10.0.0

### Expected Behavior

On Ubuntu 18.04 and 20.04, method `getPrinters()` returns `isDefault` flag as true for the default system printer in the list.

### Actual Behavior

On Ubuntu 18.04, `isDefault` flag for the system default printer is returned as false (each printer in the list has isDefault set to false).

### Additional Information

I did an upgrade from electron 10 to electron 16, and the app functionality connected with isDefault property for printers stopped working on Ubuntu 18.04 as described previously. On Ubuntu 20.04, everything is working as expected.

**Comment by DHVPP** [comment]
Hey, sorry to be bumbing my own issue, but can I please get a feedback if this sounds like a valid case that needs a fix or it might be an issue with my project specifically. Thanks in advance

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.
