### ISSUE TITLE
[Bug]: macOS disable-features IOSurfaceCapturer no longer works as of Electron 17.0.0

### ISSUE THREAD

**Issue by timothylui** [electron/electron#32958]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12.2.1 Monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

16.0.9

### Expected Behavior

This flag is used in conjunction with setContentProtection to prevent desktopCapturer from capturing windows that are protected.

### Actual Behavior

DesktopCapturer can still see protected content as of 17.0.0

### Additional Information

As of 17.0.0 the workaround suggested in https://github.com/electron/electron/issues/19880 no longer works (it's fine in the most recent 16.0.9).

It's quite important to macOS apps that use video calling and screen sharing as you can no longer hide the application from being captured whilst screen sharing, giving both a bad experience and increasing the bandwidth/cpu required.

I've searched through both the electron source code and the chromium changes for 97/98 and can't find any reference to this so I'm not sure why it no longer works.

**Comment by f4z3k4s** [comment]
We experience the same.

**Comment by ckerr** [comment]
## If No Repro Included

Thanks for reporting this and helping to make Electron better!

Please use [Electron Fiddle](https://github.com/electron/fiddle) to create a standalone (no external dependencies) testcase and publish it as a [gist](https://gist.github.com), then link to it here.

- Even if you have a code snippet or a git repository that show the testcase, please put it in a gist. This lets maintainers triage issues more effectively. It also ensures that we're testing the exact same issue that you're seeing!

- Please avoid external dependencies in the test. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.

- If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to the gist in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by VerteDinde** [comment]
@OferSisso1 @f4z3k4s Do either of you happen to have a repro of the issue that we could look at, or additional details? We'd like to tackle this, but without clear repro steps or a gist, it's a bit hard to move it forward.

**Comment by OferSisso1** [comment]
@VerteDinde as mentioned here [#19880](https://github.com/electron/electron/issues/19880)
To Reproduce:
Make a simple blank app, call `setContentProtection` on the `browserWindow`, capture the desktop stream using the `desktopCapturer` module and show it on a canvas.
The solution to make it work and prevent capturing the window in MacOS was calling `app.commandLine.appendSwitch('disable-features', 'IOSurfaceCapturer')`.
It worked in `17.0.0-alpha.3` and stopped working in `17.0.0-beta.1`.

**Comment by f4z3k4s** [comment]
@VerteDinde sorry for the late response, I've setup a [quick repro](https://github.com/scriptide-tech/electron-desktop-capturer-bug-repro). On `master` which is using `17.2.0`, it breaks. On `latest-working-version`, which uses `16.0.9` - being the only single change, it works correctly. 

Expected: on the canvas that's drawn in the renderer, you shouldn't see the contents of main window displayed. 
With 16.09: works as expected
With 17.x: you see the main window, which seems like `setContentProtection(true)` doesn't work properly

**Comment by Slapbox** [comment]
@ckerr any update on this? It seems like a pretty serious issue that this feature doesn't seem to be working on the two operating systems that the docs say it works for (Windows and macOS.)

Presumably a workable repro for this issue - just [take a screenshot](https://support.apple.com/en-us/HT201361) of the running Fiddle and see if the window's contents are obscured or not - https://gist.github.com/275e7e5fff1a1075480b7cf82610e317

**Comment by 779102260** [comment]
v18.2.3 have the same problem：

shortcut : work
mediaStream: not work

```js
navigator.mediaDevices.getDisplayMedia({
    video: true,
    audio: true,
}).then(stream => {
    console.log(stream)
}).catch(e => {
    console.error(e)
})
```

**Comment by 779102260** [comment]
sorry, screenshot



---Original---
From: ***@***.***&gt;
Date: Thu, May 19, 2022 06:44 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [electron/electron] [Bug]: macOS disable-features IOSurfaceCapturer no longer works as of Electron 17.0.0 (Issue #32958)




 
@779102260 what do you mean?
  
shortcut : work
  
What shortcut?

**Comment by 779102260** [comment]
mediaStream can still capture electron when i&nbsp;setContentProtection(true)



---Original---
From: ***@***.***&gt;
Date: Thu, May 19, 2022 08:20 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [electron/electron] [Bug]: macOS disable-features IOSurfaceCapturer no longer works as of Electron 17.0.0 (Issue #32958)




 
So you mean that when you use mediaStream that setContentProtection prevents viewing as intended, or it does not?

**Comment by QaisAlkhateeb** [comment]
I'm on electron=version v18.1.0 & macOS=Monterey 12.3.1  and facing the same issue MacOS .
are there any workaround for this issue ??

**Comment by MarshallOfSound** [comment]
Merging into #19880

**Comment by fdlmdark** [comment]
After checking source code, my workaround is 
app.commandLine.appendSwitch('disable-features', 'IOSurfaceCapturer,DesktopCaptureMacV2')

**Comment by bukharin** [comment]
@fdlmdark this workaround stop working on Electron 24+
