### ISSUE TITLE
[Bug]: `require('electron/package.json')` inside an electron process requires the `'electron'` module instead

### ISSUE THREAD

**Issue by RaisinTen** [electron/electron#32951]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Other (specify below)

### Operating System Version

all

### What arch are you using?

all

### Last Known Working Electron version

v9.4.4

### Expected Behavior

I would expect it to return the `package.json` file present inside the `electron` `node_modules` directory.

### Actual Behavior

It requires the `'electron'` module instead.

### Testcase Gist URL

https://gist.github.com/RaisinTen/dfe8c9ccc8345c656dcf0d21825c4b7f

### Additional Information

* Calling `require('electron/package.json')` in a Node.js process (`node` as well as `ELECTRON_RUN_AS_NODE=1 electron`) correctly requires the `package.json` file present inside the `electron` `node_modules` directory.
* Appending any characters after `'electron'` and passing it to `require()` would require the `'electron'` module.

**Comment by MarshallOfSound** [comment]
This isn't expected behavior.  The `electron` npm package is not what is loaded when you `require('electron')`.  The npm package is just a way to serve up prebuilt electron binaries, it doesn't contain any API / exported methods.

Loading the package.json is not valid / supported behavior in a packaged app.  If you want version information use `process.versions`

**Comment by RaisinTen** [comment]
@MarshallOfSound then shouldn't something like `require('electron/lol')` or `require('electron/package.json')` throw a `MODULE_NOT_FOUND` error at least? Also, shouldn't we document how electron's `require()` differs from the one coming from Node.js?

**Comment by RaisinTen** [comment]
reported again - https://github.com/electron/electron/issues/33014
