### ISSUE TITLE
[Bug]: Maximized window overlaps taskbar if taskbar is auto-hidden

### ISSUE THREAD

**Issue by GHKazza** [electron/electron#32957]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### What arch are you using?

x64

### Last Known Working Electron version

16.0.8

### Expected Behavior

Maximized window not covering the taskbar when the taskbar is set to auto-hide

### Actual Behavior

When the window is maximized and the taskbar is auto-hidden, you can't show the taskbar with mouse hovering, instead the cursor change to `resizing mode` when hover the bottom of the window trying to open the hidden taskbar

### Testcase Gist URL

https://gist.github.com/d03c0af4625eba907319ae959aa57a83

### Additional Information

I just noticed that the animations when minimizing, hiding or maximizing are not being done.

**Comment by jeremyspiegel** [comment]
This appears to have been fixed in 17.4.0/18.0.2.
