### ISSUE TITLE
[Bug]: Frameless BrowserWindow that is not resizable has no shadow

### ISSUE THREAD

**Issue by t57ser** [electron/electron#32955]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.985

### What arch are you using?

x64

### Last Known Working Electron version

17.0.0

### Expected Behavior

Frameless window should have shadow

### Actual Behavior

The window has no shadow

```
const { app, BrowserWindow } = require( "electron" )
app.whenReady().then(()=>{
	let main = new BrowserWindow({
		"height" : 600,
		"width" : 800,
		x: 100,
		y: 100,
		show: true,
		frame: false,
		resizable: false,
	});
})
```

### Additional Information

This broke with 17.0.1, quite likely with: https://github.com/electron/electron/pull/32692

**Comment by bruceauyeung** [comment]
electron:17.1.1
windows: 7/10
the problem exists even when `resizable` is `true`
