### ISSUE TITLE
[Bug]: `titleBarOverlay` prevent dragging the `BrowserWindow`

### ISSUE THREAD

**Issue by alefoll** [electron/electron#32966]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 21H2 (22000.527)

### What arch are you using?

x64

### Last Known Working Electron version

14.2.5

### Expected Behavior

The BrowserWindow should be draggable with `-webkit-app-region: drag`.

### Actual Behavior

Unable to move the BrowserWindow.

### Testcase Gist URL

https://gist.github.com/alefoll/1cd3b68937dad2e73ec04a55df634540

**Comment by cawa-93** [comment]
I can confirm this issue on Windows 10 19044.1566 and on electron 17.1.0

**Comment by Modjular** [comment]
I'm getting this bug as well:
 - Electron: `v17.1.0`
 - OS: Windows 10 `19043.1526`

it works fine on macos, and worked for both back in `v13.6.3` of Electron

**Comment by psycho-source** [comment]
Same issue. Windows 11 Build 22563.1. electron 17.1.0

**Comment by blakjak44** [comment]
Same issue here. ^

**Comment by workeffortwaste** [comment]
Having the same problem with 17.1.0

**Comment by alefoll** [comment]
It's fixed, thanks to #32871. You can test it in `v18.0.0-beta.2`.
Just wait for a new v16, v17 update that include:
> Fixed drag regions on WCO windows on Windows. https://github.com/electron/electron/pull/33202 (Also in https://github.com/electron/electron/pull/33201)
