### ISSUE TITLE
[Bug]: setContentProtection now longer works on Windows since Windows 11

### ISSUE THREAD

**Issue by timothylui** [electron/electron#32961]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 10.0.22000

### What arch are you using?

x64

### Expected Behavior

Capturing screen doesn't show windows which setContentProtection(true) has been set on

### Actual Behavior

As of Windows 11, this no longer works. It works fine if I go back to windows 10. This seems to affect all electron versions from 13 as far as I can tell

**Comment by mlaurencin** [comment]
[This issue](https://github.com/electron/electron/issues/32958) seems to related. The differences in working version numbers warrants separate issues to track though.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Please use [Electron Fiddle](https://github.com/electron/fiddle) to create a standalone (no external dependencies) testcase and publish it as a [gist](https://gist.github.com), then link to it here.

- Even if you have a code snippet or a git repository that show the testcase, please put it in a gist. This lets maintainers triage issues more effectively. It also ensures that we're testing the exact same issue that you're seeing!

- Please avoid external dependencies in the test. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.

- If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to the gist in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by gerhardberger** [comment]
According to this discussion: https://docs.microsoft.com/en-us/answers/questions/700122/setwindowdisplayaffinity-on-windows-11.html

This is an issue with Windows 11 and happening to certain non Win32 apps, so not sure how much we can do about it in Electron right now.

**Comment by Slapbox** [comment]
I don't know if that's the real cause @gerhardberger because `setContentProtection` was working for us on Windows 11 until the most recent update to the OS, I guess. Now it's totally busted.

@ckerr: repro: https://gist.github.com/275e7e5fff1a1075480b7cf82610e317 (but for an OS-specific issue of course)

Windows 11 build affected: 22000.675

**Comment by DanielMcAssey** [comment]
This also affects v16, a few of our users have reported this

**Comment by Slapbox** [comment]
Friendly bump.

Is there something else the community needs to do here? Can any Electron team members comment? This is a big issue for us. 

Also @timothylui your title should say "no longer" instead of "now longer."

**Comment by Slapbox** [comment]
Friendly bump. If this can't be fixed currently then the docs should be updated to reflect that this doesn't work on Windows 11.

**Comment by ckerr** [comment]
@Slapbox thanks for the bump; I didn't see the gist that you added. I'm removing the `blocked/needs-repro` tag.

**Comment by Slapbox** [comment]
Any updates on a possible solution for this?

**Comment by Slapbox** [comment]
Any news? Is there hope this will be fixed, or do we need to update our code to prevent showing this option to Windows 11 users?

**Comment by MarshallOfSound** [comment]
@Slapbox this is a bug in Windows 11, not a bug in Electron.  There's nothing we can without msft fixing `SetWindowDisplayAffinity` on Windows 11 🤷

**Comment by DanielMcAssey** [comment]
Not sure if people are aware, but I have been following this Q&A that also mentions the Windows 11 issue.

https://docs.microsoft.com/en-us/answers/questions/700122/setwindowdisplayaffinity-on-windows-11.html

**Comment by DanielMcAssey** [comment]
Bump

**Comment by Slapbox** [comment]
This is a really problematic issue to keep open for a year. It should either be addressed (which seems not possible according to the maintainers) or the documentation should be updated to address this limitation.

@ckerr

**Comment by Slapbox** [comment]
This appears to be resolved in my testing on 22.x and 23.x.

I know this was going to be closed as stale and I've now prevented that, but I wanted to confirm I'm seeing resolution (both on Win 11 21H2 and 22H2.)

**Comment by Beefal0** [comment]
My client has reported a similar issue, which matches your operating system version exactly. In my project, there are two windows that have setContentProtection(true) set. Interestingly, the client has reported that one of the windows is not being properly blocked from capture, while the other window is working correctly. Therefore, I suspect that the properties of the windows are set differently. Have you tried setting the backgroundThrottling property to different values for the windows to see if that improves the situation?

**Comment by Beefal0** [comment]
> My client has reported a similar issue, which matches your operating system version exactly. In my project, there are two windows that have setContentProtection(true) set. Interestingly, the client has reported that one of the windows is not being properly blocked from capture, while the other window is working correctly. Therefore, I suspect that the properties of the windows are set differently. Have you tried setting the backgroundThrottling property to different values for the windows to see if that improves the situation?

After a period of debugging, I found that calling setContentProtection(true) at the moment of window creation is successful on Windows 10.0.22000, but dynamically calling setContentProtection(true) during the window's lifetime does not take effect. As you mentioned, there is indeed a bug on Windows 11, but why is it possible to succeed in setting it during window creation? Does this indicate a vulnerability in Electron? Can anyone explain this phenomenon?

**Comment by mlaurencin** [comment]
It looks like this is working in currently supported versions, so I am going to go ahead and close this issue.

@Beefal0 You may have more luck asking your questions on [the Electron Discord server](https://discord.com/invite/electron). If you have a further problem after that on a currently supported version, feel free to create a new issue.

**Comment by Slapbox** [comment]
Setting it dynamically works fine for me on Windows 11. I should note that the window was initially created with contentProtection set to true. Does it work for you in that case @Beefal0? If so, that would probably be an Electron bug. Otherwise I don't know what to say since it's working here.

**Comment by Beefal0** [comment]
> Setting it dynamically works fine for me on Windows 11. I should note that the window was initially created with contentProtection set to true. Does it work for you in that case @Beefal0? If so, that would probably be an Electron bug. Otherwise I don't know what to say since it's working here.
Electron Version
21.3.3

Operating System Version
Windows 11 version 10.0.22000

I can confirm that calling setContentProtection(true) immediately after a window is successfully created, using the provided Electron and operating system versions, is effective. However, setting setContentProtection(true) dynamically after this point no longer works.

**Comment by Beefal0** [comment]
> Setting it dynamically works fine for me on Windows 11. I should note that the window was initially created with contentProtection set to true. Does it work for you in that case @Beefal0? If so, that would probably be an Electron bug. Otherwise I don't know what to say since it's working here.

Electron Version： 21.3.3
Operating System Version： Windows 11 version 10.0.22000
I can confirm that calling setContentProtection(true) immediately after a window is successfully created, using the provided Electron and operating system versions, is effective. However, setting setContentProtection(true) dynamically after this point no longer works.

**Comment by Beefal0** [comment]
Thank you for your response. I believe my Electron version is not the latest, but instead version 21.3.3. As I mentioned earlier, there seems to be a bug in Electron. I am interested in how you fixed this issue. Is there any record of the modified code? I would like to fix it on my version of Electron, which would be the most convenient solution for my clients.

@mlaurencin

**Comment by mlaurencin** [comment]
Given the elapsed time, it may have been fixed on the Electron side, or something upstream in Chromium may have fixed it. You may have luck using [Electron Fiddle](https://www.electronjs.org/fiddle) to narrow down to a potential solution. However, I would encourage upgrading to a supported version and reporting a new issue if you are still experiencing a problem.
