### ISSUE TITLE
[Bug]: When open app at the first time LocalStorage does not persist after killing process 

### ISSUE THREAD

**Issue by khanhnguyen3759** [electron/electron#32972]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21H1

### What arch are you using?

x64

### Expected Behavior

The local store should persist items even though the app is terminated as soon as the item was added.

### Actual Behavior

Nothing added to local storage

### Additional Information

**Step to reproduce:**

1. Clear folder **%APPDATA%/${APP_NAME}**
2. npm start or run the app after installation
3. localStorage setItem
4. kill the app by **Ctrl + C** or **taskkill /f /im ${APP_NAME}.exe /T**
5. open the app again

**Note:** This issue similar _https://github.com/electron/electron/issues/22048_ but it's happened when first time open the application

**Comment by gujinku** [comment]
Any update?

**Comment by khanhnguyen3759** [comment]
> Any update?

Still waiting...

**Comment by ThunderboltSmile** [comment]
> > Any update?
> 
> Still waiting...

Did you create BrowserWindow with a persist session ? https://www.electronjs.org/docs/latest/api/session#sessionfrompartitionpartition-options

**Comment by Anastassi** [comment]
Any update on that?

**Comment by khanhnguyen3759** [comment]
still occurs in the latest stable version electron 22.0.1

**Comment by khanhnguyen3759** [comment]
> > > Any update?
> > 
> > 
> > Still waiting...
> 
> Did you create BrowserWindow with a persist session ? https://www.electronjs.org/docs/latest/api/session#sessionfrompartitionpartition-options

hi @ThunderboltSmile 
yes, that working thanks, but how it's affected  to the old application if we provide a session, and why it's working with session?

**Comment by leohxj** [comment]
occurs on Electron 13.
