### ISSUE TITLE
[Bug]: Using the new titleBarOverlay with windows adds a weird line if transparent background is used

### ISSUE THREAD

**Issue by timothylui** [electron/electron#32975]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 10.0.22000

### What arch are you using?

x64

### Expected Behavior

Just display the window controls

### Actual Behavior

Window controls displayed with an extra line underneath and to the right

![Untitled](https://user-images.githubusercontent.com/22524825/154672243-000bf4b8-a6cd-4754-8c0b-f317b9bca9d2.jpg)

### Additional Information

This is with
`
titleBarStyle: "hidden",
titleBarOverlay: {
    symbolColor: 'white',
    color: 'rgba(0,0,0,0)'
},
`

**Comment by panther7** [comment]
Hover is broken too.

![hover](https://user-images.githubusercontent.com/3808250/169791728-89ef3ffa-b0d1-49db-9b99-ab3585709041.gif)

(Electron v17.4.2)

**Comment by lfpei** [comment]
I have the same situation, is there a solution?
