### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kuhlaid** [electron/electron#32989]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.5.2

### What operating system are you using?

Windows

### Operating System Version

Version	10.0.19043 Build 19043

### What arch are you using?

x64

### Expected Behavior

I use both Visual Studio Code and Azure Data Studio (both Electron based apps). These apps are loaded on an office computer I connect to remotely using Windows remote desktop. When I disconnect from my remote desktop session and reconnect I would expect the apps to behave normally.

### Actual Behavior

I use both Visual Studio Code and Azure Data Studio (both Electron based apps). These apps are loaded on an office computer I connect to remotely using Windows remote desktop. When I disconnect from my remote desktop session and reconnect, these apps will usually have the same UI issues where I can't close the windows unless I go to the taskbar, right-click the app, and tell them to close (the close button in the top right simply stops responding). Also the 'code' views of the apps get split, with the left side frozen and the right side scroll-able, as well as hovering over the menu items causes the menus to stick to the window and not close after the cursor loses focus. Once I restart the apps, they are fine during the current remote desktop connection but if I disconnect (leaving the remote computer and apps running) then reconnect, the apps usually have the issues reappear and I'm forced to restart the apps to clear the issue.

### Additional Information

I know, this is not an easy issue to troubleshoot since it involves remote desktop. Attached is a screencast of how Visual Studio Code acts after reconnecting to the remote computer. The menu items are not as 'sticky' as they can be at times (it is random), but the video does show the screen split with a small left section of the code view frozen when scrolling or trying to select text. Also I am clicking on the minimize and close buttons on the top right of the window, but they do not respond.

https://user-images.githubusercontent.com/41551429/154734968-1bef9a20-5bec-47fe-a88e-50e25d7aba1d.mp4

.

**Comment by miniak** [comment]
If you have issues with a particular product, such as Visual Studio Code, it needs to be reported there.
