### ISSUE TITLE
[Bug]: Frameless window has sharp corners on Win11 when not resizable

### ISSUE THREAD

**Issue by jonasmusall** [electron/electron#32981]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Education (Build 22000.527)

### What arch are you using?

x64

### Last Known Working Electron version

17.0.0

### Expected Behavior

A window with options `resizable: false, frame: false` should have the default Win11 rounded corners.

![grafik](https://user-images.githubusercontent.com/69427105/154686849-1d08198e-7c0b-4304-b4ae-eba581e4ac21.png)

### Actual Behavior

Frameless windows have sharp corners if resizable is set to false. Happens if created with `resizable: false` or calling `setResizable(false)` at any point after creation.

![grafik](https://user-images.githubusercontent.com/69427105/154687575-11e08afd-3a67-4cc8-9cab-dd5e833a1ab0.png)

### Testcase Gist URL

https://gist.github.com/jonasmusall/aa0116672e17962f00c62f8c96db2ec1

**Comment by jonasmusall** [comment]
Maybe this has to do with a23c93a?

**Comment by mitchchn** [comment]
Hey @codebytere, I don't know if you've had a chance to look at this yet, but I'd like to propose reverting https://github.com/electron/electron/pull/32692.

The bug which it fixes is easily worked around by hiding the window until `ready-to-show` is fired, which is a best practice that's already recommended by the Electron docs to make windows load smoothly.

On the other hand, the bugs it introduces are not possible to work around by any means, including this issue and https://github.com/electron/electron/issues/32993.

Please let me know if you think reverting that MR would be acceptable. I am happy to open the MR.

**Comment by miniak** [comment]
@MarshallOfSound should we close this one as the PR was merged?
