### ISSUE TITLE
[Bug]: Directory traversal using fetch() in loadFile() loaded webpage

### ISSUE THREAD

**Issue by sinsong** [electron/electron#32988]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 20H1

### What arch are you using?

x64

### Last Known Working Electron version

17.0.1

### Expected Behavior

When app's webpage load by `BrowserWindow.loadFile()`, using `fetch()` request resource, I expect it could't read file that outside of project root directory or `app.asar` itself.

### Actual Behavior

Such as `fetch('../../../../../../../../../../home/username/.ssh/known_hosts')`, F12 Network panel shows request URL is `file:///home/username/.ssh/known_hosts` and file content available.

`fetch()` will provide file content if:
* guess a right path.
* electron(or user) have permission.

I have test electron-forge built package on Windows 10 and Arch Linux in VM.

### Additional Information

First of all, I am looking for solution that let electron use vite built files. Vite use es module, `loadFile()` don't support.

I found a solution, registe custom protocol and grant some privilege. I use `protocol.registerFileProtocol()` and `protocol.registerSchemesAsPrivileged()` with `secure: true` and `standard: true`. Load webpage using `loadURL('app://renderer/index.html')`, it works. And I am afraid of my code will provide files that outside the project. I provide `supportFetchAPI: true` and test and get file content. I also find that if provide `standard: true`, the incoming request pathname of my custom protocol handler is safe and `../../..` are removed. To be carefull, I wrote:

```js
function registerProtocol()
{
  protocol.registerFileProtocol('app', (request, callback) => {
    // console.log(`app-protocol: ${request.url}`);
    let requrl = new URL(request.url)
    let reqpath = requrl .pathname
    let boundary = path.join('/', reqpath) // used for prevent ../.. attack
    
    callback({ path: path.join(app.getAppPath(), 'dist/renderer', boundary) })
  })
}
```

Because of curiosity, I test `fetch('../../path...')` in new project's F12 console, and I get file content.

## code

the code of create the window in `main.js`:

```js
function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: { sandbox: true }
  })
  mainWindow.loadFile('index.html')
  mainWindow.webContents.openDevTools({mode: 'detach'})
}
```

the code of webpage `index.html`:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'self'; script-src 'self'"
    />
    <link href="./styles.css" rel="stylesheet" />
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>

    <p>Which file do you like?</p>
    <div class="bar">
      <input type="text" id="path" spellcheck="false" />
      <button id="load">load</button>
    </div>
    <pre id="reqpath"></pre>
    <pre id="output"></pre>

    <script src="./renderer.js"></script>
  </body>
</html>
```

additional stylesheet:

```css
.bar
{
  display: flex;
}

#path
{
  width: 100%;
  margin-right: 5px;
}

#load
{
  flex: none;
}
```

the code of `renderer.js`:

```js
let output = document.getElementById('output')
let path = document.getElementById('path')
let rp = document.getElementById('reqpath')
let load = document.getElementById('load')

load.addEventListener('click', () => {
  // prepare for directory traversal
  let escaper = (()=>{
    let p = '';
    for (let i = 0; i < 20; ++i)
      p = p + '../'
    return p
  })()

  let reqpath = escaper + path.value
  rp.textContent = reqpath

  // fetch for file content
  fetch(reqpath)
    .then(async(res) => {
      output.textContent = await res.text()
    })
    .catch((reason) => {
      output.textContent = reason
    })
})
```

## result

![electron](https://user-images.githubusercontent.com/22849803/154702885-fcde1ff5-9545-4612-8ed7-f08ede2d4ee7.png)

![dev](https://user-images.githubusercontent.com/22849803/154702954-0e34edc0-2b9d-4638-b20e-050a891d6284.png)

**Comment by MarshallOfSound** [comment]
This is expected behavior, if you want to load a file and _not_ give it access to the filesystem on which it resides you will need to use a custom file protocol and handle the requests / paths it can access manually.

https://www.electronjs.org/docs/latest/api/protocol#protocolregisterfileprotocolscheme-handler
