### ISSUE TITLE
[Bug]: disable-hid-blocklist does not work

### ISSUE THREAD

**Issue by xltan** [electron/electron#32996]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12.2.1

### What arch are you using?

x64

### Expected Behavior

can receive keyboard inputreport when using disable-hid-blocklist, as the documentation advised.

### Actual Behavior

can not receive keyboard/mouse inputreport

### Additional Information

https://chromium.googlesource.com/chromium/src/+/main/services/device/hid/hid_connection.cc
Looking at the function body of `HidConnection::ProcessInputReport` seems the option cannot affect the return value of `IsReportIdProtected`, the function will fallback to `IsAlwaysProtected`. So the inputreport of keyboard will always be protected here.

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by xltan** [comment]
Hi, I had already point you where the bug is located in the **Additional Information
**, I also checked the modified code (Just make `IsReportIdProtected` return to `false`) will make things work as intended (though not a good solution), electron has a huge codebase, this part of code has quite different safety direction with chrome and I am quite new, sorry I can not make a pull request for this.

**Comment by codebytere** [comment]
@xltan i'm looking for a _reproducible sample_ - that has nothing to do with understanding the electron core codebase or making a pull request. In the comment above, I specified that i am looking for an Electron app that I can run to reproduce the issue. Please reread the comment above:

> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com/) that Electron maintainers can use.

so we can proceed with triaging this.

**Comment by xltan** [comment]
any code with keyboard/mouse usage inputreport can reproduce easily, I think anyone know about this codebase can know what I am saying.

**Comment by xltan** [comment]
https://gist.github.com/xltan/3e830945bbef540567ff15d066f6b648 this is the gist

**Comment by xltan** [comment]
@codebytere Hi, can you remove the blocked/need-repo, so someone can look into it, thanks!

**Comment by dmilin1** [comment]
@xltan I'm in a similar situation. Did you ever find a fix to get a mouse or keyboard to work with WebHID?

**Comment by xltan** [comment]
@dmilin1 currently, you'll have to patch electron yourself as I said above

> Hi, I had already point you where the bug is located in the **Additional Information**, I also checked the modified code (Just make `IsReportIdProtected` return to `false`) will make things work as intended (though not a good solution), electron has a huge codebase, this part of code has quite different safety direction with chrome and I am quite new, sorry I can not make a pull request for this.

**Comment by dmilin1** [comment]
Please reopen. This is still a problem.

**Comment by Astrojoinl** [comment]
@xltan How can you patch the bug yourself?

> @dmilin1 currently, you'll have to patch electron yourself as I said above
> 
> > Hi, I had already point you where the bug is located in the **Additional Information**, I also checked the modified code (Just make `IsReportIdProtected` return to `false`) will make things work as intended (though not a good solution), electron has a huge codebase, this part of code has quite different safety direction with chrome and I am quite new, sorry I can not make a pull request for this.

**Comment by Astrojoinl** [comment]
This is an electron fiddle gist that can show the bug:
https://gist.github.com/e9ffb42ec9442471f815c672215c4b0e
