### ISSUE TITLE
[Bug]: the BrowerView can't show in the version 17.0.1

### ISSUE THREAD

**Issue by zhang357622852** [electron/electron#32992]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

17.0.1

### Expected Behavior

the electron 17.0.1 use BrowerView in main process, can't show. must enable frame:false can show BrowerView

### Actual Behavior

    let view = new BrowserView()

    view.setBounds({ x: 100, y: 100, width: 900, height: 600 })

    view.webContents.loadURL("https://www.baidu.com")

    mainWindow.setBrowserView(view)

![QQ图片20220219161201](https://user-images.githubusercontent.com/18215765/154792769-bf015bcc-d4a0-41f3-a11a-cd636da4a0c4.png)

**Comment by he-jialin** [comment]
I had the same problem, is enableRemoteModule deprecated in version 17.0.1? shows that the resource is loaded but the page is blank

**Comment by codebytere** [comment]
You need to set the BrowserView first. 

```js
let view = new BrowserView()
  mainWindow.setBrowserView(view)
  view.setBounds({
    x: 100,
    y: 100,
    width: 900,
    height: 600
  })
  view.webContents.loadURL("https://www.baidu.com")
```

works just fine.

**Comment by feibi** [comment]
> You need to set the BrowserView first.
> 
> ```js
> let view = new BrowserView()
>   mainWindow.setBrowserView(view)
>   view.setBounds({
>     x: 100,
>     y: 100,
>     width: 900,
>     height: 600
>   })
>   view.webContents.loadURL("https://www.baidu.com")
> ```
> 
> works just fine.

The same problem, It's not work.

**Comment by asineth0** [comment]
Same issue here, works when trying to load https://electronjs.org (about 80% of the time), but does not work when trying to load https://google.com for example.

**Comment by asineth0** [comment]
I've done a bit of testing, and I have noticed:

- Works every time on Electron 12.x (`pnpm i -D electron@^12`) .
- Doesn't work on Electron 13.x (`pnpm i -D electron@^13`).

So it seems this bug has been around a while.

**Comment by asineth0** [comment]
Also, relevant issue: #31424.
