### ISSUE TITLE
[Bug]: macOS Monterey 12.2.1 can not install electron

### ISSUE THREAD

**Issue by fbwang** [electron/electron#32997]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.2.1

### What arch are you using?

x64

### Last Known Working Electron version

Uknown

### Expected Behavior

electron installed successfully

### Actual Behavior

[~] sudo npm i -D electron@latest                                     16:11:06 
Password:
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code 1
npm ERR! path /Users/crystal/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Error: EACCES: permission denied, mkdir '/Users/crystal/Library/Caches/electron/10682f6117b498b4fe65474ab77786527a772f7b6c11aa3884e6e5892540f2b3'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/crystal/.npm/_logs/2022-02-20T08_23_43_716Z-debug-0.log

**Comment by fbwang** [comment]
tried electron 12.0.0 also fail.
So maybe OS policy change cause this

**Comment by timothylui** [comment]
Why are you using sudo?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by JaosnHsieh** [comment]
Having same error on 

`macOS Big Sur v11.3.1`
`node v16.13.2`
`npm v8.1.2`

`sudo npm install electron --unsafe-perm=true` doesn't work.

tried [reinstall npm](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) and upgraded to node.js v16.4.2, doesn't work.
