### ISSUE TITLE
[Bug]: Frameless windows have no animation on Windows

### ISSUE THREAD

**Issue by mxmou** [electron/electron#32993]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 (21H2, build 22000.493)

### What arch are you using?

x64

### Last Known Working Electron version

16.0.8

### Expected Behavior

Frameless windows would show an animation when minimized or maximized.

### Actual Behavior

There is no animation.

### Testcase Gist URL

https://gist.github.com/mxmou/cb865ea440a2bbbd21673fa40cf39bb4

**Comment by pejman1** [comment]
same issue in electron version 16.0.9 and 17.1.0

**Comment by omarfouad** [comment]
Same issue in electron 15.4.0.

**Comment by McSon2** [comment]
Same here

**Comment by xpirt** [comment]
I confirm the issue happening on 17.1.0 version.

**Comment by Levminer** [comment]
Still present in 18.0.0.

**Comment by pejman1** [comment]
@ckerr 
it is really important bug after two major releases 
the issue has not fixed yet . version 18.0.1

**Comment by DogFoxX** [comment]
I also upgraded to 18.0.1 and still had this issue... but after trying (and not succeeding) [this answer on #33152](https://github.com/electron/electron/issues/33152#issuecomment-1059700797), the issue resolved itself.
I cannot say what happened, but I removed the code suggested by that answer, and animations for Minimize and Maximize was back. Could it be that there is underlying code for the animations that are being ignored?

**Comment by pejman1** [comment]
> I also upgraded to 18.0.1 and still had this issue... but after trying (and not succeeding) [this answer on #33152](https://github.com/electron/electron/issues/33152#issuecomment-1059700797), the issue resolved itself. I cannot say what happened, but I removed the code suggested by that answer, and animations for Minimize and Maximize was back. Could it be that there is underlying code for the animations that are being ignored?

it has been fixed in the latest version 18.0.2

**Comment by DogFoxX** [comment]
@pejman1 Ah right, thanx. Just did the update.

**Comment by seesemichaelj** [comment]
To gather all the information in one spot, as I currently understand, #33599 fixes this issue. Below is how this PR has propagated to various versions

Fix released:
- `17.4.0` (#33611)
- `18.0.2` (#33610)

Fix merged but not released:
- `16.x.y` (#33607)
- `19.x.y` (#33609)

Fix pending merge:
- `15.x.y` (#33608)

**Comment by mbeissinger** [comment]
I'm still seeing this issue on version `21.2.11`

**Comment by seesemichaelj** [comment]
@mbeissinger you should open a new issue for that
