### ISSUE TITLE
[Bug]: electron17 tray.setPressedImage invalid

### ISSUE THREAD

**Issue by he-jialin** [electron/electron#33008]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.2.3

### What arch are you using?

x64

### Last Known Working Electron version

2.0.7

### Expected Behavior

Click the tray menu to change icons

### Actual Behavior

No change on tray icon click

### Additional Information

```
function buildTray() {
    let icon = null
    let iconDark = null
    if (process.platform == 'darwin') {
        let { nativeTheme } = require('electron')
        let iconLight = nativeImage.createFromPath(path.resolve(__dirname, '../assets/img/light/icon_light.png'))
        iconDark = nativeImage.createFromPath(path.resolve(__dirname, '../assets/img/dark/icon_dark.png'))
        if (nativeTheme.shouldUseDarkColors) {
            //dark
            icon = iconDark
            console.log("dark")
        } else {
            //light
            icon = iconLight
            console.log("light")
        }
    } else {
        icon = nativeImage.createFromPath(path.resolve(__dirname, '../assets/img/icon_win.png'));
    }
    if (null == tray) {
        tray = new Tray(icon)
    } else {
        tray.setImage(icon)
    }
    if (process.platform == 'darwin') {
        console.log("setPressedImage.iconDark")
        tray.setPressedImage(iconDark)
    }
}
```

**Comment by he-jialin** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

https://gist.github.com/3af03019cd2fc9f0571f33910e47bb6f

**Comment by he-jialin** [comment]
@codebytere Hi, haven't merged into the main branch yet?

**Comment by he-jialin** [comment]
Hi，Why is there no progress?

**Comment by codebytere** [comment]
@he-jialin we are an open source project with 1500 issues and a small core team. It would behoove you to consider being patient as we are doing our best.
