### ISSUE TITLE
[Bug]: BrowserWindow.flashFrame(true) does not work in VMware VDI running on Windows Server 2016

### ISSUE THREAD

**Issue by torycl** [electron/electron#33033]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

8.x.y, 10.x.y, 16.x.y

### What operating system are you using?

Windows

### Operating System Version

VMware VDI + Windows 10 18363.1500 running in Windows Server 2016 host

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

BrowserWindow.flashFrame(true) flashes the icon on Windows taskbar

### Actual Behavior

BrowserWindow.flashFrame(true) does nothing

### Testcase Gist URL

https://gist.github.com/f3daf2983a9d9e395f323d15c5936055

### Additional Information

I understand this is quite unusual environment.
I can also report flashFrame works ok on Windows Server 2019. The bug occurs only on Windows Server 2016.

**Comment by Hakon1014** [comment]
####does not work in VMware VDI running on Windows Server 2016
We also encountered it on our side, and it was very uncomfortable. After upgrading from the nw framework to electron, we encountered this problem。
Please, does anyone know a solution? Or when will a resolved version be released?
Thank you very much！！！

**Comment by torycl** [comment]
Unfortunately, I don't know about any solution. I can confirm the Electron properly calls [WinAPI function](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-flashwindowex) with right parameters but it has no effect in this environment. 

So we have decided to document it as known issue [in product documentation](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#notifications) and suggest our users to use at least Windows Server 2016 as host.

**Comment by oohusl** [comment]
You can try to call flashFrame two times. @torycl

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump
