### ISSUE TITLE
[Bug]: How to get  protocol URL argument when windows app opens for the first time?

### ISSUE THREAD

**Issue by RohanNegiUI** [electron/electron#33032]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.2.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

ia32

### Expected Behavior

https://www.electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app
As per the above doc, we can process deep link URL protocol argument only someone tried to run a second instance.

For windows, there should be an event that can launch Your Electron App From A URL when the windows app open for the first time.

Could you please provide a way to handle the above issue?

### Actual Behavior

For windows, there should be an event that can launch Your Electron App From A URL when the windows app open for the first time.

**Comment by gaoshang212** [comment]
you can register URL protocol in Installation。 

you can custom nsis script if use electron-builder [https://www.electron.build/configuration/nsis#custom-nsis-script](url)

for example：
``` nsis
!define SCHEMENAME "app" # your URL Protocol, e.g. electron-fiddle

!macro customInstall
  DetailPrint "Register ${SCHEMENAME} URI Handler"
  DeleteRegKey HKCR "${SCHEMENAME}"
  WriteRegStr HKCR "${SCHEMENAME}" "" "${PRODUCT_NAME}"
  WriteRegStr HKCR "${SCHEMENAME}" "URL Protocol" ""
  WriteRegStr HKCR "${SCHEMENAME}\DefaultIcon" "" "$INSTDIR\${APP_EXECUTABLE_FILENAME}"
  WriteRegStr HKCR "${SCHEMENAME}\shell" "" ""
  WriteRegStr HKCR "${SCHEMENAME}\shell\Open" "" ""
  WriteRegStr HKCR "${SCHEMENAME}\shell\Open\command" "" "$INSTDIR\${APP_EXECUTABLE_FILENAME} %1"
!macroend

!macro customUnInstall 
  DeleteRegKey HKCR "${SCHEMENAME}"
  ReadRegStr $0 HKCR "${SCHEMENAME}" ""
  DeleteRegKey HKCR "$0"
!macroend
```

**Comment by gaoshang212** [comment]
you can use _process.argv_ to get arguments when app opens for the first time on windows.

**Comment by mikey-mo** [comment]
@RohanNegiUI were you ever able to figure out a solution for this?  Running into the same issue on Linux where I may want to pass some args in when app first loads.
