### ISSUE TITLE
[Bug]: clipboard failed to write bookmark on windows

### ISSUE THREAD

**Issue by NoirePerrorist** [electron/electron#33046]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10 professional 21H1 19043.1348

### What arch are you using?

x64

### Last Known Working Electron version

18.0.0-alpha.3

### Expected Behavior

I expect clipboard.writeBookmark or clipboard.write would successfully write bookmark to clipboard on window as well as on mac.

### Actual Behavior

These two apis failed on windows but worked well on mac.
![image](https://user-images.githubusercontent.com/26524561/155258011-2677a5eb-59e3-45d0-9201-abf49012cb0e.png)

### Testcase Gist URL

https://gist.github.com/NoirePerrorist/eb25d0583e3ab774672d039f1da561f1

**Comment by codebytere** [comment]
@NoirePerrorist could you please elaborate?

Output on macOS:
<img width="511" alt="Screen Shot 2022-02-23 at 11 16 11 AM" src="https://user-images.githubusercontent.com/2036040/155299863-58720ad2-064d-4773-8735-88b25e731153.png">

Output on Windows:
<img width="529" alt="Screen Shot 2022-02-23 at 11 16 17 AM" src="https://user-images.githubusercontent.com/2036040/155299888-e9713eeb-c9e3-45a4-941a-ecb5b07bce55.png">

Are these not the same?

**Comment by codebytere** [comment]
Hmm - looks like Chromium may have actually changed this on purpose 🤔 
https://chromium-review.googlesource.com/c/chromium/src/+/3108445

**Comment by NoirePerrorist** [comment]
So... Will this be fixed to ensure the consistency of api, or just follow chromium, consider this as a difference of bookmark format between window and Mac system?
