### ISSUE TITLE
[Bug]: desktopCapturer in Mac window fullscreen does not show

### ISSUE THREAD

**Issue by roy2651** [electron/electron#33047]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.5.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Monterey 12.2.1

### What arch are you using?

x64

### Expected Behavior

I use desktopCapturer api such code like 
```
 startCaptureDesktop() {
    return new Promise((resolve, reject) => {
      const desktopCapturer = electron.desktopCapturer
      desktopCapturer
        .getSources({
          types: ['window', 'screen']
        })
        .then((sources) => {
          console.log('sources:',sources)
          let screenArrary = []
          let applicationsArray = []
          for (let item of sources) {
            if (!item.id) continue
            if (item.id.indexOf('screen') != -1) {
              let screen = Object.create(null)
              screen.id = item.id
              screen.name = item.name
              screen.thumbnail = item.thumbnail.toDataURL()
              screenArrary.push(screen)
            } else if (item.id.indexOf('window') != -1) {
              let applications = Object.create(null)
              applications.id = item.id
              applications.name = item.name
              applications.thumbnail = item.thumbnail.toDataURL()
              applicationsArray.push(applications)
            }
          }
          const e = {
            screenArrary,
            applicationsArray
          }
          resolve(e)
        })
        .catch((err) => {
          reject(err)
        })
    })
  }
```
<img width="918" alt="image" src="https://user-images.githubusercontent.com/14157170/155259464-712d210a-8dc4-49f6-b38e-cdd5541e94a4.png">

### Actual Behavior

but when I make a window（such as command） fullscreen ，and soureces return this
<img width="937" alt="image" src="https://user-images.githubusercontent.com/14157170/155259541-4c75f2d3-62a4-431f-be19-467937c20b91.png">

**Comment by codebytere** [comment]
@roy this is unfortunately expected behavior - see https://github.com/electron/electron/issues/17767#issuecomment-495437137. It is a Chromium design decision.
