### ISSUE TITLE
[Bug]: app.configureHostResolver cause crash

### ISSUE THREAD

**Issue by gadfly3173** [electron/electron#33045]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.9 & 17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21H1 19043.1526 | Windows Feature Experience Pack 120.2212.4170.0

### What arch are you using?

x64

### Expected Behavior

electron start

### Actual Behavior

![image](https://user-images.githubusercontent.com/28685179/155257348-7632cae9-b816-49b4-b9fa-13395fabb34b.png)

console: 
```bash
> Executing task: npm run start <


> electron-quick-start@1.0.0 start D:\project\electron-test\electron-quick-start
> electron .


[24016:0223/112700.404:ERROR:crashpad_client_win.cc(814)] not connected
```

reproduction code: 
```js
app.configureHostResolver({
  // other options cause the same issue
  secureDnsMode: 'off',
})
```

**Comment by nornagon** [comment]
`app.configureHostResolver` must be called after the `ready` event has fired, as noted in the docs: https://www.electronjs.org/docs/latest/api/app#appconfigurehostresolveroptions
