### ISSUE TITLE
[Bug]: clipboard.readImage takes far more time in 16-x-y than it did before 15-x-y

### ISSUE THREAD

**Issue by NoirePerrorist** [electron/electron#33055]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10 professional 21H1 19043.1348

### What arch are you using?

x64

### Last Known Working Electron version

18.0.0-alpha.3

### Expected Behavior

after update electron from 14-x-y to 16.0.8. I found that clipboard.readImage take about 100 times more time on windows and 10 times on mac. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/26524561/155318337-d50481c5-5b6e-4bb6-9f9a-e0f2a1c0d231.png)
This is the test result on my windows pc, a 3M jpeg in clipboard takes 2 seconds to generate NativeImage object. On mac it's a bit better but still, take 10 times more time than it did on version 14-x-y.
This could lead to a block in main process. Does Electron do some unnecessary transforming stuff when generate the NativeImage object?

### Testcase Gist URL

https://gist.github.com/783e7e62bf8ae0a29725bac8eb03fa9e

**Comment by codebytere** [comment]
@NoirePerrorist this is unfortunately likely to be collateral damage from a massive refactor that Chromium has been doing upstream in the clipboard code. We can look into it but it's also likely we may end up refactoring this module to adapt for these changes in the near future.

**Comment by aprilandjan** [comment]
This makes the clipboard api hard to use in real user-cases 😭
