### ISSUE TITLE
[Bug]: Can't resize the BrowserView correctly using the top edge of the window.

### ISSUE THREAD

**Issue by CentRa-Linux** [electron/electron#33056]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1, 16.0.6

### What operating system are you using?

Ubuntu

### Operating System Version

KDE Neon 5.24 User Edition

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

The BrowserView will resize and fill the whole window.

### Actual Behavior

The BrowserView resizes correctly with the side and bottom handles, but not with the top handle if you move the window a little fast.

https://user-images.githubusercontent.com/68494279/155705291-5f835464-f166-4e8a-b8f5-3ad7c4ffec63.mp4

### Testcase Gist URL

https://gist.github.com/46fe22164419a1a7a34bf2ba445df1d6

**Comment by Slapbox** [comment]
"Video can't be played because the file is corrupt"

**Comment by CentRa-Linux** [comment]
It looks like the file was too big, so I'll send it again. Sorry about that.
By the way, can someone who has Linux environment please verify my fiddle?
https://user-images.githubusercontent.com/68494279/155705291-5f835464-f166-4e8a-b8f5-3ad7c4ffec63.mp4

**Comment by pushkin-** [comment]
can't repro in Electron 21
