### ISSUE TITLE
[Feature Request]: Is it possible to make the Chromium dependency optional?

### ISSUE THREAD

**Issue by distributev** [electron/electron#33050]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

and, for people which choose so, to get lightweight bundle sizes because the user’s operating system’s web browser library will be used instead of Chromium?

when I read articles as the below I'm wondering if Chromium is a "all or nothing" dependency for Electronjs or if Electron itself can be made lighter for people which prefer not to bundle Chromium.

"According to the above comparison, Tauri and Neutralino.js perform better than Electron. Electron applications consume a lot of disk space because each application is bundled with Chromium and Node. On the other hand, Tauri and Neutralino.js have surprisingly lightweight bundle sizes because those frameworks are reusing the user’s operating system’s system web browser library.

Electron allows you to ship a desktop application comfortably, but it will create critical performance issues that will cause frustration of users. Therefore, it’s time to look for an alternative."

Source: 

https://blog.logrocket.com/why-use-electron-alternative/

### Proposed Solution

make Chromium an optional dependency in Electron, every user has a web browser which can be reused and this seems a good way to package Electonjs applications also (Chromium should still remain as a valid option, for people which prefer to bundle Chromium).

### Alternatives Considered

[Tauri](https://tauri.studio/)

**Comment by MarshallOfSound** [comment]
> make Chromium an optional dependency in Electron

This is not technically possible

> but it will create critical performance issues

This is fundamentally wrong, the performance of your app is independent of Electron in most cases.  At the end of the day your app is a website, if your HTML / JS performs poorly in one browser engine it will perform poorly in all. In fact, on Windows the OS browser engine is Chromium anyway.

Refs: https://www.electronjs.org/blog/webview2

**Comment by distributev** [comment]
How is 'This is not technically possible'?

What Tauri is doing that ElectronJS cannot technically do?

**Comment by MarshallOfSound** [comment]
> What Tauri is doing that ElectronJS cannot technically do?

It is a completely different technical approach, Electron is fundamentally powered by Chromium.  It's not like we just call Chromium.start.  The entire event loop, process model, node.js integration, etc. is all tied into Chromium itself.

**Comment by distributev** [comment]
Thank you for giving more details, I understand that this might be difficult to implement in practice.

Embedding Chromium has as an advantage that the app will always run no matter what the user has or does not have installed on his system, for instance running on older versions of Windows with older browsers. 

Using an existing browser from the user's computer (like a shared library) has the advantage that the bundle size is smaller however sometimes the app might not work when the existing shared browser/library is not compatible - it is the same with all the other software dependencies bundling everything inside is always a safer bet but increases the bundle size.

When packaging Java applications people have the option to either build a "fat jar" containing all dependencies inside either to dynamically link to external jar libs and to keep the application's jar lighter. With C/C++ it is the same with static/dynamic linking, .NET is the same and so on.

I believe that it makes sense to support both options with Electron too. If this is even possible or how much effort will be involved to achieve this I don't know. 

The main selling point of solutions like Tauri is now "Build smaller" apps - https://tauri.studio/
