### ISSUE TITLE
[Bug]: titleBar disappareed on macOS while eval "win.setFullScreen(true);win.hide();win.show()"

### ISSUE THREAD

**Issue by zhaozhongyu** [electron/electron#33088]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.10

### What operating system are you using?

macOS

### Operating System Version

11.6

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

<img width="585" alt="image" src="https://user-images.githubusercontent.com/8148957/155829815-1e44d300-6e89-46e9-b6b2-56fb59161c3c.png">

### Actual Behavior

<img width="594" alt="image" src="https://user-images.githubusercontent.com/8148957/155829841-d39df5cc-7977-461b-af49-e2ba929f565e.png">

### Additional Information

 
```
const {app, BrowserWindow} = require('electron')
const path = require('path')
const remoteMain = require('@electron/remote/main');
remoteMain.initialize();

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    fullscreen: true,
    fullscreenable: true,
    titleBarStyle: 'hidden',
    trafficLightPosition: {x: 8, y: 11},
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      webSecurity: false,
      nodeIntegration: true,
      enableRemoteModule: true,
      contextIsolation: false,
      spellcheck: true,
    }
  })
  remoteMain.enable(mainWindow.webContents);

  // and load the index.html of the app.
  mainWindow.loadFile('./index.html')
  setTimeout(() => {
    mainWindow.hide();
    mainWindow.show();
  }, 5000);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
}
```

**Comment by VerteDinde** [comment]
Repro Gist: https://gist.github.com/e62d1917c8a20f594c4235661f37b05e

@zhaozhongyu I was able to successfully repro this on 17.1.0 on Monterey 12.0.1. It looks like when the window is initially set, the title bar reveals itself when I mouse over the top bar. However, if I leave the window full screen, swipe away, and swipe back, the title bar is now permanently gone.

This seems to repro as far back as 14.0.0, so it looks like it's been present for some time.

**Comment by sohobloo** [comment]
Call `win.hide()` on a fullscreen window will also cause a black screen.

Is there any way to quit fullscreen on hide?
call `win.setFullscreen(false)` before `win.hide()` will not hide the window.
and strange thing that enter fullscreen will fire a `win.on('hide')` event.
