### ISSUE TITLE
[Bug]: session.defaultSession.getBlobData(payload.blobUUID) always pending

### ISSUE THREAD

**Issue by microwugui** [electron/electron#33081]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.x.y ~ 17.x.y

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

17.x.y

### Expected Behavior

`session.defaultSession.getBlobData(payload.blobUUID)` can resolve a buffer

### Actual Behavior

`session.defaultSession.getBlobData(payload.blobUUID)` always pendding

### Additional Information

I use electron.protocol.registerStreamProtocol and upload a FormData with blob like this

```
document.body.innerHTML = `<input type="file"/>`;
document.body.firstElementChild.onchange = () => {
  var file = document.body.firstChild.files[0];
  var f = new FormData();
  f.append("file.jpg", file);
  const xhr = new XMLHttpRequest();
  xhr.open("POST", "/seeeeea");
  xhr.send(f);
};
```

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug by checking your test against different OSes and Electron versions.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
