### ISSUE TITLE
startup time is much slower in 16.0.7 than it was in 11.3.0

### ISSUE THREAD

**Issue by noob000** [electron/electron#33083]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Recently, I update an electron app which used to play music and broadcast from electron version11.3.0 to electron version16.0.7.
After update,I noticed that the startTime obviously slower than before.(on m1 mbp, both build use arm electron)
I console the mainProcess and rendererProcess create time , then  i find that the higher version always cost more 1s on mainProcess create,the old one need about 0.16s and the new one need 1.20s.(after maybe 50 times test used Spectron). 
Time costed  on rendererPrcoess-create and page render don't have too much difference.
So i would like to know ,  what cause the new version app need to cost more 1s to create mainProcess.And  could you give some advice on how to reduce the mainPrcoess create time.

### Proposed Solution

No solution yet

### Alternatives Considered

No solution yet

**Comment by ckerr** [comment]
Hey @noob000, thanks for reporting this issue. I'm not seeing any delay in startup when launching Electron's default app between versions 11 and 16. I don't know what music app you're looking at; and the Electron maintainer team is so small that we generally don't have time to do triage on third-party code.

Would it be possible for you to create a testcase based on https://github.com/electron/electron-quick-start that demonstrates the bug, e.g. a small self-contained testcase that starts up in 0.16s in Electron 11 but takes >1s on 16.0.7? That would make it easier to try and track down this issue.

If you suspect it's an issue in the app's code and would like to know how to update it, you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electronjs) a try.

**Comment by noob000** [comment]
> Hey @noob000, thanks for reporting this issue. I'm not seeing any delay in startup when launching Electron's default app between versions 11 and 16. I don't know what music app you're looking at; and the Electron maintainer team is so small that we generally don't have time to do triage on third-party code.
> 
> Would it be possible for you to create a testcase based on https://github.com/electron/electron-quick-start that demonstrates the bug, e.g. a small self-contained testcase that starts up in 0.16s in Electron 11 but takes >1s on 16.0.7? That would make it easier to try and track down this issue.
> 
> If you suspect it's an issue in the app's code and would like to know how to update it, you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electronjs) a try.

Thanks for replying!After i read your reply,i think the function i used to test the app start time maybe is not correct. i should find some other ways to analyse the app start time .Thanks for replying again!
