### ISSUE TITLE
[Bug]: Select serial port more then once

### ISSUE THREAD

**Issue by aviTwito** [electron/electron#33095]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 1809

### What arch are you using?

x64

### Expected Behavior

When calling callback method of `select-serial-port`  to grant permission to a serial port more then once, each time the selected serial port permission will be granted

```
const ports: { [id: string]: boolean } = {};

const selectSerialPort = async (
  serialPort: Electron.SerialPort
): Promise<void> => {
  return new Promise((resolve) => {
    logger.info(
      `Requested to select ${serialPort.portName}-${serialPort.portId}`
    );
    if (ports[serialPort.portId]) {
      logger.info(
        `${serialPort.displayName} - ${serialPort.portId} Already Selected`
      );
      return resolve();
    }
    win.webContents.session.on(
      "select-serial-port",
      (event, portList, webContents, callback) => {
        event.preventDefault();
        const selectedPort = portList.find((device) => {
          return device.portId === serialPort.portId;
        });
        if (!selectedPort) {
          callback("");
        } else {
          delete ports[serialPort.portId];
          callback(selectedPort.portId);
          ports[serialPort.portId] = true;
          logger.info(`SerialPort [${selectedPort.portId}] Selected`);
        }
        resolve();
      }
    );
    win.webContents.executeJavaScript(
      `navigator.serial.requestPort().then(port => port).catch(err => console.error(err));`,
      true
    );
  });
};
```

This is how I call the method from my renderer
```
const getPort = async (serialPort: Electron.SerialPort): Promise<any> => {
  const filters = [
    {
      usbVendorId: serialPort.vendorId,
      usbProductId: serialPort.productId,
    },
  ];
  console.log(`------ get port called with -------`, serialPort);
  await window.ipcRenderer.invoke("selectSerialPort", serialPort);
  
  const port = await navigator.serial.requestPort({ filters });
  console.log(port);
  try {
    await port.close();
   
  } catch {}
  const options: SerialOptions = {
    ...
  };

  await port.open(options);
  return port;
};
``` 

### Actual Behavior

When calling the callback method for the second (or any other time after the first call) time, An expectation is thrown 
![Capture](https://user-images.githubusercontent.com/19937147/155871229-51ee32b4-23be-4807-8513-03d68fb8d75d.PNG)

**Comment by dsanders11** [comment]
@aviTwito, I believe this isn't a bug with Electron, but with your code. You're using `win.webContents.session.on("select-serial-port",` multiple times, which is attaching multiple event listeners. On the second call you then have two event listeners both trying to call `callback`, and so you get that error message, which is valid. The first event handler has already called the callback, the second one can't do anything.

I would suggest you refactor your code so there is a single event listener to avoid this problem. You could also fix it with a quick and dirty `win.webContents.session.removeAllListeners('select-serial-port')` to clear existing listeners before setting a new one.
