### ISSUE TITLE
Default Zoom Level of The Webpages

### ISSUE THREAD

**Issue by fardeen0424** [electron/electron#33099]
Hello Developers,

I'm new to Electron. I just made a desktop app with the help of electron.

I loaded web pages of an already built website in the electron window.

The problem is, Many PCs use a 125% zoom level because of that my web pages are occupying 
all the space and some elements are becoming distorted. The view of the desktop app is changing according to the windows zoom level.

We do zoom in and out on our browsers for readability and good view.

How can I set a default zoom level for my electron app? So, any URL that is being loaded into the window should use 
electron's zoom level and should not change according to windows resolution.

I want my pages to appear the same on every computer.

Please help with this.

Thanks&Regards

Fardeen

P.S : zoomFactor in webPreferences is not working.

**Comment by ckerr** [comment]
The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electronjs) a try.
