### ISSUE TITLE
[Bug]: Cannot embed PDF in iframe when accessing local files via protocol.registerFileProtocol().

### ISSUE THREAD

**Issue by george-thomas-hill** [electron/electron#33094]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

Other Linux

### Operating System Version

Kubuntu 21.04

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

I expect to be able to display a PDF (or any other arbitrary local file) by embedding it in an iframe inside a BrowserWindow instance.

I expect to be able to access the local file by using protocol.registerFileProtocol() as described here: https://github.com/electron/electron/issues/23393

### Actual Behavior

When I use the minimal test case available here . . .

https://github.com/george-thomas-hill/demo-electron-problem-embeding-pdf

. . . the PDF does not display.

My renderer process displays an empty iframe.

In my console, I get the message:

```
(node:2797438) electron: Failed to load URL: protocol://secretString/707861804 with error: ERR_BLOCKED_BY_CLIENT
```

### Additional Information

This might be related to the following issue: https://github.com/electron/electron/issues/28407

However, that issue's given workaround isn't available to me, because I'm using electron-forge and webpack, so my main process needs to have ```mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)```; I don't see a way to use ```loadURL('app://./index.html');```.

I am able to display arbitrary files by using the following in app.jsx:

```
                <webview
                    src={useSrc}
                >
                </webview>
```

However, the Electron documentation advises against using ```<webview>``` elements, i.e. here: https://www.electronjs.org/docs/latest/api/webview-tag

I have also tried using the following in app.jsx:

```
                <embed
                    type="application/pdf"
                    src={useSrc}
                >
                </embed>
```

However, that crashes my app.

I believe that this constitutes a bug, and I hope it can be fixed.

Alternatively, I would be grateful for any advice regarding how to securely use ```<webview>``` tags (or some other work-around).

Thank you.

**Comment by george-thomas-hill** [comment]
bump

**Comment by george-thomas-hill** [comment]
Update:

I'm still finding (in Electron 21.2.0) that loading a PDF in an iFrame fails to display the PDF, and loading a PDF in a webview crashes Electron.

Here's an Electron Fiddle gist that demonstrates this:

https://gist.github.com/george-thomas-hill/c3179e6eddeb1a2715201a20dbf95015

**Comment by shotor** [comment]
I'm seeing the same issues with no workaround.

iframe, embed, object => grey box - network tab shows file was requested correctly
webview => 0x0 element in dom - no crash

**Comment by 0kuang** [comment]
> I'm seeing the same issues with no workaround. Using Electron 21.3.0
> 
> iframe, embed, object => grey box - network tab shows file was requested correctly webview => 0x0 element in dom - no crash
> 
> I get this error in the console:
> 
> ```shell
> [70442:1118/152356.989338:ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 1
> ```

+1; I have the same problem in 24.1.3

**Comment by Skywalker13** [comment]
Same problem with electron 26...

**Comment by bkarv** [comment]
same problem electron 26 @Skywalker13 did you find a solution for this?

**Comment by Skywalker13** [comment]
> same problem electron 26 [@Skywalker13](https://github.com/Skywalker13) did you find a solution for this?

I use [pdfjs](https://www.npmjs.com/package/pdfjs-dist) from Mozilla

**Comment by bkarv** [comment]
Thanks I end up using electron-pdf-window and got it working as a seperate window. Its an old package but can confirm works on Electron 26 (just need to run an npm audit on some vulnerable dependancy). Here is my invoke function that does it by passing base64 string. 

```
import * as fs from 'fs';
import * as os from 'os';
const PDFWindow = require('electron-pdf-window');

ipcMain.handle('display-pdf', async (event, base64Data: string) => {
            console.log('Displaying PDF using electron-pdf-window');
            
            const {printDelay = 500 } = options || {};
            
            try {
                // Clean the base64 data
                const cleanBase64 = base64Data.replace(/^data:application\/pdf;base64,/, '');
                                
                // Convert base64 to buffer
                const pdfBuffer = Buffer.from(cleanBase64, 'base64');
                
                // Create a temporary file path
                const tempDir = os.tmpdir();
                const tempFileName = `pdf_preview_${Date.now()}.pdf`;
                const tempFilePath = path.join(tempDir, tempFileName);
                
                // Write the PDF buffer to a temporary file
                fs.writeFileSync(tempFilePath, pdfBuffer);
                
                // Create the PDF window with options
                const pdfWindow = new PDFWindow({
                    width: 1000,
                    height: 800,
                    show: false, // Don't show until ready
                    webPreferences: {
                        nodeIntegration: false,
                        contextIsolation: true,
                        webSecurity: true
                    },
                    title: 'PDF Preview',                    
                    // PDF-specific options
                    autoHideMenuBar: false, // Set to true to hide menu bar
                    titleBarStyle: 'default'
                });
                
                // Load the PDF file
                await pdfWindow.loadURL(`file://${tempFilePath}`);
                
                // Show the window once it's ready
                pdfWindow.once('ready-to-show', () => {
                    pdfWindow.show();
                    pdfWindow.focus();                 
                    }
                });
                
                // Clean up the temporary file when the window is closed
                pdfWindow.on('closed', () => {
                    try {
                        if (fs.existsSync(tempFilePath)) {
                            fs.unlinkSync(tempFilePath);
                        }
                    } catch (cleanupError) {
                        console.warn('⚠️ Could not clean up temporary file:', cleanupError);
                    }
                });
                
                // Handle window errors
                pdfWindow.webContents.on('did-fail-load', (event, errorCode, errorDescription) => {
                    console.error('❌ PDF window failed to load:', errorCode, errorDescription);
                });
                
                console.log('✅ PDF window created successfully');
                
                return { 
                    success: true, 
                    windowId: pdfWindow.id,
                    tempFile: tempFilePath 
                };
                
            } catch (error) {
                console.error('❌ Display PDF error:', error);
                return { 
                    success: false, 
                    error: error.message || 'Display failed' 
                };
            }
        });
```
