### ISSUE TITLE
[Bug]: Referer header not sent using webRequest.onBeforeSendHeaders

### ISSUE THREAD

**Issue by RinseV** [electron/electron#33092]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Expected Behavior

``Referer`` header is included in request after setting it using ``onBeforeSendHeaders``

### Actual Behavior

``Referer`` header is not included in request after setting it using ``onBeforeSendHeaders``

### Testcase Gist URL

https://github.com/RinseV/electron-referer

### Additional Information

Similar to #21374. I'm trying to use ``webContents.downloadURL()`` and want to set the ``Referer`` header for the request, since this is the only way to do so (#12883), but setting the ``Referer`` header from ``onBeforeSendHeaders`` does not seem to work in 17.x. I have not tested this in older versions. 

By setting the header in the Electron app as follows:
```js
session.defaultSession.webRequest.onBeforeSendHeaders((details, callback) => {
    // Set both Referer header and custom X-Referer header
    details.requestHeaders["Referer"] = "https://www.github.com/";
    details.requestHeaders["X-Referer"] = "https://www.github.com/";

    callback({
        requestHeaders: details.requestHeaders
    });
});
```
Sending the request as follows:
```js
let request = net.request("http://127.0.0.1:3000/");
request.end();
```
And then viewing the request headers from the Express server:
```
{
  host: '127.0.0.1:3000',
  connection: 'keep-alive',
  'x-referer': 'https://www.github.com/',
  'sec-fetch-site': 'none',
  'sec-fetch-mode': 'no-cors',
  'sec-fetch-dest': 'empty',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) electron-quick-start/1.0.0 Chrome/98.0.4758.102 Electron/17.1.0 Safari/537.36',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'en-GB',
  'if-none-match': 'W/"c-Lve95gjOVATpfV8EL5X4nxwjKHE"'
}
```
The ``X-Referer`` header is clearly set but the ``Referer`` header is absent.

**Comment by RinseV** [comment]
Still an issue on the latest version (21)

**Comment by ftyszyx** [comment]
still an issue in electron 31

**Comment by markwcn** [comment]
If you want to set the referer header through `net.request`, look this:
```
      test('should set the referer header when a referrer url specified', async () => {
        const referrerURL = 'https://www.electronjs.org/';
        const serverUrl = await respondOnce.toSingleURL((request, response) => {
          expect(request.headers.referer).to.equal(referrerURL);
          response.statusCode = 200;
          response.statusMessage = 'OK';
          response.end();
        });
        // The referrerPolicy must be unsafe-url because the referrer's origin
        // doesn't match the loaded page. With the default referrer policy
        // (strict-origin-when-cross-origin), the request will be canceled by the
        // network service when the referrer header is invalid.
        // See:
        // - https://source.chromium.org/chromium/chromium/src/+/main:net/url_request/url_request.cc;l=682-683;drc=ae587fa7cd2e5cc308ce69353ee9ce86437e5d41
        // - https://source.chromium.org/chromium/chromium/src/+/main:services/network/public/mojom/network_context.mojom;l=316-318;drc=ae5c7fcf09509843c1145f544cce3a61874b9698
        // - https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer
        const urlRequest = net.request({ url: serverUrl, referrerPolicy: 'unsafe-url' });
        urlRequest.setHeader('referer', referrerURL);
        urlRequest.end();

        const response = await getResponse(urlRequest);
        expect(response.statusCode).to.equal(200);
        await collectStreamBody(response);
      });
```
