### ISSUE TITLE
[Bug]: Build fails on macOS arm64 since v17

### ISSUE THREAD

**Issue by carstenbittrich** [electron/electron#33100]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

macOS

### Operating System Version

11.6.2

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

16.0.8

### Expected Behavior

The build process should succeed when following the instructions in the [documentation](https://www.electronjs.org/docs/latest/development/build-instructions-gn)

### Actual Behavior

A release build fails on macOS arm64 with
```
../../base/dcheck_is_on.h:8:10: fatal error: 'base/debug/debugging_buildflags.h' file not found
#include "base/debug/debugging_buildflags.h"
```

### Additional Information

Since switching to v17, I'm not able to build electron on an M1 Mac Mini.
The prerequisites are met on that system:
* node version: 16.14.0
* python version 2.7.16 (confirmed to have TLSv1.2 support using `npx @electron/check-python-tls`)
* macOS version: 11.6.2
* Xcode version: 13.2.1
* macOS SDK version: 12.1

The error message indicates a missing file, which is typically auto-generated during the build process of chromium. This generation can still be successfully triggered by building the ninja target `debugging_buildflags` explicitly. Once that is done for the target mentioned before and `tracing_buildflags`, the usual build of electron succeeds. We tried reproducing the issue in vanilla chromium, but the default instructions worked fine there. 

We could also reproduce the issue when cross-compiling for arm64 on an intel mac (Xcode 12.4.0, macOS SDK version 11.1, node 16.5.0)

**Comment by StaZhu** [comment]
any update on this ？ we are facing the same issue when building electorn 17.1.2 @carstenbittrich

**Comment by garbeam** [comment]
any update on this?

**Comment by carstenbittrich** [comment]
Quick update from my side: I reran a test using v18.0.0-beta.6, where I cross-build for arm64 on intel macs (now with the correct version of the macOS SDK). This failed by default, but the above workaround of building `debugging_buildflags` and `tracing_buildflags` first manually still works.
