### ISSUE TITLE
[Bug]: `Alt` + `Shift` / `Caps Lock` moves focus to the menu

### ISSUE THREAD

**Issue by madhead** [electron/electron#33101]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.7

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Expected Behavior

No menu items are selected, no focus lost from the window content.

### Actual Behavior

I have `Alt` + `Cap Lock` as a language switch shortcut, but it doesn't work with `Alt` + `Shift` aither. Actually, anything starting with `Alt` would not work, as `Alt` instantly triggers a menu to appear. The problem is that pressing the keys in the other way round (i.e. `CapsLock` + `Alt`) doesn't switch the language (and, of course, breaks my habits and my muscle memory).

https://user-images.githubusercontent.com/577360/155823034-ac74f9e9-9f3b-4489-816d-d02f84121469.mp4

### Additional Information

More information here: https://github.com/postmanlabs/postman-app-support/issues/7349#issuecomment-1050690410

**Comment by abnerlee** [comment]
I also met this on v18.3.0 / Windows 11

**Comment by abnerlee** [comment]
relates https://github.com/electron/electron/issues/28088

**Comment by RaisinTen** [comment]
The fix was backported to 12-x-y, 13-x-y and 14-x-y but the issue is reproducible on v13.6.7. Might be worth getting in touch with the reporters in https://github.com/electron/electron/issues/28088 and hearing from them if they are still able to repro?

**Comment by tomasz1986** [comment]
Good find! Electron was recently updated to v18 in https://github.com/laurent22/joplin/commit/27ef9173507318538c967d0d2c1aec6b794a8c5d, but I can still reproduce the problem in Joplin 2.9.1, so either the fix isn't present in this version, or if it is, then it seems flawed.

The key is the order of pressing the keys.

1. Press and hold left Shift.
2. While still holding left Shift, press left Alt.
3. Keyboard input has changed, but at the same time, Joplin has also moved keyboard focus to the menu bar.

If you press Alt first, the problem doesn't happen, i.e. only keyboard input changes.

**Comment by madhead** [comment]
It seems to be fixed, at least in the latest Electron versions (e.g. 21.2.3).

**Comment by RaisinTen** [comment]
@madhead any chance you could perform a bisection and find the change that fixed this for you? If possible, we could probably backport it to supported versions.

**Comment by madhead** [comment]
My setup has slightly changed since then, it would be hard to reproduce and test with all the possible versions. Let's just have it closed.
