### ISSUE TITLE
Add a switch for build libchromiumcontent library instead of downloading prebuilt libraries.

### ISSUE THREAD

**Issue by rosca** [electron/electron#3310]
For those who want to hack on both Electron and Chromium or to debug the full stack of modules, it's difficult to achieve local, incremental libchromiumcontent + electron builds.

The current electron build is fast and nicely decoupled from libchromiumcontent build and I think this should remain the default option for most projects/teams consuming Electron. However, I'd like to have the option to skip downloading libchromiumcontent prebuilt libraries and build them locally instead. This should allow us to make changes on chromium and generate an Electron containing these changes faster, without going through generating a libchromiumcontent distribution package and build Electron on top of that package.

Full local builds would also allow us to build the debug configuration of libchromiumcontent and use it along with the debug configuration of electron. Currently it's very difficult to build this configuration.

**Comment by SidneyS** [comment]
+1 on this.

**Comment by tejaspathak** [comment]
@zcbenz please check above code changes for this issue
