### ISSUE TITLE
[Bug]: Web Bluetooth PIN pairing fails on Windows

### ISSUE THREAD

**Issue by gniezen** [electron/electron#33111]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 1909

### What arch are you using?

x64

### Expected Behavior

When pairing a device using the Web Bluetooth API that requires a PIN, I expect the PIN pairing dialog box to appear. 

### Actual Behavior

PIN pairing dialog box does not appear, and operation fails with "GATT error: Not paired."

### Additional Information

Web Bluetooth PIN pairing has always worked on MacOS, but there was a Chromium bug that [prevented it from working on Windows](https://bugs.chromium.org/p/chromium/issues/detail?id=960258). This bug has since been fixed, at least since Chromium v96.0.4664.110.

**Comment by gniezen** [comment]
@jkleinsc Anything else I can do to help with this?

**Comment by gniezen** [comment]
@jkleinsc @dsanders11 @codebytere It looks like this also affects devices that pair without a PIN, and still exists on Electron v19. Please let me know if there's anything I can do to help move this forward or make it easier to debug.

**Comment by jkleinsc** [comment]
@gniezen I have a fix about ready to go but I was wondering if you know of any specific devices to test with?

**Comment by jkleinsc** [comment]
@gniezen I see this linked issue: https://github.com/tidepool-org/uploader/issues/1515.  Will this device work to test the issue: https://www.walmart.com/ip/Contour-Next-ONE-Blood-Glucose-Monitoring-System-Value-Pack/278244026 ?

**Comment by jkleinsc** [comment]
@gniezen I have been testing #35416 with the Contour Next One meter on Windows 11 and it looks like that particular device does not require a pairing PIN.  I verified this by testing in Chrome and Edge using https://googlechrome.github.io/samples/web-bluetooth/get-characteristics.html to test.  Both browsers never prompted for a pin but they were able to successfully get the `glucose_feature` characteristic.

Electron does throw an error calling `const features = await glucoseFeature.readValue();` but if I first pair the Contour Next One meter with Windows via the OS prompt, Electron can then successfully call `const features = await glucoseFeature.readValue();`.  I've debugged this further and the error is at the OS level, so I'm not sure how we can fix that and/or why Edge and Chrome don't need the device paired at the OS first.  It's possible that Edge and Chrome have a security exception that Electron does not.

**Comment by jkleinsc** [comment]
@gniezen - I think maybe my Electron test was doing something wrong, because when I run the code from https://googlechrome.github.io/samples/web-bluetooth/get-characteristics.html in Electron with the build from #35416, it works with errors.  So I believe #35416 should resolve your issue.

**Comment by gniezen** [comment]
@jkleinsc It looks like even though the Contour Next One meter does allow for PIN pairing, it can also use Just Works pairing, so it doesn't necessarily require the PIN pairing dialog box. Sorry, I should've checked this in more detail. When I use a meter that does require a PIN (e.g. the [Accu-chek Guide Me](https://www.accu-chek.com/meters/guide-me-meter)) the browser shows this screen:

![image](https://user-images.githubusercontent.com/418233/186872060-7102d768-e39a-4b11-8719-45572c5dbb65.png)

I agree that #35416 should resolve the issue. Please let me know when there's a build available that I can test!

**Comment by gniezen** [comment]
@jkleinsc I was just looking into this again and realised support for confirm-only support only became available in Chrome v105.0.5195.68, and is still hidden behind a flag `#enable-web-bluetooth-confirm-pairing-support`:

https://bugs.chromium.org/p/chromium/issues/detail?id=1309715

**Comment by gniezen** [comment]
@jkleinsc I can't seem to get any devices that use confirm-only PIN pairing to work. Should I file a new bug report?

**Comment by jkleinsc** [comment]
@gniezen I think the PIN pairing requires the `enable-web-bluetooth-confirm-pairing-support` flag to be set (it is still disabled by default), which you can do via:
```
app.commandLine.appendSwitch('--enable-features=WebBluetoothConfirmPairingSupport')
```.

If that fails to work, feel free to open up a new issue with a reproducible test case.
