### ISSUE TITLE
[Bug]: Setting the requestExecutionLevel option to requireAdministrator on Windows Server OS will cause the application to crash

### ISSUE THREAD

**Issue by Aoiujz** [electron/electron#33131]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows Server 2016, Windos Server 2019, Windos Server 2022

### What arch are you using?

x64

### Last Known Working Electron version

13.6.9

### Expected Behavior

Application starts normally

### Actual Behavior

The application does not start and it looks like the rendering process crashes.

### Additional Information

When `requestedExecutionLevel: requireAdministrator` is set, the application runs fine on Windows Desktop OS (Windows 10, Windows 11), but when running on Windows Server OS (Windows Server 2016, Windows Server 2019, Windows Server 2022), the application crashes.

When `requestedExecutionLevel: highestAvailable` is set, it works fine on both Windows desktop operating systems and Windows server operating systems but does not request administrator privileges when started on a Windows server operating system that is not logged in with an administrator account.

**Comment by Aoiujz** [comment]
Electron 13 and below do not have this problem. Electron 14 and above have this problem.

**Comment by Aoiujz** [comment]
18.0.x has the same problem.

**Comment by account-lyj** [comment]
The latest version still has this problem.

**Comment by xmsz-stu** [comment]
still

**Comment by SilverStudio1985** [comment]
still too

**Comment by matteocappello94** [comment]
Launching with `--in-process-gpu` resolve the problem on Windows Server for our project
