### ISSUE TITLE
[Bug]: `app.setLoginItemSettings` causes `App would like access to a network volume` on MacOS

### ISSUE THREAD

**Issue by hrueger** [electron/electron#33135]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.2.3

### What operating system are you using?

macOS

### Operating System Version

macOS 12.2.1 Monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

No boxes (see below) appear.

### Actual Behavior

I use `app.setLoginItemSettings({ openAtLogin: enabled });` to set whether my app should be started automatically after login or not.

However, every time I run this method, I get the following screen:
![grafik](https://user-images.githubusercontent.com/18656830/156595484-ff4d1084-32e2-4ebf-8494-f59835a45ade.png)
It says "Glue (that's how my app is called) would like access to files on a network volume".

This happens when there are network shares defined in macOS's login items.

I get one of those boxes for each network share defined there.

**Comment by ckerr** [comment]
Hey, thanks for reporting this. Is this behavior still happening for you in newer versions of Electron, e.g. the latest stable 17.1.0? Electron 12.2.3 [is no longer supported](https://www.electronjs.org/docs/latest/tutorial/support#supported-versions) and so testing that out on a newer version would be appreciated.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

**Comment by hrueger** [comment]
Sure, there you go: https://gist.github.com/hrueger/58fef41d6cfd6c81f29f9b02507174ab

Something intersting that I've noticed:
It seems like the dialog boxes only appear when `app.setLoginItemSettings` is called from an IPC handler function. When I called it inside `app.whenReady().then(() => /* here */);` handler, no dialogs appear.

**Comment by hrueger** [comment]
Also happens with Electron 17.1.0 (like in the gist)

**Comment by hrueger** [comment]
@ckerr is there anything more I can do to help you debug this?

**Comment by erickzhao** [comment]
Wasn't able to repro on my machine (macOS 12.5.1 arm64). The login item was registered correctly with no network drive popup.

**Comment by hrueger** [comment]
> This happens when there are network shares defined in macOS's login items.

Do you have them defined there?

**Comment by hrueger** [comment]
Anything missing here? I did provide a reproduction.
