### ISSUE TITLE
[Bug]: printToPDF shows blank only after write base64 pdf files

### ISSUE THREAD

**Issue by ajesh123** [electron/electron#33142]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 21H2

### What arch are you using?

x64

### Last Known Working Electron version

11.0.0

### Expected Behavior

Case1 : ipc call for creating a pdf file writing base64 array to file :
`require('electron').ipcMain.on('print-pdf-data', (pdfData) => {
    var buffer = Buffer.from(pdfData, 'base64');
    require('fs').writeFileSync("C:\\testdir\\report1.pdf", buffer);
});
 `

Case 2: Create a pdf file using screen data : 
`require('electron').ipcMain.on('print-screen-content', () => {
  mainWindow.webContents.printToPDF({ pageSize: 'A4', printBackground: false }).then((data) => {    
    var buffer = Buffer.from(data, 'base64');
    require('fs').writeFileSync("C:\\testdir\\report2.pdf", buffer); 
  });
}); `

Expected to create both files. 

### Actual Behavior

First call Case 1 and then Case 2 - report2.pdf is blank.
First call Case 2 and then Case 1 - both files have contents.

### Additional Information

If some pdf files are written with fs then printToPdf will not work. It's working up to electron version 11.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Please use [Electron Fiddle](https://github.com/electron/fiddle) to create a standalone (no external dependencies) testcase and publish it as a [gist](https://gist.github.com), then link to it here.

- Even if you have a code snippet or a git repository that show the testcase, please put it in a gist. This lets maintainers triage issues more effectively. It also ensures that we're testing the exact same issue that you're seeing!

- Please avoid external dependencies in the test. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.

- If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to the gist in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
