### ISSUE TITLE
[Bug]: mouse right-click ends up as `click` event in DOM

### ISSUE THREAD

**Issue by bpasero** [electron/electron#33157]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When doing a right click with an external mouse, it should not record a `click` event. 

### Actual Behavior

Right clicking into an element of the DOM triggers a `click` event.

### Testcase Gist URL

https://gist.github.com/e7969f4089ffcecb560d1e2ad275d2fa

### Additional Information

To reproduce:
* run the provided gist
* open dev tools
* right-click into the "Button" text
* see how an event is printed and the "Button" word is fully selected

![Recording 2022-03-06 at 10 12 47](https://user-images.githubusercontent.com/900690/156916706-7b208d75-1044-4fc3-90c6-4b867486aa9f.gif)

I am not entirely sure this is only an Electron issue, it reproduces all the way to Electron 13 and it only reproduces on macOS for me, not on Windows for example.

More importantly: it seems to not reproduce in a packaged, signed, bundled application with entitlements (such as a built VSCode), so I suspect it may be related to that. 

//cc @deepak1556

**Comment by ckerr** [comment]
Looks like the comment about this being mac-specific may be right. When testing on Electron v14.0.0-beta.25 on  Ubuntu 21.10, right-clicking does not tickle the "Click count:" callback

**Comment by bpasero** [comment]
Can someone else try to reproduce on macOS please? We have a few people in our team hitting this...

**Comment by JasonYeMSFT** [comment]
We have seen this issue during development as well. The issue seems to have been fixed in Electron 18.

**Comment by bpasero** [comment]
It is not fixed in Electron 18 for VSCode, just tested it with `18.1.0`.

**Comment by bpasero** [comment]
Yes, this still happens.

**Comment by nornagon** [comment]
@bpasero what version are you observing this in?

**Comment by nornagon** [comment]
I can't reproduce this on any version of Electron (tried 14, 17 and current main), either with an external mouse or with a trackpad. macOS 12.6.

**Comment by JasonYeMSFT** [comment]
@nornagon Have you tried running Electron in development/debug mode?

**Comment by nornagon** [comment]
@JasonYeMSFT yes, "current main" above means a local development build.

**Comment by bpasero** [comment]
Electron `19.1.3`

**Comment by JasonYeMSFT** [comment]
This problem seems to have been solved after upgrading to macOS 13.1.

**Comment by codebytere** [comment]
@bpasero can you confirm the above?

**Comment by bpasero** [comment]
Have not yet updated, sorry.

**Comment by nornagon** [comment]
I still can't reproduce this (macOS 12.6.3, tried Electron 14 through 24 and current main).

**Comment by bpasero** [comment]
Seems fine now.
