### ISSUE TITLE
[Bug]: icons in macOS modal dialogs not shown while animating into view

### ISSUE THREAD

**Issue by kevinushey** [electron/electron#33151]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

9.4.4, 17.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.2.1 (21D62)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The application icon should remain visible the whole time that the modal is animated.

### Actual Behavior

The application icon is briefly blank for the period when the modal is animated into view.

### Additional Information

A short screencast to illustrate, using Atom. (Atom here is using Electron 9.4.4, but we reproduced locally with an application using Electron 17.1.0 as well.)

https://user-images.githubusercontent.com/1976582/156818446-1e6f01ca-2707-4aa3-96bd-30af68cf6517.mov

A screenshot of the initial period where the icon is not visible.

<img width="319" alt="Screen Shot 2022-03-04 at 10 10 19 AM" src="https://user-images.githubusercontent.com/1976582/156818516-f9eeb970-e230-4d44-9444-e89e1105c70e.png">

**Comment by kevinushey** [comment]
Note: this seems to only affect modal message boxes -- that is, calls to `showMessageBox(window, options)` with an explicit `window` object.

**Comment by kevinushey** [comment]
Thanks! Unfortunately, I'm not able to publish my Fiddle as a gist; I get the following error instead.

<img width="280" alt="Screen Shot 2022-03-07 at 10 46 48 AM" src="https://user-images.githubusercontent.com/1976582/157098274-d3615eac-5317-4037-a6e8-76f4212b575f.png">

I've instead created a repository here with my Electron Fiddle files.

https://github.com/kevinushey/electron-issue-33151

That said, the issue is pretty readily reproduced by just invoking:

```
    dialog.showMessageBoxSync(mainWindow, {
      message: 'This is a message.'
    })
```

**Comment by codebytere** [comment]
@kevinushey do you have an example of an app _not_ doing this? we just call native APIs. this is likely an Apple issue, not an Electron one.

**Comment by kevinushey** [comment]
Thanks; I think you're right. Oddly, I don't see this issue in macOS's own applications, but I do see it in some other applications that don't use Electron (e.g. TextMate).

Sorry for the noise!
