### ISSUE TITLE
[Bug]:  Tab recording not working

### ISSUE THREAD

**Issue by larssvensby** [electron/electron#33165]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2 19044.1566

### What arch are you using?

x64

### Expected Behavior

Both audio and video are recorded for webcontent with the "tab" mediaSource implemented here https://github.com/electron/electron/pull/31204

### Actual Behavior

I start the recording after 10s, record for 10s and save to disk.

When setting tabCapture = "WEBVIEW" to capture webContent of a webview result in: "DOMException: Error starting tab capture".

When setting tabCapture = "WINDOW" to capture webContent of a BrowserWindow.
The audio is muted in the BrowserWindow when the recording starts, when the recording stops the audio returns.
The recorded file has no sound (there is an audio track but no sound) but video is OK.

Maybe I'm missing something, there isn't much documentation about this.

Thanks

### Testcase Gist URL

https://gist.github.com/larssvensby/4231053538ce4bda2fa4fce85b83f046

**Comment by ravenjohn** [comment]
Seeing this error as well on offscreen rendered BrowserWindow using electron version 19.0.8.

**Comment by ravenjohn** [comment]
Found a solution for my problem, the hidden BrowserWindow can start a stream of its own window and pass it to the renderer using WebRTC. My problem was that I was passing the `SourceId` into the renderer which is not possible according to the documentation.

> The identifier is restricted to the web contents that it is registered to and is only valid for 10 seconds.

https://www.electronjs.org/docs/latest/api/web-contents#contentsgetmediasourceidrequestwebcontents

**Comment by nornagon** [comment]
This should be possible in Electron 22+ with `getDisplayMedia` and `setDisplayMediaHandler`.

**Comment by giovanni-bertoncelli** [comment]
> setDisplayMediaHandler

How?
