### ISSUE TITLE
[Bug]: Window has borders while maximized in Wayland

### ISSUE THREAD

**Issue by alissonlauffer** [electron/electron#33161]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0 and 18.0.0-alpha.5

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Expected Behavior

The window should have no borders when maximized.

### Actual Behavior

Window has borders when maximized (at least in GNOME, I have not tested in other interfaces/window managers).

### Additional Information

To reproduce:
 - Use a Wayland environment.
 - Start the Electron demo app with the flags: `--enable-features=WaylandWindowDecorations --ozone-platform=wayland`.
 - Maximize the window.
 - See that the window isn't really maximized and there are still borders.

Some notes:
 - The issue is not reproducible in Chromium 99.0.4844.51 with the same start flags, so that's probably not a bug in the window manager.
 - When removing the `WaylandWindowDecorations` feature flag, window maximizes correctly under Wayland (though there are no window decorations, so I have to maximize window using keyboard).
 - Maybe CC #29618 author?

![Screenshot](https://user-images.githubusercontent.com/29029632/156944326-4ac421cc-a2c1-4099-bf12-f0af1c29de4a.png)

**Comment by kris7t** [comment]
The same problem also appears in weston, the wayland compositor reference implementation (because it also doesn't support server-side decorations).

However, electron works correctly in compositors with server-side decorations (e.g., KDE, sway), because the client-side decorations (that fail to detect maximized state) are disabled there as per https://github.com/electron/electron/pull/29618#issuecomment-858080436

**Comment by enx1998** [comment]
I have this problem too, also enabling CSD with `--enable-features=WaylandWindowDecorations` option with Gnome 41.

`./electron --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WaylandWindowDecorations`
![immagine](https://user-images.githubusercontent.com/20546217/161393696-8742c8e8-6714-43ee-b071-b28d30d0c199.png)

**Comment by enx1998** [comment]
Hi all,
is there any progress on this issue? Actually with gnome (at least 41 and 42) and wayland session, CSD is unusable and without CSD any electron based applications doesn't have window borders and mouse cursor has wrong dimension, sometimes too small, sometimes too large.

Thanks for your work,
ENx

**Comment by DiegoMagdaleno** [comment]
I have this issue too on GNOME 42, is there any fix in progress?

**Comment by DeedleFake** [comment]
I have recently begun writing my own Wayland compositor for fun and, having now become significantly more familiar with the way the system works, I can say pretty confidently that this is a bug on Electron's part. The compositor can tell a client that it's now maximized, and it's the client's responsibility to update its decorations to match that state. Electron is not doing that, resulting in it simply being resized into a 'maximized' area by the compositor without removing the shadow, which is technically part of the decorations.
