### ISSUE TITLE
[Feature Request]: Support native spelling panel on macOS

### ISSUE THREAD

**Issue by mitchchn** [electron/electron#33172]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron already supports the native macOS spell checker, but it does not provide access to the "Spelling and Grammar" panel:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/7342119/157102511-e5136cb2-e08a-4457-abd8-38c8adbb0508.png">

<img width="477" alt="image" src="https://user-images.githubusercontent.com/7342119/157102544-7180d562-18da-4833-8218-41ad228f3652.png">

This panel lets you change languages and address spelling errors iteratively, and is available by default in native text views on macOS.

### Proposed Solution

Support the spellcheck panel in Electron and expose access to it via a menu role. The panel is already  implemented in Chromium on Mac (`SpellCheckPanel`) so it may be possible to wire up that implementation to Electron.

### Alternatives Considered

I thought about adding this panel using a native module, but I believe should be built-in, since system spellcheck is already a feature of Electron. I also think a native module would require more privileged access to the renderer implementation than it has.

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/electron/electron/issues/3211
