### ISSUE TITLE
The 'console-message' event should propagate not only the first argument passed to the console.log call (e.message) but all the passed arguments as a string array.

### ISSUE THREAD

**Issue by bvahdat** [electron/electron#3317]
Following the [documentation](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#event-console-message), if the embedded markup inside the `webview` tag does:

`console.log('foo', 'bar', 'baz')`

Then what you would see inside the dev-tool is just `foo` being logged and nothing more! I guess somewhere along the way, electron needs to collect and pass over _all_ the arguments to the `console.log` call and not only just the first one. So maybe `e.message` should be better of the type array instead of just string?

The same behaviour goes for the other methods like `console.trace`, `console.info`, `console.error` etc.

**Comment by zcbenz** [comment]
This is currently blocked by https://code.google.com/p/chromium/issues/detail?id=365427.

**Comment by bvahdat** [comment]
Other than that, I've noticed that the `e.level` property value is:
`-1` for `console.debug`
`1` for `console.warn`
`2` for `console.error`
`0` no matter if `console.trace`, `console.log`, `console.dir` or `console.info` has been called which is a problem as you can't distinguish them.

**Comment by zcbenz** [comment]
Chrome team is not going to fix it, so I'm closing this issue now.
