### ISSUE TITLE
[Bug]: Infinite Uncaught illegal access in render process

### ISSUE THREAD

**Issue by autumnfield** [electron/electron#33191]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19042.1526

### What arch are you using?

x64

### Expected Behavior

Assuming a BrowserWindow like this:
```
const mainWindow = new BrowserWindow({
    webPreferences: {
        preload: path.join(__dirname, 'preload.js'),
        nodeIntegration: false,
        nativeWindowOpen: true,
        enableRemoteModule: true,
        contextIsolation: false,
        backgroundThrottling: false
    }
});
mainWindow.loadUrl(webSite)
```
I use `window.open`  to open another page in the webSite; 
```
  mainWindow.webContents.on('new-window', function(event, url, fname, disposition, options) {
    event.preventDefault()
    let childWin = new BrowserWindow({
      height: 720,
      width: 1366,
      show: false,
      webPreferences: {
        nodeIntegration: false,
        nativeWindowOpen: true,
        contextIsolation: false,
        preload: path.join(__dirname, 'preload.js'),
        backgroundThrottling: false
      },
      webContents: options.webContents
    })
    childWin.loadURL(url)
    childWin.maximize()
    childWin.show()
    event.newGuest = childWin
  })
```
Sometimes when I close the childWin, the mainWindow will appear "Uncaught illegal access" infinite.
I expect that the childWin close correctly.

### Actual Behavior

The MainWindow no response, and wait a while, windows system no response too.

I tried to use `webContents.setWindowOpenHandler` to  instead `new-window` event, the result is the same.

The odds of this happening are about one in 20

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
