### ISSUE TITLE
[Bug]: Color profile burnt into pixels of page snapshots

### ISSUE THREAD

**Issue by archfz** [electron/electron#33198]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.1

### What operating system are you using?

Ubuntu

### Operating System Version

21.10

### What arch are you using?

x64

### Expected Behavior

Screenshots taken using `Page.captureScreenshot` command or by running `window.webContents.capturePage()` should not have color profile changes burnt in.

### Actual Behavior

When taking screenshots programmatically color profile of the system is burnt into the image. On the other hand when screenshot is taken using the DevTools the screenshot is of the actual expected pixels. 

### Testcase Gist URL

https://github.com/archfz/electron-issue-screenshot

### Additional Information

Do the following to reproduce:

0. Ensure you are using a color profile on the system. Example in Ubuntu:
    ![image](https://user-images.githubusercontent.com/13706730/157322389-b54cee7a-9303-429d-b851-f8175ad06f59.png)
1. Clone https://github.com/archfz/electron-issue-screenshot
2. `npm i && npm start`
3. In 2 seconds a screenshot will be taken `./test.png` programmatically using `window.webContents.capturePage()`
4. Click on DevTools pane and press `[ctrl+shift+p]`, search screenshot, and take screenshot using devtools. Save under project as `./test.correct.png`
5. Notice the difference. For my case the expected color `#e55145` (in index.html and in ./test.correct.png) becomes `#c85847` (in test.png).

I have found that the following options do not change the behaviour in how screenshots are taken:
- `--force-color-profile=srgb`
- `--disable-color-correct-rendering`
- `--enable-legacy-color-correct-rendering`

Why is this an issue? I am attempting to do screenshot testing, and screenshots using both electron and chrome are inconsistent between systems, thus causing false positive failures in automation. I am using Cypress, and this framework comes bundled with electron, thus it is also the default choice for pipelines to not overbloat docker images.

I am able to confirm using Cypress that the same issue is present in chrome as well. I cannot confirm with standalone chrome. Now I do not know how to actually confirm this being an issues in chromium, as that repository is highly unfamiliar for me. This issue on the other hand is not present at all in Firefox.

I think this is a major reason why there are now far from ideal workarounds, like only generating images inside docker containers, not being able to accept changes on screenshots from GUI, or even pricey third party solutions to do the screenshots. A fix on this would greatly improve DX and potentially reduce costs.

I've created this issue in electron, as this is the closest browser with easy access to screenshot testing. I hope there is someone with chromium knowledge to confirm and potentially help with a fix on the issue, by comparing how DevTools vs how [Page.captureScreenshot](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot) works.

Related issues:
- https://github.com/electron/electron/issues/10732
- https://github.com/cypress-io/cypress/issues/495
- https://github.com/jaredpalmer/cypress-image-snapshot/issues/98
- https://github.com/meinaart/cypress-plugin-snapshots/issues/117

**Comment by ckerr** [comment]
Tested on Ubuntu 21.10 with color managed profiles enabled. Oddly, the color values between my two snapshots are identical, both #e55145 -- but it's clear that two different generation steps are happening, as test.png is 1545 bytes and test.correct.png is 2589.

> I am able to confirm using Cypress that the same issue is present in chrome as well. I cannot confirm with standalone chrome. Now I do not know how to actually confirm this being an issues in chromium, as that repository is highly unfamiliar for me. 

If this is an upstream issue in Chrome, it's better to report it there. It's very often the case that the best way to fix an issue is to have it fixed upstream so that Electron can pick up the fix automatically.

**Comment by archfz** [comment]
@ckerr Can you confirm that this is not an electron bug but a chromium one? If yes I will report it upstream.
