### ISSUE TITLE
[Feature Request]: Consistent use of Node's parser for URLs in examples in docs

### ISSUE THREAD

**Issue by cchartmann** [electron/electron#33192]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

In docs/tutorial/security at "13. Disable or limit navigation" it is recommended to use Node's parser for URLs.
https://github.com/electron/electron/blob/main/docs/tutorial/security.md#13-disable-or-limit-navigation

i suggest to follow this recommendation in "5. Handle session permission requests from remote content" so that users can copy the code there in their own code. At the moment forgetting that the trailing / is necessary would enable attackers to use URLs like "https://example.com.attacker.com".
https://github.com/electron/electron/blob/main/docs/tutorial/security.md#5-handle-session-permission-requests-from-remote-content

### Proposed Solution

use Node's parser for URLs

### Alternatives Considered

-

**Comment by Shofiya2003** [comment]
I would like to work on this issue. Is someone working on it?

**Comment by dsanders11** [comment]
Hi @Shofiya2003! No one is assigned to this issue, so feel free to submit a PR for it. 🙂 There are a lot of issues so it's unlikely anyone else is working it if there's not a PR for it.

**Comment by VinEmery** [comment]
Hello I am new to Git Hub.  How can I work on this project?

**Comment by avinashji1302** [comment]
Hey I m new here can anybody tell me how can i contribute to project ??

**Comment by Shofiya2003** [comment]
I believe this issue is already resolved as @Baitinq got the PR merged

**Comment by dsanders11** [comment]
Fixed in #33463, thanks for the heads up @Shofiya2003. 🙂

**Comment by maheshvardhanmadduri** [comment]
How to get started in contributing to projects/repositories/issues please
help me, totally new to open source contribution. I have experience in web
development in skills - html/css, python, nodejs, php. Can anyone guide me
please?
