### ISSUE TITLE
feat: print options should include a way to select paper feed

### ISSUE THREAD

**Issue by JoeABCDEF** [electron/electron#33190]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

What is the function of this PageSize? Is it set to directly change the paper selected by the printer? Is it just used to constrain DOM?
![image](https://user-images.githubusercontent.com/39638510/157180260-b02ef399-6f4c-416e-a9cb-cd3a4c214096.png)

### Proposed Solution

I hope there is a way to change the printer paper

### Alternatives Considered

none

**Comment by ckerr** [comment]
`pageSize` is an optional width and height in microns. When a custom `pageSize` is passed, Chromium attempts to validate platform specific minimum values for `width_microns` and `height_microns`. Width and height must both be minimum 353 microns but may be higher on some operating systems.

From looking at the code, it doesn't appear to me to affect the choice of paper feed. (However I don't physically have a dual-feed printer to test this with.)

**Comment by JoeABCDEF** [comment]
@ckerr After I set PageSize, won't he change the paper in this place? Can I override the default paper size
![image](https://user-images.githubusercontent.com/39638510/157574894-24cea815-0f64-4aa9-84da-e7f7a60fe58c.png)

**Comment by sunchanglong** [comment]
#31750
