### ISSUE TITLE
[Bug]: Regression: chrome_crashpad_handler contains debug information on Linux

### ISSUE THREAD

**Issue by lights0123** [electron/electron#33205]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 18.04

### What arch are you using?

x64

### Last Known Working Electron version

14

### Expected Behavior

The file `chrome_crashpad_handler` distributed with electron should be stripped.

### Actual Behavior

`chrome_crashpad_handler` is not stripped, causing Electron releases to be about ~20MB larger than they should be.

### Additional Information

The file `crashpad_handler` *does* try to be stripped, but it does not exist. Supposedly, that name should be used on Linux as said in https://github.com/electron/electron/issues/32669#issuecomment-1027704471, but it is not:

```bash
❯ wget https://github.com/electron/electron/releases/download/v17.0.0/electron-v17.0.0-linux-x64.zip
electron-v17.0.0-linux-x64.zip     100%[================================================================>]  94.77M  89.3MB/s    in 1.1s    

2022-02-03 00:42:31 (89.3 MB/s) - ‘electron-v17.0.0-linux-x64.zip’ saved [99370922/99370922]
❯ unzip electron-v17.0.0-linux-x64.zip
❯ file chrome_crashpad_handler 
chrome_crashpad_handler: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=98d3be7e8c7ac9110cb07010313260a150fed208, with debug_info, not stripped
```

It's also in the zip manifest:
https://github.com/electron/electron/blob/27527fe5ca790dc7061c6e816cc8b6ff72fe56d0/script/zip_manifests/dist_zip.linux.x64.manifest#L6

`chrome_crashpad_handler` was supposed to be stripped with #32549 (backport of #32540), but that PR tries to strip the (non-existent) binary called `crashpad_handler` instead.

**Comment by ckerr** [comment]
I think this is fixed by @deermichel's 753bde866a0df48505b08562081ed0c0e8581547
