### ISSUE TITLE
[Bug]: electron doesn't run my preload script

### ISSUE THREAD

**Issue by qq29640163** [electron/electron#33208]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows11pro 21H2

### What arch are you using?

x64

### Last Known Working Electron version

17.1.1

### Expected Behavior

I wrote the code according to the official example，He can implement preloaded scripts

### Actual Behavior

this is invalid example，The preload script didn't run successfully, and my breakpoint couldn't hit the script

### Testcase Gist URL

https://gist.github.com/qq29640163/7ff7122866f331334a5b9516d8750f2f

### Additional Information

I found a solution on StackOverFlow but I didn't. I hope it can help me. Thank you

**Comment by luokunman** [comment]
I had the same problem
