### ISSUE TITLE
[Bug]: Crash log cannot be compiled successfully in Linux

### ISSUE THREAD

**Issue by dongpeng520** [electron/electron#33217]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

ubuntu20

### What arch are you using?

Other (specify below)

### Expected Behavior

Crash log can be compiled successfully in Linux

### Actual Behavior

![image](https://user-images.githubusercontent.com/20813197/157596576-6f7110bd-495a-4cae-9fbd-a7e600450bb2.png)

**Comment by VerteDinde** [comment]
Hey @dongpeng520, thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. 

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment. Thanks in advance!

**Comment by dongpeng520** [comment]
> Hey @dongpeng520, thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment. Thanks in advance!
[test.log](https://github.com/electron/electron/files/8231722/test.log)

Nihao, please help me look at this problem. When the electron starts, it immediately reports an error and crashes

**Comment by dongpeng520** [comment]
@VerteDinde
