### ISSUE TITLE
[Bug]: current pywin32 win build directions don't make sense for depot_tools python

### ISSUE THREAD

**Issue by bughit** [electron/electron#33229]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

main

### What operating system are you using?

Windows

### Operating System Version

win10 21h2

### What arch are you using?

x64

### Expected Behavior

python prereqs used to be:

- Contrary to the depot_tools setup instructions linked below, you will need to use your locally installed Python with at least version 2.7.10 (with support for TLS 1.2). To do so, make sure that in PATH, your locally installed Python comes before the depot_tools folder. Right now depot_tools still comes with Python 2.7.6, which will cause the gclient command to fail (see https://crbug.com/868864).
- [Python for Windows (pywin32) Extensions](https://pypi.org/project/pywin32/#files) is also needed in order to run the build process.

The first part has been removed so presumably one is expected to use depot_tools python now. But it doesn't have pip

### Actual Behavior

- Which python are you supposed to use, depot_tools or own?
- Is pywin32 still needed?
  - For which part of the build?
  - if so, how do you install it into depot_tools

**Comment by bughit** [comment]
@dsanders11 Found your pr (#26186) to remove pywin32. Could you please clarify the current pywin32/python situation (questions in "Actual Behavior" section)?

**Comment by dsanders11** [comment]
Hi @bughit. You're right, those instructions are a bit malformed now. I'm also the one who removed the previous section. 😄 The `pywin32` removal stuff has lingered for a while as a result of CI issues, but there's renewed interest to get it done, so hopefully it will be removed soon.

In the mean time, the only usage of `pywin32` is in `build/profile_toolchain.py`, which looks to be only run on CI. In practice, you shouldn't need `pywin32` for building locally.

**Comment by pranay101** [comment]
Hi there, I am new to open source and I would like to work on this issue. Please guide me on what needs to be done.

**Comment by dsanders11** [comment]
Hi @pranay101, thanks for the interest! I have this issue covered, I'll update the documentation once I finish some of the related `pywin32` stuff.

Unfortunately we don't have the resources to guide new contributors, but we're happy to review PRs and provide feedback there. 🙂
