### ISSUE TITLE
[Bug]: [WIN][12.x.y][13.x.y] navigator.mediaDevices.enumerateDevices() returns incorrect default output device

### ISSUE THREAD

**Issue by Alex-us** [electron/electron#33225]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Expected Behavior

navigator.mediaDevices.enumerateDevices() should return correct default output device selected as default i OS audio settings

### Actual Behavior

1. Use laptop with WIN 10 onboard
2. Connect usb headsets and set it as default in OS audio settings
3. Start electron app and run navigator.mediaDevices.enumerateDevices() --> you will found it returns correct default output device.
4. Unplug headsets and plugin again. Make sure it is default in win 10 audio settings
5. run navigator.mediaDevices.enumerateDevices() in electron console window
===============================================
Now you can see that default audiooutput device is incorrect.
Chromium same version works fine. 

![image (1)](https://user-images.githubusercontent.com/5812272/157731475-f445d22a-c696-41eb-8502-0d955dcd6160.png)

![image](https://user-images.githubusercontent.com/5812272/157731458-169fafe0-af96-4cdc-a94c-febbe59d6d07.png)

**Comment by dsanders11** [comment]
@Alex-us, could you provide the full output from steps 3 and 5? I'd like to see if it is only the order which has changed.

**Comment by Alex-us** [comment]
step 3:
![step3](https://user-images.githubusercontent.com/5812272/157887311-e9bafd1e-f0dc-4adf-b9f3-a0bf91dd3aed.png)

Step 5:
![step5](https://user-images.githubusercontent.com/5812272/157887446-eebe556c-9515-47b2-a5c9-4a26a529860e.png)

Also one important note. After step 3 and before step 4 need to play audio using default audio output.
E.g:  
HTMLMediaElement.setSinkId('default');
or load and play without setting the sink id

For the latest version of Electron it is impossible for us to try it. It is quite long process to update for the company.

**Comment by dsanders11** [comment]
> For the latest version of Electron it is impossible for us to try it. It is quite long process to update for the company.

Can you try reproducing it with [Electron Fiddle](https://www.electronjs.org/fiddle)? That would let you test on the latest versions of Electron. It doesn't look like the reproduce steps are specific to your app. A solid reproduce case in Fiddle would be helpful, especially since this issue involves USB hardware.

**Comment by miniak** [comment]
@Alex-us why are you reporting issues in an unsupported version of Electron?
