### ISSUE TITLE
[Bug]: setCertificateVerifyProc not working

### ISSUE THREAD

**Issue by anderklander** [electron/electron#33235]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 21H2 22000.493 1000.22000.493.0

### What arch are you using?

x64

### Expected Behavior

setCertificateVerifyProc should be called

### Actual Behavior

setCertificateVerifyProc is not called for net.requests if having app.on("certificate-error")-handler and has loaded content from the same source in a browserview

### Testcase Gist URL

https://gist.github.com/065adc200497166475522200afcaf3a9

**Comment by clavin** [comment]
Hi! Thanks for bringing this issue up. Unfortunately, I was unable to reproduce this issue on the latest Electron 17 (tested on Windows 11) and your testcase gist. The page loaded without error for me.

Could you please provide more information about the actual behavior and how to make it happen? Also, would you be able to explain why the actual behavior is wrong?

**Comment by anderklander** [comment]
Tested again, using latest 17. And seems to be totally independent of the reload error, updated and simplified gist: https://gist.github.com/065adc200497166475522200afcaf3a9

![image](https://user-images.githubusercontent.com/3492572/158647767-f83476e1-7921-43c3-b17b-299413dbace7.png)
As you can see above, loading the content in the browserwindow works, and the first request i successful (without calling setCertificateVerifyProc) and sends correct content, but the second request fails and throws certificate issue. 

If commenting main.js:12 and not loading any content in the browserwindow, setCertificateVeryfiProc is called (and cached for 30 minutes): 
![image](https://user-images.githubusercontent.com/3492572/158649464-6163ae1b-eec3-45fc-b272-d6af72977755.png)

Seems like app.on("certificate-error" blocks setCertificateVerifyProc and is in some way used when using the net-module, but only for the first request. And "certificate-error" listener is not called when making net.requests.

This makes it impossible to implement a custom certificate verification and to me seems obviusly wrong!

**Comment by anderklander** [comment]
Hi! Verified again using 18.0.4. ping @clavin made some small updates to the gist to make it easier to reproduce on macos.

**Comment by anderklander** [comment]
Related question, is it possible to clear the cached result of the verification function? Says "The result of this procedure is cached by the network service" and seem to hold for 30 minutes, tried all the clear cache functions on session with no luck.

**Comment by JaspreetChhabra** [comment]
@anderklander Facing similar issue, network service caches the result and holds for 30 minutes. Were you able to resolve the issue?

**Comment by anderklander** [comment]
Bump, verified on 21.0.1

**Comment by anderklander** [comment]
Bump, verified on v22.0.1

**Comment by anderklander** [comment]
Bump, again
