### ISSUE TITLE
[Bug]: Window gets smaller when moving between monitors with different dpi

### ISSUE THREAD

**Issue by t57ser** [electron/electron#33268]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.985

### What arch are you using?

x64

### Last Known Working Electron version

14

### Expected Behavior

When moving the window from one monitor to another and then back the size should stay the same

### Actual Behavior

Tested with following setup: left monitor 100%, right monitor 125%
Move the window from left to right and then back again, it will have changed size to a smaller one

const { app, BrowserWindow } = require( "electron" )

```
app.whenReady().then(()=>{
	let main = new BrowserWindow({
		"height" : 600,
		"width" : 1800,
		x: 100,
		y: 100,
		show: false,
		frame: true,
		resizable: true,
		transparent: false,
		backgroundColor: "#FFFFFF"
	});
	main.loadURL("https://www.google.com").then(() => {
		setTimeout(() => {
			main.show();
		}, 0);
	})
})

```

### Testcase Gist URL

(https://gist.github.com/t57ser/c6bd51e27cb5e3001718cbcfe3e70778)

### Additional Information

You can check the devtools of the window and check the width/height of the body element to get the exact values of the change

**Comment by dsanders11** [comment]
@t57ser, this sounds like a duplicate of #32516. Can you check that issue and close this one if you believe they're the same issue? Thanks!

**Comment by t57ser** [comment]
Seems to be the case.
