### ISSUE TITLE
[Bug]: win.webContens.session.on('will-download') is triggered after win is closed

### ISSUE THREAD

**Issue by ym13349140** [electron/electron#33277]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.0.3

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Expected Behavior

I expect 'will-download' event to be removed or stopped when the window is closed.

### Actual Behavior

I  opened a sub window to download file, this sub window listened to the 'will-download' event, after downloading, I closed this sub window.But next time I open a new sub window to download a file, the old sub window's 'will-download' event is also  triggered and caused an error because its webContents is destroyed.
so I just want to know,how can I remove 'will-download' listener on win.webContents.session when i close the window?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
