### ISSUE TITLE
[Feature Request]: Electron elevated admin privileges

### ISSUE THREAD

**Issue by kmturley** [electron/electron#33276]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron docs/examples mostly show simple self-contained apps which read/write from Temp/App Data directories.

However a key use-case of Electron apps is to build a system app which performs actions outside of the default permissions sandbox. For example installing files to a system folder, or installing a config which is shared across all users of the same machine.

The [VSCode Electron app](https://github.com/microsoft/vscode) can elevate permissions. They check to see if permissions are elevated using [native-is-elevated](https://www.npmjs.com/package/native-is-elevated), and if not prompt for an admin password using [sudo-prompt](https://www.npmjs.com/package/@vscode/sudo-prompt). Developers have to read through project-specific source-code to understand how it can be achieved. 

Aside from reading through source-code there are UX, performance and security considerations. When should I ask for admin passwords? when Electron starts? vs every time a process needs permission? should the entire electron process be run as admin? or a child process only when required? It would be helpful to have more guidance.
 
**As a developer I would like an opinionated, expert recommendation on how to elevate to admin permissions inside Electron.**

### Proposed Solution

A section/page on [Electron Docs](https://www.electronjs.org/docs/latest) describing how to approach elevated privileges within/alongside Electron. Best practices & code examples considering UX, performance and security.

An example Electron app repo on GitHub with actual working code. I've created a quick example:
https://github.com/kmturley/electron-runas-admin

### Alternatives Considered

Potential alternatives:

- Medium blog posts
- Stackoverflow answers
- GitHub issues discussions

However these are less official, contain multiple opinions and do not always demonstrate best practices.

**Comment by jgresham** [comment]
+1

**Comment by MarshallOfSound** [comment]
This is a very specific usecase and I think personally it falls outside the scope of things Electron should provide / have explicit opinions about.  i.e. it leans more into Human Interface Guidelines than the actual desktop framework we provide should.

The two modules you linked look perfectly reasonable 🤷 but I don't think this very specific small usecase belongs in our documentation
