### ISSUE TITLE
BrowserView and loadFile are incompatible

### ISSUE THREAD

**Issue by ghost** [electron/electron#33272]
This works perfectly fine:

```js
const { BrowserView, BrowserWindow, app } = require('electron')
function twoViews () {
  const win = new BrowserWindow({ width: 1280, height: 770 })

  const view = new BrowserView()
  win.addBrowserView(view)
  view.setBounds({ x: 0, y: 0, width: 1280, height: 50 })

  //loading a url without problems
  view.webContents.loadURL('https://electronjs.org')

  const secondView = new BrowserView()
  win.addBrowserView(secondView)
  secondView.setBounds({ x: 0, y: 50, width: 1280, height: 720 })
  secondView.webContents.loadURL('https://electronjs.org')
}

app.whenReady().then(twoViews)
```

And this does not:

```js
const { BrowserView, BrowserWindow, app } = require('electron')
const path = require("path");

function twoViews () {
  const win = new BrowserWindow({ width: 1280, height: 770 })

  let view = new BrowserView()
  
  win.addBrowserView(view)
  view.setBounds({ x: 0, y: 0, width: 1280, height: 50 })

  //trying unsuccessfully to load local file
  view.webContents.loadFile("views/urlWindow.html");

  const secondView = new BrowserView()
  win.addBrowserView(secondView)
  secondView.setBounds({ x: 0, y: 50, width: 1280, height: 720 })
  secondView.webContents.loadURL('https://electronjs.org')
}

app.whenReady().then(twoViews)
```

According to the documentation, it should work but it doesn't. I've tried all sorts of ways to point to the path including file:// and dirname, all fail to load the local html file. What am I missing? I've tried this with the latest version of Electron on Ubuntu 20.04.

**Comment by dsanders11** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:

**Comment by infosisio** [comment]
@dsanders11 Pardon me:

Version: "electron": "^17.1.2"
Operating System: Ubuntu 20.04
Arch: x64
Expected and actual behavior were described above

**Comment by dsanders11** [comment]
@infosisio, I've turned your code snippet into a fiddle (check out [Electron Fiddle](https://www.electronjs.org/fiddle) if you haven't seen it before) and it works fine for me on macOS: https://gist.github.com/578ec562da997176d44ffb38f2113414

I'll test it later on Ubuntu, but I have a feeling it's going to work there as well. Could you try running that test in Fiddle and see if it works as intended on your system?

**Comment by infosisio** [comment]
@dsanders11 Just tested it using your fiddle, not working here. Here is a screenshot:
![Screenshot from 2022-03-15 00-27-58](https://user-images.githubusercontent.com/40072254/158271365-f483a6b7-b543-44c6-a7ad-9d9b8054ae88.png)

**Comment by dsanders11** [comment]
@infosisio, thanks!

I've confirmed I see the same behavior on Windows, but not on macOS. The behavior is flaky on Windows, I've seen it work a few times. It could be a race condition, given the flaky nature. My macOS machine is more powerful than the others, so it could simply be avoiding the race condition.

It looks like this works consistently on all platforms on v13.4.0 and earlier. It became flaky starting in v13.5.0.

**Comment by dsanders11** [comment]
I've narrowed the fiddle to just the important bits for repro, it only needs a single `BrowserView`: https://gist.github.com/af6fdefe02c460a345efa0c672ee5e34

**Comment by infosisio** [comment]
@dsanders11 One more thing that I've noticed, if you do something like this to the view:

```
view.setAutoResize({
  width: true,
  height: true,
});
```

And drag the window around, then in some cases the html gets to render. 

Just in case this is helpful.

**Comment by dsanders11** [comment]
Might be related to #29919, which landed in v13.5.0.

**Comment by codebytere** [comment]
@dsanders11 it's ultimately related to https://chromium-review.googlesource.com/c/chromium/src/+/2780032 - there's probably a more robust fix

**Comment by pushkin-** [comment]
wonder if this should be reopened
