### ISSUE TITLE
[Bug]:setBounds is not work when dragging the window all the way

### ISSUE THREAD

**Issue by CahierX** [electron/electron#33279]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.9

### What operating system are you using?

Windows

### Operating System Version

windows 10 pro 20H2

### What arch are you using?

x64

### Expected Behavior

setBounds is work when dragging the window all the way

### Actual Behavior

setBounds is not work when dragging the window all the way

### Testcase Gist URL

https://gist.github.com/6b6ea5cdaa1883656a8bd0bf89195283

**Comment by codebytere** [comment]
Please further describe the issue - "dragging the window all the way" is not sufficient to determine what needs to be done to reproduce.

**Comment by CahierX** [comment]
> Please further describe the issue - "dragging the window all the way" is not sufficient to determine what needs to be done to reproduce.

When the program calls setBounds, the left mouse button clicks on the window without loosening, and drags left and right

https://user-images.githubusercontent.com/31394482/158505232-74c9f13d-0146-4cc0-9214-e0f251803f39.mov

**Comment by codebytere** [comment]
This is a longstanding upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=251813
