### ISSUE TITLE
[Bug]: The devicechange event of navigator.mediaDevices is incorrectly triggered when electron is first opened

### ISSUE THREAD

**Issue by Danjuanlab** [electron/electron#33282]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0 /17.1.2

### What operating system are you using?

Windows

### Operating System Version

win11

### What arch are you using?

x64

### Expected Behavior

navigator.mediaDevices.addEventListener('devicechange', event => {}); can be correctly triggered by device change.

### Actual Behavior

This event is triggered  by mistake only when electron is first opened, and when the page is loaded for the first time. In the follow-up, whether it is switching the page route or ctrl+r to refresh the electron page, this event will not be triggered by mistake again.

### Additional Information

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <span id="aa">1</span>
</body>
</html>

<script>
navigator.mediaDevices.addEventListener('devicechange', event => {document.getElementById('aa').innerText='chuf222a'});

</script>
```

**Comment by dsanders11** [comment]
Confirmed this behavior on Windows 10. I needed a USB webcam plugged in before trying the testing.

Reproduces in Chromium itself, so it's an upstream issue. It first appeared in Electron 4.0.0-nightly.20181006. Since it's in Chromium, it was probably introduced somewhere in here: https://chromium.googlesource.com/chromium/src/+log/67.0.3396.99..68.0.3440.128/

Bisecting the Chromium builds would narrow it down.

**Comment by dsanders11** [comment]
Bisected it down to this range: https://chromium.googlesource.com/chromium/src/+log/4625214fae133516f909e6305c858feb02944f4a..4b2722307920997a657fbd5472c10f3d27409b07

**Comment by dsanders11** [comment]
Mostly likely culprit: https://chromium.googlesource.com/chromium/src/+/d4af62ded717ec9fe2bb54d9d05439d4dfeff0b5

**Comment by dsanders11** [comment]
Repro gist that works all the way back to v3: https://gist.github.com/40afaae18e210a7956481d87597eeb7d

**Comment by dsanders11** [comment]
Still repros on v21.

**Comment by Danjuanlab** [comment]
Still repros on electron v22.0.0.

**Comment by EminCivelek** [comment]
I am not sure if it is really related but when I try to loadURL first time on my app, Avast is warning me for "Electron.exe try to reach your webcam". This issue is the only thread I have found that might be the cause for it.
