### ISSUE TITLE
[Bug]: setIgnoreMouseEvents forwarding does not work when certain non-electron windows are in focus.

### ISSUE THREAD

**Issue by snaggas** [electron/electron#33281]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10, version 20H2, Windows 10, version 21H2, Windows 11

### What arch are you using?

x64

### Expected Behavior

When mouse event forwarding is turned on with `win.setIgnoreMouseEvents(true,{forward:true});`, mouse events such as `mousemove`, `mouseenter`, etc should always be fired in the electron app.

### Actual Behavior

When mouse event forwarding is turned on with `win.setIgnoreMouseEvents(true,{forward:true});`, mouse events such as `mousemove` fire, except when certain non-electron windows (e.g. Device Manager, Task Manager, WireGuard and presumably others of a similar style) are in focus (the foreground window). Click through functionality still works, and windows underneath are still receiving the events, but the electron window in question does not receive the mouse events.

### Testcase Gist URL

https://gist.github.com/02dcbceec8635367cee0c93d646d1e42

**Comment by f4z3k4s** [comment]
On MacOS, we experience something similar as above v16.0.10 (even in v18.0.0.beta-4). Last version that is working is v16.0.10 (v16.1.0 breaks it). The only difference is that it doesn't matter if the window is in focus or not, the event is never forwarded when the below code is present.
```ts
    this.window.setIgnoreMouseEvents(true, {
      forward: true,
    });
 ```
 
 Maybe something broke it here: https://github.com/electron/electron/compare/v16.0.10...v16.1.0 ?

**Comment by wapgear** [comment]
Hey, have you found a solution for this one @snaggas ?

**Comment by snaggas** [comment]
> Hey, have you found a solution for this one @snaggas ?

Hi, thanks for the interest. No, unfortunately not. To me, it seems like a genuine bug in electron, but I'm open to other ideas.

Did you come across this issue independently?

**Comment by wapgear** [comment]
> but I'm open to other ideas.
For my case I found a solution, it's not nice looking but at least it works.

The problem I tried to solve - I have a fullscreen overlay that has controls that should be focusable, but all content behind the overlay also should be accessible, so I solved it by having:
1. `onMouseMove` event which returns cursor position
2.  Position and size of the mainWindow interaction with which causes the issue
3.  Position of the elements in an overlay which should be focusable
4.  Function which is tracking
    a. cursor position
    b. cursor position + `mainWindow` offset
    c. if my controls is crossing `a` or `b` and based on it setting `setIgnore` true or false

**Comment by Mad-hu** [comment]
+1 , please fix it.😭

my case temporary situation:
It looks ok, but it’s not really usable.
`
checkMouseOver(box: HTMLDivElement) {
    this.windowFocusTimer = setInterval(() => {
      // getCursorScreenPoint
      const { x, y } = electronRendererRemote().screen.getCursorScreenPoint();
      if (
        x > box.offsetLeft &&
        x < box.offsetLeft + box.offsetWidth &&
        y > 0 &&
        y < box.offsetHeight
      ) {
        if (!getCurrentWindow().isFocused()) {
          getCurrentWindow().focus();
          windowService().setIgnoreMouseEvents(false);
        }
      }
    }, 400);
  }
`

**Comment by ibc** [comment]
So is this yet another legitimate and proven bug in Electron (with proper STR) being marked as stale and then closed due to inactivity?

**Comment by jtzcode** [comment]
In my case, the issue is more likely to reproduce when there is a plugged-in stylus pen device with Windows Ink enabled (like Wacom). The mouse_move events did arrive the chrome window (observed with Spy++) but no mouse-move related events triggered in the page. The issue seems to be imported in 12.0.0, while I cannot reproduce it with 11.1.1 in my case. Has anyone met the same results?

**Comment by JasonLeviGoodison** [comment]
the {forward: true} option works for me until there is a redirect (I have an oauth login flow) and then when the page is reloaded, it no longer works. If the user is already logged in (if I simply reload the app) then everything works fine. 
Seems to be something about redirecting that is breaking the "forward" option

**Comment by ScarboroughCoral** [comment]
bump
