### ISSUE TITLE
[Bug]: All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage()

### ISSUE THREAD

**Issue by JeremyRubin** [electron/electron#33317]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

macOS

### Operating System Version

12.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

No errors on loading of fonts.

### Actual Behavior

My apps stdout log is filled with this message repeated every 0.001 seconds dramatically slowing it down.

2022-03-16 17:30:40.768 Electron Helper (Renderer)[24797:6345262] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2022-03-16 17:30:40.769 Electron Helper (Renderer)[24797:6345262] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].

### Testcase Gist URL

Can't Repro

### Additional Information

related: https://github.com/microsoft/vscode/issues/98597

I'm working on my project https://github.com/sapio-lang/sapio-studio and this issue comes up after I load canvas assets using react storm diagrams.

I have the following CSS rule:

```css
.App {
    font-family: 'IBM Plex Mono', 'Menlo', 'DejaVu Sans Mono',
        'Bitstream Vera Sans Mono', Courier, monospace;
}
```

removing this rule entirely "solves" the issue (but then i can't have fonts)

Sorry for no repro -- it *is* reproducible with using an actual `.NewYork-Regular' font in CSS, but I don't seem to be doing that.

**Comment by codebytere** [comment]
@JeremyRubin this is unfortunately not an issue with Electron - this is all implemented in Chromium itself. You should file a crbug at crbug.com or comment on https://bugs.chromium.org/p/chromium/issues/detail?id=1131559&q=NewYork-Regular&can=2
