### ISSUE TITLE
[Feature Request]: It is possible use auto-updater api for update an appx windows application build with electron?

### ISSUE THREAD

**Issue by Joralmo** [electron/electron#33327]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I have an ionic v3 application build how appx application using electron builder but i want know if is possible use code-push or some strategy for auto updates (how auto-updater api) for send [hot] updates to the app, but i not found any documentation about it, but first i want know if this is possible, thanks.

### Proposed Solution

DOES NOT APPLY

### Alternatives Considered

DOES NOT APPLY

### Additional Information

i am using electron 14 and electron-builder for create the appx package

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
