### ISSUE TITLE
Hotkeys should work with NumPad combinations

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#3332]
We have zoom hotkeys set up using accelerators for `+`, `-`, and `0`. These work as expected, but not when someone presses `NumPadPlus`, `NumPadMinus`, or `NumPad0`. Seems that all number pad keys should map to the same accelerators.

**Comment by deepak1556** [comment]
Would adding support for numpad keycodes be enough or should they be mapped instead ? The problem i see with the latter approach is that if an accelerator is registered but its mapped numpad accelerator fails to register then should the entire registeration be returned as success or failure ?

```javascript
globalShortcut.register('ctrl+Plus', listener);
globalShortcut.register('ctrl+NumpadAdd', listener);

// verify the registrations and take actions in the listener.
```

**Comment by nruffilo** [comment]
I would also like to use numpad.  I did a mapping for CommandOrControl+0 and it works fine in the number rows, but when I do the numpad, it does not work.  Using NumPad or Numpad is not recognized and throws an error.

**Comment by codebytere** [comment]
closing due to abandonment.

**Comment by stevensmedia** [comment]
So this won't be fixed, and people who need this should look elsewhere?

**Comment by BloodShura** [comment]
+1. I don't think that numeric pads are overrated enough for this to be ignored.

**Comment by AhmedLoud** [comment]
+1

**Comment by vsvipul** [comment]
any updates on this ?

**Comment by claudialphonse** [comment]
any update on this?
