### ISSUE TITLE
[Bug]: BrowserWindow.getFocusedWindow crash: Cannot read properties of null (reading 'isDevToolsFocused')

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#33326]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0, at least back to 12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

A function like `BrowserWindow.getFocusedWindow()` shouldn't crash if a window is destroyed.

### Actual Behavior

`BrowserWindow.getFocusedWindow()` sometimes crashes

### Testcase Gist URL
https://gist.github.com/d7433e132a56679832f37a9446d4530c

### Additional Information

Stack:
```
TypeError: Cannot read properties of null (reading 'isDevToolsFocused')
at BrowserWindow.n.isDevToolsFocused (node:electron/js2c/browser_init:33:2385)
at Function.n.getFocusedWindow (node:electron/js2c/browser_init:33:1508)
```

Should we have some `isDestroyed()` check here:

https://github.com/electron/electron/blob/44491b023ac2653538b7ac36bb73f3085a938666/lib/browser/api/browser-window.ts#L73-L78

Another option is for `getAllWindows()` to stop returning the destroyed window? (or I guess all we really know is that the window doesn't have a `webContents`).

1. Run the gist above
2. click the open window button (this will open a window and then create a second one that's a child of the first)
3. click the destroy window button
4. Observe the crash popup

So specific to cases where a parent window is closed, and the child window's `closed` handler is calling `BrowserWindow.getFocusedWindow()`

**Comment by pushkin-** [comment]
related VSCode [issue](https://github.com/microsoft/vscode/issues/114564)

**Comment by pushkin-** [comment]
Interestingly, if I call `win.close()` instead of `win.destroy()`, I instead get an "Object has been destroyed" error message from `isDevToolsFocused".

**Comment by codebytere** [comment]
@pushkin- I repro'd this on Windows but interestingly it doesn't happen on macOS. I'll take this and look into it.
