### ISSUE TITLE
Is Electron or any of it's dependencies affected by the `node-ipc` protestware?

### ISSUE THREAD

**Issue by TechStudent11** [electron/electron#33336]
I know that Electron has it's own IPC, but is it possible that any of Electron's dependencies are affected by this?

**Comment by erickzhao** [comment]
Electron shouldn't be affected. You can see the project's full dependency tree in the lockfile:

https://github.com/electron/electron/blob/main/yarn.lock

**Comment by TechStudent11** [comment]
Whew it looks like there's no sign of `node-ipc`.

Thank you!
