### ISSUE TITLE
[Bug]: ipc can not send Object[] data

### ISSUE THREAD

**Issue by xhxhxhxh** [electron/electron#33331]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.11

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Expected Behavior

Maybe this type is not supposed by [Structured Clone Algorithm], is there any other way to send that data?

### Actual Behavior

`const data = [
a: [
{
        children: [
{
          a: 123
        }
]
      }
]
]`
when I send this data by ipcRenderer, the data I received is incomplete;

**Comment by emreabaci** [comment]
Can you try JSON.stringfy(data) in sending section and use JSON.parse(args) in receiving section?

**Comment by xhxhxhxh** [comment]
I know the reason, In component has another function filtered that data cause this problem, it is not structured Clone Algorithm problem, I got the problem in the wrong direction.
