### ISSUE TITLE
[Bug]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by mboutin-qohash** [electron/electron#33338]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.8

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.2.1

### What arch are you using?

x64

### Expected Behavior

When running the tests, it should not throw errors

### Actual Behavior

When running tests with jest, it gives this output on many test suites

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

      at getAppData (node_modules/electron-log/src/transports/file/variables.js:27:19)
      at Object.getPathVariables (node_modules/electron-log/src/transports/file/variables.js:95:14)
      at fileTransportFactory (node_modules/electron-log/src/transports/file/index.js:17:33)
      at create (node_modules/electron-log/src/index.js:47:11)
      at Object.<anonymous> (node_modules/electron-log/src/index.js:12:18)
```

**Comment by RaisinTen** [comment]
> When running the tests, it should not throw errors

Do u mean this happens while running the electron test suite?

Looking at the logs, it seems like this is coming from a different repo altogether - https://github.com/megahertz/electron-log/blob/16b352634887d21d155bc6bcd5af09ac8bb129bc/src/transports/file/variables.js#L27.
