### ISSUE TITLE
[Bug]: cant install v8.5.5 on mac but can window

### ISSUE THREAD

**Issue by sseemmiin** [electron/electron#33330]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS monteray 12.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

8.5.5

### Expected Behavior

download 8.5.5

### Actual Behavior

i use electron version 8.5.5 

It can yarn install on window but cant on Mac

over 8.5.5 , new window popup cant selected

**Comment by miniak** [comment]
Electron 8 is not supported
