### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Talent-HYJ** [electron/electron#33334]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

13.1.0

### Expected Behavior

The App cannot be built on the MacOS Monterey 12.3 system. macOS 12.3 removes python2.7 and uses python3.8, which causes electron to fail to build the dmg package. Still can't build successfully after installing python2.7 manually

<img width="710" alt="image" src="https://user-images.githubusercontent.com/53029580/158987186-2315227b-78cb-43d8-8279-679fce60711a.png">

### Actual Behavior

Failed to build successfully on MacOS Monterey 12.3

### Additional Information

At present, brew has also removed the python@2 related dependencies

**Comment by erickzhao** [comment]
What are you using to build your application? This repository doesn't handle any building/packaging tooling, so this likely isn't the right place to file the issue.

**Comment by miniak** [comment]
Electron 13 is not supported

**Comment by codehzy** [comment]
can you Solve the problem？I have comm trouble
