### ISSUE TITLE
[Bug]: Menu.setApplicationMenu(null) doesn't work

### ISSUE THREAD

**Issue by jinyuli** [electron/electron#33332]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

trying to remove menu bar with the following code:
`Menu.setApplicationMenu(null)`

I tried it in app ready
```javascript
app.on('ready', () => {
    Menu.setApplicationMenu(null)
})
```

I also tried to call it before 'ready'
```javascript
Menu.setApplicationMenu(null)
app.on('ready', () => {
    
})
```

### Actual Behavior

the menu bar is still there
![屏幕截图 2022-03-18 173118](https://user-images.githubusercontent.com/5809787/158978147-599687fe-e3ff-487e-b90c-727f9f04a949.jpg)

### Additional Information

I'm trying to remove the top bar in red mark, that's call menu bar, right?

![屏幕截图 2022-03-18 173118](https://user-images.githubusercontent.com/5809787/158977943-70d6ba3c-6c7d-4cc0-9d25-d1b65df2c66d.jpg)

**Comment by erickzhao** [comment]
That's the title bar style, not the menu.

See https://www.electronjs.org/docs/latest/tutorial/window-customization for more information. Feel free to stop by our [Discord server](https://discord.gg/electronjs) for any help with building or debugging your app.
