### ISSUE TITLE
[Bug]: WebAuthn Discoverable Credential (Resident Credential)

### ISSUE THREAD

**Issue by ks75vl** [electron/electron#33353]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2

### What arch are you using?

x64

### Expected Behavior

After call `navigation.credential.get()` with the appropriate parameters for getting resident credential from security key. Built-in Windows FIDO2 client should popup to guide the user to complete the request.

### Actual Behavior

An error was thrown: `NotSupportedError: Resident credentials or empty 'allowCredentials' lists are not supported at this time.`

### Testcase Gist URL

https://gist.github.com/ks75vl/f6c49785a28f361c342ee60a56c2be38

### Additional Information

https://github.com/electron/electron/issues/33271

**Comment by matthewloft** [comment]
Support for discoverable credentials with physical authenticators is disabled by default in chromium. 
While the Chrome browser enables it, Electron doesn't.
Submitted this pull request [/pull/35374] to turn it on. 
Tested with a physical Yubikey on Windows, and works to create and get discoverable credentials.

**Comment by matthewloft** [comment]
@ks75vl PR https://github.com/electron/electron/pull/35374 is now merged, so you may want to retest.
Depending on your IdP, you may need to strip out any any custom agents (e.g. "Electron/xx.xx" or "MyAppName/xx.xx") from the User Agent string. IdP's can suppress security key functionality based on what they see in the User Agent. Azure AD certainly does this. Not sure about others.

**Comment by ruiquelhas** [comment]
I'm assuming this feature has been introduced in `electron@22.0.0-alpha1` according to the release notes but I've tried it using `electron@22.0.0-alpha.7` and it still does not seem to work as expected. In this case, if the `allowCredentials` property is not defined or is an empty list, instead of the error reported by OP, it yields:

> The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.

If I `allowCredentials` contains a valid credentialId, everything works fine. So, I'm guessing there is still something missing.
