### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ksy1992-dev** [electron/electron#33352]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.1

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

Hi
I am working with electron project, which is wexond framework.
https://github.com/wexond/browser-base

I have to upgrade from electron 13.x to electron.16 + so I have installed @electron/remote and electron 17.1.1.
But I got error.

ReferenceError
require is not defined

So I have changed webpack config and now I have got this error.
Electron >=v13.0.0-beta.6 required to support sandboxed renderers

### Actual Behavior

The first error:
-------------------------------------------
Call Stack
 electron
  app.bundle.js:548:1
 Object.options.factory
  runtime.app.bundle.js:613:31
 __webpack_require__
  runtime.app.bundle.js:36:33
 fn
  runtime.app.bundle.js:278:21
 eval
  src/common/renderer-config.ts:17:20
 ./src/common/renderer-config.ts
  src_constants_settings_ts-src_renderer_mixins_default-styles_ts-src_renderer_pre-entry_ts-src-e1c37d.bundle.js:17:1
 Object.options.factory
  runtime.app.bundle.js:613:31
 __webpack_require__
  runtime.app.bundle.js:36:33
 fn
  runtime.app.bundle.js:278:21
 eval
  src/renderer/pre-entry.ts:12:27

Second error
--------------------------------------------------------
Call Stack
 getContextId
  node_modules/@electron/remote/dist/src/renderer/remote.js:40:15
 eval
  node_modules/@electron/remote/dist/src/renderer/remote.js:44:45
 ./node_modules/@electron/remote/dist/src/renderer/remote.js
  vendors-node_modules_electron_remote_renderer_index_js.bundle.js:51:1
 Object.options.factory
  runtime.app.bundle.js:613:31
 __webpack_require__
  runtime.app.bundle.js:36:33
 fn
  runtime.app.bundle.js:278:21
 eval
  node_modules/@electron/remote/dist/src/renderer/index.js:15:14
 ./node_modules/@electron/remote/dist/src/renderer/index.js
  vendors-node_modules_electron_remote_renderer_index_js.bundle.js:40:1
 Object.options.factory
  runtime.app.bundle.js:613:31
 __webpack_require__
  runtime.app.bundle.js:36:33

**Comment by miniak** [comment]
If you have an issue with https://github.com/electron/remote, you need to report it there. Also it looks like you might have to disable `contextIsolation`
