### ISSUE TITLE
[Feature Request]: screen.getDisplayScreenPoint

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#33365]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There don't seem to be a function for retrieving the coordinates of the cursor in the screen relative to the current display.

### Proposed Solution

I think there should be a `screen.getDisplayScreenPoint` that does this basically:

```js
const point = screen.getCursorScreenPoint ();
const display = screen.getDisplayNearestPoint(point);
const bounds = display.bounds;
const displayPoint = { x: point.x - bounds.x, y: point.y - bounds.y };
```

### Alternatives Considered

Write the function myself.

**Comment by miniak** [comment]
There is no point exposing an API for something that you can calculate yourself using existing Electron APIs.

**Comment by miniak** [comment]
Also the `screen` API in Electron basically maps to this in Chromium https://source.chromium.org/chromium/chromium/src/+/main:ui/display/screen.h

**Comment by fabiospampinato** [comment]
> There is little benefit exposing an API for something that you can calculate yourself using existing Electron APIs.

I mean there's a threshold somewhere, everything that Electron does can be done with just Node and some more code, should we delete Electron then? For this case in particular IMO the argument is that implementing this is easy enough, the function itself may be useful enough, but before knowing how to implement it it's unclear how that could be done, there's some benefit in providing little convenience utilities like that.

**Comment by miniak** [comment]
I get your point, but I also think that this function has a niche use case. Anybody from @electron/wg-api has a different opinon?

**Comment by miniak** [comment]
@fabiospampinato btw where do you need this functionality in your app?

**Comment by fabiospampinato** [comment]
> @fabiospampinato btw where do you need this functionality in your app?

I'm playing with the following: I have a highly dynamic app menu, most of the times it gets updated that's entirely wasted time as it will get updated again before the user ever opens it, so I was playing with skipping updates if the cursor on Linux and macOS is far enough from the menubar basically.
