### ISSUE TITLE
[Feature Request]: Expose Buffer constructor

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#33370]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Some Electron APIs return a Buffer, but Node integration can be disabled in which case the Buffer can't be used directly or imported from the "buffer" module. It's strange how in that case you can have to deal with Buffers without being able to make them yourself.

### Proposed Solution

Electron should probably expose the Buffer object itself.

### Alternatives Considered

It looks like a reference to the Buffer object can already be retrieved with some gymnastics, it'd be nice if this became just a regular import, like `import {Buffer} from 'electron';`.

```ts
require ( 'electron' ).clipboard.readImage ().toPNG ().constructor
```

**Comment by fabiospampinato** [comment]
Also the Buffer is like 10x faster at some things than whatever regular JS code that does the same thing that you can write, so if a Buffer is being used by Electron anyway maybe let's just export it and encourage using the performant way of doing things.

**Comment by fabiospampinato** [comment]
This should be a bit better actually, no need to waste time with a potentially huge image in the clipboard:

```ts
require ( 'electron' ).clipboard.readBuffer ( 'buffer' ).constructor
```

**Comment by miniak** [comment]
you can expose the `Buffer` constructor in the preload script

**Comment by fabiospampinato** [comment]
Yeah but I would have to import it from Node, ideally I'd want to import it from Electron.

**Comment by miniak** [comment]
preload.js
```
const buffer = Buffer;
process.once('loaded', () => {
  window.Buffer = buffer;
});
```

**Comment by miniak** [comment]
of course this only works with `contextIsolation: false`

**Comment by miniak** [comment]
> Fair enough, but that's not what I was asking for, which I think is what should happen.
if you were asking for `import {Buffer} from 'electron';`, then it does not really make sense as `Buffer` is already available as a global.

**Comment by miniak** [comment]
cc @electron/wg-api

**Comment by fabiospampinato** [comment]
🤔 I think I might have misunderstood how this works if there's no scenario where Node is unavailable but you can import the clipboard module from electron for example.
