### ISSUE TITLE
[Feature Request]: restore search_paths sequence

### ISSUE THREAD

**Issue by thiled** [electron/electron#33385]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I found  the node entry search_paths changed from
app->app.asar->default_app.asar (before v15)
to
app.asar->app->default_app.asar  (v15 & later)
I don't know why you did this change, but it has brought some inconvenience.
In windows, the app.asar can be hot updated conveniently by previus search_paths sequence before v15, and now this gets a little tricky.

### Proposed Solution

node entry search_paths sequence restore to 
app->app.asar->default_app.asar

[in](https://github.com/electron/electron/blob/main/shell/common/node_bindings.cc)

### Alternatives Considered

Consider that app.asar will be occupied by the process in windows, the update process is as follows:
there are app.asar and updater in resource folder
run electron.
when a new update found, download update asar to resource folder named update.asar
change updater to app and restart
updater is now running as app
remove app.asar
rename update.asar-> app.asar
rename app->updater
restart, done!

**Comment by miniak** [comment]
cc @MarshallOfSound

**Comment by MarshallOfSound** [comment]
The flow you describe is actually problematic for security reasons and partially the reason we changed the order.

Please don't hot update your ASAR file, it won't be possible soon on windows and on macOS ASAR integrity already prevents it.
