### ISSUE TITLE
[Bug]: Missing `compositionupdate` IME events with Sogou Chinese input

### ISSUE THREAD

**Issue by Eugeny** [electron/electron#33386]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

13.1.6

### Expected Behavior

IME input should send the full range of `compositionupdate`/`compositionend` events:

![](https://user-images.githubusercontent.com/161476/158031790-0cc48356-ad9d-4cf2-81d5-8d6053e699dd.png)

### Actual Behavior

`keydown` and `compositionupdate` events are missing.

![image](https://user-images.githubusercontent.com/161476/159514181-b3e823de-9aed-4205-bb0c-e2d0fc2e07a7.png)

### Testcase Gist URL

`yarn electron https://w3c.github.io/uievents/tools/key-event-viewer.html`

### Additional Information

I've bisected it down to this PR: https://github.com/electron/electron/pull/29204 but can't make any further progress as I'm not aware how IMEs interact with window focus states

NB: the events are sent as expected in Chrome

**Comment by asd281533890** [comment]
bump

**Comment by zhipengzuo** [comment]
anyone solving it?

**Comment by LY1806620741** [comment]
我也查到了这个问题, 有人能解决么？I also found this problem. anyone solving it?

**Comment by asd281533890** [comment]
bump

**Comment by 1339240789** [comment]
bump

**Comment by 1339240789** [comment]
bump

**Comment by 1339240789** [comment]
bump

**Comment by li-junpeng** [comment]
这个问题我得到了解决。

**Comment by asd281533890** [comment]
> 这个问题我得到了解决。

请问怎么解决的？ @li-junpeng

**Comment by li-junpeng** [comment]
> > 这个问题我得到了解决。
> 
> 请问怎么解决的？ @li-junpeng

这个问题好像不是Electron的bug，是搜狗输入法的bug，今天我联系了搜狗输入法的开发人员，他给我的软件做了适配，这个问题就解决了。
根据官方开发人员的描述，在不做适配的情况下，可以尝试着修改YourAppName.exe的名称为chrome.exe是可行的。后来我发现vscode中也适配了搜狗输入法，我把YourAppName.exe改成Code.exe也是可行的。如果想要适配自己的软件名称，就只能去联系搜狗输入法的开发人员做适配了。

**Comment by li-junpeng** [comment]
> > > > 这个问题我得到了解决。
> > > 
> > > 
> > > 请问怎么解决的？ @li-junpeng
> > 
> > 
> > 这个问题好像不是Electron的bug，是搜狗输入法的bug，今天我联系了搜狗输入法的开发人员，他给我的软件做了适配，这个问题就解决了。 根据官方开发人员的描述，在不做适配的情况下，可以尝试着修改YourAppName.exe的名称为chrome.exe是可行的。后来我发现vscode中也适配了搜狗输入法，我把YourAppName.exe改成Code.exe也是可行的。如果想要适配自己的软件名称，就只能去联系搜狗输入法的开发人员做适配了。
> 
> 非常感谢！如果找搜狗的开发人员适配，是只需要提供exe的名称就行了吗？因为我做的软件是仅供公司内部使用的，没办法提供给搜狗开发人员他们 @li-junpeng

是的，只需要提供正确的APP名称给他们就行了。这个是公共的issues，为了维护社区环境，如果还有什么疑问，可以加我QQ:1635975742进行讨论。

**Comment by codeingforcoffee** [comment]
bump

**Comment by synw1024** [comment]
bump

**Comment by allWZQ** [comment]
bump

**Comment by safecat** [comment]
bump

**Comment by cavivie** [comment]
bump
