### ISSUE TITLE
[Bug]: Renderer crash on resize while streaming WebRTC desktop

### ISSUE THREAD

**Issue by DanielMcAssey** [electron/electron#33411]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0-beta.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19044

### What arch are you using?

x64

### Last Known Working Electron version

16.1.0

### Expected Behavior

While streaming WebRTC, if the user resizes window or restores/maximises window it should not crash the renderer

### Actual Behavior

The renderer crashes

### Additional Information

I can provide a minidump file of the crash privately

The error is **EXCEPTION_ACCESS_VIOLATION_READ** in **InterpolateRow_SSSE3** in function **ScalePlaneVertical** (scale_common.cc:1530)

I think in the LibUV library of Chromium?

**Comment by VerteDinde** [comment]
Thanks for reporting this! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

You mention sharing the minidump file privately - if you'd like to email it to me (vertedinde@electronjs.org), happy to take a look 🙂

**Comment by DanielMcAssey** [comment]
Sent the minidump. Will look at creating a repro, may take me a while as its WebRTC and can be a bit fiddly

**Comment by DanielMcAssey** [comment]
I have tracked it down to the bug being introduced between versions 17.0.0-alpha.4 and 17.0.0-beta.1
I could not launch later alpha versions to shorten the range as alpha.4 through alpha.6 would not launch due to an unrelated bug with those versions. 17.0.0-alpha.3 was the earliest working version.

https://github.com/electron/electron/compare/v17.0.0-alpha.3...v17.0.0-beta.1
