### ISSUE TITLE
[Feature Request]: Typescript list of Events

### ISSUE THREAD

**Issue by jdpaterson** [electron/electron#33410]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi,

I am wondering if a similar issue or feature already exists. I am looking to create a Typescript type that accepts only valid electron events. For instance the `BrowserWindow.on(event, listener)` , I'm looking for a list of all of the valid events for `.on`. Something like

```
type AllBrowserWindowOnEvents = {
    'always-on-top-changed': (e: Event, isAlwaysOnTop: boolean) => void;
    'app-command: (e: Event, command: string) => void;
    ...and all of the other events, except I don't want to type them out
};
```
Does such a type already exist? 

I tried things like:

```
type BrowserWindowOnEvents = Parameters<InstanceType<typeof Electron.BrowserWindow>['on']>[0];
```
but that only ever gives me Intellisense for the last BrowserWindow.on event, which is 'will-resize'.

It does work if I have `new BrowserWindow().on('')`,  the intellisense will provide a list of all the possible events, but I'm looking to use it in a type definition when I don't have an instance of BrowserWindow.

Hope that makes sense, I would be willing to maybe put something together maybe for Electron-Userland but want to make sure nothing already exists.

Thanks

### Proposed Solution

A type that lists all of the valid events for various listeners, ie 
```
type AllBrowserWindowOnEvents = {
      'always-on-top-changed': (e: Event, isAlwaysOnTop: boolean) => void;
      'app-command: (e: Event, command: string) => void;
 }
 ```
 Such a thing could be generated using the Typescript Compiler API

### Alternatives Considered

Something that already exists that I'm missing.

**Comment by vladimiry** [comment]
> but that only ever gives me Intellisense for the last BrowserWindow.on event, which is 'will-resize'.

TS doesn't support overloaded function args narrowing, see https://github.com/Microsoft/TypeScript/issues/26591 .

> Proposed Solution

I'd like this to happen to workaround the declined https://github.com/Microsoft/TypeScript/issues/26591 TS's issue as I also have a need to narrow the event args typing. But as far as I know TS declarations of @electron get generated from the docs which is not the same as manual typing.

**Comment by MarshallOfSound** [comment]
Unfortunately due to how we generate our documentation we can either (a) leave things as they are which is great for intellisense and the way 99% of our users will consume the electron types or (b) change things to use generics and inference but in a way that let's TS code consume the event types as enums in a nice way.

Personally I don't see a good way of doing both and I think the obvious choice is to keep doing (a).

We publish `electron-api.json` with every release, if you want you can manually generate your own `.d.ts` file with custom enums / structs using that JSON api definition
