### ISSUE TITLE
[Bug]: Resizing window inconsistent when the BrowserView intersects the edge of a frameless window

### ISSUE THREAD

**Issue by solarfluxx** [electron/electron#33424]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 21H2

### What arch are you using?

x64

### Last Known Working Electron version

17.1.2

### Expected Behavior

When resizing the window using the mouse, it should allow resizing.

### Actual Behavior

When resizing using the mouse, most of the time the cursor is "locked" to the browser window which prevents the window from being resized. However, some of the time it does work. It seems very inconsistent.

### Testcase Gist URL

https://gist.github.com/08a21fe0da32e9d647b1bd03934c7309

**Comment by apm963** [comment]
I am running into this too. It may have been introduced in #32871.

**Comment by solarfluxx** [comment]
After further investigation, with the same electron setup and Windows version I have discovered the following:

In electron version 17.0.0, resizing, drag regions, and the maximize/minimize animations work correctly.
In electron version 17.0.1, drag regions (`-webkit-app-region: drag;`) are broken, along with the maximize and minimize animations.
In election version 17.2.0, the drag regions are fixed but now the resize issue appears. The maximize and minimize animations are still broken.

**Comment by mankeheaven** [comment]
In electron version 17.0.1, 17.2.0, 15.4.2,  I can resize with right bottom cornor, can not resize with top, right, bottom, left edge.
which version is stable?

**Comment by mankeheaven** [comment]
13.5.2 is ok， but titlebar height can not update, is 30px,  I use this version
