### ISSUE TITLE
[Feature Request]: Support injecting external input events to BrowserWindow

### ISSUE THREAD

**Issue by chenzx** [electron/electron#33427]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I'm using Electron for the scene below: "cloud rendering"

Run a electron instance for a WebGL page, and inject a WebRTC client into the page, then the WebGL rendering result can be lively encoded to video stream, and streaming to a client chrome page.

However, i need to let client's user input events to be remote sent back to server-side electron window instance, but i found Electron's BrowserWindow doesn't provide such api.

### Proposed Solution

Add user input events inject api to Browser, such as BrowserWindow.sendInputEvent( event ); to support pass in raw touch{begin/move/end} or mouse{down/move/up} events...

### Alternatives Considered

If no such convenient apis, i had to use OS-specific way to do this, which is under investigation now...

**Comment by DanielMcAssey** [comment]
Can't you use IPC for this?

**Comment by chenzx** [comment]
IPC should be possible, since input events in chromium is sent by IPC, but it's usually sent from browser main window  to renderer process, not from external to browser window?

**Comment by Prinzhorn** [comment]
[`win.webContents.sendInputEvent(inputEvent)`](https://www.electronjs.org/docs/latest/api/web-contents#contentssendinputeventinputevent)?

**Comment by chenzx** [comment]
I didn't notice it, i'll have a try. thanks!
