### ISSUE TITLE
[Feature Request]: Set `border-radius` for `BrowserView`.

### ISSUE THREAD

**Issue by Shintarot** [electron/electron#33426]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am aware that currently the only setting items for BrowserView style are `setBounds` and `setBackgroundColor`.
https://www.electronjs.org/docs/latest/api/browser-view

Is there any way to set `border-radius` (rounded corner) for BrowserView?

If not, I would be very happy to see it implemented.

### Proposed Solution

I think it should be implemented in the constructor or instance method of BrowserView.

```
// in constructor
const view = new BrowserView({
    borderRadius: 12,
});

// instance method
view.setBorderRadius(12);
```

### Alternatives Considered

I have tried editing the HTML within webContents, but adding `border-radius` to `<html />` does not work (children do not fit).

**Comment by jordandearsley** [comment]
Please can we have this 🙏

**Comment by GGIEnrike** [comment]
I really want this feature implemented!
(Does commenting on an issue make it so that the devs notice it again? because I'm pretty sure it does, and that's why I'm writing this comment now)

**Comment by tri2820** [comment]
Hi team, can we have an update on this?

**Comment by avayedawadi** [comment]
Any update on this?

**Comment by GGIEnrike** [comment]
We should get this reconsidered by the devs

**Comment by alexi** [comment]
Would love to have this feature + drop shadow. It's hard to see how this could be implemented in a more general styling framework, but these are the two power tools of modern design so adding support for them would be high impact.

**Comment by jansenderr** [comment]
this would be an amazing feature. pls

**Comment by arn4v** [comment]
+1, would like this as well

**Comment by nemyagky** [comment]
+ 1 from me. My current solution is to overwrite page css styles and apply border radius by css

**Comment by ArcherGu** [comment]
This feature is so much needed! 😀

**Comment by itsnwa** [comment]
Yes please!

**Comment by augustdua** [comment]
Please give this feature!
