### ISSUE TITLE
[Bug]: upgrade 15.3.6->16.0.0 . I can see the cmd of the exe file executed in childprocess.

### ISSUE THREAD

**Issue by HarunoOi** [electron/electron#33425]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows10 21H2

### What arch are you using?

x64

### Last Known Working Electron version

15.3.6

### Expected Behavior

Cannot see cmd of exe file executed by child process.

### Actual Behavior

The exe file that is contained within the application is being executed internally by child_process.
After updating Electron from 15.3.6 to 16.0.0, a command prompt is launched when the exe file is executed.

`child_process.spawn(exePath, args, {cwd: this.applicationResourcesPath, stdio: ['pipe', 'pipe', process.stderr]})`

### Additional Information

 electron-builder : 22.7.0

**Comment by Prinzhorn** [comment]
Dup https://github.com/electron/electron/issues/32334

**Comment by HarunoOi** [comment]
Thanks!Those problems were all resolved.
Use windowsHide option and update Node -> 16.13.0, electron-builder -> 22.14.13 .
