### ISSUE TITLE
refactor Electron's autofill implementation to work like Chromium's

### ISSUE THREAD

**Issue by ckerr** [electron/electron#33437]
Seen in c731103eac664f79bbf3574b7746e10e3e9b49b0, which says:

> https://chromium-review.googlesource.com/c/chromium/src/+/1652925 removed colors
 needed in chromium but our autofill implementation uses them.  This patch can be removed if we refactor our autofill implementation to work like Chromium's.

**Comment by jkleinsc** [comment]
- Closing as a duplicate of #31697
