### ISSUE TITLE
[Feature Request]: API Docs webFrame.insertCSS wrong heading level

### ISSUE THREAD

**Issue by TheIceCreamBear** [electron/electron#33451]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When viewing the API docs, specifically the page [webFrame](https://www.electronjs.org/docs/latest/api/web-frame), the item [webFrame.insertCSS](https://www.electronjs.org/docs/latest/api/web-frame#webframeinsertcsscss-options) has the wrong heading level.

### Proposed Solution

Remove the extra '#' character from the relevant markdown file.

### Alternatives Considered

None. There is only one way to improve this.

### Additional Information

Fixing this is also beneficial for users with screen readers, as they heavily rely on headings to know where on the page they are.

**Comment by miniak** [comment]
@TheIceCreamBear why don't you just create a PR with a fix?

**Comment by TheIceCreamBear** [comment]
@miniak Originally it was because I did not want to fork the repo, but I have some time to fix it so I will create a PR for it

**Comment by miniak** [comment]
@TheIceCreamBear thanks!

**Comment by miniak** [comment]
@TheIceCreamBear you can actually edit files directly on github without having to clone the repro locally :)
