### ISSUE TITLE
[Bug]: webkit-app-region: drag prevent click

### ISSUE THREAD

**Issue by SquitchYT** [electron/electron#33462]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 21H2

### What arch are you using?

x64

### Expected Behavior

With native app and also with some electron based app like VSCode, the titleBar is draggable, but you can also double-click to maximize / minimize the window. All click and mouse event should be fired with `webkit-app-region: drag`

### Actual Behavior

However, the `webkit-app-region: drag` prevent all click or mouse event to be fired. It's impossible to detect when a user double-click on my custom titlebar

### Additional Information

VSCode have a custom titlebar that can be dragged, and support the double click to maximize or minimize

**Comment by zcbenz** [comment]
This is unfortunately an issue we can not fix, please check https://github.com/electron/electron/issues/1354 for more discussion and workarounds.
