### ISSUE TITLE
[Question]Build source code in Windows canning error. Illegal character 

### ISSUE THREAD

**Issue by benjamin-coding** [electron/electron#33461]
Follow the electronjs.org guidelines below for building Electron itself case error :

../../electron\shell\common\extensions\api\cryptotoken_private.idl(5) : Unexpected EoF reached after

^
'canning error. Illegal character '

../../electron\shell\common\extensions\api\resources_private.idl(5) : Unexpected EoF reached after

^
'canning error. Illegal character '

how to resolve？

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by Dragon-S** [comment]
> 
Hello! I have the same problem, has your problem been solved?

**Comment by zsunpl** [comment]
I also encountered the same error, hope somebody can help! Thanks a lot!

**Comment by ZinkPavel** [comment]
Hello ! Someone solved this problem?
Communication with the community is useless

FYI: @benjamin-coding @Dragon-S  @zsunpl

**Comment by psi-4ward** [comment]
Is this a windows problem or can git handle it using `core.autocrlf`?

**Comment by ZinkPavel** [comment]
@psi-4ward problem on windows, maybe git will help
