### ISSUE TITLE
[Feature Request]: Allow for overriding existing window properties using contextBridge.exposeInMainWorld

### ISSUE THREAD

**Issue by BrandonXLF** [electron/electron#33460]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Right now it is not possible to override existing properties of the window object using contextBridge.exposeInMainWorld.

When this is attempted, the error at [this line](https://github.com/electron/electron/blob/28ada6ea8bd2abeca8812e6d284c1f5f3974286b/shell/renderer/api/electron_api_context_bridge.cc#L577) is thrown "Cannot bind an API on top of an existing property on the window object".

For my use case, I would like to override the alert/confirm/prompt functions so I can use my own popup for them, but when I do, the error is thrown.

### Proposed Solution

Per [this comment](https://github.com/electron/electron/pull/20307/commits/e897664c4fe8627bb1bbcb791c5c48b47c470ecb#r335215499), it looks like the error was added just to prevent users from unknowingly creating errors when overriding globals. An `allowOverride` parameter could be added to `contextBridge.exposeInMainWorld` to allow intentional overriding of globals. When set to `true`, overriding would be allowed.

If it's found there's no real reason to keep the error, then it could also just be outright removed.

### Alternatives Considered

It's possible to expose the APIs to the main world as a different name and then override the global from within the main world using something like `webFrame.executeJavaScript`, but this just adds an extra unnecessary step, especially when there are legitimate reasons to override globals such as implementing the alert/confirm/prompt functions.

**Comment by BrandonXLF** [comment]
@MarshallOfSound Would you be able to help with this?

**Comment by miniak** [comment]
@BrandonXLF you can use `webFrame.executeJavaScript()` in the preload script to execute code in the main world, which would overwrite the built-in APIs and call something exposed via `contextBridge.exposeInMainWorld` for example

**Comment by BrandonXLF** [comment]
> @BrandonXLF you can use `webFrame.executeJavaScript()` in the preload script to execute code in the main world, which would overwrite the built-in APIs and call something exposed via `contextBridge.exposeInMainWorld` for example

Yes, that is the method I am using for now. I've added it to the alternatives considered section.

**Comment by asger-finding** [comment]
+++ on this proposition!  
I'm trying to proxy `JSON.parse` in my application, but the website I'm targeting really isn't keen on having native functions changed at all (yes, I've tried a lot of tomfoolery to get around this. Proxy this, proxy that) but the site still somehow figues it out. Allowing overriding could save me a lot of headache.

**Comment by MarshallOfSound** [comment]
I think the barrier here is intentional and working as intended, as outlined above there are already ways around it (https://github.com/electron/electron/issues/33460#issuecomment-1081021990) and I don't think making this _easier_ to do will by for instance adding an override option will net-benefit the electron ecosystem
