### ISSUE TITLE
[Bug]: dns.reverse sometimes returns IP instead of hostname for a particular device

### ISSUE THREAD

**Issue by dtsmarin** [electron/electron#33485]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS 11.6 Big Sur

### What arch are you using?

x64

### Expected Behavior

I use dns.reverse to get the hostname of the device that connects to my Express server (local network). For most of the devices I've tried, it works flawlessly every time.

### Actual Behavior

But for some reason for one particular mobile device (Android Samsung), the first time I'll try to connect, it will return the IP address instead of the hostname. If I restart the Wifi connection on the device and try again then it works as expected!?

This is very strange because the exact same code used to work fine for the past few weeks I've been working on my app. 

The only thing that changed in my setup is that I switched to a new router (5GHz). That's all I can think of that changed since I've noticed the issue. When I used my old 2.4GHz router the same device worked fine every single time I ran my app.

All other devices I've tried (Windows, MacOS, Linux desktops) work fine even with the new router.

I don't know if this is a Node, an Electron, a weird router or a device issue. I'm perplexed of why this is even happening. How can I rule out Node and Electron?

**Comment by zcbenz** [comment]
`dns.reverse` is a Node.js API so this is very likely an issue of libuv, which we do not really have much idea.
