### ISSUE TITLE
[Feature Request]: support running desktopCapturer in chrome --headless mode

### ISSUE THREAD

**Issue by chenzx** [electron/electron#33494]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to use electron simply as a WebRTC stream publishing client to replace crippled ffmpeg/gstreamer.
The ffmpeg/gstreamer's RTP stream publishing cmdline cannot properly deal with WebRTC's RTCP/PLI keyframe request.

That is to say, i need the following code working:

```
const {app, BrowserWindow} = require('electron')
app.commandLine.appendSwitch('ignore-gpu-blacklist')
app.commandLine.appendSwitch('headless') //<--

  const mainWindow = new BrowserWindow({
    width: 1,
    height: 1,
    //no need to set show:false, since chrome's --headless mode is CLI mode without window...
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      preload: path.join(__dirname, 'preload.js')
    }
  });
```

### Proposed Solution

desktopCapturer api currently needs running in renderer side, but it should be able to run without window system.

### Alternatives Considered

If can support, electron will become the best/convenient full-functinal WebRTC client, used in App Window to Video Live Streaming scenario.

**Comment by zcbenz** [comment]
The problem is Electron does not really support headless mode (see https://github.com/electron/electron/issues/27052), I'm merging this to https://github.com/electron/electron/issues/228.
