### ISSUE TITLE
[Bug]: Frameless window cannot be resized properly. Not to be confused with #33458

### ISSUE THREAD

**Issue by SoftVibes** [electron/electron#33495]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 1703

### What arch are you using?

x64

### Last Known Working Electron version

17.1.1

### Expected Behavior

Frameless window should be properly resizable via the handles. The window size should change as per the usage of the resize handles on all corners and sides of the window.

### Actual Behavior

Frameless window cannot be resized properly with the resize handles. The window doesn't get resized to the expected size when resizing to a smaller size and the handles resist from resizing to a larger size than the current window size. Resizing to a smaller window size is unpredictable as whether the window actually gets resized after the user releases the click holding the resize handle is random. Double-clicking the title bar set with webkit-app-region doesn't maximize the window like it is supposed to. Not to be confused with https://github.com/electron/electron/issues/33458 which states an issue causing the window to be resizable from one corner resize handle and completely non-resizable from the others.

### Additional Information

It's also noteworthy that this result is observed in a very old version of windows 10 running on very low RAM.

**Comment by Hilogen** [comment]
Changed title

**Comment by CryUshio** [comment]
Same problem. 17.0.x works properly.

**Comment by Mad-hu** [comment]
13.*.* Same problem.

**Comment by Mad-hu** [comment]
您好：
      已经收到您的来信。
                            呼岩东

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump
