### ISSUE TITLE
[Bug]:  Wrong rendering since Electron 17 on macOS

### ISSUE THREAD

**Issue by Delagen** [electron/electron#33508]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.2.0 and later

### What operating system are you using?

macOS

### Operating System Version

12.3

### What arch are you using?

x64

### Last Known Working Electron version

16.2.0 and before

### Expected Behavior

Rendering as is

Electron 16.2.0

![image](https://user-images.githubusercontent.com/783335/160684898-a1fd252b-9035-40d3-8153-d81067542aaf.png)

### Actual Behavior

Rendering as something wrong

18.0 and 17.2.0

![image](https://user-images.githubusercontent.com/783335/160683975-1d85e10a-1e40-4d94-bf9f-4ec7485f3c9f.png)

### Additional Information

index.,html contains webview
background of index.html is blue, but webview streched so has another background

**Comment by zcbenz** [comment]
Do you have a minimal reproducible example for this issue?

**Comment by Delagen** [comment]
@zcbenz
[test.zip](https://github.com/electron/electron/files/8426760/test.zip)

```bash
npm ci
npm start
```

Windows
![image](https://user-images.githubusercontent.com/783335/161973206-93f53922-2cf1-48a0-86f7-c6c27a12a0a5.png)

MacOS
![image](https://user-images.githubusercontent.com/783335/161973267-271882ce-3005-4ca7-9eac-9e67164305f1.png)

**Comment by Delagen** [comment]
@zcbenz Any news?

**Comment by Delagen** [comment]
About a month without any action. @MarshalOfSound can you escalate this?

**Comment by codebytere** [comment]
I cannot reproduce this on macOS with your sample.
<img width="1169" alt="Screen Shot 2022-05-05 at 10 14 27 AM" src="https://user-images.githubusercontent.com/2036040/166885592-59fdd6e5-4d84-4edc-b411-3889e69c1cf6.png">

**Comment by Delagen** [comment]
> I cannot reproduce this on macOS with your sample. <img alt="Screen Shot 2022-05-05 at 10 14 27 AM" width="1169" src="https://user-images.githubusercontent.com/2036040/166885592-59fdd6e5-4d84-4edc-b411-3889e69c1cf6.png">

What version of electron do you use? What MacOS platform M1 or Intel?

**Comment by Delagen** [comment]
Just launched under electron 18.2 MacOS 12.2 Intel
![image](https://user-images.githubusercontent.com/783335/166899877-08bce95c-f97f-4e57-b6d8-5b4595d15ebd.png)

**Comment by codebytere** [comment]
I launched with macOS 12.3.1 Intel using Electron 18.2 as well.

**Comment by Delagen** [comment]
May be it caused by video driver used in VmWare Virtual Machine, because it running in it.

**Comment by Delagen** [comment]
Seems related to #33685 because 17.3.1 works.

**Comment by Delagen** [comment]
20 version is still affected

**Comment by 255kb** [comment]
I guess this is related or a dup of #33735

**Comment by Delagen** [comment]
@255kb I'm not sure. Since 21 version it works sometimes, but strucks after update from 17 version till empty cache. Start lasts about 10 minutes and rendering very slow.
