### ISSUE TITLE
[Bug]: Modifying require('module').globalPaths has no effect in Electron v17+

### ISSUE THREAD

**Issue by KishanBagaria** [electron/electron#33504]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0, 18.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

16.3.0

### Expected Behavior

Modifying `require('module').globalPaths` should work.

### Actual Behavior

After https://github.com/electron/electron/pull/31275, modifying `require('module').globalPaths` no longer has any effect. `module.paths` works but isn't a good alternative because it has to be called for each module.

electron-builder has been suggesting [using `require('module').globalPaths` for its two package.json structure](https://www.electron.build/tutorials/loading-app-dependencies-manually) and a lot of projects depend on it.

**Comment by zcbenz** [comment]
`Module.globalPaths` was never meant to be used outside Electron so I'm not really willing to bring the old behavior back, to achieve the same effect with `Module.globalPaths `, you can do something like this:

```js
   const nodeModulePaths = Module._nodeModulePaths;
   Module._nodeModulePaths = (from) => {
     return nodeModulePaths(from).concat(globalPaths);
   };
```

**Comment by KishanBagaria** [comment]
@zcbenz thanks for the workaround. What's the lowest Electron version it works with?

**Comment by zcbenz** [comment]
It should work for all versions of Electron.

**Comment by Sailiy** [comment]
` const Module = require('module');
  const nodeModulePaths = Module._nodeModulePaths;
  Module._nodeModulePaths = (from) => {
    return nodeModulePaths(from).concat(globalPaths);
  };`

你好，我现在也遇到了这样的问题，electron版本从12.2.3升级到18.3.7后，也遇到了这样的问题。这串代码是否有误？
我添加在程序内，不能正常工作。
