### ISSUE TITLE
CMD + Tab not working on Mac after exiting kiosk (full screen) mode

### ISSUE THREAD

**Issue by lfwolfe** [electron/electron#33503]
Electron Version: 17.1.2

Last know working version 12.0.5

OS Version: Mac OS Big Sur 11.6.4

Prerequisite: electron app that can transition to/from kiosk mode without exiting.

Expected Behavior: After exiting kiosk mode CMD + Tab, CMD + ` etc. should work.

Actual Behavior: CMD + Tab and any similar key combinations are non-functional as if still in kiosk mode.  After exiting or blurring the app, CMD + Tab are functional.  This bug was introduced in the 12.0.6 release.

Update: Menu bar is also hidden and remains hidden until electron app is blurred or exited.

**Comment by codebytere** [comment]
I ran https://gist.github.com/40902920c8fb6c0e2ebcd8fdb936cbf6 on macOS `v17.1.12` and experienced no issues - please provide a repro if you would like for us to continue triaging this.

**Comment by lfwolfe** [comment]
Will need approval to provide any code samples but did you attempt CMD + Tab while the app was in focus? works fine if the app is closed or looses focus.

**Comment by zcbenz** [comment]
I can reproduce on macOS 11.6 with the above example.

**Comment by sridharpg** [comment]
This is easily reproducible in the latest 21.1.1 version of electron. 
Mac OS Version 12.5.1

**Comment by sridharpg** [comment]
I noticed that the keyboard and menubar is muted because of the `SetFullScreen` call.

```
void NativeWindowMac::SetKiosk(bool kiosk) {
  if (kiosk && !is_kiosk_) {
    kiosk_options_ = [NSApp currentSystemPresentationOptions];
    NSApplicationPresentationOptions options =
        NSApplicationPresentationHideDock |
        NSApplicationPresentationHideMenuBar |
        NSApplicationPresentationDisableAppleMenu |
        NSApplicationPresentationDisableProcessSwitching |
        NSApplicationPresentationDisableForceQuit |
        NSApplicationPresentationDisableSessionTermination |
        NSApplicationPresentationDisableHideApplication;
    [NSApp setPresentationOptions:options];
    is_kiosk_ = true;
    SetFullScreen(true);
  } else if (!kiosk && is_kiosk_) {
    [NSApp setPresentationOptions:kiosk_options_];
    is_kiosk_ = false;
    SetFullScreen(false); <- the issue was due to this
  }
}
```

One way I have solved this issue is using the below hack:

```
ipc.on('toggleKioskMode', (event) => {
      let isInKioskMode = win.isKiosk();
      win.setFullScreen(!isInKioskMode);
      setTimeout(() => {
          win.setKiosk(!isInKioskMode);
      });
  });
```
