### ISSUE TITLE
[Bug]: Embedded PDF not displaying

### ISSUE THREAD

**Issue by jannis6023** [electron/electron#33519]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0

### What operating system are you using?

macOS

### Operating System Version

MacOS 12.3

### What arch are you using?

x64

### Expected Behavior

PDF File should be displayed just like when opening the page in Chrome browser.

### Actual Behavior

The PDF file isn't displayed in the Embed.
Screenshot:
![Bildschirmfoto 2022-03-30 um 16 04 47](https://user-images.githubusercontent.com/40733092/160853634-a903d3b1-c11d-4b93-84ae-64af05e17ec9.png)
=> Error loading PDF document. 

### Additional Information

I use this html for displaying it:
`<embed type="application/pdf" src="https://....." style="width: 100%; height: 30rem;">`
The document URL in here is a Blob URL with a PDF fetched from an internal API.

The window is loaded using this code:
```
const { app, BrowserWindow } = require('electron')
const createWindow = () => {
    const win = new BrowserWindow({
        width: 1400,
        height: 800,
        webPreferences: {
            plugins: true
        }
    })

    win.loadURL("https://127.0.0.1:8000/app")
}

app.whenReady().then(() => {
    createWindow()
})
```

**Comment by codebytere** [comment]
Bisected to https://github.com/electron/electron/compare/v18.0.0-alpha.5...v18.0.0-beta.1

**Comment by lishid** [comment]
Hmmm just reading the PR in #33560 it doesn't sound like the patch actually closes this specific issue.

> Addresses a failure introduced by [CL:3501416](https://chromium-review.googlesource.com/c/chromium/src/+/3501416), whereby if a PDF failed to load: [...] 
> and a user then clicked the Reload button, the following error would be seen in console:
> [...]
> Notes: Fixed an issue where the PDF Viewer would fail if a user attempted to reload.

I don't have a way to test this until it's released but hopefully it actually fixes the broken PDF viewer for blob: URLs (and not just the Reload button).

**Comment by codebytere** [comment]
@lishid correct - it should be this one: https://github.com/electron/electron/pull/33664. I'll update the markings.

**Comment by sofianguy** [comment]
Fixed https://github.com/electron/electron/pull/33664

**Comment by george-thomas-hill** [comment]
@sofianguy :

I'm still finding (in Electron 21.2.0) that loading a PDF in an iFrame fails to display the PDF, and loading a PDF in a webview crashes Electron.

Here's an Electron Fiddle gist that demonstrates this:

https://gist.github.com/george-thomas-hill/c3179e6eddeb1a2715201a20dbf95015

Could you please take another look at this?
