### ISSUE TITLE
[Bug]: Recreating a menu with the "close" role causes several issues on macOS

### ISSUE THREAD

**Issue by mitchchn** [electron/electron#33521]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Replacing the application menu with different entries and roles should be possible without any issues.

### Actual Behavior

A menu with the "close" role cannot be created multiple times without issues on macOS:

1. Creating a menu with the "close" role more than once causes the "Close All" entry (exposed by holding Option while the menu is option) to have the label "<<Close All - unlocalized>>"

2. Removing the role from the "Close" entry and adding it back causes the menu to now show two Close entries, one with the strange label:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/7342119/160878099-8e840db7-10dc-4792-bef9-8a1bc4621ac6.png">

### Testcase Gist URL

https://gist.github.com/70e78bc417f2402c4276f1335676a8b1

### Additional Information

On macOS we need be able to recreate the global application menu several times over the lifecycle of the app, since the menu entries and their behaviour depend on the app state and context. 

The label bug can also be reproduced in production in other Electron apps like Slack:

1. Close the main Slack window
2. Reopen with the first workspace shortcut key (Command-1)
3. Open the File menu and hold down Option to see "<<Close All - unlocalized>>"

**Comment by codebytere** [comment]
@mitchchn hmm - what language is your OS set to? I ran the repro and saw only "Close All" and "Close Window" with no  strange labeling at any point on macOS Big Sur with 18.0.0

**Comment by mitchchn** [comment]
Here's a video for good measure:

https://user-images.githubusercontent.com/7342119/161087594-bae17347-56b8-4580-8967-ae97638a7bbb.mp4

**Comment by zcbenz** [comment]
This bug reproduces on my Intel macOS 11.6, and the "<<Close All - unlocalized>>" item shows without pressing Option.

**Comment by codebytere** [comment]
@mitchchn also got it to repro! i'll see what i can do :D

**Comment by AlbertInRC** [comment]
bump
