### ISSUE TITLE
[Bug]: Blurry Icon in Windows Search Results

### ISSUE THREAD

**Issue by weiliu-2020** [electron/electron#33530]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home

### What arch are you using?

x64

### Expected Behavior

Icon should be clear, not pixelated.

### Actual Behavior

Hi, I'm experimenting with a small app for my personal use (Things), and now struggling with the icon. While it looks ok-ish elsewhere, in the search results from start menu or search bar, the bigger icon on the right (above the options) seem quite pixelated. I'm using 256*256 ico in the build folder as instructed. What goes wrong here?
Screenshot here: https://ibb.co/9p5Y5pD
Screenshot of another app for comparison: https://ibb.co/SPpbfbS

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
