### ISSUE TITLE
[Bug]: 18.0.0 cannot start on Ubuntu 20 aarch64

### ISSUE THREAD

**Issue by klossner** [electron/electron#33533]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 18.04.6 LTS

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

17.0.0

### Expected Behavior

Starting any Electron app does not immediately fail.
"ldd electron" doesn't show errors.

### Actual Behavior

% ldd electron
electron: /usr/lib/aarch64-linux-gnu/libxkbcommon.so.0: version `V_1.0.0' not found (required by ./electron)

### Additional Information

Appears to be this chromium bug:
[https://bugs.chromium.org/p/chromium/issues/detail?id=1302542](https://bugs.chromium.org/p/chromium/issues/detail?id=1302542)

**Comment by sohobloo** [comment]
still in 18.2.0
will this be fixed in 18.x as it makes 18.x not a cross-all-platform version.

**Comment by theofficialgman** [comment]
please fix this bug in 18.X electron, this is a breaking issue for using electron on older linux releases like ubuntu bionic and buster

**Comment by theofficialgman** [comment]
@zcbenz please fix this with https://chromium-review.googlesource.com/c/chromium/src/+/3480519 or assign someone to do it. many projects are upgrading to electron 18 daily and this is a breaking change for them in terms of compatibility with debian buster, ubuntu bionic and focal, and other distros

**Comment by MarshallOfSound** [comment]
Fixed in #34155
