### ISSUE TITLE
[Bug]: The .uuid file problem is generated in the /usr/share/fonts/ directory under the linux platform

### ISSUE THREAD

**Issue by lixingithub** [electron/electron#33534]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

4.0.6

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 16.04

### What arch are you using?

x64

### Last Known Working Electron version

6.1.7

### Expected Behavior

No .uuid file is generated when I run as administrator with electron 4.0.6 on the linux platform

### Actual Behavior

When I run electron 4.0.6 version or electron 6.1.7 version with administrator privileges in linux, a .uuid file will be generated in the /usr/share/fonts/ directory, which will cause confusion in the system font library. How can I prevent it electron generates this file in the directory

**Comment by codebytere** [comment]
@lixingithub Electron is not supported below v15. Please open a new issue if it's still present on a supported version.
