### ISSUE TITLE
[Bug]: Window is sometimes unfocusable and unclickable on startup

### ISSUE THREAD

**Issue by MasDevProject** [electron/electron#33548]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0

### What operating system are you using?

macOS

### Operating System Version

Monterey

### What arch are you using?

x64

### Expected Behavior

When an Electron program starts, the windows should be focused.

### Actual Behavior

I'm using the [Electron officiale quick start project](https://github.com/electron/electron-quick-start).
I downloaded the code and performed an `npm install`.

After opening and closing the app several times, the app starts unfocused.
You can noticed that the window is unfocused because of the title is greyed out.
You can also see I wrote a :hover css class and, when the app starts unfocused, the :hover rule does not work.
But if I double click the button, then the css rule works.

If I switch to an other window and then come back to Electron, everything works correctly.
I recorded a small [video here](https://drive.google.com/file/d/1_C4vDaXCt3MJXulsaXVHoC5DH6_9tcSW/view?usp=sharing). The issue start on second 35

**Comment by zcbenz** [comment]
This behavior also happens when showing GUI from unbundled terminal programs, so I tend to think this as a glitch of macOS. None of signed apps suffer from this problem as far as I know.

**Comment by uropsm** [comment]
In my case, It is happening more frequently (90% over) than the above video.
I tried with several versions of electron and the result was the same.
It is sad for mac developers.

**Comment by miniak** [comment]
We seem to be hitting a similar issue in Teams. Is there really nothing that can be done about it?

**Comment by miniak** [comment]
The video from the description is no longer available, I was able to reproduce it with Fiddle like this:
https://github.com/electron/electron/assets/1281234/f26669ea-8659-4dcd-b451-7bf99591a453

**Comment by miniak** [comment]
cc @deepak1556, @zcbenz

**Comment by zcbenz** [comment]
@miniak Did you see the problem when running the packaged app (e.g. double clicking `Teams.app`), or when in development mode (e.g. `electron /path/to/teams/main.js`)?

**Comment by miniak** [comment]
@zcbenz packaged app, fully signed

**Comment by zcbenz** [comment]
I can reproduce this on my machine.
