### ISSUE TITLE
SHASUMS256.txt file not downloaded for Electron v 17.3.1

### ISSUE THREAD

**Issue by ranjan34** [electron/electron#33555]
We have been using electron since a year, earlier with older electron versions, when I try to build our application, SHASUMS256.txt was being downloaded into local path %appdata% .

Now I am upgrading electron to 17.3.1 , but I don't see SHASUMS256.txt in the local path %appdata%.

Could you clarify me why it's not downloaded, Am I missing something ?

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
