### ISSUE TITLE
How to detect when window title has changed, and get the title?

### ISSUE THREAD

**Issue by danimesq** [electron/electron#33577]
This should be a complement to setting the window title.

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
