### ISSUE TITLE
[Feature Request]: Over Riding Gnome and KDE themes

### ISSUE THREAD

**Issue by RyzenDew** [electron/electron#33570]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

![image](https://user-images.githubusercontent.com/84041391/161204843-a5855e3a-837a-410b-9e45-438b640a1ff3.png)
![image](https://user-images.githubusercontent.com/84041391/161204879-b8e194a5-b17d-429c-933d-b63ebeb7903a.png)
As shown above discord and cider have there own themes but on linux as shown below its taken over by gnome or KDE and cutefish DE
Linux 
![image](https://user-images.githubusercontent.com/84041391/161205024-11267246-5042-4e1c-80e1-6e7d1a0f69d4.png)
![image](https://user-images.githubusercontent.com/84041391/161205056-07d1010f-08cb-4a26-aaad-680106e9948b.png)

### Proposed Solution

so can you add the ability to give the devs to control themeing 
so if cider want's to look like Apple's music app fully it can like in windows
and if discord doesnt want an ugly title bar it wont have to use one

### Alternatives Considered

N/A

### Additional Information

thanks for hearing me out

**Comment by jannuary** [comment]
Themes have nothing to do with this? Electron doesn't follow either KDE or GNOME stylesheets.

What you're thinking of is window decorations.

**Comment by Lampomaniac** [comment]
This has to do with client side window decorations, which I'm pretty sure are already available in the latest version of Electron.

**Comment by zcbenz** [comment]
As mentioned above the client side decorations on Linux is already supported in Electron and it is app developers' choice to use it or not, so I'm closing this issue.
