### ISSUE TITLE
zoom-changed event not emitted on [role-based] menu triggered from keyboard

### ISSUE THREAD

**Issue by ajoslin103** [electron/electron#33572]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.2.0

### What operating system are you using?

macOS

### Operating System Version

12.3

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

When I change the zoomFactor using the keyboard, as supported by this menu structure 

```
  menu.append(
    new MenuItem({
      label: "Zoom",
      submenu: [
        { role: "zoomIn" },
        { role: "zoomOut" },
        { role: "resetZoom" },
      ],
    },
```

I expected a zoom-changed event to be received, so I can update the saved state for the window

`win.on("zoom-changed", saveState);`

### Actual Behavior

When I change the zoomFactor using the keyboard, as described 

The window contents zoom in and out as expected

No "zoom-changed" event is emitted on the window

Which makes sense by the docs...  https://www.electronjs.org/docs/latest/api/web-contents#event-zoom-changed 

But since Electron is handling the whole thing shouldn't it emit an event on the front() window saying it did?

One could ask, what events should Electron emit on which objects, when menu items are triggered 

Especially if the declaration of a menu item is purely role-based

Perhaps start a message channel on the menu & emit [ "menu-event", menuItemConfig ] 

### Additional Information

ref: arch: uname -m = x86_64

**Comment by codebytere** [comment]
@ajoslin103 

Per docs:
> Emitted when the user is requesting to change the zoom level using the mouse wheel.

You're changing it with the scroll wheel, which doesn't cause this event to be emitted.

**Comment by ShGKme** [comment]
Does it mean that there is no way to handle zoom changed via the default menu item with roles / shortcuts?
- `zoom-changed` is only triggered on wheel/touchpad
- Menu items with `role` don't trigger `click` option

For example, to save zoom level, or to apply it to `titleBarOverlay.height`.

A workaround could be to create custom menu items, but then it looses the default localization...
