### ISSUE TITLE
[Documentation] browserWindow event.returnValue contradiction

### ISSUE THREAD

**Issue by whudson** [electron/electron#33581]
### Documentation Issue

Please see this commit https://github.com/electron/electron/commit/bb153ee79e6bb4e54d4d075f64a448f498fbeff8 which, without explanation, says that it is both _recommended_ **and** _not recommended_ to set the event.returnValue directly. 

Is it possible to disambiguate this or provide a further explanation for the comment?

**Comment by zcbenz** [comment]
Thanks for noticing this, setting `e.returnValue` is preferred.
