### ISSUE TITLE
[Bug]: blurry text on wayland session

### ISSUE THREAD

**Issue by enx1998** [electron/electron#33583]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0-alpha.1, 18.0.1, 17.3.1

### What operating system are you using?

Other Linux

### Operating System Version

Gentoo 5.15.11-gentoo-x86_64, Ubuntu 22.04, KDE NEON

### What arch are you using?

x64

### Last Known Working Electron version

15.3.4

### Expected Behavior

When running electron with these command line options: `--enable-features=UseOzonePlatform --ozone-platform=wayland`, or in addition with `--enable-features=WaylandWindowDecorations`, the text should be always clear respecting the screen scale settings. 

### Actual Behavior

When unning electron with these command line options: `--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WaylandWindowDecorations` the text is blurry, and it becomes clear after reloading.

![immagine](https://user-images.githubusercontent.com/20546217/161394507-f7fe7016-67b9-48a9-802e-79c07862c06b.png)

after reloading

![immagine](https://user-images.githubusercontent.com/20546217/161394549-4d831177-c0ca-4f64-80c8-d911139876f8.png)

The same thing happens without using `--enable-features=WaylandWindowDecorations` command line option.

**Comment by miniak** [comment]
@enx1998 title?

**Comment by enx1998** [comment]
@miniak Sorry for forgetting to enter the title, I've added it.

**Comment by zcbenz** [comment]
Does Chromium browser have the same problem on your machine?

**Comment by enx1998** [comment]
Hi @zcbenz, with Chromium I don't have this problem, it works well.

**Comment by enx1998** [comment]
Hi @zcbenz I realised just now that the same thing happens with Chromium 99.0.4844.84 and Chrome 100.0.4896.75.
Thanks, ENx

**Comment by avdhoot** [comment]
now realised why brave `Version 1.37.116 Chromium: 100.0.4896.127 ` behave like that. Initially thought, might be my system issue.

**Comment by KucharczykL** [comment]
Chromium 101 seems to have fixed the problem.

**Comment by enx1998** [comment]
I have the same issue with Chromium `101.0.4951.54`

**Comment by xsrvmy** [comment]
Having same problem here. I can't pinpoint when this occured because I have been using X11 for electron apps for a while after the wl_output issue. The problem occurs in chrome 102 and 103 as well.
It seems to have something to do with poor dpi detection. My laptop is hidpi, and the issue only seems to happen when a normal dpi monitor is plugged in. I am on swaywm so this is not just some issue with GNOME/mutter.

**Comment by hedgepigdaniel** [comment]
On Chromium (105) I cannot reproduce this bug, whereas on Electron 17, 18, and 19 I can.

I can't say for sure which versions, but I regularly use Chromium and I have not seen this bug in Chromium.

**Comment by KucharczykL** [comment]
I haven't encountered this bug for months now. This is both for Electron 20 (standalone, just to test) and Electron 19 (in VSCode).

**Comment by claui** [comment]
Me neither (for Electron 19).

**Comment by nuclearforg** [comment]
I'm encountering this bug with Electron 20 (standalone and in Obsidian). Electron 19 is fine (standalone and in VSCode)

**Comment by go-xoxo** [comment]
i have this problem with several electron apps like VS Code, Docker, MS Terminal on Windows though. But the problem seems to not have been understood completely as it persists since 2018.
