### ISSUE TITLE
[Bug]: fullscreenable is not working while using titleBarStyle: 'hidden'

### ISSUE THREAD

**Issue by RomanSterlin** [electron/electron#33582]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

The fullscreen button should be disabled as it is when not using the titleBarStyle flag.

### Actual Behavior

fullscreen button keeps working with fullscreenable  set to false.

**Comment by zcbenz** [comment]
I think neither Electron nor Chromium adds fullscreen button to the window, can you paste a screenshot?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
