### ISSUE TITLE
[Feature Request]: official support for disabling site isolation

### ISSUE THREAD

**Issue by bughit** [electron/electron#33585]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

[Site isolation](https://www.chromium.org/Home/chromium-security/site-isolation/) causes cross-site navs and cross-site frames to spawn a new renderer. In certain use-cases you want to minimizing cpu and memory utilization, so it would be nice to have official support for disabling site isolation and have all content live in a single long lived renderer process.

### Proposed Solution

A documented api to disable site isolation e.g. `app.siteIsolation = false`

### Alternatives Considered

`disable-site-isolation-trials` switch does the job currently. But there's some unintentional fear uncertainty and doubt around it.

- Is it and will it continue to be supported by electron?
- Will it be removed by chromium? Its name (trials) kind of suggests something transitory

**Comment by miniak** [comment]
As you said, it can be disabled using `disable-site-isolation-trials`. There is no point in adding an Electron API for this as we cannot guarantee Chromium is not going to remove support for disabling it.
