### ISSUE TITLE
[Bug]: Color Picker displays incorrectly in high contrast mode

### ISSUE THREAD

**Issue by FlysoftBeta** [electron/electron#33588]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0-alpha.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2

### What arch are you using?

x64

### Expected Behavior

Color Picker displays incorrectly in high contrast mode
![image](https://user-images.githubusercontent.com/49718840/161409539-af000a81-8f8c-4074-94f7-2f11fcba2024.png)

### Actual Behavior

It should display correctly:
![image](https://user-images.githubusercontent.com/49718840/161409470-2eb93492-fe1f-4dd6-bee7-799ba2213ff9.png)
(DevTools color picker)

### Testcase Gist URL

https://gist.github.com/bd6c557d6d34f4fde730460b3be391c4

### Additional Information

It seems an upstream bug, and it also happens in Microsoft Edge:
![image](https://user-images.githubusercontent.com/49718840/161409443-cdbc4d0d-0d79-4883-9849-2551864dd6c4.png)

**Comment by codebytere** [comment]
@FlysoftBeta this is something you should file a bug upstream for, perhaps at crbug. When a fix is applied there we'll pick it up automatically through a Chromium update.
