### ISSUE TITLE
[MAS Rejection]: non-public or deprecated APIs _responsibility_get_pid_responsible_for_pid

### ISSUE THREAD

**Issue by Chris55** [electron/electron#33580]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Electron Version

18.0.1

### Rejection Email

Hello, 

Thank you for submitting your items for review. We noticed an issue with your submission that requires your attention. 

> Guideline 2.5.1 - Performance - Software Requirements
> 
> 
> 
> Your app uses or references the following non-public or deprecated APIs:
> 
> Info
> • Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_responsibility_get_pid_responsible_for_pid
> 
> The use of non-public or deprecated APIs is not permitted on the App Store, as they can lead to a poor user experience should these APIs change and are otherwise not supported on Apple platforms.
> 
> Next Steps
> 
> It would be appropriate to revise your binary and remove any references to the non-public or deprecated APIs identified above. 
> 
> If you are using third-party libraries, update to the most recent version of those libraries. If you do not have access to the libraries' source, the following command line tools can help you identify the location of problematic code:
> - The "strings" tool can output a list of the methods the library calls.
> - The "otool -ov" tool will output the Objective-C class structures and their defined methods.
> 
> Resources
> 
> - We are constantly reevaluating and identifying non-public APIs that you may have been using for an extended period of time. Always use [public APIs and frameworks](https://developer.apple.com/documentation/) and ensure they are up to date.
> - If there are no alternatives for providing the functionality your app requires, you can use [Feedback Assistant](https://feedbackassistant.apple.com/welcome) to submit an enhancement request.
> 

### Additional Information

Previous submission using Electron 17.1.2 (2 weeks ago) was accepted...

**Comment by Chris55** [comment]
After a second tentative, the answer was:

> Guideline 2.5.1 - Performance - Software Requirements
> 
> 
> 
> Your app includes a version of an SDK from Electron that violates the [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/). The version of the Electron SDK you are using in your app attempts to hide the use of private APIs. This is a violation Section 2.5.1 of the [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/).
> 
> Guideline 2.5.1: Apps may only use public APIs.
> 
> Next Steps
> 
> To resolve this issue, please either remove the Electron SDK entirely from your app, or revise your app to utilize a corrected version of the Electron SDK.

I'm going to downgrade Electron to 17.3.1 to check if this version is accepted on the Store...

**Comment by MarshallOfSound** [comment]
Downgrading to Electron 17 will work, this new code was added quite recently in Chromium.

Refs: https://source.chromium.org/chromium/chromium/src/+/main:base/process/process_info_mac.cc;l=18?q=responsibility_get_pid_responsible_for_pid&ss=chromium

It's only used for webauthn bluetooth support which I don't think Electron even initializes, I think we can safely strip out that symbol reference 👍

**Comment by Chris55** [comment]
Yep, Apple accepted my app once I downgraded to 17.3.1
