### ISSUE TITLE
Notifications from main process

### ISSUE THREAD

**Issue by s4y** [electron/electron#3359]
Is there any way to show notifications from the main process (i.e. without any windows open)? I've tried [node-notifier](https://github.com/mikaelbr/node-notifier) and it works but, since it shells out, all notifications show up on OS X as from "terminal-notifier", and some characters stop the notification from showing up at all.

![](https://cloud.githubusercontent.com/assets/111870/11010262/92e61744-84ab-11e5-87da-26f211834830.png)

**Comment by paulcbetts** [comment]
You can create a Window and just not show it.
