### ISSUE TITLE
[Bug]: ChildWindow created by BrowserProxy cannot load content

### ISSUE THREAD

**Issue by Alecyrus** [electron/electron#33612]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.01

### What operating system are you using?

macOS

### Operating System Version

macOS 12.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

17.3.1

### Expected Behavior

The window created by `window.open()` could load `https://github.com` rather than keep empty.

### Actual Behavior

1. Click `openWindow` in mainWindow
2. The childWindow does not  load `https://github.com` as expected

### Testcase Gist URL

https://gist.github.com/65d357f70c66de244c0d283f5eaa1e07

**Comment by Prinzhorn** [comment]
``` sh
childWindow.webContents.on('will-navigate', (e) => {
  e.preventDefault()
})
```

:eyes: :eyes: :eyes: :eyes: :eyes: :eyes: :eyes: :eyes: :eyes:

**Comment by Alecyrus** [comment]
@Prinzhorn The example code from [here](https://www.electronjs.org/zh/docs/latest/api/window-open)
