### ISSUE TITLE
[Feature Request]:  Chinese cannot be translated

### ISSUE THREAD

**Issue by github-ZH-cn** [electron/electron#33621]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Proposed Solution

Want to solve

### Alternatives Considered

- Alternatives Considered

**Comment by zcbenz** [comment]
Closing since this appears to be a spam.
