### ISSUE TITLE
[Bug]:Installed to vdi windows2016, the C drive can be used normally, the E drive cannot be started, and the process will be reduced by 1. The same is true for the official demo（All versions of the demo）

### ISSUE THREAD

**Issue by Hakon1014** [electron/electron#33630]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 2016

### What arch are you using?

x64

### Last Known Working Electron version

11.5.0

### Expected Behavior

Installed to vdi windows2016, the C drive can be used normally, the E drive cannot be started, and the process will be reduced by 1. The same is true for the official demo

### Actual Behavior

Installed to vdi windows2016, the C drive can be used normally, the E drive cannot be started, and the process will be reduced by 1. The same is true for the official demo

**Comment by zcbenz** [comment]
Sorry but 11.5.0 is no longer supported.
