### ISSUE TITLE
[Bug]: nativeTheme API not working on Fedora Workstation 36 / Gnome 42

### ISSUE THREAD

**Issue by aeschli** [electron/electron#33635]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

Other Linux

### Operating System Version

Fedora Linux 36 (Workstation Edition Prerelease)

### What arch are you using?

x64

### Expected Behavior

nativeTheme should reflect the light/dark scheme configured in the OS

### Actual Behavior

`nativeTheme.shouldUseDarkColors` is always false.

### Additional Information

From https://github.com/microsoft/vscode/issues/146804

- `git clone https://github.com/aeschli/electron-theme-test.git`
- `cd electron-theme-test`, `npm i && npm start`
- a simple electron window opens 
- switch between light and dark in the OS
- the window should change the menu bar colors and the terminal should print `shouldUseDarkColors` matching the OS scheme.
- 
![image](https://user-images.githubusercontent.com/53969297/161902861-27f05858-d7eb-413d-916d-3686f8b17b8f.png)

# Terminal output

```
> burly-rate-begin-iqsp1@1.0.0 start
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application
shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[4553:0406/110408.146875:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[4553:0406/110412.166946:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[4553:0406/110449.772046:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[4553:0406/110449.783890:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Comment by ckerr** [comment]
I'm not able to reproduce this when running the test repo (Electron 17.1.2) on Ubuntu 22.04, which like Fedora 36 is also running GNOME 42. Wayland graphics. When I load System  settings, go to Appearance, and click "Light" or "Dark", Electron's theme updates correctly along with the rest of the desktop.

I'll try installing Fedora 36 to see if that changes things.

As an aside, I _do_ see that the console log is triggered twice each time I toggle between light and dark:

```
shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
shouldUseDarkColors: true, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
shouldUseDarkColors: true, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
```

I"m mentioning it here since It's possible that this is relevant to the bug and that second event is needed to make Electron's theme change. It's also possible that, this is a red herring, that the testcase registered for the event twice, or that Electron is generating unnecessary duplicate events :eyes: : 

I'll try installing Fedora 36 to see if that helps in reproducing this issue.

**Comment by Jeter-work** [comment]
New install of Fedora 36 and I see this issue as well.  Specifically with VS Code 1.67.2.  Came here from: https://github.com/microsoft/vscode/issues/146804

**Comment by remlse** [comment]
The work around posted [here](https://github.com/microsoft/vscode/issues/146804#issuecomment-1123706437) worked for me:

Gnome Tweaks -> Appearance -> Themes, Legacy Application -> Select Dark theme (Adwaita-dark)

I have also figured out for myself a way to script this:
```
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
```
The first line is how Fedora 36 seems to "generally" handle dark mode, while the second covers those edge cases like vscode / electron.

**Comment by proninyaroslav** [comment]
@remlse 
But this will not follow the system theme change. Although it's possible to write a script that would listen to the DBus theme change event and change it globally.

**Comment by proninyaroslav** [comment]
Also I use a ready-made extension for GNOME 42 which allows to force a theme switch for legacy applications (this is disabled by default in the extension settings) https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension

**Comment by bundyo** [comment]
There is now an unified way to get/set the current dark mode in Linux by querying or watching with DBus org.freedesktop.appearance.color-scheme. Works in both latest KDE and Gnome 42+. You can check it out with

```sh
qdbus org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read org.freedesktop.appearance color-scheme
```

Dark mode in Gnome 42+ can be set with Settings -> Appearance -> Style. In KDE 5.24+ it takes effect when you change the UI colors from Settings -> Appearance -> Colors.

Some links about it:
About Gnome implementation: https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/
The setting in xdg-desktop-portal: https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.portal.Settings.xml
Firefox already supports it: https://bugzilla.mozilla.org/show_bug.cgi?id=1734934

Here are the possible values:
![image](https://user-images.githubusercontent.com/98318/173589416-cd510a79-3dfd-405f-a23e-0c9ba62bcbb5.png)

**Comment by HummingMind** [comment]
Same issue on Fedora 37 beta with Gnome 43.

**Comment by bundyo** [comment]
One additional bit of info - DBus introspection doesn't return the org.freedesktop.appearance color-scheme property as available, it will only return on the SettingChanged signal. However, one could directly call the bus and get the property, for instance with @homebridge/dbus-native npm package (until proper support in Electron lands):

```js
bus.invoke({
    destination: 'org.freedesktop.portal.Desktop',
    path: '/org/freedesktop/portal/desktop',
    interface: 'org.freedesktop.portal.Settings',
    member: 'Read',
    signature: 'ss',
    body: ['org.freedesktop.appearance', 'color-scheme']
}, function (err, result) {
    // This package doesn't support setting result signatures on direct invocation.
    shouldUseDarkColors = result[1][0][1][0] === 1;
});
```

**Comment by bash** [comment]
For anyone who frequently switches between dark and light mode and is looking for a workaround until this is fixed: \
Based on [this comment](https://github.com/electron/electron/issues/33635#issuecomment-1146812932) I made a [tiny rust executable](https://github.com/bash/color-scheme-sync) that watches for changes in the new `color-scheme` preference and sets the legacy `gtk-theme` setting for you.

**Comment by real-or-random** [comment]
@bash
 [Night Theme Switcher](https://extensions.gnome.org/extension/2236/night-theme-switcher/) can do this, too. But it's somewhat cumbersome: Its main purpose is to switch to dark mode automatically, and you can't turn this off officially. If you don't want to have an automatic schedule, you can set the night schedule to 5:00 to 5:00 or similar, so it's effectively always light mode, or you can set the night schedule to 5:01 to 5:00, so it's effectively always dark-mode.

**Comment by victorz** [comment]
[Darkman](https://gitlab.com/WhyNotHugo/darkman) is another great alternative to do all kinds of custom things based on when dark/light theme sets in.

**Comment by codebytere** [comment]
Combining with https://github.com/electron/electron/issues/33635

**Comment by escape0707** [comment]
> > Combining with #33635
> 
> This issue **is** #33635. Was this one closed by accident?

~~Problem solved in Chinese Communist Party ways.~~

**Comment by q234rty** [comment]
I believe this was not fixed by just updating chromium to 114, the workaround mentioned above probably needs to be removed.

**Comment by Danik1601** [comment]
> > Combining with #33635
> 
> This issue **is** #33635. Was this one closed by accident?

@codebytere I believe you closed this issue by accident. Please reopen it

**Comment by aeschli** [comment]
@codebytere Can this issue be reopened?

I tested on Fedora Linux 38 (Workstation Edition), Gnome 44.3, Wayland
Electron 26.1.0, Node.js 18.16.1, Chromium 116.0.5845.97

- `git clone https://github.com/aeschli/electron-theme-test.git`
- `cd electron-theme-test, npm i && npm start`
- a simple electron window opens

Expected:
- the console prints `shouldUseDarkColors: false` when the OS uses a light color scheme, or `shouldUseDarkColors: true` if the OS color scheme is dark

Actual:
- Always `shouldUseDarkColors: false,` is printed, even when the OS color scheme is dark.

- In the OS settings, switch between light and dark while the window is still open

Expected:
- the console prints a message matching the need OS color scheme

Actual:
- nothing printed

Test running under Wayland:

- `cd electron-theme-test, npm i && npm start-wayland`

Same problem.

**Comment by fybx** [comment]
> @codebytere Can this issue be reopened?
> 
> I tested on Fedora Linux 38 (Workstation Edition), Gnome 44.3, Wayland Electron 26.1.0, Node.js 18.16.1, Chromium 116.0.5845.97
> 
> * `git clone https://github.com/aeschli/electron-theme-test.git`
> * `cd electron-theme-test, npm i && npm start`
> * a simple electron window opens
> 
> Expected:
> 
> * the console prints `shouldUseDarkColors: false` when the OS uses a light color scheme, or `shouldUseDarkColors: true` if the OS color scheme is dark
> 
> Actual:
> 
> * Always `shouldUseDarkColors: false,` is printed, even when the OS color scheme is dark.
> * In the OS settings, switch between light and dark while the window is still open
> 
> Expected:
> 
> * the console prints a message matching the need OS color scheme
> 
> Actual:
> 
> * nothing printed
> 
> Test running under Wayland:
> 
> * `cd electron-theme-test, npm i && npm start-wayland`
> 
> Same problem.

Tested just like @aeschli has done on Arch Linux, Hyprland (Wayland) without no success.

I attached a video demonstrating the issue; you can clearly see Chromium switching themes as the GTK theme and colour scheme change, and also the logged CLI messages noticing the change; however, the Electron app doesn't react in any way.

https://github.com/electron/electron/assets/41127439/2c5c5de8-b563-42ff-aab7-6eea7d6bc213

**Comment by real-or-random** [comment]
> I attached a video demonstrating the issue;

Note: the video doesn't work (here in my Firefox). "Video can't be played because the file is corrupt."

**Comment by fybx** [comment]
> > I attached a video demonstrating the issue;
> 
> Note: the video doesn't work (here in my Firefox). "Video can't be played because the file is corrupt."

I triple checked the attachment, and it seems to work on Chromium. I'll record again with a different codec once I've the time.

**Comment by strophy** [comment]
Plays for me by downloading it and using VLC

**Comment by johnny-brav0** [comment]
This issue is still there on Fedora 39 (Workstation Edition) running GNOME 45.2

As for the gnome-tweaks solution, it doesn't work either.

Terminal output for 
```
shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
shouldUseDarkColors: true, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
[6046:0106/020111.827043:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
[6046:0106/020130.378229:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
shouldUseDarkColors: true, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
[6046:0106/020134.019750:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

`shouldUseDarkColors` seems to change but only the title bar changes to dark/light.

**Comment by fybx** [comment]
> This issue is still there on Fedora 39 (Workstation Edition) running GNOME 45.2
> 
> Terminal output:
> 
> ```
> shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
> shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
> shouldUseDarkColors: true, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
> [6046:0106/020111.827043:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
> shouldUseDarkColors: false, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
> [6046:0106/020130.378229:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
> shouldUseDarkColors: true, shouldUseHighContrastColors: false, shouldUseInvertedColorScheme: false
> [6046:0106/020134.019750:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
> ```
> 
> `shouldUseDarkColors` seems to change but only the title bar changes to dark/light.
> 
> EDIT: The Open and Save As dialog boxes are white, other ones which appear like "Are you sure you want to ... something" go dark when using "custom" dialog style.

It's apparent that we won't be getting a real fix...

**Comment by real-or-random** [comment]
> @codebytere I believe you closed this issue by accident. Please reopen it

@codebytere Giving this another try. Can you please re-open this issue? It was closed by accident.

**Comment by real-or-random** [comment]
AFAIU the discussion and in particular @Igetin's very detailed analysis (https://github.com/electron/electron/issues/33635#issuecomment-1624975665), the solution should be simply reverting https://github.com/electron/electron/commit/fdf40ce07aa9bb4532bce01b35cad074a00fca9b. Perhaps this should be submitted as a PR? This would at least raise renewed attention to the issue.

(I don't have the time right now, so for the moment, I just hope that someone else can step up here.)
