### ISSUE TITLE
[Bug]:  app not quit after calling app.quit() again in will-quit event handler while first calling has been prevent default behavior.

### ISSUE THREAD

**Issue by heychenfq** [electron/electron#33643]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

first, I call app.quit(), and prevent evnet default in will-quit once event handler for some reason(to clear other resource), after this, call app.quit again, but, app.quit look like not working.
app process should be shutdown after app.quit()

### Actual Behavior

app process is not be shutdown after app.quit()

### Testcase Gist URL

https://gist.github.com/91848219f47ab7c63cc5e5ac23cdf642

### Additional Information

if wrap app.quit() in settimeout, it work around.
if none window created, wrap in promise.resolve().then() can work around.

**Comment by RaisinTen** [comment]
@heychenfq I don't think this is a bug because the default behavior of terminating the application is still prevented because the `e.defaultPrevented` value is still set to `true` due to the `e.preventDefault()` call. As a solution, you could try to run `e.defaultPrevented = false` right before the second `app.quit()` call. Does that make you app work as expected now?

**Comment by heychenfq** [comment]
`e.preventDefault()`  is executed once in the `will-quit` event handler after the first time `app.quit()` called,  the second time `app.quit()` is called in another js context and `e.preventDefault()` will never be called cause the `will-quit` event just listen once.

**Comment by heychenfq** [comment]
I wrap `app.quit()` into `setTimeout`  to work around for now.

**Comment by RaisinTen** [comment]
>  the second time app.quit() is called in another js context

yes, but the the `e` object which has the `defaultPrevented` field we are interested in is still the same, right?

**Comment by heychenfq** [comment]
mean the `e` object still in the same?

**Comment by heychenfq** [comment]
I try to set `defaultPrevented` to false manually, everything go well, thank you for your answser!
