### ISSUE TITLE
[Bug]: safeStorage.isEncryptionAvailable() returns false in Windows

### ISSUE THREAD

**Issue by bluefoods** [electron/electron#33640]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0 and 18.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 21H1

### What arch are you using?

x64

### Expected Behavior

According to the safeStorage module documentation (https://www.electronjs.org/docs/latest/api/safe-storage) `safeStorage.isEncryptionAvailable()` should return `true` "with no other preconditions."

### Actual Behavior

I have been working on an Electron app in Electron v17.1.0. `safeStorage.isEncryptionAvailable()` returns `false` in my tests, so I have been unable to use the safeStorage module.

To ensure that it wasn't something about my application (which I don't have any reason to believe), I created a new Electron project following the latest quick start guide (https://www.electronjs.org/docs/latest/tutorial/quick-start) using Electron v18.0.2. Still, `safeStorage.isEncryptionAvailable()` returns `false`. 

If I try `safeStorage.encryptString("hello");` I get this error on `npm start`

```
App threw an error during load
Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.
    at Object.<anonymous> (C:\Users\...\Node Projects\!projects\electron-quick-start\test-safeStorage.js:4:13)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\...\Node Projects\!projects\electron-quick-start\main.js:48:1)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
```

Here are the entire contents of my `test-safeStorage.js` module:

```
const { safeStorage } = require("electron");

console.log(safeStorage.isEncryptionAvailable());
safeStorage.encryptString("hello");
```
Which I am simply requiring in `main.js` with `require("./test-safeStorage.js");`

### Additional Information

Could it be something about my Windows config that is causing this?

I have tried running `npm start` from both unprivileged PowerShell sessions and PowerShell sessions with administrative rights.

**Comment by ganthern** [comment]
FYI, it's because you don't open a BrowserWindow before trying to encrypt stuff: https://github.com/electron/electron/issues/32206

maybe we can get some visibility for this.

**Comment by bluefoods** [comment]
@ganthern Thank you. Yes, it does return `true` when I move `safeStorage.isEncryptionAvailable()` to
```
app.whenReady().then(() => {
   safeStorage.isEncryptionAvailable()
});
```
Official documentation (https://www.electronjs.org/docs/latest/api/safe-storage) should be updated to accurately explain when the safeStorage API becomes available.

**Comment by RaisinTen** [comment]
> Official documentation (https://www.electronjs.org/docs/latest/api/safe-storage) should be updated to accurately explain when the safeStorage API becomes available.

Or we can try to find out why it doesn't work the same way as macOS on the other platforms like Windows and Linux and send a fix?

**Comment by bluefoods** [comment]
@RaisinTen I may not have enough Node.js knowledge to assist effectively, and I don't have a macOS system to test with. If there is anything I can do to help you with assessing the behavior of safeStorage across platforms let me know.

**Comment by codebytere** [comment]
Hey folks - i believe I know what the cause of this is but am still trying to determine whether it can be fixed. Essentially, whether encryption is available on Window is determined [here](https://source.chromium.org/chromium/chromium/src/+/main:components/os_crypt/os_crypt_win.cc;l=283;drc=401f9911c6a32a0900f3968258393a9e729da625;bpv=1;bpt=1?q=isencryptionavailable%20oscryp&ss=chromium) - this is only capable of being set once [`RegisterLocalPrefs`](https://source.chromium.org/chromium/chromium/src/+/main:components/os_crypt/os_crypt_win.cc;l=194;drc=401f9911c6a32a0900f3968258393a9e729da625;bpv=1;bpt=1?q=isencryptionavailable%20oscryp&ss=chromium) has been called. We call that (similar to chromium) in [`PostEarlyInitialization`](https://github.com/electron/electron/blob/3da598015bccb8f9ab6833d1163c2fe2b0f2b058/shell/browser/browser_process_impl.cc#L103) which wouldn't happen before the app is ready.

**Comment by MarshallOfSound** [comment]
I think we should just document that it requires the app to be ready on windows.

**Comment by bluefoods** [comment]
@codebytere @MarshallOfSound Thanks for your help!

**Comment by Slapbox** [comment]
@MarshallOfSound does the app not need to be ready on Linux? Clarity on that could help to close #32206
