### ISSUE TITLE
[Bug]: [regression] no login event raised for WWW-Authenticate image requests

### ISSUE THREAD

**Issue by bughit** [electron/electron#33687]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

Windows

### Operating System Version

win 7 sp1

### What arch are you using?

x64

### Last Known Working Electron version

v7.0.0-beta.3

### Expected Behavior

Any request that requires authentication should raise a login event on app and webContents.

The initial gist reproduces via https://login.microsoftonline.com/ but requires and an account on an azuread-sso enabled O365 tenant.

When you submit a username on https://login.microsoftonline.com/ belonging to a tenant configured for Azure AD SSO (the gist loads login.microsoftonline.com), it will attempt to do an HTTP negotiate authentication via an image request to "https://autologon.microsoftazuread-sso.com/$TENANT_DOMAIN/winauth/ssoprobe"

The second gist is better, uses a public, test basic auth endpoint.

### Actual Behavior

There's no login event for image requests.

### Testcase Gist URL

negotiate: https://gist.github.com/4e739bdbdef5af03bef9ff277321fb5d

this gist doesn't require an O365 account to repro, so better
basic: https://gist.github.com/61d18fe783c4dc1501c62025bc99f598

### Additional Information

Bisected:
  good: v7.0.0-beta.3
  bad:  v7.0.0-beta.4

**Comment by bughit** [comment]
Reproduced this with basic auth via a public example endpoint on https://httpbin.org/

So the generalized description is: no login event raised for WWW-Authenticate image requests.

login does fire for script tags

Here's a self contained basic auth gist that doesn't require an azuread-sso tenant:
https://gist.github.com/61d18fe783c4dc1501c62025bc99f598

Looking at the changes when this regressed:
https://github.com/electron/electron/compare/v7.0.0-beta.3...v7.0.0-beta.4

the ones that seem most likely: #19609, #19979

@deepak1556 Could you please take a look at those?

**Comment by bughit** [comment]
@codebytere I've identified the source of this regression and would like to get the thoughts of the relevant members on how to address it.

This regressed due to [this](https://source.chromium.org/chromium/chromium/src/+/7d032b378c2081291cda3af49153d6d5673b4c2e:content/renderer/loader/web_url_loader_impl.cc;dlc=8a93767ecd2aa0eea3fb253a8d9db5efd36dc114;bpv=0) chromium commit. 

The [relevant part](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/loader/fetch/url_loader/web_url_loader.cc;l=428) is:

```c++
  if (!request->is_favicon &&
      request_destination == network::mojom::RequestDestination::kImage &&
      IsBannedCrossSiteAuth(request.get(),
                            passed_url_request_extra_data.get())) {
    // Prevent third-party image content from prompting for login, as this
    // is often a scam to extract credentials for another domain from the
    // user. Only block image loads, as the attack applies largely to the
    // "src" property of the <img> tag. It is common for web properties to
    // allow untrusted values for <img src>; this is considered a fair thing
    // for an HTML sanitizer to do. Conversely, any HTML sanitizer that didn't
    // filter sources for <script>, <link>, <embed>, <object>, <iframe> tags
    // would be considered vulnerable in and of itself.
    request->do_not_prompt_for_login = true;
    request->load_flags |= net::LOAD_DO_NOT_USE_EMBEDDED_IDENTITY;
  }
```

`do_not_prompt_for_login` then causes [`URLLoader::OnAuthRequired`](https://source.chromium.org/chromium/chromium/src/+/main:services/network/url_loader.cc;l=1351) to swallow the auth attempt.

```c++
void URLLoader::OnAuthRequired(net::URLRequest* url_request,
                               const net::AuthChallengeInfo& auth_info) {
  if (has_fetch_streaming_upload_body_) {
    NotifyCompleted(net::ERR_FAILED);
    // |this| may have been deleted.
    return;
  }
  if (!url_loader_network_observer_) {
    OnAuthCredentials(absl::nullopt);
    return;
  }

  if (do_not_prompt_for_login_) {
    OnAuthCredentials(absl::nullopt);
    return;
  }

  DCHECK(!auth_challenge_responder_receiver_.is_bound());

  url_loader_network_observer_->OnAuthRequired(
      fetch_window_id_, request_id_, url_request_->url(), first_auth_attempt_,
      auth_info, url_request->response_headers(),
      auth_challenge_responder_receiver_.BindNewPipeAndPassRemote());

  auth_challenge_responder_receiver_.set_disconnect_handler(
      base::BindOnce(&URLLoader::DeleteSelf, base::Unretained(this)));

  first_auth_attempt_ = false;
}
```

The justification provided may be appropriate for protecting a chrome user but it's not appropriate for electron API, which should continue emitting login events for any request that requires it.

AFAICT this would need to be patched away in chromium.

**Comment by MarshallOfSound** [comment]
> The justification provided may be appropriate for protecting a chrome user but it's not appropriate for electron API, which should continue emitting login events for any request that requires it.

I disagree, the Electron API in this case directly exposes standard-and-expected web functionality.  In this case you are asking us to change the behavior of the "standard-and-expected" functionality, not changing the Electron API itself.

We should match Chromium in it's security posture here.

**Comment by bughit** [comment]
> We should match Chromium in it's security posture here.

Chrome is trying to protect an unaware user. The audience for the electron login event is rather different. Are you claiming that an electron developer should not be allowed to authenticate to a server that is no way obscured from them?

Here's what the login event looks like:

```js
{
  url: 'https://httpbin.org/basic-auth/dynamic/image',
  isMainFrame: false,
  firstAuthAttempt: true,
  responseHeaders: {
    'access-control-allow-credentials': [ 'true' ],
    'access-control-allow-origin': [ '*' ],
    'content-length': [ '0' ],
    date: [ 'Sat, 16 Apr 2022 06:49:48 GMT' ],
    server: [ 'gunicorn/19.9.0' ],
    'www-authenticate': [ 'Basic realm="Fake Realm"' ]
  },
  isProxy: false,
  scheme: 'basic',
  host: 'httpbin.org',
  port: 443,
  realm: 'Fake Realm'
}
```

Please explain why knowing the host and the full url is not enough to make this decision? You could additionally provide the type of request this is (image, script, document, ...) and whether its cross-site, which might be useful for filtering out unexpected auths. You could also require some sort of "I really mean it" flag in case of cross-site auths. But removing the possibility to authenticate entirely cannot be justified on the premise that a chrome user could be confused by such a decision.

**Comment by MarshallOfSound** [comment]
> Are you claiming that an electron developer should not be allowed to authenticate to a server that is no way obscured from them?

Yes, because the average electron developer is just wrapping arbitrary websites and the security measures Chrome implements very much matter.  This isn't a discussion, I am strongly against _patching_ Chromium to actively reduce or eliminate security measures.

**Comment by bughit** [comment]
AFAICT, the [AuthServerAllowlist](https://chromeenterprise.google/policies/#AuthServerAllowlist) policy in chrome and the electron equivalent ses.allowNTLMCredentialsForDomains, will permit integrated windows authentication, the passing of implicit current user credentials, to such cross-site image auths. That's what azuread-sso depends on. That's not a security hole, that's intentional, the admin in the case of chrome, and the dev in the case of electron, are choosing to trust certain domains.

So if implicit (integrated) cross-site image authentication based on a domain is currently allowed both in chrome and electron, how can you argue that explicit auth also based on the domain should not be possible? What's the difference?

Their comment is about the interactive chrome user, who's likely to misunderstand the domain they're authenticating to, being tricked. So that's what do_not_prompt_for_login is intended to prevent. That it's affecting the API's of blink/chromium embedders, like the electron login event, which are capable of making sound decisions based on the domain, is an unintended side-effect.
