### ISSUE TITLE
[Bug]: app.relaunch loses args when execPath specified.

### ISSUE THREAD

**Issue by p120ph37** [electron/electron#33686]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.1

### What operating system are you using?

macOS

### Operating System Version

10.14.6

### What arch are you using?

x64

### Last Known Working Electron version

17.0.0-alpha.3

### Expected Behavior

When invoking `app.relaunch` and specifying both `execPath` and `args`, I expect the args to be passed to the new process.

### Actual Behavior

The binary specified by `execPath` is spawned as a new process, but the `args` are not applied.

### Testcase Gist URL

https://gist.github.com/p120ph37/98cf0fb13790feed702f3e90cbddfbf6

### Additional Information

This bug was introduced in `17.0.0-alpha.4`, and is present in all newer stable versions up to and including at least `19.0.0-alpha.1`  Also note that `app.relaunch()` doesn't work at all from within Electron Fiddle, so to run this gist, you must launch Electron directly (e.g.: via `npm start`).

**Comment by p120ph37** [comment]
Just a note: this does not seem to be MacOS-specific.  I've observed the same issue on Windows too at least.

**Comment by dube116** [comment]
problem from this commit
[https://github.com/electron/electron/commit/1e371621dca5104fc0d91358828579f2b0d65f0a](url)
merged in
[https://github.com/electron/electron/pull/31555/files](url)
lazily evaluated problem

**Comment by p120ph37** [comment]
Makes sense.  The similar changes in `native_window.cc` from that same commit appear to have also caused an issue which has already been fixed: #33025
