### ISSUE TITLE
[Bug]: Devtools won't open

### ISSUE THREAD

**Issue by Hate9** [electron/electron#33684]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.1

### What operating system are you using?

Other Linux

### Operating System Version

Linux mabel-endeavour-linux 5.15.32-xanmod1-1 #1 SMP Tue, 29 Mar 2022 10:56:09 +0000 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

I launch my application, I press ctrl+shift+i, and devtools appears.

### Actual Behavior

I do the above, and the devtools console briefly flashes, before disappearing. the page is still formatted as though the devtools window is up (less horizontal space), but with a blank background where the devtools window should be. Re-entering the key-combo does not change the formatting back.

log:
```
[mabel@mabel-endeavour-linux electron-test]$ electron .
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/unique_ptr.h:659: typename std::add_lvalue_reference<element_type>::type std::unique_ptr<blink::CSSSelector []>::operator[](std::size_t) const [_Tp = blink::CSSSelector [], _Dp = std::default_delete<blink::CSSSelector []>]: Assertion 'get() != pointer()' failed.
[10179:0408/145319.700844:ERROR:shared_image_manager.cc(227)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[10179:0408/145319.701892:ERROR:shared_image_manager.cc(227)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[10179:0408/145319.702470:ERROR:shared_image_manager.cc(227)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[10179:0408/145319.703007:ERROR:shared_image_manager.cc(227)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
```

**Comment by Curstantine** [comment]
Devtools *does* open but it fails to render, it loads for the first frame then disappears.
![image](https://user-images.githubusercontent.com/69104500/164541161-dae25b7c-fb61-4462-83d9-bfac36af66f6.png)

**Comment by Hate9** [comment]
that is, in fact, a slightly more correct description of what happens.

**Comment by ckerr** [comment]
This WfM using electron-quick-start on Electron 18.0.1 on Ubuntu 22.04.

```sh
$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
$ ./node_modules/electron/dist/electron --version
v18.0.1
```

But if both of you are seeing the same behavior, then surely it's something going on in the code rather than some external issue e.g. a configuration problem.

Any chance either of you could fire up [electron-fiddle](github.com/electron/fiddle) and try to walk or bisect through nightly / alpha / beta releases leading up to 18.0.1 and see where this broke for you?

I'd do this myself if I could reproduce the issue; but since I can't, I could use some help in helping track this issue down

**Comment by ckerr** [comment]
Also @Curstantine are you also running Endeavour?

**Comment by Curstantine** [comment]
> Also @Curstantine are you also running Endeavour?

Arch Linux![20220427_224116~2.jpg](https://user-images.githubusercontent.com/69104500/165582040-bacac30f-16e7-44fb-969b-2223a232d8e2.jpg)

**Comment by Curstantine** [comment]
Found something weird, while both `electron` and `electron18` runs the same version, `electron18` fails to open devtools.

1. `electron` - `/usr/bin/electron`
2. `electron18`
3. `electron15`

![image](https://user-images.githubusercontent.com/69104500/165665944-b9fa8fa1-e08c-4a40-9f9c-4c024902a5d0.png)

And what actually happens with the `electron18` binary is that it fails to render just the `Elements` page causing whole devtools window to freeze, devtools window opens fine if you set the window view mode to popup and is not in the `Elements` page.

![Screenshot_20220428_082754](https://user-images.githubusercontent.com/69104500/165667703-c630a9a3-613d-4b67-815d-a59ea0681c86.png)

Also, `electron` for some reason fails to render the `elements` page if you're in "demo page".

As for fiddle, it doesn't open; I'll restart and update the comment if it opens.

**Comment by Hate9** [comment]
@Curstantine that's interesting and surprising, because I don't have electron18 (which is the aur package, yes? I can't find anything by that name in the main repos) installed, just community/electron.

**Comment by Curstantine** [comment]
![Screenshot_20220428_085711](https://user-images.githubusercontent.com/69104500/165670496-e992018c-f891-4a8e-9f33-585e411b8e4f.png)

`electron` is the [global package](https://wiki.archlinux.org/title/Electron_package_guidelines), while `electron18` is the [versioned package](https://archlinux.org/packages/community/x86_64/electron/), you get both when installing the `electron` binary.

**Comment by Hate9** [comment]
Oh, gotcha.
In that case, it's still a little weird, since I'm launching my thing with `electron .`.

**Comment by oxodao** [comment]
Also running ArchLinux, also having this issue with the system electron.
Running one of theses, not sure which one is used
```
  ~ » pacman -Qs electron
local/electron 18.0.3-2
    Build cross platform desktop apps with web technologies
local/electron11 11.5.0-5
    Build cross platform desktop apps with web technologies
local/electron13 13.6.9-3
    Build cross platform desktop apps with web technologies
local/electron14 14.2.9-2
    Build cross platform desktop apps with web technologies
local/electron16 16.2.2-2
    Build cross platform desktop apps with web technologies
```

Running it through the npm installed one (`./node_modules/electron/dist/electron`) it is working fine

**Comment by Hate9** [comment]
how does one run it using the npm one? even with the rest uninstalled, `electron .` doesn't work

**Comment by Curstantine** [comment]
@Hate9 maybe `yarn/npm run electron .`

**Comment by oxodao** [comment]
Edit your `package.json` and where you use it (most likely the "run"/"start" script) replace `electron .` by `./node_moduels/electron/dist/electron .`

**Comment by jasonribble** [comment]
bump

**Comment by acacioscosta** [comment]
I upgraded from ubuntu 20.04 to 22.04 and the same problem happened. I reinstalled 20.04 and it worked fine.

**Comment by 13zebras** [comment]
Adding what I hope is helpful information:

In the following apps built with Electron, devtools renders similar to the screenshot attached:

vscode (recent update)
Obsidian
Typora

My system info:
```
Kernel: 5.15.71-1-lts
arch: x86_64 bits: 64
Desktop: i3 v: 4.21 
Distro: EndeavourOS - Linux
```

![2022-10-11_02-43-42_flameshot](https://user-images.githubusercontent.com/17152930/195027371-793a2203-09f2-4fcc-bd85-9033be3415bf.png)

**Comment by 13zebras** [comment]
One more bit of hopefully helpful context. Same system as in my previous comment. This is a screen shot from:
`Chromium Version 106.0.5249.103 (Official Build, ungoogled-chromium) Arch Linux (64-bit)`

As you can see, Chromium as a browser renders devtools perfectly. So the question would seem to be how Electron renders devtools differently, at least on Linux. 

One thing to consider:  does Electron utilize gtk3 or gtk4 on Linux? If so, that might be the issue. I've had gtk3 cause issues in non-electron apps related to rendering, especially with dark themes. 

![2022-10-13_11-07-37_flameshot](https://user-images.githubusercontent.com/17152930/195649142-dfda8406-c7bc-4fa9-8a29-4c89eaf30eeb.png)

**Comment by UserFlep** [comment]
Also faced this problem on ubuntu 22, electron version 13.4.0 and less does not open DevTools, version 13.5.0 ( and 13.5.2, 13.6.9) opens

**Comment by otanim** [comment]
I had a similar issue, just needed to remove the `yarn.lock` files from my project's directories, then re-install node packages via `yarn`.

**Comment by radu-b** [comment]
With electron 21.3.1 the DevTools do not open when the app is launched from the Visual Studio Code terminal. They do open when launching from a system terminal.

**Comment by Gstar123456** [comment]
tor. 24. nov. 2022 kl. 15:01 skrev Radu Balaban ***@***.***>:

> With electron 21.3.1 the DevTools do not open when the app is launched
> from the Visual Studio Code terminal. They do open when launching from a
> system terminal.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>
-- 
Gstar

**Comment by gadlevski** [comment]
After upgrading to Linux Mint 21 doesn't open devtools.

electron": "^11.4.11

**Comment by Jinul** [comment]
Same here, Devtools doesn't work with ubuntu 22. Using electron 11.4.7

**Comment by anwarpro** [comment]
Same here, Devtools doesn't work with ubuntu 22. Using electron 11.4.7

**Comment by Dolphindalt** [comment]
I am also having this issue on Arch Linux with Electron 11. Willing to do some digging, just need a nudge in the right direction.

**Comment by manhnt9** [comment]
Same here after upgrading to Ubuntu 22.04

**Comment by ckerr** [comment]
There are a confusing number of comments from the last few months mentioning Electron 11 and 13, which reached end-of-life and in mid-2021 and early 2022, respectively, and are [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline) .

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.

**Comment by e9x** [comment]
Thank you for this update. While it's good to know that newer versions of Electron are no longer encountering this issue, it's important to acknowledge that there are still developers who are working with older versions and are forced to use Electron 13 or lower. With that in mind, I would like to suggest a workaround for those who are still experiencing this issue on unsupported versions of Electron.

Just use the **remote debugger**. The built-in debugger has too many problems on earlier versions of Electron.

1. Enable Chrome's remote debugger by setting the `--remote-debugging-port` switch. this code to the main process

   (Main process)

   ```js
   app.commandLine.appendSwitch("--remote-debugging-port", "9222");
   ```

2. Go to chrome://inspect in a Chromium-based browser
   Your BrowserWindow should appear.

**Comment by Epameinondas-Theodoropoulos** [comment]
Electron: 24.3.0 

I have the same issue. Most of the time the dev tools do not open. But 1 in 20 times they will open by electron. I cannot understand why. And is very random when they open and when they are not open.

**Comment by DogFoxX** [comment]
Also had the same issue with devtools not opening when running from vs code terminal.
But adding `mainWindow.webContents.openDevTools({ mode: 'detach' })` just before `mainWindow.loadURL()` works everytime it seems.

**Comment by adasq** [comment]
> Also had the same issue with devtools not opening when running from vs code terminal. But adding `mainWindow.webContents.openDevTools({ mode: 'detach' })` just before `mainWindow.loadURL()` works everytime it seems.

Thanks! However, for me it didn't work flawlessly. 
I triggered `mainWindow.webContents.openDevTools({ mode: 'detach' })` once my UI fully rendered:

```js
//main.js
ipcMain.on('message-from-renderer-process', async () => {
  mainWindow.webContents.openDevTools({ mode: 'detach' })
});
```

100% success ratio for my so far.
