### ISSUE TITLE
[Bug]: electron打包vue2.0项目后iframe获取服务器中的pdf加载，文件名可以加载出来内容加载不出来？？？

### ISSUE THREAD

**Issue by 18465139686** [electron/electron#33697]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.1

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

18.0.1

### Expected Behavior

打包后使用iframe获取到服务器中的pdf文件展示浏览

### Actual Behavior

在代码运行带浏览器中运行时iframe可以获取到服务器中的pdf文件并加载出来，
现在使用electron打包后iframe获取服务器的pdf可以获取到，加载是只加载出来文件名，内容加载不出来，没有任何报错！！

这是打包后加载的样子图片：
http://m.qpic.cn/psc?/V13HWh7m4DIHy4/TmEUgtj9EK6.7V8ajmQrEKSYRp0E1Zo2*IjbMgjEvWhIQGGtxcv3rwB2BVLYxJcs04M3MfYuXjlcBZyahMQ4huhaSsfc1NdHHBGElW41kSg!/b&bo=VQOTAgAAAAADF*U!&rf=viewer_4

在浏览器中运行和打包后运行进行对比发现少了一个东西：
http://m.qpic.cn/psc?/V13HWh7m4DIHy4/TmEUgtj9EK6.7V8ajmQrEBSAcGX2YK9SSWlmMkixsyM6hPwTNI3OK5EHEUUWkqLqLwJHPMYSzkjcniLi3P*hHgEII5epaiQznLVZu92q3TA!/b&bo=3QQGAgAAAAADF.8!&rf=viewer_4

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
