### ISSUE TITLE
[Bug]: backgroundThrottling: false ignored by OffscreenCanvas

### ISSUE THREAD

**Issue by ThaUnknown** [electron/electron#33703]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.10

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### What arch are you using?

x64

### Expected Behavior

When a `BrowserWindow`'s preferences include `backgroundThrottling: false`, an OffscreenCanvas which is being updated by a worker, should update it's contents as it's being drawn on, when the parent `BrowserWindow` lost visibility [minimized, overlapped by another focused fullscreen app], just like when it does on a normal canvas.

### Actual Behavior

When a `BrowserWindow`'s preferences include `backgroundThrottling: false`, an OffscreenCanvas which is being updated by a worker, only displays the last frame when the parent `BrowserWindow` was last visible.

### Additional Information

The steps to reproduce this are fairly complex, as it's a fairly in-depth issue, but the """easiest""" way of seeing the impact of this issue is:
1. Create a canvas
2. Create a worker
3. Transfer the control of the canvas to the worker
4. Draw continuous animations on the canvas in the worker
5. capture the stream of the canvas using `canvas.captureStream()`
6. Create a video element
7. Set the srcObject of the video to the canvas stream
8. Request PictureInPicture on the video element
9. Minimize the app
10. Notice the canvas has stopped updating on the PiP

This issue only happens [when backgroundThrottling is disabled] with offscreen canvases, reproducing the same steps above without an offscreen canvas/worker, but instead drawing on the canvas in the main "thread" and then minimizing the app will keep the canvas updating, but if the worker needs to do the rendering [say WASM or some form of node bindings is used] this means transferring the data to be rendered from the worker to the main thread, causing significant overhead, which might prevent the animations from being drawn real-time, as blending of bitmaps can't be done on the worker, because the canvases don't update.

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Additionally to the steps you've already provided, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.

**Comment by ThaUnknown** [comment]
https://gist.github.com/ThaUnknown/ba56ae7c3bf715df1df85a8ea157c830

**Comment by ThaUnknown** [comment]
ah, this is what I get for not updating, fixed as of v17.0.0
