### ISSUE TITLE
[Bug]: Change in system timezone not updating in electron main thread

### ISSUE THREAD

**Issue by pravichandran15** [electron/electron#33723]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

macOS

### Operating System Version

Montrey

### What arch are you using?

x64

### Expected Behavior

Change in system timezone should reflect the update the new Date in main thread 
Where as in renderer its working fine

### Actual Behavior

Change in system timezone not reflecting in main thread
1) Launch electron
2) Go to system preferences
3) Update Timezone
4) Run new Date in main thread observe it still give the old timezone date

### Additional Information

Change in system timezone not reflecting in main thread
1) Launch electron
2) Go to system preferences
3) Update Timezone
4) Run new Date in main thread observe it still give the old timezone date

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.

**Comment by pravichandran15** [comment]
@mlaurencin ,
Please find the [code](https://gist.github.com/pravichandran15/47fdfd18cbeb1215288725aad6dcc1c1) attached which is done using Electron Fiddle,
Refer to the video for more details.
https://user-images.githubusercontent.com/32735162/165248433-1ce12e11-1af8-4727-939a-4afa66f8519a.mov
