### ISSUE TITLE
[Bug]: child_process.spawn error with cwd option

### ISSUE THREAD

**Issue by Fndroid** [electron/electron#33725]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0-alpha.1

### What operating system are you using?

macOS

### Operating System Version

12.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

seems no

### Expected Behavior

the code on below shold not throw ENOENT error because the `ping` command is in `/sbin/ping`
```js
require("child_process").spawn(`./ping`, ["google.com"], {
  cwd: "/sbin",
});
```

### Actual Behavior

```js
equire("child_process").spawn(`./ping`, ["google.com"], {
  cwd: "/sbin",
});
```
the code above failed and the `ping` process is running in background..

then I try to join cwd with command like this:
```js
require("child_process").spawn(`/sbin/ping`, ["google.com"]);
```

and it works

### Testcase Gist URL

https://gist.github.com/Fndroid/346e81548c2e59510f53794538fcefd4

### Additional Information

Testcase output in devtool
<img width="839" alt="image" src="https://user-images.githubusercontent.com/16091562/162930759-51be1189-2505-49cb-ad83-3cde5746e913.png">

**Comment by deepak1556** [comment]
Depends on https://github.com/libuv/libuv/pull/3583
