### ISSUE TITLE
[Bug]: GetUserMedia Black Screen for RX6000 series GPUs

### ISSUE THREAD

**Issue by jeffery30162** [electron/electron#33733]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

1. Calling desktopCapturer.getSources() will return an array of all screens and applications.

2. Calling mediaDevices.getUserMedia() using the constraints of the selected above, a video stream is created which then shows the application screen in a '<'video'>'

### Actual Behavior

My Setup:
    - Main monitor (Connected to a RX 6900xt)
    - Side monitors (All Connected to a RX480)
    - ryzen 5950x

1. Calling desktopCapturer.getSources() will return an array of all screens and applications except for anything being displayed on the Main screen. The main screen does not show at all on the types : screen.

2. Strange behavior:
    Using an application which is on the side display works as intended. When moving that application over to the main screen   causes the stream to go black but still displaying the mouse cursor within the application. Also starting a stream using an application which is on the main monitor results in a black screen. Dragging the application window back to a side monitor returns to normal behavior.

What I have tried:
    disableHardwareAcceleration() but that seems to do nothing.

Other results:
    Using another known application that uses the same tech: Discord. Discord does not suffer from this problem. (hardware acceleration enabled)

Any ideas of what is causing this and how to fix?

Thanks

### Additional Information

`desktopCapturer.getSources({ types: ['window', 'screen'], thumbnailSize: { width : 500, height : 500 } }).then(async sources => {
      win.webContents.send('getStreamerSources', sources);
 });

const constraintsVideo = {
      audio : false,
      video: {
        mandatory: {
          chromeMediaSource: 'desktop', //chromeMediaSource: 'screen',
          chromeMediaSourceId: selectedscreenId,
          minFrameRate: fps,
          maxFrameRate: fps,
          minWidth: this.miscService.getResolutionWidthFromHeight(resolution.split('x')[1]),
          maxWidth: this.miscService.getResolutionWidthFromHeight(resolution.split('x')[1]),
          minHeight: resolution.split('x')[1],
          maxHeight: resolution.split('x')[1],
        },
        //optional: [
        //  { googLeakyBucket: true },
        //  { googTemporalLayeredScreencast: true },
        //]
      }
    }

const videoStream = await mediaDevices.getUserMedia(constraintsVideo);`

**Comment by Adriannusx4321** [comment]
i have black screen too

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better! This seems like it might be related to this [older issue](https://github.com/electron/electron/issues/29931).

Would it be possible for you to make a standalone testcase using [Electron Fiddle](https://www.electronjs.org/fiddle)? It is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use. This will also make it easier to compare this to the previous issue.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
