### ISSUE TITLE
[Bug]: Electron 18.x drawing issues in MacOS Virtual Machines

### ISSUE THREAD

**Issue by mockjv** [electron/electron#33735]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

macOS

### Operating System Version

12.0.1, 12.3.1

### What arch are you using?

x64

### Last Known Working Electron version

17.4.0

### Expected Behavior

Normal drawing/rendering of the window contents, including on Virtual Machine deployments of MacOS (currently tested on VMWare Fusion).

### Actual Behavior

Any electron window comes up blank/white.  Attempts to interact with the window will cause some portions to update but not all of it.  In our test application, when we loaded the dev tools they were also buggy (e.g., select the console tab and multiple instances of the console were drawn inside each other).

The issue doesn't appear to exhibit on standard MacOS installations.  Maybe some kind of software rendering vs. hardware rendering (WAG)?

Steps followed to reproduce:

First, check out the quick start guide on the virtualized MacOS install:

```sh
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
```

Then update all of the packages to the latest packages, including Electron to 18.0.0 or later:

```sh
yarn upgrade --latest --interactive
```

Then run the electron instance and observe the drawing issue:

```sh
yarn start
```

![Screen Shot 2022-04-12 at 7 17 57 AM](https://user-images.githubusercontent.com/15215338/162971543-e9642440-2b56-4557-8db0-47281f46082e.png)

**Comment by mockjv** [comment]
It's worth noting I was able to reproduce the exact same behavior by running the electron-quick-start on macOS 12.3.1 via Parallels, so this doesn't appear to be isolated to just VMWare Fusion Pro.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/15215338/163693704-fcaaa14a-b4b4-463b-bb22-e13e0792e893.png">

**Comment by mockjv** [comment]
I would have to grab screenshots, and it might be a little while before I can, but I at least wanted to add that what you're seeing is very similar to what I was seeing if I brought up the Developer Tools.  Especially if I selected the "Console" or "Sources" tabs.

**Comment by 255kb** [comment]
ok. 
Please note here that the app was packaged with electron-builder, with the dev tools disabled. 

I wonder if this is related to #33508

**Comment by daleclack** [comment]
I have same issue when I want to display a page that written in vue3 in electron BrowserWindow, and I get these message:
ibva error: /usr/lib/dri/i965_drv_video.so init failed
[18545:0430/123413.529250:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/unique_ptr.h:659: typename std::add_lvalue_reference<element_type>::type std::unique_ptr<blink::CSSSelector []>::operator[](std::size_t) const [_Tp = blink::CSSSelector [], _Dp = std::default_delete<blink::CSSSelector []>]: Assertion 'get() != pointer()' failed.
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/unique_ptr.h:659: typename std::add_lvalue_reference<element_type>::type std::unique_ptr<blink::CSSSelector []>::operator[](std::size_t) const [_Tp = blink::CSSSelector [], _Dp = std::default_delete<blink::CSSSelector []>]: Assertion 'get() != pointer()' failed.

**Comment by mdg1019** [comment]
Same issue with an Electron/Angular app on one of my two Linux computers. It runs fine on my HP laptop, but displays the following error message on my System 76 box:

[9236:0430/060402.227143:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.

Not sure if it's relevant, but the HP laptop has an NVIDIA gpu where the System 76 box only has Intel Integrated Graphics. Both computers are running Ubuntu 20.04. I'm just starting development on the app and am running the same version of code from a terminal inside of VS Code.

**Comment by tomadimitrie** [comment]
same here on Parallels, running VS Code and same issues as above

**Comment by Dsibe** [comment]
Can confirm : running the exactly same Electron app on 18.x (Vmware Workstation 16.0, host Windows 10, guest macOS 12.1) causes the window to be blank while devtools can't connect to the window. Downgrading version to 17.x resolves this issue.

**Comment by mockjv** [comment]
This is a show stopping bug for us, and I'm growing exceedingly concerned as 17 is just around the corner from no longer being supported (assuming I'm reading the support schedule correctly, that 17 will drop out of the "last 4" when 21 drops in late September).

@mlaurencin Sorry to mention you, but I saw you as a contributor due to labelling the issue so I'm hoping to draw attention to this.  Do you know more on if there's been any discussions on whether to address this problem?

Out of everyone that's commented on this issue, has anyone specifically tried 20 yet?  I've had a ton of other distractions but I'm hoping to look at it soon...

**Comment by zlshames** [comment]
I'm also having this issue for my app after upgrading to Node v18.x & Electron v19

![CleanShot 2022-08-18 at 13 26 04](https://user-images.githubusercontent.com/18445938/185457377-7899e06c-5329-4da4-b34b-9a5e1147ec8b.png)

What's weird is that both dev-tools and the app show a white window. However, I know that the elements are being rendered because I can mouse over buttons and see the pointer cursor show where buttons _should_ be.

**Comment by zlshames** [comment]
I'm having the same issue on Node v18.x and Electron v19.

![CleanShot 2022-08-18 at 13 26 04](https://user-images.githubusercontent.com/18445938/185457793-eb06a92a-77db-455c-8e2c-1bf49a788b44.png)

What's more odd is that I can tell that the elements are rendering because I can mouse-over where the buttons should be, and I still am able to see the pointer cursor. Clicking on items still work as well. It just shows all white. Including in dev-tools.

**Comment by zuernBernhard** [comment]
Yes same problem here. Not only with VMWare but also Parallels.

**Comment by Delagen** [comment]
I tried 21 version, it compiles and even works sometimes, but I need to clean any cache before start, because it struck at start on Linux or MacOS when starts with cache of previous version (after ~10 minutes it start to show some content)

**Comment by ideologysec** [comment]
Starting electron apps with `--flags --disable_gpu` appears to resolve the issue, but for battery life and performance reasons being able to use GPU rendering would seem to be ideal.

Additionally, Chrome often displays similar rendering issues in virtual machines unless "Use hardware acceleration when available" is disabled in settings.

**Comment by zuernBernhard** [comment]
--flags --disable_gpu does not seem to help

![Uploading Bildschirmfoto 2022-10-11 um 20.50.26.jpg…]()

**Comment by nornagon** [comment]
does chromium work?

**Comment by realyuyanan** [comment]
It looks help after **renaming** the file - "**YourAppName.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib**". 
But I don't understand what‘s the reason, can someone help explain it?

**Comment by rcclerigo** [comment]
fyi starting the app w/ `--flags --disable-gpu` did seem to help

**Comment by miniak** [comment]
just `--disable-gpu` should be enough

**Comment by mockjv** [comment]
Would anyone then have a recommendation on the appropriate approach to adjust that at runtime based on environmental conditions like determining that the instance is running on a VM?  Our particular application is packaged using `electron-forge`, but bundled with a broader set of services and agents.  I'd have to revisit how all of that gets bundled but I wasn't immediately aware of ways to get in front of the execution when they're packaged that way.

That said, I also wouldn't want to disable GPU acceleration on 99% of use cases just because of the <1% that has this issue.  Additionally, that "fix" is just a band-aide on something that genuinely needs to get fixed, even if it's an upstream issue.

That said, I could stand to retest all of this against later versions but it's been a while since I've been able to keep an eye on this particular issue.

**Comment by Delagen** [comment]
@mockjv I migrated to 22 version with fully rewrite to remove webview tag and remote dependencies. Seems works fine.

**Comment by mockjv** [comment]
@Delagen Ok, that's really good news!  I'll go and sanity check at least the test case I originally posted and if it looks good I'll go ahead and close this.

**Comment by abiosoft** [comment]
> It looks help after **renaming** the file - "**YourAppName.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib**". But I don't understand what‘s the reason, can someone help explain it?

This fixed it for me on UTM macOS ventura VM. It works for all electron applications I have tried so far.
 
I was able to locate the file for Chrome but it didn't enable GPU acceleration for Chrome, which is a shame because macOS VMs on M1 devices are able to utilise the host GPU.
