### ISSUE TITLE
Publish the public API as JSON

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#3375]
Atom builds and ships an [`atom-api.json`](https://github.com/atom/atom/releases/download/v1.1.0/atom-api.json) file that lists the signatures for the entire public API to allow doc generation and API tooling.

It would be great to have something similar to electron to enable things like https://github.com/atom/autocomplete-atom-api for Electron.

Shout out to @fxfactorial who asked about this at last week's Electron meetup.

/cc @jlord

**Comment by zeke** [comment]
Work in progress: https://github.com/electron/electron/pull/6408

**Comment by mmc41** [comment]
Would love an official .d.ts typings file for electron (should be part of the npm like angular2 does)

**Comment by kevinsawicki** [comment]
Closing this out since #6408 was merged and this will be included in the next release, 1.4.1
