### ISSUE TITLE
[Bug]: ERR_ABORTED crash when navigating a window inside of the did-create-window handler

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#33765]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3 -> 12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I expect to be able to navigate a window in the `did-create-window` handler without error

### Actual Behavior

`loadURL` rejects with an `ERR_ABORTED (-3)` error.

### Testcase Gist URL

https://gist.github.com/aeb44402693a4694ff99786ddd211fdc

### Additional Information

So I guess we're not awaiting the navigation before emitting the `did-create-window` event. Is that expected?

1. start app
2. in devtools, open a window (e.g. `window.open("about:blank")`)
3. observe the crash popup:
![image](https://user-images.githubusercontent.com/6374473/163227948-b775122c-1e40-4d98-a81e-5193b304269d.png)

If I wrap the `loadURL` call in a `setTimeout(..., 0)`, it works fine.

I might consider just ignoring that `ERR_ABORTED` error in this case like I'm doing in [this issue](https://github.com/electron/electron/issues/28338). (Actually no that's not a great solution; I will do the navigation on a timer instead)

**Comment by pushkin-** [comment]
An explicit `win.webContents.stop()` call does not prevent the crash

**Comment by pushkin-** [comment]
seems like for my purposes I can do the navigation in a `did-finish-load`, or `did-fail-load` event handler

**Comment by MarshallOfSound** [comment]
> So I guess we're not awaiting the navigation before emitting the did-create-window event. Is that expected?

Yes, this event is emitted when the window is made, completely independent of navigation start / end.  As you noted you should wait for the correct event or ignore this error
