### ISSUE TITLE
single node for all apps

### ISSUE THREAD

**Issue by yosef-123** [electron/electron#33769]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

electron is HUGE

### Proposed Solution

why not bundle node separately 
or even in chunks
so that it can be used one time for all electron apps thus cutting the size by a lot
and if put in chunks you can choose to not ask for all parts that aren't needed 

### Alternatives Considered

even just creating different parts of node and having options to not download all of them would lift the size problem by something

**Comment by Prinzhorn** [comment]
https://github.com/electron/electron/issues/673

https://github.com/electron/electron/issues/28604 (replace the word Chromium with Node.js)
