### ISSUE TITLE
[Bug]: Transparent WCO titlebar gets stuck in hover state

### ISSUE THREAD

**Issue by mitchchn** [electron/electron#33764]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

The titlebar should work the same way if its color is set to transparent.

### Actual Behavior

Set the titlebar color to transparent like so:

```
    titleBarOverlay: {
      symbolColor: "black",
      color: "rgba(0,0,0,0)"
    }
```  

While the bar is initially transparent, hovering over the controls with the mouse causes their background colors to remain in their hover state.

It is possible to get all three stuck controls in that state:

![image](https://user-images.githubusercontent.com/7342119/163211773-87cdc810-d720-451f-9d02-f458ee653c6d.png)

### Testcase Gist URL

https://gist.github.com/54bd745a5bce7c2a716e57008b20cd53

**Comment by SquitchYT** [comment]
I have the same issue

**Comment by mlaurencin** [comment]
As was mentioned in the feature request, WCO currently has issues supporting transparent background colors. I will keep this issue open until that information can be updated in the docs, but request that any further discussion be directed to the feature request.

**Comment by panther7** [comment]
![hover](https://user-images.githubusercontent.com/3808250/169792245-693c64c1-d108-42a2-81c6-1e48ffea0e11.gif)

 +1

**Comment by mlaurencin** [comment]
The docs were updated in https://github.com/electron/electron/pull/34278 to acknowledge this as a current limitation. Please direct any further follow-ups to the feature request linked above.

**Comment by FanningHau** [comment]
Any updates for this issue?
