### ISSUE TITLE
Add bounds parameter to `drop-files` tray event

### ISSUE THREAD

**Issue by davej** [electron/electron#3377]
Would it be possible to pass the tray `bounds` data when files are dropped onto the tray?

**Comment by davej** [comment]
Just to add, an alternative approach might be to add a `tray.getBounds()` method. I'm not sure of the difficulty in implementing either approach but `tray.getBounds()` might be a nicer approach because it can be used elsewhere (not just `drop-files` and click events).

**Comment by jmathai** [comment]
It would be great if the `drop-files` event would default the tray window to be centered like it is with `click` and `double-click`. Looks related to gh-1543

**Comment by kevinsawicki** [comment]
> Just to add, an alternative approach might be to add a tray.getBounds() method.

This was added in #6159 so I think this can be closed now since that API can be used from any tray event listener.
