### ISSUE TITLE
OS X accent tooltip doubles letters within a webview

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#3379]
(OS X El Capitan 10.11.1, Electron 0.34.0)

The tooltip on OS X to select accented characters (accessed by pressing and holding a key like "e") does not work correctly when used in a `webview`. The correct behavior (which is what happens outside a webview) is this:
- You press the letter "e".
- "e" appears in the text field you are typing in.
- You select "ë" from the tooltip.
- The original letter changes to the new letter, meaning the text field now has the value "ë".

In a webview, the original letter is not removed. This means that the above actions will make the text field have the value "eë", which is incorrect.
#50 fixed this, but this only works in the window renderer process.

**Comment by zcbenz** [comment]
I can reproduce the same bug in the webview of Chrome 46, seems to be a regression of https://code.google.com/p/chromium/issues/detail?id=450641.

Can you also report this to upstream Chromium?

**Comment by PalmerAL** [comment]
https://code.google.com/p/chromium/issues/detail?id=554107

**Comment by paulcbetts** [comment]
We've been seeing this bug too

**Comment by guillaumemolter** [comment]
Same issue here

**Comment by groundwater** [comment]
We're about to release 1.6.0 beta, when that happens can someone check again to see if this is still an issue.

**Comment by PalmerAL** [comment]
@groundwater It's still happening in 1.6.0. According to https://bugs.chromium.org/p/chromium/issues/detail?id=554107:

> I will try to work a temporary solution out. The solution on the browser side (as mentioned in comment #9) seems a bit nontrivial and any fix would be quite hacky. I will post an update as soon as I have a CL going.
