### ISSUE TITLE
[Feature Request]: Have access to chrome password manager feature

### ISSUE THREAD

**Issue by qleguennec** [electron/electron#33803]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I'd like to store user passwords in the user filesystem in such a way that is at least as secure as chrome password manager.

### Proposed Solution

 I think the best option would be to get a direct access to that chrome feature instead of reinventing the wheel, which is often very dangerous in security.

### Alternatives Considered

Reinventing the wheel.

**Comment by MarshallOfSound** [comment]
Electron does not expose any of Chromiums `//chrome` layer which includes most of it's UI including things like it's password manager feature.  This isn't something we will be exposing
