### ISSUE TITLE
[Bug]: clarify in Security document when contextIsolation should be enabled

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#33806]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The Security [doc](https://www.electronjs.org/docs/latest/tutorial/security#3-enable-context-isolation-for-remote-content) states:
>Enable Context Isolation for remote content

Based on some of the discussion in [this issue](https://github.com/electron/electron/issues/23506) (specifically [here](https://github.com/electron/electron/issues/23506#issuecomment-922092517)), it sounds like Electron is recommending that we enable `contextIsolation` for *all* content, remote or local.

Should the Sec doc be updated in that case? 

### Proposed Solution

Remove the bit about "remote content" from that section

### Alternatives Considered

n/a

**Comment by MarshallOfSound** [comment]
You're correct, PR filed above
