### ISSUE TITLE
[Bug]: ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied

### ISSUE THREAD

**Issue by lenchvolodymyr** [electron/electron#33801]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 19044.1645

### What arch are you using?

x64

### Last Known Working Electron version

13.0.0

### Expected Behavior

When running 2 instances of the electron the terminal output is empty

### Actual Behavior

There is an error with access denied

[12816:0415/123016.202:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[12816:0415/123016.202:ERROR:cache_util.cc(146)] Unable to move cache folder C:\Users\User\AppData\Roaming\Electron\GPUCache to C:\Users\User\AppData\Roaming\Electron\old_GPUCache_000
[12816:0415/123016.202:ERROR:disk_cache.cc(185)] Unable to create cache
[12816:0415/123016.202:ERROR:shader_disk_cache.cc(612)] Shader Cache Creation failed: -2

### Additional Information

Steps to reproduce:

1. Install electron
npm i electron@17

2. In 2 terminals run:
npx electron

3. In the second one you'll see the errors

[12816:0415/123016.202:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[12816:0415/123016.202:ERROR:cache_util.cc(146)] Unable to move cache folder C:\Users\User\AppData\Roaming\Electron\GPUCache to C:\Users\User\AppData\Roaming\Electron\old_GPUCache_000
[12816:0415/123016.202:ERROR:disk_cache.cc(185)] Unable to create cache
[12816:0415/123016.202:ERROR:shader_disk_cache.cc(612)] Shader Cache Creation failed: -2

Also, I haven't found any possibility to silence the output of these errors.

**Comment by ckerr** [comment]
I don't know the history of this, but it looks related to https://github.com/electron/electron/blob/main/patches/chromium/fix_patch_out_permissions_checks_in_exclusive_access.patch

**Comment by MUX-ON-WINDOWS** [comment]
I solved the problem with:
1. delete the dist map.
2. run your build again. The errors will not be displayed again.

**Comment by lenchvolodymyr** [comment]
@MUX-ON-WINDOWS what do you mean by deleting "dist map"? If you mean deleting js bundle, it won't help, because the issue is related to electron itself, even with empty html.  

In 18.2.3 and 17.4.3 the issue still exists.

**Comment by lenchvolodymyr** [comment]
any news on this issue? It still exists in electron@20.0.2
 
![image](https://user-images.githubusercontent.com/32545092/184868839-345b1379-727b-4c13-9f1a-d621652c701e.png)

Maybe there is a way to silence somehow it? Please, advise

**Comment by lenchvolodymyr** [comment]
any updates on this issue? It still happens on 20.x, 21.x, 22.x ...

**Comment by rinkeshjain** [comment]
@lenchvolodymyr, in my case there was some issue in the library code used in the project, the issue was something related to writing in file which is already in used

**Comment by nornagon** [comment]
Running multiple instances of an app with the same user-data directory isn't supported by Chrome, and thus isn't supported by Electron either. You'll need to use requestSingleInstanceLock, an in-memory session, or a separate data directory for each instance.
