### ISSUE TITLE
[Bug]: "Debugging on Windows" doc recommends a debug build, but directions for it are missing

### ISSUE THREAD

**Issue by bughit** [electron/electron#33805]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

N/A

### What operating system are you using?

Windows

### Operating System Version

N/A

### What arch are you using?

x64

### Expected Behavior

[Debugging on Windows](https://www.electronjs.org/docs/latest/development/debugging-on-windows) states the following:

> A debug build of Electron: The easiest way is usually building it yourself, using the tools and prerequisites listed in the [build instructions for Windows](https://www.electronjs.org/docs/latest/development/build-instructions-windows). While you can attach to and debug Electron as you can download it directly, you will find that it is heavily optimized, making debugging substantially more difficult: The debugger will not be able to show you the content of all variables and the execution path can seem strange because of inlining, tail calls, and other compiler optimizations.

However there are no [build directions](https://www.electronjs.org/docs/latest/development/build-instructions-gn) for producing a debug build. out/Testing is not debug, it's optimized and symbols for locals are missing.

Looking at testing.gn, there appear to be 3 args relevant to producing a debug build:

is_debug
is_component_build
symbol_level

But I found some [reports](https://github.com/electron/electron/issues?q=is%3Aissue+is_debug) that they're not working.

Please specify what is needed for producing a debug build.

### Actual Behavior

no debug build directions

**Comment by ckerr** [comment]
https://github.com/electron/electron/pull/31979 seems related to this but we ought to make it more explicit in the build directions
