### ISSUE TITLE
[Bug]: Electron is crashing while rendering google.com in webview

### ISSUE THREAD

**Issue by AbyAbyss** [electron/electron#33808]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

9.4.4

### Expected Behavior

Should render and navigate google.com

### Actual Behavior

Crashes when we try to navigate the page

### Testcase Gist URL

https://github.com/AbyAbyss/electron-webview-crashing

### Additional Information

Issue is reproducible in the following electron versions 10,11,12,13,14,15,16,17

Working fine in version 9 and 18

**Comment by mlaurencin** [comment]
I am having trouble reproducing your issue. I created a gist [here](https://gist.github.com/304bec74da3206b9d76fc1ca40dca874) with the code from your repository and tested on a few versions of 15+, as those are the currently supported versions. Are you seeing your issue with this gist as well?

**Comment by AbyAbyss** [comment]
Hi @mlaurencin,

**Comment by AbyAbyss** [comment]
Hi @mlaurencin,

As you are using electron version above 11, `contextIsolation` is set to true by default, so the function which i wrote was not reachable. 

Can you try again by setting `contextIsolation` as false under main.js->BrowserWindow
I have updated the above code.
```json
webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      webviewTag: true,
      enableRemoteModule: false,
      contextIsolation: false
    }
```

After this you can click on `Click to crash` button wait for 2-3 seconds

**Comment by mlaurencin** [comment]
I can confirm with this updated gist crashes occur in 15, 16, and 17, but not 18

**Comment by AbyAbyss** [comment]
Hi, it works fine in version 9 and 18. It crashes for versions 10 to 17. It also happens in other operating systems not just windows.
