### ISSUE TITLE
[Bug]: --ozone-platform-hint command line flag ignored

### ISSUE THREAD

**Issue by baltitenger** [electron/electron#33810]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Expected Behavior

Setting the `--ozone-platform-hint` flag to `auto` or `wayland` should make electron use wayland (assuming `--enable-features=UseOzonePlatform` is also set)

### Actual Behavior

The flag is ignored.

### Additional Information

Using `--ozone-platform=wayland` does work, but then it fails when not running wayland.

**Comment by bacteriostat** [comment]
Can reproduce this on Signal-desktop (electron 17.3.1), VSCode (electron 17.4.1).

Since this flag was added in chromium 97, Electron 17+ should support this flag.

**Comment by MarshallOfSound** [comment]
As documented Electron doesn't automatically inherit all Chromium flags.  That flag for instance is supported inside `//chrome` **not** `//content` which means we don't support it by default.

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/chrome_browser_main_extra_parts_linux.cc;l=123-135;drc=edab26bf11e993e5069d433e8c2186ad2dee012e;bpv=1;bpt=1

Someone would have to copy that code into the right place
