### ISSUE TITLE
[Bug]: how ti ignore certification when access wss://

### ISSUE THREAD

**Issue by Dobedoooo** [electron/electron#33821]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.2.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

working fine with ws

### Actual Behavior

Im trying to connect to a webSocket server in main porcess, like this
```javascript
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'
import { app, BrowserWindow, shell, Menu, session, ipcMain, webContents } from 'electron'
import { release } from 'os'
import { join } from 'path'
import WebSocket from 'ws'

// Disable GPU Acceleration for Windows 7
if (release().startsWith('6.1')) app.disableHardwareAcceleration()

// Set application name for Windows 10+ notifications
if (process.platform === 'win32') app.setAppUserModelId(app.getName())

if (!app.requestSingleInstanceLock()) {
  app.quit()
  process.exit(0)
}

let win: BrowserWindow | null = null

async function createWindow() {
  const ws = new WebSocket(`wss://riot:5HCbnfG0fBc8OyNhJJJGQw@127.0.0.1:49932`, 'wamp')
	win = new BrowserWindow({
......
```
I set ```process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'```, but still got error
![uTools_1650281467443](https://user-images.githubusercontent.com/57029169/163802268-2cd8adca-7666-47c2-93f7-e5766919ba90.png)

**Comment by Dobedoooo** [comment]
please help me😭

**Comment by mlaurencin** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
