### ISSUE TITLE
setProxy account password login loadURL error: Failed to load URL: https://www.google.com/ with error: ERR_TIMED_OUT

### ISSUE THREAD

**Issue by 15138024314** [electron/electron#33820]
I created a new sub-window in the main window and I want this sub-window to load google and I set up an http proxy for this sub-window. The proxy given by the company requires account and password authentication to log in and I found that the login function has not been triggered. Please everyone Look at my demo code I hope to get everyone's help
`ipcMain.on('createChildWindow' ,async (event ,arg)=>{
  const childwindow = new BrowserWindow({
    width: 1200,
    height: 800,
    frame: true,
    maximizable: true,
    webPreferences: {
      devTools: true,
      webviewTag: true,
      nodeIntegration: true,
      enableRemoteModule: true,
      contextIsolation: false,
      preload: app.isPackaged ? path.resolve("resources/webview.js") : path.resolve("src/webview.js")
    },
  });

  childwindow.webContents.openDevTools();

  childwindow.webContents.session.setProxy({
    proxyRules: "http://85.92.109.253:3128",
  }).then(() => {
    childwindow.loadURL(`https://google.com/`);
  }).catch((err) => console.error(err));

  childwindow.on('login' ,(event, webContents, details, authInfo, callback)=>{
    event.preventDefault();
    console.log('app');
    callback('sub_1kni3wjb4g9i6pkhmbsz5qzd', 'stat900');
  });

  childwindow.webContents.session.resolveProxy('https://google.com/').then(res=>{
    console.log(res);
  }).catch(error=>{
    console.log(error);
  });

});
`

**Comment by 15138024314** [comment]
"electron": "^18.0.4",

**Comment by mlaurencin** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
