### ISSUE TITLE
[Bug]: Electron app crashes when window opened on external monitor and Zoom is running

### ISSUE THREAD

**Issue by sircharlo** [electron/electron#33862]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 19044

### What arch are you using?

x64

### Expected Behavior

I develop [an app](https://github.com/sircharlo/jw-meeting-media-fetcher) that is used by a few hundred users worldwide and works quite well. 

The app is intended to load a main window, and then upon clicking a button, a second window. 
If an external monitor is present, the 2nd window is opened on the external monitor and goes fullscreen. 
If only one monitor is present, the 2nd window is windowed and has the dimensions of 1280x720.

This behaviour is consistent across platforms and for (almost) all users.

### Actual Behavior

One user in particular is experiencing an issue that he can reproduce reliably on 3 out of his 6 computers. He is to my knowledge the only one with this issue.

When opening the app, all is well, the app is stable, nothing bad happens.
As soon as Zoom is opened, within 15 seconds, my app crashes. 
Notably, the crash in my app happens whether a meeting is started or not in Zoom. 
Simply having Zoom opened to its main login window is enough to crash my app.

I have attached a few of my app's crash reports [here](https://github.com/electron/electron/files/8524806/99b76acb-1c20-49b2-a0a9-c957b5be374f.zip), but they all seem to indicate the same error: 
`0x80000003 - {EXCEPTION}  Breakpoint  A breakpoint has been reached.`

### Additional Information

Some additional info:

- The problem never presents itself if Zoom is not opened.
- The problem presents itself regardless of whether Zoom was opened first, or my app.

Steps we tried:

- Disabling hardware acceleration using `app.disableHardwareAcceleration();`: **no change**
- Running my app without clicking the button to open the second window: **my app no longer crashes**
- Wiping Zoom completely and reinstalling the latest version: **no change**
- Disabling hardware acceleration in Zoom: **no change**

To me this seems to indicate some sort of issue wherein both Zoom and my app fight each other to control the second screen for some reason; however this is just an educated guess. I had high hopes for disabling hardware acceleration, thinking it might be a GPU issue, but the issue happens regardless.

Some might say the issue is with Zoom if it is making my app crash, but I would argue against that, as I run Zoom and my app concurrently on multiple computers, as do the hundreds of other users, and nothing like this has ever happened, except for that one user's three computers.

**Comment by mlaurencin** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.

Thanks in advance! Your help is appreciated.

**Comment by sircharlo** [comment]
I'm afraid I won't be able to create a gist or testcase with reproducible failure, as I myself am unable to reproduce the error. Only the one user on his three computers has the issue.
The only clue that I have is that two of the three are Dell Alienware PCs; I thought maybe a driver issue? But really the minidumps are all I have to go on.

**Comment by mathieu2345** [comment]
I have the same issue as well. I had 2,500 crashes reported in the first 72 hours after deploying 18.0.4 "breakpoint_80000003". From my analysis of the minidumps and user emails, it appears to be linked to the Zoom meeting application.  Very similar to what @sircharlo reported above. 

FYI - rolling back to v17 has temporarily resolved the issue for me.

**Comment by VerteDinde** [comment]
@sircharlo Can you try upgrading your app to 18.3.0 or later? We removed a recent addition where second instances of apps were using named pipes, and those named pipes were colliding with each other in certain sessions - I'd be curious if removing this fixes the issue with Zoom.

**Comment by sircharlo** [comment]
Yeah, I figured as much. I noticed that the issue went away with 18.3.0. Figured it was due to that commit.

I'll close this issue. Thanks for the update!
