### ISSUE TITLE
Handle close notifications from RestartManager

### ISSUE THREAD

**Issue by felicienfrancois** [electron/electron#3387]
RestartManager is a windows API that allows installers to close an App or Service to be able to update files in use, and eventually restart the App or service afterward.
https://msdn.microsoft.com/en-us/library/windows/desktop/aa373524.aspx

This is used by Windows Installer 4+ and most installer frameworks (innosetup, nsis, ...).

Currently Electron cannot be closed automatically from such installers.

**Comment by clericc** [comment]
upvote

**Comment by codebytere** [comment]
closing due to abandonment.
