### ISSUE TITLE
electron crashes on Mac 12.3.1

### ISSUE THREAD

**Issue by zhouzhanyi** [electron/electron#33875]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1

### What arch are you using?

x64

### Last Known Working Electron version

17.0.0

### Expected Behavior

Open the app crashes

### Actual Behavior

Open the app crashes

### Additional Information

The crash stack is as follow：
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process: EasyConnect [3197]
Path: /Applications/EasyConnect.app/Contents/MacOS/EasyConnect
Identifier: com.sangfor.Easyconnect
Version: 7.6.3 (102)
Code Type: X86-64 (Native)
Parent Process: launchd [1]
User ID: 501

Date/Time: 2022-04-18 10:55:44.1039 +0800
OS Version: macOS 12.3.1 (21E258)
Report Version: 12
Anonymous UUID: 9BD6E728-C832-A273-F638-069C0D618686

Time Awake Since Boot: 1000 seconds

System Integrity Protection: disabled

Crashed Thread: 0 CrBrowserMain Dispatch queue: com.apple.main-thread

Exception Type: EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY

Termination Reason: Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process: exc handler [3197]

Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread
0 Electron Framework 0x1134d5031 0x1132dd000 + 2064433
1 Electron Framework 0x113502a25 0x1132dd000 + 2251301
2 Electron Framework 0x113414c26 0x1132dd000 + 1276966
3 Electron Framework 0x113414285 0x1132dd000 + 1274501
4 Electron Framework 0x1134139d7 ProcessSingleton::Create() + 887
5 Electron Framework 0x11341362a ProcessSingleton::NotifyOtherProcessWithTimeoutOrCreate(base::CommandLine const&, int, base::TimeDelta const&) + 42
6 Electron Framework 0x1134135ed ProcessSingleton::NotifyOtherProcessOrCreate() + 45
7 Electron Framework 0x1132e9dae atom::api::App::MakeSingleInstance(base::Callback<bool (std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, base::FilePath const&), (base::internal::CopyMode)1, (base::internal::RepeatMode)1> const&) + 158
8 Electron Framework 0x1132ed73e 0x1132dd000 + 67390
9 Electron Framework 0x1132ed6ff 0x1132dd000 + 67327
10 Electron Framework 0x1132f6a1f 0x1132dd000 + 104991
11 Electron Framework 0x1132f77a0 base::internal::Invoker<base::internal::BindState<bool (atom::api::App::*)(base::Callback<bool (std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, base::FilePath const&), (base::internal::CopyMode)1, (base::internal::RepeatMode)1> const&)>, bool (atom::api::App*, base::Callback<bool (std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, base::FilePath const&), (base::internal::CopyMode)1, (base::internal::RepeatMode)1> const&)>::Run(base::internal::BindStateBase*, atom::api::App*&&, base::Callback<bool (std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, base::FilePath const&), (base::internal::CopyMode)1, (base::internal::RepeatMode)1> const&) + 32
12 Electron Framework 0x1132ea711 0x1132dd000 + 55057
13 Electron Framework 0x1132f71b2 0x1132dd000 + 106930
14 Electron Framework 0x1132f707c mate::internal::Dispatcher<bool (atom::api::App*, base::Callback<bool (std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, base::FilePath const&), (base::internal::CopyMode)1, (base::internal::RepeatMode)1> const&)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 124
15 libnode.dylib 0x1105b6025 0x1103ba000 + 2080805
16 libnode.dylib 0x110666fe8 0x1103ba000 + 2805736
17 libnode.dylib 0x110666541 0x1103ba000 + 2803009
18 ??? 0x270e928843a7 ???
19 ??? 0x270e92b3e571 ???
20 ??? 0x270e92b32297 ???
21 ??? 0x270e92b31b80 ???
22 ??? 0x270e92a40325 ???
23 ??? 0x270e929b662b ???
24 ??? 0x270e92885cd5 ???
25 ??? 0x270e9290915a ???
26 ??? 0x270e928f23f8 ???
27 ??? 0x270e92b0785c ???
28 ??? 0x270e92a40325 ???
29 ??? 0x270e929b662b ???
30 ??? 0x270e92885cd5 ???
31 ??? 0x270e9291951a ???
32 ??? 0x270e928f23f8 ???
33 ??? 0x270e92885cd5 ???
34 ??? 0x270e92b3a9a2 ???
35 ??? 0x270e92b04af6 ???
36 ??? 0x270e92af971d ???
37 ??? 0x270e9290915a ???
38 ??? 0x270e928f23f8 ???
39 ??? 0x270e92af0bde ???
40 ??? 0x270e92885cd5 ???
41 ??? 0x270e92b3117c ???
42 ??? 0x270e92b23763 ???
43 ??? 0x270e928f1ac3 ???
44 ??? 0x270e928b65c1 ???
45 libnode.dylib 0x110833775 0x1103ba000 + 4691829
46 libnode.dylib 0x1108334d9 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 169
47 libnode.dylib 0x1105d502b v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 459
48 Electron Framework 0x113303e99 mate::internal::V8FunctionInvoker<void (atom::api::Cookies::Error, std::__1::vector<net::CanonicalCookie, std::__1::allocator<net::CanonicalCookie> > const&)>::Go(v8::Isolate*, mate::internal::SafeV8Function const&, atom::api::Cookies::Error, std::__1::vector<net::CanonicalCookie, std::__1::allocator<net::CanonicalCookie> > const&) + 249
49 Electron Framework 0x113304016 0x1132dd000 + 159766
50 Electron Framework 0x113303ffc 0x1132dd000 + 159740
51 Electron Framework 0x113303fe1 0x1132dd000 + 159713
52 Electron Framework 0x113303f70 base::internal::Invoker<base::internal::BindState<void (*)(v8::Isolate*, mate::internal::SafeV8Function const&, atom::api::Cookies::Error, std::__1::vector<net::CanonicalCookie, std::__1::allocator<net::CanonicalCookie> > const&), v8::Isolate*, mate::internal::SafeV8Function>, void (atom::api::Cookies::Error, std::__1::vector<net::CanonicalCookie, std::__1::allocator<net::CanonicalCookie> > const&)>::Run(base::internal::BindStateBase*, atom::api::Cookies::Error&&, std::__1::vector<net::CanonicalCookie, std::__1::allocator<net::CanonicalCookie> > const&) + 32
53 Electron Framework 0x113301fb0 0x1132dd000 + 151472
54 Electron Framework 0x113301f7b 0x1132dd000 + 151419
55 Electron Framework 0x113301f69 0x1132dd000 + 151401
56 Electron Framework 0x113301f51 0x1132dd000 + 151377
57 Electron Framework 0x113301ef4 base::internal::Invoker<base::internal::BindState<base::Callback<void (atom::api::Cookies::Error, std::__1::vector<net::CanonicalCookie, std::__1::allocator<net::CanonicalCookie> > const&), (base::internal::CopyMode)1, (base::internal::RepeatMode)1>, atom::api::Cookies::Error, std::__1::vector<net::CanonicalCookie, std::__1::allocator<net::CanonicalCookie> > >, void ()>::Run(base::internal::BindStateBase*) + 20
58 Electron Framework 0x11353bfc1 0x1132dd000 + 2486209
59 Electron Framework 0x11350fa06 0x1132dd000 + 2304518
60 Electron Framework 0x11350fcdc 0x1132dd000 + 2305244
61 Electron Framework 0x113510023 0x1132dd000 + 2306083
62 Electron Framework 0x11351336d 0x1132dd000 + 2319213
63 Electron Framework 0x1134d021a 0x1132dd000 + 2044442
64 Electron Framework 0x113512de4 0x1132dd000 + 2317796
65 CoreFoundation 0x7ff80f258aeb __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
66 CoreFoundation 0x7ff80f258a53 __CFRunLoopDoSource0 + 180
67 CoreFoundation 0x7ff80f2587cd __CFRunLoopDoSources0 + 242
68 CoreFoundation 0x7ff80f2571e8 __CFRunLoopRun + 892
69 CoreFoundation 0x7ff80f2567ac CFRunLoopRunSpecific + 562
70 HIToolbox 0x7ff817eddce6 RunCurrentEventLoopInMode + 292
71 HIToolbox 0x7ff817edda4a ReceiveNextEventCommon + 594
72 HIToolbox 0x7ff817edd7e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
73 AppKit 0x7ff811c7d53d _DPSNextEvent + 927
74 AppKit 0x7ff811c7bbfa -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
75 AppKit 0x7ff811c6e2a9 -[NSApplication run] + 586
76 Electron Framework 0x113513bbe 0x1132dd000 + 2321342
77 Electron Framework 0x11351322c 0x1132dd000 + 2318892
78 Electron Framework 0x11350f76e 0x1132dd000 + 2303854
79 Electron Framework 0x1135242c3 0x1132dd000 + 2388675
80 Electron Framework 0x1137744db 0x1132dd000 + 4814043
81 Electron Framework 0x113774330 0x1132dd000 + 4813616
82 Electron Framework 0x113776a72 0x1132dd000 + 4823666
83 Electron Framework 0x11377040c 0x1132dd000 + 4797452
84 Electron Framework 0x1136d5f7d 0x1132dd000 + 4165501
85 Electron Framework 0x1136d5076 0x1132dd000 + 4161654
86 Electron Framework 0x1132df787 AtomMain + 71
87 EasyConnect 0x10ef4ff26 main + 38
88 dyld 0x11ab3a51e start + 462

Thread 1:
0 libsystem_pthread.dylib 0x7ff80f18df48 start_wqthread + 0

Thread 2:: WorkerPool/13067
0 libsystem_kernel.dylib 0x7ff80f1583ea __psynch_cvwait + 10
1 libsystem_pthread.dylib 0x7ff80f192aa4 _pthread_cond_wait + 1302
2 Electron Framework 0x1134d438b 0x1132dd000 + 2061195
3 Electron Framework 0x1135658f9 0x1132dd000 + 2656505
4 Electron Framework 0x113565d57 0x1132dd000 + 2657623
5 Electron Framework 0x11351a357 0x1132dd000 + 2347863
6 libsystem_pthread.dylib 0x7ff80f1924e1 _pthread_start + 125
7 libsystem_pthread.dylib 0x7ff80f18df6b thread_start + 15

Thread 3:: NetworkConfigWatcher
0 libsystem_kernel.dylib 0x7ff80f15597a mach_msg_trap + 10
1 libsystem_kernel.dylib 0x7ff80f155ce8 mach_msg + 56
2 CoreFoundation 0x7ff80f258cdd __CFRunLoopServiceMachPort + 319
3 CoreFoundation 0x7ff80f257368 __CFRunLoopRun + 1276
4 CoreFoundation 0x7ff80f2567ac CFRunLoopRunSpecific + 562
5 Foundation 0x7ff8100aad9a -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 216
6 Electron Framework 0x1135139ee 0x1132dd000 + 2320878
7 Electron Framework 0x11351322c 0x1132dd000 + 2318892
8 Electron Framework 0x11350f76e 0x1132dd000 + 2303854
9 Electron Framework 0x1135242c3 0x1132dd000 + 2388675
10 Electron Framework 0x11353cc22 0x1132dd000 + 2489378
11 Electron Framework 0x11351a357 0x1132dd000 + 2347863
12 libsystem_pthread.dylib 0x7ff80f1924e1 _pthread_start + 125
13 libsystem_pthread.dylib 0x7ff80f18df6b thread_start + 15

**Comment by miniak** [comment]
EasyConnect is a 3rd party app and the issue needs to be reported there
