### ISSUE TITLE
[Bug]: Crash in WebFrameMain::Connect() -> GetInterface -> GetInterfaceByName

### ISSUE THREAD

**Issue by t57ser** [electron/electron#33880]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17, 18

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.985

### What arch are you using?

x64

### Last Known Working Electron version

14

### Expected Behavior

No crash

### Actual Behavior

Electron crashes
![2022-04-21 10_07_53-Source Not Found (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/10595986/164416772-c4800f31-d165-4639-88e3-23be25d8fe8c.png)

This does not happen consistently but fairly often and can be reproduced in the app.
I have not been able yet to make a small/standalone reproducable example

**Comment by t57ser** [comment]
Some testing results:
15.0.0 -> working
16.0.0 -> working
16.2.3 -> working
17.4.1 -> crash
18.0.4 -> crash

**Comment by t57ser** [comment]
I can see that each time before the crash it seems like a renderer is crashing first and then 2-3s later electron crashes

**Comment by samuelmaddock** [comment]
Thanks for including the stacktrace! This seems to be occurring when a speculative RenderFrameHost is created upon navigating with `webContents.loadURL`.

Here we prevent emitting the "frame-created" event with speculative render frames. A potential fix would be to prevent calling `WebFrameMain::Connect` with speculative render frames.

https://github.com/electron/electron/blob/6a1748da0608428fe902a3fc04a27899cd9803ad/shell/browser/api/electron_api_web_contents.cc#L1525-L1539

To write a reproducible test case, it will have something to do with cross-origin navigation.

**Comment by samuelmaddock** [comment]
Hey @t57ser. The PR I created should fix the issue, but I still was never able to reproduce the crash. Did you have any luck in reproducing a minimal case in [Electron Fiddle](https://www.electronjs.org/fiddle) or would you be open to it?

Could you maybe describe what happens in your app which leads up to the crash? It seems like you were able to reproduce it reliably.

**Comment by t57ser** [comment]
I am not 100% sure what causes it, but I can tell what fixed it.
At startup of the app, multiple windows are loaded with 3rd party apps, one of those seems to cause a crash (renderer crash) and afterwards electron crashes. I fixed it by not allowing loadURL in partitions that experienced a content crash.
I guess it is a combination of a renderer crashing and calling loadURL?
Maybe to note as well, the app is only consistently crashing since v17. Probably something changed that is now causing the app to crash and has negative side effects

**Comment by samuelmaddock** [comment]
> I guess it is a combination of a renderer crashing and calling loadURL?

This ended up being correct, thanks @t57ser. #34428 added tests for this. A slight delay was needed to reproduce the crash.
