### ISSUE TITLE
need to detect if the application runs on Virtual Machine or not 

### ISSUE THREAD

**Issue by muhamedRadwan** [electron/electron#33894]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

need to detect if the application runs on Virtual Machine or not 

### Proposed Solution

function to detect if the application run on virtual machine or not 

### Alternatives Considered

I use this code in C# 
      using (ManagementObjectSearcher managementObjectSearcher = new ManagementObjectSearcher("Select * from Win32_ComputerSystem"))

to check if current OS is virtual or not

**Comment by miniak** [comment]
This is not something that needs to be provided by Electron core. You can easily implement such a such in a native node module.

**Comment by miniak** [comment]
The only exception would be if Chromium already provides such API that we could just expose in Electron easily.

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by El-Zayat** [comment]
Did you find a way to detect? @muhamedRadwan

**Comment by muhamedRadwan** [comment]
> Did you find a way to detect? @muhamedRadwan

no

**Comment by Romain-P** [comment]
@muhamedRadwan  You can create your own DLL and map it to your app, and check basic stuffs like the CPU Vendor ID (KVM, QEMU etc)
