### ISSUE TITLE
[Bug]: UTF-8 productName is interpreted as latin1 on Gnome Shell App Menu

### ISSUE THREAD

**Issue by MrMYHuang** [electron/electron#33903]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.2.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux fedora 5.14.10-300.fc35.aarch64 #1 SMP Thu Oct 7 20:32:40 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Electron app can correctly show UTF-8 productName on Gnome Shell app menu.

### Actual Behavior

This issue is specific to Gnome Shell (41) app menu. Can be reproduced with Electron 17 or 18.

I develop an Electron app:
https://github.com/MrMYHuang/cbetar2

This app can be run in dev mode by:
```
git clone --recursive https://github.com/MrMYHuang/cbetar2
npm i
npm run start

# In another terminal, run
npm run start-electron
```
The app specifies a Chinese productName "電子佛典" in UTF-8 in package.json. The Electron app correctly shows the productName on the window title bar but not on the Gnome Shell app menu as shown in here:
![image](https://user-images.githubusercontent.com/12458706/164883113-ffc6983c-2590-4c7d-b7bb-3e92525264a8.png)

However, if you change productName to any English words and restart the app, both the Gnome Shell app menu and the window title bar display correctly.

By my study this is an issue of displaying UTF-8 string as latin1: try to open a new file by vscode and copy the string "電子佛典" to it and *SAVE* it with UTF-8, like this:
![image](https://user-images.githubusercontent.com/12458706/164883460-ecbeee84-871d-4908-ba1c-401fda76bb50.png)
Then, click the UTF-8 button on vscode and click "Reopen with encoding" and "Western (ISO 8859-1)" (latin1), you will get this:
![image](https://user-images.githubusercontent.com/12458706/164883536-5d09855c-1c7e-41df-83bc-ce2dfb93ee2d.png)
The misinterpreted text is the same as the Chinese one shown in the Gnome Shell app menu. Thus, it's an issue of UTF-8 strings misinterpreted as latin1.

This app is also packed as flatpak and available on Flathub:
```
flatpak remote-modify --no-filter flathub
flatpak install flathub io.github.mrmyhuang.cbetar2
flatpak run io.github.mrmyhuang.cbetar2
```
(You can also pack it by yourself by running `npm run dist-flatpak-dev`.)
Surprisingly, I have no idea why this one correctly displays the Chinese name on the Gnome Shell app menu:
![image](https://user-images.githubusercontent.com/12458706/164884337-5f3c34da-a6d3-4df3-9a3b-318f41f8fec1.png)

Furthermore, if you run the app directly without using `flatpak run`, the Chinese name will display incorrectly again:
```
/var/lib/flatpak/app/io.github.mrmyhuang.cbetar2/current/active/files/main/cbetar2
```

**Comment by weiluenju** [comment]
I have the same issue.

But even if I use electron builder to pack AppImage format, the menu bar still show incorrect name.

**Comment by MrMYHuang** [comment]
I tried many workarounds (but only one works):
1. Use desktopName in package.json: (failed)
2. Use chromium-browser / Electron command line option `--class`: (failed)
3. Use chromium-browser / Electron environment variable CHROME_DESKTOP=foo.desktop: (failed)
4. Use ${nameInPackageJson}.desktop: (works!)

In the 4th method, you have to create a UTF-8 encoding desktop entry file, e.g.,
https://github.com/MrMYHuang/cbetar2/blob/master/buildElectron/io.github.mrmyhuang.cbetar2.desktop
and ensure it will be installed to `/usr/share/applications`, e.g.,  `/usr/share/applications/foo.desktop`
You can use non latin1 characters in Name field in `.desktop` file.
Then, `name` in your Electron app package.json must be equal to the desktop entry filename without `.desktop`, e.g.,  `foo`.

If you manually copy `.desktop` file to `/usr/share/applications`, don't forget to logout and login your desktop manager once to take the effect.

**Comment by weiluenju** [comment]
The method 4 didn't work for me.

The name in desktop file seems to only affect the name inside the launchpad.

I also try to use the app.setName(), but the menu bar still show garbled characters if I use Chinese.

> I tried many workarounds (but only one works):
> 
> 1. Use `.desktop` file and desktopName in package.json: (failed)
> 2. Use `.desktop` file and chromium-browser / Electron command line option `--class`: (failed)
> 3. Use `.desktop` file and chromium-browser / Electron environment variable CHROME_DESKTOP=foo.desktop: (failed)
> 4. Use ${nameInPackageJson}.desktop: (works!)
> 
> In the 4th method, you have to create a UTF-8 encoding desktop entry file, e.g., https://github.com/MrMYHuang/cbetar2/blob/master/buildElectron/io.github.mrmyhuang.cbetar2.desktop and ensure it will be installed to `/usr/share/applications`, e.g., `/usr/share/applications/foo.desktop` You can use non latin1 characters in Name field in `.desktop` file. Then, `name` in your Electron app package.json must be equal to the desktop entry filename without `.desktop`, e.g., `foo`.
> 
> If you manually copy `.desktop` file to `/usr/share/applications`, don't forget to logout and login your desktop manager once to take the effect.

**Comment by MrMYHuang** [comment]
> The method 4 didn't work for me.

You can debug whether the correct desktop entry is associated with your launched app by `lg`:
1. In a terminal, run `echo $XDG_DATA_DIRS`
2. Launch your app:
3. In Gnome Shell, press Alt+F2
4. Type `lg`
5. Switch to Windows tab
6. Check whether your app's app field has a corresponding desktop entry in one of $XDG_DATA_DIRS
For example:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/12458706/165231390-15be3fa8-17d2-4cc6-87ed-9f144e3743a3.png">

**Comment by weiluenju** [comment]
Thank you. It is work.

But I thing it still a bug for Electron, because when I pack the program into a AppImage format.

The desktop file is not require. The desktop integration will handle by AppImageLauncher.


> > The method 4 didn't work for me.
> 
> You can debug whether the correct desktop entry is associated with your launched app by `lg`:
> 
> 1. In a terminal, run `echo $XDG_DATA_DIRS`
> 2. Launch your app
> 3. In Gnome Shell, press Alt+F2
> 4. Type `lg`
> 5. Switch to Windows tab
> 6. Check whether your app's app field has a corresponding desktop entry in one of $XDG_DATA_DIRS
> 
> For example: <img alt="image" width="526" src="https://user-images.githubusercontent.com/12458706/165231390-15be3fa8-17d2-4cc6-87ed-9f144e3743a3.png">

**Comment by MrMYHuang** [comment]
> 4\. Use ${nameInPackageJson}.desktop and remove productName in package.json: (works!)

Sorry, I updated the 4th method a little bit in the original comment. It needs to remove productName in package.json so an Electron app will use name in package.json as wmclass. Gnome Shell select a desktop file for one app based on wmclass value from one of $XDG_DATA_DIRS. For example, name in package.json is foo. A launched Electron app with the package.json has a wmclass value foo. Gnome Shell loads foo.desktop from one of $XDG_DATA_DIRS for the app and use Name in foo.desktop as menu bar name. Fortunately, we can use UTF-8 Name in .desktop file.

If a package.json contains productName, it seems the Electron app will use productName as wmclass value. But unfortunately, productName with non-latin1 characters doesn't work with desktop file.

If one uses electron-builder to build packages, I provide electron-builder configs for Windows, macOS, and Linux to workaround the non-latin1 prodcutName problem without using it in package.json:
https://github.com/MrMYHuang/cbetar2/tree/master/electronBuilderConfigs

**Comment by sohobloo** [comment]
> > 4. Use ${nameInPackageJson}.desktop and remove productName in package.json: (works!)
> 
> Sorry, I updated the 4th method a little bit in the original comment. It needs to remove productName in package.json so an Electron app will use name in package.json as wmclass. Gnome Shell selects a desktop file for one app based on wmclass value from one of $XDG_DATA_DIRS. For example, name in package.json is foo. A launched Electron app with the package.json has a wmclass value foo. Gnome Shell loads foo.desktop from one of $XDG_DATA_DIRS for the app and use Name in foo.desktop as menu bar name. Fortunately, we can use UTF-8 Name in .desktop file.
> 
> If a package.json contains productName, it seems the Electron app will use productName as wmclass value. But unfortunately, productName with non-latin1 characters doesn't work with desktop file.
> 
> If one uses electron-builder to build packages, I provide electron-builder configs for Windows, macOS, and Linux to workaround the non-latin1 prodcutName problem without using it in package.json: https://github.com/MrMYHuang/cbetar2/tree/master/electronBuilderConfigs

Here is my workaround for wmclass, maybe `productName` needn't remove from package.json?

```javascript
  // StartupWMClass does not support unicode.
  // according to Electron's source code, WM_CLASS is set to app.name as ASCII codec.
  // temporary set app.name to non unicode before creating new BrowserWindow
  // and restore it back after BrowserWindow was created.
  const originalAppName = Electron.app.name;
  if (process.platform === 'linux' && originalAppName !== LINUX_WM_CLASS_NAME) {
    Electron.app.setName(LINUX_WM_CLASS_NAME);
  }
  const window = new Electron.BrowserWindow(composedOptions);
  if (process.platform === 'linux' && Electron.app.name !== originalAppName) {
    Electron.app.setName(originalAppName);
  }
```

**Comment by MrMYHuang** [comment]
> Here is my workaround for wmclass, maybe `productName` needn't remove from package.json?

Thank you. It works.

I use the latin1-encoding name (e.g. foo) in package.json to make all Linux app having a latin1-encoding wmclass value. Run these before new BrowserWindow.
```
if (process.platform === 'linux') {
  app.setName(PackageInfos.name);
}
```
Then, packing foo.desktop to Linux package, so that after installing it, foo.desktop will be in one of $XDG_DATA_DIRS.

**Comment by weiluenju** [comment]
> > Here is my workaround for wmclass, maybe `productName` needn't remove from package.json?
> 
> Thank you. It works.
> 
> I use the latin1-encoding name (e.g. foo) in package.json to make all Linux app having a latin1-encoding wmclass value. Run these before new BrowserWindow.
> 
> ```
> if (process.platform === 'linux') {
>   app.setName(PackageInfos.name);
> }
> ```
> 
> Then, packing foo.desktop to Linux package, so that after installing it, foo.desktop will be in one of $XDG_DATA_DIRS.

Thnak you for your reply. I finally figured out what happened. 

The AppImageLauncher auto create the desktop file in ~/.local/share/applications/ folder.

But the filename of the desktop file is not equal to the name in package.json, so the app field in lg is show "untracked".

The part of the filename seems to be a random string(ex. appimagekit_[random]-[name].desktop).

Maybe I need to find out the filename of desktop and pass it to app.setName(). or any suggestions please provide to me.

Thank you.

**Comment by MrMYHuang** [comment]
> Maybe I need to find out the filename of desktop and pass it to app.setName(). or any suggestions please provide to me.

I don't setName to `appimagekit_[random]-[name]` as the one shown in `lg`. I just launch my AppImage by
[AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher).
After AppImageLauncher moves your AppImage to ~/Applications, you can find your app launch icon in Gnome Shell Applications. Launching it, you might see your app having the correct name on Gnome Shell App Menu. You can also find the app field in lg is very different from its wmclass, for example, my cbetar2 app:
![image](https://user-images.githubusercontent.com/12458706/166266349-96657d63-191f-4ac0-99b0-ad13e225bf55.png)
(My AppImage: https://github.com/MrMYHuang/cbetar2/releases/download/v19.2.0/cbetar2_19.2.0_linux_x86_64.AppImage )

In my experience, it's not ***REQUIRED*** that Gnome Shell uses a wmclass value to find a corresponding .desktop file in $XDG_DATA_DIRS!  I find that is true if Electron apps are launched by some wrapper tools, including `flatpak run`, `snap`, and AppImageLauncher. However, I have no idea how these tools achieve that.

**Comment by MrMYHuang** [comment]
> @MrMYHuang can you try my AppImage file(https://eew.earthquake.tw/releases/linux/x64/oxwu-linux-x86_64.AppImage)? My package.json does not contain productName.

I can reproduce your problem with your app. I compare my app .desktop with your one and find your StartupWMClass contains non latin1 characters:
![image](https://user-images.githubusercontent.com/12458706/166393372-27d14221-b8c0-46a8-9b22-331b7c7c33db.png)

Thus, I think Gnome Shell find a corresponding .desktop by two rules:
1. Use wmclass value, e.g. foo, to find a corresponding foo.desktop in $XDG_DATA_DIRS.
2. Use wmclass value (foo) to find a corresponding .desktop with StartupWMClass=foo in $XDG_DATA_DIRS.

I also find electron-builder prefers to use productName than name as StartupWMClass. Fortunately, you can overwrite it with electron-builder config 'desktop'.

I suggest you to use this workaround for AppImage:
1. Use latin1 characters for name in package.json.
2. You can use UTF-8 characters for productName in package.json.
3. Overwrite StartupWMClass with name in package.json by an electron-builder config. For example:
https://github.com/MrMYHuang/cbetar2/blob/dc0359f7a86ddb7c9adabd7e97f0c454ef793e0a/electronBuilderConfigs/appImage.json
4. setName before new BrowserWindow.
```
if (process.platform === 'linux') {
  app.setName(PackageInfos.name);
}
```

**Comment by weiluenju** [comment]
> > @MrMYHuang can you try my AppImage file(https://eew.earthquake.tw/releases/linux/x64/oxwu-linux-x86_64.AppImage)? My package.json does not contain productName.
> 
> I can reproduce your problem with your app. I compare my app .desktop with your one and find your StartupWMClass contains non latin1 characters: ![image](https://user-images.githubusercontent.com/12458706/166393372-27d14221-b8c0-46a8-9b22-331b7c7c33db.png)
> 
> Thus, I think Gnome Shell find a corresponding .desktop by at least two rules:
> 
> 1. Use wmclass value, e.g. foo, to find a corresponding foo.desktop in $XDG_DATA_DIRS.
> 2. Use wmclass value (foo) to find a corresponding .desktop with StartupWMClass=foo in $XDG_DATA_DIRS.
> 
> I also find electron-builder prefers to use productName than name as StartupWMClass. Fortunately, you can overwrite it with electron-builder config 'desktop'.
> 
> I suggest you to use this workaround for AppImage:
> 
> 1. Use latin1 characters for name in package.json.
> 2. You can use UTF-8 characters for productName in package.json.
> 3. Overwrite StartupWMClass with name in package.json by an electron-builder config. For example:
>    https://github.com/MrMYHuang/cbetar2/blob/dc0359f7a86ddb7c9adabd7e97f0c454ef793e0a/electronBuilderConfigs/appImage.json
> 4. setName before new BrowserWindow.
> 
> ```
> if (process.platform === 'linux') {
>   app.setName(PackageInfos.name);
> }
> ```

Thank you so much.

Overwrite the StartupWMClass(electron-builder config) with name in package.json is work.

I prefer not to set productName in package.json, because productName will be part of the file path(ex: userData), but not all character the systems allow in path. I only specify the productName in electron-builder config.

Again thank you for your help.
