### ISSUE TITLE
[Bug]: Can not play videos on Udemy

### ISSUE THREAD

**Issue by KazuyaHayashi** [electron/electron#33902]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6.5

### What arch are you using?

x64

### Last Known Working Electron version

17.4.0

### Expected Behavior

Can play videos on Udemy like the following gif
![can_play_videos](https://user-images.githubusercontent.com/441950/164883007-a08d1bb4-dc46-4fc0-9c97-b030ad99b7e0.gif)

### Actual Behavior

Electron v18.0.0 or later can not play videos on Udemy. This issue happens on Windows too.
I've checked this issue on Youtube but it didn't happen.
![can_NOT_play_videos](https://user-images.githubusercontent.com/441950/164882619-0371e3dc-7bd3-409d-a261-14699e5a4f77.gif)
.

### Testcase Gist URL

https://gist.github.com/KazuyaHayashi/0aa4ae76034daf6d023b61fca22093cb

**Comment by codebytere** [comment]
Bisected to https://github.com/electron/electron/compare/v18.0.0-alpha.5...v18.0.0-beta.1 - most likely 68c541380ecf4a8e67d23fab9bb0fa66cf700289

**Comment by joeyskuo** [comment]
> Bisected to [v18.0.0-alpha.5...v18.0.0-beta.1](https://github.com/electron/electron/compare/v18.0.0-alpha.5...v18.0.0-beta.1) - most likely [68c5413](https://github.com/electron/electron/commit/68c541380ecf4a8e67d23fab9bb0fa66cf700289)

I also think the issue is rooted in Chromium; the video would not load and I received the following CORS error in console:

<img width="585" alt="Screen Shot 2022-05-14 at 2 22 44 PM" src="https://user-images.githubusercontent.com/19828521/168448580-6ffff37c-b80c-4a99-a82e-2ef0b9205030.png">

**Steps taken**
Installed Chromium (Version 104.0.5063.0) on Mac 
Visited link (https://www.udemy.com/course/fearless-public-speaker-bootcamp-by-ricky-mendoza)
Clicked preview video

**Comment by pushkin-** [comment]
Not sure if it's the same issue, but I was seeing something like this on Windows, and the latest Electron 20 beta fixes it for me. Would be good to test this again.

**Comment by DanielPhilosoph1** [comment]
I'm getting this issue too on Electron 17.4.3 as well

**Comment by codebytere** [comment]
Closing as this is fixed in latest stable Electron.
