### ISSUE TITLE
[Bug]: Can't embed remote or local PDFs in iframes or webviews; crash when using custom protocol; can't print; crash when printing to PDF; demo provided.

### ISSUE THREAD

**Issue by george-thomas-hill** [electron/electron#33907]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 18.04 LTS

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

I expect to be able to embed remote or local PDFs in iframes and webviews.

I also expect to be able to load and display local media files via custom protocols.

I expect to be able to print the contents of a BrowserWindow using webContents.print().

I expect to be able to print to PDF using webContents.printToPDF().

### Actual Behavior

Using a fresh installation of Ubuntu 18.04 LTS, I used electron-forge to create a React-based Electron app.

This demo app is online here:

[https://github.com/george-thomas-hill/electron-pdf-demo](https://github.com/george-thomas-hill/electron-pdf-demo)

An iframe showing a remote PNG file loads correctly.

An iframe attemping to load a local PNG file gives a white empty iframe in the browser and an error in the browser console when run in development mode; however, when run as a packaged application it displays correctly.

An iframe attempting to load a remote PDF gives a gray empty iframe in the browser and no error in the browser console.

An iframe attempting to load a local PDF gives a white empty iframe in the browser and an error in the browser console when run in development mode; however, when run as a packaged application, it gives a gray empty iframe.

An iframe attempting to load a remote PDF with sandbox on gives a white empty iframe in the browser and no error in the browser console.

An iframe attempting to load a local PDF with sandbox on gives a white empty iframe in the browser and an error in the browser console.

A webview showing a remote PNG file loads correctly.

A webview showing a local PNG file loads correctly.

A webview attempting to load a remote PDF gives a gray empty webview and no error in the browser console but an error in the system terminal.

A webview attempting to load a local PDF gives a gray empty webview and no error in the browser console nor any error in the system terminal.

An iframe attempting to load a local PNG via a custom protocol causes a crash.

An iframe attempting to load a local PDF via a custom protocol causes a crash.

A webview showing a local PNG via a custom protocol works correctly.

A webview attempting to load a local PDF via a custom protocol gives a gray empty webview and no error.

I attempted to print my BrowserWindow in order to capture a convenient record of my demo application's output.

However, webContents.print() didn't work, and webContents.printToPDF() caused a crash.

Details are in the demo application's main.js file.

For best results, please consider downloading and running the demo application hosted at the GitHub address given above.

However, I am including screenshots here:

![screenshot-2022-04-23_08-36-20](https://user-images.githubusercontent.com/52637974/164910462-03283a6e-b8f2-41b6-82f7-4e7cca464266.png)

![screenshot-2022-04-23_08-36-32](https://user-images.githubusercontent.com/52637974/164910469-65483b3c-ce03-4d7e-a930-485c8a355bd4.png)

![screenshot-2022-04-23_08-36-41](https://user-images.githubusercontent.com/52637974/164910476-df561e17-ee38-49f2-836f-7ff831cc661d.png)

![screenshot-2022-04-23_08-37-00](https://user-images.githubusercontent.com/52637974/164910480-6a41846a-d772-451c-9092-1adf0e8cbfd2.png)

![screenshot-2022-04-23_08-37-10](https://user-images.githubusercontent.com/52637974/164910483-8b4a65aa-b666-4b88-ae4e-ccf42cf8b95d.png)

![screenshot-2022-04-23_08-37-20](https://user-images.githubusercontent.com/52637974/164910487-8656784d-0be0-46d2-b71a-ffac21e901b2.png)

![screenshot-2022-04-23_08-37-29](https://user-images.githubusercontent.com/52637974/164910490-d782b589-2253-42e4-8870-65630928e4b2.png)

![screenshot-2022-04-23_08-37-42](https://user-images.githubusercontent.com/52637974/164910493-5fb8ffbe-bb2d-47b4-8801-8af9bab3af47.png)

**Comment by george-thomas-hill** [comment]
The following are existing issues that are likely related:

https://github.com/electron/electron/issues/33094

https://github.com/electron/electron/issues/28407

https://github.com/electron/electron/issues/32915

https://github.com/electron/electron/issues/33519

And here are related pull requests:

https://github.com/electron/electron/pull/33560

https://github.com/electron/electron/pull/33664

**Comment by vladimiry** [comment]
Also referencing #27121 (this hits me).

**Comment by strukteon** [comment]
Is this still not fixed?

**Comment by george-thomas-hill** [comment]
Update:

I'm still finding (in Electron 21.2.0) that loading a PDF in an iFrame fails to display the PDF, and loading a PDF in a webview crashes Electron.

Here's an Electron Fiddle gist that demonstrates this:

https://gist.github.com/george-thomas-hill/c3179e6eddeb1a2715201a20dbf95015

**Comment by george-thomas-hill** [comment]
Bump.

I'm still finding (in Electron 22.0.2) that loading a PDF in an iFrame fails to display the PDF, and loading a PDF in a webview crashes Electron.

Here's an Electron Fiddle gist that demonstrates this:

https://gist.github.com/george-thomas-hill/c3179e6eddeb1a2715201a20dbf95015

![screenshot-2023-01-21_07-27-38](https://user-images.githubusercontent.com/52637974/213866833-8467efab-a162-4e3b-ad08-a6d4aa32cf96.png)

![screenshot-2023-01-21_07-29-58](https://user-images.githubusercontent.com/52637974/213866890-3e6d64d8-8ce1-4aea-84c0-be61ee0cbb89.png)

**Comment by george-thomas-hill** [comment]
Update:

I'm still finding (in Electron 24.0.0) that loading a PDF in an iFrame fails to display the PDF, and loading a PDF in a webview crashes Electron.

Here's an Electron Fiddle gist that demonstrates this:

https://gist.github.com/george-thomas-hill/c3179e6eddeb1a2715201a20dbf95015

**Comment by thomasdao** [comment]
@george-thomas-hill I have the same issue with embedding PDF file from custom protocol. To work around this issue, I need to register the custom protocol as privileged and set `standard` to true, and the PDF file can be loaded successfully.

```js
protocol.registerSchemesAsPrivileged([{scheme: 'customprotocol', privileges: {standard: true}}])
```

**Comment by george-thomas-hill** [comment]
@thomasdao Thank you for the tip! That worked for me!

**Comment by dhanson358** [comment]
Any idea if there is a way to make that fix also work for normal embedded PDFs?  In this case I am loading one via https, so it's not a custom local protocol.

**Comment by thomasdao** [comment]
I believe <object> can load PDF from `https` protocol normally.

**Comment by thomasdao** [comment]
@dhanson358 I believe PDF file can be embedded from `https` normally.

**Comment by dhanson358** [comment]
@thomasdao  I get the same behavior (grayed out box) when trying to access PDFs over https via a normal web application.

**Comment by george-thomas-hill** [comment]
@thomasdao Thank you for the tip that you gave a few weeks back.

It worked for me for a while.

However, right now, I find that I can use a webview and a custom protocol to display a PDF only in development mode.

When I build my app (using electron-builder) and go to display the PDF, I get a grayed-out box.

Are you having the same problem?

Or can anyone on this chain suggest a way to display PDFs in production mode?

I would be so very grateful for help with this problem.

@codebytere @nornagon @MarshallOfSound Please forgive me for name-dropping the three of you, but I see that you are frequent contributors to Electron, and I'm hoping that one of you can help address this problem.

I have tried many variations of the following code:

```
                    <webview
                        webpreferences={
                            "sandbox=yes, " +
                            "javascript=no, " +
                            "plugins=true"
                        }
                        src={useSrc}
                        ref={itemRef}
                        className="ff-fileViewer-itself"
                        plugins={"true"}
                    >
                    </webview>
```

That code works in development mode to display a PDF, but in my packaged app I get a gray box.

The only possible clue that I have is that, when it does work, I get the following warning in my console:

```
Warning: disabling flag --expose_wasm due to conflicting flags
```

However, that warning does not appear when I run my packaged app and try to display a PDF.

Thank you, everyone, for your time.

**Comment by vladimiry** [comment]
> https://gist.github.com/george-thomas-hill/e46f4b875b091c8c9b42df29a8cd1805

There is no webview nor custom protocol in this gist, so the original issue is still there.

**Comment by sascha-schieferdecker** [comment]
This bug still exists, can confirm it works in development mode if PDF ist served by HTTP via vite. If I package the app using a custom protocol the PDF is not displayed. CSP bypass does not help either.
