### ISSUE TITLE
[Bug]: `setJumpList` declares `void` return type but should be `string`?

### ISSUE THREAD

**Issue by bpasero** [electron/electron#33909]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.x

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

The docs of https://github.com/electron/electron/blob/17-x-y/docs/api/app.md#appsetjumplistcategories-windows say:

> Sets or removes a custom Jump List for the application, and returns one of the following strings...

However in the `electron.d.ts`, the return type is `void`:

```ts
setJumpList(categories: (JumpListCategory[]) | (null)): void;
```

The expected signature is:

```ts
setJumpList(categories: (JumpListCategory[]) | (null)): 'ok' | 'error' | 'invalidSeparatorError' | 'fileTypeRegistrationError' | 'customCategoryAccessDeniedError';
```

### Actual Behavior

The `void` type is the wrong return type.

**Comment by RaisinTen** [comment]
Sent a fix - https://github.com/electron/electron/pull/33910!
