### ISSUE TITLE
[Bug]: Navigator.languages contains the wrong items and in the wrong order

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#33916]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

macOS

### Operating System Version

Monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

`navigator.languages` should provide an array of languages ordered by preference that's reflective of the languages set at the OS level.

### Actual Behavior

I don't have a repro, but a user of my app has the following settings:

<img width="663" alt="unknown (1)" src="https://user-images.githubusercontent.com/1812093/165143825-a22c39b8-7ef9-4ecd-8be4-feb202b6ad95.png">

They are getting the following value for `navigator.languages` from the app's devtools window:

```js
['en-US', 'en-GB']
```

And they are getting the following value inside Chrome:

```js
['en-GB', 'en-US', 'en']
```

So Electron is both returning something that's different than what Chrome is returning, which I find strange, but also "en-US" is improperly in the first position for some reason.

### Additional Information

This bug was most probably present in older versions of macOS and older versions of Electron too.

---

Edit: this bug was also present on the Intel version of macOS.

**Comment by jkleinsc** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug by checking your test against different OSes and Electron versions.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

**Comment by fabiospampinato** [comment]
It's impossible to make a self contained repro because this issue seems OS dependend, morover I can't reproduce the issue on my machine so whatever I make (retrieving navigator.languages? To do what?) would probably be pointless.

**Comment by fabiospampinato** [comment]
Still an issue to the best of my knowledge.

**Comment by fabiospampinato** [comment]
Still a problem
