### ISSUE TITLE
[Bug]:  getAllDisplays() only return one Display when laptop connected to an external display (in mirror mode).

### ISSUE THREAD

**Issue by Topppy** [electron/electron#33911]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.1.8

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

getAllDisplays() return array which contains two different Displays.

### Actual Behavior

getAllDisplays() return  only  one Display which is the laptop screen.

**Comment by Topppy** [comment]
In Mirror Mode  it seems like that the computer monitor duplicates the monitor on the laptop display.

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
