### ISSUE TITLE
[Bug]: Electron 14.x 15.x official sample throw error  `Passthrough is not supported, GL is disabled` in Windows 10

### ISSUE THREAD

**Issue by leiming** [electron/electron#33917]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

14, 15

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Last Known Working Electron version

18.0.0

### Expected Behavior

It works and has no errors.

### Actual Behavior

It throw error as below:

```bash
$ yarn start
yarn run v1.22.18
$ electron main.js

(node:13640) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `electron --trace-warnings ...` to show where the warning was created)
[7776:0426/021213.441:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[10868:0426/021411.430:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
```

### Additional Information

I push all code to this repo:

https://github.com/leiming/electron-GL-is-disabled

**Comment by leiming** [comment]
It is similar to https://github.com/electron/electron/issues/32317 https://github.com/electron/electron/issues/33080
But it does not appear at the end of the error `, ANGLE is`, just end of `GL is disabled`

**Comment by leiming** [comment]
This error overrides versions 14 to 18. Running Electron throw the error after  **1 or 2 minutes** . 
```
[1328:0426/115338.859:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled
```

This error overrides versions 14 to 15. Running Electron  throw error **immediately**.
```
[7776:0426/021213.441:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

**Comment by datdinhquoc** [comment]
What's the status of the issue at Electron 18 (current)? I can see when GL is disabled, the rendering is done through CPU and it is laggy.

**Comment by miniak** [comment]
Electron 15 is not supported anymore
