### ISSUE TITLE
[Bug]: Electron with gRPC shows 'Could not find Module 'grpc''

### ISSUE THREAD

**Issue by Sneha-Madhu** [electron/electron#33923]
# Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.4.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise @2019

### What arch are you using?

x64

### Expected Behavior

The project uses the grpc with electron and angular. While launching the application exe (packaged using electron-packager), the application should be loaded without any javascript error.

### Actual Behavior

The project works with Angular, Electron and gRPC. The pacakging has been done using 'electron-packager'. As the project uses the grpc, 'electron-rebuild' command has been run to support electron with grpc.

The flow how it works is, the angular sends the request to ipcrenderer to make a call with grpc (service.ts)

```
callgRPCMethod(type?, payload = {}, authData?) {
    if (this.electronService.isElectronApp) {
      const globalSendEventName = 'GRPCrequestEvent';

      const eventData = { eventName: type };
      if (
        this.electronService.ipcRenderer &&
        this.electronService.ipcRenderer.send
      )
        this.electronService.ipcRenderer.send(
          globalSendEventName,
          eventData,
          payload,
          { hasToken: authData? authData.hasToken : '', token: authData ? authData.token : '' }
        );
    }
  }
```
This has been received in Electron ipcMain and call the grpc call using that as shown below. (main.js)
```
ipcMain.on(
    "GRPCrequestEvent",
    (event, eventData, requestPayload = {}, authorization = null) => {
      switch (eventData.eventName) {
        case "getAllLoginNames":
          UserService.getAllLoginNames(mainWindow);
          break;
          }
       });

```
The grpc service which receives this request and place the grpc call using below code,

assets/grpcservices/user.service.js

```
var { userAccessClient } = require("./client.service");
var google_protobuf_empty_pb = require("google-protobuf/google/protobuf/empty_pb.js");
const grpc = require("grpc");

function getAllLoginNames(mainWindow) {
  userAccessClient.getAllLoginNames(
    new google_protobuf_empty_pb.Empty(),
    (error, response) => {
      sendResponse(
        "getAllLoginNamesresponse",
        error,
        response ? response.toObject() : null,
        mainWindow
      );
    }
  );
}

function sendResponse(responseName, error, response, mainWindow) {
  try {
    // const data = JSON.stringify(response)
    mainWindow.webContents.send(responseName, {
      data: response,
      error: error,
    });
  } catch (e) {
    mainWindow.webContents.send(responseName, {
      data: null,
      error: e,
    });
  }
}
module.exports = {
  getAllLoginNames: getAllLoginNames,
};
```

assets/grpcservices/client.service.js

```
const grpc = require("grpc");
const { UserACcessClient } = require("../proto/UserAccess_grpc_pb");
const path = require("path");
const fs = require("fs");
let cert = fs.readFileSync(path.resolve(__dirname, "../cert/clientCert.cer"));

let config = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, "../config/config.json"))
);

var grpcClient = grpc.credentials.createSsl(cert);
var userAccessClient = new UserACcessClient(
  config.apiServer.grpcUrl,
  grpcClient,
  {
    "grpc.max_receive_message_length":
      config.maxProtoLength * config.maxProtoLength * 100,
    "grpc.max_send_message_length":
      config.maxProtoLength * config.maxProtoLength * 100,
  }
);
```
assets/config/config.json
```
{
  "apiServer": {
    "grpcUrl": "localhost:8000",
  },
  "infoLoggingEnabled": true,
  "firstIdleTimeOut": 60000,
  "errorLoggingEnabled": true,
  "idleTimeOut": 30000,
  "debugLoggingEnabled": true,
  "maxProtoLength": 1024
}
```

When launching the application using the command 'electron .', the application launches without any issue. The project has been packaged using the below command

```
const { spawn } = require('child_process');
const ls = spawn(
`electron-packager . --platform=win32 --arch=x64 --win32metadata.requested-execution-level=requireAdministrator --overwrite ${process.argv[3]} --ignore=^/src --ignore=^/tests --ignore=^/coverage --ignore=^/e2e --ignore=^/.angular --ignore=^/projects --icon=./icon.ico --appVersion=${process.argv[4]}`,
 { shell: true },
)
```
As a result, we are getting the below issue

<img width="576" alt="ModuleNotFound" src="https://user-images.githubusercontent.com/104413647/165283638-08bfc5e7-6a46-4fd4-9530-ee1133e55132.png">

**Comment by miniak** [comment]
Electron 11 is not supported

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.

**Comment by Sneha-Madhu** [comment]
> Thank you for reaching out!
> 
> The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.
> 
> If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.
> 
> Thanks in advance! Your help is appreciated.

Thank you @jkleinsc for addressing.
