### ISSUE TITLE
[Bug]: Cannot fully control dock menu on macOS

### ISSUE THREAD

**Issue by bpasero** [electron/electron#33939]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.x

### What operating system are you using?

macOS

### Operating System Version

12.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Calling `app.dock.setMenu` I can fully control all entries of the menu.

### Actual Behavior

Some entries are filled in automatically such as "Quit", "Hide", "Show All Windows":

![image](https://user-images.githubusercontent.com/900690/165446409-2b2af17f-212f-4f14-a5dc-8cb6f383efc7.png)

### Additional Information

The application menu behaves differently in that it allows me to fully set all entries.

**Comment by MarshallOfSound** [comment]
@bpasero This menu item is placed there by the OS and is not removable afaik.  There are multiple other ways to trigger a quit on macOS through uncontrollable means.  The correct way for an app to do what vscode wants to do is to handle the `before-quit` event.

https://www.electronjs.org/docs/latest/api/app#event-before-quit

Calling `event.preventDefault()` will stop the quit and then you can do your apps "are you sure" flow.  Be sure you don't prevent your own quits though 👍
