### ISSUE TITLE
[Bug]: css user-select: text mess up webContents.findInPage behavior

### ISSUE THREAD

**Issue by jordan-breton** [electron/electron#33960]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

Linux ubuntu 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

The search bar should allow you to navigate through matches in the page, backward and forward, by clicking on the buttons in the demo project linked to this report, regardless of the css rules applied to the HTML document.

### Actual Behavior

By adding the following css rule :

```css 
*{
    user-select : text;
}
```

The `findInPage` feature's behaviour is heavily impacted:

- When clicking on the `next` button, most of the time `findInPage` will return a result that selects only the first match with `activeMatchOrdinal` always equal to `1`. If you try to click the button several times, your action will just be ignored.
- When clicking on the `prev` button, most of the time `findInPage` will return a result that selects only the last match with `activeMatchOrdinal` always equal to the last match. If you try to click the button several times, your action will just be ignored.

### Testcase Gist URL

https://github.com/AriartWt/electron-pageInView-user-select

**Comment by AriartWt** [comment]
A second bug, maybe linked to this one : 

In my test repo, comment the css rule `user-select: text` and  change one of the `button` tag by a `span`, `div` or any tag you like and the bug will be triggered when clicking on the "not button" tag, while the remaining `button` will still work as intended.
