### ISSUE TITLE
[Bug]: desktopCapturer not working in Ubuntu 22 LTS and Fedora 34

### ISSUE THREAD

**Issue by SarathKmrM** [electron/electron#33961]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22

### What arch are you using?

x64

### Expected Behavior

Get screenshot of screen.

### Actual Behavior

Getting a popup and screenshot image generated is empty and not working (0 kb)

### Additional Information

```
desktopCapturer.getSources({ types: ['screen'] }).then( sources => {
  fs.writeFile(`screenshot.jpg`, sources[0].thumbnail.toJPEG(25), (err) => {
    if (err) throw err
      console.log('Image Saved')
  })
})
```
The above code was tested and working in ubuntu 18 and 20.
But its not working in Ubuntu 22 LTS and Fedora 34.

`app.commandLine.appendSwitch('enable-features', 'WebRTCPipeWireCapturer');`
I have also enable WebRTCPipeWireCapturer at runtime in main.js

![fedora](https://user-images.githubusercontent.com/95172957/165689187-568ef108-30d1-48b1-ba88-cd75117a2a95.png)
![ubuntu](https://user-images.githubusercontent.com/95172957/165689202-67903ea5-edca-4b50-af65-8b62776ed83e.png)

I am getting the above popup in both OS. The popup appears every time when taking screenshot. Even after clicking share button getting same issue. 

Thank you in advance.

**Comment by miniak** [comment]
@SarathKmrM can you please test with all supported Electron versions (15, 16, 17, 18) + 19 beta using Fiddle?

**Comment by ckerr** [comment]
Not sure what the issue is, but FWIW I think that popup is coming from xdg-desktop-portal-gnome:

https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/blob/main/src/screencastwidget.c#L542

**Comment by ckerr** [comment]
@SarathKmrM could you link a gist with a testcase in it, e.g. from Electron Fiddle or a modified version of electron-quick-start that maintainers can test with, instead of just a code snippet?

**Comment by SarathKmrM** [comment]
Hi.
I have added entire code in below repository

[https://gitlab.com/seantaylor/electron-17-desktopcapturer-not-working](https://gitlab.com/seantaylor/electron-17-desktopcapturer-not-working)

Please check the readme file for setup Instructions and running the application.
I have tested the app in electron 17. Screenshot image generated is empty and not working (size is 0 kb).

Thank you

**Comment by SarathKmrM** [comment]
> https://gitlab.com/seantaylor/electron-17-desktopcapturer-not-working

hi @ckerr 
I have added modified version of electron-quick-start. Please check the readme file for setup Instructions and running the application.
[https://gitlab.com/seantaylor/electron-17-desktopcapturer-not-working](https://gitlab.com/seantaylor/electron-17-desktopcapturer-not-working)

Thank you

**Comment by deermichel** [comment]
We are also hitting this at Skype with E18.0.3 on Wayland Ubuntu (22.04). But I can also repro black screen with vanilla Chrome - there is this `WebRTC PipeWire support` flag that seems to serve as a workaround.

**Comment by SarathKmrM** [comment]
We have updated electron App to latest stable version 18.2.0
We are still facing issues. Any solutions ?

**Comment by RaisinTen** [comment]
> We are also hitting this at Skype with E18.0.3 on Wayland Ubuntu (22.04).

@deermichel is this wayland specific or did you get a chance to test this on x11 too?

**Comment by deermichel** [comment]
@RaisinTen afaik it's wayland specific; we use the following line to make it work:
```js
app.commandLine.appendSwitch('enable-features', 'WebRTCPipeWireCapturer');
```
