### ISSUE TITLE
[Bug]: After invoke "navigator.mediaDevices.getUserMedia()" ,  "SetWindowsHookEx()" may not take effect in Windows 

### ISSUE THREAD

**Issue by zhangkari** [electron/electron#33976]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

I develop an electron SDK (build as sdk.node) , 
using Napi (C++) to hook keyboard message for windows .
invoke like this in javascript

`require('sdk.node').SetHook()`

to hook keyboad message.

Everything goes well .

However,  after I invoke 

`navigator.mediaDevices.getUserMedia() `

in javascript, hook seems goes wrong.

### Actual Behavior

After invoke 

`navigator.mediaDevices.getUserMedia() `,

it runs  and looks all OK, 
but can not hook windows keyboard message any more.

### Testcase Gist URL

https://gist.github.com/zhangkari/2fd02813f7beb38e4b2fac0be89a936a

### Additional Information

When invoke ::SetWindowsHookEx() in a new remote process,  it's OK.

**Comment by miniak** [comment]
@zhangkari please add a title

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by miniak** [comment]
@zhangkari please use a proper title for your issue

**Comment by miniak** [comment]
@zhangkari are you loading your node module into the main or renderer process?

**Comment by ckerr** [comment]
This gist is just a code snippet; it's not runnable for a maintainer to run & use as a testcase to reproduce the problem. @zhangkari in addition to the suggestion above about titling the issue, please provide a runnable testcase

**Comment by zhangkari** [comment]
> @zhangkari are you loading your node module into the main or renderer process?

yes, load node module into main process.

**Comment by zhangkari** [comment]
> This gist is just a code snippet; it's not runnable for a maintainer to run & use as a testcase to reproduce the problem. @zhangkari in addition to the suggestion above about titling the issue, please provide a runnable testcase

I'm sorry,  it's hard to provide a runnable testcase.  
maybe  the implementation of "navigator.mediaDevices.getUserMedia()"  has conflicts with windows hook

**Comment by githubvvcao** [comment]
@zhangkari 兄弟解决了吗？

**Comment by Gstar123456** [comment]
tor. 24. nov. 2022 kl. 14:03 skrev vvcao ***@***.***>:

> @zhangkari 兄弟解决了吗？
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>
-- 
Gstar

**Comment by zhangkari** [comment]
> @zhangkari 兄弟解决了吗？

换种方式解决了。

**Comment by darrenhp** [comment]
> > @zhangkari 兄弟解决了吗？
> 
> 换种方式解决了。

请问是怎么解决的？谢谢
