### ISSUE TITLE
[Bug]: Environmental variables are not decoded correctly

### ISSUE THREAD

**Issue by jonathon-love** [electron/electron#33997]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

Windows

### Operating System Version

sorry, this machine is chinese language ... but i think it's windows 10

### What arch are you using?

x64

### Expected Behavior

process.env in electron, appears to be populated with values which are taken from the system, and assumed to by utf-8 ... rather than decoding them appropriately. this is in contrast to node, which decodes them appropriately.

running:

```
console.log(process.env['USERPROFILE']);
```

node outputs:

```
C:\Users\杨测试
```

### Actual Behavior

same thing in electron outputs:

```
C:\Users\鏉ㄦ祴璇?
```

**Comment by jonathon-love** [comment]
in python i can go:

```
>>> 'C:\\Users\\杨测试'.encode('utf-8').decode('gbk', errors='replace')
'C:\\Users\\鏉ㄦ祴璇�'
```

suggesting that utf-8 data is being decoded as `gbk` (the chinese code page) when it should be decoded at utf-8.

**Comment by jonathon-love** [comment]
if i open a terminal on windows, and change the code page to utf-8 before starting electron, everything works

```
chcp 65001
```

**Comment by jonathon-love** [comment]
easy way to reproduce this is to start a cmd terminal, change the code page to chinese:

```
chcp 936
```

set an environmental variable:

```
set MOOSE=杨测试
```

start electron and examine the value of `process.env`.

we got caught out by this, because our electron application spawns additional processes, and all the windows temp dir APIs all make use of the `USERPROFILE`, etc. environmental variables to come up with temp paths, etc. so these corrupted env vars break any child processes that rely on temp files.

with thanks

**Comment by jonathon-love** [comment]
i can confirm this is still a problem in 21.0.1

**Comment by shun2wang** [comment]
I think it's still affecting...

**Comment by jonathon-love** [comment]
bump

**Comment by kiochan** [comment]
What terminal are you using?

**Comment by jonathon-love** [comment]
`cmd.exe`

**Comment by jonathon-love** [comment]
note that the terminal isn't necessary ... electron doesn't decode env variables irrespective of how it is run ... i just provided that cmd.exe example for ease of reproducing.

**Comment by Yueyanc** [comment]
same
