### ISSUE TITLE
Window cascading

### ISSUE THREAD

**Issue by Sidnicious** [electron/electron#3399]
Right now, if I create multiple windows with the same dimensions they end up exactly on top of each other. OS X, at least, can [automatically cascade windows](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWindowController_Class/index.html#//apple_ref/occ/instm/NSWindowController/setShouldCascadeWindows:). Would it make sense for Electron to expose a flag on BrowserWindow for something like this?

**Comment by sapioit** [comment]
You could try to make them pop up on different coordonates... or move them a bit, around...

**Comment by Sidnicious** [comment]
@sapioit Understood, that'd be an okay workaround, but I'd be nice to use the OS native answer instead.

**Comment by sapioit** [comment]
I know... but since nothing like this is provided as of now, aside this issue, oppening the second window 50 pixels to the right and to the bottom would be a fair suggestion, I think... oh, and if that is not part of 80% of the screen (too to the right or to the bottom), than move it all the way to the left top... or center...

**Comment by Sidnicious** [comment]
Sure, and those are the kinds of nasty edge cases that are already handled in the OS implementations.

**Comment by Sidnicious** [comment]
Just to be clear, I'm fine with doing this as a workaround for now, but I think it would be nicer for future Electron users to not have to.

**Comment by zcbenz** [comment]
I'm closing this since no one is paying attention to this issue, and it can be easily worked around.

**Comment by etiennepinchon** [comment]
Actually I have this exact same issue right now! This flag still does not exist :(
It would be one line of code that would improve a lot of apps..

**Comment by sapioit** [comment]
Hope is not lost...
