### ISSUE TITLE
[Bug]: Menu performance degrades from version 17

### ISSUE THREAD

**Issue by MrMYHuang** [electron/electron#33996]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17

### What operating system are you using?

Ubuntu

### Operating System Version

Linux ubuntu 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 12:56:31 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

16

### Expected Behavior

The menu performance of Electron >= 17 should be the same as Electron <= 16.

### Actual Behavior

My demo environment is Ubuntu 22.04 arm64 on Parallels on MacBook Air 2020 M1.
The desktop environment is Lubuntu / LXQt. Gnome Shell has no this issue. This issue starts from Electron 17. Electron 18 has the same issue. This issue is also reproducible on x86_64.

Watch this demo video:
https://drive.google.com/file/d/17hHVfEGNbhTdCr1bpM386l5YKBz6umqX/view?usp=sharing
In this video, I first used Electron 16. When I clicked a menu and move the mouse cursor between menus, the menus showed immediately. However, later, I used Electron 17, the menus often showed blank UIs at first. After a while, the menus become normal, but the menu UI response is still slower than Electron 16.

This issue can be reproduced with electron/electron-quick-start:
```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
```
First, use Electron 16:
```
npm i electron@^16 -D && npm run start
```
Then, use Electron 17:

```
npm i electron@^17 -D && npm run start
```

**Comment by ckerr** [comment]
I've confirmed your findings that this isn't happening on 22.04 with GNOME shell.

Since this is relatively easy for you to repro on an electron version via `npm i electron@^` would it be possible for you to try & narrow down when this regression was introduced? E.g. is it present in `17.0.0-alpha1` and/or `v17.0.0-beta.1`?

If it's _not_ in alpha1, it might be relatively easy for you to bisect through alpha / beta / stable 17 releases, e.g. see https://www.electronjs.org/releases/alpha?version=17

**Comment by MrMYHuang** [comment]
> would it be possible for you to try & narrow down when this regression was introduced?

By my tests, the first version having the blank menu issue is ***17.0.0-alpha.4***. The version 17.0.0-alpha.3 has no such issue.

**Comment by ckerr** [comment]
https://github.com/electron/electron/compare/v17.0.0-alpha.3...v17.0.0-alpha.4

**Comment by MrMYHuang** [comment]
More my tests show:
1. electron@18.2.3 still has the blank menu and slow menu switching problems.
2. electron@19.0.0-alpha.1 has the slow menu switching problem but no blank menu problem.
3. electron@19.0.0-alpha.4 has no the blank menu and slow menu switching problems!
