### ISSUE TITLE
[Bug]: Application menu does not appear on linux manjaro

### ISSUE THREAD

**Issue by ionutionoi** [electron/electron#33995]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux 5.15.32-1-MANJARO, KDE Plasma  5.24.4

### What arch are you using?

x64

### Expected Behavior

Application menu appears and fuctions properly.

### Actual Behavior

On Linux the application menu does not appear however the accelerators do work as expected.

### Additional Information

I have ran both my application and the [quick start app](https://github.com/electron/electron-quick-start) on windows 10 and linux. On windows everythig works as expected and on linux the application menu does not appear. 

It is possible it might be hidden by the OS due to some setting. The reason behind it is becuase when I installed webstorm one of it's experimental features, which forces the app to use the native menu was enabled, however KDE plasma does not have or use one which left me without the file, edit menus. 
I am aware that the electron has nothing to do with webstorm but maybe this bit of context might be helpful.

I tried searching for a solution but could not find any, I do not think this is specific to electron 18 because I tried it on other versions going back to 12 with the same result.

I have tried to use the example from the [documentation](https://www.electronjs.org/docs/latest/api/menu/#examples) and got the same result.

This is the template I am using:
```javascript
[
    {
      label: 'File',
      submenu: [
        {
          label: 'Quit',
          accelerator: 'CmdOrCtrl+Q',
          click() {
            app.quit();
          }
        }
      ]
    },
    {
      label: 'Developer Tools',
      submenu: [
        {
          label: 'Toggle DevTools',
          accelerator: 'CmdOrCtrl+Shift+D',
          click(item, focusedWindow) {
            focusedWindow.toggleDevTools();
          }
        },
        {
          label: 'Toggle Active WebView DevTools',
          accelerator: 'CmdOrCtrl+D',
          click() {
            mainWindow.webContents.openDevTools();
            mainWindow.webContents.send('open-active-webview-devtools');
          }
        },
        {
          label: 'Reload Active WebView',
          accelerator: 'CmdOrCtrl+R',
          click() {
            mainWindow.webContents.send('reload-active-webview');
          }
        },
        {
          role: 'reload',
          accelerator: 'CmdOrCtrl+Shift+R'
        }
      ]
    }
  ]
```

**Comment by ckerr** [comment]
Hey @ionutionoi, I'd like to install Manjaro on a VM to testdrive this. Which version of Manjaro are you using?

It looks like versions 21.2.0, 21.2.1, and 21.2.2 all have Linux kernel 5.15 so from your bug report info I'm not sure which one to choose

**Comment by ionutionoi** [comment]
Hi @ckerr, thanks for answering, based on the contents of `/etc/lsb-release`  it seems to be `21.2.6`.
Full contents: 
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.6
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
```

**Comment by ionutionoi** [comment]
After some time messing with some plasma settings it turns out manjaro does some interesting stuff with how it handles application menus and the conditions for them to show up. 
I was able to fix the problem by following the instructions from this [link](https://unix.stackexchange.com/questions/425168/kde-global-menu-disappeared-in-plasma-5-12) and disabling the application menu daemon which immediately restored the application menu bar.
