### ISSUE TITLE
Auto update on next restart

### ISSUE THREAD

**Issue by abhijitkane** [electron/electron#3404]
Is there any way to have a downloaded update apply automatically on the next restart of the app? 

Ideal situation: The 'update-downloaded' event shows a "An update has been downloaded" message in the UI, and the update automatically applies on the next restart without having to call `quitAndUpdate` explicitly.

Right now, the user has to restart the app manually to apply the update.

**Comment by raleksandar** [comment]
Haven't used auto-updater yet but can't you just store somewhere information that new update is available (when you receive `update-downloaded` event), query that information when app is starting and call `quitAndUpdate` before showing any windows in case that flag is set?

**Comment by etiktin** [comment]
@abhijitkane listen to the `update-downloaded` event. When it's fired show the message you want (e.g. using the `dialog` module) and call `quitAndInstall`. This will wait until all your app windows are closed and install the update. So on the next app restart, the updated version will be used.

**Comment by zcbenz** [comment]
After the update is downloaded you don't have to call `quitAndUpdate` to install the update, it is already installed and you only need to restart the app.

**Comment by Kunze** [comment]
https://github.com/electron/electron/blob/master/docs/api/auto-updater.md#autoupdaterquitandinstall

autoUpdater.quitAndInstall()

Restarts the app and installs the update after it has been downloaded. It should only be called after update-downloaded has been emitted.

Should I call quitAndInstall or not? I'm trying to restart my app after updated but both ways have not worked.
