### ISSUE TITLE
[Bug]: libgdk-pixbuf library is not dynamically linked

### ISSUE THREAD

**Issue by rzhao271** [electron/electron#34060]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.x.y

### What operating system are you using?

Ubuntu

### Operating System Version

Xubuntu 20.04, Ubuntu 16.04

### What arch are you using?

x64

### Expected Behavior

While porting over Chromium's script to generate dependencies for Debian packages in VS Code (https://github.com/microsoft/vscode/issues/13089), I noticed that libgdk-pixbuf is statically linked rather than dynamically linked. An issue is that the exact name of the library changed over time, so sometimes it is libgdk-pixbuf-2.0-0, and other times it is libgdk-pixbuf2.0-0. Therefore, Electron should look up the library at runtime.

### Actual Behavior

Using the Electron sysroot when searching for Debian dependencies, it seems libgdk-pixbuf-2.0-0 is statically linked: https://github.com/microsoft/vscode/pull/147335/files#diff-b84879f8920b8ee14b70af14c40c90a255472a38795104384f64db32f1c7505dR56

I verified in a separate CI run that the dependency is indeed contributed by Electron, and not by other shared libraries that VS Code uses.

### Additional Information

Since libgdk is responsible for rendering menus and file dialogs, I think we should log a message and crash the program if the dependency cannot be found during runtime.

CC @deepak1556

**Comment by deepak1556** [comment]
To add some context,  chromium removed the static dependency on the `libgdk-pixbuf` package as part of https://chromium-review.googlesource.com/c/chromium/src/+/2645039. During the `//ui/gtk` refactor in upstream, in one of the chromium rolls I had copied over a utility function that was removed https://github.com/electron/electron/pull/20649/commits/be693fa66c719720bce5e2359fa7253d224090f2 and today's static dependency on the library comes from this `GdkPixbufFromSkBitmap` utility. We can make the library dynamic similar to upstream.

> Since libgdk is responsible for rendering menus and file dialogs, I think we should log a message and crash the program if the dependency cannot be found during runtime.

GTK library depends on `libgdk-pixbuf` and Electron depends on GTK, so there will not be a case where the dependency is not found.
