### ISSUE TITLE
[Bug]: Socket.IO and Electron : why bidirectional communication websocket don't work in my app?

### ISSUE THREAD

**Issue by EnzoZuniga** [electron/electron#34070]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS 11.4 Big Sur

### What arch are you using?

x64

### Expected Behavior

I'm using express and electron with socket.io I should have a bidirectional communicationwith websocket protocol (101) between my client (in React) and my serve part.

### Actual Behavior

It render me http protocol with GET and POST request (200).

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electronjs) a try.

I hope this helps!
