### ISSUE TITLE
[Feature Request]: Export as PDF

### ISSUE THREAD

**Issue by rejoyc-cs** [electron/electron#34086]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If I write in 10 pages on the board and want to download all the pages as a single pdf file I don't have any option. I have to export one page as an image at a time. Then I have to make pdf file with all the images using sperate app. Its so much time consuming.

### Proposed Solution

Please add a feature/option which will download one single pdf which contains all the pages of the board.

### Alternatives Considered

I can't give any other alternatives as this is a very basic feature issue.

### Additional Information

Kindly add this.

**Comment by MarshallOfSound** [comment]
This doesn't appear to be an issue for Electron
