### ISSUE TITLE
[Bug]: offscreen rendering crash with --disable-gpu

### ISSUE THREAD

**Issue by gtalusan** [electron/electron#34094]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu Jammy

### What arch are you using?

x64

### Expected Behavior

Sending a click event to the INPUT SELECT should not crash Electron

### Actual Behavior

Randomly, a click event sent an INPUT SELECT will crash electron with --disable-gpu.

### Testcase Gist URL

https://gist.github.com/gtalusan/c0ad56685aeb3b2c1108fbccf6b451b4

### Additional Information

This is part of https://github.com/electron/electron/issues/34047 which is really 3 bugs, and #34047 was closed, so I'll break these out.

The last comment https://github.com/electron/electron/issues/34047#issuecomment-1118031883 provides a stack trace with the same gist.

**Comment by gtalusan** [comment]
bump

**Comment by codebytere** [comment]
Fixed as of v19.
