### ISSUE TITLE
[Bug]: Web Serial API `removed` and `added` events are never called 

### ISSUE THREAD

**Issue by BarakChamo** [electron/electron#34103]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.0

### What operating system are you using?

Windows

### Operating System Version

Win 11

### What arch are you using?

x64

### Expected Behavior

Device Access for Web Serial events should fire correctly as documented and shown in examples. 

After calling `requestPort({})` and handling the permissions event `select-serial-port`

`serial-port-added` and `serial-port-removed` should be called when a device is then plugged out and re-plugged in.

This is documented in the official example here:
https://www.electronjs.org/docs/latest/tutorial/devices#example-2

### Actual Behavior

Even after a succesful initialization of Serial related API, with a call to `requestPort({})` and a matched device,  `serial-port-added` and `serial-port-removed` are never fired.

### Additional Information

Here is a snippet from my code:

`main.ts`
```typescript
	webContents.session.on(
		'select-serial-port',
		(event, portList, webContents, callback) => {
			console.log(portList)
			event.preventDefault()
			if (portList && portList.length > 0) {
				callback(portList[0].portId)
			} else {
				callback('') //Could not find any matching devices
			}
		},
	)

	webContents.session.on('serial-port-added', (event, port) => {
		console.log('serial-port-added', port)
	})

	webContents.session.on('serial-port-removed', (event, port) => {
		console.log('serial-port-removed', port)
	})

	webContents.session.setPermissionCheckHandler(
		(_webContents, permission, _requestingOrigin, _details) =>
			permission === 'serial',
	)

	webContents.session.setDevicePermissionHandler(
		details => details.deviceType === 'serial',
	)
```

`renderer.ts`
```typescript
const testUSB = async () => {
	const filters = [{ usbVendorId: USB_VID, usbProductId: USB_PID }]
	try {
		const port = await navigator.serial.requestPort({ filters })
		const portInfo = port.getInfo()
		console.log(port, portInfo)
	} catch (ex) {
		console.log(ex)
	}
}
```

After this code is called in the renderer, I get the device that is already connected. But following `added` and `removed` events are never called.

**Comment by codebytere** [comment]
cc @jkleinsc

**Comment by jkleinsc** [comment]
@BarakChamo the documentation isn't super clear as to the intention of these events.  They only fire _until_ the callback on from the `select-serial-port` is called.  The intention is that if you are using some kind of UI to ask users to pick a port you could listen to these events and then update your UI to show the list of available ports.

These events are not intended as some kind of generic serial port listener.  The `connect` and `disconnect` events on navigator.serial as documented here: https://web.dev/serial/#connection-disconnection can be used for ports that have already been granted access via `navigator.serial.requestPort`

**Comment by BarakChamo** [comment]
@jkleinsc thanks for clarifying.

Perhaps you could help me understand if any of the available APIs could be used for a particular usecase?

I'm designing a USB device that is configured using an Electron app. The device has a unique VID/PID combo and I want to listen to any such device that is connected, being able to support one or many during a session.

I'm currently using the `usb-detection` library but was hoping to drop external dependencies. 

Is this possible with any available USB/Serial API?

**Comment by jkleinsc** [comment]
@BarakChamo I do not believe it is possible using the web APIs because there really isn't a construct in the specs to listen for activity outside of ports that have already been granted permission.

**Comment by BarakChamo** [comment]
@jkleinsc understood, thanks for your help!
