### ISSUE TITLE
[bug, linux] crash on start `undefined symbol: gtk_native_dialog_get_type`

### ISSUE THREAD

**Issue by deermichel** [electron/electron#34118]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0, nightly v20-20220418 and newer

### What operating system are you using?

Ubuntu

### Operating System Version

repro on 16.04, no repro on 22.04, other versions unknown

### What arch are you using?

x64

### Last Known Working Electron version

18.0.3, nightly v20-20220415 and older

### Expected Behavior

Electron starts.

### Actual Behavior

Electron crashes on startup:
<img width="1696" alt="image" src="https://user-images.githubusercontent.com/8472721/167078330-76bf7b1f-2ca2-4e1a-b244-c384948f7e0c.png">

### Testcase Gist URL

No fiddle needed, just try to run an affected version.

### Additional Information

Likely caused by #33650. Can we fix the fix 😆? Since this got backported, it affects 18, 19 and 20 now.

cc @deepak1556 @miniak

**Comment by RaisinTen** [comment]
Not able to reproduce the crash on Linux while running v18.1.0. 🤷 
Is anyone else also facing this problem? The PR you linked also has a green CI on linux - https://github.com/electron/electron/runs/5870898004.

**Comment by scottnonnenberg-signal** [comment]
Signal Desktop is on Electron 18 in production right now, and this issue is causing problems for folks on older Ubuntu versions.
