### ISSUE TITLE
[Bug]: electron 18.2.1 not available on npmjs.com

### ISSUE THREAD

**Issue by vraravam** [electron/electron#34130]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.1

### What operating system are you using?

macOS

### Operating System Version

macos monterey

### What arch are you using?

x64

### Last Known Working Electron version

18.2.0

### Expected Behavior

When I have an electron project that refers to 18.2.1 in the `package.json`, I expect it to get installed

### Actual Behavior

`npm i electron@18.2.1` errors out

**Comment by mceachen** [comment]
v18.2.2 is now available on npm.

**Comment by RaisinTen** [comment]
Why was this closed? v18.2.1 is still not available on npm.

**Comment by vraravam** [comment]
Yes - please reopen. The same issue is now happening for 18.2.4!
