### ISSUE TITLE
[Feature Request]: support "original file (buffer or string)" for preload

### ISSUE THREAD

**Issue by oxy-plus** [electron/electron#34131]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If I try to encrypt asar, I can't use preload at the same time. Or I must exclude preload from asar, but that would make encrypting asar meaningless.

### Proposed Solution

support some api like this:
```js
new BrowserWindow({
    webPreferences: {
      preloadFile: Buffer.from("...")
    }
  })
```

### Alternatives Considered

I think "Proposed Solution" is enough

**Comment by vladimiry** [comment]
I guess as a hacky workaround, you could patch the read-like functions of "fs" module and return a Buffer stuff for a specific file locations.

**Comment by oxy-plus** [comment]
> I guess as a hacky workaround, you could patch the read-like functions of "fs" module and return a Buffer stuff for a specific file locations.

But it seems that electron does not use fs to read preload script.
In the following example, the console will not output anything :
```js
const
  { app, BrowserWindow } = require("electron"),
  ofs = require("original-fs"),
  fs = require("fs")

function proxy(obj, name) {
  const old = {}
  Object.keys(obj).forEach((key) => {
    if (
      typeof obj[key] !== "function"
      || !Object.hasOwnProperty.call(obj, key)
      || key.includes("write")
    ) return
    // else
    old[key] = obj[key]
    obj[key] = function (...args) {
      console.log(name, key, args)
      return old[key](...args)
    }
  })
}
proxy(fs, "fs")
proxy(ofs, "ofs")

app.on("ready", function () {
  new BrowserWindow({
    webPreferences: {
      preload: "preload-path"
    }
  }).loadFile("html-path")
})
```
And I noticed that when the preload error occurs, the console outputs information from the ".cc" file.
like :
```
[18024:0508/045629.406:ERROR:web_contents_preferences.cc(261)] preload script must have absolute path.
```
I don't think I can modify this part of the code unless I recompile electron.

**Comment by vladimiry** [comment]
The guess was wrong then, thanks for the test.

**Comment by lowfront** [comment]
Isn't there a good way? I am trying to use ipcRender in the render process, but the electron cannot read the asar internal path as the preload path, so I have created preload.js in the actual path after the build...

**Comment by oxy-plus** [comment]
> Isn't there a good way? I am trying to use ipcRender in the render process, but the electron cannot read the asar internal path as the preload path, so I have created preload.js in the actual path after the build...

Electron can use preload in asar normally.
If you use `path.join( process.cwd(), "..." )` to get the preload path, maybe you just need change it to `path.join( app.getAppPath(), "..." )`.
like:
```js
new BrowserWindow({
  height: 720,
  width: 1280,
  webPreferences: {
    preload: path.join(app.getAppPath(), "project-root/..."),
  }
})
```

**Comment by lowfront** [comment]
I must have used the wrong path. It's working fine now.

**Comment by MarshallOfSound** [comment]
Per https://github.com/electron/electron/issues/14012#issuecomment-423831675 this isn't something we want to support
