### ISSUE TITLE
[Bug]: BrowserView: flickers when switching between view

### ISSUE THREAD

**Issue by poisonReact** [electron/electron#34169]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.2.3

### What arch are you using?

x64

### Last Known Working Electron version

13.1.7

### Expected Behavior

Switching browser view should not flickers.

### Actual Behavior

Switching browser view flickers.

### Testcase Gist URL

https://gist.github.com/poisonReact/83fd391a3b4d2ba86fe51530f145e722

### Additional Information

NOTE: tested in windows, the bug is not present.

The first part: the problem
The second part: expected behavior

https://user-images.githubusercontent.com/54484694/167803223-cb5125f5-143d-49e8-b66b-dce10663ffba.mp4

**Comment by poisonReact** [comment]
@codebytere i do some research an find that this part of the code causes such a bug
![Screenshot 2022-05-13 at 12 37 40](https://user-images.githubusercontent.com/54484694/168256745-c7316630-7071-4089-b4ca-0e0cefd903c6.png)
BaseWindow::ResetBrowserViews() in electron_api_base_window.cc

**Comment by poisonReact** [comment]
still reproduce on new version 20.0.3

**Comment by poisonReact** [comment]
bump

**Comment by Imperat** [comment]
bump

**Comment by lauri865** [comment]
bump

**Comment by SagaciousLittle** [comment]
bump
