### ISSUE TITLE
[Documentation]: Where is stdout redirected to in Linux? 

### ISSUE THREAD

**Issue by robinchrist** [electron/electron#34174]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

14.1.1

### What operating system are you using?

Ubuntu

### Operating System Version

21.10

### What arch are you using?

x64

### Expected Behavior

Documentation should state where `stdout` is redirected to or `stdout` should be redirected to the console as `stderr`

### Actual Behavior

On Linux, `stderr` of native addons is redirected to the console where Electron was launched, but `stdout` is nowhere to be found.

On Windows and MacOS, `stdout` is redirected to the console where Electron was launched if I remember correctly.

**Comment by beyond9thousand** [comment]
This is quite frustrating, in my case it seems as though electron is dumping everything to my .xsession-errors file but this keeps populating it nonstop since stdout as well as stderr is constantly dumped. Very frustrating

**Comment by beyond9thousand** [comment]
bump

**Comment by beyond9thousand** [comment]
bump
