### ISSUE TITLE
[Bug]: Can't get 2nd camera when 1st camera is using on macOS12

### ISSUE THREAD

**Issue by mmppeegg** [electron/electron#34196]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

We are using `navigator.mediaDevices.enumerateDevices()` and `mediaDeviceInfo.kind === 'videoinput'`
to get connecting camera and play its video.
When second camera is plugging in, the Electron app should detect it when 1st cam is already playing by the same app.

### Actual Behavior

When the first camera's video is playing, if another camera is plug in, the second camera will not appear even devices change event is happening.
Unless we stop the 1st cam's video then replug 2nd cam, the program will never find out the 2nd cam.

### Additional Information

Only occurs on macOS 12. Electron is working fine on macOS 11.

**Comment by mmppeegg** [comment]
Google Chrome and Microsoft Edge have the same problem.

**Comment by codebytere** [comment]
@mmppeegg then please should open a bug at crbug.com - we'll receive the fix when they address it given its not a problem in our own codebase :)

**Comment by hengshanMWC** [comment]
The same problem occurs with the electron v11.0.1. The mac m1 version is 12.1 and the node v16.15.0
