### ISSUE TITLE
[Bug]: Discord bot Client not loading and it's just grey

### ISSUE THREAD

**Issue by EntityDevil** [electron/electron#34197]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

ASUS VivoBook S14

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

idk

### Expected Behavior

idfk

### Actual Behavior

idk

### Testcase Gist URL

idk.com

### Additional Information

idk

**Comment by SufiyanGaming13** [comment]
same problem how i can fix this
