### ISSUE TITLE
[Bug]: second-instance event process arguments with double "https://url" arguments

### ISSUE THREAD

**Issue by shencaobo** [electron/electron#34195]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

14.0.1

### What operating system are you using?

Windows

### Operating System Version

window10

### What arch are you using?

x64

### Expected Behavior

app.on('second-instance', async (event, commandLine, workingDirectory, additionalData) => {
	 console.log(commandLine)
)}

When we now start the second instance with 3 arguments:

open in window10. cmd.     electron.exe "https://github.com/1" "https://github.com/2" "3"
second-instance  will show 

[
  "electron.exe",
  "--allow-file-access-from-files",
  "https://github.com/1",
  "https://github.com/2",
  "3"
]

### Actual Behavior

The method second-instance cannot get any parameters
no response
after a while throw error
[8044:0512/150433.412:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled

### Additional Information

looks like “:”  error caused by
If it does not contain:, there is no problem with the parameter
The url parameter must be passed in, is there any way to deal with it?

**Comment by shencaobo** [comment]
open in window10. cmd. electron.exe "1" "2" "https://github.com/2"
When the url parameter is the last one, there is no problem

[
"electron.exe",
"--allow-file-access-from-files",
"1",
"2",
"https://github.com/2"
]

But it doesn't work with two url parameters
open in window10. cmd. electron.exe "1" "https://github.com/1" "https://github.com/1"

**Comment by shencaobo** [comment]
![image](https://user-images.githubusercontent.com/18565963/168024993-8a0a3e21-3eb8-44c3-9ed2-4c63cbc467a5.png)

**Comment by MarshallOfSound** [comment]
Prefix your arguments with `--` and URI style arguments will be allowed.  This is the side effect of an old security precaution 👍 

E.g.

```
[
"electron.exe",
"--",
"--allow-file-access-from-files",
"https://github.com/1",
"https://github.com/2",
"3"
]
```

**Comment by shencaobo** [comment]
I have no way to change the parameters.  including add
Do I have any other way to solve this problem?
Is there a pre-configured
@MarshallOfSound
