### ISSUE TITLE
[Bug]: MacOS bug in app.addRecentDocuments()

### ISSUE THREAD

**Issue by robertpatrick** [electron/electron#34212]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.3

### What operating system are you using?

macOS

### Operating System Version

macOS Monterrey 12.3.1

### What arch are you using?

x64

### Expected Behavior

I expect the calls to `app.addRecentDocuments()` to work and the menu with the role `recentDocuments` to work properly.

### Actual Behavior

The issue only seems to occur after closing all windows and then clicking the icon on the taskbar to open a new window. 

When I open our File -> Open Recent menu (which is working fine in other situations) after saving our project, I see an empty menu item.  Clicking that menu items gives me an error saying that the file is null.

I added log messages around the call to addRecentDocuments:

```javascript
    getLogger().debug('confirmProjectFile adding %s to recent documents', projectFile);
    app.addRecentDocument(projectFile);
    getLogger().debug('confirmProjectFile added %s to recent documents', projectFile);
```

In the log output when saving the project that traverses this code, I see:

```
debug: confirmProjectFile adding /Users/rpatrick/Desktop/todo/Untitled2.wktproj to recent documents
debug: confirmProjectFile added /Users/rpatrick/Desktop/todo/Untitled2.wktproj to recent documents
```

Once the Save is complete, the Open Recent menu looks like this:

![Screen Shot 2022-05-12 at 5 23 29 PM](https://user-images.githubusercontent.com/31662131/168179161-a205ba62-849e-49e2-9375-e6a9dac82179.png)

If I click on that empty menu item, I get this:
![Screen Shot 2022-05-12 at 5 25 08 PM](https://user-images.githubusercontent.com/31662131/168179196-3750f0c3-82e7-4cbf-8875-b5e1fad5a136.png)

There are no other calls to app.addRecentDocuments being made and since the file name we are passing to the call is not null, I have to assume that this is an electron bug.

### Additional Information

The menu definition looks like this and is working fine except with this newly spawned window:

```javascript
      const fileMenu = appMenuTemplate.find(item => item.id === 'file');
      if (fileMenu) {
        const openProjectIndex = fileMenu.submenu.findIndex(item => item.id === 'openProject');
        if (openProjectIndex !== -1) {
          const openRecentMenuItem = {
            id: 'openRecent',
            label: i18n.t('menu-file-openRecent'),
            enabled: !this._hasOpenDialog,
            role: 'recentDocuments',
            submenu: [
              {
                label: i18n.t('menu-file-openRecent-clearRecent'),
                role: 'clearRecentDocuments'
              }
            ]
          };
          // Insert immediately after the Open Project menu item.
          fileMenu.submenu.splice(openProjectIndex + 1, 0, openRecentMenuItem);
        }
      }
```

I would normally build a test case but this only happens after closing all electron windows and then spawning a new window by clicking on the icon in the macOS taskbar.

By the  way, this same issue was in our earlier releases based on Electron 13.x, 14.x, and 16.x so unless we are doing something wrong, this feels like a long-standing Electron issue.

**Comment by codebytere** [comment]
@robertpatrick it'd still be really helpful here if you could provide a minimal Fiddle repro - without one i don't know what else you have in your app menu template or what other code might be affecting it.

>  this only happens after closing all electron windows and then spawning a new window by clicking on the icon in the macOS taskbar.

this i can of course do myself once i have a represenative repro :)

**Comment by robertpatrick** [comment]
@codebytere i will try.  In the meantime, our source is at https://github.com/Oracle/weblogic-toolkit-ui.  Look in `electron/app/js/wktWindow.js` for the relevant code that builds the menu.

**Comment by squidbork** [comment]
Hey @robertpatrick, after playing around with your code, I think there might be some race condition between saving a file and `addRecentDocument()`? I couldn't repro the issue anymore after making the following change in `chooseProjectFile()`
```
async function chooseProjectFile(targetWindow) {
  const projectFile = await _chooseProjectSaveFile(targetWindow);
  const projectName = projectFile ? _generateProjectName(projectFile) : null;
  const projectUuid = projectFile ? _generateProjectUuid() : null;

  const fileExists = await fsUtils.exists(projectFile);
  console.log(`File exists immediately? ${fileExists}`);

  setTimeout(async () => {
    const fileExists = await fsUtils.exists(projectFile);
    console.log(`File exists after 10ms? ${fileExists}`);
    app.addRecentDocument(projectFile);
  }, 10);
  return [projectFile, projectName, projectUuid];
}
```

**Comment by robertpatrick** [comment]
@squidbork I don't think this is a race condition.  Does `app.addRecentDocument()` require the file to exist at the time of the invocation?  If so, that would explain your workaround since the chooseProjectFile() method only asks the user for the new file name when doing Save As--it does not create the file.

**Comment by robertpatrick** [comment]
I restructured my code to make sure that it is only called after the file is created on disk and it is now working as expected.  Sorry for the noise but I feel like the `app.addRecentDocument()` docs should really have a note that the path passed must actually exist on disk at the time of the API call.

**Comment by squidbork** [comment]
> I restructured my code to make sure that it is only called after the file is created on disk and it is now working as expected. Sorry for the noise but I feel like the `app.addRecentDocument()` docs should really have a note that the path passed must actually exist on disk at the time of the API call.

Glad to hear that worked 👌
since I'm already poking around this code, I'll work on a PR to improve the docs for this, and maybe change the function to return false if the path is invalid/file doesnt exist
