### ISSUE TITLE
[Bug]: SIGSEGV on calling `getAvailableDictionaries()` of `spellchecker` npm module

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#34239]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0-nightly.20220512, 20.0.0-nightly.20220513

### What operating system are you using?

Other Linux

### Operating System Version

kernel 5.17.6

### What arch are you using?

x64

### Last Known Working Electron version

20.0.0-nightly.20220511

### Expected Behavior

The `spellchecker.getAvailableDictionaries()` call completes without SIGSEGV crash.

### Actual Behavior

SIGSEGV crash on `spellchecker.getAvailableDictionaries()` call.

### Additional Information

package.json
```json
{
  "devDependencies": {
    "electron-nightly": "20.0.0-nightly.20220512"
  },
  "dependencies": {
    "spellchecker": "https://github.com/vladimiry-playground/node-spellchecker#37cebc43ccbfce27dac51f64ec45f72d9aa80b8f"
  }
}

```

index.js
```javascript
//const { app, crashReporter } = require("electron")
//console.log("crashDumps:", app.getPath("crashDumps"))
//crashReporter.start({submitURL: "", uploadToServer: false})
const spellchecker = require("spellchecker")
console.log("getAvailableDictionaries():", spellchecker.getAvailableDictionaries())
```

- `cd ./node_modules/spellchecker/` and remove the `build` folder.
- run `HOME=~/.electron-gyp node-gyp rebuild --target=v20.0.0-nightly.20220512 --arch=x64 --dist-url=https://electronjs.org/headers` to compile the native module
- `cd ../..` and then run it by `npm exec electron index.js` command.

See [crash-dump.txt](https://github.com/electron/electron/files/8693655/crash-dump.txt) if needed.

**Comment by codebytere** [comment]
Stack Trace:

```console.
test ❯ [44759:0516/095242.850516:FATAL:field_trial.cc(776)] Check failed: result.
0   Electron Framework                  0x000000012bff7fd9 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x000000012bf19e53 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework                  0x000000012bf3324f logging::LogMessage::~LogMessage() + 175
3   Electron Framework                  0x000000012779ec9e partition_alloc::internal::LoggerWithAllowedAllocations::~LoggerWithAllowedAllocations() + 14
4   Electron Framework                  0x000000012bf40c1a base::FieldTrialList::CreateTrialsFromCommandLine(base::CommandLine const&, int) + 330
5   Electron Framework                  0x000000012de05d57 content::InitializeFieldTrialAndFeatureList() + 87
6   Electron Framework                  0x00000001278f4900 content::ContentMainRunnerImpl::Run() + 432
7   Electron Framework                  0x00000001278f33d3 content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) + 2723
8   Electron Framework                  0x00000001278f34ec content::ContentMain(content::ContentMainParams) + 92
9   Electron Framework                  0x00000001274a88bd ElectronMain + 157
10  Electron Helper (Renderer)          0x00000001042c599d main + 221
11  dyld                                0x0000000111f5451e start + 462
Crash keys:
  "platform" = "darwin"
  "process_type" = "renderer"
  "osarch" = "x86_64"
  "pid" = "44759"
  "ptype" = "renderer"
```

**Comment by vladimiry** [comment]
No longer relevant to me.
