### ISSUE TITLE
[Bug]: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by rajjagani021** [electron/electron#34238]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15

### What arch are you using?

ia32

### Expected Behavior

Should emit the event using ipcMain and ipcRenderer

### Actual Behavior

when trying to send the event from `main.js` to `App.vue` It's throwing the error when the application starts as attached to the screenshot.  It happened with `ipcMain` and `ipcRenderer`.

```
import { app, BrowserWindow, ipcMain, ipcRenderer } from 'electron'

ipcRenderer.send('ping','test')

app.on('will-finish-launching', () => {
  // Protocol handler for osx
  ipcRenderer.send('ping','test');
})
```

![ipc_error](https://user-images.githubusercontent.com/4434991/168430383-bce1fa63-3ea0-4aaf-afa7-16b66aff3388.png)

**Comment by vladimiry** [comment]
`ipcRenderer.send` has to be called in a preload script (render process), not in the main process.

**Comment by rajjagani021** [comment]
> `ipcRenderer.send` has to be called in a preload script (render process), not in the main process.

But I have integrated deep-linking so I am triggering `ipcMain` from the below event.  So is there any other way like I can send a message to vue component from the main.js?

```
app.on('open-url', (event, url) => {
    event.preventDefault();
    deeplinkingUrl = url
    console.log('open-url# ' + deeplinkingUrl)
    ipcMain.send('ping');
});

```

**Comment by codebytere** [comment]
@vladimiry is correct - this is not an issue with Electron itself. For most questions about Electron and its usage there are a lot of options. Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
