### ISSUE TITLE
Issue building native Node modules for Electron Application

### ISSUE THREAD

**Issue by HackersSpirit** [electron/electron#34249]
We are working on developing a desktop-based application using Electron. The application will perform various functionalities like interfacing multiple cameras and a serial device, collecting, processing, and displaying user data.The application can be broadly divided using two parts:1. Nodejs addon:It's a CPP-based application with code for interfacing the camera and serial device written on visual studio 2019. Later the application is compiled using the node-gyp tool to convert it into Nodejs Addon to be used in the electron application.2. Electron Application:It's a React on Electron-based application written on a visual studio code editor. We display the camera frames obtained by interfacing the module mentioned above and send and receive the serial commands using the above module. When we try to install the Node addon using 'npm i ', it gets installed successfully. We can interface with the camera and serial device.Our issue is when we try to package the application using 'npm run package', we get the error as a module not found for the Node addon mentioned above.We tried to follow approaches mentioned in the electron documentation regarding the Node addons and steps mentioned in a few online forums. Still, we are getting the same error as the module not found.We are using :1.Node: 16.13.22. npm 8.1.23. Platform: Windows 10 Pro4. Compiler: MSVC 20225. Module: node-gyp6. Editors: Visual studio 2019 -- Node addonsVisual studio code -- Electron appRequest you to look into the issue and let us know of an approach that we can follow to resolve the issue.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by HackersSpirit** [comment]
@codebytere : I tried multiple approaches like posting in the community and Discord for days. I even wrote an email to the team expecting a revert. Thinking GitHub repo as the last approach I posted here was expecting something helpful
