### ISSUE TITLE
[Bug]: CSD on Wayland has unclickable close button (in Signal)

### ISSUE THREAD

**Issue by y0ast** [electron/electron#34240]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux fedora 5.17.6-300.fc36.x86_64

### What arch are you using?

x64

### Expected Behavior

Run latest signal desktop (5.43.0) with:

```
flatpak run org.signal.Signal --ozone-platform=wayland --enable-features=WaylandWindowDecorations
```

Observe program runs in Wayland mode with CSD. Click the cross on the right top.

Expect: window closes

### Actual Behavior

The window does not close: the click is ignored and the button is also not highlighted.

Running signal-desktop on XWayland does allow normal clicking of this button.

### Additional Information

Linking to issue #29618

Tagging @refi64 who expressed to be keen to make this feature promoted from behind the flag.

**Comment by VerteDinde** [comment]
Hey @y0ast, thanks for reporting this issue! This current repro is very specific to Signal, so we may need to get a simpler repro before we can move forward debugging this issue.

Does this behavior repro for you on Fedora using either [Electron Quick Start](https://github.com/electron/electron-quick-start) or [Electron Fiddle](https://www.electronjs.org/fiddle)?

**Comment by y0ast** [comment]
Unfortunately I can't repro this with the newest slack release (4.26.1 - wayland works there though!) and I don't have time to setup electron compilation.

I'll close this and can reopen if others are interested in following up.

**Comment by csett86** [comment]
As I have been hit by this for an app I maintain, I have created a repro for this, see #34820 for details.
