### ISSUE TITLE
[Bug]: OnScreen Keyboard won't open on html text input focus

### ISSUE THREAD

**Issue by cries** [electron/electron#34251]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### What arch are you using?

x64

### Expected Behavior

The onscreen keyboard should open when focusing a html text input.

### Actual Behavior

The onscreen keyboard doesn't open when focusing a html text input.

### Additional Information

Under Windows 10 20H2 the keyboard opens as expected.

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by cries** [comment]
Here is the gist:
https://gist.github.com/cries/64744b09da9fbc8dd7b35ecd55209399

**Comment by codebytere** [comment]
@cries does this work correctly if you do the same thing in Google Chrome?

**Comment by tomutsch** [comment]
The bug happens when I use a build electron fullscreen app on a windows 10 tablet device without a keyboard attached.
I didn't test this bug on the device with google chrome. Right now I don't have the device anymore since it got returned to the client. 
I tried testing this electron-fiddle on a Win10 VM but I cannot get the VM to behave like a tablet device without a keyboard attached so the onscreen keyboard never opens, not even in Windows itself.

The only thing I can report is that I tried a simple electron app with just a input field (just like the fiddle) on the clients device. On the device with Win10 20H2 the keyboard shows, on the device with Win10 21H2 it doesn't show.

**Comment by cries** [comment]
The bug happens when I use a build electron fullscreen app on a windows 10 tablet device without a keyboard attached.
I didn't test this bug on the device with google chrome. Right now I don't have the device anymore since it got returned to the client.
I tried testing this electron-fiddle on a Win10 VM but I cannot get the VM to behave like a tablet device without a keyboard attached so the onscreen keyboard never opens, not even in Windows itself.

The only thing I can report is that I tried a simple electron app with just a input field (just like the fiddle) on the clients device. On the device with Win10 20H2 the keyboard shows, on the device with Win10 21H2 it doesn't show.

**Comment by alariej** [comment]
Hi, this behavior is also present on a Pinephone running Linux mobian 5.15-sunxi64 / Phosh UI: The onscreen keyboard does not pop up automatically when a Text Input element gets focused. Users must manually open the keyboard by pressing the keyboard icon (always visible on the lower right corner of the screen).
