### ISSUE TITLE
[Bug]: after upgraded version from 11.5.0 to 12.2.3 which causes websocket connection was closed before the connection was established issue (Help Help Help SOS)

### ISSUE THREAD

**Issue by mx51damon** [electron/electron#34265]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.4

### What operating system are you using?

macOS

### Operating System Version

12.3 monterrey (M1 chip)

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

17.4.4

### Expected Behavior

The websocket connection should be keeping alive. App is still up and running.

### Actual Behavior

After I upgrade electron version from 11.5.0 to 17.4.4, everything looks perform correctly except for the websocket connection.

The error message is shown `WebSocket was closed before the connection was established`. After I have made a few trials, I noticed that since I added this attribute `contextIsolation`: false into the codebase, the websocket connection issue occurred.

If I don't put this attribute (`contextIsolation`: false), my whole app will be shown as blank screen and error message will be shown as 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/88181723/168917210-6e9ecdbb-5c6f-44ff-9ce8-c6d1939cec67.png">
<img width="804" alt="image" src="https://user-images.githubusercontent.com/88181723/168917320-2b870384-7f32-4d36-8122-b51b287e0941.png">

If I am using the attribute (`contextIsolation`: false), I will get the websocket closed error, like this:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/88181723/168917525-1d075d2f-289c-4195-a5d2-7f34054214cd.png">

If I am using old version 11.5.0 which does not need to setup this attribute (`contextIsolation`: false), which will not cause the websocket connection closed error.

May I get some help with this issue?

Mega thanks 🙏

**Comment by mx51damon** [comment]
My latest found: previously I can keep my ping() API keep sending the request, but now, after used the version 17.4.4, the ping() API is not going to be sent, is that something changed from Electron side to prevent my ping() API request keep sending? because the electron app will report the web socket closed error ...

**Comment by mx51damon** [comment]
After few trials, I can tell that the error is between 11.5.0 and 12.2.3 for electron version

**Comment by mx51damon** [comment]
Hey there, can I get som e help with this issue, I really need some help here. 

Mega thanks.

**Comment by mx51damon** [comment]
Hi @ankar84, I just found that it might not be related with contextIsolation attribute, it might be caused by the `uncaughtException` error which is raised by NodeJS, and when main process (node side) is showing the js error, then iyt seems like ipc communication is completely turned off, then the electron is going to close the app.

```
 process.on('uncaughtException', function (error) {
      console.log(
        'Triggered !!!!✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅', error
      );
    });
```

When I added this piece of code, the error popup is gone, and the error will be shown in terminal.

I would like to ask is there a way to stop the app crashing when error detected?

I think this is very important to me for understanding my current bug.

Please help me. Many many thanks ~~

**Comment by mx51damon** [comment]
Hi Electron team, may I ask fro some help? I really need some help here, it stuck around 2 weeks for now. Please help me.

Many many thanks ~~

**Comment by VerteDinde** [comment]
Hey @mx51damon - this is actually an intentional design choice on Electron's part. Context Isolation was enabled by default on Electron 12, whereas it's not enabled by default in Electron 11. That's why you need to set context isolation to false. You can read more about how context isolation works here: https://www.electronjs.org/docs/latest/tutorial/context-isolation

A few things you can do:
1. Add `contextIsolation: false` to your windows. I wouldn't recommend this long-term, but it should allow your app to work on Electron 12 in the short term.
2. Refactor your app to use context bridge, as outlined in the tutorial linked above.

I hope this helps you! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. I'll close this issue for now, but if you have more questions about Electron, there are a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by mx51damon** [comment]
Thank you very much for the directional suggestion @VerteDinde 👍, and I will have a look at the context bridge see what I can do for my current project.

If I have further questions or stuck,  I will join the discord chat to ask.

Thank you 🙏

**Comment by mx51damon** [comment]
Hi @VerteDinde, would you mind to send me another discord link, it seems like the current link is expired ..

**Comment by megasanjay** [comment]
> Hi @VerteDinde, would you mind to send me another discord link, it seems like the current link is expired ..

Here is a link to the Discord: https://discord.gg/S32JaeEJ
