### ISSUE TITLE
[Bug]: Uncaught Error: Loading non-context-aware native module in renderer.

### ISSUE THREAD

**Issue by ShruthiMallaiah** [electron/electron#34269]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.0.4

### What arch are you using?

x64

### Last Known Working Electron version

13.1.0

### Expected Behavior

The application should launch without any error in the console.

### Actual Behavior

Application is not launching and there is an error in the Devtools.

![image](https://user-images.githubusercontent.com/28384851/168994148-b741708f-79ac-4535-b97b-4a2f27baa6fe.png)

### Additional Information

Many suggested to use `app.allowRendererProcessReuse = false;` in main.js. Even this didn't resolve the issue.
Also as per official documentation of Electron, modifying this flag is disabled. So please suggest on how to resolve this

**Comment by codebytere** [comment]
This is not a bug - it's [a requirement](https://github.com/electron/electron/issues/18397)

**Comment by Tombliboo96** [comment]
Hello, may I ask how you solved this problem? Based on how you encountered the same problem @ShruthiMallaiah
