### ISSUE TITLE
v17.4.4 node headers tarball resulting in 403

### ISSUE THREAD

**Issue by t3chguy** [electron/electron#34274]
https://atom.io/download/electron/v17.4.4/node-v17.4.4-headers.tar.gz results in 403 (after a redirect to https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v17.4.4/node-v17.4.4-headers.tar.gz)
https://atom.io/download/electron/v17.4.3/node-v17.4.3-headers.tar.gz downloads fine

See respective CI fails on Mac, Linux, Windows
https://github.com/vector-im/element-desktop/runs/6477028771?check_suite_focus=true
https://github.com/vector-im/element-desktop/runs/6477028578?check_suite_focus=true
https://github.com/vector-im/element-desktop/runs/6477028883?check_suite_focus=true

Additionally 17.4.4 seems to be lacking a changelog in https://www.electronjs.org/releases/stable?version=17

**Comment by MarshallOfSound** [comment]
@t3chguy Your build is using an **incredibly** old URL, `atom.io` isn't even controlled by the same team anymore.  If you update that to point to `electronjs.org/headers` it should work fine.

For context the thing that finally broke here was this recent infrastructure change:
--> https://www.electronjs.org/blog/s3-bucket-change

But you would have been fine if you weren't on a super old legacy URL for our headers:
--> https://www.electronjs.org/docs/latest/breaking-changes#deprecated-atomio-node-headers-url

**Comment by t3chguy** [comment]
@MarshallOfSound I appreciate your response, any chance you know whats up with the missing changelog on https://www.electronjs.org/releases/stable?version=17

**Comment by MarshallOfSound** [comment]
Due to the ongoing Heroku incident we have to deploy our website manually, so it lags behind a bit nowadays
