### ISSUE TITLE
Tracking and persisting navigation in webview in electron.js

### ISSUE THREAD

**Issue by alokmahor** [electron/electron#34339]
I am creating simplest electron application for learning which is using [`webview`][1] for displaying webpage.

I want to select which website is to be opened in webview and I want to persist the last navigation url for each individual website.

Here is my attempt which does not work properly.

```typescript
import React from 'react';
import { MemoryRouter as Router, Routes, Route } from 'react-router-dom';
import icon from '../../assets/icon.svg';
import './App.css';

type Props = {

}

type State = {
  url: any,
  key: string
}
class Hello extends React.Component<Props, State> {
  webview: any;
  constructor(props) {
    super(props);
    this.state = {
      url: {
        blank: 'about:blank',
        youtube: 'https://www.youtube.com/',
        google: 'https://www.google.com/',
        wikipedia: 'https://en.wikipedia.org/wiki/Main_Page',
        w3schools: 'https://www.w3schools.com/'
      },
      key: 'blank'
    };
    this.webview = React.createRef()
  }

  componentDidMount() {
    let webview = this.webview.current
    webview.addEventListener('did-start-navigation', (event: any) => {
      console.log('event:', event)
      let newUrl = event.url
      if (newUrl != 'about:blank' && event.isInPlace && event.isMainFrame) {
        let url = { ...this.state.url }
        url[this.state.key] = newUrl
        this.setState({ ...this.state, url })
      }
    })
  }

  selectUrl(key: string) {
    this.setState({ ...this.state, key: key })
  }

  handleBack = () => {
    this.webview.current.goBack()
  }

  handleForward = () => {
    this.webview.current.goForward()
  }

  render() {
    return (
      <>
        <span onClick={this.handleBack.bind(this)}>Back</span>
        <span style={{margin: '1rem'}}></span>
        <span >Forward</span>
        <div style={{ width: '640px', height: '360px', border: 'solid' }}>
          <webview
            ref={this.webview}
            src={ this.state.url[this.state.key]}
            id="myWebview"
            style={{ display: 'inline-flex', width: '640px', height: '360px' }}
            allowpopups="true"
          />
        </div>
        <div style={{ border: 'solid' }}>
          <span onClick={() => this.selectUrl('youtube')} style={{ border: 'solid' }}>YouTube</span>
          <span onClick={() => this.selectUrl('google')} style={{ border: 'solid' }}>Google</span>
          <span onClick={() => this.selectUrl('wikipedia')} style={{ border: 'solid' }}>wikipedia</span>
          <span onClick={() => this.selectUrl('w3schools')} style={{ border: 'solid' }}>w3schools</span>
        </div>
      </>
    );
  }
}

export default function App() {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<Hello />} />
      </Routes>
    </Router>
  );
}
```

In this attempt I am using [`did-start-navigation`][2] [`DOM Event`][3] of WebView.

I tried other DOM Events also like [`will-navigate`][4], [`did-navigate`][5] and [`did-navigate-in-page`][6] but nothing works.

How can I achieve remembering the last navigated url of each website so when I come back to the website I should be able to see the last navigated page instead of the homepage of that website?

  [1]: https://www.electronjs.org/docs/latest/api/webview-tag
  [2]: https://www.electronjs.org/docs/latest/api/webview-tag#event-did-start-navigation
  [3]: https://www.electronjs.org/docs/latest/api/webview-tag#dom-events
  [4]: https://www.electronjs.org/docs/latest/api/webview-tag#event-will-navigate
  [5]: https://www.electronjs.org/docs/latest/api/webview-tag#event-did-navigate
  [6]: https://www.electronjs.org/docs/latest/api/webview-tag#event-did-navigate-in-page

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
