### ISSUE TITLE
[Bug]: installation issue on mac

### ISSUE THREAD

**Issue by wxiang-us** [electron/electron#34330]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Unknown

### What operating system are you using?

macOS

### Operating System Version

MacOS monterey

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

I dont know

### Expected Behavior

Tried to install but failed 

### Actual Behavior

Tried to install Electron on Mac follow guideline
after "npm install" got following errors, seems the version of Electron it point to no longer hold on github.
Could you please point me to the most current installation guidelines? Thanks!

`npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! code 1
npm ERR! path /Users/wxiang/electron-quick-start/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
Downloading tmp-2614-0-electron-v5.0.7-darwin-arm64.zip
npm ERR! Error: GET https://github.com/electron/electron/releases/download/v5.0.7/electron-v5.0.7-darwin-arm64.zip returned 404
npm ERR! /Users/wxiang/electron-quick-start/node_modules/electron/install.js:49
npm ERR!   throw err
npm ERR!   ^
npm ERR! 
npm ERR! Error: Failed to find Electron v5.0.7 for darwin-arm64 at https://github.com/electron/electron/releases/download/v5.0.7/electron-v5.0.7-darwin-arm64.zip
npm ERR!     at Request.<anonymous> (/Users/wxiang/electron-quick-start/node_modules/nugget/index.js:169:61)
npm ERR!     at Request.emit (node:events:527:28)
npm ERR!     at Request.onRequestResponse (/Users/wxiang/electron-quick-start/node_modules/request/request.js:1066:10)
npm ERR!     at ClientRequest.emit (node:events:527:28)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:494:22)
npm ERR!     at TLSSocket.emit (node:events:527:28)
npm ERR!     at addChunk (node:internal/streams/readable:315:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:289:9)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/w/.npm/_logs/2022-05-23T15_59_57_331Z-debug-0.log`

### Testcase Gist URL

NA

### Additional Information

latest npm version

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by themightyoarfish** [comment]
It appears this issue was closed in error, as it points out that electron cannot be installed on macos via `npm install`.
