### ISSUE TITLE
[Bug]: Electron App does not launch on Mac with SIP disabled

### ISSUE THREAD

**Issue by tellus1019** [electron/electron#34355]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

sorry I don't know

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Apps using Electron should work regardless of SIP status

### Actual Behavior

With SIP disabled, the application does not start and is immediately force-quit.

### Additional Information

Attached is the error log displayed by macOS

[slack.txt](https://github.com/electron/electron/files/8780439/slack.txt)
[1password8.txt](https://github.com/electron/electron/files/8780437/1password8.txt)

Tip: I use M1 Macbook Pro 13.

Check below for instructions on how to turn off SIP
[Disabling and Enabling System Integrity Protection](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection)

**Comment by MarshallOfSound** [comment]
I believe this is how the sandbox is kinda expected to work 🤔 Have you tested Chrome itself?

**Comment by luken11** [comment]
I’ve experienced this too, Chrome browser exhibits the same behaviour. It seems forcing affected apps to run under Rosetta instead of arm64 where possible resolves the issue for those particular apps
