### ISSUE TITLE
[Bug]: GPU process crashes with exit code -1073741819

### ISSUE THREAD

**Issue by FlysoftBeta** [electron/electron#34366]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0-alpha.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2

### What arch are you using?

x64

### Expected Behavior

Create browserwindow normally

### Actual Behavior

When I try to create a new BrowserWindow, it says:
[16720:0528/110823.336:ERROR:gpu_process_host.cc(973)] GPU process exited unexpectedly: exit_code=-1073741819
[16720:0528/110823.828:ERROR:gpu_process_host.cc(973)] GPU process exited unexpectedly: exit_code=-1073741819
[16720:0528/110825.832:ERROR:gpu_process_host.cc(973)] GPU process exited unexpectedly: exit_code=-1073741819
[16720:0528/110826.242:ERROR:gpu_process_host.cc(973)] GPU process exited unexpectedly: exit_code=-1073741819
[16720:0528/110827.345:ERROR:gpu_process_host.cc(973)] GPU process exited unexpectedly: exit_code=-1073741819
[16720:0528/110827.347:FATAL:gpu_data_manager_impl_private.cc(451)] GPU process isn't usable. Goodbye.

This happens even when I disabled hardware acceleration.

### Additional Information

CPU: Intel i3-4130
GPU: AMD Radeon HD 7570

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by FlysoftBeta** [comment]
I don't think it's necessary to upload a testcase. Just use the default testcase
![image](https://user-images.githubusercontent.com/49718840/170862688-fb7167a3-46bf-47d6-98ea-74aee7e8bddb.png)

**Comment by VerteDinde** [comment]
@FlysoftBeta Hmm, sorry, I'm actually not able to repro this on my Windows machine or in a Windows VM 🤔 I wonder if it may be specific to a certain kind of GPU or environment. If it's no trouble, would you mind sharing more information about your Windows machine, such as type of GPU? That might help us narrow it down.

One other thing that might help - would you minding grabbing and attaching a crash dump? That should help us see exactly in the code where it's crashing. You can get them by adding the following snippet to the `main.js` file in your Fiddle, before app.whenReady:

```
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```
Then reproduce the crash, zip up the crash dumps directory and attach it here.

Thanks again for reporting this! I'll keep trying to reproduce it on my end and see if I can get more information 🙇‍♀️

**Comment by VerteDinde** [comment]
@FlysoftBeta Wow, thanks for the clarification - I just tried with 20.0.0-alpha.1 on my Windows machine and could repro immediately with just the basic Fiddle example. Thanks for reporting this!

**Comment by codebytere** [comment]
<details><summary>Stacktrace</summary>

```
Received fatal exception EXCEPTION_BREAKPOINT
Backtrace:
v8_inspector::V8StackTraceId::ToString [0x0164F36B+9303227]
v8_inspector::V8StackTraceId::IsInvalid [0x046C1CBB+2888347]
v8_inspector::V8StackTraceId::ToString [0x010F0063+3670451]
v8_inspector::V8StackTraceId::IsInvalid [0x046C073D+2882845]
v8_inspector::V8StackTraceId::IsInvalid [0x046C3198+2893688]
v8_inspector::V8StackTraceId::IsInvalid [0x046C35CE+2894766]
v8_inspector::V8StackTraceId::ToString [0x0101400D+2769245]
GetHandleVerifier [0x01C2AF15+662837]
v8::HeapStatistics::external_memory [0x00368452+106258]
IsSandboxedProcess [0x01704C9E+19246]
Cr_z_deflate [0x017803AD+49581]
Cr_z_deflate [0x017811B3+53171]
cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::IsMarking [0x035F6600+2600448]
v8::String::ExternalStringResourceBase::IsCacheable [0x0314D149+4297]
cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::IsMarking [0x03601C4F+2647119]
IsSandboxedProcess [0x0170EDE3+60531]
cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::IsMarking [0x035C0A32+2380338]
Cr_z_crc32 [0x03680BED+449053]
v8_inspector::V8StackTraceId::IsInvalid [0x04CC6DDC+9200572]
v8_inspector::V8StackTraceId::ToString [0x0168428B+9520091]
v8_inspector::V8StackTraceId::ToString [0x01341CC5+6102549]
uv_os_getpid [0x0168952B+14747]
uv_os_getpid [0x01689277+14055]
AddClipboardFormatListener [0x77850FCB+75]
GetClassLongW [0x77847F9A+1962]
GetClassLongW [0x77847B9A+938]
CallNextHookEx [0x7784B75F+415]
KiUserCallbackDispatcher [0x77AE4E7D+77]
PostMessageW [0x77845929+153]
Ordinal132 [0x72423665+4885]
Ordinal45 [0x7241FB91+2577]
Ordinal45 [0x7241F808+1672]
GetSystemMetricsForDpi [0x77846157+567]
Cr_z_zError [0x054D4CDE+7790030]
uv_udp_get_send_queue_size [0x020893DD+2763293]
uv_udp_get_send_queue_size [0x02088822+2760290]
GetHandleVerifier [0x01D48459+1831545]
GetHandleVerifier [0x01D47F47+1830247]
AddClipboardFormatListener [0x77850FCB+75]
GetClassLongW [0x77847F9A+1962]
GetClassLongW [0x77847B9A+938]
CallNextHookEx [0x7784B75F+415]
KiUserCallbackDispatcher [0x77AE4E7D+77]
PostMessageW [0x77845929+153]
Ordinal132 [0x72423665+4885]
Ordinal45 [0x7241FB91+2577]
Ordinal45 [0x7241F808+1672]
GetSystemMetricsForDpi [0x77846157+567]
Cr_z_zError [0x054D4FFA+7790826]
uv_udp_get_send_queue_size [0x0208A2F7+2767159]
uv_udp_get_send_queue_size [0x020891C4+2762756]
uv_udp_get_send_queue_size [0x02088822+2760290]
GetHandleVerifier [0x01D48459+1831545]
GetHandleVerifier [0x01D47F47+1830247]
AddClipboardFormatListener [0x77850FCB+75]
GetClassLongW [0x77847F9A+1962]
DispatchMessageW [0x77845CFA+586]
DispatchMessageW [0x77845AC0+16]
cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::IsMarking [0x035CEA0C+2437644]
cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::IsMarking [0x035CE000+2435072]
v8_inspector::V8StackTraceId::ToString [0x0168412C+9519740]
uv_sleep [0x01B85346+122470]
v8_inspector::V8StackTraceId::ToString [0x01660AAC+9374716]
v8_inspector::V8StackTraceId::ToString [0x01028889+2853337]
v8_inspector::V8StackTraceId::ToString [0x0102A46E+2860478]
v8_inspector::V8StackTraceId::ToString [0x01025A21+2841457]
v8_inspector::V8DebuggerId::V8DebuggerId [0x0048F776+435462]
v8_inspector::V8DebuggerId::V8DebuggerId [0x0049091F+439983]
v8_inspector::V8DebuggerId::V8DebuggerId [0x004904A9+438841]
v8_inspector::V8DebuggerId::V8DebuggerId [0x0048D13E+425678]
v8_inspector::V8DebuggerId::V8DebuggerId [0x0048D3A8+426296]
std::__1::__vector_base<v8::CpuProfileDeoptInfo,std::__1::allocator<v8::CpuProfileDeoptInfo> >::__move_assign_alloc [0x0027F721+47201]
std::__1::__vector_base<v8::CpuProfileDeoptInfo,std::__1::allocator<v8::CpuProfileDeoptInfo> >::__move_assign_alloc [0x0027F391+46289]
GetNumaHighestNodeNumber [0x75F3DAB1+161]
GetNumaHighestNodeNumber [0x75F3DA66+86]
RtlUserFiberStart [0x77AE2777+23]

Electron exited with code 3221226525.
```

</details>

**Comment by FlysoftBeta** [comment]
Thanks! The problem fixed when I upgraded Electron to v20.0.0-alpha.2.

**Comment by psulek** [comment]
@FlysoftBeta is there any chance this will be fixed in older versions like 16x ? We stuck on that version because of some changes made in electron from v17.

**Comment by psulek** [comment]
For others who experience same error with exit code `-1073741819` , my case was that my electron app can do some "main process task without opening any windows and exit" in case when i run it with my cmd arg (like for example `--reinit`). In such case my app does some task (delete/create some files required for app and calls app.exit(0). But it still returns exist code `-1073741819` at 99% of all time (sometimes it does not).

Now i found out that i call 
```js
  app.getGPUInfo('complete').then(data=>log(data)).catch(e=>console.log(e));
```

Such call takes time (to init gpu process ??) and if my other code will to call app.exit(0) earlier than `app.getGPU` is finished i get `-1073741819` exit code.

For me it was easy fix because when my app is running special reinit mode (`--reinit` cmd arg) i do not need to log GPU data into logs, so i skip that call. It is not a fix but rather workaround.
