### ISSUE TITLE
[Bug]: .appx crashes when launching "chrome://gpu" in child window

### ISSUE THREAD

**Issue by VerteDinde** [electron/electron#34376]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0-beta.1+, 19.0.0+

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

18.0.0-alpha.5

### Expected Behavior

Trying to launch `chrome://gpu` in a new child window should open a new window and show the loaded page contents.

### Actual Behavior

Trying to launch `chrome://gpu` in a new child window will cause the packaged app to flash black and often crash. Closing the app and try to reopen it will not relaunch the app - uninstalling and reinstalling is required.

### Testcase Gist URL

https://github.com/VerteDinde/appx-crash-repro

### Additional Information

This issue is specific to the .appx build - running these same steps in Electron Fiddle on Windows and using other installers such as an .exe seem to work just fine. I bisected the issue down to a change between [18.0.0-alpha.5 and 18.0.0-beta.1](https://github.com/electron/electron/commits/18-x-y?after=26e7f27110c847790eb32d3d0a951ab78120df60+139&branch=18-x-y&qualified_name=refs%2Fheads%2F18-x-y). This likely broke somewhere in this Chromium roll: https://github.com/electron/electron/pull/33093

**Comment by VerteDinde** [comment]
Checked and confirmed - this issue is still present as of [v22.0.0-alpha.1](https://github.com/electron/electron/releases/tag/v22.0.0-alpha.1)

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump
