### ISSUE TITLE
[Bug]: Dev tools don't show

### ISSUE THREAD

**Issue by fcg42** [electron/electron#34372]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Other Linux

### Operating System Version

Pop!_OS 22.04 LTS

### What arch are you using?

x64

### Last Known Working Electron version

13.1.2

### Expected Behavior

The Dev tools panel should open.

### Actual Behavior

The dev tools don't show up

### Additional Information

It was all working fine, until I upgraded the OS for the latest version 22.04 LTS. From there on, the dev tools stopped showing. The app has no changes, and the dev tools are still showing up if I use the app on MacOS. 

I tried upgrading Electron to 13.5.x, but the problem persisted. 

Thnak you.

**Comment by VerteDinde** [comment]
Hey @fcg42, that's for reporting this issue! Electron 13 is actually end of life, so we're no longer supporting bug fixes for it. Could you try Electron 17 or later and see if the issue persists?
