### ISSUE TITLE
[Bug]: client not loading just grey screen

### ISSUE THREAD

**Issue by jomamale** [electron/electron#34382]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Microsoft Windows 10 Pro

### What arch are you using?

x64

### Last Known Working Electron version

idk

### Expected Behavior

to load teh client

### Actual Behavior

grey screen

**Comment by VerteDinde** [comment]
This is an issue with Discord specifically, and not Electron itself. Please file an issue with Discord support.
