### ISSUE TITLE
[Bug]: I opened the discord bot client, and its just stuck on a gray screen.

### ISSUE THREAD

**Issue by pariswashere** [electron/electron#34383]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

for it to open and work

### Actual Behavior

just stuck on a gray screen

**Comment by VerteDinde** [comment]
This is an issue with Discord specifically, and not Electron itself. Please file an issue with Discord support.
