### ISSUE TITLE
[Bug]: Electron 19.x.y and main require Glibc 2.29+ on arm64

### ISSUE THREAD

**Issue by theofficialgman** [electron/electron#34399]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.x.y

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu Bionic

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

18.x.y

### Expected Behavior

Electron continues to be build on Ubuntu bionic, a distro which has more than a year of standard support (april 2023) and end of life in 2028. Debian buster is also affected, a distro which does not end standard support until June, 2024

the description here is incorrect https://github.com/electron/electron/pull/32614

### Actual Behavior

Unable to use electron 19.x.y due to electron and libffmpeg.so requiring glibc 2.29

```
Electron v19.0.1 started.
/home/garrett/.config/Electron Fiddle/electron-bin/19.0.1/electron: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/garrett/.config/Electron Fiddle/electron-bin/19.0.1/electron)
/home/garrett/.config/Electron Fiddle/electron-bin/19.0.1/electron: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/garrett/.config/Electron Fiddle/electron-bin/19.0.1/libffmpeg.so)
```

**Comment by theofficialgman** [comment]
due to compiler differences, this was likely not reported earlier as (so far in my testing) it only affects ARM64

due to compiler chance, x86_64 and armhf only depend on libc 2.17+ while arm64 depends on libc 2.29+ for the current 19.0.1 electron release. this does not change the urgency of the issue however

**Comment by jkleinsc** [comment]
I have a fix for this issue.  PR incoming.
