### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'whenReady') occurs upon building

### ISSUE THREAD

**Issue by sparty182020** [electron/electron#34396]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

Upon runing `node .` (start is set to `electron .`), code starts, builds the app for view, and runs properly

### Actual Behavior

upon running, gets a:
```
app.whenReady().then(() => {
       ^

TypeError: Cannot read properties of undefined (reading 'whenReady')
```

### Additional Information

Source Code available [Here](https://github.com/sparty182020/Election-Page-using-Code-Area)

**Comment by codebytere** [comment]
```
git clone https://github.com/sparty182020/Election-Page-using-Code-Area
npm i
npm start
```

Works without issue:
![Screen Shot 2022-05-31 at 3 22 12 PM](https://user-images.githubusercontent.com/2036040/171183599-79c82260-274a-4a72-9e5e-4a2a0719712e.png)

`node .` would not work. you need to run `electron .`
