### ISSUE TITLE
[Bug]: red background on hover to PiP

### ISSUE THREAD

**Issue by Genexys** [electron/electron#34406]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version 19044.1706

### What arch are you using?

x64

### Last Known Working Electron version

18.1.0

### Expected Behavior

when hovering over pip, there is no red background and controls are visible

### Actual Behavior

when hovering over pip, there is a red background and no controls are visible

### Additional Information

![image](https://user-images.githubusercontent.com/11525479/171402617-11d4444d-fe18-4711-b5c5-a0773f9993b1.png)

**Comment by VerteDinde** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by Genexys** [comment]
https://gist.github.com/Genexys/c25b1f230a3b84436c983c67986420ab/revisions test from electron fiddle
![image](https://user-images.githubusercontent.com/11525479/172145775-4b430c85-b412-4a2c-b0b9-1ec9650fd93f.png)

**Comment by flightmansam** [comment]
Experiencing this on min browser (master) using 19.0.1.

**Comment by flightmansam** [comment]
@Genexys The latest stable version of electron that doesn't have the red background issue is 18.3.0.

This is bugging me but I am by no means an electron expert, just a tinkerer of many things. My first hunch is that it isn't loading the `picture-in-picture.html` resource properly. But I have had a look at the .ts based changes that call for this between v18.3.0 and v19.0.0 and there seems to be no appreciable difference with Picture in Picture.

Electron files I had a look at:

[electron-18.3.0/spec-main/api-web-contents-spec.ts L1891](https://github.com/electron/electron/blob/v18.3.0/spec-main/api-web-contents-spec.ts#L1891)
[electron-19.0.0/spec-main/api-web-contents-spec.ts L1891](https://github.com/electron/electron/blob/v19.0.0/spec-main/api-web-contents-spec.ts#L1891)

[electron-18.3.0/spec/fixtures/api/picture-in-picture.html](https://github.com/electron/electron/blob/v18.3.0/spec/fixtures/api/picture-in-picture.html)
[electron-19.0.0/spec/fixtures/api/picture-in-picture.html](https://github.com/electron/electron/blob/v19.0.0/spec/fixtures/api/picture-in-picture.html)

However the buttons actually work even though they are hidden by the red. Where there does seem to be an appreciable difference is in the chromium patches to implement PiP.

[electron-18.3.0/patches/chromium/picture-in-picture.patch](https://github.com/electron/electron/blob/v18.3.0/patches/chromium/picture-in-picture.patch)
[electron-19.0.0/patches/chromium/picture-in-picture.patch](https://github.com/electron/electron/blob/v19.0.0/patches/chromium/picture-in-picture.patch)

@VerteDinde I will see about making a fiddle test case for you. I am on MacOS so could you please update the tag to include this platform tag. Unsure about linux at this stage.

**Comment by leonardxfce-dialpad** [comment]
I can confirm, that we tested on 19.0.7 both in windows 10 and MacOS Monterrey and we got the red bug. 
Rollbacking our app to 18.3.5 fixed the problem.
Chrome 102 doesn't show this bug if this gives more info.

**Comment by leonardxfce-dialpad** [comment]
Thanks @MarshallOfSound for taking care of this bug! 👍
