### ISSUE TITLE
[Bug]: os.hostname() not implemented on Win7 Electron19

### ISSUE THREAD

**Issue by Elendiar** [electron/electron#34404]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 7 SP1

### What arch are you using?

ia32

### Last Known Working Electron version

18.3

### Expected Behavior

get computer hostname

### Actual Behavior

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)

On import `const { hostname } = require("os");`

Program used on production PCs, where are some amount of old win7x86.

**Comment by codebytere** [comment]
`os` is a Node.js module, not an Electron module. Please open an issue there.

**Comment by jeremyspiegel** [comment]
@codebytere Node.js doesn't claim support for Windows 7 (https://github.com/nodejs/node/blob/main/BUILDING.md#platform-list) and won't be fixing this (https://github.com/nodejs/node/issues/41297), and neither will libuv (https://github.com/libuv/libuv/issues/3260).

Should Electron stop claiming Windows 7 support also? https://github.com/electron/electron/#platform-support

**Comment by jeremyspiegel** [comment]
Just saw that this was fixed via https://github.com/electron/electron/issues/35219.
