### ISSUE TITLE
[Bug]: Tooltips open delayed and at wrong place

### ISSUE THREAD

**Issue by t57ser** [electron/electron#34422]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

x64

### Expected Behavior

I think that no tooltip should appear in this case

### Actual Behavior

I think for better understanding i first need to explain how to reproduce the issue:
- hover over the "hello world" text until the tooltip appears
- once the tooltip appears click on the text
- the click will cause another (child) window to be shown
- click back into the parent window
- wait a bit (do not move the mouse)
- the tooltip from the "hello world" text will appear

A number of other issues have been noticed related to that, sometimes the tooltip seems to keep reappearing
sometimes it will appear and not vanish
but I do not know how to reproduce these cases yet.
The one described can be reproduced all the time though

### Testcase Gist URL

https://gist.github.com/t57ser/43615237ae540d2d22712ff27672d0ea

**Comment by pushkin-** [comment]
somewhat related [PR](https://github.com/electron/electron/pull/11629)?

I feel like I've seen issues with tooltips getting stuck, and it seemed like a Chromium bug.
