### ISSUE TITLE
[Bug]: Wrong cursor theme under Wayland on Linux

### ISSUE THREAD

**Issue by francisco-zr** [electron/electron#34448]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.1

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux x86_64

### What arch are you using?

x64

### Expected Behavior

Do not change the mouse cursor theme

### Actual Behavior

Cursor theme changes in File Picker or some places under Wayland, it doesn't happend in a X11 session.
![bad_cursor](https://user-images.githubusercontent.com/94826092/172178261-15835a92-a47d-4bc8-ad92-8896d6b8a641.png)
![expected](https://user-images.githubusercontent.com/94826092/172178266-35bbf3c2-65f5-4140-9506-1fe6de14b1ad.png)

**Comment by RaisinTen** [comment]
@francisco-zr did you install VS Code from the Snap Store? If so, could you verify if this is still an issue when you download it from the official website - https://code.visualstudio.com?

**Comment by deermichel** [comment]
Thanks for reporting this and helping to make Electron better!

I can confirm this in VSCode, but I wasn't able to come up with a standalone repro in [Electron Fiddle](https://www.electronjs.org/fiddle). Could you please follow up with a minimal gist to help us narrowing down the issue.

Thanks in advance! Your help is appreciated.

**Comment by RaisinTen** [comment]
> I can confirm this in VSCode

@deermichel the one from the Snap Store? I was suspecting that this would be the same issue as https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1579268 which is also impacting Postman, see https://github.com/postmanlabs/postman-app-support/issues/10030.

**Comment by deermichel** [comment]
@RaisinTen no, it was installed from the website (deb file)

**Comment by francisco-zr** [comment]
> @francisco-zr did you install VS Code from the Snap Store? If so, could you verify if this is still an issue when you download it from the official website - https://code.visualstudio.com?

I downloaded from aur(https://aur.archlinux.org/packages/visual-studio-code-bin), but i can confirm with fedora live and oficial rpm's too, isn't from snap store, but i think it's a kde plasma bug maybe, because in gnome i can't reproduce.

In this closed bug there are some reports too under Wayland: https://github.com/electron/electron/issues/10705#issuecomment-732806867
