### ISSUE TITLE
Getting “user cancelled the requestdevice chooser” error with electron-17-x

### ISSUE THREAD

**Issue by maneetgoyal** [electron/electron#34443]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.7

### What operating system are you using?

macOS

### Operating System Version

Monterrey 

### What arch are you using?

x64

### Expected Behavior

Web Bluetooth should not throw error.

### Actual Behavior

Took a look at the following SO resources:

 1. https://stackoverflow.com/questions/69874506/web-bluetooth-chrome-extension-user-cancelled-the-requestdevice-chooser
 2. https://stackoverflow.com/questions/59568260/electron-web-bluetooth-api-requestdevice-error
 3. https://stackoverflow.com/questions/68057325/can-you-manipulate-web-bluetooth-chooser-that-shows-after-calling-requestdevice

But their solutions don't seem to be working.

Here's my `main` file:

```
import { app, BrowserWindow } from "electron";

/**
 * Ref: https://www.electronjs.org/docs/tutorial/quick-start#create-the-main-script-file
 */
async function createWindow(): Promise<BrowserWindow> {
  // Creating a browser window
  const win = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true,
    },
  });

  /**
   * Handle bluetooth connection
   * Ref: https://www.electronjs.org/docs/latest/tutorial/devices#web-bluetooth-api
   */
  win.webContents.on("select-bluetooth-device", (event, devices, callback) => {
    event.preventDefault();
    if (devices.length > 0) {
      callback(devices[0].deviceId);
    }
  });

  // Load index.html
  win.maximize();
  await win.loadFile("./dist/renderer/index.html");
  return win;
}

function setUpElectronApp(): void {
  // Browser window
  let win: BrowserWindow | undefined;

  // Enable webBluetooth
  app.commandLine.appendSwitch("enable-experimental-web-platform-features", "true");
  app.commandLine.appendSwitch("enable-web-bluetooth", "true");

  // Create bowser window once the electron app is initialized
  app
    .whenReady()
    .then(() => {
      createWindow()
        .then((response) => {
          win = response;
          console.log(win);
        })
        .catch((err) => {
          throw err as Error;
        });
    })
    .catch((err) => {
      throw err as Error;
    });

  // Quit the application when it no longer has any open windows
  app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
      // The action is no-op on macOS due to the OS' behavior (https://support.apple.com/en-ca/guide/mac-help/mchlp2469/mac)
      // On macOS it is common for applications and their menu bar to stay active until the user quits explicitly with Cmd + Q
      app.quit();
      win = undefined;
    }
  });

  // Create a new browser window only when the application has no visible windows being activated
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      // On macOS it's common to re-create a window in the app when the dock icon is clicked and there are no other windows open.
      createWindow()
        .then((response) => {
          win = response;
          console.log(win);
        })
        .catch((err) => {
          throw err;
        });
    }
  });
}

setUpElectronApp();

```

Here's some code from the `renderer` file:

```ts
function onDisconnected(event: Event) {
  const device = event.target as BluetoothDevice;
  console.log(`Device ${device.name} is disconnected.`);
}

export async function deviceConnect(): Promise<DeviceInfo> {

  const device = await navigator.bluetooth.requestDevice({
    filters: [
      {
        namePrefix: "Polar Sense",
        manufacturerData: [{ companyIdentifier: 0x006b }], // For 'Polar Electro OY' company.
      },
    ],
    acceptAllDevices: false,
    optionalServices: [0x180d, 0x180f],
  });

  device.addEventListener("gattserverdisconnected", onDisconnected);


  const server = await device.gatt?.connect();

  const heartRateService = await server?.getPrimaryService(0x180d);
  const heartRate = await heartRateService?.getCharacteristic(0x2a37);

  const batteryLevelService = await server?.getPrimaryService(0x180f);
  const batteryLevel = await batteryLevelService?.getCharacteristic(0x2a19);

  return { heartRate, batteryLevel, deviceID: device.name };
}

```

There's a button in my front which triggers the above function when clicked. Constantly, getting the `Uncaught (in promise) DOMException: User cancelled the requestDevice() chooser.` error. Tried different versions of Electron as well. Still scratching my head.

Please let me know if accessing Web Bluetooth API in Electron is even possible. Using `"electron": "^17.4.7",` on a macOS Monterey (12.4).

If you can spot anything, please suggest any issues with the approach above.

**Comment by deermichel** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by maneetgoyal** [comment]
@qur786 Please create a repro.

**Comment by maneetgoyal** [comment]
https://www.electronjs.org/fiddle

**Comment by jkleinsc** [comment]
I just tested the fiddle provided on macOS Monterey and it worked properly for me.  I did have to grant bluetooth access to Electron in order for it to work.  @qur786 if you run the fiddle does it fail for you?  If it does not, can you go to System Preferences -> Privacy -> Bluetooth and see if Electron has permission to use Bluetooth?

**Comment by maneetgoyal** [comment]
@jkleinsc We are using Webpack and React internally, can they cause such an issue? Because the gist posted above worked fine in Electron Fiddle after enabling the Bluetooth permission but our main app is still failing.

**Comment by maneetgoyal** [comment]
<img width="603" alt="Screenshot 2022-06-07 at 9 09 00 AM" src="https://user-images.githubusercontent.com/25290212/172290839-b96406b1-5581-4c57-9d01-8fc3b329a232.png">

**Comment by qur786** [comment]
Here is a github gist for electron-bluetooth app with react.
We will be shortly posting a demo with webpack-react-electron as well.
The app is connecting to a nearby device, @deermichel you can test it out as well.
BTW we don't see any pop for the list of devices to pair with in both the demo. why?
https://gist.github.com/qur786/7318d0921a17406691cb2cd87030f70f

**Comment by maneetgoyal** [comment]
<img width="599" alt="Screenshot 2022-06-07 at 3 16 18 PM" src="https://user-images.githubusercontent.com/25290212/172350310-e9f26a9e-fc75-40cd-890e-0f78cd3f88c0.png">

It's working. Seems like nothing was wrong with Electron. We had to allow it access to Bluetooth via System Preferences. Sorry about the ticket, and many thanks for pointing us in the right direction.

**Comment by maneetgoyal** [comment]
@jkleinsc @deermichel Geeting the same issue in Windows 10. Any suggestions please?
