### ISSUE TITLE
What is best practice for multi threading? web workers  or new BrowserWindow hidden?

### ISSUE THREAD

**Issue by GitMurf** [electron/electron#34459]
I have not been able to get a clear generally accepted standard or best practice for when you need to run CPU intensive activity and don’t want to run on main thread to avoid locking up the app.

In 2018 @anaisbetts did an awesome talk on Electron best practices and mentioned that vscode used a clever strategy of creating a thread pool comprised of BrowserWindow renderer threads that Electron never shows the user but can be used to offload CPU intensive tasks off the main thread. Is this still a suggested strategy?

What about web workers? Is there a reason you should use workers over hidden browser window thread? Or vice versa?

Or is there another recommended approach today?

Here is the talk I referenced above: https://www.infoq.com/presentations/electron-pitfalls/

**Comment by Prinzhorn** [comment]
> Or is there another recommended approach today?

https://nodejs.org/api/worker_threads.html

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
