### ISSUE TITLE
[Bug]: File extension is missing on Windows

### ISSUE THREAD

**Issue by Sharcoux** [electron/electron#34450]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 - 10.0.19042

### What arch are you using?

x64

### Expected Behavior

When saving a file, the file type should be correctly defined and the filename should include the extension on the operating system so that the correct program is launch when double-clicking it

### Actual Behavior

The extension is missing.

![image](https://user-images.githubusercontent.com/797545/172208806-a15f11d5-5ac9-497c-a6ce-ee0ffe4d76a5.png)

Here is the code we are using:

```js
  const a = document.createElement('a')
  a.type = getMimeType(name)
  a.href = `data:${a.type || 'text/plain'};base64,${base64}`
  a.download = name
  a.click()
  ```

I'll try to add a fiddle later

### Testcase Gist URL

https://gist.github.com/c07b1efe128ba059d0fad7ebeb7a94cb

### Additional Information

This is reproducible only on Windows

**Comment by Sharcoux** [comment]
This might be a [duplicate](https://github.com/electron/electron/issues/9593) the maybe should be reopened.

**Comment by deermichel** [comment]
Hi @Sharcoux, thanks for reporting this and helping to make Electron better!

I was able to repro this on Electron 19, though an [Electron Fiddle](https://www.electronjs.org/fiddle) gist would be much appreciated, please follow up with one. As a workaround, including the file extension in the filename should work (or consider using the native save dialog as suggested in the issue you linked).

**Comment by Sharcoux** [comment]
We're on it. Thanks for your investment. The issue is that, as the type is not specified, if the user want to rename the file, they will very likely lose the extension...

[Here is the fiddle](https://gist.github.com/c07b1efe128ba059d0fad7ebeb7a94cb)
