### ISSUE TITLE
[Bug]: Linux UI freezes if user presses mouse button while modal window is opening

### ISSUE THREAD

**Issue by alilang885** [electron/electron#34460]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v19.0.3, v18.3.2, v17.4.7, v16.2.8

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu-20.04.4, CentOS 7.9.2009

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

Everything except parent of the modal window should be clickable.

### Actual Behavior

Nothing can be clicked, including system widgets (taskbar etc.) and the modal window. There is no excessive CPU usage and processes appear to be working - opening start menu or console using keyboard works. Closing the modal using escape key helps.

### Additional Information

Create an Electron app with following code:

const { app, BrowserWindow, dialog } = require("electron");
function createMainWindow() {
    let win = new BrowserWindow();
    win.loadURL("data:text/html;charset=utf-8,test");
    setTimeout(() => {
        dialog.showOpenDialog(win);
    }, 2500);
    return win;
}
app.on("ready", createMainWindow);
Start the app, put cursor over the window and press left mouse button. Hold it down until modal window appears. At this point UI is frozen. The key to reproduce this bug is to have mouse pressed (inside an Electron window) while modal is opening - this can happen even when user is just clicking.

**Comment by alilang885** [comment]
**Another sample as below:**

const { app, BrowserWindow } = require("electron");

let mainWindow = null, modalWindow = null;

function createMainWindow() {
    mainWindow = new BrowserWindow({
        width: 600,
        height: 600
    });
    mainWindow.loadURL("data:text/html;charset=utf-8,test");
}

function createModalWindow() {
    modalWindow = new BrowserWindow({
        parent: mainWindow,
        modal: true,
        width: 300,
        height: 300
    });
    modalWindow.loadURL("data:text/html;charset=utf-8,test");
}

app.on("ready", () => {
    createMainWindow();
    setTimeout(() => {
        createModalWindow();
    }, 5000);
});

Start the app, put cursor over the window and press left mouse button. Hold it down until modal window appears. At this point UI is frozen. The key to reproduce this bug is to have mouse pressed (inside an Electron window) while modal is opening.

**Comment by mbigger** [comment]
it seems a bug from more older Electron version, what's the cause ? Maybe we should add some test case to avoid.

**Comment by ckerr** [comment]
I'm able to repro this with both testcases
