### ISSUE TITLE
[Bug]: (Docs) `app.setBadgeCount` not supported by Windows, although it is?

### ISSUE THREAD

**Issue by hognevevle** [electron/electron#34476]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

In the docs, `app.setBadgeCount` is described as only being supported on Mac and Linux. It is, however, also working on Windows, and there seems to be [a Windows implementation](https://github.com/electron/electron/blob/7e59d784a0b5c922564cbc8c55f95f0e7daf6997/shell/browser/browser_win.cc#L597) of it.

Has Windows been left out for a specific reason (i.e. we should refrain from using it for some reason), or should the docs be updated?

![CleanShot 2022-06-08 at 11 15 36](https://user-images.githubusercontent.com/2721188/172580026-69aa251c-f02b-4c4d-8376-cbd20dbf0207.png)

**Comment by codebytere** [comment]
cc @jkleinsc

**Comment by jkleinsc** [comment]
@hognevevle the docs are incorrect.  Badging is available on Windows and macOS.  It is not available on Linux.

**Comment by jkleinsc** [comment]
@hognevevle wait a minute... I stand corrected.  It does work on Linux and it is undocumented on Windows because the behavior is kind of unexpected: https://github.com/electron/electron/pull/27067#discussion_r555466735

**Comment by erickzhao** [comment]
> Has Windows been left out for a specific reason (i.e. we should refrain from using it for some reason), or should the docs be updated?

I think this issue should be closed and the behaviour left undocumented as based on the comment above.
