### ISSUE TITLE
CI failure due to crashes when running CPU profiling

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#34472]
Since https://github.com/electron/electron/pull/34424 there have been node tests failing related to CPU profiling:

`sequential/test-inspector-stop-profile-after-done`
<details>
<pre>
          ---
            duration_ms: 0.509
            severity: fail
            exitcode: 1
            stack: [test] Connecting to a child Node process
[test] Testing /json/list
[err] Debugger listening on ws://127.0.0.1:41113/d6c8089c-bbb2-4089-b022-0bbf918a26b7
[err] For help, see: https://nodejs.org/en/docs/inspector
[err] 
[err] Debugger attached.
[err] 
[err] 
[err] 
[err] #
[err] # Fatal error in ../../v8/src/execution/frames.h, line 191
[err] # Debug check failed: static_cast<uintptr_t>(type) < Type::NUMBER_OF_TYPES (70364926129724 vs. 25).
[err] #
[err] #
[err] #
[err] #FailureMessage Object: 0x7ffe38da4700
[err] 
[err]  1: 0x55a5a8d74102  [/home/builduser/project/src/out/Default/electron]
[err]  2: 0x55a5a5a79db8  [/home/builduser/project/src/out/Default/electron]
[err]  3: 0x55a5a5a799b5  [/home/builduser/project/src/out/Default/electron]
[err]  4: 0x55a5a169f78e  [/home/builduser/project/src/out/Default/electron]
[err]  5: 0x55a5a169e0a9  [/home/builduser/project/src/out/Default/electron]
[err]  6: 0x55a5a16a021b  [/home/builduser/project/src/out/Default/electron]
[err]  7: 0x55a5a169ff62  [/home/builduser/project/src/out/Default/electron]
[err]  8: 0x55a5a169fe28  [/home/builduser/project/src/out/Default/electron]
[err]  9: 0x55a5a1c948f8 v8::internal::TickSample::GetStackSample(v8::internal::Isolate*, v8::RegisterState*, v8::internal::TickSample::RecordCEntryFrame, void**, unsigned long, v8::SampleInfo*, v8::StateTag*, bool) [/home/builduser/project/src/out/Default/electron]
[err] 10: 0x55a5a1c94574 v8::internal::TickSample::Init(v8::internal::Isolate*, v8::RegisterState const&, v8::internal::TickSample::RecordCEntryFrame, bool, bool, v8::base::TimeDelta) [/home/builduser/project/src/out/Default/electron]
[err] 
[err] 11: 0x55a5a1c6b4ca  [/home/builduser/project/src/out/Default/electron]
[err] 12: 0x55a5a1935133 v8::sampler::SamplerManager::DoSample(v8::RegisterState const&) [/home/builduser/project/src/out/Default/electron]
[err] 13: 0x55a5a19351f1  [/home/builduser/project/src/out/Default/electron]
[err] 14: 0x7f2919d1f3c0  [/lib/x86_64-linux-gnu/libpthread.so.0]
[err] 15: 0x55a5a1618d64 v8::internal::PerThreadAssertScope<(v8::internal::PerThreadAssertType)5, false>::~PerThreadAssertScope() [/home/builduser/project/src/out/Default/electron]
[err] 16: 0x55a5a1480f53  [/home/builduser/project/src/out/Default/electron]
[err] 17: 0x55a5a1715e8d  [/home/builduser/project/src/out/Default/electron]
[err] 
[err] 18: 0x55a5a1715816  [/home/builduser/project/src/out/Default/electron]
[err] 19: 0x55a5a1bb775a  [/home/builduser/project/src/out/Default/electron]
[err] 20: 0x55a5a1bbc88f v8::internal::SharedFunctionInfo::StartPosition() const [/home/builduser/project/src/out/Default/electron]
[err] 21: 0x55a5a15aca3a v8::internal::Compiler::LogFunctionCompilation(v8::internal::Isolate*, v8::internal::LogEventListener::LogEventsAndTags, v8::internal::Handle<v8::internal::Script>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::FeedbackVector>, v8::internal::Handle<v8::internal::AbstractCode>, v8::internal::CodeKind, double) [/home/builduser/project/src/out/Default/electron]
[err] 
[err] 22: 0x55a5a1486caf  [/home/builduser/project/src/out/Default/electron]
[err] 23: 0x55a5a148565b  [/home/builduser/project/src/out/Default/electron]
[err] 24: 0x55a5a16e649f v8::internal::StackGuard::HandleInterrupts() [/home/builduser/project/src/out/Default/electron]
[err] 25: 0x55a5a1ceeabc  [/home/builduser/project/src/out/Default/electron]
[err] 
[err] 26: 0x55a5a2196596 v8::internal::RegExpMacroAssemblerX64::CheckStackGuardState(unsigned long*, unsigned long, unsigned long) [/home/builduser/project/src/out/Default/electron]
[err] 27: 0x55a5200af98f 
[err] 
Mismatched noop function calls. Expected exactly 1, actual 0.
    at Proxy.mustCall (/home/builduser/project/src/third_party/electron_node/test/common/index.js:369:10)
    at Object.<anonymous> (/home/builduser/project/src/third_party/electron_node/test/sequential/test-inspector-stop-profile-after-done.js:30:24)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
[err] child process crashed, signal SIGTRAP
          ...
</pre>
</details>

`sequential/test-cpu-prof-dir-absolute`
<details>
<pre>
          ---
            duration_ms: 0.508
            severity: fail
            exitcode: 1
            stack: Dispatching message { "id": 1, "method": "Profiler.enable" }
Receive CPU profile message
{"id":1,"result":{}}
Dispatching message { "id": 2, "method": "Profiler.start" }
Receive CPU profile message
{"id":2,"result":{}}
Dispatching message { "id": 3, "method": "Profiler.setSamplingInterval", "params": { "interval": 50 } }
Receive CPU profile message
{"id":3,"error":{"code":-32000,"message":"Cannot change sampling interval when profiling."}}

 1: 0x55a7d17b2102  [/home/builduser/project/src/out/Default/electron]
 2: 0x55a7ce4b7db8  [/home/builduser/project/src/out/Default/electron]
 3: 0x55a7ce4b79b5  [/home/builduser/project/src/out/Default/electron]
 4: 0x55a7ca0dd78e  [/home/builduser/project/src/out/Default/electron]
 5: 0x55a7ca0dc0a9  [/home/builduser/project/src/out/Default/electron]
 6: 0x55a7ca0de21b  [/home/builduser/project/src/out/Default/electron]
 7: 0x55a7ca0ddf62  [/home/builduser/project/src/out/Default/electron]
 8: 0x55a7ca0dde28  [/home/builduser/project/src/out/Default/electron]
 9: 0x55a7ca6d28f8 v8::internal::TickSample::GetStackSample(v8::internal::Isolate*, v8::RegisterState*, v8::internal::TickSample::RecordCEntryFrame, void**, unsigned long, v8::SampleInfo*, v8::StateTag*, bool) [/home/builduser/project/src/out/Default/electron]
10: 0x55a7ca6d2574 v8::internal::TickSample::Init(v8::internal::Isolate*, v8::RegisterState const&, v8::internal::TickSample::RecordCEntryFrame, bool, bool, v8::base::TimeDelta) [/home/builduser/project/src/out/Default/electron]
11: 0x55a7ca6a94ca  [/home/builduser/project/src/out/Default/electron]
12: 0x55a7ca373133 v8::sampler::SamplerManager::DoSample(v8::RegisterState const&) [/home/builduser/project/src/out/Default/electron]
13: 0x55a7ca3731f1  [/home/builduser/project/src/out/Default/electron]
14: 0x7fe8b03293c0  [/lib/x86_64-linux-gnu/libpthread.so.0]
15: 0x55a7c9ec481e  [/home/builduser/project/src/out/Default/electron]
16: 0x55a7c9ec365b  [/home/builduser/project/src/out/Default/electron]
17: 0x55a7ca12449f v8::internal::StackGuard::HandleInterrupts() [/home/builduser/project/src/out/Default/electron]
18: 0x55a7ca72cabc  [/home/builduser/project/src/out/Default/electron]
19: 0x55a7cabd4596 v8::internal::RegExpMacroAssemblerX64::CheckStackGuardState(unsigned long*, unsigned long, unsigned long) [/home/builduser/project/src/out/Default/electron]
20: 0x55a7400af98f 

node:assert:123
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

null !== 0

    at Object.<anonymous> (/home/builduser/project/src/third_party/electron_node/test/sequential/test-cpu-prof-dir-absolute.js:40:10)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: 0,
  operator: 'strictEqual'
}
          ...
</pre>
</details>

Began here: https://chromium.googlesource.com/chromium/src/+log/102.0.4999.0..103.0.5046.0?n=10000&pretty=full

**Comment by nornagon** [comment]
Related to #34575?

**Comment by jkleinsc** [comment]
Closing as these tests are no longer failing
