### ISSUE TITLE
[Feature Request]: Glyph badges (Windows)

### ISSUE THREAD

**Issue by hognevevle** [electron/electron#34475]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

On Mac, you have the option to set the badge to a non-numeric value such as `'•'` using `app.dock.setBadge('•')`.

On Windows, however, you are limited to a numeric value, using `app.setBadgeCount(<number>);`. Therefore, I would like to suggest the support of Glyph icons for the Windows badge, as described [here](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/badges#glyph-badges). I'm not sure it would be possible to support on Electron, however, but others will know better than me 😄 

### Proposed Solution

For Windows we could have for example `app.setBadgeGlyph("alarm");`.

### Alternatives Considered

While one could do as described in #24051, the Glyph support would make the app feel more Windows native, as more Windows apps are using them.

**Comment by MarshallOfSound** [comment]
Glyphs are unfortunately not easily accessibly to win32 or winrt apps.  The current `setBadgeCount` implementation also uses a custom renderer not the native windows API (in order to support a larger range of windows versions)
