### ISSUE TITLE
[Bug]: Version 12-17 cannot trigger reopen the app after double clicked the desktop icon when app (already running) is under minimised

### ISSUE THREAD

**Issue by mx51damon** [electron/electron#34482]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

ia32

### Last Known Working Electron version

11.5.0

### Expected Behavior

Able to trigger reopen the app after double clicked the desktop icon when app (already running) is under minimised

### Actual Behavior

cannot trigger reopen the app after double clicked the desktop icon when app (already running) is under minimised

### Additional Information

Please help, this is very urgent. 

Mega thanks for the community.

**Comment by deermichel** [comment]
Thanks for reporting this and helping to make Electron better!

From your description, I'd suggest to check your single instance handling code with the example [from the docs](https://www.electronjs.org/docs/latest/api/app#apprequestsingleinstancelockadditionaldata).

If the issue persists and is believed to be in Electron itself, please provide a standalone testcase with only the code necessary to reproduce the issue. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com/) that Electron maintainers can use.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by mx51damon** [comment]
Hi @codebytere , finally I got the answer, the issue was triggered after using electron-build version 23.x.x, if I downgrade to version 22.x.x, the issue no longer exists.

Sorry to bother you ~
