### ISSUE TITLE
[Bug]: file input control does not remember last selected directory

### ISSUE THREAD

**Issue by bruceauyeung** [electron/electron#34483]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.3

### What operating system are you using?

Windows

### Operating System Version

windows 7 x64, windows 10 x64, linux 64(a derived distro based on LXQT)

### What arch are you using?

x64

### Last Known Working Electron version

13.2.0

### Expected Behavior

file input control can remember the last selected directory

### Actual Behavior

the save dialog opened by file input control always select user's Pictures directory, no matter what the file extension is.
NOTE: `dialog.showSaveDialog` can remember the last selected directory correctly.

### Testcase Gist URL

no testcase gist

### Additional Information

none

**Comment by codebytere** [comment]
I added 

```
<input type="file" name="file">
```

to the default Fiddle and cannot reproduce this on Windows. It consistently opens to the last selected directory. In order to proceed, we'll need more informaton.

**Comment by bruceauyeung** [comment]
~~~
      if (!paths.empty()) {
        browser_context->prefs()->SetFilePath(kSelectFileLastDirectory,
                                              paths[0].DirName());
      }
~~~
where is `kSelectFileLastDirectory` stored? 
does `file input control` and `dialog.showSaveDialog` store `kSelectFileLastDirectory` into same place ?
@codebytere

**Comment by ckerr** [comment]
@bruceauyeung to clarify, are you asking for the previous directory to be remembered between sessions, e.g. after the app is exited and restarted? Or are you asking for it to remember the previous directory in the current session?

**Comment by bruceauyeung** [comment]
@ckerr current session, without exit / restart
