### ISSUE TITLE
[Bug]: webview tag inside electron and react project needs to have strings passed to boolean props

### ISSUE THREAD

**Issue by Nicodemos234** [electron/electron#34489]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Expected Behavior

Pass the right type (boolean), for props like allowpopups, on webview tag inside a React component, and work as expected

Documentation example of use:
![image](https://user-images.githubusercontent.com/35513987/172874500-891647b6-3f19-47aa-9bec-be4f46b443cd.png)

### Actual Behavior

The prop only works if we pass a string like `<webview src="https://www.github.com" allowpopups="true" />`, but if we pass `<webview src="https://github.com" allowpopups />` doesn't work, is like the attribute was not passed

### Additional Information

A React + Electron project example that this is happening https://github.com/RibeiroFMatheus/test-electron-webview-popups

Screenshot of error that I had passing true to the prop:
![image](https://user-images.githubusercontent.com/35513987/172874234-95faaa63-61f3-46a6-a06b-dc3707aeaa00.png)

**Comment by codebytere** [comment]
See https://github.com/electron/electron/issues/6046
