### ISSUE TITLE
[Feature Request]: Support for sending shallow copy of objects via IPC

### ISSUE THREAD

**Issue by wasitshafi** [electron/electron#34497]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I have been trying to send the shallow copy of the object from the renderer process(assume it Child Window A) -> the main process -> some other renderer process (Assume it Child Window B) so that I can use the actual reference of the object(for my case it the server connection, not some simple data), but I got to know from docs that args we pass uses Structured Clone Algorithm which also limits us to what we can send (assume Custom Class Instances having methods as well or a function inside JS object, etc, which we can't send now if we try to send it, we will get the error 'An object could not be cloned' refer below screenshot).
I have already tried to send/receive the custom class instances/object includes functions using  `ipcRenderer.send(),ipcRenderer.sendSync(),ipcRenderer.sendTo(),ipcRenderer.invoke()`
all of them seems to use Structured Clone Algorithm which limits use to only send deep copies via IPC also may result in data loss (even if we try to use JSON.stringify()/JSON.parse() as we know `console.log(JSON.stringify({id:101, foo: ()=>{console.log('this is non-clonable, will lose this function!!')}})) // oputput :: {"id":101})`.

I have already gone through the latest electron docs, electron GitHub issue tracker, StackOverflow, etc didn't found any fix for it till now, any kind of guidance will be of great help to me. Thanks in Advance

Docs: https://www.electronjs.org/docs/latest/api/ipc-renderer#ipcrenderersendchannel-args
Similar Issue #26338

PS: Why do I need to send an actual reference, we have multiple Child windows and for each window, we have a separate root store(using [MobX-State-Tree](https://mobx-state-tree.js.org/intro/welcome)) and in the main root store we have server connection object which we have to pass to different child windows.

![Screenshot 2022-06-10 at 1 59 00 PM](https://user-images.githubusercontent.com/32488541/173024776-fd9ac994-9cee-4b11-8f06-40667ebb208e.png)
 )

### Proposed Solution

Their should be support for passing shallow copies/actual references via IPC.

### Alternatives Considered

No Response.

**Comment by MarshallOfSound** [comment]
> Their should be support for passing shallow copies/actual references via IPC.

This is not technically possible.  These objects live in completely different processes, you couldn't share a JS object across them even if we wanted to 🤷 .  You can simulate things / keep state in sync via custom `change` IPC messages 🤷 

As an example (although not actively used anymore) https://www.npmjs.com/package/redux-electron-ipc

**Comment by wasitshafi** [comment]
@MarshallOfSound Okay, I will look forward to making them in sync(not sure now will it work for my use case), anyways thanks for the update
