### ISSUE TITLE
jQuery issue on render side

### ISSUE THREAD

**Issue by deecoolist** [electron/electron#345]
everytime loading jquery from render side (any.html) via dom `<script src="jquery.js"></script>` resulting _"Uncaught ReferenceError: jQuery is not defined"_ or _"Uncaught Error: ... requires jQuery"_;

but if I load jQuery via require:

``` html
<script>
var $ = jQuery = require('jquery'); // as node_modules
/*
 * or localy load.
 * var $ = jQuery = require('./jquery');
 */
</script>
```

(on every page) It was fine!, but module.exports get polluted by jQuery's methods

so every page either local or external site whom use jQuery would fail to properly load since jQuery header:

``` javascript
(function( global, factory ) {

    if ( typeof module === "object" && typeof module.exports === "object" ) {
        // For CommonJS and CommonJS-like environments where a proper window is present,
        // execute the factory and get jQuery
        // For environments that do not inherently posses a window with a document
        // (such as Node.js), expose a jQuery-making factory as module.exports
        // This accentuates the need for the creation of a real window
        // e.g. var jQuery = require("jquery")(window);
        // See ticket #14549 for more info
        module.exports = global.document ?
            factory( global, true ) :
            function( w ) {
                if ( !w.document ) {
                    throw new Error( "jQuery requires a window with a document" );
                }
                return factory( w );
            };
    } else {
        factory( global );
    }

// Pass this if window is not defined yet
}(typeof window !== "undefined" ? window : this, function( window, noGlobal ) {
```

are they any solution for this kind of matter?
Thanks.

**Comment by gliurn** [comment]
@deecoolist  have you found a solution to make JQuery a global variable? it would help me for my app, i got the same issue with JQuery and i need it to load a website on a webview

**Comment by DogsForArms** [comment]
Thanks very much for this quick solution.

**Comment by fountainhead** [comment]
@deecoolist what was the solution to this? i need the same functionality like you've described

**Comment by rigelk** [comment]
Just for reference @fountainhead , it did the trick for me : 
```javascript
<script type="text/javascript" src="js/jquery.min.js" onload="window.$ = window.jQuery = module.exports;"></script>
```

**Comment by eric-naguras** [comment]
Thanks rigelk.
This worked for me.
My app works on OSX but would give jquery module not found errors on Windows.
Your solution solved that.

**Comment by raghav-khunger** [comment]
Hi,

Using the following code on external page:

"<script type="text/javascript" src="js/jquery.min.js" onload="window.$ = window.jQuery = module.exports;"></script>"

did add the jQuery object but with the value of module.exports which is an object. 

What about the core jQuery file code?

I can't access any functions which jQuery exposes after that like jQuery.fn etc

Can anyone suggest any solution for adding jQuery.js on an external site loaded in Electron via:

  mainWindow.loadUrl('http://mysite.com/external.html');

**Comment by thonatos** [comment]
I use this  in script :

var $ = require(path.join(process.cwd(), 'frontend/assets/vendors/jquery/dist/jquery'));

**Comment by mendo-** [comment]
I found this worked to load jquery in window of an external website.

main.js

`mainWindow = new BrowserWindow({`
`    webPreferences: {`
`      nodeIntegration: true,`
`      webSecurity: true,`
`      preload: path.resolve(path.join(__dirname, 'path/to/preload.js'))`
`    },`
`  	width: 1400,`
`  	height: 1200`
`  });`

preload.js

`document.addEventListener("DOMNodeInserted", function(event) {`
`    if (!!window && !(!!window.$)) {`
`        window.$ = window.jQuery = require('path/to/jquery.js');`
`    }`
`});`

**Comment by Bronts** [comment]
@rigelk I use your solution but I modified like this
```
<script type="text/javascript" src="js/jquery.min.js" onload="window.$ = window.jQuery;"></script>
```

wiht `module.export` it will notice module is not defined

Thanks for you solution.

This works fine for loading remote url with jQurey.

**Comment by AizazAhmad** [comment]
Thanks @jsonnull. i was stuck to load custom jquery. it takes mine 2 days. after that i got ur solution: $ = jQuery = module.exports;
