### ISSUE TITLE
[Feature Request]: Add ipcRenderer.sendToHostSync

### ISSUE THREAD

**Issue by FlysoftBeta** [electron/electron#34506]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to send message synchronously to host in preload scripts, and wait for the return value

### Proposed Solution

Maybe we can pause the thread. And when it returns, resume the thread.

### Alternatives Considered

Well, I don't have another solution...

**Comment by miniak** [comment]
Synchronous IPC between renderers could cause a deadlock and it's also a really bad idea. We are not going to do this.
