### ISSUE TITLE
[Bug]: The WebviewTag is not exported from electron.d.ts

### ISSUE THREAD

**Issue by pietrovismara** [electron/electron#34504]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

Windows

### Operating System Version

Microsoft Windows 11 Pro

### What arch are you using?

x64

### Expected Behavior

`import type { WebviewTag } from 'electron'` should work without errors.

### Actual Behavior

I get the error `Module '"electron"' has no exported member 'WebviewTag'.`

### Additional Information

Inspecting the `electron.d.ts` in my node_modules folder makes the issue evident: the `WebviewTag` interface is defined but not exported.

**Comment by pietrovismara** [comment]
Workaround:
'''
type WebviewTag = ReturnType<Document["createElement"]>;
```

**Comment by Sharcoux** [comment]
Wait, why is this closed? This not solved.

**Comment by pietrovismara** [comment]
@Sharcoux I closed it as it looks like it was intentional to not export `WebViewTag` directly and since I found a workaround I'm ok with it. `Document` is available globally in the renderer process, if you need it in the main process and have a separate `tsconfig.json` for main then add `"dom"` to its `compilerOptions.lib` property.

**Comment by Sharcoux** [comment]
The only Document that returns the correct types is here:

![image](https://user-images.githubusercontent.com/797545/176443767-b35b923f-1d99-445b-a90d-df17e27ad92b.png)

The issue is that it is not exported either...

**Comment by Sharcoux** [comment]
The Document from dom doesn't export WebviewTag. How did you do that?

**Comment by npmrun** [comment]
```
// 1. 
type WebviewTag = ReturnType<Document["createElement"]>;

// 2.
const fn = () => document.createElement("webview")
type WebviewTag = ReturnType<typeof fn>

// 3. 
type WebviewTag = Electron.WebviewTag
```

**Comment by Sharcoux** [comment]
What version of electron are you running @npmrun ? And how do you import `Electron` in your last example for instance?

![image](https://user-images.githubusercontent.com/797545/185462984-c3aa6dbf-59c0-41f2-bef7-15b9e5eb4fa5.png)

**Comment by npmrun** [comment]
```
"electron": "19.0.11",
```
I use it in a `d.ts`
```
/// <reference types="electron" />
type WebviewTag = Electron.WebviewTag
```
[source code](https://github.com/npmrun/rush-desktop/blob/develop/packages/common/global.d.ts)

**Comment by npmrun** [comment]
@Sharcoux 
```
"electron": "19.0.11",
```
I use it in a `d.ts`
```
/// <reference types="electron" />
type WebviewTag = Electron.WebviewTag
```
[source code](https://github.com/npmrun/rush-desktop/blob/develop/packages/common/global.d.ts)

**Comment by Sharcoux** [comment]
Ah ok, that's because you're loading the types with a triple dash directive. Ok, will do for now. But that's definitely not the proper way to solve this issue. Thanks for you help.
