### ISSUE TITLE
[Build Issue] error: the requested upstream branch 'origin/main' does not exist

### ISSUE THREAD

**Issue by bobajeff** [electron/electron#34509]
I was following the build instructions [here](https://www.electronjs.org/docs/latest/development/build-instructions-gn#getting-the-code). Only instead of `gclient sync --with_branch_heads --with_tags` I did `gclient sync --no-history` (in order to save a lot of time and harddrive space).

However when I got to the [A note on pulling/pushing](https://www.electronjs.org/docs/latest/development/build-instructions-gn#a-note-on-pullingpushing) section and did `git branch --set-upstream-to=origin/main`. I got:
 ```console
error: the requested upstream branch 'origin/main' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint: 
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.
```
I assume this has to do with me not fetching the HEAD of the repository. So Is there a way I can get the HEAD for just this repository without having to do `gclient sync --with_branch_heads`?

This is my git reflog output:
```git
bd81ae0 (grafted, HEAD -> main) HEAD@{0}: checkout: moving from main to main
bd81ae0 (grafted, HEAD -> main) HEAD@{1}: checkout: moving from bd81ae08acf2a2ebb9f6ca7c17590b472ddae789 to main
bd81ae0 (grafted, HEAD -> main) HEAD@{2}: checkout: moving from main to refs/remotes/origin/main
bd81ae0 (grafted, HEAD -> main) HEAD@{3}: clone: from https://github.com/electron/electron
```

Also is the a reason we need to do `git pull` before `gclient sync`? I thought `gclient sync` took care of that too.

**Comment by MarshallOfSound** [comment]
Per that doc I'd recommend just using [`electron-build-tools`](https://github.com/electron/build-tools).

`--no-history` as a flag doesn't work very well with projects that use gclient like we do (read - it does not work at all)

**Comment by MarshallOfSound** [comment]
> So, do you think it was the --no-history flag that's causing the issue with not being able to set the upstream branch?

All I know is that `--no-history` doesn't work super well (if at all) especially when combined with the `GIT_CACHE` flag which I assume you're also using

> Also, I wonder why the docs don't mention build-tools.

They do, it's at the very top of the file you linked

**Comment by bobajeff** [comment]
Oh yeah. 😅 I do remember seeing that now. I think I just skipped it over when I saw the more familiar (to me) `depot tools` instructions. Actually I skiped "Setting up the git cache" as wasn't trying to have _"multiple directories checked out to difference branches"_ like it's suggested use not sure what the point of that would be really.
