### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ffongmdsp** [electron/electron#34515]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.4

### What operating system are you using?

macOS

### Operating System Version

Monterey 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Text Alignment of 'message', 'detail' in dialog.showMessageBoxSync() is consistent between Windows and MacOS.

### Actual Behavior

Text is left-aligned on Windows but center-aligned in MacOS.

**Comment by codebytere** [comment]
@ffongmdsp this is a platform limitation - they are displayed the way the system does through its own dialog handlers. See https://docs.microsoft.com/en-us/windows/win32/api/commctrl/ns-commctrl-taskdialogconfig for example.

**Comment by ffongmdsp** [comment]
I see. How about the MacOS? Could be it made left-aligned instead of centered? I find it difficult to format the details (such as bullet-list) if the text alignment is center.
