### ISSUE TITLE
[Bug]: setSize not work as expected when resizable tag is false

### ISSUE THREAD

**Issue by Particaly** [electron/electron#34512]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18, 19

### What operating system are you using?

Windows

### Operating System Version

win 11

### What arch are you using?

x64

### Expected Behavior

When resizable is false, use win Setsize() should still take effect

### Actual Behavior

When resizable is false, use win Setsize() reducing the window size will fail

### Testcase Gist URL

https://gist.github.com/Particaly/500aad64e8d77c0c79a5ded12435962f

**Comment by pushkin-** [comment]
weird, I could repro your gist on Windows as far back as 3, but then I stopped being able to  (even on Electron 19), and the window resizes. I deleted your preload/renderer/index file, and even when I add it back, I could get the window to resize.
