### ISSUE TITLE
[Bug]: Some electronprograms below Electron13 won't work with NVIDIA driver

### ISSUE THREAD

**Issue by TheRealOne78** [electron/electron#34522]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Electron 12 or older

### What operating system are you using?

Other Linux

### Operating System Version

5.18.1-gentoo-r1 custom kernel, gentoo release 2.8

### What arch are you using?

x64

### Last Known Working Electron version

Most likely Electron 13

### Expected Behavior

To execute the programs correctly

### Actual Behavior

Programs end up crashing with these error messages:
`[10156:0613/110912.105163:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.`

### Additional Information

https://github.com/NVIDIA/open-gpu-kernel-modules/issues/302 
On what @aaronp24 described,
*It sounds like the right fix here is for applications to update to Electron 13, or to somehow update Electron 12 to have the same sandboxing configuration as Electron 13. I'm not particularly familiar with Electron so hopefully Electron 12 can be updated in one place rather than having to update a separate copy embedded in every application...*

**Comment by codebytere** [comment]
Electron 12 is no longer supported, so the correct fix here is to update to a [supported version](https://www.electronjs.org/docs/latest/tutorial/support#supported-versions).
