### ISSUE TITLE
[Bug]: Unexpected CertVerifyProcBuiltin stderr with self-signed certs after upgrading

### ISSUE THREAD

**Issue by flotwig** [electron/electron#34583]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.0. Issue appeared starting with 17.0.0-alpha.4 and exists in latest (19.0.4)

### What operating system are you using?

Ubuntu

### Operating System Version

I am on Ubuntu, but users have reported this with other OS's.

### What arch are you using?

x64

### Last Known Working Electron version

17.0.0-alpha.3

### Expected Behavior

We are passing `--ignore-certificate-errors` to Electron in Cypress to suppress cert errors for our self-signed HTTPS proxy. This worked fine, and still works fine in new versions of Electron. But after upgrading our Electron version to 18.3.0, users began getting confusing errors in the stderr.

GH Discussion thread: https://github.com/cypress-io/cypress/discussions/22128

Sample of unexpected stderr:

> [3801:0606/152837.383892:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for www.googletagmanager.com failed:
> ----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=www.googletagmanager.com) -----
> ERROR: No matching issuer found
> [3801:0606/152837.390166:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for cdn.segment.io failed:
> ----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=cdn.segment.io) -----
> ERROR: No matching issuer found
> [3801:0606/152837.847154:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for www.google-analytics.com failed:
> ----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=www.google-analytics.com) -----
> ERROR: No matching issuer found
> [3801:0606/152838.158565:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for rum.browser-intake-datadoghq.com failed:
> ----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=rum.browser-intake-datadoghq.com) -----
> ERROR: No matching issuer found

I isolated the issue to a change between 17.0.0-alpha.3 and 17.0.0-alpha.4. Based on the 17.0.0-alpha.4 [changelog](https://releases.electronjs.org/release/v17.0.0-alpha.4) it seems that [this Chromium bump](https://github.com/electron/electron/pull/31982) is the most likely culprit.

I thought this could be related since it touches this exact area, but it doesn't appear to be in the changelog: https://github.com/electron/electron/pull/33204

### Actual Behavior

I would expect `--ignore-certificate-errors` to ignore certificate errors fully, so no excess stderr produced because of SSL errors.

### Testcase Gist URL

Repro: https://github.com/flotwig/electron-cert-verify-repro

### Additional Information

Our current workaround is to filter the stderr and ignore these lines: https://github.com/cypress-io/cypress/pull/22342

**Comment by flotwig** [comment]
#31982 does seem to touch the same patches #33204 touched, so maybe that's how there was a regression with that Chromium bump.

**Comment by vinhnq-1081** [comment]
I have the same issue
Help me give the solution, please :bow: 
>[3801:0606/152837.383892:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for [www.googletagmanager.com](http://www.googletagmanager.com/) failed:
----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=www.googletagmanager.com) -----
ERROR: No matching issuer found

**Comment by hishammalik** [comment]
bump test to be happening in 21.0.2 and 21.0.4

**Comment by codebytere** [comment]
Looks like https://github.com/electron/electron/commit/87c183df6a6b758ace3097eeb176c2643398e29d#diff-9f0f1bc931e7ccccf67980972e2f41ba1bb5f08b10f36631a584a7dd532cabba also created some related issues.

**Comment by rfricz** [comment]
Still happening in Electron 27.1.3. The docs state that calling `callback(0)` in my `ses.setCertificateVerifyProc` proc "Indicates success and disables Certificate Transparency verification", yet stderr is still polluted with `CertVerifyProcBuiltin` errors that I intentionally ignored.

**Comment by yizhi166** [comment]
bump, still happen, can someone help me take a look at this issue?
![image](https://github.com/electron/electron/assets/138545702/b64674c0-19df-4c4d-9baf-8fa57b94e1d9)

**Comment by flotwig** [comment]
@codebytere looks like this is still impacting users. Can it be reopened?

**Comment by openarun** [comment]
This is an issue still with electron version 21.3.3 .

**Comment by KeaneWong** [comment]
Bump

**Comment by WLW-CHN** [comment]
still with electron version 31.2.1

**Comment by WLW-CHN** [comment]
Electron version 31.2.1 still has this issue
