### ISSUE TITLE
[Feature Request]:  cookie can by rewrite "file//" => "http"

### ISSUE THREAD

**Issue by Kelier** [electron/electron#34608]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

<img width="178" alt="image" src="https://user-images.githubusercontent.com/16694478/174241710-ada49078-b27a-45d8-ab77-4f8ae551a5ef.png">

when i try `loadfile(index.html)`

then i try `beforeRequest` callback `redirectURL: 'myapi'`

i can see the api be redirect, but the cookie don't transfer rightly

### Proposed Solution

can you provide a cookie inject function rewrite protocol with 'file'

### Alternatives Considered

or provide a way to save local cookie , then rewrite request header

### Additional Information

thanks a lot!

**Comment by MarshallOfSound** [comment]
As of https://github.com/electron/electron/pull/35357 redirecting from `file:` to `https?:` isn't supported
