### ISSUE TITLE
[Bug]: When multiple Windows of the same instance are opened, the main process 'ipcmain. on' repeats

### ISSUE THREAD

**Issue by yyccQQu** [electron/electron#34618]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

electronVersion: 9.4.4

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

Each window triggered with ipcRenderer only needs to trigger the event monitored by 'ipcMain. on' once__

### Actual Behavior

When each window is triggered with ipcRenderer, the number of times' ipcmain. on 'is triggered is the number of Windows

### Testcase Gist URL

https://github.com/cc-electron/electron-test

### Additional Information

at renderer code

```
let { dialog, app } = remote;
ipcRenderer.send("close-win", "111");

```
at main code

```
ipcMain.on("win-close", (e, arg) => {
        console.log("win-closes: ", arg);
})
```
when i use this method create more windows, There are four Windows, and as soon as the `close-win` of one of them is triggered, the `close-win` receive of the main process is repeated four times

```
function createWindow(mainWindow, devPath = "", prodPath = "index.html", winNum) {
   winNum++
   mainWindow = windowManager.createNew(
        multipleName,
        multipleName,
        winURL,
        false,
        winObj,
        isDev
    );
  mainWindow.create();
}


let mainWindowF;
createWindow(mainWindowF)
```

Result
the main code result is 
```
win-closes:  1
win-closes:  1
win-closes:  2
win-closes:  2
```
But I only want to trigger it once.

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you’re still experiencing this issue in Electron 17.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.
