### ISSUE TITLE
[Feature Request]: Add mouse event to 'before-input-event' event in webContents

### ISSUE THREAD

**Issue by Shintarot** [electron/electron#34616]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I can't find a way to handle click events in the Renderer from the Main process.

### Proposed Solution

The 'before-input-event' event in webContents currently fires only for keyboard events, but is it possible to include click events here, or have a dedicated event handler like 'before-click-event'?

### Alternatives Considered

Of course, it is possible to combine document.addEventListener and IPC in the Renderer, but I don't want to rely on webContents.executeJavaScript whenever possible.

**Comment by TheOjasSingh** [comment]
Can you elaborate on the issue?

**Comment by Shintarot** [comment]
Looking at the documentation for `BrowserWindow`, `BrowserView`, and `webContents`, it appears that no API is provided to detect and handle click events on the `renderer` from the `main` process. (Even though keyboard events are available.)

Why I want such an API is to provide operations such as `ctrl + click` on the unreliable `renderer` (e.g., web sources).

An alternative is to set `document.addEventListener('click', ...)` but it's not appropriate in the above case because it can be overridden on the `Renderer`.

Is it possible to add, for example, `'before-click-event'` to `webContents`?

```
// Suggestions for 'before-click-event' event handler arguments
event: Electron.Event;
keys: {
    // Like PointerEvent or MouseEvent in web, including key input information such as altKey, ctrlKey, etc.
    meta: boolean;
    alt: boolean;
    control: boolean;
    shift: boolean;
    ...
};
// If data like Electron.ContextMenuParams is provided, various operations can be realized by shortcut key + click.
params: Electron.ContextMenuParams;
```

**Comment by TheOjasSingh** [comment]
Thank you for providing a explanation.

**Comment by codebytere** [comment]
Closing as i've determined it's not something we can accomplish within the bounds of WebContents as it stands.

**Comment by pfmjs** [comment]
from my knowledge of electron, you can detect if the cursor hovers/clicks over the renderer, call a function through IPC to tell main process what to do, i myself have used the technique to avoid bad layering of electron:
Renderer Process:
```javascript
const interactiveElements = document.querySelector('#parent');

interactiveElements.addEventListener("click", () => {
    window.electronAPI.handleClick();
}
```

preload:
```javascript
import { ipcRenderer, contextBridge } from "electron";

contextBridge.exposeInMainWorld('electronAPI', {
    handleClick: () => ipcRenderer.send("click-detected");
} 
```

Main Process:
```javascript
ipcMain.on('click-detected', () => {
    console.log("Click Detected")
})
```

**Comment by pfmjs** [comment]
i researched and found that they have similar event handler called `before-mouse-event`, you could try that
[mentioned here](https://www.electronjs.org/blog/electron-37-0#new-features-and-improvements), but its only available for views like WebContentsView, View, BrowserView, BrowserWindow and etc.
