### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Sirros** [electron/electron#34613]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

window

### What arch are you using?

x64

### Expected Behavior

Chinese version of the document was translated incorrectly
![image](https://user-images.githubusercontent.com/34034866/174283976-a668bcfe-1e55-4cf9-922c-539ba4b7cd56.png)

### Actual Behavior

Chinese version of the document was translated incorrectly
![image](https://user-images.githubusercontent.com/34034866/174283990-4b71922a-48fc-4bb2-b72f-10f10422cb23.png)

**Comment by SupremeLeader42** [comment]
e

**Comment by codebytere** [comment]
Please open this issue on https://github.com/electron/electronjs.org-new
