### ISSUE TITLE
[Bug]: Please reopen https://github.com/electron/electron/issues/34504

### ISSUE THREAD

**Issue by Sharcoux** [electron/electron#34664]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

whatever

### What arch are you using?

x64

### Expected Behavior

import type { WebviewTag } from 'electron' should work without errors.

### Actual Behavior

I get the error Module '"electron"' has no exported member 'WebviewTag'.

### Additional Information

Inspecting the electron.d.ts in my node_modules folder makes the issue evident: the WebviewTag interface is defined but not exported.

**Comment by MarshallOfSound** [comment]
Opening issues asking us to re-open existing issues is not an appropriate way to engage on our issue tracked

**Comment by Sharcoux** [comment]
I accept that, but I don't know what is the proper way to drag attention to closed issues. Should I duplicate the ticket? Is there any chance that someone would check closed tickets to see if new stuff might be happening there?
