### ISSUE TITLE
[Bug]: Please fix the webview docs

### ISSUE THREAD

**Issue by Michael-py001** [electron/electron#34678]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

13.0.0

### Expected Behavior

When I update electron from 13.0.0 to 19.0.5 ，webview's new-window event will not be triggered when I click a new url.
I searched a lot of docs and issues to find this answer . I finally found some discussions in #31117。
In docs [https://www.electronjs.org/docs/latest/api/web-contents#event-new-window-deprecated](https://www.electronjs.org/docs/latest/api/web-contents#event-new-window-deprecated)
Event: 'new-window' has been deprecated, but there is no any  notices or declarations in  webview docs: [https://www.electronjs.org/docs/latest/api/webview-tag](https://www.electronjs.org/docs/latest/api/webview-tag) , this is so confused me. Please fix the docs.

### Actual Behavior

 Please fix the webview docs, add some declarations about event: 'new-window' has been deprecated.

**Comment by avinashji1302** [comment]
hey I would like to work on this project can I get started?

**Comment by AniruddhaSoni** [comment]
Hey, I would like to work on this project, how can I start?

**Comment by Prajjawal12** [comment]
I would like to work on this issue, please assign me this issue to resolve.

**Comment by Baidaly** [comment]
@Michael-py001  I believe the issue is resolved as the event has been removed and documentation updated.

**Comment by jenniferteaa** [comment]
Hello,
I would like to contribute to this project, Kindly let me know if i can get started

**Comment by sagar1621** [comment]
This

> Hello, I would like to contribute to this project, Kindly let me know if i can get started

The issue is closed already and updated i think
