### ISSUE TITLE
Is there any demo code or document about using  SMJobBless in an Electron project?

### ISSUE THREAD

**Issue by bincxz** [electron/electron#34679]
Hi,guys
I'm finding a way to elevate the privilege of an Electron based Mac App.
The recommanded way from apple is using the SMJobBless api to register an XPC service in launchd. 
And there is so many demo project on the Internet about how to register such an service by a native xcode project.
But I can't find a way about implement this in an Electron project.

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
