### ISSUE TITLE
[Bug]electron app crash when startup

### ISSUE THREAD

**Issue by ChengLin-Zhou** [electron/electron#34681]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

2.0.18

### What operating system are you using?

macOS

### Operating System Version

Mojave10.14.6

### What arch are you using?

x64

### Expected Behavior

Normal startup

### Actual Behavior

app crash when I startup on Mojave10.14.6

### Additional Information

The following is the report：

Process:               YUNCHI_V3 [87946]
Path:                  /Applications/YUNCHI_V3.app/Contents/MacOS/YUNCHI_V3
Identifier:            com.devdexterity.yunchiv3.master
Version:               1.2.1 (1.2.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           YUNCHI_V3 [87946]
User ID:               501

Date/Time:             2022-06-22 00:07:45.269 +0800
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Anonymous UUID:        82AF0960-8B7B-74C3-B8EE-A66F222492F2

Sleep/Wake UUID:       106EA34A-53C6-4063-A849-D3CE4F10BE71

Time Awake Since Boot: 12000 seconds
Time Since Wake:       11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

**Comment by codebytere** [comment]
We have not supported Electron v2 for nearly four years. This issue should be resolved in all supported versions.
