### ISSUE TITLE
[Bug]: Missing 9.4.4 release file

### ISSUE THREAD

**Issue by gazpachu** [electron/electron#34695]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

9.4.4

### What operating system are you using?

macOS

### Operating System Version

12.3

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The release file should exist

### Actual Behavior

Getting this error when installing dependencies:
```
npm ERR! HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip
```

**Comment by codebytere** [comment]
We did not support Apple Silicon arm64 builds until v11 - https://www.electronjs.org/blog/apple-silicon
