### ISSUE TITLE
[Bug]: child_process.fork not working on Windows

### ISSUE THREAD

**Issue by daqi** [electron/electron#34701]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.x.y

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

![image](https://user-images.githubusercontent.com/1715916/175231182-119971c7-c93a-48b7-bba4-8dd1fc0c897c.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/1715916/175231219-c6678592-d6ad-42ef-bf10-36b72bb5a903.png)

### Testcase Gist URL

https://gist.github.com/daqi/d03bb1706633723667e0dafd93cfbd47

### Additional Information

On this PC, The gist work well in fiddle, but not after pack.
Electron 11.5.0 work well.

```
 1: 00007FF63C94AE66 node::Buffer::New+50438
 2: 00007FF63C93AC78 node::InitializeNodeWithArgs+2344
 3: 00007FF63B0B604D std::__1::__vector_base<v8::CpuProfileDeoptInfo,std::__1::allocator<v8::CpuProfileDeoptInfo> >::__end_cap+21981
 4: 00007FF63AEF7D6E std::__1::__vector_base<v8::CpuProfileDeoptFrame,std::__1::allocator<v8::CpuProfileDeoptFrame> >::__vector_base<v8::CpuProfileDeoptFrame,std::__1::allocator<v8::CpuProfileDeoptFrame> >+46110
 5: 00007FF63E892FC2 Cr_z_crc32+4115698
 6: 00007FFF8D946FD4 BaseThreadInitThunk+20
 7: 00007FFF8EA9CEC1 RtlUserThreadStart+33
```

**Comment by VerteDinde** [comment]
Thanks for reporting this! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by daqi** [comment]
> Thanks for reporting this! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance!

I updated detail.

**Comment by daqi** [comment]
3 users have reported this issue.

**Comment by daqi** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/1715916/188791400-df5beba7-ab21-4437-85b1-048dad388c8d.png">

**Comment by daqi** [comment]
bump

**Comment by li725-ll** [comment]
I encountered the same problem, but I discovered this. https://www.electronjs.org/zh/blog/electron-22-0#utilityprocess-api-36089
