### ISSUE TITLE
[Bug]: Accelerator null on predefined menu roles

### ISSUE THREAD

**Issue by johnbwoodruff** [electron/electron#34705]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.4

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When getting the menu via `Menu.getApplicationMenu()`, the accelerators should not be `null` for the predefined menu roles such as copy, paste, etc.

### Actual Behavior

Any menu items with a user-defined accelerator correctly returns the accelerator, but any of the predefined menu roles such as undo, redo, cut, copy, paste, etc. return `null` for the accelerator, despite those accelerators being registered and working.

### Testcase Gist URL

https://gist.github.com/johnbwoodruff/725227db5ae734f73de6efd3af2a7960

### Additional Information

The accelerators are definitely defined for these predefined roles. The hotkeys work correctly, and they're displayed when the native menu is rendered. However, if you want to render your own custom menu, you won't know those accelerators as they are returned as `null`.

You can see in https://github.com/electron/electron/blob/5af6b898d92432369ce9495e75d75b02af651531/lib/browser/api/menu-item-roles.ts#L36-L41, for example, that all of these roles have accelerators properly defined. (hence why they work when you use them) So those accelerators should come through on the menu when using `Menu.getApplicationMenu()`.

**Comment by VerteDinde** [comment]
@johnbwoodruff I repro'ed this, but I could reproduce the behavior as far back as Electron 16. Was this working in previous versions of Electron for you?

**Comment by johnbwoodruff** [comment]
I haven't had this usecase until now so I'm not sure if it ever worked. I would guess it hasn't ever worked, but I could be wrong about that.

**Comment by johnbwoodruff** [comment]
Also thank you for looking into this! Let me know if there's any more info I can provide. I tried to be thorough with the fiddle.

**Comment by johnbwoodruff** [comment]
I just validated that this is still an issue in the latest version of electron. (20.0.0)

**Comment by johnbwoodruff** [comment]
Just validated that this is still an issue in the latest version of Electron. (v24.1.2)

**Comment by johnbwoodruff** [comment]
Just validated that this is still an issue in the latest version of Electron (v25.3.1)

**Comment by johnbwoodruff** [comment]
Just checked and this is still an issue in the latest version. (v27.0.2)
