### ISSUE TITLE
[Bug]: chinese doc is not working

### ISSUE THREAD

**Issue by sakura-he** [electron/electron#34710]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17

### What operating system are you using?

Windows

### Operating System Version

windows

### What arch are you using?

x64

### Expected Behavior

Chinese documents can be translated normally

### Actual Behavior

https://www.electronjs.org/zh/docs/latest/tutorial/quick-start chinese doc is not working

### Additional Information

https://www.electronjs.org/zh/docs/latest/tutorial/quick-start

**Comment by codebytere** [comment]
Continue on https://github.com/electron/i18n/issues/2105
