### ISSUE TITLE
[Bug]: BrowserViews not painting their WebContents when minimize

### ISSUE THREAD

**Issue by TianbinTobin** [electron/electron#34717]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Last Known Working Electron version

19.0.6

### Expected Behavior

1. run the [Electron Fiddle Gist](https://gist.github.com/1928de14317d540d1e7028451374ab15)
2. after the first WebContents painting
3. minimize the program
4. run `electronAPI.openTab()` in Developer Tools
5. Expected painting the new WebContents

### Actual Behavior

BrowserViews not painting their WebContents when minimize, the program is white screen until you change his size

### Testcase Gist URL

https://gist.github.com/1928de14317d540d1e7028451374ab15

### Additional Information

run `electronAPI.openTab()` in Developer Tools

**Comment by dorsta** [comment]
Has anyone found any other workarounds than resizing the window?

**Comment by TianbinTobin** [comment]
> 

no found

**Comment by TianbinTobin** [comment]
> Has anyone found any other workarounds than resizing the window?

no found

**Comment by dorsta** [comment]
I've found a workaround:

`BrowserWindow.on('restore', () => BrowserWindow.show())`

But the size of the window is still lost.

**Comment by TianbinTobin** [comment]
> I've found a workaround:
> 
> `BrowserWindow.on('restore', () => BrowserWindow.show())`
> 
> But the size of the window is still lost.

I tried but it didn't work.

only `BrowserWindow.on('restore', () => BrowserView.setBounds())` working well.

**Comment by dorsta** [comment]
I am not using BrowserViews explicitly only the BrowserWindow, maybe that's why the different workarounds.
