### ISSUE TITLE
[Bug]: section sign (§) shortcut is not working

### ISSUE THREAD

**Issue by szingg** [electron/electron#34718]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

x64

### Expected Behavior

There should be a way to register the section sign (§)

### Actual Behavior

When registering the shortcut '§', i get the following error: 
`TypeError: Error processing argument at index 0, conversion failure from §`

TestCode: `globalShortcut.register('§', () => console.log('§ pressed'));`

### Additional Information

I have a physical [Swiss-German Keyboard](http://kbdlayout.info/KBDSG/)
![image](https://user-images.githubusercontent.com/11045324/175320017-59389444-05f3-4284-8f94-dd2f1ffb5bf2.png)

**Comment by ursmeili** [comment]
I have this same problem, too.

**Comment by codebytere** [comment]
This is an upstream limitation, unfortunately: https://source.chromium.org/chromium/chromium/src/+/main:ui/events/keycodes/keyboard_codes_posix.h 

it is not a recognized keycode in Chromium. We can change this if something changes upstream, though!
