### ISSUE TITLE
[Bug]: wrong desktop capturer picture resolution when use mac retina screen

### ISSUE THREAD

**Issue by terry2010** [electron/electron#34725]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.5

### What operating system are you using?

macOS

### Operating System Version

macos 11.6 (20G165) 

### What arch are you using?

x64

### Last Known Working Electron version

16.2.5

### Expected Behavior

capture desktop with right resolution  （logic resolution × screen scaleFactor）
eg:  
intel  macbookpro 13.3 with retina screen
  logic resolution : 1440×900
  physic resolution : 3200×1800 (maybe?)

copy demo code on https://www.electronjs.org/docs/latest/api/desktop-capturer  to finish destop capturer  , 
I want got a picture with real  right resolution (2880 ×1800)

### Actual Behavior

I got a blurred picture with logic resolution （1440×900）

### Testcase Gist URL

https://gist.github.com/4226c9e061fc6ca0feb9c57da04910e0

### Additional Information

it works good on electron 16.2.5, failed since 17.0.0 (even 20.0.0-nightly.20220513)

**Comment by dmermigkas** [comment]
I am also experiencing this issue and it seems that the `scaleFactor` property of DisplayObject is not correct for retinas. For my Macbook pro 13'' 2020 it is equal to 2.

**Comment by praneetrohida** [comment]
bump
