### ISSUE TITLE
[Bug]: webContents.setAlwaysOnTop(false) fail 

### ISSUE THREAD

**Issue by terry2010** [electron/electron#34743]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.6

### What operating system are you using?

Windows

### Operating System Version

windows 10 

### What arch are you using?

x64

### Last Known Working Electron version

never works

### Expected Behavior

1. execute   mainWindow.setAlwaysOnTop(true)  , window on top, cover other windows
2. mouse don't touch mainWindow, and  execute   mainWindow.setAlwaysOnTop(false)  
3. mouse don't touch mainWindow, click any other full screen  window, mainWindow will hidden 

### Actual Behavior

1. execute   mainWindow.setAlwaysOnTop(true)  , window on top, cover other windows (✔)
2. mouse don't touch mainWindow, and  execute   mainWindow.setAlwaysOnTop(false)   (✔)
3. mouse don't touch mainWindow, click any other full screen  window, mainWindow will hidden （✖）

Actual Behavior：
3.1 **mouse don't touch mainWindow**, click any other full screen  window,  mainWindow still on top
3.2 **mouse  must click mainWindow** , then click any other full screen  window, mainWindow  hidden

<img src="https://raw.githubusercontent.com/terry2010/electron-bug-has-cmd-window/main/screenshot.gif" width="100%">

### Testcase Gist URL

https://gist.github.com/6bccc9ff43b9a1dd1661e774e4bf8cc8

**Comment by mlaurencin** [comment]
As there seems to be a difference between this and the macOS functionality, it may be worth exploring in the future. For now however, the inclusion of focusing on the window after the switch should provide the functionality you are looking for. You can try adding `mainWindow.focus()` after line 31 in the `main.js` file of your gist.

**Comment by terry2010** [comment]
> As there seems to be a difference between this and the macOS functionality, it may be worth exploring in the future. For now however, the inclusion of focusing on the window after the switch should provide the functionality you are looking for. You can try adding `mainWindow.focus()` after line 31 in the `main.js` file of your gist.


![图片](https://user-images.githubusercontent.com/1849037/177489001-d4b1fd82-f164-4686-8654-4b54a304ccc4.png)

It still not work 

1.  windows 10 (21H2,19044.1766)   electron 19.0.6
                         still not works, and it has the same behavior as the old code
2.  macos (11.6 x64) , electron 19.0.6
                          has strange behavior : mainWindow auto hide after code excutes `mainWindow.focus()`
