### ISSUE TITLE
[Bug]: Electron 19.x still crashes when call app.requestSingleInstanceLock(); in MacOS with it`s code signed.

### ISSUE THREAD

**Issue by garrettjavalia** [electron/electron#34744]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.3

### What operating system are you using?

macOS

### Operating System Version

macOS monterey 12.4

### What arch are you using?

x64

### Expected Behavior

function call success without crash

### Actual Behavior

crashes immediately with this error in console(you can find it when you open it by executing binary in the app`s Contents/MacOS folder.

Last login: Mon Jun 27 14:23:49 on ttys001
/Users/minsuk.jung/Documents/GitHub/between-desktop/result/electron-shell-app-mac-mas/Between.app/Contents/MacOS/Between ; exit;
minsuk.jung@thingsflowui-MacBookPro-2 ~ % /Users/minsuk.jung/Documents/GitHub/between-desktop/result/electron-shell-app-mac-mas/Between.app/Contents/MacOS/Between ; exit;
[24917:0627/143327.649612:ERROR:process_singleton_posix.cc(1184)] Failed to bind() /var/folders/q3/rx4k87rd1nq_5w22xzzps0l40000gp/T/kr.thingsflow.BetweenMac/S/SingletonSocket: Operation not permitted (1)

Saving session…
…copying shared history…
…saving history…truncating history files…
…completed.

### Additional Information

It doesnt crash at all if you don`t sign the app. I tried to fix this by setting entitlements, but It seems to be hard/impossible to set that singleton socket file to be allowed by entitlements. I found other issues that are telling me same problem.

I tried almost few weeks to codesign my Electron app and make sure it launches correctly.

now I can tell how to set entitlements in macOS for MAS, but this problem still borders me. I can disable call of this function, however it doesnt feel right for me to just disabling a functioncall like below
let isFirstInstance = process.mas || app.requestSingleInstanceLock();

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by garrettjavalia** [comment]
https://gist.github.com/f14533e4663ddf128ae35919d8b7d680
is my simple gist which is enough to reproduce the crash. It will crash only if you codesign it for macOSX Appstore. I am not sure if it will crash even you sign it with Apple developer codesign cert, which is for outside of appstore.

**Comment by MarshallOfSound** [comment]
@garrettjavalia You need to package your app for the `mas` platform instead of the `darwin` platform if your intention is to ship the app to the Mac App Store (MAS)

**Comment by garrettjavalia** [comment]
I surely did package my app for MAS platform(I am not using electron-builder nor electron-forge, but manually all the things by myself. But I can sure that I did it corretly, because my app is already uploaded to Appstore and working.(including test flight and for real end users).
The only bad thing was that I had to disable requireSingleInstanceLock call in MAS build.
@MarshallOfSound please consider this problem again.
