### ISSUE TITLE
[Bug]: BrowserWindow's "moved" event isn't triggered when using aero snap

### ISSUE THREAD

**Issue by FlysoftBeta** [electron/electron#34741]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0-beta.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22h2

### What arch are you using?

x64

### Last Known Working Electron version

all

### Expected Behavior

The event should be triggered

### Actual Behavior

When I use Win+LeftArrow, Win+RightArrow, or drag the window to the top of screen to move the window to one side, the window is moved, but its "moved" event is not triggered.
![image](https://user-images.githubusercontent.com/49718840/175805358-a2cfe581-069a-48d0-95d4-d861687ee3e3.png)

### Testcase Gist URL

https://gist.github.com/6df4f13d195cabe34d1d35142e516b94

**Comment by mlaurencin** [comment]
@FlysoftBeta I attempted to run your gist on earlier versions and did not see this function as described in your expected behavior. Do you have a specific version you tested that worked?

**Comment by FlysoftBeta** [comment]
I tried it on 16.0.0 and it had the same behavior, and I test it on Windows 11.

**Comment by FlysoftBeta** [comment]
https://user-images.githubusercontent.com/49718840/176727549-0a3cb753-29f2-438e-8800-c0a4c5ac6d9a.mp4

Here is the test video

**Comment by mlaurencin** [comment]
This videos seems to indicate that it also did not display the expected behavior in 16.0.0. I tested on both Windows 11 and Windows 10 versions 20.0.0-beta.2 and 16.0.0 and did not see the event triggered in any of the cases. If there was no previous version in which the `moved` event was triggered, I think this would be considered a new feature rather than a bug.

**Comment by FlysoftBeta** [comment]
Yes, but I don't know why it doesn't even trigger the resized event... I need to change the layout by listening the resized event.
And hope you can add this feature in future versions. Thanks!

**Comment by demoslotid** [comment]
> Yes, but I don't know why it doesn't even trigger the resized event... I need to change the layout by listening the resized event. And hope you can add this feature in future versions. Thanks!

i also have the same bug, hope @mlaurencin  can add this feature in future versions. Thanks!

**Comment by pushkin-** [comment]
repros in v22 with gist above

**Comment by mlaurencin** [comment]
Unfortunately, as stated in the linked feature request above, the OS does not provide this aero snap information to us. I will close this issue now, but if the information is provided in the future, then a new feature request can be submitted.

**Comment by FlysoftBeta** [comment]
Although the problem has not been solved yet, thanks for your efforts!
