### ISSUE TITLE
[Bug]: Couldn't get focused element's cursor position of and Electron app.

### ISSUE THREAD

**Issue by ArulOSlash** [electron/electron#34755]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17

### What operating system are you using?

macOS

### Operating System Version

macOS 12.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I'm working on a mac native app that has similar functionalities to the [Rocket app.](https://matthewpalmer.net/rocket/). Whenever a user types `:` outside of my app I'll show an `NSWindow` near the cursor. To get the cursor position I'm using Accessibility APIs. 

I checked my window positioning in native apps like XCode, Notes, and Messages and tried on web apps as well everything is working fine But I'm facing an issue with electron apps that I'm getting the **XOrigin** always as 0 and **YOrigin** as 982 (That is equal to my screen's size: NSScreen.main?.frame.height).

```
  extension AXUIElement {
      func getCursorRect() -> CGRect? {
        guard let cursorPosition = cursorPosition else {return nil}
        var cfRange: CFRange = .init(location: cursorPosition, length: 1)
        let axval: AXValue? = AXValueCreate(.cfRange, &cfRange)
        var bounds: CFTypeRef?
        guard let axval = axval else {return nil}
        AXUIElementCopyParameterizedAttributeValue(self, kAXBoundsForRangeParameterizedAttribute as CFString, axval, &bounds)
        var cursorRect: CGRect = .zero
        guard let bounds = bounds else {return nil}
        AXValueGetValue(bounds as! AXValue, .cgRect, &cursorRect)
        return cursorRect
      }
  }
```

### Actual Behavior

The method that I mentioned is supposed to return an actual cursor position like Native and web app does. 

### Additional Information

I'm not developing my application using the Electron framework but I'm facing the above-mentioned issue with the apps that were developed using the Electron framework.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by MentalGear** [comment]
Hey @ArulOSlash - I have a similar use case: Where you able to get the electron team to fix this behaviour in their apps?
