### ISSUE TITLE
[Bug]: Overlay's minimize button stays in hovered/focused state after restoring

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#34763]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.5

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

When hovering over a "minimize" button in titlebar overlay and clicking it, and then restoring the app - I expect that the button is restored to its original state:

![image](https://user-images.githubusercontent.com/79877362/176010822-fca7de7d-921a-453c-acfe-c45d9e3adc57.png)

### Actual Behavior

Instead if I click "minimize" and then restore I see this:

![image](https://user-images.githubusercontent.com/79877362/176010875-c4c0280f-d4b5-4edc-b2b6-16a30261ecdc.png)

### Additional Information

Originally reported in: https://github.com/signalapp/Signal-Desktop/issues/5992

**Comment by indutny-signal** [comment]
❤️

**Comment by wheezard** [comment]
I'm still having this issue in electron v19.0.8

**Comment by codebytere** [comment]
That's correct. It was not released until 19.0.9.

**Comment by wheezard** [comment]
Sorry for the previous comment, but this issue still persists in 19.0.9, but only if the window was left in a maximized state before minimizing.

**Comment by codebytere** [comment]
interesting - i'll check into it!

**Comment by codebytere** [comment]
@wheezard thanks for surfacing this - just put up a PR to remedy it.
