### ISSUE TITLE
[Feature Request]: Re add Linux 32bit 

### ISSUE THREAD

**Issue by coreybruce** [electron/electron#34783]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Linux 32bit binaries are missing as Linux 32bit distros like Arch32, Gentoo, Void, Debian etc still all support Linux 32bit

### Proposed Solution

Re add Linux 32bit binaries 

### Alternatives Considered

N/A

**Comment by RaisinTen** [comment]
IA32 Linux support was dropped in https://github.com/electron/electron/pull/33731/commits/389ef0731efca802db2089486ad6d9a91cc02ba8 in https://github.com/electron/electron/pull/33731 but the PR doesn't document the reason in `docs/breaking-changes.md`. Was that intentional @codebytere?

**Comment by codebytere** [comment]
No - it was the result of an upstream change in Chromium that forced our hand.

**Comment by RaisinTen** [comment]
> result of an upstream change in Chromium that forced our hand

Curious if you have a link to the upstream change. Did it get fixed later on in Chromium or is it not possible (and will never be?) to build chromium for 32-bit Linux anymore?

**Comment by codebytere** [comment]
It was removed in Chromium permanently - i can try to find the CL.

**Comment by RaisinTen** [comment]
> We can probably add it to breaking changes 

I guess that's the only thing we can do at this point, sent https://github.com/electron/electron/pull/34787 to do that.

> i can try to find the CL.

Cool, we can add that info to the docs / the PR description if you think that's relevant.

**Comment by coreybruce** [comment]
Is there a chance this could get fixed and re-added?

**Comment by codebytere** [comment]
@coreybruce imo no - given it's not supported by Chromium it's likely to face constant breakage and we're not interested or prepapred to take on that sole maintenance burden

**Comment by coreybruce** [comment]
Ahh that's a real shame, I wouldn't even care if Electron for 32bit was behind for stability
