### ISSUE TITLE
[Bug]: Electron icon shown instead of app's on Wayland

### ISSUE THREAD

**Issue by ivan18m** [electron/electron#34801]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.4

### What operating system are you using?

Other Linux

### Operating System Version

Linux 5.18.7-arch1-1 #1 SMP PREEMPT_DYNAMIC

### What arch are you using?

x64

### Expected Behavior

* I use Linux with a KDE environment
* I run an electron app with Wayland using chromium flags --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --ozone-platform=wayland

* The default Electron icon is shown, minimize to tray doesn't work and many other problems
* The problem is similar as described here
https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/ but instead of the Wayland icon, it is the Electron icon.

### Actual Behavior

* The proper icon is shown as when running without Wayland flags
* Can minimize/close to the system tray

**Comment by italoghost** [comment]
It is happening to me as well. I am on Arch Linux Gnome Wayland 42.5.

**Comment by Henry78** [comment]
Duplicate of #35997
