### ISSUE TITLE
[Bug]: BrowserWindow created between `app.dock.hide()` and `app.dock.show()` is visible on full screen

### ISSUE THREAD

**Issue by MaximKalinin** [electron/electron#34807]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.6

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

x64

### Last Known Working Electron version

12.0.0

### Expected Behavior

If you perform steps from **Actual Behavior** section, the window will appear on one of available desktops, not on top of other fullscreen app.

This is how Electron 12.0.0 and below behaved.

### Actual Behavior

The issue is macOS specific since it is related to OS dock.

Before starting the app in the Fiddle (use [Electron Fiddle](https://github.com/electron/fiddle) app and link from **Testcase Gist URL** section), enter fullscreen mode in Electron Fiddle app (real case scenario with packaged app could be reproduced with any full-screen app opened and Electron app being started from the Spotlight).

If you create a hidden `BrowserWindow` after invoking `app.dock.hide`, then invoke `app.dock.show` and then `window.show`, window will stay always on top of other windows and will be visible on full screen. 

### Testcase Gist URL

https://gist.github.com/MaximKalinin/cc61c84dc111b7e4fc29a5394b7700ce

**Comment by twitharshil** [comment]
I can confirm the issue got introduced with electron v13.0.0 onwards. I couldn't reproduce the behavior on electron v12.2.3 which is the last version released on electron v12.
