### ISSUE TITLE
[Feature Request]: Add a parameter for BrowserWindow's moved and resized to tell whether the window has been moved or resized by AeroSnap

### ISSUE THREAD

**Issue by FlysoftBeta** [electron/electron#34815]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

https://github.com/electron/electron/issues/34741#issue-1284842462
BrowserWindow's "moved" and "resized" event isn't triggered when using AeroSnap

### Proposed Solution

 Add a parameter for BrowserWindow's moved and resized event, and when the window is moved by AeroSnap (Win+← or Win+→), triggers the event and sets the parameter to true to tell it is moved or resized by AeroSnap.

### Alternatives Considered

`window.addEventListener("resize",()=>{})` can be used instead of resized event.
But I can't do anything with moved event.

**Comment by frank-dspeed** [comment]
I will add this issue as realted as we got users reporting that pinch zoom does not work because of they are getting resize events for windows that should get pinch zoom.

We Triaged it down and are sure it is something in the electron starter because it works with chromium - 
- https://github.com/MirServer/mir/issues/2463

**Comment by ckerr** [comment]
The OS doesn't provide this information to us, so Electron literally doesn't have this information to pass along to client apps :disappointed:

**Comment by frank-dspeed** [comment]
@ckerr it does you need to consume the stuff but ok we can let this closed i only want to make that clear for others that read that sure we get from the Window Server all this infos used interfaces for that are dbus and or directly the mir or x server. 

so 2 Protocols can be used dubs (even without dubs daemon) and MIR/X11 to obtain that events Chromium also exposes all resize events on different channels if any one is interested in implementing any features simply ping me i will write you a execution plan.
