### ISSUE TITLE
[Bug]: webContents.insertCSS doesn't work when it is in Chromium-provided page

### ISSUE THREAD

**Issue by FlysoftBeta** [electron/electron#34816]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0-beta.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2

### What arch are you using?

x64

### Expected Behavior

The promise returned by webContents.insertCSS should resolve with the key.

### Actual Behavior

When the webContents loads a Chromium-provided page (eg: view-source page(like view-source:https://google.com), xml viewer, image viewer) and I try inserting CSS to the page, 
 the promise returned by webContents.insertCSS keeps pending and never resolves.

### Testcase Gist URL

https://gist.github.com/81b8b61d974173cb9f73c67aaa03a8fd

### Additional Information

Some instructions of the gist: There are two webviews on the window, and I try using insertCSS("body { background: red; }") to make the background red, but only one of them succeed.

![image](https://user-images.githubusercontent.com/49718840/177039273-a7b59e8d-b8e9-466a-a145-21146b374338.png)

and there is only one promise resolved, too.

![image](https://user-images.githubusercontent.com/49718840/177039318-073a6756-ee85-469f-afdb-dfbc548f88f7.png)

**Comment by ckerr** [comment]
https://gist.github.com/81b8b61d974173cb9f73c67aaa03a8fd is a 404, so I'm marking this as `blocked/needs-repro`
