### ISSUE TITLE
[Bug]: Electron shows duplicate tray icons

### ISSUE THREAD

**Issue by lukehmcc** [electron/electron#34811]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.6

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 36

### What arch are you using?

x64

### Last Known Working Electron version

19.0.6

### Expected Behavior

When creating a standard electron tray on a platform that both supports libappindicator and GtkStatusIcon, electron should chose one type of indicator to display and put it in the tool bar. 

### Actual Behavior

Both the native libappindicator and the GtkStatusIcon get added to the toolbar as shown below:
![image](https://user-images.githubusercontent.com/58121030/176933593-07e7a668-9d44-4ea4-afc3-a51ecb04cede.png)
The first one being libappindicator: 
![image](https://user-images.githubusercontent.com/58121030/176933641-8b84e6d7-38a0-4045-b3f6-e301536a5a5b.png)
The second one being GtkStatusIcon:
![image](https://user-images.githubusercontent.com/58121030/176933779-7c6cc543-b496-4c55-8a8e-3bb67e12368b.png)

**Comment by twitharshil** [comment]
Thanks for reporting this and helping to make Electron better!

Please use [Electron Fiddle](https://github.com/electron/fiddle) to create a standalone (no external dependencies) testcase and publish it as a [gist](https://gist.github.com/), then link to it here.

Even if you have a code snippet or a git repository that show the testcase, please put it in a gist. This lets maintainers triage issues more effectively. It also ensures that we're testing the exact same issue that you're seeing!

Please avoid external dependencies in the test. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.

If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). This lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to the gist in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
