### ISSUE TITLE
[Bug]: H264 video performance does not match Chromium on Raspberry Pi 4

### ISSUE THREAD

**Issue by tejohnso** [electron/electron#34825]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0

### What operating system are you using?

Other (specify below)

### Operating System Version

Raspbian GNU/Linux 11 (bullseye)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Similar performance between Chromium and Electron when playing an H264 video (1080p).

### Actual Behavior

Performance in Electron is noticeably reduced with dropped frames and higher cpu load. Hardware decoding is not being used.

### Additional Information

Similar to issue [22454](https://github.com/electron/electron/issues/22454) which was not resolved, I notice a significant difference when playing a Big Buck Bunny H264 video on Raspberry Pi 4. In Chromium I can see that hardware decoding is being used, while in Electron it is falling back to FFMpegDecoder.

Is it expected that hardware decoding does not work in Electron on Rpi4?
I've tried several command line flags and nothing seems to work.

To reproduce set up a simple index.js that loads a `file://` url to the local video file in a default `BrowserWindow`. The difference is noticeable. One could also load devtools and load the media tab to confirm that hardware decoding is not being used.

**Comment by tejohnso** [comment]
Chrome://gpu without any flags indicates no acceleration in both cases.

![chrome-gpu-electron](https://user-images.githubusercontent.com/1511535/178116084-62649e46-4ac2-4cb1-a5a6-d7ab8efe66d8.png)
![chrome-gpu-chromium](https://user-images.githubusercontent.com/1511535/178116085-14be72aa-01af-4c79-8d57-5ea7f7790f37.png)

However if you open devtools and look at the *media* tab, or go to `chrome://media-internals` you can see that the Chromium version is using VDAVideoDecoder while Electron is using FFMpeg.

Here's a partial diff of the media-internals logs.

```
--- media-internals-chromium.txt
+++ media-internals-electron.txt
@@ -36,8 +35,8 @@
       "kStartTime": 0,
       "kBitrate": 837589,
       "kIsVideoDecryptingDemuxerStream": false,
-      "kVideoDecoderName": "VDAVideoDecoder",
-      "kIsPlatformVideoDecoder": true,
+      "kVideoDecoderName": "FFmpegVideoDecoder",
+      "kIsPlatformVideoDecoder": false,
       "dimensions": "1920x1080",
       "kResolution": "1920x1080",
       "event": "kPause",
@@ -143,77 +133,87 @@
         ]
       },
       {
-        "time": 227.06099999998696,
+        "time": 251.41300000000047,
         "key": "kMaxDuration",
         "value": 10
       },
       {
-        "time": 227.06200000000536,
+        "time": 251.41399999998976,
         "key": "kStartTime",
         "value": 0
       },
       {
-        "time": 227.1019999999844,
+        "time": 251.41599999996834,
         "key": "kBitrate",
         "value": 837589
       },
       {
-        "time": 228.69800000000396,
+        "time": 251.65200000000186,
         "key": "info",
         "value": "Failed to initialize DecryptingVideoDecoder"
       },
       {
-        "time": 255.85999999998603,
+        "time": 251.70100000000093,
+        "key": "info",
+        "value": "Failed to initialize VpxVideoDecoder"
+      },
+      {
+        "time": 251.7270000000135,
+        "key": "info",
+        "value": "Failed to initialize Dav1dVideoDecoder"
+      },
+      {
+        "time": 258.1389999999665,
         "key": "kIsVideoDecryptingDemuxerStream",
         "value": false
       },
       {
-        "time": 255.86900000000605,
+        "time": 258.1510000000126,
         "key": "kVideoDecoderName",
-        "value": "VDAVideoDecoder"
+        "value": "FFmpegVideoDecoder"
       },
       {
-        "time": 255.87099999998463,
+        "time": 258.15299999999115,
         "key": "kIsPlatformVideoDecoder",
-        "value": true
+        "value": false
       },
       {
-        "time": 255.93799999999464,
+        "time": 258.23300000000745,
         "key": "info",
-        "value": "Selected VDAVideoDecoder for video decoding, config: codec: h264, profile: h264 high, level: not available, alpha_mode: is_opaque, coded size: [1920,1080], visible rect: [0,0,1920,1080], natural size: [1920,1080], has extra data: true, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
+        "value": "Selected FFmpegVideoDecoder for video decoding, config: codec: h264, profile: h264 high, level: not available, alpha_mode: is_opaque, coded size: [1920,1080], visible rect: [0,0,1920,1080], natural size: [1920,1080], has extra data: true, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
       },
       {
```

I've tried many flags in both cases, and in some cases the Chromium `chrome://gpu` page will correctly confirm the hardware acceleration that is shown in `chrome://media-internals`. In all cases, Electron continues to use FFMpegVideoDecoder.

**Comment by tejohnso** [comment]
I was able to get Electron to use the same `VDAVideoDecoder` as Chromium by incorporating some of the Chromium patches into an Electron build. I can confirm a significant difference in dropped frames visually. I also see the official Electron distribution spikes the chrome `renderer` process over 200% during playback, while the custom build keeps the `renderer` process usage low and puts more load on the `gpu-process`.  No command line flags applied.

**Comment by jakubmirejovsky** [comment]
> 

Could you eloborate on this Chromium patch? What patches did you apply? I am dealing with the same issue.

**Comment by tejohnso** [comment]
The patch is in [RPi-Distro/chromium-browser](https://github.com/RPi-Distro/chromium-browser) in the debian/patches directory.

I had to look back in the commit history to find a `v*.patch` that matched the electron chromium version and use that one. The other patches were't used.

I also had to update `build/args/all.gn` to include:

- `use_v4l2_code = true`
- `use_v4l2_code_rpi = true`

Then it's a matter of working through the [build instructions](https://www.electronjs.org/docs/latest/development/build-instructions-linux) while also keeping in mind the Chromium [build instructions](https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md#Build-Chromium) as well.

Ideally a working solution could be incorporated into Electron's existing [patch system](https://www.electronjs.org/docs/latest/development/patches) and maintained properly so that Electron has hardware decoding on the Rpi built in.

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! It looks as though the needed patches for `use_v4l2_code` and `use_v4l2_code_rpi` are at the heart of this issue. A group of Electron's maintainers just discussed this; if Raspberry Pi can upstream these flags into Chromium, Electron will inherit them directly as well. However, I don't think Electron has plans to maintain those ourselves. 

I'm going to close out this issue, but should these flags get upstreamed to Chromium, please feel free to tag us in this issue in the future! 🙇‍♀️

**Comment by ElConcombritos** [comment]
Hello, sorry to bother you again, but i'm following the instruction of electron, so i'm trying to build electron from a linux x86 machine. I tried to put target_cpu = "arm" to make a build that raspbian can use, but it doesn't work. What parameter did you use ? The doc only talk about arm and arm64, but no armv7l that rasbpian use.

Thanks

**Comment by ChiragMoradiya** [comment]
@tejohnso Thank you for the Tip.

After applying [v101.0.4951.57_rpi_2.52.patch](https://github.com/RPi-Distro/chromium-browser/blob/master/debian/patches/v101.0.4951.57_rpi_2.52.patch) on electron source, the built electron was able to play the video with hardware decoder enabled, on Raspberry Pi 4B running on Raspberry Pi OS.

But, the electron executable built from the source was 4.3 GB in size. While, pre-built binary available on [Github](https://github.com/electron/electron/releases) is nearly 130 MB; at max 1.5 GB for some of the platforms. 

Any idea, **Why there would be such a huge difference in the size of pre-built binary vs custom-built from source?**

BTW, there were typos in `build/args/all.gn`, they would be:
```
use_v4l2_codec = true
use_v4l2_codec_rpi = true
```

**Comment by gszentesi** [comment]
Hi All, I asked chatGPT. It provided me a working solution, however the MEAS-LOADER warnings are still there, but the playback is good. I store the anwer here, for future questions...

The answer:

If the kms_swrast driver is already installed in the /usr/lib/aarch64-linux-gnu/dri directory, you can try specifying the path to the driver explicitly in your Electron application's code.

When creating the BrowserWindow instance in Electron, you can set the GDK_BACKEND environment variable to x11 and the LIBGL_DRIVERS_PATH environment variable to the location of the dri directory containing the driver. Here's an example of how you can modify your code:

javascript
Copy code
const { app, BrowserWindow } = require('electron');

app.whenReady().then(() => {
  // Set environment variables
  process.env.GDK_BACKEND = 'x11';
  process.env.LIBGL_DRIVERS_PATH = '/usr/lib/aarch64-linux-gnu/dri';

  // Create the browser window
  const mainWindow = new BrowserWindow({
    // window configuration
  });

  // Load your YouTube URL
  mainWindow.loadURL('https://youtube.com');
});
By explicitly setting these environment variables, you ensure that Electron can locate the kms_swrast driver in the specified directory and use it for rendering. This should help resolve the frame loss issue during video playback.

Make sure to replace 'https://youtube.com' with your actual URL and adjust the window configuration according to your needs.

Give this approach a try, and hopefully, it resolves the driver loading issue and improves the video playback performance in your Electron application on Raspbian 64-bit.

**Comment by matt-oakes** [comment]
For those interest, I have started a discussion about what woud be involved with upstreaming those Chromium patches:

https://github.com/RPi-Distro/chromium-browser/issues/43

**Comment by justinasjaronis** [comment]
> @tejohnso Thank you for the Tip.
> 
> After applying [v101.0.4951.57_rpi_2.52.patch](https://github.com/RPi-Distro/chromium-browser/blob/master/debian/patches/v101.0.4951.57_rpi_2.52.patch) on electron source, the built electron was able to play the video with hardware decoder enabled, on Raspberry Pi 4B running on Raspberry Pi OS.
> 
> But, the electron executable built from the source was 4.3 GB in size. While, pre-built binary available on [Github](https://github.com/electron/electron/releases) is nearly 130 MB; at max 1.5 GB for some of the platforms.
> 
> Any idea, **Why there would be such a huge difference in the size of pre-built binary vs custom-built from source?**
> 
> BTW, there were typos in `build/args/all.gn`, they would be:
> 
> ```
> use_v4l2_codec = true
> use_v4l2_codec_rpi = true
> ```

Most probably you statically linked everything to this binary. 
BTW how did it work, did you try to repeat with later versions ?
Maybe you wouldn't mind sharing this prebuilt binary ?

**Comment by jakubmirejovsky** [comment]
@ChiragMoradiya I would be very interested in seeing the hardware decoding in action. Would you be so kind and share your approach? What is needed to build a custom Chromium binary for Electron?
