### ISSUE TITLE
[Bug]: wayland window decorations mangled and not clickable

### ISSUE THREAD

**Issue by csett86** [electron/electron#34820]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.7

### What operating system are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Last Known Working Electron version

19.0.0-alpha.3

### Expected Behavior

Running under wayland natively (`--ozone-platform=wayland`) and enabling window decorations (`app.commandLine.appendSwitch('enable-features', 'WaylandWindowDecorations');` in main.js) should show a title bar which is clickable.

Below is from 19.0.0-alpha.3 where it still worked:

![grafik](https://user-images.githubusercontent.com/1392875/177206042-21015934-5a2b-4484-bc5c-111198be4008.png)

### Actual Behavior

Running under wayland natively (`--ozone-platform=wayland`) and enabling window decorations (`app.commandLine.appendSwitch('enable-features', 'WaylandWindowDecorations');` in main.js) shows mangled transparent border on the left side instead of a title bar and is not clickable:

On **electron 19** is broke during the alpha and beta cycle:

Below is from 19.0.0-alpha.4 where it first broke, here the buttons are still clickable:

![grafik](https://user-images.githubusercontent.com/1392875/177205464-db1274be-63dc-4d5d-93e2-14157984966d.png)

Starting with 19.0.0-beta.4 the buttons are also no longer clickable:

![grafik](https://user-images.githubusercontent.com/1392875/177205697-3e1d4362-2cd3-4ceb-a4f1-5ee6ef68643f.png)

With 19.0.0 up and until 19.0.7 the same, broken titlebar and not clickable:

![grafik](https://user-images.githubusercontent.com/1392875/177205907-2ed403b8-df96-4c9e-8292-52092cb4db8b.png)

On **electron 18-x-y** it also broke between 18.2.0 and 18.2.1, but only the buttons cannot be clicked any longer:

18.2.0 still everything ok, titlebar there and clickable:

![grafik](https://user-images.githubusercontent.com/1392875/177205350-a175f92b-5b28-40e3-a108-c05e6b87aa7d.png)

18.2.1: Titlebar still there, but no longer clickable:

![grafik](https://user-images.githubusercontent.com/1392875/177205401-2dafdd0f-a8de-4a39-8cec-e101bcfb74e5.png)

Up and including 18.3.5 the titlebar stays there, but not clickable:

![grafik](https://user-images.githubusercontent.com/1392875/177205824-60381433-c39b-440d-9aa2-a7c62592f642.png)

### Testcase Gist URL

https://gist.github.com/csett86/5d45c47cb1d5331b9ede0788ff5ae284

### Additional Information

To reproduce with the gist, you need to add ```--ozone-platform=wayland``` to the user-provided flags, as I could find a way to add this to the fiddle (the WaylandWindowDecorations are part of the fiddle):

![grafik](https://user-images.githubusercontent.com/1392875/177206134-6371daec-5e63-4127-a344-0bf72ffba907.png)

**Comment by csett86** [comment]
I also already tried myself if I could spot an obvious commit that broke it on either 18 or 19 between the mentioned releases, but so far had no luck there.

**Comment by csett86** [comment]
FYI @refi64

**Comment by refi64** [comment]
I'll make sure to look into this soon-ish, but it might take a hot minute.

**Comment by GrantMoyer** [comment]
I ran a git bisect. The mangled decorations were introduced by 7c0ed9e8373e1589af8b213f338caa75853e294e … somehow. I double checked too; no mangled decoration in the parent commit, mangled in 7c0ed9e8373e1589af8b213f338caa75853e294e.
