### ISSUE TITLE
[Bug]: Error about Chinese documentation API 'did-become-active' event

### ISSUE THREAD

**Issue by yaojiadong666** [electron/electron#34828]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.7

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 2.2.1 (21D62)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

19.0.7

### Expected Behavior

 'did-groupe-active'  => 'did-become-active'

### Actual Behavior

 'did-become-active' =>  'did-groupe-active'  

https://www.electronjs.org/zh/docs/latest/api/app#%E4%BA%8B%E4%BB%B6-did-groupe-active-macos

![image](https://user-images.githubusercontent.com/105629090/177457589-b5f8dd98-ba01-4818-a8fb-3087084fc69d.png)

**Comment by VerteDinde** [comment]
@yaojiadong666 Thanks for reporting this issue! We'll get this fixed 🙇‍♀️
