### ISSUE TITLE
When frame is false transparent is true show is false, css set transparent will appear white border, click on the window border disappears

### ISSUE THREAD

**Issue by CahierX** [electron/electron#34835]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.6

### What operating system are you using?

Windows

### Operating System Version

windows 10 pro 20H2

### What arch are you using?

x64

### Expected Behavior

No white border appears

![image](https://user-images.githubusercontent.com/31394482/177744644-87ec8ee2-feee-4fe0-ba1c-a14a701ae0d2.png)

### Actual Behavior

A white border appears
![image](https://user-images.githubusercontent.com/31394482/177744352-b0b49df2-cc0e-4035-96ae-8d495de0e5ea.png)

### Testcase Gist URL

https://gist.github.com/6d645d9b55337add7d142052f8b86e45

**Comment by CahierX** [comment]
If the initial show is set to true then there is no such problem
![image](https://user-images.githubusercontent.com/31394482/177745401-d4db6eda-52d6-49ed-9661-4b126ce91a53.png)

**Comment by twitharshil** [comment]
Thanks for reporting the issue! It seems like the issue got introduced from electron v16+ onwards. I couldn't reproduce the behavior on top of electron v15.5.7 but successfully reproduced it on 16.0.0
