### ISSUE TITLE
[Bug]:  Game gets smaller on full screen.

### ISSUE THREAD

**Issue by keybladegames** [electron/electron#34830]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.00

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

16.00

### Expected Behavior

I used to play dont escape and the game would get bigger

### Actual Behavior

I click full screen and the game instead gets alot smaller instead of bigger
![bandicam 2022-07-06 21-33-42-370](https://user-images.githubusercontent.com/63317382/177678208-0d837467-575a-4d37-b832-cfd68933be91.jpg)

**Comment by twitharshil** [comment]
Thanks for reporting this and helping to make Electron better!

Please use [Electron Fiddle](https://github.com/electron/fiddle) to create a standalone (no external dependencies) testcase and publish it as a [gist](https://gist.github.com/), then link to it here.

Even if you have a code snippet or a git repository that show the testcase, please put it in a gist. This lets maintainers triage issues more effectively. It also ensures that we're testing the exact same issue that you're seeing!

Please avoid external dependencies in the test. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.

If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). This lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to the gist in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
