### ISSUE TITLE
[Bug]: Electorn 18 app is missing desktopFileName window property

### ISSUE THREAD

**Issue by mamantoha** [electron/electron#34852]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.4

### What operating system are you using?

Other Linux

### Operating System Version

Manjaro Linux

### What arch are you using?

x64

### Last Known Working Electron version

17.4.3

### Expected Behavior

`desktopFileName` window property should not be empty

![image](https://user-images.githubusercontent.com/61285/177988205-9de3f548-11da-41e7-9d8c-fbc289977148.png)

### Actual Behavior

`desktopFileName` window property is empty

With Electron 17.4.3 - OK
![image](https://user-images.githubusercontent.com/61285/177988036-3d4dcb27-706a-4708-b853-91c8bf063687.png)

**Comment by vially** [comment]
I'm not familiar with KDE to know how the `desktopFileName` property is computed, but *I think* the root underlying issue may be the same as #33578. **If** that's the case it *may* get fixed with #34855.

**Comment by mamantoha** [comment]
Look like it's related.
