### ISSUE TITLE
[Bug]: When sandbox is enabled, use __dirname or __filename in preload will cause error.

### ISSUE THREAD

**Issue by sky0014** [electron/electron#34854]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2

### What arch are you using?

x64

### Expected Behavior

__dirname should be set to the right value.

### Actual Behavior

![image](https://user-images.githubusercontent.com/6689073/177998003-e371b35b-683a-4e97-bf8a-74a698ce9fc2.png)

### Additional Information

Step to reproduce:

```bash
npx create-electron-app my-new-app --template=webpack
```

```js
// main.js
app.enableSandbox();

......

  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: "./preload.js",
    },
  });
```

```js
// preload.js
console.log(__dirname);
```

![image](https://user-images.githubusercontent.com/6689073/177998003-e371b35b-683a-4e97-bf8a-74a698ce9fc2.png)

If don't use sandbox, it will run normally, but use sandbox is more secure as the guide said.

I digged that there is some diffrence between `sandboxed_renderer` and `renderer` when handle preload script compile: `renderer` passed over `__dirname` while `sandboxed_renderer` not, Is this can be fixed? thank you for the great work.

**Comment by MarshallOfSound** [comment]
`__dirname` and `__filename` are node.js concepts.  When you enable the sandbox your scripts are evaluated as raw javascript and do not have access to a node.js context and therefore don't have values for `__dirname` or `__filename`.  This is by design
