### ISSUE TITLE
[Bug]: Running `exec` inside of a worker blocks the main thread

### ISSUE THREAD

**Issue by leolabs** [electron/electron#34865]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.10

### What operating system are you using?

macOS

### Operating System Version

macOS 12.3.1 (21E258)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I've just come across this rather strange bug. I'm running a worker_thread which runs `exec` every 2.5 seconds and reports back to the main thread when its output changes. Calling `exec` in a worker_thread shouldn't affect the main thread in any way.

### Actual Behavior

Weirdly, when I added a `setInterval` in the main thread, I noticed that it got blocked every time the command ran. It doesn't happen when I run the same script directly in Node.

Here's my code:

```js
const { Worker } = require("worker_threads");

const workerCode = `
  const { parentPort } = require("worker_threads");
  const { execSync } = require("child_process");

  setInterval(() => {
    const result = execSync("scutil --get LocalHostName").toString().trim();
    parentPort.postMessage(result.toString());
  }, 2500);
`;

const worker = new Worker(workerCode, {
  eval: true,
});

worker.on("message", (m) => {
  console.log("Hostname:", m);
});

let lastUpdate = Date.now();
let lastWarning = Date.now();
setInterval(() => {
  const newUpdate = Date.now();

  if (newUpdate - lastUpdate > 50) {
    console.warn("Something's not right...", {
      delta: newUpdate - lastUpdate,
      sinceLastWarning: newUpdate - lastWarning,
    });
    lastWarning = newUpdate;
  }

  lastUpdate = newUpdate;
}, 10);
```

Output from running this in Electron (`yarn electron test.js`):

```
$ [...]/node_modules/.bin/electron test.js
Something's not right... { delta: 138, sinceLastWarning: 2655 }
Hostname: playback
Something's not right... { delta: 96, sinceLastWarning: 2463 }
Hostname: playback
Something's not right... { delta: 136, sinceLastWarning: 2543 }
Hostname: playback
Something's not right... { delta: 135, sinceLastWarning: 2502 }
Hostname: playback
Something's not right... { delta: 132, sinceLastWarning: 2494 }
Hostname: playback
```

Output from running this in Node (`node test.js`):

```
Hostname: playback
Hostname: playback
Hostname: playback
Hostname: playback
Hostname: playback
```

### Additional Information

Even more strangely, this doesn't happen when I try to replicate the issue in Electron Fiddle with the same version of Electron.

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
