### ISSUE TITLE
[Bug]: electronjs website releases not updated since two months

### ISSUE THREAD

**Issue by ggreco** [electron/electron#34889]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.5

### What operating system are you using?

macOS

### Operating System Version

mon terey

### What arch are you using?

x64

### Last Known Working Electron version

18.3.0

### Expected Behavior

Going to https://www.electronjs.org/releases/stable

See the latest stable version for the supported releases (18.x, 19.x....)

### Actual Behavior

You get the latest versions available TWO months ago.

### Additional Information

I expected to see the latest 18.3.x stable version (18.3.5) but the website still shows 18.3.0 as the latest one ( 2 months old), I checked also for 19.x, and it shows only 19.0.0 that has been released 2 months ago.

**Comment by codebytere** [comment]
Please open this on the website repository: https://github.com/electron/electronjs.org-new
