### ISSUE TITLE
Web Serial API removed and added events are never called

### ISSUE THREAD

**Issue by Loongwoo** [electron/electron#34887]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

x64

### Expected Behavior

I want to update UI when picking a port if a serial port is plugged in or unplugged.

Test Steps:
1,  Click button to call `navigator.serial.requestPort()`
2, Show a modal to show port list in the `select-serial-port` event handler
3, Plug in or unplug a device to check the `serial-port-added` and `serial-port-removed` events

```
modal.webContents.session.on('select-serial-port', (event, portList, webContents, callback) => {
    //Add listeners to handle ports being added or removed before the callback for `select-serial-port`
    //is called.
    modal.webContents.session.on('serial-port-added', (event, port) => {
      console.log('serial-port-added FIRED WITH', port)
      //Optionally update portList to add the new port
    })
  
    modal.webContents.session.on('serial-port-removed', (event, port) => {
      console.log('serial-port-removed FIRED WITH', port)
      //Optionally update portList to remove the port
    })

    // modal.webContents.openDevTools();
    modal.webContents.send('update-list', portList);
    modal.show();

    event.preventDefault();
    ipcMain.once('serial-port', (_event, portId = '') => {
      callback(portId);
      modal.hide();
    });
  });
```

### Actual Behavior

But the `select-serial-port` and `select-serial-removed` events never called. Did I use these api in a wrong way?

### Testcase Gist URL

https://gist.github.com/0bbeeaa1c9e8f5affb6b59663870616e

**Comment by codebytere** [comment]
cc @jkleinsc

**Comment by jkleinsc** [comment]
I have a fix for this and will put up a PR shortly
