### ISSUE TITLE
[Bug]: 20-x-y nan native modules won't compile on x64 without newest electron-rebulld

### ISSUE THREAD

**Issue by VerteDinde** [electron/electron#34885]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0-alpha.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

19.0.7

### Expected Behavior

Native modules using the nan API should build correctly on x64

### Actual Behavior

Native modules using the nan API crash on x64 with a missing include for pointer compression

### Testcase Gist URL

https://gist.github.com/VerteDinde/90c7f4555c0f7ba5fd374fed3f20cbb0

### Additional Information

More information in these two PRs:
1. https://github.com/electron/electron/pull/34844
2. https://github.com/electron/electron-rebuild/pull/1023

Two tasks for us to complete before we release v20 as a stable release:

1. Include an explanation for the failure in the 20.0.0 blog post, asking people to use at least `electron-rebuild` verison 3.2.8
3. Make native modules fail to build if they don't have the right version of node-gyp and/or electron-rebuild

**Comment by nikitakot** [comment]
@VerteDinde Having problems rebuilding package which uses `nan` for Electron 20. Could it be related? Thank you.

```
nan_callbacks.h(55,23): error C2039: 'AccessorSignature': is not a member of 'v8'
```

```
"electron": "20.0.2" (V8 10.4, Node.js 16.15.0, Chromium 104)
"nan": "2.16.0
"electron-rebuild": "3.2.9"
```

**Comment by RaisinTen** [comment]
@nikitakot it's being fixed in https://github.com/nodejs/nan/pull/941

**Comment by Christian1984** [comment]
I am running into that same issue. Trying to build an electron app created with electron-forge 6.0.0-beta.65 and a native module. Consider this example:

- run `npm i https://github.com/thraaawn/winctl`
- run `npm start`
- get 

```
Preparing native dependencies: 0 / 1
C:\Users\user\.electron-gyp\20.1.4\include\node\v8-isolate.h(292,5): warning C4996: 'v8::LegacyOOMErrorCallback': Use
OOMErrorCallback (https://crbug.com/1323177) [C:\[...]\node_modules\winctl\build\w
inctl.vcxproj]
C:\[...]\node_modules\nan\nan_callbacks.h(55,23): error C2039: "AccessorSignature"
 is not a member of "v8". [C:\[...]\node_modules\winctl\build\winctl.vcxproj]`
```

I tried to manually upgrade electron-rebuild to v3.2.9 and nan to v2.16.0.

Cloning the repo of winctl to a separate directory and starting it without electron works perfectly fine. Local node version is v16.17.0.

Can anyone point me to how I can get this fixed?
