### ISSUE TITLE
[Bug]: Non-standard behavior: Electron alter the response header Content-Disposition

### ISSUE THREAD

**Issue by 9percent** [electron/electron#34896]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 with latest updates

### What arch are you using?

x64

### Last Known Working Electron version

15.3.0

### Expected Behavior

If web server response a blob with file name specified in `Content-Disposition` with encoding, for example:
server response header include:
`content-disposition: "attachment; filename*=UTF-8''filename.xlsx"`
Electron should pass server response header `Content-Disposition` as it is in XMLHttpRequest so app JavaScript can handle it correctly, should not change it's value.

### Actual Behavior

Due to the change in the PR: https://github.com/electron/electron/pull/31669
response header value `content-disposition` will be replaced if the value contains encoding info.
`content-disposition: "attachment; filename*=UTF-8''filename.txt"`
will be changed to:
`content-disposition: "attachment; filename=\"filename.txt\""`
If I inspect web request with dev tool, I can see the network panel shows the response header with original value, but in the JS XMLHttpRequest handler, I can only get the altered value instead, this should not happen as it is not expected when we need to handle the file name in the header with JS code.

### Additional Information

The commit:
https://github.com/electron/electron/commit/24b02d68a704dff04843b90b5bbafd93d9c362f1
The PR:
https://github.com/electron/electron/pull/31669
Some doc online:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
