### ISSUE TITLE
 BrowserWindow - center option doesn't work correctly with multi monitor set-up on Linux

### ISSUE THREAD

**Issue by petrvecera** [electron/electron#3490]
When you have multi monitor set-up and you start `BrowserWindow` with option center:

``` javascript
new BrowserWindow({width: 800, height: 600, center: true});
```

The new window is opened in the center of all the monitors, instead of the center of primary one. Basically it counts width of all monitors and put the window in the center of it.

OS: Linux only.
Windows, OS X are fine ( window is opened in the center of main monitor)

Tested with:  Electron 0.35.0, Ubuntu 14.04, Linux Mint 17.2

_This is pretty annoying when you are showing just a little window._
Thanks

**Comment by zcbenz** [comment]
Can you try whether this problem is still there in 0.36.2?

**Comment by petrvecera** [comment]
The issue is still there.
Tested with: Electron 0.36.2 and Linux Mint 17.2

**Comment by Krisseck** [comment]
This issue also affects me. Running [OpenBazaar-Client](https://github.com/OpenBazaar/OpenBazaar-Client) version 1.1.6 which has Electron 0.37.6.

OS: Elementary OS Freya

[The issue on OpenBazaar-Client repo](https://github.com/OpenBazaar/OpenBazaar-Client/issues/1664)

**Comment by MiffOttah** [comment]
I know this is an old issue, but it's still open and still a problem if you're using the default centering code, plus it's the top google result for "electron linux multiple monitors". I ended up working around this issue by using the [screen API](http://electron.atom.io/docs/api/screen/) to get the bounds of the primary monitor and use that to calculate the start position. Here's my code if it'll be helpful to anyone.

    let bounds = electron.screen.getPrimaryDisplay().bounds;
    let x = bounds.x + ((bounds.width - WINDOW_WIDTH) / 2);
    let y = bounds.y + ((bounds.height - WINDOW_HEIGHT) / 2);
    mainWindow = new BrowserWindow({width: WINDOW_WIDTH, height: WINDOW_HEIGHT, x: x, y: y});

**Comment by hovancik** [comment]
Here is my experience with `this issue: https://github.com/electron/electron/issues/3490

Someone should look into this, I guess.

**Comment by singhshashi** [comment]
Looks like this issue has been hanging around for some time. Any ETA for the fix?

**Comment by greemin** [comment]
Still an issue on Ubuntu v16.04

**Comment by AlexVFornazieri** [comment]
@MiffOttah Your code work for me initially, until recently, but now, I believe that after recent updates, it simply stopped, the window came back to appear between the two screens, some suspicion of what may have happened? Thank you all for the attention!

Environment:
    Electron v1.8.1,
    Node v6.12.2,
    OS: Ubuntu 17.10 (Unity)

My code:
```
function createSplash() {
  /**
   * Configurações da tela carregamento
   */
  const WINDOW_WIDTH = 500;
  const WINDOW_HEIGHT = 401;

  //Definindo centro da tela principal
  let bounds = screen.getPrimaryDisplay().bounds;
  let x = bounds.x + ((bounds.width - WINDOW_WIDTH) / 2);
  let y = bounds.y + ((bounds.height - WINDOW_HEIGHT) / 2);

  splashWindow = new BrowserWindow({
    width: WINDOW_WIDTH,
    height: WINDOW_HEIGHT,
    x: x,
    y: y,
    center: true,
    frame: false,
  });

  splashWindow.loadURL(splashURL);

  splashWindow.on("closed", () => {
    splashWindow = null;
  });
}
```

**Comment by rvanhoepen** [comment]
@AlexVFornazieri Had the same issue. Try ensuring that x and y are integers.

let x = Math.ceil(bounds.x + ((bounds.width - WINDOW_WIDTH) / 2));
let y = Math.ceil(bounds.y + ((bounds.height - WINDOW_HEIGHT) / 2));

**Comment by AlexVFornazieri** [comment]
@rvanhoepen, its works! Thanks!

**Comment by Grim102** [comment]
Running Ubuntu 18.04, this worked for me.

`const {width, height} = electron.screen.getPrimaryDisplay().workAreaSize

    let x = width / 4
    let y = height / 4

    win = new BrowserWindow({
        width: width / 2, 
        height: height / 2,
        x: x,
        y: y
    })`

**Comment by Astrych** [comment]
Tested with electron 4.0.3 and it works now (Mint 19). Fixed?

**Comment by sachetsharma1** [comment]
I am facing this issue with electron@4.0.6. 
window.open({ height: 800, width: 800, center: true })
window.getPosition(): [ 3920, 88 ]
WIndow is centered on the third monitor

**Comment by abdolence** [comment]
It is June 2019.
And it still not fixed :/ I'm not even using electron myself, but this seems popular for tools I'm using occasionally, and all of them bump into this. One of those tools even shows a form with inputs in a splash screen which because of this issue looks ridiculous.

**Comment by tonymays** [comment]
I _**hacked**_ around a solution for centering a child window on its parent regardless of the number of displays.  I used the electron-window-state package to get me the x, y, width and height of the parent window window.  I stored those in variables so they could be used in my child window create function.  Inside my child create window function I added the following:    let childX = mainWindowX + Math.round(mainWindowWidth/2) - 175;
    let childY = mainWindowY + Math.round( mainWindowHeight/2) - 63;
    newFileWindow = new BrowserWindow({
        webPreferences: {
           nodeIntegration: true
        },
        x: childX,
        y: childY,
        title: 'New File',
        parent: mainWindow,
        center: true,
        modal: true,
        resizable: false,
        alwaysOnTop: true,
        show: false,
        width: 350,
        height: 125,
    })
It is a HACK but seems to be holding.

**Comment by tonymays** [comment]
Please note the 175 and 63 in the above could equates to half my child window dimensions. Go a little lazy there ...

**Comment by hovancik** [comment]
@tonymays could you format your code for readability? 
```javascript
let x
let y
```

**Comment by gandalius** [comment]
im use "electron": "^4.2.12" and this code work for me

`win.center();`

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by hovancik** [comment]
Did anyone try to reproduce this? I am trying in Debian KDE and seems to work fine with electron 12. Would be nice to check in another DEs. I remember having issues with XFCE

**Comment by 10n37** [comment]
> I know this is an old issue, but it's still open and still a problem if you're using the default centering code, plus it's the top google result for "electron linux multiple monitors". I ended up working around this issue by using the [screen API](http://electron.atom.io/docs/api/screen/) to get the bounds of the primary monitor and use that to calculate the start position. Here's my code if it'll be helpful to anyone.
> 
> ```
> let bounds = electron.screen.getPrimaryDisplay().bounds;
> let x = bounds.x + ((bounds.width - WINDOW_WIDTH) / 2);
> let y = bounds.y + ((bounds.height - WINDOW_HEIGHT) / 2);
> mainWindow = new BrowserWindow({width: WINDOW_WIDTH, height: WINDOW_HEIGHT, x: x, y: y});
> ```

Don't forget to use Math.trunc() to avoid errors. 
```
const window = BrowserWindow({
  x: Math.trunc(x), 
  y: Math.trunc(y)
})
```
BrowserWindow.x, BrowserWindow.y and BrowserWindow.setPosition() accepts only `integers`.
