### ISSUE TITLE
[Feature Request]: Support for filling authentication dialogs with saved usernames/passwords.

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#34902]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Users to able to save the username/password like in the Chrome

### Proposed Solution

To work out of the box

### Alternatives Considered

None

**Comment by MarshallOfSound** [comment]
Electron shouldn't be getting into the password manager business, the APIs required to implement such functionality are already exposed.  Electron won't be hooking or exposing Chrome's password manager functionality
