### ISSUE TITLE
[Bug]:  Unable to reload the window

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#34919]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

Windows

### Operating System Version

Window 10 10.0.19044.1826

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

To refresh the window from the keyboard shortcut F5 and also using window.reload/webContents.reload;

### Actual Behavior

Nothing happens

### Testcase Gist URL

https://gist.github.com/b0e06a31f30cd288670f11673ebcba1e

**Comment by pejman1** [comment]
I have same problem with the latest version of the electron 21.2.3 and windows 11

**Comment by pejman1** [comment]
@codebytere
