### ISSUE TITLE
[Bug]: Very slow silent printing on Windows

### ISSUE THREAD

**Issue by sridharpg** [electron/electron#34922]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.7

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Expected Behavior

Silent print should be completed within a second, for simple pages.

### Actual Behavior

Windows 11: Silent printing takes about 10 seconds to complete. PDF conversion takes about ~3.5 seconds to complete.

### Testcase Gist URL

https://gist.github.com/sridharpg/4d4504687e4d12d13e4d8717d336039a

### Additional Information

Mac OS: Silent printing is very fast, takes 500ms to complete. PDF conversion takes 100ms to complete. The slow printing is observed only in Windows build.

**Comment by sridharpg** [comment]
I must add that the printing in nw.js is much faster. Prints within a second in Windows.

**Comment by eduardoMendozaO2** [comment]
Buenos días, 

Me está sucediendo lo mismo. Cuando llamo a la función `mainWindow.webContents.print` tarda 6 segundos en comenzar con la impresión. ¿Existe alguna forma de agilizar el proceso?

Good morning,

The same thing is happening to me. When I call the `mainWindow.webContents.print` function it takes 6 seconds to start printing. Is there any way to speed up the process?

![code_print](https://user-images.githubusercontent.com/114989746/193787381-cd5bf106-80e1-474b-9915-cd802c95519a.png)
![time_print](https://user-images.githubusercontent.com/114989746/193787388-de33bf15-df75-4b00-83db-da22e29356f6.png)

**Comment by sridharpg** [comment]
While the printing time has come down from 10 secs to around 4 secs now(in my machine), it's still much slower than NWJS. Direct chrome printing is faster too. This can be reproduced in the latest 21.1.1 version too.

**Comment by eduardoMendozaO2** [comment]
Subiendo la versión de Electron 21.2.3 tarda bastante menos. De momento así me sirve.

Uploading the version of Electron 21.2.3 takes much less. That's how it works for me at the moment.
