### ISSUE TITLE
[Bug]: crypto.getHashes() can only get a subset of hash algorithm. SM3 is needed specifically

### ISSUE THREAD

**Issue by lanyusan** [electron/electron#34925]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 36

### What arch are you using?

x64

### Expected Behavior

`crypto.getHashes() ` should return all hash algorithms supported by node, which is as below on node v16.16.0

```
[
  'RSA-MD4',
  'RSA-MD5',
  'RSA-MDC2',
  'RSA-RIPEMD160',
  'RSA-SHA1',
  'RSA-SHA1-2',
  'RSA-SHA224',
  'RSA-SHA256',
  'RSA-SHA3-224',
  'RSA-SHA3-256',
  'RSA-SHA3-384',
  'RSA-SHA3-512',
  'RSA-SHA384',
  'RSA-SHA512',
  'RSA-SHA512/224',
  'RSA-SHA512/256',
  'RSA-SM3',
  'blake2b512',
  'blake2s256',
  'id-rsassa-pkcs1-v1_5-with-sha3-224',
  'id-rsassa-pkcs1-v1_5-with-sha3-256',
  'id-rsassa-pkcs1-v1_5-with-sha3-384',
  'id-rsassa-pkcs1-v1_5-with-sha3-512',
  'md4',
  'md4WithRSAEncryption',
  'md5',
  'md5-sha1',
  'md5WithRSAEncryption',
  'mdc2',
  'mdc2WithRSA',
  'ripemd',
  'ripemd160',
  'ripemd160WithRSA',
  'rmd160',
  'sha1',
  'sha1WithRSAEncryption',
  'sha224',
  'sha224WithRSAEncryption',
  'sha256',
  'sha256WithRSAEncryption',
  'sha3-224',
  'sha3-256',
  'sha3-384',
  'sha3-512',
  'sha384',
  'sha384WithRSAEncryption',
  'sha512',
  'sha512-224',
  'sha512-224WithRSAEncryption',
  'sha512-256',
  'sha512-256WithRSAEncryption',
  'sha512WithRSAEncryption',
  'shake128',
  'shake256',
  'sm3',
  'sm3WithRSAEncryption',
  'ssl3-md5',
  'ssl3-sha1',
  'whirlpool'
]

```

### Actual Behavior

It returns just a very limited subset
```
[
  'md4',        'md5',
  'ripemd160',  'sha1',
  'sha224',     'sha256',
  'sha384',     'sha512',
  'sha512-256'
]
```

### Additional Information

I need to use some less popular hash algorithms in an Electron app and found out this problem.Specifically the one i need is `sm3`. 

Is it because Electron build of node offers such limited subset of hashes or is there a trick to get all hashes?

I really need this. I understand Node's hashes are actually provided by openssl and are fast compared to pure JS.

Thanks in advance.

**Comment by prettydiff** [comment]
https://github.com/electron/electron/issues/30176

**Comment by codebytere** [comment]
This is not a bug - this is a function of Electron only having access to BoringSSL, Google's fork of OpenSSL with a much more limited surface area.
