### ISSUE TITLE
[Bug]: run electron on kali linux amd64 root failed,how to run on root

### ISSUE THREAD

**Issue by passerbyo** [electron/electron#34927]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Other Linux

### Operating System Version

kali linux

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

run successful

### Actual Behavior

[0715/041438.326273:FATAL:electron_main_delegate.cc(292)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/electron-quick-start/node_modules/electron/dist/electron exited with signal SIGTRAP

**Comment by RaisinTen** [comment]
Hi! As you can see in the error message, this is because of an issue in Chromium, so I feel that it's unlikely that we'll be able to do much about it. I'm curious why you need to run electron as a root user?

**Comment by chenyuncai** [comment]
> I'm curious why you need to run electron as a root user

? because maybe we cannot ensure out clients is always non-root user. some people has only a root user in his daily usage.
