### ISSUE TITLE
[Bug]: devtools_app.js is not send with MIME type

### ISSUE THREAD

**Issue by BananaAcid** [electron/electron#34935]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

macOS

### Operating System Version

12.4

### What arch are you using?

x64

### Expected Behavior

For future compatibility, dev tools should be send using the correct mime type.

### Actual Behavior

It generates the following error:
"Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.", source: devtools://devtools/bundled/entrypoints/devtools_app/devtools_app.js

### Additional Information

Default electron project example, run with `electron   -r ts-node/register --no-warnings  index.ts` does work as intended with everything else in the example, except when it comes to `mainWindow!.webContents.openDevTools();`

Test project here: https://github.com/BananaAcid/Simple-Electron-Kiosk/tree/TypeScript

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Please use [Electron Fiddle](https://github.com/electron/fiddle) to create a standalone (no external dependencies) testcase and publish it as a [gist](https://gist.github.com), then link to it here.

- Even if you have a code snippet or a git repository that show the testcase, please put it in a gist. This lets maintainers triage issues more effectively. It also ensures that we're testing the exact same issue that you're seeing!

- Please avoid external dependencies in the test. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.

- If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). This lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to the gist in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by BananaAcid** [comment]
Unfortunately, the Electron fiddle blocks my efforts, not allowing me to create ts files as well as fixing the start params to use ESM.

But the test project above shows the simple problem (security issue with loading devtools js)  https://github.com/BananaAcid/Simple-Electron-Kiosk/tree/TypeScript

**Comment by BananaAcid** [comment]
Any progress / has anyone managed to have a look at this?
