### ISSUE TITLE
[Bug]: transparent windows have no animation on Windows

### ISSUE THREAD

**Issue by EGo14T** [electron/electron#34930]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 21H2

### What arch are you using?

x64

### Expected Behavior

Transparent windows would show an animation when minimized or maximized.

```js
  mainWindow = new BrowserWindow({
    show: false,
    width: 370,
    height: 610,
    frame: false,
    resizable: false,
    transparent: true,
    webPreferences: {
      nodeIntegration: false
    },
  });
```

### Actual Behavior

There is no animation.

![test](https://user-images.githubusercontent.com/28916447/179241416-0d7314e2-897d-40b6-bcbb-476aa57f2ba0.gif)

**Comment by mlaurencin** [comment]
@EGo14T I am having a bit of trouble reproducing your issue with the code you provided. 

If you are still experiencing this, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue and no third-party dependencies? Triaging code with third-party dependencies is usually not feasible for a small team like Electron's. Also [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make this test case, please link to it in a follow-up comment.

Thanks in advance! Your help is appreciated.
