### ISSUE TITLE
Menu Item of type separator ignores visible option

### ISSUE THREAD

**Issue by andre-gois** [electron/electron#3494]
This happen at least on Windows

Menu Itens with 'type' set to 'separator' stay on the menu even if I set visible: false.

**Comment by sanuj** [comment]
@zcbenz I would like to work on this but I'm new to electron. Can you help me get started? I'm reading the electron/docs for now.

**Comment by ragingwind** [comment]
As I know that at `SimpleMenuModel::IsVisibleAt`, always returns true if type of menu is `separator` whether its visible is true or not

**Comment by zcbenz** [comment]
After looking into this, I found that the native menu on macOS does not support hiding separator items, so I'm closing this as won't fix.

**Comment by tommoor** [comment]
Sorry to revive an old issue but I don't see how the macOS limitation is relevant… couldn't electron just filter the menu items before passing to the OS layer?

**Comment by hatton** [comment]
I'm removing anything not explicitly hidden:

``items = items.filter(item => item.visible !== false);``
