### ISSUE TITLE
[Feature Request]: Support more crypto algorithms

### ISSUE THREAD

**Issue by lanyusan** [electron/electron#34942]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

As reported in issue  #34925, which is closed as not a bug, since electron is built with boring ssl and it works as intended, I decide to raise a feature request.

Please enhance crypto to support more algorithm. 

My specific  need now is sm3 hash algorithm. But I foresee in future I would need more hash / cipher algorithm support from electron.

### Proposed Solution

Build electron with openssl which supports a much larger set of algorithm.

Nodejs itself uses opensssl.

### Alternatives Considered

None.

**Comment by MarshallOfSound** [comment]
I think we've discussed it in the past (can't find a reference though) and adding support for algorithms that boringssl doesn't support is simply not a thing that we can / will do.  You can't load boringssl and openssl in the same exec due to symbol name conflicts (which is why we had to chose boringssl in the first place).

For some algotithms that are implemented in boringssl but not exposed by default we have turned them on in the past to improve compatibility, but in general boringssl exposes a good secure subset of algorithms which should serve 99+% of usecases.

**Comment by lanyusan** [comment]
> I see your point about the disparity between crypto algorithms supported in Node.js and in Electron, but striving for algorithm-to-algorithm compatibility seems out-of-scope for Electron.
> 
> I don't think I've seen this discussed by maintainers so I'll leave this ticket open in case someone else wants to weigh in, but IMO adding support for algorithms not in Boring would add new dependencies and more maintenance burden for the project compared to the current use of Boring, which is (relatively) easy for Electron due to Boring's ties to Chromium.
> 
> It looks like there are 3rd party packages out there that support sm3 at https://www.npmjs.com/search?q=sm3 . Have you tried those out?

Yes I have looked the JS sm3 ones. Most of them load file to memory once as a whole so they couldn't handle large files.

And the only one calculates by chunks got the hash result one. Also JS hash is slow compared to openssl based.

I have tried to use native built libraries but when they are bundled in production in Mac with signature, the native libs are often unsigned so  will be complained by MacOs.  

Is it possible to bundle openssl crypto as a separate crypto module, say `cryptoPlus` so it wouldn't break chromium compatibility but could also support openssl's wide range of crypto algorithms.

**Comment by lanyusan** [comment]
> I think we've discussed it in the past (can't find a reference though) and adding support for algorithms that boringssl doesn't support is simply not a thing that we can / will do. You can't load boringssl and openssl in the same exec due to symbol name conflicts (which is why we had to chose boringssl in the first place).
> 
> For some algotithms that are implemented in boringssl but not exposed by default we have turned them on in the past to improve compatibility, but in general boringssl exposes a good secure subset of algorithms which should serve 99+% of usecases.

Just an idea.

Is it possible to bundle openssl crypto as a separate crypto module in electron, say cryptoPlus so it wouldn't break chromium compatibility but could also support openssl's wide range of crypto algorithms?

I mean web3 is already here and 4/5 are coming. Crypto would be more important for the ecosystem.

**Comment by MarshallOfSound** [comment]
> Is it possible to bundle openssl crypto as a separate crypto module in electron, say cryptoPlus so it wouldn't break chromium compatibility but could also support openssl's wide range of crypto algorithms?

No, the issue isn't the `crypto` module namespace.  The problem is the underlying symbols in the generated executable / shared library.
