### ISSUE TITLE
[Bug]: Error: Illegal invocation: Function must be called on an object of type NativeImage

### ISSUE THREAD

**Issue by mohitsharma80** [electron/electron#34953]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

19.0.6

### Expected Behavior

Unable to take a screenshot and with webview tag and facing the Error: Illegal invocation: Function must be called on an object of type NativeImage after electron upgrade tp the latest version. I am not able to downgrade the electron version as I facing another issue with the surface machines.

Here is the code for a screenshot 
```
const webview = <webview src="path" class="webview__3kBDE" style="width: 768px; height: 576px; margin-top: 0px; margin-left: auto; margin-right: auto;"></webview>

const rawImage = await webview.capturePage()
const URL = rawImage.toPNG()
```

### Actual Behavior

I am able to take a screenshot for the webview tag, I am using reactjs with electron.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Please use [Electron Fiddle](https://github.com/electron/fiddle) to create a standalone (no external dependencies) testcase and publish it as a [gist](https://gist.github.com), then link to it here.

- Even if you have a code snippet or a git repository that show the testcase, please put it in a gist. This lets maintainers triage issues more effectively. It also ensures that we're testing the exact same issue that you're seeing!

- Please avoid external dependencies in the test. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.

- If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). This lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to the gist in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sunknudsen** [comment]
@mohitsharma80 Experiencing same issue when calling `.toDataURL()` from renderer process… that said, calling same function from main works so either this is a bug or a context limitation.

**Comment by mohitsharma80** [comment]
I found the answer [here](https://stackoverflow.com/questions/73021491/electron-error-function-must-be-called-on-an-object-of-type-nativeimage) and my issue is fixed now.

**Comment by simo-an** [comment]
At latest electron version, set `contextIsolation: false` works
```
const w = new BrowserWindow({ webPreferences: { contextIsolation: false } })
```
