### ISSUE TITLE
window.setSize doesn't work always

### ISSUE THREAD

**Issue by meghajayakumar** [electron/electron#34954]
**Issue Details**
Electron Version: v8.5.5
Operating System: Windows 10 
Last Known Working Electron version: Unknown

Login page is smaller in size than the other pages in my project. window.setSize only works when the login page is opened first. When someone logs in, the window size changes to big screen, this is also achieved using setSize and works without any problem. Again when someone logs out, the setsize method is invoked, but the screen size remains unchanged.

**Code used:**
```
ipcMain.on('resize-screen', function() {
    window.setSize(400,700);
    window.center();
    window.resizable = false;
  });
```

Have debugged the code and made sure that this event has been triggered. The window.center works but not the setSize.

**Comment by exaggerated-dream** [comment]
I ran into a similar problem and still haven't been able to solve it?
