### ISSUE TITLE
[Bug]: Spawning another instance on Mac requires an additional click on the icon on dock

### ISSUE THREAD

**Issue by lenchvolodymyr** [electron/electron#34951]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.3.1, 19.0

### What operating system are you using?

macOS

### Operating System Version

macOs Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

When spawning an electron app, that uses `app.requestSingleInstanceLock()`, it immediately starts and stays in focus and doesn't require an additional click on the dock panel in MacOS

```
app.requestSingleInstanceLock();

const spawn = require('child_process').spawn;
const subprocess = spawn(process.execPath, args, {
        detached: true,
        stdio: 'ignore',
});
```

### Actual Behavior

When electron app, that uses `app.requestSingleInstanceLock()`, is spawned it shows up on the Dock panel of MacOS and nothing happens (`app.whenReady` is not called), until you click on the icon on the Dock panel.

![image](https://user-images.githubusercontent.com/32545092/179494698-482b7d64-ab7f-4117-b727-cc44918d78a3.png)
the 

### Testcase Gist URL

https://github.com/lenchvolodymyr/electron-spawn-issue/blob/main/index.js

### Additional Information

The behavior is the same on Big Sur M1

**Comment by lenchvolodymyr** [comment]
moving `app.requestSingleInstanceLock()` under `whenReady` made the app works as expected:

```
app.whenReady().then(() => {
    app.requestSingleInstanceLock();
    // ...
})
```

**Comment by MarshallOfSound** [comment]
Spawning your own application directly actually _doesn't_ correctly "launch" the app on macOS.  You have to open it via the `open` command rather than executing your binary directly.  E.g. `open Foo.app` instead of `Foo.app/Contents/MacOS/Foo`
