### ISSUE TITLE
[Bug]: Linux window blur unexpectedly.

### ISSUE THREAD

**Issue by sohobloo** [electron/electron#34967]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.4 LTS

### What arch are you using?

x64

### Last Known Working Electron version

16.0.1

### Expected Behavior

Menu popup works as expected.

### Actual Behavior

![F7BC5387-E43E-4c91-BF8E-2A25C6BCF0D8](https://user-images.githubusercontent.com/13310861/179708436-0e355542-cec6-4c2c-b7b4-8f8fe877b046.png)

Steps:
1. Double click the dragable region which set as `-webkit-app-region` within a `BrowserView` to maximize the window.
2. Click the popup menu button, a context menu should shown.
3. If can not reproduce, try to unmaximize / maximize the window and click the popup menu button twice.
4. Once issue occurs, mouse down on the dragable region will cause window blur and mouse up will let window re-focus; Menu pop up will cause blur then focus and the context menu flash then hide.

### Testcase Gist URL

https://gist.github.com/445ba4fb232a9c1e211c4cc99e367637

### Additional Information

Some Linux distributions have no such issue.

**Comment by ckerr** [comment]
It doesn't always reproduce, but I am seeing this bug in both 19.0.8 and 19.0.0.

I'm not able to trigger it in 19.0.0-alpha.1 though. I'll see if I can bisect this to figure out when it broke.

**Comment by ckerr** [comment]
Looks like it broke between 19.0.0.alpha-3 and -4

**Comment by sohobloo** [comment]
It backs to normal after calling `browserWindow.hide()` and `browserWindow.show()`. But that's not a user imperceptible workaround.

**Comment by sohobloo** [comment]
bump
