### ISSUE TITLE
[Bug]: `BrowserWindow.getTrafficLightPosition()` returns `{ x: 0, y: 0 }`

### ISSUE THREAD

**Issue by bpasero** [electron/electron#34969]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.5

### What operating system are you using?

macOS

### Operating System Version

12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Either `BrowserWindow.getTrafficLightPosition()` should return `undefined` if not specified or the actual value it has.

### Actual Behavior

`BrowserWindow.getTrafficLightPosition()` returns `{ x: 0, y: 0 }` when not set custom.

**Comment by ckerr** [comment]
The docs say:

> #### `win.getTrafficLightPosition()` _macOS_
> 
> Returns `Point` - The custom position for the traffic light buttons in frameless window.

This doc isn't as clear as it could be (it should be explicit on what gets returned when there's no custom value) but I agree it ought to be `undefined` -- (a) that follows more to the spirit of the existing docs, and (b) otherwise there's an edge case because it's impossible to know whether a return value of `(0, 0)` indicates a custom value or is just the default.

**Comment by MarshallOfSound** [comment]
> This was done initially for [backwards compatibility reasons](https://github.com/electron/electron/pull/26789/files#diff-9e3935b7f7b31cb73a8e976e9725bab5c20c499dc5d1e33c7c7f62e3f90b72c9R853) - @zcbenz do you think we might want to change this?

Changing this isn't viable, it would be an undetectable breaking change for lots of apps.  We could add a new API `getCustomTrafficLightPosition` (or something similarly named) that returns `null` when their is no custom position and update the setter that takes `null` as a valid argument to reset the position to the system default.

Updating the setter is `semver/minor` but changing an existing getter to potentially return `null` is `semver/major`.  Adding a new API and deprecating the old one for removal in ~two releases is probably the best option.

**Comment by zcbenz** [comment]
The API behaved this way since it was introduced, so basically all existing apps are relying on it and we can not just change the behavior. I agree we should introduce a new API and deprecate this one.

**Comment by bpasero** [comment]
bump
