### ISSUE TITLE
[Bug]: Cannot move window to secondary display immediately after leaving full screen [macOS]

### ISSUE THREAD

**Issue by Nic0S** [electron/electron#34976]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

If you attempt to move a window to a secondary display, using setBounds, immediately after that window exits fullscreen (using the 'leave-full-screen' event) it should correctly move to that display.

### Actual Behavior

If you attempt to move a window to a secondary display, using setBounds, immediately after that window exits fullscreen the window will be moved somewhere on the primary display rather than the secondary display. The window height/width are set correctly but not x/y.

A 1 second wait in between the 'leave-full-screen' event and the setBounds call seems to result in the correct behavior of moving to the second display.

I've tested this on 18.3.5, 19.0.0, 19.0.8, 20.0.0-beta.10 and all seem to have it, didn't try on anything older.

I believe a second display is needed to repro this, moving within the same display seems to work.

Thanks for taking a look!

### Testcase Gist URL

https://gist.github.com/f7052a473ea682ce21d4bdbe8027151c

**Comment by Nic0S** [comment]
bump

**Comment by juanrgm** [comment]
Same case with Windows 10 and Electron 28.2.0.
