### ISSUE TITLE
[Feature Request]: Method to wait for user login on Windows

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#34981]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

On Windows 11 the app `ready` event fires before the user logs in, which means that if you rely on it for some activity, for example showing a notification, it could very easily be missed.

### Proposed Solution

Add an event for when the user logs in

### Alternatives Considered

I can't conceive of any workable alternative except for trying to wait for [`process.env.USERNAME`](https://github.com/electron/electron/issues/4343) to populate - but for all I know it's already populated prior to the user actually logging in and then it would not be suitable. Unfortunately I don't have a development machine available where I can readily test this.

**Comment by MarshallOfSound** [comment]
I don't believe it is possible for an application to launch without running under a user context (unless you are running as a `SYSTEM` service which I'd have numerous questions about 😆).  Which means the only way the app is running and the user isn't "logged in" is actually when the user **is** logged in but they are on the lock screen.

In which case some combination of `resume`, `lock-screen` and `unlock-screen` from `powerMonitor` are probably what you want to observe.  Specifically between `lock-screen` and `unlock-screen` you could avoid sending notifications

**Comment by Slapbox** [comment]
Weird! We're definitely not running as `SYSTEM`.

I guess in Windows 11 it logs users in and simply locks the screen instantly? Because the app has definitely run and executed logic before the user has actually logged in for the first time, at least as far as the Windows login GUI goes.

I'll try to investigate this a bit more.
