### ISSUE TITLE
[Bug]: Electron crash report doesn't log in backtrace 

### ISSUE THREAD

**Issue by meghajayakumar** [electron/electron#34988]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

8.5.5

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

CrashReporter should log electron crash reports to backtrace. 

### Actual Behavior

Crashreporter doesn't log crashes to backtrace. Have tested using process.crash and it doesn't log electron crashes to backtrace. 

Implemented as follows:

const { crashReporter } = require('electron');

crashReporter.start({
  productName: 'App name',
  companyName: 'Name',
  submitURL: 'https://submit.backtrace.io/appname/3**********************************3/minidump',
  uploadToServer: true,
});

**Comment by codebytere** [comment]
v8.5.5 is not supported - the oldes supported version is v17. Please demonstrate that this issue replicates on supported versions, or we will need to close this issue in 10 days. Thank you!

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
