### ISSUE TITLE
[Bug]: node.js stops working randomly in renderer process with node integration on

### ISSUE THREAD

**Issue by Fnll** [electron/electron#34989]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.9

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

x64

### Expected Behavior

```
window.require('fs').writeFile("/path/to/test.log", "hello world", function() {
  console.log('done')
})
```
1. got a file named `test.log` with content "hello world"
2. display 'done' when the task complete

### Actual Behavior

1. got a file named `test.log` **without** content "hello world"
2. **not** display 'done' when the task complete.

![image](https://user-images.githubusercontent.com/22774281/179938316-57c410fe-10cc-4ad8-b4db-e6d681a5944e.png)

### Additional Information

I found a lot related issues though it's said been fixed at v12.x

https://github.com/electron/electron/issues/22119
https://github.com/electron/electron/issues/28154

**Comment by codebytere** [comment]
@Fnll v16 is no longer supported - please demonstrate that it replicates on a supported version (v18 and up) for this issue to stay open. Additionally, please provide a reproducible sample via gist., using something like [Fiddle](https://github.com/electron/fiddle)

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
