### ISSUE TITLE
[Bug]: BrowserWindow crashes after web worker calls ipcRenderer.invoke

### ISSUE THREAD

**Issue by lyswhut** [electron/electron#34992]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.10

### What operating system are you using?

Windows

### Operating System Version

windows 10 21H1

### What arch are you using?

x64

### Expected Behavior

Can call ipcRenderer.invoke or ipcRenderer.send normally in the web worker

### Actual Behavior

BrowserWindow crashes after web worker calls ipcRenderer.invoke or ipcRenderer.send

### Testcase Gist URL

https://gist.github.com/f0c0a60e0d5dbee10cc7680c0aa74c03

**Comment by codebytere** [comment]
This isn't a bug - using IPC requires a render frame, which a worker doesn't and can't have.

**Comment by astoilkov** [comment]
Maybe not a bug but it took me days to discover this problem and understand why our Web Worker is crashing. Maybe you can just handle the error and throw a user friendly error.
