### ISSUE TITLE
[Feature Request]: How to get the most foreground application

### ISSUE THREAD

**Issue by adonis-lsh** [electron/electron#35012]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

MacOS have a api of name is frontmostApplication, it can get the most foreground application, electron how to call it

### Proposed Solution

Directly call poppy's API method

### Alternatives Considered

none

**Comment by MarshallOfSound** [comment]
Electron will not provide interfaces into every possible permutation of native APIs, in this case you could implement a very simple native module that calls the underlying `frontmostApplication` API and returns the information your apps cares about in JS form
