### ISSUE TITLE
[Bug]: did-start-loading not triggering on window.open();

### ISSUE THREAD

**Issue by vishnuc** [electron/electron#35020]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

macOS

### Operating System Version

Mac OS monterey version 12.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

19.0.8

### Expected Behavior

"did-start-loading" should work on window.open

### Actual Behavior

"did-start-loading" not  working on window.open

### Additional Information

```
 loadingx = new BrowserWindow({ width: 300, height: 300, transparent: true, frame: false, alwaysOnTop: true });
  loadingx.loadURL(`file://${__dirname}/splash.html`);

  window.once("ready-to-show", () => {
    loadingx.hide();
    window.show();
  });

  window.webContents.on("did-start-loading", () => {
    loadingx.show();
  });

  window.webContents.on("did-stop-loading", () => {
    loadingx.hide();
  });

 window.webContents.setWindowOpenHandler(({ url }) => {
    return {
      action: "allow",
      overrideBrowserWindowOptions: {
        show: true,
        backgroundColor: "black",
        webPreferences: {
          transparent: true,
          preload: path.join(__dirname, "winload.js"),
        },
      },
    };
  });
```

I use above code to show splash screen when pages are loading , but its not working when i open url via window.open , I dont want to create new browser window , as i lose session.

**Comment by MarshallOfSound** [comment]
You aren't attaching a `did-start-loading` handler to the child window opened, you would need to listen to something like the [`browser-window-created`](https://www.electronjs.org/docs/latest/api/app#event-browser-window-created) and add the listeners there too

**Comment by vishnuc** [comment]
hi , window.open() is done via external webpage renderer process...how do i attact did-start-loading to it ? can i get small example , thanks.
