### ISSUE TITLE
[Bug]: The setAsDefaultProtocolClient() converts all arguments from array in the single line

### ISSUE THREAD

**Issue by MaksimDedov** [electron/electron#35021]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 

### What arch are you using?

x64

### Expected Behavior

When executing the code below: 
```
const appArgs = ["--arg1=1", "--arg2=2"];
app.setAsDefaultProtocolClient("prefix", process.execPath, appArgs);
```
all arguments from the array should be separated
The row in the Regedit should look like this: 
`"{path to .exe}" "--arg1=1" "--arg2=2" "%1"`

### Actual Behavior

The actual row in the Regedit is
`"{path to .exe}" "--arg1=1 --arg2=2" "%1"`

That's why the second instance of Electron couldn't rise up for me

**Comment by mesner** [comment]
Fixed in https://github.com/electron/electron/pull/32953
