### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by albu77** [electron/electron#35029]
Can't understand why even after participating a lot on crowdin, the french documentation still contains so many mix of english and french. Seems there is no more proof reader and I didn't receive any news of my last wrong translation submit. So Actually I've stopped working for nothing on this french translation

**Comment by MarshallOfSound** [comment]
Translations are managed by the website repository, if you have systemic issues with our translations please raise issues on https://github.com/electron/electronjs.org-new
