### ISSUE TITLE
[Bug]: setIgnoreMouseEvents with forward: true causes other windows to flicker while dragging [windows]

### ISSUE THREAD

**Issue by Nic0S** [electron/electron#35030]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.9

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H1

### What arch are you using?

x64

### Expected Behavior

Creating a hidden second window with `setIgnoreMouseEvents(true, {forward: true})` should not affect window dragging behavior for other windows in the same app.

### Actual Behavior

Steps to repro:

1. Create a normal electron window
2. Create a second hidden window, call `setIgnoreMouseEvents(true, {forward: true})` on it.
3. Start dragging the window from step 1 around on your screen. For me this causes it to flicker to a different position while I'm dragging it

Thanks for taking a look!

### Testcase Gist URL

https://gist.github.com/7d76e74221c18438d69dbc17cacf21f1

**Comment by guildantix** [comment]
I am also having the same issue.  I was able to work around it disabling the forwarding on my main window's 'will-move' and 'will-resize' events, then using a timeout to turn the mouse forwarding back on when the user stops moving/resizing.

```ts
        win.on( 'will-move', e => {

            // If a timeout for resuming mouse forwarding is active, let's cancel it.
            if ( this.#resumeRendererMouseForwardingTimeout != null ) {
                clearTimeout( this.#resumeRendererMouseForwardingTimeout );
                this.#resumeRendererMouseForwardingTimeout = null;
            }

            // Tell renderer to stop capturing mouse capture forwarding.
            this.pauseRendererMouseForwarding();

            // Start a new timeout that will reactivate the mouse forwarding.
            this.#resumeRendererMouseForwardingTimeout = setTimeout( () => {
                this.resumeRendererMouseForwarding();
            }, 500 );
            
        } );
```
It's kinda hacky but it works, as long as your invisible window doesn't need mouse move events while the user is resizing/moving another window.

**Comment by rtugeek** [comment]
My workaround:
```javascript
        win.on("will-move", () => {
            for (let win of BrowserWindow.getAllWindows()) {
                win.setIgnoreMouseEvents(false)
            }
        })
```

**Comment by Galkon** [comment]
Bump, running into this issue. Workarounds suggested are helpful, but it's a very weird electron specific issue.

**Comment by Galkon** [comment]
Bump
