### ISSUE TITLE
[Bug]: navigator.userAgent in child windows

### ISSUE THREAD

**Issue by Asaf-Rivni-Ericom** [electron/electron#35037]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.0.0 , 17.0.0 , 20

### What operating system are you using?

macOS

### Operating System Version

MacOs 12.2.1 & Ubuntu 18.04

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

When browsing the web in a child window after setting the useragent (setUserAgent / Headers / in preload), the user agent should be set to the new user agent.

### Actual Behavior

When browsing with a new "main" window the new user agent is used (Which is good),
But when using "window.open" with the "_blank" target then the real user agent is used.

### Testcase Gist URL

https://gist.github.com/5fa012cadc2c8904471f3df14b7bee46

### Additional Information

Make sure that you read the comments on the main.js file.
Thanks.

**Comment by Akira0705** [comment]
[#19600](https://github.com/electron/electron/issues/19600)
 This can work
