### ISSUE TITLE
[Bug]: scrolling stops with virtual scroll

### ISSUE THREAD

**Issue by sbenmoussati** [electron/electron#35049]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.9

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

x64

### Expected Behavior

User should be able to scroll smoothly

### Actual Behavior

Unable to scroll smoothly while using react virtual scrolling

### Additional Information

Users are unable to use virtual scroll with React  on Electron 19 and this issue has been fixed on Chrome v104 and back-ported on Chrome v103.

Details of the bug I'm experiencing: https://bugs.chromium.org/p/chromium/issues/detail?id=1331231

Fix and details: https://bugs.chromium.org/p/chromium/issues/detail?id=1330045

Would it be possible to back-port this fix on on Electron 19?

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/35051
