### ISSUE TITLE
[Bug]: Uploading a file that is bigger than 773,934 bytes crashes Electron.

### ISSUE THREAD

**Issue by aabluedragon** [electron/electron#35042]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro, Version 10.0.22000

### What arch are you using?

x64

### Expected Behavior

File upload larger than 773,934 bytes should not crash electron

### Actual Behavior

Uploading a file that is bigger than 773,934 bytes crashes electron.

Snippet (Example for uploading a file to Microsoft Azure Blob):
```javascript
await fetch(url, {method: "PUT", body: bytes /*Uint8Array*/, headers:[
   ['x-ms-blob-type', "BlockBlob"]
]});
```

**Comment by codebytere** [comment]
@aabluedragon does this work in Chrome?

**Comment by aabluedragon** [comment]
@codebytere Yup, in plain chrome (did not test chromium), the file upload completes successfully with http status 201, and no crash.
Here's a small html file snippet.
```html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <script>
            (async()=>{
                const a = [];
                for(let i=0;i<800000;i++) {
                    a.push(120); // just a random byte, doesn't matter
                }
                const url = `https://yourBlobContainer.blob.core.windows.net/nnuploads/myFile.txt`;
                const reqUrlWithParams = encodeURI(url)+`?`+ 'Add Your Azure Blob SAS Token here'
                const bytes = new Uint8Array(a);
                await fetch(reqUrlWithParams, {method: "PUT", body: bytes, headers:[
                    ['x-ms-blob-type', "BlockBlob"]
                ]});
            })()
        </script>
    </body>
</html>
```
The fact that this request is to Azure Blob doesn't really matter, it's just an example.

**Comment by aabluedragon** [comment]
My bad.
It doesn't happen anymore, it could be that the crash was a result of sending the above mentioned amount of bytes to a different library called `xxhash-wasm`.
