### ISSUE TITLE
[Bug]: webContents.getUserAgent() is empty since 20.0.0-alpha.6

### ISSUE THREAD

**Issue by Kilian** [electron/electron#35046]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0-alpha.6

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Last Known Working Electron version

20.0.0-alpha.5

### Expected Behavior

`webContents.getUserAgent()` returns a string with a user Agent

### Actual Behavior

webContents.getUserAgent() returns an empty string

### Testcase Gist URL

https://gist.github.com/33fd4a9ac6db6b28b1dcc5b765edb622

### Additional Information

In the console the user agent is printed in alpha.5, but empty in alpha.6. Looking at the diff between alpha.5 and alpha.6, this PR seems the likely cause: https://github.com/electron/electron/pull/34524 / #34481

It's worth noting that the renderer does have a filled-in userAgent.

**Comment by TheMightyPenguin** [comment]
I'm also getting this same issue in 19.0.9!
