### ISSUE TITLE
[Bug]: bot client isnt loading

### ISSUE THREAD

**Issue by YouAgain312** [electron/electron#35052]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

i expected to automatically load

### Actual Behavior

loading

### Testcase Gist URL

https://github.com/Flam3rboy/discord-bot-client/releases/tag/3.1.0

**Comment by YouAgain312** [comment]
i didnt know what electron version was so yea

**Comment by Kilian** [comment]
This is the repository for the Electron framework, we do not give support for apps built in Electron. If you have questions about discord-bot-client, please post an issue in their repository.
