### ISSUE TITLE
[Bug]: Ngx-electron isn't working with new electron versions

### ISSUE THREAD

**Issue by meghajayakumar** [electron/electron#35067]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Last Known Working Electron version

8.5.5

### Expected Behavior

Ngx-electron should work with electron project to communicate between angular renderer process to electron main file.

### Actual Behavior

Ngx-electron package doesn't work with the new electron version for communicating between renderer angular project to main process. 

ElectronService is shown as undefined.

**Comment by Prinzhorn** [comment]
I think you accidentally ended up in the wrong repo, this sounds like a problem with ngx-electron, which is located here https://github.com/ThorstenHans/ngx-electron/issues

**Comment by codebytere** [comment]
Closing in agreement w/ the above.
