### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Zhongxiangyun** [electron/electron#35089]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.0

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Last Known Working Electron version

18.2.0

### Expected Behavior

希望项目能够正常的启动.

### Actual Behavior

`
"start": "concurrently \"cross-env BROWSER=none craco start\" \"wait-on http://localhost:3000 && electron .\"",
    "dev": "concurrently \"wait-on http://localhost:3000 && electron .\" \"cross-env BROWSER=none npm start\"",`

![image](https://user-images.githubusercontent.com/7427588/181151418-1b4a41a1-c587-4c8c-8654-3d0c9c742fda.png)

执行启动命令后,会一直停留在这里,无法启动项目,我的电脑是windows10. node版本:14.19

`]
[1] [0] (node:19884) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[1] [0] (Use `node --trace-deprecation ...` to show where the warning was created)
[1] [0] (node:19884) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[1] [0] Starting the development server...
`

### Additional Information

`]
[1] [0] (node:19884) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[1] [0] (Use `node --trace-deprecation ...` to show where the warning was created)
[1] [0] (node:19884) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[1] [0] Starting the development server...
`

**Comment by Zhongxiangyun** [comment]
`
"dependencies": {
    "@better-scroll/core": "^2.4.2",
    "@types/jest": "^27.4.1",
    "@types/node": "^17.0.21",
    "antd": "^4.18.1",
    "axios": "^0.24.0",
    "better-scroll": "^2.4.2",
    "browserslist": "^4.20.2",
    "electron": "^12.2.3",
    "electron-is-dev": "^2.0.0",
    "electron-log": "^4.4.4",
    "history": "^4.10.1",
    "iconv-lite": "^0.6.3",
    "qrcode.react": "^2.0.0",
    "react": "^17.0.2",
    "react-color": "^2.19.3",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.2.2",
    "react-scripts": "^5.0.0",
    "serialport": "^9.2.8",
    "typescript": "^4.6.3",
    "web-vitals": "^1.1.2",
    "ws": "^8.3.0"
  },
  "devDependencies": {
    "@craco/craco": "^6.0.0",
    "@testing-library/jest-dom": "^5.11.6",
    "@testing-library/react": "^11.1.2",
    "@testing-library/user-event": "^12.2.2",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "babel-plugin-prismjs": "^2.1.0",
    "concurrently": "^6.5.1",
    "craco-less": "^2.0.0",
    "cross-env": "^5.2.1",
    "electron-builder": "^22.13.1",
    "ts-loader": "^9.2.8",
    "typescript": "^4.6.3",
    "wait-on": "^3.3.0"
  },
  "scripts": {
    "web": "craco start",
    "electron": "electron ./",
    "build": "craco build",
    "test": "craco test --env=jsdom",
    "postinstall": "electron-builder install-app-deps",
    "start": "concurrently \"cross-env BROWSER=none craco start\" \"wait-on http://localhost:3000 && electron .\"",
    "dev": "concurrently \"wait-on http://localhost:3000 && electron .\" \"cross-env BROWSER=none npm start\"",
    "pack": "electron-builder --dir",
    "pack-32": "electron-builder --dir --ia32",
    "dist": "craco build && electron-builder build --x64",
    "dist-win64": "craco build && electron-builder build --win --x64",
    "dist-win32": "craco build && electron-builder build --win --ia32",
    "dist-32": "electron-builder build --ia32"
  },
`

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
