### ISSUE TITLE
[Feature Request]: Allow disabling `File.path` (or add a function to get the full path)

### ISSUE THREAD

**Issue by Prinzhorn** [electron/electron#35094]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

https://www.electronjs.org/docs/latest/api/file-object

Given the following:

`<input type="file" onchange="alert(this.files[0].path)" />`

I was looking for ways to get  `path` from `this.files[0]` when context isolation is enabled. Turns out even with context isolation and sandboxing Electron still patches the `File` object to add the full path. That means even if I lock down my `webPreferences` as much as currently possible, the `path` property is still there and exposed to any website that has a file picker. I don't like that.

### Proposed Solution

Add an option to remove the property or make one of the existing options do that. I would like my `WebContents` to behave as close to Chromium as possible. It would be great if at some point we end up with `WebContents` that are as secure as Chromium and injecting globals via `contextBridge` is the only difference.

For situations where you need the path (I actually need it, but was sure I can't get it with my `webPreferences`, but I can) there needs to be a way to get the full path via `contextBridge`. I assume the structured cloning would destroy the  `File`, so it's probably not an option to pass the `File` object directly to the preload. Maybe the only option would be to have some sort of uuid on the `File` object that I can pass around to get the full path?

Honestly that does sound kind of horrible. And for the `WebContents` that load trusted content I'm fine with having `File.path`. But for `WebContents` that will load untrusted content, I want to lock this down. But it feels silly to have a `removeFilePath` option. Maybe there are other things that are also "not Chromium" that could be combined into a new option? My main goal is to not expose anything to untrusted `WebContents` that Chromium wouldn't either.

### Alternatives Considered

Just ignore that `File.path` exists and not make a big deal about it. But there's a reason browsers don't expose the full path to websites.

**Comment by WyattBlue** [comment]
It's gone completely in latest stable. https://github.com/electron/electron/pull/42053
