### ISSUE TITLE
[Bug]: WCO buttons cannot be activated by touch

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#35107]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.7

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Close/minimize/maximize buttons should be accessible by touch.

Chromium:

https://user-images.githubusercontent.com/79877362/181366616-b5b0c3b6-3ec5-4528-b925-21c2bb872e5b.mp4

### Actual Behavior

Electron:

https://user-images.githubusercontent.com/79877362/181366610-f63b3486-945f-42a7-9cb5-e32ad92d6754.mp4

Note that this is WCO and not native buttons!

**Comment by deepak1556** [comment]
Merging to https://github.com/electron/electron/issues/34364

**Comment by indutny-signal** [comment]
Thanks so much!
