### ISSUE TITLE
[Bug]: Window with iframes gets frozen after printing

### ISSUE THREAD

**Issue by IliaGusarov** [electron/electron#35119]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.9

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1

### What arch are you using?

x64

### Expected Behavior

Window should not get frozen after printing

### Actual Behavior

Window with iframes gets frozen after printing(Save as PDF)

**Steps to reproduce:**

1. Load html file with an iframe 
```
<html>
  <body>
    <iframe src="https://en.wikipedia.org/"></iframe>
    <button onclick="print()">Print me</button>
  </body>
</html>
  ```
2. Click on print button
3. Save as PDF
4. As a result window content gets frozen

**Comment by codebytere** [comment]
I added the above code snippet to the stock Fiddle and could not reproduce. 

To repro, I:
1. Ran the Fiddle
2. Clicked "print me"
3. Clicked "Save as PDF" and saved the PDF
4. Clicked back into the iframe and tried to load another page, which loaded successfully

**Comment by IliaGusarov** [comment]
@codebytere Did you try to reproduce it on macOS Monterey ?

**Comment by sohobloo** [comment]
same problem using 19.0.13

**Comment by patrickdbakke** [comment]
Also seeing this on `19.0.12`. 

As a workaround, we're removing the iframes, printing, then restoring the iframes. 

```
const iframes = Array.from(document.querySelector('iframe')).map(i => {
    const parent = iframe.parentElement
    const before = {
        iframe,
        parent,
        nextSibling: iframe.nextSibling
    }
    parent?.removeChild(iframe)
    return before;
})
window.print()
iframes.forEach(i => {
    const {
        iframe,
        parent,
        nextSibling
    } = i
    if (nextSibling) {
        parent.insertBefore(iframe, nextSibling)
    } else {
        parent.appendChild(iframe)
    }
})
```

**Comment by pushkin-** [comment]
bump

**Comment by patrickdbakke** [comment]
bump

**Comment by codebytere** [comment]
Same as before: https://github.com/electron/electron/issues/35119#issuecomment-1200968238

Cannot reproduce on macOS. Given this has been open for a long time and I've never been able to reproduce this i'm closing it out but if someone can provide a repro i can re-open.
