### ISSUE TITLE
[Bug]: GPU progress exited unexpectly on electron version 18.2.0 for windows.

### ISSUE THREAD

**Issue by Sara2009** [electron/electron#35113]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.0

### What operating system are you using?

Windows

### Operating System Version

windows 10 version 2004

### What arch are you using?

ia32

### Last Known Working Electron version

16.0.5

### Expected Behavior

The window is opened. And ready-to-show event is triggered by browser window.

### Actual Behavior

The electron app cannot be opened. The window is empty. And then auto closed.
![image](https://user-images.githubusercontent.com/9332442/181482908-82089721-f58c-4346-8f55-ba13cc322e47.png)
<img width="905" alt="image" src="https://user-images.githubusercontent.com/9332442/181483088-0ae541d2-be84-4c31-9a58-306e3a7ebadb.png">

**Comment by VerteDinde** [comment]
@Sara2009 You may be getting hit with a bug addressed by this PR: https://github.com/electron/electron/pull/34297
Could you try upgrading to 18.3.0 or later and see if the issue persists?

**Comment by Sara2009** [comment]
> 
![wecom-temp-16895-f9b811cb156764cb0bf34ce374047bd7](https://user-images.githubusercontent.com/9332442/183019428-77ea8e3a-8883-416f-96b4-940b6ffdda6f.jpg)

v18.3.0 does't work. Same error.
v20.0.1 does't work. Same error.

**Comment by Sara2009** [comment]
> the issue persists?

@VerteDinde
