### ISSUE TITLE
[Bug]: Input fields not focusable/editable after 'will-prevent-unload'

### ISSUE THREAD

**Issue by pvrobays** [electron/electron#35129]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows 11, 10.0.22000 Build 22000

### What arch are you using?

x64

### Expected Behavior

After canceling a synchronous dialog within the `will-prevent-unload` event and triggering `preventDefault()` on the event, the input fields of the browser window should still be editable and focusable.

### Actual Behavior

After canceling a synchronous dialog within the `will-prevent-unload` event and triggering `preventDefault()` on the event, the input fields of the browser window are neither focusable, nor editable.

### Testcase Gist URL

https://gist.github.com/15c525fc71c9e3075d314ef17f50612e

### Additional Information

When the issue occurs, you can un-focus the browser window, refocus it again and the input fields will be focusable and editable again.

**Comment by pvrobays** [comment]
A possible workaround is to quickly hide/show the browser window after the `preventDefault`:
```
mainWindow.hide();
setTimeout(() =>mainWindow.show(), 50);
```

**Comment by clavin** [comment]
Was able to repro this on both 19.0.6 as well as 20.0.0-beta.13. Thanks for the report! 👍

**Comment by clavin** [comment]
Did some searching in the issue tracker and this also is probably related to #31917.

**Comment by pvrobays** [comment]
Hi @clavin 
That definitely smells like it's the same underlying issue.
Duplicate of #31917

**Comment by codebytere** [comment]
@pvrobays interesting - looks like it _only_ affects Windows. Do you happen to know when it started?

**Comment by codebytere** [comment]
OK - looks like this problem is about the message box. If you switch to 

```
const response = await dialog.showMessageBox(mainWindow, {
          type: "question",
          title: "Wanna leave?",
          message: "Leave Site?",
          detail: "Changes that you made may not be saved.",
          buttons: ["Cancel", "Leave"]
      })
      if (response === 1) {
          event.preventDefault();
      }
```

things work just fine.

**Comment by ShaunaGordon** [comment]
`dialog` is only available in the main process, though. This is useful if the dialog originates from the main process, but it seems odd and somewhat counterintuitive to have to shunt even the most basic alerts to main.

**Comment by pvrobays** [comment]
Thanks @codebytere !
For me the async fix is sufficient. TBH I was still in believe that async triggering the `preventDefault` wouldn't work (from older electron versions) so didn't even bother to try.

**Comment by pvrobays** [comment]
Still an issue. I've updated the gist with the latest version:

https://gist.github.com/37749f99b5872f49e99a9667a7a0e4f3

I've also noticed even if you do leave the page after the unload event, you won't be able to use the input fields of the next loaded page.
To reproduce this, use the link in the gist electron app from above.
