### ISSUE TITLE
[Bug]: Property 'getOwnerBrowserWindow' does not exist on type 'Electron.WebContents'.

### ISSUE THREAD

**Issue by ashen114** [electron/electron#35145]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.9

### What operating system are you using?

Windows

### Operating System Version

Microsoft Windows [version 10.0.17763.2928]

### What arch are you using?

x64

### Last Known Working Electron version

19.0.9

### Expected Behavior

Support “Electron.WebContents” to use function getOwnerBrowserWindow

### Actual Behavior

![image](https://user-images.githubusercontent.com/28629247/181867656-9470bdab-b0a0-4e77-9b4f-3854c834a0cb.png)

```ts
import type { BrowserWindow } from "electron"
import { ipcMain } from 'electron'

export default () => {
  ipcMain.on('resize', (event, type) => {
    if (event.sender.getType() === 'browserView') {
      const window: BrowserWindow = event.sender.getOwnerBrowserWindow()
      window.center()
    }
  })
}

```

**Comment by ashen114** [comment]
temporary fix:
```ts
import type { BrowserWindow } from "electron"
import { ipcMain } from 'electron'

interface Sender extends Electron.WebContents {
  getOwnerBrowserWindow(): Electron.BrowserWindow | null;
}

export default () => {
  ipcMain.on('resize', (event) => {
    if (event.sender.getType() === 'browserView') {
      const window: BrowserWindow = (event.sender as Sender).getOwnerBrowserWindow()
      window.center()
    }
  })
}

```

**Comment by miniak** [comment]
`getOwnerBrowserWindow` is not documented
