### ISSUE TITLE
[Bug]: `BrowserView` does not use full window when maximized for the first time.

### ISSUE THREAD

**Issue by FrankenApps** [electron/electron#35149]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.10

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21H1

### What arch are you using?

x64

### Expected Behavior

The `BrowserView` would expand just like the window.

### Actual Behavior

I have worked around the `BrowserView` not accounting for the `8px` padding that should be applied to a frameless window. But the first time the window is maximized, there still is a small gap (of around `2px`) left where the browser view does not cover the window (this happens with and without the aforementioned workaround). 

This is the window when it is first beeing maximized:
![first_maximize](https://user-images.githubusercontent.com/17967303/182024609-3e78e44f-ce36-4536-b3f1-93862730f770.png)

After unmaximizing and then maximizing the window a second time, the `BrowserView` behaves as expected:

![second_maximize](https://user-images.githubusercontent.com/17967303/182024648-d02c270a-5b7b-4065-8d0b-897e1002341d.png)

### Testcase Gist URL

https://gist.github.com/53a4717f82ce372e5f763e7180a95281

### Additional Information

Because of the nature of the issue, you will have to restart the linked fiddle after restoring the window, to be able to reproduce this bug again.

**Comment by pejman1** [comment]
another issue about fullscreen with Browserview  which has not been fixed since three month ago
https://github.com/electron/electron/issues/34342

**Comment by VyMajoris** [comment]
This is affecting Discord and Postman.
