### ISSUE TITLE
[Bug]: Cratehackers desktop app does not play files with .m4a extension, .aac does work.

### ISSUE THREAD

**Issue by dbrewerton** [electron/electron#35143]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

When pressing play on the playlist item, expected behavior is the song should play. 

### Actual Behavior

Player dialog at bottom is shows no song, just play and pause buttons.

### Additional Information

Behavior of aac files
![image](https://user-images.githubusercontent.com/18341315/181855229-9a691c08-aee6-4153-b3d9-5a83589ce824.png)

Behavior of m4a files
![image](https://user-images.githubusercontent.com/18341315/181855166-b5085c4f-9186-4068-a7f8-63142276ad12.png)

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! It looks like this issue is specific to the Crate Hackers desktop app. Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. Could you file an issue directly with Crate Hackers?
