### ISSUE TITLE
[Feature Request]: Make this interactive with hover

### ISSUE THREAD

**Issue by PritamSarbajna** [electron/electron#35158]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I just think if you make this section little more interactive

![Screenshot (179)](https://user-images.githubusercontent.com/90236635/182138676-d116e974-32ac-4686-b89b-038a846d1c36.png)
 

### Proposed Solution

I'd like to add when hovering it changes color or transform like a card I can change this can you assign it to me ?

### Alternatives Considered

You can also add a slideshow or decorate but I don't recommend

**Comment by codebytere** [comment]
@PritamSarbajna please open this on https://github.com/electron/electronjs.org-new
