### ISSUE TITLE
[Bug]: Sending an Uint8Array from Renderer to Main process ends up as Object

### ISSUE THREAD

**Issue by fb13** [electron/electron#35152]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.9

### What operating system are you using?

macOS

### Operating System Version

MacOs Catalina 10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

19.0.9

### Expected Behavior

I expect to get a Uint8Array in the Main process when I send a Uint8Array from the Renderer to the Main process.

Renderer:

```
const ab = await event.data.arrayBuffer();
window.api.newRecordingData(new Uint8Array(ab));
```

Preloader:

```
const { contextBridge, ipcRenderer } = require('electron')
contextBridge.exposeInMainWorld('api', {
  newRecordingData: (data) => ipcRenderer.send('newRecordingData', data)
})
```

Main Process:

```
ipcMain.on('newRecordingData', async (data) => {
  let buf = Buffer.from(data) // <-- data should be from Uint8Array type, but instead is from type Object
  chunks.push(buf)
})
```

### Actual Behavior

Actually, the data I receive in this example in the Main process is always an object, that I cannot just convert back to an Uint8Array.

### Additional Information

I also looked into this issue: https://github.com/electron/electron/issues/9509

There it is said that sending an Uint8Array should actually be no problem.

**Comment by RaisinTen** [comment]
Your code is not correct. Making the following change to your main process code fixes the issue:
```diff
- ipcMain.on('newRecordingData', async (data) => {
+ ipcMain.on('newRecordingData', async (event, data) => {
```
Check out the [docs for `ipcMain.on()`](https://www.electronjs.org/docs/latest/api/ipc-main#ipcmainonchannel-listener) for the invocation.
Let me know if this is still a problem and I'll reopen the issue!
