### ISSUE TITLE
[Bug]: Electron autoUpdater Error: Update check failed. The server sent an invalid JSON response

### ISSUE THREAD

**Issue by wenwuwu** [electron/electron#35154]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

19.0.8

### Expected Behavior

`electron.autoUpdater` should just download the latest release.

### Actual Behavior

Error is thrown : 

```
[Error: Update check failed. The server sent an invalid response. Try again later.] {
  code: 6,
  domain: 'SQRLUpdaterErrorDomain'
}
```

### Additional Information

I am implementing `auto update` feature for my `Electron` app. I am encountering an error: 

```
[Error: Update check failed. The server sent an invalid response. Try again later.] {
  code: 6,
  domain: 'SQRLUpdaterErrorDomain'
}
```

This error is thrown from inside `Electron` node module, specifically from `Squirrel.framework`: 
```
Binary file ./dist/Electron.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
```

Part of my `electron` `main.js` code:

```javascript
    const { app, autoUpdater } = require('electron');

    let version  = app.getVersion();
    let server   = 'https://colube-deploy-pnjad1iun-wenwu.vercel.app';
    //let url    = `${server}/update/${process.platform}/${app.getVersion()}`;
    let platform = process.platform + '_arm64';
    let url      = `${server}/update/${platform}/${version}`;

    autoUpdater.setFeedURL({ url });

    setInterval(() => {
        autoUpdater.checkForUpdates();
    }, 15 * 60 * 1000);

    setTimeout(() => {
        autoUpdater.checkForUpdates();
    }, 3000);

    autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => {

releaseName, releaseNotes);

        const dialogOpts = {
            type    : 'info',
            buttons : ['Restart', 'Later'],
            title   : 'Application Update',
            message : process.platform === 'win32' ? releaseNotes : releaseName,
            detail  : 'A new version has been downloaded. Restart the application to apply the updates.',
        }

        dialog.showMessageBox(dialogOpts).then((returnValue) => {
            if (returnValue.response === 0) autoUpdater.quitAndInstall();
        })
    });

    autoUpdater.on('before-quit-for-update', () => {
    });

    autoUpdater.on('error', (message) => {
        console.error('There was a problem updating the application.');
        console.error(message);
    });
```

Some background information: 

* I am testing on `M2-chip MacOS Monterey 12.4`. `Electron` version is `^19.0.8`
* I am using `autoUpdater` from `electron` module
* I am using [Hazel][1] which is recommended in [Electron official document][2].
* Hazel is deployed to [Vercel][3]. 
* App releases are behind a private `github` repo.
* App releases are notarized by Apple successfully. 
* Hazel server is configured with environment variable `TOKEN` (my github personal token).
* The `url` argument passed to `setFeedURL()` is `https://colube-deploy-pnjad1iun-wenwu.vercel.app/update/darwin_arm64/0.9.13`
* Vercel server response to request `autoUpdater.checkForUpdates()` is status code `200` with `object` like: 
```javascript
{
    name: 'v0.9.17',
    notes: '',
    pub_date: '2022-07-31T13:47:34Z',
    url: 'colube-deploy-pnjad1iun-wenwu.vercel.app/download/darwin_arm64?update=true'
}
```
* Paste above response url `colube-deploy-pnjad1iun-wenwu.vercel.app/download/darwin_arm64?update=true` to browser can successfully download the app.

  [1]: https://github.com/vercel/hazel
  [2]: https://www.electronjs.org/docs/latest/tutorial/updates#step-1-deploying-an-update-server
  [3]: https://vercel.com/

**Comment by yaoyuanrong** [comment]
> ### Preflight Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.
> 
> ### Electron Version
> 19.0.8
> 
> ### What operating system are you using?
> macOS
> 
> ### Operating System Version
> macOS Monterey 12.4
> 
> ### What arch are you using?
> arm64 (including Apple Silicon)
> 
> ### Last Known Working Electron version
> 19.0.8
> 
> ### Expected Behavior
> `electron.autoUpdater` should just download the latest release.
> 
> ### Actual Behavior
> Error is thrown :
> 
> ```
> [Error: Update check failed. The server sent an invalid response. Try again later.] {
>   code: 6,
>   domain: 'SQRLUpdaterErrorDomain'
> }
> ```
> 
> ### Testcase Gist URL
> _No response_
> 
> ### Additional Information
> I am implementing `auto update` feature for my `Electron` app. I am encountering an error:
> 
> ```
> [Error: Update check failed. The server sent an invalid response. Try again later.] {
>   code: 6,
>   domain: 'SQRLUpdaterErrorDomain'
> }
> ```
> 
> This error is thrown from inside `Electron` node module, specifically from `Squirrel.framework`:
> 
> ```
> Binary file ./dist/Electron.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
> ```
> 
> Part of my `electron` `main.js` code:
> 
> ```js
>     const { app, autoUpdater } = require('electron');
> 
>     let version  = app.getVersion();
>     let server   = 'https://colube-deploy-pnjad1iun-wenwu.vercel.app';
>     //let url    = `${server}/update/${process.platform}/${app.getVersion()}`;
>     let platform = process.platform + '_arm64';
>     let url      = `${server}/update/${platform}/${version}`;
> 
>     autoUpdater.setFeedURL({ url });
> 
>     setInterval(() => {
>         autoUpdater.checkForUpdates();
>     }, 15 * 60 * 1000);
> 
>     setTimeout(() => {
>         autoUpdater.checkForUpdates();
>     }, 3000);
> 
>     autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => {
> 
> releaseName, releaseNotes);
> 
>         const dialogOpts = {
>             type    : 'info',
>             buttons : ['Restart', 'Later'],
>             title   : 'Application Update',
>             message : process.platform === 'win32' ? releaseNotes : releaseName,
>             detail  : 'A new version has been downloaded. Restart the application to apply the updates.',
>         }
> 
>         dialog.showMessageBox(dialogOpts).then((returnValue) => {
>             if (returnValue.response === 0) autoUpdater.quitAndInstall();
>         })
>     });
> 
>     autoUpdater.on('before-quit-for-update', () => {
>     });
> 
>     autoUpdater.on('error', (message) => {
>         console.error('There was a problem updating the application.');
>         console.error(message);
>     });
> ```
> 
> Some background information:
> 
> * I am testing on `M2-chip MacOS Monterey 12.4`. `Electron` version is `^19.0.8`
> * I am using `autoUpdater` from `electron` module
> * I am using [Hazel](https://github.com/vercel/hazel) which is recommended in [Electron official document](https://www.electronjs.org/docs/latest/tutorial/updates#step-1-deploying-an-update-server).
> * Hazel is deployed to [Vercel](https://vercel.com/).
> * App releases are behind a private `github` repo.
> * App releases are notarized by Apple successfully.
> * Hazel server is configured with environment variable `TOKEN` (my github personal token).
> * The `url` argument passed to `setFeedURL()` is `https://colube-deploy-pnjad1iun-wenwu.vercel.app/update/darwin_arm64/0.9.13`
> * Vercel server response to request `autoUpdater.checkForUpdates()` is status code `200` with `object` like:
> 
> ```js
> {
>     name: 'v0.9.17',
>     notes: '',
>     pub_date: '2022-07-31T13:47:34Z',
>     url: 'colube-deploy-pnjad1iun-wenwu.vercel.app/download/darwin_arm64?update=true'
> }
> ```
> 
> * Paste above response url `colube-deploy-pnjad1iun-wenwu.vercel.app/download/darwin_arm64?update=true` to browser can successfully download the app.

Did you solve it?
