### ISSUE TITLE
[Bug]: Last directory is not remembered when opening files in macOS

### ISSUE THREAD

**Issue by roddyaj** [electron/electron#35162]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.5

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5

### What arch are you using?

x64

### Last Known Working Electron version

15.5.7

### Expected Behavior

Have electron open the operating system's file picker  
The initial directory shown to the user is whatever was last selected (call it directory A)  
The user picks a file in a different directory (call it directory B)  
The next time the file picker is launched, it should present the user with the last directory chosen, directory B  

### Actual Behavior

Have electron open the operating system's file picker  
The initial directory shown to the user is whatever was last selected (call it directory A)  
The user picks a file in a different directory (call it directory B)  
The next time the file picker is launched, **it actually presents the user with the original directory chosen, directory A**  

### Additional Information

Note, we are using the `blueimp-file-upload` library's `fileupload` function to launch the file picker.  
This worked in macOS through electron version 15.5.7, and doesn't work in 16.0.0 through 19+.  
This works fine in Windows.

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
