### ISSUE TITLE
[Bug]: crash on windows 11 home edition when app is installed in non-c-drive

### ISSUE THREAD

**Issue by HppZ** [electron/electron#35180]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.0 / 20.0.0

### What operating system are you using?

Windows

### Operating System Version

indows 11 home edition 64-bit (10.0, Build 22000) (22000.co_release.210604-1628)

### What arch are you using?

x64

### Expected Behavior

no crash

### Actual Behavior

crashes at launch

### Additional Information

00 00000013`325fdea0 00007ff6`16df3fd1 electron_quick_start!logging::LogMessage::~LogMessage+0x849 [C:\projects\src\base\logging.cc @ 852] 
01 00000013`325fe410 00007ff6`130cda1c electron_quick_start!content::`anonymous namespace'::IntentionallyCrashBrowserForUnusableGpuProcess+0x81 [C:\projects\src\content\browser\gpu\gpu_data_manager_impl_private.cc @ 451] 
02 00000013`325fe580 00007ff6`16df27e3 electron_quick_start!content::GpuDataManagerImplPrivate::FallBackToNextGpuMode+0x3c [C:\projects\src\content\browser\gpu\gpu_data_manager_impl_private.cc @ 1718] 
03 00000013`325fe5b0 00007ff6`16df58f1 electron_quick_start!content::GpuDataManagerImpl::FallBackToNextGpuMode+0x23 [C:\projects\src\content\browser\gpu\gpu_data_manager_impl.cc @ 371] 
04 00000013`325fe5f0 00007ff6`16df5d60 electron_quick_start!content::GpuProcessHost::RecordProcessCrash+0x131 [C:\projects\src\content\browser\gpu\gpu_process_host.cc @ 1289] 
05 00000013`325fe770 00007ff6`12fcdf69 electron_quick_start!content::GpuProcessHost::OnProcessCrashed+0x80 [C:\projects\src\content\browser\gpu\gpu_process_host.cc @ 968] 
06 00000013`325fe8f0 00007ff6`13d40b87 electron_quick_start!content::BrowserChildProcessHostImpl::OnChildDisconnected+0x189 [C:\projects\src\content\browser\browser_child_process_host_impl.cc @ 462] 
07 00000013`325fe9d0 00007ff6`137a3d65 electron_quick_start!IPC::internal::MessagePipeReader::OnPipeError+0x97 [C:\projects\src\ipc\ipc_message_pipe_reader.cc @ 178] 
08 (Inline Function) --------`-------- electron_quick_start!base::OnceCallback<void ()>::Run+0x1d [C:\projects\src\base\callback.h @ 143] 
09 00000013`325fea30 00007ff6`1383102f electron_quick_start!mojo::InterfaceEndpointClient::NotifyError+0x115 [C:\projects\src\mojo\public\cpp\bindings\lib\interface_endpoint_client.cc @ 694] 
0a 00000013`325feac0 00007ff6`138325fe electron_quick_start!IPC::`anonymous namespace'::ChannelAssociatedGroupController::NotifyEndpointOfError+0xaf [C:\projects\src\ipc\ipc_mojo_bootstrap.cc @ 818] 
0b 00000013`325feb60 00007ff6`137a2d4a electron_quick_start!IPC::`anonymous namespace'::ChannelAssociatedGroupController::OnPipeError+0x2de [C:\projects\src\ipc\ipc_mojo_bootstrap.cc @ 800] 
0c (Inline Function) --------`-------- electron_quick_start!base::OnceCallback<void ()>::Run+0x1a [C:\projects\src\base\callback.h @ 143] 
0d (Inline Function) --------`-------- electron_quick_start!mojo::Connector::HandleError+0x269 [C:\projects\src\mojo\public\cpp\bindings\lib\connector.cc @ 688] 
0e (Inline Function) --------`-------- electron_quick_start!mojo::Connector::OnHandleReadyInternal+0x3f1 [C:\projects\src\mojo\public\cpp\bindings\lib\connector.cc @ 442] 
0f (Inline Function) --------`-------- electron_quick_start!mojo::Connector::OnWatcherHandleReady+0x3f1 [C:\projects\src\mojo\public\cpp\bindings\lib\connector.cc @ 422] 
10 (Inline Function) --------`-------- electron_quick_start!base::internal::FunctorTraits<void (mojo::Connector::*)(unsigned int),void>::Invoke+0x401 [C:\projects\src\base\bind_internal.h @ 541] 
11 (Inline Function) --------`-------- electron_quick_start!base::internal::InvokeHelper<0,void>::MakeItSo+0x409 [C:\projects\src\base\bind_internal.h @ 705] 
12 (Inline Function) --------`-------- electron_quick_start!base::internal::Invoker<base::internal::BindState<void (mojo::Connector::*)(unsigned int),base::internal::UnretainedWrapper<mojo::Connector> >,void (unsigned int)>::RunImpl+0x409 [C:\projects\src\base\bind_internal.h @ 778] 
13 00000013`325febf0 00007ff6`1591a19b electron_quick_start!base::internal::Invoker<base::internal::BindState<void (mojo::Connector::*)(unsigned int),base::internal::UnretainedWrapper<mojo::Connector> >,void (unsigned int)>::Run+0x42a [C:\projects\src\base\bind_internal.h @ 763] 
14 (Inline Function) --------`-------- electron_quick_start!base::RepeatingCallback<void (unsigned int, const mojo::HandleSignalsState &)>::Run+0x15 [C:\projects\src\base\callback.h @ 242] 
15 00000013`325fecb0 00007ff6`158d7e88 electron_quick_start!mojo::SimpleWatcher::OnHandleReady+0xeb [C:\projects\src\mojo\public\cpp\system\simple_watcher.cc @ 279] 
16 (Inline Function) --------`-------- electron_quick_start!base::OnceCallback<void ()>::Run+0x19 [C:\projects\src\base\callback.h @ 143] 
17 00000013`325fedf0 00007ff6`159a7afc electron_quick_start!base::TaskAnnotator::RunTaskImpl+0x128 [C:\projects\src\base\task\common\task_annotator.cc @ 135] 
18 (Inline Function) --------`-------- electron_quick_start!base::TaskAnnotator::RunTask+0x198 [C:\projects\src\base\task\common\task_annotator.h @ 74] 
19 (Inline Function) --------`-------- electron_quick_start!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl+0x427 [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 415] 
1a 00000013`325feea0 00007ff6`158e7ce6 electron_quick_start!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork+0x4cc [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 293] 
1b 00000013`325ff130 00007ff6`13713c5d electron_quick_start!base::MessagePumpForUI::DoRunLoop+0x156 [C:\projects\src\base\message_loop\message_pump_win.cc @ 215] 
1c 00000013`325ff290 00007ff6`13c8e917 electron_quick_start!base::MessagePumpWin::Run+0x7d [C:\projects\src\base\message_loop\message_pump_win.cc @ 79] 
1d 00000013`325ff2f0 00007ff6`136e8d8f electron_quick_start!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run+0x87 [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 537] 
1e 00000013`325ff360 00007ff6`12fe52e2 electron_quick_start!base::RunLoop::Run+0xdf [C:\projects\src\base\run_loop.cc @ 143] 
1f 00000013`325ff450 00007ff6`12fe6d41 electron_quick_start!content::BrowserMainLoop::RunMainMessageLoop+0xa2 [C:\projects\src\content\browser\browser_main_loop.cc @ 1041] 
20 00000013`325ff4c0 00007ff6`12fe25e8 electron_quick_start!content::BrowserMainRunnerImpl::Run+0x11 [C:\projects\src\content\browser\browser_main_runner_impl.cc @ 158] 
21 00000013`325ff4f0 00007ff6`1249d054 electron_quick_start!content::BrowserMain+0xc8 [C:\projects\src\content\browser\browser_main.cc @ 30] 
22 00000013`325ff5b0 00007ff6`1249e4e1 electron_quick_start!content::RunBrowserProcessMain+0xd4 [C:\projects\src\content\app\content_main_runner_impl.cc @ 675] 
23 00000013`325ff6b0 00007ff6`1249df7b electron_quick_start!content::ContentMainRunnerImpl::RunBrowser+0x521 [C:\projects\src\content\app\content_main_runner_impl.cc @ 1185] 
24 00000013`325ff7e0 00007ff6`1249a3ec electron_quick_start!content::ContentMainRunnerImpl::Run+0x33b [C:\projects\src\content\app\content_main_runner_impl.cc @ 1060] 
25 00000013`325ff910 00007ff6`1249a760 electron_quick_start!content::RunContentProcess+0x3fc [C:\projects\src\content\app\content_main.cc @ 411] 
26 00000013`325ffb80 00007ff6`12227aee electron_quick_start!content::ContentMain+0x60 [C:\projects\src\content\app\content_main.cc @ 439] 
27 00000013`325ffc10 00007ff6`15d44962 electron_quick_start!wWinMain+0x39e [C:\projects\src\electron\shell\app\electron_main_win.cc @ 238] 
28 (Inline Function) --------`-------- electron_quick_start!invoke_main+0x21 [d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 118] 
29 00000013`325ffe00 00007ffd`658854e0 electron_quick_start!__scrt_common_main_seh+0x106 [d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
2a 00000013`325ffe40 00007ffd`6698485b kernel32!BaseThreadInitThunk+0x10
2b 00000013`325ffe70 00000000`00000000 ntdll!RtlUserThreadStart+0x2b

**Comment by HppZ** [comment]
why no crash if app is installed in C drive? @VerteDinde

**Comment by VerteDinde** [comment]
@HppZ It's because when logging is initialized here, Chromium/Electron is looking for a very specific file path for logging. If that path does something unusual (i.e., contains a symlink, an unusual character, etc), the logging file creation will fail. That failure is currently set as a FATAL, causing a crash - the PR I linked above changes it to an error.

So you may still not be able to initialize logging on a non-C drive without doing some custom configuration, but the crash should no longer occur 🙂

**Comment by HppZ** [comment]
what is the path?

**Comment by HppZ** [comment]
I think this crash is different from that one cuz there are some GPU-related calls in the stack.
`IntentionallyCrashBrowserForUnusableGpuProcess`
maybe GPU is unusable?

**Comment by HppZ** [comment]
@VerteDinde your fix does not work, confirmed!

**Comment by HppZ** [comment]
@VerteDinde hello, my boss!

**Comment by HppZ** [comment]
@VerteDinde 👀🐱‍👓

**Comment by VerteDinde** [comment]
@HppZ Oh no, too bad! Could you include a small repro of the issue with Electron Fiddle, just so we can have an easier time looking at the same thing? I just tried to install the basic quick start on a non-C drive, and couldn't repro the crash 🤔 If we can get a repro that we can both look at, I'll reopen this. Thanks!

**Comment by liuhao189** [comment]
crash too

**Comment by woshidamaomao** [comment]
me too

**Comment by woshidamaomao** [comment]
> Since this PR was merged into 20 and a new release is being cut as we speak, I'm going to close this issue. But let me know if the issue persists and I'll reopen it!

The issue persists with electron@21.3.3 ,  it can be reopen?

**Comment by xiaomengheiheihei** [comment]
I have also encountered this problem, and it can only be replicated on certain machines. I am still investigating it and hope to have a good result.
