### ISSUE TITLE
[Bug]: can't update my app from a version that uses electron v18.2.0 to another that that uses electron v18.3.5

### ISSUE THREAD

**Issue by Karmel85** [electron/electron#35191]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 pro build 19044

### What arch are you using?

x64

### Last Known Working Electron version

18.2.0

### Expected Behavior

I expect auto-update (using squirrel) to succeed when the update includes upgrading electron itself from v18.2.0 to v18.3.5.

### Actual Behavior

- updating the app from one version to another that are both using electron v18.2.0 is OK.
- updating the app from one version to another that are both using electron v18.3.5 is OK.

- updating the app from a version that uses electron v18.2.0 to another that uses electron v18.3.5 is **NOT OK**.
in that case:
- **I'm missing the `update-downloaded` event**.
- I don't get any error from the auto-updater.
- **instead the app just hangs**.
- squirrels logs seems fine.
- nothing in "event viewer"
- after killing the process, I can see that the stub exe file is replaced and that it launches the new version successfully..

### Additional Information

I'm using electron forge to package, make and publish my app.
It worked perfectly fine until I recently upgraded electron from v18.2.0 to v18.3.5.

**Comment by MarshallOfSound** [comment]
This is unfortunately expected _buggy_ behavior, there were issues with process singletons in the 18.x series that I think were fully fixed around the 18.3.0 version.  Switching from 18.2.0 to 18.3.5 will result in a process singleton lock conflict that won't be resolved until the process is terminated.

**Comment by Karmel85** [comment]
Thanks for the quick response @MarshallOfSound !
Is there a newer version than 18.3.5 that won't result in a process singleton lock conflict while upgrading from 18.2.0?
19.x.y?
20.x.y?

**Comment by MarshallOfSound** [comment]
The problem is 18.2.0 is broken, not that 18.3.5 is broken 😓
