### ISSUE TITLE
[Bug]: crash a few seconds after launch

### ISSUE THREAD

**Issue by HppZ** [electron/electron#35197]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.9

### What operating system are you using?

Windows

### Operating System Version

windows 7

### What arch are you using?

x64

### Expected Behavior

no crash

### Actual Behavior

crashed

### Additional Information

ExceptionAddress: 00000001402b0943 (____!std::__1::vector<base::internal::CheckedObserverAdapter,std::__1::allocator<base::internal::CheckedObserverAdapter> >::begin)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000048
Attempt to read from address 0000000000000048

00 (Inline Function) --------`--------     ____!std::__1::vector<base::internal::CheckedObserverAdapter,std::__1::allocator<base::internal::CheckedObserverAdapter> >::begin(void) [C:\projects\src\buildtools\third_party\libc++\trunk\include\vector @ 1526] 
01 (Inline Function) --------`--------     ____!base::internal::begin(class std::__1::vector<base::internal::CheckedObserverAdapter,std::__1::allocator<base::internal::CheckedObserverAdapter> > * range = 0x00000000`00000048) [C:\projects\src\base\ranges\ranges.h @ 44] 
02 (Inline Function) --------`--------     ____!base::ranges::begin(class std::__1::vector<base::internal::CheckedObserverAdapter,std::__1::allocator<base::internal::CheckedObserverAdapter> > * range = 0x00000000`00000048) [C:\projects\src\base\ranges\ranges.h @ 105] 
03 (Inline Function) --------`--------     ____!base::ranges::find_if(class std::__1::vector<base::internal::CheckedObserverAdapter,std::__1::allocator<base::internal::CheckedObserverAdapter> > * range = 0x00000000`00000048, class base::ObserverList<net::ResolveContext::DohStatusObserver,1,0,base::internal::CheckedObserverAdapter>::HasObserver::<lambda_1> pred = class base::ObserverList<net::ResolveContext::DohStatusObserver,1,0,base::internal::CheckedObserverAdapter>::HasObserver::<lambda_1>, struct base::identity proj = <Value unavailable error>) [C:\projects\src\base\ranges\algorithm.h @ 483] 
04 (Inline Function) --------`--------     ____!base::ObserverList<net::ResolveContext::DohStatusObserver,1,0,base::internal::CheckedObserverAdapter>::HasObserver(class net::ResolveContext::DohStatusObserver * obs = 0x0000047c`01272b20)+0x5 [C:\projects\src\base\observer_list.h @ 304] 
05 00000000`00a1e0e0 00000001`41704f15     ____!base::ObserverList<net::ResolveContext::DohStatusObserver,1,0,base::internal::CheckedObserverAdapter>::AddObserver(class net::ResolveContext::DohStatusObserver * obs = 0x0000047c`01272b20)+0x23 [C:\projects\src\base\observer_list.h @ 271] 
06 00000000`00a1e140 00000001`40e28f2f     ____!system_media_controls::internal::SystemMediaControlsWin::AddObserver(class system_media_controls::SystemMediaControlsObserver * observer = 0x0000047c`01272b20)+0x15 [C:\projects\src\components\system_media_controls\win\system_media_controls_win.cc @ 132] 
07 00000000`00a1e180 00000001`40e28dc8     ____!content::MediaKeysListenerManagerImpl::StartListeningForMediaKeysIfNecessary(void)+0x8f [C:\projects\src\content\browser\media\media_keys_listener_manager_impl.cc @ 241] 
08 00000000`00a1e1d0 00000001`40e198b4     ____!content::MediaKeysListenerManagerImpl::StartWatchingMediaKey(ui::KeyboardCode key_code = VKEY_MEDIA_PLAY_PAUSE (0n179), class ui::MediaKeysListener::Delegate * delegate = 0x0000047c`000ee828)+0x18 [C:\projects\src\content\browser\media\media_keys_listener_manager_impl.cc @ 52] 
09 00000000`00a1e220 00000001`405d5fd3     ____!content::ActiveMediaSessionController::MediaSessionActionsChanged(class std::__1::vector<media_session::mojom::MediaSessionAction,std::__1::allocator<media_session::mojom::MediaSessionAction> > * actions = <Value unavailable error>)+0x124 [C:\projects\src\content\browser\media\active_media_session_controller.cc @ 81] 
0a 00000000`00a1e2a0 00000001`432fe873     ____!media_session::mojom::MediaControllerObserverStubDispatch::Accept(class media_session::mojom::MediaControllerObserver * impl = 0x0000047c`000ee820, class mojo::Message * message = <Value unavailable error>)+0x3f3 [C:\projects\src\out\Default\gen\services\media_session\public\mojom\media_controller.mojom.cc @ 2051] 
0b (Inline Function) --------`--------     ____!mojo::InterfaceEndpointClient::HandleValidatedMessage(class mojo::Message * message = <Value unavailable error>)+0x8b [C:\projects\src\mojo\public\cpp\bindings\lib\interface_endpoint_client.cc @ 898] 
0c 00000000`00a1e3d0 00000001`433a25a9     ____!mojo::InterfaceEndpointClient::HandleIncomingMessageThunk::Accept(class mojo::Message * message = 0x00000000`00a1e870)+0xb3 [C:\projects\src\mojo\public\cpp\bindings\lib\interface_endpoint_client.cc @ 329] 
0d 00000000`00a1e480 00000001`432ffa18     ____!mojo::MessageDispatcher::Accept(class mojo::Message * message = 0x00000000`00a1e870)+0x69 [C:\projects\src\mojo\public\cpp\bindings\lib\message_dispatcher.cc @ 43] 
0e 00000000`00a1e510 00000001`43304fd2     ____!mojo::InterfaceEndpointClient::HandleIncomingMessage(class mojo::Message * message = <Value unavailable error>)+0x38 [C:\projects\src\mojo\public\cpp\bindings\lib\interface_endpoint_client.cc @ 655] 
0f (Inline Function) --------`--------     ____!mojo::internal::MultiplexRouter::ProcessIncomingMessage(class mojo::internal::MultiplexRouter::MessageWrapper * message_wrapper = <Value unavailable error>, mojo::internal::MultiplexRouter::ClientCallBehavior client_call_behavior = ALLOW_DIRECT_CLIENT_CALLS (0n2), class base::SequencedTaskRunner * current_task_runner = 0x0000047c`0008f020)+0x176 [C:\projects\src\mojo\public\cpp\bindings\lib\multiplex_router.cc @ 1098] 
10 00000000`00a1e6a0 00000001`433a25a9     ____!mojo::internal::MultiplexRouter::Accept(class mojo::Message * message = <Value unavailable error>)+0x2a2 [C:\projects\src\mojo\public\cpp\bindings\lib\multiplex_router.cc @ 717] 
11 00000000`00a1e950 00000001`432fde20     ____!mojo::MessageDispatcher::Accept(class mojo::Message * message = 0x00000000`00a1ea58)+0x69 [C:\projects\src\mojo\public\cpp\bindings\lib\message_dispatcher.cc @ 43] 
12 (Inline Function) --------`--------     ____!mojo::Connector::DispatchMessageW(class mojo::Message * message = 0x00000000`00000000)+0x475 [C:\projects\src\mojo\public\cpp\bindings\lib\connector.cc @ 545] 
13 00000000`00a1e9e0 00000001`432c2bdb     ____!mojo::Connector::ReadAllAvailableMessages(void)+0x5f0 [C:\projects\src\mojo\public\cpp\bindings\lib\connector.cc @ 604] 
14 (Inline Function) --------`--------     ____!base::OnceCallback<void (void)+0x25 [C:\projects\src\base\callback.h @ 98] 
15 00000000`00a1ecd0 00000001`4339276e     ____!base::TaskAnnotator::RunTask(char * trace_event_name = <Value unavailable error>, struct base::PendingTask * pending_task = 0x0000047c`0207d000)+0x18b [C:\projects\src\base\task\common\task_annotator.cc @ 178] 
16 (Inline Function) --------`--------     ____!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(class base::sequence_manager::LazyNow * continuation_lazy_now = <Value unavailable error>)+0x5d1 [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 360] 
17 00000000`00a1ee10 00000001`432cf291     ____!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork(void)+0x65e [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 260] 
18 00000000`00a1f1c0 00000001`41372808     ____!base::MessagePumpForUI::DoRunLoop(void)+0x141 [C:\projects\src\base\message_loop\message_pump_win.cc @ 221] 
19 00000000`00a1f320 00000001`4188a3a3     ____!base::MessagePumpWin::Run(class base::MessagePump::Delegate * delegate = <Value unavailable error>)+0x48 [C:\projects\src\base\message_loop\message_pump_win.cc @ 79] 
1a 00000000`00a1f370 00000001`4134cee2     ____!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool application_tasks_allowed = <Value unavailable error>, class base::TimeDelta timeout = <Value unavailable error>)+0x83 [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 470] 
1b 00000000`00a1f3e0 00000001`40cde6e3     ____!base::RunLoop::Run(class base::Location * location = <Value unavailable error>)+0xb2 [C:\projects\src\base\run_loop.cc @ 136] 
1c 00000000`00a1f490 00000001`40ce0091     ____!content::BrowserMainLoop::RunMainMessageLoop(void)+0xc3 [C:\projects\src\content\browser\browser_main_loop.cc @ 989] 
1d 00000000`00a1f500 00000001`40cdbabc     ____!content::BrowserMainRunnerImpl::Run(void)+0x11 [C:\projects\src\content\browser\browser_main_runner_impl.cc @ 153] 
1e 00000000`00a1f530 00000001`407c089a     ____!content::BrowserMain(struct content::MainFunctionParams * parameters = <Value unavailable error>)+0xac [C:\projects\src\content\browser\browser_main.cc @ 49] 
1f (Inline Function) --------`--------     ____!content::RunBrowserProcessMain(struct content::MainFunctionParams * main_function_params = 0x00000000`00a1f710, class content::ContentMainDelegate * delegate = 0x00000000`00a1fab0)+0x67 [C:\projects\src\content\app\content_main_runner_impl.cc @ 608] 
20 00000000`00a1f5d0 00000001`407c029a     ____!content::ContentMainRunnerImpl::RunBrowser(struct content::MainFunctionParams * main_params = 0x00000000`00a1f710, bool start_minimal_browser = <Value unavailable error>)+0x59a [C:\projects\src\content\app\content_main_runner_impl.cc @ 1104] 
21 00000000`00a1f6d0 00000001`407bee93     ____!content::ContentMainRunnerImpl::Run(bool start_minimal_browser = <Value unavailable error>)+0x19a [C:\projects\src\content\app\content_main_runner_impl.cc @ 971] 
22 00000000`00a1f7a0 00000001`407bf626     ____!content::RunContentProcess(struct content::ContentMainParams * params = 0x00000000`00a1fa40, class content::ContentMainRunner * content_main_runner = 0x0000047c`0006c7a0)+0x53 [C:\projects\src\content\app\content_main.cc @ 394] 
23 00000000`00a1f9b0 00000001`3ffcd47b     ____!content::ContentMain(struct content::ContentMainParams * params = <Value unavailable error>)+0x36 [C:\projects\src\content\app\content_main.cc @ 422] 
24 00000000`00a1f9f0 00000001`43717ac2     ____!wWinMain(struct HINSTANCE__ * instance = <Value unavailable error>, wchar_t * cmd = <Value unavailable error>)+0x3ab [C:\projects\src\electron\shell\app\electron_main.cc @ 289] 
25 (Inline Function) --------`--------     ____!invoke_main(void)+0x21 [d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 118] 
26 00000000`00a1fbe0 00000000`76c555dd     ____!__scrt_common_main_seh(void)+0x106 [d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
27 00000000`00a1fc20 00000000`76eb2b1d     kernel32!BaseThreadInitThunk+0xd
28 00000000`00a1fc50 00000000`00000000     ntdll!RtlUserThreadStart+0x1d

**Comment by HppZ** [comment]
rax=fffff900c20b5c10 rbx=0000000000000000 rcx=0000000000000000
rdx=0000000000000000 rsi=0000000000000000 rdi=0000000000000000
rip=0000000000000000 rsp=0000000000000000 rbp=0000000000000000
 r8=0000000000000000  r9=0000000000000000 r10=0000000000000000
r11=0000000000000000 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up di pl nz na pe nc
cs=0000  ss=0000  ds=0000  es=0000  fs=0000  gs=1b14             efl=00000000
00000000`00000000 ??              ???

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by HppZ** [comment]
you sounds like a bot.

**Comment by codebytere** [comment]
@HppZ i'm not a bot. In order for us to proceed triage, we're going to need more information as I specified above. Please let me know whether this is information you'll be able to provide.

**Comment by codebytere** [comment]
No - we need some idea of what _code you were running_ when this happened. See my first comment for more information about what that means.

**Comment by HppZ** [comment]
> No - we need some idea of what _code you were running_ when this happened. See my first comment for more information about what that means.

that is exactly what call stack is, isn't it?

**Comment by codebytere** [comment]
No. It's not. Please reread

> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com/) that Electron maintainers can use.

and address the request, otherwise I will close this issue.

**Comment by lorand-horvath** [comment]
@codebytere This bug report has most probably the same cause as https://github.com/electron/electron/issues/35219
