### ISSUE TITLE
[Bug]:  Trace/breakpoint trap in centos arm64

### ISSUE THREAD

**Issue by yijialee** [electron/electron#35203]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v20.0.0 v18.3.6 v19.0.10

### What operating system are you using?

Other Linux

### Operating System Version

centos8 

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

None

### Expected Behavior

work well

### Actual Behavior

![image](https://user-images.githubusercontent.com/6447599/182588391-0b8f1757-214c-486c-b9fb-9cb40c75bbec.png)
Trace/breakpoint trap

**Comment by molizz** [comment]
一样的问题～ 关注一样

**Comment by yijialee** [comment]
https://github.com/yijialee/electron-arm64-test1/tree/master
@codebytere 
This is the test repo. Run npm run buildarm to get rpm file .  I installed the rpm in centos8 form arm64 ,then I got this

![image](https://user-images.githubusercontent.com/6447599/182750653-36632dc5-07d9-4d70-ad18-53c96189b4bc.png)

**Comment by ckerr** [comment]
Possibly specific to arm64?

When running https://github.com/yijialee/electron-arm64-test1/tree/master on amd64 & Ubuntu 22.04, I'm not able to reproduce the crash when running the code unpackaged, e.g. with `$ electron /path/to/main.js`

> This is the test repo. Run npm run buildarm to get rpm file . I installed the rpm in centos8 form arm64 ,then I got this

@yijialee just to clarify, are you saying that the code _must be packaged_ in order for the crash to happen? When you run unpackaged, do you still get a coredump?

**Comment by yijialee** [comment]
here is the rpm file 
https://github.com/yijialee/electron-arm64-test1/releases
