### ISSUE TITLE
[Bug]: navigator.windowControlsOverlay not set when only child window uses WCO

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#35214]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

`navigator.windowControlsOverlay` is available when window uses WCO.

### Actual Behavior

When a parent window without WCO opens a child window using `open()`, that child window won't have `navigator.windowControlsOverlay` available if it uses WCO.

![image](https://user-images.githubusercontent.com/1656324/182700171-cc21ef7b-11b6-421d-a9fc-fab6a93872aa.png)

### Testcase Gist URL

https://gist.github.com/samuelmaddock/4306f4fa0966ed39e4a8c094b236322e

**Comment by codebytere** [comment]
Looks like this is already fixed in main - i'll try to figure out where.

**Comment by mlaurencin** [comment]
Closing since cherry-picked fix was merged
