### ISSUE TITLE
[Bug]: app.getPath('cache') is missing in the typings of electron v20

### ISSUE THREAD

**Issue by zschreur** [electron/electron#35210]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5

### What arch are you using?

x64

### Last Known Working Electron version

19.0.10

### Expected Behavior

`app.getPath('cache')` should compile correctly in typescipt.

### Actual Behavior

`app.getPath('cache')`gives a typescript compile error: 
```
Argument of type '"cache"' is not assignable to parameter of type '"userData" | "home" ...' ts(2345)
```

Note that calling `app.getPath('cache')` still works. The only issue is the typing.

**Comment by MarshallOfSound** [comment]
@zschreur This was a deliberate change, `cache` was never meant to be public API --> https://github.com/electron/electron/pull/33509

**Comment by manuhank** [comment]
@MarshallOfSound  Should this have been added to the breaking changes?
