### ISSUE TITLE
Remove the 8 GB memory limitation in the renderer process imposed by Chromium

### ISSUE THREAD

**Issue by jssdgit** [electron/electron#35218]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Per https://github.com/electron/electron/issues/31330 and https://github.com/electron/electron/issues/35032 the 8 GB limit in Electron occurs only in Windows, and has nothing to do with V8 pointer compression.  I am formally requesting that Electron make official the changes developed by @marcelblum from https://github.com/electron/electron/issues/35032#issuecomment-1204014976.

I argue that whatever memory issues the Chromium team were trying to deal with when they hard coded this limit in the browser based application are not relevant to Electron.  My company has developed a complex data analysis application that can process many GB of data in memory.  It has worked fine for years in Electron versions prior to 13.  The main reason we chose Electron was to get around the resource limitations imposed upon us by the Chrome browser (specifically memory and disk space).  I would rather focus my efforts on supporting my company's application than on maintaining my private version of Electron just so our customers can run it.  I strongly suspect other companies and developers share this reasoning and would also appreciate not having to support private versions of Electron just to get back to 16 GB.

My company's application works fine in Firefox.  It is not subjected to the same resource limitations as in Chrome.  I've never understood why Chrome was so limiting.   That Electron allowed us to escape these seemingly arbitrary bounds was wonderful.  Please continue to support that!

(Perhaps this should be directed to the Chromium team after all.  But see https://bugs.chromium.org/p/chromium/issues/detail?id=416284 for discussions back in 2014 wherein they asked "Why would anyone need more than 4 GB?" and stated the limit exists because "it's a security issue."  Those kinds of responses don't give me much hope.) 

Indeed, there has been a bug about this open with the Chromium team for almost a year now:

https://bugs.chromium.org/p/chromium/issues/detail?id=1243314 

### Proposed Solution

Make official the changes developed by @marcelblum from https://github.com/electron/electron/issues/35032#issuecomment-1204014976.

### Alternatives Considered

It is possible for every single Electron user to maintain their own private build of Electron with the changes @marcelblum applied.  But I suspect that will be a lot of users.  Why should we all have to maintain our own private builds over something so simple to change?

**Comment by MarvMartian** [comment]
Why would we limit it to 16G?  Can it be higher?  If so, why have a limit at all?

**Comment by jssdgit** [comment]
> Why would we limit it to 16G? Can it be higher? If so, why have a limit at all?

Ha!  I was afraid to be the one to ask for too much all at once.  But yes!  Why is there a limit at all?

**Comment by codebytere** [comment]
Duplicate of https://github.com/electron/electron/issues/33994

**Comment by codebytere** [comment]
And in agreement with a comment there -  pointer compression is a fundamental performance feature of V8 that we definitely don't want to do differently to upstream or we're going to run into super bad edge cases. We can document this but it's not something we're prepared to remove.

**Comment by MarvMartian** [comment]
The Chromium team has weighed in on this now:  https://bugs.chromium.org/p/chromium/issues/detail?id=1243314#c31 (comment 31).  They appear to be saying that @marcelblum's patch will work for Windows 10+ without issues, and that it will also work for older versions although with potential performance issues.  They propose adding a parameter so that the Electron project doesn't have to patch, and they appear to see no reason for any limit other than performance for Windows <10.  @codebytere can we reopen/rename this bug or open a new bug to track this?

**Comment by jssdgit** [comment]
@codebytere no one is suggesting that pointer compression be removed.  The 8 GB limit has nothing to do with pointer compression.

**Comment by jssdgit** [comment]
@codebytere Why is https://github.com/electron/electron/issues/33994?  That bug refers to only documenting that the limit exists, not potentially working around it.

**Comment by jpambrun** [comment]
@codebytere I believe you are mistaken on the pointer compression point, but beyond that, marking this is a duplicate of #33994 in nonsensical as they are in complete opposite directions.
