### ISSUE TITLE
[Bug]: WebSerial - SerialPort doesn't open in Electron 20

### ISSUE THREAD

**Issue by rafaelpimpa** [electron/electron#35282]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.1

### What operating system are you using?

Windows

### Operating System Version

Win 10 Pro 19043

### What arch are you using?

x64

### Last Known Working Electron version

19.0.11

### Expected Behavior

WebSerial API should open a serial port.

### Actual Behavior

The ``getInfo`` method works fine, but ``open`` fails to open the port.

### Testcase Gist URL

https://gist.github.com/17afc65be515f3a1aec6256cb69f069d
https://github.com/rafaelpimpa/electron-webserial-bug-repro

### Additional Information

Error thrown is ``NetworkError: Failed to open serial port.``
I didn't use an Arduino to test, but it should work the same, since it works in v19.
Reproduction has the same code from the docs.

**Comment by codebytere** [comment]
cc @jkleinsc

**Comment by rafaelpimpa** [comment]
@codebytere 

Last working version: ``19.0.11``.
It's broken since ``20.0.0-alpha.1``, although I didn't test nightly builds — what's the easiest way to test nightly builds?.
It also do not work with the recent ``21.0.0-alpha.1``.

BTW the error thrown is just ``DOMException: Failed to open serial port.``.

**Comment by codebytere** [comment]
@rafaelpimpa https://github.com/electron/fiddle is probably the easiest way! you can check nightlies there as well as all other versions.

**Comment by rafaelpimpa** [comment]
Found it: it was broken in https://github.com/electron/electron/releases/tag/v20.0.0-nightly.20220518

**Comment by codebytere** [comment]
@rafaelpimpa sweet - so here: https://github.com/electron/electron/compare/v20.0.0-nightly.20220517...v20.0.0-nightly.20220518

i'd guess the Chromium roll - we'll keep looking from here, thank you 🙇🏻‍♀️

**Comment by rafaelpimpa** [comment]
> @rafaelpimpa got a fix up!

Wow pretty fast, awesome! thank you! Hopefully gets in next minor :)

**Comment by rafaelpimpa** [comment]
BTW the fix hasn't come yet to 20.x.y, is that usual? At least not in release notes.

I see that it needs manual backport to 20.x.y, should I just wait for v21 become stable?

**Comment by codebytere** [comment]
hey - yeah, i need to manually open a backport to 20. I can try to do it tomorrow :)

**Comment by dusionlike** [comment]
> hey - yeah, i need to manually open a backport to 20. I can try to do it tomorrow :)

@codebytere Hey. Has this been released yet? I tried it on 20.x and still got the error. ❤️

**Comment by davej** [comment]
@codebytere I don't think this has been fixed correctly (or if it has then it seems to have regressed). This is still an issue in Electron `23.1.0`. I tested it on Electron `19.1.8` and it is working perfectly but fails on Electron `23.1.0`. Let me know if you'd like me to put together a gist?

**Comment by chris-fung** [comment]
> 

same problem here, thanks bro.

**Comment by rafaelpimpa** [comment]
Works fine for me with electron@23, but doesn't work with electron@20 still.

**Comment by nevets963** [comment]
@rafaelpimpa What OS are you running? I'm testing on a Macbook Pro M2 (running: 13.3 (22E252)) and I'm not getting any serial devices reported back.

@jkleinsc I saw your great work (https://github.com/electron/electron/pull/37441) getting WebUSB running on Apple Silicon Macs - I'm wondering if there is overlap here with this issue?

**Comment by rafaelpimpa** [comment]
> @rafaelpimpa What OS are you running? I'm testing on a Macbook Pro M2 (running: 13.3 (22E252)) and I'm not getting any serial devices reported back.

Windows 10

**Comment by nevets963** [comment]
In the end, I managed to get it working using Electron version 23.2.1 on my Mac running 13.3.1 using this gist: https://gist.github.com/rafaelpimpa/17afc65be515f3a1aec6256cb69f069d
