### ISSUE TITLE
[Bug]: Headers server for past version not available

### ISSUE THREAD

**Issue by monoto** [electron/electron#35287]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.16.0

### What operating system are you using?

Windows

### Operating System Version

Windows 8.1

### What arch are you using?

x64

### Expected Behavior

Building native module againt a past version of electron.

### Actual Behavior

gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.16.0 | win32 | x64
gyp info find Python using Python version 2.7.18 found at "C:\Python27\python.exe"
gyp http GET https://electronjs.org/headers/v16.16.0/node-v16.16.0-headers.tar.gz
gyp http 404 https://electronjs.org/headers/v16.16.0/node-v16.16.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://electronjs.org/headers/v16.16.0/node-v16.16.0-headers.tar.gz

### Additional Information

Unable to build native module using this commad:

set "HOME=~/.electron-gyp" & "\node-gyp" rebuild --target=16.16.0 --arch=x64 --dist-url=https://electronjs.org/headers

**Comment by MarshallOfSound** [comment]
Electron never shipped a version called "16.16.10" you have to provide a real electron version in order to download headers

**Comment by TamojitSaha** [comment]
Hi @monoto 
The following worked for me `node-gyp rebuild --target=16.14.2 --arch=x64 --dist-url=https://nodejs.org/download/release`
