### ISSUE TITLE
[Bug]: Segmentation fault on Windows 11

### ISSUE THREAD

**Issue by danie007** [electron/electron#35295]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

9.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro Insider Preview

### What arch are you using?

x64

### Expected Behavior

```log
$ electron-webpack dev
┏ Renderer -------------------

  i ｢wds｣: Project is running at http://localhost:65240/
  i ｢wds｣: webpack output is served from /
  i ｢wds｣: Content not from webpack is served from B:\git_tmp\app\static, B:\git_tmp\app\dist\renderer-dll

┗ ----------------------------
┏ Main -----------------------
```

### Actual Behavior

```log
$ electron-webpack dev
error Command failed with exit code 3221225477.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/c/Users/*/AppData/Roaming/npm/yarn: line 14:  1789 Segmentation fault      node "$basedir/node_modules/yarn/bin/yarn.js" "$@"
```

### Additional Information

On `win11`, I often observe this error while starting our `Electron` application. When I try this exact code in `Ubuntu22.04` it's working perfectly.

On Windows, if I repeat (2 or 3 times)the comman it'll start the app, hence it's occasionally (_but frequently_) failing.

I use yarn to manage the commands and I'm not sure whether it's an issue with `yarn` or `electron-webpack`

Any help would be highly appreciable, thanks in advance.

---

CC @tkmozhi

**Comment by codebytere** [comment]
v14 is no longer supported - in order for us to triage this you'll need to demonstrate it occurs on a supported version (v18 and beyond). I'm setting the `blocked/needs-info` label for that reason, and will close this issue in 10 days if no further information is provided.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
