### ISSUE TITLE
[Bug]:  how to hide the floating layer showing width and height in the upper right-hand corner

### ISSUE THREAD

**Issue by Rabbitzzc** [electron/electron#35291]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

macOS

### Operating System Version

Macos bigsur

### What arch are you using?

x64

### Last Known Working Electron version

16.0.0

### Expected Behavior

hide it.

### Actual Behavior

<img width="530" alt="WechatIMG66108" src="https://user-images.githubusercontent.com/26913511/183810771-316d60ce-706b-4a6e-9828-9a106e313574.png">

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by Rabbitzzc** [comment]
ok,I didn't know where to ask the question, but now I get it... Thanks...

> Thanks for reaching out!
> 
> Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by Rabbitzzc** [comment]
> Thanks for reaching out!
> 
> Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

discord lost. Please send a new invitation dicord link.
