### ISSUE TITLE
[Bug]: Desktop applications developed by Electorn cannot run node-canvas properly,catch Exception

### ISSUE THREAD

**Issue by linqian02** [electron/electron#35290]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

7.3.3

### What operating system are you using?

Windows

### Operating System Version

Window 10  version 21H2

### What arch are you using?

x64

### Expected Behavior

Hello, I use Electron and node-canvas to build desktop applications in windows environment and package them into .exe. But the software can't run normally on some computers, throwing the following error.

![image](https://user-images.githubusercontent.com/29908531/183802069-0f5af54d-0316-450e-a010-3ae43d8c5445.png)

### Functioning system
    1. Windows 10 1903 , x64 
    2. Windows 7 7601 Service Pack1, x64
    
<img src="https://user-images.githubusercontent.com/29908531/183787130-9d6205fe-aea6-440d-b642-0bf51bdc24e9.png"  height="324">

### Non-functioning system
    1. Window 10 21H2 i7-8500u，x64
    2. Window 10 21H2 i5-10400F，x64
<img src="https://user-images.githubusercontent.com/29908531/183787234-00bcacfe-a054-44e3-ad15-0c37a854ecdf.jpg"  height="324">

I can't find any way to solve the problem. Need help,Thanks!

## Development Environment

canvas@2.9.1
electron@7.3.3
electron-build@23.0.3
electron-rebuild@3.2.7
node v14.18.0 on window10

### Actual Behavior

the software can't run normally,catch Exception!

**Comment by RaisinTen** [comment]
Can you check if `C:\Program Files\MD Video\resources\app.asar.unpacked\node_modules\canvas\build\Release\canvas.node` exists on your file system?

**Comment by codebytere** [comment]
Electron v7 hasn't been supported in multiple years - in order for us to triage this you'll need to demonstrate it occurs on a supported version (v18 and beyond). I'm setting the `blocked/needs-info` label for that reason, and will close this issue in 10 days if no further information is provided.

**Comment by linqian02** [comment]
> Can you check if `C:\Program Files\MD Video\resources\app.asar.unpacked\node_modules\canvas\build\Release\canvas.node` exists on your file system?

@RaisinTen  Thank you for your reply。It does exist on my file system。

But I found a solution. Use Visual Studio 2015 instead of visual studio 2017

**Comment by ajoslin103** [comment]
FWIW: FabricJS now works in Electron !!

**Comment by linqian02** [comment]
> FWIW: FabricJS now works in Electron !!

@ajoslin103  

I cannot succeed in this, how do I need to configure it?

**Comment by ajoslin103** [comment]
I use this boilerplate: https://github.com/hellosoftware-io/electron-typescript-react-mui

clone it down and go into that folder

I ran this with node v16.18.1

install deps `npm i`

then `npm install fabric @types/fabric`

then start it up `npm run dev`

then replace their `Greetings.tsx` with this:

```
import { Container, Grid } from "@mui/material";
import React from "react";

// http://fabricjs.com/docs/
import { fabric } from "fabric";

export default function Greetings() {

  const [canvas, setCanvas] = React.useState<fabric.Canvas | undefined>();

  React.useEffect(() => {
    if (!canvas) {
      setCanvas(new fabric.Canvas("canvas", { backgroundColor: "white" }));
    }
    if (canvas) {
      canvas.add(new fabric.Rect({ top: 15, left: 15, width: 100, height: 100, fill: "green" }))
      canvas.add(new fabric.Circle({ top: 100, left: 100, radius: 100, fill: "red" }))
    }
  }, [canvas]);

  return (
    <Container maxWidth="md" sx={{ mt: 8 }}>
      <Grid container justifyContent="center">
        <canvas id="canvas" width={600} height={400} />
      </Grid>
    </Container>
  );
}
```

**Comment by ajoslin103** [comment]
this repo uses a fabric canvas without using the Fabric classes  

https://github.com/mudin/indoorjs

**Comment by linqian02** [comment]
Thank you, but what I need is to use fabricjs in the main process of Electron instead of the render process.

**Comment by ajoslin103** [comment]
try importing and using fabric-pure-browser - it might be a drop-in replacement for node-canvas

apologies, I don't have any canvas experience outside the renderer
