### ISSUE TITLE
[Bug]: Unable to exit pdf present mode in WebView

### ISSUE THREAD

**Issue by PaliMartin** [electron/electron#35304]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Should be able to exit pdf present mode, in Chrome it is possible to exit present mode by pressing Esc.

### Actual Behavior

Unable to exit pdf present mode once it is selected. The Esc key only affects the windows full-screen mode, but the pdf view is unchanged.

![image](https://user-images.githubusercontent.com/111048903/184098506-5b1b63b6-c0ba-44ae-be74-e4a6bdafeb39.png)

### Testcase Gist URL

https://gist.github.com/4868233713a4119d96c9273494157843

**Comment by codebytere** [comment]
This appears to be specific to webviews - it works as expected when i do:

```
mainWindow.loadURL('https://www.electrolux-medialibrary.com/scoop/public/712310?signature=3a3d234f4396a465cdd3a1bf8270024b9bbea361d70c633fa4b3851e60abfc4d')
```

**Comment by anderklander** [comment]
Bump, reproduced in 21.3.0 and 22-beta6
