### ISSUE TITLE
[Bug]: (Linux/Wayland) Wrong scaling in multi-monitor setups with different UI scale settings

### ISSUE THREAD

**Issue by toreanderson** [electron/electron#35325]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.2

### What operating system are you using?

Other Linux

### Operating System Version

Fedora Linux 36

### What arch are you using?

x64

### Expected Behavior

The Electron app should respect the scaling setting of the monitor the app window is placed on.

### Actual Behavior

The Electron app uses the scaling setting of the primary monitor, regardless of which monitor the app window is placed on.

### Additional Information

This issue can be easily reproduced by starting [Electron Quick Start](https://github.com/electron/electron-quick-start) app.

My setup uses two monitors: an external 31.5" 3840x2160 monitor and a 13.4" 3840x2400 internal laptop display. They are stacked on top of each other, external monitor on top, both in landscape mode, leaving me with a 3840x4560 desktop. The external monitor is the designated primary in the GNOME monitor settings. The internal laptop display has scale set to 200% (otherwise everything would become extremely tiny and essentially unreadable).

When the Electron app is located on the primary montor (i.e., the top one), scaling is 100%, as expected (note: screenshots have been scaled down to 30% of original size):

![Electron on external monitor](https://user-images.githubusercontent.com/4557060/184511421-ecb3b6f0-9a4f-4b18-8411-0e41d9ae266a.png)

If I now move the Electron window down to the laptop monitor with scale=200%, the Electron app does *not* change its scale:

![Electron on laptop monitor](https://user-images.githubusercontent.com/4557060/184511454-68be78b5-1e18-43e8-9f9d-0bfb627c25dd.png)

Do note how the fonts and titlebar in the terminal windows I also moved to the laptop monitor *did* change size, as expected.

However, if I disconnect the external monitor, so that the laptop monitor becomes the primary one, the Electron window *does* change its scale:

![Electron on laptop monitor with external monitor disconnected](https://user-images.githubusercontent.com/4557060/184511528-663229f1-b90b-4f6f-8725-8f26b1794a9b.png)

Thus we can conclude that Electron *does* have the capability to respect the scale setting. It just does not correctly when located on a monitor that has a different scale setting than the primary one. As my screenshots show, the GNOME Terminal is able to get it right, so Electron should too.

**Comment by RaisinTen** [comment]
@toreanderson is v20.0.2 the first electron version where this regression was introduced? If not, could you try out the earlier versions and check if this ever worked as expected?

**Comment by toreanderson** [comment]
Hi

I do not know if this is a regression actually. That said, I think it is an upstream issue in Chrome/Chromium, because there's a workaround which involve adding a couple of browser flags:

```
~/electron-quick-start $ npm start -- --ozone-platform=wayland --enable-features=WaylandWindowDecorations
```

This also works for Electron apps like Mattermost and Slack. However the `--enable-features=WaylandWindowDecorations` appears to make the application miscalculate its available area, so content shown within can "overflow" into an invisible area outside of the window, so to speak – instead of text wrapping before reaching the end, for example. Dropping `--enable-features=WaylandWindowDecorations` resolves this, but then there are no window decorations (but that's still better than the content being unreadably small).

**Comment by ultimaweapon** [comment]
I still have this problem with the latest VS Code.

**Comment by gonzzor** [comment]
Still happens with VS Code

```
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.1.12-200.fc37.x86_64
Sandboxed: No
```
