### ISSUE TITLE
[Bug]: Moving mouse causes unexpected background CPU usage

### ISSUE THREAD

**Issue by xanderfrangos** [electron/electron#35327]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 (19044) & Windows 11 (22621)

### What arch are you using?

x64

### Expected Behavior

If a standard Electron window is occluded, hidden with `BrowserWindow.hide()`, or is simply not focused, moving the mouse cursor should not produce additional CPU usage. 

### Actual Behavior

Even when out of focus, mouse movement still causes CPU usage for the main process to go up by a small amount. Minimizing all application windows appears to stop it. However, neither the window being occluded nor using `BrowserWindow.hide()` helps. 

This CPU usage is multiplied by the mouse's polling rate. Depending on the user's CPU and mouse polling rate, it can reach several % (as estimated by Task Manager).

![cpu-usage-mouse](https://user-images.githubusercontent.com/33106561/184558722-efb210e9-bd23-4db9-965e-94724d1d7d28.jpg)

All supported Electron versions appear to be affected.

### Testcase Gist URL

https://github.com/electron/electron-quick-start

### Additional Information

This can be reproduced with [electron-quick-start](https://github.com/electron/electron-quick-start) and most Electron apps (ex. Discord, Visual Studio Code, GitHub Desktop, Crushee). Simply open the app and Task Manager, click away to another (non-admin window), and move your mouse aggressively. The higher the polling rate, the higher the usage will go up. 

![electron-quick-start](https://user-images.githubusercontent.com/33106561/184558754-1aa1ff1a-d95b-402a-ab1b-98df5e489f56.jpg)

While the actual CPU usage is small, this adds up. Many apps that people have running in the background are Electron-based, and each one might be taking a small, unnecessary cut of the CPU. When gaming, this can impact FPS while moving the mouse. While CPU-intensive tasks are active, this affects cursor responsiveness. For laptops, this can lead to unnecessary battery drain.

Minimizing the windows appears to stop the issue, but developers cannot be expected to remind their users to always minimize their unfocused applications. Additionally, `BrowserWindow.hide()` does not fix this. I would expect it to. And if this is expected behavior, there should be a way to force this background mouse event listening to stop.

**Comment by aleksey-hoffman** [comment]
Doesn't seem to be an Electron issues. You can reproduce this in the latest Chrome browser. 
If Chromium was pausing input listeners on window blur, you would be able to interact with the window and see any layout / paint changes when the window is blurred

**Comment by xanderfrangos** [comment]
@aleksey-hoffman 

I can see a case for it still being on when the window is blurred but visible, but the Page Visibility feature currently detects when windows are occluded or hidden (via minimize or `hide()`). This detection seems to be handled on the Electron side, and then passed over to Chromium (as far as I can tell from PRs/Issues). Shouldn't the mouse event listeners be paused with the same events as the Page Visibility API?

**Comment by MarshallOfSound** [comment]
> Shouldn't the mouse event listeners be paused with the same events as the Page Visibility API?

No, the occlusion detection is for renderer views only.  There are other native views that could be running at any point E.g. menus, WCO, etc.

As indicated by @aleksey-hoffman this issue is upstream in Chromium, you should raise a crbug if you want the behavior changed
