### ISSUE TITLE
[Bug]: WCO "un-maximize" icon is not centered properly

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#35346]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.11

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Expected Behavior

This is how it looks in Google Chrome:

<img width="209" alt="image" src="https://user-images.githubusercontent.com/79877362/184757827-94d9f10b-e568-48c4-b7cb-1a6cd96d65d0.png">

### Actual Behavior

This is how it looks in Electron:

<img width="193" alt="image" src="https://user-images.githubusercontent.com/79877362/184757842-550591a4-b894-4554-8273-336f14988819.png">

### Additional Information

cc @codebytere

**Comment by indutny** [comment]
Here is a zoomed-in overlay of two images to make it easier to see the difference:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/238531/184762026-ac9b6764-4b8e-4ef0-836c-b6fcd43761ed.png">

**Comment by Prinzhorn** [comment]
Is this different from #35038?

**Comment by indutny-signal** [comment]
Nope, this is a duplicate. Sorry, I couldn't find it! (Probably because I forgot that the button is called "restore" and not "un-maximize" :joy:)
