### ISSUE TITLE
[Bug]: webserial API can not open in 20.0.*

### ISSUE THREAD

**Issue by zhanglongqi** [electron/electron#35349]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.*

### What operating system are you using?

Ubuntu

### Operating System Version

5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

19.0.12

### Expected Behavior

```js
this.port
	.open({
		baudRate: 9600,
		dataBits: 8,
		parity: "none",
		stopBits: 1,
		flowControl: "none",
	})
	.then(() => {
		this.is_opened = true;
	})
	.catch((error) => {
		console.error("open_port error", error);
	});
```

![image](https://user-images.githubusercontent.com/956693/184783977-237c20d7-b62f-4baf-b56a-f7147a54b1b6.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/956693/184785170-9286fd1d-f44c-40e8-8cf4-59cf8cce6573.png)

**Comment by Prinzhorn** [comment]
https://github.com/electron/electron/issues/35282

**Comment by VerteDinde** [comment]
Closing as a duplicate (thanks @Prinzhorn!). @zhanglongqi, this should be addressed in the next 20 release, which we're planning on cutting Wednesday morning, PST.
