### ISSUE TITLE
[Bug]: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#35378]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.13

### What operating system are you using?

Other Linux

### Operating System Version

debian 5.19.12 / plasma 25.4

### What arch are you using?

x64

### Last Known Working Electron version

19.0.11

### Expected Behavior

App should start through wayland-only session.

### Actual Behavior

```
> "/opt/Signal Beta/signal-desktop-beta" --enable-features=UseOzonePlatform --ozone-platform=wayland
[4:0818/153410.892677:ERROR:browser_main_loop.cc(271)] Gdk: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed
[105:0818/153410.998572:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is egl, ANGLE is
```

### Additional Information

This happens on the latest Signal Beta that we published (5.56.0-beta.1)

**Comment by codebytere** [comment]
@indutny-signal this looks like an upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1268758

**Comment by indutny-signal** [comment]
@codebytere thanks for finding it! It sounds like the same thing indeed.

**Comment by major-mayer** [comment]
This issue has re-appeared at least when using Chromium-based apps (like Signal-Desktop) in an XWayland environment: https://bugs.chromium.org/p/chromium/issues/detail?id=1499226&q=wl_proxy_get_version&can=2

**Comment by zds-kansalliskirjasto** [comment]
I'm trying to install Eclipse right now, and the installer keeps crashing after getting tons of these.

`(Eclipse Installer:92084): Gdk-CRITICAL **: 09:02:24.522: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed

(Eclipse Installer:92084): Gdk-CRITICAL **: 09:02:24.585: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed

(Eclipse Installer:92084): Gdk-CRITICAL **: 09:02:24.617: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed

(Eclipse Installer:92084): Gdk-CRITICAL **: 09:02:24.837: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed

(Eclipse Installer:92084): Gdk-CRITICAL **: 09:02:27.252: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed

(WebKitWebProcess:92344): Gtk-WARNING **: 09:02:29.585: cannot open display: wayland-0

** (Eclipse Installer:92084): ERROR **: 09:02:29.833: readPIDFromPeer: Unexpected short read from PID socket
`

The distro is based on Ubuntu 22.04 LTS.
