### ISSUE TITLE
[Bug]: `fullscreen` browser window options are confusing and wrongly documented

### ISSUE THREAD

**Issue by bpasero** [electron/electron#35372]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19

### What operating system are you using?

macOS

### Operating System Version

12

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The `fullscreen` option of a `BrowserWindow` behaves in a confusing way.

### Actual Behavior

The JSDoc reads that `false` is the default, but that is not true, because that would mean by default a macOS window could not be set to fullscreen.

And then when you pass in `undefined`, the pure presence of the value makes the window disable fullscreen support, you really have to omit the property from being passed in.

### Testcase Gist URL

https://gist.github.com/2b3f1e1386642faba7eed3a38dc3d124

**Comment by bavulapati** [comment]
@bpasero Are you referring to `fullscreenable` too?
The issue description talks about multiple options, where as the description and the gist mentions `fullscreen` alone.

**Comment by bpasero** [comment]
No just `fullscreen`, maybe the other was added later? However I noticed that there is `window.isFullScreen()` and `window.fullscreen` 🤔

**Comment by codebytere** [comment]
`window.isFullScreen()` and `window.fullscreen` are identical - we intentionally allow for both property and function access to this information.

**Comment by bpasero** [comment]
Keep
