### ISSUE TITLE
electron Version 20.0.3  20.0.2 not runing 

### ISSUE THREAD

**Issue by ramieita** [electron/electron#35373]
can't run the Electron  App 

**symbol lookup error: /**/**/my-electron-app/node_modules/electron/dist/electron: undefined symbol: drmGetNodeTypeFromFd**

node Version  v16.16.0
npm 8.11.0

iam working on a DevVM 

any suggestions ?

**Comment by bavulapati** [comment]
Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
