### ISSUE TITLE
[Feature Request]: the render-process-gone event of webContents exposes more exception information

### ISSUE THREAD

**Issue by WangYuLue** [electron/electron#35385]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hey guys，When electron crashes and exits, the render-process-gone event of webContents only has very brief exception information, which makes troubleshooting difficult. Whether more abnormal information can be exposed to facilitate troubleshooting

![截屏2022-08-19 21 39 54](https://user-images.githubusercontent.com/19245919/185631386-63d1da5b-3a6f-459c-9fd0-75c4b65188b5.png)

### Proposed Solution

Add the detailMessage property to details to display detailed error information；

Event: 'render-process-gone'

Returns:
- event Event
- details Object
  - reason string 
  - exitCode Integer
  -  detailMessage string 

### Alternatives Considered

N/A

**Comment by codebytere** [comment]
Unfortunately no - this: https://github.com/electron/electron/blob/97b353a30a0e92a169fb0557ddff641fa0332d7c/shell/browser/api/electron_api_web_contents.cc#L1612-L1627


is the information we have access to and that's provided to us from Chromium. If this changes, we would be happy to look into exposing it.
