### ISSUE TITLE
[Bug]: Preload script works in 19.0.13 but fails in 20.0.3

### ISSUE THREAD

**Issue by robertpatrick** [electron/electron#35387]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3

### What operating system are you using?

macOS

### Operating System Version

12.5

### What arch are you using?

x64

### Last Known Working Electron version

19.0.13

### Expected Behavior

My application to load our[ ipcRendererPreload.js](https://github.com/oracle/weblogic-toolkit-ui/blob/main/electron/app/js/ipcRendererPreload.js) file properly after moving from Electron 19.x to Electron 20.x.

### Actual Behavior

I get an errors at startup printed to the devtools window:

```
Unable to load preload script: /Users/rpatrick/Projects/weblogic-toolkit-ui/electron/app/js/ipcRendererPreload.js
(anonymous) @ VM4 sandbox_bundle:93

Error: module not found: path
    at preloadRequire (VM4 sandbox_bundle:93:1386)
    at <anonymous>:8:14
    at runPreloadScript (VM4 sandbox_bundle:93:2213)
    at Object.<anonymous> (VM4 sandbox_bundle:93:2480)
    at ./lib/sandboxed_renderer/init.ts (VM4 sandbox_bundle:93:2636)
    at __webpack_require__ (VM4 sandbox_bundle:1:170)
    at VM4 sandbox_bundle:1:1242
    at ___electron_webpack_init__ (VM4 sandbox_bundle:1:1320)
    at VM4 sandbox_bundle:160:455
(anonymous) @ VM4 sandbox_bundle:93

```

### Additional Information

My application at https://github.com/oracle/weblogic-toolkit-ui has been working fine since Electron 12.x and we have incrementally upgraded to new Electron versions and are currently on 19.0.13 and the application works fine.  When I upgrade to Electorn 20.0.3, the application fails to start up properly due to failing to load our preload script.

**Comment by Prinzhorn** [comment]
Did you check the release notes for breaking changes? https://github.com/electron/electron/releases/tag/v20.0.0
This sounds a lot like

> Renderers are now sandboxed by default unless nodeIntegration: true or sandbox: false is specified

https://www.electronjs.org/docs/latest/tutorial/sandbox#preload-scripts

**Comment by robertpatrick** [comment]
@Prinzhorn No, I hadn't checked that but I thought we were following best practices already so I don't understand the purpose of this change.  What is the difference between `sandbox` and `contextIsolation`?

```
  let newWindow = new BrowserWindow({
    x,
    y,
    show: false,
    width: width,
    height: height,
    'webPreferences': {
      nodeIntegration: false,
      contextIsolation: true,
      enableRemoteModule: false,
      webviewTag: false,
      additionalArguments: _getAdditionalArguments(),
      preload: path.join(__dirname, 'ipcRendererPreload.js')
    }
  });
```

**Comment by Prinzhorn** [comment]
I cannot word it any better than the docs, these are two different security concepts.

https://www.electronjs.org/docs/latest/tutorial/security#3-enable-context-isolation
https://www.electronjs.org/docs/latest/tutorial/security#4-enable-process-sandboxing

https://www.electronjs.org/docs/latest/tutorial/context-isolation
https://www.electronjs.org/docs/latest/tutorial/sandbox
