### ISSUE TITLE
[Bug]: Website documents can not be displayed in Chinese

### ISSUE THREAD

**Issue by ksBking** [electron/electron#35380]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 LTSC 2021

### What arch are you using?

x64

### Expected Behavior

Website documents can be displayed in Chinese

### Actual Behavior

There is no Chinese in the website documents, and all the documents are displayed in English after switching to Chinese. There was still Chinese in the short time before

### Additional Information

![image](https://user-images.githubusercontent.com/54195058/185490720-bf9985ce-c189-4102-877d-f471533458ed.png)

**Comment by codebytere** [comment]
This is an issue that should be opened on https://github.com/electron/electronjs.org-new
