### ISSUE TITLE
[Bug]: Electron. 20 X Linux version does not support h265 hardware decoding

### ISSUE THREAD

**Issue by lishulincug** [electron/electron#35392]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu20

### What arch are you using?

x64

### Last Known Working Electron version

no

### Expected Behavior

Electron. 20 X Linux version support h265 hardware decoding

### Actual Behavior

![image](https://user-images.githubusercontent.com/13003282/185731960-f10e2876-de05-4bcd-9c5e-5dac0516be17.png)
No display h265 video frame images

**Comment by lishulincug** [comment]
![image](https://user-images.githubusercontent.com/13003282/185733690-46348268-8858-4e02-ad9d-204f20a93cab.png)
![image](https://user-images.githubusercontent.com/13003282/185733716-cf16cced-6f87-480b-861e-23cd82a9b57d.png)
Decoding in the Windows system is normal, but Linux report the error.

**Comment by Prinzhorn** [comment]
Does it work in Chromium? I assume on Windows you installed support on an OS level as from what I can tell this shouldn't work at all.

https://caniuse.com/?search=h265
https://bugs.chromium.org/p/chromium/issues/detail?id=684382

**Comment by lishulincug** [comment]
> 它在 Chromium 中有效吗？我假设您在 Windows 上安装了操作系统级别的支持，据我所知，这根本不应该工作。
> 
> [https://caniuse.com/?search=h265 ](https://caniuse.com/?search=h265) https://bugs.chromium.org/p/chromium/issues/detail?id=684382

The new Chromium Development version is supported in windows，linux version without verification。

**Comment by greggman** [comment]
I didn't test on Linux but I did test on MacOS

> Node.js 16.17.1, Chromium 108.0.5329.0, and Electron 23.0.0-nightly.20221007.

Works

> Node.js 16.16.0, Chromium 106.0.5249.91, and Electron 21.1.0.

Does not.  

So maybe try a newer version?

**Comment by SouthernPL** [comment]
> > 它在 Chromium 中有效吗？我假设您在 Windows 上安装了操作系统级别的支持，据我所知，这根本不应该工作。
> > [https://caniuse.com/?search=h265 ](https://caniuse.com/?search=h265) https://bugs.chromium.org/p/chromium/issues/detail?id=684382
> 
> The new Chromium Development version is supported in windows，linux version without verification。

请问在electron.js 中实现播放h265成功了吗？我也在寻找electron.js硬解码 H265的解决办法

**Comment by beyondkmp** [comment]
@SouthernPL  You can eable H265 decode by the following command in Electron 20.
```
app.commandLine.appendSwitch('enable-features', 'PlatformHEVCDecoderSupport')
```

**Comment by FireMapleLeaves** [comment]
> @SouthernPL You can eable H265 decode by the following command in Electron 20.
> 
> ```
> app.commandLine.appendSwitch('enable-features', 'PlatformHEVCDecoderSupport')
> ```
Is this gonna work?
