### ISSUE TITLE
[Bug]: Electron 18.3.9 can't read flags from electron18-flags.conf file

### ISSUE THREAD

**Issue by bacteriostat** [electron/electron#35398]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.9

### What operating system are you using?

Other Linux

### Operating System Version

(ArchLinux) Linux 5.19.2-arch1-1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

18.3.6

### Expected Behavior

Electron should read flags from electron18-flags.conf

### Actual Behavior

Electron does not read flags from electron18-flags.conf. This error is shown when running vscode from terminal:

![image](https://user-images.githubusercontent.com/32611672/185850357-7afb40a5-8cf3-4289-b601-00e46b3217c5.png)

This happens with any flags in the file.

**Comment by jplatte** [comment]
I'm pretty sure the `electron[N]-flags.conf` files are specific to the Arch Linux packages. It might still be an upstream bug, but it should probably be reported at https://bugs.archlinux.org/ first.

**Comment by bacteriostat** [comment]
Sure, thanks. I will report it there.

**Comment by jplatte** [comment]
This has been confirmed to be specific to the arch linux package / VSCode (see comments on the linked bug report). There is no Electron bug here.

**Comment by bacteriostat** [comment]
Yes, I guess we can close this issue?
