### ISSUE TITLE
[Feature Request]: Enable drag & drop events api

### ISSUE THREAD

**Issue by ArnonAsquira** [electron/electron#35404]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, ```contents.sendInputEvent``` only supports 3 types of events: 
* mouse events
* mouse wheel events
* keyboard events 
But it is not possible to trigger drag & drop events using this interface.

Would it possible to enable it in any way?

### Proposed Solution

I would admit that I don't fully understand the complexity of this issue, however I do know that in some automation platforms like Selenium there is such functionality.

### Alternatives Considered

Using mouse events to trigger drag events like so:
1.mouse down 
2. mouse move
3. mouse up
This unfortunately did not work as I hoped(didn't trigger drag events).

### Additional Information

I tested it on ubuntu 18 and Mac os X with electron 17 - 20.

**Comment by codebytere** [comment]
We only support `WebInputEvent` types found in Blink, of which drag and drop is [not one](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/common/input/web_input_event.h;l=187-209;drc=8f20fb0fd2ed4ccb7dd703557c34c3afd798f49b;bpv=0;bpt=1). Should that change, we'd be happy to reconsider!
