### ISSUE TITLE
[Bug]: macOS - Using frame, roundedCorners, and fullscreen settings together automatically causes a crash

### ISSUE THREAD

**Issue by sircharlo** [electron/electron#35403]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3

### What operating system are you using?

macOS

### Operating System Version

Catalina (confirmed on Big Sur too)

### What arch are you using?

x64

### Last Known Working Electron version

Not working in version 17-21

### Expected Behavior

Code such as the following should not crash Electron:

```
  win = new BrowserWindow({
    title: "Media Window",
    frame: false,          // These 3 options can't be
    roundedCorners: false, // used concurrently on macOS 
    fullscreen: true       // without causing a crash
  });
```

### Actual Behavior

The following code crashes Electron on macOS:

```
  win = new BrowserWindow({
    title: "Media Window",
    frame: false,          // These 3 options can't be
    roundedCorners: false, // used concurrently on macOS 
    fullscreen: true       // without causing a crash
  });
```
Any of the following 3 variants does **not** cause the crash:
```
  win = new BrowserWindow({
    title: "Media Window",
    // frame: false,
    roundedCorners: false,
    fullscreen: true
  });
```

```
  win = new BrowserWindow({
    title: "Media Window",
    frame: false,
    // roundedCorners: false,
    fullscreen: true
  });
```

```
  win = new BrowserWindow({
    title: "Media Window",
    frame: false,
    roundedCorners: false,
    // fullscreen: true
  });
```

### Testcase Gist URL

https://gist.github.com/sircharlo/c78e81a20c3eb4167037197b3803d76e

### Additional Information

Error looks like this: 

    Electron[785:12045] *** Assertion failure in -[ElectronNSWindow titlebarAccessoryViewControllers], /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1894.60.100/AppKit.subproj/NSWindow.m:3337

**Comment by rafael-anachoreta** [comment]
This issue still happens when toggling full screen on mac (fn+F).

> 2023-08-29 13:34:52.745 Electron[53708:766850] -[NativeWidgetMacNSWindowBorderlessFrame _surrenderToolbarViewForFullScreenWindow]: unrecognized selector sent to instance 0x7f90919b5770
/electron-bug-2/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGILL
error Command failed with exit code 1.

I was able to reproduce it using the exact gist from the original report and bumping electron to latest (v26.1.0).

https://github.com/electron/electron/assets/10238432/7df7c11c-3743-4399-b7f4-27c1198bbf53

Any chance this can be addressed on electron's side? Please advise if I should open a new issue for this behavior 🙏

**Comment by codebytere** [comment]
@sircharlo hey yes - i thought i got it but it looks like chromium added something that also trips this crash - the trace is subtly different now as you noted above:

> -[NativeWidgetMacNSWindowBorderlessFrame _surrenderToolbarViewForFullScreenWindow]: unrecognized selector sent to instance 0x7f90919b5770
