### ISSUE TITLE
[Bug]: Problems with webview new-window event

### ISSUE THREAD

**Issue by toschlog** [electron/electron#35417]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home 19042.1826

### What arch are you using?

x64

### Expected Behavior

When the page displayed in a webview attempts to open a new tab, I would expect to get the new-window event and be able to open a new webview myself.

### Actual Behavior

I do not get the new-window event when the web page attempts to open the new tab.  However, if I specify `allowpopups='true'` on my webview, I do get the event.  But in this case Electron opens a new BrowserWindow and there's apparently nothing I can do to stop it.

**Comment by Kilian** [comment]
The new-window event is deprecated. You can use [contents.setWindowOpenHandler(handler)](https://www.electronjs.org/docs/latest/api/web-contents#contentssetwindowopenhandlerhandler) instead which gives you more control over the handling.

**Comment by yurnery** [comment]
@Kilian this api is not for webview tag

**Comment by codebytere** [comment]
That doesn't matter - the event is still deprecated and going away. You should, as kilian said, use `contents.setWindowOpenHandler(handler)`. It's perfectly possible to get the id of the webcontents associated with the webview, which you can then use to get the webcontents itself, and then call `setWindowOpenHandler`

**Comment by toschlog** [comment]
If I use  `setWindowOpenHandler()` I do get notified, but the callback doesn't work as documented.  I've set up my handler like this:

```
    webContents.setWindowOpenHandler(evt => {
        return {action: 'allow'}
    })
```

As I understand it, this should allow the window to open.  But it doesn't.  I don't get the pop-up window, and the link opens in the existing `<webview>`.

**Comment by toschlog** [comment]
> @toschlog How to access webContents? Is it a webview property?

Like this:
```
    let remote = window.require('@electron/remote')
    let webContents = remote.webContents.fromId(webview.getWebContentsId())
```

**Comment by yurnery** [comment]
Thanks

**Comment by toschlog** [comment]
@Kilian @codebytere Anything on `setWindowOpenHandler()` not working correctly?  Should I create a new ticket?  Or can we reopen this one?

**Comment by miniak** [comment]
FYI the `new-window` event was removed in #34526
