### ISSUE TITLE
[Bug]: setIgnoreMouseEvents on Windows / Flickering Cursor

### ISSUE THREAD

**Issue by wapgear** [electron/electron#35414]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18, 19, 20

### What operating system are you using?

Windows

### Operating System Version

Windows 11, Windows 10

### What arch are you using?

x64 / ARM

### Expected Behavior

When you move the cursor, it should show the one described in CSS (`cursor: pointer` for example)

### Actual Behavior

When you move the cursor, it flickers between `cursor: default` to `cursor: described-in-css`

https://user-images.githubusercontent.com/2028200/186089174-b0634f9d-6f8c-4d6d-b436-631486a37440.mov

### Testcase Gist URL

https://github.com/wapgear/demo-for-electron

### Additional Information

I made a simple demo using the electron-quick-start repo, which is making two simple things:

1. creating two windows
2. one of them is using `alwaysOnTop` and `setIgnoreMouseEvents: true/ forward: true`

**Comment by Akenndy** [comment]
E

**Comment by wapgear** [comment]
👀

**Comment by DanielMcAssey** [comment]
Any updates to this issue?

**Comment by wapgear** [comment]
@DanielMcAssey nope. Also waiting for it

**Comment by wapgear** [comment]
Any ETA for this one?

**Comment by wapgear** [comment]
👀

**Comment by hedeshy** [comment]
Hiii :)
Pump! Pump!

**Comment by fempyrean** [comment]
Hello! Any updates on this? I'm also having this issue.

**Comment by ScarboroughCoral** [comment]
Hello! Any updates on this?

**Comment by Galkon** [comment]
Bump

**Comment by Galkon** [comment]
Still exists on latest 34

**Comment by YasinSefa15** [comment]
Still exists

**Comment by Eneris** [comment]
Still exists on 40, 41, 42, 43

**Comment by wapgear** [comment]
Opened a proposed fix in #54201.

The behavior still reproduces with the original demo on Electron 44.4.3 and Windows 11 ARM64 in Parallels. A native `GetCursorInfo` trace captured 26 hand-to-arrow-to-hand pulses while repositioning and clicking within the POINTER region with forwarding enabled, versus none with forwarding disabled. Forwarded DOM mouse events were also observed.

The fix suppresses cursor shape updates from the click-through window while preserving forwarded mouse events and cursor-client bookkeeping. It includes three Chromium regression tests.

The PR is a draft: formatting, lint, patch export, and patch application checks passed, but Windows compilation, execution of the new tests, and validation with a patched binary are still pending.
