### ISSUE TITLE
[Bug]: When downloading a file using the video tag, an extra character dot appears when saving the file!

### ISSUE THREAD

**Issue by liulinboyi** [electron/electron#35429]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

19.0.6

## When downloading a file using the video tag, an extra character dot appears when saving the file! It has two character dot  in the file type.

![image](https://user-images.githubusercontent.com/41336612/186472381-b42fe64d-6631-4def-88bd-48d10591cbd4.png)

![image](https://user-images.githubusercontent.com/41336612/186471193-e2558aaf-4e7c-4a51-8fca-e3db0f9731df.png)

### Testcase Gist URL

https://gist.github.com/liulinboyi/2e687fbf07f0d9c836933817046ea043

### I have a feeling that this bug exists from version 20.

**Comment by codebytere** [comment]
@mlaurencin maybe related to the save file changes 🤔

**Comment by qubicle** [comment]
This bug also exists in Electron 19.0.14

**Comment by zcbenz** [comment]
It seems to be related to https://github.com/electron/electron/pull/34723. /cc @mlaurencin

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/35618

**Comment by alienzhangyw** [comment]
> Closed in #35618

@codebytere This fix was not merged into v21, the bug still exists in v21.1.1

**Comment by mlaurencin** [comment]
@alienzhangyw Thank you for the notice. The fix should be in place once [this PR](https://github.com/electron/electron/pull/36027) is merged.
