### ISSUE TITLE
[Feature Request]: Add Window Object Property to Webviews

### ISSUE THREAD

**Issue by CodeLikeCrazE** [electron/electron#35436]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Basically, I’m making my own Electron-based browser (I know, original), and I want to expose custom API’s to the website, and to do that I need to somehow access the window object of a webview. You can find the frame and get the window object that way, but then there is CORS limitations that make life a pain.

### Proposed Solution

I would like to request a property on webviews, which

- Easily exposes the window object
- Exposes it **without cors limitations**

### Alternatives Considered

I’ve considered trying to use the eval system, but I really don’t want to, as it makes the code a lot more messy, this feature would allow for clean and simple code.

**Comment by MarshallOfSound** [comment]
This is not technically possible as webviews are considered as cross origin frames in most cases and thus reside in separate processes to the host frame.
