### ISSUE TITLE
[Bug]: 18.3.x changelogs are not generating

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#35433]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

N/A

### What operating system are you using?

Other (specify below)

### Operating System Version

N/A

### What arch are you using?

Other (specify below)

### Expected Behavior

Changesets for versions 18.3.7 through 18.3.9 are available at https://www.electronjs.org/releases/stable?version=18

### Actual Behavior

Missing changesets

**Comment by codebytere** [comment]
@Slapbox please open this issue on https://github.com/electron/electronjs.org-new
