### ISSUE TITLE
[Bug]: Command-Tab broken when apps are in full-screen mode

### ISSUE THREAD

**Issue by kerim** [electron/electron#35440]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

macOS

### Operating System Version

MacOS 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

???

### Expected Behavior

When I'm in another app and I hit "command-tab" and select an electron based app, it should bring that app to the front. However, this is broken for all my electron apps - when those apps are in full screen mode. (In macOS parlance, that locks them to a separate "space" or "desktop.") I believe this is true of Logseq, Upnext, 1Password, Discord, Evernote, etc. but I have reproduced it most often in Logseq, Upnext, and Discord. 

### Actual Behavior

Instead of bringing the electron app to the front, command-tab switches to the Finder. I have to command-tab to the app a second time to then properly switch to the correct space or desktop.

### Additional Information

Sorry, I'm not a developer, just a very frustrated user as more and more of my apps are failing to support this basic macOS behavior now that they have adopted Electron.

**Comment by zcbenz** [comment]
Does the same problem happen when switching focus to Chrome browser?

I'm unable to reproduce it on my machine so I wonder if it only happens for very few users.

**Comment by kerim** [comment]
I don't use Chrome, so I can't say for sure. I have not noticed it in Brave, but I mostly use Safari or Firefox these days.

It doesn't happen if you were just using an app and command-tab right back to it. It only happens if you have been using other apps for a while and the target app is in the background. In that case (if all the apps are in full screen mode) it will switch to the finder instead of the app. If you then command-tab again it will open the target app and command-tab between the two apps will work again for a short while.
