### ISSUE TITLE
[Bug]: ERROR:filesystem_win.cc(130)] GetFileAttributes {AppData}\Crashpad\attachments\a9941f5f-b7ff-41cd-a5f2-82ecbdf5effe: The system cannot find the file specified. (0x2)

### ISSUE THREAD

**Issue by oalfroukh** [electron/electron#35448]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.14

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19041

### What arch are you using?

ia32

### Last Known Working Electron version

16.x

### Expected Behavior

The main process should not contain errors after restarting the crashed app.

### Actual Behavior

The main process contains errors after restarting the crashed app.

### Additional Information

Our app is running in the development mode on the VCode after crashing with oom reason, I restarted the app, and the main process become has these errors:

```C
[45268:0825/103503.810:ERROR:filesystem_win.cc(130)] GetFileAttributes {AppData}\Crashpad\attachments\a9941f5f-b7ff-41cd-a5f2-82ecbdf5effe: The system cannot find the file specified. (0x2)
[45268:0825/103503.812:ERROR:filesystem_win.cc(130)] GetFileAttributes {AppData}\Crashpad\attachments\a9941f5f-b7ff-41cd-a5f2-82ecbdf5effe: The system cannot find the file specified. (0x2)
[45268:0825/103503.813:ERROR:filesystem_win.cc(130)] GetFileAttributes {AppData}\Crashpad\attachments\a9941f5f-b7ff-41cd-a5f2-82ecbdf5effe: The system cannot find the file specified. (0x2)
[45268:0825/103503.814:ERROR:filesystem_win.cc(130)] GetFileAttributes {AppData}\Crashpad\attachments\a9941f5f-b7ff-41cd-a5f2-82ecbdf5effe: The system cannot find the file specified. (0x2)
```

If I removed `crashReporter.start` the error will disappear, I can not create a simple repo because I can not reproduce the oom crash on it, I tried to use `process.abort()` method to generate a crash but there are no generated dmp files for this error

```js
crashReporter.start({
      productName: "project",
      submitURL: "getCrashSubmitUrl()",
      ignoreSystemCrashHandler: true,
      uploadToServer: true,
      compress: true,
      globalExtra: {
        "sentry[release]": "1.100.0",}
    });
```.

For `a9941f5f-b7ff-41cd-a5f2-82ecbdf5effe.dmp` file it is exist on `{appdata}\Crashpad\reports` path, but not on `{appdata}\Crashpad\attachments`, also If I removed `{appdata}\Crashpad` folder the errors will disappear!

FYI, the report has been uploaded to Sentry successfully!

**Comment by zcbenz** [comment]
A google search of "chromium filesystem_win.cc GetFileAttributes" shows the same error for lots of other Chromium based software like nw.js and opera, so this is not an issue of Electron and I'm closing this issue.
