### ISSUE TITLE
[Bug]: Failed to read the 'localStorage' from preload script

### ISSUE THREAD

**Issue by dortonway** [electron/electron#35458]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

20.04.3 LTS

### What arch are you using?

x64

### Expected Behavior

Be able to read localStorage from preload script

### Actual Behavior

Sometimes, but not always, electron.js preload script can't read localStorage
![image](https://user-images.githubusercontent.com/1077750/186686409-aaf0c822-c179-4eae-9949-57aa1f8efbd5.png)

So the app just doesn't work because of that.

### Additional Information

webPreferences: {
      additionalArguments: ['--c:' + args_raw],
      webSecurity: false,
      allowRunningInsecureContent: true,
      contextIsolation: false,
      //offscreen: false,
    },

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
