### ISSUE TITLE
[Feature Request]: webview tag add header prop

### ISSUE THREAD

**Issue by yurnery** [electron/electron#35450]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

webview can only add  extraHeader by `loadUrl` method, but this method can only be called after `dom-ready` event.
if I don't set the src to the webview first, because I want to load the page with my custom header, now I want to use `loadUrl` method, but now the `dom-ready` event will never call, so I can't call call `loadUrl` method

### Proposed Solution

 the webview should have a extraHeader props to pass custom header

### Alternatives Considered

 the webview should have a extraHeader props to pass custom header

**Comment by zcbenz** [comment]
You can also set extra headers with the `webRequest` API.
