### ISSUE TITLE
[Bug]: Segfault when calling `screen.getCursorScreenPoint()` under Wayland

### ISSUE THREAD

**Issue by weedz** [electron/electron#35471]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v20.0.3 and v22.0.0-nightly.20220824

### What operating system are you using?

Other Linux, and Sway WM (1.7)

### Operating System Version

ArchLinux, kernel 5.19.3

### What arch are you using?

x64

### Expected Behavior

Should provide a Point to the cursor position and not segfault.

### Actual Behavior

Get a segmentation fault when calling `screen.getCursorScreenPoint();` under Wayland (sway 1.7).

### Testcase Gist URL

https://gist.github.com/weedz/b8002775cd1a23c46d38b5f10de957e4

### Additional Information

Works fine under Xwayland. But will crash when launched with `--ozone-platform-hint=wayland`.

Tested every version down to electron@16 (with `--enable-features=UseOzonePlatform --ozone-platform=wayland`:
- Electron@16: "interface 'wl_output' has no event 4" and no window or other errors.
- Electron v17-v22.0.0-nightly.20220824: "electron exited with signal SIGSEGV"

**Comment by codebytere** [comment]
Stacktrace:

```
[234843:0830/095759.149722:FATAL:wayland_screen.cc(316)] Check failed: window. 
#0 0x5610289fce72 base::debug::CollectStackTrace()
#1 0x561028900803 base::debug::StackTrace::StackTrace()
#2 0x561028919866 logging::LogMessage::~LogMessage()
#3 0x56102891a2fe logging::LogMessage::~LogMessage()
#4 0x561024e0f976 ui::WaylandScreen::GetCursorScreenPoint()
#5 0x5610240dc9de gin::internal::Invoker<>::DispatchToCallback<>()
#6 0x5610240dc7f7 gin::internal::Dispatcher<>::DispatchToCallbackImpl()
#7 0x5610240dc6d9 gin::internal::Dispatcher<>::DispatchToCallback()
#8 0x561025b342af v8::internal::FunctionCallbackArguments::Call()
#9 0x561025b32b3c v8::internal::(anonymous namespace)::HandleApiCallHelper<>()
#10 0x561025b30b04 v8::internal::Builtin_Impl_HandleApiCall()
#11 0x561025b30399 v8::internal::Builtin_HandleApiCall()
#12 0x560fbfee66b8 <unknown>
Crash keys:
  "io_scheduler_async_stack" = "0x561025A1B6CB 0x5610275D2781"
  "platform" = "linux"
  "process_type" = "browser"
pci id for fd 119: 1ab8:0010, driver (null)
[234891:0100/000000.223106:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is egl, ANGLE is 
[234891:0100/000000.414652:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by codebytere** [comment]
Turns out this is an issue with init order - if you call `screen.getCursorScreenPoint` _after_ creating the BrowserWindow it works just fine.

**Comment by GarboMuffin** [comment]
I can still reproduce this on Electron 29.1.1, KDE Plasma 6, Wayland, Arch Linux with:

```js
const {app, screen} = require('electron');

app.whenReady().then(() => {
  const xy = screen.getCursorScreenPoint();
  console.log(xy);
  app.quit();
});
```

gdb gives me this backtrace:

```
#0  ui::WaylandWindow::GetBoundsInDIP (this=0x0) at ../../ui/ozone/platform/wayland/host/wayland_window.cc:429
#1  0x0000555558491b92 in ui::WaylandScreen::GetCursorScreenPoint (this=0x4c00017dfe0) at ../../ui/ozone/platform/wayland/host/wayland_screen.cc:400
#2  0x00005555579745fd in base::RepeatingCallback<gfx::Point (electron::api::Screen*, v8::Isolate*)>::Run(electron::api::Screen*, v8::Isolate*) const & (
    this=0x7fffffffd030, args=0x4c0002f8000, args=0x4c0002f8000) at ../../base/functional/callback.h:344
#3  gin::internal::Invoker<std::__Cr::integer_sequence<unsigned long, 0ul, 1ul>, electron::api::Screen*, v8::Isolate*>::DispatchToCallback<gfx::Point>(base::RepeatingCallback<gfx::Point (electron::api::Screen*, v8::Isolate*)>) (callback=..., this=<optimized out>) at ../../gin/function_template.h:225
#4  gin::internal::Dispatcher<gfx::Point (electron::api::Screen*, v8::Isolate*)>::DispatchToCallbackImpl(gin::Arguments*) (args=0x7fffffffd080)
    at ../../gin/function_template.h:264
#5  0x0000555557974488 in gin::internal::Dispatcher<gfx::Point (electron::api::Screen*, v8::Isolate*)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) (info=...) at ../../gin/function_template.h:270
#6  0x000055555754a207 in Builtins_CallApiCallbackGeneric ()
#7  0x00007fffffffd110 in ?? ()
#8  0x00007fffffffd148 in ?? ()
#9  0x0000000000000000 in ?? ()
```

**Comment by codebytere** [comment]
exciting - @GarboMuffin yes please thatd be helpful!
