### ISSUE TITLE
[Bug]: Debugger not hit/paused in DevTools when using CDP and dynamically creating IFrame element

### ISSUE THREAD

**Issue by pmadhur** [electron/electron#35478]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro, Version: 21H2, Build: 22000.856

### What arch are you using?

x64

### Expected Behavior

Debugger should be hit/paused in DevTools even when using webContents.debugger.attach() and creating iframe element on the fly.

### Actual Behavior

Debugger not hit/paused in DevTools.

### Testcase Gist URL

https://gist.github.com/46ecbbc25cef72196f06fbc852ab397a

### Additional Information

After running the test case gist in Electron Fiddle, click the "Create IFrame" button. You would observe that debugger is not hit/paused in DevTools. Now comment line 19 in main.js, run the test case again, click the "Create IFrame" button, you would observe that the debugger is hit/paused in DevTools.

**Comment by pmadhur** [comment]
Seems to be similar to #34938, not sure if it exactly the same problem. My problem is with Debugger domain, and #34938 seems to be with Page domain.

**Comment by pmadhur** [comment]
I tested the same with Chrome using chrome-remote-interface. Chrome works as expected. Here the same test case (Chrome Version: 104.0.5112.102, Node Version: 16.15.0) with Chrome:

Create a test directory, c:\test, open command prompt in this directory and execute:

`npm install chrome-remote-interface`

Create file, c:\test\test.js with following contents:

```
const CDP = require('chrome-remote-interface');

async function start() {
    let client;
    try {
        client = await CDP();
        const {Debugger, Page} = client;
        Debugger.on('paused', () => {
            console.log('debugger paused!');
        });
        Debugger.on('resumed', () => {
            console.log('debugger resumed!');
        });

        await Debugger.enable();
        await Page.enable();
        await Page.navigate({url: 'file:///c:/test/test.html'});
    } catch (err) {
        console.error(err);
    }
}

start();
```

Create file c:\test\test.html with following contents:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
</head>
<body>
    <button id="btnCreate">Create IFrame</button>
    <script>
        const btnCreate = document.getElementById('btnCreate');
        btnCreate.addEventListener('click', () => {
            const iframeEl = document.createElement('iframe');
            iframeEl.style.width = '500px';
            iframeEl.style.height = '500px';
            document.body.appendChild(iframeEl);
            debugger;
        });
    </script>
</body>
</html>
```

Start Chrome with following arguments:

`chrome.exe --remote-debugging-port=9222 --user-data-dir=c:/test/remote-profile`

Open DevTools in Chrome, open command prompt and navigate to c:\test and execute:

`node test.js`

In Chrome, click the "Create IFrame" button, you would observe that the debugger is hit/paused, and in the console you see the CDP events are also triggered.

So, it seems to be a problem with Electron.

**Comment by pmadhur** [comment]
Closing as there are other issues (#34260 and #34938) which have the same problem with iframe. I could do a workaround by remotely attaching debugger via Chrome DevTools Protocol.

**Comment by MrHuangJser** [comment]
i have same issue, but i passed the probrolem with another way. here is the simple code
```typescript
// create a invisible BrowserWindow
const debuggerWin = new BrowserWindow();
const proxyDebugger = debuggerWin.webContents.debugger;
proxyDebugger.attach();
// use debuggerWin to proxy all webContents events and commands
proxyDebugger.sendCommand("Target.setDiscoverTargets", { discover: true });
let targetContentsId: string;
proxyDebugger.on("message", (...[method, params]) => {
  if (method === "Target.targetCreated") {
    const {
      targetInfo: { targetId },
    } = params;
    targetContentsId = targetId
    proxyDebugger.sendCommand("Target.attachToTarget", { targetId, flatten: true })
      .then(({ sessionId }) => {
        // then you can send any command to the target or listen messages from target
        // eg: proxyDebugger.sendCommand("Emulation.setTouchEmulationEnabled", { enabled: true }, sessionId);
      });
  }

  // listen messages from target
  if (method === 'Target.receivedMessageFromTarget') {
    if (targetContentsId === params.targetId) {
      // do something
    }
  }
})
```
