### ISSUE TITLE
[Bug]: BrowserView.fromId(myid) api doesn't work

### ISSUE THREAD

**Issue by promversioning** [electron/electron#35475]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

var mynewbrowserview = BrowserView.fromId(myid) ;

### Actual Behavior

Console error:
"TypeError: BrowserView.fromId is not a function"

### Additional Information

Does not seems to exist (and no references can be found in the documentation) to the code implemented 5 years ago ( [Fixed by #10039](https://github.com/electron/electron/issues/10039) )

**Comment by Prinzhorn** [comment]
BrowserView's don't have an `id` since https://github.com/electron/electron/pull/23578 released in 11.0.0 https://github.com/electron/electron/releases/tag/v11.0.0

**Comment by ckerr** [comment]
These APIs were marked as experimental and aren't supported, so I'm going to close this issue.
