### ISSUE TITLE
[Bug]: Mac OS Panel window hide brings up other window in background up

### ISSUE THREAD

**Issue by castroCrea** [electron/electron#35483]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.0

### What operating system are you using?

macOS

### Operating System Version

Mac Os Montery 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

On electron with multiple windows, when I hide a window, other window doesn't come up on top of all others but stays where they are

### Actual Behavior

https://user-images.githubusercontent.com/20707343/187165996-cc3291d5-6c87-4741-b403-caf844f159b7.mov

So I create 2 windows and add a global shortcut to hide one. when I hide one the second one show up

### Testcase Gist URL

https://gist.github.com/castroCrea/f7d38ae1601465d088b3f5a63c104894

**Comment by codebytere** [comment]
@castroCrea this doesn't appear to be specific to panel windows - this also happens for me when i remove that option. Can you confirm?

**Comment by castroCrea** [comment]
@codebytere thx for your answer.

Yes, I confirm it also happened on regulars window

**Comment by zcbenz** [comment]
I don't think this is a bug, for example when using a screen recorder, after clicking the record button you would expect the main window to hide while everything else keep untouched.

**Comment by castroCrea** [comment]
I’m agree with you for the use case of screen record window but for app with real multiple window that have interactive content or, at least, for panel window type is not what is expected at all.

**Comment by zcbenz** [comment]
For some multiple windows apps it is expected to move focus to other windows after closing a panel window, but the question is which one to focus. For example the following case:

![multi-window](https://user-images.githubusercontent.com/639601/187679148-9d3bddc1-bdba-4c1b-a120-999eb6998a05.png)

It has 3 main windows and 2 toolbox windows, after hiding/closing a toolbox window, which window should have the focus then? It is impossible for Electron to know. If we have some kind of default behavior then it is very likely to go against user's wish.

**Comment by castroCrea** [comment]
Ok, I agree with you about the regular window (multiple NSWindow). 
So let's focus on NSpanel window behavior (BrowserWindow type `panel`) for Mac OS X.

On Gimp, those windows are not panel windows, they don't move over all the workspace, ... They don't have the same behavior as the Mac OS X spotlight for example.

Now, I will take the example of Raycast App, which uses a Mac OS X NSPanel window for its spotlight (Cf screenshot below).

Here there is a configuration window that is an NSWindow and a spotlight window that is a NSpanel Window.
So in the video below, you can see that when we close the NSPanel the NSWindow stay at the back.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/20707343/187687154-67db8e61-ce8f-4265-9606-155b9dbc50ce.png">

https://user-images.githubusercontent.com/20707343/187687197-e9b49020-8e0c-4c74-a178-b8ec5d738c3a.mov

**Comment by zcbenz** [comment]
Thanks for the example, yeah that makes sense.

**Comment by promise94** [comment]
Is there a solution? I have the same problem

**Comment by castroCrea** [comment]
nop is still there in the todo list https://github.com/orgs/electron/projects/51/views/1 👍

**Comment by castroCrea** [comment]
I can work on it, do you have an hint for me, where I can start look for? :pray

**Comment by promise94** [comment]
My problem is solved. using the solution here https://github.com/electron/electron/issues/35815#issuecomment-1341488760

**Comment by MeGaoning** [comment]
electron I'm making a tray window，Have the same problemThe temporary solution is to set setFocusable (false) in the main window before the tray window executes the "hide" method, and set setFocusable (true) after execution

**Comment by MeGaoning** [comment]
I'm making a tray window， Have the same problem；
The temporary solution is to set **setFocusable(false)**  in the main window before the tray window executes the **"win.hide()"** method, and set **setFocusable(true)** after execution
` mainWindow.setFocusable(false)
trayWindow.hide()
mainWindow.setFocusable(true)`

**Comment by MeGaoning** [comment]
I'm making a tray window， Have the same problem；
The temporary solution is to set **setFocusable(false)** in the main window before the tray window executes the "**win.hide()**" method, and set **setFocusable(true)** after execution
` mainWindow.setFocusable(false) 
trayWindow.hide() 
mainWindow.setFocusable(true)`

**Comment by ufukomer** [comment]
bump

**Comment by ufukomer** [comment]
Hi this is still happening. Have you solved this @castroCrea
