### ISSUE TITLE
[Bug]: Spellcheck API can cause errors in macOS applications despite supposedly being a "no-op" on macOS

### ISSUE THREAD

**Issue by df-asana** [electron/electron#35508]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.10

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The `setSpellCheckerLanguages` method should have no effect when invoked on macOS, other than possibly generating a warning that this API is not supported on macOS.

### Actual Behavior

On macOS, invoking `ses.setSpellCheckerLanguages` with a language array containing one or more unsupported languages causes an error which can prevent the app from rendering. ("Unsupported languages" here means languages not supported by the Electron spellcheck API, which is not actually used on macOS.)

This issue is further complicated by the fact that the `ses.getSpellCheckerLanguages` method returns the actual locale(s) that the macOS spellcheck API is checking against, regardless of whether the Electron spellcheck API supports those locales.

As such, even something as seemingly innocuous as setting the spellcheck languages to the current spellcheck languages, which should be a no-op on any platform, can cause errors on macOS.

### Testcase Gist URL

https://gist.github.com/71ad54ff04a1a5b8f1a3ceed905683a0

### Additional Information

The [Electron docs](https://www.electronjs.org/docs/latest/api/session#sessetspellcheckerlanguageslanguages) state the following:
> Note: On macOS the OS spellchecker is used and will detect your language automatically. This API is a no-op on macOS.

This issue can only be reproduced on a macOS device where the current system locale is one that the Electron spellcheck API does not support.  For English-speaking users, you can accomplish this by setting your region to "India" in the "Language & Region" settings menu.

**Comment by vladimiry** [comment]
As far as I remember, setting the unsupported language will trigger the error on Linux system too, so likely on any system. So I just reduce the languages by `session.availableSpellCheckerLanguages` before calling the `session.setSpellCheckerLanguages`.
