### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by AndreiSoroka** [electron/electron#35506]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Question: What version of the Electron will support node.js 18.x.x?

`node.js 18.x.x` support native `fetch`. Because we can't use `import/export`, we can use only `node-fetch@2.x.x` and can't use node-fetch@3.x.x

But `node@18.x.x` support native `fetch`

### Proposed Solution

create release with `node@18.x.x`

### Alternatives Considered

not found alternatives

**Comment by codebytere** [comment]
We plan to integrate Node.js 18.x once it goes LTS - it is a part of our existing upgrades roadmap!

**Comment by AndreiSoroka** [comment]
Hello! After the answer, the discussion was closed. And I couldn't answer. But now the discussion has been opened, and I feel less deprived.

So, I have two questions:
- If we knew that LTS would be coming soon, why couldn't we start connecting node 18 earlier?
- Now node 18 is LTS, so where can I find any info on when will node18 be released?

Kind regards

FYI: @codebytere 

P.s. I wanna reopen this issue because prev answer is not actual today
