### ISSUE TITLE
[Bug]: electron should not set a default menu

### ISSUE THREAD

**Issue by bpasero** [electron/electron#35512]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.x

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

An application should be in full control of the menu and thus the following code is taking startup CPU cycles when not needed:

https://github.com/electron/electron/blob/bfced8cbfe6bad6d119ea9276d13aa67accc9c9a/lib/browser/init.ts#L177

At the very minimum allow an option to disable this when the application sets a menu anyway.

### Actual Behavior

Electron seems to install a default menu which consumes time for no good reasons it seems:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/900690/187595296-0380cf75-2b92-4c69-be7c-0172124a66e7.png">

**Comment by deepak1556** [comment]
`setDefaultApplicationMenu` is actually [noop](https://github.com/electron/electron/blob/bfced8cbfe6bad6d119ea9276d13aa67accc9c9a/lib/browser/default-menu.ts#L12-L13) if application sets their menu https://github.com/electron/electron/blob/bfced8cbfe6bad6d119ea9276d13aa67accc9c9a/lib/browser/api/menu.ts#L167-L173 before the call happens. Basically, an application has to set the menu before app ready event to disable Electron from creating the default menu.

Electron would have to expose `setApplicationMenuWasSet` via something like `Menu.disableDefaultMenu` if an application wants to disable the default menu and still create the menu after the app ready event.

**Comment by bpasero** [comment]
> Electron would have to expose setApplicationMenuWasSet via something like Menu.disableDefaultMenu if an application wants to disable the default menu and still create the menu after the app ready event.

I would turn it around and by default not install a menu and have an option to set it. By default Electron should not do anything unless told so. For example, by default Electron is not creating a browser window, the application has to do it. As such, it makes little sense to install a default menu.

**Comment by MarshallOfSound** [comment]
> By default Electron should not do anything unless told so.

This is a balancing act that isn't as simple as that.  Electron has to balance ease of use against devxp and 99 other things.  In this case, having a default menu that only sets itself if the app doesn't provide one before the ready event is a perfectly reasonable compromise IMO.

For your case if you wish to ensure a default menu is not provided you simply need to provide your menu earlier, or provide an empty template (which should be a very quick no-op) early in your init process

**Comment by bpasero** [comment]
@MarshallOfSound our application on Windows is frameless, we draw our own menu. We have no reasons to set a default menu. 

In the spirit of making Electron startup fast, please do not set a default menu that is not even used.

**Comment by zcbenz** [comment]
@bpasero According to our docs calling `Menu.setApplicationMenu(null)` should suppress the default menu.

**Comment by bpasero** [comment]
@zcbenz great, is this timing sensitive? can it run before `app.on("ready")`?

**Comment by Prinzhorn** [comment]
> @zcbenz great, is this timing sensitive? can it run before `app.on("ready")`?

Quoting @deepak1556 :

> an application has to set the menu before app ready event to disable Electron from creating the default menu.

**Comment by bpasero** [comment]
👏 I will try this in VSCode.

**Comment by bpasero** [comment]
I can confirm this saves us `10ms` on our perf bot.

**Comment by fabiospampinato** [comment]
Thanks for sharing ❤️ FWIW I'm seeing about a ~2ms reduction on an M1, which is still worth it for me, these numbers add up.
