### ISSUE TITLE
[Bug]: Electron prebuilt darwin-arm64 fail with "Electron.app is damaged"

### ISSUE THREAD

**Issue by develorer** [electron/electron#35524]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12.5.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I expect the app to open

### Actual Behavior

The app fails to launch with the following message:

`“Electron.app” is damaged and can’t be opened. You should move it to the Bin.`

### Additional Information

Steps to reproduce :

1) on a macOS system, download the Electron prebuilt binary `https://github.com/electron/electron/releases/download/v20.1.0/electron-v20.1.0-darwin-arm64.zip`

2) unzip it, double-click on Electron.app

3) Watch it fail

-----

Search over the problem  :
1) The app opens correctly when using the build `darwin-x64` instead of the build `darwin-arm64` (https://github.com/electron/electron/releases/download/v20.1.0/electron-v20.1.0-darwin-x64.zip)

2) I tried codesigning the app from the `darwin-arm64` build , and it still fails.

**Comment by jkleinsc** [comment]
This error just means that the application has the quarantine bit set on it because it was downloaded from the internet.  You can clear the error by running `xattr -c Electron.app`

**Comment by develorer** [comment]
Ah, that's very interesting.

When I run the `darwin-x86` version, it has the quarantine flag, but the message is correct, it says `”Electron.app” cannot be opened because the developer cannot be verified.`

When I run the `darwin-arm64` version, it also has the same flag, but the message says `“Electron.app” is damaged and can’t be opened. You should move it to the Bin.`

I am not clear why the message is so different. But it is probably an issue on the macOS side. In any case, this solves my problem.

Thanks for your quick turnaround!

**Comment by ifree92** [comment]
Just wondering why it occurs. Does everyone know a clue?
Probably it occurs only for apps that are not being signed.

**Comment by flotwig** [comment]
I think we're also seeing this happen, but only on arm64 builds of Electron: https://github.com/cypress-io/cypress/issues/24822

**Comment by OrganicChem** [comment]
I checked my app on an x64 machined running os 12.x - it's codesigned and notarized and I get this message. Is there a solution for this?
