### ISSUE TITLE
[Bug]: Two critical bugs in BrowserView . draggable area problem and fullscreen issue

### ISSUE THREAD

**Issue by pejman1** [electron/electron#35537]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.x- 19.x - 20.x - 21.x - 22.x - 23.x - 24.x - 25.x - 26.x- 27.x
### What operating system are you using?

Windows

### Operating System Version

windows 10,11 all versions 

### What arch are you using?

x64

### Last Known Working Electron version

17.0.0

### Expected Behavior

In windows os with frameless windows 
Browserview with setAutoResize to true

1.draggable area in browserview won't work if you hide and add it again to the main window. at first it works but after hide it and add it again it won't work. 

2. after putting windows to the maximize state the browserview gets bigger size than the screen . it is a long issue after three major versions it still has not been fixed and it seems the developers have no intention to fix it !! 
I would appreciate if you could take it into consideration 

### Actual Behavior

draggable area should work after hidding and add it again to the browserwindow
browserview should resize to the size of the window after make it fullscreen 

in version 17.0.0 we don't have these bugs 

### Testcase Gist URL

https://gist.github.com/pejman1/c6b188b4564d87eb016d5331350cf60f

### Additional Information

I have also added the sample video and the sourcecode to show the problem 

https://user-images.githubusercontent.com/11601344/187837232-ff160dbc-d20f-41ef-9fef-3c93e43adb4a.MP4

**Comment by pejman1** [comment]
https://github.com/electron/electron/issues/34342#issuecomment-1306588079

**Comment by pejman1** [comment]
dear @codebytere why have you removed this issue from your assignment ? 
will it be fixed?

**Comment by pejman1** [comment]
@madarche, 
up .
after more than 1 year and 7 major version of electron form 18 to 24, the issue has not been fixed yet!!

**Comment by zerosoul** [comment]
> @madarche, up . after more than 1 year and 7 major version of electron form 18 to 24, the issue has not been fixed yet!!

yes, not fixed yet!!!

**Comment by pejman1** [comment]
the issue hast not been fixed!

**Comment by Duplicake-fyi** [comment]
This is still broken! this needs to be reopened
