### ISSUE TITLE
[Bug]: After setting minWidth, hide and then show, not keep the original size

### ISSUE THREAD

**Issue by GavinTan** [electron/electron#35536]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

should keep the original size

### Actual Behavior

After setting minWidth, hide and then show, the size will automatically increase instead of maintaining the original size

![image](https://user-images.githubusercontent.com/10555093/187813722-fa2be10f-7873-451a-9d47-8b44fe28be9e.png)
![image](https://user-images.githubusercontent.com/10555093/187813806-359c3503-f924-4801-9409-f63f4b42c99b.png)
![image](https://user-images.githubusercontent.com/10555093/187813819-2fc9eb9e-1d4c-4a98-8973-1b62f79cda82.png)

### Testcase Gist URL

https://gist.github.com/4a38d46e641452561d72016306523aef

**Comment by BlackHole1** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by GavinTan** [comment]
@BlackHole1 https://gist.github.com/4a38d46e641452561d72016306523aef

**Comment by BlackHole1** [comment]
After some troubleshooting, it is not reproducible on mac, but stable on windows. And it seems that every version has this problem.

**And it must be reproduced by means of Tray.**

**Comment by GavinTan** [comment]
yes, is there any good way?

**Comment by GavinTan** [comment]
v22.0.0 problems still exist
