### ISSUE TITLE
[Bug]: Electron tries to bind a socket outside the app's container on macOS

### ISSUE THREAD

**Issue by develorer** [electron/electron#35540]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.6

### What operating system are you using?

macOS

### Operating System Version

macOS

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I expected the socket to be binded to a file descriptor inside the app's container.
I also expected the app to launch correctly.

### Actual Behavior

1) Take the [pre-built binary `mas-arm64`](https://github.com/electron/electron/releases/download/v19.0.6/electron-v19.0.6-mas-arm64.zip). Notice this is the `mas` build, so should play nicely with sandbox entitlement.

2) Add app code to `Electron.app/Contents/Resources/app`

3) code sign with sandbox entitlements as appropriate (add `ElectronTeamID`, sign helpers, etc)

4) Launch the app on macOS, notice that a call to `app.requestSingleInstanceLock` fails with the error code :

`process_singleton_posix.cc(1184)] Failed to bind() /var/folders/s2/j0z79krx43qgmt8l71r95_zc0000gn/T/com.electron.logseq/S/SingletonSocket: Operation not permitted (1) `

This means `requestSingleInstanceLock` is trying to bind a socket outside the app's container. I would not expect that from the mas build.

### Additional Information

If I do all the same thing, but remove the `com.apple.security.app-sandbox` entitlement, then it all works correctly.

**Comment by mifi** [comment]
Did you find any solution for this? I'm having the same error after upgrading my app https://github.com/mifi/lossless-cut to electron 21

**Comment by wrangler8A** [comment]
ср, 23 нояб. 2022 г., 10:05 Mikael Finstad ***@***.***>:

**Comment by mifi** [comment]
Ok I found out why it exits with error code 0, because my code calls `if (!app.requestSingleInstanceLock()) app.quit()` (duhh)

So my workaround to this problem is to wrap the function and don't call it for mas builds:

```js
function safeRequestSingleInstanceLock() {
  if (process.mas) return true; // todo remove when fixed https://github.com/electron/electron/issues/35540
  return app.requestSingleInstanceLock();
}
```

**Comment by wrangler8A** [comment]
Ok, I'll check it out.

ср, 23 нояб. 2022 г., 10:12 Mikael Finstad ***@***.***>:

**Comment by mifi** [comment]
Bump. Maybe requestSingleInstanceLock should be changed to just return if mas is true

**Comment by mifi** [comment]
bump

**Comment by mifi** [comment]
bump

**Comment by mifi** [comment]
Bump: Still no evidence of a mas-specific check here:
https://github.com/electron/electron/blob/79e714a82506f133516749ff0447717e92104bc1/shell/browser/api/electron_api_app.cc#L1075

**Comment by 471595249** [comment]
Same here;
build mas-dev and mas.
mas pkg upload testfight successful， but app crashed when startup
mas-dev launch carsh.
have any soluion

**Comment by zoltan-szalontai** [comment]
I also ran into this issue with Electron 30 mas build.
```
  const gotTheLock = app.requestSingleInstanceLock()
  if (!gotTheLock) {
    logMessage('Another instance of the app is already running, exiting...', 'info')
    app.quit()
  }
```
On Sonoma, this works, but on older MacOS versions it always returns falsy even though there is no other instance.
I guess I just disable this logic for MacOS.

**Comment by Simon-Laux** [comment]
- MacOS 13.6 - still has the issue
- MacOS 14.3.1 - does not have the issue

**Comment by lukas2** [comment]
This is still an issue that should be addressed?
