### ISSUE TITLE
[Feature Request]: Support programmatically triggering native window-related popovers

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#35578]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

macOS and Windows since a few years have added popovers that open up once the user hovers over one or some of the buttons that minimize/maximize/close the window.

These popovers can't be triggered programmatically at the moment, so reimplementing those buttons in userland is not really 100% possible. Reimplementing those buttons should be generally discouraged, but there are use cases for it, and it'd be nice if this gap could be closed.

### Proposed Solution

Maybe a `BrowserWindow#.showSemaphorePopoverAtPoint` or something could be added.

### Alternatives Considered

I don't think there are any alternatives, either there's an API for this or this is not supportable with custom buttons.

### Additional Information

I'm referring to this:

<img width="297" alt="Screen Shot 2022-09-05 at 15 16 20" src="https://user-images.githubusercontent.com/1812093/188474493-69bd1295-6d32-4487-b2df-78ebc18c7cfe.png">

**Comment by miniak** [comment]
There is no official OS API for this
