### ISSUE TITLE
[Bug]: The actual dimensions of the window are inconsistent with the preset

### ISSUE THREAD

**Issue by BugOS-ly** [electron/electron#35571]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.1

### What operating system are you using?

Windows

### Operating System Version

Window 10

### What arch are you using?

x64

### Last Known Working Electron version

20.1.1

### Expected Behavior

![image](https://user-images.githubusercontent.com/85739810/188276710-eee273ed-4591-4e47-811f-6becc7800b48.png)
预期： 创建的窗口的宽高为 1080*768

### Actual Behavior

程序运行后， 创建的窗口的宽高却不等于我预设的宽高

**Comment by ckerr** [comment]
(translated by translate.google.com)

Expected: The created window has a width and height of 1080*768

Actual Behavior
After the program runs, the width and height of the created window are not equal to my preset width and height

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
