### ISSUE TITLE
[Bug]: Behavior:Win32/Hive.ZY

### ISSUE THREAD

**Issue by mattszymanko** [electron/electron#35572]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

N/A

### What operating system are you using?

Windows

### Operating System Version

19044

### What arch are you using?

x64

### Expected Behavior

The problem not occuring.

### Actual Behavior

Seems like Windows Defender is flagging electron-based apps as _Behavior:Win32/Hive.ZY_. Just started, but seems to be a common problem, as I've already encountered a [forum thread](http://www.nydolls.org/news/antivirus/comments/x5ij97/all_electronbased_apps_and_chrome_detected_as/) about it. Fresh, I might add.
Now, this is most likely an issue on Microsoft's end, but I'm reporting this here as well, seeing as it could use being reported.

**Comment by mattszymanko** [comment]
More threads, although a [reddit one](https://www.reddit.com/r/computerviruses/comments/x5idjw/help_behaviorwin32hivezy/) this time. Again, very recent.

**Comment by codebytere** [comment]
Thanks for letting us know! We're looking into it.

**Comment by mattszymanko** [comment]
Alright, it looks like this was an issue purely on Microsoft's end, like I've thought. It appears to have been fixed in Defender v1.373.1583.0, released today. So, it seems fine now.
Still, thank you for replying.

Have a good one, and thanks for your time,
Matt
