### ISSUE TITLE
NPM install -g failed execution of postinstall-xxxxxx.cmd

### ISSUE THREAD

**Issue by PlanBernhard** [electron/electron#35583]
I wrongly opened a issue on the `npm` github page, but this issue seems to be electron specific. The installation of other modules than `electron` (or similar) has worked.

# Issue
`npm install -g electron` results in this error

```
npm ERR! code 1
npm ERR! path C:\data\dev\dy\we\quick-start\node_modules\electron
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\X\AppData\Local\Temp\postinstall-a836babe.cmd
npm ERR! Blocked by group policy. Please contact your system administrator (translated).
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\X\AppData\Local\npm-cache\_logs\2022-09-06T09_22_56_569Z-debug-0.log
```

Our company policies blocking the execution of cmd files from the appdata folder. Other modules like `electron-cli` did also fail with the same error message.

# Tried solutions
Overrule the installation path by adding
```
prefix = 'C:\data\dev\npm-global'
```
into `C:\Users\X\.npmrc` file, but the error persits.
And installed NodeJS to `C:\data\dev\NodeJS` but this does still not solve the problem.

Execute the installation in a Powershell started as Admin.

# Questions
1. What does `postinstall-xxxxx.cmd` ? 
2. Is it possible to configure a different location for `postinstall-xxxxx.cmd`?

**Comment by ckerr** [comment]
Hi @PlanBernhard,

I _think_ that https://github.com/electron/electron/blob/main/docs/tutorial/installation.md#skip-binary-download is what you're looking for and that the suggestion there should get you past this problem.

As an aside, you might also want to check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to help!
