### ISSUE TITLE
[Bug]: Can webview dynamically load a web page like a browser

### ISSUE THREAD

**Issue by Lee-42** [electron/electron#35582]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.0.0

### What operating system are you using?

macOS

### Operating System Version

12.0

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

16.0.0

### Expected Behavior

Try to use webview to display a vue application. When the vue application runs successfully, the webview displays the content of the web page

### Actual Behavior

I use webview to load a web application.This web application was created by vue, And run in the development environment，Run in http://localhost:8080
`
<webview id="simulator-webview" :src="http://localhost:8080" />
`
But this vue app is not running yet，I set the url on webview. So webview is blank，which is understandable.   But when the web application runs, the webview still shows blank, which confuses me.

**Comment by Prinzhorn** [comment]
`:src` -> `src`

**Comment by codebytere** [comment]
This is not an Electron issue as noted above - correcting your `src` will fix the issue.
