### ISSUE TITLE
[Bug]: preload script cannot import custom module.

### ISSUE THREAD

**Issue by workaholic** [electron/electron#35587]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10, Window 11

### What arch are you using?

x64

### Last Known Working Electron version

19.0.15

### Expected Behavior

preload script can load custom modules (ex)) const { IPC_MESSAGES } from './constants')

constants.js
-------------
```
const IPC_MESSAGES = {
   LOGIN: 'id_ipm_Login',
}
module.exports = {
   IPC_MESSAGES: IPC_MESSAGES
}
```

preload.js
-----------
```
const { ipcRenderer, contextBridge } = require('electron')
const { IPC_MESSAGES} = require('./constants')

contextBridge.exposeInMainWorld('electronApi', {
   login: (id, password)=> ipcRenderer.invoke(IPC_MESSAGES.LOGIN, id, password),
   logout: () => ipcRenderer.invoke(IPC_MESSAGES.LOGOUT)
})

```
It's ok until version ~19.0.15 (last version of 19)
(
![image](https://user-images.githubusercontent.com/2888558/188773683-06756a02-7e54-4405-9d68-4ea8df5e802c.png)
)

### Actual Behavior

but preload script cannot load custom modules in 20.0.0~ (above after version)

(
![image](https://user-images.githubusercontent.com/2888558/188773811-060c3f4d-572a-4004-b7be-6727f5bffb65.png)
)

### Testcase Gist URL

https://gist.github.com/workaholic/1894fb3c255634c5458dd8fe0ff33ff0

### Additional Information

It is important to load custom modules from preload. Because putting the same string in main/preload is very inefficient and can lead to mistakes. If this is not bug and had decided by architectural decision, How do I load custom module in preload script? (after 20.0.0~)

**Comment by Prinzhorn** [comment]
https://github.com/electron/electron/issues/35584#issuecomment-1238366817
https://www.electronjs.org/docs/latest/tutorial/sandbox#preload-scripts

> How do I load custom module in preload script? (after 20.0.0~)

> Because the require function is a polyfill with limited functionality, you will not be able to use [CommonJS modules](https://nodejs.org/api/modules.html#modules_modules_commonjs_modules) to separate your preload script into multiple files. If you need to split your preload code, use a bundler such as [webpack](https://webpack.js.org/) or [Parcel](https://parceljs.org/).

**Comment by workaholic** [comment]
> [#35584 (comment)](https://github.com/electron/electron/issues/35584#issuecomment-1238366817) https://www.electronjs.org/docs/latest/tutorial/sandbox#preload-scripts


Hi, Prinzhorn!
Thank you for your reply, 

> > Because the require function is a polyfill with limited functionality, you will not be able to use [CommonJS modules](https://nodejs.org/api/modules.html#modules_modules_commonjs_modules) to separate your preload script into multiple files. If you need to split your preload code, use a bundler such as [webpack](https://webpack.js.org/) or [Parcel](https://parceljs.org/).

**Does this mean below?
"Custom module code must be integrated into 'a preload.js'"**

ex)
1. Copy content of the 'custom module' (ex. constants.js)
and then, 
2. Paste into preload.js

```
//#region (constants.js)
const IPC_MESSAGES = {
  LOGIN: 'id_ipm_Login',
}
//#endregion

contextBridge.exposeInMainWorld('electronApi', {
    login: (id, password)=> ipcRenderer.invoke(IPC_MESSAGES.LOGIN, id, password),
    logout: () => ipcRenderer.invoke(IPC_MESSAGES.LOGOUT)
})
```

**Comment by VerteDinde** [comment]
As Prinzhorn stated above, this is expected behavior beginning in Electron 20. If needed, you can specify `sandbox: false`, however please be aware that this goes against our recommended security best practices.

You can read more about this change here: https://www.electronjs.org/docs/latest/breaking-changes#default-changed-renderers-without-nodeintegration-true-are-sandboxed-by-default

**Comment by CodePlex19** [comment]
> 

If this is now the suggested best practice for security then Electron itself needs to be modularized for code structuring and separation of concerns.. no one wants a single preload file full of code for 20+ features.  we should be able to create modules each with its own renderer and preload.

**Comment by Becheler** [comment]
To build on @johannesjo's point: the current situation regarding separation of concerns is quite problematic. Are there any alternative or recommended approaches we could consider?
