### ISSUE TITLE
[Bug]: fix crashReport.start has been reverted 

### ISSUE THREAD

**Issue by becauseOf** [electron/electron#35592]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^20.1.1

### What operating system are you using?

macOS

### Operating System Version

monterey

### What arch are you using?

x64

### Expected Behavior

crashReport.start quick

### Actual Behavior

crashReport.start still slow

### Additional Information

https://github.com/electron/electron/pull/34609

**Comment by RaisinTen** [comment]
There was also a reland right after the revert - https://chromium-review.googlesource.com/c/crashpad/crashpad/+/3721655 and that change still exists.

And Electron is maintaining a patch file containing the performance fix in v20.1.1 - https://github.com/electron/electron/blob/v20.1.1/patches/chromium/posix_replace_doubleforkandexec_with_forkandspawn.patch.
