### ISSUE TITLE
[Bug]: V8 process OOM: (WasmCodeManager::Commit: Cannot make pre-reserved region writable) on Apple M1

### ISSUE THREAD

**Issue by TerryChan** [electron/electron#35608]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.13

### What operating system are you using?

macOS

### Operating System Version

12.5.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Launch successfully

### Actual Behavior

Failed to launch with errors below on Apple M1:
```
<--- Last few GCs --->

[27023:0x140008000]     5486 ms: Scavenge 40.4 (53.0) -> 39.4 (56.2) MB, 17.7 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure; 
[27023:0x140008000]     5579 ms: Scavenge 45.3 (56.2) -> 41.1 (57.5) MB, 5.3 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure; 


<--- JS stacktrace --->

[27023:0908/190742.075455:ERROR:v8_initializer.cc(689)] V8 process OOM: (WasmCodeManager::Commit: Cannot make pre-reserved region writable).
```

### Additional Information

I added [ssh2 ](https://github.com/mscdex/ssh2) to [GitHub Desktop project](https://github.com/desktop/desktop) ,  I want to support SSH in electron app, it builds succeed, but launch failed with errors on Apple M1. And it can launch successfully on Windows and Apple Intel.
I also consulted in ssh2 proejct in this [issue ](https://github.com/mscdex/ssh2/issues/1212), and the author replied that it's a v8 engine issue, and Electron may fixed. But I still get error with Electron 19.0.13.

The repro steps on Apple M1 are:
1. Clone GitHub Desktop: git clone https://github.com/desktop/desktop.git
2. build and run GitHub Desktop：yarn ; yarn build:dev ; yarn start
3. add ssh2 to the project: cd app;  yarn add ssh2 ; cd ..; yarn add @types/ssh2
4. build and run again, and it failed

Any sugesstion to fixed this issue ? Thanks

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
