### ISSUE TITLE
[Bug]: cannot select a file `.test` in open dialog with file filters

### ISSUE THREAD

**Issue by bpasero** [electron/electron#35607]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20

### What operating system are you using?

macOS

### Operating System Version

12.5.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

You can select a file `.test` from the open dialog when file filters are configured as:

```
{ name: 'test file', extensions: ['test']}
```

### Actual Behavior

The file appears as not selectable after pressing command `Cmd+Shift+.` to show hidden files.

### Additional Information

Preparation: create a file `.test` in `~/Documents` folder.

Code to reproduce:

```js
const { app, BrowserWindow, dialog } = require('electron')

app.whenReady().then(() => {
  const mainWindow = new BrowserWindow({ height: 600, width: 600 })

  // Show an "Open File" dialog and attempt to open
  // the chosen file in our window.
  dialog.showOpenDialog(mainWindow, {
    properties: [
      'multiSelections',
      'openDirectory',
      'openFile',
      'createDirectory',
      'treatPackageAsDirectory'
    ],
    filters: [
      { name: 'test file', extensions: ['test']}
    ]
  }).then(result => {
    if (result.canceled) {
      console.log('Dialog was canceled')
    } else {
      const file = result.filePaths[0]
      mainWindow.loadURL(`file://${file}`)
    }
  }).catch(err => {
    console.log(err)
  })
})
```

**Comment by ckerr** [comment]
Confirmed on Linux as well. Adding `showHiddenFIles` does show the file but does not make it selectable.

**Comment by ckerr** [comment]
gist form of @bpasero's repro testcase:

https://gist.github.com/2d6f6948ab26889479d58ec78fe9aba1

**Comment by bpasero** [comment]
Keep

**Comment by codebytere** [comment]
@bpasero having dug into this a little bit, it doesn't look like it's possible on a system level. Specifically - macOS does not understand `.test` to be a file with a `test` extension - it understands it to be a hidden file _called_ test with _no_ extension. This can be seen by for example calling `[[dialog URL] pathExtension]` on the return value of the chosen `.test` file if the dialog is opened without filters - it shows `nil`. Happy to re-open if that changes or I find a workaround - this also doesn't work in Chromium at the moment so it doesn't appear they've been able to find a solution either.

**Comment by bpasero** [comment]
Thanks for analysing 👍
