### ISSUE TITLE
[Feature Request]: Detect if sound for notifications are enabled

### ISSUE THREAD

**Issue by davej** [electron/electron#35613]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

My app plays a custom sound when there is a notification.

I want to be a considerate app and only play the sound if the user has sounds enabled for notifications. I've tried to find this setting in the `systemPreferences` module but it doesn't seem to be there. This would be great to get working so that I can be considerate of my users' preferences.

![image (11)](https://user-images.githubusercontent.com/26971/189135518-80f7b6f9-1a2d-42f4-aa0d-5eb0afd188ed.png)

### Proposed Solution

Provide an API that allows me to query whether my app has permission to play notification sounds.

### Alternatives Considered

I looked [electron-notification-state](https://github.com/felixrieseberg/electron-notification-state) but that solves a different issue.

**Comment by MarshallOfSound** [comment]
> Provide an API that allows me to query whether my app has permission to play notification sounds.

Similar to the module you linked this can be easily implemented as a native module and doesn't need to nor easily fits into Electrons core api
