### ISSUE TITLE
[Bug]: Modal frameless child window cannot display traffic light on MacOS.

### ISSUE THREAD

**Issue by Kenhuey** [electron/electron#35627]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^20.0.2

### What operating system are you using?

macOS

### Operating System Version

Latest version

### What arch are you using?

x64

### Expected Behavior

Child window options.
```
{
    width: 256,
    height: 256 + 32, 
    resizable: false,
    frame: false,
    minimizable: false,
    parent: window, // parent window instance
    modal: true,
    webPreferences: {
        webviewTag: true
    },
    titleBarStyle: "hidden",
    trafficLightPosition: { x: 10, y: 9 }
}
```

When use those options modal child window should have traffic light, and parent window should freeze.

### Actual Behavior

![image](https://user-images.githubusercontent.com/57590797/189335307-ef3997b0-9a98-45f6-9ad0-07da25265685.png)

Child modal window did not display traffic light, parent window's traffic light can be use but not for child window.

### Additional Information

Is it a bug or a feature on MacOS?
How did I code to make child frameless modal window to display traffic light either?

THX.

**Comment by UnfixedSun** [comment]
@Kenhuey @lsegal @vitaliel @anaisbetts @mcolyer Please assign me this issue. Thanks.

**Comment by Kenhuey** [comment]
#30232

**Comment by codebytere** [comment]
See https://github.com/electron/electron/issues/30232#issuecomment-884922728

**Comment by Kenhuey** [comment]
> See [#30232 (comment)](https://github.com/electron/electron/issues/30232#issuecomment-884922728)

This comment not work for me.
How did I code to make child frameless modal window to display traffic light either?
