### ISSUE TITLE
contextBridge export an readFile Function Then Package with blob send To server, memory leak

### ISSUE THREAD

**Issue by shibin-tiny-dust** [electron/electron#35626]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.9

### What operating system are you using?

Windows

### Operating System Version

Windows10

### What arch are you using?

x64

### Last Known Working Electron version

13.0.0~17.1.14

### Expected Behavior

no memory leak

### Actual Behavior

1.The memory usage will increase when call `readFile` Function.
2.The memory usage will increase  when send the result of `readFile` Function .
3.The memory is not reclaimed when the bytes send to server , i think the bytes can garbage collection.
4. Use Ctrl+R will release memory
5. Both windows and macOS

### Testcase Gist URL

https://gist.github.com/7b5811dc028826ff5bc9ff0bffd6dcc2

### Additional Information

In the test example, I can't send the blob to the server. So the effect may not be seen. I am not sure if this is a bug of electron. But this problem does exist.

**Comment by Prinzhorn** [comment]
> 13.6.9
> 13.0.0~17.1.14

These are all very outdated.

If you can reproduce this with a more recent version then the question is how are you measuring memory usage? Did you attach a debugger?

> i think the bytes can garbage collection.

Just because it _can_ be garbage collected, doesn't mean it will be immediately. Will you eventually run out-of-memory or will the garbage collector run when put under enough pressure (e.g. `malloc` fails)? What if you `--expose-gc` and gc manually when you think the buffer should be freed?

**Comment by shibin-tiny-dust** [comment]
There will be many large files uploaded in the project I participated in.  the memory will not be released, and finally the program will crash due to out-of-memory. I understand the mechanism of garbage collection. However, the memory has not been released. I wonder if this problem exists in these versions. For some reasons, i can’t show code of The project. Please forgive me. Then I'll upgrade the version of electron and do a test. Thank you for your reply

**Comment by Prinzhorn** [comment]
> and finally the program will crash due to out-of-memory

Thanks for clarifying. Does that happen with the Fiddle as well? I tried it (with Electron 20 and a 100MB file) and I could see the memory decrease periodically.

> i can’t show code of The project [...] Then I'll upgrade the version of electron and do a test

Understandable. If you can provide a Fiddle that will crash with a recent version of Electron that's all we need.

**Comment by shibin-tiny-dust** [comment]
>Does that happen with the Fiddle as well? I tried it (with Electron 20 and a 100MB file) and I could see the memory decrease periodically

We can't reproduce all our logic in fiddle, but the general steps are the same as those I showed in the example. I omitted the code uploaded to the server. I will upgrade the 'electron' version to see if this problem still exists

>If you can provide a Fiddle that will crash with a recent version of Electron that's all we need.

In the future, if I'm going to take away a small project, I'll write all the logic that appears as much as possible in it. I will also reply to the address below. Thank you very much for your reply

**Comment by shibin-tiny-dust** [comment]
I try to use the latest version of `electron` 20.1.3. Memory has been recycled . Do previous versions, such as 13.6.9, have plans for repair or troubleshooting
> Because if I update the `electron` version, I think I need to recompile the native library used in the project. I'm worried about other compatibility issues

- The following is the repositories of my test project
https://github.com/shibin-tiny-dust/vite-electron-memory-demo

**Comment by Prinzhorn** [comment]
> I try to use the latest version of `electron` 20.1.3. Memory has been recycled

Great, so I think this can be closed?

> Do previous versions, such as 13.6.9, have plans for repair or troubleshooting

Not that I'm aware. This is extremely outdated and if your app is used anywhere but in an offline/intranet setting, you are putting your users at risk.

https://endoflife.date/electron
https://www.electronjs.org/blog/8-week-cadence/

This might be a Node.js bug or a bug in V8 or who knows. If it's fixed in the latest release, there is no reason to act.

> Because if I update the `electron` version, I think I need to recompile the native library used in the project. I'm worried about other compatibility issues

Sorry, but that's not the problem of the Electron team and this isn't different from any other of your dependencies. It's up to you to keep your software up-to-date.

**Comment by shibin-tiny-dust** [comment]
OK, thank you again for your reply, then I will close it
