### ISSUE TITLE
[Bug]: Iframe content doesn't render when executeJavaScript is called against it using the 'did-start-navigation' event

### ISSUE THREAD

**Issue by andreasdj** [electron/electron#35638]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 19044.1889

### What arch are you using?

x64

### Last Known Working Electron version

19.0.6

### Expected Behavior

When calling executeJavaScript inside a 'did-start-navigation' event listener, I expect it to render the frame contents.

### Actual Behavior

When calling executeJavaScript inside a 'did-start-navigation' event listener, the script executes but the frame doesn't render.

### Testcase Gist URL

https://gist.github.com/b0ba1e4c64bec63e5e6b29a808e5a353

### Additional Information

When testing the gist with Electron Fiddle one can see that the behavior was introduced in Electron 20.0.0. 

Results:
- 20.0.0-alpha.1, crashes with ERROR:gpu_process_host.cc(973)] GPU process exited unexpectedly: exit_code=-1073741819
- 20.0.0-alpha.2 to 20.0.0-beta.8 works (i.e. renders the content)
- 20.0.0-beta.9 and later versions doesn't render the content

The chromium update between 20.0.0-beta.8 and 20.0.0-beta.9 can be found here:
https://chromium.googlesource.com/chromium/src/+log/104.0.5073.0..104.0.5112.39?n=10000&pretty=fuller

There are alternative events for executing scripts against subframes. 'frame-created' seems to be the right option to switch to although there are some things to be aware of, see:
https://github.com/electron/electron/issues/34727

**Comment by samuelmaddock** [comment]
Based on some initial investigation, `did-start-navigation` is emitted too early for what you'd like to do. [Chromium's DidStartNavigation documentation](https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/web_contents_observer.h;l=257-297;drc=4e1b7bc33d42b401d7d9ad1dcba72883add3e2af) mentions that the navigation will not be fully committed in this event.

It looks like what you want to do is override `window.print` to prevent it from being used. You should probably try using a preload script instead as it runs synchronously in the Renderer process as soon as the document's script context is first available and before remote scripts are run.

To be able to achieve the same thing from the main process, we would need a synchronous event when the frame's document is made available which I don't believe exists yet.

**Comment by codebytere** [comment]
Closing as this issue is resolvable outside the scope of a change to Electron itself.

**Comment by markleutloff** [comment]
The problem still exists with Electron v25.0.0 and possible the previous versions too.
