### ISSUE TITLE
[Bug]: BrowserView: Ctrl+Shift+= sent to active site, but Ctrl-R sent to BrowserWindow

### ISSUE THREAD

**Issue by safinaskar** [electron/electron#35634]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.3

### What operating system are you using?

Other Linux

### Operating System Version

Debian Stretch

### What arch are you using?

x64

### Expected Behavior

-

### Actual Behavior

It seems you didn't put much effort to default electron application shortcuts. They are very inconsistent.

I have an application with one BrowserWindow and one BrowserView (they have different sites with different domains, this is important). When I press Ctrl-R, this shortcut is always delivered to BrowserWindow. But when I press Ctrl-Shift-=, this shortcut is delivered to whether site is active! This behavior seems to be very inconsistent. Is this a bug?

Here is full source of my app. `main.js`:
```js
"use strict";

const { app, BrowserWindow, BrowserView, dialog, clipboard, ipcMain } = require("electron");
const path = require("path");

(async () => {
  await app.whenReady();
  const window = new BrowserWindow({});
  window.loadURL("https://www.electronjs.org");
  const view = new BrowserView({});
  window.setBrowserView(view);
  view.setBounds({x: 0, y: 0, width: 300, height: 300});
  view.webContents.loadURL("https://google.com");
})();
```

`package.json`:
```json
{
  "name": "te",
  "version": "0.1.0",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "devDependencies": {
    "electron": "^20.0.2"
  }
}
```

Additional notes:

- Ctrl-R works, but F5 doesn't. This is strange
- Ctrl-Shift-= works, but Ctrl-= doesn't. This is inconsistent with Chrome. In Chrome both shortcuts work

If you want, I can report all bugs as separate

**Comment by Kilian** [comment]
> It seems you didn't put much effort to default electron application shortcuts. They are very inconsistent.
Please refrain from rude remarks. 

Electron is not Chrome. Ctrl + r is caught because it's part of the default menu in Electron: https://www.electronjs.org/docs/latest/api/menu#examples If you do not want that menu, overwrite it with your own, or remove the menu.
