### ISSUE TITLE
[Bug]: WCO using colors with transparency while animating causes visual glitches

### ISSUE THREAD

**Issue by martijnhartlief** [electron/electron#35635]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10, Windows 11

### What arch are you using?

x64

### Expected Behavior

Changing the background color of a document, while setting transparency on WCO buttons, should not cause side effects.

### Actual Behavior

While the background color of the document changes, transparency causes various rendering glitches.

- Always applies black line under all buttons when transparency on the WCO buttons is used
- Using transparency when setting a color does not use actual transparency on the button, but seems to make a snapshot of the current document color and merges it with the transparent color.
- Hover background color is wrong
- Hover background color persists after hovering (Does not revert to background color)

### Testcase Gist URL

https://gist.github.com/f7abdc25039e5cfbaa868bae73d043ec

### Additional Information

Use case: De-emphasize WCO buttons when a modal is open, but modal backdrop animation causes WCO buttons to have inconsistent behavior.

The test case is emulating opening and closing of a modal while attempting to update the WCO button colors.

**Comment by codebytere** [comment]
This is not currently supported - see https://github.com/electron/electron/issues/33567 for updates.
