### ISSUE TITLE
[Bug]: WASM code gen disallowed

### ISSUE THREAD

**Issue by CarterFendley** [electron/electron#35637]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.3

### What operating system are you using?

macOS

### Operating System Version

12.5.1

### What arch are you using?

x64

### Expected Behavior

For WASM modules to work regardless of the `contextIsolation` or `sandbox` flag.

### Actual Behavior

Unless both set to false, the following error will happen when using rust with webpack.

```
VM26 renderer.js:310 Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
```

### Additional Information

I saw [this issue](https://github.com/electron/electron/issues/25127) and attempted to revert back to `10.1.5` but even this did not work and left me scratching my head.

You use a the `bug-reproduction` on my repo [here](https://github.com/CarterFendley/mVisual/tree/bug-reproduction) to see this issue. Apologies for the janky launch script I was dealing with a number of issues to get it to work.

**Comment by Prinzhorn** [comment]
I didn't try running your repo, but maybe it's just blocked by CSP? https://github.com/CarterFendley/mVisual/blob/aa1da6f1124851b973b022d282cb5ff5fe36cffa/src/index.html#L9

The latest Electron (with Chromium >= 103) should support `wasm-unsafe-eval` because `unsafe-eval` would make the CSP completely useless.

**Comment by CarterFendley** [comment]
@Prinzhorn you sir are a gentlemen and a scholar!

Patched in my repo with [this commit](https://github.com/CarterFendley/mVisual/commit/2ac8d84cf6f977b95c699813b37d6a99a79c13fb) will close this issue :)

How do I see which version of electron is associated with a specific version of Chromium?

**Comment by erickzhao** [comment]
https://releases.electronjs.org/
