### ISSUE TITLE
[Bug]: Windows 11 no data from userData path on app restart

### ISSUE THREAD

**Issue by bjbk** [electron/electron#35640]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

19.0.16 **(CONFIRMED)**

### Expected Behavior

Expect data retrieval from `app.getPath('userData')` after quitting and subsequent restart of the application

### Actual Behavior

Data is only retrieved on first start of application after boot up.  Subsequent app restarts do not fetch data from `app.getPath('userData')`
Users must quit and restart Windows 11 in order to get any data.
This appears to be a Windows 11 only bug, macOS is not affected.

### Additional Information

```
// main.js
ipcMain.on('dataPath', e => {
  const dataPath = app.getPath('userData')
  e.returnValue = dataPath
})
```

**Comment by bjbk** [comment]
Rolling Electron back to v19.0.16 the app works as expected.  All data is available on app restart.

**Comment by alec-kr** [comment]
Hello. I would like to work on this issue, but I will need some assistance to get started.

**Comment by bjbk** [comment]
I don't know what was changed between v19 and v20 to cause this issue.  On first start, Windows finds the data, subsequent restarts of the app come up without data.  A Windows restart restores the link again, but app restart the link seems to be lost.  Only on Windows.  Since I have not seen others raise this issue I have to wonder what possibly could have changed and what I can do to change my code to comply.  Again, no affect on macOS, it runs normally.

**Comment by mlaurencin** [comment]
@bjbk can you provide a full test case in addition to what you provided in the additional information section? I want to be sure I am testing the same scenario you are. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

**Comment by bjbk** [comment]
I'll try.
