### ISSUE TITLE
Unexpected crash on MacOS

### ISSUE THREAD

**Issue by flurin-conradin** [electron/electron#35650]
Unfortunately, this is really unspecific. My app crashes on some mac and I am really unsure why. 

![image](https://user-images.githubusercontent.com/32741304/189826357-1c4101cb-ff33-4af2-b335-d982d02de5c3.png)

**Comment by ckerr** [comment]
Hi @flurin-conradin, 

I totally get it that it's difficult to know what information to report when it's crashing mysteriously; however,  you deleted the issue template and just included a screenshot -- so this bug report doesn't even say what version of Electron you're using. All I've got to go on herfe is literally an address where the crash happened :smile_cat: 

Ideally if you could provide the information that was requested, and use [Electron Fiddle](https://github.com/electron/fiddle) to create + upload a standalone (no external dependencies) testcase for the crash you're seeing, then that would help the maintainer team to try and figure out what's going on.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to the gist in a followup comment.

**Comment by VerteDinde** [comment]
Hey @flurin-conradin! Could you please fill out our issue template, so we have the information we might need to debug this without asking as many follow ups? Happy to have one of us take a look when the template is appropriately filled out 🙇‍♀️
