### ISSUE TITLE
[Bug]: Renderer crash when clicking a bunch of times - OOM

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#35662]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

no crash

### Actual Behavior

I get an OOM crash

### Additional Information

In my app, I am adding a network delay and clicking the main window (specifically the BrowserView in the window) a bunch of times.

The `render-process-gone` event fires with the reason of `oom` and exit code `-536870904` (in hex `0x1FFFFFF8`).
[Here's](https://github.com/microsoft/vscode/issues/130375) a related, but closed issue from VSCode.

I seem to have two crash dumps a couple minutes apart. Hopefully someone can see if this is a Chromium bug, or Electron, or something else. Here they are:
[crashpad.zip](https://github.com/electron/electron/files/9560209/crashpad.zip)

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Please use [Electron Fiddle](https://github.com/electron/fiddle) to create a standalone (no external dependencies) testcase and publish it as a [gist](https://gist.github.com), then link to it here.

- Even if you have a code snippet or a git repository that show the testcase, please put it in a gist. This lets maintainers triage issues more effectively. It also ensures that we're testing the exact same issue that you're seeing!

- Please avoid external dependencies in the test. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.

- If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). This lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to the gist in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
