### ISSUE TITLE
[Question]: Will Electron@21 use Node.js ^16.17.0?

### ISSUE THREAD

**Issue by rekmarks** [electron/electron#35675]
This does not really fit any of your issue templates. I see that the current beta branch is on Node.js ^16.16.0, but will Electron@21 be on Node.js ^16.17.0?

**Comment by Prinzhorn** [comment]
Your edit made my answer completely pointless

**Comment by rekmarks** [comment]
@Prinzhorn my apologies.

**Comment by ckerr** [comment]
https://github.com/electron/electron/pull/35350 bumped `main` to 16.17.0, so the answer is yes :smile_cat:

**Comment by rekmarks** [comment]
Thank you, @ckerr!

**Comment by ckerr** [comment]
Oh hmm I may have given out fake news there. 3530 came after 21 was branched so it's currently at 16.16.0 https://github.com/electron/electron/blob/21-x-y/DEPS#L7

**Comment by rekmarks** [comment]
@ckerr we just noticed that this was the case in Electron 21. Does this mean that you will not bump to Node `16.17.x` in Electron 21?
