### ISSUE TITLE
[Bug]: Menu can show "Ctrl++", yet such shortcut is not accepted as accelerator

### ISSUE THREAD

**Issue by safinaskar** [electron/electron#35672]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.3

### What operating system are you using?

Other Linux

### Operating System Version

Debian Stretch

### What arch are you using?

x64

### Expected Behavior

.

### Actual Behavior

Consider this menu item:
```js
        {
          "role": "zoomIn"
        }
```
It shows in UI shortcut "Ctrl++". So, it seems Electron should understand "Ctrl++". Okey, so, let's create this menu item:
```js
        {
          label: "Item",
          accelerator: "Ctrl++"
        }
```
And it doesn't work! Shortcut is not displayed in UI, and the shortcut doesn't work. So, Electron doesn't accept shortcut it can show!

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by safinaskar** [comment]
@VerteDinde . Here is `package.json` I will use for all my projects I will talk about:
```json
{
  "name": "a",
  "version": "0.1.0",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "devDependencies": {
    "electron": "^20.0.2"
  }
}
```

Now let me show you first project. Here is its `main.js`:

```js
"use strict";

const { app, BrowserWindow, BrowserView, dialog, clipboard, ipcMain, Menu, MenuItem } = require("electron");
const path = require("path");

(async () => {
  await app.whenReady();

  const window = new BrowserWindow({});
  {
    const menu = new Menu;
    menu.append(new MenuItem({
      label: "Menu",
      submenu: [
        {
          "role": "zoomIn"
        }
      ]
    }));
    Menu.setApplicationMenu(menu);
  }
})();
```
After starting this project we see in UI string `Ctrl++`. This proves that Electron knows about `Ctrl++`. Now, using this knowledge, let's create project 2. Here is its `main.js`:

```js
"use strict";

const { app, BrowserWindow, BrowserView, dialog, clipboard, ipcMain, Menu, MenuItem } = require("electron");
const path = require("path");

(async () => {
  await app.whenReady();

  const window = new BrowserWindow({});
  {
    const menu = new Menu;
    menu.append(new MenuItem({
      label: "Menu",
      submenu: [
        {
          label: "Item",
          accelerator: "Ctrl++"
        }
      ]
    }));
    Menu.setApplicationMenu(menu);
  }
})();
```
Here we wrote `Ctrl++` in our source, because presumably Electron should know what is `Ctrl++`. But this doesn't work! Shortcut doesn't work and it is not shown in UI!

(This message is not meant to be self-contained, you should read it together with first message in this bug report.)

**Comment by codebytere** [comment]
This is a Chromium limitation - their internal accelerator logic does not allow the same key to be used as a modifier twice in a row. If this somehow changes, we would be happy to come back to this.

**Comment by safinaskar** [comment]
> does not allow the same key to be used as a modifier twice in a row

@codebytere , what you mean? Please, say this some another way. I don't use any modifier twice. I don't write something like `Ctrl+Ctrl+X`. Shortcut `Ctrl++` is `Ctrl+Shift+=`, it uses two different modifiers: Shift and Ctrl.

Or you mean that shortcut `Ctrl++` already exists? It does not. Project 2 uses `Menu.setApplicationMenu(menu)`, so it replaces default menu, and so the project does not have any predefined `Ctrl++`. Also, if I replace `Ctrl++` with `Ctrl+Shift+=` (this is same thing) in project 2, then the project 2 works!

Or you mean that this is impossible to use two pluses (`+` signs) in shortcut? But Electron uses this string (string `Ctrl++`) in its UI, this is my point!
