### ISSUE TITLE
[Bug]: app.requestSingleInstanceLock() returns true on second start (Windows)

### ISSUE THREAD

**Issue by ericpromislow** [electron/electron#35680]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 19043.1889

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

I've "compiled" our app into a standalone Windows executable. When I click on the app's icon the first time,
I expect the app to run. When I click on the icon the second time, I want to see the first instance's window,
even if it was minimized.

I do this through the following code:
```
const lockInfo = { otherPid: -1 };
if (!Electron.app.requestSingleInstanceLock(lockInfo)) {
  gone = true;
  Electron.app.quit();
}
...

Electron.app.on('second-instance', async(_event, _commandLine, _workingDirectory, additionalData: any) => {
  // Someone tried to run another instance,
  // reveal and focus this window instead.
  if (additionalData) {
    additionalData.otherPid = process.pid;
  } else {
    console.log(`additionalData not an object`);
  }
  await protocolRegistered;
  window.openMain();
});
```

### Actual Behavior

Here's the gist of the code, running in the main process's main TS file:

```
const lockInfo = { otherPid: -1 };
if (!Electron.app.requestSingleInstanceLock(lockInfo) || lockInfo.otherPid !== -1) {
  gone = true;
  Electron.app.quit();
}

// So if we got the single-instance lock but the lockInfo.otherPid is no longer -1, it means another process 
// is telling us they were first and we should shut down.
 
//…

Electron.app.on('second-instance', async(_event, _commandLine, _workingDirectory, additionalData: any) => {
  // Someone tried to run another instance of Rancher Desktop,
  // reveal and focus this window instead.
  if (additionalData) {
    additionalData.otherPid = process.pid;
  }
  await protocolRegistered;
  window.openMain();
});
```

Both instances succeed at calling `Electron.app.requestSingleInstanceLock()`

The first instance gets a `second-instance` event, but the `additionalInfo` field is empty. When I saw that
the call to `requestSingleInstanceLock()` was always succeeding, I was hoping that if I passed an object to `requestSingleInstanceLock()` it would be passed as `additionalInfo`  to the `second-instance` event handler, but that isn't happening.

### Testcase Gist URL

Nope

### Additional Information

Here's how to repro:
```
cd ... some-working-directory
git clone https://github.com/rancher-sandbox/rancher-desktop.git
npm run build
./dist/Rancher<TAB> complete
```
Running the installer takes a few minutes to show up.
Then double-click on the icon, and allow it to start up. Minimize the window.
Then double-click on the icon again. It should bring up the window for the first instance, but instead
it creates a new window and emits a message that a port is already in use.

 There's a `lockfile` in `~/AppData/Roaming/rancher-desktop`, but it doesn't seem to be working the same way the `Singleton*` files in `~/L/AppSupp/r-d` do for macOS.

**Comment by rzhao271** [comment]
```js
if (additionalData) {
    additionalData.otherPid = process.pid;
}
```

`additionalData` is passed from the second instance to the first instance. Changing it in the event handler doesn't affect the second instance because the variable in that case is only in the first instance.

**Comment by ericpromislow** [comment]
I read the code about adding message passing to the single-instance-lock handler.

Note that the issue here is that the second process was able to get the single-instance-lock -- our code never releases it. That's my core problem. The call works as expected on macOS (meaning that the second instance fails to get the lock), but doesn't on Windows (the second instance succeeds at getting the lock when it I would expect it not to).

The use of `additionalData. otherPid` was my attempt to find a workaround. I'm more interested in either finding out how to help fix the problem on Windows, or find out about a better workaround.

**Comment by VerteDinde** [comment]
@ericpromislow I noticed you're using v18.0.3 - could you please try using 18.2.0 or higher? We fixed a fairly significant issue with requestSingleInstanceLock in both 18.2.0 and 18.3.0, bumping up to 18.3.0 may resolve this issue for you: https://www.electronjs.org/releases/stable?version=18&page=2#18.3.0

**Comment by ericpromislow** [comment]
Bumping to 18.3.6 didn't fix this issue on Windows.

**Comment by adamkpickering** [comment]
Are there any updates on this? While I haven't gone into it as far as @ericpromislow, I'm seeing `requestSingleInstanceLock()` fail in the same way on Linux.

What is the likelihood that someone in the know will be able to look at this? I've read some of the electron and chromium code around this, and I'm not sure I could implement a fix without a lot of effort, given I'm not familiar with C++...

**Comment by rzhao271** [comment]
I wonder how much of it is due to the `second-instance` handler being async?
Was there a previous Electron version where the API worked for y'all?

**Comment by adamkpickering** [comment]
> I wonder how much of it is due to the second-instance handler being async?

**Comment by ericpromislow** [comment]
I'm pretty sure it did work, but don't remember which version it broke on (I could always investigate...)
