### ISSUE TITLE
[Bug]: app.requestSingleInstanceLock() silently fails if first instance is elevated on Windows

### ISSUE THREAD

**Issue by zawata** [electron/electron#35681]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version
23.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 20H2

### What arch are you using?

x64

### Last Known Working Electron version

15.5.7

### Expected Behavior

1. start app in elevated environment(I used an admin powershell prompt)
2. start second instance of app in non-elevated environment
first instance output:
```
first instance running
second-instance received
```
second instance output:
```
second-instance exiting
Done
```

### Actual Behavior

1. start app in elevated environment(I used an admin powershell prompt)
2. start second instance of app in non-elevated environment
first instance:
```
first instance running
```
(note that it did not recieve the second-instance event)

second instance:
```
second-instance exiting
Done
```

screenshot of the actual behavior send to a coworker:
![image](https://user-images.githubusercontent.com/6119870/190287267-95c46292-f26b-4756-bb5b-5af82711f3cd.png)

### Testcase

This issue is a product of it's environment and as such, not much code is required to repro:
```js
const { app } = require('electron');

if (!app.requestSingleInstanceLock()) {
  console.log('second instance exiting');
  app.quit();
} else {
  console.log('first instance running');
}

app.on('second-instance', () => {
    console.log('second-instance received');
}) 
```

### Additional Information

This appears to have been introduced in 16.0.0 as 15.5.7 functions as expected. The issue reproduces in every electron version I tested from 16.0.0 to 20.1.4.

I wasn't sure how best to title this issue. It does not reproduce with any other combination of privlege levels:
first(admin), second(admin): works
first(normal), second(normal): works
first(normal), second(admin): works

This behavior is causing issues in our app with custom-protocol links since the first app instance could be started by the user as admin while the second instance would be started by the system/another application to open the requested link.
We already put some work into protecting the user from potentially dangerous deep-links and starting as an admin is not an abnormal action for our app. With this issue, no deep links function as long as the app is elevated.

If communicating *to* a privledged process is restricted intentionally, I would expect that the second instance's call to "requestSingleInstanceLock" should not return false. I would also expect this behavior to be documented somewhere but haven't managed to find any relevant documentation.

**Comment by zawata** [comment]
This issue is still occurring on v23.1.4

**Comment by zawata** [comment]
I'm doubtful this is a big-enough deal that anyone has even looked into it. I would but I've got higher-priority tasks besides crawling around inside the electron/chromium codebase.

Since we needed to fix this issue internally I ended up creating a custom single-instance-lock that doesn't have this problem. The node `net` module provides a couple options on [server.listen](https://nodejs.org/api/net.html#serverlistenoptions-callback) that allows unrestricted access to the pipe which circumvents this problem.

**Comment by thomas-void0** [comment]
> 

hey,bro. can look your sloved way? I have a same question.

**Comment by thomas-void0** [comment]
> I'm doubtful this is a big-enough deal that anyone has even looked into it. I would but I've got higher-priority tasks besides crawling around inside the electron/chromium codebase.
> 
> Since we needed to fix this issue internally I ended up creating a custom single-instance-lock that doesn't have this problem. The node `net` module provides a couple options on [server.listen](https://nodejs.org/api/net.html#serverlistenoptions-callback) that allows unrestricted access to the pipe which circumvents this problem.



> I'm doubtful this is a big-enough deal that anyone has even looked into it. I would but I've got higher-priority tasks besides crawling around inside the electron/chromium codebase.
> 
> Since we needed to fix this issue internally I ended up creating a custom single-instance-lock that doesn't have this problem. The node `net` module provides a couple options on [server.listen](https://nodejs.org/api/net.html#serverlistenoptions-callback) that allows unrestricted access to the pipe which circumvents this problem.
hey,bro. can look your sloved way? I have a same question.

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.

**Comment by msLoginoff** [comment]
Hi Electron team. We have a serious problem on Windows with requestSingleInstanceLock / second-instance.

If our app is running as Administrator, and another program starts our app with a file path (to import data), the second-instance event never arrives. The second process exits, and the file is lost — users see “nothing happens”.

This workflow is used in real clinics, and missed imports can delay review of patient measurements, which is stressful for both staff and patients.

We build medical sleep software, so reliability matters. After updates this happens more often, because the app can start elevated, and then our import workflow breaks for real users.

Could you please take a look and help fix this, or at least clearly document it? Thank you in advance.
