### ISSUE TITLE
Enable the OpenSSF Scorecard Github Action and Badge

### ISSUE THREAD

**Issue by joycebrum** [electron/electron#35709]
Hi, I am Joyce and I'm working on behalf of Google and the [OpenSSF][ossf] to help essential open-source projects improve their supply-chain security. The OpenSSF is a non-profit foundation backed by the Linux Foundation, dedicated to improving the security of the open-source community. It counts GitHub as a founding [member][ossf-membership].

The [Scorecard][sc] system combines dozens of automated checks to let maintainers better understand their project's supply-chain security posture. It is developed by the OpenSSF, with [direct support from GitHub][sc-blog].

Considering that the Electron Framework is widely used on cross-platform applications using HTML, CSS and JavaScript, it's been included in the OpenSSF's list of the 100 most critical open-source projects. Thus, the Scorecard Github Action could help you to track and solve security risks involving your repository/project and this way garantee that your repository and the contribution process is safe from malicious sabotage.

However, the OpenSSF has also developed the [Scorecard GitHub Action][sc-gha], which adds the results of its checks to the project's [security dashboard](https://github.com/electron/electron/security), as well as suggestions on how to solve any issues (see examples below). This Action has been adopted by 1600+ projects already.

Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge][badge] with the project's score to be added to its README.

Please, feel free to reach me out in case of any doubt or concern and thanks for the attention on this issue.

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[ossf-membership]: https://openssf.org/about/members/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

**Comment by ckerr** [comment]
Hi @joycebrum!

The decision would probably need to be made by the people in @electron/wg-releases and @electron/wg-ecosystem, but speaking as one of those people I would be interested in finding out more.

How much of Electron's build process would the action need to run in order to run its checks? Electron is built on top of Chromium, which has very demanding build system: just *fetching* all of the extended source for Electron + Chromium + third party requires custom tooling and to pull in about 24 GB of source code before building it :dizzy_face: 

If those dependency + build steps aren't practical for a scorecard action, is it possible to pick a subset of the tests that _would_ be practical? And if so, is that subset large enough to be worthwhile?

**Comment by nornagon** [comment]
I'd imagine @electron/wg-security should be involved also.

**Comment by joycebrum** [comment]
Hi @ckerr , thanks for sharing your concerns.

The Scorecard Github Action runs every time a commit is pushed to the main branch, in other words, everytime a PR is reviewed and accepted. Although it runs quite frequently, the action itself is very lightweight, taking ~1 minute to run. 

That's because the Scorecard Github Action is more of a "meta" check. It doesn't actually run anything, it simply checks the project configs and workflow files for common security issues.  Thus, it won't actually build or pull any dependencies, it'll just check that, for example, the build script doesn't have common security issues.

Thus, whether your build process is or is not on Github, the Scorecard Github Action would have an irrelevant impact on that.

**Comment by ckerr** [comment]
@joycebrum ok sounds good; I just wanted to make sure that the dependencies wouldn't make this a nonstarter.

> Would you be interested in a PR which adds this Action?

Yes, that would probably be the best way to handle it: with a PR, the different working groups mentioned above can all be added as reviewers :+1: 

Thanks for the offer!
