### ISSUE TITLE
[MAS Rejection]: Guideline 2.5.1 - Performance - Software Requirements

### ISSUE THREAD

**Issue by Amstergo** [electron/electron#35718]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.

### Electron Version

20.1.3

### Rejection Email

Your app uses or references the following non-public or deprecated APIs:

Classes: NSNextStepFrame, CALayerHost, CAContext, NSAccessibilityRemoteUIElement, NSThemeFrame

Symbols: _NSTextInputReplacementRangeAttributeName, __kCFSystemVersionProductVersionExtraKey, _CGFontRenderingGetFontSmoothingDisabled, __kCFSystemVersionBuildVersionKey, _responsibility_spawnattrs_setdisclaim, _AudioDeviceDuck, __NSInitializeKillRing, _responsibility_get_pid_responsible_for_pid, __CFCopyServerVersionDictionary, __NSYankFromKillRing, __kCFSystemVersionProductNameKey, __NSAppendToKillRing, __LSSetApplicationLaunchServicesServerConnectionStatus, _IOBluetoothPreferenceSetControllerPowerState, __kCFSystemVersionProductVersionKey, _CGDisplayUsesForceToGray, _SetApplicationIsDaemon, __NSNewKillRingSequence, __CFCopySystemVersionDictionary, __NSSetKillRingToYankedState, _CTFontDescriptorIsSystemUIFont, _CGSSetDenyWindowServerConnections

The use of non-public or deprecated APIs is not permitted on the App Store, as they can lead to a poor user experience should these APIs change and are otherwise not supported on Apple platforms.

### Additional Information

I'm newbie to electron and uploading an app to the AppStore for the first time
My app is rejected with the following message i don't understand

myDeps:
```
"devDependencies": {
    "@babel/core": "^7.19.0",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/preset-env": "^7.11.5",
    "@babel/preset-react": "^7.18.6",
    "@svgr/webpack": "^6.3.1",
    "autoprefixer": "^10.0.1",
    "babel-loader": "^8.2.5",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-imports": "^2.0.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-react-constant-elements": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "circular-dependency-plugin": "^5.2.0",
    "copy-webpack-plugin": "^4.5.2",
    "devtron": "^1.4.0",
    "electron": "^20.1.3",
    "electron-builder": "^23.3.3",
    "electron-devtools-installer": "^3.2.0",
    "electron-react-devtools": "^0.5.3",
    "electron-redux-devtools": "^0.3.4",
    "electron-reload": "^2.0.0-alpha.1",
    "eslint": "^8.23.1",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.31.8",
    "eslint-plugin-react-hooks": "^4.6.0",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^4.5.0",
    "prettier": "2.7.1",
    "react-devtools-electron": "^4.7.0",
    "recompose": "^0.30.0",
    "style-loader": "^1.3.0",
    "uglifyjs-webpack-plugin": "^2.2.0"
  },
  "dependencies": {
    "@date-io/date-fns": "^1.3.13",
    "@material-ui/core": "^4.11.4",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.58",
    "@material-ui/pickers": "^3.3.10",
    "@reduxjs/toolkit": "^1.8.5",
    "auto-launch": "^5.0.5",
    "axios": "^0.27.2",
    "bootstrap": "^4.5.2",
    "clsx": "^1.1.1",
    "cross-env": "^7.0.2",
    "css-loader": "^4.3.0",
    "date-fns": "^2.22.1",
    "electron-log": "^4.3.5",
    "electron-redux": "^1.5.4",
    "highcharts": "^10.2.1",
    "highcharts-more": "^0.1.7",
    "highcharts-react-official": "^3.1.0",
    "i18next": "^21.6.13",
    "i18next-browser-languagedetector": "^6.1.3",
    "jquery": "^3.5.1",
    "jssip": "^3.5.7",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "network-speed": "^2.1.1",
    "node-notifier": "github:viviedu/node-notifier#fix-snoretoast-activation-pipe",
    "plyr-react": "^5.0.2",
    "prop-types": "^15.7.2",
    "rage-edit": "^1.2.0",
    "react": "^18.2.0",
    "react-audio-player": "^0.17.0",
    "react-chrome-redux": "^2.0.0-alpha.5",
    "react-dom": "^18.2.0",
    "react-draggable": "^4.4.3",
    "react-electron-browser-window": "^0.1.2",
    "react-i18next": "^11.15.6",
    "react-jss": "^8.6.1",
    "react-player": "^2.9.0",
    "react-redux": "^7.2.1",
    "react-router": "^6.3.0",
    "react-router-dom": "^6.3.0",
    "react-star-ratings": "^2.3.0",
    "react-swipeable-views": "^0.13.3",
    "react-table": "^7.7.0",
    "recharts": "^2.0.9",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.9",
    "redux-persist": "^4.10.2",
    "redux-thunk": "^2.3.0",
    "register-protocol-win32": "^1.1.0",
    "sass": "^1.26.12",
    "sass-loader": "^10.0.2",
    "url-loader": "^4.1.1",
    "webext-redux": "^2.1.9",
    "webpack": "^5.74.0",
    "webpack-cli": "^4.10.0"
  }
```

I thought that the problem is in the outdated electron packages
but I updated them to the latest version
still get a failure

**Comment by ckerr** [comment]
Looks like you submitted a Darwin build of Electron instead of a mas build?

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. 

Check out https://www.electronjs.org/docs/latest/tutorial/mac-app-store-submission-guide for more information. If you need more help, there are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be able to point you in the right direction.
