### ISSUE TITLE
[Feature Request]: Allow for opening docked DevTools, even if WCO is enabled

### ISSUE THREAD

**Issue by wheezard** [electron/electron#35715]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

#35209 has introduced a change that forces a `'detach'` state for DevTools, if they are opened on a WC in a window with the Window Controls Overlay enabled.

However, this is not always a desired behavior, especially if DevTools are an integral part of your application.

I must emphasize, the detached state is not a default, but *forced*, which means you cannot override this even with
```js
webContents.openDevTools({ mode: 'bottom' })
// ignores the mode
```

### Proposed Solution

While the `'detach'` by default is good for solving the problem of WCO covering the devtools, there should be an option to override this.

For example, `wc.openDevTools()` will open them in the detached state, but `wc.openDevTools({ mode: 'bottom' })` should respect the `mode` property.

Perhaps, this should work just like it works with the `<webview>` tags, when if you explicitly pass an empty mode, it will open the DevTools in the last docked state.

### Alternatives Considered

None. Disabling WCO isn't a good enough option.

**Comment by codebytere** [comment]
@wheezard you make a good point - opened a PR to enable your use case :)
