### ISSUE TITLE
[ASK] Share data between Multiple window without using IPC.

### ISSUE THREAD

**Issue by caoquy2000** [electron/electron#35728]
Hi, Im coding a Calling Application has multi window. However the second window can't access data in main window. The main data is SIP.js's session. It is a non object so i cant use IPC to send data across windows.
-> Anyone has an idea for this problem or give me a discord group or any channel can discuss about ElectronJS. 
Thanks.

**Comment by erickzhao** [comment]
check out our community discord server: https://discord.gg/APGC3k5yaH
