### ISSUE TITLE
[Bug]: the SSL certificate verification error occurs and the screen is blank

### ISSUE THREAD

**Issue by yf339339** [electron/electron#35725]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

Windows

### Operating System Version

windows7

### What arch are you using?

x64

### Last Known Working Electron version

16.0.6

### Expected Behavior

When the system time is incorrect ,the SSL certificate verification error occurs and the screen is not blank

### Actual Behavior

When the system time is incorrect , the SSL certificate verification error occurs and the screen is blank

**Comment by Prinzhorn** [comment]
> and the screen is not blank

What else would you expect other than blank? Electron is not Chromium / not a Browser. If you need to display some sort of error or info page, you need to do that yourself, e.g. using the `certificate-error` event.

**Comment by yf339339** [comment]
> > and the screen is not blank
> 
> What else would you expect other than blank? Electron is not Chromium / not a Browser. If you need to display some sort of error or info page, you need to do that yourself, e.g. using the `certificate-error` event.

I need to write a page with a slow clock ？

**Comment by Prinzhorn** [comment]
I thought you were expecting something like this

![image](https://user-images.githubusercontent.com/679144/191053985-04980829-7e01-4dd2-9250-b5fa28f346c5.png)


If that's not the case, then please provide more details and example code using https://github.com/electron/fiddle

**Comment by ckerr** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.

**Comment by yf339339** [comment]
> I thought you were expecting something like this
> 
> ![image](https://user-images.githubusercontent.com/679144/191053985-04980829-7e01-4dd2-9250-b5fa28f346c5.png)
> 
> If that's not the case, then please provide more details and example code using https://github.com/electron/fiddle

Yes, that's what you said. Thank you
