### ISSUE TITLE
[Bug]: The shared window using desktopCapturer.getSources doesn't focus

### ISSUE THREAD

**Issue by oalfroukh** [electron/electron#35720]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.17

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows & macOS

### What arch are you using?

ia32

### Last Known Working Electron version

15.5.7

### Expected Behavior

The captured window should be focused after deprecated/removed `desktopCapturer.getSources` in the renderer.

### Actual Behavior

After deprecated/removed `desktopCapturer.getSources` in the renderer, the shared window should be focused. 

When using `desktopCapturer.getSources` in the renderer in Electron `16.2.8` or in the main process in Electron `v16.x` to `v21.x`, the shared app will not focus as the previous versions.

### Testcase Gist URL

https://gist.github.com/oalfroukh/a844a86a9f784af6f108db4df455a300

**Comment by oalfroukh** [comment]
"bump"

**Comment by Andrew-web-coder** [comment]
bump

**Comment by theonelp123** [comment]
bump

**Comment by oalfroukh** [comment]
"bump"

**Comment by oalfroukh** [comment]
"bump"

**Comment by oalfroukh** [comment]
bump
