### ISSUE TITLE
[Feature Request]: fire event when default printer is changed in OS

### ISSUE THREAD

**Issue by RohitSaroj** [electron/electron#35739]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to detect when default printer is changed in OS and accordingly show its name in my electron app. How can I do this? Is there any event for this?

### Proposed Solution

explicit event when default printer changes in OS

### Alternatives Considered

setInterval of 5000ms to call getPrinters and get the default printer but it slows down the app and is a very bad solution in general.

**Comment by codebytere** [comment]
hey - unfortunately, this isn't functionality currently possible with existing printer capabilities on any platforms. [Core Printing](https://developer.apple.com/documentation/applicationservices/core_printing?language=objc) for example does not have observer functionality, so it's not possible to hook an event we can then use to emit an event via Electron.
