### ISSUE TITLE
[Bug]:  Showing notification on the `second-instance` event in windows does not work 

### ISSUE THREAD

**Issue by EpicPi** [electron/electron#35732]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro N 1909

### What arch are you using?

x64

### Last Known Working Electron version

11.5.0

### Expected Behavior

With the following code:
```
import {app, Notification} from 'electron';

const acquiredSingleInstanceLock = app.requestSingleInstanceLock();
if (acquiredSingleInstanceLock) {
  app.setAppUserModelId('com.my.electron');

  app.on('second-instance', (e) => {
    //setImmediate(() => {
      new Notification({
        title: 'test',
      }).show();
    //});
  });

  app.setAsDefaultProtocolClient('myprotocol');
} else {
  app.quit();
}
```
Expected to see system notification when opening a second instance of app by typing `myprotocol://test` in the browser.

The system notification for `test` successfully appears when I uncomment the `setImmediate()` function above.

### Actual Behavior

No notifications appear.

### Additional Information

The application was packaged into a windows nsis executable (`.exe`) using the latest versions of `electron-webpack` and `electron-builder` on a mac.

The windows executable was tested on a virtualbox virtual machine running Windows 10 pro N 1909.

**Comment by jkleinsc** [comment]
@EpicPi hmm this appears to be an issue of missing documentation.  In our tests that use `second-instance` we use `setImmediate`: https://github.com/electron/electron/blob/main/spec/fixtures/api/singleton/main.js#L10.  @MarshallOfSound may have more perspective why its required.
