### ISSUE TITLE
[Bug]: Setting minWidth/minHieght cause size issues in fullscreen mode

### ISSUE THREAD

**Issue by kpostekk** [electron/electron#35755]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.17, 20.1.4, 21.0.0-beta.7

### What operating system are you using?

Windows

### Operating System Version

Windows 11 21H2 22000.978

### What arch are you using?

x64

### Expected Behavior

If new BrowserWindow has minHeight and minWidth set, enabling fullscreen will set to monitor size

### Actual Behavior

If new BrowserWindow has minHeight and minWidth set, enabling fullscreen might set height larger than monitor size.

### Testcase Gist URL

https://gist.github.com/3dc4d4d3bd6dcb5e07c96491a69e3549

### Additional Information

My temporary fix looks like this:

```ts
app.whenReady().then(() => {
  const mainWindow = new BrowserWindow({
    show: false,
    width: 1280,
    height: 720,
    //minHeight: 1280,
    //minWidth: 720,
    backgroundColor: '#000',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
    },
  })

  if (process.env['VITE_DEV_SERVER_URL']) {
    mainWindow.loadURL('http://localhost:4111')
    mainWindow.setMinimumSize(1280, 720)
  } else {
    mainWindow.loadFile('dist/renderer/index.html')
    mainWindow.once('ready-to-show', () => {
      mainWindow.setFullScreen(true)
      mainWindow.setMenuBarVisibility(false)
    })
  }
  mainWindow.once('ready-to-show', () => mainWindow.show())
})
```

Also I''m using dual screen setup, both landscape 1080p resultions. Both have scale 100% set.

![image](https://user-images.githubusercontent.com/30326322/191502899-e92f0e88-8228-4415-8935-7908225e8d4c.png)

**Comment by SanjilSaurav** [comment]
hey, I would like to work on this project can I get started?
