### ISSUE TITLE
[Bug]: process cannot communicate after electron app build

### ISSUE THREAD

**Issue by samuel-hansson** [electron/electron#35753]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.9

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

Renderer process can get message from main process after I build my electron app. 

### Actual Behavior

Renderer process can get message from main process after I run command "npm run electron:serve", but cann't get message from main process after I run command "npm run electron:build" and run my electron app using double clicking exe file in win-unpacked folder.

I use vue-cli-plugin-electron-builder build-tool

**Comment by ckerr** [comment]
The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron with a standalone test case. [Electron Fiddle](https://github.com/electron/fiddle) is a great tool that can be used to create and upload standalone test cases.
