### ISSUE TITLE
[Feature Request]: MacOS Notification Center Widget

### ISSUE THREAD

**Issue by xepozz** [electron/electron#35751]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I've tried to find info about the feature, but didn't found. Could you advise was there a discussion about this? 
If not what do you think? Is it possible to port the one into Elector?

Here a few information: https://developer.apple.com/documentation/widgetkit/creating-a-widget-extension

### Proposed Solution

~

### Alternatives Considered

~

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by xepozz** [comment]
But it's kind of feature request :)

**Comment by linonetwo** [comment]
Is this possible now?
