### ISSUE TITLE
Tutorial Documentation link to Learn Node.js out-of-date

### ISSUE THREAD

**Issue by ecyrb** [electron/electron#35756]
English Tutorial [prerequisites section](https://www.electronjs.org/docs/latest/tutorial/tutorial-prerequisites) links to [here](https://nodejs.dev/learn), which is a broken link. Correct link include a language path element: https://nodejs.dev/en/learn

**Comment by ckerr** [comment]
Hm, a language-independent link would be better but I don't see a way to get one from nodejs.dev. :man_shrugging: 

I guess https://nodejs.dev/en/learn is better than a 404 :slightly_smiling_face:

**Comment by Aman-0604** [comment]
Hi, @ckerr I would like to fix this bug. From which folder can I reach to that file for `prerequisites section` of English Tutorial.
It will be my first contribution 😇.
Also https://nodejs.dev/en/learn is the only link as they have updated their routes.
