### ISSUE TITLE
[Bug]: the www.electron.org can not view in china

### ISSUE THREAD

**Issue by stack-Yaffel** [electron/electron#35762]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

11.1904

### What arch are you using?

x64

### Last Known Working Electron version

16.0.0

### Expected Behavior

the www.electron.org can not view in china

### Actual Behavior

the www.electron.org can not view in china

**Comment by codebytere** [comment]
This is not an issue with Electron itself. Please open an issue on the appropriate repo.
