### ISSUE TITLE
[Bug]: i can't use env.process in renderer process without nodeIntegration

### ISSUE THREAD

**Issue by KongLee26** [electron/electron#35779]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

> 20

### What operating system are you using?

macOS

### Operating System Version

12.*.*

### What arch are you using?

x64

### Expected Behavior

can use env.process in renderer process without nodeIntegration

### Actual Behavior

can use env.process in renderer process without nodeIntegration

**Comment by Prinzhorn** [comment]
`env` is not a global, I assume you mean `process.env`.

> ### Expected Behavior
> 
> can use env.process in renderer process without nodeIntegration

Your expectation is incorrect.

**Comment by Prinzhorn** [comment]
I'm sorry, I was incorrect. It works for me, please provide a Fiddle that shows the unexpected behavior https://github.com/electron/fiddle

**Comment by KongLee26** [comment]
<img width="485" alt="Screen Shot 2022-09-23 at 14 32 56" src="https://user-images.githubusercontent.com/103982823/191912082-644c352a-e6de-47cb-8420-5c07d80794c7.png">
i added this plugin to webpack and it work
