### ISSUE TITLE
[Bug]: screen.on(display-added) not firing when mirrored

### ISSUE THREAD

**Issue by samespresso** [electron/electron#35809]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.7

### What operating system are you using?

macOS

### Operating System Version

Monterey 12.6

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The event emitters "screen.on(display-added)" and "screen.on(display-removed)" should run when a mirrored display is added and removed respectively.

### Actual Behavior

The functions are not triggered on mirrored displays on M1 and M2 Macs tested. Works on Intel based Mac and Windows tested.

### Testcase Gist URL

https://gist.github.com/577a1e67219980d5e5716686e3a179c1

**Comment by codebytere** [comment]
This is, unfortunately, not an issue with Electron itself. The `display-added` and `display-removed` events are emitted when Chromium's `DisplayObserver` events fire: https://source.chromium.org/chromium/chromium/src/+/main:ui/display/display_observer.h, and it seems as though `OnDisplayAdded` and `OnDisplayRemoved` don't fire when mirrored displays are changed. You can, however, report this upstream at crbug.com
