### ISSUE TITLE
[Bug]: Menu Bar Visibility

### ISSUE THREAD

**Issue by zigazajc007** [electron/electron#35807]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 36

### What arch are you using?

x64

### Last Known Working Electron version

19.0.0

### Expected Behavior

If I specify:

```js
win.setMenuBarVisibility(false);
```
then menu bar will be hidden which is great. But if you spam F11 key, menu bar will become visible again.

### Actual Behavior

If I specify:

```js
win.setMenuBarVisibility(false);
```
Menu bar shouldn't be visible even while spamming F11.

**Comment by Prinzhorn** [comment]
https://github.com/electron/electron/issues/19426
https://github.com/electron/electron/issues/20237

In the Future please provide a Fiddle to reproduce the error.

The vanilla Fiddle is enough, it just needs a single line added:

https://gist.github.com/b89bfaf8532bcfb5c7d7ee2c5ee010e2

[Screencast from 25.09.2022 18:41:06.webm](https://user-images.githubusercontent.com/679144/192154972-31467b17-e021-41cc-b5a7-cfbe892cd95b.webm)

**Comment by BlackHole1** [comment]
I just tested it on both Windows and mac and I can confirm that the bug only occurs on Linux.

**Comment by Prinzhorn** [comment]
Still repros in 22.0.0 and 23.0.0-alpha.3

**Comment by wugaosheng123** [comment]
I wanna pick this issue, allow me to contribute it. I found the location of the code that might be wrong(https://github.com/electron/electron/blob/9640ac441d37ecbb15f2f0df9fb6b24d29b288ff/shell/browser/native_window_views.cc#LL736C1-L739C48), can you please give me some  advice.   @codebytere @BlackHole1 

Here's my opinion:
When exiting fullscreen, in addition to judging the `IsMenuBarAutoHide()` of the window, you should also judge the user-set visibility property of menu bar. As I known, when entering fullscreen, `IsMenuBarVisible()` will change and may not be consistent with the state set by `mainWindow.setMenuBarVisibility`.
