### ISSUE TITLE
[Bug]: NSWindow does not support nonactivating panel styleMask

### ISSUE THREAD

**Issue by glocore** [electron/electron#35815]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.4

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When using `BrowserWindow({ type: "panel", frame: false })`, the window should appear while still keeping the previous window focused. It should appear as a non-activating panel like Spotlight or Alfred.

### Actual Behavior

Previous window loses focus and the following error is seen in the terminal:
```
Electron[92036:3002739] NSWindow does not support nonactivating panel styleMask 0x80
```

### Testcase Gist URL

https://gist.github.com/8e00de45bcb55d4ebbb4b597a62a75be

### Additional Information

Please observe how the underlying window's cursor is still blinking and the traffic lights are enabled when activating Spotlight, vs. my Electron BrowserWindow, which blurs the underlying window. I'm showing the BrowserWindow using a global shortcut.

https://user-images.githubusercontent.com/24620401/192259908-491171e3-b82f-4b70-b9a5-7ca8d3536967.mp4

**Comment by johnlindquist** [comment]
Instead of `win.show()`, use `win.showInactive()` to keep the focus on the previous app. 

Once in's "shown", you may also have to use `win.focus()` and/or `win.setAlwaysOnTop()` based on the behavior you want to achieve.

**Comment by promise94** [comment]
@johnlindquist Because of the above, my problem has been solved, perfectly! Thank you so much.

**Comment by ufukomer** [comment]
@promise94 this solution did not work for me on version 24.3.1, can you provide a code example? In my case I have a single window which has a type 'panel' and executing only the showInactive (then focus()) but still getting this error. Actually this error is not causing any issue but the main problem is that it becomes invisible after sometimes or brings up other background app (https://github.com/electron/electron/issues/35483).

**Comment by rmartins90** [comment]
I'm facing the same issue. Did you find any solution @ufukomer ?

**Comment by astoilkov** [comment]
https://github.com/electron/electron/issues/35815#issuecomment-1341488760 no longer works on Sonoma

**Comment by ufukomer** [comment]
> https://github.com/electron/electron/issues/35815#issuecomment-1341488760 no longer works on Sonoma

I hope it will get fixed soon

**Comment by YongzeYao** [comment]
whenever i use focus() to focus my window, the previous app loses its focus. However, if I click my window with my mouse, it works and previous app does not "lose its focus" (is still has no focus, but its state does not change). How do I achieve the mouse click effect with code? So that the previous app keeps its state?

**Comment by mp-jarvie** [comment]
NSWindow does not support nonactivating panel styleMask 0x80

It will still be forced to focus the window by other software.

**Comment by OmarHedeya95** [comment]
Not working on Sonoma. Any help?
