### ISSUE TITLE
On Electron app production build, Javascript disabled

### ISSUE THREAD

**Issue by SevymolSebastian** [electron/electron#35816]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Application should load properly in production mode

### Actual Behavior

On production build (```npm run-script build```), The screen won't load. When inspect & checking in application, Javascript Disabled. But it is working properly in development mode (```npm start```)

**Comment by BlackHole1** [comment]
Please try to delete the folder shown in the result of: `app.getPath("userData")`. Reset the devtools

**Comment by miniak** [comment]
Electron 17 is not supported
