### ISSUE TITLE
[Bug]: WCO is displayed incorrectly in RTL locales

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#35825]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

WCO buttons are expected to be in top-right of the window in both RTL and non-RTL locales.

### Actual Behavior

WCO buttons are in top-left corner:

<img width="707" alt="image" src="https://user-images.githubusercontent.com/79877362/192359496-2fd646ce-0c53-453c-9620-324287c9e541.png">

**Comment by mlaurencin** [comment]
This is actually in the original design of WCO. The relevant information can be viewed in the first link in the [Window Controls Overlay docs](https://www.electronjs.org/docs/latest/tutorial/window-customization#window-controls-overlay-macos-windows).

**Comment by indutny-signal** [comment]
Hm... this is weird because native windows display the controls on the right side...

**Comment by indutny-signal** [comment]
Nevermind, it is just Chrome and Git terminal that are LTR. Native Settings window is not:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/79877362/192383019-1a8d627f-4c27-4ba7-9213-921c2559b649.png">
