### ISSUE TITLE
[Bug]: Mouse cursor disappears on Artix when certain lib32 repos are enabled for some reason

### ISSUE THREAD

**Issue by GanerCodes** [electron/electron#35838]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Newest

### What operating system are you using?

Other Linux

### Operating System Version

Linux

### What arch are you using?

x64

### Expected Behavior

It to show the mouse cursor

### Actual Behavior

It doesn't show the mouse cursor. Here's what I had enabled that was causing this problem (which I ruled out literally all others causes for believe me)

# [galaxy-gremlins]
# Include = /etc/pacman.d/mirrorlist

# [gremlins]
# Include = /etc/pacman.d/mirrorlist

# [lib32-gremlins]
# Include = /etc/pacman.d/mirrorlist

# [lib32]
# Include = /etc/pacman.d/mirrorlist

When I disabled these and updated it pulled some other version of some AMD apu graphics drivers and other stuff and it works now. I'm just quickly writing thing in case some other poor soul is on hour 5 of trying to track down the most obscure bug known to man

### Additional Information

im running Artix

**Comment by VerteDinde** [comment]
@GanerCodes Sorry, I don't think I fully understand the issue you're reporting - is this an issue specific to an Electron app or was it affecting the entire distro while running an Electron app? Is there a bug we can fix that's specific to Linux/Artix? Since we use the issue tracker as our team's backlog, I just want to make sure I'm clear on what we can fix here.

**Comment by GanerCodes** [comment]
It was with any electron app running on the system
