### ISSUE TITLE
[Bug]: window.open with top & left props has a position issue when put the mainWindow on the secondary screen

### ISSUE THREAD

**Issue by oalfroukh** [electron/electron#35849]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

All the versions

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19041

### What arch are you using?

ia32

### Expected Behavior

The opened window should be in the selected position when the main window is on the secondary screen

### Actual Behavior

The opened window doesn't in the selected position when the main window is on the secondary screen.

### Testcase Gist URL

https://gist.github.com/daa82e3b4fa98dff1a851847ff4a2e3c

### Additional Information

Here is the source code for the hosted URL:
`index.html`
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Blank template</title>
        <p>Click the button to open a new window called "MsgWindow" with some text.</p>
        <button onclick="myFunction()">Try it</button>
        <!-- Load external CSS styles -->
        <link rel="stylesheet" href="styles.css">
    </head>
    <body>
        <h1>My awesome space</h1>
        <!-- Load external JavaScript -->
        <script src="scripts.js"></script>
    </body>
</html>
```
`scripts.js`
```js
  const width= 400;
  const height= 100;
  const top = window.screen.availHeight-height;
  const left = window.screen.availWidth-width-10;
  var myWindow = window.open("", "MsgWindow", `width=${width},height=${height}, top=${top}, left=${left}`);
```
- The opened window appeared when the main window was on the `primary screen` which has a 150% scale that is recommended, as expected on the right bottom of the screen:
![The opened window with primary screen](https://user-images.githubusercontent.com/80884942/192732303-9269595b-51a4-4818-a062-d0065c937e51.png)

- The opened window doesn't appear on the workspace when the main window is on the `secondary screen`
 FYI: the `primary screen` has a `150%` scale which is recommended: 

- When I changed the scale for the `primary screen` to `100%`, the opened window appeared when the main window was on the `secondary screen`, but the window appeared on the primary screen (should be on the secondary screen)

**Comment by oalfroukh** [comment]
Here are the screenshots for the issue:
![The opened window with secondary screen](https://user-images.githubusercontent.com/80884942/192755389-89bea9c9-1562-4f5a-96ae-b03c77e201c0.png)

![The opened window with secondary screen (the main screens has 100% scale)](https://user-images.githubusercontent.com/80884942/192755399-612c2491-62a7-4b6e-b6c8-1719fee70d87.png)

**Comment by erikjalevik** [comment]
I'm seeing the same problem when opening the window on a secondary screen positioned to the right of one with a scaling other than 100%.

**Comment by oalfroukh** [comment]
"bump"
