### ISSUE TITLE
[Feature Request]: 5.1 surround audio support

### ISSUE THREAD

**Issue by staniel359** [electron/electron#35853]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hello.
I've tried to enable 5.1 audio feature using Chrome flags:
```
--try-supported-channel-layouts
--force-wave-audio
--disable-audio-output-resampler
```
But nothing worked.
So I'm wondering: does Electron have this feature in the first place?

### Proposed Solution

If Electron does have 5.1 audio support, I'd like to know how to enable it.
If not, I'd like to suggest you adding it.

### Alternatives Considered

In Firefox browser surround audio is working, but in Chrome / Electron it isn't.

**Comment by MarshallOfSound** [comment]
Those flags are in `//content` and should work in Electron.  Do the same flags work fine in Chrome?  If not, the issue is with Chromium not Electron

**Comment by staniel359** [comment]
@MarshallOfSound Some people say they work, some say they don't.

What is `//content`?

**Comment by MarshallOfSound** [comment]
If these flags work for you in Chromium, they should work in Electron.

> some say they don't.

This indicates they do not completely work in Chromium, and therefore this issue is not in-scope for Electron.  You should try repro in Chromium, and if you can, raise a crbug with them
