### ISSUE TITLE
[Bug]: Missing Unknown Libs

### ISSUE THREAD

**Issue by SX-9** [electron/electron#35859]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3-2

### What operating system are you using?

Other Linux

### Operating System Version

Archcraft (Arch Linux) v2022.9 With Linux v5.19.8

### What arch are you using?

x64

### Last Known Working Electron version

19

### Expected Behavior

All electron based apps to start

### Actual Behavior

Gets this error of some missing pkg
![image-1](https://user-images.githubusercontent.com/90962949/193037099-95d37c93-4d35-402d-a305-0f427ea8c8b2.png)

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by MarshallOfSound** [comment]
This looks like a rebuild / repackage of Electron 19 as some kind of distro specific package.  We don't maintain those, or support them.  You should raise this issue with the maintainers of that third party package.
