### ISSUE TITLE
[Bug]: sh /var/folders/x5/y4z5_r7d4jv7h96ppz9sm_6h0000gn/T/postinstall-ed7fa10a.sh

### ISSUE THREAD

**Issue by huyanyou** [electron/electron#35851]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.0  lasted also installed failed
### What operating system are you using?

macOS

### Operating System Version

macOs m1 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

yarn add electron success

### Actual Behavior

Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/archzks/Projects/electron-vue-ts/node_modules/electron
Output:
RequestError: connect ENETUNREACH 2409:8c02:24c:90:3::3fd:443
    at ClientRequest.<anonymous> (/Users/archzks/Projects/electron-vue-ts/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (/Users/archzks/Projects/electron-vue-ts/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by huyanyou** [comment]
npm WARN config dev Please use --include=dev instead.
npm ERR! code 1
npm ERR! path /Users/archzks/Projects/electron-vue-ts/node_modules/electron
npm ERR! command failed
npm ERR! command sh /var/folders/x5/y4z5_r7d4jv7h96ppz9sm_6h0000gn/T/postinstall-ed7fa10a.sh
npm ERR! RequestError: connect ENETUNREACH 2409:8c30:1000:202:3::3fd:443
npm ERR!     at ClientRequest.<anonymous> (/Users/archzks/Projects/electron-vue-ts/node_modules/got/source/request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:628:26)
npm ERR!     at ClientRequest.emit (node:events:525:35)
npm ERR!     at origin.emit (/Users/archzks/Projects/electron-vue-ts/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:481:9)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
