### ISSUE TITLE
[Bug]: Digest method not supported

### ISSUE THREAD

**Issue by fluentwind** [electron/electron#35857]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.9.1

### What operating system are you using?

Windows

### Operating System Version

windows 10 19044.1889

### What arch are you using?

ia32

### Expected Behavior

Run crypto.createHash('sm3')  correctly

### Actual Behavior

App threw an error during load
Error: Digest method not supported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)

### Additional Information

That run successfully in nodejs 16.9.1 32bit，but failed in electron

**Comment by Prinzhorn** [comment]
https://github.com/electron/electron/search?q=sm3&type=issues

https://github.com/electron/electron/issues/34942
https://github.com/electron/electron/issues/34925

**Comment by codebytere** [comment]
Electron bundles BoringSSL, which is a slimmed down fork of OpenSSL controlled by Google. As a result, only a majority subset of Node.js crypto module algorithms are available in Electron. We generally prefer not to patch in new ones, as Google typically has a good reason for stripping them out.
