### ISSUE TITLE
[Bug]: The use is inserted successfully, but the enumerateDevices does not return the device

### ISSUE THREAD

**Issue by hengshanMWC** [electron/electron#35867]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

enumerateDevices returns the correct device

### Actual Behavior

The device is plugged in, pulled out, and plugged in again，enumerateDevices could not get the correct device list。
Check the system use and confirm that the device exists。
<img width="334" alt="企业微信截图_03c344df-b146-418e-b49c-8d9c773cb02e" src="https://user-images.githubusercontent.com/45714422/193202207-0d9bf155-9ad0-4dbf-b58c-138f4ee032b7.png">

**Comment by VerteDinde** [comment]
Hey @hengshanMWC, Electron 11.0.1 is EOL - the current latest supported version is Electron 19. Could you please try this on Electron 19 or later and see if the issue persists?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
