### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by wuIsSky** [electron/electron#35865]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Ideas on layout adaptation of different PCs?

### Proposed Solution

Provide some configuration items or other methods

### Alternatives Considered

CSS media query

**Comment by Harsh-Singh-Rajput** [comment]
Hello @wuIsSky can you explain in detail what type of adaptation needed for different PCs? Is it website design layout/responsiveness on different PCs using media query in css or something else?
