### ISSUE TITLE
[Bug]: Mac AppStore app BrowserWindow loadURL ERR_FAILED (-2)

### ISSUE THREAD

**Issue by stefanJi** [electron/electron#35866]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.3.3

### What operating system are you using?

macOS

### Operating System Version

macOS 12.3.1

### What arch are you using?

x64

### Expected Behavior

Window loadURL can work

### Actual Behavior

Make macOS app with the electron-builder, `dmg` can running work as excepected, but `mas` cann't.

```
const defaultWebPreferences: WebPreferences = {
    preload: getPreload(),
    nodeIntegration: true,
    contextIsolation: false,
    devTools: true,
    webSecurity: false,
    sandbox: false
}

window.loadURL(url.format({ pathname: path.join(__dirname, 'renderer', name, 'index.html'), protocol: 'file:', slashes: true }))
```

`mas` pkg installed by TestFlight in mac:

```
loadURL Error: ERR_FAILED (-2) loading 'file:///Applications/xx.app/Contents/Resources/app.asar/renderer/login/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:201:7486)
    at Object.stopLoadingListener (node:electron/js2c/browser_init:201:7861)
    at Object.emit (node:events:406:35) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'file:///Applications/xx.app/Contents/Resources/app.asar/renderer/login/index.html'
}
```

`renderer/login/index.html` is exsited in app.asar.

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by stefanJi** [comment]
I found remove `hardenedRuntime` will work.

**Comment by wtl1019** [comment]
> I found remove `hardenedRuntime` will work.

please show what did you set 'hardenedRuntime'?
