### ISSUE TITLE
[Bug]: Serialport package issue after electron build with electron-builder

### ISSUE THREAD

**Issue by megha24051994** [electron/electron#35860]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

8.0.0

### Expected Behavior

In an electron-ionic project, the serialport package (v10.0.0) works when the electron window is opened in Dev mode using 'npx cap open @capacitor-community/electron' but it throws an error "Cannot find module 'serialport'" when the project is build using electron-builder. 
![image](https://user-images.githubusercontent.com/42468267/193037446-b0e0d6ee-28cd-4a40-9856-7dd8e45ab5a3.png)

### Actual Behavior

The error only shows up with a generated exe file whereas it works in electron window in dev mode.

**Comment by VerteDinde** [comment]
Hey @megha24051994, this looks like an issue with electron-builder specifically - could you file an issue with the electron-builder team? Their issue tracker is here: https://github.com/electron-userland/electron-builder/issues

If this ends up being an Electron issue, happy to re-open this, but based on the stacktrace and the fact that it runs correctly when not built, it's likely an electron-builder or packaging specific issue.
