### ISSUE TITLE
[Bug]: setInterval and setTimeout doesn't work regularly

### ISSUE THREAD

**Issue by oalfroukh** [electron/electron#35875]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19041

### What arch are you using?

ia32

### Last Known Working Electron version

18.1.14

### Expected Behavior

`setInterval/setTimeout` should work regularly in the preload script.

### Actual Behavior

`setInterval/setTimeout` doesn't work regularly in the preload script in some cases, when I put the delay 5 seconds for example.

### Testcase Gist URL

https://gist.github.com/8f0fd955f90e5a356a7a5eb9b963b5de

### Additional Information

current - date: Mon Oct 03 2022 `14:27:24` GMT+0300 (Eastern European Summer Time)

timeOut - date: Mon Oct 03 2022 `14:27:29` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:27:35` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:27:39` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:27:45` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:27:50` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:27:55` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:28:00` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:28:05` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:28:10` GMT+0300 (Eastern European Summer Time)✔
.
.
.
timeOut - date: Mon Oct 03 2022 `14:32:25` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:32:30` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:32:35` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:32:40` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:33:21` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `14:34:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:35:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:36:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:37:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:38:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:39:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:40:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:41:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:42:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:43:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:44:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:45:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:46:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:47:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:48:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:49:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:50:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:51:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:52:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:53:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:54:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:55:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:56:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:57:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:58:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `14:59:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `15:00:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `15:01:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)
timeOut - date: Mon Oct 03 2022 `15:02:21` GMT+0300 (Eastern European Summer Time)❌ (now there is i min delay, that is not OK)

timeOut - date: Mon Oct 03 2022 `15:03:03` GMT+0300 (Eastern European Summer Time)✔ (now the interval get back ok)
timeOut - date: Mon Oct 03 2022 `15:03:05` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `15:03:10` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `15:03:15` GMT+0300 (Eastern European Summer Time)✔
timeOut - date: Mon Oct 03 2022 `15:03:20` GMT+0300 (Eastern European Summer Time)✔

**Comment by Prinzhorn** [comment]
Are you aware of `backgroundThrottling` https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions

**Comment by oalfroukh** [comment]
Hi @Prinzhorn Thanks for your response, I checked it now, but why that issue appeared on v19 and up?

**Comment by Prinzhorn** [comment]
> but why that issue appeared on v19 and up?

Good question, does disabling `backgroundThrottling` fix it? If so, then maybe the implementation changed or there is a bug with it. But it was just a shot in the dark (`backgroundThrottling` is no well known), I'm not sure `backgroundThrottling` will cause exactly a whole minute delay, but someone with knowledge about the internals can probably immediately tell if your logs look like `backgroundThrottling` or not.

**Comment by Prinzhorn** [comment]
> but I think it will affect on `page visibility APIs`, right?

According to the docs, yes.

**Comment by oalfroukh** [comment]
Edit:
The same issue on Electron 16.2.3 and up!

**Comment by codebytere** [comment]
@oalfroukh so it works on 16.2.2? I can't reproduce this at all on windows on any supported version at the moment.

**Comment by oalfroukh** [comment]
Hi @codebytere I re-checked all the versions, The last known working Electron version is `v12.2.3`, it's reproducible when the main window is behind other windows, so when it's `not visible`.
