### ISSUE TITLE
[Bug]: window loses focus after alert

### ISSUE THREAD

**Issue by moataz-bahaa** [electron/electron#35872]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.1

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

i can't focus input field after showing an alert message

### Actual Behavior

i have an html input field and a button with event click show an alert message after that when i try to focus input field i can't

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by Toxic48** [comment]
This is actually a known Electron bug, I don't know if they attempted to fix it before. I suggest you to not use the defualt JavaScript alert function, instead make your own small function or use a dialog.

**Comment by moataz-bahaa** [comment]
still not working

**Comment by Wapg2002** [comment]
I also have the same problem

**Comment by Wapg2002** [comment]
> Este es en realidad un error conocido de Electron, no sé si intentaron solucionarlo antes. Le sugiero que no use la función de alerta de JavaScript predeterminada, sino que cree su propia función pequeña o use un cuadro de diálogo.

do you know any alternative? I need to create alerts that block their corresponding parent window

**Comment by vaibhavpanday** [comment]
Use Electron version == 28.3.3 or less

**Comment by AzizOzenir** [comment]
it almost 2026 and still not fixed. best practice to prevent this bug is using custom alerts that you will type

**Comment by s-hliao** [comment]
Just encountered this issue as well. Swapped out to using toasts instead.

**Comment by BubbleBloody** [comment]
I spent hours reviewing and checking my code (HTML, CSS, JS) until I discovered it was just a bug with `alert` that they apparently haven't fixed.

**Comment by moataz-bahaa** [comment]
> I spent hours reviewing and checking my code (HTML, CSS, JS) until I discovered it was just a bug with `alert` that they apparently haven't fixed.

unfortunately you need to implement your customer alert
