### ISSUE TITLE
[Feature Request]: Intercept and filter Chromium stdout, stderr

### ISSUE THREAD

**Issue by xmedeko** [electron/electron#35873]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Chromium sometimes writes messages to stderr, stdout and they cannot be suppressed, e.g. see #33685 or some other issues. That's inconvenient when using Electron process as a CLI tool, especially.  

### Proposed Solution

Make some way to hook custom JS code to be able to filter stderr and stdout from Chromium. (E.g. pipe)?

### Alternatives Considered

Create a wrapper for Electron process for every platform which would pipe and filter stderr and stdout and add it to the the installer bundle. But that's inconvenient, too. (E.g. see [silence-chromium](https://github.com/beaugunderson/silence-chromium) )

**Comment by MarshallOfSound** [comment]
These logs are basically architecturally impossible to route through JS in a manner that makes them useful still.  They come from subprocesses, other threads, etc.

You should be able to turn them off with either --disable-logging or --log-level=3 or some other combination of chromium logging flags.
