### ISSUE TITLE
Passing data from browser to electron app

### ISSUE THREAD

**Issue by alaksandarjesus** [electron/electron#35893]
I am learning electronjs and want to open electron app by clicking on a href link from browser.

**package.json**

    {
      "name": "my-app",
      "productName": "my-app",
      "version": "1.0.0",
      "description": "My Electron application description",
      "main": "src/index.js",
      "scripts": {
        "start": "electron-forge start",
        "package": "electron-forge package",
        "make": "electron-forge make",
        "publish": "electron-forge publish",
        "lint": "echo \"No linting configured\""
      },
      "keywords": [],
      "author": {
        "name": "Alaksandar Jesus Gene",
        "email": "alaksandarjesus@yahoo.co.in"
      },
      "license": "MIT",
      "config": {
        "forge": {
          "packagerConfig": {},
          "makers": [
            {
              "name": "@electron-forge/maker-squirrel",
              "config": {
                "name": "my_app"
              }
            },
            {
              "name": "@electron-forge/maker-zip",
              "platforms": [
                "darwin"
              ]
            },
            {
              "name": "@electron-forge/maker-deb",
              "config": {}
            },
            {
              "name": "@electron-forge/maker-rpm",
              "config": {}
            }
          ]
        }
      },
      "dependencies": {
        "electron-squirrel-startup": "^1.0.0"
      },
      "devDependencies": {
        "@electron-forge/cli": "^6.0.0-beta.66",
        "@electron-forge/maker-deb": "^6.0.0-beta.66",
        "@electron-forge/maker-rpm": "^6.0.0-beta.66",
        "@electron-forge/maker-squirrel": "^6.0.0-beta.66",
        "@electron-forge/maker-zip": "^6.0.0-beta.66",
        "electron": "21.0.1"
      }
    }

Referring to [link][1]

**index.js**

    const { app, dialog, BrowserWindow } = require('electron');
    const path = require('path');
    
    // Handle creating/removing shortcuts on Windows when installing/uninstalling.
    // eslint-disable-next-line global-require
    if (require('electron-squirrel-startup')) {
      app.quit();
    }
    
    if (process.defaultApp) {
      if (process.argv.length >= 2) {
        app.setAsDefaultProtocolClient('foobar', process.execPath, [path.resolve(process.argv[1])])
      }
    } else {
      app.setAsDefaultProtocolClient('foobar')
    }
    
    let mainWindow;
    
    const createWindow = () => {
      // Create the browser window.
      mainWindow = new BrowserWindow({
        width: '100vw',
        height: '100vh',
        webPreferences: {
          preload: path.join(__dirname, 'preload.js'),
        },
      });
      mainWindow.maximize();
      // and load the index.html of the app.
      mainWindow.loadFile(path.join(__dirname, 'index.html'));
    
      // Open the DevTools.
      mainWindow.webContents.openDevTools();
    
      // mainWindow.setMenuBarVisibility(false)
    };
    
    
    const gotTheLock = app.requestSingleInstanceLock()
    
    if (!gotTheLock) {
      app.quit()
    } else {
      app.on('second-instance', (event, commandLine, workingDirectory) => {
        // Someone tried to run a second instance, we should focus our window.
        if (mainWindow) {
          if (mainWindow.isMinimized()) mainWindow.restore()
          mainWindow.focus()
        }
      })
    
      // This method will be called when Electron has finished
      // initialization and is ready to create browser windows.
      // Some APIs can only be used after this event occurs.
      app.on('ready', createWindow);
    
      // Quit when all windows are closed, except on macOS. There, it's common
      // for applications and their menu bar to stay active until the user quits
      // explicitly with Cmd + Q.
      app.on('window-all-closed', () => {
        if (process.platform !== 'darwin') {
          app.quit();
        }
      });
    
      app.on('activate', () => {
        // On OS X it's common to re-create a window in the app when the
        // dock icon is clicked and there are no other windows open.
        if (BrowserWindow.getAllWindows().length === 0) {
          createWindow();
        }
      });
    
      // Handle the protocol. In this case, we choose to show an Error Box.
      app.on('open-url', (event, url) => {
        console.log("url");
        dialog.showErrorBox('Welcome Back', `You arrived from: ${url}`)
      })
    }

**index.html**

    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8" />
        <title>Hello World!</title>
        <link rel="stylesheet" href="index.css" />
      </head>
      <body>
        <script type="module">
          const {getLink} = require('electron').remote.require('./index.js');
          window.location.href='https://www.google.com';
        </script>
      </body>
    </html>

I was able to create exe file from running

    npm run publish

Now in my another project, i have a href link as 

    <a href="foobar://url=https://www.google.com">open in foobar</a>

Which by clicking opens the electron app built.

But i am getting require is not defined. Removing the line from index.html

    const {getLink} = require('electron').remote.require('./index.js');

Works with no error.

How can i read the url from a href tag and pass it electron app.

I also [followed][2] but could not get the link

  [1]: https://www.electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app#electron-forge
  [2]: https://stackoverflow.com/questions/53530726/how-to-launch-my-electron-app-from-a-website

**Comment by MarshallOfSound** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
