### ISSUE TITLE
[Bug]: Long volume names eat rscreen real estate

### ISSUE THREAD

**Issue by smurfix** [electron/electron#35903]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21

### What operating system are you using?

Other Linux

### Operating System Version

Debian Testing

### What arch are you using?

x64

### Last Known Working Electron version

20?

### Expected Behavior

Long volume or shortcut names take up an inordinate amount of screen space.

### Actual Behavior

I can push the divider between the volume+shortcut list and the files further to the left and it defaults to its new position.

### Additional Information

![image](https://user-images.githubusercontent.com/236571/193862393-ccd8d7cc-fe82-40fe-9feb-f60939dab5a2.png)

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by smurfix** [comment]
Oops. Wrong program.
