### ISSUE TITLE
[Feature Request]: Deprecate Web SQL

### ISSUE THREAD

**Issue by tomayac** [electron/electron#35901]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Web SQL is on its way out and is being [slowly deprecated](https://developer.chrome.com/blog/deprecating-web-sql/). Web SQL access in insecure contexts is deprecated as of Chromium 105 at which time a warning message will be shown in the Chrome DevTools Issue panel. It's planned to fully remove it in later versions. Currently Electron still [enables the feature by default](https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions:~:text=enableWebSQL%20boolean%20(optional)%20%2D%20Whether%20to%20enable%20the%20WebSQL%20api.%20Default%20is%20true.) in `options.webPreferences.enableWebSQL`.

### Proposed Solution

Reflect what Chromium does and start deprecating Web SQL in Electron. A first step could be to make `options.webPreferences.enableWebSQL` an opt-in by defaulting it to `false`. If possible, audit (core) Electron apps for Web SQL usage and notify developers.

### Alternatives Considered

Continue supporting Web SQL via a client-side implementation. This would presumably increase the binary size of Chromium apps dependent on Web SQL. 

### Additional Information

Feel free to reach out to [me](mailto:tomac@google.com) for any questions that can't be discussed in public.

**Comment by MarshallOfSound** [comment]
> Reflect what Chromium does and start deprecating Web SQL in Electron. A first step could be to make options.webPreferences.enableWebSQL an opt-in by defaulting it to false. If possible, audit (core) Electron apps for Web SQL usage and notify developers.

That flag to enable `webSQL` **will** respect Chromium's deprecation and removal timeline.  That flag maps to a patch we made to Chromium many years ago to allow apps to disable Web SQL to mitigate potential security issues that they didn't want to be exposed to.

I don't think we should be moving _faster_ than Chromium.  That flag will be removed once web sql is disabled in Chromium.  It will _not_ allow re-enabling of it once Chromium has disabled it.
