### ISSUE TITLE
[Bug]: The global content client will init twice on the startup

### ISSUE THREAD

**Issue by netflt** [electron/electron#35916]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19

### What operating system are you using?

Other (specify below)

### Operating System Version

macOS 

### What arch are you using?

Other (specify below)

### Expected Behavior

The global content client should init once on startup.

### Actual Behavior

The global content client will init twice on the startup and it cause a memory leak.causes. 

### Additional Information

These days I try to debug the electron source and found that the global content client will init twice on startup because the ElectronMainDelegate didn't override the CreateContentClient.

The first time, it call the `ContentMainDelegate::CreateContentClient` to create an ContentClient instance.
```
void SetContentClient(ContentClient* client) {
  /*
  if(g_client != nullptr)
  {
      DCHECK(false);
  }
  */
  g_client = client;
}

//ContentClientCreator::Create
static void Create(ContentMainDelegate* delegate) {
    ContentClient* client = delegate->CreateContentClient();
    DCHECK(client);
    SetContentClient(client);
  }
```
![image](https://user-images.githubusercontent.com/34939113/194010305-cd932f47-30a2-46ac-8d7d-4d622d3e6fb1.png)

Then the global ContentClient will be set as an ElectronContentClient instance in `ElectronMainDelegate::BasicStartupComplete`

![image](https://user-images.githubusercontent.com/34939113/194011232-6061b984-486a-4bbd-ae2c-1629910c5eac.png)

So the first one is never to be used and never to be free until the process exit.

**Comment by codebytere** [comment]
@netflt we're going to need more information - your report is at this point not clear. What bug is this causing? What lead you to look into it?
