### ISSUE TITLE
[Feature Request]: Architectural effort decouple electron-host, electron-modules and use untouched chromium src - i call it internal: Project Stealify

### ISSUE THREAD

**Issue by frank-dspeed** [electron/electron#35920]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I guess the problem is most well described in a collection of existing issues that this Internal Architectural Effort that intends to stay 1:1 Consistent for outside users this is a Architectural internal WiP PR:

## Collection of existing issues that can get closed when this is closed
Closes:
- [ ] https://github.com/electron/electron/issues/21457#issuecomment-1268448058

### Proposed Solution

We integrate into the following Architectural efforts:

- [ ] NodeJS
  - [ ] - TODO: Async Hooks, VM, mksnapshot based custom builds from userland...
  - [ ] --inspect-pipe cli flag
- [ ] Chromium
  - [ ] LaCrOS
  - [ ] MOJO API
  - [ ] devtools (CDP)

The Proposed solution is WiP will follow up soon and hope that some one from the ESM Issue comments here that he is willing to take part in this effort.

### Alternatives Considered

Patch, Think and have 20x the effort needed to implement the same features.  

### Additional Information

There will be  a lot of Additional Info a small book to be clear.

**Comment by MarshallOfSound** [comment]
Electron currently has no intention to change our fundamental architecture, nor do I see / this issue provide a compelling reason to do so (or consider it).

If you have a concrete proposal for changes, your best bet is to submit a PR / RFC, not a theoretical issue with no specifics.

**Comment by frank-dspeed** [comment]
@MarshallOfSound your correct or i simply keep doing what i am doing and that mean to simply hard fork most time it is simply more easy to replace then to change.
