### ISSUE TITLE
[Bug]: Window Controls Overlay on Win11 looks too thin until Electron v22

### ISSUE THREAD

**Issue by rzhao271** [electron/electron#35938]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

22

### Expected Behavior

Enable the Window Controls Overlay (WCO) feature. The maximize button should look fairly solid and square.

### Actual Behavior

The maximize button is rounded and the stroke width is thin.

### Testcase Gist URL

https://gist.github.com/rzhao271/73c123f5553ca5d3dd866c40cee76849

### Additional Information

The issue is fixed in v22. It appears even in v21. I believe https://github.com/electron/electron/pull/35370 should be backported to the currently supported stable versions, though I need to verify that doing so actually fixes the issue before creating the backport PRs.

The following screenshot shows the v22 WCO at the top and the previous WCO below:
![The newer and older WCOs](https://user-images.githubusercontent.com/7199958/194396157-eb089909-493f-49b8-9764-bb8569d6f324.png)

**Comment by deepak1556** [comment]
Addressed in https://github.com/electron/electron/pull/35968
