### ISSUE TITLE
[Feature Request]: Idle Time Reset

### ISSUE THREAD

**Issue by medhi2006** [electron/electron#35942]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron currently does not have a way to reset the system idle time. If a video is running in an electron app, the user may neither touch the screen in a touchscreen monitor nor move the mouse nor press any keyboard key till the video is finished running. Idle time is reset only each time the user either touches the screen in a touchscreen monitor or moves the mouse or presses any keyboard key. While this is sufficient for most cases, there could be scenarios in which system idle time needs to be 0 when media is playing. 

### Proposed Solution

Electron's power-monitor module should provide a method for resetting the system idle time programmatically.

### Alternatives Considered

Tried using nut-js plugin (https://nutjs.dev/intro). Used mouse-move method of nut-js to reset the system idle time while the video is playing. But this is not an ideal solution.

**Comment by miniak** [comment]
We are using https://source.chromium.org/chromium/chromium/src/+/main:ui/base/idle/idle.h;l=31?q=CalculateIdleTime&sq=&ss=chromium, which only supports getting the idle time.

**Comment by miniak** [comment]
Did you considering using `powerSaveBlocker`?
