### ISSUE TITLE
[Bug]: Some options of printToPDF don't work

### ISSUE THREAD

**Issue by lesleyandreza** [electron/electron#35971]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

Some options of `webContents.printToPDF` don't be ignored.
The options are:
 - `margins` (`top`, `bottom`, `left`, `right` and `marginType`)
 - `pageSize`
 - `scale`

For example: When I choose a margin top, like 2" and call `printToPDF`, the PDF should come with margin top with 2"

### Actual Behavior

I defined options, but they don't work.
Am I doing something wrong, maybe using incorrect?

### Testcase Gist URL

https://gist.github.com/lesleyandreza/7699603b20f2459d1fcf3b9480fb22e1

### Additional Information

The options `headerTemplate` and `footerTemplate` works, but in a strange way, because the text comes really small. Maybe this could be a Chromium bug.
<img width="1404" alt="very-small-header" src="https://user-images.githubusercontent.com/14945792/194948569-26c8639a-abe8-4a82-b8ee-1e00e1d38192.png">

But there is a workaround with CSS:
<img width="1400" alt="normal-header" src="https://user-images.githubusercontent.com/14945792/194948843-1ad0fd55-d881-4037-abe0-3801fe44fc29.png">

**Comment by codebytere** [comment]
@lesleyandreza could you verify this against https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF? If the issues are the same there, the issue is upstream.

**Comment by Hedwig188** [comment]
I can still reproduce the headerTemplate, footerTemplate sizing issue after the fix.
