### ISSUE TITLE
[Bug]: BrowserView setBounds behavior inconsistent between Mac and Windows

### ISSUE THREAD

**Issue by nornagon** [electron/electron#35994]
```js
bv.setBounds({x: 0, y: 0, width: 500, height: 40})
```
gives different results on different platforms:

mac:
![Screen Shot 2022-10-11 at 4 09 38 PM](https://user-images.githubusercontent.com/172800/195215145-2da82eed-c502-4d2d-8a9b-409a6a5e1192.png)

windows:
![image](https://user-images.githubusercontent.com/172800/195215162-b5658cf4-5448-4414-bc8d-8b2e2506debb.png)

Regressed in #34713 I believe. cc @codebytere

**Comment by kevinlinv** [comment]
🎉 FYI, this may partially fix this issue https://github.com/electron/electron/issues/35995

**Comment by codebytere** [comment]
@nornagon it behaves the same (arguably incorrect) way on Windows as it used to on macOS - i believe the solution here is to bring Windows in line with macOS rather than revert the change on Windows. 

From the original issue:

> Fixes an issue where part of the BrowserView could be cut off when calling setBounds on some windows. This was happening because we were not taking the titlebar height into account when calling setBounds on a framed window, which meant that the y-value for the bounds would end up negative.

This same issue happens on Windows (which I missed).

**Comment by nornagon** [comment]
hm... i'm not sure? I don't feel like y=0 should put the browserview underneath the titlebar. also, it's a breaking change because everyone who uses browserview would need to update their code to avoid their app breaking.

**Comment by arman-canva** [comment]
Hi, have there been any further developments with regards to this?

**Comment by StephanU** [comment]
I also think this is a breaking change introduced in the bugfix release v19.0.15:

https://github.com/electron/electron/compare/v19.0.14...v19.0.15#diff-c540c2e05740fa476322f2d34ffc1db3d9e85d8419aa14556af6e97bad2a3611R262

**Comment by davej** [comment]
Here's a hacky solution to normalize the `y` value on Windows and Mac (Linux not tested).

```ts
function getAdjustedY(win: BrowserWindow, y = 0) {
  const winHeight = win.getSize()[1];
  const contentHeight = win.getContentSize()[1];
  const titlebarHeight = winHeight - contentHeight;

  return process.platform === "darwin" ? titlebarHeight + y : y;
}
```

**Comment by RangerMauve** [comment]
Still seeing this in Electron 23. Ty for the fix @davej, gonna try it out.

**Comment by davej** [comment]
Still an issue.
