### ISSUE TITLE
[Bug]: On macOS, `BrowserView`s Are Unexpectedly Draggable & Position Strangely

### ISSUE THREAD

**Issue by arman-canva** [electron/electron#35995]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

20.0.3

### Expected Behavior

Dragging `BrowserView` content should not cause windows to move (unless, of course, encapsulated UI uses `app-drag-region: drag;`).

Additionally, calling `BrowserView::setBounds` w/ `y: 0` should result in the top of the associated `BrowserView` being rendered below any native title bar UI/frames (as opposed to underneath it).

https://user-images.githubusercontent.com/69829015/195234040-4687f81c-55c6-49c3-979f-67728531b4c2.mp4

### Actual Behavior

The top 28 pixels of `BrowserView`s within `BrowserWindow`s that use native title bar UI/frames are draggable.

Additionally, under the same conditions, `BrowserView`s must have `y` > 28 in order to avoid content being rendered beneath native title bar UI.

https://user-images.githubusercontent.com/69829015/195233692-5bc348c8-c0ae-4123-9c79-f18b4c8f1aac.mp4

### Testcase Gist URL

https://gist.github.com/3a00be249d749d5ba4ca04d77e5659ad

### Additional Information

These issues do not occur when [`titleBarOverlay`](https://www.electronjs.org/docs/latest/tutorial/window-customization#window-controls-overlay-macos-windows) is used.

**Comment by arman-canva** [comment]
Hey @clavin, any idea whether this issue is on the Electron team's radar?

**Comment by nornagon** [comment]
cc @codebytere

**Comment by pejman1** [comment]
maybe this issue also related with this one 
https://github.com/electron/electron/issues/35537

**Comment by StephanU** [comment]
I'm not sure whether the Draggable problem and the "28px upshift of the BrowserView" are correlated... I only have the "28px upshift" problem and could narrow it down to the Electron release v19.0.15. Looking in the change logs, there were indeed changes in the handling of the BrowserView for MacOs:

https://github.com/electron/electron/compare/v19.0.14...v19.0.15#diff-c540c2e05740fa476322f2d34ffc1db3d9e85d8419aa14556af6e97bad2a3611R262

**Comment by davej** [comment]
This is still an issue in Electron 23.

**Comment by cathykc** [comment]
Also still an issue in Electron 24! @arman-canva were you able to figure out a work around?

**Comment by codebytere** [comment]
Fixed in https://github.com/electron/electron/pull/36230 starting in v23 - it does not happen on macOS that i'm able to see 24 or 25. 

I'm closing this out as the initial issue was closed, but @davej @cathykc i'm happy to open a new issue or follow up if you're somehow still seeing the initial issue after the above PR.

**Comment by zerosoul** [comment]
I'm facing same problem, but I found it's related to the root BrowserWindow titlebar setting

if I set:
```  javascript
new BrowserWindow({
    titleBarStyle: "hidden",
    titleBarOverlay: true,
    ...
  });
```
hidden draggable areas in browserview appear!
but if I remove: `titleBarStyle` and `titleBarOverlay`, browserview works fine!

WTF?!
