### ISSUE TITLE
[Bug]: Errors about silent printing

### ISSUE THREAD

**Issue by hadesgo** [electron/electron#35996]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.17

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21H2

### What arch are you using?

x64

### Last Known Working Electron version

18.3.15

### Expected Behavior

I want to use contents.print ({silent: true}) to execute the print task only once

### Actual Behavior

Use contents.Print({silent: true}) will be executed twice.
Use the following code to monitor the actual printing times.

```js
window. onbeforeprint = (event) => {
  console. log('before print');
};

window. onafterprint = (event) => {
  console. log('After print');
};
```
This phenomenon will appear in 19 and later versions.

### Testcase Gist URL

https://gist.github.com/feddc9ddf37da270efc034d6ff6431b9

**Comment by codebytere** [comment]
@hadesgo did you forget something in your gist? I see two exposed contextBridge methods but they're never called....?

**Comment by hadesgo** [comment]
@codebytere You can use window.app.doPrint({silent: true}) in DevTools. if you are in version 19, you can see the printed information, and print "before print" and "after print" twice, but you execute window.app.doPrint({silent: true}) in version 18.3.15  will only print the information just now.
