### ISSUE TITLE
[Bug]: can‘t preview before print 

### ISSUE THREAD

**Issue by linkaimeng** [electron/electron#35998]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.1

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Last Known Working Electron version

20.1.1

### Expected Behavior

i have a web system running in chrome borswer well,support preview before print.
i useing electron to create a desktop application.useing **mainWindow.loadURL(winURL)**  winURL is my web system website.
i expected electron can support preview before print.

![image](https://user-images.githubusercontent.com/2948213/195295149-f6cd7668-ec1b-43b1-9d61-52bbe7e284b2.png)

### Actual Behavior

electron doesn't support preview before print.
![image](https://user-images.githubusercontent.com/2948213/195294900-5ba28386-1647-4d29-8f63-9d26a249e218.png)

**Comment by MarshallOfSound** [comment]
Chromium's print-preview UI is not going to be ported into Electron, we do not generate UI only provide methods (E.g. `print()`) You could build this view yourself via `printToPDF` and displaying the PDF inline (which I believe is how print-preview works anyway)

**Comment by chenzihangCMB** [comment]
> ### Preflight Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.
> 
> ### Electron Version
> 20.1.1
> 
> ### What operating system are you using?
> Windows
> 
> ### Operating System Version
> win10
> 
> ### What arch are you using?
> x64
> 
> ### Last Known Working Electron version
> 20.1.1
> 
> ### Expected Behavior
> i have a web system running in chrome borswer well,support preview before print. i useing electron to create a desktop application.useing **mainWindow.loadURL(winURL)** winURL is my web system website. i expected electron can support preview before print.
> 
> ![image](https://user-images.githubusercontent.com/2948213/195295149-f6cd7668-ec1b-43b1-9d61-52bbe7e284b2.png)
> 
> ### Actual Behavior
> electron doesn't support preview before print. ![image](https://user-images.githubusercontent.com/2948213/195294900-5ba28386-1647-4d29-8f63-9d26a249e218.png)
> 
> ### Testcase Gist URL
> _No response_
> 
> ### Additional Information
> _No response_



> ### Preflight Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.
> 
> ### Electron Version
> 20.1.1
> 
> ### What operating system are you using?
> Windows
> 
> ### Operating System Version
> win10
> 
> ### What arch are you using?
> x64
> 
> ### Last Known Working Electron version
> 20.1.1
> 
> ### Expected Behavior
> i have a web system running in chrome borswer well,support preview before print. i useing electron to create a desktop application.useing **mainWindow.loadURL(winURL)** winURL is my web system website. i expected electron can support preview before print.
> 
> ![image](https://user-images.githubusercontent.com/2948213/195295149-f6cd7668-ec1b-43b1-9d61-52bbe7e284b2.png)
> 
> ### Actual Behavior
> electron doesn't support preview before print. ![image](https://user-images.githubusercontent.com/2948213/195294900-5ba28386-1647-4d29-8f63-9d26a249e218.png)
> 
> ### Testcase Gist URL
> _No response_
> 
> ### Additional Information
> _No response_

Have you found a solution to this question? I have the same requirement for PDF printing preview as you do.

**Comment by czy132** [comment]
> 
Have you found a solution? Can you share it? Thank you

**Comment by haohaodushu** [comment]
Have you found a solution? Can you share it? Thank you
