### ISSUE TITLE
Datalist elements do not work

### ISSUE THREAD

**Issue by maufl** [electron/electron#360]
I tried to use the datalist element for auto completion of an input field but I can't make it work.
I stripped down my HTML file to be sure nothing interferes. 

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <input type="text" list="modules" />
  <datalist id="modules">
    <select>
      <option value="IN4NWK"></option>
      <option value="IN4CDT"></option>
      <option value="IN4INS"></option>
    </select>
   </datalist>
</body>
</html>
```

My main Javascript file does nothing but open a browser window and loading this HTML. Now when you start typing an "I" or press the down key in the input field, nothing happens.

Did I overlook something? The WebKit version used in atom-shell should support it.

Regards

**Comment by julianah** [comment]
on electron-v0.27.3.darwin-x64 'list' in document.createElement('input') &&
             'options' in document.createElement('datalist') is true

**Comment by seanzer** [comment]
+1

**Comment by kevin-smets** [comment]
+1. Just encountered this, the code works fine in the Chrome (v46) but not in Electron (v0.34.3).

**Comment by xbl** [comment]
+1

**Comment by KevinMartin** [comment]
@zcbenz since you had [fixed this in NW.js](https://github.com/nwjs/nw.js/commit/f98226c54d2b56bb27eb3c3f0049c2a262c800e9), is it possible to port that over to Electron easily?

**Comment by Bratkartoffl** [comment]
@zcbenz same here.. just stumbled accros this bug. Maybe you could fix it? Would much apprciate it!

**Comment by harryzzp** [comment]
+1

**Comment by buschtoens** [comment]
Try setting `webPreferences.experimentalFeatures = true` for your `BrowserWindows`. It's apparently just like flipping the `enable-experimental-web-platform-features` switch, as it enables grid layouts. :smiley:

**Comment by averagehat** [comment]
Can anyone confirm that this works in experimental mode? Not working for me.

**Comment by tdinger-ibm** [comment]
Setting `webPreferences.experimentalFeatures = true` for the `BrowserWindow` is not working for me either.

**Comment by willnwhite** [comment]
It's not looking good. I'm abandoning this feature in my UI and I'll have to see if Atom can do it natively.

**Comment by Yishengtang** [comment]
+1

**Comment by ezwiebel** [comment]
Having the same issue... Is it still under inspection or identified?

**Comment by brenca** [comment]
I've checked the current implementation in Chromium, and a lot has changed since the aforementioned nw.js implementation was created, things related to the `datalist` tag has been moved closer together with autofill related stuff, and the whole thing was moved out of WebKit and implemented in a separate component. I might experiment a bit more with this, but the solution might take a while (things missing from current libchromiumcontent, so those have to be included there, etc.). I'll try to keep you guys updated.

**Comment by brenca** [comment]
So, the update: I've tried to solve this with a minimal footprint in my spare time, but I didn't have much luck. Using the implementation in `chrome` would bring in a looot of other components (that implementation combines datalist, autocomplete and password/creditcard fill functionality, it in itself is huuge, and requires components like `webdata`, because it originally was created to communicate with google servers.). I gave up pursuing this route, since I ran into a dependency on protoc stuff, and I don't even really know what that is, but [this](https://github.com/electron/libchromiumcontent/pull/223) PR disables it explicitly, and I didn't want to create trouble with reenableing them.
I'll try to create a subset of the stuff that's required, and create a custom implementation, if I can.

**Comment by arifcakiroglu** [comment]
@zcbenz is it still under inspection?

**Comment by timerg** [comment]
+1

**Comment by linquize** [comment]
Electron 1.4.15 still have this issue

**Comment by korneliakobiela** [comment]
+1

**Comment by avighier** [comment]
I don't know if "+1" it's a good practice, but ...

+1

**Comment by enlight** [comment]
@avighier It's not, there's a button to **add your reaction** to the original comment, use it. Spamming issues with zero-content comments is rude and accomplishes nothing of value.

**Comment by metjeanjunior** [comment]
[awesomplete](https://github.com/LeaVerou/awesomplete) is an alternative for the time being.  Can confirm that it works with the following syntax:
`<input class="awesomplete"
       data-minchars="1"
       data-maxitems="5"
       data-list="China, India, Japan, Russia, UK, USA" />
` but I haven't gotten around to testing the rest of their API.

**Comment by ellis** [comment]
@metjeanjunior Thanks for the suggestion!  Unfortunately, it's not working for me.  I'm using electron 1.4.15 and awesomplete 1.1.1.  I copied the exact code you showed, and verified in the developer console that the awesomplete CSS and JS files are properly loaded, and the INPUT tag appears to be modified by awesomplete.  Still, no autocomplete.  Which versions are you running?

**Comment by Shahor** [comment]
I'm sorry, I'll be the annoying one here but the bug still exists on current version of electron and it seems like this issue is not getting attention anymore :(

**Comment by bellbind** [comment]
FYI: I made a tiny workaround script "inputlistpopup.js" injecting datalist selector as a popup menu. 

- https://gist.github.com/bellbind/0bc2bb6fd3392f93529504879d335fc9

No special Renderer code required except `<script defer>` tag in HTML or `webContents.executeJavaScript()` in Main code.

**Comment by zcbenz** [comment]
I'm keeping this opened since it has not been implemented for macOS.

**Comment by Lindenk** [comment]
Assuming that last merge made it into the 1.7.2 release, this is also a problem on linux.

**Comment by hollowdoor** [comment]
I get a drop down with datalist, but when I select an option from the drop down the `input.value` is not updated. The visible html input field is changed, but the value property still does not change.

Other activities do change the value. For instance if I press a letter key the value property of input does change.

The input event is also not fired on the input element on datalist selection. Which is another problem being that all the answers on stackoverflow about how to get the value from `input.value` after datalist selection suggest using the input event on the input element.

I'm using Linux, and electron 1.7.5

When testing I tried click, and arrow->enter to select from the datalist. Nether fired the input event. Neither updated the `input.value` value.

**Comment by brenca** [comment]
@hollowdoor this was also reported here ( #9860 ), and a fix is on the way here ( #10510 )

**Comment by SrinathG910** [comment]
Is this fixed? `npm update electron` didn't fix the issue for me?

**Comment by angrymarker** [comment]
any update on this? below code is pretty much ignored by electron
```
<datalistclass="dropdown">
<option>Volvo</option>
<option>Saab</option>
<option>Mercedes</option>
<option>Audi</option>
</datalist>
```

**Comment by sidgo28** [comment]
Any update?

**Comment by codebytere** [comment]
This should now be resolved by https://github.com/electron/electron/pull/10510.

**Comment by DoomyTheFroomy** [comment]
@codebytere I'm not sure if this was correct to be closed! 

> I'm keeping this opened since it has not been implemented for macOS.

I had a try with 2.0.10 on a macOs and it was not working!?

**Comment by saghul** [comment]
@codebytere Please reopen, this is not fixed on macOS.

**Comment by brenca** [comment]
So current status for those who are interested: @zcbenz told me a while back he would take a look at this on Mac, but I think he didn't have time to come around and do it. It should work on Windows, and I haven't tested it on any other platform.

I don't own a Mac and so my objc++ is as good as my old norse, so it might take some time for me to do this on Mac, but if I can get my hands on a machine, I might take a look at this in my spare time.
