### ISSUE TITLE
[Bug]: BrowserView is initially transparent on some webpages since Electron v15.3

### ISSUE THREAD

**Issue by mckravchyk** [electron/electron#36014]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.1.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux 5.19.7, Mac OS 11.5.2 (x64)

### What arch are you using?

x64

### Last Known Working Electron version

15.2.0

### Expected Behavior

A BrowserView should never be transparent by default

### Actual Behavior

A BrowserView is sometimes transparent despite not being configured to, it depends on the webpages that's loaded. Sometimes the bug disappears upon further navigation. There's also an issue with tearing upon navigation which seemed to arrived at around the same point (tested on Linux, on Mac OS it does not seem to occur).

I have discovered 3 different behaviours depending on OS and configuration. There's probably more.

*Affected webpage* - is a page which does not set a background colour on its outer viewport

The below are steps to reproduce, using the testcase demo fiddle app linked below.

**Linux - regular config**
1. Load an affected webpage (Hacker News)
2. Notice that the outer layer of the viewport is completely transparent (shows the background of the renderer)
3. Keep navigating within it and notice that the bug persists
4. Navigate to another affected page (test page) and notice that the bug persists
5. Navigate back to Hacker News and notice that the issue persists
6. Navigated to a non-affected page (Google) and back to an affected page. The BrowserView has been "cured", the bug does not occur any more within that view
 
**Linux - setting transparent: false**
1. Uncomment the `transparent: true,` line of the tabView config in `main.js` and run the demo
2. Load an affected page (Hacker News or Test Page)
3. Load an unaffected page (Google)
4. Load an affected page. Notice that the BrowserView has not been "cured". Ironically, setting transparent: false does the opposite to help.

**Mac OS - regular config**
1. Load an affected webpage (Hacker News)
2. Navigate around Hacker News, notice that the bug persists
3. Load Test Page and notice that the BrowserView is free from the bug

I did not test how it behaves with transparent: false on Mac OS and I did not test Windows at all.

Separately there's an issue with screen tearing during navigation on Linux  which started to occur together with that issue. Try navigating around Hacker News in the fiddle app.

### Testcase Gist URL

https://github.com/mckravchyk/electron-browserview-transparency-bug-fiddle

### Additional Information

I believe a viable temporary workaround (in an app which is structured similarly as the demo) is to set the background colour on the section in the renderer that renders just below the viewport to be white, I have yet to apply it in practice though. However, there's no workaround for tearing.

**Comment by mckravchyk** [comment]
Tearing during navigation seems to be a separate bug. It does not seem to occur on Mac OS and the last working version on Linux was 16.0.10 I don't think it's related to the transparency issue.

**Comment by mckravchyk** [comment]
I applied a workaround to set the background colour of the BrowserWindow to white after the app finishes initializing which makes this issue not noticeable. However, I have just noticed (on Linux) that when I open the dev tools, the affected page's background turns dark gray (same color as the dev tools background), despite the BrowserWindow underneath having a white background.

**Comment by Mad-hu** [comment]
![image](https://user-images.githubusercontent.com/13977755/202104422-cbb83770-05db-44a2-a39e-ff9914dedce8.png)
