### ISSUE TITLE
[Bug]: Cannot require / import native node modules in preload.js

### ISSUE THREAD

**Issue by MarMun** [electron/electron#36012]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.1 LTS

### What arch are you using?

x64

### Last Known Working Electron version

19.0.8

### Expected Behavior

I try to import / require the 'path' node module inside preload.js of the [electron-quick-start](https://github.com/electron/electron-quick-start):

```
const path = require('path') // <----------------------

window.addEventListener('DOMContentLoaded', () => {
  const replaceText = (selector, text) => {
    const element = document.getElementById(selector)
    if (element) element.innerText = text
  }

  for (const type of ['chrome', 'node', 'electron']) {
    replaceText(`${type}-version`, process.versions[type])
  }
})

```

Expected: The import works.

### Actual Behavior

The import fails:

```
VM56 sandbox_bundle:93 Unable to load preload script: /home/me/Dev/electron-quick-start/preload.js
(anonymous) @ VM56 sandbox_bundle:93
./lib/sandboxed_renderer/init.ts @ VM56 sandbox_bundle:93
__webpack_require__ @ VM56 sandbox_bundle:1
(anonymous) @ VM56 sandbox_bundle:1
___electron_webpack_init__ @ VM56 sandbox_bundle:1
(anonymous) @ VM56 sandbox_bundle:160

VM56 sandbox_bundle:93 Error: module not found: path
    at preloadRequire (VM56 sandbox_bundle:93:1386)
    at <anonymous>:9:14
    at runPreloadScript (VM56 sandbox_bundle:93:2211)
    at Object.<anonymous> (VM56 sandbox_bundle:93:2478)
    at ./lib/sandboxed_renderer/init.ts (VM56 sandbox_bundle:93:2632)
    at __webpack_require__ (VM56 sandbox_bundle:1:170)
    at VM56 sandbox_bundle:1:1242
    at ___electron_webpack_init__ (VM56 sandbox_bundle:1:1320)
    at VM56 sandbox_bundle:160:455
(anonymous) @ VM56 sandbox_bundle:93
./lib/sandboxed_renderer/init.ts @ VM56 sandbox_bundle:93
__webpack_require__ @ VM56 sandbox_bundle:1
(anonymous) @ VM56 sandbox_bundle:1
___electron_webpack_init__ @ VM56 sandbox_bundle:1
(anonymous) @ VM56 sandbox_bundle:160
```

### Additional Information

node version v16.17.1

**Comment by Prinzhorn** [comment]
https://github.com/electron/electron/issues/35587
https://github.com/electron/electron/issues/35584
https://github.com/electron/electron/issues/35387
https://github.com/electron/electron/issues/35713

https://github.com/electron/electron/issues/35589

**Comment by clavin** [comment]
As @Prinzhorn helpfully pointed out, this issue has come up a handful of times and has its own meta issue: #35589. Closing as a duplicate, please refer to that issue for future discussion on this topic. Thanks for the report!
