### ISSUE TITLE
[Bug]: WebContents.opener is undefined for windows opened via links with target=_blank

### ISSUE THREAD

**Issue by mgalla10** [electron/electron#36025]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Expected Behavior

If a new window is opened via a programmatic call to `window.open()`, that window's `webContents.opener` provides a reference to the frame that opened that window. I would expect the same behavior for new windows opened via links with target="_blank".

### Actual Behavior

For new windows opened via links with target="_blank", the window's `webContents.opener` is undefined. The opener is provided as expected if the target is a specified frame name (which doesn't already exist).

### Testcase Gist URL

https://gist.github.com/8dc8da58f36238db0ef950a0a1d639d9

**Comment by codebytere** [comment]
cc @samuelmaddock given this refs https://github.com/electron/electron/pull/35140

**Comment by samuelmaddock** [comment]
This is expected behavior when using `[target=_blank]`. It can be avoided by adding a `rel="opener"` attribute.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target

> Note: Setting target="_blank" on <a> elements implicitly provides the same rel behavior as setting [rel="noopener"](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener) which does not set window.opener.

I only learned about this when writing the tests for this API:

https://github.com/electron/electron/blob/23d4a252c69f68c576933d745a95b70bad2946df/spec/api-web-contents-spec.ts#L1302-L1329

**Comment by pushkin-** [comment]
@samuelmaddock huh, so even Electron isn't able to access/know the window that opened the child window? I'm not totally following how they're connected. If I window.open a window but disable window.opener, won't webContents.opener still give me the correct result? So how is that different from a link that opens a window with window.opener disabled.

**Comment by samuelmaddock** [comment]
> @samuelmaddock huh, so even Electron isn't able to access/know the window that opened the child window? I'm not totally following how they're connected. If I window.open a window but disable window.opener, won't webContents.opener still give me the correct result? So how is that different from a link that opens a window with window.opener disabled.

`WebContents.opener` is the main process equivalent of `window.opener` ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/opener)).

If `window.open(url, name, 'noopener')` is set, `WebContents.opener` will be null as seen in the tests:

https://github.com/electron/electron/blob/23d4a252c69f68c576933d745a95b70bad2946df/spec/api-web-contents-spec.ts#L1286-L1301
