### ISSUE TITLE
Add Session::SetUserAgent

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#3602]
`WebContents::SetUserAgent` only sets user agent for one page, we should add a way to set user agent for the whole session.

**Comment by bitwombat** [comment]
I think it userAgent persists across pages (links) just not to new windows.

Any suggested workarounds in the meantime?

**Comment by ragingwind** [comment]
I was digging to add `SetUserAgent` to Session but I couldn't find any point of sharing session between the parent window and newly created BrowserWindow. [Calling setUserAgent of webContents of guest borwser before `loadURL`](https://github.com/atom/electron/blob/master/atom/browser/lib/guest-window-manager.js#L57) is the simple way to solve the #3523 issue. but I'm not sure.
