### ISSUE TITLE
Enable crashpad support on linux for ELECTRON_RUN_AS_NODE processes

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#36030]
Refs https://github.com/electron/electron/pull/35900/commits/b10f24386cb37d736b10f4831235eedcf1f0db4b

 Node.js forked child processes have been relying on breakpad for crash report generation, with https://chromium-review.googlesource.com/c/chromium/src/+/3764621 Linux has moved onto crashpad completely. For these processes to act as crashpad clients, they need the following

* Inherit FD for the handler process communication, which is usually inherited by the chromium spawned child processes via `ElectronBrowserClient::GetAdditionalMappedFilesForChildProcess`. For Node.js the fork is performed by Libuv, we should pass it via stdio option of child_process.fork. The descriptor will eventually be looked up in [PlatformCrashpadInitialization](https://source.chromium.org/chromium/chromium/src/+/main:components/crash/core/app/crashpad_linux.cc;l=197). Also we will need to setup `base::GlobalDescriptors` instance in the child process.

* Pass the PID of the handler process to the child process via the command line flag `--crashpad-handler-pid/crash_reporter::switches::kCrashpadHandlerPid` whose value can be extracted with the same API to obtain the FD [crash_reporter::GetHandlerSocket](https://source.chromium.org/chromium/chromium/src/+/main:components/crash/core/app/crashpad.h;l=236).

**Comment by jkleinsc** [comment]
Additionally the test disabled here needs to be re-enabled:
https://github.com/electron/electron/commit/b10f24386cb37d736b10f4831235eedcf1f0db4b#diff-1f2c4205feb14a9585893fbd543c5209a4f56dcac2b6905599f70c79f22f68f3L169
