### ISSUE TITLE
[Bug]: nativeTheme API not supported on Fedora 37 (GNOME 43)

### ISSUE THREAD

**Issue by joeljosedev** [electron/electron#36040]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.1.1

### What operating system are you using?

Other Linux

### Operating System Version

`Linux fedora 5.19.14-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 5 21:31:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### What arch are you using?

x64

### Expected Behavior

Electron apps must follow the default theme used by the OS.

### Actual Behavior

Electron apps only use a light theme even when the system uses a dark theme.

### Additional Information

# Screenshots

## System Information
![Screenshot from 2022-10-16 18-44-47](https://user-images.githubusercontent.com/53969297/196037729-6b0feb4d-fb4f-44e6-aea4-e5acd7c1c04b.png)

## GNOME Shell version
![Screenshot from 2022-10-16 18-52-45](https://user-images.githubusercontent.com/53969297/196037848-99877f90-850a-4629-bb61-e804c1465487.png)

## Running [electron-quick-start](https://github.com/electron/electron-quick-start) app
![Screenshot from 2022-10-16 18-43-54](https://user-images.githubusercontent.com/53969297/196037733-7fea995a-c463-484d-a0e3-2b6bf90970c4.png)

**Comment by slynobody** [comment]
there are a bunch of open issues on this bug at electron-apps (like signal and others), all pointing back to electron itself.

you simply cant change the theme of electron-apps on konsole or os-level currently (electron is the last platform on linux with this problem) which renders all external tools on this useless. 
is there any news on this?

Maybe one should also take a look at all the issues opened on this or similar bugs: https://github.com/electron/electron/issues?q=is%3Aissue+is%3Aopen+system+theme

**Comment by codebytere** [comment]
Combining with https://github.com/electron/electron/issues/33635
