### ISSUE TITLE
[Feature Request]: Support `windowControlsOverlay` inside BrowserViews

### ISSUE THREAD

**Issue by rf-figma** [electron/electron#36058]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If you nest a BrowserView inside a BrowserWindow that was created with `titleBarOverlay` set to `true`, the `navigator.windowControlsOverlay` API is available inside the BrowserView but doesn't contain any useful information:

<a href="https://gist.github.com/rf-figma/7ff070837c1c6de764a953ef5270e125"><img width="690" alt="navigator.windowControlsOverlay.getTitlebarAreaRect() returning an empty rectangle inside a BrowserView" src="https://user-images.githubusercontent.com/114442851/196258616-800884e8-a55d-4c11-9e39-7a54c7ac4524.png"></a>

This makes it difficult to use `titleBarOverlay` in apps that use multiple BrowserViews per BrowserWindow.

### Proposed Solution

It would be helpful if `windowControlsOverlay` accurately reflected the area of overlap between the window controls and the BrowserView.

### Alternatives Considered

* There could be APIs on BrowserWindow for querying the most recent `windowControlsOverlay` information and subscribing to changes to it. This would also solve the problem; it would just require more boilerplate to then send that information manually to the BrowserView.

* `windowControlsOverlay` for BrowserViews could contain the same information as in the parent BrowserWindow. This would work for our specific use case (where the BrowserView is anchored to the top of the window anyway) but doesn't seem great as a general solution.

**Comment by dsanders11** [comment]
Hi @rf-figma 👋 Thanks for the quality issue.

This seems like a duplicate of #34947, or at least very similar. Could you take a look and if it is a dupe close this issue so we can track it in one spot? Thanks!

**Comment by rf-figma** [comment]
Hi @dsanders11! You're right, this is a dupe, good catch. Happy to close it out.
