### ISSUE TITLE
[Bug]: Electron crash during startup on WSL2 Ubuntu 18.4

### ISSUE THREAD

**Issue by YuriL180821** [electron/electron#36066]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 18.4

### What arch are you using?

x64

### Last Known Working Electron version

16.0.0

### Expected Behavior

Electron does not crash during start without parameters

### Actual Behavior

Electron crashes in the begining of the ContainMain

### Testcase Gist URL

https://github.com/electron/electron

### Additional Information

Typical testing configuration leads to app crash during startup

https://user-images.githubusercontent.com/89125090/196456222-759b61b6-1f32-4227-b7b7-cbbfe69d4446.mp4

**Comment by clavin** [comment]
Was anything printed to stdout/stderr? Naïvely, I see `base/logging.cc` and the mention of `SIGTRAP` in your screen capture and that looks like a failed `CHECK` to me causing the crash deliberately. There might be more info there.

Also, I'm not sure that WSL2 is technically a platform we officially support.

**Comment by YuriL180821** [comment]
Hello @clavin electron start was crashed because --no-sandbox option was not set. As far as I understood this option is mandatory but more, as far as I understood error messages we have to start electron only as root. 

STDERR contains next: ` Running as root without --no-sandbox is not supported.` 
All my starts into not root mode crashed too.

WSL is enough near analog of Linux and this is not a root cause.
