### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vhansanti** [electron/electron#36110]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0

### What operating system are you using?

Other (specify below)

### Operating System Version

Android Chrome

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

16.0

### Expected Behavior

[https://github.com/electron/electron.git](url)

### Actual Behavior

  **#`**

### Testcase Gist URL

https://github.com/electron/electron.git

### Additional Information

[https://github.com/electron/electron.git](url)

**Comment by RonBis** [comment]
What's the bug about? You didn't specify anything.
