### ISSUE TITLE
[Bug]: electron browserwindow show "garbled"

### ISSUE THREAD

**Issue by mqliutie** [electron/electron#36117]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.2.3

### What operating system are you using?

macOS

### Operating System Version

mac osx 12.5.1

### What arch are you using?

x64

### Expected Behavior

show correctly

### Actual Behavior

garbled

### Additional Information

![image](https://user-images.githubusercontent.com/11795518/197437139-e236fe3b-2446-4d3d-b842-72f38784d350.png)

When show another window the error message will be shown until restar the app.

**Comment by codebytere** [comment]
Electron v12 is no longer supported and has not been for a while. If this issue appears on a supported version, we can re-open this issue.

**Comment by deermichel** [comment]
@mqliutie does this happen when an update is running in the background? My guess is the app starts from the old binary, but while running the inital execution the binary gets replaced and it ends up in undefined behavior (try monitoring the ShipIt process in task manager when auto-updating).

**Comment by mqliutie** [comment]
> @mqliutie does this happen when an update is running in the background? My guess is the app starts from the old binary, but while running the inital execution the binary gets replaced and it ends up in undefined behavior (try monitoring the ShipIt process in task manager when auto-updating).

Yes, it usually happens after an upgrade
