### ISSUE TITLE
[Bug]: window.print does nothing when printing a page with one or more embedded PDFs

### ISSUE THREAD

**Issue by markleutloff** [electron/electron#36124]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.14, 20.1.0, 21.1.0, 21.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21H2

### What arch are you using?

x64

### Expected Behavior

Executing window.print() should open the printing settings dialog and execute the print of the page.

### Actual Behavior

When calling window.print() on a page with one or more embedded PDFs, nothing happens. No error or anything else is displayed.

### Testcase Gist URL

https://gist.github.com/d4cbec95f4ec334b22d5d8a04060b699

### Additional Information

window.print works when printing a page whichs whole content is a pdf (https://www.orimi.com/pdf-test.pdf)
window.print works when printing a page without a PDF
window.print does **not** work when trying to print a page with embedded pdfs (https://pdfobject.com/static/)
webContents.print() works in every case, but is not blocking the execution flow of the page (which window.print does)

window.print also does not work when printing a page with other embedded extension content. For example, in my case I have a own extension which behaves similar to the PDF extension. This bug has been reproduced without a own extension and just the default PDF extension.

**Comment by codebytere** [comment]
@markleutloff it seems this is an upstream bug. If you open Google Chrome and navigate to https://pdfobject.com/static/, then open the DevTools console and run `window.print()` you'll see there is no response there either. You should instead open this at crbug.com and when they fix it, we will inherit the fix.
