### ISSUE TITLE
[Bug]: Disabling context isolation breaks vibrancy on macOS

### ISSUE THREAD

**Issue by npezza93** [electron/electron#36126]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21

### What operating system are you using?

macOS

### Operating System Version

monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Using the BrowserWindow options of 
```
{
  width: 600,
  webPreferences: { contextIsolation: false },
  vibrancy: 'fullscreen-ui',
  transparent: true
}
```
I would expect the window to be semi transparent. 

### Actual Behavior

A solid background color is instead applied. Toggling contextIsolation to true makes the window transparent but making it false ignores the vibrancy option.

**Comment by deermichel** [comment]
Unable to repro under v21.2.0, macOS Ventura 13.0 - can you try the repro in [Fiddle](https://www.electronjs.org/fiddle) and upload a gist if there's a 100% repro, Thank you! :)

**Comment by npezza93** [comment]
Yea I don't know what was happening here. It seems to be working correctly now. Sorry about that!
