### ISSUE TITLE
[Bug]: Print options don't work on windows (webContents.print)

### ISSUE THREAD

**Issue by joannaFlw** [electron/electron#36156]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

to have the custom options which I'm passing to print like which printer and page size and margins

### Actual Behavior

it's taking the default printer with the default settings

**Comment by joannaFlw** [comment]
note: It's working fine on Mac, this issue is happening only for windows

**Comment by deermichel** [comment]
@joannaFlw Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? A testcase for [Electron Fiddle](https://www.electronjs.org/fiddle) would be very helpful for comparison purposes. It is a great tool for making small test cases in general, and makes it easy to publish your test case to a [gist](https://gist.github.com/) that Electron maintainers can use.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a follow-up comment.

Thanks a lot :)
