### ISSUE TITLE
[Bug]: window.open() opens two tabs

### ISSUE THREAD

**Issue by fredrikj** [electron/electron#36164]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3

### What operating system are you using?

macOS

### Operating System Version

Big Sur

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

13.6.1

### Expected Behavior

In an electron window, I open the chrome devtools. In the console, I write
window.open('http://google.com')
I expect my browser to open one tab on that address.

### Actual Behavior

My Chrome web browser opens two tabs at the address.

**Comment by fredrikj** [comment]
This was caused by our code having listener to events "new-window" and "will-navigate", both calling `shell.openExternal`. Hence, not an electron bug.

**Comment by HLHAOGH** [comment]
How to share sessionStorage when opening multiple windows with window. open
