### ISSUE TITLE
能否 禁用win.show()时窗口动画

### ISSUE THREAD

**Issue by WZY1999428** [electron/electron#36181]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

我使用BrowserWindow 自定义 Tray 的右键菜单时出现动画看起来很奇怪，能否禁用动画呢

### Proposed Solution

建议BrowserWindow 添加一个禁用显示动画的参数

### Alternatives Considered

.

**Comment by MarshallOfSound** [comment]
That animation happens at the OS level, you can not disable it

**Comment by fanchenio** [comment]
@MarshallOfSound I set thickFrame to false to cancel the animation, but so does the shadow, which doesn't make sense.
