### ISSUE TITLE
[Bug]: Not able to find an event in Windows snap for side-by-side viewing

### ISSUE THREAD

**Issue by VigneshSonaiya** [electron/electron#36183]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

21.1.0

### Expected Behavior

It should have any atleast single event to know when windows has snapped

### Actual Behavior

Couldn't find any event for snapping windows

**Comment by VigneshSonaiya** [comment]
This is what I mean snapping in windows 11. When you enable title bar you should have these feature if window is set to resizable
![image](https://user-images.githubusercontent.com/47246527/198577104-0523eecd-14bc-4f0f-94e1-1b8bd70ca1ec.png)

**Comment by nornagon** [comment]
I don't believe Windows itself offers any such events; you'll have to listen to the window resizes.
