### ISSUE TITLE
error while loading shared libraries: libgbm.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by ThenWang** [electron/electron#36197]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 16.04.2

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

3.1.8

### Expected Behavior

It is hoped that the application on the armv7l architecture machine can be opened and run normally.

### Actual Behavior

It can be packaged normally using the command `electron-builder --armv7l`. But when the application is opened, an error  `error while loading shared libraries: libgbm.so.1: cannot open shared object file`  is reported. Electron3.1.8 works well, but v13.1.8 has 
same problem.

**Comment by VerteDinde** [comment]
@ThenWang It sounds like this may be an issue with electron-builder, which is maintained by a slightly different team that electron core. Would you mind filing an issue in that repo?

**Comment by ThenWang** [comment]
> Could you please check if libgbm.so is at the correct path location in your OS? I think I faced a similar problem

This library does not exist on my OS. It reported an error ‘Segmentation fault’ when I tried to add one. It work well when i adjust electron to v3.1.8. Maybe it's really an issue whit electron-builder.

**Comment by ThenWang** [comment]
> Could you please check if libgbm.so is at the correct path location in your OS? I think I faced a similar problem

This library does not exist on my OS. It reported an error ‘Segmentation fault’ when I tried to add one. It work well when i adjust electron to v3.1.8. Maybe it's really an issue whit electron-builder.

**Comment by ThenWang** [comment]
> @ThenWang It sounds like this may be an issue with electron-builder, which is maintained by a slightly different team that electron core. Would you mind filing an issue in that repo?

I think so. I will fill an issue in electron-builder. Thanks.
