### ISSUE TITLE
[Bug]: WCO on a high-DPI display with 175% scaling has incorrect height

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#36200]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

WCO should have the same pixel height as specified when creating the window and thus should align nicely with the CSS height of the custom titlebar underneath it.

### Actual Behavior

![image](https://user-images.githubusercontent.com/79877362/199101053-cc287e83-4140-4d77-8be3-b906ae2b72ae.png)

WCO is substantially taller than the underlying CSS that has exactly the same pixel height specification.

### Additional Information

See: https://github.com/signalapp/Signal-Desktop/issues/6157

**Comment by codebytere** [comment]
@indutny-signal do you also notice this with Chromium itself?

**Comment by indutny-signal** [comment]
@codebytere great question, asked original reporter.

**Comment by indutny-signal** [comment]
@codebytere the user claims that Chromium doesn't have the same issue https://github.com/signalapp/Signal-Desktop/issues/6157#issuecomment-1308583499

**Comment by indutny-signal** [comment]
I believe we still have reports of this coming in. Bump.

**Comment by kass-kass** [comment]
Small update: This still happens for me (W11 22H2, 175% scaling), for latest versions of both Signal 6.10.1 (uses Electron 22.2.0) and VS Code 1.76.2 (uses Electron 19.1.11).
