### ISSUE TITLE
[Bug]: "[object DOMException]", source: devtools://devtools/bundled/ui/legacy/components/color_picker/color_picker.js (1)

### ISSUE THREAD

**Issue by wldssm** [electron/electron#36203]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.1

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Last Known Working Electron version

15.3.0

### Expected Behavior

I need to use the color picker on the devTools to pick up colors when I debug dom style.

### Actual Behavior

color_picker fails to work on devTools. and the console will report an error: "[object DOMException]", source: devtools://devtools/bundled/ui/legacy/components/color_picker/color_picker.js (1)

**Comment by nornagon** [comment]
Regressed in https://github.com/electron/electron/compare/v20.0.0-nightly.20220517...v20.0.0-nightly.20220518, likely in the Chromium roll: https://github.com/electron/electron/pull/33906

**Comment by wldssm** [comment]
您好！      邮件已接收！谢谢！

**Comment by wldssm** [comment]
您好！      邮件已接收！谢谢！

**Comment by wldssm** [comment]
您好！      邮件已接收！谢谢！
