### ISSUE TITLE
Workaround for globalShortcut disabling native OS shortcuts

### ISSUE THREAD

**Issue by T31K** [electron/electron#36204]
Hi everyone, I see that many have encountered this problem whereby `globalShortcut` will take precedence over the default shortcuts in the OS.

eg. binding Cmd + S will render user unable to Cmd + S on any other app.

Workaround:

Use robotjs to send a keystroke that you've just "disabled"

```js
import robot from 'robotjs'

function initGlobalShortcuts () {
  globalShortcut.register(`command+o`, () => {
    robot.keyTap("o", ['command'])
    // do whatever you want
  })
```

**Comment by Slapbox** [comment]
Interesting workaround, but robotjs appears to be abandoned, and I'd be wary of abandonware with input capabilities on the users' machines.

**Comment by QarthO** [comment]
> > Interesting workaround, but robotjs appears to be abandoned, and I'd be wary of abandonware with input capabilities on the users' machines.
> 
> There's a forked version that's newly maintained now https://www.npmjs.com/package/@jitsi/robotjs

This workaround doesn't work with macos when using this fork.
Haven't been able to test on windows. Not sure if it worked on the original robotjs package

**Comment by QarthO** [comment]
> > > Interesting workaround, but robotjs appears to be abandoned, and I'd be wary of abandonware with input capabilities on the users' machines.
> > 
> > 
> > There's a forked version that's newly maintained now https://www.npmjs.com/package/@jitsi/robotjs
> 
> This workaround doesn't work with macos when using this fork. Haven't been able to test on windows. Not sure if it worked on the original robotjs package

Decided to write my own package for creating globalshortcuts that don't disable native OS shortcuts
https://www.npmjs.com/package/qhotkeys
