### ISSUE TITLE
Getting Error when trying to rebase the branch with Master

### ISSUE THREAD

**Issue by amit12m** [electron/electron#36235]
Hi,

When I am using below command :   
**_git rebase -i master_**

 I am getting below Error:
**_[27256:1102/145651.076:ERROR:service_worker_storage.cc(1904)] Failed to delete the database: Database IO error_**

![image](https://user-images.githubusercontent.com/20192544/199454909-a67d0bf0-1181-41e5-834a-b62941ad269c.png)

**Comment by nornagon** [comment]
This is not an Electron issue.
