### ISSUE TITLE
how to reload webview when preload or src changes?

### ISSUE THREAD

**Issue by limerickgds** [electron/electron#36233]
webview preload not working when preload is initially empty。Even if the webview src or preload is subsequently modified
```jsx
<webview
          src={this.props.url}
          ref={this.webviewRef}
          disablewebsecurity="true"
          webpreferences="contextIsolation=no"
          preload={`${this.state.preload}`}
 />
```
BrowserWindowConstructorOptions:
```js
{
    autoHideMenuBar: false,
  webPreferences: {
    nodeIntegration: true,
    webviewTag: true,
    contextIsolation: false,
    webSecurity: false,
  },
}
```

system : macos 12.6 
electron: 21.2.0

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
