### ISSUE TITLE
[Bug]: Inconsistent Behavior when using webContents.send and ipcRenderer.on

### ISSUE THREAD

**Issue by Arbenit** [electron/electron#36248]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^21.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21H2

### What arch are you using?

x64

### Last Known Working Electron version

13.1.8

### Expected Behavior

Consistent Behavior when using  webContents.send and ipcRenderer.on (See actual Behavior for example)

### Actual Behavior

When sending an object using IPC sometimes it correctly emits and is received other times it doesn't. This started happening after I upgraded from 13.1.8. I have cut the project down to what I think is the minimum required code to showcase it. I have also added a video to the repo showcasing the bug. 

### Testcase Gist URL

https://github.com/Arbenit/Electron-bug

**Comment by qq790880208** [comment]
electron version = 13.5.1

即使不发送对象，发送或接收字符串是否也会出现该问题？
一般这种情况在Electron进程切换到后台过长时间后触发，ipcRenderer无法向ipcMain发送消息，但是可以接收ipcMain的消息。

**Comment by Arbenit** [comment]
This happens on start up during `app.whenReady().then(() =>`  and its sending the object from main to renderer. I help that answers your question.

**Comment by qq790880208** [comment]
> 

感谢🙏
