### ISSUE TITLE
[Bug]: Focusing devtools manually doesn't work

### ISSUE THREAD

**Issue by ianstormtaylor** [electron/electron#36244]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.3

### What operating system are you using?

macOS

### Operating System Version

macOS 12 (Monterey)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Based on the answer in https://github.com/electron/electron/issues/4614, you should be able to focus a devtools window that is already open (but potentially behind other windows) by doing:

```ts
require('remote').getCurrentWindow().devToolsWebContents.focus();
```

But this doesn't do anything.

### Actual Behavior

Nothing happens.

**Comment by codebytere** [comment]
@ianstormtaylor does this also happen without use of the remote module? e.g. if you use IPC and focus the devtools webContents from the main process, does this also happen?

**Comment by ianstormtaylor** [comment]
@codebytere thanks for the quick reply. Nope, the `devToolsWebContents.focus()` approach doesn't work for me either. It just keeps the devtools unfocused behind the current window.

**Comment by seahindeniz** [comment]
bump

**Comment by codebytere** [comment]
I still can't reproduce this on macOS. I"m using the following code:

https://gist.github.com/651bc104c28a7bfa67cc78c2a57be8a2

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
