### ISSUE TITLE
[Bug]: BarcodeDetector not working on macOS Ventura 13.0

### ISSUE THREAD

**Issue by sunknudsen** [electron/electron#36242]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.1.3

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

19.1.3

### Expected Behavior

On macOS Monterey 12.6.1, following code doesn’t throw error and `detectedBarcodes` contains QR codes (when applicable).

```typescript
const barcodeDetector = new BarcodeDetector({ formats: ["qr_code"] })
const detectedBarcodes = await barcodeDetector.detect(imageData)
```

### Actual Behavior

On macOS Ventura 13.0, following code doesn’t throw error but `detectedBarcodes` is always empty (even when `imageData` contains QR code).

```typescript
const barcodeDetector = new BarcodeDetector({ formats: ["qr_code"] })
const detectedBarcodes = await barcodeDetector.detect(imageData)
```

### Testcase Gist URL

https://gist.github.com/7300dc675809e4b5b8cb23d52598c303

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sunknudsen** [comment]
@nornagon Please see updated issue which now includes [gist](https://gist.github.com/7300dc675809e4b5b8cb23d52598c303) created using Electron Fiddle (cool app btw).

**Comment by codebytere** [comment]
@sunknudsen does this happen in Chrome itself?

**Comment by sunknudsen** [comment]
@codebytere yes… [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1382442) submitted. Thanks for helping out!

**Comment by codebytere** [comment]
Of course! Once they fix this upstream, we'll inherit the fix pretty quickly through our Chromium upgrade process. I'm going to close this out given it's not an issue we can fix on our side - just track the bug upstream!
