### ISSUE TITLE
[Bug]: hi, we have a problem. async is not supported after packing. If you do not add async, you will not be prompted.Here's an example   window.AsyncFunction = Object.getPrototypeOf(async function(){}).constructor;

### ISSUE THREAD

**Issue by xiajiaoyang1** [electron/electron#36241]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Expected Behavior

Can support

### Actual Behavior

3/5000 
Does not support

### Additional Information

![7AB8FB29-DFED-43ca-B61D-3E8F71D29BD6](https://user-images.githubusercontent.com/117069355/199693031-bbcdcda2-e337-4ff2-99ae-e532eea5e354.png)

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by xiajiaoyang1** [comment]
Hi has not found any similar problem in the community. I will recount the problem: window AsyncFunction = Object. getPrototypeOf(async function(){}). constructor; Uncaught Syntax Error: missing) after argument list will be prompted
如图:







杨夏交
***@***.***

签名由 网易灵犀办公 定制









Original:
From：Jeremy Rose ***@***.***>Date：2022-11-04 03:48:39To：electron/electron ***@***.******@***.***> , Author ***@***.***>Subject：Re: [electron/electron] [Bug]: hi, we have a problem. async is not supported after packing. If you do not add async, you will not be prompted.Here's an example window.AsyncFunction = Object.getPrototypeOf(async function(){}).constructor; (Issue #36241)
Thanks for reaching out!
The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at the project's Community page -- in particular, be sure to give the Electron Discord server a try.
I hope this helps!
