### ISSUE TITLE
[Bug]: BrowserWindow can not take over keyboard focus when hosted in wpf HwndSource

### ISSUE THREAD

**Issue by godsosome** [electron/electron#36240]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.2

### What operating system are you using?

Windows

### Operating System Version

20H2

### What arch are you using?

x64

### Last Known Working Electron version

10.1.6

### Expected Behavior

it can take over keyboard focus from parent window

### Actual Behavior

mouse click is fine but keyboard input not work

### Additional Information

all stuff has been working for several years on 10.1.6, now following the docs break changes and try to upgrade to 20.3.2. changes only:

1.  in main, `require('@electron/remote/main').initialize();`
2. in preload, `const remote = require('@electron/remote');`
3. when create `BrowserWindow` set `sandbox = false;` `contextIsolation = false;` `nodeIntegration = true;` and `require('@electron/remote/main').enable(win.webContents);`

by mouse click between wpf parent window and this electron window.
with 10.1.6, keyboard focus will jump between.
with 20.3.2, i can click any buttons in electron window, but can not input anything for its textbox, by snoop, i can see the keyboard focus always on wpf parent window.

after `BrowserWindow` show, i have tried `wnd.focus();`  `wnd.focusOnWebView();` `wnd.webContents.focus();` even call `blur()` first then `focus()`, or an addon extension that call win32 api `SetFocus(HWND)`, but no lucky.

any suggestion here? it blocks me 2 days, also cannot google any helpful solution.

**Comment by godsosome** [comment]
check back to the stable version v15.5.7, it has the same problem too, even worse that can not see cursor in the expected textbox at all.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
