### ISSUE TITLE
[Bug]: Scrollbars appear in Ubuntu X-Session fullscreen mode

### ISSUE THREAD

**Issue by Luokun2016** [electron/electron#36250]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.4

### What operating system are you using?

Ubuntu

### Operating System Version

5.4.0-131-generic #147~18.04.1-Ubuntu SMP Sat Oct 15 13:10:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

20.3.4

### Expected Behavior

**PrimaryDisplay info:**
{
    id: 71,
    bounds: { x: 0, y: 0, width: 1920, height: 1080 },
    workArea: { x: 0, y: 0, width: 1920, height: 1080 },
    accelerometerSupport: 'unknown',
    monochrome: false,
    colorDepth: 24,
    colorSpace: '{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}',
    depthPerComponent: 8,
    size: { width: 1920, height: 1080 },
    displayFrequency: 59,
    workAreaSize: { width: 1920, height: 1080 },
    scaleFactor: 1,
    rotation: 0,
    internal: false,
    touchSupport: 'unknown'
  }

**BrowserWindow load file**:
```
<!DOCTYPE html>
<head></head>
<body style="width: 100%; height: 100%; margin: 0; display: flex">
    <div id="app-root" style="height: 1080px; width: 1920px;">
        <button>Button</button>
    </div>
</body>
```

The display size is the same as the html page size, the scrollbar does not appear in Ubuntu X-Session fullscreen mode.

### Actual Behavior

Package electron application as electron-browser
- When starting electron-browser in ubuntu desktop mode, the scroll bar does not appear.
- When starting electron-browser in ubuntu X-Session mode, scroll bars appear.

**Source Code**
[electron-browser.zip](https://github.com/electron/electron/files/9935500/electron-browser.zip)

**Actual behavior**

https://user-images.githubusercontent.com/24650960/199904569-9fe2f97d-4789-4c1e-bb9b-ce942996daf6.mp4

**Comment by zcbenz** [comment]
Can you check if the Chromium browser has the same problem?

**Comment by Luokun2016** [comment]
> Can you check if the Chromium browser has the same problem?

Chromium browser has the same problem

**Comment by zcbenz** [comment]
Since this is a Chromium issue, I think the best way to get this fixed is to report it to Chromium's issues: https://bugs.chromium.org/p/chromium/issues/list.

If Chromium can fix it then we can backport the fix to Electron, otherwise it is hard for us to fix this in Electron alone.
