### ISSUE TITLE
[Bug]: Electron child_process taking 10+ seconds on macos 13

### ISSUE THREAD

**Issue by jsullivanlive** [electron/electron#36254]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.2

### What operating system are you using?

macOS

### Operating System Version

13

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

6

### Expected Behavior

Commands like `diskutil unmount` run as fast under `child_process` as they do at normal terminal

### Actual Behavior

Electron 21.2.2 is running very slow when using `require("child_process").execSync()`:

-  `ls` takes <10ms
-  `diskutil unmount "/Volumes/NIKON D300"` takes over 10 **seconds**. 

When I run `diskutil unmount "/Volumes/NIKON D300"` in normal terminal (default zsh) it takes **0.4s**:

```
time diskutil unmount "/Volumes/NIKON D300"
Volume NIKON D300 on disk4s1 unmounted
diskutil unmount "/Volumes/NIKON D300"  0.01s user 0.01s system 4% cpu 0.484 total
```

CPU usage doesn't spike and no new processes appear in activity monitor to indicate what is taking up that much time.

Computer: Apple M2 (arm64), 24gb ram, 1tb disk, Mac OS 13

It takes **1s** on an Intel i7 Macbook Pro 2018 with 32gb ram, so I'm trying to hunt down why it's taking so long and don't know where to look next.  Any advice is sincerely appreciated.

Breakout repo for how to reproduce it:
https://github.com/jsullivanlive/electron-slow-child-process

there are 2 buttons on the page, "ls" and "unmount" , and here's my console output when i click them:

[![enter image description here](https://i.stack.imgur.com/VW552.png)](https://i.stack.imgur.com/VW552.png)

### Testcase Gist URL

https://github.com/jsullivanlive/electron-slow-child-process

### Additional Information

Tried to upgrade libraries, watch console.app, activity monitor, etc.  Can't figure out why unmount is taking so much longer when run in child_process.

**Comment by AviVahl** [comment]
Perhaps try spawn instead of exec, to avoid running shell for native binaries, just in case the shell has many hooks? Any difference then?

**Comment by nornagon** [comment]
Duplicate of https://github.com/electron/electron/issues/32480 maybe? You write two different versions of Electron in your issue so I'm not sure if you're using a version on which this was addressed.

**Comment by nornagon** [comment]
@jsullivanlive would you mind creating a smaller repro case, perhaps using [Electron Fiddle](/electron/fiddle)? A minimal repro helps us quickly narrow in on what the issue might be without having to sift through any 3rd-party dependencies.

**Comment by zcbenz** [comment]
What happens if you execute `diskutil unmount "/Volumes/NIKON D300"` in Node.js, or with `subprocess.Popen` in python?

```python
import subprocess
process = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE)
process.wait()
```

**Comment by jsullivanlive** [comment]
I updated the project to make it vanilla electron:
https://github.com/jsullivanlive/electron-slow-child-process

Here's a video of what I'm experiencing:
[18bad578-b9c8-43c4-8423-b70cdbe8147a.webm](https://user-images.githubusercontent.com/493648/202887093-86f83527-0959-46de-8e07-d11e50214a5f.webm)

@zcbenz here's what I got when I run it via python:
```
~ time python3 x.py
python3 x.py  0.04s user 0.02s system 14% cpu 0.409 total
```

**Comment by zcbenz** [comment]
Thanks for the repro, can you also try running following commands and see if they also take 10+ seconds?

```
time node -e "require('child_process').execSync('diskutil unmount \'/Volumes/NIKON D300\'')"
```

```
time node -e "require('child_process').exec('diskutil unmount \'/Volumes/NIKON D300\'')"
```

**Comment by superhos** [comment]
same  issue. Running command in electron is much slower than directly run the shell. Any solution?
