### ISSUE TITLE
[BUG] MacOS: frame + roundedcorners prevents fullscreen

### ISSUE THREAD

**Issue by mtdvlpr** [electron/electron#36251]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.0. Apple M1 SoC

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Code like this should put the window in fullscreen.
```javascript
win = new BrowserWindow({
    title: "Media Window",
    frame: false,          // These 3 options can't be
    roundedCorners: false, // used concurrently on macOS 
    fullscreen: true       // to get a fullscreen window
  });
```

### Actual Behavior

The window is prevented from going into fullscreen.

### Testcase Gist URL

https://gist.github.com/mtdvlpr/91a1a645bf3160b3a0fd459d5726a2d8

### Additional Information

Previously this setup caused a crash as stated in #35403. The fix for the issue was to prevent fullscreen in this scenario, but I would like to see the underlying problem fixed as well, since I need a frameless, fullscreen window without the rounded corners.

**Comment by sircharlo** [comment]
Note this relevant comment: https://github.com/electron/electron/pull/35421#issuecomment-1225693209

**Comment by zcbenz** [comment]
This is unfortunately impossible on macOS. To remove rounded corners the only way is to remove the `NSWindowStyleMaskTitled` style from window, but to make the window enter fullscreen the window must have the style. This is a limitation of macOS itself and I'm not aware of any workaround, but if you could find an open source project achieving this feature I would be very willing to check how they implemented it.

I'm closing this issue as the behavior is documented and there is no way to implement it.
