### ISSUE TITLE
[Bug]: Using a method from a class extending Electron.Tray in Typescript returns Typeerror : class.method is not a function 

### ISSUE THREAD

**Issue by Pascal-Flores** [electron/electron#36269]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.4

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04 LTS

### What arch are you using?

x64

### Expected Behavior

When extending the Electron.Tray class in typescript, I should be able to create methods for the extending class (eg. CustomTray), and call these methods when using an instance of this class.

For example :
 
*CustomTray.ts*
```typescript
import { Tray, Menu } from 'electron'

class CustomTray extends Tray {
    public constructor(image : string | Electron.NativeImage) {
        super(image);
    }
    
    public buildMenu() : void {
        let menu = Menu.buildFromTemplate([
            { label : 'App title', type : 'normal', enabled : false },
            { type  : 'separator'}
        ]);
       this.setContextMenu(menu);
    }
}
```

*index.ts*
```typescript
import { CustomTray } from './CustomTray.ts'

app.whenReady().then( () => {
    let tray = new CustomTray('image.png');
    tray.buildMenu();
});
```

When executed, the tray should be showed properly.

### Actual Behavior

When creating a class extending the Tray class as above, electron throws a Typeerror : tray.buildMenu is not a function.

This behaviour does not seem to appear for other extended Electron classes (tested with Electron.BrowserWindow and Electron.Touchbar).

Also, I checked my dependencies with dpdm to see if there was any circular dependency, as it can cause this type of error, but there isn't.

Any help on this subject would be much appreciated, as I don't really know what's going on here...

**Comment by nornagon** [comment]
We don't support extending built-in classes in Electron.
