### ISSUE TITLE
[Bug]: `Electron.Event` interface in TypeScript does not match actual value

### ISSUE THREAD

**Issue by Shintarot** [electron/electron#36260]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.2

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5.1

### What arch are you using?

x64

### Expected Behavior

The documentation and TypeScript interface states that `Electron.Event` extends node.js `Event` ([doc](https://nodejs.org/api/events.html#class-event)).

### Actual Behavior

The actual values are only `preventDefault` and `sender`. (Observed in the first argument in the callback of `webContents.on('before-input-event', callback)`).

### Additional Information

- `node.js v18.12.1`
- using `webpack`

Currently, renderer cannot `preventDefault()` the handlers set in `webContents.on('before-input-event',callback)`.

**Comment by MarshallOfSound** [comment]
> Currently, renderer cannot preventDefault() the handlers set in webContents.on('before-input-event',callback).

This sounds like you are somehow proxying these main process events into a renderer process.  This is not supported and explains the strange behavior you are seeing.

You should listen to the `before-input-event` in the main process not the renderer and then the `event` object will be as expected

**Comment by Shintarot** [comment]
> This sounds like you are somehow proxying these main process events into a renderer process. This is not supported and explains the strange behavior you are seeing.
> 
> You should listen to the `before-input-event` in the main process not the renderer and then the `event` object will be as expected

Thank you for taking your time to do this.

It seems I did not communicate correctly. The above `webContents.on('before-input-event', callback)` is in the `main` process.

In the first place, I should not have added the extra words (Currently~) in _**Additional Information**_. This issue should be discussed separately as follows

### 1. Electron.Event interface in TypeScript does not match actual value (as the title says)

The problem could be either of the following

- A. The TypeScript interface and the documentation are incorrect
- B. The runtime implementation is incorrect

### 2. if A is the case, there is no way to cancel the handlers set by `webContents.on('before-input-event', callback)` from the renderer. 

This may not be something we should talk about much here (issue on bug), but if this is the case for A, the following problems arise.

An example is shown below.

- Implement `ctrl + F` in `webContents.on('before-input-event', callback)` to start a search in the page.
- For example, when opening Google Sheets and typing `ctrl + F`, the browser's in-page search should be canceled by the website (as it would be in Chrome).

- Currently, the callback argument of `webContents.on('before-input-event', callback)` only has `sender` and `preventDefault`, so it cannot be implemented.

**Comment by MarshallOfSound** [comment]
Can you provide a complete and runnable sample of typescript code that `tsc` thinks is OK but is incorrect at runtime?

**Comment by Shintarot** [comment]
Here it is.
https://github.com/Shintarot/electron_issue36260

**Comment by Shintarot** [comment]
> Can you provide a complete and runnable sample of typescript code that `tsc` thinks is OK but is incorrect at runtime?
Here it is.
https://github.com/Shintarot/electron_issue36260

**Comment by Shintarot** [comment]
> Can you provide a complete and runnable sample of typescript code that `tsc` thinks is OK but is incorrect at runtime?

Perhaps you haven't noticed? (I'm sorry if you do)

**Comment by schontz** [comment]
I am seeing this issue as well. For example, `sender` is not in the Event type.

Here is a sample:

```
const bw = new BrowserWindow({});
bw.on('close', (e) => {
  console.dir(e);
  console.log('Closing window with ID=', e.sender.id);
  // TS error: Property 'sender' does not exist on type 'Event'
});
```

The output of `console.dir(e)` shows:
```
  {
    preventDefault: [Function: preventDefault],
    sender: BrowserWindow {
      setBounds: [Function (anonymous)],
      _events: [Object: null prototype] {
        blur: [Array],
        focus: [Array],
        show: [Array],
        hide: [Array],
        minimize: [Array],
        maximize: [Array],
        restore: [Array],
        closed: [Array],
        unmaximize: [Function: onRestore],
        'enter-full-screen': [Function: onEnterFullScreen],
        'leave-full-screen': [Function: onLeaveFullScreen],
        unresponsive: [Array],
        responsive: [Array],
        swipe: [Function (anonymous)],
        'app-command': [Function (anonymous)],
        close: [Function (anonymous)],
        resized: [Function (anonymous)]
      },
      _eventsCount: 17,
      emit: [Function (anonymous)],
      devToolsWebContents: [Getter]
    }
  }
```

**Comment by MarshallOfSound** [comment]
`event.sender` was removed from the type as it wasn't part of API or documented anywhere and was inconsistently available.  In your case e.sender is just `bw` so you should just use that variable instead

**Comment by schontz** [comment]
Noted. Is there a way to work backward from an event to get the BrowserWindow? There are cases where I don't know the window, e.g.:

```
function handleClose(e: Electron.Event) {
  console.log('window closed, id:', e.sender.id);
}

const win1 = new BrowserWindow();
const win2 = new BrowserWindow();
win1.on('close', handleClose);
win2.on('close', handleClose);
```

There are other examples as well. If the answer is simply "no standard way" then I'll leave it at that. 😄

**Comment by MarshallOfSound** [comment]
No standard way, I'd suggest changing the pattern so the function closure adds the listener and retains the window

**Comment by schontz** [comment]
Makes sense. Just makes unsubscribing a little harder. Thanks! Have a good weekend.
