### ISSUE TITLE
[Bug]: Tray setImage can segfault on Linux

### ISSUE THREAD

**Issue by nicks** [electron/electron#36274]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

We've been tracking down reports for a while about our app segfaulting on Linux. We narrowed down the issue to calling Tray's setImage function. More discussion on the issue here:

[libayatana-appindicator](https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/1867996)
https://github.com/AyatanaIndicators/libayatana-appindicator/issues/51

Unfortunately, we can't guarantee that our users have a fixed version of the shared library installed. So we've removed all calls to Tray's setImage, to ensure that their apps don't crash randomly.

### Proposed Solution

We humbly request that the docs should contain a note about this problem - that setImage is known to cause segfaults, and should not be used on Linux.

https://www.electronjs.org/docs/latest/api/tray

### Alternatives Considered

Have some code in Electron to detect when broken versions of the shared library are used, and avoid calling into it. But this seemed way more complex to implement.

### Additional Information

Thanks!

**Comment by zcbenz** [comment]
I'm good adding the note in our docs, but in the long term I think we should get rid of libappindicator and use dbus directly.

**Comment by nicks** [comment]
opened a pr as https://github.com/electron/electron/pull/36310

**Comment by Atharva-17** [comment]
Hey, @nicks I added a note in `tray.md` please check opened a PR as #36432
