### ISSUE TITLE
[Bug]: After upgrading the electron appliction from 12 to 14.1.1 application open in fullscreen or more than the actual screen size

### ISSUE THREAD

**Issue by prakashnarkhede91** [electron/electron#36307]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

14.1.1

### What operating system are you using?

Ubuntu

### Operating System Version

ubuntu 20 and ubuntu 22

### What arch are you using?

x64

### Last Known Working Electron version

12

### Expected Behavior

Open the application in the actual screen size the toolbar and top bar need to display properly.

### Actual Behavior

application open and top bar close button goes right side out of the screen and toolbar also hidden
![Screenshot from 2022-11-10 11-44-28](https://user-images.githubusercontent.com/20293941/201014571-ba2328aa-e0ef-4c1f-8482-0d04e821c757.png)

In above attachment the close button out of the screen 

### Additional Information

we are using the electron version   "electron": "14.1.1",

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `19.x.y`, so in order for us to triage this please demonstrate that it is still an issue on a supported version. Otherwise, this issue will be closed in 10 days.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
