### ISSUE TITLE
[Bug]: After exiting full screen, clicking Menu does not work on ubuntu

### ISSUE THREAD

**Issue by MichinariNukazawa** [electron/electron#36327]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.3

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.1 LTS

### What arch are you using?

x64

### Expected Behavior

Menu works fine after fullscreen.

### Actual Behavior

After exiting full screen, clicking Menu does not display any menu items.

### Additional Information

A change occurs when the menu button is pressed and the button color changes.
Exiting fullscreen and waiting for a while may fix the problem, and clicking again will show the menu items.

There is no error in the shell of the started terminal and the developer console of the browser.

not reproducible on windows.

**Comment by Prinzhorn** [comment]
Sounds like https://github.com/electron/electron/issues/35724 https://github.com/electron/electron/issues/35960

**Comment by MichinariNukazawa** [comment]
Seems related to #35724

**Comment by VerteDinde** [comment]
Closing this as a repro of 35724, mentioned above. @MichinariNukazawa Thanks for reporting! We'll keep looking into it
