### ISSUE TITLE
Broken Release: v21.2.3 has Broken Version Number in package.json

### ISSUE THREAD

**Issue by PhotoNomad0** [electron/electron#36328]
I downloaded the source for `https://github.com/electron/electron/releases/tag/v21.2.3`, and In package.json the version number is incorrect (it is also broken in tag v21.2.3):
```
{
  "name": "electron",
  "version": "0.0.0-development",
  "repository": "https://github.com/electron/electron",
  "description": "Build cross platform desktop apps with JavaScript, HTML, and CSS",
...
```

**Comment by MarshallOfSound** [comment]
This is expected behavior, the version number is dynamically assigned during the build process.  It is no longer stored in version control itself, at least not directly, the version is determined based on tags.

**Comment by PhotoNomad0** [comment]
> This is expected behavior, the version number is dynamically assigned during the build process. It is no longer stored in version control itself, at least not directly, the version is determined based on tags.

Thanks.  I presume this is the same for the comments in `electron.d.ts` mentioning that it is for version 0.0.0:
```
// Type definitions for Electron 0.0.0-development
// Project: http://electronjs.org/
// Definitions by: The Electron Team <https://github.com/electron/electron>
// Definitions: https://github.com/electron/electron-typescript-definitions
...
```

**Comment by MarshallOfSound** [comment]
Ah now that, that's a bug 😂
