### ISSUE TITLE
[Bug]: Failed to install electron on FreeBSD

### ISSUE THREAD

**Issue by rilysh** [electron/electron#36325]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.5

### What operating system are you using?

Other (specify below)

### Operating System Version

FreeBSD 13.1-RELEASE

### What arch are you using?

x64

### Expected Behavior

Electron should be available on GitHub releases for FreeBSD and install properly.

### Actual Behavior

When I'm installing node packages through `yarn` of this [project](https://github.com/ArmCord/ArmCord), I encountered with an error saying electron build not found on GitHub releases.
```
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v20.3.5/electron-v20.3.5-freebsd-x64.zip
```
So I move there, check GitHub releases and realized there wasn't any electron build for FreeBSD a while.

#### Image
![image](https://user-images.githubusercontent.com/71683721/201513782-929512b6-3bbb-464d-8590-57416c98ce60.png)

**Comment by MarshallOfSound** [comment]
Electron does not support freebsd https://github.com/electron/electron/issues/3797

**Comment by rilysh** [comment]
You literally closed it without any conclusion. And what is the meaning of this, if it doesn't "support" at all?
https://github.com/electron/electron/blob/46a74d1086baead0f0963edf810bb4d301aee04a/npm/install.js#L106
My concern is, if there's FreeBSD platform specified, why there are no build available for FreeBSD nor OpenBSD on GitHub releases?

**Comment by MarshallOfSound** [comment]
Electron does not provide official builds for freebsd or openbsd (per the issue I linked above).  Some third parties have support for these builds in their download mirrors, the code you linked ensures that if the download mirror has builds for those platforms  the npm package works correctly.
