### ISSUE TITLE
[Bug]: Unix env : Cannot allocate memory during start

### ISSUE THREAD

**Issue by YuriL180821** [electron/electron#36326]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 18.04

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

Electron app should start without problems

### Actual Behavior

Electron does not start and prints **Cannot allocate memory**

### Testcase Gist URL

https://github.com/electron/electron

### Additional Information

System with issues uses 32 Gb of RAM, so absence of allocation is not caused by physical system limitations

**Comment by YuriL180821** [comment]
Have next during debug into Qt
<img width="919" alt="Debug_fail" src="https://user-images.githubusercontent.com/89125090/201515072-de6279c1-bcb4-4820-85c1-e3b2485e5137.png">

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

If you’re still experiencing this issue in Electron 19.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by YuriL180821** [comment]
Helli @mlaurencin , please put issue as active, it has reproduce on the lastest electron main.

**Comment by ckerr** [comment]
@YuriL180821 this is launching the version of Electron that was built in vscode, correct?

If you try to launch this from the command line, e.g. without debugging, does it work properly?

I'm trying to understand if the presence of a debugger is a prerequisite for this issue.

**Comment by YuriL180821** [comment]
UPD: It should to say that electron project was created into debug mode
https://www.electronjs.org/docs/latest/development/debugging

**Comment by YuriL180821** [comment]
Same results for Release configuration

```
Debugging starts
/bin/bash: /mnt/d/electron-official/src/out/Release/electron: Cannot allocate memory
/bin/bash: /mnt/d/electron-official/src/out/Release/electron: Success
Debugging has finished
```

<img width="894" alt="cannot_allocate_memory" src="https://user-images.githubusercontent.com/89125090/212482997-b5f8e8b9-6064-4387-9653-ec21131a1b33.png">

**Comment by YuriL180821** [comment]
@mlaurencin does anybody from community can take a look on problem?

**Comment by mlaurencin** [comment]
I can remove the `blocked/need-info` tag. It may also be helpful to check out [the Electron Discord server](https://discord.com/invite/electron) and see if anyone has experience with Qt that can help.
