### ISSUE TITLE
[Bug]: Documentation around nodeIntegration is wrong

### ISSUE THREAD

**Issue by xremming** [electron/electron#36330]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v21.2.3

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows 10 + Arch Linux in WSL2

### What arch are you using?

x64

### Expected Behavior

The [documentation](https://www.electronjs.org/docs/latest/api/browser-window) says the following things.

>preload string (optional) - Specifies a script that will be loaded before other scripts run in the page. This script **will always have access to node APIs no matter whether node integration is turned on or off**.

That is, the preload script should always have ***full access*** to the Node APIs.

### Actual Behavior

Starting BrowserWindow without `nodeIntegration: true` does not allow the preload script to use any Node APIs.

### Additional Information

In general this seems to mostly be an issue of documentation. After ***multiple hours*** of reading documentation and googling for solutions I still have no idea how one should expose Node functions to the browser and what is considered safe and not.

My use case is that I have an gRPC server that I need to start when a window is opened, and after it has started I need to expose a number of methods from the gRPC client to the browser window. There may be more than one of the same process running, a different one for each window opened, so the `ipcMain.invoke` does not really work (and I do not like the amount of code duplication it implies).

So far it looks like setting `nodeIntegration` to true does not actually allow the browser window to access Node APIs at all but it is required to use Node APIs in the preload script.

The following docs all have slightly different information around this topic and all of them just confuse (me) the reader the more they read through them:

- https://www.electronjs.org/docs/latest/tutorial/sandbox#preload-scripts
- https://www.electronjs.org/docs/latest/tutorial/tutorial-preload#augmenting-the-renderer-with-a-preload-script
- https://www.electronjs.org/docs/latest/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content

Especially the last one says 

>When disabling Node.js integration, you can still expose APIs to your website that do consume Node.js modules or features. Preload scripts continue to have access to require and other Node.js features, allowing developers to expose a custom API to remotely loaded content via the [contextBridge API](https://www.electronjs.org/docs/latest/api/context-bridge).

which seems to be just blatantly incorrect and extremely confusing as the other page says

>Because the require function is a polyfill with limited functionality, you will not be able to use [CommonJS modules](https://nodejs.org/api/modules.html#modules_modules_commonjs_modules) to separate your preload script into multiple files. If you need to split your preload code, use a bundler such as [webpack](https://webpack.js.org/) or [Parcel](https://parceljs.org/).

and the docs say the following thing (which I already copy-pasted in the "Expected Behaviour" block").

>[preload] specifies a script that will be loaded before other scripts run in the page. This script will always have access to node APIs no matter whether node integration is turned on or off.

---

So which of the following are true?

1. `nodeIntegration: true` only concerns the preload script.
2. `nodeIntegration: true` makes it possible to call Node APIs from the Browser Window.
3. When `nodeIntegration: false` the full Node API is available in the preload script.
4. When `nodeIntegration: false` you cannot split your code into multiple modules (and therefore the full Node API is not usable).
5. `nodeIntegration: true` is a security risk in the Browser Window when preload script is not defined.
6. `nodeIntegration: true` can be a security risk in a preload script because the user can accidentally leak powerful Node APIs to the Browser Window.
7. It is always possible to leak Node APIs to the Browser Window with a preload script.

**Comment by xremming** [comment]
I will see if I have time tomorrow to create some sample code. Really this is an issue of some very confusing and incomplete documentation.

**Comment by xremming** [comment]
Issue still persist but I moved my project from electron to a fully native Rust app.

**Comment by penx** [comment]
> After multiple hours of reading documentation and googling for solutions I still have no idea how one should expose Node functions to the browser and what is considered safe and not

+1, definitely not stale, I am also finding the docs very confusing for the reasons outlined above.

I would like to access Node APIs and then expose this as my own API to the browser window. I don't see this as a security concern as I won't be exposing full access. The current docs make it very confusing as to whether this is possible without setting `nodeIntegration: true`, (e.g. by accessing the context bridge from the main process?).

**Comment by penx** [comment]
Looks like ipcMain and ipcRenderer are what I need, possibly then combined with contextBridge.

https://www.electronjs.org/docs/latest/api/ipc-renderer
https://www.electronjs.org/docs/latest/api/ipc-renderer

If that's the case, would be great if this was mentioned in:

> To add features to your renderer that require privileged access, you can define [global](https://developer.mozilla.org/en-US/docs/Glossary/Global_object) objects through the [contextBridge](https://www.electronjs.org/docs/latest/api/context-bridge) API

https://www.electronjs.org/docs/latest/tutorial/tutorial-preload#augmenting-the-renderer-with-a-preload-script

**Comment by penx** [comment]
Not stale

**Comment by penx** [comment]
lol
