### ISSUE TITLE
[Bug]: Dragging the window prompts an error

### ISSUE THREAD

**Issue by bandiandou** [electron/electron#36346]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.6

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Last Known Working Electron version

12.0.6

### Expected Behavior

no errors

### Actual Behavior

when i drag the windows， sometimes  will prompt an error
![image](https://user-images.githubusercontent.com/86463809/201821230-2e85d9ec-3bd6-4028-91ca-6fc48034ee1e.png)

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

Additionally, you're using an older version of Electron that's no longer LTS. Could you please try upgrading to Electron 19 or higher?

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by bandiandou** [comment]
I tried a simple local demo, which won't reappear. Maybe there is something wrong with the code
