### ISSUE TITLE
How to send video stream(front-end render processes) to another render process (front-end render processes)? (Video recording)

### ISSUE THREAD

**Issue by xautwds** [electron/electron#36349]
Problem Description

I implemented the mediaStream from WebRTC
I want to send the video Stream of the front-end (renderer processes) to  another render process 
How to send video stream(front-end render processes) to another render process

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
