### ISSUE TITLE
[Bug]: setAlwaysOnTop + setVisibleOnAllWorkspaces + visibleOnFullScreen not working unless the window is manually focused by user

### ISSUE THREAD

**Issue by Nic0S** [electron/electron#36364]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.3, 20.3.5

### What operating system are you using?

macOS

### Operating System Version

macos 12.16.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

n/a

### Expected Behavior

Fullscreen some app in macOS (for example I'v been testing with chrome).

Run the repro gist, which will wait 2.5 seconds and then make the following calls on the window:

```
mainWindow.setAlwaysOnTop(true, "modal-panel");
mainWindow.setVisibleOnAllWorkspaces(true, {
    visibleOnFullScreen: true,
});
```

Once you see the electron icon disappear from your doc (indicating the calls above have been made), switch to a macOS workspace that has a fullscreened window

Now I expect to see my electron window displayed above the other fullscreened macOS window

### Actual Behavior

If you follow the above steps, the electron window is not displayed above the fullscreened window. If you manually select the electron window and move it around after calling setAlwaysOnTop and setVisibleOnAllWorkspaces, you get the correct behavior and the electron window will appear above your other fullscreen window

### Testcase Gist URL

https://gist.github.com/9b3ea630126da8c77fb648a65fb8699d

### Additional Information

I've tried various combinations of window.show(), window.focus(), window.moveTop() etc after setting the new window properties but it doesn't seem to make a difference.

**Comment by H3r3zy** [comment]
Already here on v16.0.6 actually no work around as far as I know

**Comment by vkravets** [comment]
Hi all, is any workaround exists or plans when it will be fixed?

**Comment by vkravets** [comment]
Nope, the problem still exists... Sorry for the mess (

**Comment by aheinecke** [comment]
bump

**Comment by 0xUnkn0wN** [comment]
bump

**Comment by navinthomas** [comment]
bump

**Comment by vkravets** [comment]
bump
