### ISSUE TITLE
[Bug]: TypeScript interface of `webFrame` does not match actual value

### ISSUE THREAD

**Issue by Shintarot** [electron/electron#36381]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.2

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5.1

### What arch are you using?

x64

### Expected Behavior

There are properties in TypeScript that are not mentioned in the [documentation](https://www.electronjs.org/docs/latest/api/web-frame) and do not actually exist.
(I have only checked webFrame.addListener)

```
// in preload
import { webFrame } from 'electron';

webFrame.addListener('keydown', (e) => {
    console.log('webFrame.addListener:keydown:e:', e);
});
```

```
// webContents' console
e.webFrame.addListener is not a function
```

<img width="532" alt="Screen Shot 2022-11-17 at 13 29 09" src="https://user-images.githubusercontent.com/39514220/202356068-9c58f417-90fd-442c-9c07-3db01e739398.png">

### Actual Behavior

TypeScript may be wrong, but I don't know the details.

### Additional Information

devDependencies are as follows
```
    "devDependencies": {
        "@electron-forge/cli": "^6.0.0-beta.63",
        "@electron-forge/maker-deb": "^6.0.0-beta.63",
        "@electron-forge/maker-rpm": "^6.0.0-beta.63",
        "@electron-forge/maker-squirrel": "^6.0.0-beta.63",
        "@electron-forge/maker-zip": "^6.0.0-beta.63",
        "@types/node": "^18.0.0",
        "@types/react": "^18.0.8",
        "@types/react-dom": "^18.0.0",
        "@types/webpack-node-externals": "^2.5.3",
        "@typescript-eslint/eslint-plugin": "^5.21.0",
        "@typescript-eslint/parser": "^5.21.0",
        "concurrently": "^7.1.0",
        "electron": "^21.2.2",
        "electron-squirrel-startup": "^1.0.0",
        "eslint-config-prettier": "^8.5.0",
        "react-scripts": "^5.0.1",
        "terser-webpack-plugin": "^5.3.5",
        "ts-loader": "^9.3.1",
        "ts-node": "^10.9.1",
        "typescript": "^4.6.3",
        "wait-on": "^6.0.1",
        "webpack": "^5.74.0",
        "webpack-cli": "^4.10.0"
    },
```

**Comment by MarshallOfSound** [comment]
Raised https://github.com/electron/typescript-definitions/issues/210
