### ISSUE TITLE
[Bug]: Failed to run "electric builder" on kylin

### ISSUE THREAD

**Issue by rdtx661** [electron/electron#36384]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

Other Linux

### Operating System Version

linux-4.4.131-20200704.kylin.server-generic-aarch-with-kylin-4.0.2-Juniper

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The electric builder is packaged successfully.

### Actual Behavior

There are two "kylin" computers made in China. Their CPU models are different. One CPU model is "physium, ft – 2000/4 (64 bit, 4-core)", which can run "electric builder" normally. The other CPU model is "64cores physium, ft – 2000+/64 64bit". When running "electric builder", it will download (more like updating) the current version of electric (my electric version is 11.3.0) from github, Then the compilation fails, and one of the error prompts is exited with code err_ electron_ builder_ cannot_ Execute, should I upgrade the version of Electron in this case? Which version do you need to upgrade to? Thank you, please tell me

### Additional Information

Since the node version was 10.16 at the beginning, after updating it to 10.24, the same error will still be displayed when running "electric builder"

**Comment by rdtx661** [comment]
The computer operating system I use is Yinhe Qilin. Its version is kylin 4.0.2

**Comment by VerteDinde** [comment]
Hey @rdtx661, electron-builder is actually run by a different maintainer team - could you please file an issue with that project? Their issue tracker is here: https://github.com/electron-userland/electron-builder/issues

Also, to your question about updating Electron - Electron 11 is fairly old. Our new LTS versions are Electron 19, 20 and 21. Maybe trying one of the newer versions will help. If you don't get immediate help in the electron-builder repo, there are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that may be able to lend a hand. Good luck!
