### ISSUE TITLE
[Bug]: "Request Network. setUserAgentOverride failed. {"code":-32602,"message":"Empty userAgent invalid with userAgentMetadata provided"}"

### ISSUE THREAD

**Issue by navdeepm20** [electron/electron#36397]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.3

### What operating system are you using?

Windows

### Operating System Version

22H2

### What arch are you using?

x64

### Expected Behavior

Should not show this on start up.

### Actual Behavior

[12108:1118/195247.932:ERROR:CONSOLE(1)] "Request Network.
setUserAgentOverride failed. {"code":-32602,"message":"Emp
ty userAgent invalid with userAgentMetadata provided"}", s
ource: devtools://devtools/bundled/core/protocol_client/pr
otocol_client.js (1)

When starting the electron app. 
I am using Electron forge 6 (With Webpack) and Using React With it.

**Comment by MarshallOfSound** [comment]
This error does not impacting the running of your app, we can't guarantee logs won't be emitted from the content layer.
