### ISSUE TITLE
[Bug]: mac m1 lost ime input focus on tap tray

### ISSUE THREAD

**Issue by zengchaowu** [electron/electron#36393]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0+

### What operating system are you using?

macOS

### Operating System Version

macOS 12.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

19.0.0

### Expected Behavior

when click tray to focus window. chinese/ime input cannot work, the input will on the leftbottom corner of window.

### Actual Behavior

left click on tray, chinese input cannot work.

https://user-images.githubusercontent.com/86236258/202645323-ecc2f459-b16a-4ab3-bebd-570ebce21f3a.mov

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!
