### ISSUE TITLE
[Bug]: I don't know how to customize which application the notification comes from in Window 10 Action Center

### ISSUE THREAD

**Issue by luoleya** [electron/electron#36392]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.0

### What operating system are you using?

Windows

### Operating System Version

10 version 20H2

### What arch are you using?

x64

### Expected Behavior

I want to customize which application the notification comes from in Window 10 Action Center.
![image](https://user-images.githubusercontent.com/108255914/202641324-02c5cefd-e1ee-42c0-bfcc-1fae5b37b270.png)

But I didn't find any explanation for this.

### Actual Behavior

I want to customize this content instead of displaying its path.

**Comment by MarshallOfSound** [comment]
You need to ensure your application has a shortcut in the start menu with an appusermodelid that matches your apps
