### ISSUE TITLE
[Bug]: showOpenDialog: Selecting a folder STILL crashes the app

### ISSUE THREAD

**Issue by mnumanuyar** [electron/electron#36391]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.11

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.1

### What arch are you using?

x64

### Last Known Working Electron version

n.a.

### Expected Behavior

The app starts up and shows a file open dialog, allowing me to pick a file.

### Actual Behavior

The file open dialog shows up, but the app crashes as soon as I click on one of the directories in the left side bar, or when I right-click inside the window. Sometimes, the app crashes immediately upon opening the dialog.

### Additional Information

this is same as #20380 but it is closed by bot because electron version in the issue was old, and i couldnt find newer issue related to this.

Issue only happens when i run the app in vscode console. It doesnt happen if I build it with electron builder or when I run from a seperate console

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by mnumanuyar** [comment]
I will try, but if you take a look at the referenced issue, you will see that the issue happen when it runs on vscode console. I will update the questions with this info.
Is Electron Fidle still relevant ?
