### ISSUE TITLE
[Bug]: webContents.print blurry with Epson on windows 7

### ISSUE THREAD

**Issue by Chengma999** [electron/electron#36406]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.1

### What operating system are you using?

Windows

### Operating System Version

windows 7

### What arch are you using?

x64

### Last Known Working Electron version

8.2.5

### Expected Behavior

webContents.print on Eposon receipt printer should be sharp

### Actual Behavior

webContents.print on Eposon receipt printer is blurry

### Additional Information

On Electron 18.0.1 on epson TM T20iii on windows 7 it prints blurry.
While on Electron 18.0.1 on epson TM T20iii on windows 10 it prints sharp.
While on Electron 8.2.5 on epson TM T20iii on windows 7 it prints very sharp!
![WeChat Image_20221119142954](https://user-images.githubusercontent.com/38592997/202853143-77c7e4da-c9ae-4a34-8d0b-2d4fe48e2c6b.jpg)

**Comment by codebytere** [comment]
Please verify whether this happens when you print the same documents with Chrome itself.

**Comment by Chengma999** [comment]
> Please verify whether this happens when you print the same documents with Chrome itself.
![WhatsApp Image 2022-09-03 at 12 49 01 AM](https://user-images.githubusercontent.com/38592997/203770813-65803293-060b-4e7e-aad1-4d30aff7f4e6.jpeg)

When I print it directly from Chrome itself from the same machine, it happens. the content is also not sharp, but the header is sharp.

**Comment by Chengma999** [comment]
> also please try with a supported version of Electron (currently 19+, but next week it's going to be 20+)

glad for your quick response!
Actually I have tried on 21.x 20.x and 19.x versions, but same result.

**Comment by codebytere** [comment]
> When I print it directly from Chrome itself from the same machine, it happens.

Unfortunately this means that the error should be reported and addressed upstream. Please file a bug [upstream](https://crbug.com/) and we will inherit the fix automatically.
