### ISSUE TITLE
[Feature Request]: allow to use nativeImage in service worker

### ISSUE THREAD

**Issue by Idered** [electron/electron#36408]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I need to read image from clipboard and save it as PNG or JPEG but calling toPNG on larger images is slow. 

```js
const png = clipboard.readImage().toPNG()
```

so instead I tried to pass bitmap(getBitmap is fast) to service worker:

```js
const bitmap = clipboard.readImage().getBitmap()
const worker = new Worker(resolve(__dirname, "worker.js"));
worker.postMessage([
  {}, // options
  bitmap,
]);
```

and transform it to PNG/JPEG there but I have no way to do it because nativeImage is not available there. Is there any way to convert it to png/jpeg in service worker? Libraries like https://sharp.pixelplumbing.com/ or [@vingle/bmp-js](https://www.npmjs.com/package/@vingle/bmp-js) can't parse that bitmap buffer.

### Proposed Solution

Make nativeImage available in service worker

### Alternatives Considered

Use 3rd party lib to read image from clipboard in service worker

**Comment by killgt** [comment]
Did you find a way to do it? Having similar issue

**Comment by aprilandjan** [comment]
Even the `clipboard.readImage()` is too slow if a 4K image, for example, is in clipboard. In my mbp this method costs about 1200ms.
