### ISSUE TITLE
[Bug]: webview tag background color do not follow browser window when reload webview

### ISSUE THREAD

**Issue by PerfectPan** [electron/electron#36417]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4

### What arch are you using?

x64

### Last Known Working Electron version

11.4.5

### Expected Behavior

Recently, we upgraded our electron version from 11.4.5 to 21.2.0 and met a problem.
The final problem I located is that webview's background color do not follow browser window when reload webview. So it caused from white -> red instead of browser windows' bg color -> red in my demo.
![CleanShot 2022-11-21 at 21 07 47](https://user-images.githubusercontent.com/24316656/203063068-74f6b80e-7cc3-40e0-bf3c-63393c12c53f.gif)

### Actual Behavior

![CleanShot 2022-11-21 at 21 10 09](https://user-images.githubusercontent.com/24316656/203063733-b30f0c30-a2a4-4b7c-b368-7d1f082d1b5e.gif)

### Testcase Gist URL

https://gist.github.com/PerfectPan/100900b7758293b8f72b23d0babdb1cc

### Additional Information

In our situation, we use webview to load chrome devtools frontend. This app styles background color asynchronous, so we met this problem. A hack way maybe we modify the inspect.html to hardcode our background color in it. But we want to know if there are any other way to solve this.

**Comment by dsanders11** [comment]
It looks like this first repros in 16.2.8, due to #33546.

cc @codebytere
