### ISSUE TITLE
[Bug]: Redundant Screen Sharing Notification on GNOME

### ISSUE THREAD

**Issue by maymage** [electron/electron#36419]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.03

### What operating system are you using?

Ubuntu

### Operating System Version

22.10

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

Do not show redunant screen sharing notification as a floating banner on GNOME, since it already provides a screen sharing icon next to the system menu in the top bar, see the screenshot below

![image](https://user-images.githubusercontent.com/36572014/203124605-1b0561df-48c5-4f65-9e80-fde0059a2cf3.png)

This becomes even more annoying with a tiling manager, e.g. pop-shell, where the banner is recognized as a separate window. 

### Actual Behavior

A redundant screen sharing notification is shown.

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by maymage** [comment]
I am sorry, creating a test case is beyond my capabilities. 

The below screen shot is from   [chromium](https://flathub.org/apps/details/com.github.Eloston.UngoogledChromium), version 107.0.5304.110.

![image](https://user-images.githubusercontent.com/36572014/203154649-6d340ef4-7c6f-4c70-87e7-a88ae3744159.png)

Please close, if you consider this an upstream issue.

**Comment by maymage** [comment]
This is still the case as of Version 112.0.5615.49

**Comment by maymage** [comment]
.

**Comment by maymage** [comment]
Here the relevant Firefox discussion and fix

https://bugzilla.mozilla.org/show_bug.cgi?id=1668358

**Comment by maymage** [comment]
Resolved on Firefox 117+
