### ISSUE TITLE
[Bug]: output sometimes missing in utility process

### ISSUE THREAD

**Issue by SimonSiefke** [electron/electron#36411]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0-beta.6

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.10

### What arch are you using?

x64

### Expected Behavior

The output from the child process should always be printed e.g. for this example

```js
// main.js
const { utilityProcess } = require("electron");

console.log({ utilityProcess });

utilityProcess.fork("./child.js", [], {
  stdio: "inherit",
});
```

```js
// child.js
console.log("hello from child");
```

It should be 
```
{ utilityProcess: { fork: [Function: fork] } }

hello from child
```

### Actual Behavior

Sometimes the output from the child process is missing, e.g. for this example

```js
// main.js
const { utilityProcess } = require("electron");

console.log({ utilityProcess });

utilityProcess.fork("./child.js", [], {
  stdio: "inherit",
});
```

```js
// child.js
console.log("hello from child");
```

Sometimes the output is

```
{ utilityProcess: { fork: [Function: fork] } }

hello from child
```

and sometimes the output is just

```
{ utilityProcess: { fork: [Function: fork] } }
```

### Testcase Gist URL

https://github.com/SimonSiefke/electron-utility-process-issue

**Comment by nostazac** [comment]
In this case, the child process script is "./child.js", and the options object specifies that the standard I/O streams should be inherited by the child process.

The code for the child process simply logs a message to the console when it is executed.

If you are encountering an issue with this code, please provide more information or context about the problem you are facing, and I will do my best to assist you further.

**Comment by nostazac** [comment]
In this case, the child process script is "./child.js", and the options object specifies that the standard I/O streams should be inherited by the child process.

The code for the child process simply logs a message to the console when it is executed.

If you are encountering an issue with this code, please provide more information or context about the problem you are facing, and I will do my best to assist you further.

**Comment by wangsen2020** [comment]
electron:25.3.2  This issue persists: only the first console.log is able to print it, while the others aren't. The following code is from my child.js file, but the problem doesn't occur every time.
console.log('Listening for messages...');
process.parentPort.on('message', (e) => {
    const port = e.ports[0];

    process.parentPort.postMessage({data: "Ready"});
    console.log("I coming，do you find me？")

    port.on("message", (e) => {
        console.info("why not print it？", e.data)
        setTimeout(() => {
            port.postMessage(`I get your message:${e.data}`)
        }, 2000)

    });
    port.start();
    port.postMessage({data: "Ready"});
});

**Comment by wangsen2020** [comment]
It seems that after I changed the text from Chinese to English, it could print normally. It might be related to the characters. Everything has been working fine recently."

**Comment by rikublock** [comment]
In case someone is looking for a temporary workaround.
```js
// main.js
const child = utilityProcess.fork("./child.js", [], {
  stdio: "pipe",
});

child.stdout?.on("data", (data) => {
  console.log(`[child] ${data}`);
});
```

```js
// child.js
console.log("hello from child");
```

**Comment by xieerduos** [comment]
> In case someone is looking for a temporary workaround.
> 
> ```js
> // main.js
> const child = utilityProcess.fork("./child.js", [], {
>   stdio: "pipe",
> });
> 
> child.stdout?.on("data", (data) => {
>   console.log(`[child] ${data}`);
> });
> ```
> 
> ```js
> // child.js
> console.log("hello from child");
> ```

# This way, it's also possible
```js
function logToParent(...reset) {
  process.parentPort.postMessage(reset);
}

logToParent('hello')
```

**Comment by jmaratt** [comment]
It seems like this is only an issue on linux.  I have tried the above code on linux and macOS.

console.log can be output on console using stdio: ['ignore', 'pipe', 'pipe']

However, errors in the code are reported on the console in macOS but do not appear in the console in linux.


`const child = utilityProcess.fork(join(__dirname, 'process_ddp.js'), null, { stdio: ['ignore', 'pipe', 'pipe']})
      console.log(child)
      child.postMessage({ message: 'hello' })
      child.on('message', (data) => {
        console.log(data) // hello world!
      })

      child.stdout.on('data', (data) => {
        console.log(`Received out ${data}`)
      })

      child.stderr.on('data', (data) => {
        console.log(`Received err ${data}`)
      })`

process_ddp.js:
`console.log("server process")
process.stderr.write("error! some error test\n")
process.parentPort.on('message', (e) => {
    process.parentPort.postMessage(`${e.data} world!`)
    console.log("4")
  })

  console.log("3")
`
All the console.log and process.stderr.write messages get output on console in macOS and linux.
If i introduce an error in the process_ddp.js code, the error is reported in macOS with trace but linux has no output at all at or after the error.

├── @electron-forge/cli@7.3.0
├── @electron-forge/maker-deb@7.3.0
├── @electron-forge/maker-rpm@7.3.0
├── @electron-forge/maker-squirrel@7.3.0
├── @electron-forge/maker-zip@7.3.0
├── @electron-forge/plugin-auto-unpack-natives@7.3.0
├── @electron-forge/plugin-fuses@7.3.0
├── @electron-forge/plugin-vite@7.3.0
├── @electron/fuses@1.7.0
├── @popperjs/core@2.11.8
├── @vitejs/plugin-react@4.2.1
├── bootstrap-icons@1.11.3
├── bootstrap@5.3.3
├── ddp@0.12.1
├── electron-squirrel-startup@1.0.0
├── electron@29.1.4
├── react-dom@18.2.0
├── react@18.2.0
├── sass@1.72.0
└── vite@5.1.6

Please let me know if any other detail.
