### ISSUE TITLE
[Bug]: Broken links in definition file (electron.d.ts)

### ISSUE THREAD

**Issue by jmkng** [electron/electron#36438]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Links in the definition file comments direct you to relevant documentation.

```
  interface FileFilter {

    // Docs: https://electronjs.org/docs/api/structures/file-filter

    extensions: string[];
    name: string;
  }
```

### Actual Behavior

The links are broken.

<img width="851" alt="Error message" src="https://user-images.githubusercontent.com/13169797/203826197-f0f6073f-ef5b-4e52-82ec-aaa98302eef2.png">

**Comment by HawkinsR** [comment]
This is more widespread.

The repos README.md also has a link to electronjs.org/docs, which directs to the same "Page Not Found". Looks like the routing on the page responds to any request to `electronjs.org/docs` with a 404, and all the documentation now lives at `electronjs.org/docs/latest`.

Seems like a routing issue on the electronjs.org site. If the resources are going to continue to be hosted at `/docs/latest`, then a redirect for all traffic to `/docs` should be included to avoid confusion.

**Comment by MarshallOfSound** [comment]
This has been fixed on the new CDN 👍
