### ISSUE TITLE
How to register NSServices in electron?

### ISSUE THREAD

**Issue by Complugg3d** [electron/electron#36439]
We are trying to add a keyboard shortcut to get a highlighted text in our app as an NSServices

For that we are doing the following to add the service 

`"extendInfo": {
        "NSServices": [
          {
            "NSMenuItem": {
              "default": "Item in the Text Services"
            },
            "NSMessage": "someMessage",
            "NSPortName": "what we should add here?",
            "NSSendTypes": [
              "NSStringPboardType"
            ]
          }
        ]
      }`

<img width="670" alt="Screen Shot 2022-11-24 at 12 47 38" src="https://user-images.githubusercontent.com/8353641/203850026-32533be7-c284-474e-8d90-e45420a91fc1.png">
we have successfully added the service but our doubt here is, how can we get the highlighted text in the application side? 

we found that apple uses https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/SysServices/Articles/providing.html#//apple_ref/doc/uid/20000853-BABDICBI to register the service, but is there a way to do the same in electron?

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by Complugg3d** [comment]
> Thanks for reaching out!
> 
> The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.
> 
> I hope this helps!

Hi team,

Since this is not a feature nor a bug, I guess there is a way to achieve this, I have an open question in stackoverflow https://stackoverflow.com/questions/74574926/how-to-register-nsservices-in-electron is there anyone in the team ablo to provide some guidance here pls?
