### ISSUE TITLE
[Feature Request]: DirectFB support

### ISSUE THREAD

**Issue by ryao** [electron/electron#36440]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Embedded systems running electron could benefit from DirectFB support.

### Proposed Solution

I would like a way to start electron on a Raspberry Pi that will use /dev/fb0 instead of X11. That way the rc system can just start the electron application without needing to start a X11 server.

### Alternatives Considered

Wayland exists, but it needs another process too.

**Comment by nornagon** [comment]
This is something that Chromium would have to support; it is outside of the scope of the Electron project.
