### ISSUE TITLE
[Bug]:  CORS on private network ( fetch to localhost url fails due to CORS )

### ISSUE THREAD

**Issue by dheerajkysetti** [electron/electron#36445]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS M1 Monterey 12.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

19.0.13

### Expected Behavior

From a website served via  https, an javascript fetch to http://localhost:8080 call should be successful.

### Actual Behavior

Unable to access localhost URLs(**http**://localhost:8080) from a website(**https**://example.com)
Despite turning off websecurity, allowing insecure content.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/7882386/203949375-6bbedc80-540f-4c01-84cd-99814149bd5d.png">

### Testcase Gist URL

https://gist.github.com/dheerajkysetti/ae620986fcdd68e18d1d713cc05b0a4a

### Additional Information

The http://localhost URL call should be successful from a website served over https
or have an flag/switch to enable disable it
or have intercepts via which such an access can be controlled programatically.
Adding headers(Access-Control-Allow-Private-Network:true) in onBeforeHeadersReceived

**Comment by miniak** [comment]
please add a proper title

**Comment by dheerajkysetti** [comment]
> please add a proper title

I have updated the title.

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/electron/electron/issues/33133
