### ISSUE TITLE
[Bug]: Developer Tools not showing (Electron v23.6.0)

### ISSUE THREAD

**Issue by MisiekDP** [electron/electron#36452]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home 22H2 19045.2251

### What arch are you using?

x64

### Expected Behavior

Developer Tools panel can be opened by user from Menu or can be started automatically when application starts.

### Actual Behavior

The Developer Tools not showing at start and can't be launched from Menu Panel (Toggle Developer Tools).

### Additional Information

The code used with my app:

```js
const { app, BrowserWindow, ipcMain, shell, Notification } = require('electron');
const path = require('path');
const date = require('date-and-time');
const fs = require('fs');
const cmd = require('node-cmd');
const ExcelJS = require('exceljs');
const {getDesktopFolder} = require('platform-folders');


let windowsClosedIf = false;
let values1toIpcRenderer = {};
let sendToIpcRenderer = false;

const createWindow = () => {
  // Create the browser window
	const mainWindow = new BrowserWindow({
		// frame: false,
		autoHideMenuBar: false,
		width: 800,
		height: 650,
		icon: __dirname + '/files/icon.ico',
		webPreferences: {
			nodeIntegration: true,
			contextIsolation: false
		}
	});

	mainWindow.loadFile(path.join(__dirname, 'index.html'));
	
	mainWindow.webContents.openDevTools();	
	// mainWindow.webContents.setDevToolsWebContents(devtools.webContents);
  	// mainWindow.webContents.openDevTools({ mode: 'detach' });
		
	setInterval(() => {
		if (windowsClosedIf == false){
			if (sendToIpcRenderer == true){
				mainWindow.webContents.send('valuesTest', values1toIpcRenderer);
				values1toIpcRenderer = {};
				sendToIpcRenderer = false;
			}
		}
	},500);
};

// If Electron is ready, create windows
app.on('ready', createWindow);

// If all windows are closed do...
app.on('window-all-closed', () => {
	windowsClosedIf = true;
	app.quit();
});

ipcMain.on('openExcel', function(event) {
	// .
	// .
	// .
});

ipcMain.on('awsde2x', async function(event) {
	// .
	// .
	// .
});

ipcMain.on('valsX2', async function(event, data) {
	// .
	// .
	// .
});
```

My installed packages:
`+-- date-and-time@2.4.1
+-- electron-builder@23.6.0
+-- electron@21.3.1
+-- exceljs@4.3.0
+-- fs@0.0.1-security
+-- node-cmd@5.0.0
+-- nodemon@2.0.20
+-- path@0.12.7
`+-- platform-folders@0.6.0`

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

I can't seem to reproduce the behavior you're describing. Further, the version you've stated (v23.6.0) is not a version of Electron that exists.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by MisiekDP** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> I can't seem to reproduce the behavior you're describing. Further, the version you've stated (v23.6.0) is not a version of Electron that exists.
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance! Your help is appreciated.

Ok, I can send full version of my app too. Could I maybe send it in private location in private message?

**Comment by MisiekDP** [comment]
Ok @nornagon I know which thing cause the issue. I see that my DevTools window doesn't show when I use import ExcelJS module (`const ExcelJS = require('exceljs');`). When I comment this, this window opens correctly and automatically.

Here are the project files: [2.zip](https://github.com/electron/electron/files/10118479/2.zip)
And video with preview: [LINK](https://puu.sh/JsR7q/a47a7df63f.mp4).

What do you think about this? Is it a problem with ExcelJS module only?

**Comment by MisiekDP** [comment]
Ok @shencaobo so what we can do to fix this? Is it a bug or something to do here?

**Comment by shencaobo** [comment]
I'm also waiting for the problem to be resolved. @MisiekDP 
T.T  😣

**Comment by DrRoot-github** [comment]
I got same trouble on 22.1.0 and finally I found a solution.
I don't know this is "right" approach but at least I can use Devtools

```
    win.on("ready-to-show", () => {
      win.webContents.openDevTools();
    });
```

**Comment by 1226085293** [comment]
Electron version 24.1.2
```
// create a new BrowserWindow
const window = new electron.BrowserWindow({
  width: 500,
  height: 500,
  frame: false,
  webPreferences: {
    nodeIntegration: true,
    contextIsolation: false,
    devTools: true,
    enableRemoteModule: true,
  },
});
```
When the window is focused, devTools can only be opened once using the above configuration

**Comment by SanderPs** [comment]
For some reason I do not know (yet) opening devTools stopped working in my app. 

Adding `devtools: true` to webPreferences, or calling openDevTools in `'ready-to-show'` made no difference. Also `CTRL+SHIFT+I` which is a menu shortcut in my app for devTools doesn't do anything.

The only way I can get devTools is to select 'Force Reload' from the menu and then 'Toggle Developer Tools' twice(!) :-)

I guess my problem is caused by too many things going on in the front-end at startup. Maybe I will create an issue for that with reproduce case later on, but it might be helpful for others to know how to get devTools working if nothing else works. Assuming this works in other cases as well, of course.

![image](https://github.com/electron/electron/assets/7665460/aac4de6d-db10-4a43-a6f1-0ef1c93161c1)

**Comment by helhablouj** [comment]
Same problem here, I am using electron js 22.2 and exceljs 4.3. After I added "require('exceljs')" to my code, devTools stopped working

**Comment by DaneCode** [comment]
> the menu and then 'Toggle Developer Tools' twice(!) :-)
I had this issue as well with "electron": "^26.2.2". The 'Force Reload' and then 'Toggle Developer Tools' was able to pull up the Developer Tools.  It was weird when the issue started, because it initially was happening intermittently where the tools wouldn't open and eventually tools just stopped opening up.

**Comment by sid-max1996** [comment]
The same problem. win.webContents.openDevTools() does nothing. Last known electron version 17 without that problem. Not working with version 22, 23. 24, 25, 26, 27, 28. When openDevTools executing in terminal appears electron errors:
```bash
[11182:0115/184841.842398:ERROR:platform_shared_memory_region_posix.cc(217)] Creating shared memory in /dev/shm/.org.chromium.Chromium.goNOaF failed: No such file or directory (2)
[11182:0115/184841.842616:ERROR:platform_shared_memory_region_posix.cc(220)] Unable to access(W_OK|X_OK) /dev/shm: No such file or directory (2)
[11182:0115/184841.842756:FATAL:platform_shared_memory_region_posix.cc(222)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
```
