### ISSUE TITLE
[Feature Request]: browserview  drag to change the browserview  size include width and height

### ISSUE THREAD

**Issue by 82318179** [electron/electron#36451]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Ladies and gentlemen, browserview into the mainwin inside the initial setting size of 200*200, then the mouse over the edge of the browserview, how can drag to change the browserview  size? Can this electron be realized?

### Proposed Solution

Ladies and gentlemen, browserview into the mainwin inside the initial setting size of 200*200, then the mouse over the edge of the browserview, how can drag to change the browserview  size? Can this electron be realized?

### Alternatives Considered

Ladies and gentlemen, browserview into the mainwin inside the initial setting size of 200*200, then the mouse over the edge of the browserview, how can drag to change the browserview  size? Can this electron be realized?

### Additional Information

Ladies and gentlemen, browserview into the mainwin inside the initial setting size of 200*200, then the mouse over the edge of the browserview, how can drag to change the browserview  size? Can this electron be realized?

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
