### ISSUE TITLE
Dependency types in LICENSES.chromium.html shipped for vscode

### ISSUE THREAD

**Issue by dariomx** [electron/electron#36466]
Dear all,

This is a follow up of a question I asked on your sister project vscode, which ships verbatim a bunch of third-party licenses that come from Electron. The ticket for your reference is this:

https://github.com/microsoft/vscode/issues/165559

Following a recommendation made in ticket above, I would like to ask here whether all the dependencies listed in LICENSES.chromium.html are truly runtime or, whether some of those are used as part of the development cycle. Non-runtime dependencies could be, just to provide some examples, things like build tools, documentation generation tools, libraries used in examples, unit-test frameworks, etc.

Thank you in advance,
Cheers.

**Comment by nornagon** [comment]
Seems like it definitely includes non-runtime dependencies: https://source.chromium.org/chromium/chromium/src/+/main:tools/licenses/licenses.py;l=56;drc=2be00b9639867d2fbddeece50394645b977b2a25

**Comment by nornagon** [comment]
wait up, that's _prune_ paths, i.e. not included.

**Comment by nornagon** [comment]
so, yeah, i think this is probably mostly runtime dependencies. i wouldn't say for sure that 100% of the license material in there is definitely for software that's executed by electron at runtime, but it's probably at least mostly that.

IANAL etc

**Comment by dariomx** [comment]
Got it, Jeremy. Thank you.
