### ISSUE TITLE
With Developer Tools open, `-webkit-app-region:drag` does not work

### ISSUE THREAD

**Issue by bengotow** [electron/electron#3647]
This is a regression—in Electron `0.35.1`, draggable regions of the window stop working when the developer tools are opened. This means that the window effectively can't be moved while the developer tools are open. It doesn't matter if the developer tools are docked or in a separate window.

I think this might be a side effect of an intentional change? In previous versions, you couldn't use the "Inspect Element" feature to click and select part of the DOM that was in a draggable region (since it was still draggable.) That now works (I can hover over and click on my title bar), but I can't move the window.

Here's a sample app to reproduce. Open the app, enable "top toolbar" and then open the developer tools:

![image](https://cloud.githubusercontent.com/assets/1037212/11510691/d2c9aa5c-9819-11e5-911e-55a87b840dc2.png)

https://dl.dropboxusercontent.com/u/4803975/frameless-window.zip

**Comment by zcbenz** [comment]
This is a side effect of #3163.

**Comment by tommoor** [comment]
This seems to be more of an issue now that the titleBarStyle behaviour was changed to not have the top area draggable by default

**Comment by mariotacke** [comment]
Not sure if this was fixed but it works for me now (electron `1.4.2`) with dev-tools open on Windows. Note, it is important to set the width and height, otherwise it would not work.

```js
win = new BrowserWindow({
  frame: false
});
```

```html
...
<head>
  <style media="screen">
    html, body {
      -webkit-app-region: drag;
      width: 100%;
      height: 100%;
    }
  </style>
</head>
...
```

**Comment by bpasero** [comment]
It works for me on Windows too, but not sure if it was ever broken there. I can reproduce on Mac all the time.

**Comment by jonniedarko** [comment]
still an issue on os x 10.11.6 with Electron 1.6.2 using either `frame: false` or ` titleBarStyle: 'hidden'`

**Comment by donpark** [comment]
Issue confirmed on macOS Sierra with Electron 1.6.4.

This issue should be at least documented if not fully resolvable in the near term due to low priority.

**Comment by preco21** [comment]
I can confirm this issue still on latest version of `macOS Sierra 10.12.4` and `Electron 1.6.4`.

**Comment by tommoor** [comment]
A workaround for those that are affected by this long standing bug - if you hover the mouse over the top edge of the window until you see a resize cursor and then hold and drag to the side instead of up and down to resize it will let you move the window.

**Comment by Hum4n01d** [comment]
I made a PR to add a note about this to the documentation https://github.com/electron/electron/pull/9155

**Comment by wierli** [comment]
it not work on win10

**Comment by Kilian** [comment]
An alternative workaround is using https://github.com/kapetan/electron-drag.

**Comment by justin2taylor** [comment]
Any updates on this issue? Still having it in 
- macOS 10.12.6 
- Electron 3.0.4

**Comment by justin2taylor** [comment]
Also, just upgraded and still having the issue in

- MacOS 10.13.6
- Electron 3.0.9

**Comment by nukeop** [comment]
Still affects Electron 4.1.4.

This isn't actually an issue with the dragging not working completely, it's just that the hitboxes are placed incorrectly when the developer tools are open, i.e. they overlap some part of the developer tools sidebar and some parts of the non-draggable elements, while not being active over some elements that are supposed to be draggable.

**Comment by Sombian** [comment]
-webkit-app-region: drag force an element to show contextmenu when right-clicked. this cant be ignored with javascript. is this intended behavior?

**Comment by Zyles** [comment]
4 years and counting.

**Comment by wells1013** [comment]
Mac 
electron 7.1.7
-webkit-app-region: drag

move window not work after called setSize

**Comment by caprice** [comment]
I have the same issue. Current window can be dragged to everywhere freely, but it doesn't work when i try to resize current window(remote.getCurrentWindow().setSize())

**Comment by yaddran** [comment]
> Mac
> electron 7.1.7
> -webkit-app-region: drag
> 
> move window not work after called setSize

If someone needs a workaround you can, in JS, switch style of a drag element to no-drag and after a small timeout to drag again. If you do this to one element the window will reinit the dragging of every element and magically all will work again.

**Comment by bpasero** [comment]
@yaddran how exactly does that work?

**Comment by yaddran** [comment]
> @yaddran how exactly does that work?

Well depending on the framework (or no framework) you use in the renderer process you need to change the element style from JavaScript (you can even use pure DOM and setTimeout). So, you set the style to no-drag, then do the setSize and then use setTimeout to schedule change of the element style back to drag (after 500 milli for instance). The window will resize and very soon after that the new drag will kick in and the browser will re-apply it to all elements that have drag, including the one that you are changing.

**Comment by bpasero** [comment]
@yaddran I see. I was hoping this trick would also just fix the issue where using the mouse will no longer move the window, but I tried it and it does not help for that case.

**Comment by yaddran** [comment]
> @yaddran I see. I was hoping this trick would also just fix the issue where using the mouse will no longer move the window, but I tried it and it does not help for that case.

Well... that is exactly what I am saying. It did solve the issue for me. Now even if I resize the window from the main process (this gets luckily triggered from the renderer process via ipc) my window is still movable with the mouse. I have discovered this by just changing the drag to no-drag and back in the developer tools. The window suddenly could again be moved with mouse... so I just programmed it in JS and it worked. Maybe you can first try this... apply no-drag on the element from developer tools, then change it to drag again and see if the window becomes movable with the mouse. If that is the case then my patch (I hope to remove it soon however) should work.

**Comment by bpasero** [comment]
@yaddran can you possibly come up with a sample hello world electron app to show this?

**Comment by Kilian** [comment]
I tried @yaddran's suggestion for the initial issue with devtools open, but unfortunately it doesn't fix it for that case.

**Comment by bpasero** [comment]
Will https://github.com/electron/electron/pull/21704 fix this actually?

**Comment by pfrazee** [comment]
@bpasero interested to find out!

**Comment by Kilian** [comment]
#21704 is in the release 7.1.9, so I tried it out and no luck.

**Comment by pfrazee** [comment]
@Kilian confirmed in my projects as well

**Comment by aaBaO** [comment]
Hi, here is a problem.
1. I set a custom div `-webkit-app-region: drag` first
2. Use a menu item in `main process` send a message to `renderer process`
3. Set my my custom div `-webkit-app-region:no-drag`

My div can't be `undraggable`, but if i open the `dev tools` it works.

**Comment by blakewatson** [comment]
> A workaround for those that are affected by this long standing bug - if you hover the mouse over the top edge of the window until you see a resize cursor and then hold and drag to the side instead of up and down to resize it will let you move the window.

For me, this workaround actually works on _any_ edge. For example, position your mouse cursor at the right edge until the resize pointer appears. Then, move your mouse cursor vertically instead of horizontally. You will then be able to move the window in any direction.

**Comment by muneebbug** [comment]
Had this issue on electron v 14.0.1 and 15.0.0 beta releases but downgrading to v ^13.0.0 solved my issue

**Comment by EnterVPL** [comment]
I have the same problem with drag

> System: Windows 10
> Node v14.17.6
> Electron 14.0.1

**Comment by muneebbug** [comment]
> I have the same problem with drag
> 
> > System: Windows 10
> > Node v14.17.6
> > Electron 14.0.1

Try downgrading to electron v 13.0.0

**Comment by EnterVPL** [comment]
> > I have the same problem with drag
> > > System: Windows 10
> > > Node v14.17.6
> > > Electron 14.0.1
> 
> Try downgrading to electron v 13.0.0

I got 13.3.0 version and drag is working ❤❤❤

**Comment by Wehaveall** [comment]
Why the option -webkit-app does not show to me when writing?
