### ISSUE TITLE
[Bug]: Electron Validation Bypass in kind-of

### ISSUE THREAD

**Issue by pavkcon** [electron/electron#36480]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.1.8

### What operating system are you using?

macOS

### Operating System Version

macOS

### What arch are you using?

x64

### Last Known Working Electron version

19.1.8

### Expected Behavior

kind-of 6.x prior to 6.0.3 are vulnerable to a Validation Bypass. A maliciously crafted object can alter the result of the type check, allowing attackers to bypass the type checking validation. Affected of this package are vulnerable to Validation Bypass. It leverages the built-in constructor of unsafe user-input to detect type information. However, a crafted payload can overwrite this built in attribute to manipulate the type detection result.

### Actual Behavior

The fixed has been created at [#36479](https://github.com/electron/electron/pull/36479)

### Testcase Gist URL

https://github.com/electron/electron/pull/36479

### Additional Information

https://github.com/advisories/GHSA-6c8f-qphg-qjgp
[CWE-668](https://cwe.mitre.org/data/definitions/668.html)
CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N

**Comment by nornagon** [comment]
This doesn't appear to affect users of Electron, so I'm going to close this.
