### ISSUE TITLE
[Bug]: Network.getResponseBody work incorrect

### ISSUE THREAD

**Issue by keyiis** [electron/electron#36490]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.0

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Expected Behavior

```
let win = new BrowserWindow({
        webPreferences: {
            webSecurity: false,
            sandbox: false,
        }
});
this.debug(win);
win.loadURL("https://www.zhipin.com");

function debug(win: BrowserWindow) {
        let _debugger = win.webContents.debugger;
        _debugger.attach('1.1');
        _debugger.on('message', (event, method, params) => {
            if (method === 'Network.responseReceived') {
                let url = params?.response?.url;
                if (url && url.startsWith('https://www.zhipin.com/wapi/zpgeek/search/joblist.json?')) {
                    console.log(url, params.response.mimeType);
                    _debugger.sendCommand('Network.getResponseBody', { requestId: params.requestId }).then(res => {
                        console.log(res.body);
                    }).catch(err => {
                        console.log("_debugger.sendCommand", err);
                    });
                }
            }
        })
        _debugger.sendCommand('Network.enable');
    }
```
I hope get response.body

### Actual Behavior

But get error
```
_debugger.sendCommand [Error: No resource with given identifier found]
```

**Comment by nornagon** [comment]
Does this work with Chromium? It seems like a DevTools issue, not an Electron issue. If so, file a bug at https://crbug.com.

**Comment by keyiis** [comment]
@nornagon When I add the `debug()` before `win.loadURL`,the chrome devtool can't capture url(https://www.zhipin.com/wap.....) response, If I remove `debug()` function,the devtool can capture response.

**Comment by keyiis** [comment]
@nornagon In addition,This url returns a lot of content, it may be transmitted in pieces.

**Comment by keyiis** [comment]
continue

**Comment by codebytere** [comment]
Closing as i've reproduced this in Chrome DevTools and as such agree with the path forward proposed here: https://github.com/electron/electron/issues/36490#issuecomment-1332965823
