### ISSUE TITLE
DeviceId constraints parameter is not functional for Camera

### ISSUE THREAD

**Issue by gurkanarkas** [electron/electron#36497]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

8.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I have two camera on my laptop. (Integrated and Usb) I am trying to switch with device id but parameter is not working. 

```
async function startCamera(arg) {
  if (await navigator.mediaDevices.getUserMedia) {
    const constraints = {
      audio: false,
      video: {
        deviceId: arg,
      },
    };

    await navigator.mediaDevices
      .getUserMedia(constraints)
      .then(function (stream) {
        let totalstream = new MediaStream();
        [cameraTrack] = stream.getVideoTracks();
        totalstream.addTrack(cameraTrack);
        video.srcObject = totalstream;
        video.play();
      })
      .catch(function (err0r) {
        alert(err0r);
      });
  }
}
```

### Actual Behavior

If i set width and heigth parameters as constraints, camera is automatically opened which is available for resolution. 

Whatever i send as parameter deviceId like below, always USB Camera is opening. But if i remove width and heigth parameters then integrated camera is opening.

`const constraints = {
      audio: false,
      video: {
        deviceId: arg,
        width: { ideal: 4096 },
        height: { ideal: 2160 },
      },
    };`

My USB Camera: Razer Kiyo Streamer

**Comment by nornagon** [comment]
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).
