### ISSUE TITLE
[Bug]: Unable to Launch Windows 11 (Arm64) running on Parallels Desktop 18 off MacBook Pro M1 Max

### ISSUE THREAD

**Issue by InnovateAsterisk** [electron/electron#36491]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

latest

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows 11 (Arm64) running on Parallels Desktop 18 off MacBook Pro M1 Max

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

> npm start  

Should start the application

### Actual Behavior

```
npm start

> siperb@0.0.2 start
> electron-forge start

√ Checking your system
√ Locating application
√ Loading configuration
√ Preparing native dependencies [1s]
√ Running generateAssets hook


[4900:1130/075144.519:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=18
[4900:1130/075144.551:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=18
[4900:1130/075144.566:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=18
[4900:1130/075144.566:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=18
[4900:1130/075144.582:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=18
[4900:1130/075144.601:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=18
[4900:1130/075144.609:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=18
[4900:1130/075144.625:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=18
[4900:1130/075144.625:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=18
[4900:1130/075144.625:FATAL:gpu_data_manager_impl_private.cc(441)] GPU process isn't usable. Goodbye.
```

### Additional Information

I'm pretty sure its because of the Parallels emulation, but unsure ho to fix it.

I only want to make the Windows Executables for distribution, may main system is the host Mac, and this works fine for both ```npm start``` and ```npm run make```

Also, while im here... on the windows instance the command ```npm run make``` also fails with:
```
npm run make

> siperb@0.0.2 make
> electron-forge make

√ Checking your system
√ Loading configuration
× Resolving make targets
  › Could not find module with name '@electron-forge/maker-squirrel'. If this is a package from NPM, make sure it's listed in the devDependencies…
■ Running package command
■ Running preMake hook
■ Making distributables
■ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: Could not find module with name '@electron-forge/maker-squirrel'. If this is a package from NPM, make sure it's listed in the devDependencies of your package.json. If this is a local module, make sure you have the correct path to its entry point. Try using the DEBUG="electron-forge:require-search" environment variable for more information.
```
But interestingly:
```
 npm list @electron-forge/maker-squirrel
siperb@0.0.1 X:\SIPerb\DesktopApp(win32)
`-- @electron-forge/maker-squirrel@6.0.3
```

**Comment by nornagon** [comment]
Unfortunately this isn't within our scope to fix. This is either a Parallels bug, or a Windows bug, or a Chromium bug.

Try running with --disable-gpu.

**Comment by InnovateAsterisk** [comment]
```app.commandLine.appendSwitch('no-sandbox');``` in the main.js worked fine, but i'm assuming I wouldn't deploy like this... not sure what the real world impact would be.

> Disables the Chromium [sandbox](https://www.chromium.org/developers/design-documents/sandbox). Forces renderer process and Chromium helper processes to run un-sandboxed. Should only be used for testing.

As for the ```npm run make``` this is still a problem, I can't solve.

**Comment by InnovateAsterisk** [comment]
This is the solution to the ```npm run make``` problem:
https://github.com/electron/forge/issues/2656#issuecomment-1103845609
