### ISSUE TITLE
[Bug]: Launched app from Electron is not correctly focused

### ISSUE THREAD

**Issue by lmiller1990** [electron/electron#36506]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

^ I found some (linked below) but I think they are different enough to warrant a separate issue.

### Electron Version

21.x

### What operating system are you using?

macOS

### Operating System Version

Monterey

### What arch are you using?

arm64 (including Apple Silicon)
intel also has the same problem

### Last Known Working Electron version

Not sure, I think this is a problem introduced by MacOS, not a specific electron version. I tried some old electrons, they have the same problem.

### Expected Behavior

When I launch a browser from Electron, it should be automatically focused. I need to spam click to get it to focus.

Note: to reproduce this you must **wiggle your mouse rapidly while the new window is opening**. This sounds silly, but this is very consistently reproducible. The longer the process takes to launch, the more obvious the problem.

### Actual Behavior

Need to click a bunch of times to get a mouse event to trigger.

Minimal Video (second time I open chrome, it exhibits the bug. Notice how many times I click to focus the search bar): https://github.com/cypress-io/cypress/issues/21743#issuecomment-1332788841

I first found this in Cypress, which is a test runner that launches a browser from an electron app. You can see it happening there, too, in this video: https://github.com/cypress-io/cypress/issues/21743#issuecomment-1277739066

This only happens on MacOS, both arm64 and intel. It doesn't happen on windows or linux. I think it was introduced in a more recently MacOS update. We didn't change any of our deps.

### Testcase Gist URL

https://github.com/lmiller1990/electron-bug-freezing

### Additional Information

Related, maybe: https://github.com/electron/electron/issues/36364, https://github.com/electron/electron/issues/36108

I would love to debug/fix this but I have zero idea where to even start, or if this is even something we can fix in electron core?

There is a workaround - if you change to another window and change back, it works as expected. You can do this programatically, eg something like this "works"

```js
electron.showBrowserWindow()
electron.hideBrowserWindow()
focusActiveBrowserWindow()
```

But you get a flicker of the electron app when you show + hide, which looks unpolished and isn't ideal.

**Comment by lmiller1990** [comment]
Hm, this may not be electron specific after all, but a bug in MacOS. I posted an even more minimal reproduction here: https://github.com/cypress-io/cypress/issues/21743

I might leave this to see if anyone else has something similar or a work around, but I'm thinking this is probably outside the scope of electron.

**Comment by nornagon** [comment]
Yeah, I think you're right that this is a macOS issue. I'm going to close it.

**Comment by lmiller1990** [comment]
Yep, thanks - my bad, I'll see if I can figure out a work around and share it here.
