### ISSUE TITLE
Module not found: Error: Can't resolve 'fs/promises' in ${PATH to puppeteer in node_modules}

### ISSUE THREAD

**Issue by ThalyssonLeite** [electron/electron#36514]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Expected Behavior

I am running a react app with Electron and puppeteer. 

in main.js

```
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false
    },
  })
```

But the error its still there:
 ```
$ yarn build
yarn run v1.22.19
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'fs/promises' in 'C:\Users\Edilza Leite\my-apps\node_modules\puppeteer-core\lib\esm\puppeteer\node'
```

What is the problem? Could you guys help me out?
By the way, the pure app with React compiles and runs the electron build perfectly. In the App.tsx I call a function in a **secundary script** called `find-final-date.ts` and there I call puppeteer, this all works well, it's something in compile time.., Node integration should be covering this and puppeteer should get access to fs module right? 

### Actual Behavior

...

**Comment by nornagon** [comment]
Thanks for reaching out!

This seems like an issue with your setup, not an Electron bug. You will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by ThalyssonLeite** [comment]
SOLUTION: Learn how to use Inter-process Communication (IPC) sending events that triggers the functions that I need. And not calling them in the frontend with nodeIntegration on. That will work for some cases but the best is to use ipc that is easy to use btw. Doing that It works.
