### ISSUE TITLE
[Bug]: uncaughtExceptionMonitor not called for unhandled rejection

### ISSUE THREAD

**Issue by SimonSiefke** [electron/electron#36526]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

22.10

### What arch are you using?

x64

### Expected Behavior

`uncaughtExceptionMonitor` should be called when an unhandled error or an unhandled rejection occurs.

### Actual Behavior

In Electron `uncaughtExceptionMonitor` is only called when an unhandled error occurs. 

This is different from NodeJs, where `uncaughtExceptionMonitor` is called for an unhandled errors and for unhandled rejections.

![exception](https://user-images.githubusercontent.com/23744935/205052647-5ecefdcb-64d0-4399-a0a3-abb4298b3793.png)

### Testcase Gist URL

https://github.com/SimonSiefke/electron-uncaughtExceptionMonitor-bug

**Comment by nornagon** [comment]
gist version for easy [Fiddle](/electron/fiddle)ing: https://gist.github.com/159cfcb9baab3431cf9d4c02282089d2

**Comment by nornagon** [comment]
still seems to be happening.

**Comment by nornagon** [comment]
Ah, actually, I think this is possibly intended behavior, per https://github.com/electron/electron/pull/29244#issuecomment-860735951
