### ISSUE TITLE
[Bug]: Crash in View::SchedulePaintInRectImpl

### ISSUE THREAD

**Issue by t57ser** [electron/electron#36521]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.4

### What operating system are you using?

Windows

### Operating System Version

10.0.19042

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

Electron should not crash

### Actual Behavior

![image (1)](https://user-images.githubusercontent.com/10595986/205010389-fdaec039-e6f5-4a69-8dc4-df5cb62b7e3e.png)

Unhandled exception thrown: read access violation.
this-> was 0x5.

### Additional Information

Still trying to find a way to consistently reproduce this
It appears like this is happening after a window.close()

**Comment by nornagon** [comment]
I see "OnDpiChanged" in the list there, perhaps it happens when a window is closed at the same time as a monitor is unplugged/plugged in?

**Comment by t57ser** [comment]
I thought so too but that does not seem to be the case since this crash was reported a couple times.
The crashlogs always show the same thing. Highly unlikely that users would be able to change the dpi exactly as the window closes.
The app logs also show no dpi changed event but always the same workflow
- window opens via window.open
- user does stuff
- window gets closed via window.close
Still waiting on feedback what exactly users have been doing at that point

**Comment by t57ser** [comment]
Seems like it might be related to dpi after all. 
Got a user who can reproduce this every time and only happens if a screen has dpi higher than 100%
So what seems to happen is that the user works on a second screen with higher dpi and when the window closes it gets moved to the main monitor (don't know the reason yet) and the main monitor has dpi 1.
That would explain why we get into the ondpichanged right at closing

**Comment by t57ser** [comment]
FYI this does not happen with electron 21
