### ISSUE TITLE
[Bug]: Call to getUserMedia failed

### ISSUE THREAD

**Issue by vitaliyzolotoy** [electron/electron#36529]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.0

### What operating system are you using?

macOS

### Operating System Version

Ventura

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

After calling `askForMediaAccess` and got approved from user, device should be available for use (camera or mic) with `MediaDevices.getUserMedia()`

### Actual Behavior

Getting next error `Call to getUserMedia failed: DOMException: Could not start video source` after second attempt while calling `askForMediaAccess `

In general, permissions from user granted, but using media devices is blocked

### Testcase Gist URL

https://gist.github.com/vitaliyzolotoy/df1c7401eeeb92d14b7fc94b02ad6b92

**Comment by vitaliyzolotoy** [comment]
Hi, here is link to Fiddle: https://gist.github.com/cd7135fa07f0215cc9e39c5296cfcec9
To reproduce my issue you need to `Package Fiddle` and run app twice, (on first app will ask you for mac and camera permissions, on second you will see `all to getUserMedia failed: DOMException: Could not start video source` error)

**Comment by dsanders11** [comment]
@vitaliyzolotoy, please reduce your repro Fiddle to not needing third-party dependencies like `twilio-video`.

> To reproduce my issue you need to `Package Fiddle` and run app twice, (on first app will ask you for mac and camera permissions, on second you will see `Call to getUserMedia failed: DOMException: Could not start video source` error)

Please clarify what "run app twice" means here - start the app, close the app, start it again? Or start the app, then start a second instance of the same app?

**Comment by williamli0707** [comment]
I have a similar issue - when I run the app directly with `electron-forge start`, the app does ask for camera permissions. When I build my app for Apple silicon and run the app on my M1 MBP, the app correctly asks for camera permissions. However, when I build for Mac x64 with `electron-builder --mac --x64`, the app does not work on my M1 Mac through Rosetta nor through a x64 Mac - both on Ventura - with the same error "DOMException: Could not start video source". 

I have tried to resolve this by requesting permissions with `navigator.permissions.query({name: 'camera'})`, however, my console says that permissions are granted. When I check my Security and Privacy settings, however, my app is not listed under the Camera section. I think that the app somehow thinks it has permissions when it doesn't, and then unsuccessfully turns on the camera.

My code which turns on the camera: 
`let enableCam = function () {
navigator.permissions.query({name: 'camera'})
.then((permissionObj) => {
    console.log(permissionObj.state);
})
if (hasGetUserMedia()) {
    if(videoPlaying) {
        disableCam();
    }
    else {
        const constraints = {
            video: true,
            width: 224,
            height: 224
        };
        navigator.mediaDevices.getUserMedia({video: true}).then(stream => {
            video.srcObject = stream;
            webCamStream = stream;
            console.log("found stream");
            video.addEventListener('loadeddata', function () {
                videoPlaying = true;
                console.log("adding listener");
                enableCamButton.textContent = "Disable Webcam"
                captureImageButton.classList.remove("disabled");
            });
        }, err => console.log(err));
    }
} else {
    console.warn('getUserMedia() is not supported by your browser');
    enableCamButton.textContent = "Get User Media Not Supported";
}`

Although the 
`navigator.permissions.query({name: 'camera'})
.then((permissionObj) => {
    console.log(permissionObj.state);
})`
 logs "granted", the permissions are not granted.

**Comment by williamli0707** [comment]
Here's a fiddle which shows the problem - https://gist.github.com/65eb1ae8b254f00c28f96688acbe418c
When run on my M1 Mac, it works with both "Run Fiddle" and "Package Fiddle." 
When run on an x64 Mac, or when run through Rosetta on an M1 Mac, it works with "Run Fiddle" but not "Package Fiddle."

**Comment by changyushun** [comment]
the camera work perfectly with npm start mode, but when we run the package or make command mode, the app could not get video source, it's show 'domexception could not start video source'

**Comment by ProdigyView** [comment]
> Hi, here is link to Fiddle: https://gist.github.com/cd7135fa07f0215cc9e39c5296cfcec9 To reproduce my issue you need to `Package Fiddle` and run app twice, (on first app will ask you for mac and camera permissions, on second you will see `Call to getUserMedia failed: DOMException: Could not start video source` error)

Yes! I have exact issue on Windows. Works fine the first time, 2nd time it completely failes.

**Comment by Aetherall** [comment]
Same issue here, on windows, latest electron version.
![image](https://github.com/electron/electron/assets/13298494/393d2934-326e-4924-b068-0afd1786ad22)
I cannot see my application in windows privacy settings, and from the renderer and main thread, all permissions are granted

**Comment by oppsDayly** [comment]
This is not a bug; it is due to the limited transmission capacity of the USB 2.0 interface, which does not support two or more video streams simultaneously. To resolve this, you need to connect the USB interface of the second video stream's camera to a USB 3.0 port.
