### ISSUE TITLE
[Child window with same attribute as Main One]: 

### ISSUE THREAD

**Issue by MaxESP** [electron/electron#36522]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I have develloped an Electron nodejs  async Serial app with these fitures:

1 open 3 serial ports with option of baudrates 
![serial](https://user-images.githubusercontent.com/41333143/205009611-dda866df-7285-4a1e-801c-3e40504c2985.png)

2 The l index.html main windows  is link to a renderer js with animate charts live .

![screen 2](https://user-images.githubusercontent.com/41333143/205011410-f539333a-68b7-4ffc-a50a-b86d3bb254dc.png)
3 I have create a child parent window from main window to extand space for new charts .

4 I want to stream or link async Serial port read to the child window

### Proposed Solution

no found

### Alternatives Considered

It' would be a great fiture to mirror the main attribute to shild window

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by MaxESP** [comment]
Thanks a lot for the comment i will try.
