### ISSUE TITLE
Docs link from Electron apps show Page Not Found

### ISSUE THREAD

**Issue by Ucok23** [electron/electron#36525]
I installed electron and it comes with a desktop app with some links, unfortunetely, Docs link show Page Not Found in electron website

![Screenshot from 2022-12-01 18-19-50](https://user-images.githubusercontent.com/42701951/205040989-e54ca00a-0eea-4600-bb89-8356df86e847.png)

![Screenshot from 2022-12-01 18-20-55](https://user-images.githubusercontent.com/42701951/205041000-11b05187-8c17-4f11-b051-de0155474985.png)

It's just nice to get our new user a working Docs link

**Comment by erickzhao** [comment]
I think this is easiest solved with a CDN redirect in the website. Please hold!

**Comment by erickzhao** [comment]
Should be fixed now.
