### ISSUE TITLE
how to get the process  memory & cpu  info 

### ISSUE THREAD

**Issue by fishbar** [electron/electron#3653]
`proess.memoryUsage()` seems only calculate the node process, not include the webview.

is there any way to monitor the webview mem-usage and cpu info, just like the chrome task manager

**Comment by paulcbetts** [comment]
We could really use this in the Slack client, I might put some work into porting something like chrome://memory-internals over

**Comment by fishbar** [comment]
counting on this feature,  :100:

**Comment by zcbenz** [comment]
Closed with #5526.
