### ISSUE TITLE
[Bug]: settrafficLightPosition on macOS calculates incorrectly for RTL system languages

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#36539]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS ventura 13.0.1

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

<img width="807" alt="‏لقطة الشاشة ٢٠٢٢-١٢-٠٢ في ٧ ٢٨ ٣٣ ص" src="https://user-images.githubusercontent.com/964386/205172660-1e95a7ac-cb60-4873-8a27-e93586547cb0.png">

### Actual Behavior

<img width="804" alt="‏لقطة الشاشة ٢٠٢٢-١٢-٠٢ في ٧ ٢٨ ٥٧ ص" src="https://user-images.githubusercontent.com/964386/205172682-87a89c5c-a178-4e25-b2a8-923d50f079c5.png">

### Testcase Gist URL

https://gist.github.com/deepak1556/3025154b48cb156126cfdcc74338ec8e

### Additional Information

Set the system preferred language to any RTL language value and restart the OS. When system preferred language is in RTL and application language is set to `en`, the traffic light positions are calculated from outside the window frame positions.

**Comment by deepak1556** [comment]
`base::i18n::IsRTL` evaluates to `RTL` even when `--lang=en-US` is passed this is because application locale is set to preferred language on macOS during startup via [OverLocaleWithCocoaLocale](https://source.chromium.org/chromium/chromium/src/+/main:ui/base/l10n/l10n_util_mac.mm;l=45-58) which happens before the resource bundle is loaded causing incorrect margin calculation for traffic lights in [window_button_proxy.mm](https://github.com/electron/electron/blob/main/shell/browser/ui/cocoa/window_buttons_proxy.mm). I think there are two points to address this issue,

1) Fix margin calculation for traffic lights under RTL
2) Implement `--force-ui-direction` similar to chrome https://chromium-review.googlesource.com/c/chromium/src/+/956297 if applications wants to display in LTR

**Comment by codebytere** [comment]
@deepak1556 it looks like `base::i18n::IsRTL()` is correctly evaluating to false when --lang=en-US is passed - i think the issue is the native macOS element dimensions 🤔

**Comment by deepak1556** [comment]
> it looks like base::i18n::IsRTL() is correctly evaluating to false when --lang=en-US is passed

Yeah it is an error from my end, I missed the `--lang` flag in my previous testing.

**Comment by deepak1556** [comment]
@codebytere some feedback I got from my team for this change, other native applications on macOS which support application locale like `TextEdit.app`, `Notes.app`, `Edge.app`, `Chrome.app` does not change the direction of native controls and always respect the system locale. So it seems only Electron would differ in behavior if started to respect application locale for the native controls. Here are some screenshots for when the system locale is RTL and application locale is set to `en-US` for the above applications,

**TextEdit**
<img width="582" alt="‏لقطة الشاشة ٢٠٢٣-٠١-٢١ في ١٤ ٣٣ ٣١" src="https://user-images.githubusercontent.com/964386/213845688-df07c217-3c82-49c7-b499-c244be54e050.png">

**Notes**
<img width="993" alt="‏لقطة الشاشة ٢٠٢٣-٠١-٢١ في ١٤ ٣١ ٥٦" src="https://user-images.githubusercontent.com/964386/213845696-0b9dadeb-f13d-45ad-aca7-40e30ceaea35.png">

**Safari**

<img width="681" alt="‏لقطة الشاشة ٢٠٢٣-٠١-٢١ في ١٤ ٥٢ ٠١" src="https://user-images.githubusercontent.com/964386/213845745-c6f9ef91-7895-4f4a-91b4-54b03011b737.png">



Also the test case in https://github.com/electron/electron/issues/36539#issue-1472047068 still renders the controls incorrectly with `Electron >= 22.0.2`, and it would be addressed if we always respected the system locale. Adding `--force-ui-direction=rtl` for the same test case renders correctly from right-to-left. Thoughts ?
