### ISSUE TITLE
[Bug]: setWindowOpenHandler results in incorrect dark mode background color for text/plain content

### ISSUE THREAD

**Issue by jeremyspiegel** [electron/electron#36538]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Electron 21.3.1, 22.0.0, and the latest 24.0.0-nightly.20221201

### What operating system are you using?

macOS 13 and Windows 11

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

n/a

### Expected Behavior

When the system is in dark mode, and a popup is opened via `window.open` to a URL returning content of type `text/plain`, the resulting popup window should have a black background with white text. This happens correctly unless `mainWindow.webContents.setWindowOpenHandler` is called.

See https://www.loom.com/share/4af414156762410e994b5e2a56d997c7 for the correct behavior when `mainWindow.webContents.setWindowOpenHandler` is commented out.

![image](https://user-images.githubusercontent.com/776117/205159936-c9a7719a-8bad-47e7-84f4-9af693eb08ee.png)

### Actual Behavior

With the call to `mainWindow.webContents.setWindowOpenHandler` uncommented, the popup window incorrectly has white text with a white background. See https://www.loom.com/share/15aadf785f3740c5b8f07239ea1e46ed for the actual behavior.

![image](https://user-images.githubusercontent.com/776117/205159884-fa522568-c10d-4f71-a878-98c3d08b0265.png)

### Testcase Gist URL

https://gist.github.com/36925a2377d0b8c7c67abd9816c2f411

**Comment by jeremyspiegel** [comment]
I think this is related to https://github.com/electron/electron/pull/28054. cc @MarshallOfSound

**Comment by dsanders11** [comment]
Text in the opened window first turned white starting in 19.0.0-nightly.20220325.

**Comment by dsanders11** [comment]
I'm investigating root cause, but in the mean time, this is a workaround which causes the behavior to be the same whether `setWindowOpenHandler` is set or not:

```js
mainWindow.webContents.setWindowOpenHandler(() => ({action: 'allow', overrideBrowserWindowOptions: { backgroundColor: '000000' }}))
```

The `backgroundColor` value doesn't matter, as it will be immediately replaced by the expected background color for dark mode.
