### ISSUE TITLE
[Bug]: Renderer crash in webrtc 

### ISSUE THREAD

**Issue by bporch** [electron/electron#36559]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 22H2 19045.2251

### What arch are you using?

x64

### Expected Behavior

Renderer should not crash

### Actual Behavior

Renderer is crashing with the following webrtc error:

[29944:1130/152504.373:FATAL:audio_encoder_cng.cc(284)]

Fatal error in: ..\..\third_party\webrtc\modules\audio_coding\codecs\cng\audio_encoder_cng.cc, line 284
last system error: 0
Check failed: info.encoded_bytes == 0 (160 vs. 0)
Encoder delivered data too early.

### Additional Information

This occurs in a telephony app using SIP.js and a webrtc gateway, and is triggered when several reinvites occur in quick succession.  I am also opening an issue with the webrtc team, but want to see if this can be handled in a better way in Electron, rather than crashing the entire renderer process.

This is reproducible in my environment.  Please let me know what additional info would be helpful.

**Comment by dheerajkysetti** [comment]
@bporch Could you provide a title to the bug.

**Comment by JoergvonBlon** [comment]
Hi,

I have already reported a similar issue here with repro steps and logs.
https://bugs.chromium.org/p/webrtc/issues/detail?id=14776

@bporch Any new insights from your end to get this resolved?

**Comment by itsthisjustin** [comment]
This needs to be opened back up. Same problem still exists with no good fixes. We are able to reproduce by simply muting and unmuting the microphone while connected to a session.

**Comment by ProdigyView** [comment]
Its hard for me to reproduce to but i am streaming games through Electron, and this error tends to happen when my  video sessions where I screenshare the desktop for over an hour and 15 minutes.

**Comment by zeid0ne** [comment]
I have the same problems

**Comment by nikwen** [comment]
Just for anyone taking a look at this issue: A fix for the crash reported by @bporch [seems to have landed](https://issues.webrtc.org/issues/42225071#comment20) in Chrome 128. Thus, it should be fixed in Electron 32 and later.
