### ISSUE TITLE
[Bug]: Electron is crashing while rendering google.com(/ authentication google page) in webview

### ISSUE THREAD

**Issue by muhamedsalih-tw** [electron/electron#36573]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

13.0.1 - Ventura

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

21.3.3

### Expected Behavior

Extending or reopening closed story: #33808

Should render and navigate google.com/ google's specific centralised login

[Note we use] - react-electron-web-view": "2.0.1"

### Actual Behavior

Crashes when we try to navigate/load/call api from the google page/its common auth page

### Additional Information

It kind off happening only in google and its app/apis

**Comment by codebytere** [comment]
The repro in the original issue does not crash anymore - please provide a new reproducible sample demonstrating the problem or this issue will be closed in 10 days.
