### ISSUE TITLE
[Bug]: webview crashes when nodeintegration is on

### ISSUE THREAD

**Issue by balajiv113** [electron/electron#36608]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

13.0.1

### What arch are you using?

x64

### Last Known Working Electron version

21.x.x

### Expected Behavior

when nodeintegration: on is set to the tag, webview should not crash

### Actual Behavior

Sample repo for reproducing this issue,

https://github.com/balajiv113/google-electron/blob/main/src/app.tsx#L19 - has `nodeintegration: on`

`yarn install & yarn start` - Notice the gmail loads but once clicked on login the webview crashes

### Testcase Gist URL

https://github.com/balajiv113/google-electron

**Comment by miniak** [comment]
https://www.electronjs.org/blog/a-quiet-place-22

**Comment by Zen33** [comment]
The same issue, any solutions?

**Comment by codebytere** [comment]
@balajiv113 your repro does not work as described:

<img width="1552" alt="Screenshot 2023-01-04 at 3 58 19 PM" src="https://user-images.githubusercontent.com/2036040/210583283-b5142f6b-9c79-479e-a97a-45826ac21e2c.png">

this is what i see when running it. Additionally - it would be helpful if you could provide a simpler repro. That reduces the number of assumptions we need to make and makes it easier to isolate the problem.

**Comment by balajiv113** [comment]
@codebytere 
My bad, the command to run is `yarn install && yarn start`

I believe the above image is shown when login is clicked. This is the issue itself. 

If you remove `nodeintegration: "on"` from this line https://github.com/balajiv113/google-electron/blob/main/src/app.tsx#L19 then it is working.

**Comment by balajiv113** [comment]
@codebytere 
Simpler steps to reproduce. Hope this helps.
https://gist.github.com/balajiv113/225af2ebce6e8adb681013f917883af5

**Comment by codebytere** [comment]
Still unable to repro with the above gist, unfortunately: it let me log in with no issue on macOS running 22.0.0. What is the crash you're seeing? Please attach a stacktrace.

**Comment by balajiv113** [comment]
@codebytere There is no stacktrace except for the UI not shown (Exactly live the image you have added)

> Still unable to repro with the above gist,

Can you verify if webview tag has nodeintegration="on" like in gist. 
Am able to consistently reproduce it in electron 22.0.0. I can even add a screen recording if needed.

**Comment by balajiv113** [comment]
I tried the same on macOS M1 Ventura. Same issue is present.

Steps are below,
- Open electron-fiddle
- Select electron 22.0.0
- Load the gist
- Run App, Notice webview crash (blank black screen instead of login page)

**Comment by codebytere** [comment]
Fixed in https://github.com/electron/electron/compare/v24.0.0-nightly.20221214...v24.0.0-nightly.20221215 - https://github.com/electron/electron/commit/9e7fbc7021d8d716c43782249a552e55289c35db more specifically.

**Comment by vraravam** [comment]
_Can this be backported to v22 and v23 please?_ We are stuck in 21.3.3 since we are unable to upgrade to v22.x

**Comment by vraravam** [comment]
> _Can this be backported to v22 and v23 and a patch revision released soon please?_ We are stuck in 21.3.3 since we are unable to upgrade to v22.x

Looks like this is already backported into v22 (at least - I haven't checked v23). Since v22.0.0 was released 42 days ago, and this is a blocker (at least for us), could we request a new patch version be released asap with this fix? TIA
