### ISSUE TITLE
[Feature Request]: Is there a way to remove or modify guid?

### ISSUE THREAD

**Issue by ascodelife** [electron/electron#36609]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Some users think that collecting guid and reporting it in crashReporter may infringe their privacy. I'm not sure if there is a way not to collect or remove guid escalations.

### Proposed Solution

I would like to provide a way a method to remove guid before reporting.  
Thank you for your time.

### Alternatives Considered

Or you can provide a way to modify them so that I can assign them to an empty value. Thanks!

**Comment by MarshallOfSound** [comment]
`guid` is a completely randomly assigned value and has no bearing on the machine at all (deleting it and reinstalling will give you a new id), if your users want to remove it they can screw with the `Crashpad` db file on their machines.  Or they can trust you to not store it.

We don't have any intentions to mess with Crashpad to any extent.
