### ISSUE TITLE
[Bug]: WebUSB API device list is always empty (attached devices are ignored).

### ISSUE THREAD

**Issue by 7ombie** [electron/electron#36615]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0-alpha.1

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Electron should detect my Novation Launchpad X (a class-compliant, USB MIDI device).

### Actual Behavior

The device shows up in `chrome://usb-internals` (in stock Chrome), but when I call `navigator.usb.getDevices` in Electron, the device does not appear in the device list.

The device list is always empty.

### Additional Information

Codewise, I basically have this in my `index.js` file:

``` js
const { app, BrowserWindow } = require("electron");

app.whenReady().then(function() {

    const selectDevice = function(event, details, callback) {
        console.log("device list:", details.deviceList); // this array is always empty
        event.preventDefault();
    };

    const renderer = new BrowserWindow(options); // note: `options` is defined IRL
    renderer.webContents.session.setPermissionCheckHandler(() => true);
    renderer.webContents.session.on("select-usb-device", selectDevice);
});
```

In the renderer process, I just have a call to `navigator.usb.requestDevice` (inside a `keydown` event listener that only exists to ensure that the call is in response to a user gesture).

Note: The filters I'm passing to the WebUSB API are empty (though I tried Novation's ID (`0x1235`) too).

**Comment by parkerlreed** [comment]
Even with the list being empty, do you still get the popup? Trying to test https://yume-chan.github.io/ya-webadb/ on v23 alpha 3 on Linux and not getting any dialog when clicking Add > USB

**Comment by 7ombie** [comment]
@parkerlreed - Nope. There's no popup. However, I was under the impression that Electron doesn't use the popup (the permission/device-selection dialog that Chrome uses on the Web). Electron has its own API that we can use to implement a dialog, or we can just go ahead a talk to the device.

**Comment by parkerlreed** [comment]
Thanks. That's about what I figured. Once the list being empty gets cleared up, I may poke the webadb developer and see if there can be some special; handling for Electron.

**Comment by 7ombie** [comment]
Cool cool.

It *might be* worth trying to push for a change to Electron. Electron is used for creating custom browsers, and they need to render the Web correctly, so Electron must provide some means for ensuring that standards-compliant webapps render as is.

I feel like this should have come up already, and so there may be a discussion or feature I'm just not aware of.

They're all away for Christmas, so the community have to fend for themselves till the new year.

**Comment by 7ombie** [comment]
@parkerlreed - On reflection, I'm thinking it may just be the responsibility of whoever uses Electron to make a Web browser to polyfill standards-compliant JavaScript APIs, using the corresponding Electron APIs, as required.

If that's correct, you'd need to write some code in Electron to provide the missing functions that the webapp you're trying to use expects to be there.

Again, I may be wrong about this.

**Comment by bochenev** [comment]
I have the same issue. But I accidentally find solution( on Linux): 
the problem was with permissions to  /dev/bus/usb/
So after change access rights to 777 it is works(wrong way, of course)

**Comment by 7ombie** [comment]
@bochenev - Thanks. I'll look into it. I'm on Mac, but it's hopefully related. Much appreciated.

**Comment by JoseCadenas** [comment]
I too am experiencing the same issue (on MacOS)

**Comment by 7ombie** [comment]
I've had another look at it, but cannot get it to work on Mac `:(`

I'd be grateful if @jkleinsc could give us some idea what the situation is, please?

**Comment by jkleinsc** [comment]
@7ombie can you test with this fiddle and see if it works for you? https://gist.github.com/231437c733f6a5ba187c64d53a08cda2

Also, have you tested with any other devices?

When I test locally with that Fiddle with 23.0.0-alpha.1, I get back a device list.   I am on Monterey 12.6.2, so it is possible there's an issue with Ventura.

Also, given the nature of the device you are using you could also try using [WebHID](https://www.electronjs.org/docs/latest/tutorial/devices#webhid-api)

**Comment by 7ombie** [comment]
@jkleinsc - Sorry. Just saw this. I'll look into it, and let you know (I don't currently have Electron Fiddle installed).

**Comment by 7ombie** [comment]
@jkleinsc - Sorry I haven't got back to this yet. I have a new laptop that only has Type-C ports, and all my devices and cables are for my old set up (which didn't use Type-C). I have one adapter, so need to get a couple more. Long story short, I haven't forgotten - just haven't had time.

**Comment by parkerlreed** [comment]
@jkleinsc Is python's http.server suitable for trying that out?

I tried with that and electron 23 beta8 on Linux and it says no device selected. 

![image](https://user-images.githubusercontent.com/841440/216849966-7d2278f0-0c51-4356-b12a-352e1f61bacb.png)

**Comment by parkerlreed** [comment]
Oh Im stupid I didnt reailize I just had to pass the folder to electron 

![image](https://user-images.githubusercontent.com/841440/216850041-7a30ef91-e11e-4c14-b971-2f643ea54950.png)

**Comment by desyatirikov** [comment]
I experience the same issue on macOS Monterey. It works fine on both Fedora Linux and Windows 10, but I can'n make it work on my mac.

**Comment by jkleinsc** [comment]
@desyatirikov @7ombie can you verify if Electron/Fiddle has access to Bluetooth on your macOS System Preferences -> Security & Privacy -> Bluetooth, eg:
<img width="616" alt="Screen Shot 2023-02-07 at 4 29 00 PM" src="https://user-images.githubusercontent.com/609052/217370583-e2e2015d-f0a6-482a-b75c-3713c702e339.png">

**Comment by desyatirikov** [comment]
I just tried to give Fiddle app access to Bluetooth, restarted the app and tried again, and nothing changed. I still receive an empty list when I try to list usb devices but when I use [webadb](https://app.webadb.com/) I can see my android phone in the list.

**Comment by parkerlreed** [comment]
@desyatirikov Not quite on topic but to let you know the webadb you are using a a freebooted github version with no changed and advertisements. You can use the straight upstream version here https://yume-chan.github.io/ya-webadb/

**Comment by jkleinsc** [comment]
@desyatirikov @7ombie ignore my comment above... I was also looking at a Bluetooth issue and forgot this was a WebUSB issue.

**Comment by desyatirikov** [comment]
@jkleinsc I tested the same code on my another MacBook Pro with an Intel processor and macOS Big Sur and it works as expected. So, the issue can be related to arm64 MacBooks, newer macOS versions (Monterey/Ventura), or maybe USB-C vs USB2/3.

**Comment by jkleinsc** [comment]
@desyatirikov thanks for the update.  I'll check on an arm64 mac to see if its specific to that platform.

**Comment by jkleinsc** [comment]
I just verified that it is an arm64 specific issue.  On my Intel mac, it works fine; but does not work on an arm64 mac.

**Comment by JoseCadenas** [comment]
I agree, Windows works fine but arm64 Mac failing with same and modified code.

**Comment by jkleinsc** [comment]
I found the underlying issue and am going to try and find a fix.

**Comment by 7ombie** [comment]
> I found the underlying issue and am going to try and find a fix.

Nice! Sorry I wasn't more help with this.

I'm on an M1 too. Thanks to everyone who helped out with this.

**Comment by JunzheFan** [comment]
@jkleinsc hello sir, is electron webusb available in electron 22.0.0, cos I am not able to retrieve my usb device on that specific version(return empty list), whereas i can get my usb device on the new electron version 24.0.0,  I dropped my electron version as the 22.0.0 is the last one that supports Win7

**Comment by jkleinsc** [comment]
@JunzheFan WebUSB support was added to Electron v23.0.0.  It was not available in 22.

**Comment by JunzheFan** [comment]
@jkleinsc Thanks sir, and one more question, I am confused which web APIs have been implemented by Electron as of now, for instance, this media device API https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices, it's exposed by the same Navigator object as the WebUSB,   I can confirm this API is working but it's not officially documented in the electron's doc https://www.electronjs.org/docs/latest/tutorial/devices,  so is this kind of Web API working out of the box that does not need any specific implementation?

**Comment by jkleinsc** [comment]
@JunzheFan MediaDevices is an older API and it doesn't have the same permissioning requirements that newer device APIs like WebUSB need.  As a general rule of thumb if a web api doesn't use a permissioning prompt (eg pick a USB device), it should work without changes needed to Electron, but if it is a newer API that requires a permissioning prompt in Chromium, then additional work is needed in Electron to implement it.

**Comment by JunzheFan** [comment]
@jkleinsc thanks sir, really appreciate your good work and clarification

**Comment by JunzheFan** [comment]
@jkleinsc Hello sir, I assumed you are the one who implemented the WebHID API, I recently encountered a bug where I got DOMException: failed to write the report - permission not allowed,  this exception only occurs when I use the device received during hot-plugged event, for example  
```
navigator.hid.addEventListener("connect", async ({ device }) => {
});
```
I can confirm the device has been granted permission and I can successfully send the report if the device is already connected to the pc and I find it from 
```
 await navigator.hid.getDevices()
```
Do you think this bug belongs to WebHID itself? and if can receive the connect event, I think it somehow indicates the device has been granted permission otherwise this event won't fired at all ?  My device is just a headset connector which is not a keyboard nor mouse. if possible, could you give me some hints, thanks in advance
