### ISSUE TITLE
[Bug]: `getUserMedia` triggers extra call to `setPermissionRequestHandler` handler with missing metadata

### ISSUE THREAD

**Issue by rf-figma** [electron/electron#36629]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

12.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

20.3.8

### Expected Behavior

In Electron 20.3.8, registering a handler with `setPermissionRequestHandler` and calling `navigator.getUserMedia({ audio: true }, ...)` in the browser produces one call to the handler, which includes a `securityOrigin` property in its `details`.

### Actual Behavior

Starting in Electron 21.0.0, the handler is also called a second time, with a `details` param that doesn't include a `securityOrigin` or `mediaTypes` property. Returning `false` for this call will cause the `getUserMedia` call to fail. Example log output from Fiddle:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/114442851/206822049-094ec08e-3ed4-4968-b491-419a4790329b.png">

### Testcase Gist URL

https://gist.github.com/rf-figma/35de0678214fe97a8e736b64e1a26ead

**Comment by codebytere** [comment]
Bisected to https://github.com/electron/electron/compare/v21.0.0-nightly.20220719...v21.0.0-nightly.20220720 - one of 3c7d446fad5da5ea15e0795cbe1870a242efd1f4 or be7f90481de6581401bb5f03ab18d2f89b1daef1 probably did it

**Comment by rf-figma** [comment]
Thanks @codebytere!
