### ISSUE TITLE
[MAS Rejection]: non-public or deprecated API _Py_Initialize

### ISSUE THREAD

**Issue by alebx** [electron/electron#36621]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Electron Version

18.3.0

### Rejection Email

Hello,

Thank you for your efforts to follow our guidelines. There are still some issues that need your attention.

If you have any questions, we are here to help. Reply to this message in App Store Connect and let us know. 

Guideline 2.5.1 - Performance - Software Requirements

Your app uses or references the following non-public or deprecated APIs:

Symbols: _Py_Initialize

The use of non-public or deprecated APIs is not permitted on the App Store, as they can lead to a poor user experience should these APIs change and are otherwise not supported on Apple platforms.

Next Steps

It would be appropriate to revise your binary and remove any references to the non-public or deprecated APIs identified above.

If you are using third-party libraries, update to the most recent version of those libraries. If you do not have access to the libraries' source, the following command line tools can help you identify the location of problematic code:

- The "strings" tool can output a list of the methods the library calls.

- The "otool -ov" tool will output the Objective-C class structures and their defined methods.

Resources

- We are constantly reevaluating and identifying non-public APIs that you may have been using for an extended period of time. Always use [public APIs and frameworks](https://developer.apple.com/documentation/) and ensure they are up to date.

- If there are no alternatives for providing the functionality your app requires, you can use [Feedback Assistant](https://feedbackassistant.apple.com/welcome) to submit an enhancement request.

**Comment by MarshallOfSound** [comment]
Electron 18 is not a supported version of electron and `_Py_Initialize` is not used in the Electron or Chromium codebases currently.  Please

1. Update Electron to a supported version (preferably latest)
1. Ensure that that symbol is not in a native module

**Comment by alebx** [comment]
@MarshallOfSound  Ok, thanks for the fast reply!
