### ISSUE TITLE
[Bug]:   File Open dialog does not remember Last opened directory

### ISSUE THREAD

**Issue by petervanderwalt** [electron/electron#36628]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.17

### What operating system are you using?

Windows

### Operating System Version

All

### What arch are you using?

x64

### Last Known Working Electron version

9.x

### Expected Behavior

Running a web interface in Electron.  Using ```<input type=file ...>``` in the UI, clicking the input opens the standard Windows file browse dialog.  In older versions of Electron this window remembered the last directory accessed.  We updated to Electron 19 - and now the dialog no longer remembers the last directory accessed.  It keeps going back to the last directory you used in older versions of our application.  Most windows applications remembers the last folder you were in next time you open a File > Open dialog

### Actual Behavior

Running a web interface in Electron.  Using <input type=file> in the UI, clicking the input opens the standard Windows file browse dialog.  In older versions of Electron this window remembered the last directory accessed.  We updated to Electron 19 - and now the dialog no longer remembers the last directory accessed.  It keeps going back to the last directory you used in older versions of our application.  Most windows applications remembers the last folder you were in next time you open a File > Open dialog

### Additional Information

https://github.com/OpenBuilds/OpenBuilds-CONTROL/issues/270

**Comment by petervanderwalt** [comment]
Posted on Discord too https://discord.com/channels/745037351163527189/1052326878456848464

**Comment by petervanderwalt** [comment]
> Hello @petervanderwalt. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

Sorry I cannot - we switched to using Native Dialogs (lots of rewrite work we had to do, but unfortunately we had to solve the problem).  Hope you find the cause!

**Comment by simboonlong** [comment]
Same issue. For me was Mac, electron bump from ^15.1.2 (working) -> ^21.3.1 (stopped working)

**Comment by codebytere** [comment]
I can't reproduce this and no repro has been provided, so unless one is this issue will be closed.

**Comment by simboonlong** [comment]
tried a fresh v21.3.1 and couldn't replicate too. i must be dreaming, it works

**Comment by codebytere** [comment]
if this crops up again let us know and we'll reopen :)
