### ISSUE TITLE
[Bug]: Font Scaling not correct under wayland

### ISSUE THREAD

**Issue by snaggen** [electron/electron#36632]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.3

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 37

### What arch are you using?

x64

### Expected Behavior

Due to multi dpi setup, and how badly that works still, I run my screens at 100%, adapt the resolution and compensate using the scaling options in Gnome Tweak UI, under the Font tab using the Scaling slider there. I use a scaling factor of 1.25
When I run my electron apps with X (using XWayland) things are scaled correctly, and the toolbar font is the same size as normal gnome applications. 
And this is the expected bahaviour when I enable Wayland also, to have the same size toolbar fonts as regular gnome applications.  

### Actual Behavior

The actual behaviour is that the font for a Electron application using Wayland to render (using the ozon flags), is that the fonts are smaller than the other native gnome applications, and notably smaller than the fonts were when rendering using X. My guess is that the X version handles the font scaling, but the Wayland implementation only renders the font at 100% instead of using the scaling factor of 1.25 I use. 

### Additional Information

I can compensate most apps by simply zooming in, but that only affects the appication frame and not the toolbar, which looks to small.

**Comment by ipeacocks** [comment]
Still the case.

**Comment by revolver-ocelot-saa** [comment]
I have this issue as well. This is still the case for me using an electron application running on electron 22.5.2. 

As an example this issue is reproducible using VS Code running on Wayland. If you set a font scaling factor in Gnome Tweak UI and launch VSCode using Wayland `code --ozone-platform-hint=auto --enable-features=WaylandWindowDecoration` VSCode will not use the font scaling factor.

**Comment by Xathros1** [comment]
I just tried the appimage of webcord 4.3 and this seems to fix the scaling issue. it bumps electron to v25.

**Comment by bbhtt** [comment]
Still an issue, probably

**Comment by LSeelig** [comment]
This affects me.

**Comment by VPaulV** [comment]
Hi guys, did somebody find a solution?

**Comment by LSeelig** [comment]
bump

**Comment by Interpause** [comment]
bump. no way this is stale, im almost fed up enough to try and fix it if i have time

**Comment by chf0x** [comment]
I fixed it by removing every electron application from my system xD

**Comment by kennu** [comment]
I still have to add `--ozone-platform-hint=auto --enable-features=WaylandWindowDecoration` manually to .desktop files of Slack and other Electron apps after every update. Why can't it be the default?

**Comment by LSeelig** [comment]
This is a Chromium issue, I think. I don't know what the electron devs can do about it.

**Comment by ReillyBrogan** [comment]
> I still have to add `--ozone-platform-hint=auto --enable-features=WaylandWindowDecoration` manually to .desktop files of Slack and other Electron apps after every update. Why can't it be the default?

`cp /usr/share/applications/slack.desktop ~/.local/share/applications/` and then update the latter. Desktop files in `~/.local/share/applications` have precedence over desktop files with the same name in `/usr/share/applications`.

**Comment by Interpause** [comment]
> I still have to add `--ozone-platform-hint=auto --enable-features=WaylandWindowDecoration` manually to .desktop files of Slack and other Electron apps after every update. Why can't it be the default?

Another way this can be done is via `~/.config/electron-flags.conf`, see: https://wiki.archlinux.org/title/wayland#Configuration_file

**Comment by elcste** [comment]
I seems scaling Chromium in response to the text scaling factor [was added to Chromium 113](https://nickdiego.dev/blog/chromium-ozone-wayland-the-last-mile-stretch/#text-scaling). It is disabled by default; enable with the flag chrome://flags/#wayland-ui-scaling. Presumably this will filter down to Electron once it gets Chromium 131.
