### ISSUE TITLE
[Bug]: webview not work if install folder is not in  C drive

### ISSUE THREAD

**Issue by colining** [electron/electron#36637]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.2

### What operating system are you using?

Windows

### Operating System Version

not in my pc

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

11.5.0

### Expected Behavior

webview work in any drive

### Actual Behavior

recently I upgrade electron 20 from 11.

1% user give me feedback ,that webview not load. I can't recurrent this bug in my pc.

so I do some research in my user's pc.

I give them really simple demo, and it's work in C drive and broke in D drive.

It's very oddly bug, so I check the realease https://releases.electronjs.org/release/compare/v20.0.2/v20.3.8

and find some thing relative with this bug. so I just upgrade to 20.3.8.

I need more info about it. 

thanks a lot

### Testcase Gist URL

https://gist.github.com/789a8aac546212ba88aaf6d93ebd4f0f

### Additional Information

I'm trying the browser-view,  it's need hard work. so webview is my best solution on current stage.

**Comment by mushan0x0** [comment]
bump
