### ISSUE TITLE
[Bug]: NextJS devmode broken when using sandbox: false

### ISSUE THREAD

**Issue by Kilian** [electron/electron#36647]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0-alpha.1

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Last Known Working Electron version

21.3.3

### Expected Behavior

When loading a next.js site in developer mode (like https://github.com/vercel/next-learn/tree/master/basics/demo ) the page loads as normal even with 
```
contextIsolation: false,
sandbox: false,
```
applied to the renderer. This works fine in 21.x and before

### Actual Behavior

With 
```
contextIsolation: false,
sandbox: false,
```
Applied to the renderer, nextjs doesn't apply its style and remove it's FOUC css that sets display:none on the `body` while it loads. 

In 22.0.0-alpha.1 and all versions since, the display:none CSS remains applied and no other styling is loaded.

I assume this has something to do with the replaced timers that `sandbox: false` causes, that might have changed or updated between 21.x and 22.x (Looking at https://github.com/electron/electron/releases/tag/v22.0.0-alpha.1 nothing jumped out)

### Testcase Gist URL

https://gist.github.com/5d51fe87bfd611d2fbc5adf2904dceb9

### Additional Information

The gist just tries to load http://localhost:3000, which you can start by getting the code from https://github.com/vercel/next-learn/tree/master/basics/demo

When using 21.x to start you can see the page load, from 22 onward the page remains blank.

**Comment by Kilian** [comment]
Bisected the nightlies to v22.0.0-nightly.20220830 being the first to break: 

https://github.com/electron/electron/compare/v22.0.0-nightly.20220829...v22.0.0-nightly.20220830

The node upgrade jumps out to me.

I'll see if I can isolate whatever isn't working in the next dev server and create a minimal test case with that.

**Comment by tomaszczura** [comment]
Any news on this?
