### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 82318179** [electron/electron#36645]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21

### What operating system are you using?

Windows

### Operating System Version

21

### What arch are you using?

x64

### Last Known Working Electron version

21

### Expected Behavior

setBounds()
After the setBounds function is executed, the interface does not send changes immediately, so how do you get that the interface has already sent changes? Which event can listen to the end of setBounds function execution and the interface has been adjusted? After the interface adjustment is complete, we can continue to execute other function code.

### Actual Behavior

I now need to know the notification after the execution of the setBounds function is completed and the interface adjustment is completed.

### Additional Information

I now need to know the notification after the execution of the setBounds function is completed and the interface adjustment is completed.

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
