### ISSUE TITLE
[Bug]: Cannot decompile/unzip app.asar

### ISSUE THREAD

**Issue by TheWalkingSea** [electron/electron#36644]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

This should give me the original code, I used ```npx asar extract app.asar output``` and I have used 7zip

### Actual Behavior

I get this massive error with the file at the top (btw it errors at the second letter which happens to be a b)

`
![image](https://user-images.githubusercontent.com/91487740/207220662-91f74dd2-12ed-473b-b086-8ffdfb162593.png)
`

**Comment by miniak** [comment]
https://github.com/electron/asar/issues
