### ISSUE TITLE
[Bug]: electron-updater: Could not get code signature for running application

### ISSUE THREAD

**Issue by skirsdeda** [electron/electron#36640]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.3

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

x64

### Expected Behavior

electron-updater not throwing any errors

### Actual Behavior

If App is launched while update is being installed (just after "Beginning installation" message appears in ShipIt log, i.e. `~/Library/Caches/<APP_BUNDLE_ID>.ShipIt/ShipIt_stderr.log`), sometimes electron-updater would error out with:
```
16:33:42.133 › Error: Could not get code signature for running application
    at Server.<anonymous> (/Applications/<APP>/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:168:36)
    at Object.onceWrapper (node:events:641:28)
    at Server.emit (node:events:527:28)
    at Server.emit (node:domain:475:12)
    at emitListeningNT (node:net:1406:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
16:33:42.135 › Error: Error: Could not get code signature for running application
    at Server.<anonymous> (/Applications/<APP>/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:168:36)
    at Object.onceWrapper (node:events:641:28)
    at Server.emit (node:events:527:28)
    at Server.emit (node:domain:475:12)
    at emitListeningNT (node:net:1406:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
This is not always reproducible (very sensitive to timing, it seems). Looks like code signature checking inside launched App fails simply because ShipIt is replacing Bundle files at that time and it probably crashes being unable to find some file which existed just a moment ago.
Tested with older version of App being updated to current version. App is properly signed/notarized, etc. and auto-update works in normal circumstances. 

### Steps to reproduce:

- Install older version of App
- Open ShipIt logs with `tail -f  ~/Library/Caches/<APP_BUNDLE_ID>.ShipIt/ShipIt_stderr.log`
- Launch App from terminal like `/Applications/<APP>/Contents/MacOS/<APP>` (or `open -a <APP>`)
- Wait for auto-updater to download new version ("Detected this as an install request" should be seen in ShipIt log)
- Quit App
- Wait for update to begin: "Beginning installation" message in ShipIt log
- Launch App from terminal immediately
- Optional: repeat from beginning if error did not appear

**Comment by skirsdeda** [comment]
Wrong repo, moved to https://github.com/electron-userland/electron-builder/issues/7315

**Comment by skirsdeda** [comment]
Sorry for the confusion, this is about mac updater which is internal to electron repo, therefore the bug belongs here.

**Comment by rahulbansal16** [comment]
bump

**Comment by rahulbansal16** [comment]
> bump

@skirsdeda how did you resolve this?

**Comment by skirsdeda** [comment]
@rahulbansal16 we didn't, but it's a race condition, so it doesn't happen frequently. Difficult to say for sure though 🙂
