### ISSUE TITLE
[Bug]: Source code of ElectronJS external NodeJS files are not protected

### ISSUE THREAD

**Issue by lincdh** [electron/electron#36662]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.3

### What operating system are you using?

Other (specify below)

### Operating System Version

Linux, MacOS, Windows

### What arch are you using?

x64

### Expected Behavior

The external NodeJS files should be in an hidden format not easily to be modified for unwanted purposes.

### Actual Behavior

The external NodeJS files in the extraResources folder inside Resources folder(show package content in MacOS). However the files there are shown in the exact raw JS files with their node_modules, and package.json no matter in development or production.

### Additional Information

I have an Electron app where the development version of it is working with the JS files that later to be packed into app asar.

In production the files cannot be found and the app stop working.

In package.json at build key, we can specify build: "extraResources": [ "./extraResources/**"] to access to eg: give the app access to external JS file,

So I have to push those files into the extraResources folder inside Resources folder(show package content in MacOS). However the files there are shown in the exact raw JS files with their node_modules, and package.json no matter in development or production.

![Screen Shot 2022-12-14 at 22 25 35](https://user-images.githubusercontent.com/21136244/207643626-31a9ddb5-d7b6-4e5d-acc4-1cac761d3048.png)

**Comment by miniak** [comment]
This is an issue with the packager not Electron itself
