### ISSUE TITLE
[Bug]: Crashes with "nable to get application ASN from launchservicesd ..."

### ISSUE THREAD

**Issue by jthomas-dd** [electron/electron#36671]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.0

### What operating system are you using?

macOS

### Operating System Version

12.6.1 (21G217)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

18.3.6

### Expected Behavior

Electron does not crash.

### Actual Behavior

We are getting crashes with the above error, with a similar stack trace after updating electron from `18.3.6` to `21.2.0`

This seems similar to the crash from this past issue: https://github.com/electron/electron/issues/16919,
however we are not making a `mas` build, only a `mac` build.

```
Thread 14819755 Crashed:
0   libsystem_kernel.dylib          0x18718ad98         <unknown>
1   libsystem_c.dylib               0x1870fa33c         abort
2   HIServices                      0x18ce5f4c0         _RegisterApplication
3   HIServices                      0x18ce5c450         GetCurrentProcess
4   HIToolbox                       0x18fe9fa20         MenuBarInstance::GetAggregateUIMode
5   HIToolbox                       0x18fe9f98c         MenuBarInstance::IsVisible
6   AppKit                          0x189db8698         <unknown>
7   AppKit                          0x189db6340         <unknown>
8   AppKit                          0x189db5f48         <unknown>
9   Electron Framework              0x10d1b683c         base::MessagePumpMac::Create (message_pump_mac.mm:1000)
10  Electron Framework              0x10d18062c         base::SingleThreadTaskExecutor::SingleThreadTaskExecutor (single_thread_task_executor.cc:16)
11  Electron Framework              0x10cbf7798         content::UtilityMain (utility_main.cc:119)
12  Electron Framework              0x10ab5d7cc         content::RunOtherNamedProcessTypeMain
13  Electron Framework              0x10ab5e188         content::ContentMainRunnerImpl::Run
14  Electron Framework              0x10ab5cca0         content::RunContentProcess (content_main.cc:437)
15  Electron Framework              0x10ab5d158         content::ContentMain (content_main.cc:465)
16  Electron Framework              0x10a8d5b2c         ElectronMain (electron_library_main.mm:26)
17  CoScreen Helper (Plugin)        0x1026609a0         <unknown>
18  dyld                            0x1028e508c         <unknown>
19  dyld                            0x1028e5154         <unknown>
20  dyld                            0x1028e510c         <unknown>
21  dyld                            0x1028e50f8         <unknown>
22  dyld                            0x1028e5104         <unknown>
```

Also with these annotations:

**Hiservices**
```
[_RegisterApplication(), unable to get application ASN from launchservicesd, and this application requires an ASN, so aborting.  error=#-1. ]
--
```

And **Launchservices**:
```
[rdar://problem/28724618 Couldn't create connection object <rdar://problem/28724618> Application unable to connect to launchservicesd for an unknown reason (received XPC_ERROR_CONNECTION_INVALID). XPC_ERROR_CONNECTION_INVALID from launchservice]
--
```

**Comment by codebytere** [comment]
@jthomas-dd there's no mention of what actions are being taken within the app or what might predicate this crash, whichj makes it much harder to diagnose. Could you please provide some form of a repro, or, if that's not possible, provide a description of what was happening in the app prior to the crash?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
