### ISSUE TITLE
[Bug]: calling minimize fails to minimize if the user is spam-clicking in the window that's being minimized

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#36673]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.1.1 (I think 22 as well but need to confirm)

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I expect that if I call `window.minimize()`, the window is minimized even if I'm clicking in the window

### Actual Behavior

If I'm spam clicking in the window, the window will fail to minimize. (I saw this happen only when loading a page in the window)

### Testcase Gist URL

https://gist.github.com/733114f51d98eb2554c1152656dc9603

### Additional Information

1. Start the gist
2. if you do nothing, the window will try to minimize every 5 seconds
3. if you spam click, the window won't minimize and `isMinimized()` correctly returns `false` in that case
4. if you slow down the clicking, it will minimize

possibly some OS quirk?

**Comment by codebytere** [comment]
This is, unfortunately, an OS limitation - native apps exhibit the same behavior under comparable circumstances.
