### ISSUE TITLE
[Bug]: If a `BrowserWindow` is created with `show: false`, the initial visibility state should be `visible`

### ISSUE THREAD

**Issue by cawa-93** [electron/electron#36692]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0-nightly.20220209

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Doc says:
https://github.com/electron/electron/blob/5fd7a43970c2bdfa1017a4b23098aec3dafbf513/docs/api/browser-window.md?plain=1#L125-L126

### Actual Behavior

```js
new BrowserWindow({show: false}).isVisible() // false
```

### Testcase Gist URL

https://gist.github.com/ab6f109180cdcb14ad0ce7d065bd924d

**Comment by Rohan-Dah** [comment]
Heyy.. I would like to work on this issue.. I'm a newbie to open source so can anyone please guide me through?

**Comment by issacgerges** [comment]
Hey @cawa-93! I believe what you're seeing here is as expected. That note in the docs specifically refers to the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) API. 

I've created a [fiddle](https://gist.github.com/10ae182df0eb070d384d411598e08a09) that shows that it does report the window as visible. When run it produces this output


<img width="501" alt="image" src="https://user-images.githubusercontent.com/44379112/208788250-559af5e6-df45-45c7-a298-07bdc642bdbc.png">

**Comment by cawa-93** [comment]
Thanks. I was a little confused in terms
