### ISSUE TITLE
[Bug]: Calling setBounds while listening to the window restore event crashes the main process 

### ISSUE THREAD

**Issue by twitharshil** [electron/electron#36705]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.5

### What operating system are you using?

Ubuntu

### Operating System Version

20.04.1

### What arch are you using?

x64

### Last Known Working Electron version

15.5.7

### Expected Behavior

The electron main process shouldn't crash while restoring the window 
<img width="1080" alt="Screenshot 2022-12-20 at 12 49 50 PM" src="https://user-images.githubusercontent.com/25850676/208606715-b5c5da41-32d9-4d34-8f3a-cd1c06d01fc0.png">

### Actual Behavior

Electron main process crashes while restoring the window. 

### Testcase Gist URL

https://gist.github.com/564c13c1a086e9f7dea3da3eec319310

### Additional Information

Steps to reproduce: 
1. Load the gist in fiddle 
2. Launch the application 
3. Minimise the window opened 
4. Restore the window

**Comment by twitharshil** [comment]
The issue got introduced b/w electron [v17.3.0-v17.3.1](https://github.com/electron/electron/compare/v17.3.0...v17.3.1)

**Comment by twitharshil** [comment]
cc: @deepak1556 @gerhardberger Can this be a side effect of any of your changes? Diff b/w the above two versions include couple of PR's only

**Comment by twitharshil** [comment]
I saw that when we try to restore the window from the minimized state, the Browser window restore event is getting emitted infinitely, because of which we are getting `RangeError: Maximum call stack size exceeded error`.

**Comment by deepak1556** [comment]
Thanks for bisecting and a minimal repro, Yeah this is a regression from https://github.com/electron/electron/commit/db0ad4f58de9724cc923a693b11ac28ca41390ba

This is an issue for ozone X11 backend, where we now [update window states based on bounds change](https://github.com/electron/electron/blob/5fd7a43970c2bdfa1017a4b23098aec3dafbf513/shell/browser/ui/electron_desktop_window_tree_host_linux.cc#L60-L70) to workaround a limitation in a chromium api. And during the state update, we [mark](https://github.com/electron/electron/blob/5fd7a43970c2bdfa1017a4b23098aec3dafbf513/shell/browser/ui/electron_desktop_window_tree_host_linux.cc#L128) the new state only after emitting user facing events and given these events re-enter JS currently we are causing a side effect of updating bounds in this example causing the infinite recursion.

**Comment by twitharshil** [comment]
@deepak1556 Can you suggest any workaround/proper fix to this issue? Currently, this impacts our application & we are looking for workarounds. 

Even if the fix is within electron layers we are fine to adopt those changes.

**Comment by deepak1556** [comment]
As a workaround, instead of changing the bounds synchronously you can delay the task with a `setImmediate` to avoid the recursion.

```js
mainWindow.on('restore', () => {
   setImmediate(() => {
      mainWindow.setBounds({
        x: 200, 
        y: 200, 
        width: 200, 
        height: 200
      })
    })
  })
```

**Comment by twitharshil** [comment]
Thanks @deepak1556 for [this](https://github.com/electron/electron/issues/36705#issuecomment-1359109602)  workaround, it works  :)
