### ISSUE TITLE
[Bug]: React context consumers use default value instead of provider value

### ISSUE THREAD

**Issue by aharron** [electron/electron#36706]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home version 19045

### What arch are you using?

x64

### Expected Behavior

Consumer components should receive data from the `value` prop in React context providers.

### Actual Behavior

Consumer components receive data from the default values used in the context creation. I haven't figured out how to add React to Electron Fiddle to create a reproducible test case, but here is example React code to illustrate the issue.

Context definitions:
```
export interface UserContextObj {
  user: CognitoUser | null;
  setUser: (user: CognitoUser | null) => void;
  signOut: () => void;
}

export const UserContext = createContext<UserContextObj>({
  user: null,
  setUser: () => {
    console.log("default method");
  },
  signOut: () => {},
});
```

Provider component:
```
import React, { useMemo, useState } from "react";
import { CognitoUser } from "@aws-amplify/auth";
import { UserContext } from "../Context/UserContext";

interface Props {
  children: React.ReactNode;
}

export const AuthProvider: React.FC<Props> = (props) => {
  const { children } = props;
  const [user, setUser] = useState<CognitoUser | null>(null);

  const signOut = () => setUser(null);

  const userContext = useMemo(
    () => ({ user, setUser, signOut }),
    [user, setUser, signOut]
  );

  return (
    <UserContext.Provider value={userContext}>{children}</UserContext.Provider>
  );
};
```

Component tree:
```
<AuthProvider>
  <TestAuth />
</AuthProvider>
```

Consumer component:
```
export const TestAuth: React.FC<{}> = () => {
  const { setUser } = useContext(UserContext);
  
  useEffect(() => {
    console.log('received setUser func: ', setUser);
  }, [setUser]);

  return <h1>test</h1>
}
```

### Additional Information

This has been reported as an issue on StackOverflow previously:
https://stackoverflow.com/questions/57399318/why-is-react-context-api-mis-behaving-in-electron-app

**Comment by nornagon** [comment]
It's unclear to me how this is an Electron issue. Does this also happen in the browser? If not—what's the difference?

**Comment by aharron** [comment]
This issue does not happen in the browser, here's a better description of the difference:

In browser-based React, a child component (consumer) of a context provider calling `useContext()` will receive the data passed in to the provider's `value` property if it exists, otherwise the consumer will receive the default data passed in to `createContext()`. When running React in Electron, consumer components appear to always receive the default data passed in to `createContext()` instead of the expected data passed in the `value` property.

In the above example, the expected behavior the function `setUser` received by the consumer component `TestAuth` should be a `setState` func passed in the `value` property of `UserContext.Provider`. In Electron, `TestAuth` instead receives the default `setUser` function defined in the creation of `UserContext`, defined as this:
```
() => {
    console.log("default method");
  },
```

Does this help?

**Comment by aharron** [comment]
Just following up here! @nornagon

**Comment by aharron** [comment]
NVM, this ended up being a silly mistake on my part. I had accidentally copied two definitions of the same context object into different files with the same name and certain components were importing from one vs. the other, causing the discrepancy.
