### ISSUE TITLE
[Bug]: Developer tools click link does not create a new page

### ISSUE THREAD

**Issue by 1339240789** [electron/electron#36715]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.17

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Expected Behavior

![image](https://user-images.githubusercontent.com/71307878/208800464-e0902998-8600-4d81-b99d-8e29761a43d9.png)
click the link should create a new page

### Actual Behavior

but nothing happen

**Comment by 1339240789** [comment]
@codebytere

**Comment by MAYANKpandey14** [comment]
hey, is this assigned to someone @1339240789 @codebytere

**Comment by codebytere** [comment]
This is not so much a bug as a feature request, as we do not currently support this behavior. I am looking into a simple implementation to address the issue.
