### ISSUE TITLE
[Feature Request]: Reduced versions

### ISSUE THREAD

**Issue by Coding-Kiwi** [electron/electron#36714]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

For the last version of my app I put a lot of work into properly bundling my javascript, treeshaking and refactoring to really bring down the bundle size only to notice that the bundled app is bigger than the last version! The reason is that I updated the electron version because of security improvements but the ever-growing app size is very frustrating.

Electron / chromium takes up about 95% of the final executable and **everytime I update the electron version, the app noticeably grows in size**. 

I could not find any information about what parts of chromium make up the most, but I do think a lot of the built-in features of chromium are not needed for most if not all electron apps. For example some apps work completely offline, might never play video or audio, never use spell checking, desktop capturing or navigation between urls..  just to name a few.

### Proposed Solution

Add a possibility to get a stripped down or feature-reduced version of electron / chromium / nodejs

### Alternatives Considered

Split up into modules which can be added when needed instead of forcing developers to always use a full-featured version of chromium / nodejs

**Comment by brjsp** [comment]
I maintain the electron package in openSUSE and we have noticed there's a lot which can be disabled when building electron/chromium. The following can be safely removed (and i wish official builds did disable them, bc they are completely useless dead code):

```bash
myconf_gn+=" enable_vr=false"
myconf_gn+=" enable_reading_list=false"
myconf_gn+=" enable_reporting=false"
myconf_gn+=" disable_fieldtrial_testing_config=true"
myconf_gn+=" build_with_tflite_lib=false"
myconf_gn+=" build_tflite_with_xnnpack=false"
myconf_gn+=" safe_browsing_mode=0"
myconf_gn+=" enable_captive_portal_detection=false"
myconf_gn+=" enable_browser_speech_service=false"
myconf_gn+=" enable_speech_service=false"
myconf_gn+=" enable_screen_ai_service=false"
myconf_gn+=" include_transport_security_state_preload_list=false"
myconf_gn+=" enable_web_speech=false"
myconf_gn+=" chrome_wide_echo_cancellation_supported=false"
myconf_gn+=" enable_downgrade_processing=false"
myconf_gn+=" enable_click_to_call=false"
myconf_gn+=" enable_webui_tab_strip=false"
myconf_gn+=" enable_webui_certificate_viewer=false"
myconf_gn+=" enable_background_contents=false"
myconf_gn+=" enable_xz_extractor=false"
myconf_gn+=" enable_feed_v2=false"
myconf_gn+=" ozone_platform_headless=false"
myconf_gn+=" angle_enable_gl_null=false"
myconf_gn+=" enable_paint_preview=false"



#Do not build Chromecast
myconf_gn+=" enable_remoting=false"
myconf_gn+=" enable_media_remoting=false"
myconf_gn+=" enable_service_discovery=false"


#do not build widevine
myconf_gn+=" enable_library_cdms=false"
```

The following can be removed if you don't use WebGPU (if you don't know what it is, you don't use it):
```bash
# Do not build WebGPU support. It is huge and not used by ANY known apps (we would know if it was — it's hidden behind an experimental flag).
myconf_gn+=" use_dawn=false"
```

The following can be removed if you don't use PPAPI and stuff which depends on it:
```bash
# do not build PDF support
myconf_gn+=" enable_pdf=false"
myconf_gn+=" enable_pdf_viewer=false"
myconf_gn+=" enable_print_preview=false"
myconf_gn+=" enable_basic_printing=false"

#do not build chrome pepper plugins support
myconf_gn+=" enable_plugins=false"
myconf_gn+=" enable_ppapi=false"
```

**Comment by Coding-Kiwi** [comment]
@brjsp interesting!

So I guess one would need to follow https://www.electronjs.org/de/docs/latest/development/build-instructions-gn for each platform and then supply the custom dist to the builder

Sadly no good instructions to build electron-windows on linux because everytime I tried to get visual studio running to build something I failed miserably

**Comment by ckerr** [comment]
So, Electron is probably _not_ going to get into shipping different flavors of every release. The system's current complexity is already pushing what can be maintained by the team's people and the team's CI system, so multiplying that with different options is probably not tenable for the project. (e.g. this has been proposed before for people who want to disable the memory cage and/or pointer compression).

But @brjsp has a pretty neat list there. I think it would be really worthwhile to look into that to see if some of those make sense to disable by default, making Electron better for everyone!

@brjsp if you disable everything in that list, what's the outcome that you're seeing? E.g. is the executable N% smaller?

**Comment by Coding-Kiwi** [comment]
I agree with @ckerr ! And I would also be interested in how much outcome there is, smaller executable? noticeable ram/cpu usage difference?

**Comment by codebytere** [comment]
Closing in agreement with @ckerr:

> So, Electron is probably not going to get into shipping different flavors of every release. 

this is not actionable as it stands.

**Comment by AtiaDjaber** [comment]
> I maintain the electron package in openSUSE and we have noticed there's a lot which can be disabled when building electron/chromium. The following can be safely removed (and i wish official builds did disable them, bc they are completely useless dead code):
> 
> ```shell
> myconf_gn+=" enable_vr=false"
> myconf_gn+=" enable_reading_list=false"
> myconf_gn+=" enable_reporting=false"
> myconf_gn+=" disable_fieldtrial_testing_config=true"
> myconf_gn+=" build_with_tflite_lib=false"
> myconf_gn+=" build_tflite_with_xnnpack=false"
> myconf_gn+=" safe_browsing_mode=0"
> myconf_gn+=" enable_captive_portal_detection=false"
> myconf_gn+=" enable_browser_speech_service=false"
> myconf_gn+=" enable_speech_service=false"
> myconf_gn+=" enable_screen_ai_service=false"
> myconf_gn+=" include_transport_security_state_preload_list=false"
> myconf_gn+=" enable_web_speech=false"
> myconf_gn+=" chrome_wide_echo_cancellation_supported=false"
> myconf_gn+=" enable_downgrade_processing=false"
> myconf_gn+=" enable_click_to_call=false"
> myconf_gn+=" enable_webui_tab_strip=false"
> myconf_gn+=" enable_webui_certificate_viewer=false"
> myconf_gn+=" enable_background_contents=false"
> myconf_gn+=" enable_xz_extractor=false"
> myconf_gn+=" enable_feed_v2=false"
> myconf_gn+=" ozone_platform_headless=false"
> myconf_gn+=" angle_enable_gl_null=false"
> myconf_gn+=" enable_paint_preview=false"
> 
> 
> 
> #Do not build Chromecast
> myconf_gn+=" enable_remoting=false"
> myconf_gn+=" enable_media_remoting=false"
> myconf_gn+=" enable_service_discovery=false"
> 
> 
> #do not build widevine
> myconf_gn+=" enable_library_cdms=false"
> ```
> 
> The following can be removed if you don't use WebGPU (if you don't know what it is, you don't use it):
> 
> ```shell
> # Do not build WebGPU support. It is huge and not used by ANY known apps (we would know if it was — it's hidden behind an experimental flag).
> myconf_gn+=" use_dawn=false"
> ```
> 
> The following can be removed if you don't use PPAPI and stuff which depends on it:
> 
> ```shell
> # do not build PDF support
> myconf_gn+=" enable_pdf=false"
> myconf_gn+=" enable_pdf_viewer=false"
> myconf_gn+=" enable_print_preview=false"
> myconf_gn+=" enable_basic_printing=false"
> 
> #do not build chrome pepper plugins support
> myconf_gn+=" enable_plugins=false"
> myconf_gn+=" enable_ppapi=false"
> ```

Where can I find this file?

**Comment by brjsp** [comment]
> Where can I find this file?

@AtiaDjaber the current version is always <a href="https://build.opensuse.org/package/view_file/home:dziobian:gulgul-ultron:19/nodejs-electron/nodejs-electron.spec?expand=1">here in the Open Build Service</a>. Also check the <a href="https://build.opensuse.org/package/view_file/home:dziobian:gulgul-ultron:19/nodejs-electron/create_tarball.sh?expand=1">tarball download script</a> in the same repo.
