### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SomeDevWeb** [electron/electron#36712]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home - ver 22H2

### What arch are you using?

x64

### Expected Behavior

This is not a bug per-se, but some expected code that is not present in the documentation and I don't know if it's even implemented. 
I am trying to write to a serial port (COM having an Arduino connected) and I manged to do the detecting and reading the ports by using this example: https://www.electronjs.org/docs/latest/tutorial/devices#web-serial-api
The problem is that neither there or nowhere else I could find any example or docs about how to write to the serial port. 
For example, there's this API doc: https://www.electronjs.org/docs/latest/api/structures/serial-port, but that does not have any code example or reference about the **writing** to a port...
I know there is the Node "serialport" module, but I'd much rather use a native approach than a third-party one.
Any suggestions/thoughts highly appreciated! :)
Thanks a lot for any replies!

### Actual Behavior

There is no code examples or documentation/mention for **writing** to a serial port.

### Additional Information

FIY, the node serialport electron example:
https://github.com/serialport/electron-serialport

**Comment by miniak** [comment]
Electron 17 is not supported

**Comment by dsanders11** [comment]
Hi @SomeDevWeb. You want to use the [Web Serial API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API) in the renderer to interact with the serial port. The Electron documentation you linked just shows you how to handle the permissions and port selection in the main process.
