### ISSUE TITLE
[Bug]: systemPreferences.getMediaAccessStatus('screen') doesn't retrieve new status once changed in macOS Preferences

### ISSUE THREAD

**Issue by ibc** [electron/electron#36722]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5 (21G72)

### What arch are you using?

x64

### Expected Behavior

`systemPreferences.getMediaAccessStatus('screen')` should return `granted` after granting "Screen Recording" permission to the app in macOS "Preferences - Security & Privacy".

### Actual Behavior

`systemPreferences.getMediaAccessStatus('screen')` still returns `denied` after granting "Screen Recording" permission to the app in macOS "Preferences - Security & Privacy".

### Additional Information

**STR:**

This is easy to reproduce in any Electron app running in macOS Monterey 21.5 (and probably any macOS version supporting "Screen Recoding"):

- I assume the Electron app is launched from `Terminal.app` so media permissions of the Electron app are the ones of `Terminal.app`.
- Before launching the Electron app ensure that "Microphone" and "Screen Recording" permissions are not enabled for `Terminal.app` in macOS "Preferences - Security & Privacy".
     <img width="679" alt="CleanShot-2022-12-21-at-11 22 57@2x" src="https://user-images.githubusercontent.com/16191/208882422-d088ed7c-1d8f-46b0-90cf-cd8379edecbe.png">
- Open `Terminal.app` and launch the Electron app.
- Run `systemPreferences.getMediaAccessStatus('microphone')`. It will return `denied` as expected.
- Run `systemPreferences.getMediaAccessStatus('screen')`. It will return `denied` as expected.
- Grant `Terminal.app` permission in "Microphone" and "Screen Recording" sections of "Security & Privacy". Don't close `Terminal.app` but click on "Later" button instead.
    ![CleanShot-2022-12-21-at-11 26 12@2x](https://user-images.githubusercontent.com/16191/208883104-4f71caa9-fe4e-46e7-9a61-7dc15d7c1d17.png)
- Run `systemPreferences.getMediaAccessStatus('microphone')`. Now it will return `granted` as expected.
- Run `systemPreferences.getMediaAccessStatus('screen')`. It will still return `denied`. This is the problem: 'screen' permission changes are not updated in Electron land when querying the permission again via `systemPreferences.getMediaAccessStatus('screen')`.

**Comment by MarshallOfSound** [comment]
This is expected behavior? The dialog tells you that your app won't be granted screen access till it's restarted.  As far as your app/macOS is concerned, it doesn't currently have access to the screen.  That's just how TCC works.

**Comment by ibc** [comment]
> This is expected behavior? The dialog tells you that your app won't be granted screen access till it's restarted.  As far as your app/macOS is concerned, it doesn't currently have access to the screen.  That's just how TCC works.

Well, I clearly proved in my STR that the same is not true for "microphone", right? This is, if you grant a running app "Microphone" permission then Electron reports "granted" for it.  But if you do the same for "Screen Recording" then Electron keeps reporting "denied". It's obviously inconsistent.

**Comment by MarshallOfSound** [comment]
The API returns the correct value.  In some cases where TCC is operating under inheritance (obtaining TCC from a parent process rather than via your own bundle ID) **some** TCC permissions can be granted without a restart.  That is just how the OS works, under the hood we are just asking the OS "do we have permission to do this" you can replicate this exact behaviour in a standalone cocoa based app and calling the same system APIs that Electron calls

**Comment by ibc** [comment]
From a colleague of mine:

> Looking into the source code of how screenshare permission grant is calculated: https://source.chromium.org/chromium/chromium/src/+/main:ui/base/cocoa/permissions_utils.mm;l=26;drc=b27c2e3d302825d806142462d8fc0d1e970b7720
> we can see that on macOS Ventura they use `CGPreflightScreenCaptureAccess` method which returns the correct permission every time even if you don't restart the app. So this issue is only relevant for users on older macOS versions than Ventura (e.g. Monterey). On older macOS versions a different custom heuristic is used based on window levels and names, which when I enabled it on my electron build, gives incorrect answer.
