### ISSUE TITLE
[Feature Request]: `input-event` of `webContents` doesn't provide scroll direction

### ISSUE THREAD

**Issue by Shintarot** [electron/electron#36726]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

`input-event` of `webContents` currently provides `inputEvent`, but there is no information about scroll direction here.

[webContents #event-input-event](https://www.electronjs.org/docs/latest/api/web-contents#event-input-event)
[InputEvent](https://www.electronjs.org/docs/latest/api/structures/input-event)

### Proposed Solution

Let me offer two suggestions.

Case 1: Provide a direction like `BrowserWindow`'s `swipe` event.

Case 2: Split `input-events`.
To begin with, isn't it unreasonable to handle mouse events and keyboard events in the same interface?

### Alternatives Considered

It might be possible to implement this by listening to `wheel` event on the renderer, but there are two drawbacks.

(1) It fires continuously during scrolling, and it is difficult to get the start/end of the scrolling.

(2) If not passive, performance will be affected.

**Comment by codebytere** [comment]
This is currently not supported by [`blink::WebInputEvent`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/common/input/web_input_event.h;l=51) which underpins the `input-event` object. Should this change, we are more than happy to look into adding requisite support.
