### ISSUE TITLE
[Bug]: macOS confirmation dialog does not show blue border around focused button when it is default

### ISSUE THREAD

**Issue by bpasero** [electron/electron#36721]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22

### What operating system are you using?

macOS

### Operating System Version

12.6.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

A focused button shows a blue border even when default button:

![image](https://user-images.githubusercontent.com/900690/208836917-442e9641-3ef7-4ab0-ac61-d934411be91e.png)

### Actual Behavior

A focused button does not show the blue border:

![image](https://user-images.githubusercontent.com/900690/208837077-0bb46a91-3fe1-479b-a2f5-8b0f893ec835.png)

### Testcase Gist URL

https://gist.github.com/d9bd650ffc1efcf61016cbc81ea35652

### Additional Information

This only seems to happen when using non-standard labels for the buttons. It requires this macOS setting:

![image](https://user-images.githubusercontent.com/900690/208837201-f1529993-651a-4fa0-8ea2-b9763ac8433b.png)

**Comment by codebytere** [comment]
Looks like it's to do with this logic: https://github.com/electron/electron/blob/470396d6aceb53817f003e7a0a8cf21eb673bb99/shell/browser/ui/message_box_mac.mm#L70-L87 that sets key equivalents and highlights buttons. I'll see what i can do!
