### ISSUE TITLE
Which is the lowest macOS version supported by electron ?

### ISSUE THREAD

**Issue by popod** [electron/electron#36730]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.0

### What operating system are you using?

macOS

### Operating System Version

ventura

### What arch are you using?

x64

### Expected Behavior

Changes of macOS supported version by electron should be added as breaking changes in the changelog and in `docs/breaking-changes.md` ?

### Actual Behavior

Which is the lowest macOS version supported by electron ?

The README.md say "macOS (High Sierra and up)...", but longer as I know, the latest supported version is macOS El Capitan..

The changes have been made on october 5, 2022 on branch 20, 21, 22 and up : https://github.com/electron/electron/commit/6196393c942c254ce95289655306edfd1fb8e28e

But I've seen nothing about this changes in the breaking changes or releases notes.

Could you please help me ? Thanks you !

**Comment by popod** [comment]
Hi @codebytere

Please, could you give me a feedback about this ?

Thank you

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by popod** [comment]
Hi @codebytere 

Thank you for your reply. But this issue is not really a question..

I want to know what is the lowest macOS version supported by electron v21. This is an important point for us and a lot of developers, I think.

The official electron documentation seems to be wrong about that or the changelog are missing some important information about the dropping support of macOS Sierra and El Capitan !

So please, could you check and give me an answer ? Thank you in advance !

**Comment by evrial** [comment]
> Thanks for reaching out!
> 
> Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

Coming from google search, this response wasn't productive, just wasting my time for sake for formality
