### ISSUE TITLE
[Feature Request]: Add .paks for usb-internals page

### ISSUE THREAD

**Issue by nikolaxmarkovic** [electron/electron#36738]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Since electron has support for WebUSB https://github.com/electron/electron/pull/36289 it may be useful to add .paks for usb-internals built-in page

### Proposed Solution

extending electron_paks.gni to include chrome/usb_internals_resources.pak as done for webrtc-internals https://github.com/electron/electron/pull/24010 

### Alternatives Considered

alternative would be to implement it in electron

**Comment by codebytere** [comment]
@nikolaxmarkovic if we do decide to go down this path, it's unfortunately not as simple as adding the `.paks` - the usb internals page has its own full set of UI and other logic we'd need to subclass in Electron and add UI bindings for (which would need to be customized in order to work in Electron).

**Comment by nikolaxmarkovic** [comment]
Thank you @codebytere for looking into it. I did not realize UI dependency complexity and I guess it we can close the ticket since similar functionality can be built within application itself using window.navigator.usb interface.
