### ISSUE TITLE
Add event to capture crashes

### ISSUE THREAD

**Issue by benogle** [electron/electron#3674]
When `autoSubmit` is set to `false`, nothing happens. To enable an opt-in crash reporting experience, we could add an event that fires on the restart after the crash happens. 

Something like 

``` js
app.on('crashed', (event) => {
  dialog.showMessageBox({
    message: "The app crashed, send report? plz?"
    buttons: ['No', 'Yes']
  }, (response) => {
    if (response == 'Yes') {
      // Would be nice
      event.sendReportToServer()

      // Or maybe, we need to post manually?
      postCrashReportToServer(event.crashReport)
    }
  })
})
```

**Comment by kevinsawicki** [comment]
THis can now be done with current APIs that read the crashes directory and selectively upload reports after confirming with the user, closing this out.
