### ISSUE TITLE
app can't load .

### ISSUE THREAD

**Issue by bat-tech** [electron/electron#36742]
i am using the m1 macbook air and when i load this app called roam i get this error here is the log 

[localhost-1671929811214.log](https://github.com/electron/electron/files/10299805/localhost-1671929811214.log)
 
 idk what is the issue here but i want help bc the app doesn't load it just stays on the logo and then crash or just doesn't load
  here is the app :
  https://github.com/abrahampo1/roam/releases/tag/1.1.4
  
  i am not a dev i am an average user

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
