### ISSUE TITLE
[Bug]: net.request fails to fetch file when url points to domain with local cert

### ISSUE THREAD

**Issue by CezaryKulakowski** [electron/electron#36749]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

13.0.0-beta.13

### Expected Behavior

Following app:
```
const { app, BrowserWindow, net } = require('electron')

function startTest() {
  let win = new BrowserWindow();
  const request = net.request('<url_to_domain_with_local_cert>');
  request.on('response', (response) => {
    console.log(`STATUS: ${response.statusCode}`)
    console.log(`HEADERS: ${JSON.stringify(response.headers)}`)
    response.on('data', (chunk) => {
      console.log(`BODY: ${chunk}`)
    });
    response.on('end', () => {
      console.log('No more data in response.')
    });
  });
  request.on('error', (err) => {
    console.log(`request failed: ${err}`);
  });
  request.end();
}

app.on('ready', startTest)
```
should fetch the file.

### Actual Behavior

Request returns error `net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED`.

### Additional Information
It's happening because there is an empty implementation of method `SimpleURLLoaderWrapper::OnCertificateRequested`.

**Comment by codebytere** [comment]
@CezaryKulakowski this seems to have been fixed in https://github.com/electron/electron/compare/v23.0.0-nightly.20221117...v23.0.0-nightly.20221118 - most likely https://github.com/electron/electron/commit/87c183df6a6b758ace3097eeb176c2643398e29d. Could you run with `v23.0.0-nightly.20221118` to confirm? I created a local repro using https://justmarkup.com/articles/2018-05-31-https-valid-certificate-local-domain/ and successfully reproduced the issue which I then observed as fixed in `v23.0.0-nightly.20221118`

**Comment by CezaryKulakowski** [comment]
@codebytere I can still repro it on `v23.0.0-nightly.20221118`. I don't know how it could be fixed by chromium intake as problem is with missing implementation of certificate selection in Electron's implementation of simple url loader.

**Comment by CezaryKulakowski** [comment]
@codebytere could you check what happens if you have two certificates installed for the same domain? This event https://www.electronjs.org/docs/latest/api/app#event-select-client-certificate should be generated but request fails with error `net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED` instead.

**Comment by CezaryKulakowski** [comment]
@codebytere where have you added generated certificate? It reproduces to me when I add it to the branch `Certificates - Current User/Personal/Certificates` under Windows' mmc.
