### ISSUE TITLE
[Bug]: openDevTools() not working

### ISSUE THREAD

**Issue by Tetrax-10** [electron/electron#36748]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Expected Behavior

when running this command dev tools should automatically open.
```js
mainWindow.webContents.openDevTools()
```

### Actual Behavior

I noticed this is happening when installing some libraries such as [request](https://www.npmjs.com/package/request) and [download-git-repo](https://www.npmjs.com/package/download-git-repo).

when importing these libraries in main process dev tools doesn't open even manually pressing `ctrl+shift+I` didn't open but after 10 to 15 seconds if we press `ctrl+shift+I` devtools opens.

Am not using those modules just importing itself causes this behaviour
![image](https://user-images.githubusercontent.com/75513645/209720448-a6253598-6947-4e7c-a43a-798ca8df7962.png)

**Comment by codebytere** [comment]
it's likely those repos are interfering with the behavior of your application, and that this is not an issue or bug with Electron itself given that it cannot be reproduced without third-party dependencies. As such, i'm going to close this issue out unless it can be conclusively demonstrated that this is a bug in Electron itself.
