### ISSUE TITLE
[Bug]: After window blur, it will cause the previous window active

### ISSUE THREAD

**Issue by moshangqi** [electron/electron#36746]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0

### What operating system are you using?

macOS

### Operating System Version

No response

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

No response

### Expected Behavior

When I use the blur method, I hope not to cause the previous window active

### Actual Behavior

![屏幕录制2022-12-27 13 11 54](https://user-images.githubusercontent.com/50158871/209615178-abeb47ea-00ff-40d3-a95a-a155d80a96c4.gif)

### Testcase Gist URL

https://github.com/electron-modules/electron-windows

**Comment by xudafeng** [comment]
also encountered this situation, such as unexpected window focus

**Comment by MohitKumar020291** [comment]
Hello @moshangqi , did you used the command to install electron properly. It may be problem of installation. Try command    
 " npm install electron --save-dev " and if does not work then follow the link . https://www.tutorialspoint.com/electron/electron_installation.htm
These types of problem occurs when we do local setup for the first time.
Tell me if it works , I will be very glad .

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `21.x.y`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
