### ISSUE TITLE
[Bug]: Sharing powerpoint window stop update when entering presentation mode

### ISSUE THREAD

**Issue by fdlmdark** [electron/electron#36750]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS 13.1 (22C65)

### What arch are you using?

x64

### Expected Behavior

Auto switch to new full-screen window and continue shareing

### Actual Behavior

Shared stream stays at the orignal window, but not the presentation window.
This feature works fine in Chrome

### Additional Information

Chromium has a offical fix on this feature, but not work on electron.
https://webrtc-review.googlesource.com/c/src/+/156020

**Comment by fdlmdark** [comment]
Works fine with the following code in Chrome Browser
`
navigator.mediaDevices.getDisplayMedia()
`

**Comment by dtzxporter** [comment]
Have you tried the new getDisplayMedia() API?

It was released in v22.

**Comment by fdlmdark** [comment]
> Have you tried the new getDisplayMedia() API?
> 
> It was released in v22.

Will have a try :)

**Comment by fdlmdark** [comment]
The new getDisplayMedia() API works as expected. Thanks.

**Comment by Hin-D** [comment]
Macos fixed, but Windows did not.  Any idea?

**Comment by fdlmdark** [comment]
> Macos fixed, but Windows did not. Any idea?

That's because Window name didn't match the logic in Chrome source, use native code change the window's title will make it work. There is a pair of [] in window title which is unnecessary.
