### ISSUE TITLE
[Bug]: Choppy microphone audio on electron apps with chromium and different bluetooth device involved.

### ISSUE THREAD

**Issue by SimonNitzsche** [electron/electron#36757]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

unknown

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

Clean audio from microphone.

### Actual Behavior

So this accoured to me since like a few years. I've done a bit of testing over more than a year to try to narrow down the issue as much as possible.

When im using an electron based app like Discord, WhatsApp or MS Team, my microphone audio sounds bad.
Instead of a clean audio signal the audio will distort in 2 ways:
1. Being robot like
2. Cutting out volume in a wave where as 1 second full audio, 1 second no audio with a gradient in between. 

### Additional Information

I belive the issue to be related to electron since the same issue appears on various electron apps like Discord, MS Teams and WhatsApp.

My setup:
- Microphone: Rode NT1-A connected via XLR to a Scarlett SOLO via USB.
- Headphones: Sony WH-1000XM3 via Bluetooth

The headphones being connected to bluetooth besides only being the output device seems to play a huge role.

Investigation:
This issue seems to get worse when my headphones disconnect and reconnect.
This issue only seems to happen on electron with a chromium based browser. The issue couldn't be reproduced with Firefox and electron or Chrome and a microphone testing page (without electron).
If i test my audio directly in Windows via (Sounds > Input Device > Wiretap > Feedback) the audio is crystal clear aswell.

One thing that worked in the past was to switch out the usb ports which temporarily fixed it until i ran out of usb ports. Uninstalling the usb devices in Windows Device Manager didn't solve the issue.

I have tried various attempts to solve the issue on my own with little to results.
This involves:
Playing with the sample rate / buffer size of the mic
Playing with the audio format in Windows Sounds
Playing with exclusive mode in Windows Sounds
Disabling/Enabling my Headphones Hands-Free AG Audio in Windows Sounds
Setting the input/output device to the device and default in the application settings
Playing with the audio optimizations in the app

I've seen many people online talking about this issue unfortunately no one was able to find a fix for years.

**Comment by codebytere** [comment]
@SimonNitzsche does this also occur if you're using the same apps but in Chromium itself? e.g. the web version of MS Teams?

**Comment by SimonNitzsche** [comment]
Yes. It happens on the webversions aswell on all chromium-based browsers. It doesn't happen on Firefox.

**Comment by codebytere** [comment]
@SimonNitzsche then the best place to file this issue is https://crbug.com. We'll inherit their fix.

**Comment by SimonNitzsche** [comment]
Well, unfortunately this doesn't occours on Chromium based browsers. Only in use with electron.

**Comment by SimonNitzsche** [comment]
To give a bit of context, just a few user reports:

https://hypixel.net/threads/microphone-is-terrible-on-discord-only.4020939/
https://linustechtips.com/topic/1179255-my-mic-sounds-bad-in-discord/
https://twitter.com/KandUwU/status/1178711229642297349
https://www.quora.com/Why-is-my-microphone-so-bad-on-Discord-but-not-on-other-apps-My-mic-keeps-cutting-I-tried-deleting-Discord-and-reinstalling-it-and-other-things
https://www.reddit.com/r/discordapp/comments/7ojz6x/mic_sounds_bad_only_discord_though/
https://support.discord.com/hc/en-us/community/posts/1500001194361-Discord-should-not-have-control-over-how-my-Mic-sounds

**Comment by rodrigo-itao** [comment]
I'm having the same issue (Windows 11 x64). It doesn't happen in Chromium-based browsers, only in Electron.

**Comment by DaRacci** [comment]
Same issue, only occurs in electron based projects, chromium browsers are perfectly fine.
