### ISSUE TITLE
[Bug]: GNOME 43 Screen Keyboard

### ISSUE THREAD

**Issue by PhilipYip1988** [electron/electron#36759]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.10 and Fedora 37

### What arch are you using?

x64

### Expected Behavior

Install Ubuntu 22.10 or Fedora 37 on a system with a touchscreen.

Install Electron Applications such as Chromium, Chrome, VSCode, only Office Desktop Editors.

Press into a text input field. -> Screen Keyboard should display.

Swipe up from the bottom. -> Screen keyboard should display.

Input text on screen keyboard. -> Input text should display.

### Actual Behavior

Install Ubuntu 22.10 or Fedora 37 on a system with a touchscreen.

Install Electron Applications such as Chromium, Chrome, VSCode, only Office Desktop Editors.

Press into a text input field. -> Screen Keyboard does not display.

Swipe up from the bottom. -> Screen keyboard displays.

Input text on screen keyboard. -> Input text does not display.

The following video 04:08 shows FireFox working as expected and 05:18 the issue with Chromium/Chrome. Similar issues are seen with other Electron Applications:
https://www.youtube.com/watch?v=TY_XHlI1tH0

Bug submission to GNOME Shell:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6238#note_1627332
And Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=1403989

Response from GNOME Shell developer. Chrome/Chromium/Electron apps (basically everything from your list of non-working applications) are all because Chrome does not support the zwp_text_input_v3 protocol. It seems to still be stuck at zwp_text_input_v1: https://github.com/chromium/chromium/blob/main/components/exo/wayland/zwp_text_input_manager.cc. It should start working once they update their protocol support to the current protocol version.

**Comment by codebytere** [comment]
This is unfortunately something that needs to be fixed at the Chromium level. If you haven't yet, please open a [crbug](https://crbug.com) and then when they fix it we will inherit their fix.
