### ISSUE TITLE
[Bug]: Idea terminal cannot open Electron.exe by command(npm run electron:serve)

### ISSUE THREAD

**Issue by StepFH** [electron/electron#36754]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.2.3

### What operating system are you using?

macOS

### Operating System Version

macos Ventura 13.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

9.4.4

### Expected Behavior

I use command  in idea terminal 
e.g.`npm run electron:serve`

The normal situation  in my colleague's computer.
Colleague's code environment：
win10
node@16.17.1
npm@8.19.2
electron@9.4.4
<img width="868" alt="image" src="https://user-images.githubusercontent.com/42028539/209901142-f4900c41-9008-457c-85a5-33fbc454e325.png">

### Actual Behavior

My code environment：
Mac M1/macos Ventura13.0.1
node@14.21.2
npm@6.14.17
electron@12.2.3

The command stopped after Vue project compiled successful.
like this:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/42028539/209900659-86baa0a7-3220-44fa-9ad8-1568be4972f6.png">

This is my package.json
`{
  "name": "RetinaCare",
  "version": "2.3.11",
  "publishDate": "2022-03-07",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "axios": "^0.21.1",
    "chokidar": "^3.4.2",
    "core-js": "^3.6.5",
    "el-table-infinite-scroll": "^1.0.10",
    "electron-builder": "^23.6.0",
    "electron-updater": "^4.3.9",
    "element-ui": "^2.13.2",
    "html2canvas": "^1.0.0-rc.7",
    "iconv-lite": "^0.6.3",
    "js-md5": "^0.7.3",
    "jspdf-html2canvas": "^1.4.9",
    "print-js": "^1.2.0",
    "qiao-is-online": "0.0.6",
    "vue": "^2.6.11",
    "vue-html-to-paper": "^1.3.1",
    "vue-image-zoomer": "1.0.4",
    "vue-print-nb": "^1.5.0",
    "vue-qr": "^2.4.0",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0",
    "xml2js": "^0.4.23"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-standard": "^5.1.2",
    "babel-eslint": "^10.1.0",
    "electron": "^12.2.3",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^6.2.2",
    "lint-staged": "^9.5.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.2",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.4",
    "vue-template-compiler": "^2.6.11"
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,jsx,vue}": [
      "vue-cli-service lint",
      "git add"
    ]
  }
}`

This is my vue.config.js
`module.exports = {
  pages: {
    index: 'src/main.js',
    login: 'src/login/main.js'
  },
  chainWebpack: config => {
    config.resolve.symlinks(true)
  },
  devServer: {
    hot: true,
    hotOnly: true,
    watchContentBase: false
  },
  configureWebpack: {
    target: 'electron-renderer',
    externals: ['fsevents']
  },
  pluginOptions: {
    electronBuilder: {
      extraResources: {
        from: './public/dll',
        to: './dll'
      },
      builderOptions: {
        asar: false,
        mac: {
          target: {
            target: 'default',
            arch: [
              'x64',
              'arm64'
            ]
          }
        },
        win: {
          requestedExecutionLevel: 'requireAdministrator',
          icon: './public/ljj_256.ico', 
          artifactName: '${productName}-Setup-${version}.${ext}', 
          target: [
            {
              target: 'nsis', 
              arch: [
                'ia32'
              ]
            }
          ]
        },
        productName: 'testProject', 
        nsis: {
          include: './public/nsis/installer.nsh',
          perMachine: false, 
          runAfterFinish: true,
          oneClick: false, 
          allowElevation: true,
          allowToChangeInstallationDirectory: true, 
          installerIcon: './public/ljj_256.ico', 
          uninstallerIcon: './public/ljj_256.ico', 
          installerHeaderIcon: './public/ljj_256.ico', 
          createDesktopShortcut: true, 
          createStartMenuShortcut: true, 
          shortcutName: 'electronProject', 
          deleteAppDataOnUninstall: true
        },
        publish: [
          {
            provider: 'generic',
            url: 'https://www.electronProject_test.com/client'
          }
        ]
      }
    }
  }
}`

This is project catalogue:
<img width="389" alt="image" src="https://i.stack.imgur.com/yUhHl.png">

There are no other logs to find error. If anyone had resolve the same problem, please tell me how to fix it. thanks~

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
