### ISSUE TITLE
[Bug]: Cannot input FIDO2 PIN on macOS with Electron@22.0.0

### ISSUE THREAD

**Issue by zsxsoft** [electron/electron#36766]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.0

### What arch are you using?

x64

### Expected Behavior

Call to `navigator.credentials.create({ publicKey: ... })` opens an authentication prompt on macOS.

### Actual Behavior

Throws `The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client. Retry, create a new challenge or choose a different method.`

### Testcase Gist URL

https://gist.github.com/6568be0f3265959e6afa56d0ab02bea9

### Additional Information

I used WebAuthn API with YubiKey in macOS 13.0. According to the [document](https://support.yubico.com/hc/en-us/articles/4402836718866-Understanding-YubiKey-PINs#:~:text=If%20you%20prefer%20not%20to,allowing%20you%20to%20sign%20in.
), FIDO2 PIN is required for passwordless authentication.

After calling `navigator.credentials.create` or `navigator.credentials.get` and pressing the YubiKey, Chromium will show a modal dialog to let user input the PIN of the FIDO2 device. Instead, Electron will throw an exception.

I guess this issue is related to https://github.com/electron/electron/issues/27355, but it was closed.

**Comment by codebytere** [comment]
This is not supported at the moment. Feel free to follow https://github.com/electron/electron/pull/34769 for progress on potential future support.

**Comment by nathanosdev** [comment]
@codebytere could you consider reopening this please?
The linked PR hasn't been updated since June, 22. I don't think it seems reasonable to follow a stale PR.

**Comment by HKITYAN** [comment]
@codebytere any update on the progress. The linked PR hasn't been updated for a long time
