### ISSUE TITLE
[Bug]: Passthrough is not supported, GL is disabled, ANGLE is 

### ISSUE THREAD

**Issue by OnClickListener2048** [electron/electron#36762]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

windows11

### What arch are you using?

x64

### Last Known Working Electron version

22.0.0

### Expected Behavior

test

### Actual Behavior

wrong

### Additional Information

test

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by shulongfei** [comment]
兄弟，这个问题有解决吗？似乎v12.2.3之后的版本都存在该问题

**Comment by Mluocheng** [comment]
解决了吗 electrong 23 遇到了
