### ISSUE TITLE
[Bug]: ERR_INVALID_ARG_TYPE The "path" argument must be of type string (Yarn pnp)

### ISSUE THREAD

**Issue by asamofal** [electron/electron#36775]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

OS independent

### What arch are you using?

x64

### Expected Behavior

The application is starting.

### Actual Behavior

Crash on the start.

### Additional Information

Hi there! Help me figure out where I'm wrong.
I'm trying to init a new VueJS project, according to VueJS docs I use recommended `create-vue` tool with yarn, then install `electron` there. But there's an error in yarn pnp mechanism. I'm not sure if is it really related to `electron` or to `create-vue`, or to `yarn` itself. 

Could anyone help me, please?

[![asciicast](https://asciinema.org/a/ylqq3WeEzdxN7iNxDtr9lkrzG.svg)](https://asciinema.org/a/ylqq3WeEzdxN7iNxDtr9lkrzG)

![image](https://user-images.githubusercontent.com/2729547/210242087-4b2a9f7f-54af-42f1-9f30-9e2df611bf5b.png)

p.s. if create a project with `yarn init` - the test app launches fine =\ I understand the error but don't understand what module (package, etc) really triggers it.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by kyleshrader** [comment]
I followed that Discord link to find that it is a different community. The correct Discord URL is [https://discord.gg/electronjs](https://discord.gg/electronjs)
