### ISSUE TITLE
[Feature Request]: Migrate to using native ESM modules instead of CommonJS

### ISSUE THREAD

**Issue by martinszeltins** [electron/electron#36788]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Right now when you create a new Electron app using Forge `npm init electron-app@latest my-app` it still uses the old CommonJS require statements. Node has had native ESM module support for a long time and it just makes sense to switch to it so it is more modern and the Javascript community has moved to it.

Current app genereted with Forge:
````
const { app, BrowserWindow } = require('electron');
const path = require('path');
...
````

### Proposed Solution

Use modern native ESM modules instead:

````
import { app, BrowserWindow } from 'electron'
import path from 'path'
````

### Alternatives Considered

There are no alternatives.

**Comment by codebytere** [comment]
If you would like to propose this change, you are welcome to do so on the [forge repo](https://github.com/electron/forge) - this is not the place for that.

**Comment by Prinzhorn** [comment]
> Node has had native ESM module support for a long time and it just makes sense to switch to it so it is more modern and the Javascript community has moved to it.

https://github.com/electron/electron/issues/21457
