### ISSUE TITLE
[Bug]: Printing bing.com site fails since Electron 22

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#36796]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

21.0.0

### Expected Behavior

I expect to be able to print the bing site to a PDF printer

### Actual Behavior

print callback resolves when selecting the printer with the "Print job failed" failure reason, presumably from [here](https://github.com/electron/electron/blob/8acf6039e78725918af5797fad6fc4f7cf1e177c/patches/chromium/printing.patch#L145)

### Testcase Gist URL

https://gist.github.com/2eb2b9fdfdd0479f67b2451c4da7083a

### Additional Information

run the gist, select the Microsoft PDF printer, observe the error dialog

The print callback runs before the OpenFile dialog displays

**Comment by pushkin-** [comment]
bump

**Comment by codebytere** [comment]
@pushkin- what versions is this still happening to you on? I can't reproduce it following your provided steps on v25, v26 or v27 - it successfully saves the document to disk.

**Comment by pushkin-** [comment]
@codebytere huh, sometimes it takes a second try to repro, but indeed, it doesn't repro in the later versions. It *seems* like it may have been fixed in [v22.3.15](https://releases.electronjs.org/release/v22.3.15) though not sure what in there would have fixed it.
