### ISSUE TITLE
[Bug]: The web serial port selection panel cannot be opened in electron

### ISSUE THREAD

**Issue by 651778286** [electron/electron#36809]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

when i called
`await navigator.serial.requestPort()`
the serial port selection panel should show, just like it works in chrome browser

![image](https://user-images.githubusercontent.com/7576363/210826608-cb2c045d-ca7a-4f14-8b79-43230d62e5b6.png)

### Actual Behavior

the serial port selection panel do not show

**Comment by codebytere** [comment]
@651778286 this is not correct - Electron does and will not show Chrome UI. it's up to the developer to create their own dialog.
