### ISSUE TITLE
Pixelated icons on external monitor Electron 15+

### ISSUE THREAD

**Issue by hosnar** [electron/electron#36822]
Hi,

i've encountered a weird issue that i'm not really sure where it comes from. If i update my app on Electron that is higher version that 14, SVG icons i use in the app become pixelated/ragged if i use my app on an external 2K monitor (primary monitor is Macbook PRO retina). If i move the app to retina display, icons look ok. If i revert back to Electron 14, icons are also ok on external monitor. I've also noticed that if i disable hardware acceleration, then icons are also ok on external monitor. Does anyone have an idea what could be a solution for this? I'm guessing this is probably more chromium issue than electron, but i'm asking here just in case. Any help would be greatly appreciated, i've been searching for a solution for a few days now and can't find any. And i also don't want to stay at version 14 (and i need hardware acceleration enabled). Thank you!

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
