### ISSUE TITLE
Not allowed to load local resource in sandboxed iframe

### ISSUE THREAD

**Issue by codingMASTER398** [electron/electron#36835]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Zorin OS 16.2 (Ubuntu 20.04)

### What arch are you using?

x64

### Expected Behavior

I expect that a sandboxed iFrame shouldn't throw a "Not allowed to load local resource" error when fetching/loading a file that the main window can.

### Actual Behavior

It works fine when loading a local resource in a BrowserWindow (e.g. `file:///home/user/app/index.html`). However, if this is replicated in a sandboxed iFrame within the BrowserWindow, it throws the error "Not allowed to load local resource". This also applies to `fetch`.

Outside of the iFrame, it works perfectly fine, same location and all. I have a custom handler built to ensure the website cannot access files it's not supposed to, however.

**Comment by Abhijit20112003** [comment]
generally not possible to load local resources in a sandboxed iframe. This is because the sandbox attribute of the iframe element restricts the iframe from doing certain things that could potentially be harmful to the user, such as loading local files.

**Comment by Abhijit20112003** [comment]
work around this restriction is to use a server to serve the local resource, rather than trying to load it directly. This way, the resource can be accessed via a URL, rather than being treated as a local file.

**Comment by codingMASTER398** [comment]
That'll work, thanks!
