### ISSUE TITLE
[Bug]: Why is bluetooth started on Linux?

### ISSUE THREAD

**Issue by joshuataylor** [electron/electron#36831]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0-alpha.3/main

### What operating system are you using?

Other Linux

### Operating System Version

Linux kit 6.1.4-1

### What arch are you using?

x64

### Expected Behavior

Bluetooth should not be started when an application is launched.

### Actual Behavior

Bluetooth is started on application start, but this should not be the case.

Bluetooth might be disabled by default, and launching an app that uses Electron (Visual Studio Code, etc) will start the service:

https://github.com/electron/electron/blob/main/shell/browser/electron_browser_main_parts.cc#L547

I understand that Bluetooth is a required feature for some applications, but is there not a compromise for this?

Options:
1. Launch flag to enable/disable Bluetooth (maybe short term disable, as a temporary workaround?)
2. Only run that when a function that requires Bluetooth is actually called for the first time?

### Additional Information

Bluetooth is started on application start, but this should not be the case.

Bluetooth might be disabled by default, and launching an app that uses Electron (Visual Studio Code, etc) will start the service:

https://github.com/electron/electron/blob/main/shell/browser/electron_browser_main_parts.cc#L547

**Comment by dsanders11** [comment]
Do you see the same behavior when running Chromium? It looks like Electron is matching Chromium's behavior there, so if you see the same behavior with Chromium, I'd recommend opening an upstream bug. They'd be in a better position to make a call on if option 2 is feasible.

**Comment by codebytere** [comment]
Closing in agreement with the above - Chromium does in fact do this. You should open an upstream bug on https://crbug.com
