### ISSUE TITLE
[Feature Request]: Add powerMonitor 'battery-level-changed` event

### ISSUE THREAD

**Issue by m-naeem66622** [electron/electron#36830]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.

### Problem Description

[powerMonitor](https://www.electronjs.org/docs/api/power-monitor) triggers events when the computer goes on AC or on battery. But there's no way to check battery level changed each time.

Tried to get approach like:

> function checkBatteryLevel() {
>   const currentLevel = powerMonitor.battery.level;
>   if (previousLevel !== null && currentLevel !== previousLevel) {
>     console.log('Battery level changed.');
>     // Run code here
>   }
>   previousLevel = currentLevel;
> }

but failed as this will only run when `on-ac` or `on-battery` events fired.

### Proposed Solution

There will be an event that fired everytime when battery level will changed.

### Alternatives Considered

-

**Comment by codebytere** [comment]
This module wraps PowerMonitor [upstream](https://source.chromium.org/chromium/chromium/src/+/main:base/power_monitor/power_observer.h) - this type of observation is something you should handle with a native node module or similar and not one that we're likely to add to core.

**Comment by miniak** [comment]
There is https://source.chromium.org/chromium/chromium/src/+/main:base/power_monitor/battery_level_provider.h

**Comment by codebytere** [comment]
@miniak yes, but it doesn't have an observer, and so we would need to then implement polling ourselves which i'd be fairly opposed to doing
