### ISSUE TITLE
[Bug]: Received signal 11 SEGV_ACCERR 0000000005b5 - Renderer crash

### ISSUE THREAD

**Issue by jupnit** [electron/electron#36832]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6.2

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

21.3.3

### Expected Behavior

Renderer process should not crash.

### Actual Behavior

Renderer process is crashing on upgrade to electron v22. This happens in both Windows and MacOS. App is working fine with last stable electron version 21.3.3.
Unable to debug the exact root cause but we are using `[single-spa-angular](https://github.com/single-spa/single-spa-angular)` module in our project and this crash happens just after loading `single-spa-angular-internals.umd.js` script asynchronously.

Using `export ELECTRON_ENABLE_STACK_DUMPING=true`, I get following log - 

`Received signal 11 SEGV_ACCERR 0000000005b5`
 `[0x00010d44b530]`
 `[0x00010d3ea190]`
 `[0x00010d44b4b0]`
 `[0x0001b23934a4]`
 `[0x000110a89a2c]`
 ....`

The only reason we want to upgrade to electron v22 is because it comes with bumped version of `electron/get` to 2.0.0. This version of `electron/get` has a fix for a security vulnerability as described in [this issue](https://github.com/electron/get/issues/224). If this can be backported to electron version 21.3.3, we can still continue to use that version.

### Additional Information

Unfortunately, I cannot upload my project or any part of it. I'm hoping people with more experience can point out how to debug this issue. Ideally to identify what's causing the problem.

**Comment by BobSos** [comment]
> Hello @jupnit. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by jupnit** [comment]
Hello,

After further analysis, I found out that this was happening because I had disabled sandboxing for preload - 
```
webPreferences: {
  ....
  sandbox: false
}
```
When I enable sandbox, I have to remove/replace all Node.Js module usage in preload but otherwise my app works fine. 
Strange thing is that the app also works fine with `sandbox: false` when using electron version 21.3.3.

**Comment by ckerr** [comment]
I'm glad you found a workaround!

Still, Electron shouldn't _crash_ with or without sandboxing. There's nothing actionable in the crash report in the initial description, but @jupnit if you're still interested in this issue, please try isolating the crash further, e.g. with a standalone testcase that maintainers can use to try and reproduce the problem

**Comment by ci7lus** [comment]
I'm also facing a similar issue, I have created a reproduction. It requires macOS to run a setup script. https://github.com/vivid-lapin/electron-v22-native-module-repro
