### ISSUE TITLE
[Bug]: The dev tools cannot display the style of the selected element

### ISSUE THREAD

**Issue by bayun2** [electron/electron#36844]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.0.1

### What arch are you using?

x64

### Last Known Working Electron version

21.0.1

### Expected Behavior

The dev tools can display the style of the selected element

### Actual Behavior

The dev tools cannot display the style of the selected element
<img width="1595" alt="image" src="https://user-images.githubusercontent.com/3183696/211487193-ed8e5133-b0b5-46cc-ba32-73a63e3e5b1a.png">

The terminal displays the following error
<img width="599" alt="image" src="https://user-images.githubusercontent.com/3183696/211487515-75f5d331-8767-4592-9921-24727ae3867b.png">

It seems that when devtools detects the style conflict prompt again, there is an internal js variable that is not defined and throws an error.

devtools has modified this variable, I don’t know whether it can be fixed by upgrading the version of devtools built in electron

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/3183696/211488894-4cbe87f2-4501-4478-a1ee-fa423c824078.png">

**Comment by bayun2** [comment]
I have found the problem
![image](https://user-images.githubusercontent.com/3183696/211562415-de5b40f0-5308-44ae-ada7-66debd0fd8c1.png)

devTools only updated the language pack of us，so when I use the Chinese mode，cause the above bug

**Comment by codebytere** [comment]
@bayun2 you should likely open this as a bug on Chromium - crbug.com
