### ISSUE TITLE
crash on Windows NT 6.3.9600 16384, Crash reason: oom

### ISSUE THREAD

**Issue by ChaoLei-Ling** [electron/electron#36841]
Electron Version
11.2.0

What operating system are you using?
Windows Server 2012

Operating System Version
Windows NT 6.3.9600 16384

What arch are you using?
x86

Last Known Working Electron version
No response

Expected Behavior
I would expect the render process to not crash

Actual Behavior
The renderer process get en render-process-gone event after some times, the event details is oom, i have got the minidump file and try to use electron-crash-server to open it:
Operating system: Windows NT
                  6.3.9600 16384
CPU: amd64
     family 6 model 85 stepping 7
     44 CPUs

Crash reason:  0xe0000008 / 0x00000001
Crash address: 0x7ffc339a8384

Thread 0 (crashed)
 0  KERNELBASE.dll + 0x8384
    rbx = 0x000000a65e0d77c0   r12 = 0x00000000001ea9d8
    r13 = 0x000000000071f6fc   r14 = 0x0000000000040001
    r15 = 0x00007ff72572b6e4   rip = 0x00007ffc339a8384
    rsp = 0x000000a65e0d7250   rbp = 0x000000a65e0d75b0
    Found by: given as instruction pointer in context
 1  KERNELBASE.dll + 0x8384
    rip = 0x00007ffc339a8384   rsp = 0x000000a65e0d7288
    rbp = 0x000000a65e0d75b0
    Found by: stack scanning
 2  dntester.exe + 0x11f5d50
    rip = 0x00007ff720365d50   rsp = 0x000000a65e0d7308
    rbp = 0x000000a65e0d75b0
    Found by: stack scanning
 3  dntester.exe + 0x26c3ec2
    rip = 0x00007ff721833ec2   rsp = 0x000000a65e0d7330
    rbp = 0x000000a65e0d75b0
    Found by: stack scanning
 4  dntester.exe + 0xf2be39
    rip = 0x00007ff72009be39   rsp = 0x000000a65e0d7340
    rbp = 0x000000a65e0d75b0
    Found by: stack scanning
 5  dntester.exe + 0x18ca8a0
    rip = 0x00007ff720a3a8a0   rsp = 0x000000a65e0d7360
    rbp = 0x000000a65e0d75b0
    Found by: stack scanning
 6  dntester.exe + 0x18ca5e9
    rip = 0x00007ff720a3a5e9   rsp = 0x000000a65e0d7390
    rbp = 0x000000a65e0d75b0
    Found by: stack scanning
 7  dntester.exe + 0x658172c
    rip = 0x00007ff7256f172c   rsp = 0x000000a65e0d7398
    rbp = 0x000000a65e0d75b0
    Found by: stack scanning
 8  dntester.exe + 0x2ccfd42
    rip = 0x00007ff721e3fd42   rsp = 0x000000a65e0d73a0
    rbp = 0x000000a65e0d75b0
    Found by: stack scanning
 9  dntester.exe + 0xd812ff
    rip = 0x00007ff71fef12ff   rsp = 0x000000a65e0d73c0
    rbp = 0x000000a65e0d75b0
    Found by: stack scanning
10  dntester.exe + 0xd812d1
    rip = 0x00007ff71fef12d1   rsp = 0x000000a65e0d73f0
    rbp = 0x000000a65e0d75b0
    Found by: stack scanning

**Comment by ChaoLei-Ling** [comment]
The general phenomenon is that the program will become stuck, then inoperable, then white screen, and finally get the above events. This process is relatively slow, usually for more than 10 minutes. And if you run multiple programs on the same machine, when one of them gets stuck, the other will also become stuck, but when the stuck program crashes, the other programs will automatically recover

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by miniak** [comment]
Electron 11 is not supported

**Comment by ChaoLei-Ling** [comment]
Can you give a hint about what causes this kind of problem？

**Comment by miniak** [comment]
Please file a new issue using the template if you can reproduce this on a current Electron version (20, 21 or 22)
