### ISSUE TITLE
[Bug]: Renderer crash when nodeIntegration is true

### ISSUE THREAD

**Issue by markleutloff** [electron/electron#36856]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0, 23.0.0-alpha.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21H2

### What arch are you using?

x64

### Last Known Working Electron version

21.3.3

### Expected Behavior

Renderer process should not crash.

### Actual Behavior

The renderer process does crash.

### Testcase Gist URL

https://gist.github.com/5b4b04de7eba3b3d52e190ff05455702

### Additional Information

I only encountered the issue with the https://orf.at URL and then only when a certain window width has been exceeded.
The crash occurs after the cookie consent banner is visible.

Reducing the width of the BrowserWindow on creation/initialization ensures that the renderer process will not crash.
Increasing the width of the window after the site has been loaded will also not crash the process.

**This will crash:**
```
const mainWindow = new BrowserWindow({
    width: 1100,
    height: 500,

    webPreferences: {
      nodeIntegration: true,
    }
  })

  mainWindow.loadURL('https://orf.at')
```

**This will not crash (width has been reduced):**
```
const mainWindow = new BrowserWindow({
    width: 1000,
    height: 500,

    webPreferences: {
      nodeIntegration: true,
    }
  })

  mainWindow.loadURL('https://orf.at')
```

**Comment by codebytere** [comment]
Already fixed in https://github.com/electron/electron/pull/36567
