### ISSUE TITLE
[Bug]: inAppPurchase.getProducts method resolve empty array.

### ISSUE THREAD

**Issue by luokunman** [electron/electron#36872]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS M1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I want to get the appstoreConnect in-app purchase list.

### Actual Behavior

I got an empty array

### Additional Information

I think Electron.app has not enabled in-app purchase capability.
The main process code is as follows
```
const getProducts = () => {
  if (!inAppPurchase.canMakePayments()) {
    console.log('The user is not allowed to make in-app purchase.')
  }

  inAppPurchase.getProducts(PRODUCT_IDS).then(products => {
    console.log(products) // 
    if (!Array.isArray(products) || products.length <= 0) {
      console.log('Unable to retrieve the product informations.')
      return
    }
    // Display the name and price of each product.
    products.forEach(product => {
      console.log(`The price of ${product.localizedTitle} is ${product.formattedPrice}.`)
    })
    const selectedProduct = products[0]
    const selectedQuantity = 1
    // Purchase the selected product.
    inAppPurchase.purchaseProduct(selectedProduct.productIdentifier, selectedQuantity).then(isProductValid => {
      if (!isProductValid) {
        console.log('The product is not valid.')
        return
      }
      console.log('The payment has been added to the payment queue.')
    })
  })
}```
I have consulted the documentation and finished configuring iTunes Connect.(https://www.electronjs.org/docs/latest/tutorial/in-app-purchases)

**Comment by luokunman** [comment]
I am very anxious about this problem, if anyone knows how to solve the problem, please propose a solution

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by luokunman** [comment]
I really need an answer. The Electron community does not have a solution.
<img width="680" alt="image" src="https://user-images.githubusercontent.com/41885648/215989349-1be13b1a-7dec-45a3-b889-ad4048c20ef5.png">

**Comment by 15814596022** [comment]
same in dev, but can work in testflight

**Comment by lpasquini** [comment]
Do you have any updates on this matter? I am facing the same issue. Everything works fine in development, but the app downloaded from the store is not receiving the products. I am planning to upload a version with the embedded JSON of products, but I am unsure if the other methods will work.

**Comment by 15814596022** [comment]
> Do you have any updates on this matter? I am facing the same issue. Everything works fine in development, but the app downloaded from the store is not receiving the products. I am planning to upload a version with the embedded JSON of products, but I am unsure if the other methods will work.

The products on [https://appstoreconnect.apple.com/apps/](https://appstoreconnect.apple.com/apps/) should be granted permission. Otherwise we can only get products in development mode

**Comment by lpasquini** [comment]
> > Do you have any updates on this matter? I am facing the same issue. Everything works fine in development, but the app downloaded from the store is not receiving the products. I am planning to upload a version with the embedded JSON of products, but I am unsure if the other methods will work.
> 
> The products on https://appstoreconnect.apple.com/apps/ should be granted permission. Otherwise we can only get products in development mode

Thank you for your response. I am unable to locate where that would be. As far as I understand, the plans have been published and approved.

**Comment by lpasquini** [comment]
> > > Do you have any updates on this matter? I am facing the same issue. Everything works fine in development, but the app downloaded from the store is not receiving the products. I am planning to upload a version with the embedded JSON of products, but I am unsure if the other methods will work.
> > 
> > 
> > The products on https://appstoreconnect.apple.com/apps/ should be granted permission. Otherwise we can only get products in development mode
> 
> Thank you for your response. I am unable to locate where that would be. As far as I understand, the plans have been published and approved.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/847745/233761416-c4d0391d-c5d7-4c88-868b-34e84fd83885.png">
<img width="387" alt="image" src="https://user-images.githubusercontent.com/847745/233761489-10f1aa3c-4a15-403f-8e80-d71d83af5c46.png">

**Comment by 15814596022** [comment]
> Thank you for your response. I am unable to locate where that would be. As far as I understand, the plans have been published and approved.

below this image, has an App Store localized version, also should be approved

**Comment by lpasquini** [comment]
Yes, that is also approved.

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/847745/233814679-6a2f4900-315e-43a1-b44c-18cbabe43e9a.png">

**Comment by 15814596022** [comment]
> Yes, that is also approved.
> 
> <img alt="image" width="1085" src="https://user-images.githubusercontent.com/847745/233814679-6a2f4900-315e-43a1-b44c-18cbabe43e9a.png">

Sorry，I have no idea >..<

**Comment by lpasquini** [comment]
> > Yes, that is also approved.
> > <img alt="image" width="1085" src="https://user-images.githubusercontent.com/847745/233814679-6a2f4900-315e-43a1-b44c-18cbabe43e9a.png">
> 
> Sorry，I have no idea >..<

Thank you very much.

**Comment by kharenzze** [comment]
I'm facing the same issue. I'm going to downgrade electron to an older version to check if it works. 
Also, I already set the development environment for Electron and I'll try to debug this, but my Objective-C is a little bit rusted

**Comment by kharenzze** [comment]
It's working now in dev mode and release mode. I think the key is that I upgraded xcode version. (14.3.0)

**Comment by luokunman** [comment]
> 它现在在开发模式和发布模式下工作。我认为关键是我升级了xcode版本。(14.3.0)
Upgrade electron version 21 is valid

**Comment by luokunman** [comment]
Build the electron project as mas-dev, and add entitlements to com.apple.security.app-sandbox, and get empty data.
