### ISSUE TITLE
Request - capturePage on <webview>

### ISSUE THREAD

**Issue by thiakil** [electron/electron#3687]
I'm using a webview tag to isolate a website from node/electron and have custom window decorations, however I need to capture the contents of the page in order to compare it to another.

Currently this would only be possible by getting the embedded page's height and extending the window.

**Comment by appelgriebsch** [comment]
+1

**Comment by youyudehexie** [comment]
+1

**Comment by snoblenet** [comment]
+1

**Comment by cyvirus** [comment]
+1

**Comment by IsaiahJTurner** [comment]
+1
