### ISSUE TITLE
[Bug]: Cors error net::ERR_CONNECTION_REFUSED, only on electron, not browser

### ISSUE THREAD

**Issue by Juan321654** [electron/electron#36890]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

21H2

### What arch are you using?

x64

### Expected Behavior

data from internal server should be showing

### Actual Behavior

I am using react, and I am making a `sqlite` server to save data.

when I launch the electron app (dev mode), it fetches data once, then the second time(useEffect) it gets the cors error.

I have added all the suggestions from stackoverflow and other sites to include `webSecutiry: false` in the `webPreferencces` and `OutOfBlinkCors` and a few more but I still have not been able to fix it.

if I use the build command, then the first time I launch the app, I get the cors error, if I reload, it gets data, if I keep refreshing it keeps doing that same loop, every time I reload, it gets cors then on the next reload it gets data.

I have enabled cors on the server folder and if I go to my actual browser, it works fine, I do not get a cors error, it only happens on the electron app. 

here is a dummy repo where this happens, in the `server` branch **not** the `master`
`https://github.com/Juan321654/electron_react_with_build_installer`
make sure to install node modules in the `server` folder too. 
`npm run start` to start the electron app (you can check the browser on localhost:3000 to see that it works fine without cors)
`npm run build` to build the software. 
the electron file is in `public` > `electron.js`
the sqlite db file is included in the server folder, if for some reason it does not work, make sure to `cd` into the `server` folder and run `sequelize db:migrate`

in my actual project, I will have to include 3 different servers that each has an sqlite db in one project. and something that I noticed is that the cors error goes away if I separate the server and run it by itself and not include it in this same project, so in my case, I would have to create 4 different electron apps to make my app work, but that would be really annoying for the user, to have to run 3 different apps one for each server and then another for the actual software.

**Comment by Juan321654** [comment]
@codebytere what do you mean... I provided a repo. it just doesn't happen with one-line command...

**Comment by Juan321654** [comment]
I have found a workaround, which is to create a second window as a hidden `tray` to run the server and had to move the `node modules` to the main root folder. but now my issue is that when I do the `build` command, I can launch the app and it works fine from the regular executable in the `dist` > `win-unpacked` folder.
But when I install the software, it does not work.

**Comment by codebytere** [comment]
Closing as completed then. For follow-up questions, check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by defghy** [comment]
First confirm right click request and `copy as fetch`, fetch is ok in browser console. then

In my case, remote debug trigger cors `ERR_CONNECTION_REFUSED`
```
  app.commandLine.appendSwitch('host-rules', 'MAP * 127.0.0.1');
```
delete this line, it's ok
