### ISSUE TITLE
[Bug]: After updateding the chrome driver version to 91 for electron app, getting white screen on launch for electron app automation

### ISSUE THREAD

**Issue by shankaram** [electron/electron#36903]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.9

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

My electron app migrated to electron version -"electron": "13.6.9". Hence i needed to update my chrome driver version from 85 to 91 .
But on launching the application page should load.

### Actual Behavior

My electron app migrated to electron version -"electron": "13.6.9". Hence i needed to update my chrome driver version from 85 to 91 .
But on launching the application its showing white screen.

### Additional Information

Code:-
System.setProperty(DataManager.getChromeDriver(), DataManager.getElectronDriverPath());
ChromeOptions opt = new ChromeOptions();
opt.setBinary(DataManager.getElectronAppPath());
ChromeDriverService chromeservices = new ChromeDriverService.Builder().build();
electronDriver=new ChromeDriver(chromeservices, opt);

Note:- Before it was working fine.

Software version:
Java v1.8.0_311
Selenium- 3.141.59
Chrome version- 91

**Comment by miniak** [comment]
Electron 13 is not supported

**Comment by shankaram** [comment]
> Electron 13 is not supported, please create a new issue in cases you can still reproduce it with a supported version

Just want to make it clear , is Electron 13 version is not supported for selenium automation?
