### ISSUE TITLE
[Bug]: webContents.print is push print document repeat once to print driver in some user environment

### ISSUE THREAD

**Issue by Wayne529** [electron/electron#36911]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.1 

### What operating system are you using?

Windows

### Operating System Version

Win10  1903

### What arch are you using?

x64

### Last Known Working Electron version

20.0.1 

### Expected Behavior

print no repeat

### Actual Behavior

prrint repeat:
eg: I had invoke the webcontens print API 12 times, one document one time, it should be 12 docoments,but the print driver recieve   23 documents, the documents is repeat. 

### Additional Information

1.It is not appear inevitably. In some user environment is OK,but in other some user environment is repeat
2.the print pseudo-code is blew:
I divide the all print data into some queue.Had print prev queue,then print the next queue,util all queus is done.
`
ipcMain.on('printHtml', () => {
  // batchPrintWindow is print render window
  batchPrintWindow.webContents.print(printOption, (success: boolean, failureReason: string) => {
    if (success) {
      // if return function result is success,to do next print render
      batchPrintWindow.webContents.send('renderHtml', {
        printList
      });
    }else{
     // log the error to local log file
      log.error('failureReason is', failureReason);
    }
  }）
}）
`
3.Actually,the print API is invoke the correct times,but the documents print repeat.Maybe the print API to print driver get something wrong.
4.It probably relate to user environment, but user environment is very conplicated, I cannot find the reason of the problem.
So I create the issue ask for help.thks!

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by Wayne529** [comment]
> 

I try to update the Electron version from V20.0.1 to V22.1.0, the problem is resolved.Why?Are U fix the bug?Hope your reply the reason.tks! The print API had modify?

**Comment by Wayne529** [comment]
> 

And we find the print repeat problem is related to computer's default printer in settings.If set default printer as A printer,and select A printer to silent webcontent print,invoke the print API in sencond time, it do repeat.If set default printer as A printer,but select B printer  to silent webcontent print,it do print both in A and B printer.

But I update Electron version to 22.1.0,it is OK,the problem is gone!

**Comment by cjx-2435** [comment]
I got the same problem with electron verison 20.1.1

**Comment by Wayne529** [comment]
> 

U can update the electron version to 22.1.0.Maybe the problem is gone
