### ISSUE TITLE
[Bug]: CSS Cursor style doesn't work on Mac OS Ventura (both framed and frameless)

### ISSUE THREAD

**Issue by menushka** [electron/electron#36921]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.2

### What operating system are you using?

macOS

### Operating System Version

Mac OS Ventura 13.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

Tried all the way down to Electron 12 with no luck

### Expected Behavior

Placed `cursor: pointer` on the `body` of the `index.html` template file and expected the entire window to show the pointer icon when hovering over it.

### Actual Behavior

Instead only the default pointer shows.

### Additional Information

Default Electron Fiddle shows the same behaviour, hovering the text doesn't show text cursor only shows default.

**Comment by codebytere** [comment]
@menushka i can't reproduce this as-is. 

If i load for example load https://github.com in Fiddle, open devtools, and place `cursor: pointer` on the body it works just fine.

**Comment by menushka** [comment]
Odd I tried reproducing on my Intel machine and wasn't able to, restarting my M1 seemed to have solved the issue, I'll go ahead and close, maybe it was some weird MacOS bug 🤷‍♂️.  Thanks for looking into it!

**Comment by AndrewWebDev** [comment]
Hello, had the same issue with Sonoma 14.4, macbook m1 pro

Restart solve the issue, weird bug

Safari, Chrome had cursor default for all elements on the page
