### ISSUE TITLE
[Feature Request]: Should be able to access files in the clipboard module

### ISSUE THREAD

**Issue by rudraasakariya** [electron/electron#36930]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am working on a project of mine that requires me to access the files copied on the clipboard and then do certain computations but the module has no provision of any service related to files. I want to work with all possible file types such as .docx, .pptx, .xlsx, or even .js, .cpp, or any other file extensions.

Can you please help me with what I should do in the meanwhile I have deadlines to meet for the project I am working on and any help would be great!!

### Proposed Solution

Develop an interface similar to  NativeImage for NativeFiles which may have attributes of files. This could make the reading and writing files much easier

### Alternatives Considered

I cannot think of a possible alternative at the time. I may update the thread if I come up with something

**Comment by codebytere** [comment]
it's not clear exactly what you're asking for here - could you please provide an example code snippet or explain further?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
