### ISSUE TITLE
[Bug]: Enabling titleBarOverlay causes enableBlinkFeatures warning

### ISSUE THREAD

**Issue by k9** [electron/electron#36948]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.2

### What operating system are you using?

macOS

### Operating System Version

Monterey 12.5.1

### What arch are you using?

x64

### Expected Behavior

I didn't expect enabling `titleBarOverlay` to cause a warning.

### Actual Behavior

When I add these two lines to my window config:
```
titleBarOverlay: true,
titleBarStyle: 'hidden'
```

I get the warning below in dev tools. I've seen this in my own app and also in the Gist attached. In both cases, I haven't enabled any blink features.

```
Electron Security Warning (enableBlinkFeatures) This renderer process has additional "enableBlinkFeatures"
  enabled. This exposes users of this app to some security risk. If you do not
  need this feature, you should disable it.
```

### Testcase Gist URL

https://gist.github.com/e3fefa1598f557e7de9dc0349aa3a020

**Comment by codebytere** [comment]
This is expected behavior - these go away in v23 and up.

**Comment by DarkSynx** [comment]
good v22.3.2
