### ISSUE TITLE
[Bug]: ReactDevTools Loads but won't work

### ISSUE THREAD

**Issue by Digamasyx** [electron/electron#36941]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 22H2

### What arch are you using?

x64

### Expected Behavior

Expected the extension load the components tree

### Actual Behavior

The reactDevtools extension Ver: 4.27.1_0, loads in Electron fine using
```js 
// The USERPROFILE variable, it's never been changed so it keeps the default value "C:/USERS/{user}"
let extPath = os.join(os.homedir(), "AppData/Local/Google/Chrome/User Data/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.27.1_0");
session.defaultSession.loadExtension("path-to-extension");
```
This code runs on the index.js/index.ts file on the createWindow function, For me the createWindows function it's like this
```ts
const createWindow = (): void => { 

   const mainWindow = new BrowserWindow({
       show: false,
       webPreferences: {
         preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
       }
  })

  let extPath = path.join(os.homedir(), "AppData/Local/Google/Chrome/User Data/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.27.1_0")
  session.defaultSession.loadExtension(extPath)



  // Maximize and Show
  mainWindow.maximize();
  mainWindow.show();

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

}
```

And this function runs on
```js 
app.on("ready", createWindow)
```
And on console i recieve
```
(node:1284) ExtensionLoadWarning: Warnings loading extension at C:\Users\{user}\AppData\Local\Google\Chrome\User Data\Default\Extensions\fmkadmapgofadopljbjfkapdkoienihi\4.27.1_0:
  Manifest contains a differential_fingerprint key that will be overridden on extension update.
  Permission 'scripting' is unknown or URL pattern is malformed.

(Use `electron --trace-warnings ...` to show where the warning was created)
[1284:0118/115808.156:ERROR:extensions_browser_client.cc(62)] Extension Error:
  OTR:     false
  Level:   1
  Source:  manifest.json
  Message: Service worker registration failed. Status code: 15
  ID:      fmkadmapgofadopljbjfkapdkoienihi
  Type:    ManifestError
[1284:0118/115808.156:ERROR:extensions_browser_client.cc(62)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
  Message: Uncaught TypeError: Cannot read properties of undefined (reading 'registerContentScripts')
  ID:      fmkadmapgofadopljbjfkapdkoienihi
  Type:    RuntimeError
  Context: chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
  Stack Trace:
    {
      Line:     107
      Column:   1
      URL:      chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
      Function: (anonymous function)
    }
```
The extension loads but can't get the components
![image](https://user-images.githubusercontent.com/88753741/213210452-0158035a-92bf-4ce9-bbad-a844898f030f.png)

### Additional Information

I use the electron-forge webpack-typescript template

**Comment by zhouzi** [comment]
This issue was originally reported in #36545 and then tracked in React's repository through https://github.com/facebook/react/issues/25843

See https://github.com/facebook/react/issues/25843#issuecomment-1406766561 for the latest update.

**Comment by rohitguptaa22** [comment]
hi can you please assign this issue to me?
