### ISSUE TITLE
[Bug]: "display-metrics-changed" When window is minimized when using only the built-in monitor

### ISSUE THREAD

**Issue by tboulis** [electron/electron#36951]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

`display-metrics-changed` should not be fired when the app is minimized. 

### Actual Behavior

`display-metrics-changed` is fired when the app is minimized but only when you use the built-in monitor (no external monitor plugged in).

### Testcase Gist URL

https://gist.github.com/6605c8c73fb00b282ece6130a2296264

### Additional Information

This code:
```js
screen.on('display-metrics-changed', (event, display, changedMetrics) => {
    console.log({
        display,
        changedMetrics,
    });
});
```

outputs this when the window is minimized and then maximized:
```js
{
  display: {
    id: 1,
    bounds: { x: 0, y: 0, width: 1728, height: 1117 },
    workArea: { x: 0, y: 38, width: 1728, height: 1002 },
    accelerometerSupport: 'unknown',
    monochrome: false,
    colorDepth: 30,
    colorSpace: '{primaries:BT709, transfer:SRGB_HDR, matrix:RGB, range:FULL}',
    depthPerComponent: 10,
    size: { width: 1728, height: 1117 },
    displayFrequency: 120,
    workAreaSize: { width: 1728, height: 1002 },
    scaleFactor: 2,
    rotation: 0,
    internal: true,
    touchSupport: 'unknown'
  },
  changedMetrics: [ 'workArea' ]
}
{
  display: {
    id: 1,
    bounds: { x: 0, y: 0, width: 1728, height: 1117 },
    workArea: { x: 0, y: 38, width: 1728, height: 1004 },
    accelerometerSupport: 'unknown',
    monochrome: false,
    colorDepth: 30,
    colorSpace: '{primaries:BT709, transfer:SRGB_HDR, matrix:RGB, range:FULL}',
    depthPerComponent: 10,
    size: { width: 1728, height: 1117 },
    displayFrequency: 120,
    workAreaSize: { width: 1728, height: 1004 },
    scaleFactor: 2,
    rotation: 0,
    internal: true,
    touchSupport: 'unknown'
  },
  changedMetrics: [ 'workArea' ]
}
```

I've verified this behaviour on two different Macbook Pro. It happens only when you use the built-in monitor. If I plug in my external monitor, I'm unable to reproduce.

**Comment by codebytere** [comment]
@tboulis can you be more specific? I ran your fiddle with the same parameters, then minimized the application, followed by clicking the dock icon to un-minimize it, and could not reproduce.

**Comment by codebytere** [comment]
Same here  - Ventura 13.1 🤔 how did you minimize/unminimize it? Is there a way you could automate that into the fiddle to remove potential discrepancies? I notice the difference seems to be 2px in the `workArea`, which is also interesting

**Comment by codebytere** [comment]
Let me know if it comes up again and i can re-investigate!
