### ISSUE TITLE
[Bug]: macOS button order of dialog is not really deterministic

### ISSUE THREAD

**Issue by bpasero** [electron/electron#36973]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.3

### What operating system are you using?

macOS

### Operating System Version

12.6.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The order and visual presentation of buttons in message box dialogs is a bit of a mystery to me on macOS, so I am wondering if this is something Electron does or if its native macOS behaviour.

It looks like the presence of `cancelId` property results in resorting of buttons. On top of that, with 2 buttons you get them from left to right and with 3+ buttons you get them from top to bottom (which is probably macOS standard behaviour since a few years).

Here are some examples and related questions:

1) 2 buttons, no cancel button (achieved by invalid index)

```js
const res = dialog.showMessageBoxSync(mainWindow, {
  title: "Hello World",
  buttons: ["1", "2"],
  cancelId: 100
});
```

<img width="286" alt="image" src="https://user-images.githubusercontent.com/900690/213785265-b417c778-97a1-4814-81e2-1440934626df.png">

Here, the button "2" comes first and "1" second. Imho unexpected, given the next example.

2) 3 buttons, no cancel button (achieved by invalid index)

```js
const res = dialog.showMessageBoxSync(mainWindow, {
  title: "Hello World",
  buttons: ["1", "2", "3"],
  cancelId: 100
});
```

<img width="278" alt="image" src="https://user-images.githubusercontent.com/900690/213785481-be195a18-fe40-4784-b393-8be44657eebd.png">

Here the order is preserved, which I think is correct.

3) 3 buttons, with cancel button

```js
const res = dialog.showMessageBoxSync(mainWindow, {
  title: "Hello World",
  buttons: ["1", "2", "3"],
  cancelId: 1
});
```

<img width="286" alt="image" src="https://user-images.githubusercontent.com/900690/213785675-ab383162-e32a-4b10-a903-902d8abe2c6b.png">

Here it seems that when `cancelId` is a valid index, that button will be moved to the end with a slight gap to the 2 other buttons. Again, not sure if macOS does this or Electron.

4) 2 buttons, with cancel button (variant a)

```js
const res = dialog.showMessageBoxSync(mainWindow, {
  title: "Hello World",
  buttons: ["1", "2"],
  cancelId: 0
});
```

<img width="287" alt="image" src="https://user-images.githubusercontent.com/900690/213785981-beb9a522-b626-411a-90de-8e2d15326743.png">

Looks like the same result as in the beginning where `cancelId` was invalid, but what if we change to the other button...?

5) 2 buttons, with cancel button (variant b)

```js
const res = dialog.showMessageBoxSync(mainWindow, {
  title: "Hello World",
  buttons: ["1", "2"],
  cancelId: 1
});
```

<img width="285" alt="image" src="https://user-images.githubusercontent.com/900690/213786100-a448edfb-2c25-48c5-bdcd-d5bbb9b04c4e.png">

Interesting, now we got a blue default button?

### Actual Behavior

I think I would expect all platforms to be the same here and leave the button order as I pass it in. This seems to be the case on Linux and Windows anyway.

On top of that, I would not render a default button unless one is provided via the `defaultId` option.

Btw on Windows and Linux it seems not possible to disable the cancel support of a dialog via `Escape` key, while on macOS you can. That also seems a bit inconsistent.

### Additional Information

I would be happy for details how this is made up, whether this is Electron doing something or whether this is all macOS doing.

//cc @deepak1556

**Comment by bpasero** [comment]
The Apple [HIG](https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts) state:

> Place buttons where people expect. In general, place the button people are most likely to choose on the trailing side in a row of buttons or at the top in a stack of buttons. Always place the default button on the trailing side of a row or at the top of a stack. Cancel buttons are typically on the leading side of a row or at the bottom of a stack.

As such I think the observed behaviour makes sense based on `cancelId`:
* with 2 buttons: at the leading edge of the row
* with 3 buttons: at the trailing edge of the stack

**Comment by codebytere** [comment]
@bpasero is there behavior you still think needs correction/change based on your most recent comment? Or is this something which perhaps just merits better documentation?

**Comment by bpasero** [comment]
@codebytere curious, does Electron just pass on the options, or is there any massaging happening for `buttons`, `cancelId` and `defaultId`?

**Comment by ckerr** [comment]
@bpasero on macOS the actual indexing is a pass-through to `[NSAlert addButtonWithTitle]` in a loop.

There is some light work done to set key equivalents when cancelId and / or defaultId are specified; but AFAICT that doesn't affect the button order.

Relevant code starts at https://github.com/electron/electron/blob/32288ac9c588fe8c3b814338aaf5df7fddbce276/shell/browser/ui/message_box_mac.mm#L61

**Comment by ckerr** [comment]
Also, agree with @codebytere's previous question -- if the observed behavior matches HIG, is there any action that needs to be taken here or should this issue be closed?

**Comment by bpasero** [comment]
I did some testing on macOS Catalina before they started to show 3 buttons in a stack from top to bottom and notice a difference, but I will keep our code that we have to reshuffle buttons based on `cancelId` presence for older macOS versions.
