### ISSUE TITLE
[Bug]: nativeTheme.themeSource doesn't work

### ISSUE THREAD

**Issue by DoneDeal0** [electron/electron#36986]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.2

### What operating system are you using?

macOS

### Operating System Version

10.13.4

### What arch are you using?

x64

### Expected Behavior

When setting `nativeTheme.themeSource = "dark"`, the title bar should be dark. 

### Actual Behavior

When setting `nativeTheme.themeSource = "dark"`, the title bar remains grey.

### Additional Information

I set `nativeTheme.themeSource = "dark"` at the top of the file. Here is the code in main.ts:

```ts
import { app, BrowserWindow, nativeTheme } from "electron";

nativeTheme.themeSource = "dark";

declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
      contextIsolation: false,
    },
  });

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY).then(() => {
    splash.close();
    mainWindow.center();
    mainWindow.show();
  });

  const splash = new BrowserWindow({
    width: 1200,
    height: 800,
    transparent: true,
    alwaysOnTop: true,
  });
  splash.loadFile("./src/splash-screen/index.html");
  splash.center();

  if (process.env.NODE_ENV === "development") {
    mainWindow.webContents.openDevTools();
  }
};

app.on("ready", createWindow);

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
```

**Comment by Sheikh-JamirAlam** [comment]
Can you maybe share a screenshot?

**Comment by dsanders11** [comment]
@DoneDeal0, I believe this is expected behavior. In macOS 10.13 there isn't support for app-level dark mode, that was introduced in macOS 10.14. I'm going to close this issue for now, but if you see the issue on macOS 10.14 and newer, please ping me and I'll re-open.
