### ISSUE TITLE
[Bug]: Unable to resize, with cursor drag, from edge of window that is set to -webkit-app-region:drag

### ISSUE THREAD

**Issue by takumus** [electron/electron#37008]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0-beta.5

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro (10.0.22621 Build 22621)

### What arch are you using?

x64

### Last Known Working Electron version

22.0.3

### Expected Behavior

User is able to resize window from the edge of window that is set to `webkit-app-region:drag` , by dragging from this edge. (reproducible up till version 22.0.3)

### Actual Behavior

User is unable to resize window from the edge of window that is set to `webkit-app-region:drag` , by dragging from this edge. 

https://user-images.githubusercontent.com/15127636/214312123-018f7ea2-2e9c-4e6c-8a8f-1489943007c3.mp4

### Testcase Gist URL

https://gist.github.com/takumus/9054bde77c8206143232fed2659bf108

**Comment by codebytere** [comment]
Looks like https://github.com/electron/electron/commit/184ac2b382e8324a0b3db1944fd17cdd6ccffff9 did it - i can try to look into it soon!

**Comment by tejashvi-t** [comment]
Hey I want to contribute on this issue please assign this issue to me .
