### ISSUE TITLE
[Bug]: Build version does not work properly

### ISSUE THREAD

**Issue by crazydevlegend** [electron/electron#37018]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.2

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows 11 version 22H2

### What arch are you using?

x64

### Expected Behavior

When I run the electron app on dev mode, everything works fine.

It's browsing a web page hosted on local network.
But when I run the build version (released with `electron-builder`), it should work fine as it shows on the browser.

### Actual Behavior

But when I run the build version (released with `electron-builder`), it doesn't browser a webpage on local network (only the page title is shown).
And the whole web page is white-screen.

**Comment by crazydevlegend** [comment]
My electron app disconnects Internet connection internally.
And make LAN available while it's running.

Do you have any ideas why this happens? or anyone experienced similar issues before?

**Comment by salahawk** [comment]
I had the same issue, and couldn't managed to resolve yet.

- I tried with different proxy settings, but no LUCK
- I tried on different machines, but some work, and others don't

I really look forward to having the answer for this issue.

Thanks in advance.

**Comment by ckerr** [comment]
FWIW, electron-builder isn't a project run by the electron org. If you think the bug is specific to electron-builder then consider reporting it upstream to that project at https://github.com/electron-userland/electron-builder

As for stock Electron 22.0.2, I'd say just try downloading it straight from npm at https://www.npmjs.com/package/electron/v/22.0.2 and see if the problem persists; that way we can eliminate any question of whether the issue requires electron-builder

**Comment by salahawk** [comment]
I finally managed to resolve my issue.
For me, it was because the HTTP request kept disconnected while trying to load the webpage because the network is being switched in the meantime.
I'm not sure if this is your case, but can you please debug your app with remove debugging tool, @crazydevlegend ?

**Comment by codebytere** [comment]
Closing as this is not an issue with Electron itself.
