### ISSUE TITLE
GH Workflow Fails to Trigger `mksnapshot` Release for `23-x-y` Prereleases

### ISSUE THREAD

**Issue by dsanders11** [electron/electron#37028]
Example failure: https://github.com/electron/electron/actions/runs/3991558400

I think there are two issues here:
* First looks like a permission error, possibly because [the permissions for the workflow](https://github.com/electron/electron/blob/a30a9c7c4faa5aca476dd593dd02bbfac43432df/.github/workflows/release_dependency_versions.yml#L10-L11) are too restrictive? Not sure what the correct permission is to trigger a cross-repo workflow.
* It looks like [`update-version.js` in `mksnapshot`](https://github.com/electron/mksnapshot/blob/ca16d69d8fd1257caceac224aa5397d12d95ae64/script/update-version.js#L4) would reject prerelease versions

**Comment by xcyn** [comment]
thanks
