### ISSUE TITLE
[Bug]: nodeIntegrationInWorker: true makes the app crash using AudioWorklet

### ISSUE THREAD

**Issue by rmnbrd** [electron/electron#37038]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.1.0

### What operating system are you using?

MacOS

### Operating System Version

Ventura 13.2

### What arch are you using?

arm64 (and x64)

### Last Known Working Electron version

9

### Expected Behavior

The app shouldn't crash.

### Actual Behavior

Setting `nodeIntegrationInWorker: true` will make the app crash when using an AudioWorklet.

I forked the `electron-quickstart` project in order to be able to easily reproduce the issue.
The changes can be found here: https://github.com/electron/electron-quick-start/compare/master...rmnbrd:electron-quick-start:issue-node-integration-in-worker-and-audio-worklet

**Reproduction steps**
- Clone the example I've linked right above
- Run `yarn && yarn start`
- Click the `Start AudioWorklet` button **twice**
- Click the `Reload` button
- **App crashes**

### Testcase Gist URL

https://github.com/electron/electron-quick-start/compare/master...rmnbrd:electron-quick-start:issue-node-integration-in-worker-and-audio-worklet

### Additional Information

We have tested on several versions of Electron (22, 21, 20, 19). 
It is worth noting that:
- We could not experience that issue on v9 and below.
- The bug is not reproducible on v22 if `nodeIntegrationInWorker` is set to `false`.
- The bug is not reproducible on Chrome 109.

---

Here you will find the complete crash report:
https://pastebin.com/wrKshgK3

**Comment by nornagon** [comment]
was able to reproduce the crash in a debug build:
```
[77923:0126/155131.809763:FATAL:node_bindings.cc(127)] Check failed: uv_is_closing(handle). 
0   Electron Framework                  0x00000001181db4c4 base::debug::CollectStackTrace(void**, unsigned long) + 28
1   Electron Framework                  0x0000000118117080 base::debug::StackTrace::StackTrace() + 24
2   Electron Framework                  0x000000011812cc24 logging::LogMessage::~LogMessage() + 164
3   Electron Framework                  0x000000011812d82c logging::LogMessage::~LogMessage() + 12
4   Electron Framework                  0x0000000118111260 logging::CheckError::~CheckError() + 36
5   Electron Framework                  0x00000001144e06f0 _ZZN12_GLOBAL__N_122stop_and_close_uv_loopEP9uv_loop_sEN3$_08__invokeEP11uv_handle_sPv + 104
6   Electron Framework                  0x000000011433846c uv_walk + 188
7   Electron Framework                  0x00000001144dd7fc electron::NodeBindings::~NodeBindings() + 140
8   Electron Framework                  0x000000011453d02c electron::NodeBindingsMac::~NodeBindingsMac() + 12
9   Electron Framework                  0x0000000114504eec electron::WebWorkerObserver::~WebWorkerObserver() + 216
10  Electron Framework                  0x0000000114505184 electron::WebWorkerObserver::ContextWillDestroy(v8::Local<v8::Context>) + 288
11  Electron Framework                  0x000000011adc1074 blink::WorkerThread::PrepareForShutdownOnWorkerThread() + 400
12  Electron Framework                  0x000000011817b974 base::TaskAnnotator::RunTaskImpl(base::PendingTask&) + 284
13  Electron Framework                  0x000000011819ec74 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) + 1208
14  Electron Framework                  0x000000011819e304 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() + 108
15  Electron Framework                  0x0000000118134ad0 base::MessagePumpDefault::Run(base::MessagePump::Delegate*) + 120
16  Electron Framework                  0x000000011819f98c base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) + 420
17  Electron Framework                  0x000000011815a5f0 base::RunLoop::Run(base::Location const&) + 448
18  Electron Framework                  0x0000000116e15b50 blink::scheduler::NonMainThreadImpl::SimpleThreadImpl::Run() + 260
19  Electron Framework                  0x00000001181e7a50 base::(anonymous namespace)::ThreadFunc(void*) + 132
20  libsystem_pthread.dylib             0x00000001a618c26c _pthread_start + 148
21  libsystem_pthread.dylib             0x00000001a618708c thread_start + 8
Task trace:
0   Electron Framework                  0x000000011adc0c38 blink::WorkerThread::Terminate() + 252
1   Electron Framework                  0x00000001188d3974 IPC::(anonymous namespace)::ChannelAssociatedGroupController::Accept(mojo::Message*) + 528
Crash keys:
  "blink_scheduler_async_stack" = "0x1188D3974 0x0"
  "v8_ro_space_firstpage_address" = "0x35bb00000000"
  "v8_isolate_address" = "0x148030000"
  "num-experiments" = "0"
  "platform" = "darwin"
  "process_type" = "renderer"
  "osarch" = "arm64"
  "pid" = "77923"
  "ptype" = "renderer"
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
[77920:0126/155134.012697:ERROR:kill_posix.cc(34)] waitpid(77922): No child processes (10)
```

**Comment by nornagon** [comment]
Here's a [Fiddle](/electron/fiddle) for easy repro: https://gist.github.com/e5b882ff0e1b7e1eff7e7f3658f7b97d

**Comment by codebytere** [comment]
hey @rmnbrd i took a look at and this and have a preliminary fix up so this should be addressed soon!

**Comment by rmnbrd** [comment]
Hello @codebytere,
That's wonderful news, thanks a lot for taking the time to look into that ! 🎉

**Comment by rmnbrd** [comment]
Hey @codebytere, 
Thank you for having worked on that and merged a fix! 🤩 

I noticed that the ["publish" pipeline](https://github.com/electron/electron/runs/11003918544) was canceled, any reason why?
When could we expect to have the fix released to NPM?

Many thanks 🙂
