### ISSUE TITLE
[Question] Correct way to import a native module from an AudioWorklet?

### ISSUE THREAD

**Issue by rmnbrd** [electron/electron#37043]
Hi there!

I've got a quick question regarding the usage of a native module in the context of an `AudioWorklet` module.

This module uses C++ code, compiled thanks to `node-pre-gyp`. 
As of now, the only solution I've found to be able to import and use this module is that hacky condition:

```
const isDev = process.env.NODE_ENV === 'development';

const addonPath = isDev
  ? path.resolve(
      process.resourcesPath.slice(0, process.resourcesPath.indexOf('electron')),
      'native-audio-processor'
    )
  : path.resolve(process.resourcesPath, 'app.asar.unpacked', 'node_modules', 'native-audio-processor');

const { AudioProcessor } = require(addonPath);
```

---

**Is there any alternative to this, or any other cleaner way to achieve that?**

Many thanks in advance.

**Comment by Mudassir55** [comment]
One alternative way to import a native module in an Electron app's AudioWorklet context is to use the 'require' method from the 'remote' module of Electron. The 'remote' module allows you to access the main process from the renderer process, which is where the AudioWorklet runs.

You can use 'remote.require' to import the native module in the main process and then pass it to the AudioWorklet via a message. In the AudioWorklet, you can use the 'onmessage' event to listen for messages from the main process and receive the imported native module.
I have attached a file you can try that code in this way you don't need to check the environment or use the 'path.resolve'
 method, it's more elegant and cleaner.

![suggestedcode](https://user-images.githubusercontent.com/91305738/215254392-633065ab-19a3-4f46-9efa-046095057049.PNG)

**Comment by mlaurencin** [comment]
Thanks for reaching out!

I am going to close this as it seems to have been answered. For future, it would be best to direct questions to one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try. The issues tracker should be reserved for feature requests and bug reports.

I hope this helps
