### ISSUE TITLE
[Feature Request]: Make use of Happy Eyeballs algorithm according to RFC 8305

### ISSUE THREAD

**Issue by treysis** [electron/electron#37044]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, Electron forces NodeJS to reorder DNS results (`ipv4first`) overriding the the default set by the operating system, giving precedence to IPv4. This breaks Electron on IPv6-only networks, which are especially common in mobile networks.

### Proposed Solution

NodeJS v18.13 introduces support for Happy Eyeballs as described in RFC 8305. This algorithm makes NodeJS connect to IPv4 and IPv6 addresses in an alternating fashion, making NodeJS and thus Electron work in IPv4- as well as IPv6-only networks. The Happy Eyeballs algorithm is very well established and already used by many applications, including every browser around (Chrome, Firefox, Safari, Internet Explorer).

The Happy Eyeballs algorithm can be activated by passing the `net.setDefaultAutoSelectFamily(true)` to NodeJS.

### Alternatives Considered

There are no known alternatives to using Happy Eyeballs.

### Additional Information

See also https://github.com/electron/electron/issues/31515 which mentions Happy Eyeballs should be used once available.

**Comment by VerteDinde** [comment]
Hey @treysis, I just wanted to clarify an option that @/nornagon mentioned in 31515 - I think you can already use `dns.setDefaultResultOrder('verbatim')` in your app, as an alternative to the `ipv4first` default.

Previous versions of Electron were built using Node 16.x, which does set `ipv4first` as the default ([see docs here](https://nodejs.org/docs/latest-v16.x/api/dns.html#dnssetdefaultresultorderorder)). However, Electron 23 and higher should be using Node 18, which changed the default value to [verbatim](https://nodejs.org/docs/latest-v18.x/api/dns.html#dnssetdefaultresultorderorder). If you don't want to manually set a different default, have you tried using Electron 23 or higher in your app? As far as I'm aware, we're not deliberately changing the defaults set by Node here (correct me if I'm wrong). If the behavior seems wrong and you have a repro of the issue, happy to take a look!

**Comment by treysis** [comment]
> `dns.setDefaultResultOrder('verbatim')` in your app, as an alternative to the `ipv4first` default.

That's a really bad advice that will break Electron apps for many IPv6 users. It would be best to implement node v18.13 and adjust the `net`-calls to use Happy Eyeballs. Once node backports the global setter for Happy Eyeballs to v18.x, this should/could be enabled as the default.

**Comment by codebytere** [comment]
This isn't really an issue with Electron itself at the moment. Users can already call `setDefaultAutoSelectFamily()` via out Node.js integration. Per docs:

> The default value for autoSelectFamily option can be changed at runtime using `setDefaultAutoSelectFamily` or via the command line option `--enable-network-family-autoselection`.

This is something Electron developers can and should make use of, sure, but not something that should change at this time in Electron's own code base. It's a user configuration.

**Comment by treysis** [comment]
> Users can already call `setDefaultAutoSelectFamily()` via out Node.js integration. Per docs:

No, they can't. This setting is currently only available in Node v19.4+. General support for Happy Eyeballs exists only from Node v18.13+. Electron 23 still uses Node v18.12.x, and Electron 24-alpha uses Node v18.14 (which supports Happy Eyeballs, but not the global setting).

However, I do understand how users/developers are supposed to make use of the Node integration. It might be great however if Electron offered an option to override such defaults by the end user.
