### ISSUE TITLE
[Feature Request]: Allow clearing of aspect ratio

### ISSUE THREAD

**Issue by schontz** [electron/electron#37040]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

`window.setAspectRatio` allows us to specify the resizing aspect ratio for a window, but how can we reset this value to allow any aspect ratio? Perhaps `window.clearAspectRatio` (which might also warrant the addtion of `window.getAspectRatio`).

### Proposed Solution

I want to go between enforcing and not enforcing aspect ratio, e.g.:

```
window.setAspectRatio(bounds);

// later...

if (window.getAspectRatio()) {
  window.clearAspectRatio();
}
```

### Alternatives Considered

Current workaround is to destroy the window once it has aspect ratio set and re-create a new one without aspect ratio.

**Comment by codebytere** [comment]
This isn't well documented, but setting it to 0 or below resets it.

**Comment by schontz** [comment]
Is there any API for restricting resizing to one axis?

**Comment by codebytere** [comment]
@schontz yes - you could set `height`, `minHeight` and `maxHeight` to the same value, or vice versa for width, etc.

**Comment by varunlmxd** [comment]
is this issue still open, can you assign this issue to me and can I work on this issue

**Comment by schontz** [comment]
Closed since it works, but re-opened so docs can get updated.
