### ISSUE TITLE
[Bug]: Using child_process.spawn to spawn a script throws Unknown system error -8

### ISSUE THREAD

**Issue by Virian** [electron/electron#37051]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.x, 23.x, 16.2.4+

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

16.2.3

### Expected Behavior

When spawning a script, it should be executed

### Actual Behavior

Spawning a script throws following error:
```
(node:17575) UnhandledPromiseRejectionWarning: Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:737:9)
```

### Testcase Gist URL

https://gist.github.com/Virian/c9e20f3ae547cd695523d165dd84bb94

### Additional Information

This scenario stopped working in version 16.2.4 and is broken to this day. The script has permissions of 755, so it is executable. The command I want to run is `open`, although the error is thrown even when the command in the script is, for example, `echo`. There is no error if I change `shell` to `true` but in my case, I need to leave it as `false`.

**Comment by rafrafek** [comment]
I'm getting the same error message in OpenLens, Electron 19.1.9

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/23004737/216051018-801bc1a8-5e9e-47c1-b346-eed052f0feaf.png">

**Comment by eeror** [comment]
Just in case anyone runs into this again at some point: adding a shebang to the script would also solve the issue.
