### ISSUE TITLE
[Bug]: Electron not able to load large audio after packaging

### ISSUE THREAD

**Issue by lzz29** [electron/electron#37068]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.9

### What operating system are you using?

macOS

### Operating System Version

macOS

### What arch are you using?

x64

### Question

I use vue3 + electron
In development mode, I can successfully play the audio.
After packaging, audio does not play.

### Actual Behavior
```
<template>
  <div class="music">
    <div>
        <audio controls loop :src='audio1' />
    </div>
    <div>
        <audio controls loop :src='audio2' />
    </div>
    <div>
        <audio controls loop :src='audio3' />
    </div>
  </div>
</template>

<script>
import audio1 from '../assets/media/y990.mp3'
import audio2 from '../assets/media/13257.mp3'
import audio3 from '../assets/media/clock.wav'
export default {
  name: 'music',
  data() {
    return {
        audio1:audio1,
        audio2:audio2,
        audio3:audio3,
    }
  },
}
</script>

<style lang='scss'>
.music{
    -webkit-app-region: drag;
}
</style>
```
Code is very simple.
The page load several audio.
When the size of the audio exceeds 2m, it cannot be played.
One of the 47k aiduo can be played.

**Comment by Prinzhorn** [comment]
> 13.6.9

EOL was 25 May 2021

**Comment by VerteDinde** [comment]
@lzz29 Like @Prinzhorn mentioned above, 13.x has unfortunately been EOL for some time - would it be possible to try using a newer version of Electron, and could you let us know what method you're using to package the app? If you could share a repo of your code or a repro pre-/post-package that we could look at, that would be very appreciated!

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
