### ISSUE TITLE
[Bug]: `ipcRenderer` seems broken

### ISSUE THREAD

**Issue by zhanghaobin** [electron/electron#37067]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.6

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

x64

### Expected Behavior

`ipcRenderer` should work properly, including `ipcRenderer.send()`, `ipcRenderer.sendSync()`, `ipcRenderer.sendTo()`, `ipcRenderer.invoke()`, `ipcRenderer.postMessage()` etc ...

### Actual Behavior

`ipcRenderer` seems broken sometime:
- The main process never received the message sent by `ipcRenderer.send()`, `ipcRenderer.sendSync()`, `ipcRenderer.invoke()`, `ipcRenderer.postMessage()`
- Other renderer process never received the message sent by `ipcRenderer.sendTo()`
- `ipcRenderer.sendSync()` always returns `null`
- `ipcRenderer.on()` can still receive the message from other process
- Unable to create a new `<webview>` element
- `ipcRenderer` works fine in other webContents, including window and webview
- `ipcRenderer` works normal after the page reloaded

### Additional Information

I'm sorry I can't reproduce the issue, it happened randomly in some user's machine, both macOS and Windows system.

I don't know how to debug this problem, maybe the mojo message pipe disconnected? And how can I debug the `ipcRenderer` internal implementation?

Maybe related: [#25035](https://github.com/electron/electron/issues/25035) [#31733](https://github.com/electron/electron/issues/31733)

**Comment by dsanders11** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline).

If you're still experiencing this issue in the latest version of Electron, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. If we don't see a response in 10 days, I'll close this issue.

Thanks in advance! Your help is appreciated.

**Comment by zhanghaobin** [comment]
> Thank you for taking the time to report this issue and helping to make Electron better.
> 
> The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline).
> 
> If you're still experiencing this issue in the latest version of Electron, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.
> 
> I'm setting the `blocked/need-info` label for the above reasons. If we don't see a response in 10 days, I'll close this issue.
> 
> Thanks in advance! Your help is appreciated.

@dsanders11  Thank you for your reply!

I wonder how could I debug this issue? What information would help to debug this issue and how to collect such information? 

Is there any guesses on this issue? For example, what causes `ipcRenderer.sendSync()` always returns null?

**Comment by dsanders11** [comment]
@zhanghaobin, if you can confirm you see the behavior on newer, supported versions of Electron (ideally v22), then we can dig a bit deeper on debugging.

**Comment by zhanghaobin** [comment]
Sorry, we don't have the plan to upgrade Electron version to such high version for our App in a short time. I just want to figure out the causes of this issue and try to avoid it. 

But I can try to package our App with high Electron version and see if the issue recurs.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by Rabbitzzc** [comment]
> @dsanders11 Thank you for your reply!
> 
> I wonder how could I debug this issue? What information would help to debug this issue and how to collect such information?
> 
> Is there any guesses on this issue? For example, what causes `ipcRenderer.sendSync()` always returns null?

![image](https://user-images.githubusercontent.com/26913511/233241087-4e378d0d-0691-4c81-a770-403141681e02.png)

in `api/remote.ts` file
```ts
const command = IPC_MESSAGES.BROWSER_MEMBER_GET;
const meta = ipcRender.sendSync(command, ....)
```
In some cases, the `meta` is null.. I have no idea...
