### ISSUE TITLE
[Bug]: The transparent borderless window display error under win11

### ISSUE THREAD

**Issue by fanchenio** [electron/electron#37088]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows11

### What arch are you using?

x64

### Expected Behavior

normal display

![image](https://user-images.githubusercontent.com/88647148/215938855-31ccc3af-cd47-438b-99dd-1ec5088ddb48.png)

### Actual Behavior

The window as a whole becomes transparent, and the picture also becomes transparent.

![image](https://user-images.githubusercontent.com/88647148/215938946-795e26fd-7e6a-472e-9006-3e420aeddf66.png)

### Additional Information

`global.floatingWindow = floatingWindow = new BrowserWindow({
    width: 50,
    height: 50,
    frame: false,
    show: false,
    resizable: false,
    transparent: true,
    hasShadow: false,
    alwaysOnTop: true,
    opacity: 1,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      devTools: devTools,
    },
  })`

**Comment by fanchenio** [comment]
https://gist.github.com/df77e306d69048902b0b60b611a1fa13 @codebytere
It can be displayed normally under win10, but not under win11, and even the picture becomes transparent.

**Comment by fanchenio** [comment]
The electron 22 version also has this problem.

**Comment by fanchenio** [comment]
Is there no one to handle this?

**Comment by codebytere** [comment]
This is what i see when i run on Windows 11:

<img width="380" alt="Screenshot 2023-03-14 at 7 21 24 PM" src="https://user-images.githubusercontent.com/2036040/225101215-6c0e87ae-4354-4027-81d5-6a21a94e6721.png">

Which seems correct?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
