### ISSUE TITLE
[Bug]: Web Bluetooth: Always cancelled request after first dismiss

### ISSUE THREAD

**Issue by cavonlee** [electron/electron#37090]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2 

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

Even if it didn't found any devices, after i dismiss the request, it should perform another scan next time i call requestDevice.

### Actual Behavior

After first dismiss the requestDevice, all later navigator.bluetooth.requestDevice return User cancelled immediatly.

### Testcase Gist URL

https://gist.github.com/111927e2d69b53c6c151eb6aa5070948

### Additional Information

I have create a simple tst code on Fiddle, see above.

I have alreadly check #10763, who seem like having the same problem but somehow he never repoduce it anymore. But i think i found the issue.

It's really simple to reproduce infact, just get "select-bluetooth-device" event, and run navigator.bluetooth.requestDevice({ filters: [{ services: [0xffff] }] }) in console, and just run it again, it will return user cancelled immediatly.

In fact, there's kinda a way to prevent that happend, is to call the callback in "select-bluetooth-device" event with an empty string when you need to cancel the discovery.

But, that's the main issue here, if there's no filtered device found at all, then you never get the callback function to call with an empty string. if then you dismiss the request, it will keep returning "user cancelled" immediatly everytime you call requesrDevice later.

the Fiddle example is demonstrating this. click scan, if there's no device found, click cancel, console will prompt "User cancelled the requestDevice()". if you uncomment the "acceptAllDevices" in renderer.js, which will found all the device, will not have this problem.

Is there a way to get the callback funtion? or a better way to cancel the discovery?

Thank you.

**Comment by jkleinsc** [comment]
@cavonlee can you further explain what you are trying to do?  When you use a filter and there are no devices that match then there is really no point in `select-bluetooth-device` being called because there are no devices available to select.

**Comment by cavonlee** [comment]
>

I am developing an application to connect ESP32 open source devices. Users can use our program to burn the firmware to the device and then connect to it. However, if the user hits search first and then goes to burn the firmware, the program returns an error message directly because the device was not able to find aany devices on the first search. The user cannot connect to the device until they restart the application.

I believe this is a bug, although the trigger conditions for this bug are rather harsh. I believe this should be a minor issue with where to handle Bluetooth events and should be easy to fix

**Comment by jkleinsc** [comment]
@cavonlee ok, I think I better understand what you are seeing.

When you call `navigator.bluetooth.requestDevice` multiple times without the callback from `select-bluetooth-device` being called, you will see `User cancelled the requestDevice()` because the first navigator.bluetooth.requestDevice is still pending a response to the callback and when you call  `navigator.bluetooth.requestDevice` again, it effectively cancels the first  navigator.bluetooth.requestDevice` and then you see the message.

I do now see what you mean about the callback from `select-bluetooth-device` not being available to cancel the pending `navigator.bluetooth.requestDevice` when no devices are returned.  I think this is the same issue as #37436.  Looking at the code I think I understand why this is happening and there is a relatively simple fix.

**Comment by cavonlee** [comment]
@jkleinsc Yes! seems like so. Do you have any suggestion to this? or should i wait for the fix update?

**Comment by cavonlee** [comment]
@jkleinsc Thanks a lot! It's fixed!
