### ISSUE TITLE
[Bug]: systemPreferences.getMediaAccessStatus('microphone') doesn't retrieve new status once changed in macOS Preferences

### ISSUE THREAD

**Issue by kafka-yu** [electron/electron#37091]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

macOS

### Operating System Version

11.7.2

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

unknown

### Expected Behavior

When changing the permission in system preference from Enabled to Disabled, and restart the app, I should get "denied" via the SDK `getMediaAccessStatus('microphone') `

<img width="780" alt="image" src="https://user-images.githubusercontent.com/3942409/216001046-6111aee0-0622-47ec-a059-db364034cef2.png">

### Actual Behavior

But now it still returns "granted"

### Additional Information

I have to run bash command: `tccutil reset Microphone xxx` to make it works. Is it a bug?

**Comment by codebytere** [comment]
This is unfortunately an upstream bug and not a bug in Electron. We plumb straight through to Chromium's [logic](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/media/webrtc/system_media_capture_permissions_mac.mm;l=153?q=CheckSystemVideoCapturePermission&sq=package:chromium&type=cs)

**Comment by kafka-yu** [comment]
Thanks for your Reply @codebytere 

While when it returns Denied, `askForMediaAccess` also returns Denied, it will not bring up the granting dialog, is it a bug or?

**Comment by MarshallOfSound** [comment]
The OS will not let you spam the underlying API that `askForMediaAccess` calls.  Repeatedly calling will not show the dialog more than once

**Comment by theogravity** [comment]
I actually have the opposite issue. If the user initially denies then goes to the panel and toggle it to enable, then quits and restarts, the status reports as not determined.

Looks like this:

- Native prompt to deny or grant.
- Select deny -> status is denied
- Open the security panel and toggle the permission for the app to allow
- App closes and reopens
- Status is reported as not determined

**Comment by theogravity** [comment]
It doesn't seem to be a Chromium bug, but probably a macOS bug itself. 

I looked at the Chromium code and also looked into `node-mac-permissions` to see how it was implemented, and the code is pretty much the same:

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/media/webrtc/system_media_capture_permissions_mac.mm;l=48;drc=0e9a0b6e9bb6ec59521977eec805f5d0bca833e0?q=CheckSystemVideoCapturePermission&sq=package:chromium&type=cs

https://github.com/codebytere/node-mac-permissions/blob/main/permissions.mm#L348

When trying `getAuthStatus()` from `node-mac-permissions`, I get the same bug.

**Comment by theogravity** [comment]
Update: You need to make sure the app hard quits and restarts. You can't do a soft quit (as in the electron app itself never quits) and it should properly read status from the panel.
