### ISSUE TITLE
Text renders incorrectly?  Larger than container compared to Firefox

### ISSUE THREAD

**Issue by Konglomneshued** [electron/electron#37105]
Unsure where to post this.  Could not find a repo for Chrome itself from Google.

Look _closely_, you can see the padding is not off, the text is.  Same exact code, I run in two browsers (Firefox and Brave) at localhost port and in Electron window.

It's a CSS grid layout, I have tried align baseline and center and it does not change.

Firefox:
![Screenshot from 2023-02-01 18-22-58](https://user-images.githubusercontent.com/94726665/216200293-4f230269-cfca-4aee-a577-5bfe43785876.png)
![Screenshot from 2023-02-01 18-32-29](https://user-images.githubusercontent.com/94726665/216201453-aa0ec8b7-5ab2-47c3-873b-673178e5c348.png)

Electron/Chrome/Brave:
![Screenshot from 2023-02-01 18-23-06](https://user-images.githubusercontent.com/94726665/216200297-f41152bd-aa15-477b-b2a6-a44e9f104f5e.png)
![Screenshot from 2023-02-01 18-32-46](https://user-images.githubusercontent.com/94726665/216201468-6d7c28d0-61e4-4c5f-a5e8-0d5888105457.png)

**Comment by codebytere** [comment]
Electron is based off of Chromium, so incomparability to Firefox or Firefox-based browser would not be an issue in Electron itself. I would post this issue on Chromium's issue tracker.
