### ISSUE TITLE
[Bug]: spurious ERR_FAILED for .html file on app.quit()

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#37123]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.2.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.2

### What arch are you using?

x64

### Expected Behavior

No failures on `app.quit()`.

### Actual Behavior

Very rarely it seems that app tries to access the html file that was opened in the main window, and fails with:

```
Unhandled Promise Rejection: Error: ERR_FAILED (-2) loading 'file:///Users/indutny/.../background.html
```

Unfortunately, I'm unable to reproduce it consistently, but happy to try anything if you have ideas!

**Comment by indutny-signal** [comment]
FWIW, I can reproduce it if I start Signal and press Cmd+Q while the preload script is loading/compiling (ours is 8mb).

**Comment by VerteDinde** [comment]
Hey @indutny-signal! I'll test a bit and see if I can reproduce this as well - when the error does appear, do you happen to know how it manifests for an end user? Does the application itself crash, or is it just logged with no user-facing errors? Just trying to better understand how it manifests so I can watch out for it.

**Comment by indutny-signal** [comment]
It is an unhandled rejection so unfortunately we do crash the application for our users. When this happens - we display a dialog like this:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/79877362/217154791-92287eba-8583-45d1-abd1-3cacaa10dd0a.png">

**Comment by indutny-signal** [comment]
You know what, looks like it might be just us awaiting `window.loadURL()`.  It doesn't resolve until preload finishes so terminating it in the middle results in an unhandled rejection. We'll add try catch around it.

**Comment by indutny-signal** [comment]
That being said, I don't know why this changed with electron update.

**Comment by mushan0x0** [comment]
bump
