### ISSUE TITLE
Get keyboard and mouse presses when the application is not on focus or running in background.

### ISSUE THREAD

**Issue by Scorpion197** [electron/electron#37138]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The current features allow a developer to get keyboard and mouse presses only when the application is on focus. However if we need to record them when we are using another application or running the electron app on in the background there isn't not a way to do it with the current features.

### Proposed Solution

Add an API to electron which interacts with the system I/O to get keyboard and mouse events.

### Alternatives Considered

Actually there is a node module which allows to interact with the system I/O but it would be much better if electron has its own API.

**Comment by codebytere** [comment]
In general, Electron likes to keep its core API surface area smaller when possible. As a result of this, things which can be trivially accomplished with native Node.js modules or similar should be done there. If that's not possible, we can potentially reconsider, but here it's the case that this is _already_ possible with an external module. Therefore, we're going to decline this at this time but if there are more compelling arguments or something changes we may reconsider.

**Comment by zqy233** [comment]
> In general, Electron likes to keep its core API surface area smaller when possible. As a result of this, things which can be trivially accomplished with native Node.js modules or similar should be done there. If that's not possible, we can potentially reconsider, but here it's the case that this is _already_ possible with an external module. Therefore, we're going to decline this at this time but if there are more compelling arguments or something changes we may reconsider.

[iohook](https://github.com/wilix-team/iohook) try this

**Comment by zqy233** [comment]
> which external module can do this ?

try this
https://github.com/wilix-team/iohook

**Comment by hrithikdas88** [comment]
io hook is not working anymore

**Comment by vojtabohm** [comment]
Did anyone come up with a different solution to iohook which is not working anymore?

**Comment by dladeira** [comment]
Perhaps we should reconsider this? I have been searching for a while for a module that does this, but can't seem to find any. `iohooks` is broken, and `robotjs` has been abandoned long time ago and old releases don't work on electron

**Comment by Scorpion197** [comment]
I finished by writing something similar to iohook using Rust

**Comment by vojtabohm** [comment]
could you please share it?

**Comment by dladeira** [comment]
I managed to get `robotjs` to work. There is a actively maintained fork available at [@hurdlegroup/robotjs](https://github.com/hurdlegroup/robotjs). It allows you to get the mouse position, but not listen to clicks or key presses.

**Comment by hrithikdas88** [comment]
On Windows, use the pynput library in Python to detect mouse movements and convert it into an executable using PyInstaller. On macOS, use the CGEventTap API in Swift to capture mouse events, including movement. For Linux, access /dev/input/mice or /dev/input/eventX to read raw mouse data. In all cases, the respective platform-specific executable is invoked from the Electron app using Node.js’s child_process to capture the mouse movement data. Finally, package everything with electron-builder, ensuring platform-specific executables are included for Windows, macOS, and Linux. This worked for me

**Comment by mustafazeb381-123** [comment]
> On Windows, use the pynput library in Python to detect mouse movements and convert it into an executable using PyInstaller. On macOS, use the CGEventTap API in Swift to capture mouse events, including movement. For Linux, access /dev/input/mice or /dev/input/eventX to read raw mouse data. In all cases, the respective platform-specific executable is invoked from the Electron app using Node.js’s child_process to capture the mouse movement data. Finally, package everything with electron-builder, ensuring platform-specific executables are included for Windows, macOS, and Linux. This worked for me

I did in python with screen shot but UI was not achievable in python in tkinter then I started it in the electron  and I have python code but I don't know we will be need venv for that to execute the python code rightlike how can we use that code in the electron.

**Comment by hrithikdas88** [comment]
Use PyInstaller to create a standalone executable of your Python script from within the activated virtual environment. This ensures that all necessary dependencies are bundled.

**Comment by mustafazeb381-123** [comment]
> Use PyInstaller to create a standalone executable of your Python script from within the activated virtual environment. This ensures that all necessary dependencies are bundled. then call the executable using child _process as mentioned above

okay
