### ISSUE TITLE
[Feature Request]: Clear cookies by url

### ISSUE THREAD

**Issue by djiangdev** [electron/electron#37136]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Support clear cookies for an url

### Proposed Solution

How to clear cookies by url?

### Alternatives Considered

Clear cookies by url is not support

**Comment by Prinzhorn** [comment]
https://www.electronjs.org/docs/latest/api/session#sesclearstoragedataoptions

**Comment by codebytere** [comment]
Closing in agreement with above, which addresses the root need.
