### ISSUE TITLE
[Bug]: ERROR: PlacementList must be sorted by first 8 bits of display_id

### ISSUE THREAD

**Issue by weilaimg** [electron/electron#37156]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

No warning/errors on start-up.

### Actual Behavior

When starting the program, there is an Error shown:

[26416:0207/133945.070:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id 
[26416:0207/133945.228:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id 

Even I did nothing but create a blank window.

![image](https://user-images.githubusercontent.com/18102105/217134738-bbd32ece-da3d-415c-b324-bef506ba99c3.png)
![image](https://user-images.githubusercontent.com/18102105/217134762-6e5e8b89-037f-424e-962e-b87e0cf7a5a1.png)

**Comment by weilaimg** [comment]
https://gist.github.com/weilaimg/87db29e78e9c346c4664b55eb395757a

Just need main,js and the issue occurred.

![image](https://user-images.githubusercontent.com/18102105/217152364-f024aa5c-5c22-4ffa-a182-27ec1c8303c8.png)

**Comment by codebytere** [comment]
is this affecting UI somehow? I cannot reproduce this and it seems to be upstream in origin.

**Comment by weilaimg** [comment]
> 

No, everything works fine but just errors in the console.

**Comment by maxzz** [comment]
I see the same problem started recently. Same line of code 551.
```
[16736:0214/164157.657:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id
[16736:0214/164157.727:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id
[16736:0214/164158.054:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id
```
By the way, I have two monitors (maybe this is related?).

**Comment by weilaimg** [comment]
> 

You reminded me that I have two monitors as well. Two external monitors and a Laptop original monitor. And when I disconnect one of them, the error has gone...

**Comment by aikrez** [comment]
Same issue with 2 external monitors. When for example using Cypress the application is started offscreen and cannot be moved.

**Comment by maxzz** [comment]
I recently worked on 3 different new applications with electron. With electron 24.4.0 I don't see this issue anymore.

**Comment by mdodge-ecgrow** [comment]
I am still getting the same error using "electron": "^25.2.0", "electron-builder": "^24.4.0".

Also, I have 2 external monitors and my main laptop screen all running.

**Comment by ediweissmann** [comment]
Running into this as well, seems to be related to having external monitors. Main window pops up and then disappears.

**Comment by maxzz** [comment]
Oh no, looks like this error is back again.

**Comment by oryaacov** [comment]
same here :(

**Comment by deadlinecode** [comment]
+1

**Comment by StuartDavies** [comment]
> > 
> 
> You reminded me that I have two monitors as well. Two external monitors and a Laptop original monitor. And when I disconnect one of them, the error has gone...

I'm so glad I stumbled across your comment at 2am the other morning - saved my sanity.

**Comment by felpsg** [comment]
It seems like I managed to work around this issue.

Disable Hardware Acceleration:
Disabling hardware acceleration can sometimes bypass graphical issues. You can do this by adding the following line to your settings.json file in VS Code:

**"terminal.integrated.gpuAcceleration": "off"**
