### ISSUE TITLE
[Bug]: Failed to get current electron version on manual build

### ISSUE THREAD

**Issue by footniko** [electron/electron#37163]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

x64

### Expected Behavior

It should generate Release build config of Electron without issues

### Actual Behavior

It returns a non-zero code

### Additional Information

I'm trying to build Electron with the instructions provided here: https://github.com/electron/electron/blob/main/docs/development/build-instructions-gn.md

But after I run the release build config preparation command I get the following:

```
gn gen out/Release --args="import(\"//electron/build/args/release.gn\")"
ERROR at //electron/BUILD.gn:110:20: Script returned non-zero exit code.
electron_version = exec_script("script/print-version.py",
                   ^----------
Current dir: /Users/sam/electron/src/out/Release/
Command: python3 /Users/sam/electron/src/electron/script/print-version.py
Returned 1 and printed out:

b"<Buffer 66 61 74 61 6c 3a 20 4e 6f 20 6e 61 6d 65 73 20 66 6f 75 6e 64 2c 20 63 61 6e 6e 6f 74 20 64 65 73 63 72 69 62 65 20 61 6e 79 74 68 69 6e 67 2e 0a>\n/Users/sam/electron/src/electron/script/lib/get-version.js:19\n    throw new Error('Failed to get current electron version');\n    ^\n\nError: Failed to get current electron version\n    at module.exports.getElectronVersion (/Users/sam/electron/src/electron/script/lib/get-version.js:19:11)\n    at [eval]:1:37\n    at Script.runInThisContext (node:vm:129:12)\n    at Object.runInThisContext (node:vm:307:38)\n    at node:internal/process/execution:79:19\n    at [eval]-wrapper:6:22\n    at evalScript (node:internal/process/execution:78:60)\n    at node:internal/main/eval_string:28:3\n\nNode.js v18.14.0\n"
```

```
python --version
Python 3.10.7
node -v
v18.14.0
```

Any hints?

**Comment by codebytere** [comment]
@footniko are you using `build-tools`?

**Comment by footniko** [comment]
I'm using `depot_tools` (fully manually). And having the same issue in Windows 10, btw.

**Comment by codebytere** [comment]
@footniko i recommend using `build-tools`. There are a lot of potential footguns when building fully manually that we smooth over in our toolkit, so it's a bit hard to say exactly what's gone wrong here. Feel free to re-open if `@electron/build-tools` gives you the same issue.

**Comment by CoorFun** [comment]
@footniko FYI, I had this same issue. The root cause and solution is here:

The problem comes from running python script:
```bash
python3 electron/script/print-version.py
```

In this script, it loads a node js script and calls to "getElectronVersion()" function:

Try to run it manually produces the issue.
```bash
node -p 'require("<path_to_src/electron/scripts/lib/get-version.js>").getElectronVersion()'
```

The root cause is that `getelectronVersion()` relies on git tags to resolve the current electron version. But if the electron git repo is fetched with `--depth 1` or gclient sync with `--no-history` argument, it loses this information. 

Simply direct to electron directory, and do a unshallow pull solves the issue.
```bash
cd electron
git pull --unshallow
```
