### ISSUE TITLE
[Bug]: Crash in WebRtcAudioDeviceImpl dtor

### ISSUE THREAD

**Issue by s-sasha** [electron/electron#37166]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.22621

### What arch are you using?

x64

### Expected Behavior

No crash

### Actual Behavior

Crash during webrtc session

### Additional Information

Sometimes the application crashes on garbage collection when **WTF::StringImpl** is released.

`
WTF::AtomicStringTable::Remove (atomic_string_table.cc:368)
[inlined] WTF::CurrentThread (threading.h:52)
WTF::Threading::Threading (threading.cc:45)
RtlAddRefActivationContext
RtlpGetStackLimits
[inlined] WTF::StringImpl::~StringImpl (string_impl.cc:78)
WTF::StringImpl::DestroyIfNotStatic (string_impl.cc:83)
[inlined] WTF::StringImpl::Release (string_impl.h:302)
[inlined] scoped_refptr<T>::Release (scoped_refptr.h:321)
[inlined] scoped_refptr<T>::~scoped_refptr (scoped_refptr.h:223)
[inlined] WTF::String::~String (wtf_string.h:58)
blink::WebRtcAudioDeviceImpl::~WebRtcAudioDeviceImpl (webrtc_audio_device_impl.cc:54)
_tailMerge_winusb.dll
rtc::RefCountedObject<T>::~RefCountedObject (ref_counted_object.h:56)
RtlpGetStackLimits
[inlined] delete (GrCpuBuffer.h:29)
GrCpuBuffer::~GrCpuBuffer (GrCpuBuffer.h:15)
rtc::RefCountedObject<T>::Release (ref_counted_object.h:42)
RtlAddRefActivationContext
[inlined] rtc::scoped_refptr<T>::~scoped_refptr (scoped_refptr.h:102)
cricket::WebRtcVoiceEngine::~WebRtcVoiceEngine (webrtc_voice_engine.cc:339)
_tailMerge_winusb.dll
_tailMerge_winusb.dll
_tailMerge_winusb.dll
_tailMerge_winusb.dll
_tailMerge_winusb.dll
_tailMerge_winusb.dll
cricket::WebRtcVoiceEngine::~WebRtcVoiceEngine (webrtc_voice_engine.cc:327)
base::sequence_manager::internal::SequencedTaskSource::SelectedTask::SelectedTask (sequenced_task_source.cc:16)
[inlined] std::__1::default_delete<T>::operator() (unique_ptr.h:54)
[inlined] std::__1::unique_ptr<T>::reset (unique_ptr.h:315)
[inlined] std::__1::unique_ptr<T>::~unique_ptr (unique_ptr.h:269)
cricket::CompositeMediaEngine::~CompositeMediaEngine (media_engine.cc:169)
RtlAddRefActivationContext
cricket::CompositeMediaEngine::~CompositeMediaEngine (media_engine.cc:169)
RtlpGetStackLimits
[inlined] std::__1::vector<T>::~vector (vector:558)
cricket::ChannelManager::~ChannelManager (channel_manager.cc:61)
[inlined] std::__1::default_delete<T>::operator() (unique_ptr.h:54)
[inlined] std::__1::unique_ptr<T>::reset (unique_ptr.h:315)
[inlined] webrtc::ConnectionContext::~ConnectionContext::<T>::operator() (connection_context.cc:150)
rtc::FunctionView<T>::CallVoidPtr<T> (function_view.h:109)
jingle_glue::JingleThreadWrapper::Dispatch (thread_wrapper.cc:226)
RtlAddRefActivationContext
RtlpGetStackLimits
jingle_glue::JingleThreadWrapper::ProcessPendingSends (thread_wrapper.cc:294)
jingle_glue::JingleThreadWrapper::PostTask (thread_wrapper.cc:330)
blink::HTMLParserScriptRunner::PendingScriptFinished (html_parser_script_runner.cc:302)
[inlined] base::WeakPtr<T>::operator* (weak_ptr.h:264)
[inlined] base::internal::FunctorTraits<T>::Invoke (bind_internal.h:535)
[inlined] base::internal::InvokeHelper<T>::MakeItSo (bind_internal.h:719)
[inlined] base::internal::Invoker<T>::RunImpl (bind_internal.h:772)
base::internal::Invoker<T>::RunOnce (bind_internal.h:741)
[inlined] mojo::SimpleWatcher::Context::Notify (simple_watcher.cc:101)
mojo::SimpleWatcher::Context::CallNotify (simple_watcher.cc:61)
_tailMerge_winusb.dll
[inlined] base::OnceCallback<T>::Run (callback.h:142)
base::TaskAnnotator::RunTaskImpl (task_annotator.cc:135)
base::sequence_manager::internal::SequenceManagerImpl::GetNextTaskTime (sequence_manager_impl.cc:765)
jingle_glue::JingleThreadWrapper::Send (thread_wrapper.cc:264)
jingle_glue::JingleThreadWrapper::PostTask (thread_wrapper.cc:330)
blink::HTMLParserScriptRunner::PendingScriptFinished (html_parser_script_runner.cc:302)
[inlined] mojo::SimpleWatcher::Context::Notify (simple_watcher.cc:101)
[inlined] mojo::SimpleWatcher::Context::CallNotify (simple_watcher.cc:61)
[inlined] mojo::SimpleWatcher::Context::Notify (simple_watcher.cc:101)
mojo::SimpleWatcher::Context::CallNotify (simple_watcher.cc:61)
[inlined] base::TaskAnnotator::RunTask (task_annotator.h:74)
[inlined] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl (thread_controller_with_message_pump_impl.cc:356)
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork (thread_controller_with_message_pump_impl.cc:261)
WaitForSingleObjectEx
<unknown>
base::sequence_manager::internal::ThreadController::RunLevelTracker::OnIdle (thread_controller.cc:86)
_tailMerge_winusb.dll
base::MessagePumpDefault::Run (message_pump_default.cc:38)
base::internal::PartitionMalloc (allocator_shim_default_dispatch_to_partition_alloc.cc:263)
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run (thread_controller_with_message_pump_impl.cc:468)
[inlined] base::internal::WeakReference::Flag::Flag (weak_ptr.cc:14)
[inlined] base::MakeRefCounted (scoped_refptr.h:98)
[inlined] base::internal::WeakReferenceOwner::WeakReferenceOwner (weak_ptr.cc:72)
base::internal::WeakPtrFactoryBase::WeakPtrFactoryBase (weak_ptr.cc:102)
base::RunLoop::Run (run_loop.cc:140)
_tailMerge_winusb.dll
[inlined] ShimMalloc (allocator_shim.cc:188)
malloc (allocator_shim_override_ucrt_symbols_win.h:67)
[inlined] base::internal::PlatformThreadLocalStorage::GetTLSValue (thread_local_storage.h:70)
[inlined] 'anonymous namespace'::GetTlsVectorStateAndValue (thread_local_storage.cc:200)
base::ThreadLocalStorage::Slot::Set (thread_local_storage.cc:445)
[inlined] base::internal::PlatformThreadLocalStorage::GetTLSValue (thread_local_storage.h:70)
[inlined] 'anonymous namespace'::GetTlsVectorStateAndValue (thread_local_storage.cc:200)
base::ThreadLocalStorage::Slot::Get (thread_local_storage.cc:430)
base::Thread::Run (thread.cc:334)
[inlined] base::WeakPtrFactory<T>::WeakPtrFactory (weak_ptr.h:342)
base::RunLoop::RunLoop (run_loop.cc:98)
_tailMerge_winusb.dll
_tailMerge_winusb.dll
base::Thread::Run (thread.cc:334)
base::Thread::ThreadMain (thread.cc:405)
[inlined] std::__1::lock_guard<T>::~lock_guard (__mutex_base:97)
base::internal::PCScanInternal::NotifyThreadCreated (pcscan_internal.cc:1539)
base::'anonymous namespace'::ThreadFunc (platform_thread_win.cc:123)
BaseThreadInitThunk
RtlUserThreadStart
`

As I understand the problem occurs :
1) **WebRtcAudioDevice** - is created and destroyed in the worker thread.
2) In the main thread, during initialization, **WebRtcAudioRenderer** calls **WebRtcAudioDeviceImpl::SetOutputDeviceForAec** and passes 
**WTF::AtomicString** which created on the main thread.
`source_->SetOutputDeviceForAec(output_device_id_);`
3) This value is not cleared when deinitializing **WebRtcAudioRenderer** (`RemoveAudioRenderer`)
 
As a result **AtomicString** is created in the main thread but is destroyed in worker thread - which leads to a crash.

Maybe **WebRtcAudioDeviceImpl::output_device_id_for_aec_** should be cleared before removing audio renderer 
`source_->SetOutputDeviceForAec(WTF::String());`

or create a copy of this string when passed to **SetOutputDeviceForAec** ( `WTF::String::isolatedCopy` )

**Comment by miniak** [comment]
Electron 17 is not supported

**Comment by codebytere** [comment]
Closing in agreement with https://github.com/electron/electron/issues/37166#issuecomment-1421661508 - this does not seem to occur on supported versions and therefore we will not be backporting to EOL versions.
