### ISSUE TITLE
[Bug]: Devtools links not clickable

### ISSUE THREAD

**Issue by SimonSiefke** [electron/electron#37184]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.10

### What arch are you using?

x64

### Expected Behavior

When clicking a link in Chrome Devtools, the link is opened in the default browser

### Actual Behavior

When clicking a link in Chrome Devtools, nothing happens.

### Additional Information

Detailed steps:
1. Launch any electron app using Electron Fiddle
2. Open Chrome Devtools
3. Navigate to the "Application" tab in Chrome Devtools
4. Click on "Local Storage"
5. Click on the "Learn more" link 
6. The link doesn't open

**Comment by codebytere** [comment]
This is intended behavior - see  https://github.com/electron/electron/pull/36774 for how to handle this.
