### ISSUE TITLE
[Bug]: Can't copy image via context menu

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#37187]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I expect to be able to add a context menu item to copy an image.

### Actual Behavior

Doesn't seem to be possible.

If I right click on the main image on google.com, I get a "copy image" menu item:
![image](https://user-images.githubusercontent.com/6374473/217587000-0a39a4c9-ef42-4cc3-9a8c-32637fc733cf.png)

In Electron, `params.hasImageContents` is `true`, but `params.editFlags.canCopy` is `false`.

I tried adding a copy item anyway:
```
if (params.hasImageContents) {
	menuItems.push({ role: "copy", label: "Copy image" });
}
```

But it doesn't copy anything.

### Testcase Gist URL

https://gist.github.com/378f492a867254c4c2aa7d5d81912a2d

**Comment by codebytere** [comment]
@pushkin- has this ever worked for you? I can reproduce this in versions back to 17 (i didn't try farther)

**Comment by pushkin-** [comment]
@codebytere No, I don't believe it ever has, but I never tried to get it to work until now.

**Comment by pushkin-** [comment]
bump

**Comment by codebytere** [comment]
Looked into this a bit more - that option is a custom Chrome option, not part of the default menu. It's controlled via [`chrome/browser/renderer_context_menu/render_view_context_menu.cc`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/renderer_context_menu/render_view_context_menu.cc) which we don't pull in or use at all. I can try to see what we can do here but it's not a bug per se.

**Comment by codebytere** [comment]
@pushkin- yes - it's not a bug as noted above. This is Chromium-specific functionality and not something that's inherent to or guaranteed with default menu functionality.

**Comment by thecodrr** [comment]
For someone else look for this, it's as simple as:

```js
    if (params.mediaType === "image") {
      menu.append(
        new MenuItem({
          id: "copyImage",
          label: "Copy Image",
          click() {
            webContents.copyImageAt(params.x, params.y);
          }
        })
      );
    }
```

**Comment by p2kmgcl** [comment]
I have a similar issue on Mac (at least it looks the same):

- The `editFlags.canCopy` variable is false (not sure in which case this should be true).
- The `copy` role does nothing.
- If I try to manually execute `webContents.copyImageAt(params.x, params.y)` on a click callback, the application just crashes with no error or log 🤷

This happens on electron 29

**Comment by codebytere** [comment]
This is something you can accomplish on the developer side. Under the hood, Chrome's Copy Image calls `RenderFrameHost::CopyImageAt` which we [already expose](https://github.com/electron/electron/blob/a0dad83ded4661eb873cc62b75bb0f406ad7fecb/docs/api/web-contents.md#L1418).

Working example:

```js
const {app, BrowserWindow, Menu } = require('electron')

async function createWindow () {
  const mainWindow = new BrowserWindow();
  await mainWindow.loadURL('https://google.com')
  mainWindow.webContents.on("context-menu", (e, params) => {
    const template = [{
      label: 'Edit',
      submenu: [
        {
          label: 'Cut',
          accelerator: 'CmdOrCtrl+X',
          role: 'cut'
        },
        {
          label: 'Copy',
          accelerator: 'CmdOrCtrl+C',
          role: 'copy'
        },
        {
          label: 'Copy Image',
          accelerator: 'CmdOrCtrl+I',
          enabled: params.hasImageContents,
          click: () => {
            mainWindow.webContents.copyImageAt(params.x, params.y)
          }
        },
        {
          type: 'separator'
        },
        {
          label: 'Paste',
          accelerator: 'CmdOrCtrl+V',
          role: 'paste'
        },
      ]
    }];

    const menu = Menu.buildFromTemplate(template);
    menu.popup(mainWindow, params.x, params.y);
  });
}

app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```
