### ISSUE TITLE
Missing release notes for 23.0.0

### ISSUE THREAD

**Issue by Prinzhorn** [electron/electron#37219]
This time I was more patient than with 14.0.0 (#30767) :smile: 

It's been three days and there are no release notes for 23.0.0 https://github.com/electron/electron/releases/tag/v23.0.0
I would like to upgrade but I need to know what changed. Maybe a bot messed up the release and needs a new trigger or something?

![image](https://user-images.githubusercontent.com/679144/218059949-dcd80c84-2c55-41c2-9eca-925929a01e8c.png)

**Comment by VerteDinde** [comment]
Thanks for the catch, @Prinzhorn! They've now been updated 🙇‍♀️ https://github.com/electron/electron/releases/tag/v22.2.0

**Comment by VerteDinde** [comment]
Thanks so much, @Prinzhorn! They've now been updated here 🙇‍♀️ https://github.com/electron/electron/releases/tag/v23.0.0
