### ISSUE TITLE
[Bug]: crashes on win11(ntdll.dll)

### ISSUE THREAD

**Issue by fangjiataigao** [electron/electron#37216]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.2

### What operating system are you using?

Windows

### Operating System Version

win11家庭版

### What arch are you using?

x64

### Last Known Working Electron version

无

### Expected Behavior

Microsoft (R) Windows Debugger Version 6.11.0001.404 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [\\Mac\Home\Desktop\e96510cb-ea3f-4940-beb0-b55055c1f5f0.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
Windows 7 Version 9200 (1105) MP (8 procs) Free x86 compatible
Product: WinNt
Machine Name:
Debug session time: Fri Feb 10 12:58:30.000 2023 (GMT+8)
System Uptime: not available
Process Uptime: 0 days 0:00:03.000
................................................................
......................
Loading unloaded module list
.
This dump file has a breakpoint exception stored in it.
The stored exception information can be accessed via .ecxr.
eax=00000000 ebx=100edd38 ecx=00000000 edx=00000000 esi=0030a000 edi=100edd38
eip=77b368ac esp=100edcd4 ebp=100edcf4 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000206
Unable to load image C:\Windows\SYSTEM32\ntdll.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for ntdll.dll
*** ERROR: Module load completed but symbols could not be loaded for ntdll.dll
ntdll+0x768ac:
77b368ac ??              ???

### Actual Behavior

Microsoft (R) Windows Debugger Version 6.11.0001.404 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [\\Mac\Home\Desktop\e96510cb-ea3f-4940-beb0-b55055c1f5f0.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
Windows 7 Version 9200 (1105) MP (8 procs) Free x86 compatible
Product: WinNt
Machine Name:
Debug session time: Fri Feb 10 12:58:30.000 2023 (GMT+8)
System Uptime: not available
Process Uptime: 0 days 0:00:03.000
................................................................
......................
Loading unloaded module list
.
This dump file has a breakpoint exception stored in it.
The stored exception information can be accessed via .ecxr.
eax=00000000 ebx=100edd38 ecx=00000000 edx=00000000 esi=0030a000 edi=100edd38
eip=77b368ac esp=100edcd4 ebp=100edcf4 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000206
Unable to load image C:\Windows\SYSTEM32\ntdll.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for ntdll.dll
*** ERROR: Module load completed but symbols could not be loaded for ntdll.dll
ntdll+0x768ac:
77b368ac ??              ???

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
