### ISSUE TITLE
[Bug]: SetWindowOpenHandler cannot be used for <webview />

### ISSUE THREAD

**Issue by iwangx** [electron/electron#37218]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

22.0.3

### Expected Behavior

<webview/> can use setWindowOpenHandler normally

### Actual Behavior

```
document.querySelector('webview').setWindowOpenHandler(({ url }) => {
  if (url === 'about:blank') {
    return {
      action: 'allow',
      overrideBrowserWindowOptions: {
        frame: false,
        fullscreenable: false,
        backgroundColor: 'black',
        webPreferences: {
          preload: 'my-child-window-preload-script.js'
        }
      }
    }
  }
  return { action: 'deny' }
})
```
setWindowOpenHandler document.querySelector('webview').setWindowOpenHandler is not a function

**Comment by miniak** [comment]
It was never supposed to

**Comment by miniak** [comment]
Related to #36985
