### ISSUE TITLE
[Bug]: Draggable regions prevent webContents interaction with `customButtonsOnHover` 

### ISSUE THREAD

**Issue by tmtk75** [electron/electron#37210]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6.2

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.2.1

### Expected Behavior

It can be clicked for the button next "toolbar" which is on an area with `-webkit-app-region: drag`.

<img width="737" alt="screenshot" src="https://user-images.githubusercontent.com/425100/217817505-30c7704d-238b-49c1-855d-a771d4e9145a.png">

### Actual Behavior

The button next "toolbar" cannot be clicked.

### Testcase Gist URL

https://gist.github.com/tmtk75/ba7ad4867fd5a98acce001ac376ada07

### Additional Information

I tried to use https://github.com/electron/fiddle, but it said like this when I run.
```
Saving files to temp directory...
Saved files to /var/folders/9j/6d8ql3fs6g99nqkt_lvth3rr0000gn/T/electron-fiddle-94128-5UGo3OdAo0ir
Failed to spawn Fiddle: Unrecognized electron name: "23.0.0"
```

So I created a repository to reproduce.
https://github.com/tmtk75/electron-app-region-drag

**Comment by codebytere** [comment]
Tracked to https://github.com/electron/electron/pull/35603.

**Comment by lxndrdagreat** [comment]
This also seems to be affecting my app, no matter what I set `titleBarStyle` to (I've tried `hidden`, `hiddenInset`, `default` and `customButtonsOnHover`. The app's sidebar has `-webkit-app-region: drag` in the CSS. In my screenshot, I've highlighted the area that I cannot click through:

![image](https://user-images.githubusercontent.com/2231440/219415047-f4b15e57-a7bd-4b3d-b8b5-204367317d7b.png)

If I remove the CSS rule, then (obviously) drag no longer works, but I can click through.

**Comment by davej** [comment]
Gist repro here: https://gist.github.com/b3c3295ec314cc82bcdebdf3de911616

Working in `Electron 22.2.0`, broken in `Electron 23.0.0`.

As noted by @lxndrdagreat, it affects all `titleBarStyle` options on macOS.

**Comment by nornagon** [comment]
This is working as intended. Your button needs `-webkit-app-region: no-drag`. This previously worked _by accident_ because the customButtonsOnHover option created a draggable region at the top of the window regardless of the CSS in the app. This has now been fixed.

Here's an example gist showing that if the button in the draggable region is moved below the "accidental" drag region created by customButtonsOnHover, it is no longer clickable in 22.x: https://gist.github.com/3f493f3c784c898f95e7951f7a73fe0f

And here is a "fixed" example which applies `-webkit-app-region: no-drag` to the toolbar button, making it interactable again: https://gist.github.com/305948c2c071ed619afdeea630b635fe

**Comment by davej** [comment]
@nornagon sounds good! it might be worth mentioning this in breaking changes as I imagine it will require a lot of apps (like mine) to change their code.

**Comment by tmtk75** [comment]
>  by accident 

I got it, thanks for your explanation. I'll fix my code.

**Comment by nornagon** [comment]
@davej fair point, I'll add a note!

**Comment by noobfromph** [comment]
If you want to get if of `webkit-app-region: drag` , you can use  [electron-click-drag-plugin](https://github.com/noobfromph/electron-click-drag-plugin)
```
const { app, BrowserWindow, ipcMain } = require('electron');
const dragAddon = require('electron-click-drag-plugin'); // Loads the native addon

app.whenReady().then(() => {
  const win = new BrowserWindow({
    width: 800,
    height: 800,
    frame: false, // Important: no OS window frame
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false, // only for test/dev
      devTools: true
    },
  });

  win.loadFile('index.html');
  win.webContents.openDevTools();

  ipcMain.on('start-drag', () => {
    try {
      const hwndBuffer = win.getNativeWindowHandle();
      // On Linux, extract the window ID from the buffer (first 4 bytes, little-endian)
      const windowId = process.platform === 'linux'
      ? hwndBuffer.readUInt32LE(0)
      : hwndBuffer;

      dragAddon.startDrag(windowId);
    } catch (error) {
      console.error(error);
    }
  });
});
```
