### ISSUE TITLE
[Bug]:Main process crash when trying to print a pdf

### ISSUE THREAD

**Issue by saoraozhe3hao** [electron/electron#37217]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.4 LTS

### What arch are you using?

x64

### Expected Behavior

window.open(a pdf url) and preview it. Opens print dialog after clicking the printer button.

### Actual Behavior

Main process crashes after clicking the printer button.

**Comment by pushkin-** [comment]
[related](https://github.com/electron/electron/issues/30947)?

**Comment by saoraozhe3hao** [comment]
> 

totally different

**Comment by saoraozhe3hao** [comment]
https://gist.github.com/e849b87bd25bfa474ebd4f84e2fff880

**Comment by thrstn** [comment]
I'm having the exact same issue. I tried using older electron versions but that didn't make any difference. I'm using Ubuntu 22.04.2 LTS
