### ISSUE TITLE
[Bug]: COM Initialization fails in native module

### ISSUE THREAD

**Issue by smooth038** [electron/electron#37212]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version	21H2 OS build	19044.2486 Experience Windows Feature Experience Pack 120.2212.4190.0

### What arch are you using?

x64

### Expected Behavior

I have a native node.js module called `Decklink` written in C++ that I import inside my main Electron process (`main.ts`). The native module is correctly compiled and imported into Electron (no build errors). The package exposes a method called `initialize()` which calls the `CoInitializeEx` method from COM library.

When I run the Electron application and the application calls the package's `initialize()` method from the main process, the code should run without error.

### Actual Behavior

However, when I run the application, the app crashes with the following error:

```
[792:0209/174044.731:ERROR:crashpad_client_win.cc(844)] not connected
```

I can confirm that this error follows exactly the `throw` statement inside the following native package code:

```
   #include <combaseapi.h>
   // ...
   void Decklink::initialize()
   {
      result = CoInitializeEx(NULL, COINIT_MULTITHREADED); // result actually equals -2147417850
      if (FAILED(result))
      {
         throw new std::runtime_error("Initialization of COM failed.\n"); // the error happens here
      }
      // some more code...
   }
```

I know my package code is not at fault because I can require it inside a javascript `test.js` file, call the method from there, and run `node test.js`, and all the code works perfectly in this environment. It seems that the `CoInitializeEx` method only fails when called from the Electron app.

**Comment by miniak** [comment]
HRESULT - 0x80010106 - Cannot change thread mode after it is set. Chromium initializes COM in the main process, you cannot override that in your node module. Nothing to fix on Electron side here.

**Comment by miniak** [comment]
https://source.chromium.org/chromium/chromium/src/+/main:base/win/scoped_com_initializer.h

**Comment by smooth038** [comment]
Thank you very much for the feedback. Now I have a better idea where to go from there.

**Comment by Xutaotaotao** [comment]
> Thank you very much for the feedback. Now I have a better idea where to go from there.

I have the same problem，how do you solve it , can you tell me

**Comment by smooth038** [comment]
Just don't call `CoInitializeEx` at all. It is already initialized by Electron.
