### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Lunar94** [electron/electron#37221]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Expected Behavior

![image](https://user-images.githubusercontent.com/105256980/218093439-52575b47-7479-4bd5-b2bb-2416a545b927.png)
![Screenshot_20230209-121702](https://user-images.githubusercontent.com/105256980/218093635-822a46df-3f32-43cf-96f0-4191f24d38f8.png)

He replied:

![Sans titre](https://user-images.githubusercontent.com/105256980/218093890-a122dbe8-7c38-4e13-a735-e5e399eec313.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/105256980/218093439-52575b47-7479-4bd5-b2bb-2416a545b927.png)
![Screenshot_20230209-121702](https://user-images.githubusercontent.com/105256980/218093635-822a46df-3f32-43cf-96f0-4191f24d38f8.png)

He replied:

![Sans titre](https://user-images.githubusercontent.com/105256980/218093890-a122dbe8-7c38-4e13-a735-e5e399eec313.png)

Just read an image is like 1000 words. Div is in de devtool but NOT in the code. The first person that say to me that is still in the code take a slap :D  

Looks like it's not an electron problem people say this but I say YES it's an electron problem because, I use Electron. Only Electron.

Thanks a lot,

Lunar

**Comment by miniak** [comment]
Electron 17 is now supported
