### ISSUE TITLE
[Bug]: macOS ventura not respecting `openAsHidden` in `setLoginItemSettings`

### ISSUE THREAD

**Issue by kyleshay** [electron/electron#37228]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.2.0

### What operating system are you using?

macOS

### Operating System Version

Darwin C02ZM0YBLVDV 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64

### What arch are you using?

x64

### Expected Behavior

```
// Set launch items
app.setLoginItemSettings({
  openAtLogin: true,
  openAsHidden: true,
});
// Fetch launch items
const {openAsHidden} = app.getLoginItemSettings();

openAsHidden === false // incorrect
```

### Actual Behavior

```
// Set launch items
app.setLoginItemSettings({
  openAtLogin: true,
  openAsHidden: true,
});
// Fetch launch items
const {openAsHidden} = app.getLoginItemSettings();

openAsHidden === true // correct
```

### Additional Information

I'm not 100% certain, but this may be a Ventura only issue.

**Comment by kyleshay** [comment]
Seems to be Ventura only.

Easiest way to repro is just pasting the following into a fiddle in the ready block:
```
app.setLoginItemSettings({
  openAtLogin: true,
  openAsHidden: true,
});

 // openAsHidden is `true` on macOS before Ventura and `false` on Ventura.
console.log(app.getLoginItemSettings());
```

**Comment by kyleshay** [comment]
Seems to be Ventura only.

Easiest way to repro is just pasting the following into a fiddle in the ready block:
```
app.setLoginItemSettings({
  openAtLogin: true,
  openAsHidden: true,
});

// openAsHidden is `true` on macOS before Ventura and `false` on Ventura.
console.log(app.getLoginItemSettings());
```

**Comment by kyleshay** [comment]
Seems to be Ventura only.

Easiest way to repro is just pasting the following into a fiddle in the ready block:
```
app.setLoginItemSettings({
  openAtLogin: true,
  openAsHidden: true,
});

// `openAtLogin` is being set properly
//`openAsHidden` is `true` on macOS before Ventura and `false` on Ventura. 
console.log(app.getLoginItemSettings());

```

**Comment by kyleshay** [comment]
Seems to be Ventura only.

Easiest way to repro is just pasting the following into a fiddle in the ready block:
```
app.setLoginItemSettings({
  openAtLogin: true,
  openAsHidden: true,
});

// `openAtLogin` is being set properly
// `openAsHidden` is `true` on macOS before Ventura and `false` on Ventura. 
console.log(app.getLoginItemSettings());

```

**Comment by codebytere** [comment]
it seems that this is not a failure in `setLoginItemSettings`, but in `getLoginItemSettings` 🤔  

i can repro but it's definitely setting the login item:

<img width="417" alt="Screenshot 2023-02-12 at 9 01 46 PM" src="https://user-images.githubusercontent.com/2036040/218334246-d8a68642-474e-4ed1-82df-0687be7a3c90.png">
<img width="552" alt="Screenshot 2023-02-12 at 9 02 21 PM" src="https://user-images.githubusercontent.com/2036040/218334250-76e69229-f84f-46c4-8b7b-234029a4cd85.png">

**Comment by kyleshay** [comment]
Thanks for taking a look! I'm not sure why our own code base was using `wasOpenedAsHidden` in place of `wasOpenedAtLogin` in the first place (I guess it was to be more semantically correct based?) 

Just using `wasOpenedAtLogin` resolves our own bug, so no major rush (on our end, at least.)

**Comment by kyleshay** [comment]
Thanks for taking a look! I'm not sure why our own code base was using `wasOpenedAsHidden` in place of `wasOpenedAtLogin` in the first place (I guess it was to be more semantically correct?) 

Just using `wasOpenedAtLogin` resolves our own bug, so no major rush (on our end, at least.)

**Comment by codebytere** [comment]
@kyleshay you may also want to take a peek at https://github.com/electron/electron/pull/37244

**Comment by codebytere** [comment]
Closing this issue as a `wontfix` since it's unfortunately an OS limitation on Ventura.
