### ISSUE TITLE
[Bug]: DevTools Application Tab - Request CacheStorage.requestCacheNames failed.

### ISSUE THREAD

**Issue by jorodi** [electron/electron#37249]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.2

### What arch are you using?

x64

### Last Known Working Electron version

22.2.1

### Expected Behavior

There should be no errors when the DevTools Application tab is opened.

### Actual Behavior

Open the DevTools Application tab in v23.0.0 and the following errors are output to terminal in VS Code:

```
[57435:0213/095545.766357:ERROR:CONSOLE(1)] "Request CacheStorage.requestCacheNames failed. {"code":-32602,"message":"Invalid security origin"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[57435:0213/095545.771139:ERROR:CONSOLE(1)] "Request CacheStorage.requestCacheNames failed. {"code":-32602,"message":"Storage key corresponds to invalid origin"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
```

**Comment by codebytere** [comment]
Cannot reproduce this. If you would like for us to continue triage, please add a reliably reproducible code sample illustrating the problem.

**Comment by ShantelWilson** [comment]
I am having this issue as well.

**Comment by mencomao** [comment]
I am having this issue as well.

**Comment by NayamAmarshe** [comment]
Experiencing the same issue. LocalStorage is often empty.

**Comment by payamyek** [comment]
Same error here. Happens on both Windows 11 and MacOS Ventura. 

Currently unable to view any items in cache from the Chrome Dev Tools.

**Comment by javierguzman** [comment]
Anyone has a workaround?

**Comment by codebytere** [comment]
Looks like this is an upstream bug that's since been addressed - it's gone as of this diff: https://github.com/electron/electron/compare/v26.0.0-alpha.5...v26.0.0-alpha.6, likely in https://github.com/electron/electron/commit/cddfdf3ba26e92efa2f2e40490e2bada11e7115a.

**Comment by codebytere** [comment]
@javierguzman so what's happened is that Chromium has already fixed it - we pick up upstream changes automatically through our upgrade process. Older versions of Chromium aren't updated past a certain point, and we match that cadence in our own versioning. 26 has already picked it up, and 25 _might_ pick it up depending on what Chromium decides to do :)

**Comment by javierguzman** [comment]
Understood! Thank you very much for the clarification :)

**Comment by batman0911** [comment]
same error for v25.0.1 when integrate with ckeditor5

**Comment by Dekita** [comment]
same error in 26.2.2 with a fresh "nextron" project.

**Comment by mingmars** [comment]
"electron": "^27.0.0",集成opc-ua包也出现这个问题

**Comment by bradisbell** [comment]
@codebytere Please re-open, this issue is not resolved.

**Comment by lyndonliu89757** [comment]
Please re-open, this issue is not resolved.

**Comment by makeryangcom** [comment]
Please re-open, this issue is not resolved. 

version：31.3.1
