### ISSUE TITLE
[Bug]: window.api returns undefined. 

### ISSUE THREAD

**Issue by ashraf7ali** [electron/electron#37252]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

8.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

under main.js I have the following code 

win = new BrowserWindow({
    width: 800,
    height: 600,
    title: `**************`,
    webPreferences: {
      devTools: true,
      nodeIntegration: false,
      nodeIntegrationInWorker: false,
      nodeIntegrationInSubFrames: false,
      contextIsolation: true,
      enableRemoteModule: false,
      additionalArguments: [`storePath:${app.getPath('userData')}`],
      preload: path.join(__dirname, 'preload.js'),
    },
  });

The preload.js has following function

contextBridge.exposeInMainWorld('api', {
  i18nextElectronBackend: i18nextBackend.preloadBindings(ipcRenderer),
  store: store.preloadBindings(ipcRenderer, fs),
  sequelize: new SequelizeHelper(Sequelize, fs, path, msnodesqlv8).preloadBindings(),
  contextMenu: ContextMenu.preloadBindings(ipcRenderer),
  openUrl,
  checkFile,
  proxyMethods,
});

window.api should return the values defined above.

### Actual Behavior

window.api returns undefied.

**Comment by albu77** [comment]
You are using Electron 8.3 are you sure ContextBridge was already included ?
