### ISSUE TITLE
[Bug]: context menus cannot be displayed when "-webkit-app-region: drag" is enabled

### ISSUE THREAD

**Issue by sprout2000** [electron/electron#37301]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.x

### Expected Behavior

I want to show the context menu in "-webkit-app-region: drag" enabled area, 

### Actual Behavior

 No response and no reaction.

### Testcase Gist URL

https://gist.github.com/3fe6a69c1eba1d7f85caf7572ba77fd2

**Comment by sprout2000** [comment]
Same on Windows 11 22H2.
https://gist.github.com/3591cfe18a50841115038de49c746606

**Comment by nornagon** [comment]
Looks like this is caused by #35603. Opened #37386 to preserve the original behavior.
