### ISSUE TITLE
[Bug]: Display Object has incorrect scaling on INTEL UHD Graphics Adapter

### ISSUE THREAD

**Issue by Antix-Development** [electron/electron#37310]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

`screen.getPrimaryDisplay()` should return 1920x180 resolution and scaling multiplier of 1.

### Actual Behavior

I have an external monitor connected to my laptop. I have checked both displays and their scaling is set too 100% and resolution set to 1920x1080.

Both displays show bounds of 1746x982 and scaling of 1.100000023841858 when calling `screen.getPrimaryDisplay()`.

These values are clearly wrong and I cannot fathom why.

I replicated my project onto another machine in my office and on that machine it works as expected, with correct resolution and scaling provided when calling `screen.getPrimaryDisplay()`.

The laptop which has the issue has an INTEL UHD Graphics Adapter, and the other machine which works has an Nvidia Graphics Adapter.

I've checked the INTEL Graphics Command Center and it reports 1920x1080 resolution and no custom scaling, so I'm really baffled as to why `screen.getPrimaryDisplay()` gives the wrong results

Might this be a bug with INTEL chipsets? Or is there some other "thing" happening?

What else might I be able to try to resolve this issue?

**Comment by codebytere** [comment]
@Antix-Development does this also happen in Chrome/Chromium?

**Comment by Antix-Development** [comment]
> @Antix-Development does this also happen in Chrome/Chromium?

Err, I suppose so since Electron is Chromium based.. there's no way to use another browser with Electron.
