### ISSUE TITLE
[Bug]: html fullscreen not working post v18

### ISSUE THREAD

**Issue by jtvberg** [electron/electron#37311]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6.3

### What arch are you using?

x64

### Last Known Working Electron version

18.3.15

### Expected Behavior

With the `BroswerWindow` set to `fullscreenable: false`, when hitting the fullscreen button on a video (on YouTube, Tubi, etc...) the video should 'fullscreen' to the window. When clicking it again, it should restore.

### Actual Behavior

In some cases (e.g on YouTube) the fullscreen works and `enter-html-full-screen` is emitted. When clicking it again the video does not restore though `leave-html-full-screen` will be emitted.

Any subsequent press of the video's fullscreen button will do nothing and emit nothing.

In other cases (e.g. sometimes on Tubi) neither fullscreen or the restore works at all.

### Testcase Gist URL

https://gist.github.com/jtvberg/8673c71b5dc489a285ac405d6bec8540

### Additional Information

This stopped working as expected somewhere between v18 and v19.
I have also tried v20-v23.
I am referring to the button in actual video host not the fullscreen button on the window.

**Comment by jtvberg** [comment]
After going through versions of 19 on fiddle I found that it reliably works in 19.0.9 and stops working in 19.0.10.
That said, looky [here](https://github.com/electron/electron/commit/438347d891c472c0a630ecf319dbb467338eb2de).

**Comment by codebytere** [comment]
Ah exciting, looks like i goofed here somehow. I'll look into this soon :)

**Comment by codebytere** [comment]
@jtvberg popped up a PR that will fix this!

**Comment by jtvberg** [comment]
@codebytere thank you so much!
