### ISSUE TITLE
[Bug]: On X11 and XWayland when GDK_SCALE=1 is not set in the environment, Electron apps are aways scaled to 100% or less rather than appropriate native scale

### ISSUE THREAD

**Issue by Pointedstick** [electron/electron#37312]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.1.9

### What operating system are you using?

Other Linux

### Operating System Version

Fedora KDE 37

### What arch are you using?

x64

### Expected Behavior

When using screen scaling, Electron apps do not require `GDK_SCALE=1` to be set in the environment to be scaled correctly on X11, or on Wayland when run in XWayland compatibility mode.

### Actual Behavior

When `GDK_SCALE=1` is not set in the environment, and the system is using a scale factor higher than 100%, Electron apps on X11 or Wayland (when run in the default XWayland compatibility mode) are drawn at 100% scale on the highest scale factor screen, and an even lower scale on other screens. For example, on a 200% scale screen, they are drawn at 100% scale, and on a 100% scale screen, they are drawn at 50% scale.

Reproduced with VSCode and Element.

### Additional Information

This issue was noticed after KDE Plasma 5.27 stopped setting `GDK_SCALE=1` in the environment in https://invent.kde.org/plasma/plasma-workspace/-/commit/63de3d6f1716a6924fa5924b5a57af4abaa4460f.

The fact that this breaks X11/XWayland-using Electron apps was unfortunately missed in testing due to local workarounds that masked the issue.

**Comment by eszlari** [comment]
GNOME doesn't set `GDK_SCALE` because it's only meant for debugging purposes, so this must be a KDE specific bug.

**Comment by eszlari** [comment]
Since 5.27 Plasma uses `xsettingsd` for scaling, maybe the bug is there.

**Comment by eszlari** [comment]
Found it:

1. open `/home/user/.config/xsettingsd/xsettingsd.conf`
2. change `Gdk/WindowScalingFactor 1` to `Gdk/WindowScalingFactor 2`
3. restart `xsettingsd` daemon

(tested on Fedora Rawhide with VSCode)

**Comment by easyteacher** [comment]
Fixed by https://invent.kde.org/plasma/kde-gtk-config/-/merge_requests/54

**Comment by Pointedstick** [comment]
Indeed, thanks!

**Comment by juliangrubio** [comment]
The trouble continue when you split screen or when you extend your screen.
