### ISSUE TITLE
[Bug]: Generated checksum for "electron-v23.1.0-darwin-arm64.zip" did not match expected checksum.

### ISSUE THREAD

**Issue by Solo-it** [electron/electron#37329]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1 (21E258)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Generated checksum for "electron-v23.1.0-darwin-arm64.zip" did not match expected checksum.
yarn add --dev electron 
not worked

### Actual Behavior

Generated checksum for "electron-v23.1.0-darwin-arm64.zip" did not match expected checksum.
yarn add --dev electron 
not worked

**Comment by Solo-it** [comment]
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Error: Generated checksum for "electron-v22.3.0-darwin-arm64.zip" did not match expected checksum.
npm ERR!     at Hash.<anonymous> (/Volumes/KINGSTON/Solo-it/electron-puppeteer-demo/node_modules/sumchecker/index.js:133:20)
npm ERR!     at Hash.emit (node:events:513:28)
npm ERR!     at emitReadable_ (node:internal/streams/readable:590:12)
npm ERR!     at onEofChunk (node:internal/streams/readable:568:5)
npm ERR!     at readableAddChunk (node:internal/streams/readable:275:5)
npm ERR!     at Readable.push (node:internal/streams/readable:234:10)
npm ERR!     at node:internal/streams/transform:145:12
npm ERR!     at Hash._flush (node:internal/crypto/hash:96:3)
npm ERR!     at Hash.final [as _final] (node:internal/streams/transform:132:10)
npm ERR!     at callFinal (node:internal/streams/writable:698:12)
npm verb exit 1

**Comment by MarshallOfSound** [comment]
The supplied command works on my (and multiple other) machines.  You more than likely have an http proxy or other similar setup modifying the Electron artifact in flight resulting in an artifact that does not match the checksums we ship with.  You should inspect the downloaded zip file and see how it's been modified and fix it in your network setup

**Comment by Solo-it** [comment]
No problem - I have not proxy
and this not worked

**Comment by Solo-it** [comment]
```
yarn -D add electron
yarn add v1.22.19
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
error /Volumes/KINGSTON/Solo-it/electron-puppeteer-demo/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Volumes/KINGSTON/Solo-it/electron-puppeteer-demo/node_modules/electron
Output:
Error: Generated checksum for "electron-v23.1.0-darwin-arm64.zip" did not match expected checksum.
    at Hash.<anonymous> (/Volumes/KINGSTON/Solo-it/electron-puppeteer-demo/node_modules/sumchecker/index.js:133:20)
    at Hash.emit (node:events:512:28)
    at emitReadable_ (node:internal/streams/readable:590:12)
    at onEofChunk (node:internal/streams/readable:568:5)
    at readableAddChunk (node:internal/streams/readable:275:5)
    at Readable.push (node:internal/streams/readable:234:10)
    at node:internal/streams/transform:145:12
    at Hash._flush (node:internal/crypto/hash:96:3)
    at Hash.final [as _final] (node:internal/streams/transform:132:10)
    at callFinal (node:internal/streams/writable:700:12)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by Solo-it** [comment]
I Find fix:

```
yarn set version stable
yarn
```

And its Work!
