### ISSUE TITLE
[Bug]: not keep the origin text of messagebox on linux

### ISSUE THREAD

**Issue by wangxiuwen** [electron/electron#37323]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.2.3

### What operating system are you using?

Other Linux

### Operating System Version

ubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

do not translate the text (remove the TranslateToStock), just keep it as it is

```
  // Add buttons.
    GtkDialog* dialog = GTK_DIALOG(dialog_);
    if (settings.buttons.size() == 0) {
      gtk_dialog_add_button(dialog, TranslateToStock(0, "OK"), 0);
    } else {
      for (size_t i = 0; i < settings.buttons.size(); ++i) {
        gtk_dialog_add_button(dialog, TranslateToStock(i, settings.buttons[i]),
                              i);
      }
    }
    gtk_dialog_set_default_response(dialog, settings.default_id);
```

```
  const char* TranslateToStock(int id, const std::string& text) {
    const std::string lower = base::ToLowerASCII(text);
    if (lower == "cancel")
      return gtk_util::GetCancelLabel();
    if (lower == "no")
      return gtk_util::GetNoLabel();
    if (lower == "ok")
      return gtk_util::GetOkLabel();
    if (lower == "yes")
      return gtk_util::GetYesLabel();
    return text.c_str();
  }
```

### Actual Behavior

the text was translated when hit the text 'cancel' .etc

**Comment by codebytere** [comment]
We intentionally want to localize these to maintain parity with Chromium and won't be removing that at this time. Should that change upstream or otherwise, we're happy to revisit this.
