### ISSUE TITLE
[Bug]: 'BrowserWindow | null' is not assignable to parameter of type 'PopupOptions

### ISSUE THREAD

**Issue by Konglomneshued** [electron/electron#37339]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^21.3.3

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 37

### What arch are you using?

x64

### Expected Behavior

Following the guide [Electron render process context menus](https://www.electronjs.org/docs/latest/api/menu/#render-process) will work with TypeScript.

### Actual Behavior

Following the guide [Electron render process context menus](https://www.electronjs.org/docs/latest/api/menu/#render-process)

### Guide code
```
// renderer
window.addEventListener('contextmenu', (e) => {
  e.preventDefault()
  ipcRenderer.send('show-context-menu')
})

ipcRenderer.on('context-menu-command', (e, command) => {
  // ...
})

// main
ipcMain.on('show-context-menu', (event) => {
  const template = [
    {
      label: 'Menu Item 1',
      click: () => { event.sender.send('context-menu-command', 'menu-item-1') }
    },
    { type: 'separator' },
    { label: 'Menu Item 2', type: 'checkbox', checked: true }
  ]
  const menu = Menu.buildFromTemplate(template)
  menu.popup(BrowserWindow.fromWebContents(event.sender))
})
```
### Mine (following along)
```
ipcMain.on(Events.showTabContextMenu, (event) => {
   const template = [/* Irrelevant */];

   const menu = Menu.buildFromTemplate(template);

   menu.popup(BrowserWindow.fromWebContents(event.sender));
});
```

![Screenshot from 2023-02-18 15-36-38](https://user-images.githubusercontent.com/94726665/219900598-dd6547f2-2bfb-47ec-ab64-908514572dd6.png)

**Comment by MarshallOfSound** [comment]
This is expected behaviour, the types have no way of knowing that `fromWebContents` is guaranteed to be non-null in that case.  And our examples are JS not TypeScript 🤷 The correct thing to do in this case is either to just fix the TS error on your side, E.g. add `!` or add a null check
