### ISSUE TITLE
[Bug]: Calling event.preventDefault() in the "before-input-event" event will block the subsequent keyup version of the event from firing

### ISSUE THREAD

**Issue by JephDiel** [electron/electron#37336]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise Version 21H2

### What arch are you using?

x64

### Expected Behavior

If you call preventDefault in the listener on "before-input-event" the key events in the webContents will get prevented, but "before-input-event" will still trigger again with the keyup version of the input.

### Actual Behavior

If you call preventDefault() in the listened on "before-input-event" the subsequent keyup version of the same event doesn't trigger.

### Testcase Gist URL

https://gist.github.com/8262c65ea6b0edd68f4e54b0db573c32

**Comment by coderdeadpool** [comment]
hey @JephDiel i think i can fix this bug.
Is anyone working on this issue ?

**Comment by codebytere** [comment]
This is unfortunately [intended behavior](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_widget_host_impl.cc;l=1727-1737;drc=a8addd2e8cfba6253a8ce03f1a0ab1cf4f45d5ae;bpv=1;bpt=1?q=PreHandleKeyboardEvent&sq=package:chromium) on the Chromium level - it's been the case for years and isn't something we control in Electron's own codebase. If that changes, we're happy to re-open this!
