### ISSUE TITLE
[Bug]: electron23 not resolve 'fs'

### ISSUE THREAD

**Issue by labike** [electron/electron#37343]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1

### What operating system are you using?

macOS

### Operating System Version

13.2

### What arch are you using?

x64

### Expected Behavior

in electron `const fs = require('fs')`

### Actual Behavior

<img width="1019" alt="截屏2023-02-19 15 09 41" src="https://user-images.githubusercontent.com/15871933/219934789-d93a85b7-3f58-4fbb-90f6-40980ae4d605.png">

**Comment by MarshallOfSound** [comment]
This looks like a bug in whatever bundler you are using, maybe vite? Hard to tell from the error log.  I'd suggest configuring that correctly or debugging follow their guides.  This error is not coming from Electron itself.
