### ISSUE TITLE
[Feature Request]: Minimal build

### ISSUE THREAD

**Issue by Generalize** [electron/electron#37347]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

NodeJs already provides enough power.  So you can remove the functions in BrowserWindow that are not related to the ui display just keep the html/css rendering and javascript DOM api to reduce the build size.

### Proposed Solution

  See description

### Alternatives Considered

  See description

**Comment by MarshallOfSound** [comment]
Picking and choosing which parts of V8 / blink to include is neither technically viable nor desired.
