### ISSUE TITLE
[Bug]: Electron Latest version  DownloadItem.getFileName returns wrong filename,  when use Chinese encode

### ISSUE THREAD

**Issue by biology-w** [electron/electron#37354]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows10

### What arch are you using?

x64

### Last Known Working Electron version

9.4.4

### Expected Behavior

When obtaining filename attribute in Content-Disposition in electron, i use 
the code `attachment;filename=${encodeURIComponent("测试-英语-正确-1.pdf",)}; filename*=UTF-8''${encodeURIComponent("测试-英语-正确-2.pdf")}` expect filename to be normal when encoding in Chinese;

expect Chinese  As follows words correct.

![image](https://user-images.githubusercontent.com/25600705/220145655-d751660d-82d3-4391-b31a-6825673e682d.png)

### Actual Behavior

But Actual Chinese characters encounter garbled characters when obtaining the filename attribute in Content-Disposition in electron. 

electron responseHeader: Content-Disposition filename is error
![image](https://user-images.githubusercontent.com/25600705/220147465-fea7cc09-ed99-484c-8b0a-46a9b846a6a9.png)

### Additional Information

That is my electron code 

![image](https://user-images.githubusercontent.com/25600705/220147852-29e72c20-7de9-4456-90ab-cddf5b591a01.png)

That is my server code 

![image](https://user-images.githubusercontent.com/25600705/220148061-de01d7b6-a07f-46b9-9694-d8c07dcd4dc6.png)

**Comment by Prinzhorn** [comment]
I don't think `encodeURIComponent` alone is correct, see this package https://github.com/jshttp/content-disposition (https://github.com/jshttp/content-disposition/blob/73bf21e7c3f55f754932844584061027767289f4/index.js#L436-L444), it has sources to specs listed in the README

**Comment by biology-w** [comment]
> I don't think `encodeURIComponent` alone is correct, see this package https://github.com/jshttp/content-disposition (https://github.com/jshttp/content-disposition/blob/73bf21e7c3f55f754932844584061027767289f4/index.js#L436-L444), it has sources to specs listed in the README
> 
> Does your code work correctly in Chromium? If so, then ignore what I said above.

yes, when use in chrome browser not use electron , everything is ok!
![image](https://user-images.githubusercontent.com/25600705/220160541-ff45abbb-ba62-4f79-aa89-b88d3ef9f9af.png)

**Comment by biology-w** [comment]
Surprised!  when i use doubule `encodeURIComponent(encodeURIComponent('')) ` the Chinese decode is ok!!!

That is my server code 

![image](https://user-images.githubusercontent.com/25600705/220162635-941b714c-8dd3-486f-bc3e-57a5f649f30b.png)

Correct!
![image](https://user-images.githubusercontent.com/25600705/220163700-156fd510-b697-4ca7-888e-61fa77cbb44f.png)



    console.log(
      'filename',
      filename === encodeURIComponent('测试-英语-正确-1.pdf')
    );
    console.log(
      'filename',
      filename === encodeURIComponent('测试-英语-正确-2.pdf')
    );
    console.log('filename', filename === '测试-英语-正确-2.pdf');

content-disposition: attachment; filename="%E6%B5%8B%E8%AF%95-%E8%8B%B1%E8%AF%AD-%E6%AD%A3%E7%A1%AE-2.pdf"

**Comment by biology-w** [comment]
> I don't think `encodeURIComponent` alone is correct, see this package https://github.com/jshttp/content-disposition (https://github.com/jshttp/content-disposition/blob/73bf21e7c3f55f754932844584061027767289f4/index.js#L436-L444), it has sources to specs listed in the README
> 
> Does your code work correctly in Chromium? If so, then ignore what I said above.

I use that code in my project test,
![image](https://user-images.githubusercontent.com/25600705/220165568-b2ade171-ccc9-4741-972b-6d412404e9f5.png)

but the result also is error.

![image](https://user-images.githubusercontent.com/25600705/220165365-4d02aae6-a39f-4572-9a44-46626bae6f6a.png)

**Comment by codebytere** [comment]
> Surprised! when i use doubule encodeURIComponent(encodeURIComponent(''))  the Chinese decode is ok!!!

So you were able to make it work in Electron?

**Comment by biology-w** [comment]
> > Surprised! when i use doubule encodeURIComponent(encodeURIComponent(''))  the Chinese decode is ok!!!
> 
> So you were able to make it work in Electron?

We found that version 11 and previous versions do not have the problem of Chinese garbled code.
After version 12, there is a problem of garbled Chinese.

[fix: incorrect Content-Disposition encoding](https://github.com/electron/electron/commit/84a42a050e7d45225e69df5bd2d2bf9f1037ea41) This PR for version 12 involves Content-Disposition modification, I don't know if it is related to this code.

**Comment by biology-w** [comment]
I'm very sorry, I found the problem in my code.   
Chinese garbled characters caused by this re-code  ``` responseHeaders: d.responseHeaders```

![image](https://user-images.githubusercontent.com/25600705/221199846-0044cf18-f423-4b83-a9c0-8c282178a8a1.png)

**Comment by codebytere** [comment]
@biology-w can this be closed then? Or do you still think this is a problem in Electron itself?

**Comment by codebytere** [comment]
Closing as there was no response to the above.

**Comment by xql799** [comment]
> I'm very sorry, I found the problem in my code. Chinese garbled characters caused by this re-code ` responseHeaders: d.responseHeaders`
> 
> ![image](https://user-images.githubusercontent.com/25600705/221199846-0044cf18-f423-4b83-a9c0-8c282178a8a1.png)

Hello, I have discovered the cause of this issue. Is there any way to solve it? I have encountered the same problem
