### ISSUE TITLE
[Bug]: `setWindowOpenHandler` never called with disposition `save-to-disk`

### ISSUE THREAD

**Issue by Prinzhorn** [electron/electron#37350]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

Linux alex-NUC11PAHi7 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

When using `setWindowOpenHandler` I expect the callback to be called with `disposition: 'save-to-disk'` when clicking a `a[download]` link or when serving an `application/octet-stream` content-type.

### Actual Behavior

In both cases a "Save as..." dialog is opened. But the `setWindowOpenHandler` is not called, hence I cannot `deny`.

### Testcase Gist URL

https://gist.github.com/f41534b9a524f54abb8cc1ebeb4f080d

### Additional Information

`a[download]`: https://gist.github.com/f41534b9a524f54abb8cc1ebeb4f080d
`application/octet-stream`: https://gist.github.com/dd09b4f18556c1c775bf1b97bdaed76d

This is a more generalized version of https://github.com/electron/electron/issues/32165 showing that there's a bigger underlying issue. So there are at least three cases where you can trigger a "Save as..." dialog that cannot be prevented. I feel like `disposition: 'save-to-disk'` is not properly wired up.

**Comment by Prinzhorn** [comment]
Fourth way: "Download" button in native media controls https://gist.github.com/5b4dd6ec0f2f630ee838105a1e340285

![image](https://user-images.githubusercontent.com/679144/220096752-76b355d1-b4a8-48a6-9a05-7b3b1e192e8c.png)

**Comment by codebytere** [comment]
@Prinzhorn it looks, unfortunately, like this is a Chromium-level issue - they expose this as a potential disposition but don't really [do anything with it](https://source.chromium.org/search?q=%22SAVE_TO_DISK%22%20-f:out%20lang:cpp&sq=package:chromium&start=11), or invoke it in the cases you specify above. For example, when `OpenNewUrlFromTab` is invoked with that disposition [nothing happens](https://source.chromium.org/chromium/chromium/src/+/main:headless/lib/browser/headless_web_contents_impl.cc;l=164-176?q=%22SAVE_TO_DISK%22%20-f:out%20lang:cpp&sq=package:chromium&start=11). You might be better served opening a bug upstream to ask about their plans for better supporting it.

**Comment by Prinzhorn** [comment]
@codebytere turns out the `will-download` event is the right thing to use here (thanks to @MarshallOfSound for pointing that out).

```js
mainWindow.webContents.session.on('will-download', (e) => {
  e.preventDefault();
});
```

Now could you clarify if we should remove `save-to-disk` from the docs? Or how does this relate to `will-download'`? Why can Electron trigger `will-download'` if Chromium doesn't do anything with `save-to-disk`? I'm just curious how this fits together and if there is a mismatch between the two concepts?

**Comment by nornagon** [comment]
Yeah, seems like it should be removed from the docs. I'm not sure there's any path for save-to-disk to arrive in setWindowOpenHandler. In fact, I think this enum value might no longer be used in Chrome, I couldn't find anything that actually detected that value and did anything with it.
