### ISSUE TITLE
[Feature Request]: Add event to WebContents to react to changes of `isCurrentlyAudible`

### ISSUE THREAD

**Issue by Prinzhorn** [electron/electron#37352]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Chromium only shows the button to mute/unmute a tab when it actually has media playing. Once the media has paused, the button will eventually fade away. Electron does not offer a way to react to this change.

### Proposed Solution

Either a single change event like `audible-change` or two symmetrical events along the lines of `did-become-audible` and `stopped-being-audible`.

### Alternatives Considered

Poll `isCurrentlyAudible`

**Comment by codebytere** [comment]
I think this is reasonable - I can try to open a PR for this.
