### ISSUE TITLE
[Bug]: No way to close a browserView

### ISSUE THREAD

**Issue by t57ser** [electron/electron#37378]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

Windows

### Operating System Version

10.0.19042

### What arch are you using?

x64

### Expected Behavior

There should be a way to close a browserView. 

### Actual Behavior

Neither window.close() nor webContents.close() has any effect.
You can play a video on youtube and hear the sound continue after .removeBrowserView is called. So that does not change the behavior either. Also calling window.close() in the devtools has no effect.
```
const electron = require( "electron" )

electron.app.whenReady().then(()=>{
	let main = new electron.BrowserWindow({
		"height" : 700,
		"width" : 800,
		show: true,
	});

	let view = new electron.BrowserView({});
	view.webContents.loadURL("https://www.youtube.com");
	main.addBrowserView(view);
	view.setBounds({x: 0, y: 0, width: 800, height: 700})
	view.webContents.openDevTools({ mode: "detach" });

	setTimeout(() => {
		console.log("calling webContents.close()")
		//main.removeBrowserView(view);
		//view.webContents.close();
		view.webContents.executeJavaScript("window.close()");
	}, 5000);
})

```

**Comment by dsanders11** [comment]
Can confirm that YouTube video continues to play after `view.webContents.close()`. It looks like this regressed in v23.1.0, likely due to https://github.com/electron/electron/pull/37205.

cc @codebytere
