### ISSUE TITLE
[Bug]: Windows transparency fails after the taskbar is hidden

### ISSUE THREAD

**Issue by HAPENLY** [electron/electron#37379]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

windows 10 19044

### What arch are you using?

x64

### Last Known Working Electron version

12.0.2

### Expected Behavior

Windows transparency fails after the taskbar is hidden

### Actual Behavior

The project is divided into parent-child Windows. The child window is set transparent: true. When the taskbar is not automatically hidden, the parent window can be seen through the child window. But when the taskbar is automatically hidden, the child window turns black and the contents of the parent window cannot be seen.

### Testcase Gist URL

none

### Additional Information

Subwindows load HTML pages that are also background-color: transparent but not transparent. The current test shows that the parent window content is visible when the child window does not load HTML, and the parent window content is not visible when the child window loads HTML.
transparent does not hide background-color: transparent in the system taskbar.

**Comment by codebytere** [comment]
Electron v12 is not supported and has not been for some time. Please check with a [supported version](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) - will we not be able to triage this until it is confirmed for a supported version.
