### ISSUE TITLE
[Bug]: It threw an exception when the paramter type is blob through contextBridge

### ISSUE THREAD

**Issue by 136759790** [electron/electron#37377]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I want to get the data in main process though contextBridge,but it threw an exception.
I find the doc described that **Because parameters, errors and return values are copied when they are sent over the bridge, there are only certain types that can be used. At a high level, if the type you want to use can be serialized and deserialized into the same object it will work. A table of type support has been included below for completeness:**  [click here](https://www.electronjs.org/docs/latest/api/context-bridge#parameter--error--return-type-support)

### Actual Behavior

It threw an exception

### Testcase Gist URL

https://gist.github.com/753924fd235cb1d26ffd229e8ae53acc

**Comment by 136759790** [comment]
Error log 
`Uncaught (in promise) Error: An object could not be cloned`

**Comment by codebytere** [comment]
This is not an issue with `contextBridge` - it is that you are trying to sent the blob with `ipcRenderer`, which is not supported.
