### ISSUE TITLE
webcam doesn't work on tinker board 2s

### ISSUE THREAD

**Issue by Stevenragy** [electron/electron#37382]
I built my video call electron app on V19.1 the web cam works fine on mac os, windows and Linux but on my tinker board 2s os based on debian it doesn't work.
Actually it works and show the camera view for less than a second. 

here are the main.js code

```
const { app, BrowserWindow } = require("electron");

const createWindow = async () => {
  const window = new BrowserWindow({
    // fullscreen: true,
    // fullscreenable: true,
    closable: false,
    center: true,
    alwaysOnTop: true,
    simpleFullscreen: true,
    acceptFirstMouse: false,
    skipTaskbar: true,
    frame: true,
    autoHideMenuBar: true,
    minimizable: false,
    minWidth: 1600,
    minHeight: 900,
  });

  window.once("ready-to-show", () => {
    window.show();
  });

  // ignore mouse interaction
  // window.setIgnoreMouseEvents(true);
  window.loadURL("https://webcamtests.com/");
  // open dev tools
  //   window.webContents.openDevTools();
};

app.on("ready", () => {
  createWindow();
});

app.on("activate", () => {
  if (!BrowserWindow.getAllWindows().length) createWindow();
});

app.on("window-all-closed", () => {
  app.quit();
});
```

**Comment by Stevenragy** [comment]
and also when i run the electron app it returns this error on the console

```
viz_main_impl.cc(186) Exiting GPU process due to errors during initialization
ERROR:command_buffer_proxy_impl.cc(128) ContextResult:kTransientFailure: Failed to send GpuControl.CreateCommandBuffer
```

**Comment by Stevenragy** [comment]
@codebytere

**Comment by codebytere** [comment]
@Stevenragy please fill out the template properly or we cannot continue triage. This issue will otherwise be closed in 10 days.

**Comment by Stevenragy** [comment]
@codebytere 
I'm trying to access localstrem using a web cam on react.js and when the app runs on tinker board 2s based on debian v10 
the camera give a snap shot with the camera view then it gives me a black screen 

here are the localstream access code 
```    const getVideo = () => {
        navigator.mediaDevices.getUserMedia({ audio: true, video: true }).then((mediaStream) => {
            let video = videoRef.current;
            if (video) {
                video.srcObject = mediaStream;
                video.onloadedmetadata = function (e) {
                    video?.play();
                };
            }
        });
    };
```
I'm asking if I should configure something related to the camera access on the main file

**Comment by codebytere** [comment]
Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. if this turns out to be a bug in Electron itself and not a question about how to make something work, we can revisit and open this.
