### ISSUE TITLE
[Bug]: no scrollbar is showing in browserview and popup is out of frame. 

### ISSUE THREAD

**Issue by arnabTeknikforce** [electron/electron#37387]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

windows11

### What arch are you using?

x64

### Expected Behavior

popup should be centered and the scrollbar should be visible.

### Actual Behavior

![Screenshot_20230223_140626](https://user-images.githubusercontent.com/100270808/220858384-1910f74f-387e-485c-a406-8f997d5870bb.png)

**Comment by sumitshinde-84** [comment]
hey , i am interested to fix this issue , can you please assign me this issue ?
