### ISSUE TITLE
[Bug]: loadUrl returns empty string

### ISSUE THREAD

**Issue by Imperat** [electron/electron#37390]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.4

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Look at this piece of source code:

```
  mainWindow.loadURL('http://github.com');
  console.log(`url: '${mainWindow.webContents.getURL()}'`);
})
```

I expect that output would be `url: 'http://github.com'`.

### Actual Behavior

Empty string

### Testcase Gist URL

https://gist.github.com/6a60a2e23e470756b2396825fea36b7b

### Additional Information

I see in [the code snippet](https://www.electronjs.org/docs/latest/api/web-contents#contentsgeturl) described in docs

```
const { BrowserWindow } = require('electron')
const win = new BrowserWindow({ width: 800, height: 600 })
win.loadURL('http://github.com').then(() => {
  const currentURL = win.webContents.getURL()
  console.log(currentURL)
})
```

the author waits for the promise returned by `loadURL` to be resolved. Do you know if this required behavior? Can we document it or fix returning an empty string, please? :)

**Comment by codebytere** [comment]
@Imperat `win.loadURL` is an asynchronous function (as is documented), so this behavior is working as intended. You would, by the nature of asynchronous functions, be required to wait until the promise has settled in order to query the newly loaded url.
