### ISSUE TITLE
[Bug]: WebSocket and Worker messaging latency lag during mouseEvents

### ISSUE THREAD

**Issue by KraXen72** [electron/electron#37391]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

>10.4.7 (present in any version above 10.4.7)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home, 21H2

### What arch are you using?

x64

### Last Known Working Electron version

10.4.7

### Expected Behavior

messaging using webSocket and workers would register with low latency, while the mouseevents are occuring.

### Actual Behavior

currently, mouseEvents like dragging, holding, moving, clicking, in rapid succession block worker/websocket communication almost fully. repro: https://github.com/v5p/mouse-freeze-bug (i am not the author of the repro)
tested with latest electron version, v23.1.1

### Testcase Gist URL

https://github.com/v5p/mouse-freeze-bug

### Additional Information

the issue is reproducible in this repository: https://github.com/v5p/mouse-freeze-bug
and also in the online game krunker.io (shots fired don't get registered until mouse is let go)

**Comment by Prinzhorn** [comment]
The link you've posted says this is a Chromium bug, correct? So there's nothing Electron can do other than wait for a fixed Chromium they can pull in.

**Comment by KraXen72** [comment]
i've failed to reproduce it in latest chromium, however that is also due to the reason it's almost impossible to disable the frame rate limit in newer chrome versions. i will report this in the chromium repo instead

**Comment by KraXen72** [comment]
see: https://bugs.chromium.org/p/chromium/issues/detail?id=1162922&q=mouse%20freeze%20bug&can=2 for reference. this issue can be closed for now, until chromium devs fix that.
