### ISSUE TITLE
[Bug]: nativeImage.getSize, and nativeImage.toPNG ignore scaleFactor

### ISSUE THREAD

**Issue by dtaskoff** [electron/electron#37401]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.0.1

### What arch are you using?

x64

### Expected Behavior

I'd expect the following code to print at least two different sizes:
```javascript
window.capturePage(pageRect).then(image => {
  console.log(image.getSize())
  console.log(image.getSize(2.0))
  console.log(image.getSize(3.0))
})
```

### Actual Behavior

It prints the same size.

### Additional Information

Saving the image with `fs.writeFile(path, image.toPNG({ scaleFactor: ... }))` has the same incorrect behaviour.

**Comment by codebytere** [comment]
This is working as documented:

> If `scaleFactor` is passed, this will return the size corresponding to the image representation most closely matching the passed value.

 If there is only one representational size in the `nativeImage` instance, only one size will ever be returned.

**Comment by Rabbitzzc** [comment]
me too
![image](https://github.com/electron/electron/assets/26913511/fa2199b0-1f65-4087-9d0e-3689a38da822)

**Comment by Rabbitzzc** [comment]
It needs to use `resize` method to change the image size before using 'toPng'
```ts
const resizeImage = shotImage.resize({ quality: 'good', width: rect.width, height: rect.height });
```
