### ISSUE TITLE
[Bug]: Frameless window is not draggable when running MAS build

### ISSUE THREAD

**Issue by streamer45** [electron/electron#37414]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.3.1

### Expected Behavior

Window should be draggable.

### Actual Behavior

Window is not draggable.

### Testcase Gist URL

https://gist.github.com/1387d3e19cbf2717cd21bbf3befaf159

### Additional Information

To be noted, dragging works as expected on standard Electron builds but consistently fails when using Mac Apple Store builds (>= v23).

@nornagon I understand you've been working on some related issues recently, please let me know if this is a known/fixed issue and I'll close this one, thanks!

**Comment by georgexu99** [comment]
Thanks for logging this issue!

I tried reproducing it (albeit with ventura vs big sur) and couldn't reproduce the behaviour, using the test case in the description. Could you let me know if it's still reproducible on your end, and if so, attach a video? Thanks!!

**Comment by streamer45** [comment]
@georgexu99 Thanks for having a look. I had at least one report from a more recent macOS version but need to confirm whether that was Monterey or Ventura. 

Also it actually seems like the window is draggable from very specific regions (top right and left corners) but clearly not working consistently as I'd expect.

https://user-images.githubusercontent.com/1832946/221997197-8595b899-2d0b-4293-96cb-9ea353f07447.mp4

**Comment by nornagon** [comment]
You might be running up against this: https://www.electronjs.org/docs/latest/breaking-changes#behavior-changed-draggable-regions-on-macos

**Comment by streamer45** [comment]
I though about that originally but if that was the case I'd expect it to work consistently between builds of the same Electron version but that's not the case. Also the reproducer is a dead simple draggable body element with nothing else in the page, no overlap or anything of the kind. 

Honestly I don't even know what's the actual difference between a MAS build and a standard MacOS build for the same version and architecture but from what I could test that's making a big difference because it's working just fine using any other build type.

**Comment by nornagon** [comment]
Yeah, I can repro this on v23.1.1-mas-arm64 on macOS Monterey 12.6.3.

**Comment by nornagon** [comment]
Looks like it's this patch causing the issue: https://github.com/electron/electron/blob/main/patches/chromium/mas_disable_custom_window_frame.patch
