### ISSUE TITLE
[Bug]: Uncaught ReferenceError: versions is not defined     at renderer.js:2:55

### ISSUE THREAD

**Issue by student-ice** [electron/electron#37416]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

Other Linux

### Operating System Version

deepin v23 alpha2

### What arch are you using?

x64

### Expected Behavior

Version information can be displayed normally
![图片](https://user-images.githubusercontent.com/59855569/221413626-c7892886-1ce2-4a8e-963d-d711d27722f1.png)

### Actual Behavior

Unable to display 
point out Uncaught ReferenceError: versions is not defined
    at renderer.js:2:55
![图片](https://user-images.githubusercontent.com/59855569/221413959-89f1c3d1-ed12-4058-ac9f-6ccc224cf161.png)

![图片](https://user-images.githubusercontent.com/59855569/221413918-488fd64e-f0cd-46b6-8270-d58538e04b18.png)

![图片](https://user-images.githubusercontent.com/59855569/221413839-3db02c47-9e95-47d8-9269-211b615b4dc3.png)

**Comment by VerteDinde** [comment]
Hey @student-ice, is this happening to you with the default Fiddle gist? I can't repro this on Ubuntu 22.04 and 20.04, can you provide more info about the distro you're running this in?

**Comment by student-ice** [comment]
> Hey @student-ice, is this happening to you with the default Fiddle gist? I can't repro this on Ubuntu 22.04 and 20.04, can you provide more info about the distro you're running this in?
The system I am using is  https://cdimage.deepin.com/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso

**Comment by codebytere** [comment]
@student-ice this means you're not using the preload script correctly. See [electron-quick-start](https://github.com/electron/electron-quick-start) for reference on what's needed!
