### ISSUE TITLE
Window menu folders not opening after resizing window

### ISSUE THREAD

**Issue by Mike-Wood** [electron/electron#37415]
On Ubuntu, opening a menu folder works perfectly until I resize the window, then menu folder can't be opened anymore.

Here's a GIF of what's happening:
![Menu bug](https://user-images.githubusercontent.com/11504707/221389530-2409becb-6718-49f5-a53c-86f4ebcbdffb.gif)

Try it out using this Electron Fiddle: https://gist.github.com/0fc155a8e5f06957e576780c875f95ff

I can't remember if this was an issue in the past, but all my Electron based apps (E.g., Slack) have the same problem.

Electron version: v23.1.1
OS: Ubuntu 20.04.5 LTS

Thanks.

**Comment by Prinzhorn** [comment]
https://github.com/electron/electron/search?q=ubuntu+menu+resize&type=issues
https://github.com/electron/electron/issues/35724

**Comment by VerteDinde** [comment]
Thanks for the report! Going to close this as a duplicate and mark that this is still happening in E23
