### ISSUE TITLE
[Feature Request]: Generate a compile-able Electron tarball release 

### ISSUE THREAD

**Issue by caneraltinbasak** [electron/electron#37422]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently Electron release tarballs only includes electron source itself. It doesn't ship the dependencies to go with. It is not easily possible to download the rest of the dependecies from source tarball. Build system heavily relies on gclient and source being checked out from git repo. We are using yocto for building Electron, there isn't a official workflow for using gclient with yocto. I would like to use Electron tarball if possible.

### Proposed Solution

Electron can use export_tarball.py from https://chromium.googlesource.com/chromium/tools/build, and export entire source tarball including the dependencies, just like Chromium does with every release(ex:https://commondatastorage.googleapis.com/chromium-browser-official/chromium-110.0.5481.77.tar.xz)

Downsides are:

- When I export entire source tree with export_tarball.py, the tarball size substantially(It is approximately 3gb) I am not sure what is the best method to store this.
- There is a script/lib/get-version.js call which uses  git tags to determine the current version. This should be updated to use a different method. I've changed this to use a environment variable which gets passed when running gn, however I am open to suggestions
-  BUILD.gn script/lib/get-version.js depends on .git/packed-refs, and .git/HEAD. These dependencies should be removed

I can work on this and improve the methodology.
print-version.py and get-version.js are related to each other. If you propose a better method for retrieving the version which doesn't require git access, I can implement that solution.

### Alternatives Considered

If build-able tarball exports is not important for the project, I can work on gclient fetcher for bitbake(yocto).

**Comment by brjsp** [comment]
Take a look at the <a href=https://gist.github.com/brjsp/c721e0392fc7c4a66d1e53fd23a1f0a6>download script we use at openSUSE</a>. We patch gclient so that it does not download the entire history, only the needed commits.

The entire tarball for electron 22.3.0 is 565 MB after compressing with zstd. Note that this excludes some tests, non-Linux dependencies, and most vendored libraries that we use the system versions of.

**Comment by caneraltinbasak** [comment]
@brjsp Thank you for the download script. 
@MarshallOfSound I am closing the issue as "not planned".
