### ISSUE TITLE
[Bug]: Still meet issue CORS-RFC1918 on Electron 19.0.0. Can I set [chrome://flags/#enable-experimental-web-platform-features = disable] in Electron?

### ISSUE THREAD

**Issue by liuchangling** [electron/electron#37435]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

1. Set public domain in hosts file to a private IP like 192.168.*.*
2. Request from public domain
3. Expected get data success.

### Actual Behavior

Seeing CORS-RFC1918 issue: 
* has been blocked by CORS policy: Request had no target IP address space, yet the resource is in address space private

### Additional Information

Same issue as https://github.com/electron/electron/issues/33133#issuecomment-1331239971

Still seeing this issue on electron 19.0.0. Tried all appendSwitch sugesstions

`app.commandLine.appendSwitch('disable-site-isolation-trials')
app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors')
app.commandLine.appendSwitch('disable-features', 'BlockInsecurePrivateNetworkRequests')
`

I find Chrome 102 meet same issue when [chrome://flags/#enable-experimental-web-platform-features = enable].
Solve this issue when [chrome://flags/#enable-experimental-web-platform-features = disable]

**Can I set [chrome://flags/#enable-experimental-web-platform-features = disable] in Electron?**

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
