### ISSUE TITLE
[Feature Request]: support limiting the number of renderer processes

### ISSUE THREAD

**Issue by ylqhust** [electron/electron#37437]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.11

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2 19045.2486

### What arch are you using?

x64

### Expected Behavior

after set this switch to value 1, the renderer process count should always be 1

### Actual Behavior

 the renderer process count still increase when i create a new BrowserWindow

### Additional Information

i import app from electron and set renderer-process-limit to 1
```
app.commandLine.appendSwitch("renderer-process-limit", "1");
```
it doesn't work.

but if i launch electron from command line and special cmd argument "--renderer-process-limit=1", it's work
so i am sure the feature is supported by chrome

anyone know how to solve it ?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
That flag is read by Chromium's internals before Electron ever runs JavaScript: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/browser_main_loop.cc;l=618-623;drc=c65a603f7748a9f09e8740ab3f25a8ae00077a03

Theoretically, we could add a hook for `RenderProcessHost::SetMaxRendererProcessCount`. Can you say more about your use case?

**Comment by ylqhust** [comment]
> That flag is read by Chromium's internals before Electron ever runs JavaScript: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/browser_main_loop.cc;l=618-623;drc=c65a603f7748a9f09e8740ab3f25a8ae00077a03
> 
> Theoretically, we could add a hook for setting this (https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/content_browser_client.cc;l=353;drc=c65a603f7748a9f09e8740ab3f25a8ae00077a03). Can you say more about your use case?

i just put this line in my main.js head
```
app.commandLine.appendSwitch("renderer-process-limit", "1");
```
after that i create two BrowserWindow and the are two renderer process
