### ISSUE TITLE
[Bug]: navigator.bluetooth.requestDevice  always return device which name is null

### ISSUE THREAD

**Issue by 717009629** [electron/electron#37445]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23

### What operating system are you using?

Windows

### Operating System Version

win11

### What arch are you using?

x64

### Expected Behavior

navigator.bluetooth.requestDevice  return device and name is not null

### Actual Behavior

navigator.bluetooth.requestDevice  return device and name is null

### Testcase Gist URL

https://gist.github.com/a5d16943212179f7c033d5bd70531404

### Additional Information

![image](https://user-images.githubusercontent.com/16289643/222024231-fc453b34-4768-48cb-95be-a84b4ba06446.png)

I click test button 
First time ,in fiddle console the name is none  and in app console the name is null.
After the second time, in fiddle console the name is Sinocare but in app console the name  is  still null.

**Comment by codebytere** [comment]
cc @jkleinsc - may be up your alley!

**Comment by 717009629** [comment]
> cc @jkleinsc - may be up your alley! @717009629 has this ever worked previously, in an older version of Electron?
some times return  device with name ，sometimes return device with null name

**Comment by jkleinsc** [comment]
@717009629 I just tested this on Windows with Electron 23 and it works correctly for me.  I did notice something that might be the problem on your end.  I the documentation for [select-bluetooth-device](https://www.electronjs.org/docs/latest/api/web-contents#event-select-bluetooth-device), it says that:
>If event.preventDefault is not called, first available device will be selected.
So which device gets selected is random.

If you are trying to connect to a device called Sinocare, can you try the following to see if it works?
```js
  mainWindow.webContents.on('select-bluetooth-device', (event, deviceList, callback) => {
    console.log(deviceList)
    event.preventDefault()
    const result = deviceList.find((device) => {
      return device.deviceName === 'Sinocare'
    })
    if (result) {
      callback(result.deviceId)
    }
  })
```

**Comment by 717009629** [comment]
> ```js
>  console.log(deviceList)
>     event.preventDefault()
>     const result = deviceList.find((device) => {
>       return device.deviceName === 'Sinocare'
>     })
>     if (result) {
>       callback(result.deviceId)
>     }
> ```

thank you，it worked for me.

![image](https://user-images.githubusercontent.com/16289643/225171949-d9f3b3ca-6301-464b-94b0-fa3b64ffca64.png)
