### ISSUE TITLE
[Feature Request]: Add parameter to session.downloadURL to associate with will-download event

### ISSUE THREAD

**Issue by asd281533890** [electron/electron#37446]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am developing a file download manager. When the downloaded file is deleted, it can be downloaded again. I need to implement this: the re-downloaded file reuses the previous save path and no `saveDialog` will pop up. When the user clicks the re-download button, the rendering process calls:
```
ipcRenderer.send ('re-download', { url: 'http://download/url', reusedSavePath: 'C:\\a.jpg' })
```
In the main process:
```
session.defaultSession.on('will-download', (event, downloadItem, webContents) => {
  // How can I accurately get reusedSavePath here?
})

ipcMain.on('re-download', (event, param) => {
  const { url, reusedSavePath } = param
  session.defaultSession.downloadURL(url) // Asynchronously trigger the will-download event.
})
```

I have tried to listen the `will-download` event once before calling the downloadURL each time, but because the will-download is triggered asynchronously (depends on the response time of the server), the execution order of the event callback cannot be guaranteed.
```
ipcMain.on('re-download', (event, param) => {
  const { url, reusedSavePath } = param
  session.defaultSession.once('will-download', (event, downloadItem, webContents) => {
    downloadItem.setSavePath(reusedSavePath)
  })
  session.defaultSession.downloadURL(url)
})
```

### Proposed Solution

Can you add a parameter to `session.downloadURL`, such as
```
session.downloadURL(theURL, extraParam)
```
Then the callback of the `will-download` event can get this parameter.
```
session.defaultSession.on('will-download', (event, downloadItem, webContents, extraParam) => {
  // Here you can obtain the extraParam parameter
})
```

### Alternatives Considered

Trigger the download with a new webContents.
```
ipcMain.on('re-download', (event, param) => {
  const { url, reusedSavePath } = param
  const browserView = new BrowserView()
  session.defaultSession.on('will-download', (event, downloadItem, webContents) => {
    if (webContents.id === browserView.webContents.id) {
      downloadItem.setSavePath(reusedSavePath)
    }
  })
  browserView.webContents.downloadURL(url)
})
```

**Comment by asd281533890** [comment]
> 

Thank you for your solution. The second solution may block subsequent downloads. If there is no more better solution, I will adopt the first one you said.

**Comment by asd281533890** [comment]
> There are multiple possible ways you can solve that in user land. Here are two from the top of my head:
> 
> 1. Keep a `Map<url, savePath>` so you can look up the path inside the event handler via `downloadItem.getURL()`
> 2. Use a mutex (e.g. https://github.com/ide/await-lock) or a different queuing-system to prevent race conditions and guarantee a consistent order allowing you to use the `once('will-download')` closure

@Prinzhorn Thank you for your solution. The second solution may block subsequent downloads. If there is no more better solution, I will adopt the first one you said.

**Comment by codebytere** [comment]
In agreement with @Prinzhorn, given this is fairly trivially solvable in userland, this isn't something we're going to add to core at this time. Should something change, we're happy to consider revisiting this.

**Comment by asd281533890** [comment]
I finally set a hash for the url to associate the downloadURL with the will-download.
