### ISSUE TITLE
[Bug]: BrowserView app region can't trigger context-menu event.

### ISSUE THREAD

**Issue by XRenSiu** [electron/electron#37453]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.1

### What operating system are you using?

macOS

### Operating System Version

12.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

0.0.0

### Expected Behavior

When right-clicking on the app region, webContents can receive a context-menu event.

### Actual Behavior

When right-clicking on the app region, webContents can't receive a context-menu event.

### Testcase Gist URL

https://gist.github.com/XRenSiu/0d6a171ea10e81ad792aaab82a9b3e5f

**Comment by XRenSiu** [comment]
[test case gist url](https://gist.github.com/0d6a171ea10e81ad792aaab82a9b3e5f)

**Comment by nornagon** [comment]
I can repro this going as far back at least as Electron 14, probably earlier. So this bug has been around for a while, and isn't related to #37386.
