### ISSUE TITLE
[Bug]: Undo clears one character at a time in a React-controller input

### ISSUE THREAD

**Issue by codeclown** [electron/electron#37462]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Monterey 12.6

### What arch are you using?

x64

### Expected Behavior

1. Focus the textarea
2. Type "abc"
3. Press cmd+z
4. Input value is changed to ""

### Actual Behavior

1. Focus the textarea
2. Type "abc"
3. Press cmd+z
4. Input value is changed to "ab"

### Testcase Gist URL

https://gist.github.com/16965ee7d6083e143faf20b74d293da0

### Additional Information

Not a React-bug / does not happen in the browser. Codesandbox: https://codesandbox.io/s/twilight-paper-0fp74q

**Comment by Prinzhorn** [comment]
> does not happen in the browser

I'm seeing the exact same behavior in Chromium. At the end of the screencast I'm alternating ctrl+z and ctrl+y and it only changes the last character.

[Screencast from 2023-03-01 19-25-56.webm](https://user-images.githubusercontent.com/679144/222230030-c8b5b70e-e32f-4d6e-88b1-ad3e17910b9d.webm)

**Comment by Prinzhorn** [comment]
https://github.com/facebook/react/issues/8514

**Comment by codeclown** [comment]
@Prinzhorn You are correct. I can also reproduce this in Chrome. Earlier I tested it in Firefox, which is a brainfart on my part.
