### ISSUE TITLE
[Bug]: when App start, the child-process-gone event got  Utility,network.mojom.NetworkService,Network Service  crash code -1073740940, how can i fix it

### ISSUE THREAD

**Issue by ProvenceL** [electron/electron#37469]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.3

### What operating system are you using?

Windows

### Operating System Version

win32 10.0.19045

### What arch are you using?

ia32

### Expected Behavior

the browserwindow page is normal show

### Actual Behavior

the browserwindow page is white screen,can not do anything

**Comment by nornagon** [comment]
Please attach a crash dump. You can collect them by adding the following snippet to your main process code, before app.whenReady:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by ProvenceL** [comment]
> Please attach a crash dump. You can collect them by adding the following snippet to your main process code, before app.whenReady:
> 
> ```js
> const { app, crashReporter } = require('electron')
> 
> console.log(app.getPath('crashDumps'))
> crashReporter.start({ submitURL: '', uploadToServer: false })
> ```
> 
> Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by ProvenceL** [comment]
I am aleady open the local crashReporter like you，but i am not find the dump file in crashReporter\reports folder, because of this, i do not know what can i do more

**Comment by ProvenceL** [comment]
> Please attach a crash dump. You can collect them by adding the following snippet to your main process code, before app.whenReady:
> 
> ```js
> const { app, crashReporter } = require('electron')
> 
> console.log(app.getPath('crashDumps'))
> crashReporter.start({ submitURL: '', uploadToServer: false })
> ```
> 
> Then reproduce the crash, zip up the crash dumps directory and attach it here.

I am aleady open the local crashReporter like you，but i am not find the dump file in crashReporter\reports folder, because of this, i do not know what can i do more

**Comment by sourcegiegie** [comment]
> 

me too..

**Comment by sourcegiegie** [comment]
![image](https://github.com/electron/electron/assets/128764031/22e53746-3a31-48ce-9182-427b1c169b24)
sentry did not report a crash report, only this information

**Comment by zpm683** [comment]
me too...

**Electron Version**
19.1.2

**What operating system are you using?**
Windows11

**Comment by tommoor** [comment]
Still seeing this regularly in your error tracker, can we re-open?

**Electron Version**
29.1.6

**What operating system are you using?**
macOS, windows
