### ISSUE TITLE
[Bug]: did-fail-load event can not catch 403 status

### ISSUE THREAD

**Issue by binvb** [electron/electron#37470]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

electron@23.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6.3

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

i  can't catch loadURL error with:  
```
webContents.on('did-fail-load', async (event) => {})
// and
mainWindow.loadURL(url).catch(err=>{})
```
<img width="365" alt="image" src="https://user-images.githubusercontent.com/18115907/222379863-8691d4c5-3ead-47ac-85c5-ff11af2c7743.png">

### Actual Behavior

go inside ready-to-show event.

**Comment by nornagon** [comment]
This is working as intended; a 4xx isn't a failure to load.

**Comment by binvb** [comment]
> This is working as intended; a 4xx isn't a failure to load.

thank you, and where can i find if http status wouldn't catch?   
i can't find any document.thank you
