### ISSUE TITLE
[Bug]: onafterprint not being fired

### ISSUE THREAD

**Issue by seanaye** [electron/electron#37472]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.0

### What operating system are you using?

macOS

### Operating System Version

MacOS 12.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

N/A

### Expected Behavior

When printing an iframe the `contentWindow.onafterprint` event should be fired

### Actual Behavior

No event is fired. Tried all of the below

`contentWindow.onbeforeprint`
`contentWindow.onafterprint`
`contentWindow.addEventListener("beforeprint")`
`contentWindow.addEventListener("afterprint")`

### Testcase Gist URL
https://gist.github.com/76b1d83c30aa1028dc68f8bd0d278bad

### Additional Information

Same as #19685 it appears the issue was never solved and was instead closed

**Comment by codebytere** [comment]
@seanaye what are you trying exactly? If i run the default Fiddle Gist on macOS with version `v20.3.12` with the following lines added to the renderer process:

```
window.onafterprint = () => {
    console.log('this does not get called');
}
window.onbeforeprint = () => {
    console.log('this does get called');
}

window.print()
```

it works just fine, and both console logs appear correctly.

**Comment by seanaye** [comment]
@codebytere thanks for looking at this. I updated the original post with the gist repro

**Comment by seanaye** [comment]
This appears to be a feature of Chrome: https://stackoverflow.com/a/51735450/13271838

Closing
