### ISSUE TITLE
css cursor: pointer; not work correctly when element on the top of the window.

### ISSUE THREAD

**Issue by Shandawei** [electron/electron#37497]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.1

### What operating system are you using?

macOS

### Operating System Version

12.6.3 (21G419)

### What arch are you using?

x64

### Expected Behavior

css cursor: pointer work all frame of the element.

### Actual Behavior

css cursor: pointer only works at the bottom of the element, maybe the m1 mac mini of my friend will be working as expected.

### Testcase Gist URL

https://gist.github.com/2b596877710b06c9366d70a25ee6da77

### Additional Information

Maybe the issue is only on macOS x64.

https://user-images.githubusercontent.com/876662/222960065-fc742fd8-5990-4d16-bfd3-23729f4b4919.mp4

**Comment by codebytere** [comment]
@Shandawei this is unfortunately not a problem with Electron itself - it's an issue originating with Chromium appearing only on x64 macOS machines. This should be fixed upstream with Chromium - once they fix it we will inherit the fix for free.

**Comment by yuanzhibang-tool** [comment]
@codebytere if I set the titleBarStyle='default ', the css style works as expected.  Do you think it's an error of Chromium and it is an issue of many electron versions. I think it is an issue with the standard title bar area.
