### ISSUE TITLE
[Bug]: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fetch' 

### ISSUE THREAD

**Issue by TomasHubelbauer** [electron/electron#37493]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Since Electron 23.1.2 ships with Node 18.12.1 according to https://releases.electronjs.org/releases.json it should support the global `fetch` API which started shipping with Node 17.5.0 and since 18.0.0 is no longer behind `--experimental-global-fetch`. This code should work:

```javascript
const fetch = require('fetch');
console.log(fetch);
```

### Actual Behavior

When I run this code in my Electron script, I get the titular error:

```javascript
const fetch = require('fetch');
console.log(fetch);
```

### Additional Information

I searched the issues for `is:issue Cannot find package 'fetch'` but did not find anything relevant.

**Comment by mattlucock** [comment]
Electron does support the global `fetch` API, the key word being *global*. There is no module to import; `fetch` is just available by default. Your import also does not work in regular Node, because the module doesn't exist.

I hope I haven't misunderstood your issue; please correct me if I have.

**Comment by TomasHubelbauer** [comment]
I got my wires crossed, for some reason I didn't realize I don't need anything to import as `fetch` is now a built-in. In both Node and the Electron main process being Node as I've just verified. Apologies for the noise!
