### ISSUE TITLE
[Bug]: Window showing on 'open-url' with preventDefault()

### ISSUE THREAD

**Issue by vothvovo** [electron/electron#37495]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.3

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey

### What arch are you using?

x64

### Expected Behavior

The window should not show up.

### Actual Behavior

The window shows up.

### Testcase Gist URL

https://gist.github.com/vothvovo/00b6932c52d49c2ecf42853bd5db778a

### Additional Information

You have to build the gist to test it because otherwise the custom uri schema won't register.

**Comment by codebytere** [comment]
@vothvovo this event is not preventable - the documentation is wrong. I opened a PR to update it.
