### ISSUE TITLE
[Bug]: can not download pdf

### ISSUE THREAD

**Issue by zk320520** [electron/electron#37498]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

x64

### Expected Behavior

use iframe in browserView, download button in pdf viewer can download pdf

### Actual Behavior

![20230306094408](https://user-images.githubusercontent.com/24220783/223001479-90501157-9ac2-4bf1-8a7b-86ecf6312f62.jpg)
use iframe in browserView, download button in pdf viewer is not work

**Comment by codebytere** [comment]
v15 is no longer supported - this is fixed in currently supported versions.
