### ISSUE TITLE
[Bug]: webRequest.onHeadersRecieved applies headers inconsistently

### ISSUE THREAD

**Issue by Kilian** [electron/electron#37509]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.2

### What operating system are you using?

Ubuntu

### Operating System Version

18.04

### What arch are you using?

x64

### Expected Behavior

When changing headers in `webRequest.onHeadersRecieved` they are applied to all responses and those are visible in the network tab of the chrome devtools.

### Actual Behavior

When changing headers, behaviour seems inconsistent when inspecting with the chrome devtools network tab.

I set an `x-wat` header in the onHeadersRecieved function.

fromscratch.rocks: 
It seems the header isn't being added for the main URL, though it's added to CSS, JS and image requests made from the site. You can see in the log however that the function is being called for the main URL.

fixa11y.com (comment out the line in the test case)
It seems that none of the requests here get the `x-wat` header added to them, not the main page nor any of its resources.

### Testcase Gist URL

https://gist.github.com/4db8fc74ae56a7cc973a07c80bf63700

### Additional Information

To use the testcase:

- launch the app from fiddle
- switch to the network tab
- press ctrl/cmd r to reload the page
- inspect the headers of the main web page and other resources.

**Comment by MarshallOfSound** [comment]
@Kilian Just to be clear here, is the issue just that the header modification doesn't show up in devtools.  Or does the header modification actually not impact the `Request` / `Response` objects in JS.  The devtools view doesn't show updated headers for chrome extensions either so I'd suspect that that alone is expected / upstream behavior

**Comment by Kilian** [comment]
@MarshallOfSound you're right, the response headers do have them, just the devtools don't show them! Closing this out, thanks.
