### ISSUE TITLE
Windows created with `window.open` do not inherit up-to-date window options (particularly `show`)

### ISSUE THREAD

**Issue by wearhere** [electron/electron#3751]
Follow-up to #2771.

If:
1. you create a `BrowserWindow` with the `show` option set to `false`,
2. you show that window
3. JavaScript in that page calls `window.open`

nothing will happen—no window will appear.

My hypothesis is that the new window is inheriting the `show` option. This is corroborated by #2771. (However I tried selecting the "Bring All to Front" menu option (with `role` set to 'front') and that didn't cause any hidden windows to appear—perhaps that's a separate bug.)

I think it's reasonable for a new window to inherit `show: false` if the parent window is hidden—but after the parent window is shown, child windows should also be shown, no? Otherwise `window.open` is forever broken in the parent window.

(The parent window could call `window.open` with `show=true`, but IMO even if Electron chooses to hide child windows, in-page JavaScript loaded from a remote server should not have to be aware of this.)

As far as the rest of the options that child windows inherit, I'm undecided whether I think that the child windows should inherit the up-to-date options or the original options. It'd probably simplify the implementation to have everything be up-to-date. On the other hand, perhaps the original options are better defaults for new windows.

**Comment by wearhere** [comment]
A workaround is to immediately `hide` the window after creating it rather than pass `show: false`.

**Comment by abdihaikal** [comment]
Have you try with the BrowserWindow options: webPreferences -> preload
http://electron.atom.io/docs/v0.35.0/api/browser-window/

**Comment by wearhere** [comment]
I do indeed have set `webPreferences.preload`, and still see the issue—not sure what result you expected that to have.

**Comment by wearhere** [comment]
Ah, this was caused by #2771. I'll ask about reopening that issue there.

**Comment by wearhere** [comment]
Actually I think this is slightly different than #2771. Please read the updated title and description. cc @zcbenz, the implementer on #2771.

**Comment by brian-mann** [comment]
We are still having issues with this as of `0.37.6` but have found a very nice and simple workaround.

All you have to do is listen to the `new-window` event of the parent `webContents` instance and modify the `options`.

These options should come from the `features` string in `window.open` and should be merged into the parent `BrowserWindow` options.

```javascript
win.webContents.on("new-window", function(e, url, frameName, disposition, options){
  // modify any other options such as width/height, etc
  options.show = false
})
```

**Comment by codebytere** [comment]
closing due to abandonment.
