### ISSUE TITLE
[Bug]: app drag regions capture clicks on windows with frame

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#37515]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### What arch are you using?

x64

### Last Known Working Electron version

22.2.1

### Expected Behavior

WebContents containing `-webkit-app-region: drag` should not be draggable or capture clicks when a window includes a frame.

### Actual Behavior

WebContents containing `-webkit-app-region: drag` captures clicks and is not draggable when window includes a frame.

### Testcase Gist URL

https://gist.github.com/samuelmaddock/ce68e2160f80c576bbf0bc3a8809363d

### Additional Information

This likely isn't a bug, but rather a change in Chromium that might need to be documented in our release notes.

@MarshallOfSound mentioned that `-webkit-app-region` was recently implemented for non-frameless windows in Chrome, likely leading to this change of behavior.

**Comment by nornagon** [comment]
Hm, are we sure this is intended behavior? I think drag regions working on windows with a frame seems like a bug.

**Comment by codebytere** [comment]
@nornagon tracked to https://github.com/electron/electron/compare/v23.0.0-nightly.20221107...v23.0.0-nightly.20221108 - https://github.com/electron/electron/commit/184ac2b382e8324a0b3db1944fd17cdd6ccffff9 caused it it looks like
