### ISSUE TITLE
[Bug]: After setting BrowserView.setAutoResize, then repeatedly resize the entire window, the content of the BrowserView will slip up and hide

### ISSUE THREAD

**Issue by wangjunkai** [electron/electron#37518]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v23.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

x64

### Last Known Working Electron version

Keep trying until 17.x,Maybe all versions have problems

### Expected Behavior

Once setAutoResize is set, then repeatedly resize the entire window so that the contents of BrowserView are not scrolled and hidden

### Actual Behavior

After setting BrowserView.setAutoResize, then repeatedly resize the entire window, the content of the BrowserView will slip up and hide

![372 (1)](https://user-images.githubusercontent.com/9315821/223899038-9789e51d-9442-4b6e-9cef-3c97f12ffe25.gif)

### Testcase Gist URL

https://gist.github.com/wangjunkai/8d6efe906d6ac5827dcf7a94604d5964

### Additional Information

If setAutoResize is not set, it is normal

**Comment by MrFiend179** [comment]
The video doesnt work.
Have u tried updating electron to its latest version.
Try declaring in the browser window body css `overflow y: hidden;`

**Comment by MrFiend179** [comment]
U could also try listening for resize event anthen update the setBounds method of the BrowserView accordingly
``` mainWindow.on('resize', () => {
    const bounds = mainWindow.getBounds()
    view.setBounds({
      x: 50,
      y: 50,
      width: bounds.width - 100, // adjust for margins
      height: bounds.height - 100 // adjust for margins
    })
  })
}
```
Use this in main process

**Comment by longzezhao** [comment]
Set fixed width and height for content area?

**Comment by wangjunkai** [comment]
I'm not going to set setAutoResize, and then

mainWindow.on('resize', () => {
    const bounds = mainWindow.getBounds()
    view.setBounds({
      x: 50,
      y: 50,
      width: bounds.width - 100, // adjust for margins
      height: bounds.height - 100 // adjust for margins
    })
  })
}
