### ISSUE TITLE
[Bug] : Can't able to store cookies using electron session

### ISSUE THREAD

**Issue by dhineshtp** [electron/electron#37520]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Able to get, store and remove the cookies in application using session. 

### Actual Behavior

I can't able to store the cookies using session. Getting session as undefined. 

```
TypeError: Cannot read properties of undefined (reading 'defaultSession')
    at setAuthenticationToken (cookie.ts?9807:42:13)
    at eval (signin.tsx?7f92:78:27)
    at step (tslib.es6.js?a673:147:1)
    at Object.eval [as next] (tslib.es6.js?a673:128:46)
    at asyncGeneratorStep (_async_to_generator.mjs?bf9b:3:1)
    at _next (_async_to_generator.mjs?bf9b:25:1)
    at eval (_async_to_generator.mjs?bf9b:32:1)
    at new Promise (<anonymous>)
    at eval (_async_to_generator.mjs?bf9b:21:1)
    at redirectToAdmin (signin.tsx?7f92:77:51)
    at eval (signin.tsx?7f92:65:30)
    at async eval (index.esm.mjs?18ef:2013:1)

```

Previously I used `js-cookie` to do that, but it didn't worked on exported. So I remove d it.  

### Additional Information

I'm using the typescript in electron with nextJs. I have to created new file name `cookies.ts` to manage the cookies related task. Inside that file, I have imported `session` from electron. Then I wrote a function to store cookie in application.  

Previously I used `js-cookie` to store the cookies. But that didn't worked on exported application. So I explored and found out about the session, which we can use it store the cookies. But it's also not working.  This is the function I wrote to store it 👇

```
import { session } from 'electron';

export const setAuthenticationToken = (userToken: any) => {

  if (userToken) {
    let stringifyUserToken = userToken ? optimizeUserToken(userToken) : null;
    stringifyUserToken =
      stringifyUserToken != null ? JSON.stringify(stringifyUserToken) : "";
     session.defaultSession.cookies.set({
      name: "userToken",
      value: stringifyUserToken,
      url: "",
     });
    setAxiosHeader(userToken.access_token);
  }

};
```

Here I'm getting session as undefined. I tried to store the cookies by using and importing the `webContents`, But that's also not working. I can't able to find any proper way to resolve this. I need some one help to resolve this.

**Comment by MrFiend179** [comment]
Have u tried using local storage?
Its relaively easy and you can clear it whenever you like

**Comment by ckerr** [comment]
@dhineshtp could you please attach a testcase that doesn't require external dependencies? The snipped you've provided here depends on  undefined function `optimizeUserToken()` and also third-party library `axios`.

Basically, the maintainers are looking for a fiddle that can be plugged into [Electron Fiddle](https://www.electronjs.org/fiddle/) for quick & easy testing to reproduce the problem.

**Comment by codebytere** [comment]
@dhineshtp are you trying to do this in the renderer process? `session` is a main process only module, so it would be undefined in the renderer.
