### ISSUE TITLE
[Bug]: getLocale for system language fr-CA (or en-CA) returns fr (or en)

### ISSUE THREAD

**Issue by inxsvf** [electron/electron#37534]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22; 23

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2 19044.2604

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

When "Windows display language" is set to French (Canada) both  [`getLocale()`](https://www.electronjs.org/docs/latest/api/app#appgetlocale) and `navigator.language` should return `fr-CA`

\* if not using [--lang](https://www.electronjs.org/docs/latest/api/command-line-switches#--lang) or similar to change the application's locale

### Actual Behavior

`getLocale` and `navigator.language` returns `fr`

(same happens with `en-CA` => `en-GB`)

![electronWindowsLang](https://user-images.githubusercontent.com/476038/223761248-239c2836-f7d8-458b-b1f4-780a8fbebad1.PNG)

### Testcase Gist URL

https://gist.github.com/inxsvf/57b0c9e99f9a9f70446d908bab8a3625

### Additional Information

Hi! 

Firstly, thanks for all your work 🙏💖

I'm an Electron newbie and this issue impacts how external pages are rendered inside an Electron app (what language they will try to use). 

**Questions**:

1) From the Windows Language Settings panel it says that "Windows display language - _Windows features, like Settings and File Explorer, will appear in this language._" and for "Preferred Languages - _Apps and websites will appear in the first language in the list that they support._"
    - On the "Preferred Languages" list `fr-CA` code is passed correctly to [`getPreferredSystemLanguages()`](https://www.electronjs.org/docs/latest/api/app#appgetpreferredsystemlanguages).

    - When the "Windows display language" changes, it is automatically set as the first item on "Preferred Languages" (followed by similar languages). But the user can also edit that list, and so "Windows display language" might not be the first one.
    
    Should _application locale_ or `getLocale` or `navigator.langugae` be using "Windows display language" or "Preferred languages"?

2) It looks like it is related to some Chromium Issue: when it doesn't have that language available it defaults to the closest one:
    - https://bugs.chromium.org/p/chromium/issues/detail?id=99526
    - https://bugs.chromium.org/p/chromium/issues/detail?id=874225

    What can we do to workaround this? 

**Related Issues:**
- https://github.com/electron/electron/issues/34194
- https://github.com/electron/electron/issues/28119

**Comment by inxsvf** [comment]
As a workaround, I tried to [add a pak file to the locales folder (as suggested in issue#28119)](https://github.com/electron/electron/issues/28119#issuecomment-1072719929), it only worked for fr-CA (getLocale was fr-CA ✔️). For en-CA, `getLocale` was en-GB ❌...

**Comment by VerteDinde** [comment]
Thanks so much for the repro and the detailed issue report! We'll have someone start looking into this soon 🙇‍♀️

**Comment by ckerr** [comment]
FWIW, it doesn't appear to be Windows-specific.

Testing @inxsvf's gist on Electron 22.0.2 on Ubuntu 22.04.02, when setting my language to en-CA, `getLocale()` returns `en-GB`. I didn't manually select `en-GB` at any time.

```
Electron v22.0.2 started.
getLocale en-GB
getSystemLocale en-CA
getPreferredSystemLanguages en-CA, en, en
```

![linux](https://user-images.githubusercontent.com/70381/225078330-b9b7b445-0710-4b2a-8ded-7998ec13a294.png)

**Comment by ckerr** [comment]
Same behavior in the 25 nightlies:

```
Electron v25.0.0-nightly.20230310 started.
getLocale en-GB
getSystemLocale en-CA
getPreferredSystemLanguages en-CA, en, en
```

**Comment by codebytere** [comment]
Closing in agreement with above - this isn't actionable on our end.
