### ISSUE TITLE
[Bug]: 打包后托盘图标找不到图片文件

### ISSUE THREAD

**Issue by WX308806058** [electron/electron#37542]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.0.0

### What operating system are you using?

Windows

### Operating System Version

win10  21H2

### What arch are you using?

x64

### Expected Behavior

使用 vue-cli-service electron:build 命令打包，安装应用并启动，发现托盘图标不显示，

每次都要把图标文件复制到目录下才行，有没有方法使其在打包的时候就把图片一起打包过去？

`var {
	Menu,
	Tray,
	BrowserWindow,
	app,
	nativeImage
} = require('electron');

var win = BrowserWindow.getFocusedWindow();

var path = require('path');

var iconPath = "";

if (process.env.WEBPACK_DEV_SERVER_URL) {
	//测试环境
	iconPath = nativeImage.createFromPath(path.join(app.getAppPath(), '../build/icons/icon.ico'));

} else {
	//正式环境
	iconPath = nativeImage.createFromPath(path.join(path.dirname(app.getPath('exe')), './icon.ico'));
}

// 创建拖盘
var iconTray = new Tray(iconPath);

// 鼠标悬停托盘提示
iconTray.setToolTip('QRCloud打印系统');

// 配置右键菜单
var trayMenu = Menu.buildFromTemplate([{
		label: '设置',
		click: function() {
			console.log('setting')
		}
	},
	{
		label: '升级',
		click: function() {
			console.log('update')
		}
	},
	{
		label: '退出',
		click: function() {
			if (process.platform !== 'darwin') {
				app.quit();
			}
		}
	}
]);

// 绑定右键菜单到托盘
iconTray.setContextMenu(trayMenu);

// setTimeout(function() {

// 	// 点击关闭按钮让应用保存在托盘
// 	win.on('close', (e) => {
// 		if (!win.isFocused()) {
// 			win = null;
// 		} else {
// 			// 阻止窗口的关闭事件
// 			e.preventDefault();
// 			win.hide();
// 		}
// 	});
// })

// 任务栏图标双击托盘打开应用
iconTray.on('double-click', function() {
	win.show();
});
`

### Actual Behavior

使用 vue-cli-service electron:build 命令打包，安装应用并启动，发现托盘图标不显示，

每次都要把图标文件复制到目录下才行，有没有方法使其在打包的时候就把图片一起打包过去？

`var {
	Menu,
	Tray,
	BrowserWindow,
	app,
	nativeImage
} = require('electron');

var win = BrowserWindow.getFocusedWindow();

var path = require('path');

var iconPath = "";

if (process.env.WEBPACK_DEV_SERVER_URL) {
	//测试环境
	iconPath = nativeImage.createFromPath(path.join(app.getAppPath(), '../build/icons/icon.ico'));

} else {
	//正式环境
	iconPath = nativeImage.createFromPath(path.join(path.dirname(app.getPath('exe')), './icon.ico'));
}

// 创建拖盘
var iconTray = new Tray(iconPath);

// 鼠标悬停托盘提示
iconTray.setToolTip('QRCloud打印系统');

// 配置右键菜单
var trayMenu = Menu.buildFromTemplate([{
		label: '设置',
		click: function() {
			console.log('setting')
		}
	},
	{
		label: '升级',
		click: function() {
			console.log('update')
		}
	},
	{
		label: '退出',
		click: function() {
			if (process.platform !== 'darwin') {
				app.quit();
			}
		}
	}
]);

// 绑定右键菜单到托盘
iconTray.setContextMenu(trayMenu);

// setTimeout(function() {

// 	// 点击关闭按钮让应用保存在托盘
// 	win.on('close', (e) => {
// 		if (!win.isFocused()) {
// 			win = null;
// 		} else {
// 			// 阻止窗口的关闭事件
// 			e.preventDefault();
// 			win.hide();
// 		}
// 	});
// })

// 任务栏图标双击托盘打开应用
iconTray.on('double-click', function() {
	win.show();
});
`

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
