### ISSUE TITLE
[Bug]:  alwaysOnTop window doesn't receive focus when using Command–Grave accent (`) keyboard shortcut

### ISSUE THREAD

**Issue by bradmanAWS** [electron/electron#37547]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.1.9

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.2.1

### What arch are you using?

x64

### Expected Behavior

Using the mac keyboard shortcut Command–Grave accent switches keyboard focus between all application windows, including windows that have property `alwaysOnTop: true`.

https://support.apple.com/en-us/HT204434#:~:text=the%20front%20app-,Command%E2%80%93Grave%20accent%20(%60),-Activate%20the%20previous

https://support.apple.com/en-us/HT201236#:~:text=Command%E2%80%93Grave%20accent%20(%60)

### Actual Behavior

If a window is given the `alwaysOnTop: true` property, it does not receive focus when using the Mac keyboard shortcut Command–Grave accent (`CMD + ~`).

**Comment by codebytere** [comment]
@bradmanAWS it might be kind of hard to verify this but i unfortunately suspect this is an issue at the native level. Setting `alwaysOnTop: true` or calling `window.setAlwaysOnTop(true, level)` with any [level](https://developer.apple.com/documentation/appkit/nswindowlevel) above `normal` causes this problem, and I suspect that would also be true for an arbitrary native app that sets the window level above normal.

**Comment by schontz** [comment]
Registering the global shortcut will capture it even when other apps are in focus? This seems undesirable.
