### ISSUE TITLE
[Bug]: mixed content don't shown

### ISSUE THREAD

**Issue by cnhuye** [electron/electron#37551]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.3

### What operating system are you using?

macOS

### Operating System Version

11.7.4 (20G1120)

### What arch are you using?

x64

### Last Known Working Electron version

8

### Expected Behavior

Display HTTP images in a HTTPS page.

### Actual Behavior

The HTTP images are forced redirect to a HTTPS url.

### Additional Information

I have a HTTPS web page, in the page, there are some HTTP image to show.

In previous version Electron (maybe 12 I forgot), the images are working. But in Electron V20, I got this warning message:

> Mixed Content: The page at 'https://......' was loaded over HTTPS, but requested an insecure element 'http://183.251.216.162:8087/ims/_P-SCKs7tcyheFG_IUtNUf3EFwg=/fit-in/300x300/smart/ver1677583017/album/1019/230100/1/00007823.JPG'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

Then the HTTP images are forced redirect to HTTPS, but the image server is a locale deployed server, don't support HTTPS.

I already set webPreferences when CreateWindow in main.js:
```
createWindow({
          webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
            enableRemoteModule: true,
            webviewTag: true,
            webSecurity: false,
            allowRunningInsecureContent: true,
            allowDisplayingInsecureContent: true
          },
          width: 1024,
          height: 600
        })
```
and set `disablewebsecurity` in WebView tag:
```
<webview id="main_page" disablewebsecurity="on" allowpopups="on" partition="persist:photo-studio" autosize="on" style="width:100%;height:100%" preload="./preload.js" webpreferences="allowRunningInsecureContent,allowDisplayingInsecureContent,nodeIntegration=true, contextIsolation=false" src="https://..."></webview>
```
But don't work for me.

How can I show the mixed content correctly ?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by Riteshsulakhe1** [comment]
@codebytere I am facing the same issue on
Electron: v24.1.1
I have the same webPreference. In my case "allowRunningInsecureContent" is loading the "http" page but one of the API call is going to insecure "http" url that is getting blocked.
Please help and re-open the issue.
Thanks
