### ISSUE TITLE
[Bug]: Accelerators on dialogs button doesn't underline the key

### ISSUE THREAD

**Issue by MaelNivel** [electron/electron#37563]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version 21H2

### What arch are you using?

x64

### Expected Behavior

Dialog buttons with accelerator underlines the accelerator key on Windows.

Example of expected Behavior:
![image](https://user-images.githubusercontent.com/127734549/224663796-db089b30-0c73-45f3-98fa-365f91e18fdf.png)

### Actual Behavior

**Without Electron Fiddle**

The dialogue buttons has the accelerator key but sometimes do not highlight the required key.

Current Dialog :
![image](https://user-images.githubusercontent.com/127734549/224664539-eba4a409-4a36-4f5a-854d-4c1e6de382a4.png)

In those cases the application has to be restarted (potentially multiple times) for the accelerator key to be highlighted.

**With Electron Fiddle**

The dialogue buttons include the accelerator key but never highlight the required key.

### Testcase Gist URL

https://gist.github.com/bcab636e5c73a9c86aebe44449673a04

### Additional Information

According to the documentation, on Windows, Electron automatically adds a shortcut and a specific style to common buttons (like "Cancel" or "Yes"). On Fiddle, even common buttons are not highlighted.

![image](https://user-images.githubusercontent.com/127734549/224676479-868d3d3d-9a86-4a66-9467-abc6c9645228.png)

**Comment by codebytere** [comment]
@MaelNivel to clarify - are you saying this is a Fiddle issue? If yes, this should be opened on the [Fiddle repo](https://github.com/electron/fiddle)

**Comment by florent-guinard** [comment]
Hi,

We also have this issue in our Electron application. Is there anything else we can try/use to make this work consistently?

**Comment by florent-guinard** [comment]
We're still affected by the issue, it can be reproduced in electron v27.
