### ISSUE TITLE
[Bug]: Electron TLS session reuse bug

### ISSUE THREAD

**Issue by thesunfei** [electron/electron#37562]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 PRO Version 22H2

### What arch are you using?

x64

### Expected Behavior

Specified TLS session buffer was applied after using tls.connect() session parameter.

### Actual Behavior

Electron tls.connect() function ignored session parameter or reusing session failed.

### Testcase Gist URL

https://gist.github.com/d35fa1e6212d03cc5af828e2ae6dbc18

### Additional Information

In this gist example,when the ftp client is using LIST command,it reused the session buffer that already connected to the FTP server with,it works well independently in a node.js file,but got an error "SSL connection failed: session reuse required" returned by the FTP server when running in Electron because session reuse failed.
Here are the clear codes that described the issue:

```
let socket = tls.connect({
  socket:a socket,
  session:a session Buffer
});
console.log(socket.getSession())//returned undefined in Electron,but returned the right session Buffer in standalone Node.js.
```

**Comment by codebytere** [comment]
@thesunfei can you please provide an example of what you understand to be the working correct behavior in Node.js?

**Comment by thesunfei** [comment]
> @thesunfei can you please provide an example of what you understand to be the working correct behavior in Node.js?

There is a preload.js file in the gist project,it is the same file that runs in Electron,use "node preload.js" to run it in standalone node.js.

**Comment by sid-max1996** [comment]
I have same problem, trying to use basic-ftp (https://www.npmjs.com/package/basic-ftp?activeTab=readme) in electron 28.0.0.
This code works with nodejs without electron. In electron it throws error:
522 SSL connection failed: session reuse required
Error: Server sent FIN packet unexpectedly, closing connection.

```javascript
const ftp = require('basic-ftp')
const { mkdir, access, stat } = require('fs').promises
const path = require('path')

const createDirectoryIfNotExists = async (folderPath) => {
  try {
    await access(folderPath)
  } catch (e) {
    await mkdir(folderPath, { recursive: true })
  }
}

const getFileStat = async (filePath) => {
  try {
    return await stat(filePath)
  } catch (e) {
    return null
  }
}

const remoteFolderPath = 'some_ftps_folder'
const localFolderPath = path.join(__dirname, 'ftps-download')
const ftpConfig = {
  host: 'X.X.X.X',
  port: 21,
  user: 'some_login',
  password: 'some_pass',
  secure: true,
  secureOptions: {
    rejectUnauthorized: false // prevent self signed certificate error
  }
}

export async function startFtps() {
  const client = new ftp.Client()

  client.ftp.verbose = true
  try {
    await client.access(ftpConfig)
    console.log('connected')

    const files = await client.list(remoteFolderPath)
    console.log('file list', files)

    client.trackProgress((info) => {
      console.log('File', info.name)
      console.log('Type', info.type)
      console.log('Transferred', info.bytes)
      console.log('Transferred Overall', info.bytesOverall)
    })

    createDirectoryIfNotExists(localFolderPath)

    for (const file of files) {
      const fileName = file.name
      const fileSize = file.size
      const remoteFilePath = path.join(remoteFolderPath, fileName)
      const localFilePath = path.join(localFolderPath, fileName)
      const localFileStat = await getFileStat(localFilePath)
      if (localFileStat && fileSize && localFileStat.size === fileSize) {
        console.log('Already downloaded file', fileName)
        continue
      }
      try {
        await client.downloadTo(localFilePath, remoteFilePath)
        console.log('Downloaded file', fileName)
      } catch (err) {
        console.error('Error download file', fileName, err)
      }
    }

    // Stop logging
    client.trackProgress()
  } catch (err) {
    console.log(err)
  }
  client.close()
}

startFtps()
```

**Comment by sid-max1996** [comment]
> maxVersion

@thesunfei thanks a lot. This works. I changed secureOptions in ftpConfig to:
```javascript
 secureOptions: {
    rejectUnauthorized: false,
    maxVersion: 'TLSv1.2'
  }
```
