### ISSUE TITLE
[Bug]: Open at login with setLoginItemSettings in MAS build is not working

### ISSUE THREAD

**Issue by domengasperlin** [electron/electron#37560]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

macOS

### Operating System Version

Version 13.2 (22D49)

### What arch are you using?

x64

### Expected Behavior

Setting app to open at login with setLoginItemSettings api should work both locally and with MAS build.
Locally the app is added to login items but when i build it for MAS this doesn't work.

### Actual Behavior

Setting app to open at login with setLoginItemSettings api works locally but doesn't work in MAS build. 
In MAS build the app is not added to login items. 
<img width="477" alt="image" src="https://user-images.githubusercontent.com/17458685/224576455-a9145dfc-7121-4097-9fe4-a472f0c2ead4.png">

### Additional Information

According to docs https://www.electronjs.org/docs/latest/api/app#appsetloginitemsettingssettings-macos-windows setting login item in MAS build should work by using the following API
```js
app.setLoginItemSettings({
    openAtLogin: openAtLogin,
  })
```
In the docs on limitations of MAS build there is no mention of any limitation of using above API https://www.electronjs.org/docs/latest/tutorial/mac-app-store-submission-guide#limitations-of-mas-build 

Here is possible related issue and PRs:
- https://github.com/electron/electron/issues/7312
- https://github.com/electron/electron/pull/11144
- https://github.com/electron/electron/pull/10856

**Comment by codebytere** [comment]
See https://github.com/electron/electron/pull/37244 - this is an underlying API issue.

**Comment by evmin** [comment]
I was able to reproduce the issue in Electron 26.6.2 on Monterey 12.7.1.
```
  app.setLoginItemSettings({
      openAtLogin: true,
    });
```
Fails to add the application to the Login Items when the application is installed through TestFlight.
