### ISSUE TITLE
[Feature Request]: Open the system preferences pane in MacOS when re-requesting permission

### ISSUE THREAD

**Issue by theogravity** [electron/electron#37581]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

A user might deny permission to media (microphone, camera, screen recording) accidentally when calling `systemPreferences.askForMediaAccess()`.

I'd like to be able to open the system prefs pane for that specific media should the user request again.

### Proposed Solution

I'd like the `systemPreferences.askForMediaAccess()` call to open the corresponding system preferences pane when the user re-requests access under a denied status, or another API call that I can use to open it.

### Alternatives Considered

https://github.com/codebytere/node-mac-permissions does what I generally need, but it's additional configuration / steps to bundle in a native module into an electron project.

**Comment by nornagon** [comment]
You can do this trivially with `shell.openExternal('x-apple.systempreferences:com.apple.preference.security?Privacy_Camera')`, which is more or less what the linked module does.
