### ISSUE TITLE
[Bug]: 'system-context-menu' event is not triggered

### ISSUE THREAD

**Issue by ferreira-tb** [electron/electron#37614]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

System context menu should not appear.

### Actual Behavior

It appears.

### Testcase Gist URL

https://gist.github.com/ferreira-tb/d98c7d72a33a98f5dcc2baf438ee56fc

### Additional Information

```javascript
mainWindow.on('system-context-menu', (e) => e.preventDefault())
```

This should prevent the context menu from appearing. However, it still appears in regions with `-webkit-app-region: drag;` when `frame: false`.

I opened this issue to reproduce #37055.

**Comment by Nabin2469** [comment]
> 

Ok

**Comment by ferreira-tb** [comment]
bump

**Comment by ferreira-tb** [comment]
Bump
