### ISSUE TITLE
[Bug]: setApplicationMenu causes 'Minimize All' to be disabled

### ISSUE THREAD

**Issue by colin1994** [electron/electron#37619]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5

### What arch are you using?

x64

### Expected Behavior

If not call **setApplicationMenu** to customize the menu. Press Option, **Minimize** will become **Minimize All**, use `Cmd+Option+M`, all windows can be minimized.

If use **setApplicationMenu** to customize the menu. like this:
```javascript
const menu = Menu.buildFromTemplate([
  {
    label: 'Window',
    submenu: [
      { role: 'minimize' },
      { role: 'close' }
    ]
  }])
Menu.setApplicationMenu(menu)
```
Expect **'Minimize All'** to work as usual

### Actual Behavior

However, when customizing the Menu, pressing Option, and **'Minimize'** will not change anything. Always keep Minimize. 

`Cmd + Option + M` doesn't work.

Appreciate any feedback. Thank you.

### Testcase Gist URL
https://gist.github.com/colin1994/d01be66bcadec3678f8c3654f3d362e1

_No response_

**Comment by ameeetgaikwad** [comment]
Would like to help!

**Comment by its-kunal-ssi** [comment]
I would like to help in this issue.

**Comment by colin1994** [comment]
**Updated.**
Testcase Gist URL
https://gist.github.com/colin1994/d01be66bcadec3678f8c3654f3d362e1

**Comment by codebytere** [comment]
This is unfortunately not something that's expected to work as you describe - it switches to `Close All` only when it is created as part of the Window Menu (see: `windowmenu` role)
