### ISSUE TITLE
[Bug]: Angular DevTools Extension Doesn't Work

### ISSUE THREAD

**Issue by mann-david** [electron/electron#37616]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11, 22H2, Build 22621.1413

### What arch are you using?

x64

### Expected Behavior

The Angular DevTools extension (https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh) works in Chrome but not in Electron.  

### Actual Behavior

The extension loads and shows in the DevTools, but when I click on it to open, it just says "Angular application not detected."  (and yes, I am running an Angular app in my renderer :-) )

The following error is logged in the console:

(node:7928) ExtensionLoadWarning: Warnings loading extension at { my homeDir path }\AppData\Local\Google\Chrome\User Data\Default\Extensions\ienfalfjdbdpebioblfackkekamfmbnh\1.0.7_0:
  Permission 'scripting' is unknown or URL pattern is malformed.
  Permission 'activeTab' is unknown or URL pattern is malformed.

(Use `electron --trace-warnings ...` to show where the warning was created)
[7928:0318/183519.105:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[7928:0318/183519.105:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
[7928:0318/183526.929:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[7928:0318/183526.929:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)

**Comment by codebytere** [comment]
Angular DevTools [uses manifest v3](https://github.com/angular/angular/blob/f9b821f07d8dba57a6a7e5fc127dc096247424aa/devtools/projects/shell-browser/src/manifest/manifest.chrome.json#L2) which Electron doesn't yet support. Folding into https://github.com/electron/electron/issues/37876 as a duplicate.
