### ISSUE TITLE
[Bug]: removal of increase/decreaseCaptureCount changed behavior of capturePage

### ISSUE THREAD

**Issue by Kilian** [electron/electron#37611]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23

### What operating system are you using?

Ubuntu

### Operating System Version

18.04

### What arch are you using?

x64

### Last Known Working Electron version

22

### Expected Behavior

When calling `capturePage` on a `webContents` that was offscreen somehow (scrolled out of sight) it immediately returns with an empty image. This isn't great and rarely what you want.

In 22 and earlier this could be remedied by calling `webContents.incrementCaptureCount()`, which would stall until the `webContents` did become visible, and a `capturePage` after it would return an image. You could use this, along with a timeout, to detect "stalled" capturePages and take measures to scroll them into view and make them screenshotable.

### Actual Behavior

With the removal of `webContents.incrementCaptureCount()` it is no longer possible to know that a webContents needs to be brought into view to be screenshottable.

### Additional Information

Setting a testcase up for this is quite involved, so I'm hoping someone has a "oh but you forgot setting Foo!" solution. If not then I'll set up a fiddle.

**Comment by Kilian** [comment]
Gist: https://gist.github.com/Kilian/73cf6002347a4cd3cda2d29a6ad8ccd0

This gist has one horizontally scrollable div with two webviews: a leftmost one that renders electronjs.org, and a rightmost one that renders nodejs.org. The rightmost one is offscreen. There are two buttons to capture a screenshot from a webview (one for each) and that renders it to the canvas at the bottom of the page (there is some distortion in the canvas, but that's not relevant). Right above the canvas is a result string that shows the status.

Repro steps: 

**On 22.x** 
Clicking "Screenshot webview 1" will render a screenshot into the canvas. The result string will very quickly say "waiting on webview 1..." before resolving to "Webview 1 rendered". 

If you click "screenshot webview 2" however, the string will remain "waiting on webview 2..." and the canvas empty.[1] Then, manually scroll the div containing the webviews such that the second webview is visible. At that point, the screenshot resolves and is drawn to the canvas, and the status string will resolve to "Webview 2 rendered". 

You can repeat this exercise by having the scrollarea such that the rightmost webview (nodejs.org) is visible, and clicking the button to screenshot webview 1 (electron.js.org). It likewise will only resolve after scrolling makes the webview visible.

**On 23.x**

The same behavior on 23.x will resolve in "Webview 2 rendered" being shown, but the canvas being empty because the image being rendered is a 0 by 0 transparant image. Only when you first scroll the webview into view will you be able to capture a screenshot.

[1] I have observed this to sometimes resolve straight away on the first click, but this behavior is visible in all subsequent clicks.

**Comment by 82318179** [comment]
I also encountered this problem. How on earth did I solve it? why didn't I see the solution?
