### ISSUE TITLE
[Bug]: build windows package in  electron 23.1.4

### ISSUE THREAD

**Issue by Kusou1** [electron/electron#37618]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.4

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

x64

### Last Known Working Electron version

18.2.3

### Expected Behavior

after electron-builder -mwl success without error

### Actual Behavior

• electron-builder  version=23.6.0 os=21.6.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=release/build/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sqlite3@5.1.2, v8-profiler-next@1.6.0 platform=darwin arch=arm64
  • rebuilding native dependency  name=v8-profiler-next version=1.6.0
  • rebuilding native dependency  name=sqlite3 version=5.1.2
  ⨯ cannot execute  cause=exit status 1
$ node-gyp rebuild
      CXX(target) Release/obj.target/profiler/src/cpu_profiler/cpu_profiler.o
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    
                    errorOut=gyp info it worked if it ends with ok
    gyp info using node-gyp@9.1.0
    gyp info using node@16.17.0 | darwin | arm64
    gyp info find Python using Python version 3.10.8 found at "/opt/homebrew/opt/python@3.10/bin/python3.10"
    gyp info spawn /opt/homebrew/opt/python@3.10/bin/python3.10
    gyp info spawn args [
    gyp info spawn args   '/Users/zhangshaohong/.nvm/versions/node/v16.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/zhangshaohong/my/trading-electron/app/release/app/node_modules/v8-profiler-next/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/zhangshaohong/.nvm/versions/node/v16.17.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/zhangshaohong/.electron-gyp/23.1.4/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/Users/zhangshaohong/.electron-gyp/23.1.4',
    gyp info spawn args   '-Dnode_gyp_dir=/Users/zhangshaohong/.nvm/versions/node/v16.17.0/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/Users/zhangshaohong/.electron-gyp/23.1.4/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/Users/zhangshaohong/my/trading-electron/app/release/app/node_modules/v8-profiler-next',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    In file included from ../src/cpu_profiler/cpu_profiler.cc:1:
    In file included from ../src/cpu_profiler/cpu_profiler.h:4:
    In file included from ../src/isolate_aware.h:4:
    In file included from ../../nan/nan.h:60:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/node.h:79:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8.h:24:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-array-buffer.h:12:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-local-handle.h:12:
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:461:30: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    SHARED_EXTERNAL_POINTER_TAGS(CHECK_SHARED_EXTERNAL_POINTER_TAGS)
                                 ^
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:461:30: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:461:30: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:461:30: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:461:30: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    PER_ISOLATE_EXTERNAL_POINTER_TAGS(CHECK_NON_SHARED_EXTERNAL_POINTER_TAGS)
                                      ^
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:462:35: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:645:61: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
        static_assert(kJSObjectType + 1 == kFirstJSApiObjectType);
                                                                ^
                                                                , ""
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:646:55: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
        static_assert(kJSObjectType < kLastJSApiObjectType);
                                                          ^
                                                          , ""
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:647:63: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
        static_assert(kFirstJSApiObjectType < kLastJSApiObjectType);
                                                                  ^
                                                                  , ""
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-internal.h:780:49: warning: 'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
        static_assert(tag != kExternalPointerNullTag);
                                                    ^
                                                    , ""
    In file included from ../src/cpu_profiler/cpu_profiler.cc:1:
    In file included from ../src/cpu_profiler/cpu_profiler.h:4:
    In file included from ../src/isolate_aware.h:4:
    In file included from ../../nan/nan.h:60:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/node.h:79:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8.h:24:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-array-buffer.h:13:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-object.h:9:
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-maybe.h:106:45: error: no template named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
      template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
                                           ~~~~~^~~~~~~~~~~~~~~~~~~~~
                                                is_lvalue_reference
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:910:29: note: 'is_lvalue_reference' declared here
    struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
                                ^
    In file included from ../src/cpu_profiler/cpu_profiler.cc:1:
    In file included from ../src/cpu_profiler/cpu_profiler.h:4:
    In file included from ../src/isolate_aware.h:4:
    In file included from ../../nan/nan.h:60:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/node.h:79:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8.h:24:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-array-buffer.h:13:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-object.h:9:
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-maybe.h:106:69: error: expected '(' for function-style cast or type construction
      template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-maybe.h:123:43: error: no template named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
    template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
                                         ~~~~~^~~~~~~~~~~~~~~~~~~~~
                                              is_lvalue_reference
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:910:29: note: 'is_lvalue_reference' declared here
    struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
                                ^
    In file included from ../src/cpu_profiler/cpu_profiler.cc:1:
    In file included from ../src/cpu_profiler/cpu_profiler.h:4:
    In file included from ../src/isolate_aware.h:4:
    In file included from ../../nan/nan.h:60:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/node.h:79:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8.h:24:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-array-buffer.h:13:
    In file included from /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-object.h:9:
    /Users/zhangshaohong/.electron-gyp/23.1.4/include/node/v8-maybe.h:123:67: error: expected '(' for function-style cast or type construction
    template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    21 warnings and 4 errors generated.
    make: *** [Release/obj.target/profiler/src/cpu_profiler/cpu_profiler.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Users/zhangshaohong/.nvm/versions/node/v16.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
    gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    gyp ERR! System Darwin 21.6.0
    gyp ERR! command "/Users/zhangshaohong/.nvm/versions/node/v16.17.0/bin/node" "/Users/zhangshaohong/.nvm/versions/node/v16.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/zhangshaohong/my/trading-electron/app/release/app/node_modules/v8-profiler-next
    gyp ERR! node -v v16.17.0
    gyp ERR! node-gyp -v v9.1.0
    gyp ERR! not ok 
error Command failed with exit code 1.
    
                    command=/Users/zhangshaohong/.nvm/versions/node/v16.17.0/bin/node /Users/zhangshaohong/.node/corepack/yarn/1.22.19/bin/yarn.js run install
                    workingDir=/Users/zhangshaohong/my/trading-electron/app/release/app/node_modules/v8-profiler-next
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Testcase Gist URL

_No response_

### Additional Information

_No response_

**Comment by sibelius** [comment]
how did you solved that?
