### ISSUE TITLE
[Bug]: pre-created window, the web content not disaply immediately

### ISSUE THREAD

**Issue by stefanJi** [electron/electron#37633]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.0

### What operating system are you using?

macOS

### Operating System Version

13.1 (22C65)

### What arch are you using?

x64

### Expected Behavior

When a pre-created window is displayed, the content of the web should be displayed immediately.

### Actual Behavior

Background:
In our project, the main window will be pre-created in the login window. When the main window is constructed, `show` will be set to false, and then the `show()` method of the main window will be called to display it after the login is completed.

In login window, will create the main window with hide
```typescript
const win = new BrowserWindow({
            //...
            autoHideMenuBar: true,
            frame: false,
            titleBarStyle: 'hidden',
            show: false
        })
```

When login success, show the main window
```typescript
win.show()
```

Error:
When the main window is displayed, the window will be blank first, and the content of the web will be displayed after about 1 to 2 seconds

**Comment by Bossesoneroom** [comment]
How to the bug[]()

**Comment by stefanJi** [comment]
Found the reason, our code blocked the main process
