### ISSUE TITLE
[Bug]: the main process crashed by getAppMetrics

### ISSUE THREAD

**Issue by ProvenceL** [electron/electron#37643]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.3

### What operating system are you using?

Windows

### Operating System Version

win32 10.0.19045

### What arch are you using?

ia32

### Expected Behavior

when i use app.getAppMetrics() to get some info, i want it can be use normal

### Actual Behavior

it Occasionally crash
![image](https://user-images.githubusercontent.com/20573253/226844106-66205918-dcdb-4bb2-bb1f-da2cbe065549.png)

**Comment by ProvenceL** [comment]
> Hello @ProvenceL. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

If I can reproduce the problem, I can also debug it to find the cause, because it happens sporadically not always, how can i make a example

**Comment by codebytere** [comment]
@ProvenceL we have no idea what code you're running when this error happens. We need a sample, as in the above:

> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

that we can attempt to triage with, otherwise we won't be able to proceed on this issue.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
