### ISSUE TITLE
isMinimized() / isMaximized() broken in tests on Linux/OSX

### ISSUE THREAD

**Issue by leshow** [electron/electron#3764]
On OSX and Linux, the value from isMinimized() and isMaximized() is not representative of the actual state that the window is in. I have a test suite that I ran on all platforms, the relevant parts are here:

as.spec.js:
```
...

    it('minimize', () => {
        as.minimize();

        expect(remote.getCurrentWindow().isMinimized()).toBeTruthy();
    });

    it('restore', () => {
        as.restore();

        expect(remote.getCurrentWindow().isMinimized()).not.toBeTruthy();
    });

    it('maximize', () => {
        as.maximize();

        expect(remote.getCurrentWindow().isMaximized()).toBeTruthy();
    });

    it('unmaximize', () => {
        as.unmaximize();

        //there is a bug on OSX where this doesn't work, so skip test on OSX
        if (os.platform() !== 'darwin') {
            expect(remote.getCurrentWindow().isMaximized()).not.toBeTruthy();
        }
    });

...
```

in the file `as`:
```
import { remote } from 'electron';

...

    minimize () {
        remote.getCurrentWindow().minimize();
    }

    maximize () {
        remote.getCurrentWindow().maximize();
    }

    restore () {
        remote.getCurrentWindow().restore();
    }
```

On windows, all of these tests succeed. 

On Linux the minimize/maximize tests fail, although the window does minimize properly (but fails to maximize). In the dev console window, I can invoke remote.getCurrentWindow().minimize() and isMinimized() and it returns true. However, maximize() doesn't make the window maximize nor does it change the value of isMaximized()

On OSX, the unmaximize() test fails and likewise remote.getCurrentWindow.maximize() does not seem to maximize a window when invoked from the dev window.

**Comment by etiktin** [comment]
What Electron version are you using?

**Comment by leshow** [comment]
the latest version 0.35.4

**Comment by petrfelzmann** [comment]
+1 we just discovered this bug in our production code.

**Comment by etiktin** [comment]
Can you reproduce it with v0.36?
@zcbenz do you mind adding an OS X label (the OP said it's also happening on OS X)?

**Comment by petrfelzmann** [comment]
Currently we have other difficulties to run our project in v0.36, so I cannot test this bug with the latest Electron version.

**Comment by leshow** [comment]
happening in both OSX and Linux.

**Comment by leethomas** [comment]
Have you tried calling the assertions within the vent listener? For example:

```
it 'minimizes', ->
  win.on 'minimized', ->
    expect(win.isMinimized()).toBeTruthy()

  win.minimize()
```

**Comment by lukeapage** [comment]
I have this problem too, with the latest code (36.7). It only effects osx.
I have a frameless always on top window. I create the browserWindow and keep a reference to it.
Then at some point later on after an ipcCall, I check browserWindow.isMaximized() and it returns true even though the window has never been maximised and is not maximised.

**Comment by lukeapage** [comment]
I just had a hunch and it turns out to be right. The value is wrong is the window is created with `resizable: false`. When I comment that out, isMaximized returns the right value for me in this scenario.

**Comment by leshow** [comment]
I also have `resizable: false` on my window.
