### ISSUE TITLE
[Bug]: BrowserWindow.removeBrowserView will crash the app if the browserView is destroyed 

### ISSUE THREAD

**Issue by guoqikai** [electron/electron#37642]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.4

### What operating system are you using?

macOS

### Operating System Version

13.0

### What arch are you using?

x64

### Expected Behavior

BrowserWindow.removeBrowserView should remove the browserView regardless of whether browserView is destroyed or not.

### Actual Behavior

The app will exit with code SIGSEGV.

### Testcase Gist URL

```Javascript
const {app, BrowserWindow, BrowserView} = require('electron')
const path = require('path')

async function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })
  const view = new BrowserView({
    preload: path.join(__dirname, 'preload.js')
  });

  view.webContents.on('destroyed', () => {
    mainWindow.removeBrowserView(view)
  });

  mainWindow.addBrowserView(view);
  view.setBounds({x:0, y:0, width:300, height:300});

  // and load the index.html of the app.
  await mainWindow.loadFile('index.html')

  await view.webContents.loadFile('index.html')

  view.webContents.close();


  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

**Comment by guoqikai** [comment]
gist: https://gist.github.com/guoqikai/ff949a40ec58488515e24ff22fa6cd3e.js

**Comment by codebytere** [comment]
@guoqikai that is not a Fiddle Gist - please provide one in the expected format. That cannot be loaded into [Fiddle](https://www.electronjs.org/fiddle)

**Comment by guoqikai** [comment]
@codebytere do you mean you can't open the link I provided or the code itself cannot be loaded?

**Comment by oold** [comment]
Fiddle gist for the original issue: https://gist.github.com/oold/87e07c1ac296bff2c01ac03d702fa2a6

**Comment by BABA983** [comment]
you can try remove the browserview first, and then destory the webcontents with a private method which not documentd  `(browserview.webContents as any).destroy?.();`
