### ISSUE TITLE
Perf problems with dns lookup

### ISSUE THREAD

**Issue by SofianHn** [electron/electron#3767]
I am investigating a perf problem in VSCode when connected to a network without internet https://github.com/microsoft/vscode/issues/1000

I narrowed down the issue to find that before `req.on("error")` callback gets executed some native code is causing the delay. 

Here is the simplist repro I could produce [perf-issue.js](https://gist.github.com/SofianHn/a877dab2020d8daf6608#file-perf-issue-js)

```
$ electron -v
v0.35.4

$ electron perf-issue.js
...
task called 2718 times, time since last executed 15
task called 2719 times, time since last executed 12
task called 2720 times, time since last executed 10
task called 2721 times, time since last executed 10
task called 2722 times, time since last executed 13
task called 2723 times, time since last executed 12
task called 2724 times, time since last executed 13
task called 2725 times, time since last executed 11
task called 2726 times, time since last executed 10
task called 2727 times, time since last executed 11
task called 2728 times, time since last executed 13
task called 2729 times, time since last executed 10
task called 2730 times, time since last executed 12
task called 2731 times, time since last executed 11
task called 2732 times, time since last executed 13
task called 2733 times, time since last executed 12
task called 2734 times, time since last executed 10010
lookup called  5
task called 2735 times, time since last executed 469
address ok
task called 2736 times, time since last executed 10010
lookup called  6
address ok
task called 2737 times, time since last executed 10010
lookup called  7
address ok
task called 2738 times, time since last executed 8397
task called 2739 times, time since last executed 1391
task called 2740 times, time since last executed 4290
lookup called  8
address ok
task called 2741 times, time since last executed 1372
task called 2742 times, time since last executed 2498
```

You can see after 4 or 5 calls to the dns lookup, `doTask` calls are being delayed by multiple seconds. This code runs fine on `node 4.1.1`, I ran it for minutes without noticing any perf issues. In electron it will take less than a min to hit this issue. I am testing on a a Mac. 

Any idea what's going on?

**Comment by zcbenz** [comment]
Our [node message loop integration](https://github.com/atom/electron/blob/master/atom/common/node_bindings_mac.cc#L46) relies on `uv_backend_timeout` to determine how long we should wait before the next event iteration, it seems that in the test case it is returning the wrong `timeout` after a few DNS lookups.

It could be a bug of libuv, but it also may because we are using `uv_backend_timeout` wrong, we are calling it in a new thread while it is not thread safe.

**Comment by SofianHn** [comment]
any tips on perf benchmarking in electron? I could not find something similar to `node --prof` switch. It was really tricky to get to a small repro.

**Comment by zcbenz** [comment]
For generic profiling you can use `Instruments` on OS X, I'm not sure how to do it on Windows. For JavaScript specific, you can just use devtools for renderer process, we haven't added the support for `--prof` switch so currently there is no good way for the main process.

**Comment by SofianHn** [comment]
ping @zcbenz any update here?

**Comment by zcbenz** [comment]
I hate to say this but I think we are encountering a bug of OS X here.

Under the hood Electron relies on `kevent` to get notified of the timer, in your perf-issue.js as example, we would call `kevent` with timeout of 10ms, so for every 10ms we would execute the timer. However when executing your code, it happens that sometimes `kevent` blocks for more than 10ms, even though we are passing 10ms as timeout, which results in large delay of the timer.

I can't explain why it can happen.

**Comment by codebytere** [comment]
https://github.com/manosim/gitify
