### ISSUE TITLE
[Bug]: preload is not loaded

### ISSUE THREAD

**Issue by ildella** [electron/electron#37677]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.10

### What arch are you using?

x64

### Expected Behavior

I am following [this docs](https://www.electronjs.org/docs/latest/tutorial/tutorial-preload) to have some javascript preloaded, in order to have an ipcRenderer intercept the `find-in-page` message sent by the main.js. 

The preload script is apparently never loaded, in fact I can never even see the console.info() message at start, while all other logs are visible. 

### Actual Behavior

Preload.js should at least print the console.info message at the very beginning. 

### Testcase Gist URL

https://github.com/ildella/chatgpt-electron/blob/make-find-in-page-work/main.js#L25

### Additional Information

The link to the PR should give anyone all the necessary info to see what is wrong. 
Thanks.

**Comment by Prinzhorn** [comment]
> in fact I can never even see the console.info() message at start, while all other logs are visible.

Are you looking in the right place? It should be in the dev tools console as it's part of the renderer.

I didn't try running your project, but there is no `remote` import (anymore), so the preload will definitely not work like that. So you should see your console log followed by an exception.

**Comment by ckerr** [comment]
> https://github.com/ildella/chatgpt-electron/blob/make-find-in-page-work/main.js#L25

Hi @ildella, this testcase requires electron-store and as @Prinzhorn pointed out also seems to be using remote which [was removed in v14](https://www.electronjs.org/docs/latest/breaking-changes#removed-remote-module).

Would it be possible to create a minimal, standalone testcase with [Electron Fiddle](https://www.electronjs.org/fiddle) that the Electron maintainers can use to try & reproduce the issue?

**Comment by ildella** [comment]
Here's the gist: https://gist.github.com/ildella/3b343f9005d54f5643caac81312c4413

So the preload did work indeed, I just see the logs in the dev tools and not on the terminal :+1: 

I shall open a new issue then as the `contents.findInPage()` have strange behavior and can't make it work. 

In the Fiddle, it does not actually perform the search as the results are not highlighted. 
The very same code on my app does that, but the search field continue to loose focus at every input.
