### ISSUE TITLE
[Bug]: The time zone obtained by Date() on electron22.0.0 is incorrect.

### ISSUE THREAD

**Issue by JiaFuGuo** [electron/electron#37688]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

ia32

### Last Known Working Electron version

13.6.0

### Expected Behavior

I hope that the time zone can be obtained after the version is updated.

### Actual Behavior

My computer's time zone is GMT+8. On electron 13.6.0, using devtools input Date(), the result is “Fri Mar 24 2023 11:27:54 GMT+0800”. On electron 22.0.0, using devtools input Date(), the result is “Thu Mar 23 2023 19:27:54 GMT-0800”.Normally is “Fri Mar 24 2023 11:27:54 GMT+0800”. That's a 16-hour time difference. Why did this happen? What did eletron do in the electron new version? And what can I do for fix it?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
