### ISSUE TITLE
[Bug]: IndexedDB security origin changed from `file://` to `file:///` in v23

### ISSUE THREAD

**Issue by matejkriz** [electron/electron#37702]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

macOS, Win10 too

### Operating System Version

macOS 13.0 (22A380)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.3.4

### Expected Behavior

origin should stay the same `file://`

### Actual Behavior

origin has been changed to `file:///` (three slashes) so user loose data in IndexedDB (because of the change of Security origin from `file://` to `file:///`)

### Testcase Gist URL

Electron 23.1.1:
https://gist.github.com/matejkriz/63cbc7d7efe468f779ac19106df1bce2

Electron 22.3.4:
https://gist.github.com/matejkriz/66085d9dc5305edec86a91ea9e12ec1a

### Additional Information

I tried to look into how the change could have happened or how to undo it, but I'm stuck.

**Comment by dsanders11** [comment]
Thanks for reporting this and helping to make Electron better!

Please use [Electron Fiddle](https://github.com/electron/fiddle) to create a standalone (no external dependencies) testcase and publish it as a [gist](https://gist.github.com), then link to it here.

- Even if you have a code snippet or a git repository that show the testcase, please put it in a gist. This lets maintainers triage issues more effectively. It also ensures that we're testing the exact same issue that you're seeing!

- Please avoid external dependencies in the test. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.

- If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). This lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug.

I'm adding the https://github.com/electron/electron/labels/blocked%2Fneed-repro label for this reason. After you make a test case, please link to the gist in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by MarshallOfSound** [comment]
@nornagon this sounds related to the protocol stuff you were talking about last week

**Comment by matejkriz** [comment]
standalone testcase:

Electron 23.1.1:
https://gist.github.com/matejkriz/63cbc7d7efe468f779ac19106df1bce2
<img width="799" alt="image" src="https://user-images.githubusercontent.com/3729633/227925599-9fa4e664-d883-4173-99c5-186215fe0eed.png">

Electron 22.3.4:
https://gist.github.com/matejkriz/66085d9dc5305edec86a91ea9e12ec1a
![image](https://user-images.githubusercontent.com/3729633/227925916-c3117d53-1cd1-41ed-876f-66324372b08c.png)

**Comment by dsanders11** [comment]
Went down a bit of a rabbit hole on this.

Confirmed to be upstream Chromium changes. Bisected on Windows 10 to [`03af843..aba7447`](https://chromium.googlesource.com/chromium/src/+log/03af843cf4360e9d73471de7e69e481d5ea5f010..aba7447208a5ceb5de6d694e8227d11a102f0b9c). None of those commits seem obviously related, and reviewing the diff for the whole range nothing looked particularly relevant. However, there's a DevTools frontend roll in that range which includes ["[IndexedDB] Remove security origin support for storage in frontend"](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3963110).

I think the bisected range is when the visual change to DevTools landed (seems incorrect that they left it called "Security origin" in the UI, based on that CL's name), but I think the functional change was in ["[IndexedDB] Prefer storage key over security origin"](https://chromium-review.googlesource.com/c/chromium/src/+/3918391).

Which leads me to believe the change is related to [Chromium's Storage Partitioning project](https://developer.chrome.com/en/docs/privacy-sandbox/storage-partitioning/), which is switching from keying storage (like IndexedDB) from being keyed on just the origin to also being keyed on the top-level site.

That's as far as I got for now, it's unclear to me if the change has any functional impact on Electron if you're not using iframes. Testing to see what the functional impact of this change is for `file:` protocol in Electron would be a good next step.

@matejkriz, is your application using iframes, and accessing the IndexedDB database from an iframe? Your application itself may be hitting the changes in how Chromium partitions the storage.

**Comment by matejkriz** [comment]
> @matejkriz, is your application using iframes, and accessing the IndexedDB database from an iframe? Your application itself may be hitting the changes in how Chromium partitions the storage.

No, we are not accessing the IndexedDB from an iframe.

The weird thing is, that even though Security origin has changed, the data hasn't disappeared – I just tested that the data are preserved between the versions.

**Comment by matejkriz** [comment]
So maybe it's not an issue at all in the end and can be closed?

**Comment by nornagon** [comment]
If the data is still accessible then I think this is working as intended and can be closed.

**Comment by matejkriz** [comment]
@dsanders11 Thank you and I'm very sorry for the false alarm!
