### ISSUE TITLE
[Bug]: BrowserView is blank if it's reattached to a window

### ISSUE THREAD

**Issue by zeeker999** [electron/electron#37709]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6.3

### What arch are you using?

x64

### Expected Behavior

The content of BrowserView should be displayed.

### Actual Behavior

The page is blank.

### Testcase Gist URL

https://gist.github.com/1bbc43fb01ad62d7b6edde5fde48de0c

### Additional Information

it seems disabling background throttling causes this issue.  And incrementCapturerCount() fixes it. However, there is no way to work around this issue for newer versions since electron 23 has removed the incrementCapturerCount.

**Comment by nornagon** [comment]
I checked and this is fixed with https://github.com/electron/electron/pull/35658, though I discovered some other issues with semitransparent background colors in that PR...

**Comment by zeeker999** [comment]
> I checked and this is fixed with #35658, though I discovered some other issues with semitransparent background colors in that PR...

I have just checked your PR, the issue is gone. Great work!

**Comment by codebytere** [comment]
Closing as the issue specified in this PR is addressed - let's open any transparency issues as a new issue.
