### ISSUE TITLE
[Bug]: browserWindow.setBackgroundColor() does not work without resizing the window

### ISSUE THREAD

**Issue by miniak** [electron/electron#37705]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6.3

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Calling `browserWindow.setBackgroundColor()` at any time works properly

### Actual Behavior

Calling `browserWindow.setBackgroundColor()` when the window is already visible (with setTimeout for example) does not work until the window is resized by the user or programmatically

### Additional Information

```
const {app, BrowserWindow} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  })

  setTimeout(() => {
    mainWindow.setBackgroundColor('#80ff0000')
  }, 1000)

  mainWindow.loadFile('about:blank')
}

app.whenReady().then(() => {
  createWindow()
})

app.on('window-all-closed', function () {
  app.quit()
})
```

**Comment by fivepointfire** [comment]
if we update the setTimeout function and make it force to redraw the content after setting the background color without updating (resizing the window) it should work

    ```
  setTimeout(() => {
    mainWindow.setBackgroundColor("#80ff0000");
    const [width, height] = mainWindow.getContentSize();
    mainWindow.setContentSize(width, height);
  }, 1000);
```

**Comment by miniak** [comment]
This seems to be fixing the issue
```patch
diff --git a/shell/browser/api/electron_api_browser_window.cc b/shell/browser/api/electron_api_browser_window.cc
index b92954814d..18af1c5186 100644
--- a/shell/browser/api/electron_api_browser_window.cc
+++ b/shell/browser/api/electron_api_browser_window.cc
@@ -330,8 +330,9 @@ void BrowserWindow::SetBackgroundColor(const std::string& color_name) {
   auto* rwhv = web_contents()->GetRenderWidgetHostView();
   if (rwhv) {
     rwhv->SetBackgroundColor(color);
-    static_cast<content::RenderWidgetHostViewBase*>(rwhv)
-        ->SetContentBackgroundColor(color);
+    auto* rwhv_base = static_cast<content::RenderWidgetHostViewBase*>(rwhv);
+    rwhv_base->SetContentBackgroundColor(color);
+    rwhv_base->RequestRepaintForTesting();
   }
   // Also update the web preferences object otherwise the view will be reset on
   // the next load URL call
```

**Comment by johnlindquist** [comment]
@miniak Do you have a recommended programmatic workaround until this is sorted?

**Comment by johnlindquist** [comment]
Also, the behavior is a little for me:
1. Use `setBackgroundColor()`
2. Background color successfully changes
3. Wait somewhere between 1-10 seconds (I don't know why it's random)
4. Color unsets

> Note: Using `getBackgroundColor()` will still print the correct value, but the color visually disappears from the window.
```js
  setInterval(() => {
    console.log(`Background color:`, win?.getBackgroundColor())
  }, 1000)
  ```


This is what it looks like on my machine. The only code I'm adding to a basic starter template:
```js
  setTimeout(() => {
    win?.setBackgroundColor(`rgba(255, 0, 0, 0.5)`)
    console.log(win?.getBackgroundColor())
  }, 3000)
  ```

https://user-images.githubusercontent.com/36073/232147357-04f79e1f-f316-490c-b7cc-5ed9d87d979d.mp4

**Comment by codebytere** [comment]
@johnlindquist it looks like you have some transparency being applied to the window - could you possibly attach a Fiddle repro?

**Comment by johnlindquist** [comment]
@codebytere Thanks for following up! 

Here's the fiddle gist:

https://gist.github.com/johnlindquist/9b5953b9d62ed635515b0275e24a50b6

I do need to wait ~7 seconds for it to happen. You can also trigger the bug by resizing the window.

Things I changed:
- transparent: true
- vibrancy: "hub"
- used setBackgroundColor with transparency
- added a `setInterval` so the dom updates (the bug didn't trigger if the dom wasn't updating, unless I resized it)

https://user-images.githubusercontent.com/36073/233182642-0ceb0104-ca98-4609-95cd-576689dfeb12.mp4

**Comment by codebytere** [comment]
I addressed something similar a while ago 🤔  https://github.com/electron/electron/pull/32593

I'll take a look soon!

**Comment by kongfu-cat** [comment]
some question.
here is my workaround: trigger resize
```js
const [width, height] = browserWin.getSize();
browserWin.setSize(width - 1, height);
browserWin.setSize(width, height);
```
