### ISSUE TITLE
[Feature Request]: Update Electron App with P2P Network

### ISSUE THREAD

**Issue by 826541814** [electron/electron#37716]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Before my app had a large number of users, I used Electron-autoUpdater with OSS to distribute software upgrade packages.  But when the number  of users exceeded 10,000 level, distributing the upgrade package consumed a lot of OSS resources( even through I use exe.blockmap) and incurs expensive costs

### p2p
I found that Microsoft also used a p2p solution to download system upgrade packages to avoid high fees and to solve the problem of network availability in some ares, 
I wonder if you will consider this new proposal

### Alternatives Considered

We have also considered controlling the version information API at the business level to mitigate the problem fo concentrated bursts of user update traffic. 
However, it cannot reduce the total traffic of requests, nor can it be controlled very precisely.

**Comment by MarshallOfSound** [comment]
The autouodater in electron supports reading the files from disk, so you can load the update payloads however you want and then point electrons auto updater to the on disk location.
