### ISSUE TITLE
[Bug]: Doesn't work with TypeScript

### ISSUE THREAD

**Issue by s1nistr4** [electron/electron#37713]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.0

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Expected Behavior

For TypeScript to work with Electron just like every other npm package

### Actual Behavior

If there is a way to get Electron to work with TypeScript, it is way too complicated and not explained in the docs, I don't have this issue with any other npm package except for electron

1. Install Electron and run ```npm install electron; npm install --save-dev electron```
2. Setup my tsconfig.json

```json
{
  "compilerOptions": {
    "target": "ES6",
    "module": "ES6",
    "rootDir": "./src",
    "outDir": "./",
    "removeComments": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "strict": true,
    "skipLibCheck": true,
    "noImplicitAny": false
  },
  "include": ["./src"],
  "exclude": ["node_modules"]
}
```

3. Make a basic Electron app

```typescript
import { app, BrowserWindow } from "electron"

function createWindow():any {
    const win = new BrowserWindow({
        width: 480,
        height: 480,
        title: "Hello world"
    })

    win.loadFile("index.html")

    return win
}

app.whenReady().then(() => {
    createWindow()
})
```

4. Run ```tsc --watch```
5. It says "Cannot find module 'electron'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?"

Already a severe issue, Electron is not detected as a package when using TypeScript. Whatever, I set "moduleResolution" to "node" in my tsconfig.json and the error goes away. Now I run "npm start" and get a new error:

```
SyntaxError: Cannot use import statement outside a module
```

???

After Google searching, I found that you have to put "type": "module" to get around this. Okay, so I add that to my package.json, so I did that, ran "npm start" again and saw

```
require() of ES Module ./app/index.js from .//app/node_modules/electron/dist/resources/default_app.asar/main.js not supported. Instead change the require of index.js in ./app/node_modules/electron/dist/resources/default_app.asar/main.js to a dynamic import() which is available in all CommonJS modules.
```

After Google searching, no solution to this came up. Idk if I'm the only human to encounter this error or if people just don't use Electron with TypeScript.

So whatever, using Electron with vanilla JS works fine, but when you add TypeScript it just doesn't work. If there is a way to work around this then can it at least be added to the official Electron docs?

**Comment by MarshallOfSound** [comment]
Your issue here I believe is your tsconfig, electron works fine with typescript, our tests are typescript and we have definition tests too.

Your set module to ES6 which is not the default and changes the default module resolution setting as well 

Ref: https://www.typescriptlang.org/tsconfig#module

If you remove your both the module and moduleResolution settings in your tsconfig and remove "type: module" from your package.json as well everything will work as expected.
