### ISSUE TITLE
[Feature Request]: Disable GPU/Disable hardware acceleration/Software rendering mode

### ISSUE THREAD

**Issue by SkybuckFlying** [electron/electron#37727]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

AMD Radeon GPU on this laptop is broken. However the intel processor iCore 5 has an integrated GPU.

Only way to use it is to disable hardware acceleration with provided apis.

That way the IGPU is used.

So I request fiddle to find a way to try and incorporate this functionality.

I will be available for testing this future.

You can also test it yourself on windows, by simplying disabling your GPU, only do this if you are sure your CPU has an integrated GPU as fallback option ! ;)

### Proposed Solution

Disable GPU/Disable hardware acceleration options should be added.

### Alternatives Considered

No alternative, besides buying new PC, waiting for new processors to arrive in country ! ;)

**Comment by miniak** [comment]
https://github.com/electron/electron/blob/main/docs/api/app.md#appdisablehardwareacceleration
