### ISSUE TITLE
[Bug]: "npm install electron" throws an error in the new version of Node.js

### ISSUE THREAD

**Issue by tisoz** [electron/electron#37735]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.0

### What operating system are you using?

Windows

### Operating System Version

windows 11 and windows 10

### What arch are you using?

x64

### Last Known Working Electron version

23.2

### Expected Behavior

He should have installed successfully without any issues.

### Actual Behavior

I have conducted the following tests on two different computers, including a new one. I tried versions of Node.js ranging from 12 to 18, but the issue persists. The NPM registry source I used is the official source: https://registry.npmjs.org/.

Here is my version information:
`Node.js version: 18.14.2`
`NPM version: 9.6.2`

I received the same error message on both Windows 10 and Windows 11 during the tests. The error message is shown below.

When I tried running the command provided by the official website, I received the following error message:
`npm install --save-dev electron --verbose`

result : 
```
412 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 827ms
413 timing auditReport:getReport Completed in 829ms
414 silly audit report {}
415 timing auditReport:init Completed in 0ms
416 timing reify:audit Completed in 829ms
417 info run electron@23.2.0 postinstall { code: 1, signal: null }
418 timing reify:rollback:createSparse Completed in 62ms
419 timing reify:rollback:retireShallow Completed in 0ms
420 timing command:install Completed in 1270086ms
421 verbose stack Error: command failed
421 verbose stack     at ChildProcess.<anonymous> (C:\Users\tisoz\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
421 verbose stack     at ChildProcess.emit (node:events:513:28)
421 verbose stack     at maybeClose (node:internal/child_process:1091:16)
421 verbose stack     at Socket.<anonymous> (node:internal/child_process:449:11)
421 verbose stack     at Socket.emit (node:events:513:28)
421 verbose stack     at Pipe.<anonymous> (node:net:322:12)
422 verbose pkgid electron@23.2.0
423 verbose cwd F:\albion_radar
424 verbose Windows_NT 10.0.19045
425 verbose node v18.15.0
426 verbose npm  v9.6.2
427 error code 1
428 error path F:\albion_radar\node_modules\electron
429 error command failed
430 error command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
431 error ReadError: The server aborted pending request
431 error     at IncomingMessage.<anonymous> (F:\albion_radar\node_modules\got\dist\source\core\index.js:809:31)
431 error     at Object.onceWrapper (node:events:627:28)
431 error     at IncomingMessage.emit (node:events:525:35)
431 error     at origin.emit (F:\albion_radar\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
431 error     at IncomingMessage._destroy (node:_http_incoming:224:10)
431 error     at _destroy (node:internal/streams/destroy:109:10)
431 error     at IncomingMessage.destroy (node:internal/streams/destroy:71:5)
431 error     at TLSSocket.socketCloseListener (node:_http_client:462:11)
431 error     at TLSSocket.emit (node:events:525:35)
431 error     at node:net:322:12
432 verbose exit 1
433 timing npm Completed in 1270133ms
434 verbose unfinished npm timer reify 1679983321221
435 verbose unfinished npm timer reify:build 1679983334344
436 verbose unfinished npm timer build 1679983334345
437 verbose unfinished npm timer build:deps 1679983334345
438 verbose unfinished npm timer build:run:postinstall 1679983334352
439 verbose unfinished npm timer build:run:postinstall:node_modules/electron 1679983334352
```

The complete detailed log file is here : 
[2023-03-28T06_02_01_185Z-debug-0.log](https://github.com/electron/electron/files/11086451/2023-03-28T06_02_01_185Z-debug-0.log)

**Comment by MarshallOfSound** [comment]
Are you using an http proxy?

Make sure you enable proxy support of electron/get if so --> https://github.com/electron/get#proxies

**Comment by tisoz** [comment]
> 您是否在使用 http 代理？
> 
> 确保启用 electron / get 的代理支持，如果是这样 --> https://github.com/electron/get#proxies

yes , I even used proxifier to force the use of a proxy, as well as global proxy. According to the error message, it doesn't seem like a download failure, but rather an issue with the callback in the underlying library.
