### ISSUE TITLE
[Bug]: performance regression in electron 24

### ISSUE THREAD

**Issue by Kilian** [electron/electron#37736]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0-beta.5

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Last Known Working Electron version

23.2.0

### Expected Behavior

web content loads as quickly in 24 as it does in 23

### Actual Behavior

web contents load significantly slower in 24.

### Testcase Gist URL

https://gist.github.com/Kilian/d897c0c8f20642f319443c2da73316a7

### Additional Information

The test case has a button and three webview. When you click the button the webviews load a URL, and the time between clicking the button and all webviews having loaded is shown below the button.

On 23.2.0, the first load is ~600ms and subsequent loads are ~150ms. On 24 the initial load is ~1500ms and subsequent loads are ~800ms. This holds true for 24.0.0-alpha.1 through to 24.0.0-beta.5. I haven't checked the 24 nightlies.

**Comment by Kilian** [comment]
A possible clue from the console output, 24 has a bunch of these:
```bash
[658975:0328/105017.323576:ERROR:interface_endpoint_client.cc(695)] Message 6 rejected by interface blink.mojom.WidgetHost
[658975:0328/105017.333093:ERROR:interface_endpoint_client.cc(695)] Message 7 rejected by interface blink.mojom.WidgetHost
[658975:0328/105017.337427:ERROR:interface_endpoint_client.cc(695)] Message 3 rejected by interface blink.…mojom.WidgetHost
[658975:0328/105017.421815:ERROR:interface_endpoint_client.cc(695)] Message 3 rejected by interface blink.mojom.Widget
[658975:0328/105017.514998:ERROR:interface_endpoint_client.cc(695)] Message 6 rejected by interface blink.mojom.WidgetHost
[658975:0328/105017.516434:ERROR:interface_endpoint_client.cc(695)] Message 7 rejected by interface blink.mojom.WidgetHost
[658975:0328/105017.517734:ERROR:interface_endpoint_client.cc(695)] Message 3 rejected by interface blink.mojom.Widget
```

**Comment by Kilian** [comment]
Testing with the above fiddle on macOS doesn't show the same results, so it seems this is localised to linux.

**Comment by ckerr** [comment]
(Tested on Ubuntu 22.04.2)

| Electron Version | 1st Load | 2nd Load | "Message Rejected" |
|---|---|---|---|
| v24.0.0-beta.5 | 1256 | 956 | Yes |
| v24.0.0-alpha.1 | 1030 | 722 | Yes |
| v24.0.0-nightly.20230209 | 934 | 741 | Yes |
| v24.0.0-nightly.20230206 | 1108 | 781 | Yes |
| v24.0.0-nightly.20230203 | 982 | 985 | Yes | 
| v24.0.0-nightly.20230202 | 666 | 638 | No |
| v24.0.0-nightly.20230125 | 702 | 700 | No |
| v24.0.0-nightly.20221201 | 619 | 648 | No |
| v23.2.0 | 909 | 805 | No |

So looks like this was introduced in https://github.com/electron/electron/compare/v24.0.0-nightly.20230202...v24.0.0-nightly.20230203 which happily only has two commits between them:

1. a Chromium roll, which is _usually_ the prime suspect -- except the other commit is
2. https://github.com/electron/electron/pull/37109 which sounds pretty sus in the context of this bug report.

CC @miniak for opinion

**Comment by Prinzhorn** [comment]
See https://github.com/electron/electron/issues/37454
