### ISSUE TITLE
[Bug]: Use getUserMedia to get the video media stream in portrait, and the obtained video stream is a landscape result

### ISSUE THREAD

**Issue by wangwenwen130** [electron/electron#37748]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.14.0

### What operating system are you using?

Windows

### Operating System Version

window 7  intel(R) Celeron(R) cpu 3855U @ 1.60GHz 1.60GHz

### What arch are you using?

x64

### Last Known Working Electron version

18.3.8

### Expected Behavior

![微信图片_20230329142720](https://user-images.githubusercontent.com/48354328/228449388-2206a4e3-ca49-4ec5-8577-3cea620a3c66.png)

### Actual Behavior

![微信图片_20230329143052](https://user-images.githubusercontent.com/48354328/228449413-1b947b81-e50c-4503-929e-38ba4cfc6e3c.png)

**Comment by wangwenwen130** [comment]
// test 
 
 navigator.mediaDevices
    .getUserMedia({
      audio: false,
      video: {
        width: 500,
        height: 400,
      }
    })
    .then(function (stream) {
      let body = document.getElementsByTagName('body')[0]
      let video = document.createElement('video')
      video.srcObject = stream
      video.style.width = '500px'
      video.style.height = '400px'
      body.appendChild(video)
      video.onloadedmetadata = function () {
        video.play()
      }
    })
    .catch((err) => {
      console.log(err)
      console.log("没有开启摄像头权限或浏览器版本不兼容.")
    });

**Comment by nornagon** [comment]
does this work in Chrome on desktop? i feel like this is a mobile-only API.

**Comment by wangwenwen130** [comment]
> does this work in Chrome on desktop? i feel like this is a mobile-only API.
On the same system, chrome displays correctly, but electron displays incorrectly

**Comment by nornagon** [comment]
Okay, thanks for the confirmation. Electron 16 is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines), can you try again on a supported version of Electron?

**Comment by wangwenwen130** [comment]
> Okay, thanks for the confirmation. Electron 16 is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines), can you try again on a supported version of Electron?

the  same as on the  electron 18

**Comment by wangwenwen130** [comment]
Good news, I found the question, please see the attachment for details
[Use getUserMedia to get the video media stream in portrait^J and the obtained video stream is a landscape result.pdf](https://github.com/electron/electron/files/11133948/Use.getUserMedia.to.get.the.video.media.stream.in.portrait.J.and.the.obtained.video.stream.is.a.landscape.result.pdf)

**Comment by codebytere** [comment]
@wangwenwen130 Electron 18 is no longer supported either. As @nornagon, please check [currently supported versions](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) and confirm the problem exists there in order for us to continue triage.

**Comment by wangwenwen130** [comment]
> @wangwenwen130 Electron 18 is no longer supported either. As @nornagon, please check [currently supported versions](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) and confirm the problem exists there in order for us to continue triage.
The problem remains in version 21 、22，In zhe test I found a new problem in  v23 v24 , Unable to start the program in window 7 after installation. please see the attachment for details
![微信图片_20230406093501](https://user-images.githubusercontent.com/48354328/230251146-22b38dbb-adca-439e-ad3c-c33916a637e3.jpg)

**Comment by wangwenwen130** [comment]
> 



> @wangwenwen130 Electron 18 is no longer supported either. As @nornagon, please check [currently supported versions](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) and confirm the problem exists there in order for us to continue triage.

The problem remains in version 21 、22，In zhe test I found a new problem in v23 v24 , Unable to start the program in window 7 after installation. please see the attachment for details
微信图片_20230406093501

**Comment by wangwenwen130** [comment]
@nornagon @codebytere Can you fix this problem
