### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by luokunman** [electron/electron#37749]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Is there any way to sign in with apple on the Electron?
sign in with apple is required for app store review, but relevant content is not found in documents and community materials, please help me

### Proposed Solution

Expect an interface similar to inAppPurchase.

### Alternatives Considered

*

### Additional Information

![image](https://user-images.githubusercontent.com/41885648/228463650-231abf29-b5ca-4889-a2dd-e65ac3e5f9a1.png)

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
