### ISSUE TITLE
[Bug]: Window is resized when clicking notifications

### ISSUE THREAD

**Issue by ibahnasy** [electron/electron#37750]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.10

### What arch are you using?

x64

### Expected Behavior

It should show the Electron app windows is it was before it get minimized to sent to the background.

### Actual Behavior

It show the app windows not maximized as it was.

### Additional Information

Steps to reproduce

  1. Electron app window is opened in the background as maximized.
  2. A new message is received and display a gnome-shell notification.
  3. Click on the notification.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
