### ISSUE TITLE
[Bug]: Error: Command 'git rev-list -n 1 HEAD' returned non-zero exit status 128

### ISSUE THREAD

**Issue by hailangljb** [electron/electron#37768]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22-x-y

### What operating system are you using?

Other Linux

### Operating System Version

Debian GNU/Linux 10 (buster)

### What arch are you using?

x64

### Last Known Working Electron version

22-x-y

### Expected Behavior

i according to the https://www.electronjs.org/docs/latest/development/build-instructions-linux

### Actual Behavior

ljb@yisu-641d35059ae14:~/temp/electron/src/electron$ gclient sync -f
Updating depot_tools...
using /tmp/goma_ljb as tmpdir
INFO: creating cache dir (/tmp/goma_ljb/goma_cache).
compiler_proxy is not running
/home/jb/temp/electron/.gclient_entries missing, .gclient file in parent directory /home/jb/temp/electron might not be the file you want to use.
________ running 'python3 src/electron/script/patches-mtime-cache.py generate --cache-file src/electron/patches/mtime-cache.json --patches-config src/electron/patches/config.json' in '/home/jb/temp/electron'
Using existing mtime cache for patches

src (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00] Finished running: git config remote.origin.url
----------------------------------------
Error: Command 'git rev-list -n 1 HEAD' returned non-zero exit status 128 in /home/jb/temp/electron/src
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

### Additional Information

first question to github ,may something dont know.

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
