### ISSUE TITLE
[Bug]: "Bundle identifier mismatch" error on APN token register

### ISSUE THREAD

**Issue by JoeHossam** [electron/electron#37799]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

request to APNS should succeed.

### Actual Behavior

request to APNS fails:
```
[Error: 13 NSOSStatusErrorDomain {
    NSDebugDescription = "Bundle identifier mismatch";
}]
```

### Testcase Gist URL

https://gist.github.com/JoeHossam/d4b585c21f78752a5bc6f90a38a27b4e

### Additional Information

I want to provide a push notification certificate.
I want to know where does the code read the appId from. so I can set it correctly
Please provide more details in the documentation.
Thank you.

**Comment by JoeHossam** [comment]
https://gist.github.com/JoeHossam/d4b585c21f78752a5bc6f90a38a27b4e

the gist contains the basic fiddle template and I just called the `pushNotifications.registerForAPNSNotifications` function

**Comment by TheBudgetMan** [comment]
Any update on this issue? I would like to get started with push notifications on MacOS, but there don't seem to be any documentation on it.

**Comment by JoeHossam** [comment]
Unfortunately no, the closest solution that I've reached is to simply implement the notification logic yourself, by registering a daemon into the device that listens to some server this will make it work for all OSs, that being said I haven't really tested it.

**Comment by JoeHossam** [comment]
Bump

**Comment by JCBsystem** [comment]
any news on this ?

**Comment by JoeHossam** [comment]
Sadly no, I wish they fix it and make a solution for windows too.

**Comment by JCBsystem** [comment]
im kind of stuck 
if i add     <key>com.apple.developer.aps-environment</key>
    <string>development</string>
    
    the app wont start after signing and if i remove it i get same error as you 
    
    this is a mas build 
    
    i gusse its back to the external old electron-push lib

**Comment by JCBsystem** [comment]
i got it to work . the provison profilen needs cert 
add certs den build  whit the entitlements above

**Comment by ddenis-k** [comment]
@JCBsystem Could you please elaborate on this and explain what exactly you did to make it work?

**Comment by JCBsystem** [comment]
@ddenis-k 
sure 
i use it in  sign mas build but i guess the key is that it need to be a signed build with the right entitlements and provisionprofile 

you need these in you entitlements
<key>com.apple.developer.aps-environment</key>
   <string>development | production</string>

and when you create your provisionprofile make sure you have push certs created to your app identity
even if you dont use them to send push messages with (i use a apn pushkey)
think this was what made it work for me 
<img width="898" alt="Screenshot 2023-11-30 at 09 51 12" src="https://github.com/electron/electron/assets/31064157/12f20950-0342-416f-912e-c2c24277f22b">

then it shuld work 
let me know if you need more help

**Comment by ddenis-k** [comment]
I got this working! Thank you @JCBsystem.

**Comment by jarvis-zgp** [comment]
How was this problem solved?

**Comment by jarvis-zgp** [comment]
I want to know where does the code read the appId from. so I can set it correctly
