### ISSUE TITLE
[Bug]: Electron[4169:1464466] +[CATransaction synchronize] called within transaction

### ISSUE THREAD

**Issue by sprout2000** [electron/electron#37793]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.1

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

unknown

### Expected Behavior

Not getting this error message.

### Actual Behavior

"Electron[4169:1464466] +[CATransaction synchronize] called within transaction" appears in console.

**Comment by PrematureDeer8** [comment]
Did you find a solution?

**Comment by robertmassman** [comment]
I have the same issue too. Running macOS and Intel arch.

**Comment by a4xrbj1** [comment]
Same issue here, MacOS 13.4.1 (c) (22F770820d) on Apple M2 chip
