### ISSUE TITLE
[Feature Request]: Show support message on Windows7/8/8.1 with electron >= 23

### ISSUE THREAD

**Issue by cp-sumi-k** [electron/electron#37819]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I was on electron 19. Now I want to end support for windows versions < 10. For that, I have upgraded the electron version to 24.0.0.

After upgrading, the app is not opening on windows7/8/8.1. Instead of it, I want to show a dialog like `Windows 7 is not supported`

### Proposed Solution

Provide a feature to show dialog on app ready, when the windows version is less than 10.

### Alternatives Considered

Currently, I am running the app on electron 22, In which I am getting OS version on the app launching and showing the alert accordingly

**Comment by codebytere** [comment]
@cp-sumi-k it's relatively straightforward to determine the os type and information with Node.js' `os` module, e.g with a combination of `os.platform()`, `os.type()` and `os.release()` and so isn't something that would make sense to do in Electron's core API. I recommend you use Node.js to do this.
