### ISSUE TITLE
[Feature Request]: BrowserWindow.isMenuBarVisible won't work anymore but has no document.

### ISSUE THREAD

**Issue by sprout2000** [electron/electron#37827]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Since v24, BrowserWindow.isMenuBarVisible has been changed to BrowserWindow.menuBarVisible, yet there is no documentation of this breaking change.

### Proposed Solution

BrowserWindow.menuBarVisible should be mentioned as a breaking change.

### Alternatives Considered

It should also be mentioned that BrowserWindow.isMenuBarVisible is obsolete.

### Additional Information

I spent a good half hour wrestling with a bug that didn't make sense before I noticed this change.

**Comment by dsanders11** [comment]
[`BrowserWindow.isMenuBarVisible()`](https://www.electronjs.org/docs/latest/api/browser-window#winismenubarvisible-windows-linux) has not been removed, and is not obsolete. [`menuBarVisible`](https://www.electronjs.org/docs/latest/api/browser-window#winmenubarvisible-windows-linux) is a boolean property. If you want to check the value you can use either.

I'm going to close this issue, but feel free to ping me if I've misunderstood.

**Comment by sprout2000** [comment]
@dsanders11 
Thanks for getting back to me, and I apologize for my misunderstanding.

I don't know why, but the reason for the misunderstanding is that my app has been working with **`BrowserWindow.isMenuBarVisible`** instead of [`BrowserWindow.isMenuBarVisible()`](https://www.electronjs.org/docs/latest/api/browser-window#winismenubarvisible-windows-linux).

You are correct, and I can confirm that neither is obsolete.
Thank you so much.

**Comment by dsanders11** [comment]
@sprout2000, you're welcome! Glad you figured it out. 🙂
