### ISSUE TITLE
[Bug]: `app.dock.hide()` is not working after call `browserWindow.setVisibleOnAllWorkspaces(true)`

### ISSUE THREAD

**Issue by 1zilc** [electron/electron#37832]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 13.3

### What arch are you using?

x64

### Last Known Working Electron version

23.1.4

### Expected Behavior

 `app.dock.hide()` can be used normally

### Actual Behavior

When I create a BrowserWindow after the ready event and execute the following code
```typescript
  console.log(app.dock.isVisible());
  app.dock.hide();
  console.log(app.dock.isVisible());

  mainWindow.setVisibleOnAllWorkspaces(true);

  console.log(app.dock.isVisible());
  app.dock.hide();
  console.log(app.dock.isVisible());
```
Obtain the following execution results
<img width="470" alt="image" src="https://user-images.githubusercontent.com/44715458/230081350-0fe552af-8e0f-4996-958c-fb151f8aa7b1.png">

`app.dock.hide()` is not working after call `browserWindow.setVisibleOnAllWorkspaces(true)`. The same problem also occurs in 23.2.x, It seems to be related to this https://github.com/electron/electron/pull/37599

**Comment by codebytere** [comment]
@1zilc that's a result of a known limitation of the underlying API - if `app.dock.hide()` is called within one second of a previous call it will not succeed. The change was necessary to fix another more critical bug.

**Comment by 1zilc** [comment]
@codebytere Although it is not possible to call `app.dock.hide()` within one second due to some serious issues, `setVisibleOnAllWorkspaces(true)` to break the dock's original visible state, which I believe is also a serious bug

**Comment by 1zilc** [comment]
I tried to avoid this issue by setting skipTransformProcessType. Thank you for your answer

**Comment by rmdashrfv** [comment]
@1zilc Does this call for a setTimeout? I'm having the same issue

**Comment by clicktodev** [comment]
im encountering the same problem. closing the window right after it opens causes the dock.hide command to do nothing

**Comment by clicktodev** [comment]
i fixed this by delaying dock.hide calls in a setTimeout

```ts
// --- Throttled dock show/hide ---
// macOS app.dock.hide() silently fails if called within ~1s of dock.show().
// These helpers serialize calls with a minimum gap.
let lastDockShowTime = 0;
let pendingHideTimer: ReturnType<typeof setTimeout> | null = null;

function showDock(): Promise<void> {
  if (pendingHideTimer) {
    clearTimeout(pendingHideTimer);
    pendingHideTimer = null;
  }
  lastDockShowTime = Date.now();
  return app.dock?.show() ?? Promise.resolve();
}

function hideDock(): void {
  if (pendingHideTimer) {
    clearTimeout(pendingHideTimer);
    pendingHideTimer = null;
  }

  const elapsed = Date.now() - lastDockShowTime;
  const MIN_GAP = 1100;

  if (elapsed >= MIN_GAP) {
    if (app.dock?.isVisible()) app.dock.hide();
  } else {
    pendingHideTimer = setTimeout(() => {
      pendingHideTimer = null;
      if (app.dock?.isVisible()) app.dock.hide();
    }, MIN_GAP - elapsed);
  }
}

```
