### ISSUE TITLE
[Bug]: the macOS open-file event is not fired in case of filenames with diacritics

### ISSUE THREAD

**Issue by Skywalker13** [electron/electron#37831]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

broken with electron 24, 22, 20, 18, 16 and 14

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.3

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

N/A

### Expected Behavior

The `open-file` event must be fired with files that are using diacritics, like for example `"épée.txt"` where there are two `é`.

### Actual Behavior

The event is fired only with file using US style filenames (without diacritics).

### Testcase Gist URL

https://github.com/Skywalker13/diacritics-open-file-bug

### Additional Information

You can use the repository (testcase) in order to reproduce the bug. It's very easy to experiment. The problems appear with macIntel and mac M1.

Here a GIF of this bug (based on the testcase):

<https://github.com/Skywalker13/diacritics-open-file-bug>

![](https://raw.githubusercontent.com/Skywalker13/diacritics-open-file-bug/master/demo.gif)

---

Related to:
- https://github.com/electron/electron/issues/14029
- https://github.com/electron/electron/issues/4403
- https://github.com/electron/electron/issues/9925

**Comment by SamLebarbare** [comment]
Can electron handle this problem ?

https://stackoverflow.com/questions/6153345/different-utf8-encoding-in-filenames-os-x/6153713#6153713

If the event is fired in electron and some checks are made about the file to open, perhaps electron must normalize filename before avoid the opening ?

**Comment by codebytere** [comment]
@SamLebarbare unfortunately no -

> some checks are made about the file to open,

this isn't what happens. The function that gets called, [`application:openFile:`](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428612-application), is called by Apple. We don't do any file processing or sanitization beforehand.

**Comment by Skywalker13** [comment]
Thank you for the investigations around this nasty macOS bug, it's very appreciated.

Some interesting information (for the posterity) available with the `convmv` tool that is useful to convert filename into the appropriate encoding.
- https://j3e.de/linux/convmv/man/#Filesystem-issues
