### ISSUE TITLE
[Bug]: navigator.bluetooth.getAvailability() does not update, and no availabilitychanged events thrown

### ISSUE THREAD

**Issue by NbrTDB** [electron/electron#37830]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### What arch are you using?

x64

### Expected Behavior

When using the following snippets (see below) the expectation is that messages will appear in Electron's console whenever the system's BLE modem is removed/reattached, or Windows' Bluetooth is disabled/enabled.

```javascript
navigator.bluetooth.getAvailability()
.then(isBluetoothAvailable => {
  console.log(`> Bluetooth is ${isBluetoothAvailable ? 'available' : 'unavailable'}`);
});

if ('onavailabilitychanged' in navigator.bluetooth) {
  navigator.bluetooth.addEventListener('availabilitychanged', function(event) {
    console.log(`> Bluetooth is ${event.value ? 'available' : 'unavailable'}`);
  });
}
```

### Actual Behavior

Instead, if BLE was available when Electron is launched, the output from `navigator.bluetooth.getAvailability()` is just `true` at all times, regardless of actual availability. If you launch Electron with the modem already unplugged or disabled, then it always returns `false` regardless of availability even if the modem is subsequently plugged back in and/or Windows Bluetooth re-enabled in settings.

Meanwhile in all cases, the `availabilitychanged` event is never thrown.

### Testcase Gist URL

https://googlechrome.github.io/samples/web-bluetooth/availability.html

### Additional Information

Should Electron be started with a lack of Bluetooth availability, attempts to use web-bluetooth API calls like `navigator.bluetooth.requestDevice()` will fail with `Uncaught (in promise) DOMException: Bluetooth adapter not available.` even when it has in fact been plugged in since Electron was started, and Windows indicating that Bluetooth is up and running.

It seems to me like Electron is only making a singular check during start-up as to whether BLE is available and thereafter it never checks again?

This may be relevant, but the same behaviour is also observed in Chrome - I do wonder if it's not something that can be fixed on Electron end.

**Comment by codebytere** [comment]
> the same behaviour is also observed in Chrome - I do wonder if it's not something that can be fixed on Electron end.

Unfortunately yes - we subclass some bluetooth related logic but this is something that upstream is responsible for. You're welcome to file a [crbug](https://crbug.com) and see what they say though.
