### ISSUE TITLE
[Bug]: `setVisibleOnAllWorkspaces` triggers `blur` event

### ISSUE THREAD

**Issue by davej** [electron/electron#37875]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.2 (22D49)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.3.3

### Expected Behavior

Calling `win.setVisibleOnAllWorkspaces(true)` should not trigger the blur event on the associated window.

### Actual Behavior

Calling `win.setVisibleOnAllWorkspaces(true)` will trigger the `blur` event even though the window does not lose focus.

I bisected based on different Electron versions and I was able to conclude that this bug was introduced in `22.3.4`.

### Testcase Gist URL

https://gist.github.com/davej/0a0f34f5be40cbca3146f50f7901da91

**Comment by davej** [comment]
Still an issue.

**Comment by jacksman** [comment]
+1

**Comment by mikeyyyzhao** [comment]
Still an issue on 27.0.0

**Comment by zane-atomus** [comment]
Having the same problem on 27.0.2

**Comment by davej** [comment]
Still an issue.

**Comment by geovie** [comment]
Setting `skipTransformProcessType` to true could be a workaround for this.

It looks like the change was introduced in https://github.com/electron/electron/pull/37599 not sure if it was intentional to have this side effect
