### ISSUE TITLE
[Bug]: chrome.scripting API not implemented for extensions using Manifest V3

### ISSUE THREAD

**Issue by jonluca** [electron/electron#37876]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0

### What operating system are you using?

macOS

### Operating System Version

Monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Extensions using the `chrome.scripting` API should work properly. Manifest v3 should work properly. A React-specific bug is here https://github.com/electron/electron/issues/36545

### Actual Behavior

With the following code:

```
import installExtension, { REACT_DEVELOPER_TOOLS } from 'electron-devtools-installer';

const { app } = require('electron');

app.whenReady().then(() => {
    installExtension(REACT_DEVELOPER_TOOLS)
        .then((name) => console.log(`Added Extension:  ${name}`))
        .catch((err) => console.log('An error occurred: ', err));
});
```

You get the following errors/issues:

```
[44297:1203/150155.162121:ERROR:extensions_browser_client.cc(62)] Extension Error:
  OTR:     false
  Level:   1
  Source:  manifest.json
  Message: Service worker registration failed. Status code: 15
  ID:      fmkadmapgofadopljbjfkapdkoienihi
  Type:    ManifestError
[44297:1203/150155.162205:ERROR:extensions_browser_client.cc(62)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
  Message: Uncaught TypeError: Cannot read properties of undefined (reading 'registerContentScripts')
  ID:      fmkadmapgofadopljbjfkapdkoienihi
  Type:    RuntimeError
  Context: chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
  Stack Trace: 
    {
      Line:     107
      Column:   1
      URL:      chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
      Function: (anonymous function)
    }
```

**Comment by nosferatu500** [comment]
Same here. Electron 24.0.0 (MacOS 13.3 (amd64))

**Comment by jonluca** [comment]
I published https://www.npmjs.com/package/electron-extension-installer as a temporary workaround for some common extensions, including React, but this really should be fixed on electrons end. (source code [here](https://github.com/jonluca/electron-extension-installer))


```typescript
import { installExtension, REACT_DEVELOPER_TOOLS } from "electron-extension-installer";

app.on("ready", async () => {
  await installExtension(REACT_DEVELOPER_TOOLS, {
    loadExtensionOptions: {
      allowFileAccess: true,
    },
  });
});
```

**Comment by codebytere** [comment]
This is not a bug - we don't currently support that [per documentation](https://github.com/electron/electron/blob/e3b7c3024f6f70155efb1022b691954280f983cb/docs/api/extensions.md#L1).

**Comment by nbabanov** [comment]
@codebytere Is the support planned in the roadmap? React Dev tools are an important asset in the Dev's toolbelt.

**Comment by stelladraco27** [comment]
With Manifest V3, scripting is needed. All of my dev tools dont work.

**Comment by stelladraco27** [comment]
@jonluca Is there any way you could add support for "recoilize" or "reactime"? Those are the two extensions that are now unsupported with V3.

**Comment by codebytere** [comment]
hey all - i'm actively working on this and should have a flurry of PRs to improve Manifest v3 support up within 2-3 weeks at most.

**Comment by stelladraco27** [comment]
Thank you!

**Comment by nosferatu500** [comment]
@codebytere Hi! Thank you for your hard work on this, but it looks like we still have a runtime error with react dev tools. 

In my case with Electron 28 it shows next:

```
[39416:1102/145854.069162:ERROR:extensions_browser_client.cc(69)] Extension Error:
  OTR:     false
  Level:   2
  Source:  
  Message: Error in event handler: TypeError: Cannot read properties of undefined (reading 'setIcon')
    at setExtensionIconAndPopup (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js:1:1614)
    at handleReactDevToolsHookMessage (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js:1:3438)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js:1:6759
  ID:      fmkadmapgofadopljbjfkapdkoienihi
  Type:    RuntimeError
  Context: 
  Stack Trace: 
    {
      Line:     0
      Column:   1
      URL:      
      Function: (anonymous function)
    }
```

btw, it works (in general) but internal timeline tab is totally black for me. idk if this might be the reason.

Thank you in advance!

**Comment by codebytere** [comment]
@nosferatu500 ah dang yes i know what that is - it's not an issue with `chrome.scripting` but rather `chrome.action`. It's on my short-term todo list to address!

**Comment by rendomnet** [comment]
> @nosferatu500 ah dang yes i know what that is - it's not an issue with `chrome.scripting` but rather `chrome.action`. It's on my short-term todo list to address!
 **Permission 'scripting' is unknown or URL pattern is malformed**

So Electron is not supporting Devtools? Or what? What is update on this issue?

**Comment by nosferatu500** [comment]
This should be fixed already. I haven't used the extension for a while, but it was fixed the last time I used it.

**Comment by codebytere** [comment]
@nbabanov what's broken? I loaded the latest version of DevTools on latest Electron and see:

<img width="1512" alt="Screenshot 2024-02-29 at 11 13 00 AM" src="https://github.com/electron/electron/assets/2036040/d0d7a821-f1b2-44e0-afe6-55dd7d94a9fe">

**Comment by nosferatu500** [comment]
Hi @codebytere ! Can you check react dev tools v5.0 please? Looks like it unable to load again (4.27 has no issues)

**Comment by codebytere** [comment]
@nosferatu500 yes, the above comment is using 5.0 and works

**Comment by nosferatu500** [comment]
@codebytere yep, 5.0 not working for me at all. 

```
(Use `Electron --trace-warnings ...` to show where the warning was created)
[91044:0308/100700.690484:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[91044:0308/100700.690537:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
[91044:0308/100702.144480:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
```

Electron 29.1.0

and as always, thank you!

**Comment by codebytere** [comment]
@nosferatu500 to clarify - is the dev tools extension not showing up? or are you just seeing those errors in console?

**Comment by nosferatu500** [comment]
@codebytere Both. The dev tools extension (v5.0.0_2) not showing up AND I seeing those errors in console.

**Comment by codebytere** [comment]
@nosferatu500 just tried with `v5.0.2_3`:

<img width="1169" alt="Screenshot 2024-03-11 at 12 14 12 PM" src="https://github.com/electron/electron/assets/2036040/6e08e6b6-9dac-44a5-9277-41813f0110ab">

**Comment by nosferatu500** [comment]
@codebytere  ~you're a wizard, Harry~ Still broken on my end (v5.0.2_3)

**Comment by Jurin** [comment]
Exact same issue here but with Vue Devtools. Electron v29.2.0.

Output after attempting to open devtools. The extension seems to load ok, but it's not appearing in devtools.

Same issue with  electron-devtools-installer (3.2.0) or manually.

```
[24844:0422/101748.810:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wa
sn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[24844:0422/101748.903:ERROR:CONSOLE(2)] "Electron renderer.bundle.js script failed to run", source: node:electron/js2c/
renderer_init (2)
[24844:0422/101748.903:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.ite
rator))", source: node:electron/js2c/renderer_init (2)
```

**Comment by codebytere** [comment]
@tbrkollar no promises on fix timeline but i'll take a look before the week ends :)

**Comment by Elawen-Carl** [comment]
> @tbrkollar no promises on fix timeline but i'll take a look before the week ends :)

hi @codebytere 
When using vue devtools on electron 28.3.0 the project does not have this tool option, tried to ask the solution of gpt, still did not solve this small problem.
![image](https://github.com/electron/electron/assets/81508974/f04599a1-c686-4ffe-b1de-d46c9c350dc9)
![image](https://github.com/electron/electron/assets/81508974/8b3dc888-307b-4fd4-97b9-475f7e60211c)

**Comment by tbrkollar** [comment]
> @tbrkollar no promises on fix timeline but i'll take a look before the week ends :)

Hi @codebytere, 
I hope you are doing well. 

I tried to fix it, but the vue tab cannot load. When I check the installation with ses.getAllExtensions() everything is all right. It returns an array that contains vue-tool extension object.  I tried to use electron-devtools-installer and also load extension manually. 

Do you have any news? or idea?
Thanks

**Comment by lnovelli** [comment]
Hi, has anyone had any luck in using the [Angular DevTools extension](https://chromewebstore.google.com/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh)? I'm testing version 1.0.37 with Electron 36.3.1, I'm able to load the extension, but when clicking on the Angular tab in the Chrome DevTools, it says "Angular application not detected" (see pic below).

![Image](https://github.com/user-attachments/assets/2a128007-9646-4609-878c-9ea16b707374)

this is how i'm loading the extension:

```
const angularDevToolsPath = path.join(__dirname, '../../../../../..', 'AngularDevTools', '1.0.37_0');
console.log('angularDevToolsPath', angularDevToolsPath);
if (fs.existsSync(angularDevToolsPath)) {
  console.log('LOADING ANGULAR DEVTOOLS', angularDevToolsPath);
  const extension = await session.defaultSession.extensions.loadExtension(angularDevToolsPath);
  console.log('Angular DevTools extension loaded:', extension.name, extension.id, extension.version);
}
```

If it can help, in the main process console log I also see the following errors:

```
[27462:0703/181752.126119:ERROR:CONSOLE:1] "Uncaught (in promise) SyntaxError: Unexpected token 'H', "HTTP/1.1 4"... is not valid JSON", source: devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@d2c6cdeb9e24770f5aad73d7bd59bc4e265ecf88/&can_dock=&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (1)
[27462:0703/181752.205245:ERROR:CONSOLE:2] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[27462:0703/181752.205281:ERROR:CONSOLE:2] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
[27462:0703/181753.805420:ERROR:CONSOLE:2] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[27462:0703/181753.805458:ERROR:CONSOLE:2] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
```

Any help would be greatly appreciated! 🙏🏼

**Comment by Bravo123** [comment]
If you have no other options, try using double loading.
I don‘t know why. but it's actually useful to me..
```
await app.whenReady();
  const ses = session.defaultSession
  try {
    // 加载插件 - 路径指向插件的文件夹
    const extensionPath = getExtensionPath(); // path.join( __dirname, '..', 'src', 'extensions', 'chrome-mv3-prod' )
    await ses.loadExtension( extensionPath )
    await ses.loadExtension( extensionPath )
    console.log( '扩展加载成功:' )
  } catch ( error ) {
    console.error( '扩展加载失败:', error )
  }

  this.createMainWindow();
```
