### ISSUE TITLE
[Bug]: Windows 10 snap assist not working when BrowserWindow is set to transparent: true

### ISSUE THREAD

**Issue by McWoahs** [electron/electron#37888]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I have created an app that is frameless with a transparent background. I have done this so I can set the app border-radius to be rounded. I have also created my own AppTopBar component with all the necessary drag/maximize/minimize functions. I'd like to be able to drag the window to the edge of the screen and have the Windows Snap Assist feature work with my application.

### Actual Behavior

As it is now, with 'transparent: true' for the BrowserWindow, the windows snap assist feature does not detect the application.
When I set 'transparent: false' the windows snap assist works as intended.

### Additional Information

Current Electron 'main.js' file:

https://github.com/McWoahs/just-stream/blob/674c2ded4419e71e3146ae5f6939183c872182db/main.js

**Comment by MaksymPylypenko** [comment]
Having the same issue
