### ISSUE TITLE
[Bug]: Notification can't show app's name when the app is at C:/Program Files

### ISSUE THREAD

**Issue by tangan666** [electron/electron#37885]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

Windows

### Operating System Version

Window10

### What arch are you using?

x64

### Last Known Working Electron version

23.1.0

### Expected Behavior

when my app is  at  C:/program files . I want  the Window10 Notification just show my app's name and the content;

### Actual Behavior

but actually , Window 10 Notification show my app's path like 'C:/program files/myApp/app.exe  ' ,that's weird. If  my app is not  at 'C:/Program Files' , the Notification will show my app's name correctly.
![471680897165_ pic](https://user-images.githubusercontent.com/37064975/230669151-090e70f2-3a7e-4e6d-be33-a1813aa7a612.jpg)
![481680897166_ pic](https://user-images.githubusercontent.com/37064975/230669158-675fb56c-610a-4327-90cb-a0449a52c3c6.jpg)

### Additional Information

I have setAppUserModelId(process.execPath) and I have created  shortcuts  for both situation.

**Comment by piyush09-05** [comment]
I am beginner in Open Source Contribution, can I get some help in building electron on my local machine, I have forked the repository, what should I do now?

**Comment by tangan666** [comment]
> I am beginner in Open Source Contribution, can I get some help in building electron on my local machine, I have forked the repository, what should I do now?

**Comment by tangan666** [comment]
> I am beginner in Open Source Contribution, can I get some help in building electron on my local machine, I have forked the repository, what should I do now?
follow this
https://www.electronjs.org/zh/docs/latest/tutorial/quick-start

**Comment by tangan666** [comment]
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/37064975/230781788-78fdae4e-a31d-4738-b4d8-e55a623336c0.png">
I follow this document and  setAppUserModelId(process.execPath) and I have created shortcuts
I package my program by electron-packager

**Comment by codebytere** [comment]
@tangan666 we need this issue to be demonstrated on a supported version of Electron in order to proceed with triage. See [supported lines](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) for details - this issue will be closed in 10 days otherwise.

**Comment by tangan666** [comment]
> @tangan666 we need this issue to be demonstrated on a supported version of Electron in order to proceed with triage. See [supported lines](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) for details - this issue will be closed in 10 days otherwise.

    "electron": "^23.1.0",

**Comment by tangan666** [comment]
use  this version 23.1.0, and follow the document about Notifications,  and setAppUserModelId(process.execPath),package it , make a shortcuts, move the app to C:/Program Files , then you will find the  problem

**Comment by tangan666** [comment]
> @tangan666 we need this issue to be demonstrated on a supported version of Electron in order to proceed with triage. See [supported lines](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) for details - this issue will be closed in 10 days otherwise.

use this version 23.1.0, and follow the document about Notifications, and setAppUserModelId(process.execPath),package it , make a shortcuts, move the app to C:/Program Files , then you will find the problem

**Comment by tangan666** [comment]
[package.json.txt](https://github.com/electron/electron/files/11254700/package.json.txt)

**Comment by tangan666** [comment]
`const { app, BrowserWindow, Notification } = require('electron')

function createWindow () {
  const win = new BrowserWindow({
    width: 800,
    height: 600
  })

  win.loadFile('index.html')
}

const NOTIFICATION_TITLE = 'Basic Notification'
const NOTIFICATION_BODY = 'Notification from the Main process'

function showNotification () {
  setInterval(()=>{
  new Notification({ title: NOTIFICATION_TITLE, body: NOTIFICATION_BODY }).show()},2000)
}


app.whenReady().then(()=>{
app.setAppUserModelId(process.execPath);
createWindow();}).then(showNotification)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})`
my code in main.js

**Comment by tangan666** [comment]
If I move my app to system files like C:/Program Files , and create a start menu shortcut , notification won't show it's name exactly.
If I move my app to C:/xxx , D:/xxx, and create a  start menu shortcut, everything works properly, notification show it's name exactly.

**Comment by 1339240789** [comment]
you can user app.setAppUserModelId('your app name')
