### ISSUE TITLE
[Bug]:  App logo are having a blue background on Windows Notifications.

### ISSUE THREAD

**Issue by huangruiqi** [electron/electron#37893]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.2.1

### What operating system are you using?

Windows

### Operating System Version

windows 10、windows11

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

clear blue background

### Actual Behavior

<img width="332" alt="企业微信截图_16811150198313" src="https://user-images.githubusercontent.com/23137020/230873929-bd6273d9-197d-4c11-a976-e70426b8968b.png">

**Comment by Anshul-target** [comment]
@huangruiqi could you elaborate the issue please.I am new to open source

**Comment by huangruiqi** [comment]
> @huangruiqi could you elaborate the issue please.I am new to open source
When I call the new Notification pop-up notification, I find that the application logo of the notification has a blue background by default. How to remove it? No other native applications have this problem.

**Comment by huangruiqi** [comment]
> @huangruiqi could you elaborate the issue please.I am new to open source

When I call the new Notification pop-up notification, I find that the application logo of the notification has a blue background by default. How to remove it? No other native applications have this problem.
