### ISSUE TITLE
[Feature Request]: Disable mouse loading icon on autoUpdater.checkForUpdates()

### ISSUE THREAD

**Issue by juxnpxblo** [electron/electron#37929]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Every time autoUpdater.checkForUpdates() is called, the loading icon is showed on the mouse cursor.

If you have an application that is constantly checking for updates, lets say every minute (or even 5 minutes), it can get annoying for the user.

### Proposed Solution

Just disable it if possible. 

### Alternatives Considered

none

### Additional Information

electron version: 22.2.0
OS: Windows 11

screenshots (first one is mine with custom skin, the second is the default one I guess):

![cursor_loading](https://user-images.githubusercontent.com/82245700/231194130-b1c32951-b6db-4ece-aaeb-398caefb3b49.jpeg)

![cursor_loading_default](https://user-images.githubusercontent.com/82245700/231194257-effa9798-cdf8-4e79-9150-f2cd97ea8e17.png)

**Comment by juxnpxblo** [comment]
oh of course @codebytere 

electron 22.2.0 on Windows 11

it's a bit tricky to get cursor on screenshot on Windows so I took a picture, I use a custom skin so I get this:

![cursor_loading](https://user-images.githubusercontent.com/82245700/231186584-55c3f354-64cc-4ad0-a249-4ce2e730b95f.jpeg)

I guess the default one looks like this: 

![cursor_loading_default](https://user-images.githubusercontent.com/82245700/231186645-8e1e9bce-92b3-46b8-9038-1038e5f9a14b.png)

everytime autoUpdater.checkForUpdates() is called

**Comment by codebytere** [comment]
Looked a bit more into this, and sadly it's not really something we have control over at the Electron level. It's not really disable-able via API, and so it's something that end users will need to disable or control via system settings.
