### ISSUE TITLE
[Bug]: Electronjs setting power plan to idledisable = 1, causing significant CPU usage / excessive power consumption

### ISSUE THREAD

**Issue by KThreeMTPO** [electron/electron#37932]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro, 21H2

### What arch are you using?

x64

### Expected Behavior

When starting electronjs apps, there is something triggering CPU usage to peg to 100% due to a change in windows power plan configuration.  I would expect when an electron app starts up, that it would not make system level changes to the pc.

### Actual Behavior

https://www.youtube.com/watch?v=avEG8qPg8F8
This video shows the behavior with discord, which is where I originally discovered this behavior before testing and verifying it occurs in other electron applications.

When starting an electron app, windows has it's powerplan changed to set the flag IDLEDISABLE to 1, which causes windows to consume more CPU cycles preventing idling, but this has a negative impact on performance, power consumption, and potentially life of the CPU.

### Testcase Gist URL

https://gist.github.com/010f2f5b743ad986de19a79549fbda95

### Additional Information

I was able to verify this on multiple versions of electron. even though the video only shows Discord.

**Comment by KThreeMTPO** [comment]
uploaded a repro that on my machine will repro the issue with just loading url: discord.com/login
it does not occur when loading html locally with the default hello world example, and some sites don't seem to have the issue.  Regardless, wouldnt expect any website to result in electron changing the powerplan for windows.

**Comment by KThreeMTPO** [comment]
![image](https://user-images.githubusercontent.com/99424087/231211311-1b49b69e-cf78-4630-9787-c2660ffab02e.png)
from running electron fiddle here's the eventviewer log showing it setting the powerplan, it sets it to the same plan currently applied (balanced) as defined here: https://learn.microsoft.com/en-us/windows/win32/power/power-policy-settings

but for some reason the idledisable flag is getting set to 1.

**Comment by VerteDinde** [comment]
Hey @KThreeMTPO, can you confirm if this behavior is also happening in Chrome itself when you visit the Discord page? Does it similarly change the system flag?

**Comment by KThreeMTPO** [comment]
it does not happen in Chrome, but was able to reproduce in edge after your suggestion.  Perhaps a bug with chromium?

**Comment by KThreeMTPO** [comment]
Bump

**Comment by KThreeMTPO** [comment]
bump
