### ISSUE TITLE
[Tracking Issue] Direct Sockets API

### ISSUE THREAD

**Issue by GrapeGreen** [electron/electron#37936]
Dear Electron team,

I'm a Chrome developer working on the [Direct Sockets API](https://github.com/WICG/direct-sockets) that provides lower-level socket communications on the Web.

Since Electron is partially based on Chromium, I'd be very curious to hear your thoughts on the API in general as well as the opportunity to introduce this API to Electron (from what I understand, this might be achieved without putting in too much effort from the maintainers). The API is currently in a limited developer trial, so there's plenty of room for incorporating new feedback and altering the API shape.

- [Explainer](https://github.com/WICG/direct-sockets/blob/main/docs/explainer.md)
- [Spec](https://wicg.github.io/direct-sockets/)
- [Example](https://github.com/GoogleChromeLabs/telnet-client): Telnet Client over Direct Sockets

I would be happy to discuss further if you are interested!

**Comment by nornagon** [comment]
One thought that might be relevant: it could make sense to implement a polyfill that allowed using the Direct Sockets API from Node.JS, by wrapping the underlying Node APIs. That would allow implementing isomorphic libraries that would work in Electron, Node.JS or in an IWA.
