### ISSUE TITLE
[Bug]: window.open with windowname does not work correctly

### ISSUE THREAD

**Issue by t57ser** [electron/electron#37949]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.1

### What operating system are you using?

Windows

### Operating System Version

10.0.19042

### What arch are you using?

x64

### Expected Behavior

when a page opens a window with a frame name and afterwards a cross-domain navigation happens and a new window with the same frame name is opened then this should result in 2 distinct windows
Each domain should have its own "context" of window names (chrome behavior)
Additionally, window.open with names is not seperated by partition

### Actual Behavior

No new window is opened for different domains

- be on youtube.com
- open devtools
- var w = window.open("http://www.microsoft.com", "test")
- navigate to a different domain (in the youtube window)
- open devtools
- var w = window.open("http://www.microsoft.com", "test")

**Comment by pushkin-** [comment]
weird, that behavior isn't intuitive to me. If you're using the same window name, why doesn't the same window get navigated. I can repro your behavior even when not navigating to a different domain. In my case, I'm seeing the `window.name` not to get set to the name I passed in: `window.open("https://google.com", "a")`

**Comment by t57ser** [comment]
@pushkin- 
Google is not a good use case, it has a COOP header set that does not allow a child window to be used. You will also see that after creation the window has the closed property set to true.

every window should have its own "context" in regards to window names. otherwise it can happen that you have multiple websites using the same window. even in case of same domain, chrome will open new windows, which makes sense otherwise you would get weird behavior if you have the same website open twice.
Regarding cross-domain, that is an obvious security issue

**Comment by gpetrov** [comment]
Bump

**Comment by t57ser** [comment]
bump

**Comment by t57ser** [comment]
bump
