### ISSUE TITLE
[Bug]: Application failed to start in Win7

### ISSUE THREAD

**Issue by y489436672** [electron/electron#37945]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.0

### What operating system are you using?

Windows

### Operating System Version

win7

### What arch are you using?

x64

### Last Known Working Electron version

14.2.9

### Expected Behavior

The application can run normally

### Actual Behavior

![image](https://user-images.githubusercontent.com/19664101/231405391-8ff9338e-904f-4d63-b513-5c69881ddebd.png)

**Comment by wma2001** [comment]
I encountered the same error,How did you solve it?

**Comment by wy2022** [comment]
I have the same problem. How can I solve it

**Comment by wma2001** [comment]
> I have the same problem. How can I solve it
Please see this release change and you can try to downgrade version in your application.[https://releases.electronjs.org/release/v23.0.0](url)

**Comment by wma2001** [comment]
Please see this release change and you can try to downgrade version in your application.[https://releases.electronjs.org/release/v23.0.0](url)

**Comment by y489436672** [comment]
Update Electron version to 21.4.4.
Higher versions no longer support Win7.
更新electron版本到21.4.4
更高的版本已经不支持win7

**Comment by y489436672** [comment]
@wy2022 @wma2001
