### ISSUE TITLE
feature request: header and footer content for PDF

### ISSUE THREAD

**Issue by bjrmatos** [electron/electron#3795]
hi! i work on [jsreport](https://github.com/jsreport/jsreport), an open source reporting platform, currently we use phantomjs as the primary way to generate PDF from html/css/js but [we would love to replace phantomjs with electron](https://github.com/bjrmatos/jsreport-electron-pdf).

in order to replace phantomjs, the only feature missing in electron is the ability to specify a header and footer for the PDF.

[the way that phantomjs lets specify header and footer](http://phantomjs.org/api/webpage/property/paper-size.html) is something like this:

``` js
page.paperSize = {
  header: {
    height: "1cm",
    contents: phantom.callback(function(pageNum, numPages) {
      return "<h1>Header <span style='float:right'>Page " + pageNum + " / " + numPages + "</span></h1>";
    })
  },
  footer: {
    height: "1cm",
    contents: phantom.callback(function(pageNum, numPages) {
      return "<h1>Footer <span style='float:right'>Page " + pageNum + " / " + numPages + "</span></h1>";
    })
  }
}
```

as you see, phantomjs lets us specify `content` and `height` for the header and footer respectively (don't know if the `height` value is an important value for internal purposes), that feature give us the ability to cover a basic use case for reports.. generate content for all pages that knows the current page and total pages.

in the case of electron, i think this feature can be added as an option for `webContents.printToPDF` (is possible to add it to `webContents.webContents.print` too?):

``` js
currentWindow.webContents.printToPDF({
  pageSize: 'A4',
  header: {
    height: "1cm", // if this value is not important for internal pdf generation, i think you can get ride of it..
    content: function(pageNum, numPages, callback) {
      // if callback is called with nothing or an object that has an error property the pdf generation will fail, just like `protocol.registerFileProtocol` handler's callback behaviour
      callback("<h1>Header <span style='float:right'>Page " + pageNum + " / " + numPages + "</span></h1>");
  },
  footer: {
    height: "1cm",
    content: function(pageNum, numPages, callback) {
      // if callback is called with nothing or an object that has an error property the pdf generation will fail, just like `protocol.registerFileProtocol` handler's callback behaviour
      callback("<h1>Footer <span style='float:right'>Page " + pageNum + " / " + numPages + "</span></h1>");
    }
  }
}, function(err, data) {
  // pdf with header and footer content is generated
}); 
```

what do you think? anything i can help? i don't have c++ skills but i will like to help test this feature.

**Comment by zcbenz** [comment]
Chrome doesn't support custom headers and footers when exporting PDF, so we have to hack into the PDF code to add this feature, which can be very hard.

**Comment by astoilkov** [comment]
Chrome has a checkbox in its Print Preview for enable/disable footer and headers. Is it possible to expose that as Boolean option in Electron?

**Comment by vkarpov15** [comment]
+1

**Comment by klappy** [comment]
+1

**Comment by shd101wyy** [comment]
+1
https://github.com/shd101wyy/markdown-preview-enhanced/issues/57
Thanks!

**Comment by alnour-altegani** [comment]
*any change in the feature ?*
I have desktop application with many reports and I need to set custom header and footer in the report with electron  .
the alternative is to use wkhtmltopdf it is work fine .  but add another 40mb file just for reports is not good . the only difference is the full customization for print html to pdf .

**Comment by jkostrz** [comment]
+1

**Comment by vkarpov15** [comment]
I used electron (via nightmare) to generate the PDF for [my last ebook](http://es2015generators.com/) and ended up just doing a nasty loop to put page numbers at the bottom with hardcoded offsets.

```javascript
    <script type="text/javascript">
      var start = 3400;
      var delta = 1681;
      for (var i = 2; i < 52; ++i) {
        var height = start + (i - 1) * delta;
        document.write('<div class="page-num" style="top:' + height + 'px;">' + (i - 1) + '</div>');
      }
    </script>
```

**Comment by ziegfried** [comment]
+1

**Comment by amoshg** [comment]
+1

**Comment by ykou** [comment]
+1

**Comment by missing1984** [comment]
+1, because of lacking the header and footer we have to use phantom in a big project.. it'll be great to have it support in electron!

**Comment by glouie** [comment]
+1

**Comment by zcbenz** [comment]
I'm merging this to #7849 since it is a superset of this issue.

**Comment by bjrmatos** [comment]
@zcbenz thnks i'll keep and eye on the issue

**Comment by LqdBcnAtWork** [comment]
[Electron API - Print To PDF](https://www.electronjs.org/docs/latest/api/web-contents#contentsprinttopdfoptions)

The .printToPDF method has a headerFooter option which could be used to at least attach page numbers.

Unfortunately as far as I can tell it's no custom header or footer, and both are required at the same time which basically allows this suggestion with a bit more features than enable/disable:

> Chrome has a checkbox in its Print Preview for enable/disable footer and headers. Is it possible to expose that as Boolean option in Electron?

Being able to create a fully custom header/footer would be a huge boon for my own project too.

At least I'll have accurate page numbers with the headerFooter option.
