### ISSUE TITLE
[Feature Request]: support navigator.bluetooth.requestLEScan() - advertisementreceived events never occur

### ISSUE THREAD

**Issue by NbrTDB** [electron/electron#37964]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### What arch are you using?

x64

### Expected Behavior

Per Web Bluetooth spec, when calling `navigator.bluetooth.requestLEScan()` what happens (on Chrome, for instance) is a deluge of `advertisementreceived` events containing detected advertising packets comprising device MAC address, identity, detected primary service(s) UUIDs and other such details.

### Actual Behavior

if you've set `app.commandLine.appendSwitch(`enable-experimental-web-platform-features`, `true`);` in the main process, then you can call `navigator.bluetooth.requestLEScan()` but the Promise never resolves and no `advertisementreceived` events are thrown on either the renderer or main processes, as far as I can tell.

### Additional Information

Example snippet that works in Chrome here:
```javascript
navigator.bluetooth.addEventListener(`advertisementreceived`, (event) => {
  console.log(`Received:`, event);
});
navigator.bluetooth.requestLEScan({
  acceptAllAdvertisements: true,
  active: true
}).then((data) => {
  console.log(`Got data`, data);
});
```

The `requestLEScan()` mechanism is a much preferred way of detecting and identifying nearby BLE devices vs the old `navigator.bluetooth.requestDevice()` mechanism, which only acquires a list of MAC addresses and names, and subsequently requires connecting to each detected device to filch primary services, GATT profiles, etc.

You can define filters for `navigator.bluetooth.requestDevice()` but if you have more than one potential service or device to support, you have no way to quickly identify which MAC address is which without first connecting to them all to query their services. Whereas you can see that information at a glance with `requestLEScan()`.

I understand that one issue for `requestLEScan()` may be that the normal Chrome permissions popup is not bypassed like the device chooser is for `requestDevice()`. Chrome also doesn't fire any `advertisementreceived` events until you click "Allow" on the popup window, and we wouldn't want said popup on our Electron app where we want to do everything in our own UI. 

Perhaps the same mechanism can be created such that calls to `requestLEScan()` bypass that popup and can immediately start triggering `advertisementreceived` packets?

**Comment by ianupam001** [comment]
may i resolve thi issue??

**Comment by ianupam001** [comment]
This error message typically indicates that the navigator.bluetooth.requestLEScan() method is not supported in the user's web browser or device.

navigator.bluetooth.requestLEScan() is part of the Web Bluetooth API, which is not supported by all browsers and devices. To use this API, the user's browser must support it, and the user's device must have Bluetooth capabilities.

You can check if the Web Bluetooth API is supported in the user's browser using the following code:

`if ('bluetooth' in navigator) {
  navigator.bluetooth.requestDevice({ acceptAllDevices: true })
    .then(device => {
      console.log(`Connected to device: ${device.name}`);
      // Device is now connected, perform operations on the device
    })
    .catch(error => {
      console.error(`Error connecting to device: ${error}`);
    });
} else {
  console.error('Web Bluetooth API is not supported on this browser.');
}
`
