### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by deguich** [electron/electron#37963]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Squared menu on main window or rounded but with a smaller radius.

### Actual Behavior

Menu corner are rounded. That is strange, no other apps on win11 have rounded corners.

Exemple from another user on stackoverflow :
https://stackoverflow.com/questions/73350918/electronjs-rounded-menu-corners

**Comment by Pushyajain** [comment]
Hello, I am new to open source, I think that I can solve this bug, so if no one is working on this issue please assign it to me

**Comment by deguich** [comment]
Thks for your response.
OK, Chromium has rounded corner menu too, but I think this kind of settings should be the choice of developpers (or should be globally fixed by OS, not the case for windows).
