### ISSUE TITLE
[Bug]: Electron Apps Not Using Correct Timezone (America/Mexico_City)

### ISSUE THREAD

**Issue by RickSlash84** [electron/electron#37972]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.3

### What operating system are you using?

Other Linux

### Operating System Version

Manajaro DE Plasma 5.27.4

### What arch are you using?

x64

### Expected Behavior

I expected that Electron apps on my Manjaro Linux KDE system would automatically use the correct system timezone (America/Mexico_City) without any issues. This would result in the apps displaying the correct local time and handling any time-related functions accurately. Additionally, I expected that launching the apps with a specific timezone using the `--timezone` flag would allow me to set the desired timezone for the Electron apps, ensuring that they function correctly and in accordance with the actual local time.

### Actual Behavior

Instead of using the correct system timezone (America/Mexico_City), Electron apps on my Manjaro Linux KDE system appear to be using the Daylight Saving Time, which is no longer observed in Mexico. As a result, the apps display incorrect local time and any time-related functions within the apps are not accurate. 

When attempting to launch the Electron apps with a specific timezone using the `--timezone` flag, the method does not work as expected and results in an error. Consequently, I am unable to set the desired timezone for the Electron apps, leading to improper functioning of the apps in relation to the actual local time.

**Comment by mikeyyyzhao** [comment]
This is fixed in the latest version of electron (24.0.0)

**Comment by RickSlash84** [comment]
Thank you for letting me know. When are you planning to push it to Manjaro/Arch repositories? 

![image](https://user-images.githubusercontent.com/107479723/231852237-a5ed8a51-da2b-4218-a9e3-949c3d6e39a1.png)

**Comment by RickSlash84** [comment]
any news?

**Comment by cucbin** [comment]
upgrade last ICU version that's a dependency of chromium.

**Comment by RickSlash84** [comment]
I did that already, which solved the chrome based browsers issues. But desktop apps like WhatsApp run via electron. So I am still waiting for the last release to be pushed to repos.

**Comment by arnoldochavez** [comment]
Would this be solved? or is there a workaround? My target platform is windows 7 and I can only use Electron 22

**Comment by RickSlash84** [comment]
I am also still encounter the issue.

**Comment by cucbin** [comment]
that's the ICU version you guys used?

**Comment by maymage** [comment]
.
