### ISSUE TITLE
[Bug]: Using the official electron forge template, when running the npm run package file and opening the generated exe file, the page cannot be displayed. This issue can occur with versions above 20.0.0.

### ISSUE THREAD

**Issue by whw155** [electron/electron#37987]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.5

### What operating system are you using?

Windows

### Operating System Version

window11，AMD的CPU

### What arch are you using?

x64

### Last Known Working Electron version

24.0.0

### Expected Behavior

Using a version of 20.0.0 or higher, using the electronic forge official template, open the generated exe file after running the npm run package, and it can be used in any environment.

### Actual Behavior

Using the official electron forge template, when running the npm run package file and opening the generated exe file, the page cannot be displayed. This issue can occur with versions above 20.0.0.

After testing, it was found that this issue only occurred in the Windows version, under the CPU of AMD. In the Windows Intel CPU environment, there is no such issue, however. The package used normally in Intel environment cannot be used in AMD environment.

By outputting logs, it was found that during the main process rendering, browserWindow. webContent. loadFlie() threw an error when loading the file.

[Sun Apr 16 2023 10:38:24 GMT+0800 ] loadFlie---reject--event---Error: ERR_FAILED (-2) loading 'file://D:\work_code\study\electron\my-app1\out\my-app1-win32-x64\resources\app\.webpack\renderer\main_window\index.html'
[Sun Apr 16 2023 10:38:24 GMT+0800 ] loadFlie---reject--event---{"errno":-2,"code":"ERR_FAILED","url":"file://D:\\work_code\\study\\electron\\my-app1\\out\\my-app1-win32-x64\\resources\\app\\.webpack\\renderer\\main_window\\index.html"}

May I ask how to solve this problem?

**Comment by codebytere** [comment]
Please instead open this on the [Forge repo](https://github.com/electron/forge).
