### ISSUE TITLE
[Bug]: Can't re-open dialog for opening files or directory after it has been used once (even canceled)

### ISSUE THREAD

**Issue by AlexandreLemoine40** [electron/electron#37994]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.2.0

### What operating system are you using?

Other Linux

### Operating System Version

Debian 11

### What arch are you using?

x64

### Expected Behavior

Re-open a dialog file chooser each time I cancel or select a file and then re-click the button made to show the dialog.

### Actual Behavior

I click a button which triggers window.electronAPI.openDialog() to create a dialog from the main process and then select a file or cancel the dialog, and then I re-click the button and the electronAPI method is triggered but the main process doesn't open a new dialog.

**Comment by AlexandreLemoine40** [comment]
The dialog opened was not focused by the window and was opened in background

**Comment by Prinzhorn** [comment]
Linking this to #32857
