### ISSUE TITLE
[Bug]: Extra Keydown event sent when holding multiple keys

### ISSUE THREAD

**Issue by JephDiel** [electron/electron#38009]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise Version 21H2

### What arch are you using?

x64

### Expected Behavior

Only one (non-repeat) keydown event is sent pre key, and only sent at the moment the key is physically pressed.

### Actual Behavior

If you press and hold two keys, then release first pressed key, after ~ 1 second a keydown event will be sent on the second key that is not marked as repeat.

1.  Press the 'a' key and hold
2.  Press the 'b' key and hold
3.  Release the 'a' key
4.  Continue holding the 'b' key for ~1 second
5.  Observe a second (non-AutoRepeat) keydown event sent to the webcontents.

![image](https://user-images.githubusercontent.com/16943267/232582149-1ac133e5-b049-4e1e-a48d-10ee66e2d0dc.png)

### Testcase Gist URL

https://gist.github.com/1a5b01668ef6d23b3c148cb19daebdcc

**Comment by codebytere** [comment]
@JephDiel i can reproduce this but i'm unfortunately not sure there's much to do on our end. We plumb this directly from Chromium so it's probably best reported upstream.

**Comment by JephDiel** [comment]
Found a chromium issue that looks like the source of this bug. Adding it here for reference and for others who come across this.

[https://bugs.chromium.org/p/chromium/issues/detail?id=843558&q=extra%20keydown&can=2](https://bugs.chromium.org/p/chromium/issues/detail?id=843558&q=extra%20keydown&can=2)

**Comment by codebytere** [comment]
Closing this as an upstream bug - please feel free to comment on the Chromium bug and we'll inherit a fix once they address it!
