### ISSUE TITLE
[Bug]: app.relaunch doesn't work on App Store version

### ISSUE THREAD

**Issue by Imperat** [electron/electron#38012]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.0

### What operating system are you using?

macOS

### Operating System Version

MacOS 13.3.1 (22E261)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

On a sandboxed and signed Mac App Store App, calling:

```
 app.relaunch()
 app.quit() // or app.exit()
```

### Actual Behavior

App crashes and won't restart

### Additional Information

Similar issues closed automatically in the past:

https://github.com/electron/electron/issues/17699
https://github.com/electron/electron/issues/30515

**Comment by codebytere** [comment]
> App crashes and won't restart

@Imperat could you please attach the crash dump?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by Imperat** [comment]
Hi @codebytere 
Could we please re-open this as @nicedudu provided the dump?
