### ISSUE TITLE
[Bug]: setAlwaysOnTop(true, 'screen-saver') Does not stop the windows task bar from displaying

### ISSUE THREAD

**Issue by tehanby** [electron/electron#38020]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22621.1265

### What arch are you using?

x64

### Expected Behavior

When in Kiosk mode and setting the browserWindow to setAlwaysOnTop(true, 'screen-saver') should not allow the windows key on a keyboard to display the task bar in front of the browserWindow.

### Actual Behavior

The task bar displays in front of the browser.

**Comment by tehanby** [comment]
![image](https://user-images.githubusercontent.com/884019/232890504-44d7d14e-5847-45f6-a7ee-de5bc96a4f23.png)

**Comment by tehanby** [comment]
Test Case:

https://gist.github.com/tehanby/29b9c61643abb2b9ab75b801bb1a08f0

**Comment by tehanby** [comment]
Any updates on this?

**Comment by Suraj-Bhandarkar-S** [comment]
any updates on this ?

**Comment by sandyfigueroa** [comment]
I have the same issue on Electron v27.0.2

I set `win.setAlwaysOnTop(true, 'screen-saver');`

Even tried `win.setAlwaysOnTop(true, 'screen-saver', 1);` or increasing the number of the layer, but it doesn't work, the window is always below windows taskbar.

Only setting fullscreen to true works, but that is not what I need.

The documentation mentions this:

```
From pop-up-menu to a higher it is shown above the Dock on macOS and above the taskbar on Windows
```

But setting `pop-up-menu` or `screen-saver` doesn't cause the desired effect

My OS is Windows 11 Home 22H2.

**Comment by RandoMixs** [comment]
The same issue on Electron v28.2.0, I set ```win.setAlwaysOnTop(true, 'screen-saver');``` too!
