### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by StefanRadisavcevic** [electron/electron#38037]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

21.0.1

### Expected Behavior

When i open lot of tabs with iframes i want that my app work, not get freezed.

### Actual Behavior

i have backup in version 21.0.1 and i am not aware if in the version between the latest and 21.0.1 some of them work, but in the latest i have a problem when i want to load multiple tabs which containing iframes only one with simple html. after adding more than 3 tabs, my electron app freeze and screen is white.
Video of problem is below:
https://user-images.githubusercontent.com/22811562/233216815-de8eb59f-c4b4-4db1-a589-f9e7051c7c5d.mp4

Just to share my html pages which are loaded in iframes, maybe some scripts make problems in new version of Electron:
<!DOCTYPE html>
<html lang="en" style="width: 100%;height: 100%">
<head>
  
  <link rel="stylesheet" type="text/css" href="css/stilMasterChoose.css">
  <link href="css/fontovi.css" rel="stylesheet" type="text/css"/>   
  <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css"> 
  <link type="text/css" rel="stylesheet" href="css/font-awesome-4.7.0/css/font-awesome.min.css" />
  
  <script>const $ = require('jquery');window.$ = $;window.jQuery = $;</script>
  <script src="js/bootstrap.min.js"></script>  
  <style>
  :root {
  --surface-color: #fff;
  --curve: 40;
}

* {
  box-sizing: border-box;
}

body {
  font-family: 'Noto Sans JP', sans-serif;
  background-color: #fef8f8;
}

.cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 5rem;
  margin: 15rem 16vw;
  padding: 0;
  list-style-type: none;
}

.card {
  position: relative;
  display: block;
  height: 100%;  
  border-radius: calc(var(--curve) * 1px);
  overflow: hidden;
  text-decoration: none;
}

.card__image {      
  width: 100%;
  height: auto;
}

.card__overlay {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 1;      
  border-radius: calc(var(--curve) * 1px);    
  background-color: var(--surface-color);      
  transform: translateY(100%);
  transition: .2s ease-in-out;
}

.card:hover .card__overlay {
  transform: translateY(0);
}

.card__header {
  position: relative;
  display: flex;
  align-items: center;
  gap: 2em;
  padding: 2em;
  border-radius: calc(var(--curve) * 1px) 0 0 0;    
  background-color: var(--surface-color);
  transform: translateY(-100%);
  transition: .2s ease-in-out;
}

.card__arc {
  width: 80px;
  height: 80px;
  position: absolute;
  bottom: 100%;
  right: 0;      
  z-index: 1;
}

.card__arc path {
  fill: var(--surface-color);
  d: path("M 40 80 c 22 0 40 -22 40 -40 v 40 Z");
}       

.card:hover .card__header {
  transform: translateY(0);
}

.card__thumb {
  flex-shrink: 0;
  width: 50px;
  height: 50px;      
  border-radius: 50%;      
}

.card__title {
  font-size: 2em;
  margin: 0 0 .3em;
  color: #6A515E;
}

.card__tagline {
  display: block;
  margin: 1em 0;
  font-family: "MockFlowFont";  
  font-size: .8em; 
  color: #D7BDCA;  
}

.card__status {
  font-size: 1em;
  color: #D7BDCA;
}

.card__description {
  padding: 0 2em 2em;
  margin: 0;
  color: #D7BDCA;
  font-family: "MockFlowFont";   
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  overflow: hidden;
}    
  </style>
</head>
<body style="width: 100%;height: 100%">
<div class="container-fluid" style="height: 100%">
  <ul class="cards">
  <li>
    <a id="affiliact" href="#" class="card">
      <img src="slike/aaaa.png" class="card__image" alt="aaa.com"/>
      <div class="card__overlay">
        <div class="card__header">                   
          <img class="card__thumb" src="slike/aaaa.png" alt="aaa" />
          <div class="card__header-text">
            <h3 class="card__title">aaa</h3>            
            <span class="card__status">aaaa</span>
          </div>
        </div>
        <p class="card__description"></p>
      </div>
    </a>      
  </li>
  <li>
    <a id="dating" href="#" class="card">
      <img src="slike/ccc.png" class="card__image" alt="xxxx" />
      <div class="card__overlay">        
        <div class="card__header">                
          <img class="card__thumb" src="slike/dating_small.png" alt="xxx" />
          <div class="card__header-text">
            <h3 class="card__title">ddddd</h3>
            <span class="card__status">ccc</span>
          </div>
        </div>
        <p class="card__description"></p>
      </div>
    </a>
  </li>  
</ul>
</div>    
</body>
</html>

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by StefanRadisavcevic** [comment]
I am showing you an error. It was working normal on versions before. When you open more iframes with html page i shared you, electron app freezed.
