### ISSUE TITLE
[Feature Request]: Remove "Experimental" tag from BrowserView

### ISSUE THREAD

**Issue by GGIEnrike** [electron/electron#38036]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Since the initial release a few years ago, the `BrowserView` API has matured and has been integrated in countless projects big and small. From my observations, the Notion app uses `BrowserView`s in its new-ish update that added multiple tab support. Although I cannot verify that, but Figma may probably be using them as well.

This runs the risk of this API being removed and causing many projects to rewrite major parts of their functionality or, in the case of a few, cease to exist entirely. But, if the development team doesn't plan any radical changes regarding this API, due to the mass adoption and nature of this API (the functionality is deeply intertwined with Electron core and cannot be replaced by other modules. It is also the way of displaying the app's contents so any app using it wouldn't work unless adjusted to the change, it rarely is just another feature), the use of the "Experimental" tag is even more unjustified, and may likely need to be reconsidered.

### Proposed Solution

The development team could consider calling the community beloved `BrowserView` API stable and not experimental.

### Alternatives Considered

The presence of this tag is not impacting any funcitonality of Electron, but I do think it needs to be looked at by the team as I described above. However, as I already outlined, the removal of the API could not be worked around by external modules, only inferior `iframe` and `webview` can be used to replicate it.

### Additional Information

I couldn't find a better place to put this message in, but I don't think it would belong in any community channels either.

**Comment by Prinzhorn** [comment]
Related https://github.com/electron/electron/pull/35658

**Comment by codebytere** [comment]
@GGIEnrike 

> if the development team doesn't plan any radical changes regarding this API

See https://github.com/electron/electron/pull/35658 as @Prinzhorn linked above - we are in fact going to be making some significant changes to this API, and so as of now it's not something we're prepared to mark stable. See that PR for more updates.
