### ISSUE TITLE
[Bug]: GSlice: assertion failed: sinfo->n_allocated > 0

### ISSUE THREAD

**Issue by KillerCodeMonkey** [electron/electron#38048]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24

### What operating system are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Last Known Working Electron version

23

### Expected Behavior

No errors when processing images (in parallel as well) with sharpjs like it is in electron v23

### Actual Behavior

i am using sharpjs to transform images, randomly the app crashes with
`GSlice: assertion failed: sinfo->n_allocated > 0`

### Additional Information

I already asked at the sharp repo:
https://github.com/lovell/sharp/issues/3384#issuecomment-1516283279

There i linked another github project with similar problems and how they solved it:
https://github.com/libvmi/libvmi/pull/927/files

So i do not know if this is a general electron issue or a combination when using both libs.

**Comment by VerteDinde** [comment]
Hey @KillerCodeMonkey, happy to look more into this - if you could attach a repro like the bot mentions above, or link to how you're using sharp in your own codebase, that would be awesome 🙂

**Comment by KillerCodeMonkey** [comment]
i will try my best to build an example to reproduce it.

**Comment by KillerCodeMonkey** [comment]
heyho, i invested some time and the root cause was the usage of graphql-upload library and not handline the createReadstream() in ALL cases. i had some condition so the graphql resolver so the stream was never read and that seems to lead to open streams until the memory is full.

but strange that this really occurs that fast with electron 24... but in the end. it was my fault :). Thanks

**Comment by Sandakan** [comment]
@KillerCodeMonkey How did you fix the crash?

**Comment by KillerCodeMonkey** [comment]
in the graphql part you need to read the readstream as the first thing you do in your resolver.

See: https://github.com/jaydenseric/graphql-upload/issues/352#issuecomment-1401290104
or: https://github.com/flash-oss/graphql-upload-minimal/issues/37#issuecomment-1399174788
