### ISSUE TITLE
[Bug]: system context menu doesn't appear for frameless windows when right-clicking on the taskbar icon preview

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#38050]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

When I hover over the task bar icon for my application, and right-click on the preview that appears, I expect to see a context menu:
![image](https://user-images.githubusercontent.com/6374473/233471964-aa487fff-cc73-4c8e-a89c-8663600d8fd7.png)

### Actual Behavior

I don't get a context menu

### Testcase Gist URL

https://gist.github.com/fbc33db0e46375227f1f787fd7b1565c

### Additional Information

can repro back to Electron 4

**Comment by pushkin-** [comment]
[related, closed issue](https://github.com/electron/electron/issues/12134)

**Comment by pushkin-** [comment]
bump

**Comment by codebytere** [comment]
See https://github.com/electron/electron/issues/12134 - this is controlled by Windows and not something we're able to change unfortunately.
