### ISSUE TITLE
[Bug]: Accessibility Access in Render process

### ISSUE THREAD

**Issue by glani** [electron/electron#38094]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0

### What operating system are you using?

macOS

### Operating System Version

13.3.1 (22E261)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Actual only for DMG release build.

A native module that uses Accessibility API works as expected in the Render process for arm64 architecture.

The simple application shows correct behavior on intel x64 architecture.

console log for x64:

REQUEST_MAIN_WINDOW_INIT_REPLY
renderer.js:11 Is accessibilityOk true (call to the main process systemPreferences.isTrustedAccessibilityClient(true))

Retrieve the list of all windows in the Render process (Native module call, the module is loaded in the Render Process)
renderer.js:18 Renderer: (13) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]

Retrieve the list of all windows in the Main process (Native module call, the same module is loaded in the Main Process)
renderer.js:21 Main Process Windows: (13) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]

renderer.js:25 Render Process requestAccessibilityPermissions: {Access: true} (isTrustedProcess macos Accessibility API call in the render process  against Native Module)

renderer.js:26 Main Process requestAccessibilityPermissions: {Access: true} (isTrustedProcess macos Accessibility API call in the main process  against Native Module)

### Actual Behavior

Actual only for DMG release build.

In arm64 architecture, the same application behaves differently:

Is accessibilityOk true  (call to the main process systemPreferences.isTrustedAccessibilityClient(true))

Retrieve the list of all windows in the Render process (Native module call, the module is loaded in the Render Process)
renderer.js:18 Renderer: []

Retrieve the list of all windows in the Main process (Native module call, the same module is loaded in the Main Process)
renderer.js:21 Main Process Windows: (26) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]

renderer.js:25 Render Process requestAccessibilityPermissions: {Access: false} (isTrustedProcess macos Accessibility API call in the render process  against Native Module)

renderer.js:26 Main Process requestAccessibilityPermissions: {Access: true} (isTrustedProcess macos Accessibility API call in the main process  against Native Module)

### Additional Information

If Electron process started in Development Environment in arm64 (for example under WebStorm) there would be no problems under arm64
DevEnv application has all the necessary permissions.

There is no problem when I am running the DMG release under iTerm (with all Accessibility permissions enabled for iTerm).
As a result, the render process has all permissions and works as expected.

Tested on two arm64 (mac book pro m1 14 2021 and mac mini m1 2020) and MacBook pro core i9 intel x64 2019.

I would appreciate some ideas and thoughts on where I have to look.

Thank you.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Comment by glani** [comment]
So interesting that it was closed.

I tried to explain in detail.

The problem is that Electron ARM Dmg blocks permissions in the Render process (does not inherit them from the main).
