### ISSUE TITLE
[Bug]: showSaveDialog cannot show modal action on Linux Debian10 system

### ISSUE THREAD

**Issue by liudenaxietian** [electron/electron#38099]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.11

### What operating system are you using?

Other Linux

### Operating System Version

debian10 arm64 system

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

show modal dialog normally on debian10 system

### Actual Behavior

can not show modal actions on arm64 debian10 system while show normally on windows system

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `22.x.y`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
