### ISSUE TITLE
[Bug]: MessageChannelMain and utilityProcess pipe does not work

### ISSUE THREAD

**Issue by glani** [electron/electron#38121]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0

### What operating system are you using?

macOS

### Operating System Version

13.3.1 (22E261)

### What arch are you using?

arm

### Expected Behavior

In the gist:  [utility-process.js](https://gist.github.com/glani/c793e2cc2a8d3efc927db8746c5b9268#file-utility-process-js-L7) line 7 should write back to the channel.

As a result [main](https://gist.github.com/glani/c793e2cc2a8d3efc927db8746c5b9268#file-main-js-L41) will receive the message in the channel.

### Actual Behavior

In the gist:  [utility-process.js](https://gist.github.com/glani/c793e2cc2a8d3efc927db8746c5b9268#file-utility-process-js-L7) line 7 has no effect.

As a result [main](https://gist.github.com/glani/c793e2cc2a8d3efc927db8746c5b9268#file-main-js-L41) is not received.

### Testcase Gist URL

https://gist.github.com/glani/c793e2cc2a8d3efc927db8746c5b9268

### Additional Information

From the documentation
```
Class: UtilityProcess
Instances of the UtilityProcess represent the Chromium spawned child process with Node.js integration.
```

However, in the browser, there is a way to write back to the channel. 

Missing this functionality makes utilityProcess slightly useless. Especially on tasks request / response. Spawning everytime is a resource consumption operation (for example sub process loads native library and perform async calls against native code)

**Comment by deepak1556** [comment]
Messages on the port will be queued until the `start` method is called, ex: in your example `port1.start()`, refs https://github.com/electron/electron/blob/main/docs/api/message-port-main.md#portstart
