### ISSUE TITLE
How to check if electron of specific version can work on my ubuntu20.04

### ISSUE THREAD

**Issue by wanted002** [electron/electron#38120]
As a newbe to electron, I'd like to know that how to check if electron of specific version can work on my ubuntu20.04.  Maybe I'll try from 10-x-y to 24-x-y , and if there are some TestSuits or some rules to follow ?  AS I know ,electron depends on NodeJs and chromium, and possibly they should not dependend on specific version of Linux . Many thanks.

**Comment by franchesco98** [comment]
As you've said (and if I understood correctly), Electron depends on NodeJS, so it really doesn't matter what os you're using. If you have installed NodeJS, then Electron is compatible.
Another different thing is packaging your developed application using Electron, to make it native. But I don't think you'll have problems either.

**Comment by VerteDinde** [comment]
Hey @wanted002 - all currently supported versions of Electron should work with Ubuntu 20.04. To my knowledge, there's no limitation on older versions of Electron working with Ubuntu 20.04, although some older versions may have outdated or now unsupported APIs.
