### ISSUE TITLE
[Bug]: Electron app exits /usr/app/node_modules/electron/dist/electron exited with signal SIGTRAP

### ISSUE THREAD

**Issue by sudhu678** [electron/electron#38128]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.4

### What operating system are you using?

Other Linux

### Operating System Version

Debian GNU/Linux 5.10.76-linuxkit x86_64

### What arch are you using?

x64

### Expected Behavior

App should not be running normally. Started electron app logging in as root user using npm start with --no-sandbox flag to avoid  below error.
The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/app/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.

### Actual Behavior

[2] /usr/app/node_modules/electron/dist/electron exited with signal SIGTRAP
[2] npm run electron exited with code 1
--> Sending SIGTERM to other processes..
[1] [1] tsc-alias -w -p tsconfig.node.json exited with code SIGTERM
[1] --> Sending SIGTERM to other processes..
[1] [0] tsc -w -p tsconfig.node.json exited with code SIGTERM
[1] npm run build:electron:watch exited with code SIGTERM
--> Sending SIGTERM to other processes..
[0] ✔ Browser application bundle generation complete.
[0] ng serve exited with code SIGTERM
# node -v
v16.20.0
# npm -v
8.19.4

### Additional Information

FROM node:16

WORKDIR /usr/app

COPY . /usr/app

RUN apt-get update

RUN apt-get -y install libgtkextra-dev libgconf2-dev libnss3 libasound2 libxtst-dev libxss1 xvfb x11vnc libatk-bridge2.0-0 libgtk-3-0 libgbm1 libudev1 libsecret-1-dev dbus-x11 dbus

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket

ENV ELECTRON_ENABLE_LOGGING=1

ENV DISPLAY=localhost:99

RUN npm install

CMD ["/usr/app/start.sh"]
-------------------------------------
start.sh:

#!/bin/sh
(Xvfb :99 && export DISPLAY=':99') &
/etc/init.d/dbus start
x11vnc -display :99

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
