### ISSUE TITLE
[Bug]:  Macos new BrowserWindow with particular parameters crashes main process

### ISSUE THREAD

**Issue by glani** [electron/electron#38132]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.2+

### What operating system are you using?

macOS

### Operating System Version

13.3.1 (22E261)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

No crash is expected

### Actual Behavior

Periodically after opening a window from ipcMain.on (original call comes from another window) application crashed. Report is in gist

### Testcase Gist URL

https://gist.github.com/glani/8f9742ead48e08743bf3a8d0fe221d9b

### Additional Information

spawning parameters for the window

```
{
  x: 600,
  y: 398,
  width: 600,
  height: 354,
  alwaysOnTop: false,
  frame: false,
  fullscreenable: false,
  fullscreen: false,
  maximizable: false,
  resizable: true,
  show: true,
  titleBarStyle: undefined,
  webPreferences: {
    preload: '/Users/denis/self/smbact-app/app-native/preload-embeddedbrowserwindow.js',
    partition: 'persist:6dafde2d-8e65-49ea-896b-4efa645a8f5f',
    webSecurity: true,
    devTools: true,
    sandbox: false,
    additionalArguments: [
      '--embeddedbrowserwindow={"frameless":true,"customTitleBar":{"show":"onPress","pressTargetKey":"Meta","doublePressTargetKey":"Meta"},"useSystemControls":false,"serve":true,"winId":"db1bdded-f508-401b-8f2c-8fbc3f407e89"}'
    ]
  }
}
```

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
