### ISSUE TITLE
[Bug]: Narrator Support Issue - Electron App does not emit property/structure changed event

### ISSUE THREAD

**Issue by msftedad** [electron/electron#38162]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Win 32: OS build : 21286.1000 VS code version: 1.54.0-insider (Universal) AT used : Keyboard.macOS: Catalina macOS version: 10.15.6 VS code version: 1.54.0-insider (Universal)

### What arch are you using?

x64

### Last Known Working Electron version

12.0.0

### Expected Behavior

Screen reader should announce expanded/collapsed information of the style

### Actual Behavior

Screen reader is silent on expanding/collapsing the styles in the 'Elements' tab. i.e, styles in DOM tree.
[Repro_Expand collpase.webm](https://user-images.githubusercontent.com/93735775/235856852-b85abdaf-21b2-4186-aa42-ca57fd466825.webm)

### Testcase Gist URL

Pre-Requisites: 'Install 'Visual Studio Code' application. Go to 'Extensions' and add 'Elements for Microsoft edge(Chromium)' extension. Repro Steps:​ 1. Launch VS code application. 2.Navigate to the 'Elements' tab in the devtools. 3.Navigate through the 'Styles' try to expand and collapse the styles. 4.Listen to Screen reader's announcement  Note: This issue has been observed in MAC as well as win32 platform all over the Application.

**Comment by codebytere** [comment]
@msftedad Does this also happen in Chromium itself?

**Comment by msftedad** [comment]
This issue is closed from our end. Thanks

**Comment by msftedad** [comment]
Hi @codebytere, issue is still repro in latest Canary build. As per below comment, we are able to reproduce this issue on [Supported version of Electron](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline)(27.3.2). Providing attachment for reference(Repro_expand_collapse.webm)
Verified in:
Win11:
OS version: 24H2
OS build: 26063.1
VS code version(Insiders): 1.87.2
Could you please reopen this issue.
