### ISSUE TITLE
[Bug]: Text corruption with inline image on Linux with Intel GPU

### ISSUE THREAD

**Issue by cas--** [electron/electron#38182]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24

### What operating system are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Last Known Working Electron version

17.4.11

### Expected Behavior

Text is not corrupted or garbled

![image](https://user-images.githubusercontent.com/606038/236233023-2f7ef5d5-498a-44f3-9ba0-d5181cdc799f.png)

### Actual Behavior

Text is corrupted or garbled

![image](https://user-images.githubusercontent.com/606038/236233331-d95f91de-a80c-45ee-a91e-102b284f4f4e.png)

### Testcase Gist URL

https://gist.github.com/0d6e3524b9b095e1e567a07a7c797e31

### Additional Information

This is a common problems in the sidebar of several Electron apps for Linux users with Intel GPUs:

* https://github.com/logseq/logseq/issues/7233
* https://github.com/laurent22/joplin/issues/7506

The initial suggested workaround was to disable GPU rendering,then it was found that opacity was somehow related and from my research it seems to be something to do with stacking contexts with inline icon and text elements.

**Comment by cas--** [comment]
This looks like it originates as a Chromium bug since Electron 18 moved to Chromium 100 and checking old releases I can see the following:

Chromium versions from [clickot](https://github.com/clickot/ungoogled-chromium-binaries/releases) or [linchrome](https://github.com/macchrome/linchrome/tags)
* 98.0.4758.80 - Good
* 99.0.4844.84 - Good 
* 100.0.4896.75 - Bad
* 112.0.5615.165 - Bad

The latest version installed with Ubuntu 22.04 seems good though
* 112.0.5615.49 - Good

Is there something else at play with the packaging? :thinking:

**Comment by pearsche** [comment]
@cas-- could you help here? https://gitlab.freedesktop.org/mesa/mesa/-/issues/8853

**Comment by cas--** [comment]
@pearsche What help do you need? Not sure how much I can add, other than how to replicate using that [index.html](https://gist.githubusercontent.com/cas--/0d6e3524b9b095e1e567a07a7c797e31/raw/a50b0f0918db55ad012116bb41b805482173f590/index.html)

However it does look to be fixed in latest Chromium 113, testing with [clickot](https://github.com/clickot/ungoogled-chromium-binaries/releases) releases:
* ungoogled-chromium_113.0.5672.63 - Good
* ungoogled-chromium_113.0.5672.127 - Good

**Comment by pearsche** [comment]
Libva is for hw video acceleration, so i doubt its related.

**Comment by pearsche** [comment]
I've noticed that the text rendering bug i get on pleroma instances is far lesser with that version of chrome. well, that's nice...

**Comment by cas--** [comment]
bump

**Comment by pearsche** [comment]
@cas--  do you still get this bug, even with mesa 23.2 or newer?
