### ISSUE TITLE
[Bug?]: Unable to run WebGPU in linux/docker with swiftshader

### ISSUE THREAD

**Issue by lslzl3000** [electron/electron#38189]
- Ubuntu 22  vm or docker
- Electron 25+ with Chromium 113+

As WebGPU has officially shipped in Chromium/Chrome 113,  it will be a very popular api in a very short future.
We are working on many WebGPU based projects, it works well in Electron on normal Window/Mac/Linux with GPU hardware. 

One of important jobs is CI test, e.g. in Github actions. But the Github runners(like most of the CI/CD platforms) are only CPU vms without GPU hardware or drivers(DX/Metal/Vulkan), so it is hard to do a CI test with WebGPU api. 

I think this is also a problem for WebGL applications. Is there a good solution for Electron run WebGL in Docker/Linux without GPU? 

In theory, [swiftshader](https://github.com/google/swiftshader) should work in docker/linux without GPU, and chromium also support `--use-webgpu-adapter=swiftshader`.  But I can't get it work in Electron

I tried with `app.commandLine.appendSwitch("use-webgpu-adapter", "swiftshader")`, but got an error `viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization`, unable to access WebGPU apis.  
Is this a bug in Electron or I need something else to config?

Anyone know how to make swiftshader work in docker/linux?  Do I need to install extra swiftshader or vulkan sdk in Ubuntu? I thought Electron has embedded swiftshader/vulkan by default with `libvk_swiftshader.so` and `libvulkan.so.1`

**Comment by lslzl3000** [comment]
I tried many flags to start electron, finally got a working combination:
```bash
electron --enable-unsafe-webgpu --enable-features=Vulkan --use-vulkan=swiftshader --use-webgpu-adapter=swiftshader --no-sandbox test/main.js
```
no `Exiting GPU process` error, and the WebGPU APIs (e.g. `navigator.gpu.requestAdapter()` ) could process with no error in render process.

But in the electron internal process, there are still some errors:
```
Warning: vkCreateInstance: Found no drivers!
Error: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:416)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:302)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:232)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:492)

Error: eglChooseConfig returned zero configs
    at Create (../../third_party/dawn/src/dawn/native/opengl/ContextEGL.cpp:53)

Error: EGL_EXT_create_context_robustness must be supported
    at Create (../../third_party/dawn/src/dawn/native/opengl/ContextEGL.cpp:67)
```
But they are not stop/interrupt the js/webgpu process. 

Is this a chromium/dawn bug or electron one? e.g.  old swiftshader version? 
Hope someone could dig this further

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
