### ISSUE TITLE
[Bug]: Selenium tests don't work on electron 21+

### ISSUE THREAD

**Issue by phwang4** [electron/electron#38198]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

20.3.12

### Expected Behavior

Should be able to run a selenium test for my electron app 

### Actual Behavior

App does not appear so I get a "No target with given id found" error.
[Here](https://github.com/electron/electron/files/11409511/individual.out.log) is the chromedriver log

**Comment by VerteDinde** [comment]
Hey @phwang4, as an additional data point, we're running Selenium tests on Electron 24 and Electron 25 betas without any issue. If you could include a repro of your test setup or more information, that would be very helpful
