### ISSUE TITLE
focus() doesn't focus web view for frameless window.

### ISSUE THREAD

**Issue by pilwon** [electron/electron#382]
focus() works fine for browser window with frame (focuses the window and stays focused on the web view), but it works differently for frameless browser windows. The window is focused but I cannot trap keyboard press using [mousetrap](https://github.com/ccampbell/mousetrap) until I make a click on the web view inside the window.

**Comment by foolyoghurt** [comment]
I still have the same problem with window having frame. I need to click on the page inside the window so that listening for keyboard event works. I use OSX 10.0.9 and electron v0.26.0.

**Comment by MarshallOfSound** [comment]
I'm having this issue still on all platforms, the keyboard listeners inside a webview do not work without the webview focused and I can't call `.focus()` on the webview
