### ISSUE TITLE
[Bug]: ProcessMemoryInfo build error

### ISSUE THREAD

**Issue by YuriL180821** [electron/electron#38209]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0-nightly.20230504

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Last Known Working Electron version

23.0.0

### Expected Behavior

Electron main branch should have all declarations mentioned into electron.d.ts and be able to compiled

### Actual Behavior

**process-memory-info.md** became to be present only after my manipulations with smartgit, which means file was absent into main branch and created only after press Open file.

Build till my manual creation **process-memory-info.md** for main branch was impossible, build console printed next 

ninja: Entering directory `out/Release'
[0/1] Regenerating ninja files
[195/43767] ACTION //electron:build_electron_definitions(//build/toolchain/linux:clang_x64)
FAILED: gen/electron/tsc/typings/electron.d.ts 
python3 ../../electron/build/npm-run.py --silent gn-typescript-definitions -- /home/scar/Documents/electron-official/unix/src/out/Release/gen/electron/tsc/typings/electron.d.ts
NPM script 'gn-typescript-definitions' failed with code '2':
- Checking argv
✔ Electron Typescript Definitions generated in "/home/scar/Documents/electron-official/unix/src/electron" took 745ms
../electron.d.ts(19548,37): error TS2304: Cannot find name 'ProcessMemoryInfo'.

As additional confirmation, see timestamp for **process-memory-info.md** into my **![Screenshot from 2023-05-08 10-14-52](https://user-images.githubusercontent.com/89125090/236760334-500eef99-7eb0-465c-837a-3bf492b1cf33.png)** was created today, but build was started yesterday and failed

**Comment by YuriL180821** [comment]
Bingo, even with existing file build is impossible

286/43592] ACTION //electron:build_electron_definitions(//build/toolchain/linux:clang_x64)
FAILED: gen/electron/tsc/typings/electron.d.ts 
python3 ../../electron/build/npm-run.py --silent gn-typescript-definitions -- /home/scar/Documents/electron-official/unix/src/out/Release/gen/electron/tsc/typings/electron.d.ts
NPM script 'gn-typescript-definitions' failed with code '2':
- Checking argv
✔ Electron Typescript Definitions generated in "/home/scar/Documents/electron-official/unix/src/electron" took 749ms
../electron.d.ts(19475,37): error TS2304: Cannot find name 'ProcessMemoryInfo'.


[295/43592] CXX obj/third_party/jsoncpp/jsoncpp/json_reader.o
ninja: build stopped: subcommand failed.


I would ask to fix this problem ASAP  because not able to work at all (I did rebase on main branch and as result my working branch is also corrupted)

**Comment by codebytere** [comment]
@YuriL180821 this file exists on main - https://github.com/electron/electron/blob/main/docs/api/structures/process-memory-info.md, and can't be reproduced locally. Are you sure you've rebased and updated deps?

**Comment by YuriL180821** [comment]
Hello @codebytere on given moment repo can be compiled again and ticket can be closed.

Answering on Your question: yes I'm sure, I had repo which was fully compiled, than I did rebase on main branch and received problems shown above. Before opening ticket I did full sync and checkout from my feature branch to main , my second post with unsuccessful build is for this stage.
