### ISSUE TITLE
[Feature Request]: Adds a static method for fromWebContents or fromWebContentsId to BrowserView

### ISSUE THREAD

**Issue by 1339240789** [electron/electron#38202]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

BrowserWindow and WebContents both have static methods that you can quickly fetch by id or whatever, and I think BrowserView can add static methods to quickly fetch instances.Otherwise, every time i get the specified browserview, i must first go through the getBrowserView method of BrowserWindow

### Proposed Solution

can use webContents under BrowserView to quickly locate it

### Alternatives Considered

or from webContens'Id

**Comment by miniak** [comment]
`BrowserView.fromWebContents()` was removed by #23578

**Comment by miniak** [comment]
cc @nornagon
