### ISSUE TITLE
Disable Swipe Gestures in KIOSK Mode

### ISSUE THREAD

**Issue by valueerrorx** [electron/electron#38217]
KIOSK mode should keep the electron window above others (notifications, screensaver, taskbar, ..) and prevent the user from leaving it. 

Unfortunately it doesn't do a very good job at that. 
Keyboardshortcuts and Swipe gestures trigger operating system functions that for example let the user switch to another application on Windows.

I managed to block keyboard strokes with the launch of an additional c application in the background that captures most of them and drops them. but it seems to be impossible to capture and drop the 3fingers "swipe up" gesture for example.

using electron 20.1.0
windows 11

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Could you please fill out our issue template, so we have the information we might need to debug this without asking as many follow ups? Happy to have one of us take a look when the template is appropriately filled out 🙇‍♀️

**Comment by valueerrorx** [comment]
sorry... i used the form: https://github.com/electron/electron/issues/38286
so this can be deleted
