### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Dimizk** [electron/electron#38247]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

Win 10

### What arch are you using?

x64

### Last Known Working Electron version

it dont work

### Expected Behavior

wont load
Screenshot : https://cdn.discordapp.com/attachments/946764309722181702/1105864601674973295/image.png

### Actual Behavior

a

### Testcase Gist URL

https://github.com/SamuelScheit/discord-bot-client/releases/tag/3.1.0

### Additional Information

a

**Comment by MarshallOfSound** [comment]
This does not appear to be an issue with electron rather with a third party discord client.  Please report issues to them, not to us.
