### ISSUE TITLE
[Bug]: Window transparency is not restored when a maximised video is unmaximised

### ISSUE THREAD

**Issue by SilverBirchh** [electron/electron#38244]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6.5

### What arch are you using?

x64

### Expected Behavior

With an app that has a transparent area if you maximise a video element to view it full screen and then minimise the transparent area should stay transparent.

### Actual Behavior

With an app that has a transparent area if you maximise a video element to view it full screen and then minimise the transparent area turns solid.

https://github.com/electron/electron/assets/16886168/d45d58fa-f545-4155-8daa-0333d753e3ef

### Testcase Gist URL

https://gist.github.com/SilverBirchh/8e4e4c92e0b3759f0f9d8fc2ef599bd2

### Additional Information

Sorry if this has already been fixed! I couldn't find anything else

Repo https://github.com/SilverBirchh/electron-video-test

**Comment by georgexu99** [comment]
Managed to bisect this to 16.0.8! I'll havn't looked in-depth into the issue, but this [PR] (https://github.com/electron/electron/pull/32648/files) may have changed the way we handle the css transparency

**Comment by SilverBirchh** [comment]
> this [issue](https://github.com/electron/electron/issues/37705) may be related

fwiw that is the hack we're using to get around this issue. when the video is un-maximised we're changing the window size by a pixel and back again. Doesn't always work but 90% of the time it does

**Comment by SilverBirchh** [comment]
bump
