### ISSUE TITLE
[Bug]: BrowserWindow.show()  caused window to exit split-screen mode

### ISSUE THREAD

**Issue by kanweiwei** [electron/electron#38253]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

Window11 22H2

### What arch are you using?

x64

### Expected Behavior

`BrowserWindow.show() ` should not cause window to exit split-screen mode

### Actual Behavior

`BrowserWindow.show() ` caused window to exit split-screen mode

### Testcase Gist URL

https://gist.github.com/89890e9c5008a09093a44a8d9e84521e

**Comment by migueljolv** [comment]
@kanweiwei Did you find a workaround for this? I'm having the same issue

**Comment by migueljolv** [comment]
This issue is present in version 25 too

**Comment by kagezhao** [comment]
I have same issue.  my temporary solution: @migueljolv 

when your window is already visible, dont call show(), call focus() instead.

      if (!win.isVisible()) {
        win.show();
      }
      win.focus();
