### ISSUE TITLE
[Bug]: getOSProcessId returns 0 just right after new `webContents` created

### ISSUE THREAD

**Issue by Imperat** [electron/electron#38256]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

macOS

### Operating System Version

Venture 13.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I want to gather renderer process pid for performance tracking purposes and I am running into an issue where `webContents.getOSProcessId()` returns 0 in the first few moments after creating.

```
const {app, BrowserWindow} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  })

  mainWindow.loadURL('https://google.com')

  console.log('get os process id');
  console.log(mainWindow.webContents.getOSProcessId());
  console.log();
  setTimeout(() => {
  
  console.log('get os process id after timeout');
  console.log(mainWindow.webContents.getOSProcessId());
  console.log();
  }, 1000);
}

app.whenReady().then(() => {
  createWindow()
})

```

Is it possible to fix or introduce an asynchronous analog of `getOSProcessId()`?

### Actual Behavior

`webContents.getOSProcessId` returns 0 after new webContents created.

**Comment by miniak** [comment]
The renderer process only gets created when the webContents navigates
