### ISSUE TITLE
[Feature Request]: version for Windows legacy

### ISSUE THREAD

**Issue by ask2018** [electron/electron#38262]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron 23+ dropped support for Windows 7/8/8.1 and that makes many Electron based applications incompatible with those systems. Specially for Win7 there is still many users with valid reasons to use it left.

### Proposed Solution

If the only reason why electron 23+ dropped the support for Win 7/8/8.1 is this:
https://github.com/electron/electron/releases/tag/v23.0.0
Windows 7, Windows 8, and Windows 8.1 are not supported anymore, as Chromium 110 dropped support.
Then there is solution now, because there is Chromium fork for Windows legacy now available here:
https://github.com/win32ss/supermium
The aim of Supermium is to provide the latest Chromium features, support for rendering the web and security patches to users of Windows Vista (with extended kernel), Windows 7 and Windows 8.x.

### Alternatives Considered

The only alternative for Windows 7/8/8.1 users is atm use older Electron 22, but that will end support on October 10, 2023. as described here: https://www.electronjs.org/blog/electron-22-0
Sooner or later somebody will make probably unofficial fork, but it would be great if official version exists, so I wanted to ask if you are interested in this or not.

**Comment by VerteDinde** [comment]
Hey @ask2018 - we're intentionally extending the support life of Electron 22 and backporting security fixes to Electron 22 until October 2023, to support those moving off of Windows 7/8/8.1. However, because both Chromium and Microsoft are dropping support for legacy versions of Windows in the long term, Electron will also follow suite. It's just not feasible at this time for us to build a version of Electron against Chromium, and a second version against a fork of Chromium, particularly one that isn't supported by the Chromium team.

Thanks for bringing this to our attention, and I'm sorry we couldn't help you here. If you do have any questions about the support life of Electron 22, feel free to ask them here or in our [community Discord here](https://discord.gg/electron).

**Comment by ask2018** [comment]
Hello and thank you for detailed answer @VerteDinde. I fully understand your position and accept it. I just want to explain this problem more detailed here. Maybe it might be helpful for somebody reading this in the future. Unfortunately the situation became very bad for people like me, because there is simple nowhere to move from Win7 atm easy way. Windows is dead for me, I'll never accept the way of the system Microsoft did since Win8 and specially with Win10/11 when it became even worse. It is now simple something I refuse to use for multiple reasons. My solution for future is Linux, but fully moving to that is simple something very time consuming for my needs and that's something I cannot do in near future. Specially if I have here Windows 7 where everything is working exactly as I need and the only problem is now some software is dropping support. 

Here is another example of people who refuse to leave Win7 and their reasons:
https://old.reddit.com/r/windows7/comments/13bpe0g/why_you_still_use_windows_7_just_curious_questions/

That means the solution for people like me might be some unofficial fork, or extended kernel like this https://github.com/vxiiduu/VxKex (but that is not capable to run Electron 23+ at its current state) or simply create virtual machine with Linux based system and run the non supported software there.

**Comment by NCLnclNCL** [comment]
> Hello and thank you for detailed answer @VerteDinde. I fully understand your position and accept it. I just want to explain this problem more detailed here. Maybe it might be helpful for somebody reading this in the future. Unfortunately the situation became very bad for people like me, because there is simple nowhere to move from Win7 atm easy way. Windows is dead for me, I'll never accept the way of the system Microsoft did since Win8 and specially with Win10/11 when it became even worse. It is now simple something I refuse to use for multiple reasons. My solution for future is Linux, but fully moving to that is simple something very time consuming for my needs and that's something I cannot do in near future. Specially if I have here Windows 7 where everything is working exactly as I need and the only problem is now some software is dropping support.
> 
> Here is another example of people who refuse to leave Win7 and their reasons: https://old.reddit.com/r/windows7/comments/13bpe0g/why_you_still_use_windows_7_just_curious_questions/
> 
> That means the solution for people like me might be some unofficial fork, or extended kernel like this https://github.com/vxiiduu/VxKex (but that is not capable to run Electron 23+ at its current state) or simply create virtual machine with Linux based system and run the non supported software there.

Dont use electron, use c++, c# with net framework, java with old ...

**Comment by ask2018** [comment]
> Dont use electron, use c++, c# with net framework, java with old ...

It is not about if I want to use electron or something else. That I can do only on my own project. But if I want to use software other people are creating, I have no power to force them not to use electron. And the reality is lot of projects with no or bad alternative using electron. That means I'm forced to use such electron based projects as well - no matter if I like they are electron based or not. It is not possible to code everything on your own even if you have the skills. Day have only 24 hours :)
