### ISSUE TITLE
[Bug]: title bar and menu can still show up sometimes after calling setKiosk(true)

### ISSUE THREAD

**Issue by guoqikai** [electron/electron#38261]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.3.0

### What operating system are you using?

macOS

### Operating System Version

13.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

title bar shouldn't show when user hover on the top after entering kiosk mode

### Actual Behavior

70% of the time the title bar will show up.

### Testcase Gist URL

https://gist.github.com/aeeec2c228c56ff23b9d18d10588ba51

**Comment by DarshanDixit05** [comment]
Hi 👋, I want to work on this issue. Can you please assign it to me?
