### ISSUE TITLE
[Bug]: The zoom out button of the window cannot be displayed properly

### ISSUE THREAD

**Issue by gjcf** [electron/electron#38289]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.9

### What operating system are you using?

Windows

### Operating System Version

windows10，windows11, windows8, windows7

### What arch are you using?

x64

### Expected Behavior

During the process of using the BrowserWindow instance option, "titleBarStyle: hidden" and "titleBarOverlay: true" were set, and then the window's setMinimizable (false) was set through ipc; setMaximizable(false);  setClosable(false); The result is obvious that the zoom in and zoom in buttons are hidden, and the close button is disabled and displayed. This is normal, but setMinimizable (true) is set in reverse through ipc; setMaximizable(true);  setClosable(true); The results show that the close button, zoom in button, and zoom out button are displayed normally

### Actual Behavior

During the process of using the BrowserWindow instance option, "titleBarStyle: hidden" and "titleBarOverlay: true" were set, and then the window's setMinimizable (false) was set through ipc; setMaximizable(false);  setClosable(false); The result is obvious that the zoom in and zoom in buttons are hidden, and the close button is disabled and displayed. This is normal, but setMinimizable (true) is set in reverse through ipc; setMaximizable(true);  setClosable(true); The result shows that the close button and zoom in button are displayed normally, while the zoom out button cannot be displayed

**Comment by gjcf** [comment]
Testcase Gist URL: https://gist.github.com/b694a68a0aaeb172d4b261be09389941

Could you please take a look at the leaders of the Electron team? We really need this requirement

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
