### ISSUE TITLE
[Bug]: freeze if pass additionalArguments: "--wait-for-debugger" in to new BrowserWindow

### ISSUE THREAD

**Issue by Megabyteceer** [electron/electron#38283]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro N for Workstations 22H2 build 19045.2965

### What arch are you using?

x64

### Last Known Working Electron version

not found

### Expected Behavior

My goal is debug render process without debugging main process.
I run electron without any debug arguments and then pass debug arguments in to new BrowserWindow:

```
new BrowserWindow({
  webPreferences: {
    preload: path.join(__dirname, 'preload.js'),
    additionalArguments: [
      "--remote-debugging-port=9223",
      "--wait-for-debugger"
    ]
  }
});
```

I expect Electron Render process waits for debugger with debug port open

### Actual Behavior

Electron shows empty window, and freezes for 60 seconds and then unfreeze and work normally without debugger port open. If i open built in electron devTools - it is not connected to webpage.

I have checked all network activity on local machine. There is no any new port open when electron freezes with   additionalArguments: ["--wait-for-debugger"]

### Testcase Gist URL

https://gist.github.com/de0a78c1ffa9d59b8c6cc16e47762c94

**Comment by espeluznante** [comment]
Same behavior on linux. "--remote-debugging-port=" just ignoring if set in additionalArguments

**Comment by MarshallOfSound** [comment]
`--remote-debugging-port` has to be set in the main process not for a single renderer process, what you're trying to do is not possible / supported by Chromium
