### ISSUE TITLE
[Bug]: KIOSK Mode allows the user to leave via keyboard shortcuts and touchpad gestures

### ISSUE THREAD

**Issue by valueerrorx** [electron/electron#38286]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.0

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Expected Behavior

KIOSK mode should keep the electron window above others (notifications, screensaver, taskbar, ..) and prevent the user from leaving it.

### Actual Behavior

Keyboardshortcuts and Swipe gestures trigger operating system functions that for example let the user switch to another application on Windows.

### Additional Information

It isn't possible to capture strg+alt+entf but every other key combination is possible with something like this:
https://gitlab.com/valueerror/next-exam/-/tree/master/student/disable-shortcuts

3FingerSlideUp always triggers the taskview so it's easy to see other applications and leave the kiosk mode

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
