### ISSUE TITLE
[Bug]: Software Can not launch when it is installed on non-C drive on Windows 11 Home Edition

### ISSUE THREAD

**Issue by as1006** [electron/electron#38284]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home Edition

### What arch are you using?

x64

### Expected Behavior

Can Launch

### Actual Behavior

Click application.exe, and not launch when it is installed on a non-C drive on Windows 11

### Additional Information

Unfortunately, On Windows 11 Home Edition 22H2 22621.1555, when our software is installed on a non-C drive, it can't be launched. We also tried the demo application of electron, and tried electron 16.0.7, electron 22.0.0, electron 24.0.0, all of which have this problem.

>	ACLOS.exe!logging::LogMessage::~LogMessage() 行 959	C++
 	ACLOS.exe!content::`anonymous namespace'::IntentionallyCrashBrowserForUnusableGpuProcess() 行 440	C++
 	ACLOS.exe!content::GpuDataManagerImplPrivate::FallBackToNextGpuMode() 行 1712	C++
 	ACLOS.exe!content::GpuDataManagerImpl::FallBackToNextGpuMode() 行 378	C++
 	ACLOS.exe!content::GpuProcessHost::RecordProcessCrash() 行 1359	C++
 	ACLOS.exe!content::GpuProcessHost::OnProcessCrashed(int exit_code) 行 993	C++
 	ACLOS.exe!content::BrowserChildProcessHostImpl::OnChildDisconnected() 行 486	C++
 	ACLOS.exe!IPC::internal::MessagePipeReader::OnPipeError(unsigned int error) 行 178	C++
 	[内联框架] ACLOS.exe!base::OnceCallback<void ()>::Run() 行 145	C++
 	ACLOS.exe!mojo::InterfaceEndpointClient::NotifyError(const absl::optional<mojo::DisconnectReason> & reason) 行 729	C++
 	ACLOS.exe!IPC::`anonymous namespace'::ChannelAssociatedGroupController::NotifyEndpointOfError(IPC::`anonymous namespace'::ChannelAssociatedGroupController::Endpoint * endpoint, bool force_async) 行 888	C++
 	ACLOS.exe!IPC::`anonymous namespace'::ChannelAssociatedGroupController::OnPipeError() 行 870	C++
 	[内联框架] ACLOS.exe!base::OnceCallback<void ()>::Run() 行 145	C++
 	[内联框架] ACLOS.exe!mojo::Connector::HandleError(bool force_pipe_reset, bool force_async_handler) 行 688	C++
 	[内联框架] ACLOS.exe!mojo::Connector::OnHandleReadyInternal(unsigned int result) 行 442	C++
 	[内联框架] ACLOS.exe!mojo::Connector::OnWatcherHandleReady(unsigned int result) 行 422	C++
 	[内联框架] ACLOS.exe!base::internal::FunctorTraits<void (mojo::Connector::*)(unsigned int),void>::Invoke(void(mojo::Connector::*)(unsigned int) method, mojo::Connector * && receiver_ptr, unsigned int && args) 行 647	C++
 	[内联框架] ACLOS.exe!base::internal::InvokeHelper<0,void,0>::MakeItSo(void(mojo::Connector::*)(unsigned int) & functor, const std::Cr::tuple<base::internal::UnretainedWrapper<mojo::Connector,base::RawPtrBanDanglingIfSupported>> & bound, unsigned int && args) 行 826	C++
 	[内联框架] ACLOS.exe!base::internal::Invoker<base::internal::BindState<void (mojo::Connector::*)(unsigned int),base::internal::UnretainedWrapper<mojo::Connector,base::RawPtrBanDanglingIfSupported>>,void (unsigned int)>::RunImpl(void(mojo::Connector::*)(unsigned int) & functor, const std::Cr::tuple<base::internal::UnretainedWrapper<mojo::Connector,base::RawPtrBanDanglingIfSupported>> & bound, std::Cr::integer_sequence<unsigned long long,0> seq, unsigned int && unbound_args) 行 920	C++
 	ACLOS.exe!base::internal::Invoker<base::internal::BindState<void (mojo::Connector::*)(unsigned int),base::internal::UnretainedWrapper<mojo::Connector,base::RawPtrBanDanglingIfSupported>>,void (unsigned int)>::Run(base::internal::BindStateBase * base, unsigned int unbound_args) 行 887	C++
 	[内联框架] ACLOS.exe!base::RepeatingCallback<void (unsigned int)>::Run(unsigned int args) 行 267	C++
 	[内联框架] ACLOS.exe!mojo::SimpleWatcher::DiscardReadyState(const base::RepeatingCallback<void (unsigned int)> & callback, unsigned int result, const mojo::HandleSignalsState & state) 行 192	C++
 	[内联框架] ACLOS.exe!base::internal::FunctorTraits<void (*)(const base::RepeatingCallback<void (unsigned int)> &, unsigned int, const mojo::HandleSignalsState &),void>::Invoke(void(*)(const base::RepeatingCallback<void (unsigned int)> &, unsigned int, const mojo::HandleSignalsState &) & function, const base::RepeatingCallback<void (unsigned int)> & args, unsigned int && args, const mojo::HandleSignalsState & args) 行 537	C++
 	[内联框架] ACLOS.exe!base::internal::InvokeHelper<0,void,0>::MakeItSo(void(*)(const base::RepeatingCallback<void (unsigned int)> &, unsigned int, const mojo::HandleSignalsState &) & functor, const std::Cr::tuple<base::RepeatingCallback<void (unsigned int)>> & bound, unsigned int && args, const mojo::HandleSignalsState & args) 行 826	C++
 	[内联框架] ACLOS.exe!base::internal::Invoker<base::internal::BindState<void (*)(const base::RepeatingCallback<void (unsigned int)> &, unsigned int, const mojo::HandleSignalsState &),base::RepeatingCallback<void (unsigned int)>>,void (unsigned int, const mojo::HandleSignalsState &)>::RunImpl(void(*)(const base::RepeatingCallback<void (unsigned int)> &, unsigned int, const mojo::HandleSignalsState &) & functor, const std::Cr::tuple<base::RepeatingCallback<void (unsigned int)>> & bound, std::Cr::integer_sequence<unsigned long long,0> seq, unsigned int && unbound_args, const mojo::HandleSignalsState & unbound_args) 行 920	C++
 	ACLOS.exe!base::internal::Invoker<base::internal::BindState<void (*)(const base::RepeatingCallback<void (unsigned int)> &, unsigned int, const mojo::HandleSignalsState &),base::RepeatingCallback<void (unsigned int)>>,void (unsigned int, const mojo::HandleSignalsState &)>::Run(base::internal::BindStateBase * base, unsigned int unbound_args, const mojo::HandleSignalsState & unbound_args) 行 884	C++
 	[内联框架] ACLOS.exe!base::RepeatingCallback<void (unsigned int, const mojo::HandleSignalsState &)>::Run(unsigned int args, const mojo::HandleSignalsState & args) 行 267	C++
 	ACLOS.exe!mojo::SimpleWatcher::OnHandleReady(int watch_id, unsigned int result, const mojo::HandleSignalsState & state) 行 278	C++
 	[内联框架] ACLOS.exe!base::OnceCallback<void ()>::Run() 行 145	C++
 	ACLOS.exe!base::TaskAnnotator::RunTaskImpl(base::PendingTask & pending_task) 行 134	C++
 	[内联框架] ACLOS.exe!base::TaskAnnotator::RunTask(perfetto::StaticString event_name, base::PendingTask & pending_task, base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl::<lambda_0> && args) 行 72	C++
 	[内联框架] ACLOS.exe!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow * continuation_lazy_now) 行 441	C++
 	ACLOS.exe!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() 行 297	C++
 	ACLOS.exe!base::MessagePumpForUI::DoRunLoop() 行 215	C++
 	ACLOS.exe!base::MessagePumpWin::Run(base::MessagePump::Delegate * delegate) 行 79	C++
 	ACLOS.exe!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool application_tasks_allowed, base::TimeDelta timeout) 行 603	C++
 	ACLOS.exe!base::RunLoop::Run(const base::Location & location) 行 143	C++
 	ACLOS.exe!content::BrowserMainLoop::RunMainMessageLoop() 行 1050	C++
 	ACLOS.exe!content::BrowserMainRunnerImpl::Run() 行 163	C++
 	ACLOS.exe!content::BrowserMain(content::MainFunctionParams parameters) 行 30	C++
 	ACLOS.exe!content::RunBrowserProcessMain(content::MainFunctionParams main_function_params, content::ContentMainDelegate * delegate) 行 716	C++
 	ACLOS.exe!content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams main_params, bool start_minimal_browser) 行 1257	C++
 	ACLOS.exe!content::ContentMainRunnerImpl::Run() 行 1116	C++
 	ACLOS.exe!content::RunContentProcess(content::ContentMainParams params, content::ContentMainRunner * content_main_runner) 行 346	C++
 	ACLOS.exe!content::ContentMain(content::ContentMainParams params) 行 374	C++
 	ACLOS.exe!wWinMain(HINSTANCE__ * instance, HINSTANCE__ *, wchar_t * cmd, int) 行 244	C++
 	[外部代码]

**Comment by as1006** [comment]
我们找到问题，用户电脑上D盘目录有时候会多两个安全访问权限是未知账户，这两个账户是父目录继承下来的，暂时还不知道是如何出现的这个问题。但是我引导用户删除那两个未知账户之后，electron应用就能正常在D盘被拉起
-------------
We found the reason. Sometimes there are two more accounts with unknown security access permissions in the D drive directory on the user's computer. These two accounts are inherited from the parent directory. We don't know how this problem occurs for the time being. But after I guide the user to delete the two unknown accounts, the electron application can be pulled up normally on the D drive
![image](https://github.com/electron/electron/assets/5902481/67e7246c-6b18-4871-951a-e05f010d98c1)

**Comment by dsanders11** [comment]
@as106, sounds like it was misconfiguration specific to that user's machine? I'm going to close this issue, but if that is not correct, ping me and I'll reopen. 🙂

**Comment by as1006** [comment]
@dsanders11 . Although it is a issue with misconfiguration specific machines, other programs can run normally on these machines, but electron cannot. Is the compatibility of electron not good enough in this case?

**Comment by dsanders11** [comment]
@as1006, if you can determine a small reproduce case for the issue, then it could be looked at. Without actionable details, there is not enough information here for Electron maintainers to do anything.

**Comment by mushan0x0** [comment]
bump

**Comment by mushan0x0** [comment]
> @as1006, if you can determine a small reproduce case for the issue, then it could be looked at. Without actionable details, there is not enough information here for Electron maintainers to do anything.

https://github.com/electron/electron/issues/36637 @dsanders11 Here is the repository for reproduction.

**Comment by mushan0x0** [comment]
https://github.com/electron/electron/issues/35180 Similar issues.
