### ISSUE TITLE
[Bug]: Segmentation fault in CommonEnvironmentSetup::event_loop with Electron 17.0.0

### ISSUE THREAD

**Issue by locomotiveboy** [electron/electron#38296]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

No segmentation fault

### Actual Behavior

Process:               同频协作 [90643]
Path:                  /Applications/同频协作.app/Contents/MacOS/同频协作
Identifier:            同频协作
Version:               1.1.1 (1.1.1)
Code Type:             X86-64 (Native)
Parent Process:        同频协作 [90630]
Responsible:           同频协作 [90630]
User ID:               501

Date/Time:             2023-05-13 10:48:24.718 +0800
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        E34DBBA3-E207-B59F-F92D-23E26527B88E

Sleep/Wake UUID:       9FC6A93F-25AF-4CB3-B1E0-21C9AAEB4514

Time Awake Since Boot: 14000 seconds
Time Since Wake:       140 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [90643]

VM Regions Near 0x20:
--> 
    __TEXT                 000000010aad0000-000000010aad2000 [    8K] r-x/r-x SM=COW  /Applications/同频协作.app/Contents/MacOS/同频协作

Application Specific Information:
crashed on child side of fork pre-exec

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	0x00007fff7222ce41 nanov2_forked_calloc + 7
1   libsystem_malloc.dylib        	0x00007fff72217f59 malloc_zone_calloc + 99
2   libsystem_malloc.dylib        	0x00007fff72217ed9 calloc + 24
3   libobjc.A.dylib               	0x00007fff70eac603 allocateBuckets(unsigned int) + 29
4   libobjc.A.dylib               	0x00007fff70eac096 cache_fill + 283
5   libobjc.A.dylib               	0x00007fff70eabb27 lookUpImpOrForward + 530
6   libobjc.A.dylib               	0x00007fff70eab399 _objc_msgSend_uncached + 73
7   libxpc.dylib                  	0x00007fff722b689e xpc_atfork_child + 125
8   libSystem.B.dylib             	0x00007fff6f043ab8 libSystem_atfork_child + 59
9   libsystem_c.dylib             	0x00007fff720bf8ad fork + 40
10  com.github.Electron.framework 	0x00000001110e2c87 node::CommonEnvironmentSetup::event_loop() const + 21126951
11  com.github.Electron.framework 	0x00000001110e58b5 node::CommonEnvironmentSetup::event_loop() const + 21138261
12  com.github.Electron.framework 	0x00000001110e4a5c node::CommonEnvironmentSetup::event_loop() const + 21134588
13  com.github.Electron.framework 	0x00000001110ef499 node::CommonEnvironmentSetup::event_loop() const + 21178169
14  com.github.Electron.framework 	0x00000001110eca45 node::CommonEnvironmentSetup::event_loop() const + 21167333
15  com.github.Electron.framework 	0x000000010ab2e353 node::FreeIsolateData(node::IsolateData*) + 76083
16  com.github.Electron.framework 	0x000000010ab2f9c7 node::FreeIsolateData(node::IsolateData*) + 81831
17  com.github.Electron.framework 	0x000000010ab2f312 node::FreeIsolateData(node::IsolateData*) + 80114
18  com.github.Electron.framework 	0x000000010bb2d1fb v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) + 12651
19  ???                           	0x0000003a07f0aa38 0 + 249241315896
20  ???                           	0x0000003a07e8c862 0 + 249240799330
21  ???                           	0x0000003a07e8c862 0 + 249240799330
22  ???                           	0x0000003a07e8c862 0 + 249240799330
23  ???                           	0x0000003a07e8c862 0 + 249240799330
24  ???                           	0x0000003a07e8c862 0 + 249240799330
25  ???                           	0x0000003a07e8c862 0 + 249240799330
26  ???                           	0x0000003a07e8c862 0 + 249240799330
27  ???                           	0x0000003a07e8c862 0 + 249240799330
28  ???                           	0x0000003a07e8c862 0 + 249240799330
29  ???                           	0x0000003a07e8c862 0 + 249240799330
30  ???                           	0x0000003a07e8c862 0 + 249240799330
31  ???                           	0x0000003a07e8c862 0 + 249240799330
32  ???                           	0x0000003a07e8c862 0 + 249240799330
33  ???                           	0x0000003a0004c24f 0 + 249108415055
34  ???                           	0x0000003a07e8c862 0 + 249240799330
35  ???                           	0x0000003a07e8c862 0 + 249240799330
36  ???                           	0x0000003a07e8c862 0 + 249240799330
37  ???                           	0x0000003a07e8c862 0 + 249240799330
38  ???                           	0x0000003a07e8c862 0 + 249240799330
39  ???                           	0x0000003a07e8c862 0 + 249240799330
40  ???                           	0x0000003a07e8a89c 0 + 249240791196
41  ???                           	0x0000003a07e8a5c7 0 + 249240790471
42  com.github.Electron.framework 	0x000000010bbfd1cc v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 684
43  com.github.Electron.framework 	0x000000010baddff9 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 713
44  com.github.Electron.framework 	0x00000001111658ac node::EmitAsyncDestroy(node::Environment*, node::async_context) + 273612
45  com.github.Electron.framework 	0x00000001111669ed node::EmitAsyncDestroy(node::Environment*, node::async_context) + 278029
46  com.github.Electron.framework 	0x000000011116673b node::EmitAsyncDestroy(node::Environment*, node::async_context) + 277339
47  com.github.Electron.framework 	0x000000011112055d node::LoadEnvironment(node::Environment*, std::__1::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>) + 109
48  com.github.Electron.framework 	0x000000010ac48da7 v8::CodeEvent::GetScriptName() + 197335
49  com.github.Electron.framework 	0x000000010abc204a v8::internal::compiler::RawMachineAssembler::TargetParameter() + 8874
50  com.github.Electron.framework 	0x000000010cc103ff v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5177855
51  com.github.Electron.framework 	0x000000010cc13bc8 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5192136
52  com.github.Electron.framework 	0x000000010cc0fb18 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5175576
53  com.github.Electron.framework 	0x000000010adc5255 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 1957
54  com.github.Electron.framework 	0x000000010adc6423 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 6515
55  com.github.Electron.framework 	0x000000010adc5ea1 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 5105
56  com.github.Electron.framework 	0x000000010adc445d v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 12189
57  com.github.Electron.framework 	0x000000010adc4d93 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 739
58  com.github.Electron.framework 	0x000000010aaf7be8 ElectronMain + 152
59  libdyld.dylib                 	0x00007fff7205fcc9 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007fff7222ce3a  rbx: 0x0000000000000004  rcx: 0x00007fff70eca140  rdx: 0x0000000000000001
  rdi: 0x0000000000000000  rsi: 0x0000000000000040  rbp: 0x00007ffee512c1f0  rsp: 0x00007ffee512c1c8
   r8: 0x0000000000000003   r9: 0x00007ffee512c268  r10: 0x0000000100000000  r11: 0x00007ffee512c260
  r12: 0x00007fff98b91000  r13: 0x00007fff98b9e6e8  r14: 0x0000000000000001  r15: 0x0000000000000040
  rip: 0x00007fff7222ce41  rfl: 0x0000000000010246  cr2: 0x0000000000000020
  
Logical CPU:     2
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

**Comment by codebytere** [comment]
@locomotiveboy Electron v17 is no longer supported. For us to continue triage, you must demonstrate that this occurs on a [supported version](https://www.electronjs.org/docs/latest/tutorial/electron-timelines)

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
