### ISSUE TITLE
[Bug]: Buffer + Fetch cause renderer process crash

### ISSUE THREAD

**Issue by kewde** [electron/electron#38295]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.3.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux dev 5.10.0-20-amd64 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

Fetch does not crash when its body is a string from Buffer object.

### Actual Behavior

Renderer process crashes upon large fetch request:
* if the body string is generated from a Buffer.
* nodeIntegration: true,
*  contextIsolation: false,

```
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
```

```js
// NO CRASH
const payload = "aa".repeat(2 * 1000 * 1000)

// DOES CRASH
const payload = Buffer.from("aa".repeat(2 * 1000 * 1000), 'hex').toString('hex')

const response = await fetch("https://www.toptal.com/developers/postbin/1684149488352-0371321751736", {
  method: "POST", 
  body: payload,
});
```

### Testcase Gist URL

https://github.com/kewde/electron-fetch-crash

### Additional Information

Does not crash in 24.0.0 and upwards.

**Comment by nkumawat34** [comment]
Can i work on this bug..

**Comment by kewde** [comment]
@nkumawat34 Yes, you are very welcome to! 😄

**Comment by codebytere** [comment]
Closing as all currently supported versions do not crash.
