### ISSUE TITLE
Improve Type Union Typings in the Docs

### ISSUE THREAD

**Issue by dsanders11** [electron/electron#38339]
[The phrasings that `electron/docs-parser` recognizes for string union types](https://github.com/electron/docs-parser/blob/c56164b4cebcf010306e0458729bf179bf69e650/src/markdown-helpers.ts#L459) is fairly narrow, and it looks like there's a handful of places in the docs where the phrasing is not being picked up as string union types.

Fix these and add smoke tests with `// @ts-expect-error` to ensure type unions are being used. See #38336 for an example.

Alternatively, extend the phrasings that `electron/docs-parser` recognizes, and add the smoke tests.

A (possibly non-exhaustive) list of ones which aren't being picked up. There's [an upstream issue](https://github.com/electron/docs-parser/issues/88) preventing certain values from being picked up.

https://github.com/electron/electron/blob/2a16c73834358f85ef20c07e50dfb5178c30bb1e/docs/api/webview-tag.md?plain=1#L1091-L1093

https://github.com/electron/electron/blob/2a16c73834358f85ef20c07e50dfb5178c30bb1e/docs/api/web-contents.md?plain=1#L796-L798

https://github.com/electron/electron/blob/2a16c73834358f85ef20c07e50dfb5178c30bb1e/docs/api/native-image.md?plain=1#L308-L309

https://github.com/electron/electron/blob/2a16c73834358f85ef20c07e50dfb5178c30bb1e/docs/api/session.md?plain=1#L577-L580

https://github.com/electron/electron/blob/2a16c73834358f85ef20c07e50dfb5178c30bb1e/docs/api/session.md?plain=1#L581-L582

https://github.com/electron/electron/blob/e08c583dea42ce70c926825a2f6d455bbddf2089/docs/api/desktop-capturer.md?plain=1#L91-L92

**Comment by avionicharshit-byte** [comment]
I wanna pick this issue, allow me to contribute it

**Comment by saloni0419** [comment]
hey, I want to solve this issue can you please assign me this

**Comment by sr-04** [comment]
Anyone working on this?

**Comment by dsanders11** [comment]
If anyone wants to work on this, please just create a PR rather then comment here. If a PR mentions this issue it will be visible here, so in the absence of said linked PRs, please feel free to create a PR - we don't assign issues like this to external contributors. 🙂
