### ISSUE TITLE
[Bug]: Electron exited with signal SIGKILL

### ISSUE THREAD

**Issue by sriharivishnu** [electron/electron#38372]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.3.3

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The application starts without any errors as indicated in the electron tutorial Quick Start: https://www.electronjs.org/docs/latest/tutorial/quick-start

### Actual Behavior

```
-> % npm start --verbose
npm verb cli [
npm verb cli   '/Users/sriharivishnu/.nvm/versions/node/v14.18.1/bin/node',
npm verb cli   '/Users/sriharivishnu/.nvm/versions/node/v14.18.1/bin/npm',
npm verb cli   'start',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@8.5.2
npm info using node@v14.18.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/Users/sriharivishnu/.nvm/versions/node/v14.18.1/lib/node_modules/npm/npmrc Completed in 3ms
npm timing config:load:builtin Completed in 3ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/Users/sriharivishnu/dev/testcase/.npmrc Completed in 0ms
npm timing config:load:project Completed in 5ms
npm timing config:load:file:/Users/sriharivishnu/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/Users/sriharivishnu/.nvm/versions/node/v14.18.1/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 14ms
npm timing npm:load:configload Completed in 14ms
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 3ms
npm timing npm:load:display Completed in 6ms
npm verb logfile /Users/sriharivishnu/.npm/_logs/2023-05-18T05_32_44_235Z-debug-0.log
npm timing npm:load:logFile Completed in 5ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 26ms

> testcase@1.0.0 start
> electron .

/Users/sriharivishnu/dev/testcase/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGKILL
npm timing command:run-script Completed in 246ms
npm timing command:start Completed in 248ms
npm verb exit 1
npm timing npm Completed in 374ms
npm verb code 1
```

and the application exits. I tried adding and index.html and loading it from main.js, but still no luck - same error.

### Additional Information

Steps to Reproduce:
- npm init (and run through initialization process described in quick start)
- npm install --save-dev electron
- add `"start": "electron ."` to package.json scripts
- run `npm start` and observe crash

---
Chip: Apple M1 Max
Node Version: 14.8.1
NPM version: 8.5.2

There are only 3 files: main.js, package.json, and package.lock.

main.js is empty.
package.json:
```
{
  "name": "testcase",
  "version": "1.0.0",
  "description": "Test app",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "author": "Srihari Vishnu",
  "license": "ISC",
  "devDependencies": {
    "electron": "^24.3.1"
  }
}
```

package-lock.json

**Comment by VerteDinde** [comment]
Hey @sriharivishnu, I think another issue you may be having is that you're using Node 14. If I recall correctly, Node 14 doesn't play very well on arm64 Macs by default. Could you try using using Node 16 (`nvm install 16 && nvm use 16` if you're using nvm) and see if that works?

**Comment by sriharivishnu** [comment]
> Hey @sriharivishnu, I think another issue you may be having is that you're using Node 14. If I recall correctly, Node 14 doesn't play very well on arm64 Macs by default. Could you try using using Node 16 (`nvm install 16 && nvm use 16` if you're using nvm) and see if that works?

This fix worked for me! Thank you!

**Comment by nickjuntilla** [comment]
Also doesn't work with node 18 on mac with arm processor.
