### ISSUE TITLE
`autoUpdater.quitAndInstall` does not cause application to emit normal quit events

### ISSUE THREAD

**Issue by wearhere** [electron/electron#3837]
When `app.quit` is called, `app` will emit `'before-quit'`, `'will-quit'`, and so on. When the application is quit by calling `autoUpdater.quitAndInstall`, these events are not emitted.

**Comment by zcbenz** [comment]
Doing this will change behaviors of existing apps, I don't think we should do that, no matter whether it is good or not.

If you really want this behavior you can just monkey-patch the `autoUpdater.quitAndInstall` method in your app.

**Comment by wearhere** [comment]
Hm, I can see how emitting the events would be a breaking change. Don't you agree that this is a bug though? I don't see why we would not want to broadcast that the app was quitting, and so give modules the ability to clean up or even abort the quit, in this case vs. a regular quit.

Perhaps we keep it open/slated for the next major release? (In the semver sense, where a release is understood to contain breaking changes.)

**Comment by wearhere** [comment]
I can indeed work around in this in my application. It would be much better if it were fixed in core though—assuming that 'before-quit' would be fired, I got bitten by a bug where:

1. I have a "main" window that can never be closed, only hidden—it normally prevents the 'close' event and hides itself. This is how many Mac apps behave.
2. But the main window will allow itself to be closed if the app is quitting—it deregisters the 'close' listener on 'before-quit'.
3. But since 'before-quit' is not emitted when auto-updating, and the app only quits when all windows have been closed, the app would never quit when the user said 'quit and install'—auto-updates are thus broken in production for me. :(

I'd like to save other developers from this. Or, we should amend the 'before-quit' documentation to this effect—but it'd be better if it were consistent.

**Comment by zcbenz** [comment]
After a closer look I found autoUpdater behaves differently on Windows, it uses `app.quit` to quit the program so `quitAndInstall` will emit quit events there. It makes this issue a bug then, I'm now :+1: on changing the behavior on OS X to follow the behavior on Windows.

**Comment by kainosnoema** [comment]
We also just ran into this problem, and are having quite a bit of trouble getting `quitAndInstall` to work at all. Currently all windows are being closed, but the app never quits. We've checked all our code to make sure nothing's preventing it from quitting, but since no `before-quit` or `will-quit` events are being emitted, it's difficult to debug.

+1 on making the behavior consistent with Windows.

**Comment by Aluxian** [comment]
My app calls quitAndInstall in the `will-quit` event listener if an update has been downloaded already (and calls `event.preventDefault()` too). It works flawlessly on OS X, however, it hangs on Windows. The behaviour is similar to what @kainosnoema reported: `before-quit` is emitted, windows are closed, `will-quit` is emitted, I call `quitAndInstall()`, the app is updated but it doesn't quit. It's as if [this call](https://github.com/atom/electron/blob/dd158e172f279d224cc1de91c536e97418e64842/lib/browser/api/auto-updater/auto-updater-win.js#L16) isn't executed at all.

**Comment by zcbenz** [comment]
I'm not able to reproduce this in v1.2.2 anymore.
