### ISSUE TITLE
[Feature Request]: printToPDF flatten annotations

### ISSUE THREAD

**Issue by maxvinten** [electron/electron#38380]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I'm creating an electron application that merges several PDFs of images of several formats to a single PDF, and then prints it via node-printer.
Unfortunately passing the file to the printer using Node-Printer malforms the annotations/ink at the time of printing. Printing the output file from edge prints everything flawlessly.
I tried pdf-to-printer, but it was too slow (and has now been archived?). I tried electron-pdf-window, but it didn't recognise the PDF as part of the webcontents, so printed X pages of the pdf as blank pages when print was called from code. I tried a hidden electron window, but it's not possible to print from the plugin, according to another issue. I tried rasterising the pdf using ghostscript, but the annotation/ink resolution is low and can't be changed in settings. I've tried a bunch of different ways...

### Proposed Solution

Flattening or "Rasterising" the pdf natively via the printToPDF function. This solidifies the output file which can't then be malformed after the fact. Also allows native creation of "finalised" uneditable PDFs for other applications.

### Alternatives Considered

As mentioned above, different print libraries, external dependencies (imagemagick, PDFtk, Ghostscript), exec functions have all yeilded less than desirable results. If I could use the native features of electron for silently outputting a finalised file... It qould be magic. Happy to answer any other questions about methods tried, I'm a few deep now and can't remember them all.

**Comment by maxvinten** [comment]
I don't know if this is as much of a bug report, rather a feature request. I struggled to get PDFs from my app to the printer in the same format that the files appeared on my screen. While Electron has a printToPDF function which I was hoping to use for PDF flattening, it only seems to work for webcontents (which I couldn't find a way to load a PDF into)/ and wasn't very helpful in processing existing PDFs.
The library I found to achieve my goal was Poppler-PDF, which uses Poppler to output each PDF page with annotations to a flat jpeg, and then PDF-lib to recompile the PDF from the converted pages.

The more I revise what I'm writing in here, the more it feels like this isn't in Electron's court. 😅 But with printToPDF being an existing feature, it would just be cool to have this feature set expanded to allow for PDF input and flattened PDF output.

**Comment by codebytere** [comment]
Yeah - this is unfortunately not something that our team will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
