### ISSUE TITLE
[Bug]: getCaptureHandle not working

### ISSUE THREAD

**Issue by t57ser** [electron/electron#38381]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0-beta.7

### What operating system are you using?

Windows

### Operating System Version

10.0.19042

### What arch are you using?

x64

### Expected Behavior

Calling `getCaptureHandle` on a video track should return the shared data
See: https://developer.chrome.com/docs/web-platform/capture-handle/

### Actual Behavior

Always returns null

### Testcase Gist URL

https://gist.github.com/t57ser/919ff9c9fe623b51fde41772bf4c9207

### Additional Information

Steps to reproduce:
After starting the shared gist, click on the "open presentation" button
This opens a new window with the content that will be shared
Afterwards click "capture"
The content can be seen (shared)

The issue here is that the following text:
"Try sharing a tab that exposes information to capturing applications instead."
should display shared information by the content

**Comment by codebytere** [comment]
@t57ser figured out a fix i think - i'll get it up into a PR monday
