### ISSUE TITLE
Change window icon dynamically

### ISSUE THREAD

**Issue by sapioit** [electron/electron#3839]
Hello,

I recently tried to change the icon of [my app](https://github.com/sapioit/zFacebook), and noticed is a real headache. So, I came here requesting BrowserWindow to have a method of having it's icon changed, at will, without changing anything about the executable files. I know there are ways if doing that natively, on Windows and Linux, but such thing does not exists implemented into the app itself.

I'd like to have the icon in cause be changed to a different one, when the state of the app changes. For example, when it's done doing something and waits for user input, I'd like to have it chance it's icon, yet I see no way to do so. I tried the following, out of which none worked, so far:

main.js
```node
 var app = require('app');
 var BrowserWindow = require('browser-window');
 require('crash-reporter').start();

 var mainWindow = null;

 app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
   app.quit();
 });

 app.on('ready', function() {
  mainWindow = new BrowserWindow({
   width: 700,
   height: 850,
   resizable: true,
   title: "zFacebook",
   icon: "/zFacebook.icns",
   icon: "/zFacebook.ico",
   icon: "/zFacebook.png"
  });
  mainWindow.setOverlayIcon(
   __dirname + "/zFacebook.png",
   "Test?");
  mainWindow.setTitle("zFacebook");
  mainWindow.loadUrl('file://' + __dirname + '/index.html');
  mainWindow.focus();
  mainWindow.on('closed', function() {
   mainWindow = null;
  });
  //mainWindow.toggleDevTools();
 });
```
index.html
```html
<!DOCTYPE html>
<html>
 <head>
  <title>zFacebook</title>
  <link rel="icon" href="/zFacebook.incs">
  <link rel="icon" href="/zFacebook.ico">
  <link rel="icon" href="/zFacebook.png">
 </head>
 <body style="overflow:hidden;">
  <webview id="webview" src="http://messenger.com" preload="" style="position:absolute;width:100%;height:100%;"></webview>
  <script>
   // need to have a script tag make webview work even if you don't plan to use it...
  </script>
 </body>
</html>
```
Help?

**Comment by paulcbetts** [comment]
Usually on Windows you'd do this via an Overlay icon, which is the `setOverlayIcon` method on BrowserWindow

**Comment by sapioit** [comment]
If you'd have checked, I already tried that... did not worked, for some reason... does that function just adds something on top of the existing icon? Because in my case it did nothing... nothing at all...
```node
mainWindow.setOverlayIcon(
   __dirname + "/zFacebook.png",
   "Test?");
```

**Comment by zcbenz** [comment]
`mainWindow.setOverlayIcon` works on my machine and I believe also on other people's, since there was no other report on this.

Please include a full example including the icon you used, also what's the version of Electron and Windows are you using?

**Comment by sapioit** [comment]
I was using what was the last version released, at the time, and tested it in the current version, as well...
The script is [this one](https://github.com/sapioit/zFacebook)

**Comment by zcbenz** [comment]
It seems to work on my machine?
<img width="216" alt="screen shot 2016-01-05 at 9 57 01 am" src="https://cloud.githubusercontent.com/assets/639601/12105755/c0c012a8-b392-11e5-85ea-b1342a528973.png">

**Comment by sapioit** [comment]
Strange. Even stranger is the size of the overlay. By that I mean that it's not entirely replacing the Electron logo.

**Comment by zcbenz** [comment]
That's what an overlay icon is supposed to do:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd391696(v=vs.85).aspx

**Comment by sapioit** [comment]
Than how do I change the whole icon, altogether? Because I couldn't find a method that worked... Even the overlay didn't worked for me...

**Comment by zcbenz** [comment]
There is currently no API to change window icon dynamically.

**Comment by sapioit** [comment]
But what about when the window object is made?

**Comment by zcbenz** [comment]
Windows uses exe's icon as task bar icon under most cases, the `icon` property only sets window icon.

**Comment by sashazxtt** [comment]
It appears that setOverlayicon doesn't work on Windows 7/8/8.1. It does work on Windows 10.
At least, that's what my experience is

**Comment by sondreb** [comment]
It's been some years since this issue was closed and I was wondering if there is a known way to update the icon while the app is running, or if this is something planned for the future?
