### ISSUE TITLE
[Feature Request]: Want to control whether mouse events pass through the BrowserWindow function

### ISSUE THREAD

**Issue by InhamiRei** [electron/electron#38396]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

My development environment：
window 10，x64，electron：24.3.1

My BrowserWindow is like this，i set，transparent: true，frame: false
```
    mainWindow = new BrowserWindow({
        width: 340,
        height: 340,
        x: width - 340 - 10,
        y: height - 340 - 10,
        autoHideMenuBar: true, // Hide menu bar
        transparent: true, // Set to transparent window
        frame: false, // Hide window border
        alwaysOnTop: true, // Window at top
        skipTaskbar: true, // Hide the taskbar icon
        resizable: false, // Prohibit changing window size
    });
```
![image](https://github.com/electron/electron/assets/53500845/6fc24958-d27f-4f3a-aacb-cdbdcf1afc4e)

My needs：Click on the transparent area and click on the mouse to penetrate, so that you can click on the following application. If you click on the flower, the mouse will not penetrate, but will still click on the flower to trigger some of the methods I wrote

I have already written a method for determining click transparency in renderer.js
```
mainWindow.setIgnoreMouseEvents(true);
```
I saw this feature and after setting it up, the entire window couldn't listen to my mouse anymore, so I couldn't click on the flower. I don't know what to do

### Proposed Solution

1. Can there be an attribute that allows this click event to penetrate
2. Or what method is there to add a window mouse movement event to the BrowserWindow，I can keep sending messages to renderer.js to see if the mouse position is in the transparent or flower area, to control whether the mouse penetrates, but I still need the mouse penetration attribute. setIgnoreMouseEvents does not listen to all mouse attributes
3. SetIgnoreMouseEvents can be parameterized, such as not listening for mouse movement, but listening for mouse clicks

### Alternatives Considered

I have thought of many methods, but none of them have worked，Double click is required to penetrate and conflicts with drag and drop

```
    ipcMain.on("mouse-click", (event, obj) => {
        console.log("obj", obj);
        // Make the mouse unable to penetrate
        mainWindow.setIgnoreMouseEvents(true);
        mainWindow.setIgnoreMouseEvents(true, { forward: true });
            // MouseInputEvent
            mainWindow.webContents.sendInputEvent({
                ...
            })
            // Let the mouse penetrate
            mainWindow.setIgnoreMouseEvents(false);
        }, 500);
    });
```

### Additional Information

I am a novice and have reviewed the entire document and some other people's questions. I have looked at examples in the official document
el.addEventListener('mouseenter', () => {
 ipcRenderer.send('set-ignore-mouse-events', true, { forward: true })})
el.addEventListener('mouseleave', () => {
 ipcRenderer.send('set-ignore-mouse-events', false)})
 
 When this element is set to 'set ignore mouse events', true, {forward: true}
The BrowserWindow has set win. setIgnoreMouseEvents (... args)
So isn't this win page unable to listen to mouse events? How do I know if it triggered mouseleave, which leads to the entire window being in a penetrating state
I don't understand

add：Just like this circular icon, clicking on it triggers other windows. Clicking on the blue icon should penetrate the application below. The circles inside may not necessarily be circular, but may be irregular shapes
![SLA 6%8LC6I55AGCRR~P798](https://github.com/electron/electron/assets/53500845/614f1447-d142-41c5-9414-65916d73cb05)

**Comment by InhamiRei** [comment]
sorry，i Got it

**Comment by agleis** [comment]
@InhamiRei what did you do to solve this issue? I am facing a similar issue and have not been able to make it work.

**Comment by InhamiRei** [comment]
> @InhamiRei what did you do to solve this issue? I am facing a similar issue and have not been able to make it work. @InhamiRei 你做了什么来解决这个问题？我面临类似的问题，但无法使其工作。
main.js
```
// 一开始给窗口设置允许鼠标穿透 Initially, set the window to allow mouse penetration
mainWindow.setIgnoreMouseEvents(true, { forward: true });
```

```
ipcMain.on("mouse-move", (event, obj) => {
    if (obj.ignore) {
        mainWindow.setIgnoreMouseEvents(true, { forward: true });
    } else {
        mainWindow.setIgnoreMouseEvents(false);
    }
});
```

render.js
```
if (rgba === "rgba(0,0,0,0)") {
    canvas.style.cursor = "default";
    window.mouseAPI.mouseMove({
        x: pos.x,
        y: pos.y,
        ignore: true,
        drap: false,
    });
    return false;
} else {
    canvas.style.cursor = "pointer";
    window.mouseAPI.mouseMove({
        x: pos.x,
        y: pos.y,
        ignore: false,
    });
    if (dis) {
        window.mouseAPI.mouseDrap(dis);
    }
    return true;
}
```

preload.js
```
contextBridge.exposeInMainWorld("mouseAPI", {
    mouseMove: (obj) => ipcRenderer.send("mouse-move", obj),
});
```

你能看得懂吗？
Can you understand these codes?
