### ISSUE TITLE
How to disable "web-security" in BrowserWindow?

### ISSUE THREAD

**Issue by kurdin** [electron/electron#384]
This is not working:

``` js
mainWindow = new BrowserWindow({
    width: 1100, 
    height: 800, 
    "web-preferences": {
      "web-security": false
    }
  });
```

Loading any external webpage with iframes will throw errors for every iframe on the page:
`Sandbox access violation: Blocked a frame at "http://cnn.com" from accessing a frame at "null".  The frame being accessed is sandboxed and lacks the "allow-same-origin" flag.`

This is not helping as well: 

``` html
<iframe sandbox="none" src="http://cnn.com"></iframe>
```

**Comment by mburakkalkan** [comment]
I don't know old versions have dashed property names but they are camelCased `webPreferences` and `webSecurity` not dashed for late versions:

```
mainWindow = new BrowserWindow({
    width: 1100, 
    height: 800,
    webPreferences: {
      webSecurity: false
    }
  });
```
