### ISSUE TITLE
autoUpdater does not emit an error if quitAndInstall is called without an update to apply

### ISSUE THREAD

**Issue by wearhere** [electron/electron#3840]
`autoUpdater`'s docs say that `quitAndInstall` should only be called after `'update-downloaded'` has been emitted, and if it is called _before_ that is emitted, the app will quit but not reopen.

For both these reasons, `autoUpdater` should emit an error (and not proceed to quit) if `quitAndInstall` is called without an update to apply.

**Comment by wearhere** [comment]
Tested by #3838. I would fix this, but I'm not sure if the fix needs to go in Electron or Squirrel.

**Comment by zcbenz** [comment]
Before someone cares to fix this, I think you can just check whether `update-downloaded` is fired before calling `quitAndInstall`.

**Comment by wearhere** [comment]
Oh for sure. I just think that the auto-updater itself should enforce that restriction since seeing an error is better UX than seeing the app quit and it not come back.

(One simple though perhaps not-totally-correct way to fix this would be to have the auto-updater itself listen for 'update-downloaded' and only allow `quitAndInstall` to be called thereafter—is that what you were suggesting?)
