### ISSUE TITLE
[Bug]: Out of Memory / 0x7ffbaf85cf19 Fatal Error: Out of Memory / 0x7ffbaf85cf19

### ISSUE THREAD

**Issue by Akash9773312** [electron/electron#38415]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

It throwing an oom error after every 2-3 days while it should not 

### Actual Behavior

It is throwing an OOM after 2-3 days of runtime

**Comment by dsanders11** [comment]
Hi @Akash9773312. I'm going to close this as it is not an actionable issue. Lots of things can cause OOM, and there's no information here to indicate if it's related to Electron, the app using Electron, or the system itself. If you can create a 

If you can create a small repro case with just Electron, we can reconsider this issue. For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
