### ISSUE TITLE
[Bug]: Application menu visible while embedded video is in fullscreen

### ISSUE THREAD

**Issue by c3er** [electron/electron#38414]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Expected Behavior

When a video is in fullscreen mode, only the video itself is visible, i.e. there is no menu on the screen.

### Actual Behavior

When a video is in fullscreen mode, the application menu bar stays visible on top of the screen. See the screenshot below.

![Upper left corner of fullscreen video](https://github.com/electron/electron/assets/24460532/35595370-7bf4-446a-890d-81468e2b9fe6)

### Additional Information

I observed this problem on Windows. I didn't try Linux. On macOS, the behavior is as expected; but the application menu is outside the window there.

I made a minimal Electron application, to show this bug: https://github.com/c3er/electron-fullscreen-issue

The important part of this demo is the `index.html` file that contains a `<video>` tag referencing a local video file (downloaded from https://samplelib.com/).

**Comment by Suvrajit69** [comment]
Hello, I am newbie.  Is this issue beginner friendly? what tech stack used in this project? what are the prerequisite for solving this issue. I am absolute beginner don't know how things works.

**Comment by c3er** [comment]
@Suvrajit69 I'm afraid, the Electron project is anything but beginner friendly.

First, you have to manage [to build the project](https://www.electronjs.org/docs/latest/development/build-instructions-gn), which is already not trivial.

Then one has to work through millions of lines of C++ code to isolate and fix this problem. I don't dare this myself without help by somebody with good knowledge of this codebase. Also a setup of local development environment with debugging facility would be *very* helpful.

Also, C++ is quite a complex language with a steep learning curve -- not only for beginners but also people who know already other languages.

**Comment by c3er** [comment]
@Suvrajit69 While Electron applications are written in JavaScript (and HTML, CSS of course), Electron itself is written in C++ (and additional languages). It is based on Chromium, the open source version of Google's Chrome browser.

**Comment by c3er** [comment]
Didn't disappear magically in version 26.1.0. I updated [my repro repo](https://github.com/c3er/electron-fullscreen-issue) accordingly.

**Comment by c3er** [comment]
Still no magic disappearance in version 27.1.3. [Repro repo](https://github.com/c3er/electron-fullscreen-issue) updated accordingly.

Please deactivate this so called triage bot. It hurts the contributor experience very badly and I think, I'm not the only one who is frustrated with this. A big count -- even a very big count -- of issues is only a problem if you're not able to prioritize them properly.

**Comment by mifi** [comment]
did you find any workaround? I found that if setting `autoHideMenuBar: true` in the BrowserWindow constructor, then the menu disappears completely in fullscreen (but also when not in fullscreen). see also discussion here: #543

**Comment by mifi** [comment]
I found in the source code that windows is handled differently from the others.

Windows:

https://github.com/electron/electron/blob/cee51785e1ed057fa5c78b2fc7bb1e8a5b91053d/shell/browser/native_window_views.cc#L720

Others:

https://github.com/electron/electron/blob/cee51785e1ed057fa5c78b2fc7bb1e8a5b91053d/shell/browser/native_window_views.cc#L756

specifically, the auto-hide menu bar code only gets called for non-windows:

https://github.com/electron/electron/blob/cee51785e1ed057fa5c78b2fc7bb1e8a5b91053d/shell/browser/native_window_views.cc#L763

not sure what's the reasoning for that, but someone on windows could try to enable that for Windows too and see if it helps

**Comment by mifi** [comment]
still a bug i bielieve

**Comment by c3er** [comment]
I can confirm this with version 30.0.3. The menu bar in the newest Electron got a little higher, both in the Electron window (I like this actually) and in fullscreen mode, described above (which makes the bug a little worse).

So, it seems like a bug is not like a bread, that gets stale with time.

**Comment by mifi** [comment]
bump
