### ISSUE TITLE
[Feature Request]: How to make a SplashScreen or SplashImage Before app.ready?

### ISSUE THREAD

**Issue by tomleader** [electron/electron#38428]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Everyone tell me that I should create a BrowserWindow in the app ready event function, codes like below:
```
app.whenReady().then(() => {
  createSplashWindow()
  createMainWindowButDontShow()
  // do some stuff...
 showMainWindowAndHideSplash()
})
```
This is a normal way.

But I found that on some old windows machine, when I (click my app.exe ---> until app ready event trigger), the time cost is about 1-2 seconds.
I had tried to search hours but seems that there is no method to implement a splashScreen before the electron app ready event. 

In fact , there are many apps built by C#, C++ or other languages have the feature.
So, the Electron Team , or anyone got any thoughts on this (Make a splashScreen right after the app is begin running, before ready event) ? 
Thank you!

### Proposed Solution

I had found the electron-builder had a splashImage Option:
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/nsis/nsisOptions.ts#L219

But the limitation is that : the option only works for a windows portable exe file( one exe file contains all resources);

the normal nsis or win-unpacked way, the .exe file still can not make the splash image show before app ready.

### Alternatives Considered

Still got none.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
