### ISSUE TITLE
[Bug]: Continuous segfaults when opening more than one window on wayland

### ISSUE THREAD

**Issue by danog** [electron/electron#38430]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.3

### What operating system are you using?

Other Linux

### Operating System Version

Arch linux, sway

### What arch are you using?

x64

### Expected Behavior

Getting continuous segfaults when opening a new window in vscode, since `gdb backtrace` shows that the segfaults are occurring inside of electron decided to open an issue here.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2, b3e4e68a0bc097f0ae7907b217c1119af9e03435, x64
- OS Version: Arch linux, sway
- Electron Version: v22.3.3

Steps to Reproduce:

1. Open one repository using `code --goto --disable-extensions repo1`
2. Open a different repository using `code --goto --disable-extensions repo2`

Sometimes, vscode can segfault right away even when opening just one repository.

Using these electron flags to enable wayland support:
```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```

Coredumps:
https://paste.daniil.it/core.code-oss.1000.fda55a72533c4a30ab28a4f64152a76d.142642.1684927266000000.zst
https://paste.daniil.it/core.code-oss.1000.fda55a72533c4a30ab28a4f64152a76d.143430.1684927298000000.zst
https://paste.daniil.it/core.code-oss.1000.fda55a72533c4a30ab28a4f64152a76d.144473.1684927537000000.zst

### Actual Behavior

No segfault

**Comment by danog** [comment]
The reproducer is literally just running plain vscode on arch+sway, with no extensions enabled.

I provided three coredumps, these should help in identifying the issue.

**Comment by nd-jharn** [comment]
This now also happening on `slack-electron`, even with latest `22.3.13`version.
