### ISSUE TITLE
[Bug]: Errors from dev tools "Elements" and "Application" tabs

### ISSUE THREAD

**Issue by thehans** [electron/electron#38438]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v24.3.1

### What operating system are you using?

Ubuntu

### Operating System Version

Linux Mint 21.1 (ubuntu jammy based)

### What arch are you using?

x64

### Expected Behavior

No internal errors when viewing dev tools.

### Actual Behavior

Follow instructions from electron-quick-start for a minimal project:
```
# Clone this repository
git clone https://github.com/electron/electron-quick-start
# Go into the repository
cd electron-quick-start
# Install dependencies
npm install
# Run the app
npm start
```

Then use shortcut Ctrl-Shift-I to open dev tools.  When the "Elements" tab has focus for the first time, an error is printed to the terminal from which `npm start` was run.
```
[973450:0524/150137.221227:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)
```
Additionally when the "Application" tab of dev tools is focused for the first time, then a different error is printed:
```
[975383:0524/150402.246539:ERROR:CONSOLE(1)] "Request CacheStorage.requestCacheNames failed. {"code":-32602,"message":"Storage key corresponds to invalid origin"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
```

**Comment by codebytere** [comment]
These errors do not affect functionality at the moment - we can into it but i'm closing this out as it doesn't affect user functionality.
