### ISSUE TITLE
[Bug]: Hover issue on Title bar overlay color buttons with transparent color

### ISSUE THREAD

**Issue by VigneshSonaiya** [electron/electron#38431]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

23.1.3

### Expected Behavior

It will work properly with color code : `#00000000` (transparent)

### Actual Behavior

We have set titleBarOverlay as below which will have color as transparent, It's showing but after hover/focus it lost the transparent background.

```
titleBarOverlay: {
        color: "#00000000",
        symbolColor: "#ffffff",
        height: 48,
      },
```
Before Hover
![image](https://github.com/electron/electron/assets/47246527/9a6b697f-0ea0-477c-8535-d7820913efaa)

After Hover
![image](https://github.com/electron/electron/assets/47246527/2c8bf2b0-49c4-4097-833b-f7f40cfb57c2)

### Testcase Gist URL

https://gist.github.com/2ffe761476c99423ff8cd2dc56ccb95c

**Comment by mlaurencin** [comment]
That is a current limitation of the titleBarOverlay. The specific information and PR to track can be found [here in the documentation](https://www.electronjs.org/docs/latest/tutorial/window-customization#limitations).

**Comment by ChenTraveler** [comment]
Hello, I have encountered the same problem. When the mouse hovers over the button, the hovering style will not disappear. When maximized, the button will still turn black. May I ask if you have solved it? Can you please let me know the solution? Thank you
