### ISSUE TITLE
errors in the main process not catchable??

### ISSUE THREAD

**Issue by tripower** [electron/electron#38457]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Exception / Error should be catched for logging / exit ...

### Actual Behavior

"catch" will not be reached and app runs with buggy code

### Additional Information

if I run my app with "npm run start" I can handle the exception with
process.on('uncaughtException', function (err) {
but after packaging and run the EXE with ASAR
the code of uncaughtException will never be reached??
inside I have tried console.log, winston.log, process.exit ...
nothing happen

any ideas to get this working?

here the dialogbox if no handler and run it with "npm run start"
with EXE + ASAR this is not showing
![electron starter with NO dll](https://github.com/electron/electron/assets/25051422/2359732c-1019-4627-bb47-86b09b755c9b)

the exception occur at 
`const {importClass} = require('java-bridge');`
if wrong MS Visual C++ Dist. is installed or vcruntime140.dll not on the machine 
(for test vcruntime140.dll => vcruntime140.old)

**Comment by Bhavyaatrivedi** [comment]
Hi, can I work on this issue

**Comment by tripower** [comment]
Problem is / was
my code for overwriting the require to log function calls
this might cause problems to other parts ...
