### ISSUE TITLE
[Feature Request]: Bring back getWebPreferences to WebContents

### ISSUE THREAD

**Issue by mannok** [electron/electron#38451]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently we have no way to get the `webPreferences` from `webContents` whereas the old electron build did. We could do `webContents.getWebPreferences()` in the past.

Recently in my project, I added the `<webview>` into the renderer page, when I want to retrieve the session's partition via `webContents.on('did-attach-webview', (evt, wc) => { wc.getWebPreferences(); });` I found that this API was gone. Since I must be able to access the `webPreferences` in order to obtain the partition name and match with the `<webview>` I instantiated from the renderer process, I can no longer achieve this and I couldn't control the webview from main process anymore.

Is there any workaround or should Electron bring back this API?

[https://github.com/electron/electron/pull/30160#issuecomment-882689640](https://github.com/electron/electron/pull/30160#issuecomment-882689640) I am the person who used this un-documented API before and now suffering since this breaking change 
[https://github.com/electron/electron/issues/32557#issuecomment-1017860183](https://github.com/electron/electron/issues/32557#issuecomment-1017860183) A similar request has been raised before but seems no workaround

### Proposed Solution

Bring back `WebContents.getWebPreferences()`

### Alternatives Considered

N/A

**Comment by MarshallOfSound** [comment]
The `will-attach-webview` gives you the `webPreferences` before the webContents is constructed (and let's you modify them).

Or you can use `wc.session` and som kind of reverse weakmap with session objects as they key to lookup the partition name / whatever other info you want to associate with a session.

There are no plans / intentions to add this kind of API back into Electron (it was never officially here to begin with and had all kinds of footguns)
