### ISSUE TITLE
[Bug]: Cannot enable Background Material for the client area

### ISSUE THREAD

**Issue by DeMineArchiver** [electron/electron#38454]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2 build 22624.1755

### What arch are you using?

x64

### Expected Behavior

When setting the `backgroundMaterial` property on a new BrowserWindow, it is expected for the window background to use the material as well as the titlebar.

### Actual Behavior

Only the titlebar of the window has the material, but the client area remains white or any other background color, unless the window is set to be transparent (see below).

### Additional Information

You can work around this issue by setting `transparent: true`, `show: false` in the window constructor, and showing the window after the webcontents have been loaded. But this approach raises and issue: **the window becomes unresizeable** and the **`thickFrame: true` option is ignored**. The method `window.setResizeable(true)` doesn't work either.

**Comment by Daydreamer-riri** [comment]
There are also some other questions here.

As shown in the figure, `backgroundMaterial` appears to be working properly when `titleBarStyle` is set to `default`. However, when `titleBarStyle` is set to 'hidden', the effect is not satisfactory.

I lost the rounded corners, and at the same time `backgroundMaterial` is not working.

#### **titleBarStyle**: `default`:
![image](https://github.com/electron/electron/assets/70067449/5e90945e-2191-4064-9376-346dc39f142a)

#### **titleBarStyle**: `hidden`:
![image](https://github.com/electron/electron/assets/70067449/84e10d07-fede-4a93-8cea-e98aa463dc35)

**Comment by kochie** [comment]
If it helps, with a similar setup I get a white window that disappears when the window goes over the edge of the screen.
![image](https://github.com/electron/electron/assets/10809884/d93a1ee4-604d-46e5-9974-004f3bec39cd)

**Comment by Brouilles** [comment]
Any news on this?

**Comment by craftzdog** [comment]
The `transparent = true` and `frame = true` combination makes the browser window unresizable.

**Comment by fzf404** [comment]
I have the same problem.

**Comment by codebytere** [comment]
Should have been addressed in https://github.com/electron/electron/pull/39708

**Comment by JellyBrick** [comment]
> Should have been addressed in #39708

@codebytere This issue was not resolved in `v27.0.0-beta.8` & `v28.0.0-nightly20230929`

![image](https://github.com/electron/electron/assets/16558115/025f160e-384f-4126-af48-e61858bdf8ce)

![image](https://github.com/electron/electron/assets/16558115/ce4c897c-6f52-4d37-9a29-5623f8d2d29f)

**Comment by vitaminj** [comment]
Yeah there seems to be a series of issues here where they try to add this, but every time it's not quite right or not quite enough. The latest is https://github.com/electron/electron/issues/39959

**Comment by MrLarso2002** [comment]
> If it helps, with a similar setup I get a white window that disappears when the window goes over the edge of the screen. ![image](https://github.com/electron/electron/assets/10809884/d93a1ee4-604d-46e5-9974-004f3bec39cd)
> 
> https://gist.github.com/4b5f34680a08a6ff569196e70e5d48a0

From my observations what is happening in that window is that it starts out white, but ONCE you push it out of the screen, that region that has been outside of the screen becomes acrylic. This also happens when you open a window that is maximized from the task bar and then go back to the electron app.
