### ISSUE TITLE
[Bug]: Electron notification "show" method is not working during Microsoft teams screen sharing

### ISSUE THREAD

**Issue by shrikant7kulkarni** [electron/electron#38455]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^23.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### What arch are you using?

x64

### Expected Behavior

In desktop application developed using Electron, Electron notifications "show" method should work and notification should be shown irrespective of screen sharing using MS Teams application.

### Actual Behavior

Electron notification "show" method is not working during Microsoft teams screen sharing. I am using windows machine and electron-forge package for packaging the application. Notifications are working correctly if screen sharing is Off and MS teams meeting is joined. Issue is only during screen sharing using MS teams application on windows.

Electron notification "show" method not working during Microsoft teams screen sharing. I am using windows machine and electron-forge package for packaging the application. Notifications are working correctly if screen sharing is not ON and MS teams meeting is joined. Issue is only during screen sharing using MS teams application on windows.

I am trying to show notification from Electron main process as per documentation given here: https://www.electronjs.org/docs/latest/api/notification 
https://www.electronjs.org/docs/latest/tutorial/notifications#show-notifications-in-the-main-process

It works perfectly while running in local and with packaged application using electron-forge. But As soon as I start MS Teams meeting and try to share the screen, the same notification is not showing up. I have already set AppUserModelID in main process. I have put the code in try catch block but it is not throwing up any error. It is just moving on to next lines of code. Below code is not the complete but it has all the relevant details.

const { app, BrowserWindow, Notification } = require('electron')

const NOTIFICATION_TITLE = "Test1"; const NOTIFICATION_BODY = "test2";

    const notification = new Notification({
        title: NOTIFICATION_TITLE, body: NOTIFICATION_BODY,
        silent: false,           
        urgency: 'critical',
    });

    notification.show();
app.on('ready', () => app.setAppUserModelId("Test GUI"));

Somehow the MS teams app is messing up with electron notification. This issue is happening on Windows machine.

**Comment by MarshallOfSound** [comment]
This is a setting either in Windows iirc that prevents notifications showing while an app is "presenting" i.e. sharing the screen

It's by design in Windows and not something we can / should bypass 🤔
