### ISSUE TITLE
[Bug]: Crash with `enable-wayland-ime` parameters on Linux

### ISSUE THREAD

**Issue by Bryan2333** [electron/electron#38467]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.x.y

### What operating system are you using?

Other Linux

### Operating System Version

Including but not limited to Arch Linux

### What arch are you using?

x64

### Expected Behavior

Applications launch normally.

### Actual Behavior

As soon as I type using the input method, the application crashes

### Additional Information

Some of my applications like [drawio-desktop](https://github.com/jgraph/drawio-desktop) are using electron 24, which is based on chromium 112. However there is  a bug in chromium 112, see [Chromium crashes when running with `--ozone-platform=wayland --enable-wayland-ime` under weston/kwin](https://bugs.chromium.org/p/chromium/issues/detail?id=1431532), which make electron applications crash immediately when launching them with `--enable-wayland-ime` . I have to launch the applications in xwayland mode.

Although the [patchset](https://chromium-review.googlesource.com/c/chromium/src/+/4423030) has been merged into the mainline of chromium, the chromium 112 is no longer supported, so they won't backport the patchset to 112. I wonder if the patchset can be merged into electron 24 to fix this problem.

**Comment by Bryan2333** [comment]
Any update?

**Comment by MarshallOfSound** [comment]
Picked in #38711
