### ISSUE TITLE
[Feature Request]: Like on macOS, be able to disable rounded corners on Windows 11

### ISSUE THREAD

**Issue by JonathanLydall** [electron/electron#38462]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to be able to opt-out of rounded corners for frameless windows in Windows 11.

Although [BrowserWindow](https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions) options has a `roundedCorners option`, it seems to only be respected on macOS.

### Proposed Solution

Creating a window in the following manner should create a frameless window with square corners in Windows 11:

```js
const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    frame: false,
    roundedCorners: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  });
```

**Comment by JonathanLydall** [comment]
I just had an idea which achieves the desired outcome:

```const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    frame: false,
    transparent: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  });
```

As long as the background is a solid colour, it has the exact desired effect for me.

**Comment by DrSiemer** [comment]
This is not a solution but a workaround. It is not a great option for my situation (loading 24 windows in external pages).
If it is possible to disable the Windows 11 rounding then it would be great if that can be added to the roundedCorners setting as well.
