### ISSUE TITLE
[Bug]: The wheel event of the handle is valid, but the mouse related events are invalid

### ISSUE THREAD

**Issue by liees** [electron/electron#38476]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.9

### What operating system are you using?

Windows

### Operating System Version

window11

### What arch are you using?

x64

### Expected Behavior

I want to be able to simulate mouse usage using the handle, including clicking, moving, scrolling, etc.

### Actual Behavior

Only the wheel of the handle can be used normally, click and move or enter are invalid

**Comment by liees** [comment]
The amazing thing is that when I use vscode to run electron in the development environment, the operation of the mouse or handle is consistent

**Comment by liees** [comment]
> Hello @liees. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

I am also very confused. I encountered this problem in my project, but it did not appear when I minimized the recurrence. I would like to consult. Based on your experience, what are the possible causes of this problem? I'm confused now, I'm out of ideas

**Comment by liees** [comment]
I am also very confused. I encountered this problem in my project, but it did not appear when I minimized the recurrence. I would like to consult. Based on your experience, what are the possible causes of this problem? I'm confused now, I'm out of ideas， @codebytere

**Comment by liees** [comment]
Update problem:

 the reason is that the handle cannot get the focus

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
