### ISSUE TITLE
[Bug]: Egypt summer time saving

### ISSUE THREAD

**Issue by manuelernestog** [electron/electron#38496]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.4.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

Electron app should use system time.

### Actual Behavior

The time is one hour ahead since it still counts the Egypt Summer time.

## To Reproduce

- Go to time settings on your pc, Change timezone to "(UTC +02:00) Egypt ". 

![Screenshot from 2023-05-30 20-18-06](https://github.com/electron/electron/assets/53962116/e418eede-34a8-4e54-b676-46246e2afd42)

- Open dev tools and paste "new Date()" to console. 
- The resulting time will be one hour ahead.

## Screenshot

![Screenshot from 2023-05-30 20-30-28](https://github.com/electron/electron/assets/53962116/091ed44f-714a-4a0c-b2e8-ccb0dc474c45)

### Additional Information

This error looks similar to this old problem with Brazilian summer time saving https://github.com/electron/electron/issues/20998

**Comment by Snitrxm** [comment]
Im goona look into this!

**Comment by Snitrxm** [comment]
When I arrive in home, I will test it in a Linux Distro too!

**Comment by manuelernestog** [comment]
Just to check again, I realized that version 25 of electron already existed and I created an app from scratch with this new version and the same problem still persists.

![image](https://github.com/electron/electron/assets/53962116/d7db90f1-d322-4ac9-8017-8f0861f383cb)


As soon as I hear from the user I'll let you know

**Comment by Snitrxm** [comment]
But its saying that the hour is 17:23, and its right, now its 17:xx in Cairo, Egypt due summer time saving in EU

Maybe your computer is set to normal time, that is 16:xx

**Comment by manuelernestog** [comment]
@Snitrxm take a look what the user says.

![image](https://github.com/electron/electron/assets/53962116/b0759d48-e360-4398-bcc0-3aa845c2709f)

I'm not sure why he tells me about a manual local configuration and if this could be the source of the problem in his case

For my part I have all the automatic date and time settings and I also keep seeing this problem

![image](https://github.com/electron/electron/assets/53962116/2adc1e9e-7810-4cdd-a30e-57cfa019e592)

**Comment by Snitrxm** [comment]
> 🤔🤔 not 100% sure about how that should work. This is the same test on Chrome console. 
> 
> ![image](https://github.com/electron/electron/assets/53962116/6704821f-ba34-4e5b-9d81-d320955b5187)
> 

in chrome is correct innit?

**Comment by Snitrxm** [comment]
Where you are? Cuz if u are in Egypt I think that the in ur computer is wrong, it should be one hour ahead

**Comment by Snitrxm** [comment]
I saw the comment from ur user, Im gonna test what he said about setting manually the time

**Comment by Snitrxm** [comment]
Im not 100% about what he said, I tried again and its okay, the new Date() in console follows the machine time, so, if his machine is with the correct time, it would be fine

**Comment by manuelernestog** [comment]
I'm in America. I asked the same to the user. 

![image](https://github.com/electron/electron/assets/53962116/ab640ba3-5eca-41ed-8a6e-bb1b81193f0c)

It seems strange to me that I do have automatic time on my PC and even so it continues to reflect the problem.

**Comment by Snitrxm** [comment]
U can ask the user abou the time on his machine, ask him a print of the configurantion on Windows 10

**Comment by SaifEl-Deen** [comment]
Hi there guys, it's me the guy with the problem, here is a screenshot from my PC:
![image](https://github.com/electron/electron/assets/130001839/03c7421f-103d-459f-819a-3031f67747f1)

**Comment by Snitrxm** [comment]
So its not a electron problem, im gonna close thsi isssue oky?

**Comment by manuelernestog** [comment]
🤔🤔 To be honest, I still don't quite understand what's going on here and especially because the problem with the automatic time occurred on my computer.

Where does the electron take time?

**Comment by SaifEl-Deen** [comment]
No, there's a problem with the source from which electron gets time info, it should be pulled from the system rather than an online service source.

**Comment by MarshallOfSound** [comment]
The latest tzdata patch is definitely in Electron 26 and I _think_ it's in Electron 25.  Any issues folks are seeing with the latest tzdata (Cairo and a few other places did last minute daylight savings changes this year) are either OS related (update your OS) or you're on too old a version of Electron (update Electron) 🥳

**Comment by xpirt** [comment]
> The latest tzdata patch is definitely in Electron 26 and I _think_ it's in Electron 25. Any issues folks are seeing with the latest tzdata (Cairo and a few other places did last minute daylight savings changes this year) are either OS related (update your OS) or you're on too old a version of Electron (update Electron) 🥳

just pointing this here: only in Electron 26 the issue is fixed, as it's based on Node 18.16 (with latest tzdata patch). Electron 25 does not have the patch.
