### ISSUE TITLE
[Bug]: Transparent property is making the whole window invisible along with the contents in it

### ISSUE THREAD

**Issue by Rohit-258** [electron/electron#38503]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

13

### Expected Behavior

Window should be transparent and contents should be visible 

### Actual Behavior

It is present in the screen because i have added an Console.log on mouse entering the window but whole Window along with the contents are not visible

**Comment by codebytere** [comment]
@Rohit-258 Electron v13 is not supported and has not been for several years. Additionally, you've not provided enough information to triage - there is insufficient description of the issue and no reproductive steps. As such, i'm going to close this issue - you are welcome to open a follow up and we can proceed if it's actionable per stated requirements.
