### ISSUE TITLE
[Bug]: IPC communication in 25.X

### ISSUE THREAD

**Issue by MatthijsBurgh** [electron/electron#38504]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22/20

### What arch are you using?

x64

### Last Known Working Electron version

24.X

### Expected Behavior

Correct IPC behaviour

### Actual Behavior

We are experiencing various issues with IPC communication in combination with PlayWright testing.

The various symptoms are:
- Undefined errors
- Events not coming through

### Additional Information

We think this issue might be caused by changes in file https://github.com/electron/electron/blob/25-x-y/lib/browser/ipc-main-impl.ts in commit https://github.com/electron/electron/commit/71944f2c3bbbfe3af25d117c3241484d05365e91

Issue and PR showing these issues:
https://github.com/spaceagetv/electron-playwright-helpers/issues/38
https://github.com/spaceagetv/electron-playwright-helpers/pull/39

**Comment by MatthijsBurgh** [comment]
@jjeff Do you think the issues we experience are solely related to using Electron with Playwright? Or do you think we can test this easily in a standalone app?

**Comment by jjeff** [comment]
`electron-playwright-helpers`'s [`ipcMainInvokeHandler()`](https://github.com/spaceagetv/electron-playwright-helpers/blob/eaf4c2a3d1c1ce7cd8ec9f57062c2ab37050c8ac/src/ipc_helpers.ts#L236-L265) is attempting to (as it says on the tin) invoke a registered ipc handler via the main process. We do this with some Typescript contortions, reading the private `_invokeHandlers` Map and then calling the handler, which manipulates an event object.

In the past, this added more private properties: `event._reply` which is a function that takes the return value and `event._throw` which is a function to throw any errors.

I'm guessing that `event._reply` has changed in Electron 25. I'm still tracking this down.

Admittedly, these are hacks, but this functionality is super helpful in end-to-end testing as we're able to invoke handlers directly and get their results. Perhaps in the future, we can add some methods to make all of this a little less hacky.

**Comment by jjeff** [comment]
This issue has been resolved in `electron-playwright-helpers`.

It appears that the internal structure of `ipcMain.handle()` has been changed with Electron 25. It's actually much simpler now to trigger a registered handler. So… thanks!

I don't have permission to close this issue, but I think it's been resolved.

**Comment by MarshallOfSound** [comment]
I'll note here that fiddling with IPC like that is gonna break whenever we do refactors of the internal IPC implementation.  (As it did this time).  So don't expect this to be stable / possible to hack around in the long run 😅 Happy to hear you made it work though
