### ISSUE TITLE
[Bug]: Simulated Exception caught by Sentry

### ISSUE THREAD

**Issue by peter-rb2** [electron/electron#38501]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

	 24.4.0

### What operating system are you using?

Windows

### Operating System Version

Window 10 (10.0.19045(2965))

### What arch are you using?

x64

### Expected Behavior

Error should be resolved 

### Actual Behavior

![WXWorkCapture_16854988031063](https://github.com/electron/electron/assets/109708299/de2a70bc-66ac-474a-b657-d97e0294c925)
![WXWorkCapture_16854985986102](https://github.com/electron/electron/assets/109708299/84c2b2ab-4215-4812-b6c8-e0cb90466d76)

A unhandled exception was captured by sentry called "Simulated Exception / 0x7ff7a4ca71a7",  the name is not very descriptive of where the error happeded, the above are the screenshot from sentry, can somebody identify the cause of this error

**Comment by peter-rb2** [comment]
@ivanBereznev I was using version electron version 24, the maintainer suggested to upgrade the electron version saying that could possibly fix that problem, so I just bumped to 25.x, the error has not recurred but what I can do is keeping monitoring

**Comment by Ashu-Bashir** [comment]
Hi @peter-rb2 We could see that It is happening again on 27.x , Could you please specify whether it is handled for you in this version or it is occurring again ?

**Comment by Galkon** [comment]
Seeing these on electron 30. Always wondered what they were.

**Comment by oltreseba** [comment]
Same, happening on electron 30.
