### ISSUE TITLE
[Bug]: Web Serial Not Working on macOS

### ISSUE THREAD

**Issue by dsanders11** [electron/electron#38548]
Skeleton issue as I don't have the time to flesh it out at the moment, but I'm seeing the following failures with Web Serial on macOS using the fiddle from the docs.

* Opening port consistently fails
  * `[83876:0601/053953.148169:ERROR:device_event_log_impl.cc(215)] [05:39:53.148] Serial: serial_io_handler.cc:147 Failed to open serial port: FILE_ERROR_IN_USE`
  * Works fine in Chrome
* `port.getInfo()` isn't defining `vendorId` or `productId`
  * Works fine in Chrome

**Comment by jkleinsc** [comment]
@dsanders11 what macOS version and what Electron version(s)?  Could you fill out the issue template so we have more information about this issue?
