### ISSUE TITLE
[Bug]: Unexpected incorrect custom scrollbar rendering

### ISSUE THREAD

**Issue by CryUshio** [electron/electron#38543]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.1

### What operating system are you using?

macOS

### Operating System Version

MacOS 13.3.1 

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

https://github.com/electron/electron/assets/30655354/967c7cbd-67d3-4a4e-be78-8c28545ae747

Scrollbar color has transition and correct rendering `overflow: overlay;`

### Actual Behavior

https://github.com/electron/electron/assets/30655354/287061da-0702-412d-9f84-6de529a1f9e9

In electron 24. Scrollbar color has no transition.

https://github.com/electron/electron/assets/30655354/f181924c-02f7-4997-8c28-1873327492ac

In electron 25. Scrollbar color has no transition and incorrect rendering `overflow: overlay;`.

### Testcase Gist URL

https://gist.github.com/e52e29929e95dd1449bc15e2ede6080d

### Additional Information

In addition, there are bugs in the electron fiddle, such as styles not working.

**Comment by zhourubin** [comment]
I encountered the same problem as you did.
