### ISSUE TITLE
[Bug]: shell.trashItem() doesn't move file to trash when file is in OneDrive, instead it is moved to root of OneDrive

### ISSUE THREAD

**Issue by Shurikal** [electron/electron#38541]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.3.1 (a) 

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

shell.trashItem should move Item to trash

### Actual Behavior

shell.trashItem moves Item to root of OneDrive folder

### Additional Information

I tried to create the Electron Fiddle app, but it creates the file in the wrong place. I have an example [app](https://github.com/Shurikal/electron_delete) which shows the problem when it is run from inside a folder in the OneDrive.

**Comment by Shurikal** [comment]
After playing a bit around with objective-c (never done that before), I think I know where the problem is:

https://github.com/electron/electron/blob/f247ca3f6222eb27435b47484f93b2041f019918/shell/common/platform_util_mac.mm#L145

I observed the following behaviour with a small test script:
```
// File goes into root directory of onedrive
BOOL did_trash = [[NSFileManager defaultManager] trashItemAtURL:self.fileURL
                                                   resultingItemURL:nil
                                                             error:&deleteError];

// File is gone forever, doesn't go into trash
BOOL did_trash = [self.fileManager removeItemAtURL:self.fileURL error:&deleteError];
```

Maybe someone has an idea how to solve this issue :)

**Comment by MarshallOfSound** [comment]
This is a bug in OneDrive implementation, the API Electron is calling is correct but OneDrive clearly isn't handling it correctly 😅 I'd suggest reporting this bug to OneDrive / msft support as it's something that their app can fix but Electron can / should not.
