### ISSUE TITLE
[Bug]: event.sender undefined in WebContents events

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#38566]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0-nightly.20230214

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

25.0.0-nightly.20230210

### Expected Behavior

`event.sender` should be defined in WebContents event listeners.

### Actual Behavior

The `event.sender` value is undefined in WebContents events.

In the snippet below, the sender is undefined.
```js
mainWindow.webContents.addListener('did-finish-load', (event) => {
  console.log(event.sender);
});
```

### Testcase Gist URL

https://gist.github.com/samuelmaddock/be106f446180308e6cbb5af85096656b

### Additional Information

Bisected to https://github.com/electron/electron/compare/v25.0.0-nightly.20230210...v25.0.0-nightly.20230214

Likely cause is https://github.com/electron/electron/pull/37099

**Comment by MarshallOfSound** [comment]
@samuelmaddock This was an intended change `sender` was only ever documented as being a property for IPC events, in the context of an event listener using `event.sender` doesn't make much sense as it was always basically a reference to `this` or the object that you attached the listener to (in this case `mainWindow.webContents`).

E.g. [`IpcMainEvent`](https://www.electronjs.org/docs/latest/api/structures/ipc-main-event) has a documented `sender` property, the main `Event` type does not
