### ISSUE TITLE
[Bug]: URLSearchParams has no `size` property

### ISSUE THREAD

**Issue by pmwals09** [electron/electron#38565]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.2.1 (22D68)

### What arch are you using?

x64

### Expected Behavior

After initializing a `URLSearchParams` object with properties, I expect the size to match the number of properties:

```js
const u = new URLSearchParams({a: 1, b: 2});
console.log(u.size); // expect 2
```

### Actual Behavior

The size property in the example above logs `undefined`

### Testcase Gist URL

https://gist.github.com/pmwals09/55988efa7a5e593d68592b52c0eaf69c

### Additional Information

The same two lines of code yield the expected response in Chrome v113.0.5672.126 (Official Build) (x86_64)

**Comment by MarshallOfSound** [comment]
![image](https://github.com/electron/electron/assets/6634592/42905414-b77d-458d-ab21-4ecbe3187a95)

`URLSearchParams.size` was only introduced in Chrome 113, per releases.electronjs.org the only version of Electron that contains that version of Chromium is Electron 25 with Chromium 114.

Electron 23 will not support that API
