### ISSUE TITLE
[Bug]: Right-click menu can not appear in tab Elements of Developer Tools

### ISSUE THREAD

**Issue by illusory-dream** [electron/electron#38589]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.22631.1830

### What arch are you using?

x64

### Expected Behavior

1. Run electron app with Developer Tools enabled.
2. Switch the tab of Developer Tools to Elements.
3. Then I could right-click on html content shown under tab Elements. And a menu would display. See screenshot:
![图片](https://github.com/electron/electron/assets/37270118/96889afe-d242-4302-a390-77c9d5f481df)

### Actual Behavior

1. Run electron app with Developer Tools enabled.
2. Switch the tab of Developer Tools to Elements.
3. Then I could right-click on html content shown under Elements. But nothing happened. I cannot open right-click menu.
4. I check the command line and find an error message: [25540:0605/173726.688:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)

### Additional Information

The error message I said above seems to have existed for a long time. But this issue only occured on electron version 25-x-y. I had a test on v24.4.1 and it worked well.

**Comment by illusory-dream** [comment]
After testing I find that the right-click menu does not disappear. It is actually covered by Developer Tools.
Or it could be shown on the electron window, but not developer tools window.

Menu show but be covered:
![Menu show but be covered](https://github.com/electron/electron/assets/37270118/1c73b9c6-5769-49e6-8c28-04f02a1a3a5c)

Menu not show when I minimize electron window:
![Menu not show when I minimize electron window](https://github.com/electron/electron/assets/37270118/f65b4658-2cc0-49ad-91be-51328edb8c23)

**Comment by illusory-dream** [comment]
In addition, I find this issue first appear in version v25.0.0-nightly.20230324. As no problem with version v25.0.0-nightly.20230323.

So I checked the commits between them. There are only two commits. Maybe the updating of chromium is the root cause? But I cannot reproduce it on Chrome with the same version of Chromium.

Two commits before the issue occurred:
![图片](https://github.com/electron/electron/assets/37270118/bf2772a5-b218-44c5-b65f-15904dc9f27c)

[chore: bump chromium to 113.0.5670.0 (main) (](https://github.com/electron/electron/commit/42e7cd9b3f3e16d07f162716b4f1346e32004aec)https://github.com/electron/electron/pull/37675[)](https://github.com/electron/electron/commit/42e7cd9b3f3e16d07f162716b4f1346e32004aec)

**Comment by codebytere** [comment]
Folding this into https://github.com/electron/electron/issues/38790
