### ISSUE TITLE
[Bug]: Crashing due to FD ownership violation when trying to open print dialogue

### ISSUE THREAD

**Issue by kristianh00** [electron/electron#38593]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

11.1.2

### Expected Behavior

Electron's BrowserWindow should load up a webpage with an iframe. The iframe contains PDF that has to be printed. Top right corner of iframe with PDF contains print button which, when pressed, should show chrome print dialogue. Upon selecting printer on print dialogue, PDF should be printed.

### Actual Behavior

Electron's BrowserWindow loads up a webpage with an iframe. The iframe correctly shows PDF that has to be printed. Top right corner of iframe with PDF does indeed contain print button. When print button is pressed, print dialogue shows for less than a seconds (sometimes it doesn't even show), after which the app crashes.

Terminal displays following error message:
`Crashing due to FD ownership violation:
#0 0x5650054cec23 <unknown>
#1 0x56500555207c <unknown>
#2 0x565005552041 close
#3 0x7fdc60dabcdb <unknown>
Trace/breakpoint trap
`
Does not work on build, nor when testing development version.

**Comment by mgurzixo** [comment]
I have the same problem.

I have created a simple [Electron fiddle](https://gist.github.com/ddacbb84a295f8970b2a3cdb04978c84) that reproduce the problem on my system.
I am running Ubuntu 22.04.5 LTS  with kernel 6.8.0-65-generic.

When clicking the button, the print dialog appears *sometimes*,  the Electron console displays the first message ("Printing...") but not the second ("Printing done."), and the Fiddle console shows:
```
Crashing due to FD ownership violation:
#0 0x607edc495e0a
<unknown>
#1 0x607edc48f39c
<unknown>
#2 0x607edc48f359
close
#3 0x7205ca832ef3
<unknown>
```

In fact, I was originally trying to print a PDF blob from a new tab, and the UI blocked when I clicked on the "Printer" button, just after showing the print dialog.

Any suggestion?

Thanks,

Michel

Edit:
PS: I am using CUPS, with cups server: `/run/cups/cups.sock`
