### ISSUE TITLE
[Bug]: webContents.print fails with unspecified options

### ISSUE THREAD

**Issue by mgalla10** [electron/electron#38598]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Last Known Working Electron version

24.4.1

### Expected Behavior

Calling `webContents.print()`, `webContents.print({})`, or `webContents.print(null)` will result in the system print dialog to appearing.

### Actual Behavior

If `print()` or `print({})` are called, the call will never invoke the provided callback (at least not within 5 minutes, which was the longest I let it sit), nor will it throw any exceptions catchable by a try-catch block. When running the provided gist in Electron Fiddle, I see the following console log: "[19232:0605/173028.939:ERROR:device_event_log_impl.cc(222)] [17:30:28.939] Printer: print_view_manager_base.cc:352 Printer settings invalid for \\epic-print1\vca2cpy-Revenge (destination type kLocal): content size is empty; page size is empty; printable area is empty"

If `print(null)` is called, an exception will be thrown with the error message: "Cannot read properties of null (reading 'pageSize')".

### Testcase Gist URL

https://gist.github.com/mgalla10/7710e8f22830f1122cfe0d98dd99ab08

**Comment by HuzaifaJH** [comment]
Hi
I am using electron 34.2.0 and still facing this issue. Can anyone help me with this? TIA.

`[5048:0514/170030.266:ERROR:device_event_log_impl.cc(201)] [17:00:30.266] Printer: print_view_manager_base.cc:384 Printer settings invalid for Black Copper 80 (destination type kLocal): content size is empty; page size is empty; printable area is empty`

Code:
`ipcMain.on("print-content", (event, htmlContent) => {
    const timestamp = dayjs().format("YYYYMMDD_HHmmss");
    const tempPath = path.join(
      app.getPath("temp"),
      `invoice_${timestamp}.html`
    );
    fs.writeFileSync(tempPath, htmlContent);

    const printWindow = new BrowserWindow({
      width: 400,
      height: 600,
      show: true, // Keep true for now to confirm it's loading
      frame: false,
      webPreferences: {
        contextIsolation: true,
      },
    });

    printWindow.loadURL("file:///" + tempPath.replace(/\\/g, "/"));

    setTimeout(() => {
      printWindow.webContents.print(
        {
          silent: true,
          printBackground: true,
          deviceName: "Black Copper 80",
        },
        (success, errorType) => {
          if (!success) console.error("Print failed:", errorType);
          printWindow.close();
          fs.unlink(tempPath, () => {});
        }
      );
    }, 1500);
  });`
