### ISSUE TITLE
[Bug]: I submit a pr, but the circleci check does not pass

### ISSUE THREAD

**Issue by wugaosheng123** [electron/electron#38601]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

Other Linux

### Operating System Version

ubuntu

### What arch are you using?

x64

### Last Known Working Electron version

23.0.0

### Expected Behavior

In order to solve a menu bar problem, submitted a pr, pr id is #38599 , but CircleCI check can  pass. 

### Actual Behavior

In order to solve a menu bar problem, submitted a pr, pr id is https://github.com/electron/electron/pull/38599 , but CircleCI check did not pass, in the local are compiled through.
This is the wrong link: 
[https://app.circleci.com/pipelines/github/electron/electron/71042/workflows/dc12646e-63df-4cc5-9a8d-5509b025d587/jobs/1540627](url)
[https://app.circleci.com/pipelines/github/electron/electron/71042/workflows/eab85132-ac7f-42ca-b341-62eda803cfff/jobs/1540643](url)
[https://ci.appveyor.com/project/electron-bot/electron-x64-testing/builds/47230226/job/klcgo2te1g5c4cnv](url)

### Additional Information

none

**Comment by MarshallOfSound** [comment]
@wugaosheng123 Please do not raise issues for things like failing CI on your own pull requests.  If when a reviewer gets to your PR they believe the CI failure to be a flake they will trigger a rerun.
