### ISSUE TITLE
[Bug]:  CORS policy: Request had to target IP address space, yet the resource is in address space 'local'

### ISSUE THREAD

**Issue by ag250655** [electron/electron#38639]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.1

### What operating system are you using?

Other Linux

### Operating System Version

Ubuntu

### What arch are you using?

x64

### Last Known Working Electron version

13.1.4

### Expected Behavior

do not block by CORS policy

### Actual Behavior

Access to HMLHttpRequest at 'http://localhost:3100/v1/a .... 'has been blocked by CORS policy: Request had to target IP address space, yet the resource is in address space 'local'''

### Additional Information

we have a button when we need some action to happen when button clicked but CORS blocks the action

**Comment by MarshallOfSound** [comment]
CORS rules mean that whatever is running at `http://localhost:3100/v1/a` needs to respond with appropriate CORS headers

Ref: https://web.dev/cross-origin-resource-sharing
