### ISSUE TITLE
[Feature Request]: An option to remove the "link to highlight" selection

### ISSUE THREAD

**Issue by kaizjen** [electron/electron#38657]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Some links have this at the end: `#:~:text=some_content`, which makes the text selected in purple. ([`Example`](https://www.electronjs.org/#:~:text=Native%20graphical%20user%20interfaces))

Electron will show the purple selection in these links, however, there's currently no way to remove the highlight. (Any chromium browser allows you to remove the highlight with its right click menu)

### Proposed Solution

Add a `contents.removeHighlight()` API that will remove all highlights on a page.

### Alternatives Considered

You can prevent the selection of any text by removing all the `#:~:text` from URLs in the `onBeforeRequest()` handler of `WebRequest`.
However, the text selection may be a desired feature, but not being able to disable it wouldn't be desirable.

**Comment by codebytere** [comment]
While I do understand why this would be wanted, it's rather too specific for adding to webContents API surface given it's achievable through existing API and a relatively small burden to handle through that API. Should that change, we can reconsider.
