### ISSUE TITLE
[Bug]: 在银河麒麟系统 运行报错

### ISSUE THREAD

**Issue by wpbjiuy** [electron/electron#38668]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.13

### What operating system are you using?

Other Linux

### Operating System Version

Kylin V10

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

24.1.13

### Expected Behavior

/usr/lib/aarch64-linux-gnu/libnss3.so: version `NSS_3.30' not found

### Actual Behavior

npm run dev

**Comment by jiawei-lee132** [comment]
@wpbjiuy 这个问题已经解决了吗，还是说没有办法解决，只能使用低版本Electron
