### ISSUE TITLE
[Feature Request]: Document if accelerators are case insensitive or not

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#38673]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It's unclear reading the [docs](https://www.electronjs.org/docs/latest/api/accelerator) if accelerators are case insensitive or not. I assume they are because it seems nonsensical for them not to be, but at the same time I see an inconsistent casing being used in the docs, e.g. `PageUp` vs `numdiv`, so it's confusing.

### Proposed Solution

Mentioning if they are case insensitive or not.

And really if they are not case insensitive they should be.

### Alternatives Considered

Checking manually, but that only solves the problem for me, not for everybody else who needs this bit of information.

**Comment by dsanders11** [comment]
cc @electron/docs
