### ISSUE TITLE
[Feature Request]: Ignored pageSize  if @page CSS at-rule is used in the web page when use webContetns.printToPDF( )

### ISSUE THREAD

**Issue by 1339240789** [electron/electron#38674]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

webContetns.printToPDF will Ignored landscape if @page CSS at-rule is used in the web page,So again, if the pageSize attribute is defined in css, printToPDF should also be ignored.
![9N( )}QQ_CGGG2%G_8CL@4Y](https://github.com/electron/electron/assets/71307878/65cc304e-fff0-4ad0-ac06-2a576e392097)

### Proposed Solution

like this,If I were in the page set to print the page size to A4, webContents.printToPDF method should be ignored PageSize 
![image](https://github.com/electron/electron/assets/71307878/40269b62-73e9-4870-943d-15da87221f9d)

### Alternatives Considered

null

**Comment by codebytere** [comment]
@1339240789 does this work with [`Page.printToPDF`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF)? We adhere to that method so if it is not supported there, we will not support it here.

**Comment by 1339240789** [comment]
I used chrome's headless mode to test print pdf，like this
![image](https://github.com/electron/electron/assets/71307878/30e7cdf9-0701-432c-b9ac-6f20e79d0a06)
The size of the pdf page printed out in headless mode does depend on the @page CSS of the page；
Does headless mode printing work the same way as [Page.printPDF](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF)？
