### ISSUE TITLE
[Bug]: Electron reload necessary to adhere to system theme after theme change.

### ISSUE THREAD

**Issue by rokejulianlockhart** [electron/electron#38684]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.5.5

### What operating system are you using?

Other Linux

### Operating System Version

`Linux RQN6C6 6.3.4-1-default #1 SMP PREEMPT_DYNAMIC Mon May 29 06:22:29 UTC 2023 (2c66b1f) x86_64 x86_64 x86_64 GNU/Linux`

### What arch are you using?

x64

### Expected Behavior

Electron apps should immediately notice a system theme change and adhere to it.

### Actual Behavior

When switching themes in a `startplasma-wayland` session (`lookandfeeltool --apply org.kde.breeze.desktop` or `lookandfeeltool --apply org.kde.breezedark.desktop` per https://askubuntu.com/a/1183309/1002900), I must restart https://github.com/microsoft/vscode (`code` and `*insiders`) and https://software.opensuse.org/package/discord for them to adhere to the changed system theme if they were running when the theme was changed.

This isn't the case in a `startx` session.

### Additional Information

Operating System: openSUSE Tumbleweed 20230605
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.9
Kernel Version: 6.3.4-1-default (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: AMD Radeon RX 5700

**Comment by rokejulianlockhart** [comment]
@jkleinsc and @github-actions, no. I'm not an Electron developer.

**Comment by jkleinsc** [comment]
@rokejulianlockhart unfortunately without a test case that reproduces this issue, we cannot resolve the issue.  I am going to  again mark it as needing a repro.  Perhaps someone from one of the projects you mentioned can provide a test case that reproduces the issue.

**Comment by aeschli** [comment]
@jkleinsc Here is the test case. Can we please reopen?

I tested on Fedora Linux 38 (Workstation Edition), Gnome 44.3, Wayland
Electron 26.1.0, Node.js 18.16.1, Chromium 116.0.5845.97

- `git clone https://github.com/aeschli/electron-theme-test.git`
- `cd electron-theme-test, npm i && npm start-wayland`.
-> This starts Electron with parameters `--enable-features=UseOzonePlatform --ozone-platform=wayland`
- a simple electron window opens

Expected:
- the console prints `shouldUseDarkColors: false` when the OS uses a light color scheme, or `shouldUseDarkColors: true` if the OS color scheme is dark

Actual:
- Always `shouldUseDarkColors: false,` is printed, even when the OS color scheme is dark.

- In the OS settings, switch between light and dark while the window is still open

Expected:
- the console prints a message matching the need OS color scheme

Actual:
- nothing printed

Related issue: #33635

@rokejulianlockhart if you can describe your setup and try the same steps that would be helpful.

**Comment by rokejulianlockhart** [comment]
> https://github.com/electron/electron/issues/38684#issuecomment-1691550740

```log
PS /home/rokejulianlockhart> git clone https://github.com/aeschli/electron-theme-test.git && cd electron-theme-test, npm i && npm start-wayland
Cloning into 'electron-theme-test'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 18 (delta 5), reused 14 (delta 2), pack-reused 0
Receiving objects: 100% (18/18), 155.49 KiB | 1.09 MiB/s, done.
Resolving deltas: 100% (5/5), done.
Set-Location: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Path'. Specified method is not supported.
PS /home/rokejulianlockhart> cd electron-theme-test
PS /home/rokejulianlockhart/electron-theme-test> npm i && npm start-wayland
npm WARN deprecated asar@3.1.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated asar@2.1.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
(##################) ⠙ reify:electron-winstaller: http fetch GET 200 https://registry.npmjs.org/electron-winstaller/-/electron-winstaller-5.0.0.tgz 18140ms (cache miss)
npm ERR! path /home/rokejulianlockhart/electron-theme-test/node_modules/electron
npm ERR! command failed
npm ERR! signal SIGINT
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in: /home/rokejulianlockhart/.npm/_logs/2023-08-24T13_09_07_141Z-debug-0.log
PS /home/rokejulianlockhart/electron-theme-test>
```

Does that test case work on Linux? It seems to hang at the https://registry.npmjs.org/electron-winstaller/-/electron-winstaller-5.0.0.tgz download section indefinitely for me.

**Comment by RokeJulianLockhart** [comment]
Per https://github.com/electron/electron/issues/38684#issuecomment-1691550740, this needs to be reopened.
