### ISSUE TITLE
Lost BrowserWindow skipTaskbar: true on show(); hide(); sequence. Linux  

### ISSUE THREAD

**Issue by faustman** [electron/electron#3869]
Hi,

when I'm trying to hide active window and then show it again,
the electron show up the item in task bar.

```javascript
mainWindow = new BrowserWindow({
    width: 200,
    height: 600,
    skipTaskbar: true,
    autoHideMenuBar: true,
    backgroundColor: '#66CD00',
    show: false
});

systemTray = new Tray(__dirname + '/icon.png')

systemTray.on('click', function(e) {
    mainWindow.isVisible() ? mainWindow.hide() : mainWindow.show();
});
```

To reproduce: Click on systemTray 3 times

Arch Linux 4.1.13-1-lts, node 5.1.1, Chrome 47.0.2526.73, and Electron 0.36.1

**Comment by evgenyzinoviev** [comment]
This also happens on Windows.

**Comment by zcbenz** [comment]
Unable to reproduce with v1.2.x anymore.

**Comment by anion155** [comment]
Did reproduce with: Ubuntu 18.04, node v10.15.1, Electron v4.0.5

**Comment by Sentero-esp12** [comment]
This happens to me: Electron 11.1.0, Linux Mint 20
