### ISSUE TITLE
[Bug]: macOS arm64 binary's code signature is corrupted

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#38694]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

```bash
❯ codesign --verify Electron.app

❯ echo $?
0
```

### Actual Behavior

Electron's [darwin-arm64](https://github.com/electron/electron/releases/download/v25.1.0/electron-v25.1.0-darwin-arm64.zip) binary is code signed during the build, but the code signature appears to be corrupted. This doesn't seem to be right.

```bash
❯ codesign --display --verbose Electron.app
Executable=/Users/alkuzmin/Downloads/electron-v25-arm64/Electron.app/Contents/MacOS/Electron
Identifier=Electron
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=513 flags=0x20002(adhoc,linker-signed) hashes=13+0 location=embedded
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements=none
```

```bash
❯ codesign --verify Electron.app
Electron.app: code has no resources but signature indicates they must be present
❯ echo $?
1
```

Trying to launch the app you get
<img width="372" alt="MicrosoftTeams-image" src="https://github.com/electron/electron/assets/607250/c0f74e7f-28cb-4886-b4a4-870b6bfd168c">

**Comment by jkleinsc** [comment]
@alexeykuzmin We don’t codesign Electron.app and because of the way GN assembles the final app bundle it’s never ad-hoc signed correctly.  It will still launch though.
