### ISSUE TITLE
[Bug]: autoUpdater.quitAndInstall closes all windows even when preventDefault is called

### ISSUE THREAD

**Issue by schontz** [electron/electron#38718]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.4.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.4

### What arch are you using?

ia32

### Expected Behavior

1. Have 2 windows open (main and secondary)
2. Update downloads, triggering `quitAndInstall`
3. Prevent the default behavior
4. Expect `close` event is not sent to windows

### Actual Behavior

1. A `close` event is sent to every window

### Testcase Gist URL

https://gist.github.com/schontz/0405bb7e38fae6542a7f831c8178d49a

**Comment by MarshallOfSound** [comment]
`before-quit-for-update` is not a preventable event, it is not documented as such either.

You _can_ call `e.preventDefault()` inside the actual `close` event but it's not recommended to do so after calling `autoUpdater.quitAndInstall()` as there is a pending system task spinning waiting for your app to close windows and quit.  Continuing to leave the app open after that is bad practice.

**Comment by schontz** [comment]
Can this be added to the documentation? It's not clear that this is bad practice. https://www.electronjs.org/docs/latest/api/auto-updater#autoupdaterquitandinstall
