### ISSUE TITLE
Transparent windows has a top border on OS X

### ISSUE THREAD

**Issue by Sneezry** [electron/electron#3872]
![b4abbc7f-3432-4fa0-ad57-64396fec4fa2](https://cloud.githubusercontent.com/assets/1621293/11913422/35f5e4a0-a69e-11e5-9e1d-7c19a439d558.png)

I create a landing window to show my app logo in a transparent window before the main window is ready to show, however, there is a top border on the landing window, any ideas? Thanks.

**Comment by zcbenz** [comment]
`transparent: true` has to be used together with `frame: false`.

**Comment by Sneezry** [comment]
Hi @zcbenz ,

Thanks for fast reply. I do create a transparent window without frame, and here's my code:

    landingWindow = new BrowserWindow({
        width: 600,
        height: 200,
        minWidth: 600,
        minHeight: 200,
        maxWidth: 600,
        maxHeight: 200,
        frame: false,
        alwaysOnTop: true,
        transparent: false,
        skipTaskbar: true,
        icon: __dirname + '/images/logo512.png'
    });

FYI, my system version is 10.9.5, I'm not sure whether this is a bug only for OS X 10.9.

Zhe

**Comment by zcbenz** [comment]
I can reproduce on OS X 10.9, while 10.11 works fine. It seems to be a 10.9 only bug.

**Comment by mohalobaidi** [comment]
I still have it and my system version is 10.14 Beta

**Comment by MarshallOfSound** [comment]
@gavJackson I believe you are experiencing https://github.com/electron/electron/issues/13164

**Comment by gavJackson** [comment]
@MarshallOfSound thanks yep that looks like it
