### ISSUE TITLE
[Bug]: desktopCapturer Documentation may reqiore clarification

### ISSUE THREAD

**Issue by tmfksoft** [electron/electron#38730]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home 22H2

### What arch are you using?

x64

### Expected Behavior

It appears desktopCapturer.getSources **has** to be called before invoking `navigator.mediaDevices.getUserMedia` to capture a specific screen. Unless it's called Electron throws `NotReadableError: Could not start video source`.

Is this intentional, if so the documentation found here:
https://www.electronjs.org/docs/latest/api/desktop-capturer

May need a clarification that this is required, I've only been able to confirm this by copy/pasting from the documentation while my own project didn't work, calling `desktopCapturer` first fixed it.

### Actual Behavior

Documentation may require clarification on the requirement to call desktopCapturer.getSources before invoking `navigator.mediaDevices.getUserMedia`

**Comment by mlaurencin** [comment]
What did your code look like before using the sample in the documentation you linked? In particular, what was the `navigator.mediaDevices.getUserMedia` call? (eg `navigator.mediaDevices.getUserMedia({audio: true, video: true})`). Also were you trying to capture more than one screen?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
