### ISSUE TITLE
[Bug]: Crash if theme is changed via application menu

### ISSUE THREAD

**Issue by c3er** [electron/electron#38732]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Last Known Working Electron version

24.5.0

### Expected Behavior

The application changes the theme, e.g. the application menu is colored accordingly and it doesn't crash.

### Actual Behavior

As soon the theme is changed via the application menu, the application crashes. On the console appears following output:

```
[36016:0612/045936.512:ERROR:crashpad_client_win.cc(844)] not connected
```

### Testcase Gist URL

https://gist.github.com/c9e0ce78e7811ce716923f4ad7111c8c

### Additional Information

Selecting the currently used theme has no effect.

This bug was introduced with Electron 25.0.0-alpha.1

Electron 26.0.0-alpha.5 is still affected as are (probably) all versions in between (I didn't try all).

**Comment by codebytere** [comment]
Tracked to https://github.com/electron/electron/compare/v25.0.0-nightly.20230330...v25.0.0-nightly.20230331 - likely https://github.com/electron/electron/commit/3fa03977c7f5be9442b356ae39dd310276314dce

**Comment by c3er** [comment]
Thank you! I just confirmed that theme switching works again as expected.
