### ISSUE TITLE
[Bug]: set color with alpha would got a red background in ver 25

### ISSUE THREAD

**Issue by jrainlau** [electron/electron#38733]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventrua 13.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

23.0.0

### Expected Behavior

Open a window with correct background.

### Actual Behavior

In the main process, I init the BrowserWindow by a function named "createWindow" below:

```js
async function createWindow(backgroundColor) {
    await main_1.app.whenReady();
    const options = {
        width: 960,
        height: 620,
        autoHideMenuBar: true,
        backgroundColor,
        webPreferences: {
            preload: path.resolve(__dirname, 'preload.js'),
            contextIsolation: true,
            sandbox: true
        },
        useContentSize: true,
        show: false
    };
    mainWindow = new main_1.BrowserWindow(options);
    // ...
    return mainWindow;
}
```
After I put a color with alpha to this function, like `createWindow('#00000000');`, I got a **RED** background window.

<img width="960" alt="企业微信截图_6b0278d9-461c-4f90-84c5-6e0040f8e4e4" src="https://github.com/electron/electron/assets/12172868/265afcf3-2234-43c0-ad41-873a6644b68a">

Besides, it only occurs in **MAS** mode after the building of *electron-builder*.

### Additional Information

[app.zip](https://github.com/electron/electron/files/11718776/app.zip)

**Comment by jrainlau** [comment]
Add `app.commandLine.appendSwitch('use-angle', 'opengl')` could solve this problem...Maybe it's not the “real" solution.

**Comment by coolBrown12** [comment]
Verify Electron Version: Make sure you are using the latest stable version of Electron and check if there are any reported issues related to transparent backgrounds.

Are we using the latest upgradation in electron
