### ISSUE TITLE
[Bug]: When will I get the correct process id

### ISSUE THREAD

**Issue by 1339240789** [electron/electron#38734]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.2.0

### What operating system are you using?

Windows

### Operating System Version

win 11

### What arch are you using?

x64

### Expected Behavior

I can get processId at the right time

### Actual Behavior

when i create a new BrowserWindow,I get processId through webContents, and processId is always 0；If I fetch processId in the 'did-finish-load' event of webContents, it returns the correct one, so when will I get processId correctly, is it the 'did-finish-load' event? Or something else?
![image](https://github.com/electron/electron/assets/71307878/b1f88c03-3f3b-41f3-8c78-4e5f8f3d651f)

### Testcase Gist URL

https://gist.github.com/2aaba6ff0efdf80052e863680723fa22

**Comment by codebytere** [comment]
yes - correct. this is https://github.com/electron/electron/issues/38256
