### ISSUE TITLE
[Bug]: Issues while attempting to upload files to a web app.

### ISSUE THREAD

**Issue by fvulich** [electron/electron#38745]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.x.x , 23.x.x , 24.x.x , 25.x.x

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro  version 19045.2965

### What arch are you using?

x64

### Expected Behavior

Drag and drop a file in the BrowserWindow that has Mega web app loaded, and the file upload dialog is shown.
(Gif showing expected behavior in Chrome)
![Grabando #239](https://github.com/electron/electron/assets/46904390/da473b41-db94-41da-9a76-f9ff42f83cd4)

Upload file using the button upload file of the Mega web app and the file gets uploaded.
(Gif showing expected behavior in Chrome)
![Grabando #240](https://github.com/electron/electron/assets/46904390/3ad8dd75-4184-4997-bd7a-710491010b03)

### Actual Behavior

When try to upload a file using drag and drop, nothing happens and in the console you get  the following error:

`TypeError: Cannot set property path of #<File> which has only a getter
    at pushFile (64c93c7c-2b8f-4d41-b24a-460b4a29d4ec:87204:23)
    at 64c93c7c-2b8f-4d41-b24a-460b4a29d4ec:87230:17`
    
    
![Grabando #237 (4)](https://github.com/electron/electron/assets/46904390/3a63254a-9f2b-4c4d-a065-b7128f1bbc4d)

When try to upload a file using the upload file button of the Mega web app, the file gets loaded but inside a folder structure (same as the one in the device)

![Grabando #238](https://github.com/electron/electron/assets/46904390/356af079-4b82-42f6-9af6-c5bb63d5f7ae)

### Testcase Gist URL

https://gist.github.com/bad29ec6ed98fa7438d047475f6d0084

### Additional Information

This behavior is also reproducible using webview tags.

**Comment by MarshallOfSound** [comment]
This is a bug in mega, Electron augments the `File` type with a `path` property that is readonly.  Mega is trying to set the `path` property on that `File` object for it's own purposes (idk why) and that is causing a JS error because path is readonly

**Comment by fvulich** [comment]
Thank you for your reply! We have thoroughly tested this case and it seems to work in every browser so far. That's why we think this is more like to be an Electron restriction rather than a bug of Mega. Do you know whether there is a need to make this path variable a “read-only” variable, or if it is a design decision?
On the other hand, are you aware of any workaround for this issue?
Thanks for your help!

**Comment by MarshallOfSound** [comment]
> or if it is a design decision?

It's all codegenned, I don't think we want to make it writeable rather we'd want to remove it completely but it's not that simple.  See #38776 for the start of that process

> On the other hand, are you aware of any workaround for this issue?

Execute this code in the main world `delete File.prototype.path` (has to be in the main world, not the isolated world that the preload runs in)

**Comment by fvulich** [comment]
@MarshallOfSound Thanks so much, the workaround did the trick!
