### ISSUE TITLE
[Bug]: Opening Popup Window (window.open) issue 

### ISSUE THREAD

**Issue by rmtech11** [electron/electron#38746]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2 19044, macOS Ventura 13.4

### What arch are you using?

x64

### Expected Behavior

On clicking a link in a webpage, i call window.open for the first time. Electron invokes a 'setWindowOpenHandler' followed by 'did-create-window' event. A new electron "BrowserWindow" is created and loaded the webpage. No issues so far.

(I took the window obj in did-create-window and registered for weContents.destroyed and browserWindow.closed event)

Now I keep track of the opened window in the renderer ( this.popupWindow['frameName'] =  window.open(o.url + "?" + o.queryParam, s, d);) and subsequently when i click the same link again (with the same frameName), i call window.close - this.popupWindow['frameName'].close() (so that the first opened webContent would be destroyed) and then call 'window.open' to create a new window again. In this case, i'm expecting the following sequence,

1. 'weContents.destroyed' event to be fired for the first BrowserWindow
2. Electron.browserWindow closed for the firs BrowserWindow
3. Electron to invoke the setWindowOpenHandler
4. did-create-window event should be fired.

### Actual Behavior

On calling window.close first and then window.open in the renderer,

1. Electron invoked setWindowOpenHandler
             did-create-window event is **_NOT_** fired (seems electron under the hood maintains a collection based on the frameName and reuse the window if a BrowserWindow exists for the frameName)

2. Received 'weContents.destroyed' event (of the first window, based on webContents.id)
3. Received electron.browserWindow closed event

It appears that calling window.close() in the renderer did not close the window immediately or at least until setWindowOpenHandler is invoked. Electron decided to pick the window available for the frameName (https://github.com/electron/electron/blob/f5869b6fb936ba125071f6560ae8c871e4488777/lib/browser/guest-window-manager.ts#LL51C52-L51C61) but got closed as soon as it received the (guest.once('closed')) closed event.

**Comment by rmtech11** [comment]
@t57ser thanks for pointing out, its the same issue

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/38754

**Comment by codebytere** [comment]
Closing as duplicate of https://github.com/electron/electron/issues/28625
