### ISSUE TITLE
[Bug]: 当我拖动时，调用win.setPosition(data.posX,data.posY)时，窗口会纵向和横向变大，一直变大，版本是25.1.0

### ISSUE THREAD

**Issue by Myyidagit** [electron/electron#38752]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.0

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Last Known Working Electron version

25.1.0

### Expected Behavior

mainWin && mainWin.setPosition(data.posX,data.posY)

### Actual Behavior

mainWin && mainWin.setPosition(data.posX,data.posY)

**Comment by SorryToPerson** [comment]
same issues

**Comment by fanchenio** [comment]
bump.

**Comment by HQidea** [comment]
see https://github.com/electron/electron/issues/10862
