### ISSUE TITLE
wayland csd on gnome are broke for 25.x and newer. 

### ISSUE THREAD

**Issue by frosth555** [electron/electron#38786]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux / 6.3.7-zen1-1-zen

### What arch are you using?

x64

### Last Known Working Electron version

24.5

### Expected Behavior

`$ electron24 --ozone-platform-hint=auto --enable-features=UseOzonePlatform,WaylandWindowDecorations`
![Zrzut ekranu z 2023-06-14 15-12-55](https://github.com/electron/electron/assets/22305379/6261fe32-040a-4f9b-8e20-601fc4daf2f2)

### Actual Behavior

`$ electron25 --ozone-platform-hint=auto --enable-features=UseOzonePlatform,WaylandWindowDecorations`
![Zrzut ekranu z 2023-06-14 15-14-58](https://github.com/electron/electron/assets/22305379/44b87b93-f081-416d-83c1-6d89bde184d1)

### Additional Information

any electron version newer than 24 (25/alpha-26/nightbuild-27) are broken

**Comment by heftig** [comment]
Hi-DPI support seems to have been lost as well, which seems related. The windows have scale 1 even when the monitor has scale 2, thus get upscaled by gnome-shell.

**Comment by dtcooper** [comment]
Confirming the lack of title bar buttons on Wayland.

**Comment by orowith2os** [comment]
I've been getting this with Element (im.riot.Riot) too. No buttons, everything else works.

**Comment by Midar** [comment]
Can confirm that all Electron apps look really blurry and without a titlebar. Adding `--disable-features=WaylandFractionalScaleV1` does *not* fix the blurriness for me.

**Comment by PRGWITHSTYLE** [comment]
I'm still seeing this issue on a Fedora based Linux distro using wayland
