### ISSUE TITLE
[Bug]: `e.preventDefault()` from within `beforeunload` event handler prevents closing of the window since v25, but should not

### ISSUE THREAD

**Issue by ivanggq** [electron/electron#38798]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2 (build 22621.1702)

### What arch are you using?

x64

### Last Known Working Electron version

24.5.1

### Expected Behavior

Calling `e.preventDefault()` from within the `beforeunload` event handler should not prevent the closing of the window. It did not prevent the closing in Electron versions 24, 23, and before that.

`e.preventDefault` is not documented to prevent the closing of the window in the Electron docs: https://www.electronjs.org/docs/latest/api/browser-window#event-close

### Actual Behavior

Calling `e.preventDefault()` from within the `beforeunload` event handler prevents the closing of the window.

### Testcase Gist URL

https://gist.github.com/ivanggq/f0c994532e6dd8fdee1c21b86233c95b

### Additional Information

This breaks apps that use `react-use` library https://github.com/streamich/react-use/blob/master/src/useBeforeUnload.ts, because it calls `e.preventDefault()` unconditionally.

Edit: Also, if this has any importance, `preventDefault()` is not preventing the closing of the window in the Chrome browser. It seems to me it is best if this behavior is uniform across Electron versions and aligned with Chrome.

**Comment by codebytere** [comment]
This, unfortunately, looks like a bug Chromium introduced and then fixed themselves. it's gone as of https://github.com/electron/electron/compare/v26.0.0-nightly.20230523...v26.0.0-nightly.20230524, specifically https://github.com/electron/electron/commit/30e992dec4ca1c7b33c2bda1b4353072a9621aa7. I can try to look and find what the fix is and backport it to 25.
