### ISSUE TITLE
[Bug]: developer tools more Tabs tab list is under the devtools windows

### ISSUE THREAD

**Issue by zeonler** [electron/electron#38790]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

from 25.0.0 through 26.0.0 alpha 6

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2

### What arch are you using?

x64

### Last Known Working Electron version

24.5.0

### Expected Behavior

developer tools more Tabs tab list selection is rendered over the devTools windows
![image](https://github.com/electron/electron/assets/17425313/77706765-d57b-43a4-8a1f-03d162cbf1ed)

### Actual Behavior

when undocked developer tools more Tabs tab list selection is under the devTools windows
![image](https://github.com/electron/electron/assets/17425313/07df8f4e-1687-4336-aa70-b9800b006227)

### Testcase Gist URL

https://gist.github.com/zeonler/65057a3c62258b284622ab79bfa31539

**Comment by codebytere** [comment]
Tracked to https://github.com/electron/electron/compare/v25.0.0-nightly.20230323...v25.0.0-nightly.20230324

**Comment by codebytere** [comment]
Looks like it's this: https://chromium-review.googlesource.com/c/chromium/src/+/4356117
For now, this can be worked around by adding:

```js
app.commandLine.appendSwitch('disable-features', 'WidgetLayering');
```

to your code.

**Comment by illusory-dream** [comment]
I find this issue disappeared after nightly build v29.0.0-nightly.20231129

**Comment by absidue** [comment]
Can confirm that it is working again without the workaround on Electron 29.1.1.

**Comment by codebytere** [comment]
Closing as resolved in light of above.
