### ISSUE TITLE
Selenium and Chromedriver Compatibility?

### ISSUE THREAD

**Issue by rawberg** [electron/electron#388]
Is there a way to run integration tests with Selenium and Chromedriver? The node-webkit folks provide a [customized driver](https://github.com/rogerwang/node-webkit/wiki/chromedriver) that looks for node-webkit binaries. Does atom-shell need something similar?

**Comment by swqaindia** [comment]
I have automated the test case in java language using selenium webdriver. but I want run it with electron.
which I don't know properly. anyone can help me?
