### ISSUE TITLE
[Bug]: multiple issues with utf-8 characters

### ISSUE THREAD

**Issue by n0rbyt3** [electron/electron#38802]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### What arch are you using?

x64

### Expected Behavior

utf-8 characters are printed and handled correct

### Actual Behavior

Running
```js
'use strict';
const { app } = require('electron');
app.whenReady().then(() => {
  console.log('äöü');
});
```
prints the garbage string `├ñ├Â├╝`.

I have tested both, the terminal inside VSCode and a normal `cmd` window. Responses from `fetch()` calls are also broken. My files are formatted as utf-8 without bom.

However, running the script directly without electron works as espected in VSCode and `cmd`.
That's why I assume electron messes sth. up.

### Additional Information

node version: 18.13.0
npm version: 9.6.0

**Comment by deermichel** [comment]
I'm unable to reproduce this one. Can you try that on a different machine since it sounds suspiciously like a local env issue. Please also try a repro in https://www.electronjs.org/fiddle and if it repros, post the gist here. Thank you.

**Comment by codebytere** [comment]
Also unable to reproduce this: I see this in console just as expected:

```console
Saving files to temp directory...
Saved files to C:\Users\CODEBY~1\AppData\Local\Temp\electron-fiddle-14320-W3xiI636a73M
Electron v999999999.9.9 started.

äöü
```

**Comment by n0rbyt3** [comment]
@deermichel I tried it on a different machine (Windows 10.0.19045.2965, node 18.13.0, npm 9.4.1) and got the same broken output.

Electron Fiddle works on that machine:
`
Saving files to temp directory...
Saved files to C:\Users\norbyte\AppData\Local\Temp\electron-fiddle-14868-M5lYDAD5L2d4
Electron v25.0.1 started.

äöü

Electron exited with code 0.
`

I used the same code as above with an additional ```app.quit();``` at the end.

**Comment by n0rbyt3** [comment]
@deermichel The issue is the default codepage used by the Windows command line utility. I use a German version of Windows 10 on both machines. Running ```chcp``` inside the ```cmd``` window returns ```Aktive Codepage: 850.``` After executing ```chcp 65001``` to set the current codepage to UTF-8 for the active window, electron prints all characters correct and strings can be compared without issues.

I guess you can reproduce the issue by executing ```chcp 850``` before executing electron.

However, independant to the codepage set, ```node``` is always able to print German umlauts inside a ```cmd``` window. It would be great if electron could adapt the logic. I had a quick look at ```node```'s source code but cannot find any helpful line where the magic happens.

**Comment by deermichel** [comment]
maybe related: 
https://github.com/nodejs/node/issues/3284
https://github.com/nodejs/node/commit/2d3560767e6da62ceb0e5189c8f0b9a8f0a0924d

**Comment by codebytere** [comment]
Closing as this is likely an underlying Node.js issue and not one in Electron.
