### ISSUE TITLE
[Bug]: webContents.print doesn't invoke callback when print dialog is canceled

### ISSUE THREAD

**Issue by mgalla10** [electron/electron#38811]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Last Known Working Electron version

24.5.1

### Expected Behavior

When I show a print dialog via `webContents.print(options, callback)` then cancel the dialog, `callback` should be invoked with `success = false` and `failureReason = "Print job canceled"` (or some similar message).

### Actual Behavior

When the print dialog is canceled, `callback` is never invoked.

### Testcase Gist URL

https://gist.github.com/7710e8f22830f1122cfe0d98dd99ab08

### Additional Information

In the test gist, comment out the line setting `options = undefined` and uncomment the line setting `options = {}` (incidentally, both `options = undefined` and `options = null` used to work in v24.5.1, but now throw an exception in v25.1.1). In versions <= v24.5.1, clicking print and canceling the dialog would show a message box saying the print failed because it was canceled. In v25.1.1, nothing happens because the callback is never called.

**Comment by codebytere** [comment]
Already fixed in https://github.com/electron/electron/pull/38709
