### ISSUE TITLE
[Feature Request]: Load html string directly from native BrowserView api

### ISSUE THREAD

**Issue by linonetwo** [electron/electron#38813]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

We need to load dynamically generated HTML in a BorwserView inside a BrowserWindow. And the HTML string is 100M+ so using datauri is not possible https://github.com/electron/electron/issues/1146#issuecomment-1593307315

### Proposed Solution

Add a `.loadHtmlString` method to load HTML string.

Or even allow stream to it.

### Alternatives Considered

Allow `.loadFile` to load from a in-memory file, so we can pretend this HTML string is in a vfs with things like [vfs](https://www.npmjs.com/package/@typescript/vfs).

### Additional Information

This is a well wanted feature, in https://github.com/electron/electron/issues/1146

**Comment by linonetwo** [comment]
Trying this workaround in `"electron": "25.1.1",` failed:

```ts
  private async loadHTMLStringForView(htmlString: string, view: BrowserView) {
    const callbackWithHTMLString = (request: GlobalRequest): GlobalResponse => {
      // DEBUG: console request
      console.log(`request`, request);
      return new Response(htmlString, {
        headers: { 'content-type': 'text/html' },
      });
    };
    try {
      view.webContents.session.protocol.handle('htmlString', callbackWithHTMLString);
      const handled = view.webContents.session.protocol.isProtocolHandled('htmlString');
      if (!handled) {
        logger.warn(`loadHTMLStringForView: htmlString protocol is not handled`);
      }
      await view.webContents.loadURL(`htmlString://`);
      view.webContents.session.protocol.unhandle('htmlString');
    } catch (error) {
      logger.error(`loadHTMLStringForView: ${(error as Error).message}  (maybe this htmlString is not encodeURIComponent):\n${htmlString.substring(0, 100)}...`);
    }
  }
```

While `isProtocolHandled('htmlString')` returns true, I get

```
ERR_FAILED (-2) loading 'htmlString://'
```

And windows will say no app can handle `htmlString://`

**Comment by codebytere** [comment]
@zcbenz what do you think about this?

**Comment by Susheer** [comment]
let htmlString = '<html><h1>Hello</h1></html>';
let encodedHtmlString = encodeURIComponent(htmlString);
let mainWindow = new BrowserWindow();

mainWindow.loadURL(`data:text/html;charset=utf-8,${encodedHtmlString}`);
