### ISSUE TITLE
[Bug]: When capturing a window desktopCapturer does not capture menus on MacOS

### ISSUE THREAD

**Issue by ZeroMax-dev** [electron/electron#38810]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.4

### What arch are you using?

x64

### Expected Behavior

When I capture a single window with electron's desktopCapturer API and I interact with the captured window the desktopCapturer does not record the sub-menus and context menus when interacting with the window. When there is a drop-down menu or when I right click inside my window to see the context menu these menus are completely invisible in the window video stream.

### Actual Behavior

Show the menus in the video stream like they appear within the window. On Windows sub- and context-menus are shown normally, so this behaviour is inconsistent.

**Comment by ivanggq** [comment]
I believe this behavior is coming from WebRTC's implementation for capturing a window. It is the same for both Mac and Windows. Basically the OS APIs used to capture the window capture just the window, and any context menus, modal dialogs, tooltips, etc. are all different windows, which are not captured by the window-capturing APIs.

Since this is part of WebRTC, the same behavior exists in Google Chrome.

**Comment by codebytere** [comment]
Closing in agreement with @ivanggq - we plumb straight down to Chromium's behavior here, and from a maintenance burden and parity perspective intend to continue doing so. Should they change this in the future, so will we.
