### ISSUE TITLE
[Bug]: webContents.print({ landscape: true )} is not working

### ISSUE THREAD

**Issue by KAROTT7** [electron/electron#38823]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

25.1.1

### Expected Behavior

webContents.print({ landscape: true )} should work

### Actual Behavior

webContents.print({ landscape: true )} is not working

### Testcase Gist URL

https://github.com/KAROTT7/electron-print-landscape-issue

### Additional Information

![WechatIMG97](https://github.com/electron/electron/assets/21054747/e427ca33-adc0-4a0f-b0f6-a4475f196632)
![WechatIMG96](https://github.com/electron/electron/assets/21054747/e4a5ddb0-a14a-4a3c-b342-80ed0bdc44a3)

**Comment by codebytere** [comment]
Already fixed in https://github.com/electron/electron/pull/38741
