### ISSUE TITLE
[Bug]: webContents.print() fails for immutable object parameter

### ISSUE THREAD

**Issue by LeonZimmermann** [electron/electron#38837]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows Version 10.0.19044 Build 19044

### What arch are you using?

x64

### Last Known Working Electron version

24.2.0

### Expected Behavior

Making the following request results in a _printer selection dialog_ being displayed:
```
webContents.print(Object.freeze({
  silent: false,
  printBackground: true,
}));
```

### Actual Behavior

The app crashes with the following message:
```
(node:54988) UnhandledPromiseRejectionWarning: TypeError: Cannot add property mediaSize, object is not extensible

at _.print (node:electron/js2c/browser_init:2:83987)

at createWindow (C:\Users\xxx\AppData\Local\Temp\electron-fiddle-25576-SCjuZwebgVHq\main.js:21:26)

at C:\Users\xxx\AppData\Local\Temp\electron-fiddle-25576-SCjuZwebgVHq\main.js:31:3

(Use `electron --trace-warnings ...` to show where the warning was created)

(node:54988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

[54988:0620/131209.732:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)
```

### Testcase Gist URL

https://gist.github.com/289e2f14fcbcf98e1e0aba55b7204d4e

**Comment by LeonZimmermann** [comment]
Added Testcase Gist: https://gist.github.com/289e2f14fcbcf98e1e0aba55b7204d4e

**Comment by codebytere** [comment]
@LeonZimmermann can you explain to me your use case in doing this? This API has never worked any other way, and i'm not sure why you'd want to call `Object.freeze` on it.

**Comment by BurningEnlightenment** [comment]
I will chime in here as I work on the same project as LeonZimmermann.

> I'm not sure why you'd want to call Object.freeze on the options object.

The options object is a module scoped variable in our case and doesn't need to be mutable, therefore we make it immutable to prevent accidental modifications. It's pretty much the same reasoning as preferring `const pi = 3.14` over `let pi = 3.14`.

**Comment by BurningEnlightenment** [comment]
bump

**Comment by BurningEnlightenment** [comment]
@codebytere thanks!
