### ISSUE TITLE
[Feature Request]: roundedCorners option in BrowserWindow options for Windows 11

### ISSUE THREAD

**Issue by suheelsn** [electron/electron#38834]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

As Windows 11 has introduced rounded corners, this is causing the frameless BrowserWindow look bad in my application. 
One can see the background in the corners and on the boundaries of the BrowserWindow.

Going to fullscreen mode is not an option for me as I combine two displays as one in the application. 

### Proposed Solution

I know the disabling of rounded corners is supported for MacOS by setting the BrowserWindow option roundedCorners: false.

It is very much appreciated if this option is enabled for Windows as well. 
Please help me if anyone knows an alternate solution to fix this.

### Alternatives Considered

I have tried below solutions already but they were not so useful for my use case or did not work!

- Disabling the Display adaptor on Windows 11. 
       This works, but I do not want to do this because, it affects my video quality.
       
- Adding Registry entry 'UseWindowFrameStagingBuffer' in Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM
       This solution doesn't work anymore on latest Windows 11

**Comment by codebytere** [comment]
@suheelsn could you please provide a reproducible sample we can run, ideally with [Fiddle](https://github.com/electron/fiddle) that demonstrates the UI you believe looks bad in your case? That would help us move forward to more effectively triage this and decide on potential next steps.
