### ISSUE TITLE
[Bug]: when `contextIsolation: false`, `v8BreakIterator` is deleted from `Intl`

### ISSUE THREAD

**Issue by Kallenju** [electron/electron#38841]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2

### What arch are you using?

x64

### Expected Behavior

Hi,

I noticed that when you turn off context isolation, `v8BreakIterator` is removed from `Intl`.

Is it intended behavior?

I expect that disabling context isolation should not cause any property in global objects to be removed.

### Actual Behavior

When context isolation is disabled, `v8BreakIterator` is removed from `Intl`.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
