### ISSUE TITLE
[Bug]: Preload script not running on child-window "top" frame

### ISSUE THREAD

**Issue by Asaf-Rivni-Ericom** [electron/electron#38844]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Last Known Working Electron version

16.0.4

### Expected Behavior

I have an app that uses the preload script on some contexts.
Recently I found out that in some scenarios the preload script is not running.
Im using the setWindowOpenHandler function in order to use the same preload in all future child window that will be created.
Electron fiddle gist is added for refrence.

Bug flow:
1. Go to gmail.com.
2. Click on the "meet" button on the left.
3. Click on "New Meeting"
4. A pop up will open up
5. The expected behaviour is to have preload script running on this window as well.

### Actual Behavior

Bug flow:
1. Go to gmail.com.
2. Click on the "meet" button on the left.
3. Click on "New Meeting"
4. A pop up will open up
5. The actual behaviour is that the preload script does not run at all on the top frame.

### Testcase Gist URL

https://gist.github.com/cbb4249641359cce34b87c0203b55d8a

### Additional Information

Tested also 26.0.0-alpha.7 to make sure its not something that was fixed in newer versions
Looking at the release notes this PR seems to be what's causing this bug: https://github.com/electron/electron/pull/32108

**Comment by codebytere** [comment]
@zcbenz could you take a look at this?

**Comment by ytzlax** [comment]
+1

**Comment by ShmayaFrankel** [comment]
+1

**Comment by zcbenz** [comment]
I can reproduce this issue but I have to say this is very hard to debug since gmail is one of the most complicated js app and it is apparently doing some very fancy things.

Currently from my observation, it seems that gmail created an empty new child window, then wrote content to it in the parent window, and then did some magic to make the child window disconnected from the parent window probably from safety reasons. This method bypasses how we initialize the node integration.

I'll see if I can find a fix.

**Comment by Asaf-Rivni-Ericom** [comment]
@zcbenz Thanks for the update, much appreciated!
