### ISSUE TITLE
[Bug]: Creating multiple BrowserViews "simultaneously" causes some to have the same renderer process

### ISSUE THREAD

**Issue by linwang** [electron/electron#38851]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.3.3

### What operating system are you using?

macOS

### Operating System Version

13.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When our app creates new BrowserViews, we expect each to have a unique process id for getOSProcessId().

this.browserView = new BrowserView({
      webPreferences: {
        preload: PRIMARY_WINDOW_PRELOAD_WEBPACK_ENTRY, // eng-disable PRELOAD_JS_CHECK
        contextIsolation: true,
        webSecurity: true,
        javascript: true,
        sandbox: true,
      },
    });

### Actual Behavior

Sometimes two BrowserViews have the same process id for getOSProcessId(). Note that the user below has 3 BrowserViews, but two of them have the same OS process id
Code:
views.forEach((view) => {
        try {
          processId = view.webContents.getOSProcessId();
          useLogger().info(`Killing Process: ${processId}`);
          process.kill(processId);
        } catch (err) {
          useLogger().error("Failed to kill process: ", err);
        }

Logs:
2023-06-18T00:44:34.561 | ERROR | Failed to kill process: Error: kill ESRCH 
2023-06-18T00:44:34.164 | INFO | Killing Process: 11168
2023-06-18T00:44:33.800 | INFO | Killing Process: 3152
2023-06-18T00:44:33.429 | INFO | Killing Process: 11168

**Comment by MarshallOfSound** [comment]
> When our app creates new BrowserViews, we expect each to have a unique process id for getOSProcessId().

This is an incorrect assumption, renderer processes are per-site and therefore multiple webContents can be hosted in the same process (in fact it is intentional).  E.g. loading `google.com` in two `BrowserView`'s will result in only one renderer process
