### ISSUE TITLE
[Bug]: webContents.print({ silent: true }) not working

### ISSUE THREAD

**Issue by KAROTT7** [electron/electron#38852]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0-alpha.7

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

26.0.0-alpha.7

### Expected Behavior

webContents.print({ silent: true }) should work correctly

### Actual Behavior

webContents.print({ silent: true }) not working

### Testcase Gist URL

https://github.com/KAROTT7/electron-print-silent-issue

### Additional Information

Is this problem relate to printer?

**Comment by Hedwig188** [comment]
> Already fixed in #38812

Is this going to merge back to 25.2.0? I can reproduce the same issue in that version.
