### ISSUE TITLE
[Bug]: Electron 10.0.0 app window won't be displayed until gpu-process is killed manually

### ISSUE THREAD

**Issue by alintintesan** [electron/electron#38858]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

10.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Build 19042

### What arch are you using?

x64

### Last Known Working Electron version

8.5.0

### Expected Behavior

Electron application window should be displayed once the application is started.

### Actual Behavior

We're using electron 10 and electron-packager to package several angular applications. The packager builds an exe that contains everything needed in order to run with electron 10. When the exe is launcher, it will start a node process that runs a js file that requires the built files of one of the several angular applications, this is determined via a command line argument. This was working perfectly in the past with 8.5.0, but once we've decided to upgrade to 10, it stopped working for one of our applications, the other ones work as before. I've also tried starting it from the console, the window still won't show up and no error is displayed. When I check the details tab of task manager (and enable the commandline column for each process), I can see that there are 4 processes related to this:
1) The main one used to start the application from the commandline
2) utility process
3) gpu-process
4) renderer

For some reason, by manually killing the gpu-process, it's automatically reinitialized and then the application window shows up no problem. I've also enabled the logs with the env variable ELECTRON_ENABLE_LOGGING set to true, but it doesn't show anything useful:
C:\Program Files (x86)\Micro Focus\UFT Developer\Tools\bin\leanft>
[11944:0620/174606.123:INFO:CONSOLE(1890)] "dispatch LOAD_SETTINGS", source: file:///C:/Program%20Files%20(x86)/Micro%20Focus/UFT%20Developer/Tools/bin/leanft-comps/node_modules/record-client/app/main.js (1890)
[11944:0620/174606.129:INFO:CONSOLE(36121)] "Angular is running in the development mode. Call enableProdMode() to enable the production mode.", source: file:///C:/Program%20Files%20(x86)/Micro%20Focus/UFT%20Developer/Tools/bin/leanft-comps/node_modules/record-client/app/vendor.js (36121)
[11944:0620/174615.026:WARNING:gpu_process_host.cc(1257)] The GPU process has crashed 1 time(s)
[11944:0620/174615.244:WARNING:gpu_process_host.cc(985)] Reinitialized the GPU process after a crash. The reported initialization time was 152 ms
(here I've manually killed the gpu process in order for the app window to show up)

**Comment by codebytere** [comment]
Electron 10 has not been supported for several years now. In order for us to continue triaging this issue, you'll need to demonstrate this this issue occurs on a [currently supported version](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
