### ISSUE TITLE
[Bug]: contentProtection no longer working on macOS

### ISSUE THREAD

**Issue by schontz** [electron/electron#38863]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0-beta.1 and higher

### What operating system are you using?

macOS

### Operating System Version

13.4 (22F66)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

24.0.0-alpha.7

### Expected Behavior

1. Set switch: `app.commandLine.appendSwitch('disable-features', 'IOSurfaceCapturer,DesktopCaptureMacV2')`
1. Set `win.contentProtection(true)`
2. Share entire screen
3. Expected: Window is excluded from screen share

### Actual Behavior

3. Actual: Window is included in screen share

### Testcase Gist URL

https://gist.github.com/schontz/3f414a8f3ebc8db821fbf916f19cbed2

### Additional Information

Per https://github.com/electron/electron/issues/19880#issuecomment-1582039905, I attempted to use the `ScreenCaptureKitMac` flag, but it doesn't seem to work, or if it does, it's not consistent.

**Comment by schontz** [comment]
I did some more fiddling and confirmed that it breaks beginning with the first v24 beta. No issue in any v24 alpha or nightly builds.

**Comment by MarshallOfSound** [comment]
Duplicate #19880 

See https://github.com/electron/electron/issues/19880#issuecomment-1139115348
