### ISSUE TITLE
[Feature Request]: Adding TS types to `Menu.buildFromTemplate` to avoid runtime errors

### ISSUE THREAD

**Issue by 3v0k4** [electron/electron#38865]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

`Menu.buildFromTemplate` accepts anything as input:

https://github.com/electron/electron/blob/74d73166d93e569e96721fa4aaeac03698844240/lib/browser/api/menu.ts#L185

and later throws a `TypeError` if `template` is not an array:

https://github.com/electron/electron/blob/74d73166d93e569e96721fa4aaeac03698844240/lib/browser/api/menu.ts#L185-L188

### Proposed Solution

Is there any reason not to have `template` typed like in the following snippet and remove the runtime check and error?

```ts
Menu.buildFromTemplate = function (template: SomeType[]) {
```

### Alternatives Considered

No other alternatives considered.

### Additional Information

I'd be happy to submit a PR if the change is welcome. Also, I guess we could look into specializing the types so that also `areValidTemplateItems` is checked at compile time:

https://github.com/electron/electron/blob/74d73166d93e569e96721fa4aaeac03698844240/lib/browser/api/menu.ts#L185-L192

**Comment by MarshallOfSound** [comment]
This code is strongly typed, example from my editor.

<img width="748" alt="image" src="https://github.com/electron/electron/assets/6634592/0e683b86-1adb-4b84-adb6-29aed25969ea">

Typed in `electron.d.ts` (the types we publish) as:

```typescript
/**
 * Generally, the `template` is an array of `options` for constructing a MenuItem.
 * The usage can be referenced above.
 *
 * You can also attach other fields to the element of the `template` and they will
 * become properties of the constructed menu items.
 */
static buildFromTemplate(template: Array<(MenuItemConstructorOptions) | (MenuItem)>): Menu;
```

**Comment by 3v0k4** [comment]
🤦 My bad.

I switched from

```ts
const { Menu } = require("electron")
```

to

```js
import { Menu } from "electron"
```

and types started flowing properly.

Thanks for the nudge! 🙏

BTW, I was using the `require`s because I went through the [Quick Start](https://www.electronjs.org/docs/latest/tutorial/quick-start).
