### ISSUE TITLE
[Bug]: desktopCapturer doesn't capture area inside webstorm

### ISSUE THREAD

**Issue by rtukalenka** [electron/electron#38867]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.1

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.4

### What arch are you using?

x64

### Expected Behavior

desktopCapturer captures content in all windows

### Actual Behavior

desktopCapturer doesn't capture area inside webstorm when its window is active

### Additional Information

Hello Electron team. I want to thank you for a great product.

We need your help. Our team is developing an application for windows, macos using electron. The application allows the user to take a screenshot and send it to our server. When the program takes a screenshot, the area inside the webstorm window remains black, as if the entire area was intentionally blurred. This issue reproduces in macOS Ventura, macOS Catalina for webstorm with versions 2022.2 - 2023.1. I assume that this can somehow be connected with the transition of webstorm to a new UI, which, as I understand it, uses a new rendering engine, and in versions 2022.1 and below, where the old rendering engine is used, we do not experience such a problem. Perhaps this information will be useful https://bugs.openjdk.org/browse/JDK-8284381. We tried disabling all plugins, and also looking in the settings for some option that allows you to block screenshots inside webstorm, but there is no such option. Also, we noticed that if we place another smaller, active window on top of the webstorm window, we can see that the content in the webstorm window area is captured normally. Also, one user told us that the problem is relevant for sublime (unfortunately did not have time to check). You can use https://github.com/rtukalenka/screenshots test repository with minimal code to reproduce the issue. Any help would be invaluable.
Thanks and have a nice day

<img width="1211" alt="Снимок экрана 2023-06-21 в 09 49 16" src="https://github.com/electron/electron/assets/134746211/3b204ce6-0eb6-4a9f-8d3e-ffcd998ca936">
<img width="1272" alt="Снимок экрана 2023-06-21 в 09 49 46" src="https://github.com/electron/electron/assets/134746211/d67233ba-26fe-457a-bf98-c1611cac4ae4">

**Comment by codebytere** [comment]
@rtukalenka did you verify that this works as expected in Chrome itself? We use the upstream implementation, so we don't have as much control over the underlying implementation. If you find that it works there, we can investigate this further, otherwise your next best step is to open a bug on Chromium itself at https://crbug.com

**Comment by rtukalenka** [comment]
@codebytere You may not have seen or missed my question above. You can help?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
