### ISSUE TITLE
[Feature Request]: Request for RISC-V Architecture

### ISSUE THREAD

**Issue by gkdlight** [electron/electron#38892]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

**Request for RISC-V Architecture Package Support**

I would like to request official support for RISC-V architecture in Electron. Currently, Electron does not provide prebuilt binaries or support for RISC-V, which limits its usage on RISC-V platforms.  Is there any progress or plans regarding RISC-V architecture support in Electron?

Thank you,

### Proposed Solution

None

### Alternatives Considered

 I have reviewed the discussions in the Electron community (https://github.com/electron/electron/issues/32551) regarding RISC-V support, but it appears that the issue has been closed without a resolution.

**Comment by codebytere** [comment]
As noted in https://bugs.chromium.org/p/chromium/issues/detail?id=1443443 - Chromium is considering it. We may be willing to look to support it once they do, but for now it's not something we'd support unless Chromium does.

**Comment by garrdbyrd** [comment]
@codebytere I realize this issue is closed, but thought I'd spread the word about [this issue](https://github.com/microsoft/vscode/issues/206766) on the VS Code repo that has gained a bit of traction. Trying my best to communicate to upstream sources that their is a growing demand for this.
