### ISSUE TITLE
[Bug]: Windows Print Dialog Ignores Print Options

### ISSUE THREAD

**Issue by bimbimbu** [electron/electron#38915]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 230609

### What arch are you using?

x64

### Expected Behavior

When invoking `window.webContents.print({ silent:false, copies: 2, deviceName: x }, () => {})`, the Windows print dialog should correctly process and respect the provided options.

### Actual Behavior

The Windows print dialog does not process or respect any of the specified print options.

### Additional Information

rerender.js
```javascript
const printBtn = document.getElementById('print-btn')
printBtn.onclick = async () => {
  await window.versions.print("POS-80", "")
}
```

preload.js
```javascript
contextBridge.exposeInMainWorld('versions', {
    print: (printerName, data) => ipcRenderer.invoke('print', printerName, data)
})
```

main.js
```javascript
ipcMain.handle('print', (event, printerName, data) => {
    mainWindow.webContents.print({
      silent: false,
      copies: 2,
      deviceName: printerName,
    }, (success, failureReason) => {
      if (!success) {
        console.log(failureReason);
      } else {
        console.log('Print Success');
      }
    });
  })
  ```

![image](https://github.com/electron/electron/assets/119002301/94b969a3-e633-43f2-86f5-8eec39ffc93f)
![image](https://github.com/electron/electron/assets/119002301/de8e550a-3b0d-4953-be9d-58531d8128f8)

**Comment by pushkin-** [comment]
Can you determine in what version this broke exactly?

**Comment by Hedwig188** [comment]
Seems like a dup of [this issue](https://github.com/electron/electron/issues/29286).

**Comment by mlaurencin** [comment]
@bimbimbu Would it be possible for you to convert your test case to use [Electron Fiddle](https://www.electronjs.org/fiddle)? I see it is missing some of the button information and such, and it would be helpful to ensure everyone's looking at the same issue. With Fiddle you can then make and publish your small test case to a [gist](https://gist.github.com) that Electron maintainers can use.

**Comment by Methrat0n** [comment]
Still present in 27.1.3 I litteraly lost days on this now !
I would be open to fix it if anyone can share 2 hours to set me up 😄

**Comment by cndinx** [comment]
This issue still exists in version 28.1.3.
Why hasn't this been resolved?

**Comment by bimbimbu** [comment]
Very sorry for the late reply. We resolved the issue by downgrading to Electron version 24.x. This seems to have bypassed the problem with the Windows print dialog. Hope this information helps others facing similar issues.

**Comment by Methrat0n** [comment]
Bump
