### ISSUE TITLE
[Bug]: Error Cannot read properties of undefined (reading 'onClicked') when loading chat software line chrome extension

### ISSUE THREAD

**Issue by join-xiaohui** [electron/electron#38958]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise LTSC

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

The chat software line extension can be loaded properly

### Actual Behavior

With the following code:

`const {BrowserWindow, app , session } = require("electron")`

`app.on('ready', async () => {
    await session.defaultSession.loadExtension(
      path.join(__dirname, './public/ophjlpahpchlmihnnnihgmmeilfjmjjc/3.0.2_0'),
      { allowFileAccess: true }
    )
})
`

After running the command npm run dev, the following error occurs:

[1] [7356:0630/181122.640:ERROR:extensions_browser_client.cc(67)] Extension Error:
[1]   OTR:     false
[1]   Level:   2
[1]   Source:  chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/background.js
[1]   Message: Uncaught TypeError: Cannot read properties of undefined (reading 'onClicked')
[1]   ID:      ophjlpahpchlmihnnnihgmmeilfjmjjc
[1]   Type:    RuntimeError
[1]   Context: chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/background.js
[1]   Stack Trace:
[1]     {
[1]       Line:     1
[1]       Column:   1
[1]       URL:      chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/background.js
[1]       Function: (anonymous function)
[1]     }
[1] [7356:0630/181122.640:ERROR:extensions_browser_client.cc(67)] Extension Error:
[1]   OTR:     false
[1]   Level:   1
[1]   Source:  manifest.json
[1]   Message: Service worker registration failed. Status code: 15
[1]   ID:      ophjlpahpchlmihnnnihgmmeilfjmjjc
[1]   Type:    ManifestError

### Testcase Gist URL

https://github.com/join-xiaohui/de-mo.git

**Comment by samuelmaddock** [comment]
Electron has limited support for Chrome Extension APIs by default. Do you happen to know what API is being used for `onClicked`? It may fall outside of the [supported list of APIs.](https://www.electronjs.org/docs/latest/api/extensions#supported-extensions-apis)

**Comment by join-xiaohui** [comment]
> Electron has limited support for Chrome Extension APIs by default. Do you happen to know what API is being used for `onClicked`? It may fall outside of the [supported list of APIs.](https://www.electronjs.org/docs/latest/api/extensions#supported-extensions-apis)

Oh no, because the chrome extension was upgraded to v3, the previous browser_action was replaced with action in manifest.json, so chrome.action became an unsupported api

**Comment by join-xiaohui** [comment]
> > Electron has limited support for Chrome Extension APIs by default. Do you happen to know what API is being used for `onClicked`? It may fall outside of the [supported list of APIs.](https://www.electronjs.org/docs/latest/api/extensions#supported-extensions-apis)
> 
> Oh no, because the chrome extension was upgraded to v3, the previous browser_action was replaced with action in manifest.json, so chrome.action became an unsupported api

This seems like depressing news

**Comment by patil-milind** [comment]
@codebytere is there any plan to add support for `onClicked` API in the upcoming release of an electron?

**Comment by GoranMikulic** [comment]
@codebytere This is blocking Azure AD Login in Electron for a lot of organizations as the Windows Accounts extension has to be used to comply with AD policies.

**Comment by donghbcn** [comment]
I got the same problem. Is this supported already?
@join-xiaohui I found some electron app could load v3 extensions. Pleaes share it with me if you've found solution already, you can contact me at 16010651@qq.com

**Comment by UFO-001** [comment]
I'm also having the same issue, is it solved now?

**Comment by YangQingHua** [comment]
So how to solve this problem？

**Comment by GitMurf** [comment]
I see this was closed but was there ever a solution / outcome? Thanks!

**Comment by GitMurf** [comment]
> Just fill in the environment in `preload.js`

Can you explain? I do not know what that means.

**Comment by tanhh326** [comment]
> > Just fill in the environment in `preload.js`只需在 `preload.js` 中填写环境
> 
> Can you explain? I do not know what that means.您能解释一下吗？我不知道这是什么意思。

Supplement the environment, for example: window.chrome.action=｛onClick(){}｝

**Comment by GitMurf** [comment]
> Supplement the environment, for example: window.chrome.action=｛onClick(){}｝

Oh interesting so you mean basically monkey patching the chrome APIs that are not supported in Electron?
