### ISSUE TITLE
[Bug]: `BrowserWindow.isVisible()` doesn't take into account occlusion state

### ISSUE THREAD

**Issue by Imperat** [electron/electron#38955]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I found out that BrowserWindow on Mac started to take into account page occlusion state since this PR: https://github.com/electron/electron/pull/17463/files

BrowserWindow.isVisible() should return false if window is occluded by another window.

### Actual Behavior

BrowserWindow.isVisible() always returns true unless minimized.

### Testcase Gist URL

https://gist.github.com/Imperat/0ecffacee8d1386258d67a91e0017644

### Additional Information

Provided fiddle is best way to reproduce the issue: move browser window to the corner (or another screen) and open another app on top of browserWindow. Observe that in fiddle console "visible true" still logged.

**Comment by blimpich** [comment]
@codebytere Hello Shelly! It looks like there hasn't been much movement on https://github.com/electron/electron/pull/38982, but it looks close to being done! Do you know if you'll be able to continue work on it sometime soon? All good if not, just trying to figure out over at https://github.com/Expensify/App whether we should be investing in a workaround on our side, wait for this to be fixed upstream, or consider fixing it ourselves 🙂

**Comment by codebytere** [comment]
@blimpich https://github.com/electron/electron/pull/38982 is merged!

**Comment by blimpich** [comment]
Yay! Thank you

**Comment by blimpich** [comment]
Should this be reopened since it looks like the PR got [reverted](https://github.com/electron/electron/pull/41311)?
