### ISSUE TITLE
VERY STRANGE PROBLEM: Drm Widevine not work in Electron App, but it work in Chrome Browser

### ISSUE THREAD

**Issue by vanminhquangtri** [electron/electron#38959]
I got a very very strang problem, that I think it's may be from electron. 
I use **Widevide DRM** to play my protect video on project **Vue + Electron**.
I run electron:serve sucess at: http://localhost:80
On Electron APP: when call api DRM widevine to get key: it throw error: **HTTP Status 400 – Bad Request**

BUT, if I run http://localhost:80 **on Chrome, it has no problem**. So I would like if anyone can give me advice how to solve this, thank you.
My app version: 
"electron": "github:castlabs/electron-releases#v25.2.0+wvcus",
"electron-builder": "^23.2.0",
"vue": "^3.2.13",

player: dashjs 4.7.1

**Comment by samuelmaddock** [comment]
Widevine is not supported in the main version of Electron. You may want to try raising in issue in [the castLabs fork](https://github.com/castlabs/electron-releases), which it looks like you're using.
