### ISSUE TITLE
[Bug]: Taskbar Preview Displays Blank when window is minimized

### ISSUE THREAD

**Issue by RhodeHummel** [electron/electron#38952]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Expected Behavior

When the window is minimized, the taskbar preview should show the last valid render of the browser window.

### Actual Behavior

When the window is minimized, all of the webcontent is blank. All of the render content is black aside from the native toolbar.

The closest reported bug I can find is here.

#28255 [Bug]: Window contents disappear when webcontents is focused after a navigation all while the window is hidden

### Additional Information

Using `app.disableHardwareAcceleration()` seems to fix the problem. However this is not ideal as we want gpu acceleration on.

To duplicate create a new project using `npm create @quick-start/electron`. The base project has the problem. Even after upgrading to the latest stable electron version it still has the same problem.

This problem has also been observed on Teams, and Visual Studio Code which both use electron. However, it is not as consistent. I wonder how they were able to mitigate the problem.

Working:
<img width="189" alt="Screenshot 2023-06-29 at 8 35 04 AM" src="https://github.com/electron/electron/assets/1737359/12721d81-5dc8-470d-a2fa-a1e62479ecaa">

After minimizing:
<img width="185" alt="Screenshot 2023-06-29 at 8 36 09 AM" src="https://github.com/electron/electron/assets/1737359/95cd009e-6302-4697-90ba-d3387b07bb78">

**Comment by kuuroro** [comment]
me too

**Comment by RhodeHummel** [comment]
Here is the gist. It is just the standard Electron Fiddle project with nothing changed. https://gist.github.com/a8b9cce70e9e5464118e0301421d443a

When you minimize you may get a white screen (no text or images rendered) and in some cases a black screen.

**Comment by GhostlyDark** [comment]
This might be exclusive to Windows 11 and is reproducible at least as far back as Electron v22.
