### ISSUE TITLE
[Bug]: error callback on print

### ISSUE THREAD

**Issue by AkhmedovSH** [electron/electron#38975]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I have no paper in my printer and when I want print it document stay in queue
and electron 
window.contents.print(options, (success, errorType) => {
	console.log(success)
	console.log(errorType)
})

errorType is empty and success return true but i am not printed anything because no paper
if my document not printing success have to return false and if my document in a queue errorType have to return some information about it

### Actual Behavior

success true
and no errorType

**Comment by AkhmedovSH** [comment]
@codebytere sorry, any news about this issue

**Comment by codebytere** [comment]
> if my document not printing success have to return false and if my document in a queue errorType have to return some information about it

this is not correct. The method returns true if the document was successfully sent to the printer. Issues like the printer having no paper are not relevant to whether it returns `true`. This is also how Chrome works and how this API has always functioned.
