### ISSUE TITLE
[Bug]: render process will crashed after continuous running for one week

### ISSUE THREAD

**Issue by Durian-j** [electron/electron#38980]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.3

### What operating system are you using?

Other Linux

### Operating System Version

Linux sfere 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

22.0.3

### Expected Behavior

I want to avoid the problem of rendering process crashed while running continuously, rather than automatically restarting the application after a crash

### Actual Behavior

After the application runs for a week or so, it will crash, by listening to the render-process-gone event and printing a log to get this message

### Additional Information

I build a deb package through electron-builder and ran it on the touch screen of linux system. It will continue to run. During the test phase, I learned from the log that the rendering process would crash once a week or so, and the cause of the crash could not be found for the time being. Other times everything seems normal, and despite I listening to the render-process-gone to restart it, I still want to avoid this behavior.

**Comment by codebytere** [comment]
@Durian-j in order to proceed we'll need a reproducible sample or crash log of some kind, possibly with [`crashReporter`](https://github.com/electron/electron/blob/d1cddf2517fbcf159cb128f624aa28f3b6d3c342/docs/api/crash-reporter.md#L1). Please let us know if you're able to do so. This issue will be closed in 10 days if there is no response.

**Comment by Durian-j** [comment]
> @Durian-j in order to proceed we'll need a reproducible sample or crash log of some kind, possibly with [`crashReporter`](https://github.com/electron/electron/blob/d1cddf2517fbcf159cb128f624aa28f3b6d3c342/docs/api/crash-reporter.md#L1). Please let us know if you're able to do so. This issue will be closed in 10 days if there is no response.

Hello, these are some crash logs I have recently collected through the crash reporter, but I cannot understand them very well.

[reporter.zip](https://github.com/electron/electron/files/11950582/reporter.zip)

**Comment by Durian-j** [comment]
> @Durian-j in order to proceed we'll need a reproducible sample or crash log of some kind, possibly with [`crashReporter`](https://github.com/electron/electron/blob/d1cddf2517fbcf159cb128f624aa28f3b6d3c342/docs/api/crash-reporter.md#L1). Please let us know if you're able to do so. This issue will be closed in 10 days if there is no response.

By the way, the crash log content obtained by listening to the render-process-gone event is

``` json
{ reason: 'crashed', exitCode: 5 }
```

**Comment by michalzaq12** [comment]
@Durian-j, how did you solve the problem?
