### ISSUE TITLE
[Feature Request]: Security Recommendation - Run Jitless

### ISSUE THREAD

**Issue by xAzazellx** [electron/electron#38988]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There are many vulnerabilities when running in JIT Mode also it makes it impossible to add important security mitigations such as CET and ACG.

### Proposed Solution

Mainly add support similar to how Edge have implemented it.
It also supports WebAssembly.
https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-browse-safer

### Alternatives Considered

None other considered.

**Comment by MarshallOfSound** [comment]
You can run jitless already via `--js-flags='--jitless'`
