### ISSUE TITLE
Re: Keypress event from console

### ISSUE THREAD

**Issue by noname29** [electron/electron#38989]
https://www.electronjs.org/docs/latest/tutorial/keyboard-shortcuts

I understand I can hook key events with this, for the BROWSER WINDOW. How can I do the same for the CONSOLE ?

in nodejs, it goes with `process.stdin.setRawMode(true)` YET `process.stdin.setRawMode` is not a property of the app as I run my application with `electron myapp.js` rather than `node myapp.js`

Please help... Thank you in advance

I post again STOP forwarding us to Electron community or Discord server community is not helpful for these case and your discord invite link doesn't even work.

Thank you in advance

**Comment by codebytere** [comment]
@noname29 this is the correct Discord link: https://discord.gg/electronjs. 

Regardless - this issue forum is not for asking general questions. it is for requesting new features or raising bugs within Electron. I understand you're looking for assistance, but there are other forums better suited to this kind of question, like the Discord, Reddit, Stackoverflow, etc.
