### ISSUE TITLE
[Bug]: App won't launch on MacOS

### ISSUE THREAD

**Issue by chris-deep** [electron/electron#38985]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.1.0

### What operating system are you using?

macOS

### Operating System Version

13.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

21.1.0

### Expected Behavior

I have built an electron app (on v21.1.0) running on MacOS Apple Silicon.  I haven't built and installed / tested a production installer version for about 1-2 months but I did today and the app appears in mac taskbar but the window doesn't open.

Expected: 
- Launch app from Applications folder or from console with "open -a MyApp.app"
- App should run, display window

### Actual Behavior

The process gets created, the app icon appears in the Dock and then nothing.  The app window does not appear, no logging is sent to console, etc...

How do I launch the app on MacOS so I can see console/stdout output?  I've tried:

In Terminal > open -a MyApp.app
and
In Terminal > open -a MyApp.app --args --enable-logging

I've put several "console.log" in my boot script but I see nothing on the console when the app launches.  

No clue how to proceed.  Previously, I had built Mac and Win installers and was running / testing them fine.  But, without being able to get some console output, I can't diagnose what changed in my code / dependencies / configuration that is now preventing the app from running on Mac.

I'll test on Windows 11 ARM in a VM soon and see what happens.

### Additional Information

n/a

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
