### ISSUE TITLE
[Bug]: Record multiple screens error by using getUserMedia without chromeMediaSourceId on macOS

### ISSUE THREAD

**Issue by chinaofmelon** [electron/electron#38993]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS 14.0 beta(also reproduce in 13.4)

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

I have written a function to record the entire desktop in a render.ts file which is loaded in a window.
This function has constraint chromeMediaSource parameters(not include chromeMediaSourceId).
This works fine and records the screen. And all screen should be recorded.

### Actual Behavior

On macOS, when main screen was on the right, second screen on the left, some areas on the second screen cannot be recorded correctly, and main screen cannot be recorded correctly(Move an application on the screen to see this phenomenon). And if connect with iPad by using sidecar, the iPad screen will never be recorded.

This issue not reproduce on windows, And record work fine when constraint chromeMediaSourceId.

main screen: 1920 x 1080
second screen: 2560 x 1440

### Additional Information

All function are in html code:

`
<!DOCTYPE html>
<html>

    <head>
    <meta charset="utf-8">
    <title>apegv2-browser-welcome</title>
    </head>

    <body>
        <script type="text/javascript">
            var lastScreenStream = null;

            openScreen = async () => {
                try {
                    if (lastScreenStream) {
                        return;
                    }

                    lastScreenStream = lastScreenStream = await navigator.mediaDevices.getUserMedia({
                        video: {
                            mandatory: {
                                chromeMediaSource: 'desktop',
                                maxFrameRate: 10,
                            },
                        }
                    });

                    const screen = document.getElementById('screen');
                    let screenElement = null;
                    if (screen && screen instanceof HTMLVideoElement) {
                        screenElement = screen;
                        screenElement.srcObject = lastScreenStream;
                        screenElement.width = 1920;
                        screenElement.height = 1080;
                    }
                } catch (e) {
                    closeScreen();
                }
            }

            closeScreen = async () => {
                try {
                    if (lastScreenStream) {
                        lastScreenStream.getTracks().forEach(track => track.stop());
                        lastScreenStream = null;
                        const screen = document.getElementById('screen');
                        let screenElement = null;
                        if (screen && screen instanceof HTMLVideoElement) {
                            screen.srcObject = null;
                            screen = null;
                        }
                    }
                } catch (e) {
                }
            }
        </script>

        <button type="button" onclick="openScreen()">open screen sharing</button>
        <button type="button" onclick="closeScreen()">close screen sharing</button>

        <div>
            <video id="screen" autoPlay muted playsInline />
        </div>
    </body>

</html>
`

**Comment by chinaofmelon** [comment]
gist test link: https://gist.github.com/8fccd24ca5a38415873ac8b4a504ce0b

**Comment by chinaofmelon** [comment]
Any update?

**Comment by chinaofmelon** [comment]
Also, I can only record main screen(connect 2 screen to the macbook) when without chromeMediaSourceId constraint. and this issue happened in MacBook Air M2, 2022(14.0 beta).

**Comment by ilya-lopukhin** [comment]
I'm experiencing the same issue with MacOS 14.0 (23A344) and electron 27.0.0
passing `screen:1:0` `screen:2:0` returned from `desktopCapturer.getSources` to `chromeMediaSourceId` results in `Uncaught DOMException: Could not start video source` error.

 Electron application windows themselves return a valid stream as well as main display stream is visible if you don't pass `chomeMediaSourceId` at all to the GUM.

**Comment by valeriangalliat** [comment]
Same issue here, Electron 28.1.4

`chromeMediaSource: 'desktop'` "works" but it only shows the desktop background and a frozen picture of my app window, but no other window (or even menu items) on the screen, like if it needed some permission to "see" other windows?? Only the cursor is moving in the video stream, but everything else appears frozen

Setting `chromeMediaSourceId: 'screen:1:0'` (from `desktopCapturer.getSources`) results in `DOMException: Could not start video source`

**Comment by imyuanx** [comment]
The same problem, as long as 'chromeMediaSourceId' exists, will get an error :' DOMException: Can't start video source '.
