### ISSUE TITLE
[Bug]: setContentProtection not working on macOS when connect via remote desktop tool like anydesk , splashtop etc..

### ISSUE THREAD

**Issue by Britto28** [electron/electron#38994]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

it should not allow to take screen shot or recording if the setContentProtection is set to true even if remote desktop tool access.

### Actual Behavior

The setContentProtection is set to true,  it allows to take screen shot and recording even via remote desktop tool like anydesk, splashtop and micro soft remote desktop etc...

**Comment by codebytere** [comment]
Duplicate of https://github.com/electron/electron/issues/38973
