### ISSUE TITLE
[Bug]: Finalizer never invoked in Electron app

### ISSUE THREAD

**Issue by xiazhvera** [electron/electron#39001]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

macOS

### Operating System Version

13.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

napi_finalize get invoked.

### Actual Behavior

The napi_finalize never invoked. 

### Additional Information

I created a node library and used it in an electron app. However, on electron quit, the finalize callback never get called. 
This is how I initialize the napi library, I skipped some of the native codes:
```
struct napi_obj {
    napi_ref ref;
   // Skipped other native members in the struct
};

static void s_napi_context_finalize(napi_env env, void *user_data, void *finalize_hint) {
  struct napi_obj *obj = user_data;
  napi_delete_reference(env, obj->ref)

  // release other native members
   my_native_allocator->release(obj);
}


NAPI_MODULE_INIT() /* (napi_env env, napi_value exports) */ {

  struct napi_obj *obj = my_native_allocator->malloc(sizeof(struct napi_obj));

  /* bind the context to exports, thus binding its lifetime to that object */
  AWS_NAPI_ENSURE(env, napi_wrap(env, exports, ctx, s_napi_context_finalize, NULL, &obj->ref));

  // make sure increase the ref, the ref should keep the electron alive until the finalize delete the ref? 
  AWS_NAPI_ENSURE(env, napi_reference_ref(env, obj->ref, NULL));
  
  // Binding other functions and classes to `exports`

  return exports;
}
```

Correct me if I'm wrong, to make sure the finalize get invoked, I create a ref to keep the binding alive, and delete it in finalize. However, it seems that `s_napi_context_finalize` never get triggered on when I quit the electron app. 
I've seen search the issues, and saw some closed issue with similar finalize problem in Electron, however, none of them are closed with an solution. Any idea or suggestions?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
