### ISSUE TITLE
[Bug]: powerSaveBlocker.stop() is incorrectly typed

### ISSUE THREAD

**Issue by christianlundberg** [electron/electron#39015]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The return type of the `stop` function should be correctly typed as `boolean`

```typescript
// stopped should be infered as boolean
const stopped = powerSaveBlocker.stop(id);
``` 

### Actual Behavior

The return type of the `stop` function is `void`, thus attempting to assign the return value to a variable results in the error `Type 'void' is not assignable to type 'boolean'.` which can only be overcome by forcefully casting to `boolean`.

```typescript
const stopped = powerSaveBlocker.stop(id) as unknown as boolean;
console.log(stopped); // prints true or false;
```

**Comment by georgexu99** [comment]
PR is certainly welcome!

**Comment by VIRAT9358** [comment]
I am new to open source .Can you please specify the file .I am unable to navigate to that file

**Comment by VIRAT9358** [comment]
This is my first open source contribution in such a big codebase.
Review is required for merging .
Please let me know if anything more is required .

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/39320
