### ISSUE TITLE
[Bug]: No ways to configure trusted domains for storing third-party cookies or allow all

### ISSUE THREAD

**Issue by MurzNN** [electron/electron#39021]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

Many web services require storing third-party cookies to keep the authorization and other things. For example, Microsoft products for the web require this.
So, Electron should provide some API to configure the list of allowed domains or allow any domain in the web view element settings.

### Actual Behavior

Seems Electron just refuses to store all third-party cookies, and there are no ways to allow them or configure the list of domains.

Here is the explanation how to resolve this "constantly logging out" problem in Chromium: https://learn.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution

But seems this is not applicable for Electron, because of missing API. of 

### Additional Information

If there already exists some API to configure 3rd party cookie rules, please point me out to the documentation. Thanks!

**Comment by mlaurencin** [comment]
I would suggest looking at the documentation on [electronjs.org](https://www.electronjs.org) to see if you can find what you are looking for. If it is not there, you could look to [the Electron Discord server](https://discord.com/invite/electron) to see if anyone has run into this problem before and has a solution. And if neither of those two options work, feel free to refile this issue as an enhancement rather than a bug.
