### ISSUE TITLE
[Bug]: Close the iframe, then open the iframe, and open the Web page with the same name through window.open, still the old web page

### ISSUE THREAD

**Issue by 1339240789** [electron/electron#39022]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.1

### What operating system are you using?

Windows

### Operating System Version

win 11

### What arch are you using?

x64

### Expected Behavior

When ifrmae is removed and re-added, open the web page with the same name again through window.open and it should reopen

https://github.com/electron/electron/assets/71307878/65a2b60c-3cdb-40e0-b824-d19dfbdb7734

### Actual Behavior

If you use window.open to create a web page with name in iframe, close the iframe and open the iframe again. If you create a web page with name in window.open, no new web page is opened.

https://github.com/electron/electron/assets/71307878/0600c260-b4ff-4a0b-addb-61f1260c0673

### Testcase Gist URL

https://gist.github.com/b2cf9337e3bd6cd05e3bef11fe81423a

**Comment by 1339240789** [comment]
This is a bit like when the iframe is removed and the resources are not freed up, the memory still carries the old window.open web page with name, causing the iframe to be re-added and the window.open with nama to be re-called still refreshes the old web page without refiring the setWindowOpenHandler

**Comment by 1339240789** [comment]
It should be that the iframe is not released after being removed. When I remove the ifrma on the page, I still see the relevant information of the iframe in the console;
![image](https://github.com/electron/electron/assets/71307878/2897e512-5ae0-4c2b-bf1d-94ea773f4b57)
![image](https://github.com/electron/electron/assets/71307878/e90622ab-376b-437c-ba3a-02d004b1a5d5)

**Comment by 1339240789** [comment]
In A and B two different pages, call window.open, the second argument uses the same name, it should pop up two pages, but in fact only one.The second parameter name in window.open does not appear to be bound to the page that called it

**Comment by mlaurencin** [comment]
It looks like they changed the parameter names in the [native documentation](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#parameters). 'frameName' in the [Electron documentation](https://www.electronjs.org/docs/latest/api/window-open) refers to 'target' in the native documentation. With that being noted, the native documentation states that "If the name doesn't identify an existing context, a new context is created and given the specified name." So in order to have different windows open at the same time, you need to have different frameNames. There are other specific keywords that can be utilized as well.

I will updated the Electron documentation to reflect the changed named in the native documentation.

**Comment by 1339240789** [comment]
What I mean is that different Browser Windows should pop up two Windows, not the same one, even if they call the same target, and the later call can't change the window.location of the pop-up window

**Comment by mlaurencin** [comment]
If you are looking to have two separate Brower Windows pop up, the keyword "_blank" from the documentation should work for you. 

If that does not work for your specific situation, I recommend checking out this [Discord](https://discord.gg/electronjs). There are a bunch of helpful people in there that should be willing to point you in the right direction. We have many active help channels and mentors, as well as fellow devs, who can help you out with this and other potential questions you may have in future.
