### ISSUE TITLE
[Bug]: Log "Check failed: false" when trying to use webContents.print()

### ISSUE THREAD

**Issue by laux98** [electron/electron#39025]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.2 LTS

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

Hello, I am trying to open the print interface from an electron app with these part of code : 

public/electron.js

```js
function handlePrint(event, options) {
 const webContents = event.sender;
  const win = BrowserWindow.fromWebContents(webContents);
  win.webContents.print(options, (success, failureReason) => {
   if (!success) console.log("Failure raison : ", failureReason);
    console.log("Print Initiated");
  });
}

 //Some other code

app.whenReady().then(() => {
  //Some other code
  //Some other code
  createWindow();
  ipcMain.on("print", handlePrint);
  //Some other code
  //Some other code
});

```

public/preload.js
```js
process.once("loaded", () => {
 contextBridge.exposeInMainWorld("electronAPI", {
  print: (options) => {
   console.log('HERE I AM ?')
    ipcRenderer.send("print", options)},
  });
});
```

src/front.tsx

```ts
<Button
 style={{ width: "auto" }}
 onClick={() => {
  console.log("Clicked here");
  (window as any)?.electronAPI?.print?.({ silent: false });
 }}
>
 PRINT
</Button>
```

The expected result is the display of the interface which displays the configurations for printing.

### Actual Behavior

When I click on the button "PRINT", an error message is displayed on the console.

`[62080:0707/152327.433298:ERROR:check.cc(222)] Check failed: false.`

### Additional Information

I am trying to implement this solution because, initially I wanted to use the window.print() function but when using it, the application crashes and the following messages are displayed in the console.

```
#0 0x55b5a441c533 <unknown>
#1 0x55b5a441055c <unknown>
#2 0x55b5a441052b close
#3 0x7f87ba98cef3 <unknown>
```

Hhanks in advance if anyone has an idea for a solution.

**Comment by basil** [comment]
Same issue here.

**Comment by basil** [comment]
Worked around the issue by downgrading to Electron 24.6.2. This is a regression.

**Comment by laux98** [comment]
> Worked around the issue by downgrading to Electron 24.6.2. This is a regression.

Even if I switch to 24.6.2, nothing changes and I have the same problems

**Comment by basil** [comment]
@codebytere Based on https://github.com/electron/electron/issues/39025#issuecomment-1629442277 could the `has-repro-comment` label be added to this ticket?

**Comment by basil** [comment]
bump

**Comment by kmieshkov1** [comment]
Faced the same issue today using Cypress with Electron v25.8.0
Downgrade Cypress to 13.2.0 (which has Electron v21.0.0) resolved it

**Comment by basil** [comment]
I can no longer reproduce the issue on Electron 28.1.1. This ticket can be closed.
