### ISSUE TITLE
[Bug]: protocol.handle() is not working with file protocol

### ISSUE THREAD

**Issue by Aasim-A** [electron/electron#39031]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Other Linux

### Operating System Version

6.4.1-arch2-1

### What arch are you using?

x64

### Expected Behavior

When using `protocol.handle()` to intercept the `file` protocol, the handler should be called and `handle()` should be intercepting the request.

### Actual Behavior

`protocol.handle()` is not calling the handler and the request finishes without going through the interceptor.

### Testcase Gist URL

https://gist.github.com/Aasim-A/87b30a9acf3b4cbc61e8102290f9197b

### Additional Information

When I try to do the same thing with `http` or any custom protocol, it works without any issues.

**Comment by pengx17** [comment]
I too have the same trouble of migrating custom protocols besides `file`.
When I registered a custom protocol in https://www.electronjs.org/docs/latest/api/protocol#protocolhandlescheme-handler and the renderer tries to fetch `app://bundle/`, the browser will report "Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, chrome, https, chrome-untrusted." error.

**Comment by Aasim-A** [comment]
> I too have the same trouble of migrating custom protocols besides file.

You need to register the protocol like so:
```js
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'app',
    privileges: {
      secure: true,
      standard: true,
      supportFetchAPI: true, // Add this if you want to use fetch with this protocol.
      // stream: true, // Add this if you intend to use the protocol for streaming i.e. in video/audio html tags.
      // corsEnabled: true, // Add this if you need to enable cors for this protocol.
    },
  },
]);
```
this has to run before app's `ready` event.
