### ISSUE TITLE
[Bug]: [Squirrel.Windows] update does not remember the tray icon position

### ISSUE THREAD

**Issue by tbertels** [electron/electron#39032]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### What arch are you using?

x64

### Expected Behavior

Update remembers the tray icon position.

### Actual Behavior

Update does not remember the tray icon position.

### Additional Information

Squirrel.Windows issue: https://github.com/Squirrel/Squirrel.Windows/issues/863
Reproduced in element-desktop https://github.com/vector-im/element-desktop/issues/786

Fixed by https://github.com/Squirrel/Squirrel.Windows/pull/1835, but since [Squirrel.Windows didn't get any new release](https://github.com/electron/electron/issues/17722) since 2020, it could be added as a [patch](https://github.com/electron/electron/tree/main/patches/).

**Comment by MarshallOfSound** [comment]
@tbertels This can be "fixed" by providing a unique guid to the `new Tray` constructor.  This guid should be unique to your app and **never** change.  It is associated with your apps signature so changing your apps name or signature will invalidate the guid and you'll have to ship an update with a new guid.  Be careful when testing this feature as each guid you use on an unsigned app will be "burned" by windows.

**Comment by tbertels** [comment]
Thanks!
