### ISSUE TITLE
[Bug]: SIGSEGV after window.close() called inside a webview

### ISSUE THREAD

**Issue by jeanfbrito** [electron/electron#39040]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.3.1

### What arch are you using?

x64

### Expected Behavior

Just close the window that contains the webview.

### Actual Behavior

It crashes the Electron app.
`Electron exited with signal SIGSEGV.`

### Testcase Gist URL

https://gist.github.com/jeanfbrito/c5373cbe102b05e68f05d80ca515b066

### Additional Information

We started to have reports of this error on Windows and macOS since Electron v22. 
Before we didn't use a new window with a webview inside for video calls.
When the `window.close()` happens directly on the window content, it doesn't crashes.

**Comment by codebytere** [comment]
@jeanfbrito this has already been solved! https://github.com/electron/electron/pull/38996 should be out in the next version of v25.

**Comment by jeanfbrito** [comment]
@codebytere thank you!!!
