### ISSUE TITLE
[Bug]: 26.0.0-beta.3 clipboard.readImage causes error RAW Bad optional access

### ISSUE THREAD

**Issue by johnlindquist** [electron/electron#39055]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0-beta.3

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

25.2.0

### Expected Behavior

Not to crash

### Actual Behavior

Running clipboard.readImage() completely crashes the app

### Testcase Gist URL

https://gist.github.com/johnlindquist/db52bd78f76afc33366241ccf3d0cb2a

### Additional Information

Make sure to have an image in the clipboard or else it won't crash.

**Comment by codebytere** [comment]
Tracked to https://github.com/electron/electron/compare/v26.0.0-nightly.20230524...v26.0.0-nightly.20230525

**Comment by johnlindquist** [comment]
@codebytere This still crashes in 26.0.0-beta.7, it just crashes silently now. Use the same fiddle as above to reproduce. Again, make sure to have an image in the clipboard to see the crash.
