### ISSUE TITLE
[Bug]: Performance degraded between versions 24 & 25

### ISSUE THREAD

**Issue by JuanIrache** [electron/electron#39052]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0

### What operating system are you using?

macOS

### Operating System Version

13.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

24.6.2

### Expected Behavior

@25 should be as performant as  @24

### Actual Behavior

Performance is heavily degraded in versions 25 and newer. On my end, this is happening when loading mulitple HTML video elements and scrolling between them as if they were a single video.

### Additional Information

I will try to make a minimal test gist, but given the complexity of my project, it might take me a bit to isolate the necessary components to reproduce this. Just wondering if anyone knows what could be behaving differently between @24 and @25 that could be affecting this

**Comment by VerteDinde** [comment]
Hey @JuanIrache, I realize that providing a repro isn't easy - if you're able to link to the project itself (if it's public), we can also take a look. It's pretty difficult to tell what could be the issue without seeing the code, unfortunately. If you could send us a performance trace from devtools, we can also see what events are taking a longer amount of time.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
