### ISSUE TITLE
[Bug]: Cannot generate a FCM token for push notification in electron app in react js project

### ISSUE THREAD

**Issue by shahketul11** [electron/electron#39053]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.3

### What arch are you using?

x64

### Expected Behavior

Should get a FCM token in electron app

### Actual Behavior

Does not generate a Firebase token in electron app
![Screenshot 2023-07-11 at 3 59 47 PM](https://github.com/electron/electron/assets/123630563/70e8f2a1-aa57-4133-bb82-2bdec1fa557e)

**Comment by shahketul11** [comment]
If anyone can help me? It would be a great help for me!

Thanks in advance

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
