### ISSUE TITLE
[Bug]: Child window can't be minimized on Mac when it's brought back by activating the parent window rather than through the minimize section of the dock

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#39078]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I expect to be able to minimize a child window correctly

### Actual Behavior

After the first minimize, if I get the window back by activating the parent window (since I guess the child is brought up since it's supposed to be on top of the parent), I can't minimize/close it.
It needs to be retrieved from the minimize section of the doc

### Testcase Gist URL

https://gist.github.com/pushkin-/c7f43c9692b085adca3a784a390eb89b

### Additional Information

1. start gist
2. click Open Window button
3. minimize the child window (seems to work the first time)
4. then pull it back from the dock (I had to click on some other application and then my app)
5. now the minimize button doesn't do anything. Neither does the X. If I bring the child window back via the minimize section of the dock, then it works fine.

Only happens when the window is a child window.

**Comment by codebytere** [comment]
@pushkin- it looks like this is hitting a cocoa bug where deminiaturizing a parent window when the original window minimized was the child window doesn't properly restore the child window. I'll try to find a better solution but in the meantime, when this happens, you can hook the `show` event for the parent and call `child.restore()`.
