### ISSUE TITLE
[Feature Request] Bold or default menu items 

### ISSUE THREAD

**Issue by brandonwamboldt** [electron/electron#3908]
Windows context menus can have a "default" menu item that appears bolded. It would be great if we could emulate this with the Menu api in Electron.

Example:

![untitled-3](https://cloud.githubusercontent.com/assets/629141/11987213/76082f24-a9b1-11e5-9daf-c2e18222111d.png)

**Comment by zcbenz** [comment]
Unfortunately this is not possible on OS X, and I'm closing this as won't fix.

**Comment by mifozski** [comment]
Maybe, this functionality can be added only to windows implementations, like add a property to MenuItem called 'bold' that works only for Windows.

**Comment by vanowm** [comment]
Why won't fix? There is `toolTip` that only works on MacOS, why can't we have "default" style on platforms that support that?
