### ISSUE TITLE
[Bug]: window 'close' event sometimes doesn't always fire after app `before-quit`

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#39094]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.0

### What operating system are you using?

macOS

### Operating System Version

13.4.1

### What arch are you using?

x64

### Expected Behavior

According to document, unless we run an update - `before-quit` is:

> Emitted before the application starts closing its windows. Calling event.preventDefault() will prevent the default behavior, which is terminating the application.

Which implies that `close` event should be fired on all active windows afterwards.

### Actual Behavior

However, we found that in rare cases `close` event doesn't seem to be fired after `before-quit` doesn't seem to happen. There is no known repro for it, but it was reported by different users.

**Comment by VerteDinde** [comment]
🤔 The window list losing reference to the window is definitely possible? I added a blocked/needs-info, just since we don't have a consistent repro, but I'll bring this up at the Releases meeting this week and we can take a deeper look at it

**Comment by indutny-signal** [comment]
@VerteDinde sorry to ping you on this, but did you get a chance to discuss this since your previous comment? I'm curious what you found out!

**Comment by SuperShan0926** [comment]
> 


so did i, in some rare cases, when we emit the close event to main process, our log shows the `window.close` has been called, but the 'closed' event just not triggered and the window were still exist, and i don't know how to reproduce it 😂

**Comment by SuperShan0926** [comment]
> 🤔 The window list losing reference to the window is definitely possible? I added a blocked/needs-info, just since we don't have a consistent repro, but I'll bring this up at the Releases meeting this week and we can take a deeper look at it


so did i, in some rare cases, when we emit the close event to main process, our log shows the `window.close` has been called, but the 'closed' event just not triggered and the window were still exist, and i don't know how to reproduce it 😂
