### ISSUE TITLE
[Bug]: WebContents.print fails with {silent: true}

### ISSUE THREAD

**Issue by mgalla10** [electron/electron#39092]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Last Known Working Electron version

24.6.3

### Expected Behavior

If I call webContents.print({silent: true, deviceName: "Microsoft Print to PDF"}), a save dialog should appear asking me where I want to save a PDF of the webContents' print content. If I omit deviceName, it should automatically print to my default printer using my default settings.

### Actual Behavior

Nothing happens - the print call doesn't fail, but doesn't call its callback until I close the application, at which point it runs and provides success = false and a blank failureReason. If I attempt to print multiple times before closing the application, subsequent calls result in the callback immediately being called with success = false and a blank failureReason.

### Testcase Gist URL

https://gist.github.com/mgalla10/053de2471f74277e60fb908aaa3685ff

### Additional Information

This is an issue for all versions of v25 (although versions up to and including v25.1.0 break due to a "Printer settings invalid for" error that was fixed in v25.1.1). From what I've tested, this works for all versions of v24.

It's a fairly common workflow for us to determine the print settings via a different UI, then silently print them using this API, so this bug unfortunately keeps us from being able to release v25.

**Comment by codebytere** [comment]
@mgalla10 thanks for flagging this - I actually fixed this earlier but hadn't gotten to backport it to 25 yet. This will be fixed when https://github.com/electron/electron/pull/39095 lands - i'm going to close this issue though since we close issues when they're closed in main.
