### ISSUE TITLE
[Bug]: WebContents.print fails with {dpi: {horizontal: 0, vertical: 0}}

### ISSUE THREAD

**Issue by mgalla10** [electron/electron#39108]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v25.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Last Known Working Electron version

v24.6.3

### Expected Behavior

We specify a horizontal and vertical DPI of 0 to work around an issue with printing where providing unspecified DPI values seems to result in the lowest available DPI being used, whereas providing unsupported DPI values seems to result in the default DPI being used (https://github.com/electron/electron/issues/18917#issuecomment-781136205). In Electron v24, calling `webContents.print({ dpi: { horizontal: 0, vertical: 0 } })` doesn't crash and causes the default DPI to be used, as expected.

### Actual Behavior

In Electron v25, the `webContents.print()` call fails if given a DPI with horizontal and vertical sizes of 0. When running from Electron Fiddle, the following message is logged to the console:

[49556:0714/153022.964:ERROR:device_event_log_impl.cc(222)] [15:30:22.964] Printer: print_view_manager_base.cc:352 Printer settings invalid for Microsoft Print to PDF (destination type kLocal): content size is empty; page size is empty; printable area is empty; invalid DPI dimensions

### Testcase Gist URL

https://gist.github.com/mgalla10/606893c8c876ff1396a1d87bdc5c0880

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/39095

**Comment by mgalla10** [comment]
This doesn't seem to be fixed by #39095 - silent printing now works as expected, but passing { dpi: horizontal: 0, vertical: 0 }} as the print options still results in the same "invalid DPI dimensions" error. The gist I provided above still reproduces the same error as before in version 25.3.1. Can we re-open this?

**Comment by mgalla10** [comment]
@codebytere Can we re-open this for Electron v25? This is still easily reproducible in v25.3.1, and one of our printing workflows is broken without it.

**Comment by cah-eric-waight01** [comment]
I am facing this same issue, stuck on Electron 24.6.1 because of this. Can this issue be reopened? I have verified this still doesn't work in the latest version.
