### ISSUE TITLE
[Feature Request]: spec test

### ISSUE THREAD

**Issue by wugaosheng123** [electron/electron#39103]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi , I have this need to ask. I need a tool to check the compatibility of electron on our platform. Because our operating system and hardware is quite complex and we have all kinds of hardware.
I found a test case for your electron framework that meets our needs. code under the electron/spec directory.
The test cases for electron are a separate electron and I don't know how I can separate the test cases from the electon code repository. I can run the test cases using `npm run test` after compiling electron, can the test cases run if electron is not compiled?

### Proposed Solution

1.How to be able to run test cases without compiling electron source code?
2.Can a test case be run as a separate application?

### Alternatives Considered

null

### Additional Information

NULL

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
