### ISSUE TITLE
[Feature Request]: Improve text rendering on Linux

### ISSUE THREAD

**Issue by ryuukk** [electron/electron#39115]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Text looks washed out on Linux with low-dpi 1080p screens 

The reason for that is Chromium passes wrong gamma correction values to Skia

https://bugs.chromium.org/p/chromium/issues/detail?id=1443720

You can see a side by side comparison (with chromium) here: https://github.com/ryuukk/linux-improvements/tree/main/chromium-patch-compare#readme

### Proposed Solution

I propose to include my patch:

https://github.com/ryuukk/linux-improvements/blob/main/chromium.md

### Alternatives Considered

The alternative is to get the patch finally accepted for Chromium, but this process is rather slow..

**Comment by MarshallOfSound** [comment]
> The alternative is to get the patch finally accepted for Chromium, but this process is rather slow..

This is the correct path forward here, landing patches to Chromium is normally quite quick assuming the patch is valid and has reasonably explanations.  We tend to avoid deviating from upstream especially when it comes to more unknown-to-us areas of Chromium like this
