### ISSUE TITLE
[Bug]: unable to access property of window object that was attached from the main process when using v 17.2.0 or higher version.

### ISSUE THREAD

**Issue by arnabTeknikforce** [electron/electron#39113]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.2.0

### What operating system are you using?

Windows

### Operating System Version

windows11

### What arch are you using?

x64

### Last Known Working Electron version

17.1.2

### Expected Behavior

It should return the value every time.

### Actual Behavior

I am attaching a property to the window object using contextBridge.exposeInMainWorld() so that I can access that property from the renderer process. However, when using version 17.2.0 or higher, it does not function consistently, occasionally returning a value but sometimes returning undefined.

this is my preload script.
ipcRenderer.on("startup", (event, profileId) => {
  contextBridge.exposeInMainWorld("Startup", {
    profileId: profileId,
  });
});

**Comment by MarshallOfSound** [comment]
You are only calling `contextBridge.exposeInMainWorld` inside an IPC event handler,  that IPC message can arrive asynchronously _at any time_ and has no guarantees about when it arrives relative to page load or preload script execution.  If at any point that variable is `undefined` it's simply because that IPC message hasn't been received yet
