### ISSUE TITLE
[Bug]: Disable Microsoft store

### ISSUE THREAD

**Issue by toannguyen1412** [electron/electron#39120]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v26.0.0

### What operating system are you using?

Windows

### Operating System Version

Win 10

### What arch are you using?

x64

### Last Known Working Electron version

v26.0.0

### Expected Behavior

How to disable popup "You will need a new app to open this bytedance link"
I am test chrome & firefox => not show popup
But i am test on electron from version 19.0 => 26 => always show this popup
Url: https://seller-vn.tiktok.com/
```
  mainWindow.loadURL('https://seller-vn.tiktok.com/',{
    userAgent : 'Chrome'
  })
```
![You will need a new app to open this bytedance link](https://i.imgur.com/nzjcDAp.png)

**Comment by MarshallOfSound** [comment]
Deny the [`openExternal`](https://www.electronjs.org/docs/latest/api/session#sessetpermissionrequesthandlerhandler) permission request that page makes

**Comment by toannguyen1412** [comment]
thank you it work!!!

**Comment by toannguyen1412** [comment]
`
    const {webContents} = win
    session.defaultSession.setPermissionRequestHandler((webContents, permission, callback) => {
      if ( permission === 'openExternal') {
        return callback(false) // denied.
      }
    
      callback(true)
    })
    
`
