### ISSUE TITLE
[Bug]: Mac App gets rejected due to crash on launch

### ISSUE THREAD

**Issue by ndebartha** [electron/electron#39121]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

MacOs 13.4.1 

### What arch are you using?

Other (specify below) 
--arch=universal

### Expected Behavior

After successful upload to App Store, app should get approved for store release.

### Actual Behavior

App gets rejected by Apple. Saying  "We were unable to review your app as it crashed on launch on Mac running macOS 13.4.1.  The app cannot be opened because the developer cannot be verified."

After creating app bundle and codesign, when verifying with Apple's Signature Check, It's saying "The target is not signed with Developer ID or by the Mac App Store."

/Users/{user_account}/Documents/projects/out/myapp-mas-universal/myapp.app: The target is not signed with Developer ID or by the Mac App Store.
NO

Also doing,
spctl -a -t exec -vv myapp.app

Outputs, 

myapp.app: rejected
source=3rd Party Mac Developer Application: XXXXXXXXX (XXXXXXXXX)

 

### Additional Information

Attached complete report from Apple - 

Guideline 2.1 - Performance - App Completeness

We were unable to review your app as it crashed on launch on Mac running macOS 13.4.1. We have attached detailed crash logs to help troubleshoot this issue.

Guideline 2.1 - Performance

We discovered one or more bugs in your app when reviewed on Mac running macOS 13.4.1.

The app cannot be opened because the developer cannot be verified.

This may due to an issue with your app’s Gatekeeper conformance.

**Comment by MarshallOfSound** [comment]
This won't be an issue with Electron itself, at best it may be an issue with the tool you are using to build your Electron app.  If you're using `electron/forge` please raise an issue on that repository not here.

Please note that the error provided by apple is almost certainly accurate and the issue appears to be you are not signing your application with a Mac App Store certificate
