### ISSUE TITLE
[Feature Request]: Add Local Font Access API to the permission handler

### ISSUE THREAD

**Issue by Jelmerro** [electron/electron#39140]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, the local fonts are always allowed via `queryLocalFonts()`, it would make more sense to have this implemented in Electron via the permission handler.

### Proposed Solution

Make the `queryLocalFonts` API only be allowed if it is allowed via https://www.electronjs.org/docs/latest/api/session#sessetpermissioncheckhandlerhandler, as it will currently ignore any blocking done there, it doesn't seem to pass the handler.

### Alternatives Considered

Overriding the API manually via contextBridge and/or preloads window calls, but this is less ideal than having it in the official Electron permission handler.

### Additional Information

I found this while searching for a list of permissions to implement separatly in my own Electron project, and noticed this one which doesn't seem to do anything. It is listed in the code below, but not on the docs. This is similar to `idle-detection`, `persistent-storage`, `display-capture` and lots of others not listed in the docs, but unlike those, the `local-fonts` one is not used and actually bypassed as it never calls the handler.

https://github.com/electron/electron/blob/139774ce4857af1d897383eb81fc3dcb65f7170c/shell/common/gin_converters/content_converter.cc#L190-L247

**Comment by codebytere** [comment]
hey @Jelmerro - could you talk a bit more about what you're expecting? I've included a gist: https://gist.github.com/9b09103f20f19663a871c0a51ffa249c demonstrating it working as I'd expect. When `window.queryLocalFonts()` is called, `setPermissionCheckHandler` callback is invoked and if it is denied, `window.queryLocalFonts()` returns an empty array.

**Comment by Jelmerro** [comment]
It is confusing that it never reaches `setPermissionRequestHandler`, but only `setPermissionCheckHandler`. To my understanding, `setPermissionCheckHandler` is for `navigator.query`, while `setPermissionRequestHandler` (and by extension `setDevicePermissionHandler` are for the actual request, in this case `queryLocalFonts`, but when calling that it also uses `setPermissionCheckHandler` instead of `setPermissionRequestHandler`. Please compare the handling of querying notifications vs local-fonts and then `Notification.requestPermission()` and `queryLocalFonts()` to each other in terms of which handler is used when, and to me the difference in handling is confusing since it bypasses the request handler for fonts specifically, hence this issue.

**Comment by codebytere** [comment]
Ah - ok. Looked into this more, and unfortunately I don't think this is something we can fix in our own codebase. Chromium's permissions modeling can be a bit capricious, and while we implement check and request handlers, which is called is dependent on upstream logic. Here, [`queryLocalFonts`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/font_access/font_access.cc;l=48?q=%22EnumerateLocalFonts%22%20-f:gen%20&sq=package:chromium) calls [`FontAccessManager::EnumerateLocalFonts`](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/font_access/font_access_manager.cc;l=104;bpv=1;bpt=1?q=GetPermissionStatusForCurrentDocument%20font&sq=package:chromium), which then calls [`GetPermissionStatusForCurrentDocument`](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/font_access/font_access_manager.cc;l=104;bpv=1;bpt=1?q=GetPermissionStatusForCurrentDocument%20font&sq=package:chromium), which corresponds to our `setPermissionCheckHandler`. I'll poke around a little more but given there _is_ handling and it does work, i'm going to close this out.
