### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by KevalPanchalSilicon** [electron/electron#39153]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am creating an electron app based on react-app 
My react build size is around 8 MB, When I create an electron build for LINUX it will be 345 MB and WINDOWS build 400 MB

Now when I change small changes in react I need to create a new build of an electron, I have 1000 active users and everyone downloads 400 MB for each release you do 2 releases/week then the total bandwidth consumption for a month would be (400 MB x 4 x 2) x 1000 Users = ~3120 GB.

How to reduce electron application build size for new release using electron-builder.

Please guide me on this point.

### Proposed Solution

Reduced the build size for the release 

### Alternatives Considered

 If you have any other package please share it so we can integrate.

**Comment by mlaurencin** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
