### ISSUE TITLE
[Bug]: (desktopCapturer.getSources) not work properly in rocky

### ISSUE THREAD

**Issue by Canees** [electron/electron#39151]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.12

### What operating system are you using?

Other Linux

### Operating System Version

rocky9.2

### What arch are you using?

x64

### Last Known Working Electron version

19.0.12

### Expected Behavior

It works fine in ubuntu and Windows (returning thumbnail.todataURL ()), but in rocky it returns black.
A simple example is:
`    
const { size:{width,height} } = screen.getPrimaryDisplay();

const sors = await desktopCapturer.getSources({
      types: ['screen'],
      thumbnailSize: {
        width, height
      }
});

console.log(sors[0].toDataURL());
`

### Actual Behavior

It returns the data, but the data appears black

### Additional Information

A simple example is:
`    
const { size:{width,height} } = screen.getPrimaryDisplay();

const sors = await desktopCapturer.getSources({
      types: ['screen'],
      thumbnailSize: {
        width, height
      }
});

console.log(sors[0].toDataURL());
`

**Comment by Canees** [comment]
Compare ubuntu and rocky,ubuntu uses X11 windowing system, rocky uses wayland windowing system

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

If you’re still experiencing this issue in Electron 22.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by Canees** [comment]
Because it is compatible with Windows 7, the higher version is not true

**Comment by mlaurencin** [comment]
I am not sure what you mean by ‘not true'. Are you saying that you cannot use a supported version of Electron on rocky9.2 because you also need this to work in Windows 7?

**Comment by Canees** [comment]
> I am not sure what you mean by ‘not true'. Are you saying that you cannot use a supported version of Electron on rocky9.2 because you also need this to work in Windows 7?

I can't use the latest version because it doesn't support Windows 7

**Comment by Canees** [comment]
> I am not sure what you mean by ‘not true'. Are you saying that you cannot use a supported version of Electron on rocky9.2 because you also need this to work in Windows 7?

In rocky9.2, the screenshot is black

**Comment by mlaurencin** [comment]
Unfortunately, since we are only supporting 22.x.y and later at this time, this issue will be closed. If you experience this issue with a supported version, feel free to open a new issue.
