### ISSUE TITLE
[Bug]: visibility state can be changed to `hidden` when `backgroundThrottling` is disabled

### ISSUE THREAD

**Issue by xiaofeihan1** [electron/electron#39165]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.1

### What operating system are you using?

macOS

### Operating System Version

MacOS 13.4.1

### What arch are you using?

x64

### Expected Behavior

According to the [API doc](https://www.electronjs.org/docs/latest/api/browser-window#page-visibility), When  `backgroundThrottling` is `false, the `document.visibilityState` always return `visible` even if the window is minimized, occluded, or hidden.
> If backgroundThrottling is disabled, the visibility state will remain visible even if the window is minimized, occluded, or hidden.

### Actual Behavior

When  `backgroundThrottling` is `false, the `document.visibilityState` always return `hidden` when the window is minimized, occluded, or hidden.

### Testcase Gist URL

https://gist.github.com/xiaofeihan1/4aceba89108f9b1a5b6d577ddd50e565

### Additional Information

https://github.com/electron/electron/assets/107654914/f2b40385-8d51-42aa-a360-3537befe1797

**Comment by xiaofeihan1** [comment]
Hi @codebytere  I publish the test case to https://gist.github.com/xiaofeihan1/4aceba89108f9b1a5b6d577ddd50e565
And attach a video to the first comment. Thanks!

**Comment by codebytere** [comment]
hi @xiaofeihan1 - thanks! I looked into it a bit and it seems you're right and current behavior does not reflect the doc. It looks like when we introduced [this patch](https://github.com/electron/electron/blob/16aac6da13971f357a9ed8fcefd172ca2f6a8b0c/patches/chromium/disable_compositor_recycling.patch#L6-L7) it broke this behavior, and so now when `backgroundThrottling: false`, `document.visibilityState` still changes between hidden to visible. I'll see what i can do!

**Comment by xiaofeihan1** [comment]
Hi @codebytere This is also reproduced in Windows, so I think it should have nothing to do with [the patch](https://github.com/electron/electron/blob/16aac6da13971f357a9ed8fcefd172ca2f6a8b0c/patches/chromium/disable_compositor_recycling.patch#L6-L7)

First, I want to say, from a developer's perspective, perhaps our current behavior is what makes more sense than the documentation describes. And current behavior makes it easy for developers to understand the logic.
1. `BackgroundThrottling` does not affect visibility state
2. The web page's visibility state is always synced with native visibility

So I think we should update electron doc to describe the behavior instead of fixing the code.

Second, if we finally decide to fix code, I think it is related with the following code. When window is occluded/minimized/hidden, chromium will call `SetVisibilityState(hidden)` then call `GetPage()->SetVisibilityState` to change web page's visibility state. 
```
void WebViewImpl::SetVisibilityState(
     mojom::blink::PageVisibilityState visibility_state,
     bool is_initial_state) {
   DCHECK(GetPage());
   // 1. Set the visibility state of web page
   GetPage()->SetVisibilityState(visibility_state, is_initial_state);
   // 2. Set the JavaScript throttling
   GetPage()->GetPageScheduler()->SetPageVisible(
     visibility_state == mojom::blink::PageVisibilityState::kVisible);
      scheduler_throttling_allowed_ ?
          (visibility_state == mojom::blink::PageVisibilityState::kVisible) : true);
   // Notify observers of the change.
   ...
```

**Comment by codebytere** [comment]
At the moment, this is behavior contradictory to docs and the API contract made with our users. As such, it's a bug for which the expected solution is that we restore previous behavior. If you'd like to make a proposal that we change that behavior intentionally, that could be considered, but it would be a breaking change that would need to go through our API cycle.
