### ISSUE TITLE
[Bug]: Mp4 Video playback is failing

### ISSUE THREAD

**Issue by quinn-linear** [electron/electron#39182]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0-beta.1

### What operating system are you using?

macOS

### Operating System Version

Mac Ventura 13.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

25.0.1

### Expected Behavior

Video should playback inline

https://github.com/electron/electron/assets/97164745/0aab77da-87b2-40ee-bdad-da309558b475

### Actual Behavior

Video refuses to playback in version specified and also latest version beta-6

https://github.com/electron/electron/assets/97164745/23e8740d-dc3c-44a4-8eb9-3fa3a07ca081

Error in console is PIPELINE_ERROR_DECODE: Failed to parse H.264 stream

**Comment by codebytere** [comment]
@quinn-linear and the issue is on macOS? The videos provided look they're playing on a mobile device 🤔

**Comment by quinn-linear** [comment]
Yes, the video I attached is an example file that won't play on that
electron version, not the video of the bug.

**Comment by tommoor** [comment]
@quinn-linear looks like Electron `26.1.0` resolved this
