### ISSUE TITLE
[Bug]: ipcRenderer undefined in before-quit event

### ISSUE THREAD

**Issue by Welfordian** [electron/electron#39184]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.1

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.4.1

### What arch are you using?

x64

### Expected Behavior

Requiring `ipcRenderer` in the `before-quit` event should return the expected `ipcRenderer` object.

### Actual Behavior

`ipcRenderer` and `ipcMain` are both undefined, even after re-requiring within the event handler `require('electron').ipcRenderer`. I thought, perhaps, this was due to them being destroyed as this is a quit handler, but even if I immediately `e.preventDefault()`, they are both still undefined.

**Comment by Welfordian** [comment]
Here's the gist. I noticed that `ipcMain` is not undefined here, but `ipcRenderer` is.

https://gist.github.com/Welfordian/5e052f651698d84fc11ed4a527cb607a

Run the fiddle & `CMD+Q` then check the console.

**Comment by Welfordian** [comment]
I ran this under `25.0.1`, `25.2.0` & `26.0.0-beta.4`. Same results on each.

**Comment by Welfordian** [comment]
In this fiddle, I explicitly re-require `ipcRenderer` if it's undefined... but still, after requiring, it remains `undefined`.

https://gist.github.com/154b7299ae52dc0ec7d7d304103040c8

**Comment by MarshallOfSound** [comment]
`ipcRenderer` is not available in the main process per docs, I'm not sure what you're trying to do here but `ipcMain` is always available in the main process, ipcRenderer is only available in the renderer process.
