### ISSUE TITLE
[Feature Request]: Support `BrowserWindow` opacity on X11 via the `_NET_WM_WINDOW_OPACITY` property

### ISSUE THREAD

**Issue by somebody1234** [electron/electron#39197]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

`BrowserWindow` `opacity` does nothing on Linux: [docs](https://www.electronjs.org/docs/latest/api/browser-window#winsetopacityopacity-windows-macos)

### Proposed Solution

Support opacity on X11 via the `_NET_WM_WINDOW_OPACITY` EWMH X property

### Alternatives Considered

None

### Additional Information

The property is a 32-bit integer from `0` meaning fully transparent to `0xffffffff` meaning fully opaque

**Comment by codebytere** [comment]
Duplicate https://github.com/electron/electron/issues/23922
