### ISSUE TITLE
[Bug]: no cross(close) option on top bar Electron (Riot) flatpak

### ISSUE THREAD

**Issue by Naadiyaar** [electron/electron#39205]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

help!

### What operating system are you using?

Other Linux

### Operating System Version

Fedora workstation 38 (using Flatpak package)

### What arch are you using?

x64

### Expected Behavior

Existence of a close option on top bar

### Actual Behavior

There is no way to close Element-desktop flatpak version because there is no cross button on the top bar. This behavior is only seen on GNOME Wayland, and everything is ok while using GNOME with x11.
provided screenshot here: https://github.com/flathub/im.riot.Riot/issues/380#issue-1794933306

### Additional Information

Also top bar doesn't follow system theme, again only on Wayland

**Comment by frosth555** [comment]
look at:
https://github.com/electron/electron/issues/38786
it's fixed in electron 25.3.1

**Comment by Naadiyaar** [comment]
is there a way to figure out what Electron version is Element using? i coudn't find out myself

**Comment by codebytere** [comment]
Closing as fixed in 25.3.0
