### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by milin-debug** [electron/electron#39220]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

how can I match version   between   electron and electron-builder? for example,  I need electron version is ^19.0.10,            
   electron-builder is    _____?

### Proposed Solution

A matching table   between electron and   electron-builder   is needed,please

### Alternatives Considered

no

**Comment by MarshallOfSound** [comment]
electron-builder is a third party system, we do not officially support it, issues with that package should be raised on their repo
