### ISSUE TITLE
[Bug]: electron25 becomes blurred on wayland.

### ISSUE THREAD

**Issue by g0ne150** [electron/electron#39255]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v25.2.1

### What operating system are you using?

Other Linux

### Operating System Version

Linux 6.5.0-rc2-1-amd-drm-next-gbc1688fce2ec #1 SMP PREEMPT_DYNAMIC Wed, 26 Jul 2023 21:54:39 +0000 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

v24.6.2

### Expected Behavior

This is electron24 on same system and parameter:
![image](https://github.com/electron/electron/assets/8351695/7542064a-caa9-4654-aba3-3cfaa97e1e58)

### Actual Behavior

![image](https://github.com/electron/electron/assets/8351695/165e74a4-4520-46b9-8621-76f1d25417cf)

### Additional Information

- Display scale: 200%
- Parameter: `--enable-features=WaylandWindowDecorations --ozone-platform-hint=auto`
- Wayland: 1.22.0

**Comment by aiddya** [comment]
I assume that you're on GNOME and the mutter feature "scale-monitor-framebuffer" is not enabled.

This is a result of [Chromium changing their rendering behavior](https://bugs.chromium.org/p/chromium/issues/detail?id=1356014) to support fractional scales on Wayland. You can go back to the old behavior by adding the command line option `--disable-features=WaylandFractionalScaleV1`.

Alternatively, you could also enable "scale-monitor-framebuffer". You'd get support for fractional scales and multiple monitors with different scales at the cost of [losing HiDPI support for X11 applications](https://discourse.gnome.org/t/full-explanation-of-current-hidpi-fractional-and-integer-scaling-support-in-wayland/14225).

**Comment by g0ne150** [comment]
> I assume that you're on GNOME and the mutter feature "scale-monitor-framebuffer" is not enabled.
> 
> This is a result of [Chromium changing their rendering behavior](https://bugs.chromium.org/p/chromium/issues/detail?id=1356014) to support fractional scales on Wayland. You can go back to the old behavior by adding the command line option `--disable-features=WaylandFractionalScaleV1`.
> 
> Alternatively, you could enable the mutter feature "scale-monitor-framebuffer". You'd get support for fractional scales and multiple monitors with different scales at the cost of [losing HiDPI support for X11 applications](https://discourse.gnome.org/t/full-explanation-of-current-hidpi-fractional-and-integer-scaling-support-in-wayland/14225).

Great!!
