### ISSUE TITLE
[Bug]: will-download Unable to download images error

### ISSUE THREAD

**Issue by 82318179** [electron/electron#39263]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Windows

### Operating System Version

win11

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

I would like to access a website address through the main window, BrowserWindow https://weibo.com/2084401300/NbCMnnxeU?pagetype=profilefeed There is an image in this website, and the address of the image is https://wx1.sinaimg.cn/orj360/7c3d7094ly1hga4f3v3bhj20n01ds42o.jpg Now that the BrowserWindow can successfully see this image, download the image using Electron's downloadURL method. However, downloading the image using the downloadURL method always returns an error
下载失败: interrupted

### Actual Behavior

I would like to access a website address through the main window, BrowserWindow https://weibo.com/2084401300/NbCMnnxeU?pagetype=profilefeed There is an image in this website, and the address of the image is https://wx1.sinaimg.cn/orj360/7c3d7094ly1hga4f3v3bhj20n01ds42o.jpg Now that the BrowserWindow can successfully see this image, download the image using Electron's downloadURL method. However, downloading the image using the downloadURL method always returns an error
下载失败: interrupted

How can I download this image?

![image](https://github.com/electron/electron/assets/25976728/0936ab13-ab2f-467f-9db6-67aa4f3c1309)

### Testcase Gist URL

https://gist.github.com/d2ac218ee4660fa08378d00325af7eaa

**Comment by codebytere** [comment]
@82318179 I think this is unfortunately not something we're able to fix on our end: when you load that image into a browser, it's a 403 forbidden URL.
