### ISSUE TITLE
[Bug]: Printer "status" is not reporting correctly on Windows

### ISSUE THREAD

**Issue by WillPoulson** [electron/electron#39278]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

The `status` field from `getPrintersAsync` should be a numerical value associated to a status for that OS.

### Actual Behavior

The `status` field is always coming back as `0` on Windows.

However it's working fine on MacOS for the same printer. 

### Additional Information

This was reported a little while back in #16836 however got closed due to the original report now being an unsupported version.

**Comment by WillPoulson** [comment]
Thank you for triaging this bug @codebytere.

Please see my gist https://gist.github.com/WillPoulson/d209601e106a41a9c122292e3da3a162 for replicating this.

It's setup to log out your default printer status every second until the app quits. 

On MacOS (my current dev machine), it's working correctly and returning the status of `3` but if I run the same on Windows. It just always seems to be returning `0` regardless of if the printer is offline, online, busy, jammed etc.

**Comment by WillPoulson** [comment]
This issue is still impacting our application

**Comment by codebytere** [comment]
This unfortunately is not something we control in Electron - the return value maps directly to [this data structure](https://source.chromium.org/chromium/chromium/src/+/main:printing/backend/print_backend.h;l=32?q=printing::PrinterBasicInfo&sq=package:chromium&type=cs) in Chromium. It looks like that's set by Chromium [here](https://source.chromium.org/chromium/chromium/src/+/main:printing/backend/win_helper.cc;drc=7fa0c25da15ae39bbd2fd720832ec4df4fee705a;bpv=1;bpt=1;l=429) via [`PrintBackendWin::EnumeratePrinters`](https://source.chromium.org/chromium/chromium/src/+/main:printing/backend/print_backend_win.cc;drc=7fa0c25da15ae39bbd2fd720832ec4df4fee705a;bpv=1;bpt=1;l=361)- so if that's not working I'd say the best thing to do is to report this as an issue upstream at [crbug](https://crbug.com).

**Comment by hsddu** [comment]
> This issue is still impacting our application

how did you solved? I also encountered the same problem

**Comment by csozidev** [comment]
Did anybody find a solution for this problem?
