### ISSUE TITLE
[Bug]: Uncaught Error: Cannot read properties of undefined

### ISSUE THREAD

**Issue by mahdi9925** [electron/electron#39282]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.3.0

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Expected Behavior

I want to use shell  module in preload.js but there is a problem.
![image](https://github.com/electron/electron/assets/84701951/77eab4a9-21ff-411c-862c-7f7065d762e7)
but when I use electron 17 there isn't any problem.

I have same problem in clipboard module.
I can't run this code on preload.js

const { clipboard } = require('electron')
clipboard.writeText('Example string', 'selection')
console.log(clipboard.readText('selection'))

![image](https://github.com/electron/electron/assets/84701951/7a2d2d38-2002-4e6b-9959-8a0015892e55)

When I use ipc there isn't any problem.

### preload.js
import { shell } from "electron";
window.addEventListener("DOMContentLoaded", () => {
  const replaceText = (selector: string, text: string) => {
    const element = document.getElementById(selector);
    if (element) {
      element.innerText = text;
    }
  };
  for (const type of ["chrome", "node", "electron"]) {
    replaceText(
      `${type}-version`,
      process.versions[type as keyof NodeJS.ProcessVersions]
    );
  }
  shell.showItemInFolder("C:\\Users\\Mahdi-G3\\Desktop\\new");
});

**Comment by mahdi9925** [comment]
I fixed.
I should add `nodeIntegration: true,` to object `webPreferences` in mian.js file

**Comment by chelinho139** [comment]
This actually has to do with [Electron Sandbox](https://www.electronjs.org/docs/latest/tutorial/sandbox). 
You could keep nodeIntegrations off but disable the sandbox for more security.

Like this:
`
function createWindow() {

  let win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
        sandbox: false,
      nodeIntegration: false, 
      contextIsolation: true, 
      preload: path.join(__dirname, 'preload.js') 
    }
  });
`

**Comment by chelinho139** [comment]
If you would like to do it the safest way, then you should implement an IPC message and use the shell on your main file.

**main.js**
`
const { app, BrowserWindow, ipcMain, shell } = require('electron');

app.on('ready', () => {
  // Your code to create the BrowserWindow and other setup

  ipcMain.handle('open-link-externally', async (event, url) => {
    await shell.openExternal(url);
//or do other stuff with shell
  });
});

`
