### ISSUE TITLE
[Bug]: `setBackgroundColor` method of BrowserView doesn't work

### ISSUE THREAD

**Issue by aadcg** [electron/electron#39281]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.1

### What operating system are you using?

Other Linux

### Operating System Version

Linux 6.2.6 

### What arch are you using?

x64

### Expected Behavior

The background color should change.

### Actual Behavior

Nothing happens.

### Additional Information

```js
const { app, BrowserView, BrowserWindow } = require('electron')

app.whenReady().then(() => {
  const win = new BrowserWindow({ width: 800, height: 600 })
  win.loadURL('about:blank')

  const view = new BrowserView()
  win.setBrowserView(view)
  view.setBounds({ x: 0, y: 0, width: 300, height: 300 })
  view.setBackgroundColor("#000")
})
```

**Comment by anyerqi** [comment]
How about removing this line of your code: 
`win.loadURL('about:blank')`
