### ISSUE TITLE
One-Signal Push notifications 

### ISSUE THREAD

**Issue by Salmankhan033** [electron/electron#39286]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hey, I want to implement one signal notification in my Electron js(desktop app).
I haven't found any documentation about this.
Please help me how to integrate one signal notification on desktop app 

### Proposed Solution

How to implement one Signal notification on Electron js?

### Alternatives Considered

How to implement one Signal notification on Electron js?

**Comment by kingpower2542** [comment]
--
Sent from VK Mail app for Android วันอาทิตย์, 30 กรกฎาคม 2023, 06:21ก่อนเที่ยง +07:00 from Salman Khan  ***@***.*** :
