### ISSUE TITLE
[Bug]: Dock "Quit" does not work when a window has a modal dialog open

### ISSUE THREAD

**Issue by jcc1997** [electron/electron#39294]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.12

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.1

### What arch are you using?

x64

### Last Known Working Electron version

20.3.12

### Expected Behavior

Dock "Quit" does quit the application when a window has a modal dialog open

### Actual Behavior

Dock "Quit" does not work when a window has a modal dialog open

### Testcase Gist URL

https://gist.github.com/222aeb0010637c49328501a52c078ead

**Comment by codebytere** [comment]
Electron v20 isn't currently supported. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days f there is no response.
