### ISSUE TITLE
[Bug]: Using Node-ffi to load a 2gb file will cause the page to crash

### ISSUE THREAD

**Issue by feedline** [electron/electron#39319]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.9

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Expected Behavior

Loaded successfully and executed as expected.

### Actual Behavior

In the C code, it crashes when applying for memory, without any return or error.

### Additional Information

I used to validate in Node.js project(node main.js) and it executed fine, but in Electron, it crashed. I suspect that there is a memory limit during the execution of Electron, which leads to the failure to apply for memory. 
I have tried the app.commandLine.appendSwitch('js-flags', '--max_old_space_size=4096') method, but it didn't work. 
I don't know of any other than updating the C code to read file in chunks.

**Comment by codebytere** [comment]
@feedline Electron v13 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days f there is no response.
