### ISSUE TITLE
[Bug]: --trace-warnings option not doing anything

### ISSUE THREAD

**Issue by hovancik** [electron/electron#39322]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.2

### What operating system are you using?

Other (specify below)

### Operating System Version

any OS

### What arch are you using?

Other (specify below)

### Expected Behavior

I expect to get some more information about warning when using `--trace-warnings` 

### Actual Behavior

Same behavior as without `--trace-warnings`

`    "start": "electron  --trace-warnings ."`
```
electron-quick-start git:(main) npm start

> electron-quick-start@1.0.0 start
> electron . --trace-warnings

(node:22471) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 window-all-closed listeners added to [App]. Use emitter.setMaxListeners() to increase limit
(Use `electron --trace-warnings ...` to show where the warning was created)
```

`    "start": "electron  ."`
```
electron-quick-start git:(main) ✗ npm start

> electron-quick-start@1.0.0 start
> electron .

(node:22616) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 window-all-closed listeners added to [App]. Use emitter.setMaxListeners() to increase limit
(Use `electron --trace-warnings ...` to show where the warning was created)
```

### Testcase Gist URL

https://github.com/hovancik/electron-trace-warnings-isssue

**Comment by codebytere** [comment]
@hovancik we previously disallowed non-debug options from being passed via the command line, but we actually do currently allow setting this via the `process` object. I'll open a PR to align those settings.
