### ISSUE TITLE
[Bug]: Windows 11 window corner radii are exaggerated on non-hidpi display when hidpi display is primary

### ISSUE THREAD

**Issue by jono-hayward** [electron/electron#39339]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise v22H2

### What arch are you using?

x64

### Expected Behavior

The corners of windows should use an appropriate radius for the display they're on.

### Actual Behavior

I've observed this behaviour when using my laptop (a Dell XPS 13+ with 3840x2400 display) along with a second external display that is not HiDPI (in this case, an 34in ultrawide Acer screen running at 3440x1440).

If the HiDPI screen is set as the primary display in Windows, Electron apps will render their rounded corners at a radius appropriate for that display:
![Screenshot 2023-08-03 103258](https://github.com/electron/electron/assets/659408/672a2739-a075-4ae2-b87a-eba8729370ad)

But if that same window is moved to the _non_ HiDPI screen, the corner radius becomes exaggerated as it's still rendered as if it's on a higher resolution display:
![Screenshot 2023-08-03 103302](https://github.com/electron/electron/assets/659408/e13d6bd2-a4f9-4273-aabd-46ccd2cc64a1)

It's particularly evident when compared to a window not affected by this behaviour (in this case, Edge):
![image](https://github.com/electron/electron/assets/659408/7261dbbb-2486-414e-a55b-3120bc0fc61d)

I've observed this behaviour on multiple apps from multiple vendors, all based on Electron:
- Microsoft Teams
- Microsoft VS Code
- GitHub Desktop (Electron v24.4.0)
- Postman (Electron v18.3.5)

### Additional Information

For context: I'm not a developer of Electron apps; I'm just a user who's noticed a consistent behaviour across multiple production apps that use Electron, suggesting it's an issue with the framework itself.

**Comment by jono-hayward** [comment]
Unfortunately, as I said I'm not a developer, I have no ability to write code that would replicate this issue. This is more end-user UI feedback. If there's a better forum to submit this, I'm happy to go there instead.

**Comment by codebytere** [comment]
@jono-hayward does this happen with Chrome itself?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
