### ISSUE TITLE
[Bug]: ReferenceError: crypto is not defined

### ISSUE THREAD

**Issue by ghost** [electron/electron#39358]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.4.0

### What operating system are you using?

macOS

### Operating System Version

MacOs Ventura 13.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

This code should return a value
```
ipcMain.handle('doCryptoStuff', (event, str) => {
    return crypto.createHash('sha256').update(str).digest('hex')
})
```

### Actual Behavior

Cant use `crypto` module in main process.
Error `ReferenceError: crypto is not defined`

### Additional Information

Bundler: Vite;
Lang: ts;

tsconfig:

```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "types": ["node"],
    "noImplicitThis": false,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue", "electron"],
  "references": [{ "path": "./tsconfig.node.json" }],
  "paths": {
    "@/*": ["./src/*"],
  },
}
```

Vite config

```
import { defineConfig } from 'vite'
import electron from 'vite-plugin-electron'
import renderer from 'vite-plugin-electron-renderer'
import vue from '@vitejs/plugin-vue'
import { fileURLToPath, URL } from "url";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    electron([
      {
        // Main-Process entry file of the Electron App.
        entry: 'electron/main.ts',
      },
      {
        entry: 'electron/preload.ts',
        onstart(options) {
          // Notify the Renderer-Process to reload the page when the Preload-Scripts build is complete, 
          // instead of restarting the entire Electron App.
          options.reload()
        },
      },
    ]),
    renderer(),
  ],
  resolve: {
    alias: [
      { find: '@', replacement: fileURLToPath(new URL('./src', import.meta.url)) }
    ]
  }
})

```

Window config
```
width: 980,
    icon: '../public/logo.png',
    webPreferences: {
      devTools: true,
      preload: path.join(__dirname, 'preload.js'),
      sandbox: false,
      webSecurity: false,
    },
    titleBarStyle: "default",
    movable: true
```

**Comment by NirajanPrasad** [comment]
Hey, we can use nullish coalescing operator, so whenever the 'crypto' not defined it get returned without any error

**Comment by somanos** [comment]
Hi all,
Just tumble upon the same issue after upgrading electron to the latest version. My app was working fine with 19.1.9. It stopped working from [20.0.0]
Please, check fiddle here. https://gist.github.com/9a464f832b88aa36b1428607b52729d0
Thanks
