### ISSUE TITLE
[Bug]: event object returned is empty for events such as window move, window resize, webcontents contextmenu etc...

### ISSUE THREAD

**Issue by Mons-Joseph** [electron/electron#39353]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura

### What arch are you using?

x64

### Last Known Working Electron version

24.6.0

### Expected Behavior

event object returned from events such as window move, window resize, webcontents contextmenu etc... are supposed to be an instance of event.

### Actual Behavior

event object returned is empty.

**Comment by codebytere** [comment]
This is intended behavior as of: https://github.com/electron/electron/pull/37099. If
