### ISSUE TITLE
[Bug]: Notifications with `toastXml` don't show on Windows 10 or 11

### ISSUE THREAD

**Issue by wrgoto** [electron/electron#39367]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

13.2.2

### Expected Behavior

Notifications using the `toastXml` property should show up correctly on Windows 10 or 11.

### Actual Behavior

The notifications do not show up and do not trigger a `failed` event.

### Testcase Gist URL

https://gist.github.com/wrgoto/c312a2cce946483bd92b3d0fa5ea2b3a

### Additional Information

Notifications just using `title` work correctly on Windows.
The notification using `toastXml` doesn't invoke a `failed` event, but does invoke the `show` event.
App user model ID is correctly set.

**Comment by wrgoto** [comment]
@codebytere Here's the gist created from Electron Fiddle: https://gist.github.com/wrgoto/c312a2cce946483bd92b3d0fa5ea2b3a

**Comment by mlaurencin** [comment]
@wrgoto The gist is not working for me on either Windows 10 or 11 with your given last known working version. Can you confirm whether or not your notification using `toastXml` appears when using 13.2.2?

**Comment by wrgoto** [comment]
Hi @mlaurencin! I just realized that the old version of Electron is running in a project built with Electron Builder not Electron Forge. I'm sorry as that's probably not very helpful. The project is running Node v14.17.5, electron v13.2.2, electron-builder v22.11.7.

**Comment by mlaurencin** [comment]
@wrgoto Can you produce your working condition using the gist and v13.2.2 in [Electron Fiddle](https://www.electronjs.org/fiddle)? If you can confirm a version that it was last working using this tool, that will be helpful as everyone can be on the same page when testing.

**Comment by wrgoto** [comment]
After more probing, it turns out that the notifications with `toastXml` don't work in a development environment, but they do work on a production environment. Would be great to add this to the documentation or something.

**Comment by mlaurencin** [comment]
Given that it is not in the documentation, I am going to look into this a bit more and try to figure out the cause. In the case that this cannot be fixed, the documentation should be modified to reflect this.

**Comment by wrgoto** [comment]
Thank you @mlaurencin!
