### ISSUE TITLE
[Bug]: removeBrowserView() crashes if view.webContents.close() is called beforehand.

### ISSUE THREAD

**Issue by Bill77** [electron/electron#39377]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.0

### What operating system are you using?

macOS

### Operating System Version

macOs Ventura 13.4.1 (c)

### What arch are you using?

x64

### Last Known Working Electron version

25.2.0

### Expected Behavior

We are using `browserViews` in a `browserWindow`, when closing our view, we need the `window.close` event to be sent, so I'm using the `view.webContents.close()` to close the window (it's hosting a citrix receiver html5 page) before I call `mainWindow.removeBrowserView()`.

Expected behavior is the `browserView` closes, and the `getBrowserViews` list is updated by `removeBrowserView()` call.

### Actual Behavior

The `removeBrowserView` call crashes the electron app. In the fiddle it crashes with `Electron exited with signal SIGSEGV.`

### Testcase Gist URL

https://gist.github.com/Bill77/1db0aefcd338b612f66e09a9f7372d82

### Additional Information

Attached is a Electron Fiddle with the **add** and **close** buttons. To reproduce, add the view and then close it, which works in `25.2.0` but does not in `25.3.0+`. Looking at the change log, it seem it's related to [this PR](https://github.com/electron/electron/pull/38996). 

I did try to just use the `webContents.close()` and skip calling `removeBrowserView()` but the view list does not get updated, and we get a list of views that have null `webContents`. Which I suspect is causing the issue in `removeBrowerView()` to crash. 

We either need a solution where within `removeBrowserView` it calls the `webContents.close` or the logic in `removeBrowserView` needs null checks on the `webContent` references. Sorry, that's my guess based on not looking at the Electron code directly! 🤷‍♂️

**Comment by rjvelasquezm** [comment]
Sorry to hijack the thread but could someone please look at this issue (https://github.com/electron/electron/issues/34211)

Its been open for years in different forms without as much as an acknowledgement
