### ISSUE TITLE
refactor: fix or intentionally annotate dangling pointers on Linux

### ISSUE THREAD

**Issue by VerteDinde** [electron/electron#39370]
Refs https://github.com/electron/electron/pull/39304

Refs https://chromium.googlesource.com/chromium/src/+/main/docs/dangling_ptr.md

Chrome recently added a dangling pointer detector, enabled by default with `enable_dangling_raw_ptr_checks = true`. Electron currently has several raw_ptrs that are triggering the dangling pointer detector on Linux.

This pointers should either be 1) refactored to avoid dangling or 2) the `DisableDanglingPtrDetection` option can be used to annotate “intentional-and-safe” dangling pointers.

More details can be found at https://chromium.googlesource.com/chromium/src/+/main/docs/dangling_ptr_guide.md .

**Comment by ckerr** [comment]
I've done fixes for some of these raw_ptr issues and would like to work on more of this.

In the short term what would y'all think about a PR that re-enables it by default and marks all the issues as `DisableDanglingPtrDetection`? That would effectively give us a TODO list and let us see at-a-glance what's not yet done.

**Comment by ckerr** [comment]
> In the short term what would y'all think about a PR that re-enables it by default and marks all the issues as `DisableDanglingPtrDetection`? That would effectively give us a TODO list and let us see at-a-glance what's not yet done.

This doesn't appear to be enough. I made local changes to mark all of our own raw_ptrs as Untriaged using rg+xargs+perl mark, but am still getting memory leak detection issues in our tests. I'm going to try & figure out why that's happening.
