### ISSUE TITLE
[Feature Request]: Whether Electron supports Kirin 990 arm cpus

### ISSUE THREAD

**Issue by gugol-boor** [electron/electron#39384]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Whether Electron supports Kirin 990 arm cpus

### Proposed Solution

supports Kirin 990 arm cpus

### Alternatives Considered

supports Kirin 990 arm cpus

**Comment by wugaosheng123** [comment]
@gugol-boor Yes,It's supportive.

**Comment by codebytere** [comment]
Yes, we do.
