### ISSUE TITLE
[Bug]: open camera in ubuntu 22  not working normaly 

### ISSUE THREAD

**Issue by likui888** [electron/electron#39382]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.1

### What operating system are you using?

Ubuntu

### Operating System Version

Linux pc-laptop 5.19.0-50-generic #50-Ubuntu SMP PREEMPT DYNAMIC Mon Jul 10 18:2 4:29 UTC 2023 X86_64 ×86_64 ×86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

Camera can work in normal color

### Actual Behavior

```
<template>
  <div>
    <video id="videoElement" autoplay/>
    <select
        v-model="params.deviceID"
        v-if="params.videoDevices.length >= 1"
        style="border: 1px black solid"
    >
      <option
          v-for="i in params.videoDevices"
          :key="i.deviceId"
          :value="i.deviceId"
          :selected="(params.deviceID = i.deviceId)"
      >
        {{ i.label }}
      </option>
    </select>
    <button @click="startCam">Start</button>
    <button @click="stopCam">stop</button>

  </div>
</template>

<script setup lang="ts">
import {onMounted, reactive} from "vue";

const params = reactive<{ videoDevices: Array<any>, deviceID: string | null, videoElement: HTMLVideoElement | null }>({
  videoDevices: [],
  deviceID: null,
  videoElement: null
})
onMounted(async () => {
  params.videoElement = (document.getElementById("videoElement") as HTMLVideoElement);
  let devices = await navigator.mediaDevices.enumerateDevices();
  for (let index = 0; index < devices.length; index++) {
    const device = devices[index];
    if (device.kind == "videoinput") {
      params.videoDevices.push({
        deviceId: device.deviceId,
        kind: device.kind,
        label: device.label,
      });
    }
  }
});

const stopCam = () => {
  var tracks = params.videoElement?.srcObject?.getTracks();
  for (var i = 0; i < tracks.length; i++) {
    var track = tracks[i];
    track.stop();
  }
  params.videoElement = null;
};
const startCam = () => {
  var constraints = {
    deviceId: {exact: params.deviceID},
  };
  navigator.mediaDevices
      .getUserMedia({video: constraints} as MediaStreamConstraints)
      .then((stream) => {
        if (params.videoElement) {
          params.videoElement.srcObject = stream;
        }
      });
};
</script>

<style>
select {
  appearance: none;

  background-color: transparent;
  border: none;
  padding: 0 1em 0 0;
  margin: 0;
  width: 100%;
  font-family: inherit;
  font-size: inherit;
  cursor: inherit;
  line-height: inherit;
}
</style>
```
 When I open my camera in ubuntu 22.4.01 LTS in the electron project, the camera color is green, and then ```navigator.mediaDevices.getUserMedia``` the call on the browser is also green.

<img width="1370" alt="image" src="https://github.com/electron/electron/assets/131512161/a7131999-facf-4881-9972-640fe9dd6313">

### Additional Information

1. If I first call this ```navigator.mediaDevices.getUserMedia``` on the browser side to open the camera, it will work normally, and then it will work normally when I open it in the electron project.
2. The above two phenomena are triggered after the camera switches usb.
3. my  electron project use camera is all right on windows or macos.

**Comment by IrfanKhan66** [comment]
I tried running your project but got runtime error, I think you should try changing the camera saturation settings using Javascript. Im not familiar with typescript and electron so cant help much

**Comment by likui888** [comment]
@IrfanKhan66 Yes, I also think it is a camera parameter setting problem, but what I don't understand is why calling the same api under the browser can work normally and my guess is that the browser successfully did what the camera parameter initialization did not succeed in the client.

**Comment by IrfanKhan66** [comment]
@likui888 There may be any pre settings for saved camera or something like that, keep an eye out for updates in the package it will surely be resolved if its a global bug

**Comment by IrfanKhan66** [comment]
@likui888 Hey buddy, I just did some research on your camera name and model that you provided, turns out that it's a security camera company and many old security cameras have green shade, may be it's a manufacturing software defect causing it to flicker between green and colorful view. I may be wrong so pardon me, but it's good if you check it 😊
