### ISSUE TITLE
[Feature Request]: Notifications actions on Mac should NOT activate the app

### ISSUE THREAD

**Issue by ivanggq** [electron/electron#39396]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Notification actions on Mac activate the app. This can be undesired depending on the application.
Ideally, it should be up to the application to decide if it wants to activate the app when the notification action is selected.

### Proposed Solution

Selecting the notification action should not activate the app.

### Alternatives Considered

No alternative - if an app does not want to be activated when a notification action is selected, it has no alternative.

### Additional Information

For comparison, implementation on Windows allows devs to not activate the app when the notification (or a button in it) is clicked.

**Comment by codebytere** [comment]
This is a native macOS behavior - it's unfortunately not something exposed to macOS developers via API. We're eventually going to upgrade to use UNNotifications, which may confer that ability, but until then this isn't something we can fix.
