### ISSUE TITLE
[Bug]: Intercepting file request produces an infinite loop

### ISSUE THREAD

**Issue by quinton-ashley** [electron/electron#39402]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.4.0

### What operating system are you using?

macOS

### Operating System Version

13.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

unknown

### Expected Behavior

I found this outdated gist that claims to do exactly what I want to do:
https://gist.github.com/hamstu/b1f88ea486508111668df8d39e2d0ca1

```js
const path = require('path');
const { protocol } = require('electron');

/**
 * This method is used to intercept file requests from the Electron
 * BrowserWindow ensure we load the correct files.
 *
 * This allows us to intercept requests from the JavaScript that ask for
 * resources with absolute paths, e.g., `/web_modules/react.js`. Without
 * the intercept, Electron would attempt (and fail) to load from the
 * system's root directory.
 *
 * The reason our JS code is making absolute requests is becuse it is bundled
 * with Snowpack, which assumes we'll be serving our site from a server,
 * where using absolute `/` paths would resolve normally.
 */
module.exports = function interceptFileRequests(assetDirectory) {
  if (!assetDirectory) {
    throw new Error('`interceptRequests` must be passed a directory argument.');
  }
  return protocol.interceptFileProtocol('file', (request, callback) => {
    // Remove `file://` from URL/path - decode as well since it may be urlencoded
    const url = decodeURIComponent(request.url.substr(7));
    // Get just the relative path
    const rootDir = path.resolve(__dirname, '..');
    const requestedUrlRelative = url.replace(rootDir, '');
    // Now insert the path to the asset directory
    const newPath = path.join(rootDir, assetDirectory, requestedUrlRelative);
    callback({ path: newPath });
  });
};
```

I tried implementing this same idea in the current version of Electron:

```js
protocol.handle('file', (req) => {
  const url = req.url;
  log(url);
  
  // convert the url to use the app directory as the root
  // file path instead of the system root
  
  return net.fetch(url);
});
```

How can I implement an intercept of root file paths in html and convert them to use the app directory as the root instead of the system root?

### Actual Behavior

It infinite loops. I don't understand how to implement an intercept now since the old method is deprecated. I'd really appreciate help with this, thank you!

**Comment by XieJiSS** [comment]
https://www.electronjs.org/docs/latest/api/net#netfetchinput-init

You need to provide `bypassCustomProtocolHandlers` to `net.fetch`

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
