### ISSUE TITLE
Reloading from performance tab of devtools creates an intermediate about:blank load

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#39427]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0-beta.12

### What operating system are you using?

macOS

### Operating System Version

14.0

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.3.18

### Expected Behavior

Page reloads without `about:blank` being loaded.

### Actual Behavior

The change appeared first with Electron 23, we should understand what changed in the devtools navigation that causes this new intermediate page to load.

### Testcase Gist URL

https://gist.github.com/deepak1556/4b6316d5a30f3abcb353ecc7f835aae3

### Additional Information

Steps to repro:

- Launch the above gist
- In devtools, navigate to `performance` tab and click `reload`
- Check console output and see `about:blank` gets printed from preload before the page url gets printed

**Comment by codebytere** [comment]
@deepak1556 tracked to https://github.com/electron/electron/commit/1c1a0cdead3407ac02aceae7f006c153e47602f3

**Comment by deepak1556** [comment]
Thanks for narrowing it down, I wonder if we should document this somewhere ?
