### ISSUE TITLE
Disable webview when node integration is off

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#3943]
Currently webview tag is available even when node integration is off, this can introduce security problems since webview can be used to execute arbitrary code.

Refs #3921.

**Comment by xywz** [comment]
Will the preload script still be able to create webviews?

**Comment by seanchas116** [comment]
> Will the preload script still be able to create webviews?

How about adding new `WebView` modules or something to create webview element without `<webview>` tag? It can be used in preload scripts and safe from injection.

Example: 

```js
const WebView = require("electron").WebView;
const webView = new WebView({src: ...});
document.body.appendChild(webView.element);
```

**Comment by wearhere** [comment]
Rather than disable the webview tag altogether, why not just prevent Node integration from being re-enabled on the webview? #4026

**Comment by xywz** [comment]
This is a separate issue that should remain open. Arbitrary webpages can still use webviews to bypass CSP, get access to the entire `webContents` API, and do many other potentially damaging actions.

**Comment by bridiver** [comment]
after our release this week I'm going to resolve a few backwards compatibility issues and put together PRs for the electron work we've done. We sandboxed and completely removed node from renderer processes that have node integration disabled. Webviews are not available, but preload script capability is available through extension content scripts (including ipcRenderer)

**Comment by laramies** [comment]
@bridiver I am interested in the sandboxing and removing node from renderer processes work. Any chance to do the PRs?

**Comment by laramies** [comment]
Any progress on fixing this issue? Or porting the changes from Brave?  Thanks in advance

**Comment by bridiver** [comment]
We have everything working, but our nodeless renderer processes use content scripts as a replacement for the preload script. It's fairly simple to remove node and add the sandbox, but without extensions you'll be left without preload script support. I've had some discussions with @zcbenz about extensions and he feels pretty strongly that they should not be included in Electron, so I'm not sure if our changes will be helpful.

**Comment by xywz** [comment]
@zcbenz can there be an option to enable webviews? This breaking change weakens the security of apps that use webviews with preload scripts because now all scripts in the page will have access to node instead of just one.

**Comment by zcbenz** [comment]
@xywz I'm not sure I get what you meant, the change was to disable webview itself, instead of node integration in webview.

**Comment by xywz** [comment]
@zcbenz currently node integration is disabled for the window and webviews are used. The code that needs access to node is in a preload script and all other code runs in the standard browser context. Updating will break this setup unless there is an option to enable webviews.
