### ISSUE TITLE
[Bug]: `BrowserWindow`'s top offset (`y` value) is set to 25 when trying to set it explicitly below 25 on macOS

### ISSUE THREAD

**Issue by anmolshres98** [electron/electron#39445]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.4.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

BrowserWindow's top offset from screen (`y` value) should be respected when explicitly specified to be below 25

### Actual Behavior

BrowserWindow's top offset from screen (`y` value) is always set to 25 when explicitly specified to be below 25 

### Testcase Gist URL

https://gist.github.com/7bd49c0498a46da629adf1327fc03160

### Additional Information

Both when creating a new `BrowserWindow` like so:
```js
const win = new BrowserWindow({
    x: 15,
    y: 16,
  })
console.log(win.getBounds()); // logs { x: 15, y: 25, width: 800, height: 600 }
```
or when  setting the `BrowserWindow` position after creation like so:
```js
const win = new BrowserWindow();
win.setPosition(15,16);
console.log(win.getBounds()); // logs { x: 15, y: 25, width: 800, height: 600 }
```

When the y-value above is set to anything below 25, it always goes to 25 and never below. However, setting the y-value above 25 works correctly and returns position that was specified.

This issue doesn't seem to exist on Windows and Linux and seems to isolated to MacOS.

I did find a possibly related issue filed [here](https://github.com/electron/electron/issues/39257)

**Comment by codebytere** [comment]
@anmolshres98 this is unfortunately not a bug - it's a system limitation. I've opened a PR to make that more explicit.
