### ISSUE TITLE
[Bug]: Menu item visible property not working

### ISSUE THREAD

**Issue by sunknudsen** [electron/electron#39460]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.5.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When [visible](https://www.electronjs.org/docs/latest/api/menu-item#menuitemvisible) is set to `false`, menu item is not visible.

### Actual Behavior

Menu item remains visible when [visible](https://www.electronjs.org/docs/latest/api/menu-item#menuitemvisible) is set to `false`.

### Testcase Gist URL

https://gist.github.com/sunknudsen/6e508c6c28003b78cea482438761ca5c

**Comment by albu77** [comment]
Perhaps could be better to add Os specific tag, I can't test on last versions but it's working on Windows7 with Electron 22.2.0
