### ISSUE TITLE
[Bug]: Deprecated API warning in Sonoma devices

### ISSUE THREAD

**Issue by theYoungDetective** [electron/electron#39463]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma Developer Beta 14.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

On using desktopCapturer from electron in macOS devices can be used to capture audio and video details from the desktop.

### Actual Behavior

In Sonoma macOS devices, on using desktopCapturer an alert message is shown, similar to that attached, warning that the application utilises a deprecated API.
<img width="372" alt="66703e88-9c55-4f07-8633-e0ab83213a28" src="https://github.com/electron/electron/assets/112820088/c1d9a9fe-85f7-48a6-a725-c2a2b180bc85">
The alert is just shown once and does not affect the normal performance of the app.

### Additional Information

To reinitiate the alert after the initial run, execute the following command macOS commandLine.
`defaults delete com.apple.replayd`

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
