### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chenyaohuan** [electron/electron#39467]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.6

### What operating system are you using?

macOS

### Operating System Version

MacOs Ventura 13.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.3.6

### Expected Behavior

  const notify = new Notification({
      body: "textBody1",
      title: "textTitle1",
    });
    notify.show();

    notify.on("show", () => {
      console.log("succeed");
    });

In my project, there is a logic similar to displaying a notification. This is a simple demo. The expected behavior of this function when executed in the MacOS system is that I see the notification popping up from the top right corner, and then the callback function is executed.

### Actual Behavior

Most of the time, the execution result meets expectations. However, sometimes the notification is displayed after a delay, even though I have already executed the callback function.

**Comment by chenyaohuan** [comment]
const notify = new Notification({
  body: "textBody1",
  title: "textTitle1",
  });Ï
notify.show();

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
