### ISSUE TITLE
[Bug]: `BrowserWindow.reload` renders white page and fires `app.render-process-gone`

### ISSUE THREAD

**Issue by jijojosephk** [electron/electron#39476]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.2

### What operating system are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Last Known Working Electron version

24.6.3

### Expected Behavior

`BrowserWindow.reload` should refresh the current page.

### Actual Behavior

`BrowserWindow.reload` crashes.

1. Renders a blank white page.
2. Fires `app.render-process-gone` event.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
