### ISSUE TITLE
[Bug]: with wayland & gnome, maximizing a window to the side results in margin around the window

### ISSUE THREAD

**Issue by cypresslf** [electron/electron#39470]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.1 and 22.3.18

### What operating system are you using?

Other Linux

### Operating System Version

Linux jig 6.1.41-1-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Jul 25 09:17:30 UTC 2023 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

The demo app maximizes to the right or the left to take up half the screen, and the window extends to the top, bottom, and side all the way.

### Actual Behavior

The demo app maximizes to the right or the left to take up half the screen, but the borders of the app don't extend all the way to the side and bottom of the screen. The title-bar extends all the way to the top of the screen, but the title bar is double the height it should be, and it seems to only respond to clicks in the bottom half

![image](https://github.com/electron/electron/assets/133676745/d79fef6a-6db4-45c5-a0e9-036a9e6871da)

#### Reproduction steps

- Install Manjaro with GNOME Shell 44.3, use gnome with wayland

```
pamac install electron
electron --ozone-platform=wayland --enable-features=WaylandWindowDecorations
```

- Drag demo app to side of screen to maximize to the right or the left

[Screencast from 2023-08-11 12-25-01.webm](https://github.com/electron/electron/assets/133676745/7e2cec76-df18-4de1-aea3-06c095d8ab68)

Note: maximizing full screen works as intended, but this may be related to https://github.com/electron/electron/issues/33161

**Comment by kaimast** [comment]
I see this bug too on my setup (Gnome and Arch Linux).

**Comment by Jazzinghen** [comment]
I see this bug on my setup as well (GNOME, Arch Linux, Wayland and NVIDIA)

**Comment by aiddya** [comment]
I've bisected this bug to [v22.0.0-beta.3...v22.0.0-beta.4](https://github.com/electron/electron/compare/v22.0.0-beta.3...v22.0.0-beta.4). The regression was caused by an update to Chromium 108.0.5359.29, specifically while updating the CSD code after [this CL](https://chromium-review.googlesource.com/c/chromium/src/+/3970920).
