### ISSUE TITLE
[Bug]: Title bar controls are outdated in Windows 11

### ISSUE THREAD

**Issue by flachware** [electron/electron#39471]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home Version 22H2

### What arch are you using?

x64

### Expected Behavior

The title bar controls should look like in native Windows 11 applications:

![Screenshot 2023-08-11 at 17 09 04](https://github.com/electron/electron/assets/419747/d1793cb4-a652-4694-8c30-560242275879)

### Actual Behavior

The title bar controls look like in Windows 10:

![Screenshot 2023-08-11 at 17 08 37](https://github.com/electron/electron/assets/419747/52bd0d77-36cc-4aac-ad2f-d075f532aa79)

### Additional Information

To my knowledge the icons for the Windows 10 title bar controls are part of the Segoe MDL2 Assets icon font, whereas the icons for the Windows 11 title bar controls are part of the Segoe Fluent icon font. The _Maximize_ icon has rounded corners now and more notable the _Close_ icon has a thicker stroke width which is more in line with the other icons.

**Comment by kelvin-14** [comment]
![image](https://github.com/electron/electron/assets/129178453/d7aeff1c-4530-4a71-9eab-4b728453fee9)

maybe this can help in some way. I'm on windows 11 and it looks like this. I'm also on the same electron version and windows version as you

**Comment by flachware** [comment]
Thanks for the screenshot – this looks good to me. It makes me wonder if the issue above only occurs in virtualized environments (the screenshots above are from a guest Windows 11 in VirtualBox).

**Comment by codebytere** [comment]
Looks like an upstream issue - see related https://bugs.chromium.org/p/chromium/issues/detail?id=1444871. I recommend filing an issue at https://bugs.chromium.org - we will inherit the fix when it's addressed by Chromium.
