### ISSUE TITLE
Webview's object node doesn't fill the webview if the webview is a flexbox

### ISSUE THREAD

**Issue by clavin** [electron/electron#3948]
A webview's object node doesn't get stretched vertically when the webview is part of a flexbox.

![Webview is full size](http://puu.sh/mcxMj/b4f2e3c0d3.png)
![Object node isn't full size of webview](http://puu.sh/mcxX4/e220828802.png)
(the images show a different bug also: the webview is obviously being cut off at the bottom. this fixes itself upon resizing the window.)

I was able to fix this by adding `display: flex` to the webview and disabling the `height: 100%;` of the object node, except that was using dev tools. I can't find a way to style the object node (neither JS nor CSS seem to be ways to get to it) so this isn't a real solution.

That given, the only solution I can think of is being able to access the object node via JS. Even if it is annoying to have to set styling w/ JS, it'd still be a fair workaround.

I'm using v0.36.1 on WIndows 7, for any help that could (somehow) be.

It's not hard to replicate, and nothing else affects it outside of the html document and styling, so here's a document (just setup the quick start app using this for the page) that showcases this.

``` html
<!DOCTYPE html>
<html>
    <head>
        <style>
        html, body {
            margin: 0;
            width: 100%;
            height: 100%;
        }
        .container {
            height: 100%;
            display: flex;
            flex-flow: column;
        }
        webview {
            flex: 1 1 auto;
        }
        </style>
    </head>
    <body>
        <div class='container'>
            <webview src='https://www.google.com/'></webview>
        </div>
    </body>
</html>

```

**Comment by zcbenz** [comment]
This is a known upstream bug: https://code.google.com/p/chromium/issues/detail?id=499766.

**Comment by krokofant** [comment]
Any workaround?

**Comment by zcbenz** [comment]
Closed with #4665.

**Comment by zcbenz** [comment]
Reopening this for 3.0

**Comment by Galkon** [comment]
ETA on a real fix for this? Too many open issues, been waiting for years.
