### ISSUE TITLE
[Bug]: nodeIntegration=true flag in webPreferences causes screen to blank out

### ISSUE THREAD

**Issue by andrewheadricke** [electron/electron#39515]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 23.04

### What arch are you using?

x64

### Last Known Working Electron version

25.5.0

### Expected Behavior

Expect app to load normally and remain visible.

### Actual Behavior

When using the `nodeIntegration: true` in webPreferences the renderer goes blank within 1-2 seconds of app loading. It had been working fine in previous releases.

If I set `nodeIntegration: false` the app disappearing stops happening.

**Comment by dtcooper** [comment]
I'm observing this too. With verbose logging you get,

```
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
```

Running on Arch with GNOME 44 with Wayland and the following settings:

```js
const win = new BrowserWindow({
  x: mainWindowState.x,
  y: mainWindowState.y,
  width: mainWindowState.width,
  height: mainWindowState.height,
  useContentSize: true,
  minWidth,
  minHeight,
  icon: iconPath,
  webPreferences: {
    devTools: isDev,
    contextIsolation: false,
    nodeIntegration: true,
    webSecurity: false,
    spellcheck: false,
    backgroundThrottling: false
  }
})
```

**Comment by gitZokki** [comment]
+1

**Comment by andrewheadricke** [comment]
Simple app that triggers renderer crash

https://gist.github.com/andrewheadricke/3042d86b4ace52cf9718607797e7b536

**Comment by gitZokki** [comment]
> Simple app that triggers renderer crash
> 
> https://gist.github.com/andrewheadricke/3042d86b4ace52cf9718607797e7b536

Idk what is the problem on your side, but I had the error with sandbox=false
I also have nodeIntegration=true, but I need this to 100%

**Comment by andrewheadricke** [comment]
Yeah, it seems a combination of nodeIntegration and sandbox change the behaviour of this bug slightly, but that very simple gist i posted above definitely crashes the renderer everytime.

**Comment by andrewheadricke** [comment]
So I checked both Wayland and X, the issue remains under both display systems.

I also noticed that if you start the app and don't move the mouse or press any keys, it will stay rendered UNTIL you move the mouse or cause the window to refresh/redraw in anyway, then the renderer crashes.

The console also outputs `ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!` but that may be a red herring.

**Comment by dtcooper** [comment]
Tried this on Debian bookworm with GNOME/Wayland and can't reproduce. However, on up-to-date Arch it happens. Odd.

**Comment by andrewheadricke** [comment]
I've had issues in previous upgrades where not clearing the cache was causing weird crashes, but i've done a `rm -rf ~/.config/Electron/` and that hasn't fixed it.

**Comment by Jelmerro** [comment]
Exactly the same issue here on the latest Fedora on one of my devices, doesn't crash, just a blank screen a few seconds after starting any Electron app with version 26, only happens on one of my devices though.

**Comment by frosth555** [comment]
I'm not sure if it's really useful:
`electron-nightly@27.0.0-nightly.20230630` is the last affected build
`electron-nightly@27.0.0-nightly.20230703` and newer work ok.

**Comment by Jelmerro** [comment]
That would mean that upgrading from Chromium 116 to 117 fixed the issue, given that there are only 3 commits between those 2 nightly versions of v27, two of which are most likely unrelated, see https://github.com/electron/electron/compare/v27.0.0-nightly.20230630...v27.0.0-nightly.20230703
And that that v26 nightly is the last Electron release to feature 115, as the next v26 nightly jumps to Chromium 116, see:
https://github.com/electron/electron/compare/v26.0.0-nightly.20230525...v26.0.0-nightly.20230529

**Comment by igorflavio** [comment]
The same issue occurs to me. I'm using Ubuntu 22.04, Electron 26.0.0 and Node 19.9.0.

**Comment by vraravam** [comment]
> In other words, all the affected Electron versions use Chromium 116.

Can you please release a 26 beta so that we can verify that the fix works for all combinations of OSes and windowing systems?

**Comment by WortgeschichteDigital** [comment]
I can confirm this bug.

Only happens with electron@26-x-y. With electron@25-x-y and electron@alpha (which right now is 27.0.0-alpha.5) everything works fine. I could only test this on a Linux system.

For test purposes, I created a minimal Electron app: https://github.com/WortgeschichteDigital/MinimalElectronApp. "Hello world!" should disapear after about two seconds. Removing `nodeIntegration: true` on line 21 of `main.js` does the trick. After that the app won't crash anymore.

Crash dump: [Crashpad.zip](https://github.com/electron/electron/files/12514989/Crashpad.zip)

BTW, the DevTool window prints the message "DevTools was disconnected from the page" (see image). You have to be fast enough to open them before the app crashes, though. Hope that helps!

![DevTools](https://github.com/electron/electron/assets/55915607/b92ce7e9-e2f7-4936-9125-bea785871403)

**Comment by thecodrr** [comment]
I can also confirm this bug. It is happening in only some Linux systems. Windows & macOS seem to be fine.

**Comment by DaveyL2013** [comment]
> I can also confirm this bug. It is happening in only some Linux systems. Windows & macOS seem to be fine.

This has just started happening to me on my Win11 pc in ArmCord (their issues page marked the problem as upstream so now I'm here)

**Comment by tr1p0p** [comment]
> Nevermind this turned out to have similar visual results but the issue is on ArmCord's side just pretend this isn't here

Can we know how you deduce that ?

**Comment by monisankarsard** [comment]
Iiiiiij sjisjss

**Comment by monisankarsard** [comment]
![Uploading IMG-20230908-WA0000.jpg…]()

**Comment by dtcooper** [comment]
Confirmed still broken on latest Arch Linux with GNOME + Wayland on 26.2.1. Last working stable version is 25.8.0.

**Comment by ZIMkaRU** [comment]
I can confirm this issue
with electron `27.0.0-beta.2` I don't see this bug, but would like to have a fix for a stable version

**Comment by Kilian** [comment]
Getting the same reports from some Linux users (various Ubuntu versions, various graphics cards). I can't replicate it on my own Ubuntu machine, neither in X11 or Wayland.

**Comment by Kilian** [comment]
I think https://github.com/electron/electron/issues/39775 might be the same bug.

**Comment by jtbandes** [comment]
Cross-posting from #39775 since I think these may be the same issue:

I am also able to reproduce the same crash on:
- Ubuntu 22.04.3
- ASUSTeK COMPUTER INC. Zephyrus S15 GX502LXS_GX502LXS
- NV164 / Mesa Intel® UHD Graphics (CML GT2)
- Intel® Core™ i7-10875H CPU @ 2.30GHz × 16
- Node v18.18.0
- Electron 26.2.2

It happens when I use the stock electron-fiddle app, **with the sole addition of `sandbox: false`**. The renderer crashes a few seconds after launching. Stack trace below (I am not sure how to get proper symbols, let me know if anyone knows how):

```
$ ELECTRON_ENABLE_STACK_DUMPING=1 npx electron@26.2.2 .
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Received signal 11 <unknown> 306d80001048
#0 0x561731a6f263 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x57d7262)
#1 0x561731a7feec (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x57e7eeb)
#2 0x7ff3c1642520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#3 0x561731b6d7ac (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x58d57ab)
#4 0x561731b67284 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x58cf283)
#5 0x561731a82668 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x57ea667)
#6 0x561730e3a399 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x4ba2398)
#7 0x56173079560a (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x44fd609)
#8 0x56173077b5e9 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x44e35e8)
#9 0x561731a125ed (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x577a5ec)
#10 0x561731a2eb54 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x5796b53)
#11 0x561731a2e369 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x5796368)
#12 0x561731a2f095 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x5797094)
#13 0x5617319cea98 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x5736a97)
#14 0x561731a2f400 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x57973ff)
#15 0x5617319f2dc1 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x575adc0)
#16 0x561735512d54 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x927ad53)
#17 0x56172e8e580b (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x264d80a)
#18 0x56172e8e6cb8 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x264ecb7)
#19 0x56172e8e4527 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x264c526)
#20 0x56172e8e4636 (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x264c635)
#21 0x56172e61821d (/home/foxglove/.npm/_npx/2d0e8517694be14b/node_modules/electron/dist/electron+0x238021c)
#22 0x7ff3c1629d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
  r8: 0000000010600002  r9: 80cc4a0020170000 r10: 0000000000000000 r11: 0000000000000001
 r12: 0000000000000000 r13: 00005617361e7008 r14: 0000000000000000 r15: 00005617362990b0
  di: 0000306d80008020  si: 0000000010600002  bp: 00007ffc078713a0  bx: 00005617362990b0
  dx: 0000306d80001040  ax: 0000306d80001040  cx: 0000000000000000  sp: 00007ffc07871390
  ip: 0000561731b68953 efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000027
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000306d80001048
[end of stack trace]
[30075:0922/160328.374513:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
```


When I use version 27.0.0-beta.1 or newer, it no longer crashes. (I do still see the same `GetVSyncParametersIfAvailable` error, so I guess that's unrelated.)

Let me know if there's any additional information that would be useful for debugging.

**Comment by deepak1556** [comment]
I am merging this issue to https://github.com/electron/electron/issues/39775, please subscribe to the other issue and if possible provide the results of https://github.com/electron/electron/issues/39775#issuecomment-1737152374. Thanks!

**Comment by sabaimran** [comment]
Can confirm I also have this exact same issue. Here are my machine specs:
```
Ubuntu 22.04.2 LTS
11th Gen Intel® Core™ i7-1185G7 @ 3.00GHz × 8
Mesa Intel® Xe Graphics (TGL GT2)

Electron 26.1.0
```
