### ISSUE TITLE
[Bug]: Event 'did-fail-load' cannot catch net::ERR_NETWORK_CHANGED

### ISSUE THREAD

**Issue by Luokun2016** [electron/electron#39522]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.2

### What operating system are you using?

Ubuntu

### Operating System Version

5.4.0-150-generic #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

Event 'did-fail-load' cannot catch net::ERR_NETWORK_CHANGED error

### Actual Behavior

**webRequest** can catch **net::ERR_NETWORK_CHANGED**
```
session.defaultSession.webRequest.onErrorOccurred((details) =>{
        console.error(details)
        log.error(details)
        if (details.error ==='net::ERR_NETWORK_CHANGED') {
            log.info("reload file")
            win.loadFile('startup/startup.html')
        }
    })
```

Event 'did-fail-load' cannot catch net::ERR_NETWORK_CHANGED
```
win.webContents.on('did-fail-load', (event, code, desc, url, isMainFrame) =>{
        console.log('did-fail-load',  code,  desc,  url)
        log.warn(code)  // An operation was aborted (due to user action).  NET_ERROR(ABORTED, -3)
        log.warn(desc)
        log.info("isMainFrame:" + isMainFrame)
        if (isMainFrame && code != -3){
            win.loadFile('startup/startup.html')
        }
    })
```

### Testcase Gist URL

(https://gist.github.com/Luokun2016/7bc577e6decfbf678c585c392e807591)

**Comment by Luokun2016** [comment]
**test case** https://gist.github.com/Luokun2016/7bc577e6decfbf678c585c392e807591

Only **webRequest** catch **net::ERR_CONNECTION_REFUSED** and **net::ERR_NETWORK_CHANGED**
![image](https://github.com/electron/electron/assets/24650960/2e20ac78-ed51-4433-9672-ac4dd8cfb4a0)

**Comment by Luokun2016** [comment]
Use the following command to generate "net::ERR_NETWORK_CHANGED" error.
```
sudo ifconfig lo down
sudo ifconfig lo up
```

![image](https://github.com/electron/electron/assets/24650960/973eff74-ae91-4509-8c65-3f97aea4910b)

**Comment by MafistoPL** [comment]
The 'did-fail-load' event is designed to capture network-related errors specifically with the loadURL API, not through fetch requests. The issue described in the gist as net::ERR_NETWORK_CHANGED not being caught by 'did-fail-load' is a misunderstanding of the event's intended usage, rather than a bug. I have conducted tests in Electron versions 19 and 25, and can confirm that the net::ERR_NETWORK_CHANGED error is captured when using the loadURL API in both versions. However, this error is not caught by 'did-fail-load' when the error originates from fetch API requests in either version.
