### ISSUE TITLE
[Bug]: Update variables on dialog window

### ISSUE THREAD

**Issue by Dango090799** [electron/electron#39534]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows Server 2022 Version 21H2

### What arch are you using?

x64

### Expected Behavior

Variables changed through setInterval/setTimeout should update on dialog screen when changing in the background.

### Actual Behavior

Variables currently do not update text on the dialog screen when updating through setInterval/setTimeout in the background.

### Additional Information

Hi All,

I'm not sure if this is a bug or if this is meant to be the actual behaviour for this feature.

My use case is that I want a dialog to update a dialog message dependant on a timer which is running through a setInterval in the background. When doing this, it appears that the text just stays static regardless of the timer ticking in the background.

Please do let me know if I'm being an idiot for expecting this to happen haha!

**Comment by VIRAT9358** [comment]
@Dango090799 Can you please tell in exactly which file should I look to solve the issue.

**Comment by Dango090799** [comment]
Hi @VIRAT9358, I'm not sure which file it will be in as I haven't looked deep into the electron code. But I'll try give a bit more context and maybe it might help.

The message I'm expecting to be updatable is in the dialog options object which is inputted into the 'onMessageBox(browserWindow, options)' function. I'm instatiating the dialog in the main.js file. Please see below the code, and hopefully this will explain better than I can.

```
let startTime = new Date();
let breakLength = "";
let interval = setInterval(() => {
    const length = new Date().getTime() - startTime.getTime();
    const seconds = Math.floor(length / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);
    if (hours >= 1)
        breakLength = `(${hours.toString().padStart(2, '0')}:${(minutes % 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')})`;
   else 
        breakLength = `(${(minutes % 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')})`;
}, 1000);

const dialogOpts = {
    type: 'info',
    buttons: ['End Break'],
    title: "Break",
    message: `On Break: ${breakcode}. Start Time: ${startTime.toLocaleTimeString('en-Gb')}. Duration: ${breakLength}`
}

dialog.showMessageBox(win, dialogOpts).then((returnValue) => {
    if (returnValue.response === 0) {
        win.webContents.send("returnFromBreak");
            clearInterval(interval);
    }
});
```

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
