### ISSUE TITLE
[Bug]: Issues with all packages on Raspberry Pi OS with Electron due to incorrect Node.js version

### ISSUE THREAD

**Issue by JhonyWA** [electron/electron#39579]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Raspberry Pi OS 

### What arch are you using?

x64

### Expected Behavior

I'm encountering problems while trying to install various packages on Raspberry Pi OS using the npm install command. Some examples of these packages are onoff, express, and rpi-softspi. All packages are generating the same error, as exemplified below:

The package was compiled in a different version of Node.js using NODE_MODULE_VERSION 115. This version of Node.js requires NODE_MODULE_VERSION 116. Please try recompiling or reinstalling the module (e.g., using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)

### Actual Behavior

was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 116. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)

**Comment by danthedev123** [comment]
You can try using `nvm` to switch Node.js versions. 115 is a previous version (20.5.1) so try 
```
➜  ~ nvm install 20.5.1
Downloading and installing node v20.5.1...
Downloading https://nodejs.org/dist/v20.5.1/node-v20.5.1-linux-x64.tar.xz...
########################################################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v20.5.1 (npm v9.8.0)
Creating default alias: default -> 20.5.1 (-> v20.5.1)
➜  ~ nvm use 20.5.1
Now using node v20.5.1 (npm v9.8.0)
➜  ~ 
```
Install NVM: https://github.com/nvm-sh/nvm/blob/master/README.md#installing-and-updating

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

As to this issue in particular - the error you're seeing occurs for certain modules, and isn't an error in Electron itself. The most straightforward way to handle this is to use the [`electron-rebuild`](https://github.com/electron/rebuild) module.

**Comment by JhonyWA** [comment]
> You can try using `nvm` to switch Node.js versions. 115 is a previous version (20.5.1) so try
> 
> ```
> ➜  ~ nvm install 20.5.1
> Downloading and installing node v20.5.1...
> Downloading https://nodejs.org/dist/v20.5.1/node-v20.5.1-linux-x64.tar.xz...
> ########################################################################################################## 100.0%
> Computing checksum with sha256sum
> Checksums matched!
> Now using node v20.5.1 (npm v9.8.0)
> Creating default alias: default -> 20.5.1 (-> v20.5.1)
> ➜  ~ nvm use 20.5.1
> Now using node v20.5.1 (npm v9.8.0)
> ➜  ~ 
> ```
> 
> Install NVM: https://github.com/nvm-sh/nvm/blob/master/README.md#installing-and-updating

thanks for trying to help, apparently Electron uses a different version than the one I'm applying with nvm.

I tried to do what you instructed, download the version of my noje.js , I was downloading and testing until version 10.0.0, but even so the same error appeared.

**Comment by JhonyWA** [comment]
> > You can try using `nvm` to switch Node.js versions. 115 is a previous version (20.5.1) so try
> > ```
> > ➜  ~ nvm install 20.5.1
> > Downloading and installing node v20.5.1...
> > Downloading https://nodejs.org/dist/v20.5.1/node-v20.5.1-linux-x64.tar.xz...
> > ########################################################################################################## 100.0%
> > Computing checksum with sha256sum
> > Checksums matched!
> > Now using node v20.5.1 (npm v9.8.0)
> > Creating default alias: default -> 20.5.1 (-> v20.5.1)
> > ➜  ~ nvm use 20.5.1
> > Now using node v20.5.1 (npm v9.8.0)
> > ➜  ~ 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Install NVM: https://github.com/nvm-sh/nvm/blob/master/README.md#installing-and-updating
> 
> thanks for trying to help, apparently Electron uses a different version than the one I'm applying with nvm.
> 
> I tried to do what you instructed, download the version of my noje.js , I was downloading and testing until version 10.0.0, but even so the same error appeared.

the only way I found to follow my path, was to build two applications that communicate through localhost, because apparently electron, locks in any module that I install
