### ISSUE TITLE
[Bug]: leave html fullscreen will result in incorrect theme mode

### ISSUE THREAD

**Issue by pengx17** [electron/electron#39576]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0

### What operating system are you using?

macOS

### Operating System Version

14.0 Beta (23A5312d)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

24.0

### Expected Behavior

Assume app is in light mode. 
When html element calls `requestFullscreen` and then exit fullscreen mode, app will be in light mode.

### Actual Behavior

Assume app is in light mode. When html element calls `requestFullscreen` and then exit fullscreen mode, the app's background will be in dark mode.

### Additional Information

To reproduce: https://github.com/pengx17/electron-playground

https://github.com/electron/electron/assets/584378/9825e700-227f-4089-8f3c-bfcc3dc5034c

**Comment by flyyuan** [comment]
I think it is a Chromium bug because I tried Chrome which has the same bug.

**Comment by codebytere** [comment]
@pengx17 This appears after some testing to be a Chromium bug, in agreement with @flyyuan. This is something you should report upstream to Chromium via [crbug](https://crbug.com/) along with a repro in Chrome itself - once they address it we'll pick up the fix via our upgrades process.
