### ISSUE TITLE
[Bug]: minimizing child window minimizes parent window on Mac (and sometimes makes the child restore automatically)

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#39578]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I expect that minimizing a child window doesn't minimize the parent window (like on Windows)

### Actual Behavior

Minimizing a child window also minimizes the parent window for some reason.

(in my actual app [don't have minimal example yet], what happens is that the child window is restored for some reason)

### Testcase Gist URL

https://gist.github.com/pushkin-/e66fb76a5c418b878f83dd4b064c67e4

### Additional Information

possibly related to [this issue](https://github.com/electron/electron/issues/39504)

**Comment by codebytere** [comment]
@pushkin- this is native macOS window behavior, unfortunately. it's inherently different than the analogous behavior on Windows. This behavior has been consistent on macOS since earliest versions of Electron.
