### ISSUE TITLE
Right-click on the taskbar to close all Windows, the electron process does not close

### ISSUE THREAD

**Issue by wangwenwen130** [electron/electron#39588]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.18

### What operating system are you using?

Windows

### Operating System Version

11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz

### What arch are you using?

x64

### Last Known Working Electron version

22.3.18

### Expected Behavior

Right-click on the taskbar to close all Windows, All processes should be shut down

### Actual Behavior

Process not closed 
![image](https://github.com/electron/electron/assets/48354328/0811643f-7d98-4358-9beb-404518b63b8b)
![image](https://github.com/electron/electron/assets/48354328/062e2a88-1715-4808-bf3e-f7088d652b17)

**Comment by wangwenwen130** [comment]
Please repair as soon as possible

**Comment by anoop-mobi** [comment]
Facing Same Issue

**Comment by anoop-mobi** [comment]
Facing Same issue 

while using that 

app.setLoginItemSettings({
    openAtLogin: true,
    openAsHidden: false, 
  });
  app.on('ready', () => {
    setTimeout(createWindow, 400)
    // tray = new Tray('src/assets/icons/icon-72x72.png')
    tray = new Tray(path.join(__dirname, '../dist/assets/icons/icon-72x72.png'));

    const contextMenu = Menu.buildFromTemplate([
      
      { label: 'Add New Products' },
      
      { type: 'separator' },
      { label: 'Close Application',
        click: () => {
          win?.close()         
        },
      },
    ])
    tray.on('click', ()=>{
     win?.isVisible()?win.hide():win?.show();
    })
    tray.setToolTip('My Application')
    tray.setContextMenu(contextMenu)
  });

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by jiang-zhong-xi** [comment]
I have the same issue and I have fixed. 

**here is the reason**: when starting app.exe, a BrowserWindow is creating and showing, and b BrowserWindow is loading and hiding, after loading b BrowserWindow, a BrowserWindow  is **hided**, and b BrowserWindow is showing, so when close from windows taskbar, the hided a BrowserWindow is not destroy, so the 'window-all-closed' event is not emited.

**the resoltion**: executing a.destroy while not a.close will fix that.
