### ISSUE TITLE
[Bug]: ninja -C out/Testing electron =>  ../../device/fido/mac/icloud_keychain_sys.h:37:7: error: unknown type name 'ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationState'

### ISSUE THREAD

**Issue by flyyuan** [electron/electron#39602]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

main

### What operating system are you using?

macOS

### Operating System Version

macOS 12.6.6 Monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

run ```ninja -C out/Testing electron``` to build successfully

### Actual Behavior

$ ninja -C out/Testing electron

[29132/48342] OBJCXX obj/device/fido/fido/icloud_keychain.o
FAILED: obj/device/fido/fido/icloud_keychain.o 
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/device/fido/fido/icloud_keychain.o.d -DIS_DEVICE_FIDO_IMPL -DDCHECK_ALWAYS_ON=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ENABLE_ASSERTIONS=1 -DCR_XCODE_VERSION=1420 -DCR_CLANG_REVISION=\"llvmorg-18-init-1174-g2532b68f-1\" -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=84fb809dd6dae36d556dc0bb702c6cc2ce9d4b80 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DENABLE_IPC_FUZZER -DSK_ENABLE_SKSL -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_DISABLE_LEGACY_SKSURFACE_METHODS -DSK_DISABLE_LEGACY_GRAPHITE_IMAGE_FACTORIES -DSK_DISABLE_LEGACY_GRAPHITE_IMAGE_METHODS -DSK_DISABLE_LEGACY_SKSURFACE_FACTORIES -DSK_DISABLE_LEGACY_SKSURFACE_FLUSH -DSK_DISABLE_LEGACY_SKSURFACE_AS_IMAGE -DSK_DISABLE_LEGACY_SKSURFACE_DISPLAYLIST -DSK_DISABLE_LEGACY_IMAGE_SUBSET_METHODS -DSK_DISABLE_LEGACY_IMAGE_COLORSPACE_METHODS -DSK_DISABLE_LEGACY_IMAGE_RELEASE_PROCS -DSK_DISABLE_LEGACY_GL_BACKEND_SURFACE -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_JPEG -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_HAS_WUFFS_LIBRARY -DSK_DISABLE_LEGACY_CANVAS_FLUSH -DSK_LEGACY_GPU_GETTERS_CONST -DSK_BUILD_FOR_MAC -DSK_GANESH -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DSK_GL -DSK_GRAPHITE -DSK_DAWN -DSK_METAL -DWEBP_EXTERN=extern -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DGOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE=0 -DHAVE_PTHREAD -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_MAC -DABSL_ALLOCATOR_NOTHROW=1 -DLOGGING_INSIDE_WEBRTC -I../.. -Igen -I../../buildtools/third_party/libc++ -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../net/third_party/quiche/overrides -I../../net/third_party/quiche/src/quiche/common/platform/default -I../../net/third_party/quiche/src -I../../third_party/skia -Igen/third_party/skia -I../../third_party/wuffs/src/release/c -Igen/third_party/dawn/include -I../../third_party/dawn/include -I../../third_party/libwebp/src/src -I../../third_party/libyuv/include -I../../third_party/jsoncpp/source/include -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/ipcz/include -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -Igen/net/third_party/quiche/src -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc  -Wall -Werror -Wextra -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wno-deprecated-this-capture -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing -fstack-protector -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -fcomplete-member-pointers -arch arm64 -fno-global-isel -mno-outline -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fno-omit-frame-pointer -gdwarf-4 -g1 -gdwarf-aranges -isysroot ../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacos-version-min=10.15 -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ref-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-stack-allocated -Xclang -plugin-arg-find-bad-constructs -Xclang check-raw-ptr-fields -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=um/winnt.h -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -DPROTOBUF_ALLOW_DEPRECATED=1 -Wimplicit-retain-self -Wobjc-missing-property-synthesis -std=c++20 -Wno-trigraphs -fobjc-call-cxx-cdtors -fno-exceptions -fno-rtti -nostdinc++ -isystem../../third_party/libc++/src/include -isystem../../third_party/libc++abi/src/include -fobjc-arc -fno-objc-arc-exceptions -fvisibility-inlines-hidden -c ../../device/fido/mac/icloud_keychain.mm -o obj/device/fido/fido/icloud_keychain.o
In file included from ../../device/fido/mac/icloud_keychain.mm:32:
../../device/fido/mac/icloud_keychain_sys.h:37:7: error: unknown type name 'ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationState'
   37 |       ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationState;
      |       ^
../../device/fido/mac/icloud_keychain_sys.h:39:7: error: use of undeclared identifier 'ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined'
   39 |       ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined;
      |       ^
../../device/fido/mac/icloud_keychain_sys.h:41:7: error: use of undeclared identifier 'ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateDenied'
   41 |       ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateDenied;
      |       ^
../../device/fido/mac/icloud_keychain_sys.h:43:7: error: use of undeclared identifier 'ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateAuthorized'
   43 |       ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateAuthorized;
      |       ^
../../device/fido/mac/icloud_keychain_sys.h:47:11: error: unknown type name 'AuthState'
   47 |   virtual AuthState GetAuthState() = 0;
      |           ^
../../device/fido/mac/icloud_keychain_sys.h:57:19: error: unknown type name 'ASAuthorizationWebBrowserPlatformPublicKeyCredential'
   57 |           NSArray<ASAuthorizationWebBrowserPlatformPublicKeyCredential*>*)) = 0;
      |                   ^
../../device/fido/mac/icloud_keychain.mm:152:17: error: unknown type name 'ASAuthorizationWebBrowserPlatformPublicKeyCredential'
  152 |         NSArray<ASAuthorizationWebBrowserPlatformPublicKeyCredential*>*
      |                 ^
../../device/fido/mac/icloud_keychain.mm:158:40: error: property 'credentialID' not found on object of type 'const __strong id'
  158 |                          ToVector(cred.credentialID),
      |                                        ^
../../device/fido/mac/icloud_keychain.mm:160:44: error: property 'userHandle' not found on object of type 'const __strong id'
  160 |                              ToVector(cred.userHandle), cred.name.UTF8String,
      |                                            ^
../../device/fido/mac/icloud_keychain.mm:160:62: error: property 'name' not found on object of type 'const __strong id'
  160 |                              ToVector(cred.userHandle), cred.name.UTF8String,
      |                                                              ^
10 errors generated.
[29135/48342] OBJCXX obj/device/fido/fido/icloud_keychain_sys.o
FAILED: obj/device/fido/fido/icloud_keychain_sys.o 
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/device/fido/fido/icloud_keychain_sys.o.d -DIS_DEVICE_FIDO_IMPL -DDCHECK_ALWAYS_ON=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ENABLE_ASSERTIONS=1 -DCR_XCODE_VERSION=1420 -DCR_CLANG_REVISION=\"llvmorg-18-init-1174-g2532b68f-1\" -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=84fb809dd6dae36d556dc0bb702c6cc2ce9d4b80 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DENABLE_IPC_FUZZER -DSK_ENABLE_SKSL -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_DISABLE_LEGACY_SKSURFACE_METHODS -DSK_DISABLE_LEGACY_GRAPHITE_IMAGE_FACTORIES -DSK_DISABLE_LEGACY_GRAPHITE_IMAGE_METHODS -DSK_DISABLE_LEGACY_SKSURFACE_FACTORIES -DSK_DISABLE_LEGACY_SKSURFACE_FLUSH -DSK_DISABLE_LEGACY_SKSURFACE_AS_IMAGE -DSK_DISABLE_LEGACY_SKSURFACE_DISPLAYLIST -DSK_DISABLE_LEGACY_IMAGE_SUBSET_METHODS -DSK_DISABLE_LEGACY_IMAGE_COLORSPACE_METHODS -DSK_DISABLE_LEGACY_IMAGE_RELEASE_PROCS -DSK_DISABLE_LEGACY_GL_BACKEND_SURFACE -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_JPEG -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_HAS_WUFFS_LIBRARY -DSK_DISABLE_LEGACY_CANVAS_FLUSH -DSK_LEGACY_GPU_GETTERS_CONST -DSK_BUILD_FOR_MAC -DSK_GANESH -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DSK_GL -DSK_GRAPHITE -DSK_DAWN -DSK_METAL -DWEBP_EXTERN=extern -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DGOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE=0 -DHAVE_PTHREAD -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_MAC -DABSL_ALLOCATOR_NOTHROW=1 -DLOGGING_INSIDE_WEBRTC -I../.. -Igen -I../../buildtools/third_party/libc++ -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../net/third_party/quiche/overrides -I../../net/third_party/quiche/src/quiche/common/platform/default -I../../net/third_party/quiche/src -I../../third_party/skia -Igen/third_party/skia -I../../third_party/wuffs/src/release/c -Igen/third_party/dawn/include -I../../third_party/dawn/include -I../../third_party/libwebp/src/src -I../../third_party/libyuv/include -I../../third_party/jsoncpp/source/include -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/ipcz/include -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -Igen/net/third_party/quiche/src -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc  -Wall -Werror -Wextra -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wno-deprecated-this-capture -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing -fstack-protector -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -fcomplete-member-pointers -arch arm64 -fno-global-isel -mno-outline -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fno-omit-frame-pointer -gdwarf-4 -g1 -gdwarf-aranges -isysroot ../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacos-version-min=10.15 -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ref-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-stack-allocated -Xclang -plugin-arg-find-bad-constructs -Xclang check-raw-ptr-fields -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-exclude-path=um/winnt.h -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -DPROTOBUF_ALLOW_DEPRECATED=1 -Wimplicit-retain-self -Wobjc-missing-property-synthesis -std=c++20 -Wno-trigraphs -fobjc-call-cxx-cdtors -fno-exceptions -fno-rtti -nostdinc++ -isystem../../third_party/libc++/src/include -isystem../../third_party/libc++abi/src/include -fobjc-arc -fno-objc-arc-exceptions -fvisibility-inlines-hidden -c ../../device/fido/mac/icloud_keychain_sys.mm -o obj/device/fido/fido/icloud_keychain_sys.o
In file included from ../../device/fido/mac/icloud_keychain_sys.mm:5:
../../device/fido/mac/icloud_keychain_sys.h:37:7: error: unknown type name 'ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationState'
   37 |       ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationState;
      |       ^
../../device/fido/mac/icloud_keychain_sys.h:39:7: error: use of undeclared identifier 'ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined'
   39 |       ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined;
      |       ^
../../device/fido/mac/icloud_keychain_sys.h:41:7: error: use of undeclared identifier 'ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateDenied'
   41 |       ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateDenied;
      |       ^
../../device/fido/mac/icloud_keychain_sys.h:43:7: error: use of undeclared identifier 'ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateAuthorized'
   43 |       ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateAuthorized;
      |       ^
../../device/fido/mac/icloud_keychain_sys.h:47:11: error: unknown type name 'AuthState'
   47 |   virtual AuthState GetAuthState() = 0;
      |           ^
../../device/fido/mac/icloud_keychain_sys.h:57:19: error: unknown type name 'ASAuthorizationWebBrowserPlatformPublicKeyCredential'
   57 |           NSArray<ASAuthorizationWebBrowserPlatformPublicKeyCredential*>*)) = 0;
      |                   ^
../../device/fido/mac/icloud_keychain_sys.mm:180:1: error: unknown type name 'ASAuthorizationWebBrowserPublicKeyCredentialManager'; did you mean 'ASAuthorizationSecurityKeyPublicKeyCredentialProvider'?
  180 | ASAuthorizationWebBrowserPublicKeyCredentialManager* GetManager() {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | ASAuthorizationSecurityKeyPublicKeyCredentialProvider
../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/AuthenticationServices.framework/Headers/ASAuthorizationSecurityKeyPublicKeyCredentialProvider.h:12:12: note: 'ASAuthorizationSecurityKeyPublicKeyCredentialProvider' declared here
   12 | @interface ASAuthorizationSecurityKeyPublicKeyCredentialProvider : NSObject <ASAuthorizationProvider>
      |            ^
../../device/fido/mac/icloud_keychain_sys.mm:181:12: error: use of undeclared identifier 'ASAuthorizationWebBrowserPublicKeyCredentialManager'
  181 |   return [[ASAuthorizationWebBrowserPublicKeyCredentialManager alloc] init];
      |            ^
../../device/fido/mac/icloud_keychain_sys.mm:226:3: error: unknown type name 'AuthState'
  226 |   AuthState GetAuthState() override {
      |   ^
../../device/fido/mac/icloud_keychain_sys.mm:243:19: error: unknown type name 'ASAuthorizationWebBrowserPlatformPublicKeyCredential'
  243 |           NSArray<ASAuthorizationWebBrowserPlatformPublicKeyCredential*>*))
      |                   ^
../../device/fido/mac/icloud_keychain_sys.mm:227:25: error: property 'authorizationStateForPlatformCredentials' not found on object of type 'ASAuthorizationSecurityKeyPublicKeyCredentialProvider *'
  227 |     return GetManager().authorizationStateForPlatformCredentials;
      |                         ^
../../device/fido/mac/icloud_keychain_sys.mm:234:55: error: type-id cannot have a name
  234 |         requestAuthorizationForPublicKeyCredentials:^(AuthState state) {
      |                                                       ^~~~~~~~~
../../device/fido/mac/icloud_keychain_sys.mm:234:65: error: expected ')'
  234 |         requestAuthorizationForPublicKeyCredentials:^(AuthState state) {
      |                                                                 ^
../../device/fido/mac/icloud_keychain_sys.mm:234:54: note: to match this '('
  234 |         requestAuthorizationForPublicKeyCredentials:^(AuthState state) {
      |                                                      ^
../../device/fido/mac/icloud_keychain_sys.mm:234:53: error: a type specifier is required for all declarations
  234 |         requestAuthorizationForPublicKeyCredentials:^(AuthState state) {
      |                                                     ^
../../device/fido/mac/icloud_keychain_sys.mm:234:9: error: no visible @interface for 'ASAuthorizationSecurityKeyPublicKeyCredentialProvider' declares the selector 'requestAuthorizationForPublicKeyCredentials:'
  233 |     [GetManager()
      |      ~~~~~~~~~~~~
  234 |         requestAuthorizationForPublicKeyCredentials:^(AuthState state) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../device/fido/mac/icloud_keychain_sys.mm:246:9: error: no visible @interface for 'ASAuthorizationSecurityKeyPublicKeyCredentialProvider' declares the selector 'platformCredentialsForRelyingParty:completionHandler:'
  245 |     [GetManager()
      |      ~~~~~~~~~~~~
  246 |         platformCredentialsForRelyingParty:base::SysUTF8ToNSString(rp_id)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  247 |                          completionHandler:handler];
      |                          ~~~~~~~~~~~~~~~~~
16 errors generated.
[29141/48342] CXX obj/device/fido/fido/enclave_http_client.o
ninja: build stopped: subcommand failed.

### Testcase Gist URL

https://gist.github.com/flyyuan/41c16de121510835aad9bc7ebbe2c22c

**Comment by jkleinsc** [comment]
@flyyuan you will need a newer version of Xcode to build from main.  Electron build tools will automatically download the correct Xcode version or you can look at the SDK version here https://chromium.googlesource.com/chromium/src/+/refs/heads/main/build/config/mac/mac_sdk.gni#50 and manually download the correct Xcode version.

**Comment by jkleinsc** [comment]
@flyyuan check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by flyyuan** [comment]
I updated to  the newest version of macOS ,  and it  works

**Comment by sesm** [comment]
@flyyuan what version of XCode you ended up using? I'm having the same issue when building `chromium`, tried with XCode 14.2 and 15 and it didn't help.
