### ISSUE TITLE
[Bug]: Invalid PlatformChannel receive right when closing better-sqlite3 database (Possible regression)

### ISSUE THREAD

**Issue by linonetwo** [electron/electron#39600]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

~~26.0.0~~ [electron v26.0.0-beta.2](https://github.com/electron/electron/releases/tag/v26.0.0-beta.2)

### What operating system are you using?

macOS

### Operating System Version

13.5 (22G74)

### What arch are you using?

x64

### Last Known Working Electron version

~~25.6.0~~ [electron v26.0.0-beta.1](https://github.com/electron/electron/releases/tag/v26.0.0-beta.1)

### Expected Behavior

No crush or error.

### Actual Behavior

Immeadately crush with this output in the console:

> [69364:0822/003532.451897:ERROR:child_thread_impl.cc(235)] Invalid PlatformChannel receive right

### Testcase Gist URL

https://gist.github.com/linonetwo/aa3d3ad829a3497af6bc1e269c2a613e

I bysect in fiddle to make sure bug happen between electron [v26.0.0-beta.1](https://github.com/electron/electron/releases/tag/v26.0.0-beta.1) ~ [v26.0.0-beta.2](https://github.com/electron/electron/releases/tag/v26.0.0-beta.2)

### Additional Information

Electron fiddle seem to have problem installing better-sqlite3 https://github.com/electron/fiddle/issues/1444

So in the gist I use 

```js
nativeBinding: '/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
```

You may need to install `better-sqlite3` somewhere and get the file path like this, and modify this line, sorry!

Otherwise it will error:

```sh
(node:69993) UnhandledPromiseRejectionWarning: Error: The module '/private/var/folders/t3/0jyr287x3rd2m0b6ml8w4f2c0000gn/T/electron-fiddle-65967-ge4Iih4ZET7a/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 116. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by codebytere** [comment]
We can probably safely say it's caused by https://github.com/electron/electron/pull/38826 then. I'll see what i can do.

**Comment by Ridhwan889** [comment]
I like girl

**Comment by ZIMkaRU** [comment]
Hi @linonetwo
no specific solution here
If I'm not mistaken, there was a problem with running the driver on version v26
at that time I downgraded the version to v25 and everything works, now we use v27 and everything is fine too
we had to skip version 26
as for me, it can be closed
