### ISSUE TITLE
[Bug]: setVisibleOnAllWorkspaces correct behavior on macOS M1 chip

### ISSUE THREAD

**Issue by ashwin-mittal** [electron/electron#39601]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

- **Objective:** I want to use the setVisibleOnAllWorkspaces function with skipTransformProcessType set to false.
- **Expected Behavior:** I want my application to be visible on all workspaces, including fullscreen, but still visible in the dock.
- **Solution Attempt:** I changed the activation policy to 'regular' explicitly.

### Actual Behavior

- **New Issue:** When using an input of type date, it is not working in fullscreen mode, even though the window is visible over fullscreen.

### Testcase Gist URL

https://gist.github.com/ashwin-mittal/a328a3e6d989d70090636a112296cce3

**Comment by codebytere** [comment]
@ashwin-mittal I cannot repro this with the provided Fiddle. I tested running it, then trying to set the date before entering fullscreen. This worked as expected. After entering fullscreen, I was again able to change the date successfully. I'm running macOS Ventura on Apple M1 Max.

**Comment by ashwin-mittal** [comment]
> @ashwin-mittal I cannot repro this with the provided Fiddle. I tested running it, then trying to set the date before entering fullscreen. This worked as expected. After entering fullscreen, I was again able to change the date successfully. I'm running macOS Ventura on Apple M1 Max.

Actually, the issue is when I try to set a date while the window is floating over the fullscreen window of some other app, for example, Notes.

**Comment by ashwin-mittal** [comment]
@codebytere Actually, the issue is when I try to set a date while the window is floating over the fullscreen window of some other app, for example, Notes.

**Comment by codebytere** [comment]
@ashwin-mittal I still could not reproduce it in that context.

**Comment by ashwin-mittal** [comment]
@codebytere I can able to reproduce it consistently. Not sure why it is working fine for you. Which macOS version are you using?
