### ISSUE TITLE
[Bug]: Child windows open fullscreen when parent is fullscreen even if fullscreenable is disabled on child; weird behavior when unfullscreening

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#39612]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

1. I expect that launching a child window from a full screen window doesn't also full screen the child window (maybe this is just Mac behavior though)
2. I expect that it doesn't get fullscreened if it's configured to be unfullscreenable, or at least that unfullscreening it works correctly.

### Actual Behavior

1. Child window that's marked as unfullscreenable will launch in fullscreen mode when the parent window is fullscreen

### Testcase Gist URL

https://gist.github.com/pushkin-/43e0b045140a1f779de7a74b55d89475

### Additional Information

1. full screen main window
2. open child window
3. (notice it is also fullscreened for some reason [does it inherit parent's configuration?], even though fullscreenable is false)
4. if you try to unfullscreen the child window, it attempts to do that, but then remains full screen, and now we can't get the titlebar back to close or anything.

[maybe related to this issue](https://github.com/electron/electron/issues/39504)

https://github.com/electron/electron/assets/6374473/81db2d8d-adb8-4363-8b46-022ed1834891

**Comment by pushkin-** [comment]
looks like the titlebar I'm unfullscreening actually belongs to the parent window not the child for some reason.

**Comment by pushkin-** [comment]
Actually, I'll need to come up with a better example. This issue goes away when I disable fullscreening in the setWindowOpenHandler, which is what I do in my app. In my app, it seems like calling `show()` on the child window triggers the `enter-full-screen` event for some reason, though I need to repro this in a minimal example.

**Comment by pcprince** [comment]
Could you provide an example of how you used `setWindowOpenHandler` to disable fullscreening? The handler code never seems to run for me.
