### ISSUE TITLE
[Bug]: webContents.sendInputEvent does not work with Space and Enter

### ISSUE THREAD

**Issue by tristanmercille** [electron/electron#39610]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.9

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Expected Behavior

webContents.sendInputEvent({ keyCode: "Space", type: "keyDown" });
webContents.sendInputEvent({ keyCode: "Space", type: "char" });
webContents.sendInputEvent({ keyCode: "Space", type: "keyUp" });

Displays "Spa" in my input field.
Same applies for "Enter", which displays "Ent".

Backspace and other simple letters work fine.

### Actual Behavior

"Space" and "Enter" keycodes input the first 3 letters instead of the actual key.

**Comment by tristanmercille** [comment]
Here's a link to the gist for reproduction: https://gist.github.com/tristanmercille/ec40d0ef8ce2da99da52a464b74f8d70

**Comment by wugaosheng123** [comment]
I want to work for this.

**Comment by wugaosheng123** [comment]
bump

**Comment by codebytere** [comment]
@tristanmercille i'm not seeing this when i use `mainWindow.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Enter' })`, though I can repro with the Space example. What Enter input event are you sending to see this?
