### ISSUE TITLE
[Bug]: Menus in Windows have much less padding in Electron 26

### ISSUE THREAD

**Issue by craxal** [electron/electron#39611]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

25.6.0

### Expected Behavior

Windows menus have a certain amount of padding:

![image](https://github.com/electron/electron/assets/3473026/79cf4e32-3ff7-456f-b941-d7406744dae7)

### Actual Behavior

Windows menus have much less padding:

![image](https://github.com/electron/electron/assets/3473026/a1af13f5-6f11-4b20-9d90-20504b6a2590)

### Testcase Gist URL

https://gist.github.com/81fd7969bb7e9ad5f4e22e05201a0603

**Comment by MarshallOfSound** [comment]
This appears to be an intentional upstream change, on Windows in Chrome I see the same behaviour.

**Comment by Tjs002** [comment]
@craxal can you assign this task to me if it exists?

**Comment by craxal** [comment]
@Tjs002 Do you mean if there's an existing Chromium issue? I don't see one, but I don't consider this a pressing issue. Just not sure if this was intentional or not.

**Comment by codebytere** [comment]
@craxal we inherit Chromium behavior around Windows menus - if it's happening in Chrome stable there that means it was an intentional change upstream. You're welcome of course to file a bug in https://crbug.com/ - but it's likely that they don't consider it a bug and as such we wouldn't either.
