### ISSUE TITLE
[Bug]: non-fullscreenable, non-resizable child windows get fullscreened when being shown if the parent window is fullscreened

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#39614]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I expect that if a child window that's configured to be non-fullscreenable is shown while the parent window is fullscreened, the child window won't get fullscreened.

### Actual Behavior

Child window opens fullscreened for some reason and the main window crashes when the child is closed.

### Testcase Gist URL

https://gist.github.com/pushkin-/3b4bcdb219eee85789e95f6d94ec8a92

### Additional Information

1. full screen main window
2. click open window
3. notice that child window is fullscreened even though it shouldn't be able to get fullscreen
4. closing the window makes the parent window go black

seems like the invocation of `BrowserWindow::show()` causes the `enter-full-screen` event to get emitted for some reason.

https://github.com/electron/electron/assets/6374473/f96e2680-4938-4de6-b562-94f80c46ecfb

**Comment by pushkin-** [comment]
In my actual app, this also seems to affect resizable windows though I haven't been able to repro in a minimal example yet.

**Comment by pushkin-** [comment]
If I unscreen the child window after it opens (Fn+F), and then close it, I don't get a crash. But also why does Fn+F do anything if fullscreenable is set to false. I can use that same hotkey to return it to fullscreen.

**Comment by kyle-w-20230331** [comment]
I got the same issue. 😭

**Comment by SuperShan0926** [comment]
> I got the same issue. 😭

so did I
