### ISSUE TITLE
[Bug]: Cannot run quickstart tutorial on Nixos results in "Unhandled 'error' event" 

### ISSUE THREAD

**Issue by ryardley** [electron/electron#39632]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

9.6.7

### What operating system are you using?

Other Linux

### Operating System Version

 NixOS 23.11pre514517.8353344d3236 (Tapir) x86_64

### What arch are you using?

x64

### Expected Behavior

1. Clear electron cache
```
rm -rf ~/.cache/electron
```

2. Create a new empty folder for the project

```
mkdir electron-test
```

3. Setup package.json like so:

```
{
  "name": "my-electron-app",
  "version": "1.0.0",
  "description": "Hello World!",
  "main": "main.js",
  "author": "Jane Doe",
  "license": "MIT"
}
```

4. Install electron

```
 npm install --save-dev electron
(##################) ⠼ reify:@types/node: http fetch GET 200 https://registry.npmjs.org/@typ

added 72 packages, and audited 73 packages in 28s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

5. Add scripts to package.json
```json
{
  "name": "my-electron-app",
  "version": "1.0.0",
  "description": "Hello World!",
  "main": "main.js",
  "author": "Jane Doe",
  "license": "MIT",
  "scripts": {
    "start": "electron ."
  },
  "devDependencies": {
    "electron": "^26.1.0"
  }
}
```

Setup main.js
```js
console.log("Hello");
```

6. Try run start

```
npm start
```

## Expect 

Expect an electron app to run without errors

### Actual Behavior

6. Try run start
```
❯ npm start

> my-electron-app@1.0.0 start
> electron .

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn /path/to/project/electron-test/node_modules/electron/dist/electron ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /path/to/project/electron-test/node_modules/electron/dist/electron',
  path: '/path/to/project/electron-test/node_modules/electron/dist/electron',
  spawnargs: [ '.' ]
}
```

Binary appears to have downloaded
```
❯ ls -la ~/.cache/electron/966ea66f0461372b810ef8cc7950fe560aca9f692bb8ed9c89d09afad9f168bd
total 95268
drwxr-xr-x 2 ry users     4096 Aug 24 09:48 .
drwxr-xr-x 3 ry users     4096 Aug 24 09:48 ..
-rw-r--r-- 1 ry users 97540502 Aug 24 09:48 electron-v26.1.0-linux-x64.zip
```

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by ryardley** [comment]
Sorry this is a bug. What question am I asking here?

**Comment by ryardley** [comment]
@codebytere sorry - a little confused here. This is a bug not a question. Is there another space for bug reports?

**Comment by novikov1337danil** [comment]
@ryardley I encountered exactly the same error. I also use NixOS. Have you found a solution to this problem?

**Comment by ryardley** [comment]
I found this situation pretty ridiculous so just use tauri instead as it solves all the problems electron would solve. https://tauri.app/

**Comment by Antiarchitect** [comment]
Faced the same issue. Trying to debug an app written with electron. Using NixOS + node2nix.

```
[2024-03-28T10:58:43.233Z] [electron-connect] [server] started electron process: undefined
[2024-03-28T10:58:43.233Z] [electron-connect] [server] server created and listening on 30080
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/andrey/PROJECTS/desktop/node_modules/electron/dist/electron ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/andrey/PROJECTS/desktop/node_modules/electron/dist/electron',
  path: '/home/andrey/PROJECTS/desktop/node_modules/electron/dist/electron',
  spawnargs: [ '-r process', 'dist/' ]
}
```
