### ISSUE TITLE
[Bug]: function app.getPath("userData") returns a wrong path in AppX package

### ISSUE THREAD

**Issue by mordom0404** [electron/electron#39636]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro Workstaion 22H2 

### What arch are you using?

x64

### Expected Behavior

When I run function app.getPath('userData') should give me the path of userdata which given by system, and this works fine on Windows exe package.
But on Windows AppX package, sometimes this path should be:
```
C:\Users\[username]\AppData\Local\Packages\[appid]\LocalCache\Roaming\[appname]
```
and sometimes it should be:
```
C:\Users\[username]\AppData\Roaming\[appname]
```

### Actual Behavior

the function gives me this all the time :

```
C:\Users\[username]\AppData\Roaming\[appname]
```

**Comment by mordom0404** [comment]
Here is some more details may help:
What I'm doing is, I put some third-party apps(such as ffmpeg.exe etc.) into my app resources and package them into my AppX package. 

Step 1:
Create an image by canvas and save it by using 
```
let maskPath = path.resolve(`${app.getPath('userData')}/mask.png`)
fs.writeFileSync(maskPath, dataBuffer)
```
It successfully saved the image.png in this folder
```
C:\Users\[username]\AppData\Local\Packages\[appid]\LocalCache\Roaming\[appname]
```
Here is something a little bit interesting: 
If you add console.log to show where the image is:
```
console.log(app.getPath('userData'))
```
you will get 
```
C:\Users\[username]\AppData\Roaming\[appname]
```
This is not where the image actually is.
But I'm guessing Electron or Windows is doing something to do the automatic conversion?


Step 2：
When I run some ffmpeg command I pass the image path to child_process.spawn(). 
```
child_process.spawn("ffmpeg.exe", [...,"C:\Users\[username]\AppData\Roaming\[appname]\mask.png",....], {
    cwd: somedir,
    shell:false
  });
```
But ffmpeg shows that he cannot read the image. Apparently I passed the wrong path to ffmpeg, but electron does not provide an effective way to get the real userData path.

**Comment by MarshallOfSound** [comment]
This isn't Electron rather it's how Windows operates with appx containerized apps.  I'd suggest reading https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes#file-system to figure out how this stuff works.

I'm not sure if there's a way to _correctly_ let ffmpeg read/write into that private location, it may just be a case of signing it correctly but this isn't an issue with Electron itself so not something we can help with

**Comment by hovancik** [comment]
I think it behaves rather weirdly:

    when you already have a regular installer / data in typical location, it uses that location
    when ever installed app from store only, it uses that other location
