### ISSUE TITLE
[Bug]: pageSize invalid

### ISSUE THREAD

**Issue by buWenXin** [electron/electron#39634]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.21

### What operating system are you using?

Windows

### Operating System Version

Windows 10专业版 1909

### What arch are you using?

x64

### Expected Behavior

` win.webContents.print({
      silent: false,
      printBackground: true,
      deviceName: "pdfFactory Pro",
      margins: {
         marginType: "none"
      },
      //attribute invalid!
      pageSize: {
         width: 50* 1000,
         height: 30* 1000
      },
   }
`
I hope the pageSize set can take effect and output the size I set during printing
And the content should not automatically rotate.

我希望设置的pageSize能够生效，打印的时候能输出我设置的尺寸；
并且内容不要自动旋转。

### Actual Behavior

`      //attribute invalid!
      pageSize: {
         width: 50* 1000,
         height: 30* 1000
},`

The custom size set by pageSize does not take effect, whether using a real printer or a virtual printer (pdfFactory Pro), the size set cannot take effect.
And the set content is 50mm wide and 30mm high, but the output content has been rotated, with 50mm high and 30mm wide output
My English is not good and I am using machine translation. I hope you can understand the problem I have described

pageSize设置的自定义尺寸不生效， 无论使用的真实打印机，还是虚拟打印机（pdfFactory Pro），设置的尺寸都是无法生效。
并且是设置的内容是 宽50mm，高30mm，但是输出的内容被旋转了，输出 高50mm，宽30mm
我的英文不好，使用的是机器翻译，希望你们可以看懂我描述的问题
![image](https://github.com/electron/electron/assets/69368870/c4d5db4b-3aca-4a50-b4df-f33f78e3d003)

### Testcase Gist URL

https://github.com/buWenXin/Electron-test16

**Comment by buWenXin** [comment]
我已经制作了测试用例：https://github.com/buWenXin/Electron-test16

**Comment by buWenXin** [comment]
是不是我的测试用例不够精简？

**Comment by buWenXin** [comment]
这是我使用 Electron Fiddle 制作的示例：https://gist.github.com/9e4d29cb91c41c260bf23aa1a072f431

**Comment by buWenXin** [comment]
@codebytere Can you help me check this issue?

**Comment by buWenXin** [comment]
Printing is a very important feature of the client, why is there no one to handle this issue

**Comment by codebytere** [comment]
Combining with https://github.com/electron/electron/issues/31705
