### ISSUE TITLE
[Bug]: run electron application with admin privileges on windows can't receive second-instance event

### ISSUE THREAD

**Issue by stefanJi** [electron/electron#39656]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

ia32

### Expected Behavior

Normal run, will receive second-instance event, then we can restore/show exist window.

https://github.com/electron-userland/electron-builder/assets/15273198/46112329-a833-473a-8184-6dd7a5c21803

### Actual Behavior

 When run with admin, can't receive second-instance event, so we can't show exist window.

https://github.com/electron-userland/electron-builder/assets/15273198/2a311272-71c5-452d-9bef-8e1589c9ffde

**Comment by MarshallOfSound** [comment]
Duplicate #35681
