### ISSUE TITLE
[Bug]: Frameless windows don't have drop shadow on Wayland

### ISSUE THREAD

**Issue by aiddya** [electron/electron#39664]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.1.0

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 38

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

Create a BrowserWindow with `frame` set to `false`. The window should have a drop shadow.

### Actual Behavior

The window has a drop shadow with `--ozone-platform=x11`, but none with  `--ozone-platform=wayland`.

### Additional Information

ClientFrameViewLinux needs to be updated to draw just shadows without a GTK frame and this case should be handled in `ElectronDesktopWindowTreeHostLinux::UpdateFrameHints()`.

**Comment by devsnd** [comment]
As a workaround I'm using the following `settings.json` entries in vscode
```
    "window.titleBarStyle": "native",
    "window.menuBarVisibility": "toggle",
    "window.customTitleBarVisibility": "never"
```

which hides the custom title bar and shows a system native one instead. Since this also draws the window decorations, I now also get proper window shadowing using electron in wayland (kwin).
