### ISSUE TITLE
[Bug]: record screen with Deprecated API warning display in Sonoma devices

### ISSUE THREAD

**Issue by chinaofmelon** [electron/electron#39669]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.7.0， 25.0.0+， 26.0.0+, 27.0.0.beta+

### What operating system are you using?

macOS

### Operating System Version

macOS 14.0 beta(23A5301h)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

N/A

### Expected Behavior

screen record success, and without any warning dialog.

### Actual Behavior

An alert message is shown when using desktopCapturer to capture screen in Sonoma macOS devices. The warning message like:

![image](https://github.com/electron/electron/assets/9248242/07dbccc7-709a-4a07-a588-6a1189999847)

The alert is just shown once and does not affect the normal performance of the app.

### Testcase Gist URL

https://gist.github.com/8fccd24ca5a38415873ac8b4a504ce0b

### Additional Information

To reinitiate the alert after the initial run, execute the following command macOS commandLine.

`defaults delete com.apple.replayd`

I did not reproduce this issue on macOS 14.0 beta with intel process by using electron fiddle

**Comment by VerteDinde** [comment]
@chinaofmelon Thanks for reporting this issue! Supporting Screen Capture Kit and MacOS 14 specifically is something we're currently working on. I'll leave your issue open until we can confirm that work has landed, but wanted to let you know it's on our radar. Thanks for reporting this and including a gist for repro, it's very helpful 🙇‍♀️

**Comment by codebytere** [comment]
Closed in https://chromium-review.googlesource.com/c/chromium/src/+/4892397
