### ISSUE TITLE
[Bug]: BrowserView webPreferences backgroundThrottling:false not work  in electron 22.3.22

### ISSUE THREAD

**Issue by 82318179** [electron/electron#39665]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v22.3.22

### What operating system are you using?

Windows

### Operating System Version

win11

### What arch are you using?

x64

### Last Known Working Electron version

26.1

### Expected Behavior

The official statement is that setting backgroundThrottling: false under webPreferences can ensure that when the Browserwindow is minimized, the document.visibilityState on the page is always' visible '. However, after I set it, when the window is minimized, the document.visibilityState is always hidden。

In order to be compatible with Win7, I used the latest version of version 22 and now found that version 26.1 can correctly output 'visible'. However, in the latest version of 22, hidden was output. In the Testcase Gist URL, because version 22 cannot be selected, version 23 was used for testing. Can the issue with version 22 be resolved?

`// Modules to control application life and create native browser window
const { app, BrowserWindow,BrowserView } = require('electron')
const path = require('path')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  })
  const view = new BrowserView({
    webPreferences:{
      backgroundThrottling:false
    }
  }
  )
  mainWindow.setBrowserView(view)
  view.setBounds({ x: 0, y: 0, width: 800, height: 500 })
  view.webContents.loadURL('https://www.baidu.com')
  // Open the DevTools.
  view.webContents.openDevTools();

  setTimeout(async ()=>{
    mainWindow.minimize();
  const doJS = `
    (function () {
      return document.visibilityState;
    }
    )()`;
    let res = await view.webContents.executeJavaScript(doJS);
    console.log('aaa'+res);
  },2000)
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
`

### Actual Behavior

In order to be compatible with Win7, I used the latest version of version 22 and now found that version 26.1 can correctly output 'visible'. However, in the latest version of 22, hidden was output. In the Testcase Gist URL, because version 22 cannot be selected, version 23 was used for testing. Can the issue with version 22 be resolved?

The official statement is that setting backgroundThrottling: false under webPreferences can ensure that when the Browserwindow is minimized, the document.visibilityState on the page is always' visible '. However, after I set it, when the window is minimized, the document.visibilityState is always hidden。
![image](https://github.com/electron/electron/assets/25976728/abd6eb45-9376-49d1-9f53-cc0ea833f7ae)

### Testcase Gist URL

https://gist.github.com/5577e603ad0cd3931f3224506e388020

**Comment by mhamzanadeem** [comment]
can I  work on it ?

**Comment by 82318179** [comment]
> v22.3.22

Please use version v22.3.22 for testing. In order to be compatible with Win7, I have to use the latest version of 22. I found that version 26.1 is correct, but version 22.3.22 is not.

**Comment by mhamzanadeem** [comment]
I am first time contributing to " electron " open source project .  Can you guide me how to install v22.3.22 for testing
