### ISSUE TITLE
[Bug]: require() between string variable and raw string for my module, the former fails  and the latter successes

### ISSUE THREAD

**Issue by LittleAlen** [electron/electron#39674]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.2.3

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The two methods are both supposed to work!

### Actual Behavior

 my code:
const k="./database"
const database =require(k)
result:
INFO  Launching Electron...
App threw an error during the load
Error: Cannot find module './database'
    at webpackEmptyContext (webpack:///./src/core_sync?:2:10)
    at eval (webpack:///./src/core/run.js?:5:65)
    at Object../src/core/run.js (/Users/Desktop/WebScanTool/origin/dist_electron/index.js:2750:1)
    at __webpack_require__ (/Users/Desktop/WebScanTool/origin/dist_electron/index.js:20:30)
    at eval (webpack:///./src/core/events.js?:6:62)
    at Module../src/core/events.js (/Users/Desktop/WebScanTool/origin/dist_electron/index.js:2738:1)
    at __webpack_require__ (/Users/Desktop/WebScanTool/origin/dist_electron/index.js:20:30)
    at eval (webpack:///./src/background.js?:7:73)
    at Module../src/background.js (/Users/Desktop/WebScanTool/origin/dist_electron/index.js:2668:1)
    at __webpack_require__ (/Users/Desktop/WebScanTool/origin/dist_electron/index.js:20:30)

my code:
const database =require("./database")
result: 
success

### Additional Information

I do it because I need to store a path that points to my module database so that the other modules can require it  for some function

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

If you’re still experiencing this issue in Electron 22.x.y, or 24.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by LittleAlen** [comment]
hi！ The same issue happens in electron@^24.0.0 and 22.0.0

**Comment by mlaurencin** [comment]
Great, I will update the labels then.

Would it also be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) for example is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.

**Comment by LittleAlen** [comment]
Sorry to bother you, the issue doesn't happen in Fiddle, It happens in my project which uses electron + vue， maybe the issue comes from other components.  😂
