### ISSUE TITLE
[Bug]: print page size

### ISSUE THREAD

**Issue by eli-amazing** [electron/electron#39670]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0

### What operating system are you using?

Windows

### Operating System Version

22H2

### What arch are you using?

x64

### Last Known Working Electron version

24.0.0

### Expected Behavior

when invoking `webContents.print` without providing pageSize, the default size of the printer was chosen (with options

### Actual Behavior

when invoking `webContents.print` without providing pageSize, A4 size is chosen

### Additional Information

I use a Thermal 80 printer and A4 page causes either scaled content or cut out content, in previous versions the page size was omitted and it's printing correctly, and now even if im providing a page sized 80*297 it's scaling
maybe there's something i'm missing

**Comment by codebytere** [comment]
This is [expected behavior](https://github.com/electron/electron/blob/f30fbebb984816d71ab6723c04dd40b81337f397/lib/browser/api/web-contents.ts#L349) - the default is A4 unless otherwise specified.

**Comment by erykciepiela** [comment]
I guess the problem should be stated as follows (please confirm, @eli-amazing). The following code:

```
     const win = new BrowserWindow({
        width: 800,
        height: 600,
        show: false,
        contextIsolation: true,
      });
      const html64 = Buffer.from("<span>123456789012345678901234567890</span>").toString("base64");
      win.loadURL(`data:text/html;charset=utf-8;base64,${html64}`);
      win.webContents.on("did-finish-load", () => {
        win.webContents.print(
          { silent: false, printerName }
        );
      });
```
for `printerName` which is not a default system printer USED TO (e.g. Electron version 19) print with `printerName`'s default print page size. Currently (e.g. Electron version 30) it is not, page size taken from elsewhere.
With `silent: false`, the printing dialog by default chooses `printerName`'s default page size. This is inconsistent with the above.

Consequently, there is not way to silently print on given not default printer using its default page size which is blocking many sensible use cases. Our case is printing on POS printer which most likely is not the default printer in the system and which print page size is unknown.

Can we, please, re-open and address the issue? 

Thanks
