### ISSUE TITLE
[Bug]: Source maps of preload scripts break in Electron 26

### ISSUE THREAD

**Issue by inukshuk** [electron/electron#39701]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.1.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

25.8.0

### Expected Behavior

When loading preload scripts with source maps, the sources should be available in devtools.

Here is an example running in 25.8.0:

<img width="1147" alt="Screenshot 2023-08-31 at 09 42 36" src="https://github.com/electron/electron/assets/325102/0b2f19a3-a067-4c59-9762-d9e8270fdf5c">

### Actual Behavior

Since 26.0.0 source maps of preload scripts don't get applied in the sense: the relevant scripts are missing from 'content scripts', as a result it's difficult to find the scripts in devtools. By printing to the console you can link to and open a given preload script but you will see only the compiled/bundled version.

Here is the example from above, unchanged, running in 26.1.0:

<img width="1150" alt="Screenshot 2023-08-31 at 09 43 40" src="https://github.com/electron/electron/assets/325102/02a8d0fa-9ad0-41fa-923f-91f5c843b7de">

### Testcase Gist URL

https://gist.github.com/inukshuk/7374963a8bc966d5da72a38da3402d70

### Additional Information

Note that the source maps themselves get loaded. Here is the same example again, but I altered one of the source maps to contain a syntax error:

<img width="854" alt="Screenshot 2023-08-31 at 09 58 27" src="https://github.com/electron/electron/assets/325102/7b311c37-20c3-443f-9d3b-742b8b244382">

**Comment by inukshuk** [comment]
Here is a [gist to reproduce the issue](https://gist.github.com/inukshuk/7374963a8bc966d5da72a38da3402d70)

To run it:
1. `gh gist clone https://gist.github.com/inukshuk/7374963a8bc966d5da72a38da3402d70`
2. `cd 7374963a8bc966d5da72a38da3402d70`
3. `npm install`
4. `npm run build`
5. `npm start`

Here is a screenshot showing that the `preload.js` sourcemap has not been applied.

![Screenshot from 2023-09-26 10-47-54](https://github.com/electron/electron/assets/325102/f0019d94-3b9a-4011-883c-0e2dcb9ff7ff)

For comparison with older Electron:
1. `npm install electron@v25`
2. `npm start`

In this screenshot you can see that sourcemap is working.

![Screenshot from 2023-09-26 10-46-05](https://github.com/electron/electron/assets/325102/40684f74-76ab-426d-8cce-91e2ff8968f3)

**Comment by zacharyrankin** [comment]
👍 having this issue as well

**Comment by inukshuk** [comment]
Bump. This is the same on 28.1.3.

**Comment by chinaofmelon** [comment]
face the same issue, the issue on 29.1.5

**Comment by chinaofmelon** [comment]
face the same issue, the issue on 31.1.0

**Comment by inukshuk** [comment]
I've recently switched to using the Node.js ESM loader and if I try to access the preload script the inspector first says that the file was ignored because it's on the ignore list. It also shows an option to remove the file from the ignore list and then it shows up. At this point the sourcemap is not there (it was skipped presumably because the file was ignored) but if I then reload, the sourcemap is loaded and I can use the debugger normally.
