### ISSUE TITLE
[Bug]: Electron crashes by some users (Break instruction exception 0x80000003)

### ISSUE THREAD

**Issue by bladeRunner404** [electron/electron#39700]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.13

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

13.6.0

### Expected Behavior

As far as I know, this error triggers the cpu debugging breakpoint exception(0x80000003), but I did not debug the electron process. How to avoid this problem?

### Actual Behavior

CONTEXT:  (.ecxr)
rax=00007ff781ed0540 rbx=000000420d1fdbb0 rcx=0000000000000000
rdx=0000000000000000 rsi=000000420d1fe050 rdi=000000420d1fe068
rip=00007ff77a65c525 rsp=000000420d1fdac0 rbp=0000000000000071
 r8=00007ff781e87b68  r9=0000000000000004 r10=00000fff28eb8a7b
r11=0800000000000000 r12=aaaaaaaaaaaaaaaa r13=0000000000000000
r14=000000420d1fdb31 r15=0000000000000065
iopl=0         nv up ei pl zr na po nc
cs=0033  ss=0000  ds=0000  es=0000  fs=0053  gs=002b             efl=00000246
electron!logging::LogMessage::~LogMessage+0x9d5:
00007ff7`7a65c525 cc              int     3
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ff77a65c525 (electron!logging::LogMessage::~LogMessage+0x00000000000009d5)
   ExceptionCode: 80000003 (Break instruction exception)
  ExceptionFlags: 00000000
NumberParameters: 1
   Parameter[0]: 0000000000000000

PROCESS_NAME:  ntdll.wrong.symbols.dll

WRONG_SYMBOLS_TIMESTAMP: 7b5414ec

WRONG_SYMBOLS_SIZE: 1f5000

FAULTING_MODULE: 00007ff947570000 ntdll

0:000> .excr
rax=00007ff781ed0540 rbx=000000420d1fdbb0 rcx=0000000000000000
rdx=0000000000000000 rsi=000000420d1fe050 rdi=000000420d1fe068
rip=00007ff77a65c525 rsp=000000420d1fdac0 rbp=0000000000000071
 r8=00007ff781e87b68  r9=0000000000000004 r10=00000fff28eb8a7b
r11=0800000000000000 r12=aaaaaaaaaaaaaaaa r13=0000000000000000
r14=000000420d1fdb31 r15=0000000000000065
iopl=0         nv up ei pl zr na po nc
cs=0033  ss=0000  ds=0000  es=0000  fs=0053  gs=002b             efl=00000246
electron!logging::LogMessage::~LogMessage+0x9d5:
00007ff7`7a65c525 cc              int     3
0:000> kp
  *** Stack trace for last set context - .thread/.cxr resets it
 # Child-SP          RetAddr               Call Site
00 00000042`0d1fdac0 00004aec`00ae0b80     electron!logging::LogMessage::~LogMessage(void)+0x9d5 [C:\projects\src\base\logging.cc @ 959] 
01 00000042`0d1fdac8 00000042`0d1fe068     0x00004aec`00ae0b80
02 00000042`0d1fdad0 00004aec`00abef86     0x00000042`0d1fe068
03 00000042`0d1fdad8 00000042`0d1fe050     0x00004aec`00abef86
04 00000042`0d1fdae0 00000000`0000000d     0x00000042`0d1fe050
05 00000042`0d1fdae8 00007ff7`7cd7b5b3     0xd
06 00000042`0d1fdaf0 00000042`0d1fe170     electron!__crt_stdio_output::output_processor<char,__crt_stdio_output::string_output_adapter<char>,__crt_stdio_output::standard_base<char,__crt_stdio_output::string_output_adapter<char> > >::type_case_integer<10>(bool capital_hexits = true)+0x1a7 [C:\projects\src\out\Default\minkernel\crts\ucrt\inc\corecrt_internal_stdio_output.h @ 2631] 
07 00000042`0d1fdaf8 00007ff7`7cd7884e     0x00000042`0d1fe170
08 00000042`0d1fdb00 00000000`00000026     electron!__crt_stdio_output::string_output_adapter<char>::write_string(char * string = <Value unavailable error>, int length = 0n220192872, int * count_written = 0x00000042`0d1fdbb0, class __crt_cached_ptd_host * ptd = 0x00000000`00000049)+0x62 [C:\projects\src\out\Default\minkernel\crts\ucrt\inc\corecrt_internal_stdio_output.h @ 284] 
09 00000042`0d1fdb08 00007ff7`7cd7726f     0x26
0a 00000042`0d1fdb10 00000042`0d1fe144    electron!__stdio_common_vsprintf(unsigned int64 options = 0x65, char * buffer = 0x00000042`0d1fe050 "???", unsigned int64 buffer_count = 0x00000042`0d1fdbb0, char * format = <Value unavailable error>, struct __crt_locale_pointers * locale = 0x00000000`00000000, char * arglist = 0x00000000`00000000 "")+0x23f [C:\projects\src\out\Default\minkernel\crts\ucrt\src\appcrt\stdio\output.cpp @ 244] 
0b 00000042`0d1fdb18 00000000`0000000d     0x00000042`0d1fe144
0c 00000042`0d1fdb20 00007ff7`807ba941     0xd
0d 00000042`0d1fdb28 00007ff7`7cd791d6     electron!_wctype+0x1f1
0e 00000042`0d1fdb30 00000000`00000071     heyboxbrowser!__crt_stdio_output::output_processor<char,__crt_stdio_output::string_output_adapter<char>,__crt_stdio_output::standard_base<char,__crt_stdio_output::string_output_adapter<char> > >::state_case_type(void)+0x3ae [C:\projects\src\out\Default\minkernel\crts\ucrt\inc\corecrt_internal_stdio_output.h @ 2169] 
0f 00000042`0d1fdb38 00000000`00000066     0x71
10 00000042`0d1fdb40 00004aec`00ae0b80     0x66
11 00000042`0d1fdb48 00004aec`00afc6a0     0x00004aec`00ae0b80
12 00000042`0d1fdb50 00000000`00000049     0x00004aec`00afc6a0
13 00000042`0d1fdb58 00000000`00000001     0x49
14 00000042`0d1fdb60 00000000`0000002d     0x1
15 00000042`0d1fdb68 00007ff7`00000000     0x2d
16 00000042`0d1fdb70 00008660`3d05a365     0x00007ff7`00000000
17 00000042`0d1fdb78 00001d2c`00240400     0x00008660`3d05a365
18 00000042`0d1fdb80 00000000`00000040     0x00001d2c`00240400
19 00000042`0d1fdb88 00007ff7`807ba960     0x40
1a 00000042`0d1fdb90 aaaaaaaa`aaaaaaaa     electron!__crt_stdio_output::standard_lookup_table_spectre
1b 00000042`0d1fdb98 00000000`00000000     0xaaaaaaaa`aaaaaaaa

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
