### ISSUE TITLE
[Bug]:Trace/breakpoint trap (core dumped) 

### ISSUE THREAD

**Issue by lichanging** [electron/electron#39727]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

 25.7.0

### What operating system are you using?

Other Linux

### Operating System Version

CentOS 8.0 64bit with ARM

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Successfully run https://github.com/electron/electron/releases/download/v25.7.0/electron-v25.7.0-linux-arm64.zip with arm64v8/centos:centos7 container.

### Actual Behavior

![image](https://github.com/electron/electron/assets/29010071/87746737-73e0-4208-be46-b050efcdef2b)

coredump file with arm64v8/centos:centos7 ，[https://github.com/microsoft/vscode/files/12484074/core-electron-194-1693469608.zip](url)

### Additional Information

this bug was submitted first in VSCode  [https://github.com/microsoft/vscode/issues/191451](https://github.com/microsoft/vscode/issues/191451)

**Comment by lichanging** [comment]
Hi  @codebytere .  This bug depend on running environment，I send my  PC's login  token and reappear steps to  your [shelley.vohr@gmail.com](mailto:shelley.vohr@gmail.com)

**Comment by codebytere** [comment]
@lichanging if it cannot be reproduced outside one very specific device that's not something we can triage and investigate further. I do not SSH into arbitrary user devices as a matter of safety and principle. If you'd like us to proceed, you can attach a crash dump to help us get more information. You can collect them by adding the following snippet to your main process code, before `app.whenReady`:

```
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by lichanging** [comment]
reproduced crash steps：

1. download https://github.com/electron/electron/releases/download/v25.7.0/electron-v25.7.0-linux-arm64.zip, then unzip to directory： /home/tongyuan/electron-v25.7.0-linux-arm64/

2. execute following command:
```
docker pull arm64v8/centos:centos7
docker run -v /home/tongyuan:/home/tongyuan -it --privileged arm64v8/centos:centos7 /bin/bash

yum install gtk3 -y
yum install alsa-lib-devel -y
yum install cups-libs -y
yum install at-spi2-atk -y
yum install atk -y

echo "core-%e-%p-%t" > /proc/sys/kernel/core_pattern

cd /home/tongyuan/electron-v25.7.0-linux-arm64/
ELECTRON_RUN_AS_NODE=1 ./electron
```
3. The terminal reproduced： **Trace/breakpoint trap (core dumped).**    
    [the crash dump file download address.](https://github.com/electron/electron/files/12517633/core-electron-207-1693874947.zip)

**Comment by VerteDinde** [comment]
@lichanging Did the repro steps produce a .dmp file specifically that you could share here? As @codebytere mentioned above, you can create and then find the .dmp file by adding this before `app.whenReady`:

```
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

The `console.log(app.getPath('crashDumps'))` should log where the .dmp file is specifically - if we can see the .dmp file, we can more easily see the stacktrace of your crash, and figure out what's breaking.

If adding that line of code doesn't produce a .dmp file, you could also try downloading the .rpm build of Electron Fiddle here, and trying to reproduce the Electron 25.7.0 on Fiddle itself: https://github.com/electron/fiddle/releases/tag/v0.34.0 Sorry to keep asking, but without a .dmp file or more detailed stacktrace, it's very difficult for us to move forward with debugging (we unfortunately can't SSH into your environment for security reasons, as @codebytere said above). Thanks for your help!

**Comment by lichanging** [comment]
```
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```
![image](https://github.com/electron/electron/assets/29010071/5063d845-7d85-447b-8eea-aafe4775b498)

add above code in demo [electron-quick-start](https://github.com/electron/electron-quick-start) happened  errors: [exited with signal SIGTRAP](https://github.com/electron/electron-quick-start/issues/554)，

**Comment by lichanging** [comment]
@VerteDinde  after installed electron-fiddle-0.34.0-1.arm64.rpm to run it,  happened error：Trace/breakpoint trap (core dumped)
[This core dump file.](https://github.com/electron/electron/files/12592665/core-electron-fiddle-3443-1694570511.zip)

**Comment by jgresham** [comment]
Having a similar issue when I upgrade electron from 25 to 26 or 27. I only receive `SIGTRAP` on Ubuntu. No problems on Mac or Win

**Comment by shimr12** [comment]
I'm also having same issue after I've upgraded from 2.23 to 2.26+ (tried several versions)

**Comment by wangjiesg** [comment]
I also encountered the same problem
![微信截图_20240111132758](https://github.com/electron/electron/assets/89345915/b97a1901-dad8-4f5b-b650-fadb995f35f6)

**Comment by plp13** [comment]
OK, it looks this has been reported elsewhere:

https://github.com/electron/electron/issues/46538
