### ISSUE TITLE
[Bug]: safeStorage decryption doesn't work with a different `userData` path

### ISSUE THREAD

**Issue by johnnyd710** [electron/electron#39733]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

I expected to be able to encrypt some data using the safeStorage encryptString API:
```js
  const userDataPath = path.join(__dirname, 'userData1');
  app.setPath('userData', userDataPath);
  await app.whenReady();
  const password = 'password';
  const encryptedPassword = safeStorage.encryptString(password);
  await fs.promises.writeFile(path.join(__dirname, 'encryptedPassword.txt'), encryptedPassword);
```

And then be able to decrypt the data later without issue, despite changing the `userData` path:

```js
  const userDataPath = path.join(__dirname, 'userData2'); // 'userData1' will work, 'userData2' does not.
  app.setPath('userData', userDataPath); 
  await app.whenReady();
  const encryptedPassword = await fs.promises.readFile(path.join(__dirname, 'encryptedPassword.txt'));
  const decryptedPassword2 = safeStorage.decryptString(encryptedPassword); // should return 'password'
```

See a full repro here: https://github.com/johnnyd710/electron-safe-storage-bug

### Actual Behavior

I get: 
```
Error: safeStorage.decryptString - Error while decrypting the ciphertext
```

### Additional Information

We have a unique application architecture requiring us to NOT use the `singleInstanceLock` feature of electron. Instead, we allow multiple instances by changing the `userData` path. But we want them to share the same secrets.

**Comment by MarshallOfSound** [comment]
This is expected behavior, the implementation of `safeStorage` on Windows requires a consistent `userData` path as the secret is stored in that path (encrypted via DPAPI)

You could potentially do stuff like copy the secret around to other userData directories and it would technically continue to work but this isn't something that Electron would officially support / provide an API for
