### ISSUE TITLE
[Bug]: Use backgroundColor: '#00000000' to set the issue of transparency not taking effect

### ISSUE THREAD

**Issue by 123lujiaqiang** [electron/electron#39764]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.8.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### What arch are you using?

x64

### Last Known Working Electron version

26.0.0

### Expected Behavior

Should be a transparent window.

### Actual Behavior

I used backgroundColor: '#00000000' to set the window transparency, but it doesn't seem to work and the window still has a black background.But it doesn't work.

This is the application window：
![image](https://github.com/electron/electron/assets/71049666/a8cd49f3-ac55-4dc2-a7a5-63506b313afb)

This is my code：

`
// Create the browser window.
  mainWindow = new BrowserWindow({
    width: 500,
    height: 630,
    show: false,
    resizable: false,
    autoHideMenuBar: true,
    // transparent: true,
    // fullscreen: true,
    frame: false,
    backgroundColor: '#00000000',
    hasShadow: false,
    // opacity: 0.5,
    title: 'effect_tools_app',
    ...(process.platform === 'linux' ? { icon } : {}),
    webPreferences: {
      backgroundThrottling: false,
      webSecurity: false,
      preload: path.join(__dirname, '../preload/index.js'),
      sandbox: false
    }
  })
`

### Additional Information

I can use transparent: true to make Windows transparent, and it works fine in Windows. However, when I used window capture software to capture the electron application window, the transparent part of it turned into a black background, which was weird. I had to try setting the backgroundColor: '#00000000', but that obviously didn't work either.

I hope I can get help.
Finally, please forgive my clumsy English.

**Comment by VerteDinde** [comment]
@123lujiaqiang I tried to load the code you provided into a gist for testing with Electron Fiddle - let me know if I didn't get it quite right!: https://gist.github.com/VerteDinde/86ad079a3d4194fba399de3749358c1c

From my testing, the transparency seemed to be working as expected 🤔 You mentioned that the window turned black when you tried to use window capture software - could you provide the name of the software you used, or maybe record a video showing how you were using the window capture software and what happened? Just trying to get more of a repro of the issue so we can figure out what's going on.

**Comment by 123lujiaqiang** [comment]
I am very glad to receive your reply.
I have used your example program on my computer, and it was indeed transparent at initial startup, and the window Capture software (OBS) captured the window without problem, but once minimized in the taskbar and displayed again, it became opaque.
This is my recording:

https://github.com/electron/electron/assets/71049666/8c148322-2e73-400b-b8d1-78b3b8f714d5

**Comment by Galkon** [comment]
I believe some of our users are running into this on our production app. We cannot reproduce it internally at all, which is frustrating. I am currently attempting to run a couple tests with users if I can get in contact with them.

Has anyone found any solutions yet?

**Comment by Galkon** [comment]
Oh also, @123lujiaqiang did you confirm that this is fixed on electron 26?

**Comment by 123lujiaqiang** [comment]
> Oh also, @123lujiaqiang did you confirm that this is fixed on electron 26?

I'm sure this was appearing in electron: version 26.2.0, however, it works fine again. I don't know what caused it, and I'm sorry. Here's a screenshot of me working normally:

![2023-11-10_102824](https://github.com/electron/electron/assets/71049666/68f61688-3bf8-44a6-aa89-b03f51571abe)

**Comment by Galkon** [comment]
> > Oh also, @123lujiaqiang did you confirm that this is fixed on electron 26?
> 
> I'm sure this was appearing in electron: version 26.2.0, however, it works fine again. I don't know what caused it, and I'm sorry. Here's a screenshot of me working normally:
> 
> ![2023-11-10_102824](https://user-images.githubusercontent.com/71049666/281936308-68f61688-3bf8-44a6-aa89-b03f51571abe.png)

You're on 26.2.0? I've made a 27.0.4 build for our users to try who have this issue but it doesn't seem to fix it. Sad.
