### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Dgc12d782** [electron/electron#39760]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

3.10

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

idk

### Expected Behavior

After launch, you need to enter the bot token and manage it

### Actual Behavior

Just a gray screen after startup.

https://github.com/electron/electron/assets/125802021/a19e34b1-995b-4498-8bd7-af99aa5ebf1c

**Comment by Dgc12d782** [comment]
Fix this bug pls

**Comment by ProgramminCat** [comment]
Please check the "Elements" tab of the dev tools

**Comment by Dgc12d782** [comment]
![Снимок экрана 2023-09-07 011850](https://github.com/electron/electron/assets/125802021/90884bc4-c7e5-403d-9426-e901d257243c)

**Comment by Dgc12d782** [comment]
![Снимок экрана 2023-09-07 011850](https://github.com/electron/electron/assets/125802021/99cfd86f-e61a-4da3-83d8-188109652aac)
![Снимок экрана 2023-09-07 012154](https://github.com/electron/electron/assets/125802021/de69ae48-8cd3-45c6-91f7-1a9524aee706)
![Снимок экрана 2023-09-07 012204](https://github.com/electron/electron/assets/125802021/933d3984-aee8-42e7-b742-0a5c04c33905)
![Снимок экрана 2023-09-07 012212](https://github.com/electron/electron/assets/125802021/ae0078bc-203b-4690-a50f-c13a650931e1)
![Снимок экрана 2023-09-07 012221](https://github.com/electron/electron/assets/125802021/7d74a0b1-31a4-4f33-a9f3-76cf6bdbf00d)
![Снимок экрана 2023-09-07 012228](https://github.com/electron/electron/assets/125802021/0e4f8785-efdc-4330-bc89-ee56738f2464)
![Снимок экрана 2023-09-07 012239](https://github.com/electron/electron/assets/125802021/c8dc4700-f449-4d87-933a-cb2f1703c259)

**Comment by ProgramminCat** [comment]
seems to be a problem with the dom manipulation...

**Comment by Dgc12d782** [comment]
it's app problem or System (client) problem?

**Comment by ProgramminCat** [comment]
probably a client problem like your electron chromium version is not compatible with an other version of some other dependency.

So you should probably do a `sudo apt update && sudo apt upgrade` or `sudo pacman -Syu`

**Comment by ProgramminCat** [comment]
oh wait you're on Windows...

You need to probably reinstall Electron

**Comment by Dgc12d782** [comment]
I have Windows on my computer or can these commands be entered in powershell?

**Comment by Dgc12d782** [comment]
how to reinstall Electron?
(sorry)

**Comment by Dgc12d782** [comment]
btw. old version works perfect (1.0.0)

**Comment by Dgc12d782** [comment]
> btw. old version works perfect (1.0.0)

but don't understand wihout tags # usernames

**Comment by Dgc12d782** [comment]
and don't add friends with tags username #

**Comment by ProgramminCat** [comment]
> how to reinstall Electron? (sorry i dump)

`npm install --save-dev electron`

**Comment by VerteDinde** [comment]
Thanks for reaching out and logging this issue! It looks like this issue is specific to Discord Bot Client and not Electron itself. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
