### ISSUE TITLE
[Bug]: minWidth, minHeight, maxWidth, maxHeight in BrowserWindow are not applied.

### ISSUE THREAD

**Issue by forestk** [electron/electron#39786]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0-alpha.6

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.5.1（22G90）

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

26.2.0

### Expected Behavior

When the following code is executed, the window should only be resized to a width of 600-800 and a height of 400-600.

```js
const win = new BrowserWindow({

  minWidth: 600,
  width: 700,
  maxWidth: 800,

  minHeight: 400,
  height: 500,
  maxHeight: 600
  
})
```

### Actual Behavior

The window can be resized beyond 600-800 in width and 400-600 in height.

### Testcase Gist URL

https://gist.github.com/cd2632ea636bc4a33be98a8330003dae

### Additional Information

Thanks for the great work you guys do.

**Comment by codebytere** [comment]
Looks like https://github.com/electron/electron/commit/3fa15ebb7e8aef2029cd23370fdc96f382c9d161 broke this cc @zcbenz

**Comment by forestk** [comment]
How is the issue going?

**Comment by codebytere** [comment]
@forestk working on fixing an edge case for frameless windows but i'd estimate a week or two max and it'll be handled!

**Comment by forestk** [comment]
@codebytere Thanks. I look forward to seeing it fixed!
