### ISSUE TITLE
[Bug]: Incorrect font under Wayland

### ISSUE THREAD

**Issue by PlumeTomi** [electron/electron#39791]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04 Gnome

### What arch are you using?

x64

### Expected Behavior

Electron should use the correct system font whether running under Wayland, XWayland or X11. Unlike Electron, Chromium works correctly and always uses the system font whether under Wayland, XWayland or X11.

### Actual Behavior

I cloned `electron-quick-start` git repo and started the app using `electron .` command. App opened under XWayland and the app correctly uses system font. However, when launching the app under Wayland using `electron --ozone-platform-hint=auto .`, the app does not use system font for the window itself anymore, but some other font (perhaps its a default or predefined electron font, not sure). Chromium does not suffer from this issue.

This issue affects other popular electron apps as well, most notably `VS Code`! In VS Code, the code editor itself works as it should (as the user can specify the font), but all the other GUI elements (file explorer,  etc.) are using the wrong font when running under Wayland.

Running under XWayland (this is how it should be)
![image](https://github.com/electron/electron/assets/71773685/9a0ee3d4-fac3-420a-8608-858e44b41a57)

Running under Wayland (incorrect font for window title and dropdown)
![image](https://github.com/electron/electron/assets/71773685/6ee26877-d4a1-4dd1-8dd7-227764639fd4)

### Additional Information

I had a similar issue with cursor itself, but I resolved it by creating `/usr/share/icons/default` a symlink that points to the correct icon theme on Ubuntu. If that helps with anything.

**Comment by VPaulV** [comment]
still having this issue
