### ISSUE TITLE
[Bug]: Restoring the parent window will re-show hidden child windows

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#39813]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2.1

### What arch are you using?

x64

### Expected Behavior

I expect that when I restore a window, its hidden child windows aren't re-shown

### Actual Behavior

child windows are reshown

### Testcase Gist URL

https://gist.github.com/pushkin-/2352a690db1762d3d6c70f4de23f6d15

### Additional Information

1. click "Open Window" button
2. after 2 seconds, it will hide
3. minimize the main window
4. restore the main window
5. notice the child window is reshown

**Comment by abpbackup** [comment]
Related to this
https://github.com/electron/electron/issues/39704#issuecomment-1724516510

**Comment by codebytere** [comment]
Folding into https://github.com/electron/electron/issues/39704 as they have the same root cause.
