### ISSUE TITLE
[Bug]: loadFile can't find the file if query string is provided (for a production build)

### ISSUE THREAD

**Issue by israelidanny** [electron/electron#39831]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

window.loadFile("path/to/my/file.html") should work just as fine as window.loadFile("path/to/my/file.html", { query: { id: 123 } }) 

### Actual Behavior

window.loadFile("path/to/my/file.html") finds the file and loads it just fine
window.loadFile("path/to/my/file.html", { query: { id: 123 } }) fails to load file with Error -6: ERR_FILE_NOT_FOUND

**Comment by mlaurencin** [comment]
With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this, but it can be reopened if a test case is provided.
