### ISSUE TITLE
[Bug]: Flash of window in incorrect postion when using setbounds on a transparent window

### ISSUE THREAD

**Issue by MTalkatoo** [electron/electron#39834]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When calling setbounds on a transparent window, if I correctly adjusted the coordinates of the window to accommodate the change in size of the window, the contents of the window should not appear to move, even thought the window is now larger.

### Actual Behavior

after calling setbounds on a transparent window, there is a brief flash as the window is first moved and then resize (even though only one setbounds call was made).

### Testcase Gist URL

https://gist.github.com/94b8a3cfc518cf689d2647626129a102

### Additional Information

For best results of triggering this issue with the gist, click onto another window before you click the expand button.

I am on macOS as mentioned, but I also find this issue to occur on windows (at least 10, untested on 11).

This is slightly related to issue #1445, which resulted in the setbounds function being created, except it appears the issue wasn't fully resolved, of even though two function calls are no longer needed, visually, there is still a flash as the window is first re-positioned then expanded.

**Comment by githoniel** [comment]
face the same issue in win10

**Comment by MTalkatoo** [comment]
still an issue.

**Comment by MTalkatoo** [comment]
Still an issue, even on electron version 30.0.6.

**Comment by githoniel** [comment]
> Still an issue, even on electron version 30.0.6.

I have a workround if you have to change window bounds when align your content to left or top,  eg: popup a new menu to top of your content. It is to create multi-window.  you can create a new hidden window to display menu, set to right bounds and show it  when popup.
