### ISSUE TITLE
[Bug]: Drag and Drop a file opens a new Electron window and a save dialog

### ISSUE THREAD

**Issue by ollm** [electron/electron#39839]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

`27.0.0-beta.1`  and `27.0.0-beta.2`

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.3 LTS

### What arch are you using?

x64

### Last Known Working Electron version

`27.0.0-alpha.6`

### Expected Behavior

Drag and drop should work correctly.

### Actual Behavior

I have in my app the function of drag files from the file explorer, using the drag `HTMLElement` and getting the `event.dataTransfer.files[0].path`, in electron `v25.8.0` and `v27.0.0-alpha.6` it works fine, but in version `27.0.0-beta.1` when dropping the file opens a new Electron window and below a dialog to save the file that I just dragged.

![Captura desde 2023-09-12 22-14-12](https://github.com/electron/electron/assets/18549191/0cc8caa2-1c49-4511-8e6b-139abc3bacf6)

Events I use:

``` js
window.addEventListener('dragenter', showDropZone);
window.addEventListener('dragleave', hideDropZone);
window.addEventListener('dragover', allowDrag);
window.addEventListener('drop', handleDrop);
```

### Testcase Gist URL

https://github.com/ollm/electron-drag-and-drop-bug

### Additional Information

This has started to happen in the `beta` version of electron 27, it did not happen in the `alpha` version.

**Comment by Sourav-Kumar-Panda** [comment]
Can i work on this?

**Comment by ckerr** [comment]
@ollm I removed the "https://github.com/ollm/OpenComic" link since that's not a standalone testcase; that's a whole application :smile_cat:

**Comment by ollm** [comment]
Hi, I have created standalone testcase: https://github.com/ollm/electron-drag-and-drop-bug

After doing some tests, it seems that drag and drop in electron `27.0.0-beta.1` opens the files as if I drag and drop them in Chrome/Chromium, if I drag an image it opens the window showing it, the same with text files or even with a PDF, it opens the Chrome/Chromium PDF reader, in the file that I originally reported, he can't open it and tries to download/save it as it would happen in Chrome/Chromium.

**Comment by ollm** [comment]
I can confirm that it also happens in Windows 11


https://github.com/electron/electron/assets/18549191/f3a8a05f-f72d-47e8-a83b-50531abc1b50

**Comment by dsanders11** [comment]
Having dug into this more, I don't believe there's an actual bug here, so I'm going to close the issue accordingly. There's an upstream Chromium behavior change which is causing the dropped file to open a new window, but you should be using `event.preventDefault()` on the `drop` event to prevent the default behavior anyway. It also looks like the new window is suppressed if you have `WebContents.setWindowOpenHandler` set up to deny opening new windows.

So adding `event.preventDefault()` to your `drop` event handler should restore the previous behavior for you. 👍
