### ISSUE TITLE
[Bug]: The https request for set-cookies did not write the cookie successfully

### ISSUE THREAD

**Issue by tetap** [electron/electron#39830]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.0

### What operating system are you using?

Windows

### Operating System Version

Window10 22H2

### What arch are you using?

x64

### Last Known Working Electron version

26.2.0

### Expected Behavior

Successfully written to cookie，And allows http requests to be carried

### Actual Behavior

Failed to carry correctly when sending the request

**Comment by tetap** [comment]
Because I used it session.defaultSession.webRequest.onCompleted

**Comment by Sourav-Kumar-Panda** [comment]
Can i work on this?
