### ISSUE TITLE
[Bug]:   protocol.handle('xx', (request) =>    this only trigger for xx:\\ in windows xx:// not working in windows

### ISSUE THREAD

**Issue by AiHaibara** [electron/electron#39843]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.1.0

### What operating system are you using?

Windows

### Operating System Version

win11

### What arch are you using?

x64

### Expected Behavior

keep support old  like protocol.registerFileProtocol('xx' can support xx:// ?
but not sure does this are changed by design

### Actual Behavior

xx:// will not trigger protocol.handle('xx', (request) =>
xx:\\\\ will trigger protocol.handle('xx', (request) =>

**Comment by MarshallOfSound** [comment]
File protocols and network protocols are different, `protocol.handle` supports a very specific spec for URLs which is just `protocol://foo`.  I don't think adding support for `\` makes sense for this API

**Comment by AiHaibara** [comment]
> 
but currently is windows can't using protocol:// trigger for handle('protocol',     only can using protocol:\\ can trigger this handle
if this is the same thing, maybe it's ok
