### ISSUE TITLE
[Bug]: On Mac, hidden window is still accessible after calling win.hide()

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#39840]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I expect that when a window is hidden, it isn't visible and not accessible

### Actual Behavior

There are situations where it can be made visible (though not interactable)

### Testcase Gist URL

https://gist.github.com/pushkin-/edac0a8d9290e4a18891d570e734e25d

### Additional Information

Possibly related to [this issue](https://github.com/electron/electron/issues/39572)

1. start app
2. click Open Window
3. Three-finger swipe up to see all the windows
4. After 5 seconds, the preview of the secondary window will disappear
5. You can still hover over that area and see the blue outline, click on it
6. Notice you can access the hidden window, though you can't interact with it.

**Comment by codebytere** [comment]
Looking into this, it seems unfortunately to be a native macOS AppKit bug. If i create a window and strip out every other call besides `NSWindow orderOut:`, it reproduces - it can also be seen in native behavior for non-Electron apps. I'd suggest filing a [Bug Report](https://developer.apple.com/bug-reporting/) there but there's nothing we can do at this point to fix it given the locus of the issue. Should something change though, happy to re-investigate!
