### ISSUE TITLE
[Feature Request]: Start app on system boot

### ISSUE THREAD

**Issue by Generalize** [electron/electron#39845]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Add feature to support start app on system boot that can enable and disable app auto start and query app startup configuration.

### Proposed Solution

In windows can place vbs script to startup folder or add register table.
In linux can add user corn task.
I don't kown about macos.

### Alternatives Considered

No alternatives solutions ,There isn't npm package can to do this.

**Comment by Prinzhorn** [comment]
A quick search brings up this:

```js
app.setLoginItemSettings({
  openAtLogin: true
})
```

is this different from what you are asking here?

**Comment by Generalize** [comment]
> A quick search brings up this:
> 
> ```js
> app.setLoginItemSettings({
>   openAtLogin: true
> })
> ```
> 
> is this different from what you are asking here?

This is i want
