### ISSUE TITLE
[Bug]: Crash on MacOS during normal usage

### ISSUE THREAD

**Issue by fdlmdark** [electron/electron#39856]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.6

### What operating system are you using?

macOS

### Operating System Version

macOS 13.0.1 (22A400)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Not crash

### Actual Behavior

Crash

### Additional Information

[jira.rongcloud.net_secure_attachment_39985_beemmac_crash.log.txt](https://github.com/electron/electron/files/12603258/jira.rongcloud.net_secure_attachment_39985_beemmac_crash.log.txt)

**Comment by 3177014867** [comment]
Hello @fdlmdark. Thanks for helping to make Electron better with this. Makes Electron maintainers easy to use and publish. Added dead tag to block all unnecessary variables to solve problems.
