### ISSUE TITLE
Issue Commented: No jobs were run email from Github

### ISSUE THREAD

**Issue by hovancik** [electron/electron#39882]
Hi, when I comment on issue, I get this email from github that links to: 
Issue Commented: No jobs were run
https://github.com/electron/electron/actions/runs/6201054415

Happened twice on https://github.com/electron/electron/issues/27912#issuecomment-1721616197

**Comment by dsanders11** [comment]
Thanks for the report. This issue is being fixed in #39875, it just hasn't been merged yet. Apologies for the email noise.
