### ISSUE TITLE
[Bug]: Area where traffic lights is rendered does not receive click events when app is fullscreened with titlebar hidden on macOS

### ISSUE THREAD

**Issue by sergeichestakov** [electron/electron#39885]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.5.2

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

N/A

### Expected Behavior

Hi there! Apologies if there is already an opened issue for this, I tried to look in the repo but could not find anything relevant.

As the title suggests, we're currently experiencing an issue in our Mac app, which uses a hidden titlebar and therefore renders the traffic lights inline in our app's header alongside clickable elements such as buttons and popovers, where the leftmost buttons are no longer clickable when the app is maximized.

In debugging this, I realized that those buttons (which we have set up to replace the position of where the traffic lights were in the maximized state) do not receive click events at all (e.g. I can't select them from the Chromium inspector and setting a debugger for `onclick` events in the DOM yields nothing when I click that region.

Other relevant information here is that our header which renders these buttons has `-webkit-app-region: drag` set (so it does not receive DOM click events as expected) but each individual button has `-webkit-app-region: no-drag` set to allow them to be clickable and otherwise work just fine when the app is not maximized and the buttons have not been rendered where the traffic lights were in the un-maximized state.

### Actual Behavior

As described above, the relevant two leftmost buttons in our draggable header (which have `no-drag` set) are clickable when rendered next to the traffic lights while the app is not maximized but no longer receive click events when they replace the traffic lights at the edge of the window when it is maximized.

See demo gif below:

![no-click-events-desktop-app-macos](https://github.com/electron/electron/assets/24947334/94270fec-08e6-456c-a7c5-d90c29bd61c1)

### Testcase Gist URL

https://gist.github.com/sergeichestakov/c84835f4d80182744b99e837268edc7c

### Additional Information

Worth noting that we can only reproduce this so far in macOS Ventura (on an M1 Mac). We also tried macOS Big Sur (on an x86 Mac) but this bug does not reproduce there.

Also relevant, we initialize the BrowserWindow with the following options:

```typescript
  const window = new BrowserWindow({
    webPreferences: {
      preload,
      additionalArguments: [
        `--app-version=${app.getVersion()}`,
        `--platform=${process.platform}`,
      ],
      webviewTag: true,
    },
    title,
    icon,
    minWidth: 720,
    minHeight: 480,
    backgroundColor,
    autoHideMenuBar: true,
    // on macOS:
    titleBarStyle: 'hidden',
    titleBarOverlay: { height: 48 },
    trafficLightPosition: { x: 20, y: 16 },
  });
```

**Comment by sergeichestakov** [comment]
thanks! yeah I realized this would be much harder to triage / debug without a repro. I can put one together later this week or weekend

**Comment by sergeichestakov** [comment]
update: I put together a minimal repro with Electron Fiddle today in [this gist](https://gist.github.com/sergeichestakov/c84835f4d80182744b99e837268edc7c) (also updated PR description).

See demo:

![electron-click-bug-repro](https://github.com/electron/electron/assets/24947334/a30744f3-087b-4dea-a72b-2769cf560389)

**Comment by jtbandes** [comment]
Thanks for fixing this! Just found the same issue in our app and glad to see it's already been fixed 😄

**Comment by jtbandes** [comment]
Also worth mentioning that I noticed that the problem did not occur whenever the dev tools were open.
