### ISSUE TITLE
[Bug]: Uncaught DOMException: Background Sync is disabled.

### ISSUE THREAD

**Issue by abdallahemad94** [electron/electron#39893]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Electron has background sync disabled. Background sync is used to trigger the service worker to sync changes. It helps to sync work which was done by user when he was offline. Would be good to enable it by default. It is enabled by default in chromium and chrome.
On page with service worker registered, this snippet should produce no errors.

```
navigator.serviceWorker.ready.then(function(swRegistration) {
  return swRegistration.sync.register('myFirstSync');
});
```

This issue was raised at https://github.com/electron/electron/issues/9802
It is unclear to me why https://github.com/electron/electron/issues/9802 was merged with https://github.com/electron/electron/issues/6697. The other issue is about Web Push, which is distinct from Background Sync.
Also, the https://github.com/electron/electron/issues/6697 was closed without a fix to the Background Sync problem https://github.com/electron/electron/issues/9802 .

### Actual Behavior

When run with electron, I get

Uncaught (in promise) DOMException: Background Sync is disabled.

### Additional Information

How to reproduce
Open youtube.com with electron

OR

git clone https://github.com/hokein/electron-sample-apps
cd electron-sample-apps
npm install -g electron
electron service-worker/mock-response
Open the console and type in the snippet:

navigator.serviceWorker.ready.then(function(swRegistration) {
return swRegistration.sync.register('myFirstSync');
});
It gives the error in electron. Use the same snippet in youtube on the browser, it runs fine.

**This is the same bug as #31063 which is closed as not planned the issue still exists with electron v 26.2.1**

**Comment by MarshallOfSound** [comment]
https://github.com/electron/electron/issues/6697 is the correct tracking issue for this, internally they are not so distinct and the work required to support one is similar to the other (somehow exposing the ability for electron apps to provide their own service urls for push/sync)
