### ISSUE TITLE
[Bug]: In Mac OS Sonoma (14.0) showInactive, is not inactive anymore

### ISSUE THREAD

**Issue by castroCrea** [electron/electron#39914]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.1

### What operating system are you using?

macOS

### Operating System Version

Mac OS Sonoma 14

### What arch are you using?

x64

### Expected Behavior

When `window.showIncative()` the focus is still on the app below the window that you just make appear. The menu is still the menu from the app below and not the menu from your app.

My window is in `type: panel`

### Actual Behavior

When window `type: panel` and on `window.showIncative()` the electron js app becomes active, the app's menu shows. 

This wasn't the behavior on the previous Mac OS version.

**Comment by castroCrea** [comment]
`focus()` active the window, when it is not supposed too.

**Comment by nbabanov** [comment]
We are experiencing the same issues.

**Comment by castroCrea** [comment]
@electron-triage  here de Fiddle https://gist.github.com/castroCrea/2465a8dbeb7a00781d30a2cd01fbd18e

I also add a comment 
<img width="551" alt="image" src="https://github.com/electron/electron/assets/20707343/cd2704fe-ac43-4f37-a8c0-73cbc9ae6471">

**Comment by codebytere** [comment]
@castroCrea what behavior do you see on previous versions exactly? The provided Fiddle does not work on Ventura as-is: the window does not show at all and i see the following in console:

> NSWindow does not support nonactivating panel styleMask 0x80

**Comment by abhaybuch** [comment]
Also running into this when trying to show a panel window without taking activating the application. Investigating if there's an quick fix via native Node module. But my suspicion is that the issue is that Sonoma changed some implementation detail that caused the [following lines](https://github.com/electron/electron/blob/main/shell/browser/native_window_mac.mm#L472-L473) in `focus`:
```
[[NSApplication sharedApplication] activateIgnoringOtherApps:NO];
[window_ makeKeyAndOrderFront:nil];
```
to start activating the application when it previously did not. The new behavior reads as more correct so we might have been relying on a bug 😬 

I think the thing we need is to be able to call just `makeKeyAndOrderFront`, will report back if I can get it working in a test

**Comment by abhaybuch** [comment]
Take a look at https://github.com/abhaybuch/node-mac-window for a hacked together native module that lets you bring a window into focus without activating it's application

**Comment by ufukomer** [comment]
> Take a look at https://github.com/abhaybuch/node-mac-window for a hacked together native module that lets you bring a window into focus without activating it's application

@abhaybuch Thank you so much this is just working! :) Electron team should create a built-in function for this!

**Comment by ufukomer** [comment]
yeah, I haven't seen this bug in any of the change log even though it's merged. I am still using @abhaybuch's library.

**Comment by castroCrea** [comment]
@ufukomer how do you use this lib?

**Comment by ufukomer** [comment]
> @ufukomer how do you use this lib?

yes

**Comment by ufukomer** [comment]
> @ufukomer how do you use this lib?

1. Add to `package.json`:

```json
"dependencies":  {
  "node-active-app": "github:abhaybuch/node-mac-window",
}
```

2. Add types if you are using TS:

```typescript
// node-active-app.d.ts
declare module 'node-active-app' {
  export function makeKeyAndOrderFront(buffer: Buffer): void;
}

```

3. Instead of calling browserWindow's show function, override it, or just call makeKyAndOrderFront function:

```typescript
import { makeKeyAndOrderFront } from 'node-active-app';

// This is how it looks like for my app but you don't have to do it, just call makeKeyAndOrderFront by passing the native window handle of your BrowserWindow as param.
show(): void {
    if (this.isLocked()) {
       iipc.send(SHOW_MAIN_WINDOW);
    } else if (!this.window.isVisible()) {
      makeKeyAndOrderFront(this.window.getNativeWindowHandle());
    } else {
      this.hide();
    }
}
```

**Comment by mikeyyyzhao** [comment]
Anyone else seeing the [work around](https://github.com/electron/electron/issues/39914#issuecomment-1767361782) from @abhaybuch fail on `Sonoma 14.3`? It worked wonders on previous version of the macOS but broke when I updated my macOS to 14.3

**Comment by ufukomer** [comment]
> Anyone else seeing the [work around](https://github.com/electron/electron/issues/39914#issuecomment-1767361782) from @abhaybuch fail on `Sonoma 14.3`? It worked wonders on previous version of the macOS but broke when I updated my macOS to 14.3

I did not create any new build after updating to Sonoma 14.3, I will let you know when I try.

Also, since this issue is closed, @felixrieseberg  can you help us out to understand how to achieve the same functionality without using @abhaybuch's library?

**Comment by YongzeYao** [comment]
> Take a look at https://github.com/abhaybuch/node-mac-window for a hacked together native module that lets you bring a window into focus without activating it's application

Could you please tell me how to use this?

**Comment by YongzeYao** [comment]
hi @castroCrea, if I understand this correctly, this is still not fixed right?
calling `focus()` on a panel still activates the app right now.

**Comment by castroCrea** [comment]
it is not fixed

**Comment by YongzeYao** [comment]
is there a plan to fix this?

**Comment by YongzeYao** [comment]
@ufukomer hey friend, just checked your app, looks great. Could you please tell me how you achieve to get where the pasted content comes from?

**Comment by ufukomer** [comment]
@YongzeYao are you asking about the source App Icon's that appear on left side of the clipboard history items? Like, if you copied data from Chrome, chrome app icon is appearing on the left site of the list item. If so, it is about accessing the active app using native swift code. I can help me more if that is what you are asking about. If you have telegram: @ufukomer. If not drop me a line: ufukomer@gmail.com because this is irrelevant with the issue subject.

**Comment by YongzeYao** [comment]
Please fix this :) 
It is essential for certain system utility apps to not steal previous app's activation.
