### ISSUE TITLE
[Feature Request]: Event for Tabbed BrowserWindows close

### ISSUE THREAD

**Issue by jinusean** [electron/electron#39927]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There is no way to tell if a tabbed group of BrowserWindows closed

### Proposed Solution

An event should be sent to the last browser window in the tabbed group when the entire group is closed at once.

Something like a `tabbing-group-close`

### Alternatives Considered

No other way I can think of.

**Comment by codebytere** [comment]
Unfortunately as of now there isn't a way to differentiate these. See [this forum post](https://stackoverflow.com/questions/59512245/difference-between-osx-windows-red-dot-close-button-and-a-tabbed-windows-x-clo) for more context. I'm going to close this out as a wontfix but would be happy to revisit in the future should this become possible as described.
