### ISSUE TITLE
(love) Just to tell you how great your software is

### ISSUE THREAD

**Issue by aleluff** [electron/electron#39929]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

MacOS

### What arch are you using?

x64

### Expected Behavior

The real issue is maybe that opensource developers don't receive enough gratification.
Thanks to you, creator can build better software

### Actual Behavior

Have a nice day =)

**Comment by georgexu99** [comment]
<3
