### ISSUE TITLE
[Bug]:  render process memory leak when reload page

### ISSUE THREAD

**Issue by eltonchan** [electron/electron#39936]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v26.2.2

### What operating system are you using?

macOS

### Operating System Version

macOs Monterey Mac Book Pro 16-inch,2021 Memory 16G

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

none

### Expected Behavior

when web page reload no memory leak

### Actual Behavior

memory leak when web reload

### Additional Information

[https://user-images.githubusercontent.com/12627010/249026190-16cba606-7c6f-4b16-8774-5a6736c893f4.png
https://user-imag](https://user-images.githubusercontent.com/12627010/249026190-16cba606-7c6f-4b16-8774-5a6736c893f4.png)

https://user-images.githubusercontent.com/12627010/249026374-365e759c-081d-4cf8-a858-aa828494cb35.png

![1684984004063](https://github.com/electron/electron/assets/12627010/4d7b3aac-abd1-49ad-86a2-f82913a1ec74)
es.githubusercontent.com/12627010/249026374-365e759c-081d-4cf8-a858-aa828494cb35.png

<img width="1728" alt="image" src="https://github.com/electron/electron/assets/12627010/26041988-bcbe-4242-a2af-a4ed9293a70e">

When system swap used memory large, if I use app several days with reload app several times, It's will occur 2x dom, document detached but memory leak.

chrome haven't this issues, I don't know what different between electron reload and chrome reload, it's seem some different in technical detail. It's seem Electron document different to Chrome document, I just use window.location.reload to reload web page. Only kill render process make memory normal

It's main process code like:
const windowOptions = {
width: 1280,
height: 840,
title: "Electron APIs",
}
mainWindow = new BrowserWindow(windowOptions)
mainWindow.loadURL('https://xxxxx.com/')

When this happens, the 'old space' in V8 becomes very large, and even when I call webFrame.clearCache, force a window garbage collection, or even load a different URL, it cannot be reclaimed. It's necessary to terminate the renderer process to resolve the issue. I haven't encountered this problem in Chrome's incognito browser, so I believe there may be some differences between Electron's reload and Chrome's reload, but I'm not familiar with the details.

because it's hard to reproduce so i don't have demo app to reproduce it. I don't know whether other people encounter this issues, if there is an answer, please let me know. Thank you very much. This question has been bothering me for a long time.

**Comment by eltonchan** [comment]
If a memory snapshot is needed, I can provide it.

**Comment by eltonchan** [comment]
Do you have any recommendations? How can we pinpoint this issue, or which Electron module might be related to it? Is Electron considering aligning its reload mechanism with Chrome? What are the differences between them?

**Comment by eltonchan** [comment]
This issue has been bothering me for a very, very long time. It seems that Windows systems may also experience this problem. Do you have any hints or suggestions?

**Comment by MarshallOfSound** [comment]
Without a minimal sample (fiddle is a good place to start) we won't be able to really help track this down, if you can repro the leak with a simple app (or as simple as you can make it) posting that would be a good

**Comment by eltonchan** [comment]
chrome can reopen this bug. so it's not electron issues, close it.
