### ISSUE TITLE
[Bug]: Thread 0 Crashed:: CrRendererMain Dispatch queue: com.apple.main-thread

### ISSUE THREAD

**Issue by AndyLyttle** [electron/electron#39938]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Deploying App to App Store via using MAS format from

(neither work - both get same error)
1) Electron forge
2) Electron builder.

### Actual Behavior

Steps:
1) Generate PKG through forge Makers (or through Electron builder)
2) Upload PKG to App store connect via Apple transporter app 
3) Release pkg via testflight for download
4) App Launches, then crashes 

### Additional Information

I dont think i can create a fiddle for this - its for the desktop versions - but i am getting the same error from the following tries:

1) my actual app i want to deploy using electron-forge
2) a hello world react app using electron forge
3) a hello world react app using electron-builder

All get the following crash:

https://pastebin.com/E61mmx8k

**Comment by codebytere** [comment]
@AndyLyttle looking at the dump:

```
Kernel Triage:
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage
 
 
Thread 0 Crashed:: CrRendererMain Dispatch queue: com.apple.main-thread
0   Electron Framework            	       0x11a02280e node::AsyncResource::get_async_id() const + 10793118
1   Electron Framework            	       0x11a022829 node::AsyncResource::get_async_id() const + 10793145
2   Electron Framework            	       0x11a022846 node::AsyncResource::get_async_id() const + 10793174
3   Electron Framework            	       0x11b66bd78 node::AsyncResource::get_async_id() const + 34162184
4   Electron Framework            	       0x117ce01f0 v8::internal::V8::FatalProcessOutOfMemory
```

This is what happens when you exceed heap limitations in V8. This is not an issue with Electron - it's a function of the app you've written and the V8 JavaScript engine underpinning Chromium/Node.js. See https://github.com/electron/electron/issues/22705#issuecomment-600372490 for potential paths forward.

**Comment by AndyLyttle** [comment]
We did see this and profile the app, it never goes over 100MB usage.

What solved this error was entitlement changes,  

1) in electron forge you cant seem to specify different entitlements for different things 

We moved to electron builder and by specifying entitlement files correctly,  the app now ran as expected

![image](https://github.com/electron/electron/assets/95286921/70ab6a1b-101e-4b06-8503-012f5b84f381)

For anyone facing an issue like this in future - the Login Helper entitlement was of particular importance,  we think this is what was crashing our app,  When we put com.security.apple.inherit within this, it crashed every time,  but when we just included ONLY com.security.apple.sandbox - the app finally started without issue.
