### ISSUE TITLE
[Bug]: Electron ignores XCompose settings when running natively on Wayland

### ISSUE THREAD

**Issue by RalfJung** [electron/electron#39957]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.14

### What operating system are you using?

Other Linux

### Operating System Version

Debian testing

### What arch are you using?

x64

### Expected Behavior

Put some custom definitions into `~/.XCompose`, such as
```
# General logic notation
<Multi_key> <t> <o> : "→"
<Multi_key> <minus> <greater> : "→"
<Multi_key> <g> <e> <t> <s> : "←"
<Multi_key> <less> <minus> : "←"
<Multi_key> <i> <f> <f> : "↔"
<Multi_key> <less> <minus> <greater> : "↔"
<Multi_key> <e> <x> : "∃"
<Multi_key> <a> <l> <l> : "∀"
<Multi_key> <a> <n> <d> : "∧"
<Multi_key> <slash> <backslash> : "∧"
<Multi_key> <backslash> <slash> : "∨"
<Multi_key> <n> <o> <t> : "¬"
<Multi_key> <n> <e> <g> : "¬"
```
Now restart everything and start an electron application (I am using vscodium). The compose definitions should work. (They work in all other Wayland applications.)

### Actual Behavior

The custom compose definitions do not work, they are entirely ignored.

### Additional Information

This is https://github.com/electron/electron/issues/29345 being reopened. It got closed without being fixed by an over-aggressive bot.

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
