### ISSUE TITLE
[Bug]: node-gyp failed to rebuild after updated to 26.2.1

### ISSUE THREAD

**Issue by ArunKathir98** [electron/electron#39953]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

22.0.0

### Expected Behavior

Build Successfully.

### Actual Behavior

node-gyp failed to rebuild 'K:\GRB\4tvKbV-H\0\**\node_modules\exe-icon-extractor'.

[FAILED] For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

[FAILED] 

[FAILED] Error: request to https://www.electronjs.org/headers/v26.2.1/node-v26.2.1-headers.tar.gz failed, reason: write EPROTO A42E0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:922:

Unable to build the exe and msi package.

**Comment by MarshallOfSound** [comment]
This looks more like an issue with your local environment being unable to connect to our headers server, ensure your version of node is up to date or that your proxy correctly supports the SSL algos our headers CDN supports
