### ISSUE TITLE
[Bug]: set "transparent" to true and "titleBarStyle” to "hidden", a title bar is shown when window loses focus, "backgroundMaterial" not work until resizing the window.

### ISSUE THREAD

**Issue by bluesky335** [electron/electron#39959]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0-beta.5

### What operating system are you using?

Windows

### Operating System Version

Windows 11 - 22H2 

### What arch are you using?

x64

### Expected Behavior

1、The window should show without a title bar.
2、The window should be transparent and backgrounds should be "acrylic" style.
![image](https://github.com/electron/electron/assets/13523898/42e404c0-7215-4810-9603-06d93e0b95ad)

### Actual Behavior

1、window background not transparent and not "acrylic" style until I resize the window.

![image](https://github.com/electron/electron/assets/13523898/13e58cf2-4695-4d60-8cf1-f6d347febdf0)
 after resize the window:
![image](https://github.com/electron/electron/assets/13523898/87c3ed1a-0858-4812-a5f5-857034d9e6b3)

2、If the window loses focus, a title bar is shown and it can't interact.

![image](https://github.com/electron/electron/assets/13523898/2a733fde-4f60-4947-9891-97f18073890d)

### Testcase Gist URL

https://gist.github.com/d51806da56e0f6103859d0164b22a80a

**Comment by michalzaq12** [comment]
Confirmed in the environment (Electron 27.0.0-beta.5, Windows 11 - 22H2). Can be divided into two independent issues:
1. Transparent window without frame (`frame: false, transparent: true` or `transparent: true, titleBarStyle: 'hidden'`) shows the title bar when it loses focus.
2. Transparent window without frame still doesn't work with Mica, resizing the window solves the problem (however when I hide/show the window it stops working again).

**Comment by codebytere** [comment]
cc @clavin

**Comment by vitaminj** [comment]
The phantom titlebar that is drawn under everything seems to happen even without acrylic (transparent true, frame false and/or titleBarStyle hidden).

But there seem to be a whole collection of bugs around these handful of settings that need to be tackled at the same time, this feel like whack-a-mole otherwise. I think they're all related to window flags that overlap each other.

Something is drawing a phantom titlebar which can be seen when titleBarStyle=hidden and transparent=true
Something is not setting up the window correctly on initial show wrt acrylic
With frame on but titlebar hidden, the Windows 11 rounded corners are lost
If transparent=true the window is no longer resizeable unless you set titleBarStyle=hidden

(Also, some combinations of the settings may not be possible? I feel the documentation should be updated.)

With all of these issues, there's no way to make a Windows 11 style app which should have rounded corners, no oldstyle titlebar, and parts or all of the content being acrylic/mica.

**Comment by togume** [comment]
Any updates on this? We finally got #40062 solved (but not merged with 26), and now this is blocking us from upgrading to 27 😭. We're stuck on 25 with a horrible bug where sharing screen during a call will crash the full app randomly.

@clavin let us know if there's any way we can support you in testing or being guinea pigs. cc. @VerteDinde 

Much gratitude, as always, for supporting this project 🙏

**Comment by KochiyaOcean** [comment]
As a workaround, set the background as `#00000000` when the window is foucsed or blurred can hide the title bar

```javascript
win.on('blur', () => {
  win.setBackgroundColor('#00000000')
})

win.on('focus', () => {
  win.setBackgroundColor('#00000000')
})
```

**Comment by vitaminj** [comment]
Thanks @KochiyaOcean! And along those lines, putting this in the focus handler kicks the acrylic into action (although does give you a flicker in dev mode):
```
const [w, h] = win.getSize();
win.setSize(w, h);
```
Now, how to fix rounded corners...?

Or should I just carry on using the Win10-era native hacks in [electron-acrylic-window](https://www.npmjs.com/package/electron-acrylic-window)?

**Comment by KochiyaOcean** [comment]
> Thanks @KochiyaOcean! And along those lines, putting this in the focus handler kicks the acrylic into action (although does give you a flicker in dev mode):
> 
> ```
> const [w, h] = win.getSize();
> win.setSize(w, h);
> ```
> 
> Now, how to fix rounded corners...?
> 
> Or should I just carry on using the Win10-era native hacks in [electron-acrylic-window](https://www.npmjs.com/package/electron-acrylic-window)?

I think the only way is to wait until dev fix it, I've tried some ways but cannot bring round corner back

**Comment by abpbackup** [comment]
It seems like the real problem is when you use showInactive instead of show(). Keep the same settings without the mentioned workarounds and use show() instead and see the issue is gone. I know that show() behaves different, just giving more insights so the fix comes faster!

**Comment by abpbackup** [comment]
@codebytere FYI

**Comment by meta-panic** [comment]
Hello! Our team faced the same issue after upgrading electron to the 27 version.
We can provide you with another reproduction if needed.
Unfortunately, @KochiyaOcean's workaround didn't work for us  :( 

Could you update us on the progress of the bug?




### Some information about our case, we hope it would help you
#### **Electron Version**
"electron": "~27.0.0"
#### **What operating system are you using?**
Windows
#### **Operating System Version**
Windows 10/11
#### **What arch are you using?**
x64
#### **Last Known Working Electron version**
`"electron": "~25.8.0"

**Comment by meta-panic** [comment]
@clavin FYI

**Comment by Nakus0426** [comment]
[Reproduce Video](https://user-images.githubusercontent.com/41540888/276517016-1ed57049-bc9d-45cd-bb00-18c30fbd9d5b.mp4)

**Comment by sandyfigueroa** [comment]
I have the same issue with Electron 27.0.2.

Impossible to get rid of that phantom titlebar.

(transparent: true and titleBarStyle: 'hidden')

**Comment by KochiyaOcean** [comment]
As I mentioned in another issue,  the reason is that when transparent is true, the thick frame will be disabled, which removes all animation of window

https://github.com/electron/electron/blob/652f995128de858c7a68fad853f56e80e0c2c222/shell/browser/native_window_views.cc#L238-L241

I've opened a PR to allow thickFrame transparent window, but since it's taking breaking changes, I'm wondering if there is a better way to fix it

**Comment by brhenrique** [comment]
The title bar issue is caused by `WN_NCACTIVATE` messages being sent to frameless transparent windows, see #40395 for more details

**Comment by cedric-swivvel** [comment]
We stumbled across the issue with the title bar appearing after removing this line on the transparent window: `window.setContentProtection(true)`. When adding that line back, the title bar no longer appeared.

So, at least for us, it seems that setting content protection to `true` is a temporary workaround to prevent the title bar from appearing. We're on `electron@27.0.3`.

**Comment by mydaoyuan** [comment]
after resize the window is ok .

I dynamically adjust the window size when the window loses focus and regains focus. is work for me.

**Comment by KoalatyCode** [comment]
I also have this issue when a transparent and frameless window loses focus for the first time.

**Comment by beibeibeibei2022** [comment]
```javascript
/**/
function createWindow() {
	win = new BrowserWindow({
		width: 1600,
		height: 900,
		frame: false,
		transparent: true,
		backgroundColor: "#00000000",
	});

	win.loadFile("index.html");

	/* Electron issues 39959 */
	/* Electron27.0.3 On win11, Electron 28.0.0 on Win10 22H2 X64*/
	/* Temporary solution: Modify window size when the window is focused or blurred */
	/* (Whether modifying the height or the width, the page content may shake, please choose according to your needs) */
	
	/* Using Electron26.6.2 may not have this issue. For me, this bug may not appear.*/
	/* Electron26.6.2 cannot click through the transparent area */
	/* Electron27.0.3 and 28.0.0 can click through the transparent area */
	
	if (/^(27|28)\.\d+\.\d+(\-alpha\.\d+|\-beta\.\d+)?$/.test(process.versions.electron) && process.platform === "win32") {
		win.on("blur", () => {
			const[width_39959, height_39959] = win.getSize();
			win.setSize(width_39959, height_39959 + 1);
			win.setSize(width_39959, height_39959);
		});
		win.on("focus", () => {
			const[width_39959, height_39959] = win.getSize();
			win.setSize(width_39959, height_39959 + 1);
			win.setSize(width_39959, height_39959);
		});
	}
}
/**/
```

**Comment by clavin** [comment]
The fixes for this issue have been merged to the development branches for Electron 27, 28, and 29. The next release for each of those versions should contain the fix!

As I write this, we're working on releasing Electron 28.1.1 which contains this fix. 😄

**Comment by HenrikoMagnifico** [comment]
Still having this issue on electron 29...

**Comment by flick9000** [comment]
Problem still present

**Comment by DK013** [comment]
Problem still persists in electron v31.3.1. none of the mentioned workarounds worked for me.

**Comment by DK013** [comment]
> Problem still persists in electron v31.3.1. this workaround works.

Can confirm the problem exists in v32 as well as there's a problem with this solution as well. the height restore part doesn't work. Tried even with a timeout. and as the window keep loosing focus and get into focus, it keeps growing

**Comment by AndrewSmithDev** [comment]
I was able to fix this in Electron v36.2.1 with:

```js
win.on("blur", () => {
  win.setResizable(true);
  win.setResizable(false);
});
```

**Comment by royalsrivastavagithub** [comment]
@DK013 does this bug still exist ?

**Comment by An0nshy** [comment]
@royalsrivastavagithub for me yes, on windows11 and electron 36.4.0

**Comment by devPablo** [comment]
I can confirm this is still an issue on Windows 10, Electron 36.4.0

**Comment by bukharin** [comment]
New issue to track the regression - https://github.com/electron/electron/issues/46882

**Comment by lvcabral** [comment]
The proposed workarounds (changing some window properties on `blur` and `focus`) works mostly (with some flashes) but not when the blur is caused by a dialog modal (window blur is not triggered) so the phantom title bar appears and is not removed until the dialog closes.

<img width="1469" height="706" alt="Image" src="https://github.com/user-attachments/assets/f68dfd07-15d1-46bd-825f-20aadcc23436" />

**Comment by CrossPr0duct** [comment]
confirm this is still a bug lol

**Comment by yassine-ouchen** [comment]
Yoooooo it's from 2023 fix this shiiit

**Comment by RushNRX** [comment]
tag me when u fix this

**Comment by wujunliang** [comment]
This issue still exists in version 37.2.4

**Comment by Kemerd** [comment]
I have a version that doesn't flash. You essentially stop rendering, do the flash, then re-enable flash. 

This is what I have, roughly:

```
const runWorkaround = () => {
	if( yourWindow && !yourWindow.isDestroyed()) {
		// Pause rendering
		yourWindow.webContents.setFrameRate(0)
		const [width, height] = yourWindow.getSize()
		yourWindow.setSize(width, height + 1)
		process.nextTick(() => {
			if( yourWindow && !yourWindow.isDestroyed()) {
				trayWindow.setSize(width, height)
				trayWindow.webContents.setFrameRate(60)
			}
		})
	}
}

yourWindow.webContents.on('before-input-event', runWorkaround)
yourWindow.webContents.on('focus', runWorkaround)
yourWindow.webContents.on('blur', runWorkaround)
```

Thank you @DK013 for your workaround. I could not have created this one without yours.
