### ISSUE TITLE
[Bug]: Why does the program start with an error like this

### ISSUE THREAD

**Issue by student-ice** [electron/electron#39958]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.2

### What operating system are you using?

Other Linux

### Operating System Version

Deepin v23

### What arch are you using?

x64

### Last Known Working Electron version

26.2.2

### Expected Behavior

This error will not be printed

### Actual Behavior

Why does the program start with an error like this?
It didn't affect my program, though

![image](https://github.com/electron/electron/assets/59855569/31dde2c4-415a-472f-9e45-ea05f5e05d4a)

**Comment by MarshallOfSound** [comment]
Chromium logs anything sev warn or higher by default, if your app isn't actually having any issues just ignore it.
