### ISSUE TITLE
[Bug]: App Window Becomes Unclickable Due to Cursor Movement at Startup

### ISSUE THREAD

**Issue by Imperat** [electron/electron#39952]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.8.1

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.0

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

Tested on 24 (lowest version available on Fiddle)

### Expected Behavior

The BrowserWindow is focused and content within it is clickable.

### Actual Behavior

The BrowserWindow is not focused and content within it is not clickable.

### Testcase Gist URL

https://gist.github.com/Imperat/624d9989cff29005e6f9e8a9cc185eef

### Additional Information

First half of the recording shows how the issue is reproduced, I had to move the cursor in a specific way immediately after starting the app. The last part of the recording shows that the issue is not reproducible if the cursor isn't moved while the window is being created.

Other finding notes:
- It is much harder to reproducible lower version of macOS Sonoma.
- Double clicking and using keyboard navigation (via `tab`) allows interacting with the `webContents`.
- Focusing other app window and switching back allow us to recover the window. 
- Calling `browserView.webContents.focus()` within a timeout fixes the issue.

https://github.com/electron/electron/assets/7069867/09b770e9-fc43-4e56-951c-a9f9f9b216aa

**Comment by mlaurencin** [comment]
@Imperat In order to test older versions of Electron on Fiddle, you can go into the settings and within Electron Settings check the Obsolete box under Channels.  If you are able to identify the last known working version and could update your issue with it that would be great.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by Imperat** [comment]
Hello @mlaurencin @codebytere 

I tested and I was able to reproduce it with the earliest supported version on my machine - Electron 11.

For ease of reproducing I recommend use laptop's touch pad and external mouse at the same time.
