### ISSUE TITLE
[Bug]: fromDevToolsTargetId is not a function

### ISSUE THREAD

**Issue by Bug-Reaper** [electron/electron#39961]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.2

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.5

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

Unkown

### Expected Behavior

Be able to get a web-contents instance for a developer-tools panel using code snippet from [official documentation](https://www.electronjs.org/docs/latest/api/web-contents#webcontentsfromdevtoolstargetidtargetid):

### Actual Behavior

Given snippet from docs:
```javascript
async function lookupTargetId (browserWindow) {
  const wc = browserWindow.webContents
  await wc.debugger.attach('1.3')
  const { targetInfo } = await wc.debugger.sendCommand('Target.getTargetInfo')
  const { targetId } = targetInfo
  const targetWebContents = await wc.fromDevToolsTargetId(targetId)
}
```

Get error in terminal: 
```bash
(node:17134) UnhandledPromiseRejectionWarning: TypeError: wc.fromDevToolsTargetId is not a function
```

Can see a proper targetId is picked up. Unclear why `fromDevToolsTargetId()` function is undefined for my root application window web-contents.

Easy to replicate on any vanilla electron.js config/setup. Simply declare and run above function on the BrowserWindow instance returned from `new BrowserWindow({})`

**Comment by Bug-Reaper** [comment]
Figured it out. The import/require version of `webContents` has many of the methods like `fromDevToolsTargetId()` etc....
**However** the `webContents` instance returned from `new BroswerWindow({})` does not have many of the methods listed in the documentation

If this is an intended quirk, the code snippet should be adjusted to something akin to:
```javascript
import { webContents } from 'electron'
async function lookupTargetId (browserWindow) {
  const wc = browserWindow.webContents
  await wc.debugger.attach('1.3')
  const { targetInfo } = await wc.debugger.sendCommand('Target.getTargetInfo')
  const { targetId } = targetInfo
  const targetWebContents = await webContents.fromDevToolsTargetId(targetId)
}
```

**Comment by Ricky004** [comment]
Hi, I am a novice and I am unable to comprehend. I believe you have resolved your issue or not ?

**Comment by MarshallOfSound** [comment]
@Bug-Reaper This may be a clarity issue in the docs but they are accurate.  There are two concepts of "webContents" in Electron, the class and the module.

`browserWindow.webContents` returns an **instance** of the `WebContents` class.

`import { webContents } from 'electron'` returns the webContents **module**.  These are documented separately.

[Methods on the `webContents` module](https://www.electronjs.org/docs/latest/api/web-contents#methods) (has a code example too)

[The WebContents class documented separately further down the page](https://www.electronjs.org/docs/latest/api/web-contents#class-webcontents)

**Comment by Bug-Reaper** [comment]
> @Bug-Reaper This may be a clarity issue in the docs but they are accurate. There are two concepts of "webContents" in Electron, the class and the module.
> 
> `browserWindow.webContents` returns an **instance** of the `WebContents` class.
> 
> `import { webContents } from 'electron'` returns the webContents **module**. These are documented separately.
> 
> [Methods on the `webContents` module](https://www.electronjs.org/docs/latest/api/web-contents#methods) (has a code example too)
> 
> [The WebContents class documented separately further down the page](https://www.electronjs.org/docs/latest/api/web-contents#class-webcontents)

@MarshallOfSound 

Ahhh so it is intentional that the instance of `WebContents` **class** returned from `browserWindow.webContents` does not have the `fromDevToolsTargetId` method and also several other methods listed in the `WebContents`**module**.

---

See [code-snippet from electron documentation that mislead me](https://www.electronjs.org/docs/latest/api/web-contents#webcontentsfromdevtoolstargetidtargetid):

```javascript
  async function lookupTargetId (browserWindow) {
    const wc = browserWindow.webContents
    await wc.debugger.attach('1.3')
    const { targetInfo } = await wc.debugger.sendCommand('Target.getTargetInfo')
    const { targetId } = targetInfo
    const targetWebContents = await wc.fromDevToolsTargetId(targetId)
  }
```

This example used as is returns an error because `fromDevToolsTargetId` method does not exist on the `browserWindow.webContents` **class** instance it is run from.

---

If docs are open-source. I could add something to make the module/class distinction more clear and also fix example snippet of code that is outright broken.
