### ISSUE TITLE
[Feature Request]: Add means to get the main process entry script when using ESM

### ISSUE THREAD

**Issue by timfish** [electron/electron#39986]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Once Electron v28 makes it to stable and we see wider adoption of ESM in the main process, we lose `require.main.filename` and when the Electron app is packaged to is a great way to get the entry script. 

### Proposed Solution

`app.mainStartupScript`?

### Alternatives Considered

In Node you can just use `process.argv[1]` but there is no path supplied in the args in packaged Electron apps.

**Comment by timfish** [comment]
Actually, after checking the internal code, I can see that I can access this at `process._firstFileName`.

Could this be made public and documented?

**Comment by timfish** [comment]
Ah, it looks like `mainModule` is just a "soft deprecation" and it wont be removed from runtime:
https://github.com/nodejs/node/pull/32232#pullrequestreview-373812950

**Comment by timfish** [comment]
Oh no, `mainModule` isn't set with ESM so it looks like there is no way to get the entry path in Electron with ESM...

**Comment by dsanders11** [comment]
@timfish, have you tried using `url.fileURLToPath(import.meta.url)` as a replacement? That should be the equivalent to  `require.main.filename` in the main process.

**Comment by timfish** [comment]
`require.main.filename` gives you the entry module from any module whereas `url.fileURLToPath(import.meta.url)` only gives you the entry module FROM the entry module.

**Comment by timfish** [comment]
We don't really have a need for this any more so I'll close it an anyone can re-open it if they still think it should be added!
