### ISSUE TITLE
[Bug]: Everlast loading cursor on tray menu

### ISSUE THREAD

**Issue by alx-dmt** [electron/electron#39981]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2

### What arch are you using?

x64

### Last Known Working Electron version

13.6.9

### Expected Behavior

If I open tray menu by right click and move mouse on menu items cursor has normal view (as arrow).

### Actual Behavior

If I open tray menu by right click and move mouse on menu items _for the first time_ I see everlast loading cursor (spinner). At the same time I can click on items and commands will done correctly. If I will close tray menu and open again, cursor becomes normal (arrow).
![image](https://github.com/electron/electron/assets/67313455/1d81f1f2-4e41-4475-b039-3b6b0dc96cdf)

### Additional Information

It reproduced on node v18.18.0 (x64) and v16.15.1 (x64)
Github repo to clone https://github.com/stalker8610/electron-tray-bug

```
const { app, Tray, Menu } = require('electron');
const path = require('path');

let tray;
// create menu template
const mainContextMenuTemplate = [
    {
        label: 'Some label 1',
        type: 'normal',
        click() {
            console.log('some text');
        }
    },
    {
        label: 'Quit',
        type: 'normal',
        role: 'quit'
    },
]

function createTray() {
    // load tray icon
    const trayIconPath = path.join(__dirname, './assets/images/tray-image.png');
    tray = new Tray(trayIconPath);
    tray.setToolTip("Some tooltip");
    const contextMenu = Menu.buildFromTemplate(mainContextMenuTemplate);
    tray.setContextMenu(contextMenu);
}

app.on('ready', function () {
    console.log(process.versions.electron);
    createTray();
});

app.on('window-all-closed', () => {
});

app.on('before-quit', function () {
    tray.destroy();
});
```

**Comment by alx-dmt** [comment]
Github repo to reproduce https://github.com/stalker8610/electron-tray-bug

**Comment by b5414** [comment]
same with `electron v28.2.1`

**Comment by vojtabohm** [comment]
bump

**Comment by OhASys** [comment]
bump
