### ISSUE TITLE
[Bug]: Window control button style adaptation

### ISSUE THREAD

**Issue by iyuli** [electron/electron#39995]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows11

### What arch are you using?

x64

### Last Known Working Electron version

26.2.1

### Expected Behavior

Window control button style adaptation
The window control buttons of Electron are inconsistent with other types of Win11 windows
The following screenshot includes the control buttons for three window types in Win 11, which are:
1. Electron
2. UWP
3. Win 32 APP
![QQ截图20230927205128](https://github.com/electron/electron/assets/38270397/188ee30e-21a7-4fe8-9be6-bdcca1453e88)

### Actual Behavior

I hope that Electron can optimize the style of window control buttons and adapt to Win11

**Comment by mlaurencin** [comment]
Thanks for taking the time to contribute! As this is request is for an enhancement to a feature rather than a bug, I am going to go ahead and close this bug report. If you would like, you may refile this as a feature request so that this adaptation may be considered in the future.
