### ISSUE TITLE
[Bug]: Can`t create menu bar for macOS on 26.2.3 version, in 26.0.0 work normal

### ISSUE THREAD

**Issue by Degensoft-vlad** [electron/electron#40018]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.3

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2.1

### What arch are you using?

x64

### Last Known Working Electron version

26.0.0

### Expected Behavior

I expect a normal work for shortcuts command like copy/paste

### Actual Behavior

I can not copy or paste text in electron app, and add menu from template after packaging

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
