### ISSUE TITLE
[Feature Request]: BrowserView and BrowserWindow can be converted into each other

### ISSUE THREAD

**Issue by Saodd** [electron/electron#40027]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

We are building a simple browser based on electron. User can open multiple tabs in a single window just like common browsers.

Our new browser creates one electron-`BrowserView` for each "tab" and add it to the mono `BrowserWindow` to simulate "multiple tabs".
We use `setWindowOpenHandler()` to intercept window-open events and get the url to new a `BrowserView.`

But some websites open new window like this:

```js
const win = window.open();
win.opener = null;
win.location = 'https://foo.bar';
```

In this case, the arguments of `setWindowOpenHandler()` will be something like `details.url === 'about:blank#blocked'`. So we are not able to get the real url for the new `BrowserView`.

### Proposed Solution

Propose 1:
BrowserView and BrowserWindow can be converted into each other, by tranfsering their `.webcontents`.
OR:
Let  `setWindowOpenHandler()` open new window in a `BrowserView`, for example, by returning a `{action: 'allow', openInBrowserView: true}`

### Alternatives Considered

Propose 2:
Since `window.open()` returns a WindowProxy that supports futher control in RendererProcess, can `setWindowOpenHandler()` return a whateverProxy that can listen to those events in MainProcess?

**Comment by pushkin-** [comment]
I'm not really following this at all. Why can't you hook into the `browserView.webContents.setWindowOpenHandler` and handle the window.open from there and have that open a new tab or navigate or whatever you need? What does "about:blank#blocked" have to do with anything. If you see that URL, why can't you just cancel the window.open or show some error message or something

**Comment by codebytere** [comment]
@Saodd I understand what you're trying to achieve, but that can be achieved with existing APIs and events in Electron's core  now - there's not really enough impetus here to add a new bespoke API for that purpose. I'm closing this out in agreement with @pushkin-.

**Comment by Saodd** [comment]
@codebytere 
Excuse me, can you give me some tips on how to achieve this?
