### ISSUE TITLE
[Bug]: Preventing the event "page-title-updated" doesn't prevent of changing the window title.

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#40048]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 10.0.19045.3448

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

The title should remain the same.

### Actual Behavior

The title of the window is being changed.

### Testcase Gist URL

https://gist.github.com/c444b2fca4de519c6e655f6cbf7cedfd

**Comment by codebytere** [comment]
@gdavidkov it's a bit confusing, but there are two places where `page-title-updated` is emitted, and only one of them can be prevented. Per [docs](https://github.com/electron/electron/blob/c96bb9958f98822af9ce072e02a17b8b8a9766d3/docs/api/web-contents.md#L172) the event on `webContents` _cannot_ be prevented, while the event on [`BrowserWindow`](https://github.com/electron/electron/blob/c9eb3deab58f2562113866eaf89d094e60f8184a/docs/api/browser-window.md#L164) _can_. In your gist, simply changing

```js
mainWindow.webContents.on("page-title-updated", (e, title) => {
    e.preventDefault();
})
```

```js
mainWindow.on("page-title-updated", (e, title) => {
    e.preventDefault();
})
```

achieves your goal.
