### ISSUE TITLE
[Bug]: GLSL Link errors in Electron 26.2.4 (stable / latest)

### ISSUE THREAD

**Issue by davesmith00000** [electron/electron#40055]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.4

### What operating system are you using?

Other Linux

### Operating System Version

Manjaro Linux, kernel 6.1.53-1

### What arch are you using?

x64

### Last Known Working Electron version

25.8.4

### Expected Behavior

Working, known good WebGL 2.0 GLSL 300 programs should link correctly.

### Actual Behavior

Shader programs are failing to compile with a linking error, where the status returned by a call to `gl.getProgramParameter(shaderProgram, LINK_STATUS)` is false.

### Additional Information

![electron_26_2_4_glsl_linker_error](https://github.com/electron/electron/assets/908709/4346273a-7027-4625-8152-41500f149ad6)

The code that produced that error looks like this, but unfortunately there is no additional log information being produced:

```scala
val shaderProgram = gl.createProgram()
gl.attachShader(shaderProgram, vertShader)
gl.attachShader(shaderProgram, fragShader)
gl.linkProgram(shaderProgram)

if (gl.getProgramParameter(shaderProgram, LINK_STATUS).asInstanceOf[Boolean]) shaderProgram
else {
  IndigoLogger.error(gl.getProgramInfoLog(shaderProgram));
  gl.deleteProgram(shaderProgram);
  throw new Exception(s"Fatal: RawShaderCode program link error ($layerLabel)")
}
```

Tested in all the publically listed stable Electron versions, only the latest (26.2.4) is failing.

**Comment by codebytere** [comment]
@davesmith00000 does this work in Google Chrome latest versions?

**Comment by davesmith00000** [comment]
Hi @codebytere, I have Chrome and Chromium installed, both on apparently the same version and both apparently work:

```
Chrome - Version 117.0.5938.149 (Official Build) (64-bit)
Chromium - Version 117.0.5938.149 (Official Build) Arch Linux (64-bit)
```

I don't know if this is any use to you, but this is a web accessible version of same of the engine/code that didn't work when I raised the issue:

https://davesmith00000.github.io/shaders/shaders/noise/cellular-noise

If the canvas has a colorful pattern in it, it works. If it's black then it does not, and if you check the logs you see a somewhat vague shader link error.

**Comment by davesmith00000** [comment]
Hmmm... I'd done a system update today and, feeling paranoid that I might have given you incorrect information I thought I'd test again. Neither show the link error but Chrome is misbehaving FYI:

Chromium (good):
![image](https://github.com/electron/electron/assets/908709/9f63a5c4-76f5-4f29-ac76-d5f9ad640d16)

Chrome (bad):
![image](https://github.com/electron/electron/assets/908709/badae6c2-1e72-4762-ab67-0d2e325b4f27)

So that _isn't_ related to this bug. If you see that behaviour in testing... it's something else. :grimacing:

**Comment by davesmith00000** [comment]
Closing. Apologies, after my system update I now have the inverse problem where the older version `25.8.4` doesn't work, but the latest release does. As terrible as it is, I'm therefore assuming it's actually something driver related and specific to my machine. Thanks, and sorry for the wild goose chase!
