### ISSUE TITLE
[Bug]: EXCEPTION_ACCESS_VIOLATION_READ / 0x0: Fatal Error: EXCEPTION_ACCESS_VIOLATION_READ / 0x0

### ISSUE THREAD

**Issue by ductridev** [electron/electron#40051]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19045

### What arch are you using?

x64

### Last Known Working Electron version

25.4.0

### Expected Behavior

It should open new tab

### Actual Behavior

Unexpected closed and stopped working

### Additional Information

I can provide the code source and sentry log through your email.

**Comment by ductridev** [comment]
Just drop your email, I only can share details through contributors' email.
Many thanks.

**Comment by ductridev** [comment]
![image](https://github.com/electron/electron/assets/49811496/21bc9a8a-ced7-4249-9a7c-77a79b5b5882)
![image](https://github.com/electron/electron/assets/49811496/7dcd8852-f50a-4e02-b7a7-e1df6603fd79)
There is 2 images for the errors. Drop your email if you need to access to full logs.
Many thanks.

**Comment by ductridev** [comment]
More details which I think necessary:
[13468:1001/082147.337:INFO:CONSOLE(1)] "MetaMask initialization complete.", source: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js (1)
(node:13468) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:13468) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:13468) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[4084:1001/082158.610:WARNING:backend_impl.cc(1816)] Destroying invalid entry.
Checking for update
[4084:1001/082158.613:WARNING:backend_impl.cc(1816)] Destroying invalid entry.
I think the problem is with upstream chromium content shell which is mentioned [here](https://github.com/nwjs/nw.js/issues/25) causing a segmentation fault.

**Comment by ductridev** [comment]
The issue is solved by clearing the old cache of the application.

**Comment by faisal-aali** [comment]
Hi @ductridev, 
I'm encountering the same issue. How can I effectively clear cache of electron application?
Should I remove cache directories from OS or from Debug console's Applications Tab?

Thanks.
