### ISSUE TITLE
[Bug]: electron disable gpu

### ISSUE THREAD

**Issue by killghost** [electron/electron#40052]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Expected Behavior

Electron error, this problem has been around for a very, very long time, I sincerely hope you can solve it. The problem is this. Electron just opens a very simple page, and electron cannot be started on some computers. The UI interface cannot be displayed normally. At this time, if you disable gpu, the UI interface can be displayed normally. I really hope you can resolve this issue. If possible, I can provide a computer for you to debug remotely. Or give you a dump.

### Actual Behavior

UI show a page

Electron error, this problem has been around for a very, very long time, I sincerely hope you can solve it. The problem is this. Electron just opens a very simple page, and electron cannot be started on some computers. The UI interface cannot be displayed normally. At this time, if you disable gpu, the UI interface can be displayed normally. I really hope you can resolve this issue. If possible, I can provide a computer for you to debug remotely. Or give you a dump.

### Testcase Gist URL

http://testURL.com

### Additional Information

test test test

**Comment by killghost** [comment]
Not only this version, but every version I have used has this problem. This appears among our users. We all ask users to disable gpu

**Comment by killghost** [comment]
Not only this version, but every version I have used has this problem. This appears among our users. We all ask users to disable gpu

**Comment by killghost** [comment]
open

**Comment by killghost** [comment]
Electron error, this problem has been around for a very, very long time, I sincerely hope you can solve it. The problem is this. Electron just opens a very simple page, and electron cannot be started on some computers. The UI interface cannot be displayed normally. At this time, if you disable gpu, the UI interface can be displayed normally. I really hope you can resolve this issue. If possible, I can provide a computer for you to debug remotely. Or give you a dump.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
