### ISSUE TITLE
[Bug]: Crash with access violations

### ISSUE THREAD

**Issue by arunnadesh** [electron/electron#40084]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

NA

### Expected Behavior

Electron doesn't creash

### Actual Behavior

Electron crashes

Found electron crashes with below back traces on multiple occasions during automation test runs. Unable to identify the exact scenario leading to this crash. Would like to know if similar issue has been observed by the community and any possible fixes.

1. 
OS Version: Windows 10.0.22621 
Application Specific Information:
Fatal Error: EXCEPTION_ACCESS_VIOLATION_READ / 0xffffffffffffffff
Thread 5912 Crashed:
0   app.exe                 0x7ff783fb7241      [inlined] uv__loop_alive (core.c:595)
1   app.exe                 0x7ff783fb7241      uv_run (core.c:611)
2   app.exe                 0x7ff78584d1f0      v8::internal::interpreter::BytecodeArrayBuilder::ToBytecodeArray<T> (bytecode-array-builder.cc:99)
3   app.exe                 0x7ff785756105      v8::internal::Factory::AllocateRaw (factory.cc:338)
4   app.exe                 0x7ff78564881b      v8::internal::FactoryBase<T>::NewByteArray (factory-base.cc:226)
5   app.exe                 0x7ff78572ffb0      v8::internal::SourcePositionTableBuilder::AddPosition (source-position-table.cc:161)
6   app.exe                 0x7ff782e0903e      v8::internal::SourcePositionTableBuilder::ToSourcePositionTable<T> (source-position-table.cc:194)
7   app.exe                 0x7ff782e97769      v8::internal::interpreter::BytecodeArrayWriter::ToSourcePositionTable<T> (bytecode-array-writer.cc:70)
8   app.exe                 0x7ff789a6eb97      _tailMerge_winusb.dll
9   app.exe                 0x7ff782e91993      v8::internal::interpreter::BytecodeArrayBuilder::ToSourcePositionTable<T> (bytecode-array-builder.cc:122)
10  app.exe                 0x7ff782e99a77      v8::internal::interpreter::BytecodeGenerator::FinalizeSourcePositionTable<T> (bytecode-generator.cc:1252)
11  app.exe                 0x7ff78586787f      v8::internal::interpreter::InterpreterCompilationJob::FinalizeJobImpl (interpreter.cc:257)
12  app.exe                 0x7ff7858560a4      [inlined] v8::internal::interpreter::BytecodeGenerator::set_execution_context (bytecode-generator.h:470)
13  app.exe                 0x7ff7858560a4      [inlined] v8::internal::interpreter::BytecodeGenerator::ContextScope::~ContextScope (bytecode-generator.cc:76)
14  app.exe                 0x7ff7858560a4      v8::internal::interpreter::BytecodeGenerator::GenerateBytecode (bytecode-generator.cc:1399)
15  app.exe                 0x7ff789a6eb87      _tailMerge_winusb.dll
16  app.exe                 0x7ff785756105      v8::internal::Factory::AllocateRaw (factory.cc:338)
17  app.exe                 0x7ff7859a4567      v8::internal::AccountingAllocator::AllocateSegment (accounting-allocator.cc:95)
18  app.exe                 0x7ff785d2099f      base::internal::PartitionMalloc (allocator_shim_default_dispatch_to_partition_alloc.cc:302)
19  app.exe                 0x7ff78564979a      [inlined] v8::internal::HandleBase::HandleBase (handles-inl.h:21)
20  app.exe                 0x7ff78564979a      [inlined] v8::internal::Handle<T>::Handle (handles-inl.h:52)
21  app.exe                 0x7ff78564979a      [inlined] v8::internal::handle (handles-inl.h:64)
22  app.exe                 0x7ff78564979a      v8::internal::FactoryBase<T>::NewFeedbackMetadata (factory-base.cc:548)
23  app.exe                 0x7ff7859a45d4      v8::internal::AccountingAllocator::ReturnSegment (accounting-allocator.cc:115)
24  app.exe                 0x7ff7859a46ad      [inlined] v8::internal::Zone::ReleaseSegment (zone.cc:128)
25  app.exe                 0x7ff7859a46ad      [inlined] v8::internal::Zone::DeleteAll (zone.cc:113)
26  app.exe                 0x7ff7859a46ad      v8::internal::Zone::~Zone (zone.cc:41)
27  app.exe                 0x7ff785867f1e      v8::internal::interpreter::InterpreterCompilationJob::~InterpreterCompilationJob (interpreter.cc:35)
28  app.exe                 0x7ff78572a2bc      v8::internal::`anonymous namespace'::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs<T> (compiler.cc:865)
29  app.exe                 0x7ff7859a45d4      [inlined] v8::internal::AccountingAllocator::ReturnSegment (accounting-allocator.cc:115)
30  app.exe                 0x7ff7859a45d4      v8::internal::AccountingAllocator::ReturnSegment (accounting-allocator.cc:115)
31  app.exe                 0x7ff785741fab      [inlined] v8::internal::ExecutionAccess::Lock (isolate.h:2537)
32  app.exe                 0x7ff785741fab      [inlined] v8::internal::ExecutionAccess::ExecutionAccess (isolate.h:2533)
33  app.exe                 0x7ff785741fab      v8::internal::StackGuard::PopInterruptsScope (stack-guard.cc:108)
34  app.exe                 0x7ff785da225b      v8::base::TimeTicks::Now (time.cc:715)
35  app.exe                 0x7ff785904054      [inlined] v8::internal::ReusableUnoptimizedCompileState::NotifySingleParseCompleted (parse-info.h:199)
36  app.exe                 0x7ff785904054      v8::internal::ParseInfo::~ParseInfo (parse-info.cc:245)
37  app.exe                 0x7ff785728993      [inlined] v8::internal::Isolate::set_current_vm_state (isolate.h:1375)
38  app.exe                 0x7ff785728993      [inlined] v8::internal::VMState<T>::~VMState (vm-state-inl.h:51)
39  app.exe                 0x7ff785728993      v8::internal::Compiler::Compile (compiler.cc:2062)
40  app.exe                 0x7ff785d12c50      base::sequence_manager::internal::TaskQueueImpl::TaskRunner::PostDelayedTask (task_queue_impl.cc:145)
41  app.exe                 0x7ff78a22a395      _tailMerge_winusb.dll
42  app.exe                 0x7ff785f3ba3a      blink::LayoutObject::UpdateFillImages (layout_object.cc:3043)
43  app.exe                 0x7ff785f3b803      blink::LayoutObject::UpdateFirstLineImageObservers (layout_object.cc:2662)
44  app.exe                 0x7ff7898e6c77      _tailMerge_winusb.dll
45  app.exe                 0x7ff785f3b803      blink::LayoutObject::UpdateFirstLineImageObservers (layout_object.cc:2662)
46  app.exe                 0x7ff7858f3f6f      v8::internal::String::MakeThin<T> (string.cc:188)
47  app.exe                 0x7ff789ee4892      _tailMerge_winusb.dll
48  app.exe                 0x7ff7858f366a      v8::internal::StringTable::TryStringToIndexOrLookupExisting (string-table.cc:785)
49  app.exe                 0x7ff7858951bd      v8::internal::JSFunction::InitializeFeedbackCell (js-function.cc:618)
50  app.exe                 0x7ff7858ec0b4      v8::internal::SharedFunctionInfo::GetCode (shared-function-info.cc:118)
51  app.exe                 0x7ff78572aaff      v8::internal::Compiler::Compile (compiler.cc:2096)
52  app.exe                 0x7ff785dd7b22      base::PendingTask::PendingTask (pending_task.cc:23)

2. 
OS Version: Windows 10.0.22621 
Application Specific Information:
Fatal Error: EXCEPTION_ACCESS_VIOLATION_READ / 0xffffffffffffffff

Thread 20188 Crashed:
0   app.exe                 0x7ff74d0fbdb1      [inlined] uv__loop_alive (core.c:595)
1   app.exe                 0x7ff74d0fbdb1      uv_run (core.c:611)
2   app.exe                 0x7ff74f089e4a      blink::LayoutObject::UpdateFillImages (layout_object.cc:3043)
3   app.exe                 0x7ff74f089c13      blink::LayoutObject::UpdateFirstLineImageObservers (layout_object.cc:2662)
4   app.exe                 0x7ff74f1792f4      blink::LayoutObjectChildList::RemoveChildNode (layout_object_child_list.cc:161)
5   app.exe                 0x7ff74e20b58c      blink::LayoutSVGContainer::RemoveChild (layout_svg_container.cc:121)
6   app.exe                 0x7ff74f13f788      [inlined] cppgc::internal::PersistentBase::GetValue (persistent.h:31)
7   app.exe                 0x7ff74f13f788      [inlined] cppgc::internal::BasicPersistent<T>::Get (persistent.h:194)
8   app.exe                 0x7ff74f13f788      [inlined] cppgc::internal::BasicPersistent<T>::operator* (persistent.h:185)
9   app.exe                 0x7ff74f13f788      blink::NodeRenderingData::SharedEmptyData (node_rare_data.cc:113)
10  app.exe                 0x7ff74e20b87a      blink::LayoutSVGModelObject::WillBeDestroyed (layout_svg_model_object.cc:106)
11  app.exe                 0x7ff74eff6fe5      [inlined] blink::NodeRenderingData::IsSharedEmptyData (node_rare_data.h:164)
12  app.exe                 0x7ff74eff6fe5      blink::Node::SetComputedStyle (node.cc:1071)
13  app.exe                 0x7ff74f089e4a      blink::LayoutObject::UpdateFillImages (layout_object.cc:3043)
14  app.exe                 0x7ff74f089c13      blink::LayoutObject::UpdateFirstLineImageObservers (layout_object.cc:2662)
15  app.exe                 0x7ff74f1792f4      blink::LayoutObjectChildList::RemoveChildNode (layout_object_child_list.cc:161)
16  app.exe                 0x7ff74e20b58c      blink::LayoutSVGContainer::RemoveChild (layout_svg_container.cc:121)
17  app.exe                 0x7ff74f1792f4      blink::LayoutObjectChildList::RemoveChildNode (layout_object_child_list.cc:161)
18  app.exe                 0x7ff74e20b87a      blink::LayoutSVGModelObject::WillBeDestroyed (layout_svg_model_object.cc:106)
19  app.exe                 0x7ff74eff6fe5      [inlined] blink::NodeRenderingData::IsSharedEmptyData (node_rare_data.h:164)
20  app.exe                 0x7ff74eff6fe5      blink::Node::SetComputedStyle (node.cc:1071)
21  app.exe                 0x7ff74ef263e2      base::PendingTask::PendingTask (pending_task.cc:23)
22  app.exe                 0x7ff74f089c13      blink::LayoutObject::UpdateFirstLineImageObservers (layout_object.cc:2662)
23  app.exe                 0x7ff74ee66023      [inlined] base::internal::PlatformThreadLocalStorage::GetTLSValue (thread_local_storage.h:70)
24  app.exe                 0x7ff74ee66023      [inlined] `anonymous namespace'::GetTlsVectorStateAndValue (thread_local_storage.cc:242)
25  app.exe                 0x7ff74ee66023      base::ThreadLocalStorage::Slot::Get (thread_local_storage.cc:473)
26  app.exe                 0x7ff74ee66067      [inlined] base::internal::PlatformThreadLocalStorage::GetTLSValue (thread_local_storage.h:70)
27  app.exe                 0x7ff74ee66067      [inlined] `anonymous namespace'::GetTlsVectorStateAndValue (thread_local_storage.cc:242)
28  app.exe                 0x7ff74ee66067      base::ThreadLocalStorage::Slot::Set (thread_local_storage.cc:488)
29  app.exe                 0x7ff74ee66023      [inlined] base::internal::PlatformThreadLocalStorage::GetTLSValue (thread_local_storage.h:70)
30  app.exe                 0x7ff74ee66023      [inlined] `anonymous namespace'::GetTlsVectorStateAndValue (thread_local_storage.cc:242)
31  app.exe                 0x7ff74ee66023      base::ThreadLocalStorage::Slot::Get (thread_local_storage.cc:473)
32  app.exe                 0x7ff74cb2b112      base::TaskAnnotator::WillQueueTask (task_annotator.cc:91)
33  app.exe                 0x7ff74ee59d65      base::ScopedDeferTaskPosting::~ScopedDeferTaskPosting (scoped_defer_task_posting.cc:74)
34  app.exe                 0x7ff74ef259d4      [inlined] base::internal::WeakPtrBase::WeakPtrBase (weak_ptr.h:164)
35  app.exe                 0x7ff74ef259d4      [inlined] base::WeakPtr<T>::WeakPtr (weak_ptr.h:237)
36  app.exe                 0x7ff74ef259d4      base::sequence_manager::Task::Task (tasks.cc:47)
37  app.exe                 0x7ff74ef25940      base::sequence_manager::internal::PostedTask::~PostedTask (tasks.cc:144)
38  app.exe                 0x7ff74ee61510      base::sequence_manager::internal::TaskQueueImpl::TaskRunner::PostDelayedTask (task_queue_impl.cc:145)
39  app.exe                 0x7ff74f1792f4      [inlined] blink::LayoutObjectChildList::RemoveChildNode (layout_object_child_list.cc:161)
40  app.exe                 0x7ff74f1792f4      blink::LayoutObjectChildList::RemoveChildNode (layout_object_child_list.cc:161)
41  app.exe                 0x7ff74eff6fe5      [inlined] blink::NodeRenderingData::IsSharedEmptyData (node_rare_data.h:164)
42  app.exe                 0x7ff74eff6fe5      blink::Node::SetComputedStyle (node.cc:1071)
43  app.exe                 0x7ff7530be02c      _tailMerge_winusb.dll
44  app.exe                 0x7ff753375cd5      _tailMerge_winusb.dll
45  app.exe                 0x7ff74ee93a75      [inlined] mojo::SimpleWatcher::Context::Notify (simple_watcher.cc:101)
46  app.exe                 0x7ff74ee93a75      mojo::SimpleWatcher::Context::CallNotify (simple_watcher.cc:61)
47  app.exe                 0x7ff7530be02c      _tailMerge_winusb.dll
48  app.exe                 0x7ff753375cd5      _tailMerge_winusb.dll
49  app.exe                 0x7ff74ee93a75      [inlined] mojo::SimpleWatcher::Context::Notify (simple_watcher.cc:101)
50  app.exe                 0x7ff74ee93a75      mojo::SimpleWatcher::Context::CallNotify (simple_watcher.cc:61)
51  app.exe                 0x7ff74ee704d6      base::internal::PartitionAlignedAlloc (allocator_shim_default_dispatch_to_partition_alloc.cc:340)
52  app.exe                 0x7ff74e982bca      v8::internal::LoadIC::ComputeHandler (ic.cc:1227)
53  app.exe                 0x7ff74ea29060      v8::internal::Object::GetProperty (objects.cc:1189)
54  app.exe                 0x7ff7530be02c      _tailMerge_winusb.dll
55  app.exe                 0x7ff753375cd5      _tailMerge_winusb.dll
56  app.exe                 0x7ff74ee93a75      [inlined] mojo::SimpleWatcher::Context::Notify (simple_watcher.cc:101)
57  app.exe                 0x7ff74ee93a75      mojo::SimpleWatcher::Context::CallNotify (simple_watcher.cc:61)
58  app.exe                 0x7ff74ea10491      v8::internal::LookupIterator::GetDataValue (lookup.cc:1058)
59  app.exe                 0x7ff74ee6f25f      base::internal::PartitionMalloc (allocator_shim_default_dispatch_to_partition_alloc.cc:302)
60  app.exe                 0x7ff74e8afa41      [inlined] v8::internal::HandleBase::HandleBase (handles-inl.h:21)
61  app.exe                 0x7ff74e8afa41      [inlined] v8::internal::Handle<T>::Handle (handles-inl.h:52)
62  app.exe                 0x7ff74e8afa41      [inlined] v8::internal::handle (handles-inl.h:64)
63  app.exe                 0x7ff74e8afa41      v8::internal::Factory::NewLoadHandler (factory.cc:3561)
64  app.exe                 0x7ff74ea29d7b      [inlined] v8::internal::HandleScope::CreateHandle (handles-inl.h:175)
65  app.exe                 0x7ff74ea29d7b      [inlined] v8::internal::HandleScope::GetHandle (handles-inl.h:186)
66  app.exe                 0x7ff74ea29d7b      [inlined] v8::internal::HandleBase::HandleBase (handles-inl.h:21)
67  app.exe                 0x7ff74ea29d7b      [inlined] v8::internal::Handle<T>::Handle (handles-inl.h:52)
68  app.exe                 0x7ff74ea29d7b      [inlined] v8::internal::handle (handles-inl.h:64)
69  app.exe                 0x7ff74ea29d7b      v8::internal::Object::GetProperty (objects.cc:1156)
70  app.exe                 0x7ff74ea207b5      v8::internal::Map::GetOrCreatePrototypeChainValidityCell (map.cc:2267)
71  app.exe                 0x7ff75331704f      _tailMerge_winusb.dll
72  app.exe                 0x7ff74e9da732      [inlined] v8::base::SharedMutexGuard<T>::~SharedMutexGuard (mutex.h:344)
73  app.exe                 0x7ff74e9da732      [inlined] v8::internal::NexusConfig::SetFeedbackPair (feedback-vector.cc:517)
74  app.exe                 0x7ff74e9da732      [inlined] v8::internal::FeedbackNexus::SetFeedback (feedback-vector-inl.h:488)
75  app.exe                 0x7ff74e9da732      v8::internal::FeedbackNexus::ConfigureMegamorphic (feedback-vector.cc:680)
76  app.exe                 0x7ff74e99c617      [inlined] std::Cr::__cxx_atomic_fetch_add (atomic:1004)
77  app.exe                 0x7ff74e99c617      [inlined] std::Cr::__atomic_base<T>::fetch_add (atomic:1682)
78  app.exe                 0x7ff74e99c617      [inlined] v8::internal::StatsCounter::Increment (counters.h:107)
79  app.exe                 0x7ff74e99c617      v8::internal::StubCache::Set (stub-cache.cc:109)
80  app.exe                 0x7ff74e98577e      v8::internal::KeyedLoadIC::Load (ic.cc:1595)
81  app.exe                 0x7ff75331704f      _tailMerge_winusb.dll

3. OS Version: Windows 10.0.22621 (2361)

Application Specific Information:
Fatal Error: EXCEPTION_ACCESS_VIOLATION_READ / 0xffffffffffffffff

Thread 13952 Crashed:
0   app.exe                 0x7ff6ae9b7241      [inlined] uv__loop_alive (core.c:595)
1   app.exe                 0x7ff6ae9b7241      uv_run (core.c:611)
2   app.exe                 0x7ff6b024d1f0      v8::internal::interpreter::BytecodeArrayBuilder::ToBytecodeArray<T> (bytecode-array-builder.cc:99)
3   app.exe                 0x7ff6b0156105      v8::internal::Factory::AllocateRaw (factory.cc:338)
4   app.exe                 0x7ff6b004881b      v8::internal::FactoryBase<T>::NewByteArray (factory-base.cc:226)
5   app.exe                 0x7ff6b012ffb0      v8::internal::SourcePositionTableBuilder::AddPosition (source-position-table.cc:161)
6   app.exe                 0x7ff6ad80903e      v8::internal::SourcePositionTableBuilder::ToSourcePositionTable<T> (source-position-table.cc:194)
7   app.exe                 0x7ff6ad897769      v8::internal::interpreter::BytecodeArrayWriter::ToSourcePositionTable<T> (bytecode-array-writer.cc:70)
8   app.exe                 0x7ff6b446eb97      _tailMerge_winusb.dll
9   app.exe                 0x7ff6ad891993      v8::internal::interpreter::BytecodeArrayBuilder::ToSourcePositionTable<T> (bytecode-array-builder.cc:122)
10  app.exe                 0x7ff6ad899a77      v8::internal::interpreter::BytecodeGenerator::FinalizeSourcePositionTable<T> (bytecode-generator.cc:1252)
11  app.exe                 0x7ff6b026787f      v8::internal::interpreter::InterpreterCompilationJob::FinalizeJobImpl (interpreter.cc:257)
12  app.exe                 0x7ff6b02560a4      [inlined] v8::internal::interpreter::BytecodeGenerator::set_execution_context (bytecode-generator.h:470)
13  app.exe                 0x7ff6b02560a4      [inlined] v8::internal::interpreter::BytecodeGenerator::ContextScope::~ContextScope (bytecode-generator.cc:76)
14  app.exe                 0x7ff6b02560a4      v8::internal::interpreter::BytecodeGenerator::GenerateBytecode (bytecode-generator.cc:1399)
15  app.exe                 0x7ff6b446eb87      _tailMerge_winusb.dll
16  app.exe                 0x7ff6b0156105      v8::internal::Factory::AllocateRaw (factory.cc:338)
17  app.exe                 0x7ff6b03a4567      v8::internal::AccountingAllocator::AllocateSegment (accounting-allocator.cc:95)
18  app.exe                 0x7ff6b072099f      base::internal::PartitionMalloc (allocator_shim_default_dispatch_to_partition_alloc.cc:302)
19  app.exe                 0x7ff6b004979a      [inlined] v8::internal::HandleBase::HandleBase (handles-inl.h:21)
20  app.exe                 0x7ff6b004979a      [inlined] v8::internal::Handle<T>::Handle (handles-inl.h:52)
21  app.exe                 0x7ff6b004979a      [inlined] v8::internal::handle (handles-inl.h:64)
22  app.exe                 0x7ff6b004979a      v8::internal::FactoryBase<T>::NewFeedbackMetadata (factory-base.cc:548)
23  app.exe                 0x7ff6b03a45d4      v8::internal::AccountingAllocator::ReturnSegment (accounting-allocator.cc:115)
24  app.exe                 0x7ff6b03a46ad      [inlined] v8::internal::Zone::ReleaseSegment (zone.cc:128)
25  app.exe                 0x7ff6b03a46ad      [inlined] v8::internal::Zone::DeleteAll (zone.cc:113)
26  app.exe                 0x7ff6b03a46ad      v8::internal::Zone::~Zone (zone.cc:41)
27  app.exe                 0x7ff6b0267f1e      v8::internal::interpreter::InterpreterCompilationJob::~InterpreterCompilationJob (interpreter.cc:35)
28  app.exe                 0x7ff6b012a2bc      v8::internal::`anonymous namespace'::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs<T> (compiler.cc:865)
29  app.exe                 0x7ff6b03a45d4      [inlined] v8::internal::AccountingAllocator::ReturnSegment (accounting-allocator.cc:115)
30  app.exe                 0x7ff6b03a45d4      v8::internal::AccountingAllocator::ReturnSegment (accounting-allocator.cc:115)
31  app.exe                 0x7ff6b0141fab      [inlined] v8::internal::ExecutionAccess::Lock (isolate.h:2537)
32  app.exe                 0x7ff6b0141fab      [inlined] v8::internal::ExecutionAccess::ExecutionAccess (isolate.h:2533)
33  app.exe                 0x7ff6b0141fab      v8::internal::StackGuard::PopInterruptsScope (stack-guard.cc:108)
34  app.exe                 0x7ff6b07a225b      v8::base::TimeTicks::Now (time.cc:715)
35  app.exe                 0x7ff6b0304054      [inlined] v8::internal::ReusableUnoptimizedCompileState::NotifySingleParseCompleted (parse-info.h:199)
36  app.exe                 0x7ff6b0304054      v8::internal::ParseInfo::~ParseInfo (parse-info.cc:245)
37  app.exe                 0x7ff6b0128993      [inlined] v8::internal::Isolate::set_current_vm_state (isolate.h:1375)
38  app.exe                 0x7ff6b0128993      [inlined] v8::internal::VMState<T>::~VMState (vm-state-inl.h:51)
39  app.exe                 0x7ff6b0128993      v8::internal::Compiler::Compile (compiler.cc:2062)
40  app.exe                 0x7ff6b0712c50      base::sequence_manager::internal::TaskQueueImpl::TaskRunner::PostDelayedTask (task_queue_impl.cc:145)
41  app.exe                 0x7ff6b4c2a395      _tailMerge_winusb.dll
42  app.exe                 0x7ff6b093ba3a      blink::LayoutObject::UpdateFillImages (layout_object.cc:3043)
43  app.exe                 0x7ff6b093b803      blink::LayoutObject::UpdateFirstLineImageObservers (layout_object.cc:2662)
44  app.exe                 0x7ff6b42e6c77      _tailMerge_winusb.dll
45  app.exe                 0x7ff6b093b803      blink::LayoutObject::UpdateFirstLineImageObservers (layout_object.cc:2662)
46  app.exe                 0x7ff6b02f3f6f      v8::internal::String::MakeThin<T> (string.cc:188)
47  app.exe                 0x7ff6b48e4892      _tailMerge_winusb.dll
48  app.exe                 0x7ff6b02f366a      v8::internal::StringTable::TryStringToIndexOrLookupExisting (string-table.cc:785)
49  app.exe                 0x7ff6b02951bd      v8::internal::JSFunction::InitializeFeedbackCell (js-function.cc:618)
50  app.exe                 0x7ff6b02ec0b4      v8::internal::SharedFunctionInfo::GetCode (shared-function-info.cc:118)
51  app.exe                 0x7ff6b012aaff      v8::internal::Compiler::Compile (compiler.cc:2096)
52  app.exe                 0x7ff6b07d7b22      base::PendingTask::PendingTask (pending_task.cc:23)

### Testcase Gist URL

NA

### Additional Information

NA

**Comment by codebytere** [comment]
@arunnadesh we can try but without any type of repro or information about circumstances surrounding this crash we aren't likely to get far.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
