### ISSUE TITLE
[Bug]: desktopCapturer source IDs are valid for a single use on Wayland

### ISSUE THREAD

**Issue by aiddya** [electron/electron#40097]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0-beta.9

### What operating system are you using?

Other Linux

### Operating System Version

Fedora Workstation 39

### What arch are you using?

x64

### Expected Behavior

1. Get a source ID from desktopCapturer
2. Display the stream using getUserMedia
3. Stop the stream
4. Display the stream again using getUserMedia

### Actual Behavior

XDG desktop portal permission dialog appears again

### Testcase Gist URL

https://gist.github.com/aiddya/cfd89d040661e0553425e4203ce4512b

### Additional Information

The fiddle has a timeout function that displays the stream after 10 seconds. So the steps to test using the fiddle boil down to: select a source, preview it, stop it and then wait 10 seconds.

**Comment by ProdigyView** [comment]
I am actually have the same issue on windows on version v26.3.0.
