### ISSUE TITLE
[Bug]: macOS menu closes when using `role:  'Help'`

### ISSUE THREAD

**Issue by bpasero** [electron/electron#40099]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.x

### What operating system are you using?

macOS

### Operating System Version

13.6

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When a macOS main menu is opened, updating the menu should not close it. Especially when the items do not change.

### Actual Behavior

A macOS menu with `role:  'Help'` closes when rebuilding the menu.

### Testcase Gist URL

https://gist.github.com/rssowlreader/4361bfa113ebb95102a36695c4679685

### Additional Information

In the Fiddle, run the app, click into Help and wait for 3 seconds until the menu is rebuild. The menu will close.

**Comment by codebytere** [comment]
@bpasero this unfortunately isn't a bug inasfar as a feature request - it's default functionality of menus on macOS. There's never been a way to allow dynamic menu updating via public APIs. I'm folding this into https://github.com/electron/electron/issues/528 - i do believe it's possible but as of now only by messing with fairly low-level functionality discouraged by Apple.

See https://twitter.com/sindresorhus/status/1186958149036568576?s=20 for a bit more context

**Comment by bpasero** [comment]
Yeah I understand, however in this case the contents of the menu are not changing at all.
