### ISSUE TITLE
[Bug]: `desktopCapturer.getSources` returns different payloads in fullScreen vs normal version on MacOS.

### ISSUE THREAD

**Issue by MohammedTaha** [electron/electron#40102]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.1

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.4

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

In order to let users share their screen, we are using `desktopCapturer.getSources` to get the list of available windows and screens. The user can then select one of the available item n rest of the routine works to share their screen.

```
desktopCapturer.getSources({
  types: ["window", "screen"],
  thumbnailSize: { width: numX, height: numY },
});
```

On MacOs (irrespective of version), if the user is using the app in full screen mode (using the green traffic light button on top left) and invoke this `desktopCapturer.getSources` method, the returned value is different than the list being returned when app is being used in normal mode.

Shouldn't it return the same list in both modes?

<img width="398" alt="image" src="https://github.com/electron/electron/assets/3276864/e5f8c643-153a-4ef8-a56b-dd691a78891e">

### Actual Behavior

- If the app is running in normal mode, `desktopCapturer.getSources` resolves with the list of all available screens and windows.
- If the app is running in full screen mode (again, the green traffic light button in the title bar, on top left of the screen), `desktopCapturer.getSources` resolves with the list of all available screens but ignore all other windows (other running apps)except this app.

**Comment by bemniller** [comment]
Unfortunately, I believe this is a known issue with how Apple devices handle applications when they enter Full-Screen mode. In MacOS, a Full-Screened application is moved to its own "Virtual Desktop" which then restricts access to other open applications. You would have to switch back to the original "Virtual Desktop" to record another application. Many people appear to find this challenging.

https://discussions.apple.com/thread/254547879
https://www.quora.com/Why-do-full-screen-Mac-apps-create-their-own-desktop-space
