### ISSUE TITLE
Get Taskbar position (& size), Windows

### ISSUE THREAD

**Issue by black-snow** [electron/electron#4010]
Currently (0.36.0) it seems to be impossible to position a window next to the tray area (think of dropbox) for one cannot tell where the user has put his taskbar. It could be on top, bottom, left or right (plus additional screens). Electron doesn't provide information on where the taskbar is or how big it is (or if its currently visible), right?

I'd really appreciate having this so that projects like https://github.com/jenslind/electron-positioner/ can provide a simple way to move BrowserWindows to the tray area.

Google turns up plenty resources on how to get the taskbar position/size (e. g. http://stackoverflow.com/questions/1264406/how-do-i-get-the-taskbars-position-and-size). Sadly my C++ knowledge is pretty much nil so I can't file a PR for this.

**Comment by felixrieseberg** [comment]
I'm not sure that this should be a part of Electron. Instead, you could make a little Node module that uses ffi or a little console application to figure this out.

**Comment by black-snow** [comment]
@felixrieseberg Do you know if anything's changed here since 0.36?

**Comment by codebytere** [comment]
I don't believe it has, no.
