### ISSUE TITLE
[Bug]: Close browser view destroy the browser window

### ISSUE THREAD

**Issue by laux98** [electron/electron#40123]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.2 LTS

### What arch are you using?

x64

### Last Known Working Electron version

Never

### Expected Behavior

Hello, 

For my electron projet, I want to put a BrowserView() in a BrowserWindow() .

### Actual Behavior

The problem is, when I close the browserView, the browser window is destroyed. 

### Additional Information

So to start, I declare my mainWindow and put an url inside , and open the dev tools. 

```
const browserWindowOpts = Object.assign({}, cdvElectronSettings.browserWindow, {
    icon: appIcon,
    nativeWindowOpen: true,
  });
  browserWindowOpts.webPreferences.preload = path.join(app.getAppPath(), "cdv-electron-preload.js");
  browserWindowOpts.webPreferences.contextIsolation = true;

let mainWindow = new BrowserWindow(browserWindowOpts);
// Load a local HTML file or a remote URL.
  const cdvUrl = cdvElectronSettings.browserWindowInstance.loadURL.url;
  const loadUrl = cdvUrl.includes("://") ? cdvUrl : `${basePath}/${cdvUrl}`;
  const loadUrlOpts = Object.assign({}, cdvElectronSettings.browserWindowInstance.loadURL.options);

  mainWindow.loadURL(loadUrl, loadUrlOpts);

  // Open the DevTools.
  if (cdvElectronSettings.browserWindow.webPreferences.devTools) {
    mainWindow.webContents.openDevTools();
  }
```

And this is my function when I open the browserView (the browser view open succesffuly).

```
async function handleOpenUrl(event, url) {

  //Create the browserView and give her the same dimensions as my screen
  view = new BrowserView();
  mainWindow.setBrowserView(view);
  const primaryDisplay = screen.getPrimaryDisplay();
  const { width, height } = primaryDisplay.workAreaSize;
  view.setBounds({ x: 0, y: 0, width: width, height: height });
  
}
```

So, at this moment, browser view is open, but when i close her, my application crash. 

My question is : what it the cleanest way to close a browser view withouth destroying the main window ?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
