### ISSUE TITLE
[Bug]: Window Animitions disappear when use "transparent: true"

### ISSUE THREAD

**Issue by yuzh0816** [electron/electron#40121]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Version 23H2

### What arch are you using?

x64

### Expected Behavior

Have window animitions when minimize/maxmize the window.

### Actual Behavior

Don't have window animitions when minimize/maxmize the window.

**Comment by codebytere** [comment]
@yuzh0816:

>  https://github.com/Sherlockouo/music

This does not address the request in https://github.com/electron/electron/issues/40121#issuecomment-1752146664 - we need a _standalone_ reproducible sample and not a  larger app.

As specified above, stand-alone test cases make fixing issues go more smoothly: they ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by KochiyaOcean** [comment]
For my case, it happens when the `frame` is set to `false` and `transparent` is set to `true`

Here is the gist to reproduce https://gist.github.com/KochiyaOcean/b6313e134a5ae42a2c47cf2c28e831d3

**Comment by yuzh0816** [comment]
> For my case, it happens when the `frame` is set to `false` and `transparent` is set to `true`
> 
> Here is the gist to reproduce https://gist.github.com/KochiyaOcean/b6313e134a5ae42a2c47cf2c28e831d3

Sorry, but I don't know how to reproduce with this, can you offer more detailed instructions?

**Comment by yuzh0816** [comment]
> > > For my case, it happens when the `frame` is set to `false` and `transparent` is set to `true`
> > > Here is the gist to reproduce https://gist.github.com/KochiyaOcean/b6313e134a5ae42a2c47cf2c28e831d3
> > 
> > 
> > Sorry, but I don't know how to reproduce with this, can you offer more detailed instructions?
> 
> You can load the gist link above using electron-fiddle and start it. The window will maximumize and unmaximumize at an interval and you can confirm if the window animation exists

Yes, this is also my issue. Completely the same.

**Comment by yuzh0816** [comment]
> @yuzh0816:
> 
> > https://github.com/Sherlockouo/music
> 
> This does not address the request in [#40121 (comment)](https://github.com/electron/electron/issues/40121#issuecomment-1752146664) - we need a _standalone_ reproducible sample and not a larger app.
> 
> As specified above, stand-alone test cases make fixing issues go more smoothly: they ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

@codebytere  The issue is just the same in the gist from @KochiyaOcean.

https://gist.github.com/KochiyaOcean/b6313e134a5ae42a2c47cf2c28e831d3

**Comment by KochiyaOcean** [comment]
I read the code and think the reason is that when transparent is true, the thick frame will be disabled, which removes all animation of window

https://github.com/electron/electron/blob/652f995128de858c7a68fad853f56e80e0c2c222/shell/browser/native_window_views.cc#L240

I'm wondering why we need to disable thick frame, will take a look into it

**Comment by yuzh0816** [comment]
> I read the code and think the reason is that when transparent is true, the thick frame will be disabled, which removes all animation of window
> 
> https://github.com/electron/electron/blob/652f995128de858c7a68fad853f56e80e0c2c222/shell/browser/native_window_views.cc#L238-L241
> 
> I'm wondering why we need to disable thick frame, will take a look into it

Cool, it looks like the origin of the bug. Hope the official will fix it.👀

**Comment by KochiyaOcean** [comment]
I've tried to remove the logic of force disabling thickFrame when transparent is true, and complied a local version to test
The bug seems to be fixed.

Before (27.0.0 release without patch to enable thickFrame)
![image](https://github.com/electron/electron/assets/8194131/82af0294-1cac-463f-86c1-6e06044e07b1)

After (27.0.2 release with patch to enable thickFrame)
![image](https://github.com/electron/electron/assets/8194131/2afa1c5d-45c2-45a2-942c-289df699ab51)

**Comment by yuzh0816** [comment]
Going to close this PR because _https://github.com/electron/electron/pull/40395_ is better solution to the issue
