### ISSUE TITLE
[Bug]: How to use Command+A to disable the configuration in the application menu within an editable element?

### ISSUE THREAD

**Issue by whxcode** [electron/electron#40134]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.4

### What operating system are you using?

Windows

### Operating System Version

macOs Ventura Version 13.1 (22C65)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I configured a Select All action (Command+A) in the application menu; by default it triggers a custom action in the render process.
But within the input, I use Command+A just to trigger the default behavior of the input itself (selecting text); but it will still trigger my custom operations in the rendering process.
I tried to use focusedWebContents.executeJavaScript to get the currently focused node, but I used an iframe; when cross-domain, I cannot directly get the focused node to determine whether the current mouse is on an editable element.

The isEditableElement function cannot work properly when it encounters an iframe that is not of the same origin.
![Uploading image.png…]()

### Actual Behavior

...

**Comment by whxcode** [comment]
The isEditableElement function cannot work properly when it encounters an iframe that is not of the same origin.

<img width="1426" alt="image" src="https://github.com/electron/electron/assets/44012914/a3c7cf6a-bf88-4458-a84e-af1ef90c50de">

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by whxcode** [comment]
I should have gone in the wrong direction before. Now I only care about the focus within the document itself, and block events that occur on the iframe tag. This processing is also in line with my expectations.
Thank you for your attention.

**Comment by whxcode** [comment]
> Thanks for reaching out!
> 
> Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

I should have gone in the wrong direction before. Now I only care about the focus within the document itself, and block events that occur on the iframe tag. This processing is also in line with my expectations.
Thank you for your attention.
