### ISSUE TITLE
[Bug]: screen.getCursorScreenPoint() does not work with a pen tablet when windows ink is enabled

### ISSUE THREAD

**Issue by ryjacky** [electron/electron#40145]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 10.0.22621

### What arch are you using?

x64

### Expected Behavior

screen.getCursorScreenPoint() should return the current cursor position when windows ink is on and the cursor moves between windows that use windows ink. Pen tablet is used.

### Actual Behavior

screen.getCursorScreenPoint() return the last cursor position that the cursor is at before entering the window that uses windows ink

### Additional Information

To reproduce this issue, you need a pentablet, the brand does not matter, windows ink should be enabled.

~~Open some UWP apps or even just chrome (which windows ink could be used I think)~~
Open some WindowsInk-enabled apps or even just chrome (which windows ink could be used I think), 

put the two windows together, 
and log the screen.getCursorScreenPoint() output continuously on your electron app, 
move your pen so the cursor also moves between the two windows opened previously. 
You will noticed how the position only changes when the cursor cross the border.
Even worse, if you have two maximized these kinds of window on two monitor, screen.getCursorScreenPoint() won't even change when your cursor moves cross between the two monitor.

**Comment by codebytere** [comment]
@ryjacky unfortunately we don't implement this ourselves - it's plumbed [straight from Chromium](https://github.com/electron/electron/blob/5931f69f183bfcd57c9dc7dffe8560ac9163bb45/shell/browser/api/electron_api_screen.cc#L87). I recommend opening a [crbug](https://crbug.com/) or searching for existing issues in their tracker. When/if they fix it, we would inherit that fix.
