### ISSUE TITLE
[Bug]: Native '.node' Addon - ERROR:crashpad_client_win.cc

### ISSUE THREAD

**Issue by MrTob** [electron/electron#40141]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2

### What arch are you using?

x64

### Expected Behavior

i wrote a custom '.node' Addon in C++ with an NAPI_MODULE_EXPORT interface.
When i use the addon in an plain nodejs project the addon is working fine.
i use it like this:
```
const addon = require("./native-modules/my-addon.node");
console.log(addon.my_function());
```

### Actual Behavior

No when i include this addon in an electron app and call the addon function i get this error:
`[21064:1009/075829.466:ERROR:crashpad_client_win.cc(844)] not connected`

### Additional Information

i use an "nx" monorepo with Angular as frontend-framework, to load the addon i use the 'node-loader' from webpack
https://webpack.js.org/loaders/node-loader/

**Comment by rafael-castelo** [comment]
Did you get any update on this? I am experiencing the same issue

**Comment by HmingWang** [comment]
I meet the same issue
