### ISSUE TITLE
[Bug]: browserWindow setting show: false does not always take effect

### ISSUE THREAD

**Issue by bayun2** [electron/electron#40155]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.5.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

23.3.24

### Expected Behavior

Create two sub-windows that are hidden by default. When you show one of them, the other is still hidden.

### Actual Behavior

Create two sub-windows that are hidden by default. When you show one of them, the other one is displayed together.

### Testcase Gist URL

https://gist.github.com/e69484336a6e5d418cf12af032f46b4b

**Comment by codebytere** [comment]
Already fixed in https://github.com/electron/electron/pull/40107 - will be out in next release.
