### ISSUE TITLE
[Bug]: openDevTools causes `transparent` window to opaque window

### ISSUE THREAD

**Issue by universeroc** [electron/electron#40156]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.3.0

### What operating system are you using?

macOS

### Operating System Version

13.4.1 (c) (22F770820d)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Keep the BrowserWindow as transparent

### Actual Behavior

Firstly transparent but immediately opaque

### Testcase Gist URL

https://gist.github.com/023bd581db125e5d8f42fa569e23784d

**Comment by codebytere** [comment]
@universeroc while I recognize it's a little confusing, this is not a bug nor has ever worked as you specified. When DevTools is docked and attached to the window, devtools itself will not be transparent nor is that behavior we would want. To ensure the window remains transparent, you should consider opening DevTools in detached mode: 

```js
mainWindow.webContents.openDevTools({ mode: 'detach' })
```
