### ISSUE TITLE
[Bug]: :FATAL:gpu_data_manager_impl_private.cc(440)] GPU process isn't usable. Goodbye

### ISSUE THREAD

**Issue by xiaoxiaohuayu** [electron/electron#40157]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows11 

### What arch are you using?

x64

### Expected Behavior

Run normally and open window

### Actual Behavior

The following error message appears electron executing the command.
<img width="982" alt="image" src="https://github.com/electron/electron/assets/30976418/5f4aa2a2-e7da-48e6-9692-747193ccf903">

**Comment by xiaoxiaohuayu** [comment]
I am running a project in Parallels Desktop. would use such a question

**Comment by codebytere** [comment]
@xiaoxiaohuayu whether the app is being run in Parallels should not make a difference. I run Windows in Parallels as well.
