### ISSUE TITLE
[Bug]: Narrator Cursor not Performing with Mouse Interactions

### ISSUE THREAD

**Issue by jmegginson** [electron/electron#40164]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

When any of the Windows Narrator cursor mouse settings are enabled they should track the mouse (hover) like it does in the Edge browser or all Windows OS screens.

### Actual Behavior

When a user of Windows Narrator enables Mouse cursor settings, the TTS voice output is not announced when mouse events occur over plain static text on web pages. A Narrator user in Electron must use the keyboard for the voice output to be rendered.

### Additional Information

Steps to reproduce:

go to any web page specifically a page with text in electron or a chromium browser
Navigate to Narrator settings via Windows ease of access settings
enable any of the Narrator cursor options; specifically those related to mouse
navigate with the mouse and observe that the narrator cursor does not track to plain (static) text when mouse events occur

Appears to be related to Narrator's reliance on UIAutomation APIs. Similar issues noted here:
https://github.com/electron/electron/issues/11867
https://github.com/electron/electron/issues/28479

**Comment by codebytere** [comment]
> go to any web page specifically a page with text in electron or a chromium browser

Given this is reproducible in Chromium itself, this isn't the right place to file this bug. Please report it upstream at [crbug](https://crbug.com/) and when it is fixed there we will inherit the fix.

**Comment by jmegginson** [comment]
see Issue  #1487592
