### ISSUE TITLE
[Bug]: Encrypted ClientHello is not enabled

### ISSUE THREAD

**Issue by rastiqdev** [electron/electron#40176]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### What arch are you using?

x64

### Expected Behavior

The ECH (Encrypted ClientHello) extension of TLS should be enabled as Electron 27 is based on Chromium 118 and ECH is enabled by default as of Chromium 117, so https://tls-ech.dev should say that ECH is enabled.

### Actual Behavior

https://tls-ech.dev says that ECH is not enabled.

### Testcase Gist URL

https://gist.github.com/rastiqdev/8642f20dcf48adc15cd79b684af15f78

**Comment by codebytere** [comment]
@rastiqdev that's not true, unfortunately - it was shipped as stable in M117 but not enabled by default. It was actually enabled by default in CL:4897260, which was merged on Sept 28th. Checking the [Release Dashboard](https://chromiumdash.appspot.com/commits?commit=d7b0a766146de2f43d2bfc721cf217f7d7784703&platform=Android) for the commit, that default won't be changed until M119.

**Comment by rastiqdev** [comment]
@codebytere Figured out why I was confused. I probably somehow broke my Chrome settings on my computer because ECH was enabled when the flag was set to "Default".
