### ISSUE TITLE
[Bug]: The app fails to open after quit the windowSever process

### ISSUE THREAD

**Issue by rmchen-12** [electron/electron#40170]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

none

### Expected Behavior

The application can be opened normally

### Actual Behavior

App cannot open

### Testcase Gist URL

none

### Additional Information

step1:
Call app.relaunch() in my code.

step2:
close windowServer process，after the windowServer process is closed, the desktop will restarts。
![image](https://github.com/electron/electron/assets/35126234/549f4fab-26d6-4972-a4d7-1f8d5ed3993a)

step3:
The problem arises, after desktop restarts, There will always be an abnormal process, if i call app.requestSingleInstanceLock() in my code, i cannot continue to open app.
![image](https://github.com/electron/electron/assets/35126234/02401a6b-56e3-4f5b-8836-bd20ccb060c6)

**Comment by codebytere** [comment]
@rmchen-12 why are you closing the WindowServer process? That shouldn't be necessary.

**Comment by rmchen-12** [comment]
> @rmchen-12 why are you closing the WindowServer process? That shouldn't be necessary.

Sometimes the computer will have an exception and restart the desktop. At this time, I find that the program can no longer be opened. After trying for a long time, I found that shutting down the windowServer process can reproduce this.
