### ISSUE TITLE
[Bug]: dialog.showOpenDialog() crashes the electron app.

### ISSUE THREAD

**Issue by iprathamjain** [electron/electron#40171]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Ubuntu 16.04 LTS

### Operating System Version

Ubuntu 16.04 LTS

### What arch are you using?

x64

### Expected Behavior

dialog.showOpenDialog() this should open a dialog to select a file, and get it's path.

### Actual Behavior

 Instead as soon as this function is called, the electron app crashes and exits automatically.

### Additional Information

Happening on ubuntu 16.04, but works properly on ubuntu 17 and 18.
This is the short code snippet

```
async function handleFileOpen() {
  const { canceled, filePaths } = await dialog.showOpenDialog();
  console.log(filePaths,canceled);
  if (!canceled) {
    return filePaths[0];
  }
}
```

This are logs I got when app got crashed-
```
[7252:1010/183035.184817:ERROR:browser_main_loop.cc(275)] Gtk: gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
[7252:1010/183035.184886:ERROR:browser_main_loop.cc(275)] GLib-GObject: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
Segmentation fault (core dumped)
```

**Comment by codebytere** [comment]
@iprathamjain Unfortunately Chromium no longer supports Ubuntu v16, and as a result Electron does not either. We've [updated our documentation](https://github.com/electron/electron/pull/40177) to reflect that.
