### ISSUE TITLE
[Bug]: dyld[57850]: Library not loaded: '@rpath/Electron Framework.framework/Electron Framework'

### ISSUE THREAD

**Issue by sunquakes** [electron/electron#40172]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^26.3.0

### What operating system are you using?

macOS

### Operating System Version

Version 12.6.9 (21G726)

### What arch are you using?

x64

### Expected Behavior

1.Add scripts item in package.json
```json
 "scripts": {
    "postinstall": "install-app-deps",
    "start": "electron .",
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  }
```
2.Run command
```bash
pnpm i
pnpm start
```
3.Start the electron windows

### Actual Behavior

3.Report error
```bash
> electron-kits@0.0.1 start /path/to/project
> electron .

dyld[61326]: Library not loaded: '@rpath/Electron Framework.framework/Electron Framework'
  Referenced from: '/path/to/project/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'
  Reason: tried: '/path/to/project/node_modules/electron/dist/Electron.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/path/to/project/node_modules/electron/dist/Electron.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/System/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file)
/path/to/project/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGABRT
```

### Additional Information
`Electron Framework` actural lin the path of
`/path/to/project/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework`

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
