### ISSUE TITLE
[Bug]: cli electron main.js can't require electron

### ISSUE THREAD

**Issue by TTSKarlsson** [electron/electron#40184]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 Build 22621.2283

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

Require in `main.js`, when running with `npx electron main.js`, should return a module that can be destructured in to `app` and `BrowserWindow` and all other parts of the API.

### Actual Behavior

![20231012_093748_567x248](https://github.com/electron/electron/assets/9962943/c2be2e97-232f-4667-befa-11b97851d0e6)

Results in:

![20231012_093022_693x388](https://github.com/electron/electron/assets/9962943/52d60345-ad6d-4d01-8e21-460b1ab20d20)

### Additional Information

I've had this problem for at least a year when checking back at electron, so we've not been able to use it. It happens regardless of which computer we're using, and there been several versions of node/npm/electron over that time.

Doing the quick start step by step breaks when adding the `app.whenReady()` as app is not defined, and can't be destructured from the string that contains the path to electron executable.

![20231012_093348_377x375](https://github.com/electron/electron/assets/9962943/ee1e75e4-41bb-4fb0-a69b-40b33fd1a3ce)
![20231012_093415_997x374](https://github.com/electron/electron/assets/9962943/0d0caa94-7ea4-4bf2-be78-ba8f52b47023)

`package.json` and `index.html` from the Quick Start is used, main.js simplified for brevity.

**Comment by MarshallOfSound** [comment]
This looks like you're using a shell / terminal that is setting the `ELECTRON_RUN_AS_NODE` environment variable.  Try logging out that value and seeing if it's set, on windows in cmd you can unset it with `set ELECTRON_RUN_AS_NODE=`

**Comment by TTSKarlsson** [comment]
![20231012_095813_454x59](https://github.com/electron/electron/assets/9962943/04c07c8e-b535-40fe-8fff-5afbf833ba5a)
![20231012_095833_446x58](https://github.com/electron/electron/assets/9962943/f7f7cafb-ff5c-430c-9979-b8e1cda1b04c)

But yes you're right, it's not in my environment per se, but something that nvm for windows does for some explicable reason. Thanks, I'm going to use proper installs of nodejs from now on, on all machines.
