### ISSUE TITLE
[Bug]: Tray 'middle-click' event is emitted as 'click' on Windows 11

### ISSUE THREAD

**Issue by roduk** [electron/electron#40196]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0-alpha.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

When middle-clicking the tray, the new 'middle-click' event should be emitted.

### Actual Behavior

When middle-clicking the tray, the 'click' event is emitted instead.

### Testcase Gist URL

https://gist.github.com/roduk/d550eae91921c55eb772da4557ec54a0

### Additional Information

This event works fine on Windows 10, this is isolated to Windows 11 only.

**Comment by codebytere** [comment]
Looks like this isn't an Electron issue: https://github.com/HavenDV/H.NotifyIcon/issues/82

Also see https://www.microsoft.com/en-us/windowsinsider/feedbackhub/fb?contextid=951&feedbackid=0f802adb-8264-4a16-93c7-c334ef74af17&form=1&utm_source=product-placement&utm_medium=feedback-hub&utm_campaign=feedback-hub-redirect
