### ISSUE TITLE
Unable to Capture Option(Alt) Key Combinations in Mac

### ISSUE THREAD

**Issue by adhithyan15** [electron/electron#402]
Hey Guys! I am trying to capture `option` key combinations using accelerators. But I am unable to capture any  of the key combinations like `option + F1`. 

I looked at the file https://github.com/atom/atom-shell/blob/2cdcb45d16737ad9f509777e659ab29ab8e095bc/atom/browser/ui/accelerator_util.cc and I found that there is no mapping for **option** key in the file. 

Can someone help me with this issue?

**Comment by muub** [comment]
I think what @adhithyan15 is trying to say here is that atom is not capturing the usage of the Alt/Option key as an Alt/Meta/Option key so none of the keychords mapped to alt in the atom editor are working on the mac. The option key on the mac is usually used for typing special characters or symbols and it's still doing that by default.

**Comment by Rosey** [comment]
I was encountering something like this, filed a different issue here: https://github.com/atom/electron/issues/4184 because I wasn't sure if it was the same as what @adhithyan15 was getting at.
