### ISSUE TITLE
[Bug]: Setting color-scheme to dark changes text color but not background color for webviews

### ISSUE THREAD

**Issue by BrandonXLF** [electron/electron#40207]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

The background colour of the webview should be black and the text colour should be white.

### Actual Behavior

The background colour of the webview is white and the text colour is also white, making it impossible to read the text.

### Testcase Gist URL

https://gist.github.com/BrandonXLF/4a6f65cba592bece8d1413f7a8730dca

### Additional Information

Continuation of #36122 as it became stale

Issue applies to both the `color-scheme` CSS property when it's applied to `:root`/`html` and the `color-scheme` meta tag, but it works fine when applied to other elements like `textarea`. The issue is not present in iframes.

**Comment by arianxq** [comment]
This seems like an interesting task. Can I try to solve this?
