### ISSUE TITLE
[Bug]: after call setIgnoreMouseEvents(true, {forward: true}) on a transparent frameless BrosweWindow，when i use wacom(also installed its driver)，i can't recieve mousemove、mouseenter event

### ISSUE THREAD

**Issue by unfor** [electron/electron#40213]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows11 22621.2283

### What arch are you using?

x64

### Last Known Working Electron version

v11.1.1

### Expected Behavior

I hope i can recieve mouseenter、mouseleave event, so that i can let my program behave in right way

### Actual Behavior

after call setIgnoreMouseEvents(true, {forward: true}) on a transparent frameless BrosweWindow，when i use wacom(also installed its driver, link- https://www.wacom.com/zh-cn/support/product-support/drivers)，i can't recieve mousemove、mouseenter event
![image](https://github.com/electron/electron/assets/23637532/eeb3eba0-dc9f-446c-b1ce-38129e4bec15)
driver settings are as follows
![image](https://github.com/electron/electron/assets/23637532/60a2cb8b-7ca4-4b72-8468-27f9738fced5)
when i move cursor or write with wacom's pen, i found bug above

### Testcase Gist URL
I have tried electron v26.0.0，also has the same question. Test case is: run the demo, use this hardware to move cursor, when pass document.body, logs are as expected. After click the button to set window ignoreMouseEvents，do the same thing, however, there is no log on console.
**https://gist.github.com/unfor/eef5e19fdea1bfb2b56c267ebeb29d8b**

**Comment by unfor** [comment]
Whether it's because the window is out of focus?

**Comment by codebytere** [comment]
Duplicate of https://github.com/electron/electron/issues/30808

**Comment by Beefal0** [comment]
I encountered the same issue. I tried using `onPointerEnter` and `onPointerLeave` to replace `onMouseEnter `and `onMouseLeave`. I hope it will be effective.
