### ISSUE TITLE
[Bug]: HTML DOM is rendered broken in some environment 

### ISSUE THREAD

**Issue by JellyBrick** [electron/electron#40223]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Debian 12 SID

### What arch are you using?

x64

### Last Known Working Electron version

22.3.6

#### Electron 22.3.6

![image](https://github.com/electron/electron/assets/16558115/0f237fa3-911f-46d6-9bc9-105692ce01a0)

HTML DOM must load successfully.
In other environments (`AMD RX6600XT + Ubuntu 23.04 + Linux kernel 6.2.0`), Electron 27 works fine.

#### Electron 27.0.0

![image](https://github.com/electron/electron/assets/16558115/decbb218-50c8-4b8a-b2bc-98fd82ba9a95)

#### Electron 27.0.0-beta.9

![image](https://github.com/electron/electron/assets/16558115/3e14a548-7db9-4f36-8d0b-11db25a83f56)

Rendered broken.

### Testcase Gist URL

https://gist.github.com/1b5d032a77775f26349ed2e35a51da13

#### Hardware & Software information

- Debian GNU/Linux trixie/sid
- AMD Radeon Pro WX 5100 Graphics
- Mesa VA drivers 23.2.1-1
- Gnome 44.5
- Linux 6.5.0-2-amd64

**Comment by JellyBrick** [comment]
![image](https://github.com/electron/electron/assets/16558115/43958019-5f20-44a2-b7b9-1bd0f8157b5a)
Experimentally, a package was found that leads to this problem libllvm16 1:16.0.6-16
Downgrade to version libllvm16 1:16.0.6-15 solves the problem.

Original comment: https://github.com/th-ch/youtube-music/issues/1324#issuecomment-1766362235

**Comment by codebytere** [comment]
@JellyBrick can you reproduce this in Google Chrome itself, without Electron? You'll need to ensure your version of Chrome is at least 118.0.5993.54.

**Comment by JellyBrick** [comment]
> @JellyBrick can you reproduce this in Google Chrome itself, without Electron? You'll need to ensure your version of Chrome is at least 118.0.5993.54.

Can't reproduce in `Google Chrome` (Version 118.0.5993.88)

**Comment by JellyBrick** [comment]
> @JellyBrick can you reproduce this in Google Chrome itself, without Electron? You'll need to ensure your version of Chrome is at least 118.0.5993.54.

Can't reproduce this issue in `Google Chrome` 118.0.5993.88.
(This issue is still reproducible in Electron 27.0.1)

**Comment by JellyBrick** [comment]
Upgrade to version: `libllvm16 1:16.0.6-17` also breaks the interface.

**Comment by JellyBrick** [comment]
Fixed in #40450
