### ISSUE TITLE
PrintToPdf with PageSize and Pdf Content issue

### ISSUE THREAD

**Issue by NManasia16** [electron/electron#40254]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

**I want to downlod  Pdf according Specified Page Size and rotate-left Content. but issue is their pdf download with lot's of space.**

I have Done this in BrowserWindow. it's perfectly shown fine, but i want to download PDF file, in that by default margin are in there.
 
and i want to download PDF with whole browserWindow content.

can you please see below image?  and exactly same content i want to download in PDF without any margin or any space.

![image](https://github.com/electron/electron/assets/103309079/52fbc667-2963-4055-8445-1df82f412730)

please check it out output as a Pdf
[temp.pdf](https://github.com/electron/electron/files/13006555/temp.pdf)

Can any One Help me to solve it out this issue?

### Proposed Solution

const exportToPDF = () => {
  var printContent: any = document.getElementById("section-to-print")?.innerHTML;

  var content =
    `<html><head><style>body { visibility: hidden; position:relative; margin:0;} .mainDiv {visibility: visible; position: absolute; top:0; left:0;transform: rotate(270deg);transform-origin: 50% 120%; width: 816px; height: 336px; background-color: gray !important;} .payableSpan, .amountWordSpan, .dateSpan, .amountSpan {position: absolute; }</style></head><body><div class="mainDiv">` +
    printContent +
    `</div></body></html>`;
  ipcRenderer.invoke("printPDF", content);
};

ipcMain.handle('printPDF', async (_event, html) => {
    const fs = require('fs');
    const os = require('node:os')

    var options = {
        marginsType: 1,
        pageSize: {
            width: 3.5,
            height: 8.5            
        },
        printBackground: true,
    } 

    const win = new BrowserWindow({width: 336,
    height: 816,
    webPreferences: {
        nodeIntegration: true, // You may need this depending on your Electron version
    }}) 
    // win.webContents.openDevTools();
    win.loadURL('data:text/html,'+html);

    win.webContents.on('did-finish-load', () => {
        const pdfPath = path.join(os.homedir(), 'Desktop', 'temp.pdf')
        win.webContents.printToPDF(options).then(data => {
            fs.writeFile(pdfPath, data, (error:any) => {
                if (error) throw error
                console.log(`Wrote PDF successfully to ${pdfPath}`)
            })
        }).catch(error => {
            console.log(`Failed to write PDF to ${pdfPath}: `, error)
        })
    })
})

### Alternatives Considered

// Calculate the scale factor to fit the content to the desired size
 const contentSize = win.getContentSize();
const scaleFactorX = fitWidth / contentSize[0];
const scaleFactorY = fitHeight / contentSize[1];        
const scaleFactor = Math.min(scaleFactorX, scaleFactorY);

// Adjust the zoom factor based on the calculated scale factor
win.webContents.setZoomFactor(scaleFactor);

**Comment by NManasia16** [comment]
Hello,
Please check it out below Demo in Fiddle
https://gist.github.com/NManasia16/5cadf005d089be1e42a375888286e309

After run above example please check pdf file into /Desktop/temp.pdf

**Comment by NManasia16** [comment]
@codebytere can you please provide me any solution of above issue.
Thanks.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
