### ISSUE TITLE
[Bug]: Grand central dispatch not working on macOS

### ISSUE THREAD

**Issue by chelemen-razvan** [electron/electron#40258]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.2

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.0.1 (22A400)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.0.2

### Expected Behavior

Expected behaviour is that dispatching some task with delay should work fine in a native module. Same code works as expected on version 22.0.2 but on version 26.2.2 the task is never run. [Here is a sample app](https://github.com/chelemen-razvan/electron-26-threading-issue-mac) to reproduce the issue. The relevant code is in `cam_mac.mm`, `This is called.` is printed to the console as expected while `This is NOT called.` is never printed. 

### Actual Behavior

The dispatched task is never run on 26.2.2 while on 22.0.2 works as expected.

**Comment by codebytere** [comment]
Tracked to https://github.com/electron/electron/compare/v25.0.0-nightly.20230330...v25.0.0-nightly.20230331 - probably https://github.com/electron/electron/pull/37701

**Comment by jim-lake** [comment]
Is this expected to work correctly in the main process then?  Is this documented anywhere?
