### ISSUE TITLE
[Bug]: The BrowserWindow will keep last render result in render view, seem like a shadow of render, when i hide or show the window with manual.

### ISSUE THREAD

**Issue by rictt** [electron/electron#40256]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.9.1

### What operating system are you using?

macOS

### Operating System Version

12.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Normal rendering, when i control to hide or show browserWindows

### Actual Behavior

<img width="1312" alt="image" src="https://github.com/electron/electron/assets/39750025/69afc434-db8f-4793-beee-8a114c496ff5">

For clearer presentation, i have set an interval  to change text by random.
when i click hide, and then show window by shortcut, you can see the gray text behind the red text.

### Testcase Gist URL

https://gist.github.com/rictt/5a2fde1077782959cf5779f059c8e660

**Comment by rictt** [comment]
`
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    * {
      margin: 0;
      padding: 0;
    }

    body,
    html {
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.1);
    }

    .random {
      font-size: 80px;
      color: red;
      text-align: center;
      margin: 40px 0;
    }
    button {
      font-size: 30px;
      padding: 5px 10px;
    }
  </style>
</head>

<body>
  <div class="random"><span id="random"></span></div>
  <div>
    <button id="hide">hide</button>
    <button id="show">show</button>
  </div>
  <script>
    const span = document.querySelector('#random')
    const hideBtn = document.querySelector('#hide')
    const showBtn = document.querySelector('#show')

    showBtn.addEventListener('click', () => {
      window.ipcRenderer.invoke('window:show')
    })
    hideBtn.addEventListener('click', () => {
      window.ipcRenderer.invoke('window:hide')
    })

    const setRandom = () => {
      const randomText = Math.random().toString(16).slice(-12).toUpperCase()
      span.innerText = randomText
    }

    setInterval(() => {
      setRandom()
    }, 2000)

    setRandom()
  </script>
</body>

</html>

`

**Comment by rictt** [comment]
preload.js

```
const { contextBridge, ipcRenderer } = require('electron')


contextBridge.exposeInMainWorld('ipcRenderer', ipcRenderer)
window.ipcRenderer = ipcRenderer

```

**Comment by rictt** [comment]
main.js

```js
const { app, shell, BrowserWindow, globalShortcut, ipcMain } = require('electron')
const { join } = require('path')

let mainWindow

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 900,
    title: '',
    show: true,
    transparent: true,
    // frame: false,
    // alwaysOnTop: true,
    webPreferences: {
      devTools: true,
      preload: join(__dirname, './perload.js'),
      sandbox: false
    }
  })

  console.log(1234)

  mainWindow.setAlwaysOnTop(true, 'screen-saver')
  // 设置窗口在所有工作区都可见
  mainWindow.setVisibleOnAllWorkspaces(true)

  mainWindow.on('ready-to-show', () => {
    mainWindow.show()
  })

  ipcMain.handle('window:show', () => {
    mainWindow.show()
  })
  ipcMain.handle('window:hide', () => {
    mainWindow.hide()
  })

  mainWindow.webContents.setWindowOpenHandler((details) => {
    shell.openExternal(details.url)
    return { action: 'deny' }
  })

  mainWindow.loadFile(join(__dirname, './index.html'))
}

function whenAppReady() {
  createWindow()

  globalShortcut.register('f2', () => {
    mainWindow.show()
  })

  globalShortcut.register('esc', () => {
    mainWindow.hide()
  })

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
}

app.whenReady().then(() => {
  whenAppReady()
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

```

**Comment by codebytere** [comment]
@rictt could you please put this in a [gist](https://gist.github.com/) for simplicity?

**Comment by rictt** [comment]
> @rictt could you please put this in a [gist](https://gist.github.com/) for simplicity?

sure, please click [here](https://gist.github.com/rictt/5a2fde1077782959cf5779f059c8e660)

**Comment by syt-honey** [comment]
Is there any progress here？

**Comment by MafistoPL** [comment]
Issue still reproduces with electron 30, here is gist with updated preload.js https://gist.github.com/MafistoPL/38c8244319a7e435d0cebe6c7702f69d
