### ISSUE TITLE
[Bug]: Menu separators in WIndows are almost invisible in Electron 27

### ISSUE THREAD

**Issue by cdonnellytx** [electron/electron#40267]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise, Version 22H2, OS build 22621.2428, Experience	Windows Feature Experience Pack 1000.22674.1000.0Edition	Windows 11 Enterprise Version	22H2 Installed on	‎6/‎2/‎2023 OS build 22621.2428, Windows Feature Experience Pack 1000.22674.1000.0

### What arch are you using?

x64

### Last Known Working Electron version

26.4.0

### Expected Behavior

Windows menu separators are clearly visible.

![Electron 26 Hello World, "View" menu opened](https://github.com/electron/electron/assets/183046/cdfe4bfa-6aee-465b-8c77-759602c490cc)

### Actual Behavior

Windows menu separators as of Electron 27 have changed from a visible line to a barely-visible gap.

![Electron 27 Hello World, "View" menu opened](https://github.com/electron/electron/assets/183046/0ab8ab2d-b941-4144-bc9d-89d8da4e6741)

### Testcase Gist URL

https://gist.github.com/81fd7969bb7e9ad5f4e22e05201a0603

### Additional Information

_NOTE: I am linking to @craxal's existing snippet from #39611 as it is sufficient to display the issue in Electron._

This appears to be another by-design Chrome change similar to the one in Electron 26 (#39611), as Chrome 118 also exhibits the same behavior:

![Screenshot of opened "hamburger" menu, Google Chrome 118.0.5993.71, dark mode](https://github.com/electron/electron/assets/183046/9c7b46c6-1f81-4114-a151-7ca82eb55fab)

I am mainly posting this as a "bug" so that it is documented and easily found, like the other menu change.

**Comment by codebytere** [comment]
I hear you all that this is a frustrating unexpected change but as a project by policy we don't keep issues open that aren't actionable in any way, especially if they're by design. I suggest instead commenting on the upstream issues - i've dug around a bit and i thiiink it's CL:4762885 associated with CRBUG:1470006.
