### ISSUE TITLE
[Bug]: CSS font-size with .1rem Displays Extremely Small in Electron Compared to Chrome

### ISSUE THREAD

**Issue by JamesSCC** [electron/electron#40277]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.5.1

### What arch are you using?

x64

### Expected Behavior

When setting the font size to .1rem in CSS, the text should display at a readable size, similar to how it appears in the Chrome browser.

### Actual Behavior

In my Electron app, the font size set to .1rem displays significantly smaller, making it almost invisible. This behavior is different from what is observed in the Chrome browser, where the font size is clearly readable.

### Testcase Gist URL

https://gist.github.com/JamesSCC/3b4b322ebc7da9b8318e7f6839a78ce5

**Comment by Bilal-Shahzad** [comment]
can i  be assigned to this?

**Comment by JamesSCC** [comment]
Hello,

I have created a standalone test case as requested and uploaded it to gist. You can find it at the following link:
https://gist.github.com/JamesSCC/3b4b322ebc7da9b8318e7f6839a78ce5

I hope this will assist you in better understanding and addressing the issue. Looking forward to your feedback!
