### ISSUE TITLE
Shared node context between multiple windows / iframes

### ISSUE THREAD

**Issue by FunkMonkey** [electron/electron#403]
Is it possible to share a node-context between multiple windows or at least between a window and its iframes? This would make sharing data a lot easier.

node-webkit does this by default, unless you use the `new-instance` parameter on [window.open()](https://github.com/rogerwang/node-webkit/wiki/Window#openurl-options).

Is something similar possible here? Does that require having the windows/iframes in the same process?

Thanks a lot!

**Comment by fwextensions** [comment]
Happened upon this page and it seems the API suggested above has changed.  It's now:

`require('electron').remote.getGlobal('sharedObject').someProperty = 'new value'`

**Comment by NickClark** [comment]
It's worth noting, that while this works for simple objects, it's useless for things like MediaStreams. I have a case where I need to display media streams originating in another window in child windows. For this reason alone, I've been forced to use NW.js

**Comment by blueeaglex** [comment]
@NickClark  @Ajeey
Yes. MediaStreams are too big for shared objects. I also got performance issue with sharing MediaStreams between processes.  It seems that electron didn't realy share any thing between processes, but only copy data from one to another.  It is not a good idea to copy a 1920*1080 video frame all around.

**Comment by danielsokolowski** [comment]
Has there been any new approaches on sharing context between windows?

**Comment by snarun** [comment]
I think shared context will definitely be helpful, especially when we deal with large applications, where functions are separated across multiple renderer processes, but utlilizing the same instance of the context.  Also, repeated loading of context can be avoided and thereby reducing the memory heap size.
