### ISSUE TITLE
[Bug]: macOS Sonoma (14.0) warning about secure coding not being enabled for restorable state

### ISSUE THREAD

**Issue by eXhumer** [electron/electron#40318]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

No warning messages to be shown

### Actual Behavior

This warning message is printed on console everytime I launch an Electron application in development.

```
2023-10-24 10:11:52.605 Electron[4922:67768] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
```

### Additional Information

This warning appears to be related to the following vulnerability (https://sector7.computest.nl/post/2022-08-process-injection-breaking-all-macos-security-layers-with-a-single-vulnerability/)

**Comment by eXhumer** [comment]
Being worked in PR #40296

**Comment by necipsagiro** [comment]
Hiding the dock icon with `app.dock.hide()` seems to prevent the warning from appearing. I hope this is helpful.

**Comment by gustavo-maurina** [comment]
> Hiding the dock icon with `app.dock.hide()` seems to prevent the warning from appearing. I hope this is helpful.

This also fixed the issue for me, but it harms the dev experience (no icon on the dock). Has anyone found a fix for it?
