### ISSUE TITLE
[Bug]: Permissions are not removed from Privacy & Security in Macos

### ISSUE THREAD

**Issue by DavidGOrtega** [electron/electron#40314]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.2

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Uninstall the app with AppCleaner or alike should remove the app in any Privacy & Security` permission list

### Actual Behavior

When I uninstall an app via AppCleaner normally the app is not shown in `Privacy & Security` under the given permission anymore. However electron apps like Slack, Discord (or mine) are still there. The only way to remove them is via 

```sh
tccutil reset SERVICE [BUNDLE_ID]
```

Its a bit of annoying when you develop and endup changing the bundleId:

<img width="477" alt="image" src="https://github.com/electron/electron/assets/414967/a9e6ce24-0f3f-4e3d-9720-f216ebfc8ec3">

**Comment by codebytere** [comment]
@DavidGOrtega does Chrome itself do this correctly? We plumb their logic essentially, so this is likely an issue to open upstream with them.

**Comment by DavidGOrtega** [comment]
@codebytere thanks for the reply.

Chrome behaves the same, leaves the permissions in the `Privacy & Security` settings, however and this is very interesting Microsoft Teams which is also electron behaves properly. It removes everything.
May them be running a cleanup script or something? 

Tested with AppCleaner

**Comment by codebytere** [comment]
@DavidGOrtega that'd be my assumption - we're of course interested in addressing this but to be honest I think the most effective way to have this fixed would be to file an issue at Chromium's [crbug](https://crbug.com) tracker. When they fix it, we inherit that fix for free via our Chromium upgrade process, and we're quite close to tip of tree so the delta there is small.

**Comment by codebytere** [comment]
Closing this out for now in light of the above.

**Comment by ayushete02** [comment]
@codebytere I am still encountering the same issue when uninstalling the Electron app. Even after completely removing the app from the system and the recycle bin, the permissions are not being revoked.

**Comment by ayushete02** [comment]
@DavidGOrtega did you find some solution??
