### ISSUE TITLE
[Bug]: Call dll crashes or cpu is too high

### ISSUE THREAD

**Issue by zhou1591** [electron/electron#40324]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

22.0.0

### Expected Behavior

node-ffi can be used in the main thread to call system functions, or in the rendering thread when the cpu is not so high

### Actual Behavior

I am now using node-ffi to call a dll that contains a system function

`
init_apartment(apartment_type::multi_threaded);
`
At first I used the main thread to call, then I got the following result, the final result is because electron sandbox mode I can not use external memory

![image](https://github.com/electron/electron/assets/39522200/0ae0e654-8597-4ca4-9fa4-d439207c42d9)

I then tried to configure the sandbox:false for the rendering thread and found that it worked, which made me very happy, but when I put it into the actual scenario I found that the cpu was very high when the "ffi.Callback" was called, which made my other applications very dull

In order to confirm where the problem is, I took out the code that called dll to run separately, and found that the cpu would not be so high, so I guess electron did some processing that caused the cpu to be high. 

Hope someone can help me when they see this problem, thank you everyone, I have been troubled for a week.

**Comment by zhou1591** [comment]
Help me.！！！  Thank you

**Comment by miniak** [comment]
Electron 22 is not supported anymore, does it reproduce with Electron 25+?

**Comment by zhou1591** [comment]
> Electron 22 is not supported anymore, does it reproduce with Electron 25+?

Thank you for your answer. I have solved the problem, probably because electron started its own node child thread. It feels good after switching to regular node
