### ISSUE TITLE
[Bug]: Submenus of the parent window are covered by the child window after child.setParenWindow(parent)

### ISSUE THREAD

**Issue by virtuecoder** [electron/electron#40322]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise, 22H2, 19045.3579

### What arch are you using?

x64

### Last Known Working Electron version

19.0.10

### Expected Behavior

The submenus of the parent window should be displayed above the child window. This is a simple example:

```
app.on('ready', () => {   
  const parent = new BrowserWindow({x: 100, y: 20, width: 300, height: 300});   
  const child = new BrowserWindow({x: 100, y: 20 + 60, width: 300, height: 300 - 60});   
  child.setParentWindow(parent);   
  parent.loadFile('index.html');   
  child.loadFile('index.html'); 
})
```

### Actual Behavior

The submenus are covered by the child window.
Submenus work fine if the parent is set during creation `const child = new BrowserWindow({ parent, ... })`

**Comment by codebytere** [comment]
@virtuecoder if you add `app.commandLine.appendSwitch('disable-features', 'WidgetLayering');` to your main process, does the issue still occur?

**Comment by codebytere** [comment]
@virtuecoder thanks! in that case, i'm going to fold this into https://github.com/electron/electron/issues/38790 - it's the same root issue.
