### ISSUE TITLE
[Bug]: fullscreened window doesn't come to front when activating it while other windows are open

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#40323]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I expect that clicking on a fullscreened window will bring it to front (or send other windows to the back) when there are other windows over the fullscreened window.

### Actual Behavior

Secondary windows stay on top

### Testcase Gist URL

https://gist.github.com/pushkin-/54c09a651cb66794189d80556343a8d4

### Additional Information

1. Full screen the main window
2. Click Open Window
3. window opens (and notice it's not fullscreened which would be the default behavior, because I disable that setting; otherwise it opens in a separate Desktop/Space)
4. click on the main window
5. it gets focus but doesn't come to the front (or secondary windows don't go to back)

**Comment by codebytere** [comment]
@pushkin- this unfortunately is not expected behavior on macOS - fullscreened windows _are_ the space, and so cannot go to the back in the way you're talking about. Clicking on the fullscreen window will correctly focus it, but it's not possible for the non-fullscreen window to go behind it in that context.

**Comment by codebytere** [comment]
@pushkin- yes, correct!
