### ISSUE TITLE
[Feature Request]: Upgrade nodejs to v20 LTS

### ISSUE THREAD

**Issue by Bartel-C8** [electron/electron#40343]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Is there a timeline on the upstep to the latest Node.JS v20 , now that it recently hit (Active) LTS?

### Proposed Solution

Use current Node LTS: [20.9.0 LTS](https://nodejs.org/en)

### Alternatives Considered

Curious about possible performance gains as opposed to the current v18, which is in Maintenance LTS

**Comment by codebytere** [comment]
Hi @Bartel-C8 - we track upstream's [Release Schedule](https://nodejs.org/en/download/releases) and will adopt Node v20 when it enters active LTS. I'm going to close this out for now given our upgrade process is already enshrined into policy but there should be a PR starting this soon.

**Comment by sparecycles** [comment]
@codebytere According to the [release schedule with dates](https://github.com/nodejs/release#release-schedule) Node 20 is active LTS as of 2023-10-24. 😉 

Personally, I'm hoping to use [`module.register`](https://nodejs.org/docs/latest-v20.x/api/module.html#moduleregisterspecifier-parenturl-options) in a project.

(Un)fortunately, it looks like that might allow/require some of the native work done in https://github.com/electron/electron/pull/37535 to be moved to using that API.

**Comment by Bartel-C8** [comment]
I saw work is being done here: https://github.com/electron/electron/tree/nodejs-v20

**Comment by codebytere** [comment]
@Bartel-C8 correct! We're working on it :)

**Comment by kkocdko** [comment]
Will this released with electron v28 or not? The v28 seems enter the beta version already.

**Comment by Bartel-C8** [comment]
> Will this released with electron v28 or not? The v28 seems enter the beta version already.

Probably not...


But will v29 be using Node.JS 20 now that it's merged to master?

Docs were updated yesterday but still mention Node 18.19?
https://github.com/electron/electron/pull/40622

**Comment by sparecycles** [comment]
I'm sure this is unsupported, but 

https://releases.electronjs.org/release/v29.0.0-nightly.20231206 ?
