### ISSUE TITLE
[Bug]: Prompt window not loaded in browserWindow

### ISSUE THREAD

**Issue by raksha-987** [electron/electron#40341]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0

### What operating system are you using?

macOS

### Operating System Version

13.4.1 

### What arch are you using?

x64

### Last Known Working Electron version

12

### Expected Behavior

When a URL opens a prompt for input/any action the URL when loaded in browserWindow using win.loadURL the pop up should open on an electron window.

### Actual Behavior

When a URL opens a prompt for input/any action the URL when loaded in browserWindow using win.loadURL is not showing this prompt, but similarly if the URL contains an alert or confirm pop-up then it shows up in an electron pop-up.
Please let us know if there are any browser window options that we can enable to allow the prompts or any workaround. The Url in this case is a login page for a 3rd party authentication and the credentials are accepted through a prompt and this prompt is not visible and thus user can't proceed further

**Comment by codebytere** [comment]
Electron does not support `prompt()`, unfortunately, nor do we plan to. You should use `dialog.messageBox` for this.
