### ISSUE TITLE
Potentially undocumented breaking change (v23+): BrowserWindow 'close' event object

### ISSUE THREAD

**Issue by larissa-n** [electron/electron#40350]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Between v22 and v23, the BrowserWindow `'close'` instance method changes, with fewer attributes sent in the returned Event object.

Previously, the `event` object contained a `sender` object including sender.id. In electron v23 and up, sender is undefined. This may be a breaking change depending on existing implementations making use of event.sender or event.sender.id.

### Proposed Solution

Add detail to the docs (https://www.electronjs.org/docs/latest/api/browser-window#event-close) / breaking changes (https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-230, https://releases.electronjs.org).

### Alternatives Considered

For existing applications, a workaround would be:

Existing:
```
handleclose = event => console.log(event.sender && event.sender.id)
win.on('close', handleclose)
```

Electron v23 and up:
```
handleclose = (event, senderId) => console.log(senderId)
win.on('close', event => handleclose(event, win.webContents.id)
```

**Comment by soundar-m** [comment]
Noticing a similar change in `context-menu` event in webContents
the `event` argument in the context-menu handler is just having defaultPrevented key.

**Comment by MarshallOfSound** [comment]
This was intentional and isn't a breaking change, event.sender was never documented nor intended to be set for non-ipc events.  In both cases mentioned in this issue event.sender is trivially the object the event listener is added on, e.g. event.sender will never not be the window you're listening to events on.
