### ISSUE TITLE
[Bug]: visibilitychange event doesn't fire when backgroundThrottling is set to false

### ISSUE THREAD

**Issue by samu** [electron/electron#40353]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.2

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.5.2

### What arch are you using?

x64

### Last Known Working Electron version

24.8.8

### Expected Behavior

`visibilitychange` event fires when coming back to app.

### Actual Behavior

`visibilitychange` event doesn't fire.

### Additional Information

This happens when `backgroundThrottling` is set to false.

Seems to be related to https://github.com/electron/electron/pull/39223.

**Comment by codebytere** [comment]
This is now intended behavior, see PR:

> This should address that by ensuring that the page visibility is always visible when backgroundThrottling is disabled, and that the visibilitychange event is no longer emitted.
