### ISSUE TITLE
[Bug]: Zoom controller doesn't persist when changing webviews

### ISSUE THREAD

**Issue by SpecialAro** [electron/electron#40354]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2 - Build 22621.2428

### What arch are you using?

x64

### Last Known Working Electron version

26.0.0

### Expected Behavior

When switching between different Webviews the Zoom scale persists after going back to the initial webview.

### Actual Behavior

[Ferdium](https://github.com/ferdium/ferdium-app) currently uses multiple Webviews for each service it renders. When switching between Webviews the Zoom scale is not persistent (when switching away the zoom resets - this is visible for some milliseconds before changing to the other webview).

### Additional Information

I'm logging this issue in Electron given that this was not present in past versions of Electron, but only after `26.0.0` (I'm blaming `26.1.0` as the version who started to cause issues). After some investigation it seems like the PR that caused this unwanted behaviour is: https://github.com/electron/electron/pull/39495 .

Is it possible for you to search and revert this unwanted breakage? We would really need this to be fix because we have several users with this accessibility needs.

Thank you very much in advance!

PS: If this is not the proper way to open an issue on Electron please let me know.

**Comment by codebytere** [comment]
@SpecialAro would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

I can try to look into it this week but providing a repro would definitely speed things along!

**Comment by SpecialAro** [comment]
Hello @codebytere and thank you so much for answering this issue!

I'll try to make a test case as soon as possible and will publish it here.

Thank you very much for taking the time to take at look at this.

**Comment by david-christ** [comment]
Confirming the same issue on macOS 13 (Ventura)

**Comment by RJVB** [comment]
Confirming on Linux, also that it's highly annoying and really surprising that this could have slipped through!

**Comment by codebytere** [comment]
@RJVB @david-christ it would be helpful if you could provide a repro then!

**Comment by RJVB** [comment]
>@RJVB @david-christ it would be helpful if you could provide a repro then!

I know somebody is on it (see the Ferdium ticket referenced above) but I am just a user who's concerned that the issue gets the attention it deserves.

**Comment by codebytere** [comment]
I've continued to try but am not clear on the precise circumstances required to reproduce this. I cannot use ferdium as a reproducible sample as it is an entire app and i cannot simply swap in a locally built version.

**Comment by codebytere** [comment]
Alright i ended up messing with ferdium until i could get it to work with a local build - i have a solution locally and will hopefully get this addressed soon.
