### ISSUE TITLE
[Bug]: Electron not launching window on Windows, Linux seems unaffected.

### ISSUE THREAD

**Issue by strawmelonjuice** [electron/electron#40360]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2; Debian/Half-Ubuntu 22.04 LTS

### What arch are you using?

x64

### Expected Behavior

On windows:

```powershell
npx electron .
```
-> works.

On linux:
```bash
npx electron .
```
-> works.

### Actual Behavior

On windows:

```powershell
npx electron .
```
-> Quits when app.ready should fire.

On linux:
```bash
npx electron .
```
-> works.

### Additional Information

```bash
npm start
```
works on both, I'll put my `package.json` below:

```json
{
  "name": "plantain",
  "productName": "Plantain: Bananen GUI",
  "description": "A graphical user interface around Bananen, built on Kivi",
  "version": "0.2.1",
  "main": "dist/plantain.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "electron dist/plantain.js",
    "build": "npx tsc",
    "devj": "concurrently \"npx tsc --watch\" \"nodemon --exec electron dist/plantain.js -e js,css,html,handlebars\"",
    "dev": "concurrently \"npx tsc --watch\" \"nodemon --exec electron dist/plantain.js -e js\"",
    "pack": "electron-packager --platform=all --arch=x64 ./ Plantain --out ./dist/release && electron-packager --platform=all --arch=arm64 ./ Plantain --out ./dist/release"
  },
  "author": "Strawmelonjuice Mar",
  "license": "GPL-3.0",
  "devDependencies": {
    "@types/electron": "^1.6.10",
    "@types/express": "^4.17.19",
    "@types/markdown-it": "^13.0.2",
    "@types/node": "^20.7.1",
    "concurrently": "^8.2.1",
    "electron": "^20.0.2",
    "electron-packager": "^17.1.2",
    "nodemon": "^3.0.1",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "express": "^4.18.2",
    "handlebars": "^4.7.8",
    "kivi-bananen": "^2.1.0-alpha",
    "markdown-it": "^13.0.2",
    "tslog": "^4.9.2"
  }
}
```

**Comment by arifakhtar51** [comment]
@strawmelonjuice sir can i work on this issue ??

**Comment by strawmelonjuice** [comment]
If you'd like to, though I can't assign anyone, think only the electron team can

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
