### ISSUE TITLE
[Bug]: <webview> property allowpopups is typed as boolean but only works if passed as string.

### ISSUE THREAD

**Issue by ranzwertig** [electron/electron#40364]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.2

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Setting the property `allowpopups` as boolean like defined in the types of Electron.WebviewTag to a webview element should lead to `allowpopups="true"` in the rendered dom.

### Actual Behavior

Setting allowpopups like `<webview allowpopups />` (JSX) leads to the following warning:

```
Warning: Received `true` for a non-boolean attribute `allowpopups`.
If you want to write it to the DOM, pass a string instead: allowpopups="true" or allowpopups={value.toString()}.
```
It seems like types are not correct in `electron/electron.d.ts > interface WebviewTag extends HTMLElement`.

### Additional Information

The issues appears in JSX with TypeScript.

**Comment by codebytere** [comment]
@ranzwertig If i add `<webview src="https://www.github.com/" allowpopups></webview>` to the default quick-start I don't see this issue on either Windows or macOS.

**Comment by ranzwertig** [comment]
@codebytere, I apologize for not being clear enough. We are using a React app within Electron, and it's written in TypeScript. I've encountered an issue with the type of the webview (Electron.WebviewTag). It exposes the allowpopups property as a boolean. However, when I pass it as a boolean in JSX, it doesn't seem to have any effect. But when I bypass the types and pass it as a string, it works as expected. I believe this issue is related to the types defined in interface WebviewTag extends HTMLElement {."

**Comment by codebytere** [comment]
@ranzwertig ahhh ok that makes sense! thanks - i'll poke into fixing that :D

**Comment by felixrieseberg** [comment]
Hi! I think the reason you're seeing an error is because you're passing any value at all - `allowpopups` should just stand on it's own. The following all mean that `allowpopups` is enabled:

```
<webview allowpopups>
<webview allowpopups='true'> 
<webview allowpopups='false'>
```

That hasn't always been handled super well by JSX, but if you want the "correct" HTML type, you'd pass React an empty string or just nothing.

The following is valid TSX with React on my machine:

```tsx
return (
	<webview allowpopups />
)
```

You're right that the types complain if you try to assign it a boolean, but that's on the React side, I'm afraid: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v17/index.d.ts#L2776

**Comment by ranzwertig** [comment]
Hi @felixrieseberg. Actually it ONLY works if I pass it as a string like `<webview allowpopups="true" />`. Whenever I pass it like `<webview allowpopups />` JSX interprets it as boolean (its the same as `<webview allowpopups={true} />`) and then I get the following error:

```
instrument.js:122 Warning: Received `true` for a non-boolean attribute `allowpopups`.
If you want to write it to the DOM, pass a string instead: allowpopups="true" or allowpopups={value.toString()}.
    at webview
```
