### ISSUE TITLE
[Bug]: Unable to select filter in showOpenDialog dialog on macOS

### ISSUE THREAD

**Issue by xpadev-net** [electron/electron#40361]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.x

### What operating system are you using?

macOS

### Operating System Version

- macOS 14.0（23A344）
- macOS 14.1（23B74）

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

26.4.2

### Expected Behavior

Ability to select any filter in the file selection dialog

<img width="240" alt="image" src="https://github.com/electron/electron/assets/96982836/232d2ff0-e903-4850-a2ff-d4078db932eb">

↑ v26.4.2

### Actual Behavior

In the file selection dialog, the filter selection field is disabled and cannot be changed from the initial filter.

<img width="219" alt="image" src="https://github.com/electron/electron/assets/96982836/21f95f73-515e-4f8f-8e36-d83cffa227ee">

↑v27.0.0

<img width="226" alt="image" src="https://github.com/electron/electron/assets/96982836/17a39849-56a5-4c02-bf0c-574f776fd84a">

↑v27.0.1

<img width="205" alt="image" src="https://github.com/electron/electron/assets/96982836/9e2924cb-0ea4-4d64-894a-72bf1032a67b">

↑v27.0.2

### Testcase Gist URL

https://gist.github.com/d42aa1d0f297f1764c7aa5a7beeb4761

**Comment by codebytere** [comment]
Already fixed in https://github.com/electron/electron/pull/40308 - will be out in the next release!

**Comment by xpadev-net** [comment]
Sorry, I couldn't find it.
Thanks.
