### ISSUE TITLE
[Bug]: session.setUserAgent not inherited by iframes

### ISSUE THREAD

**Issue by mayfield** [electron/electron#40374]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24

### What operating system are you using?

Other Linux

### Operating System Version

NA

### What arch are you using?

x64

### Expected Behavior

For any context of a BrowserWindow using a custom session to use the session based user-agent.

### Actual Behavior

The top frame uses the correct session based user agent but iframes of the same window do not.

### Additional Information

Repro:

```
session = electron.session.fromPartition('persist:foobar');
session.setUserAgent('CUSTOM');

win = new electron.BrowserWindow({webPreferences: {session}});
win.loadURL('some site with iframes');
```

// Observe the incorrect user-agent header being used for the iframes (in my case I remove Electron and my product name from useragent to prevent anti-bot issues)

https://github.com/electron/electron/assets/139316/d0e64ec0-e65e-4c39-b0d6-1b809e4e720d

It appears this affects new popup windows too, but that's perhaps for another report.

**Comment by mayfield** [comment]
Some additional data:

All the WebContents instances look correct (i.e. they have "Electron" scrubbed from them in my case):

```
electron.webContents.getAllWebContents().map(x => x.userAgent.match(/Electron/))
(2) [null, null]
```

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.

**Comment by mayfield** [comment]
> Thank you for reaching out!
> 
> The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.
> 
> If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.
> 
> Thanks in advance! Your help is appreciated.

Hi I really don't want to re-enter all of this info but this bug is still present on 27 (just tested).  Can you reopen?

**Comment by mayfield** [comment]
@jkleinsc

**Comment by aguantelinux** [comment]
I have the same issue in electron@30.0.9. When using 

electronSession.webRequest.onBeforeSendHeaders((details, callback) => {
     details.requestHeaders['User-Agent'] = user_Agent;
     callback({ cancel: false, requestHeaders: details.requestHeaders });
}); 

it works well for everything except those that are inside an iframe.

**Comment by jappp** [comment]
Hello, I've encountered the same issue in electron@28.2.3. The problem manifests when I customize the useragent parameter for the webview tag. It works as expected for page A, which is loaded directly through the webview. However, if page A includes an iframe that loads page B, the user agent for HTTP requests initiated by page B reverts to the default Electron UA.Do you have any good suggestions? 
@jkleinsc

**Comment by udbmnm** [comment]
> Hello, I've encountered the same issue in electron@28.2.3. The problem manifests when I customize the useragent parameter for the webview tag. It works as expected for page A, which is loaded directly through the webview. However, if page A includes an iframe that loads page B, the user agent for HTTP requests initiated by page B reverts to the default Electron UA.Do you have any good suggestions? [@jkleinsc](https://github.com/jkleinsc)

You can use webRequest.onBeforeSendHeaders to solve the issue with the request headers
