### ISSUE TITLE
[Bug]: App crashes when unloading webview before it finished rendering since Electron 26.1.0

### ISSUE THREAD

**Issue by wartab** [electron/electron#40391]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10/11

### What arch are you using?

x64

### Last Known Working Electron version

16.0.0

### Expected Behavior

The application should just move on and not crash.

### Actual Behavior

The application closes without any error message shown or logged.

### Testcase Gist URL

https://github.com/wartab/electron-bug

### Additional Information

I previously reported this here, but another customer of ours had this issue happen on a fast PC and I could reproduce it on mine as well.
https://github.com/electron/electron/issues/40288

I can't reproduce it in Electron Fiddle, but the following repository reproduces the issue. 

It attempts to load a webview with inline HTML in the src attribute. That HTML is > 3 MB large with inline images. Electron never manages to render this webview, but when unloading the webview, the app crashes.

Simply removing the webview with removeChild() didn't crash the application, so my minimum reproduction is a bit closer to what we actually do. It is in an Angular application. The reproduction contains the app already built in `dist-angular`.

To reproduce:
`npm i`
Optionally: `ng build --base-href .`
`npm run-script build-electron`

**Comment by wartab** [comment]
And I confirm 100% that the crash does not happen in 26.0.0, but does in 26.1.0!

**Comment by codebytere** [comment]
@wartab figured out how to repro it - should have a PR up soon.

**Comment by wartab** [comment]
Ah thanks a lot, literally started trying to make it work without Angular less than 10 minutes ago. Trying to find what caused the bug had already taken me many hours of debugging on the slowest computer ever. 😆 
If you have a simple reproduction, I'd be curious to know why just deleting the element from the DOM wasn't sufficient to cause the crash.
