### ISSUE TITLE
[Bug]: `render-process-gone` reason is `crashed` rather than `oom` when renderer runs out of memory

### ISSUE THREAD

**Issue by jtbandes** [electron/electron#40426]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.3

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I added this to the default Fiddle template:

```js
  mainWindow.webContents.on("render-process-gone", (event, details) => {
    console.error("gone", details)
  })
````

Then I trigger an OOM crash by creating a button with the following action:

```js
let vals = []
document.getElementById("alloc").addEventListener("click", () => {
    vals.push(new Array(10_000_000).fill().map((_,i) => `${i}`));
})
```

Click the button until the renderer crashes.

I would expect to see `details.reason === "oom"`.

### Actual Behavior

`details.reason` is `"crashed"`.

The full console output is:

```
Electron v27.0.3 started.
2023-11-01 18:44:00.984 Electron[39880:19068364] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
<--- Last few GCs --->

[39886:0x178008000]    30604 ms: Scavenge 3929.7 (4054.9) -> 3929.7 (4054.9) MB, 2.04 / 0.00 ms  (average mu = 0.190, current mu = 0.058) allocation failure; 
[39886:0x178008000]    33849 ms: Mark-Compact 3975.7 (4093.0) -> 3975.6 (4093.0) MB, 3195.92 / 0.00 ms  (average mu = 0.107, current mu = 0.016) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

[39886:1101/184435.673685:ERROR:v8_initializer.cc(752)] V8 javascript OOM (Committing semi space failed.).
gone { reason: 'crashed', exitCode: 5 }
```

### Testcase Gist URL

https://gist.github.com/jtbandes/bfcebf9959c113daca891837ba242403

**Comment by codebytere** [comment]
@jtbandes this unfortunately isn't something we have too much control over - we plumb this from Chromium directly. We override it [here](https://github.com/electron/electron/blob/3bb93c472d0d7d6ee9536c8acfbaa2c98c1f8c61/shell/browser/api/electron_api_web_contents.h#L605-L606) but it's exclusively called [upstream](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/web_contents/web_contents_impl.cc;l=7947-8014;drc=7fa0c25da15ae39bbd2fd720832ec4df4fee705a;bpv=1;bpt=1). I recommend opening a [crbug](https://crbug.com/) to alert Chromium to the issue.

**Comment by jtbandes** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1500429
