### ISSUE TITLE
[Bug]: "Illegal instruction (core dumped)" in electron 26 with linux-hardened on Skylake due to faulty AVX(2) detection in simdutf 3.2.2 in nodejs 18.16.1

### ISSUE THREAD

**Issue by hardfalcon** [electron/electron#40441]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.4.3@aec6ffe4c728069ed435628f1a1e1c2742c75992

### What operating system are you using?

Other Linux

### Operating System Version

Linux myhostname 6.5.9-hardened1-1.1-hardened #1 SMP PREEMPT_DYNAMIC Mon, 30 Oct 2023 05:00:44 +0000 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

25.9.3@0ffac056c3eb622e05ca2493808760bbf4b96bde, 27.0.3@a6a35f12b00942924f7f2d00ac6db29ebc866802

### Expected Behavior

Electron 26.x on a Skylake machine with "gather data sample" mitigations enabled (and therefore AVX/AVX2 support disabled) shouldn't crash on start.

### Actual Behavior

Electron 26.x on a Skylake machine with "gather data sample" mitigations enabled (and therefore AVX/AVX2 support disabled) crashes on start with an illegal instruction.

Excerpt from gdb:

```
Thread 1 "electron" received signal SIGILL, Illegal instruction.
0x0000000109a0b348 in simdutf::haswell::implementation::utf16_length_from_utf8(char const*, unsigned long) const ()
```

### Additional Information

I'm running Archlinux x86_64 with the testing repos enabled, with a custom-built kernel derived from the "normal" `linux-hardened` kernel in Archlinux, and with custom-built `electron26` and `electron27` packages, where the electron packages always use the latest commit available from their respective `26-x-y`/`27-x-y` branch, and the `DEPS` file has additionally been modified to use the latest chromium version/tag available from their respective version branch at the time I compile the respective electron package.

I have enabled all available spectre/meltdown mitigations on the kernel cmdline in the bootloader, which includes mitigations for the "gather data sample" vulnerability. Note that enabling these mitigations is [known](https://kernel.org/doc/html/next/admin-guide/hw-vuln/gather_data_sampling.html#mitigation-mechanism) to cause software with faulty AVX/AVX2 support detection to use illegal instructions and thus crash. In my case, these mitigations cause the `avx`, the `avx2` and the `sse3` flag to be missing from `/proc/cpuinfo` although the CPU is a Skylake CPU. All other sse flags are present/available, though.

In my case, I can start `electron27` just fine, but `electron26` will crash immediately with an illegal instruction.

I think that the root cause is `nodejs 18.16.1` using `simdutf 3.2.2`, and that electron 27 doesn't crash because nodejs 18.17.1 uses `simdutf 3.2.12`, which contains this particular change introduced in `simdutf 3.2.9`:
https://github.com/simdutf/simdutf/commit/55b107f609f5f63880db650a92861ae84cb10abe

Note that even though the commit message mentions only AVX-512, the added checks look like they also influence the code path for at least also AVX2/AVX-256, and likely also the codepath for AVX.

**Comment by hardfalcon** [comment]
@jkleinsc : Here's a small reproducer script that uses your official release binary. If you have already installed electron 26.x on your system, you can also just do something like `qemu-x86_64 -cpu Skylake-Client-v4,-avx,-avx2,-sse3 /usr/lib/electron26/electron`.

```bash
#!/bin/bash
set -euxo pipefail
# Create the tempdir in the user's home directory, since /tmp might be mounted with nosuid enabled
TEMPDIR="$(mktemp --directory ${HOME}/electron-issue-40441-reproducer-XXXXX)"
chmod 755 "${TEMPDIR}"
curl --location "https://github.com/electron/electron/releases/download/v26.4.3/electron-v26.4.3-linux-x64.zip" | bsdtar --extract --directory="${TEMPDIR}"
sudo chown --recursive root:root "${TEMPDIR}"
sudo chmod 4755 "${TEMPDIR}/chrome-sandbox"
sudo chmod 755 "${TEMPDIR}/chrome_crashpad_handler" "${TEMPDIR}/electron"
echo "After reproducing the crash, execute the following command to clean up temporary files:"
echo "sudo rm --one-file-system --recursive \"${TEMPDIR}\""
# It is sufficient to just block either the avx or the sse3 flag to reproduce the illegal instruction crash, but on my machine, all three flags are blocked
qemu-x86_64 -cpu Skylake-Client-v4,-avx,-avx2,-sse3 "${TEMPDIR}/electron"
```

**Comment by hardfalcon** [comment]
The crash is indeed fixed by updating the `simdutf` version that ships with nodejs 18.16.1 from version 3.2.2 to 3.2.9. I've created a patch for this (to be added in electron's `patches/node/` directory and the corresponding `.patches` file) using the following process (sadly Github doesn't let me upload/attach the patch file here although it has the supposedly supported `.patch` filename extension):
1. Check out out the node [repo](https://github.com/nodejs/node) at tag `v18.16.1`.
2. Then edit the `tools/dep_updaters/update-simdutf.sh` script such that the `NEW_VERSION` [variable](https://github.com/nodejs/node/blob/v18.16.1/tools/dep_updaters/update-simdutf.sh#L10C1-L10C12) is hard-wired to the desired version `3.2.9`.
3. Execute the `tools/dep_updaters/update-simdutf.sh` script, and make sure the script's return code is `0` (this requires at least the `node` and `unzip` commands to be available).
4. Create a `git diff` of the changes, omitting the changes made to the `tools/dep_updaters/update-simdutf.sh` script.

**Comment by hardfalcon** [comment]
Here's the patch in a form that you can directly `git apply` it to the `26-x-y` branch of the `electron` repo:
https://gist.github.com/hardfalcon/126697b51ee2c23bd55688c81c02f3ea

**Comment by hardfalcon** [comment]
Feel free to add a test case for your test suite, run npm test on it, add or remove check boxes from the Checklist section, modify the commit message, or do whatever else you feel necessary to merge #40446.

**Comment by kmille** [comment]
Hey is this fixed and can be closed? I have an [issue](https://github.com/element-hq/element-desktop/issues/1467) with element-desktop that depends on this issue..?

**Comment by hardfalcon** [comment]
@kmille: Thanks for the hint. This specific issue has been fixed in the 26-x-y branch by commit https://github.com/electron/electron/commit/eb2173846bddf4f118fc55f1f376317863eb109e

I had also reported another AVX-related bug in electron, which was caused by node's `base64` dependency. That bug has also been fixed in the 26-x-y branch, more precisely by commit https://github.com/electron/electron/commit/a0af9e0e3c0e743e2ba23949a99278b777906bdb.

I wouldn't be surprised if there similar bugs waiting to be fixed in other dependencies of electron/node/chromium, though.

**Comment by kmille** [comment]
Thanks for the update. If it's fixed in 26-x-y, is it then also fixed in 28-x-y? Do you have any information how I can find out, which dependency is broken?

**Comment by hardfalcon** [comment]
@kmille : You're welcome :)

The bug in node's `simdutf` dependency has been fixed since simdutf 3.2.9. In electron 27.0.0 and newer, this is fixed because electron 27.0.0 started using 18.17.1, and newer electron branches use even newer versions of node. In the electron 26-x-y version branch, the specific commit fixing only this issue has been [backported](https://github.com/electron/electron/commit/eb2173846bddf4f118fc55f1f376317863eb109e) [since electron 26.6.3](https://github.com/electron/electron/blob/v26.6.3/patches/node/fix_backport_avx_detection_fix_from_simdutf_3_2_9.patch). This fix was never backported to electron 25-x-y.

The bug in node's `base64` dependency is only carried as a backport [since electron 26.6.2](https://github.com/electron/electron/blob/v26.6.2/patches/node/fix_avx_detection.patch) because the nodejs 18x´.x version branch is still using the the outdated base64 version 0.5.0, whilst this specific bug has only been fixed in [base64 0.5.1](https://github.com/aklomp/base64/releases/tag/v0.5.1) and newer. This fix also was never backported to electron's 25-x-y branch.

**Comment by kmille** [comment]
Yea, but Arch Linux uses Electron 28.x.x., so it's pretty new. If I run element-desktop it just crashes. How can I find which component/dependency is responsible for the crash?

**Comment by hardfalcon** [comment]
This is usually done using gdb. There's a page about how to do this in the Archlinux wiki:
https://wiki.archlinux.org/title/Debugging/Getting_traces

**Comment by kmille** [comment]
Thanks for the guidance, I made opened an issue: https://github.com/electron/electron/issues/41214
