### ISSUE TITLE
[Bug]: Using `net.fetch` with `bypassCustomProtocolHandlers` fails to load local mp4 files

### ISSUE THREAD

**Issue by BrandonXLF** [electron/electron#40447]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Expected Behavior

The mp4 file should load just as it would without the protocol handle set.mp4 

### Actual Behavior

The document for the mp4 files loads but the video itself does not.

### Testcase Gist URL

https://gist.github.com/BrandonXLF/465e91ee96fe29514d4e9d998e590d76

**Comment by BrandonXLF** [comment]
Reproducible in v29.1.0

**Comment by wangf1978** [comment]
same issue with me

**Comment by liuxini** [comment]
same issue with me

**Comment by Matt95** [comment]
I am getting the same issue even with bypassCustomProtocolHandlers: false

**Comment by Matt95** [comment]
> I am getting the same issue even with bypassCustomProtocolHandlers: false

Resolved, stream was required for correctly loading mp4 file types:
 ```javascript 
privileges: {
    bypassCSP: true,
    stream: true,
}
```

**Comment by Siddharth0304** [comment]
Ensure you have cross-origin="anonymous" on your video tag
