### ISSUE TITLE
[Bug]: When the window is transparent, setting thickFrame:false has no effect

### ISSUE THREAD

**Issue by fanchenio** [electron/electron#40456]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.4.2

### What operating system are you using?

Windows

### Operating System Version

Windows10

### What arch are you using?

x64

### Expected Behavior

When the window is transparent, the window display/hide animation can be removed by setting thickFrame:false.

### Actual Behavior

When the window is transparent, setting thickFrame:false has no effect, and there is still animation.

**Comment by brhenrique** [comment]
This is by design according [to this comment](https://source.chromium.org/chromium/chromium/src/+/main:ui/views/widget/widget_hwnd_utils.cc;l=152?q=widget_hwnd_utils.cc&ss=chromium%2Fchromium%2Fsrc)

> To avoid having a window frame and to avoid blurring the contents behind the window, the window must have WS_POPUP in its style and must not have not have WM_SIZEBOX, WS_THICKFRAME or WS_CAPTION in its style.
