### ISSUE TITLE
access_denied in CreateForMonitor

### ISSUE THREAD

**Issue by HuntCode** [electron/electron#40455]
Hello,
I developed A.dll with OSB libs(use IGraphicsCaptureItemInterop::CreateForMonitor)，when I write a addon.node with A.dll，it works fine    when run with non-admin Powershell，but it doesn't work when run with amin Powershell. The results is same as I debug with VS2022

Details in [access_denied in CreateForMonitor in some cases #125](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/125)

I'm not familiar with Electron, so I'm confused with the different results between MFC and Electron apps

A LowIP or a cef sandbox problem?

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by HuntCode** [comment]
Thanks for your answer，I will close this issue and submit a new issue with bug template

**Comment by shixiaolong-tech** [comment]
@HuntCode Have you fixed this problem? I come across the same problem with electron add-on when useing CreateForMonitor.

**Comment by HuntCode** [comment]
@shixiaolong-tech I didn't fix this problem，but I had a workaround.  I will check if the D3D11 supported，like this 
```c++
bool SupportD3D11()
{
    auto activation_factory = winrt::get_activation_factory<
        winrt::Windows::Graphics::Capture::GraphicsCaptureItem>();
    auto interop_factory =
        activation_factory.as<IGraphicsCaptureItemInterop>();

    winrt::Windows::Graphics::Capture::GraphicsCaptureItem item = { nullptr };

    struct monitor_info monitor = { 0 };
    monitor.desired_id = 0;
    EnumDisplayMonitors(NULL, NULL, enum_monitor, (LPARAM)&monitor);

    const HRESULT hr = interop_factory->CreateForMonitor(
        monitor.handle,
        winrt::guid_of<ABI::Windows::Graphics::Capture::
        IGraphicsCaptureItem>(),
        reinterpret_cast<void**>(
            winrt::put_abi(item)));
    if (FAILED(hr))
    {
        blog(LOG_ERROR, "CreateForMonitor (0x%08X)", hr);
        return false;
    }

    return true;
       
}```

if D3D11 is not supported，I will use OpenGL

Hope this method could help you
