### ISSUE TITLE
[Bug]: MediaMetadata cover not work

### ISSUE THREAD

**Issue by lu0se** [electron/electron#40469]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.3

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux x86_64

### What arch are you using?

x64

### Expected Behavior

When I run this code in firefox,it can show
![图片](https://github.com/electron/electron/assets/55630902/9d86b938-c1bf-4895-9ff4-058d87c958fe)

### Actual Behavior

when i run this code in electron,the cover can't show 
![图片](https://github.com/electron/electron/assets/55630902/44245370-7e16-4e17-9d0b-35303076961b)

### Testcase Gist URL

https://gist.github.com/lu0se/8d301adbeda5c0ba3566c4dd35dbe632

**Comment by codebytere** [comment]
@lu0se does it show in Chrome or Edge? Firefox is not based in Chromium.

**Comment by lu0se** [comment]
> @lu0se does it show in Chrome or Edge? Firefox is not based in Chromium.

yes 
![图片](https://github.com/electron/electron/assets/55630902/c42208be-ca94-4548-af98-b65ce918c0bc)

**Comment by xushengfeng** [comment]
you can use [MediaSession api](https://developer.mozilla.org/zh-CN/docs/Web/API/MediaSession)
This seems to be handled automatically by chrome, but Electron requires us to add it manually
