### ISSUE TITLE
showMessageBox dialog is not highlighting the default button on macOS

### ISSUE THREAD

**Issue by sami-azzam** [electron/electron#40466]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The default message box button should be highlighted 

### Actual Behavior

on macOS Sonoma (14.0), the default button isn't highlighted:

<img width="288" alt="image" src="https://github.com/electron/electron/assets/26723707/534195a9-119d-450b-aa24-7e41f9ab3fda">

Here is the code:
```typescript
const options: MessageBoxOptions = {
      type: "question",
      buttons: ["Delete", "Cancel"],
      defaultId: 1,
      cancelId: 1,
      title: "Confirm Delete",
      message: "Are you sure you would like to delete this item?",
      detail: "This action cannot be undone.",
    };

dialog.showMessageBoxSync(win, options);
```

@codebytere

**Comment by sami-azzam** [comment]
> @sami-azzam can't reproduce on macOS Sonoma with the provided code:
> 
> 
> 
> <img width="870" alt="Screenshot 2023-11-13 at 2 19 27 PM" src="https://github.com/electron/electron/assets/2036040/36abe00e-a151-4c19-a3a2-438f1ebb3913">
> 
> 

Hey, shouldn't the cancel button be colored in this case and nut just outlined?

**Comment by codebytere** [comment]
@sami-azzam i found this: https://developer.apple.com/forums/thread/737391

i'm not sure what our next steps are but i can poke at it.

**Comment by idjugostran** [comment]
You can try using the name 'Cancel ' with a space and remove 'cancelId'. It works in version 28.2.4.
```
const options: MessageBoxOptions = {
		type: "question",
		buttons: ["Delete", "Cancel "],
		defaultId: 1,		
		title: "Confirm Delete",
		message: "Are you sure you would like to delete this item?",
		detail: "This action cannot be undone.",
	};
	dialog.showMessageBoxSync(win, options);
```

<img width="319" alt="Снимок экрана 2024-02-28 в 18 42 57" src="https://github.com/electron/electron/assets/14208437/ec270776-a24b-40ca-b2d3-531a060ebfe6">

**Comment by mlaurencin** [comment]
@sami-azzam Does the code provide above fix your issue? If not, could you confirm which stable version of Electron this is still reproducible in?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
