### ISSUE TITLE
[Bug]: access_denied in CreateForMonitor

### ISSUE THREAD

**Issue by HuntCode** [electron/electron#40468]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.1.9,  21.4.1,  27.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro  22H2  19045.3570

### What arch are you using?

x64

### Expected Behavior

Electron app through C++ addons can capture monitor when run with admin Powershell or debug with admin VS2022 

### Actual Behavior

I developed A.dll with OSB libs(use IGraphicsCaptureItemInterop::CreateForMonitor)，when I write an addon.node with A.dll，it works fine when run with non-admin Powershell，but it doesn't work when run with admin Powershell. The results is same as I debug with VS2022

Three apps use A.dll :
      1) C#(wpf) app doesn't have a UAC shield,  when Administrator User Logon Windows, app works fine both when double click run and run as Administrator. I think the process level is right, so app works fine. If I switch Standard User Logon Windows, app works fine when double click run, but access_denied in CreateForMonitor when run as Administrator, in this case I think the process level or token info is not matched. 
      2）I also write a MFC demo with default UAC level（asInvoker), the running performance is the same as C# app
      3）Electron app through C++ addons(wrapped with A.dll),  when run use non-admin Powershell, it works fine, but it doesn't work when use admin Powershell（access_denied in CreateForMonitor）

I use VS2022 and log in to Windows as an administrator. I found that when I launch VS2022 and debug with electon app, it works fine, but it doesn't work when I launch VS2022 as an administrator. The running performance is the same as run with Powershell

so I'm confused，is it a program permission problem?

Some similar but unsolved issues:
 [Cannot use IGraphicsCaptureItemInterop::CreateForWindow with electron apps#111](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/111)
[winrt::hresult_access_denied in CreateForWindow in some cases#49](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/49)

In case 3), I write an Electron app through C++ addons(wrapped with A.dll), the dependence is 
Electron app->addon.node->A.dll->OBS libs(use IGraphicsCaptureItemInterop::CreateForMonitor)

| Windows User |Powershell |   Electron app    |
|----------|----------|----------|
|  Administrator |  click run(non-admin)  | work fine |
|  Administrator | Run as Admin  |  don‘t work |

| Windows User | Debug with VS2022|   Electron app    | C#     | MFC Demo |
|----------|----------|----------|----------|----------|
|  Administrator |  non-admin launch VS2022 | work fine |work fine |work fine |
|  Administrator | Admin launch VS2022 |  don‘t work |work fine |work fine |

Debug Electron app with VS2022(non-admin launch)
![image](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/assets/15995016/c631240d-7c8e-4874-9809-4fdff8b03cd5)
The IntegrityLevel is SECURITY_MANDATORY_MEDIUM_RID(8192) and the CreateForMonitor is OK, so can capture the monitor

Debug Electron app with VS2022(admin launch)
![image](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/assets/15995016/4c86ddde-690e-41bb-917e-46c244e7b147)
The IntegrityLevel is SECURITY_MANDATORY_HIGH_RID(12288) and the CreateForMonitor is access_denied, so can't capture the monitor

So I don't know if the electron has some constraint or something else?

Debug MFC app with VS2022(non-admin launch)
![image](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/assets/15995016/ba729a24-7cbd-4a42-90b5-b34c67c713d9)
The IntegrityLevel is SECURITY_MANDATORY_MEDIUM_RID(8192) and the CreateForMonitor is OK, so can capture the monitor

Debug MFC app with VS2022(admin launch)
![image](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/assets/15995016/8e70963e-ae6a-4770-837a-24f616767682)
The IntegrityLevel is SECURITY_MANDATORY_HIGH_RID(12288) and the CreateForMonitor is OK, so can capture the monitor

GetProcessIL is from [Cannot use IGraphicsCaptureItemInterop::CreateForWindow with electron apps #111](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/111)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
