### ISSUE TITLE
[Bug]: Applications rendering as blank due to shader cache corruption (backport chromium fix)

### ISSUE THREAD

**Issue by bbhtt** [electron/electron#40475]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.2

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 39

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

Applications should render fine

### Actual Behavior

Rendered as blank

### Testcase Gist URL

None

### Additional Information

This was reported as a Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1442633 and fixed there https://chromium-review.googlesource.com/c/chromium/src/+/4988290

The patch itself is fairly small and simple, would Electron please backport the change to all the current supported branches?

It seems to be in 28.0.0-beta3 but v28 stable is a long way away to be adopted by apps.

Reason for backporting:

1. The issue potentially affects all electron versions as a change in mesa caused the shader regeneration logic to fail
2. Mesa is outside of control of electron or app developers
3. There's no "good" workarounds - ask users to clear the GPUCache folder manually when the issue happens or disable shader cache at runtime - neither of which are optimal

It affects almost every major Electron app eg. 

https://github.com/microsoft/vscode/issues/190437
https://github.com/vector-im/element-desktop/issues/1074
https://github.com/laurent22/joplin/issues/9187
https://github.com/bitwarden/clients/issues/6732

**Comment by bbhtt** [comment]
Ah I just noticed https://github.com/electron/electron/pull/ 40467 which backports to v27.

I guess now the question is if it is possible for Electron 26 and 25

**Comment by VerteDinde** [comment]
@bbhtt Thanks for the issue! This seems like a pretty straightforward fix, I'll backport it into 26 and 25 as well. Typically we only backport security fixes into our oldest stable supported line (25, in this case), but this is such a small fix that I think it would be fine.

**Comment by VerteDinde** [comment]
Oh, looks like we have backports going for them already!

26-x-y: https://github.com/electron/electron/pull/40452
25-x-y: https://github.com/electron/electron/pull/40473

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/40452 - the 25-x-y one will be merged soon as well.

**Comment by bbhtt** [comment]
Many thanks!
