### ISSUE TITLE
[Bug]: Multi touch support on a multi window app

### ISSUE THREAD

**Issue by marcotw** [electron/electron#40482]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

I have several Browser Window and when I perform a touch action on one window, the others are not capable to handle the touch gesture performed on it.

### Actual Behavior

Every Browser Window should able to handle indipendently every touch gestures performed.

### Additional Information

I have an app that generate 4 different Browser Window:

```js
// Create number of window specified in windowsNumber
for (let index = 0; index < windowsNumber; index++) {

    //Create screen
    let screen = new BrowserWindow({
        autoHideMenuBar: true,
        webPreferences: {
            partition: 'persist:win' + index,
            contextIsolation: true,
            preload: path.join(__dirname, 'preload.js')
        }
    });

    //Load screen content
    if (process.env.VITE_DEV_SERVER_URL) {
        screen.loadURL(process.env.VITE_DEV_SERVER_URL);
    } else {
        screen.loadFile(`.output/public/index.html`);
    }

}
```

These 4 windows goes to 4 touch screen monitor.

The problem it's that when I perform a touch gesture on one monitor, the others don't listen their gesture anymore.

Seems that Electron is able to handle only one touch gesture at time in all the application.

It's possible to configure Electron (or develop a custom way) to handle the gesture of all window simultaneously and independently?

**Comment by mlaurencin** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
