### ISSUE TITLE
[Bug]: oom in renderer process doesn't cause minidump creation

### ISSUE THREAD

**Issue by origin-yaropolk** [electron/electron#40485]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2 19045.3570

### What arch are you using?

x64

### Last Known Working Electron version

21 and below

### Expected Behavior

OOM inside renderer processes should create minidump like for others crashes.

### Actual Behavior

It doesn't.

### Testcase Gist URL

https://gist.github.com/origin-yaropolk/b7e53398ea1ad6edc5d4950404b249d6

### Additional Information

It works as expected in macos
render-process-gone works in any case

**Comment by codebytere** [comment]
@origin-yaropolk do you know which version below 21 it last worked in?

**Comment by origin-yaropolk** [comment]
It seems I wrote it wrong. I meant 21 _and_ below) Last work version that I know was with 21.3.0 electron onboard.

**Comment by origin-yaropolk** [comment]
Regarding Linux, I recently created [an issue](https://github.com/electron/electron/issues/39073) that crashpad does not create a dump for renderers at all. But this applies to packaged snap only. I can test with the app unpacked if this information helps.

**Comment by origin-yaropolk** [comment]
@codebytere Tested at Linux mint 21.
Upackaged and packaged to deb app (Electron 27.0.0 onboard) creates dump as expected.
Packaged to snap does not.

**Comment by helloforrestworld** [comment]
bump 27.0.1
