### ISSUE TITLE
[Bug]: Certificate error example code has random ERR_CERT_AUTHORITY_INVALID in browser

### ISSUE THREAD

**Issue by MichaelJCole** [electron/electron#40499]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.4

### What operating system are you using?

Other Linux

### Operating System Version

Linux Mint 21.2

### What arch are you using?

x64

### Expected Behavior

The [event 'certificate-error' docs](https://www.electronjs.org/docs/latest/api/app#event-certificate-error) shows code for accepting a self-signed certificate.

```
app.on('certificate-error', (event, webContents, url, error, certificate, callback) => {
  if (url === 'https://github.com') {
    // Verification logic.
    event.preventDefault()
    callback(true)
  } else {
    callback(false)
  }
})
```

### Actual Behavior

The code doesn't work.  The browser is rejecting the certificate before the certificate-error event can run.  

When forcing a reload, the browser randomly rejects different files.
![image](https://github.com/electron/electron/assets/1504790/85b90a94-2b54-400c-ba87-9f3794d6d226)
Force reload
![image](https://github.com/electron/electron/assets/1504790/04c39e39-4a7c-4e80-bb3a-248b63470391)
Force reload
![image](https://github.com/electron/electron/assets/1504790/36c7f5e7-8122-47bf-a97a-6e60a800d3cb)
Sometimes it loads more or less, but it never loads everything.

In the shell console, this happens once, no matter how many windows are opened/closed:
```
[78714:1109/225610.775342:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for 127.0.0.1 failed:
----- Certificate i=0 (O=Internet Widgits Pty Ltd,ST=Some-State,C=AU) -----
ERROR: No matching issuer found

>>> certificate-error event happens here<<<
```

The browser white-screens and the browser console shows these errors:

```
Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
VM4 sandbox_bundle:2 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
  Policy set or a policy with "unsafe-eval" enabled. This exposes users of
  this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
error-404.4b819ffd.css:1 
 Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
error-dev.2fb198e3.css:1 
 Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
error-dev.2a3d0a96.js:1 
 Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
```

### Additional Information

I'm creating a 2nd BrowserWindow to preview a locally hosted website.  

I get the same behavior for 'https://127.0.0.1:8080/' and  'https://localhost:8080/'

**Comment by MichaelJCole** [comment]
Bah.  I found a workaround and can't make a reproduction that needs it.  

The workaround is to add this to the window's session:

```
    session.defaultSession.setCertificateVerifyProc((request, callback) => {
      const myUrl = new URL(PREVIEW_URL)
      if (request.hostname === myUrl.hostname) {
        callback(0)
      } else {
        callback(-3)
      }
    })
```

**Comment by alexandernovadev** [comment]
if you wish to track all the coincidences within the same domain.

   session.defaultSession.setCertificateVerifyProc((request, callback) => {
      const myUrl = new URL('https://MYWEB.com');
      if (request.hostname.includes(myUrl.hostname)) {
        callback(0); // trust the certificate
      } else {
        callback(-3);
      }
    });
