### ISSUE TITLE
Electron title on frameless windows when focus is lost

### ISSUE THREAD

**Issue by iamisti** [electron/electron#40494]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

26.4.1

### Expected Behavior

Losing focus on a transparent window should not add any title bar to it

### Actual Behavior

Losing focus on a transparent window will add an unwanted title bar to the window 

### Additional Information

Transparent window in focus:
![image](https://github.com/electron/electron/assets/4672916/2190172f-9fb4-4570-abdc-6fda5f4ad3cd)

Transparent window losing focus:
![image](https://github.com/electron/electron/assets/4672916/58a7c21d-de70-42ef-9191-f8af428902cd)

**Comment by iamisti** [comment]
I've successfully created the gits: https://gist.github.com/a930b0edf6a23abb775f60bd624ae2c5

Reproducible every time. It seems that the "backgroundThrottling: false" setting is triggering this issue.

Steps:
- run the gist
- focus on the semi-transparent window
- switch to a different window
- switch back to the semi-transparent window

Actual behavior:
- unwanted title is showing on the semi-transparent window

Expected behavior:
- no title showing on the semi-transparent window

**Comment by pyphkx** [comment]
I also encountered this problem. He first gets the title tag of the html. If it is empty, get the package.json name

**Comment by brhenrique** [comment]
Related issues

https://github.com/electron/electron/issues/40286
https://github.com/electron/electron/issues/39959

**Comment by codebytere** [comment]
Folding into https://github.com/electron/electron/issues/40286 as a duplicate.
