### ISSUE TITLE
[Bug]: No more Tray icons on several Electron based apps

### ISSUE THREAD

**Issue by dtrunk90** [electron/electron#40493]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

20.0.4.6 Budgie

### What arch are you using?

x64

### Expected Behavior

Ubuntu 20.04 is still supported. Budgie is version 10.5.1 so it still uses XEmbed (afaik they've adopted the Status Notifier specification in 10.8). Tray Icons should be displayed.

### Actual Behavior

Since several electron versions there are no more tray icons on several electron based apps. Whether it's discord, element or mattermost as examples.

**Comment by codebytere** [comment]
@dtrunk90 I understand that this is definitely frustrating, but at this point you should report this directly to the apps themselves. Once they've triaged it and it can be demonstrated it's an issue with core Electron and not their implementations, Electron's core team can look to triage this as a new bug.

**Comment by dtrunk90** [comment]
So, now it's reported for Element Desktop and I've already reported it some time ago for Mattermost. There are several explanations why it's an Electron issue and has nothing to do with "their implementations". Electron deprecated libappindicator. Yet, there are still supported operating systems which are using libappindicator. My workaround now is to hold mattermost updates so I'll stay forever on the old still working version. Please, fix it.

**Comment by devinbinnie** [comment]
@codebytere @dtrunk90 Mattermost Desktop dev here. So I'm guessing the issue being experienced is that libappindicator is no longer supported by Electron, which I assume is intentional correct? If so, then there might not be an actual bug here. If not, is there a plan to bring back support for it?

As a note, we are supporting `StatusNotifierItem` correctly AFAIK and it is working for us.
