### ISSUE TITLE
Atom shell processes sticking around when app closed (Windows)

### ISSUE THREAD

**Issue by frankhale** [electron/electron#405]
I've started to develop a simple application, not much beyond a Hello, World at this point. As I work through my Atom-Shell learning curve I am noticing that Atom Shell processes are sticking around when I close my app. I'm not really sure how to properly report this. I'm working with some very basic code that doesn't do a whole lot yet Atom-Shell processes are sticking around at random times even when I close the application. I noticed this by looking at Task Manager.

**Comment by lhalver1** [comment]
I was having the same problem. What seems to have fixed it for me was zcbenz answer. No longer have processes hanging around after I close my app.
