### ISSUE TITLE
[Bug]: electron-updater throwing SSL error in versions greater than v12.0.7

### ISSUE THREAD

**Issue by bmkgww** [electron/electron#40502]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0+

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.6 (22G120)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

12.0.7

### Expected Behavior

When attempting to auto update from a URL that requires client certificate it should successfully make the request to get the latest version and then begin updating.

### Actual Behavior

When fetching the auto-update URL on any version higher than 12.0.7 the request fails with this error message:  
```
[15:36:46.281] [info] Checking for update

[15:36:47.008] [error] Error: Error: net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49595)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)

(node:27164) UnhandledPromiseRejectionWarning: Error: net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49595)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
```

Downgrading to 12.0.7 resolves this issue in local development.

### Additional Information

We recently upgraded a legacy application from electron 10 to 25+ and this error has been stumping us for a while. We are unsure of a path around it other than changing the update URL to an insecure server (which seems to do the trick).

**Comment by MarshallOfSound** [comment]
The electron-updater npm module is not official / maintained by the electron team.  It has known issues and deficiencies.  We recommend using the built in autoUpdater module instead.
