### ISSUE TITLE
[Bug]: Undefined process.mainModule / require.main after 28.0.0-nightly.20230831

### ISSUE THREAD

**Issue by mxschmitt** [electron/electron#40501]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

electron-nightly@28.0.0-nightly.20230831

### What operating system are you using?

macOS

### Operating System Version

14.1.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

electron-nightly@28.0.0-nightly.20230828

### Expected Behavior

Its not undefined, like in normal Node.js.

Note: This repro does not use any ESM.

### Actual Behavior

Its undefined.

### Testcase Gist URL

https://gist.github.com/deb6bec291739ac591b811c6a5186dc0

### Additional Information

Downstream issue: https://github.com/microsoft/playwright/issues/28048
More complex Playwright repro: https://playwright.dev/docs/api/class-electron

Good npm install electron-nightly@28.0.0-nightly.20230828
Bad npm install electron-nightly@28.0.0-nightly.20230831

RANGE: https://github.com/electron/electron/compare/v28.0.0-nightly.20230828...v28.0.0-nightly.20230831

Most likely caused by https://github.com/electron/electron/pull/37535.

We need this in order get access to the electron object inside our code as per https://github.com/microsoft/playwright/blob/1b22c43c3546bc4363071b4dd0b164ea9bec5e36/packages/playwright-core/src/server/electron/electron.ts#L75.

**Comment by Alwyn88** [comment]
> ### Preflight Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.
> 
> ### Electron Version
> electron-nightly@28.0.0-nightly.20230831
> 
> ### What operating system are you using?
> macOS
> 
> ### Operating System Version
> 14.1.1
> 
> ### What arch are you using?
> arm64 (including Apple Silicon)
> 
> ### Last Known Working Electron version
> electron-nightly@28.0.0-nightly.20230828
> 
> ### Expected Behavior
> Its not undefined, like in normal Node.js.
> 
> Note: This repro does not use any ESM.
> 
> ### Actual Behavior
> Its undefined.
> 
> ### Testcase Gist URL
> https://gist.github.com/deb6bec291739ac591b811c6a5186dc0
> 
> ### Additional Information
> Downstream issue: [microsoft/playwright#28048](https://github.com/microsoft/playwright/issues/28048) More complex Playwright repro: https://playwright.dev/docs/api/class-electron
> 
> Good npm install electron-nightly@28.0.0-nightly.20230828 Bad npm install electron-nightly@28.0.0-nightly.20230831
> 
> RANGE: [v28.0.0-nightly.20230828...v28.0.0-nightly.20230831](https://github.com/electron/electron/compare/v28.0.0-nightly.20230828...v28.0.0-nightly.20230831)
> 
> Most likely caused by #37535.
> 
> We need this in order get access to the electron object inside our code as per https://github.com/microsoft/playwright/blob/1b22c43c3546bc4363071b4dd0b164ea9bec5e36/packages/playwright-core/src/server/electron/electron.ts#L75.

**Comment by Alwyn88** [comment]
> ### Preflight Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.
> 
> ### Electron Version
> electron-nightly@28.0.0-nightly.20230831
> 
> ### What operating system are you using?
> macOS
> 
> ### Operating System Version
> 14.1.1
> 
> ### What arch are you using?
> arm64 (including Apple Silicon)
> 
> ### Last Known Working Electron version
> electron-nightly@28.0.0-nightly.20230828
> 
> ### Expected Behavior
> Its not undefined, like in normal Node.js.
> 
> Note: This repro does not use any ESM.
> 
> ### Actual Behavior
> Its undefined.
> 
> ### Testcase Gist URL
> https://gist.github.com/deb6bec291739ac591b811c6a5186dc0
> 
> ### Additional Information
> Downstream issue: [microsoft/playwright#28048](https://github.com/microsoft/playwright/issues/28048) More complex Playwright repro: https://playwright.dev/docs/api/class-electron
> 
> Good npm install electron-nightly@28.0.0-nightly.20230828 Bad npm install electron-nightly@28.0.0-nightly.20230831
> 
> RANGE: [v28.0.0-nightly.20230828...v28.0.0-nightly.20230831](https://github.com/electron/electron/compare/v28.0.0-nightly.20230828...v28.0.0-nightly.20230831)
> 
> Most likely caused by #37535.
> 
> We need this in order get access to the electron object inside our code as per https://github.com/microsoft/playwright/blob/1b22c43c3546bc4363071b4dd0b164ea9bec5e36/packages/playwright-core/src/server/electron/electron.ts#L75.

**Comment by MarshallOfSound** [comment]
@mxschmitt Is there a reason you can't use `globalThis.require` instead of going the long way round via `process.mainModule` (which is hard deprecated in node fwiw)

**Comment by mxschmitt** [comment]
`globalThis` has unfortunately no `require` in this case, it only has these keys: `global, queueMicrotask, clearImmediate, setImmediate, structuredClone, clearInterval, clearTimeout, setInterval, setTimeout, atob, btoa, performance, fetch`.

It also had no `require` before this release, thats why we went the mainModule route.

**Comment by MarshallOfSound** [comment]
Do you actually need the whole electron object? You might be able to make do with just the linked bindings? `process._linkedBinding(name)`

Not how restoring this capability would look, the original definitely relied on some internals which we won't change back :/

**Comment by mxschmitt** [comment]
Yeah the whole object would be ideal, since we expose it to the user again, he can do [ElectronApplication.evaluate(electron => ...)](https://playwright.dev/docs/api/class-electronapplication#electron-application-evaluate) so he has access.

Ideally something like `globalThis[Symbol.for('electron')] = require('electron');` maybe only exposed in a special testing mode would be great for us.

**Comment by MarshallOfSound** [comment]
@mxschmitt Although I can replicate the error I'm not super familiar with playwright so debugging the internals appears to be a bit, _complicated_ 😆 

I will say that in isolation connecting a debugger to the Electron main process and executing `require('electron')` as pure code appears to work, logging the result of `require` for instance in a connected inspector shows a valid require function in Electron 28.  I'm not sure exactly how playwright is trying to eval this code but `require` is in the global scope (at least for the default app)

**Comment by mxschmitt** [comment]
Turns out we did not specify `includeCommandLineAPI: true` in our `Runtime.evaluate` CDP call. After specifying it it works as expected see https://github.com/microsoft/playwright/pull/28499 for further reference.

Feel free to close it (or I will once its merged).

**Comment by obsius** [comment]
@MarshallOfSound This simple test reproduces the issue:

electron@27:

```
PS D:\code\test\node_modules\.bin> ./electron.cmd test.js

[Function: require] {
  resolve: [Function: resolve] { paths: [Function: paths] },
  main: {
    id: '.',
    path: 'D:\\code\\test\\node_modules\\.bin',
    exports: {},
    filename: 'D:\\code\\test\\node_modules\\.bin\\test.js',
    loaded: false,
    children: [ [Object] ],
    paths: [
...
```

electron@28:

```
PS D:\code\test\node_modules\.bin> ./electron.cmd test.js

[Function: require] {
  resolve: [Function: resolve] { paths: [Function: paths] },
  main: undefined,
...
```

test.js contents:

```
console.log(require);
```

`require.main` is undefined in v28, but was an object with additional properties prior. Probably related to ESM support, but this difference in `require.main` is not listed under breaking changes.

**Comment by a-leithner** [comment]
@MarshallOfSound Can this please be reopened? Setting custom resolution paths is currently impossible with this breaking change because the `require` object is reset for every new required module, which makes it impossible to monkey-patch the `require.main` object in and thus all changes made to `require.main` and `require.main.paths` are lost.

**Comment by mxschmitt** [comment]
@obsous @a-leithner I recommend filing a new bug since this one about Playwright got fixed on our side.

**Comment by a-leithner** [comment]
But that would be a duplicate of this one, wouldn't it? The testcase Gist isn't related to Playwright and still exhibits this issue.

**Comment by MarshallOfSound** [comment]
We wont be reverting the change that removed require.main, it's a side effect of moving the internal electron entry point to ESM.

This issue was valid because we wanted to support the playwright use case but we were never gonna bring back require.main or process.mainModule.

**Comment by a-leithner** [comment]
Oh great, so CommonJS will remain broken like this forever? If this is not going to be fixed, I guess opening a new issue won't make any difference either, right?
