### ISSUE TITLE
[Feature Request]: Override `location.href` getter with custom value

### ISSUE THREAD

**Issue by DRSDavidSoft** [electron/electron#40509]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I would like to load a page from the local disk into Electron.js, load some third-party libraries, and override the value of `location.href` to be something other than the `file://` URL (for example, it should appear to be `https://www.mywebsite.com/foo/bar`.

### Proposed Solution

Provide a native method to override the value of `location.href` without actually navigating to an other page.

### Alternatives Considered

Initially I though I could achieve this with something like this:

```javascript
// Create a Proxy for the location object
const fakeLocation = new Proxy(window.location, {
  get: function(target, prop) {
    // Check if the accessed property is 'href'
    if (prop === 'href') {
      // Return the custom URL instead of the actual one
      return 'https://example.com/custom/page';
    }
    // For other properties, return the original location object's property value
    return target[prop];
  }
});

// Override the location object with the fakeLocation object
Object.defineProperty(window, 'location', {
  value: fakeLocation,
  writable: false,
  configurable: false,
  enumerable: true
});
```

However, I get the following exception: **`Cannot redefine property: location`**, and rightfully so.

Another approach would be to actually attempt to make a request to the destination, and intercepting it like so:

```javascript
session.defaultSession.webRequest.onBeforeRequest((details, callback) => {
  // Modify or handle the request as needed
  console.log('Intercepted Request:', details);

  // Send a custom response without satisfying the request
  const customResponse = {
    statusCode: 200,
    headers: { 'Content-Type': 'text/plain' },
    body: 'This is a custom response'
  };
  callback(customResponse);
});
```

This seems less than ideal to me, and I don't believe it would work in this context.

### Additional Information

To avoid this being an [XY Problem](https://xyproblem.info/), let me explain the use case, I simply want to render reCAPTCHA in my Electron app and avoid running a web server (`localhost`) for a simple task like this (as suggested [here](https://stackoverflow.com/q/41584833/1454514)). This should be a simple task, don't we/shouldn't we have complete control over the environment and the `window` object?

**Comment by MarshallOfSound** [comment]
> Another approach would be to actually attempt to make a request to the destination, and intercepting it like so:

This is the _correct_ way of doing the (questionable) thing you're trying to do.  Just overriding `window.location` isn't enough as captcha also verifies certain headers (origin, referrer, etc.) and other things that you'd also have to override.  Implementing support explicitly for messing with recaptcha isn't the business Electron really wants to get into.

The "correct" way to do this is host a legit website (external to the app) or to use a custom protocol and somehow allowlist that protocol (`my-app` or something) in the google developer console
