### ISSUE TITLE
[Bug]:  --lang parameter does not work for certain locales: `en-AU`, `de-DE` etc

### ISSUE THREAD

**Issue by darkydarkjason** [electron/electron#40516]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.4.3

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.6.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Setting electron . --lang=en-AU will set the locale to en-AU and --lang=de-DE will set the locale to de-DE.
app.getLocale() returns 'en-AU` and `de-DE`.

### Actual Behavior

Setting electron . --lang=en-AU will set the locale to en-AU and --lang=de-DE will set the locale to de-DE
app.getLocale() actually returns `en` for both 'en-AU` and `de-DE`.

*Only --lang=de makes app.getLocale() return `de`.

**Comment by darkydarkjason** [comment]
Also `zh-CN`, `zh-TW` as well, app locale only gets updated correctly when you pass `zh` to lang flag, otherwise it defaults to `en`

**Comment by darkydarkjason** [comment]
Same issue applying to setting language locale as `fr-CA`, it's unrecognised and defaults to `en-US` and to fix it we have to pass  `fr`  instead of `fr-CA` to --lang.

**Comment by codebytere** [comment]
This is unfortunately an upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1240990. I recommend commenting on that existing issue or filing a new one. We don't control that code within Electron, so we would inherit a fix when it is addressed upstream.
