### ISSUE TITLE
[Bug]: cannot group windows under the same native tabbing identifier

### ISSUE THREAD

**Issue by bpasero** [electron/electron#40529]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.4

### What operating system are you using?

macOS

### Operating System Version

14.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When opening windows on the same `tabbingIdentifier`, I would expect the windows to all show in the same tab group.

### Actual Behavior

Windows open separately.

### Testcase Gist URL

https://gist.github.com/rssowlreader/a96c38adb4be4e5930590b184e8fc5c0

**Comment by codebytere** [comment]
@bpasero 

> I  would expect the windows to all show in the same tab group.

this unfortunately isn't the expected behavior - what this property indicates is the _ability_ to group them together, like so: 

![group_tab_identifier](https://github.com/electron/electron/assets/2036040/b4b4bfb8-e9c2-40e5-ae5e-aa5344a9a6bd)

It doesn't automatically group them.

**Comment by bpasero** [comment]
@codebytere so when a macOS application is grouped together in native tabs and quits, you cannot restore this state back when the application opens again?
