### ISSUE TITLE
[Bug]: macOS text replacements autocomplete is in the wrong position

### ISSUE THREAD

**Issue by mayacoda** [electron/electron#40520]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.4

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When typing text in an input which matches a macOS text replacement, the autocomplete field should appear underneath the input.

### Actual Behavior

The autocomplete field appears offset to the right and bottom from the input field, specifically double the position of where it should be.

![2023-11-14 at 10 48 39@2x](https://github.com/electron/electron/assets/6614995/82f5463d-402b-4fd3-9527-f6226683a452)

### Testcase Gist URL

https://gist.github.com/f7177bd9706bfbb02618d5930ad9ccc4

**Comment by codebytere** [comment]
hi maya! i will look at this soon :)

**Comment by codebytere** [comment]
Fixed in https://github.com/electron/electron/pull/40534
