### ISSUE TITLE
[Bug]: Video hardware acceleration not working on Ubuntu/Lubuntu

### ISSUE THREAD

**Issue by miguel-cagide** [electron/electron#40521]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.4

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04, Lubuntu 22.04

### What arch are you using?

x64

### Last Known Working Electron version

24.8.8

### Expected Behavior

On Ubuntu 22.04/Lubuntu 22.04 with a correctly configured Intel GPU. Electron 24.8.8 (also works on electron 17) shows video decoders when launching with needed CLI switchs .
![decoders_24](https://github.com/electron/electron/assets/36760317/b89333bc-129e-4356-ad96-7ed76b9d8708)
This enables hardware decoding (at least for supported codecs) .

### Actual Behavior

Video hardware acceleration not working, checking chrome://gpu video decoders list shows no decoders (empty list).
And acceleration does not work. Using the same CLI command, no decoders are loaded.
![decoders_27](https://github.com/electron/electron/assets/36760317/64d10179-eb2d-453d-8972-aee8930bf4f7)
And hardware decoding does not work.

### Testcase Gist URL

https://gist.github.com/miguel-cagide/8de44cdbeaf6d15896a25d62407a0ebd

### Additional Information

It only works for electron 17/24. Testing i can see that other versions (19 onwards) do not work.

**Comment by jtbandes** [comment]
Hi, did you find any workaround or root cause for this?

**Comment by miguel-cagide** [comment]
> Hi, did you find any workaround or root cause for this?

Nope, sadly i fixed electron version to 24, i still have to check newer versions, but if it's not fixed soon probably i'll be switching to python/libmpv or  .net core/libmpv (as both works on amd64/arm64 build).

**Comment by mtinnes** [comment]
Is there a specific reason for acceleration not being enabled by default? We are struggling to play video at an acceptable frame rate and there does seem to be a workaround without having to build electron and apply some patches? Our GPU is requires VAAPI which does work well on Firefox and Chromium, however Electron is pegging the CPU with no GPU usage regardless of the flags we have supplied.

**Comment by miguelcagidefagin** [comment]
> Is there a specific reason for acceleration not being enabled by default? We are struggling to play video at an acceptable frame rate and there does seem to be a workaround without having to build electron and apply some patches? Our GPU is requires VAAPI which does work well on Firefox and Chromium, however Electron is pegging the CPU with no GPU usage regardless of the flags we have supplied.

It looks like 3D acceleration can be enabled without problem. But, also looks like the embedded chromium has no video codecs included.
