### ISSUE TITLE
[Bug]: While focusing the frameless renderer process(title glitch)

### ISSUE THREAD

**Issue by KarthikeyanKanniappan** [electron/electron#40543]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 pro 

### What arch are you using?

x64

### Last Known Working Electron version

26.4.1

### Expected Behavior

While focusing on the frameless window, a glitch occurs where the title of the window is displayed.

### Actual Behavior

While focusing on the frameless window, a glitch should not occurs.

### Testcase Gist URL

https://gist.github.com/KarthikeyanKanniappan/4e1c24071bbde1a486f5520dd1092627

### Additional Information

![Electron-fiddle screenShot](https://github.com/electron/electron/assets/105141303/6c8c225e-920f-4861-acf8-1fb8dba44c92)

When focusing on the frameless window, a title glitch is observed at the backside of the window, becoming visible when it is in focus.

**Comment by theolivenbaum** [comment]
Same here, happens on the latest 27.1.0:
![image](https://github.com/electron/electron/assets/8791811/3fcfd095-62aa-4d94-bfd5-ff2ffbfd6ce7)

**Comment by codebytere** [comment]
Folding into https://github.com/electron/electron/issues/40286 as a duplicate.
