### ISSUE TITLE
[Bug]: Chrome/120.0.6099.18 in 28 beta version is not working

### ISSUE THREAD

**Issue by PatONeil** [electron/electron#40549]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Navigator.share is not working.   Should be working on Chrome/120.0.6099

### Actual Behavior

Message when trying to use "Sharing is not supported by this browser"

### Testcase Gist URL

(https://gist.github.com/341b459ed716e4e01e6138563c7600a8)

**Comment by PatONeil** [comment]
Test case for issue as Electron Fiddle
https://gist.github.com/341b459ed716e4e01e6138563c7600a8

**Comment by codebytere** [comment]
@PatONeil does that same code work in Google Chrome on the same machine?

Does this code? https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by PatONeil** [comment]
Yes Get Outlook for Android

**Comment by PatONeil** [comment]
Has anyone looked at adding navigator.share support to electron.   I need it for my application as way to send emails and text messages.   The version of chrome supports this functionality and I don't know why its not include in Elecctron.
