### ISSUE TITLE
[Bug]: XDG Base Directory Specification: Incorrect path ~/.pki/nssdb is used

### ISSUE THREAD

**Issue by BoostCookie** [electron/electron#40548]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.9.4

### What operating system are you using?

Other Linux

### Operating System Version

Linux geher-pc 6.1.62-1-lts #1 SMP PREEMPT_DYNAMIC Fri, 10 Nov 2023 19:17:13 +0000 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

For nss, electron should use `$XDG_DATA_HOME/pki/nssdb` where `$XDG_DATA_HOME` defaults to `~/.local/share`.
This is now the default behaviour of nss.
https://hg.mozilla.org/projects/nss/rev/da45424cb9a0b4d8e45e5040e2e3b574d994e254
https://bugzilla.mozilla.org/show_bug.cgi?id=818686

### Actual Behavior

For some reason electron still creates the old `~/.pki/nssdb`.

**Comment by BoostCookie** [comment]
OK, I think the issue is with chromium which electron uses.
https://src.chromium.org/viewvc/chrome?revision=23057&view=revision
https://bugs.chromium.org/p/chromium/issues/detail?id=16976
https://bugs.chromium.org/p/chromium/issues/detail?id=1038587

Maybe using the latest version of chromium for electron would fix the issue.

**Comment by codebytere** [comment]
@BoostCookie we have an existing Chromium update process - if this is changed upstream we will inherit that change. In the meantime, you should comment on the existing issues you linked or file a new issue to indicate interest.
