### ISSUE TITLE
[Bug]: Doesnt work "window.matchMedia("(prefers-color-scheme: dark)");" on Linux

### ISSUE THREAD

**Issue by morfyum** [electron/electron#40559]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.3.13

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 39

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

window.matchMedia("(prefers-color-scheme: dark)");

when "dark" returnt "true"

### Actual Behavior

window.matchMedia("(prefers-color-scheme: dark)");

When "dark" return "false"

### Additional Information

I test in google-chrome, and firefox, and work without issue!
Only Electron can't recognize this.

Please fix.

**Comment by codebytere** [comment]
Should be fixed in https://github.com/electron/electron/pull/38977 - 23 is no longer a supported version so it will not receive the fix.

**Comment by morfyum** [comment]
Thank you so much! True! Work with 27.x
I dont know why have I installed older version.
Sorry
