### ISSUE TITLE
[Bug]: BrowserWindow.setShape cause app background black in win 10 1809 version when rect array over one with electron version 27.1.0

### ISSUE THREAD

**Issue by wuang1992** [electron/electron#40552]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 1809

### What arch are you using?

x64

### Expected Behavior

app background color not change to black

### Actual Behavior

when rect over 1, app background change to black, even if i set window background transparent

**Comment by wuang1992** [comment]
app.disableHardwareAcceleration() can resolve this issue, but  i think it is not a good solution。

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
