### ISSUE TITLE
[Bug]: Missing CSD Shadows for apps that have custom window decorations

### ISSUE THREAD

**Issue by RushingAlien** [electron/electron#40575]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux rolling

### What arch are you using?

x64

### Expected Behavior

For apps that draw their own window decorations to have CSD shadows, affects GNOME and Weston
Example apps : Logseq, Visual Studio Code with custom titlebar enabled

### Actual Behavior

Apps are missing shadow decoration

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by RushingAlien** [comment]
Sorry I  don't have the expertise to code in  the Fiddle app
to replicate would be
- use an electron app with custom window decor on Linux
- use it on gnome desktop or weston, WM
- run it with --ozone-platform=wayland
- see missing window shadow
