### ISSUE TITLE
[Bug]: Application menu is not switching properly

### ISSUE THREAD

**Issue by diksha-2020** [electron/electron#40591]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 pro

### What arch are you using?

x64

### Last Known Working Electron version

23.1.0

### Expected Behavior

The back to back switching between application menu options should work.

### Actual Behavior

My application menu has View, Window and one custom menu option .
When I try to switch between them continuously , its gets stuck on previous menu option's submenu list.

Note: The switching between menus is fast than usual practice.

Any help would be appreciated.

Thanks.

### Additional Information

Used buildFromTemplate to create a menu.
Rf: 
```
const menu = Menu.buildFromTemplate(template);
Menu.setApplicationMenu(menu);
```

**Comment by diksha-2020** [comment]
Thanks for looking into this issue @codebytere .
Here is the link of a sample code [https://gist.github.com/diksha-2020/6fb7995d94965ab28d40dc0df1b063a1 ](url).
Looking forward for your response.

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

If you’re still experiencing this issue in Electron 26.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by diksha-2020** [comment]
Hi @mlaurencin ,

Thanks for answering the doubt. 
I had a change request for single menu only. I would not able be able to switch version to latest one and share the updates further.
Thanks for your support. 

All d best!!

**Comment by mlaurencin** [comment]
Unfortunately, since a supported version of Electron cannot be used, this issue will be closed.

If you are able to update to a supported version in the future, and are still experiencing this problem, please file a new issue for that version of Electron.
