### ISSUE TITLE
[Bug]:  Getting ERR_NO_SUPPORTED_PROXIES when trying to load a url with proxy set

### ISSUE THREAD

**Issue by alintintesan** [electron/electron#40590]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Build 19042

### What arch are you using?

x64

### Expected Behavior

The page should load without any isses with proxy set.

### Actual Behavior

The page won't load at all and a ERR_NO_SUPPORTED_PROXIES error is thrown in the electron console.
The proxy is set successfully with:
const proxyConfig = {
proxyRules: "proxyURL"
};
webContents.session.setProxy(proxyConfig).then(() => ...).catch((e) => ...);

Error:
(node:4600) UnhandledPromiseRejectionWarning: Error: ERRO_NO_SUPPORTED_PROXIES (-336) loading 'https://integ-master.ftdigitallab.valueedge.saas.microfocus.com/integration8/en/#/wizard/deviceStandalone?jobId=xxxxxxx'
at rejectAndCleanup (node:electron/js2c/browser_init:2:77633)
at EventEmitter.failListener (node:electron/js2c/browser_init:2:77846)
at EventEmitter.emit (node:events:513:28)

**Comment by wave314** [comment]
@alintintesan Hello, has this problem been solved? I've encountered the same issue.
