### ISSUE TITLE
[Bug]: crash dir cannot find the .dmp file

### ISSUE THREAD

**Issue by TJ666** [electron/electron#40617]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

9.4.4

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 12.2.3

### What arch are you using?

x64

### Last Known Working Electron version

9.4.4

### Expected Behavior

I want to test crashReporter in my local Mac env, the crash dir has been created, but cannot find dmp file. My steps are as follows:
1.  app.setPath('crashDumps', fileLog.getFilePath(0) + '/crash');
2. `crashReporter.start({
    submitURL: 'http://127.0.0.1:9001/crash',
    rateLimit: false,
    uploadToServer: true,
    ignoreSystemCrashHandler: false,
    autoSubmit: true
});`
3. `setTimeout(() => {
    process.crash();
}, 20 * 1000);`
4. Expected create dmp file, and post to my local node server.

### Actual Behavior

I want to test crashReporter in my local Mac env, the crash dir has been created, but cannot find dmp file. My steps are as follows:
1.  app.setPath('crashDumps', fileLog.getFilePath(0) + '/crash');
2. `crashReporter.start({
    submitURL: 'http://127.0.0.1:9001/crash',
    rateLimit: false,
    uploadToServer: true,
    ignoreSystemCrashHandler: false,
    autoSubmit: true
});`
3. `setTimeout(() => {
    process.crash();
}, 20 * 1000);`
4. Create crash dir automaticlly, but can not find dump file in 'new/pending/completed' dir;
![image](https://github.com/electron/electron/assets/17919231/299305d6-8895-4982-965e-34ff42cd0740)

**Comment by TJ666** [comment]
My colleagues can also reproduce it.  We look forward to your reply.

**Comment by codebytere** [comment]
Electron 9.4.4 isn't supported and hasn't been in many years. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days f there is no response.
