### ISSUE TITLE
[Bug]: Crash reporter receiver server cannot get the dump file and other params

### ISSUE THREAD

**Issue by TJ666** [electron/electron#40620]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 12.2.3

### What arch are you using?

x64

### Expected Behavior

Expected:
The crash report server could receive the crash report payload, such as "upload_file_minidump", my extra params. Besides, the request body should be normal.

### Actual Behavior

1. Mock crash and report crash file:
```
const { app, BrowserWindow, crashReporter } = require('electron')
const path = require('path')

app.setPath('crashDumps', path.join(__dirname, 'crash'));

crashReporter.start({
    submitURL: 'http://127.0.0.1:3000/crashreports',
    autoSubmit: true,
    extra: {
        userId: '123456'
    },
});

let crashDumpsDir = app.getPath('crashDumps');


setTimeout(() => {
    process.crash();
}, 2 * 1000);
```

2. The submitURL server provide post API, but cannot get the request body,file,and params. My code as follow:
```
const express = require('express'),
  multer = require('multer'),
  path = require('path'),
  fs = require('fs'),
  http = require('http'),
  miniDumpsPath = path.join(__dirname, 'app-crashes');

const bodyParser = require('body-parser');
const compression = require('compression')


const app = express(),
  server = http.createServer(app);

app.use(bodyParser.json());
app.use(compression());
app.use(bodyParser.urlencoded({ extended: true }));

let upload = multer({
  dest: miniDumpsPath
}).single('upload_file_minidump');

app.post('/crashreports', upload, (req, res) => {
    req.body.filename = req.file.filename
    const crashData = JSON.stringify(req.body);
    fs.writeFile(req.file.path + '.json', crashData, (e) => {
        if (e){
        return console.error('Cant write: ' +  e.message);
        }
        console.info('crash written to file:\n\t' + crashData);
    })
    res.end();
});

app.get('/', (req, res) => {
    res.end('Hello World!');
});

server.listen(3000, () => {
  console.log('running on port 3000');
});
```

3. The debug context:
<img width="1004" alt="infoflow 2023-11-27 21-24-01" src="https://github.com/electron/electron/assets/17919231/0a615b92-0c12-4433-b4b4-2c0167f3b223">
<img width="887" alt="infoflow 2023-11-27 21-24-46" src="https://github.com/electron/electron/assets/17919231/fc55099d-9dcc-4a72-9c7a-7141c1622e36">

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
