### ISSUE TITLE
[Bug]: Modal child window loses titlebar on Mac

### ISSUE THREAD

**Issue by gpetrov** [electron/electron#40673]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Windows

### Operating System Version

MacOS 

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When a modal popup window is displayed with framd and title, it should show them on top of the window, together with the minimize, maximize and close buttons. On the Mac that will be the traffic lights.

### Actual Behavior

The modal popup window gets displayed without titlebar and traffic lights on Mac:

![image](https://github.com/electron/electron/assets/504730/f16d4582-b5cb-4437-b012-ff9d24fb6ca0)

On Windows it displays as it should, with titlebar:

![image](https://github.com/electron/electron/assets/504730/3e9a9cbf-46b5-4346-b311-748be5d1b304)

On Ubuntu Linux it displays well but still missed minimize and maximize buttons:

![image](https://github.com/electron/electron/assets/504730/a425388d-4a9d-48de-8917-7d1c2f0e2ef9)

### Testcase Gist URL

https://gist.github.com/gpetrov/e980776cec63df96da35792c1a0dc523

### Additional Information

1.  Open the test fiddle
2. Click on the "popup" button to open the modal popup
3. The popup displays but without a titlebar on mac

**Comment by abhijith94** [comment]
Can confirm that this issue exists on MacOS Sonoma 14.2.1(arm64).

**Comment by gpetrov** [comment]
Bump

**Comment by mqliutie** [comment]
closed.............

**Comment by mqliutie** [comment]
Not only titlebar is lost but also the modal window can not be closed. I have clicked out of modal window, modal window not be closed

**Comment by gpetrov** [comment]
@codebytere please reopen or should I post a new issue?
