### ISSUE TITLE
[Bug]: Child window on full screen parent results in blank window on Mac

### ISSUE THREAD

**Issue by gpetrov** [electron/electron#40672]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

macOS

### Operating System Version

MacOS 

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When the main window is in full screen mode and a child window is opened and closed the main window should be displayed.

### Actual Behavior

When the main window is in full screen mode and a child window is opened that has as parent the main window, the child window also opened in full screen, but when closed the main window becomes black and the application can only be killed

Happens on all Electron versions including the latest 28 beta

### Testcase Gist URL

https://gist.github.com/gpetrov/5e48ebf4e733e4c7ea5b6c86e199ec5c

### Additional Information

1. Open the test fiddle and run it on mac. It will open the main window in full screen mode.
2. Then click on the "Popup" button
3. It will open the popup - also in full screen mode
4. Close the popup by clicking on the "close" button
5. The child window is closed and focus is returned to the main window - but it is blank.
6. Application can only be killed

**Comment by gpetrov** [comment]
@codebytere maybe you can have a look? Seems like a critical mac window rendering issue.

**Comment by codebytere** [comment]
@gpetrov sure - i'd also like your thoughts on https://github.com/electron/electron/issues/39572#issuecomment-1691431363, since i think the two potential solutions are likely to be related.

**Comment by gpetrov** [comment]
stll happens even in the latest Electron 30 beta 7
