### ISSUE TITLE
[Bug]: Alert dialog opened from `BrowserView` causes application crash when dismissed after destroying the `BrowserView`

### ISSUE THREAD

**Issue by FrankenApps** [electron/electron#40683]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.3

### What operating system are you using?

Windows

### Operating System Version

Microsoft Windows 11 Pro 10.0.22621 Build 22621

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

Either the dialog should be closed / destroyed when the owing `BrowserView` is destroyed or nothing should happen when the user clicks the button on the alert dialog.

### Actual Behavior

The alert popup stays open even after the owning `BrowserView` was destroyed. After clicking on the **OK** button, the application crashes with code `3221225477`.

The full message is:
```
Electron exited with code 3221225477.
```

### Testcase Gist URL

https://gist.github.com/FrankenApps/c32d0433a92ba62f4d4005a464fe493d

### Additional Information

On MacOS the popup stays open after the owning `BrowserView` was destroyed, but the application does not crash when the **OK** button is clicked.

Ideally though I think that the alert dialog should be closed once the `BrowserView` is removed from the window. In any case it must be removed at least once the associated `webContents` are destroyed, because it would otherwise cause the crash on windows.

**Comment by nornagon** [comment]
Closing this as I believe this is resolved with the new BrowserView implementation in 29.x. Reopen if that's not the case.
