### ISSUE TITLE
[Bug]: WebGL not working

### ISSUE THREAD

**Issue by OmegaRogue** [electron/electron#40684]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.9.5

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Last Known Working Electron version

27.1.3

### Expected Behavior

WebGL and PixiJS works

### Actual Behavior

Errors:
```
WebGL: INVALID_OPERATION: useProgram: program not valid
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use
PixiJS Error: Could not initialize shader.
PixiJS Warning: gl.getProgramInfoLog() Program binary could not be loaded. Binary is not compatible with current driver/hardware combination. Driver build date Nov 16 2023. Please check build information of source that generated the binary.
PixiJS Error: Could not initialize shader.
PixiJS Warning: gl.getProgramInfoLog() Program binary could not be loaded. Binary is not compatible with current driver/hardware combination. Driver build date Nov 16 2023. Please check build information of source that generated the binary.
THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: Program binary could not be loaded. Binary is not compatible with current driver/hardware combination. Driver build date Nov 16 2023. Please check build information of source that generated the binary.
``` 
Blank Canvases, no render output since GPU Driver update

### Additional Information

NVIDIA driver version 545.29.06-2
Kernel 6.6.3-arch1-1

using PixiJS
Program: https://github.com/OmegaRogue/fvtt-player-client

**Comment by OmegaRogue** [comment]
> 
> 
> Hello @OmegaRogue. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the https://github.com/electron/electron/labels/blocked%2Fneed-repro label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

This is a system specific issue, unrelated to specific electron code

**Comment by codebytere** [comment]
> This is a system specific issue, unrelated to specific electron code

Then it is not something that should be on our issue tracker. I recommend reporting it upstream to Chromium.

**Comment by OmegaRogue** [comment]
> > This is a system specific issue, unrelated to specific electron code
> 
> Then it is not something that should be on our issue tracker. I recommend reporting it upstream to Chromium.

The problem isn't occurring in upstream chromium, only here

**Comment by Palashxeuron** [comment]
my app has also suddenly started showing this error at two places, on where threejs was rendering the scene and another where mediapipe task vision was trying to draw the pose.

**Comment by sadkodev** [comment]
I also have the same problem. All my graphic card settings are perfect. The issue comes from electron. In my case, I have the difficulty when I want to open the graph view in Obsidian and I get the error.

**Comment by Palashxeuron** [comment]
Maybe this helps but I have seen that in my case when i create and login to new linux user the problem is rectified. can anyone else confirm if its the case for them too?

**Comment by strattonbrazil** [comment]
Not sure whether an Electron bug or a PixiJS, but based on the comment from @Palashxeuron I blew away my Electron cache and the error went away. 
```
$ rm -rf ~/.config/Electron/
```

**Comment by RPGillespie6** [comment]
Interesting, destroying the cache worked for me too. Is there a way to disable electron cache? I don't want my users to have to manually delete caches if webgl suddenly stops working
