### ISSUE TITLE
No Cut/Copy/Paste context menus on <input> fields

### ISSUE THREAD

**Issue by alexandrudima** [electron/electron#4068]
From Microsoft/vscode#1578
- Tried in Electron v0.35.6
- Edit the default app `index.html`
- Add a `<textarea>`:

```
  <p>
  Or you can just drag your app here to run it:
  </p>

<textarea>
SOME TEXT HERE
</textarea>
```
- Righit click
  > Observe, no context menu appears:

---

![image](https://cloud.githubusercontent.com/assets/5047891/12263146/223277de-b92d-11e5-8600-1ec2fef718ad.png)

**Comment by zcbenz** [comment]
Only devtools has context menu by default in Electron, for all other elements you have to implement the menus on your own. It would be nice to have default context menu for native input elements though.

Refs #3210.

**Comment by parro-it** [comment]
It would be useful to have a userland module that implement this. @alexandrudima if you'll write one, you can find my [debug-menu](https://github.com/parro-it/debug-menu) module useful as an example. Otherwise, I could develop it...

**Comment by raleksandar** [comment]
Adding context menus to all inputs/textarea's is simple:

```js
'use strict';

const electron = require('electron');
const remote = electron.remote;
const Menu = remote.Menu;

const InputMenu = Menu.buildFromTemplate([{
        label: 'Undo',
        role: 'undo',
    }, {
        label: 'Redo',
        role: 'redo',
    }, {
        type: 'separator',
    }, {
        label: 'Cut',
        role: 'cut',
    }, {
        label: 'Copy',
        role: 'copy',
    }, {
        label: 'Paste',
        role: 'paste',
    }, {
        type: 'separator',
    }, {
        label: 'Select all',
        role: 'selectall',
    },
]);

document.body.addEventListener('contextmenu', (e) => {
    e.preventDefault();
    e.stopPropagation();
   
    let node = e.target;

    while (node) {
        if (node.nodeName.match(/^(input|textarea)$/i || node.isContentEditable) {
            InputMenu.popup(remote.getCurrentWindow());
            break;
        }
        node = node.parentNode;
    }
});
```

Just put that in render process somewhere

**Comment by adv0r** [comment]
@raleksandar thanks for the snippet. FYI :  A closing parenthesis is missing in the condition for the nodeName

**Comment by NielsLeenheer** [comment]
Showing a default context menu on native input elements would is something that should be enabled by default. Manually scripting this behaviour is not always possible. For example, when loading external content such as an OAuth login from an external service.

**Comment by vulture** [comment]
The suggested workaround is a nice stopgap, but it's useless as a fix. The native OS context menu has vitally important options especially for internationalized versions of Windows, like RTL ordering, IME options, etc. This really needs to get fixed.

This also appears to be a systemic problem (not showing native context menus) in other places in Electron. For example, the taskbar context menu (right click in vista-, shift+right click on w7+) does not work at all (nothing shows up).

**Comment by parro-it** [comment]
I just published a module that provide input menu, originally based on @raleksandar example code. You give it a shot here: https://github.com/parro-it/electron-input-menu.

It work as a context menu middleware for [electron-contextmenu-middleware](https://github.com/parro-it/electron-contextmenu-middleware).

**Comment by odedhb** [comment]
Use this nifty trick:

    const {remote} = require('electron');
    const {Menu} = remote;

    window.addEventListener('contextmenu', (e) => {
        e.preventDefault();
        Menu.getApplicationMenu().popup(remote.getCurrentWindow());
    }, false);

**Comment by dogrocker** [comment]
Adding context menu to textField based on @raleksandar reply.

Difference is use this on main process.

```
mainWindow.webContents.on('context-menu', (e, props) => {
    const InputMenu = Menu.buildFromTemplate([{
        label: 'Undo',
        role: 'undo',
    }, {
        label: 'Redo',
        role: 'redo',
    }, {
        type: 'separator',
    }, {
        label: 'Cut',
        role: 'cut',
    }, {
        label: 'Copy',
        role: 'copy',
    }, {
        label: 'Paste',
        role: 'paste',
    }, {
        type: 'separator',
    }, {
        label: 'Select all',
        role: 'selectall',
    },
    ]);
    const { inputFieldType } = props;
    if (inputFieldType === 'plainText') {
      InputMenu.popup(mainWindow);
    }
  });
```

**Comment by mobitar** [comment]
Building on @odedhb's answer, you can trigger just the Edit menu of the main window's menu using:

```
<script>

const {remote} = window.nodeRequire('electron')
const {Menu, MenuItem} = remote

window.addEventListener('contextmenu', (e) => {
    e.preventDefault();
    var mainMenu = Menu.getApplicationMenu().items.filter(function(item){
      return item.label == "Edit";
    })[0].submenu;
    mainMenu.popup(remote.getCurrentWindow());
}, false);

</script>
```

**Comment by swampthang** [comment]
Hi, mobitar. Thanks for the tip. This works but after executing one of the resulting menu options, the contextmenu doesn't go away. I have to use the esc key to get rid of it. Any ideas?

**Comment by gabriel** [comment]
FYI, I used the following to show an input menu if editable, otherwise a selection menu if there was selected text, but you're behavior may vary. More details on the context-menu event are here: https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-context-menu

```js
  window.webContents.on('context-menu', (e, props) => {
    const { selectionText, isEditable } = props;
    if (isEditable) {
      inputMenu.popup(window);
    } else if (selectionText && selectionText.trim() !== '') {
      selectionMenu.popup(window);
    }
  })
```

**Comment by Srivatsa-M-Hegde** [comment]
@raleksandar in the snippet taken from the code you have given above:-
document.body.addEventListener('contextmenu', (e) => {
    e.preventDefault();
    e.stopPropagation();

    let node = e.target;

    while (node) {
        if (node.nodeName.match(/^(input|textarea)$/i) || node.isContentEditable) {
            InputMenu.popup(remote.getCurrentWindow());
            break;
        }
        node = node.parentNode;
    }

the "node.nodeName", "node.parentNode" and "node.isContentEditable" all throw up errors saying these don't exist on the object "node". Anything I might be missing to get this error ?

**Comment by AoDev** [comment]
Hi, seeing this is still an open issue and it's almost 2019 (almost 3 years old issue!). Was there any improvement made? Like default menu available or should one still use some of the proposed solutions in this thread?

**Comment by codebytere** [comment]
We recommend that users look towards https://github.com/electron/electron/issues/4068#issuecomment-274159726 for this issue: at present this is not on the team's roadmap and so i'm going to label this a `wontfix` but we would happily accept a PR.

**Comment by crifan** [comment]
finally use [electron-context-menu](https://github.com/sindresorhus/electron-context-menu) to meet my requirement: in `textarea`, select and right click able to `Copy` content:

![Snip20200110_339](https://user-images.githubusercontent.com/2750682/72146338-2fbb2300-33d7-11ea-8890-0b61ca823cde.png)

**Comment by JeremyMColegrove** [comment]
Is this issue being tracked? 6 years later and this issue still exists.
