### ISSUE TITLE
[Bug]: Not possible to scale system tray menu

### ISSUE THREAD

**Issue by ssrakesh** [electron/electron#40696]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10/11

### What arch are you using?

x64

### Expected Behavior

Electron version 24.8.2
currently using webContents.setZoomFactor to scale the windows.
But system tray menu cant be resized or scaled accordingly
earlier I was using force-device-scale-factor, so entire app including tray menu and windows was scaling.
But currently not using force-device-scale-factor, bz of its behavior in multimonitor.

### Actual Behavior

system tray menu shows in 100% scale, when used in 4k (any dpi/text scale) the menus looks very small
this is bz I am using high-dpi-support 1, force-device-scale-factor 1
but in this case I wanted to scale the system tray menu, could not find a way

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
