### ISSUE TITLE
[Bug]: BrowserWindow positioning not working on MacOS 14.0 Sonoma

### ISSUE THREAD

**Issue by GiulioMabiloft** [electron/electron#40699]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

macOS

### Operating System Version

macOs 14 Sonoma

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When setting x and y positions on a BrowserWindow instance the window should move by the specified pixel amount from the top left corner.

### Actual Behavior

When setting x and y positions on a BrowserWindow instance the window always shows at the center of the screen.

### Testcase Gist URL

https://gist.github.com/79f3a55e0c593ca7d8b061c3bb0197d8

### Additional Information

I have tested this in a previous version of macOS and can confirm that the positioning api works correctly. It only breaks on macOs 14.0 Sonoma

**Comment by GiulioMabiloft** [comment]
Here's the link to the `Electron Fiddle` gist https://gist.github.com/79f3a55e0c593ca7d8b061c3bb0197d8. The only thing to note here is that `x` and `y` positions on `BrowserWindow` instance are set to 0 but when running the fiddle the app is placed in the center of the screen instead.

**Comment by syt-honey** [comment]
Maybe you can set `x` again. It works for me:

```
const win = new BrowserWindow({
    x: 0,
    y: 130,
    width: 68,
    height: 300
    // ...
})

// set the `x` again to fix the bug that window was positioned in the center of Desktop in Apple Silicon.
win.setBounds({
    x: 10
})
```

**Comment by GiulioMabiloft** [comment]
> Maybe you can set `x` again. It works for me:
> 
> ```ts
> const win = new BrowserWindow({
>     x: 0,
>     y: 130,
>     width: 68,
>     height: 300
>     // ...
> })
> 
> // set the `x` again to fix the bug that window was positioned in the center of Desktop in Apple Silicon.
> win.setBounds({
>     x: 10
> })
> ```

When should i do it? Right after the window has been created or in a specific lifetime event?

**Comment by syt-honey** [comment]
> When should i do it? Right after the window has been created or in a specific lifetime event?

You can try setting it right after creation, that's what I did, and it worked for me. Below is my code for your reference, hope it helps.

```ts
export const registerRecordingWindowMainIPCHandler = (): void => {
    let recordingWindow: BrowserWindow | null = null

    ipcMain.on('createRecordingWindow', (e, { url }) => {
        if (!validateSender(e.senderFrame)) return
        if (recordingWindow || !url) return

        const primaryDisplay = screen.getPrimaryDisplay()
        const { height } = primaryDisplay.workAreaSize
        // The `createWindow` is a wrapper around BrowserWindow. You can think of it as directly being BrowserWindow
        recordingWindow = createWindow({
            x: 0,
            y: height / 2 - 130,
            width: 68,
            height: 300,
            frame: false,
            alwaysOnTop: true,
            transparent: true,
            resizable: false,
            title: WindowType.RECORDING,
            url: runtime.baseUrl() + url
        })

        // We need to set the `x` again to fix the bug that window was positioned in the center of Desktop in Apple Silicon.
        recordingWindow.setBounds({
            x: 10
        })

        recordingWindow.webContents.setWindowOpenHandler(({ features }) => {
            return registerWindowHandler(features)
        })

        recordingWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: false })

        // make recording window higher than other window
        recordingWindow.setAlwaysOnTop(true, 'pop-up-menu', 2)
    })

    // register closeRecordingWindow handler
    ipcMain.on('closeRecordingWindow', (e) => {
        if (!validateSender(e.senderFrame)) return

        recordingWindow?.close()
        recordingWindow = null
    })
}
```

**Comment by GiulioMabiloft** [comment]
> > When should i do it? Right after the window has been created or in a specific lifetime event?
> 
> @GiulioMabiloft You can try setting it right after creation, that's what I did, and it worked for me. Below is my code for your reference, hope it helps.
> 
> ```ts
> export const registerRecordingWindowMainIPCHandler = (): void => {
>     let recordingWindow: BrowserWindow | null = null
> 
>     ipcMain.on('createRecordingWindow', (e, { url }) => {
>         if (!validateSender(e.senderFrame)) return
>         if (recordingWindow || !url) return
> 
>         const primaryDisplay = screen.getPrimaryDisplay()
>         const { height } = primaryDisplay.workAreaSize
>         // The `createWindow` is a wrapper around BrowserWindow. You can think of it as directly being BrowserWindow
>         recordingWindow = createWindow({
>             x: 0,
>             y: height / 2 - 130,
>             width: 68,
>             height: 300,
>             frame: false,
>             alwaysOnTop: true,
>             transparent: true,
>             resizable: false,
>             title: WindowType.RECORDING,
>             url: runtime.baseUrl() + url
>         })
> 
>         // We need to set the `x` again to fix the bug that window was positioned in the center of Desktop in Apple Silicon.
>         recordingWindow.setBounds({
>             x: 10
>         })
> 
>         recordingWindow.webContents.setWindowOpenHandler(({ features }) => {
>             return registerWindowHandler(features)
>         })
> 
>         recordingWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: false })
> 
>         // make recording window higher than other window
>         recordingWindow.setAlwaysOnTop(true, 'pop-up-menu', 2)
>     })
> 
>     // register closeRecordingWindow handler
>     ipcMain.on('closeRecordingWindow', (e) => {
>         if (!validateSender(e.senderFrame)) return
> 
>         recordingWindow?.close()
>         recordingWindow = null
>     })
> }
> ```

unfortunately for me it doesn't seem to make any effect and the window stays always at the center of the screen. On which version of macOS are you?

**Comment by syt-honey** [comment]
> unfortunately for me it doesn't seem to make any effect and the window stays always at the center of the screen. On which version of macOS are you?

Below are the details of the machine I used for testing:

Chip: Apple M1
OS: macOS Sonoma 14.1.1

**Additional information:**

1. I conducted the tests after packaging the application. I packaged it twice: the first time I set x directly, and the second time I set x again using `win.setBounds()`. Through testing, I found that in the first case, the window was centered, but in the second case, the position was set correctly.

2. On my own machine (Intel Core i5, macOS: Sonoma 14.2), both in the development environment and in the production environment, setting x directly when creating the window positioned it correctly.

[Here is the repository of the code I tested.](https://github.com/syt-honey/vboard/blob/581660ace22af8d936b167b5ca4fbdcb93c9cd22/src/main/ipc.ts#L93C21-L93C21)

**Comment by codebytere** [comment]
I ran the provided gist on macOS Sonoma with my M1 device using v28.1.3 and see the following:

<img width="1622" alt="Screenshot 2024-01-17 at 9 11 09 PM" src="https://github.com/electron/electron/assets/2036040/cd77d4bf-983b-4c43-ae10-233da87969ae">

I'm not able to reproduce it at all so far

**Comment by mlaurencin** [comment]
I just ran the gist from my Fiddle downloaded from [the Electron Fiddle site](https://www.electronjs.org/fiddle) and am seeing the same thing as @codebytere but with Electron 29.3.0.

@GiulioMabiloft Unless you can provide any additional information to help reproduce this bug, this issue will be closed in 10 days. If additional information is discovered after that, then please feel free to file a new bug report.

**Comment by GiulioMabiloft** [comment]
> I just ran the gist from my Fiddle downloaded from [the Electron Fiddle site](https://www.electronjs.org/fiddle) and am seeing the same thing as @codebytere but with Electron 29.3.0.
> 
> @GiulioMabiloft Unless you can provide any additional information to help reproduce this bug, this issue will be closed in 10 days. If additional information is discovered after that, then please feel free to file a new bug report.

Yeah unfortunately i'm not actively working on this anymore so i can't really provide any additional information. I'll mark this as closed. Ty to everyone!
