### ISSUE TITLE
[Bug]: inAppPurchase.getProducts no result returned

### ISSUE THREAD

**Issue by zyk-mjzs** [electron/electron#40720]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.1.2 (23B92)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.3.27

### Expected Behavior

return Product[]

### Actual Behavior

Continuously waiting for no result returned

**Comment by zyk-mjzs** [comment]
> Hello @zyk-mjzs. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the [ blocked/need-repro](https://github.com/electron/electron/labels/blocked%2Fneed-repro) Needs a test case to reproduce the bug label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

```javascript

const productList = await inAppPurchase.getProducts([productIdA, productIdB]) // <-- No results will be returned
console.log(productList) // <-- will not be executed

```

**Comment by codebytere** [comment]
@zyk-mjzs what you've included in https://github.com/electron/electron/issues/40720#issuecomment-1848430281 is not a repro as requested. Please add a repro or this issue will be closed.

**Comment by Jeepeng** [comment]
I've encountered the same issue, and it persists in both versions 27.x and 28.x. However, version 26.x works fine.

**Comment by codebytere** [comment]
Folding into https://github.com/electron/electron/issues/40851 - I have a PR up at https://github.com/electron/electron/pull/40938
