### ISSUE TITLE
[Documentation]: List of supported Operating Systems and Platforms is missing

### ISSUE THREAD

**Issue by hovancik** [electron/electron#40739]
There is a mention of platform/os being discontinued in some blog posts (https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice, https://www.electronjs.org/blog/electron-27-0#removed-macos-1013--1014-support), but there is no page that I can find that would tell me what is supported.

**Comment by MarshallOfSound** [comment]
The README has this information --> https://github.com/electron/electron/blob/main/README.md#platform-support
