### ISSUE TITLE
[Bug]:  BrowserView is set to the same size as BrowserWindow window, and the rendered content size of the two is different. BrowserView is rendered to the same size as its own window. The content of BrowserWindow is smaller than that of its own window

### ISSUE THREAD

**Issue by yf339339** [electron/electron#40731]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19045.3693

### What arch are you using?

x64

### Last Known Working Electron version

16.0.6

### Expected Behavior

BrowserView is set to the same size as BrowserWindow window, the rendering content of both is the same size

### Actual Behavior
BrowserView is rendered to the same size as its own window. The content of BrowserWindow is smaller than that of its own window

### Testcase Gist URL
https://gist.github.com/yf339339/f238a19afd6f18aa6ddf4263e1252b3a
_No response_

**Comment by yf339339** [comment]
> Hello @yf339339. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the [ blocked/need-repro](https://github.com/electron/electron/labels/blocked%2Fneed-repro) Needs a test case to reproduce the bug label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

https://gist.github.com/yf339339/f238a19afd6f18aa6ddf4263e1252b3a

**Comment by rmchen-12** [comment]
I also encountered this problem. How did you solve it?

**Comment by yf339339** [comment]
> I also encountered this problem. How did you solve it?

I used the low version  16.0.6
