### ISSUE TITLE
[Bug]: `net.fetch()` fails to forward html form submissions intercepted with `protocol.handle()`

### ISSUE THREAD

**Issue by BurningEnlightenment** [electron/electron#40754]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

`25.9.8`, `26.6.2`, `28.0.0`, `29.0.0-alpha.3`

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise 22H2 22621.2715

### What arch are you using?

x64

### Last Known Working Electron version

None--it doesn't work with any electron version shipping `protocol.handle()`. 

### Expected Behavior

It is [documented](https://www.electronjs.org/docs/latest/api/net#netfetchinput-init) that if one intercepts a protocol (e.g. given `s: Electron.Session` `s.protocol.handle('http', ...)`) one can forward a request to the built-in handler by passing `bypassCustomProtocolHandlers: true` in the `RequestInit` parameter. 

### Actual Behavior

However, if the request originates from a plain html `<form>` submission, the built-in handler fails with
```
Error: net::ERR_FAILED
at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49030)
at SimpleURLLoaderWrapper.emit (node:events:517:28)
(node:9824) electron: Failed to load URL: http://127.0.0.1:3000/ with error: ERR_UNEXPECTED
```
I observed that the form submission request contains an `origin: null` header and that removing said header from the request allows the request to succeed. The request also succeeds if no custom protocol handler is installed.

### Testcase Gist URL

https://gist.github.com/BurningEnlightenment/83ef1268fa71ebe0fafd9dfa4cc2811f

### Additional Information

The Testcase contains an html form which can be submitted to the included koa webserver.

**Comment by ckerr** [comment]
CC @nornagon
