### ISSUE TITLE
[Feature Request]: Expose `net` module to preload scripts when `contextIsolation` is enabled.

### ISSUE THREAD

**Issue by RealAlphabet** [electron/electron#40752]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, when context isolation is enabled and nodejs integration is disabled, it is not possible in a preload script to use the `net` module.

Instead, the preload script must send an IPC message to the renderer process, which will then use the `net` module  to send the request, and return the HTTP response back via IPC.

This poses a practical and performance problem for stream responses.

### Proposed Solution

Exposing Chromium's `net` module in the preload would remove the need to communicate with the renderer.

Ideally, if Electron's `MessagePort` API enabled the transfer of complex JavaScript objects such as `SharedArrayBuffer` or `ReadableStream` between the preload and the renderer, this could be another viable solution that meets more needs.

### Alternatives Considered

1. Create an off-screen `BrowserWindow` with context isolation disabled and transfer a `MessagePort` from it to the second window. The offscreen window makes requests using Chrome's `net` module and returns a `ReadableStream` via `postMessage` to the real window. Complex object transfer works in this case since the two windows are Blink contexts.
> **Problem:** To be honest, I haven't tried it yet, so I don't know if it works. In any case, I find it relatively complex for such a simple use case, and probably not safe.

2. Send serialized binary blocks between the renderer and reimplement a `ReadableStream` on the preload side with an in-flight request cancellation system.
> **Problem:** Poor performance due to the need to copy binary data, not at all efficient and error-prone.

### Additional Information

Thank you for all you do. I'd like to offer my moral support to the developers and maintainers of electrons and wish you all a very happy holiday season. 🎄

**Comment by MarshallOfSound** [comment]
Preload scripts can use `fetch`, exposing the net module to the renderer is unsafe and therefore we probably won't be doing it by default 

If you want this capability in your app your outlined method of using IPC handle/invoke is the way to do it.  Please ensure you Allowlist / restrict the options / urls the renderer is allowed to request otherwise your app is a walking security issue.

**Comment by RealAlphabet** [comment]
> Preload scripts can use `fetch`, exposing the net module to the renderer is unsafe and therefore we probably won't be doing it by default
> 
> If you want this capability in your app your outlined method of using IPC handle/invoke is the way to do it. Please ensure you Allowlist / restrict the options / urls the renderer is allowed to request otherwise your app is a walking security issue.

Thank you for taking the time to read this suggestion for improvement. I understand your point of view and the implications it could cause.

However, if I don't use the fetch API it's because I have a specific need that requires defining the origin of the request.

For the performance problems I mentioned, would it be better to create a new issue or wait until the issue concerning the implementation of transferable objects on Electron's "MessagePort" has been dealt with?

There doesn't seem to have been any movement on the corresponding issue for a while now.
https://github.com/electron/electron/issues/34905
