### ISSUE TITLE
[Bug]: Can't resize devtools(detached window) on mas-x64 version

### ISSUE THREAD

**Issue by wanghanzhen** [electron/electron#40755]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 14.0 (23A344)

### What arch are you using?

x64

### Expected Behavior

Can resize devtools detached window

### Actual Behavior

Can't resize devtools detached window on [mas-x64 version](https://github.com/electron/electron/releases/download/v28.0.0/electron-v28.0.0-mas-x64.zip).
It works on [darwin-x64 version](https://github.com/electron/electron/releases/download/v28.0.0/electron-v28.0.0-darwin-x64.zip).
I think there's a same behavior on arm64.

### Additional Information

I recorded a video: https://abc-1251316161.cos.ap-guangzhou.myqcloud.com/QQ20231213-195537-HD.mp4

_No response_

**Comment by zhourubin** [comment]
I am also facing the same issue.

**Comment by wanghanzhen** [comment]
bump

**Comment by wanghanzhen** [comment]
this is still reproducible in the [latest version of Electron](https://www.electronjs.org/releases/stable) or in the [beta](https://www.electronjs.org/releases/beta)

**Comment by devinbinnie** [comment]
Can confirm same behaviour on ARM64 MAS build.
