### ISSUE TITLE
[Bug]: Native Node Modules in Win 32 bit build got error in Electron 28.0.0

### ISSUE THREAD

**Issue by tk1cntt** [electron/electron#40760]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21h1

### What arch are you using?

x64

### Last Known Working Electron version

27.0.3

### Expected Behavior

Build OK

### Actual Behavior

Build got error

### Additional Information

Native Node Modules build with command

`node-gyp rebuild --target=28.0.0 --target_platform=win32 --arch=ia32 --dist-url=https://electronjs.org/headers`

I found the solution in here: https://stackoverflow.com/questions/27442885/syntax-error-with-stdnumeric-limitsmax

`Add #undef max before calling numeric_limits<size_t>::max():`

Error:

> C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(30,70): warning C4003: not enough arguments for function-like macro invocation 'max' [D:\xxx\electr
on\addons\build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(30,70): error C2589: '(': illegal token on right side of '::' [D:\xxx\electron\addons\build\xxxr 
idge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(30): error C2062: type 'unknown-type' unexpected [D:\xxx\electron\addons\build\xxx.vcxproj] 
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(30,42): error C2789: 'v8::TypedArray::kMaxByteLength': an object of const-qualified type must be initialized [D 
:\xxx\electron\addons\build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(30): message : see declaration of 'v8::TypedArray::kMaxByteLength' [D:\xxx\electron\addons\build\xxxBridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(30,70): error C2059: syntax error: ')' [D:\xxx\electron\addons\build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(41,40): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxx
ridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(41,40): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\b 
uild\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(41,40): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj]  
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(70,34): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxx 
ridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(70,19): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\b 
uild\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(70,19): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj]  
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(98,34): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxx 
ridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(98,19): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\b 
uild\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(98,19): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj]  
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(127,34): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxxBridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(127,19): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(127,19): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj] 
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(155,34): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxxBridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(155,19): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(155,19): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(183,34): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxxBridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(183,19): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(183,19): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj] 
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(211,34): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxxBridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(211,19): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(211,19): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj] 
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(239,34): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxxBridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(239,19): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(239,19): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj] 
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(267,34): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxxBridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(267,19): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(267,19): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(295,34): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxx 
Bridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(295,19): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(295,19): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj] 
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(323,34): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxx 
Bridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(323,19): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\
build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(323,19): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj] 
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(351,34): error C2131: expression did not evaluate to a constant [D:\xxx\electron\addons\build\xxx 
Bridge.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(351,19): message : failure was caused by a read of an uninitialized symbol [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-typed-array.h(351,19): message : see usage of 'kMaxByteLength' [D:\xxx\electron\addons\build\xxx.vcxproj] 
D:\xxx\electron\addons\xxx.cc(47,38): warning C4996: 'v8::CopyablePersistentTraits<v8::Function>': Use v8::Global instead [D:\xxx\electron\
addons\build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-persistent-handle.h(244,73): message : see declaration of 'v8::CopyablePersistentTraits' [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
D:\xxx\electron\addons\xxx.cc(106,55): warning C4996: 'v8::CopyablePersistentTraits<v8::Function>': Use v8::Global instead [D:\xxx\electron 
\addons\build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-persistent-handle.h(244,73): message : see declaration of 'v8::CopyablePersistentTraits' [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
D:\xxx\electron\addons\xxx.cc(304,38): warning C4996: 'v8::CopyablePersistentTraits<v8::Function>': Use v8::Global instead [D:\xxx\electron 
\addons\build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-persistent-handle.h(244,73): message : see declaration of 'v8::CopyablePersistentTraits' [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
D:\xxx\electron\addons\xxx.cc(365,55): warning C4996: 'v8::CopyablePersistentTraits<v8::Function>': Use v8::Global instead [D:\xxx\electron 
\addons\build\xxx.vcxproj]
C:\Users\xxx\AppData\Local\node-gyp\Cache\28.0.0\include\node\v8-persistent-handle.h(244,73): message : see declaration of 'v8::CopyablePersistentTraits' [D:\xxx\electron\addons\ 
build\xxx.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\xxx\electron\node_modules\node-gyp\lib\build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\xxx\\electron\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=28.0.0" "--target_platform=win32" "--arch=ia32" "--dist-url=[https://electronjs.org/headers"](https://electronjs.org/headers%22)
gyp ERR! cwd D:\xxx\electron\addons
gyp ERR! node -v v18.18.2
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
[10:56:03] 'build:addons' errored after 32 s
[10:56:03] Error: Command failed: cd addons && build.bat
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at sh (D:\xxx\electron\gulpfile.js:13:3)
    at D:\xxx\electron\gulpfile.js:133:5
    at taskWrapper (D:\xxx\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (node:domain:433:15)
    at runBound (node:domain:444:12)
    at asyncRunner (D:\xxx\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
[10:56:03] 'build' errored after 32 s
[10:56:03] '<anonymous>' errored after 59 s
[10:56:03] Error: Command failed: D:\xxx\node_modules\.bin\gulp build
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at sh (D:\xxx\gulpfile.js:57:3)
    at gulpExec (D:\xxx\gulpfile.js:37:7)
    at D:\xxx\gulpfile.js:353:5
    at bound (node:domain:433:15)
    at runBound (node:domain:444:12)
    at asyncRunner (D:\xxx\node_modules\async-done\index.js:55:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[10:56:03] 'build:pc' errored after 1.48 min
node:child_process:965
    throw err;
    ^
 

> Error: Command failed: D:\xxx\node_modules\.bin\gulp build:pc

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at setenv.sh (D:\xxx\script\setenv.js:5:3)
    at Object.<anonymous> (D:\xxx\script\rungulp.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 22744,
  stdout: null,
  stderr: null
}
 
```
Node.js v18.18.2
 
*  The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run build:pc" terminated with exit code: 1. 
*  Te
```rminal will be reused by tasks, press any key to close it.

**Comment by evgenys91** [comment]
I'm having the same issue win ia32 build for windows. 

One of my native modules has `#include windows.h` import, which somehow conflicts with `v8-typed-array.h` in `~\.electron-gyp\28.1.1\include\node`. 

At the same time electron versions prior to 28 are working fined.
If someone has an idea of how to resolve this will be glad to hear from you.

**Comment by codecompanion-ai** [comment]
@tk1cntt Did you ever figure out how to fix? I am having the same problem

**Comment by oalfroukh** [comment]
Hi,
I have the same error when upgrading `electron` from `v26` to `v28.2.4` on Windows `arch ia32` does anyone have a fix for it?

here are the errors I have:

```
 npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(30,70): warning C4003: not enough arguments for function-like macro invocation 'max' [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(30,70): error C2589: '(': illegal token on right side of '::' [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(30,44): error C2062: type 'unknown-type' unexpected [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(30,42): error C2789: 'v8::TypedArray::kMaxByteLength': an object of const-qualified type must be initialized [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(30,27):
    npm ERR!   see declaration of 'v8::TypedArray::kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(30,70): error C2059: syntax error: ')' [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(41,40): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(41,40):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(41,40):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(70,34): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(70,19):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(70,19):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(98,34): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(98,19):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(98,19):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(127,34): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(127,19):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(127,19):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(155,34): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(155,19):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(155,19):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(183,34): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(183,19):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(183,19):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(211,34): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(211,19):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(211,19):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(239,34): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(239,19):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(239,19):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(267,34): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(267,19):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(267,19):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(295,34): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(295,19):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(295,19):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(323,34): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(323,19):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(323,19):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(351,34): error C2131: expression did not evaluate to a constant [C:\Users\oalfroukh\Desktop\project\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(351,19):
    npm ERR!   failure was caused by a read of an uninitialized symbol
    npm ERR!   C:\Users\oalfroukh\.electron-gyp\28.2.4\include\node\v8-typed-array.h(351,19):
    npm ERR!   see usage of 'kMaxByteLength'
    npm ERR!
    npm ERR! C:\Users\oalfroukh\Desktop\project\node_modules\nan\nan.h(688,37): warning C4996: 'v8::Isolate::IdleNotificationDeadline': Use MemoryPressureNotification() to influence the GC schedule. [C:\Users\oalfroukh\Desktop\Asal_projects\desktop-v2\rb-services\node_modules\@aabuhijleh\windows-notification-state\build\notificationstate.vcxproj]
    npm ERR!   (compiling source file '../lib/notificationstate-query.cc')
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@10.0.1
    npm ERR! gyp info using node@18.18.2 | win32 | ia32
    npm ERR! gyp info find Python using Python version 3.9.13 found at "C:\Users\oalfroukh\AppData\Local\Programs\Python\Python39\python.exe"
    npm ERR! gyp info find VS using VS2022 (17.8.34525.116) found at:
    npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
```

**Comment by nikitakot** [comment]
as mentioned in stackoverflow above passing `"NOMINMAX"` build flag fixes the issue, it can be passed via binding.gyp of the problematic module, like so:

```diff
--- a/binding.gyp
+++ b/binding.gyp
@@ -10,7 +10,8 @@
       ["OS=='win'", {
         "defines": [
           "UNICODE",
-          "_UNICODE "
+          "_UNICODE ",
+          "NOMINMAX"
         ],
```
