### ISSUE TITLE
[Bug]: webContents.debugger does not obtain Page.frameNavigated event on domain change

### ISSUE THREAD

**Issue by jayakrishnankp** [electron/electron#40763]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.6.2

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6.1

### What arch are you using?

x64

### Expected Behavior

When any navigation happens in webContents, the webContents.debugger should emit the `Page.frameNavigation` event.

### Actual Behavior

If the navigation is from one domain to a different domain, the `Page.frameNavigation` is not obtained in any of the debugger.on('message') listeners.

### Testcase Gist URL

https://gist.github.com/jayakrishnankp/907da7ec27d514e3b525c99410a20e6c

### Additional Information

In the test case linked, the expectation is to get a `Page.frameNavigated` event when we click the link which goes to a different domain (wikipedia in the example), i.e. after the log `CLICK AND GOTO WIKI (EXPECT PAGE NAVIGATION HERE)` and before the log `CLICK WIKI SUB LINK`.
This is not obtained.

Furthermore testing the same using [Playwright's Electron app connection implementation](https://playwright.dev/docs/api/class-electron) successfully fires this missing event. Here the connection is made by opening a port.

**Comment by bacy** [comment]
bump
