### ISSUE TITLE
[Bug]: navigator.mediaDevices.getUserMedia can't get the audio stream

### ISSUE THREAD

**Issue by RomanticNeverDie** [electron/electron#40761]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.3

### What operating system are you using?

Ubuntu

### Operating System Version

22.04.3

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

If I set audio to false, I can successfully obtain video, but when I enable audio, I can no longer retrieve both video and audio.

### Actual Behavior

To obtain both audio and video.

### Additional Information

      this.localStream = await navigator.mediaDevices.getUserMedia({
        audio: {
          mandatory: {
            chromeMediaSource: 'desktop',
          },
        } as MediaTrackConstraints,
        video: {
          mandatory: {
            chromeMediaSource: 'desktop',
            chromeMediaSourceId: ipcData.data,
            // minWidth: 2560,
            // maxWidth: 2560,
            // minHeight: 1440,
            // maxHeight: 1440,
            // maxFrameRate: 120,
            // minFrameRate: 120,
          },
        } as MediaTrackConstraints,
      });
        if (!this.peerConnection) {
        const pcConfig: RTCConfiguration = {
          iceServers: Settings(SettingKeys.ICE_SERVICES),
        };
        this.logger.info('pcConfig: ', JSON.stringify(pcConfig));
        this.peerConnection = new RTCPeerConnection(pcConfig);
        this.peerConnection.onicecandidate = (e: any) => {
          if (e.candidate) {
            ipcData.data = {
              type: 'candidate',
              label: e.candidate.sdpMLineIndex,
              id: e.candidate.sdpMid,
              candidate: e.candidate.candidate,
            };
            ipcRenderer.send(IPCEvents.WEBRTC_SEND_MESSAGE, ipcData);
          } else {
            this.logger.info('this is the end candidate');
          }
        };
      } else {
        this.logger.info('the pc have be created!');
      }

      if (!this.peerConnection) {
        this.logger.error('pc is null or undefined!');
        return;
      }

      if (!this.localStream) {
        this.logger.error('localstream is null or undefined!');
        return;
      }

      this.localStream.getTracks().forEach((track: any) => {
        this.peerConnection.addTrack(track, this.localStream);
        this.logger.info('add a track: ', track.type);
      });

      this.dataChannel = this.peerConnection.createDataChannel(this.dataChannelName);
      this.dataChannel.onmessage = this.dataChannelReceivemsg;
      this.dataChannel.onopen = this.dataChannelStateChange;
      this.dataChannel.onclose = this.dataChannelStateChange;

      const offerOptions = {
        offerToRecieveAudio: 0,
        offerToRecieveVideo: 0,
      } as RTCOfferOptions;
      this.peerConnection
        .createOffer(offerOptions)
        .then((offer: any) => {
          this.peerConnection.setLocalDescription(offer);

          if (this.bitrate) {
            this.logger.info('set bitrate: ', this.bitrate * 1000);
            offer.sdp = this.setMediaBitrates(offer.sdp, this.bitrate * 1000);
          }

          ipcData.data = offer.toJSON();
          ipcRenderer.send(IPCEvents.WEBRTC_SEND_MESSAGE, ipcData);
        })
        .catch((e: any) => {
          this.logger.error('Failed to create offer:', e);
        });
    } catch (e: any) {
      this.logger.error('Failed to render:', e);
`

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
