### ISSUE TITLE
[Bug]: Print blank on paper when silent: true in mainWindow.webContents.print({silent: true})

### ISSUE THREAD

**Issue by alfianlensundev** [electron/electron#40778]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Last Known Working Electron version

Uknown

### Expected Behavior

Silent print html content

### Actual Behavior

print blank

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
