### ISSUE TITLE
[Bug]: datalist doesn't have a scroll bar in electron

### ISSUE THREAD

**Issue by bhosasac** [electron/electron#40773]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

**Issue Details :**

Datalist control should have scroll bar if it has many items to display.
```
<input list="browsers" id="myBrowser" name="myBrowser" />
<datalist id="browsers">
  <option value="Chrome">
  <option value="Firefox">
  <option value="Internet Explorer">
  <option value="Opera">
  <option value="Safari">
  <option value="Microsoft Edge">
</datalist>
```

### Actual Behavior

It doesn't have scroll bar and it can only show limited items.
It works in chrome.

**Comment by oklang** [comment]
I'm facing the same issue. This seems to have been a problem for a long while according to #18925
