### ISSUE TITLE
[Bug]: Slower https transfer data in electron than nodejs

### ISSUE THREAD

**Issue by Makus577** [electron/electron#40774]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.0

### What operating system are you using?

Windows

### Operating System Version

WIndows 10

### What arch are you using?

x64

### Last Known Working Electron version

23.1.0

### Expected Behavior

the same speed when upload file use https protocol in eletron or nodejs 

### Actual Behavior

I'm developing an Electron app that upload a file from my web server.

I tried downloading the exact same file from a separate NodeJS script (no Electron, just plain NodeJS) and speeds are as to be expected: very fast.

However when I run the exact same code from withing my Electron app it is extremely slow.

### Additional Information

const https = require('https');
const fs = require('fs');
const { performance } = require('perf_hooks');

const serverAddress = 'your-https-server-address';
const serverPort = 443;
const filePath = 'path/to/local/file.txt';

const fileStream = fs.createReadStream(filePath);

const options = {
  hostname: serverAddress,
  port: serverPort,
  path: '/upload', // Replace with the actual upload path
  method: 'PUT', // Use the PUT method
  headers: {
    'Content-Type': 'application/octet-stream', // Set the appropriate Content-Type
  },
};

console.time('TCP Connection');

// Use a connection pool, set keepAlive to true
options.agent = new https.Agent({ keepAlive: true });

// Initiate an HTTPS request
const req = https.request(options, (res) => {
  console.timeEnd('TCP Connection');

  const startDataTransfer = performance.now();
  let responseData = '';

  // Use streaming to handle response data
  res.on('data', (data) => {
    responseData += data;
  });

  res.on('end', () => {
    const endDataTransfer = performance.now();
    console.timeEnd('Data Transfer');
    console.log(`Data transfer time: ${endDataTransfer - startDataTransfer} milliseconds`);
    console.log('Received data:', responseData);
  });
});

req.on('error', (error) => {
  console.error('Request failed:', error.message);
});

console.time('Request');

// Send the request
req.end(() => {
  const endRequest = performance.now();
  console.timeEnd('Request');
  console.log('Total request time:', endRequest - startRequest, 'milliseconds');
});

// Listen for the 'finish' event on the request to ensure the file transfer is complete before ending the request
fileStream.pipe(req);

fileStream.on('error', (error) => {
  console.error('File read error:', error.message);
});

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
