### ISSUE TITLE
[Bug]: Devtools is missing all context menus

### ISSUE THREAD

**Issue by t57ser** [electron/electron#40772]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Windows

### Operating System Version

10.0.19042

### What arch are you using?

x64

### Last Known Working Electron version

24.0.0

### Expected Behavior

Devtools provide various context menus which should be available

### Actual Behavior

Context menus do not open
Works in electron 24. Does not work in electron 25
[edit]: appears to only be an issue if the devtools are undocked
Example of context menu:
![image](https://github.com/electron/electron/assets/10595986/548ae189-2254-41c5-9db3-7e7988de2bc7)

### Testcase Gist URL

https://gist.github.com/t57ser/1684784219cbd1f1a79df2733742e914

**Comment by ckerr** [comment]
https://github.com/electron/electron/issues/38790#issuecomment-1592911862
