### ISSUE TITLE
[Bug]:  desktopCapturer.getSources only shows black screen and mouse in some video streams

### ISSUE THREAD

**Issue by KongYy1** [electron/electron#40782]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

6.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

18.0.0

### Expected Behavior

Obtain all processes displayed in the video tag through Electon's desktopCapturer.getSources API for users to choose, and then perform the sharing function

### Actual Behavior

When the video stream list obtained through the API is rendered to the video tag through webrtc, some tags may appear black, but the mouse can be seen

****
```javascript
async function loadDesktopProcess() {
    const sources = await desktopCapturer.getSources({
        types: ['window','screen'],
        fetchWindowIcons: true
    })
    const selectContainer = document.getElementById('share-list');
    for (const obj of sources) {
        const videoElement = document.createElement('video');
        const stream = await navigator.mediaDevices.getUserMedia({
            audio: false,
            video: {
                mandatory: {
                    chromeMediaSource: 'desktop',
                    chromeMediaSourceId: obj.id
                }
            }
        })
        videoElement.addEventListener('loadedmetadata', (event) => {
            videoElement.play()
        }, false);
        videoElement.srcObject = stream
        selectContainer.appendChild(videoElement)
    }
}
```

**Comment by KongYy1** [comment]
Partial screenshot
![image](https://github.com/electron/electron/assets/109017039/eab91724-b185-41e4-8abc-e36a8d53dff7)
![image](https://github.com/electron/electron/assets/109017039/94e38740-f2fa-40e6-995c-352f0018a4e8)

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
