### ISSUE TITLE
[Bug]: Built electron app does not work at all on Windows.

### ISSUE THREAD

**Issue by mzeinh** [electron/electron#40788]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2 19045.3803

### What arch are you using?

x64

### Expected Behavior

Expected behavior is app opens or at least throws an error when running it through powershell or using electron/unhandled.

### Actual Behavior

Where do I get started...

I can't seem to get an electron app to launch on windows for the life of me. I have tried running it windows 10 and 11 on 3 different PC. I have tried building it on a Mac M1 and a Windows 10. Turned off all anti-virus, firewall and added the app's folder to the exclusion list and it still does not work. 

At first, I thought that it has something to do with my code in the project I am working on, but that does not seem to be the case. It is the same behavior with a blank project from `npm create @quick-start/electron my-app -- --template react-ts`, running `npm install` and then `npm run build:win`.  

I tried running it through powershell but it doesn't throw an errors and I used `electron/unhandled` putting it as the first line of code in the main process, but there are no errors. 

This is the same behavior with electron-forge and electron-builder.

### Behavior:

- The application will not open at all if it is not run as administrator. 
- When it is run as administrator, the window shows for 1 or 2 seconds before closing.
- After closing, sometimes the app will continue running as a background process but with no window visible.

### Reproducing the issue:

- Run `npm create @quick-start/electron my-app -- --template react-ts`
- Run `npm install`
- Run `npm run build:win --64x` 
- Run the installer once the build is completed. 
- After installation, run the `.exe` file.

FWIW, these built applications whether its my project, or a blank electron-vite project, work just fine on my Mac M1 Ventura.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by deniskabana** [comment]
@mzeinh After running into the same issue, you have to add `--x64` flag to create an x64 compatible build. By default electron builder seems to implicitly create a ARM win version if you're on an ARM based Mac.
