### ISSUE TITLE
[Bug]: Broken Vibrancy

### ISSUE THREAD

**Issue by RoyalFoxy** [electron/electron#40799]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.3

### What operating system are you using?

macOS

### Operating System Version

macOS sonoma 14.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

26.6.2

### Expected Behavior

Working vibrancy

### Actual Behavior

Vibrancy doesn't work

### Testcase Gist URL

https://gist.github.com/RoyalFoxy/75bbfcae5cc404201bf64e2f9a597f46

### Additional Information

Note that this issue was introduced with 27.0.0, I just chose 27.1.3 as that's the current vscode electron version. This issue persists on all versions above 27.0.0 including 28.x.x and the alpha builds for version 29

**Comment by codebytere** [comment]
@RoyalFoxy this is unfortunately not a bug. Support for `dark` vibrancy has been deprecated since 10.15 and was finally removed when we updated our minimum supported OS in https://github.com/electron/electron/pull/38891. We regrettably missed this in our breaking change doc.

I've opened https://github.com/electron/electron/pull/40893 to address this.

**Comment by RoyalFoxy** [comment]
Thanks for the clarification! I tested all possible values and came up with this list `fullscreen-ui, header, hud, menu, popover, selection, sidebar, titlebar, tooltip, under-window` of values that had a visible effect. Which of these is comparable to dark? Obviously none of the header, menu or tooltip ones but would `under-window` or `fullscreen-ui` be preferred?
