### ISSUE TITLE
[Bug]: When webContens is used to load a PDF file, the pdf file is not loaded when did-finish-load is triggered

### ISSUE THREAD

**Issue by 1339240789** [electron/electron#40797]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.2.37

### What operating system are you using?

Windows

### Operating System Version

win 11

### What arch are you using?

x64

### Expected Behavior

When the "did-finish-load" event of the pdf page is triggered, the pdf page should be fully loaded and the specific pdf image can be seen

### Actual Behavior

When the did-finish-load event of the pdf page is triggered, the main page remains blank in the loading pdf

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
