### ISSUE TITLE
[Bug]: Vibrancy top corners are white

### ISSUE THREAD

**Issue by RoyalFoxy** [electron/electron#40800]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS sonoma 14.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

26.2.4

### Expected Behavior

Vibrancy works just as expected.

<img width="1800" alt="image" src="https://github.com/electron/electron/assets/48829979/39b70992-6eac-4061-aa0b-163bbede235f">

### Actual Behavior

The vibrancy part of the window seems to be too small and not cover the title bar leaving tiny ugly white rounded corners behind in the top section.

<img width="1800" alt="image" src="https://github.com/electron/electron/assets/48829979/b68f482f-7222-4a1e-9960-8604b60a6f22">

### Testcase Gist URL

https://gist.github.com/977c2ba87b683011bf1e093f6dd06d2f

### Additional Information

I don't know if this issue would still persist in versions above 26 considering vibrancy has [broken entirely in versions 27 and above](https://github.com/electron/electron/issues/40799)

**Comment by codebytere** [comment]
@RoyalFoxy yes, this is an issue if you change the gist to a supported vibrancy option. I'll take a look.

**Comment by RoyalFoxy** [comment]
I've tested and updated my fiddle to now use `under-window` as it also has these white corners. Note that I have also looked at 27+ now that I know that dark isn't supported anymore and 27.x.y also has corners but they are the same color as the titlebar from what I could tell.
