### ISSUE TITLE
[Bug]: Registered scheme doesn't honor privileges 

### ISSUE THREAD

**Issue by aadcg** [electron/electron#40816]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.0

### What operating system are you using?

Other Linux

### Operating System Version

nix-channel (Nix) 2.16.1 

### What arch are you using?

x64

### Expected Behavior

The sound track wouldn't play.

### Actual Behavior

The sound track plays.

### Additional Information

```js
const { app, protocol, BrowserWindow, BrowserView, net } = require('electron')

protocol.registerSchemesAsPrivileged([{scheme:'new', privileges:{stream:false}}])

app.whenReady().then(() => {
  url = 'https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3'
  protocol.handle('new', () => {return net.fetch(url)})

  let win = new BrowserWindow()
  let view = new BrowserView()

  win.addBrowserView(view)
  view.setBounds({ x: 0, y: 0, width: 400, height: 200 })

  view.webContents.loadURL('new:dummy')})
```

**Comment by Lilneo786** [comment]
const { app, protocol, BrowserWindow, BrowserView, net } = require('electron')
const http = require('http')

protocol.registerSchemesAsPrivileged([{ scheme: 'new', privileges: { standard: true, secure: true } }])

app.whenReady().then(() => {
  url = 'https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3'
  protocol.registerHttpProtocol('new', (request, callback) => {
    const req = http.get(url, (response) => {
      let data = ''
      response.on('data', (chunk) => {
        data += chunk
      })
      response.on('end', () => {
        callback({ data, mimeType: 'audio/mpeg' })
      })
    })
    req.end()
  })

  let win = new BrowserWindow()
  let view = new BrowserView()

  win.addBrowserView(view)
  view.setBounds({ x: 0, y: 0, width: 400, height: 200 })

  view.webContents.loadURL('new:dummy')
})
