### ISSUE TITLE
[Bug]: How do I make CHECK(false) continue to run without crashing?

### ISSUE THREAD

**Issue by JiaFuGuo** [electron/electron#40815]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.26

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

Do not let the program crash when certain failures are executed to CHECK(false).

### Actual Behavior

When a handle fails to be closed, CHECK(false) is executed, which causes the program to crash. Actually, the handle has been closed. Repeatedly closing the handle has no impact on the program. However, it is unreasonable to force the program to crash.

### Additional Information

For example, the following code：
file: 
electron\src\base\win\scoped_handle_verifier.cc
function:
bool CloseHandleWrapper(HANDLE handle) {
  if (!::CloseHandle(handle))
    CHECK(false) << "CloseHandle failed";
  return true;
}

**Comment by Lilneo786** [comment]
#include <Windows.h>

// Define an error code enum or use an existing one
enum class ErrorCode {
    Success,
    CloseHandleFailed
};

ErrorCode CloseHandleWrapper(HANDLE handle) {
    if (!::CloseHandle(handle)) {
        // Instead of CHECK(false), return an error code
        return ErrorCode::CloseHandleFailed;
    }
    return ErrorCode::Success;
}

**Comment by MarshallOfSound** [comment]
hard checks like `CHECK(false)` or `FATAL()` are normally in place for security reasons, or may be because it's a theoretically impossible scenario that puts the application into an unknown or unhandled state.  The hard crash is expected behavior in these cases and we won't be deviating from that

**Comment by JiaFuGuo** [comment]
> hard checks like `CHECK(false)` or `FATAL()` are normally in place for security reasons, or may be because it's a theoretically impossible scenario that puts the application into an unknown or unhandled state. The hard crash is expected behavior in these cases and we won't be deviating from that

Thank you for your reply. I can understand what you mean, but in fact, this unexpected behavior occurs during the running of the application, but we can't solve or avoid the problems from the electron kernel level. And we found that it did not necessarily affect the running of the program.
