### ISSUE TITLE
[Bug]: Error setting cookie: [Error: Setting cookie failed]

### ISSUE THREAD

**Issue by kyrieLiu** [electron/electron#40829]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.2.12

### What operating system are you using?

macOS

### Operating System Version

14.1 (23B74)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

14.2.9

### Expected Behavior

    const currentSession = win.webContents.session;

    // 设置 HTTP cookie
    currentSession.cookies.set({
        url: 'http://example.com',  // 替换为实际的域名
        name: 'myCookie',
        value: 'cookieValue',
        domain: 'example.com',  // 可选，根据需要设置
        path: '/',  // 可选，根据需要设置
        secure: false,  // 对于 HTTP 协议，设置为 false
        httpOnly: false,  // 根据需要设置
        sameSite: 'no_restriction'
    }).then(() => {
        console.log('Cookie set successfully');
    }).catch((error) => {
        console.error('Error setting cookie:', error);
    });

When i setting http cookies,The result should be success,but error

### Actual Behavior

Always throw error Error setting cookie: [Error: Setting cookie failed]

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info! 

Additionally, Electron v20 is no longer supported. If you choose to file a follow-up issue with the requested information, you'll need to demonstrate that it happens on a [supported version](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).
