### ISSUE TITLE
[Bug]: protocol.handle `file` issue when dealing with FormData

### ISSUE THREAD

**Issue by pengx17** [electron/electron#40826]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.3

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

1. Intercept `file` protocol using `protocol.handle`
2. Sending FormData in the renderer
3. Request intercepted in the function registered in 1
4. The File's blob size in the form should have correct content and size

### Actual Behavior

In step 4, the File's size is 0

### Testcase Gist URL

https://gist.github.com/pengx17/d7b9f3e0f16fd362b44510d3842e90d4

### Additional Information

Please see the console output. The printed File is something like this:
```
FormData { [Symbol(state)]: [ { name: 'file', value: [File] } ] } File {
  size: 0,
  type: 'application/octet-stream',
  name: 'test.txt',
  lastModified: 1703500799473
}
```

**Comment by BurningEnlightenment** [comment]
Note that this is unrelated to the `file://` protocol as `protocol.handle()` currently swallows any `Blob` part of a `FormData` request.
