### ISSUE TITLE
[Bug]: Failed to get location information using navigator.geolocation.getCurrentPosition after upgrading macOS (that the app is not published to the app store, it just runs through a local installer)

### ISSUE THREAD

**Issue by 123XXKK** [electron/electron#40831]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.1

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.1.1

### What arch are you using?

x64

### Expected Behavior

Can get the latitude and longitude by navigator.geolocation.getCurrentPosition.

### Actual Behavior

Can't use navigator.geolocation.getCurrentPosition to get location information after upgrading macOS Sonoma 14.1.1, always goes to failure function， i haven't released the app, I'm just using the installer for now，please help me to check it, thanks a lot.

**Comment by 123XXKK** [comment]
<img width="560" alt="image" src="https://github.com/electron/electron/assets/154871801/e2606094-d040-4293-b971-21c03b224a4b">

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by 123XXKK** [comment]
Thanks, I'll be looking for help in the community.

**Comment by ralyodio** [comment]
@123XXKK did you ever find an answer?

**Comment by meshhi13** [comment]
I'm having a similar problem, did anyone find a solution?

**Comment by qianxuemin** [comment]
我也遇到了类似问题 有人找到解决方案了吗？

**Comment by qianxuemin** [comment]
> I'm having a similar problem, did anyone find a solution?
Is your problem solved?

**Comment by nilayarya** [comment]
@qianxuemin @meshhi13 @ralyodio @rick-xukai I might have a solution that will trigger prompt and list it in location services. There's a way to get coordinates without the navigator.geolocation requests using Apple's CLLocation manager (kinda tested it). Let me know if you weren't able to resolve the issue. Happy to help!

**Comment by rick-xukai** [comment]
@nilayarya Thanks for your reply. Sorry. I forgot about this question. About what you said. How do you call Apple's API?

**Comment by nilayarya** [comment]
@rick-xukai I'm trying to bridge it completely. I'll keep you posted.

**Comment by nilayarya** [comment]
> @nilayarya Thanks for your reply. Sorry. I forgot about this question. About what you said. How do you call Apple's API?

Can you test navigator.geolocation.getcurrentposition once more and let me know if it still hasn't been patched.

**Comment by nilayarya** [comment]
@rick-xukai you can check out https://github.com/nilayarya/electron/tree/custom-geolocation-manager and build it yourself. It's a working solution to request geolocation permission and get current coordinates. Instructions on how to use are here: [https://github.com/nilayarya/electron/pull/1](https://github.com/nilayarya/electron/pull/1)
