### ISSUE TITLE
[Bug]: <select> not rendering in OSR when the offscreen BrowserWindow is created after any other window

### ISSUE THREAD

**Issue by EladBahar** [electron/electron#40832]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 

### What arch are you using?

x64

### Expected Behavior

create BrowserWindow,  and render another offscreenWindow in to canvas in to main window.
when trying to click on the select <select> drop down options should be rendered.

### Actual Behavior

<select> drop down offscreen doesn't, 
when createing the oddscreeen window after main window was created.

### Testcase Gist URL

https://gist.github.com/EladBahar/8e4aa38cb742227021ece5516a2c95b2

### Additional Information

**working:**
![working-video](https://github.com/electron/electron/assets/6461532/6adc75c0-9bce-4e98-9f54-6288ec1aef3f)

**not working:**
![not-working](https://github.com/electron/electron/assets/6461532/f8f03b23-6b77-4a53-8831-3cf56e065ad9)

**Comment by dowmeister** [comment]
bump

**Comment by EladBahar** [comment]
@codebytere hey, 
any update maybe?

**Comment by EladBahar** [comment]
bump
