### ISSUE TITLE
[Bug]: generated config.gypi always reports libraries as not shared

### ISSUE THREAD

**Issue by selfisekai** [electron/electron#40836]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.0

### What operating system are you using?

Other Linux

### Operating System Version

Alpine Linux edge

### What arch are you using?

x64

### Expected Behavior

unbundling a dependency of node.js should set appropriate variables in config.gypi. 
- for ones shared with chromium, like `zlib`, this should follow whether it got unbundled with `//build/linux/unbundle/replace_gn_files.py`, and set `node_shared_zlib` accordingly
- for node.js-specific ones, like `cares`, setting `use_system_cares` (defined in `//third_party/electron_node`) should add `--shared-cares` to args in `//electron:generate_config_gypi`, which will set `node_shared_cares` accordingly. or does it actually change any behavior in the generator? if not, it can also be a swap at the end.
- openssl is a special care one. alpine's policy is that openssl should be unbundled, but boringssl should be bundled (no abi stability). boringssl symbols are not getting re-exposed to node modules, and so, modules should depend on distro's openssl headers and mark openssl's libraries as needed, am i right?

### Actual Behavior

all dependencies are marked as bundled. `//third_party/electron_node/tools/install.py` installs openssl (yes, not boringssl) and zlib headers (and a different config.gypi, but that's another story)

**Comment by codebytere** [comment]
@selfisekai can you share more about what you're trying to do here? Why are you seeking to unbundle them?

**Comment by selfisekai** [comment]
@codebytere i'm the maintainer of electron in alpine linux. unbundling is a standard distro policy (e.g. https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling) that i believe pretty much any distro does with chromium. this enables de-duplication of the same libraries (like libwebp) that we also use in chromium and other apps, and allows us to ship security updates to them much more quickly

**Comment by brjsp** [comment]
In openSUSE we use the  `copy_node_headers` ninja target (called `copy_headers` in older versions) and <a href="https://build.opensuse.org/package/view_file/devel:languages:nodejs/nodejs-electron/no-zlib-headers.patch?expand=1">patch out the zlib dependency</a>. This does not attempt to pull in openssl/boringssl.

**Comment by selfisekai** [comment]
still affected

**Comment by selfisekai** [comment]
bump
