### ISSUE TITLE
When the role of menu is undo or redo, clicking the menu does not work, but the shortcut keys can be used

### ISSUE THREAD

**Issue by Gemini-0529** [electron/electron#40837]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.1.0

### What operating system are you using?

Windows

### Operating System Version

windows10

### What arch are you using?

x64

### Expected Behavior

```ts
{
    label: '编辑',
    submenu: [
      {
        label: '撤销',
        role: 'undo'
      },
      {
        label: '重做',
        role: 'redo'
      }
    ]
  },
```
I expect that pressing a shortcut key will have the same effect as clicking a menu bar button.

### Actual Behavior

At present, pressing the shortcut keys of undo and redo in my application works normally, but clicking the corresponding menus does not work.

**Comment by Gemini-0529** [comment]
@

> Hello @Gemini-0529. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the [ blocked/need-repro](https://github.com/electron/electron/labels/blocked%2Fneed-repro) Needs a test case to reproduce the bug label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

Thank you very much for your reply. I discovered the cause of the problem in fiddle.

**Comment by codebytere** [comment]
Great! I'm going to close this out then but if more information crops up i'm happy to reopen.
