### ISSUE TITLE
[Bug]: Mac OS Sonoma Occluded Windows No Longer Works

### ISSUE THREAD

**Issue by ProdigyView** [electron/electron#40849]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

28.1.0

### Expected Behavior

Occluded windows is a chrome flag that when displaying a desktop window on screen using 'navigator.mediaDevices.getUserMedia', when the window loses focus the video will not stop. Otherwise if you are a on a multi-desktop mac, ie using spaces, and you switch Desktops, the video captured using navigator.mediaDevices.getUserMedia will stop. Or on Windows, if you make a window that goes full like a  game, the video will stop.

The flag has the same functionality on Windows and Mac and is set using : 'disable-backgrounding-occluded-windows'.

### Actual Behavior

I recently updated to Mac OS Sonoma, and when a window is made full screen, ie a game, the video stops. If I go back to a previous version like Mac Os Ventura, it works perfectly fine. And it still works on Windows. So either:
1. This an Mac OS Sonoma issue
2. A different chrome flag has to be used.

**Comment by codebytere** [comment]
Given this is a Chrome flag i recommend reporting this upstream at crbug.com
