### ISSUE TITLE
[Bug]: Close event doesn't fire since v20

### ISSUE THREAD

**Issue by eden-lane** [electron/electron#40857]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20+

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.0

### What arch are you using?

x64

### Last Known Working Electron version

19

### Expected Behavior

When you prevent window from closing, it should be possible to show it again without creating it.

### Actual Behavior

You get an error when you try to show existing window:
![image](https://github.com/electron/electron/assets/2963477/c3cef348-14d4-45b5-bb0c-c6d84a7a290d)

### Additional Information

It looks like 'close' event doesn't fire at all. 
I'm using the following code, which works in `electron@19.1.9` and stops working in `electron@20`.:

```ts
let createWindow;

function createCreateWindow() {
  createWindow = new BrowserWindow({
    alwaysOnTop: false,
    transparent: true,
    frame: false,
    show: false,
    height: 600,
    width: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
    },
  });

  createWindow.maximize();

  if (isDev && !isPackaged) {
    createWindow.loadURL('http://localhost:8080/create.html');
  } else {
    createWindow.loadFile(path.join(__dirname, './create.html'));
  }

  createWindow.on('close', (ev) => {
    if (!isQuitting) {
      ev.preventDefault();
      createWindow.hide();
    }
  });
}

app.whenReady().then(async () => {
  createCreateWindow();

  globalShortcut.register('CommandOrControl+Shift+C', () => {
    createWindow.show();
    createWindow.focus();
  });
})
```

**Comment by LoveLuanQi1202** [comment]
same in v28.1.2

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
