### ISSUE TITLE
[Bug]: InAppPurchase promises not resolving

### ISSUE THREAD

**Issue by TheMax98000** [electron/electron#40851]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 14.1.1 (23B81)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

In app purchase working as expected and described in the documentation.

### Actual Behavior

I want to integrate In App Purchase, i setup all the code correctly, in development or in "production" via testflight any of the methods inAppPurchase.getProducts or inAppPurchase.purchaseProduct didn't work.

The first one return a promise that never resolve, the second one just didn't do anything.

I tested to upgrade to electron 29.0.0 -> Same behaviour.

I downgraded my electron version to 24.1.0 and i got another behaviour.

In this version all work fine in development, but not in "production" via testflight, via testflight the inAppPurchase.getProducts didn't resolve the promise too and only the inAppPurchase.purchaseProduct kinda work but i didn't receive any inAppPurchase.on("transactions-updated") event so it's also unusable (can't restore purchases or check if a purchase is made if i didn't get the events).

**Comment by TianbinTobin** [comment]
Electron Version 26.6.4 works fine.
