### ISSUE TITLE
[Bug]: calling app.hide before or after webContens.startDrag doesnt hide the app until drag is finished

### ISSUE THREAD

**Issue by MoeBazziGIT** [electron/electron#40869]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS 14.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

All windows of the app to be hidden, just like the app.hide docs say.

### Actual Behavior

No windows are hidden

### Additional Information

Doing the following does not hide the app windows until after the drag has finished.
```
ipcMain.on('ondragstart', (event, file) => {
  app.hide()
  event.sender.startDrag({
    file: file,
    icon: getDragIconForFile(file.path)
  })
})
```

However, when wrapping the webContents.startDrag method in a setTimeout, the app gets hidden:
```
ipcMain.on('ondragstart', (event, file) => {
  app.hide()
  setTimeout(() => {
    event.sender.startDrag({
      file: file,
      icon: getDragIconForFile(file.path)
    })
  }, 0)
})
```

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by claudia-romano** [comment]
Hi there, here's the code to reproduce the bug:
https://gist.github.com/e63fdcfab93b9cfa21586cd828c14353

Thank you
