### ISSUE TITLE
[Feature Request]: allow passing web preferences to an iframe

### ISSUE THREAD

**Issue by alissawix** [electron/electron#40870]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to enable `nodeIntegration` in **some** of my iframes.
the same way it's possible for `window.open`

### Proposed Solution

I think it will be useful to be able to pass [WebPreferences](https://www.electronjs.org/docs/latest/api/structures/web-preferences) to an iframe (in my case I need `nodeIntegration` and `contextIsolation`).

the same way we can pass them to [`window.open`](https://www.electronjs.org/docs/latest/api/window-open) , or add something like [`setWindowOpenHandler`](https://www.electronjs.org/docs/latest/api/web-contents#contentssetwindowopenhandlerhandler) for iframes as well (after all they are windows too).

### Alternatives Considered

using `nodeIntegrationInSubFrames` setting, but it is global, for all frames.

or using [`BrowserView`](https://www.electronjs.org/docs/latest/api/browser-view) instead of iframes, but it behaves differently and requires a significant refactor. 

another option could be maybe to pass `require` from the parent window, but I can't use parent `process`, but that doesn't sound like a good idea anyway..

**Comment by codebytere** [comment]
@alissawix can you explain in more detail the use case you're trying to enable? Can it be accomplished through an alternate approach?

**Comment by nornagon** [comment]
This isn't possible on a per-`<iframe>` basis due to Chromium's architecture. `<webview>` is probably what you're looking for.

**Comment by alissawix** [comment]
@nornagon thank you for clarifying that

electron advise against using `webView` - https://www.electronjs.org/docs/latest/tutorial/web-embeds#webviews
