### ISSUE TITLE
[Bug]: Electron titlebar interferes with mouse events

### ISSUE THREAD

**Issue by PocketMage** [electron/electron#40874]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

macOS

### Operating System Version

12.6.6

### What arch are you using?

x64

### Expected Behavior

Mouse hover events responding normally at the top 40-50 pixels of a customized window that does **not** have a titlebar.

### Actual Behavior

I have customized my Electron app's titlebar to be hidden but still display the traffic lights. In it's place I have created a custom titlebar which is 45 pixels high and contains several interactive elements, mainly buttons. This is my BrowserWindow configuration:

```typescript
{
    width: 2200,
    height: 1200,
    webPreferences:
    {
        nodeIntegration: true,
        preload: path.join(__dirname, './preload.js'),
    },
    autoHideMenuBar: true,
    frame: false,
    titleBarOverlay: { height: 0 },
    titleBarStyle: 'hidden',
    trafficLightPosition: {x: 10, y:10},
    show: false,
}
```

The buttons I have added to the titlebar are about 32 pixels high and have the cursor: pointer; style along with a background that changes from gray to white. Whenever I hover over them, the background color correctly changes from gray to white, however, the cursor only changes to a pointer when I place my house on the bottom half of the button. It does not change to a point when my mouse is at the top half. The exact same thing happens whenever I hover selectable text, my pointer only changes on the bottom half of the element.

This bug does not happen when I hover over the button on the local server I use for Svelte, which is an address I can open in a web browser, meaning my CSS styling is not the issue.

Furthermore, when I don't hide the titlebar, or when set the titleBarStyle to default, the hover effects work just fine.

Based on the size of the button that doesn't work, I believe the titlebar could be "hidden" only visually and still be registering mouse events before my elements.

### Testcase Gist URL

Minimum reproducible example made with Electron Fiddle, Gist: https://gist.github.com/PocketMage/f484481e0cf831e9104e35f188f73ba2

### Additional Information

While investigating I opened a StackOverflow question regarding this issue. After noticing different another Electron-based application, namely Discord, showed similar behavior (ie, I noticed the same bug) I decided to open this issue here in hopes of helping the development of this project.

**Comment by PocketMage** [comment]
Minimum reproducible example made with Electron Fiddle, Gist: https://gist.github.com/PocketMage/f484481e0cf831e9104e35f188f73ba2

**Comment by PocketMage** [comment]
Minimum reproducible example made with Electron Fiddle, Gist: https://gist.github.com/PocketMage/f484481e0cf831e9104e35f188f73ba2

**Comment by georgexu99** [comment]
👋 Hello! Maintainer here. I tried reproducing it and I'm not sure I'm seeing what you are describing- would you mind attaching a video or some screenshots of the behaviour to assist in investigating this bug?

**Comment by leonardxfce-dialpad** [comment]
Hi Team, I can reproduce this bug also. Starting electron 23.  We have in macOS version of our app some buttons close to the position `titleBar` , if we use "titleBarStyle" as hidden, our buttons respond to hover event or even click events. Something I noticed it's left click works as expected and then after the first left click made on that zone the click event start to work again.
