### ISSUE TITLE
[Bug]: Spotify Application can not play song & opens a new electron window on clicking each song or play all button

### ISSUE THREAD

**Issue by alapanc17** [electron/electron#40878]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.6.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise Version 23H2 OS Build 22631.2861

### What arch are you using?

x64

### Last Known Working Electron version

Do not know

### Expected Behavior

Spotify application should behave like the Mobile application or Web application. We should be able to play songs via the play all button or individual play button beside each song.

### Actual Behavior

Individual play button is not available beside each song. And when we click on each song or click on the play all button it keeps on opening new electron windows. 

![Screenshot 2024-01-04 115843](https://github.com/electron/electron/assets/149356022/a3b91838-6bb8-4794-8d04-691cc62c91d9)

![Screenshot 2024-01-04 115859](https://github.com/electron/electron/assets/149356022/b3c29f0e-26e3-41af-bf4f-490c874ccaed)

### Testcase Gist URL

https://gist.github.com/108235026251961961a2c2299cc92bfa

**Comment by jkleinsc** [comment]
@alapanc17, I added the https://github.com/electron/electron/labels/blocked%2Fneed-repro label because the testcase you have provided is unfortunately depending on a third party external dependency (Spotify web app).  The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.  If you can come up with a test case that specifically highlights the issue in Electron this issue may be able to move on.

**Comment by ivan-bialotski-sm** [comment]
Any updates on that issue? Has anyone solved it?

**Comment by Erisdar** [comment]
Any updates on that issue? Has anyone solved it?

**Comment by anshluu** [comment]
+1 on this. Any solutions?

**Comment by dsanders11** [comment]
Hey folks. This looks like it's just the Spotify Web app acting differently due to Electron's user agent string, nothing specific to Electron itself. It looks like you can get it to act as expect by setting the user agent string to match Chrome's before creating the `BrowserWindow`.

```
session.defaultSession.setUserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36")
```
