### ISSUE TITLE
[Bug]: some kind of color in css did not shown in electron on some pc.

### ISSUE THREAD

**Issue by chinaofmelon** [electron/electron#40911]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.7.0

### What operating system are you using?

Windows

### Operating System Version

10.0.18363

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

The html show correct, and color show correct.

### Actual Behavior

Background color of button show as transparent and did not show the correct color.

correct in edge:
![edge](https://github.com/electron/electron/assets/9248242/a6d9ba51-d1fa-4c05-bdb1-64309e36ec16)

incrrect in electron:
![electron](https://github.com/electron/electron/assets/9248242/1f46950c-ea4c-49d0-8e4c-957732ce0ede)

### Testcase Gist URL

https://gist.github.com/8baa05ddb396c78ab633385ff308ce10

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
