### ISSUE TITLE
[Bug]: stale renderer process on quit

### ISSUE THREAD

**Issue by meteor199** [electron/electron#40921]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19045.3324

### What arch are you using?

x64

### Expected Behavior

When the Electron app is closed, there should be no stale renderer processes.

### Actual Behavior

After closing the Electron app, a residual renderer process occurs.

### Additional Information

In our Electron application, we use BrowserView. When a particular BrowserView opens a code-server website and then the BrowserWindow is immediately closed and the Electron app is exited, it results in the residual rendering process of that BrowserView. Moreover, this residual process occupies more than 10% of the CPU. 

The issue can only be reproduced if the app is closed within 2 seconds of opening the code-server page. If the app is closed a few seconds after opening, the issue does not reoccur

Since this is an internal project, the source code cannot be provided. I attempted to recreate this issue with a minimal example using the same BrowserWindow and BrowserView, but was unable to reproduce it.

This issue is different from that issue : https://github.com/electron/electron/pull/32888
This is a log recorded by Windows Performance Recorder. It can be analyzed using Windows Performance Analyzer.

https://drive.google.com/file/d/1mAMZTplHOLJJ2LSPODiu8U_5JaDAZdao/view?usp=sharing

The residual process ID is 16036. The actual Electron version is 28.1.2.
![image](https://github.com/electron/electron/assets/21106029/2e8dd8e5-7064-4d8d-8f0c-a457ea30a6d3)

**Comment by meteor199** [comment]
进程16036有两个线程耗费了大量CPU，
这是线程22040
![image](https://github.com/electron/electron/assets/21106029/6ac65183-2d39-4ce7-8974-441a8d188c04)

这是线程3232
![image](https://github.com/electron/electron/assets/21106029/bc84551a-8442-494e-89e6-eb9693121760)

**Comment by meteor199** [comment]
This is the repository URL ：https://github.com/meteor199/issue-electron-stale-renderer-process




## How to Start

```bash
pnpm i
npm start
```
After BrowserWindow opens, it will auto-close after 1 second, and then a stale renderer process will appear.

## Steps to Reproduce
1. Open a BrowserWindow
2. Attach a BrowserView to the BrowserWindow
3. Add an iframe in the BrowserView, and let the iframe block the process
4. Once the BrowserView page is displayed, after 1 second, instantly close the window and exit the program. A stale renderer process will appear.

**Comment by meteor199** [comment]
The issue exists with the iframe, whereas the webview is functioning normally.

**Comment by abigail-0111** [comment]
Hi, I seem to have the same problem. Same `iframe` in `BrowserView`, same residual process. And this causes my `auto-updater` to fail to install after executing `quitAndInstall()`, prompting that "the app is still not closed". Any new ideas?

**Comment by abigail-0111** [comment]
`app.exit()` doesn't work. I found a new way to exit.

```
const killAllProcesses = (): void => {
  const metrics = app.getAppMetrics()
  const processIds = new Set()

  metrics.forEach((metric) => {
    if (metric.type === 'Tab') {
      processIds.add(metric.pid)
    }
  })

  const { exec } = require('child_process')
  for (const pid of processIds) {
    exec(`taskkill /F /PID ${pid}`, (error) => {
      if (error) {
        console.error(`Failed to kill process ${pid}:`, error)
      } else {
        console.log(`Successfully killed process ${pid}`)
      }
    })
  }
}

app.on('quit', () => {
  if (process.platform === 'win32') {
    killAllProcesses()
  }
})
```

My application is for Windows only. It works for me..
