### ISSUE TITLE
[Bug]: setIgnoreMouseEvents is not working on ubuntu 22.04 wayland compositor

### ISSUE THREAD

**Issue by MajdAlbaho** [electron/electron#40935]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04 wayland compositor

### What arch are you using?

x64

### Expected Behavior

By setting setIgnoreMouseEvents to true for the main window, I should be able to pass the mouse click through it, it is working on x11 compositor on ununtu 20.04 but it's not on 22.04 wayland compositor

### Actual Behavior

The actual behavior is the window blocking the mouse clicks and it's not passed through it

### Additional Information

This bug 🐛 occurred on ubuntu 22.04 wayland compositor

**Comment by MajdAlbaho** [comment]
Added on Electron Fiddle, just to mention that this is on ubuntu 22.04 wayland compositor
https://gist.github.com/MajdAlbaho/7029b97379394356c1cb35bf77f95bca

**Comment by MajdAlbaho** [comment]
Any updates ?

**Comment by MajdAlbaho** [comment]
@zcbenz 
@kevinsawicki 
@codebytere 
@MarshallOfSound 

Please guys have a look

**Comment by MajdAlbaho** [comment]
@zcbenz @kevinsawicki @codebytere @MarshallOfSound @electron-bot

**Comment by MarshallOfSound** [comment]
@MajdAlbaho Spam pinging maintainers who happen to be at the top of the "Contributors" page is not the way to get attention on your issue, it's disrespectful to maintainers who you are spamming and a violation of our code of conduct.

And frankly, a surefire way for me to never want to look at your issue.  Please reconsider how you interact with open source projects. Do not spam ping maintainers again.

**Comment by MajdAlbaho** [comment]
@MarshallOfSound I just wanna say really sorry for this, it is my bad and it will never happen again

I appreciate your understanding.
