### ISSUE TITLE
[Bug]: Recursive rmdir returns error while trying to remove folder, that contains asar file.

### ISSUE THREAD

**Issue by tangjfn** [electron/electron#40943]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22631.3007

### What arch are you using?

x64

### Last Known Working Electron version

27.*.*

### Expected Behavior

await fs.promises.rm("path contains asar file",{force: true, recursive: true})
// no throw

### Actual Behavior

await fs.promises.rm("path contains asar file",{force: true, recursive: true})
// throw a error ENOTEMPTY: directory not empty, rmdir '...'

**Comment by MarshallOfSound** [comment]
If you want to treat ASAR files as "files" instead of transparently treating them as filesystems, you have to use `original-fs` instead of `fs`.

E.g. `const fs = require('original-fs')`

That is an unmodified version of the fs module that doesn't include our patches for asar support

**Comment by tangjfn** [comment]
original-fs throw same error
