### ISSUE TITLE
[Bug]: Updated time zone not getting picked up by Intl.DateTimeFormat().resolvedOptions().timeZone

### ISSUE THREAD

**Issue by mikeyyyzhao** [electron/electron#40944]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

macOS

### Operating System Version

13.5.2 (22G91)

### What arch are you using?

ARM64

### Last Known Working Electron version

27.1.2

### Expected Behavior

if user changes time zone (physically or through system preferences) -> enter `Intl.DateTimeFormat().resolvedOptions().timeZone` into inspector console -> time zone changes

### Actual Behavior

The way to reproduce is:
go to macOS settings (aka "System Preferences" -> change system time zone
go to electron app -> open inspector
type `Intl.DateTimeFormat().resolvedOptions().timeZone` into inspector console
console will print the previous time zone (before you changed the timezone in settings)
refreshes won't help (will still print old time zone)
quitting the app and then reopening fixes the issue

### Testcase Gist URL

https://gist.github.com/mikeyyyzhao/be048395ddedb290a947d63a3002fdb7

**Comment by codebytere** [comment]
@mikeyyyzhao can you verify if this happens in Chrome itself on your machine or if it's specific to Electron?

**Comment by mikeyyyzhao** [comment]
@codebytere I am also seeing this on chrome (120.0.6099.129)

**Comment by codebytere** [comment]
@mikeyyyzhao then you should report this upstream via [crbug](crbug.com) - when they fix it we'll inherit the fix via our upgrade process!

**Comment by rickpastoor** [comment]
For anyone landing here (hey @mikeyyyzhao 👋): this bug in Chromium is fixed and will land in Electron when it's updated to Chromium 124. See: https://issues.chromium.org/issues/41495940

**Comment by mikeyyyzhao** [comment]
Thanks for the update @rickpastoor !

**Comment by mikeyyyzhao** [comment]
@codebytere @rickpastoor is there a rough timeline on when Electron will get updated to chromium 124? I see that the latest stable version of chromium (v29.1.5) is still on chromium 122.

**Comment by rickpastoor** [comment]
Electron on versioning [here](https://www.electronjs.org/docs/latest/tutorial/electron-timelines):

> Electron targets Chromium even-number versions, releasing every 8 weeks in concert with Chromium's 4-week release schedule. For example, Electron 26 uses Chromium 116, while Electron 27 uses Chromium 118.

**Comment by mikeyyyzhao** [comment]
Thank you so much @rickpastoor !

**Comment by rickpastoor** [comment]
Electron 30 is stable now, and includes Chrome 124.
