### ISSUE TITLE
Cross-Compiling for Windows on Linux, as Chromium does

### ISSUE THREAD

**Issue by Alex313031** [electron/electron#40986]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Expected Behavior

Since Chromium M73, it can be cross compiled for Windows on Linux. I do this all the time. See > https://chromium.googlesource.com/chromium/src/+/master/docs/win_cross.md

I am building Electron for both Linux and Windows. It would make my workflow greatly easier if we could cross-compile Electron.
However, this doesn't seem to work. I have tried it with every major stable Electron version since 12.2.3.

Is this something that can be overcome, or is it a hard limitation because of Node?

### Actual Behavior

Cannot cross-compile for other OSes, only other architectures.

**Comment by MarshallOfSound** [comment]
This is not a supported build configuration for Electron, we don't do it or test it and therefore can't support other folks doing it.  If you want to try and figure it out, we'll take PRs that fix build issues, but we don't have the resources to support a build configuration we don't use.

(There's also zero change anyone can help if all you say is "it doesn't work" with no specific errors)
