### ISSUE TITLE
[Feature Request]: Set tray image and text ordering

### ISSUE THREAD

**Issue by JeffreyWardman** [electron/electron#40984]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I'd like to be able to set the text in a tray to the left of the image.

### Proposed Solution

Allow for an option/order of initialisation to determine this.

### Alternatives Considered

-

**Comment by codebytere** [comment]
@JeffreyWardman can you please describe a bit more what you're envisioning here? There are different platform considerations here and it'd be helpful to know what use case you're trying to solve or how this would help you.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by JeffreyWardman** [comment]
Apologies for the delay. At the moment, if adding text to the tray, it appends to the right of the icon but there doesn't appear to be a way to set it to appear to the left.
