### ISSUE TITLE
[Bug]: `-webkit-app-region: drag` doesn't works

### ISSUE THREAD

**Issue by JellyBrick** [electron/electron#40985]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0.0-alpha.9, 29.0.0-alpha.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 (22631)

### What arch are you using?

x64

### Last Known Working Electron version

29.0.0-alpha.7

### Expected Behavior

If `-webkit-app-region: drag` was used, it should be possible to click on the region and drag the `Window`. 

### Actual Behavior

It will behave as if the property is not applied.

### Testcase Gist URL

https://gist.github.com/5e1d4f4331881ef8c608b8ab61cef9ac

**Comment by codebytere** [comment]
cc @nornagon - tracked to https://github.com/electron/electron/pull/35658

**Comment by yi-ge** [comment]
I have encountered the same problem, I also cannot drag and drop in MacOS.

**Comment by JellyBrick** [comment]
This issue remains under certain conditions (behavior is different from 29.0.0-alpha.7)

**Comment by deepak1556** [comment]
Can you provide a test case and clarify which conditions break the draggable behavior ? Thanks!

**Comment by JellyBrick** [comment]
> Can you provide a test case and clarify which conditions break the draggable behavior ? Thanks!

I'm not sure under what conditions this happens yet. (We're investigating the cause)

Application: https://github.com/th-ch/youtube-music
(It works fine with 29.0.0-alpha.7, but not with 29.0.0-beta.4)
