### ISSUE TITLE
[Feature Request]: Bypass the "allow paste"

### ISSUE THREAD

**Issue by linonetwo** [electron/electron#40995]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

![截屏2024-01-15 22 12 04](https://github.com/electron/electron/assets/3746270/30d3f964-4b14-415a-992b-0262b599b100)
(screenshot: brand new fiddle)

In latest v29, I can't directly paste things in the developer tools for debugging on devTool of a BrowserWindow. This make dev experience worse a bit.

This also happen on BrowserView on a BrowserWindow.

### Proposed Solution

Add a preference for BrowserWindow and BrowserView to allow disable this "security feature".

### Alternatives Considered

Or at least disable this during development...

**Comment by codebytere** [comment]
@linonetwo this is something mediated by Chrome DevTools - please file a bug at https://crbug.com/ to request the team consider allowing a conditional bypass.

**Comment by linonetwo** [comment]
Ok, fired https://bugs.chromium.org/p/chromium/issues/detail?id=1518788

**Comment by wanghanzhen** [comment]
> @linonetwo this is something mediated by Chrome DevTools - please file a bug at https://crbug.com/ to request the team consider allowing a conditional bypass.

Chrome DevTools has a setting that can control it.
<img width="563" alt="image" src="https://github.com/electron/electron/assets/25301012/65da4336-eb88-49ae-904d-9a5ccc005c7e">
but every time I restart electron app, this setting will be reset to the enable state which is really annoying.

I reviewed the DevTools source and found the following code.
```javascript
Common.Settings.Settings.instance()
      .createSetting('disable-self-xss-warning', false, Common.Settings.SettingStorageType.Synced)
      .set(true);
```

Perhaps we can patch devtools_frontend to export the Common object and disable it by `openDevTools`.
https://github.com/electron/electron/blob/main/patches/devtools_frontend/chore_expose_ui_to_allow_electron_to_set_dock_side.patch

like:
```javascript
webContents.openDevTools({ disableSelfXssWarning: true });
```

**Comment by wolfib** [comment]
We've added a Chrome command line flag to disable self-XSS warnings: `--unsafely-disable-devtools-self-xss-warnings`(https://crbug.com/41491762 for details)

**Comment by linonetwo** [comment]
This only work for electron window:

```ts
app.commandLine.appendSwitch('--unsafely-disable-devtools-self-xss-warnings');
```

But doesn't work for WebContentsView, @codebytere need to reopen

```
    const view = new WebContentsView({
      webPreferences: {
        additionalArguments: ['--unsafely-disable-devtools-self-xss-warnings'],
      },
    });
```

![Image](https://github.com/user-attachments/assets/f95d68f3-5edf-4f27-96d6-07b3d3d00218)

![Image](https://github.com/user-attachments/assets/f3558a26-7391-45c6-9021-e4de7d52be59)

**Comment by paralin** [comment]
@linonetwo Did you find a solution?

**Comment by linonetwo** [comment]
No, maybe need to send another ticket.
