### ISSUE TITLE
[Bug]: iframe cannot inherit the modified ua on webContents 

### ISSUE THREAD

**Issue by bayun2** [electron/electron#40990]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.5.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I open devtools, print the current ua on the console, and switch to the iframe to print the ua inside the iframe.
iframe can inherit the modified ua on webContents

### Actual Behavior

iframe cannot inherit the modified ua on webContents 

### Testcase Gist URL

https://gist.github.com/bayun2/892a9213c91d7eee2002b1967a8e4fde

**Comment by bayun2** [comment]
bump

**Comment by bayun2** [comment]
bump

**Comment by bayun2** [comment]
@codebytere @mlaurencin It hasn’t been dealt with yet, I hope it can be reopened

**Comment by mlaurencin** [comment]
@bayun2 Can you confirm a currently supported version that this issue can be reproduced on?
