### ISSUE TITLE
[Bug]: `original-fs` does not provide unmodified methods

### ISSUE THREAD

**Issue by erikian** [electron/electron#41008]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

`original-fs` should provide unmodified methods from Node.js' `fs` module

### Actual Behavior

`original-fs` seems to be using our ASAR patches that are meant to be applied only when importing the plain `fs` module in Electron

### Testcase Gist URL

https://gist.github.com/3f029d290d598c9e1d1322c25c48c575

### Additional Information

The Fiddle above is just a slight variation of the repro provided by @tangjfn in #40943 / #40960 (thanks for the test case!), where you can enter a path to a folder containing an `.asar` file and attempt to remove it using `fs.promises.rm` or `fs.promises.rmdir`. They both fail with `ENOTEMPTY: directory not empty`:

![image](https://github.com/electron/electron/assets/19478575/e7555a0f-7fa2-43b6-ac43-d00b94f191e1)

**Comment by codebytere** [comment]
Introduced in https://github.com/electron/electron/compare/v28.0.0-nightly.20230830...v28.0.0-nightly.20230831 h/t @dsanders11  - likely https://github.com/electron/electron/commit/ac031bf8dedf8e3da6d918cbbc2e64a03830c639
