### ISSUE TITLE
[Bug]: "ReferenceError: dragEvent is not defined" when switch devtools tabs

### ISSUE THREAD

**Issue by subframe7536** [electron/electron#41007]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Expected Behavior

should not have such error

### Actual Behavior

![recording](https://github.com/electron/electron/assets/78338239/8d3c3dab-02e0-4424-9a56-803c0f1e1751)

**Comment by subframe7536** [comment]
https://gist.github.com/subframe7536/29104f57e7bb7e1f77583dc98e521c93

**Comment by ry0513** [comment]
I didn't have any issues in version 27.2.4, but encountered this problem in version 28.0.0.

**Comment by codebytere** [comment]
This was a Chromium upstream issue - it's since been fixed [here](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/5067599).
