### ISSUE TITLE
[Bug]: Error expected when instantiating Request

### ISSUE THREAD

**Issue by Lingyan000** [electron/electron#41005]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.3

### What operating system are you using?

Windows

### Operating System Version

22631.3007

### What arch are you using?

x64

### Last Known Working Electron version

28.1.3

### Expected Behavior

The following code should print application/json.
```js
let request = new Request('https://www.google.com')
request.headers.set('Content-Type', 'application/json')
request = new Request(request, {
  method: 'GET'
})
console.log(request.headers.get('Content-Type'))
```

### Actual Behavior

actually prints null.

### Testcase Gist URL

https://gist.github.com/31b1185f3021f64e70b4e9993eae31e4

**Comment by Lingyan000** [comment]
\

> @Lingyan000 you've put 28.1.3 both for the affected version and the last working version. Did this previously work as expected, and if yes, in what version?

problems start at 28.0.0, 27.x.y is normal.

**Comment by codebytere** [comment]
Tracked to https://github.com/electron/electron/compare/v28.0.0-beta.4...v28.0.0-beta.5

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/41019
