### ISSUE TITLE
[Bug]: cant install electron in mac

### ISSUE THREAD

**Issue by williamding1989** [electron/electron#41009]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Latest(v28.1.3)

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

/

### Expected Behavior

install electron successful

### Actual Behavior

it makes error at the fourth step : Building fresh packages...
![WX20240117-004912@2x](https://github.com/electron/electron/assets/34363860/37c19959-5c64-4b16-94a6-8646d1fd3696)

### Additional Information

![WX20240117-004938@2x](https://github.com/electron/electron/assets/34363860/5f4a7a69-b950-45c3-a086-92c70cf911ae)

**Comment by ckerr** [comment]
It's working for me right now; this was probably a network error yesterday.

Please file a new ticket if the problem persists. Thank you!
