### ISSUE TITLE
[Bug]: `-webkit-app-region: drag;` in underlying browserView blocks mouse interaction

### ISSUE THREAD

**Issue by Imperat** [electron/electron#41002]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Actual Behavior

I have an app which has two BrowserViews: title bar and content.
Content view can go full-screen via HTML5 Fullscreen API. In that case I listen to `enter-html-full-screen` event on webContents of content view and change it's size to be the size of all app window.

Content view is placed on top of title bar view. Part of title bar view (which is behind content and which is marked as drag area via css rule `-webkit-app-region: drag`) blocks event handling in content view.

Please, run my fiddle example. It will have:
1. orange area - my content view
2. green area - is my title bar view
3. blue area - `div` element which has css rule `-webkit-app-region: drag`.

After that, please move mouse in orange area and see that title of button is updated. Click the button to go to full-screen and move mouse to the top of the screen. Button label will have title `x: SOME_VALUE, y: 0`.

Start slowly moving cursor down and see that the value stops receiving updates when y is 7. It will start receive updates only when y value is 59. Those values perfectly match height of blue area which is 51.

### Expected Behavior

`-webkit-app-region: drag` does not affect other views when it is placed behind them.

### Testcase Gist URL

https://gist.github.com/Imperat/45c09b8c558ee9b99e1c3270db7cfee6

**Comment by codebytere** [comment]
@Imperat did this work in any versions prior to 28.1.3 that you're aware of? Additionally, are you experiencing it on any other platforms?

**Comment by Imperat** [comment]
Hi @codebytere 
Thank you for having a look!

I tested with Electron 26.6.2 & 28.1.3 on MacOS Sonoma 14.0 and I did not observe this issue.

For Windows I also tested it with Electron 26.6.2 & 27.2.2 and reproduced the bug.

**Comment by Imperat** [comment]
Could you please point me to the place in the source code where `component/draggable-regions` is implemented? I am more than happy to have a deep look

**Comment by codebytere** [comment]
@Imperat sure! https://github.com/electron/electron/pull/36230 should get you started with the general implementation

**Comment by Imperat** [comment]
Thinking out loud: 
It looks like the bug is [here](https://github.com/electron/electron/blob/03a3deca181807c2b152264a11f92c70b7adc9ef/shell/browser/native_window.cc#L768https://github.com/Imperat/electron/blob/03a3deca181807c2b152264a11f92c70b7adc9ef/shell/browser/native_window.cc#L768)

The implementation simply run test against each draggable region provider without considering occlusion state of the views.

It looks like that a particular case for the full screen mode is handled [here](https://github.com/electron/electron/blob/03a3deca181807c2b152264a11f92c70b7adc9ef/shell/browser/native_window_mac.mm#L1757
https://github.com/Imperat/electron/blob/03a3deca181807c2b152264a11f92c70b7adc9ef/shell/browser/native_window_mac.mm#L1757) for MacOS implementation.

I did not yet compile the code

**Comment by nornagon** [comment]
Here's a simpler repro: https://gist.github.com/nornagon/0965c258dd9048ae487c1b04df755868

**Comment by nornagon** [comment]
NB, this is, roughly speaking, expected behavior from an implementation perspective. I don't believe stacking BrowserViews like this has ever worked differently. I agree that it's surprising from a developer point of view, though!
