### ISSUE TITLE
[Bug]: Using  session.setProxy for HTTPS requests not work

### ISSUE THREAD

**Issue by menglingyu659** [electron/electron#41017]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.0

### What operating system are you using?

macOS

### Operating System Version

14.1.1 (23B81)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

27.1.0

### Expected Behavior

Both HTTPS requests and HTTP requests access proxy services

### Actual Behavior

HTTPS request did not access proxy service

### Testcase Gist URL

https://gist.github.com/menglingyu659/b40299d625cac78aadc96944a5eb6a95

### Additional Information

Thanks

**Comment by menglingyu659** [comment]
Please help to take a look at this issue

**Comment by codebytere** [comment]
@menglingyu659 you put the same version for broken and previously working. What was the last version in which this worked as you expected?

**Comment by mlaurencin** [comment]
We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/41017#issuecomment-1898531849). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
