### ISSUE TITLE
[Bug]: UtilityProcess stdout has always been null

### ISSUE THREAD

**Issue by tuyangJs** [electron/electron#41018]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows11 22h2

### What arch are you using?

ia32

### Expected Behavior

https://www.electronjs.org/zh/docs/latest/api/utility-process
According to the official document above, the case code can be run
demo:
```
// Main process
const { port1, port2 } = new MessageChannelMain()
const child = utilityProcess.fork(path.join(__dirname, 'test.js'))
child.postMessage({ message: 'hello' }, [port1])

// Child process
process.parentPort.once('message', (e) => {
  const [port] = e.ports
  // ...
})
```

### Actual Behavior

In fact, the situation is that the official provided code cannot run successfully, and the value of child.stdout has always been null. I have tried changing args and many combinations are the same.

**Comment by ckerr** [comment]
@tuyangJs can you confirm that the previous comment's suggestion solves the issue?

**Comment by ckerr** [comment]
This is expected behavior & is documented at https://www.electronjs.org/docs/latest/api/utility-process#childstdout
