### ISSUE TITLE
[Feature Request]: Unable to use 'import' to import Node.js modules in the renderer process when 'nodeIntegration' is set to true

### ISSUE THREAD

**Issue by fullmooooon** [electron/electron#41038]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Set nodeIntegration : true.
Attempt to use import to import Node.js modules in a Vue.js component or page within the renderer process.
Observe the console or application behavior.
```
Error: Module "fs" has been externalized for browser compatibility and cannot be accessed in client code.
```
Use ```const fs=require ('fs')```
Instead of ``` import fs from 'fs' ```
There will be no error output. But this way it won't cool at all

### Proposed Solution

I expect to be able to use the import syntax to import Node.js modules in the page, not limited to using require only.

### Alternatives Considered

 n/a

**Comment by MarshallOfSound** [comment]
This is an issue with your bundler.  It thinks that fs is not accessible in a browser environment, you must configure it differently.

Webpack has "electron" specific bundler targets, other bundlers probably have something similar.
