### ISSUE TITLE
[Bug]: When double clicking full screen, the background turns black

### ISSUE THREAD

**Issue by Apries406** [electron/electron#41039]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Expected Behavior

This is what the app I built using React18+electron28.1.1 looks like when opened normally on Windows
I expect that after double clicking to zoom in, it will keep the background color unchanged and zoom in to full screen
![image](https://github.com/electron/electron/assets/118501068/4dcfb73f-b1e5-4244-81d2-755c8a58d0ca)

### Actual Behavior

When I double-click to enlarge it to full screen
![image](https://github.com/electron/electron/assets/118501068/0b921393-3fbe-4597-b84f-db4f1a592018)

**Comment by michalzaq12** [comment]
Related to: https://github.com/electron/electron/issues/41073

**Comment by gaetandezeiraud** [comment]
On my side, don't turn black, but get the classic window decoration.
On Windows 11 & Electron 28.1.4. With just `backgroundMaterial: 'mica',`.

![image](https://github.com/electron/electron/assets/1573282/b85d8206-97be-4a80-acf1-12a9b32f9591)

**Comment by 3elDU** [comment]
bump. I have the same issue with 'mica' material.

**Comment by amnweb** [comment]
Both mica and acrylic have a problem, same issue in v28.x.x, also in 29.x.x, also i can see same problem now in VSCode Insiders which is v28.2.2. This is definitely electron bug.

**Comment by gerrykeys** [comment]
Any news about? I have the same issue here

**Comment by igorstefaniak** [comment]
bump

**Comment by richhost** [comment]
any update?
