### ISSUE TITLE
[Feature Request]: Device chooser for WebHID

### ISSUE THREAD

**Issue by mumangguo** [electron/electron#41047]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

const { app, BrowserWindow } = require('electron/main')

function createWindow () {
  const mainWindow = new BrowserWindow({
     width:1500,
     height:900,
  })
  
  //去掉菜单
  mainWindow.setMenu(null);
  mainWindow.webContents.session.on('select-hid-device', async (event, details, callback) => {
    // Add events to handle devices being added or removed before the callback on
    // `select-hid-device` is called.
    mainWindow.webContents.session.on('hid-device-added', (event, device) => {
      console.log('hid-device-added FIRED WITH', device)
      // Optionally update details.deviceList
    })

    mainWindow.webContents.session.on('hid-device-removed', (event, device) => {
      console.log('hid-device-removed FIRED WITH', device)
      // Optionally update details.deviceList
    })

    event.preventDefault()
    if (details.deviceList && details.deviceList.length > 0) {
      callback(details.deviceList[0].deviceId)
    }
  })

  mainWindow.webContents.session.setPermissionCheckHandler((webContents, permission, requestingOrigin, details) => {
    if (permission === 'hid' && details.securityOrigin === 'file:///') {
      return true
    }
  })

  mainWindow.webContents.session.setDevicePermissionHandler((details) => {
    if (details.deviceType === 'hid' && details.origin === 'file://') {
      return true
    }
  })

  mainWindow.loadFile('index.html')
}

app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
//......description
When I use the above code as my Electron entry file, I can access WEBHID normally, but it defaults to only accessing the first one. I searched for some documents but couldn't find out how to display the device list for WEBHID. Is there any relevant method for Electron to display it? I implemented it myself using the dialog component. I don't know, do I?
//....my code
//first
const { dialog } = require('electron')
//when the device is accessed
if (details.deviceList && details.deviceList.length > 0) {
    const deviceButtons = details.deviceList.map(device => device.name);

    // 显示设备列表对话框
    try {
      const result = await dialog.showMessageBox(mainWindow, {
        type: "info",
        title: "选择设备",
        message: "请选择一个设备：",
        buttons: deviceButtons
      });
      if (!result.canceled) {
        // 用户选择了一个设备，将设备 ID 传递给回调函数
        callback(details.deviceList[result.response].deviceId);
      }
    } catch (err) {
      console.error(err);
    }
  }

### Proposed Solution

//first
const { dialog } = require('electron')
//when the device is accessed
if (details.deviceList && details.deviceList.length > 0) {
    const deviceButtons = details.deviceList.map(device => device.name);

    // 显示设备列表对话框
    try {
      const result = await dialog.showMessageBox(mainWindow, {
        type: "info",
        title: "选择设备",
        message: "请选择一个设备：",
        buttons: deviceButtons
      });
      if (!result.canceled) {
        // 用户选择了一个设备，将设备 ID 传递给回调函数
        callback(details.deviceList[result.response].deviceId);
      }
    } catch (err) {
      console.error(err);
    }
  }

### Alternatives Considered

i dont konw?

### Additional Information

hope reply me!

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
