### ISSUE TITLE
[Bug]: When the application window is full screen, the exit full screen button in the upper left corner of MacOS cannot be clicked

### ISSUE THREAD

**Issue by wewehao** [electron/electron#41040]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.4

### What operating system are you using?

macOS

### Operating System Version

14.1.1 (23B81)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

28.1.0

### Expected Behavior

When the application window is full screen, the exit full screen button in the upper left corner of MacOS can be clicked

### Actual Behavior

Can't click, it's gray

### Additional Information

<img width="1427" alt="image" src="https://github.com/electron/electron/assets/29031861/a6793357-b17a-4c43-a810-adc720a1a603">
<img width="1187" alt="image" src="https://github.com/electron/electron/assets/29031861/9abcf49f-1d98-4c5f-8c94-60aab9d429ab">

**Comment by wewehao** [comment]
In fact, in version 28.1.0, you can exit full screen normally.

<img width="730" alt="image" src="https://github.com/electron/electron/assets/29031861/c7be3ae4-0c74-401d-b7c8-da0a304435ba">

**Comment by codebytere** [comment]
@tzahola is this perhaps related to recent changes?

**Comment by tzahola** [comment]
Fixed here: https://github.com/electron/electron/pull/40994

**Comment by codebytere** [comment]
Closing for above comment - thanks @tzahola!
