### ISSUE TITLE
[Bug]: GPU process exited unexpectedly: exit_code=34 When loading multiple videos

### ISSUE THREAD

**Issue by psyirius** [electron/electron#41057]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 22631.3007

### What arch are you using?

x64

### Expected Behavior

Run normally without crahsing the GPU process

### Actual Behavior

stdout
```
[25068:0119/194224.382:ERROR:gpu_process_host.cc(993)] GPU process exited unexpectedly: exit_code=34
```

UI window
![image](https://github.com/electron/electron/assets/99079175/2676922a-1e47-4487-aeed-bb31713f88c6)
White areas above are unrendered areas. when i hover over it. reactive areas will re render. like below

![image](https://github.com/electron/electron/assets/99079175/a8401de1-a282-414c-98ff-3758102cb6df)

### Additional Information

Happens when HW Acceleration is enabled
#31319

**Comment by psyirius** [comment]
https://stackoverflow.com/questions/69467977/gpu-process-exited-unexpectedly-exit-code-34-error-in-electron-js-on-scrollin

**Comment by troppoli** [comment]
I get this too, in Electron 38.4.0, on windows. I seem to be able to avoid it if I 
`            app.commandLine.appendSwitch('use-angle', 'vulkan');
            app.commandLine.appendSwitch('use-vulkan');
`
