### ISSUE TITLE
[Bug]: DesktopCapturer API cannot start audio source

### ISSUE THREAD

**Issue by Psyjakes** [electron/electron#41069]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 10.0.19045 Build 19045

### What arch are you using?

x64

### Expected Behavior

When I start the Desktop Capturer to record display video and audio it should use the default output audio stream

### Actual Behavior

When I have more than one connected output device (speakers and earphones) then I get a "DOMException: Could not start audio source".

### Additional Information

I use the exact method as shown on the docs page for DesktopCapturer
```const audioStream = await navigator.mediaDevices.getUserMedia({ audio: { mandatory: { chromeMediaSource: ‘desktop’ } }, video: { mandatory: { chromeMediaSource: ‘desktop’ } } } as any); ```
The as any is inserted to move around typescript errors

**Comment by Psyjakes** [comment]
Update on the issue, I tested with setting my audio output default to be the speakers and not my usb connected headset and it worked. This is still not ideal as the users of the app will have usb headsets

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
