### ISSUE TITLE
[Bug]: When you create a modal window, it is modal only to its parent window and not to the rest of the windows.

### ISSUE THREAD

**Issue by gamalielmendez** [electron/electron#41077]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Currently, I am developing an application with multiple windows, and some of these windows invoke others modally. My expectation is that, if I have at least two windows open and one of them calls its modal child, it should also block the second window(s).

### Actual Behavior

Currently, what happens is that when one of the windows calls its child modally, it is modal only for itself and does not affect other open windows at that time.

##### This is how I am creating the main window of the application.
```javascript 
    createWindow() {

        this.window = new BrowserWindow({
            width: 800,
            height: 600,
            show: false,
            webPreferences: {
                preload: path.join(__dirname, "../preload.js")
            },
        });

        //se configuran los eventos de la ventana
        this.window.on('closed', this.onClose.bind(this))
        this.window.once('ready-to-show', this.onShow.bind(this));

        //se configuran los ipcs
        this.configureIpcs();

        //carga la pantalla
        this.window.loadURL(this._url);

        if (isDev) {
            this.window.webContents.openDevTools();
        }

    }
```` 
##### This is how I am creating the secondary windows of the application.
```javascript 
  createWindow() {

        this.window = new BrowserWindow({
            parent: (this.parent) ? this.parent.window : null,
            width: 520,
            height: 400,
            resizable: false,
            maximizable: false,
            show: false,
            webPreferences: {
                preload: path.join(__dirname, "../preload.js")
            },
        });

        //se configuran los eventos de la ventana
        this.window.on('closed', this.onClose.bind(this))
        this.window.once('ready-to-show', this.onShow.bind(this));

        //se configuran los ipcs
        this.configureIpcs();

        this.window.setMenu(null)
        //carga la pantalla
        this.window.loadURL(this._url);
        //if (isDev) { this.window.webContents.openDevTools(); }

    }
```` 
##### This is how I am creating the modal windows of the application.
```javascript 
    createWindow() {

        this.window = new BrowserWindow({
            parent: (this.parent) ? this.parent.window : null,
            modal: true,
            width: 400,
            height: 180,
            show: false,
            resizable: false,
            minimizable: false,
            maximizable: false,
            webPreferences: {
                preload: path.join(__dirname, "../preload.js")
            },
        });

        //se configuran los eventos de la ventana
        this.window.on('closed', this.onClose.bind(this))
        this.window.once('ready-to-show', this.onShow.bind(this));

        //se configuran los ipcs
        this.configureIpcs();

        this.window.setMenu(null)
        //carga la pantalla
        this.window.loadURL(this._url);
        //if (isDev) { this.window.webContents.openDevTools(); }
    }
````
I hope you can help me solve this issue. I am available to provide more information if needed. Thank you.

**Comment by ckerr** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
