### ISSUE TITLE
[Bug]: Version reported in file is one patch release ahead

### ISSUE THREAD

**Issue by alerque** [electron/electron#41070]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.4

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Last Known Working Electron version

27.2.4

### Expected Behavior

The contents of `/usr/lib/electron28/version` should be `28.1.4`.

### Actual Behavior

The contents of `/usr/lib/electron28/version` is `28.1.5`.

### Additional Information

The ZIP file generated by `ninja -C out/Release electron electron_dist_zip` includes a `version` file with the built version. Building it from the 28.1.4 tagged release actually fills in a version file that is one patch release ahead and shows 28.1.5.

I don't know if this is a one-off problem with the last release or it has been in other 28.x releases or what. I do know the current 26.x and 27x. release series identify themselves correctly.

**Comment by MarshallOfSound** [comment]
@alerque The `version` file in our zip's upload to GitHub appear to be correct 🤔 Can you clarify where you are seeing the wrong version number specifically, link to the asset or something?

**Comment by alerque** [comment]
Thanks for checking. I did some spelunking in the Chromium source and found where the template with `$full_version` is getting written, but in the tagged release I don't see any hints how we're getting the wrong version.

The specific case this turns up is in building the Arch Linux package for e28. The package is built by checking out the Git repo at the tag, then eventually building the dist zip ([at L281](https://gitlab.archlinux.org/archlinux/packaging/packages/electron28/-/blob/e7692365de1a5f795b0d2ff392f164383bbe7b18/PKGBUILD#L281)), then shortly thereafter ([at L287](https://gitlab.archlinux.org/archlinux/packaging/packages/electron28/-/blob/e7692365de1a5f795b0d2ff392f164383bbe7b18/PKGBUILD#L287)) the zip is extracted. This package is being rebuilt by a reproducibility daemon and the results are consistent, the version file has the wrong version.

This exact build process with only minor adjustments the same code to handle feature/dependency changes has been used since Electron 22 something and this is the first time we're seeing this.

**Comment by ckerr** [comment]
I'm not sure what the cause is, but there is something funky going on here.

The v28.1.4 and v28.1.5 tags are both pointing at the same commit, 8f902599e47d9b06264c15ca60630802aa3bb5ec :confused: 

https://github.com/electron/electron/commits/v28.1.4
https://github.com/electron/electron/commits/v28.1.5

**Comment by ckerr** [comment]
This seems to have been a tagging issue and has been fixed. Thanks for reporting it!

**Comment by alerque** [comment]
Okay, but the duplicate tags still exist, so it isn't clear what the current release is or what the next one should be. Will v28.1.5 be retagged or will it the next release be v28.1.6 or what? Is the current release be released as v28.1.4 or v28.1.5?
