### ISSUE TITLE
[Bug]: The following error is reported when using yarn to add an electron dependency: RequestError: certificate has expired

### ISSUE THREAD

**Issue by weartist** [electron/electron#41089]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.2.3

### What operating system are you using?

macOS

### Operating System Version

macOS13.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Able to install normally

### Actual Behavior

![image](https://github.com/electron/electron/assets/17105034/a87a6b3c-a445-433a-92c7-7c46ff9f136f)

### Additional Information

The following error is reported when using yarn to add an electron dependency: RequestError: certificate has expired

**Comment by ParryGao** [comment]
I have the save issues

**Comment by linketian** [comment]
I have the same issues

**Comment by felixrieseberg** [comment]
Hello! You are likely using an `npm` mirror. You can confirm whether or not you are using a mirror by running the following command:

```
echo $ELECTRON_MIRROR
```

You might be using https://npm.taobao.org. The certificate for taobao.org has expired. We do not control that mirror and can therefor not fix this error.

To remove the setting, run:

```
unset $ELECTRON_MIRROR
```

For more information and help, I recommed https://github.com/gucong3000/mirror-config-china.

**Comment by qidasheng369** [comment]
I only reported this error when performing yarn in the React source code. The node version is v20.10.0, the react version is 18.2.0, and the Windows version is Windows 11 Professional Workstation Edition, with a 64 bit operating system.
![image](https://github.com/electron/electron/assets/22865380/a49324ac-5811-4dbe-a5e2-80e411656231)

error message
`[4/4] Building fresh packages...
[11/13] ⠐ electron
[7/13] ⠐ gifsicle
[9/13] ⠈ optipng-bin
[-/13] ⠈ waiting...
error E:\web\1.my-demo\2024\2.frame\1.react\react-master\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: E:\web\1.my-demo\2024\2.frame\1.react\react-master\node_modules\electron
Output:
RequestError: certificate has expired
    at ClientRequest.<anonymous> (E:\web\1.my-demo\2024\2.frame\1.react\react-master\node_modules\got\dist\source\core\index.js:970:111)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at origin.emit (E:\web\1.my-demo\2024\2.frame\1.react\react-master\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)`

**Comment by weartist** [comment]
sorry im late, I've fixed the issue, I didn't configure $ELECTRON_MIRROR, but I found that ~/.yarnrc redefines 'electron_mirror' internally, if you run into the same issue, check if the following are reset to other links in turn:

1. $ELECTRON_MIRROR 
2. ~/.npmrc and ‘electron_mirror’
3. ~/.yarnrc and ’electron_mirror'

**Comment by yejimeiming** [comment]
```diff
- electron_mirror="https://registry.npmmirror.com/-/binary/electron/"
+ electron_mirror=https://npmmirror.com/mirrors/electron/
```

**Comment by panmengquan** [comment]
> ```diff
> - electron_mirror="https://registry.npmmirror.com/-/binary/electron/"
> + electron_mirror=https://npmmirror.com/mirrors/electron/
> ```



> ```diff
> - electron_mirror="https://registry.npmmirror.com/-/binary/electron/"
> + electron_mirror=https://npmmirror.com/mirrors/electron/
> ```

it's  resolve my  problem

**Comment by panmengquan** [comment]
I get the same problem ,I resolve it by  npm config set electron_mirror https://npmmirror.com/mirrors/electron/

**Comment by reaishenghuo9264** [comment]
> 我遇到了同样的问题，我通过 npm config set electro_mirror [https://npmmirror.com/mirrors/electron/解决了它](https://npmmirror.com/mirrors/electron/)
有用, 非常感谢!

**Comment by hanzhenfang** [comment]
> I get the same problem ,I resolve it by npm config set electron_mirror https://npmmirror.com/mirrors/electron/

![image](https://github.com/user-attachments/assets/4472a64d-4edc-46bb-a7fe-7ce2193f5a7e)
Tanks!
