### ISSUE TITLE
[Bug]: html5 Fullscreen API requires user interaction

### ISSUE THREAD

**Issue by cpojer** [electron/electron#41090]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

latest

### What operating system are you using?

macOS

### Operating System Version

latest

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Electron can use its native fullscreen behavior without user interaction when a window is created, or it can use the html5 fullscreen API when a user interaction happens in the renderer process, but it cannot fullscreen an app without a user interaction, like onload.

The fullscreen request is instantly denied without even calling the permissions handler. It would be great if Electron bypassed the permissions check and called the default permissions handler even without a user interaction.

In terms of justification, I'd like to stick with using Web APIs and I'm already using the fullscreen API to support various browsers, and adding Electron's native fullscreen API side by side is more complex than just enabling html5 fullscreen on load.

### Actual Behavior

In the renderer process:
```js
document.addEventListener('DOMContentLoaded', () => {
  document.documentElement.requestFullscreen();
});
```

results in this:
![CleanShot 2024-01-24 at 11 33 50@2x](https://github.com/electron/electron/assets/13352/b48b7d95-c3cd-48d8-aaea-bbd930eb6340)

It works when using a `click` event.

**Comment by ckerr** [comment]
This use case is handled by the `userGesture` parameter to `executeJavaScript()`, which was added in https://github.com/electron/electron/pull/2383. Hope this helps!

**Comment by cpojer** [comment]
Oh sweet, thanks so much for the quick response. Might be good to document this somewhere.

**Comment by ckerr** [comment]
> Might be good to document this somewhere.

@cpojer when I go to https://www.electronjs.org/docs/latest/ and type `requestFullscreen` into the search field, this is the first result I get:

https://www.electronjs.org/docs/latest/api/web-frame-main#frameexecutejavascriptcode-usergesture

> In the browser window some HTML APIs like requestFullScreen can only be invoked by a gesture from the user. Setting userGesture to true will remove this limitation.

:smile_cat:
