### ISSUE TITLE
[Bug]: 在electron的13.1.7的版本中使用elementUI的el-table中嵌套el-input-number时会出现el-input-number点击没反应的问题，在单独的vue项目启动后浏览器打开就没有问题，我猜应该是框架的问题

### ISSUE THREAD

**Issue by wang727179528** [electron/electron#41093]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 11 专业版

### What arch are you using?

x64

### Expected Behavior

代码链接 https://codepen.io/wang727179528/pen/BabwaJN

### Actual Behavior

代码链接 https://codepen.io/wang727179528/pen/BabwaJN

**Comment by ckerr** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
