### ISSUE TITLE
[Bug]: "select-serial-port" event handler not cleaned with webContents.session

### ISSUE THREAD

**Issue by leithouse** [electron/electron#41104]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

22.0.4.3 LTS

### What arch are you using?

x64

### Expected Behavior

When a BrowserWindow is closed, it's associated webContents.session should clean up any event handlers for `select-serial-port`.

### Actual Behavior

It does not, resulting in the error `TypeError: One-time callback was called more than once`

### Testcase Gist URL

https://gist.github.com/leithouse/27172b1c8f59175cc01d87e4a7ce77e4

**Comment by jkleinsc** [comment]
This functions as designed.  The event handler is tied to the lifetime of the Session object, not the lifetime of the BrowserWindow.
