### ISSUE TITLE
[Bug]: WebRTC getUserMedia MediaRecorder Memory Leak That Changes Based On Codec

### ISSUE THREAD

**Issue by ProdigyView** [electron/electron#41123]
I am having an issue of what I think is memory leak for when I capture a desktop source and stream it using the MediaRecorder. This happens on both windows and mac and I'm using Electron 28, and how the error manifest changes depending on the codec. The setup is a bit complex but I am to describe it below. It also might be a chromium issue that is similar to this:

https://bugs.chromium.org/p/chromium/issues/detail?id=1174675

### How To Produce

**1. Capture a media** 

We are going to try to capture a desktop source, ie screenshare, at 60 FPS.

```
desktopStream = await navigator.mediaDevices.getUserMedia({
        audio: { mandatory: { chromeMediaSource: 'desktop', chromeMediaSourceId: [some_source_ide], sampleRate: 48000, sampleSize: 16, channelCount: 2 } },
        video: {
          mandatory: {
            chromeMediaSource: 'desktop',
            chromeMediaSourceId: [some_source_id],
            minWidth: 1920,
            maxWidth: 1920,
            minHeight: 1080,
            maxHeight: 1080,
            minFrameRate: 10,
            maxFrameRate: 60
          },
        }
      });
```

**2. Feed Source Into Media Recorder**

```
//high quality stream with vBPS that supports 60 FPS
//Swap our av1 for vp9 or vp8 to test how the error occurs differently
const recorder = new MediaRecorder(desktopStream, { mimeType: 'video/x-matroska; codecs=av1,opus', audioBitsPerSecond: 480000, videoBitsPerSecond: 8000, bitsPerSecond: 8000 });


//Send to Electron main.js
    recoder.ondataavailable = (event) => {

      if (event.data.size > 0) {

        const reader = new FileReader();

        reader.readAsArrayBuffer(event.data);

        reader.onloadend = () => {
          const buffer = Buffer.from(reader.result);;
          ipcRenderer.send('ENCODED_CHUNK', buffer)

          // Clean up the file reader
          reader.onloadend = null; // Remove the onloadend event listener
          reader.abort(); // Abort the reader to release resources
         
          // Clean up resources
          buffer.length = 0;
          reader = null;
        };

      }
    };

    recoder.onstart = (event) => {

    };

    recorder.onstop = (event) => {
      console.log("VP8 and VP9 Error Here, but no error it just stops");
    };

  recoder.onerror = (event) => {
    console.log("av1 Will error out here")
 };

  //Small chunks for quicker processings
   recorder.start(20);
```

**3. On The Main.js for Electron Backend, start a ffmpeg pipe**

```
let ffmpegPipe = null;

//Change ffmpeg path depending on your env
let ffmpegPath = '/usr/bin/ffmpeg'

//A pipe to send the data out too
let randomString = crypto.randomBytes(10).toString('hex');
let inputPipePath = `pipe:${randomString}`;

let command = `${ffmpegPath} -y  -re -i ${inputPipePath}  -c:v libx264 -preset ultrafast 23  -b:v 7000k -maxrate 8000k -bufsize 12000k -pix_fmt yuv420p -tune zerolatency -r ${data.fps} -g 120 -c:a aac -b:a 300k -ac 2 -ar 48000 -af -attempt_recovery 1 -max_recovery_attempts 2 -recover_any_error 1  -f flv "[some_rtmp endpoint]`;

//Have the pipe execute the command
ffmpegPipe = exec(command);
```

**4. Feed the Chunks Into The Pipe**

As the chunks come in from the BrowserWindow, feed them into the pipe.

```
ipcMain.on('ENCODED_CHUNK', (event, buffer) => {

  try {
    if (ffmpegPipe && ffmpegPipe.stdin) {
      ffmpegPipe.stdin.write(buffer);
    } 

  //clean up
  buffer = null;

});
```

The code tries to set everything to null to the garbage collector knows to come get it.

### The Results With AV1 vs VP9/VP8

This code will crash eventually, but it changes when and how depending if the codec is AV1 or VP9/VP8.

#### AV1

With AV1, the crash will occur about every hour, around the hour mark. When it crashes, the MediaRecorder onerror will be called. I've implemented a solution that when this happens, it will restart the start the stream.

#### VP9/VP8

With VP9 or VP8, the crash will occur every 1 and half hours, so it last 30 minutes than AV1. Except when it crashes, its a silent crash, meaning the MediaRecorder onstop function is being called, and it just says the recording has stopped. There is no actual error.

### Memory

In My AV1 solution, because it throws the onerror, I have a function that restarts that restarts everything. What I've noticed in my Task Manager is the memory in my app is constantly climbing. When the app starts, it 400 MB, hour later is 800 MB, 2 hours in is 1200 MB, and it keeps going up on the app commands to a halt and I have restart.

### Chromium Flags

I have tested against several chromium flags.

1. Disable GPU:  
  "--disable-webrtc-hw-decoding",
  "--disable-webrtc-hw-encoding",
  "--disable-yuv-image-decoding",
  "--disable-accelerated-video-decode",
  "--disable-accelerated-video-encode",
  "--disable-accelerated-2d-canvas",
  "--disable-oop-rasterization",
  "--disable-gpu",

2. Enable GPU but disable Acceleteration
 "--gnore-gpu-blocklist",
  "--ignore-gpu-blacklist",
  "--enable-gpu-rasterization",
  "--disable-accelerated-video-decode",
  "--disable-accelerated-video-encode",
  "--disable-accelerated-2d-canvas",
  "--enable-gpu",
  
  3. Enable GPU with Accelerator
  "--ignore-gpu-blocklist",
  "--ignore-gpu-blacklist",
  "--enable-gpu-rasterization",
  "--enable-accelerated-2d-canvas",
  "--enable-accelerated-video-decode",
  "--enable-accelerated-mjpeg-decode",
  "--enable-gpu",
  "--enable-webgl",

4. No flags at all, just run the system as is

All variation produce the same results, with or without gpu and/or acceleration. Any ideas on what can be up?

**Comment by MaikonPanazzolo** [comment]
I'm having this trouble too, any update?

**Comment by YoGoUrT20** [comment]
bump
