### ISSUE TITLE
[Bug]: Uncaught SyntaxError bootstrap.bundle.min.js:6 - Bootstrap 5 js file won't load with Electron 

### ISSUE THREAD

**Issue by privatekenny** [electron/electron#41126]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19044

### What arch are you using?

x64

### Expected Behavior

**Given** i've imported jquery, bootstrap.bundle.min.js & bootstrap.min.css scripts inside my html file
**When** I use components from bootstrap 5.3.1 such as the accordion dropdown
**Then** I expect the dropdown to open when I click it

bootstrap.bundle.js script should load correctly without any exception

### Actual Behavior

When starting the electron app with bootstrap 5, none of the components behave as expected.

The developer tool throws this error: 
**`bootstrap.bundle.min.js:6 Uncaught SyntaxError: Unexpected token ...`** 

- I have nodeIntegration enabled in the main.js
- I have the bootstrap.bundle.min.js at the end of the body tag
- Everything works fine when starting the app as webapp instead of electron
- Bootstrap 4 works and does not throw this exception

### Additional Information

This seems to be different than all the other issues regarding Jquery not loading.

**Comment by privatekenny** [comment]
I've imported the scripts into my html file like this.

<script src="../static/js/jquery.min.js"></script>
<script src="../static/js/bootstrap.bundle.min.js"></script>

**Comment by privatekenny** [comment]
> Hello @privatekenny. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the [ blocked/need-repro](https://github.com/electron/electron/labels/blocked%2Fneed-repro) Needs a test case to reproduce the bug label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

Here are the files
https://gist.github.com/privatekenny/500bd5f691a935eb1f98b0b851028123

**Comment by ckerr** [comment]
> Electron Version
> 28.0.0
>
> Last Known Working Electron version
> 28.0.0


@privatekenny I'm confused by this part of the report. It can't be working and broken in the same version! :smile: 

Was this working in 27?

**Comment by privatekenny** [comment]
> > Electron Version
> > 28.0.0
> > Last Known Working Electron version
> > 28.0.0
> 
> @privatekenny I'm confused by this part of the report. It can't be working and broken in the same version! 😄
> 
> Was this working in 27?

Let me remove that that. I’m unsure of last known working version.

**Comment by adwyali99** [comment]
[](url)

**Comment by codebytere** [comment]
@privatekenny your repro did not run as is, but after i made the following changes:

```
Desktop ❯ diff one.html two.html                                                   2:02PM
8,9c8,9
<   <script src="../color-modes.js"></script>
<   <link href="../sidebars.css" rel="stylesheet">
---
>   <script src="./color-modes.js"></script>
>   <link href="./sidebar.css" rel="stylesheet">
281c281
<     <script src="../sidebars.js"></script>
---
>     <script src="./sidebar.js"></script>
```

it worked just fine:

![bootstrap](https://github.com/electron/electron/assets/2036040/21b52a70-4509-458e-9acd-30d803511289)
