### ISSUE TITLE
[Bug]: "fatal error: 'xlocinfo.h' file not found" when runnin "ninja -C out/Release electron"

### ISSUE THREAD

**Issue by ssrdop** [electron/electron#41170]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.1.5

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

28.2.0

### Expected Behavior

running "ninja -C out/Release electron" with no errors.

### Actual Behavior

I want to build electron with verions 13.1.5, not latest.
Using this docs "https://www.electronjs.org/docs/latest/development/build-instructions-gn" my steps are: 
1)  Succesfully download code with command "gclient sync --with_branch_heads --with_tags"
2)  Going to /src/electron i run "git checkout v13.1.5". Then go back to ../
3)  Running "gclient sync --with_branch_heads --with_tags -f -D"
4)  Creating all enviroment variables
5) Succesfully running "gn gen out/Release --args="import(\"//electron/build/args/release.gn\")" and get "done" message.

So 6 step is running "ninja -C out/Testing electron". When i run it i get message:
   "depot_tools/ninja.py: Could not find Ninja in the third_party of the current project, nor in your PATH.
  Please take one of the following actions to install Ninja:
  - If your project has DEPS, add a CIPD Ninja dependency to DEPS.
  - Otherwise, add Ninja to your PATH *after* depot_tools."

I dont understand why it cant find ninja, because when i do same steps with latest electron version it running perfect.

Ok i download ninja.exe file from internet and running : "E:\work\electromain\ninja-win\ninja.exe -C out/Release electron"
It starts to build, but after near 40 actions i get errors:

 CXX obj/buildtools/third_party/libc++/libc++/locale.obj
FAILED: obj/buildtools/third_party/libc++/libc++/locale.obj
 ...
In file included from ../../buildtools/third_party/libc++/trunk/src/locale.cpp:16:
In file included from ../../buildtools/third_party/libc++/trunk/include\locale:191:
In file included from ../../buildtools/third_party/libc++/trunk/include\__locale:24:
../../buildtools/third_party/libc++/trunk/include\__support/win32/locale_win32.h(15,10): fatal error: 'xlocinfo.h' file not found

Why it cant find 'xlocinfo.h'. When i do the same with latest electron version i am succesfull with it.

Why the same steps work with latest electron version and not working with specified version?

### Additional Information

Electron v13.1.5 was published at june 2021. I even tried to checkout depot_tools to closest jule 2021 version. But same steps fail.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
