### ISSUE TITLE
[Bug]: [linux] Cannot use client certificates protected by password

### ISSUE THREAD

**Issue by arenevier** [electron/electron#41188]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

linux

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

See actual Behavior for description of the issue.

### Actual Behavior

Support for client certificate store is implemented in [ElectronBrowserClient::CreateClientCertStore](https://github.com/electron/electron/blob/main/shell/browser/electron_browser_client.cc#L783). On linux, a password delegate factory must be passed. Electron passes a null factory, so the password delegate will be null. When nss requires a password, the null password delegate means that it is not possible to prompt the user for a password, and the request will fail.

So currently, it's not possible to connect to mTLS websites on linux if the certificate is stored on a yubikey or a card reader that requires a pin.

**Comment by codebytere** [comment]
Electron v27 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

**Comment by arenevier** [comment]
The electron version number was auto filled. I don't know what is the current version. 

 The issue is present on all versions I believe. 

I have checked the current main branch on GitHub.

**Comment by mlaurencin** [comment]
@arenevier Since you closed the pull request related to this issue, is this still an active problem for you or has it been resolved?

I am keeping the `blocked/need-info` label in place for this reason. If there is no response in 10 days the issue will be closed.

**Comment by arenevier** [comment]
@mlaurencin : I closed the pull request by accident. Thanks for the notice.
