### ISSUE TITLE
[Bug]: How Do I Resolve the Crash Caused by CancelActiveAndPendingDialogs?

### ISSUE THREAD

**Issue by JiaFuGuo** [electron/electron#41208]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.26

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

ia32

### Expected Behavior

I don't know what the cause of the crash is and how to solve or avoid it.

### Actual Behavior

Crash dump info：
0:000> .ecxr
*** WARNING: Unable to verify timestamp for WeLink.exe
eax=efefefef ebx=ffffffff ecx=31ba5c00 edx=00000000 esi=31ba5c00 edi=3179fb90
eip=021db3b2 esp=0f6eeb60 ebp=0f6eebc8 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210206
WeLink!content::WebContentsImpl::CancelActiveAndPendingDialogs+0xd2:
021db3b2 8b480c          mov     ecx,dword ptr [eax+0Ch] ds:002b:efefeffb=????????
0:000> kb
  *** Stack trace for last set context - .thread/.cxr resets it
electron!content::WebContentsImpl::CancelActiveAndPendingDialogs+0xd2 [C:\projects\src\content\browser\web_contents\web_contents_impl.cc @ 1546] 
electron!content::WebContentsImpl::DidNavigateAnyFramePostCommit+0xfd [C:\projects\src\content\browser\web_contents\web_contents_impl.cc @ 5957] 
electron!content::Navigator::DidNavigate+0xb21 [C:\projects\src\content\browser\renderer_host\navigator.cc @ 689] 
electron!content::RenderFrameHostImpl::DidCommitNavigationInternal+0x3b1 [C:\projects\src\content\browser\renderer_host\render_frame_host_impl.cc @ 12069] 
electron!content::RenderFrameHostImpl::DidCommitNavigation+0x11b [C:\projects\src\content\browser\renderer_host\render_frame_host_impl.cc @ 12665] 
electron!base::internal::FunctorTraits<void (content::RenderFrameHostImpl::*)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) __attribute__((thiscall)),void>::Invoke<void (content::RenderFrameHostImpl::*)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) __attribute__((thiscall)),content::RenderFrameHostImpl *,content::NavigationRequest *,mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>,mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams> >+0x4c [C:\projects\src\base\functional\bind_internal.h @ 647] 
electron!base::internal::InvokeHelper<0,void,0,1>::MakeItSo+0x54 [C:\projects\src\base\functional\bind_internal.h @ 826] 
electron!base::internal::Invoker<base::internal::BindState<void (content::RenderFrameHostImpl::*)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) __attribute__((thiscall)),base::internal::UnretainedWrapper<content::RenderFrameHostImpl,base::RawPtrBanDanglingIfSupported>,base::internal::UnretainedWrapper<content::NavigationRequest,base::RawPtrBanDanglingIfSupported> >,void (mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>)>::RunImpl+0x54 [C:\projects\src\base\functional\bind_internal.h @ 920] 
electron!base::internal::Invoker<base::internal::BindState<void (content::RenderFrameHostImpl::*)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) __attribute__((thiscall)),base::internal::UnretainedWrapper<content::RenderFrameHostImpl,base::RawPtrBanDanglingIfSupported>,base::internal::UnretainedWrapper<content::NavigationRequest,base::RawPtrBanDanglingIfSupported> >,void (mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>)>::RunOnce+0x6d [C:\projects\src\base\functional\bind_internal.h @ 871] 
electron!base::OnceCallback<void (mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>)>::Run+0x19 [C:\projects\src\base\functional\callback.h @ 145] 
electron!content::mojom::NavigationClient_CommitNavigation_ForwardToCallback::Accept+0xd9 [C:\projects\src\out\Default\gen\content\common\navigation_client.mojom.cc @ 1125] 
electron!mojo::InterfaceEndpointClient::HandleValidatedMessage+0x3d5 [C:\projects\src\mojo\public\cpp\bindings\lib\interface_endpoint_client.cc @ 989] 
electron!mojo::MessageDispatcher::Accept+0x6e [C:\projects\src\mojo\public\cpp\bindings\lib\message_dispatcher.cc @ 43] 
electron!mojo::InterfaceEndpointClient::HandleIncomingMessage+0x32 [C:\projects\src\mojo\public\cpp\bindings\lib\interface_endpoint_client.cc @ 693] 
electron!IPC::`anonymous namespace'::ChannelAssociatedGroupController::AcceptOnEndpointThread+0xd8 [C:\projects\src\ipc\ipc_mojo_bootstrap.cc @ 1083] 
electron!base::internal::FunctorTraits<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message) __attribute__((thiscall)),void>::Invoke<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message) __attribute__((thiscall)),scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController>,mojo::Message>+0x14e [C:\projects\src\base\functional\bind_internal.h @ 647] 
electron!base::internal::InvokeHelper<0,void,0,1>::MakeItSo+0x1e [C:\projects\src\base\functional\bind_internal.h @ 826] 
electron!base::internal::Invoker<base::internal::BindState<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message) __attribute__((thiscall)),scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController>,mojo::Message>,void ()>::RunImpl+0x1e [C:\projects\src\base\functional\bind_internal.h @ 920] 
electron!base::internal::Invoker<base::internal::BindState<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message) __attribute__((thiscall)),scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController>,mojo::Message>,void ()>::RunOnce+0x36 [C:\projects\src\base\functional\bind_internal.h @ 871] 
electron!base::OnceCallback<void ()>::Run+0x17 [C:\projects\src\base\functional\callback.h @ 145] 
electron!base::TaskAnnotator::RunTaskImpl+0xe2 [C:\projects\src\base\task\common\task_annotator.cc @ 134] 
electron!base::TaskAnnotator::RunTask+0x19 [C:\projects\src\base\task\common\task_annotator.h @ 72] 
electron!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl+0x3fc [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 441] 
electron!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork+0x494 [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 297] 
electron!base::MessagePumpForUI::DoRunLoop+0x162 [C:\projects\src\base\message_loop\message_pump_win.cc @ 214] 
electron!base::MessagePumpWin::Run+0x6c [C:\projects\src\base\message_loop\message_pump_win.cc @ 79] 
electron!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run+0xf0 [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 603] 
electron!base::RunLoop::Run+0xdc [C:\projects\src\base\run_loop.cc @ 141] 
electron!content::BrowserMainLoop::RunMainMessageLoop+0x79 [C:\projects\src\content\browser\browser_main_loop.cc @ 1050] 
electron!content::BrowserMainRunnerImpl::Run+0xe [C:\projects\src\content\browser\browser_main_runner_impl.cc @ 163] 
electron!content::BrowserMain+0xa1 [C:\projects\src\content\browser\browser_main.cc @ 30] 
electron!content::RunBrowserProcessMain+0xb6 [C:\projects\src\content\app\content_main_runner_impl.cc @ 716] 
electron!content::ContentMainRunnerImpl::RunBrowser+0x4f1 [C:\projects\src\content\app\content_main_runner_impl.cc @ 1257] 
electron!content::ContentMainRunnerImpl::Run+0x30e [C:\projects\src\content\app\content_main_runner_impl.cc @ 1116] 
electron!content::RunContentProcess+0x552 [C:\projects\src\content\app\content_main.cc @ 346] 
electron!content::ContentMain+0x58 [C:\projects\src\content\app\content_main.cc @ 374] 
24 0f6efc84 01096911     00f80000 00000000 00000000 electron!wWinMain+0x3a4 [C:\projects\src\electron\shell\app\electron_main_win.cc @ 244] 
25 0f6efca0 77147b87     00adfdc0 e06956d9 00000000 electron!FiberBinder+0x11 [C:\projects\src\electron\shell\app\electron_main_win.cc @ 81] 
26 0f6efcd8 77147b36     ffffffff 77ab92b9 00000000 KERNELBASE!_BaseFiberStart+0x49
27 0f6efce8 77a96517     00000000 00000000 00000000 KERNELBASE!BaseFiberStart+0x16
28 0f6efcf0 00000000     00000000 00000000 00000000 ntdll!RtlUserFiberStart+0x17

**Comment by JiaFuGuo** [comment]
> Hello @JiaFuGuo. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the [ blocked/need-repro](https://github.com/electron/electron/labels/blocked%2Fneed-repro) Needs a test case to reproduce the bug label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

Thank you for your answer. I don't know how this problem happened before. I don't have steps to reproduce it. I caught it from other users through crashReporter. Can you give me some clues or ideas to troubleshoot? It looks like closing the window that is opening? Or when the CancelActiveAndPendingDialogs function is called?

**Comment by mlaurencin** [comment]
@JiaFuGuo Unfortunately, the version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/latest/tutorial/electron-timelines). In addition, it is not feasible to triage this crash without knowing how it was triggered.

I would encourage you to look explore [the project's Community page](https://www.electronjs.org/community) -- in particular, [the Electron Discord server](https://discord.com/invite/electron) to see if anyone has run into a similar issue.

If you are able to recreate the crash on a supported version, please feel free to make a new bug report including the reproduction steps and the crash dump.

I hope this helps!
