### ISSUE TITLE
[Bug]: `-webkit-app-region: drag` still doesn't works after #41030

### ISSUE THREAD

**Issue by JellyBrick** [electron/electron#41212]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0.0-beta.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 (22631)

### What arch are you using?

x64

### Last Known Working Electron version

29.0.0-alpha.7

### Expected Behavior

If `-webkit-app-region: drag` was used, it should be possible to click on the region and drag the `Window`. 

### Actual Behavior

It will behave as if the property is not applied.

### Testcase Gist URL

https://gist.github.com/JellyBrick/ec1ef4b79d55bc8a46fcdcd289259996

### Additional Information

In this case (gist), `YouTube` internally overrides the browser's events (like `MouseEvent`, `Event`, etc), which seems to cause `-webkit-app-region: drag` to be ignored. (Until `29.0.0-alpha.7`, `-webkit-app-region: drag` was not ignored and worked fine)

- Related to #40985

**Comment by JellyBrick** [comment]
cc @deepak1556
https://github.com/electron/electron/issues/40985#issuecomment-1918762765

**Comment by VerteDinde** [comment]
Bisected this down to http://crrev.com/c/4814003 - this is a side effect from Chrome only collecting app regions for apps using the Window Controls Overlay or borderless apps
