### ISSUE TITLE
[Bug]: Body scrollbars cannot be hidden with webkit-scrollbar display:none

### ISSUE THREAD

**Issue by uffou** [electron/electron#41218]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.1

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.2.1

### What arch are you using?

x64

### Last Known Working Electron version

25.9.8

### Expected Behavior

Using 
```css
body::-webkit-scrollbar {
    display: none;
}
```
Should hide the body scrollbars but preserve scrolling capabilities

### Actual Behavior

Body scrollbars remain visible even after the style to hide them is applied 
![image](https://github.com/electron/electron/assets/2581788/6ceb2220-4057-46ca-b5d4-4c2fc8d26d09)

### Additional Information

The problem does not exist on Electron 25.9.8 and older versions.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
