### ISSUE TITLE
[Bug]: Why can't I use ipcRenderer.on in BrowserView

### ISSUE THREAD

**Issue by yao-xk** [electron/electron#41219]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Windows

### Operating System Version

win11

### What arch are you using?

x64

### Expected Behavior

ipcRenderer.on can work in BrowserView

### no error

![20240202211904](https://github.com/electron/electron/assets/118623516/6ca4ce6f-834c-4331-b764-fe16042eded9)

**Comment by yao-xk** [comment]
### iframe.value's content

**Comment by yao-xk** [comment]
### the content of iframe.vue

**Comment by yao-xk** [comment]
### the content of iframe.vue

![image](https://github.com/electron/electron/assets/118623516/d41697e5-e002-4ebe-ad79-dc6089dd94cf)

Thanks for answering questions

**Comment by MiaoWenDa** [comment]
这个问题解决了吗，大佬
