### ISSUE TITLE
[Bug]:  When BrowserView loadURL, it will automatically switch the main window from the background to the foreground. How to solve this problem?

### ISSUE THREAD

**Issue by axeryu** [electron/electron#41217]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

macOS

### Operating System Version

MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

keep origin status

### Actual Behavior

 it will automatically switch the main window from the background to the foreground.

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

Additionally, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

If you’re still experiencing this issue in Electron 26.x.y or later, please add a comment with steps to reproduce the issue, specify the version you’re testing with, and include any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for these above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
