### ISSUE TITLE
[Bug]: Could not locate the bindings file

### ISSUE THREAD

**Issue by Supamiu** [electron/electron#41234]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 Build 22631.3007

### What arch are you using?

x64

### Last Known Working Electron version

27.3.1

### Expected Behavior

My app should be able to locate bindings for a lib that has been working for years until 28.0.0.

### Actual Behavior

The bindings can not be found starting with 28.0.0.

### Additional Information

The app is here: https://github.com/ffxiv-teamcraft/ffxiv-teamcraft and the bug can be tested by running `yarn electron:start` on it with `electron`'s version set to 28.0.0 in the package.json file, then running `yarn` to install dependencies and rebuild everything. IF everything works fine, the app just starts (since you didn't biuld the frontend part, it'll probably throw an error about index.html not found, in that case, run `yarn build:electron-dev` to generate the assets.

I'm using Node 18.18.2 and I tested again with 27.3.1, it's working like a charm. I tried looking through changelog toi see what could have caused that and I can't figure out what it can be.

The bindings it's trying to load are from https://github.com/Supamiu/dll-inject which is required as dependency.

**Comment by Supamiu** [comment]
I tried to update my bindings call to provide module root: 
https://github.com/Supamiu/dll-inject/commit/1229993b814fb2fbe8b8dcc6bf17392022ed79ee

But I'm getting the same error.

**Comment by Supamiu** [comment]
Updating to `node-gyp@10.0.1` and `nan@2.18.0` did the trick along with the above change to the bindings call, closing this issue.

**Comment by Supamiu** [comment]
Reopening because I was wrong, the issue isn't fixed with these changes.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
