### ISSUE TITLE
[Bug]: There's no visibilitychange event when backgroundThrottling disabled

### ISSUE THREAD

**Issue by beyondkmp** [electron/electron#41233]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.2.0

### What operating system are you using?

Windows

### Operating System Version

windows11

### What arch are you using?

x64

### Last Known Working Electron version

electron23

### Expected Behavior

The web can monitor the 'visibilitychange' event.

```javascript
document.addEventListener( 'visibilitychange' , function() {
    if (document.hidden) {
        console.log('bye');
    } else {
        console.log('well back');
    }
}, false );
```

### Actual Behavior

The web can  not monitor the 'visibilitychange' event

### Additional Information

This bug is caused by this https://github.com/electron/electron/pull/39223.

In my current code, I need to set `backgroundThrottling` to `false`, and I also need to listen for 'visibilitychange' in the web to get the document's occluded state. After this change, the web can no longer directly listen to the 'visibilitychange' event. 

@codebytere  Currently, I haven't found an alternative event. Do you have any recommendations?

You are adding a api to check if the window is occluded in https://github.com/electron/electron/pull/38982. But this only has a detection function and no corresponding event to listen to. Can we add an 'occluded' event?

**Comment by codebytere** [comment]
This is the [expected and documented behavior](https://github.com/electron/electron/blob/15c60143241c7d0335f3bc8c722054ce6b8a9481/docs/api/browser-window.md#L128-L129), which https://github.com/electron/electron/pull/39223 fixed.
