### ISSUE TITLE
[Bug]: Electron apps always use dgpu on wayland with --ozone-platform=wayland flag

### ISSUE THREAD

**Issue by vsantalov** [electron/electron#41232]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.2.3

### What operating system are you using?

Other Linux

### Operating System Version

fedora 39

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

When using any electron app with the flag --ozone-platform=wayland, it should default to igpu, or at least provide an option to select a video card

### Actual Behavior

When starting any electron app with the --ozone-platform=wayland (must-have for gnome fractional scaling), it will use the dgpu with no way to force it to use the igpu, so apps like slack and vscode will kill the battery in a couple of hours. I tried different flags, the only "fix" is to disable hardware acceleration but then heavy apps like vscode become unusable.
```--force_low_power_gpu``` does nothing, also tried it with ```--enable-logging```

### Additional Information

Optimus laptop with dual 680m/RX6800s AMD video cards in hybrid mode

**Comment by mlaurencin** [comment]
@vsantalov How does Chromium behave regarding this? Is there anything in Chromium that supports this type of gpu selection?

**Comment by vsantalov** [comment]
> @vsantalov How does Chromium behave regarding this? Is there anything in Chromium that supports this type of gpu selection?

Chromium behaves the same way. With the ```--ozone-platform=wayland``` flag it will only use dgu and the ```--force_low_power_gpu=1``` does not do anything. I can find very little information on ```--force_low_power_gpu```. Based on what I have seen so far, it might be a workaround flag for macbooks only.

Does it mean this is an upstream bug and we should close the issue?

**Comment by mlaurencin** [comment]
Correct, we should close this issue. An enhancement such as this would be best brought upstream first.
