### ISSUE TITLE
[Bug]:  "jsHeapSizeLimit" will not change after "--max-old-space-size" is set

### ISSUE THREAD

**Issue by code997** [electron/electron#41248]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.9

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

ia32

### Last Known Working Electron version

16.0.9

### Expected Behavior

I hope to increase the memory limit of v8 to reduce oom crashes by setting --max-old-space-size in the main process. Although I know that pointer compression is enabled in this version, the maximum limit is 4GB, but I set it to less than 4GB. The value is still invalid.

I have tried setting it like this：
`
"dev": "set NODE_OPTIONS=--max-old-space-size=2048&&node ./scripts/dev.js",
`
`
app.commandLine.appendSwitch('js-flags', '--max-old-space-size=2048');
`
`
app.commandLine.appendSwitch('js-flags', '--max_old_space_size=2048');
`
`
require('v8').setFlagsFromString('--max-old-space-size=2048');
`
`
require('v8').setFlagsFromString('--max_old_space_size=2048');
`

None of them have any effect. Even if I only set 500M, it still does not take effect. Is there something wrong with my settings? I hope you can get an answer. Thank you.

### Actual Behavior

The maximum stack memory limit my render process gets is still 1136000000
<img width="244" alt="temp" src="https://github.com/electron/electron/assets/19968960/b9b2bdbf-15eb-42a6-ab25-bc612b0f0a8d">

**Comment by codebytere** [comment]
Electron v16.0.9 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

**Comment by code997** [comment]
I have found the reason. It cannot be set because other attributes are set. I can just remove these two attributes in the project.
`app.commandLine.appendSwitch('js-flags', '--expose_gc');`
`app.commandLine.appendSwitch('js-flags', '--max-semi-space-size=64');`

It is not necessary whether different Electron versions delete these two attributes.

**Comment by codebytere** [comment]
Closing in light of above comment.
