### ISSUE TITLE
[Feature Request]: Provide native way to query hidden state of BrowserWindow.

### ISSUE THREAD

**Issue by neobyteUK** [electron/electron#41270]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I can call .show() and .hide() on a BrowserWindow, but cannot query the current state. The closest option appears to be isVisible(), but that returns false if a window is minimised or behind another window, and so is not a reliable indicator of whether a window is currently not visible due to a call to .hide(). There does not appear to be a native way to query a BrowserWindow to determine whether it has been exposed to the OS UI at all via .show() and .hide().

### Proposed Solution

Provide a function isHidden() that exposes the internal hide/show state.

### Alternatives Considered

I am unaware of a workaround for this other than maintaining a local service that tracks the hidden state of each window, but this feels like something the framework should provide by default.

Combining isVisible() with isMinimized() gets you part of the way there, but doesn't handle the scenario where the window is just currently behind another window.

**Comment by Prinzhorn** [comment]
My first search https://github.com/search?q=repo%3Aelectron%2Felectron+BrowserWindow+show+hide+ishidden&type=issues yields:

https://github.com/electron/electron/pull/41010
https://github.com/electron/electron/issues/30485

**Comment by neobyteUK** [comment]
Clearly I used the wrong terms to search by. Apologies.
