### ISSUE TITLE
[Bug]: win.focus() activates an inactive panel.

### ISSUE THREAD

**Issue by YongzeYao** [electron/electron#41273]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.8.1

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.3

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

1. create window with `type: "panel"`
2. show window with `showInactive()`
3. focus window with `win.focus()`

`win.focus()` should focus on the panel but not activate the app.

### Actual Behavior

`win.focus()` activates the app.

**Comment by YongzeYao** [comment]
https://gist.github.com/YongzeYao/f2d172d47d3627824805230edc22a9aa

**Comment by clavin** [comment]
I've been seeing many reports of this, so I trust that this report is true, but I haven't had the time to repro it myself.

After digging in, I suspect the problem could be that our [`IsPanel` check](https://github.com/electron/electron/blob/38850112200a8fa5e17c7c393b409bb33a747f9a/shell/browser/native_window_mac.mm#L121) only checks to see if the passed in window inherits from `NSPanel`, whereas [our panel window implementation](https://github.com/electron/electron/blob/38850112200a8fa5e17c7c393b409bb33a747f9a/shell/browser/ui/cocoa/electron_ns_panel.h#L10) doesn't inherit from `NSPanel` as far as I can tell. This check was added as part of #40570.

**Comment by YongzeYao** [comment]
@clavin  Hey Calvin, is there any plan to fix this issue? It is very important to certain kinds of utility apps.
