### ISSUE TITLE
[Bug]: Electron BrowserView instance not properly cleared on window.close()

### ISSUE THREAD

**Issue by janschmutz** [electron/electron#41289]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.1.1

### What arch are you using?

x64

### Expected Behavior

window.close() inside the BrowserView should remove the BrowserView entirely and destroy the webContents

### Actual Behavior

"destroyed" event fires but BrowserView instance is still visible and blocks screen.

### Testcase Gist URL

https://gist.github.com/janschmutz/46c795efae620ae7fd35f2011dda0aed

### Additional Information

If a website inside a browserView calls `window.close()` the browserView should be completely cleared, but there remains a empty BrowserView that cannot be deleted or hidden. Additionally if `sandbox: false` the entire app closes.
To emulate this you can simply execute `window.close()` in the browser console of the small electron fiddle I attached.

**This only happens for the macOS version**. Windows works as expected.

related:
https://github.com/electron/electron/issues/28260
https://github.com/electron/electron/issues/28260

**Comment by codebytere** [comment]
Fixed by https://github.com/electron/electron/pull/35658

**Comment by janschmutz** [comment]
@codebytere how is this fixed if it happens for the latest version of electron? Gist is attached

**Comment by codebytere** [comment]
Issues are closed as fixed when the PR associated with them is merged. That has been our policy for the entirety of the project's existence.
