### ISSUE TITLE
[Bug]: loadURL is failing to load large string urls

### ISSUE THREAD

**Issue by gmishramdsol** [electron/electron#41286]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.1.9

### What operating system are you using?

macOS

### Operating System Version

macOS ventura

### What arch are you using?

x64

### Expected Behavior

const blob = new Blob([global.viewRecordInfo.ccda], {type: 'text/html'});
const objectURL = URL.createObjectURL(blob);
loadURL(objectURL) 
OPening a html file as blob in a new browser window is not working with larger files (2.5 MB fails) and 1.5 MB works
The above code is not working when blob size is 2.5mb and works for lesser size files like in Kbs and also worked for a 1.5 mb file

### Actual Behavior

Expected to work with 2.5 MB file. Not able to find any documentation on the size limits

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

If you’re still experiencing this issue in Electron 26.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
