### ISSUE TITLE
[Bug]: Native Node Modules in Win 32 bit build got error in Electron 28+

### ISSUE THREAD

**Issue by avivsalman** [electron/electron#41293]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

27

### Expected Behavior

Build of 32 bit will work

### Actual Behavior

after upgrading from electron 27 to 28, i am trying to build dependencies with electron-builder, for 64 bit architecture its success, in 32 bit its failed.

Build of 32 bit got an error:
npm ERR! node_printer.cc
npm ERR! C:\Users\AvivSalman\.electron-gyp\28.2.2\include\node\v8-typed-array.h(30,70): warning C4003: not enough arguments for function-like macro invocation 'max' [C:\projects\test\node_modules\@thiagoelg\node-printer\build\node_printer.vcxproj]
npm ERR!   (compiling source file '../src/node_printer.cc')

<img width="1007" alt="image" src="https://github.com/electron/electron/assets/31519121/9c6dac72-7f36-4358-889d-306960a877d1">

**Comment by mlaurencin** [comment]
As this is an error occurring while running electron-builder, you will want to report it in [their issue tracker](https://github.com/electron-userland/electron-builder/issues) rather than here.
