### ISSUE TITLE
[Bug]: canGoForward has invalid value after goForward() with did-fail-load event

### ISSUE THREAD

**Issue by panther7** [electron/electron#41294]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.2  
29.0.0-beta.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Expected Behavior

Expected `canGoForward : false` after `goForward()` to latest page.

#### log

```
did-navigate 200 OK index.html
canGoBack false
canGoForward false

-------
did-fail-load -310 ERR_TOO_MANY_REDIRECTS https://httpbin.org/relative-redirect/*
canGoBack true
canGoForward false

goBack()
-------
did-navigate 200 OK index.html
canGoBack false
canGoForward true

goForward()
-------
did-fail-load -310 ERR_TOO_MANY_REDIRECTS https://httpbin.org/relative-redirect/*
canGoBack true
canGoForward false
```

### Actual Behavior

Actual `canGoForward : true` after `goForward()` to latest page.

#### log

```
did-navigate 200 OK index.html
canGoBack false
canGoForward false

-------
did-fail-load -310 ERR_TOO_MANY_REDIRECTS https://httpbin.org/relative-redirect/*
canGoBack true
canGoForward false

goBack()
-------
did-navigate 200 OK index.html
canGoBack false
canGoForward true

goForward()
-------
did-fail-load -310 ERR_TOO_MANY_REDIRECTS https://httpbin.org/relative-redirect/*
canGoBack false
canGoForward true
```

### Additional Information

If webContents go to failing URL via `goForward()`, than `canGoBack`/`canGoForward` is not modified.

It is broken on `ERR_TOO_MANY_REDIRECTS`. Probably is broken for all `did-fail-load` events.

### main.js (Electron Fiddle):

```ts
const { app, BrowserWindow } = require('electron')

async function delay (wait = 0) {
  return new Promise((r) => setTimeout(r, wait));
}

async function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  })

  function log (name, ...args) {
    console.log('-------');
    console.log(name, ...args);
    console.log('canGoBack', mainWindow.webContents.canGoBack());
    console.log('canGoForward', mainWindow.webContents.canGoForward());
    console.log();
  }

  mainWindow.webContents.on('did-fail-load', (_event, code, desc, url) => {
    log('did-fail-load', code, desc, url);
  });

  mainWindow.webContents.on('did-navigate', (_event, url, code, desc) => {
    log('did-navigate', code, desc, url)
  });

  // TEST ->
  await delay(500);
  mainWindow.webContents.loadURL(`file:///${__dirname}/index.html`);

  await delay(500);
  mainWindow.webContents.loadURL('https://httpbin.org/redirect/100');

  await delay(5000);
  console.log('goBack()');
  mainWindow.webContents.goBack();

  await delay(500);
  console.log('goForward()');
  mainWindow.webContents.goForward();
  // <- TEST
}


app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

**Comment by mlaurencin** [comment]
Here is a [link](https://gist.github.com/mlaurencin/311689978c2ef249c25d37dea7d39b87) to a gist with the contents of the main.js originally provided.

**Comment by codebytere** [comment]
@panther7 these functions are directly delegated to Chromium's [`NavigationControllerImpl`](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/navigation_controller_impl.cc) methods: [`CanGoBack`](https://github.com/electron/electron/blob/cee51785e1ed057fa5c78b2fc7bb1e8a5b91053d/shell/browser/api/electron_api_web_contents.cc#L2523) and [`CanGoForward`](https://github.com/electron/electron/blob/cee51785e1ed057fa5c78b2fc7bb1e8a5b91053d/shell/browser/api/electron_api_web_contents.cc#L2532). I suggest opening a bug upstream with Chromium if you'd like them to consider changing their implementation.

**Comment by panther7** [comment]
@codebytere  s possible, that problem is in 'did-fail-load'?
