### ISSUE TITLE
[Feature Request]: Ability to force network adapter

### ISSUE THREAD

**Issue by jrj2211** [electron/electron#41291]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

From my understanding, Chrome has broken the ability to use something like ForceBindIP by moving code out of DLLs making its DLL injection not work.

For testing/development, I often run several electron applications on a single computer, but need them all to use their own virtual network adapter (or additional USB ethernet dongles).

On older versions of electron this worked fine, but upgrading our legacy apps to newer versions means I can't use forcebindip.

I'd love the ability to specify the network adapter to use for its connection.

### Proposed Solution

API to change which network adapter electron sends network data over.

### Alternatives Considered

At this point, the only alternative is to spin up virtual machines as other solutions like ForceBindIP no longer work. 

### Additional Information

Since this project modifies chromium, I'm curious the feasibility of this.

This might also be better requested as a direct feature of chromium, such as adding a command line switch such as `--network-adapter=192.168.2.10`

I also totally understand this is an obscure request that probably would have a niche user base but wanted to at least throw it out there.

**Comment by codebytere** [comment]
@jrj2211 It'd require patching Chromium, which we're open to doing in [certain circumstances](https://github.com/electron/electron/blob/43dbd1bdf8a48d798f4e392f921bde81a3430f4b/docs/development/patches.md#L5-L13). For this feature - the most effective way to get some forward momentum imo is to file a bug upstream at crbug.com. If they say it's a no-go, we can consider re-opening this and pursuing other options :)
