### ISSUE TITLE
How to get Chromium to not deactivate the tab when inactive for 5 minutes programmatically in an Electron app?

### ISSUE THREAD

**Issue by ssaputo** [electron/electron#41315]
I have a LitElement single-page Electron application with a C#/.NET back-end running a Kestrel server that requests data from an external machine and returns a result that could include measurement data, informational data, etc. This request for data loops until the user stops the process of looping via a button. The users started complaining that the output on the page stops updating with new values after roughly 5 minutes of inactivity.

I discovered that at some point, Chromium added a memory management feature that disables tabs when they are inactive for roughly 5 minutes or so (unclear on the exact time). As long as some user activity occurs (e.g., mouse movement, etc.), this reactivates the tab which results in new data being updated on the page.

I am looking to see how to disable this memory management feature for tabs programmatically through Electron.

Versions: LitElement v2.5.1 Electron v23.3.12 .NET 7

Any help would be greatly appreciated.

**Things that I tried:**

**Electron app:**
In main.js, I added this line of code:

` app.commandLine.appendSwitch('disable-features', 'TabSuspender');`

**In development environment (Chromium Browser without Electron):**
Disabled Calculate window occlusion on Windows
In `Settings -> Performance, disabled/enabled Memory Saver`
Added local URL to the `Always keep these sites active` section

All these attempts did not resolve the issue of keeping the tab alive so that the data display does not get interrupted.

**Comment by ssaputo** [comment]
Although I cannot provide you the code as it is proprietary, I did create a test case that will display data in a continuous manner in JS Fiddle that will show the tab in Chromium goes to sleep after 5 minutes of inactivity. 

To use the program, click the Start button and wait for 5 minutes (about 300 seconds of elapsed time). Please keep in mind that you cannot move the mouse over the browser during this time.

However, even when the tab is asleep the code is still running. As soon as the mouse is jiggled over the browser, the data on the screen begins to update again and that the elapsed time jumps ahead in time.

Please find my test case here:
https://jsfiddle.net/ssaputo/z05wf8ru/4/

Thank you!

**Comment by theogravity** [comment]
I don't think this is an electron-specific issue. Chrome will throttle / sleep tabs if they're not active.

https://aboutfrontend.blog/tab-throttling-in-browsers/

I encountered this issue with our own app where interval timers weren't firing when they should have been and used a library like [worker-timers](https://www.npmjs.com/package/worker-timers) with a combination of page visibility events to resolve things.

Your fiddle doesn't seem to be using timers, but the same concepts should apply.

https://stackoverflow.com/questions/71984730/how-to-prevent-javascript-from-suspending-when-the-user-tabs-out

**Comment by tonny008** [comment]
disable backgroundThrottling

```ts
  mainWindow = new BrowserWindow({

    webPreferences: {
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js'),
      backgroundThrottling: false,
    },
  });
```

**Comment by theogravity** [comment]
> disable backgroundThrottling
> 
> 
> 
> ```ts
> 
>   mainWindow = new BrowserWindow({
> 
> 
> 
>     webPreferences: {
> 
>       contextIsolation: true,
> 
>       preload: path.join(__dirname, 'preload.js'),
> 
>       backgroundThrottling: false,
> 
>     },
> 
>   });
> 
> ```

There is a consequence to this - it will drain laptop battery because it's no longer being throttled when the browser isn't in focus

**Comment by ssaputo** [comment]
> > disable backgroundThrottling
> > ```ts
> >   mainWindow = new BrowserWindow({
> > 
> > 
> > 
> >     webPreferences: {
> > 
> >       contextIsolation: true,
> > 
> >       preload: path.join(__dirname, 'preload.js'),
> > 
> >       backgroundThrottling: false,
> > 
> >     },
> > 
> >   });
> > ```
> 
> There is a consequence to this - it will drain laptop battery because it's no longer being throttled when the browser isn't in focus

Thank you for your reply and will definitely look into this. For our app, it's only a single-page application and even if the Electron app has focus and you sit idle for 5 minutes, the page stops painting/rendering until the user moves the mouse again, similar to a screen saver.

**Comment by BubuInc** [comment]
> **Electron app:** In main.js, I added this line of code:
> 
> ` app.commandLine.appendSwitch('disable-features', 'TabSuspender');`

I couldn't find TabSuspender in [https://niek.github.io/chrome-features/](url)

**Comment by BubuInc** [comment]
Eureka!! It works with
`app.commandLine.appendSwitch('disable-features', 'WebContentsDiscard');`
It doesn't suspend.
