### ISSUE TITLE
[Bug]: cannot start

### ISSUE THREAD

**Issue by amongus11111** [electron/electron#41310]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

windows 10 22H2

### What arch are you using?

x64

### Last Known Working Electron version

IDK

### Expected Behavior

to work normally: I can log in with a bot token

### Actual Behavior

cannot start, beacuse have some errors, i see errors in console(Toggled Developer Tools): ```
 (index):1 Refused to apply style from 'https://discord.com/assets/0.2d737cc92c807c265e1f.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
discord.com/assets/e1180c171e5a54377584.js:1 Failed to load resource: the server responded with a status of 403 ()
discord.com/assets/07ca8d15cc9ad4ffc0f6.js:1 Failed to load resource: the server responded with a status of 403 ()
discord.com/assets/c05bdc0c5c3c90e28c77.js:1 Failed to load resource: the server responded with a status of 403 ()
discord.com/assets/7288c77130c62ff8aa82.js:1 Failed to load resource: the server responded with a status of 403 ()
(index):29 loaded /assets/e1180c171e5a54377584.js
blank.org/:1 Uncaught SyntaxError: Unexpected token '<'
    at (index):685
    at async Promise.all (/index 0)
    at /async https:/blank.org/:16
(index):29 loaded /assets/07ca8d15cc9ad4ffc0f6.js
blank.org/:1 Uncaught SyntaxError: Unexpected token '<'
    at (index):685
    at async Promise.all (/index 1)
    at /async https:/blank.org/:16
(index):29 loaded /assets/c05bdc0c5c3c90e28c77.js
blank.org/:1 Uncaught SyntaxError: Unexpected token '<'
    at (index):685
    at async Promise.all (/index 2)
    at /async https:/blank.org/:16
(index):29 loaded /assets/7288c77130c62ff8aa82.js
blank.org/:1 Uncaught SyntaxError: Unexpected token '<'
    at (index):685
    at async Promise.all (/index 3)
    at /async https:/blank.org/:16
(index):1 Refused to apply style from 'https://discord.com/assets/0.2d737cc92c807c265e1f.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

### Testcase Gist URL

_No response_

### Additional Information

_No response_

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
