### ISSUE TITLE
[Bug]: remote-debugging-port tries to connect, fails with websocket disconnected

### ISSUE THREAD

**Issue by inthegarage** [electron/electron#41325]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

23.3.13

### Expected Behavior

When I connect with a browser the Chrome debugging console should appear as it normally does. This allows me to inspect the console, network and elements. To enable the flag the electron app is sent the following command:

` app.commandLine.appendSwitch('remote-debugging-port', '8315');`

This command has not changed since v23.

### Actual Behavior

After a connection attempt, the following error is seen:

![image](https://github.com/electron/electron/assets/3224329/3382e61f-03dc-41fe-8ba7-eb1f8499a05a)

There is no further information.

### Additional Information

This is large application and so a gist isn't particularly possible. Has this flag been dropped?

**Comment by inthegarage** [comment]
@sbenmoussati Yes I did, I need to try and get a demo going. The thing it tries to connect (so it is starting), it then refusing to connect for some reason.

**Comment by inthegarage** [comment]
@sbenmoussati What I can say is if I revert back to v23 as the only change, then all is working again. In other words this is regression.

**Comment by Kitaharakasusa** [comment]
add this line in your code `app.commandLine.appendSwitch('remote-allow-origins', '*');`
