### ISSUE TITLE
GetVSyncParametersIfAvailable() failed error

### ISSUE THREAD

**Issue by gokul-3** [electron/electron#41323]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.4.4

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

Application need to run without any error. 

### Actual Behavior

Application run perfectly but some features are not working. It throws the below error when electron window launches.

### Additional Information

I am trying to implement key press action using nutjs in an electron app. It works perfectly in some systems but throws the mentioned error in some other systems. Application runs fine but key press action is not working in those laptops. What is the reason for the error? How to resolve that?

**Comment by codebytere** [comment]
Electron v21 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days f there is no response.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
