### ISSUE TITLE
[Bug]: iMac 2015 with AMD R9 Chip has rendering issues with BrowserView

### ISSUE THREAD

**Issue by Abisco** [electron/electron#41346]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.2

### What operating system are you using?

macOS

### Operating System Version

MacOS Catalina, Monterey, Big Sur

### What arch are you using?

x64

### Last Known Working Electron version

26.0.0

### Expected Behavior

BrowserView should work correctly

### Actual Behavior

Only iFrames seem to load (sometimes), our website seems to be either completely blank, have weird white or black boxes, and dev tools does not load (is black).

![image](https://github.com/electron/electron/assets/5394823/60c03f6b-8a1c-48fc-882e-20408dcd00a5)
![image](https://github.com/electron/electron/assets/5394823/5c7e4883-c8ce-4399-b758-4883909153b7)
![image](https://github.com/electron/electron/assets/5394823/ad7cd954-4d56-4cb4-bf06-6ccf78e77d02)
![image](https://github.com/electron/electron/assets/5394823/e35369a5-1872-4a5d-b399-b8de7dcf83bc)
![image](https://github.com/electron/electron/assets/5394823/c9faaa0e-5eaa-4871-a8ae-8dd7ee7ca96d)
![image](https://github.com/electron/electron/assets/5394823/c7ca0177-99ee-48b0-8dc1-27880d73a667)
![image](https://github.com/electron/electron/assets/5394823/0c472cad-8d14-4faa-867c-ab967ec15c38)

### Additional Information

This is happening to some of our clients. All of them have the exact same iMac build (2015 iMac 5k Screen with an AMD Radeon R9 chip). We did not get to try electron 27, but I can confirm that electron 26.0.0 works, while electron 28.2.0 and 28.2.2 do not work. 

Previously we were on Electron 25.0.0 which was working fine for all my users. 

Chrome works for all the users when visiting the website (latest chrome I believe) and so does Safari.

**Comment by VerteDinde** [comment]
Hey @Abisco, just to let you know, I've triaged your issue, but I think this one may be a bit difficult to move forward because none of us have the iMac required to repro this, unfortunately 😬 We'll do our best, but apologies in advance if a solution is slow moving.

As an interim solution, you may be able to detect the user's desktop model and disable hardware acceleration if a user has either the iMac make or the AMD chip.

**Comment by Abisco** [comment]
Hey @VerteDinde thanks so much! Does electron have a way to detect the GPU type? I know there's a way to check that it has Intel vs ARM so I could use that but don't want to turn off HA for all intel users

**Comment by YuhApps** [comment]
Happens to my app as well, both MAC and MAS builds are affected.

**Comment by rmartins90** [comment]
Did anyone find a workaround for this?

**Comment by YuhApps** [comment]
> Did anyone find a workaround for this?

Use Electron 26.

**Comment by thomasdao** [comment]
> Did anyone find a workaround for this?

I'm using Electron 29.2.0, and use the workaround from https://github.com/bitwarden/clients/pull/8427/files. I can confirm this fixes the issue for our iMac users.

```js
const gpuInfo = await app.getGPUInfo('basic')
const badGpu = gpuInfo?.auxAttributes?.amdSwitchable ?? false
const isImac = gpuInfo?.machineModelName === 'iMac'
if (isImac && badGpu) {
  app.disableHardwareAcceleration()
}
```

**Comment by thomasdao** [comment]
This issue happens with many Mac models, not only iMac with AMD R9 Chip. One user has the same problem with Macbook (12-inch, Early 2016, Dual-Core Intel Core m5 processor) with Intel HD Graphics 515 1536MB.

@VerteDinde It has been some time since your last reply but not sure if the Electron team has any progress regarding this issue? This affects all Electron version from 27 and above. Thank you :)

**Comment by kevinlinv** [comment]
Does anyone know if this is resolved in later major versions above v29??
