### ISSUE TITLE
[Bug]: laoder.wrap breaks sourceMapComment

### ISSUE THREAD

**Issue by jonnytest1** [electron/electron#41364]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.1

### What operating system are you using?

Windows

### Operating System Version

irrelevant

### What arch are you using?

x64

### Expected Behavior

when supplying the wrapper for nodeintegration i expect 
comments like 
`//# sourceMappingURL=`
are matched and copied after the wrapping

```
let wrap=function(script){
   let newScript=Module.wrapper[0] + script + Module.wrapper[1]
   const sourceMappingLine=script.trim().match(/(\/\/# sourceMappingURL=.*)/)
   if(sourceMappingLine?.[0]){
      newScript +=`\n${sourceMappingLine[0]}` ;
   }
   return newScript 
}
```

### Actual Behavior

the wrapping breaks this feature

**Comment by jonnytest1** [comment]
small fiddle:
https://gist.github.com/jonnytest1/89b9a70585adff96f43382ebab5960db

the wrapper breaks the sourcemapping

![image](https://github.com/electron/electron/assets/13507796/becc4d16-7870-4897-bcf7-9c3b4349c965)

**Comment by codebytere** [comment]
@jonnytest1 electron 21 is not supported. In order for us to continue, you'll need to demonstrate it happening on a [currently supported version](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

**Comment by jonnytest1** [comment]
the fiddle was running with the most current version

**Comment by jonnytest1** [comment]
my bad i used //# sourceMappingURL=instead of below

this is the correct example and it works with that
`//# sourceURL=https://runtime/content.key.1.js`
