### ISSUE TITLE
[Bug]: 我想把指定的Chromium集成到项目里，而不是使用项目自带的

### ISSUE THREAD

**Issue by rabbit-yu** [electron/electron#41366]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

28.2.1

### Expected Behavior

我想使用不同版本的UserAgent，但是我使用loadURL的userAgent参数更改以后，网页崩溃了，没有正常打开，而不指定userAgent可以打开，但是userAgent里边包含的electron的特征：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.268 Electron/28.2.1 Safari/537.36，对于我测试目标网站不好，所以我想去掉electron的特征，和可以随意的切换ua

### Actual Behavior

我使用过
mainWindow.webContents.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
和
mainWindow.loadURL('', {userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"});
都无法正常打开网页，只有不更改才可以

**Comment by CoorFun** [comment]
Electron 版本和 Chromium 版本是绑定的关系，直接替换 chromium 版本可能导致编译失败。可以考虑把目标 Electron 项目拉下来，然后同步对应的 Chromium，然后修改 Chromium 中被 electron 打了 patch 的部分（UA），重新构建 Electron App。

参考：https://www.electronjs.org/docs/latest/development/build-instructions-gn

**Comment by rabbit-yu** [comment]
> Electron 版本和 Chromium 版本是绑定的关系，直接替换 chromium 版本可能导致编译失败。可以考虑把目标 Electron 项目拉下来，然后同步对应的 Chromium，然后修改 Chromium 中被 electron 打了 patch 的部分（UA），重新构建 Electron App。
> 
> 参考：https://www.electronjs.org/docs/latest/development/build-instructions-gn

重新构建的electrion，ua里还有electron的特征吗，还是标准的chromium的ua呢
