### ISSUE TITLE
[Bug]: Electron deosn't use cached video file?

### ISSUE THREAD

**Issue by TerryChan** [electron/electron#41378]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

When play video looply with html video element , it use cached video file, don't always fetch video from server 

### Actual Behavior

it always fetch whole video from server

### Additional Information

In my Electron app,I use the html video element below to play mp4 video looply:
```
      <video
        ref={this.onVideoRef}
        autoPlay={true}
        loop={true}
        src={this.videoSrc}
        preload="auto"
      ></video>
```
and the src points to a CDN(https) url, the video size is more than 190MB. I found it always fetch the video from cdn with whole size, the the status code is always 206(Partial Content) instead of 304(Not Modified). The server response header has cache-control: max-age=86400, and also has etag and last-modified fields. It didn't use the cached video file locally.(sometimes it didn't fetch whole video from server, I don't know why)
![image](https://github.com/electron/electron/assets/5396286/55ff6a32-fa8c-4031-bf79-52544c33d062)
And when I request the video file in Chrome directly, it will response 304, don't fetch whole video from server
![image](https://github.com/electron/electron/assets/5396286/d60fd39b-024e-4d21-9b05-8a96a3999907)
I tried to add the code be low in my Electron app to set the cache size to 250MB, but it doesn't work
```
app.commandLine.appendSwitch('disk-cache-size', '256000000')
```
Is it true that Electron doesn't support caching video files when using the video element in an HTML file? or any other problem when use video in Electron? How to let it use local cached video file?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by brendanmatkin** [comment]
@codebytere I'm not sure that this is just a community issue - this might be an actual bug. I'm experiencing something similar. Are you saying that electron not caching videos is not a bug? Or are you saying there are some specific questions we should be asking about how to make it work properly?
