### ISSUE TITLE
[Bug]: Electron13+  always wakes up dGPU on hybrid setup (Intel + Nvidia PRIME)

### ISSUE THREAD

**Issue by cyqsimon** [electron/electron#41389]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Tested: 13-28

### What operating system are you using?

Other Linux

### Operating System Version

Linux 6.7.5-arch1-1

### What arch are you using?

x64

### Last Known Working Electron version

12.2.3

### Expected Behavior

When starting an electron application, the discrete GPU does not get waken up, or only gets waken up momentarily before going back to `D3cold` state.

### Actual Behavior

When starting an electron application, the discrete GPU always get waken up (goes to `D0` state) and stays awakened until the program exits. This causes significant and unnecessary battery drain.

### Additional Information

Versions of system packages (up to date Arch Linux as of writing):
- `nvidia-utils`: 545.29.06
- `intel-media-driver`: 24.1.3
- `mesa`: 24.0.1

Related: https://bbs.archlinux.org/viewtopic.php?id=284426

**Comment by cyqsimon** [comment]
## Steps to reproduce

On a laptop with a working Intel + Nvidia PRIME hybrid setup (see https://wiki.archlinux.org/title/PRIME):

1. Follow the [Quick Start Guide](https://www.electronjs.org/docs/latest/tutorial/quick-start) to create a new Electron application. An empty `index.js` will do.
2. Before starting the application, run `watch /sys/class/drm/card*/device/power_state` in a separate terminal to monitor the power state of the Nvidia GPU. Verify that the Nvidia GPU is currently in the `D3cold` state.
3. Run `yarn start`.
4. Verify that the Nvidia GPU is now in the `D0` state.
5. Wait a while and observe that the Nvidia GPU stays in the `D0` state.
6. Terminate the electron application. In a few seconds you should see that the Nvidia GPU has returned to the `D3cold` state.

**Comment by Hobbyist11** [comment]
I can also reproduce the issue using the same steps. Launching foliate (epub reader) turns on the Nvidia GPU which leads to high power usage.

**Comment by cyqsimon** [comment]
## Update 2024-02-28:

I very recently updated my Nvidia drivers (`nvidia-utils`) to 550.54.14 (latest for Arch Linux at time of writing), which seems to have solved this issue. So this may be an Nvidia driver issue after all.

Starting the Electron application still wakes up the dGPU (which I guess is fine because it was being queried), but it soon goes back to `D3cold` after a few seconds.

I'll close this issue for now. Will reopen if it reappears in the future.

**Comment by HelloMum** [comment]
> ## Update 2024-02-28:
> 
> Starting the Electron application still wakes up the dGPU (which I guess is fine because it was being queried), but it soon goes back to `D3cold` after a few seconds.
> 

The problem with this is that electron apps still try to wake app the GPU, shouldn't be an issue as it is only a few seconds of extra power, but this generates  a delay of 5-10 seconds in every electron app opening, as it needs tp wait to the GPU to wake app to respond to the call with the state, and go back to sleep.

**Comment by esklarski** [comment]
I ca attest this is not an Nvidia driver problem, I'm on an AMD system with an AMD dgpu, and electron apps all cause the dgpu to wake for a few seconds delaying their startup.

**Comment by HelloMum** [comment]
> I ca attest this is not an Nvidia driver problem, I'm on an AMD system with an AMD dgpu, and electron apps all cause the dgpu to wake for a few seconds delaying their startup.

Basically it does a pcie reading and wakes up everything, when using a VFIO on the graphic card it was completely disconnected both from the environment and not using the Nvidia driver, but still got awakened for a few seconds! I cannot imagine the headache that this has given to some people. Best practice is make the pcie line not accessible

**Comment by waltercool** [comment]
> > I ca attest this is not an Nvidia driver problem, I'm on an AMD system with an AMD dgpu, and electron apps all cause the dgpu to wake for a few seconds delaying their startup.
> 
> Basically it does a pcie reading and wakes up everything, when using a VFIO on the graphic card it was completely disconnected both from the environment and not using the Nvidia driver, but still got awakened for a few seconds! I cannot imagine the headache that this has given to some people. Best practice is make the pcie line not accessible

It doesn't got awakened for a few seconds, it gets awakened permanently as long the app is running.

In this case, I have teams-for-linux opened after few minutes and is still connected to my dGPU, preventing going into D3Cold.

![Screenshot_20240913_144956](https://github.com/user-attachments/assets/8ea6b099-a639-4a28-9f9c-b2657ca747a3)

**Comment by lprobsth** [comment]
During my search for blocking the usage of the nvidia dGPU on hybrid systems by electron apps (discord, VScode, ...) I stumbled upon:
```
export VK_DRIVER_FILES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json
```

This seems to force usage of the intel iGPU.

In my case this was for unloading the nvidia kernel modules with nvx for turning the dGPU off (power management is unsupported due to an older nvidia GPU model) which is blocked if electrons are started while the dGPU is still on. But I suspect that this also works for Runtime D3 (RTD3) Power Management.

**Comment by HelloMum** [comment]
> It doesn't got awakened for a few seconds, it gets awakened permanently as long the app is running.
> 
> In this case, I have teams-for-linux opened after few minutes and is still connected to my dGPU, preventing going into D3Cold.
> 
> ![Screenshot_20240913_144956](https://github.com/user-attachments/assets/8ea6b099-a639-4a28-9f9c-b2657ca747a3)

I had a small fix to avoid some headaches in my .bashrc by always assigning the AMD selection. Then I manually run whatever I want by calling envidia + command.

```

# Default Vulkan ICD for AMD
export VK_DRIVER_FILES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json

# Function to run commands with NVIDIA GPU
function envidia() {
  # Save the old VK_DRIVER_FILES
  local old_vk_driver_files=$VK_DRIVER_FILES

  # Temporarily unset VK_DRIVER_FILES
  unset VK_DRIVER_FILES

  # Set environment variables for NVIDIA GPU and run the command
  VK_DRIVER_FILES=/usr/share/vulkan/icd.d/nvidia_icd.x86_64.json \
  __NV_PRIME_RENDER_OFFLOAD=1 \
  __GLX_VENDOR_LIBRARY_NAME=nvidia \
  __VK_LAYER_NV_optimus=NVIDIA_only \
  "$@"

  # Restore VK_DRIVER_FILES after command execution
  export VK_DRIVER_FILES=$old_vk_driver_files
}

```
With this you avoid accidentally activating the dedicated GPU, which significantly reduces unnecessary power consumption.
