### ISSUE TITLE
[Bug]: Trojan.Heur!.02052023 present in Windows binaries 

### ISSUE THREAD

**Issue by kaljjuta** [electron/electron#41392]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.3.2 and newer

### What operating system are you using?

Windows

### Operating System Version

Windows 10 and newer

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

Windows binary releases should not be infected by Trojan.Heur!.02052023

### Actual Behavior

Win binary releases 27.3.2 upto 29.0.0 have file electron.exe that is infected by Trojan.Heur!.02052023

Did not check older ones.

https://github.com/electron/electron/releases/

To reproduce, just drop the file to online virus scan at https://www.virustotal.com/gui/home/upload

**Comment by kaljjuta** [comment]
as chromedriver.exe is identified the same way, it may originate from there

https://www.virustotal.com/gui/file/8cddfc47d5a388a08ea94ac79e86932bec1fa0550b8b74a90a08ce5ae1863d37/detection

**Comment by MarshallOfSound** [comment]
@kaljjuta This is a false positive, Chrome's `chrome.exe` and `chromedriver.exe` _also_ report this on virustotal.  In general the `Heur` flags are quite commonly false positives as their heuristically matches rather than literal malware matches.

This is safe to ignore, closing out.
