### ISSUE TITLE
[Bug]: IME keyboards break in text input on Windows Remote Desktop connections after server-side disconnect

### ISSUE THREAD

**Issue by mt-xing** [electron/electron#41393]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.2.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise Version 22H2 build 22621.3155

### What arch are you using?

x64

### Expected Behavior

When using a CJK language input with an IME (eg: Chinese, Japanese, or Korean keyboard input) in an Electron app in a remote desktop session on a remote Windows machine, if a server-side disconnect happens, when the user reconnects, the input should still work.

### Actual Behavior

Any text fields on screen no longer accept input after reconnecting. It still receives focus and the blinking cursor shows up just fine, but typing does nothing. This happens on all Electron apps I tested, including VS Code, Slack, and MS Teams. Note this behavior does not repro in non-Electron apps, such as Notepad.

Other interesting behaviors:
- Switching focus to another app and back does not fix the problem
- The app still accepts mouse input no problem
- Switching keyboards to another language like English not only fixes the inputs, but also causes the last few keypresses to suddenly show up in the input field as English characters, as if buffered somehow.
- Any new input fields that spawn on screen after the reconnect by the app **do** work properly (eg: in Slack, switching to a different message thread causes the message box on that message thread to work properly, and then switching back makes the original work too, whereas on Teams, which evidently persists the same message box across message threads, switching to a different message thread has no effect).

### Additional Information

I don't know any specifics about IMEs but it would appear that it's not properly handling whatever hangup message the remote desktop protocol sends in the event of a server-side disconnect. Note this behavior does not repro if the client manually disconnects from the remote desktop session.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by gnh1201** [comment]
In Windows 11 Remote Desktop session environments, when using CJK IMEs, keyboard input for text input fields in web-based apps (such as Microsoft Edge browser and Electron-based apps) may experience delays or become unresponsive.

This issue is primarily known to occur when using East Asian IMEs (e.g., Chinese, Japanese, or Korean keyboard input) in Windows 11. Since the problem does not occur with IMEs in Windows 10, it suggests a bug in the IMEs of Windows 11 that needs to be fixed. However, Microsoft does not appear to have shown much interest in addressing this issue yet.

**Comment by gnh1201** [comment]
Related issues:

- #40578
- https://github.com/microsoft/vscode/issues/167556
