### ISSUE TITLE
[Bug]: Window title screen corruption in Electron 29 when full screen (Linux/Wayland/GNOME)

### ISSUE THREAD

**Issue by cedricroijakkers** [electron/electron#41409]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux (rolling)

### What arch are you using?

x64

### Last Known Working Electron version

27.3.2

### Expected Behavior

Window title bar is not corrupted

### Actual Behavior

I'm testing this with [Ferdium](https://github.com/ferdium/ferdium-app) which has recently switched from Electron 27 to Electron 29 (in the nightly builds, if you want to test it). I'm using Linux with Wayland and GNOME as desktop environment.

Since the upgrade to 29, the window title bar is corrupted. However, only when the screen is maximised, and only when using the native Wayland integration (i.e. running with `--ozone-platform-hint=wayland` or `--ozone-platform-hint=auto`). In X11 (using XWayland) mode, the screen is fine (however since I'm using fractional scaling, the text is blurry).

I've had to make a photo of my screen, because it does not show up in a screenshot, but this is what it looks like:

![image](https://github.com/electron/electron/assets/15158042/0a57a936-abf4-4feb-a959-69d3a7301e09)

It is as if what as previously displayed on that location of the screen, is still partially shown. In the next photo, you can see a leftover bit of Evolution displayed in the top left corner:

![image](https://github.com/electron/electron/assets/15158042/8f58f525-e7d0-4ebb-857b-7f5f8742c1ee)

This only happens since the upgrade to v29.

**Comment by janvlug** [comment]
I see also some window title corruption. I can kind of reproduce this on Fedora 39 GNOME Wayland with the Signal Desktop [flatpak](https://flathub.org/apps/org.signal.Signal) installation:

- Make Signal full screen
- Quit Signal when it is full screen
- Start Signal again. Note that Signal is now not full screen, but there is room at the right and bottom side of the Signal window
- Click and drag Signal via the window title bar. Now the window title bar corruption happens.

**Comment by cedricroijakkers** [comment]
Can still reproduce the issue with Electron 29.1.1

**Comment by iommu** [comment]
Interesting note : I find it to be GTK theme specific. 
Specifically I found that the Arc theme, and Adwaita both don't appear to corrupt

**Comment by cedricroijakkers** [comment]
You are correct. I can reproduce it on [Yaru-Colors](https://www.gnome-look.org/p/1299514) and [Vimix](https://www.gnome-look.org/p/1013698/), but not on [Matcha](https://www.gnome-look.org/p/1187179/) and Adwaita.

**Comment by cedricroijakkers** [comment]
I am not in the business of making neither Electron apps or GTK Themes, which this issue seems to be a combination of. So I will leave the creation of an Electron app to reproduce the issue to someone with more knowlegde of that.

**Comment by janvlug** [comment]
To reproduce this, install Signal from flathub on fully up-to-date Fedora 39, maximize and unmaximize Signal and you will see the disruption.
