### ISSUE TITLE
[Bug]: Electron crash on GetClipboardData

### ISSUE THREAD

**Issue by GaurangTandon** [electron/electron#41411]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.22000

### What arch are you using?

x64

### Expected Behavior

Electron app should not crash

### Actual Behavior

Electron app crashed

### Additional Information

The crash only happened once, and we could not reproduce it again. We are using invoke handler - wherein the renderer process requests the clipboard content from the main process, and the main process responds to that request.

**From renderer**: `window['electronAPI'].invokeHandler(data)`

**From preload.js:**

```js
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  invokeHandler: (data) => ipcRenderer.invoke('invoke-handler', data)
});
```

**From main process:**

```js
  ipcMain.handle('invoke-handler', (event, dataReceived) => {
    ...
    return { text: clipboard.readText('clipboard') }
  });
```

**Error trace:**

```
OS Version: Windows 10.0.22000 (2538)
Report Version: 104

Crashed Thread: 20288

Application Specific Information:
Fatal Error: EXCEPTION_ACCESS_VIOLATION_READ / 0xffffffffffffffff

Thread 20288 Crashed:
0   USER32.dll              0x7ffb5d93874a      GetClipboardData
1   appname.exe             0x7ff72eb98bbd      ui::ClipboardWin::ReadText (clipboard_win.cc:362)
2   appname.exe             0x7ff72829292d      electron::api::Clipboard::ReadText (electron_api_clipboard.cc:152)
3   appname.exe             0x7ff72814c644      base::internal::Invoker<T>::Run (bind_internal.h:932)
4   appname.exe             0x7ff7281f3798      gin_helper::Invoker<T>::DispatchToCallback<T> (function_template.h:224)
5   appname.exe             0x7ff728296477      gin_helper::Dispatcher<T>::DispatchToCallback (function_template.h:269)
6   appname.exe             0x7ff72c0ef641      Builtins_CallApiCallbackGeneric
7   <unknown>               0xd32c1fcd40        <unknown>
```

**Comment by GaurangTandon** [comment]
Regretfully, I cannot provide any reproducible and standalone testcase for this, as this issue only happened once out of several (possibly thousands) of triggers.

Can you please point me to some general directions as to why such a crash would occur? Given the stack trace this looks like an Electron issue, although I could be wrong, and in that case I could use some help understanding the full context.

Thanks!

**Comment by codebytere** [comment]
@GaurangTandon yes you're right - it's definitely something we should triage in Electron! It just is much harder to fix if we don't know how to trigger it and/or ensure that a fix addresses the issue properly.

**Comment by GaurangTandon** [comment]
Hi @codebytere this issue happened again. Here's the stack trace:

```text
OS Version: Windows 10.0.19045 (4046)
Report Version: 104

Crashed Thread: 29120

Application Specific Information:
Fatal Error: EXCEPTION_ACCESS_VIOLATION_EXEC / 0x7ff9d2680ffa

Thread 29120 Crashed:
0   <unknown>            0x7ff9d2680ffa      <unknown>
1   appname.exe          0x7ff6a4e08bbd      ui::ClipboardWin::ReadText (clipboard_win.cc:362)
2   appname.exe          0x7ff69e50292d      electron::api::Clipboard::ReadText (electron_api_clipboard.cc:152)
3   appname.exe          0x7ff69e3bc644      base::internal::Invoker<T>::Run (bind_internal.h:932)
4   appname.exe          0x7ff69e463798      gin_helper::Invoker<T>::DispatchToCallback<T> (function_template.h:224)
5   appname.exe          0x7ff69e506477      gin_helper::Dispatcher<T>::DispatchToCallback (function_template.h:269)
6   appname.exe          0x7ff6a235f641      Builtins_CallApiCallbackGeneric
7   <unknown>            0xa9e2ffca48        <unknown>
8   appname.exe          0x7ff6a24e8088      Builtins_CreateObjectLiteralHandler
9   <unknown>            0xa9e2ffca18        <unknown>
10  appname.exe          0x7ff6a235d6e3      Builtins_InterpreterEntryTrampoline
```

We're using SentryJS for error monitoring. Please let me know what additional info (like breadcrumb or other system state) would be useful for your team for debugging this issue, and we'll try our best to get them.

**Comment by GaurangTandon** [comment]
I apologise for the misunderstanding. Today's crash has actually happened on an older app version using Electron v25.8.1. The original error (in my original post) was still on Electron v28.0.0.

**Comment by GaurangTandon** [comment]
I got the same crash today on Electron v28.2.3:

```
OS Version: Windows 10.0.19045 (3930)
Report Version: 104

Crashed Thread: 9672

Application Specific Information:
Fatal Error: EXCEPTION_ACCESS_VIOLATION_EXEC / 0x7ffca9f00ffa

Thread 9672 Crashed:
0   <unknown>               0x7ffca9f00ffa      <unknown>
1   appname.exe             0x7ff6501088ad      ui::ClipboardWin::ReadText (clipboard_win.cc:362)
2   appname.exe             0x7ff6497e97bd      electron::api::Clipboard::ReadText (electron_api_clipboard.cc:152)
3   appname.exe             0x7ff6496abe44      base::internal::Invoker<T>::Run (bind_internal.h:932)
4   appname.exe             0x7ff649749db8      gin_helper::Invoker<T>::DispatchToCallback<T> (function_template.h:224)
5   appname.exe             0x7ff6497ed307      gin_helper::Dispatcher<T>::DispatchToCallback (function_template.h:269)
6   appname.exe             0x7ff64d672481      Builtins_CallApiCallbackGeneric
```

I would appreciate any pointers on how to at least mitigate these errors, as they are all fatal errors, and breaking the user experience. Happy to provide any extra breadcrumbs/events information as needed.
