### ISSUE TITLE
[Feature Request]: Any plan to build a new version for 26.x.y with pr #41376 ?

### ISSUE THREAD

**Issue by appdevopts** [electron/electron#41422]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The pr #41376 introduced some CVE fixes and was merged into branch 26-x-y these days.
And it was opened at days before 26-x-y reached it's EOF.
I have seen some build jobs on the page but they have been cancelled, so there are still plans to release a new version for 26-x-y, is that right?

### Proposed Solution

None

### Alternatives Considered

None

**Comment by MarshallOfSound** [comment]
That PR was landed _after_ the final EOL `26-x-y` release.  Our automation kicked off the 26-x-y release at 8:30am PST on Monday the 19th, Electron 26 went EOL on the 20th per our [timeline](https://www.electronjs.org/docs/latest/tutorial/electron-timelines), that PR was merged the next day on the 21st.

Admittedly it probably should have been merged or closed before the final EOL release but it wasn't and now neither our automation nor our policies allow for an additional release of Electron 26.  I will follow up with the rest of the release wg tomorrow but the current answer is "no, there will not be an additional release of Electron 26", we reccomend you update to a supported Electron version (preferably latest so v29)
