### ISSUE TITLE
[Bug]: Crash on Window, Electron >= 27

### ISSUE THREAD

**Issue by trungutt** [electron/electron#41426]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.x.x

### What operating system are you using?

Windows

### Operating System Version

Windows 22H2 19045.4046 with 2 CPUs

### What arch are you using?

x64

### Last Known Working Electron version

26.x.x

### Expected Behavior

Electron app doesn't crash on startup

### Actual Behavior

Electron app crash on startup (worked fine with Electron 26.x.x)

### Additional Information

Hi, firstly thanks for maintaining this amazing library.

Our application is fairly complex, using Electron internally. With Electron 26.6.6 (and we could assume all 26.x.x), our application works fine. From Electron 27.x.x, it crashes on startup. 

Here's the zip of .dmp file

[4c16a081-0b77-4699-8d4b-e4ff4eaf2e54.dmp.zip](https://github.com/electron/electron/files/14385384/4c16a081-0b77-4699-8d4b-e4ff4eaf2e54.dmp.zip)

We tested our applications across lots of machines in different platforms. We notice that for Windows with 2 CPUs, it crashes easily.

Nevertheless, Electron 26.x.x isn't a long term solution because it's becoming EOL according to [Electron releases timeline](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline)

Could anyone please look into that? Thanks in advance

**Note:**

`electron-minidump` gives that

```
Operating system: Windows NT
                  10.0.19045 4046
CPU: amd64
     family 6 model 85 stepping 7
     2 CPUs

GPU: UNKNOWN

Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0x0
Process uptime: 7 seconds

Thread 44 (crashed)
 0  ntdll.dll!RtlCreateUnicodeString + 0x28
    rax = 0x0000000000000000   rdx = 0x0000000000000000
    rcx = 0x00000082d37ff760   rbx = 0x00007ff75a65c100
    rsi = 0x0000000000007530   rdi = 0x00000082d37ff760
    rbp = 0x00000082d37ff7a9   rsp = 0x00000082d37ff6c0
     r8 = 0x00000082d37ff7d8    r9 = 0x0000000000000000
    r10 = 0x0000000000000000   r11 = 0x0000000000000246
    r12 = 0x00007ff98201b710   r13 = 0x0000000000000000
    r14 = 0x0000000000000000   r15 = 0x0000000000000000
    rip = 0x00007ff982308b18
    Found by: given as instruction pointer in context
 1  KERNELBASE.dll!WaitNamedPipeW + 0x31
    rbx = 0x00007ff75a65c100   rsi = 0x0000000000007530
    rdi = 0x0000000000000000   rbp = 0x00000082d37ff7a9
    rsp = 0x00000082d37ff700   r12 = 0x00007ff98201b710
    r13 = 0x0000000000000000   r14 = 0x00007778003e84a8
    r15 = 0x00007ff98203bb90   rip = 0x00007ff97fe1e531
    Found by: call frame info
...
```

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
