### ISSUE TITLE
[Bug]: Doc generated API extends NodeJS.EventEmitter unexpectedly

### ISSUE THREAD

**Issue by CoorFun** [electron/electron#41421]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.6.9

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22621.3007

### What arch are you using?

x64

### Expected Behavior

I try to extends som electron apis.

I first define it under `docs/api/hello_world.md`:
```markdown
# helloWorld

> Print the "hello world" message in different ways

Process: [Main](../glossary.md#main-process), [Renderer](../glossary.md#renderer-process)

## Methods

The `helloWorld` module has the following methods:

### `helloWorld.print(message)`

* `message` string - A message that would be printed from native code.

Passing message from Javascript, using native methods to print out.
```

Then I ran script gen-filenames:
```bash
ts-node scripts/gen-filenames.ts
```

Finally I rebuilt Electron. I expect to have the following d.ts:

```typescripts
interface HelloWorld {
  // Docs: https://electronjs.org/docs/api/hello_word

  /**
   * Passing message from Javascript, using native methods to print out.
   */
  print(message: string): void;

  Passing message from Javascript, using native methods to print out.
}
```

But it extends NodeJS.EventEmitter for no reason. 

### Actual Behavior

Generated type definition:

```typescripts
interface HelloWorld extends NodeJS.EventEmitter {
  // Docs: https://electronjs.org/docs/api/hello_word

  /**
   * Passing message from Javascript, using native methods to print out.
   */
  print(message: string): void;

  Passing message from Javascript, using native methods to print out.
}
```

**Comment by MarshallOfSound** [comment]
This list of things that **aren't** event emitters is currently hardcoded in our ts generation module

https://github.com/electron/typescript-definitions/blob/main/src/utils.ts#L262-L286

There's a world where that extends information is correctly inferred from the docs but currently that's the source of the eventemitter extend you're seeing
