### ISSUE TITLE
[Bug]: Renderer's IPC Listener goes undefined after pressing "X" on MacOS

### ISSUE THREAD

**Issue by meddouribadis** [electron/electron#41438]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.3

### What arch are you using?

x64

### Expected Behavior

The sending of messages between the main process and the renderer is carried out correctly when I close (with the cross and not with CMD+Q) and reopen my application on MacOS.

### Actual Behavior

When I instantiate my window for the first time, the renderer does have a listener but when I close my window (with the cross and without doing CMD+Q), when I restart my application, the IPC listener on the renderer becomes "undefined" and is therefore unable to receive messages.

`electron.js` file :
```javascript
// ...

function launchApp() {
	const mainWindow = createWindow("main", {
		webPreferences: {
			preload: join(__dirname, "../preload/index.js"),
		},
	});

	powerMonitor.on("on-ac", () => {
		mainWindow.webContents.send("power-resume", "on-ac");
	});

	powerMonitor.on("resume", () => {
		mainWindow.webContents.send("power-resume", "resume");
	});
}

// ...
```

`./preload/index.js` file :
```javascript
const { contextBridge, ipcRenderer } = require("electron");

// Expose protected methods that allow the renderer process to use
// the ipcRenderer without exposing the entire object
contextBridge.exposeInMainWorld("ipcRenderer", {
	send: (channel, data) => ipcRenderer.send(channel, data),
	on: (channel, func) =>
		ipcRenderer.on(channel, (events, ...args) => func(...args)),
	onPowerResume: (callback) => {
		console.log("TEST");
		ipcRenderer.on("power-resume", (_event, value) => callback(value));
	},
});
```

My React renderer listener :
```javascript
useEffect(() => {
	console.log(window.ipcRenderer); // This line prints an object when the window is instantiated the first time and becomes undefined if I close and reopen the window
	window.ipcRenderer.onPowerResume((value) => {
		if (value) {
			doAction();
		}
	});
});
```

Console output on first launch :
```
index.js:43 {send: ƒ, on: ƒ, onPowerResume: ƒ}
VM5:11 TEST
index.js:43 {send: ƒ, on: ƒ, onPowerResume: ƒ}
VM5:11 TEST
```

Console output on app relaunch :
```
index.js:43 undefined
index.js:44 Uncaught TypeError: Cannot read properties of undefined (reading 'onPowerResume')
```

**Comment by jkleinsc** [comment]
@meddouribadis I added blocked/need-repro here because while you have provided somewhat of a repro in your comments, it is missing pieces which doesn't give a complete picture of what you are trying to do  (eg your output says line 43 of index.js, but that doesn't match the index.js you provided).
