### ISSUE TITLE
[Bug]: webContents.send() does not thrown a serialization error

### ISSUE THREAD

**Issue by Rn145** [electron/electron#41433]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2 19045.3693

### What arch are you using?

x64

### Expected Behavior

When passing an argument to web content.send that is not subject to serialization, the exception 'Error: Failed to serialize arguments' should be caught.
```ts
try{
  window.webContents.send('CHANNEL_1', Symbol()) // thrown exception
}
catch(error){
  console.log('sucessful catched', error)
}
```

### Actual Behavior

The exception is not returned from the function. Instead, this exception is output to the console without affecting the progress of the program, except that the rendering process receives nothing.
```ts
try{
  window.webContents.send('CHANNEL_1', Symbol()) // the exception is not thrown
}
catch(error){
  console.log('sucessful catched', error)
}
```

### Testcase Gist URL

https://gist.github.com/Rn145/25493b427379ff70f089d731a9397c6a

### Additional Information

I was trying to study this problem, and the first thing I did was go to study the Electron source code. I saw it there:
```ts
WebFrameMain.prototype.send = function (channel, ...args) {
  if (typeof channel !== 'string') {
    throw new TypeError('Missing required channel argument');
  }

  try {
    return this._send(false /* internal */, channel, args);
  } catch (e) {
    console.error('Error sending from webFrameMain: ', e);
  }
};
```
Later I came across this PR https://github.com/electron/electron/pull/31401 in which another error was discussed, but its temporary solution still remained in the code and intercepted all exceptions from _send().

**Comment by taniishkaaa** [comment]
hi, i might have a fix for this issue & I'd be happy to open a PR for the same but I'm facing an error while running the tests:
`An error occurred inside the spec runner: Error: No valid out directory found; use one of Testing,Release,Default,Debug or set process.env.ELECTRON_OUT_DIR
    at Object.getOutDir (/home/tanishka/electron/script/lib/utils.js:57:9)
    at installSpecModules (/home/tanishka/electron/script/spec-runner.js:216:62)
    at main (/home/tanishka/electron/script/spec-runner.js:92:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
I've tried reading the documentation but I haven't been able to fix this yet. Any advice on how I can resolve this?
