### ISSUE TITLE
[Bug]: The first level menu is not displayed

### ISSUE THREAD

**Issue by maoweifan** [electron/electron#41444]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.x.y

### What operating system are you using?

macOS

### Operating System Version

14.3.1 (23D60)

### What arch are you using?

x64

### Expected Behavior

First level menu display

### Actual Behavior

I have only verified Mac OS currently, and the situation with Windows is unknown. Is this intentional or a bug?

### Testcase Gist URL

https://github.com/maoweifan/electron_The-first-level-menu-is-not-displayed

**Comment by vaishu567** [comment]
Hello maoweifan!
can you upload a video demonstration of the issue so that we can understand where exactly you are facing the issue?

**Comment by maoweifan** [comment]
https://github.com/maoweifan/electron_The-first-level-menu-is-not-displayed

**Comment by maoweifan** [comment]
I think the code for the warehouse I provided can reproduce the problem, do you still need to provide a video?

**Comment by maoweifan** [comment]
@vaishu567
