### ISSUE TITLE
[Bug]: can not  import ipcRender and contextBridge in mjs module

### ISSUE THREAD

**Issue by keven-wang** [electron/electron#41449]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0.1

### What operating system are you using?

macOS

### Operating System Version

12.7.1 (21G920)

### What arch are you using?

x64

### Expected Behavior

can import and run correctly

### Actual Behavior

![image](https://github.com/electron/electron/assets/6857789/3da6b1e9-ca6d-4803-98a6-9ca1ab6f30de)

### Additional Information

the following code can run successfully
```javascript
const { app, ipcRenderer, contextBridge, BrowserWindow }  = require('electron');
```
but in mjs module mode, the following code will report error
```javascript
import { app, ipcMain, ipcRenderer, contextBridge, BrowserWindow } from 'electron';
```
ipcRenderer and contextBridge can not import, **but ipcMain can.**

![image](https://github.com/electron/electron/assets/6857789/203b25f4-609a-4875-8fa5-f9771ccc876c)

i console log the electron default export use the following code:
```javascript
import * as electron from 'electron';
console.log('electron default info:', electron);
```
and get the folling output
![image](https://github.com/electron/electron/assets/6857789/43f6db7f-cec4-4a62-a87c-f992dea1873c)

my test code:
```javascript
// main.js

// Modules to control application life and create native browser window
import path, { dirname } from 'node:path'
import { app, ipcMain, ipcRenderer, contextBridge,  BrowserWindow } from 'electron';

const __dirname = dirname(new URL(path.dirname(import.meta.url)).pathname);

const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  // 加载 index.html
  mainWindow.loadFile('index.html')
}

app.whenReady().then(() => {
  createWindow()

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})

```

**Comment by codebytere** [comment]
` ipcRenderer` and `contextBridge` are renderer process only modules. This is intended behavior.

**Comment by keven-wang** [comment]
ok, I get it. Thanks very much.

**Comment by therealkenc** [comment]
I just hit this also. This has to do with [ESM](https://www.electronjs.org/docs/latest/tutorial/esm). I blindly did this in the renderer `index.ts`:

```
contextBridge.exposeInMainWorld("electronAPI", {
  onChatMessage: (callback: (msg: string) => void) =>
    ipcRenderer.on("message", (_event, msg) => callback(msg)),
});
```

But that blows up with: Module "path" has been externalized for browser compatibility.

![Image](https://github.com/user-attachments/assets/e9203631-71c1-42e4-8f02-fc2fa2d0ab47)

I wouldn't expect that to make sense more I think about it.

Like the OP, I am passing a `.mjs` to the `new BrowserWindow`. It is running in the a "renderer process only module", that Window is the renderer.

```
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      contextIsolation: true,
      preload: path.join(__dirname, "preload.mjs"),
      sandbox: false,
      nodeIntegration: true,
    },
  });
```

@keven-wang  if you push through it somehow, pointers appreciated.
