### ISSUE TITLE
[Bug]: maximize not working for child windows on Ubuntu (X11)

### ISSUE THREAD

**Issue by hrnxm** [electron/electron#41465]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0.1

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Expected Behavior

Child `BrowserWindow` should be maximizable, like regular (orphan) window.

### Actual Behavior

When window is created and a parent window is assigned to it, `maximize` function is not working on the child. There is also no maximize button on the native frame.

### Testcase Gist URL

[Gist](https://gist.github.com/hrnxm/ded014253f7cc6573b15cb1e67fa7f26)

### Additional Information

Confirmed to be working on Debian 12

**Comment by hrnxm** [comment]
Added the [Gist](https://gist.github.com/hrnxm/ded014253f7cc6573b15cb1e67fa7f26) URL to the original description

**Comment by ak47me** [comment]
I think I can try to resolve the issue.Can I be assigned?Thank you
