### ISSUE TITLE
[Bug]: Docs - webContents.print() options aren't optional

### ISSUE THREAD

**Issue by panther7** [electron/electron#41464]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Expected Behavior

```js
webContents.print(); // ok, without error
```

### Actual Behavior

```js
webContents.print(); // TypeError: webContents.print(): Invalid print settings specified.

webContents.print({}); // with empty object - ok
```

### Additional Information

Docs: https://www.electronjs.org/docs/latest/api/web-contents#contentsprintoptions-callback

**Comment by Reqwey** [comment]
Encountered this problem a few months ago. Waiting for official explanation.

**Comment by Reqwey** [comment]
electron/docs-parser#104 This issue seems to be similar.
