### ISSUE TITLE
[Feature Request]: How to write both text and custom format data into the clipboard simultaneously

### ISSUE THREAD

**Issue by fanybook** [electron/electron#41462]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

How to write both text and custom format data into the clipboard simultaneously?

```js
clipboard.writeText('hello')

and

clipboard.writeBuffer('custom/html', buffer)
```

I hope to write both text and custom format data into the clipboard simultaneously! like the 'clipboard.write'（only support text, html, image, rtf, bookmark）
I hope to hide the HTML content and not be easily read by other programs!

### Proposed Solution

```js
clipboard.writeTextAndBuffer({
    text: 'hello',
    'custom/utf8-html': buffer1,
    'custom/hidden: buffer2,
})

// call they via the same 'ui::ScopedClipboardWriter writer'
writer.WriteText(text)
writer.WriteUnsafeRawData
```

### Alternatives Considered

none

**Comment by dhimmel** [comment]
@fanybook why did you close the issue? Did you find a solution?
