### ISSUE TITLE
[Feature Request]: Electron@29 not supported astc extension in WebGL

### ISSUE THREAD

**Issue by YunYouJun** [electron/electron#41473]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.0

### What operating system are you using?

macOS

### Operating System Version

14.3.1 (23D60)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

null

### Expected Behavior

Supprt WebGL extension `WEBGL_compressed_texture_astc`

![image](https://github.com/electron/electron/assets/25154432/24cc564d-7306-481b-a8ed-fa4bc654d3a4)

### Actual Behavior

astc not supported.

https://webglreport.com/

### Additional Information

Just in electron, `window.location.href=https://webglreport.com/`

We can see what that electron supports.

**Comment by nornagon** [comment]
We do not enable or disable any WebGL features specifically in Electron; such feature support is entirely in Chromium and we inherit whatever Chromium does here.
