### ISSUE TITLE
[Bug]: Linkedin loaded in WebView prompting Windows users to "Sign in with your passkey"

### ISSUE THREAD

**Issue by joelwright-dev** [electron/electron#41472]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Version 22H2

### What arch are you using?

x64

### Expected Behavior

The user can sign in using their username and password.

### Actual Behavior

The user attempts to sign in, the Windows Security "Sign in with your passkey" popup appears, the user clicks Cancel, the cycle repeats.

![Screenshot 2024-02-29 112116](https://github.com/electron/electron/assets/71912904/5bcb9b6e-2599-44ac-80e3-1dcf389d936d)

### Additional Information

Linkedin is the only site this behavior can be observed on. The URL is being loaded through a webview. The following electron settings are in use:
```
const mainWindow = new BrowserWindow({
    icon: __dirname + "/images/favicon.icns",
    webPreferences: {
      webviewTag: true,
      preload: path.join(app.getAppPath(), 'src/scripts/nest.js'),
      nativeWindowOpen: false,
      contextIsolation: true,
      sandbox: false
    },
    maximizable: false,
    frame: false,
    backgroundColor: "#FFF"
  });
```

**Comment by slavochek2** [comment]
yes, would love to see it fixed :)

**Comment by VerteDinde** [comment]
Thanks for reaching out! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. In this specific case, because the issue is specific to LinkedIn's auth page, it's likely either a bug or intended feature of their login flow.

This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by joelwright-dev** [comment]
Is there potential for a feature to be added which can disable these types of popups?

**Comment by joelwright-dev** [comment]
Additionally, this doesn't happen in the chrome browser, this isn't expected functionality from loading this website in the webview, and as such would consider that as a bug.

**Comment by slavochek2** [comment]
Yes, this is not feature of Linkedin. It doesnt happen in other browsers
like chrome. It happens only on latest version of windows with electron.
Whixh is why its an electron bug. I suspect it also happens on any other
authentification page, so its probably not related to LinkedIn
specifically. It relates to electron on latest versions of windows.

If it happens for any login page on latest version of Windows, I guess it
makes it very much worth solving. What do you think?

**Comment by joelwright-dev** [comment]
I agree, this might seem like a specific case that isn't too important to fix but this could cause future issues in applications as this is not expected behavior. I've seen bugs like this reported before and be closed because "its a question". These aren't questions, these are unexpected behaviors we're experiencing, and as far us we can tell, don't have any way of even debugging or implementing a work around.

**Comment by slavochek2** [comment]
@VerteDinde what can we do to appeal and reopen this ticket please? :)

**Comment by joelwright-dev** [comment]
I've also created a post on reddit if you'd like to keep up to date with the thread: [https://www.reddit.com/r/electronjs/comments/1b4ke3g/linkedin_authentication_issues_passkey_popup/](https://www.reddit.com/r/electronjs/comments/1b4ke3g/linkedin_authentication_issues_passkey_popup/)

**Comment by doug-cb** [comment]
I'm also seeing this issue with LinkedIn.  It only occurs with Electron, not with Edge or Chrome

**Comment by joelwright-dev** [comment]
I have an update! After playing around with the requests being sent by Linkedin and blocking certain ones until I got somewhere, I managed to come up with this work around code. Ideally the electron team still implements a way to block this passkey request, however for those in need of a solution for the particular case of Linkedin, let me know if this works:
```javascript
// when a webview is created, add the following code to it
app.on("web-contents-created", (e, wc) => {
  // before a webview makes a request
  wc.session.webRequest.onBeforeRequest((details, callback) => {
    // if the request url matches the url which appears to be sending the passkey request
    if(details.url.includes("checkpoint/pk/initiateLogin")) {
      // log the blocked url
      console.log("\x1b[31m", "Blocked", details.url)
    } else {
      // if the request url doesn't match the misbehaving url, allow the callback as usual
      callback({})
    }
  })
})
```

**Comment by slavochek2** [comment]
@joelwright-dev thanks! we will try this and I will write back if it works :)

**Comment by slavochek2** [comment]
@joelwright-dev You are awesome!! Thank you for sharing! This worked :)

**Comment by joelwright-dev** [comment]
@slavochek2 glad I could come up with the work around 😄 hopefully the team implements something for disabling this properly in a future update

**Comment by Polyline78** [comment]
Works great Joel, thank you so much!

**Comment by ilterkaganocal** [comment]
```

const blockBrowserApis = `      
      if (navigator && navigator.credentials) {
        navigator.credentials.create = async () =>
          Promise.reject(new Error('create() is disabled.'));
        navigator.credentials.get = async () =>
          Promise.reject(new Error('get() is disabled.'));
        navigator.credentials.store = async () =>
          Promise.reject(new Error('store() is disabled.'));
        navigator.credentials.preventSilentAccess = async () =>
          Promise.reject(new Error('preventSilentAccess() is disabled.'));
      }
    }
`;

const didAttachWebviewListener = (event, webContents) => {
  const webviewSession = webContents.session;
  const didFrameNavigateListener = (event, url, code, status, isMainFrame, frameProcessId, frameRoutingId) => {

    const frame = webFrameMain.fromId(frameProcessId, frameRoutingId);
    if (frame && !frame.detached) {
      webContents.setAudioMuted(true);
      frame.executeJavaScript(blockBrowserApis).catch(e => {
        // console.log('error when executeJavaScript did-frame-navigate blockBrowserApis', e);
      });
    }
  }

  const didFrameFinishLoadListener = (event, isMainFrame, frameProcessId, frameRoutingId) => {
    const frame = webFrameMain.fromId(frameProcessId, frameRoutingId);
    if (frame && !frame.detached) {
      webContents.setAudioMuted(true);
      frame.executeJavaScript(blockBrowserApis).catch(e => {
        // console.log('error when executeJavaScript did-frame-finish-load blockBrowserApis', e);
      });
    }
  }
  webContents.on('did-frame-navigate', didFrameNavigateListener);
  webContents.on('did-frame-finish-load', didFrameFinishLoadListener);
}

const myWindow = new BrowserWindow({});
myWindow.webContents.on('did-attach-webview', didAttachWebviewListener);
```

Here is my solution that overrides the chrome `navigator.credentials` API by executing JS on `webview` evertime it navigates to a new webpage. 

For some reason this javascript does not work when I put it into a preloaded script for the webview, it works if I inject it later.

**Comment by panther7** [comment]
@ilterkaganocal Script doesn't works in latest Electron. Tested on https://www.linkedin.com/login

**Comment by panther7** [comment]
@ilterkaganocal 

New code, works (blocking), tested on LinkedIn and Electron 40:
```ts
// view is `Electron.WebContentsView`

const isBlockedId = crypto.randomUUID();
const blockCredentialsApiCode = `
    (() => {
        if (typeof window === 'undefined' || window['_${isBlockedId}'] === true) return;
        window['_${isBlockedId}'] = true;

        if (typeof navigator !== 'undefined' && navigator.credentials) {
            Object.keys(CredentialsContainer.prototype).forEach((method) => {
                let firstCall = true;
                Object.defineProperty(navigator.credentials, method, {
                    value: async () => {
                        await new Promise((resolve) => setTimeout(resolve, firstCall ? 0 : 10_000));
                        firstCall = false;
                        throw new DOMException('The user agent does not support public key credentials.', 'NotSupportedError');
                    },
                    configurable: true,
                    writable: true,
                });
            });
        }
    })();
`;
view.webContents.on('did-frame-navigate', () => {
    view.webContents.executeJavaScript(blockCredentialsApiCode).catch((err) => {
        console.error('error when executeJavaScript did-frame-navigate blockCredentialsApiCode', err);
    });
});
view.webContents.on('did-frame-finish-load', () => {
    view.webContents.executeJavaScript(blockCredentialsApiCode).catch((err) => {
        console.error('error when executeJavaScript did-frame-finish-load blockCredentialsApiCode', err);
    });
});
```

**Comment by panther7** [comment]
@ilterkaganocal ok, i tried in preload script and works. Tested on [linkedin.com](https://www.linkedin.com/login) and Electron 40.

preload.js
```js
import { webFrame } from 'electron';

const blockCredentialsApiCode = `
(() => {
    Object.defineProperty(navigator, 'credentials', {
        value: undefined,
        configurable: true,
        writable: true,
    });
})()`;

webFrame.executeJavaScript(blockCredentialsApiCode).catch((err) => {
    console.error('error when executeJavaScript for blockCredentialsApiCode', err);
});
```

**Comment by Agritite** [comment]
Apparently this isn't a problem exclusive to linkedin, but all webpages that uses webauthn. It seems like this can be disabled by adding `--disable-features=WebAuthenticationUseNativeWinApi` when launching electron, a very obscure feature flag that nonetheless exists according to

https://github.com/cefsharp/CefSharp/discussions/4051,

https://issues.chromium.org/issues/40740046, and

https://source.chromium.org/chromium/chromium/src/+/main:device/fido/public/features.cc;l=59?q=WebAuthenticationUseNativeWinApi&ss=chromium
