### ISSUE TITLE
[Bug]: crash on File > Quit on Linux

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#41486]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.4 LTS

### What arch are you using?

x64

### Expected Behavior

No crashes on File > Quit.

### Actual Behavior

Consistent crash with the following stack trace:
```0 electron 0x000055aa16b4c91d base::AtExitManager::ProcessCallbacksNow()
1 electron 0x000055aa16b4c6e9 base::AtExitManager::~AtExitManager()
2 electron 0x000055aa1362d441 content::ContentMainRunnerImpl::Shutdown()
3 electron 0x000055aa1362a785 content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*)
4 electron 0x000055aa1362a87f content::ContentMain(content::ContentMainParams)
5 electron 0x000055aa13336577 main
6 electron 0x000055aa1b7e1dff _fini
7 electron 0x000055aa1b0ac457 _fini
8 electron 0x000055aa1b7e1ebf _fini
9 ld-linux-x86-64.so.2 0x00007fb1b7c9203f memset
10 libc.so.6 0x00007fb1b5c29d8f __libc_start_call_main
11 electron 0x000055aa1333641f lstat64
12 electron 0x000055aa1333641f lstat64
13 ld-linux-x86-64.so.2 0x00007fb1b7c9203f memset
14 libc.so.6 0x00007fb1b5c29e3f __libc_start_main_impl
15 electron 0x000055aa12f38fff () + 0
16 electron 0x000055aa12f39029 _start
```

**Comment by codebytere** [comment]
@indutny-signal is that the very top of the stacktrace? that looks like a snippet - it'd help to have a bit more! esp what type of crash e.g. bad access

**Comment by indutny-signal** [comment]
We changed the way we collect crash dumps, but I'm pretty sure that's the top. Here's the crash info:

```json
  "crash_info": {
    "address": "0x000000c401010109",
    "adjusted_address": null,
    "assertion": null,
    "crashing_thread": 0,
    "instruction": null,
    "memory_accesses": null,
    "possible_bit_flips": null,
    "type": "SIGSEGV / SEGV_ACCERR"
  },
```

Electron module:
```json
    {
      "base_addr": "0x0000556409b1d000",
      "cert_subject": null,
      "code_id": "f2911e948bd3396745a9a0ef127d99fd79fe7e09",
      "corrupt_symbols": false,
      "debug_file": "signal-desktop-alpha",
      "debug_id": "941E91F2D38B673945A9A0EF127D99FD0",
      "end_addr": "0x0000556414388108",
      "filename": "signal-desktop-alpha",
      "loaded_symbols": false,
      "missing_symbols": true,
      "symbol_url": null,
      "version": "0.0.0.0"
    },
```

**Comment by indutny-signal** [comment]
I think one of the AtExit handlers is just garbage?
