### ISSUE TITLE
[Bug]: Docs: Some webContents listeners has errors in TypeSript

### ISSUE THREAD

**Issue by panther7** [electron/electron#41482]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Expected Behavior

No error.

### Actual Behavior

Typescript error on some event listeners.

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '"close"' is not assignable to parameter of type '"zoom-changed"'.ts(2769)
electron.d.ts(13879, 5): The last overload is declared here.
```

![2024-02-29 16 57 12](https://github.com/electron/electron/assets/3808250/0b793417-8b78-4a84-a234-28a1354b5a2d)

### Additional Information

Visual Studio Code v1.87.0
TypeScript v5.3.3

```js
import { BrowserView } from 'electron';

const view = new BrowserView();

view.webContents.on('focus', () => {});
view.webContents.on('close', () => {});
view.webContents.on('closed', () => {});
view.webContents.on('blur', () => {});
```

**Comment by codebytere** [comment]
Yes - that's because `close` and `closed` aren't valid `webContents` events. Maybe you were trying to listen for those events on BrowserWindow?

**Comment by panther7** [comment]
@codebytere I think, that is valid.

If you call
```ts
view.webContents.close();
```

then close event will be emit
```ts
view.webContents.on('close', () => console.log('close event'));
```

We must using for detect "closing" browser views.
