### ISSUE TITLE
[Bug]: screen.getCursorScreenPoint() not works on linux, KDE

### ISSUE THREAD

**Issue by STRRL** [electron/electron#41496]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.0

### What operating system are you using?

Other Linux

### Operating System Version

archlinux

### What arch are you using?

x64

### Last Known Working Electron version

28.2.5

### Expected Behavior

everytime I call `screen.getCursorScreenPoint()`, it could return the position of mouse 

### Actual Behavior

only the very first time I call `screen.getCursorScreenPoint()`, it would return the right position. on the next calls, it would always return the same value as the first call returned, regardless how I move the mouse

**Comment by ak47me** [comment]
Hey @STRRL , I have experience with javascript and would love to resolve this bug. Can I please be assigned to solve the bug?thank you

**Comment by Maniiisha-sachdeva** [comment]
Hello @STRRL ,I'm interested in resolving the given issue, with your permission, I'd like to work on resolving this issue and submit a pull request for your review.
