### ISSUE TITLE
[Bug]: BrowserWindow Preload Doesn’t Preload MJS Files

### ISSUE THREAD

**Issue by elliot-huffman** [electron/electron#41498]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Expected Behavior

Loads the preload script as expected.

### Actual Behavior

Ignores it and doesn't run the script.

### Additional Information

CJS files work fine.
MJS files are ignored.
This prevents usage of features like IPC bridging in projects that use modern module frameworks like ESM.
I had to revert my files to use CJS since they weren't executing.

**Comment by erickzhao** [comment]
> there is no code repro needed

Sorry to bother you @elliot-huffman, but could you attach a minimal repro with the bug report? I wanted to test this out by forking the electron-quick-start repo to test this out, but I was able to successfully load `preload.mjs` just fine.

https://github.com/electron/electron-quick-start/commit/8234be99cde7018dd01967386f943fcb6350996d

<img width="912" alt="image" src="https://github.com/electron/electron/assets/16010076/64400227-f92b-4dc2-a783-2ac846fbd7e8">

**Comment by elliot-huffman** [comment]
Will do, sorry about the inconvenience

**Comment by elliot-huffman** [comment]
I wasn't able to repro in electron fiddle but can in my project, I will re-visit my project and go from there.
