### ISSUE TITLE
[Bug]: Performance issues with contextBridge

### ISSUE THREAD

**Issue by iptop** [electron/electron#41511]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.9.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Expected Behavior

Because function calls through contextBridge actually involve parameter passing by copying, this leads to poor performance in scenarios with large amounts of data.

# preload.js

```javascript
const { contextBridge, ipcRenderer } = require('electron')
let arr = new ArrayBuffer(1080 * 1920 * 4)
function testFunc (cb) {
  cb(arr)
}

contextBridge.exposeInMainWorld('electron', {
  testFunc
})


```

# WEB.js
```javascript
let s = (new Date()).getTime()
window.electron.testFunc(()=>{
  let e = (new Date()).getTime()
  console.log(e-s) // 10ms
})
```

### Actual Behavior

I hope there is a way, like postMessage, to transfer control and avoid a large amount of data copying.

**Comment by Prinzhorn** [comment]
First [search result](https://github.com/search?q=repo%3Aelectron%2Felectron+contextBridge+transfer&type=issues) I found https://github.com/electron/electron/issues/27024

So you _can_ use `postMessage` between renderer and the preload script.

> The main reason to use contextBridge is for synchronous messaging between the isolated world and main world. If you don't need synchronous messaging, window.postMessage works just as well.

https://github.com/electron/electron/issues/27024#issuecomment-745589923

**Comment by iptop** [comment]
@Prinzhorn Your response successfully solved my problem.However, I have a question. Since it's supposed to be context isolated, why can the preload.js file access the same window object as the rendering process？

**Comment by Prinzhorn** [comment]
Read the linked issue:

https://github.com/electron/electron/issues/27024#issuecomment-745618327
