### ISSUE TITLE
Empty title bar of fullscreen Frameless window

### ISSUE THREAD

**Issue by Rokt33r** [electron/electron#4151]
I emulated traffic lights by CSS&HTML. But, when I set the window fullscreen, empty title bar block to click the emulated buttons.

Is it intended?

<img width="158" alt="screen shot 2016-01-19 at 9 23 48" src="https://cloud.githubusercontent.com/assets/5865853/12406238/97c3cabe-be8e-11e5-9eb4-3dc14a0d510c.png">

process.versions
```
ares: "1.10.1-DEV"
atom-shell: "0.36.4"
chrome: "47.0.2526.73"
electron: "0.36.4"
http_parser: "2.6.0"
modules: "47"
node: "5.1.1"
openssl: "1.0.2e"
uv: "1.7.5"
v8: "4.7.80.27"
zlib: "1.2.8"
```

<img width="189" alt="screen shot 2016-01-18 at 6 49 10" src="https://cloud.githubusercontent.com/assets/5865853/12406285/02f4d6ca-be8f-11e5-9b7e-f526ee00a0b9.png">

**Comment by zcbenz** [comment]
Can you provide the code that creates the window?

**Comment by Rokt33r** [comment]
This is my code.
```
var mainWindow = new BrowserWindow({
  width: 1080,
  height: 720,
  zoomFactor: 1.0,
  webPreferences: {
    blinkFeatures: 'OverlayScrollbars'
  },
  frame: false
})
```

And, Nylas N1 also has same problem.

<img width="229" alt="screen shot 2016-01-20 at 5 48 07" src="https://cloud.githubusercontent.com/assets/5865853/12431554/71a928b4-bf39-11e5-8da4-47d1bc6b731d.png">

Is it possible to remove empty title bar or show traffic icons?
