### ISSUE TITLE
[Bug]: Desktop Capturer window recording has low fps

### ISSUE THREAD

**Issue by vvillaluna** [electron/electron#41524]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Recording using window (specific window) should be smoother depending on the constraint that was passed like 60fps.

### Actual Behavior

Recording using window (specific window) is very laggy or low fps. But recording the entire screen is very smooth compared to window recording.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
