### ISSUE TITLE
[Bug]: Node.js fs.readdir new param recursive caused bug

### ISSUE THREAD

**Issue by jiawei397** [electron/electron#41549]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.4

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.2.1

### What arch are you using?

x64

### Expected Behavior

When I use `fs/promises.readdir` with params `withFileTypes` and  `recursive`, expect get real list of directory.

```js
const fs = require("fs/promises");

const files = await fs.readdir(dir, { 
  withFileTypes: true,
  recursive: true
});
```

And the same is:
```js
const fs = require("fs");

fs.readdir(
    dir,
    {
      withFileTypes: true,
      recursive: true
    },
    (err, files) => {
      if (err) {
        console.error('Error:', err)
      } else {
        console.log('Node:', process.version)
        console.log('files:', files.length)
      }
    }
  )
```

Also is `readdirSync`:

```js
const fs = require('fs')

const files = fs.readdirSync(dir, {
  withFileTypes: true,
  recursive: true
})
console.log('Node:', process.version)
console.log('files:', files.length)
```

### Actual Behavior

The electron version `27.0.4` get the list length is `2`

### Additional Information

I have found [the cause of the issue](https://github.com/nodejs/node/commit/7c758f60ab#diff-9b2c5bf36570be7a09ba2597abdf6d9bc2cc1e19866b6674b0cf275c1188dcad). It is a bug starting from Node.js `v18.17.0`, which was only fixed in `v18.19.0`. Since Electron started using `Node.js v20` in version `v29`, the earlier versions using `v18.17.1` all had issues.

Furthermore, as Node.js `fs.readdir` already supports the recursive parameter, it is not supported in `lib/node/asar-fs-wrapper.ts`. Therefore, there will be a bug when packaging if it is an internal file (when `isAsar` is true).

```ts
const { readdir } = fs;
fs.readdir = function (pathArgument: string, options?: { encoding?: string | null; withFileTypes?: boolean } | null, callback?: Function) {
    const pathInfo = splitPath(pathArgument);
    if (typeof options === 'function') {
      callback = options;
      options = undefined;
    }
    if (!pathInfo.isAsar) return readdir.apply(this, arguments);
    const { asarPath, filePath } = pathInfo;

    const archive = getOrCreateArchive(asarPath);
    if (!archive) {
      const error = createError(AsarError.INVALID_ARCHIVE, { asarPath });
      nextTick(callback!, [error]);
      return;
    }

    const files = archive.readdir(filePath);
    if (!files) {
      const error = createError(AsarError.NOT_FOUND, { asarPath, filePath });
      nextTick(callback!, [error]);
      return;
    }

    if (options?.withFileTypes) {
      const dirents = [];
      for (const file of files) {
        const childPath = path.join(filePath, file);
        const stats = archive.stat(childPath);
        if (!stats) {
          const error = createError(AsarError.NOT_FOUND, { asarPath, filePath: childPath });
          nextTick(callback!, [error]);
          return;
        }
        dirents.push(new fs.Dirent(file, stats.type));
      }
      nextTick(callback!, [null, dirents]);
      return;
    }

    nextTick(callback!, [null, files]);
  };

  fs.promises.readdir = util.promisify(fs.readdir);
  ```

The cause of this issue lies in a bug in `fs.readdir`, but in fact, the original `fs.promises.readdir` is not problematic. It is a separate implementation from `fs.readdir`, so the bug occurred in the above code due to the usage of `fs.promises.readdir = util.promisify(fs.readdir);`.

Moreover, the native `fs.readdir` may have performance issues when used recursively, as mentioned [here](https://github.com/nodejs/node/issues/51749). Please be aware of this if you intend to support it.

**Comment by Brandontam29** [comment]
Also has been broken for me for a few months already.

### Electron Version
28.2.6

### Operating System Version
Windows 11: WSL 2 Ubuntu 22.04

### What arch are you using?
x64

**Comment by frankalbenesius** [comment]
Just ran into this, too. Thank you for filing an issue. Took me forever to realize it wasn't something I was doing wrong.
