### ISSUE TITLE
[Bug]: Schemes not respected.

### ISSUE THREAD

**Issue by jmercouris** [electron/electron#41548]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.4.0

### What operating system are you using?

Other Linux

### Operating System Version

NixOS

### What arch are you using?

x64

### Expected Behavior

When a scheme is set to stream: true, it should allow streaming of a resource. When a scheme is set to stream: false, it should disable streaming of a resource.

### Actual Behavior

The opposite behavior is observed.

### Testcase Gist URL

https://gist.github.com/jmercouris/fca7cba9d8e6b30a2f861268a3180cff

**Comment by fuwad121** [comment]
It seems the streaming behavior is the opposite of what's expected. I think flipping the stream property for each scheme could fix it :  true for enable, false for disable in main.js
But, I could be mistaken.

**Comment by jmercouris** [comment]
Another thing; when I set `standard` to `true` and `false` the dispatch of schemes will change. For example `a:` will dispatch on a standard scheme, but `a:asdf` will NOT dispatch on a standard scheme. This is what we may in fact be observing here.

**Comment by codebytere** [comment]
@jmercouris see https://github.com/electron/electron/issues/41032 (which you were tagged in i think?)

**Comment by jmercouris** [comment]
I agree, it should probably be removed. However, there is an important point above within this issue that has not been addressed. 

```
When I set standard to true and false the dispatch of schemes will change. For example a: will dispatch on a standard scheme, but a:asdf will NOT dispatch on a standard scheme. This is what we may in fact be observing here.
```

Please don't close issues unless the problems have been addressed. There is still a very deep bug that dispatch won't happen for 'standard' schemes when the URL appears to be malformed.

**Comment by jmercouris** [comment]
Perhaps I should open up a new issue for this.

**Comment by codebytere** [comment]
@jmercouris i hear you but the initial issue is a duplicate of an open one - i folded it into that issue which remains open. the second comment you made:

> https://github.com/electron/electron/issues/41548#issuecomment-1987598518

is a different issue. I can re-open this issue if you change the PR body to reflect that as the primary issue you'd like investigated.

**Comment by jmercouris** [comment]
I've created a new issue https://github.com/electron/electron/issues/41601
