### ISSUE TITLE
[Bug]: The filters of showOpenDialog in dialog do not work properly

### ISSUE THREAD

**Issue by TinsFox** [electron/electron#41550]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.0 and 26.6.0 and 28.2.1

### What operating system are you using?

macOS

### Operating System Version

14.3

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I want to open the dialog window and be able to select two types of files, video and picture.

### Actual Behavior

When I set filters, I can only select one type of file. Only the first filter in the filters array will take effect, and the second filter will be invalid. This means that I can only select videos or files (depending on the order of the elements in the filters array).

Here is a demo [video](https://buckets.tinsfox.com/Export-1709878303115.mp4)

### Testcase Gist URL

https://gist.github.com/TinsFox/85bbb79c85df961c39183d79942360e5

**Comment by codebytere** [comment]
@TinsFox - this is working as intended. The selected filter index allows only the file specified in that array. To change what filter is active, you needed to click "show options":

<img width="805" alt="Screenshot 2024-03-11 at 5 09 41 PM" src="https://github.com/electron/electron/assets/2036040/d74c77cf-e2ba-4978-969b-30aa487330b2">

If you wanted both for one index, you could do:

```js
filters: [
          { name: 'Media', extensions: ['mkv', 'avi', 'mp4', 'jpg', 'png', 'gif'] },
          { name: 'All Files', extensions: ['*'] }
        ]
```

**Comment by TinsFox** [comment]
@codebytere  Oh thank you very much, I never noticed this before.
