### ISSUE TITLE
[Bug]: autoUpdater crashes app for largest files >1GB

### ISSUE THREAD

**Issue by viplifes** [electron/electron#41555]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.1

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Allow autoUpdater work with update files over 1Gb

### Actual Behavior

Applications crash in development and production modes

### Testcase Gist URL

https://github.com/viplifes/electron_app_crash_large_update/tree/main

### Additional Information

The autoUpdater crashes the application if the update size exceeds 1GB. 

I created a demo project to showcase this issue. 
**It's not a full-fledged update** but merely a demonstration that if the file size exceeds `1073741824 bytes`, the application will crash.

You can find the demo project here: https://github.com/viplifes/electron_app_crash_large_update/tree/main

Just need to run the commands:
```
yarn
yarn start
```

In this file you can simply specify the desired file size in bytes
https://github.com/viplifes/electron_app_crash_large_update/blob/main/src/update.ts#L6

If we specify `1073741824 bytes`, we will see in the logs:
```
/download finish
2024-03-09 12:08:26.690 Electron[88531:871284] Download completed to: file:///Users/dimir/Library/Caches/com.github.Electron.ShipIt/update.YQwiIil/download
```
And the application will continue to work

If we specify `>= 1073741825 bytes`, **the application will crash** and these lines will no longer be in the logs

Is this an Electron problem? Or perhaps there is a way to increase the allowed size of update files?

**Comment by ap4499** [comment]
Did you find a solution to this btw?
