### ISSUE TITLE
[Bug]: Breaking changes in Electron 23 version for net library network calls (Server is no more receiving the cookie whenever 302 redirect happen in server side)

### ISSUE THREAD

**Issue by reetesha** [electron/electron#41560]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

Windows

### Operating System Version

Window 10

### What arch are you using?

x64

### Last Known Working Electron version

22.0.0

### Expected Behavior

Whenever server is doing 302 redirect electron version should send the cookie ...In electron version 22 its working as expected.

**Steps to reproduce**

1. Server is no more receiving cookie in electron 23 version whenever the api is doing 302 redirect, 
2. Electron 22 version is sending the cookie properly ...Please note you need to enable 302 redirect whenever you want to replicate the issue. 
3. Below are code which i using - 

<img width="863" alt="image" src="https://github.com/electron/electron/assets/5560623/6c72402e-55cc-4ecc-b8bc-3e224aa29285">

Please let me know if you need more details

### Actual Behavior

Whenever server is doing 302 redirect electron version should send the cookie. 
In electron version 22 its working as expected.

### Testcase Gist URL

https://github.com/reetesha/electron/tree/main

### Additional Information

 Breaking changes in Electron 23 version for net library network calls. ( Server is no more receiving the cookie whenver 302 redirect happen in server side)

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
