### ISSUE TITLE
[Bug]: Badge not displaying content correctly

### ISSUE THREAD

**Issue by guendev** [electron/electron#41565]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

28.2.6

### Expected Behavior

The badge icon should display the provided count (e.g., "10") as its content.

### Actual Behavior

The badge icon displays only a dot instead of the provided count.

### Additional Information

https://www.electronjs.org/docs/latest/api/app#appsetbadgecountcount-linux-macos

**Comment by ayumi-signal** [comment]
I've noticed this as well. Although `setBadgeCount()` doesn't officially support Windows, it was nice to share the same badging code between platforms. If it were fixed it would be helpful.
