### ISSUE TITLE
[Bug]: On a Mac, animations rendered in gif or threejs always leave a white semi-transparent background

### ISSUE THREAD

**Issue by SorryToPerson** [electron/electron#41564]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.1

### What operating system are you using?

macOS

### Operating System Version

Sonama 14

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

29.1.1

### Expected Behavior

When I use electron to build an application, I want to create a transparent, animated character with actions, to be displayed on the desktop for a long time as an assistant image. But whether using gif or threejs rendering, there is always a semi-transparent white background of historical actions on the Mac computer, which is very frustrating.

### Actual Behavior

When I use electron to build an application, I want to create a transparent, animated character with actions, to be displayed on the desktop for a long time as an assistant image. But whether using gif or threejs rendering, there is always a semi-transparent white background of historical actions on the Mac computer, which is very frustrating.

### Testcase Gist URL

https://gist.github.com/SorryToPerson/0b489bc47738fb0bbcbaca29e2482536

**Comment by fauzank339** [comment]
I tried different methods seems like a issue either with electron or Mac have you tried this on windows?

**Comment by SorryToPerson** [comment]
> I tried different methods seems like a issue either with electron or Mac have you tried this on windows?
> 

On the Windows platform, this issue was not found. 
There is also a problem on the mac platform. When the width or height of the window is less than 160, the transparency function fails, and the white background cannot be eliminated. This issue does not exist on Windows.

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
