### ISSUE TITLE
[Bug]: In Electron 19, iframe inside a browserWindow has big content render lag compared with DOM content when in put background or invisible.

### ISSUE THREAD

**Issue by yurychika** [electron/electron#41562]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.10

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

When browser window is not visible and put in background, the iframe inside it should still render correctly. 
When browser window is focused again, the iframe should render immediately showing the up-to-date content.

### Actual Behavior

When browser window is not visible and put in background, the JS is excuted correctly and we could see log that **React** widget's **hook** is triggered with correct prop.

When browser window is focused again, the **iframe** spend more than **10** to **30** s to render the page to the correct state. Which makes me feel that somehow the **browserWindow** or iframe is sleeping and spend long time to get back to normal.

This is not always reproducible, and has around 10% chances to be hit. The app inside the iframe is a ticking app and update itself pretty frequently.

### Additional Information

Wonder if it'sto be related to https://issues.chromium.org/issues/40786336.

**Comment by codebytere** [comment]
@yurychika Electron 19 is no longer supported and has not been for some time. Unless this issue is demonstrated to occur on a [currently supported version](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) it will be closed in 10 days.

**Comment by yurychika** [comment]
@codebytere  thanks for the quick response!
Is there any workaround for this issue?  Or is there any similar reports? If we suspected it's realted to https://issues.chromium.org/issues/40786336, is there an easy way to turn this feature off  in electron 19 which seems to be using the chrome 102 which is the same version mentioned in the previous link.

I'm asking since we are not in a position to upgrade to newer version for now, while we need the issue to be solved for the clients.
