### ISSUE TITLE
[Feature Request]: Callback to be notified when "tile memory limits exceeded"

### ISSUE THREAD

**Issue by theogravity** [electron/electron#41578]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Our app may contain a lot of items to render on our "canvas" (as in not a `canvas` element) and in electron, we'll hit the `tile memory limits exceeded, some content may not draw` warning when doing certain actions. We can probably apply a lot of different techniques (such as hiding certain items during a transition / animation), but it would help to know that the user is encountering the issue so we can limit how we render objects.

### Proposed Solution

Probably something like `app.on('tile-memory-limit-warning', <callback>)`, where `<callback>` may contain some information relating to the limit if possible.

Can also be against a `BrowserWindow` if this error is renderer-specific.

### Alternatives Considered

Don't think there is any based on my research.

**Comment by Maniiisha-sachdeva** [comment]
here is the solution....
// Implement event listener for 'tile-memory-limit-warning'
app.on('tile-memory-limit-warning', (info) => {
    // Notify user about the memory limit issue
    showNotification("Memory Limit Warning", "The application has encountered memory limits. Some content may not be fully rendered.");

    // Adjust rendering settings dynamically
    adjustRendering();

    // Implement further optimization techniques if necessary
    optimizeMemoryUsage();
});

// Function to show user-friendly notification
function showNotification(title, message) {
    // Implement notification mechanism (e.g., using Electron's dialog API or custom UI component)
}

// Function to adjust rendering settings
function adjustRendering() {
    // Implement logic to dynamically adjust rendering settings
}

// Function to optimize memory usage
function optimizeMemoryUsage() {
    // Implement optimization techniques to manage memory more efficiently
}

**Comment by codebytere** [comment]
Hi @theogravity - as this is a Chromium bug, it's not something we'd intentionally add a feature for. There are quite a few bugs [filed upstream about it](https://issues.chromium.org/issues?q=%22tile%20memory%20limits%20exceeded%22) - I'd recommend commenting there or creating a new issue to get this resolved upstream rather than within Electron itself.

**Comment by ZONEZH** [comment]
I also have the same application scenario and the same error message as you. In the end, I went to Google to see the issue and there were related error descriptions, but there was no good solution. How did you solve it in the end

**Comment by theogravity** [comment]
> I also have the same application scenario and the same error message as you. In the end, I went to Google to see the issue and there were related error descriptions, but there was no good solution. How did you solve it in the end

Optimize your app to not perform unnecessary re-renders is one.

**Comment by ZONEZH** [comment]
Okay, thank you, but our app does have a preview of this large canvas. I haven't even drawn a canvas yet. When I created this 10000px width and height window through an electron, the console reported this error

**Comment by ZONEZH** [comment]
> > I also have the same application scenario and the same error message as you. In the end, I went to Google to see the issue and there were related error descriptions, but there was no good solution. How did you solve it in the end
> 
> Optimize your app to not perform unnecessary re-renders is one.

Okay, thank you, but our app does have a preview of this large canvas. I haven't even drawn a canvas yet. When I created this 10000px width and height window through an electron, the console reported this error

**Comment by theogravity** [comment]
Sounds like it's just out of memory

You can use this event in the main process to see why it's crashing:

https://www.electronjs.org/docs/latest/api/app#event-render-process-gone

**Comment by ThaUnknown** [comment]
even with fully GPU only paints this issue can occur, the simplest fix is forcefully increasing GPU memory: `--force-gpu-mem-available-mb=4096`, d3d11 is also known to have issues on chromium you could try forcing angle via `--use-angle=d3d9`, but that overrides the 'default' setting for angle, which dynamically detects the available angle backend, which means if the device doesn't support d3d9, then the app wont boot ^^
