### ISSUE TITLE
[Feature Request]: 期望设置的maxWidth及maxHeight超出当前window的size时，maximize 方法和setFullScreen方法可以应用该最大宽度及高度

### ISSUE THREAD

**Issue by lilix00** [electron/electron#41597]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

当我期望窗体可以铺满两个显示器时，只需要setMaximumSize即可正常适用maximize 方法和setFullScreen方法。不期望electron限制 最大化 及 全屏 的宽度高度为当前window的size。

### Proposed Solution

提供设置 最大化及全屏的大小不受当前window的限制，取maxWidth及maxHeight

### Alternatives Considered

手动setBounds

**Comment by codebytere** [comment]
https://github.com/electron/electron/issues/41595#issuecomment-1998011791
