### ISSUE TITLE
[Bug]: Schemes dispatch inconsistent

### ISSUE THREAD

**Issue by jmercouris** [electron/electron#41601]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0

### What operating system are you using?

Other Linux

### Operating System Version

NixOS

### What arch are you using?

x64

### Expected Behavior

I expect either BOTH windows to render, or NEITHER window to render.

### Actual Behavior

One of the two windows renderers.

### Testcase Gist URL

https://gist.github.com/jmercouris/5682e62e11b73c8b2e99c303d51eacd0

### Additional Information

If you change the URL for both URLs to something like:

`a:asdf`

and

`b:sdf`

it will work.

**Comment by jmercouris** [comment]
If setting the scheme privileges to `standard` is supposed to elicit this behavior, I believe it should be more clearly documented.

**Comment by dsanders11** [comment]
@jmercouris, this is expected behavior. You're registering the scheme as `standard` and then trying to load a URI which does not conform to the expected syntax. From the docs:

> A standard scheme adheres to what RFC 3986 calls [generic URI syntax](https://tools.ietf.org/html/rfc3986#section-3). For example http and https are standard schemes, while file is not.

If you change the URl to `a://foobar`, which adheres to the generic URI syntax, it works fine.

**Comment by jmercouris** [comment]
However, it isn't documented clearly. I think it could be more thoroughly explained.
