### ISSUE TITLE
[Bug]: win11 election: 29.1.4  Print PDF using printWindow. webContents.print, all pages are blank

### ISSUE THREAD

**Issue by gaoshan001** [electron/electron#41624]
### Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.4

### What operating system are you using?

Windows

### Operating System Version

windows11

### What arch are you using?

x64

### Last Known Working Electron version

29.1.4

### Expected Behavior

This bug can be fixed, PDF can print normally using this method

### Actual Behavior

 printWindow.webContents.print({ silent: false, printBackground: true }, (success, errorType) => {

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
