### ISSUE TITLE
[Bug]: Desktop capturer thumbnails are generated in a low quality

### ISSUE THREAD

**Issue by MaximKalinin** [electron/electron#41630]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.4 (23E214)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

29.0.1

### Expected Behavior

Thumbnails are generated with a good quality. (example from electron 29.0.1)
![image](https://github.com/electron/electron/assets/22202138/42115640-ce22-40d4-b3dc-2586148aac1e)

### Actual Behavior

Thumbnails are generated blurry.
![image](https://github.com/electron/electron/assets/22202138/d078749f-a3cd-45cd-ada3-6c990ea658aa)

### Testcase Gist URL

https://gist.github.com/7944bd3381db8d1cf6d7a4eca86b073e

**Comment by codebytere** [comment]
@MaximKalinin have you given your app permission to screen record?

**Comment by MaximKalinin** [comment]
> @MaximKalinin have you given your app permission to screen record?

Yes, I did.

**Comment by ganning127** [comment]
Has there been a solution to this? I'm facing the same issue

**Comment by Galkon** [comment]
> Has there been a solution to this? I'm facing the same issue

You can upgrade to electron 30 or downgrade to electron 28.

**Comment by codebytere** [comment]
@Galkon theres been a solution - it's been backported to 29
and should go out with the next release

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/42049
