### ISSUE TITLE
[Bug]: autoUpdater for macOS doesn't respect to proxy-server settings

### ISSUE THREAD

**Issue by clouds56** [electron/electron#41643]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.12

### What operating system are you using?

macOS

### Operating System Version

macOS 13.0

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When open app using `--proxy-server=...` the autoUpdater should use the proxy as well.

### Actual Behavior

Other part of electron works well with the proxy-server, except autoUpdater.

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.

**Comment by clouds56** [comment]
I did a quick research and believe it is still the issue for the `main` branch.
I tracked down into autoUpdater and seems we electron just delegate the request to [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac), or in case of win, [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows).
The Squirrel updater only respect to system proxy for both platform. Related issue https://github.com/Squirrel/Squirrel.Mac/issues/200#issuecomment-306267302 and https://github.com/Squirrel/Squirrel.Windows/issues/657

**Comment by clouds56** [comment]
I know this is hard to do a workaround in electron. So just record for others to reference for other developers, it might be a good idea to use [electron-updater](https://github.com/electron-userland/electron-builder) on Mac as mentioned in the comment in the issue of Squairrel.Mac.
