### ISSUE TITLE
[Bug]: 无法结局！！

### ISSUE THREAD

**Issue by renjiali** [electron/electron#41644]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0

### What operating system are you using?

Windows

### Operating System Version

win11

### What arch are you using?

x64

### Last Known Working Electron version

16

### Expected Behavior

  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=8.236s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855.7z
    --
    Path = C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2

    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855\darwin\10.12\lib\libcrypto.dylib       
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855\darwin\10.12\lib\libssl.dylib

                    command='C:\Users\renjiali\Desktop\demo\electron-app\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855.7z' '-oC:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855'
                    workingDir=C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign     
  • Above command failed, retrying 3 more times
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=7.27s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755.7z
    --
    Path = C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2

    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755\darwin\10.12\lib\libcrypto.dylib       
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755\darwin\10.12\lib\libssl.dylib

                    command='C:\Users\renjiali\Desktop\demo\electron-app\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755.7z' '-oC:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755'
                    workingDir=C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign     
  • Above command failed, retrying 2 more times

### Actual Behavior

  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=8.236s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855.7z
    --
    Path = C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2

    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855\darwin\10.12\lib\libcrypto.dylib       
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855\darwin\10.12\lib\libssl.dylib

                    command='C:\Users\renjiali\Desktop\demo\electron-app\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855.7z' '-oC:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855'
                    workingDir=C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign     
  • Above command failed, retrying 3 more times
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=7.27s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755.7z
    --
    Path = C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2

    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755\darwin\10.12\lib\libcrypto.dylib       
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755\darwin\10.12\lib\libssl.dylib

                    command='C:\Users\renjiali\Desktop\demo\electron-app\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755.7z' '-foC:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755'
                    workingDir=C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign     
  • Above command failed, retrying 2 more times

### Testcase Gist URL

dfffffffff

### Additional Information

  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=8.236s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855.7z
    --
    Path = C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2

    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855\darwin\10.12\lib\libcrypto.dylib       
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855\darwin\10.12\lib\libssl.dylib

                    command='C:\Users\renjiali\Desktop\demo\electron-app\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855.7z' '-oC:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\498850855'
                    workingDir=C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign     
  • Above command failed, retrying 3 more times
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=7.27s
  ⨯ cannot execute  cause=exit status 2
                    out=
    7-Zip (a) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

    Scanning the drive for archives:
    1 file, 5635384 bytes (5504 KiB)

    Extracting archive: C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755.7z
    --
    Path = C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755.7z
    Type = 7z
    Physical Size = 5635384
    Headers Size = 1492
    Method = LZMA2:24m LZMA:20 BCJ2
    Solid = +
    Blocks = 2

    Sub items Errors: 2

    Archives with Errors: 1

    Sub items Errors: 2

                    errorOut=ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755\darwin\10.12\lib\libcrypto.dylib       
    ERROR: Cannot create symbolic link : �ͻ���û����������Ȩ�� : C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755\darwin\10.12\lib\libssl.dylib

                    command='C:\Users\renjiali\Desktop\demo\electron-app\node_modules\7zip-bin\win\x64\7za.exe' x -bd 'C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755.7z' '-oC:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign\621394755'
                    workingDir=C:\Users\renjiali\AppData\Local\electron-builder\Cache\winCodeSign     
  • Above command failed, retrying 2 more times

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by lucktangpeng** [comment]
The above problem is because win11 does not have permission to cause, using cmd admin mode to re-compile can be successful

**Comment by shiftonetothree** [comment]
@lucktangpeng thank's
