### ISSUE TITLE
[Bug]: fs module on Windows cannot handle special characters

### ISSUE THREAD

**Issue by JasonYeMSFT** [electron/electron#41659]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.4

### What operating system are you using?

Windows

### Operating System Version

10.0.22631

### What arch are you using?

x64

### Last Known Working Electron version

28.2.8

### Expected Behavior

Be able to write to create a file with a valid file name.

For example, add these two lines in the main.js script.
```
const fs = require("fs");
fs.writeFileSync("./test.txt🍕🍕", "Hello World", "utf-8");
```

### Actual Behavior

Fail with Error: ENOENT: no such file or directory.

### Additional Information

This is a node bug and the Node team is fixing it in a new Node release: https://github.com/nodejs/node/issues/48673

Electron v29.1.x is currently on a buggy node version that also suffers from this bug. Is there any plan to address it in a patched Electron release?

**Comment by Prinzhorn** [comment]
Is this different from https://github.com/electron/electron/issues/41484 ?

**Comment by JasonYeMSFT** [comment]
> Is this different from #41484 ?

I think they probably share the same root cause. When we hit the problem we were exclusively trying to write using fs instead trying to read the file.
