### ISSUE TITLE
[Bug]: Window resizes incrementally on win.show

### ISSUE THREAD

**Issue by doods-irl** [electron/electron#41675]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 22621.3296

### What arch are you using?

x64

### Expected Behavior

Window should stick to the bounds that are set for it during initialisation.

### Actual Behavior

I've discovered that when I use some shortcuts to display the window, that repeatedly pushing the shortcuts incrementally expands the window beyond the parameters that the window should abide by.

Below, I am pretty explicitly telling the window which size it should be:
```
function registerShortcuts() {
  const editorShortcut = "CommandOrControl+Alt+L";
  const bigEditorShortcut = "CommandOrControl+Alt+K";
  const escapeShortcut = "Escape";

  globalShortcut.register(editorShortcut, () => {
    if (!win.isVisible()) {
      showMiniEditor();
    } else {
      showBigEditor();
    }
  });

  globalShortcut.register(bigEditorShortcut, showBigEditor);
  globalShortcut.register(escapeShortcut, () => win.blur());
}

function prepareEditor() {
  serveLogs();
  const { width } = screen.getPrimaryDisplay().workAreaSize;
  win.setPosition(width - 820, 20);
  win.webContents.executeJavaScript("clearText()");
  win.show();
  win.webContents.executeJavaScript("focusText()");
}

function showMiniEditor() {
  prepareEditor();
  win.setSize(800, miniHeight);
}

function showBigEditor() {
  prepareEditor();
  console.log(bigHeight);
  win.setSize(800, bigHeight);
}
```

The bigHeight console log repeats "800, 800, 800..." every time the shortcut is pressed.

So I added some extra bells and whistles to try reign it in...

```
win = new BrowserWindow({
    width: 800,
    height: miniHeight,
    minWidth: 800,
    maxWidth: 800,
    x: width - 820,
    y: 20,
    frame: false,
    resizable: false,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      devTools: true,
    },
    skipTaskbar: true,
  });

  win.setMaximumSize(800, bigHeight);
  win.on('resize', () => {
    const [width, height] = win.getSize();
    console.log(`Window resized to: ${width}x${height}`);
  });
```

The height eventually caps at 1004px, but the width will go on forever:
```
...
Window resized to: 1684x1004
Window resized to: 1685x1004
Window resized to: 1687x1004
Window resized to: 1686x1004
Window resized to: 1688x1004
Window resized to: 1689x1004
Window resized to: 1691x1004
Window resized to: 1690x1004
Window resized to: 1692x1004
...
```

I disabled the setPosition in prepareEditor(), set up a few more logs and found that it was never hitting the size target:
```
Window blurred, explicitly setting 800, 70!
Window resized to: 802x71
Showing mini editor!
Window resized to: 802x91
Mini becomes big editor!
Window resized to: 802x801
Window blurred, explicitly setting 800, 70!
Window resized to: 801x71
Big editor, str8 up!
Window resized to: 802x801
```

Of interest though, removing setPosition did stop the window growing, just strange that even with the boundaries set that the window is always bigger than I've defined. (And I would still like to explicitly set the location! Changes in resolution without setPosition to catch it will cause the window to appear in the wrong spot!)

https://github.com/electron/electron/assets/10229798/27c41b19-a8c8-4eb4-a72a-5fa77b2b4bea

**Comment by HQidea** [comment]
see https://github.com/electron/electron/issues/10862
