### ISSUE TITLE
[Bug]: shell.showItemInFolder does not correctly open the folder if it includes a hash (#)

### ISSUE THREAD

**Issue by ollm** [electron/electron#41679]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.9.8

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

Open the correct folder without using `encodeURIComponent`.

I don't know if similar functions (like `shell.openPath`) have the same issue.

### Actual Behavior

The folder before the file/folder with the hash (#) is opened, currently,  I need to use `encodeURIComponent` to open correct folder.

Example:

```js
shell.showItemInFolder(encodeURIComponent(path).replace(/\%2F/g,'/').replace(/\%5C/g,'\\').replace(/\%3A/g, ':'));
```

**Comment by codebytere** [comment]
Electron v25 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days f there is no response.

**Comment by ollm** [comment]
I have checked different versions and the bug does not happen in Electron v26 or higher.

Sorry for not checking this before.

I close the issue.
