### ISSUE TITLE
[Feature Request]: RPM depend on so files instead of package names

### ISSUE THREAD

**Issue by Lunarequest** [electron/electron#41677]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently the rpm file outputted by electron-builder has dependencies on package names. This leads to issues on distributions like opensuse & magia/mandrake which uses different package names. This results in users needing to tell the package manager(eg zypper) to ignore dependencies and manually install dependencies.

### Proposed Solution

Making RPMs depend on .so files like `libuuid.so.1` this would solve the issue of different distros having different packages

### Alternatives Considered

Sticking with the current situation would result in a worse user experience for people who are not using RHEL alike distros.

**Comment by Lunarequest** [comment]
based on some quick experimentation it should be as easy as changing the fpm calls from using package names to so files

**Comment by codebytere** [comment]
The Electron team does not maintain `electron-builder` - feel free to open an issue there.
