### ISSUE TITLE
[Bug]: can't build electron with debugging page guide

### ISSUE THREAD

**Issue by weihongfei** [electron/electron#41674]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Electron v31.0.0-nightly.20240315

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Last Known Working Electron version

no

### Expected Behavior

https://www.electronjs.org/docs/latest/development/debugging
fllowing this guide can build correctly

### Actual Behavior

link electron.exe error

ninja: Entering directory `out\Debug'
[1/2] LINK electron.exe electron.exe.pdb
FAILED: electron.exe electron.exe.pdb
..\..\third_party\llvm-build\Release+Asserts\bin\lld-link.exe "/OUT:./electron.exe" /nologo -libpath:..\..\third_party\llvm-build\Release+Asserts\lib\clang\19\lib\windows "-libpath:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.39.33519\ATLMFC\lib\x64" "-libpath:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.39.33519\lib\x64" "-libpath:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "-libpath:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "-libpath:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" /MACHINE:X64  "/PDB:./electron.exe.pdb" "@./electron.exe.rsp"
lld-link: error: undefined symbol: protected: virtual class ExtensionFunction::ResponseAction __cdecl extensions::ExtensionActionOpenPopupFunction::RunExtensionAction(void)
>>> referenced by obj/electron/shell/browser/extensions/api\api_registration/generated_api_registration.obj:(const extensions::ExtensionActionOpenPopupFunction::`vftable')
ninja: build stopped: subcommand failed.

**Comment by weihongfei** [comment]
can anybody help me?

**Comment by weihongfei** [comment]
Breakpoint Debugging
Note that this will increase the size of the build significantly, taking up around 50G of disk space

Write the following file to electron/.git/info/exclude/debug.gn

import("//electron/build/args/testing.gn")
is_debug = true
symbol_level = 2
forbid_non_component_debug_builds = false

Then execute:

$ gn gen out/Debug --args="import(\"//electron/.git/info/exclude/debug.gn\") $GN_EXTRA_ARGS"
$ ninja -C out/Debug electron


Now you can use LLDB for breakpoint debugging.

**Comment by weihongfei** [comment]
is_debug flag will cause errors,

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by yanite** [comment]
> is_debug标志将导致错误，

extension_action_api.cc add function

ExtensionFunction::ResponseAction
ExtensionActionOpenPopupFunction::RunExtensionAction() {
  LOG(INFO) << "chrome.action.getPopup is not supported in Electron";

  return RespondNow(WithArguments(""));
}
