### ISSUE TITLE
[Bug]: win11 electron unable to trash nested folders.

### ISSUE THREAD

**Issue by python-studio** [electron/electron#41678]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.0

### What operating system are you using?

Windows

### Operating System Version

windows11

### What arch are you using?

x64

### Expected Behavior

file Structure:
    folder a/folder b/file c

shell.trashItem('folder a') 

I want this work.

### Actual Behavior

file Structure:
    folder a/folder b/file c

shell.trashItem('folder a')  then it request administrator privileges and finally fail !!!!
main process fail log: [Error: Failed to perform delete operation]

but shell.trashItem('folder a\\folder b')  and shell.trashItem('folder a\\folder b\\file c')  is ok!!!

**Comment by archanakush900** [comment]
updating your dependencies if you're using npm or yarn.
