### ISSUE TITLE
[Bug]: display id non existent in linux 

### ISSUE THREAD

**Issue by Deamoner** [electron/electron#41687]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.8.2

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu

### What arch are you using?

x64

### Expected Behavior

I expect the display_id to be present in the desktopCapturer.getSources and in  const { screen } = require('electron')
        const displays = screen.getAllDisplays();

### Actual Behavior

{
    name: 'Screen 1',
    id: 'screen:396:0',
    thumbnail: NativeImage {
      toPNG: [Function: toPNG],
      toJPEG: [Function: toJPEG],
      toBitmap: [Function: toBitmap],
      getBitmap: [Function: getBitmap],
      getScaleFactors: [Function: getScaleFactors],
      getNativeHandle: [Function: getNativeHandle],
      toDataURL: [Function: toDataURL],
      isEmpty: [Function: isEmpty],
      getSize: [Function: getSize],
      setTemplateImage: [Function: setTemplateImage],
      isTemplateImage: [Function: isTemplateImage],
      isMacTemplateImage: [Getter/Setter],
      resize: [Function: resize],
      crop: [Function: crop],
      getAspectRatio: [Function: getAspectRatio],
      addRepresentation: [Function: addRepresentation]
    },
    display_id: '67',
    appIcon: null
  },
  {
    name: 'Screen 2',
    id: 'screen:656:0',
    thumbnail: NativeImage {
      toPNG: [Function: toPNG],
      toJPEG: [Function: toJPEG],
      toBitmap: [Function: toBitmap],
      getBitmap: [Function: getBitmap],
      getScaleFactors: [Function: getScaleFactors],
      getNativeHandle: [Function: getNativeHandle],
      toDataURL: [Function: toDataURL],
      isEmpty: [Function: isEmpty],
      getSize: [Function: getSize],
      setTemplateImage: [Function: setTemplateImage],
      isTemplateImage: [Function: isTemplateImage],
      isMacTemplateImage: [Getter/Setter],
      resize: [Function: resize],
      crop: [Function: crop],
      getAspectRatio: [Function: getAspectRatio],
      addRepresentation: [Function: addRepresentation]
    },
    display_id: '71',
    appIcon: null
  },
  {
    name: 'Screen 3',
    id: 'screen:658:0',
    thumbnail: NativeImage {
      toPNG: [Function: toPNG],
      toJPEG: [Function: toJPEG],
      toBitmap: [Function: toBitmap],
      getBitmap: [Function: getBitmap],
      getScaleFactors: [Function: getScaleFactors],
      getNativeHandle: [Function: getNativeHandle],
      toDataURL: [Function: toDataURL],
      isEmpty: [Function: isEmpty],
      getSize: [Function: getSize],
      setTemplateImage: [Function: setTemplateImage],
      isTemplateImage: [Function: isTemplateImage],
      isMacTemplateImage: [Getter/Setter],
      resize: [Function: resize],
      crop: [Function: crop],
      getAspectRatio: [Function: getAspectRatio],
      addRepresentation: [Function: addRepresentation]
    },
    display_id: '72',
    appIcon: null
  }
]
[
  {
    id: 21691165392764996,
    label: 'Built-in display',
    bounds: { x: 1440, y: 0, width: 2560, height: 1440 },
    workArea: { x: 1440, y: 27, width: 2560, height: 1354 },
    accelerometerSupport: 'unknown',
    monochrome: false,
    colorDepth: 24,
    colorSpace: '{r:[0.6694, 0.3169], g:[0.1997, 0.7248], b:[0.1455, 0.3169], w:[0.3127, 0.3290]}, transfer:SRGB, matrix:RGB, range:FULL}',
    depthPerComponent: 8,
    size: { width: 2560, height: 1440 },
    displayFrequency: 59,
    workAreaSize: { width: 2560, height: 1354 },
    scaleFactor: 1,
    rotation: 0,
    internal: true,
    touchSupport: 'unknown'
  },
  {
    id: 71,
    label: '',
    bounds: { x: 0, y: 0, width: 1440, height: 1440 },
    workArea: { x: 0, y: 0, width: 1440, height: 1440 },
    accelerometerSupport: 'unknown',
    monochrome: false,
    colorDepth: 24,
    colorSpace: '{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}',
    depthPerComponent: 8,
    size: { width: 1440, height: 1440 },
    displayFrequency: 59,
    workAreaSize: { width: 1440, height: 1440 },
    scaleFactor: 1,
    rotation: 0,
    internal: false,
    touchSupport: 'unknown'
  },
  {
    id: 72,
    label: '',
    bounds: { x: 4000, y: 0, width: 1440, height: 1440 },
    workArea: { x: 4000, y: 0, width: 1440, height: 1440 },
    accelerometerSupport: 'unknown',
    monochrome: false,
    colorDepth: 24,
    colorSpace: '{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}',
    depthPerComponent: 8,
    size: { width: 1440, height: 1440 },
    displayFrequency: 59,
    workAreaSize: { width: 1440, height: 1440 },
    scaleFactor: 1,
    rotation: 0,
    internal: false,
    touchSupport: 'unknown'
  }
]

**Comment by codebytere** [comment]
@Deamoner in your provided code `display_id` is shown. it is not shown in the `screen` objects because it is not a property of screen.

**Comment by Deamoner** [comment]
@codebytere it seems you misinterpretted my issue. I was not expecting that property in screen objects. but the id in screen objects has traditionally been used to associate the display information. Otherwise how can you tell what display/resolution information you are getting from the desktopcapture? This has been accepted as something fixed previously. Such as https://github.com/electron/electron/issues/12312 -
