### ISSUE TITLE
[Bug]: DesktopCapturer API cannot start audio source

### ISSUE THREAD

**Issue by Psyjakes** [electron/electron#41697]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 10.0.19045 Build 19045

### What arch are you using?

x64

### Expected Behavior

When I start the Desktop Capturer to record display video and audio it should use the default output audio stream even if it is from a usb device

### Actual Behavior

When I use a usb output device (speakers and earphones) then I get a "DOMException: Could not start audio source".

### Additional Information

I use the exact method as shown on the docs page for DesktopCapturer
`const audioStream = await navigator.mediaDevices.getUserMedia({ audio: { mandatory: { chromeMediaSource: ‘desktop’ } }, video: { mandatory: { chromeMediaSource: ‘desktop’ } } } as any); `
The as any is inserted to move around typescript errors.

Please note this is not a duplicate of issue #41069
I was informed of the old version and updated. The instructions on the docs still gives the same error, but I have since found that the issue is only for usb output devices

**Comment by Psyjakes** [comment]
Hello thank you for the response you can find the test app at this link https://github.com/Psyjakes/DesktopCapture_TestBed.git please read the readme for instructions to start the app. I did make the repo public please let me know if you have trouble accessing it

**Comment by Psyjakes** [comment]
I did more testing and after removing my Logitech headphones driver software the desktop capturer worked to retrieve sound so it looks like there is a software permission clash when drivers are installed

**Comment by georgexu99** [comment]
Thank you for reporting and investigating this issue. If it was indeed a software permission clash I'm going ahead and closing this thread! Feel free to reopen this if needed.

**Comment by pCoder3000** [comment]
I got the same problem with Vencord and my Logitech USB headset.
