### ISSUE TITLE
[Bug]: I get an error when I use canvas or any module containing canvas

### ISSUE THREAD

**Issue by thescrayx** [electron/electron#41729]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 23H2

### What arch are you using?

x64

### Expected Behavior

I am using Electron js via Node.js, I get an error when I add the canvas module, Electron js application and canvas work separately from each other without any errors.

I tried using the latest version of electron js, same problem.

I put the github link containing a similar scenario with Electron Fiddle and added a screenshot.
![Ekran görüntüsü 2024-03-28 172304](https://github.com/electron/electron/assets/61876272/a085047e-c0fd-4664-8338-4a5523d4dc72)

### Actual Behavior

When the canvas module is added to the Node js electron js application, it gives the following error.

`Electron v29.1.5 started.

App threw an error during load
Error: The module '\\?\C:\Users\scray\AppData\Local\Temp\electron-fiddle-32588-4mbj3bRr2w0Y\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 121. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
at Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
at Module.load (node:internal/modules/cjs/loader:1098:32)
at Module._load (node:internal/modules/cjs/loader:945:12)
at c._load (node:electron/js2c/node_init:2:13672)
at Module.require (node:internal/modules/cjs/loader:1122:19)
at require (node:internal/modules/helpers:130:18)
at Object.<anonymous> (C:\Users\scray\AppData\Local\Temp\electron-fiddle-32588-4mbj3bRr2w0Y\node_modules\canvas\lib\bindings.js:3:18)
at Module._compile (node:internal/modules/cjs/loader:1256:14)`

### Testcase Gist URL

https://gist.github.com/thescrayx/39087f53fc3e19ab03500e9a9b5290c5

### Additional Information

Node.js v20.11.1
"electron": "^29.1.0"
"canvas": "^2.11.2"
"discord.js": "^14.14.1"
"node-os-utils": "^1.3.7"
"npm": "^10.5.0"

**Comment by codebytere** [comment]
This means you need to do as the error specifies and reconcile the version of Node.js against what you need. You can use https://github.com/electron/rebuild to do this.
