### ISSUE TITLE
[Bug]: Clicking app icon in dock always focuses the first created window

### ISSUE THREAD

**Issue by Imperat** [electron/electron#41725]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.5

### What operating system are you using?

macOS

### Operating System Version

MacOS Sonoma 14.4

### What arch are you using?

x64

### Expected Behavior

I have an app with multiple windows. User minimizes windows one by one. When they click app icon on dock I expect the last focused window to appear.

### Actual Behavior

The first created window appears.

### Testcase Gist URL

https://gist.github.com/f14c05d8d66b2b07964e6cefb64f8b29

### Additional Information

https://github.com/electron/electron/assets/7069867/23a4575e-7a71-484b-ab54-a7979b79732e

**Comment by codebytere** [comment]
@Imperat this is, unfortunately, a macOS and not Electron issue. If you try this with three open Finder windows you will see the same behavior.
