### ISSUE TITLE
[Bug]: backgroundMaterial and app.disableHardwareAcceleration() conflict with each other

### ISSUE THREAD

**Issue by LoveLuanQi1202** [electron/electron#41742]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### What arch are you using?

x64

### Expected Behavior

When there is a transparent acrylic background, you can click inside the window

### Actual Behavior

Mouse click events penetrate to the desktop behind the program

### Testcase Gist URL
https://gist.github.com/LoveLuanQi1202/19b805b16c49ac7e132c956a8dfdd716

### Additional Information

just transparent background with some text

**Comment by mlaurencin** [comment]
For testing, this is also reproducible by making these changes to `main.js` in the demo gist of [Electron Fiddle](https://www.electronjs.org/fiddle).

**Comment by LoveLuanQi1202** [comment]
> For testing, this is also reproducible by making these changes to `main.js` in the demo gist of [Electron Fiddle](https://www.electronjs.org/fiddle).


I have updated  the demo gist
