### ISSUE TITLE
[Bug]:  Silent print give empty paper

### ISSUE THREAD

**Issue by brkrtp** [electron/electron#41741]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2

### What arch are you using?

x64

### Last Known Working Electron version

29.1.6

### Expected Behavior

I can't print the html document, it just prints out a piece of white paper.

### Actual Behavior

it just prints out a piece of white paper in thermal printer

**If I remove the silent print feature I can print successfully with the dialog screen, but if I turn on the silent print feature, only a piece of white paper comes out.** 

### Additional Information

![WhatsApp Image 2024-03-29 at 04 09 30](https://github.com/electron/electron/assets/18514716/b03410f1-e785-4aa2-8fce-5fe26ab2571e)

 

> let printerWindow = new BrowserWindow({
>         width: 800,
>         height: 800,
>         show: false
>     })
>     return new Promise((resolve, reject) => {
>         printerWindow.loadURL(printerFile);
>         printerWindow.webContents.once('crashed', (e) => {
>             console.error("printerWindow crashed")
>             reject("crashed");
>         });
>         let p1 = new Promise((resolve) => printerWindow.webContents.on('did-finish-load', resolve))
>         let p2 = new Promise((resolve) => printerWindow.on('ready-to-show', resolve))
>         Promise.all([p1, p2]).then(() => {
>             const options = {
>                 silent: true,
>                 deviceName: deviceName,
>             }
>             return printerWindow.webContents.print(options, (success, errorType) => {
>                 setTimeout(() => printerWindow.close(), 1000);
>                 if (!success) reject(errorType); else resolve(success)
>             })
>         })
>     })

**Comment by S-NOPPY** [comment]
I also encountered this problem, and it printed fine with version 22.0.0

**Comment by MohamedMuflahi** [comment]
I also am experiencing the same issue, it prints correctly, when silent is set to true, and works on mac, but windows produces this blank paper.

**Comment by victorcarablut** [comment]
> I also encountered this problem, and it printed fine with version 22.0.0

"electron": "^24.8.8" also OK

**Comment by codebytere** [comment]
Closing as a duplicate of https://github.com/electron/electron/issues/39179 for which i've got a PR up at https://github.com/electron/electron/pull/41811

**Comment by a-eid** [comment]
this is exactly what is happening with me as well. 

@codebytere please keep in mind that the issue is still present even with the latest electron version `38.4.0`

**Comment by faheem1810** [comment]
Same problem in "electron": "^39.2.6", and   "electron-pos-printer": "^1.3.8",
version
