### ISSUE TITLE
[Bug]: screen display_id from desktopCapturer doesn't match the id from screen.getAllDisplays() in Linux, but mac and windows works

### ISSUE THREAD

**Issue by wanghanzhen** [electron/electron#41755]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.5

### What operating system are you using?

Ubuntu

### Operating System Version

ubuntu 22.04.4

### What arch are you using?

x64

### Expected Behavior

a real data from my linux user. the two ids below should match so I can get screen-related data.

getAllDisplays：
```json
[{
	"accelerometerSupport": "unknown",
	"bounds": {
		"x": 0,
		"y": 0,
		"width": 2560,
		"height": 1440
	},
	"colorDepth": 24,
	"colorSpace": "{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}",
	"depthPerComponent": 8,
	"detected": true,
	"displayFrequency": 59.9505500793457,
	"id": 13702250537190212,
	"internal": false,
	"label": "LEN P27q-10",
	"maximumCursorSize": {
		"width": 0,
		"height": 0
	},
	"monochrome": false,
	"nativeOrigin": {
		"x": 0,
		"y": 0
	},
	"rotation": 0,
	"scaleFactor": 1,
	"size": {
		"width": 2560,
		"height": 1440
	},
	"workArea": {
		"x": 72,
		"y": 27,
		"width": 2488,
		"height": 1413
	},
	"workAreaSize": {
		"width": 2488,
		"height": 1413
	},
	"touchSupport": "unknown"
}]
```
display data (been transformed) from desktopCapturer
```json
{"displayId":"3487859523","isFullWindow":true,"windowId":382,"mediaSourceId":"screen:382:0"}
```

### Actual Behavior

`"id": 13702250537190212` !== `"displayId":"3487859523"`
I cannot get the info about specified screen.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction. 

There was also no repro provided, which means we cannot effectively triage further.

**Comment by Hahlh** [comment]
@codebytere This issue doesn't seem to have been a question, so if the lack of a repro isn't the deciding factor, this should likely not have been closed.

**Comment by bitbound** [comment]
@codebytere   This does appear to be a bug.  For me, this is appearing on Windows.  I haven't tested other platforms.

In Electron version 29.4.2 and prior, these two properties were identical, and you could use them to correlate displays retrieved from `desktopCapturer` and `screen` APIs:
- `Electron.DesktopCaptureSource.display_id`
- `Electron.Display.id`

As you can see in the JSDocs, they are indeed supposed to match:

![image](https://github.com/electron/electron/assets/20995508/018f044e-8a41-464a-9ae6-f4788d42bf24)

I upgraded to Electron version 31.1.0 and found that they no longer match.  I've attached a repro project.  When you run it, you'll see the below output in the main process, which gets logged in `mediaHelper.ts`.  This project was created from the electron-forge Vite + TypeScript template.

Output (notice the mismatch):

```
Getting capturer sources.
Found capturer sources:  [
  {
    name: 'Entire screen',
    id: 'screen:0:0',
    thumbnail: NativeImage {
      // Irrelevant properties removed for brevity.
    },
    display_id: '2528732444',
    appIcon: null
  }
]
Found displays:  [
  {
    accelerometerSupport: 'unknown',
    bounds: { x: 0, y: 0, width: 1920, height: 1080 },
    colorDepth: 24,
    colorSpace: '{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}',
    depthPerComponent: 8,
    detected: true,
    displayFrequency: 144,
    id: 4096356785,
    internal: true,
    label: '',
    maximumCursorSize: { width: 0, height: 0 },
    monochrome: false,
    nativeOrigin: { x: 0, y: 0 },
    rotation: 0,
    scaleFactor: 1,
    size: { width: 1920, height: 1080 },
    workArea: { x: 0, y: 0, width: 1920, height: 1032 },
    workAreaSize: { width: 1920, height: 1032 },
    touchSupport: 'unknown'
  }
]
Error while getting screens. Display 2528732444 not found.
```

[my-new-app.zip](https://github.com/user-attachments/files/16007589/my-new-app.zip)

**Comment by wanghanzhen** [comment]
+1. Recently I have been upgrading electron@31 and encountered this issue in Windows (previously it was Linux) but it works fine in MacOS.

@codebytere Could you reopen this issue and take a look at this?
