### ISSUE TITLE
[Bug]: MAC: The cleared notification is not responding again

### ISSUE THREAD

**Issue by Rebecca-z** [electron/electron#41754]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.0

### What operating system are you using?

macOS

### Operating System Version

Darwin RebeccadeMacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 x86_64

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

In the process of responding to the first notification, several other notifications came, and the first notification clicked the button to clear all notifications.

### Actual Behavior

The electron monitor showed that the clearance was successful, but a new notification was received again, and the cleared notification was carried out, and there was no response.

### Testcase Gist URL

https://gist.github.com/Rebecca-z/0b7e7a97d2cd8ecf71e33dde53fe4a03

**Comment by georgexu99** [comment]
Thank you for submitting a bug report! Can you clarify what you mean by 'no response' in the actual behaviour?

**Comment by Rebecca-z** [comment]
> Thank you for submitting a bug report! Can you clarify what you mean by 'no response' in the actual behaviour?

It means that the notification bar of the system is stuck, and there is no response when you click the close button
