### ISSUE TITLE
[Bug]: 'did-fail-load' is not happening if JavaScript fails to load

### ISSUE THREAD

**Issue by ashwin-mittal** [electron/electron#41766]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.6

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

29.1.6

### Expected Behavior

As I have kept the script as a parser-blocking script in my index.html, but as that resource is not present I am getting a "resource fails to load" error on the console but "did-fail-load" is not coming in my main process.
![Screenshot 2024-04-03 at 6 30 37 PM](https://github.com/electron/electron/assets/56213491/9364d580-3888-46a0-be48-6f0ede1cd5d4)

### Actual Behavior

As the parser-blocking script fails to load, the frame fails to load, but "did-fail-load" is not getting emitted. I have attached the code to reproduce the issue.

### Testcase Gist URL

https://github.com/ashwin-mittal/load-issue

**Comment by codebytere** [comment]
@ashwin-mittal `did-fail-load` is emitted when the `webContents` fails to load a given url - not when a subcomponent of the loaded page isn't properly fetched. In your case it would not be emitted.

**Comment by ashwin-mittal** [comment]
> @ashwin-mittal `did-fail-load` is emitted when the `webContents` fails to load a given url - not when a subcomponent of the loaded page isn't properly fetched. In your case it would not be emitted.

Can you please clarify what is the meaning of `webContents` here? Is it an HTML file only?

**Comment by ashwin-mittal** [comment]
Is there any other way or events we can listen to handle JavaScript load failure?
