### ISSUE TITLE
[Bug]: alwaysOnTop property does not work when using screen sharing with microsoft teams on windows.

### ISSUE THREAD

**Issue by vaibhavagrawal2912** [electron/electron#41760]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

When I open my BrowserWindow with the param `alwaysOnTop: true`, it works for the majority all the time. 
But we have encountered a weird issue where if I am using Microsoft Teams, and enable screen sharing, then my topmost window moves to the most below behind all the windows. 

This happens as soon as the MS Teams screen sharing is started. I am not able to bring the window on top as well.

Note: This does not happen with Google meet or Zoom screen sharing.

### Actual Behavior

Any BrowserWindow that is marked as alwaysOnTop should remain on top. There could be a priority for the top-level windows but it should definitely does not move to the bottom of the stack.

**Comment by codebytere** [comment]
Please report this issue to Microsoft Teams to start. It's possible this is an issue with overrides or other changes made by Teams - if they determine it's an Electron issue, we're happy to take another look here.
