### ISSUE TITLE
[Bug]: When menu item has label equal to `Preferences` word it becomes `Settings...`

### ISSUE THREAD

**Issue by Imperat** [electron/electron#41764]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.5

### What operating system are you using?

macOS

### Operating System Version

MacOS Sonoma 14.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

For my fiddle I expect having "Electron" menu group with "Preferences" menu item.

### Actual Behavior

I see "Electron" menu group with "Setting..." menu item.
<img width="134" alt="Screenshot 2024-04-03 at 4 09 45 PM" src="https://github.com/electron/electron/assets/7069867/b3930c1b-6144-48cd-b619-e1035eeeacbd">

### Testcase Gist URL

https://gist.github.com/Imperat/6feb7ed7c391c7f75321d92d256be977

**Comment by mlaurencin** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I would also recommend looking at the documentation for [Menu ](https://www.electronjs.org/docs/latest/api/menu) and [Menu Item](https://www.electronjs.org/docs/latest/api/menu-item). In particular, [this example of a menu](https://www.electronjs.org/docs/latest/api/menu#examples) should be helpful.

I hope this helps!
