### ISSUE TITLE
[Bug]: Unable to create status tray icon on Windows 10

### ISSUE THREAD

**Issue by felipecrs** [electron/electron#41773]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 22H2

### What arch are you using?

x64

### Last Known Working Electron version

26

### Expected Behavior

The tray icon to be created normally when a uuid is used, as it used to be in Electron 26.

### Actual Behavior

Tray icon only gets created when the application is first installed. Try installing/updating the application with the same tray icon uuid and tray icon will no longer be created.

### Additional Information

Replaying what I wrote in https://github.com/electron/electron/issues/41721:

I know this issue is almost 10 years old, but I am facing this exact same problem after upgrading my application from Electron from 26 to 28.

```console
[13988:0201/145554.280:WARNING:notify_icon.cc(62)] Unable to create status tray icon.
[13988:0201/145554.289:WARNING:notify_icon.cc(143)] Error setting status tray icon image
[13988:0201/145554.296:WARNING:notify_icon.cc(159)] Unable to set tooltip for status tray icon
```

And, as suggested by @anaisbetts, removing GUID from the tray icon indeed brings the tray icon back.

Note however I can only reproduce this bug in Windows 10, not Windows 11.

_Originally posted by @felipecrs in https://github.com/electron/electron/issues/2468#issuecomment-1921870756_

**Comment by codebytere** [comment]
@felipecrs unfortunately there's not much we can do about this at this juncture - see https://github.com/electron/electron/pull/21891 which brought it back for requisite caveats to using the GUID.

**Comment by felipecrs** [comment]
@codebytere that PR is from 2020. I believe it was merged way before Electron 26, and this is not an issue with Electron 26.

I have a reproducible environment, where if I downgrade Electron to 26, the issue occurs.

**Comment by felipecrs** [comment]
Hello?

**Comment by felipecrs** [comment]
I confirmed this is still an issue with Electron 30.
