### ISSUE TITLE
[Bug]: contextBridge.exposeInIsolatedWorld with worldId 999 is not exposing the API in isolatedContext (preload.ts file)

### ISSUE THREAD

**Issue by ayaankhan98** [electron/electron#41778]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.1

### What operating system are you using?

macOS

### Operating System Version

MacOS sonoma

### What arch are you using?

x64

### Expected Behavior

I am using typescript with electron. I want to expose an api from `main.ts` to `preload.ts`. According to electron docs I am using `contextBridge.exposeInIsolatedWorld` with world id 999.

please refer [here](https://www.electronjs.org/docs/latest/api/context-bridge#contextbridgeexposeinisolatedworldworldid-apikey-api)

`main.ts`
```
const api: MyAPI = new MyAPI();
contextBridge.exposeInIsolatedWorld(999, 'myApi', myAPI);
```

`preload.ts`
```
const myAPI = (window as any).myApi;
console.log(myAPI) // prints undefined
```

### Actual Behavior

It should be able to expose the api in preload.ts

**Comment by RawRaw111** [comment]
> ### Preflight Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.
> 
> ### Electron Version
> 26.2.1
> 
> ### What operating system are you using?
> macOS
> 
> ### Operating System Version
> MacOS sonoma
> 
> ### What arch are you using?
> x64
> 
> ### Last Known Working Electron version
> _No response_
> 
> ### Expected Behavior
> I am using typescript with electron. I want to expose an api from `main.ts` to `preload.ts`. According to electron docs I am using `contextBridge.exposeInIsolatedWorld` with world id 999.
> 
> please refer [here](https://www.electronjs.org/docs/latest/api/context-bridge#contextbridgeexposeinisolatedworldworldid-apikey-api)
> 
> `main.ts`
> 
> ```
> const api: MyAPI = new MyAPI();
> contextBridge.exposeInIsolatedWorld(999, 'myApi', myAPI);
> ```
> 
> `preload.ts`
> 
> ```
> const myAPI = (window as any).myApi;
> console.log(myAPI) // prints undefined
> ```
> 
> ### Actual Behavior
> It should be able to expose the api in preload.ts
> 
> ### Testcase Gist URL
> _No response_
> 
> ### Additional Information
> _No response_

**Comment by mlaurencin** [comment]
Since it looks like there has already been discussion about this as a question in the Discord, I am going ahead and closing this. Should you need more assistance, be sure give the others channels a try for more help.
