### ISSUE TITLE
[Bug]: Subclass of BrowserWindow missing from BrowserWindow.getAllWindows()

### ISSUE THREAD

**Issue by safris** [electron/electron#41785]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.2.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

In the following code, I declare a subclass of `BrowserWindow` by the name of `CustomWindow`.
Then, I instantiate a regular `BrowserWindow`, as well as a `CustomWindow`.
Both windows appear.
When I call `BrowserWindow.getAllWindows().length`, I expect `2` to be returned.

```javascript
const { app, BrowserWindow } = require("electron");

class CustomWindow extends BrowserWindow {
  constructor(options) {
    super(options);
  }
}

app.on("ready", () => {
  const win1 = new BrowserWindow();
  const win2 = new CustomWindow();
  const expected = 2;
  const actual = BrowserWindow.getAllWindows().length;
  if (actual != expected)
    throw new Error("Assertion failed");
});

app.on("window-all-closed", () => app.quit());
```

### Actual Behavior

When I call `BrowserWindow.getAllWindows().length`, `1` is returned.

**Comment by nornagon** [comment]
We don't support subclassing `BrowserWindow`. This isn't guaranteed to work correctly, even if it happens to (apparently, somewhat) work today.
