### ISSUE TITLE
[Bug]: An error when trying to install electron-forge

### ISSUE THREAD

**Issue by Fyphen1223** [electron/electron#41780]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

When trying to run this command
`npx electron-forge import`
from the get started page, I got this error:

```
An unhandled rejection has occurred inside Forge:
Error: Failed to install modules: ["electron-squirrel-startup"]

With output: Command failed with a non-zero return code (1):
npm install electron-squirrel-startup --save

npm ERR! Cannot read properties of null (reading 'matches')
```

Some error text are reducted due to privacy, if you need this for debugging, I'll post it as soon as possible.

### Actual Behavior

Should justr install the library that are necessary to compile the files.

**Comment by codebytere** [comment]
Please open this issue on the [forge repo](https://github.com/electron/forge)
