### ISSUE TITLE
[Bug]: desktopCapturer.getSources created a file without any permissions (Read/write/delete)

### ISSUE THREAD

**Issue by fzs1994** [electron/electron#41797]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

10.1.5

### What operating system are you using?

Windows

### Operating System Version

Window 10 any

### What arch are you using?

x64

### Last Known Working Electron version

10.1.5

### Expected Behavior

Few of the screenshots created with `desktopCapturer.getSources` are fine but sometimes few of them do not have any permissions. Event to view the image, admin permission is required. I've attached image showing thumbnail of the files. The one with preview thumbnail visible are okay but the ones whos thumbnail is not previewable are having this issue.

![1000030890](https://github.com/electron/electron/assets/10684213/86f432e0-659c-4e54-a17b-bf49d894a44c)

Also you can see the error when tried to view the file details.

### Actual Behavior

File should not require any read/write/delete permission.

**Comment by codebytere** [comment]
Electron 10 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

**Comment by mlaurencin** [comment]
We haven't gotten a response and over 10 days have elapsed since the previous comment. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
