### ISSUE TITLE
[Bug]: Cannot send command "Page.setInterceptFileChooserDialog" by webContents.debuggerr

### ISSUE THREAD

**Issue by congguago** [electron/electron#41796]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.6

### What operating system are you using?

macOS

### Operating System Version

14.2.1 (23C71)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I want to intercept browser's file chooser and use setFileInputFiles like this:
`
mainWindow.webContents.debugger.sendCommand("Page.enable").then((res) => {
   
    mainWindow.webContents.debugger.sendCommand("Page.setInterceptFileChooserDialog",{enable: true})
      .then(res => {
        mainWindow.webContents.debugger.addListener('message', (event, method, params, sessionId) => {
          if (method === 'Page.fileChooserOpened') {
            // do something
            
          }
        });
      }).catch(e => {
      console.warn(e);

    });
  });
`

### Actual Behavior

sendCommand("Page.setInterceptFileChooserDialog", { enable: true}) throw an error:
`
{stack: "Error: Invalid parameters", message: "Invalid parameters"}
`

### Additional Information

https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setInterceptFileChooserDialog

**Comment by codebytere** [comment]
@congguago the property name is `enabled` not `enable`.
