### ISSUE TITLE
[Bug]: IPC Dialog showing up behind main window after activated a second time

### ISSUE THREAD

**Issue by scalgoon** [electron/electron#41803]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.5

### What operating system are you using?

Ubuntu

### Operating System Version

Linux dez-ubuntu 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

IPC showOpenDialog should open as focused every time without needing the app to be restarted

### Actual Behavior

The showOpenDialog only shows as focused whenever it is opened for the first time, any time after that it is opened behind the main window until the app is restarted

### Additional Information

My current code for the dialog: 
```js
ipcMain.handle('dialog:openDirectory', async () => {
                const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
                    properties: ['openDirectory']
                })

                if (canceled) {
                    return;
                } else {
                    return filePaths[0]
                }
            })
```

**Comment by codebytere** [comment]
Duplicate https://github.com/electron/electron/issues/32857
