### ISSUE TITLE
[Bug]: nativeImage.createThumbnailFromPath fails to resolve in renderer process from version 25.0.0

### ISSUE THREAD

**Issue by gaodeng** [electron/electron#41816]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.2.0

### What operating system are you using?

macOS

### Operating System Version

13.6 (22G116)

### What arch are you using?

x64

### Last Known Working Electron version

24.8.8

### Expected Behavior

The function should resolve as it did in version 24.8.8, returning a thumbnail image or throwing an error if the operation fails.

### Actual Behavior

The function call does not resolve or throw errors, leaving the operation in an unresolved state.

### Testcase Gist URL

https://gist.github.com/gaodeng/05a4fefb9cde972336a1285821953df6

**Comment by gaodeng** [comment]
https://gist.github.com/gaodeng/05a4fefb9cde972336a1285821953df6

**Comment by nornagon** [comment]
Bisected to https://github.com/electron/electron/compare/v25.0.0-nightly.20230330...v25.0.0-nightly.20230331, likely caused by https://github.com/electron/electron/pull/37701. Haven't narrowed down the specific cause yet but that's where it broke.
