### ISSUE TITLE
[Bug]: <webView>.methods not available in preload script

### ISSUE THREAD

**Issue by charlie632** [electron/electron#41814]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.2.0

### What operating system are you using?

macOS

### Operating System Version

14.1.1 (23B81)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I have this in my index.html:

```html
      <webview
        id="foo"
        src="https://www.github.com/"
        style="display: inline-flex; width: 640px; height: 480px"></webview>
```

Calling `webView` from the preload script should work

```js
  const webview = document.getElementById('foo');

  webview.addEventListener('dom-ready', function (e) {
    console.log('webview dom-ready', webview.getWebContentsId);
  });
```

### Actual Behavior

The callback is called, but the `webview.getWebContentsId` is undefined. All methods described here: https://www.electronjs.org/docs/latest/api/webview-tag#methods are undefined.

If the same is run on the renderer process it works as expected.

### Testcase Gist URL

https://gist.github.com/charlie632/406270a2f91c0aafc5472d52d4ecea32

**Comment by charlie632** [comment]
This seems to work on this project: https://github.com/ddupont808/GPT-4V-Act/blob/7b0cbfd561e5d4e2f524b299559e4fdbc067fccd/preload.js#L36-L39

**Comment by charlie632** [comment]
Thanks! Here is the gist https://gist.github.com/charlie632/406270a2f91c0aafc5472d52d4ecea32

**Comment by MaximKalinin** [comment]
Hello!
I see that in the example above they disable `contextIsolation: false` for the browser window instance. If I add it to your gist, it also works.

https://github.com/ddupont808/GPT-4V-Act/blob/7b0cbfd561e5d4e2f524b299559e4fdbc067fccd/main.js#L82
![image](https://github.com/electron/electron/assets/22202138/a2b93e2c-0476-44ab-b73b-a8e1c17399f5)

**Comment by georgexu99** [comment]
Thanks for submitting this issue! I believe this is intended behaviour and that you need to either 1) expose the views api via [contextBridge](https://www.electronjs.org/docs/latest/api/context-bridge), or 2) (not recommended) turn off contextIsolation (see above comment)
