### ISSUE TITLE
[Bug]: Label cutting issue on Brother QL800

### ISSUE THREAD

**Issue by srizzon** [electron/electron#41813]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.8.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

When printing labels on a Brother QL800 printer using Electron, the labels should be printed correctly, with cutting occurring only after the last label. This means that if multiple labels are sent for printing, the cutting should happen once at the end of the entire print job, not after each label.

### Actual Behavior

I'm facing a peculiar issue when trying to print labels on a Brother QL800 printer using Electron. The printing is successful, however, the label cutting is not happening as expected.

I typically send two labels to be printed. Although the labels are printed correctly, the cutting is done after each label. I've tried adjusting the printer's cutting settings, but when the cutting isn't done after each label, it's not done at the end as well, resulting in the user having to manually remove the labels.

Here's a snippet of my code:

```typescript
data.info.map(async (info: any) => {
    const icons = info.icons.map((icon: string) => `<i class="material-icons-outlined">${icon}</i>`);

    const qrCode = await QRCode.toDataURL(info.qr_code_url, { width: 150, margin: 0 });

    const htmlTemplate = template
      .replace('{TITLE}', info.title)
      .replace('{SUBTITLE}', info.subtitle)
      .replace('{EVENT_NAME}', info.eventName)
      .replace('{EVENT_DATE}', info.eventDate)
      .replace('{QR_CODE_DATA}', qrCode)
      .replace('{ICONS}', icons.join(''));

    await printSilently(printOptions, htmlTemplate, serve);
});

async function printSilently(printOptions: WebContentsPrintOptions, htmlTemplate: string, preview = false) {
  let printWin: BrowserWindow | null = new BrowserWindow({ width: 340, height: 109, show: preview });

  printWin.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(htmlTemplate));
  if (preview) return;

  printWin?.webContents.on('did-finish-load', () => {
    printWin?.webContents.print(printOptions, (success, error) => {
      console.log('Print success: ', success);
      console.log('Print error: ', error);
      
      printWin?.close();
    });
  });
}
```

Any suggestions on how I can resolve this label cutting issue? I appreciate any help or guidance in advance!

**Comment by codebytere** [comment]
@srizzon i'd recommend you start here with [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction. If they're unable to help and it is determined this is an issue with Electron itself, we can reopen this and start investigating more thoroughly!
