### ISSUE TITLE
[Bug]: My Node Addon stopped working after version 20.3.8

### ISSUE THREAD

**Issue by iamterryclark** [electron/electron#41823]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.8

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Last Known Working Electron version

20.3.8

### Expected Behavior

compiling node-gyp creates a  ".node" file and should be allowed to be required into a react / electron app

This added is used to expose a shared memory array buffer from c++ to js (pixels of a video)

in version 20.3.9 something was added to stop this from happening but no information was discussed on how to resolve this.

Found here
https://releases.electronjs.org/releases/stable?page=105&limit=2
Added node-api: handle no support for external buffers. [#36626](https://github.com/electron/electron/pull/36626)

### Actual Behavior

electron app runs but array buffer not working.

usually the array buffer is put onto a html canvas and shows the video frame. this has not stopped in version 20.3.9

**Comment by MarshallOfSound** [comment]
> This added is used to expose a shared memory array buffer from c++ to js

This is no longer supported after the V8 Memory Cage was enabled, the release notes you linked reference this and point you to the blog post on the matter --> https://www.electronjs.org/blog/v8-memory-cage

The blog post and linked issue have further discussions on this
