### ISSUE TITLE
[Bug]: install, RequestError: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by XiaCanKeng** [electron/electron#41821]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows10 version 1909

### What arch are you using?

x64

### Last Known Working Electron version

29.2.0

### Expected Behavior

I expected to successfully install it through a proxy.

### Actual Behavior

error log : 
npm ERR! code 1
npm ERR! path E:\Project\WebstormProjects\test\test-electron-app\node_modules\electron
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! RequestError: getaddrinfo ENOTFOUND npmmirror.com
npm ERR!     at ClientRequest.<anonymous> (E:\Project\WebstormProjects\test\test-electron-app\node_modules\@electron\get\node_modules\got\dist\source\core\index.js:970:111)
npm ERR!     at Object.onceWrapper (node:events:634:26)
npm ERR!     at ClientRequest.emit (node:events:531:35)
npm ERR!     at origin.emit (E:\Project\WebstormProjects\test\test-electron-app\node_modules\@electron\get\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:500:9)
npm ERR!     at TLSSocket.emit (node:events:519:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:169:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)

base info : 
node v21.7.2
npm v10.5.1

I have tried all methods mentioned below, but they all failed :
.npmrc :
proxy=xxxx
https-proxy=xxxx
registry=https://registry.npmmirror.com
ELECTRON_MIRROR="https://npmmirror.com/mirrors/electron/"
ELECTRON_CUSTOM_DIR="{{ version }}"
ELECTRON_GET_USE_PROXY=1
electron_builder_binaries_mirror=https://npmmirror.com/mirrors/electron-builder-binaries/

cmd : 
set HTTP_PROXY=xxx
set HTTPS_PROXY=xxx

yarn or cnpm install, failed;
changing the versions of Node.js and npm, but it still failed.

The company accesses the internet through a proxy, and other packages can be installed normally.
I have tried all the methods described in https://www.electronjs.org/zh/docs/latest/tutorial/installation, but I have not been successful.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
