### ISSUE TITLE
[Bug]: Custom protocol called many times with huge video files

### ISSUE THREAD

**Issue by eldanet** [electron/electron#41826]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

In my Electron / Vue application I need to load images and video files from a local folder and for that reason I created a custom protocol pointing to the local folder on app.on('ready') block.
`protocol.registerFileProtocol('atom', (request, callback) => {`
`    const url = request.url.substr(7)`
`    log.info("=> atom: "+ appPath + url)`
`    callback({ path: appPath + url })`
`})`

Protocol should be called only once, and everything works as expected with images and small videos or when there is only one video in one page.

### Actual Behavior

On some pages I need to show a background looped video and than some foreground "detail" videos on button click. 
If video files are small there is no problem, but with bigger files (4k H264 encoded videos of 120 / 280MB) the protocol is called many times, both for the background video that for the foreground video (more than one time per second) causing the block of the app.

I checked that the click action that sets the video path is called only once.
On Vue I've got a data variable called 'path'; on click I set the path of the detail, based on the button clicked.

Click action:
`doAction(ev) {`
`	let item = ev.target`
`	this.path = item.dataset.path`
`}`

Vue component:
`<div class="full-screen" v-if="path" id="discovery-detail">`
`	<div id="box-video" @click="hideDetail">`
`		<video id="fullscreen-video" class="full-screen" :src="path" autoplay loop></video>`
`	</div>`
`</div>`

hideDetail action:
`hideDetail() {`
`	this.path = false`
`}`

The same happens on a new MacMini that will be used fot the show

**Comment by eldanet** [comment]
Hi,
I've tried to fix the problem putting one single video per page but I didn't solve.
The problem raises with every video larger than 120MB. After some time the application crashes.

I tried an old application that uses Electron 13.6.9, already tested many times, and the problem didn't rise.
I then checked various Electron versions and the problem start to rise from 18 version (tested version: 18.3.15).

I fixed the problem installing version 17.4.9
Hope this can help you fixing the problem.

**Comment by MarshallOfSound** [comment]
Chrome will make multiple network requests for larger video files as it "buffers" the video in chunks, as such it's expected behavior that your custom protocol handler will receive multiple requests to resolve a given URL to a "response".

**Comment by eldanet** [comment]
Hi, after sereral tests vith different Electron versions, I understood that the multiple requests were due to "streaming" download of huge files.
The problem is that with Electron 29.1.0 the application craches, with other versions not.
As soon as I can I will crate a repository to reproduce the problem.

**Comment by eldanet** [comment]
Here the test repository:
https://github.com/eldanet/test-video-electron

**First run**
Wait for file to download locally

**App launched**
Click on remote file (https:// origin) => everything works as expected and video loops.
Click on local file (atom:// origin) => app crashes approximatively after 1 minute

Be aware that sometimes it works!
