### ISSUE TITLE
feature request: allow build with enable_extensions=false

### ISSUE THREAD

**Issue by brjsp** [electron/electron#41850]
I'm building electron for a linux distro (openSUSE) and am trying to reduce the size of the binary and the linker's memory requirements by not building unused code in the first place.

One flag i have identified is enable_extensions — for example, entire dependency on //third_party/openscreen seems to be gated on this (as shown by `gn path`). Unfortunately, as of 28.x it even fails to `gn gen` due to overzealous inclusions. Once i import the <a href="https://code.qt.io/cgit/qt/qtwebengine-chromium.git/commit/?h=118-based&id=80a3b06e5b5eeaa7d223c2457811a020790af8c4">patch from Qtwebengine</a> that fixes this, there are several places where a header from `//extensions/common/api:mojom` gets unconditionally included.

**Comment by MarshallOfSound** [comment]
Electron doesn't have the bandwidth to test and maintain all the possible gn arg permutations that the underlying build system supports. We support our `testing` and `release` configs and will ensure those work, that's it.

We do accept PRs for folks wanting to fix other configurations as long as the change isn't too crazy but it's not a maintenance burden that we ourselves take on.

**Comment by brjsp** [comment]
I'm only mentioning that flag in particular because that seems to be a regression — see #23307 for instance. (Unfortunately that happened before i started maintaining the package, so could not have noticed it earlier)
