### ISSUE TITLE
[Bug]: WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.

### ISSUE THREAD

**Issue by elkon028** [electron/electron#41853]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.4.1 (23E224)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

29.3.0

### Expected Behavior

main:
```js
await desktopCapturer.getSources({ types: ['screen', 'window'] })
....
```
renderer:
```js
const { data } = await IPCRequest.system.getSources()
await navigator.mediaDevices.getUserMedia({
        audio: false,
        video: {
          // @ts-ignore
          mandatory: {
            chromeMediaSource: 'desktop',
            chromeMediaSourceId: data[0].id
          }
        }
      })
```

### Actual Behavior

```txt
2024-04-14 00:04:05.403 Electron[44366:1365647] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
2024-04-14 00:04:06.444 Electron Helper (Plugin)[44383:1366041] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
```

**Comment by MarshallOfSound** [comment]
You can ignore this warning, it is a deprecation warning from the OS that will be fixed in upstream Chrome
