### ISSUE TITLE
[Bug]: process.exit does return and is not exiting synchronously when called in async function

### ISSUE THREAD

**Issue by IIIMADDINIII** [electron/electron#41866]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2

### What arch are you using?

x64

### Expected Behavior

When i run electron with the following code, it should not log test to the console:
```
const { setTimeout } = require("timers/promises");

async function main() {
  await setTimeout(100);
  process.exit();
  console.log("test");
}

main()
```

### Actual Behavior

test is logged to the console.
So ```process.exit()``` doeas return wenn called in an async function after an await.
The same code un in node will not log test.

### Testcase Gist URL

https://gist.github.com/61fb0bb05e0da37bb1b2da6ff78baacc

**Comment by codebytere** [comment]
@IIIMADDINIII see https://github.com/electron/electron/pull/32831 - this has been tried before and is unfortunately a pretty tricky problem!

**Comment by IIIMADDINIII** [comment]
Interestingly i can not reproduce the mentioned issue #32060 in #32831 with the provided Gist (https://gist.github.com/RaisinTen/ced9932fd0d76dd30ec72758bc18bc51) in Electron Fiddle and Electron v28.3.0.

I will try the Solution of the Pull Request #32831 locally.

**Comment by georgexu99** [comment]
Adding a status/won't fix, see above comments 🙇 The current proposed solution involves a breaking change that will likely cause more problems than it fixes (https://github.com/electron/electron/pull/32831).

**Comment by codebytere** [comment]
Closing in agreement with above.
