### ISSUE TITLE
[Bug]: ReadableStream is malformed when protocol.handle'd

### ISSUE THREAD

**Issue by mnvr** [electron/electron#41872]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.x, 29.x

### What operating system are you using?

macOS

### Operating System Version

macOS 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

1. [main] Define a custom protocol

```js
protocol.handle("myscheme", async (request) => {
    try {  await fs.rm("/tmp/myscheme.txt")   } catch {}
    for await (const p of request.body) {
        await fs.appendFile("/tmp/myscheme.txt", p)
    }
    return new Response("", { status: 200 })
})
```

2. [renderer] Make a request with the request body as a stream using standard web fetch + duplex "half"

```js
const dataStream = () =>
    new ReadableStream({
        async start(controller) {
            for (let i = 0; i < 10; i++) {
                // await wait(1000)
                controller.enqueue(Array(1024 * 128).fill(+i).join("\n"))
            }
            controller.close()
        },
    }).pipeThrough(new TextEncoderStream())

fetch(new Request("myscheme://host", {
    method: "POST",
    body: dataStream(),
    duplex: "half",
}))
```

3. [main] Verify the data (e.g. using shasum)

Expectation: The stream should come through intact.

### Actual Behavior

The stream gets malformed.

In the attached fiddle gist, you can see two buttons. 
- **Send** button sends the entire payload in the request body
- **Stream** button streams the payload in the request body (to pass a stream as the request body, we also need to set "duplex" to "half")

**Send** always works.
```
$ shasum /tmp/myscheme.txt
d269175ac71ed60bb96f08881c39453c8e8d7020  /tmp/myscheme.txt
```

**Stream** doesn't work. The resulting data (as evidenced by seeing its shasum) is different each time.

### Testcase Gist URL

https://gist.github.com/mnvr/e08d9f4876fb8400b7615347b4d268eb

### Additional Information

I hope I'm just missing something silly, but I tried to boil down the issue to a isolated gist, and I'm out of ideas about what to try next. I've tried with both the latest beta and the older stable 29.x.

FWIW, if the data is less than one chunk, the streaming seems to work fine (but then I guess it's not really streaming).

The gist also has a commented out await in the code that enqueues data to the stream. If we uncomment this, Stream starts to work - by adding a 1 second delay between these enqueues. But I'm not sure about this, smaller delays didn't work, and it is also possible that I've just been getting lucky with these 1 second delays.

**Comment by nornagon** [comment]
Thanks for the report, #41894 should address this!

**Comment by mnvr** [comment]
Thank you!
