### ISSUE TITLE
[Bug]: Window Not Displaying Over Dock in Fullscreen Mode

### ISSUE THREAD

**Issue by ayushete02** [electron/electron#41874]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.3.0

### What operating system are you using?

macOS

### Operating System Version

14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I am developing an application using Electron where I need the application window to display in full-screen mode, covering all screen elements including the dock (on macOS) 

### Actual Behavior

The window does not extend over the dock; instead, it adjusts to fit the available space above the dock, not utilizing the full screen.

![Screenshot 2024-04-16 at 4 43 33 PM](https://github.com/electron/electron/assets/75811912/09c8a3db-a660-4d14-9531-366ca90426ca)

**Comment by ayushete02** [comment]
https://github.com/electron/electron/assets/75811912/57eb9aa2-15ad-4573-9226-039d232554f2

Hello, Thank you for your guidance. I appreciate the suggestion to use Electron Fiddle for creating a minimal test case. Here is a more detailed context of the issue:

I am developing a video recorder application that includes a feature allowing users to select a specific region of the screen to record. While this feature functions correctly on Windows, I am facing a challenge on macOS. Despite setting the window to fullscreen mode, it does not overlay the dock and the top taskbar, which is crucial for the functionality of the region selection feature.

To provide a clearer picture i shared you a video, the application creates a fullscreen overlay on the desktop under which users can define the recording area. However, on macOS, the overlay window does not cover the entire screen, specifically leaving the dock and top taskbar areas exposed. This issue limits the selectable region and affects the user experience.

**Comment by ayushete02** [comment]
https://gist.github.com/ayushete02/71e52e07c6090d6c7ddfb4e2ab237c49

**Comment by ayushete02** [comment]
Hello,

Thank you for your insights on the macOS behavior with BrowserWindow. I understand that the observed behavior aligns with macOS's default handling of within-desktop fullscreen applications.

However, I have noticed that some Electron apps seem to achieve a truly immersive fullscreen experience that covers the dock and top taskbar. Could you possibly provide any insights or documentation on how these applications might be circumventing the default macOS limitations?

Additionally, I am considering a potential solution where I could programmatically hide the dock to allow the fullscreen window to cover the entire screen. Is there a recommended approach within Electron to achieve this? Any guidance or references to similar implementations would be extremely helpful as I navigate this part of the project.

Thank you for your continued support and looking forward to your advice.

**Comment by rahulbansal16** [comment]
@ayushete02 were you able to solve it?
