### ISSUE TITLE
 electron应用在分辨率为1600*900的时候，出现亮线问题

### ISSUE THREAD

**Issue by tonglin-ai** [electron/electron#41878]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.5

### What operating system are you using?

Windows

### Operating System Version

Windows10

### What arch are you using?

x64

### Expected Behavior

electron版本是18.3.5
![1713342971884](https://github.com/electron/electron/assets/59386561/98bad015-c942-4773-871c-479c7c13a7a1)

### Actual Behavior

把分辨率设置为1600*900，打开应用，放大窗口就会出现亮线问题
![1713342971884](https://github.com/electron/electron/assets/59386561/92602215-6141-4068-820b-ca6f543f85fa)

**Comment by codebytere** [comment]
Electron 18 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

**Comment by tonglin-ai** [comment]
> Electron 18 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

So which version can switching to solve this problem？

**Comment by tonglin-ai** [comment]
> Electron 18 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

But after upgrading to version 28.0.0, I still encountered the issue of bright lines
![66571ff80aaa19fd2fdfdbb1cf3d2b9](https://github.com/electron/electron/assets/59386561/2a53cfaf-8a5c-4cd7-8b0b-a0b00148adf2)

**Comment by tonglin-ai** [comment]
> > Electron 18 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.
> 
> But after upgrading to version 28.0.0, I still encountered the issue of bright lines ![66571ff80aaa19fd2fdfdbb1cf3d2b9](https://private-user-images.githubusercontent.com/59386561/323443473-2a53cfaf-8a5c-4cd7-8b0b-a0b00148adf2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDcxNTYsIm5iZiI6MTcxMzQwNjg1NiwicGF0aCI6Ii81OTM4NjU2MS8zMjM0NDM0NzMtMmE1M2NmYWYtOGE1Yy00Y2Q3LThiMGItYTBiMDAxNDhhZGYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAyMjA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZjBjNzI1OTU3Y2FiOTJkMzY2NjhiY2U5ODVhYTlmZDU2Yjk5NjVkZGZlNzQ4ODA1MDEyOWVkMGM2YWZmZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qdetPuz9FvuXWzma6u0_fjKp2zwghB9bGG_Qa7fXlSI)

sorry，Restart the client, the issue is resolved

**Comment by tonglin-ai** [comment]
> Electron 18 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

I have upgraded to version 27.0.0 now. Is this version okay on Windows 7

**Comment by mlaurencin** [comment]
Electron no longer supports Windows 7 as of version 23. You can read further in our blog post [here](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice)

The version of Electron you reported this initially had been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

If you’re still experiencing this issue in Electron 28.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m keeping the `blocked/need-info` label in place for the above reasons. This issue will be closed 10 days from now if there is no response. If your problem is resolved, please feel free to close the issue yourself.

Thanks in advance! Your help is appreciated.

**Comment by tonglin-ai** [comment]
> After upgrading to version 27, there was still a problem with the bright lines, which only appeared elsewhere

![ab2df357b4f26668b4603eacbb1bb9b](https://github.com/electron/electron/assets/59386561/eb31e963-cea4-48c1-bbc6-26ccd9aeb877)

**Comment by mlaurencin** [comment]
I've added this new  `blocked/need-repro` label because due to time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Please provide a standalone testcase that displays your issue in version 28 or above.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
