### ISSUE TITLE
 [Bug]: process.env.npm_package_version cannot be read in product

### ISSUE THREAD

**Issue by FlyBooks** [electron/electron#41870]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.9.8

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Expected Behavior

i wanna read the version data in the package.json in the production environment. That means process.env.npm_package_version has value in production environment.

### Actual Behavior

only in the development mode, process.env.npm_package_version has value. And in the production mode, its value is undefined.

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
