### ISSUE TITLE
[Bug]: App. DisableHardwareAcceleration() affect transparent effect

### ISSUE THREAD

**Issue by Halecoder** [electron/electron#41891]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v29.1.5

### What operating system are you using?

Windows

### Operating System Version

版本	Windows 10 企业版 版本号	22H2 安装日期	‎2023/‎5/‎27 操作系统内部版本	19045.4170 体验	Windows Feature Experience Pack 1000.19054.1000.0

### What arch are you using?

x64

### Expected Behavior

I am setting up a startup page and I have to disable hardware acceleration due to some issues
When I enable `app. DisableHardwareAcceleration ()`, I found that I had a transparent attribute failure,  when I notes `app. DisableHardwareAcceleration ()`, it shall, in accordance with the expected effect

### Actual Behavior

The startup window does not become transparent

### Testcase Gist URL

https://gist.github.com/Halecoder/fa7fe70a629e772cd8de293b0bd4cb17

### Additional Information

![image](https://github.com/electron/electron/assets/75030331/f2b1ee47-3960-4bb2-868a-878615889c34)
![image](https://github.com/electron/electron/assets/75030331/2699cd36-b7c0-43ac-bc9d-537efd0d95cf)

**Comment by zxzxac110** [comment]
on this a , I don't know

**Comment by mlaurencin** [comment]
![image](https://github.com/electron/electron/assets/35157522/e24df579-8266-4fe6-b7b7-b9a2a01c5c82)
![image](https://github.com/electron/electron/assets/35157522/8258db89-37ca-4718-8d7d-1ddc2413e431)

Testing with Windows 10 I am unable to reproduce this issue. Are there any other settings within the gist that need to be modified in order for this problem to occur? 

Setting `blocked/need-info` for this reason. The issue will be closed in 10 days if there is no response.
