### ISSUE TITLE
[Bug]: What do I need to do to package an application with a Chinese name?

### ISSUE THREAD

**Issue by ruyudeshuileling** [electron/electron#41912]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0

### What operating system are you using?

Windows

### Operating System Version

windows10

### What arch are you using?

x64

### Expected Behavior

打包一个中文名的应用，我需要怎么做？

### Actual Behavior

打包一个中文名的应用，我需要怎么做？
This is my configuration in package.js
{
"Name": "Chinese Name",
"Version": "1.0.0",
"Main": "main. js",
"Scripts":{
"Start": "Electron forge start",
"Test": "echo" Error: no test specified "&&exit 1",
"Package": "Electron forge package",
"Make": "Electron forge make"
},
   
"Author": "ryds",
"License": "ISC",
"Description": "General demo testing",
"DevDependencies":{
"@ electron forge/cli": "^ 7.3.0",
"@ electron forge/maker deb": "^ 7.3.0",
"@ electron forge/maker rpm": "^ 7.3.0",
"@ electron forge/maker Squirrel": "^ 7.3.0",
"@ electron forge/maker zip": "^ 7.3.0",
"@ electron forge/plugin auto unpack natives": "^ 7.3.0",
"Electron": "^ 29.1.4"
},
"Dependencies":{
"@ electron forge/plugin uses": "^ 7.3.0",
"Electron squirrel startup": "^ 1.0.0"
}
}

**Comment by Halecoder** [comment]
老兄，百度这些一下呗，为啥这个不是bug还提个issue呢？
```js
{
  "name": "english-name",
  "version": "1.0.0",
  "main": "electron/main.js",
  "private": true,
  "description": "xxx",
  "author": "xxx",
  "license": "MIT",
  "keywords": [
    "typescript",
    "Vue3",
    "electron-desktop"
  ],
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "preview": "vite preview",
    "electron": "cross-env NODE_ENV=development electron . ",
    "electron:serve": "concurrently -k \"npm run dev\" \"npm run electron\"",
    "electron:build": "vite build && electron-builder",
    "rebuild": "electron-rebuild -f -w sqlite3"
  },
  "config": {
    "electron": {
      "mirror": "http://npm.taobao.org/mirrors/electron/"
    }
  },
  "build": {
    "appId": "com.hl.app",
    "productName": "这里设置打包中文名",
    "copyright": "Copyright © 2024 <HL>",
    "buildDependenciesFromSource":true,
    "nodeGypRebuild": false,
    "npmRebuild": false,
    "publish": [
      {
        "provider": "generic",
        "url": "http://localhost:8888/",
        "channel": "latest"
      }
    ],
    "mac": {
      "icon": "./wj-logo.ico",
      "category": "public.app-category.productivity",
      "artifactName": "${productName}_${version}.${ext}",
      "target": [
        "dmg",
        "zip"
      ]
    },
    "win": {
      "icon": "./wj-logo.ico",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64"
          ]
        }
      ]
    },
    "nsis": {
      "oneClick": false,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "installerIcon": "./wj-logo.ico",
      "uninstallerIcon": "./wj-logo.ico",
      "installerHeaderIcon": "./wj-logo.ico",
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true,
      "shortcutName": "这里设置快捷方式中文名"
    },
    "files": [
      "dist/**/*",
      "electron/**/*"
    ],
    "directories": {
      "buildResources": "assets",
      "output": "dist_electron"
    }
  },
```
无意义的issue下次不要提了哦😊

**Comment by Halecoder** [comment]
解决了，记得关闭issue哈

**Comment by ruyudeshuileling** [comment]
您说的这个方法我在搜索引擎和chatgpt看到过，但是对electron forge没有作用，所以前来咨询。
不过刚刚在electron forge仓库issue看到了解决方法，问题已解决，同时感谢您及时的回复
{
  name: '@electron-forge/maker-deb',
  config: {
    options: {
      maintainer: 'The Forgers',
      homepage: 'https://example.com',
      icon: 'path/to/icon.svg'
      productName:"中文名",
      name:"packageName"
    }
  }
}
