### ISSUE TITLE
[Bug]: openvino-node doesn't work...

### ISSUE THREAD

**Issue by turbobuilt** [electron/electron#41913]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.x.x (tried on 18 and 13 as well with no luck)

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

This line in main.js causes a crash on windows 11 x64:

const { addon: ov } = require('openvino-node');
//use to make sure it gets bundled
const core = new ov.Core();

I ran the same file in node, and it works fine. There are no logs that are useful just a crash.  I don't know how to debug.

[1032:0420/222218.558:ERROR:crashpad_client_win.cc(814)] not connected

That's the only output.

### Actual Behavior

The app doesn't do anything anymore.

**Comment by dsanders11** [comment]
Thanks for reaching out and logging this issue! Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. As such, I'm closing this issue.

**Comment by turbobuilt** [comment]
I think it makes sense to make sure node addons work... but I'm not an admin on this project. Is there a reason why it's not considered a bug if a node compatible module doesn't work?

I'm not trying to criticize, I just would say that that's a showstopper for a lot of people.  If it's not gonna work, or freeze... shouldn't it have some kind of error message? I know it's hard, but this is critical for people trying to debug.  I did a ton of debugging, and it's actually hanging on the require statement that requires the internal .node file, I think.  I'm not gonna argue cause this is open source stuff, and we are just glad for your time.  But I think 100% node compatibility should be a goal.
