### ISSUE TITLE
[Bug]: getCurrentWindow().close() causing an error

### ISSUE THREAD

**Issue by dengxueru** [electron/electron#41920]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 企业版   22H2

### What arch are you using?

x64

### Expected Behavior

**Create code for the main window**

`export function createMainWindow() {
    const win = new BrowserWindow({
        ...loginWinSize,
        frame: false,
        titleBarStyle: 'hidden',
        trafficLightPosition: { x: 5, y: 24 },
        minimizable: false,
        maximizable: false,
        resizable: false,
        title: 'Henglink',
        titleBarOverlay: isMac,
        webPreferences: {
            ...webPreferences,
            navigateOnDragDrop: false,
        },
        show: false,
        icon: dockIconPath,
    })

    win.name = EWinName.MAIN
    const scaleFactor = screen.getPrimaryDisplay().scaleFactor
    if (scaleFactor !== 1) {
        win.webContents.setZoomFactor(scaleFactor)
    }
    win.removeMenu()

    if (process.env.WEBPACK_DEV_SERVER_URL && isDevelopment) {
        //win.webContents.openDevTools()
    } else {
        createProtocol('app')
    }
    win.loadURL(appUrl)
    mainWin = win
    // win.webContents.openDevTools()
    win.on('will-resize', onMainWinWillResize)
    win.webContents.on('new-window', (e, url) => {
        e.preventDefault()
        handleWindowOpenWin({
            url,
        })
    })
    win.on('close', (e) => {
        if (!globalData.willQuitApp) {
            e.preventDefault()
            if (mainWin) {
                if (mainWin.isFullScreen()) {
                    mainWin.once('leave-full-screen', () => {
                        mainWin.hide()
                    })
                    mainWin.setFullScreen(false)
                } else {
                    mainWin.hide()
                }
            }
        }
    })
    win.on('ready-to-show', () => {
        win.show()
    })

    win.on('unmaximize', () => {
        mainWin.webContents.send(EIpcRendererChannel.SET_TOPBAR_CONTROL, {
            name: EIpcRendererEvent.UN_MAXIMIZE,
        })
    })

    win.on('maximize', (event: Event) => {
        event.preventDefault()
        const { width, height } = screen.getPrimaryDisplay().workAreaSize
        mainWin.setMaximumSize(width, height)
        mainWin.getMaximumSize()
        mainWin.setSize(width, height)
        mainWin.center()
        mainWin.webContents.send(EIpcRendererChannel.SET_TOPBAR_CONTROL, {
            name: EIpcRendererEvent.MAXIMIZE,
        })
    })

    win.on('hide', () => {
        fileSizeReport()
    })

    win.on('minimize', () => {
        fileSizeReport()
    })

    return win
}`

### Actual Behavior

**### first**

![image](https://github.com/electron/electron/assets/38432260/74f7379e-108c-4efe-9c47-c15b53d4c15d)
![image](https://github.com/electron/electron/assets/38432260/ff1dbf12-e632-4f5b-b245-a5fd19989ce3)

Error occurred when using instruction **getCurrentWindow().close()** 

After using it for a period of time, the customer may encounter this error message

This is an occasional occurrence

![image](https://github.com/electron/electron/assets/38432260/2ec92cd8-a251-4165-b0f0-946e9c1e02a0)

**### second**

Error occurred when using instruction **getCurrentWindow().show()** 

![image](https://github.com/electron/electron/assets/38432260/1bb05c9a-cf7b-465d-8511-76cb43dfda45)

**Comment by codebytere** [comment]
Electron 13.6.3  isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

**Comment by dengxueru** [comment]
> Electron 13.6.3 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

This problem has been bothering me for a long time

Using 13.6.3 has relatively good compatibility with low configurations

Or is there any way to address this fault tolerance

**Comment by codebytere** [comment]
@dengxueru we do not fix issues in unsupported versions. As noted above, for us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron.
