### ISSUE TITLE
[Bug]:  Inconclusive Parsing of Content-Disposition Header 

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#41939]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.0

### What operating system are you using?

Windows

### Operating System Version

Microsoft Windows [Version 10.0.19045.4291]

### What arch are you using?

x64

### Expected Behavior

The "content-disposition" header shouldn't be modified and work as in Chromium. Please, take a look at the screenshots I've attached. The problem is in the function HttpResponseHeadersToV8 - https://github.com/electron/electron/blob/main/shell/browser/api/electron_api_web_request.cc#L93C22-L93C45

### Actual Behavior
![1a](https://github.com/electron/electron/assets/5815794/38dcc068-fd00-4c6d-a489-c1a46deeff0e)
![2a](https://github.com/electron/electron/assets/5815794/34925501-ae06-4d80-a506-2540f99581be)

### Testcase Gist URL

https://gist.github.com/gdavidkov/08a8edae420a5b30e9f855f0ebb75a63

### Additional Information

Ref: https://github.com/electron/electron/pull/25961
PR: https://github.com/electron/electron/pull/31669

**Comment by gdavidkov** [comment]
When I try to add the missing information to the header, I encounter the following problem:
![image](https://github.com/electron/electron/assets/5815794/52a48983-0962-4e7d-b96d-ac54a8ba8444)
![image](https://github.com/electron/electron/assets/5815794/52357763-4bc7-4018-9bac-4ca69b27ece1)

**Comment by gdavidkov** [comment]
If the header is in not the correct format, the filename is empty. I think we should return the original header like in the Chromium.
![3a](https://github.com/electron/electron/assets/5815794/98362441-1f64-47c4-a2bd-367a1e28da89)
![4a](https://github.com/electron/electron/assets/5815794/f06282bb-05d1-48b2-9752-1b6d7f97c850)
![5](https://github.com/electron/electron/assets/5815794/7502b6a3-cbef-4873-823c-14b14e56098c)

**Comment by alfein** [comment]
This bug is happening due to a change that was made in this [pull request](https://github.com/electron/electron/pull/25961).  Unfortunately, if the onHeadersReceived is used and client code needs to modify headers, the original value of the constent-disposition header is lost.  Moreover the new value incorrectly includes a space before the word attachment and it drops the value of filename*, which is what should be used to avoid issues with filename encoding on the client side.

The PR should be undone.  Reference to similar [comment](https://github.com/electron/electron/issues/25628#issuecomment-1277780004)

**Comment by alfein** [comment]
Bump

**Comment by ScarboroughCoral** [comment]
issue also in electron 19.1.9, any solution?
