### ISSUE TITLE
[Bug]: TypeError: win.setTitleBarOverlay is not a function

### ISSUE THREAD

**Issue by imp-oh** [electron/electron#41938]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.0

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Last Known Working Electron version

30.0.1

### Expected Behavior

```js
// In the main process.
const { BaseWindow, WebContentsView, app } = require('electron')

app.whenReady().then(() => {
  const win = new BaseWindow({ width: 800, height: 600 ,  titleBarStyle: 'hidden',})

  win.setTitleBarOverlay({
    color: '#DEE1E6',
    symbolColor: 'black',
    height: 30
  })

  const leftView = new WebContentsView()
  leftView.webContents.loadURL('https://electronjs.org')
  win.contentView.addChildView(leftView)

  // const rightView = new WebContentsView()
  // rightView.webContents.loadURL('https://github.com/electron/electron')
  // win.contentView.addChildView(rightView)

  leftView.setBounds({ x: 0, y: 0, width: 400, height: 600 })
  // rightView.setBounds({ x: 400, y: 0, width: 400, height: 600 })
})

```

### Actual Behavior

Want to support setTitleBarOverlay api

### Additional Information

(node:20488) UnhandledPromiseRejectionWarning: TypeError: win.setTitleBarOverlay is not a function
    at E:\Hui\Github\ce-hub\cehub-browser-window\out\main\index.js:18:9
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:20488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by AliasT** [comment]
seems only works with BrowserWindow.
