### ISSUE TITLE
Badge Icon / Counter for Unity Launcher Icon?

### ISSUE THREAD

**Issue by zweicoder** [electron/electron#4193]
Is there a way to set the counter on the launcher icon to show number of notifications or similar?

**Comment by zweicoder** [comment]
Found the (Unity Api)[https://wiki.ubuntu.com/Unity/LauncherAPI] with support for counters if anyone knows how to add it in

**Comment by bengotow** [comment]
Hey @zweicoder — thanks for digging that up! I work on Nylas N1 and we've had a few requests for this feature. (https://github.com/nylas/N1/issues/408) It definitely seems like that API is the right one. I think that this class (https://github.com/atom/electron/blob/0e2ac2d80226c652042c2f8819b596876119d6bd/atom/browser/browser_linux.cc) needs to implement these functions (currently only implemented on Mac OS X):

```
  // Set/Get dock's badge text.
  void DockSetBadgeText(const std::string& label);
  std::string DockGetBadgeText();
```

**Comment by andreaolivato** [comment]
Hi, any ETA on this? It's really an important missing feature for Desktop integration.

**Comment by paulcbetts** [comment]
@andreaolivato We'll definitely take a PR for it, but nobody is working on this currently

**Comment by JMarteF** [comment]
Hey guys, can anyone please guided me on how to test this feature on the whatsapp.web app ? Im currently trying to include the counter feature on linux but It doesnt seem to work.

**Comment by jnugh** [comment]
@JMarteF writing into this old issue might not be very helpful as there is only a limited audience. Also please don't paste the same question into multiple unrelated issues.
Did you read the docs?https://github.com/electron/electron/blob/master/docs/api/app.md#appsetbadgecountcount-linux-macos

Especially this part might not be something you expect when just using the API: 
> Note: Unity launcher requires the existence of a .desktop file to work, for more information please read Desktop Environment Integration.

If this does not work and you think there is a bug you should probably create a new issue.

**Comment by JMarteF** [comment]
@jnugh I apologize for that. And yes i did check the docs for info on the API but for some reason it does not work. I figured that since you guys implemented it before you could've guide me through the process of implementing it myself but I will go ahead and open a new issue. Thank you!

**Comment by jayarjo** [comment]
Same problem here. @JMarteF have you figured it out? Or filed another issue?
