### ISSUE TITLE
[Bug]: addChildView会崩溃

### ISSUE THREAD

**Issue by code-small-white** [electron/electron#41934]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.4.1 (23E224)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

可以正常工作

### Actual Behavior

直接退出

### Testcase Gist URL

https://gist.github.com/24a6cac9a6a3cd762c8f8299d9f5c02d

### Additional Information

反注释44行,可以正常运行

**Comment by AliasT** [comment]
https://source.chromium.org/chromium/chromium/src/+/main:ui/views/view.cc;l=3094;bpv=1;bpt=1?q=AddChildViewAt
chromium will reorder same view while electron creates new, then check failed.

**Comment by code-small-white** [comment]
> https://source.chromium.org/chromium/chromium/src/+/main:ui/views/view.cc;l=3094;bpv=1;bpt=1?q=AddChildViewAt chromium will reorder same view while electron creates new, then check failed.

那为什么不用settimeout的时候就正常

**Comment by AliasT** [comment]
跟setTimeout没关系。

**Comment by code-small-white** [comment]
> 跟setTimeout没关系。

那我那个例子,在settimeout外面添加两次view,再或者添加6次,都不会报错,都是正常执行,但是在settimeout里面添加就崩溃了,这不证明多多少少和settimeout有点关系?

**Comment by codebytere** [comment]
Combining with https://github.com/electron/electron/issues/41974
