### ISSUE TITLE
[Bug]: clipboard.read cannot get anything.

### ISSUE THREAD

**Issue by saltfish233** [electron/electron#41955]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.3.1

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

I wish use clipboard.read to get all format of clipboard data.
```
        for(let format of clipboard.availableFormats()) {
            console.log(clipboard.read(format))
        }
```

### Actual Behavior

read cannnot return anything.

**Comment by wangborong12345** [comment]
example of this bug:https://gist.github.com/wangborong12345/e2a7c608234447e2c5dcd021b8abfcc6
