### ISSUE TITLE
[Bug]: Calling .center() on BrowserWindow with parent now centers relative to parent instead of screen

### ISSUE THREAD

**Issue by neobyteUK** [electron/electron#41956]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2 19045.4291

### What arch are you using?

x64

### Last Known Working Electron version

27

### Expected Behavior

As per documentation for .center() : "Moves window to the center of the screen.".

https://www.electronjs.org/docs/latest/api/browser-window#wincenter

### Actual Behavior

When a BrowserWindow has a parent window defined, calling .center() on the child centers the window relative to the parent, not the screen.

### Testcase Gist URL

https://gist.github.com/yangannyx/277e71dc348b289cde39e94b4b59d683

### Additional Information

This issue does not exist in 27.3.11 but DOES exist in 28.0.0 onwards.

Credit to yangannyx for creating the gist in response to my initial query regarding this on discord.

**Comment by yangannyx** [comment]
Hello! To add to this, I'm seeing a few differences in behavior between MacOS and Windows on child windows.
1. MacOS child windows get centered relative to the screen, while Windows child windows become centered relative to the parent screen.
2. Dragging the parent window in MacOS will also drag the child windows to preserve their distance/position to the parent window. On Windows, dragging the parent window has no effect on the child window's position.

If it's manageable, I think this would be cool to parameterize in some way

**Comment by codebytere** [comment]
Looks like this might be an upstream-instigated change, as our Windows implementation hasn't changed in ~6 years:

https://github.com/electron/electron/blob/76f7bbb0a8db04c002293b2753f24146518737b5/shell/browser/native_window_views.cc#L1073

**Comment by codebytere** [comment]
Good news and bad news: I found the CL that caused this after a quick sprint through Chromium: https://chromium-review.googlesource.com/c/chromium/src/+/4916277, but the CL indicates the previous behavior was unintended and that the new behavior (centering relative to parent) is correct and intended. I'll see what the potential options are!

**Comment by codebytere** [comment]
@yangannyx if you could, it'd be helpful to make this:

> Dragging the parent window in MacOS will also drag the child windows to preserve their distance/position to the parent window. On Windows, dragging the parent window has no effect on the child window's position.

its own issue!

**Comment by yangannyx** [comment]
@codebytere, I actually see there's existing electron documentation that describes the drag behavior discrepancy [here](https://www.electronjs.org/docs/latest/api/browser-window#platform-notices). I'm leaning towards not opening an issue for this reason
