### ISSUE TITLE
[Bug]: Unexpected Massive Download of Chromium Files During Electron Update

### ISSUE THREAD

**Issue by lautarovculic** [electron/electron#41965]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.9.8-6

### What operating system are you using?

Other (specify below)

### Operating System Version

Arch Linux - 6.8.7-arch1-1

### What arch are you using?

x64

### Expected Behavior

I expected the Electron update to proceed without a massive download of additional files. Typically, Electron updates do not involve downloading a large number of Chromium-related files. I anticipated the update to be carried out efficiently and without a significant increase in disk usage.

### Actual Behavior

The Electron update unexpectedly triggered a massive download of Chromium-related files, resulting in a significant increase in disk usage. This behavior was unexpected and not consistent with previous Electron updates, which typically do not involve such extensive downloads.

### Additional Information

In **~/.cache/paru/clone/electron25**
`du -h -s -c .`
Output: **80GB**

Files & Folders:

- **chromium-mirror_buildtools_clang_format_script
- chromium-mirror_buildtools_third_party_libc++_trunk
- chromium-mirror_buildtools_third_party_libc++abi_trunk
- chromium-mirror_buildtools_third_party_libunwind_trunk
- chromium-mirror_chrome_test_data_perf_canvas_bench
- chromium-mirror_chrome_test_data_perf_frame_rate_content
- chromium-mirror_chrome_test_data_xr_webvr_info
- chromium-mirror_media_cdm_api
- chromium-mirror_native_client
- chromium-mirror_net_third_party_quiche_src
- chromium-mirror_third_party_android_ndk
- chromium-mirror_third_party_angle
- chromium-mirror_third_party_angle_third_party_glmark2_src
- chromium-mirror_third_party_angle_third_party_rapidjson_src
- chromium-mirror_third_party_angle_third_party_VK-GL-CTS_src
- chromium-mirror_third_party_boringssl_src
- chromium-mirror_third_party_breakpad_breakpad
- chromium-mirror_third_party_cast_core_public_src
- chromium-mirror_third_party_catapult
- chromium-mirror_third_party_ced_src
- chromium-mirror_third_party_centipede_src
- chromium-mirror_third_party_cld_3_src
- chromium-mirror_third_party_colorama_src
- chromium-mirror_third_party_content_analysis_sdk_src
- chromium-mirror_third_party_cpuinfo_src
- chromium-mirror_third_party_crc32c_src
- chromium-mirror_third_party_cros-components_src
- chromium-mirror_third_party_cros_system_api
- chromium-mirror_third_party_crossbench
- chromium-mirror_third_party_dav1d_libdav1d
- chromium-mirror_third_party_dawn
- chromium-mirror_third_party_dawn_build
- chromium-mirror_third_party_dawn_buildtools
- chromium-mirror_third_party_dawn_testing
- chromium-mirror_third_party_dawn_third_party_abseil-cpp
- chromium-mirror_third_party_dawn_third_party_glfw
- chromium-mirror_third_party_dawn_third_party_jinja2
- chromium-mirror_third_party_dawn_third_party_markupsafe
- chromium-mirror_third_party_dawn_third_party_protobuf_electron25
- chromium-mirror_third_party_dawn_third_party_zlib
- chromium-mirror_third_party_dawn_tools_clang
- chromium-mirror_third_party_depot_tools
- chromium-mirror_third_party_devtools-frontend_src
- chromium-mirror_third_party_dom_distiller_js_dist
- chromium-mirror_third_party_eigen3_src
- chromium-mirror_third_party_electron_node
- chromium-mirror_third_party_emoji-segmenter_src
- chromium-mirror_third_party_expat_src
- chromium-mirror_third_party_farmhash_src
- chromium-mirror_third_party_ffmpeg
- chromium-mirror_third_party_flac
- chromium-mirror_third_party_flatbuffers_src
- chromium-mirror_third_party_fontconfig_src
- chromium-mirror_third_party_fp16_src
- chromium-mirror_third_party_freetype-testing_src
- chromium-mirror_third_party_freetype_src
- chromium-mirror_third_party_fxdiv_src
- chromium-mirror_third_party_gemmlowp_src
- chromium-mirror_third_party_google_benchmark_src
- chromium-mirror_third_party_googletest_src
- chromium-mirror_third_party_grpc_src
- chromium-mirror_third_party_harfbuzz-ng_src
- chromium-mirror_third_party_highway_src
- chromium-mirror_third_party_hunspell_dictionaries
- chromium-mirror_third_party_icu
- chromium-mirror_third_party_jsoncpp_source
- chromium-mirror_third_party_leveldatabase_src
- chromium-mirror_third_party_libaddressinput_src
- chromium-mirror_third_party_libaom_source_libaom
- chromium-mirror_third_party_libavif_src
- chromium-mirror_third_party_libdrm_src
- chromium-mirror_third_party_libFuzzer_src_electron25
- chromium-mirror_third_party_libgav1_src
- chromium-mirror_third_party_libipp_libipp
- chromium-mirror_third_party_libjpeg_turbo
- chromium-mirror_third_party_liblouis_src
- chromium-mirror_third_party_libphonenumber_dist
- chromium-mirror_third_party_libprotobuf-mutator_src
- chromium-mirror_third_party_libsrtp
- chromium-mirror_third_party_libsync_src
- chromium-mirror_third_party_libvpx_source_libvpx
- chromium-mirror_third_party_libwebm_source
- chromium-mirror_third_party_libwebp_src
- chromium-mirror_third_party_libyuv
- chromium-mirror_third_party_lss
- chromium-mirror_third_party_material_color_utilities_src
- chromium-mirror_third_party_minigbm_src
- chromium-mirror_third_party_nan
- chromium-mirror_third_party_nasm
- chromium-mirror_third_party_nearby_src
- chromium-mirror_third_party_neon_2_sse_src
- chromium-mirror_third_party_openh264_src
- chromium-mirror_third_party_openscreen_src
- chromium-mirror_third_party_openscreen_src_third_party_tinycbor_src
- chromium-mirror_third_party_openxr_src
- chromium-mirror_third_party_ots_src
- chromium-mirror_third_party_pdfium
- chromium-mirror_third_party_perfetto
- chromium-mirror_third_party_pthreadpool_src
- chromium-mirror_third_party_pyelftools
- chromium-mirror_third_party_pywebsocket3_src
- chromium-mirror_third_party_quic_trace_src
- chromium-mirror_third_party_re2_src
- chromium-mirror_third_party_ruy_src
- chromium-mirror_third_party_securemessage_src
- chromium-mirror_third_party_skia
- chromium-mirror_third_party_smhasher_src
- chromium-mirror_third_party_snappy_src
- chromium-mirror_third_party_sqlite_src
- chromium-mirror_third_party_swiftshader
- chromium-mirror_third_party_text-fragments-polyfill_src
- chromium-mirror_third_party_tflite_src
- chromium-mirror_third_party_ukey2_src
- chromium-mirror_third_party_vulkan-deps
- chromium-mirror_third_party_vulkan-deps_glslang_src
- chromium-mirror_third_party_vulkan-deps_spirv-cross_src
- chromium-mirror_third_party_vulkan-deps_spirv-headers_src
- chromium-mirror_third_party_vulkan-deps_spirv-tools_src
- chromium-mirror_third_party_vulkan-deps_vulkan-headers_src
- chromium-mirror_third_party_vulkan-deps_vulkan-loader_src
- chromium-mirror_third_party_vulkan-deps_vulkan-tools_src
- chromium-mirror_third_party_vulkan-deps_vulkan-validation-layers_src
- chromium-mirror_third_party_vulkan_memory_allocator
- chromium-mirror_third_party_wayland-protocols_gtk
- chromium-mirror_third_party_wayland-protocols_kde
- chromium-mirror_third_party_wayland-protocols_src
- chromium-mirror_third_party_wayland_src
- chromium-mirror_third_party_webdriver_pylib
- chromium-mirror_third_party_webgl_src
- chromium-mirror_third_party_webgpu-cts_src
- chromium-mirror_third_party_webrtc
- chromium-mirror_third_party_weston_src
- chromium-mirror_third_party_wuffs_src
- chromium-mirror_third_party_xdg-utils
- chromium-mirror_third_party_xnnpack_src
- chromium-mirror_tools_page_cycler_acid3
- chromium-mirror_v8
- electron
- .nvchecker.toml
- .SRCINFO
- add-some-typename-s-that-are-required-in-C-17.patch
- default_app-icon.patch
- electron-launcher.sh
- electron.desktop
- icu-74.patch
- jinja-python-3.10.patch
- libxml2-2.12.patch
- makepkg-source-roller.py
- PKGBUILD
- random-fixes-for-gcc13.patch
- REVERT-disable-autoupgrading-debug-info.patch
- std-vector-non-const.patch
- use-system-libraries-in-node.patch**

In my backup of 3 days ago, I don't have these files & folders.

**Comment by d3finit** [comment]
Occurs for me when updating from 25.9.8-5 to 25.9.8-6 via `yay -Syu`. Electron 22 was also installed as a separate package and updates normally. 

As noted above the Electron 25 package update results in the downloading of the "chromium-mirror" repo being downloaded, which contains ~80 GB of data, inconstant with previous Electron updates. 

Upon checking the chromium upstream (https://github.com/chromium/chromium.git) it appears to have the same download size to clone the repo from there.

I'll try to test a fresh install of 25.9.8-6 when I can, but I can't uninstall it from my system right now as I have applications that depend on it.

**Comment by brjsp** [comment]
Hello, i'm a maintainer from another distro (openSUSE).

<b>Please do not report any issues with distro packaging here</b>. The Electron developers have enough time on their hands already, and reporting issues with distro added code they are <b>not familiar with</b> and <b>not responsible for</b> is just wasting their time.

You should instead direct your report at whomever you've obtained the software from, which is <a href="https://wiki.archlinux.org/title/Bug_reporting_guidelines">your distro</a>, and not where you imagine the code to be originating in.

**Comment by lautarovculic** [comment]
https://www.reddit.com/r/archlinux/comments/1bawy0u/electron25_update_taking_forever/

I found the response.
