### ISSUE TITLE
[Bug]: Windows 10 32bit render process gone while <input type="file" />  in html file

### ISSUE THREAD

**Issue by pcdeng** [electron/electron#41963]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.4.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro version 22H2 32bit

### What arch are you using?

ia32

### Expected Behavior

should display <input type="file" /> normally without render process gone
![image](https://github.com/electron/electron/assets/5336505/301c56be-21ff-455d-bd4f-a7810cac0320)

### Actual Behavior

[2024-04-24 15:53:08.020] [info]  render-process-gone
[2024-04-24 15:53:08.034] [info]  { reason: 'crashed', exitCode: -1073741819 }

![image](https://github.com/electron/electron/assets/5336505/80234b0f-3184-4c5c-872b-d18524a2faf5)

### Testcase Gist URL

https://github.com/pcdeng/electron-demo-win10-32bit

### Additional Information

Same code works good in Windows 7 x64, Windows 7 32bit, Windows 10 x64, Windows 11 x64

**Comment by dsanders11** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
