### ISSUE TITLE
[Bug]: Crash when adding child view

### ISSUE THREAD

**Issue by t57ser** [electron/electron#41974]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.0

### What operating system are you using?

Windows

### Operating System Version

10.0.19042

### What arch are you using?

x64

### Expected Behavior

No crash

### Actual Behavior

Electron crashes with: 
/c/Program Files/nodejs/npm: line 64: 11105 Segmentation fault      "$NODE_EXE" "$NPM_CLI_JS" "$@"

![image](https://github.com/electron/electron/assets/10595986/07991770-ac39-4722-b644-38e3364fb5a6)

![image](https://github.com/electron/electron/assets/10595986/90f29f75-39d5-47b9-8821-c7410782dabf)

I am not sure what exactly causes this, but it happened when I switched the implementation from browserView to webContentsView

**Comment by VerteDinde** [comment]
Hey @t57ser, I appreciate the report and I know it might be tricky to make an isolated repro case for this one. If you happen to be able to share any code that can repro the issue, that may help us better understand what's going on - the stack traces alone unfortunately don't give us much to go on here.

If a repro is too hard to make, could you please attach a crash dump to help us get more information? That might give us just a bit more than the stack trace screenshot. You can collect them by adding the following snippet to your main process code, before app.whenReady:

```
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```
Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by t57ser** [comment]
It seems like this was an issue on my side.
The app had the following code:
```
const parentWindow = electron.BrowserWindow.fromBrowserView(view)
parentWindow.removeBrowserView(child);
```
in order to get the parent and detach the view. I later changed this to
```
const parentWindow = electron.BrowserWindow.fromWebContents(view.webContents)
parentWindow.contentView.removeChildView(child);
```
This is wrong though as it does not get the parent.
After fixing these occurrances, the crash disappeared. It probably still should not crash if such a mistake is made but I do not see this as a critical issue.

**Comment by t57ser** [comment]
I think I know how to reproduce it:
```
window1.contentView.addChildView(view);
window2.contentView.addChildView(view);
```
Attach the same view to 2 different windows and it crashes

**Comment by codebytere** [comment]
@t57ser thanks! agree it should never crash - will investigate soon :)

**Comment by codebytere** [comment]
@t57ser couldn't repro with the following:

<details><summary>sample</summary>
<p>

```js
const { app, BrowserWindow, WebContentsView } = require('electron')

function createWindow () {
  const win1 = new BrowserWindow({ title: 'win1' })
  const win2 = new BrowserWindow({ title: 'win2' })

  const view1 = new WebContentsView()
  win1.contentView.addChildView(view1)

  setTimeout(() => {
   win2.contentView.addChildView(view1)
  }, 5000)

  view1.webContents.loadURL('https://electronjs.org')
  view1.setBounds({ x: 0, y: 0, width: 400, height: 400 })
}

app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

</p>
</details>

what happens instead is the webcontentsview is detached from win1 and attached to win2.

**Comment by t57ser** [comment]
@codebytere This seems to crash for me each time:
```
const {app, BrowserWindow, ipcMain} = require('electron')
const electron =  require('electron')
const path = require('path')

let mainWindow

function createWindow () {

	const mainWindow1 = new BrowserWindow({
		x: 0,
		y: 0,
		width: 1000,
		height: 600,
		show: true,
	})

	mainWindow = new BrowserWindow({
		x: 0,
		y: 0,
		width: 1000,
		height: 600,
		show: true,
	})

	mainWindow.loadFile("index.html")

	const view = new electron.WebContentsView({
		x:0,
		y: 0,
		width: 600,
		height: 600,
		show: true,
	})

	view.setBounds({
		x:0,
		y: 0,
		width: 600,
		height: 600,
	})

	mainWindow.contentView.addChildView(view);
	mainWindow.contentView.addChildView(view);
	mainWindow.contentView.addChildView(view);
	mainWindow.contentView.addChildView(view);
	mainWindow1.contentView.addChildView(view);
	mainWindow1.contentView.addChildView(view);
	mainWindow1.contentView.addChildView(view);
	mainWindow.contentView.addChildView(view);

}

app.on('ready', createWindow)
app.on('window-all-closed', function () {
	if (process.platform !== 'darwin') {
		app.quit()
	}
})
app.on('activate', function () {
	if (mainWindow === null) {
		createWindow()
	}
})
```

**Comment by codebytere** [comment]
@t57ser got it - looks like https://source.chromium.org/chromium/chromium/src/+/main:ui/views/view.cc;l=3094;bpv=1;bpt=1?q=AddChildViewAt
 is the root here
