### ISSUE TITLE
[Bug]: Crash when maximizing window if handling protocol

### ISSUE THREAD

**Issue by JoelEinbinder** [electron/electron#41970]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.1

### What operating system are you using?

Other Linux

### Operating System Version

Linux joel-asahi 6.1.0-asahi-2-2-edge-ARCH #2 SMP PREEMPT_DYNAMIC Fri, 16 Dec 2022 05:04:23 +0000 aarch64 GNU/Linux

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The window should not crash when maximizing.

### Actual Behavior

electron exited with signal SIGSEGV

### Testcase Gist URL

https://gist.github.com/JoelEinbinder/5bcc5adac5c832d7d0b2dc473cc4085c

### Additional Information

I am on Arch Linux ARM, but I had a user report this issue on Ubuntu 22.04 x64 as well.

**Comment by JoelEinbinder** [comment]
Bisecting today: https://github.com/electron/electron/compare/v29.3.1...v30.0.0-alpha.1

**Comment by clavin** [comment]
Thanks for the crash report!

This looks like the same crash as #41839 to me, especially if it ends up that the crash address is null and the crashing function is `views::View::UpdateChildLayerBounds`. I'm going to close this as a duplicate to keep things tidy, but feel free to reopen if you find out there's a difference. Thanks for the report! 👍
