### ISSUE TITLE
[Feature Request]: Hardware accelerated off-screen rendering

### ISSUE THREAD

**Issue by reitowo** [electron/electron#41972]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

OnPaint has always been sharing the OSR pictures using FrameSinkVideoCapturer, but via CPU. This is not optimal performance, and a GPU based OSR would be in favor instead of the current one.

CEF has OnAcceleratedPaint, but was dead since M103, however this PR reintroduced the capability since M125 (possibly backport to M124): https://bitbucket.org/chromiumembedded/cef/pull-requests/734

I think electron fundamentally use same arch as CEF does, and I think we can also port this to electron.

A PR will follow shortly.

### Proposed Solution

https://bitbucket.org/chromiumembedded/cef/pull-requests/734

### Alternatives Considered

No

**Comment by reitowo** [comment]
PR: https://github.com/electron/electron/pull/42001

**Comment by Galkon** [comment]
This would be much welcomed in our stack, big thanks for taking this on. Hope to use it in the near future.

**Comment by Sash0check** [comment]
I'm looking forward to this!)
