### ISSUE TITLE
[Bug]: Clicking on the color picker doesn't do anything

### ISSUE THREAD

**Issue by Falling10fruit** [electron/electron#41981]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 22H2

### What arch are you using?

x64

### Expected Behavior

I expected something like a circle thing to appear with a grid inside with all the pixels under the cursor.
![image](https://github.com/electron/electron/assets/85048907/a478b981-908b-4890-80de-938aae6422eb)

### Actual Behavior

Clicking the water dropper doesn't do anything, I can see the dropper getting darker when mouse down but that's it.
![image](https://github.com/electron/electron/assets/85048907/c79a0516-54e6-48a3-97e6-ed16791867bf)

### Additional Information

I need this to debug glsl

**Comment by Falling10fruit** [comment]
[Shouldn't the code have no effect on the dev tools?](https://gist.github.com/Falling10fruit/4583f82cfd5b8be5da30a23f12736ed0)

**Comment by mlaurencin** [comment]
@Falling10fruit Reproduction steps and a gist can help ensure that everyone is testing in the same way. Are you only experiencing this with dev tools or are you also experiencing it with the color input, like in [this gist](https://gist.github.com/mlaurencin/cb0f0b2d6b075e67721c41474c0f17da). 

I can confirm Chrome canary is not having this issue in dev tools

**Comment by Falling10fruit** [comment]
Only dev tools, the color input works.

I guess I can make a stray color input appear and substitute the dev tools.

**Comment by ashgrover** [comment]
bump

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/43685
