### ISSUE TITLE
[Bug]: Capturing the screen is broken in the newer version (desktopCapturer)

### ISSUE THREAD

**Issue by YouDJapp** [electron/electron#41988]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.1

### What operating system are you using?

macOS

### Operating System Version

MacOS Sonoma 14.1.1

### What arch are you using?

x64

### Last Known Working Electron version

25.2.0

### Expected Behavior

Capturing the screen of the app (desktopCapturer.getSources / mediaDevices.getUserMedia) and recording it (MediaRecorder) works well, like in v25.2.0, here is a working video : https://youtu.be/0fmZNy6Jo84.

var video_settings = { mandatory: { chromeMediaSource: 'desktop'}};
video_settings.mandatory.chromeMediaSourceId = video_sourceid; // ID from the desktopCapturer electron API

navigator.mediaDevices.getUserMedia({audio: false, video: video_settings}).then(function(stream) {
      recorder_chunks = [];
      var recorder = new MediaRecorder(stream, { mimeType: 'video/webm; codecs=vp9', audioBitsPerSecond : 192e3, videoBitsPerSecond : 8e6});
      recorder.ondataavailable = function(e) {  recorder_chunks.push(e.data); };
      recorder.start(100);
});

### Actual Behavior

Updating my app to v30, the screen capture is frozen at the first frame, but only the mouse is moving. Same code... Here is a video of the recording showing the issue : https://youtu.be/hHx2q9JqMNM.

**Comment by YouDJapp** [comment]
nevermind, I was sending the wrong source ID

**Comment by VerteDinde** [comment]
Glad it works! Thanks for letting us know!
