### ISSUE TITLE
[Bug]: Calling session.defaultSession.webRequest.onHeadersReceived after ready and before window creation causes silent crash

### ISSUE THREAD

**Issue by RobertWHurst** [electron/electron#42000]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.1

### What operating system are you using?

Ubuntu

### Operating System Version

PopOS 22.04 (based on Ubuntu)

### What arch are you using?

x64

### Last Known Working Electron version

29.3.1

### Expected Behavior

Once electron's ready event has fired I can setup an onHeadersReceived handler for the default session, prior to creating a window.

### Actual Behavior

If a onHeadersReceived is registered after the ready event, but before a window is created, then some time later the window is maximized electron will silently crash; the process will simply exit without any log message.

### Testcase Gist URL

https://gist.github.com/RobertWHurst/db17ceefd432ab272c4689991263594e

### Additional Information

Possibly related to #41839

Note that creating a window before using onHeadersReceived prevents the crash. To see what I mean, load the electron fiddle linked above, and move createWindow() above the call to onHeadersReceived.

**Comment by VerteDinde** [comment]
Hey @RobertWHurst, does this issue persist for you in Electron 30.0.6 or later?
