### ISSUE TITLE
webContents.getPrintersAsync() not returning printer list on Linux Mint Cinnamon 19.1

### ISSUE THREAD

**Issue by RohitSaroj** [electron/electron#42002]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.8.8

### What operating system are you using?

Other Linux

### Operating System Version

Linux Mint Cinnamon 19.1

### What arch are you using?

x64

### Last Known Working Electron version

13.2.2

### Expected Behavior

webContents.getPrinters() or webContents.getPrintersAsync() should return the list of printers present in the OS. For electron version 13.2.2 on which my old app was based, I was getting the list of printers.

### Actual Behavior

webContents.getPrintersAsync() is not returning the list of printers for Linux Mint only. For Ubuntu and Windows, it's working fine.

### Testcase Gist URL

https://gist.github.com/RohitSaroj/ca0341da6abe965d752bf3fafac7c494

### Additional Information

Is anyone aware of this issue since the electron versions involved here are old? I cannot go beyond 24.8.8 as all the versions above that have an ongoing print issue.

**Comment by RohitSaroj** [comment]
Test case gist: https://gist.github.com/RohitSaroj/ca0341da6abe965d752bf3fafac7c494

**Comment by codebytere** [comment]
Unfortunately there's not much we can do here - this function is directly plumbed to [`EnumeratePrinters`](https://source.chromium.org/chromium/chromium/src/+/main:printing/backend/print_backend.h;l=332;bpv=1;bpt=1?q=EnumeratePrinters&sq=package:chromium&type=cs) in Chromium. You should open an issue at https://issues.chromium.org/issues, and when they fix it we'll inherit that fix.
