### ISSUE TITLE
[Bug]: showMessageBox ignores abort signal if BrowserWindow is not provided on MacOS

### ISSUE THREAD

**Issue by CliftonH** [electron/electron#42036]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.2

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The [documentation](https://www.electronjs.org/docs/latest/api/dialog#dialogshowmessageboxbrowserwindow-options) for `showMessageBox` indicates that the first argument, a `BrowserWindow` instance to attach to, is optional. I would expect the behavior of the dialog to be consistent given the same options whether or not a parent window is specified. Specifically, the dialog should respect a provided abort signal and dismiss in both scenarios. 

### Actual Behavior

If a parent window is not specified, the dialog will ignore an abort signal and its behavior becomes identical to that of `showMessageBoxSync` on MacOS.

### Testcase Gist URL

https://gist.github.com/CliftonH/60160decd9eac483ec946a8ecbba4bdc

### Additional Information

As far as I can tell, this works as expected on Windows 11 (tested in-app but I haven't tested this fiddle yet)

**Comment by codebytere** [comment]
@CliftonH this is noted in documentation:

https://github.com/electron/electron/blob/1cf194faae12592c1963040a7fd94085bae1852e/docs/api/dialog.md#L279-L281

and is, while unfortunate, expected.

**Comment by CliftonH** [comment]
Apologies for missing that part in the docs, thanks for pointing that out!
