### ISSUE TITLE
[Bug]: WebContentsView preload.js events fullscreenchange not work

### ISSUE THREAD

**Issue by 82318179** [electron/electron#42039]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.1

### What operating system are you using?

Windows

### Operating System Version

win11

### What arch are you using?

x64

### Last Known Working Electron version

16

### Expected Behavior

If this website is directly accessed in BrowserWindow, then this in preload can retrieve events after the user clicks the video full screen button.
However, after using WebContentsView and its own preload, when accessing a video URL and clicking the video full screen play button, preload cannot obtain the fullscreenangle event. How can this problem be resolved?

main.js

```
const { app, BaseWindow,WebContentsView,ipcMain  } = require('electron')
const path = require('node:path')

function createWindow () {
  const mainWindow = new BaseWindow({
    width: 800,
    height: 600,
  })
const view1 = new WebContentsView(
  {
    preload: path.join(__dirname, 'preload.js')
  }
)
mainWindow.contentView.addChildView(view1)
view1.webContents.loadURL('https://www.jnnews.tv/kuaixun/p/2024-05/05/1050076.html')
view1.setBounds({ x: 0, y: 0, width: 800, height: 600 })
view1.webContents.openDevTools()
}

app.whenReady().then(() => {
  createWindow()
  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

preload.js
```
window.addEventListener('DOMContentLoaded', () => {
  document.addEventListener('fullscreenchange', () => {
    if (document.fullscreenElement) {
      console.log('Entered fullscreen mode');
    } else {
      console.log('Exited fullscreen mode');
    }
  });
})
```

### Actual Behavior

If this website is directly accessed in BrowserWindow, then this in preload can retrieve events after the user clicks the video full screen button.
However, after using WebContentsView and its own preload, when accessing a video URL and clicking the video full screen play button, preload cannot obtain the fullscreenangle event. How can this problem be resolved?

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
