### ISSUE TITLE
[Bug]:  fs.createWriteStream had a bug and has been fixed on v18.20.0, v20.12.0, and v21.7.1. I wonder if we can accelerate the releases on Electrons that depend on newer Node.

### ISSUE THREAD

**Issue by tanin47** [electron/electron#42041]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.x.x

### What operating system are you using?

macOS

### Operating System Version

N/A

### What arch are you using?

x64

### Expected Behavior

fs.createWriteStream in NodeJS has a bug. It has been fixed in recent Node versions. 

Please see: https://github.com/nodejs/node/issues/51993

### Actual Behavior

fs.createWriteStream shouldn't write out of order.

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/42046
