### ISSUE TITLE
[Bug]: 'suspend' and 'resume' events not emitted by powerMonitor

### ISSUE THREAD

**Issue by dorsta** [electron/electron#42050]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.9.8

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.4

### What arch are you using?

x64

### Expected Behavior

On suspending or resuming system powerMonitor emits 'suspend' or 'resume' event accordingly.

### Actual Behavior

No event emitted.

### Additional Information

Similar issue as https://github.com/electron/electron/issues/7699

**Comment by dorsta** [comment]
This was my bad. I was expecting screen locking to behave the same as suspending, but they are separate things. It would be cool if powerMonitor could handle screen-lock on Linux though.

Closing this issue.

**Comment by dorsta** [comment]
After further investigation it became clear that powerMonitor is indeed not emitting 'suspend' or 'resume' events, but only when the environment is set to 'production'. When the environment is set to 'development' powerMonitor is emitting those events as expected.

Reopening this issue. Please help.

**Comment by ckerr** [comment]
@dorsta does this issue persist in Electron 30?

**Comment by dorsta** [comment]
@ckerr Thanks for the reply. Unfortunately, I get the same result with Electron 30.0.3 - 'suspend' and 'resume' emitted in development, not production.

**Comment by alanp-sporelab** [comment]
I'm using Electron 31.1.0, and seeing the same behaviour on Linux (Ubuntu 24.04)

**Comment by wonkyungup** [comment]
I am using 25.2.0 and am experiencing the same issue.
