### ISSUE TITLE
[Bug]: BrowserWindow.fromWebContents does not work with WebContentsView WebContents

### ISSUE THREAD

**Issue by neobyteUK** [electron/electron#42060]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2 19045.2491

### What arch are you using?

x64

### Expected Behavior

Calling BrowserWindow.fromWebContents(web) where web is the WebContents of a BrowserView that belongs to a BrowserWindow currently returns the associated BrowserWindow.

As such, I would expect calling BrowserWindow.fromWebContents(web) where web is the WebContents of a WebContentsView that belongs to a BrowserWindow to return the associated BrowserWindow.

### Actual Behavior

Calling BrowserWindow.fromWebContents(web) where web is the WebContents of a WebContentsView that belongs to a BrowserWindow does not return the associated BrowserWindow.

### Testcase Gist URL

https://gist.github.com/neobyteUK/ea714d9f6493fb2dbcc1870b27eaaf2d

### Additional Information

Code is so small to replicate, have also included screenshot.

![image](https://github.com/electron/electron/assets/6770417/bbdaca06-2364-4a5d-a6b9-1f36138b0022)

**Comment by VerteDinde** [comment]
Hey @neobyteUK, I actually think this is expected behavior - we can consider changing this as a feature in the future, but as of right now, I don't think we expect that the BrowserWindow value is returned here

**Comment by codebytere** [comment]
Closing in agreement with above - when a WebContents belongs to a WebContentsView, it may or may not be attached to a BrowserWindow. Event when the WebContentsView is attached, its webContents are not strictly owned by the BrowserWindow.
