### ISSUE TITLE
[Bug]: WebContentsView has no ability to set which view is "on top" when overlapping

### ISSUE THREAD

**Issue by neobyteUK** [electron/electron#42061]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

When two BrowserViews within a single BrowserWindow overlap, the one that is "on top" is interactable with. Which one is on top can be set via:

`window.setTopBrowserView(view);`

I would expect there to be a similar API for WebContentsView.

### Actual Behavior

There is no API for WebContentsView.

### Additional Information

This can be worked around via removing and immediately re-adding a WebContentsView, which appears to set it to the "top".

```
window.contentView.removeChildView(view);
window.contentView.addChildView(view);
```

But this feels like a regression versus what we had before.

**Comment by neobyteUK** [comment]
Looks like this will be resolved when #42085 is merged.

**Comment by mckravchyk** [comment]
I think there should be a direct method to do it, like `setTopChildView`.  The intent of calling `addChildView` on existing view to push it on top is not clear and requires either adding a comment to explain it or creating a wrapper function.

**Comment by imp-oh** [comment]
I also agree that we need a setTopChildView
