### ISSUE TITLE
[Bug]: There is an issue with the title bar button 

### ISSUE THREAD

**Issue by ChenTraveler** [electron/electron#42080]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 家庭中文版

### What arch are you using?

x64

### Last Known Working Electron version

20.0.0

### Expected Behavior

The button triggers the move in and move out effect normally, and the corresponding display effect is displayed normally

### Actual Behavior

The main process code is as follows:
```
new BrowserWindow({
    width: 1440,
    height: 810,
    show: false,
    autoHideMenuBar: true,
    ...(process.platform === 'linux' ? { icon } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false,
    },
    titleBarStyle: 'hidden',
    titleBarOverlay: {
      color: 'rgba(0,0,0,0)',
      symbolColor: 'white',
      height: 40
    },
    webviewTag: true
  })
```
default
![image](https://github.com/electron/electron/assets/114156886/893b264f-172d-4a80-9e46-4eba964a60fc)
hover
![image](https://github.com/electron/electron/assets/114156886/2ab537c8-72af-4aac-819c-a39fdaa9a525)
Maximize
![image](https://github.com/electron/electron/assets/114156886/5e9bcd5d-45ac-4ffb-b1eb-ed1525da75fd)

The display effect did not meet expectations, and the suspension effect did not disappear after removal, resulting in full white after multiple attempts

### Testcase Gist URL

https://github.com/ChenTraveler/electron-issue-demo

### Additional Information

I reproduced this problem with a demo and placed it in my GitHub project

**Comment by codebytere** [comment]
Electron 20 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 daysi f there is no response.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
