### ISSUE TITLE
[Upgrade Followup]: heap allocation crashes in v8/node tests

### ISSUE THREAD

**Issue by VerteDinde** [electron/electron#42125]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

In a recent Chromium roll (https://github.com/electron/electron/pull/41868), v8 made several upstream changes to how line endings are handled in heap snapshots. These changes caused 8-9 consistent crashes in our downstream Linux Node tests. 

V8 tracking bug: https://issues.chromium.org/issues/42204564

### Proposed Solution

To keep the roll moving a patch was applied, but this isn't a permanent solution: https://github.com/electron/electron/pull/41868/commits/8ecca61086fec1c1b6fe2097f157e979c43d7e08 We should address the root issue of the heap allocation crashes - they may also be fixed in future upstream changes, but those changes need be applied and the patch removed.

### Additional Information

Chrome Roll: https://github.com/electron/electron/pull/41868
V8 tracking bug: https://issues.chromium.org/issues/42204564

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/42413/ via ingestion of https://chromium-review.googlesource.com/c/v8/v8/+/5531355
