### ISSUE TITLE
[Bug]: multi-window conflict with one of the window fullscreened

### ISSUE THREAD

**Issue by tianjunnew** [electron/electron#42133]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.6.10

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

one BrowserWindow should not be affected by the other BrowserWindow's fullscreen state.

### Actual Behavior

Scene 1.
1. create win1 that is not fullscreened;
2. create win2 with 
    a. alwaysOnTop
    b. visibleOnAllWorkspaces/visibleOnFullScreen
    c. enableLargerThanScreen
    d. setBounds with the fullscreen size
3. fullscreen win1

The third step will cause win2 change position

Scene 2.
swap step 2 and 3 in Scene 1, and it will checkout a new empty workspace

**Comment by codebytere** [comment]
Electron 26 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
