### ISSUE TITLE
after switching to WebContentsView the app crashes

### ISSUE THREAD

**Issue by IroniumStudios** [electron/electron#42131]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.3

### What operating system are you using?

Windows

### Operating System Version

windows 11 23h2

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

Automate the Crashpad client to run seamlessly, preventing log errors and eliminating the risk of my app crashing unexpectedly.

### Actual Behavior

During app navigation, sudden crashes occur with an error message indicating:
[17528:0512/115530.396:ERROR:crashpad_client_win.cc(868)] not connected
this issue could not be re created in electron fiddle

**Comment by codebytere** [comment]
Could you please attach a crash dump to help us get more information? You can collect them by adding the following snippet to your main process code, before app.whenReady:
```
const { app, crashReporter } = require('electron')
console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```
Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by IroniumStudios** [comment]
I can indeed add a crash dump, give me one moment

**Comment by IroniumStudios** [comment]
here is my provided crashpad files to help
[Crashpad.zip](https://github.com/electron/electron/files/15298599/Crashpad.zip)

**Comment by ikapta** [comment]
I encountered the same issue, but I found that using `removeChildView()` before `addChildView()` can solve the current problem and avoid crashing.
```ts
  let current: WebContentsView | null = null;
  if (current) {
    contentView.removeChildView(current);
  }
  contentView.addChildView(newView);
```

**Comment by codebytere** [comment]
Fixed in https://github.com/electron/electron/commit/3bd807b03e7c0f4c5dd14ee0ac88f56585ab4ba7
