### ISSUE TITLE
[Bug]: Asynchronous onBeforeRequest handler crashes Chromium with unretained dangling ptr error for specific websites

### ISSUE THREAD

**Issue by mgalla10** [electron/electron#42149]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 23H2

### What arch are you using?

x64

### Last Known Working Electron version

v29.3.3

### Expected Behavior

Providing an asynchronous handler to a window's `webContents.session.webRequest.onBeforeRequest` method should not result in a crash, regardless of the website being navigated to.

### Actual Behavior

If there is any asynchrony in the onBeforeRequest handler (even just a setTimeout(0) delay), attempting to navigate to or within the website "https://yahoo.com" results in Chromium crashing with the fatal error "Detected dangling raw_ptr in unretained with id=0x########". Try-catch blocks are not sufficient to keep this error from tearing down the entire application.

So far, this issue seems to be specific to https://yahoo.com, but I'm not convinced there aren't other sites out there that would also manifest the same issue.

### Testcase Gist URL

https://gist.github.com/0baeefc537a83dc044f4880d9eaeb5c4

### Additional Information

Using the test Gist, once Yahoo has loaded, click the main "yahoo!" button to renavigate to that page again. Within anywhere from 1 to 5 clicks, the entire app will crash and the console will display information about the dangling raw_prt error.

**Comment by clavin** [comment]
Thanks for the report! I was able to reproduce this on a Windows device, but not on my macOS device. I was able to reproduce this on Electron 30.0.3 as well as Electron 31.0.0-beta.5.

**Comment by clavin** [comment]
After more testing, I believe this crash occurs on websites that use the [Service Worker Navigation Preload feature](https://web.dev/blog/navigation-preload) in such a way that the network request for the navigation preload gets cancelled as soon as possible. I couldn't find any other websites that have this exact setup, nor have the time right now to create a demo, but this should hopefully narrow down the problem space a lot & give clear guidance on what to make an isolated, reproducible test case for.

**Comment by mgalla10** [comment]
Any updates on a potential fix or workaround for this? This is starting to impact our ability to develop and test our Electron application since we're seeing this error for more websites, there doesn't seem to be any way to handle or prevent this error, and hitting this error immediately causes our application to close.

**Comment by amitparida** [comment]
Same issue: https://github.com/electron/electron/issues/42505

Please fix it at the earliest.
