### ISSUE TITLE
[Bug]: Electron setContentBounds / setContentSize doesn't work

### ISSUE THREAD

**Issue by brondibur** [electron/electron#42178]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.4

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

`setContentBounds` / `setContentSize` resize the contents relative to the window.

### Actual Behavior

`setContentBounds` / `setContentSize` actually behave like `setBounds` and set the bounds of the entire window instead of the contents within it.

### Testcase Gist URL

https://gist.github.com/brondibur/f063baec603e95a206a3e69afafd32a1

### Additional Information

In the Fiddle Gist, `setContentBounds({ x: 10, y: 10, width: 400, height: 300 })` should set the contents as 400x300 originating from (10, 10) within the 800x600 window, whereas it converts the BrowserWindow to 400x300 that originates from (10, 10) of the screen.
Same goes for `setContentSize`

**Comment by brondibur** [comment]
Hi @codebytere 

Bug reports for this issue have been incorrectly closed multiple times (https://github.com/electron/electron/issues/41665, https://github.com/electron/electron/issues/33969, https://github.com/electron/electron/issues/23758). 

Can you please take a look?

**Comment by codebytere** [comment]
This unfortunately has never worked as you expect - we should probably reclassify this as a feature request or otherwise decide what to do with those functions.

**Comment by codebytere** [comment]
@brondibur following up on this - it was never intended to work that way. It resizes the window bounds according to then content area, but it never resized content without affecting window bounds at all. You can use `webContentsView` to do what you want.
