### ISSUE TITLE
[OS X] Hide dock icon?

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#422]
I'm creating a tray app and on OS X I would like to hide it from the dock and only show it in the menubar (tray).

With node-webkit I could set `"show_in_taskbar": false,` in package.json to hide it from the dock.

I've seen the `BrowserWindow` `skip-taskbar` option, but I couldn't get it to work, and I don't want to have to create a `BrowserWindow` for being able to hide the dock icon.

**Comment by IdanAdar** [comment]
Isn't something mising? Lets say you've use app.dock.setBadge("2"); and now the count want down to "0". How do you remove the badge completely?

**Comment by davidmarkclements** [comment]
isn't it `app.dock.setBadge('')` ?

**Comment by aaronfrost** [comment]
@davidmarkclements didn't work for me. I need to know how to remove it as well.

**Comment by aaronfrost** [comment]
app.dock.setBadge('') worked for me to remove the badge

**Comment by IdanAdar** [comment]
Yep. This issue can be closed now.

**Comment by fritx** [comment]
I call `app.dock.hide()` in main.js, but it always causes a short flip in the dock.
Is it able to be suppressed?

**Comment by kevingelion** [comment]
@fritx did you ever find a solution to this? I only want a menubar app without an icon and want the user to have no possible sighting of a twitch in the dock :/

**Comment by Shugabuga** [comment]
Not that I know of. :(

**Comment by matthewjumpsoffbuildings** [comment]
Is there any news on this? The quick flash of the dock icon is annoying, would be nice to be able to kill it

**Comment by Shugabuga** [comment]
@matthewjumpsoffbuildings Nope. Haven't heard anything.

**Comment by MarshallOfSound** [comment]
Check out the LSUIElement info.plist setting if you never want the dock icon to appear.

https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-108256

**Comment by Shugabuga** [comment]
@matthewjumpsoffbuildings @kevingelion I think this could be the solution. You want to try?

**Comment by vitorgalvao** [comment]
@MarshallOfSound’s solution works for me. After building the app, I simply `/usr/libexec/PlistBuddy -c 'add LSUIElement string 1' {{path_to_app}}/Contents/Info.plist`.

**Comment by develar** [comment]
If you use electron-builder / electron-packager, you can can customise Info.plist, e.g. seehttps://github.com/electron-userland/electron-builder/issues/1456#issuecomment-293518692

**Comment by derwaldgeist** [comment]
Is there a way to hide the icon from the dock, but keep open windows in the task switcher?
