### ISSUE TITLE
[Feature Request]: Any plans to build a new version for 28-x-y which has already not been released for about a month?

### ISSUE THREAD

**Issue by appdevopts** [electron/electron#42204]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The last version of 28-x-y is v28.3.1, which was built a month ago!

### Proposed Solution

Are there any official builds for 28-x-y before it reaches EOL(June-11)?

### Alternatives Considered

Any plans?

**Comment by codebytere** [comment]
28, as the oldest supported line, at this point receives security fixes only:

> The oldest supported release line will receive only security fixes directly.

We will cut a release when the need arises but as of now there are no plans to do so from a security perspective.
