### ISSUE TITLE
[Bug]: setBrowserView broken in v30 on macOS, works on Windows

### ISSUE THREAD

**Issue by Stanzilla** [electron/electron#42202]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.6

### What operating system are you using?

macOS

### Operating System Version

14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

29

### Expected Behavior

Same functionality as in v29

### Actual Behavior

When this line of code if present, the app will only show a blank window:

`mainWindow.setBrowserView(ads);`

ads is defined as follows:

```ts
ads = new BrowserView({
    webPreferences: {
      partition: 'persist:adpartition',
    },
  });
```

On Windows everything works as before in v29.

**Comment by Stanzilla** [comment]
> Hello @Stanzilla. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the [ blocked/need-repro](https://github.com/electron/electron/issues?q=is%3Aopen+label%3Ablocked%2Fneed-repro+sort%3Aupdated-desc) Needs a test case to reproduce the bug label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

Here is the Fiddle https://gist.github.com/Stanzilla/be0c9e14572178e6b3a9b2237a486074

**Comment by codebytere** [comment]
Looks like it's related to https://github.com/electron/electron/pull/41256 being in 30 and not https://github.com/electron/electron/pull/41326

**Comment by Stanzilla** [comment]
> Looks like it's related to #41256 being in 30 and not #41326

Does that mean it should be fixed in 31?

**Comment by Stanzilla** [comment]
This was fixed in some 30.1. versions but is broken again on 31.0.2

**Comment by Stanzilla** [comment]
Also broken in [v31.2.0](https://github.com/electron/electron/releases/tag/v31.2.0)

**Comment by Stanzilla** [comment]
New fiddle with v32 beta, it loads now but the child windows overlay the main content. https://gist.github.com/Stanzilla/96f4628602cf57ce9ceefa79e34f33f6

Try to click the button
