### ISSUE TITLE
I upgraded electron from 17.4.4 to 30.0.5 and it cannot run normally after building and installing it.[Bug]: 

### ISSUE THREAD

**Issue by whxcode** [electron/electron#42205]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.5

### What operating system are you using?

macOS

### Operating System Version

macOS 13.1 22C65 arm64

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

17.4.4

### Expected Behavior

After installation, I expect it to run normally, but when opening it, a crash message will pop up. There is no such problem during development and debugging.

### Actual Behavior

MacOS ./Mockplus\ DT

#
# Fatal process out of memory: Failed to reserve virtual memory for CodeRange
#
----- Native stack trace -----

 1: 0x112743f54 node::OnFatalError(char const*, char const*) [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x10ff377ec _$LT$object..xcoff..Symbol64$u20$as$u20$object..read..xcoff..symbol..Symbol$GT$::n_value::he0fe3918a79f4509 [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x10cba165c _$LT$font_types..tag..Tag$u20$as$u20$core..cmp..PartialEq$LT$$u5b$u8$u3b$$u20$4$u5d$$GT$$GT$::eq::h1cf26754fa042eb7 [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x10cba15a0 _$LT$font_types..tag..Tag$u20$as$u20$core..cmp..PartialEq$LT$$u5b$u8$u3b$$u20$4$u5d$$GT$$GT$::eq::h1cf26754fa042eb7 [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x10ccf8048 v8::Unlocker::~Unlocker() [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x10ff3be3c _$LT$object..xcoff..Symbol64$u20$as$u20$object..read..xcoff..symbol..Symbol$GT$::n_value::he0fe3918a79f4509 [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x10ccf7f3c v8::Unlocker::~Unlocker() [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x10cd6c5f0 v8::CppHeap::wrapper_descriptor() const [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x10ccd03f0 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x10ccd0f58 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x10d16e05c v8::internal::TickSample::print() const [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x10cbc5614 v8::Isolate::Initialize(v8::Isolate*, v8::Isolate::CreateParams const&) [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x1100d831c _$LT$object..xcoff..Symbol64$u20$as$u20$object..read..xcoff..symbol..Symbol$GT$::n_value::he0fe3918a79f4509 [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x10baa6da0 v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>) [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x10ba8dbf4 v8::BackingStore::MaxByteLength() const [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
16: 0x10de4d9c8 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
17: 0x10de5131c v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
18: 0x10de4d29c v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
19: 0x10bcca648 v8::CodeEvent::GetScriptLine() [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
20: 0x10bccb6a8 v8::CodeEvent::GetScriptLine() [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
21: 0x10bccb520 v8::CodeEvent::GetScriptLine() [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
22: 0x10bcc9e60 v8::CodeEvent::GetScriptLine() [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
23: 0x10bcca024 v8::CodeEvent::GetScriptLine() [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
24: 0x10b9a451c ElectronMain [/Applications/Mockplus DT.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
25: 0x18c51be50 start [/usr/lib/dyld]
[1]    74076 trace trap  ./Mockplus\ DT

### Additional Information

electron-builder: 24.13.3
Node.js v20.13.1

electron-buidler configuration.
![image](https://github.com/electron/electron/assets/44012914/ff061502-866b-488c-8cc3-838d04b64b41)

Build log

  dt-desktop git:(update) ✗ sudo npm run build-zh-mac

> mockplus-dt-desktop@1.0.16 build-zh-mac
> tsc && cross-env CROSS_LANG=zh-ch  CROSS_IS_TEST=false productName='Mockplus' electron-builder --mac -p always  --config config/ele-build.js

  • electron-builder  version=24.13.3 os=22.2.0

  • loaded configuration  file=/Users/mac/webProject/dt-desktop/config/ele-build.js
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=arm64 electron=30.0.5 appOutDir=dist/mac-arm64
  • signing         file=dist/mac-arm64/Mockplus platform=darwin type=distribution identity=7905348DFF8D4460037B2176826B4869786A1670 provisioningProfile=none
  • skipped macOS notarization  reason=`notarize` options were unable to be generated
  • building        target=macOS zip arch=arm64 file=dist/Mockplus_DT_macOS_arm64_v1.0.16.zip
  • building        target=DMG arch=arm64 file=dist/Mockplus_DT_macOS_arm64_v1.0.16.dmg
  • Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+
  • building block map  blockMapFile=dist/Mockplus_DT_macOS_arm64_v1.0.16.dmg.blockmap
  • building block map  blockMapFile=dist/Mockplus_DT_macOS_arm64_v1.0.16.zip.blockmap

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by BlackHole1** [comment]
@whxcode Please check if your `Helper(Plugin).app` has the "com.apple.security.cs.allow-jit" permission. You can refer to the vscode configuration: https://github.com/microsoft/vscode/blob/498fd4e37e6b6368ebe9891a67a900682d9b68ed/build/azure-pipelines/darwin/helper-plugin-entitlements.plist#L5

**Comment by aaort** [comment]
I'm currently having the similar issue I believe.

Versions
`electron@33.2.0`
`electron-builder@25.1.8`

I've created the most basic hello world application without any additional logic with only development packages being `electron` and `electron-builder`.

Here my actions step by step.

1. Generate "MAS" build  for `arm64` (Apple Silicon) with proper `identity` set to `null` so I later sign it with `@electorn/osx-sign`.
2. Sign application using `signAsync` utility from `@electron/osx-sign`  to sign the application with `Apple Distribution` certificate and include all the required entitlement for sandboxed build as per Apple's policy (All apps distributed through Mac App Store or Testflight must include `com.apple.security.app-sandbox` entitlement). I also include provisioning profile at the root of the project for `@electron/osx-sign` to embed it into the app.
3. After successful sign process I'm generating a `PKG` installer since that's the format the Apple's `Transporter.app` accepts for uploading to App Store Connect.
4. Sign `PKG` installer with `3rd Party Mac Developer Installer` or more modern name `Mac Installer Distribution`.
5.  The output of all of this is signed `PKG` installer with that include application that is signed as well.
6.  Upload the installer to App Store Connect using `Transporter.app`, all the checks and diagnosis are passed successfully.
7.  I install the Application from Testflight and try to launch it from the terminal with `ELECTRON_ENABLE_LOGGING=true`.

Application crashes leaving me with this:

```
 1: 0x113245e88 fontations_ffi$cxxbridge1$BridgeOutlineCollection$operator$sizeof [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x11089bb90 fontations_ffi$cxxbridge1$BridgeHintingInstance$operator$sizeof [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x10d2ddda4 _$LT$font_types..tag..Tag$u20$as$u20$core..cmp..PartialEq$LT$$u5b$u8$u3b$$u20$4$u5d$$GT$$GT$::eq::h1d3c8b15283ac140 [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x10d2ddce8 _$LT$font_types..tag..Tag$u20$as$u20$core..cmp..PartialEq$LT$$u5b$u8$u3b$$u20$4$u5d$$GT$$GT$::eq::h1d3c8b15283ac140 [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x10d5f18f8 node::AsyncResource::get_trigger_async_id() const [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x11089fec8 fontations_ffi$cxxbridge1$BridgeHintingInstance$operator$sizeof [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x10d5f17c4 node::AsyncResource::get_trigger_async_id() const [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x10d4c2670 v8::CppHeap::CollectGarbageInYoungGenerationForTesting(cppgc::EmbedderStackState) [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x10d42c034 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x10d42cd34 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x10d952888 v8::internal::TickSample::print() const [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x10d305c38 v8::Isolate::Initialize(v8::Isolate*, v8::Isolate::CreateParams const&) [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x110a4db9c fontations_ffi$cxxbridge1$BridgeHintingInstance$operator$sizeof [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x10c1a72ac v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>) [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x10c18cab0 v8::BackingStore::MaxByteLength() const [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
16: 0x10e4196b0 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
17: 0x10e41c8f4 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
18: 0x10e419080 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
19: 0x10c3eb854 v8::CodeEvent::GetScriptLine() [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
20: 0x10c3ec818 v8::CodeEvent::GetScriptLine() [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
21: 0x10c3ec698 v8::CodeEvent::GetScriptLine() [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
22: 0x10c3eb0b8 v8::CodeEvent::GetScriptLine() [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
23: 0x10c3eb1a0 v8::CodeEvent::GetScriptLine() [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
24: 0x10c0a536c ElectronMain [/Applications/X.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
25: 0x193aac274 start [/usr/lib/dyld]
[1]    30242 trace trap  ELECTRON_ENABLE_LOGGING=true ./X.app/Contents/MacOS/X
```

I think it might make more sense for me to create separate issue for this because I don't think this is how it should be. I should not have those kind of issues with the most minimal application created following Electron's official documentation.

**Comment by Daniil-33** [comment]
@aaort Hello!
Did you found any way to solve issue with fontations_ffi?
I faced same problem

**Comment by aaort** [comment]
@Daniil-33 Hi.
I cannot name specific thing I did that solved the issue but apparently the issue was my `electron-builder.json`.
I started looking at open source projects that managed to release MAS versions and found [bitwarden desktop client](https://github.com/bitwarden/clients/blob/main/apps/desktop/electron-builder.json) and copied their `electron-builder.json` file with adjustments that we needed. 
This solved all the issue I was having. Hope this helps somehow. Let me know if I can provide more information to help you debug this issue.

**Comment by Daniil-33** [comment]
@aaort 
I finally fixed the issue. Most likely the reason was an electron version. Before i changed it, i connected all my custom fonts locally (instead of google fonts api) and addet it in mac.extendInfo.UIAppFonts[] in my builder config. But everything became fine after i changed electron version on "36.1.0"

Thanks for your help!)
