### ISSUE TITLE
[Bug]: {action: "deny"} from contents.setWindowOpenHandler(handler) is unusable

### ISSUE THREAD

**Issue by safris** [electron/electron#42210]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.4

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The documentation [here](https://www.electronjs.org/docs/latest/api/web-contents#contentssetwindowopenhandlerhandler) describes the behavior of the `contents.setWindowOpenHandler(handler)`.

If `{action: "allow"}` is returned, a `BrowserWindow` will be instantiated.

If `{action: "deny"}` is returned, a `BrowserWindow` will be not be instantiated. But also, the `WebContents` from whose renderer the `window.open()` function was called will show a dialog saying "Grrr! A popup blocker may be preventing the application from opening the page. If you have a popup blocker, try disabling it to open the window."

I would expect there to be a mechanism by which the "Grrr!..." dialog can be quashed (i.e. not shown).

### Actual Behavior

I have not been able to find any mention of how to quash the "Grrr!..." dialog. If the dialog cannot be quashed, then `{action: "deny"}` cannot ever be returned from `contents.setWindowOpenHandler(handler)` for a `window.open()` call from a renderer without displaying the "Grrr!..." dialog, thus making `{action: "deny"}` unusable.

**Comment by codebytere** [comment]
> "Grrr! A popup blocker may be preventing the application from opening the page. If you have a popup blocker, try disabling it to open the window."

I've never seen this and it's not part of Chromium's own codebase - is this part of the app you're working on? It's not reproducible for me either. The window simply doesn't open, as I'd expect.

**Comment by safris** [comment]
@codebytere, you're absolutely right. This bug was indeed outside of Electron. I apologize for raising this here, and thank you for looking into it 🙏
