### ISSUE TITLE
[Bug]: Crash SIGSEGV at v8::internal::CppHeap::WriteBarrier(v8::internal::JSObject)

### ISSUE THREAD

**Issue by tn185075** [electron/electron#42224]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.6.0

### What operating system are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Expected Behavior

No crash.

### Actual Behavior

electron intermittently crashes after `window.location.assign("react/route")` which happens in a pop-up created by the main window. We see `render-process-gone` with exit code 139, and the crash dump has the reference to `v8::internal::CppHeap::WriteBarrier(v8::internal::JSObject)` with symbols generated for our own electron app.

What could be the cause of crash here? Or Is this a v8 bug to be reported?

**Comment by tn185075** [comment]
@clavin  thanks for taking time out, I will need to isolate the case from our app to provide a reproducible piece of code, which I'll try to. do you recommend upgrading to later version of electron?

**Comment by clavin** [comment]
Yes, upgrading to Electron 29 or 30 to make sure this crash is still present in recent versions and not just an old crash that may have been fixed already.
