### ISSUE TITLE
[Bug]: `alert`/`confirm` dialog from WebContentsView does not show message contents

### ISSUE THREAD

**Issue by code-small-white** [electron/electron#42225]
> **Original Title**:
> 在WebContentsView里面window.alert window.confirm 无法正常使用

### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v31.0.0-beta.3

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

可以像BrowserWindow里面正常使用

> **Machine Translation**:
> Can be used normally like in BrowserWindow

### Actual Behavior

![image](https://github.com/electron/electron/assets/28834925/a920f79f-4a54-48fd-b331-01adcd329da0)

### Testcase Gist URL

https://gist.github.com/428834acf25125a0027fc847f5a28868

**Comment by code-small-white** [comment]
@clavin 为什么把标题改成了英文

**Comment by clavin** [comment]
@code-small-white I changed the title to English to help other people find this problem and to clarify what the issue is to other maintainers 🙂

**Comment by codebytere** [comment]
@code-small-white if you use a BrowserWindow instead of a BaseWindow that'll fix it in the short term. There's a bigger fix to be made but that'll at least handle it for now!
