### ISSUE TITLE
[Bug]: Electron .pkg throwing JS error when installed through TEST FLIGHT

### ISSUE THREAD

**Issue by sanket-springct** [electron/electron#42242]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Electron Version

19.0.3

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

-

### Expected Behavior
Electron app is unable to load renderer url using mainWindow.loadURL('renderer_url').

Application is working properly with .dmg but giving JS error.
Note: I have uploaded .pkg signed using transporter and downloaded it through Test-Flight
![Electron-JS-Error](https://github.com/electron/electron/assets/117143383/940f4279-519b-4ea1-aed1-18d035256774)

### Actual Behavior

App should work .pkg same way its working in .dmg format.
any one can suggest me how can I create dev version of mas build

### Testcase Gist URL

https://gist.github.com/steve981cr/def310670dfd9ed1439bf31cc734f941#step-12-upload-the-pkg-file

### Additional Information

I am using electron with react to create my application.
I am using electron-builder to build and create .dmg with Developer ID application certificate & .pkg with Apple Distribution Certificate.
And @electron/notarize to notarize the application and installer.

**Comment by sanket-springct** [comment]
Hi Team,
I am attaching the screen recording with this thread.
Also I will try to provide you the gist test case.

Uploading ninja_issue.mov…

**Comment by sanket-springct** [comment]
Hi Team,
I have created gist test with all required code information.
https://gist.github.com/sanket-springct/9d48e52db79db6fdf85efe4dd8300a37

**Comment by sanket-springct** [comment]
Hello team,
Attaching screen recording for better reference.


https://github.com/electron/electron/assets/117143383/bbdea3eb-3e1c-4b5e-9911-8bec276b9dda

**Comment by sanket-springct** [comment]
Hi Folks,
Any updates for this issue?

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

If you’re still experiencing this issue in Electron 28.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sanket-springct** [comment]
Hi @mlaurencin ,
I tried upgrading the electron version also.
Providing information for your reference:
    "electron": "^19.0.3",
    "electron-builder": "^24.13.3"

**Comment by sanket-springct** [comment]
Hi @mlaurencin ,
I tried upgrading the electron version also.
Providing information for your reference:
"electron": "^19.0.3",
"electron-builder": "^24.13.3"

**Comment by mlaurencin** [comment]
@sanket-springct Given the currently provide information it is not clear whether the source of this issue is Electron itself. Triaging code with third-party dependencies is usually not feasible for a small team like Electron's. So in order to proceed, it needs to be shown how neither the third-party dependencies nor an incorrect object access resulting in null are instead responsible for this issue. 

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

**Comment by sanket-springct** [comment]
Hi @mlaurencin ,
 I will update the issue with more relevant information.

**Comment by sanket-springct** [comment]
Hi @mlaurencin ,
Can you please elaborate what information exactly should I provide to you for resolution.

**Comment by mlaurencin** [comment]
@sanket-springct With what you have currently provided, it is possible that one of your dependencies is causing the issue, as opposed to Electron itself. For example, electron-builder and/or TestFlight could be causing the problem. In order to illustrate that Electron is the source of the problem, you need to provide a test case with the fewest dependencies possible to recreate this issue. This should also help to show whether or not your code is accessing webContents appropriately.

**Comment by mlaurencin** [comment]
It is possible this is related to #42564

**Comment by sanket-springct** [comment]
Thank you for the information @mlaurencin , Let me check for the possibilities.

**Comment by sanket-springct** [comment]
> It is possible this is related to #42564

This is not relatable. I am facing issue while testing the application on test flight.

**Comment by mlaurencin** [comment]
@sanket-springct Unfortunately given the third-party dependency needed to recreate this issue, it is unlikely that the team will be able to triage it. I am going to go ahead and close this issue, but you may have better luck looking to the community and asking how people interface with test flight. Links to resources can be found at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
