### ISSUE TITLE
[Bug]: Electron not sending cookies with request

### ISSUE THREAD

**Issue by TylerWanta** [electron/electron#42247]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows 11 10.0.22631

### What arch are you using?

x64

### Expected Behavior

Cookies that are set or that are received via the `set-cookie` header are sent on subsequent requests.

### Actual Behavior

Cookies should be sent with requests. I've tried a simple example like so: 
```
// main/index.js

const cookie: Electron.CookiesSetDetails =
{
  url: 'https://vaultic-api.vaulticserver.vaultic.co',
  name: 'VaulticCookie',
  value: 'cookie',
  sameSite: 'no_restriction'
};

session.defaultSession.cookies.set(cookie).then(async () =>
{
  await session.defaultSession.cookies.flushStore();
  fetch('https://vaultic-api.vaulticserver.vaultic.co/Session/ValidateEmail', {
	  method: 'POST',
	  credentials: 'include',
	  headers: {
		  'Content-Type': 'application/json',
	  },
	  body: JSON.stringify({
		  test: 'test'
	  })
  });
});
```

but no cookie is available in the request on the server. 

I've also tried with axios after confirming that a cookie was sent back from the server:
```
// axios config
const url = 'https://vaultic-api.vaulticserver.vaultic.co/';
const axiosInstance = axios.create({
	baseURL: url,
	timeout: 120000,
	withCredentials: true
});

// the previous request successfully returned a cookie, try sending another request to see if the cookie is sent back
axiosInstance.post(serverPath, requestData[1])
```

I've tested with postman and everything works fine. Its just in electron that things aren't working.

**Comment by TylerWanta** [comment]
standalone testcase https://gist.github.com/TylerWanta/de52f7adc44fec38bea91bc82d123abe

**Comment by clavin** [comment]
My apologies, after trying your test case and looking at the code, I believe that this might be a misunderstanding about how `Session` works. `Session` is a part of Chromium's networking stack, whereas the global `fetch` in the main process is part of Node.js' networking stack.

I'm going to close this issue as its more of a question/discussion. Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For any future questions, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
