### ISSUE TITLE
[Bug]: Windows 7 BrowserWindow setting transparent background is invalid

### ISSUE THREAD

**Issue by kangtongshun** [electron/electron#42245]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.27

### What operating system are you using?

Windows

### Operating System Version

windows 7

### What arch are you using?

x64

### Last Known Working Electron version

no

### Expected Behavior

Can achieve transparency

### Actual Behavior

In Windows 7, it is opaque and the background is black, which is normal on Windows 10 and Windows 11

### Additional Information

``` javascript
const parentWin = new BrowserWindow({
      width: 800,
      height: 800,
    });
const childWindow = new BrowserWindow({
      width: 100,
      height: 100,
      backgroundColor: "#00000000", 
      transparent: true,
      parent: parentWin,
      frame: false,
      resizable: false,
    });
```

I have tried to turn off hardware acceleration and ` --enable-transparent-visuals` but it still doesn't work

**Comment by clavin** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so I'm going to close this issue. Additionally, Windows 7 is [no longer supported](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice) by Electron.
