### ISSUE TITLE
[Bug]: `showItemInFolder` opens up to parent directory when file at path does exist for Electron snap

### ISSUE THREAD

**Issue by richardMSFT** [electron/electron#42251]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.3.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

`showItemInFolder` should open to the folder and select the item in the provided path when the file exists.

### Actual Behavior

`showItemInFolder` opens up to the parent directory even when the file exists. For example for the path:

```
shell.openItemInFolder("/home/username/Downloads/test.txt");
```

the file explorer opens up to the "Downloads" directory.

### Additional Information

The behavior seems to not consistently happen all the time. Of the 3 Ubuntu VMs this has been tested on, the behavior reproduces 2/3 of them. These VMs are all running Ubuntu 22.04 and running our app installed via snap.

**Comment by craxal** [comment]
There's an issue already open for this: #33804. Unfortunately, it hasn't been looked at.
