### ISSUE TITLE
[Bug]: backgroundThrottling does not work for BrowserView on MacOS

### ISSUE THREAD

**Issue by yevheniishulha** [electron/electron#42261]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.2.0

### What operating system are you using?

macOS

### Operating System Version

all macOS versions

### What arch are you using?

x64

### Expected Behavior

There is no white screen after switch between tabs, when backgroundTrotling param is set to false in the BrowserView component

### Actual Behavior

There is a browser based application that allows to make additional actions with some sites in the backgrond. For the sites rendering is used BrowserView component. Here is set of params
webPreferences: {
        preload: `${app.getAppPath()}/build/view-preload.bundle.js`,
        nodeIntegrationInWorker: true,
        contextIsolation: false,
        webSecurity: false,
        plugins: true,
        javascript: true,
        partition: this.storageId,
        backgroundThrottling: false
      },

On the macOs it works like this:
1. Open couple of site tabs.
2. The first render is OK
3. Try to switch between tabs
4. There is a white screen when you get back to previosly opened tab

**Comment by yevheniishulha** [comment]
Is it OK if I attach the video?

**Comment by mlaurencin** [comment]
@yevheniishulha in order to proceed with triaging this issue, maintainers will need a standalone testcase. Specifically one without third-party dependencies, as it is usually not feasible for a small team like Electron's to triage those due to time constraints. You may attach a video along with said testcase.
