### ISSUE TITLE
[Bug]: contentWindow.document.fonts.ready in an iframe never resolves in a window that was hidden by window.hide()

### ISSUE THREAD

**Issue by acemtp** [electron/electron#42284]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30

### What operating system are you using?

macOS

### Operating System Version

macOs 14.5 (23F79)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

If we create a BrowserWindow with 'show:false' and then create an iframe in the html and wait for fonts.ready, it works.

But if we win.show() then win.hide(), the fonts.ready never resolve for an unknown reason.

We've done a small Testcase Gist URL so you can easily reproduce, just check the devtool console and see that the last 'after' is never displayed.

In the testcase Girst URL `iframe.contentWindow.document.fonts.ready` should resolve and we should see in the console output of the window:

```
start TEST1: test on the new hidden window
before
after
start TEST2: test on showed window
before
after
start TEST3: test on hidden window
before
after
```

### Actual Behavior

In the testcase Girst URL `iframe.contentWindow.document.fonts.ready` should resolve

```
start TEST1: test on the new hidden window
before
after
start TEST2: test on showed window
before
after
start TEST3: test on hidden window
before
```

it stall because the await of the fonts.ready never resolve for an unknown reason

### Testcase Gist URL

https://gist.github.com/acemtp/1746e237f3c906727e5f63f82dfd90eb

**Comment by codebytere** [comment]
Tracked to https://github.com/electron/electron/compare/v30.0.0-alpha.4...v30.0.0-alpha.5 - probably https://github.com/electron/electron/commit/058c6b4af7253dbd19739adc3043de75397a3493

**Comment by codebytere** [comment]
I'm not sure yet what the best solution is moving forward but I've asked upstream if this is an intentional breaking change or if they'd be interested in allowing this functionality to be preserved: https://issues.chromium.org/issues/324572951#comment19. Depending on what they say, I'll proceed here with an upstream CL and temporary fix.

**Comment by acemtp** [comment]
Thank you for tracking down the problem.

The strange thing is that the first time, the window is hidden (just after the creation) and the async resolve, but after 
a show and a hide, it doesn't resolve... even if in the both cases, the window was hidden.

I hope they'll see that as a bug.

**Comment by codebytere** [comment]
Opened a CL at https://chromium-review.googlesource.com/c/chromium/src/+/5584820 - let's see.
