### ISSUE TITLE
[Feature Request]: Allow rounded corners on WebContentsView

### ISSUE THREAD

**Issue by spikecodes** [electron/electron#42288]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The [WebContentsView](https://www.electronjs.org/docs/latest/api/web-contents-view) in Electron currently only supports rectangular corners. Allowing customizable rounded corners would enable more flexible, modern designs for Electron apps.

### Proposed Solution

Add a new method to the WebContentsView to set the corner radius:

```js
const { BaseWindow, WebContentsView } = require('electron')
const win = new BaseWindow({ width: 800, height: 400 })

const view1 = new WebContentsView()
win.contentView.addChildView(view1)
view1.webContents.loadURL('https://electronjs.org')
view1.setBounds({ x: 0, y: 0, width: 400, height: 400 })
view1.setRoundedCorners(20); // for 20px
```

### Alternatives Considered

Add an option to WebContentsView constructor to set corner radius:

```js
const view1 = new WebContentsView({ roundedCorners: 20 }); // for 20px
```

**Comment by samuelmaddock** [comment]
Tagging a similar issue request, for the now deprecated BrowserView https://github.com/electron/electron/issues/33426

**Comment by liuyike98** [comment]
@jkleinsc any version can preview this feature?

**Comment by samuelmaddock** [comment]
@liuyike98 this'll be available in electron v33. you can access it via [electron-nightly](https://www.npmjs.com/package/electron-nightly) for an early preview.

**Comment by liuyike98** [comment]
@samuelmaddock webContentsView overflow the parent view which has border radius. ![Image](https://github.com/user-attachments/assets/855de604-bccf-495f-b383-2d568d2307dd)
```
app.whenReady().then(() => {
  const win = new BaseWindow();
  win.contentView.setBorderRadius(20);
  win.contentView.setBackgroundColor("red")

  const view1 = new WebContentsView();
  view1.setBackgroundColor("green");
  view1.setBounds({ x: 0, y: 0, height: 100, width: 100 });
  view1.webContents.loadFile("./index.html");
  
  win.contentView.addChildView(view1);
})
```
