### ISSUE TITLE
[Bug]: `utilityProcess` does not properly report exit codes

### ISSUE THREAD

**Issue by bpasero** [electron/electron#42283]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.1

### What operating system are you using?

macOS

### Operating System Version

macOS 14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When a utility process crashes, its exit code should indicate as such.

### Actual Behavior

The utility process exits with code `0` when crashing. Then a `child-process-gone` event follows with `child-process-gone {"type":"Utility","reason":"crashed","exitCode":11,"serviceName":"node.mojom.NodeService","name":"Node Utility Process"}`

### Testcase Gist URL

https://gist.github.com/73c1dd4ee8b4bfd79aa25d6aaf507725

//cc @deepak1556

**Comment by codebytere** [comment]
Looks like this is a race condition - `UtilityProcessWrapper::OnServiceProcessDisconnected` gets called before `App::BrowserChildProcessCrashed` sometimes. When this happens we see the incorrect exit code 0, whereas when `App::BrowserChildProcessCrashed` is called first it flows to `UtilityProcessWrapper::Shutdown` and we see the expected code 11.

**Comment by bpasero** [comment]
I also saw it when sending kill signal to the process.

**Comment by codebytere** [comment]
I think i might have a solution - poking around now!

**Comment by deepak1556** [comment]
@codebytere that is correct and this is an expected flow in upstream (i-e) the process can perform cleanup after the message pipe disconnection, I initially joined these two unrelated observers to get better exit code when process crashes but seems like that is more often ending up in a race condition. The alternative is to rely on the observers here https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/service_process_host.h;l=137-149 but it needs patching to get exit codes when the process crashes which I think now is better to pay to avoid the above race condition.
