### ISSUE TITLE
[Bug]: `utilityProcess` reports crash when `process.exit(0)`

### ISSUE THREAD

**Issue by bpasero** [electron/electron#42290]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.1

### What operating system are you using?

macOS

### Operating System Version

macOS 14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Calling `process.exit(0)` from within utility process should not report as crash.

### Actual Behavior

An exit code of `11` is reported as well as a `child-process-gone` event.

### Testcase Gist URL

https://gist.github.com/0c0f59203b66894681d0e19ffef322c0

### Additional Information

Similar to

**Comment by codebytere** [comment]
Looks like a similar race, although i'm struggling to reproduce this one (it exits with 0 for me consistently)
