### ISSUE TITLE
[Bug]: Multi select folder option is broken on Linux with portal backend

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#42303]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.0

### What operating system are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Last Known Working Electron version

29.3.1

### Expected Behavior

`dialog.showOpenDialog` with `multiselections` and `openDirectory` enabled should allow choosing multiple folders.

### Actual Behavior

Only single folder is allowed to be selected.

### Additional Information

Regression from file dialog refactor https://github.com/electron/electron/pull/42144/commits/cb588a123516e2274a8c553e209406dcc0295ebc

~~[gtk_file_chooser_set_select_multiple](https://source.chromium.org/chromium/chromium/src/+/main:ui/gtk/select_file_dialog_linux_gtk.cc;l=475;) is not configured for folder open dialogs when multiselection is required by Electron~~.

/cc @codebytere

**Comment by deepak1556** [comment]
Turns out in my case we were using the [portal implementation](https://source.chromium.org/chromium/chromium/src/+/main:ui/shell_dialogs/select_file_dialog_linux_portal.cc;l=562-568) which does have the patch to support the file dialog options

**Comment by GaragusoPD** [comment]
This issue is still happening, in Ubuntu 2024.04 with Electron 34.0.0.
