### ISSUE TITLE
[Bug]: BrowserWindow.webContents is not defined when "closed" event dispatched on macOS, while it is defined on Windows

### ISSUE THREAD

**Issue by Raykid** [electron/electron#42317]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.2

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.6.7

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Let BrowserWindow.webContents be the same when "closed" event dispatched between Windows and macOS and any other OS.

### Actual Behavior

BrowserWindow.webContents is not defined when "closed" event dispatched on macOS, while it is defined on Windows.

**Comment by codebytere** [comment]
Electron 22 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
