### ISSUE TITLE
[Feature Request]: Improve safeStorage documentation to highlight capabilities and limitations

### ISSUE THREAD

**Issue by datosh** [electron/electron#42318]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The [documentation for safeStorage](https://www.electronjs.org/docs/latest/api/safe-storage) is lacking in regards to the security properties of the functionality provided. This makes it hard for developers to make informed decisions about the security trade-offs they are making. It currently reads:

"Allows access to simple encryption and decryption of strings for storage on the local machine. This module protects data stored on disk from being accessed **by other applications** or users with full disk access."

With my current understanding of the implementation, the highlighted part is not true, but please correct me if I'm wrong here! On both Linux & MacOS the keychain/-ring is used, which is accessible, once unlocked, by any application runner for the current user. I am a bit fuzzy on the details on Windows/DPAPI.

### Proposed Solution

I propose that the documentation should be extended to help developers answer the following questions:

What are the security properties of safeStorage? Does it protect my secret from other processes? OS users? 
What are the threats I need to mitigate as an application developer?
Mention the silent fallback to basically unencrypted secrets on Linux systems when "basic_text" is used **explicitly**.

### Alternatives Considered

I don't have any other ideas to solve the described limitation, but I'd be happy to discuss other avenues!

### Additional Information

Let me know if you agree with this feedback and see the value. I am super happy to also provide a first draft to update the documentation accordingly.

**Comment by codebytere** [comment]
cc @deepak1556

**Comment by datosh** [comment]
Any feedback on this @codebytere @deepak1556 ?

We have released a [blog post](https://control-plane.io/posts/abusing-vscode-from-malicious-extensions-to-stolen-credentials-part-2/) that details a specific attack on Electrons SafeStorage API, as most Electron apps do not have the same sandboxing capabilities that Chrome tabs enjoy. 

I think Electron documentation should display a big disclaimer here that security assumptions that are valid for Chrome tabs, extensions, ... are not the same for Electron based apps and developers should careful think about using SafeStorage or use a different API.

**Comment by MarshallOfSound** [comment]
Hey @datosh, while we always appreciate issues being raised I would like to flag that this is not the right way to report even theoretical security concerns. We have a [Security Policy](https://github.com/electron/electron/blob/main/SECURITY.md) with a reporting process and raising issues and then publishing blog posts is not the right way to operate. I see you reported issues to Microsoft but not to us.

> as most Electron apps do not have the same sandboxing capabilities that Chrome tabs enjoy.

This is inaccurate, your trick for VSCode does not apply to 99.99% of other Electron apps as they don't have built in features that allow you to run code using their app identity. And this discussion is irrelevant to either OS level or Chromium-flavored sandboxing.

> What are the security properties of safeStorage? Does it protect my secret from other processes? OS users?

This is a fair question, and one that our current documentation does a poor job of answering. This is being fixed and clarified here https://github.com/electron/electron/pull/42666. The fair TLDR is that your content is protected the exact same amount as every major browsers cookie store is 🤷 

I'm going to close this out as there's a PR in flight to clarify docs which answer your original concerns.  In the future please operate in good faith and report issues to us via our documented security policy. Hopefully the new docs colour in the missing parts of the picture 👍

**Comment by datosh** [comment]
Hey @MarshallOfSound, thanks for your detailed response!

I agree that I should have been more thorough in checking each project's security policies and also followed the one from Electron. Sorry for that!

I also jumped to the conclusion that VSCode is a representative example of an Electron app. Thanks for pointing out that the project chose a different security model when it comes to sandboxing.

Thanks for taking the time to improve Electron's documentation and help developers make more informed decisions when using security relevant features. As you mentioned #42666 is already merged. Were there other factors/motivations to get this documentation extended or was this based on our feedback here?
