### ISSUE TITLE
[Bug]: Unable to build when `is_debug = true`

### ISSUE THREAD

**Issue by reitowo** [electron/electron#42337]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

latest

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2

### What arch are you using?

x64

### Expected Behavior

Build

### Actual Behavior

Using debug.gn
```
import("testing.gn")
is_debug = true
symbol_level = 2
forbid_non_component_debug_builds = false
```

Failed at final linking stage
```
FAILED: electron.exe electron.exe.pdb
..\..\third_party\llvm-build\Release+Asserts\bin\lld-link.exe "/OUT:./electron.exe" /nologo -libpath:..\..\third_party\llvm-build\Release+Asserts\lib\clang\19\lib\windows /winsysroot:../../third_party/depot_tools/win_toolchain/vs_files/3ba76c5c20 /MACHINE:X64  "/PDB:./electron.exe.pdb" "@./electron.exe.rsp"
lld-link: error: undefined symbol: public: static class v8::platform::tracing::TraceWriter * __cdecl v8::platform::tracing::TraceWriter::CreateJSONTraceWriter(class std::__Cr::basic_ostream<char, struct std::__Cr::char_traits<char>> &, class std::__Cr::basic_string<char, struct std::__Cr::char_traits<char>, class std::__Cr::allocator<char>> const &)
>>> referenced by .\..\..\third_party\electron_node\src\inspector\tracing_agent.cc:91
>>>               obj/third_party/electron_node/src/inspector/inspector/tracing_agent.obj:(public: virtual void __cdecl node::inspector::protocol::`anonymous namespace'::InspectorTraceWriter::AppendTraceEvent(class v8::platform::tracing::TraceObject *))

lld-link: error: undefined symbol: protected: virtual class ExtensionFunction::ResponseAction __cdecl extensions::ExtensionActionOpenPopupFunction::RunExtensionAction(void)
>>> referenced by obj/electron/shell/browser/extensions/api\api_registration/generated_api_registration.obj:(const extensions::ExtensionActionOpenPopupFunction::`vftable')
ninja: build stopped: subcommand failed.
ERROR Error: Command failed: ninja.bat electron
```

**Comment by reitowo** [comment]
![image](https://github.com/electron/electron/assets/29846655/bc1493d5-9beb-4283-987f-d4e789134c7d)

The implementation was removed if perfetto is enabled, so can we disable it?

**Comment by Aryansingh0103** [comment]
can I work on it?

**Comment by reitowo** [comment]
#42338

**Comment by Ritika-27** [comment]
can i work on it?

**Comment by codebytere** [comment]
Addressed in https://github.com/electron/electron/pull/42338#pullrequestreview-2093136936
