### ISSUE TITLE
[Bug]: Window with specific effect didn't appear when using 'backgroundMaterial' Option in BrowserWindow()

### ISSUE THREAD

**Issue by alexliu07** [electron/electron#42331]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.9

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 22631.3593

### What arch are you using?

x64

### Expected Behavior

After run the program, it should appear a window with specific effect.
Like these:
![image](https://github.com/electron/electron/assets/101923999/749113d9-5b4b-4a5c-83f9-0af8d811966c)
![image](https://github.com/electron/electron/assets/101923999/b623d137-776e-4f19-a1d5-22b5b00e8a46)

### Actual Behavior

It just showed up a normal window with white background
![image](https://github.com/electron/electron/assets/101923999/ae13076e-9766-4d3b-bd6b-4fa66971b88c)
And the mica effect showed only when I updated the window (eg. minimizing and resizing window, opening dev tools, enabling full screen and exiting full screen), or set 'frame' option to 'false'
![image](https://github.com/electron/electron/assets/101923999/350ae0b5-748a-4f9d-9739-216c4951aafe)
![image](https://github.com/electron/electron/assets/101923999/715473d4-ad89-4bba-a000-3a2b2ef125ba)

### Testcase Gist URL

https://gist.github.com/alexliu07/3299f97e5cacbae155568942b4f034c8

**Comment by codebytere** [comment]
cc @clavin for Mica-related issues
