### ISSUE TITLE
[Bug]: WebView zoom level persistence on location hash change

### ISSUE THREAD

**Issue by wimagguc** [electron/electron#42333]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.6

### What operating system are you using?

macOS

### Operating System Version

Version 17.5 (19618.2.12.11.6)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

We should be able to change the location hash while using the OS zoom in/out feature, and expect the zoom level to stay consistent.

### Actual Behavior

When changing the location hash the _internal_ zoom level resets. For example:

1. Zoom in a few steps (100% -> 90% -> 75% -> 50%) by pressing `cmd —`
2. Change the search parameters (e.g. by using `window.location.hash = '#/?x=1234'` in an electron window. (The _observed_ zoom level doesn't change.)
3. Zoom back once (50% -> 75%) by pressing `cmd +`

We'd expect the _observed_ zoom level to be at 75%, but the actual value is now at 110%. Once the location changes in step two, even though visibly nothing happens to the app zoom, the _internal_ zoom level resets and so pressing `cmd +` takes the app from 100% -> 110%.

### Additional Information

Related bug fix from Dec 2023: https://github.com/electron/electron/pull/40650 fixes similar navigation-related zoom issues.

Important note: the bug only happens in an exported app, but using the dev server everything works fine. May have to do with the difference in protocol between those two (compare `http://localhost:3050/renderer/index.html#/` in the dev server with the exported bundle's `file:///tmp/MyApp.app/Contents/Resources/app.asar/renderer/index.html#/'`)

**Comment by jtbandes** [comment]
Submitted a new issue with repro: https://github.com/electron/electron/issues/44526
