### ISSUE TITLE
[Feature Request]: Fix setContentBounds / setContentSize

### ISSUE THREAD

**Issue by brondibur** [electron/electron#42341]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

This is a follow up on https://github.com/electron/electron/issues/42178

Currently, `setContentBounds` / `setContentSize` actually behave like `setBounds` and set the bounds of the entire window instead of the contents within it.

### Proposed Solution

One of `setContentBounds` / `setContentSize` should be fixed, or else a new method should be created that changes content size without affecting window size.

### Alternatives Considered

Alternative is to use multiple `WebContentView`s within a `BrowserWindow` and resize them while maintaining the existing bounds of the window.

### Additional Information

I  may be wrong, but I think the functionality might already exist, and can be observed when we open DevTools in a BrowserWindow. The content is resized without affecting the window size.

**Comment by codebytere** [comment]
@brondibur this was previously addressed: https://github.com/electron/electron/issues/42178#issuecomment-2117103750

**Comment by brondibur** [comment]
Hi @codebytere 
Since the bugfix was rejected earlier, this was raised as a feature request. Since you've closed this, should I assume that this feature request will not be considered?
Or did you close this by mistake thinking this was a duplicate bugfix request?

**Comment by codebytere** [comment]
@brondibur sorry, yeah - maybe the original comment wasn't clear enough.

>  following up on this - it was never intended to work that way. It resizes the window bounds according to then content area, but it never resized content without affecting window bounds at all. You can use webContentsView to do what you want.

What i was saying was `setContentBounds` / `setContentSize` aren't intended to work as you thought they were, and are working as intended. What you should be doing is using `webContentsView` to accomplish your stated goal.

**Comment by brondibur** [comment]
@codebytere Yeah I understood that, but I was hoping this would still be implemented, which is why I said:

> or else a new method should be created that changes content size without affecting window size

But I guess this feature request won't be considered because there is no intention to resize the contents without resizing the window. Thanks anyway for being proactive.

**Comment by brondibur** [comment]
@codebytere On this note, how does opening DevTools work? It does resize the content while window size remains the same and accommodates DevTools on the right. Is this something I can do as well without adding an additional layer of `webContentsView`?
