### ISSUE TITLE
Selenium TakesScreenshot error (OS X)

### ISSUE THREAD

**Issue by NikolaiSokolov** [electron/electron#4234]
I use `org.openqa.selenium.TakesScreenshot` with groovy Geb. 
If `takesScreenshot` is invoked I have “unknown error: cannot get automation extension”.
## error.log  

`org.openqa.selenium.WebDriverException: unknown error: cannot get automation extension from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
 (Session info: content shell=)
 (Driver info: chromedriver=2.20.353124 ...` 

Could you create embedded bridge between Selenium webDriver "take Screenshot" command handler and `BrowserWindow.capturePage` internal implementation?

**Comment by zcbenz** [comment]
`org.openqa.selenium.TakesScreenshot` requires the `chrome.automation` API to be available, which is not supported by Electron yet.

**Comment by codebytere** [comment]
closing due to abandonment.
