### ISSUE TITLE
[Bug]: Setting electron cookie with ';' character fails with empty error

### ISSUE THREAD

**Issue by TylerWanta** [electron/electron#42342]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows 11 10.0.22631

### What arch are you using?

x64

### Expected Behavior

Cookie sets or a more descriptive error is thrown.

### Actual Behavior

When trying to set a cookie with a `;` character, an empty exception is thrown.

### Testcase Gist URL

https://github.com/TylerWanta/vite-csp-issue

### Additional Information

Reproduction steps:
- Clone provided repo
- CD in project
- run `npm run dev`
- Click on `Fail to set cookie` button on screen.

**Comment by codebytere** [comment]
hey @TylerWanta - thanks for surfacing this to us. It'd be great if you could get us a repo that did not involve a ton of externalities and dependencies, as that makes it much harder for us to confirm it's an Electron issue and pinpoint the root cause.
