### ISSUE TITLE
Setting a proxy for session with setProxy

### ISSUE THREAD

**Issue by MissGwen** [electron/electron#42345]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

28.2.0

### Expected Behavior

 ```
const ses = session.fromPartition('persist:github')

ses.setProxy({
   proxyRules: 'socks5://username:password@127.0.0.1:1080'
})
```

I think setting up the socks proxy in this format and adding a username and password should work, but it doesn't!

How do I change it?

### Actual Behavior

The proxy isn't working

**Comment by tanhh326** [comment]
https://github.com/ginuerzh/gost.git
