### ISSUE TITLE
[Bug]: crash in WebUSB API when using a session's partition

### ISSUE THREAD

**Issue by boutetnico** [electron/electron#42340]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.9

### What operating system are you using?

macOS

### Operating System Version

macOS 14.5

### What arch are you using?

x64

### Last Known Working Electron version

22.3.27

### Expected Behavior

No crash

### Actual Behavior

Electron crashes with `SIGSEGV`.

### Testcase Gist URL

https://github.com/boutetnico/electron-webusb-crash

### Additional Information

`npm run start`

**Comment by codebytere** [comment]
Issue specifically seems to be when using in-memory session - will look a bit more. Prepending `persist:` to make it a persistent session fixes it though.

**Comment by boutetnico** [comment]
@codebytere thank you for your work!

However the crash is still happening in latest Electron 31:

- `git clone https://github.com/boutetnico/electron-webusb-crash`
- `npm run start`

**Comment by codebytere** [comment]
@boutetnico found something i missed - PR up soon. To clarify though - this won't work on in-memory partitions and shouldn't be used there. This is also true of Chromium and incognito profiles.
