### ISSUE TITLE
[Feature Request]: Web File System API's `showOpenFilePicker()` should remember previous directory

### ISSUE THREAD

**Issue by absidue** [electron/electron#42352]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19045.4412

### What arch are you using?

x64

### Expected Behavior

The Web File System API's `showOpenFilePicker()` function has an option to specify an `id`. The browser (in this case Electron) should remember the directory that you last selected a file from and if you call the function again with the same ID, it should open the file picker to that directory.

1. Click button to open the file picker
2. Navigate to a directory that isn't the default one
3. Pick a file
4. Click the button again to open the file picker
5. You should be seeing the same directory that you picked the first file from.

### Actual Behavior

Electron always opens the file picker to the default location or the well-known directory set in the `startIn` option.

### Testcase Gist URL

https://gist.github.com/absidue/8124af98e9971c17b1455cc6c38aab3d

**Comment by codebytere** [comment]
@absidue this is not supported at the moment, and explicitly logs that to the console:

> [3396:0604/110611.311958:INFO:file_system_access_permission_context.cc(588)] NOTIMPLEMENTED GetLastPickedDirectory

 I can certain consider taking a look at adding it in the future though!

**Comment by absidue** [comment]
Oh goodness! I'm really sorry, I completely missed that log message.

Thank you for implementing the Web File System API in Electron, the stuff that is already implemented works great!

**Comment by codebytere** [comment]
@absidue gave it a go, PR up!

**Comment by absidue** [comment]
@codebytere Thank you so much for implementing it! It works great :D
