### ISSUE TITLE
[Bug]: Post electron upgrade

### ISSUE THREAD

**Issue by Sabrish-Krish** [electron/electron#42358]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.9

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.4.1

### What arch are you using?

x64

### Last Known Working Electron version

29.4.0

### Expected Behavior

The tool that we use this electron should work without any crash. 

### Actual Behavior

Post electron upgrade we were facing an issue post electron upgrade.

Error:
/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGTRAP
[91253:0529/192908.067019:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)

Because of this our application is getting crashed frequently during testing. We havent faced such errors in previous versions. We haven’t surfaced this issue with last version 29.4.0 

Post from 30.0.0 to till now there are issues of crash

Attaching the error trace as well. 

[99174:0604/141329.225627:ERROR:partition_alloc_support.cc(763)] Detected dangling raw_ptr in unretained with id=0x000001340086edfc:

Task trace:
0   Electron Framework                  0x0000000111d66b5c std::process::id::h056ebf195753a258 + 5891228
1   Electron Framework                  0x0000000111aabc5c std::process::id::h056ebf195753a258 + 3028380

Stack trace:
0   Electron Framework                  0x00000001117d4730 std::process::id::h056ebf195753a258 + 49264
1   Electron Framework                  0x00000001117c9634 std::process::id::h056ebf195753a258 + 3956
2   Electron Framework                  0x00000001117d79d4 std::process::id::h056ebf195753a258 + 62228
3   Electron Framework                  0x000000010e5501a4 v8::CpuProfileNode::GetNodeId() const + 40560
4   Electron Framework                  0x000000010e54e08c v8::CpuProfileNode::GetNodeId() const + 32088
5   Electron Framework                  0x000000010e4e816c v8::CpuProfileNode::GetDeoptInfos() const + 36068
6   Electron Framework                  0x000000010e54deec v8::CpuProfileNode::GetNodeId() const + 31672
7   Electron Framework                  0x000000010e499698 v8::ValueSerializer::Delegate::HasCustomHostObject(v8::Isolate*) + 79120
8   Electron Framework                  0x000000010e499f54 v8::ValueSerializer::Delegate::HasCustomHostObject(v8::Isolate*) + 81356
9   Electron Framework                  0x000000010e60fc9c v8::CodeEvent::GetScriptName() + 230340
10  Electron Framework                  0x000000010e61010c v8::CodeEvent::GetScriptName() + 231476
11  Electron Framework                  0x000000010e610040 v8::CodeEvent::GetScriptName() + 231272
12  Electron Framework                  0x000000010e60febc v8::CodeEvent::GetScriptName() + 230884
13  ???                                 0x0000000157e10530 0x0 + 5769332016
14  ???                                 0x00000001500ac7f4 0x0 + 5637851124
15  ???                                 0x00000001500a9d3c 0x0 + 5637840188
16  ???                                 0x00000001500ad7b4 0x0 + 5637855156
17  ???                                 0x00000001500a91d0 0x0 + 5637837264
18  ???                                 0x00000001500ad7b4 0x0 + 5637855156
19  ???                                 0x0000000157e0b6a8 0x0 + 5769311912
20  ???                                 0x0000000157e0b398 0x0 + 5769311128
21  Electron Framework                  0x000000010f7952ec v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) + 716
22  Electron Framework                  0x000000010f6973d0 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 384
23  Electron Framework                  0x00000001150f8f80 node::CallbackScope::~CallbackScope() + 1556
24  Electron Framework                  0x00000001150f93c8 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) + 264
25  Electron Framework                  0x000000010e611444 v8::CodeEvent::GetScriptName() + 236396
26  Electron Framework                  0x000000010e539f54 v8::ValueSerializer::Delegate::GetWasmModuleTransferId(v8::Isolate*, v8::Local<v8::WasmModuleObject>) + 114092
27  Electron Framework                  0x000000010e5221d4 v8::ValueSerializer::Delegate::GetWasmModuleTransferId(v8::Isolate*, v8::Local<v8::WasmModuleObject>) + 16428
28  Electron Framework                  0x000000010e522a84 v8::ValueSerializer::Delegate::GetWasmModuleTransferId(v8::Isolate*, v8::Local<v8::WasmModuleObject>) + 18652
29  Electron Framework                  0x000000010e55e150 v8::BackingStore::MaxByteLength() const + 5508
30  Electron Framework                  0x0000000111536e70 node::GetMultiIsolatePlatform(node::IsolateData*) + 7256868
31  Electron Framework                  0x000000010e55e298 v8::BackingStore::MaxByteLength() const + 5836
32  Electron Framework                  0x0000000111a8b7f0 std::process::id::h056ebf195753a258 + 2896176
33  Electron Framework                  0x0000000111a90214 std::process::id::h056ebf195753a258 + 2915156
34  Electron Framework                  0x0000000111a8d3dc std::process::id::h056ebf195753a258 + 2903324
35  Electron Framework                  0x0000000111d69898 std::process::id::h056ebf195753a258 + 5902808
36  Electron Framework                  0x0000000111d6a018 std::process::id::h056ebf195753a258 + 5904728
37  Electron Framework                  0x0000000111779120 std::sys::pal::unix::os::errno::h12fdde1c2329795a + 279504
38  Electron Framework                  0x0000000111793600 std::sys::pal::unix::os::errno::h12fdde1c2329795a + 387248
39  Electron Framework                  0x0000000111793c10 std::sys::pal::unix::os::errno::h12fdde1c2329795a + 388800
40  Electron Framework                  0x00000001117ddb38 std::process::id::h056ebf195753a258 + 87160
41  Electron Framework                  0x000000010e3e9600 Electron Framework + 2004480
42  Electron Framework                  0x00000001117dcd00 std::process::id::h056ebf195753a258 + 83520
43  CoreFoundation                      0x00000001834bdeb0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
44  CoreFoundation                      0x00000001834bde44 __CFRunLoopDoSource0 + 176
45  CoreFoundation                      0x00000001834bdbb4 __CFRunLoopDoSources0 + 244
46  CoreFoundation                      0x00000001834bc7a0 __CFRunLoopRun + 828
47  CoreFoundation                      0x00000001834bbe0c CFRunLoopRunSpecific + 608
48  HIToolbox                           0x000000018dc57000 RunCurrentEventLoopInMode + 292
49  HIToolbox                           0x000000018dc56e3c ReceiveNextEventCommon + 648
50  HIToolbox                           0x000000018dc56b94 _BlockUntilNextEventMatchingListInModeWithFilter + 76
51  AppKit                              0x0000000186d14970 _DPSNextEvent + 660
52  AppKit                              0x0000000187506dec -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 700
53  AppKit                              0x0000000186d07cb8 -[NSApplication run] + 476
54  Electron Framework                  0x00000001117de754 std::process::id::h056ebf195753a258 + 90260
55  Electron Framework                  0x00000001117dc6c4 std::process::id::h056ebf195753a258 + 81924
56  Electron Framework                  0x0000000111794278 std::sys::pal::unix::os::errno::h12fdde1c2329795a + 390440
57  Electron Framework                  0x000000011175f5a8 std::sys::pal::unix::os::errno::h12fdde1c2329795a + 174168
58  Electron Framework                  0x000000011092f4d8 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 9098908
59  Electron Framework                  0x0000000110930f58 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 9105692
60  Electron Framework                  0x000000011092ce0c v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 9088976
61  Electron Framework                  0x000000010e7aa644 v8::CodeEvent::GetScriptLine() + 378780
62  Electron Framework                  0x000000010e7ab6a4 v8::CodeEvent::GetScriptLine() + 382972
63  Electron Framework                  0x000000010e7ab51c v8::CodeEvent::GetScriptLine() + 382580
64  Electron Framework                  0x000000010e7a9e5c v8::CodeEvent::GetScriptLine() + 376756
65  Electron Framework                  0x000000010e7aa020 v8::CodeEvent::GetScriptLine() + 377208
66  Electron Framework                  0x000000010e48451c ElectronMain + 180
67  dyld                                0x00000001830560e0 start + 2360

exited with signal SIGTRAP

 [0604/141332.740055:ERROR:http_transport_mac.mm(278)] HTTP status 500

Assist us with an alternative or can give insights from where this might occurs to dive deep further.

**Comment by KarthikTarun** [comment]
@Sabrish-Krish were you able to identify the issue or fix it?
