### ISSUE TITLE
[Bug]: Release doc for v29.0.0 provides false info about feature availability

### ISSUE THREAD

**Issue by Imperat** [electron/electron#42377]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0.0

### What operating system are you using?

Any

### Operating System Version

Any

### What arch are you using?

x64

### Expected Behavior

In the release doc for [Electron 29.0.0](https://releases.electronjs.org/release/v29.0.0) there is a statement:

* Added `WebContentsView` and `BaseWindow`, replacing the now-deprecated `BrowserView` APIs. [#40759](https://github.com/electron/electron/pull/40759)

This feature was first merged [here](https://github.com/electron/electron/pull/35658) and backported to v 29.0.0 [here](https://github.com/electron/electron/pull/40759). However, later this PR was reverted [here](https://github.com/electron/electron/pull/41060) only for v 29.0.0.

I expect `WebContentsView` and `BaseWindow` APIs are available in all 29-x-y versions

### Actual Behavior

`WebContentsView` and `BaseWindow` are not available.

**Comment by Imperat** [comment]
🙌 I do not propose getting this feature back. I mostly raised this to confirm that all Electron 29-x-y releases have the old implementation of `BrowserView` API

**Comment by codebytere** [comment]
@Imperat you're correct, this should be removed from 29 notes!

**Comment by Imperat** [comment]
Thank you very much for the confirmation @codebytere 🙏

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by mlaurencin** [comment]
The reversion line is accounted for in the Other Changes section at the bottom with:
- Reverted new WebContentsView and BaseWindow APIs. https://github.com/electron/electron/pull/41060
But that is fairly far down and makes things unnecessarily confusing. I'm going to remove both this line and the line mentioned in the issue.

**Comment by mlaurencin** [comment]
Both lines have been removed now 👍
