### ISSUE TITLE
[Bug]: Old deprecated Electron app cannot use GPU sandbox, any solution or recommendation for this case ?

### ISSUE THREAD

**Issue by AkechiShiro** [electron/electron#42375]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.5.0

### What operating system are you using?

Other Linux

### Operating System Version

NixOS

### What arch are you using?

x64

### Last Known Working Electron version

11.5.0

### Expected Behavior

Should work like it used too on older platforms/GPUs and older Linux

### Actual Behavior

Does not work and crash : 
```
(node:403838) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[403838:0605/161502.803907:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
[1]    403838 trace trap (core dumped)  /nix/store/xwkmhpfclvpna6c3b2nvsn96s8vg7kzx-bloodhound-4.3.1/bin/BloodHound
```

### Additional Information

`--no-sandbox` or `--no-gpu-sandbox` or `--in-gpu-process` can sometimes fix this crash.

**Comment by VerteDinde** [comment]
Hey @AkechiShiro, this version of Electron (11.5.0) is unfortunately very old and no longer in our LTS line. We bump Electron's major version to stay in line with Chrome's major versions (see https://www.electronjs.org/docs/latest/tutorial/electron-versioning#semver); without digging too deeply, it's possible that this version of Electron was releases before full support for this was implemented. Could you try upgrading your app to Electron 29 or higher and see if you see the same results?

**Comment by AkechiShiro** [comment]
I will attempt to do so and compile BloodHound with Electron 29, if I get something that works I'll let you know but it's highly probable that it won't be compiling with success due to the fact that upstream, this software is deprecated and soon will be archived.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by AkechiShiro** [comment]
@VerteDinde it's near impossible to update to a maitnained electron version without breaking the app.

Upstream has also tried twice to do so and gave up.

Closing this issue.
