### ISSUE TITLE
[Bug]: Vibrant BrowserWindow not responding to pointer events after opening DevTools

### ISSUE THREAD

**Issue by TheCommieAxolotl** [electron/electron#42382]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.0-beta.8

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

30.0.0

### Expected Behavior

When opening DevTools, both the app contents and DevTools continue to respond to pointer events.

### Actual Behavior

In a `BrowserWindow` with vibrancy set to `"sidebar"`:

When opening DevTools for the first time, both DevTools and the app stop responding to pointer events.
Upon then closing DevTools and reopening it, DevTools becomes responsive but the app stays unresponsive.

Note: The app continues to respond to other input such as <kbd>Tab</kbd> navigation.

### Testcase Gist URL

https://gist.github.com/TheCommieAxolotl/3b91b79f80278e3e18f5d8c0e0456245

**Comment by TheCommieAxolotl** [comment]
Possibly related/duplicate of #42336

**Comment by codebytere** [comment]
@TheCommieAxolotl i'd also put my money on it being the same root cause as #42336 unfortunately - the vibrant view isn't being inserted at the right place in the Views hierarchy anymore as a result of https://github.com/electron/electron/pull/41326

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by TheCommieAxolotl** [comment]
Also reported in #43003
