### ISSUE TITLE
[Bug]: In version 30.1.0, the FormData object is not available.

### ISSUE THREAD

**Issue by mushan0x0** [electron/electron#42381]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.1.0

### What operating system are you using?

macOS

### Operating System Version

14.5 (23F79)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The FormData object can be used normally.

### Actual Behavior

<img width="702" alt="image" src="https://github.com/electron/electron/assets/29084441/2b6f20b5-1937-4beb-9d39-3e2b498bc6dd">

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by absidue** [comment]
@codebytere This issue is probably worth reopening considering that it's not just `FormData` that doesn't exist in 30.1.0, other built-ins like `Headers`, `Request` and `Response` are missing too. This problem does not exist on the previous release 30.0.9.

**Comment by codebytere** [comment]
@absidue hmm - can you explain a little more what you mean? If i create a FormData for example in the renderer:

```js
const formData = new FormData();
formData.append("username", "Groucho");
formData.append("accountnum", 123456);
console.log(formData)
```

I don't see an issue.

**Comment by absidue** [comment]
I'll do so more investigating, I know that we have `nodeIntegration` turned on (yes, I am aware it's bad, I'm slowly refactoring the project so we can turn it off at some point), so that could be related.

**Comment by codebytere** [comment]
Thanks! we bumped Node.js in that diff so i'd guess it's that and can investigate more once i have a better grasp of the issue 😄

**Comment by mushan0x0** [comment]
> @absidue hmm - can you explain a little more what you mean? If in 30.1.0 create a FormData for example in the renderer:
> 
> ```js
> const formData = new FormData();
> formData.append("username", "Groucho");
> formData.append("accountnum", 123456);
> console.log(formData instanceof FormData) // true
> ```
> 
> I don't see an issue 🤔

@codebytere Sorry I didn't make it clear, this situation occurs in a webpage loaded in a webview tag, and may not occur in the rendering process or main thread.

**Comment by absidue** [comment]
@codebytere Here's a gist that can be used in Electron Fiddle to reproduce the issue: https://gist.github.com/absidue/13878d7b295265028dd2a9e7c99960b3

The magic combination to break it seems to be setting both `nodeIntegration: true` and `contextIsolation: false` in `webPreferences`. As it only seems to be certain classes that are missing such as `Response`, `Request`, `Headers`, I wonder if there is some kind of conflict between Chromium's implementation of those classes and node's through `undici`, that results in those classes not getting loaded/created at all.

**Comment by codebytere** [comment]
@absidue Tracked it to https://github.com/nodejs/node/commit/bd2a3c10aeff38281992b8437a9f6e1830ba9d6f - i'll look at potential solutions!

**Comment by babsey** [comment]
> @codebytere This issue is probably worth reopening considering that it's not just `FormData` that doesn't exist in 30.1.0, other built-ins like `Headers`, `Request` and `Response` are missing too. This problem does not exist on the previous release 30.0.9.

I can confirm that `Headers` is not defined in v30.1.0.

**Comment by Xing1P** [comment]
Response is not defined in Worker
Electron version 31.0.1
