### ISSUE TITLE
[Bug]: Switching to single HiDPI display breaks HiDPI settings in running Electron apps

### ISSUE THREAD

**Issue by perroboc** [electron/electron#42383]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.1

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 40

### What arch are you using?

x64

### Expected Behavior

Setup: 2x HiDPI monitors (4k) on Plasma 6 Wayland, set to run at 200% Scale. Extended desktop.

When using Electron apps in this setup, they run at the configured HiDPI settings (200%) when starting, and stay that way as long as I have the same displays connected. If I disconnect a display, I expect the applications to stay at the configured scale (200%).

### Actual Behavior

Whenever I disconnect a display, Electron apps change their resolution to 100%. A workaround is to change the display scale to 100% and back to 200%, or close and restart the applications.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
