### ISSUE TITLE
[Bug]: Electron will not run if given a v8 experimental flag

### ISSUE THREAD

**Issue by tustin2121** [electron/electron#42394]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 v22H2

### What arch are you using?

x64

### Expected Behavior

When I add `--js-flags="--experimental-vm-modules"` to the command line, I expect the program to run and make the `vm.Module` API available to use.

### Actual Behavior

Electron closes with no feedback whatsoever. It prints a newline then closes with exit code 3.

```bash
tustin2121@machine MINGW53 /d/project/path
$ npx electron --js-flags="--experimental-vm-modules"


tustin2121@machine MINGW53 /d/project/path
$ echo $?
3

tustin2121@machine MINGW53 /d/project/path
$
```

### Additional Information

I can run `node --experimental-vm-modules` just fine. Apparently this flag has been in node since version 13 (which... just why?? Why is this still "experimental"??). I have v20 installed on my command line, and electron reports v22. I tried one or two other experimental feature flags I found in `node --v8-options` just because, and the same thing happened. But it's the `vm.Module` APIs I want access to.

**Comment by tustin2121** [comment]
It seems like this can be worked around for the moment by setting the [`NODE_OPTIONS` environment variable](https://nodejs.org/api/cli.html#node_optionsoptions) in lieu of trying to pass through electron.

**Comment by codebytere** [comment]
@tustin2121 js-flags are for the v8 engine: https://github.com/electron/electron/blob/3d2a7545314f68c21f3fb92fb0a6eb9edcceabd3/docs/api/command-line-switches.md#L119

--experimental-vm-modules is a Node.js specific flag and therefore not valid. However, it shouldn't crash the app, so i'll put up a fix for that!

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
