### ISSUE TITLE
[Bug]: `type="module"` support in `index.html`

### ISSUE THREAD

**Issue by rtritto** [electron/electron#42439]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.0

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Expected Behavior

Dev tools console is empty

### Actual Behavior

In `index.html`, I have a script with `type="module"`:

`index.html`
```js
<script type="module">
  import { ipcRenderer } from 'electron'
  ...
</script>
```

Current output in dev tools console:
```console
(Warning) electron.js?v=024e3aa9:24 Module "path" has been externalized for browser compatibility. Cannot access "path.join" in client code. See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

(Error) electron.js?v=024e3aa9:36 Uncaught TypeError: path.join is not a function
    at .yarn/unplugged/electron-npm-31.0.0-df97707901/node_modules/electron/index.js (electron.js?v=024e3aa9:36:25)
    at __require (chunk-Y2F7D3TJ.js?v=024e3aa9:3:50)
    at electron.js?v=024e3aa9:54:16
```

**Comment by absidue** [comment]
As mentioned in the docs https://www.electronjs.org/docs/latest/tutorial/esm ES Modules in the renderer process are handled by Chromium's ES Modules loader, so you cannot import Node.JS modules.

You should look into using a preload script instead.

**Comment by thot-experiment** [comment]
When using the `nodeIntegration: true` the following works on client
```js
const fsp = require('fs/promises')
```
but this does not
```js
import fsp from 'fs/promises'
```
This is confusing, counterintuitive, and not mentioned anywhere in the documentation. I think it should probably be considered a bug?
