### ISSUE TITLE
[Feature Request]: version support policy is too short-lived

### ISSUE THREAD

**Issue by axetroy** [electron/electron#42437]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The current version release strategy makes a version exist for a very short time before reaching its maintenance cycle.

For example, use `24.0.0`

It was released on 2023-Apr-04, and maintenance ended on 2023-Oct-10, lasting 6 months

When I found some bugs using this version, there was no way to fix them, because this version is no longer maintained, and I can only upgrade the version.

But unfortunately, due to some restrictions, it is not possible to upgrade.

I hope there will be a version similar to LTS, which can get long-term and stable support, and the life cycle should be at least longer than 6 months.

### Proposed Solution

Refer to nodejs launch LTS plan.

Its LTS versions have basically been maintained for a long time.

The following is a breakdown of the maintenance time for nodejs's LTS and the maintenance time for Electron.

### Nodejs

```json
[
  {
    "version": "24.x",
    "days": 1104
  },
  {
    "version": "22.x",
    "days": 1101
  },
  {
    "version": "20.x",
    "days": 1108
  },
  {
    "version": "18.x",
    "days": 1107
  },
  {
    "version": "16.x",
    "days": 546
  },
  {
    "version": "14.x",
    "days": 546
  },
  {
    "version": "12.x",
    "days": 587
  },
  {
    "version": "10.x",
    "days": 756
  },
  {
    "version": "8.x",
    "days": 581
  },
  {
    "version": "6.x",
    "days": 734
  },
  {
    "version": "4.x",
    "days": 571
  },
  {
    "version": "v0.12.x",
    "days": 420
  },
  {
    "version": "v0.10.x",
    "days": 934
  }
]
```

The support for recent versions is basically 3 years

# Electron

```json
[
  {
    "version": "31.0.0",
    "days": 210
  },
  {
    "version": "30.0.0",
    "days": 182
  },
  {
    "version": "29.0.0",
    "days": 182
  },
  {
    "version": "28.0.0",
    "days": 189
  },
  {
    "version": "27.0.0",
    "days": 189
  },
  {
    "version": "26.0.0",
    "days": 189
  },
  {
    "version": "25.0.0",
    "days": 189
  },
  {
    "version": "24.0.0",
    "days": 189
  },
  {
    "version": "23.0.0",
    "days": 189
  },
  {
    "version": "22.0.0",
    "days": 315
  },
  {
    "version": "21.0.0",
    "days": 189
  },
  {
    "version": "20.0.0",
    "days": 189
  },
  {
    "version": "19.0.0",
    "days": 189
  },
  {
    "version": "18.0.0",
    "days": 182
  },
  {
    "version": "17.0.0",
    "days": 182
  },
  {
    "version": "16.0.0",
    "days": 189
  },
  {
    "version": "15.0.0",
    "days": 245
  },
  {
    "version": "14.0.0",
    "days": 210
  },
  {
    "version": "13.0.0",
    "days": 252
  },
  {
    "version": "12.0.0",
    "days": 259
  },
  {
    "version": "11.0.0",
    "days": 287
  },
  {
    "version": "10.0.0",
    "days": 273
  },
  {
    "version": "9.0.0",
    "days": 287
  },
  {
    "version": "8.0.0",
    "days": 287
  },
  {
    "version": "7.0.0",
    "days": 308
  },
  {
    "version": "6.0.0",
    "days": 294
  },
  {
    "version": "5.0.0",
    "days": 287
  },
  {
    "version": "4.0.0",
    "days": 306
  },
  {
    "version": "3.0.0",
    "days": 315
  },
  {
    "version": "2.0.0",
    "days": 357
  }
]
```

### Alternatives Considered

No longer following Chromium's release schedule.

This makes Electron not well maintained, but stable enough

### Additional Information

Electron's maintenance cycle for versions is too short, so I dare not upgrade the version.

Because when I find a bug in this version, it may reached EOL, and I have to upgrade. This is an endless game

**Comment by codebytere** [comment]
> No longer following Chromium's release schedule.

While unfortunate, and while we understand your frustration, this is something we've discussed extensively and won't be changing in the definite future.
