### ISSUE TITLE
[Bug]: Background material can break the window in VM/RDP

### ISSUE THREAD

**Issue by mitchchn** [electron/electron#42446]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.02

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Expected Behavior

Setting a background material on a window should not cause any adverse affects. In a VM or machine without a real GPU, the material should fall back to being opaque as it does in other apps.

### Actual Behavior

Setting a background material in an Azure VM accessed over RDP makes the window blank and unusable.

![Screenshot 2024-06-11 at 12 22 05 PM](https://github.com/electron/electron/assets/7342119/520a33fe-3218-4f7b-9ccf-65b27b874988)

### Testcase Gist URL

https://gist.github.com/mitchchn/360cd5bfeae8d98cf9f8121893512829

### Additional Information

Disabling hardware acceleration is a workaround, but it should not be necessary as native apps with Mica fall back gracefully in this scenario.

The GPUs reported in the VM are "Microsoft Hyper-V Video" and "Microsoft Remote Display Adapter"

![Screenshot 2024-06-11 at 1 17 06 PM](https://github.com/electron/electron/assets/7342119/02004a79-ba27-4c5e-a568-7407dd220aac)

**Comment by flick9000** [comment]
Same here
