### ISSUE TITLE
[Bug]: white screen

### ISSUE THREAD

**Issue by Progaming95967** [electron/electron#42465]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

1.2.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

1

### Expected Behavior

i expect to enter my username and i will add my own custom skin

### Actual Behavior

only  white screen and file view help option show

**Comment by Progaming95967** [comment]
1.2 Last Known Working Electron version

**Comment by VerteDinde** [comment]
Hey @Progaming95967, Electron 1.2 has been end of life for some time. Could you try updating the version of Electron and seeing if that solves the issue? If the issue is happening in an app, I'd recommend filing an issue with those project maintainers. Thanks!
