### ISSUE TITLE
[Bug]: GlobalShortcut IS TOO GLOBAL !!

### ISSUE THREAD

**Issue by ajoslin103** [electron/electron#42474]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.2

### What operating system are you using?

macOS

### Operating System Version

Mac Sonoma 14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I created and started this fiddle (which captures Cntrl-Z in the main.js) and then Ctrl-Z SHOULD STILL WORK in VSCode

### Actual Behavior

I created and started this fiddle (which captures Cntrl-Z in the main.js) and then Ctrl-Z DOES NOT WORK in VSCode until I quit this fiddle

### Testcase Gist URL

https://gist.github.com/e3fde56136e2cbed867cbbc867d913e1

### Additional Information

I found the problem using Electron v19

**Comment by MarshallOfSound** [comment]
This is the design and documented behavior of global shortcuts, they are global and capture the shortcut regardless of focused application. If you want local shortcuts use menu accelerators.

**Comment by ajoslin103** [comment]
Wow, talk about a super-power !!  Thanks.

**Comment by ajoslin103** [comment]
I have to admit to some confusion

From the Menu options documentation

https://www.electronjs.org/docs/latest/api/menu-item#new-menuitemoptions

This is the page that comes up when I click on 'accelerator' in the menu docs

https://www.electronjs.org/docs/latest/api/accelerator

So I'll keep reading and looking -- when I can make it work I'll try to submit a Docs PR
