### ISSUE TITLE
[OS X] Disable tray icon highlighting

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#425]
A common use-case with menubar (tray) apps is to not show a menu on click, but instead change the icon and do an action. While this is possible, it's not possible to disable the blue highlighting

![screen shot 2014-06-23 at 18 26 26](https://cloud.githubusercontent.com/assets/170270/3360462/26db980a-faf3-11e3-94b1-f44862b42a3d.png)
## 
#### Example app:

Normal:

![screen shot 2013-07-29 at 21 27 16](https://f.cloud.github.com/assets/170270/874096/f9fa6346-f884-11e2-961a-3b9ce0f5d89c.png)

Click (no blue highlighting):

![screen shot 2013-07-29 at 21 27 21](https://f.cloud.github.com/assets/170270/874097/002ecd38-f885-11e2-8815-b2ac29e90517.png)
## 

It's just about exposing [NSStatusItem.highlightMode](https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSStatusItem_Class/Reference/Reference.html).

**Comment by softwheredon** [comment]
The SetHighlightMode method is no longer available. How can we accomplish this in the latest version of Electron?

**Comment by donkooijman** [comment]
^ This can be achieved by setting an empty context menu on the tray.

`const contextMenu = Menu.buildFromTemplate([]);`
`tray.setContextMenu(contextMenu);`
