### ISSUE TITLE
[Bug]: BrowserView is not resized correctly on BrowserWindow resize

### ISSUE THREAD

**Issue by staniel359** [electron/electron#42501]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.1

### What operating system are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Last Known Working Electron version

29.3.0

### Expected Behavior

BrowserWindow's BrowserView should resize according to its parent.

### Actual Behavior

Doesn't:
[Screencast from 14-06-24 11:23:05.webm](https://github.com/electron/electron/assets/18214933/55337636-92e8-4c51-ab04-ec55e4efd716)

**Comment by staniel359** [comment]
Found out this issue was in `BrowserView.setAutoResize()` method.

Removed it and used resizing on `BrowserWindow`'s `resize` event.

**Comment by codebytere** [comment]
@staniel359 to clarify - you think there's a bug in setAutoresize? or you realized you were incorrectly using the API?

**Comment by staniel359** [comment]
@codebytere `setAutoResize` had been working correctly until `29.3.0`.
So I removed it and used the resize logic explicitly but as a workaround.

https://gist.github.com/staniel359/ef9af020415662b8069e265976910c30
