### ISSUE TITLE
[Bug]: DevTools have overly vibrant blue background

### ISSUE THREAD

**Issue by Vendicated** [electron/electron#42516]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.1 / 32.0.0-alpha.1

### What operating system are you using?

Other Linux

### Operating System Version

6.8.11-300.fc40.x86_64 # 1 SMP PREEMPT_DYNAMIC Mon May 27 14:53:33 UTC 2024 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

29

### Expected Behavior

Devtools have expected look that matches normal chrome/chromium.
Screenshot from normal chrome (Version 126.0.6478.61 (Official Build) (64-bit))

![image](https://github.com/electron/electron/assets/45497981/6e3d2d62-8cf0-4fa9-a21e-51d6b6cdff09)

### Actual Behavior

Devtools have this really ugly blue background 
![image](https://github.com/electron/electron/assets/45497981/16829496-a6f0-4b7c-815e-8e5f5335c7e0)

### Testcase Gist URL

https://gist.github.com/markh-discord/4d828931b38d5917e5c8e73101981a54 (i just used one from some other issue)

### Additional Information

This is a [verified bug in chromium](https://issues.chromium.org/issues/330678210), that they already fixed in chromium 125, confirmed by me to be working (see "Expected Behaviour"), yet Electron still has the bug even in alpha's chromium version of 127

**Comment by MoConWu** [comment]
I also have this issue, but I don't think it's a bug, maybe it's a change in the Chrome kernel update

**Comment by TypeScriptError** [comment]
Yes its a bug https://issues.chromium.org/issues/330678210

**Comment by Vendicated** [comment]
.

**Comment by Vendicated** [comment]
Fixed in latest versions, likely via https://github.com/electron/electron/pull/44114
