### ISSUE TITLE
[Bug]: window.requestAnimationFrame(update)无法在窗口最小化时，正常使用;

### ISSUE THREAD

**Issue by 2573825854** [electron/electron#42511]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 专业版

### What arch are you using?

x64

### Expected Behavior

在electron中，使用了 window.requestAnimationFrame(update);我已经设置了backgroundThrottling: false,在最小化窗口时，程序应当正常更新

### Actual Behavior

实际上会变成1秒1帧，并且我找不到解决的办法

**Comment by Ktibit** [comment]
![transaction](https://github.com/electron/electron/assets/172862050/b4fbf9c5-7af5-4fbd-b410-6324fcaec4b8)

**Comment by 2573825854** [comment]
我在electron的中使用iframe，iframe中使用了window.requestAnimationFrame(update);我设置了backgroundThrottling: false,但在最小化时，window.requestAnimationFrame(update);还是变成了1秒1帧，我该怎么把iframe的可见性保持为visible

**Comment by mlaurencin** [comment]
@2573825854 In order to triage your issue, we need you to provide us code that we can run on our end to reproduce the issue. Can you please provide either a [GitHub gist](https://gist.github.com/) or cloned repository of https://github.com/electron/electron-quick-start with what is needed to reproduce your issue?

**Comment by qian-jiang** [comment]
I have the same problem, is there a solution?

**Comment by 2573825854** [comment]
> 我有同样的问题，有解决办法吗？

I used a stupid method.When using an iframe, I manipulate the dom object directly for the next frame refresh

**Comment by qian-jiang** [comment]
> > 我有同样的问题，有解决办法吗？
> 
> I used a stupid method.When using an iframe, I manipulate the dom object directly for the next frame refresh
I set it up in main.js, and after 300 milliseconds of executing the minimize method, the window is restored and the x-axis is moved to a negative number, which is visually invisible, so that requestAnimationFrame can maintain a high frame rate.
