### ISSUE TITLE
[Bug]: dependency not found

### ISSUE THREAD

**Issue by rtritto** [electron/electron#42525]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.1

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Expected Behavior

No error

### Actual Behavior

Console output:
```console
Ignore error:  Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'electron-squirrel-startup' imported from C:\template-electron-vite\.vite\build\main.js
    at packageResolve (node:internal/modules/esm/resolve:861:9)
    at moduleResolve (node:internal/modules/esm/resolve:934:18)
    at defaultResolve (node:internal/modules/esm/resolve:1164:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:365:17)
    at Object.resolve (node:internal/modules/esm/initialize_import_meta:30:25)
    at file:///C:/template-electron-vite/.vite/build/main.js:6:15
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadApplicationPackage (file:///C:/template-electron-vite/.yarn/unplugged/electron-npm-31.0.0-df97707901/node_modules/electron/dist/resources/default_app.asar/main.js:129:9) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Testcase Gist URL

https://github.com/rtritto/template-electron-vite

### Additional Information

Stack: Electron Forge + Vite + ESM + Plug'n'Play (PnP)

`src/main.ts` file:
  ```ts
  try {
    // Handle creating/removing shortcuts on Windows when installing/uninstalling.
    import.meta.resolve('electron-squirrel-startup/package.json')
    app.quit()
  } catch (error) {
    // Ignore
    console.log('Ignore error: ', error)
  }
  ```

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by rtritto** [comment]
@codebytere this should be a bug with bundle and ESM.

`electron-squirrel-startup` must be a _dependency_.
Same problem with other _dependencies_ such as _react_, _solid.js_.

It works if I move it from _dependencies_ to _devDependencies_.

From [doc](https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app):
> WHY IS ELECTRON A DEVDEPENDENCY?
This may seem counter-intuitive since your production code is running Electron APIs. However, packaged apps will come bundled with the Electron binary, eliminating the need to specify it as a production dependency.

**Comment by reatang** [comment]
I encountered the same file and had to use the webpack template.

```shell
npm init electron-app@latest electron-demo -- --template=webpack
```
