### ISSUE TITLE
[Bug]: desktopCapturer.getSources The method returns consistent screen thumbnails

### ISSUE THREAD

**Issue by list12318** [electron/electron#42555]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.2

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

Return thumbnails of different screens

### Actual Behavior

![QQ截图20240618163502](https://github.com/electron/electron/assets/33713614/b13e7c42-cdd0-442e-9ee7-879e35fa63f3)

thumbnail. toDataURL() After converting screen sources, multiple screen sources display the same thumbnail

**Comment by codebytere** [comment]
Electron v27 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.

**Comment by list12318** [comment]
> Electron v27 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.
> 
> 
> Electron v27不受支持，并且已经有一段时间没有了。如果要继续分类此问题，则必须在[当前支持](https://www.electronjs.org/docs/latest/tutorial/electron-timelines)的Electron版本上存在此问题。如果没有响应，此问题将在10天内关闭。

Thank you for your reply, but I am currently using V27, would like to consult the solution to this problem, is it necessary to upgrade the version?

**Comment by list12318** [comment]
> Electron v27 isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days if there is no response.
> 
> 
> Electron v27不受支持，并且已经有一段时间没有了。如果要继续分类此问题，则必须在[当前支持](https://www.electronjs.org/docs/latest/tutorial/electron-timelines)的Electron版本上存在此问题。如果没有响应，此问题将在10天内关闭。

Thank you for your reply, but I am currently using V27, would like to consult the solution to this problem, is it necessary to upgrade the version ?
