### ISSUE TITLE
[Bug]: Electron traps or segfaults on Wayland when maximizing

### ISSUE THREAD

**Issue by yretenai** [electron/electron#42560]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.1

### What operating system are you using?

Other Linux

### Operating System Version

Gentoo, Linux 6.9.5

### What arch are you using?

x64

### Last Known Working Electron version

30.1.1

### Expected Behavior

Application maximizes

### Actual Behavior

SIGTRAP crash

### Additional Information

Command: `electron --ozone-platform-hint=wayland`

SIGTRAP raised in: `electron::ElectronPermissionMessageProvider::IsPrivilegeIncrease` (electron code)

Further stack: 
- `emplace<float const&, gtk::WindowFrameProviderGtk::Asset>` (libcxx code) 
- `base::flat_map<float const&, gtk::WindowFrameProviderGtk::Asset>::operator[]` (chromium code) 
- `gtk::WindowFrameProviderGtk::GetOrCreateAsset` (chromium code)
- `gtk::WindowFrameProviderGtk::GetFrameThicknessDip` (chromium code)
- `electron::ClientFrameViewLinux::GetBorderDecorationInsets` (electron code)

This happens on every electron app, including `default_app.asar`

Electron 32.0.0.alpha.1 and later segfaults instead of sigtraps.

SIGSEGV raised in `gtk::WindowFrameProviderGtk::GetFrameThicknessDip` (`frame_provider_` is NULL)

Compositor tested: Sway 1.9

**Comment by yretenai** [comment]
https://gist.github.com/yretenai/fbfbc1eab29da3400c608619a009921f

This immediately sigtraps on my machine with Sway 1.9

```
$ npm start
> wayland-crash@1.0.0 start
> electron . --ozone-platform-hint=wayland

/opt/code/electron/wayland-crash/node_modules/electron/dist/electron exited with signal SIGTRAP
```

**Comment by yretenai** [comment]
It seems to be an issue on all tiling compositors, at least Sway and dwl. tinywl and weston do not crash.

**Comment by TheComputerGuy96** [comment]
> It seems to be an issue on all tiling compositors, at least Sway and dwl. tinywl and weston do not crash.

KWin Wayland 6.0.5 crashes for me (Mutter 46.2 works fine though)

**Comment by hovancik** [comment]
I am seeing this crash as well on Debian with KDE and Wayland. Not with fullscreen though, but with `backgroundColor` but not with all of my BrowserWindows so not sure what is the other parameter

**Comment by SunRed** [comment]
With `v31.1.0` this issue now seems fixed for me.

**Comment by hovancik** [comment]
> I am seeing this crash as well on Debian with KDE and Wayland. Not with fullscreen though, but with `backgroundColor` but not with all of my BrowserWindows so not sure what is the other parameter

I still see this on `v31.1.0`

**Comment by yretenai** [comment]
Seems that issue is resolved on 31.1.0 (at least for wlroots/sway,) indicating that the backgroundColor issue is a different crash.

**Comment by aidilzm** [comment]
Is this an issue on Electron's end or the compositor's end?

**Comment by yretenai** [comment]
The fullscreen segfault/trap does not appear to be a compositor issue as it seems to be fixed in v31.1.0 (presumably due to the chromium bump.)

32.0.0-alpha.5 still crashes when going fullscreen with a SIGSEGV signal due to a null pointer dereference in GetFrameThicknessDip (Chromium code,) which only happens in Electron (not Chromium builds.) 

No idea on the `backgroundColor` issue reported above, and probably needs to be in a separate issue as this crash only happens when going into fullscreen due to frame thickness offset handling incorrectly receiving/using null pointers.

**Comment by hovancik** [comment]
I've created separate issue for bg color

**Comment by codebytere** [comment]
Does this still happen?

**Comment by yretenai** [comment]
It does not.

**Comment by codebytere** [comment]
Closing as this appears resolved - will reopen if it recurs.
