### ISSUE TITLE
[Bug]: Electron doesn't check for webContents is null or undefined in get/set ownerWindow, and throws an exception

### ISSUE THREAD

**Issue by origin-yaropolk** [electron/electron#42564]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2 19045.4412

### What arch are you using?

x64

### Last Known Working Electron version

27.3.1

### Expected Behavior

The `BrowserWindow` should allow a new view to be installed regardless of the state of the previously installed `BrowserView`.

Also, `setBounds` should have no effect if view not exists.

### Actual Behavior

`BrowserWindow.setBounds()` and `BrowserWindow.setBrowserView()` throws similar errors.

![image](https://github.com/electron/electron/assets/25509934/94d12ad2-08b8-4286-a3c4-bd7fe18ef78b)

![image](https://github.com/electron/electron/assets/25509934/9049175a-9c7b-4b95-a472-3c7d23f65df9)

### Testcase Gist URL

https://gist.github.com/origin-yaropolk/c9342adc7eacec0da9cf78f2ad13f0af

### Additional Information

Looks like [here](https://github.com/electron/electron/blob/v31.0.1/lib/browser/api/browser-view.ts#L58) and [here](https://github.com/electron/electron/blob/v31.0.1/lib/browser/api/browser-view.ts#L62) missed checks for `webContents` is null/undefined

**Comment by origin-yaropolk** [comment]
Btw, I know that this api is deprecated, but I think new one is unusable with things like that :)
![image](https://github.com/electron/electron/assets/25509934/36256d8a-b275-47d4-a6b5-15c11acc5410)

**Comment by codebytere** [comment]
@origin-yaropolk would you have any interest in opening a PR? Happy to review if yes, otherwise i'll get to this sometime in the near future!

**Comment by origin-yaropolk** [comment]
Setting up build and test environment, as well as, a basic introducing will took some time for me, but I'll consider this possibility next issue :)
