### ISSUE TITLE
[Bug]: Crash when using Version 29.4.0

### ISSUE THREAD

**Issue by fr43nk** [electron/electron#42565]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.0

### What operating system are you using?

Other Linux

### Operating System Version

 4.18.0-553.5.1.el8_10.x86_64

### What arch are you using?

x64

### Last Known Working Electron version

28.2.8

### Expected Behavior

Coming from VSCode the software works with the basis of Electron 28.2.8. VSCode is starting up.

### Actual Behavior

Since the current version of vscode uses 29.4.0 the software crashes with the following message:

```
[0617/085433.786964:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0617/085433.789584:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[0617/085433.789605:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
```

### Additional Information

The OS is running virtualized on en VMWare server. The cpufreq directory does not exist.

**Comment by codebytere** [comment]
Please first report this to VSCode - thanks!
