### ISSUE TITLE
[Bug]: missing fetch-dependent interfaces in web workers

### ISSUE THREAD

**Issue by thomas-jakemeyn** [electron/electron#42577]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

30.0.9

### Expected Behavior

`fetch`-dependent interfaces (e.g. `Request`, `Response`) should be defined in web workers.

### Actual Behavior

`fetch`-dependent interfaces are not defined in web workers (`nodeIntegration` is enabled). This problem has been partially addressed by #42419 that patched `shell/renderer/electron_renderer_client.cc`. It looks to me like `shell/renderer/web_worker_observer.cc` should be patched in a similar manner (see [this code change](https://github.com/electron/electron/compare/v30.0.9..v30.1.1#diff-89fdcdb019f69ce0046e3ddc34709ba6a6e05bfd25b7893d15ec5ff290026d8fR6)).

**Comment by codebytere** [comment]
@thomas-jakemeyn you're right, ty for catching this. I'll have a PR up today!

**Comment by thomas-jakemeyn** [comment]
Thank you very much for the fix!
