### ISSUE TITLE
Ignore X-Frame-Options

### ISSUE THREAD

**Issue by matteodelabre** [electron/electron#426]
It would be intersting if we had a way to ignore X-Frame-Options header, restricting retrieval of pages to same origin.

This restriction leads to this kind of issues : https://github.com/gabceb/atom-web-view/issues/7. `node-webkit` has a `nwfaketop` attribute that does the trick.

**Comment by sgarbesi** [comment]
This was removed. Is there another working solution?

**Comment by frankhale** [comment]
@sgarbesi, what was removed?

**Comment by frankhale** [comment]
https://github.com/electron/electron/blob/master/docs/api/browser-window.md

> webSecurity Boolean - When setting false, it will disable the same-origin policy (Usually using testing websites by people), and set allowDisplayingInsecureContent and allowRunningInsecureContent to true if these two options are not set by user. Default is true.

**Comment by sgarbesi** [comment]
@frankhale https://github.com/electron/electron/pull/573

```html
<iframe name="google-disable-x-frame-options" src="https://google.com"></iframe>
```

**Comment by frankhale** [comment]
Does disabling web security on the browser window not help you on this? See previous post.

**Comment by frankhale** [comment]
It doesn't help that we've had no commentary by @zcbenz on this issue. Lots of people are confused by this.

**Comment by sgarbesi** [comment]
If you mean this:

```html
<iframe disablewebsecurity>
```

Then no, it doesn't work.

**Comment by sgarbesi** [comment]
@frankhale No, it doesn't work.

**Comment by frankhale** [comment]
Does the last commend with code snippet on https://github.com/electron/electron/pull/573 work in your case?

**Comment by frankhale** [comment]
I've asked about this on the official Electron slack channel to see if somebody can answer this.

https://atomio.slack.com/messages/electron/

**Comment by kirilpopov** [comment]
@frankhale  you need to lower case the header name to make it work

```
if(d.responseHeaders['x-frame-options']){
  delete d.responseHeaders['x-frame-options'];
}
```

**Comment by frankhale** [comment]
Actually this is for @sgarbesi, thanks @kirilpopov!!!

**Comment by Ursi** [comment]
For those coming after me: you can currently accomplish this with the method posted in the comments of #573.

**Comment by TheSalarKhan** [comment]
Thanks @ursi . To save time, I'll post the work around here. 
```
  // We set an intercept on incoming requests to disable x-frame-options
  // headers.
  win.webContents.session.webRequest.onHeadersReceived({ urls: [ "*://*/*" ] },
    (d, c)=>{
      if(d.responseHeaders['X-Frame-Options']){
        delete d.responseHeaders['X-Frame-Options'];
      } else if(d.responseHeaders['x-frame-options']) {
        delete d.responseHeaders['x-frame-options'];
      }

      c({cancel: false, responseHeaders: d.responseHeaders});
    }
  );
```
``win`` should be the reference to your BrowserWindow object. After that in your html you can do something like this.
```
<iframe src="https://www.youtube.com/watch?v=CnFtZZp7f-c" style="width: 100vw; height: 100vh"></iframe>
```

**Comment by wslp12** [comment]
```
  // We set an intercept on incoming requests to disable x-frame-options
  // headers.
  win.webContents.session.webRequest.onHeadersReceived({ urls: [ "*://*/*" ] },
    (d, c)=>{
      if(d.responseHeaders['X-Frame-Options']){
        delete d.responseHeaders['X-Frame-Options'];
      } else if(d.responseHeaders['x-frame-options']) {
        delete d.responseHeaders['x-frame-options'];
      }

      c({cancel: false, responseHeaders: d.responseHeaders});
    }
  );
```

not workig any more ^16.0.4

Has a new solution been proposed according to the version update?
