### ISSUE TITLE
[Bug]: crashReport not work in windows  electron@29.4.2

### ISSUE THREAD

**Issue by jackieli123723** [electron/electron#42601]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.2

### What operating system are you using?

Windows

### Operating System Version

 [cpu={"model":"11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz","length":8},arch=x64,platform=win32,chrome=122.0.6261.156,electron=29.4.2]

### What arch are you using?

x64

### Last Known Working Electron version

31.0.2

### Expected Behavior

import {
  app,
  BrowserWindow,
  crashReporter
} = require('electron');

setTimeout(() => process.crash(), 1000 * 30)

crashReporter.start({

  submitURL: 'xxxxx.com/crash',

  productName: 'xxxx',

  compress: false,

  uploadToServer: true,

  rateLimit: false,

  ignoreSystemCrashHandler: false,

});

//app启动

const createWindow = () => {
  const win = new BrowserWindow({
    width: 800,
    height: 600
  });
  win.loadFile('index.html');
}

app.whenReady().then(() => {
  createWindow()
})

在主进程入口mac中可以触发crashReporter函数，但是在windows中无法触发crashReporter函数，submitURL接口收集不到崩溃文件xxx.dmp

### Actual Behavior

import {
  app,
  BrowserWindow,
  crashReporter
} = require('electron');

setTimeout(() => process.crash(), 1000 * 30)

crashReporter.start({

  submitURL: 'xxxxx.com/crash',

  productName: 'xxxx',

  compress: false,

  uploadToServer: true,

  rateLimit: false,

  ignoreSystemCrashHandler: false,

});

//app启动

const createWindow = () => {
  const win = new BrowserWindow({
    width: 800,
    height: 600
  });
  win.loadFile('index.html');
}

app.whenReady().then(() => {
  createWindow()
})

在主进程入口mac中可以触发crashReporter函数，但是在windows中无法触发crashReporter函数，submitURL接口收集不到崩溃文件xxx.dmp

### Additional Information

electron@28.3.1是正常的可以触发崩溃收集器

**Comment by jackieli123723** [comment]
I learned through the interface capture that the failure of the crash report to work in Windows was caused by an increase in the size of the dmp file in electron@29.4.2. Why can the dmp file be so large after upgrading to 29.4.2? Is there any way to reduce its size? The DMP files should be within 10M. 
![image](https://github.com/electron/electron/assets/10346511/488fd05a-40eb-4c63-bfd8-352cde074a39)
@electron-issue-triage

**Comment by mlaurencin** [comment]
@jackieli123723 In order to triage your issue, we first need you to provide us code that we can run on our side to reproduce the issue. Can you please provide either a [GitHub gist](https://gist.github.com/) or cloned repository of https://github.com/electron/electron-quick-start with what is needed to reproduce your issue?

Now adding the https://github.com/electron/electron/labels/blocked%2Fneed-info%20%E2%9D%8C label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by jackieli123723** [comment]
@mlaurencin  yes. i update new electron@31.0.2 . in windows Crashpad dmp file size is too large  maybe 37M 。 gist code：https://gist.github.com/jackieli123723/d252f0f839c6e0230a7b3c2447031cec

**Comment by jackieli123723** [comment]
Looking forward to your reply and answer. How to reduce the file size of the crash file dmp on Windows, how to configure it, and what is the reason for the dmp file to become larger after the Electron upgrade

**Comment by mlaurencin** [comment]
@jackieli123723 You included 31.0.2 in the "Last Known Working Electron version" section of the initial post, which would mean you are not seeing these large crash dumps in 31.0.2. However, from your recent message it appears that the problem exists in 31.0.2 as well. Is this correct?

 If so, what was the version you upgraded from initially before 29.4.2? Do you also have large crash dumps if you run the same code using that version? The gist you provided does not work for me unfortunately.

**Comment by jackieli123723** [comment]
Before the upgrade, it was "electron": the dmp files produced by "28.3.1" versions of Windows and Mac are only a few megabytes. Upgrade to electron@29.4.2 and electron@31.0.2 Afterwards, the crash file dmp of Windows grew to 37M, while Mac remained normal
