### ISSUE TITLE
[Bug]: desktopCapturer.getSources The method returns consistent screen thumbnails

### ISSUE THREAD

**Issue by list12318** [electron/electron#42607]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.2

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

Return thumbnails of different screens

### Actual Behavior

![QQ截图20240621145445](https://github.com/electron/electron/assets/33713614/c238db3c-4d70-4f90-888a-11a8fed3aeac)
![1](https://github.com/electron/electron/assets/33713614/824511a8-d294-45c7-9c54-3fe1f331d36a)
![2](https://github.com/electron/electron/assets/33713614/018acbca-5ee2-4b00-a15e-6ce273be7092)

Test screenshot as shown above

After converting the screen source through thumbnail. toDataURL(), multiple screen sources display the same thumbnail, all of which are the main screen thumbnail

**Comment by chudongvip** [comment]
Version 31.2.0 still has this problem. so is this issue fixed, Which version should I use?

![image](https://github.com/user-attachments/assets/82f1a3ed-ff8d-42ac-b0fc-2ce4fb316de2)

![image](https://github.com/user-attachments/assets/f9ce57ef-8fc4-4134-867e-913b177ddb81)

**Comment by simo-an** [comment]
I also facing the same issue, waiting for the fix.

**Comment by hoomanaskari** [comment]
33.2.0 was released 6 days ago, and still the issue persists. I have also noticed that the app icons are the same screenshots as well! Are we expecting a fix any time soon?

**Comment by misakayao** [comment]
您的邮件我已收到，感谢您的来信！

**Comment by misakayao** [comment]
> I have the same issue on 33.1.0

I resolved this issue by calling thumbnail.toDataURL in the main process, transferring the string instead of NativeImage.
