### ISSUE TITLE
[Bug]: High Contrast Mode doesn't work anymore

### ISSUE THREAD

**Issue by doctolivier** [electron/electron#42609]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro

### What arch are you using?

x64

### Last Known Working Electron version

30.1.2

### Expected Behavior

When we navigate to Windows Accessibility settings, we can enable a contrast theme
![settings](https://github.com/electron/electron/assets/100758811/5d2e5fc1-b4fd-4ecb-9dc8-fff00b62f198)

This will apply a high contract mode to all applications, and also websites.
As we can see into the default fiddle code:
![electron30](https://github.com/electron/electron/assets/100758811/05d30926-cc64-4126-af0f-2cb2e31657c4)

the high contrast is applied to the BrowserWindows and also the website.

### Actual Behavior

When we activate a high contrast mode on Electron 31.x.x, the contrast is only applied to BrowserWindows, but not on the website anymore.
![electron31](https://github.com/electron/electron/assets/100758811/5b75f5bc-2ede-470c-83ad-0428d1d57d62)

**Comment by VerteDinde** [comment]
Bisected back to the first 31.0.0-alpha.1. The issue isn't present in 31.0.0-nightly.20240412, and the alpha was cut on 04/17, so the breaking change is somewhere here: https://github.com/electron/electron/compare/05fba85aa38dba54e513cca786ed8ffac1f9f6a5..cdafe09ffbfdcbbc789bd141f6c9cad7e7fa3e92 I'm suspicious of this Chrome roll: https://github.com/electron/electron/pull/41610

**Comment by doctolivier** [comment]
thank you for the fix!
