### ISSUE TITLE
[Bug]: Crash while re-parenting window to another with different scales

### ISSUE THREAD

**Issue by origin-yaropolk** [electron/electron#42619]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2 19045.4412

### What arch are you using?

x64

### Last Known Working Electron version

27.3.1

### Expected Behavior

Window re-parenting successfully

### Actual Behavior

Crash
![image](https://github.com/electron/electron/assets/25509934/a50b7a88-6213-4aae-a27f-6c83058b7eaf)

### Testcase Gist URL

https://gist.github.com/origin-yaropolk/5b24083394da63cfc59e3e18c3134d96

### Additional Information

Windows only.
To reproduce this you need two monitors with different scales - 1 and 1.25 for example.
I faced that crash in my custom menu implementation while migrating to new Electron. I don't recreate menu window due to optimization, just show/hide move and re-parent.
As workaround I can avoid re-parenting but that causes menu window appearing in windows task panel.

**Comment by origin-yaropolk** [comment]
Tried with v31.0.2 right now and it seems fixed. Issue can be closed, I think.

**Comment by VerteDinde** [comment]
Thanks for the bug report! Looks like this was fixed by https://chromium-review.googlesource.com/c/chromium/src/+/5600753, which was pulled into Electron 31 here: https://github.com/electron/electron/pull/42458 This should be fixed in Electron 31.0.2 and higher, closing this.
