### ISSUE TITLE
[Bug]:  Library methods from preload js do not work

### ISSUE THREAD

**Issue by s160684a** [electron/electron#42610]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.2

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

Operation of library methods loaded in preload js

### Actual Behavior

When using a library method loaded via preload js I get an error (it is not a function)

### Additional Information

preload js:
```
const { contextBridge } = require("electron");
const mineflayer = require("mineflayer");

contextBridge.exposeInMainWorld('libs', {
    mine: mineflayer
});
```

main.js
```
const path = require('path');
const url = require('url');
const {app, BrowserWindow, ipcMain} = require('electron');

let win;

function createWindow() {
    win = new BrowserWindow({
        resizable: false,
        width: 900,
        height: 700,
        autoHideMenuBar: true,
        webPreferences: {
            preload: path.join(__dirname, 'preload.js'),
            nodeIntegration: true,
            sandbox: false
        }
    });

    win.loadURL(url.format({
        pathname: path.join(__dirname, './html/index.html'),
        protocol: 'file:',
        slashes: true
    }));

    win.webContents.openDevTools();

    win.on('closed', () => {
        win = null;
    });
}

app.on('ready', createWindow);

app.on('window-all-closed', () => {
    app.quit();
});
```

index.js (js scripts in html)
```
const bot = libs.createBot();

bot.on("message", msg => {console.log(msg)}); // bot.on it is not a function
```

A simple js file in which everything works
```
const mineflayer = require("mineflayer")

const bot = mineflayer.createBot({
    username: "123123a",
    host: "funtime.su",
    versions: "1.16.5"
});

bot.on("message", msg => {console.log(msg)});
```

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
