### ISSUE TITLE
[Bug]: Wrong web browser opened when clicking links

### ISSUE THREAD

**Issue by bittylicious** [electron/electron#42611]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.6

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 24.04

### What arch are you using?

x64

### Expected Behavior

The _shell.openExternal_ call appears to open links in Google Chrome even if Firefox is configured as the default browser.

This happens when using the Ferdium and Slack apps, making me think it's an ElectronJS issue. No non-ElectronJS applications on by Ubuntu install have this problem.

### Actual Behavior

If Firefox is the default browser, e.g. as shown with Ubuntu's _update-alternatives --get-selections_ command, links should open in Firefox.

### Additional Information

This has been confirmed on two installations of Ubuntu 24.04, so it could be a weird configuration in 24.04 that's not being updated properly, and that only ElectronJS appears to take note of. I don't think it happened with Ubuntu 20.04.

The only workaround I've found so far is to make Chrome fail so it falls back to Firefox, e.g. by renaming _/usr/bin/google-chrome-stable_ to something else.

Unfortunately, I don't have the skills to build a Fiddle, but I am willing to test it. My initial investigation though suggested Fiddle only has a Chrome stub, this might not be testable.

**Comment by bittylicious** [comment]
Hello bot.

As said in the issue, I think the Fiddle won't be helpful here because it has some sort of Chrome stub, so I don't think it'll try and use what it thinks is the default web browser. I'm not 100% sure of this though, but based on this being a possibility, I think it can only be tested with a real app.

In reality, this should be reproducible using any normal Electron app, as long as you perform the following steps:

1. Install Ubuntu 24.04.
2. Install Firefox and make it the default browser.
3. Run any Electron app that opens external links, e.g. Slack or Ferdium, and see it open in Chrome.

**If someone could just perform the above steps to confirm this is an issue, it would be appreciated.**

I personally have done the above on two clean machines, and the issue is visible.

It of course could be an issue with Ubuntu, but I'm not sure how the underlying choice is made by Electron as to what browser to open.

**Comment by NobodysNightmare** [comment]
@bittylicious I feel your pain on this, just wanted to let you know that I face the same issue.

Not that anyone from Electron will be reading this anymore, but the bug reporting process is broken IMHO. You explained pretty clearly that you are a user/consumer of electron apps and thus unable to provide code, but you included great reproduction instructions.

However, people and bots involved were apparently not able to deal with reports from non-devs. Here's hoping that some day someone with Electron skills (I have none) will face this issue and report it.

**Comment by bittylicious** [comment]
@NobodysNightmare Thanks so much - you absolutely echo what I feel!

This is really easy to repeat and has been going on since 24.04's release. It's surprising a dev doesn't want to reproduce this themselves.

**Comment by Viicos** [comment]
@mlaurencin, here is a Fiddle repro: https://gist.github.com/Viicos/d77af018be1b7b27294a74c378731992.

I can also reproduce on Ubuntu 24.04, and I believe it wasn't the case on 22.04. I have both Firefox and Chrome installed on my machine. I can reproduce on Slack and VSCode, although Discord works as expected.

While the Linux implementation of `openExternal` seems to rely on xdg-open:

https://github.com/electron/electron/blob/2745771a22dc7aec4364fec758804e0b7f230357/shell/common/platform_util_linux.cc#L352-L361

Firefox is configured as being my default browser:

```sh
$ xdg-settings get default-web-browser
firefox_firefox.desktop
```

Note that when upon calling `shell.openExternal`, I get the following error logged:

```sh
[2066424:2066424:1220/223619.954207:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not part of the idle inhibition specification: https://specifications.freedesktop.org/idle-inhibit-spec/latest/
Created TensorFlow Lite XNNPACK delegate for CPU.
Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#-1 is a dynamic-sized tensor).
```

As a workaround, adding the following in `~/.local/share/applications/mimeapps.list`:

```cfg
[Default Applications]
x-scheme-handler/http=firefox_firefox.desktop
x-scheme-handler/https=firefox_firefox.desktop
```

resolves the issue, and I don't get the logged error anymore.

**Comment by NobodysNightmare** [comment]
FYI: I opened a new issue https://github.com/electron/electron/issues/45129 as per the bot's suggestion, assuming that no one from Electron would ever look at this closed issue anymore.

**Comment by mlaurencin** [comment]
@Viicos Thank you for that reproduction. The example functioned as expected on Windows, so that Linux implementation is most likely the cause of the problem. As this has been closed and a new issue was created above, I will go ahead and provide similar information there. Any further information or conversation related to this issue should take place there as well.

**Comment by amaranth133** [comment]
I know this issue is closed, but adding a confirmed workaround / datapoint in case it helps others.

On Ubuntu 24.04 GNOME, Electron apps (tested with Discord) opened links in Chrome even though Firefox was the default browser and xdg-mime handlers were correct.

Launching the app with:
XDG_CURRENT_DESKTOP=GNOME
causes links to open in Firefox as expected. (the originally set XDG_CURRENT_DESKTOP was set as Ubuntu:GNOME.) This suggests Electron may be mis-detecting or misusing the desktop environment, similar to the workaround used by Tutanota:
https://github.com/tutao/tutanota/commit/439260efbb451a1dfe2eef69113a6d1e45beee5c
