### ISSUE TITLE
[Bug]: dialog.showSaveDialogSync fails silently when the file name is entered manually

### ISSUE THREAD

**Issue by mpolk** [electron/electron#42621]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux Mint Cinnamon 21.0.3

### What arch are you using?

x64

### Last Known Working Electron version

29.3.3

### Expected Behavior

1) Call dialog.showSaveDialogSync(mainWindow, {defaultPath: "example.txt"}) from the main script
2) Change "example.txt" to "example1.txt" in the "file name" dialog field
3) Click "Save" button
Now the control should be returned to the calling script, and the return value should be something like "/home/path/example1.txt"

### Actual Behavior

1) Call dialog.showSaveDialogSync(mainWindow, {defaultPath: "example.txt"}) from the main script
2) Change "example.txt" to "example1.txt" in the "file name" dialog field
3) Click "Save" button
The control does not return to the calling script. Moreover something wrong apparently happens in the background (probably some thread gets blocked), since now the electron app can not stop normally even after main window is closed. But control-C still can quit the app.

### Testcase Gist URL

https://gist.github.com/2cf36a722696695b6e0107a2250c8ccc

### Additional Information

1) Async function variant (dialog.showSaveDialog) does not show this issue.
2) The issue appears in Electron version 29.4.0 and can be seen in all later version except 30.0.2-30.0.3
3) The issues appeared at the same time when another issue related to the dialog window popup-behavior was fixed. Previously the dialog window opened in the background, did not pop-up automatically and had to be brought to the top with the mouse click. But at least it worked. After the popup behavior was fixed the described issue has appeared.

I could not reproduce the issue with the Fiddle exactly. But the Fiddle's gist reproduce it rather closely. Contrary to my app, this fiddle shows the issue in any case, independently on whether the file name was changed and what button was pressed. In my app dialog fails only when the file name is changed and the "Save" button is pressed.

I suspect that the issue may be reproduced on the Linux only and probably only on the Cinnamon or similar DE.

**Comment by mpolk** [comment]
The issue also reproduces on Ubuntu 24.04 Destop (Gnome DE)

**Comment by MikesGlitch** [comment]
I'm getting this on Pop!_OS 22.04 LTS. Works on Windows. And it fails silently which has made it a bit annoying to track down.
