### ISSUE TITLE
[Bug]: impossible to ensure that IPC promises actually resolve before proceeding

### ISSUE THREAD

**Issue by ChristopherJTrent** [electron/electron#42667]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.1

### What operating system are you using?

Windows

### Operating System Version

11 Pro 10.0.22631

### What arch are you using?

x64

### Expected Behavior

I expect, that if I create a promise using this code:
```ts
function spawnGitProcess(args:string[], opts?:ExecOptions):ChildProcess {
  const proc = exec([`cd ${ASHITA_LOCATION} &&`,'git', ...args].join(' '), {
    windowsHide: true,
    ...opts
  })
  proc.on('error', (e) => {console.log(`what the fuck: ${e}`)})
  return proc
}

export type installStatus = ('uninstalled'|'up-to-date'|'behind')

export async function getAshitaStatus():Promise<installStatus> {
  return new Promise((resolve, _reject) => {
    let string = ''
    const proc = spawnGitProcess(
      ['status'])
    proc.stdout?.on('data', (data) => {
      console.log(`received chunk from git: ${data.toString()}`)
      string += data.toString()
    })
    proc.stdout?.on('end', () => {
      resolve(/up to date/.test(string) ? 'up-to-date' : 'behind')
    })
    proc.on('exit', (code) => {
      if (code !== 0) {resolve('uninstalled')}
    })
  })
}

export async function pullAshita():Promise<void> {
  return new Promise((resolve, _reject) => {
    try{
      spawnGitProcess([
        'pull',
        '--rebase'
      ], {
       // cwd: ASHITA_LOCATION
      }).on('exit', resolve)
    } catch (err) {
      console.log(err)
      _reject()
    }
    }
  )
}

export function installAshita():Promise<void> {
  return new Promise((resolve, _reject) => {
    try{

      spawnGitProcess([
        `clone https://github.com/ashitaxi/ashita-v4beta.git "${ASHITA_LOCATION}"`,
      ], {
        timeout: ASHITA_DOWNLOAD_TIMEOUT
      }).on('close', resolve)
    } catch(e) {
      console.log(e)
      _reject()
    }
  })
}
```
And wait for that promise to resolve using 
```ts
  ipcMain.on('magian:legacy:installAshita', (e) => {
    try{
    console.log('received ashita update request')
    // eslint-disable-next-line promise/always-return, promise/catch-or-return
    updateAshita().then((v) => {
      console.log(v)
      e.reply('magian:legacy:installAshita:reply')
    })
  } catch(err) {console.log(`${err}`)}})
```

That the promise will not resolve until after the process has exited. 

### Actual Behavior

The promise resolves early and causes my mutex to proceed to the next task, causing my application to crash because it's trying to read directories that don't exist yet.

**Comment by mlaurencin** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, but this appears to be more of a question about how to resolve an issue with your code. You will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by ChristopherJTrent** [comment]
> Thanks for reaching out!
> 
> The issues tracker is used for feature requests and bug reports, but this appears to be more of a question about how to resolve an issue with your code. You will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.
> 
> I hope this helps!

@mlaurencin Yeah the electron discord was completely worthless. They insisted on trying to tell me that I should do it by blocking the main thread.
I posted this as a bug because it violates every single convention about how promises work, and is therefore a bug.

**Comment by VerteDinde** [comment]
@ChristopherJTrent, your comment was deleted as a violation of [the Electron Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md). You may consider this an official warning.

Please do not interact with the project for 24 hours. After that, you're welcome to continue any issues or discussions as needed, as long as they fall within the code of conduct guidelines. I understand that working with open source software can be frustrating, but please be kind and civil to the people who are trying to help maintain that software.
