### ISSUE TITLE
[Bug]: Electron crashes with background color (hexadecimal with transparency)

### ISSUE THREAD

**Issue by hovancik** [electron/electron#42704]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^31.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Last Known Working Electron version

30

### Expected Behavior

I can set `backgroundColor: '#1D1F21d9'`

### Actual Behavior

when I do, electron crashes

`ERROR:crashpad_client_win.cc(868)] not connected`

### Testcase Gist URL

https://github.com/hovancik/electron-bg-issue

### Additional Information

Affects Linux as well. I do not have macOS to test but would guess the same.

**Comment by mlaurencin** [comment]
[Fiddle gist](https://gist.github.com/9f19928b3638a3afed3c678df57eed67). It looks like it starts failing on v31.0.0-beta.1. In Fiddle, it is erroring with the following exited code: `Electron exited with code 2147483651.` on Windows. On macOS instead of the number it is `SIGTRAP`
