### ISSUE TITLE
[Feature Request]: ESM Support for Node 22+

### ISSUE THREAD

**Issue by lemanschik** [electron/electron#42757]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It was not real possible for electron to support ESM in the entry point without -r esm (the NPM esm shim) to use ESM as Entrypoint nodejs gets a new flag in 22.0 that will get unflagged in 22.x electron will then out of the box support ESM and the below issue can be reopened and re closed.

This is only a tracking issue for that process.

- [ ] https://github.com/electron/electron/issues/21457

### Proposed Solution

The solution is awaiting node 22.x with none experimental support for require modules.

### Alternatives Considered

no alternativ existing alternativ is npm i esm node -r esm

### Additional Information

- [ ] https://github.com/nodejs/package-maintenance/issues/542

**Comment by lemanschik** [comment]
I would propose the following path forward now:

- Create ESM-only packages and only use the module field. Call it a day.
- Use the `-r esm` flag to require the ESM NPM module to activate user-land support for `require(esm-module.js)` with additional support for top-level await as a migration path.
- From Node.js 22+ onward, migrate to `--experimental-require-module` and `-r esm` until the other flag works.
- From Node.js 22.x+ when the experimental flag gets an opt-out flag, call it a day. We will have resolved the ambiguity. Top-level import can import ESM and CJS code, and `require` can do the same. While everything should get transpiled to ESM for analyzability and tooling.
- should annoy people to produce only exports["string"] = assignments and do avoid module.exports as migration path also exports.name = any is total ok simple let them avoid module.exports = and we wre good to go

## Special edge case electron and other runtimes consuming npm
There are cases where .cjs is needed they will simple need to create a cjs entrypoint inside that single application where they use the modules they should not publish that application but if they wish to publish it then they simple publish it with a post install transpil to cjs hook or again use the -r esm flag

_Originally posted by @lemanschik in https://github.com/nodejs/package-maintenance/issues/542#issuecomment-2203064535_
            
            
```js
require('es-module.js')
```

**Comment by VerteDinde** [comment]
Thanks for filing this issue. As of right now, Electron does support ESM for Node 22 and higher, and we're not aware of any upstream changes that would change the state of ESM in future versions of Node. If you do find an upstream issue that may change ESM support, feel free to link it here and we'll look into reopening this issue.

**Comment by lemanschik** [comment]
@VerteDinde i guess this is that change as it allows to import esm via require when the esm code does not depend on top level await

**Comment by lemanschik** [comment]
require('ESM-module.js') does only work when the module has no top level await that means that the missing part.

**Comment by lemanschik** [comment]
it will sync require the ESM Code without additional loop

**Comment by lemanschik** [comment]
```js
const { app } = require('electron');
const myEsm = require('my-es-module.js');
app.on('window-all-closed', () => {
  myEsm.doIt();
  app.quit();
})


app.whenReady()
```
