### ISSUE TITLE
[Bug]: Need to click two times for elements of other window on Mac

### ISSUE THREAD

**Issue by xiaofeihan1** [electron/electron#42759]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.2

### What operating system are you using?

macOS

### Operating System Version

MacOS 14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

click one times to click button/link of another window

### Actual Behavior

click two times to click button/link of another window

### Additional Information

1. Use electron to create two windows
2. Focus window 1
3. Click a button/link of window 2

**Comment by xiaofeihan1** [comment]
Attached the video.
I can use a simple Electron app to reproduce the issue. But I found it seems VSCode can work as expected. Is there some API to change the behavior?

https://github.com/electron/electron/assets/107654914/d4e12014-9a7b-42a4-ad6d-8a3163ac0c43

**Comment by xiaofeihan1** [comment]
Attached the gist. https://gist.github.com/6df0920a657bdeecf5b7db427e1d3b78

**Comment by codebytere** [comment]
This is unfortunately expected behavior - it occurs in many native apps as well. A second click is required as the first one only focuses the window.
