### ISSUE TITLE
[Bug]: getUserMedia to get system-wide or window audio capture on Windows errors or terminates renderer

### ISSUE THREAD

**Issue by CynicalBusiness** [electron/electron#42765]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Version 23H2

### What arch are you using?

x64

### Expected Behavior

System audio can be accessed with `getUserMedia`.

### Actual Behavior

System audio is inaccessible.

When requesting audio + video from [the desktopCapturer docs](https://www.electronjs.org/docs/latest/api/desktop-capturer):
```javascript
await navigator.mediaDevices.getUserMedia({
  audio: {
    mandatory: {
      chromeMediaSource: 'desktop'
    }
  },
  video: {
    mandatory: {
      chromeMediaSource: 'desktop'
    }
  }
});
```

I get: `DOMException: Could not start audio source` (and this error has no stack)

Even if I specify a `chromeMediaSourceId` to either `screen:0:0` or any window, the same error occurs.

When requesting *only* audio:
```javascript
await navigator.mediaDevices.getUserMedia({
  audio: {
    mandatory: {
      chromeMediaSource: 'desktop'
    }
  }
});
```
The entire renderer process is instantly terminated and a message appears from the main process: `[48728:0703/162757.047:ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 263`

### Additional Information

My end goal with part of the application is to record system audio; I do not care about video. The solution only needs to work on Windows for now.

I investigated a solution like [pulseaudio2](https://www.npmjs.com/package/pulseaudio2) as well, but with Electron lacking a good method to send data streams between main and renderer AFAIK, not sure about that one either.

**Comment by CynicalBusiness** [comment]
An update:
In doing some research I saw a mention somewhere that Logitech audio drivers break Chromium's underlying audio engine, so I tried playing with that.

Turns out, after *completely unplugging* (not just turning off) my Logitech headset, Electron's audio now works as expected up until I plug it back in, then the error re-appears.

This headset works in other Electron-powered apps (Discord, Teams, etc.) so I'm unsure why its mere presence breaks my own Electron v31 app if the issue is upstream (unless it's fairly new).

**Comment by codebytere** [comment]
See https://github.com/electron/electron/issues/41024#issuecomment-1953172032

There's not much we can do here, sorry 😓

**Comment by CynicalBusiness** [comment]
> See [#41024 (comment)](https://github.com/electron/electron/issues/41024#issuecomment-1953172032)
> 
> There's not much we can do here, sorry 😓

I took a look at the comment and the mentioned `getUserMedia()` function, and while this works to capture a mic or output to a speaker, I can't capture system audio with this.
There is `getDisplayMedia()`, but trying to use this within an electron renderer gives me `DOMException: Not supported` (and I've tried a bunch of different constraints).

I can switch to another API, but what is now the supported method for capturing system (either window or whole desktop) video/audio? To enumerate window/screens?

**Comment by Alpha-T30** [comment]
> An update: In doing some research I saw a mention somewhere that Logitech audio drivers break Chromium's underlying audio engine, so I tried playing with that.
> 
> Turns out, after _completely unplugging_ (not just turning off) my Logitech headset, Electron's audio now works as expected up until I plug it back in, then the error re-appears.
> 
> This headset works in other Electron-powered apps (Discord, Teams, etc.) so I'm unsure why its mere presence breaks my own Electron v31 app if the issue is upstream (unless it's fairly new).

Did you get any solution for the Logitech device ???
