### ISSUE TITLE
[Bug]: 非常严重的bug，关于鼠标穿透窗口和移动窗口的bug

### ISSUE THREAD

**Issue by 2514765066** [electron/electron#42772]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.1 ， 28.1.2 ，31.0.1

### What operating system are you using?

Windows

### Operating System Version

win11家庭版

### What arch are you using?

x64

### Last Known Working Electron version

30.0.1

### Expected Behavior

我在做一个简单的桌面美化类的软件，我找到了bug并且还原了bug，如果一个browserwindow窗口win设置了 忽略鼠标事件并且保留鼠标悬浮win.setIgnoreMouseEvents(true, { forward: true });，另一个窗口win1里面有一个元素设置了  -webkit-app-region: drag;这个可以拖动窗口的css属性，就会出现bug，我拖动win1这个窗口到win窗口上的时候win1窗口会疯狂频闪抖动，我认为他不应该会频闪抖动

### Actual Behavior

我在做一个简单的桌面美化类的软件，我找到了bug并且还原了bug，如果一个browserwindow窗口win设置了 忽略鼠标事件并且保留鼠标悬浮win.setIgnoreMouseEvents(true, { forward: true });，另一个窗口win1里面有一个元素设置了  -webkit-app-region: drag;这个可以拖动窗口的css属性，就会出现bug，我拖动win1这个窗口到win窗口上的时候win1窗口会疯狂频闪抖动，我上传了yi'g一段mp4的视频，用来展示我出现的问题，还有的代码截图，一个是我的主进程，一个是我的渲染进程
![image](https://github.com/electron/electron/assets/122349197/93e6a5b9-db6d-466e-8c79-ae22cd9919b3)
![image](https://github.com/electron/electron/assets/122349197/62997c1d-d110-4cc9-a156-1d9e37b7b136)

https://github.com/electron/electron/assets/122349197/ad0e6b83-df12-4b61-9446-baed17272012

**Comment by 2514765066** [comment]
不论是使用 -webkit-app-region: drag;来拖动窗口还是使用electron自带的标题栏拖动，他都会出现频闪和错位

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
