### ISSUE TITLE
[Bug]: if protocol.handle "http" or "https", all header change to lowner case 

### ISSUE THREAD

**Issue by oohusl** [electron/electron#42774]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.*

### What operating system are you using?

macOS

### Operating System Version

14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

http header keys not changed

### Actual Behavior

http header keys change to lower case

### Additional Information

protocol.handle("http", async (req) => {
    let iter = req.headers.keys();
    let result = iter.next()
    while (!result.done) {
      console.log(result.value);
      result = iter.next();
    }
    return net.fetch(req, { bypassCustomProtocolHandlers: true, cache: 'reload' });
  })

all the output and send to server, http header change to lower case

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
