### ISSUE TITLE
[Bug]: render process randomly can not exit and cpu is busy after terminate main process.

### ISSUE THREAD

**Issue by LowellTest** [electron/electron#42770]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31-x-y

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 2263

### What arch are you using?

x64

### Expected Behavior

process can exit successfully after quit main process.

### Actual Behavior

process can not exit and cpu always be busy.

### Additional Information

the render process' main thread is busy and nested infinite loops.
third_party\blink\renderer\platform\widget\compositing\layer_tree_view.cc:
RequestNewLayerTreeFrameSink -> SetLayerTreeFrameSink -> DidFailToInitializeLayerTreeFrameSink -> RequestNewLayerTreeFrameSink

**Comment by LowellTest** [comment]
enabled the feature named kEstablishGpuChannelAsync in chromium can fix this issue.

**Comment by LowellTest** [comment]
did not reproduced with Electron Fiddle under electron 29.0.0 and above.
only reproduced with a very sample test app with sandbox: false under electron 27.x.y

**Comment by georgexu99** [comment]
Hey @LowellTest , can you attach the fiddle reproducible gist in the issue? 🙇

**Comment by LowellTest** [comment]
Hi @georgexu99 here is the reproducible steps.

![image](https://github.com/user-attachments/assets/ab5f1c5a-dcac-4bb2-b290-41d4f3733c32)
1.set sandbox false here.
2.run the test electron app,

3. kill the main process in the Task Manager.

![image](https://github.com/user-attachments/assets/c0010ba1-5d5c-4a1b-9553-529316adb669)
4. the renderer process will not quit after kill the main process in the Task Manager.

can reproduced with electron 31.1.0
![image](https://github.com/user-attachments/assets/3b3abf1f-73fa-4551-bf98-b928fd05c1fb)

**Comment by LowellTest** [comment]
I also find another ticket https://github.com/electron/electron/issues/42918, looks like it is same.
