### ISSUE TITLE
[Bug]: Setting up a MessageChannel between two renderers not working

### ISSUE THREAD

**Issue by davidwinograd1** [electron/electron#42784]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.6

### What operating system are you using?

macOS

### Operating System Version

MacOS Sonoma 14.5

### What arch are you using?

x64

### Expected Behavior

Hi guys,

Using ElectronJS, I'm trying to get one component to send props to another in a new window, but there are some errors along the way. I'd appreciate any help. I'll give the highlights of the code:

Main process (Both 'Main window ready to show, sending port1' and 'Port1 sent to main window' log):

win = new BrowserWindow({
width: 900,
height: 670,
center: true,
title: 'Boutboard',
frame: false,
titleBarStyle: 'hidden',
vibrancy: 'under-window',
visualEffectState: 'active',

webPreferences: {
nodeIntegration: false,
contextIsolation: true,
preload,
enableBlinkFeatures: 'CSSWindowDragging',
},
})

// Create a hidden secondary window for FanFacingClock
secondaryWindow = new BrowserWindow({
show: false,
webPreferences: {
nodeIntegration: false,
contextIsolation: true,
preload,
},
})

const { port1, port2 } = new MessageChannelMain()

win.once('ready-to-show', () => {
console.log('Main window ready to show, sending port1')
win?.webContents.postMessage('port', null, [port1])
console.log('Port1 sent to main window')
})

secondaryWindow.once('ready-to-show', () => {
secondaryWindow?.webContents.postMessage('port', null, [port2])
})

ipcMain.on('open-fan-facing-clock', () => {
if (secondaryWindow) {
secondaryWindow.show()
}
})

Preload (anything after ipcRenderer.on does not long -- is my preload set up right?):

import { contextBridge, ipcRenderer } from 'electron'

console.log('Preload script is running') // this works

const electronAPI = {
onPort: (callback: (port: MessagePort) => void) => {
console.log('Setting up onPort listener')
ipcRenderer.on('port', (event) => {
console.log('Port message received in preload script')
const [port] = event.ports
if (port) {
console.log('Port is valid, calling callback')
port.start()
callback(port)
} else {
console.error('Received invalid port')
}
})
},
openFanFacingClock: () => {
console.log('Sending open-fan-facing-clock message')
ipcRenderer.send('open-fan-facing-clock')
},
}

contextBridge.exposeInMainWorld('electronAPI', electronAPI)
console.log('electronAPI exposed to main world')

^^ Here it is important to note that while 'Setting up onPort listener' always logs, 'Port message received in preload script' does not!

Component 1 ('Received port in ScoreclockV2:', receivedPort) never runs but everything before it does):

useEffect(() => {
console.log('window.electronAPI:', window.electronAPI)
if (!window.electronAPI || !window.electronAPI.onPort) {
console.error('electronAPI or onPort not found on window object')
return
}
console.log('Setting up port listener in ScoreclockV2')
window.electronAPI.onPort((receivedPort) => {
console.log('Received port in ScoreclockV2:', receivedPort)
if (receivedPort) {
console.log('Port properties:', Object.keys(receivedPort))
setPort(receivedPort)
} else {
console.error('Received port is null or undefined in ScoreclockV2')
}
})
}, [])

useEffect(() => {
if (port) {
console.log('Port is set:', port)
const sendUpdate = () => {
const updateData = {
leftScore,
rightScore,
time: wrestlingClockLogic.formattedTime,
leftWrestler,
rightWrestler,
boutNumber,
}
console.log('ScoreclockV2 sending update:', updateData)
port.postMessage(updateData)
}

// Send updates whenever relevant state changes
sendUpdate()
}
}, [
port,
leftScore,
rightScore,
wrestlingClockLogic.formattedTime,
leftWrestler,
rightWrestler,
boutNumber,
])

const openFanFacingClock = () => {
console.log('Opening fan-facing clock')
window.electronAPI.openFanFacingClock()
}

Component 2 (Setting up port listener logs but never "Received port", same as before):

export function FanFacingClockWrapper() {
const [clockData, setClockData] = useState({
leftScore: 0,
rightScore: 0,
time: '0:00',
leftWrestler: '',
rightWrestler: '',
boutNumber: 0,
})

useEffect(() => {
console.log('Setting up port listener in FanFacingClockWrapper')
window.electronAPI.onPort((port) => {
console.log('Received port in FanFacingClockWrapper:', port)
if (port) {
port.onmessage = (event) => {
console.log('Received message in FanFacingClockWrapper:', event.data)
setClockData(event.data)
}
} else {
console.error('Received invalid port in FanFacingClockWrapper')
}
})
}, [])

return <FanFacingClock {...clockData} />
}

Can anyone let me know what I'm doing wrong? I'm just trying to send data from Component 1 to Component 2 essentially.

Thanks!

### Actual Behavior

Props do not get sent. They are stuck at default values in new window.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
