### ISSUE TITLE
[Bug]: Using `desktopCapturer` to share the chrome window, it can not display drop-down list effect powered by html label <select> and <option>

### ISSUE THREAD

**Issue by wangdiqi** [electron/electron#42782]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.3

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura Version 13.1

### What arch are you using?

x64

### Expected Behavior

I follow the document [here](https://www.electronjs.org/docs/latest/api/desktop-capturer) to share a window which is chrome application. The chrome application open a [website](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) contains a drop-down list(\<select\> and \<option\>). When i click the drop-down list in chrome application, the dropdown list effect should be displaying in my Electron application.

### Actual Behavior

When i click the drop-down list in chrome application, the dropdown list effect is not displaying in my Electron application, however, when I select an option, the final selected value displays correctly.

Image1 is what showing in Chrome.
Image2 is what showing in Electron for sharing screen.

<img width="736" alt="chrome" src="https://github.com/electron/electron/assets/7059919/a2a731ad-b678-4ba1-a94b-4339d1fe99e7">
<img width="496" alt="electron-sharing-sceen" src="https://github.com/electron/electron/assets/7059919/82e142f1-a275-4af9-9cd2-0587343f0e8c">

### Testcase Gist URL

https://gist.github.com/e3e6faf584a9ef47685d875d298dd517

### Additional Information

I can not determine it

**Comment by shah-azman-sakin-alam** [comment]
You need to share more information, your code? We cannot reproduce the problem without that.

**Comment by wangdiqi** [comment]
> You need to share more information, your code? We cannot reproduce the problem without that.

I shared the testcase gist : https://gist.github.com/e3e6faf584a9ef47685d875d298dd517. You can use 'electron fiddle' to reproduce the problem directly.

If it's inconvenient, the main code looks like this(it's almost copied from the [documentation](https://www.electronjs.org/docs/latest/api/desktop-capturer).):

```
# main.js

ipcMain.on("start-share-screen", (event) => {
    const webContents = event.sender;
    const win = BrowserWindow.fromWebContents(webContents);
    desktopCapturer
      .getSources({ types: ["window", "screen"] })
      .then(async (sources) => {
        console.log("sources: ", sources);
        win.webContents.send("SET_SOURCES", sources);
      });
  });

# preload.js

onSetSources: (callback) =>
    ipcRenderer.on("SET_SOURCES", (_event, sources) => {
      console.log("_event: ", _event, "; sources: ", sources);
      callback(sources);
    }),

# render.js

const stream = await navigator.mediaDevices.getUserMedia({
      audio: false,
      video: {
        mandatory: {
          chromeMediaSource: "desktop",
          chromeMediaSourceId: sourceId,
          minWidth: 1280,
          maxWidth: 1280,
          minHeight: 720,
          maxHeight: 720,
        },
      },
    });
    console.log("videoShareScreen: ", videoShareScreen);
    console.log("steam: ", stream);
    videoShareScreen.srcObject = stream;
    videoShareScreen.onloadedmetadata = (e) => videoShareScreen.play();
```

Thank you and look forward to your reply.

**Comment by codebytere** [comment]
I see the dropdown as expected:

<img width="527" alt="Screenshot 2024-07-08 at 11 17 53 AM" src="https://github.com/electron/electron/assets/2036040/2d2b885f-460b-41d3-b5a2-466f5ff9efcc">

**Comment by wangdiqi** [comment]
> I see the dropdown as expected:
> 
> <img alt="Screenshot 2024-07-08 at 11 17 53 AM" width="527" src="https://private-user-images.githubusercontent.com/2036040/346502683-2d2b885f-460b-41d3-b5a2-466f5ff9efcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0ODY2MjgsIm5iZiI6MTcyMDQ4NjMyOCwicGF0aCI6Ii8yMDM2MDQwLzM0NjUwMjY4My0yZDJiODg1Zi00NjBiLTQxZDMtYjVhMi00NjZmNWZmOWVmY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDA1MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVkYjY3MjgyNjExNDZmMjEzMWI3MjcwMTA4MDllMmQzMDZkNjk0Yzc1YmEzMGNiY2UwZWNmM2NiYzYzMzEyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AyYUinaVgsw1Ym2SGHDY4SvVoZQQcS2rbbUWSX9IIns">

Hello，

> I see the dropdown as expected:
> 
> <img alt="Screenshot 2024-07-08 at 11 17 53 AM" width="527" src="https://private-user-images.githubusercontent.com/2036040/346502683-2d2b885f-460b-41d3-b5a2-466f5ff9efcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0ODY2MjgsIm5iZiI6MTcyMDQ4NjMyOCwicGF0aCI6Ii8yMDM2MDQwLzM0NjUwMjY4My0yZDJiODg1Zi00NjBiLTQxZDMtYjVhMi00NjZmNWZmOWVmY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDA1MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVkYjY3MjgyNjExNDZmMjEzMWI3MjcwMTA4MDllMmQzMDZkNjk0Yzc1YmEzMGNiY2UwZWNmM2NiYzYzMzEyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AyYUinaVgsw1Ym2SGHDY4SvVoZQQcS2rbbUWSX9IIns">

Thank you for your reply. The problem I'm referring to is not the dropdown menu here. Using your screenshot as an example, here are the steps to reproduce the issue:

step1: Let's select 'Google Chrome - window:111683:0'.
step2: Open the webpage 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select' in the selected Google Chrome window.
step3: Click on the dropdown menu on the opened webpage, as shown in Image 3.
step4: Observe the shared screen page in Electron.

![Image3](https://github.com/electron/electron/assets/7059919/2552e96e-53f3-4683-b007-774bc786f5e4)

**Comment by wangdiqi** [comment]
> I see the dropdown as expected:
> 
> <img alt="Screenshot 2024-07-08 at 11 17 53 AM" width="527" src="https://private-user-images.githubusercontent.com/2036040/346502683-2d2b885f-460b-41d3-b5a2-466f5ff9efcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0ODczOTYsIm5iZiI6MTcyMDQ4NzA5NiwicGF0aCI6Ii8yMDM2MDQwLzM0NjUwMjY4My0yZDJiODg1Zi00NjBiLTQxZDMtYjVhMi00NjZmNWZmOWVmY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDEwNDU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTE2ZTY1M2ViZGI4NjYwM2JiYjg5MDdkOGJmMzc1MzQyNTZlZWY0NmNiMzEyMmFmZWE1ZWM1ZTc3MDM1OTM1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ETSBnWOeOZOLFVKSTxA3L32qVejpRBnkeOr2NXOkseI">

Thank you for your reply. The problem I'm referring to is not the dropdown menu here. Using your screenshot as an example, here are the steps to reproduce the issue:

step1: Let's select 'Google Chrome - window:111683:0'.
step2: Open the webpage 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select' in the selected Google Chrome window.
step3: Click on the dropdown menu on the opened webpage, as shown in Image 3.
step4: Observe the shared screen page in Electron.

![Image3](https://github.com/electron/electron/assets/7059919/20b95ab9-87b9-4dd7-b179-19dde4c4bd98)
