### ISSUE TITLE
[Bug]: Remote Permissions not automatically accepted

### ISSUE THREAD

**Issue by moritztim** [electron/electron#42783]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.1.0

### What operating system are you using?

Other Linux

### Operating System Version

`Arch Linux moritz 6.6.36-1-lts #1 SMP PREEMPT_DYNAMIC Thu, 27 Jun 2024 12:26:27 +0000 x86_64 GNU/Linux`

### What arch are you using?

x64

### Expected Behavior

According to [the docs](https://www.electronjs.org/docs/latest/tutorial/security#5-handle-session-permission-requests-from-remote-content):
> By default, Electron will automatically approve all permission requests unless the developer has manually configured a custom handler.
And running [this](https://github.com/moritztim/electron-permissions-demo/) very simple setup with electron (`electron .`) works as expected.

### Actual Behavior

However when I access it as a website from electron (`python -m http.server --directory .` `electron http://ocalhost:8000`), it launches a popup. Am I missing something here or is this a bug?

### Testcase Gist URL

https://github.com/moritztim/electron-permissions-demo/

**Comment by codebytere** [comment]
hey @moritztim - this is a function of the way Electron's `default_app` works. There is a default permissions handler: https://github.com/electron/electron/blob/ac031bf8dedf8e3da6d918cbbc2e64a03830c639/default_app/default_app.ts#L75-L88.

When you run the app directly using electron, you're not running the default app. However, when you access it as you are (via `python -m http.server --directory . electron http://ocalhost:8000`) you're running Electron without providing a consumer app and thus the default app is run.

**Comment by codebytere** [comment]
@moritztim for a consumer app, Electron will automatically approve all permission requests unless the developer has manually configured a custom handler.

you didn't provide a consumer app to the electron binary in the scenario where the popup occurred - this is functioning as intended.
