### ISSUE TITLE
[Bug]: Frameless window frame is visible when BrowserWindow after focus lost

### ISSUE THREAD

**Issue by ararif724** [electron/electron#42791]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Window should be frameless

### Actual Behavior

`const window = new BrowserWindow({
	frame: false,
	transparent: true,
	width: 770,
	height: 650,
	fullscreenable: false,
	resizable: false,
	webPreferences: {
		preload: preloadScriptPath + "/mainWindowPreload.js",
	},
});`

Window should be frameless. It's works fine in linux mint and mac.

But in windows 11 initially frame is not visible but after app lost focus (Like if we click on desktop empty place) the titlebar become visible.

![image](https://github.com/electron/electron/assets/48169386/6c2455e0-59e5-426d-9ed9-c41cefeac3ae)

### Additional Information

Seems this issue was before but fixed in 1.8.3.

But the issue reappears.

Old issue link:
https://github.com/electron/electron/issues/11849

**Comment by ararif724** [comment]
I found a hotfix if I disable hardware acceleration the issue disappear.

`app.disableHardwareAcceleration();`

**Comment by codebytere** [comment]
Not seeing this - can you please provide a more complete repro?

<img width="1179" alt="Screenshot 2024-07-08 at 10 41 14 AM" src="https://github.com/electron/electron/assets/2036040/dcc364aa-80c0-4ee1-bde7-b3c9ea4d253e">

**Comment by nicfix** [comment]
bump
