### ISSUE TITLE
[Bug]: webContents.executeJavaScript fails when body content contains \0 or \1

### ISSUE THREAD

**Issue by oiooooio** [electron/electron#42790]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.3.0

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Last Known Working Electron version

24.3.0

### Expected Behavior

The webContents.executeJavaScript method should execute JavaScript code correctly, even if the body content contains characters like \0 and \1.

executeJavaScript， 测试下来发现， 如果body内容里有\0 \1 也就是 +数字，就会报错， \a\b不会报错， 这个问题是否已经解决？

### Actual Behavior

When the body content contains characters such as \0 or \1 (i.e., \ followed by a digit), the webContents.executeJavaScript method throws an error. However, characters like \a and \b do not cause any issues.

**Comment by oiooooio** [comment]
![image](https://github.com/electron/electron/assets/34410568/cddcb0c5-fa02-4348-895c-2374c297de2c)

**Comment by oiooooio** [comment]
eg:
  <div data-v-a31162ca="" class="fz--text">\\192.168.3.27\1604-6\2024年0 </div>

**Comment by oiooooio** [comment]
`
eg:
  <div data-v-a31162ca="" class="fz--text">\\192.168.3.27\1604-6\2024年0 </div>
`

**Comment by oiooooio** [comment]
```
eg:
  <div data-v-a31162ca="" class="fz--text">\\192.168.3.27\1604-6\2024年0 </div>
```

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
