### ISSUE TITLE
[Bug]: Window CSD borders at the wrong position

### ISSUE THREAD

**Issue by RushingAlien** [electron/electron#42793]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Last Known Working Electron version

30

### Expected Behavior

![gambar](https://github.com/electron/electron/assets/80886145/234388c5-8191-462e-b8f4-0e23839afdef)

Window border ends at border

### Actual Behavior

![gambar](https://github.com/electron/electron/assets/80886145/9e0f67bf-7a2f-4fc3-9aa5-3afedc166194)

Window border ends at CSD shadow?

### Additional Information

To check window border i used the `rounded-window-corners-reborn` extension on GNOME. The extension has a feature to draw an outline at window border.

**Comment by codebytere** [comment]
@RushingAlien please first report this to Discord and see what they say If they determine it's an Electron issue, we can investigate further.

**Comment by RushingAlien** [comment]
![gambar](https://github.com/electron/electron/assets/80886145/52cd08eb-ffef-4f50-a24f-c362d7698d3a)

@codebytere, I can reproduce this in plain electron in
- GNOME Wayland
- use `--ozone-platform-hint=auto`

**Comment by RushingAlien** [comment]
![gambar](https://github.com/electron/electron/assets/80886145/001f98be-4238-4a11-a789-a07e5ec41b49)

and yes, it does not happen on electron 30, just 31. I hope this can be reopened without needless back and forth.

**Comment by RushingAlien** [comment]
@codebytere Sorry to notify you, but considering this can be reproduced with just electron: https://github.com/electron/electron/issues/42793#issuecomment-2213394865 , can this be reopened?

**Comment by RushingAlien** [comment]
I'm sorry but it's been 4 days, so I'd like to notify once again that this can be reproduced with plain electron.
