### ISSUE TITLE
[Bug]: `ipcRenderer.on` does not trigger in `contextBridge.exposeInMainWorld`

### ISSUE THREAD

**Issue by rtritto** [electron/electron#42804]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

`ipcRenderer.on` event should trigger such as `ipcRenderer.send` event.

`preload.ts`
```ts
contextBridge.exposeInMainWorld('electronApi', {
  ipcRenderer: {
    on: ipcRenderer.on,
    send: ipcRenderer.send
  }
})
```

### Actual Behavior

`ipcRenderer.on` event should not trigger.

I need to use this workaround:
`preload.ts`
```ts
contextBridge.exposeInMainWorld('electronApi', {
  ipcRenderer: {
    on: (channel, listener) => ipcRenderer.on(channel, listener),
    send: ipcRenderer.send
  }
})
```

### Additional Information

`Home.tsx`
```tsx
  const restartApp = () => {
    window.electronApi.ipcRenderer.send('test-send')
  }

  createEffect(() => {
    window.electronApi.ipcRenderer.on('test-on', (event: Electron.IpcRendererEvent, testPar: number) => {
      ...
    })
  }, [])
```

**Comment by MarshallOfSound** [comment]
Exposing `ipcRenderer` or it's methods over the bridge is a security foot gun and effectively neutralizes a core reason you need to use the bridge.

Ref: https://github.com/electron/electron/blob/main/docs/breaking-changes.md#behavior-changed-ipcrenderer-can-no-longer-be-sent-over-the-contextbridge

Expose the **minimal** API surface that your app requires over the bridge, not a wildcard API like `on` or `send`.

**Comment by rtritto** [comment]
@MarshallOfSound It's correct to use:

`Home.tsx`
```ts
contextBridge.exposeInMainWorld('electronApi', {
  ipcRenderer: {
    on: (channel, listener) => ipcRenderer.on(channel, listener),
    send: ipcRenderer.send
  }
})
```

**Comment by rtritto** [comment]
This should be good:

`Home.tsx`
```ts
contextBridge.exposeInMainWorld('electronApi', {
  ipcRenderer: {
    on(channel: Channels, func: (...args: any[]) => void) {
      const subscription = (_event: Electron.IpcRendererEvent, ...args: any[]) => func(...args)
      ipcRenderer.on(channel, subscription)

      return () => {
        ipcRenderer.removeListener(channel, subscription)
      }
    },
    send(channel: Channels, ...args: any[]) {
      ipcRenderer.send(channel, ...args)
    }
  }
})
```

The code
```ts
return () => {
  ipcRenderer.removeListener(channel, subscription)
}
```

relpace this

```tsx
useEffect(() => {
  // Clean the listener after the component is dismounted
    return () => {
      window.electronApi.ipcRenderer.removeAllListeners(CHANNELS.CHECK_FOR_UPDATE)
    }
  }, [])
```
?
