### ISSUE TITLE
[Bug]: Configure the configuration of the HTTPS web API to work properly under HTTP.

### ISSUE THREAD

**Issue by xhc-code** [electron/electron#42812]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.0

### What operating system are you using?

Windows

### Operating System Version

window 10

### What arch are you using?

x64

### Expected Behavior

I expect the Electron to have configuration properties that support the use of MediaDevices: getUserMedia API under HTTP, as this is a necessary prerequisite for my business needs.

### Actual Behavior

![image](https://github.com/electron/electron/assets/28866025/09f3614e-4763-488e-b295-1019649576ac)
hi, This is the BrowserWindow configuration I used, and even though I set the webSecurity property to false, it still cannot solve the problem of using MediaDevices: getUserMedia.

I want to use the MediaDevices: getUserMedia API through the loadURL of Electron, but it needs to be used in a local area network environment and in an HTTP protocol IP address environment. Is there any way Electron can configure MediaDevices: getUserMedia API to use this API in HTTP? What content needs to be configured? I saw in MDN that this can only be used under the HTTPS protocol.

### Additional Information

Electron accessing services through loadURL is used on the local area network and accessed through IP.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by xhc-code** [comment]
> Thanks for reaching out!
> 
> Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

Hello, neither Stackerflow nor Discord has solved my problem for some time now, and I urgently need a solution.thank you

**Comment by Waris007-hub** [comment]
ฉัน สามารถ ให้ เมลฉัน ให้คุณเข้าได้ไหม

**Comment by Waris007-hub** [comment]
ดิส ฉันเข้าไม่ได้

**Comment by Waris007-hub** [comment]
ใน บัชชี Waris007 ฉัน มีไฟล์

**Comment by xhc-code** [comment]
> ฉัน สามารถ ให้ เมลฉัน ให้คุณเข้าได้ไหม

Hello, may I ask if this is related to my question? Or did you answer in the wrong position.
