### ISSUE TITLE
[Bug]: File menu item automatically renamed to "Settings..."

### ISSUE THREAD

**Issue by adityatoshniwal** [electron/electron#42837]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.1.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I am from pgAdmin team and we're working on integrating Electron. I noticed that my menu labelled as "Preferences" is automatically renamed as "Settings...". This doesn't happen on Windows.
Screenshot below:
![image](https://github.com/electron/electron/assets/31855755/fe8d10b7-0905-4a1a-9d5c-b7ae5c4aa561)

### Actual Behavior

Auto renaming the menu should be optional.
It doesn't look like an OS issue as it works fine in NW.js which is also based on Chromium.
I had raised this here https://github.com/electron/electron/issues/42583 but there was no response for long.

### Testcase Gist URL

https://gist.github.com/adityatoshniwal/9a97d779ca50617c765ea0aeae61cce4

**Comment by codebytere** [comment]
https://github.com/electron/electron/issues/42583#issuecomment-2180357898

**Comment by adityatoshniwal** [comment]
> [#42583 (comment)](https://github.com/electron/electron/issues/42583#issuecomment-2180357898)

You missed my comment on NW.js? NW.js is also chromium based and it doesn't rename like Electron does.

**Comment by codebytere** [comment]
@adityatoshniwal it's because NW.js is using a macOS SDK that is years old and extremely out of date
