### ISSUE TITLE
[Bug]: getUserMedia Fails when called for a single window from an elevated context.

### ISSUE THREAD

**Issue by Antelope-IT** [electron/electron#42882]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 10 22H2 19045.4651

### What arch are you using?

x64

### Last Known Working Electron version

29.4.4

### Expected Behavior

When calling getUserMedia with chromeMediaSource: 'desktop' and a chromeMediaSourceId that points to a single application window from an Electron app running in an elevated context (as administrator) I expect it to return a stream which can be set as the source object of an HTML video element so that the source application window content is played in the video element of the electron app.

### Actual Behavior

If the Electron app is running in an elevated context (as administrator) and the source is an application window then getUserMedia method throws a "DOMException: Could not start video source." 

If the source is a Fullscreen capture then the call to getUserMedia works and a video of the fullscreen activity is played in the electron app window. 

When the Electron app is not running in an elevated context (normal user privileges) then both application window and fullscreen sources can be captured without issue.

### Testcase Gist URL

https://gist.github.com/31ccba107ebb68af1b90a1a466013378

### Additional Information

I've provided the above Electron Fiddle gist - You can test it by running Electron fiddle as administrator on a Windows machine with Electron version 30+. 
When the selected source is an application window (source name starts with 'Electron') Then no video appears in the Electron application window and the DOMException error is visible in the devtools console.

If you edit the main code uncomment line 27 and comment line 28 to change the selected source to a screen then the fullscreen is captured and shown in the Electron application window, asexpected.

If you run the Electron Fiddle app with normal privileges then the selected source is captured regardless of source type and Electron version.

If you change the version of Electron to version 29.x.x then the video is captured regardless of source type or privilege elevation.

The bug was first detected in a production Electron application both when being debugged via VSCode and as a packaged application - running with elevated privileges as it has to.

The Electron fiddle was built as a simple demonstration by taking the desktopCapturer demontration code from the Electron docs and applying it to the basic Electron Fiddle starter app. Additional code was added for logging  and clarity. 

I've run tests with Electron v29.0.0 and 29.4.4 - these versions work under all circumstances.  Versions 30.0.0, 30.0.1, 31.0.1 and 31.2.0 (latest at the time) all exhibited the error behaviour described above.

**Comment by chrismorrisprojects** [comment]
Confirming that I am able to replicate the same issue.

**Comment by codebytere** [comment]
Can this be replicated with the same API call in Chrome itself?

**Comment by Antelope-IT** [comment]
I'm not an expert with the Chrome API's and the first thing to note is that the getUserMedia API method exposed in Electron is different to the getUserMedia API in Chrome and the MDN documentation. I've hacked together a single page test harness (below) with the limited knowledge I have. 

If you call getUserMedia running in the Chrome browser with Electron compatible constraints (mandatory.chromesourceid etc) then it will fail; elevated context, or not. 

If you call getUserMedia with Chrome constraints either in an elevated context or not then it will capture the camera. But there doesn't seem to be a way to capture the desktop and its the desktop application windows and screens we want / used to get.

The only way I was able to capture a desktop application window or screen image was by using the Chrome getDisplayMedia method. Running this method in Chrome in a non elevated context enables you to capture either windows or screens or in fact any device on the machine but it requires the user to select the source to share from a popup and doesn't allow for programatical selection so while we can capture the required screen it doesn't fit the desired behaviour for the use case (programatic source selection - no user interaction) which is what we used to have in Electron < v30

Notably though in an attempt to answer your @codebytere question if you call getDisplayMedia from a script running in Chrome in an elevated context then it will allow you to select a window as a source but then it fails with the Error: _NotReadableError: Could not start video source_ Which is the same underlying error as in Electron.

I don't know how this reflects on the Electron code because tome they are different methods on different API's but Chrome is the technology underlying  Electron so I'm guessing it must have some bearing.

The above was found using the script below running in Chrome Version 126.0.6478.127 (Official Build) (64-bit) which is up-to-date at the time of writing.

` index.html`
```
<html>

  <body></body>
  <script>
    const captureDisplayMedia = async () => {
      // Works in Chrome but have to select source from system popup - not compatible with use case. 
      // Running in Chrome with elevated privileges throws Error: NotReadableError: Could not start video source
      try {
        const captureStream = await navigator.mediaDevices.getDisplayMedia();
        const video = document.createElement("video");
        document.body.appendChild(video);
        video.srcObject = captureStream;
        video.play()
      } catch (err) {
        console.error("Error: " + err);
      }
    };

    const captureUserMediaElectronApi = async (sourceId) => {
      // Fails Under all circumstances - API is not compliant with Chrome API its Electron only
      // Throws Rejected! DOMException: Invalid state
      navigator.mediaDevices
        .getUserMedia(
          {
            video: {
              mandatory: {
                chromeMediaSource: 'desktop',
                chromeMediaSourceId: sourceId,
              }
            },
            audio: false
          })
        .then((localMediaStream) => {
          const video = document.createElement("video");
          document.body.appendChild(video);
          video.srcObject = localMediaStream;
          video.play()
        })
        .catch((error) => {
          console.log("Rejected!", error);
        });
    };

    const captureUserMediaChromeApi = async () => {
      // Only capture Cameras and Microphones - Screens and Windows Not an option
      navigator.mediaDevices
        .getUserMedia(
          {
            video: true,
            audio: false
          })
        .then((localMediaStream) => {
          const video = document.createElement("video");
          document.body.appendChild(video);
          video.srcObject = localMediaStream;
          video.play()
        })
        .catch((error) => {
          console.log("Rejected!", error);
        });
    }

    window.addEventListener('DOMContentLoaded', () => {

      // Chrome Api getDisplayMedia - works, not when Chrome run as administrator and requires user to choose from popup.
      captureDisplayMedia();

      // Needed to set your own sourceId from Electron.desktopCapturer
      // let sourceId = 'window:460420:0';
      // captureUserMediaElectronApi(sourceId);

      // Chrome getUserMediaApi - starts Camera sharing only
      // captureUserMediaChromeApi();

    });
  </script>

</html>
```

**Comment by codebytere** [comment]
@Antelope-IT thanks for the detailed investigation! it's helpful and appreciated 🙇🏻‍♀️ 

We plumb our methods here essentially straight down to Chromium, so this error:

> NotReadableError: Could not start video source

is likely the real root error. The next best step here is to ask Chromium to investigate - so you should open a bug at ihttps://issues.chromium.org/issues with the set of steps necessary to reproduce the issue in Chrome itself.

**Comment by Antelope-IT** [comment]
I've raised an issue on Chromium org. For reference and tracking the link is [getDisplayMedia P2 Bug](https://issues.chromium.org/issues/353555347)

**Comment by codebytere** [comment]
I'm closing this out for now as it's not actionable on our side - when Chromium fixes it we will inherit the fix via our upgrade process.
