### ISSUE TITLE
[Bug]: Electron v29.4.4 missing from npm

### ISSUE THREAD

**Issue by mgalla10** [electron/electron#42907]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v29.4.4

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11 version 23H2

### What arch are you using?

x64

### Last Known Working Electron version

v29.4.3

### Expected Behavior

Defining Electron v29.4.4 as a dev dependency in a package.json file, then running "npm install", should install Electron v29.4.4 on the local machine.

### Actual Behavior

The installation fails with an ETARGET error code and message saying "No matching version found for electron@29.4.4.".

### Additional Information

It seems like Electron v29.4.4 is simply missing from npm. Running "npm view electron version" includes all versions up to v29.4.3, but not v29.4.4. The v32.0.0-alpha.8 version, which was released about 5 hours later, is present on the version list and installs without issue.

**Comment by yossev** [comment]
Only maintainers with publish permissions can publish new versions to the npm registry.

**Comment by erickzhao** [comment]
v29.4.4 was a failed publish on our part. v29.4.5 is now available, so please pick up changes by updating to that version on npm!
