### ISSUE TITLE
[Bug]: Crash reporter not sending the dump to remote URL

### ISSUE THREAD

**Issue by theIYD** [electron/electron#42958]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2.1

### What operating system(s) are you using?

Windows, macOS

### Operating System Version

Windows Server 2019 Datacenter

### What arch are you using?

x64

### Expected Behavior

The crash reporter should be sending the dump file with `compress: false` to the remote URL server.

### Actual Behavior

On Windows (using a datacenter VM for testing the app on Windows), the crash reporter successfully generates the dump files but is not able to POST on a remote URL. The flag `compress` is `false` as mentioned in the docs.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
