### ISSUE TITLE
[Bug]: REGRESSION, on MacOS starting 31 when you open devtool the text in the window become unselectable

### ISSUE THREAD

**Issue by peernohell** [electron/electron#43003]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2.1

### What operating system(s) are you using?

macOS

### Operating System Version

MacOS Sonoma 14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

30.3.0

### Expected Behavior

Text to be selectable

### Actual Behavior

Text is not selectable

### Testcase Gist URL

[Electron fiddle Gist](https://gist.github.com/8a83e75387e95c171ed4c523eef68a5f)

### Additional Information

You just need to change the version in the Electron Feedle.
In 30.3.0 everything is good.
starting version 31.0.0-alpha1 and more recent, the text is no more selectable.
If you comment line 30 from main.js (that just open the devtools) the text is selectable.

**Comment by peernohell** [comment]
I forgot to share the gist
https://gist.github.com/8a83e75387e95c171ed4c523eef68a5f

**Comment by codebytere** [comment]
Tracked to https://github.com/electron/electron/commit/e67ab9a93dadccecff30de50ab4555191c30b6c4
