### ISSUE TITLE
[Bug]: VS code crash and refering to Electron

### ISSUE THREAD

**Issue by glebramanchuk** [electron/electron#43007]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2.1

### What operating system(s) are you using?

macOS

### Operating System Version

Big Sir (11.7.10)

### What arch are you using?

x64

### Expected Behavior

VS Code opens and run normally 

### Actual Behavior

VS Code starts opening, asking if it should open recent files, I click yes or no (same behaviour in both cases) and than it crash throwing error referring to electron framework - https://github.com/glebramanchuk/home/blob/main/report. 
Tried to reinstall VS Code, did not work. 
Need help.

**Comment by codebytere** [comment]
Please first report this to VSCode following their issue guidelines. Thanks!
