### ISSUE TITLE
[Bug]: On MacOS, desktopCapturer make window with `resizeable:false` resizeable

### ISSUE THREAD

**Issue by peernohell** [electron/electron#43002]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2.1

### What operating system(s) are you using?

macOS

### Operating System Version

MacOS Sonoma 14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The window should be not resizeable

### Actual Behavior

After 10 second, `desktopCapturer.getSources({ types: ['screen'] })` is called, and the window become resizeable

### Testcase Gist URL

https://gist.github.com/peernohell/301b616884c0ff02a77dda56b59aa8bd

### Additional Information

You can use the Electron Fiddle to reproduce the issue.

**Comment by codebytere** [comment]
@peernohell I ran this repro on macOS Sonoma 14.5 and the window never became resizable. Is there anything I might be missing?

**Comment by peernohell** [comment]
Really strange. You use the 31 version of electron?
I just recorded a video to showcase because I didn't see anything missing.

https://youtu.be/-ou1Tlz5qq0

**Comment by acemtp** [comment]
It never worked on our projects (few month old) but it's only today we understood it was due to desktopCapturer

**Comment by codebytere** [comment]
Tracked to https://github.com/electron/electron/compare/v29.0.1...v29.1.0 - will keep looking

**Comment by codebytere** [comment]
@acemtp @peernohell ok mystery solved, with wild outcome: there's a bug in ScreenCaptureKit that modifies a window's styleMask the first time it captures a non-resizable window.

To fix this, we'll probably need to note each non-resizable window's styleMask and restore it later after the screen capture. We'll probably need to patch this into Chromium, but given it's an Apple bug I can probably get them to accept an upstream CL.

**Comment by acemtp** [comment]
wow, very nasty edge case bug ^^

**Comment by peernohell** [comment]
Hello,

I just tested with latest 33 and it don't work.
You can try with the gist in the first message<

**Comment by acemtp** [comment]
@codebytere hello, it's 3 months old now and it seems that fixed you've done didn't work. any news?
