### ISSUE TITLE
[Bug]: Fullscreen window does not show dropdown list of select element  on macOS 31-x-y

### ISSUE THREAD

**Issue by kounorimich** [electron/electron#43010]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2.1

### What operating system(s) are you using?

macOS

### Operating System Version

Sonoma 14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

30.3.0

### Expected Behavior

When fullscreen mode on macOS, when a `<select>` element within a `BrowserWindow` is clicked, the dropdown list should be displayed properly, just as it does in non-fullscreen mode.

### Actual Behavior

When a `<select>` element is clicked in a fullscreen `BrowserWindow` on macOS, the dropdown list does **not** show.

### Testcase Gist URL

https://gist.github.com/kounorimich/cffc319e21468665512c7da0df555a45

### Additional Information

I have tested the same functionality in version 30.3.0, and it worked well without any issues.
On an Ubuntu PC (Ubuntu 22.04.3 LTS), the functionality also works as expected.

**Comment by codebytere** [comment]
Tracked to https://github.com/electron/electron/commit/e67ab9a93dadccecff30de50ab4555191c30b6c4
