### ISSUE TITLE
Allow setting headers in protocol handler

### ISSUE THREAD

**Issue by skerit** [electron/electron#4303]
Currently the way `protocol.registerHttpProtocol` works, it only allows you to _redirect_ the request to an actual HTTP server.

Ideally, it should provide you with some way to directly respond to the request with headers & body content. And, preferably, allow streaming content.

The other protocol methods (like file, string and buffer) do allow you to create an immediate response, but you can't set the response header.
The only configurable header there is 'Content-Type', which you can set via the 'mimeType' property in the callback.

This would allow my application to run without starting an actual http server.

**Comment by guatedude2** [comment]
i second this. I would also add that same ability to `registerBufferProtocol`

**Comment by cuixiping** [comment]
+1

**Comment by cuixiping** [comment]
Strongly agree.

**Comment by dregenor** [comment]
in my case need attach file if specific header is present.

i can check/modify headers in *webRequest.onBeforeSendHeaders*
but can't attach files (can't modify uploadData).

and i can modify uplaodData in *protocol.interceptHttpProtocol* but can't check headers.

quantum uncertainty :)
or I know the headlines, but can not do anything,
or I can do something, but do not know when.

**Comment by tarruda** [comment]
#11008 implements a more flexible `registerStreamProtocol`/`interceptStreamProtocol` that allows intercepting any browser request (headers passed to the user callback), setting any headers on the response, and streaming content back.

If that PR is accepted/merged, I will later propose reimplementing all the other `{intercept,register}*Protocol` functions on top of it, since it is trivial to obtain streams from files, buffers, strings or http requests.

**Comment by Prinzhorn** [comment]
> If that PR is accepted/merged, I will later propose reimplementing all the other `{intercept,register}*Protocol` functions on top of it, since it is trivial to obtain streams from files, buffers, strings or http requests.

@tarruda Did this ever happen? I was just wondering why the `registerBufferProtocol` is so different from `registerStreamProtocol` and came across this issue. It'd be neat if the APIs would be aligned, e.g. if I could set headers in `registerBufferProtocol`. For now I'll turn my buffers into stream I guess.

**Comment by canvascat** [comment]
for `protocol.registerHttpProtocol`,  it seems to be the only way to use `onBeforeSendHeaders`  to set the headers.
```js
session.defaultSession.webRequest.onBeforeSendHeaders((details, callback) => {
    details.requestHeaders['token'] = 'my-token';
    callback({ requestHeaders: details.requestHeaders });
});
```
