### ISSUE TITLE
[Bug]: Cursor not hiding using css

### ISSUE THREAD

**Issue by AlexKratky** [electron/electron#43049]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.2

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Ubuntu 24.04 (Wayland)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Cursor should be hidden if I use:

```css
* {
  cursor: none;
 }
```

However, this does not work on Ubuntu (using Wayland), only if I move mouse, then it will work. I am opening the app automatically after user login.  

### Actual Behavior

Cursor stays visible until I move cursor atleast by 1px.

**Comment by sachan13harshit** [comment]
@AlexKratky please assign this issue to me

**Comment by AlexKratky** [comment]
@sachan13harshit I don't think I have a permission for that.
