### ISSUE TITLE
[MAS Rejection]: Simple Electron app has been rejected.

### ISSUE THREAD

**Issue by slavikator** [electron/electron#43046]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Electron Version

31.2.1

### Rejection Email

Guideline 2.5.1 - Performance - Software Requirements

Your app uses or references the following non-public or deprecated APIs:

Contents/Frameworks/MyApp Helper (GPU).app/Contents/MacOS/MyApp Helper (GPU)
Symbols:
• _sandbox_apply

Contents/Frameworks/MyApp Helper (Plugin).app/Contents/MacOS/MyApp Helper (Plugin)
Symbols:
• _sandbox_apply

Contents/Frameworks/MyApp Helper (Renderer).app/Contents/MacOS/MyApp Helper (Renderer)
Symbols:
• _sandbox_apply

Contents/Frameworks/MyApp Helper.app/Contents/MacOS/MyApp Helper
Symbols:
• _sandbox_apply

Contents/Frameworks/Squirrel.framework/Versions/A/Resources/ShipIt
Symbols:
• _responsibility_spawnattrs_setdisclaim

The use of non-public or deprecated APIs is not permitted on the App Store, as they can lead to a poor user experience should these APIs change and are otherwise not supported on Apple platforms.

Next Steps

It would be appropriate to revise your binary and remove any references to the non-public or deprecated APIs identified above.

If you are using third-party libraries, update to the most recent version of those libraries. If you do not have access to the libraries' source, the following command line tools can help you identify the location of problematic code:
- The "strings" tool can output a list of the methods the library calls.
- The "otool -ov" tool will output the Objective-C class structures and their defined methods.

### Additional Information

Simple Electron app.

This is the part of my package.json:

  "devDependencies": {
    "@electron/notarize": "^2.3.2",
    "@electron/osx-sign": "^1.3.0",
    "concurrently": "^7.6.0",
    "dotenv": "^10.0.0",
    "electron": "^31.2.1",
    "electron-builder": "^24.13.3",
    "electron-builder-notarize": "^1.5.2",
    "electron-is-dev": "^2.0.0",
    "electron-notarize": "^1.2.2",
    "wait-on": "^6.0.1"
  },
  "dependencies": {
    "electron-main-fetch": "^1.0.0",
    "electron-store": "^10.0.0",
    "set-interval-async": "^2.0.3",
    "simple-plist": "^1.3.1"
  }

**Comment by codebytere** [comment]
hey @slavikator - it looks like you submitted your app using a non-MAS build of Electron. The MAS build doesn't ship with Squirrel. Ensure you're following all steps in our [app store guide](https://github.com/electron/electron/blob/83748bd1817df54c2d2ac1a46d29ca7dceaba9d9/docs/tutorial/mac-app-store-submission-guide.md) and your submission should proceed successfully.

**Comment by slavikator** [comment]
> hey @slavikator - it looks like you submitted your app using a non-MAS build of Electron. The MAS build doesn't ship with Squirrel. Ensure you're following all steps in our [app store guide](https://github.com/electron/electron/blob/83748bd1817df54c2d2ac1a46d29ca7dceaba9d9/docs/tutorial/mac-app-store-submission-guide.md) and your submission should proceed successfully.

I have made an MAS build and submitted it again and it was rejected with the same response.
      
      
By the way, in this [guide](https://github.com/electron/electron/blob/83748bd1817df54c2d2ac1a46d29ca7dceaba9d9/docs/tutorial/mac-app-store-submission-guide.md), isn't clear what the MAS build is.

I set this in my package.json:
"mac": {
      "target": "mas",



Guideline 2.5.1 - Performance - Software Requirements

Your app uses or references the following non-public or deprecated APIs:

Contents/Frameworks/MU Notifier Helper (GPU).app/Contents/MacOS/MU Notifier Helper (GPU)
Symbols:
• _sandbox_apply

Contents/Frameworks/MU Notifier Helper (Plugin).app/Contents/MacOS/MU Notifier Helper (Plugin)
Symbols:
• _sandbox_apply

Contents/Frameworks/MU Notifier Helper (Renderer).app/Contents/MacOS/MU Notifier Helper (Renderer)
Symbols:
• _sandbox_apply

Contents/Frameworks/MU Notifier Helper.app/Contents/MacOS/MU Notifier Helper
Symbols:
• _sandbox_apply

Contents/Frameworks/Squirrel.framework/Versions/A/Resources/ShipIt
Symbols:
• _responsibility_spawnattrs_setdisclaim

The use of non-public or deprecated APIs is not permitted on the App Store, as they can lead to a poor user experience should these APIs change and are otherwise not supported on Apple platforms.
