### ISSUE TITLE
[Bug]: visibility change will not triggered when app is  fully covered by  macos native app like Calendar

### ISSUE THREAD

**Issue by SuperShan0926** [electron/electron#43058]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.5

### What operating system(s) are you using?

macOS

### Operating System Version

mac os 14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

N/A

### Expected Behavior

any window of APP which covered the browser window should trigger visibility to 'hidden'

### Actual Behavior

only electron APP could change visibilityState like VS code， but system app like apple calendar will not trigger 'onVisibilityChange'

**Comment by cucbin** [comment]
@SuperShan0926 could you check the `backgroundThrottling` value?

**Comment by SuperShan0926** [comment]
> backgroundThrottling
i've read the Doc and we never set this property "backgroundThrottling", so it would be default 'true', and when this browser window was fully covered by VS code or other browser window of my app, it always change to 'hide' as expected, but when i use 'Apple Music' or 'Calendar', it will never triggered, that's so wired

**Comment by cucbin** [comment]
@SuperShan0926  Got you, but I can not reproduce it. All windows, also include 'Calendar.app' can make page visibility change.

**Comment by SuperShan0926** [comment]
> @SuperShan0926 Got you, but I can not reproduce it. All windows, also include 'Calendar.app' can make page visibility change.
those app can not stay in fullscreen mode, there is a sample: set a browser window at size 500x500,  and use a native app window at 600 x 600 then move to cover on it, will reproduce, or you can use netEase music app or main window of lark @cucbin

**Comment by SuperShan0926** [comment]
[录屏2024-07-26 21.41.58.zip](https://github.com/user-attachments/files/16392580/2024-07-26.21.41.58.zip)

there is a screen record i can reproduce it @cucbin

**Comment by SuperShan0926** [comment]
i have upload a screen record you can download and see, it's simple enough to reproduce, XD
@cucbin 
[screen record](https://www.filemail.com/d/omixutivxjfeitk)

**Comment by SuperShan0926** [comment]
OMG!!! you could change your calendar view from month to day, then this callback won't triggered, and AppleMusic.app can reproduce


https://github.com/user-attachments/assets/1567af89-ca04-4cf7-9943-1e506696fc19

**Comment by SuperShan0926** [comment]
@cucbin any update for this case bro？ seems special window can reproduce this issue

**Comment by SuperShan0926** [comment]
hi @codebytere, could you please help with this issue? maybe add some event like browserWindow.on('occluded') ? i found you reverted the win.isOccluded() pr, thanks in advance!

**Comment by cucbin** [comment]
I saw your screen record. 
AFAIK, it's not Electron bug, even it could also reproduce in Chrome. But this is still probably not a Chrome's bug.

**Comment by SuperShan0926** [comment]
NP, i think i should use like polygon-clipping to compute the occlusion state by myself, thanks anyway!

**Comment by cucbin** [comment]
I think it would related with the transparent layer in the window that covering it.
Anyway, I guess it should use the NSWindows API, which may ultimately be a system-related problem.
