### ISSUE TITLE
[Bug]: Main app crash when show notification while minimized windows

### ISSUE THREAD

**Issue by cucbin** [electron/electron#43055]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.3.11 and later

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 10.0.22631

### What arch are you using?

x64

### Last Known Working Electron version

no clear

### Expected Behavior

App should not crash.

### Actual Behavior

App crash and exist

### Testcase Gist URL

https://gist.github.com/69c547dce5f0f3a0223b495b908bc27d

### Additional Information

Reproduction Steps:
1. Launch the application.
2. Minimize the application window.
3. Restore the application window from the dock.
4. Press the Windows key + D to show the desktop.

**Comment by cucbin** [comment]
The stack trace:

0 0x7ff7da9bf4f8 [inlined] std::__Cr::__tree::find (__tree:2477)
1 0x7ff7da9bf4f8 std::__Cr::__tree::__erase_unique (__tree:2453)
2 0x7ff7de118cbf [inlined] std::__Cr::__copy_trivial_impl (copy_move_common.h:64)
3 0x7ff7de118cbf [inlined] std::__Cr::__copy_trivial::operator() (copy.h:103)
4 0x7ff7de118cbf [inlined] std::__Cr::__unwrap_and_dispatch (copy_move_common.h:107)
5 0x7ff7de118cbf [inlined] std::__Cr::__dispatch_copy_or_move (copy_move_common.h:158)
6 0x7ff7de118cbf [inlined] std::__Cr::__copy (copy.h:110)
7 0x7ff7de118cbf [inlined] std::__Cr::copy (copy.h:117)
8 0x7ff7de118cbf [inlined] std::__Cr::copy_n (copy_n.h:62)
9 0x7ff7de118cbf [inlined] std::__Cr::char_traits::copy (char_traits.h:259)
10 0x7ff7de118cbf std::__Cr::operator+ (string:4089)
11 0x7ff7da9bf287 [inlined] std::__Cr::set::erase (set:773)
12 0x7ff7da9bf287 electron::NotificationPresenter::RemoveNotification (notification_presenter.cc:30)
13 0x7ff7e3083e69 _tailMerge_winusb.dll
14 0x7ff7daa5f1de electron::WindowsToastNotification::ShowInternal (windows_toast_notification.cc:176)
15 0x7ff7dedb9d96 __crt_stdio_output::output_processor::state_case_type (corecrt_internal_stdio_output.h:2169)
16 0x7ff7de124999 allocator_shim::internal::PartitionMalloc (allocator_shim_default_dispatch_to_partition_alloc.cc:240)
17 0x7ff7e2ddf9ef _tailMerge_winusb.dll
18 0x7ff7dedb9542 __crt_stdio_output::output_processor::process (corecrt_internal_stdio_output.h:1704)
19 0x7ff7de124999 allocator_shim::internal::PartitionMalloc (allocator_shim_default_dispatch_to_partition_alloc.cc:240)
20 0x7ff7e308c607 _tailMerge_winusb.dll
21 0x7ff7de1245d2 [inlined] ShimMalloc (allocator_shim.cc:229)
22 0x7ff7de1245d2 malloc (allocator_shim_override_ucrt_symbols_win.h:73)
23 0x7ff7e308c607 _tailMerge_winusb.dll
24 0x7ff7daa5edbd electron::WindowsToastNotification::Show (windows_toast_notification.cc:129)
25 0x7ff7dad372bc [inlined] SkImageInfo::operator= (SkImageInfo.h:194)
26 0x7ff7dad372bc [inlined] SkPixmap::operator= (SkPixmap.h:40)
27 0x7ff7dad372bc SkBitmap::operator= (SkBitmap.cpp:68)
28 0x7ff7da9bfa47 electron::`anonymous namespace'::OnWebNotificationAllowed (platform_notification_service.cc:41)
29 0x7ff7de74bfdb Builtins_JSEntryTrampoline

**Comment by ckerr** [comment]
I don't understand some of this code, e.g. the `presenter()` check -- every Notification constructor passes the presenter `this` in as the second argument, so how can this ever be `nullptr`?

**Comment by cucbin** [comment]
@ckerr Actually, in fact, the Notification object is `nullptr`, and `RemoveNotification()` will be called twice.
In the second time call to `RemoveNotification()`, Notification object has been `deleted` yet.

So I think this is also the reason why other methods check whether `delegate()` is `nullptr`?
