### ISSUE TITLE
更新electron31.2.1后, mainWindow.unmaximize()没反应[Bug]: 

### ISSUE THREAD

**Issue by KuanyaLiao** [electron/electron#43054]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2.1

### What operating system(s) are you using?

Windows

### Operating System Version

Windows11

### What arch are you using?

x64

### Expected Behavior

  if (mainWindow && !mainWindow.isDestroyed()) {
          console.log('maxsize1');
          if (mainWindow.isMaximized()) {
            console.log('maxsize2');
            try {
              mainWindow.unmaximize()
              console.log('unmaximize');
            } catch (error) {
              console.log('error', error);
            }
          } else {
            console.log('maxsize3');
            mainWindow.maximize()
          }
        }

打印结果maxsize
maxsize1
maxsize2
unmaximize
界面没反应

### Actual Behavior

 if (mainWindow && !mainWindow.isDestroyed()) {
          console.log('maxsize1');
          if (mainWindow.isMaximized()) {
            console.log('maxsize2');
            try {
              mainWindow.unmaximize()
              console.log('unmaximize');
            } catch (error) {
              console.log('error', error);
            }
          } else {
            console.log('maxsize3');
            mainWindow.maximize()
          }
        }

**Comment by kampiu** [comment]
我在macOS下使用 33.2.1 下使用以下代码无法缩小窗口

```javascript
if (win.isMaximized()) {
	win.unmaximize()
} else {
	win.maximize()
}
```
