### ISSUE TITLE
[Bug]: Windows cmd calls the program compiled by Electron, and the log will be displayed in the foreground

### ISSUE THREAD

**Issue by zhimingzhang123** [electron/electron#43057]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.1.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

Windows cmd calls the program compiled by Electron, log will be displayed in the foreground, eg **vscode**
![WX20240726-161415@2x](https://github.com/user-attachments/assets/89c8ed44-4b48-4114-8276-9d99b7832dcf)

and when close cmd window, the software will be close

### Actual Behavior

see picture

### Testcase Gist URL

None

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
