### ISSUE TITLE
[Bug]: Acrylic window removes border radius

### ISSUE THREAD

**Issue by notAperson535** [electron/electron#43075]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.3.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11 23H2 (22631.3958)

### What arch are you using?

x64

### Expected Behavior

The window should have rounded corners, as usual.

### Actual Behavior

When I set the window to `transparent: true` , `titleBarStyle: "hidden",`, and use `mainWindow.setBackgroundMaterial("acrylic");`, the window loses all of its rounded corners.

![image](https://github.com/user-attachments/assets/eaacffa6-d1ff-4097-a261-8ae931acc218)

### Testcase Gist URL

https://gist.github.com/notAperson535/ce3d4a05a678898a031524428ed51388

**Comment by MicroCBer** [comment]
probably u should use only setBackgroundMaterial, and set transparent to false.

**Comment by MicroCBer** [comment]
if u insist on transparent: true for some reason, you can refer to the following code to add the rounded courners back:
https://github.com/MicroCBer/BetterNCM/blob/dcc663f6d9854a3bdaba435790fc3cd3d6180a38/src/App.cpp#L372-L373

**Comment by MicroCBer** [comment]
HWND can be gained by:
```ts
const hwnd = mainWindow.getNativeWindowHandle()["readInt32LE"]()
```

**Comment by notAperson535** [comment]
Thanks, didn't realize that I could use it without `transparent: true`
