### ISSUE TITLE
[Bug]: Arabic font

### ISSUE THREAD

**Issue by RainbowZephyr** [electron/electron#43074]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.0

### What operating system(s) are you using?

Other Linux

### Operating System Version

Archlinux

### What arch are you using?

x64

### Last Known Working Electron version

29.1.0

### Expected Behavior

Arabic font does not render correctly, it should be 
![image](https://github.com/user-attachments/assets/aea2a0e6-6b61-40d2-bb50-53cbf5dedd57)

### Actual Behavior

The letters are not joined and result in hard to read text. The same image as above through an electron app
![image](https://github.com/user-attachments/assets/94862a32-ff62-4865-a91c-3cb3e14e9624)

**Comment by RainbowZephyr** [comment]
No it does not

**Comment by codebytere** [comment]
@RainbowZephyr then unfortunately this is an issue with Chrome - you should file it at https://issues.chromium.org/issues and we will receive the fix when they address it.
