### ISSUE TITLE
[Bug]: gin_helper::MicrotasksScope is instantiated with wrong arguments

### ISSUE THREAD

**Issue by ckerr** [electron/electron#43085]
The constructor for gin_helper::MicrotasksScope is declared this way:

```c++
    explicit MicrotasksScope(v8::Isolate* isolate,
                             v8::MicrotaskQueue* microtask_queue,
                             bool ignore_browser_checkpoint = false,
                             v8::MicrotasksScope::Type scope_type =
                                 v8::MicrotasksScope::kRunMicrotasks);
```

The `scope_type` arg was added in 2eb3bddb05b6efc92e36c22ed55c37021d84276a (#29058).

v8::MicrotasksScope is an `enum`, rather than an `enum class`:

```c++
enum Type { kRunMicrotasks, kDoNotRunMicrotasks };
```

There are many places where we incorrectly instantiate with a v8::MicrotasksScope::Type as the third argument. I was surprised that this compiles; but since `v8::MicrotasksScope::Type` is declared as an `enum` rather than an `enum class`, my guess is that the compiler is implicitly converting `Type` to a `bool`?

Examples:

```sh
shell/common/v8_value_serializer.cc
37:    gin_helper::MicrotasksScope microtasks_scope(
38-        isolate_, isolate_->GetCurrentContext()->GetMicrotaskQueue(),
39-        v8::MicrotasksScope::kDoNotRunMicrotasks);

shell/common/node_bindings.cc
286:    gin_helper::MicrotasksScope microtasks_scope(
287-        isolate, env->context()->GetMicrotaskQueue(),
288-        v8::MicrotasksScope::kDoNotRunMicrotasks);

shell/renderer/api/electron_api_spell_check_client.cc
223:  gin_helper::MicrotasksScope microtasks_scope(
224-      isolate_, context->GetMicrotaskQueue(),
225-      v8::MicrotasksScope::kDoNotRunMicrotasks);

```

So these MicrotasksScopes are being instantiated with both the wrong flag _and_ the wrong type. This raises several questions:

- Is this code actually working?
- If it _is_ working, is it because these instantiations aren't necessary?
- If it _isn't_ working, why didn't we find out sooner? Do we not have tests covering this code?

CC @deepak1556 who didn't introduce this bug, but who probably has the most context on when to use `gin_helper::MicrotasksScope`

Background info on `gin_helper::MicrotasksScope`: #24131

**Comment by deepak1556** [comment]
Oh wow, thanks for noticing this issue! You are right about the implicit conversion https://godbolt.org/z/hjf73GWfv

> Is this code actually working?

I don't think so, both in the browser process and renderer process we are performing the opposite of the callsite intention.

> If it isn't working, why didn't we find out sooner? Do we not have tests covering this code?

We have been lucky I guess, the checks in V8 side affect only scoped microstasks for ex: https://source.chromium.org/chromium/chromium/src/+/main:v8/src/api/api-inl.h;l=205-213. The callsites for most cases will be explicit mode which will just no-op when it cannot run the microtasks. Our tests should be improved to capture these cases.

**Comment by ckerr** [comment]
@deepak1556 I came across this because I was looking at where we instantiate `gin_helper::MicrotasksScope` to try and understand it better. I understand what its implementation is doing, but don't fully understand when to use it & when to not use it. Is there a heuristic you use for saying "ah, we need to add our MicrotasksScope here"?
