### ISSUE TITLE
[Bug]: Weird behavior transparent BrowserWindow

### ISSUE THREAD

**Issue by iuuukhueeee** [electron/electron#43084]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2.1

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Ventura 13.6.7

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Expected no weird drawn frames.

### Actual Behavior

https://github.com/user-attachments/assets/3cabf272-9b90-4db6-94ce-f4ce227f2343

**Comment by nikwen** [comment]
v31.3.0 seems to have some fixes around transparency. Might be worth trying those. (See also #42704.)

**Comment by iuuukhueeee** [comment]
I've upgraded my electron package to 31.3.1. Sadly the bug is still there.

https://github.com/user-attachments/assets/d746796e-fa5b-4c11-a4da-bea3464e1ff0

**Comment by iuuukhueeee** [comment]
Got it fixed by adding backgroundColor to BrowserWindow. Thank you for your help @nikwen.

<img width="248" alt="image" src="https://github.com/user-attachments/assets/5d13d9c3-ede4-4a3a-a485-65d4b320a581">
