### ISSUE TITLE
[Bug]: React devtools become unusable after opening profiler

### ISSUE THREAD

**Issue by nikwen** [electron/electron#43092]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.3.0

### What operating system(s) are you using?

macOS

### Operating System Version

14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

28.3.3

### Expected Behavior

I can use the React devtools profiler as usual.

### Actual Behavior

When opening the profiler tab of the React devtools, the React devtools freeze.

Both the components tab and the profiler tab no longer work. Reloading the page doesn't fix it.

### Testcase Gist URL

https://github.com/nikwen/electron-devtools-bug-repro

#### Reproduction

1. Clone https://github.com/nikwen/electron-devtools-bug-repro
2. `npm start`
3. Reload page using Cmd/Ctrl + R (necessary due to #41613)
4. React devtools appear
5. Click on React Profiler tab
6. Devtools freeze

#### Video showing the issue

https://www.loom.com/share/5c440ed9ed47423ca9ac2374fb51aa0c

**Comment by codebytere** [comment]
Tracked to https://github.com/electron/electron/compare/v31.0.0-nightly.20240412...v31.0.0-alpha.1 - probably a chrome roll

**Comment by codebytere** [comment]
It looks like this isn't specific to React - I can reproduce this with any arbitrary devtools extension containing drag regions on all platforms.

Specifically looks like it was caused by CL:5373340 and our changes to account for it in the above linked Chrome roll commit - not yet sure what our best path forward is though
