### ISSUE TITLE
[Bug]: Improve Handling of Minimum and Maximum Window SizesThe window should not resize below the defined minimum width and height. The window should not resize above the defined maximum width and height.

### ISSUE THREAD

**Issue by VincentLaaa** [electron/electron#43110]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.3.1

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sonoma Version 14.5

### What arch are you using?

x64

### Expected Behavior

The window should not resize below the defined minimum width and height.
The window should not resize above the defined maximum width and height.

### Actual Behavior

The window resizes below the defined minimum width and height, leading to unusable UI.
The window resizes above the defined maximum width and height, potentially causing display issues.

### Additional Information

Steps to Reproduce:

Create a new BrowserWindow instance with specific minimum and maximum size constraints.
Attempt to resize the window below the minimum width or height.
Attempt to resize the window above the maximum width or height.
Example Code:
Here is an example to illustrate the issue:
const { BrowserWindow } = require('electron');

let mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  minWidth: 300,
  minHeight: 200,
  maxWidth: 1200,
  maxHeight: 900
});

// Attempt to resize below minimum size
mainWindow.setSize(100, 100);
console.log(mainWindow.getSize()); // Expected: [300, 200], Actual: [100, 100]

// Attempt to resize above maximum size
mainWindow.setSize(1300, 1000);
console.log(mainWindow.getSize()); // Expected: [1200, 900], Actual: [1300, 1000]

Proposed Solution:

Enforce minimum and maximum size constraints more robustly within the Electron window handling code.
Ensure the window resizing logic adheres strictly to the defined constraints.

**Comment by VincentLaaa** [comment]
Have updated it to be the correct version, previously opened with the wrong version number.

**Comment by dsanders11** [comment]
Hi @VincentLaaa. This is documented behavior (see below), and changing it would be a breaking change. As such I don't think this issue is valid.

> [When setting minimum or maximum window size with `minWidth`/`maxWidth`/
`minHeight`/`maxHeight`, it only constrains the users. It won't prevent you from
passing a size that does not follow size constraints to `setBounds`/`setSize` or
to the constructor of `BrowserWindow`.](https://github.com/electron/electron/blob/1a6563fb66455d3ec68efaeb62c11f3c25187c62/docs/api/structures/base-window-options.md?plain=1#L121-L124)
