### ISSUE TITLE
remove use of NSWindowStyleMaskTexturedBackground

### ISSUE THREAD

**Issue by ckerr** [electron/electron#43125]
This is deprecated in macOS 11, so we should remove it.

- It's [used](https://github.com/electron/electron/blob/87fb2ad70cf778752aadc5496f534b7a0793da61/shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm#L172) for the `styleMask` in `shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm`
- It's [used](https://github.com/electron/electron/blob/87fb2ad70cf778752aadc5496f534b7a0793da61/shell/browser/native_window_mac.mm#L229) in for the `styleMask` in `shell/browser/native_window_mac.mm
-[ `BaseWindowConstructorOptions.type` of `textured`](https://github.com/electron/electron/blame/87fb2ad70cf778752aadc5496f534b7a0793da61/docs/api/structures/base-window-options.md#L143) maps to this value & should be removed
-[ ] I think we'd also remove the [`kStandardWindow` option](https://github.com/electron/electron/blob/87fb2ad70cf778752aadc5496f534b7a0793da61/shell/browser/native_window_mac.mm#L204) which (a) has a comment saying we should deprecate it, and (b) seems to be unused + undocumented, and (c) is related to opting-out of a textured background that we won't be able to use anymore

**Comment by code-small-white** [comment]
The frame window will send a notification.
> DeprecationWarning: The 'textured' window type is deprecated and will be removed

```js
BrowserWindow({
    frame: false
})

```
