### ISSUE TITLE
Allow opening dev tools only for a specific iframe

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#4315]
In `nwjs` there is a specific option to open the dev tools and [lock it to a specific iframe](https://github.com/nwjs/nw.js/blob/nw13/docs/References/Window.md#winshowdevtoolsiframe-headless-callback).

This enables you to trap the dev tools to a specific iframe.

This was super useful in `nwjs` and would be just as useful in Electron.

**Comment by baconface** [comment]
I needed this feature to port my editor from NW.js to Electron. With a little creativity I found the same can be done in Electron using the remote debugging port.

Enable it in your main.js:
```javascript
app.commandLine.appendSwitch('remote-debugging-port', '9222');
```
Retrieve the instance from the /json reponse. For me it is usually always the first instance. If not change the integer in ```json[0].id;``` until it gets your frame or webview.
```javascript
var devtools = '127.0.0.1:9222'
var devurl = 'http://' + devtools + '/devtools/inspector.html?ws=' + devtools + '/devtools/page/';
$.getJSON('http://' + devtools + '/json', function(json) {
  devurl = devurl + json[0].id;
  console.log(devurl);
});
```

```devurl``` is the URL for the devtools jailed to your iframe. Either open it in a new window or create another iframe/webview and open it in there.

**Comment by baconface** [comment]
Here is a screenshot showing the effect in action:
![Editor Screenshot](https://scontent-dfw1-1.xx.fbcdn.net/hphotos-xlp1/t31.0-8/12370762_1952050801687229_2095977490271131782_o.jpg)

**Comment by brian-mann** [comment]
This only allows you to debug independent windows. In my case I have a window and within that a child `<iframe>`. I only want to debug the `<iframe>` not the whole window.

The `/json` endpoint does not expose any specific iframes to connect to. I peeked at the source of `nwjs` and it looks like they might have modified chromium to make this feature possible.

**Comment by baconface** [comment]
Well, I know for a fact this works for webviews. The result panel you see in the screenshot is a webview child element and not a window. And the method I posted will give you the desired effect. So if it is possible to switch your iframe to a webview then you have a possible solution. If not then you will have to wait for a PR to be submitted that allows this.

Incidentally I came up with this work around when I was still using NW.js and switched my iframe to a webview to fix issues with using an iframe. But the webview was incompatible with their jail dev tools feature. I made the switch to Electron once I discovered this because the only missing feature holding me back was jailing the dev tools. Haha.

**Comment by zcbenz** [comment]
nw.js did this by adding a big patch to Chromium, generally I'm strongly opposed to adding patch to Chromium unless it is very necessary.

**Comment by nbering** [comment]
@baconface Wow. I happened to be browsing the issues and came across this. I was looking for a way to host the DevTools of multiple windows in a single other window (maybe in tabs, or just as a split panel). If this works, your work-around might just do the trick for me. Is there somewhere I can find more documentation on the remote debugging protocol this uses?

**Comment by baconface** [comment]
You mean like the [docs](https://developer.chrome.com/devtools/docs/debugger-protocol)? And you should be able to do what you are wanting to do with this method just fine.

**Comment by nbering** [comment]
Thanks! Not sure how I didn't find that on my own. I'll go crawl under my rock now.

**Comment by zcbenz** [comment]
I'm closing this as won't fix since Chromium doesn't provide such ability. It is possible to achieve this by patching Chromium heavily, but I don't think we should do that.

**Comment by guox191** [comment]
watch

**Comment by baconbrad** [comment]
@guox191 There will be no update. It won't be patched.
