### ISSUE TITLE
[Feature Request]: Support all chrome://* pages

### ISSUE THREAD

**Issue by code-small-white** [electron/electron#43163]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Support all chrome://* pages

### Proposed Solution

Support all chrome://* pages

### Alternatives Considered

Support all chrome://* pages

**Comment by codebytere** [comment]
@code-small-white Given they change upstream all the time and aren't part of our externally exposed API surface, we aren't going to commit to supporting `chrome://` pages now or in the forseeable future. If there are specific pages you need or would like to see supported, it's possible to discuss that provided supporting them does not incur much maintenance burden.
