### ISSUE TITLE
[Bug]: Subprocess crash when rendering in iframe (regression in v31)

### ISSUE THREAD

**Issue by Shiyukine** [electron/electron#43197]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.3.1

### What operating system(s) are you using?

Windows, Other (specify below)

### Operating System Version

Windows 10 22H2, Garuda Linux "Bird of Prey"

### What arch are you using?

x64

### Last Known Working Electron version

30.3.1

### Expected Behavior

The goal is to render several webpages in iframes by modifying their headers like "x-frame-options".

### Actual Behavior

In 31.0.0-alpha.1 up to 32.x-beta.x, a subprocess crash when rendering in iframe. 
After a short time, the iframe turns gray, and the iframe stops responding:  in DevTools, I can no longer view the HTML, CSS and I can no longer send JS commands to the iframe.

### Testcase Gist URL

https://gist.github.com/4e56e4ae77dc8935048a197783ccf5fb

### Additional Information

However, the subprocess won't crash when the iframe has `style.display = "none"`, or if a certain element in the iframe has `style.display = "none"`, but I won't see the page.

This only affects Electron. This works on Chrome and Brave 125.x and more.

**Comment by codebytere** [comment]
hey @Shiyukine - i just fixed this in https://github.com/electron/electron/pull/43179!
