### ISSUE TITLE
select options rendered as a black blox when page has a media element [Linux electron v0.36.7]

### ISSUE THREAD

**Issue by loddit** [electron/electron#4322]
If a media element (e.g. `<audio>` or `<video>`) added in page, or `new Audio('some audo file')` statement in sciprt, options of select tag become a black box.

page has a `<audio>` tag:
![image](https://cloud.githubusercontent.com/assets/394562/12745295/84270660-c9d3-11e5-9e58-7d0165375e62.png)

page without  `<audio>` tag:
![image](https://cloud.githubusercontent.com/assets/394562/12745389/f12ef9fc-c9d3-11e5-852c-1110c432b12a.png)

page source:

```
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <select>
      <option>Option 1</option>
      <option>Option 2</option>
      <option>Option 3</option>
      <option>Option 4</option>
    </select>
    <audio src="some audio file"></audio>
  </body>
</html>
```

**Comment by OlsonDev** [comment]
This happens to me in Chrome, too. It didn't do it till I changed

```
Enable GPU rasterization. Mac, Windows, Linux, Chrome OS, Android
Use GPU to rasterize web content. Requires impl-side painting. #enable-gpu-rasterization
```

to `Force enabled for all layers`. No idea if related...

**Comment by bengotow** [comment]
This has been reported several times in N1 (https://github.com/nylas/N1/issues/1163, https://github.com/nylas/N1/issues/1567). We do use the `<audio>` tag to play a few "incoming email" sounds, so that fits the description above. Would love if it were possible to fix.

**Comment by vojtatranta** [comment]
We've got some issues in Avocode with Ubuntu further reading: https://github.com/avocode/avocode/issues/1158#event-901296659

**Comment by timfish** [comment]
Platform: Windows 10 
Version: 1.4.14

This has started happening the first time I open any dropdown after starting my app and I'm not using any `<audio>` tags. I'm not sure what change started the behaviour.

**Comment by codebytere** [comment]
closing due to abandonment.
