### ISSUE TITLE
[Bug]: When calling BrowserWindow.webContents.reload or BrowserWindow.loadURL, the execution order of the Chrome extension is incorrect.

### ISSUE THREAD

**Issue by huangnana520** [electron/electron#43221]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.3.3

### What operating system(s) are you using?

Windows

### Operating System Version

window10

### What arch are you using?

x64

### Expected Behavior

chrome extension manifest
`{"content_scripts":[{"run_at":"document_start","matches":["<all_urls>"],"js":["content.js"],"all_frames":true}]}`

HTML
`<html lang="zh-CN" style="font-size: 100%; --saturation-factor: 1; --devtools-sidebar-width: 0px;" class="reduce-motion show-redesigned-icons has-webkit-scrollbar theme-dark images-dark platform-web font-size-16" data-rh="lang,style,class">
  <script src="chrome-extension://jcmaajlodmiihcimfpdmoacbnchchiif/dist/Vencord.js" id="vencord-script" data-extension-base-url="chrome-extension://jcmaajlodmiihcimfpdmoacbnchchiif/" data-version="1.9.5"></script>
  <head>
    <meta content="width=device-width,initial-scale=1,maximum-scale=3" name="viewport">
    <title>xx</title>
  </head>
  <body>
    <div id="app-root"></div>
    <script src="/assets/web.7dd92f74c71ef3eed57a.js" defer=""></script><script src="/assets/sentry.2e0499c86d1c7e90d3e4.js" defer=""></script>
  </body>
</html>`

app index.js
`
app.whenReady().then(async () => {
   const mainWin = new BrowserWindow(/**/)

  // loadExtension
  const path_ = path.join(__dirname, '..', 'VencordExtension');
  await session.defaultSession.loadExtension(path_);
})
`

The expectation is that the Chrome extension's execution timing, configured as document_start in the manifest, should precede other JS scripts in the HTML.

### Actual Behavior

When the application loads for the first time, the Chrome extension always executes according to the timing defined in the manifest, preceding other JS scripts in the HTML. However, after calling BrowserWindow.webContents.reload or BrowserWindow.loadURL, the extension's execution timing is always behind that of the other JS scripts in the HTML.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
