### ISSUE TITLE
[Bug]: Uncaught (in promise) DOMException: Failed to execute 'getMappedRange' on 'GPUBuffer': getMappedRange failed     at WebGPUBackend.uploadToGPU 

### ISSUE THREAD

**Issue by sakura-xiamu** [electron/electron#43236]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system(s) are you using?

Windows

### Operating System Version

win11 23H2

### What arch are you using?

x64

### Expected Behavior

my chrome running no error 
but my local electron develop running error

please help me !

app.commandLine.appendSwitch('enable-experimental-web-platform-features', 'enable')
app.commandLine.appendSwitch('ignore-gpu-blocklist')
app.commandLine.appendSwitch('enable-gpu-rasterization')
app.commandLine.appendSwitch('enable-gpu')
app.commandLine.appendSwitch('enable-unsafe-webgpu')
app.commandLine.appendSwitch('enable-features', 'WebRTCPipeWireCapturer,Vulkan,UseSkiaRenderer,VaapiVideoDecoder,CanvasOopRasterization,VaapiVideoEncoder,RawDraw,SharedArrayBuffer')
app.commandLine.appendSwitch('disable-features', 'UseSkiaRenderer,UseChromeOSDirectVideoDecoder')
app.commandLine.appendSwitch('enable-zero-copy')
app.commandLine.appendSwitch('enable-oop-rasterization')
app.commandLine.appendSwitch('enable-native-gpu-memory-buffers')
app.commandLine.appendSwitch('enable-vulkan')
app.commandLine.appendSwitch('in-process-gpu', 'enable')
app.commandLine.appendSwitch('enable-webgl-draft-extensions')
app.commandLine.appendSwitch('enable-webgl')

![image](https://github.com/user-attachments/assets/d0ae601f-57e3-4e08-9834-15847cd03afe)

![image](https://github.com/user-attachments/assets/b32c49ed-3825-4a95-907b-440aa93b39d0)

### Actual Behavior

Uncaught (in promise) DOMException: Failed to execute 'getMappedRange' on 'GPUBuffer': getMappedRange failed
    at WebGPUBackend.uploadToGPU

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
