### ISSUE TITLE
some important response headers are not included in response.headers when using fetch API.

### ISSUE THREAD

**Issue by mehdishojaei** [electron/electron#4326]
When using Fetch API in Electron (), some important response headers are not included in `response.headers`. Headers like `Content-Length` are not exist.

```javascript
fetch('http://electron.atom.io/images/electron-logo.svg').then(function(response) {
  console.log([...response.headers]);
}

// output only contains "last-modified", "content-type", "expires" and "cache-control"!
```

While we can see headers like `Content-Length` in the network panel.

**Comment by 1999** [comment]
@mehdishojaei why did you close this issue? Did you find the solution?

**Comment by mehdishojaei** [comment]
@1999 No. Actually I closed this issue mistakenly.

**Comment by deepak1556** [comment]
You are making a cors request whose response headers doesn't contain `Access-Control-Expose-Headers` as per the [spec](https://fetch.spec.whatwg.org/#concept-filtered-response), which results in the expected output.
