### ISSUE TITLE
[Bug]: Can't use GPU Hardware accelerated on arm64 linux platform

### ISSUE THREAD

**Issue by wanyingwe** [electron/electron#43277]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.3.1

### What operating system(s) are you using?

Ubuntu

### Operating System Version

5.10.160-rt89+

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

none

### Expected Behavior

I used some threejs 3D effects in my program and GPU hardware acceleration is required
My hardware platform uses the RK3568 chip, which only supports opengl-es.

### Actual Behavior

GPU hardware acceleration does't work, GPU load almost 0%.

I really don't know where the problem is

#### The commands are these
    'ignore-gpu-blocklist',
    'enable-gpu-rasterization',
    'enable-zero-copy',
    'enable-webgl',
    'enable-accelerated-2d-canvas',
    'disable-software-rasterizer',
    'enable-oop-rasterization',
    'enable-drdc'
#### chrome://gpu information seems OK

    Graphics Feature Status
    =======================
    *   Canvas: Hardware accelerated
    *   Canvas out-of-process rasterization: Enabled
    *   Direct Rendering Display Compositor: Disabled
    *   Compositing: Hardware accelerated
    *   Multiple Raster Threads: Enabled
    *   OpenGL: Enabled
    *   Rasterization: Hardware accelerated on all pages
    *   Raw Draw: Disabled
    *   Skia Graphite: Disabled
    *   Video Decode: Hardware accelerated
    *   Video Encode: Software only. Hardware acceleration disabled
    *   Vulkan: Disabled
    *   WebGL: Hardware accelerated
    *   WebGL2: Hardware accelerated
    *   WebGPU: Disabled
    *   WebNN: Disabled

#### But Chromium GPU info shows disable
    Chromium GPU info: {
      "auxAttributes": {
        "amdSwitchable": false,
        "canSupportThreadedTextureMailbox": false,
        "glImplementationParts": "(gl=none,angle=none)",
        "glResetNotificationStrategy": 0,
        "inProcessGpu": true,
        "initializationTime": 0,
        "isAsan": false,
        "isClangCoverage": false,
        "jpegDecodeAcceleratorSupported": false,
        "optimus": false,
        "passthroughCmdDecoder": false,
        "sandboxed": false,
        "subpixelFontRendering": true,
        "targetCpuBits": 64,
        "visibilityCallbackCallCount": 0
      },
      "gpuDevice": [
        {
          "active": false,
          "cudaComputeCapabilityMajor": 0,
          "deviceId": 0,
          "gpuPreference": 0,
          "vendorId": 0
        }
      ]
    }

In addition, my Chrome browser can use GPU acceleration for 3D rendering normally, and I can use glmark2-es2 to test it

**Comment by wanyingwe** [comment]
I now realize that this problem may be a problem with the chromium kernel, which does not support GPU hardware acceleration well.

**Comment by wanyingwe** [comment]
I now realize that this problem may be a problem with the chromium kernel, which does not support GPU hardware acceleration well.

**Comment by pedroveiga99** [comment]
@wanyingwe do you have any reference to the issue of that problem? Is it solved?

**Comment by 07ke** [comment]
> [@wanyingwe](https://github.com/wanyingwe) do you have any reference to the issue of that problem? Is it solved?

+1
