### ISSUE TITLE
[Bug]: Dialog TS type doesn't accept `BaseWindow`

### ISSUE THREAD

**Issue by kevinlinv** [electron/electron#43292]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.1.0

### What operating system(s) are you using?

macOS

### Operating System Version

Sonoma 14.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

N/A

### Expected Behavior

The typing allows using `BaseWindow` to display a modal-based message boxes or file-saving dialogs.

### Actual Behavior

The type only accepts `BrowserWindow`.

### Testcase Gist URL

https://gist.github.com/ff2ba9201ffe5de109b824bc21b9fe80

### Additional Information

I've attached the gist showing cases we can use `BaseWindow`, but I am unsure whether that's 100% safe on all use cases. 

I've also tested the gist both on macOS and Windows.

**Comment by codebytere** [comment]
hey @kevinlinv - it should be fine to use! See https://github.com/electron/electron/pull/42315 - we can consider documenting this to reflect the accepted types but in the meantime it is safe :)

**Comment by kevinlinv** [comment]
Oh, nice. Thank you for checking 👍

**Comment by kevinlinv** [comment]
Thank you for updating the docs @codebytere 🙏
