### ISSUE TITLE
[Bug]: Dev-Tools Cannot Copy Paste 

### ISSUE THREAD

**Issue by Bug-Reaper** [electron/electron#43291]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^29.4.5

### What operating system(s) are you using?

macOS

### Operating System Version

MacOS Ventura 13.5

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

^29.4.5

### Expected Behavior

Be able to copy/paste/select-all within dev-tools via shortcut keys `⌘+C`/`⌘+V`/`⌘+A` etc...

### Actual Behavior

Cannot copy or paste text in the dev-tools. Ironically, I've been on version `^29.4.5` since close to release and never had this issue until like a week ago.

### Additional Information

- I am not prompted in the console to "allow pasting" and changing the settings for such experiment has no effect.
- Chrome canary dev-tools allow me to copy/paste/select-all as normal.

**Comment by Bug-Reaper** [comment]
Figured it out, has to do with my custom native-menu. It would appear if your app does not have the default accelerators for copy/paste/select-all that this also removes the ability to use copy/paste accelerators inside dev-tools? Seems odd?

```
// Where menu doesn't have copy/paste accelerators
const menu = Menu.buildFromTemplate(template)
Menu.setApplicationMenu(menu)
```

**Comment by Bug-Reaper** [comment]
Wanna hear thoughts from the maintainers (or other users). My intuition is that the native-menu configuration for your application should not affect the hotkeys that work for the dev-tools/web-inspector?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by Bug-Reaper** [comment]
@codebytere this wasn't a question.

 It's completely undocumented that changing the native-menu options for your electron-app would restrict accelerators that work within web-inspector-dev-tools. Should be fixed *or* documented IMO.

**Comment by linonetwo** [comment]
If you have search ability: #40995
