### ISSUE TITLE
[Bug]: desktopCapturer When the desktop capturer captured a 4K desktop, it was only 1920

### ISSUE THREAD

**Issue by lei006** [electron/electron#43307]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.3.1

### What operating system(s) are you using?

macOS

### Operating System Version

mac any

### What arch are you using?

x64

### Expected Behavior

1. Desktop Resolution 1920X1080, Launcher. 
2. The resolution is adjusted to 4K 
3. the captured desktop is 4K.

### Actual Behavior

1. Desktop Resolution 1920X1080, Launcher. 
2. The resolution is adjusted to 4K 
3. the captured desktop is 1920x1080.

**Comment by lei006** [comment]
I hope to change the resolution of the captured desktop without restarting the app on MAC：

https://gist.github.com/lei006/aa6cf818c30063043eeb2d638f12a9d2

**Comment by brhenrique** [comment]
yeah I think this is a bug in Chromium, not Electron:

https://issues.chromium.org/issues/40823488
https://issues.chromium.org/issues/40822920
