### ISSUE TITLE
Update Twitter branding to X

### ISSUE THREAD

**Issue by Harshinireddy05** [electron/electron#43322]
### Description:
The website currently references Twitter in the footer navigation links . Given Twitter's recent re-branding to "X", we need to update the footer to reflect this change.

### Steps to Reproduce:
Navigate to the website's footer.
Observe the list of links which includes "Twitter".
### Expected Behavior:
The link text should be updated from "Twitter" to "X".

**Comment by codebytere** [comment]
This is not an issue with Electron core. Please open this issue on the website repo.

**Comment by Harshinireddy05** [comment]
@codebytere Okay sure! Thank you for the guidance.
