### ISSUE TITLE
[Bug]: alert() not working

### ISSUE THREAD

**Issue by borsotti** [electron/electron#43352]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Fiddle 0.36.4

### What operating system(s) are you using?

Windows

### Operating System Version

Windowd 10 Pro 22H2

### What arch are you using?

x64

### Expected Behavior

I have just dowloaded Fiddle, che added:
<button type="button" onclick="alert('Hello world!')">Click Me!</button>
after Hello world, and run it.

### Actual Behavior

The button is displayed, but when I click on it, no alert is shown.

### Testcase Gist URL

https://gist.github.com/borsotti/a6c89391a9b3e02d425c593b0f727ddd

**Comment by codebytere** [comment]
@borsotti this is expected for the content security policy in place:

```
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'">
```

the error states this:

```
[25411:0819/173704.356056:INFO:CONSOLE(15)] "Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

**Comment by borsotti** [comment]
Hi,

Since the app is a desktop one, I guess that it should not have the
restrictions of
web pages. Thus, I removed the Content security policy, but the result is
the same:
the alert is not shown.
I tried also to find the error report, but could not find it.

.-Angelo
