### ISSUE TITLE
App not getting focus on `open-url` events initiated from Chrome [OSX El Capitan] (Atom repro)

### ISSUE THREAD

**Issue by TGOlson** [electron/electron#4338]
I'm running an app using the newest version of Electron, and I want to handle `open-url` events by giving focus to the `mainWindow` of my application.

The code looks something like this:

``` js
app.on('open-url', function(e, url) {
  e.preventDefault();

  mainWindow.webContents.send('custom-open-url', url);

  if (mainWindow.isMinimized()) {
    mainWindow.restore();
  } else {
    mainWindow.focus();
  }
});
```

The problem I've found is that when Chrome initiates an `open-url` event on OSX El Capitan, my Electron app flashes to the foreground for a moment, but then hides while Chrome keeps focus. 

Note: this problem only occurs when opening the custom protocol from Chrome and the app is already running - opening the protocol from Firefox or running `open my-protocol:foo:bar` from the command line works & gives focus correctly. OSX Yosemite works correctly, as well.

This issue can also be reproduced using the newest version of Atom on OSX El Capitan. Steps to repro:
- Open Atom
- Hit `atom://foo` from Chrome
- Observe Atom flash to foreground, but Chrome keeps control

Note: you can observe correct behavior by running `open atom://foo` from the command line w/ Atom already open. This correctly gives focus to Atom.

**Comment by zcbenz** [comment]
I can not reproduce with Atom on my machine, which is also EI Capitan. Can you try with other apps that support custom protocol? Like Dash.

**Comment by jweinstein** [comment]
Works properly in Dash (is that using Electron?). We can reproduce the issue using the above steps. Do you have Atom already open during the test?

**Comment by jweinstein** [comment]
Confirmed Dash isn't using Electron. Happy to screen share through the problem if helpful!

**Comment by TGOlson** [comment]
@zcbenz thanks for the response. I created a [minimal repro case with electron](https://github.com/TGOlson/chrome-protocol-repro) that might be helpful for you to check out and see if you can observe the issue. One caveat is that the bug appears much less often in the minimal repro case  (maybe 20% to 25%) compared to full electron app (over 75%).

**Comment by zcbenz** [comment]
I can reproduce with Atom when there is an editor window opened, but after I click the "remember my choice" box in Chrome, this problem is gone in following testings.

I think it is probably a bug os x, so when there is a dialog showing while opening URL with another app, the window would lose focus.

**Comment by TGOlson** [comment]
@zcbenz - exactly. The application has to already be open, and you have to **not** have checked the "remember my choice" option.

I think you are correct about this being some sort of OSX bug, although I'm not able to recreate on Firefox, even though that browser has a popup notice as well.

Does it seem like there is anything that electron can do to avoid this issue? I'm going to add this to the chrome bug tracker as well and see what they say.

**Comment by zcbenz** [comment]
You can probably call `focus` with `setTimeout` to work around this, I don't know other solutions.

**Comment by feross** [comment]
I can confirm this issue.

I dug a bit deeper and concluded that this actually may not be an OS X bug. Other applications that register handlers don't exhibit the same issue.

For example, [Transmission.app](https://www.transmissionbt.com/) can open magnet links from Chrome and take focus. When I try with my app ([webtorrent-app](https://github.com/feross/webtorrent-app)), Chrome keeps focus.

**Comment by feross** [comment]
This workaround seems to do the trick in the meantime.

```js
setTimeout(function () {
  if (windows.main.isMinimized()) {
    windows.main.restore()
  }
  windows.main.show()
}, 100)
```

**Comment by codebytere** [comment]
As this has not been active for a while and there is a workaround, i'm going to go ahead and close this.

**Comment by jasonjmcghee** [comment]
Not a big fan of the flashing behavior from the above workaround.
I had better luck forcing it to be on top so chrome can't take back focus in the time window.
```
... open-url ...
mainWindow.setAlwaysOnTop(true);
setTimeout(() => {
    if (mainWindow.isMinimized()) {
        mainWindow.restore()
    }
    mainWindow.setAlwaysOnTop(false)
}, 100);
```
