### ISSUE TITLE
[Bug]: Issue template has expired discord invite link

### ISSUE THREAD

**Issue by cgarrovillo** [electron/electron#43446]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

Sonoma

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Discord link works

### Actual Behavior

Discord link doesnt work

**Comment by ckerr** [comment]
The link in the issue template, https://discord.gg/APGC3k5yaH, seems to be working for me. Maybe it was a temporary outage or something? @cgarrovillo can you try again and report back whether it's still broken for you?
