### ISSUE TITLE
[Feature Request]: Add native print api

### ISSUE THREAD

**Issue by steinmetz85** [electron/electron#43450]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There is no native print api in electron. There is a library (node-printer), which does the job. But this library isn't maintained anymore.
The print functionality under webcontent only supports files, changes the layout of data and needs a window to print

### Proposed Solution

Implement a native print api in electron:
- Reading the local printers
- Print data (array buffer) to a special printer

### Alternatives Considered

- webcontent - print
- https://www.npmjs.com/package/@thiagoelg/node-printer

**Comment by codebytere** [comment]
While we understand the desire for this API, given you can print from a hidden window as well as craft a native module to accomplish the same end, I'm closing this as something that won't be added in the near future nor something we'd be likely to accept in core if a PR was opened externally.

This would essentially require duplicating dozens of files and logic that exists Chromium and isn't maintenance burden the project is prepared to take on.
