### ISSUE TITLE
[Bug]: safeStorage.isEncryptionAvailable doesn't work

### ISSUE THREAD

**Issue by aureliumsk** [electron/electron#43479]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.1

### What operating system(s) are you using?

Other Linux

### Operating System Version

Linux Mint 22 x86_64

### What arch are you using?

x64

### Expected Behavior

`safeStorage.isEncryptionAvailable()` should return either a false, or true, and it should be passed to `console.log()`.
*(simple, isn't it?)*

### Actual Behavior

`safeStorage.isEncryptionAvailable()` just blocks the entire application in an infinite computation.

### Testcase Gist URL

https://gist.github.com/JustLoveC1de/4f5dd695622d893d01468dbad2250a24

**Comment by JustLoveC1de** [comment]
[aha, I totally looked for issues like that and there is totally no way someone reported this already. absolutely, there is no way this is possible.](https://github.com/electron/electron/issues/32206)

**Comment by JustLoveC1de** [comment]
[despite this being already reported here](https://github.com/electron/electron/issues/32206), and fix being implemented, this is still, for some reason, an issue.

**Comment by ckerr** [comment]
I'm not able to repro this with the gist on Ubuntu 24.04 x64. Running the gist both with 32.0.1 and with `main` gives:

```txt
Encryption is available: true
```

@JustLoveC1de any ideas on what specifically is needed to repro this? e.g.  whether this is specific to Linux Mint 22, or ...?
