### ISSUE TITLE
Improve showItemInFolder by bringing the explorer to front

### ISSUE THREAD

**Issue by flexpaper** [electron/electron#4349]
OSX brings the finder to front when showItemInFolder is called, whereas Windows does not bring explorer to front. Would it be possible to improve this function so it does the same on Windows?

**Comment by bpasero** [comment]
I am also seeing this and think this used to work before?

**Comment by quicksnap** [comment]
As referenced in #4464, the same behavior is present with shell.openItem on Windows.

**Comment by kevinsawicki** [comment]
@paulcbetts think this could be related to #4092 ?

**Comment by paulcbetts** [comment]
@kevinsawicki It could be but these changes should only have effect if we were in previous circumstances going to completely fail

**Comment by catalin-testenv** [comment]
+1 Please fix this. Thank you !

**Comment by markbrocato** [comment]
+1 Yes please

**Comment by popod** [comment]
`shell.openItem()` open file in background (behind the app) but I want that the opened file get in front..
Any solution ?

**Comment by bpasero** [comment]
What seems to work for me is to run `shell.showItemInFolder` from the main process and not the render process. I believe this is the same underlying issue we have seen in other cases: the renderer process wants another process to come to foreground but Windows treats it as background process and thus prevents it from opening another application to the foreground. The main (browser) process seems to be able to do this though.

**Comment by flexpaper** [comment]
Thanks for the tip @bpasero !

**Comment by quicksnap** [comment]
@bpasero Thanks for this! We'll test it soon but it sounds like a good workaround!

**Comment by flexpaper** [comment]
We have verified that this works in both OSX and Win64/Win32. Thanks again!

**Comment by bpasero** [comment]
Btw there are more methods in `shell` where this applies. In VS Code we have now moved the following calls to main process side on all OS:
* `shell.showItemInFolder`
* `shell.openExternal(url[, options])`
* we do not use it, but probably also apply: `shell.openItem(fullPath)`

This should probably be documented.

**Comment by quicksnap** [comment]
Over the past months I've been working with chromium code.. perhaps we can modify how this call works to defer it outside the browser process behind the scene.

**Comment by JeroenSormani** [comment]
For me the following happens on Mac, both the renderer and main process seem to have the same behaviour:
`showItemInFolder(path)`: open on front 
`openItem(path)`: opens in back

What I'm running into is that I'd like to open it into the front, but `showItemInFolder()` shows the folder in the path it is in, while I'd like to be inside folder (one level down)

**Comment by hexaguin** [comment]
Still seeing this issue as of 5.0.6 on Windows 10. Renderers open Explorer in the background, main opens it in the foreground. Calling `remote.shell.openItem(path)` fixes the issue and consistently opens in the foreground.

Perhaps, as @quicksnap mentioned, this call could be made by the main process on Windows? I'm not super familiar with Electron's low-level workings, but I would think it could even be as simple as wrapping calls to `remote.shell` in `shell` on Windows (at least until a better solution is found). The API would stay the same, and this bug *should* be fixed.

**Comment by Maus3rSR** [comment]
Same issue for Electron v8+, @hexaguin answer worked for me too

**Comment by cdetamble** [comment]
What fixed it for me was to call

```window.require('electron').remote.shell.showItemInFolder(path);```

instead of

`window.require('electron').shell.showItemInFolder(path);`

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by sunjw** [comment]
> What fixed it for me was to call
> 
> `window.require('electron').remote.shell.showItemInFolder(path);`
> 
> instead of
> 
> `window.require('electron').shell.showItemInFolder(path);`

`remote.shell` works like a charm.

**Comment by jsyanyang** [comment]
how to use the "remote" module in electron 19? this issue still happen to me
