### ISSUE TITLE
[Feature Request]: Improve Performances

### ISSUE THREAD

**Issue by foxypiratecove37350** [electron/electron#43509]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Because Electron use Chromium, it's very performances consuming, it's literally it's own web browser. Yes, I know, it will be complicated to change that but I think we all agree that having a lot of Chromium (that isn't the lightest web browser) processes isn't really performances efficient.

### Proposed Solution

Find another renderer. Gecko can be good but don't have all features of Chromium's Blink, WebKit can be good as it was the base for Chromium's Blink, but there's a ton of other possible renderers.

### Alternatives Considered

At last resort, create a new one. But really at last resort because it will be complex and will need to be maintained, ...

**Comment by felixrieseberg** [comment]
Citation needed: For complex web applications, Chromium continuously beats other available renderers. Electron will not in the foreseeable future switch from V8 to another JS runtime. Chromium is currently the best embeddable rendering engine on top of V8.

**Comment by foxypiratecove37350** [comment]
@felixrieseberg IE has better performances *but* less features, end of support and is closed source and proprietary. I started working on a web renderer, but yes using Chromium is currently probably one of the best options.
