### ISSUE TITLE
[Bug]: The application on electron crashes when I try to implement ASAR Integrity check on windows

### ISSUE THREAD

**Issue by ibragimovbr** [electron/electron#43514]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.3.1

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 10 Enterprise 19045.4529

### What arch are you using?

x64

### Expected Behavior

when changing the app.asar file and when trying to open the application via exe 
the application should crash and not open

### Actual Behavior

when changing the app.asar file and when trying to open the application via exe 
The application does not open at all

### Additional Information

I set up everything according to this documentation
https://www.electronjs.org/ru/docs/latest/tutorial/asar-integrity
Added flags using the library "@electron/fuses": "~1.6.2",
Added flags in this way:
    await flipFuses(appPath, {
        version: FuseVersion.V1,
        [FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true,
        [FuseV1Options.OnlyLoadAppFromAsar]: true
    });

I also use "electron-builder": "~25.0.1"
They added the necessary file generation for asar integrity check in version 25
https://github.com/electron-userland/electron-builder/releases/tag/v25.0.0

And in this release they added the necessary feature
https://github.com/electron-userland/electron-builder/pull/8245

At the same time, I saw how people set this EnableEmbeddedAsarIntegrityValidation: false flag, the windows application starts to open, but checking for the hash amount does not work

So what am I doing wrong?
Or electron does not know how to check the hash amount yet

**Comment by mlaurencin** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by ibragimovbr** [comment]
so what if it's not a bug?

**Comment by ibragimovbr** [comment]
can you please duplicate the link to the channel in discord 
I didn't have time to go in and it expired

**Comment by mlaurencin** [comment]
If you are unsure if your implementation was done correctly or not, then it will be difficult to verify whether the crash is due to a bug or improper implementation. Asking on Discord will allow you to confirm your implementation and if the crashing still persists, you can create a new issue with the verified information. 

This invite link should work instead: https://discord.gg/electronjs

**Comment by ibragimovbr** [comment]
I'm sorry, but I can't accept the invitation from your link.
