### ISSUE TITLE
[Bug]: Cannot use native module better-sqlite3 in electron worker_thread

### ISSUE THREAD

**Issue by KoningWouter** [electron/electron#43513]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.1

### What operating system(s) are you using?

Windows, macOS

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

We are using better-sqlite3 in our project. And we are using it in a worker thread. 

It is a native module that is built on compile time (.node file). 

In our development environment it's possible to use it in the worker_thread without problems. When we require it in production in the main.ts file it's running fine.

### Actual Behavior

But when we try to use it in a worker_thread and in production we get the error:
Error: Cannot find module 'better-sqlite3'

It's just the native module. We are able to include non-native modules in worker_threads just fine.

We are struggling with this for days now and have no clue where to look or what could possible be the problem so it would really help if somebody could give it a hint.

Could it be a code signing issue? But then we wouldn't be able to require it from the main.ts file in production would we?

**Comment by nikwen** [comment]
Works just fine for me. Here's a simple code example: https://github.com/nikwen/electron-better-sqlite3-test

Hope this helps. If you still have issues, feel free to contact me through the email on my Github profile. I might be able to fix it for you as a small consulting project.

**Comment by KoningWouter** [comment]
@nikwen Thank you so much! We are going to try it today.

**Comment by KoningWouter** [comment]
> Works just fine for me. Here's a simple code example: https://github.com/nikwen/electron-better-sqlite3-test
> 
> Hope this helps. If you still have issues, feel free to contact me through the email on my Github profile. I might be able to fix it for you as a small consulting project.

I just tried your solution and it's indeed working the way you are doing it from the webpack config file.

In our code we are using it like this:
`new Worker(`${process.resourcesPath}/worker.ts`);`

From the main. (We instantiate the worker from an IPC call in our code)

If we do it like that it gives an error that it can't be imported. But it's very good you got it to work in a worker the way you did it. I wished it would be possible to do it the way you did but then run it on a method call with parameter.

**Comment by nikwen** [comment]
@KoningWouter You're welcome! I received an email on this issue that it didn't work on an IPC call, so here's another example of doing it from an IPC call: https://github.com/nikwen/electron-better-sqlite3-test/commit/bffe2dbb28d92e6b680c85ec34516a2867a0ecec

**Comment by KoningWouter** [comment]
> @KoningWouter You're welcome! I received an email on this issue that it didn't work on an IPC call, so here's another example of doing it from an IPC call: [nikwen/electron-better-sqlite3-test@bffe2db](https://github.com/nikwen/electron-better-sqlite3-test/commit/bffe2dbb28d92e6b680c85ec34516a2867a0ecec)

That is correct! I thought you only included the worker in the webpack configuration file but after further inspection it was in the index.ts so I deleted my comment.

Thanks so much for your time man, I really appreciate it. We're just two brothers trying to make a app and have been struggling with this for days! We now have to rewrite half of our project but that's not a problem. (We were creating an electron app with a very old boilerplate and couldn't use imports or typescript in our workers. Now we can!

So thanks again!

**Comment by nikwen** [comment]
Good luck!

**Comment by stuartambient** [comment]
> Works just fine for me. Here's a simple code example: [https://github.com/nikwen/electron-better-sqlite3-test ](https://github.com/nikwen/electron-better-sqlite3-test)
> 
> Hope this helps. If you still have issues, feel free to contact me through the email on my Github profile. I might be able to fix it for you as a small consulting project.

Is that from the packaged app or dev ? I've been fighting with worker threads, packaged app and the database .

**Comment by nikwen** [comment]
@stuartambient Both work. Packaged and dev.

**Comment by stuartambient** [comment]
@nikwen Thanks for clarifying. For the most part I have it working but found (since I have separate scripts for each worker I run) I can't point each worker to 1 file that holds the database connection.  Have had to repeat code in each worker script to make it work.

**Comment by georgexu99** [comment]
Closed as this is end-of-life 🙇
