### ISSUE TITLE
[Bug]: Custom scheme handler loses some data from url

### ISSUE THREAD

**Issue by alexpelan** [electron/electron#43516]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2.1

### What operating system(s) are you using?

Windows, macOS

### Operating System Version

MacOS Ventura 13.6.3

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I would expect the url received as `req.url` in the handler to not lose data. Currently the first letter after the protocol is getting set to lowercase and we are losing the colon character.

The output should read:
req.url unified-desktop-file://Users/test/Downloads/scout.png
req.url unified-desktop-file://C://Users//test//Downloads/scout.png

### Actual Behavior

Here's the console from the custom handler:

req.url unified-desktop-file://users/test/Downloads/scout.png
req.url unified-desktop-file://c//Users//test//Downloads/scout.png

The first line shows the capital U in Users is getting set to lower case.
The second line shows the C in C:\ is getting set to lowercase and the colon is being lost.

### Testcase Gist URL

https://gist.github.com/alexpelan/3e94116869ddf94ed67567762763a13d

**Comment by MarshallOfSound** [comment]
@alexpelan URI's have to follow a very strict spec, by definition file paths do not conform to that spec. In your case the important part is the "host" part of a URI is case insensitive, this means the OS (in most cases) will standardize that into lowercase, the hostname is also not allowed to have a trailing `:` as that would be the port syntax. E.g. `foo://a:123/bar` would be valid.

If you want to communicate a file path in a URI, use a query param

**Comment by nathanbabcock** [comment]
For anyone else who is still left a little confused like me, [this table](https://url.spec.whatwg.org/#url-representation) helped shed a little light:

![Screenshot 2024-08-31 133033](https://github.com/user-attachments/assets/cdebcd1d-e515-4920-aa95-a970b892582b)

If I understand correctly, registering a protocol with `{ standard: true }` in Electron puts it in the top row of this table, therefore requiring it it to have a non-empty hostname. Only the `file:` protocol gets special treatment where it can pass an empty host with `file:///C:/path/to/file`. Note the triple forward slash, with an empty string where the hostname would normally be.

Without `{ standard: true }` a custom protocol would go into the bottom "Others" row, and then something resembling a File URL like `custom:///C:/path/to/file` would be valid. But then the browser would not give it the same priveleges for CORS, media playback, etc.

So another alternative to using a query parameter would be to use a dummy hostname, something like: `custom://file/C:/path/to/file`. Colons are still valid inside URLs after the initial hostname section, for example: <https://en.wikipedia.org/wiki/Template:Welcome>.
