### ISSUE TITLE
[Bug]: DevTools always loads in light mode

### ISSUE THREAD

**Issue by sparecycles** [electron/electron#43525]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.1

### What operating system(s) are you using?

macOS

### Operating System Version

14.4.1 (23E224)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

31.4.0

### Expected Behavior

Devtools should open in darkmode when the Appearance theme indicates it should (system or Dark).

### Actual Behavior

Devtools opens in light mode every time, it _does_ remember the Appearance Theme _setting_ between runs, it just doesn't _respect_ it (as seen here with "Appearance -> Theme -> Dark" selected).

<img width="516" alt="image" src="https://github.com/user-attachments/assets/7122b2bf-c637-42f4-b9f3-4233e66e8915">

Changing the setting to a dark setting (system or Dark) changes the theme (until devtools is closed and re-opened).

Reproducible in fiddle, default project,... starting in 32.0.0-alpha1 (I didn't test exhaustively, but 32.0.0-alpha1 and both 32 releases), (33.0.0-alpha1 is still impacted, too)

### Testcase Gist URL

reproducible from the default fiddle

### Additional Information

Related / regression of https://github.com/electron/electron/issues/31864 ?

**Comment by AviVahl** [comment]
https://github.com/electron/electron/issues/43367

**Comment by forestk** [comment]
The light mode is very hard on my eyes, so I switch to dark mode from the settings every time. But I'm sick of it... 🫤
