### ISSUE TITLE
[Bug]: path not set on DataTransfer.files on drop event 

### ISSUE THREAD

**Issue by rmraya** [electron/electron#43534]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.1

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sonoma (14,6.1), Windows 11 Pro 23H2, openSUSE Leap 15.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

31.4.0

### Expected Behavior

The `path` attribute should be set on  DragEvent.dataTransfer.files  when files are dropped on an electron application.

It should be possible to get a list of files for processing using a snippet like this to handle a drop event:

``` typescript
dropListener(event: DragEvent, container: HTMLElement): void {
        event.preventDefault();
        event.stopPropagation();
        let filesList: string[] = [];
        for (const f of event.dataTransfer.files) {
            if (f.path) {
                filesList.push(f.path);
            }
        }
        if (filesList.length > 0) {
           // do something with the files
        }
    }
```

### Actual Behavior

On electron 32.0.1, all elements of `event.dataTransfer.files` have `path` set to `undefined`. 

Handling drag and drop with a snippet posted above worked fine in previous releases.

**Comment by rmraya** [comment]
Gist available at https://gist.github.com/rmraya/d41a6226ab036273f9ddb9927d95c4ab

**Comment by MarshallOfSound** [comment]
This was noted as a breaking change in Electron 32 --> https://www.electronjs.org/docs/latest/breaking-changes#removed-filepath

The breaking changes doc indicates it's replacement
