### ISSUE TITLE
[Bug]: [ERR_REQUIRE_ESM]: require() of ES Module ... is not supported

### ISSUE THREAD

**Issue by benbucksch** [electron/electron#43532]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.2

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Expected Behavior

(and actual result before adding `electron-context-menu`)
* App starts without errors

### Actual Behavior

Build failure

### Additional Information

Project setup
===

* Electron app using electron-builder, which uses vite as build system. The build system is still almost identical to the template.
* TypeScript, with the `.ts` file extension
* ESM and `import` everywhere in our code. We do not use `require()` anywhere in our code base.
* Obviously, we're using various third-party npm libraries.

Reproduction
===

1. `npm create @quick-start/electron@latest`
  * Project name: electron-app
  * Select a framework: › svelte
  * Add TypeScript? Yes
  * Add Electron updater plugin? Yes
  * Enable Electron download mirror proxy? No
2. `cd electron-app; yarn install; yarn run dev` -- works
3. `yarn add electron-context-menu`
4. `import` it and add the code to main.ts, as shown below.
5. Start the app using `yarn run dev`

Note: This is an ESM-only (!) third-party npm library, not built by me. The problem is not limited to this library. I have seen the same error multiple times in the past, with different libraries. It appears to be a generic problem with vite in combination with ESM-only modules.

Actual result
===

* Error, see below for console output

Expected result
===

(and actual result before adding `electron-context-menu`)
* App starts without errors

Code
===

Reduced code of the e2/src/main/index.ts file:
```typescript
import { BrowserWindow } from 'electron'
import contextMenu from 'electron-context-menu'; // <-- fails here

function createWindow(): void {
  contextMenu({}); // <-- actual use of the import
  const mainWindow = new BrowserWindow({...})
  ...
}

createWindow();
...
```

You find the rest of the files, including the build config files, at https://github.com/mustang-im/mustang/tree/4fc959d/e2 . This link is just for your convenience. Alternatively, you can follow the minimal steps above to reproduce the problem with a new empty Electron app. So, the problem is unrelated to our app code.

Error
===
```
App threw an error during load
Error [ERR_REQUIRE_ESM]: require() of ES Module /e2/node_modules/electron-context-menu/index.js from /e2/out/main/index.js not supported.
Instead change the require of /e2/node_modules/electron-context-menu/index.js in /e2/out/main/index.js to a dynamic import() which is available in all CommonJS modules.
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Object.<anonymous> (/e2/out/main/index.js:37:21)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at loadApplicationPackage (/e2/node_modules/electron/dist/resources/default_app.asar/main.js:121:16)
    at Object.<anonymous> (/e2/node_modules/electron/dist/resources/default_app.asar/main.js:233:9)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at node:electron/js2c/browser_init:2:123937
    at node:electron/js2c/browser_init:2:124140
    at node:electron/js2c/browser_init:2:124144
    at f._load (node:electron/js2c/asar_bundle:2:13377)
A JavaScript error occurred in the main process
Uncaught Exception:
Error [ERR_REQUIRE_ESM]: require() of ES Module /e2/node_modules/electron-context-menu/index.js from /e2/out/main/index.js not supported.
Instead change the require of /e2/node_modules/electron-context-menu/index.js in /e2/out/main/index.js to a dynamic import() which is available in all CommonJS modules.
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Object.<anonymous> (/e2/out/main/index.js:37:21)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at loadApplicationPackage (/e2/node_modules/electron/dist/resources/default_app.asar/main.js:121:16)
    at Object.<anonymous> (/e2/node_modules/electron/dist/resources/default_app.asar/main.js:233:9)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at node:electron/js2c/browser_init:2:123937
    at node:electron/js2c/browser_init:2:124140
    at node:electron/js2c/browser_init:2:124144
    at f._load (node:electron/js2c/asar_bundle:2:13377)
```

Fix attempts
===

What I tried to fix it:
* I found an existing Electron bug report [21457](https://github.com/electron/electron/issues/21457) which claims that the problem is fixed in Electron 28, but it seems that it's not working
* Error msg suggests to "change the require of ...": We're not using `require()` at all. Very confusing and misleading error msg. I suspect vite converts the `import` into a `require()`?
* I've tried with and without `type: module` in e2/package.json (of the electron app) - same result. Does not fix it.
* Various SO answers are **not** applicable (already tried, see above) or suggest HACKs that don't address the underlying problem (see below)
  * [Error [ERR_REQUIRE_ESM]: require() of ES Module not supported](https://stackoverflow.com/questions/69081410/error-err-require-esm-require-of-es-module-not-supported)
  * [Error: require() of ES modules is not supported when importing node-fetch](https://stackoverflow.com/questions/69041454/error-require-of-es-modules-is-not-supported-when-importing-node-fetch)
  * [Error [ERR_REQUIRE_ESM]: require() of ES Module index.js not supported](https://stackoverflow.com/questions/70550799/error-err-require-esm-require-of-es-module-index-js-not-supported)
* I've filed an [SO question](https://stackoverflow.com/questions/78942085/err-require-esm-require-of-es-module-is-not-supported), and was told to file a bug.
* Another person on StackOverflow was able to reproduce the exact same issue, with the reproduction steps above.

Rejected solutions
===

What I consider a bad fix with other disadvantages and what I do not want to do:
* Use a dynamic `import()`, because completely unnecessary here.
* Rename our code files and change the file extensions
* Downgrade the third-party library and use an old, unmaintained version of it.
* Using `require()`, or any other manual workarounds, like adding the module to exception lists etc.. 

Possible solutions
===
What I could imagine might work:

* Change the build configuration of vite to emit `import`/ESM code instead of transpiling into `require()` code.
* Fix vite?
* If it's a mistake on my part, the error message should point to the right fix. At the very least, the current error message is erroneous and misleading.

**Comment by VerteDinde** [comment]
@benbucksch You say you're using electron-builder - you may need to report this issue in that repo: https://github.com/electron-userland/electron-builder The Electron maintainers unfortunately don't directly maintain electron-builder (it's maintained independently), so we aren't equipped to debug issues with it. If you see the same issue with Electron Forge as well, that is a build system directly maintained by Electron's core maintainers, and we could be more helpful in debugging that. This isn't meant to push you toward one tool over another, just to be transparent about where we can provide debugging help vs where we have less oversight.

**Comment by benbucksch** [comment]
The core question is: Does Electron now fully support ESM everywhere? Most importantly in the main and preload processes?

In the past, it did not, that's why all the projects configure the builders to transpile into require() - even fully native ESM code. That's why we see that strange (and misleading) error message about changing require() to ESM, even though it's already ESM code.

If this is no longer necessary, and ESM now works everywhere I can tell the other projects to reconfigure vite to output ESM instead of require().

If ESM does not work flawlessly in Electron yet, then this is the cause and then this bug is about fixing that.

Ben

**Comment by absidue** [comment]
@benbucksch I would suggest reading the relevant page in the documentation that explains everything nicely and also what you need to watch out for: https://www.electronjs.org/docs/latest/tutorial/esm

**Comment by codebytere** [comment]
In agreement with above commenters, this is an item for forum discussion and not an issue with Electron itself - I'm going to close this out as not actionable on our side but if something else turns up we can reopen it.
