### ISSUE TITLE
[Bug]: memory leak when open and close application

### ISSUE THREAD

**Issue by win9s** [electron/electron#43569]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system(s) are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

When I frequently open and close applications(I used electron.exe from the official demo), although the process in the task manager has exited, I can see that there are residual processes in the process through the rammap tool, occupies the computer's virtual memory, But this problem does not occur in the latest version 32.0.2

![微信截图_20240905154359](https://github.com/user-attachments/assets/73afad1b-576a-4b76-af2e-554134a4f104)

### Actual Behavior

I expect the memory to be normal

**Comment by holaw442** [comment]
Its the same issue 😭

**Comment by win9s** [comment]
This problem does not require a test case. You can reproduce it by using the official application downloaded from GitHub and the rammap memory analysis tool provided by Microsoft. The following are the links:

1. electron 13.1.7 : https://github.com/electron/electron/releases/download/v13.1.7/electron-v13.1.7-win32-x64.zip
2. rammap application : https://learn.microsoft.com/en-us/sysinternals/downloads/rammap

Here are the steps to reproduce:
1. Download electron-v13.1.7-win32-x64.zip, unzip it and double-click to run electron.exe
2. Close electron.exe
3. Repeat opening and closing electron.exe several times
4. Use the rammap tool to perform memory analysis, and you will see that there are residual electron.exe processes in the "process" module

In addition, the latest version of electron does not have this problem.

 Any reply will be much appreciated!

**Comment by MarshallOfSound** [comment]
> In addition, the latest version of electron does not have this problem.

13.1.7 is no longer a supported Electron version. Per our [Version Support Policy](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#version-support-policy) only the last three major versions are supported.

Given this isn't occurring on latest stable I'm going to close this out as resolved. If you want the fix, update to a more recent version of Electron.
