### ISSUE TITLE
[Bug]: macOS Production Build: Infinite Window Instantiation and System Freeze

### ISSUE THREAD

**Issue by alkaest2002** [electron/electron#43593]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.1

### What operating system(s) are you using?

macOS

### Operating System Version

Mac OS Sonoma 14.6.1 (23G93)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

N.a.

### Expected Behavior

App launches and creates main window.

### Actual Behavior

I have developed a site using the Hugo static site generator and encapsulated the output from the Hugo build process within an Electron application. _The development version of the macOS app functions correctly_; however, the production build exhibits a critical issue. Upon launching the production app, the main window is instantiated repeatedly in an infinite loop.

This loop causes multiple windows to stack in the same position on the screen, resulting in an increasingly darker shadow effect beneath them. The continuous creation of windows ultimately leads to a near-total freeze of the macOS environment. Even attempting to force quit the app is insufficient to stop the loop, necessitating a full system reboot to regain control.

The site built with Hugo is a straightforward static site that doesn't include any complex or advanced functionalities. For styling, the site uses Tailwind CSS as the framework. Additionally, the site leverages HTMX and Alpine.js for minimal JavaScript interactivity.

**server.js**

```javascript
const express = require('express');
const path = require('path');

const app = express();
const port = 9000;

app.use(express.static(path.join(__dirname, 'public')));

app.listen(port);
```

**main.js**

```javascript
const {app, BrowserWindow} = require('electron');
const path = require('path');
const { fork } = require('child_process');

const ps = fork(path.resolve(__dirname, "server.js"));

const createWindow = () => {

  const mainWindow = new BrowserWindow({
    width: 750,
    minWidth: 750,
    height: 850,
    minHeight: 850,
    webPreferences: { webSecurity: false }
  });
  
  mainWindow.loadFile(path.resolve(__dirname, "public", "index.html"));
  // mainWindow.webContents.openDevTools()
}

app.whenReady().then(() => createWindow()) 
app.on('window-all-closed', () => {
	app.quit();
	ps.kill();
});
```

### Testcase Gist URL

https://github.com/alkaest2002/mpa.git

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by alkaest2002** [comment]
This is not a question but rather a report of what I believe to be a bug. I'm not seeking support; I'm highlighting an issue that should be addressed as a bug. The Electron app runs smoothly in development mode but hangs in production mode. The app essentially serves as a container for a site generated by a static site generator, so it should work seamlessly.

The fact that a collection of static HTML files, minimally enhanced with client-side JavaScript, causes the production app to freeze—and even impacts the OS—seems to be clear evidence of a bug. Please note that these static files work correctly in a browser.

Please help me better understand why this behavior should not be considered a bug."

**Comment by alkaest2002** [comment]
As an additional note, I should clarify that the glitchy behavior does not occur when I download the prebuilt binary of the Electron app and add the app folder (containing the goHugo generated static files) according to the electron website instructions. To recap, the problem arises when I "compile" the electron app via @electron-forge/cli.

**Comment by alkaest2002** [comment]
I tried to solve the issue by using the electron app prebuilt binary for MacOS.

Since Express.js is not a native Node module, I let ChatGPT rewrite the server like so:

**server.js**

```javascript
const http = require('http');
const fs = require('fs');
const path = require('path');

const port = 9000;
const publicDir = path.join(__dirname, 'public');

const server = http.createServer((req, res) => {
    let filePath = path.join(publicDir, req.url);

    // Check if the request is for a directory or a non-file resource
    if (fs.existsSync(filePath) && fs.statSync(filePath).isDirectory()) {
        filePath = path.join(filePath, 'index.html');
    }

    // If the file does not exist, check if it's a non-file resource and serve index.html
    if (!fs.existsSync(filePath)) {
        filePath = path.join(publicDir, 'index.html');
    }

    const extname = String(path.extname(filePath)).toLowerCase();
    const mimeTypes = {
        '.html': 'text/html',
        '.js': 'application/javascript',
        '.css': 'text/css',
        '.json': 'application/json',
        '.png': 'image/png',
        '.jpg': 'image/jpg',
        '.gif': 'image/gif',
        '.svg': 'image/svg+xml',
        '.wav': 'audio/wav',
        '.mp4': 'video/mp4',
        '.woff': 'application/font-woff',
        '.ttf': 'application/font-ttf',
        '.eot': 'application/vnd.ms-fontobject',
        '.otf': 'application/font-otf',
        '.wasm': 'application/wasm',
        '.zip': 'application/zip'
    };

    const contentType = mimeTypes[extname] || 'application/octet-stream';

    fs.readFile(filePath, (error, content) => {
        if (error) {
            if (error.code == 'ENOENT') {
                res.writeHead(404, { 'Content-Type': 'text/html' });
                res.end('404 Not Found', 'utf-8');
            } else {
                res.writeHead(500);
                res.end(`Server Error: ${error.code}`, 'utf-8');
            }
        } else {
            res.writeHead(200, { 'Content-Type': contentType });
            res.end(content, 'utf-8');
        }
    });
});

server.listen(port, () => {
    console.log(`Server is running on http://localhost:${port}`);
});
```
Made some slight changes to the main.js file.

**main.js**

```javascript
const {app, BrowserWindow} = require('electron');
const path = require('path');
const { fork } = require('child_process');

const ps = fork(path.resolve(__dirname, "server.js"));

const createWindow = () => {

  const mainWindow = new BrowserWindow({
    width: 750,
    minWidth: 750,
    height: 850,
    minHeight: 850,
    webPreferences: { webSecurity: false }
  });
  
  mainWindow.loadFile(path.resolve(__dirname, "public", "index.html"));
  // mainWindow.webContents.openDevTools()
}

app.whenReady().then(() => createWindow());
app.on('window-all-closed', () => app.quit());
app.on('quit', () => ps.kill());
```

The production app launches correctly with the MacOS prebuilt binary, the server.js, main.js (as illustrated here) and the goHugo generated static site inside the app folder.

So, I guess that the bug relates to @electron-forge/cli.
