### ISSUE TITLE
`ipc.send` cannot be called reliably before BrowserWindow.close

### ISSUE THREAD

**Issue by bengotow** [electron/electron#4366]
If you call `ipc.send` in a beforeUnload handler, for example, the window is destroyed before the IPC message reaches the main process. Technically, an application could carefully track that it was in a "beforeUnload" state and use `ipc.sendSync` instead, but this is hard to do and requires that everyone think about this potential scenario when designing libraries that wrap `ipc`.

I think Electron should internally ensure that `ipc` messages are completely sent before cleaning up a BrowserWindow if that's possible!

**Comment by CharlieHess** [comment]
:+1:; we encounter this often in the Slack app.

**Comment by feross** [comment]
I encounter this in the [WebTorrent app](https://github.com/feross/webtorrent-app).

**Comment by bengotow** [comment]
Hey folks! Our team got bit by this again today, wanted to see if we could move the discussion forward on a possible solution. Is there any way we could "upgrade" a call to `AtomViewHostMsg_Message` to a synchronous call by waiting on it to complete when the window is about to close?

Just as a side note, it appears that `ipc.send` calls can take up to 100ms to reach the main process in some scenarios.

**Comment by lasryaric** [comment]
We are also hitting that issue on the [hellobill app](http://www.hellobill.io)

**Comment by codebytere** [comment]
closing due to abandonment.
