### ISSUE TITLE
Bug]: session.defaultSession.loadExtension

### ISSUE THREAD

**Issue by langrenzhou** [electron/electron#43699]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^28.2.0

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Last Known Working Electron version

^28.2.0

### Expected Behavior

import { app, shell, BrowserWindow, ipcMain, BrowserView ,screen,session} from 'electron'
import { join } from 'path'
import { electronApp, optimizer, is } from '@electron-toolkit/utils'
import icon from '../../resources/icon.png?asset';

let mainWindow;
const host = '127.0.0.1'
const AppsViews = [
  {
    appName: 'vqe',
    href: `http://${host}:5176/vqes/detail`,
    view: null,
    jobType: 'Vqe'
  }, {
    appName: 'maxCut',
    href: `http://${host}:5176/maxcuts`,
    view: null,
    jobType: 'Qaoa'
  }, {
    appName: 'trotter',
    href: `http://${host}:5176/trotters`,
    view: null,
    jobType: 'Trotter'
  }, {
    appName: 'tutorial',
    href: `http://${host}:5176/tutorial/list`,
    view: null
  }, {
    appName: 'composer',
    href: `http://${host}:5178/composer`,
    view: null,
    jobType: 'Composer'
  }
];

const createWindow = () => {
  const primaryDisplay=screen.getPrimaryDisplay();
  const {width,height}=primaryDisplay.size;
  mainWindow = new BrowserWindow({
    show: false,
    fullscreen: true,width,height,
    autoHideMenuBar: true, 
    ...(process.platform === 'linux' ? { icon } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false,
      devTools:true
    },
    titleBarStyle: 'hidden'
  });
  app.path = join(__dirname, '../renderder/public')
  app.path = join(__dirname, '../renderder/public')

  // AppsViews.forEach(item => {
  //   const newView = new BrowserView({
  //     webPreferences: {
  //       preload: join(__dirname, '../preload/index.js'),
  //       sandbox: false
  //     }
  //   });
    // newView.setBounds({ x: 0, y: 0, width: 0, height:0 });
    // newView.webContents.loadURL(item.href);
    // item.view = newView;
  // });

  mainWindow.on('ready-to-show', () => {
    mainWindow.show();
    mainWindow.webContents.openDevTools();
  })

  mainWindow.webContents.setWindowOpenHandler((details) => {
    shell.openExternal(details.url)
    return { action: 'deny' }
  })

  if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    mainWindow.loadURL(process.env['ELECTRON_RENDERER_URL'])
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
}

app.disableHardwareAcceleration();

app.whenReady().then(async () => {

  const path = require('path');
  // await session.defaultSession.loadExtension(reactDevToolsPath)
  try{
    // const extPath = path.join(__dirname, '..\\..\\resources\\extensions\\keyWord');
    // await session.defaultSession.loadExtension(extPath);
    // createWindow();
    // // console.log(extPath)
    await session.defaultSession.loadExtension("C://Users//26036//AppData//Local//Google//Chrome//User Data//Default//Extensions//cjabmkimbcmhhepelfhjhbhonnapiipj//0.4.6_0").then(res=>{console.log(res)}).catch(err=>{console.log(err)});
    createWindow();
  }catch(e){
    console.log(e);
  }
  
  electronApp.setAppUserModelId('com.electron')
  app.on('browser-window-created', (_, window) => {
    optimizer.watchWindowShortcuts(window)
  })

  ipcMain.on('ping', () => console.log('pong'))

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
});

app.on('will-quit', () => {
   console.log(session)
});

const showBrowserView = (name,token) => {
  const currentView = mainWindow.getBrowserView();
  if (currentView) {
    mainWindow.removeBrowserView(currentView);
  }
  const { view } = AppsViews.find(({ appName }) => appName == name);
  mainWindow.setBrowserView(view);
  view.webContents.send('save-token',token);
  view.webContents.executeJavaScript('window.scrollTo(0, 0);');
  view.webContents.openDevTools();
  if(name == 'composer'){
    view.webContents.reload();
  }
  view.setBounds({ x: 0, y: 0, width: mainWindow.getBounds().width, height: mainWindow.getBounds().height });
}

ipcMain.on('show-browser-view', (_, data) => {
    const {token}=data;
    const { href, view, appName } = AppsViews.find(({ appName }) => appName == data.appName);
    // if(!href.includes('?')){
    //   showBrowserView(appName,token);
    //   return ;
    // }
    view.webContents.once('did-finish-load', () => {
      // console.log()
      showBrowserView(appName,token);
    });
    view.webContents.loadURL(`${href}?token=${token}`);
  });

ipcMain.on('change-browserWindow-route', (_, data) => {
  mainWindow.webContents.send('changeRouter', data);
});

ipcMain.on('hide-browser-view', () => {
  const currentView = mainWindow.getBrowserView();
  if (currentView) {
    mainWindow.removeBrowserView(currentView);
  }
});

// ipcMain.on('save-article', (_, data) => {
//   mainWindow.webContents.send('save-article-axios', data);
// });

ipcMain.on('show-browser-view-Archive', (_, data) => {
  const { id ,token} = data;
  const { href, view, appName } = AppsViews.find(({ jobType }) => jobType == data.jobType);
  
  view.webContents.once('did-finish-load', () => {
    showBrowserView(appName,token);
  });
   
  view.webContents.loadURL(`${href}?ArticleId=${id}&token=${token}`);
});

ipcMain.on('shutdown',()=>{
  const {exec}=require('child_process');
  exec("shutdown -h now",(err)=>{
    if(err){
      console.log(err)
    }
  })
})
  我期望在 build 之后可以加载这个扩展

### Actual Behavior

但是实际上我再开发模式运行中扩展可以被加载，但是build之后扩展未使用

### Additional Information

但是实际上我再开发模式运行中扩展可以被加载，但是build之后插件被加载，但是扩展程序没有启动

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
