### ISSUE TITLE
[Bug]: `window.onerror` doesn't catch error in renderer

### ISSUE THREAD

**Issue by nikwen** [electron/electron#43705]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.1.0

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sonoma 14.6.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

If an uncaught error occurs in a function in my renderer, it is passed to `window.onerror` of the renderer process.  
If an unhandled rejection occurs in a function in my renderer, it is passed to `window.onunhandledrejection` of the renderer process.

### Actual Behavior

If a function from my renderer script is passed to `ipcRenderer.on()` via the preload script, `window.onerror` and `window.onunhandledrejection` of the renderer script won't catch the error / rejection.

Instead, the error / rejection is passed to the `window.onerror` and `window.onunhandledrejection` listeners of the preload script.

### Testcase Gist URL

https://gist.github.com/nikwen/4f09211d95a628b5b1292e95c9f69f8b

#### Output of the Fiddle

<img width="912" alt="Output" src="https://github.com/user-attachments/assets/67774479-b809-4cd6-b14d-b574a1f31d5e">

I'd expect the output to say:

```
We have an uncaught error
We have an unhandled rejection
```

**Comment by MarshallOfSound** [comment]
This is currently expected behaviour, exceptions are dispatched in the context they are "uncaught" not the context in which they are created.

The actual place where the error is not being caught is here `() => callback()`. Which is quite clearly on the preload script side of the bridge, so that's where the uncaught exception handler is firing.

Exceptions bubble all the way up the callstack until either a `try/catch` is reached, or it becomes an unhandled exception. The top of the stack in this case is the preload script because that's where the IPC message entrance began.

**Comment by nikwen** [comment]
Thanks for explaining, @MarshallOfSound!

Do you think it would make sense to document this somewhere, as it can be unexpected and confusing?

I was thinking the [IPC tutorial](https://www.electronjs.org/docs/latest/tutorial/ipc) might be a good place.

**Comment by Bistard** [comment]
> Thanks for explaining, [@MarshallOfSound](https://github.com/MarshallOfSound)!
> 
> Do you think it would make sense to document this somewhere, as it can be unexpected and confusing?
> 
> I was thinking the [IPC tutorial](https://www.electronjs.org/docs/latest/tutorial/ipc) might be a good place.

I just got confused about this too. Glad I checked the issue list instead of asking twice.

**Comment by nikwen** [comment]
> I just got confused about this too. Glad I checked the issue list instead of asking twice.

There is a pull request for documenting this that has been sitting unreviewed for over a month: https://github.com/electron/electron/pull/44113
