### ISSUE TITLE
[Bug]: Linux window control overlays do not allow window resize on the corners

### ISSUE THREAD

**Issue by bpasero** [electron/electron#43714]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.x

### What operating system(s) are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

You can resize the window in the top-right corner around the window controls:

![Image](https://github.com/user-attachments/assets/a2ea2ccf-eae3-48a4-bd8a-6e02522e4bef)

### Actual Behavior

You cannot resize.

### Additional Information

Simple gist:

```
// Modules to control application life and create native browser window
const { app, BrowserWindow } = require('electron')
const path = require('node:path')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
    },
    frame: false,
    titleBarStyle: "hidden",
    titleBarOverlay: {
      height: 29
    }
  });

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

//cc @codebytere 

Reported as https://github.com/microsoft/vscode/issues/228505

**Comment by quexten** [comment]
Not sure if it's the same bug, but on Gnome on Wayland, in at least Fedora 40 and Ubuntu 22.04, with `--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto`, on `default` titlebarstyle, the window becomes entirely un-resizeable (no matter from which side / corner) after upgrading to `32.1.0`. This is not present when downgrading to `31.4.0`.

With the titlebarstyle from the comment in this issue, on `32.1.0`, I see the same behavior as described in the comment (i.e sides are re-sizeable but corner is not).

**Comment by dtcooper** [comment]
> Not sure if it's the same bug, but on Gnome on Wayland, in at least Fedora 40 and Ubuntu 22.04, with `--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto`, on `default` titlebarstyle and `frame: true`, the window becomes entirely un-resizeable (no matter from which side / corner) after upgrading to `32.1.0`. This is not present when downgrading to `31.4.0`.
> 
> With the titlebarstyle from the comment (`frame: false`) in this issue, on `32.1.0`, I see the same behavior as described in the comment (i.e sides are re-sizeable but corner is not).

Observing this as well, even after the fix @quexten. Tested on GNOME 46 and 47. Should we create a new issue?

**Comment by codebytere** [comment]
@dtcooper i believe this is related to https://github.com/electron/electron/issues/42894

**Comment by dtcooper** [comment]
Ah, thanks for pointing that out @codebytere. I'll track that issue for a fix -- let me know if I can assist. Tested on Debian stable (GNOME 43) and Arch (GNOME 46/47) and observing the problem with Wayland enabled.
