### ISSUE TITLE
[Bug]: No file path in File object returned by Ant Design Upload component

### ISSUE THREAD

**Issue by ngochoangnd95** [electron/electron#43720]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.1.0

### What operating system(s) are you using?

macOS

### Operating System Version

Sonoma 14.4.1

### What arch are you using?

x64

### Last Known Working Electron version

31.0.1

### Expected Behavior

I build a video editor tool by Electron Forge, React and Ant Design. I use Upload component in Ant Design to select local files. Two months ago, when I selected a file, it returned a File object which had file path. Now I remake my repo, returned File object has no file path. I try downgrading some dependencies and find out that electron version 31.0.1 still work fine. Please check this bug in the latest version.

### Actual Behavior

File object has no file path.

**Comment by absidue** [comment]
Please read the changelog, it mentions the removal of that non-standard property and the replacement for it: https://www.electronjs.org/docs/latest/breaking-changes#removed-filepath

**Comment by ngochoangnd95** [comment]
> Please read the changelog, it mentions the removal of that non-standard property and the replacement for it: https://www.electronjs.org/docs/latest/breaking-changes#removed-filepath

Thank you for your reply! I will close this issue.
