### ISSUE TITLE
[Upgrades Follow-Up]: Re-enable base url + data url test

### ISSUE THREAD

**Issue by clavin** [electron/electron#43730]
In #43454 we've ended up with a single test that was failing on Windows CI: `BrowserWindow module BrowserWindow.loadURL(url) should support base url for data urls`.

This roll has been open and paused for a couple of weeks. In the interest of keeping upgrades rolling, we're opting to disable the test in the short-term. We want to come back and re-enable this test ASAP, but we figure that can be done async to the rest of the upgrade roll process.

**Comment by jkleinsc** [comment]
This was caused by https://chromium-review.googlesource.com/c/chromium/src/+/5802682.  I have fix in https://github.com/electron/electron/pull/43453; I'll put up a separate PR to fix in main.
