### ISSUE TITLE
[Bug]: window.document is not accessible when child window creation is overriden

### ISSUE THREAD

**Issue by CezaryKulakowski** [electron/electron#43740]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.0-nightly.20240808

### What operating system(s) are you using?

macOS

### Operating System Version

macOS 14.6.1

### What arch are you using?

arm64 (including Apple Silicon)

### Reproduction steps

1. Start following app:
```
const {app, BrowserWindow, BrowserView} = require('electron')

app.once('ready', async () => {
  window = new BrowserWindow({
    width: 800,
    height: 600,
    show: true
  })

  window.webContents.setWindowOpenHandler(({ url }) => {
    console.log(`open window: ${url}`);
    return {
      action: 'allow',
      createWindow: (options) => {
        const child = new BrowserWindow({
            webContents: options?.webContents,
            webPreferences: options?.webPreferences
        });

        return child.webContents;
      }
    }
  });

  await window.webContents.loadURL('https://www.example.com');
});
```
2. Open devtools window
3. Execute: `let win = window.open('about:blank')`

### Expected Behavior

win.document can be accessed

### Actual Behavior

win.document can't be accessed: it fails with error:
```
Uncaught SecurityError: Failed to read a named property 'document' from 'Window': Blocked a frame with origin "https://www.example.com" from accessing a cross-origin frame.
```

### Additional Information

`win.document` can be accessed when child window creation is not overriden by `WebContents::setWindowOpenHandler`.

_No response_

**Comment by codebytere** [comment]
@CezaryKulakowski it looks like this is a result of https://github.com/electron/electron/pull/41432 - it works as expected when `createWindow` isn't passed.

**Comment by CezaryKulakowski** [comment]
I can confirm that https://github.com/electron/electron/pull/43775 fixes the problem. @codebytere thanks for quick respond and fix.
