### ISSUE TITLE
[Bug]: Pipewire screen capture crashes if used more than once in the same execution of electron31

### ISSUE THREAD

**Issue by kode54** [electron/electron#43824]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.6.0

### What operating system(s) are you using?

Other Linux

### Operating System Version

Arch Linux laharl 6.11.0-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sun, 15 Sep 2024 19:32:27 +0000 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

31.x.x unknown

### Expected Behavior

Screen sharing should continue to function after repeated uses in the same execution of the electron31 app.

### Actual Behavior

Vesktop crashes electron31 when sharing the screen for a second successive time in the same execution.

### Additional Information

I am running under a wlroots compositor, using xdg-desktop-portal-wlr.

Here is a backtrace of the crash which usually happens:

```
#0  pw_thread_loop_start (loop=0x0) at ../pipewire/src/pipewire/thread-loop.c:319                  
319		if (!loop->running) {
[Current thread is 1 (Thread 0x7b825e5df140 (LWP 425387))]
(gdb) bt
#0  pw_thread_loop_start (loop=0x0) at ../pipewire/src/pipewire/thread-loop.c:319
#1  0x00005b38df01db6f in webrtc::SharedScreenCastStreamPrivate::StartScreenCastStream(unsigned int, int, unsigned int, unsigned int, bool, webrtc::DesktopCapturer::Callback*) ()
#2  0x00005b38df0189b8 in webrtc::BaseCapturerPipeWire::OnScreenCastRequestResult(webrtc::xdg_portal::RequestResponse, unsigned int, int) ()
#3  0x00005b38df019ccc in webrtc::ScreenCastPortal::OnPortalDone(webrtc::xdg_portal::RequestResponse) ()
#4  0x00005b38df01aa61 in webrtc::ScreenCastPortal::OnOpenPipeWireRemoteRequested(_GDBusProxy*, _GAsyncResult*, void*) ()
#5  0x00007b826e2e042c in g_task_return_now (task=0x3c2404ac3580) at ../glib/gio/gtask.c:1361
#6  0x00007b826e2e4705 in g_task_return (type=<optimized out>, task=0x3c240587c600)
    at ../glib/gio/gtask.c:1430
#7  g_task_return (task=0x3c240587c600, type=<optimized out>) at ../glib/gio/gtask.c:1387
#8  0x00007b826e35130d in reply_cb (connection=<optimized out>, res=<optimized out>, 
    user_data=0x3c240587c600) at ../glib/gio/gdbusproxy.c:2555
#9  0x00007b826e2e042c in g_task_return_now (task=0x3c240251ff00) at ../glib/gio/gtask.c:1361
#10 0x00007b826e2e4705 in g_task_return (type=<optimized out>, task=0x3c240251ff00)
    at ../glib/gio/gtask.c:1430
#11 g_task_return (task=0x3c240251ff00, type=<optimized out>) at ../glib/gio/gtask.c:1387
#12 0x00007b826e340043 in g_dbus_connection_call_done (source=<optimized out>, 
    result=<optimized out>, user_data=0x3c240251ff00) at ../glib/gio/gdbusconnection.c:6346
#13 0x00007b826e2e042c in g_task_return_now (task=0x3c24033d09c0) at ../glib/gio/gtask.c:1361
#14 0x00007b826e2e0475 in complete_in_idle_cb (task=0x3c24033d09c0) at ../glib/gio/gtask.c:1375
#15 0x00007b826eb0d559 in g_main_dispatch (context=0xb7c00220b60) at ../glib/glib/gmain.c:3357
#16 0x00007b826eb70157 in g_main_context_dispatch_unlocked (context=0xb7c00220b60)
    at ../glib/glib/gmain.c:4208
#17 g_main_context_iterate_unlocked.isra.0 (context=context@entry=0xb7c00220b60, 
    block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/glib/gmain.c:4273
#18 0x00007b826eb0ca55 in g_main_context_iteration (context=0xb7c00220b60, may_block=1)
    at ../glib/glib/gmain.c:4338
#19 0x00005b38de699fac in base::MessagePumpGlib::Run(base::MessagePump::Delegate*) ()
#20 0x00005b38de63254a in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ()
#21 0x00005b38de5fb1a6 in base::RunLoop::Run(base::Location const&) ()
#22 0x00005b38dd2eb45d in content::BrowserMainLoop::RunMainMessageLoop() ()
#23 0x00005b38dd2ed273 in content::BrowserMainRunnerImpl::Run() ()
#24 0x00005b38dd2e89ca in content::BrowserMain(content::MainFunctionParams) ()
#25 0x00005b38dacbd027 in content::RunBrowserProcessMain(content::MainFunctionParams, content::ContentMainDelegate*) ()
#26 0x00005b38dacbe9c7 in content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) ()
#27 0x00005b38dacbe7a8 in content::ContentMainRunnerImpl::Run() ()
#28 0x00005b38dacbbb31 in content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) ()
#29 0x00005b38dacbc02a in content::ContentMain(content::ContentMainParams) ()
#30 0x00005b38da94bc1e in main ()
```

**Comment by kode54** [comment]
It may be related to the display being powered off and back on across night time and resuming again the next day. I don't believe either of these displays detach themselves from the bus in the process, though.

**Comment by kode54** [comment]
I may take this to Vesktop/Vencord as a bug in their implementation of NodeJS code around Discord, as I think I isolated the exact reproduction process.

It seems to trigger if I restart Vesktop and it is offering to reconnect a video call, and I click the reconnect button, then turn on my camera, then attempt to share my desktop to the call. I'll leave this open in case it's a combination with an Electron issue.

**Comment by kode54** [comment]
Also, I can reproduce this with their upstream build with Electron 32.1.2.

**Comment by mlaurencin** [comment]
Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. A stand-alone testcase without third-party code would allow for this issue to be triaged by maintainers.

**Comment by kode54** [comment]
I will just live with the crashes, as I am not a javascript developer.
