### ISSUE TITLE
Mouse Down Event for Tray Icon

### ISSUE THREAD

**Issue by keithpitt** [electron/electron#4384]
Hey! After clicking around tray icons in OSX, native applications show their applications on mouse down, and not click. Would a "mouse down" event for tray icons make sense in electron? I checked out the OS X implementation and saw that it could be possible in there.

**Comment by lucidNTR** [comment]
+1

**Comment by lucidNTR** [comment]
also long clicks cannot really be handled with the existing events, as long clicks will not trigger click events

**Comment by danhp** [comment]
Dug into this and I don't think this is fixable. The only reason being that as long presses swallows the `:mouseUp` event, this results in a minor UI hiccup if the menu was shown on mouse down.

It would be possible to add a `mouse-down` event but I can't find a use case for it.

**Comment by OlsonDev** [comment]
> It would be possible to add a mouse-down event but I can't find a use case for it.

Doesn't the OP illustrate a use case?

**Comment by danhp** [comment]
@OlsonDev which is already handled in a bug free manner by `mouseUp`

**Comment by keithpitt** [comment]
@danhp thanks for looking into it! So the reason I mentioned it in the first place, is because I think it'd be a good idea to be able to show a popup panel on mouse down instead of mouse up. By using mouse down, by the time the user lifts their finger from the button, the panel would already be visible, making the app feel much faster.

If you hold the mouse button over a native OSX menu bar app, the panels show up on mouse down (not mouse up) so I was trying to replicate that behaviour as close as I could.

**Comment by danhp** [comment]
@keithpitt Yup, that's the reason I looked into this (wanted the tray to behave like native). But exposing a `mouse-down` event won't bring it closer to being solved as it will allow you to show a menu but not highlight the tray icon itself. So it's better to just let the app handle all of that for you. As for having it show on `mouseDown`, long pressed leave the tray icon highlighted until the next click but with no menu showing.

For reference the Google Drive tray runs into a very similar problem but overcomes it by having a custom menu that they have full control over.

**Comment by keithpitt** [comment]
Ah, that's a shame! So I suppose this should be marked as a "can't/won't fix" type thing and the issue closed? Thanks for taking the time to look into it!

**Comment by zcbenz** [comment]
I'm closing this issue since adding mouse down event won't solve the original problem.

**Comment by natew** [comment]
@zcbenz is there a ticket for the original problem?
