### ISSUE TITLE
System level key bindings

### ISSUE THREAD

**Issue by twolfson** [electron/electron#439]
I am interested in system level key binding support for `atom-shell`. I have built a desktop Google Music application via `node-webkit`. I would like to add media key support but `node-webkit` does not currently support this and has stagnated on the issue, rogerwang/node-webkit#200. As a result, I am looking for alternatives, including switching to `atom-shell`.

https://github.com/twolfson/google-music-webkit

Is there is currently a way to attach system level key bindings via `atom-shell` or are there plans for supporting this in the future?

**Comment by jordanpotter** [comment]
Curious, was this feature implemented and then closed? Or was this feature considered out of scope?

**Comment by 72lions** [comment]
:+1:
