### ISSUE TITLE
[Bug]: How to limit the memory of GPU process

### ISSUE THREAD

**Issue by leon9508** [electron/electron#43937]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3.24

### What operating system(s) are you using?

macOS

### Operating System Version

macOS1 3.5.1 (22G90)

### What arch are you using?

x64

### Expected Behavior

The rendering process of my application is a webview, where multiple iframe pages are nested within the webview page.

When my application quickly clicks to switch between different iframe pages, the GPU process's memory continues to increase to 300-500M. When I stop the operation, the GPU process's memory is not reclaimed unless I minimize the window.

And when I perform the same operation in the browser,  the memory of the GPU process in the browser will be quickly reclaimed.

My expectation is that the GPU process's memory can be reclaimed as soon as possible or its maximum memory usage can be limited without turning off hardware acceleration.

### Actual Behavior

The GPU process's memory is not reclaimed unless I minimize the window.

**Comment by leon9508** [comment]
When I added the following command, the problem was solved on Mac, and the GPU process's memory was controlled within 200M, but it was not effective on Windows 11:
app.commandLine.appendSwitch("disable-gpu-memory-buffer-compositor-resources");

**Comment by leon9508** [comment]
Can someone help me solve this problem？

**Comment by leon9508** [comment]
I guess it should be related to webview tag

**Comment by mlaurencin** [comment]
@leon9508 Like mentioned in electron-issue-triage's earlier message, 22.3.24 is no longer supported. Please test this issue against the currently supported versions, and if you are still experiencing it, update the issue with that new version number and provide a standalone test case. For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

I'm adding the https://github.com/electron/electron/labels/blocked%2Fneed-info%20%E2%9D%8C label for this reason. This issue will be closed in 10 days if the above is not addressed.

**Comment by leon9508** [comment]
Thank you very much for your reply!  After upgrading the version to 30.0.0 or above, I found that there was a significant optimization for this issue. GPU process memory can be reclaimed, but I need to be compatible with Win7 and can only use version 22.
Will you continue to optimize version ^22.0.0?

**Comment by mlaurencin** [comment]
^22.0.0 as not been a supported version for some time now, so unfortunately there will be no more updates to that version line. Since this is the case, is this issue all set to be closed?

**Comment by leon9508** [comment]
Of course! thank you
