### ISSUE TITLE
[Bug]: Electron shown blank screen on redirect for auth popup

### ISSUE THREAD

**Issue by bhosachin** [electron/electron#43940]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.1.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

NA

### Expected Behavior

We are using electron browser window to show third party web app and that web app asks for authentication popup which is not working with electron window, it just makes screen white where as if we try same URL in chrome browser, it works fine.

electron should not block authentication popup.

Here is code snipp :
createWindow(url: string, devTools: boolean) {
    const window = new BrowserWindow({
      ...this.settings,
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        contextIsolation: true,
      },
    });
    window.loadURL(url);
    if (devTools) window.webContents.openDevTools();
    window.webContents.on('did-fail-load', (event, errorCode, errorDescription) => {
      console.log(`An error occurred: ${errorDescription}`);
    });
    return window;
  }

### Actual Behavior

We are using electron browser window to show third party web app and that web app asks for authentication popup which is not working with electron window, it just makes screen white where as if we try same URL in chrome browser, it works fine.
Electron browser window is block authentication popup and it becomes white screen.

Here is code snipp :
createWindow(url: string, devTools: boolean) {
    const window = new BrowserWindow({
      ...this.settings,
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        contextIsolation: true,
      },
    });
    window.loadURL(url);
    if (devTools) window.webContents.openDevTools();
    window.webContents.on('did-fail-load', (event, errorCode, errorDescription) => {
      console.log(`An error occurred: ${errorDescription}`);
    });
    return window;
  }

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by bkarv** [comment]
@bhosachin did you end up finding a solution for this? We are also getting a blank screen trying to open microsoft login page for SSO auth.

**Comment by bkarv** [comment]
@bhosachin All good found the issue it was related to the csp for microsoft login not being set.

**Comment by Danishlynx** [comment]
I’ve implemented a complete fix for the OAuth popup white-screen in Electron by:

Whitelisting Google OAuth domains in the SecurityManager

Detecting and exempting OAuth popup BrowserWindows from navigation blocking

Allowing OAuth popups via setWindowOpenHandler for accounts.google.com, gsi.google.com, auth.character.ai, writesonic.com, etc.

Spoofing a modern Chrome User-Agent on all web requests

Injecting JavaScript into the OAuth window to remove all Electron detection globals (navigator.userAgent, navigator.webdriver, window.process.versions.electron)

 Please consider reopening and merging my fix to resolve this.
