### ISSUE TITLE
Crash when setting src for invisible webview

### ISSUE THREAD

**Issue by zh99998** [electron/electron#4395]
this code will cause a crash under windows.

``` html
<webview id="xx" src="xxx">
```

then run this in page javascript or chrome console

``` javascript
var element = document.getElementById('xx');
element.src = 'xxxx'
```

then electron process will crash.
only on windows. OSX works well.

**Comment by kevinsawicki** [comment]
What version of Windows are you on and using which version of Electron? Thanks.

**Comment by baconface** [comment]
I can't reproduce this crash on Windows 7 or Windows 8.1 using Electron 0.36.7.

**Comment by kevinsawicki** [comment]
I was unable to reproduce on Windows 10 yesterday.

**Comment by zh99998** [comment]
Windows 10 x64 and Electron 0.36.7.

**Comment by zh99998** [comment]
I found another thing.

if page has a script with 
```javascript
'use strict';
```
then it could happen.

index.html
```html
<webview id="forum" src="https://ygobbs.com"></webview>
<script src="js/app.js"></script>
```
js/app.js
```javascript
'use strict';
```

chrome console
```javascript
document.getElementById('forum').src = 'http://www.bing.com'
```

**Comment by baconface** [comment]
I tried again with the steps and code you provided and still can't reproduce this crash on Windows 7 or Windows 8.1 using Electron 0.36.7.

Only thing I did differently was use npm start with the electron-prebuilt package and didn't use the Windows installer package.

**Comment by zh99998** [comment]
I removed most of functional codes of my project and packaged here:

https://drive.google.com/file/d/0Bw0mhHjNa1PPZkkzblhWSERUemc/view?usp=sharing

1. unzip and run it using 
```bash
electron .
```
2. in chrome console, execute
```javascript
document.getElementById('forum').src = 'http://www.bing.com'
```

**Comment by zcbenz** [comment]
I can reproduce with your example. This is caused by your webview being invisible, if you change the `src` after the webview is shown, the crash will be gone.

Refs #1682.

**Comment by zh99998** [comment]
it's not only caused by invisible. as https://github.com/atom/electron/issues/4395#issuecomment-182860675 , if i remove line 11 of index.html
```html
<script src="js/app.js"></script>
```
or just remove this in js/app.js
```javascript
'use strict';
```

then set src. even it's still invisible, it's not crash

**Comment by baconface** [comment]
This is because it is allowed to be invisible. But if you interact with it while invisible it can't access the DOM object in this case. ```'use strict';``` enforces very strict JavaScript usage. Which is violated by what you are trying to do.

**Comment by baconface** [comment]
Is is also my guess this would require patching Chromium to change. As this is likely by design.

Why would Chromium do this? Well you have to think of it as a web browser. And think of the unnecessary use of resources rendering content that doesn't need rendered. And the potential of loading hidden malicious content.

**Comment by sofianguy** [comment]
Thanks for contributing!

This is an old version that we are no longer supporting. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.
