### ISSUE TITLE
redirect response emits "did-fail-load" event

### ISSUE THREAD

**Issue by cole-dda** [electron/electron#4396]
for version > 0.36.5 
when load a url return redirect，webContents first emit "did-fail-load"(errorCode=-3) ，then emit "did-finish-load"

for version = 0.36.5
only emit "did-finish-load"

**Comment by deepak1556** [comment]
Can confirm the behavior for 303 responses. Related to https://github.com/atom/electron/issues/3471 .

**Comment by aggregatejeff** [comment]
Any update on this? I can certainly work around it by just ignoring errorcode -3, but that's clearly not ideal.

**Comment by bmcminn** [comment]
@aggregatejeff, you mean something like this? https://src.chromium.org/svn/trunk/src/net/base/net_error_list.h

**Comment by CharlieHess** [comment]
We see the same thing during the Slack sign-in flow. We explicitly ignore that error code, but it feels bad. I've clarified the documentation [here](https://github.com/electron/electron/pull/5409).

**Comment by tbo** [comment]
@CharlieHess How exactly do you ignore that error code?

**Comment by ccnokes** [comment]
@aggregatejeff @bmcminn I got tired of constantly looking at that chrome header file for what the error is, so I made: https://github.com/ccnokes/chrome-network-errors.
