### ISSUE TITLE
[Feature Request]: Support of JPEG XL

### ISSUE THREAD

**Issue by t0maz** [electron/electron#43993]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron doesn't support JPEG XL yet.
This image format is now gaining popularity quickly when Apple devices got full support of it since macOS 14 and iOS 17,
displaying it in Safari, sharing and previews in iMessage, opening and editing in Preview and Photos apps etc.

More info about the format: https://jpegxl.info/

### Proposed Solution

Add support of JPEG XL images.

### Alternatives Considered

A kind of workaround accepting files in JPEG XL format and converting it to other already supported format like JPEG?
It's not ideal as standard JPEG is now dated and inferior but with greater support.
Any other alternative solution?

**Comment by brjsp** [comment]
There is a maintained patch restoring jxl support at the [Thorium fork](https://github.com/Alex313031/thorium-libjxl/blob/main/Restore-libjxl-in-M126.patch).

**Comment by codebytere** [comment]
This is something that we will consider once Chromium adds support for it. You're more than welcome to file a request upstream at https://issues.chromium.org

**Comment by t0maz** [comment]
Good news! Chrome is adding support of jxl:
https://groups.google.com/a/chromium.org/g/blink-dev/c/WjCKcBw219k/m/NmOyvMCCBAAJ

**Comment by Pheubel** [comment]
> Good news! Chrome is adding support of jxl: https://groups.google.com/a/chromium.org/g/blink-dev/c/WjCKcBw219k/m/NmOyvMCCBAAJ

To give a status update on this, jxl support seems to be on it's way
https://chromiumdash.appspot.com/commit/8215ebd5eb9d45b42bbc68e1ceff039a319b35d6
