### ISSUE TITLE
[Bug]: Properties on Number (and BigInt) objects do not pass through the preload-renderer boundary

### ISSUE THREAD

**Issue by sparecycles** [electron/electron#44018]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.0 – 34.0.0-beta4

### What operating system(s) are you using?

macOS

### Operating System Version

Sonoma 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Number and BigInt objects (e.g., produced with `new Number(123)` and/or `Object(BigInt(123n))` with additional assigned fields lose those fields when returned from preload methods to renderer code.

I don't expect values to lose fields when passed between preload/renderer isolation boundary, but perhaps this could be addressed with clarifications to documentation (or maybe I missed something).

### preload.js
```js
const { contextBridge } = require("electron");

const bridge = {
  decoratedNumber() {
    return Object.assign(new Number(123), { decoration: 'hello' });
  }
}

contextBridge.exposeInMainWorld('bridge', bridge);

console.log('preload - number', +bridge.decoratedNumber());
console.log('preload - decoration', bridge.decoratedNumber().decoration);
```

### renderer.js
```js
console.log('renderer - number', +window.bridge.decoratedNumber());
console.log('renderer - decoration', window.bridge.decoratedNumber().decoration);
```

### console
<img width="554" alt="image" src="https://github.com/user-attachments/assets/3c340dfb-bb67-49ef-b9ef-6dd7986b0a30">

### Additional Information

Yes, this is a very edgy case.

Note: Additional fields on these kinds of objects are also lost when using `structuredClone()`, not sure if that's related.

**Comment by codebytere** [comment]
Yes - modifying primitives isn't supported by `contextBridge` nor by structured clone. Certain primitives including Number and BigInt use the current V8::Context and can be passed through directly which is significantly more performant than copying them as would be required in order to achieve your above objective.

Changing this to account for modified primitives (which probably isn't something you should be doing anyway!) isn't something we're likely ever going to consider.
