### ISSUE TITLE
[Bug]: The problem of inactive traffic lights not being displayed on macos.

### ISSUE THREAD

**Issue by LANMIN-X** [electron/electron#44034]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.3.1

### What operating system(s) are you using?

macOS

### Operating System Version

macos 15.0 (24A335)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

31.3.1

### Expected Behavior

I created a window without titleBar. When the window is active, the traffic light can be displayed normally, but it is not displayed when it is inactive.
`mainWindow = new BrowserWindow({
    width: 470,
    height: 780,
    show: false,
    titleBarStyle: 'hiddenInset', 
    fullscreenable: false,  `

### Actual Behavior

The traffic light should be gray when inactive, but it is transparent and no longer displayed.

Activity status of my program::
![WX20241001-011128@2x](https://github.com/user-attachments/assets/22f91cfd-54dd-45a4-be1f-62218a5833c7)

Inactive state of my program:
![WX20241001-011142@2x](https://github.com/user-attachments/assets/92513253-b3aa-4f32-9e1a-c871decc2c3f)

Inactive state of other programs:
![WX20241001-012011@2x](https://github.com/user-attachments/assets/a7594653-bc6b-4873-a88a-e9a2c82db143)

**Comment by LANMIN-X** [comment]
**titleBarStyle: 'hiddenInset',** 
I only added this line. The inactive theme's traffic lights work fine in light mode, but they don't appear correctly in dark mode. I can't figure out if I did something wrong or what the issue might be.

**Comment by codebytere** [comment]
@LANMIN-X it's not transparent - it just matches the background color of your application. Another app in light mode with `hiddenInset` and a darker background:

![Image](https://github.com/user-attachments/assets/d4774228-a2af-4435-81dd-00e394fad732)

macOS calculates the contrast itself - there's not much we can do here.

**Comment by LANMIN-X** [comment]
> [@LANMIN-X](https://github.com/LANMIN-X) it's not transparent - it just matches the background color of your application. Another app in light mode with `hiddenInset` and a darker background:
> 
> ![Image](https://github.com/user-attachments/assets/d4774228-a2af-4435-81dd-00e394fad732)
> 
> macOS calculates the contrast itself - there's not much we can do here.

https://github.com/sindresorhus/caprine 

This project can correctly identify the inactive state on a light background. It also uses hiddenInset, but its logic is too complicated. I am a beginner and can’t understand it at all. his code.


**light mode**

![Image](https://github.com/user-attachments/assets/67b292e6-01cf-4c99-94fd-63fd5a043f54)



**dark mode**

![Image](https://github.com/user-attachments/assets/46855a7d-a9f4-462a-8129-129c778f3132)

**Comment by thisislvca** [comment]
Hey @LANMIN-X did you end up finding a solution?
