### ISSUE TITLE
Pi camera is not detected from electron version 12 onwards

### ISSUE THREAD

**Issue by Amit-Pareek-VTS** [electron/electron#44146]
device : Raspberry Pi 4 - 8GB RAMModel B (2018)
my node version ^14.21,  npm ^7.15. 
Getting error **`DOMException: Requested device not found` (From electron version 12 onwards)**

Code : const stream = await navigator.mediaDevices.getUserMedia(constraints);

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Could you please fill out our issue template, so we have the information we might need to debug this without asking as many follow ups? Happy to have one of us take a look when the template is appropriately filled out 🙇‍♀️

**Comment by Amit-Pareek-VTS** [comment]
> Thanks for reporting this issue! Could you please fill out our issue template, so we have the information we might need to debug this without asking as many follow ups? Happy to have one of us take a look when the template is appropriately filled out 🙇‍♀️

I have created the issue template for this https://github.com/electron/electron/issues/44176
