### ISSUE TITLE
但是怎样将主进程选择文件赋值webview里面的网页里面html的input标签呢

### ISSUE THREAD

**Issue by 1937650094** [electron/electron#44143]
> you can set  preload for webview，and then interceptor the click event in preload 

 _Originally posted by @leon9508 in [#43970](https://github.com/electron/electron/issues/43970#issuecomment-2376178474)_

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Could you please fill out our issue template, so we have the information we might need to debug this without asking as many follow ups? Happy to have one of us take a look when the template is appropriately filled out 🙇‍♀️
