### ISSUE TITLE
Add create shortcut API

### ISSUE THREAD

**Issue by adam-lynch** [electron/electron#4414]
In order to use notifications on Windows 8-8.1, we need to create a shortcut. Instead of having to use a native module like [`node-win-shortcut`](https://www.npmjs.com/package/node-win-shortcut), could Electron provide a method? [NW.js does](https://github.com/nwjs/nw.js/blob/00eaaee63f668eae4e65fb812ad3f28d3411393c/src/api/app/app.cc#L154); e.g. `gui.App.createShortcut(process.env.APPDATA + "\\Microsoft\\Windows\\Start Menu\\Programs\\node-webkit.lnk")`

**Comment by adam-lynch** [comment]
Ok this is a bit of a pain. I can't see how anyone has achieved this programmatically.

Native modules are a pain on Windows. That module I linked above fails on install for me. It's not clear how to do this manually. Not even a viable option anyway though. I'd settle for bundling in an `.exe` and calling it with args, but I don't want to have to write C++. The only remaining options I see are:

1. Use the "balloons" notifications from the Tray API (assuming the work fine on Windows 8 too). That's not really nice though.
2. Create custom HTML ones yourself with Electron Windows. Not nice.
3. If you were using something like InnoSetup or NSIS or some other installer, maybe *maybe* they might be able to create a shortcut with an app ID and put it in the right place. This has the downside though that it's only run once. It's nice that it's in your app with NW.js because:
    a: it can tweaked in automatic updates.
    b: you could check if it's there everytime your app starts and if not, create it. So it doesn't matter if the user deletes it. Whereas if you use an installer to do this, it's only do once ever.

**Comment by MarshallOfSound** [comment]
Use the squirrel.windows installer and it will allow you to make a shortcut really easily.  Just follow their example

**Comment by enlight** [comment]
This was discussed recently in https://github.com/atom/electron/issues/4381
For future reference building of native modules is documented in https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by jorangreef** [comment]
It would be great if Electron could create shortcuts on Windows.

At present I am using a few `.vbs` shell scripts if that helps anyone:

### resolve-special-folder.vbs
Resolve the location of a special system folder which is dependent on user language (accepts 1 argument: name of special folder - see https://en.wikipedia.org/wiki/Special_folder - and writes resolved path to stdout):
```
WScript.Echo WScript.CreateObject("Wscript.Shell").SpecialFolders(WScript.Arguments.Item(0))
```

### create-shortcut.vbs
Create a shortcut (accepts 3 arguments: target path, icon location, working directory):
```
set WshShell = WScript.CreateObject("WScript.Shell")
set oShellLink = WshShell.CreateShortcut(WScript.Arguments.Item(0))
oShellLink.TargetPath = WScript.Arguments.Item(1)
oShellLink.IconLocation = WScript.Arguments.Item(2)
oShellLink.WorkingDirectory = WScript.Arguments.Item(3)
oShellLink.Save
```

**Comment by adam-lynch** [comment]
>Use the squirrel.windows installer and it will allow you to make a shortcut really easily. Just follow their example

@MarshallOfSound Good Squirrel examples seem a little hard to find. Is it possible to add the application ID to the shortcut with it? Still, it has the downside of not being in the app code anyway like I said earlier.

Although, in @kevinsawicki says (https://github.com/atom/electron/issues/4381#issuecomment-180507555):

>Yeah, I thought https://github.com/Squirrel/Squirrel.Windows handled this correctly already so I'm not sure if a core API is needed here. I'd be curious what others think.

---

Thanks @enlight. Not sure that native modules doc helps me? I'd be using one, not building one?

---

@jorangreef thanks, am I wrong in saying that doesn't set the app ID?

**Comment by adam-lynch** [comment]
Oh... maybe I can use https://github.com/KochiyaOcean/windows-shortcuts (see https://github.com/atom/electron/issues/4381#issuecomment-180815711)

**Comment by enlight** [comment]
> Not sure that native modules doc helps me? I'd be using one, not building one?

You have to rebuild native modules in order to use them in Electron. If you were using plain old Node you'd also have to rebuild them unless they happened to rely on `node-pre-gyp`.

**Comment by adam-lynch** [comment]
@enlight ugh. [node-win-shortcut](https://www.npmjs.com/package/node-win-shortcut) failing on install is irrelevant so. I could download manually from GitHub and rebuild.

**Comment by adam-lynch** [comment]
Yep,  https://github.com/KochiyaOcean/windows-shortcuts is the way to go. This is the best solution as far as I'm concerned:

```javascript
const electron = require('electron');
const path     = require('path');
const fs       = require('fs');
const platform = require('./platform.js');
const ws       = require('windows-shortcuts-appid');

const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

let mainWindow;

app.on('ready', function() {
  // Typical stuff
  mainWindow = new BrowserWindow({width: 800, height: 600});
  mainWindow.loadURL('file://' + __dirname + '/index.html');

  // Only need to do this for Windows 8, in a packaged app
  if(platform.isWindows8){
    var appId = "com.myCompany.myapp.MyApp";
    app.setAppUserModelId(appId);

    var shortcutPath = process.env.APPDATA + "\\Microsoft\\Windows\\Start Menu\\Programs\\" + app.getName() + ".lnk";
    fs.exists(shortcutPath, function(exists){
      if(exists) {
        // The shortcut already exists, no need to do anything
        return;
      }

      // Create the shortcut
      ws.create(shortcutPath, process.execPath, function(err){
        if(err) throw err;

        // Add the app ID to the shortcut
        ws.addAppId(shortcutPath, appId, function(err){
          if(err) throw err;
          // Ready!
        });
      });
    });
  }
});
```

I'll go add `addAppId` documentation to KochiyaOcean/windows-shortcuts, but Electron should definitely still add a method.

**Comment by ahallicks** [comment]
I just had a play with this and everything works fine, it creates the shortcut beautifully... until I package my app with `electron-installer-windows` to create a Windows installer `.exe` file. It's weird that everything works before doing this. Is there anything special that you think needs to be considered before attempting to creating the `.exe` installer for Windows?

**Comment by ahallicks** [comment]
Belay that, it now works again for some reason. See https://github.com/unindented/electron-installer-windows/issues/30 for more information in case anyone has the same issue.

**Comment by soichih** [comment]
+1 > It would be great if Electron could create shortcuts on Windows [@jorangreef]

I am trying to write a multi-platform application installer / configurator using electron. It would be nice if electron could support shortcut creation on all supported platforms.

**Comment by adam-lynch** [comment]
Nice!
