### ISSUE TITLE
[Bug]: OpenFile dialog freeze/crash

### ISSUE THREAD

**Issue by McBen** [electron/electron#44147]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.5.1  -   33.0-beta8

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Kubuntu 24.04

### What arch are you using?

x64

### Last Known Working Electron version

30.5.0

### Expected Behavior

`dialog.showOpenDialog(mainWindow, {});`
should show a file open dialog.

But since 30.5.1 this won't happen.

### Actual Behavior

I took the [electron/electron-quick-start] as template and added a showOpenDialog :

```
const { app, BrowserWindow, dialog } = require('electron')
const path = require('node:path')

function createWindow() {
  const mainWindow = new BrowserWindow({
    width: 800, height: 600, webPreferences: { preload: path.join(__dirname, 'preload.js')} 
 })

  mainWindow.loadFile('index.html')

// ----------------------------------
  // last working on v30.5.0
  dialog.showOpenDialog(mainWindow, {});
// ----------------------------------
}

```

The open file Dialog won't appear.

Instead I see the process 'kdialog' eating my whole ram until my system becomes unstable.
![Image](https://github.com/user-attachments/assets/17b96642-99b0-47e1-8588-7a5f6ad3aad1)

**Comment by McBen** [comment]
okay, figured out that it depends if I start the app in VS-Code terminal window or in a seperated bash.
need further investigations...

**Comment by yetian** [comment]
I encountered the same issue but I guess the RC is https://github.com/electron/electron/issues/42510
