### ISSUE TITLE
[Bug]: webview show different css than in chrome

### ISSUE THREAD

**Issue by shunmian** [electron/electron#44175]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

8.0.0

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.6 LTS

### What arch are you using?

x64

### Expected Behavior

Should show css correctly in electron `webview` as it does in chrome 

### Actual Behavior

I have an external static web, which shows correctly in chrome as P1 below

![Image](https://github.com/user-attachments/assets/27793335-e0ca-4c84-963d-f71e6e6d8e9c)

When I use `webview` in electron with code 
`
<webview src={url} style={{ width: '100vw', height: '100vh' }} >
`
it shows a different view (the content within the red rectangle) as P2 below

![Image](https://github.com/user-attachments/assets/b2def688-ab5a-4271-8e21-311b1101588d)

It seems electron webview cannot handle some css properly which works fine in chrome.

Any suggestions?

**Comment by codebytere** [comment]
Electron 8 isn't supported and hasn't been in some time. This has been fixed in [currently supported versions](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).
