### ISSUE TITLE
[Bug]: Error [ERR_INTERNAL_ASSERTION]: Code: ERR_MODULE_NOT_FOUND; The provided arguments length (2) does not match the required ones (3).

### ISSUE THREAD

**Issue by InfiniteLoopAlchemist** [electron/electron#44274]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

Sequoia 15.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

33.0.0

### Expected Behavior

the app starts 

### Actual Behavior

Uncaught Exception:
Error [ERR_INTERNAL_ASSERTION]: Code: ERR_MODULE_NOT_FOUND; The provided arguments length (2) does not match the required ones (3).
This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

at assert (node:internal/assert:14:11)
at getMessage (node:internal/errors:594:5)
at new NodeError (node:internal/errors:471:20)
at legacyMainResolve (node:internal/modules/esm/resolve:221:9)
at packageResolve (node:internal/modules/esm/resolve:848:14)
at moduleResolve (node:internal/modules/esm/resolve:934:18)
at defaultResolve (node:internal/modules/esm/resolve:1176:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)

### Additional Information

{
  "name": "hideout-weather",
  "productName": "Hideout Weather",
  "type": "module",
  "version": "0.0.1",
  "description": "hideout weather desktop widget",
  "main": ".vite/build/main.mjs",
  "forge": {
    "packagerConfig": {
      "icon": "src/assets/icons/Hideout-Weather-icon",
      "extraResources": [
        {
          "from": "src/assets/icons",
          "to": "../../assets/icons",
          "filter": [
            "**/*"
          ]
        }
      ]
    }
  },
  "scripts": {
    "start": "electron-forge --trace-deprecation .",
    "dev": "electron-forge start",
    "build": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "clearNode": "rm -rf node_modules package-lock.json",
    "clearBuild": "rm -rf out",
    "lint": "echo \"No linting configured\""
  },
  "devDependencies": {
    "@electron-forge/cli": "^7.5.0",
    "@electron-forge/maker-deb": "^7.5.0",
    "@electron-forge/maker-rpm": "^7.5.0",
    "@electron-forge/maker-squirrel": "^7.5.0",
    "@electron-forge/maker-zip": "^7.5.0",
    "@electron-forge/plugin-auto-unpack-natives": "^7.5.0",
    "@electron-forge/plugin-fuses": "^7.5.0",
    "@electron-forge/plugin-vite": "^7.5.0",
    "@electron/fuses": "^1.8.0",
    "autoprefixer": "^10.4.20",
    "electron": "^33.0.0",
    "eslint": "^9.12.0",
    "eslint-plugin-react": "^7.37.1",
    "postcss": "^8.4.41",
    "tailwindcss": "^3.4.14",
    "vite": "^5.4.9"
  },
  "keywords": [],
  "author": {
    "name": "InfLoopAlchemist",
    "email": "InfLoopAlchemist@gmail.com"
  },
  "license": "MIT",
  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e",
  "dependencies": {
    "astronomy-engine": "^2.1.19",
    "axios": "^1.7.7",
    "cacheable": "^1.8.0",
    "cron": "^3.1.7",
    "dotenv": "^16.4.5",
    "electron-extension-installer": "^1.2.0",
    "electron-squirrel-startup": "^1.0.1",
    "electron-store": "^10.0.0",
    "luxon": "^3.5.0",
    "moment-timezone": "^0.5.46",
    "prop-types": "^15.8.1",
    "react": "^18.3.1",
    "react-color": "^2.19.3",
    "react-dom": "^18.3.1",
    "react-icons": "^5.3.0",
    "react-router-dom": "^6.27.0",
    "react-tooltip": "^5.28.0",
    "suncalc": "^1.9.0",
    "tailwind-scrollbar": "^3.1.0",
    "tz-lookup": "^6.1.25",
    "uuid": "^10.0.0",
    "zips": "^1.1.3"
  }
}

**Comment by InfiniteLoopAlchemist** [comment]
its not electron its self because I got version 33 to work but after updating @electron-forge/plugin-vite I get that error. going to update the others one by one and report back

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
