### ISSUE TITLE
[Bug] Starting a second app which actually opens a window does not accept key inputs

### ISSUE THREAD

**Issue by eneufeld** [electron/electron#44299]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.1

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.5 LTS

### What arch are you using?

x64

### Expected Behavior

I would expect the opened window to behave normally and accept key inputs in input fields.

### Actual Behavior

Starting a second app after the headless start, leads to the window opening as expected but it does not show the key inputs in the input fields.
Attaching a dedicated KeyListener to an element allows to get the key input and output it (e.g on the console).
Keyinput is not working in the devtools neither. But keybinding to open the devtools work. 

### Testcase Gist URL

https://gist.github.com/eneufeld/4a0d67fafe498d66cef1508fea6cf3fe

### Additional Information

Using JSFiddle the window is started directly in the broken state.
But to make the behavior more explicit you can use the minimal example here which has two scripts:
`start` and `start:headless`.
If you just run `start` everything works.
If you run `start:headless` first and then `start` you see the window opening but now in a broken state. The second app is closed.

https://github.com/eneufeld/electron-headless-reproducer

**Comment by eneufeld** [comment]
If you simply pass `--headless` to your Electron app as argument, without further changes, the input is broken as described above.
I don't know who is checking for this argument but ideally there would be some documentation to not use it.

**Comment by georgexu99** [comment]
👋 Thank you for filing an issue! Unfortunately I'm going to go ahead and close this out, as we don't support `--headless` as a feature, hence the lack of documentation 🙇
