### ISSUE TITLE
The release file ffmpeg-v30.3.1-darwin-x64.zip is wrong

### ISSUE THREAD

**Issue by GazeboXu** [electron/electron#44313]
the file url is: [https://github.com/electron/electron/releases/download/v30.3.1/ffmpeg-v30.3.1-darwin-x64.zip](https://github.com/electron/electron/releases/download/v30.3.1/ffmpeg-v30.3.1-darwin-x64.zip), as the name suggestion, it should be x86 arch, but if you unzip the file and use the command `lipo -info libffmpeg.dylib`, it shows that the arch is arm "Non-fat file: libffmpeg.dylib is architecture: arm64".

thanks!

**Comment by codebytere** [comment]
@GazeboXu is this also true for [currently supported releases](https://www.electronjs.org/docs/latest/tutorial/electron-timelines)?

**Comment by jkleinsc** [comment]
Closing as a duplicate of #43076.  @GazeboXu  this issue has been fixed for newer releases. Please upgrade to the latest 30-x-y version (https://github.com/electron/electron/releases/tag/v30.5.1) to resolve your issue.

**Comment by GazeboXu** [comment]
@codebytere , yes, the current release(31.7.3) is ok.

thanks
