### ISSUE TITLE
The main process crashes when changing the parent of browser windows

### ISSUE THREAD

**Issue by SvetozarMateev** [electron/electron#44315]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows Server 2016 1607

### What arch are you using?

x64

### Last Known Working Electron version

24.4.1

### Expected Behavior

The reparent operation should succeed without any interruption to the flow of the application

### Actual Behavior

Electron crashes with access violation exception
```Unhandled exception at 0x00007FF61E10668C (my-app.exe) 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.```

### Additional Information

We are reparenting the browser windows with our own native windows and at some point of the user interaction (it is most likely happening when we change the parent window to a hidden one) electron crashes sporadically with a access violation exception. I have attached the stack trace and can provide more information if required.

I wasn't able to reproduce the issue with Electron Fiddle, but it appears to be related to https://github.com/electron/electron/issues/31812 and https://github.com/electron/electron/issues/31406

![Image](https://github.com/user-attachments/assets/3ca02214-b08f-4f25-aca6-f3a9fd73fafd)

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
