### ISSUE TITLE
build-electron offline

### ISSUE THREAD

**Issue by firstdeepfeel** [electron/electron#44332]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

14.2.9

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 10 version 1909

### What arch are you using?

x64

### Last Known Working Electron version

14.2.9

### Expected Behavior

build successful

### Actual Behavior

When I package an electron in an offline model, I get the error 'electron/packager could not build' Getaddrinfo ENOTFFOUND GitHub. After successfully packaging it on a computer with a network, I copied the npm cache and npm to the internal network computer, as well as the node modules All offline resources are ready.. Due to the need for compatibility with the Win7 system, I switched the Electron version to 14.2.9
/npm WARN config production Use --omit=dev` instead.

added 182 packages in 13m

14 packages are looking for funding
run npm fund for details
App • Bundling app with electron/packager...

App • ⚠️ FAIL electron/packager could not build

RequestError: getaddrinfo ENOTFOUND github.com

undefined

App • ⚠️ FAIL Failed to finalize build (check the log above)`

### Testcase Gist URL

https://codesandbox.io/p/devbox/ywtlc4?file=%2Fpackage.json

### Additional Information

npm WARN config production Use `--omit=dev` instead.

added 182 packages in 13m

14 packages are looking for funding
  run `npm fund` for details
 App • Bundling app with electron/packager...

 App • ⚠️   FAIL  electron/packager could not build

RequestError: getaddrinfo ENOTFOUND github.com

undefined

 App • ⚠️   FAIL  Failed to finalize build (check the log above)

**Comment by firstdeepfeel** [comment]
> Hello [@firstdeepfeel](https://github.com/firstdeepfeel). Thanks for reporting this and helping to make Electron better!
> 
> The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline). If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please update this issue to reflect that version of Electron.
> 
> Now adding the [ blocked/need-info ❌](https://github.com/electron/electron/labels/blocked%2Fneed-info%20%E2%9D%8C) Cannot proceed without more information label for this reason. This issue will be closed in 10 days if the above is not addressed.

Due to the need for compatibility with the Win7 system, I switched the Electron version to 14.2.9

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
