### ISSUE TITLE
utilityProcess fork returns undefined PID

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#44338]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33

### What operating system(s) are you using?

Windows

### Operating System Version

10.0.19045.5011

### What arch are you using?

x64

### Expected Behavior

The forkedProcess.pid should return the process ID.

### Actual Behavior

The forkedProcess.pid is undefined.

### Additional Information

When using utilityProcess.fork() in Electron v33.0.0, the returned forkedProcess.pid is undefined.

**Comment by codebytere** [comment]
@gdavidkov the PID is assigned after the process emits the `spawn` event!

```js
const proc = utilityProcess.fork(/some/path);
proc.on('spawn', () => {
     console.log(child.pid) // will always be a valid number
})

```
