### ISSUE TITLE
[Bug] Behavior changed for middle click window title in gnome 46

### ISSUE THREAD

**Issue by lonix1** [electron/electron#44372]
**ENVIRONMENT:**
linux ubuntu 24.04
gnome 46.0 (with wayland or x11)

**WHAT USED TO WORK:**
I use the mouse middle click (on a window's titlebar) to lower the window - so I can easily cycle through open windows. This setting is set via the shell, or the gnome tweaks tool.

**HOW IT WORKS NOW:**
That changed in when upgrading to gnome 46. It doesn't honor that gnome setting anymore. So a middle click on the titlebar does nothing.

I've experienced this bug in a number of electron-based apps, including vscode.

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Could you please fill out our issue template, so we have the information we might need to debug this without asking as many follow ups? Happy to have one of us take a look when the template is appropriately filled out 🙇‍♀️
