### ISSUE TITLE
Return the selected filter in `dialog.showOpenDialog`  and `dialog.showSaveDialog` methods

### ISSUE THREAD

**Issue by FarSeeing** [electron/electron#44387]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Right now the mentioned methods return only a `filePath` (wrapped in an object) that makes it difficult to differentiate the cases when multiple filters share the same extension (like different formats or different locales).

### Proposed Solution

Add a new field that indicates the selected filter in the return object.

### Alternatives Considered

None so far

### Additional Information

Should be possible at least on Linux - https://docs.gtk.org/gtk3/method.FileChooser.get_filter.html

**Comment by codebytere** [comment]
This would be a significant breaking change that's not cross-platform compatible - while we appreciate the suggestion given the downsides this isn't something we're going to be pursuing at least in the medium term. Should that change, we can revisit this.

**Comment by dyvniy** [comment]
You can add it to linux save dialog simply:
[index01.patch](https://github.com/user-attachments/files/17693253/index01.patch)
But in open file dialog, that uses multy files select, it more dificult - need change interfaces.

**Comment by dyvniy** [comment]
For windows index works too.
```diff
diff --git a/shell/browser/ui/file_dialog_win.cc b/shell/browser/ui/file_dialog_win.cc
index cfc8c6068c..3fcddde7d4 100644
--- a/shell/browser/ui/file_dialog_win.cc
+++ b/shell/browser/ui/file_dialog_win.cc
@@ -157,6 +157,8 @@ static void ApplySettings(IFileDialog* dialog, const DialogSettings& settings) {
   }
 }
 
+unsigned int index = -1;
+
 }  // namespace
 
 bool ShowOpenDialogSync(const DialogSettings& settings,
@@ -209,9 +211,12 @@ bool ShowOpenDialogSync(const DialogSettings& settings,
     if (FAILED(hr))
       return false;
 
+    // can be failed
     paths->push_back(base::FilePath(file_name));
   }
 
+  hr = file_open_dialog->GetFileTypeIndex(&index);
+
   return true;
 }
 
@@ -223,6 +228,7 @@ void ShowOpenDialog(const DialogSettings& settings,
     auto dict = gin::Dictionary::CreateEmpty(promise.isolate());
     dict.Set("canceled", !success);
     dict.Set("filePaths", result);
+    dict.Set("index", index);
     promise.Resolve(dict);
   };
   dialog_thread::Run(base::BindOnce(ShowOpenDialogSync, settings),
@@ -258,6 +264,8 @@ bool ShowSaveDialogSync(const DialogSettings& settings, base::FilePath* path) {
   if (!SUCCEEDED(hr))
     return false;
 
+  hr = file_save_dialog->GetFileTypeIndex(&index);
+
   *path = base::FilePath(result_path);
   CoTaskMemFree(result_path);
 
@@ -272,6 +280,7 @@ void ShowSaveDialog(const DialogSettings& settings,
     auto dict = gin::Dictionary::CreateEmpty(promise.isolate());
     dict.Set("canceled", !success);
     dict.Set("filePath", result);
+    dict.Set("index", index);
     promise.Resolve(dict);
   };
   dialog_thread::Run(base::BindOnce(ShowSaveDialogSync, settings),
```
