### ISSUE TITLE
[Bug] unable to get `context-menu` event when using `-webkit-app-region: drag`

### ISSUE THREAD

**Issue by bpasero** [electron/electron#44386]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

15

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

27

### Expected Behavior

An element with `-webkit-app-region: drag` should still receive context menu events.

### Actual Behavior

No `context-menu` event fires.

### Additional Information

This is a regression from maybe Electron 27 or 28, where all mouse events used to work.

**Comment by codebytere** [comment]
@bpasero I tracked this to https://github.com/electron/electron/pull/41256 - I'm considering the best path forward but while the root cause is different the solution seems to be similar to the original bug, e.g. patching `BridgedContentView`, which brings its own significant drawbacks 🤔

**Comment by bpasero** [comment]
@codebytere is there any chance this fix only works on macOS and Windows, but not Linux?

**Comment by bpasero** [comment]
Created https://github.com/electron/electron/issues/45301 for Linux
