### ISSUE TITLE
Fcitx5(Wayland): Redundant extra Character inserted when using fcitx5 long press

### ISSUE THREAD

**Issue by liz3** [electron/electron#44399]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.2

### What operating system(s) are you using?

Other Linux

### Operating System Version

Arch linux, kernel 6.11.4-zen1-1-zen, wm: hyprland: v0.44.1

### What arch are you using?

x64

### Last Known Working Electron version

- Unknown

### Expected Behavior

When long pressing a character, it should be inserted and then be marked with the fcitx5 special accents menu popping up and replacing it after choosing an accent.

### Actual Behavior

Unless the input is empty, it occurs that the character pressed is added, added *again* and the last addition is then marked as replacement by fcitx5. So for example if you have the input value `How ` and wanting to add `ä`, you will end with `How aä`, note again the `How ` is prepended since if the input is empty, i.e the first character is being inserted the bug does not occur.

An error is printed whenever this happens, though i do believe this is coming from chromium/blink NOT electron source:
```
[475360:1025/024801.110327:ERROR:wayland_input_method_context.cc(762)] The deletion range needs to cover whole selection range.
```

### Testcase Gist URL

https://gist.github.com/liz3/611ddb942dfdd9f32b6ea40de9ec9cbb

### Additional Information

**Note**: I have added a description to the fiddle gist giving the instructions for the fcitx5 setup this bug needs.
I have only noticed this issue with electron based applications, i.e discord, signal and so on.

**Comment by mlaurencin** [comment]
Thanks for reaching out! Given the error that is produced, there is a good chance this is actually a problem upstream in Chromium rather than from Electron. If you can reproduce this issue with Chrome as well, then it would be best to go ahead and file this issue with them instead. 

I'm going to mark this as `blocked/need-info` for now. If you are not able to recreate this bug in Chromium, feel free to update this issue. If there is no response, this issue will be closed in 10 days.

**Comment by liz3** [comment]
> Thanks for reaching out! Given the error that is produced, there is a good chance this is actually a problem upstream in Chromium rather than from Electron. If you can reproduce this issue with Chrome as well, then it would be best to go ahead and file this issue with them instead.
> 
> I'm going to mark this as `blocked/need-info` for now. If you are not able to recreate this bug in Chromium, feel free to update this issue. If there is no response, this issue will be closed in 10 days.

Using `Version 130.0.6723.69 (Official Build) Arch Linux (64-bit)` and using the provided [index.html from the fiddle gist](https://gist.github.com/liz3/611ddb942dfdd9f32b6ea40de9ec9cbb#file-index-html) the issue does **not** happen when using `chromium index.html` but it **does** happen when using command: ` chromium --gtk-version=4 index.html`
