### ISSUE TITLE
showOpenDialog won't show files with uppercase letters in their extensions

### ISSUE THREAD

**Issue by gtritchie** [electron/electron#44398]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.7.2 (but repros in any currently supported version I've tried)

### What operating system(s) are you using?

Ubuntu

### Operating System Version

22.04.5 LTS

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

Don't know if it ever did

### Expected Behavior

When providing file extensions via a filter for `showOpenDialog`, case differences in extensions on a case-sensitive filesystem should be obeyed. Create three files in a folder on Linux:

```bash
mkdir ~/test
cd ~/test
touch one.RProj
touch two.Rproj
touch three.rproj
```

Using the filter `{ name: 'Projects', extensions: ['RProj', 'Rproj'] }` for Open File dialog, browse to that folder. Expect to see "one.RProj" and "two.Rproj", but not "three.rproj".

### Actual Behavior

Only "three.rproj" is displayed. The other two cannot be seen.

### Testcase Gist URL

https://gist.github.com/b25f95b0efdcb1a26958a0db1079df3b

### Additional Information

Curiously, this works for a shorter extension; I tried a filter of `extensions: ['r']` and that shows me files with both `.R` and `.r` extensions. Using `rproj` as the filter extension, however, only reveals `foo.rproj`, not `foo.Rproj` or `foo.RProj`.

**Comment by Redalamr** [comment]
I suggest checking the file filters in showOpenDialog. Make sure to include both lowercase and uppercase extensions (e.g., ['rproj', 'Rproj']). Also, confirm you're using the latest version of Electron, as updates might fix this issue

**Comment by mlaurencin** [comment]
@gtritchie You mention testing for this on v31.7.2 and other supported versions. Can you specify which version in the 33 release line you tested? 

I'm adding the `blocked/need-repro` label for now.

**Comment by gtritchie** [comment]
All of them. I went through the entire list in electron-forge, up to and including 33.0.2.

Also repros in 34.0.0-alpha.5.

**Comment by codebytere** [comment]
@gtritchie this seems unfortunately like something Chromium has chosen to do on purpose: https://source.chromium.org/chromium/chromium/src/+/main:ui/gtk/select_file_dialog_linux_gtk.cc;l=324-328;drc=dbb4b2f7e4fec41b92b627c81416c265677787ce;bpv=1;bpt=1

I'd recommend filing a bug upstream - we'd inherit the fix/change if/when they agree to change it.

**Comment by gtritchie** [comment]
Thanks, confirmed I can repro in Chromium, and opened https://issues.chromium.org/issues/376094901.

**Comment by georgexu99** [comment]
Closing as we will inherit the fix when Chromium fixes this upstream
