### ISSUE TITLE
[BUG]: Linux x64 executable file size is abnormal

### ISSUE THREAD

**Issue by pompurin404** [electron/electron#44409]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.2

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Ubuntu 24.04

### What arch are you using?

x64

### Last Known Working Electron version

33.0.1

### Expected Behavior

The file [electron-v33.0.2-linux-x64.zip](https://github.com/electron/electron/releases/download/v33.0.2/electron-v33.0.2-linux-x64.zip) is more than twice the size of the other files.The size of the electron executable file inside is nearly 1GB.

### Actual Behavior

File size is comparable to others

**Comment by EvidentlyCube** [comment]
This is something that must've happened between `23.1.3` and current version - just today I updated Electron and the final size for my game rose from 350mb to 1.1GB.

Built using Electron `23.1.3`:
![Image](https://github.com/user-attachments/assets/902b35f1-0b95-4a70-8819-dbe0d0a15650)

Built using Electron `33.0.2`:
![Image](https://github.com/user-attachments/assets/fa9156bc-af8d-4834-be15-b8974eb45080)

(Other changes in the project between the builds would account to <1mb)

**Comment by ckerr** [comment]
Yep, https://github.com/electron/electron/releases/download/v33.0.2/electron-v33.0.2-linux-x64.zip has an electron binary size of `178M`.  https://github.com/electron/electron/releases/download/v33.0.2/electron-v33.0.2-linux-x64.zip has an electron binary size of `1.1G`.

**Comment by convertcompany** [comment]
I've noticed the same issue runing electron v33.0.2, but when i downgrade to v32.1.2 it seems to bundle normally again, ~180mb

**Comment by jkleinsc** [comment]
This issue has been resolved for the latest 33 release, 33.1.0: https://github.com/electron/electron/releases/tag/v33.1.0
