### ISSUE TITLE
[Documentation request] Explain why someone might enable the fuse `loadBrowserProcessSpecificV8Snapshot`

### ISSUE THREAD

**Issue by nikwen** [electron/electron#44450]
The [documentation](https://www.electronjs.org/docs/latest/tutorial/fuses#loadbrowserprocessspecificv8snapshot) of the fuse `loadBrowserProcessSpecificV8Snapshot` does not explain in which cases it would make sense to enable the fuse, i.e. why someone would want the browser process to use a separate V8 snapshot or what benefits and drawbacks that brings with it.

It would be great if that could be documented.

**Comment by nilaygit-10721** [comment]
can you assign me this issue?
