### ISSUE TITLE
shell.openExternal does not give focus to Firefox and Safari on macOS

### ISSUE THREAD

**Issue by ravicious** [electron/electron#44457]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.2

### What operating system(s) are you using?

macOS

### Operating System Version

Sonoma 14.7

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

After executing `shell.openExternal("https://example.com")`, Electron opens the website in the default browser and the focus is given to the browser.

### Actual Behavior

After executing `shell.openExternal("https://example.com")`, Electron opens the website in the default browser, but the focus remains on the app itself. This is the case for Firefox and Safari, but not for Chrome.

### Testcase Gist URL

https://gist.github.com/ravicious/ee7ee48d85ca36c10e069017b425b2d9

Click the link to example.com to reproduce this behavior.

### Additional Information

This bug has been reported (#18293) and then fixed (#18657) in the past.

**Comment by georgexu99** [comment]
Closing this issue, fixed with 
https://github.com/electron/electron/pull/44408
