### ISSUE TITLE
Clicking a MenuItem with role "about" on MacOS won't focus the About window

### ISSUE THREAD

**Issue by joshleaves** [electron/electron#44462]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.2

### What operating system(s) are you using?

macOS

### Operating System Version

macOs Sonoma 14.7

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

My app has a tray icon and menu, with a `{ role: 'about' }` MenuItem.

While focused anywhere else, when clicking on this "About MyApp" menu item, I expect the native "About" window to be focused.

### Actual Behavior

My app has a tray icon and menu, with a `{ role: 'about' }` MenuItem.

While focused anywhere else, when clicking on this "About MyApp" menu item, the native "About" windows appears unfocused somewhere in my windows list.

(Note: My own app and the gist I provided are tray-only apps, but I also made sure that the behaviour was the same when the app had windows.)

### Testcase Gist URL

https://gist.github.com/joshleaves/19a5c32b901ac6b3e3fe8d5a015fd0d2

### Additional Information

This can be easily circumvented developer-side by replacing `{ role: "about" }` with the following code:
```
{
  label: "About MyApp",
  click: () => {
    app.showAboutPanel()
    app.focus()
  }
}
```

However, in this case, I believe it's a gotcha for the expected behaviour of the "about" role, and were it not for me thoroughly checking through all my opened windows, I would still be wondering what I did wrong.

I've given a quick look through the electron code, and it seems that adding `app.focus()` on [lib/browser/api/menu-item-roles.ts line 29](https://github.com/electron/electron/blob/9fc94a162bed056daea0324ca878f33061484cb0/lib/browser/api/menu-item-roles.ts#L29) would bring about the required change. If that's okay with you, I would like to provide this change.

Thank you for your hard work

**Comment by georgexu99** [comment]
Hey @joshleaves , thanks for filing this issue. Unfortunately this is a limitation of the underlying native API that Electron uses and is the bahaviour many other apps, so Electron for now will keep the standard. However users can implement auto-focusing behaviour if needed within their app/native code. 🙇
