### ISSUE TITLE
Mouse Events Malfunction When alwaysOnTop is Enabled

### ISSUE THREAD

**Issue by oknesar** [electron/electron#44474]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.2

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sonoma 14.5 (23F79)

### What arch are you using?

arm64 (including Apple Silicon)

### Description
When the `alwaysOnTop` window parameter is set to `true`, the application intermittently fails to correctly process mouse events in specific scenarios. Specifically, if another window is dragged over the main application window and released, the main window stops responding to certain mouse events until the cursor is moved outside the window boundaries and then brought back in.

### Expected Behavior

The main application window should handle all mouse events consistently, regardless of the alwaysOnTop parameter or interactions with other windows on the screen.

### Actual Behavior

With alwaysOnTop enabled, after dragging and releasing another window over the main window, the main window stops responding properly to mouse events. It may register clicks but not handle hover effects until the cursor is moved outside and re-enters the window.

### Testcase Gist URL

[https://gist.github.com/61b7d3d647ea81fc018fa45f83ccfcf3](https://gist.github.com/61b7d3d647ea81fc018fa45f83ccfcf3)

### Steps to Reproduce

1. Set the main application window parameter alwaysOnTop to true.
2. Launch the application.
3. Open another window on the screen, ensuring its boundaries **do not** overlap with the main window.
4. Begin dragging the second window across the main window.
5. **Release the dragged window over the main application window.** (Due to alwaysOnTop being enabled, the second window will be partially or fully obscured by the main window.)
6. Observe that the main window will not correctly respond to mouse events, such as hover effects, until the mouse cursor is moved outside the window and then brought back in.

### How it looks
https://github.com/user-attachments/assets/747d0e01-646a-41f3-b9dc-f77fc04b5654

### Setup
I have the same issue on a big project but for simplicity, the video was recorded with the basic template from `npm init electron-app@latest my-app -- --template=vite-typescript`

### index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello World!</title>

  </head>
  <body>
  <div class="wrapper">
    <div class="block"></div>
    <div class="block"></div>
    <div class="block"></div>
    <div class="block"></div>
    <div class="block"></div>
    <div class="block"></div>
    <div class="block"></div>
    <div class="block"></div>
    <div class="block"></div>
  </div>
    <script type="module" src="/src/renderer.ts"></script>
  </body>
</html>
```

### index.css
```css
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica,
    Arial, sans-serif;
  margin: auto;
  max-width: 38rem;
  padding: 2rem;
}

.wrapper {
  display: inline-grid;
  grid-template-columns: repeat(3, auto);
  gap: 20px;
}

.block {
  width: 100px;
  height: 100px;
  background-color: blue;

  &:hover {
    background-color: red;
  }
}
```

### main.ts
```typescript
import { app, BrowserWindow } from 'electron';
import path from 'path';

declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    x: 0,
    y: 0,
    alwaysOnTop: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
    },
  });

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`));
  }

  // Open the DevTools.
  mainWindow.webContents.openDevTools({mode: "detach"});
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
```

**Comment by oknesar** [comment]
Hello! Sure. Here is the testcase [gist](https://gist.github.com/61b7d3d647ea81fc018fa45f83ccfcf3). Please let me know if there's anything else needed.

**Comment by georgexu99** [comment]
Hey @oknesar , thanks for filing an issue- unfortunately this is a limitation of the underlying native API that Electron uses.

**Comment by oknesar** [comment]
Hey @georgexu99, could you share some details about what API Electron uses and what causes that state? Our team is trying to find a workaround for this problem.

**Comment by georgexu99** [comment]
SetAlwaysOnTop() adjusts the z_order within the [views widget](https://chromium.googlesource.com/chromium/src/+/master/docs/ui/views/overview.md)
