### ISSUE TITLE
When browserView is not visible, document.hidden is false on macos and true on windows

### ISSUE THREAD

**Issue by wukong1995** [electron/electron#44542]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.2.2

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sequoia 15.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

none

### Expected Behavior

A browserWindow has multiple browserViews, such as A, B, and C.
Use `browserWindow.setTopBrowserView(A)` to put A on top, and B C is covered and invisible.
It is expected that the value on macos/windows is the same, `false`

### Actual Behavior

on MacOS, when `document.hidden` is executed in B, it is `false`,
on Windows it is `true`.

### Testcase Gist URL

https://gist.github.com/wukong1995/5c173c24e6d8429f96d0e9d515f201aa

**Comment by dsanders11** [comment]
`BrowserView` has been deprecated in favor of [`WebContentsView`](https://www.electronjs.org/docs/latest/api/web-contents-view), can you please check if this issue still occurs using the new API? You can use `addChildView` to move a `WebContentsView` on top instead of `setTopBrowserView`.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
