### ISSUE TITLE
segfault when moving WebContentsView between BrowserWindows

### ISSUE THREAD

**Issue by Kilian** [electron/electron#44571]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33, 34

### What operating system(s) are you using?

Ubuntu

### Operating System Version

23.04

### What arch are you using?

x64

### Expected Behavior

When moving WebContentsViews between different browser windows, the app doesn't crash

### Actual Behavior

When moving WebContentsViews from BrowserWindow A to BrowserWindow B and back to BrowserWindow A, the app crashes. Going just from A BrowserWindow A to BrowserWindow B works, but then back to A segfaults.

### Testcase Gist URL

https://gist.github.com/Kilian/8014d47a193a8f66b05f490def934166

**Comment by georgexu99** [comment]
@Kilian is there a last known version?

**Comment by Kilian** [comment]
e29 fails on this line:

```
const contentsView = new WebContentsView();
```
with
```sh
(node:2038244) UnhandledPromiseRejectionWarning: TypeError: Insufficient number of arguments.
    at createWindow (/tmp/electron-fiddle-2030700-MSoL9sQJYrOk/main.js:21:24)
    at /tmp/electron-fiddle-2030700-MSoL9sQJYrOk/main.js:43:3
```
I can't find the webcontentsview docs in the 29 branch, so I don't know if there were any required arguments at that point.

It first started crashing in 30.0.0-beta.8, though in 30.0.0-beta.7 and earlier there is no webcontentsview visible but there is also no error visible like above.

**Comment by mlaurencin** [comment]
WebContentsView was [reverted in v29](https://github.com/electron/electron/pull/41361), so that is why you cannot find any docs in that branch. If it started crashing in a v30, then it has basically been crashing from the start from the looks of things.

**Comment by estoykov** [comment]
I hit the same issue and the solution was to remove the view from its current parent and then add it to the new parent.
It complicated our code a bit, but solved the problem.

**Comment by Kilian** [comment]
@estoykov do you have a code example?

I have an different fiddle here that first removes the webcontentsview but it still crashes: https://gist.github.com/Kilian/8f0365a3c962b4d5927f2c21284fb1e6

**Comment by estoykov** [comment]
Well, may be I miss leaded you as our structure is a bit more complex - we need to have more than one view in our containers, so the flow is something like this:
- create BrowserWindow
- create rootView = new View()
- browserWindow.setContentView(rootView)
- create multiple "hosts" which are simply Views, i.e.
- host1 has rootView = new View()
- host2 has rootView = new View()
- put host1 and host2 rootVews in the BrowerWindow content rootView 
- and then we move some other view from host1 and host2 rootView - it crashed before when added to host1, then host2 and then back to host1 - removing from the current host root view before adding to the new one solved the problem

Changing BrowserWindow content view comes with an additional processing - you need to track this content view (View in my case) bounds change and re-pos/re-size the real content (WebContentsView) if any, ditto for the hosts and their content...
