### ISSUE TITLE
Electron could not be installed

### ISSUE THREAD

**Issue by AhmedBHK2** [electron/electron#44582]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.2

### What operating system(s) are you using?

Ubuntu

### Operating System Version

18.04

### What arch are you using?

x64

### Expected Behavior

npm install --save-dev electron@latest must install electron as dev dependency

### Actual Behavior

Installation stuck since electron is using package called boolean which is deprecated

**Comment by AhmedBHK2** [comment]
` npm install --unsafe-perm electron@latest
npm WARN deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm ERR! path /home/bhk/Perso/electron/IMAGE-SHRINK/node_modules/electron
npm ERR! command failed
npm ERR! signal SIGINT
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bhk/.npm/_logs/2024-11-05T20_49_56_881Z-debug-0.log
`

**Comment by yuiyideyui** [comment]
aha me too

**Comment by SunboX** [comment]
#metoo :(

**Comment by karlpokus** [comment]
Try bumping nodejs https://github.com/nodesource/distributions/blob/master/README.md

**Comment by SunboX** [comment]
No, it seems that Electron for Windows on Arm64 / Apple Silicon ist not available

**Comment by wongzigii** [comment]
I can confirm that this issue happend in macOS too.

**Comment by SunboX** [comment]
@codebytere There is a task! Provide a build for Windows on ARM64 please so it can be installed on Windows running in Parallels on new Apple hardware!

**Comment by shyandsy** [comment]
nobody help to fix it util 2025.12.22?
