### ISSUE TITLE
`minimize` event not triggered in macOS Stage Manager mode

### ISSUE THREAD

**Issue by magic-akari** [electron/electron#44586]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

all versions

### What operating system(s) are you using?

macOS

### Operating System Version

15.1 (24B83)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

never

### Expected Behavior

The `minimize` event should be triggered when the user minimizes the window, or a new event should be introduced.

### Actual Behavior

nothing happened

**Comment by magic-akari** [comment]
https://gist.github.com/magic-akari/d8a097aa81f05829d722229e4ac1eb76

**Comment by codebytere** [comment]
Unfortunately there's nothing that we can do on our end about this. Apple has not exposed any API for interacting with Stage Manager or even checking whether it's active - the native system that are sent when a window is minimized in all other cases simply aren't sent. You're welcome to open a bug report against Apple, and if something changes we can revisit this.
