### ISSUE TITLE
Breaking change in `webUtils.getPathForFile()` (maybe due to new MacOS filesystem security?), `File` object on drag/drop event fails to resolve absolute path (still works with `<input type="file">`)

### ISSUE THREAD

**Issue by danielweck** [electron/electron#44600]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.0

### What operating system(s) are you using?

macOS

### Operating System Version

Sequoia 15.1 (maybe older versions too)

### What arch are you using?

x64

### Expected Behavior

`File` object on drag/drop event should resolve to absolute path using `webUtils.getPathForFile()` (like `<input type="file">`)
 (maybe due to new MacOS filesystem security?),

### Actual Behavior

`File` object on drag/drop event resolves to empty absolute path when using `webUtils.getPathForFile()`.
`<input type="file">` still works fine, this seems to be a breaking change that applies to Electron versions [30...33] and probably due to some MacOS filesystem security (?) as this was working at some point before I upgraded to Sequoia 15.1

### Additional Information

I am trying to build a repro test case using Electron Fiddle...

**Comment by danielweck** [comment]
Closing. I am unable to reproduce with ElectronFiddle, so the regression bug must have arisen from somewhere else. I will report back here when I figure this out! :)

**Comment by danielweck** [comment]
We're using https://www.npmjs.com/package/react-dropzone
The fix was to pass the`getFilesFromEvent` prop to the `<DropZone>` component and to simply return `Array.from(ev.dataTransfer.files)` ... go figure :)

**Comment by steveoh** [comment]
> console.log(require("electron").webUtils.getPathForFile(ev.dataTransfer.files[0]));

I had to move this to the context bridge and pass the file through which is now null. Are you still able to run/import webUtils from the renderer? I'm not able to import that without error.
