### ISSUE TITLE
[Feature Request]: Upgrade to Node 22 LTS

### ISSUE THREAD

**Issue by mleonhard-notion** [electron/electron#44630]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

NodeJS v22 began active LTS support on 2024-10-29 with version 22.11.0.  See https://github.com/nodejs/release?tab=readme-ov-file#nodejs-release-working-group .

My organization is upgrading our backend and test runners to Node 22.  We would like to use an Electron version that also uses Node 22, so we can run our desktop tests with the same version of Node that they will run on in production.

### Proposed Solution

Upgrade to [Node 22.11.0 LTS](https://www.npmjs.com/package/node/v/22.11.0).

### Alternatives Considered

We could change our test runners to run desktop tests with Node 20 and run backend tests with Node 22.

### Additional Information

Thanks for making Electron! :)

**Comment by MarshallOfSound** [comment]
Per [release policy](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#nodejs-version-support) Electron is actively updating **main** to track the latest lts --> https://github.com/electron/electron/pull/44597

Once it relands in `main` it will go out in the _next_ release branch of Electron which should be Electron 35 (maybe).

If you truly want to run your tests in a version of node that matches the underlying Electron version, you should probably just use Electron itself to run the tests 🤷. i.e. use `ELECTRON_RUN_AS_NODE=1 electron ./my-test-runner`
