### ISSUE TITLE
WebContentsView remains stuck onscreen after a WebContentsView is removed

### ISSUE THREAD

**Issue by Hans-Halverson** [electron/electron#44652]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.7.4

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sonoma 14.7.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

31.7.3

### Expected Behavior

After removing a WebContentsView with `removeChildView` I expect that further adding/removing WebContentsView will show/hide those other WebContentsViews.

### Actual Behavior

Instead a WebContentsView appears to be stuck onscreen and adding/removing WebContentsViews stops working.

### Testcase Gist URL

https://gist.github.com/Hans-Halverson/faaacef5fa45df246f1a76112b100ddb

### Additional Information

I think this tracks back to the changes to WebContentsView removal in https://github.com/electron/electron/pull/44599. I can confirm that the repro gist shows no bug on 31.7.3 but shows the bug on 31.7.4. The only non-Chromium update in between is https://github.com/electron/electron/pull/44599 according to https://releases.electronjs.org/release/compare/v31.7.3/v31.7.4

Included is a small Electron fiddle link that shows this issue - toggling between two WebContentsViews with addChildView and removeChildView breaks in 31.7.4.

Given that this PR was also backported to 32, 33, and 34 I expect this issue will start showing up in those versions too, they just haven't had a release with this PR included yet.

**Comment by codebytere** [comment]
@Hans-Halverson as it turns out, IDs for a given `View` aren't unique nor automatically assigned, so logic added in https://github.com/electron/electron/pull/44599 failed because it incorrectly matched IDs and then removed all the children. Views can be compared directly (and should be!) which will fix this. PR up soon!
