### ISSUE TITLE
Spellchecker dictionary is initialized without downloading the files specified in `setSpellCheckerDictionaryDownloadURL`

### ISSUE THREAD

**Issue by mli-pason** [electron/electron#44668]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.2

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Ubuntu 20.0.4

### What arch are you using?

x64

### Last Known Working Electron version

27.0.2

### Expected Behavior

When the app loads, Electron downloads the custom dictionary files then initialize.

### Actual Behavior

After `setSpellCheckerDictionaryDownloadURL` gets called, the event listener for `spellcheck-dictionary-download-begin` never fires, but the listener for `spellcheck-dictionary-initialized` fires instead.

### Additional Information

I've read through the guide and related github issues carefully so I don't think I missed any steps here.

I downloaded the `hunspell_dictionaries.zip` from the Electron release files, then replaced some of them with custom bdic files. The bdic files are generated by `convert_dict` tool mentioned on this page: https://www.chromium.org/developers/how-tos/editing-the-spell-checking-dictionaries/, I would assume they're valid. The names of the custom bdic files match the ones in Electron exactly.

Uploaded upper and lower case version of every file to the target url, verified the url can be accessed by the Electron app, since it has been using the parent url directory for a long time. Also added spellchecker-download event listeners, if the url is invalid, I would expect to see some log messages.

The OS language is set to EN-US, also set language to EN-US for spellchecker.

Calling `setSpellCheckerDictionaryDownloadURL` in `createWindow` function, it seems like the spellchecker dictionary gets initialized right after the app loads, but I'm not sure when the downloading should happen.

Deployed to Windows 10 system, same issue presists.

**Comment by MarshallOfSound** [comment]
The dictionaries are cached, if they've ever been downloaded before (even from a different URL) they will be used from the cached location. Ensure you clear local disk before testing this

**Comment by Mynini** [comment]
> The dictionaries are cached, if they've ever been downloaded before (even from a different URL) they will be used from the cached location. Ensure you clear local disk before testing this

You might be right. I ran an open-source software, and the package initially built by the author did not support Rosetta mode. I couldn't open it on my M2 Pro, so I contacted the author and asked him to export a package that supports Rosetta mode. However, I still couldn't open it on my machine. I sent the package to my colleagues at work, and they were able to open it (Note: They were using it for the first time after downloading and installing the package). Only I couldn't open it.

Out of options, I pulled the source code of the software and ran it locally, but it threw the same error mentioned above. I also tried creating an empty Electron project, which worked fine.

I will go back and clear the cache on my laptop to see if it helps, and then provide feedback on whether it was effective.

**Comment by mli-pason** [comment]
> The dictionaries are cached, if they've ever been downloaded before (even from a different URL) they will be used from the cached location. Ensure you clear local disk before testing this

Could you point me to where the dictionaries get cached? I tried to delete the Cache and Dictionaries folders under the electron app, but the `spellcheck-dictionary-download-begin` event is still not being dispatched.
