### ISSUE TITLE
Frameless macOS window triggers textured type is deprecated

### ISSUE THREAD

**Issue by lutzroeder** [electron/electron#44688]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.0

### What operating system(s) are you using?

macOS

### Operating System Version

15.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

15.1

### Expected Behavior

on macOS, creating a `BrowserWindow` with `frame: false` is causing a warning that `textured` window type is deprecated.

**Steps:**
1. Download [repro.zip](https://github.com/user-attachments/files/17787737/repro.zip)
2. `npm install`
3. `npm start`

**Output:**
```bash
~/Projects/electron-quick-start: npm start

> electron-quick-start@1.0.0 start
> electron .

(node:81668) DeprecationWarning: The 'textured' window type is deprecated and will be removed
(Use `Electron --trace-deprecation ...` to show where the warning was created)
```

#43125 @ckerr @codebytere

### Actual Behavior

No deprecation warning is shown.

**Comment by codebytere** [comment]
@qinfeng0214 It's been functionally a no-op for a while (see https://chromium-review.googlesource.com/c/chromium/src/+/4300751). We deprecated this because it's being removed by Apple in a future version - there's nothing we can do about it.
