### ISSUE TITLE
Re-add unbundling of Node.js dependencies

### ISSUE THREAD

**Issue by selfisekai** [electron/electron#44691]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Linux distributions have guidelines on using distro-provided dependencies, rather than compiling them statically in, such as this one: https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies

Chromium has its own tools for this in `//build/linux/unbundle`, but Node.js introduces more deps. Some are shared with Chromium, like zlib, where gn workflow uses the same `//third_party/zlib`, so unbundling zlib with Chromium tools works.

Electron handles that as of 34-x-y, but this is now gone from main since it switched to gn buildscripts from Node.js repo.
https://github.com/electron/electron/blob/9bd442fb623e8f6ee43e352a7da782fe9bd007bc/patches/node/build_add_gn_build_files.patch#L69-L73

### Proposed Solution

Re-implement the previous solution: build switches to use dependencies from pkg-config.

### Alternatives Considered

None

### Additional Information

not sure how exactly should it look like now with the upstream/downstream gn workflow split and partial gyp reuse

**Comment by codebytere** [comment]
@selfisekai I'll open an upstream PR to re-add this when I have some time!
