### ISSUE TITLE
`shell.readShortcutLink` crashes when reading some links on Windows

### ISSUE THREAD

**Issue by dlon** [electron/electron#44752]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11 version 23H2

### What arch are you using?

x64

### Last Known Working Electron version

31.7.5

### Expected Behavior

We should be able to handle the error, if reading the link fails.

### Actual Behavior

An (SEH) exception is raised and the process exits:

```
[9572:1120/092034.785:ERROR:crashpad_client_win.cc(868)] not connected

Electron exited with code 4294930435.
```

### Testcase Gist URL

https://gist.github.com/dlon/fedbd11d9f66e212674511e10a69ad8b

### Additional Information

The gist assumes that WezTerm is installed.

Here is a (partial) stack trace from the Mullvad app that is triggered by this issue:

```
Mullvad VPN.exe!base::win::ResolveShortcutProperties(const base::FilePath & shortcut_path, unsigned int options, base::win::ShortcutProperties * properties) Line 299
Mullvad VPN.exe!`anonymous namespace'::ReadShortcutLink(gin_helper::ErrorThrower thrower, const base::FilePath & path) Line 154
```

In Chromium, it occurs on the following line: https://chromium.googlesource.com/chromium/src/base/+/master/win/shortcut.cc#299.

One difference between the chromium versions is that the new version throws (via `NOTREACHED()`) and does not return false in `ResolveShortCutProperties`: https://chromium.googlesource.com/chromium/src/+/refs/tags/126.0.6478.234/base/win/shortcut.cc#300

```
        default:
+         NOTREACHED() << "Unexpected variant type: " << pv_app_id.get().vt;
-         NOTREACHED_IN_MIGRATION()
-             << "Unexpected variant type: " << pv_app_id.get().vt;
-         return false;
```

**Comment by codebytere** [comment]
This is likely a result of https://chromium-review.googlesource.com/c/chromium/src/+/5795485 and similar CLs, which are part of an upstream effort to make `NOTREACHED` fatal instead of debug-fatal.

**Comment by dlon** [comment]
Hello again!

There are issues with other shortcuts now. E.g. Slack:

```
const { shell } = require('electron');

shell.readShortcutLink(`${process.env.AppData}/Microsoft/Windows/Start Menu/Programs/Slack Technologies Inc/Slack.lnk`)
```

I've reproduced the above on v33.3.1, as well as the latest beta.

Should this issue be reopened or shall I open another one?
