### ISSUE TITLE
insert menu before help menu ( role: 'help' ) will make the search bar show in the wrong place in OSX

### ISSUE THREAD

**Issue by jwu** [electron/electron#4479]
I found a problem when dynamically inserting menu before a Help menu. Let's say I build up a menu contains help menu at the beginning:

```javascript
  var myMenu = Menu.buildFromTemplate([
    {
      label: 'Editor',
      submenu: [
        {
          label: 'Reload',
          accelerator: 'CmdOrCtrl+R',
          click: function() {
            // BrowserWindow.getFocusedWindow().reload();
            BrowserWindow.getFocusedWindow().reloadIgnoringCache();
          }
        },
        {
          label: 'Dev Tools',
          accelerator: 'CmdOrCtrl+D',
          click: function() {
            BrowserWindow.getFocusedWindow().openDevTools({
              detach: true
            });
          }
        },
      ]
    },

    {
      label: 'Help',
      role: 'help',
      id: 'help',
      submenu: [
        {
          label: 'Manual',
          click: function() {
          }
        },
        {
          label: 'API',
          click: function() {
          }
        },
      ]
    },
  ]);
  Menu.setApplicationMenu(myMenu);
```

The menu shows correctly like this:

<img width="435" alt="screen shot 2016-02-15 at 10 38 57 am" src="https://cloud.githubusercontent.com/assets/174891/13038621/5c1d41e6-d3d0-11e5-886c-76751e50d2de.png">

After that I insert another menu before the help menu (role: 'help'):

```javascript
  myMenu.insert(0, new MenuItem({
    label: 'Foobar',
    submenu: new Menu(),
    type: 'submenu',
  }));
  Menu.setApplicationMenu(myMenu);
```

And I found the search bar shows in the menu I just inserted. It should be stay in Help menu.

<img width="454" alt="screen shot 2016-02-15 at 10 39 24 am" src="https://cloud.githubusercontent.com/assets/174891/13038659/a44179c4-d3d0-11e5-9a0a-33d32ef1322a.png">

My test environment is:

Mac OSX: 10.11.3
Electron: v0.36.7

I also create a repo to reproduce this problem: https://github.com/jwu/electron-help-menu-bug

**Comment by zcbenz** [comment]
It seems that any dynamical change to menu would make the `role` property wrong, we need to have our own `MenuModel` class instead of extending the `SimpleMenuModel` in C++.

**Comment by jpittner** [comment]
This also happens with the Window menu item. The current window title gets appended under the 3rd or 4th submenu, even if it isn't the "Window" submenu.
