### ISSUE TITLE
Tray icon does not display after updating to macOS Sequoia 15.1.1

### ISSUE THREAD

**Issue by crossandco-jacob** [electron/electron#44817]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.0

### What operating system(s) are you using?

macOS

### Operating System Version

15.1.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

A Tray icon should appear in the menu bar

### Actual Behavior

The tray icon does not show in the menu bar. No errors are thrown. 

### Additional Information

I just updated my M1 Macbook Pro to 15.1.1 today from a 14.x.x version. After doing so, my app's Tray icon, along with several other Electron apps I have on my computer (including 1Password) no longer appear in the menu bar. 

I've tried all sorts of workarounds to no avail. 

On the same device I'm running 14.6.1 via VirtualBuddy and the Tray icon still appears correctly, which leads me to believe this is a problem that has appeared with Sequoia. Tested with multiple versions of Electron including latest; doesn't work with any.

**Comment by cucbin** [comment]
On my 15.1.1 machine, I can't reproduce this scenario.
