### ISSUE TITLE
Electron horrible lag after hours of inactivity

### ISSUE THREAD

**Issue by MrLarso2002** [electron/electron#44819]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11 Home 23H2

### What arch are you using?

x64

### Expected Behavior

Electron app shouldn't be lagging even after hours of opening the app. It doesn't seem to occur to apps like VSC or Discord so this might only be the case for apps that arent already built, but run with npm start

### Actual Behavior

Theres large amounts of lag when resizing, and the frame takes a while to keep up. After a couple times of minimizing and focusing the window again it seems to recover.
https://github.com/user-attachments/assets/24d4baf2-e62a-481c-b050-cabad1c44ba4

**Comment by nikwen** [comment]
Can you reproduce this on a fresh project setup?

It would be really helpful if you could add a testcase gist made with [Electron Fiddle](https://www.electronjs.org/fiddle) that exhibits this behavior. This is 1) to allow maintainers to easily reproduce the bug and 2) to make sure the lag is not caused by application code.

**Comment by MrLarso2002** [comment]
alright, ill try!
