### ISSUE TITLE
Unable trigger pointerup event for rightclick on 33.2.1

### ISSUE THREAD

**Issue by lslzl3000** [electron/electron#44887]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.1

### What operating system(s) are you using?

macOS

### Operating System Version

MacOS 15.1.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

33.0 - 33.2.0

### Expected Behavior

Should catch `pointerdown` & `pointerup` events on right button

### Actual Behavior

A right click (contextmenu) on any element should catch `pointerdown` & `pointerup` events, but on `33.2.1`,  only `pointerdown` is triggered, no `poinerup` is fired.  Probably something wrong with the commit https://github.com/electron/electron/commit/86e4529d266df5fb89d02271474b52588f653cc3

**Comment by nikwen** [comment]
There's a fix for other bugs caused by the commit you mentioned: #44940

Maybe it'll fix your issue, too.

**Comment by lslzl3000** [comment]
resolved in 33.3.0
