### ISSUE TITLE
context-menu event is not emitting for WebContentsView webContents

### ISSUE THREAD

**Issue by dmitry-dzyuba-uinno** [electron/electron#44896]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.1

### What operating system(s) are you using?

macOS

### Operating System Version

macOS 15.1.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

33.2.0

### Expected Behavior

context-menu event is not emitting for WebContentsView webContents, it works in v. 33.2.0, but not on v. 33.2.1

### Actual Behavior

context-menu event should be emitting for WebContentsView webContents

### Testcase Gist URL

https://gist.github.com/dmitry-dzyuba-uinno/88342b14d4ce3e2e19e37b4e0ce3d611

**Comment by jjeff** [comment]
Maybe related to https://github.com/electron/electron/issues/44898

**Comment by dmitry-dzyuba-uinno** [comment]
Added testcase
