### ISSUE TITLE
[Bug]: WebContentsView not being transparent by default

### ISSUE THREAD

**Issue by KiruPoruno** [electron/electron#44914]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.1

### What operating system(s) are you using?

Other Linux

### Operating System Version

6.11.8

### What arch are you using?

x64

### Expected Behavior

If 2 `WebContentsView`'s are on top of each other, they should appear below each other, as previously `BrowserView` had transparency enabled by default.

As shown below with the example code, using `BrowserView`'s:
![Image](https://github.com/user-attachments/assets/0e8a92e5-bea6-4e0f-ae42-05e2b58d9f84)

### Actual Behavior

Each `WebContentsView` has a white background instead of transparent by default:
![Image](https://github.com/user-attachments/assets/3f2435f1-9fb2-4c61-beb2-7294c13061c2)

### Testcase Gist URL

https://gist.github.com/KiruPoruno/389c6c714164dbb0c31e98ad3be3aa5f

**Comment by KiruPoruno** [comment]
It turns out that transparency is supported, and I made a slight mistake, attempted to confirm this wasn't working by using `.setBackgroundColor()` accidentally setting it to `"transparent"`, not realizing this isn't part of the accepted colors, using `"#00000000"` does re-enable the transparency.

This change to having transparency be disabled by default is however seemingly not documented anywhere, at least I couldn't find it on the [migration page](https://www.electronjs.org/blog/migrate-to-webcontentsview) or in any other docs.

**Comment by nikwen** [comment]
@KiruPoruno Thanks for reporting! Do you want to submit a PR that adds a note to the migration guide?

Here's the post source code: https://github.com/electron/website/blob/main/blog/migrate-to-webcontentsview.md
