### ISSUE TITLE
Cannot find @electron-tollkit/utils despite is installed and added to the asarUnpack in package.json

### ISSUE THREAD

**Issue by Andrea-Dispe** [electron/electron#44939]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.22.1

### What operating system(s) are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Expected Behavior

It should install the windows app

### Actual Behavior

upon installing the windows app it crashes and returns this error:
Cannot find module @electron-toolkit/utils

### Additional Information

Steps and package.json
After cleaning the .next folder, the dist folder and node modules I run these commands:
- npm i 
- npm run next:build
- npm run electron:dist:win

even when i unpack asar with
-npx asar extract dist/win-unpacked/resources/app.asar unpacked-app
the resulting package.json doesn't have electron-toolkit 

this is my package.json
`{
  "name": "test",
  "version": "0.1.0",
  "main": "build/main.js",
  "private": true,
  "scripts": {
    "next:dev": "next dev",
    "next:build": "next build",
    "next:start": "next start",
    "next:lint": "next lint",
    "format": "dprint fmt",
    "postinstall": "electron-builder install-app-deps",
    "electron:dist": "electron-builder --win",
    "electron:dist:deb": "electron-builder --linux deb",
    "electron:dist:win": "electron-builder --win",
    "electron:build": "tsup",
    "build": "run-s next:build electron:build",
    "dist": "run-s next:build electron:dist",
    "dev": "npm-run-all --parallel electron:dev next:dev",
    "electron:build_watch": "tsup --watch --entry electron/main.ts --entry electron/preload.ts",
    "electron:dev": "npm-run-all --parallel electron:build_watch electron:watch",
    "electron:watch": "cross-env NODE_ENV='development' nodemon",
    "cypress:open": "cypress open",
    "cypress:run": "cypress run --browser chrome"
  },
  "dependencies": {
    "@electron-toolkit/utils": "^3.0.0",
    "@tanstack/react-query": "^5.61.0",
    "@tanstack/react-query-devtools": "^5.60.5",
    "@types/jwt-decode": "^3.1.0",
    "@types/react-table": "^7.7.12",
    "affiliazioni11": "file:",
    "bootstrap": "^5.3.3",
    "crypto-js": "^4.2.0",
    "dotenv": "^16.4.5",
    "formik": "^2.4.5",
    "get-port-please": "^3.1.2",
    "jwt-decode": "^4.0.0",
    "lodash": "^4.17.21",
    "moment": "^2.30.1",
    "next": "^14.2.18",
    "react": "^18",
    "react-bootstrap": "^2.10.2",
    "react-dom": "^18",
    "react-icons": "^5.0.1",
    "react-select": "^5.8.3",
    "react-spinners": "^0.13.8",
    "react-table": "^7.8.0",
    "uuid": "^9.0.1",
    "xlsx": "^0.18.5",
    "yup": "^1.4.0"
  },
  "devDependencies": {
    "@tanstack/eslint-plugin-query": "^5.27.7",
    "@types/crypto-js": "^4.2.2",
    "@types/lodash": "^4.17.13",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "cross-env": "^7.0.3",
    "cypress": "^13.6.6",
    "electron": "^33.2.1",
    "electron-builder": "^25.1.8",
    "eslint": "^8",
    "eslint-config-next": "14.1.0",
    "nodemon": "^3.1.7",
    "npm-run-all": "^4.1.5",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "tsup": "^8.3.5",
    "typescript": "^5.3.3"
  },
  "build": {
    "asar": true,
    "executableName": "NextJSElectron",
    "appId": "com.saybackend.nextjs-electron",
    "asarUnpack": [
      "node_modules/next",
      "node_modules/@img",
      "node_modules/sharp",
      "node_modules/@electron-toolkit/utils",
      "**\\*.{node,dll}"
    ],
    "files": [
      "build/**/*",
      "node_modules/**/*",
      {
        "from": ".next/standalone",
        "to": "app",
        "filter": [
          "!**/.env",
          "!**/package.json"
        ]
      },
      {
        "from": ".next/static",
        "to": "app/.next/static"
      },
      {
        "from": "public",
        "to": "app/public"
      }
    ],
    "win": {
      "target": [
        "nsis",
        "portable"
      ],
      "icon": "icons/win.ico"
    },
    "linux": {
      "target": [
        "deb"
      ],
      "category": "Development"
    }
  }
}`

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

**Comment by slogivewd** [comment]
Im having this issue, electron build the .msi but open the app results in a error @electron-toolkit/utils package is not found

**Comment by roshan00123** [comment]
@slogivewd have you solved this issue?
I am facing the same
