### ISSUE TITLE
Failed to compile Electron when `is_debug` = true

### ISSUE THREAD

**Issue by xiaofeihan1** [electron/electron#44962]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

35.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

15.1.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The chromium version is `133.0.6852.0`

I want to debug the run logic in renderer process of Electron binary. So I try to build Electron with `is_debug = true`.

I met two errors when linking, the following is my workaround. Hopefully it can help someone.

```
1. lld-link: error: undefined symbol  ExtensionActionOpenPopupFunction::RunExtensionAction in extension_action_api.h
2. lld-link: error: undefined symbol IsOffTheRecord in profile.h
```

There is the workaround. 
1. Add the following code in `extension_action_api.cc`. As @yanite mentioned in [here](https://github.com/electron/electron/issues/41674#issuecomment-2094851023)
```
ExtensionFunction::ResponseAction
ExtensionActionOpenPopupFunction::RunExtensionAction() {
  LOG(INFO) << "chrome.action.openPopup is not supported in Electron";

  return RespondNow(WithArguments(""));
}
```

2. Change the `bool IsOffTheRecord() final;`  in `src/chrome/browser/profiles/profile.h`

```
bool IsOffTheRecord() override;
```

### Actual Behavior

Should compile no error.

**Comment by nikwen** [comment]
Bot is wrong again. See #44850. Commenting to remove the label.

**Comment by jkleinsc** [comment]
@xiaofeihan1 have you tried debugging with a testing build?  That build usually has enough symbol information to debug with.  We do not officially support the debug build.

**Comment by cucbin** [comment]
@xiaofeihan1, it's not needed to set the argument `is_debug = true`. because the build has enough symbol to debug, though it build with the release.args.
if you want to debug and set breakpoints in xcode on macOS, you can ref these steps below:
1. build Electron with official guide
2. integrate with Electron in your app.
3. attach the process and set breakpoints in xcode.

Note that not all code can be breakpointed.

**Comment by mrbeardad** [comment]
> [@xiaofeihan1](https://github.com/xiaofeihan1) have you tried debugging with a testing build? That build usually has enough symbol information to debug with. We do not officially support the debug build.

When I debug electron by visual studio on Windows, I can not view any local variable values, Is this a normal phenomenon?
