### ISSUE TITLE
Maximize a window with transparency effect

### ISSUE THREAD

**Issue by Enfrade** [electron/electron#44970]
Hi,

I've encountered an issue where a window cannot be maximized when the transparency effect is enabled in Electron. I am trying to apply the Mica material on my app's window, but this automatically disables the maximize button, which prevents the window from being resized to full screen.

Is there any way to enable maximization while having the transparency effect or active Windows backdrop materials? That would be awesome if Electron supported such functionality, allowing the users to maximize a window without losing the transparency effect or Mica material.

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! Could you please fill out our issue template, so we have the information we might need to debug this without asking as many follow ups? Happy to have one of us take a look when the template is appropriately filled out 🙇‍♀️

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
