### ISSUE TITLE
Document contextmenu event fires twice in non-draggable regions

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#44976]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

34.0.0-beta.9

### What operating system(s) are you using?

macOS

### Operating System Version

macOS 14.7.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

34.0.0-beta.8

### Expected Behavior

The `contextmenu` event should fire once when right-clicking into a WebContents.

### Actual Behavior

The `contextmenu` event should fires twice when right-clicking into a WebContents.

### Testcase Gist URL

https://gist.github.com/8eefd9b741018120624eca9776f826bf

### Additional Information

We're seeing issues in React code where this doesn't allow preventing the native OS context menu from appearing. That may or may not be related.

Possibly related https://github.com/electron/electron/pull/44940

**Comment by erickzhao** [comment]
Seems related to the above PR since the Fiddle repros for me on the Dec 5 nightly but not the Dec 4 one: https://github.com/electron/electron/compare/v35.0.0-nightly.20241204...v35.0.0-nightly.20241205
