### ISSUE TITLE
webUtils.getPathForFile cannot be used

### ISSUE THREAD

**Issue by super-chen** [electron/electron#44982]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.2.0

### What operating system(s) are you using?

macOS

### Operating System Version

mac os 14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Gets the real path of the file selected in the render layer

import { ipcMain, webUtils } from 'electron';

ipcMain.handle('util.getPathForFile', async (_,file) => {
  const path = webUtils.getPathForFile(file);
  return path
});

### Actual Behavior

webUtils cannot be used

![Image](https://github.com/user-attachments/assets/e1d14566-a865-44ff-b25a-db8b9972b53a)

**Comment by super-chen** [comment]
Got the following error

`App threw an error during load
file:///Users/yuanchen/Desktop/quickupload/dist-electron/uploader/util.js:1
import { ipcMain, webUtils } from 'electron';
                  ^^^^^^^^
SyntaxError: The requested module 'electron' does not provide an export named 'webUtils'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:146:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:229:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async loadApplicationPackage (file:///Users/yuanchen/Desktop/quickupload/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:129:9)
    at async file:///Users/yuanchen/Desktop/quickupload/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:242:9`

**Comment by MarshallOfSound** [comment]
`webUtils` is documented as only being available in the renderer process.

Ref: https://www.electronjs.org/docs/latest/api/web-utils

**Comment by vexCoder** [comment]
This maybe a different problem but i hope you can look at it, 

![Image](https://github.com/user-attachments/assets/8346915c-0180-41f2-9664-016bc3d07814)

In the  image ipcrenderer is there, while webUtils is undefined, this was ran on a preload script

**Comment by adamgreenhall** [comment]
see also, if you are attempting to call this from the renderer process:
https://github.com/electron/electron/issues/45540#issuecomment-2647320052
