### ISSUE TITLE
electron  application start  node memory overflow

### ISSUE THREAD

**Issue by nickchainnb** [electron/electron#44990]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.1.4

### What operating system(s) are you using?

Windows

### Operating System Version

win10 (CPU AMD  x4 970)

### What arch are you using?

x64

### Last Known Working Electron version

29.1.4

### Expected Behavior

electron  application can start

### Actual Behavior

electron  application can not start，it (node ) looks like node memory overflow in CMD

The command line pendding...

1: 00007FF6FF74FF96 node::SetTracingController+88134
 2: 00007FF6FF7728BE node::InitializeOncePerProcess+1310
 3: 00007FF6FF7723C5 node::InitializeOncePerProcess+37
 4: 00007FF6FD77C5C8 node::loader::ModuleWrap::SelfSize+2728
 5: 00007FF6FD6CE904 std::__Cr::vector<v8::CpuProfileDeoptInfo,std::__Cr::allocator<v8::CpuProfileDeoptInfo> >::__alloc+72788
 6: 00007FF6FE7A8FAB uv_timer_set_repeat+1330427
 7: 00007FF6FE7ACF3F uv_timer_set_repeat+1346703
 8: 00007FF6FE7A851C uv_timer_set_repeat+1327724
 9: 00007FF6FD891112 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+588162
10: 00007FF6FD892314 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+592772
11: 00007FF6FD8920E1 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+592209
12: 00007FF6FD88E5B6 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+577062
13: 00007FF6FD88E6FD v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+577389
14: 00007FF6FD5D1195 v8::Extension::set_auto_enable+93893
15: 00007FF701F8C652 Cr_z_adler32+5181426
16: 00007FFFC9AF7E94 BaseThreadInitThunk+20

### Additional Information

![Image](https://github.com/user-attachments/assets/f9852200-6d36-4ddf-a782-a12dc77ae906)

**Comment by VerteDinde** [comment]
Closing as a duplicate
