### ISSUE TITLE
dialog.showOpenDialog open twice after select a file

### ISSUE THREAD

**Issue by Ionasjospo** [electron/electron#45004]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.2

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11 Home Single Language

### What arch are you using?

x64

### Expected Behavior

dialog.showOpenDialog close and dont open another window(to select a file)

### Actual Behavior

dialog.showOpenDialog close and opens another window(to select a file)

### Additional Information

This is how im using the function:

    const { canceled, filePaths } = await dialog.showOpenDialog({ properties: ['openFile'] });

I tried to put a boolean variable and ifs but didnt work.

Any tips?
Thanksss

**Comment by Ionasjospo** [comment]
Sorry! I dont want to dowload Electron Fiddle, my code is:

index.js:
    let openDialog = false; // This was added as a first solution but didnt work

    document.getElementById('selectFileButton').addEventListener('click', () => {
      if (!openDialog) {
        ipcRenderer.send('request-file-selection');
        openDialog = true;        
      }
    });


main.js:
  ipcMain.on('request-file-selection', async () => {
    const { canceled, filePaths } = await dialog.showOpenDialog({ properties: ['openFile'] });
    if (!canceled && filePaths.length > 0) {
      const filePath = filePaths[0];
      win.webContents.send('file-selected', filePath);
    }
  });

**Comment by alicestoneprod** [comment]
I have the same problem.

**Comment by Ionasjospo** [comment]
I finally realized that I made a mistake. I had the event ipcMain.on('request-file-selection', ...) duplicated.

**Comment by alicestoneprod** [comment]
> I finally realized that I made a mistake. I had the event ipcMain.on('request-file-selection', ...) duplicated. Try to check it!

no, seems all okay, but i have this trouble
