### ISSUE TITLE
Electron[88193:16856386] error messaging the mach port for IMKCFRunLoopWakeUpReliable

### ISSUE THREAD

**Issue by jeckni** [electron/electron#45002]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.1

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sequoia v15.1.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

npm run start

<img width="1377" alt="Image" src="https://github.com/user-attachments/assets/db256569-9945-43bf-b095-755e1dd8c231" />

### Actual Behavior

Electron[88193:16856386] error messaging the mach port for IMKCFRunLoopWakeUpReliable

**Comment by codebytere** [comment]
This is a known side effect of a recent Chromium bump of the macOS SDK. App behavior is not affected and there's nothing that can be done about it on the Electron side as of now, unfortunately.
