### ISSUE TITLE
Application Crash Caused by Electron Upgrade to 33.2.1

### ISSUE THREAD

**Issue by lmsccc** [electron/electron#45003]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.1

### What operating system(s) are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

29.3.2

### Expected Behavior

application running good

### Actual Behavior

application crash

### Additional Information

Recently, we upgraded the Electron version of our application from 29.3.2 to 33.2.1. After the application was released, the crash rate increased significantly. We analyzed the crash logs uploaded by users, and most of the stack trace information is related to DNS refreshConfig. The following is the stack trace information at the time of a certain crash.

 	[内联框架] main.exe!base::ImmediateCrash() 行 176	C++
 	main.exe!logging::LogMessage::HandleFatal(unsigned __int64 stack_start, const std::__Cr::basic_string<char,std::__Cr::char_traits<char>,std::__Cr::allocator<char>> & str_newline) 行 1073	C++
 	[内联框架] main.exe!logging::LogMessage::Flush::<lambda_0>::operator()() 行 773	C++
 	[内联框架] main.exe!absl::cleanup_internal::Storage<`lambda at ..\..\base\logging.cc:771:40'>::InvokeCallback() 行 87	C++
 	[内联框架] main.exe!absl::Cleanup<absl::cleanup_internal::Tag,`lambda at ..\..\base\logging.cc:771:40'>::~Cleanup() 行 106	C++
 	main.exe!logging::LogMessage::Flush() 行 956	C++
 	main.exe!logging::LogMessage::~LogMessage() 行 728	C++
 	[内联框架] main.exe!logging::`anonymous namespace'::NotReachedLogMessage::~NotReachedLogMessage() 行 133	C++
 	main.exe!logging::`anonymous namespace'::NotReachedLogMessage::~NotReachedLogMessage() 行 128	C++
 	[内联框架] main.exe!std::__Cr::default_delete<logging::LogMessage>::operator()(logging::LogMessage * __ptr) 行 69	C++
 	[内联框架] main.exe!std::__Cr::unique_ptr<logging::LogMessage,std::__Cr::default_delete<logging::LogMessage>>::reset(logging::LogMessage * __p) 行 281	C++
 	main.exe!logging::CheckError::~CheckError() 行 329	C++
 	main.exe!logging::NotReachedError::TriggerNotReached() 行 361	C++
 	main.exe!net::DnsConfigService::RefreshConfig() 行 66	C++
 	[内联框架] main.exe!content::WebContentsImpl::NotifyPrimaryMainFrameProcessIsAlive() 行 11012	C++
 	main.exe!content::WebContentsImpl::NotifySwappedFromRenderManager(content::RenderFrameHostImpl * old_frame, content::RenderFrameHostImpl * new_frame) 行 9535	C++
 	main.exe!content::RenderFrameHostManager::CommitPending(std::__Cr::unique_ptr<content::RenderFrameHostImpl,std::__Cr::default_delete<content::RenderFrameHostImpl>> pending_rfh, std::__Cr::unique_ptr<content::StoredPage,std::__Cr::default_delete<content::StoredPage>> pending_stored_page, bool clear_proxies_on_commit, bool allow_subframe_paint_holding, bool is_initiated_by_animated_transition) 行 4982	C++
 	main.exe!content::RenderFrameHostManager::CommitPendingIfNecessary(content::RenderFrameHostImpl * render_frame_host, bool was_caused_by_user_gesture, bool is_same_document_navigation, bool clear_proxies_on_commit, bool allow_subframe_paint_holding, bool is_initiated_by_animated_transition) 行 834	C++
 	main.exe!content::RenderFrameHostManager::DidNavigateFrame(content::RenderFrameHostImpl * render_frame_host, bool was_caused_by_user_gesture, bool is_same_document_navigation, bool clear_proxies_on_commit, const blink::FramePolicy & frame_policy, bool allow_subframe_paint_holding, bool is_initiated_by_animated_transition) 行 787	C++
 	main.exe!content::Navigator::DidNavigate(content::RenderFrameHostImpl * render_frame_host, const content::mojom::DidCommitProvisionalLoadParams & params, std::__Cr::unique_ptr<content::NavigationRequest,std::__Cr::default_delete<content::NavigationRequest>> navigation_request, bool was_within_same_document) 行 553	C++
 	main.exe!content::RenderFrameHostImpl::DidCommitNavigationInternal(std::__Cr::unique_ptr<content::NavigationRequest,std::__Cr::default_delete<content::NavigationRequest>> navigation_request, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams> params, mojo::StructPtr<content::mojom::DidCommitSameDocumentNavigationParams> same_document_params) 行 14620	C++
 	main.exe!content::RenderFrameHostImpl::DidCommitNavigation(content::NavigationRequest * committing_navigation_request, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams> params, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams> interface_params) 行 15392	C++
 	[内联框架] main.exe!base::internal::DecayedFunctorTraits<void (content::RenderFrameHostImpl::*)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>),content::RenderFrameHostImpl *,content::NavigationRequest *&&>::Invoke(void(content::RenderFrameHostImpl::*)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) method, content::RenderFrameHostImpl * && receiver_ptr, content::NavigationRequest * && args, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams> && args, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams> && args) 行 738	C++
 	[内联框架] main.exe!base::internal::InvokeHelper<0,base::internal::FunctorTraits<void (content::RenderFrameHostImpl::*&&)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>),content::RenderFrameHostImpl *,content::NavigationRequest *&&>,void,0,1>::MakeItSo(void(content::RenderFrameHostImpl::*)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) && functor, std::__Cr::tuple<base::internal::UnretainedWrapper<content::RenderFrameHostImpl,base::unretained_traits::MayNotDangle,0>,base::internal::UnretainedWrapper<content::NavigationRequest,base::unretained_traits::MayNotDangle,0>> && bound, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams> && args, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams> && args) 行 930	C++
 	[内联框架] main.exe!base::internal::Invoker<base::internal::FunctorTraits<void (content::RenderFrameHostImpl::*&&)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>),content::RenderFrameHostImpl *,content::NavigationRequest *&&>,base::internal::BindState<1,1,0,void (content::RenderFrameHostImpl::*)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>),base::internal::UnretainedWrapper<content::RenderFrameHostImpl,base::unretained_traits::MayNotDangle,0>,base::internal::UnretainedWrapper<content::NavigationRequest,base::unretained_traits::MayNotDangle,0>>,void (mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>)>::RunImpl(void(content::RenderFrameHostImpl::*)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) && functor, std::__Cr::tuple<base::internal::UnretainedWrapper<content::RenderFrameHostImpl,base::unretained_traits::MayNotDangle,0>,base::internal::UnretainedWrapper<content::NavigationRequest,base::unretained_traits::MayNotDangle,0>> && bound, std::__Cr::integer_sequence<unsigned long long,0,1>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams> && unbound_args, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams> && unbound_args) 行 1067	C++
 	main.exe!base::internal::Invoker<base::internal::FunctorTraits<void (content::RenderFrameHostImpl::*&&)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>),content::RenderFrameHostImpl *,content::NavigationRequest *&&>,base::internal::BindState<1,1,0,void (content::RenderFrameHostImpl::*)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>),base::internal::UnretainedWrapper<content::RenderFrameHostImpl,base::unretained_traits::MayNotDangle,0>,base::internal::UnretainedWrapper<content::NavigationRequest,base::unretained_traits::MayNotDangle,0>>,void (mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>)>::RunOnce(base::internal::BindStateBase * base, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams> && unbound_args, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams> && unbound_args) 行 980	C++
 	main.exe!base::OnceCallback<void (mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>)>::Run(mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams> args, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams> args) 行 157	C++
 	main.exe!content::mojom::NavigationClient_CommitNavigation_ForwardToCallback::Accept(mojo::Message * message) 行 1198	C++
 	[内联框架] main.exe!mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message * message) 行 1046	C++
 	main.exe!mojo::InterfaceEndpointClient::HandleIncomingMessageThunk::Accept(mojo::Message * message) 行 371	C++
 	main.exe!mojo::MessageDispatcher::Accept(mojo::Message * message) 行 43	C++
 	main.exe!mojo::InterfaceEndpointClient::HandleIncomingMessage(mojo::Message * message) 行 724	C++
 	[内联框架] main.exe!IPC::ChannelAssociatedGroupController::AcceptOnEndpointThread(mojo::Message message, IPC::`anonymous namespace'::ScopedUrgentMessageNotification scoped_urgent_message_notification) 行 1216	C++
 	[内联框架] main.exe!base::internal::DecayedFunctorTraits<void (IPC::ChannelAssociatedGroupController::*)(mojo::Message, IPC::(anonymous namespace)::ScopedUrgentMessageNotification),IPC::ChannelAssociatedGroupController *&&,mojo::Message &&,IPC::(anonymous namespace)::ScopedUrgentMessageNotification &&>::Invoke(void(IPC::ChannelAssociatedGroupController::*)(mojo::Message, IPC::`anonymous namespace'::ScopedUrgentMessageNotification) method, scoped_refptr<IPC::ChannelAssociatedGroupController> && receiver_ptr, mojo::Message && args, IPC::`anonymous namespace'::ScopedUrgentMessageNotification && args) 行 738	C++
 	[内联框架] main.exe!base::internal::InvokeHelper<0,base::internal::FunctorTraits<void (IPC::ChannelAssociatedGroupController::*&&)(mojo::Message, IPC::(anonymous namespace)::ScopedUrgentMessageNotification),IPC::ChannelAssociatedGroupController *&&,mojo::Message &&,IPC::(anonymous namespace)::ScopedUrgentMessageNotification &&>,void,0,1,2>::MakeItSo(void(IPC::ChannelAssociatedGroupController::*)(mojo::Message, IPC::`anonymous namespace'::ScopedUrgentMessageNotification) && functor, std::__Cr::tuple<scoped_refptr<IPC::ChannelAssociatedGroupController>,mojo::Message,IPC::(anonymous namespace)::ScopedUrgentMessageNotification> && bound) 行 930	C++
 	[内联框架] main.exe!base::internal::Invoker<base::internal::FunctorTraits<void (IPC::ChannelAssociatedGroupController::*&&)(mojo::Message, IPC::(anonymous namespace)::ScopedUrgentMessageNotification),IPC::ChannelAssociatedGroupController *&&,mojo::Message &&,IPC::(anonymous namespace)::ScopedUrgentMessageNotification &&>,base::internal::BindState<1,1,0,void (IPC::ChannelAssociatedGroupController::*)(mojo::Message, IPC::(anonymous namespace)::ScopedUrgentMessageNotification),scoped_refptr<IPC::ChannelAssociatedGroupController>,mojo::Message,IPC::(anonymous namespace)::ScopedUrgentMessageNotification>,void ()>::RunImpl(void(IPC::ChannelAssociatedGroupController::*)(mojo::Message, IPC::`anonymous namespace'::ScopedUrgentMessageNotification) && functor, std::__Cr::tuple<scoped_refptr<IPC::ChannelAssociatedGroupController>,mojo::Message,IPC::(anonymous namespace)::ScopedUrgentMessageNotification> && bound, std::__Cr::integer_sequence<unsigned long long,0,1,2>) 行 1067	C++
 	main.exe!base::internal::Invoker<base::internal::FunctorTraits<void (IPC::ChannelAssociatedGroupController::*&&)(mojo::Message, IPC::(anonymous namespace)::ScopedUrgentMessageNotification),IPC::ChannelAssociatedGroupController *&&,mojo::Message &&,IPC::(anonymous namespace)::ScopedUrgentMessageNotification &&>,base::internal::BindState<1,1,0,void (IPC::ChannelAssociatedGroupController::*)(mojo::Message, IPC::(anonymous namespace)::ScopedUrgentMessageNotification),scoped_refptr<IPC::ChannelAssociatedGroupController>,mojo::Message,IPC::(anonymous namespace)::ScopedUrgentMessageNotification>,void ()>::RunOnce(base::internal::BindStateBase * base) 行 980	C++
 	[内联框架] main.exe!base::OnceCallback<void ()>::Run() 行 156	C++
 	main.exe!base::TaskAnnotator::RunTaskImpl(base::PendingTask & pending_task) 行 203	C++
 	[内联框架] main.exe!base::TaskAnnotator::RunTask(perfetto::StaticString event_name, base::PendingTask & pending_task, base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl::<lambda_4> && args) 行 90	C++
 	[内联框架] main.exe!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow * continuation_lazy_now) 行 470	C++
 	main.exe!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() 行 332	C++
 	main.exe!base::MessagePumpForUI::DoRunLoop() 行 259	C++
 	main.exe!base::MessagePumpWin::Run(base::MessagePump::Delegate * delegate) 行 84	C++
 	main.exe!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool application_tasks_allowed, base::TimeDelta timeout) 行 643	C++
 	main.exe!base::RunLoop::Run(const base::Location & location) 行 136	C++
 	main.exe!content::BrowserMainLoop::RunMainMessageLoop() 行 1104	C++
 	main.exe!content::BrowserMainRunnerImpl::Run() 行 157	C++
 	main.exe!content::BrowserMain(content::MainFunctionParams parameters) 行 34	C++
 	main.exe!content::RunBrowserProcessMain(content::MainFunctionParams main_function_params, content::ContentMainDelegate * delegate) 行 735	C++
 	main.exe!content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams main_params, bool start_minimal_browser) 行 1314	C++
 	main.exe!content::ContentMainRunnerImpl::Run() 行 1165	C++
 	main.exe!content::RunContentProcess(content::ContentMainParams params, content::ContentMainRunner * content_main_runner) 行 354	C++
 	main.exe!content::ContentMain(content::ContentMainParams params) 行 367	C++
 	main.exe!wWinMain(HINSTANCE__ * instance, HINSTANCE__ *, wchar_t * cmd, int) 行 238	C++
	[内联框架] main.exe!invoke_main() 行 118	C++
 	main.exe!__scrt_common_main_seh() 行 288	C++
 	KERNEL32.DLL!BaseThreadInitThunk()	未知
 	ntdll.dll!RtlUserThreadStart()	未知

I tried looking at the source code of Chromium and found that they recently submitted a commit [54bd8e3](https://github.com/chromium/chromium/commit/54bd8e328edeeabe366b950496144b8ee93b2c48#diff-5fafc1ee0208a239a0729696151528b4160b994c0554f2b9e8ff72c38c49437b), which mentioned in the commit log

`Migrate to NOTREACHED() in net/
NOTREACHED() and NOTREACHED_IN_MIGRATION() are both CHECK-fatal now.
The former is [[noreturn]] so this CL also performs dead-code removal
after the NOTREACHED().`

I think this modification is the direct cause of the application crash. The dns refreshConfig method is not supported on every platform. In unsupported platforms, NOTREACHED will be called. Then NOTREACHED has recently been changed to CHECK-fatal, which will cause the application to crash.

But I don't know why dns refreshConfig is called. I don't know whether this is the behavior of electron or chromium. As expected, platforms that do not support dns refreshConfig should not call this method. I hope to get your help. If you can help me look into this problem, I would really appreciate it.

**Comment by KarthikTarun** [comment]
@lmsccc were you able to fix this?

**Comment by lmsccc** [comment]
> [@lmsccc](https://github.com/lmsccc) were you able to fix this?

No, we have temporarily rolled back the version of electron
