### ISSUE TITLE
Does electron support task manager?

### ISSUE THREAD

**Issue by leon9508** [electron/electron#45065]
Does Electron support task manager, just like Chrome？

<img width="998" alt="Image" src="https://github.com/user-attachments/assets/1001276a-5f64-42f1-b764-b7ab8f8d8600" />

**Comment by VerteDinde** [comment]
Hi @leon9508, I'm not sure exactly what you mean by "supporting" task manager, but yes, Electron app processes will also appear in Task Mamager

**Comment by nikwen** [comment]
@VerteDinde I think @leon9508 was referring to Chrome's built-in task manager, not to the one from the OS.

It might make sense to reopen the issue.

![Image](https://github.com/user-attachments/assets/8556a2a6-437e-48d2-85aa-bc0bcedf90a1)

**Comment by leon9508** [comment]
Hi @VerteDinde What I mean is, as @nikwen  said, does Electron support opening its own task management like Chrome.

<img width="589" alt="Image" src="https://github.com/user-attachments/assets/9dc817f1-2081-4e8c-a24e-0b7407cca522" />
