### ISSUE TITLE
Is there any way to get the current clipboard content information?

### ISSUE THREAD

**Issue by ReAlign** [electron/electron#45064]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Is there any way to get the current clipboard content information, no matter what type, currently clipboard.readText always returns a string, even if the copied content is a picture or a file

### Proposed Solution

I expect there will be an API like this, clipboard.readCurrent() or something similar.

### Alternatives Considered

-

**Comment by nikwen** [comment]
The [`clipboard` API](https://www.electronjs.org/docs/latest/api/clipboard) has many functions to get the current clipboard contents, e.g. `readImage` for images or the generic `readBuffer` function.

If there's anything you would want to do that the API doesn't allow you to do yet, it would be great if you could specify what that is.

**Comment by VerteDinde** [comment]
☝ Echoing what @nikwen said, there are specific clipboard APIs for various different format types. We also have `readBuffer`/`writeBuffer` as a generic option.
