### ISSUE TITLE
[Bug]: On mobile, "Copy" and "Toggle Word Wrap" buttons must be outside the code box.

### ISSUE THREAD

**Issue by harshal050** [electron/electron#45079]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.0

### What operating system(s) are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Last Known Working Electron version

33.0.0

### **Steps :**

1 : In mobile screen go to : https://www.electronjs.org/docs/latest/tutorial/asar-archives
2 : go to Web API section
3 : fix this issue of buttons

![Image](https://github.com/user-attachments/assets/78b24abf-c62d-4361-a443-dd316ae3be2d)
**

**Comment by ankit010IITJ** [comment]
How it should look like? Is there any ss of correct ui which we could refer. And the issue you are highlighting for content of Web API section, but it is there  with some other section also.

**Comment by VerteDinde** [comment]
Hey folks, that overlay comes from Docusaurus itself and isn't something the Electron website controls. I'd encourage you to file an upstream issue. I'm going to close this.
