### ISSUE TITLE
[Docs]It is hoped that the deprecated APIs can be marked in the left sidebar.

### ISSUE THREAD

**Issue by liaodalin19903** [electron/electron#45085]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When check docs, the deprecated info is in the detial. 

### Proposed Solution

It is hoped that the deprecated APIs can be marked in the left sidebar.
Benefit: It will be convenient for everyone to read the documents more easily. 

![Image](https://github.com/user-attachments/assets/f69fb335-03c5-47f0-88fb-94474a7d065a)

### Alternatives Considered

None.

**Comment by nikwen** [comment]
I love that idea!

Would you be able to open the issue in the [`electron/website`](https://github.com/electron/website) repository? That's where the right people will see it.

Thanks!

**Comment by liaodalin19903** [comment]
[Done](https://github.com/electron/website/issues/723)

**Comment by nikwen** [comment]
Thanks, @liaodalin19903!
