### ISSUE TITLE
Cookie Encryption breaks Cookie Storage

### ISSUE THREAD

**Issue by thomasbachem** [electron/electron#45088]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.2.1

### What operating system(s) are you using?

macOS

### Operating System Version

Sonoma 14.7

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Non-session cookies should be stored persistently between app launches. I create a BrowserWindow with `webPreferences.partition` set to `persist:…`.

### Actual Behavior

It seems only a single cookie gets stored persistently; the rest vanishes when quitting and reopening the app. The cookie that gets restored between launches is stored in the `Cookies` SQLite file in the `appData` folder (`/Users/…/Library/Application Support/…/Partitions/…/`).

There are no errors or permission requests (e.g. for keychain access) raised.

### Additional Information

**This issue gets resolved when I disable the `EnableCookieEncryption` fuse in my `forge.config.js`** – which was turned on by default when I set up Electron Forge as described in the tutorial.

Related to #27524, #7073, #8416

**Comment by MarshallOfSound** [comment]
Can you run your packaged app from terminal with `ELECTRON_ENABLE_LOGGING=1` as an environment variable. Cookie Encryption definitely works generically as major apps are consuming it right now.

The two things to check:
* Try the logging trick mentioned above
* Check your app is being code signed correctly, this is a hard requirement on macOS nowadays and certain things (including keychain) don't function correctly without a valid code signature

**Comment by thomasbachem** [comment]
Thanks for the quick review, @MarshallOfSound!

My app is packaged but, indeed, not yet code signed (it's not ready for distribution yet) – so that's probably the issue here. I also cannot code sign it at the moment because Apple support needs to fix my developer account status first.

**Still, I think this should be pointed out with a clear warning in the tutorial and a comment in the forge config template next to the fuse!**

**Comment by MarshallOfSound** [comment]
> Still, I think this should be pointed out with a clear warning in the tutorial and a comment in the forge config template next to the fuse!

Although I partially agree here, more and more stuff requires code signing with every release of macOS. In fact your app simply won't launch on most M-series devices without being code signed. So it's kind of a given for distribution unfortunately.

cc @erickzhao not sure if you have thoughts on the docs aspect here?

**Comment by thomasbachem** [comment]
I think if the `EnableCookieEncryption` fuse/feature doesn't work with an unsigned app, it should simply throw an error message… As should everything else too.

**Comment by nikwen** [comment]
I remember seeing various bug tracker issues pop up where the issue was that someone didn't code sign their app. I think it would make sense documenting that, @erickzhao and @MarshallOfSound.

List of some APIs where code signing is necessary for them to work properly:

- Login item
- Cookie encryption
- OS-level encryption
- Auto updater

**Comment by dmatora** [comment]
I'm so happy this is at least mentioned in the issue.
I never sign my apps for long list of reasons (and yes, then perfectly run unsigned even on apple silicon, you can have to confirm it once in security settings)
And I would NEVER would figure out why my app not working after packaging, if it wouldn't be layout out here.
Changed EnableCookieEncryption to false and tada! problem solved.

**Comment by nikwen** [comment]
Documentation issue: #45802
