### ISSUE TITLE
Glibc mismatch for snap after building with electron builder

### ISSUE THREAD

**Issue by IH-Priyam** [electron/electron#45111]
I have a working application, I have tested that the app.exe file works on windows and also the Appimage works on Linux. But after installing the snap version of the app, I am not able to run it because of this error:

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found.

My local host has GLIBC 2.35, 
But on snap run --shell airobox-desktop-app, I get GLIBC version 2.27. I have tried to use core 20 and core 22, and also tried different confinement option but nothing seems to work. 

Here is the code block for my build options in vue.config.json
linux: {
          target: ["snap"],
          category: 'Development',
          snap: {
            base: "core22", 
            confinement: "classic", 
            stagePackages: ["libc6", "libc6-dev", "libstdc++6", "zlib1g", "libgcc1"]
          },

Any feedback or suggestions are appreciated. Thanks in advance

**Comment by MarshallOfSound** [comment]
Electron Builder is an unofficial third party packaging tool, you should raise issues on their [repository](https://github.com/electron-userland/electron-builder) not ours 👍
