### ISSUE TITLE
setSkipTaskbar breaks setThumbarButtons

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#4514]
When you call `setThumbarButtons([ ... Items .. ])` the buttons appear as expected.  If you then call `setSkipTaskbar(true); setSkipTaskbar(false);` the buttons have gone.

This is not expected, (I would expect the buttons to come back after the program is back on the taskbar.  Even stranger is that calling `setThumbarButton` after you have skipped the taskbar and then "unskipped" the taskbar does nothing.  It throws no errors and just fails silently.

Any ideas?

**Comment by MarshallOfSound** [comment]
As a quick update, `setThumbarButtons` returns `true` even if the buttons are not added.

https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winsetthumbarbuttonsbuttons-windows-7

**Comment by Ariyn** [comment]
this happens to me too.
in my case, hide() and show() makes this bug.

**Comment by codehz** [comment]
I have a little demo for those bugs..
https://github.com/codehz/electron-test
The first test (fullscreen related) has been fixed.

**Comment by MarshallOfSound** [comment]
@zcbenz Can you point in me in the right direction as to what is going wrong here.  I dived in this morning trying to find where the icons are lost or at least why calling `setThumbarButtons` once the window is visible again doesn't bring them back.  But I can't see the issue in the code.

**Comment by zcbenz** [comment]
@MarshallOfSound I think Windows simply removes the buttons when the taskbar icon is removed (by either hiding window or setting skipTaskbar), we need to reset the buttons when the window adds the taskbar icon back.

**Comment by MarshallOfSound** [comment]
@zcbenz I thought that aswell but when I manually try to reset (readd) the buttons after the taskbar icon is readded they don't reappear although the method returns `true` as if it was successful.
