### ISSUE TITLE
No audio on a mono device in Win 10

### ISSUE THREAD

**Issue by vferko** [electron/electron#4545]
I am having audio issues in electron with Jabra 280 USB mono headset in Windows 10.
No sound is heard whatsoever, however, the system sound works normally with the headset.
The system and electron sound also works normally with notebook's built-in speakers.

There is no issue with the headset and electron in Windows 7.

**Comment by zcbenz** [comment]
Does Chrome browser work?

**Comment by vferko** [comment]
Yes, chrome and everything other than Electron worked in Windows 10.

**Comment by zcbenz** [comment]
A search in Chromium's issues list shows some related issues, I'll see if upgrading to Chrome 48 would fix this.

**Comment by zcbenz** [comment]
Can you try if v0.37.x fixes this?

**Comment by vferko** [comment]
v0.37.5 - still the same issue. Tested also with Windows 8, sound not working with the headset.

**Comment by zcbenz** [comment]
Hmm I have no idea of why this happens. I'm sorry but we are not able to fix this since it is a problem with a specified hardware, and I'm closing it as won't fix.
