### ISSUE TITLE
Safe ipc between browser and app

### ISSUE THREAD

**Issue by cpsubrian** [electron/electron#456]
I am loading potentially unsafe pages into a BrowserWindow, however, I still need those windows to be able to send messages to the server. If I use `node-integration` = `disable`, to make loading the page safe, that disables the ability to use ipc, correct?

**Comment by bgSosh** [comment]
IMO a `node-integration = ipc-only` option (or a seperate `ipc-only = <bool>` field) would be a good solution.

**Comment by whiskyagogo** [comment]
I second the suggestion from @bgSosh. We only need the ability to pass messages and it would be wonderful to use the provided `ipc` module without concerns for full node access security issues.

**Comment by arendjr** [comment]
+1 for being able to use IPC from web pages.

**Comment by jdurand** [comment]
Is there a simple way to receive CustomEvents from *outside* the BrowserWindow? Something like :
```js
  // main.js
  browserWindow.on('custom-event', function(e) { doSomething(); });
```
```js
  // index.html
  window.dispatchEvent(new CustomEvent('custom-event'))
```
I thinking of writing a hack by listening on __page-title-updated__ and I don't think I'll be able to look at myself in the mirror if I go through with it...

**Comment by paulcbetts** [comment]
Being able to use IPC means you can use remote eval, because that's how remote eval works. Having IPC enabled in a webpage is no different from a security boundary perspective than having node integration enabled

**Comment by anghene** [comment]
nevermind, I managed to implement electron-safe-ipc which works perfectly with nodeIntegration off, exactly what I needed.
