### ISSUE TITLE
webview scaled again when apply css transform to it

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#4562]
* Electron version: 0.36.8
* Operating system: OS X 10.11.2

Origin webview:
![image](https://cloud.githubusercontent.com/assets/8194131/13200044/b512c94a-d873-11e5-9e77-bd9891b629a0.png)

Add transform: scale(0.3) to it:
![image](https://cloud.githubusercontent.com/assets/8194131/13200054/e1c16c9e-d873-11e5-9a99-12c0da85b0db.png)

The content of webview is scaled to 0.3*0.3 = 0.09 of the origin size.

Add transform: scale(0.5) to it:
![image](https://cloud.githubusercontent.com/assets/8194131/13200068/fd4d5a86-d873-11e5-8ab2-4007b22371a3.png)

The content of webview is scaled to 0.5*0.5 = 0.25 of the origin size.

**Comment by paulcbetts** [comment]
If all you want to do is scale the WebView, use the WebFrame's zoom methods

**Comment by KochiyaOcean** [comment]
I want to scale the WebView together with its content.

**Comment by zcbenz** [comment]
This is an upstream Chromium bug: http://crbug.com/492182

**Comment by xywz** [comment]
Duplicate of #2168.

**Comment by zcbenz** [comment]
@xywz Didn't realize this is a duplicate, thanks!
