### ISSUE TITLE
MIME-type based filtering in file dialogs

### ISSUE THREAD

**Issue by obuchtala** [electron/electron#458]
File dialogs should support something similar to the browsers 'accept' attribute in input elements.

E.g.,  accept="image/*".

**Comment by WofWca** [comment]
Not sure if it's really a duplicate? File extension and file MIME are not the same thing. MIME allows you to pick e.g. `image/*`, without having to list all known file extensions: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/file#unique_file_type_specifiers
