### ISSUE TITLE
min-width doesn't work

### ISSUE THREAD

**Issue by as3boyan** [electron/electron#461]
I still can change window size without any restrictions

**Comment by techninja** [comment]
Hate to bug a closed issue, but on Linux I have a similar issue. Ubuntu 14.04, setting both `min-height` & `min-width`, and neither is being limited. The exact same code works fine on Windows, and likely mac (haven't tried yet though).

**Comment by garnieretienne** [comment]
Same here (Ubuntu 14.04): the window is still resizeable.

```
  // Create the browser window.
  mainWindow = new BrowserWindow({
    'width': 1024,
    'height': 768,
    'min-width': 1024,
    'min-height': 768,
    'auto-hide-menu-bar': true,
    'center': true
  });
```

**Comment by techninja** [comment]
@garnieretienne Actually I seem to have this working in latest 0.30.1. I also have this feeling no one looks at old, closed issues :P

**Comment by kunkinkan** [comment]
nope, still doesn't work in latest electron.

**Comment by didierfranc** [comment]
I handle it with javascript ...

```js
let width = window.innerWidth > 800 ? window.innerWidth : 800
```

**Comment by johny-bravo** [comment]
same issue here with 1.6.2 on win7
