### ISSUE TITLE
Mac: Rubber-Band Issue After First Resize

### ISSUE THREAD

**Issue by ghost** [electron/electron#462]
I've prepared a [Screencast](https://dl.dropboxusercontent.com/u/169803890/atom-shell-rubber-band-issue.mov) to show the problem.

Explanation: It's possible to prevent rubber-band scrolling with a bit of CSS. And it works. But, after resizing, the rubber-band prevention doesn't work any more until the window is resized again (as you can see in the linked video). That's a huge problem when working in a frameless window (as in the video). Can this behavior please be resolved, or rubber-band scrolling prevented completely (maybe with a switch).

**Comment by frozeman** [comment]
This is not a solution:
```
html {
  height: 100%;
  width: 100%;
  overflow: hidden;
}
```

As this makes it also impossible to place objects with `position: fixed`

Couldn't we add a option to the browserWindow `rubber-band-effect: false`?

**Comment by angelxmoreno** [comment]
what is the status of this? was it ever added?

**Comment by lfuelling** [comment]
Still have this problem.

**Comment by desilinguist** [comment]
It would be nice to have this.
