### ISSUE TITLE
OS native File Drag from Electron to *

### ISSUE THREAD

**Issue by bunterWolf** [electron/electron#4622]
The best way to start a File-Drag for now, is the downloadURL as i know.

Like here in Nylas N1:
https://github.com/nylas/N1/blob/master/internal_packages/attachments/lib/attachment-component.cjsx#L67

But only Images and PDFs are able to Drop direct on an Application (MAC). Other file formats just can be copied to Folders.
I think I'm not the only one who is looking for a full native file drop and I think chromium offers that already.

On chrome://downloads/ its possible to Drag any File on an Application (Mac).

Is there maybe a way to access this Drag Function in electron or can it become a part of?
Multi File Drag would be very nice too! :)

[chrome://downloads/ > js dragstart > chrome.send('drag', id)](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/resources/md_downloads/crisper.js&q=crisper.js&sq=package:chromium&type=cs&l=15751)

I have no knowledge, about cc++ but it found that... :D
[drag_download_item_views.cc](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/download/drag_download_item_views.cc&q=DragDownloadItem&sq=package:chromium&dr=CSs&l=31)
[md_downloads_dom_handler.cc](https://chromium.googlesource.com/chromium/src.git/+/master/chrome/browser/ui/webui/md_downloads/md_downloads_dom_handler.cc)

**Comment by zcbenz** [comment]
It is possible to port that ability in Electron, but I think it would need lots of work.

**Comment by bunterWolf** [comment]
I expected something like that and I know you have a lot to do... :)

Is it maybe the smarter way to create the drag function on my own with node bridges?
(Like: https://github.com/TooTallNate/NodObjC)
(I'm not sure if that is really possible, just an idea :))

merci!

**Comment by Paxa** [comment]
What is a difference between native and not native? I only notice that with electron can not drop files on icon in a Dock.

I'm using code like:
```js
window.ondragover = function(e) {
  $('body').addClass('file-hover');
  e.preventDefault();
  e.dataTransfer.dropEffect = 'copy';
  return false;
};

window.ondrop = function(e) {
  e.preventDefault();
  $('body').removeClass('file-hover');
  for (var i = 0; i < e.dataTransfer.files.length; ++i) {
    console.log(e.dataTransfer.files[i].path);
  }
  return false;
};

window.ondragleave = function () {
  $('body').removeClass('file-hover');
  return false;
};
```

**Comment by bunterWolf** [comment]
@Paxa 
You wrote about File Drops to an Electron app. That works great! (as you described)

I mean a File Drag **out** of Electron.

(The title is about that not very specific, sorry ;))

**Comment by bengotow** [comment]
Hey folks! I implemented the drag-and-drop behavior referenced above in N1, and we've definitely noticed that you can't drag to other apps in all scenarios. It seems like the drag session is being created with a "file promise" (here's a mime-type. Do you want it? If you accept this drop, I'll give you data) rather than a "file reference" (here's a file, do you want it?). 

(I don't know the proper system names for these concepts unfortunately, but I think that's the distinction.)

I think the first step might be to inspect the drag-and-drop pasteboard data coming from Chromium using a tool like https://pmougin.wordpress.com/2008/03/23/inspecting-the-pasteboard-with-drop-inspector/ to identify what is missing / different. This /might/ be very hard to change, but it's also possible that a few lines of NodObjC could extend the pasteboard data in-flight and make the drop work.

**Comment by bunterWolf** [comment]
#### Reference to "Hacking Choromium":
https://discuss.atom.io/t/hacking-chromium-for-drag-out/17852/9?u=justwolf

looks like "quicksnap" is here maybe already further.
As you can see on my reply I don't know exactly what to do with his patches

**Comment by bengotow** [comment]
Hmm that actually seems like a pretty good solution to me. @zcbenz what do you think? Looks like he's translating a specific pasteboard type into file paths in `web_drag_source_mac.mm`.

If that's possible, it might be preferable to actually detect the `downloadURL` and translate that into a real path reference if it's a `file://` URL. Might make the feature work "out of the box" with a wider range of JavaScript apps.

**Comment by zcbenz** [comment]
@bengotow I'm not very willing to add a patch like that, it is hard to maintain and we need to make it optional since there are security issues.

But it seems not hard to just add a new API for this without patching Chromium, the [DragDownloadItem](https://code.google.com/p/chromium/codesearch#search/&q=DragDownloadItem&sq=package:chromium&type=cs) function shows a very good example.

**Comment by quicksnap** [comment]
While we have had success with the patch mentioned by @bengotow, I agree it is not suitable for upstream.

I am very interested in DragDownloadItem.. @zcbenz do you think we'd be able to leverage to expose an API? Our main use case is hooking into `dragStart` and firing `preventDefault` and issuing a native drag.

I'm not familiar entirely with adding an API method to Electron, but I'll try to make time to see what can be done. It'd be lovely to get away from our electron fork!

**Comment by zcbenz** [comment]
@quicksnap I think it is quite reasonable to add an API for it.

**Comment by mattetti** [comment]
@zcbenz I'm evaluating using Electron for a new project and this feature is a requirement for us. I looked at the current version of the code but didn't see the API being implemented yet. I'd be glad to give it a try if you could point me in the right direction.

I'm looking at the chromium implementation:

```
void DragDownloadItem(const content::DownloadItem* download,
                      gfx::Image* icon,
                      gfx::NativeView view) {

  // Set up our OLE machinery
  ui::OSExchangeData data;

  drag_utils::CreateDragImageForFile(
      download->GetFileNameToReportUser(),
      icon ? icon->AsImageSkia() : gfx::ImageSkia(),
      &data);

  base::FilePath full_path = download->GetTargetFilePath();
  std::vector<ui::FileInfo> file_infos;
  file_infos.push_back(
      ui::FileInfo(full_path, download->GetFileNameToReportUser()));
  data.SetFilenames(file_infos);

  aura::Window* root_window = view->GetRootWindow();
  if (!root_window || !aura::client::GetDragDropClient(root_window))
    return;

  gfx::Point location = display::Screen::GetScreen()->GetCursorScreenPoint();
  aura::client::GetDragDropClient(root_window)->StartDragAndDrop(
      data,
      root_window,
      view,
      location,
      ui::DragDropTypes::DRAG_COPY | ui::DragDropTypes::DRAG_LINK,
      ui::DragDropTypes::DRAG_EVENT_SOURCE_MOUSE);
}
```

I'm not sure about a few things:

* how do these classes map to Electron, can we just import and start using?
* where should we do the integration? I think for safety reason we don't want to change the default drag and drop behavior so we would need to expose a new API. What's the machinery do that?

As mentioned, I'd be glad to help but I do need some guidance.

**Comment by zcbenz** [comment]
@mattetti I'm not sure wha't the best form of the API, I haven't looked into it yet, will give a try.

**Comment by mattetti** [comment]
Very much appreciated, as mentioned, I'm vey excited and willing to dedicate time to help.

**Comment by hems** [comment]
@mattetti / @zcbenz / @bengotow any news on this? i'm also having issues dragging an audio file into audio software, would be great to sort this out. is there any way i could help?

**Comment by mattetti** [comment]
It works well here, make sure your code is correct and the DAW/audio software you use can receive a dragged audio file.

**Comment by hems** [comment]
@mattetti would you kindly share snippets of your html and javascript code regarding that drag?

do i need to patch something on electron or chromium?

**Comment by r3verser** [comment]
Any code example guys? How to drag out file from Electron to another app.

**Comment by mattetti** [comment]
Look at the PR that closed this issue, you will find an example there.

**Comment by hems** [comment]
@mattetti thanks a ton!
