### ISSUE TITLE
Support sandbox bookmarks in MAS build

### ISSUE THREAD

**Issue by positlabs** [electron/electron#4637]
- Electron version: 0.35.6
- Operating system: OSX 10.11

Seems like app-scoped and document-scoped bookmarks are currently unsupported by Electron. This is a pretty huge feature for usability. E.g. not needing to re-select an output directory every time the user restarts the app.

There's a thread about this over at https://github.com/electron-userland/electron-packager/issues/271

I'm unfamiliar with truly native dev, but here's an [article about implementation](http://objcolumnist.com/2012/05/21/security-scoped-file-url-bookmarks/)

And [Apple docs on bookmarks](https://developer.apple.com/library/mac/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW16)

**Comment by jasonhinkle** [comment]
+1 , otherwise all mac app store apps are limited to using the Downloads, Movies, Music or Pictures folders for storage, which don't always make sense for the app.

**Comment by jdp** [comment]
Somewhat related, would it be possible to have [`app.getPath`](http://electron.atom.io/docs/v0.36.8/api/app/#appgetpathname) return a path compatible with [App Sandbox](https://developer.apple.com/library/mac/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html) when appropriate? Sandboxed apps don't have access to `~/Library/Application Support` (but they do have access to `~/Library/Containers/<bundle_id>/Data/Library/Application Support/<app_name>/`), and I'm not sure where I should start to store the files used for persisting app state across restarts in the meantime.

**Comment by positlabs** [comment]
@jdp persisting app state shouldn't be a problem. See my output for various `app.getPath` arguments in `mas` builds. It seems like what you are asking for is already implemented.

<img width="877" alt="screen shot 2016-03-08 at 1 39 02 pm" src="https://cloud.githubusercontent.com/assets/1918844/13617374/4e9a59d6-e533-11e5-919c-fc604dfa7d3c.png">

**Comment by jdp** [comment]
You're right, my problem was that I was using [tmp](https://www.npmjs.com/package/tmp), which I didn't have permissions for. `app.getPath` returns an appropriate container path.

**Comment by Maay** [comment]
+1

**Comment by fuermosi777** [comment]
Any updates?

**Comment by callodacity** [comment]
Wondering if this has been solved in any way?
I'm making a writing app (like TextEdit) which has a treeview for open folders, and it remembers open files on startup - but because of the Sandbox every time the app starts it's denied access to all of these files and the user must manually specify using the `open` or `save` dialogs.

Having `app-scoped` bookmarks would solve this problem, is there any way to do so with the current version of Electron?

**Comment by fuermosi777** [comment]
just curious why this issue hasn't attract enough attention as it is such an important one

**Comment by callodacity** [comment]
@fuermosi777 I don't know, it's definitely essential for some `mas` apps!

In the meantime I've written a module [`electron-bookmarks`](https://www.npmjs.com/package/electron-bookmarks) that has support for `app-scoped` bookmarks only. I'm planning on adding support for `document-scoped` bookmarks but it seems a little tricky.

**Please note** however, that this module uses `nodobjc` to bridge to the Objective-C runtime, and I'm not sure it if will pass the Apple Store Review process, I haven't yet tried.

**Comment by hackjutsu** [comment]
+1

**Comment by goodhyun** [comment]
@callodacity 
Thanks for the module, but I'm having an issue here
https://gitlab.com/callodacity/electron-bookmarks/issues/1 

any idea?

**Comment by matthieuh** [comment]
+1
