### ISSUE TITLE
Being able to update a menu item currently showing

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#4685]
The use case would be:
- Open a context-menu, one menu-item in it with a "Loading..." label
- Fetch the info required to fill this Loading... item
- Update the Loading... item with the new info (and potentially submenus as well)

**Comment by zcbenz** [comment]
This is unfortunately impossible with our menu implementation, it works by treating the menu object as a model and there is no direct control of the native menu items. So I'm closing this as won't fix.

**Comment by renandecarlo** [comment]
My workaround was to get mouse cursor position when the user clicks on the menu, and then show it at the coordinates after recreating it with `Menu.buildFromTemplate()` or the `Menu()` object. 
Basically like that:

```
let menuCoordinates = {};
contextMenu.on('menu-will-show', () => {
   menuCoordinates = require('electron').screen.getCursorScreenPoint();
});
```

... then rebuild it with `Menu.buildFromTemplate()` or new `Menu()`
... then reopen it at the coordinates we got:

```
contextMenu.popup({ x: menuCoordinates .x, y: menuCoordinates .y });
```

It should work with Tray too.

References
#937
#4801
#846
