### ISSUE TITLE
process.argv differs in built electron apps

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#4690]
* Electron version: 0.36.9
* Operating system: OSX

I have an application that can accept CLI arguments. I noticed when I built the app that `process.argv` is not the same as when running electron while developing.

When running electron from the command line `process.argv` looks like:

```bash
electron ./my-app --foo --ping=123
```

```js
[
  '/Users/bmann/Dev/my-app/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron',
  './my-app',
  '--foo',
  '--ping=123'
]
```

This is good because typically when you parse CLI args you do something like:
`minimist(process.argv.slice(2))`

This matches what its like to use `node` regularly such as `node index.js --foo --ping=123`

However when passing args directly to my built app, `process.argv` looks like this:

```bash
./MyApp.app/Contents/MacOS/Electron --foo --ping=123
```

```js
[
  '/Users/bmann/Dev/MyApp.app/Contents/MacOS/Electron',
  '--foo',
  '--ping=123'
]
```

This is bad because now `minimist(process.argv.slice(2))` misses the args. I get why this is happening but it is unfortunately not easy to work around, and I did not have this problem with `nwjs`.

**Comment by baconface** [comment]
I recommend using a command line arguments management system like [this package](https://www.npmjs.com/package/command-line-args). This will ensure your application can verify the input. Especially if you are depending on other human's input.

**Comment by brian-mann** [comment]
That is what I'm doing - using `minimist`. 

That solves the problem with dasherized arguments like `-v` or `--foo` - however if your CLI tool accepts a non dashed argument this will fail.

Imagine something like `gulp`. If you ran `gulp build` in node typically the arguments would look like this:

```js
[
  '/usr/bin/node',
  '/my-app/node_modules/.bin/gulp',
  'build'
]
```

However once you package your electron application the arguments will then become this:

```js
[
  '/MyApp.app/Contents/MacOS/Electron'
  'build'
]
```

Do you see the problem there? 

Now let's imagine your application accepts something like a path to a file as its argument. There is no way to tell the difference between what the user is providing via the CLI and what is coming from a standard node `process.argv`.

**Comment by zcbenz** [comment]
We can probably move `my-app` from `process.argv` in the default app, so it has the same `process.argv` with packaged app.

**Comment by jean-emmanuel** [comment]
I had the same issue using [yargs](https://www.npmjs.com/package/yargs). This did the trick for me (assuming your command line switches always start with an hyphen) : 

```
if (process.argv[1]&&process.argv[1].indexOf('-')==0) process.argv.unshift('')
```

**Comment by erkyrath** [comment]
Yes, I ran into this too. My app accepts filename arguments. I had to add a special case to remove `main.js` from the argument list.

(Fortunately my app doesn't deal with Javascript files, so this was a low-impact hack. Still, a hack.)

**Comment by jean-emmanuel** [comment]
You could also define a npm startup script in your package.json that tells the app there is an extra argument not to parse : 
```
    "scripts": {
        "start": "electron . --not-packaged"
    }
```

Just check before parsing process.args if it contains this special switch : 

```
var n = process.argv.indexOf('--not-packaged')!=-1?2:1
var args = minimist(process.argv.slice(n))
```

Then you would use `npm start -- [options]` if the app is not packaged.

**Comment by gbaumgart** [comment]
same here, just that i can't see my args at all with prebuild/electron --myArg="test" in the app with process.argv. There is only a bunch of chrome args. Is that a bug?

**Comment by MrSaints** [comment]
I'm running into the same problem. As a temporary _fix_, I used `sed` during build time to prepend a line to _push_ the process arguments. e.g.

```bash
sed -i "1s/^/process.argv.unshift(\"--\");\n /" /project/build/artifacts/main.js
```

Everything works as expected :+1:

**Comment by tejohnso** [comment]
Yargs conveniently mentions a workaround for Electron and nwjs in their [documentation](https://www.npmjs.com/package/yargs#argv)

**Comment by gbaumgart** [comment]
thanks to @MrSaints . works here too!

**Comment by zcbenz** [comment]
It is too late to change this behavior, this is going to break numerous apps. Instead I have added a `process.defaultApp` property to indicate whether the app is started by being passed as parameter to the default app, so people can use it to correctly handle this when parsing CLI parameters.

**Comment by bhj** [comment]
As of Electron 3 there is an [app.isPackaged](https://electronjs.org/docs/api/app#appispackaged) property:

```
  if (app.isPackaged) {
    process.argv.unshift(null)
  }
```
