### ISSUE TITLE
Publish electron official document multi-languages ebook

### ISSUE THREAD

**Issue by imfly** [electron/electron#4704]
I turned electron`s documents into ebook.

Read: http://doc-ebooks.github.io/electron-docs-gitbook/

Code: http://github.com/doc-ebooks/electron-docs-gitbook/

This is published with `GitBook`, used and read easily. Its every language documents are cloned from Electron`s documents.

Choose a language:

![1](https://cloud.githubusercontent.com/assets/12215508/13571978/dba6e410-e4b2-11e5-9eb9-f62a8215e327.jpg)

and engilish document:

![2](https://cloud.githubusercontent.com/assets/12215508/13572007/f615ac64-e4b2-11e5-9267-0617bae7ee45.jpg)

**Comment by imfly** [comment]
Update to electron v0.37.2

**Comment by kevinsawicki** [comment]
Merging this into #2524
