### ISSUE TITLE
Fullscreen mode does not hide the window menu

### ISSUE THREAD

**Issue by giuscri** [electron/electron#4709]
I built the `electron-quick-start` application. When I toggle the fullscreen mode, the toolbar remains visible.

![0703y2016 19 22 176170475](https://cloud.githubusercontent.com/assets/4048120/13578761/2c4ec5e0-e49a-11e5-9392-66cc75ea14a8.png)

---
* Electron version: 0.36.10
* Operating system:
```
% uname -a
Linux <hostname> 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux
% node --version
v5.7.0
```
running Openbox as the windows manager.

**Comment by Riuujin** [comment]
Have the same issue on windows with a custom app, when the windows goes fullscreen. Both on creation of a window with the 'fullscreen' option set to true or using setFullScreen method the menu bar stays visible. 

* Electron version: 0.37.3
* Operating system: Windows 10

**Comment by Siilwyn** [comment]
Can't replicate here, fullscreen mode is working and hiding the window menu on **Ubuntu 14.04 using Unity**.
So this seems distribution specific, suggest to tag this: `linux-distribution-specific`.

**Comment by samouds** [comment]
Have the same problem here with a Raspbian.

**Comment by acrixl** [comment]
same in windows

**Comment by Hadatko** [comment]
same on amr7l
