### ISSUE TITLE
Why prompt is not supported?

### ISSUE THREAD

**Issue by coderaiser** [electron/electron#472]
What is the reason that `prompt` is [not supported](https://github.com/atom/atom-shell/blob/516d46444dc88325b82ae016a9f56d66d247b599/atom/renderer/lib/override.coffee#L53)?

How could input box be created?
I see that prompt could be almost like `confirm`:

``` js
window.confirm = (message, title='') ->
  remote = require 'remote'
  dialog = remote.require 'dialog'
  buttons = ['OK', 'Cancel']
  not dialog.showMessageBox remote.getCurrentWindow(), {message, title, buttons}
```

Here is [possible solution](https://github.com/electron/electron/issues/472#issuecomment-143433593).

**Comment by coderaiser** [comment]
Possible solution: [Promise-based Alert, Confirm and Prompt replacement](https://github.com/coderaiser/smalltalk).

**Comment by alexandrev** [comment]
+1 and related to: https://github.com/atom/electron/issues/4134

**Comment by feross** [comment]
It seems that on OS X at least, it can't be that hard to support a prompt-like dialog box, since Transmission does it:

<img width="580" alt="screen shot 2016-03-02 at 4 24 05 pm" src="https://cloud.githubusercontent.com/assets/121766/13480526/419bc3b8-e093-11e5-886a-e7369e861139.png">

**Comment by konsumer** [comment]
I made one that works just like the browser `window.prompt`. Check it out [here](https://github.com/konsumer/electron-prompt)

**Comment by konsumer** [comment]
This looks like a "fake" prompt in the window, but it's a separate blocking synchronous window, just like prompt.

**Comment by JamesKyburz** [comment]
Check out https://github.com/jameskyburz/dialogs as a possible solution.

**Comment by konsumer** [comment]
Those are, in the sense that it's inside the window. Mine are outside if it.

**Comment by noahbenham** [comment]
FYI for those considering @JamesKyburz's link, the Github page states the solution is `not allowed in electron and some chrome extention contexts`.

**Comment by JamesKyburz** [comment]
@noahbengam

No, https://github.com/jameskyburz/dialogs is a fix in response to alert, prompt, confirm not always being available.

From the readme:

Theses native counterparts block the UI thread, are are not allowed in electron and some chrome extention contexts.

**Comment by popod** [comment]
I don't understand why prompt is not supporter and alert is ! the two block the thread and wait for a user action.. As is, I think prompt is a really useful feature and it should be implemented on electron.. Because now, they is no simply way to do that !!

**Comment by konsumer** [comment]
My code above is synchrous, and works just like prompt (seperate window) but you can style it how you like. It's definitely a hack, but I use it with existing code that relies on prompt.

**Comment by philfreo** [comment]
My two sense: it doesn't make sense that Electron implements `alert` and `confirm` natively but not `prompt`.

**Comment by sonofachuck** [comment]
Everytime I find a random, but essential, "unwilling to fix" issue in Electron, the words "Adobe Air" float through my addled brains. Let's reinvent a broken wheel.

**Comment by laurent22** [comment]
I don't get the refusal to implement this in Electron and forcing people to resort to awful hacks [like this](http://www.scriptol.com/javascript/electron-prompt.php). Even if it's not a common dialog on most operating systems, it's still easy to fallback to the build-in `prompt()` dialog of Chromium, and I bet that's all most people need. It's basically 4 lines of clean code in Electron against pages of hacky code in clients.

**Comment by rob10e** [comment]
When you need a solution due to third party libraries, @konsumer's solution works great.
Great job @konsumer .

**Comment by peterfreeman** [comment]
If you're on a Mac check out my solution: [electron-osx-prompt](https://www.npmjs.com/package/electron-osx-prompt).

It's just a native BrowserWindow (as modal) with some OS X styling based on [photonkit](http://photonkit.com).

**Comment by blurymind** [comment]
Just want to add to this by saying that so me it makes no sense its not supported either.

I found this workaround
https://www.npmjs.com/package/electron-prompt
Not sure if its the best way to go about it

**Comment by phil294** [comment]
> There is no native prompt dialogs in most GUI toolkits, so implementing prompt in atom-shell would require writing the prompt dialog from ground up on all platforms. 

So you refrain from implementing a prompt dialog because you need to do it three times, but forcing hundreds of developers to implement a custom solution is ok with you?

**Comment by gabrielstuff** [comment]
Hello,

For those who want easy prompt and no third party libs, I found that using native HTML5 dialog are fine and fully customizable to match Linux, Windows and Mac as it is renderless (no particular CSS, do what you want!) : 

```
<button id="openBtn">🎉 Open Modal</button>
<dialog id="modal" ref="imagePrompt">
  <form method="dialog">
    <h2>🛎Some question</h2>
    <input id="modalInputVal" type="text" placeholder="type something" required>
    <button type="submit" value="no" formnovalidate>
            Cancel
          </button>
    <button type="submit" value="yes">
            Confirm
          </button>
  </form>
</dialog>
```

And for the `js` part : 

```js
let openModalButton = document.querySelector('#openBtn')
let modal = document.querySelector('#modal')
let modalInputValue = modal.querySelector('#modalInputVal')

function openModal() {
  modal.showModal()
}

function logInput(answer) {
  console.log(typeof answer)
  if(answer === 'yes') {
      window.alert(modalInputValue.value)
  } else {
    window.alert('user cancel')
  }
  modalInputValue.value = modal.returnValue =  ''
}
openModalButton.addEventListener('click', openModal)
modal.addEventListener('close', () => logInput(modal.returnValue))
```

You can read more there: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
You have example on this page and I made a simple codepen which demonstrate the use : 

https://codepen.io/gabrielstuff/pen/YoqvBr

**Comment by gabrielstuff** [comment]
> But presisally i'd use a prompt for blocking the IO, my application receive a code that it interprete, if a loop that is transpiled like this.
> 
> ```js
> while (i < n) {
>   let a = read('Something message')
>   ...
> }
> ```
> 
> Block the io was perfect to me, with the promise api that code will be some painful.

Hello @jefer94, I thought this simple example might interest you, it is non blocking and allow to display a modal prompt recursively : 

https://codepen.io/gabrielstuff/pen/ewZjNJ

**Comment by fenwick67** [comment]
The number of public repos that have had to hack around this is crazy.

While it makes sense that `prompt()` isn't the most elegant way to get input from a user, it's a non-obsolete browser API that people use frequently on their websites.

People like @beakerbrowser and @maidsafe and *anyone loading webpages with Electron* give the guest page most reasonable browser APIs (`alert`, `confirm` and yes even `HTMLMarqueeElement` works) except this one bizarre omission. 

So, if only for supporting the guest content use-cases, I hope you reconsider not supporting prompt.

**Comment by DRocksCoding** [comment]
> https://codepen.io/gabrielstuff/pen/YoqvBr

Hey, thanks a lot man this is working! Its the best workaround for now.

But I agree with every other posts above that mentionned that a built-in prompt feature would be very useful to have implemented by Electron.

**Comment by gabrielstuff** [comment]
Since Dialogs are working fine and are fully customizable, I do not see why you would need prompt. 

If you just want to use a shortcut, there are plenty of libs providing user inputs with JS solution and which are framework agnostics.

Enjoy Native Dialog :)

**Comment by ssight** [comment]
For anybody who really wants native prompt windows in their Electron app, I've written [this](https://github.com/ssight/native-prompt) library. It's not perfect, but it gets the job done.

**Comment by blurymind** [comment]
We use this
https://sweetalert2.github.io/

**Comment by avin-shum** [comment]
Thank you @konsumer ! Still a good solution 4 years after published.

**Comment by andyfleming** [comment]
I wish there were a native prompt. I'm developing an app and want to quickly capture some input. I just want something temporary, but now I'm left looking for a workaround for something that should just be built in. No one ever really wants to use `prompt`, but it's useful while developing.

**Comment by dperetti** [comment]
Same complaint here. Sometimes, quick & dirty is the way to go, especially when you're scaffolding something.

**Comment by dan-peterson** [comment]
> For anybody who really wants native prompt windows in their Electron app, I've written [this](https://github.com/ssight/native-prompt) library. It's not perfect, but it gets the job done.

Thank you @ssight. Very well done.

**Comment by pjebs** [comment]
If you want consistency across different OS's, just use https://electron.guide/electron-alert/

It's powered by SweetAlert2.

**Comment by yunjimmy** [comment]
When we use the alert (1) in the Render Process,

In the Browser Window, it appears whether BrowserViews are occupying the screen.

Like the picture below.
![image](https://user-images.githubusercontent.com/93508630/147651938-9b4cfa2f-b383-4e9a-be38-9777c2eff3f5.png)

However, the above libraries have lower priorities than BrowserView.

**Comment by Saturnine-Softworks** [comment]
Cannot believe this issue has been open since 2014.

**Comment by jonnycook** [comment]
I cannot for the life of me understand why confirm is supported but prompt is not. I don't want to be ungrateful for the hard work you guys have put into creating this platform, but don't you want it to be as easy to use and as valuable as possible?

**Comment by dandeancook** [comment]
2024, i still can't understand why it's not supported, it basic input!
while alert/confirm are working.

**Comment by laurent22** [comment]
> There is no native `prompt` dialogs in most GUI toolkits, so implementing `prompt` in atom-shell would require writing the `prompt` dialog from ground up on all platforms. Due to the rare use of `prompt`, I think it doesn't deserve to do all the work, and it is very easy to use a web implemented solution for this.
> 
> So I'm closing this as won't fix.

The reason for closing for strange too, and it mentions atom-shell, is that how Electron was called?

But Electron is based on Chromium and I'm sure Chromium already includes code for `prompt` so there's nothing to reimplement for each platform.

I think this issue, 10 years after it was created, should be reviewed again taking into account the current state of Electron.

**Comment by dubdia** [comment]
Would be nice to have 👍

**Comment by leegee** [comment]
It's a shame patches are not welcome, since the feature certainly would be.

**Comment by JerryI** [comment]
bump
