### ISSUE TITLE
Object in shadow-root# of webview is wrong size after webview.setZoomFactor(1);

### ISSUE THREAD

**Issue by rokyed** [electron/electron#4739]
After playing with zoom factor, reverting it to 1 will make the ```<object>``` in the ```shadow-root#``` to take the height of the ```BrowserWindow``` and not the height of the ```<webview>```.

I fixed it with this hack: 
https://github.com/rokyed/cocoChanelJS/blob/master/app/plugins/mobileSim.js#L57

and CSS
```css
position: relative;
```
doesn't help.

Thanks for the support. And if any questions I am ready to answer.

* Electron version: 0.36.10
* Operating system: Mac OSX

**Comment by zcbenz** [comment]
It seems like a Chromium bug, not sure how to fix this.

**Comment by zcbenz** [comment]
Can not reproduce in v0.37.x anymore.
