### ISSUE TITLE
Windows: Allow Alt-key bindings to override menus.

### ISSUE THREAD

**Issue by mkleehammer** [electron/electron#474]
On Windows, top-level menu items like "&File" always process their hotkeys - after the menu is dismissed the bound behavior then executes.  For example, if Alt-f is bound to a "forward word command" (similar to bash, emacs, etc.), the File menu drops down.  After the file menu is dismissed with Esc the cursor will move forward.

Since there are many basic readline-style keybindings that conflict, this can be a show-stopper for some.

**Comment by ZiaMM** [comment]
I am on Linux, where some of us also use modern keymappings which accompany "drop down menus" at the top of "windows".  I also expect "Alt-F" to bring down the "File Menu".  Pressing "s", after that, should save my work.

The way I fixed this problem, with an older version of atom-editor, was to delete the emacs.json file (under “resources\apps\keymaps\").  Now that file is no longer there, and modifying "keymaps.cson" seems to only work "for a little while", then revert to the "default" mapping (1970s terminal style).  

I am guessing that the "default" keymap  is still coded in some file I can dispose of ... but where? Alternatively, is there a "reload keymap file" command which I could use in place of a restart?

**Comment by Mingling94** [comment]
I'm on Ubuntu Gnome 15.04

I have the same issue as ZiaMM, I *want* my Alt-F to bring down the File Menu without having to select it by mouse. Pressing Alt to bring down a menu toggled to be hidden or even pressing Alt when the menu is shown underlines the 'F' in 'File' implying that it can be selected through pressing 'F'

However, it just does forward word :(

I'd like to not have to edit files and have these keymappings customizable through more graphical routes like the menu.

**Comment by phillipwei** [comment]
I'm on windows. This was terribly confusing.

@rjattrill I think what you are suggesting is perfect.

**Comment by rjattrill** [comment]
Ok - working on a pull request now.

**Comment by ZiaMM** [comment]
Please allow Linux users to also enable standard drop-down menu functionality.  This is present on every other GUI application I use on my Linux-OS PC.  Atom is the exception to the rule.  We should be able to access the "File" menu by pressing Alt-F, along with Windows-OS users.  Thanks.

**Comment by rjattrill** [comment]
What is the standard for OS X?   If it is the same across OS X, Linux and Windows then the approach in my pull request might not be correct.

**Comment by dkleehammer** [comment]
@rjattrill & @paulcbetts 

What @mkleehammer (as well as myself) is to have a custom keymap as we like it... weird or not for you, many of us work on multiple platforms in a day (personally, I'm on windows and OSX) and come from an emacs world, so mapping my keys to emacs style of keys works best for me as I'm not having to *think* about what platform I'm on, but rather It Just Works™.  Processing the keymap before the applications hot-keys will enable atom to be a high custom IDE specific to the user.

@rjattrill - Ross, I don't see pull-request #7343, so I'm unable to tell you the approach is correct.

**Comment by frankhale** [comment]
@dkleehammer, the pull request is here: https://github.com/atom/atom/pull/7434

**Comment by mn4367** [comment]
@rjattrill 
> What is the standard for OS X? If it is the same across OS X, Linux and Windows then the approach in my pull request might not be correct.

There is no equivalent to Alt+* to open a menu on OS X. The standard way on OS X to reach the application menu is Ctrl+F2, after that you can go to menu entries by entering the first letter of the name of the desired menu entry or by using the cursor keys.
Just a note on your pull request, if Atom should be localized in the future, ALt+F of course won't work in every other language, so maybe for this kind of 'overrides' it's worth considering a solution which allows localization.

**Comment by uptownhr** [comment]
I'm on ubuntu using emacs bindings, and going back to the original poster, can alt be disabled from toggling the menu?

**Comment by akappen** [comment]
@uptownhr 

I'm also on Ubuntu and really hate the alt menu shortcuts. Here's a way to disable them for the Atom editor, tested on versions 1.0.0 - 1.3.1.

https://discuss.atom.io/t/alt-key-menu-bar-interaction-overrides-shortuts/9192/7

Add this to your Atom init script:

```
# Get rid of the alt-menu shortcuts
atom.menu.template.forEach (t) ->
  t.label = t.label.replace("&", "")
atom.menu.update()
```

**Comment by uptownhr** [comment]
@akappen thanks, I will check this out and report any issues.

**Comment by ElijahLynn** [comment]
@akappen On Ubuntu 14.04 here and I have alt menu shortcuts disabled but for some reason Slack (electron) has my overridden my override. I initially thought it was a Gnome 2 vs Gnome 3 thing but your comment has given me some hope. I am currently trying to find out how to do the same as you did for Slack.

**Comment by ElijahLynn** [comment]
https://twitter.com/SlackHQ/status/859449588285046784

**Comment by assafmo** [comment]
@ElijahLynn Any update on this? Still annoying 3 years later.

**Comment by rjattrill** [comment]
Everyone is using Visual Studio Code now @ElijahLynn

**Comment by ElijahLynn** [comment]
> @ElijahLynn Any update on this? Still annoying 3 years later.

Latest Slack for Linux seems to not have my shortcuts overridden anymore and works nicely for me now.

**Comment by ElijahLynn** [comment]
> Everyone is using Visual Studio Code now @ElijahLynn

Confused by this, I wasn't using Atom before and am not using Visual Studio Code now. I use IntelliJ fwiw. But I am missing some context I think, maybe you meant to mention someone else?

**Comment by rjattrill** [comment]
One context for the problem was the Atom editor built on top of Electron.
 I use IntelliJ too.  :-)

**Comment by rjattrill** [comment]
Yes - sorry @ElijahLynn.  I was responding to @assafmo.  I believe original context for the problem was Atom editor - and this issue has been moved to Electron since.

**Comment by assafmo** [comment]
I asked if maybe you have an update from slack... Anyway it's still not working for me on linux on slack and vscode

**Comment by ElijahLynn** [comment]
> I asked if maybe you have an update from slack... Anyway it's still not working for me on linux on slack and vscode

Bummer to hear that, it is really annoying!

**Comment by ElijahLynn** [comment]
> Yes - sorry @ElijahLynn. I was responding to @assafmo. I believe original context for the problem was Atom editor - and this issue has been moved to Electron since.

Thanks for clarifying!

**Comment by shaygover** [comment]
Anything new on this front?
