### ISSUE TITLE
Support Tray.setTitle on Linux

### ISSUE THREAD

**Issue by johannesjo** [electron/electron#4742]
- Electron version: 0.36.10 (latest stable)
- Operating system: Ubuntu 15.10

I already asked this on stackoverflow: http://stackoverflow.com/questions/35755240/how-to-add-text-to-ubuntu-app-indicator-with-with-nw-js-or-electron

I would like to add text to the ubuntu (unity) app indicator. That's possible via the python package libindicator but not via electron so far.

**Comment by zcbenz** [comment]
Currently setting label for app indicator is not supported.

**Comment by johannesjo** [comment]
What would be required to enable this functionality? Maybe I could provide a PR? I'm just not sure where to start (aside from the libindicator package).

**Comment by johannesjo** [comment]
This is still not supported with electron 1.4.1. I really would like to help, but I'm not sure were to get started.

**Comment by johannesjo** [comment]
I suppose this would be the right file to map the code: https://github.com/electron/electron/blob/72d67788945d456147edb4498154d231fa1482a6/atom/browser/ui/gtk/app_indicator_icon.cc

Is it enough to bind the function there to the proper app_indicator_set_title?

**Comment by johannesjo** [comment]
Ok I found this: https://github.com/electron/electron/blob/master/docs/development/build-instructions-linux.md unfortunately I have no wake to make the 25 Gig required available currently. I'm still wondering, if this is not an easy fix.

**Comment by MarshallOfSound** [comment]
@johannesjo Try bootstrapping with `--dev` it will download a lot less

**Comment by johannesjo** [comment]
Seems like a simple mapping won't solve this issue, as this feature needs to be implemented into chromium itself first ([maybe here](https://github.com/Nu3001/external_chromium_org/blob/master/ui/linux_ui/status_icon_linux.h)).

**Comment by mkg20001** [comment]
Any progress?

**Comment by codebytere** [comment]
Given that this remains impossible without action on the chromium side, and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution or chromium were to implement it, we would be very open to accepting a PR!

**Comment by johannesjo** [comment]
Just FYI: I created a new request with chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=1016125&can=2&q=Tray%20Title&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
