### ISSUE TITLE
enable-system-flash support

### ISSUE THREAD

**Issue by frankietaylor** [electron/electron#4755]
[Flash download page](http://www.adobe.com/support/flashplayer/debug_downloads.html)

Flash ppapi can be installed through adobe installer for chromium based browsers.

Can we have this support (enable-system-flash) to automatically detect system installed flash which cef3 does.

**Comment by deepak1556** [comment]
`enable-system-flash` commandLine support can only be provided for windows and OSX. Adobe doesnt provide PPAPI binaries for linux. If someone is willing to provide a PR can refer this [code](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/common/chrome_content_client.cc&sq=package:chromium&l=340&rcl=1457882956) .

**Comment by codebytere** [comment]
closing due to abandonment.
