### ISSUE TITLE
Ability to choose media source for document.getUserMedia

### ISSUE THREAD

**Issue by buschtoens** [electron/electron#476]
For when you have more than one microphone/webcam.

---

Context: I'm currently working on a VoIP application with an atom-shell client.

**Comment by sergiovilar** [comment]
Is there's a way to specify a default video device for `getUserMedia()`?
I need to open a webpage that uses getUserMedia() but I want to specify which device should be used.

**Comment by buschtoens** [comment]
@sergiovilar Well.. yeah. At least if the example @zcbenz provided still works.

**Comment by sergiovilar** [comment]
@buschtoens but in the example the webpage must implement this code... not cool.

**Comment by buschtoens** [comment]
That's because the media features are provided by Chromium, not by electron.

In the end it doesn't really matter where you choose the media device. If you absolutely need to, you could use the IPC API to control this from the main process side.
