### ISSUE TITLE
OS X three finger "look up" tap doesn't work inside Webview

### ISSUE THREAD

**Issue by shamrin** [electron/electron#4772]
Tapping with three fingers (and pressing `ctrl-cmd-d`) to open up dictionary on OS X doesn't work when doing it inside Webview. For example:

``` html
<h1>Hello World!</h1>
We are using node …
<webview src="data:text/plain,Try three-finger tap here." />
```

![untitled](https://cloud.githubusercontent.com/assets/510678/13723935/246ffe2c-e885-11e5-90dc-a485de5a89ff.gif)
- Electron version: electron-v0.36.11-darwin-x64
- Operating system: OS X 10.11

**Comment by codebytere** [comment]
Given that Webviews have changes significantly over the past several years (and the team [no longer recommends their use](https://electronjs.org/docs/api/webview-tag#warning)) and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!
