### ISSUE TITLE
Zombie processes and memory leaks.

### ISSUE THREAD

**Issue by niknickolas** [electron/electron#4817]
* Electron version: 0.36.9
* Operating system: Ubuntu 14.

After closing one of Browser Windows, on console appears zombie process, but after at about 5-10 seconds it is disappears, but if there are more zombie processes   than 5, electron  hangs. Memory starts leaking after each zombie process. 
I use electron under Xvfb on Ubuntu 14....
One electron app creates many Browser Windows for running some tasks from beanstalk queue after task is done  Browser Window is closed and new  Browser Window is creating for new task but it cannot going on for a long time 
because of zombie processes and memory leaks make  electron app to hang.

How to correct close Browser Window  ?

**Comment by baconface** [comment]
According to the quick start repo making the actual Browser Window object null on the close event should be all you need to do.
```javascript
win.on('closed', function() {
  win = null;
});
```
If that is in your main process then ```win.destroy();``` will fire off the close event and destroy it without interruption. Otherwise you will need to use ```win.close();``` to simulate the user clicking the close button.

**Comment by niknickolas** [comment]
Yes, I know about it, but in my case it does not work.
I use proxy server to enter internet but when proxy server closes connection with error net::ERR_PROXY_CONNECTION_FAILED. some listeners are still alive such as Browser.webContents.session.webRequest.onErrorOccurred that produces some events after closing Window Browser. Might it is calls some errors in background and I cannot  see them.

I use this code for closing all processes and listeners 

 let NetworkErrors = [
        'net::ERR_PROXY_CONNECTION_FAILED',
        'net::ERR_NETWORK_CHANGED',
        'net::ERR_CONNECTION_CLOSED',
        'net::ERR_CACHE_MISS'
    ];
 

    try {
        this.Browser.webContents.session.webRequest.onErrorOccurred((details) => {
          
            if (NetworkErrors.indexOf(details.error) > -1 && (this.getMainUrl() === details.url)) {
                Helper.log(true, '\n >>> SESSION WEB REQUEST ERROR \n', details.url, '\n', details.error, '\n');
                this.stop('FAIL');
            }

        });
    } catch (e) {
        Helper.log(true, '\n >>> SESSION WEB REQUEST ERROR LISTENER \n', e, '\n');
    } 



TaskRunner.prototype.stop = function stop (status) {

    try {

        this.Browser.on('LISTENING:STOPPED', ()=> {
            try {
                this.Browser.webContents.session.webRequest.onErrorOccurred(null, null);
            } catch (e) {
                Helper.log(DEBUGGING || true, '\n !!!! >>> STOP BROWSER FOR JOB', this._jobId, e);
            }

            try {
                this.Browser.webContents.session.removeAllListeners();
            } catch (e) {
                Helper.log(DEBUGGING || true, '\n !!!! >>> STOP BROWSER FOR JOB', this._jobId, e);
            }

            try {
                this.Browser.webContents.removeAllListeners();
            } catch (e) {
                Helper.log(DEBUGGING || true, '\n !!!! >>> STOP BROWSER FOR JOB', this._jobId, e);
            }

            try {
                this.Browser.webContents.removeAllListeners();
            } catch (e) {
                Helper.log(DEBUGGING || true, '\n !!!! >>> STOP BROWSER FOR JOB', this._jobId, e);
            }

            this.Browser.once('closed', ()=> {
                Helper.log(DEBUGGING || true, '\n !!!! >>> CLOSED BROWSER FOR JOB', this._jobId);
                try {
                    this.Browser.removeAllListeners();
                } catch (e) {
                    Helper.log(DEBUGGING || true, '\n !!!! >>> STOP BROWSER FOR JOB', this._jobId, e);
                }
                try {
                    this.Browser = null;
                } catch (e) {
                    Helper.log(DEBUGGING || true, '\n !!!! >>> STOP BROWSER FOR JOB', this._jobId, e);
                }
                this.event.emit(status);
            });

            this.clearTasks()
                .Browser.close();
        });

    } catch (e) {
        this.event.emit(status);
    }

    this.Browser.webContents.send('STOP:LISTENING');


};

**Comment by zcbenz** [comment]
Can you provide a reproducible example?

**Comment by niknickolas** [comment]
Hello, Chang Zhao.

There is my project in zip file.



2016-03-27 5:17 GMT+03:00 Cheng Zhao <notifications@github.com>:

**Comment by niknickolas** [comment]
Hello, Chang Zhao.

There is my project https://github.com/niknickolas/task-runner

2016-03-28 12:54 GMT+03:00 Nik Nickolas <niknickolas@gmail.com>:

**Comment by zcbenz** [comment]
It is impossible to any of us to just debug your app, unless you can make the example minimal so we can obviously see the problem of Electron, otherwise we have to assume it is a bug of your app.

**Comment by niknickolas** [comment]
Hello.

Ok, I will change the app for the best test

2016-03-31 13:45 GMT+03:00 Cheng Zhao <notifications@github.com>:

**Comment by niknickolas** [comment]
Hello.

You can test my app but be careful, I set maximum number of working
browsers for
each tube to 50, if you have more memory operation cat you increase this
variable MaxNumberOfWorkingBrowsersForEachtube;

use the access content through a proxy server, for more accurate testing , it
would be better if most ip addresses are non-working, you will get result
faster


/*
 * proxy = null; if don't use proxy
 * */
let proxy = {
    address: 'ip:port',
    credentials: ['login', 'password']
};

/*
 * I don't use proxy
 * */
proxy = null;



2016-03-31 13:53 GMT+03:00 Nik Nickolas <niknickolas@gmail.com>:

**Comment by zcbenz** [comment]
Following apps are perfect examples of minimal test cases:

https://github.com/nathansobo/disable-renderer-backgrounding-test-case
https://github.com/kamesh-a/electron-samples/tree/master/willDownload
https://github.com/davej/electron-execSync-test

A minimal test case should only include necessary information to show the problem, like, calling a certain API of Electron leaks memory, instead of, your app doing complex things and there is memory leak. The latter mostly sounds like there is bug in your code.

**Comment by niknickolas** [comment]
I think, minimal test cases can only show you that api works perfect but
what about if app is working for a long time and doing complex things, only
after that you can see whole result.

I don't say that I am good programmer, yes I can do lot of mistakes. What
is real problem ?
Is it  closure that doesn't let garbage collector do its job or it is some
other thing ?

2016-04-01 8:03 GMT+03:00 Cheng Zhao <notifications@github.com>:

**Comment by niknickolas** [comment]
Hello.
I  remembered one feature that when I run my application on the server very
quickly ran out of file descriptors, and for this I increased the limit.
May it give you some idea.

2016-04-01 12:00 GMT+03:00 Nik Nickolas <niknickolas@gmail.com>:

**Comment by baconface** [comment]
What I think zcbenz is trying to say is there are two types of things that can cause issues. The first is a bug in your application and the second is a bug in his application. To show him his bug you would typically find what caused it and make a reproducible example. One that would be a test case interchangeable with other Electron projects and not just yours.

**Comment by zcbenz** [comment]
> I think, minimal test cases can only show you that api works perfect but
> what about if app is working for a long time and doing complex things, only
> after that you can see whole result.

If that is the case, I'm afraid no one except yourself will be interested in looking into it.
