### ISSUE TITLE
v0.37.x not send kerberos ticket

### ISSUE THREAD

**Issue by StyleEX** [electron/electron#4825]
* Electron version: >=0.37
* Operating system: ubuntu linux x64

When server send header 'WWW-Authenticate: Negotiate' electron not send kerberos ticket. 
`app.allowNTLMCredentialsForAllDomains(true)`  is called.

On electron v0.36.x it work's fine.

**Comment by thojansen** [comment]
I can verify that. Just tried to get NTLM based auth. working to connect to our exchange API. 0.36.12 is still working.

**Comment by thojansen** [comment]
@zcbenz any idea why this is happening/ how that could be fixed? Maybe you can add a disclaimer to the API.

**Comment by paulcbetts** [comment]
@StyleEX @thojansen Can you try this with v1.1.1?

**Comment by thojansen** [comment]
Sure, just tried it and it is still broken (as mentioned this is since 0.37.x).
- v1.1.1 gives a 401 response (anonymous request disallowed) and does not send NTLM headers
- v0.36.12 gives a 200 response and sends NTLM headers

**Comment by justindujardin** [comment]
@thojansen can you confirm that the latest builds fixed this problem for you?

**Comment by thojansen** [comment]
yes, this is working
