### ISSUE TITLE
Lost access to dialog after hiding bound browser window

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#4849]
- Electron version: 0.36.11
- Operating system: osx

``` coffeescript
win = new BrowserWindow(...)

## show the dialog bound to the window instance
dialog.showOpenDialog win, {properties: ["openDirectory"]}, (paths = []) ->

win.hide()
... later on...
win.show()
```

The problem is that after you hide the browser window and then show it - the dialog is lost and will not display again. Programmatically attempting to show the dialog again does not work either.

It will display correct as long as you don't pass the window instance as an argument.

``` coffeescript
## this works
dialog.showOpenDialog {properties: ["openDirectory"]}, (paths = []) ->
```

**Comment by zeke** [comment]
I can reproduce this on Electron 1.4.3, OS X 10.11.6.

The code in the above comment has some syntax errors. Here's how I'm able to reproduce:

```js
dialog.showOpenDialog(mainWindow, {properties: ["openDirectory"]}, (paths = []) => {
  console.log('closed dialog')
})

mainWindow.hide()
```

The error only seems to occur if `hide()` is called programmatically. Even if the call to `hide()` is delayed, the problem persists:

```js
// window still disappears
setTimeout(function() { mainWindow.hide() }, 3000)
```

Switching windows manually or invoking <kbd>Command</kbd><kbd>H</kbd> to hide the windoes does not cause any issues.

**Comment by kevinsawicki** [comment]
> The code in the above comment has some syntax errors

Yeah, I think it is CoffeeScript.

**Comment by zeke** [comment]
It's Coffeescript, but I think it's also not properly calling the `showOpenDialog` method. Unless I'm missing something, that `["openDirectory"]` array should be a value in the options object: `{properties: ["openDirectory"]}`

**Comment by brian-mann** [comment]
Yes, it is coffeescript. Up until fairly recently most of `electron` was in coffeescript so I felt safe posting that, haha.

Correct, I apologize, it should be `{properties: ["openDirectory"]}`.

**Comment by zeke** [comment]
No worries, @brian-mann! Just want to clarify how to reproduce. I'm working on a fix for this.

**Comment by leethomas** [comment]
I think we're blocked on this one: https://bugs.chromium.org/p/chromium/issues/detail?id=667602

Also I searched around and someone reported that calling `orderOut` removes attached sheets all the way back in 2006.

**Comment by dkfiresky** [comment]
I think the described issue also represents mine: when I close the main window and try to open a directory via the `File` > `Open...` there is no `Open` dialog. Only after creating new window it works again.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `1.6.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
