### ISSUE TITLE
Setting the Title Bar Color for Windows 10

### ISSUE THREAD

**Issue by feross** [electron/electron#4856]
Would be great if Electron offered an option for this.

<img width="910" alt="e0eda051a2ef9f1aac3c48cd574cfcb3bd0dbe9f" src="https://cloud.githubusercontent.com/assets/121766/13901552/120dc948-ede5-11e5-9eae-e83e60865540.PNG">

**Comment by paulcbetts** [comment]
:+1:, this would be super cool but I think this is only available to Universal apps :(

**Comment by erusev** [comment]
This would indeed be great.

**Comment by felixrieseberg** [comment]
@paulcbetts Since we'll work on putting apps into AppX next week, we might as well work on this. Since it'd be appx-only (and probably won't work for vanilla exe), it doesn't have to make its way into Electron Core, but I'm happy to provide a little Node module that does the work.

Obviously, if I manage to call into `Windows::UI::ViewManagement` from the exe, we're good and I'll PR for core.

**Comment by paulcbetts** [comment]
I don't think this would work even in an AppX, because we're not creating a CoreWindow instance, we're creating a Win32 window.

**Comment by felixrieseberg** [comment]
Soooooooo... long story short, I was too optimistic, Paul is as always right, and this won't be possible - you can use `{ frame: false }` to get rid of the whole Chrome (and then build your own), but otherwise, there's no way to change the title bar color for just one HWND. Sorry :|

**Comment by MehediH** [comment]
Any update on this?

**Comment by felixrieseberg** [comment]
Nothing has changed - we won't be able to do this unless we go with a custom window frame, which we should just leave to the user. If you want a custom frame and don't want to build it yourself, I recommend https://github.com/gabrielbull/react-desktop.

**Comment by icharge** [comment]
Slack app can do this...

**Comment by MarshallOfSound** [comment]
@icharge The slack app has a custom window frame as described by @felixrieseberg

**Comment by icharge** [comment]
@MarshallOfSound It's look so real

**Comment by marcus13345** [comment]
For others who may stumble into this thread like I did, there does exist packages that will automatically give you a universal app/metro style title bar. like [electron-titlebar-windows](https://github.com/sidneys/electron-titlebar-windows)

**Comment by JT-Potato** [comment]
The issue with using a custom title bar in electron is that we can't call the Windows 11 split screen menu. Any solutions?
