### ISSUE TITLE
Move to electron GitHub organization

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#4874]
:truck: The plan is to move all Electron-related repositories to the [electron](https://github.com/electron) organization on **April 4th, 2016**.

:house: This will be the home for any future Electron-related repositories as well. The Atom organization will only contain Atom-related projects.

:file_folder: :dash:  The following repositories will be moved over:

- [x] [electron](https://github.com/atom/electron)
- [x] [brightray](https://github.com/atom/brightray)
- [x] [brightray_example](https://github.com/atom/brightray_example)
- [x] [libchromiumcontent](https://github.com/atom/libchromiumcontent)
- [x] [electron.atom.io](https://github.com/atom/electron.atom.io)
- [x] [electron-quick-start](https://github.com/atom/electron-quick-start)
- [x] [node fork](https://github.com/atom/node)
- [x] [node-mksnapshot](https://github.com/atom/node-mksnapshot)
- [x] [node-chromium-pickle](https://github.com/atom/node-chromium-pickle)
- [x] [chromium-breakpad](https://github.com/atom/chromium-breakpad)
- [x] [asar-require](https://github.com/atom/asar-require)
- [x] [asar](https://github.com/atom/asar)
- [x] [debian-sysroot-image-creator](https://github.com/atom/debian-sysroot-image-creator)
- [x] [crashpad](https://github.com/atom/crashpad)
- [x] [mini-breakpad-server](https://github.com/atom/mini-breakpad-server)

:busts_in_silhouette: All organization teams will be migrated by then so people with push access to any of these repositories will be invited to a new team in the `electron` organization.

:mega: Please comment with any concerns and feel free to `@`-mention people to make them aware of this change.

/cc @zeke @zcbenz @jlord

**Comment by baconface** [comment]
Could you not use the electron name from what appears to be an inactive Github account or was the selection of the electronjs intentional without that factor?

**Comment by zeke** [comment]
@baconface we're working on it :)

**Comment by kevinsawicki** [comment]
> Could you not use the electron name from what appears to be an inactive Github account or was the selection of the electronjs intentional without that factor?

We are now going with just `electron` for the organization name 👍 ⚡

**Comment by paulcbetts** [comment]
@kevinsawicki Can you create an electron-archive org and move these repos to it:

* https://github.com/electron/compile-cache
* https://github.com/electron/electron-manifesto

**Comment by kevinsawicki** [comment]
> Can you create an electron-archive org and move these repos to it:

👍 done, https://github.com/electron-archive

**Comment by deepak1556** [comment]
@kevinsawicki include [debian-sysroot-image-creator](https://github.com/atom/debian-sysroot-image-creator) to the electron org repo list.

**Comment by kevinsawicki** [comment]
@deepak1556 added 👍

**Comment by kevinsawicki** [comment]
Going to start doing this over the next couple hours, starting with the smaller repos and moving over brightray, libchromiumcontent, and electron last.

**Comment by kevinsawicki** [comment]
The repositories have been moved over, closing this out :ship:
