### ISSUE TITLE
Provide official .d.ts typings for Electron

### ISSUE THREAD

**Issue by miniak** [electron/electron#4875]
There is github-electron.d.ts in the DefinitelyTyped repository, however it is quite out of date (I have several PRs with added/updated APIs pending). Wouldn't it make sense to somehow coordinate this effort? Or maybe even generate the documentation from a .d.ts file instead of writing it in Markdown. Keeping the typings in a separate repository makes it really hard to keep it up to date.

Ideas?

**Comment by kevinsawicki** [comment]
Refs #3375 /cc @jlord @zeke

**Comment by zcbenz** [comment]
VS Code is maintaining a nice `electron.d.ts`:
https://github.com/Microsoft/vscode/blob/70de2237720d9d756c803fe68e05d0dd3034ef15/src/typings/electron.d.ts

/cc @bpasero

**Comment by OlsonDev** [comment]
VS Code's `electron.d.ts` is much more out of date than the @miniak's aforementioned `DefinitelyTyped` typings.

**Comment by bpasero** [comment]
The one we use in VS Code is really just the one from DefinitelyTyped and might be a bit out dated as of today (I took it some months ago).

**Comment by felixrieseberg** [comment]
A decent solution is to use YUIDoc (or something else along the same lines) and use that to create typings. That way, it benefits everyone (TypeScript people, VSCode users, Flow users, etc.).

**Comment by zeke** [comment]
Work in progress: https://github.com/electron/electron/pull/6408

**Comment by mmc41** [comment]
Yes, please - would really, really like an official typescript definition file (if possible embedded in the npm like Angular2 does for typescript). Besides making typescipt users happy this would improve the code editor experience a lot in IDE's (also for javascript users). This is the most wanted feature for me.

**Comment by mmc41** [comment]
What is the status on this?

**Comment by zeke** [comment]
@mmc41 I'm working on generating a JSON object that describes the Electron APIs. Hoping to ship that soon. Hopefully we can use it as a starting point for generating a TypeScript definition file. I will post back here when the JSON doc is ready.

**Comment by mmc41** [comment]
@zeke Thanks for the update. I recommend another approach. It would seem to be much more easier to create a (commented) typescript definition file and generate JSON and other documentation artifacts from those. An analog situation is if you want both digital and analog copies of a video. If you start with analog you are likely to have great difficulty in producing a high quality digital copy. The typescript definition file (possibly with some comments if needed) is the digital equivalent. Another benefit of starting with the typescript version is that you can use it internally even if you do not do typescript yourself to feed IDE's (you will be amazed by the help that various IDEs can give based on a typescript definition file). You can also beta-test the typescript definition file as people can use it even if it is not finished. A JSON is not really useful in itself for people.

**Comment by mmc41** [comment]
@zeke Note that someone else have create a draft typescript definition file that could be used as a starting point (properly easier to use this than to start from scratch - especially on the bumpy json road you mentioned):  "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/6d4239b89e0452b66cb7850ef9842aff71e370be/github-electron"

**Comment by zeke** [comment]
> It would seem to be much more easier to create a (commented) typescript definition file and generate JSON and other documentation artifacts from that.

I agree that would be a good starting point if Electron was a new project, but the content in `docs/api` is currently our source of truth about how all the APIs work. Maybe we can eventually move toward using a schema as the canonical thing, but for now it's the docs.

Thanks for sharing that `github-electron` typing. I have seen it and would definitely consider using it as a starting point.

**Comment by mmc41** [comment]
@zeke BTW: Interesting enough jere is a tool for doing the reverse of what you are doing - generating json from typescript : http://lbovet.github.io/typson-demo/ 
:-)

**Comment by miniak** [comment]
I am maintaining those typings, I am willing to help if possible. Btw this is the latest version: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/github-electron

**Comment by miniak** [comment]
I also think the a TypeScript definition with properly documented arguments and return values would be a better source of truth.

**Comment by MarshallOfSound** [comment]
@miniak @mmc41 Personally (although after some research DefinitelyTyped looks very useful) I don't think that anyone should have to learn a new syntax / style of documentation purely to document methods inside Electron.

Markdown is a global language that most if not all devs know the basics of.  I don't think we should be expecting devs to contribute to typescript definitions as our source of truth when an unknown proportion of them may have never come close to using typescript before.

You also have to take into account readability of the docs.  A typescript definition is all very nice but it doesn't fit very well with the way [electron.atom.io](https://github.com/electron/electron.atom.io) displays the docs.

Considering the current majority usage of the docs is to display easily readable content on either GitHub or the Jekyll Electron site.  I think we should proceed with @zeke 's cool doc parser and then potentially write a converter to take that JSON file and turn it into a definitely typed declaration file.

The alternative (switching our source of truth to typescript files) would require writing even more converters to allow the current usage of the docs to continue (typescript -> JSON, typescript -> markdown / jekyll, Etc.)

**Comment by sedwards2009** [comment]
If you want to create type declaration files then contributors are going to have to learn and use some kind of formal language to write the function/methods descriptions in. That can be TypeScript or some other ad hoc system which the doc parser reads. But either way, a formal style of documentation will be needed and contributors will have to know or learn it.

TypeScript has the advantage that lots of people know it already, and it is a formal language for specifying types as used in a JS program. It is also well documented etc.

**Comment by mmc41** [comment]
The problem with markdown (as any text) is that it is ambiguous and there is no way for a machine to check for errors. With markdown you essentially have to invent your own language, parsers and other technology in order to produce the needed typescript declarations.

**Comment by enlight** [comment]
I haven't looked at the JSON file that @zeke has been working on in https://github.com/electron/electron/pull/7120 to see if it contains sufficient type information to generate type definitions, but assuming it will at some point contain all the requisite information it could be fed to https://github.com/RyanCavanaugh/dts-dom to generate the TypeScript type definitions.

**Comment by felixrieseberg** [comment]
No worries everyone, we'll get a definition file eventually - we discussed a few times amongst the maintainers what the best way here is, and we have to consider the time and effort of those working on electron above everything else. Nothing is more useless than an outdated definitions file :wink:

As soon as Zeke is done with his JSON approach, I'll make sure that we have an official first-party d.ts.

**Comment by rootscript** [comment]
Just to add a little newbie view.  I use `npm` to install `typings`.  Doing a search for electron returns these results.

```
typings search electron        
Viewing 9 of 9

NAME                     SOURCE DESCRIPTION VERSIONS UPDATED                  HOMEPAGE                                              
electron                 env                2        2016-09-09T06:56:30.000Z                                                       
electron-builder         dt                 1        2016-03-16T15:55:26.000Z https://github.com/loopline-systems/electron-builder  
electron-json-storage    dt                 1        2016-03-24T00:02:15.000Z https://github.com/jviotti/electron-json-storage      
electron-notifications   dt                 1        2016-08-12T19:51:47.000Z https://github.com/blainesch/electron-notifications   
electron-notify          dt                 1        2016-08-16T15:10:39.000Z https://github.com/hankbao/electron-notify            
electron-packager        dt                 1        2016-03-16T15:55:26.000Z https://github.com/maxogden/electron-packager         
electron-window-state    dt                 1        2016-02-12T17:13:54.000Z https://github.com/mawie81/electron-window-state      
github-electron          dt                 1        2016-09-14T12:41:56.000Z http://electron.atom.io/                              
github-electron/electron dt                 1        2016-08-17T06:16:22.000Z https://github.com/electron-userland/electron-prebuilt
```

**Comment by zeke** [comment]
@MarshallOfSound and I are actively working on this, and with each release we are inching toward an [`electron-api.json`](electron.atom.io/blog/2016/09/27/api-docs-json-schema) that will have all the necessary data to compile a TypeScript definition file. https://github.com/electron/electron/pull/7379 is an important piece of that, and with any luck it will land in the next release, 1.4.4

To track progress, watch [MarshallOfSound/Electron-DefinitelyTyped](https://github.com/MarshallOfSound/Electron-DefinitelyTyped)

**Comment by crocket** [comment]
I want to automatically generate a GHCJS binding to electron, should I have a GHCJS binding automatically generated from `electron-api.json` or `electron.d.ts`?

It seems both are not ready for a GHCJS binding at this point.

**Comment by MarshallOfSound** [comment]
@crocket In order to use the maximum amount of information you should probably go from the JSON reference.  Unless their is already a converter from `.d.ts` to GHCJS in which case just wait for `.d.ts` to be fully functioning and then run it through a converter 👍

**Comment by crocket** [comment]
@MarshallOfSound https://github.com/mgsloan/ghcjs-typescript is a stalled work, and it is supposed to convert `.d.ts` to haskell modules when it's completed.

Is `electron-api.json` ready for GHCJS binding?

As far as I know, optional object elements aren't unambiguously marked, yet.

**Comment by MarshallOfSound** [comment]
> Is electron-api.json ready for GHCJS binding?

Lot's of the information you would need to generate bindings is already in the JSON output.  The `optional` object element thing can be tracked #7370

> Also, I'm looking for a way to automatically generate a GHCJS binding to NodeJS. However, NodeJS project doesn't have any typing information, yet.

Can't really help with that, you might be better off converting the existing `node.d.ts` file to GHCJS

**Comment by crocket** [comment]
Will `electron-api.json` become stable after #7370 is closed?
The closure of #7370 introduces a breaking change in `electron-api.json`, and I don't know if other issues will break `electron-api.json`, too in the near future.

When do you think `electron-api.json` will become stable as a parser input?

**Comment by MarshallOfSound** [comment]
> The closure of #7370 introduces a breaking change

I disagree, that wouldn't be breaking.  Currently there is no way to determine if a parameter is optional, that issue will add a way.  Not a breaking change rather a new feature.

> When do you think electron-api.json will become stable as a parser input?

I already use it in my `electron-definitelytyped` parser that is still a WIP.  Updates haven't broken the parser yet 👍

**Comment by crocket** [comment]
I see. Will `electron.d.ts` be able to express optional parameters or optional object elements? How much information do you lose during conversion of `electron-api.json` to `electron.d.ts`?

**Comment by MarshallOfSound** [comment]
> I see. Will electron.d.ts be able to express optional parameters or optional object elements? How much information do you lose during conversion of electron-api.json to electron.d.ts?

You don't lose any information currently, as more things get added to the JSON output I can add more things to my `.d.ts` output

> By the way, https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/electron/github-electron.d.ts was updated to electron 1.4.3 already.

Yeah, that typing file is the entire point of this issue.  It is out of date, inaccurate in lots of places and is missing documentation that is fixed / updated / added over time.  The entire purpose of the JSON api is to export the docs for an Electron version in a standard way.  Then the point of my `.d.ts` converter is to take the standard JSON file and convert to a definitely typed file.

Then on release day we can generate a `.d.ts` file with no manual interaction that we can guarantee is correct as it is parsed directly from the documentation.

**Comment by zeke** [comment]
Getting closer! https://github.com/electron/electron/pull/7857

**Comment by aculeat** [comment]
Hello, any updates on the status of this? I'd love to get going on a project using TS with Electron but I'm hesitant to start without official typings.

**Comment by HitomiTenshi** [comment]
Same here!

**Comment by zeke** [comment]
The latest is this: before we officially bundle an `electron.d.ts` file within the `electron` npm package, we need to teach the [docs linter](https://github.com/electron/electron-docs-linter) to parse the docs for Electron's [webview](https://github.com/electron/electron/blob/master/docs/api/webview-tag.md) tag. I belive this is the last blocker.

If you want to take the current WIP file for a spin, see https://github.com/electron-userland/electron-prebuilt/pull/209

See also https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12888 for progress on deprecating/replacing the third-party definitions.

**Comment by aculeat** [comment]
Thanks for the reply! The WIP file should be good enough for now :)

**Comment by MarshallOfSound** [comment]
@aculeat The most up to date file can be found in this gist

https://gist.github.com/MarshallOfSound/8b1b1aa0773fab1a9178cc2d1025dadd

**Comment by aculeat** [comment]
Great, thanks!

**Comment by chrilith** [comment]
Don't `npm install -D @types/electron`do the trick?

**Comment by MarshallOfSound** [comment]
@chrilith They are third-party provided typings written by hand.  This issue is about generating first-party typings and shipping them with the "electron" npm module.

**Comment by unional** [comment]
As I do more work in TS, I start to realize that JSON -> type definition is not as good as type definition -> JSON (I think the same hold true for JSON schema, but need to verify).

The reason is that there are information cannot be represented in JSON compare to a formal type specification language such as TypeScript or Flow.

For example. consider the following:

```ts
export function foo(options: Options) { ... }

export interface Options {
  a: string,
  b: {
    c: string
    d?: int
  }
}
```

While this can be used, it is actually better to be written as:

```ts
export function foo(option: foo.Options) { ... }

export namespace foo {
  export interface Options {
    a: string,
    b: Options.B
  }

  // this is advance
  export namespace Options {
    export interface B {
      c: string,
      d?: int
    }
  }
}
``` 

This way, you can do the following when consuming this library:

```ts
import { foo } from 'some-foo'

function myFoo(option: MyOption) { ... }

interface MyOption {
  a?: string // make a optional
  b: foo.Options.B // while keep and reuse type of B
}
```

I think you will have a hard time to generate type definitions like this from JSON.

My two cents. 🌷 

Of course, for the first version, the easy way is the best way. 😄

**Comment by zeke** [comment]
> I think you will have a hard time to generate type definitions like this from JSON

Hard indeed, but it is happening: https://github.com/electron/electron-typescript-definitions

**Comment by sohail85** [comment]
Hi @zeke  : This question might not sound right question to be asked in this thread, but  being starter on typescript and following this thread made me a bit confused.
In this thread we started to talk about JSON([#6408](https://github.com/electron/electron/pull/6408)) and then [electron doc linter](https://github.com/electron/electron-docs-linter) and then typedefination, 
what I understood you will use JSON to make typedefination for electron and I am not sure about linter if we need that since typedefination will be used as a helper and provide intellisense, correct me if I am wrong.
I need to use Electron's type definition in my project and it seems to me there are 3 versions of it available one which maintain by VS code, one by definatly typed and one which you guys are working on, which type definition is safe to work with? 
usually by running npm install we get typing folder but its not the case with following command, am I missing something? `npm install electron-typescript-definitions --save` 
Thanks for you hard work and again sorry to ask this question here.

**Comment by kevinsawicki** [comment]
The `electron.d.ts` file is now released with the electron npm module and published with each release on https://github.com/electron/electron/releases

Closing this out, please open new issues for specific issues with the current file.
