### ISSUE TITLE
Document enabled and visible properties for MenuItem

### ISSUE THREAD

**Issue by erkyrath** [electron/electron#4884]
* Electron version: 0.36.11.
* Operating system: OSX 10.11.3

The MenuItem doc (https://github.com/atom/electron/blob/master/docs/api/menu-item.md) describes how to create an item with various initial options. But it fails to mention that you can update `enabled` and `visible` on the fly, after the menu is created. It tooks me months to figure that out...

(Comment https://github.com/atom/electron/issues/937#issuecomment-67543939 indicates that you can update `checked` on the fly as well, but `checked` isn't working for me at all, right now.)

I can write up this doc addition, but I want to make sure my understanding is correct.

**Comment by bengotow** [comment]
(The docs have been updated via the PR so I'm going to close this—thanks!)
