### ISSUE TITLE
Crash on app.quit if there are multiple windows open

### ISSUE THREAD

**Issue by juturu** [electron/electron#4894]
* Electron version: 0.37.2
* Operating system: Windows

Performing app.quit with multiple windows open is causing a crash on executing browserwindow.close()

stack
` 0  electron.exe!atom::NativeWindow::RequestToClosePage() [native_window.cc : 373 + 0xc]
 1  electron.exe!atom::`anonymous namespace'::NativeWindowClientView::CanClose() [native_window_views.cc : 96 + 0x1c]
 2  electron.exe!views::Widget::Close() [widget.cc : 601 + 0x5]
 3  electron.exe!atom::WindowList::CloseAllWindows() [window_list.cc : 74 + 0x8]
 4  electron.exe!mate::internal::Dispatcher<void >::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const &) [function_template.h : 228 + 0x16]`

**Comment by zcbenz** [comment]
Can you provide a reproducible example for this?

**Comment by zcbenz** [comment]
Closing until more information is provided.
