### ISSUE TITLE
webContents.print doesn't do anything on Windows 7

### ISSUE THREAD

**Issue by mousavian** [electron/electron#4906]
* Electron version: 0.37.2
* Operating system: Windows 7 64-bit

I have tried to call `mainWindow.webContents.print`, which showed the printer dialog but when I choose the printer, it just do nothing. Not even an error.

I have tried with multiple printers such as physical and virtual one (like print to XPS/PDF).

I suspect its my code, so I tried this [this example](https://github.com/hokein/electron-sample-apps/tree/master/printing) as well but I got same result.

After that I tested it on another computer (Microsoft surface 4) and still nothing.

Then  I run the same code on Mac OS, and it was working ok.

So I'm confusing right now and wondering if anybody else have same issue or not...

PS: `webContents.printToPDF` was also okay on windows since I guess has nothing to do with OS printing functionality.

**Comment by pantsel** [comment]
Same problem here. Had to roll back to v0.36.12 where print is working.

**Comment by RobsonMi** [comment]
The problem seems to be related to missing pdf.dll from electron packages since 0.37.3.

A temporary solution is to copy pdf.dll from 0.36.12 electron zip to 0.37.3 or 0.37.5 zips for windows and all will work as far as I tested.

**Comment by mousavian** [comment]
@RobsonMi yea. just tested and worked fine. 
I wasted a lot of time on this and never thought "pdf.dll" has something to do with "print".

**Comment by RobsonMi** [comment]
The fix didn't make it to 0.37.6, right? Should we expect it in 0.37.7?

**Comment by zcbenz** [comment]
@RobsonMi It is in 0.37.6, is printing still not working for you?

**Comment by RobsonMi** [comment]
Nope. Pdf.dll is still missing in electron zip.

**Comment by zcbenz** [comment]
@RobsonMi You don't need pdf.dll to have printing support from 0.37.6, there was a change in Chromium that made it impossible to separate printing code into a separate library.

**Comment by RobsonMi** [comment]
Okay, it works. My bad!

But why print quality is worse on windows than on linux? And also is it true that electron on windows does not support @page CSS tag? I am using it with success on linux but on windows I always get portrait layout.

**Comment by davemackintosh** [comment]
@zcbenz I still see this issue in the latest Electron, with or without `pdf.dll` if I open the print dialog everything works fine until I select a printer, then until I unfocus the print dialog and refocus click events never make it to the interface. Hover effects like button highlights still work but clicking does nothing (Like there's an invisible prompt/alert somewhere)

**Comment by barbalex** [comment]
I have this issue in electron 1.6.1

**Comment by barbalex** [comment]
yep, downgrading to 1.4.15 makes printing work again

**Comment by barbalex** [comment]
where can I find "pdf.dll" and where would I have to place it when importing electron via npm?

**Comment by mousavian** [comment]
@barbalex just follow [RobsonMi's comment](https://github.com/electron/electron/issues/4906#issuecomment-208084062).
I remember I found pdf in [0.36.1 version](https://github.com/electron/electron/releases/tag/v0.36.1)

**Comment by barbalex** [comment]
Thanks for helping, @mousavian 

I did read that comment. But I don't get what an "electron zip" is, especially as electron is installed via npm, not from a zip file.

Maybe @RobsonMi meant the release built from the project. This includes an .exe file and a folder with project files. I don't see how the "electron zip" could relate to these though.

I can download a zip file from https://github.com/electron-userland/electron-prebuilt. But that contains no "pdf.dll".

By the way: I am using https://github.com/chentsulin/electron-react-boilerplate which in turn uses electron-builder to build a release.

**Comment by nickwinger** [comment]
Hi guys,

this issue is still here with electron 1.6.1 and newer. 
This is actually one of the worst bugs if you need an app that can print.

I downgraded to Version 1.4.15, it's working with this electron version.

Cheers,
Nick

**Comment by alexmccabe** [comment]
I'm still having this issue, all I get is the status `spooling`.

**Comment by JohnAnthony** [comment]
Same issue here. Rolling back to 1.4.15 worked, but it's a shame to not be using the latest version or manually handle the DLL dependency.

**Comment by ChristianFranke** [comment]
Hey guys, does it work in the current version 1.7.5?

**Comment by VinKamat** [comment]
I am on 1.6.13, and the silent : true doesn't work, and pops open the default windows print settings dialog.
OS: Windows 10. Copying pdf.dll from 0.63.1 in to the node_modules/electron/dist folder didn't help.

Any ideas?

**Comment by barbalex** [comment]
Just to add: This problem happens to me on Windows 10

**Comment by ishwarrimal** [comment]
I am using 1.7.6 and facing the same issue. Is there any solution for this issue?

**Comment by LoganArnett** [comment]
Same issue, running on 1.6.10 and Windows 10

**Comment by ishwarrimal** [comment]
@LoganArnett The problem for me was the electron version. Also keep in mind to update the local electron version as well along with global. In my case i had updated electron globally, but my app was still running in 1.6.something.

**Comment by codedeus** [comment]
@VinKamat where you able to get the silent: true working?

**Comment by gtkpr** [comment]
I'd like to know too? I'm using 3.0.10, and there doesn't seem to be a `pdf.dll` included, which is the culprit for why one can't print to PDF according to [this SO thread?](https://stackoverflow.com/questions/36509989/electron-printing-on-windows-doesnt-work) The normal `webContents.print` works fine nonetheless, but what do we gotta do to get some PDF up in here?
