### ISSUE TITLE
Document the new REPL

### ISSUE THREAD

**Issue by zeke** [electron/electron#4913]
A followup to https://github.com/atom/electron/pull/4883

**Comment by hellonearthis** [comment]
Could the node.js documents and tutorials be used to help form the documentation?
https://nodejs.org/api/repl.html

**Comment by zeke** [comment]
Yes! That would be awesome. Would you like to take a shot at it, @hellonearthis?

**Comment by hellonearthis** [comment]
I could give it a try,  what area of the docs will it go into? 
I've not done docs before but because it's all GitHub based my mistakes can be fixed up :)

**Comment by hellonearthis** [comment]
Well it's the first time I have done something like this on github and on a project.
Had to learn what to actually do and think I have added the RELP document to the Electron/docs/api 
I put it there as that's where node.js stored the document, under the api.

I did a pull request so I guess it's out there.   If I've done it all wrong then please let me know where so I can learn.

**Comment by zeke** [comment]
Thanks, @hellonearthis. I left some feedback over at https://github.com/electron/electron/pull/6979 -- you might want to rename your PR title from "Master" to something that explains your intent.

**Comment by amtj** [comment]
https://github.com/electron/electron/pull/7449

**Comment by kevinsawicki** [comment]
Fixed by #7449

**Comment by zeke** [comment]
🎉
