### ISSUE TITLE
[Linux] shell.openExternal can hang

### ISSUE THREAD

**Issue by AsaAyers** [electron/electron#4916]
* Electron version: 0.34.5 in Atom
* Electron version: [unknown] in the [v2.0.1 version of Slack](https://slack.com/downloads)
* Operating system: Ubuntu 15.10

Under Linux `shell.openExternal` uses `xdg-open`. If your default browser is Firefox and it's already open then `xdg-open` only runs long enough to open the new tab then exits. But if you didn't have Firefox open `xdg-open` lives for the life of Firefox and the electron app hangs until you close the browser.

I don't know if the same thing happens with Chrome.

**Comment by AsaAyers** [comment]
Now that I have my `xdg-open` configured to use Chrome I can verify it has the same behavior. `xdg-open` runs until Chrome exits and the electron app acts frozen.

**Comment by bengotow** [comment]
This has been reported a couple times by linux users of N1 — the issues typically look like this: https://github.com/nylas/N1/issues/1062. It seems that Firefox is particularly impacted because it doesn't return from xdg-open?

**Comment by AsaAyers** [comment]
Chrome and Firefox display the same behavior. This seems to just be the behavior of `xdg-open` because it also happens when I have it open an image.

If `xdg-open` launches an app then it remains running for the life of that app. If `xdg-open` is launching a new tab in an already running browser it exits once the tab is open.

The problem in this issue is that Electron assumes `xdg-open` will always be a quick launch and exit, so it waits for it to close to get the return code.

**Comment by zcbenz** [comment]
Closed with #5072.
