### ISSUE TITLE
Disable throttling of requestAnimationFrame

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#4925]
The `--disable-renderer-backgrounding` command line switch only disables throttling for timers, there is currently no way to disable throttling of `requestAnimationFrame`.

Refs https://github.com/atom/electron/issues/4317#issuecomment-190990964.

**Comment by Dillybob92** [comment]
@zcbenz  I'm not sure if these are correlated but if you use `win.setMinimizable(false);` it actually runs RAF in the background but only if you minimize the window by using WindowsKey+D.  Obviously a weird / unintuitive solution but just thought I'd say something incase it might have ties within `disable-render-backgrounding`

**Comment by nathansobo** [comment]
For posterity, what flag do we need to set now to disable backgrounding? Which version of Electron does it work on?

**Comment by zcbenz** [comment]
In the coming v0.37.6, you can use the `backgroundThrottling` option:

```js
new BrowserWindow({webPreferences: {backgroundThrottling: false}});
```

**Comment by OlsonDev** [comment]
@zcbenz Will this allow us to achieve >60 FPS or just maintain 60 FPS when the window is unfocused?

**Comment by Dillybob92** [comment]
@OlsonDev Yeah, it's  a great feature for games that are multiplayer and rely on RAF (with physics). Also, just in general, for animations. I am very please @zcbenz is adding this functionality to electron.

**Comment by iamisti** [comment]
NOT yet fixed. Just open performance monitor on your electron window and switch to a different one. Then going back to your electron window will show you that cpuy usage was VERY limited while it was running in the background.
Electron team PLS FIX THIS! IT's been years now!

**Comment by danidan95** [comment]
anything yet?

**Comment by iamisti** [comment]
looks like they ignoring it

**Comment by ProdigyView** [comment]
Any update on this?
