### ISSUE TITLE
WebRTCAdapter return stream if no one device is plugged in.

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#4933]
- Electron version: 0.36.7
- Operating system:Mac/Win

When call WebRTCAdapter.getUserMedia({audio: false, video: true}) will return stream if no video devices is plugged in. Should call reject with no error.

This stream can be identified as "wrong" using 'active' key in stream object, but since getUserMedia call return promise, major part of apps will define callbacks for resolve/reject. And in this case this will call resolve, and it's wrong.

**Comment by zcbenz** [comment]
Can you provide some code snippets that can show the problem?

**Comment by cumajkeee** [comment]
On pc with no camera plugged in try to call following:

`
if (navigator.webkitGetUserMedia) {
   navigator.getUserMedia({ audio: false, video: true },
      function(stream) {
         console.log(stream, stream.active);
      },
      function(err) {
         console.log("The following error occurred: " + err.name);
      }
   );
} else {
   console.log("getUserMedia not supported");
}
`

AR: This will call resolve with stream.
ER: Supposed to call reject since browser can't get access to camera.

**Comment by raphinesse** [comment]
This is still an issue in version 1.7.5 with the following updated code. 

```js
navigator.mediaDevices.getUserMedia({ audio: false, video: true })
  .then(stream => console.log('got camera stream', stream))
  .catch(err => console.log('cannot get camera stream', err))
```

**Expected output:** cannot get camera stream (...)
**Actual output:** got camera stream (...)

Tested on Ubuntu 17.04 and Windows 10 hosts.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
