### ISSUE TITLE
Ability to create Spotlight/Alfred like windows

### ISSUE THREAD

**Issue by florian** [electron/electron#4939]
Spotlight/Alfred (and other native apps like 1Password Mini) on Mac have a special behaviour, their windows are displayed above all other windows, but the last used app is still focused.
The closest I could find for Electron was the `alwaysOnTop` option, but it doesn't have the exact same behaviour.

My Electron app has a Spotlight/Alfred like floating window and the visibility of the window can be toggled with a hotkey. However after hiding the window, the last used application doesn't get focused, which is pretty annoying for the user.
E.g. if I type a message in Skype, open the floating window to quickly look something up and then close it again, I won't be able to keep typing in Skype. I have to click on the Skype window before that. Spotlight/Alfred don't have that problem.

Is there any way to replicate this behaviour in Electron?

**Comment by zcbenz** [comment]
You can create a always-on-top hidden window, and then call `showInactive()`.

**Comment by florian** [comment]
@zcbenz Sadly this isn't what I meant. While this will keep the last app focused, I'm not able to type in my app anymore.

Do you use a Mac? If you open Spotlight (Cmd + Space) you will be able to type into Spotlight (i.e it captures all keyboard and mouse events) while the last app is still shown as "focused" (maybe this isn't the right term to describe it).
With focused I meant that the name of the last app is still displayed in the top left of the menubar. The windows actions buttons (close, hide, fullscreen) are also colored, which in OS X shows that the window is focused.

<img width="159" alt="bildschirmfoto 2016-03-31 um 14 23 45" src="https://cloud.githubusercontent.com/assets/1564556/14175594/486037ae-f74c-11e5-9281-4b94403ad6d8.png">

**Comment by zcbenz** [comment]
Hmm what you want should be a way to prevent window from being focused.

**Comment by florian** [comment]
Thanks for reopening :)

Maybe OS X offers a standard way to implement those windows? It might be a possibility, since a bunch of 3rd party Mac apps (Alfred, 1PW Mini, …) have those windows.

**Comment by eyalse** [comment]
heya @florian, any updates? did you manage to create something similar to spotlight/alfred with electron?

**Comment by florian** [comment]
@zcbenz Any chance that this is coming to Electron soon?

**Comment by zaaack** [comment]
@florian app.hide() would meet your demand

**Comment by florian** [comment]
It has a similar behaviour and I also ended up using it. But it's not the exact same thing as the Spotlight/Alfred behaviour.

**Comment by joshaber** [comment]
https://github.com/electron/electron/pull/7296 is possibly related since it allows lots of different window levels.

**Comment by ajprax** [comment]
Hi @florian, it sounds like you have a workaround while this behavior isn't fully supported; are you happy with it? Would you be willing to share your solution?

**Comment by codebytere** [comment]
closing due to abandonment.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (101/100 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:60480 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dx1La-001588-I1
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:41:13 -0500
Date: Tue, 26 Sep 2017 18:40:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1506476424;
	bh=P3CxGuFqHc4XrvAq5OxMirAF5kHQ/PV5mGoOZobjcU8=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=OeW4dQVzDtrSBCA4SxA/xNH3pO/rYTE+5dNosTIdBuxzjHiNDEFVao6YrAfxJHWvy
	 7INyEtGceOi7NV/yE1NVYT39ptdb5xboi0J/23aWuD6+N0eN9rAht1wFmdFFTgIxpf
	 RoBHxnb2/z0U7JEkz0iUedqTH2h4LVKdOhOGpBiI=

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (100/100 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:49588)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-96d6-jcjackson=joe-jackson.net@sgmail.github.com>)
	id 1dx1LX-00155g-LV
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:41:10 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=wjenyoFtH7s5JVi0g1nlbINi1ys=; b=neVRG5dCLXEV8gU5
	uuaOKjnGssEnPghN1T/uax5B7iOHRyN7V7GemZ+FzO+kQxT0sbrSvFUfSwjQ3HG+
	FMhMKYj+2JIPnEMv1dY7TTDu7ZFncCprOR7n+zmGmd9M1ow+coE7Wn549AXoO3/3
	HQd9soBWlFgQulq5AEaX1THgJmQ=
Received: by filter0549p1mdw1.sendgrid.net with SMTP id filter0549p1mdw1-20565-59CB0183-32
        2017-09-27 01:40:19.755394343 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0007p1iad1.sendgrid.net (SG) with ESMTP id 4vNHMW9YQWCq_wUVJdTg0A
	for <jcjackson@joe-jackson.net>; Wed, 27 Sep 2017 01:40:19.708 +0000 (UTC)
Date: Wed, 27 Sep 2017 01:40:19 +0000 (UTC)

**Comment by florian** [comment]
Is not making progress on this really a reason to close the issue? I would still very much like to see this in Electron and apparently others are interested, too.

**Comment by awright415** [comment]
Not sure how it could be implemented, but the key seems to be using [NSPanel](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/WinPanel/Concepts/UsingPanels.html#//apple_ref/doc/uid/20000224) with [NSNonactivatingPanelMask](https://developer.apple.com/documentation/appkit/nsnonactivatingpanelmask) instead of NSWindow.

**Comment by codebytere** [comment]
We're trying to close out issue that are abandoned and not on our radars at the moment. If there's still interest i can most definitely reopen :)

**Comment by ajprax** [comment]
I'm still interested in seeing better support for this style of window. I'm working around it right now (`app.dock.hide()` allows my app's windows to join the space of other apps' full screen windows) but it creates awkward UX (no icon in `cmd+tab`, no dock icon).

**Comment by florian** [comment]
Thanks a lot for reopening! :)

**Comment by QuadDepo** [comment]
Any updates so far?

**Comment by mdings** [comment]
> #7296 is possibly related since it allows lots of different window levels.

I tried a few things out with that feature the other day but I couldn't find a window level at which the underlying app keeps focus.

**Comment by Bpazy** [comment]
I find that `win.close()`  will send back the focus.
As same as `app.quit()`.
So I use the above solution to resolve this issue.

Any ideas please?

**Comment by xudaolong** [comment]
I use applescript to switch application by press cmd + tab.
![oncework](https://camo.githubusercontent.com/7dae4f3fd09c22efb8465f639432798ab5bbc6d2/687474703a2f2f3778717671692e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f77696e646f772d616c667265642e676966)

**Comment by bernatfortet** [comment]
@tommoor Awesome package! One issue I'm finding is that if I use `titleBarStyle` with anything different than default it will crash on me.

So I'm still looking for a solution. I'm using electron v7 but can't find a way to make it work.

**Comment by mefyl** [comment]
Unfortunately it seems that the previous, library based solution (https://github.com/goabstract/electron-panel-window) does not work anymore : it segfaults right away when calling `object_setClass`, at least on Apple Silicon. It used to sort-of work, but I still had memory errors when leaving the app. I'm no ObjectiveC expert, but I don't think swapping an `NSWindow` subclass classes for `NSPanel` later at runtime is defined behavior.

It is my impression that the only way to get this feature properly is to add it to electron, to spawn an actual proper `NSPanel` from the get-go. We'd be willing to sponsor work of this if anyone is interested.

**Comment by stefanoTron** [comment]
@mefyl was opened suggesting just that https://github.com/electron/electron/issues/26596
but was closed for some reason.

**Comment by proxi** [comment]
@mefyl I agree that spawning `NSPanel` from the get-go is the only way to make it work reliably. It's not hard (see my [comment here](https://github.com/electron/electron/issues/26596#issuecomment-868727304)) but unfortunately not possible without patching Chromium, and involves duplicating a lot of code in `NativeWidgetMacNSWindow`, `ElectronNSWindow`.

**Comment by mitchchn** [comment]
I would love to see the ability to create `NSPanel` browser windows. Floating command palettes are extremely popular nowadays and the web stack lends itself well to their aesthetic -- it's a natural fit for Electron.

Most other aspects of native window management are already available in, or are at least possible to imitate, but this one does really does need a bit of help from the library before developers can run with it.

**Comment by stephancasas** [comment]
Until this feature is added, a workaround you might consider is a library like [`iohook`](https://github.com/wilix-team/iohook), which can intercept HID events. You could keep the already-frontmost app active, while still sending keystrokes to your `alwaysOnTop` Electron window.

At the moment, it looks like there's an open PR to stop propagation of keystrokes to whatever has the current focus, so it should be possible to intercept and then redirect input wherever you want it to go. I'm currently experimenting with this, and will be happy to update if anyone is interested.

**Comment by vmwsree** [comment]
can any one update me on what is the current way to implement this

**Comment by YongzeYao** [comment]
Any updates?

**Comment by clavin** [comment]
I'm closing this as it was implemented in #34388 👍

**Comment by YongzeYao** [comment]
@clavin hey Clavin, there is currently no way to achieve spotlight, alfred like window with electron...

**Comment by OmarHedeya95** [comment]
Still not working guys... Did anyone figure it out?

**Comment by jbriales** [comment]
> Still not working guys... Did anyone figure it out?

Doesn't adding `type: "panel"` in `BrowserWindow` work as of https://github.com/electron/electron/pull/34388 ?
