### ISSUE TITLE
Best practices for differentiating dev environment from runtime environment?

### ISSUE THREAD

**Issue by zeke** [electron/electron#4945]
I want to use [electron-debug](https://github.com/sindresorhus/electron-debug) to automatically open Dev Tools in development, but not when the packaged app is run. Something like this:

```js
require('electron-debug')({
  showDevTools: (process.env.ELECTRON_ENV === 'development')
})
```

Is there a de facto technique for doing this?

@sindresorhus @paulcbetts

**Comment by paulcbetts** [comment]
How about:

```
let isDevMode = process.execPath.match(/[\\\/]electron-prebuilt[\\\/]/)
```

**Comment by zeke** [comment]
That works. Thanks, @paulcbetts!

**Comment by sindresorhus** [comment]
:+1: That's pretty much what I've been doing too. I made a module for it because why not: https://github.com/sindresorhus/electron-is-dev

-

@zeke Latest version of `electron-debug` now only runs in development by default, so no need to manually guard it ;)

Just use it as normal:

```js
require('electron-debug')({showDevTools: true})
```
