### ISSUE TITLE
shell.openItem opens finder window in Background

### ISSUE THREAD

**Issue by generalconsensus** [electron/electron#4951]
* Electron version: 0.36.7
* Operating system: OSX 10.10.5
Regarding shell (https://github.com/atom/electron/blob/master/docs/api/shell.md)

1. showItemInFolder opens finder to front
2. openItem opens finder in background

Similar to #4349

**Comment by zcbenz** [comment]
We should probably add an option for it like `shell.openExternal`.

**Comment by bengotow** [comment]
For what it's worth, you have Mac OS X open a window in the foreground showing any directory using the existing `openExternal` API, eg: `require('electron').shell.openExternal('file:///Users')`

**Comment by catalin-testenv** [comment]
+ 1 Please fix this for windows. Thank you !

**Comment by zcbenz** [comment]
I'm merging this to #4349.
