### ISSUE TITLE
[OS X] Event for switching between 'blue' and 'graphite' appearance

### ISSUE THREAD

**Issue by sunabozu** [electron/electron#4954]
* Electron version: 0.37.3
* Operating system: OS X

In 0.37 you added `platform-theme-changed` event in case a user switches the 'dark mode' in OS X. It would be nice to have a similar event for the situations when the colour scheme changes between 'blue' and 'graphite'. You can name it `platform-appearance-changed` for example. And a property for checking a current value.

It would really help the developers to make their UI more native-looking.

**Comment by miniak** [comment]
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/DrawColor/Tasks/SystemTintAware.html
