### ISSUE TITLE
devtools extension doesn't load in detached devtools window

### ISSUE THREAD

**Issue by jhen0409** [electron/electron#4958]
* Electron version: 0.37.x
* Operating system: OS X 10.11.3

I used [remotedev-extension](https://github.com/jhen0409/remotedev-extension) in Electron, it works well on v0.36.12, but when I upgrade to v0.37, the devtools tab will not displayed.

**Comment by kevinsawicki** [comment]
Are any errors logged to the terminal when you click the tab in the dev tools for that extension?

**Comment by jhen0409** [comment]
The problem is `BrowserWindow.addDevToolsExtension(...)` returns undefined, this means it not loaded. 

[manifest file here](https://github.com/jhen0409/remotedev-extension/blob/master/dist/manifest.json)

**Comment by jhen0409** [comment]
@kevinsawicki I found that when I would separate Developer Tools window and restart Electron process, the devpanel will not displayed. Looks it's not problem of this extension.

I also created a tiny extension, it have the same problem:
![2016-04-04 11 36 48](https://cloud.githubusercontent.com/assets/3001525/14237698/0fb1e306-fa5a-11e5-8dad-da95d3ba5837.png)
Undock into separate window & restart program:
![2016-04-04 11 37 38](https://cloud.githubusercontent.com/assets/3001525/14237700/1371f09e-fa5a-11e5-91ea-a7f593903984.png)

**Comment by abdihaikal** [comment]
@jhen0409 
Try append script below in your app’s main script before the `ready` event of `app` module is emitted: (ref : [Supported Chrome command line switches](http://electron.atom.io/docs/v0.37.5/api/chrome-command-line-switches/))
`app.commandLine.appendSwitch('remote-debugging-port', '8315');`
`app.commandLine.appendSwitch('host-rules', 'MAP * 127.0.0.1');`

Open google chrome browser and go to `http://127.0.0.1:8315`, continue activating the dev tools, and you'll found some error occured. In my case, the `Object.observe` has been deprecated.

Confirmed by ref : [API Deprecations and Removals in Chrome 49](https://developers.google.com/web/updates/2016/02/chrome-49-deprecations?hl=en)

**Comment by kevinsawicki** [comment]
I believe this has been fixed by the Chrome 50 upgrade. I am no longer able to reproduce it in the Electron 1.1.0 release so I'm going to close this out.
