### ISSUE TITLE
Printing on Windows 10: paper size from default printer is always used

### ISSUE THREAD

**Issue by d9k** [electron/electron#4967]
Hi! We found a strange issue.
1) User prints from our electron application, `BrowserWindow.print()` is executed and standart system printing dialog is shown
2) User selects printer **other then default** from printing dialog
3) The paper size setting from default printer is used, printed pages are numerous and have large empty spaces and small rectangles with dense printing in them. 

The issue was easy to find because we had thermal printer set as default and it has small paper size. The printer used to print browserwindow content was some model of HP LaserJet.

Everything is ok only when default printer matches the selected from dialog printer.
But we couldn't produce issue with PDF virtual printer, only physical had an issue.
- Electron version: 0.37.2
- Operating system: Windows 10

**Comment by keerthivasan-r** [comment]
So, Do we have support for printing in Thermal receipt printer?

**Comment by codebytere** [comment]
closing due to abandonment.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (103/100 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:57095 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dx1NI-001613-PI
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:42:59 -0500
Date: Tue, 26 Sep 2017 18:42:10 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1506476530;
	bh=jPx/xR+mQTNDH5FHadctNWn/0NUVHvbeCRN7h0lJot4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=mZuAkHKiKeaiV/d4/ulvWblc82X/2uPzz/VT0HR8WZmVvyEwtvsxihgjcpXEtXa32
	 4pHngxgABALwADiAXX6cPqfypurryAG22o/B2YAqF6Ma5k7Rdl5aEPruHx/kkoINsF
	 DOO4U5tr77LOnHvYsN9M3OklOaisCUZhTY/NTLoI=

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (105/100 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:42510)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-96d6-jcjackson=joe-jackson.net@sgmail.github.com>)
	id 1dx1Nc-0016C3-Tl
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:43:19 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=YZ4aXjdpm2m3vSASr4c9sQlGjHs=; b=QNz7i5NsnxQ1zuVV
	5uEr8VEWwxArNKjiNbpYdmPSw8nv+vaZakOS3gCt9djmZeCx1eq06pcbxEPSxotz
	dUMaItOacUryumkOao7vEZJmytJ1nbe5R122hcQRdqy3G6ETq+5+e7i1urV56N39
	bujtTq9qNCjkaEL3wuBg3Kc4X/8=
Received: by filter1122p1mdw1.sendgrid.net with SMTP id filter1122p1mdw1-4090-59CB0206-9
        2017-09-27 01:42:30.515675121 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id ROWwH46fQCu9-XgzUWe3qw
	for <jcjackson@joe-jackson.net>; Wed, 27 Sep 2017 01:42:30.489 +0000 (UTC)
Date: Wed, 27 Sep 2017 01:42:30 +0000 (UTC)
