### ISSUE TITLE
The BrowserWindow does not take the focus on launch.

### ISSUE THREAD

**Issue by solarsailer** [electron/electron#497]
Hello,

I have some hotkeys in my WebView (like 'a' to open a prompt, etc.). I bind these hotkey with jQuery, because my app should also run in a classic web browser.

The problem is that I can't use these hotkeys directly after the launch of my app. I must click on the web view first, then use the hotkey.

I tried several things, without success (like getting the BrowserWindow and changing the focus, or triggering a click with jQuery). The Menu hotkeys work fine however.

Is there a way to do this or is it a bug?

Thanks.

(64 bits Mac on Mavericks with v0.13.3)

**Comment by roguexiaohuihui** [comment]
This problem is transmitted 6.X. It still exists. How to deal with it?
