### ISSUE TITLE
Question: how to return a value for WndProc

### ISSUE THREAD

**Issue by evgenyzinoviev** [electron/electron#4975]
On Windows you have this
```
bool NativeWindowViews::PreHandleMSG(UINT message, WPARAM w_param, LPARAM l_param, LRESULT* result)
```
handler for window messages.

Original winapi WndProc handler should return `LRESULT`, and I need to return a value. I see you have this pointer `LRESULT* result` and this is what I do:
```
*result = 1; // the value I need to return
return true; // is this right?
```

Please tell me if I am doing it right or not and what is the meaning of boolean return value of `PreHandleMSG`? (I can't achieve what I want, maybe I'm doing it wrong.)

**Comment by zcbenz** [comment]
From the [source code](https://code.google.com/p/chromium/codesearch#chromium/src/ui/views/win/hwnd_message_handler.cc&sq=package:chromium&type=cs&l=880) of `HWNDMessageHandler::OnWndProc`, you are doing it right.

**Comment by haoxi911** [comment]
Hi @evgenyzinoviev, it has been quite a while since your OP, not sure if you could remember what you did. I am curious how could you update `PreHandleMSG`, did you re-compile Electron to include these edits? Thank you!
