### ISSUE TITLE
Can't run electron from vscode due to ATOM_SHELL_INTERNAL_RUN_AS_NODE=1

### ISSUE THREAD

**Issue by unional** [electron/electron#4979]
I'm using `vscode` and `vscode-startanyshell` to open `cmder`.

When I run `browserify test.js | tape-run`
It fails with:
```sh
module.js:340
    throw err;
    ^
Error: Cannot find module 'electron'
```

After some digging, it turns out to be ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 causes the issue.

Once I remove that env variable, it started working again.

Reference:
https://github.com/remcoros/vscode-startanyshell/issues/2

**Comment by paulcbetts** [comment]
This isn't a bug in Electron, you need to specify your environment explicitly when you launch the process

**Comment by unional** [comment]
cc/ @remcoros

Any pointer on how to do that? @remcoros is the owner of `vscode-startanyshell`

**Comment by remcoros** [comment]
I don't know why or how that environment variable is set. It's not something the plugin does, and I don't see this in my own environment.

Can you try launching the default shell (built-in vscode command), using Command Pallet -> Open new command prompt and see if this variable set.

Are you sure you don't have it set in your user profile?

**Comment by remcoros** [comment]
@unional See this: https://github.com/Microsoft/vscode/blob/00035055a491040569f2744d1636f6f86161f5e5/resources/win32/bin/code.cmd

It's being set in 'code.cmd'.

This is my setup:

λ where code
C:\Program Files (x86)\Microsoft VS Code\Code.exe
C:\Program Files (x86)\Microsoft VS Code\bin\code
C:\Program Files (x86)\Microsoft VS Code\bin\code.cmd
C:\Program Files (x86)\Microsoft VS Code\bin\code.js

So 'code.exe' takes preference over 'code.cmd' and the environment variable is not set. You might want to report this to vscode also.

**Comment by zcbenz** [comment]
Closing since this turns out to be a problem of vscode.
