### ISSUE TITLE
Hide Title Bar depending on Platform?

### ISSUE THREAD

**Issue by LRRoberts0122** [electron/electron#4983]
I'd like to hide the title bar depending on Platform. Is there any way to do this? 

Thanks! :)

**Comment by DerNivel** [comment]
There is no Electron-way to do this but you can simply check the Platform with this Node-function: https://nodejs.org/dist/latest/docs/api/os.html#os_os_platform

**Comment by kevinsawicki** [comment]
Yup, as @DerNivel mentioned, checking `process.platform` or `os.platform()` before creating the browser window and tweaking the options based on the value is the way to accomplish this.
