### ISSUE TITLE
Custom Protocol Does Not Work With Different WebView Partition

### ISSUE THREAD

**Issue by cretz** [electron/electron#4991]
* Electron version: 0.37.3
* Operating system: Windows 8.1

When using `electron.protocol.registerHttpProtocol` it works fine using the default `partition` on `<webview>`. But when using a different partition name it does not.

It appears this was handled in #4551 only to be reverted in #4588. I do not see an issue tracking the effort.

**Comment by Drakulix** [comment]
Happens with `registerFileProtocol` on a normal `BrowserWindow` with `nodeIntegration` set to `false` as well. Removing the custom partition fixes the problem.
