### ISSUE TITLE
App doesn't exit with app.quit()

### ISSUE THREAD

**Issue by super-ienien** [electron/electron#4994]
* Electron version: 0.37.2
* Operating system: windows 10

I get stuck with some weird issue when i try to do an app.quit()

I have 3 BrowserWindows and a tray icon with a Quit menu item that execute app.quit()

When the 3 windows are opened and that i click on my tray icon menu to quit, the 3 windows are closed but the main process is still running, the 'before-quit' event is emitted, the 'closed' event is also emitted on each BrowserWindow but no 'will-quit' event and no 'quit' event on the app object. And in the task manager I've still got two process running.

The weird thing is that when I close the 3 windows manually (with the native X button) and then I click on the tray icon menu to quit the application, the main process exits normally.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by super-ienien** [comment]
Hi,
Sorry, I had a closed event listener on a BrowserWindow that was firing the creation of a new window... so it was not a bug. I just had to remove this listener during the before-quit app event to solve the problem.
