### ISSUE TITLE
What is the best way to get the Source Code from webContents

### ISSUE THREAD

**Issue by andrewex** [electron/electron#4999]
I want to get the source code from webContents in the `did-finish-load` event. Is there a better way to do this other than sending the HTML from the `executeJavaScript` function. It would be nice if there was somthing like this. `webContents.getSourceCode()`

**Comment by zcbenz** [comment]
You can use the `webContents.savePage` API:
http://electron.atom.io/docs/v0.37.4/api/web-contents/#webcontentssavepagefullpath-savetype-callback
