### ISSUE TITLE
Blurry Fonts and Widgets

### ISSUE THREAD

**Issue by danielroehrig** [electron/electron#5000]
* Electron version: 0.36.8
* Operating system: elementary OS (Ubuntu 14.04)

When I open atom or atom-beta, this is how all fonts are rendered:
![Atom About Section](https://cloud.githubusercontent.com/assets/12596513/14232151/3adb0262-f99f-11e5-91c9-fe482b662117.png)

It also happens in GitKraken. I don't have a high-resolution monitor and all other fonts are looking fine (including chrome). I tried passing several arguments to atom, but none of them solved the issue.

**Comment by danielroehrig** [comment]
I just realized that all the widgets are also smudged:
![Smudged Panel Header](https://cloud.githubusercontent.com/assets/12596513/14232196/954903d2-f9a1-11e5-8e12-7fd7113bc689.png)

**Comment by sedwards2009** [comment]
Does starting atom with the flag `--force-device-scale-factor=1` have any effect?

**Comment by danielroehrig** [comment]
Sadly not. I already tried that. I am still not sure if this problem has something to do with my version of `fontconfig`, as there seems to be a related problem with steam.

**Comment by danielroehrig** [comment]
I noticed, that my laptop - which has the same OS and the same version of Atom - does have crisp clear fonts. I am trying to find out the difference between the two setups. Could it be a problem with the multi-monitor setup?

**Comment by danielroehrig** [comment]
Found the culprit. It's not Electron. It's the Nvidia driver, especially the antialiasing settings. Turning off the FXAA solves the issue.
