### ISSUE TITLE
npm.install() crashes on Electron v0.37.4

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#5001]
* Electron version: v0.37.4
* Operating system: Mac OS X

I execute `require('npm').install(something)` in devtool and Electron crashed. Both devtool and stdout have no error message.

![image](https://cloud.githubusercontent.com/assets/8194131/14232351/b7070b42-f9db-11e5-8624-31dd440d5c17.png)

**Comment by KochiyaOcean** [comment]
Seems the node version of Electron 0.37.4 is 6.0.0-prebuilt, not v5.10.0 as changelog says.

![image](https://cloud.githubusercontent.com/assets/8194131/14232385/aaf85a9e-f9dc-11e5-804c-74a257a7e333.png)

**Comment by feross** [comment]
This proabably crashes because `Buffer` is broken in 0.37.4. You can't do `new Buffer()` with a size over 4kB. See: https://github.com/electron/electron/issues/5028

**Comment by zcbenz** [comment]
I'm merging this to #5003.
