### ISSUE TITLE
sending key combinations with sendInputEvent

### ISSUE THREAD

**Issue by rosshinkley** [electron/electron#5005]
* Electron version: 0.37.x
* Operating system: Ubuntu 14.04

Two (hopefully quick) questions:

1. Are sending _any_ Accelerator combinations with `sendInputEvent` allowed for `keyDown`/`keyUp`/`char`?  Do I need to set the modifiers manually?  Eg, if I send `CmdOrCtrl+A`, would I need to add the `control` modifier, or would it be done automatically?
1. The `Enter`/`Return` modifier doesn't behave exactly as I'd expect.  I can see the event happen, but if I send it to a `textarea`, say, the newline does not get added.  Is this expected behavior?

**Comment by zcbenz** [comment]
The sendInputEvent API is simply a wrapper of Chromium API, so we don't have fully control of its behavior in Electron. So I don't have answers to your questions, you have to capture the DOM events to see what's the correct sequence to enumerate real inputs, and then replay them.

**Comment by davismiculis** [comment]
So this is what worked for me sending Enter/Return:
```
webview.getWebContents().sendInputEvent({ type: 'char', keyCode: '\u000d', charCode: 13 })
```
