### ISSUE TITLE
Is there a way to forward requests from file:// to http://

### ISSUE THREAD

**Issue by rittbys** [electron/electron#5007]
* Electron version: 0.37.4
* Operating system: Windows 10 (but this is relevant to all)

Hi, my Electron program calls the YouTube API quite frequently, but the problem is that it seems to look for several files in a directory where they don't exist. This is probably due to the API code using relative paths somewhere. Is there a way that I can redirect those specific requests to http:// instead of file://? Thanks!
![capture](https://cloud.githubusercontent.com/assets/5205015/14235555/7ec4b720-f9c7-11e5-81bc-3ba7ce43addf.PNG)

EDIT: The reason this is important is that it causes the whole javascript to completely freeze for a good ten seconds, then reload some of the elements that the user has been interacting with. My code: http://github.com/rittbys/YouTubeDesktop

**Comment by rittbys** [comment]
This is being created by the Subscribe button API segment. When I don't load that bit it works fine.

**Comment by MarshallOfSound** [comment]
This might be a viable solution https://github.com/atom/electron/blob/master/docs/api/protocol.md#protocolregisterhttpprotocolscheme-handler-completion

Or you could host a mini HTTP server inside your app, something small and lightweight like https://github.com/cloudhead/node-static

**Comment by baconface** [comment]
My money is one that they are utilizing ```://``` through out their code. This is meant so it loads in either ```http``` or ```https``` depending on the host site. The problem is this will use any protocol given. In your case ```file://```.

**Comment by rittbys** [comment]
So I've fixed my individual problem but the issue still stands. This would be a good feature for dealing with APIs and the like that weren't built for electron.

**Comment by paulcbetts** [comment]
electron-compile used to fix this up but with the new release of the protocol hook API, it's much harder to do so :-/

**Comment by zcbenz** [comment]
For this bug it is tracked at #1747.
