### ISSUE TITLE
Using autoUpdater with an unsigned app on OS X

### ISSUE THREAD

**Issue by mccxiv** [electron/electron#5008]
* Electron version: 0.34.7
* Operating system: OS X

Hello, is there a technical reason why this isn't possible? I can't find relevant documentation or other issues on the topic...

![](http://puu.sh/o5a18/ba9129d6db.png)

**Comment by paulcbetts** [comment]
Verifying a code signature is the easy way to ensure an update succeeded

**Comment by kevinsawicki** [comment]
This behavior is provided/required by Squirrel which the auto update library that Electron uses, it wasn't an explicit choice for Electron apps to have this requirement.

https://github.com/Squirrel/Squirrel.Mac/blob/8caa2fa2007b29a253f7f5be8fc9f36ace6aa30e/Squirrel/SQRLUpdater.m#L149-L156

**Comment by kevinsawicki** [comment]
I'm going to close this out since this would require major `Squirrel.Mac` changes.

If that gets changed in `Squirrel.Mac` someday then it eventually land in Electron.

I'm going to update the docs though to make sure this is clear.
