### ISSUE TITLE
API naming scheme

### ISSUE THREAD

**Issue by zeke** [electron/electron#5010]
Going through the docs, I started to notice that some APIs are CamelCase like `BrowserWindow` and `DownloadItem`, whereas others are mixedCase, like `crashReporter` and `nativeImage`. Is this intentional? Is there a system to it?

I [generated this report](https://github.com/atom/electron/commit/86074846c0123c594c82be9ea4f3fdba320afe37) based on the contents of [/docs/api](https://github.com/atom/electron/tree/master/docs/api) and the `<h1>` in each file:

## CamelCase

- [Accelerator](https://github.com/atom/electron/blob/master/docs/api/accelerator.md)
- [BrowserWindow](https://github.com/atom/electron/blob/master/docs/api/browser-window.md)
- [DownloadItem](https://github.com/atom/electron/blob/master/docs/api/download-item.md)
- [MenuItem](https://github.com/atom/electron/blob/master/docs/api/menu-item.md)
- [Menu](https://github.com/atom/electron/blob/master/docs/api/menu.md)
- [Synopsis](https://github.com/atom/electron/blob/master/docs/api/synopsis.md)
- [Tray](https://github.com/atom/electron/blob/master/docs/api/tray.md)

## mixedCase

- [app](https://github.com/atom/electron/blob/master/docs/api/app.md)
- [autoUpdater](https://github.com/atom/electron/blob/master/docs/api/auto-updater.md)
- [clipboard](https://github.com/atom/electron/blob/master/docs/api/clipboard.md)
- [contentTracing](https://github.com/atom/electron/blob/master/docs/api/content-tracing.md)
- [crashReporter](https://github.com/atom/electron/blob/master/docs/api/crash-reporter.md)
- [desktopCapturer](https://github.com/atom/electron/blob/master/docs/api/desktop-capturer.md)
- [dialog](https://github.com/atom/electron/blob/master/docs/api/dialog.md)
- [globalShortcut](https://github.com/atom/electron/blob/master/docs/api/global-shortcut.md)
- [ipcMain](https://github.com/atom/electron/blob/master/docs/api/ipc-main.md)
- [ipcRenderer](https://github.com/atom/electron/blob/master/docs/api/ipc-renderer.md)
- [nativeImage](https://github.com/atom/electron/blob/master/docs/api/native-image.md)
- [powerMonitor](https://github.com/atom/electron/blob/master/docs/api/power-monitor.md)
- [powerSaveBlocker](https://github.com/atom/electron/blob/master/docs/api/power-save-blocker.md)
- [process](https://github.com/atom/electron/blob/master/docs/api/process.md)
- [protocol](https://github.com/atom/electron/blob/master/docs/api/protocol.md)
- [remote](https://github.com/atom/electron/blob/master/docs/api/remote.md)
- [screen](https://github.com/atom/electron/blob/master/docs/api/screen.md)
- [session](https://github.com/atom/electron/blob/master/docs/api/session.md)
- [shell](https://github.com/atom/electron/blob/master/docs/api/shell.md)
- [webContents](https://github.com/atom/electron/blob/master/docs/api/web-contents.md)
- [webFrame](https://github.com/atom/electron/blob/master/docs/api/web-frame.md)

## Other

- [Supported Chrome command line switches](https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md)
- [Environment variables](https://github.com/atom/electron/blob/master/docs/api/environment-variables.md)
- [File object](https://github.com/atom/electron/blob/master/docs/api/file-object.md)
- [Frameless Window](https://github.com/atom/electron/blob/master/docs/api/frameless-window.md)
- [The <webview> tag](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md)
- [The window.open function](https://github.com/atom/electron/blob/master/docs/api/window-open.md)

**Comment by yishn** [comment]
It seems classes are CamelCase while modules that contain functions are mixedCase. I find that perfectly agreeable. Also, "Synopsis" is not a module.

**Comment by zcbenz** [comment]
The basic idea is, the name of API should match how you use them. So use CamelCase when it is a class, or mixedCase when you want to call its methods.

* When the module itself is a class, like `BrowserWindow` => use CamelCase
* When the module is a set of APIs, like `clipboard` => use mixedCase
* When the API is a property of object, and it is complex enough to be in a separate chapter, like `win.webContents` => use mixedCase
* For other non-module APIs, use natural titles, like `<webview> Tag` or `Process Object`.

This follows the style of Node's APIs.
