### ISSUE TITLE
app.focus() doesn't work well after it called sevral times on Ubuntu Linux

### ISSUE THREAD

**Issue by Rokt33r** [electron/electron#5011]
* Electron version: 0.36.12
* Operating system: Ubuntu 14.04 LTS (unity 7.2.6)

As the title, `app.focus()` becomes disabled after it called several times.

**Comment by zcbenz** [comment]
On Linux whether a window should be focused is depended on the desktop environment you use, and for most desktop environments it is common to prevent program from taking the focus without user's behavior.

**Comment by Rokt33r** [comment]
Hmm.. I thought electron team would support Unity and Gnome at least. Anyway, thanks for your comment.
I'll try it on my own. 😄

**Comment by BHSPitMonkey** [comment]
Is there no way to indicate to the environment that the request is indeed user-requested? I'm trying to call `show()` as a handler for a Tray menu item titled "Show [app name]" and it can be confusing that it doesn't always appear when clicked.
