### ISSUE TITLE
Cannot get URL of  a 'new-window' from one website.

### ISSUE THREAD

**Issue by shingo-nakamura** [electron/electron#5012]
* Electron version:0.36.8
* Operating system:Windows 8.1

I found a webview issue. I added an event handler to webview using ES6 like as below.
```
webview.addEventListener("new-window", (e) => {
  console.log("url: " + e.url);
});
```

In almost website, I can get proper URL from `e`, but I cannot get the proper URL from the URL as below.
http://ima.goo.ne.jp/word/69252/%E3%82%A4%E3%83%A1%E3%83%81%E3%82%A7%E3%83%B3%E3%81%8C%E8%A3%8F%E7%9B%AE%E3%81%AB%E3%80%8C%E6%81%90%E6%80%96%EF%BC%81%E5%8A%A0%E5%B7%A5%E4%BA%BA%E9%96%93%E3%80%8D?from=ima_rec

You can reproduce by clicking the link on the right side of girl's image.
`e.url` is same as URL as above.

**Comment by herrmannplatz** [comment]
I think the URL is passed as the second parameter .

see http://electron.atom.io/docs/v0.36.8/api/web-contents/#event-new-window

**Comment by deepak1556** [comment]
a little debugging showed the site uses google tag manager, which uses window.open to open links with `target=_blank` and sets the `location.href` of the new window later. This can be fixed by providing complete support to location object on `BrowserWindowProxy`.

**Comment by zcbenz** [comment]
I'm merging this to #1865.
