### ISSUE TITLE
Provide frame info in webContents `did-fail-load` event

### ISSUE THREAD

**Issue by Mr0grog** [electron/electron#5013]
The `did-fail-load` event on WebContents fires for other frames inside the main frame. It would be nice to get some information about whether the frame that failed was the main frame (as in the `did-frame-finish-load` event) or to not get this event at all if it didn’t happen in the main frame.

If I understand correctly, this is mainly a matter of checking whether the `RenderFrameHost` provided to the relevant callbacks in https://github.com/atom/electron/blob/e5aa712bf39178d89352332105c06d315dca0ca6/atom/browser/api/atom_api_web_contents.cc has a parent.

Happy to write a PR for this if someone can tell me which approach would be preferable (a boolean indicating mainFrame or just not having the event on child frames). Or some other approach.

* Electron version: 0.37.4
* Operating system: Mac OS X 10.11.4

**Comment by deepak1556** [comment]
You can add a boolean similar to `did-frame-finish-load`

**Comment by bmcminn** [comment]
https://github.com/shyiko/electron-har/issues/8

Experiencing a similar problem, where a page loads a google doubleclick ad that returns a 204 (no content) error, however I have no response data to determine what the problem is with the request so I can filter it out.

**Comment by Mr0grog** [comment]
@bmcminn does the patch in #5029 get you what you need, or is just knowing whether the failure came from the main frame or a child frame not detailed enough for your case? If not, have you looked into the various `session.webRequest` handlers? http://electron.atom.io/docs/v0.37.4/api/session/#seswebrequest They’re more of a pain to work with, but also more detailed.

There's unfortunately not a lot more information available once we get to this point in the chromium side; no extra data about the request itself beyond what’s already provided is available. We probably could say more about which specific frame the error is coming from, but I don't think Electron really has a good way to expose that to the JS side.

That said I'm not by any means an expert in Electon or Chromium, so others might know better.

**Comment by bmcminn** [comment]
@Mr0grog I think that gets me moving in a direction at least. Thanks for the info.
