### ISSUE TITLE
Possible memory leak from alarming number of open ports after opening multiple BrowserWindow's

### ISSUE THREAD

**Issue by mintcore** [electron/electron#5014]
I've been experiencing memory leaks while opening and closing a large number of browser-windows. So far I've narrowed it down to the BrowserWindows being opened even though i'm using the `win.on('closed', function(){ win = null });` practice.

One thing i've noticed is an alarming number of open ports being shown in terminal

![image](https://cloud.githubusercontent.com/assets/1777129/14240965/10198990-fa49-11e5-8888-311e62e3c9b7.png)

about ~30K in after opening about ~15K windows that loads the same local file via `loadURL`.

Is the large number of seemingly open tcp-connections something to be worried about?

Can be reproduced with this code:

```js
'use strict';

const electron = require('electron')
const app = require('app');  // Module to control application life.
const BrowserWindow = require('browser-window');  // Module to create native browser window.

// Prevents the default closing of app when no windows are open
app.on('window-all-closed', function(){});

app.on('ready', function(){
  console.log('ready')

  let size = Array(100).fill(1).map((value, index) => index )

  size.forEach(function(item){

    let win = new BrowserWindow({
      show: false,
      chrome: false,
      webPreferences: {
        nodeIntegration: false,
        webgl: false,
        webaudio: false
      }
    })

    win.on('closed', function(){
      console.log(`closed: ${item}`)
      win = null
    })

    win.webContents.on('did-finish-load', function(){
      win.close()
    })

    console.log(`opening: ${item}`)
    win.loadURL('file:///Users/johantell/Sites/electron_as_service/index.html')
  })

});
```

* Electron version: 0.37.4
* Operating system: OSX 10.11.4 (the memory leaks also occur on ubuntu 14.04)

**Comment by zcbenz** [comment]
I think that's a bug of Activity Monitor when counting number of ports, if you view the list of opened ports of Electron with `lsof` or Activity Monitor, you will find there is no leak at all.

**Comment by littleskunk** [comment]
These ports are opened by electron. https://github.com/electron/electron/issues/5014
