### ISSUE TITLE
Setting Application Menu with "Type: 'Normal'" Removes It

### ISSUE THREAD

**Issue by sqwk** [electron/electron#5015]
* Electron version: 0.37.3
* Operating system: OSX 10.11

I am having trouble setting an application menu on OSX, compiling with `gulp-atom-electron`.

When setting a menubar using `Menu.setApplicationMenu()` from either the main process or the renderer process the menu disappears completely, also disabling the ⌘Q shortcut. All that is left is the name of the app, clickable, but without any submenu.

When `Menu.setApplicationMenu()` is not executed the menu is left as it is, with the default Quit under the app name.

    const electron = require('electron');
    const Menu                               = electron.Menu;
    const MenuItem                           = electron.MenuItem;

    app.once('ready', function () {
        // Main application menu
        var name = app.getName();
        var menu = new Menu();
        menu.append(new MenuItem({ type: 'normal', label: name, submenu: [] }));
        menu.append(new MenuItem({ type: 'normal', label: 'Edit', submenu: [] }));
        Menu.setApplicationMenu(menu);
    });

**Comment by sqwk** [comment]
Removing `type: 'normal'` from the top-most level of the menu (or its template) makes the menu visible again. 

Something like this will work:

    var template = [
        { label: "App", submenu: [
                { type: 'normal', label: "About App" },
                { type: 'separator' },
                { type: 'normal', label: 'Hide Others', role: 'hideothers', accelerator: 'Command+Alt+H' },
                { type: 'normal', label: 'Show All', role: 'unhide' },
                { type: 'separator' },
                { type: 'normal', label: 'Quit', accelerator: 'Command+Q', click: function () { app.quit(); } }
            ] },
    ];
    Menu.setApplicationMenu(Menu.buildFromTemplate(template));


Something like this will not work:

    var template = [
        { type: 'normal', label: "App", submenu: [
                { type: 'normal', label: "About App" },
                { type: 'separator' },
                { type: 'normal', label: 'Hide Others', role: 'hideothers', accelerator: 'Command+Alt+H' },
                { type: 'normal', label: 'Show All', role: 'unhide' },
                { type: 'separator' },
                { type: 'normal', label: 'Quit', accelerator: 'Command+Q', click: function () { app.quit(); } }
            ] },
    ];
    Menu.setApplicationMenu(Menu.buildFromTemplate(template));

Note that the `type` property is currently documented for `MenuItem` at http://electron.atom.io/docs/v0.37.3/api/menu-item/. Including it may be verbose but should really work.

**Comment by zcbenz** [comment]
The first menu item of application menu bar has to be a submenu.
