### ISSUE TITLE
spellcheck API to manually check all words in the field

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#5017]
- Electron version: 0.36.7
- Operating system: Windows 10

Hello!
Spellcheck works fine for ordinary input fields. But I have problems when use spellchecker with custom rich text editor, because the editor renders new HTML after every changing in the input field. 
For now, there is only method `webFrame.setSpellCheckProvider` in the API. It will be great if webFrame provides functionality to execute spellcheck manually for all words in the field (e.g. as it does after pasting).
Actually in Chrome there is no such problems.

**Comment by beshur** [comment]
I triggered manual spellcheck by moving cursor. See https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify

**Comment by clusterberries** [comment]
@beshur , yes, I know about that workaround and I have already tried this. But it affects performance of the editor it there is a lot of text in the input field. Also it is not great that we have to use such a hack... Calling method from `webFrame` would be much better approach.

**Comment by beshur** [comment]
@clusterberries, yeah, right, have the same performance problem with rich text editor.

**Comment by rogeru** [comment]
We have the same issue. Is there any progress on this?

**Comment by codebytere** [comment]
Closing as our spellchecker works as Chrome's does now with the addition of [this pr](https://github.com/electron/electron/pull/20692)
