### ISSUE TITLE
node version is 6.0.0-pre

### ISSUE THREAD

**Issue by iofjuupasli** [electron/electron#5019]
* Electron version: 0.37.4
* Operating system: xubuntu 14.04 x64

```js
process.versions.node
```
```
6.0.0-pre
```

It should be 5.10. Seems that my app is broken because some breaking changes in node major update

**Comment by rich-newman** [comment]
There is no node 6.0.0, it's the current [version number in master](https://github.com/nodejs/node/blob/master/src/node_version.h) but the [5.10.0 tag in the node repo](https://github.com/nodejs/node/blob/v5.10.0/src/node_version.h) has the correct version number (5.10.0 obviously), and that's their last release.  I think you may have used the wrong node commit for 0.37.4.

**Comment by baconface** [comment]
I haven't updated to try it myself. But it appears another user is having this result as well on issue #5001.

**Comment by caibirdme** [comment]
Yeah, I also meet with this problem. I want to upgrade my project to the latest version but the `process.versions.node === '6.0.0-pre'`,I'm not sure if I will meet with another strange things for the puzzled node version if I upgrade now
