### ISSUE TITLE
How can I disable the native file save dialog for particular file types?

### ISSUE THREAD

**Issue by hp011235** [electron/electron#5024]
Hello,

I am trying to integrate pdf.js library with my electron app. However, when the application/pdf content is detected in my app; it shows me the native file save dialog. Is there any way I can disable this dialog (only for pdf files and not for other files like .docx or .xml or etc.) so that I can gracefully open the pdf file in my pdf.js viewer without having to click on "Cancel" button in the dialog every time.

Thanks!

**Comment by zeke** [comment]
Hi @hp011235. Can you share some sample code and/or screenshots that will help illustrate the issue you're having?

**Comment by deepak1556** [comment]
you can use [session#will-download](http://www.johngustafson.net/presentations/Multicore2016-JLG.pdf) event to prevent the default action.

**Comment by deepak1556** [comment]
you can use [session#will-download](https://github.com/electron/electron/blob/master/docs/api/session.md#event-will-download) event to prevent the default action.

**Comment by hp011235** [comment]
Hi @zeke,

Please find the screenshot below, in which I am getting the native save dialog:
![screen shot 2016-04-04 at 5 05 56 pm](https://cloud.githubusercontent.com/assets/7158776/14267682/9b3dbcb0-fa87-11e5-8b4d-03b60368c257.png)

Here is my code:
`webview.addEventListener("did-get-response-details", function(e) {
         // e.preventDefault();
          var headers = e.headers;
         // console.dir("Headers: " + headers);
          var contentTypeArray = headers["content-type"];
         // console.dir("contentTypeArray: " + contentTypeArray);
          if (typeof contentTypeArray != 'undefined') {
            var contentType = contentTypeArray[0];
           // console.dir("contentType: " + contentType);
            //now check whether the content type is pdf or not
            if (contentType == "application/pdf;charset=UTF-8") {
              console.log("Found the PDF URL: " + e.newURL);
              ipcRenderer.send("show-pdf", e.newURL);
            }
          }
        });`

In main.js:
`ipcMain.on('show-pdf', function(event, args) {
  createPDFWindow(args);
});`

Thanks for your help!

**Comment by hp011235** [comment]
@deepak1556 Thanks for your suggestion. However, I tried that but was not successful. Here is what I am trying right now:

In main.js:
`ipcMain.on('getSession', function(event, arg) {
  let session = mainWindow.webContents.session;
  event.returnValue = session;
});`

In my html script page:
`webview.addEventListener("did-get-response-details", function(e) {
          var headers = e.headers;
          var contentTypeArray = headers["content-type"];
          if (typeof contentTypeArray != 'undefined') {
            var contentType = contentTypeArray[0];
            //now check whether the content type is pdf or not
            if (contentType == "application/pdf;charset=UTF-8") {

              // get the session object from the main process
              var session = ipcRenderer.sendSync("getSession");
              console.dir(session);

              session.defaultSession.on('will-download', function(event, item, webContents) {
                event.preventDefault();
              });

              ipcRenderer.send("show-pdf", e.newURL);
            }
          }
        });`

I feel like I am not getting the correct session object as `session.defaultsession` is throwing undefined.

Please let me know if I am doing something wrong here.

**Comment by hp011235** [comment]
@deepak1556 Thanks for your suggestion. However, I tried that but was not successful. Here is what I am trying right now:

In main.js:

`ipcMain.on('getSession', function(event, arg) {
  let session = mainWindow.webContents.session;
  event.returnValue = session;
});`

In my html script page:

`webview.addEventListener("did-get-response-details", function(e) {
          var headers = e.headers;
          var contentTypeArray = headers["content-type"];
          if (typeof contentTypeArray != 'undefined') {
            var contentType = contentTypeArray[0];
            //now check whether the content type is pdf or not
            if (contentType == "application/pdf;charset=UTF-8") {

              // get the session object from the main process
              var session = ipcRenderer.sendSync("getSession");
              console.dir(session);

              session.defaultSession.on('will-download', function(event, item, webContents) {
                event.preventDefault();
              });

              ipcRenderer.send("show-pdf", e.newURL);
            }
          }
        });`

I feel like I am not getting the correct session object as `session.defaultsession` is throwing undefined.

Please let me know if I am doing something wrong here.

**Comment by deepak1556** [comment]
`will-download` should provide the necessary details, you can just do

```
// main.js
let webviewSession = session.fromPartition(partitionName);
webviewSession.on('will-download', function(e, item, webContents) {
    if (item.getMimeType() === "application/pdf") {
        e.preventDefault()
        // logic
    }
})
```

**Comment by hp011235** [comment]
@deepak1556 Thanks for the answer. Really appreciate it.
Yea, I think I was making it complicated by introducing ipc to get the session object from main process to the renderer. However, I only got to know this by referring to this thread: [http://electron.atom.io/docs/all/#downloaditem](url) before your comment.

I think it would be better to keep electron docs in sync.
