### ISSUE TITLE
BrowserWindow height has to account for title bar heights in OS X and Windows

### ISSUE THREAD

**Issue by jviotti** [electron/electron#5025]
I've noticed that setting a `height` in a `BrowserWindow` on Windows and OS X causes the window size to equal that height, but not necessarily the `WebView` leading users to have to account for the title bar height.

For example, if I want the `WebView` to have a height of `380px` (and assuming no `hidden-inset` in OS X), I have to set the following heights:

- Windows 10: 419px
- OS X: 10.11.4: 402px

This doesn't seem to happen in Linux (at least on Ubuntu 14.04), since the `WebView` correctly obeys the height set in the `BrowserWindow`.

As I user, I'd expect that the height I pass is for the `WebView`, not the complete window.

I didn't look at the code that sets the Window height, but happy to contribute in any way.

***

* Electron version: 0.36.12

**Comment by feross** [comment]
Have you tried using the `useContentSize` option?

**Comment by jviotti** [comment]
@feross Thanks, looks exactly what I'm looking for. I'll give it a try.

In any case, I think there is still an inconsistency here, since Linux obeys the `width`/`height` without considering the title bar, while the rest of the operating systems do the opposite, like if Linux had `useContentSize` enabled by default. Maybe there's something that can be done to polish this?

**Comment by zcbenz** [comment]
The behavior on Linux is actually bug, and it is tracked at #3183.
