### ISSUE TITLE
How to automate UI testing for Tray/Menubar ? 

### ISSUE THREAD

**Issue by sandeep2** [electron/electron#5026]
* Electron version: v0.37.4
* Operating system: Windows/OSX

How to test the contents of tray icon in windows and osx. Is there a way to do that using Selenium?

**Comment by zcbenz** [comment]
If you want to test them reliably you have to rely on UI testing frameworks on each platform, otherwise the only choice is to use Electron's API to test whether the logics are right. Selenium doesn't work with Electron's native UI elements.
