### ISSUE TITLE
Can't  use nodejs  'mqtt'(nodejs的mqtt模块不能使用)

### ISSUE THREAD

**Issue by kcsm-lqk** [electron/electron#5027]
* Electron version:0.37.4
* Operating system:WIN7-32

Masters,I'm a green hand and I have a few questions to ask you for help.
1、Do I have to install nodejs before I use electron?

2、My js code:
       var fs = require('fs');
       var mqtt = require('mqtt');
       client = mqtt.createClient(1883, 'localhost');
       client.subscribe('testMessage');
       client.on('message', function (topic, message) {
       var str = message.toString("utf-8"); 	
       alert(str);
       });

 Error message：Cannot find module 'mqtt'
I can normally use fs but can't use mqtt
(同样的代码直接用nodejs运行一切正常，用electron运行mqtt模块不能用，求大神们帮忙)

**Comment by kevinsawicki** [comment]
> Do I have to install nodejs before I use electron?

Not necessarily, but if you need to install modules then you'll need to have node/npm installed.

> Error message：Cannot find module 'mqtt'

How did you install `mqtt`? Did you run `npm install mqtt`? Is it located in a `node_modules` folder at the root of your Electron app?

**Comment by kcsm-lqk** [comment]
Hi @kevinsawicki ,thanks for your help.
    I  download Electron’s release package(electron-v0.37.4-win32-ia32), done writing my app, run as a distribution on my client computer.
   My understanding is 'electron-v0.37.4-win32-ia32'  don't have 'mqtt' modules,because 'mqtt'   modules is third party modules of node.
   My solution: npm install mqtt.Then I can see a mqtt folder in node_modules folder and I copy the mqtt folder to my app boot folder.
   And my code is: var mqtt = require('./mqtt'); By this way I can use 'mqtt' and normally operating at all clients without installing nodejs or install mqtt modules .
  Is this approach feasible? Is there any better way?
    Thanks

**Comment by kevinsawicki** [comment]
> var mqtt = require('./mqtt');

You should use `require('mqtt')` (without the `./`) if you've installed it into `node_modules`.

You should also make sure that when you ran `electron-packager`, you specified the right path so that the local `node_modules` folder is included in your app's package so that `mqtt` is bundled with your app.

**Comment by kcsm-lqk** [comment]
@kevinsawicki   I understand,thanks for your help,you are a warmhearted master.
