### ISSUE TITLE
Provide response object argument to webContents events

### ISSUE THREAD

**Issue by bmcminn** [electron/electron#5031]
* Electron version: 0.35.6
* Operating system: Win7 Pro 64bit & OSX El Capitan 10.11.4

Found these similar issues that didn't exactly communicate the problem I'm having:
- https://github.com/electron/electron/issues/4396
- https://github.com/electron/electron/issues/5013

The issue I'm having is related to a false-positive `-3` net error on a `204` response during page load which triggers a `did-fail-load` event. You can read more about this in https://github.com/shyiko/electron-har/issues/8

Because I'm generating HAR data, I don't care that a particular request initiated by the page failed to load. Technically it didn't fail because of a `user action` per the Chromium net error docs: https://src.chromium.org/svn/trunk/src/net/base/net_error_list.h

I don't have any response data about the failed request so I can filter the result or make a more informed decision of how to handle the error, but having the response object passed into the `webContents` events would really go a long way to make that a much more intuitive process.

If anyone has an alternative approach to resolving this issue I'm all ears, but I'll try maybe reinitializing the request and see if the response data I get from that can help determine what the problem was.

**Comment by Mr0grog** [comment]
> Technically it didn't fail because of a user action per the Chromium net error docs: https://src.chromium.org/svn/trunk/src/net/base/net_error_list.h

Just had an a-ha moment when I popped over here and read this. I'm *fairly* sure in-page JS code counts as “user action” for Chromium in this context (non-user action here would be things like the server hanging up, some underlying subsystem in Chromium canceling the request, a proxy problem, etc. Anything happening *in the page,* by contrast, is user action.), so it could very well be that some script on the page is manipulating an iframe or aborting an XHR, which would likely get you the result you're seeing.

**Comment by deepak1556** [comment]
@bmcminn its just as you have concluded, this happens for 204 responses. Its not request failed in this scenario, you can verify by capturing `log-net-log` and loading in `chrome://net-internals` instead blink just terminates further resource [load](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/loader/DocumentLoader.cpp&l=412&cl=GROK&gsn=WebURLError&rcl=1459826222) .  This termination actually occurs in the provisional stage of the request, but we have `did-fail-provisional-load` emit as `did-fail-load`, you can listen to `did-fail-provisional-load` to distinguish these failures (should be fixed @zcbenz ? ). To answer original feature request you can listen to `did-get-response-details`.

For bit more context on provisional load look [here](https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/Fal1ZJnTgGQ/UDdxbrf_Rv4J)

**Comment by zcbenz** [comment]
Thanks for the answers, I'm closing this.
