### ISSUE TITLE
OSX App with Electron - Access Address Book or Core Data?

### ISSUE THREAD

**Issue by sushinger** [electron/electron#5032]
* Electron version: any
* Operating system: OSX 10.10

Hi, I'm would like to know, if it is possible to develop an App for Mac, that is able to access vCards from the AdressBook.app or any CardDAV-server. Any suggestions are welcomed :) I'm not a developer, rather need someone to develop it for us.
Thank you,
Sascha

**Comment by jlord** [comment]
There is not an Electron API for accessing the OS X Address book. You would need to find a developer to write the native code in order to implement this.

**Comment by sushinger** [comment]
Hello, sorry for coming up with this question again.

I have tried to understand the current documentation at http://electron.atom.io/docs/ in order to find out, if Electron API can now read

either
macOS Address Book Cards (vcards, vcf etc.)
or
vCards directly via CardDAV-Account / Server

I need someone to develop an App for macOS that can access the phone-numbers from either local macOS or carddav-server/account. If Electron is still not providing this kind of access, I can still look for another Developer, no problem ;) But I would prefer Electron just because of better support for other platforms than macOS.

Thank you and kind regards,
Sascha

**Comment by tonioloewald** [comment]
This is definitely possible using [AppleScript](https://apple.stackexchange.com/questions/72652/contacts-app-command-line-interface) and similarly using jsa (javascript bridged to Apple's OSA).

Or you could use [nodeobj](https://stackoverflow.com/questions/37003383/node-js-get-all-mac-contacts) to call Apple's APIs from nodejs.

Or, you could bundle command-line tool like this this [contacts](https://github.com/tgray/contacts) command line tool and use it.

Or: the address book is an sqlite3 database and can be [accessed directly](http://hints.macworld.com/article.php?story=20100130052524548).

The question is which (if any) of these methods would not violate App Store policies.

**Comment by Fiser12** [comment]
Thanks a lot for your solution, however my app is multisystem. Is it any way to do the same to get the contact list in Windows and Linux?
