### ISSUE TITLE
Not able to create a Blob object in main process

### ISSUE THREAD

**Issue by Vingtoft** [electron/electron#5035]
Im trying to create a Blob object in the main process:
`var file = new Blob([html], {type: "text/plain"});`
but it returns an error:
 `Uncaught Exception: ReferenceError: Blob is not defined`

Is this an error, or is it on purpose? 
Is there any workarounds? 

* Electron version: latest
* Operating system: OSX 10.11.3

**Comment by feross** [comment]
`Blob` is a DOM API so it is only available in renderer processes.

**Comment by Vingtoft** [comment]
Thanks for your response. 
Can you recommend any workarounds? 
Im trying to create a file object with a temporarily URL and it must be created in the main process.

**Comment by paulcbetts** [comment]
Can you tell us more about what you're trying to do at a higher level? There might be a better way

**Comment by zcbenz** [comment]
`Blob` can only be used in web pages, the main process is more like the environment of Node.js.

**Comment by Vingtoft** [comment]
Thank you all for the clarification. 
I tried to implement the [swig-templating system](http://paularmstrong.github.io/swig/), which compiles the templates and returns them as a string. The string needed to be saved as a html file in order to pass it to loadURL.
