### ISSUE TITLE
It would be nice to disable security restrictions in <iframe>

### ISSUE THREAD

**Issue by Klestofer** [electron/electron#5036]
Hello to all.
Yes, I know about `<webview>`, but what I need is to display several sites inside `<webview>`. `<webview>` in `<webview>` is not working. `disablewebsecurity` attribute in `<webview>` doesn't help also. I tried to display sites in `<iframe>`s, but 'X-Frame-Options' header prevents this.  Any other ways to do this?
As I understand, `disable-x-frame-options` feature used to work, but now it is not working. So it would be nice to have possibility to ignore 'X-Frame-Options' in `<iframe>`, and, probably, to disable other restrictions like CORS, if they exist. For example by using `disablewebsecurity` or by bringing back `disable-x-frame-options` feature.

**Comment by zcbenz** [comment]
I suggest watching #1130 for the update on embedding webview inside webview, we are not going to bring back the `disable-x-frame-options` option since it is a maintenance burden, and we want to use webview to cover all use cases.

**Comment by lukemt** [comment]
@Klestofer I have exactly the same Problem :)

**Comment by MaciejKrawczyk** [comment]
I had the exact same issue. You can disable x-frame-option by manipulating web request headers.

First, make sure that your webview has a partition defined

```
webview.partition = 'no-xframe';

//Then use IPC to send partition name to the main process:
const {ipcRenderer} = require('electron')
ipcRenderer.send('disable-x-frame', webview.partition);
```

And in the main process:

```
const {session} = require('electron')
const {ipcMain} = require('electron')

ipcMain.on('disable-x-frame', (event, arg) => {
	
  session.fromPartition(arg.partition).webRequest.onHeadersReceived({}, (d, c) => {
							
	if(d.responseHeaders['x-frame-options'] || d.responseHeaders['X-Frame-Options']){
		delete d.responseHeaders['x-frame-options'];
		delete d.responseHeaders['X-Frame-Options'];
	}
	c({cancel: false, responseHeaders: d.responseHeaders, statusLine: d.statusLine});
  });

});
```
