### ISSUE TITLE
Issue with file pickers.

### ISSUE THREAD

**Issue by Aelkeris** [electron/electron#5037]
* Electron version: 0.37.4
* Operating system: Windows 7

Hello everyone, i have an issue regarding file pickers. Basically, i have to select a file using electrons ShowOpenDialog, and that works, i select a file, and i save it into a variable, and then i output that variable into the console using the "console.log(variable)", and it works fine, i get my file path. However, when i try to show the data from that same variable again into console, but from another function, it says that the output is null. I am not sure how is that even possible, or how is it happening. This worked while developing for OSX, but now i am trying to make sure that everything works on windows too, and this baffles me.

![screenshot_2](https://cloud.githubusercontent.com/assets/14875692/14287065/aa974288-fb51-11e5-9c54-9010f584dbad.png)
When the "trazi potpis" button is clicked and the file is selected, it gets outputted as it should

![screenshot_3](https://cloud.githubusercontent.com/assets/14875692/14287063/aa96c966-fb51-11e5-86ae-6afa6f660400.png)
However when the "potpiši" button is clicked, null gets outputted to the console

![screenshot_4](https://cloud.githubusercontent.com/assets/14875692/14287064/aa971858-fb51-11e5-9a80-32747248f090.png)
function PickSignature is what works when the "trazi potpis" button is clicked, the path should be saved to the variable, and logged, and it works

![screenshot_5](https://cloud.githubusercontent.com/assets/14875692/14287066/aa975c64-fb51-11e5-91d0-c472efe3f667.png)
Sign function is what works when the "potpiši" button is clicked, first thing it should do is log the variable, and it logs, null, why ?

**Comment by martinstarman** [comment]
I'm not sure, but I think you are doing something like
```
var a = null
function fn1() { var a = "foo" }
function fn2() { console.log(a) }
fn1()
fn2() // -> null
```
This may works
```
var a = null
function fn1() { a = "foo" }
function fn2() { console.log(a) }
fn1()
fn2() // -> foo
```
If it does not work provide full script.

**Comment by Aelkeris** [comment]
Found the issue, i have declared the same variable twice, and that made it not function propely. Once i made only one declaration the functions worked as they should.
