### ISSUE TITLE
Bundled clang crashes on Arch Linux because of libncurses linkage

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#5041]
* Electron version: master
* Operating system: Arch Linux

We're hitting https://github.com/rust-lang/rust/issues/9334 in Electron's version of clang, we can probably easily fix it a similar way

**Comment by zcbenz** [comment]
rust builds their own compiler, so that solution works for them. For us there are only two ways:

1. Report it to Chromium and hope they will use a prebuilt clang binary without libncurses linkage.
2. Build with system clang.

The (2) is probably the ultimate solution, and I'm merging this to #259.

**Comment by paulcbetts** [comment]
:+1:
