### ISSUE TITLE
resource drag n drop into browserwindow not working

### ISSUE THREAD

**Issue by shindoh** [electron/electron#5044]
* Electron version: v0.36.4
* Operating system: win7/64x

Resource drag n drop into browserwindow not working in this version...
After I version up election, It's not working... 

Is there any flag to allow drag n drop to resource load into browserwindow?

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by zcbenz** [comment]
Closing until more information is provided.
