### ISSUE TITLE
OS X app icon not set

### ISSUE THREAD

**Issue by VoidingWarranties** [electron/electron#5045]
* Electron version: v0.37.4
* Operating system: OS X

The app produced by `npm run release-mac` for our [Sia-UI](https://github.com/NebulousLabs/Sia-UI) app has the default electron icon instead of our icon. This change was introduced in v0.37.4, as v0.37.3 works correctly.

**Comment by kevinsawicki** [comment]
It looks like your app is using `electron-packager` and here is the relevant issue there to track for a fix for this, https://github.com/electron-userland/electron-packager/issues/300
