### ISSUE TITLE
edge-cs.dll cannot be loaded in electron app when packaged in asar

### ISSUE THREAD

**Issue by kneumei** [electron/electron#5046]
* Electron version: 0.36.2
* Operating system: WIndows 10

Not sure if this is the right place to ask this question, but I'm trying to use edge in my electron app (using https://github.com/kexplo/electron-edge). Everything works fine when I run the app unpackaged, however when I package the app into an asar file, I see

Error: Could not load file or assembly 'file:///C:\app\v0.36.2\win32-x64\…s\app.asar\node_modules\electron-edge\node_modules\edge-cs\lib\edge-cs.dll' or one of its dependencies. The system cannot find the file specified.
    at Error (native)
    at Object.exports.func (C:\app\v0.36.2\win32-x64\resources\app.asar\node_modules\electron-edge\lib\edge.js:157:17)
I've found other threads (electron/electron#1802, for example) saying that I need to unpack the dlls. I did that, but still seeing the errors. I'm thinking that whatever loads edge-cs.dll needs to know to look in the unpacked folder?

**Comment by paulcbetts** [comment]
I fixed this in `edge-atom-shell`, a fork of edge.js that works with Electron

**Comment by zcbenz** [comment]
The asar package doesn't work well with modules that load native resources, because we can not hook file loading in the module's native code.
