### ISSUE TITLE
ELECTRON_RUN_AS_NODE with babel/ES6

### ISSUE THREAD

**Issue by vutran** [electron/electron#5047]
Electron version: 0.36.12
Operating system: WIndows 10

My Electron app is written in ES6 but when forking a child process, it doesn't work with an ES6 child module.

I have to do something like this which currently works but wondering if there is a more direct way of doing this with Electron?

### main.js
````js
import { fork } from 'child_process';
​
const child = fork('./worker-es6', [], { env: { ELECTRON_RUN_AS_NODE: true } });
child.send('some-message');
````

### worker-es6.js
````js
require('babel-register');
require('babel-polyfill');
require('./worker');
````

### worker.js
````js
process.on('message', message => {
	// do my stuff
});
````

**Comment by kevinsawicki** [comment]
Have you tried not setting `ELECTRON_RUN_AS_NODE`? I'm not 100%  that option is needed when calling `fork`.

https://github.com/electron/electron/blob/b48788af43ed8e9e94cc0bd0a86f28221cf9acc1/spec/node-spec.js#L11-L20

**Comment by zcbenz** [comment]
0.36.x is using Chrome 47 which doesn't support ES6 good enough.

**Comment by zcbenz** [comment]
Closing until more information is provided.
