### ISSUE TITLE
Elementary OS tray icon / indicator missing - again

### ISSUE THREAD

**Issue by Thomas-O** [electron/electron#5050]
* Electron version: not a clue
* Operating system: Elementary Freya 0.3.2

Hi,
The developer of [Google-Play-Music-Desktop-Player](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-) asked me to raise the bug below as a generic electron issue. It would probably be better coming from him - someone who knows what they're talking about - but there you go...

The (Google-Play-Music-Desktop) player's sys tray icon is missing on my Elementary Freya. As neither the launcher nor the listing in the sound menu indicator will recall the player I have no means of showing the minimised window. However, I can still control playback from the sound indicator menu.

The tray icon is present and works just fine on my Ubuntu 14.04.

**Comment by MarshallOfSound** [comment]
Could probably be handled with https://github.com/electron/electron/issues/5065 but elementary does support tray icons so not sure

**Comment by Aluxian** [comment]
Maybe this helps:
> Reason: ElementaryOS does not support deprecated APIs. See http://elementaryos.stackexchange.com/a/4227/4551 for a summary
https://github.com/Aluxian/Whatsie/issues/102#issuecomment-212921694

**Comment by zcbenz** [comment]
Elementary OS stops supporting adding tray icons anymore from 0.4:
http://blog.elementary.io/post/145881464631/loki-beta

So there is no meaning investigating why tray icons do not show in 0.3, and I'm closing this as won't fix.

**Comment by zcbenz** [comment]
Reopening as mentioned in #6479.

**Comment by GreyAsteroid** [comment]
Bug is still present on the final release of elementary os 0.4. Seems to be an issue with electron not recognizing Pantheon as a desktop environment that supports tray icons. Setting the environment to Unity with `env XDG_CURRENT_DESKTOP=Unity` works around this bug.

**Comment by WebShapedBiz** [comment]
@GreyAsteroid Thanx for the tip. However the elementaryplus-configurator does not recognise that Skype For Linux Alpha is installed therefore leaving the default green icon.

**Comment by Menci** [comment]
Related Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=408110

**Comment by zcbenz** [comment]
Fixed with #7319.
