### ISSUE TITLE
Add support to the "append" hint in linux notifications

### ISSUE THREAD

**Issue by 3v1n0** [electron/electron#5052]
* Operating system: Ubuntu Linux

When supported (mostly Ubuntu's notifyOSD), this would allow to merge messages coming from the same origin into a single bubble.

Check [this](https://wiki.ubuntu.com/NotifyOSD#Merging_notifications) and [dev info](https://wiki.ubuntu.com/NotificationDevelopmentGuidelines#How_to_use_the_append-hint).

**Comment by paulcbetts** [comment]
We could do this via the `tag` field on Notifications. Wanna submit a PR @3v1n0? https://github.com/electron/brightray/blob/master/browser/linux/notification_presenter_linux.cc is the code you want to have a look at

**Comment by 3v1n0** [comment]
@paulcbetts thanks for the hints, actually getting into electron development is quite straight forward.

As for the fix itself, I think that the `tag` field is probably not meant to be used in this way, as it's made for replacing the notifications.
However, in the mean time I've implemented the support for it: https://github.com/electron/brightray/pull/211

I think we could use that in a reverse way, though: by default in ubuntu we add the `append` hint, if a tag is specified, then  by design the append tag is ignored (this has actually to be fixed in notify-osd, but I'm looking at that as well).
