### ISSUE TITLE
Performance issue when compiled to Mac App Store

### ISSUE THREAD

**Issue by rodrigok** [electron/electron#5054]
* Electron version: 0.36.10
* Operating system: OS X 10.11.4

There is an performance problem when running the application compiled to MAS, as you can see on the following video: http://cl.ly/012F3G06473y

If I do the same thing with the app compiled as a normal DMG the frame rate is 60fps all the time.

**Comment by rodrigok** [comment]
You can see the original issue here https://github.com/RocketChat/Rocket.Chat.Electron/issues/164

**Comment by paulcbetts** [comment]
Sandboxing disables GPU support, this is a known (crappy) bug that we need to fix

**Comment by rodrigok** [comment]
@paulcbetts Is this an apple requirement?

**Comment by rodrigok** [comment]
I found the issue https://github.com/electron/electron/issues/3871

**Comment by kevinsawicki** [comment]
Closing this out and merging it into #3871
