### ISSUE TITLE
MenuItem of type 'checkbox' doesn't get visually updated when modifying 'checked'' value.

### ISSUE THREAD

**Issue by hvmonteiro** [electron/electron#5055]
* Electron version: 0.37.2
* Operating system: Fedora 23 _and_ Windows 7

MenuItem of type 'checkbox' doesn't get updated in it's corresponding Menu when the value changes from true to false and vice-versa. This happens in both Linux and Windows.

According to documentation http://electron.atom.io/docs/v0.37.4/api/menu-item/#instance-properties that property can be changed at runtime, and I can confirm it does get changed, but it's value is not reflected in the corresponding menu.
 If you click on the Menu Item, the checkbox visually changes correctly (loops from checked to unchecked) but the value of it's 'item.checked' is not changed correctly to 'false' if unchecked or 'true' if checked.

Here's a small portion of the code I used to check this:
```

var sysTrayMenu = [{
  label: 'Show Window',
  type: 'checkbox',
  checked: true,
  click: function (item, BrowserWindow) {
    if (mainWindow.isVisible()) {
      mainWindow.hide();
      item.checked = false;
    } else {
      mainWindow.show();
      item.checked = true;
    }
    console.log(contextMenu.items[0].checked);
  }
}, {
  label: 'On Top',
  type: 'checkbox',
  checked: false,
  click: function (item, BrowserWindow) {
    mainWindow.setAlwaysOnTop(item.checked);
    appMenu.items[0].submenu.items[3].checked = item.checked;
  }
}, {
  type: 'separator'
}, {
  label: 'Quit',
  accelerator: 'CmdOrCtrl+Q',
  click: function (item, BrowserWindow) {
    if (mainWindow) mainWindow.close();
  }
}];
var contextMenu = Menu.buildFromTemplate(sysTrayMenu);
```
```
  mainWindow.on('minimize', function () {
    if (appMenu.items[0].submenu.items[2].checked) { // appMenu Item 'Minimize To Tray'
      console.log(contextMenu.items[0].checked); // Value is set to 'true'
      contextMenu.items[0].checked = false; // Value does get modified
      console.log(contextMenu.items[0].checked); // Value is correctly set to 'false'
      mainWindow.hide();
    }
  });
```

* Maybe I'm using it wrong. But it doesn't seem so.

-
Cheers,
Hugo

**Comment by zcbenz** [comment]
Can you provide a reproducible example? Following code works fine for me:

```js
  var icon = __dirname + '/icon.png'
  var m = Menu.buildFromTemplate([
    {
      label: 'Test',
      type: 'checkbox',
      checked: false,
    },
  ])
  tray = new Tray(icon)
  tray.on('clicked', function(event, bounds, modifiers) {
    m.items[0].checked = !m.items[0].checked
  })
  tray.setContextMenu(m)
```

**Comment by hvmonteiro** [comment]
Hello again,

I've discovered the problem. 
I leave here what was the problem for further reference for others that might cross the same problem.

The problem, as stated in documentation https://github.com/electron/electron/blob/master/docs/api/tray.md
is that:

> On Linux in order for changes made to individual MenuItems to take effect, you have to call setContextMenu again. For example:
```
contextMenu.items[2].checked = false;
appIcon.setContextMenu(contextMenu);
```
So the corrected code I wrote above should be modified to this:

```
 mainWindow.on('minimize', function () {
    if (appMenu.items[0].submenu.items[2].checked) { // appMenu Item 'Minimize To Tray'
      contextMenu.items[0].checked = false; // contextMenu Item 'Show Window'
      trayIcon.setContextMenu(contextMenu); // re set the contextMenu with changes made in the line above
      mainWindow.hide();
    }
```

My problem trying to workaround this was that: I'm coding and testing in Linux, and until I found this, it got me changing the code to the point that is was also not working on both platforms (windows and linux), because at a certain point, it was bad coding.

Thanks for letting me know everything is working as expected.
Sorry for the trouble and thanks for the help.

Cheers,
Hugo
