### ISSUE TITLE
auto-updater-win.js downloads updates twice when available.

### ISSUE THREAD

**Issue by djpereira** [electron/electron#5057]
- Electron version: 0.37.3
- Operating system: Windows 

When you look at the code for auto-updater-win.js, `squirrelUpdate.download` gets called and if succesful then `squirrelUpdate.update` gets called too.

```
AutoUpdater.prototype.checkForUpdates = function () {
  if (!this.updateURL) {
    return this.emitError('Update URL is not set')
  }
  if (!squirrelUpdate.supported()) {
    return this.emitError('Can not find Squirrel')
  }
  this.emit('checking-for-update')
  squirrelUpdate.download(this.updateURL, (error, update) => {
    if (error != null) {
      return this.emitError(error)
    }
    if (update == null) {
      return this.emit('update-not-available')
    }
    this.emit('update-available')
    squirrelUpdate.update(this.updateURL, (error) => {
      var date, releaseNotes, version
      if (error != null) {
        return this.emitError(error)
      }
      releaseNotes = update.releaseNotes
      version = update.version

      // Following information is not available on Windows, so fake them.
      date = new Date()
      this.emit('update-downloaded', {}, releaseNotes, version, date, this.updateURL, () => {
        this.quitAndInstall()
      })
    })
  })
}
```

These two calls in turn call Squirrel's `Update.exe  --download` and `Update.exe --update`.

If you look at [Squirrel's source code](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Update/Program.cs), in both cases this will call `UpdateManager.DownloadReleases`, effectively downloading the whole release twice.

I may be wrong, but I think it could possibly be more efficient to just call `Update.exe --update` and that's it. Please let me know if I'm missing something.

**Comment by kevinsawicki** [comment]
I thought calling `Update.exe --update` would use the already downloaded version from `Update.exe --download` so it would only be downloaded once and just update accordingly.

@paulcbetts is this not the case? Will this cause double downloads?

**Comment by paulcbetts** [comment]
> @paulcbetts is this not the case? Will this cause double downloads?

We shouldn't need to double-download, but I can look into it

**Comment by friksa** [comment]
I am seeing a double download in the logs too when a new update is available

**Comment by philipgiuliani** [comment]
I can confirm this on my windows builds.

**Comment by mzmousa** [comment]
+1

**Comment by jrx-jsj** [comment]
There shouldn't be a "download" call but a check for update, as it is stated in the event names, and then calling update (including download) just after the `update-available` event has been emitted.

**Comment by askingalot** [comment]
+1

**Comment by karlpablo** [comment]
I am seeing this issue as well.

**Comment by edunad** [comment]
Same here, on windows builds

**Comment by qbunt** [comment]
+1 for the same issue.

**Comment by stouchardIpso** [comment]
+1 same issue.

**Comment by iamiota** [comment]
+1 same issue.

**Comment by jublo** [comment]
We have an app that has 900MB update size, so letting the user wait for 2x 900MB is really not good. How can we fix this ASAP?

**Comment by Ali8668** [comment]
Goood
