### ISSUE TITLE
Tray icon:  'right-click' event is not emitted when a menu is set with Tray.setContextMenu()

### ISSUE THREAD

**Issue by blueoctopus** [electron/electron#5058]
* Electron version: 0.37.3
* Operating system: Windows 7 and Windows 10 (didn't test Windows 8)

As explained in the title, I was expecting to handle the 'right-click' event on the tray icon.

I was able to identify the issue was with the set context menu. Without a context menu, the event is emitted as expected.

So instead of using `setContextMenu` I've found a workaround using `popUpContextMenu` to still display the context menu while still handling the event:  

```javascript
appTrayIcon.on('right-click', (event, bounds) => {
  appTrayIcon.popUpContextMenu(contextMenu);
  lastTrayIconBounds = bounds;
});
```

**Comment by zcbenz** [comment]
After calling `Tray.setContextMenu`, it is expected that the corresponding events won't get emitted. I'll make this explicit in documents.

**Comment by guerrerocarlos** [comment]
Where was this made more explicit? I am having the same problem, and don't know what is the expected then.

**Comment by guerrerocarlos** [comment]
Found it, for future reference, the expected is to add the click event to the menu as in:

    var tray = new Tray('logo.png')
    var contextMenu = Menu.buildFromTemplate([
      { label: 'Connecting...'},
      { label: 'Close', click: function(){ console.log('close clicked') } }
    ])
    tray.setContextMenu(contextMenu)
