### ISSUE TITLE
Support setting hasShadow to false on Windows

### ISSUE THREAD

**Issue by visualfanatic** [electron/electron#5060]
![shadow](https://cloud.githubusercontent.com/assets/920747/14334195/0c298c2a-fc53-11e5-8f91-a2b747a72242.png)
* Electron version: **0.37.4**
* Operating system: **Windows 8.1 x64**

**Comment by visualfanatic** [comment]
Also, the shadow appears when the window is focused.

**Comment by kevinsawicki** [comment]
Are you setting `hasShadow: false` on the `BrowserWindow` options?

http://electron.atom.io/docs/v0.37.4/api/browser-window/#new-browserwindowoptions

**Comment by kevinsawicki** [comment]
> Are you setting hasShadow: false on the BrowserWindow options?

Looks like that is only implement on Mac, is that screenshot from Windows?

**Comment by visualfanatic** [comment]
Yes and yes, `hasShadow` unfortunately doesn't work, setting `transparent` to `true` is working, but I just want to get rid of that shadow or an option to customise it.

**Comment by kevinsawicki** [comment]
@visualfanatic Not sure what the Windows APIs support regarding this, perhaps @felixrieseberg knows more :postal_horn:

**Comment by felixrieseberg** [comment]
In theory possible. One could use `SPI_SETDROPSHADOW` (more info here https://msdn.microsoft.com/en-us/library/windows/desktop/ms724947(v=vs.85).aspx).

**Comment by UxieVerity** [comment]
setting `transparent` to `true` and `backgroundColor` to `#FFF` working to me
