### ISSUE TITLE
What's the proper format/way for the icon in the title on Windows?

### ISSUE THREAD

**Issue by lipis** [electron/electron#5062]
* Electron version: 0.37.4
* Operating system: Windows 7

Here is how it looks like on some Windows 7..
![icon windows 7](https://cloud.githubusercontent.com/assets/125676/14335974/f1b78ca4-fc5f-11e5-8b8a-20fbcad1a4c0.png)

and here is the `.ico` file that we are providing with all the different sizes.. are we missing any size in particular?! Or maybe we have too many.. :D

<img width="616" alt="screen shot 2016-04-07 at 01 28 44" src="https://cloud.githubusercontent.com/assets/125676/14335997/1aa8aa1c-fc60-11e5-9b05-ffa8791a27b0.png">

I'm not setting any `icon` in the `BrowserWindow`, so it takes the icon from the executable.

**Comment by MarshallOfSound** [comment]
Can this question also serve for the tray icon as well?

No matter how high quality the icon is it always looks rubbish in the Windows tray

**Comment by felixrieseberg** [comment]
First of all, say hi to @bennyn for me! To respond to your question: Giving people better options for customizing the toolbar on Windows is still something that I'd like to see (if I ever get to it). For the Window icon, things *should* look okay if you have 16x16 and 32x32 (check out [VSCode, for instance](https://github.com/Microsoft/vscode/blob/master/resources/win32/)). However, I currently don't have Windows 7 around and I'm not sure if there's anything wrong with Windows 7.

For the tray icon, yep, that too is still hard to get right. Let's have this issue serve for fixes to both.

**Comment by zcbenz** [comment]
I'm merging this to #2248, which is basically the same problem.
