### ISSUE TITLE
Tray API: add isSupported() method

### ISSUE THREAD

**Issue by grunjol** [electron/electron#5065]
* Electron version: 0.37.4
* Operating system: Some linux distros with basic DE.

We can not check if the underlying OS supports Tray functionality.
In the case of minimize-to-tray, the user is not able to bring back focus to the window.

**Comment by feross** [comment]
This would help WebTorrent Desktop out quite a bit. Right now, we're either going to have to add a preference option to disable minimize-to-tray, or accept that some Linux users will have to use `kill -9` to actually close the app.

**Comment by paulcbetts** [comment]
tbh we should just fix why the tray doesn't show up in certain rando Linux environments - like some of the super simple ones like i3 et al will never support it, but others like Ubuntu 14.04 _should_ support it but it randomly doesn't show

**Comment by mbilker** [comment]
I use i3 and as long as the tray is enabled it will show the tray icon.

**Comment by zcbenz** [comment]
Electron should have supported all kinds of tray icons, the problem is on some desktop environments the tray icons do not show. So if we are able to add the `isSupported` method, we would just be able to fix it completely.

**Comment by feross** [comment]
@zcbenz Fair enough :+1:
