### ISSUE TITLE
windows F12 not triggering but F5 trigged

### ISSUE THREAD

**Issue by Luncher** [electron/electron#5066]
* Electron version: 0.37.2
* Operating system:windows

var globalShortcut = require('global-shortcut');

function registerShortcut() {
    function doRegister(cmd, callback) {
        globalShortcut.register(cmd, callback);
    }

    //dev tools
    doRegister('F12', function() {
        console.log("toggleDevTools");
        webContents.toggleDevTools();
    });

    //refresh
    doRegister('F5', function() {
        console.log("refresh");
        mainWindow.reload();
    });

    return;
}

**Comment by zcbenz** [comment]
This turns out to be restriction of Windows itself, you can find about it in this article:
http://muzso.hu/2011/12/13/setting-f12-as-a-global-hotkey-in-windows

**Comment by bbondy** [comment]
Because of this we're using the work around here:
https://github.com/brave/browser-laptop/blob/82445d66f378369177e87c97e9ab91eab74a3023/js/components/main.js#L57

**Comment by bbondy** [comment]
(In the renderer)

**Comment by sindresorhus** [comment]
@zcbenz F12 correctly toggles Dev Tools in Chrome though. So it *is* possible. I need it to be able to replicate the same keyboard shortcuts for Dev Tools as used in Chrome. Can't you reuse the Chrome code?

**Comment by zcbenz** [comment]
@sindresorhus It is totally fine to register F12 for your window, but not as a global shortcut. So using F12 to toggle devtools would work.
