### ISSUE TITLE
Electron not starting on Raspberry Pi

### ISSUE THREAD

**Issue by MichMich** [electron/electron#5069]
* Electron version: stable & prebuilt
* Operating system: Raspberry Pi Jessie on RPi 2
* NPM version: 3.8.3
* Node version: 5.10.1

Electron fails starting on a clean installed Raspberry Pi 2. I've set the npm loglevel to silly, which shows no additional errors. To make sure it isn't an issue with my app, I've cloned the electron-quick-start. The results of `npm start` are shown below.

![screen shot 2016-04-07 at 09 58 20](https://cloud.githubusercontent.com/assets/210954/14344393/9a5b95d4-fca7-11e5-911a-2aa060908de8.png)

**Comment by zcbenz** [comment]
It seems that the pre-built binary doesn't work with your model, I'm merging this to #259.

**Comment by MichMich** [comment]
@zcbenz Thanks! Is there a guide somewhere on how to built the binary myself?

**Comment by carlosperate** [comment]
> It seems that the pre-built binary doesn't work with your model

It's been a little while since I last tried it, but electron-prebuilt was working perfectly fine on the Raspberry Pi Raspbian Jessie (derived from Debian). @zcbenz are you sure this is part of #259 ?

**Comment by MichMich** [comment]
See: https://github.com/MichMich/MagicMirror/issues/145 an other user of my software has no issues on the RPi2. So I don't think it's part of #259

**Comment by MichMich** [comment]
FYI: I just put the same SD-card in a RPi3, and it works. SO it's a RPi2 issue.

**Comment by phodara** [comment]
Any resolution yet with the PI 2?  Not sure if this is any help but theInstallation completes successfully.  On start up I receive the following error:
...: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: no such file or directory
