### ISSUE TITLE
Add `resourceType` to WebContents `did-get-response-details` event

### ISSUE THREAD

**Issue by Mr0grog** [electron/electron#5074]
Since it’s available on the underlying `content::ResourceRequestDetails` object, it would be helpful to expose the request’s `resourceType` in WebContents’s `did-get-response-details` event, similar to how it is exposed to `session.webRequest.on*` listeners (http://electron.atom.io/docs/v0.37.4/api/session/#seswebrequestonbeforerequestfilter-listener).

In my particular use-case (https://github.com/segmentio/nightmare/pull/553), I’m trying to add more detailed response data from a `webContents.loadURL()` call in [Nightmare](https://github.com/segmentio/nightmare), an automated browser built on top of Electron. In order to determine whether the response is for the main frame itself, we currently have to compare the URL, which can be somewhat iffy (and has other complications). It would be easier to just check whether `resourceType === 'mainFrame’`.

I think I could achieve this with `webRequest.onHeadersReceived/onResponseStarted` (not sure which is most equivalent), but I’d *like* to avoid that, since you can only register one listener for each webRequest notification at a time, which makes it easy for my listener to accidentally clobber a third-party listener (or vice versa).

If this would be good, I’d be happy to write a small PR for it. My biggest question would be whether `ResourceTypeToString` should be moved out of `atom_network_delegate.cc` so it’s more easily accessible to `WebContents` (and is there a good place to put it?) or if it should just be publicly exposed in `atom_network_delegate.h`.

**Comment by zcbenz** [comment]
It sounds good to me.

> My biggest question would be whether ResourceTypeToString should be moved out of atom_network_delegate.cc so it’s more easily accessible to WebContents (and is there a good place to put it?) or if it should just be publicly exposed in atom_network_delegate.h.

I'm good with either solution, probably just expose it in `atom_network_delegate.h` since `atom_api_web_contents.h` is quite bloated.

**Comment by meetSuraj** [comment]
In https://developer.chrome.com/extensions/webRequest#type-ResourceType it is written that resourceType will be `main_frame` but electron gives it as `mainFrame`. Can someone point me to actual type used by electron.

**Comment by Mr0grog** [comment]
@meetSuraj I don’t believe it’s explicitly documented anywhere, but you can find them in the `ResourceType` converter in [the API for `WebRequest`](https://github.com/electron/electron/blob/5b53f1a39c0bb1e7b7060b69326b69dd1bc77dfe/shell/browser/api/electron_api_web_request.cc): https://github.com/electron/electron/blob/5b53f1a39c0bb1e7b7060b69326b69dd1bc77dfe/shell/browser/api/electron_api_web_request.cc#L41-L72

**Comment by meetSuraj** [comment]
@Mr0grog @zcbenz Isn't this wrong, chrome uses https://developer.chrome.com/extensions/webRequest#type-ResourceType, `main_frame` instead of `mainFrame`, why do we have difference here?

**Comment by Mr0grog** [comment]
There’s not really a *right* or *wrong* here, since Electron’s API is not Chrome’s extension API (though they are certainly similar).

Either way, this closed issue is not really a useful place for that discussion — if you think the current values should change, you should file an issue about that. (Fair warning, though: you’re asking for a breaking change on something that’s been stable for more than 4 years. That’s not an small thing for the Electron team to modify.)

**Comment by meetSuraj** [comment]
@Mr0grog I have one question to ask, if electron internally have chrome itself, then won't this API will be inside chrome anyway, why did electron had to reimplement it?

**Comment by zcbenz** [comment]
Chromium's webRequest implementation has some hard-coded restrictions, for example it can only capture requests with `http` and `https`. And it has a hard dependency on the extensions code, so we have to either patch the code or reimplement webRequest to expose the APIs in Electron without exposing the whole `chrome.*` APIs.

When the API was introduced to Electron reimplementing the code was much easier than patching the code.
