### ISSUE TITLE
Open window in print preview mode

### ISSUE THREAD

**Issue by tquetano-r7** [electron/electron#5076]
* Electron version: 0.37.5
* Operating system: Linux

I've been scouring the documentation and can't seem to find anything ... is there a way to open the window by default in print preview mode? I can access it once I open the devtools and manually check (Console => Rendering => Emulate print media), but hoping there is a way to set that as a property by default.

**Comment by zcbenz** [comment]
Currently there is no support for print preview in Electron.

**Comment by tquetano-r7** [comment]
Well that just isn't true ... as mentioned, I can open "print preview mode" in the Electron window manually via the devtools. All I was looking for was an automated way to trigger that, rather than needing to manually activate it each time.

**Comment by kamalbennani** [comment]
:+1:

**Comment by ivoputzer** [comment]
👍

**Comment by rikkertkoppes** [comment]
A workaround may be to print to a pdf, using webContents.printToPdf and show the result
