### ISSUE TITLE
link to QTKit incompatible with Mac App Store

### ISSUE THREAD

**Issue by stevedekorte** [electron/electron#5077]
* Electron version: v0.36.1
* Operating system: OSX 10.11.3

When submitting an electron app to the Mac App Store, one of the errors iTunesConnect reports is:

"Deprecated API Usage - Apple no longer accepts submissions of apps that use QuickTime or QTKit APIs."

I'm not sure what it's used for but it appears the Electron Framework links to QTKit:

otool -L "Electron Framework" 
Electron Framework:
...
	/System/Library/Frameworks/QTKit.framework/Versions/A/QTKit (compatibility version 1.0.0, current version 1.0.0)

**Comment by zcbenz** [comment]
You should try later versions of v0.36.x, this is an old bug that already got fixed. But 0.36.x doesn't work well after being sandboxed, if you want to submit to MAS you have to use 0.35.x for now.

**Comment by stevedekorte** [comment]
Thanks for the response. I hope MAS is supported again soon. Electron is currently my favorite development platform and I'd like to be able to recommend it to other Apple developers.
