### ISSUE TITLE
win.on('show') not firing

### ISSUE THREAD

**Issue by radiovisual** [electron/electron#5080]
* Electron version: 0.35.0
* Operating system: Mac OS X Yosemite (10.10.5)

I have this function:

```js
function createNewWindow(windowInfo) {
	const _windowInfo = windowInfo || {};
	const win = new BrowserWindow({
		'width': _windowInfo.width || 201,
		'height': _windowInfo.height || 151,
	});

	win.on('show', () => {
		console.log('show!');
	});

	win.on('close', () => {
		console.log('close!');
	});

	win.on('closed', () => {
		console.log('closed!');
	});

	console.log('win: ', win);

	win.loadURL(`file://${__dirname}/index.html`);

	windows.push(win);
}
```
which results in the following output:

<pre>
win:  BrowserWindow {
  _events: 
   { blur: [Function],
     focus: [Function],
     show: [ [Function], [Function] ],
     hide: [Function],
     minimize: [Function],
     restore: [Function],
     'devtools-opened': [Function],
     close: [Function],
     closed: [Function] },
  _eventsCount: 9,
  devToolsWebContents: [Getter] }
close!
closed!
</pre>

After I close the window, every single `console.log()` statement is hit, EXCEPT for the `on('show)` event. 

The strange thing is, when I copy and paste this code into a new project, it works, but inside of my project environment, the `show` event is being ignored. 

So can someone help me think of a reason why the `show` event is not being fired, while the `close` and `closed` events are working just fine?

Appreciate the help. I have no idea how to troubleshoot something like this. 

Thanks.

**Comment by zcbenz** [comment]
If the code works in in a new project but not inside your project, it is very likely it is something else in your code has caused the problem.

**Comment by radiovisual** [comment]
@zcbenz , that is very true. I was just hoping to get a little insight on some internal structure that could cause something like this, because even when I strip away all of my external code, the `show` event never fires, while all of the others do. So I know there is a condition where the `show` event can be blocked, so if I am ever able to reproduce the issue, I will come post my findings here.  

Thanks.

**Comment by MarioHofer** [comment]
@radiovisual I experienced the same kind of issues and found out, that using [Electron Connect](https://www.npmjs.com/package/electron-connect) may cause it. Electron Connect also causes problems with BrowserWindow.maximize() by resizing - or at least causing it - the window afterwards.

**Comment by radiovisual** [comment]
Thanks @MarioHofer , I will look into it. The problem still exists in my project, so perhaps this new insight could help me find the problem.
