### ISSUE TITLE
Eliminate pause when opening Dialog (Full Async Dialogs)

### ISSUE THREAD

**Issue by iyobo** [electron/electron#5081]
* Electron version: v0.37.5
* Operating system: All

It seems there is always a slight (at least 1 second) pause when opening a dialog filechooser.
This causes ALL renderer processes to pause, not just the parent. 

In certain situations, (e.g where render processes are being used for video presentations in other screens), these pauses or hiccups can add a rather low quality shine to said presentation.

Is there a way to open dialogs smoothly in such a way that they don't affect UI?
I think Chrome was able to achieve this with their file picking API.

**Comment by iyobo** [comment]
So I was able to yield the desired result by Spawning another electron app and thus creating an asyncdialog child process. 
`
var electronBin = "./node_modules/.bin/electron"
var asyncdialog = require('child_process').spawn(electronBin,['forks/dialog']);
...
asyncdialog.stdout.on('data', (data) => {
	console.log("from Dialog",JSON.stringify(data.toString()));
	//TODO: send filepath to render process to do stuff, e.g. transition with new video file
});
asyncdialog.stdin.write('openFileChooser')
`

All dialog actions take place within that forks/dialog/dialog.js which gives my app that smooth dialog feel I want. 

This works in dev...  However I am concerned how this can possibly work when packaged for distribution.
Some tips would be helpful

**Comment by iyobo** [comment]
Okay, it seems I can get the spawn binary file path with `app.getPath('exe')` (thanks @luigiplr).
This solves my problem as it will always yield the right electron binary to use to spawn stuff.

i.e.

`var electronBin = app.getPath('exe')`

**Comment by luigiplr** [comment]
Perhaps this issue should remain open in the event someone decides to fix it correctly. (in electron) :)

**Comment by iyobo** [comment]
Makes sense.

**Comment by zcbenz** [comment]
It is related to how your code actually opens a dialog, a minimal app that reproduce the problem will help here.

**Comment by iyobo** [comment]
@zcbenz I doubt it's related to how the dialog is open. You're likely thinking about the blocking stall when dialogs are opened browser/renderer side. 
I'm referring to the 1 second (or so) pause that happens even when you open dialogs in the main process. See below:

`
var app = require("app");
var dialog = require("dialog");
var BrowserWindow = require("browser-window");
var projector;
var dashboard;
app.on("ready", function () {
    projector = new BrowserWindow({width: 400, height: 400});
    projector.loadUrl("file://" + __dirname + "/screens/projector.html");
    dashboard = new BrowserWindow({width: 400, height: 400});
    dashboard.loadUrl("file://" + __dirname + "/screens/dashboard.html");
    setTimeout(function () {
        var parent = null;
        console.log("showOpenDialog called");
        dialog.showOpenDialog(parent, {}, function (paths) {
            console.log("callback");
        });
       
        console.log("showOpenDialog returned");
    }, 3000);
});
`

Assuming either dashboard.html or projector.html had some animation or video playing, you would notice this pause.

**Comment by zcbenz** [comment]
Which operating system are you using? I'm unable to reproduce on OS X.

**Comment by iyobo** [comment]
OSX


-------
Iyobo Eki

**Comment by joshaber** [comment]
I'll throw this theory out there in case it's useful:

1. When OS X shows the Open dialog, I've noticed it also spins up all disks. If you have, e.g., a slow external hard drive that's spun down, this can make showing the Open dialog slow.
2. I've also noticed that Electron's very sensitive to whatever it is OS X does when it spins up disks. Whenever my old external hard drive spun up, Atom would appear to freeze.

Put those two together and I think it accounts for what you're seeing.

**Comment by joshaber** [comment]
Fixing (2) would be great. I don't have any theories off the top of my head.

**Comment by iyobo** [comment]
If these were true, then my workaround of spawning a brand new electron
process using childprocess.spawn would also cause a one second pause on
playing video backgrounds and animations when opening file-centric dialogs,
but it doesn't.

Spawning makes it work seamlessly in a true multi-threaded manner befitting
desktop apps, with just the added annoyance of now having to manage 2
entirely separate electron main contexts.

**Comment by luigiplr** [comment]
>I've also noticed that Electron's very sensitive to whatever it is OS X does when it spins up disks. 

I dev on a windows 10 machine w/ a SSD and still encounter the "delay" when opening the dialog myself.

**Comment by zcbenz** [comment]
If you use the async version of the API that takes a callback, both Windows and OS X implementations are already using the async API provided by the system, which are the exactly same with the implementations of Chromium.

* On Windows the file dialog is opened in a new thread, because there is no native async dialog API.
* On OS X the `[NSAlert beginSheetModalForWindow:completionHandler:]` API is used, which runs the dialog asynchronously. It is not possible to run UI in other threads with Cocoa as far as I know.

But using async API doesn't mean there is no pause, creating a new thread or the native API itself would cost time. On my machine the `showOpenDialog` call costs 174ms, and 173ms of it was spent on the `NSOpenPanel` API itself, which can not be eliminated.

Running the dialog in another process is a interesting solution, because the pause time is only the time used for creating a new process. Under most cause it should be slower than calling the Cocoa APIs in current process, but on your machine it is not.

Anyway I think we are already doing the best we can, if you have ideas on improving it, PRs are welcomed.

**Comment by iyobo** [comment]
Maybe this should be set as "won't fix" or "can't fix" or something.
It's still a valid bug.
