### ISSUE TITLE
proxy-pac-url problem

### ISSUE THREAD

**Issue by SMOKExRA** [electron/electron#5085]
* Electron version: 0.36.12
* Operating system: Ubuntu 15.10, Windows 10

--proxy-pac-url command line switches doesn't affect for anything.

If we got electron/electron-quick-start and add these lines:
const app = require('electron').app;
app.commandLine.appendSwitch('proxy-pac-url', 'http://127.0.0.1/proxy.pac');

Start the app and ... Apache access.log still empty. No any queries to the PAC file, no errors in console or anything else, so it doesn't work anyway.

**Comment by deepak1556** [comment]
Can you try [session.setProxy](https://github.com/electron/electron/blob/master/docs/api/session.md#sessetproxyconfig-callback) .

**Comment by zcbenz** [comment]
You need to set the command line before the `ready` event of `app` module.

**Comment by SMOKExRA** [comment]
I set the command before the `ready` event ;)

**Comment by zcbenz** [comment]
Can you try 0.37.x? I'm unable to reproduce with v0.37.5.

**Comment by SMOKExRA** [comment]
Ok, I try to reproduce it in 0.37.5 version!

**Comment by mashaalmemon** [comment]
Hi All,

I am having a similar problem. The `--proxy-pac-url` seems to work fine on Mac OSX. However if I attempt to set it within a docker which is running Linux I get a `ERR_MANDATORY_PROXY_CONFIGURATION_FAILED` error from the underlying chromium engine.  From what I can tell, the Url I give via the switch is not even visited.

Any assistance in troubleshooting this would be appreciated.
