### ISSUE TITLE
Javascript disabled by default ?

### ISSUE THREAD

**Issue by elBarkey** [electron/electron#5088]
* Electron version: 0.37.5
* Operating system: ubuntu 14.04

The docs says that BrowserWindow javascript support enabled by default.
I tried to load http://whatsmyuseragent.com & couple of browser checking sites, each of them says javascript are disabled. Even if the webPreferences javascript set to true.
Should i worry about this?

**Comment by jean-emmanuel** [comment]
Using regular chromium (v49), http://whatsmyuseragent.com fails to detect that javascript is enabled, http://www.enable-javascript.com/ detects it correctly though, no reason to worry I think.

**Comment by elBarkey** [comment]
i got it, thanks! :)
