### ISSUE TITLE
bounds of Tray doesn't take account of scale factor

### ISSUE THREAD

**Issue by tex0l** [electron/electron#5089]
* Electron version: 0.37.4
* Operating system: Windows 10

Hi guys,
I ran into a strange problem:

When the 'click' event is fired on my Tray icon, I get the bounds of the trayIcon, and use it to calculate which args to give to BrowserWindow.setposition() so that I can display it near the Tray Icon.

It works fine on my Mac, and the Mac Retina of a friend. It works fine on windows on a virtualBox on my mac, but when he tried it on Windows under a VirtualBox on his retina mac, he ran into a strange problem:

He has a resolution of 2880x1800, and the settings -> system -> display -> cursor set at 200%.
The coordinates given by the 'click' event don't take into account this scaling factor (I get coordinates such as 2300x1300), but the set/getPosition of BrowserWindow does (max 1440x900)...

Hence, when I get the bounds from the 'click' event, and set the position of the BrowserWindow, it only works when I divide by two (200%) all the coordinates I give to setPosition...

Any idea ?

**Comment by zcbenz** [comment]
It is a bug that the bounds of Tray doesn't take account of scale factor
