### ISSUE TITLE
Built on Electron pull request and order of featured applications

### ISSUE THREAD

**Issue by gautamsi** [electron/electron#5092]
* Electron version: Any
* Operating system: Any

I have noticed people put pull request to add their icon on top of the row. I keep checking regularly on what's new on the list. It is difficult to keep track of icons getting here and there each time someone adding it. 

May I propose 

1. Featured Section: where only known developers like Microsoft Facebook and other big names can put pull request. Electron team can arrange them however you like. 
2. Other section: where it must be at the end and not in middle of lines.

it will make it easy for people like me to follow up on progress and community efforts.

**Comment by kevinsawicki** [comment]
Thanks for opening this issue, would you mind moving it to the repository for the site?

https://github.com/electron/electron.atom.io/issues/new

**Comment by sbruchmann** [comment]
@gautamsi You might be interested in [awesome-electron](https://github.com/sindresorhus/awesome-electron).

**Comment by gautamsi** [comment]
sorry I clicked on source and get here. let me move it.
