### ISSUE TITLE
Having problems printing

### ISSUE THREAD

**Issue by abrelsfo** [electron/electron#5093]
* Electron version: 0.37.2
* Operating system: windows 7 64 bit

I am trying to print from my app. When I run window.print() it opens the print menu. Once I click OK it adds it to the queue and it is immediately removed from the queue and prints nothing. When I check the queue Pages is N/A and Size has no information. I found the post about using webContent.print() which requires the pdf.dll but I can't seem to find that in my files or in the electron repository.

**Comment by fxckdead** [comment]
+1 i'm facing the same issue (same OS and Electron)

**Comment by mnquintana** [comment]
Thanks for the report! This looks like a duplicate of https://github.com/electron/electron/issues/4906 though – feel free to subscribe there for updates.
