### ISSUE TITLE
Add option to open devtools docked on right or bottom side.

### ISSUE THREAD

**Issue by parro-it** [electron/electron#5094]
* Electron version: v0.37.5
* Operating system: Any

It would be useful if we can open DevTools choosing all of it's available position: detached, docked right or docked bottom.

The new API could be something like this:

# webContents.openDevTools([options])

Opens the devtools.

* options Object (optional)

    * mode String - ['detached' | 'right' | 'bottom'] . opens DevTools in specified position. Defaults to last used mode.
    * detach Boolean - opens DevTools in a new window (deprecated, use mode: 'detached')

**Comment by marcelfalliere** [comment]
this does not work for a `webview`, right ? ie:

`this.webview.openDevTools({ mode: 'right' });`

(seen behaviour is a detached dev tools ; wanted is docked to the right)

**Comment by Nashorn** [comment]
does not work. Devtools for inspecting page always opens in detached window. Any solution?

**Comment by shennan** [comment]
`bottom` seems to work but not `right`

**Comment by MarcoFriz** [comment]
you can add the option ```{ mode: 'undocked' }``` to show the different options button
