### ISSUE TITLE
setTimeout schedule does not correctly work.

### ISSUE THREAD

**Issue by h13i32maru** [electron/electron#5101]
* Electron version: 0.37.5
* Operating system: MacOSX 10.10.5

Hi! Electron Team.
Thanks for this great tool!

I want to 10sec interval with the following code.
```javascript
// ./node_modules/.bin/electron ./src/index.js

var last = Date.now() / 1000;
function foo(){
  console.log(Date.now() / 1000 - last);
  last = Date.now() / 1000;
  setTimeout(foo, 10000);
}
foo();
```

But, the result is not what I expected.
``` javascript
0
10.004999876022339
10.003000020980835
10.000999927520752
10.001999855041504
10
10.001000165939331
16.7739999294281 // <- !?
10.002999782562256
20 // <- !?
20 // <- !?
10.000999927520752
20
20.002000093460083
10.001999855041504
10.001000165939331
20.000999927520752
10.000999927520752
10.002000093460083
20.000999927520752
```

This behavior occur in electron, but does not occur in original node.js(v5.10.1).

Is this behavior is by design? or bug?

**Comment by bengotow** [comment]
Hey! There's a small chance that this is due to the timer coalescing Apple added to Mavericks (http://appleinsider.com/articles/13/06/18/os-x-mavericks-new-app-nap-timer-coalescing-features-target-battery-efficiency). Not sure though...

**Comment by zcbenz** [comment]
Yeah it seems that the program was throttled by OS X since it is running in background. You can use the `powerSaveBlocker` module to prevent that:

```js
powerSaveBlocker.start('prevent-app-suspension');
```

**Comment by h13i32maru** [comment]
Thanks!
