### ISSUE TITLE
SoapUI request code highlights and Brazilian Portuguese translation

### ISSUE THREAD

**Issue by dmjesus** [electron/electron#5106]
* Electron version: Beta v0.7.1
* Operating system: Win10

Hello Electron team, how are you?

I found a problem with the translation to Brazilian Portuguese, where the symbols like "ç" turns to "?" and a problem related with the soapUI request code, where the code disappears in the document view after saving.

The code pattern begins with it:

&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"&gt;
    ...
&lt;/soapenv:Envelope&gt;

**Comment by zcbenz** [comment]
You have posted on the wrong place, this is for issues of Electron.
