### ISSUE TITLE
promise reject in remote not work

### ISSUE THREAD

**Issue by joshuaChou** [electron/electron#5111]
* Electron version:0.36.5
* Operating system: MAC OS 10.11.3

I upgrade my electron v0.36.3 to v0.37.5 

example：

```
main process  
getUserMe() {
    if(this.authToken) {
      return this.call('user.me').then(this._afterAuth);
    }

    return Promise.reject({
      code: 400011,
      error: 'invalid_refresh',
      error_description: 'The refresh token is invalid.'
    })
  }
```

```
render process

let _service = remote.require('./main/service_export');
  getUserMe() {
    return _service.getUserMe()
      .then((user) => {
        return JSON.parse(user);
      }).catch((err)=>{
         console.log(err);
      });
  }
```

i can't get any return from promise reject . someone can help me thank!

**Comment by zcbenz** [comment]
It looks like a regression.

**Comment by abdihaikal** [comment]
For `Promise` case, i always use to ipcMain to ipcRenderer vice-versa. For me, at least it works well

**Comment by joshuaChou** [comment]
Thank zcbenz and abdihaikal, 
my projcet is use remote to renderer , in the 0.36.12 is work well , but update to v0.37.X  promise reject can't catch any error.

**Comment by BornaP** [comment]
I can confirm that on 0.37.x and higher (including 1.x.x), Promise.reject error gets swallowed and can't be caught. Latest version it works fine with is 0.36.12.

**Comment by cdaringe** [comment]
i tried doing some investigation on this, but am not fully grasping how the RPC works.  i'd love to be able to debug and PR this, just not quite there yet!
