### ISSUE TITLE
Add API to get WebFrame for all frame/iframes

### ISSUE THREAD

**Issue by Mr0grog** [electron/electron#5115]
Is there any way to get an instance of `WebFrame` representing a particular iframe (or actual frame) inside a window’s main frame? It doesn’t look like  there is (at least, it’s non-obvious to me if it is).

I’m not sure there are a lot of use cases for this kind of functionality, but there is some discussion over on the Nightmare repository (https://github.com/segmentio/nightmare/pull/496) about scripting content in iframes. As a browser automation/testing tool, this seems like a great thing for Nightmare to be able to have. However, one of the caveats with current approaches is the need to turn off a lot of security features to script across frames from different domains. I think the only meaningful way around this would be to obtain a `webFrame` instance for a given frame, then call methods (e.g. `executeJavaScript`) on that.

It seems like this should be possible (`blink::WebLocalFrame`, which Electron’s `WebFrame` wraps, has a static [`fromFrameOwnerElement()` method](https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/public/web/WebLocalFrame.h#56). `blink::WebFrame` has [a series of traversal methods](https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/public/web/WebFrame.h#231) as well.) Maybe it would be an API on `WebFrame` instances, that way security issues are probably avoided (you can only call it if you have node support). Nightmare could probably benefit, but I don’t know how valuable this would be in general.

**Comment by zcbenz** [comment]
Yeah it is possible with the API you mentioned. Nightmare's usage looks reasonable to me so I'm good adding this.

**Comment by kalehrishi** [comment]
Is anyone working on this feature?

**Comment by Mr0grog** [comment]
I have unfortunately not had time to work on this, so as far as I’m aware, no. Do you have another particular need/use case for it?

**Comment by kalehrishi** [comment]
We are trying to include an extension which injects script in all frames. Unfortunately `all_frames:true` doesn't work with Electron. It would be really great to have some API to executeScript with frames without disabling `webSecurity`. For now we are using this but I would really like to have a secure way to do it.

Is there somehow I could help?

**Comment by Mr0grog** [comment]
> Unfortunately `all_frames:true` doesn't work with Electron.

Are you referring to the first argument to [WebContents::SendIPCMessage](https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_web_contents.h#L137) or something else? I’m not sure I exactly get what you’re going for here, though I think I get the general idea.

> Is there somehow I could help?

Well, you could write a patch that does what this issue is suggesting ;)   Otherwise, I certainly don’t think I’m going to be able to get around to this myself anytime soon. I certainly won’t claim any monopoly on working on this issue, though. Anyone can take this if they want!

**Comment by kalehrishi** [comment]
I am talking about `all_frames` flag used in chrome extension to inject content script in iframes. https://developer.chrome.com/extensions/content_scripts

I am trying to implement same in my Electron app. I have 3 options:
1. Use chrome extension which can inject script in iframes on page (This doesn't work with chrome)
2. There should be some API which will allow to execute script in iframes present in page loaded in WebView tag/BrowserWindow
3. Disable web-security so that executeScript could execute script in main window which could access elements within iframe 

Right now we are using option 3. But it's not right way to do it. So I was thinking if we could get this API developed then we can start using it.

Would you be able to give me some pointers about how we can implement it? I would like to help on this one.

**Comment by Mr0grog** [comment]
Hmmm, I don't think I had thought too deeply on exactly what the API should be, but my general idea was to expose a method on `WebFrame` that takes an element and returns a `WebFrame` instance for it. e.g. `WebFrame#getFrameForElement()`.

Under the hood, Electron’s [`atom::api::WebFrame`](https://github.com/electron/electron/blob/master/atom/renderer/api/atom_api_web_frame.h) wraps Blink’s [`blink::WebLocalFrame`](https://chromium.googlesource.com/chromium/blink-public/+/master/web/WebLocalFrame.h) (it’s stored in the `web_frame_` instance variable).

`WebLocalFrame` has a static [`fromFrameOwnerElement()` method](https://chromium.googlesource.com/chromium/blink-public/+/master/web/WebLocalFrame.h#48) that returns the `WebLocalFrame` instance corresponding to an element. So you’d need to call that and then create a new `atom::api::WebFrame` to wrap the result. So you might have a method sorta-kinda like:

```cpp
v8::Local<v8::Value> WebFrame::GetFrameForElement(v8::Local<v8::Value> value
                                                  mate::Arguments* args) {
  mate::Handle<WebElement> element;
  // Note you'll probably need to implement the converter for this
  if (mate::ConvertFromV8(isolate(), value, &element)) {
    blink::WebLocalFrame* element_frame = WebLocalFrame::fromFrameOwnerElement(element);
    if (element_frame != 0) {
      // You'll need to add a way to construct a `WebFrame` with a given `WebLocalFrame`
      // (it always grabs the current context's frame right now)
      mate::Handle<WebFrame> frame_handle = mate::CreateHandle(isolate, new WebFrame(isolate, element_frame));
      return frame_handle.ToV8();
    }
  }
  else {
    args->ThrowError("Must pass a frame element instance");
  }
}
```

Hope that helps!

**Comment by bughit** [comment]
@Mr0grog 

> // Note you'll probably need to implement the converter for this

Could you please give some guidance for getting a blink::WebElement from a v8::Value?

**Comment by bughit** [comment]
according to [V8Element.h](https://cs.chromium.org/chromium/src/out/Debug/gen/blink/bindings/core/v8/V8Element.h?l=40) the following should work
```c++
blink::Element* frame_element = blink::ToScriptWrappable(v8::Local<v8::Object>::Cast(value))->ToImpl<blink::Element>();
```
however it has these problems:

* ScriptWrappable.h includes ScriptWrappableVisitor.h which includes RuntimeEnabledFeatures.h which is not present.
* `blink::Element` is declared in `src/third_party/WebKit/Source/core/dom/Element.h` which is missing.  Should I try getting it from chromium?  How would I determine which commit?
* in order to contruct a `blink::WebElement` from `blink::Element`, you need `third_party/WebKit/Source/core/exported/WebElement.cpp` which is absent and BLINK_IMPLEMENTATION=1

I can try

* commenting out the RuntimeEnabledFeatures.h include
* grabbing `src/third_party/WebKit/Source/core` from chromium (how do you determine which commit to take?)
* setting BLINK_IMPLEMENTATION=1

Am I on the right track here, or is there a better way to do this?

**Comment by Mr0grog** [comment]
I’m sorry to say that you are much farther along on this than I ever had time to get to. @zcbenz would almost certainly know more about this than I — I foolishly didn’t expect this part to be that complicated!

A different approach that wouldn’t require dealing with WebElements might be to expose the [traversal methods on WebFrame](https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/public/web/WebFrame.h#151) (`Parent()`, `FirstChild()`, `NextSibling()`, `TraverseNext()`) so users can simply walk the frame tree to find the `WebFrame` they want.

It’s not nearly as pretty or nice as exchanging an `<iframe>` element for a `WebFrame` instance, but it still solves a lot of the use cases. (It might be hard or impossible to determine which frame you want in a page with several frames all pointing to the same URL, but it lets you traverse deeply through the hierarchy easier and lets you get at frames inside shadow trees, which might be pretty hard with API I’d proposed above.)

**Comment by bughit** [comment]
> A different approach that wouldn’t require dealing with WebElements might be to expose the traversal methods on WebFrame (Parent(), FirstChild(), NextSibling(), TraverseNext())

Those methods return `blink::WebFrame*`.  Which I am assuming means they could be remote and can't be cast to `blink::WebLocalFrame*` (which `atom::api::WebFrame` needs)?

**Comment by Mr0grog** [comment]
Isn’t `WebLocalFrame` a subclass of `WebFrame`, though? https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/public/web/WebLocalFrame.h#71

**Comment by bughit** [comment]
Yes and if `atom::api::WebFrame` needed a `WebFrame` and the methods returned a `WebLocalFrame`, it would have been fine, but it's the other way around.

**Comment by Mr0grog** [comment]
Well, you could always see if what it returns are actually `WebLocalFrame` instances most of the time, and if so, then just do that check at runtime and cast if you get an instance or throw an error if not. Obviously if that’s not usually the case, then you don’t have a viable approach there.

Another ugly approach might be to take a string selector or ID instead of an element reference. Then you could get the element by:

```cpp
WebElement* element = localFrame->GetDocument()->QuerySelector(frame_selector);
WebLocalFrame* element_frame = WebLocalFrame::fromFrameOwnerElement(element);
```

**Comment by bughit** [comment]
>  You could always see if what it returns are actually WebLocalFrame instances most of the time

RTTI is disabled by default, however empirically a blind cast does seem to work. The following works and the frame can execute javascript:

```cpp
v8::Local<v8::Value> WebFrame::FirstChild() const {
  blink::WebFrame* _first_child = WebFrame::web_frame_->FirstChild();
  blink::WebLocalFrame* first_child = (blink::WebLocalFrame*) _first_child;
  if (first_child)
    return mate::CreateHandle(isolate(), new WebFrame(isolate(), first_child)).ToV8();
  else
    return v8::Null(isolate());
}
```
Is there a guarantee that these will always be local? Then what's the remote frame for?

`QuerySelector` also works, the string conversion is pretty cumbersome here, is there a better way?

```cpp
v8::Local<v8::Value> WebFrame::getFrameForSelector(v8::Local<v8::Value> selector_value, mate::Arguments* args) const {
  if (!selector_value->IsString()) {
    args->ThrowError("selector string required");
    return v8::Null(isolate());
  }
  v8::Local<v8::String> selector_v8_string = selector_value->ToString();
  int selector_utf8_size = selector_v8_string->Utf8Length();
  char* selector_utf8_buff = new char[selector_utf8_size];
  selector_v8_string->WriteUtf8(selector_utf8_buff, selector_utf8_size);
  blink::WebString selector_web_string = blink::WebString::FromUTF8(selector_utf8_buff, selector_utf8_size);
  delete[] selector_utf8_buff;
  blink::WebElement element = web_frame_->GetDocument().QuerySelector(selector_web_string);
  blink::WebLocalFrame* element_frame = blink::WebLocalFrame::FromFrameOwnerElement(element);
  if (element_frame)
    return mate::CreateHandle(isolate(), new WebFrame(isolate(), element_frame)).ToV8();
  else
    return v8::Null(isolate());
}
```

**Comment by bughit** [comment]
#11607

It probably won't be merged as I don't time to do tests or documentation, but it's worth to have the code reviewed

**Comment by Mr0grog** [comment]
Oh, nice! Thanks for taking this over and pushing it through that slow review process, @bughit.
