### ISSUE TITLE
Background transparency glitch during animations

### ISSUE THREAD

**Issue by lionep** [electron/electron#5123]
* Electron version: >= 0.37.3
* Operating system: Ubuntu 14.04.4
* Graphics: Intel HD

While running this code : 
```
var config = {
  alwaysOnTop: false,
  enableLargerThanScreen: true,
  frame: false,
  show: true,
  webPreferences: {
    nodeIntegration: false,
    plugins: true
  },
  'always-on-top': false,
  kiosk: true,
  fullscreen: true
};

var bw = new BrowserWindow(config);

bw.loadURL('http://peacekeeper.futuremark.com/run.action');
```
I notice lots of glitches (background blinking white / black, ubuntu background can be seen sometimes).

This does not appear on electron <= 0.37.2

**Comment by zcbenz** [comment]
I'm merging this to #5120.
