### ISSUE TITLE
alwaysOnTop: true breaks the windows transparency

### ISSUE THREAD

**Issue by mim-Armand** [electron/electron#5124]
* Electron version: v0.37.5
* Operating system: Windows

On windows Setting BrowserWindow frameless **transparency** option to *true* while having the **alwaysOnTop** flag set to *true* as well will not work:
The window will stay on top however and will be **completely** transparent, but nothing else will be shown, all the elements remain either transparent and/or will not render regardless of their styling.
Everything starts working again once **alwaysOnTop** flag is either removed **or set to false**.

thx, mim

* Electron: v0.37.5Node: 5.10.0Chromium: 49.0.2623.75V8: 4.9.385.28

**Comment by zcbenz** [comment]
Can you show your code that creates `BrowserWindow `?

**Comment by mim-Armand** [comment]
sure,

```javascript
'use strict';
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;
let mainWindow;
let splashWindow;
function openSplashScreen(){
	splashWindow = new BrowserWindow({width: 333, height: 333, center: true, resizable: false, minimizable: false, maximizable: false, fullscreen: false, fullscreenable: false, skipTaskbar: true, hasShadow: false, experimentalCanvasFeatures: true, toolbar: false,  backgroundColor: '#00000000', frame: false, transparent: true, alwaysOnTop: true}); // alwaysOnTop does not work for some reason with transparent window...
	splashWindow.loadURL('file://' + __dirname + '/src/html/splash.html');
	setTimeout(loadMainWin, 1236); //closes the splash screen and opens the main window
}
app.on('ready', openSplashScreen);
```



regardless of the html file content and styling the transparent window will be completely transparent with no visible element if the *alwaysOnTop* flag is being set to *true*, as soon as it is being changed to *false* or removed from the options however everything works fine again..
So to trim it down to the problematic parts, you can even use only those two options to reproduce the issue:


```javascript

	splashWindow = new BrowserWindow({frame: false, transparent: true, alwaysOnTop: true});

```
Thanks,

**Comment by zcbenz** [comment]
Hmm I'm unable to reproduce on my Windows 8.1 machines, it seems to be machine dependent problem.

What will happen if you open devtools?

**Comment by mim-Armand** [comment]
Oh,.. I'm sorry I should have test it on more machines, I tested on two machines I had access to at office in addition of my laptop (all win 10) and they all had this issue but after your last comment I doubt  again it may be just me and because of something in my environment (these machines all have pretty much the same env set up) so I tried it yet on another computer (win 10 again) and it seems like it's working just fine! I don't know what is the issue in those other systems but whatever it is it can't be related to Electron.
My apology again, let me close the ticket, I really appreciate your time and your help.
,m

**Comment by arjun-g** [comment]
I am facing the same problem. Mine is a win 10 machine and it works fine. Our tester was using a win 8.1 and the same issue as mentioned above happens on BrowserWindow with both transparent and alwaysontop set to true. I see a icon in taskbar but the window is not visible at all. If any one of this is set to false it works fine. To confirm I installed a win 8.1 machine as a vm and faced the same issue.

This is on Electron 1.7.5

**Comment by Nditah** [comment]
Electron v1.8.4
The Windows stays behind the main windows even when  alwaysOnTop is true as long as  **transparent** is true

    let win = new BrowserWindow({
        frame: false,
        transparent: false,
        alwaysOnTop: true,
        width: 400,
        height: 200
    })

**Comment by rdiazv** [comment]
I'm having the same problem. When both `alwaysOnTop` and `transparent` are `true`, no content is shown on Windows 8.1.

Using electron 1.8.4
