### ISSUE TITLE
webContents.print Default Margins

### ISSUE THREAD

**Issue by fxckdead** [electron/electron#5125]
* Electron version: 0.37.2
* Operating system: Windows 7 x64 / OSX / Linux

I want to know if there's some way to set page margins, coz `webContents.print` only accept 2 options (`printBackground` and `silent`) so i can't set margins, but in `webContents.printToPDF` you can define the option `marginsType` and i think it's same as the chrome option:

![margins-chrome](https://cloud.githubusercontent.com/assets/116668/14468043/708bff26-00b4-11e6-83b7-d51a61908a79.png)

If i print in my Electron application it always set margins (bottom line in the image) and if i set "no margins" in chrome (i think its same as `marginsType: 1`) it prints like the bottom line:

**(The blue line is where margin is)**
![fullsizerender](https://cloud.githubusercontent.com/assets/116668/14467806/56c3e474-00b3-11e6-9d04-f6f61db91ff8.jpg)

Is there some way to configure "Global Margins" for printer? or it must be in the API Framework of Electron?

**Comment by baconface** [comment]
You should be able to do this through CSS by setting margins for the ```@page``` selector.

**Comment by fxckdead** [comment]
@baconface wow t**hat did the trick** ! thx u so much !... but just to know, there is no way to do this like an "option" for the print function?

**Comment by baconface** [comment]
You are correct. Unless you ```printToPDF()``` you cannot set margins for ```print()``` as options. Being that the CSS method is the defacto specification and Chrome nor any other browser vendor has plans to extend on print() beyond event handlers per [the latest specifications](https://w3c.github.io/html/webappapis.html#printing) I am unsure if this will be implemented in Electron anytime soon.

**Comment by fxckdead** [comment]
@baconface Now everything is more clear, thx u !

**Comment by arielpires** [comment]
@fxckdead and @fxckdead , Can you guys please show me an example on how to set this margins?

**Comment by fxckdead** [comment]
@arielpires When we refeer to `@page` we mean about the CSS rule to define printing style. You can read about it [here at mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/@page) and [here is an article](https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/) where you can find a lot of explanation and examples.

ps: i don't have the code i used in my question, so i can't send a concrete example right now

**Comment by arielpires** [comment]
@fxckdead thanks a lot! That solved my problem. =)

**Comment by okonon** [comment]
`@page` worked for me!

**Comment by NewSimpleLife** [comment]
@page can't woeked for 58mm 80mm Thermal printer，some printer‘s margin was unbelievable。

**Comment by baconbrad** [comment]
@NewSimpleLife By chance was that a Epson thermal printer? We had a bit of issues with margins on it for our POS we wrote in Electron. Our Star receipt printer also was also goofy. We ended up having to make a separate CSS "profile" for each printer type. If it was the Epson I remember really fighting that one the most and I believe we had to adjust printer settings as well `@page`.

**Comment by tnishimura** [comment]
> Untested with Electron but you should be able to do this through CSS by setting margins for the `@page` selector. This is how web browsers typically handle print margins.

I just spent several hours because I thought the above said `@media print` instead... So, for my dyslexic friends who are reading @baconbrad's comment in the future: he is not talking about `@media print` queries -- there is a separate thing called `@page`. Do `@page { margin: 0; }`.
