### ISSUE TITLE
inconsistent results for findInPage()

### ISSUE THREAD

**Issue by abrelsfo** [electron/electron#5126]
* Electron version: 0.37.2
* Operating system: Windows 7 64 bit

Trying to use webContents.findInPage() but when I check the results I am getting odd results. Sometimes matches is undefined and other times activeMatchOrdinal is undefined

This is the function I am using 
```js
function search() {
  var remote = require('remote');
  var webContents = remote.getCurrentWindow().webContents;
  webContents.on('found-in-page', function(event, result) {
    document.getElementById('matches').innerHTML = result.activeMatchOrdinal + ' of ' + result.matches + ' matches';
  });
  var text = document.getElementById('searchInput').value;
  webContents.findInPage(text);
}
```

If I put an alert() with activeMatchOrdinal or matches before I try to set the innerHTML then the result I check will be fine but the other will be undefined.

**Comment by zcbenz** [comment]
Every time you called `search()` you will add a new handler to the `found-in-page` event. You can probably reference how other people implemented this:
https://github.com/search?q=found-in-page&type=Code&utf8=✓

**Comment by abrelsfo** [comment]
@zcbenz but why am I not getting `activeMatchOrdinal` and `matches` with the same result? I get one or the other.
