### ISSUE TITLE
electron how to call gulp task

### ISSUE THREAD

**Issue by littledu** [electron/electron#5129]
* Electron version: 0.36.12
* Operating system: osx

Hi, i want to run `spawn('gulp', ['gulptask'])`, `npm start` it is ok, but after build package , it throw error `spawn gulp ENOENT `. I have npm install the `gulp-cli` in node_modules ,can you help me to resolve this problem?

**Comment by abdihaikal** [comment]
For `gulp-cli`, have you try to set `ELECTRON_RUN_AS_NODE=true` env variable
Ref: [Debugging the Main Process](http://electron.atom.io/docs/v0.37.5/tutorial/debugging-main-process/)

For `gulp` in electron app manner, AFAIK, you should call gulp tasks with command `gulp.start.apply(null, [your tasks name])`

Found this command script in `gulp` source code it self

**Comment by zcbenz** [comment]
@abdihaikal Thanks for answering this, closing now.

**Comment by littledu** [comment]
@zcbenz 
But, can't solve my problem.

**Comment by zcbenz** [comment]
I suggest seeking help from [the community](https://github.com/electron/electron#community), the issues list is mostly used for bug reports and feature requests.

**Comment by littledu** [comment]
ok, I will

**Comment by littledu** [comment]
thanks @abdihaikal @zcbenz
