### ISSUE TITLE
window.close after print dialog closes all windows

### ISSUE THREAD

**Issue by RobsonMi** [electron/electron#5130]
* Electron version: 0.37.5
* Operating system: Linux

I am printing canvas contents with special window where I call:
`window.print();`
`setTimeout(function() { window.close(); }, 100);`

It works as it should:

1. Print dialog pops up and is waiting for user action.
2. When user is done with dialog and closes it print window closes with it.

But while on Windows only the print window is closed on Linux also my main window is closed. This only happens in case user decides to print the file. If user hits cancel all works well.

Any suggestions? Someone can confirm?

**Comment by zcbenz** [comment]
I can confirm this, it seems that Electron just crashed with your code.

**Comment by fdelayen** [comment]
It looks like in the latest release, it is not a bug anymore. The main window stays and everything is working fine !

**Comment by zcbenz** [comment]
@fdelayen Thanks for the update!
