### ISSUE TITLE
More detail in the documentation about using WebDriver please

### ISSUE THREAD

**Issue by snoblenet** [electron/electron#5134]
* Electron version: v0.37.5
* Operating system: 10.11.4

The page [Using Selenium and WebDriver](http://electron.atom.io/docs/v0.28.0/tutorial/using-selenium-and-webdriver/) is useful but incomplete.

Sections 1 and 2 make sense, but Section 3 seems to be based on the user controlling a web browser rather than the app:

`driver.get('http://www.google.com');`

How do you tell the driver to get `main.html`? (And switch focus to other app windows if any.)

I presume that once the driver gets `main.html` you can just read and interact with the page as per usual.

**Comment by zcbenz** [comment]
The main purpose of the guide is to show how to connect webdriver with Electron, it doesn't mean to cover everything of webdriver, I suggest seeking help from [the community](https://github.com/electron/electron#community).
