### ISSUE TITLE
25% Performance hit when using v0.37?

### ISSUE THREAD

**Issue by mgcrea** [electron/electron#5135]
* Electron version: v0.37.5 vs. v0.37.2 vs. v0.36.12
* Operating system: Ubuntu LTS 14.04.4LTS (up to date)

We're encountering a big performance hit after migrating from 0.36 to 0.37, also tried the 0.37.2 to rule out the transparency issue. Probably the jump from chrome 47 to 49 is the culprit.

We're using [Peacekeeper](http://peacekeeper.futuremark.com/) as a benchmarking tool.

On a NUC5i7, v0.36.12 yields a score of 5680, while v0.37.2 scores 4390.

**Comment by baconface** [comment]
You should test and measure performance in other browser bench marking tools such as Browsermark, Octane, or Sunspider to see if they reflect Peacekeeper's results. Peacekeeper is not only no longer maintained but it was doomed to begin with. It also requires and uses Flash for some of its HTML5 tests. Which being absent will ruin the reliability of such tests. I just wouldn't trust it without trying other benchmarks and comparing the results.

**Comment by baconface** [comment]
Not saying there isn't a performance hit. Just suggesting a change of benchmark.

**Comment by zcbenz** [comment]
The benchmark results of Chrome 49 should also be compared.

**Comment by bengotow** [comment]
I haven't noticed any performance degradation in N1 after updating from 0.36 => 0.37, at least on Mac OS X. I wonder if this is Linux-specific? (Also as a side note, we're really loving that window resize is synchronized with repaint now).

**Comment by mgcrea** [comment]
#### Electron 36.12

- Peacekeeper: `5611`
- Browsermark: `6692`
- Octane: `32450`

#### Chromium 49

- Peacekeeper: `4470`
- Browsermark: `6836`
- Octane: `32866`

Looks like @baconface was right and Peacekeeper shouldn't be trusted. Thanks for your inputs.
