### ISSUE TITLE
AutoUpdate not restarting

### ISSUE THREAD

**Issue by ghego1** [electron/electron#5139]
* Electron version: 0.37.5
* Operating system: MacOSX 10.11.3 (15D21)

When launching `quitAndUpdate()` the app quits, but never reopens (nor updates).

In the system console I've these logs. They keep appearing every 2 seconds:

        13/04/16 13:22:33,510 com.apple.xpc.launchd[1]: (com.myapp.macapp.ShipIt[8673]) Service exited with abnormal code: 1`
        13/04/16 13:22:33,510 com.apple.xpc.launchd[1]: (com.myapp.macapp.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.`
        13/04/16 13:22:34,863 com.apple.xpc.launchd[1]: (com.myapp.macapp.ShipIt[8674]) Service could not initialize: 15D21: xpcproxy + 12644 [1472][13E77DA5-3602-31BF-B074-49D4EE27E9D8]: 0xd

The autoupdate systems seems to be working fine. At launch the new version is downloaded and it is placed under `Application Support/com.myapp.macapp.ShipIt/update.RlXAmWd/myapp`.

In `main.js` I have the following code:

        autoUpdater.checkForUpdates();
        autoUpdater.on('update-downloaded', function (event, releaseNotes, releaseName, releaseDate, updateUrl, quitAndUpdate) {

        //confirm install or not to user
        var index = dialog.showMessageBox(mainWindow, {
            type: 'info',
            buttons: ['Restart', 'Later'],
            title: "Enoron",
            message: 'The new version has been downloaded. Restart the application to apply the updates.',
            detail: releaseName + "\n\n" + releaseNotes
        });

        if (index === 1) {
            return;
        }

          // restart app, then update will be applied
          quitAndUpdate();
      });`

Not sure if it matters, but when launching the app I get the following in the console:

       13/04/16 13:34:18,012 myapp[9464]: Error loading /Users/don/Library/Application Support/SIMBL/Plugins/Afloat.bundle/Contents/MacOS/Afloat:  dlopen(/Users/don/Library/Application Support/SIMBL/Plugins/Afloat.bundle/Contents/MacOS/Afloat, 265): no suitable image found.  Did find:
	/Users/don/Library/Application Support/SIMBL/Plugins/Afloat.bundle/Contents/MacOS/Afloat: no matching architecture in universal wrapper
       13/04/16 13:34:18,020 myapp[9464]: Loading Maximizer into bundle: com.myapp.macapp

**Comment by ghego1** [comment]
Not sure of what the problem was, but restarting the system seems to have fixed the problem. So the problem was basically down to old good question "Have you tried to witch it off and on?" :-D

**Comment by TheChuckster** [comment]
Restarting seems like a band-aid fix to me, the whole point of hot updates is that you don't have to restart (this isn't an OS update).
