### ISSUE TITLE
How to debug Electron crashes?

### ISSUE THREAD

**Issue by bennyn** [electron/electron#5140]
Hello,

We built an Electron application ([Wire](https://wire.com/)) which sometimes crashes on Windows. When it crashes we get a crash dump (`Wire.dmp`) but we miss the symbol files to debug it in Visual Studio. Visual Studio requires `electron.pdb`.

Can you please give us access to the symbol files and a recommendation on how to debug Electron crash dumps?

* Electron version: v0.37.2
* Operating system: Windows 10 Home

**Comment by felixrieseberg** [comment]
Benny! The symbol server is here: http://54.249.141.255:8086/atom-shell/symbols. I'll also put it on my to-do list do make it easier for people to understand how to debug Electron on Windows.

**Comment by zcbenz** [comment]
The symbols server is currently not working because of some problems with our CI server.

**Comment by zcbenz** [comment]
I'm closing this since #5143 added some instructions. For the PDB symbols, I'm reopening #784.

**Comment by dhaavi** [comment]
Just in case anyone stumbles over this, @felixrieseberg has written a blog post on how to debug electron crashes here: https://felixrieseberg.com/debugging-electron-apps-on-windows/
