### ISSUE TITLE
github releases server is extremely slow

### ISSUE THREAD

**Issue by OneOfOne** [electron/electron#5142]
I was trying to download electron v0.37.5 for vscode and it was downloading at 0-1kb/s, ran into this issue trying to download other releases on github as well.

Is it possible to use a different CDN?

**Comment by zcbenz** [comment]
It is possible to change to another mirror depending on the build system of vscode, for example the `electron-download` module provides a env variable to specify the mirror: https://www.npmjs.com/package/electron-download. However the only mirror server I know is located in China, so it might not help you.

Or you can contact GitHub to complain about the slow connection: https://github.com/contact.
