### ISSUE TITLE
Modularize to reduce footprint

### ISSUE THREAD

**Issue by mhalano** [electron/electron#5144]
The footprint of an application which uses Electron is 40-50MB. I say this as a bug. Probably is possible create a way to modularize and just use in the final build the parts which web apps needs, like a Linux kernel for an embedded system. An example: If the app don't need to show notifications, this part of code is not included in Electron final build. Result = minimum footprint in storage and RAM.

**Comment by baconface** [comment]
This isn't a bug. Electron packages both Chromium and Node.js along with what they are dependent on to run. And they try to cut out what is overall likely not needed or can be done via Node.js. Nit picking and cutting features here isn't going to yield a big difference when the bulk of it is required for Electron to operate. Modularizing also requires massive modifications to Chromium itself which makes the project considerably harder to maintain against the upstream.
