### ISSUE TITLE
Does WebView, like iFrame, support the Resource Priorities spec?

### ISSUE THREAD

**Issue by snoblenet** [electron/electron#5145]
While the user is interacting with a WebView I won't to preload the next WebView (CSS display hidden). With iFrame's you'd use W3C's Resource Hints spec to ensure the loading of the second iFrame didn't drag on the loading of the first.

http://w3c.github.io/resource-hints/

Does Electron's WebView allow the same?

**Comment by zcbenz** [comment]
No there is no such feature in webview tag, if you really want it I suggest creating a feature request at Chromium's issues list, since Electron is using Chromium's webview code.
