### ISSUE TITLE
Window: backgroundColor is not applied as I pass it in?

### ISSUE THREAD

**Issue by bpasero** [electron/electron#5150]
* Electron version: 0.37.5
* Operating system: Mac OS X 10.11.4

When I pass `backgroundColor: '#FF0000' to a window, the color that shows up on the screen is actually '#FF301E'.

**Comment by bpasero** [comment]
This only seems to happen on Mac, not Windows or Linux.

**Comment by zcbenz** [comment]
How did you get the actual color value? I put a `div` with `background-color: red` in the page, and the color of it is exactly the same with window's `backgroundColor`.

**Comment by bpasero** [comment]
I am setting the background color on the window and wait for 5 seconds before calling loadUrl(). In the index.html I set the color to be red. In the video below you can see the 2 colors are changing:

![untitled](https://cloud.githubusercontent.com/assets/900690/14527758/63658882-024c-11e6-8ef4-eb5ba9d9c191.gif)

**Comment by zcbenz** [comment]
I turned off f.lux and saw it now. 😸

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
@zcbenz I am still seeing different colors though. In my test I set #FF0000 as background color on the window and via CSS on the body and the window color becomes #FF2E20

**Comment by zcbenz** [comment]
There are three layers for drawing on OS X: 1. the web page; 2. the RenderWidgetHostView; 3 the NSWindow. Before you call `loadURL`, the background color of NSWindow is showed, which somehow displayed wrong color than the one we passed to. So if you `loadURL` immediately after creating the window, the `backgourndColor` should work perfectly.

**Comment by bpasero** [comment]
Yeah it works quite good, it is just a slight flicker (hard to notice) from the time I show() the window until loadUrl() does something. Not a big deal.
