### ISSUE TITLE
Error running electron-quick-start

### ISSUE THREAD

**Issue by dominikmathmann** [electron/electron#5154]
* Electron version: 0.37
* Node Version: 4.2.2 (also tried with 5.1)
* Operating system: Windows 8.1 Pro

I clone the Quick-Start example an try to run it as suggested. I get an error.

Log:
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Software\\Tools\\node\\node.exe',
1 verbose cli   'E:\\Software\\Tools\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart electron-quick-start@1.0.0
6 info start electron-quick-start@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info electron-quick-start@1.0.0 Failed to exec start script
9 verbose stack Error: electron-quick-start@1.0.0 start: `electron main.js`
9 verbose stack Exit status 3221225621
9 verbose stack     at EventEmitter.<anonymous> (E:\Software\Tools\node\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (E:\Software\Tools\node\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid electron-quick-start@1.0.0
11 verbose cwd E:\Entwicklung\privat\electron-quick-start
12 error Windows_NT 6.3.9600
13 error argv "E:\\Software\\Tools\\node\\node.exe" "E:\\Software\\Tools\\node\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "start"
14 error node v4.2.2
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error electron-quick-start@1.0.0 start: `electron main.js`
17 error Exit status 3221225621
18 error Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
18 error This is most likely a problem with the electron-quick-start package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron main.js
18 error You can get their info via:
18 error     npm owner ls electron-quick-start
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

If i try to run the app directly with electron my/path/to/quickstart nothing happens...

Somebody any idea?
Thanks

**Comment by zcbenz** [comment]
It seems that you have some problems with your environment, I suggest seeking help from [the community](https://github.com/electron/electron#community).
