### ISSUE TITLE
Store entire website into a cache version ?

### ISSUE THREAD

**Issue by MattiooFR** [electron/electron#5158]
* Electron version: 0.37.5
* Operating system: OSX

Hi,

I was wondering, is it possible to store an entire website somewhere, when I use loadURL() function, that I could load that "cache" and have it offline if I disable internet in my computer, or if the URL is not reachable in the future.

Thanks !

**Comment by luigiplr** [comment]
:neutral_face: Yes its possible. https://www.npmjs.com/package/website-scraper

**Comment by zeke** [comment]
Sounds interesting, @MattiooFR. Keep us posted as you work on it!

**Comment by zcbenz** [comment]
Chromium doesn't have offline mode, and I don't think they will ever add it. So we wont be able it have builtin feature for this, you have to use third party node modules instead.

**Comment by MattiooFR** [comment]
Hey !
[Website-scraper](https://www.npmjs.com/package/website-scraper) seems to be a very good way to do that and it works perfectly !

**Comment by zeke** [comment]
Nice, @MattiooFR. Is your project public on GitHub?

**Comment by MattiooFR** [comment]
@zeke not yet but it will !
