### ISSUE TITLE
autoUpdater.quitAndInstall does not restart when app.makeSingleInstance is used

### ISSUE THREAD

**Issue by havenchyk** [electron/electron#5163]
* Electron version: 0.37.2
* Operating system: Window 7 x64

I'm doing auto update of app and run `autoUpdater.quitAndInstall()` on 'update-downloaded' event.
With using `app.makeSingleInstance` quiteAndInstall() will not start my app again, just quit.

Is it possible to fix?

**Comment by zcbenz** [comment]
@paulcbetts It seems that we should use `--processStartAndWait` in `autoUpdater.quitAndInstall`?

**Comment by felixrieseberg** [comment]
Couldn't one just run makeSingleInstance after squirrel events have been evaluated?

**Comment by havenchyk** [comment]
@felixrieseberg it's a question to @paulcbetts, isn't it?

**Comment by felixrieseberg** [comment]
I haven't tried it, but my feeling is that one could just check process.argv and only make it a single instance if it's a "normal" launch.

**Comment by zcbenz** [comment]
@felixrieseberg Having two instances of Electron running at the same time is usually not good, race conditions may happen when reading/writing things in `userData` dir.
