### ISSUE TITLE
Add `isDefaultProtocolClient` API

### ISSUE THREAD

**Issue by bengotow** [electron/electron#5164]
The new `setAsDefaultProtocolClient`  and `removeAsDefaultProtocolClient` APIs are great, but without a way to query the current state, it's not possible to implement a UI element like this one. I think it'd be great to add `isDefaultProtocolClient`!

![image](https://cloud.githubusercontent.com/assets/1037212/14545184/fc1a6fac-026a-11e6-98d5-8bf6b2f9678e.png)

Also, I find the naming of these APIs pretty confusing. On Mac OS X and iOS `mailto` is referred to as a "URL Scheme", not a protocol (https://developer.apple.com/library/ios/featuredarticles/iPhoneURLScheme_Reference), and it seems like that might be the case on Windows too. (https://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx)

It'd be nice to clarify that this is registering the app system-wide, while the other `protocol` module is only for handling requests initiated from within the app. 

Maybe we could change these to `registerForURLScheme`, `isRegisteredForURLScheme`?

**Comment by bengotow** [comment]
After doing a bit more digging, it looks like the Microsoft documentation calls them "URL Schemes" as well, and you handle them by defining a "pluggable protocol handler", which can be used for other things as well.

**Comment by paulcbetts** [comment]
Please don't rename public APIs, even if the name is less-than-ideal

**Comment by bengotow** [comment]
Could we consider deprecating it? Or maybe the takeaway is just to be more careful to match platform conventions in the future? Really a shame in the long run because we have to add language to the docs explaining what this means, and a better name might make it obvious.

**Comment by zcbenz** [comment]
I don't think using "URLScheme" would make it clearer, it is as confusing as "protocol", we already have a bunch of `webFrame.registerURLScheme*` APIs.

**Comment by bengotow** [comment]
Ok - I'll rename this to just be about querying current state.

**Comment by felixrieseberg** [comment]
I can take this one.
