### ISSUE TITLE
Expose --disable-directwrite-for-ui flag

### ISSUE THREAD

**Issue by Tyriar** [electron/electron#5165]
See https://github.com/Microsoft/vscode/issues/1334 for more context, basically this flag is the workaround for a blurry text issue that repros in VSCode, Atom and Chrome.

Article with fix for Chrome: http://www.trilithium.com/johan/2015/03/chrome-directwrite-2/

![d9e426da-a33d-11e5-94bf-d5aa826942c2](https://cloud.githubusercontent.com/assets/2193314/14545301/d9d3701e-0252-11e6-9996-1a41306982a5.png)

**Comment by paulcbetts** [comment]
Does this actually fix your bug?

**Comment by zcbenz** [comment]
They are already in Electron.

**Comment by Tyriar** [comment]
@zcbenz It's not listed on https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md though?

**Comment by zcbenz** [comment]
@Tyriar Not all command line switches are listed there, since there are hundreds of them. Electron uses Chromium's content module, so the command line switches that implemented in it will be inherited.

**Comment by Tyriar** [comment]
@zcbenz oh ok thanks, I thought they were being exposed explicitly.

**Comment by sangohan** [comment]
The flag `--disable-directwrite-for-ui` is experimental in chrome, and I suppose that's why it's undocumented, as it may go away in a future version of chrome. I think this is a fundamental bug in chrome, not in electron tbh.
