### ISSUE TITLE
Creating directory at the wrong place after packaging

### ISSUE THREAD

**Issue by goktugerce** [electron/electron#5170]
* Electron version: 0.37.5
* Operating system: Ubuntu 15.10

I packaged my project using [electron-packager](https://www.npmjs.com/package/electron-packager). Normally, I create a directory named `downloads` in application directory where my `main.js` file exists. After packaging, I have `locales` and `resources` directories along with other files, and inside `resources` directory, there is another named `app` and there's also `electron.asar` file. Inside `app` folder there are my project files.

When I run the executable, it creates the directory at the same location with executable file, instead of creating it under `/resources/app/`. I don't know what causes this and how to fix it.

My `createDirectories` function:

    // create directory if it does not exist
    function createDirectory(directory, callback) {
        Fs.mkdirs(directory, function (err) {
            if (err) {
                console.error(err);
                return callback(err);
            } else {
                return callback();
            }
        })
    }

I give `downloads/images/` as a parameter to this function, for example. `Fs.mkdirs` is a method of `fs-extra` module.

**Comment by zcbenz** [comment]
You need to use absolute paths, otherwise the location of the files will be depended on current working directory.
