### ISSUE TITLE
XLSX.writeFile failure in electron release package

### ISSUE THREAD

**Issue by barbalex** [electron/electron#5174]
* Electron version: 0.37.5
* Operating system: windows 10

I have implemented XLSX (https://github.com/SheetJS/js-xlsx) in electron and it works very well in dev mode (I have also implemented it successfully in regular web apps).

Unfortunately once I created a release package it fails: On this line

    XLSX.writeFile(wb, path, { bookType: 'xlsx', bookSST: true, type: 'binary' })

electron's window turns white / empty / blank.

Can anyone help me debug this? I am an electron noob :-(

This issue has also been reported in the XLSX repo: https://github.com/SheetJS/js-xlsx/issues/399

**Comment by zcbenz** [comment]
I'm closing this since it is already reported in the original module. We can't look into failure of every third party modules because there are just too many of them, but if it turns out to be a bug of Electron, we would be happy to fix it.

**Comment by barbalex** [comment]
Well, the thing is: This is probably not an issue in XLSX. Because XLSX works perfectly in Chrome regular browser and in dev mode in electron.

Don't you have a hunch what could possibly be different between dev mode and release?

This bugs me as it works perfectly in dev mode.
And I have absolutely no Idea how to track this issue down.

The only things I can tell is:
- the active browserWindow turns white
- the window title remains, so I guess no new window was opened (?)
- code inserted after the XLSX call does not run

**Comment by barbalex** [comment]
I tried using exceljs (https://github.com/guyonroche/exceljs) instead of XLSX.
It turns out exceljs is very powerful yet much simpler to use than XLSX. Nice.

Unfortunately exactly the same happens:

- works in dev
- window turns white in release
- window title remains, so I guess no new BrowserWindow was opened

And it happens on this line:

    workbook.xlsx.writeFile(path)

**Comment by barbalex** [comment]
I forgot to mention: The page can be reloaded. So the BrowserWindow is definitely still there, even though blank
