### ISSUE TITLE
Electron 0.37.6: process.exit() no longer returns to terminal on Linux

### ISSUE THREAD

**Issue by bpasero** [electron/electron#5177]
* Electron version: 0.37.6
* Operating system: Ubuntu 15

When updating from 0.37.5 to 0.37.6 our integration tests no longer finish. They open a VS Code window, run some tests in it and then terminate and return the status of the test run as exit code to the CI terminal. 

It seems when I call process.exit() from the main side with latest, I am not getting out of the process back to the terminal.

I wonder if https://github.com/electron/electron/commit/6e467534997704b3167e61ff874e4d81b3ee5dc2 could have an impact?

**Comment by bpasero** [comment]
Hm, I cannot reproduce with a standalone electron sample, trying to dig into more...

**Comment by bpasero** [comment]
Ok this is due to the fact that `will-quit` is not fired when calling `process.exit();`

@zcbenz is `app.exit` and `process.exit` the same after all when called from the main side?

**Comment by paulcbetts** [comment]
In general, `process.exit` results in sadness in Electron, you should always use `app.quit` instead

**Comment by bpasero** [comment]
Well, we use it in cases where we do not want a normal shutdown (e.g. second instance starting and shutting down after talking to first instance). 

If there is app.exit(), I would expect it to behave like process.exit(), but making Electron happy.

**Comment by zcbenz** [comment]
@bpasero `process.exit` is mapped to `app.exit` in the main process in Electron, because we always got reports of using `process.exit` with happy results.

**Comment by bpasero** [comment]
@zcbenz great, I am all for happiness :)

**Comment by bpasero** [comment]
Also: another use case for app.exit() is that I can return an exit code to the terminal. Since I need to report the status of the integration tests via the exit code, there really is no other option for me it seems.
