### ISSUE TITLE
property 'createDirectory' for dialog.showOpenDialog is meaningless

### ISSUE THREAD

**Issue by inklesspen** [electron/electron#5178]
After the property didn't do what I expected, I looked at the code. `createDirectory` seems to only actually be implemented on OS X Electron, but according to the OS X docs, `[dialog setCanCreateDirectories:YES]` is only meaningful for a save dialog, not an open dialog.

**Comment by zcbenz** [comment]
Didn't realize this before 👍 , we should probably move this property to `dialog.showSaveDialog`.

**Comment by kevinsawicki** [comment]
I am seeing it have an effect in the open dialog.

Notice the `New Folder` button in the bottom left is only present when `createDirectory` is set.

### With `createDirectory`

```js
dialog.showOpenDialog({title:'hey', properties: ['openFile', 'createDirectory']})
```

<img width="709" alt="screen shot 2016-04-21 at 3 42 35 pm" src="https://cloud.githubusercontent.com/assets/671378/14726530/c8282550-07d7-11e6-9be1-55fa52806a6b.png">

### Without `createDirectory`

```js
dialog.showOpenDialog({title:'open', properties: ['openFile']})
```

<img width="712" alt="screen shot 2016-04-21 at 3 42 48 pm" src="https://cloud.githubusercontent.com/assets/671378/14726531/c8285390-07d7-11e6-8e77-a4eb754051fc.png">

**Comment by kevinsawicki** [comment]
@inklesspen did you not see the `New Folder` button impacted by setting `createDirectory` in the open dialog?

**Comment by inklesspen** [comment]
I could have sworn I was able to see the `New Folder` button without `createDirectory`, but I think I must have been misled by parts of my app not being subject to webpack's hot reload (and also by Apple's docs not actually listing it for the `NSOpenPanel`, which it turns out is a subclass of `NSSavePanel`). Sorry for the false alarm.

**Comment by kevinsawicki** [comment]
> Sorry for the false alarm.

@inklesspen no worries, closing this out.
