### ISSUE TITLE
webview FileSystemPermissionRequest access

### ISSUE THREAD

**Issue by JayCanuck** [electron/electron#5179]
* Electron version: 0.37.5
* Operating system: Windows 10
* Feature Request:

I noticed searching previous issues that webview 'permissionrequest' event types were being handled internally in electron. FileSystemPermissionRequest would be useful having app-side access, to allow/deny access to depending on filepath patterns, so as to allow specific directories for file:// urls on a per webview basis.

**Comment by zcbenz** [comment]
I'm merging this to #1378.
