### ISSUE TITLE
textarea cannot get focus

### ISSUE THREAD

**Issue by christinesha** [electron/electron#5182]
* Electron version:
* Operating system: windows

I have an electron app, click on a link on the main page, window.open()  a new page. The new page contains a textarea and other input controls. After textarea loses focus, it cannot get focus again. Not sure what is the problem.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by seanzer** [comment]
I think it has to do with `-webkit-app-region`. I had to explicitly set it to `-webkit-app-region: no-drag`

**Comment by zcbenz** [comment]
Closing until more information is provided.
