### ISSUE TITLE
`WebContents.executeJavaScript()` never succeeds when called during a resource load, but after page load

### ISSUE THREAD

**Issue by Mr0grog** [electron/electron#5183]
* Electron version: 0.37.6
* Operating system: All platforms

If you call WebContents’s `executeJavaScript()` method after the main frame finishes loading, but while a subframe is loading, the JS will never get executed and the call will never complete (unless you navigate the main frame to some new page). The culprit is how the JS additions to `WebContents` choose to forward the call to the `WebFrame`: https://github.com/electron/electron/blob/master/lib/browser/api/web-contents.js#L119

`webContents.isLoading()` will be true when a subframe is loading even if the main frame is finished. In that case the JS additions wait for `did-finish-load` before sending the call off to the frame, but that never happens.

I *think* Chromium’s `WebContents::IsLoadingToDifferentDocument` is the thing we actually want to check (instead of `WebContents::IsLoading`), but that’s not exposed in Electron’s WebContents API. Should it be? If not, we could track the `did-get-response-details` event to determine whether the main frame is loading. (We can’t use `did-start-loading` because that fires for sub-frames and there’s currently no way to differentiate [should there be?]).

On the other hand, is this check really about not running scripts while a page is loading, or is it just about making sure at least the first page has been loaded? (The `this.getURL()` check is what makes me wonder). If so, it would be better and simpler to just have a flag that says a page has been loaded, so any `executeJavaScript` call is now safe to forward along.

Many Nightmare users are hitting this issue in real-world cases (it’s particularly bad on pretty much any page with ads), e.g. https://github.com/segmentio/nightmare/issues/375

Simple Electron app test case:

```js
var electron = require('electron');
var mainWindow = null;

electron.app.on('ready', function() {
  mainWindow = new electron.BrowserWindow({show: true});

  mainWindow.webContents.on('did-finish-load', function() {
    console.log('Main frame loaded.');

    setTimeout(() => {
      mainWindow.webContents.executeJavaScript(`
        var iframe = document.createElement('iframe');
        iframe.src = 'http://cnn.com';
        document.body.appendChild(iframe);
      `);
    }, 40);

    setTimeout(function execute() {
      console.log('Started executeJavaScript');
      mainWindow.webContents.executeJavaScript(
        'console.log("hello");',
        result => {
          console.log('...finished');
          setTimeout(execute, 25);
        });
    }, 25);
  });

  mainWindow.webContents.loadURL('http://example.com');
});
```

This logs:

```
Main frame loaded.
Started executeJavaScript
...finished
Started executeJavaScript
```

And just stops there, when you should get `...finished` again.

**Comment by felicienfrancois** [comment]
According to the timeout values, the first script that executes (and succeed) is the console.log. The second is the iframe load.
So the console.log don't fail because of resource load.
The resource load fail

**Comment by Mr0grog** [comment]
@felicienfrancois That’s not quite right—the resource load actually succeeds, and it doesn’t matter whether it succeeds or fails anyhow. The issue is that `executeJavaScript` is called *during* the resource load. When that happens, the script will simply never get executed, which is the issue.

The reason why is actually extremely clear if you look into https://github.com/electron/electron/blob/master/lib/browser/api/web-contents.js#L119 and the implementation of Chromium’s `WebContents::IsLoading`. The example here is just illustrative.

**Comment by felicienfrancois** [comment]
ok understood

**Comment by Mr0grog** [comment]
Anyway, happy to write a patch for this if someone who knows Electron well can give feedback on which of the approaches outlined above is best (exposing `WebContents::IsLoadingToDifferentDocument`, tracking resource load events, or just not doing this check at all once the first page has been loaded). Or if there’s a different approach that would be better.

**Comment by zcbenz** [comment]
I'm 👍 on exposing `WebContents::IsLoadingToDifferentDocument` and use it in `executeJavaScript`.
