### ISSUE TITLE
Cannot view Blink logs

### ISSUE THREAD

**Issue by dcposch** [electron/electron#5185]
* Electron version: 0.37.5
* Operating system: Ubuntu 15.10

According to this page, I should be able to show most Chromium logs using `--enable-logging` and the Blink (rendering engine) logs using `--blink-platform-log-channels=<channels>`

* `--enable-logging` **works** in Electron
* `--blink-platform-log-channels` **doesn't work**, as far as I can tell

Running
```
electron --enable-logging --v=2 --blink-platform-log-channels=Media .
```
...starts my app, prints a ton of logs, but Chromium logs only, no Blink logs. This makes it hard to debug renderer issues.

The flags are being passed correctly to the renderer process:

```
$ ps -eF | grep electron
dc       17534 20978 10 382160 124140 4 05:41 pts/13   00:00:00 /home/dc/electron/out/D/electron --enable-logging --v=2 --blink-platform-log-channels=Media .
dc       17536 17534  2 92125 62528   3 05:41 pts/13   00:00:00 /home/dc/electron/out/D/electron --type=zygote --enable-logging --no-sandbox --v=2
dc       17558 17534  4 155246 109932 4 05:41 pts/13   00:00:00 /home/dc/electron/out/D/electron --type=gpu-process --channel=17534.0.1448236558 --enable-logging --no-sandbox --v=2 --window-depth=24 --supports-dual-gpus=false --gpu-driver-bug-workarounds=3,16,54 --disable-gl-extensions=GL_ARB_occlusion_query GL_ARB_occlusion_query2 --disable-accelerated-video-decode --gpu-vendor-id=0x8086 --gpu-device-id=0x0d26 --gpu-driver-vendor --gpu-driver-version --enable-logging --v=2 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
dc       17563 17536 14 324366 166984 2 05:41 pts/13   00:00:01 /home/dc/electron/out/D/electron --type=renderer --blink-platform-log-channels=Media --enable-logging --no-sandbox --v=2 --lang=en-US --node-integration=true --background-color=#1E1E1E --num-raster-threads=4 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553 --disable-accelerated-video-decode --channel=17534.1.1614456547 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
```

Thanks in advance if anyone knows how to fix this.

**Comment by dcposch** [comment]
Figured it out, it is probably because `libchromiumcontent` needs to be built with debug flags

http://pwnall.herokuapp.com/blog/2013/10/25/logging-in-chromium

**Comment by dcposch** [comment]
So building electron with `./script/build.py -c Debug` isn't enough.

Looks like the `script/build` in `libchromiumcontent` doesn't have configuration options.

@zcbenz do you know how to get a debug build of Electron, with the debug flags enabled in Chromium and Blink as well?

Thanks in advance!

**Comment by zcbenz** [comment]
You can set the `blink_logging_always_on` flag to `1` in libchromiumcontent (in `chromiumcontent/chromiumcontent.gypi`), and do a rebuild to get a build of libchromiumcontent with blink logging enabled.

**Comment by dcposch** [comment]
@zcbenz thanks!
