### ISSUE TITLE
win: Window frames are missing when DWM is turned off

### ISSUE THREAD

**Issue by orzFly** [electron/electron#519]
When DWM is turned off (in Windows 7 select a theme without Windows Aero), the window frames are missing.

![image](https://cloud.githubusercontent.com/assets/158528/3713445/7e87f66a-156b-11e4-995d-642cd1c1806a.png)

When DWM is turned on, everything works fine.
![image](https://cloud.githubusercontent.com/assets/158528/3713458/e8ecaeb4-156c-11e4-9869-ed91a2d771f5.png)

This is the default app without any modification.

I built this from b84226244d840a1ec8410b2dbce03b9de3f5c7b1 in Windows Server 2012 R2 with Visual Studio 2013.

**Comment by polarathene** [comment]
@zcbenz @orzFly Is there a way to switch from `chrome` frame decoration to windows `native` frame decoration? I've noticed Atom-Editor is using the `native` frame decoration, while minor the menu is missing bottom padding with `chrome` frame decoration as well as app icon besides the title. Is there a way to adjust this?
