### ISSUE TITLE
WebView loses content after hidden for amount of time

### ISSUE THREAD

**Issue by locomain** [electron/electron#5193]
* Electron version: v0.37.6 
* Operating system: windows 7,8.1 and 10

after a small amount of time the content in the webview disappears or the webview turns white.
This happens when i hide a webview en unhide it later.

EDIT:
this also occurs when a window containing a hidden webview gets minimized.
as soon as the window gets un-minimized and the webview gets unhidden the view is empty / white.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by paulcbetts** [comment]
WebView probably doesn't _deal_ with `display:none`, try `visibility:hidden` instead

**Comment by locomain** [comment]
@zcbenz shop.dreamincode.nl/packages/getPackage.php?package=nexmessenger :)

**Comment by locomain** [comment]
@paulcbetts i will try it out

**Comment by zcbenz** [comment]
It is a know bug (#4395) that webview gets problems when not visible, there is a workaround for this:
https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md#css-styling-notes
