### ISSUE TITLE
Does `auto-updater` implements typical OS X update dialogs?

### ISSUE THREAD

**Issue by jviotti** [electron/electron#5195]
I'm trying to implement auto update functionality for OS X. We've implemented the server that complies with what `Squirrel.Mac` expects, however I wonder if we should take care of displaying dialogs informing the user that an application update is available, and once its downloaded, the typical "Install and relaunch" dialog visible in many OS X application, or its something handled by the `auto-update` module out of the box.

According to [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac#user-interface):

> Squirrel does not provide any GUI components for presenting updates. If you want to indicate updates to the user, make sure to listen for downloaded updates.

Is this something Electron implements though? This is what we have for now:

```js
const autoUpdater = require('auto-updater');
const dialog = require('./src/dialog');
const packageJSON = require('../package.json');
const os = require('os');

// Auto-update functionality has not been
// implemented for other platforms yet
if (os.platform() === 'darwin') {

  autoUpdater.on('error', dialog.showError);

  autoUpdater.on('update-downloaded', function() {
    autoUpdater.quitAndInstall()
  });

  autoUpdater.setFeedURL(`https://etcher.io/api/update/etcher?v=${packageJSON.version}`);
  autoUpdater.checkForUpdates();

}
```

Will this take care of showing the dialogs? Is there a way to easily test the auto-update functionality while in development?

***

* Electron version: 0.36.11
* Operating system: OS X 10.11.4

**Comment by paulcbetts** [comment]
> Will this take care of showing the dialogs?

Squirrel.Mac _has no dialogs of any kind_, unlike something like Sparkle (which is probably what you're thinking of). You should use the information that autoUpdater returns to make your own HTML-based dialog that's appropriate for your application

**Comment by kevinsawicki** [comment]
You can see how Atom provides these type of dialogs in https://github.com/atom/atom/blob/master/src/browser/auto-update-manager.coffee

**Comment by jviotti** [comment]
I see, thanks for the clarification.

**Comment by matjaz** [comment]
https://sparkle-project.org provides nice dialog. Is it possible to reuse this dialog in electron?

**Comment by paulcbetts** [comment]
> https://sparkle-project.org provides nice dialog. Is it possible to reuse this dialog in electron?

No, sorry. That'd be a great OSS library though!
