### ISSUE TITLE
Error trying to run quickstart commands

### ISSUE THREAD

**Issue by keyboSlice** [electron/electron#5198]
* Electron version: 0.37.6
* Operating system: Ubuntu 14.04

Receiving the following error when trying to get the quick start app up and running

/var/www/electron-quick-start/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

can anyone please advise?

**Comment by jlord** [comment]
Hi @keyboSlice! 

Since this issue is related to the Quick Start App I'm going to close it here and open an issue in the [electron-quick-start repository](https://github.com/electron/electron-quick-start).
