### ISSUE TITLE
Expose "prompt" option on `dialog.showOpen/SaveDialog`

### ISSUE THREAD

**Issue by bengotow** [electron/electron#5204]
On Mac OS X, you can change the text of the primary "OK" button in open and save dialogs by providing a "prompt": https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSSavePanel_Class/index.html#//apple_ref/occ/instp/NSSavePanel/prompt

It'd be great to make this an option on the dialog APIs. We want to show an open dialog and ask the user to create / select a folder where files will be saved, and change the prompt from "Open" to "Choose".

Slightly related to #5178

**Comment by bengotow** [comment]
Looks like this is also possible on Windows via https://msdn.microsoft.com/en-us/library/windows/desktop/bb761830(v=vs.85).aspx.

**Comment by zcbenz** [comment]
This is a duplicate of #1531.
