### ISSUE TITLE
Access to other application windows

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#5207]
* Electron version: 0.37.2
* Operating system: Windows 10

Hi, guys!
After getting sources using `desktopCapturer.getSources()`, we have windows ids, thumbnails and so on of other desktop applications windows. Is it possible to receive API of this windows to get their positions and handle events like 'minimized', 'moved' etc? I haven't found any modules that allow such functionality.

**Comment by bengotow** [comment]
Hey! I don't know if there's a good cross-platform way to do this. On Mac OS X, you'd want to use the "Accessibility" APIs. Once your app asks for permission to use Accessibility to control the computer, you can basically do anything you want to any window. I'm not sure there are events for `moved`, etc., but you could certainly poll. Not sure about Windows 10, though.

**Comment by zcbenz** [comment]
Interacting with other app's windows is completed different from managing our own, so it would lots of work and we won't benefit much by making it a builtin feature of Electron. I suggest writing a Node module for this purpose.

**Comment by clusterberries** [comment]
Thanks for answers!
Does NodeJS provide some Accessibility APIs?
