### ISSUE TITLE
Unable to define property in webview after updating Electron

### ISSUE THREAD

**Issue by teimaj** [electron/electron#5209]
I've recently had to upgrade Electron on an application, from 0.30.5 to the latest (0.37.6), and i am no longer able to use `var ipc = window['require]('electron').ipcRenderer;` to require the ipcRenderer module in a guest page on a `<webview>` 

Previously it worked perfectly well and the application was able to send and receive messages.

I noticed that now, ipcRenderer is set on the parent view of the `<webview>`, however i am unable set it on the `<webview >` itself

I also cannot see any documentation that shows any changes that would cause this to stop working 

Thanks

* Electron version: 0.37.6
* Operating system: Windows 10

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem? I'm not able to reproduce on my machine.

**Comment by teimaj** [comment]
So, i've since found out that i now have to specify a preload script on the `<webview>` tag attribute `preload`. This enables me to set a global variable for the guest page such as `window.ipcRenderer = require('electron').ipcRenderer` and then my application works.

I guess this `preload` attribute has been created between the previous version i was using and the current version, and the previous way no longer works. 

Going to close this as it's a not an issue
