### ISSUE TITLE
Downloads aren't working after authenticating with proxy server

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#5216]
* Electron version: 0.37.6
* Operating system: All

1. Configure a proxy server that requires basic authentication
1. Handle the [`app.login`](https://github.com/electron/electron/blob/master/docs/api/app.md#event-login) event and submit the correct username / password
1. Try to initiate or monitor a download using the `session` APIs
1. None of the events are firing 😞 

We're seeing a similar problem with file uploads freezing, despite successful authentication.

**Comment by deepak1556** [comment]
Can you attach [log-net-log](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#--log-net-logpath) trace if possible ?

**Comment by CharlieHess** [comment]
@deepak1556: Sure thing, here's a log: [net-trace.log.zip](https://github.com/electron/electron/files/230445/net-trace.log.zip).

**Comment by paulcbetts** [comment]
We've got a dummy Squid server set up if someone wants to give this a try, DM me on atomio

**Comment by deepak1556** [comment]
Wasn't able to reproduce the issue following the steps, the `net-log` trace shows the request was cancelled by an external factor to the network stack. Any reproducible app would help, thanks!

**Comment by zcbenz** [comment]
Closing until more information is provided.
