### ISSUE TITLE
webview new-window event is sometimes triggered twice

### ISSUE THREAD

**Issue by felicienfrancois** [electron/electron#5217]
* Electron version: 0.37.6
* Operating system: Windows 10

In a few cases, the webview `new-window` event is triggered twice.
I can reproduce it going to https://search.yahoo.com/search?p=any+query and clicking on one of the results.
Depending on the `allowpopups` attribute the behavior is different:
- With `allowpopups` disabled, I get the `new-window` event triggered twice (one with disposition `new-window` and the other with `foreground-tab`)
- With `allowpopups` enabled, I get only one event triggered (with disposition `new-window`), but I also get an unexpected new BrowserWindow opened, without getting the event catched.

**Comment by felicienfrancois** [comment]
it happens when the new window is opened with 'window.open' from an onclick event.
```html
<a href="somepage1.html" target="_blank" onclick="window.open('somepage2.html'); return false">Click me</a>
```
in this case, both tabs are opened, and when `allowPopups` is on, the event for 'somepage2.html' is not cached (and it opens in an unexpected new BrowserWindow).

With Chrome, only `somepage2.html` is opened, even if the onclick event handler returns true (event default not prevented)

**Comment by zcbenz** [comment]
I can no longer reproduce this in v1.3.1 anymore.
