### ISSUE TITLE
Electron bluebird promise not defined?

### ISSUE THREAD

**Issue by sweetim** [electron/electron#5220]
* Electron version: 0.37.6
* Operating system: Wins 10

I would like to know is `electron` supports `bluebird` promisification? I am having problem when I try to include the `bluebird` package

```javascript
const Promise = require('bluebird')
```

In the console, it complains that Promise is not defined?
```
E:\myapp\node_modules\bluebird\js\release\bluebird.js:3 
Uncaught ReferenceError: Promise is not defined
```

Am I missing something?

**Comment by zcbenz** [comment]
`bluebird` detects current environment and if it found a browser like environment weird things will happen. I suggest using a the ES6 Promise instead, or reporting this to `bluebird`'s repo.
