### ISSUE TITLE
process.env is not preserved to the renderer process

### ISSUE THREAD

**Issue by gliheng** [electron/electron#5224]
* Electron version: 37.6
* Operating system: linux

I set some environment variable to process.env in the browser process, then start the renderer process, but I can not get the environment variable I have set on the renderer process.

I tested this on windows and mac, they worked!

Since my app rely on this environment passing to the renderer process, it would be great if the behaviors are the same across different platforms.

**Comment by MarshallOfSound** [comment]
Seems a bit strange to use environment variables for communication between processes :+1: 

But as a temporary workaround you might be able to use `remote.getGlobal('process').env`.

**Comment by zcbenz** [comment]
This is unfortunately an expected behavior and we are not able to fix it, you can find more about it in #3306.

**Comment by myfrndjk** [comment]
Hi,

I am trying to use` process.env.TZ = 'America/Managua';` in my app
if I give that in main process it is working fine, if I give that in render process no effect.
is there any way to achieve this.
I just need to change the time zone for every request.

**Comment by dcsw** [comment]
In the rendering process, try using the following:

`
const electron = window.require('electron');
const remote = electron.remote;
//...
console.log(remote.process.env["TZ"]);
`

Change "TZ" to get other environment variable values.

**Comment by myfrndjk** [comment]
@dcsw : Thanks for the update.
Already @MarshallOfSound has clarified this  https://github.com/electron/electron/issues/9150

**Comment by ryancwalsh** [comment]
Maybe [this](https://github.com/electron/electron/issues/5224#issuecomment-332585403) is outdated. I get `Property 'remote' does not exist on type 'typeof CrossProcessExports'. ts(2339)`
