### ISSUE TITLE
Panels display error in Gnome 3.20

### ISSUE THREAD

**Issue by echpiel** [electron/electron#5226]
* Electron version: 0.36.x - 0.37.x (?)
* Operating system: any Linux with Gnome 3.20

The error has been detected and reproduced using the two most known editors that use Electron (Atom and Visual Studio Code) under Gnome 3.20 in Arch Linux and OpenSUSE Tumbleweed. Any other application using Electron in a similar way should be affected.

To reproduce the error:
  
1. Install Atom or VS Code (last available version) and open it.
2. Try to change focus to any other application or go to the Activities. See that only the title bar and menu are sent to the back, the panels stay on top.

I do not know how to provide more information. The error was initially reported in the VS Code Github tracker (#5533) and I was asked to report it here.

**Comment by sbruchmann** [comment]
For reference: [Microsoft/vscode#5533](https://github.com/Microsoft/vscode/issues/5533)

**Comment by zcbenz** [comment]
Can you paste a screenshot describing this? I'm not sure what Panels is.

**Comment by echpiel** [comment]
Hello there,

You can find attached two screenshots. The first one shows VS Code on the foreground with GNOME Files in the background. In the second one you can see GNOME Files in the foreground and VS Code in the background; also, to make it clearer I have clicked in the activity menu so it is also displayed. As you can see, the most part of the VS Code interface continues in front of everything. Even if you close the application a black rectangle will the there and will only disappear if you go to the activities screen.

As I said before, this happens also with Atom Editor, and it seems that it would happen with every app that uses a similar use of Electron.

![foreground](https://cloud.githubusercontent.com/assets/12746147/14732809/4968a01e-085e-11e6-8316-b285e32a4455.png)

![background](https://cloud.githubusercontent.com/assets/12746147/14732811/4e7b74be-085e-11e6-92b4-06288062cebd.png)

**Comment by zcbenz** [comment]
Thanks for the details, does it also happen for chromium-browser?

**Comment by echpiel** [comment]
It is even worse. Chromium just started:

![image](https://cloud.githubusercontent.com/assets/12746147/14734433/b2d0c188-086a-11e6-80d1-ae5ed4532b56.png)

And if you send it to the background it behaves just as Atom and VS Code, it keeps on top.

**Comment by echpiel** [comment]
By the way, everything worked fine with GNOME 3.18.

**Comment by zcbenz** [comment]
Do you mind reporting this to GNOME or Chromium's issues list? Electron uses Chromium for rendering, so this is either a bug of GNOME or Chromium, and we are not able to fix it on Electron's side.

**Comment by echpiel** [comment]
Thanks for the suggestion. I have working on this issue and the report is wrong. I thought that I had ruled all the other possibilities before reporting the error, but finally it is related to Chromium 3D rendering inside Gnome 3.20 in my installation (specifically, I think the culprit is the display card driver). Disabling 3D rendering in Chromium works as a workaround. If I could disable it for Electron based applications I could use them until a fix is provided.

You can close the issue.

Best regards.
