### ISSUE TITLE
Can't Extract Electron Zip From Inside Electron Environment

### ISSUE THREAD

**Issue by JeremyMiller** [electron/electron#5227]
* Electron version: 0.37.6
* Operating system: OS X 10.11.3

I have an electron application that I want to use to download and extract a prebuilt version of electron. The problem is that when extracting the zip I get an `Invalid Archive` error when the extractor gets to the `.asar` files in the electron zip. I'm using basically the same code as the `electron-prebuilt` project and the code works in the normal node environment.

I'm assuming the problem is something related to how electron modifies the native node `fs` functions to support reading from asar archives, but I'm not sure.

I'm expecting that this behaviour is considered normal so there won't be any fix. I would however really appreciate any suggestions concerning how to accomplish what I'm trying to do. I've been trying to figure out a solution for a while and I don't want to resort to shipping an application with prebuilt electron versions for each OS.

Thanks a lot for any help.

**Comment by JeremyMiller** [comment]
Found the solution: https://github.com/electron/grunt-download-electron/blob/master/tasks/download-atom-shell-task.coffee#L51. Sorry for the trouble.

I'll close this issue, but if there are any caveats I should know about regarding this fix, I'd appreciate it if you could let me know.

**Comment by jeffreylanters** [comment]
I know this issue is closed, but what was the solution exactly?
