### ISSUE TITLE
Downloading a file emits a `did-fail-load` event 

### ISSUE THREAD

**Issue by ccnokes** [electron/electron#5228]
* Electron version: 0.36.9
* Operating system: Mac OSX 10.11.14

When I click on a link that triggers a file download, it emits a `did-fail-load` event with an error code `-3`. The download works and is saved as expected though. 

As a side note, I was calling `loadURL` in the `did-fail-load` handler which caused Electron to crash. I can provide the full dump for that if you'd like. 

Let me know if you'd like any more details.

**Comment by deepak1556** [comment]
Could you provide a simple app demonstrating the issue ?

**Comment by ccnokes** [comment]
Yeah, here you go: https://github.com/ccnokes/electron-did-fail-load. 

I was able to verify that behavior in 0.36.9 (my version) and the latest 0.37.6. My sample app is on the latest. 

I based it on electron-boilerplate so it's got all of that project's commit history on it, but here's my change set: 
https://github.com/ccnokes/electron-did-fail-load/commit/ce7f3a6d18615cbbf20bc09132bc81f58b7f0496

After `npm install`ing it, run `node server.js` to start a node server that will serve a gif to download. Then start the electron app with `npm run build && npm run start`. Click the "download gif" link to see the behavior I'm talking about. Electron should emit a `did-fail-load` event with a `-3` code, and then crash once the native save file dialog is closed. 

If it's helpful, I can try to PR a failing unit test for this. I wish I could jump in a debug it more but I don't really know C++ or ObjC 😦 .

**Comment by deepak1556** [comment]
Thanks for the test case, the `did-fail-load` is just a duplicate fire of `did-fail-provisional-load` which is to be expected for downloads, i think we should separate `did-fail-provisional-load` and `did-fail-load

**Comment by zcbenz** [comment]
> As a side note, I was calling loadURL in the did-fail-load handler which caused Electron to crash. I can provide the full dump for that if you'd like.

The crash had been fixed in 0.37.x.

> i think we should separate did-fail-provisional-load and did-fail-load since its causing confusion

It would be a breaking change, #1242.

**Comment by aight8** [comment]
If the url is a file download ONLY "did-fail-provisional-load" is emitted. "did-fail-load" NOT anymore!
