### ISSUE TITLE
Search through files not working in devtools after adding folder in workspace

### ISSUE THREAD

**Issue by darrrk** [electron/electron#5230]
* Electron version: 0.36.12, 0.37.6
* Operating system: Kubuntu 15.10

Try Ctrl+Shift+F, find progress freeze always.

**Comment by zcbenz** [comment]
I'm unable to reproduce, does it happen in default app?

**Comment by darrrk** [comment]
1. Need open devtools in any app
2. Go to "Sources" panel
3. Apply shortcut Ctrl+Shift+F (Cmd+Shift+F on OS X) for opening search through files
4. Try to search any request, not working. Search progress on bottom freezes.

**Comment by darrrk** [comment]
0.35.6 not affected.

**Comment by darrrk** [comment]
Looks like it low priority issue. Can I self fix it with JS knowledges only?
I think here need programmatically allow access to filesystem.

**Comment by darrrk** [comment]
Seems calling from devtools unresponsible
`DevToolsHost.sendMessageToEmbedder(JSON.stringify(message))`,
where message is:
```json
{
  "id": 51,
  "method": "indexPath",
  "params": [
    "<number requestId>",
    "<path to fs>"
  ]
}
```

**Comment by darrrk** [comment]
Cool stuff for electron devs! Thanks!

**Comment by darrrk** [comment]
`1.0.0` still broken indexing
Seems not fixed

**Comment by darrrk** [comment]
@deepak1556, maybe need update *brightday* for electron?
