### ISSUE TITLE
<webview> preload not work on v0.37.6

### ISSUE THREAD

**Issue by otarim** [electron/electron#5235]
* Electron version: v0.37.6
* Operating system:mac osx 0.11.4

webview `preload` attribute not work on electron v0.37.6.I use another version v0.36.12 and it works.

![image](https://cloud.githubusercontent.com/assets/2024477/14697322/2e4f786a-07b5-11e6-944c-3b58b429ed43.png)

v0.37.6 installed via npm and v0.36.12 installed from taobao mirror.

btw i notice my preload resource (hack.js) didn't loaded from devtool's network panel.

**Comment by kevinsawicki** [comment]
I'm having trouble reproducing this, would it be possible for you to provide a full sample app that isn't working?

**Comment by zcbenz** [comment]
Closing until more information is provided.
