### ISSUE TITLE
'login' callback for webview.getWebContents() not working

### ISSUE THREAD

**Issue by yuya-oc** [electron/electron#5240]
* Electron version: 0.37.6
* Operating system: Windows 10 x64

In renderer process, the webContents which is provided by `webview.getWebContents()` doen't login into the page when calling `callback('user', 'password')`. Besides, it seems that `event.preventDefault` also not working in this case because webview doesn't stop loading.

The sample app and console out put is here.

https://gist.github.com/yuya-oc/4832c866973d93ba65227a94758c431a

```
Object {}constructor: (...)preventDefault: (...)get preventDefault: ()set preventDefault: (value)sender: (...)get sender: ()set sender: (value)__proto__: Object
Object {}method: (...)get method: ()set method: (value)referrer: (...)get referrer: ()set referrer: (value)url: (...)get url: ()set url: (value)__proto__: Object
Object {}host: (...)get host: ()set host: (value)isProxy: (...)get isProxy: ()arguments: (...)caller: (...)length: 0name: ""prototype: Object__proto__: ()<function scope>set isProxy: (value)port: (...)get port: ()set port: (value)realm: (...)get realm: ()set realm: (value)scheme: (...)get scheme: ()set scheme: (value)__proto__: Object
() { [native code] }
```

**Comment by zcbenz** [comment]
Currently we do not support calling `event.preventDefault` in renderer process, you can find more about this in:
http://electron.atom.io/docs/v0.37.6/api/remote/#passing-callbacks-to-the-main-process

You can probably handle the `login` event of `app` module in the main process.

**Comment by yuya-oc** [comment]
Yes, I can handle it on 'login' event of app. I had thought it become easier to implement the login dialog in renderer process. Thanks.
