### ISSUE TITLE
Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by delvedor** [electron/electron#5242]
Hi all,
I made [this](https://github.com/delvedor/electron-screen) tiny module for getting screen info from windows.

If I require it from NodeJs (not Electron), I can read all the data without problem.
If I use it inside Electron I get this error.

<img width="858" alt="screen shot 2016-04-21 at 4 04 03 pm" src="https://cloud.githubusercontent.com/assets/4865608/14711912/751c826c-07db-11e6-948c-0b82ee1b6f5c.png">

I used electron-rebuilt.
What can it be?

* Electron version: 0.37.6
* Operating system: Windows 10 (but also 8 and 7)

**Comment by paulcbetts** [comment]
There's a trick to this where you get an extra file win32-delay-hook or something included that node-gyp does for you, but for the life of me I can't remember how it works or find anything on it. I'd try to copy-paste the code from https://github.com/paulcbetts/node-system-idle-time which is a similarly super simple module that definitely works with electron

**Comment by zcbenz** [comment]
It is very likely that the version of Electron used in your app is not the same with the one installed globally, and `electron-rebuild` got the wrong version. You can probably pass the version of Electron to  `electron-rebuild` manually, or use the dummy npm way of installing a module: http://electron.atom.io/docs/v0.37.6/tutorial/using-native-node-modules/#the-npm-way. With the latter way your module works on my machine.

**Comment by delvedor** [comment]
Let me understand, every user that want to use `electron-screen` module needs to setup [these](http://electron.atom.io/docs/v0.37.6/tutorial/using-native-node-modules/#the-npm-way) npm environment variables?

ps I've tried to pass a version to electron-rebuild but nothing changed.

**Comment by paulcbetts** [comment]
@delvedor No, only developers need to worry about this, when you package your app users won't think about this

**Comment by delvedor** [comment]
@paulcbetts cool!  
And if I want that the other developers don't have to compile it, is enough distribute through npm the .node file, right?

**Comment by paulcbetts** [comment]
@delvedor That approach doesn't really work with Electron, it's much better to ask developers to compile it

**Comment by delvedor** [comment]
@paulcbetts ok, thank you for your help and suggestions!
