### ISSUE TITLE
Conditional ContextMenu on Webview

### ISSUE THREAD

**Issue by cniemann88** [electron/electron#5245]
* Electron version: (prebuild) 0.36.9
* Operating system: Win 10 and Mac OS

Hey!

I've been trying to enable a simple conditional contextMenu on <webview>. Essentially i only want to show 'copy' on text and 'cut/copy/paste' on input fields, i might add more functionality to this later. However, i cannot get the target or even the selected text out of the webview before it gets added to the clipboard. all i get is the main <webview> tag, and nothing below it. For the application i am building there is no other way around using a webview, everything is steered through URL reroutes, and none of the pages are owned by the app, essentially its a very specialized browser that only runs for one website. 

I have code working to show a static context menu, and everything seems to function as expected, i would just like to improve the look and feel a little bit. 

Apparently the selected code from the webview makes it to the clipboard eventually, so i was wondering if there was anything i could hook into to get that data right before i want to open the contextMenu. My code is pretty simple: 

`
 var template = [    
    {
        label: 'Cut',
        accelerator: 'CmdOrCtrl+X',
        role: 'cut'
    },
    {
        label: 'Copy',
        accelerator: 'CmdOrCtrl+C',
        role: 'copy'
    },
    {
        label: 'Paste',
        accelerator: 'CmdOrCtrl+V',
        role: 'paste'
    },
    {
        label: 'Select All',
        accelerator: 'CmdOrCtrl+A',
        role: 'selectall'
    },
];

window.addEventListener('contextmenu', function (e) {
    e.preventDefault();
    
    var menu = Menu.buildFromTemplate(template);
        menu.popup(remote.getCurrentWindow());
}, false);`

Any help would be appreciated!

**Comment by zcbenz** [comment]
I'm merging this to #3210.
