### ISSUE TITLE
Move Focus to Next Window not working anymore

### ISSUE THREAD

**Issue by bpasero** [electron/electron#5246]
* Electron version: 0.37.6
* Operating system: Mac OS X 10.11

A user reported that with VS Code running with Electron 0.37.6 would no longer allow him to "Move Focus to Next Window". It seems you can assign a keybinding for this globally in settings (in this case he tried with Cmd+F1).

I verified that the same keybinding works just fine with our VS Code on Electron 0.35.6.

When I look through the release notes, I see an entry in v0.36.8 that might be suspicious?

> Fix Command + ~ not switching windows sometimes.

**Comment by zcbenz** [comment]
Yeah "Move Focus to Next Window" stopped working a long time ago, we worked around it by manually handling the cmd+~ shortcut, but if user specifies a custom key binding then it will not work.

**Comment by bpasero** [comment]
Suggesting Cmd+~ as a workaround seems like a good idea.

**Comment by djadomi** [comment]
Is it possible to add "Move Focus to Next Window" to the keymap? The lack of Cmd-` function is driving me slightly insane!

**Comment by bengotow** [comment]
Hey folks—any idea what change to Electron broke this behavior? I'm not able to reproduce it with an English keyboard layout (Cmd + ~ works for me in N1 using Electron 0.37, and we don't handle it manually), but if I change my keyboard layout to Swedish the shortcut no longer works in Electron as it does in other applications.

**Comment by bengotow** [comment]
It looks like there's additional discussion of this here: https://discuss.atom.io/t/os-x-cmd-short-does-not-work-on-some-keybord-layouts-azerty/12660

**Comment by maaarghk** [comment]
I don't buy the explanation on this thread. This is happening to me at random on a UK english keyboard. ` + e doesn't give me e grave, so not the OS' fault. Atom is the only app this is happening with across the whole system.
