### ISSUE TITLE
Can not copy text of devtools by context menu 

### ISSUE THREAD

**Issue by MetaMemoryT** [electron/electron#525]
In google chrome, you can open the inspector, navigate to the console tab, highlight some text, and right click, then select copy from the menu.

in the atom text editor, you cannot right click on text in the inspector console (or in the regular buffer) and select copy from the menu.

**Comment by 1j01** [comment]
:+1: Can't set conditional breakpoints (you have to open the context menu on a breakpoint to add a condition) which makes it rather difficult to debug where NaNs are [coming from](https://github.com/atom/atom/issues/5250) when they're being introduced only occasionally.

**Comment by s-a** [comment]
:+1: this is very Bad for mac users.

**Comment by ykadosh** [comment]
Any updates on the issue? I still have this issue a year later

**Comment by luchillo17** [comment]
I've stumbled uppon this, maybe is this the way to fix?
https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by yahyaKacem** [comment]
Still having the same problem the work around provided by @luchillo17 didn't work for me.
is there any news for this?

**Comment by luchillo17** [comment]
@yahyaKacem The edit says clearly it doesn't work, i'm sticking out to develop on Chrome for the time being since i don't need OS only features until later.

**Comment by bradennapier** [comment]
Did you guys remove the "Edit" from the menu where the copy/paste accelerators are added?

**Comment by main** [comment]
same problem on MAC OS

**Comment by zeroliu** [comment]
I'm experiencing the same issue on MAC OS and it is very frustrating. My copy/paste accelerators are added to Menu but it still can't copy/paste any text. I'm hoping to hear more about this issue. Thanks!

**Comment by jcrben** [comment]
@zcbenz noticing this with 1.84 on macOS High Sierra 10.13.4
![image](https://user-images.githubusercontent.com/5614134/40589198-18c79f78-619e-11e8-8340-be40d9e611df.png)

also can't do a CMD+click
![image](https://user-images.githubusercontent.com/5614134/40589205-28fc59ba-619e-11e8-8711-7d29dfd5409d.png)

I know this isn't the most recent version but I suspect this probably hasn't gotten attention from 2.0+ either...

**Comment by wallflips** [comment]
Take a look at this, it solved the issue for me on mac os sierra.

https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by zeroliu** [comment]
To give an update on my old comment, I realized the issue was due to the fact I started electron from tmux. All weird issues I have been experienced with electron are gone when not using tmux.
