### ISSUE TITLE
Black screen on Ubuntu

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#5257]
* Electron version: 0.37.*
* Operating system: Ubuntu

Every single version from `0.37.0` to `0.37.7` immediately gives a black screen on Ubuntu. Even the built in example window running directly from `electron` is black.

```bash
npm install electron-prebuilt
electron .
// window opens and is 100% black
```

Version `0.36.12` works just fine.

I am running `Ubuntu Desktop` inside of VirtualBox from OSX.

**Comment by zcbenz** [comment]
You can probably disable GPU acceleration to work around this, or just use another visual machine software. Basically the GPU acceleration of Linux in virtual machines is a mess, depending on the software of visual machine, the version and distribution of Linux, and the version of Chromium, you can get various results and bugs.

**Comment by brian-mann** [comment]
I tried using both of these and neither work.

```javascript
app.commandLine.appendSwitch("disable-gpu")
app.commandLine.appendArgument("disable-gpu")
```

Is there any other way to `disable-gpu` instead of passing this argument directly as `electron --disable-gpu`?
