### ISSUE TITLE
 How to define a module that can be used in the main progress and renderer process?

### ISSUE THREAD

**Issue by linkFly6** [electron/electron#5264]
* Electron version:0.37.6
* Operating system:windows 10
 
How to define a module that can be used in the main progress and renderer process?

like these modules:
-    clipboard
-    crashReporter
-    nativeImage
-    screen
-    shell

I want to define a module, can be used in progress main, but also in the use of renderer proces .

main progress:
```javascript
    const store = require(' store');
    module.exports = { foo:sore };
```

renderer process:
```javascript
  jQuery(function(){
        const store = require(' store');
   });
```

**Comment by zcbenz** [comment]
You can use the `remote.require` API:
http://electron.atom.io/docs/v0.37.7/api/remote/#remoterequiremodule
