### ISSUE TITLE
[Future Request] - Ability to Append Files to .ASAR archive

### ISSUE THREAD

**Issue by Dillybob92** [electron/electron#5265]
Hey guys,

This is just a request. But, I think the ability to append files to an .asar file would be really cool. This would make it so simple for patching files or whatnot.  

For example, if you only need to update a couple files, and instead of sending over the entire .asar package, just send over the files that will be overwritten. Thoughts? 

Edit: (The reason I thought about this is because our asar is around 100mb, and if I were to release a hotfix, or just several files that need to be patched, the user would either have to download the entire 100mb patch, or use asar locally to re-pack) -- So, I think a appending feature would be very intuitive here.

**Comment by paulcbetts** [comment]
On Windows, the ASAR file ends up being diff-patched anyways, I think it'd be more appropriate to request that Squirrel.Mac support general delta patching, which would save bytes on _all_ the files, not just the ASAR package.

**Comment by zcbenz** [comment]
Allow appending files only fixes a very specific edge case: when only a few files are added. If you want to patch some files, it won't work. I agree making the auto updater to handle this is the right way.
