### ISSUE TITLE
Not correctly choosing fonts in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by renkun-ken** [electron/electron#5266]
* Electron version: 0.35.6
* Operating system: Ubuntu 16.04 LTS

I'm using the latest release of Slack (v2.0.3 64-bit), VSCode (v1.0.0), and GitKraken (v1.1.0) in Ubuntu. The font rendering are good in Ubuntu 15.10. But when I had a fresh install of the newly released Ubuntu 16.04 LTS, the monospace and Chinese font rendering of these apps becomes weird (too thin).

Firefox can correctly use _Noto Sans CJK SC Regular_ to render Chinese font as it becomes default for Chinese language in Ubuntu 16.04 LTS. But Electron-based applications seem to suffer from not falling back to the right font in the GUI. Instead of choosing _Noto Sans CJK SC Regular_ for Chinese characters, it seems to have chosen _Noto Sans CJK SC Thin_, which is too thin for reading. 

My OS language and locales are English with Chinese installed (so I have the necessary fonts). 

The following text is for test:

```
hello, world!
测试文字
文字如果太细了就看不清楚
```

In `gedit`, the font looks fine:

![screenshot from 2016-04-23 23-11-28](https://cloud.githubusercontent.com/assets/4662568/14762268/d957dd98-09a8-11e6-802c-9edad4a78af8.png)

But in Electron-based apps, fonts are too thin:

VSCode:

![screenshot from 2016-04-23 23-06-10](https://cloud.githubusercontent.com/assets/4662568/14762238/233bb00c-09a8-11e6-9f05-28051bca0711.png)

Slack:

![screenshot from 2016-04-23 23-09-37](https://cloud.githubusercontent.com/assets/4662568/14762253/8f275366-09a8-11e6-8691-f8893b7d567c.png)

**Comment by zcbenz** [comment]
This seems to be an upstream bug of Chromium: https://crbug.com/595690.

**Comment by renkun-ken** [comment]
Here is a walk around: <http://www.xiangji.me/2016/04/29/solving-cjk-font-rendering-issue-in-chrome-on-ubuntu-16.04/>. I test it and it solves my problem :)

**Comment by renkun-ken** [comment]
It looks like fonts-noto-cjk package is updated and the problem is gone.

**Comment by zcbenz** [comment]
@renkun-ken Thanks for the update!
