### ISSUE TITLE
Add Menu.remove

### ISSUE THREAD

**Issue by quasado** [electron/electron#527]
How are we currently supposed to remove a menu entry, i.e. when we're adding & removing views? There seems to be an append() and insert() api on Menu only, no remove?

**Comment by jwu** [comment]
Well since we all known Chromium have this limitation, I found a way to work around with this. I paste my code here so that people can follow the way to get around it. 

My solution is to rebuild the menu except the item you specified by path. Let's say, you have a menu item  in the menu path: foo/bar/foobar, and when you run `Editor.MainMenu.remove('foo/bar/foobar')`, it will clone the exists Menu, except the one you want to removed. 

The code to do this:

```javascript
var Path = require('fire-path');
var Editor = require('fire-editor')
var Editor.JS = require('js-utils');

function _cloneMenuItemLevel1 ( menuItem ) {
    var options = Editor.JS.extract( menuItem, [
        'click',
        'selector',
        'type',
        'label',
        'sublabel',
        'accelerator',
        'icon',
        'enabled',
        'visible',
        'checked',
        // 'submenu', // NOTE: never clone submenu, other wise we can't change item inside it
        'id',
        'position',
    ]);
    if ( options.type === 'submenu' ) {
        options.submenu = new Menu();
    }
    return new MenuItem(options);
}

function _cloneMenuExcept ( newMenu, nativeMenu, exceptPath, curPath ) {
    var result = false;

    for ( var i = 0; i < nativeMenu.items.length; ++i ) {
        var menuItem = nativeMenu.items[i];
        var path = Path.join( curPath, menuItem.label );

        if ( Path.contains( path, exceptPath ) ) {
            if ( path === exceptPath ) {
                result = true;
                continue;
            }

            var newMenuItem = _cloneMenuItemLevel1(menuItem);
            if ( newMenuItem.type === 'submenu' ) {
                var removed = _cloneMenuExcept( newMenuItem.submenu,
                                                menuItem.submenu,
                                                exceptPath,
                                                path );
                if ( removed ) result = removed;
            }
            newMenu.append(newMenuItem);
        }
        else {
            newMenu.append(menuItem);
        }
    }

    return result;
}

// base on electron#527 said, there is no simple way to remove menu item
// https://github.com/atom/electron/issues/527
MainMenu.remove = function ( path ) {
    var newMenu = new Menu();
    var removed = _cloneMenuExcept( newMenu, this.nativeMenu, path, '' );

    if ( !removed ) {
        Editor.error('Failed to remove menu in path: %s, can not find it', path );
        return false;
    }

    // apply to main menu
    Menu.setApplicationMenu(newMenu);

    return true;
};
```

The 'fire-path' is just a io.js path module with Path.contains( pathA, pathB ) support, which used in above code, I put the implementation below. And the Editor.JS.extract is just a easy function to copy the properties you want from the oldMenuItem, so I guess you can modify it to your own.

```javascript
// pathA = foo/bar,         pathB = foo/bar/foobar, return true
// pathA = foo/bar,         pathB = foo/bar,        return true
// pathA = foo/bar/foobar,  pathB = foo/bar,        return false
// pathA = foo/bar/foobar,  pathB = foobar/bar/foo, return false
FirePath.contains = function ( pathA, pathB ) {
    pathA = FirePath.stripSep(pathA);
    pathB = FirePath.stripSep(pathB);

    //
    if ( pathA === pathB ) {
        return true;
    }

    // never compare files
    if ( Path.dirname(pathA) === Path.dirname(pathB) ) {
        return false;
    }

    if ( pathA.length < pathB.length &&
         pathB.indexOf (pathA) === 0 )
    {
        return true;
    }

    return false;
};
```

I test these in my editor-framework for a couple of days, and it works well, hope this can help you.

**Comment by bsclifton** [comment]
I recently spent a lot of time investigating this and found a solution that worked for me.  For [our project](https://github.com/brave/browser-laptop), we have menus like:
- File
- Edit
- etc (none of these change)

and menus which do change:
- History
- Bookmarks

Here's how I solved it for us:

1) Use the current menu handle and find the MenuItem object for the parent menu (ex: History)
2) Note that MenuItem has a submenu object, which is also of type menu
3) Call clear() on that submenu
4) Re-add the child menu items using submenu.append()
5) Call Menu.setApplicationMenu with your modified top-level menu handle

This seems to work great (you can [check the change out here](https://github.com/brave/browser-laptop/blob/8a044fc91707bbb5dd3835ce31a7c37b2d709314/app/menu.js#L593)).

My only concern is that it may leak memory.  I did some basic profiling by attaching to the process (with a version of Electron w/ symbols) and object counts seemed to be OK. Comments or concerns appreciated :smile: 

One route I tried, which did *not* work, was exposing the `RemoveItemAt` method of the underlying model. When you call this, it does remove the item from the menu that's visible to the user... but not from the menu object itself. On top of that, even if you call destroy on the MenuItem's submenu, it visibly leaks memory.  I can see why @zcbenz said this is a limitation of Chromium

**Comment by yunjia** [comment]
@bsclifton I think the work around works pretty well, except for one thing.

I'm not sure if you noticed, the `menu.items` gets accumulated, even `menu.clear()` has been called.

**Comment by codebytere** [comment]
As this is a limitation of Chromium and some workarounds appear to have been found, i'm going to go ahead and close this.
