### ISSUE TITLE
Packaging Electron App for Mac OS X

### ISSUE THREAD

**Issue by ilatif** [electron/electron#5270]
* Electron version: 0.37.6
* Operating system: Mac OS X (10.9)

I' am trying to develop a simple menu-bar based Mac App using Electron. I have successfully packaged the App into an `.app` file using `electron-packager`. But when I run the `.app` file, I' am seeing App's icon in **Dock** as well. Is there a way in Electron to remove App's icon from Dock for menu-bar based apps?

Thanks

**Comment by MarshallOfSound** [comment]
`require('electron').app.dock.hide()`

https://github.com/electron/electron/blob/master/docs/api/app.md#appdockhide-os-x

**Comment by paulcbetts** [comment]
Huh, TIL. There's also an entry in Info.plist you can use to permahide it

**Comment by ilatif** [comment]
@MarshallOfSound, @paulcbetts: Thanks for prompt reply and pointing me in right direction :-).
