### ISSUE TITLE
Get image from cache without re-downloading it

### ISSUE THREAD

**Issue by evgenyzinoviev** [electron/electron#5271]
Hi guys.

If an image has already been downloaded (and cached) with `<img src="..." />`, is it possible to get it from cache and save it to the disk to specified path, without downloading it again?

I tried to use `web-contents`/`session`/`download-item` download API but no success - it refetches the image from the server.

If it's not possible, then it would be great to add such API.

**Comment by zcbenz** [comment]
You can [get the data URL of img](https://gist.github.com/lucasferreira/1135780) and then use `nativeImage` API to convert it to actual file and save it to disk.

This is basically how Chromium implements the "Save Image As" feature, I don't know why but Chromium doesn't provide a way to save a file from disk cache directly.

**Comment by evgenyzinoviev** [comment]
This should work, thanks.

**Comment by klausgao** [comment]
@evgenyzinoviev have you made it？

**Comment by gch1p** [comment]
@klausgao sort of. You can use method suggested by @zcbenz, but the problem is that if, for example, you're dealing with jpeg, you cannot just save it as is - it will be reencoded. I don't know how to get original image from cache and just save it as is.
