### ISSUE TITLE
[Question] Can electron.app event 'activate' trigger before 'ready' event?

### ISSUE THREAD

**Issue by princejwesley** [electron/electron#5272]
* Electron version:  < 0.37.4
* Operating system: OSX

In my application, I have used `screen` instance in `ready` and `activate` event's callback.As per [this](https://github.com/princejwesley/Mancy/issues/123) ticket, `screen` is not ready to get `Display` object when `activate` event is triggered.

Is it possible to receive `activate` event before electron is initialised ? (Please let me know if it is a programmer's responsibility to wait for `ready` event before handling `activate` event)

**Comment by zcbenz** [comment]
The `activate` and `ready` events are mapped from OS X's `applicationShouldHandleReopen` and `applicationDidFinishLaunching` events, I couldn't find documentation on whether `applicationShouldHandleReopen` would be emitted before `applicationDidFinishLaunching`. So I guess you should probably get prepared for it.
