### ISSUE TITLE
Electron with AngularJS Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by jechazelle** [electron/electron#5274]
* Electron version: 0.37.6
* Operating system: Mac (El Capitan)

I have a problem when I want to use AngularJS with Electron :

> Uncaught SyntaxError: Unexpected token < home.html:1

But in my page home.html I have only `<div>Test</div>`

I tried to add : 

    1 - Declare <!DOCTYPE html> on my index.html
    
    2 - Declare the type on my script <script type="text/javascript" src="js/lib/angular.min.js"></script>

    3 - Change the include templateUrl in my module

**home.js (module)**

    'use strict';
    
    app.home = angular.module('ReleaseChecker.Home', []);
    
    app.home.config(['$routeProvider', function ($routeProvider) {
    
        $routeProvider.when('/', {
            templateUrl: './js/modules/home/views/home.html?d=' + Date.now(),
            controller: 'HomeController'
        });
        $routeProvider.otherwise({ redirectTo: '/' });
    
        // var routes = {
        //     '/': {
        //         template: './js/modules/home/views/home.html?d=' + Date.now(),
        //         controller: 'HomeController',
        //         page: {
        //             code: 'HOME',
        //             title: 'Home'
        //         }
        //     }
        // };
        //
        // for (var path in routes) {
        //     if (routes.hasOwnProperty(path)) {
        //         $routeProvider.when(path, routes[path]);
        //     }
        // }
    
    }]);
    
    app.home.run(['config', function (config) {
    
    }]);

When I use home.html empty I have no error..

**Comment by TM818** [comment]
I'm having the same issue - why was this closed with no answer?
