### ISSUE TITLE
Add showDefinitionForSelection() to WebView

### ISSUE THREAD

**Issue by h13i32maru** [electron/electron#5275]
* Electron version: 0.37.5
* Operating system: MacOSX 10.10.5

----

Hi! Electron team.

I want to use showDefinitionForSelection() in WebView. Now, showDefinitionForSelection() only works in BrowserWindow. Would you please advise me for this.

Ref. https://github.com/electron/electron/pull/938

Thanks.

**Comment by Aluxian** [comment]
Thanks @kevinsawicki!
