### ISSUE TITLE
makeSingleInstance returns true if no app dir in Application Support (MacOS)

### ISSUE THREAD

**Issue by erkyrath** [electron/electron#5277]
* Electron version: 0.37.7
* Operating system: MacOS 10.11.4

Create a directory with the attached `package.json` and `main.js` files. The app just calls `app.makeSingleInstance` (code sample copied from the Electron docs) and then creates an empty window.

[package.json.txt](https://github.com/electron/electron/files/233556/package.json.txt)
[main.js.txt](https://github.com/electron/electron/files/233558/main.js.txt)

Type:

        rm -rf ~/Library/Application\ Support/Electron
        npm start

The app will display

        ### version 0.37.7
        ### shouldQuit:  true

...even though no other instance is running.

If you create an empty ~/Library/Application\ Support/Electron directory, the app runs as expected.

(Obviously, any established Electron developer will have such a directory and will not notice this bug. Their users will notice it very quickly indeed.)

**Comment by erkyrath** [comment]
(To be clear, the app doesn't run at all because it calls app.quit() after printing "### shouldQuit:  true".)

**Comment by erkyrath** [comment]
Bug does not occur with 0.37.6.

**Comment by hoffmabc** [comment]
I am seeing this on Windows 8.1 64-bit with 0.37.7 and 0.37.6

**Comment by erkyrath** [comment]
I have also had a user report this on Windows 7. At least it sounds like the same bug -- newly-installed app did not launch -- and it was fixed by rolling back to 0.37.6. (I didn't have them verify it by creating an empty directory.)

**Comment by IGZangelsanchez** [comment]
Same problem in Ubuntu
