### ISSUE TITLE
will-download is not emitted when URL is HTML pages

### ISSUE THREAD

**Issue by dennyferra** [electron/electron#5278]
* Electron version: 0.37.5
* Operating system: Windows 10

When calling a window's `webContents.downloadURL(URL)` method if the specified URL returns a 404 the `will-download` event on `webContents.session` does not fire and instead a dialog pops up asking the user to save an html file (the contents of the 404 page).

Is this expected behavior and is there any event I can listen to or some other way to get around this? I'd like to handle the error differently if possible.

Thanks

**Comment by zcbenz** [comment]
It seems that the `will-download` event just doesn't fire when the URL is HTML pages.

**Comment by eternalharvest** [comment]
@zcbenz 

I have same issue with electron version 11.1.0.
I want to know how to prevent opening save dialog when the server returns 404 not found.
But I don't know how to check the response status code...

```javascript
mainWindow.webContents.downloadURL('https://example.com/404.html');
```

```javascript
mainWindow.webContents.session.on('will-download', (event, item, webContents) => {
    if (/* check if response status code != 200) */) {
        event.preventDefault();
    }
});
```
