### ISSUE TITLE
Windows app won't run

### ISSUE THREAD

**Issue by mrmayfield** [electron/electron#5279]
* Operating system: Windows 10

Running into all sorts of .dll errors trying to test the Windows binary. MSVCP120.dll, ffmpeg.dll and node.dll just to name a few. How come? Do we really need every user that we want to run the application running custom C++ DLL's (which I think is what those files are).

Thanks

**Comment by MarshallOfSound** [comment]
Where did you get your binary from, those dlls are shipping with the prebuilts

**Comment by mrmayfield** [comment]
Yeah good point I can see those dlls now, I plucked the executable out of the build folder and put it on Github, how can I build that executable with all the dlls included from a Mac?

**Comment by MarshallOfSound** [comment]
You can package the binaries and the dll's into a single installer executable using https://github.com/electron/windows-installer.  You'll need `mono` to get that working on a mac though.

**Comment by mrmayfield** [comment]
Okay perfect, and how about the same thing with Linux? It's a similar situation where there's libraries shipping with the binary.

**Comment by MarshallOfSound** [comment]
Linux users require 3 different styles of packages `rpm`, `deb` and arch linux requires `AUR`.

It sounds like you need something to do all this for you, https://github.com/electron-userland/electron-builder handles building distributable packages for OS X, Win32 and Linux (debian and fedora)

**Comment by zcbenz** [comment]
Thank @MarshallOfSound for answering it! I'm closing this now.

**Comment by mrmayfield** [comment]
Yup thanks a lot @MarshallOfSound , can definitely take it from here to fix the issue.
