### ISSUE TITLE
BrowserWindow Y position is automatically increased after its creation

### ISSUE THREAD

**Issue by a-chris** [electron/electron#5284]
* Electron version: 0.37.7
* Operating system: Ubuntu 15.10 with Unity

After a BrowserWindow is created with an explicit position (x, y) the window is "moving" 28 px to the bottom. The window itself is not actually moved but its y is increased by 28.
I think it could be the height of the Unity top bar but I'm not sure.

On windows 7 it doesn't happen, I can't test in on other linux systems (neither on mac).

Example code -> https://gist.github.com/anonymous/ceeddcda5ea717516cf44a6a8863127c
W,H,X,Y on close should be as defined in mainWindow creation but Y is different.

**Comment by zcbenz** [comment]
On Linux the position of BrowserWindow is just a hint to your desktop environment, in your case Unity decides to take account of the height of top bar when putting the window, and we can not prevent that.
