### ISSUE TITLE
Dock icon is shown in any case for OS X

### ISSUE THREAD

**Issue by z-ax** [electron/electron#5286]
* Electron version: ^0.37.7
* Operating system: OS X 10.11.4

So, the case is we're working on Tray icon app. So, no icons in Dock/Taskbar should appear.
I've checked in all versions of 0.37 and can't actually hide it.

Do you know what may cause the problem?
As we checked, on Windows it's fine.
From `npm start` or built with `"electron-packager": "^7.0.1"` OS X version is still in Dock.

After window creation we do nothing to it's position or size. On Tray icon click it's shown (and position is calculated).

Example:
```
        let mainWindow = new BrowserWindow({
            autoHideMenuBar: true,
            dir: __dirname,
            frame: false,
            fullscreenable: false,
            maximizable: false,
            minimizable: false,
            movable: false,
            resizable: false,
            transparent: isOSX,
            hasShadow: !isOSX,
            icon: appParams.icon.main,
            show: false,
            skipTaskbar: true,
            showDockIcon: false,
            width: 400,
            height: 600,
            webPreferences: {
                defaultEncoding: 'utf-8',
                defaultFontFamily: 'sansSerif',
                webgl: false,
                webaudio: false
            }
        });
```

Thank you in advance for assistance!

**Comment by z-ax** [comment]
I've seen the `showDockIcon` doesn't exist in the latest docs. But I suppose it should work with `skipTaskbar: true`. Is it correct?

**Comment by zcbenz** [comment]
`skipTaskbar` doesn't work on OS X because there is no taskbar on it. You can call `app.dock.hide()` to achieve this, but the correct way is to add `LSUIElement` to Info.plist: http://stackoverflow.com/questions/620841/how-to-hide-the-dock-icon.

**Comment by z-ax** [comment]
So, the `showDockIcon` param is gone forever? Which was the last version which supports it?
Not so good. We need an option to toggle Dock icon if user wants to.
And with app.dock.hide() I see the "glitch" in Dock on launch anyways.
