### ISSUE TITLE
child_process.fork fails silently when using ASAR

### ISSUE THREAD

**Issue by ArekSredzki** [electron/electron#5288]
* Electron version: 0.37.7
* Operating system: OS X 10.11.4

I'm trying to make my application compatible with ASAR before I release it.

Thus far I have been unsuccessful in getting it to work.  I create an additional process using `child_process.fork` from main that is used for long-running CPU-bound tasks. Unfortunately, when using ASAR the ipc channel to the other process isn't opened (I'm not sure if the other process even starts).

Debugging the issue was very painful because the process does not emit an error event (even though the documentation states that it should).

First I attempted to adjust the file path to include the asar extension, similarly to what is shown in #3512

Next I also tried to make use of `asar-unpack` but the effect for the developer is poorly documented.
That paired with the inability to debug led me to abandon the effort.

Any pointers are appreciated.

**Comment by paulcbetts** [comment]
Spawn asks the OS to start a process, and the OS doesn't know anything about ASAR archives. `asar-unpack` is the right idea, but I totally agree that it's super unclear how to use the `--unpack-dirs` command. The easiest way is to just give it the name of a directory you want to guarantee is unpacked

**Comment by ArekSredzki** [comment]
@paulcbetts Thanks for catching that, I 100% meant to say that I'm using `fork`.

**Comment by zcbenz** [comment]
It would be great if you can work out a test case, we have specs testing `child_process.fork` and they don't seem to have problems.

**Comment by ArekSredzki** [comment]
@zcbenz Could you give an example of how one should use it in an `asar` application?

**Comment by zcbenz** [comment]
You should be able to use it just like in normal apps, `child_process.fork` can recognize files in asar archive.

**Comment by ArekSredzki** [comment]
Interesting. So I shouldn't have to use `unpack` or even include `.asar` in the path?

**Comment by zcbenz** [comment]
You can just use it like `child_process.fork('some/path/to/file.asar/dir/script.js');`

**Comment by ArekSredzki** [comment]
@zcbenz Thanks for the help, it turns out that an exception was being thrown just after the process started.

It would be good to include in the docs that one doesn't have to account for the `.asar` in the path if `__dirname` is used inside the same ASAR.
