### ISSUE TITLE
quitAndInstall() installs update, but does not quit and restart.

### ISSUE THREAD

**Issue by dougludlow** [electron/electron#5289]
* Electron version: 0.37.3
* Operating system: OS X 10.11.3

In OS X, I'm seeing an issue where autoUpdater.quitAndInstall() appears to install the update, but does not actually quit and restart the app. When I quit the app manually, the new version is installed. Something appears to cause the quit to hang, but there are no errors logged to indicate what the issue might be.

quitAndInstall works fine for me on Windows, but not on OS X.

**Comment by dougludlow** [comment]
As a workaround, I've got it working, by calling app.quit() after:

```javascript
autoUpdater.quitAndInstall();
app.quit();
```

**Comment by MarshallOfSound** [comment]
Are you listening for `will-quit` and preventing it in any cases?

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by gralance** [comment]
The workaround is helpful !

**Comment by johnryan** [comment]
Did anyone get to the bottom of why this workaround is needed? I just started seeing the same issue. The install happens if I manually quit but not after calling `quitAndInstall()`

**Comment by dougludlow** [comment]
@johnryan I don't think so. Even slack did this for a while. May even still...
