### ISSUE TITLE
How toremove menu bar in electron app

### ISSUE THREAD

**Issue by RamakantVerma** [electron/electron#5292]
By default we  are a getting an menu bar and Tittle bar in the electron desktop application .
I want to remove only the menu from my desktop application.
Setting  **frame: false** will make frame less and you will loose the Tittle bar also(with title , max ,min button) 
**menubar :false**  is not working
I want to **remove only menu bar and not the Tittle bar** .
Is there any way to achieve this??.

**Comment by martinstarman** [comment]
```mainWindow.setMenu(null)```

**Comment by zcbenz** [comment]
Thank @martinstarman for answering this.
