### ISSUE TITLE
vm.runInDebugContext('PropertyKind') fails (works in node.js 5.10.0)

### ISSUE THREAD

**Issue by bpasero** [electron/electron#5295]
* Electron version: 0.37.5
* Operating system: Mac OS X 10.11

For our VS Code debugger we rely on the following call to succeed in node.js 5.x:

`vm.runInDebugContext('PropertyKind')`

When I run this code in node.js 5.10.0 it works, but it fails when run from Electron:

![image](https://cloud.githubusercontent.com/assets/900690/14815474/dca698e0-0bab-11e6-80ce-23e7ccad2a3e.png)

Any ideas why this could fail in Electron and work in node.js?

**Comment by zcbenz** [comment]
It seems like a change caused by upgrade of V8 4.9, in Node v6 you can get the same result. You probably need to detect `process.versions.v8` in VS Code to fix this, the V8 version in Node does not always match Chromium's one, since they have different release plans.

**Comment by bpasero** [comment]
All right, that explains it.
