### ISSUE TITLE
Notification icon is not fetched correctly

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#5296]
* Electron version: `0.37.7`
* Operating system: Windows 10 x64

When creating a large quantity of notifications with different images (no set amount at this point but it seems to be a variable amount > 20) the image defaults to the applications icon.  Could there be some kind of cache naming collision going on?

**Comment by blainesch** [comment]
What are you using to create notifications?

**Comment by MarshallOfSound** [comment]
The standard [HTML5 Notification API](https://developer.mozilla.org/en/docs/Web/API/notification)

I.e.

```js
new Notication("title", { icon: "url-to-icon" });
```

**Comment by zcbenz** [comment]
It is probably because the requests to the icon failed because of server's throttling or anti-crawl policy. Following code fetches a different icon every second and it seems to work for me:

```js
let i = 1;
let n = null;
setInterval(function () { 
  if (n)
    n.close();
  n = new Notification("title", { icon: `https://unsplash.it/100/?random&i=${i}` });
  i++;
}, 1000);
```

**Comment by MarshallOfSound** [comment]
@zcbenz I shall attempt to track down the root cause as it could be as you say a servers throttling policy.  The reason I think it is an issue with electron is that my desktop notification polyfill code for windows 7 (Makes an actual desktop notification instead of an annoying bubble popup thing :+1: ) doesn't experience this issue at all/

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/inject/win32/polyfill_Notification.js

And all that code does is fetch the image for each notification.

I'll try figure out what's going on :+1:

**Comment by MarshallOfSound** [comment]
I'm going to close this as I can't replicate it any more :cry:

**Comment by MarshallOfSound** [comment]
Reopening as it just happened again (and is happening right now).

@zcbenz Is there anything I can do to test it, I don't have access to dev tools on the instance that is currently running (WIndows 10 x64).

I do however have access to the icon URL it is trying to fetch

https://lh3.googleusercontent.com/Xy6i86mFRPWqqVXY-UmrkG7mclfZfICf9IDlq-NpGBHwPDwc6siv3qKUAgifc_mbgV-M62eaBA=s90-c-e100

As you can see that URL works correctly

**Comment by blainesch** [comment]
I downloaded the image 100+ times and didn't get timed out.

Maybe the internal notification api doesn't like that there isn't an extension in the file name?

**Comment by MarshallOfSound** [comment]
@blainesch I can't reproduce through any sequence of steps, it kind of just happens after a while :cry: 

It works for a few hours (correctly fetches images), and then just suddenly stops working.

**Comment by zcbenz** [comment]
The only difference between Windows and other platforms' notification implementation is, on Windows we would first save the icon to filesystem and then pass a `file://` URL to system API. So probably something weird happened in `NotificationPresenterWin::SaveIconToFilesystem`, but I can't see how:
https://github.com/electron/brightray/blob/master/browser/win/notification_presenter_win.cc#L56

**Comment by MarshallOfSound** [comment]
@zcbenz this is still happening randomly.  Could it be some kind of caching issue.  I can see the files are downloaded to a temp directory, are they downloaded every time if it has downloaded the image before?

**Comment by zcbenz** [comment]
@MarshallOfSound The files are cached according to their URL's MD5 checksum, do different images have same URLs in your app?

**Comment by MarshallOfSound** [comment]
@zcbenz They shouldn't.  Is it at all possible that a windows service is cleaning out the temp directory at certain intervals and therefore Electron thinks the image is cached when in fact it has been cleared?

**Comment by zcbenz** [comment]
The code checks the existence of the cache file, so it shouldn't be the cause. Can you probably try logging all URLs of the notification icons? We can also try to reproduce with the logged URLs.

**Comment by MarshallOfSound** [comment]
@zcbenz Yup, I'll leave it running with this code overnight and see if it's doing it in the morning.

```js
class LoggingNotification extends Notification {
  constructor(title, opts) {
    super(title, opts);
    console.log(opts.icon);
    fetch(opts.icon).then(() => console.log('success')).catch(() => console.log('failed'));
  }
}

window.Notification = LoggingNotification;
```

**Comment by MarshallOfSound** [comment]
OK, so interestingly while I was back in NZ this issue never occurs but it occurs reasonably frequently mac at University so I'm thinking there is some kind of network issue.

However, I noticed today that when running Franz the notification icon also glitched out and reverted to Franz's icon instead of profile pictures of the users messaging me.

Somehow all Electron based apps on my machine simultaneously decided to fail to fetch notification icons. 😕

**Comment by kevinsawicki** [comment]
>  so I'm thinking there is some kind of network issue.

@MarshallOfSound do you think this should be closed out or still left open?

**Comment by MarshallOfSound** [comment]
None of my users have reported it so it appears to be localized to just me, maybe it's run time, maybe it's the network.  Whatever it is it's system specific (mine only) so I'n happy closing it out 👍

**Comment by theuniverse** [comment]
@zcbenz I am facing similar problem on Windows 7, and Electron 1.6.10.
