### ISSUE TITLE
WebContents goBack with only hash changes not triggering did-navigate-in-page

### ISSUE THREAD

**Issue by wenkaili** [electron/electron#5304]
* Electron version: 0.37.6
* Operating system: Windows 10

I'm seeing an issue where sometimes when I call webContents.goBack to a previous page that only had hash changes, the webContents trigger a "did-navigate" event instead of a  "did-navigate-in-page" event. Since I'm running an angular web app, this is causing the web contents to do a full reload (instead of just updating some portions of the UI). 

I'm seeing this happen when I've navigated to a page with embedded iframe, and attempted to go back. If I'm on a page without iframes and I trigger webContents.goBack, then it works correctly.

Here's the general repro steps:
- Navigate to a page with iframe inside
- Trigger webContents.goBack()
- Notice the web app does a full reload while navigating back to previous page

**Comment by zcbenz** [comment]
I tried to navigate in a page with iframe, but I can not reproduce this, can you provide a minimal example for this?

**Comment by zcbenz** [comment]
Closing until more information is provided.
