### ISSUE TITLE
appenSwitch js-flags with --max_old_space_size doesn't increase the memory limit

### ISSUE THREAD

**Issue by mcaballeropinto** [electron/electron#5305]
* Electron version: 0.34.1
* Operating system: Windows

Hi there!

I am trying to increase the memory cap a bit on my Electron app. I have this code on my main process before ready event handler:

`app.commandLine.appendSwitch("js-flags", "--max_old_space_size=2000");`

AFAIK, this should increase the memory cap to 2000mb (I can't go any higher number BTW, otherwise Electron crashes at start) on my renderer process. However, I see that my renderer process still crashes when reaching around 1,4GB memory.

Is this expected? Is there another way to do this?

Thank you very much for your time!

**Comment by zcbenz** [comment]
Setting `max_old_space_size` to 2000 doesn't necessarily mean you can use memory up to 2000mb, allocating memories generates fragments so the memory you can use is usually much less than the upper limit.

But I am not an expert on V8, I suggest seeking help from the v8-users mailing list.
