### ISSUE TITLE
NSAllowsArbitraryLoads

### ISSUE THREAD

**Issue by bryan-jowers** [electron/electron#5307]
Is it needed to addNSAllowsArbitraryLoads key to plist so that insecure (non-ssl) content can be rendered in Electron apps? Is there a better way to do this than manually alter the plist file after electron-packager creates the app?

**Comment by zcbenz** [comment]
Usually you don't need `NSAllowsArbitraryLoads` since Chromium's network stack is independent from Cocoa, but you probably will need it if you use `autoUpdater` to update from unsafe locations.

I think the best way to add it is to add an option in `electron-packager `.

**Comment by bryan-jowers** [comment]
@zcbenz 
Are you aware of any reason why insecure content loaded over secure connection would prevent the content from being rendered in Electron? On web Chrome, I see the content as expected, with the console warning: 

> 
Mixed Content: The page at 'https://applicationURL.com/' was loaded over HTTPS, but requested an insecure image 'http://sfist.com/assets_c/2016/03/ttc_w-01-penrose-366-02_0-thumb-640xauto-937835.jpg'. This content should also be served over HTTPS.

What I am experiencing: 

My Electron app loads a web site. There can be insecure content in the website. Any non-ssl image is blocked by electron. But it is loaded in web.

**Comment by zcbenz** [comment]
That was the security policy of Chromium, you can turn it off by setting the `webSecurity` option of `webPreferences.`
