### ISSUE TITLE
Dragging in webView causes CoreDragCreate error

### ISSUE THREAD

**Issue by nickaversano** [electron/electron#5308]
* Electron version: v0.37.7
* Operating system: Mac 10.9.5

HTML5 drag and drop events don't work. Dragging in the webView or the devtools causes Electron[27385:507] CoreDragCreate error: -4960 and CoreDragDispose: -1850. Using the following code: [from mozilla](https://developer.mozilla.org/en-US/docs/Web/Events/dragstart#Example：dropzone).

Any advice on how to fix this? Or are drag events not supported in Electron?

**Comment by zcbenz** [comment]
We have problems with dragging in webview, I'm merging this to #2897.
