### ISSUE TITLE
Make downloads icon in dock bounce

### ISSUE THREAD

**Issue by herrmannplatz** [electron/electron#5309]
* Electron version: 0.37.3
* Operating system: OSX

To give better feedback when a file was download, i would like to make the downloads icon bounce in the dock. ASAIK this should be doable with the given API on OSX. Is this something you people would like to see in electron and what would be the best place in the electron API?

**Comment by MarshallOfSound** [comment]
This is something you should probably (and can quite easily) handle yourself.

Simply hook into the [`will-download`](https://github.com/electron/electron/blob/master/docs/api/session.md#event-will-download) event on a session object.  Then listen for the [`done` event](https://github.com/electron/electron/blob/master/docs/api/download-item.md#event-done) on the DownloadItem.  When that done event is fired you can manually call the [bounce method](https://github.com/electron/electron/blob/master/docs/api/app.md#appdockbouncetype-os-x)

Untested example code:  
```js
win.webContents.session.on('will-download', function(event, item) {
  item.on('done', function(e, state) {
    if (state === 'completed') {
      app.dock.bounce();
    }
  });
});
```

**Comment by herrmannplatz** [comment]
Sorry was tack about the Downloads stack. Guess thats the correct term.

**Comment by MarshallOfSound** [comment]
Ahh, I agree that that should / can be part of the Electron API.  It should be as simple as firing off something like this.

```mm
[[NSDistributedNotificationCenter defaultCenter]
        postNotificationName:@"com.apple.DownloadFileFinished"
        object:filePath];
```

Possibly put the API somewhere like  
```js
app.dock.downloadComplete(filePath);
```

If someone from electron can confirm that this is acceptable I can give it a go

**Comment by zcbenz** [comment]
I think adding  an `app.dock.downloadComplete` API is enough, many developers are using the download operation silently so it may not be a good idea to make this default behavior.

**Comment by danhp** [comment]
I got this implemented, but I can't seem to put in a pull request as Github is giving a 500 error.

**Comment by zcbenz** [comment]
@danhp There was a bug of GitHub itself preventing creating pull requests yesterday, the website should work now.
