### ISSUE TITLE
Windows notification application name

### ISSUE THREAD

**Issue by philipgiuliani** [electron/electron#5313]
![1efb5326-0c5a-11e6-973a-a7904181b723](https://cloud.githubusercontent.com/assets/5446019/14854967/188f923a-0c92-11e6-8592-0ab949416ed8.png)

The Windows 10 Notification center shows me `com.squirrel.youtv.YouTV-Downloader` but i would like to just have the app's name there. Is there a way to customize this?

```javascript
new Notification("Download abgeschlossen", {
    body: `${download.title} wurde erfolgreich heruntergeladen`
});
```

See: https://github.com/electron-userland/electron-builder/issues/362

* Electron version: v0.37.7
* Operating system: Windows 10 x64

**Comment by felixrieseberg** [comment]
To get a name for the notification center, Windows 10 first checks for a corresponding shortcut in the start menu (anywhere there, it doesn't need to be pinned). If it finds a shortcut with the same AppUserModelId, it'll use the shortcut's name. If it doesn't, it'll use the AppUserModelId.

Can you confirm that Squirrel set a shortcut somewhere in `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`?

**Comment by zcbenz** [comment]
Closing until more information is provided.
