### ISSUE TITLE
Arch Linux dependency issue

### ISSUE THREAD

**Issue by shesmu** [electron/electron#5318]
* Electron version:v.0.37.7
* Operating system: Linux: distro: Arch
After installing electron on arch i got the error. /usr/lib/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory. This can be fixed by installing gconf.( sudo pacman -Su gconf). A fix for this is not urgent i just wanted to post this here for anybody with the same issue.

**Comment by zcbenz** [comment]
Usually this is solved by adding a dependency for app packagers, however it is impossible to solve this with npm module since npm doesn't handle native dependencies.
