### ISSUE TITLE
Mac OS X: How do you handle migrating the app if you need to change the Bundle Identifier?

### ISSUE THREAD

**Issue by eugirdor** [electron/electron#5321]
I recently updated [electron-packager](https://github.com/electron-userland/electron-packager) from 5.2.1 to 7.0.1.  Part of the changes that came with that upgrade was a change in how the default Bundle Identifier was generated [Platform: Mac App Store support #233](https://github.com/electron-userland/electron-packager/pull/223). That ended up causing me a pretty painful breaking change as my app had a space in the name which would get normalized to an underscore (_) in 5.2.1 but a dash (-) in 7.0.1.  That in turn broke auto-updating because the new app's Bundle Identifier no longer matched.

The new version of electron-packager has the correct implementation, the Bundle Identifier should never have had an underscore in it, as that is not a valid character according to the spec, but I already have versions of the app distributed with it.  Right now, I do not know how I would be able to gracefully handle the Bundle Identifier changing.

**Comment by zcbenz** [comment]
Sorry but I don't think autoUpdater would be able to handle this.
