### ISSUE TITLE
net.connect hangs on windows

### ISSUE THREAD

**Issue by MarcoPolo** [electron/electron#5324]
* Electron version: 0.37
* Operating system: Windows

### Problem
Calling `net.connect` in windows on a named pipe will hang indefinetely.
Unless you do:
```
var fake = net.connect({})
fake.on('error', function () {})
```

after calling `net.connect`. If you do that hack, net.connect will work successfully.

### Repro
Minimal repo here: https://github.com/MarcoPolo/electron-quick-start/tree/net-fail-windows
Includes small go server to setup named pipe.

**Comment by zcbenz** [comment]
Thanks for the repro and the hack, it helps greatly on solving this.

**Comment by zcbenz** [comment]
Unable to reproduce with v1.1.2 anymore.

**Comment by jorisvddonk** [comment]
This issue can unfortunately be reproduced again under Electron 1.4.4 and 1.6.3, and the following versions of Windows: Windows 10 Pro Insider Preview, version 1607 build 15048.0; Windows 10 Pro, version 1607 build 14393.693; Windows 8.1 Pro. Other versions of Electron and Windows were not tested by me.

To reproduce, see https://github.com/jorisvddonk/electron-named-pipe-connect-issue, or use MarcoPolo's repo mentioned above.

**Comment by jorisvddonk** [comment]
I have also been able to reproduce this issue (using https://github.com/jorisvddonk/electron-named-pipe-connect-issue) on Electron 1.1.2 and 1.3.1 on Windows 10 Pro Insider Preview, version 1607 build 15048.0.

Using MarcoPolo's repository, I've also been able to successfully reproduce the issue on Electron 1.1.2, but haven't tried any other Electron versions yet.

**Comment by jorisvddonk** [comment]
@zcbenz given the above, can this issue be reopened or should I post a new issue?
