### ISSUE TITLE
Preload CSS for webview

### ISSUE THREAD

**Issue by Sjael** [electron/electron#5325]
I'd find it really convenient if all pages that a `webview` visits could be preloaded with a specified CSS file via a `preloadcss` attribute. That way I don't need to use `.InsertCSS()` everytime a user navigates to a new page. 

Could this be a future Electron enhancement?

**Comment by zcbenz** [comment]
You can load the CSS in the preload script, it is a more general solution then adding a new option.

**Comment by MJRomka** [comment]
Can I attach internal (hosted in the app) CSS via preload JS?

**Comment by vanowm** [comment]
> 
> 
> You can load the CSS in the preload script, it is a more general solution then adding a new option.

Any examples how to do it?
I currently have this setup:
**index.html**:
```
<webview src="https://google.com/" nodeintegration plugins autosize preload="bridge.js"></webview>
<script src="app.js"></script>
```

**bridge.js**
`import "bridge.css"`

**app.js**
`import "app.css"`

It fails with `Unable to load preload script: bridge.js` error

however app.css applies just fine.
