### ISSUE TITLE
Opening a file should open a new window if no window present on current Ubuntu workspace

### ISSUE THREAD

**Issue by dragly** [electron/electron#5327]
On Ubuntu, when opening a file from the file manager in Atom, it will first open a new window on the current workspace (A). Opening a second file opens in the same window in a new tab. This is expected.

After changing to a different workspace (B) in Ubuntu where no Atom window is present and then opening another file, the file will open in the Atom window present on the first workspace (A). However, the expected behavior is that the file is opened in a new window of Atom.

This has already been reported to Atom, but I was asked to post it here as an enhancement suggestion as it would likely require API changes to Electron for Atom to implement this behavior.

The original issue is located here:
https://github.com/atom/atom/issues/11610

### Steps to Reproduce

1. Open a file in Atom from the file manager in Ubuntu on workspace (A).
2. Change workspace to workspace (B).
3. Open a second file in Atom from the file manager.

**Expected behavior:** Two Atom windows open, one on workspace (A) with the first file and one on workspace (B) with the second file.

**Actual behavior:** One Atom window opened on workspace (A) with both files.

* Electron version:
Electron: 0.36.8
* Operating system:
Ubuntu 15.10 and Ubuntu 16.04 running Unity 7.

**Comment by zcbenz** [comment]
Currently Electron doesn't have the ability to move windows between screens and workspaces, I'm merging this to #1836.

**Comment by dragly** [comment]
@zcbenz Sorry if I was a bit unclear in my description. This is issue not about moving windows between screens and workspaces, but detecting if there is a window present on the current workspace.

To summarize: If there is a window present on the current workspace, the file should open in that. Otherwise, a new window should open. No windows should be moved.

I therefore don't believe this should be merged with #1836.

**Comment by zcbenz** [comment]
@dragly Currently Electron creates the window and let the Desktop Environment decides where to put it, I think the DE just decided to put the new window in the same workspace with other windows of the same program. If we want be able to show the new window in current workspace, we have to move it.

**Comment by dragly** [comment]
@zcbenz Moving the window would not solve the problem. That would still cause both file 1 and file 2 to be open in the same window, which is not wanted/expected. It is expected to have a window with file 1 on workspace A and a window with file 2 on workspace B.

I have a attached a drawing drawing that might clarify this:

![open-window-if-none-exists-on-workspace](https://cloud.githubusercontent.com/assets/220658/14936670/e05363f2-0ef2-11e6-815a-8e1b4d78f973.png)

As shown in this drawing, going from the actual behavior to the expected behavior cannot be done by moving the window. However, a new window needs to be opened on workspace B.

For the record, the expected behavior can be achieved today from terminal by some manual work by the user:

- The user opens file 1 on workspace A
- The user changes to workspace B
- The user checks if there is an existing window on the current workspace (B) (in the drawing above, the answer would be "no")
- If yes, the user opens file 2 by using the command
```
atom file2
```
- If no, the user opens the file by using the command
```
atom --new-window file2
```

What I would like to see is that this process is automated. In other words, that Atom/Electron automatically checks if a window exists on the current workspace and performs the same operation as "--new-window" does if there is no window on the current workspace.

**Comment by zcbenz** [comment]
Thanks for the explanation, I have created a new issue of necessary APIs for implementing the correct behavior in Atom: https://github.com/electron/electron/issues/5362.
