### ISSUE TITLE
Native module can not modify content of Buffer in renderer process

### ISSUE THREAD

**Issue by csy2002** [electron/electron#5329]
- Electron version:v0.36.12
- Operating system:windows

can i share buffer object between javascript and native addon that write by c++?
try belowing, but failed;

c++ addon：
void setBuffer(const v8::FunctionCallbackInfov8::Value& args) {
    Isolate\* isolate = args.GetIsolate();
    char\* jsBuffer = node::Buffer::Data(Local<Object>::Cast(args[0]));
    memcpy(jsBuffer, "bbbbbbbbbb", 10);
    printf("native addon output:%s\n", jsBuffer);
}

javascript:
var native = require('nativeAddon');
var globalBuffer = new Buffer(20).fill('a');
native.setBuffer(globalBuffer); //set globalBuffer to 'bbbbbb....', using memcpy
console.log("js output:" + globalBuffer);
//////////////////////////////////////////
result:
native addon output: bbbbbbbbbbaaaaaaaaaaaaaaaa
js output: aaaaaaaaaaaaaaaaaaaaaaaaaa

////////////////////////////////////////
but, globalBuffer not change, why?

**Comment by csy2002** [comment]
when the javascript code run in main.js, i can get the right result;
but, the javascript code run in other BrowserWindow, I can't get the right result;
why？thanks

**Comment by codebytere** [comment]
closing due to abandonment.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (113/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:13653)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-96d6-jcjackson=joe-jackson.net@sgmail.github.com>)
	id 1dx1QR-0017qo-Ds
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:46:14 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=E34YDwP5cyTf2le24Hcw+Udxd7I=; b=aNAodTaFSTRb7gKj
	vK6aywKK2+q0r82xA5gL/aLaESM9p0+RxS9wqIFK7iLWz7ZhgESR/98U/9XryRtB
	moSkD05AI3aKFxhv+ZVkbkUVuGrGsHzO286sJ+VvkjAizXEs8ZHKJij816l+QVar
	JOC+GXBbtVwS4KqjjaKvOUa+kqE=
Received: by filter1075p1mdw1.sendgrid.net with SMTP id filter1075p1mdw1-4663-59CB02B5-1
        2017-09-27 01:45:25.061733662 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0009p1iad2.sendgrid.net (SG) with ESMTP id ZAiREYviRFOT9IvBtKq-DA
	for <jcjackson@joe-jackson.net>; Wed, 27 Sep 2017 01:45:25.094 +0000 (UTC)
Date: Wed, 27 Sep 2017 01:45:25 +0000 (UTC)

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (114/100 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:43423 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dx1QU-0017s0-6L
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:46:17 -0500
Date: Tue, 26 Sep 2017 18:45:27 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1506476727;
	bh=TWP1UHlbPGHbr9bMOR8O/jYswLfsqYoJl4EJ3On6X+Y=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=AtjMQfmoWfY645YvLNtB1x+GGEMTMJK0g0ChKyE/wPEwl4o2Vy+XXUO8YX6ckLBm7
	 szZUOWyiD8QDxs3J4AmYlpNITdeEpgl9XyLRYNUwURoLROYINn0RrS8PtLuciaWFpm
	 PoH6ukZLZQKhaTr1mzwB6388cvwb2pyKHANHfdIY=
