### ISSUE TITLE
Is atom-shell intended to be compatible with prebuilt node modules?

### ISSUE THREAD

**Issue by yhahn** [electron/electron#533]
@zcbenz would appreciate your thoughts.
### Background

@springmeyer + other contributors have been working on [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) which **lets native node modules be installed from prebuilt, static binaries** without dependencies/compiling. These binaries target specific architectures and node abi versions (example url for such a binary: http://node-mapnik.s3.amazonaws.com/v1.4.10/mapnik-v1.4.10-node-v14-darwin-x64.tar.gz)
### Can atom-shell use node-pre-gyp compiled static binaries?

In practice so far seems the answer is yes. However we have some questions that it would be great to get an answer to:
- **Differences in the headers** between node v0.11.13 (http://nodejs.org/dist/v0.11.13/node-v0.11.13.tar.gz) and what modules are meant to be built against for atom-shell (https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.11.13/node-v0.11.13.tar.gz). They don't appear to be substantive enough to cause prebuilt binaries problems currently. **Is the intention of atom-shell to continue to deviate as little/not at all from node core if possible?**
- **The atom-shell x64 executable has process.arch='ia32'** but appears to be capable of requiring static x64 binaries. Can you clarify how this happens and whether we should expect atom-shell to remain on ia32 or switch to x64 at some point?

To be very concrete, depending on the answers:
### Yes, atom-shell is meant to be node v0.11 compatible
- We may start using node-pre-gyp v0.11 prebuilt static binaries with atom-shell,
- We may ignore the `process.arch=ia32` in atom-shell OR build static binaries for ia32 in more node-pre-gyp modules,
### No, atom-shell is its own thing
- (long shot) we may look into atom-shell-specific static binaries built against the atom-shell headers in node-pre-gyp modules,
- (more realistic) look at alternatives to atom-shell.

**Comment by stefanKuijers** [comment]
Updated link that zbencz posted in his first reply: https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md
