### ISSUE TITLE
[Asar] Limitations on Node API: spawn a child

### ISSUE THREAD

**Issue by Graphfx** [electron/electron#5330]
----------
* **Electron version**: v0.37.7
* **Operating system**: Mac OS (El Capitan v10.11.1) & Windows 10

----------
Hello,

I’m currently developing an electron app that has, at some point, to convert an HTML file into a PDF file. For this purpose, I use the native node module `html-pdf` which is based on `phantomjs`. 

It works well when the application is not packed but when it is under _asar_, there is an _uncaught exception_ because `html-pdf` cannot spawn a child process. 

**The stack error**
```bash
internal/child_process.js:302 Uncaught Error: spawn ENOTDIR

exports._errnoException @ util.js:890
ChildProcess.spawn @ internal/child_process.js:302
exports.spawn @ child_process.js:379
PdfExec @ /Users/graphfx/html2pdf/html2pdf.asar/node_modules/html-pdf/lib/…:87
PdfToFile @ /Users/graphfx/html2pdf/html2pdf.asar/node_modules/html-pdf/lib/…:83
convert @ index.html:35
onclick @ index.html:19
```

I suppose that is due to the _asar_ [Limitations on Node API](http://electron.atom.io/docs/v0.27.0/tutorial/application-packaging/#limitations-on-node-api) but I really need to pack my app in _asar_ due to the _260 character path length limit_ on Windows.

I have also tried using the option  `--unpack-dir 'node_modules'` when building the _asar_ package but the problem persists.

**Reproduce the error**

```bash
git clone https://github.com/Graphfx/html2pdf
cd html2pdf
npm install
npm run asar-pack
npm run start-asar
```

----------
Does someone know how solve this problem?

Thank you very much,
:evergreen_tree: Graphfx

**Comment by MarshallOfSound** [comment]
@Graphfx Just as a side point to the windows 260 character issue.  If you use `NPM 3.x+` when packaging your electron application (specifically when you call `npm install`) the dependency structure is flattened so you don't hit the limit :+1:

**Comment by zcbenz** [comment]
I think it is probably the module is using `cwd` option when spawning a child, I'm afraid the only solution is to patch the module, or see if the module provides options to avoid that.

**Comment by riona2** [comment]
I think u all also have to try this Long Path Tool for the solution of this issue because I also tried this and it really works

**Comment by sffc** [comment]
@Graphfx Did you find a workaround for this issue?  Changing the `cwd` option in spawn didn't work.
