### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by tejohnso** [electron/electron#5333]
Is there a schedule or typical plan for following chromium updates?  I'm wondering when we'll be moving up to Chrome 50.

**Comment by sbruchmann** [comment]
[/docs/faq/electron-faq.md#when-will-electron-upgrade-to-latest-chrome](https://github.com/electron/electron/blob/master/docs/faq/electron-faq.md#when-will-electron-upgrade-to-latest-chrome)

**Comment by MarshallOfSound** [comment]
https://github.com/electron/electron/pull/5322

**Comment by tejohnso** [comment]
Thanks guys - closing.
