### ISSUE TITLE
autoUpdater.checkForUpdates() Crashing on Windows 10

### ISSUE THREAD

**Issue by eugirdor** [electron/electron#5337]
* Electron version: 0.37.6-0.37.7
* Operating system: Windows 10

I'm running into an issue where after calling `autoUpdater.checkForUpdates()` on Windows 10, the application crashes.  Checking the `SquirrelSetup.log` does list any errors the last line is just `{timestamp}> FileDownloader: Downloading url: ...`

Tested on Windows 7 and Windows 8 and both are working fine.  Additionally, if right-click the .exe and set the Compatibility mode to Windows 7, it will work (no crash).

No errors are thrown on the Javascript side.  Neither `try/catch`, `autoUpdater.on('error', ...)` nor `.on('uncaughtException', ...)` ever fires.  The process just exits.

I'm not sure if there's a better crash log generated somewhere that I can capture.

I even tried removing the `RELEASES` file from the server to see if it would stop it from crashing.  Only change in behavior is that it logs the 404 before crashing.

**Comment by eugirdor** [comment]
If it is relevant, this was a 32-bit build that was running on a 64-bit version of Windows 10.

**Comment by MarshallOfSound** [comment]
@eugirdor I can't replicate this issue on my end.  What update server implementation are you using?

**Comment by eugirdor** [comment]
It's just static files on S3 for Windows.

**Comment by zcbenz** [comment]
`autoUpdater.checkForUpdates` just spawns some child processes I don't see why it would crash. For crash did you mean the app quits immediately?

**Comment by eugirdor** [comment]
Yeah, it quits immediately.

**Comment by zcbenz** [comment]
Is it related to the URL? What will happen it you call `setFeedURL` with some random URL?

**Comment by eugirdor** [comment]
Whether the URL was accessible or not didn't not seem to matter.

**Comment by zcbenz** [comment]
Can you try if executing following code crashes?

```js
let updateURL = 'http://some.where'
let updateExe = require('path').resolve(process.execPath, '..', '..', 'Updater.exe')
require('remote').require('child_process').spawn(updateExe, ['--download', updateURL], { detached: false })
```

**Comment by eugirdor** [comment]
@zcbenz I had to make a few tweaks to the code.  Since I'm running this from the main process, I removed the `require('remote')` part.  And I changed `Updater.exe` to `Update.exe`.  It did still crash.  Can you think of any way I might be able to get some kind of log or indication of why the process is exiting?

**Comment by MarshallOfSound** [comment]
@eugirdor Just a quick thing, have you tested to ensure that `Updater.exe` file exists.

E.g.

```js
console.log(require('fs').existsSync(require('path').resolve(process.execPath, '..', '..', 'Updater.exe')));
```

**Comment by eugirdor** [comment]
@MarshallOfSound `Updater.exe` does not, it's named `Update.exe` for me.

**Comment by MarshallOfSound** [comment]
My bad, I just copy pasted @zcbenz sample :+1: :laughing: 

But that `Update.exe` exists?

Do you have some form of a proxy or VPN?

**Comment by eugirdor** [comment]
Yeah, it exists.  No proxy or VPN in this case.  The update check itself seems to complete successful, but the process exits right after.  Taking out the check and it no longer exits.

Without any kind of error code, it's really hard to tell what's going on.  I tried attaching the Visual Studio debugger, and did see it say something about a corrupted heap, but I could not really make much sense about where the issue was or if it is related.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem? It is weird that the process just exits after spawning a child process, I tried to reproduce with the quick start app but got no luck, I'm wondering whether it is other parts of your app's code caused this.

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by damianobarbati** [comment]
@zcbenz I'm having crashes on Win10 when uploading :(

https://github.com/electron-userland/electron-builder/issues/2970
