### ISSUE TITLE
Building on OpenPandora?

### ISSUE THREAD

**Issue by Silent-Hunter** [electron/electron#5338]
* Electron version: 0.37.7
* Operating system: Ångstrom Linux on OpenPandora

I'm attempting to build Electron on my OpenPandora so I can use Discord, but it doesn't want to checkout all the dependencies.

This happens instead: `Cloning into 'vendor/requests'...
remote: Counting objects: 17315, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 17315 (delta 2), reused 0 (delta 0), pack-reused 17289
Receiving objects: 100% (17315/17315), 6.87 MiB | 491.00 KiB/s, done.
Resolving deltas: 100% (10216/10216), done.
Checking connectivity... done.
Submodule path 'vendor/requests': checked out 'e4d59bedfd3c7f4f254f4f5d036587bcd8152458'
Failed to recurse into submodule path 'vendor/breakpad'
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 212, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 39, in main
    update_submodules()
  File "./script/bootstrap.py", line 95, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "/home/silent/electron/script/lib/util.py", line 176, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status`

The device is ARM architecture, but I'm not sure that has anything to do with this. Also I'm not crosscompiling, I'm attempting to do this directly on the OpenPandora itself.

https://pyra-handheld.com/boards/pages/pandora/ is more about what the device is. If Electron won't work on this that's OK, but I'd like to know as I've spent the past day trying.

**Comment by zcbenz** [comment]
Currently Electron only supports building on x64 machines, to build for other targets you have to do cross compilation.

Also we don't have good support for building for arbitrary Linux platforms, it is blocked by #3310.
