### ISSUE TITLE
maybe update to Node@6?

### ISSUE THREAD

**Issue by ss4xxi** [electron/electron#5341]
Node.js@6 supports ECMAScript2015 > 95%  [proof](http://node.green)

**Comment by zcbenz** [comment]
It had been explained in our FAQ:
http://electron.atom.io/docs/v0.37.7/faq/electron-faq/#when-will-electron-upgrade-to-latest-nodejs

**Comment by arlair** [comment]
Now here: http://electron.atom.io/docs/faq/#when-will-electron-upgrade-to-latest-nodejs
