### ISSUE TITLE
getting error while setting up electron

### ISSUE THREAD

**Issue by anantwaykar** [electron/electron#5342]
I am trying to install electron but I got error.
I am just a starter of node js so I don't have much knowledge of it. Can anybody help me on that to solved this error.
I am attachecing the log file for review.
[npm-debug.txt](https://github.com/electron/electron/files/242810/npm-debug.txt)

Thanks
Anant Waykar

**Comment by MarshallOfSound** [comment]
It looks like you are trying to **build** electron not **install** it.

To get started quickly with electron take a look at the starter application https://github.com/electron/electron-quick-start
