### ISSUE TITLE
OS X auto-updater error messages contain undesired elements

### ISSUE THREAD

**Issue by ArekSredzki** [electron/electron#5343]
* Electron version: 0.37.8
* Operating system: OS X 10.11.4

The error messages emitted to `autoUpdater.on('error', cb)` contain undesired elements.

Example:
`The Internet connection appears to be offline.: (null)`

The error comes from [here](https://github.com/electron/electron/blob/master/atom/browser/auto_updater_mac.mm#L92-L96)

There should be a check to ensure a `error.localizedFailureReason` actually exists, otherwise the complete message has `: (null)` appended to it.

**Comment by zcbenz** [comment]
Fixed with #5371.
