### ISSUE TITLE
Make the default app more useful

### ISSUE THREAD

**Issue by zeke** [electron/electron#5345]
This is a followup to https://github.com/electron/electron/pull/5300, which updated the styles of the default app.

> I think it's kind of weird that this screen exists. Encouraging users to drag and drop things is not exemplary of how people familiar with electron actually use it.

Here's what it looks like today:

![screen shot 2016-04-29 at 12 57 15 pm](https://cloud.githubusercontent.com/assets/2289/14927962/ea69a480-0e09-11e6-8108-245234295f07.png)

Here are a few things we could do:
- [ ] Remove the stuff about dragging, instead telling users how to set up a repeatable automated workflow.
- [ ] Mention and link to [electron-prebuilt](https://github.com/electron-userland/electron-prebuilt) because it's what most people actually use.
- [ ] Mention Electron's `--interactive` flag which provides a Node.js-style REPL.
- [ ] Link to the [electron-quick-start](https://github.com/electron/electron-quick-start) repo  instead of (or in addition to) the [quick-start doc](https://github.com/electron/electron/blob/v0.37.7/docs/tutorial/quick-start.md).
- [ ] Link to the demo app?
- [ ] What else?

@kevinsawicki @jlord

**Comment by bengotow** [comment]
I think we should consider a note about adding a `Content-Security-Policy` meta tag to your app, or some other link to a security overview.

**Comment by zeke** [comment]
@codebytere asked if this is still relevant. I think so.

This is a screen that most people see on their path to becoming Electron developers. It's an opportunity to congratulate people on getting this far (Electron is installed an running 🎉 ) but also to teach about best practices and next steps.

I think the above checklist would be a good start, but here are some other ideas:

- [ ] show Chrome, Node, and V8 versions
- [ ] teach <kbd>CtrlOrCommand</kbd><kbd>Shift</kbd><kbd>C</kbd> for devtools / magical node-ified console
- [ ] link to electron-forge
- [ ] only show `--interactive` tip on macOS and Linux because it's [not supported on Windows](https://github.com/electron/electron/issues/10621)
- [ ] link the logo to the website

**Comment by zeke** [comment]
A couple more ideas that @codebytere tossed around:

- Change the default behavior of `electron` to just print usage info to STDOUT, à la `electron --help`. The default app could instead be opened with a flag, like `electron --default-app` or similar.
- Detect when the default app is being run from the `*/electron/out/*` directory, in which case this is a person working on in the Electron codebase itself, and running the default app to smoke-test their changes.

**Comment by codebytere** [comment]
this is now in master 🎉 
going to go ahead and close!
