### ISSUE TITLE
libnotify.so.4 is not available on all distros

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#5348]
On several distros of Linux the latest libnotify ships libnotify.so.5. However, since we link against libnotify.so.4, we blow up. In older version of RHEL / CentOS, this version is at libnotify.so.1! Should we go back to shipping libnotify in-box?

**Comment by zcbenz** [comment]
I think we should load it dynamically now, shipping libnotify binary causes weird crashes on some platforms.

**Comment by MarshallOfSound** [comment]
@paulcbetts @zcbenz 

Running a CI build agent on Ubuntu 14.04 I get the following error
```
/home/ubuntu/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
```

This would appear to be related to this issue, is there a workaround I can implement on the CI agent

**Comment by zcbenz** [comment]
@MarshallOfSound You should install `libnotify-dev` in the CI server.

**Comment by frederikbosch** [comment]
@zcbenz I did install `libnotify-dev` on my Ubuntu 16.04 machine. Still receive the error `error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory`.

But maybe [the commit you made](https://github.com/electron/brightray/issues/221) helps me out here. I am using [`ember-electron`](https://github.com/felixrieseberg/ember-electron). I find it hard to see how the dependency tree eventually resolves to here. So I cannot find out if that commit is included in the electron version that I am using.

**Comment by frederikbosch** [comment]
@zcbenz I found that the error (`error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory`) is only there for linux 32 bit builds. So I do not get the error for 64 bit builds.

Is this intended? Or is there still an unwanted dependency towards `libnotify`?

**Comment by marshall86** [comment]
Ubuntu 14.04 error : error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory.

I have libnotify-dev already installed, I can not figure out a way, workaround to launch generated linux script built with electron-packager.

It's really urgent for me..

**Comment by BrainsoftLtd** [comment]
I have installed the 32-bit version using 'sudo apt-get install libnotify4:i386'. That solved the problem for me on the 32-bit builds.

**Comment by frederikbosch** [comment]
I also got it running, forgot how. But I believe libnotify should have been removed as dependency, but it is not.
