### ISSUE TITLE
spawn wine ENOENT Used when build windows app using electron v0.37.8

### ISSUE THREAD

**Issue by 21jhf** [electron/electron#5354]
* Electron version:0.37.8
* Operating system:MacOs
Downloading electron-v0.37.8-win32-x64.zip
[============================================>] 100.0% of 49.65 MB (224.17 kB/s)
Packaging app for platform win32 x64 using electron v0.37.8
Warning: spawn wine ENOENT Used --force, continuing.

Process finished with exit code 0

when i build Kitematic use command "grunt electron:windows" i got spawn wine ENOENT Used
the full command details like this:
/usr/local/bin/node /usr/local/lib/node_modules/grunt/bin/grunt --gruntfile /Users/subway/Documents/reactjs/kitematic-0.10.2/Gruntfile.js --force --verbose electron:windows

**Comment by MarshallOfSound** [comment]
This is an https://github.com/electron-userland/electron-packager issue not an electron issue

**Comment by paulcbetts** [comment]
Install wine

**Comment by Pika1998** [comment]
> Install wine

Yes this is the correct solution, is this step only necessary when i am trying to package for win32 using a linux OS?
