### ISSUE TITLE
Keyboard input doesn't seem to work

### ISSUE THREAD

**Issue by sota1235** [electron/electron#5355]
* Electron version: 0.37.7
* Operating system: OS X Yosemite (10.10.5)

I try to use `<input type="text">` in my `index.html`. But it doesn't seem to work...
I found the issue like this problem and I tried a solution that has been listed. But it failed.
#957

Please tell me what I'm wrong. I need some optinos?

Here is my main script.

`main.js`
```javascript
'use strict';

const app = require('app');
const BrowserWindow = require('browser-window');

let mainWindow = null;

app.on('window-all-closed', () => {
  if (process.platform != 'darwin') {
    app.quit();
  }
});

app.on('ready', () => {
  mainWindow = new BrowserWindow({width: 800, height: 600});
  mainWindow.loadURL(`file://${__dirname}/index.html`);

  mainWindow.webContents.openDevTools();

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
});
```

`index.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
    <title>Application name</title>
  </head>
  <body>
    <form action="/">
      <input type="text">
    </form>
  </body>
</html>
```

Thank you.

**Comment by zcbenz** [comment]
That is because the input tag is not focused:

```js
    <script type="text/javascript" charset="utf-8">
      document.getElementsByTagName('input')[0].focus()
    </script>
```

**Comment by sota1235** [comment]
Thank you for the comment. But I can't solve my problem...

I tried this code on electron, but it doesn't seem to work yet.
Is it wrong? 

`main.js`
```javascript
'use strict';

const app = require('app');
const BrowserWindow = require('browser-window');

let mainWindow = null;

app.on('window-all-closed', () => {
  if (process.platform != 'darwin') {
    app.quit();
  }
});

app.on('ready', () => {
  mainWindow = new BrowserWindow({width: 800, height: 600});
  mainWindow.loadURL(`file://${__dirname}/index.html`);

  mainWindow.webContents.openDevTools();

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
});
```

`index.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
    <title>Application name</title>
  </head>
  <body>
    <form action="/">
      <input type="text">
    </form>
    <script type="text/javascript" charset="UTF-8">
      document.getElementsByTagName('input')[0].focus();
    </script>
  </body>
</html>
```

**Comment by zcbenz** [comment]
> mainWindow.webContents.openDevTools();

Because the focus is moved to devtools after you call `openDevTools`.

**Comment by sota1235** [comment]
I found this issue( #733 ), and I tried starting electron without tmux. The problem was solved!!
Thank you for teaching various :)

**Comment by LoveKino** [comment]
I got this problem too. Thanks for the answer and starting electron without tmux is the solution. it's strange.

**Comment by luchillo17** [comment]
WTF?!! i've been fighting this for 3 days thinking i had messed up the dependencies (my project was done before npm 5 and started using yarn a few days ago), getting out of tmux or adding the following in tmux config fix the issue (for the above to work you need to install `brew install reattach-to-user-namespace`):
```sh
# Patch for OS X pbpaste and pbcopy under tmux.
set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"
```

**Comment by khanhicetea** [comment]
@luchillo17 solution is worked with tmux. Thanks !
