### ISSUE TITLE
theme icon for tray on Linux

### ISSUE THREAD

**Issue by wa4557** [electron/electron#5364]
As far as I understand the code there is no way to use theme icons in the tray class
`new tray  = Tray('path to hardcoded file or native image')`
which does not allow to use properly themed icons from an icon theme
Is there something that can be done about that?
- Operating system: Ubuntu 16.04

**Comment by Silvercast** [comment]
+1

**Comment by codebytere** [comment]
Given that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!

**Comment by rocka** [comment]
For some reason, the tray icon is somewhat "themeable" before electron@8, when using the libappindicator implementation, which is, set environment variable `XDG_CURRENT_DESKTOP` to `Unity`.

By doing so, when the app creates a tray icon, a dbus interface would be exposed, contains object `/org/ayatana/NotificationItem/${APP_NAME}1`. The object's `IconName` property would be `${APP_NAME}1_1` , and it's `IconThemePath` would be a temporary path like `/tmp/.org.chromium.Chromium.${RANDOM_HASH}` , and inside that directroy lies the icon. From it's name, I believe it's a chromium thing ... And if you provide such a icon named exactly `${APP_NAME}1_1` in your icon theme, the tray icon image would appear as the icon theme provided, not the hard coded one, kind of nice tbh.

![image](https://user-images.githubusercontent.com/13914967/74584572-f21d6b80-500e-11ea-88d3-f5a14e5c37d1.png)

This "hack" was confirmed works on KDE Plasma and Ubuntu Untiy desktop, with electron@7.

But start from electron@8, this "hack" dose not work anymore, the dbus interface dose not even show up. Maybe this is a chromium change? Even worse, tray icon on HiDPI displays also got blurry, even if you provide a high resolution image, as per #22207
