### ISSUE TITLE
Associate Application With File Type

### ISSUE THREAD

**Issue by simonhochrein** [electron/electron#5369]
I was wondering how to make a electron app the default opener for .md files.
I was researching and didn't find anything.
Does anyone know how this can be accomplished?
thanks

**Comment by flooooh** [comment]
For OS X you can find information in Apple's official [developer library](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-101685-TPXREF107).

**Comment by kevinsawicki** [comment]
You can see how the Atom text editor does this with the follow:

Mac OS X via the plist file: https://github.com/atom/atom/blob/d6d47c422c07b71421471720f7d96b52890feeb0/resources/mac/atom-Info.plist#L745-L761

Windows via writing to the registry: https://github.com/atom/atom/blob/d6d47c422c07b71421471720f7d96b52890feeb0/src/browser/squirrel-update.coffee#L90-L92

Hope this helps.
