### ISSUE TITLE
Uncaught Error:DLL initialisation routine failed on Windows 10

### ISSUE THREAD

**Issue by FabianTerhorst** [electron/electron#5370]
* Electron version: 0.37.8
* Operating system: Windows 10 x64

I have tried to implement my own native module with electron, but im getting the following js error inside my console:"`Uncaught Error:DLL initialisation routine failed C:.../node`". I used npm install NameOfMyModuleto install it. My main.js looks like this: `var NameOfMyModule = require('NameOfMyModule');`
I run electron-rebuild.cmd after calling npm install. When im using nodejs without electron the module works fine.

**Comment by FabianTerhorst** [comment]
I got now the following error when im running `node-gyp rebuild --target=0.29.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell` inside my node module folder:Uncaught Error: The specified procedure could not be found.

**Comment by FabianTerhorst** [comment]
Running `node-gyp rebuild --target=0.37.8 --arch=x64 --dist-url=https://atom.io/download/atom-shell` is returinig the following error:  `Error: Invalid URI "url=https://atom.io/download/atom-shel/v0.37.8/node-v0.37.8.tar.gz"`

**Comment by L3V147H4N** [comment]
I got a similar problem: I'm getting:

`Uncaught Error: A dynamic link library (DLL) initialization routine failed.`
on
`node_modules\bindings\bindings.js`

**Comment by MarshallOfSound** [comment]
Please read the documentation on using native node modules.

https://github.com/electron/electron/blob/f403950503eb82bcfa230b13a909572beff75fc0/docs/tutorial/using-native-node-modules.md

**Comment by FabianTerhorst** [comment]
i have tried the simple way, but the other ways require the download of electron 0.37.8 and this doesn´t work https://github.com/electron/electron/issues/5370#issuecomment-216239845

**Comment by FabianTerhorst** [comment]
I can also provide the source for my native module thats already working for nodejs, maybe i can improve it for a better electron support.

**Comment by L3V147H4N** [comment]
When attepting to rebuild I get this error:

![image](https://cloud.githubusercontent.com/assets/5846479/14960185/bc217ef6-1069-11e6-8730-c9f4db041422.png)

**Comment by MarshallOfSound** [comment]
@L3V147H4N I've had that error before, simply go into File Explorer and manually delete the file it can't unlink.

@FabianTerhorst I just tested `electron-rebuild` on your module and it definitely rebuilds it, it looks like you are missing typing the command.  The error message you posted has a single "l" in atom-shell when there should be 2

**Comment by FabianTerhorst** [comment]
@MarshallOfSound thanks, node-gyp rebuild --target=0.37.8 --arch=x64 --dist-url=https://atom.io/download/atom-shell is working.
