### ISSUE TITLE
Enable Notifications in Webviews

### ISSUE THREAD

**Issue by saenzramiro** [electron/electron#5374]
* Electron version: 0.37.8
* Operating system: Windows 7

Hello.

I read that enabling notifications in Electron require some steps on Windows. But my question is if there is a way to display native notifications for a website embedded in a webview.

I have an app that have one HTML with a Webview showing WhatsApp page for example (Slack, Facebook Messenger, etc). As you know, when you receive a new message, Chrome displays a notification. I want to display the same notification comming from the original website.

Also, I tried to make a quick example without using Webview, so I create an electron quick start folder, and load the following URL in my BrowserWindow:

http://demo.codeforgeek.com/notification/

Then I click in the button to display the notification, and nothing happened.

**Comment by MarshallOfSound** [comment]
@saenzramiro Read the Notification docs for electron.

https://github.com/electron/electron/blob/a4de40ec89fa876f567ef8ddbd892f762a2ce4fa/docs/tutorial/desktop-environment-integration.md#windows

> On Windows 7 and below, notifications are not supported.

**Comment by saenzramiro** [comment]
> You can however send "balloon notifications" using the Tray API.

And if I want to use balloons? Is there a way to replace native notifications with balloons in those websites?
