### ISSUE TITLE
Updating Code Samples in Documentation

### ISSUE THREAD

**Issue by stevekinney** [electron/electron#5380]
* Electron version: 0.37.8
* Operating system: All

I've been reading through the (excellent) documentation for Electron and I've noticed a few minor things with some of the code samples in the documentation.

I'm more than happy to go ahead, fix these issues, and open a pull request if it's something that the team thinks is helpful. (I just don't want to get in the way if there is something else going on too.)

Here are some of the updates I'd like to take on:

In the [synopsis][syn], it says that [if we're using Babel, we can use destructuring assignment][des]. This is officially supported in the version of V8 that ships with at least the most recent version of Electron. I'd like to update the documentation to this style since it seems like something you encourage.

In the section on [coding style][cod], the documentation makes the following recommendations:

> * Write [standard](http://npm.im/standard) JavaScript style.
> * Files should **NOT** end with new line, because we want to match Google's
>   styles.
> * File names should be concatenated with `-` instead of `_`, e.g.
>   `file-name.js` rather than `file_name.js`, because in
>   [github/atom](https://github.com/github/atom) module names are usually in
>   the `module-name` form. This rule only applies to `.js` files.
> * Use newer ES6/ES2015 syntax where appropriate
>   * [`const`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const)
>     for requires and other constants
>   * [`let`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let)
>     for defining variables
>   * [Arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)
>     instead of `function () { }`
>   * [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
>     instead of string concatenation using `+`

I'd like to update the code sample to use at least the style conventions outlined in the last major bullet point, but I'd also be willing to update everything to Standard JavaScript if that was something you all were interested in as well.

Let me know if you'd like me to move forward with this—and thank you for all of your awesome work.

[syn]: https://github.com/electron/electron/blob/master/docs/api/synopsis.md
[des]: https://github.com/electron/electron/blob/master/docs/api/synopsis.md#destructuring-assignment
[cod]: https://github.com/electron/electron/blob/master/docs/development/coding-style.md

**Comment by zcbenz** [comment]
The code samples were written before we have modern ES6 in Electron, it would be awesome if you can help update them!

**Comment by zcbenz** [comment]
Closed with #5394.
