### ISSUE TITLE
BrowserWindow's .show() fails on Windows startup

### ISSUE THREAD

**Issue by MarcoPolo** [electron/electron#5384]
* Electron version: 0.37.3
* Operating system: Windows

On startup if a `BrowserWindow` is hidden before Windows fully launches, and you try to `.show()` it. The `BrowserWindow` will not show up, and `.isVisible()` correctly returns `false`.

Workaround is to keep trying to `.show()` on a loop until `.isVisible()` returns true.

Just wondering if this is expected, and if so should probably be documented.

Thanks!

**Comment by MarshallOfSound** [comment]
@MarcoPolo can you provide minimum sample code to reproduce this issue?

**Comment by danhp** [comment]
This is expected behavior as the `BrowserWindow` isn't created instantaneously.

Instead of continuously trying to call `show` you should do the following:
```js
const win = new BrowserWindow()
win.webContents.on('did-finish-load', function () {
    win.show()
})
```

**Comment by MarcoPolo** [comment]
@danhp Worked great thanks.
