### ISSUE TITLE
Getting started ... or not?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [electron/electron#5386]
* Electron version: I don't know how to look that up, but npm probably downloaded that prebuild version: 0.37.8 when I ran the example app using `npm install && npm start`.
* Operating system: Fedora 22

So I've installed `nvm` and then installed the LTS release of `npm` in order to run my electron app. I want to create a simple tutorial app, but already the getting started doesn't work as described. When I run `electron .` in my app's directory, I only get the the following error:

    bash: electron: command not found...

Obviously the bash doesn't know the command electron. However, that electron must have been installed with the minimal app, which one can clone and run as shown on the [electron.atom website](http://electron.atom.io/#get-started). That `npm install && npm start` ought to have downloaded the electron binary specified in the example project's `package.json`, right? So why does `electron .` not work in my project then?

There should be more explanation for this definitely. I can't even get the [quick start tutorial](http://electron.atom.io/docs/latest/tutorial/quick-start/) running with the given explanation. Note: I don't have Node.js experience. This might be the getting started assuming too much knowledge about the whole Node.js architecture or package management or developing cycle.

When I run the `npm install && npm start` instead of `electron .` in my projects directory, I get different errors:

	npm WARN package.json tutorial_app@0.1.0 No repository field.
	npm WARN package.json tutorial_app@0.1.0 No README data
	npm WARN package.json tutorial_app@0.1.0 No license field.

	> tutorial_app@0.1.0 start /home/xiaolong/development/Electron/tutorial
	> electron main.js

	App threw an error when running [TypeError: Cannot read property 'on' of undefined]
	A JavaScript error occurred in the main process
	Uncaught Exception:
	TypeError: Cannot read property 'on' of undefined
		at Object.<anonymous> (/home/xiaolong/development/Electron/tutorial/main.js:35:4)
		at Module._compile (module.js:413:34)
		at Object.Module._extensions..js (module.js:422:10)
		at Module.load (module.js:357:32)
		at Function.Module._load (module.js:314:12)
		at loadApplicationPackage (/home/xiaolong/development/Electron/tutorial/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:253:23)
		at Object.<anonymous> (/home/xiaolong/development/Electron/tutorial/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:293:5)
		at Module._compile (module.js:413:34)
		at Object.Module._extensions..js (module.js:422:10)
		at Module.load (module.js:357:32)

So to me it seems that `app` in the `main.js` is undefined because electron is undefined, because somehow it cannot find electron.

I've searched around a bit, but so far I've only found stuff related to node.js and the `package.json`, which I also had to change a lot, to even get to this point. Here is my changed `package.json`:

	{
		"name": "tutorial_app",
		"description": "This is a tutorial application. Its purpose is to write some Electron code, to learn how to use Electron to create desktop applications.",
		"version": "0.1.0",
		"main": "main.js",
		"scripts": {
			"start": "electron main.js"
		},

		"keywords": [
			"Electron",
			"tutorial"
		],

		"author": "杨小龙",
		"devDependencies": {
			"electron-prebuilt": "^0.37.8"
		}
	}

I also ran into an issue when I used whitespace in my package name. Worth mentioning in the getting started, I think.

How can I really get started with electron? Is there a more detailed installation + getting started somewhere?

**Comment by mnquintana** [comment]
What quick start instructions are you using?

Have you tried running `npm start` in the quick start app directory? The quick start instructions right now say to run `npm start` in the directory, rather than `electron .`

As you mentioned, running `electron` in the command line won't work because `npm install` installs all dependencies locally in the app directory, instead of globally. The quick start app includes the `npm start` script so you can run the app using the local dependency, without having to set up `electron` globally.

Hope that helps!

**Comment by ZelphirKaltstahl** [comment]
@mnquintana Yes, I've tried that. The getting started tutorial tells you to use `electron .`, which doesn't work, but the example hello world app instruction, which you can clone from the repo, tells you to use the `npm install && npm start`, which is why I even tried that in my tutorial app. That resulted in the longer error I described above.
What I was also wondering about is, that the tutorial doesn't tell you to list the electron as a dependency in your `package.json` although it clearly is one. I had to figure that out myself as well. Still no run : (

**Comment by baconface** [comment]
It was closed because this is a users misunderstanding of how to use Electron. This issue manager is meant for bug reports and feature requests. Please re-close the issue and ask for help at https://discuss.atom.io/c/electron

**Comment by ZelphirKaltstahl** [comment]
Ah ok I assumed it to be a bug, because the very instructions from the official website don't work as expected. Might make a post over there and ask people there. Thanks.

**Comment by kevinsawicki** [comment]
@ZelphirKaltstahl do you have `node_modules/.bin` on your `PATH`?

I think that is one assumption the instructions currently assume.

Does `./node_modules/.bin/electron .` work for you?

**Comment by mnquintana** [comment]
I reopened because I wanted to see if the docs needed updating. I think the confusion might be at this step: http://electron.atom.io/docs/latest/tutorial/quick-start/#electron-prebuilt

It lists two options, depending on how you installed `electron-prebuilt` – `electron .` if you installed globally, and `./node_modules/.bin/electron .` if you installed locally. Since you installed locally, you should run the latter command, which should work if you've run `npm install` in your project directory.

To make things easier, I'd recommend looking into [setting up an `npm run` script](https://docs.npmjs.com/misc/scripts) so you don't have to type the full path to the Electron binary every time you run your app.

**Comment by ZelphirKaltstahl** [comment]
> do you have node_modules/.bin on your PATH?

No, I have not, but this might be a good idea to always do that for new project.

> Does ./node_modules/.bin/electron . work for you?

`~/.nvm/versions/node/v4.4.3/bin/electron .` in the project directory does not work either. Same error as in the original post.

> Since you installed locally, you should run the latter command, which should work if you've run npm install in your project directory.

And exactly there is the problem. Even if I use the full path, it gives the error in my original post.

**Comment by kevinsawicki** [comment]
What is on the `/home/xiaolong/development/Electron/tutorial/main.js:35` line?

That is where the error is coming from, looking there should tell you what variable/property you are trying to call `on()` on that is not there.

**Comment by ZelphirKaltstahl** [comment]
> What is on the /home/xiaolong/development/Electron/tutorial/main.js:35 line?

The thing is, that there is a comment on that line. It seems not to count the comments as lines or something. The following is my `main.js` file.

	const electron = require('electron')
	// Module to control application life.
	const app = electron.app
	// Module to create native browser window.
	const BrowserWindow = electron.BrowserWindow

	// Keep a global reference of the window object, if you don't, the window will
	// be closed automatically when the JavaScript object is garbage collected.
	let mainWindow

	function createWindow () {
	  // Create the browser window.
	  mainWindow = new BrowserWindow({width: 800, height: 600})

	  // and load the index.html of the app.
	  mainWindow.loadURL('file://' + __dirname + '/index.html')

	  // Open the DevTools.
	  mainWindow.webContents.openDevTools()

	  // Emitted when the window is closed.
	  mainWindow.on('closed', function () {
		// Dereference the window object, usually you would store windows
		// in an array if your app supports multi windows, this is the time
		// when you should delete the corresponding element.
		mainWindow = null
	  })
	}

	// This method will be called when Electron has finished
	// initialization and is ready to create browser windows.
	// Some APIs can only be used after this event occurs.
	app.on('ready', createWindow)

	// Quit when all windows are closed.
	app.on('window-all-closed', function () {
	  // On OS X it is common for applications and their menu bar
	  // to stay active until the user quits explicitly with Cmd + Q
	  if (process.platform !== 'darwin') {
		app.quit()
	  }
	})

	app.on('activate', function () {
	  // On OS X it's common to re-create a window in the app when the
	  // dock icon is clicked and there are no other windows open.
	  if (mainWindow === null) {
		createWindow()
	  }
	})

	// In this file you can include the rest of your app's specific main process
	// code. You can also put them in separate files and require them here.

Next to the line 35 would be:

    	app.on('window-all-closed', function () {
	  // On OS X it is common for applications and their menu bar
	  // to stay active until the user quits explicitly with Cmd + Q
	  if (process.platform !== 'darwin') {
		app.quit()
	  }
	})

However, `app` is defined at the top:

    const app = electron.app

So I don't know what is going on : /

**Comment by cjdg** [comment]
i have the same issue

**Comment by stianSjoli** [comment]
Yes, me as well. The quick start tutorial fails, and I tried to build electron on my macOS which also fails.

**Comment by sielay** [comment]
+1 shouldn't be closed

**Comment by minimedj** [comment]
As a temporal workaround I had to create `electron.sh` with `./node_modules/.bin/electron .` in it...

**Comment by markedelman** [comment]
Had the same problem, kevinsawicki's comment to try "./node_modules/.bin/electron ." insstead of "electron ." or "npm start" worked perfectly, Thank you : )

**Comment by bennymeier** [comment]
Had also the same problem, kevinsawicki's comment to try "./node_modules/.bin/electron ." insstead of "electron ." or "npm start" worked perfectly, Thank you : )

**Comment by bonniesimon** [comment]
> 
> 
> Had also the same problem, kevinsawicki's comment to try "./node_modules/.bin/electron ." insstead of "electron ." or "npm start" worked perfectly, Thank you : )

I tried this, but still its not working for me. Are there any other solution?
