### ISSUE TITLE
x64 can't compatible x86 native module ?

### ISSUE THREAD

**Issue by csy2002** [electron/electron#5389]
* Electron version:0.36.12
* Operating system:window 7
load x86 native module fail with in electron that base on x64;
error message : Error: %1 is not a valid Win32 application..

**Comment by MarshallOfSound** [comment]
You need to follow the instructions over at https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md

32bit compiled modules won't work on a 64bit version of electron, you need to recompile through one of the ways mentioned in that doc.
