### ISSUE TITLE
app.restart()

### ISSUE THREAD

**Issue by marcbachmann** [electron/electron#539]
Currently there is no app.restart function. I think a simple method that restarts the app is quite useful.

In my application, I do database updates after downloading a new version of an app.
After those database updates, it's best to just restart the app to prevent database problems.

The app.restart method can also be reused in the `auto-updater`.

**Comment by jaunkst** [comment]
It does relaunch a window for me on OSX but it doesn't load the app.

**Comment by paulcbetts** [comment]
This is actually something that might be useful given the addition of the `makeSingleInstance` API, since the straightforward way that @bwin provides doesn't work then (since if you lose the race, you'll just signal yourself then proceed to exit)

**Comment by RiderSx** [comment]
Any news/plans on this?

**Comment by lipis** [comment]
yes, please.. :dancers:

**Comment by kurisubrooks** [comment]
Any news on this?

**Comment by wesleywesley** [comment]
any news?

**Comment by gbaumgart** [comment]
doesn't really work on linux with latest:
- args are not passed
- app not relaunching

i'v got nothing on the console, no errors.

**Comment by samuelcesc** [comment]
Would really love this to be added.

**Comment by MarshallOfSound** [comment]
@samuelcesc See #5837

That is the PR that closed this issue 👍

**Comment by mobiniusHarshajagadish** [comment]
@zcbenz thanks for your amazing work. But I have a problem . Could you please tell me how to call an API , a service on my server , before the operating system restarts or shuts down ?

**Comment by SuperAL** [comment]
For anyone looking for solution，here is mine for now：
```
const remote = require('electron').remote;
remote.app.relaunch();
remote.app.exit(0);
```
Reference:
https://electronjs.org/docs/api/app#apprelaunchoptions

**Comment by zimulili** [comment]
https://electronjs.org/docs/api/app#apprelaunchoptions
