### ISSUE TITLE
Devtools console logs does not scroll automatically

### ISSUE THREAD

**Issue by remss** [electron/electron#5391]
* Electron version: 0.37.8
* Operating system: Windows 7 64bit

Try with a main.js from Quick Start documentation, and index.html like this

```
<!DOCTYPE HTML>
<html lang="en">
<body>
    <script>
    
        setInterval(function() {
            console.log('foo');
        }, 50);
        setInterval(function() {
            console.warn('bar');
        }, 100);
        
    </script>    
</body>
</html>
```

Auto scroll in console logs stop working after few seconds.

**Comment by MarshallOfSound** [comment]
This occurs in chrome as well, it is probably to stop console spam.  Not an issue, it's a feature :+1:

**Comment by tylerstalder** [comment]
Seems it's a Dev Tools bug released in Chrome 49 smooth scrolling.
https://bugs.chromium.org/p/chromium/issues/detail?id=603294&q=component%3APlatform%3EDevTools%20scroll&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

Other reports in Chrome
http://stackoverflow.com/a/21073677

**Comment by zcbenz** [comment]
I'm closing this since this is an upstream bug of Chromium and we are not able to fix it on Electron's side.
