### ISSUE TITLE
electron main.js isn't working

### ISSUE THREAD

**Issue by mark-hahn** [electron/electron#5396]
* Electron version:  v0.37.8 (just guessing, that is what is shown at http://electron.atom.io/#get-started)
* Operating system: ubuntu 12.04

I cloned `electron/electron-quick-start` and ran `npm install && npm start` and all the dependencies loaded and then I got this ...

```
> electron-quick-start@1.0.0 start /root/dev/logic+/electron-quick-start
> electron main.js

npm ERR! Linux 3.14.0
npm ERR! argv "/root/.nvm/versions/node/v5.11.0/bin/node" "/root/.nvm/versions/node/v5.11.0/bin/npm" "start"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron main.js`
npm ERR! Exit status 1
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
dot-dot-dot
```

then I tried `node main.js` and got this ...

```
/root/dev/logic+/electron-quick-start/main.js:9
let mainWindow
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

What am I doing wrong?

**Comment by kevinsawicki** [comment]
Does `./node_modules/.bin/electron main.js` work for you?

**Comment by mark-hahn** [comment]
I just got a prompt back, but at least no error.

**Comment by kevinsawicki** [comment]
> then I tried node main.js and got this ...

This is expected, `main.js` only runs in Electron.

**Comment by mark-hahn** [comment]
It is working now.  Thanks ...
