### ISSUE TITLE
Multiple character accelerators doesn't work on OS X

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#5398]
Setting an accelerator to `'G+N'`, will only register the `N` keyboard shortcut. I need to execute an action when G+N is pressed.

<img width="369" alt="napkin 05-05-16 8 53 44 am" src="https://cloud.githubusercontent.com/assets/170270/15034358/e3d14a26-129e-11e6-8d97-075eeadde9ea.png">

-

* Electron version: 0.37.8
* Operating system: OS X 10.11.4

**Comment by danhp** [comment]
Most platforms only support shortcuts of the form `1 key code + modifiers` in the menu bar, so I don't think this is easily implementable. But it also looks like the shortcut you're trying to create is a Vim style accelerator (Hit G and then hit N) which is definitely not supported.

**Comment by zcbenz** [comment]
Yeah this is a platform limitation we can not overcome, to achieve it you have to use DOM keyboard events.
