### ISSUE TITLE
Support an array of paths in `BrowserWindow.webPreferences.preload`

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#5400]
I need to preload multiple script in order. I know I can load the next ones async inside the first preloaded script, but that get's convoluted fast. Would be nice if the `preload` option also accepted an array of paths.

http://electron.atom.io/docs/v0.37.8/api/browser-window/

-

* Electron version: 0.37.8
* Operating system: OS X 10.11.4

**Comment by paulcbetts** [comment]
Why not just use `require` to pull them in?

**Comment by sindresorhus** [comment]
@paulcbetts `require` them where/how?

**Comment by OlsonDev** [comment]
I believe @paulcbetts means, for example, `preload.js`:

```js
'use strict';
require('dependency-with-side-effects');
const otherDep = require('other-dep');
const main = require('preload-main');
otherDep.config({ foo: 'bar' });
main.init(otherDep);
```

instead of `main.js`:

```js
...
{
    preload: [
        'dependency-with-side-effects.js'
        'other-dep.js',
        'configure-other-dep.js',
        'preload-main.js',
    ]
}
```

**Comment by paulcbetts** [comment]
Yup ^^^

**Comment by sindresorhus** [comment]
Oh, right. That actually works. I didn't realize you could `require` local dependencies in a preload script. That should definitely be clearer in the docs.

**Comment by paulcbetts** [comment]
Preload scripts have all of the node.js powers, even if node integration is disabled. This means you can set stuff up on the global scope like:

```
import {app} from 'electron';

// Now the page will have access to bounceTheDock, but not require or module
window.bounceTheDock = () => app.dock.bounce();
```

**Comment by sindresorhus** [comment]
@paulcbetts Yup, after you mentioned this, I discovered the same trick for `ipc` too.

**Comment by zcbenz** [comment]
Should we close this? It seems that this doesn't make much improvement and makes the interface more complicated.

**Comment by leethomas** [comment]
I think so, it really isn't necessary. Didn't realize that

**Comment by sindresorhus** [comment]
Yes, I'll do a PR later to improve the `preload` docs.
