### ISSUE TITLE
Top-most pixel of maximized frameless window does not allow you to drag

### ISSUE THREAD

**Issue by vulture** [electron/electron#5404]
* Electron version: Various
* Operating system: Windows 8

Repro:
(1) Maximize a frameless window
(2) Move mouse to very top of screen
(3) Try to drag, notice nothing happens
(4) Move mouse down ~1 pixel, then try dragging, notice a different behavior happens

On Win7+ with the extra window management stuff enabled (default), this would normally de-maximize a window to allow you to drag it somewhere else. With it disabled or pre-Win7, the behavior is usually nothing (although, in an unrelated bug, Electron [wrongly] allows you to drag the window, while chromium frameless windows [correctly] do not).

**Comment by zcbenz** [comment]
Hmm I didn't observe anything different, did you mean it would de-maximize the window?

**Comment by zcbenz** [comment]
Closing until more information is provided.
