### ISSUE TITLE
What are the limitations of Electron IPC  (would like to push real-time HD+ video to renderer)

### ISSUE THREAD

**Issue by pkoshevoy** [electron/electron#5405]
* Electron version: n/a
* Operating system: Mac, Windows, Linux, iOS, Android

I am trying to understand the limitations of Electron native integration capabilities.

My user experience is defined as:
* Drag-n-drop a selection of files/folders/hard-drives onto the app window or app icon, or open a URL
* The files/folders/hard-drives/URL are organized into a playlist (potentially 1000s of items), and playback of the first item in the playlist starts immediately (or resumes from a bookmark from previous run of the application)
* Playback can be paused/resumed
* The playlist can be toggled on/off as an overlay over the live video
* Individual playlist item thumbnails are decoded/rendered on-demand as the user scrolls through the playlist
* Playlist can be filtered  by keywords
* Playlist can be sorted by name or (file) time, in ascending or descending order

Underneath, the video files are processed as follows:
* The video is decoded using ffmpeg libraries (libavformat, libavcodec, libavfilter, libswscale, etc...)
* The video frames are pushed into a short thread-safe blocking queue, from which they can be requested by the video renderer thread.
* The audio frames are similarly decoded and pushed into a short thread-safe frame queue, from which they are consumed by the audio renderer thread.
* Subtitles are decoded to text or bitmaps and also pushed into an thread-safe output queue, which is consumed by the video renderer.

* Could I re-use my existing cross-platform C++ code that handles video decoding/filtering with ffmpeg libraries with Electron?
* Could I implement audio/video frame rendering using Electron *efficiently*, maintaining real-time playback of the video and audio/video synchronization?   Audio renderer should become the master clock provider that would dictate the "real time" for requesting/discarding/waiting-for video frames
* Could I implement color-space conversion of the video frames (from whatever YUV(A) format they are natively stored in to RGB(A) using fragment shaders on the GPU) -- what does Electron provide to facilitate this?

**Comment by zcbenz** [comment]
The IPC in Electron copies data cross processes, so you shouldn't assume it is efficient when passing large real-time data.

For video related things, the only thing you can use is HTML5 video APIs, the low-level ffmepg routines are not exposed in Electron. If you want to do something really complicated, you should probably write a PPAPI plugin instead.
