### ISSUE TITLE
autoUpdater downloads and installs lower version .nupkg and keeps installing it

### ISSUE THREAD

**Issue by jaypanares** [electron/electron#5414]
* Electron version: 0.37.8
* Operating system: Windows 10 x64

Not sure if it's a bug or an error in my implementation, but I noticed that if I installed, say, a version 0.0.16 of my app and the update URL points to a URL folder containing a release that is 0.0.14, it downloads the lower version .nupkg then `update-downloaded` fires.  If i `quitAndInstall()` the process repeats itself.

**Comment by bengotow** [comment]
Hey! I'm not sure if this is related, but https://github.com/Squirrel/Squirrel.Windows does not support downgrading. When it's completing the installation process, it goes to delete the "old" files, and it always deletes the folder with the lower semver version number. Took us a while to figure out!

**Comment by jaypanares** [comment]
Thanks for the info, I wasn't actually trying to downgrade my app but just noticed that autoUpdater still downloads the .nupkg file even though it's a lower version.  Anyways, this probably shouldn't happen in a normal production setting since higher versions of .nupkg will always be uploaded to the release URL.
