### ISSUE TITLE
 While you can screen transition was to keep the scaling?

### ISSUE THREAD

**Issue by ytokiwa** [electron/electron#5417]
* Electron version:0.37.6
* Operating system:Windows8.1

Currently we have been developing in Electron, or transition to another screen in a state in which the scale the screen, do you specifications of the Electron is the scaling of the screen to refresh the screen would go back to the original?
I or transition to another screen in the state is that you scale the screen of seeking, but the state also scaling to refresh I want to keep ....

**Comment by zcbenz** [comment]
Electron will follow the behavior of Chrome browser.

**Comment by ytokiwa** [comment]
"Electron will follow the behavior of Chrome browser." And I understand that, but the transition actually screen while zoomed in Chrome browser was operation, back to the once 100 percent of the state when the screen transition after the expansion in Electron will specifications of the Electron is to put away. Or do you have to say and how to screen transition while zoomed in Electron. Please tell me if any.
