### ISSUE TITLE
Support 'Forward Delete' accelerator on Mac OS X

### ISSUE THREAD

**Issue by vkatushenok** [electron/electron#5419]
It would be great to use something like `FwdDeleteOrDelete` and `FwdDelete` accelerators on Mac OS X platform, as this this most intuitive shortcut for Mac users, when deleting something (fn+backspace).

* Electron version: 0.37.8
* Operating system: OS X El Capitan, 10.11.3

**Comment by zcbenz** [comment]
The `Delete` accelerator should be what you want, but somehow it is not working.

**Comment by xMrWhite** [comment]
I'm trying to trace this bug, looks like it might be a mismatch of key codes in libchromiumcontent.
Where is the code file that corresponds to this header?
`./electron/vendor/brightray/vendor/download/libchromiumcontent/src/ui/events/keycodes/keyboard_code_conversion_mac.h`
