### ISSUE TITLE
webContents "did-fail-load" event should be triggered for "ERR_TUNNEL_CONNECTION_FAILED" and similar errors

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#5420]
In Google Chrome, that would be this error:

<img width="679" alt="screen shot 2016-05-06 at 7 40 39 pm" src="https://cloud.githubusercontent.com/assets/797899/15072036/b3186264-13c2-11e6-91c8-dd6a739573ed.png">

Chrome (and I assume Chromium) can throw a bunch of errors like the one above and right now when those happened webContents [did-fail-load](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-did-fail-load) doesn't seem to be triggered.

**Comment by deepak1556** [comment]
Can confirm `did-fail-load` emits with `ERR_TUNNEL_CONNECTION_FAILED` error code. Tested with proxy and following in default app.

```
window.loadURL('https://google.com')

session.defaultSession.webRequest.onHeadersReceived(function (details, callback) {
    details.responseHeaders['Location'] = 'http://httpstat.us'
    callback({
      responseHeaders: details.responseHeaders,
      statusLine: 'HTTP/1.1 302 Found'
    })
  });
```

can you provide an example app ?

**Comment by romaincointepas** [comment]
Oh indeed, I must have done something wrong, sorry about that and thank you for the swift response.
