### ISSUE TITLE
electron not doing anything on Ubuntu 14.04

### ISSUE THREAD

**Issue by odubuc** [electron/electron#5422]
* Electron version: 0.37.8
* Operating system: Ubuntu 14.04 trusty

On a fresh install with npm v 3.8.9
using: npm install -g electron-prebuilt

using the command "electron -v" doesn't output anything 
and running a js containing only console.log('test') doesn't output anything either (e.g. "electron test.js")
it simply skip the electron command without output or errors.

Am I doing something wrong or did I hit an issue?

I replicated on two different servers with the same OS and npm versions both fresh install.

**Comment by lastmjs** [comment]
I think I ran into a similar issue a few days ago with a fresh install of 14.04. In my case, I had some console output though, telling me that I was missing a file from a library. I installed these libraries and I've been good to go: `libgtk2.0-0 libnotify-bin libgconf-2-4 libnss3`

**Comment by odubuc** [comment]
I do have those libraries installed on 1 of the two servers I've installed electron on. But both react exactly the same. no output, just nothing.

**Comment by zcbenz** [comment]
Can you run following command and see if there is any output?

```
export ELECTRON_ENABLE_LOGGING=1
export ELECTRON_ENABLE_STACK_DUMPING=1
electron -v
```

**Comment by odubuc** [comment]
Now I can get the following error:
`[20027:0509/085149:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/sr                                                                        c/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[20027:0509/085149:ERROR:browser_main_loop.cc(267)] Gtk: cannot open display:
[20029:0100/000000:ERROR:zygote_linux.cc(668)] write: Broken pipe`

I think I understand my problem, I did not realize I needed X for some reasons...
https://github.com/electron/electron/issues/2472

Am I correct? I'm currently on headless servers inside different data centers.

**Comment by odubuc** [comment]
I got it running inside `xvfb`. Now Electron seems to work properly.
Thank you for your help, you pointed me in the right direction!
