### ISSUE TITLE
[Request] - WebGL / Canvas Only Mode

### ISSUE THREAD

**Issue by Dillybob92** [electron/electron#5435]
Hey!

I'm developing a rather large UI if you will for our game. Think of a Path of Exile game and their extensive user interface.  CSS/HTML just seems so laggy as compared to a WebGL/Canvas rendering UI system.  

I was wondering maybe if it's possible to have a **"canvas"** only mode feature. This mode basically just renders a canvas element (that you can configure in your main.js file)  -- This feature will disable the CSS renderer and DOM (for performance reasons) and just run your configured canvases. Think of it as a "WebGL" only mode. Thanks for reading ~

**Comment by paulcbetts** [comment]
CSS and DOM don't have any overhead if you don't use them, you should be fine.
