### ISSUE TITLE
Electron app steal focus on system start

### ISSUE THREAD

**Issue by joseramonc** [electron/electron#5441]
* Electron version: 0.36.8, 0.37.8 and I don't know the 3rd app.
* Operating System: OSX El capitan 10.11.4

When my computer gets started all electron apps that initialize on startup get opened, this is really annoying because I have to wait until electron apps stop stealing focus and then I can start to work.

I was expecting that electron apps load in the background without stealing focus like all my non-electron apps that auto initialize on startup.

**Comment by paulcbetts** [comment]
This isn't an electron bug, this is just whatever these three apps are happening to choose to do
