### ISSUE TITLE
 On HiDPI Linux, the drag indicator is at the incorrect screen position

### ISSUE THREAD

**Issue by forivall** [electron/electron#5442]
* Electron version: Atom editor 1.7.3
* Operating system: Arch Linux 64-bit, Gnome 3

On HiDPI, the drag indicator is 2x from the top left corner from where it should be.

```
» xrandr --listactivemonitors
Monitors: 1
 0: +*eDP1 3200/293x1800/165+0+0  eDP1
```

In the shown screenshot, my mouse is on the highlighted entry in the tree view, but the drag indicator is down near the line markers.

![screenshot from 2016-05-07 19-31-26](https://cloud.githubusercontent.com/assets/760204/15095704/d7bd2f14-148a-11e6-81ba-14dd1440d351.png)

I checked, and this is also an issue in chrome, so this issue can be closed in waiting for an upstream fix.

**Comment by zcbenz** [comment]
This had been reported in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=491599, let's click the start button to get Chromium team aware of it.

I'm closing this since this is an upstream bug of Chromium, and we are not able to work around it in Electron.

**Comment by forivall** [comment]
No problem, googling didn't help me find that issue, and I already had the screenshot prepared :wink: . Thanks!
