### ISSUE TITLE
Accept CSS in the `BrowserWindow.webPreferences.preload` option

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#5446]
With https://github.com/electron/electron/issues/5400, it would be useful if it also accepted CSS files. Currently preloading CSS files require some boilerplate:

```js
page.on('dom-ready', () => {
	page.insertCSS(fs.readFileSync(path.join(__dirname, 'browser.css'), 'utf8'));
});
```

Would be nice if I could just do:

```js
new BrowserWindow({
	webPreferences: {
		preload: [
			path.join(__dirname, 'browser.css'),
			path.join(__dirname, 'browser.js')
		]
	}
});
```

http://electron.atom.io/docs/v0.37.8/api/browser-window/

-

* Electron version: 0.37.8
* Operating system: OS X 10.11.4

**Comment by zcbenz** [comment]
Since we are not going to support multiple preload scripts as explained in #5400, I'm closing this as won't fix.

For inserting CSS in preload script, it can be easily done with [DOM's style interface](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule).

**Comment by heyimyunyl** [comment]
It can't be easily done with that. If you import a CSS url with inject.js, the original style of the HTML or the website you are loading will show up for a second and then your css will be loaded. It's really annoying, can't find a solution for this.
