### ISSUE TITLE
typescript nested lambdas error in debugger

### ISSUE THREAD

**Issue by bluEEil** [electron/electron#5450]
* Electron version: latest at this time
* Operating system: windows
Sometimes when trying to nested lambda expressions written in typescript, the debugger shows the "this" object as the window, while in reality its the right object (for example a component I wiritten), If I console.log the some property that I know my object has and the window doesn't I do get correct result, so its only problem with the debugging itself

**Comment by mnquintana** [comment]
Are you writing an Atom package in Typescript? Or working on another Typescript project using a debugger package?

**Comment by bluEEil** [comment]
Just another electron project, written with angular 2 in typescript

**Comment by zcbenz** [comment]
It is hard to say whether it is the bug of devtools or your code, can you provide a minimal app that can reproduce this problem?

**Comment by bluEEil** [comment]
Will a small typescript code sample do? Its a bit tricky for me to post the app

**Comment by zcbenz** [comment]
Yeah a minimal sample would be helpful, it is important that the code is minimal and can show the problem clearly, otherwise no one would have time to actually debug into the code.

**Comment by zcbenz** [comment]
Closing until more information is provided.
