### ISSUE TITLE
Calling 'menu.popup()' should try to show all context-menu's items.

### ISSUE THREAD

**Issue by danhp** [electron/electron#5451]
Currently on OS X, when `menu.popup()` is called and some of the items go lower than the the screen's lower bound, those items are hidden behind a scroll action.

![screen shot 2016-05-08 at 7 49 34 pm](https://cloud.githubusercontent.com/assets/3745612/15101189/8f155048-1557-11e6-95c3-bdb94431a57f.png)

This isn't the same behaviour as Apple's apps which by default try to show all the items by offsetting the menu. I think Electron should replicate this behaviour by default to have context menus feel more native.

---
* Electron version: 0.37.8
* Operating system: OS X

**Comment by praveenkumarzoho** [comment]
I am getting the above issue again.
Electron : 1.3.3
Operating system : OS X
