### ISSUE TITLE
 electron how to call gulp task

### ISSUE THREAD

**Issue by kenzouno1** [electron/electron#5452]
i try write a gulp manager application with electron.I'm running with npm start not have problem. in after release application to exe file i see response message  "Local gulp not found " and "Try running: npm install gulp".
I readed issue [#5129](https://github.com/electron/electron/issues/5129) and many question in google but I do not understand.I'm not a nodejs dev...
I would be very happy if there is an example
Sorry for stupid question.

* Electron version: 0.37.8
* Operating system: window 10 32 bit

**Comment by MarshallOfSound** [comment]
This is probably a job for `child_process.spawn`.  You just need to spawn the executable in `path/to/your/project/node_modules/.bin/gulp` with a options object of 

```
{
    cwd: 'path/to/your/project'
}
```

**Comment by kenzouno1** [comment]
oh.it looks like it has activities but can not found gulpfile.js

**Comment by zcbenz** [comment]
I suggest seeking help from [the community](https://github.com/electron/electron#community), the issues list is only for bug reports and feature requests.
