### ISSUE TITLE
Re:While you can screen transition was to keep the scaling? #5417

### ISSUE THREAD

**Issue by ytokiwa** [electron/electron#5453]
* Electron version:
* Operating system:

"Electron will follow the behavior of Chrome browser." And I understand that, but the transition actually screen while zoomed in Chrome browser was operation, back to the once 100 percent of the state when the screen transition after the expansion in Electron will specifications of the Electron is to put away. Or do you have to say and how to screen transition while zoomed in Electron. Please tell me if any.

**Comment by zcbenz** [comment]
I suggest seeking help from [the community](https://github.com/electron/electron#community).
