### ISSUE TITLE
List a subdirectory of ASAR returns the list of the ASAR root

### ISSUE THREAD

**Issue by remss** [electron/electron#5454]
* Electron version: 0.37.8
* Operating system: Windows 7 64bit
* Project app as ASAR like this

        app.asar
        ├── index.html
        ├── main.js
        ├── package.json
        └── sub
            └── folder
                ├── file1.js
                └── file2.js

Start the electron app, then from devtools

        fs.readdirSync(__dirname + "\\sub\\folder") // returns [file1.js, file2.js] => Right

        fs.readdirSync(__dirname + "\\sub\\folder\\") // returns [index.html, main.js, package.js] => Wrong!!

Expected result

        fs.readdirSync(__dirname + "\\sub\\folder") // returns [file1.js, file2.js] => Right

        fs.readdirSync(__dirname + "\\sub\\folder\\") // returns [file1.js, file2.js] => Right

**Comment by zcbenz** [comment]
I can also reproduce on OS X.

**Comment by remss** [comment]
Seems to be resolved at Electron 1.0.2

**Comment by zcbenz** [comment]
That's good to know, thanks!

**Comment by semiosis** [comment]
I'm seeing this behavior on Electron 1.2.2.

**Comment by cookiejest** [comment]
im seeing this in 1.7.10
