### ISSUE TITLE
QUESTION: How is secure asar application packaging

### ISSUE THREAD

**Issue by loretoparisi** [electron/electron#5457]
I wonder if there is any metrics / test that define a security level for packaging a web app with asar i.e. files contained within the executable. This question can be read in another way. Supposed I build my app with electron and package with `asar`, are there any malicious tools that could reverse my app sources? If so, how to protected against it?

**Comment by enlight** [comment]
There's no need for malicious tools, [the very same tool](https://github.com/electron/asar) that created the .`asar` can be used to extract files from it. This topic has been discussed ad nauseam in issue #3041, and then again in #4359.

**Comment by paulcbetts** [comment]
ASAR is not a mechanism for code security, it is a mechanism to increase app performance.

**Comment by loretoparisi** [comment]
@paulcbetts ok thank you, so it's a matter of how to protect the asar package as discussed ad nauseam in the referred issues.

**Comment by Omar25py** [comment]
you can protect code with enigma virtual box, this have an API you can use to code inside to increase security, and i test this ...i tried to read renderer.js and virtual box dont show file
