### ISSUE TITLE
JS dialogs not working

### ISSUE THREAD

**Issue by rickmed** [electron/electron#5458]
* Electron version: 0.37.8
* Operating system: win 10x64
 
I'm loading a page using BrowserWindow, win.loadURL() and dialogs (confirm, alert, etc) does not apear.
For example, loading 'http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_confirm' and clicking the button it does not appear the alert window, IDEM for any loaded page and loading the page with webview

**Comment by xywz** [comment]
Duplicate of #2644.
