### ISSUE TITLE
Flag to disable runtime features like smooth scrolling

### ISSUE THREAD

**Issue by prasannavl** [electron/electron#5460]
Is there any way to disable runtime features? 

I see the `blinkFeatures` options that can be passed to the webPreferences. However, they seem to pass down directly to native method, which simply just enables the flags. 

Is there any way to disable them? Smooth scrolling for example is enabled by default on the later builds, however I'd like to disable them. I'm wondering what's the best way to do it.

**Comment by davej** [comment]
Have you tried `--disable-smooth-scrolling`?

```js
// in main process before `ready` event.
const { app } = require('electron');
app.commandLine.appendSwitch('disable-smooth-scrolling');
```

**Comment by zcbenz** [comment]
`blinkFeatures` can only turn on features, we can probably add a corresponding `disableBlinkFeatures` option.

**Comment by symbyte** [comment]
Using `--disable-smooth-scrolling` doesn't appear to work. On further inspection it doesn't seem to be supported. See: https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md
