### ISSUE TITLE
The icon in `dialog.showMessageBox` is not resized on Linux

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#5465]
With the following code:

```js
app.on('ready', () => {
	electron.dialog.showMessageBox({
		message: 'Lorem ipsum',
		buttons: [],
		icon: path.join(__dirname, 'Icon.png')
	});
});
```

*The icon is 1024x1024 pixels.*

This is what I get on Linux:

<img width="1159" alt="screen shot 2016-05-10 at 18 15 07" src="https://cloud.githubusercontent.com/assets/170270/15144697/4f4d9c1a-16db-11e6-9fd8-a52534a4ae76.png">

The icon is correctly resized on OS X:

<img width="438" alt="screen shot 2016-05-10 at 18 16 03" src="https://cloud.githubusercontent.com/assets/170270/15144718/6ecbac58-16db-11e6-95cc-8c312bcecb2e.png">

And Windows:

<img width="361" alt="screen shot 2016-05-10 at 18 15 37" src="https://cloud.githubusercontent.com/assets/170270/15144721/7432fbe2-16db-11e6-8322-5980def359e9.png">

-

The documentation for the `icon` option should also document the recommended minimum size for the icon.

-

* Electron version: 0.37.8
* Operating system: Ubuntu 14.04

**Comment by zcbenz** [comment]
This is the behavior of GTK+'s `gtk_message_dialog_set_image`, I don't see any API to change it. We should document the icon size on each platform clearly.

**Comment by sindresorhus** [comment]
@zcbenz Can't you just resize it to a sensible size in Electron before passing it to `gtk_message_dialog_set_image`? Electron strives to smoothen out platform inconsistencies, this is no different.

**Comment by zcbenz** [comment]
@sindresorhus Yeah it sounds better to resize the image.
