### ISSUE TITLE
page turns white and unresponsive when writing .xlsx files

### ISSUE THREAD

**Issue by barbalex** [electron/electron#5467]
* Electron version: 0.37.8
* Operating system: Windows 10, OsX 10.11.4
* XLSX or excel.js newest versions

In my electron app users should be able to export data as .xlsx files.

I am using methods tested and working in Chrome Browser and electron dev mode.
They do not work in electron after building a release package.

After running

    XLSX.writeFile(wb, path, { bookType: 'xlsx', bookSST: true, type: 'binary' })

using XLSX (https://github.com/SheetJS/js-xlsx), or:

    workbook.xlsx.writeFile(path)

using exceljs (https://github.com/guyonroche/exceljs),
the following happens:

- the window turns white / blank
- code following the line is not run
- the window title remains and the page can be reloaded (Ctrl + r), so I guess no new BrowserWindow was opened

I have posted this issue here:
- https://github.com/SheetJS/js-xlsx/issues/399
- https://github.com/guyonroche/exceljs/issues/118
- https://github.com/electron/electron/issues/5174

Issue https://github.com/electron/electron/issues/5174 was closed as being a failure of a third party module.

I do not believe that to be true. If this were so, why would the same code

- work in regular Chrome Browser
- work in dev mode in electron
- not work in two separate third party modules?

This is the last functionality I need to get working before ending my first electron project.
Thanks for this amazing tool.
I would be VERY grateful for help / pointers / solutions to get by this blocking issue.

**Comment by paulcbetts** [comment]
You probably need to run this in another process in the background, my library [electron-remote](https://github.com/paulcbetts/electron-remote) is a very easy way to do this

**Comment by zcbenz** [comment]
Another solution is to use the module in `child_process.fork`, which is an environment more similar to Node.

XLSX is a complex module and none of us have time to debug into it, I'm closing this for the same reason in https://github.com/electron/electron/issues/5174#issuecomment-210710032.

**Comment by barbalex** [comment]
@zcbenz Running

    workbook.xlsx.writeFile(path)

using `child_process.fork` works.

And I learned a lot about node.js while implementing it.

THANKS SO MUCH!

**Comment by eis84** [comment]
I  barbalex ! I have the same problem ...
When execute `
var workbook = new Excel.Workbook();

//Creating Sheet for that particular WorkBook
var sheetName = 'Sheet1';
var sheet = workbook.addWorksheet(sheetName);

//Header must be in below format
sheet.columns = [{key:"name", header:"name"}, {key: "age", header: "age"}];

//Data must be look like below, key of data must be match to header.
var data = [{name:"Kalai", age: 24}, {name:"Vignesh", age:24}];

let i:any;
//adding each in sheet
for( i in data){
  sheet.addRow(data[i]);
}

//Finally creating XLSX file

workbook.xlsx.writeFile(fileName).then(function() {
                this.callback(null);
            });
`
return (in the electron browser console), 

> Y:\*******\node_modules\promish\lib\promish-class.js:17 Uncaught TypeError: Cannot read property 'then' of null

Can you help me?

PS: The xlsx is created, but corruped!
