### ISSUE TITLE
Packaging For Smaller File Size / Footprint

### ISSUE THREAD

**Issue by sgarbesi** [electron/electron#5468]
I've read a number of issue(s) describing the footprint size being a issue.
It's interesting that a simple ZIP compression can yield the packages to a 3rd of their unzipped size.

**Ideas:**

- A small Objective-C wrapper application, that simply unzips the archive and executes it on the system. My app is `test123`, I package it, it comes out as 100MB. When electron does its packaging it could automatically compress the application, then add the wrapper which when invoked on the system would unzip the application then execute it.

- Automated installer? Similar to the issue already posted. Ship the application without the framework, and if the framework excepts globally on the system, then use it. Otherwise prompt for the framework installation, or download it quietly in the background. The application itself could communicate to the end user that it's simply running an update/installing background packages, which shouldn't be that bad. Again this would need it's own Objective-C wrapper obviously.

https://github.com/electron/electron/issues/673

**Comment by zcbenz** [comment]
I like the idea, and it is a already quite popular for Windows apps. But this issue does not belong to Electron, you can write a small installer that downloads the actual file from internet, which can work for arbitrary app instead of just Electron.

**Comment by sgarbesi** [comment]
@zcbenz I was thinking more along the lines of a wrapper.

`test.app` === wrapper with .zip of electron app bundled.

When running `test.app` it decompresses itself internally, then launches the decompressed app. Obviously after the first run, it would cache the decompressed application and either swap itself out, or just always reference the decompressed library.

You're correct though. This is a separate app, but because of the large footprint, it probably would've been appealing if something like this was already bundled in. Maybe if I can find some spare time I'll try to write a add-on. I can't imagine it being that much code.
