### ISSUE TITLE
Mac tray apps should be draggable across the tray section of the menu bar

### ISSUE THREAD

**Issue by jorisw** [electron/electron#5475]
* Electron version: any
* Operating system: Mac OS X

'Tray' apps on OS X should be drag-arrangable but holding Command and dragging a tray app left or right. Native tray items on Mac support this. Try your wifi menu for example.

**Comment by danhp** [comment]
OS X doesn't expose any of those API to third party apps so it isn't possible to implement this feature.

**Comment by zcbenz** [comment]
I'm closing this as won't fix since it is not possible to implement in third party apps with public APIs.
