### ISSUE TITLE
webContents ID is too large

### ISSUE THREAD

**Issue by virli** [electron/electron#5476]
* Electron version:v0.37.8
* Operating system:windows 7

web content not load if this exception happened, is there a way to reset web Contents ID
![13184644_120300000003104167_1651628531_o](https://cloud.githubusercontent.com/assets/13587401/15158819/ca3b89ce-171b-11e6-89b0-1287858e7dfb.png)

**Comment by zcbenz** [comment]
Hmm I didn't expect this error to actually happen,  I'll fix this on Electron's side.
