### ISSUE TITLE
Ignoring/overriding command line switches

### ISSUE THREAD

**Issue by laramies** [electron/electron#5478]
I am looking a way to ignore certain command line switches, for example I want to ignore the following:

--host-rules
--remote-debugging-port
--ignore-certificate-errors

Basically in order to prevent potential Social Engineer attacks on my users. (Copy pasting from forums, attackers tricking users to start the app with those switches, shortcuts including those switches, etc)

Is there any way to do so?

Many thanks
- Electron version: 0.37.8
- Operating system: W10

**Comment by zcbenz** [comment]
Currently there is no good ways to do that, we can probably add a method to reset the command line switches.

**Comment by miniak** [comment]
Or maybe and entry in package.json?

**Comment by paulcbetts** [comment]
@laramies In the Slack app, we just detect these switches on the browser side then refuse to start, our current list is:

```js

// These Chromium switches let you hack yourself or do Weird Things. Blacklist
// them.
const thingsIDontLike = [
  /disable-web-security/i,
  /proxy-server/i,
  /proxy-pac-url/i,
  /allow-running-insecure-content/i
];
```

**Comment by codebytere** [comment]
@laramies this is something that is best done on the client side as @paulcbetts said above, so i'm going to go ahead and close this.
