### ISSUE TITLE
How to assign process.env.* from calling node shell shortcut to electron GUI environment?

### ISSUE THREAD

**Issue by s-a** [electron/electron#5483]
* Electron version: *
* Operating system: *

  
Users want to change  ```process.env.NODE_PATH``` of my electron app. What is the prefered way to this? 

Ref.: https://github.com/s-a/iron-node/issues/98

**Comment by zcbenz** [comment]
`NODE_PATH` and system node modules are ignored in Electron, otherwise it would be very to hijack the app. If you want to add it back, currently you can parse `env.NODE_PATH` and the add the paths to `module.paths`.
