### ISSUE TITLE
context-menu event broken in v1.0.0 (regression)

### ISSUE THREAD

**Issue by miniak** [electron/electron#5493]
* Electron version: v1.0.0.
* Operating system: OS X 10.9

https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-context-menu is broken. Looks like a regression as it worked on a master build (version after v0.37.8, when this feature was added). It does not fire in v1.0.0.

Tested in dev console in the default app:
```
electron.remote.getCurrentWebContents().on('context-menu', function() { console.log(arguments); });
```

Also does not work in the main script.

**Comment by danhp** [comment]
This hasn't been release yet.

**Comment by miniak** [comment]
Oh, that's possible... I wonderer why are the release notes so short. So 1.0.0 is functionally equivalent to 0.37.8 except for the removal of deprecated APIs?

**Comment by miniak** [comment]
Hm, but I've checked the changes: `git diff v0.37.8..v1.0.0 docs/api`

**Comment by miniak** [comment]
In that case the documentation in v1.0.0 tag does not correspond to the functionality in v1.0.0 relase

**Comment by danhp** [comment]
https://github.com/electron/electron/blob/v1.0.1/docs/api/web-contents.md

**Comment by miniak** [comment]
The v1.0.0 tag changed... That's why :)
