### ISSUE TITLE
Any way to control how the os returns focus when electron window is closed?

### ISSUE THREAD

**Issue by aeikenberry** [electron/electron#5495]
* Electron version: 0.37.6
* Operating system: osx

If i'm in another app, and typing in an input, and I access my application via global hotkey, do my thing in my application and close it, I'd like to be returned to typing in my input. Instead, the previous app is focused, but I'd have to manually focus the input I was typing in before my app's window launched.

Is there any way to return focus in a specific way like this?

**Comment by zcbenz** [comment]
No, currently there is no way to do this with Electron's built-in APIs, Cocoa does provide APIs to do this and you find how to do it at http://stackoverflow.com/questions/13367703/cocoa-switch-focus-to-application-and-then-switch-it-back.

I suggest writing a native Node module for this, I don't think we should make it a built-in feature of Electron since it is about managing other windows.

**Comment by aeikenberry** [comment]
@zcbenz Thanks for the reply. I just wanted to make sure I wasn't missing anything.

**Comment by markbao** [comment]
@aeikenberry, did you eventually figure out a way to do this?

@zcbenz, any pointers on how one would go about writing a native Node module for this? I have good experience in Node, but not so much in Electron, and don't really know how it would be possible to interface a Node app with the Obj-C example you linked. Would it be necessary to use an ObjC/Node bridge? Willing to try, just not sure where to start. Thanks!

**Comment by aeikenberry** [comment]
@markbao No, I looked into it briefly, but didn't have the time. It seemed like you needed to hook into AppDelegate methods, but I couldn't figure out how to access that from Node/Electron.

**Comment by markbao** [comment]
@zcbenz, just following up: any pointers on how one would go about writing a native Node module for this? I have good experience in Node, but not so much in Electron, and don't really know how it would be possible to interface a Node app with the Obj-C example you linked. Would it be necessary to use an ObjC/Node bridge? Willing to try, just not sure where to start. Thanks!

**Comment by CBaptiste** [comment]
hey !
I don't know if this is still needed, but if you are on macOS, you can just write a small applescript 
like 
```
tell application "System Events"
    set activeApp to name of first application process whose frontmost is true
end tell
activate application activeApp```

this should do the trick (it did for me ;))

**Comment by markbao** [comment]
Thanks @CBaptiste! Do you run this when the Electron window closes, or do you somehow capture `activeApp` before the Electron app gets focus?

Just wondering because if you run this when the Electron window closes, I feel like `whose frontmost is true` would be the Electron app, and you'd be focusing the Electron app, right?

**Comment by CBaptiste** [comment]
On my app, I `win.hide()`and then run the script. But I guess you can `.close()`and run the script as well ! If you run it after, the `whose frontmost is true` will not be the electron app (since it is closes/hidden)

**Comment by darkyen** [comment]
Alternatively using NodObjC you can do this programmatically (for OS X)

```
import $ from 'nodobjc'; 
const appOnTop = $.NSWorkspace('sharedWorkspace')('activeApplication');
/* Do some stuff */
appOnTop('activateWithOptions')($.NSApplicationActivateIgnoringOtherApps);
```

**Comment by mishchea** [comment]
@darkyen that looks really promising, however your code snippet is missing many details and does not work as-is. Do you know what is missing?

**Comment by Eugeny** [comment]
In case someone is still looking: `Menu.sendActionToFirstResponder('hide:')` emulates `⌘-H` (Hide app), which hides the window AND gives away focus to the app below.

**Comment by duke79** [comment]
this works -

```ts
Menu.sendActionToFirstResponder('hide:');
```

https://stackoverflow.com/a/55104179/973425

**Comment by nbonamy** [comment]
I needed something a bit more subtle than `Menu.sendActionToFirstResponder('hide:');` so ended up with this. Works in my app, because I want to restore focus after executing something triggered with a `globalShortcut`. So I call `getForemostApp` on the trigger, save that "somewhere" and call `focusApp` when done.

```javascript
export type Application = {
  id: string
  name: string
  path: string
  window: string
}

async getForemostApp(): Promise<Application|null> {

    const script = `
      tell application "System Events"
        set appProcess to first application process whose frontmost is true
        set bundleID to bundle identifier of appProcess
        set appName to name of appProcess
        set appPath to POSIX path of (file of appProcess as alias)
        set winTitle to name of first window of appProcess
      end tell
      return bundleID & "<|>" & appName & "<|>" & appPath & "<|>" & winTitle
    `

    // run it
    const app = await this.runScript(script);
    const [id, name, realpath, window] = (app as string).split('<|>');
    const path = realpath
      .replace('/System/Volumes/Preboot/Cryptexes/App/System', '')
      .replace('/Volumes/Preboot/Cryptexes/App/System', '')
    return { id, name, path, window };

  }

  async focusApp(application: Application): Promise<boolean> {

    try {
      
      // check
      if (!application.id) {
        console.error('Application ID is required');
        return false
      }
      
      // now focus window
      if (application.window?.length) {

        const script = `
          tell application "System Events"
            set appProcess to first application process whose bundle identifier is "${application.id}"
            tell appProcess
              set frontmost to true
              set focusedWindow to first window whose name is "${application.window.replaceAll('"', '\\"')}"
              perform action "AXRaise" of focusedWindow
              set value of attribute "AXFocused" of focusedWindow to true
            end tell
          end tell
        `

        // run it
        await this.runScript(script);

      } else {

        const script = `
          tell application "System Events"
            set appProcess to first application process whose bundle identifier is "${application.id}"
            tell appProcess
              set frontmost to true
            end tell
          end tell
        `
        
        // run it
        await this.runScript(script);

      }

      // probably done
      return true

    } catch (error) {
      console.error('Error while focusingApp', application, error);
      return false
    }

  }


runScript(script: string) {
    return new Promise((resolve, reject) => {
      applescript.execString(script, (err: Error, rtn: any) => {
        if (err) {
          reject(err);
        } else {
          resolve(rtn);
        }
      });
    });
  }

```
