### ISSUE TITLE
Notification Icon

### ISSUE THREAD

**Issue by jonathanwiesel** [electron/electron#5497]
* Electron version: 0.36
* Operating system: Mac OS X 10.11.2

I'm new to Electron and I want to build a notification number menu bar icon. 

I was thinking on how could I add the notification number beside the icon in other platforms other than Mac OS X. Since OS X can implement `Tray.setTitle` but not other platforms.

Any ideas?

**Comment by flooooh** [comment]
In #5439 are some suggestions on how to dynamically create an icon for the tray.

**Comment by zcbenz** [comment]
Other platform do not allow native title and you have to draw it as part of the icon.
