### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by s-devaney** [electron/electron#5498]
Somebody mentioned Electron to me as a way to package web apps as desktop apps.

Great!

What I wanted to see when I loaded your website:

- Do I need to make any changes to my app, is Electron just a wrapper (package, some config and deploy) or a framework?
- A basic tutorial so I can get the jist of what Electron is

What I actually get:

- A link to a github with some example code, none of it documented or explained
- A huge array of docs

I've still got no idea if Electron does what I want it to do and I'm not going to spend an hour browsing docs to find out

**Comment by lee-dohm** [comment]
Just beneath the fold on the https://electron.atom.io website, there is a link to [watch the video](https://www.youtube.com/watch?v=8YP_nOCO-4Q&feature=youtu.be):

<img width="843" alt="screen shot 2016-05-11 at 3 05 21 pm" src="https://cloud.githubusercontent.com/assets/1038121/15198069/e29954ec-1789-11e6-8e4e-6a67efa1e7dd.png">

which explains that Electron is a framework for building native applications with the same tools you use for web applications. It also explains this just above the link to the video:

> Electron is a framework for creating native applications with web technologies like JavaScript, HTML, and CSS.

A little beneath that there is a whole section with options on how to get started:

<img width="1026" alt="screen shot 2016-05-11 at 3 07 06 pm" src="https://cloud.githubusercontent.com/assets/1038121/15198100/1b70f144-178a-11e6-861d-5a17912dedef.png">

Including:

* A link to the [API Demos app](https://github.com/electron/electron-api-demos) which has examples of what is possible with Electron and the code to achieve it
* A link to the [Quick Start app](https://github.com/electron/electron-quick-start) (which also points you to the [Quick Start tutorial](http://electron.atom.io/docs/tutorial/quick-start/)
* A link to the documentation that has numerous tutorials
* Suggestions on other resources such as Discuss, Slack, Twitter and email

I hope that gives you more resources to choose from. Let us know if you have any other questions.
