### ISSUE TITLE
Tray icon disappear after a while

### ISSUE THREAD

**Issue by ruanbarcellos** [electron/electron#5499]
When launching the app, the Tray Icon is created successfully. After a few minutes, the Tray Icon just disappear without any issue or error message.

This error does not occur on v0.37.5 and older.

* Electron versions: v0.37.6 to v1.0.1.
* Operating system: Windows 10

**Comment by zcbenz** [comment]
Please check the FAQ entry on this:
http://electron.atom.io/docs/faq/#my-apps-windowtray-disappeared-after-a-few-minutes
