### ISSUE TITLE
UPX compression issue

### ISSUE THREAD

**Issue by silverkorn** [electron/electron#5506]
* Electron version: 1.0.1
* Operating system: Windows 7 64-bit

Using the latest `electron-prebuilt` (So, I ain't sure if it's with Electron directly of their build), applying a compression with [UPX](http://upx.sourceforge.net/) v.3.91w doesn't work properly.

Though it is not guaranteed to work, passing the latest NW.js executable (0.14.5 LTS) for Windows 7 64-bit works properly with a barely visible slower start. (~60MB to ~22.5MB)

Do you plan to support this for allowing smaller disk usage?
Thank you!

**Comment by zcbenz** [comment]
Sorry but UPX is a third party thing and we don't know how to make it work with Electron.
