### ISSUE TITLE
How access data from manifest file (package.json)

### ISSUE THREAD

**Issue by jayralencar** [electron/electron#5511]
* Electron version: 1.0.1
* Operating system: Win32

Hi, I need to access the data from manifest file in a electron app.

Does anyone know how to do this?

**Comment by sindresorhus** [comment]
The [support](http://discuss.atom.io/c/electron) forum or the [Slack chat](http://atom-slack.herokuapp.com/) would be a better place to ask ;) The issue tracker is for actual issues.
