### ISSUE TITLE
Accelerator for Tab key?

### ISSUE THREAD

**Issue by BHSPitMonkey** [electron/electron#5512]
* Electron version: 1.0.1
* Operating system: Ubuntu Linux

According to the docs here, Electron Accelerators don't support the Tab key. I was hoping to bind a Ctrl+Tab keyboard shortcut to a menu item; is this a known limitation or has it just not been implemented? Thanks!

**Comment by danhp** [comment]
`Ctrl+Tab` works just fine.
See https://github.com/sindresorhus/caprine/blob/master/menu.js#L253

**Comment by BHSPitMonkey** [comment]
@danhp - Thanks for the clarification and for patching the docs. The accelerator still isn't working for me, so I'll just have to assume that my OS (Ubuntu 16.04) is eating the event before it reaches Electron (though I'm not sure for what; nothing seems to happen).
