### ISSUE TITLE
Error: Cannot find module 'shell'

### ISSUE THREAD

**Issue by lipis** [electron/electron#5514]
After updating to `1.0.1` from `37.8` I'm getting the above error when just including the `shell` or `dialog`.. Am I the only one?! I cleaned everything and reinstalled all the dependencies :)

* Electron version: 1.0.1
* Operating system: OS X

<img width="532" alt="screen shot 2016-05-12 at 23 05 59" src="https://cloud.githubusercontent.com/assets/125676/15230490/3c596d02-1896-11e6-8463-f1b5d6f1560b.png">

**Comment by mnquintana** [comment]
A lot of deprecations were removed for 1.0 – one of the things that was deprecated was `require` ing Electron-specific modules globally (ie. `const shell = require('shell')`, or `import shell from 'shell`. You'll need to update your app to import these properties from the `electron module:

```
import {shell} from 'electron';
const {shell} = require('electron');
```

Hope that helps!

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Electron message board](https://discuss.atom.io/c/electron) or the [Electron Slack channel](http://atom-slack.herokuapp.com/) is where you'll probably be able to find answers faster.

**Comment by lipis** [comment]
I have to admit I was a bit lazy with my research.. :/ Thanks @mnquintana 💃
