### ISSUE TITLE
MenuItem.checked state inconsistent in MenuItem.click handler

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#5515]
* Electron version: 0.37.8
* Operating system: All

Add a checkable `MenuItem` and a click handler for it. In the click handler, print out `MenuItem.checked`. Now try it. You'll see a pattern of:
```
true
true
false
true
true
false
```

**Comment by danhp** [comment]
I tried to debug this but couldn't reproduce this in `v1.0.2`
Not sure if we had the same code.

```
const menu = new Menu();
menu.append(new MenuItem(
  {
    label: 'Test',
    type: 'checkbox',
    click(item, win) {
      console.log(item.checked)
    }
  }
));
```

**Comment by kevinsawicki** [comment]
@CharlieHess are you still seeing issue? Could you provide a code sample if you are? Thanks.

**Comment by zcbenz** [comment]
Closing until more information is provided.
