### ISSUE TITLE
Lagging when playing video with JS (Raspberry Pi2)

### ISSUE THREAD

**Issue by goktugerce** [electron/electron#5516]
* Electron version: 0.37.5
* Operating system: Raspberry Jessie on Raspberry Pi2

I have a simple application with slider that shows images or videos. It's working without a problem on my Ubuntu 16.04. I use [Slick](http://kenwheeler.github.io/slick/) as slider and [Video.js](http://videojs.com/) as video player. When I run the application on Raspberry Pi2, HD videos are lagging (or maybe the app is slow in general).

I asked the reason to somebody on their forum, and the response is:

> and its well known that without GPU help the CPU of the PI is far too slow to decode such content! Modify the Electron runtime (Webkit ?? ) gstreamer pipelines to include gst-omx. AFAIK Electron is based on Chromium/Webkit , and Webkit uses gstreamer for multimedia on Linux.

Is this a viable thing to do? If so, how can I do it?

**Comment by gabrielaraujof** [comment]
The same with me. I also have an application with slides for videos and images that is intended to run on the Pi2 and Pi3. However, my stack is a little bit different, including AngularJS and some custom directives.

My application also runs fine in linux x86 and x64 versions, although on the RPi the **videos (with any resolution) becomes oddly lagged**. As @goktugerce has posed, I also learned that Pi's GPU is accessed via OpenMAX API but somehow the built-in browser on electron does not seem to take advantage on that, instead relying only on the CPU for decoding.

Any help would be great. *Is there any chance that electron could support this in a near future?*
Even if not, anyone could help me to build a customized version with this support?

**Comment by zcbenz** [comment]
Unfortunately Chromium doesn't implement video acceleration for the hardware used by Raspberry Pi, I would like to fix this, but the work would be really huge, and none of us in Electron actually knows how to do that.

I suggest opening an issue at Chromium's [issues list](https://crbug.com) instead, I'm closing this since it is an upstream issue, and we are not able to fix it on Electron's side.

**Comment by kristjanmik** [comment]
@goktugerce @gabrielaraujof did you manage to find a solution elsewhere?

**Comment by jujubetz** [comment]
Same issue here, @goktugerce @gabrielaraujof  @kristjanmik , any update on some solution/workaround ?

**Comment by elboletaire** [comment]
This is really annoying... playing a video in chromium with my raspberry PI 3 works perfectly (played 1080p videos directly from youtube). But when doing exactly the same in electron, it's absolutely glitchy.

I even tried creating a really simple app just with an embed of youtube, which is less glitchy than my main app, but still glitchy compared to the chromium installed in raspbian.

Isn't there any flag to enable "gpu" video acceleration or something? I can't understand why does not work here in electron and it works perfectly in chromium when browsing websites.

**Comment by jujubetz** [comment]
@elboletaire 

We solved our problem building an Electron app that calls OMXPLAYER when we need to play youtube videos. HTML5 videos on Rasp2/3 sux :(

**Comment by elboletaire** [comment]
Ouch 😢

**Comment by MStylesMS** [comment]
Would @jujubetz be willing to share his electron app to call omxplayer?  :)

**Comment by jujubetz** [comment]
@MStylesMS aw, sorry :( it is proprietary code for now.. But we are thinking about making it public. Ill let you know.

**Comment by MStylesMS** [comment]
Awe bummer!  But thanks for at least sharing that there is a solution.  :-) 

Please let me know if you release it anytime soon.

**Comment by Controlhaus** [comment]
This project works well to control omxplayergui from node https://github.com/Ap0c/node-omxplayer
