### ISSUE TITLE
Cannot find module 'app'

### ISSUE THREAD

**Issue by paul321** [electron/electron#5517]
* Electron version: 1.0.2
* Operating system: Win x64, OSX

Just updated from 0.37.8 to 1.0.0 and 1.0.2 and i get the error:

Error: cannot find module 'app'

This happens in the first line of the app in index.js which is 
var app = require('app');

**Comment by felixrieseberg** [comment]
```
var app = require('electron').app;
```

Or, if you want to be fancy

```
const {app} = require('electron')
```
