### ISSUE TITLE
Module loading broken in e2e tests with protractor / angular

### ISSUE THREAD

**Issue by kieronbrowne** [electron/electron#5520]
* Electron version: >=0.37 (inc. 1.0.2)
* Operating system: Ubuntu and Windows

I have managed to configure the Angular end-to-end testing tool Protractor to work with an Angular app running in Electron. A skeleton project can be seen here: https://github.com/kieronbrowne/electron-angular-protractor.git. This has been working fine up to version 0.36 of Electron.

Since Electron v0.37.x and including 1.0.x, 'require' (or nodeRequire - as I have followed the advice in the Electron FAQ about conflicts with Angular's require) has stopped finding the node modules during protractor tests.

If I output `__dirname` from the browser, I get `<appDir>/node_modules/electron-prebuilt/dist/resources/electron.asar/renderer`, when I expected to get my application directory, which is what I get when the application is run directly in Electron.

To reproduce:
1. Clone the git repository above
2. `npm install`
3. `./node_modules/electron_prebuilt/dist/electron .` to see standard behaviour (hello world displayed)
4. `npm run protractor` to see protractor working normally (this is Electron-v0.36.12). Note the __dirname output is the app directory.
5. Switch to the 'dirname-bug' branch (which just has electron-prebuilt bumped to v1.0 in package.json)
6. `npm install` to take the newer Electron
7. Repeat step 3 (which works ok), and step 4 (which will fail - unable to load 'lodash').

**Comment by zcbenz** [comment]
The `__dirname` is only set to the file's location when the it is loaded with `file://`, otherwise it is impossible to figure out where in filesystem the file is located. In your case I suggest manually push the path of your app to `module.paths`.

**Comment by kieronbrowne** [comment]
Thanks for your response. I've added some code in the browser index.html to grab the app/node_modules path via IPC and append it to `module.globalPaths`. This fixes my issue.

I just wanted to point out that this example does use `file://` throughout though:

- Protractor starts electron, which loads `file://[projectDir]/app/index.html`.
- It then loads the reset page, which is configured to be another file url: `file://[projectDir]/e2e-tests/reset.html`.
- And finally, it executes a javascript `window.location.replace("file://[projectDir]/e2e-tests/../app/index.html?test=protractor");`

And when the final page is loaded, it has lost its directory.

Just running this directly doesn't trigger the problem though. It has to be via the selenium driver.
