### ISSUE TITLE
White screen when starting app

### ISSUE THREAD

**Issue by Darkneon** [electron/electron#5521]
* Electron version: 0.37.6
* Operating system: Windows 8.1

We are observing that sometimes when we start our application we get a white screen. The dev tools are in an unusable state. It seems like chromium crashed or didn't load. 

![white-screen-windows](https://cloud.githubusercontent.com/assets/654727/15258297/c922a604-1918-11e6-8439-18df5414a8f4.png)

Here's a log with ELECTRON_ENABLE_LOGGING=true
[white-screen-log.txt](https://github.com/electron/electron/files/263904/white-screen-log.txt)

For comparison, here's a log when the application starts successfully
[success.txt](https://github.com/electron/electron/files/263891/success.txt)

Any ideas what could be going on or how we can investigate the issue further?

**Comment by zcbenz** [comment]
I can't see anything weird from the log, and the renderer process doesn't seem to have crashed, otherwise the devtools would have reported that.

It is probably because some code in your app is blocking when loading the page.

**Comment by Darkneon** [comment]
Thanks, so after going through the code again, we identified a potential race condition that could have caused it.

Fix is done, I'll see if we still get it.
