### ISSUE TITLE
Paste role does not handle image data from clipboard

### ISSUE THREAD

**Issue by BHSPitMonkey** [electron/electron#5523]
* Electron version: 1.0.1
* Operating system: Ubuntu 16.04

Several web sites natively allow you to paste image data from your clipboard (Imgur, chat clients like HipChat, etc.), by handling Ctrl+V events and using the Clipboard API.

This functionality works in an Electron window as well. However, if I implement a menu with an item using `role: 'paste'` (and a `'CmdOrCtrl+V'` accelerator), Electron intercepts the keypress and its paste implementation does not seem to forward the image data to the page as expected.

My workaround for now is to remove the Paste item from my window menu, letting the page itself handle it. It would be nice if Electron's paste implementation could handle this data and present it to the page.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem? I'm unable to reproduce with following steps:

1. Copy some image to clipboard in Chrome
2. Open electron's default app
3. Navigate to http://jsfiddle.net/KJW4E/754/
4. Paste image

**Comment by BHSPitMonkey** [comment]
Upon closer inspection, this might be specific to how HipChat tries to handle pastes; this is not affecting imgur and the jsfiddle you linked. Closing.
