### ISSUE TITLE
Cannot play flv inside a video tag?

### ISSUE THREAD

**Issue by Zzzen** [electron/electron#5527]
* Electron version: 1.0.1
* Operating system: Win10 64
When I set `src` to a local flv file, nothing happend.
```
<body>
    <video src="file://D:/1.flv" />
</body>
```
I have tried to set `src` to `file://D:/2.avi`, and it worked.

**Comment by MarshallOfSound** [comment]
The HTML5 Video element does not support `.flv` elements in ANY browser.  These are the only formats supported by the HTML5 spec.
> WebM video format
> MPEG-4/H.264 video format
> Ogg/Theora video format
> WebVTT - Web Video Text Tracks

Check it out here http://caniuse.com/#feat=video

`.flv` literally stands for Flash Video so it's not suprising the HTML5 standard doesn't support it.  If you need to play `.flv` videos you can use something like `video.js` or JWPlayer

**Comment by zcbenz** [comment]
Thank @MarshallOfSound for answering it, I'm closing this now.
