### ISSUE TITLE
In v1.1.0 app can not be started due to vcruntime140.dll is missing

### ISSUE THREAD

**Issue by webarchymeta** [electron/electron#5528]
* Electron version: 1.1.0
* Operating system: Windows 7

The system does not have visual studio 2015 installed

**Comment by MarshallOfSound** [comment]
What app?
Using what modules?

**Comment by jack1243star** [comment]
Similar issue on Windows 8.1 with missing `msvcp140.dll`, perhaps older versions of the `*120.dll` libraries should be replaced?

**Comment by MarshallOfSound** [comment]
This doesn't occur for me but I assume that is due to me having VS2013 and VS2015 installed and on my path so the DLL is being sourced from there.

**Comment by MarshallOfSound** [comment]
To assist someone with fixing this bug, this is the line that appears to fetch the `*120.dll` files

https://github.com/electron/electron/blob/master/script/update-external-binaries.py#L33

**Comment by blushmoon** [comment]
try to install vc++  
https://www.microsoft.com/zh-tw/download/details.aspx?id=48145

**Comment by webarchymeta** [comment]
yes, i know. I was just reporting a bug since electron will be used in apps that are used by others and the users are not suppose to know that

**Comment by kaepora** [comment]
Be careful, `electron-packager` still links to `*120.dll` libraries. This needs to be fixed still.

**Comment by coelho-extremosistemas** [comment]
Hi.... after install Visual C++ Redistributable 2015, I get this error:
api-ms-win-crt-runtime-l1-1-0.dll not found

**Comment by soichih** [comment]
Same here. I had to downgrade electron-packager to 1.0.1..

**Comment by coelho-extremosistemas** [comment]
This a piece of my package.json
```
  "devDependencies": {
    "electron-packager": "^7.0.1",
    "electron-prebuilt": "^1.0.1"
  }
```
electron-packager: 1.0.1, really?

**Comment by premierfx** [comment]
These two zip files will help for resolve the issue with electron for win32 v1.1.0:
**https://github.com/atom/atom-shell-frameworks/releases/download/v1.0.0/vs2015-crt-x64.zip**
**https://github.com/atom/atom-shell-frameworks/releases/download/v1.0.0/vs2015-crt-ia32.zip**

**Comment by coelho-extremosistemas** [comment]
Hi @premierfx, I extract vs2015-crt-x64.zip into the root folder of electron, and get the same error.
api-ms-win-crt-runtime-l1-1-0.dll not found.
This fonder was create with electron-packager 7.0.2

**Comment by boxertech** [comment]
Same.  I get the api-ms-win-crt-runtime-l1-1-0.dll error after adding the msvcp140 and other ddl's from above zip.

**Comment by tomzx** [comment]
@zcbenz What is the release cycle of electron? When can we expect this fix to be part of a tagged release?

Thanks!

**Comment by facekapow** [comment]
I'm also having this issue on my app (which needs to be cross-platform) and I'm wondering when the fix will show up in the next electron-prebuilt. Anything?

**Comment by zcbenz** [comment]
I'm reopening this issue since Visual Studio 2015 is also linking with a bunch of Windows 10 CRT libraries like `api-ms-win-crt-runtime-l1-1-0.dll`.

**Comment by premierfx** [comment]
The error with msvcp140. What need to do just extract the zip to build folder where is your new build  myproject.exe file and run it. The error will gone.
