### ISSUE TITLE
cmd-w doesn't close windows on mac after packaging app

### ISSUE THREAD

**Issue by Joorge** [electron/electron#5536]
* Electron version: 1.0.1
* Operating system: OS X 10.11.2

After using electron-packager@7.0.1 **cmd-w** doesn't close windows on mac, you have to click the red circle to close the window. However, it works when you execute the app with **electron .**

**Comment by zcbenz** [comment]
The Cmd-W only works when you have application menu in your app. When you run your app via the default app, a default application menu will be assigned, but it be gone after you packaged your app.
