### ISSUE TITLE
systemPreferences.subscribeNotification should pass the notification to the callback

### ISSUE THREAD

**Issue by johndbritton** [electron/electron#5543]
I'm using `electron.systemPreferences.subscribeNotification` to listen for events coming from `NSDistributedNotificationCenter` in my app:

```js
prefs.subscribeNotification('com.app.name.EventName', function(notification){
  console.log(notification)
})
```

This produces a single line of output in my log every time the event happens on my system, the only trouble is that the output is `undefined`. My expectation is that I would have access to the `NSNotification` object metadata as JSON.

When I subscribe to this notification in an Objective-C app, I get metadata with the event

```obj-c
<0x618000000750>-[AppDelegate notify:]: object: com.app.name name: com.app.name.EventName userInfo: {
    Key = Value;
    ...
}
```

**Comment by johndbritton** [comment]
When observing `NSDistributedNotificationCenter` our selector is called and passed an `NSNotification` object whenever a notification that we're observing occurs.

`NSNotification` has a `userInfo` method that returns a dictionary of metadata for the notification, that's what I'd like to be able to get access to.

**Comment by johndbritton** [comment]
@zcbenz is this something likely to be implemented soon or should I take a different path in my app?

**Comment by paulcbetts** [comment]
@johndbritton I don't think anyone is working on it, you could probably reuse the NSDictionary to V8 stuff from #5352 to implement it

**Comment by johndbritton** [comment]
Will give it a try using that example @paulcbetts. Are there any architectural docs that describe how working with native code works? I looked around but didn't find anything that made it clear to me, if not that PR might be enough context for me.

**Comment by zcbenz** [comment]
@johndbritton I will give it a try today.
