### ISSUE TITLE
converting a long base64 string to buffer whitescreen crashes the renderer 

### ISSUE THREAD

**Issue by dominictarr** [electron/electron#5544]
* Electron version: 0.4.0
* Operating system: ubuntu 15.10

when converting a base64 string that will be longer than about 3k the render process crashes suddenly with no output.

however, the following code works without crashing!

``` js
function base64ToBuffer(s) {
  var l = s.length * 6 / 8
  if(s[s.length - 2] == '=')
    l = l - 2
  else
  if(s[s.length - 1] == '=')
    l = l - 1

  var b = new Buffer(l)
  b.write(s, 'base64')
  return b
}
```
script to reproduce here: https://gist.github.com/dominictarr/1960025225218426984cbb6428a88a47

**Comment by zcbenz** [comment]
This was an old bug and got fixed in v0.37.5.
