### ISSUE TITLE
import electron from "electron"

### ISSUE THREAD

**Issue by fab1an** [electron/electron#5548]
I want to use `babel` with electron. At the moment I'm using the require hook, which means starting electron with this file:

`require('babel-register');
require('./main.js');
`

This works fine, but when I ship my app, I want to do the transpiling before hand. Unfortunately trying to transpile it gives me "electron" module not found.

* Electron version: 1.1.0
* Operating system: MacOSX

**Comment by mnquintana** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Electron message board](https://discuss.atom.io/c/electron) or the [Electron Slack channel](http://atom-slack.herokuapp.com/) is where you'll probably be able to find answers faster.
