### ISSUE TITLE
API description / WebIDL

### ISSUE THREAD

**Issue by tong** [electron/electron#5549]
Does the project provide some sort of API description we can use to auto generate the required type definitions for compile-to-js languages like haxe (fponticelli/hxelectron#17), typescript, dart, ... ?
(Like atom-api.json for the atom editor or webidl files)

**Comment by zcbenz** [comment]
I'm merging this to #3375.

**Comment by zeke** [comment]
Work in progress: https://github.com/electron/electron/pull/6408
