### ISSUE TITLE
Widevine DRM not working on Windows 10

### ISSUE THREAD

**Issue by jbleuzen** [electron/electron#5550]
Electron v1.1.0
Windows 10
widevine-cdm-version 1.4.8.885

We actually use Electron v0.36.12 for our application using WidevineCDM, it working with "Widevine 1.4.8.866".

With both 0.37.* & 1.* we can't play video on Windows ONLY. If I read the docs [using widevine plugins](https://github.com/electron/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md) and try to play a video on the site of bitdash, I end up having the plugin loaded but with the error : "DRM:Failed to create and initialize a MediaKeys object".
I updated the version of widevine to "1.4.8.885" to match the version in Google Chrome, but it doesn't work.

![sans titre](https://cloud.githubusercontent.com/assets/280681/15291841/4b14bcce-1b80-11e6-89b7-122d39d6366e.png)

I made a repository showing the error I'm encountering : [electron-widevine-test (branch : electron-1.0.0)](https://github.com/jbleuzen/electron-widevine-test/tree/electron-1.1.0)

For info, this is working correctly on OSX, not tested on Linux.

**Comment by zcbenz** [comment]
The version of widevine plugin doesn't matter, what really maters is the version of Chrome has to match Electron. So in order to make widevine work for Electron v1.1.0, you have to copy the plugin files from Chrome 50.0.2661.102.

You can try following files which were copied from Chrome 50.0.2661.102: [Archive.zip](https://github.com/electron/electron/files/267165/Archive.zip).

**Comment by jbleuzen** [comment]
That's what I did... And comparing the files in my `\AppData\Local\Google\Chrome\User Data\WidevineCDM\1.4.8.885\_platform_specific\win_x86` and the archive you sent, I don't have the same file... And I'm sure that I have the same Chrome version that I have in Electron...

Thanks anyway !

**Comment by yohaia** [comment]
Hello,

Using **electron-v1.6.6-win32-x64** with **Chrome Version 58.0.3029.81 (64-bit)** on **Windows 10 64Bit**

I have the same issue:
The plugin is loaded:
The Bitmovin player uses widevine in your browser (Chrome 56)

But when try to play i am getting:
DRM: Failed to create and initialize a MediaKeys object

Did someone was able to resolve this?

**Comment by yohaia** [comment]
I will response to my own question, 
When using the right Chrome browser - its works.

**Comment by vanminhquangtri** [comment]
@yohaia , I am getting the same problem. Can you please advise me how to check if I use the right Chrome version?
Thank you.
