### ISSUE TITLE
Add support for --disable-http2 command line option

### ISSUE THREAD

**Issue by dlmanning** [electron/electron#5555]
* Electron version: 1.1.0
* Operating system: OS X and Windows
* What am I doing that's causing an issue: Attempting to negotiate OpenID Connect authentication using Windows NTLM as an identity provider (wasn't my idea).

TL;DR: http2 is incompatible with NTLM auth, and Electron seems to not fall back to http 1.1 correctly when the NTLM auth challenge happens at the end of a series of 302s. (The NTLM challenge happens in the last request)

So one gets this:
![image](https://cloud.githubusercontent.com/assets/2949092/15308542/80268646-1b93-11e6-9712-ee8618665220.png)

Instead of this:
![image](https://cloud.githubusercontent.com/assets/2949092/15308610/055093b6-1b94-11e6-89a2-681b6507bde9.png)

Chrome/Chromium exhibits the same behavior upon the first request to such a resource. Fixing it is probably hard, and probably NTLM's fault anyway. However, the process works in HTTP 1.1. Chromium has a `--disable-http2` flag, and I think enabling it in Electron would only require one or two line patches to both electron and brightray.

**Comment by paulcbetts** [comment]
@dlmanning Can you file this bug upstream? It's obscure, but at least if it's filed Chrome might fix it in the future

**Comment by dlmanning** [comment]
@paulcbetts : yeah, I'll make a report. Who knows, right? (Honestly, I'm not sure NTLM even deserves to be fixed)

**Comment by gaving** [comment]
From 4 years in the future (almost to the day), thank you both for fixing this as it's burned me in a corporate environment big time trying to wrap an Electron app.

Adding this flag sorted it out! ❤️ 👍 🥳
