### ISSUE TITLE
Menu: possible to use OSX native Font and Text menus?

### ISSUE THREAD

**Issue by masonicboom** [electron/electron#5556]
* Electron version: v1.0.1
* Operating system: OSX 10.11.4

Is there some way to use the OSX Font and Text menus (see screenshots) like the other "standard menus" described at https://github.com/electron/electron/blob/master/docs/api/menu.md#standard-menus?

If not, can someone point me in the right direction to implement this?

*Text menu*
![text menu](https://cloud.githubusercontent.com/assets/86958/15312727/6485fc64-1bbb-11e6-9621-fa726f91e7ae.png)

*Font menu*
![font menu](https://cloud.githubusercontent.com/assets/86958/15312728/64a37b90-1bbb-11e6-9eb6-c2854f1418d2.png)

**Comment by zcbenz** [comment]
Unfortunately there is no stock Font and Text menus in Electron, they are only meaningful for text editors, while Chromium is a browser and renders everything itself.
