### ISSUE TITLE
Install electron on a ARMv8 x64

### ISSUE THREAD

**Issue by djsunrise19** [electron/electron#5558]
* Electron version: 1.0.2
* Operating system: Odroid C2 with Ubuntu 16.04 LTS (v1.1) -> File name : ubuntu64-16.04lts-mate-odroid-c2-20160226.img.xz

ERR with npm install for electron 1.0.2. It seems, that there is no prebuild on this platform. Any chance to fix that?

![image](https://cloud.githubusercontent.com/assets/14234570/15315263/c6c51bac-1c16-11e6-8a3b-1cd18ca59167.png)

**Comment by zcbenz** [comment]
Unfortunately we don't have support for ARMv8 yet, I'm merging this to #259.
