### ISSUE TITLE
Prevent window from closing on Cmd + W

### ISSUE THREAD

**Issue by parisk** [electron/electron#5563]
Hi, I am building a desktop app with Electron and I am using `electron-prebuit` in development.

My issue is that I would like to use the <kbd>⌘</kbd> + <kbd>W</kbd> shortcut (on my Mac)..

This does not happen in the built version of my app though. Happens only in development.

I mentioned this in electron-userland/electron-prebuilt#129, but I was prompted to mention in here actually.

**Comment by danhp** [comment]
Duplicate of #5536. See that one for more details.

**Comment by parisk** [comment]
🆒 

This clears things up. Thanks!
