### ISSUE TITLE
Support Handoff fallback to website

### ISSUE THREAD

**Issue by dasilvacontin** [electron/electron#5566]
From https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/Handoff/AdoptingHandoff/AdoptingHandoff.html#//apple_ref/doc/uid/TP40014338-CH2-SW19:

> When using a native app on the originating device, the user may want to continue the activity on another device that does not have a corresponding native app. If there is a web page that corresponds to the activity, it can still be handed off. For example, video library apps enable users to browse movies available for viewing, and mail apps enable users to read and compose email, and in many cases users can do the same activity though a web-page interface. In this case, the native app knows the URL for the web interface, possibly including syntax designating a particular video being browsed or message being read. **So, when the native app creates the NSUserActivity object, it sets the webpageURL property, and if the receiving device doesn't have an app that supports the user activity’s activityType, it can resume the activity in the default web-browser of the continuing platform.** :heart:

You can read more about the property at: https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSUserActivity_Class/index.html#//apple_ref/occ/cl/NSUserActivity/

**Comment by dasilvacontin** [comment]
Maybe add support for a more detailed definition that allows the possibility of implementing the rest of `NSUserActivity`'s properties in the future, if anyone ever needs them.

```js
app.setUserActivity({
  activityType: 'in.dasilvacont.ludumpad.gamepad',
  userInfo: {
    id: app.id,
    icon: app.icon
  },
  webpageURL: server.address
})
```

**Comment by dasilvacontin** [comment]
If you settle on an API / new function declaration, I'd be willing / interested in giving this issue a shot. Cheers!

**Comment by dasilvacontin** [comment]
@zcbenz Should it support two signatures, eg:

```js
setUserActivity(activityType : string, userInfo : Object)
setUserActivity(properties : Object)
```

or what solution do you have in mind?

**Comment by danhp** [comment]
We could probably get by having the `webpageURL` be an optional argument.

**Comment by zcbenz** [comment]
Yeah adding a new argument would be the easiest way.

**Comment by dasilvacontin** [comment]
Okay. I guess that if more people request props they can just do something similar to what I suggested above. Or add another optional argument.

**Comment by danhp** [comment]
I'll try to give it a crack tomorrow.
