### ISSUE TITLE
Problem when C++ Redistributable for Visual Studio 2015 is not installed

### ISSUE THREAD

**Issue by rodryquintero** [electron/electron#5568]
* Electron version: 1.1.0
* Operating system: Windows 7

----------------------------------------------
Check that Visual [C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) is installed. This affects the "quick start" boilerplate's `npm start` command.

Check [https://github.com/electron/electron-quick-start/issues/55](https://github.com/electron/electron-quick-start/issues/55) for more information.

**Comment by felixrieseberg** [comment]
See https://github.com/electron/electron/pull/5538. This is already fixed and will be in 1.1.1 (or whatever the next release will be).

**Comment by rodryquintero** [comment]
Ok, good. It took me two days to come across the solution though. This issue can help people with the same problem until the new version is released.

Thanks.
