### ISSUE TITLE
Open external program with arguments

### ISSUE THREAD

**Issue by isvaljek** [electron/electron#5569]
* Electron version: 1.1.0
* Operating system: Windows 10 Pro x64

I'm trying to call FileZilla and pass the arguments separated by space, but it fails even though the function returns true,

`require('electron').shell.openExternal('"C:\\Program Files\\FileZilla FTP Client\\filezilla.exe"' + ' "'+ conn.file_protocol+'://'+conn.user_name+':'+conn.password+'@'+conn.host_name+':'+conn.port_number+'"')`

The same string that I'm passing to openExternal works fine when pasted into windows command prompt.

**Comment by paulcbetts** [comment]
You probably can just use `child_process.spawn` for that

**Comment by isvaljek** [comment]
Thanks, I found the same 10 minutes after, sorry for the noise.
