### ISSUE TITLE
Silent Print Options, there is no way to select a printer except default?

### ISSUE THREAD

**Issue by bachmay** [electron/electron#5572]
- Electron version: Latest
- Operating system: OSX 10.11.4

How can I print silently but also pick a printer through the API options?

Thanks.

**Comment by zcbenz** [comment]
Currently there is no API for that.

**Comment by jochenonline** [comment]
Is there any other chance to do what @bachmay wants (and not only with OSX, but Windows too)? How probable is it, that there will be a solution for that in the (near) future?

**Comment by startupfoundry** [comment]
I'm also interested in this.

**Comment by zcbenz** [comment]
I'm merging this to #7849 since it is a superset of this issue.

**Comment by virendra038** [comment]
Hello guys , just wanted to know if the deviceName parameter is working in contents.print({deviceName:''});
