### ISSUE TITLE
Allow dialogs to be cancelled

### ISSUE THREAD

**Issue by 50Wliu** [electron/electron#5577]
- Electron version: 1.1.0
- Operating system: N/A

Currently there isn't any way to remove dialog boxes (such as ones created through `dialog.showMessageBox`).  This can be useful in, for example, "Keep Waiting" dialogs.  After the window becomes responsive again it would be great if we could programmatically close the dialog.

**Comment by jakubzitny** [comment]
This would also be useful e.g. when user opens a dialog and returns to the app and changes stuff (context) which makes the dialog unneccessary. From the app it'd make sense to cancel the dialog.

**Comment by sante85** [comment]
up

**Comment by sante85** [comment]
Please, could you tell me which component to modify to solve the problem?

Best Regards

**Comment by codebytere** [comment]
Closing due to abandonment.

**Comment by sagiegurari** [comment]
What kind of resolution is this? This is one of the annoying behaviours in atom and I hoped for a fix.

**Comment by codebytere** [comment]
We're weeding out abandoned issues right now; if you'd like this issue to remain open & think it's an important fix that's totally fine and i'll reopen it :)

**Comment by sagiegurari** [comment]
Yes please. First time boot is slow and this dialog hurts the useability

**Comment by codebytere** [comment]
I'll see if i can take a look at this soon and work on a fix!

**Comment by Ben3eeE** [comment]
:+1: on getting this fixed. Moving to an async dialog that we can programmatically close once Atom is responsive again would be great.

**Comment by 50Wliu** [comment]
@codebytere have you maybe looked into using [probot/stale](https://github.com/probot/stale)?  It's definitely helped the Atom organization clean up a lot of old issues, and you can configure it to give a warning message in advance so that it's not as surprising when it does close the issue.

**Comment by thisisgabe** [comment]
Any update on this? I'm working on an "auto-logoff" feature that changes windows once the user has been idle for a certain amount of time. I display a warning message box 30 seconds before I switch back to the login window but I would like to close that message box once I go back to the login page (if the user doesn't return from idle).

**Comment by bpasham** [comment]
this is a super important feature. I am looking for a "timeout" option on dialogs. The dialog should automatically close if no response for 30s or so. I build apps for publicly visible unattended scenarios, and automatic dialog closing is extremely important.... thanks

**Comment by renambot-uic** [comment]
Any hope to be fixed in v2 ?

**Comment by tcanusso** [comment]
It's been 2 years since this was opened, and a whole lot of issues referencing it. Any progress made? Or was it abandoned?

I'm currently having trouble testing dialogs. To put anyone who reads this in context, my app loads the file selected by the user from the filesystem and generates some html using React. Without the programmatic way to interact with the dialog, I can't test it, meaning I have to manually click and select the file (which hurts a lot, because I intended to automate my tests). I tried using [electron-mocha](https://github.com/jprichardson/electron-mocha) and [electron-test-utils](https://github.com/MarshallOfSound/electron-test-utils) with [spectron](https://github.com/electron/spectron), but failed due to not being able to run my tests. Plain mocha works just fine, but again, I can't interact with the dialog.

Any suggestions are more than welcome!

**Comment by jrj2211** [comment]
I too am looking for this feature. For example, I have a button for saving a file. If the user goes back to the application without closing out of the dialog and forget they had already clicked the "Save" button, clicking it again will either:
- open a brand new dialog without closing the old one
- not refocus the the dialog that was already opened (done by storing the state when the user initially opens the dialog to only allow the save dialog to be opened once)

Would be great if a callback is provided, to return a reference to the dialog object with functions to close or refocus the dialog box. If the dialog isn't used asynchronously then it could still return the filenames like it does now.

**Comment by HaulinOats** [comment]
I'm guessing this has been abandoned? I was hoping to avoid the extra footwork of setting up IPC processes for managing dialog boxes with timeouts.

**Comment by miniak** [comment]
Electron is an open-source project with limited resources. You can always create a PR contributing this feature.

**Comment by HaulinOats** [comment]
I apologize. Really didn't mean to come off as ungrateful as I know open source projects like this are completely community driven and not funded by anyone. I appreciate the work people like you put into these kinds of projects and sorry for coming off as rude.

I plan to give back by opening a PR on this soon when I get some time.

**Comment by pushkin-** [comment]
Has anyone successfully worked around this by, for example, firing off a custom Esc keypress event to close the dialog? I personally haven't gotten that to work, but I haven't tried everything.

**Comment by belloyang** [comment]
I came across this issue and I figured out a way to workaround it. 
Electron actually already provides APIs that allow users to attach BowserWindow with the dialog such as `showMessageBox` and `showOpenDialog`, etc. : https://www.electronjs.org/docs/api/dialog
Once we have passed a remote BrowserWindow to the function to launch the dialog, we have reference to the BrowserWindow and therefore we can programatically call the methods close() or destroy() of the BrowserWindow to close the dialog.
Hope that help.

**Comment by nuryagdym** [comment]
@belloyang 's solution did not work on electron v3.1 
destroying or closing browser window did close messag box.

**Comment by WasabiThumb** [comment]
It looks like this is really close to happening. Only thing is that switching to the bleeding edge version of electron doesn't work for everyone, so for now
`
// Make a new message box and close after 5 seconds
function tempBox(options){
     return new Promise((resolve, reject) => {
          const slave = new BrowserWindow({width: 1, height: 1, show: false});
          var resolved = false;
          const btn = dialog.showMessageBox(slave, options).then((index) => {
               resolved = true;
               resolve(index);
          });
          await new Promise((res) => setTimeout(res, 5000));
          slave.close();
          if (!resolved) reject();
     });
}
`
Thanks to @belloyang

**Comment by muety** [comment]
Would be awesome to have this fixed! :)

**Comment by Mazin-Roushdy** [comment]
Hi @berkon, I have tried this solution and the popup window doesn't close like the abort signal doesn't reach it....this is my code and it's simple as you see : 
`var ac = new AbortController();
    var options1 = {
        type: window_type,
        title: window_title,
        message: message,
        buttons: buttons,
        signal: ac.signal
    }

    dialog.showMessageBox(options = options1)

    ac.abort();
    console.log(ac.signal.aborted);`
    
can you kindly tell me what I am doing wrong ? I am using **nodejs 14.15.0** and **electron 1.12.4**

**Comment by berkon** [comment]
@Mazin-Roushdy, some things you should check:

- The Electron version you mentioned 1.12.4 does not exist. I tried 12.0.0 and also 16.0.0. Both work fine.
- Did you put the code in the main process? It doesn't work in the renderer process!
- You are creating the message box asynchronously (which is correct/required for this case) but you are also cancelling it immediately! This means that you cancel it before it might have been created properly. I'd put the ac.abort() into a setTimeout() and delay it for a few seconds which will be required anyway for the user to have enough time to read it.

**Comment by Mazin-Roushdy** [comment]
Hi @berkon , thanks very much for you help...regarding your points : 

- you're right I got it wrong first time, my electron version is **10.1.5**
- that's actually the main mistake I have put my function in the renderer process not my main process thanks for this tip
- yes I was creating and deleting it immediately just to test the **abortSignal** feature it won't be like that in my app

I really appreciate your help...have a good day.

**Comment by nornagon** [comment]
Closing this as this is now implemented as the `signal` parameter to `dialog.showMessageBox`.

**Comment by berkon** [comment]
@kavitha-animaker, I don't understand what exactly you are trying to do. Please provide more details. Is your issue related to cancelling the popup? To me it sounds more like you can't open the popup. So I'd suggest to open a new issue.
