### ISSUE TITLE
remote app.commandLine.appendSwitch('proxy-server', '') is not ok

### ISSUE THREAD

**Issue by falconyue** [electron/electron#5579]
* Electron version:1.1.0
* Operating system:mac os x
in render process (html), i write below code:
`const {remote} = require('electron');
  const app = remote.app;
  app.commandLine.appendSwitch('proxy-server', 'xxx');` 
the proxy server is not ok, why?
`<webview id="foo" src="http://www.ip138.com" plugins></webview>`

**Comment by jprichardson** [comment]
I believe the command line switches must be added before `app.on('ready'`... so since you're calling from `remote`, this would imply the `renderer` process and thus, app.on('ready', ...)` has already fired.

**Comment by falconyue** [comment]
yes, i think so too, is there any method to refrush app's setting, then the proxy-server will be effected.

**Comment by zcbenz** [comment]
You can use the `session.setProxy` API if you want to change it dynamically.
