### ISSUE TITLE
Cann't set window icon

### ISSUE THREAD

**Issue by hon** [electron/electron#5581]
* Electron version: 0.37.8
* Operating system:win10(64)

I set the window icon with this
```es6
let img = nativeImage.createFromPath('build/icon.png')
mainWindow = new BrowserWindow({
  //... other stuff,
  icon: img
})
```
It works when I run 'electron ./app', But after I build a installer and installed, the window icon is another one(not the electron icon either).

**Comment by zcbenz** [comment]
You can try creating icon from absolute path, using relative path would make the actual icon depend on current working directory.

**Comment by hon** [comment]
I tried to set the path to a file server, but dose not work either.

**Comment by hovancik** [comment]
@hon 
this works for me on Linux: 
```
icon: `${__dirname}/images/stretchly_18x18.png`,
```
