### ISSUE TITLE
Why electron-rebuild.cmd return an empty result

### ISSUE THREAD

**Issue by mydansun** [electron/electron#5583]
At First I executed  `npm install jquery --save`

And then I run `.\node_modules\.bin\electron-rebuild.cmd`

But the program show an empty result

```
E:\Desktop\PROJECT\Electron\w>.\node_modules\.bin\electron-rebuild.cmd

E:\Desktop\PROJECT\Electron\w>
```

My packager script is `electron-packager . launcher --platform=win32 --arch=x64 --version=1.0.0 --out=dist/ --overwrite --ignore=node_modules/electron-* --ignore=node_modules/.bin --ignore=.git --ignore=launcher.json --ignore=.jshintrc --ignore=dist --prune`

But when I run the exe after packaging, I got a error told me that Vue is not found

Where is my error step???

**Comment by MarshallOfSound** [comment]
First off this should be raised over at the `electron-rebuild` repository.

Secondly an empty result indicates a successful rebuild.  Only errors generate output

**Comment by paulcbetts** [comment]
@mydansun You only need to rebuild native modules (i.e. modules that contain C++ code). Since jQuery is written in JavaScript, you don't need to use `electron-rebuild`

**Comment by mydansun** [comment]
@paulcbetts thanks, but why my packaging result does not include jquery?

**Comment by paulcbetts** [comment]
Because jQuery doesn't contain C++ Code
