### ISSUE TITLE
v1.1.0 broke electron-packager

### ISSUE THREAD

**Issue by super-ienien** [electron/electron#5585]
Hi,

when packaging an electron app using electron v1.1.0 with electron-packager. The app doesn't start if Visual Studio is not installed on the computer.

https://github.com/electron-userland/electron-packager/issues/368

**Comment by zcbenz** [comment]
It had been fixed with https://github.com/electron/electron/pull/5538.

**Comment by super-ienien** [comment]
Ok sorry, I didn't check closed issues. When do you think it will be released ?

**Comment by paulcbetts** [comment]
@super-ienien You don't need to wait, just include the VS2015 runtime DLLs in the folder
