### ISSUE TITLE
In frameless mode electron app is opened without content and with black background

### ISSUE THREAD

**Issue by flashlee** [electron/electron#5586]
* Electron version: 0.37.5
* Operating system: Fedora 23

I just cloned electron-quick-start project, added `frame: false` and delete `mainWindow.webContents.openDevTools();` string.
As result opened window is black, content is not visible (but can be selected)
![elec](https://cloud.githubusercontent.com/assets/17676386/15356531/99fe9c86-1cf9-11e6-82c4-7178cbc2f3b0.png)

**Comment by zcbenz** [comment]
Please update to a more recent version of Electron which had fixed this issue.
