### ISSUE TITLE
how to deal with window decoration on osx ?

### ISSUE THREAD

**Issue by gbaumgart** [electron/electron#5591]
The standard window controls (minimize, maximize, close) in OSX are rendered inside my application and are overlapping my own menu bar (File/Edit/...). 

Any idea how to deal with this problem? 

I can think currently only of using a margin-left for the first item in my top-menu but I have no idea how this works with custom window decorators or themes in osx. The chromium built menu system isn't an option since its lacking of too many things.

![osx2](https://cloud.githubusercontent.com/assets/1205100/15370236/52c667f8-1d36-11e6-945f-8a94e17e2986.jpg)

thanks a lot, close this if its out of your scope.

* Electron version: latest
* Operating system: osx - latest

**Comment by paulcbetts** [comment]
Unfortunately, OS X picks where those buttons go and there's nada you can do about it. In your case, I'd just ditch the custom menu entirely and move those items into the actual top-level menu, it's Quite Odd to put window-specific menus on OS X apps

**Comment by gbaumgart** [comment]
yeah, guessed so. i'll go for css hacking then. 
ok, thanks a lot
