### ISSUE TITLE
chrome popup are showing up as white window when BrowserWindow.show = false.

### ISSUE THREAD

**Issue by lasryaric** [electron/electron#5593]
* Electron version: 0.36.0 to 1.0.2
* Operating system: os x 10.11.1

I am creating a new browser window with the option `show:false`, so the window does not  appear, but when the window opens a new window using the javascript method `window.open(url)`, a white window shows up in electron.

Any idea how to make this new window not show up at all?

Thanks

**Comment by zcbenz** [comment]
You can prevent the behavior by using `new-window` event:
http://electron.atom.io/docs/api/web-contents/#event-new-window

**Comment by lasryaric** [comment]
thank you
