### ISSUE TITLE
How to read a certificate from a USB token

### ISSUE THREAD

**Issue by coelho-extremosistemas** [electron/electron#5596]
Hi folks.
Are there any module in nodejs that is compatible with the Electron , which I can use to read a certificate within a pendrive (e-token)?
Does anyone have any tips for me to start a search?

[like this: e-token](http://www.safenet-inc.com/multi-factor-authentication/authenticators/pki-usb-authentication/)

**Comment by zcbenz** [comment]
I suggest seeking help from [the community](https://github.com/electron/electron#community).

**Comment by tiagotol** [comment]
Hi @coelho-extremosistemas . Have you find a solution to this issue?

**Comment by ricardosbarbosa** [comment]
I would like to know also!
