### ISSUE TITLE
Download.Item ‘done’ event does not fire with ‘interrupted’ state when network connection fails

### ISSUE THREAD

**Issue by HangTenKen** [electron/electron#5598]
* Electron version:  0.37.8
* Operating system: Windows 7 Ultimate SP1

I am testing failure scenarios for file downloading using downloadURL. I've registered an event listener to the 'done' even using the download item. When I interrupt the network connection during a download, I do not see any 'done' event fire with the state of 'interrupted.

I was hoping to catch and do something useful in case a download is interrupted, but it appears that I'm not getting the notification event I expect.

Can anyone help? Is this the right approach? Does the event handling require external network connection to function? What does trigger the 'interrupted' state?

```javascript
... 
   item.on('done', (e, s) => this._handleDone(e, s))
  }

  _handleDone(event, state) {
    logger.info("_handleDone: state = " + state)
    switch(state) {
      case 'completed': {
        logger.info("DOWNLOAD COMPLETED")
        this.currentJob.file.Status = Downloader.STATUS_COMPLETED
        this.emit('job-changed', this._jobStatus(this.currentJob.job))
        break;
      }
      case 'cancelled': {
        logger.info("DOWNLOAD CANCELLED")
        this.currentJob.file.Status = Downloader.STATUS_CANCELLED
        this.emit('job-changed', this._jobStatus(this.currentJob.job))
        break;
      }
      case 'interrupted': {
        logger.info("DOWNLOAD FAILED")
        this.currentJob.file.Status = Downloader.STATUS_FAILED
        this.emit('job-changed', this._jobStatus(this.currentJob.job))
        break;
      }
      default: {
        logger.info("DOWNLOAD DONE UNHANDLED STATE", state)
      }
    }
```

**Comment by zcbenz** [comment]
Hmm it seems to be deign flaw of the DownloadItem API.

**Comment by HangTenKen** [comment]
@zcbenz :  Thanks for confirming the bug.  What is the typical bug turn-around time?  Do you have any work-arounds in the mean time?

**Comment by tonifds** [comment]
Received bytes: 0
Received bytes: 54693
Received bytes: 54693
Received bytes: 54693
Received bytes: 54693
Download failed: interrupted

appear in console
