### ISSUE TITLE
Why my electron-packing does not package my vue.js

### ISSUE THREAD

**Issue by mydansun** [electron/electron#5607]
At First I executed npm install vue --save

My packager script is electron-packager . launcher --platform=win32 --arch=x64 --version=1.0.0 --out=dist/ --overwrite --ignore=node_modules/electron-* --ignore=node_modules/.bin --ignore=.git --ignore=launcher.json --ignore=.jshintrc --ignore=dist --prune

But when I run the exe after packaging, I got a error told me that Vue is not found. Why??

**Comment by danhp** [comment]
You're probably going to have to take that issue up with https://github.com/electron-userland/electron-packager as this is a packaging issue not linked with core Electron.
But that aside, ignoring folders in `node_modules` can be risky business.

**Comment by mydansun** [comment]
@danhp thanks
