### ISSUE TITLE
windows service from electron process

### ISSUE THREAD

**Issue by gtaranas** [electron/electron#5609]
* Electron version:
* Operating system:

I tried [node-windows ](https://github.com/coreybutler/node-windows) to register a window service from main process but when running on deployment machine (after packaging to exe) the services starts with myapp.exe as the host. is there anyway to pass the script needed to run as argument in myapp.exe (electron)? just like nodejs in the form: node main.js

**Comment by zcbenz** [comment]
I believe Windows services allow specify command line parameters, but you have to ask the maintainers of node-windows on how. Another choice is to package your app into standalone app.
