### ISSUE TITLE
Add internal electron support for the `chrome.mdns` API

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#5612]
- Electron version: Any
- Operating system: All

I'm not sure what the Electron teams position on implementing / porting the `chrome.XXXX` API's are (I couldn't find many issues regarding it) but it would be great if the `mdns` API was implemented in Electron.

The initial implementation in chromium can be seen here https://codereview.chromium.org/668983003

I don't know how much work this would take or if it's just the case of turning on some code??  I am unfamiliar with how chromium is built.

**Comment by deepak1556** [comment]
There was request for this feature https://github.com/electron/electron/issues/2961 , doesnt existing node modules serve the purpose ?

**Comment by MarshallOfSound** [comment]
@deepak1556 Wow, can't believe I didn't find that issue when searching.  But to answer the question

* Basically there are two type of MDNS `npm` modules.
    * The "Native Module" MDNS.  This requires `Bonjour` is installed on your users system which on Windows is a nightmare when using Squirrel.  So this is a no go for most Electron users
    * The "Full JS" MDNS.  These are dodgily implemented and have a lot of flaws.  In particular they don't query other devices correctly on some networks.

Whereas, the Chromium implementation is proven to work, and is proven to work ALONGSIDE an existing Bonjour install (this is critically important).

Does that answer your question?

**Comment by MarshallOfSound** [comment]
@zcbenz I'm keen to sort this one out.  Has this kind of thing (enabling a chrome API inside the Electron API) been done before so I can see the kind of work I would need to do?

If not could you point me in the right direction?

**Comment by deepak1556** [comment]
You can look at how chrome uses [net::MDnsClient](https://code.google.com/p/chromium/codesearch#chromium/src/net/dns/mdns_client.h&l=150&rcl=1464664581) to implement the api. It would be cool if this can be made a standalone node module, since it has a generic use case than in electron.

**Comment by 3mp3ri0r** [comment]
Any update about this issue?

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
