### ISSUE TITLE
Release single instance lock before exit

### ISSUE THREAD

**Issue by felicienfrancois** [electron/electron#5620]
* Electron version: 1.1.0
* Operating system: Windows
* Use case: cleanup and reporting tasks executed on quit (headless), which may take time and should not prevent from opening a new instance.
* Proposed solutions:
  * new _app.releaseSingleInstance()_ API which free the singleInstance lock
  * replace _app.releaseSingleInstance()_ API by an event listener (which may be listened/unlistened)
  * [app.makeSingleInstance](https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback) returns the result of the callback function. So we can choose to quit or not in a more accurate way.
  * Provide a communication channel between the new instance and the main one (in callback arguments)

**Comment by zcbenz** [comment]
I'm 👍 on adding a new `app.releaseSingleInstance` API, it is compatible with current API and easy to implement.

**Comment by paulcbetts** [comment]
:+1:
