### ISSUE TITLE
event 'platform-theme-changed' removed?!!!

### ISSUE THREAD

**Issue by MathijsvVelde** [electron/electron#5623]
* Electron version: v0.37.8+
* Operating system: *

The tray icon in my app changes color depending on the current theme of the menu bar (OSX)
So I was depending on the event `platform-theme-changed` in `electron.app`
If it was just moved, I did not mind, but it is removed, in this PR to be precise (https://github.com/electron/electron/pull/5282). 😢 

Can you please put back again, as it must in `electron.SystemPreferences`?

Thanks!

**Comment by danhp** [comment]
It was replaced by the much more powerful `subscribeNotification` which can achieve the same effect.
If you feel lazy you can use https://github.com/danhp/electron-osx-appearance instead of looking things up.

**Comment by MathijsvVelde** [comment]
Okay,
Thanks for the quick reply.
It seems that I missed the deprecated warning.

Thanks 👍

**Comment by rootscript** [comment]
@danhp @MathijsvVelde - I was trying to use as:
```
const {systemPreferences} = require('electron')
app.on('platform-theme-changed', function () {
    console.log(`Platform theme changed. In dark mode? ${systemPreferences.isDarkMode()}`)
})
```
do you have an example with `subscribeNotification`, please?
