### ISSUE TITLE
PATH is lost in production ?

### ISSUE THREAD

**Issue by antoniobrandao** [electron/electron#5626]
* Electron version: 0.30 - 1.0.1
* Operating system: OSX Yosemite

I having a problem PATH using Electron in production. The problem I have is with "pdfinfo" (poppler). Poppler was installed with homebrew and it is in the PATH (I can execute "pdfinfo" from any folder in my terminal).

When starting my Electron app from the command line, I have no problem at all with the PATH. This will work fine, and "pdfinfo" will be found and work correctly:

    ./node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron ./

It's only when I start my app in production (opening the Electron.app app icon like any normal app). When spawning "pdfinfo" in this scenario, i get this:

    stderr stdout: /bin/sh: pfdinfo: command not found

Notice the "/bin/sh" path.

While looking for an explanation for this problem I stumbled upon this thread: https://discuss.atom.io/t/every-spawn-task-throws-enoent-when-electron-app-packaged-for-distribution/18692

Read where "erikmellum" states:

> When in production, spawn does not use your regular PATH variable to locate executables. It will basically use a PATH that includes OS bin folders (such as /usr/bin).

Which kinda seems to be related to my problem. Is this true? How can I get around this? Is there a way to tell production Electron to use the normal system PATH in production?

**Comment by zcbenz** [comment]
This is unfortunately a behavior of OS X, every app started from Finder does not get the environment variables from terminal. There is a simple module to work around this:
https://github.com/sindresorhus/fix-path

**Comment by antoniobrandao** [comment]
BIG thanks @zcbenz

**Comment by JF-23** [comment]
https://github.com/electron/electron/issues/13214

**Comment by Emmanuel0705** [comment]
this really 

> This is unfortunately a behavior of OS X, every app started from Finder does not get the environment variables from terminal. There is a simple module to work around this: https://github.com/sindresorhus/fix-path

this really helped me a lot ..
i have been on this issue for over 2 weeks .
i  got it fixed easily with this solution .
thanks a lot man
