### ISSUE TITLE
electron > 1.0.0 : web-security not working

### ISSUE THREAD

**Issue by mnagaev** [electron/electron#5628]
* Electron version:1.0.0
* Operating system:windows 

Stops working disable web security settings in web-preferences section.
Version 0.37.8 everything works, was forced to return.

**Comment by kevinsawicki** [comment]
@mnagaev can you include the options object you are seeing to the `BrowserWindow` constructor?

1.0 did remove support for old key names so it needs to be `webPreferences` and `webSecurity` now.

**Comment by mnagaev** [comment]
Thank you, come back to life my application.
You can close this issue
