### ISSUE TITLE
Cannot get BrowserWindow icon to work

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#563]
Here is my code:

```
mainWindow = new BrowserWindow({
    'x': 2560,
    'y': 880,
    'width': 850,
    'height': 530,
    'skip-taskbar': false,
    'icon': 'file://' + __dirname + '/../images/icon.png',
    'frame': true,
});
```

Yet I still keep seeing this icon when running:

![capture](https://cloud.githubusercontent.com/assets/62191/3853039/3dcc2c92-1eba-11e4-8ad7-e50e29f71d76.PNG)

My icon.png is a 256x256 PNG. The image file path is correct, as I am successfully starting my app with this command:

```
mainWindow.loadUrl('file://' + __dirname + '/../index.html');
```

My project is open source, here is the repo:

https://github.com/kirkouimet/notes

**Comment by onmyway133** [comment]
I have this problem too, try all different size, and even use icns, but electron still shows default icon. It must be because of caching

**Comment by gschier** [comment]
Can you all give this new Beta build a try and let me know if it works? Seems to be working on my Ubuntu install for AppImage, Snap, and dev
