### ISSUE TITLE
feature request: add non-native promise support

### ISSUE THREAD

**Issue by cdaringe** [electron/electron#5633]
for full information and demonstration, please see: https://github.com/cdaringe/electron-native-promises-only

**Comment by cdaringe** [comment]
while i was at it, confirmed #5111 in the above (`v1.1.1`)

**Comment by zcbenz** [comment]
The `remote` object does support non-native Promise, but the name of class has to be `Promise`, otherwise it is impossible to confirm whether the object is an Promise. In your case it doesn't work because you are using the `bluebird` object directly, and Electron doesn't know it is a Promise.

**Comment by cdaringe** [comment]
right, i saw that in the coffeescript.  however, per the issue title, I was hoping consideration of non-native promise detection.  i was thinking that it could simply test for an instance of a .then prop, and if .then is a function. it does collide with pojos or other prototypes having a `.then` attribute.  perhaps testing for `.resolve` && `.reject` on the constructor would be more thorough or less likely to risk collisions.

**Comment by zcbenz** [comment]
I'm good supporting non-native promise as long as we can do it reliably, but testing the `.then` attribute is unreliable.
