### ISSUE TITLE
Does not save updated HTML file when using "HTMLOnly" option

### ISSUE THREAD

**Issue by nick2012** [electron/electron#5635]
* Electron version:
* Operating system: Windows 7 x64

```
  "name": "electron-prebuilt",
  "version": "0.37.8",

webContents.savePage(fullPath, saveType, callback)

HTMLOnly - Save only the HTML of the page.
HTMLComplete - Save complete-html page.

```

Basically, if you click, scroll, etc so that the content of the page gets extended via JavaScript, when using the save page option with HTMLOnly option, Nightmare does not save the latest HTML, but the one that was loaded at the beginning. However, it saves the latest version when using HTMLComplete.

**Comment by zcbenz** [comment]
This is unfortunately the expected behavior of Chrome browser, I suggest reporting this to [Chromium's issues list](https://crbug.com) if you think this is a bug.

If you want to save the updated HTML, I suggest getting it with `document.documentElement.innerHTML`.
