### ISSUE TITLE
scrollBounce option ignored in MAS builds

### ISSUE THREAD

**Issue by turadg** [electron/electron#5637]
* Electron version: 1.1.1
* Operating system: Mac (App Store builds)

Rubberbanding (or scroll bouncing) makes an Electron app feel more like a browser page (#5397). #5412 solved this by setting a default false `NSScrollViewRubberbanding` pref on the app, but it doesn't work for Mac App Store sandboxed builds. (Or at least I can't get it to.)

In my use, non-MAS has no rubberbanding and MAS builds do. My best hypothesis is that the `CFPreferencesSetAppValue` call in [atom_renderer_client.cc](https://github.com/electron/electron/blob/6f3d0e17826313898ef12932282479cf7d5cb7c0/atom/renderer/atom_renderer_client.cc#L120-L126) is being ignored by the MAS sandbox. I tried granting the [com.apple.security.temporary-exception.shared-preference.read-write](https://developer.apple.com/library/mac/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/AppSandboxTemporaryExceptionEntitlements.html) permission in parent.plist but it had no effect,
```
    <key>com.apple.security.temporary-exception.shared-preference.read-write</key>
    <array>
      <string>com.remind.desktop</string>
    </array>
```

Any other ideas?

**Comment by zcbenz** [comment]
I'm unable to reproduce, does the default app have the rubber banding effect on your machine?

**Comment by turadg** [comment]
Root cause: PEBCAK

(sorry to waste your time)
