### ISSUE TITLE
window.open() on same origin should expose child window document.

### ISSUE THREAD

**Issue by jhgg** [electron/electron#5639]
On a regular browser, you can call `win = window.open()` to a url that shares the same origin as the page you open it from. When doing that, you'd have access to `win.document`, etc... which lets you mutate the child window's DOM. 

Electron's `window.open()` is a shim around the BrowserWindow API, which prevents us from having access to `.document`, etc... 

Is there any way to restore `window.open()` to be the default one used in the browser? Or are there any plans to expose it in a way more similar to how it's implemented in the browser. 

The use-case here for this would be to be able to open a new window, and then mount a react component into the child window's <body>, which is controlled by the parent window.

**Comment by zcbenz** [comment]
I'm merging this to #1865.
