### ISSUE TITLE
Change default notification sound on OS X

### ISSUE THREAD

**Issue by evgeniyzinoviev** [electron/electron#5642]
* Electron version: 1.1.0
* Operating system: OS X

I need to change default notification sound for my app. Or disable it programmatically. I'm talking about this
![untitled-1](https://cloud.githubusercontent.com/assets/18737999/15455717/fad90f1c-205c-11e6-99d0-6f79f8c64b65.png)

Is it possible?

**Comment by zcbenz** [comment]
I don't think OS X exposes API to change this, you can probably write an Apple Script for this, and then call it from Electron.

**Comment by PierBover** [comment]
Why do Electron notifications emit a sound when all other notifications are mute?
