### ISSUE TITLE
app crash after packing

### ISSUE THREAD

**Issue by cinder92** [electron/electron#5647]
* Electron version: 0.36.8
* Operating system: OS X

i don't know why it says that loadURL (from electron)  is not defined

![captura de pantalla 2016-05-22 a las 8 02 09 p m](https://cloud.githubusercontent.com/assets/4725556/15457895/3714eb4a-2058-11e6-89f0-8005fbdcc0a1.png)

**Comment by davej** [comment]
You'll need to provide `main.js` before this can be debugged.

**Comment by zcbenz** [comment]
Closing this is a question on using Electron, I suggest seeking help from [the community](https://github.com/electron/electron#community).
