### ISSUE TITLE
Extending BrowserWindow fails on 1.1.x 

### ISSUE THREAD

**Issue by inukshuk** [electron/electron#5652]
Extending `BrowserWindow` via `class extend` has been working for me in the past, but stopped working starting with Electron 1.1.0. Do you have any idea why that could be?

Given something like:

    class MyWindow extends BrowserWindow {
      constructor() { super({ show: false }) }
      open() {}
    }

    expect(new MyWindow()).to.be.instanceof(BrowserWindow)
    expect(new MyWindow().open).to.be.a('function')

On 1.0.2 both these expectations pass; on 1.1.x the first expectation passes, the second one fails. Note that creating the browser window actually works (without show: false it shows up). Trying to debug this, I noticed that 'object has been destroyed' when trying to inspect MyWindow.prototype -- note that I get the same error when trying to inspect BrowserWindow.prototype; I think this was already the case in previous versions though (but it might make sense to override the 'inspect' method, to make sure it does not happen).

Anyway, I'd be happy to help track this down further, but I wanted to make sure that it should even be possible to extend BrowserWindow in the first place.

* Electron version: 1.1.0, 1.1.1
* Operating system: Linux

**Comment by kevinsawicki** [comment]
Are you extending it in the main or renderer process?

Perhaps related to https://github.com/electron/electron/issues/5599 ?

**Comment by inukshuk** [comment]
I was extending (and using) `BrowserWindow` only in the main process – the snipped above was also tested in main.

**Comment by zcbenz** [comment]
It is actually surprising to me that you could extend BrowserWindow, the design of V8 makes it very hard to implement a native class that can be inherited by JavaScript, and that's also why you are not able to extend most of DOM elements.

For more details you can take a look at #23. I'm closing this as won't fix.

**Comment by inukshuk** [comment]
Thanks @zcbenz -- I had a feeling it wasn't supposed to work. (Interesting that it did work from 0.30 through 1.0 though!)
