### ISSUE TITLE
Please update build instructions for windows

### ISSUE THREAD

**Issue by evgeniyzinoviev** [electron/electron#5655]
* Electron version: 1.1.0
* Operating system: Windows

Since Electron 1.1.0 you build it with VS 2015, but docs still saying that we need VS 2013.

**Comment by felixrieseberg** [comment]
On it.

**Comment by fritx** [comment]
Excuse me. Does VS 2013 still work?

**Comment by MarshallOfSound** [comment]
@fritx Pretty sure the answer to that is no 😄
