### ISSUE TITLE
Electron + React - Cant require('fs') -> returns empty object

### ISSUE THREAD

**Issue by FinnFrotscher** [electron/electron#5657]
* Electron version: newest
* Operating system: Mac OSX newest

I have an empty `electron quickstart` project. 
The only file ist `app/app.js` with the two lines

    var fs = require('fs');
    console.log(fs);

`"watch": "watchify app/app.js -t babelify -o public/js/bundle.js --debug --verbose"`  is used with `npm run watch ` and `npm start` to run electron 
as presets for `babel` I have `react` and `es2015`.

I need the `fs` to read and write files. 
When I require the fs in the `renderer.js` file, it works perfectly. not inside the `app.js` code. 
I have tried using browserfy but it doesnt work either.

when `"build": "browserify app/app.js -o public/js/bundle.js -t babelify"`, `npm run build` and then `npm run`  -> `console.log(fs);` returns an object with only `__proto__` defined.

**Comment by danhp** [comment]
Node modules are only available from main or renderer processes.
You can test what you wanted by adding the snippet to the top of `main.js` in the [quickstart app](https://github.com/electron/electron-quick-start) 
```
const fs = require('fs');
console.log(fs);
```

**Comment by FinnFrotscher** [comment]
How can I have `fs` on the client?
or is there a way to communicate with the `main.js` -process?

**Comment by mnquintana** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Electron message board](https://discuss.atom.io/c/electron) or the [Electron Slack channel](http://atom-slack.herokuapp.com/) is where you'll probably be able to find answers faster.

**Comment by ziarno7** [comment]
@FinnFrotscher did you figure out how to do that? Having the same problem

**Comment by FinnFrotscher** [comment]
hi,
sorry to letting you wait.
well, kind of. I dont remember the exact situation i was in when i asked this. 
BUT I build some apps with react since and use the FS frequently.
if you want i can give you some demo code where it works.

**Comment by tyurderi** [comment]
@FinnFrotscher Yes, please.

**Comment by nginnever** [comment]
also interested @FinnFrotscher

**Comment by ziarno7** [comment]
Browserify overrides the `require` method. I'm running it with these flags and it all works `--verbose --ignore-missing --no-builtins --no-commondir --insert-global-vars=\"global\"`
