### ISSUE TITLE
onbeforeunload inside webview doesn't fire correclty

### ISSUE THREAD

**Issue by r1si** [electron/electron#5661]
* Electron version: 1.1.1
* Operating system: OSX
In my index.html create a webview with a webapp url.
All work fine, but when the webview try to fire a onbeforeunload event it doesn't work and the webview result freeze

if you want reproduce the problem try to load a webview with this url and press the "exit page" link (the alert didn't appear :( )
https://jsfiddle.net/objrqzb9/1/

any advice ? 

Thanks a lot 

Elia

**Comment by zcbenz** [comment]
The alert not showing problem is tracked at #2579. But I can't reproduce the webview freezing problem with your code.

**Comment by r1si** [comment]
There is some way to mantain the chrome default behavior (show the confirm message) ? 
Some application freeze (for example roundcube)

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by zcbenz** [comment]
Closing until more information is provided.
