### ISSUE TITLE
beginFrameSubscription doesn't work with webview

### ISSUE THREAD

**Issue by IsaiahJTurner** [electron/electron#5665]
# BOUNTY [![Bountysource](https://www.bountysource.com/badge/issue?issue_id=34506613&style=bounties_received)](https://www.bountysource.com/issues/34506613-beginframesubscription-doesn-t-work-with-webview)
*If you complete this issue you will receive the posted bounty amount.*
* Electron version: 1.0.1
* Operating system: El Capitan

## DOES NOT WORK:
```js
webview.getWebContents().on('did-finish-load', function() {
  webview.getWebContents().beginFrameSubscription(function(buffer) {
    console.log("buffer", buffer); // this will never fire
  });
});
```
`webview.getWebContents()` is returning a valid WebContents object.

## Works:
```js
mainWindow.webContents.on('did-finish-load', function() {
  mainWindow.webContents.beginFrameSubscription(function(buffer) {
    console.log("buffer", buffer); // this will be called when pixels change
  });
});
```

**Comment by IsaiahJTurner** [comment]
Would anyone be willing to take this on for a bounty?

**Comment by IsaiahJTurner** [comment]
I increased the bounty to over $100.

**Comment by brenca** [comment]
The above PR should fix this
![](http://i.imgur.com/eJiagaI.jpg)

**Comment by IsaiahJTurner** [comment]
@brenca is it possible that it doesn't work with retina screens? I get the right info in the changed rect object and `(width * height) / buffer.length = 0.25` but when I visualize the pixels they only include the top left fourth of the screen. I don't have a non-retina screen to test yet. Inspect element reveals the webview is the correct size.
<img width="314" alt="screen shot 2016-09-08 at 11 59 47 pm" src="https://cloud.githubusercontent.com/assets/3732588/18375063/7f7aa2b2-7620-11e6-9d67-fe194bc3b4e4.png">
<img width="745" alt="screen shot 2016-09-09 at 12 00 02 am" src="https://cloud.githubusercontent.com/assets/3732588/18375064/7f876222-7620-11e6-9c03-28cc130b9ebf.png">

**Comment by brenca** [comment]
@IsaiahJTurner Can you check if the same thing happens when capturing a `BrowserWindow`'s `WebContents` too?

**Comment by IsaiahJTurner** [comment]
@brenca It does not. Didn't break any old stuff but I confirmed the issue with a second monitor. As soon as I drag the window onto a non-retina display it works great. Should I open an issue here or on electron/libchromiumcontent?

**Comment by brenca** [comment]
The comments [here](https://cs.chromium.org/chromium/src/content/browser/frame_host/render_widget_host_view_child_frame.cc?sq=package:chromium&dr=CSs&l=176) might be relevant, webviews seem to be a special case. It's most likely going to be a fix on the electron side of things.
