### ISSUE TITLE
Get access to the current NavigationController?

### ISSUE THREAD

**Issue by simonlast** [electron/electron#5667]
Is it possible to get access to the current NavigationController? I can't seem to find it attached anywhere accessible.

**Comment by paulcbetts** [comment]
NavigationController?

**Comment by simonlast** [comment]
This: https://github.com/electron/electron/blob/ecbb088ea600227c0cd1356e3a19575d579bf664/lib/browser/api/navigation-controller.js

**Comment by simonlast** [comment]
It looks like it's instantiated here, but I'm not sure how to get access to it (besides hacking into the code)
https://github.com/electron/electron/blob/4193fb1742ee5b0e19d079e5bd8e47dacbabfc0b/lib/browser/api/web-contents.js#L82

**Comment by zcbenz** [comment]
The instance of `NavigationController` is hidden from users, so there is no way to get access to it.
