### ISSUE TITLE
Cookies not holding values if the application is restarted.

### ISSUE THREAD

**Issue by bansalvks** [electron/electron#5673]
* Electron version: 1.1.0
* Operating system: OSX 10.5

I need to create some cookeis that persist even the applicaiton is launched after a week. In order to do that I have created a session [https://github.com/electron/electron/blob/master/docs/api/session.md#class-session](url) 

Code:
```
const session = require('electron').session;
const ses = session.fromPartition('persist:name');

 // Query all cookies associated with a specific url.
    ses.cookies.get({ url: 'http://www.github.com' }, (error, cookies) => {
        console.log(cookies); /// cookies values should be printed next time the applciation is launched.
    });

    // Set a cookie with the given cookie data;
    // may overwrite equivalent cookies if they exist.
    const cookie = { url: 'http://www.github.com', name: 'dummy_name', value: 'dummy' };
    ses.cookies.set(cookie, (error) => {
        if (error)
            console.error(error);
    });
```

**ISSUE**
The cookies does exists from the next launch of the applicaton

**Comment by zcbenz** [comment]
You need to set `expirationDate` otherwise the cookie only exists for current session.
