### ISSUE TITLE
 When to support the XP window system?

### ISSUE THREAD

**Issue by bdxing** [electron/electron#5676]
There are still a lot of applications for this demand scenario

**Comment by MarshallOfSound** [comment]
See issues such as #1775 #3370 

Electron will only support Windows 7 and up.

**Comment by felixrieseberg** [comment]
Yep, sorry to say that this is a clear "wontfix" from the Electron team. NW.js still supports XP, so that might be a good solution for your problem.

**Comment by bdxing** [comment]
thanks, you's response

**Comment by jetiny** [comment]
the windows xp version https://github.com/jetiny/electron-xp

**Comment by alainazpe** [comment]
> the windows xp version https://github.com/jetiny/electron-xp

need xp version please, no way to found it in the web :(
