### ISSUE TITLE
build for arm64

### ISSUE THREAD

**Issue by WebReflection** [electron/electron#5677]
* Electron version: latest
* Operating system: linux

just wondering if it's planned or in the pipeline, the current arm prebuilt version does not seem to work but the arm64 link doesn't exist ( so forcing `--arch=arm` is not a solution on arm64 )

Thank you for any sort of info.

**Comment by zcbenz** [comment]
Currently we don't have a a way to build for custom ARM configurations, I'm merging this to #259.
