### ISSUE TITLE
Window cannot be dragged on Mac OS with titleBarStyle="hidden"

### ISSUE THREAD

**Issue by markbrocato** [electron/electron#5678]
* Electron version: 1.1.1
* Operating system: Mac OS El Capitan

When a BrowserWindow is configured with titleBarStyle "hidden" or "hidden-inset", the user can no longer drag the window to move it.

**Comment by markbrocato** [comment]
Nevermind, just found the workaround: add style="-webkit-app-region: drag" to the html element corresponding to the app header.  Seems reasonable.

**Comment by MarshallOfSound** [comment]
See #5660 for a similar issue

See #5557 for the PR that changed this behavior

See https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#draggable-region for how to implement yourself from now on :+1: :smile:

**Comment by LDubya** [comment]
Well how are you supposed to account for the fact that titleBarStyle doesn't work for <Yosemite?
If you have to include custom HTML component to act as a draggable menu in Yosemite+, then you have to *not include* that same html component for <Yosemite, or else for <Yosemite you'll have two menu bars. So how do you do this without having to create two separate builds?

**Comment by enlight** [comment]
@LDubya Node provides the OS version via `os.release()`, more details at http://stackoverflow.com/questions/14989081/node-js-to-get-determine-os-version
