### ISSUE TITLE
saveDirectory for save dialog boxes does not work properly on Windows

### ISSUE THREAD

**Issue by desilinguist** [electron/electron#5679]
* Electron version: 1.0.2
* Operating system: Windows 7

Using `dialog.showSaveDialog({properties: ['saveDirectory']})` on Windows seems to behave incorrectly. On OS X, if I try to save a directory in a folder where another directory with the same name already exists, it correctly asks me if I want to replace the older directory. However, on Windows, it seems to save the new directory inside the older directory with the same name. 

For example, if I want to save the directory `foobar` on the Desktop but `Desktop/foobar` already exists, on OS X, it will ask me if I want to replace `Desktop/foobar` but on Windows, there's no prompt and it just saves `Desktop/foobar/foobar`.

**Comment by desilinguist** [comment]
Hmm, may be I just hallucinated that `saveDirectory` is a valid property for the save dialog box.

**Comment by zcbenz** [comment]
The save dialog is a native Windows dialog that the behavior is controlled by Windows, and it seems that Windows disagrees with OS X on how the behavior should be. I don't know which one is better, but I think we should follow the default behavior on each platform.
