### ISSUE TITLE
window.print() from a BrowserWindowProxy instance?

### ISSUE THREAD

**Issue by blazeworx** [electron/electron#5685]
* Electron version: 0.37.2
* Operating system: OSX 10.11.4

I understand that the `BrowserWindowProxy` class has limited functionality. However, I am packaging a web app that can open a new window and then calls on `window.print()`. Unfortunately the `BrowserWindowProxy` instance that gets instantiated when `window.open()` is called does not have `print()` as an available function. The end goal is that I would like to print the contents of this newly opened window. Is there any way to have `print()` available in `BrowserWindowProxy`?

**Comment by MarshallOfSound** [comment]
Assuming you want a fully powered `BrowserWindow` you could try doing something like.

```
window.open = (url) => {
    const bw = new BrowserWindow();
    bw.center();
    bw.loadURL(url);
    return bw;
}
```
