### ISSUE TITLE
can not find module remote

### ISSUE THREAD

**Issue by gbaumgart** [electron/electron#5690]
* Electron version:1.1.2
* Operating system:win7-32/linux

I updated today to 1.1.2 and I have now an error : can not find module "remote"

I required it by : var app = electronRequire('remote').require('app');// electronRequire is just a pointer 

Any idea ? 

thanks a lot.

**Comment by martinstarman** [comment]
Try 
```
require('electron').remote;
```
Doc: http://electron.atom.io/docs/api/remote/

**Comment by mnquintana** [comment]
Please take a look at the [1.0 migration guide](http://electron.atom.io/blog/2015/11/17/electron-api-changes) for help you migrate your 0.x Electron app to 1.x.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For support questions, [the Electron message board](https://discuss.atom.io/c/electron) or the [Electron Slack channel](http://atom-slack.herokuapp.com/) is where you'll probably be able to find answers faster.

**Comment by gbaumgart** [comment]
thanks a lot guys,

there is something wrong with the shell object. the migration guide says nothing about it and official docs says: 

const {shell} = require('electron'); 

so i did : 

var shell = require('electron');

but this has no openItem method, so I did end up with : 

var shell = require('electron').shell

I guess this is because we don't use this all JS post processor stuff.
