### ISSUE TITLE
Electron icon for windows x64

### ISSUE THREAD

**Issue by coelho-extremosistemas** [electron/electron#5691]
I am trying to generate a package of electron, with new version 1.1.2 of electron, but icon of executable file ".exe", not change to my png file at windows 8.1.
In the older version of electron, 1.0.2 it's ok.

electron-packager version 7.0.2
electron-packager . --ignore=\"(examples|LICENCE)\" --icon=appccs.png --platform=win32 --arch=x64 --version=1.1.2 --overwrite --prune
electron-prebuilt version 1.1.2
window 8.1 x64

**Comment by danhp** [comment]
You might have a better chance of getting an answer directly from [electron-packager](https://github.com/electron-userland/electron-packager) as this is a packaging issue not related to core Electron.

Hope that helps :sparkles:

**Comment by coelho-extremosistemas** [comment]
My issue was canceled in electron-packager:
https://github.com/electron-userland/electron-packager/issues/377

**Comment by paulcbetts** [comment]
This can't be an Electron bug, that makes zero sense

**Comment by coelho-extremosistemas** [comment]
Please.. close this issue. My fail.

**Comment by paulcbetts** [comment]
@coelho-extremosistemas Not your fault! We'll keep looking into it at electron-packager
