### ISSUE TITLE
Shadow redraw on transparent windows (OS X)

### ISSUE THREAD

**Issue by davej** [electron/electron#5692]
I am having issues with shadows being drawn incorrectly on OS X when using transparent windows. 

Would it be possible to get a brief description on when shadows are drawn and redrawn so that I can ensure shadows get drawn predictably on transparent windows. If shadow redraws could be triggered from JS-land then that would be ideal but I realise this may be too low-level for Electron.

---
* Electron version: 0.37.7
* Operating system: OS X 10.10.5

**Comment by zcbenz** [comment]
How the shadow is drawn is controlled by OS X, I don't think anyone ever tried to hack that. The best choice you can do is to close the native shadow, and draw shadow with CSS yourself.
