### ISSUE TITLE
What's the best way to open a window on multiple screens

### ISSUE THREAD

**Issue by mansona** [electron/electron#5696]
Hey all,

I've been looking back through the issues and I've found a few references to people "opening dialog boxes on multiple screens" 

I don't see anything in the documentation that suggests that I could use something like window.open() to open one window per connected display. I am trying to write something that pops up an always on top notification that you can't miss or ignore and I want it to show on every screen. 

Any suggestions?

**Comment by OlsonDev** [comment]
Did you see [`screen.getAllDisplays()`](http://electron.atom.io/docs/api/screen/#screengetalldisplays)? Couple that with `BrowserWindow`'s `x` & `y` and I think that covers what you're looking for.

By the way, questions like this should be directed toward [the community](https://github.com/electron/electron#community); they want to keep issues as bugs/feature requests.

**Comment by zcbenz** [comment]
#1836 tracks how to make this easier.
