### ISSUE TITLE
Traffic lights showing with titleBarStyle=hidden and frame=false

### ISSUE THREAD

**Issue by paul321** [electron/electron#5697]
There is a bug in OSX when setting BrowserWindow.titleBarStyle to hidden or hidden-inset, the traffic lights are showing over our html traffic lights, we are setting the BrowserWindow with frame=false

See screenshot
![screen shot 2016-05-25 at 9 38 18 pm copy](https://cloud.githubusercontent.com/assets/555502/15552364/aee7e868-22c2-11e6-924e-999facf2137f.jpg)
 

* Electron version: 1.1.0+
* Operating system: OSX

**Comment by danhp** [comment]
You shouldn't configure `titleBarStyle` when using `frame: false`
For a recent discussion about this see https://github.com/electron/electron/issues/5660

**Comment by paul321** [comment]
Ok thank you, it's working. I think we can close it
