### ISSUE TITLE
Ability to store custom data types to the clipboard

### ISSUE THREAD

**Issue by erkyrath** [electron/electron#5698]
- Electron version: 1.1.3

The clipboard API docs are somewhat confusing, but it looks like you can only deal with plain text, RTF, HTML, and image data.

It would be great if I could define arbitrary data types. Ideally, multiple types in a single clipboard.write operator.

This is how the Javascript DOM clipboard API works, and Chromium supports it, so hopefully the capability can be exposed in Electron.

The call might look like

```
clipboard.write({
    text: "Textual representation",
    html: "<p>HTML representation</p>",
    "application/graph-editor": "<xml>...custom representation</xml>",
});
```

(The `type` arguments to all the calls describe the _clipboard_ type, not the data type. The only meaningful arguments are `undefined` and `"selection"`, as far as I can tell. Please let me know if I'm wrong about this.)

**Comment by erkyrath** [comment]
Now that I dig further, the `availableFormats()` call already exposes a list of data types on the clipboard (as MIME type strings). And `read()` *looks* like it takes a data type argument (although I haven't been able to make it work yet).

So this concept is already baked into the API. We just need a version of write() that supports it.

**Comment by seanchas116** [comment]
I tried modifying `write` method to allow custom data types but I couldn't because Chromium's `ScopedClipboardWriter` doesn't have methods for writing data with custom type.
Maybe patching or committing to Chromium is needed...

**Comment by ReDreamport** [comment]
We can set the type/format with `ClipboardEvent` such as:

```javascript
e.clipboardData.setData("application/x-com-data", JSON.stringify(data))
```

So could electron support API like that?

**Comment by ArnonAsquira** [comment]
I understand that you can't write multiple custom formats to the clipboard using ```clipboard.writeBuffer()```,
But when I try to use it write a "Google slides" format data, nothing is written to the clipboard:
("application/x-vnd.google-docs-drawings-page+wrapped" = Google slides format)
```const slideBuffer = Buffer.from('slide format data');
    clipboard.writeBuffer("application/x-vnd.google-docs-drawings-page+wrapped", slideBuffer);```
I am able to read the buffer using 
and consequently, nothing is being pasted when 
```webcontent.paste()``` is called.

That being said, I can read the buffer from the clipboard using ```clipboard.readBuffer()```,
but ```clipboard.availbaleFormtas()``` returns an empty array.

Are some formats not supported at all?
