### ISSUE TITLE
Update docs on "fullscreen: false"

### ISSUE THREAD

**Issue by andruhon** [electron/electron#5699]
* Electron version: 1.1.3
* Operating system: Windows 10 Pro x64

Documentation in https://github.com/electron/electron/blob/master/docs/api/browser-window.md on `fullscreenable` seems to be not exactly true.

`fullscreenable` default value on windows seems to be the same as `fullscreen` option, not just false

For example:
main.js
```JavaScript
  mainWindow = new BrowserWindow({
    width: 800, height: 600,
    minWidth: 800, minHeight: 600,
    center: true,
    fullscreen: false,
    autoHideMenuBar: true,
    frame: false,
    resizable: false
  });
```

somewhere in client code:
```JavaScript
        //...
        let currentWindow = electron.remote.getCurrentWindow();
        currentWindow.setFullScreen(true); //Does not switch to the fullscreen
        //currentWindow.setFullScreen(false) and back to true  works when initial fullscreen:true
        //...
```

**However** the code below seems to work as expected,
main.js
```JavaScript
  mainWindow = new BrowserWindow({
    width: 800, height: 600,
    minWidth: 800, minHeight: 600,
    center: true,
    fullscreen: false,
    fullscreenable: true, //ADDED
    autoHideMenuBar: true,
    frame: false,
    resizable: false
  });
```

somewhere in client code:
```JavaScript
        //...
        let currentWindow = electron.remote.getCurrentWindow();
        currentWindow.setFullScreen(true); //does switch to the fullscreen
        //...
```

**Comment by zcbenz** [comment]
This is actually a feature before we introduced the `fullscreenable` option:

> fullscreen Boolean - Whether the window should show in fullscreen. When explicitly set to false the fullscreen button will be hidden or disabled on OS X. Default is false.

The doc should still be fixed though, it is working for all platforms instead of just OS X.

**Comment by felixrieseberg** [comment]
It is kind of weird that you need to specify `fullscreenable` in order to be able to call the `setFullscreen()` API on Windows. I'll update the docs and submit a PR to fix that behavior.

**Comment by andruhon** [comment]
@felixrieseberg, @zcbenz thank you!
