### ISSUE TITLE
Window edge

### ISSUE THREAD

**Issue by matuzalemsteles** [electron/electron#5702]
* Electron version: v1.1.3
* Operating system: Windows 10 Pro x64

When the **frame** **BrowserWindow** is false, to any possibility to round off the edge of the left or right of the top?

CSS style:

```
header {
  border-top-left-radius: 7px;
  border-top-right-radius: 7px;
}
```

**Comment by zcbenz** [comment]
You can set `transparent` to true to draw the window in arbitrary shape.
