### ISSUE TITLE
Chinese font not rendering in Flash

### ISSUE THREAD

**Issue by chenkaigithub** [electron/electron#5704]
* Electron version:1.1.1-1.1.3
* Operating system:windows7/10

![capture_electron](https://cloud.githubusercontent.com/assets/1229736/15561804/30f6d6ca-232c-11e6-809b-1facfc3413ad.PNG)

I try to load flash in electron with pepflashplayer.dll. But in some cases, the text in flash cannot be shown.Please see the attachment image.
How to solve it? Thank you.

**Comment by zcbenz** [comment]
Does the flash show correctly in Chrome browser?

**Comment by chenkaigithub** [comment]
I tried several versions chrome. All show correctly in Chrome.Please see the image.
![capture](https://cloud.githubusercontent.com/assets/1229736/15660538/6f32a88c-2710-11e6-8917-603091bd2d14.PNG)

**Comment by chenkaigithub** [comment]
I tried the same code in Mac OS. It shows correctly.

**Comment by zcbenz** [comment]
It seems that Electron doesn't set fallback font for the plugin.

**Comment by aztack** [comment]
Same problem: On Windows 7 and 10 Chinese font are rendered as rectangles while rendered correctly on Mac.
Electron 0.37.60, pepflashplayer.dll 21.0.0.157.

here is a snapshot:

![2016-08-09_15-10-26](https://cloud.githubusercontent.com/assets/782871/17507769/2157e21a-5e44-11e6-923e-f99d4c7c0019.png)

Any clues?

**Comment by zcbenz** [comment]
> I investigated the source code of Electron and Chromium, and found there are some questionable code may be the cause of above problem:

Thanks for the hint! It looks very relevant, I'll take a look.

**Comment by zcbenz** [comment]
Closed with #7018.
