### ISSUE TITLE
Voice recognition api throwing "Network error "

### ISSUE THREAD

**Issue by dashingsat** [electron/electron#5705]
* Electron version: 1.1.2
* Operating system: Windows 7 64 bit

We are using node 6.1.0, Chromium 50.0.2661.102, and Electron 1.1.2.

This is the simple code which I am trying to invoke on a button click .

var recognition = new SpeechRecognition();

recognition.lang = 'en-US';
recognition.interimResults = true;
recognition.maxAlternatives = 1;

startButton.onclick = function () {
     console.log("clicked");
     recognition.start();
 }

recognition.onresult = function(event) {
   
    var color = event.results[0][0].transcript;

    console.log("Got result");

    output.value = color ;
}

recognition.onspeechend = function() {
    console.log("detection ends");
    recognition.stop();
}

recognition.onnomatch = function(event) {
    console.log("no match")
}

recognition.onerror = function(event) {
   // alert(event.error);
    console.log("Error:"+event.error)
}
});

**Comment by deepak1556** [comment]
that is because of quota exceed, you can provide your google api key by setting the environment variable `GOOGLE_API_KEY`.
