### ISSUE TITLE
Better support for Linux ARM machines

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#5706]
This issue lists the tasks on making Electron support more ARM machines.
- [x] **Enable building libchromiumcontent locally with Electron together**

http://electron.atom.io/docs/development/build-instructions-linux/#advanced-topics
- [x] **Make it possible to pass ARM related configurations when building**

``` bash
$ ./script/bootstrap.py -v --build_libchromiumcontent \
                           --target_arch=arm \
                           --defines='arm_version=7 arm_float_abi=softfp'
```
- [ ] **Add docs on which ARM related configurations we can provide**
- [ ] **Add support for ARM 64**

``` bash
$ ./script/bootstrap.py -v --build_libchromiumcontent \
                           --target_arch=arm64
```
- [ ] **Provide prebuilt builds for popular ARM machines**

Related: #2343
- [ ] **Enable building without using sysroot**

``` bash
$ ./script/bootstrap.py -v --build_libchromiumcontent \
                           --target_arch=arm
                           --disable_sysroot
```
- [ ] **Enable building with GCC provided by user**

``` bash
$ export CC=my-weird-gcc
$ export CXX=my-werid-g++
$ export CPPFLAGS=--my-weird-flags
$ ./script/bootstrap.py -v --build_libchromiumcontent \
                           --disable_clang
                           --target_arch=arm
```

Feel free to share opinions here if anyone thinks this is not enough for building Electron for your ARM machine.

/cc @iolsen @francoislaberge

**Comment by dantwinkler** [comment]
FYI, it looks like support for arm64 was merged in: https://github.com/electron/electron/commit/1257dee0b524750a1967da6a52e5134f6855e889

Electron for arm64 builds successfully now that libchromiumcontent merged the arm64 support.  Will this be included in future official builds for electron?

**Comment by zeke** [comment]
@groundwater is giving it a shot here: https://github.com/electron/libchromiumcontent/issues/334

**Comment by groundwater** [comment]
We have a PR here #10205 for Linux.

**Comment by galvesribeiro** [comment]
Any updates on getting this out?

**Comment by zcbenz** [comment]
This issue was mostly about libchromiumcontent which had already been removed, so I'm closing it. Please create new issues if there is any problem with arm Linux support.
