### ISSUE TITLE
node integration fails when webSecurity is disabled

### ISSUE THREAD

**Issue by jprichardson** [electron/electron#5712]
* Electron version: 1.2.0
* Operating system: Mac OS X - 10.11.5

I upgraded from 1.1.1 to 1.2.0. 1.2.0 breaks on the following `index.html`:

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<script>
			console.log(process.env.NODE_ENV)
		</script>
	</head>
	<body>
		<div id="app-container"></div>
	</body>
</html>
```

Error:

```
Uncaught ReferenceError: process is not defined
```

**Comment by jprichardson** [comment]
I should have added, that `index.html` is passed to `loadURL` on an instance of `BrowserWindow`.

**Comment by davemackintosh** [comment]
I'm seeing the same behaviour, Have tried setting `nodeIntegration` to true when creating the window but `module`, `global`, `require` and `process` are all undefined.

**Comment by kevinsawicki** [comment]
@jprichardson @davemackintosh what options are you passing to the `BrowserWindow` constructor?

**Comment by davemackintosh** [comment]
```
const {BrowserWindow} = require("electron")
let window = new BrowserWindow({
  width: 1266,
  height: 758,
  minWidth: 1266,
  minHeight: 758,
  resizable: true,
  show: false,

  // Disable some stuff we don't want or need.
  webPreferences: {
    webgl: false,
    webaudio: false,
    webSecurity: false,
    nodeIntegration: true,
    allowDisplayingInsecureContent: true,
    allowRunningInsecureContent: false
  }
})
```

**Comment by davemackintosh** [comment]
Rather interestingly, in my `app-ready`, I open a window that does some asset updating. That has the Node context. The subsequent window (same options, different size) doesn't have the Node context.

**Comment by kevinsawicki** [comment]
I was able to reproduce, it looks like it might be because `webSecurity: false` is set

**Comment by davemackintosh** [comment]
@kevinsawicki confirmed. Setting to `true` brings the app back up.

**Comment by rosshinkley** [comment]
I wasn't able to reproduce this problem exactly, but `webSecurity` being disabled seems to cause `webContents.executeJavascript()` to fail regardless of whether `nodeIntegration` is set or not.  Symptoms of the same problem?

**Comment by Oceanswave** [comment]
+1
