### ISSUE TITLE
[WINDOWS] spawn stdio not piping

### ISSUE THREAD

**Issue by farfromrefug** [electron/electron#5713]
* Electron version: 1.1.3
* Operating system: Windows 10 64 bit

I have that script in my app:
```javascript
const child = spawn(process.execPath, [info.path], {
            env: { "ATOM_SHELL_INTERNAL_RUN_AS_NODE": "0" },
            shell: false,
            detached: true
          });
          child.unref();
          child.stdout.on('data', (data) => {
            console.log('received data', data);
            term.write(data.toString());
          });

          child.stderr.on('data', (data) => {
            console.log('received data', data);
            term.write(data.toString());
          });
```
The idea is to spawn a node script and output its log within the main app view.

Now this works great on OSX, however it does not work on windows. The stdout and stderr are always output in the main process "console".
It feels like ```stdio: 'inherit' is always used.

**Comment by zcbenz** [comment]
I can reproduce this, it is probably because Electron is a GUI app and Windows doesn't pipe the output to console.

**Comment by farfromrefug** [comment]
@zcbenz well i see the output in the console if i run my app from the console.
So i am not sure this is it.
i am wondering if it s related to this issue https://github.com/nodejs/node-v0.x-archive/issues/3871

**Comment by farfromrefug** [comment]
@zcbenz I managed to get it to work even before your PR :D
```ELECTRON_NO_ATTACH_CONSOLE``` seems to have done the trick for me.
Will report on your PR when released.
Thanks for your work
