### ISSUE TITLE
Can't seem to get registerHttpProtocol to work

### ISSUE THREAD

**Issue by victorporof** [electron/electron#5714]
* Electron version: 1.2.0
* Operating system: OS X

```js
electron.protocol.registerStandardSchemes(['foobar', 'http', 'https']);

app.on('ready', function() {
  electron.protocol.registerHttpProtocol('foobar', (request, callback) => {
    const redirectPath = `http://www.google.com`;
    callback({ method: request.method, referrer: request.referrer, url: redirectPath });
  }, e => { if (e) { console.log(e); } });
});
```

A webview somewhere gets its src set to "foobar://baz", however a blank window appears. The page is perpetually in a load state, as only the `did-start-loading` and `did-get-response-details` events get triggered on the webview.

If I redirect to `http://localhost:{port}/foobar`, my server does receive the request and responds properly. However, the webview in electron is still blank. Loading that address in a different browser works as expected.

What am I missing? Is there something more I need to do to get `registerHttpProtocol` working?

**Comment by deepak1556** [comment]
Regressed since `v1.1.0`

**Comment by victorporof** [comment]
FWIW I've tested in `v1.1.0` with the same results.

**Comment by deepak1556** [comment]
The current logic fails since `chrome50` upgrade, if its possible you can try with versions `<=1.0.2` where it should work fine.
