### ISSUE TITLE
Native Modules linked differently to MSVCRT than Electron proper on Win32

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#5716]
Moving Electron proper to compile MSVCRT statically as part of #5602 has a confusing consequence - since native node modules will still be linked dynamically with MSVCRT, developers who ship their app will now start seeing missing DLL errors (maddeningly, pointing to a file that exists!) when they ship to machines other than ones with VS installed, and since Electron itself isn't shipping MSVCRT DLLs, we're not solving this problem for users anymore.

I know it's hideous, but I think we should just bite the bullet and ship those like 20 DLLs, then send pages upon pages of hate mail to @felixrieseberg as therapy (just kidding! :smiley_cat:)  This will make it so the vast majority of Electron developers can just install VS2015 and build native modules, and not have to think about C++ runtimes

**Comment by paulcbetts** [comment]
Hm, this seems to be even worse than I previously expected, I'm investigating today

**Comment by felixrieseberg** [comment]
Yay fan mail

![](https://i.imgur.com/vIf0lAD.gif)

**Comment by zcbenz** [comment]
Node's native modules link with VC++ statically by default, the missing DLL problem is probably caused by some third party DLLs.

**Comment by paulcbetts** [comment]
Hm, I was seeing edge.node linked to MSVCRT dynamically, but it's also a Special Snowflake. I'll look into it more

**Comment by miniak** [comment]
I definitely vote for shipping the runtime. It's a lot of files, but so what? The users don't look into the the app folder.

**Comment by paulcbetts** [comment]
I think this is just edge.js, closing this
