### ISSUE TITLE
Loading 3rd party vendor folder?

### ISSUE THREAD

**Issue by jdell64** [electron/electron#5724]
I'm having an issue getting any third party libraries to load up in electron (angular2 in this case).

Errors:

````
Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///vendor/systemjs/dist/system.src.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///vendor/reflect-metadata/Reflect.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///vendor/zone.js/dist/zone.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///vendor/es6-shim/es6-shim.js Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:32 Uncaught ReferenceError: System is not defined
````
How do i reference the vendor files in my `index.html` file?

How I made this project: 

- I used the angular CLI tool to make an angular2 project. `ng new myapp`
- I used gulp to create an electron-package dir
- run `electron ./electron-package/`

full code:
https://github.com/jdell64/electronAngularBoilerplate/tree/so-37447020

* Electron version: 1.1.1
* Operating system: Ubuntu 16.04 LTS

I also asked it on SO:
http://stackoverflow.com/questions/37447020/electron-angular2-loading-vendor-lib

**Comment by paulcbetts** [comment]
Do you really have a `/vendor` folder on your computer?

**Comment by jlord** [comment]
Ditto ☝️ Your app is looking for them in a `/vendor` folder on your computer and not somewhere within the project. They also don't seem to be in the project.

This looks to be an issue of using the correct path. 

> How do i reference the vendor files in my index.html file?

You can reference them as is typical in HTML with `<script src="">` but you can also use Node requires as is done in the Electron API Demos app https://github.com/electron/electron-api-demos/blob/master/index.html#L103.

**Comment by jdell64** [comment]
When I use require, it can't find other files referenced by angular2

**Comment by paulcbetts** [comment]
@jdell64 I would try to follow a tutorial specifically geared toward Electron, I think that ng new` is assuming it's being hosted over HTTP and is trying to use protocol-relative URLs  (i.e. `//foo/bar/`)

**Comment by jdell64** [comment]
So, I've prepeneded it with

    __dirname +

In a require function as well, and it gets passed those four, but then
inside @angular, that tries to call a different file...

I've looked at a number of tutorials with angular2+electron, and they all
package assets differently. Some preface anything with localhost and just
have node running at the same time, others do all sorts of minifying, but
all of them were published months ago (which in JavaScript time is like
millennia). Since most of these, angular2 was renamed and a number of
packages have changed.

Sorry for bugging you. I know this isn't really a bug, I've just been
working on this for 2 days now with no results. And yes, I am very new at
this.

On Thursday, May 26, 2016, Paul Betts <notifications@github.com> wrote:

> @jdell64 <https://github.com/jdell64> I would try to follow a tutorial
> specifically geared toward Electron, I think that ng newis assuming it's
> being hosted over HTTP and is trying to use protocol-relative URLs (i.e.
> //foo/bar/`)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/electron/electron/issues/5724#issuecomment-222002521>
>


-- 

--
Richard J Tindell

Ps 102:18- "This will be written for the generation to come, That a people
yet to be created may praise the Lord."

**Comment by jdell64** [comment]
Sorry, that last update wasn't very clear... this is what I've tried:

```javascript
  require('./vendor/es6-shim/es6-shim.js');
  require("./vendor/reflect-metadata/Reflect.js");
  require("./vendor/systemjs/dist/system.src.js");
  require("./vendor/zone.js/dist/zone.js");
  
    System.import(__dirname + '/system-config.js').then(function () {
      System.import(__dirname + '/main');
    }).catch(console.error.bind(console));
```

Which gets me past that last error, but is unable to find thigns inside the package:

```
Unhandled Promise rejection: 
	Error loading file:///home/jeff/dev/ang_proj/electronAngularBoilerplate/electron-package/main ; Zone: <root> ; Task: Promise.then ; Value: Error: (…)consoleError @ /home/jeff/dev/ang_proj/electronAngularBoilerplate/electron-package/vendor/zone.js/dist/zone.js:461

Error: Uncaught (in promise): Error: (…)consoleError @ /home/jeff/dev/ang_proj/electronAngularBoilerplate/electron-package/vendor/zone.js/dist/zone.js:463

```

**Comment by jdell64** [comment]
OKAY! I think I got it to work:

```
    require('./system-config.js');
    require('./main.js');
  
    //  System.import(__dirname + '/system-config.js').then(function () {
    //   System.import(__dirname + '/main.js');
    // }).catch(console.error.bind(console));
```

I don't know why I can't use the systemjs imports, but commenting them out seems to have worked... I hope that does't come back to bite me later.
