### ISSUE TITLE
Webview executeJavaScript method not working in Electron 1.2.0 but 1.1.3 is okay

### ISSUE THREAD

**Issue by frankhale** [electron/electron#5727]
Electron version: 1.2.0
Operating system: Windows 10 x64

When I invoke the webview executeJavaScript method under Electron 1.2.0 it appears as though my code is not executed. If I execute the method under Electron 1.1.3 everything is okay and my code gets executed.

**Comment by LukePulverenti** [comment]
Confirmed here as well.

**Comment by djpereira** [comment]
Same here. The problem happens with OSX also. I am using the webview.preload.
