### ISSUE TITLE
Installation error on boostrap step 

### ISSUE THREAD

**Issue by amtrek** [electron/electron#5729]
* Electron version:1.2.0
* Operating system: Windows 8.1

I was working on installation but encountered an WindowError at very first step while trying to do 
python script\bootstrap.py -v

 WindowsError: [Error 3] The system cannot find the path specified: 'MyPathName\\ElectronApp\\electron\\script\\vendor\\requests'

Can anyone help with the issue ? I am fairly new to python, this seems like a python exception

**Comment by zcbenz** [comment]
You don't need to run bootstrap script if you just want to use electron, for more questions
I suggest seeking help from [the community](https://github.com/electron/electron#community).

**Comment by solomonope** [comment]
If you want to just use electron, you don't need the to run the bootstrap script.

I had the same problem while trying to build electron, you need to run this bootstrap command from the root of your electron folder and not from the script folder, that solved it for me.
