### ISSUE TITLE
Can not use node-serialport,gentlemen please help me !

### ISSUE THREAD

**Issue by kcsm-lqk** [electron/electron#5730]
* Electron version:V1.1.0
* Operating system: WIN7 32 

Masters,please help me.I  want to operate serial port and I use node-serialport,but it did not work.

log:
C:\Users\Administrator\node_modules\bindings\bindings.js:91 Uncaught Error: Could not locate the bindings file. Tried:
 → C:\Users\Administrator\node_modules\serialport\build\serialport.node
 → C:\Users\Administrator\node_modules\serialport\build\Debug\serialport.node
 → C:\Users\Administrator\node_modules\serialport\build\Release\serialport.node
 → C:\Users\Administrator\node_modules\serialport\out\Debug\serialport.node
 → C:\Users\Administrator\node_modules\serialport\Debug\serialport.node
 → C:\Users\Administrator\node_modules\serialport\out\Release\serialport.node
 → C:\Users\Administrator\node_modules\serialport\Release\serialport.node
 → C:\Users\Administrator\node_modules\serialport\build\default\serialport.node
 → C:\Users\Administrator\node_modules\serialport\compiled\6.1.0\win32\ia32\serialport.node

**Comment by felixrieseberg** [comment]
Hi! Your trouble is that node-serialport is a native addon. Please see the [docs](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) for help (in Chinese [here](https://github.com/electron/electron/blob/master/docs-translations/zh-CN/tutorial/using-native-node-modules.md)).

**Comment by bhaveshgohel** [comment]
@Xiao-Yaran :  Try this [solution](https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/538#issuecomment-235740495). :smiley:
