### ISSUE TITLE
node environment is lost when setting webSecurity to false

### ISSUE THREAD

**Issue by taroxd** [electron/electron#5733]
* Electron version: 1.2.0
* Operating system: Windows 10 Build 10586
* This bug can be reproduced with one simple line of code: https://github.com/taroxd/electron-quick-start/commit/79f4cab82f301bead31cd353f2212119c8c538ea

  In the devtool, We get
```
index.html:10 Uncaught ReferenceError: process is not defined
```

**Comment by enlight** [comment]
Dupe of #5712
