### ISSUE TITLE
Doubt collision to twitter login page

### ISSUE THREAD

**Issue by sokcuri** [electron/electron#5735]
* Electron version:1.2.0 or lower
* Operating system: Windows 10
![1234asdf](https://cloud.githubusercontent.com/assets/9635637/15609322/59627da6-245a-11e6-9415-57f2122f16ff.png)

through electron, Can't input password field in twitter login page. i think electron sth collision twitter stylesheet.

Below code is example.

main.js
```
const electron = require('electron');
const {app} = electron;
const {BrowserWindow} = electron;

let win;

function createWindow() {
  win = new BrowserWindow({width: 800, height: 600});
  win.loadURL('https://twitter.com/login');

  win.on('closed', () => {
    win = null;
  });
}

app.on('ready', createWindow);
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (win === null) {
    createWindow();
  }
});
```

**Comment by jlord** [comment]
This is actually a problem with the jQuery on Twitter.com. There are some tips in https://github.com/electron/electron/issues/4832#issuecomment-198110679 & #254.

Closing as a dupe.
