### ISSUE TITLE
Error launching app

### ISSUE THREAD

**Issue by atdrago** [electron/electron#5743]
* Electron version: 1.2.0
* Operating system: Mac OS X

Originally posted here: https://github.com/electron/electron-rebuild/issues/70, but I think this might be a better place for it. The factor that's causing the error is Electron v1.2.0 (via electron-prebuilt v1.2.0).

Thank you for any help or suggestions!

> I've been getting this strange error referencing `console.log(process.versions.modules)` the past few days in my Travis builds. Just noticed it this morning locally. It happens after I run `./node_modules/.bin/electron-rebuild`
> 
> I'm running Node v6.1.0, electron-prebuilt v1.2.0, and electron-rebuild v1.1.4 (though it seems to be happening with all electron-rebuild v1.1.x).
> 
> ![screen shot 2016-05-27 at 10 23 43 am](https://cloud.githubusercontent.com/assets/144225/15615858/73629390-23f5-11e6-8c39-a8e4a66532fc.png)
> 
> I don't believe I changed anything for this to happen, besides doing an `npm install` this morning. Any ideas what's going on here?

**Comment by kevinsawicki** [comment]
How are you launching the app?

**Comment by atdrago** [comment]
I'm not. I just run `./node_modules/.bin/electron-rebuild` and see that error.

Here are the steps:
1. `npm install`
2. `./node_modules/.bin/electron-rebuild`
3. The above error.

This only happens when I install v1.2.0. I'm not seeing it with v1.1.3. Do you think it's an `electron-rebuild` issue?

**Comment by kevinsawicki** [comment]
> Do you think it's an electron-rebuild issue?

Yeah, just opened a pull request https://github.com/electron/electron-rebuild/pull/72

Closing this here.

**Comment by atdrago** [comment]
Thank you!
