### ISSUE TITLE
Can't disable maximizable gumdrop with frameless windows

### ISSUE THREAD

**Issue by davej** [electron/electron#5745]
* Electron version: Reproduced in 1.1.3 and 1.2.0 (was working in 0.37.7)
* Operating system: OS X

If a window has `transparent: true` then the window will always have the maximizable control available even when set to `false`. To reproduce, simply do:

```js
const win = new BrowserWindow({
  width: 100,
  height: 100,
  transparent: true,
  maximizable: false,
});

win.loadURL(url);
```

![image](https://cloud.githubusercontent.com/assets/26971/15623329/61186cd0-246a-11e6-8bee-49feab067537.png)

**Comment by danhp** [comment]
Also happening with frameless  windows.
Seems like a regression due to https://github.com/electron/electron/pull/5557

**Comment by xMrWhite** [comment]
Should the fullscreen or all gumdrops be hidden?

**Comment by davej** [comment]
Just the maximize button in my code example. I presume @danhp edited the title to 'gumdrops' because he found that this bug applies to `minimizable` and `closable` options too.

**Comment by xMrWhite** [comment]
The previous [commit](https://github.com/electron/electron/commit/3fedea4b9ec419e44b5ed24b0a3e9f501c0fa93f) specifically forces the buttons to be shown on frameless windows. I can't seem to find the reason for this, but would be nice if @zcbenz would chime in before I reverse that.

**Comment by danhp** [comment]
Ok my fault, I forgot to build before testing all of the cases.
@davej was correct when he said it only applied to `maximizable`. Should be a tiny fix.

**Comment by zcbenz** [comment]
The `transparent` option is required to be used together with `frame: false`, and the behavior is undefined if you use `transparent: true` in a window with frame. This rule is not enforced in code, but if you don't follow it you are on your own if you met any bug.

For this bug, I'm cool fixing it if it doesn't take much efforts.

@xMrWhite That commit is part of #5557 which fixes another bug.

**Comment by danhp** [comment]
@zcbenz Something changed so that [this code block](https://github.com/electron/electron/blob/master/atom/browser/native_window_mac.mm#L516) is not behaving correctly.

A better example is
```
mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  titleBarStyle: 'hidden',
  minimizable: false,
  maximizable: false
});
```
Which creates this:
![image](https://cloud.githubusercontent.com/assets/3745612/15638323/07576618-25ed-11e6-9a81-db90b55bbee8.png)

Calling `setMaximizable(false)` afterwards will disable the button so the function itself is fine.

**Comment by davej** [comment]
For anyone looking for a quick hacky fix until this is resolved then @danhp's suggestion of doing `setMaximizable(false)` works well.
 
```js
const win = new BrowserWindow({
  // ...
  maximizable: false
});

win.setMaximizable(false); // HACK
```
