### ISSUE TITLE
ses.setProxy proxyRules don't allow proxy bypass configuration

### ISSUE THREAD

**Issue by tejohnso** [electron/electron#5746]
>proxyRules = schemeProxies[";"<schemeProxies>]
schemeProxies = [<urlScheme>"="]<proxyURIList>
urlScheme = "http" | "https" | "ftp" | "socks"
proxyURIList = <proxyURL>[","<proxyURIList>]
proxyURL = [<proxyScheme>"://"]<proxyHost>[":"<proxyPort>]

**Comment by deepak1556** [comment]
`ses.setProxy` takes a PAC script, its easy to specify proxy bypass configurations there. Is there a reason for not using PAC script ?

**Comment by tejohnso** [comment]
I dont know the rules ahead of time.  It seems kludgy to have to provide a URL to a file that contains a dynamically generated JavaScript function as a parameter to a JavaScript function call.  But if it's the only way I'll give it a shot.

**Comment by deepak1556** [comment]
>  I dont know the rules ahead of time.

hmm we can add a `proxyBypassRules` option.

**Comment by zcbenz** [comment]
As listed in the examples of the `ses.setProxy` API, `direct://` represents for no proxy:

```
http=foopy,direct:// - Use HTTP proxy foopy for http URLs, and use no proxy if foopy is unavailable.
```

**Comment by deepak1556** [comment]
@zcbenz I believe the OP wanted certain hosts to bypass proxy while not others, this cant be achieved with `proxyRules` while certainly can be achieved with a PAC script but since the OP wants to dynamically specify the rules, PAC might turn out useless.

**Comment by zcbenz** [comment]
@deepak1556 The `ProxyConfig` of Chromium is not able to set proxy rule per host as far as I know.

The PAC script can be set dynamically, users can always generate a PAC script on the fly and then save it to filesystem and pass its path to `setProxy`.

**Comment by deepak1556** [comment]
Yup `proxyconfig` cant set per host but we can set a bypass list on the config https://code.google.com/p/chromium/codesearch#chromium/src/net/proxy/proxy_config.h&q=proxyconfig&sq=package:chromium&l=121

> The PAC script can be set dynamically, users can always generate a PAC script on the fly and then save it to filesystem and pass its path to setProxy.

:+1:

**Comment by zcbenz** [comment]
@deepak1556 I didn't know that, it is definitely a thing we can have.
