### ISSUE TITLE
showOpenDialog fails after signing for MAS

### ISSUE THREAD

**Issue by Allendar** [electron/electron#5748]
* Electron version: 1.2.0
* Operating system: OS X 10.11.5

The following code works perfectly while running with `electron ./app/`. No errors, warnings or output:

```
ipc.on('open-save-folder-dialog', function (event) {
    dialog.showOpenDialog({
        properties: ['openDirectory', ]
    }, function (dirs) {
        if (dirs) event.sender.send('selected-directory', dirs)
    })
})
```

But when I code sign the app validly (Apple's Application Loader passes the app until the actual submit-button) with `codesign-osx-sign` like so:

```
electron-osx-sign "$APP_DIR/$FINAL_NAME.app" --platform=mas --entitlements="$PWD/parent.plist" --entitlements-inherit="$PWD/child.plist"
electron-osx-flat "$APP_DIR/$FINAL_NAME.app" "$APP_DIR/$FINAL_NAME.pkg" --platform=mas
```

..where the plist files are the standard entitlement files as recommended on the Electron Docs pages. The app does nothing at all when triggering it. It actually comes into the call itself when debugging output there, but the the `dialog.showOpenDialog` never gives a callback. I also notice a very slight bump in performance when triggering the function, as if something is trying to be done, but doesn't work or so. Before the trigger on the event nothing special happens; just a simple jQuery click event catch.

This `ipc` code works, so it's not that nothing works in the events:

```
ipc.on('open-no-valid-files-dialog', function (event) {
  dialog.showErrorBox('No valid files', 'No valid images found');
})
```

And then this one also doesn't work (I have it bound in the menu to `CMD+O` and a  button event trigger:

```
ipc.on('open-select-files-dialog', function (event) {
    dialog.showOpenDialog({
        properties: ['openFile', 'openDirectory', 'multiSelections']
    }, function (dirs) {
        if (dirs) event.sender.send('selected-files', dirs)
    })
})
```

Please ask me more things to supply or tests if my case is not complete enough.

Thank you in advance for taking your time.

**Comment by herrmannplatz** [comment]
Have you tried to add
```
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
```
to your entitlements (parent.plist)?

Check [Apple Documentation](https://developer.apple.com/library/mac/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW1) to see if your app needs more.

**Comment by Allendar** [comment]
That instantly worked! Thank you so much!! I was pooping my pants in fear that this would totally block me releasing my app lol!

Thank you thank you thank you! Loves <3
