### ISSUE TITLE
QTKit deprecated on MAS submit

### ISSUE THREAD

**Issue by Allendar** [electron/electron#5749]
* Electron version: 1.2.0
* Operating system: 10.11.5

My app just got rejected because of deprecated errors, yet I'm not using any exotic features. I'm also using the latest version of Electron:

> Deprecated API Usage - Apple no longer accepts submissions of apps that use QuickTime or QTKit APIs.

I saw this question : http://stackoverflow.com/questions/33591941/apple-no-longer-accepts-submissions-of-apps-that-use-quicktime-or-qtkit-apis-of

But no one seems to know how to fix it.

If I didn't adjust anything exotic, then everyone must have this issue right? What can be done to make Apple not notice this anymore?

**Comment by Allendar** [comment]
This is my worker script:

```
#!/bin/bash

# Settings
FINAL_NAME="My App Name
APP="MyAppName"
KEY_NAME="Firstname Surname"
KEY_ID="X7XXX3XX2X"
CATEGORY="public.app-category.productivity"
BUNDLE_IDENTIFIER="com.company.product"
APP_VERSION="1.0.2"
TEAM_ID="X7XXX3XX2X"
ICON_FILE="$PWD/icon.icns"
ASSETS_DIR="$PWD/app"

# Build
PROJECT_DIR="$PWD"
APP_DIR="$PROJECT_DIR/$APP-darwin-x64"
APP_CONTENTS="$APP_DIR/$APP.app/Contents"
APP_RESOURCES="$APP_CONTENTS/Resources"
PLIST="$APP_CONTENTS/Info.plist"

rm -rf "$APP_DIR" && rm -rf "$APP_DIR"
electron-packager "$ASSETS_DIR" --platform=darwin --arch=x64 --asar=true
cp "$ICON_FILE" "$APP_RESOURCES/icon.icns"
rm "$APP_RESOURCES/electron.icns"
rm "$APP_DIR/LICENSE"
rm "$APP_DIR/LICENSES.chromium.html"
rm "$APP_DIR/version"

# Preferences
defaults write "$PLIST" LSApplicationCategoryType -string "$CATEGORY"
defaults write "$PLIST" CFBundleIdentifier -string "$BUNDLE_IDENTIFIER"
defaults write "$PLIST" CFBundleShortVersionString -string "$APP_VERSION"
defaults write "$PLIST" CFBundleVersion -string "$APP_VERSION"
defaults write "$PLIST" ElectronTeamID -string "$TEAM_ID"
defaults write "$PLIST" CFBundleIconFile -string "icon.icns"
chmod 777 "$PLIST"

# Signing and Packaging
mv "$APP_DIR/$APP.app" "$APP_DIR/$FINAL_NAME.app"
electron-osx-sign "$APP_DIR/$FINAL_NAME.app" --platform=mas --entitlements="$PWD/parent.plist" --entitlements-inherit="$PWD/child.plist"
electron-osx-flat "$APP_DIR/$FINAL_NAME.app" "$APP_DIR/$FINAL_NAME.pkg" --platform=mas
```

**Comment by Allendar** [comment]
These are my only dependencies:

```
        "animate.css": "^3.5.1",
        "font-awesome": "^4.6.1",
        "image-size": "^0.5.0",
        "jimp": "^0.2.24",
        "jquery": "^2.2.3",
        "node-mkdirp": "0.0.1"
```

**Comment by herrmannplatz** [comment]
You should use the decicated MAS version of eletron. Newest electron-packager should be able to download this version. Try too use.

`electron-packager "$ASSETS_DIR" --platform=mas --arch=x64 --asar=true`

**Comment by Allendar** [comment]
Ohh I didn't know there was that one too. You helped me again! Thanks so much!. First time building with Electron. Normally used to just giving Xcode a bump and submission is easy then.

It got accepted now and is waiting for review :)

Learning new things everyday <3
