### ISSUE TITLE
Synchronous communication from main process to renderer process

### ISSUE THREAD

**Issue by lastmjs** [electron/electron#5750]
It looks like synchronous message passing from the renderer process to the main process is pretty easy with `ipcRenderer.sendSync` or using `require('electron').remote` and calling functions on the main process, which is done synchronously. But I would really like to be able to send messages or call functions synchronously from the main process to the renderer process. It looks like ipc main only allows asynchronous message passing, and webContents.executeJavaScript can only be done asynchronously as well.

**Comment by zcbenz** [comment]
It is extremely easy to cause a dead lock if we allow sending synchronous message from main process to the renderer process, and Chromium doesn't provide this ability for this reason.

I'm closing this as won't fix.
