### ISSUE TITLE
Feature Request: MenuItem to have a default item

### ISSUE THREAD

**Issue by stanleyxu2005** [electron/electron#5752]
* Electron version: 1.2.0
* Operating system: Windows 7

It'd be great, if we can specify one menu item to be default. Optically, it will be bold, which means clicking on the tray icon will click this menu item automatically. Can this feature request be considered?

**Comment by zcbenz** [comment]
The menu implementation of Electron is using Chromium's custom-drawn menu, which unfortunately doesn't have the concept of default menu item, so I'm closing this as won't fix.
