### ISSUE TITLE
The icon of a window is reset under some situations

### ISSUE THREAD

**Issue by taroxd** [electron/electron#5754]
* Electron version: 1.1.3 & 1.2.0
* Operating system: Windows 10 Build 10580

The icon of a window is reset after minimizing it for a short period of time (about 2 minutes), hiding it and showing it again.
An app to reproduce this bug: https://github.com/taroxd/electron-quick-start

**Comment by cedx** [comment]
Same problem here with a personal app. Electron 1.2.0 and Windows 10.
Used the same actions to reproduce the bug: minimizing the window, waiting, showing the window, hiding it (repeat)... and after an undetermined amout of time or trials, the icon is reset to the Electron one.
