### ISSUE TITLE
Electron quick-start app renders as black rectangle in Ubuntu 14.04, unless --disable-gpu is supplied

### ISSUE THREAD

**Issue by halfer** [electron/electron#5755]
I just tried [the quickstart instructions](http://electron.atom.io/docs/tutorial/quick-start/) and started up an Electron app in three commands, woop! However I noticed a rendering bug, even with this simple app.

I started the app thus:

    node_modules/.bin/electron main.js

This renders the app as an entirely black window with a native-looking title bar. When I use Show Workspaces, it reveals my 3x3 desktops in a grid view. If the screen that was previously shown contains a running Electron app, a black square equal to the size of the app window "floats" over the top of the grid display.

However I have discovered a `--disable-gpu` switch. If I add that to my console command, the app renders correctly and there is no display glitch in Show Workspaces. I run my Ubuntu/Unity desktop in a VirtualBox VM.

I run a good number of apps in this environment (Firefox, NetBeans, LibreOffice, all the usual Ubuntu system apps) and I've not experienced this with anything else. Is there a way I can dump useful graphics info so as to aid your debugging?

* Electron version: v1.2.0
* Operating system: Ubuntu 14.04 LTS with Unity desktop running in VirtualBox 5.0.20 with 3D acceleration enabled

**Comment by zcbenz** [comment]
VirtualBox is known to not work well with Chromium browser, I'm afraid there is nothing we can do to fix this on Electron's side. I suggest reporting this to [Chromium's issues list](https://crbug.com) instead.

Closing as won't fix.

**Comment by halfer** [comment]
Urgh, need an Google account for that. No thanks! :smirk_cat:

**Comment by halfer** [comment]
For anyone experiencing this issues with Electron/VirtualBox, [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=608215) might be the issue. A recent VB update produced a pointer regression in Ubuntu, and I wouldn't be surprised if the Guest Additions fix in that link resolved this too.

@zcbenz - do you have a reason to suspect Chromium rather than VirtualBox? My money would be on the latter, just because I've experienced some long-standing (but tolerable) display problems here, such as not being able to screenshot from inside a VM - results are all black).
