### ISSUE TITLE
Webview cancelled requests

### ISSUE THREAD

**Issue by adlk** [electron/electron#5758]
* Electron version: 1.2.0
* Operating system: OSX 10.11.5

I'm currently working on an Electron (1.2.0) project where I'm heavily dependent of webviews. Everything works so far except when I try to access `https://twitter.com`, `https://tweetdeck.twitter.com` and lately even on `https://slack.com/checkcookie`.

Whenever I try to login some requests gets canceled and I'm not logged in.

However, if I take a look at the stored cookies I can see a newly generated access token – so when I refresh the site I'm logged in. 

The webview initialization is very simple:

    <webview src="https://tweetdeck.twitter.com" partition="persist:tweetdeck"></webview>

The first time I saw this behaviour (on tweetdeck) was with Electron 36.7 and after upgrading to 1.2.0 it even happens with Slack. 

![dev tools network](http://i.stack.imgur.com/uVJCo.png)

**Comment by deepak1556** [comment]
Related to https://github.com/electron/electron/issues/3471

**Comment by zcbenz** [comment]
I'm merging this to #3471.
