### ISSUE TITLE
Cannot print unicode to console on Windows

### ISSUE THREAD

**Issue by inukshuk** [electron/electron#5761]
I noticed that I cannot print characters such as 'ρ' or 'β' from Electron to the console on Windows (works fine on Linux and OS X). I tried this using the default command prompt and power shell; also made sure both terminals were printing the characters otherwise (works fine with `node -e "console.log('β')"`). When printing from Electron it does not work (tested in both Main and Renderer with `console.log` and `process.stdout.write`).

Possibly related to #2311
- Electron version: 1.1.3
- Operating system: Windows 8.1

**Comment by felixrieseberg** [comment]
@ritazh will take a look :eyes:

**Comment by MingyaoLiu** [comment]
is this fixed or still open?

**Comment by inukshuk** [comment]
I can still observe this on Windows 10 with Electron 1.6.1.

**Comment by gucong3000** [comment]
```shell
$ electron -v
v1.8.0

$ ver
Microsoft Windows [版本 10.0.15063]

$ chcp
活动代码页: 936

$ electron test.js
涓枃

$ node test.js
中文

$ chcp 65001
Active code page: 65001

$ electron test.js
中文

$ node test.js
中文
```

**Comment by codebytere** [comment]
This should be fixed on the most recent versions of Electron!

**Comment by Eskibear** [comment]
any updates? @codebytere

**Comment by TonyBogdanov** [comment]
5 years later and this still seems to be an issue.

**Comment by FirokOtaku** [comment]
A solution is to modify launch scripts in `package.json` to be like this:

```json
{
  "scripts": {
    "dev": "chcp 65001 && electron-vite dev",
  }
}
```

(use `&&` operator to execute multiple commands in single line)

**Comment by TonyBogdanov** [comment]
@FirokOtaku Yes! This seems to be the only thing that works at the moment. Thank you!

**Comment by Seblor** [comment]
Is there a solution or workaround for a production build ?

I just had a user with a cyrillic Windows setup and they need to run `chcp 65001` before running my app in the terminal for it to work...

**Comment by Kane-Kuroneko** [comment]
same issue here , and now is 2024/10  ![Image](https://github.com/user-attachments/assets/2ffc3d55-a5ac-4a5e-878e-d61cd47eb58c)
![Image](https://github.com/user-attachments/assets/1dcfe179-1f0a-4cbf-b874-fcfb943fc0a8)

**Comment by enihsyou** [comment]
I encountered the same issue, even when trying the [Electron Tutorial First App]. After spending quite some time searching for solutions and experimenting, I finally arrived here. On Windows, different shells require different settings.

[Electron Tutorial First App]: https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#running-an-electron-app

In CMD, just using chcp can make it work

```bat
R:\my-electron-app>chcp 936
Active code page: 936
                                                                                 
R:\my-electron-app>npx electron main.js
Hello from Electron 馃憢

R:\my-electron-app>chcp 65001
Active code page: 65001

R:\my-electron-app>npx electron main.js
Hello from Electron 👋
```

However, in PowerShell, setting chcp alone does not work. Instead, you need to use `[Console]::OutputEncoding = [System.Text.Encoding]::UTF8`.
I resolved this by adding it to my `$PROFILE` configuration file. There are other methods, such as modifying the registry globally or append a setup command in package.json. You can search for those if needed.

```powershell
$ chcp
Active code page: 936

$ node main.js
Hello from Electron 👋
# [comment]: node is working correctly

$ npx electron main.js
Hello from Electron 馃憢
# [comment]: but not electron

$ chcp 65001
Active code page: 65001
# [comment]: when switch to UTF-8 codepage on powershell

$ npx electron main.js
Hello from Electron 馃憢
# [comment]: it's not taking effect

$ [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$ npx electron main.js
Hello from Electron 👋
# [comment]: but change output encoding works

$ chcp 936
$ npx electron main.js
Hello from Electron 👋
# [comment]: even if not using chcp beforehand
```

<details>
<summary>System and Environment Information</summary>

```powershell
$ pwsh -v             
PowerShell 7.5.0

$ cmd -v
Microsoft Windows [版本 10.0.26100.3194]
(c) Microsoft Corporation。保留所有权利。

$ npx electron -v
v34.2.0

$ node -v
v22.13.1

$ Get-Content main.js 
console.log('Hello from Electron 👋')
process.exit(0)
```
</details>
