### ISSUE TITLE
Crash with node-usb sending to sleep

### ISSUE THREAD

**Issue by armaseg** [electron/electron#5762]
* Electron version: 1.2.0
* Operating system: Windows 7 64bits
* Node: 6.1.0

I've been using electron with [node-usb](https://github.com/nonolith/node-usb) installing it like [this](https://discuss.atom.io/t/use-node-usb-inside-electron/16748) to be able to use it on electron: It works really good but electron crashs only when I send the pc to sleep.

You can reproduce this behavior using the [First Electron App](https://github.com/electron/electron/blob/master/docs/tutorial/quick-start.md#write-your-first-electron-app):
- Add at the beginning of the main.js file this line:
```javascript
const  usb = require('usb');
```
- Send the pc to sleep

If you add the same line in the renderer process you will finish with a white screen.

**Comment by paulcbetts** [comment]
Sounds like this is most likely a bug with node-usb, if native node modules crash in C++ land it will do this

**Comment by zcbenz** [comment]
Does it crash if you use it in Node?

**Comment by armaseg** [comment]
Indeed, is a bug with node-usb. You may set this issue as invalid. Thank you!
