### ISSUE TITLE
"Use Electron from the command line" doesn't work on OSX 10.11

### ISSUE THREAD

**Issue by shyamalschandra** [electron/electron#5771]
* Electron version: 1.2.0
* Operating system: OSX 10.11

`
iMac:~ shyamalc$ npm install --save-dev electron-prebuilt
npm WARN saveError ENOENT: no such file or directory, open '/Users/shyamalc/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/shyamalc/package.json'
npm WARN shyamalc No description
npm WARN shyamalc No repository field.
npm WARN shyamalc No README data
npm WARN shyamalc No license field.
iMac:~ shyamalc$ 
`

![screen shot 2016-05-30 at 11 57 20 am](https://cloud.githubusercontent.com/assets/9545735/15654906/afe0d7fe-265d-11e6-9dcb-481d97ca5af5.png)

What should I do?  The first snippet is the output of the npm command output.  The screenshot is of the error I get when I run: ./node_modules/.bin/electron .

**Comment by paulcbetts** [comment]
@shyamalschandra You should check out the documentation on how to get started with Electron or check out the discussion forums at https://discuss.atom.io/
