### ISSUE TITLE
app.setAsDefaultProtocolClient() is not part of the 'app' object as the documentation suggests.

### ISSUE THREAD

**Issue by ChiggerChug** [electron/electron#5773]
* Electron version: 1.1.3
* Operating system: Windows 10 64bit

I installed electron using the npm electron pre-built package. I am trying to authorize the soundcloud api and to do this, I need to set up apps internal url protocol. After looking at the documentation I found this: [app.setAsDefaultProtocolClient()](https://github.com/electron/electron/blob/master/docs/api/app.md#appsetasdefaultprotocolclientprotocol-os-x-windows)

When attempting to use this I get the following error: 
![error](https://cloud.githubusercontent.com/assets/6593130/15656467/8bb41e4e-269f-11e6-9c1b-b9b96e8aeacd.png)

I console logged the app object to see if it was available in a sub-object. but I can't seem to find it anywhere. Maybe I'm misunderstanding where this function is supposed to be available? I've tried searching for an answer to this on stackoverflow but I had no luck. Sorry if this is the wrong place to be posting this.

Here is the code I'm using:
`var app = require('app');`
`app.setAsDefaultProtocol('electron');`

And the logged 'app' object:
![app object](https://cloud.githubusercontent.com/assets/6593130/15656566/baa7b228-26a0-11e6-8525-28563ace9096.png)

**Comment by zcbenz** [comment]
Can you print `process.versions.electron` to verify you are actually using 1.1.3?

**Comment by ChiggerChug** [comment]
Ah, it seems I am using 0.35.2. I used the pre-built electron instructions directly from the main site (which had that version as part of the package.json) Sorry for the inconvenience!
