### ISSUE TITLE
Moving a frameless window with size 50x50 makes its size get larger

### ISSUE THREAD

**Issue by bansalvks** [electron/electron#5779]
* Electron version: 1.2.0
* Operating system: OSX 10.5

**Motive**
Create a chat head like _Google Hangout Desktop Application_

**Problem**
Unable to create a window of height width: 50, 50

**Reproduce**
[chatHead.zip](https://github.com/electron/electron/files/290482/chatHead.zip)

1. Please download the Electron app attached with this issue.
2. Extract using .zip
3. Open the extracted folder in terminal and run the following command `npm install`
4. Run the application using electron version 1.2.0 either by opening it in VS Code and press F5 or use the `Electron .` command

As soon as the application is launched try to drag it that will resize the window "god knows why..."

Note: I have set the transparency to false on purpose to make the window size visible.

**Comment by MarshallOfSound** [comment]
Just saying that a frameless 50x50 works on windows so if this is a problem it is an OS X specific one :+1:

**Comment by bansalvks** [comment]
@MarshallOfSound is the dummy working on you end. While draging, does it changing its size to `100*70` ??

**Comment by zcbenz** [comment]
I can confirm on OS X.

**Comment by danhp** [comment]
It seems the code provided is faulty.
Replacing everything in `index.js` with the following snippet yields the correct results.

```javascript
$(document).ready(() => {
    $('#chatIcon').css("-webkit-app-region", "drag");
});
```

**Comment by bansalvks** [comment]
@dalabarge Yes! of course, I knew this way yet I choose to do it by javascript code **because** _-webkit-app-region_ takes away the click event of the element.

I have to drag the window plus I need the click event of the chat had as well (to open the chats)

In my dummy, if you go to the index.js file then you will see the code that is used to drag the chat head.

**Comment by danhp** [comment]
In that case you should use [`BrowserWindow.setPosition(x, y)`](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetpositionx-y-animate) instead of `window.moveTo()`

It'll probably look something like:

```javascript
const win = BrowserWindow.getFocusedWindow();
win.setPosition(x, y);
```

**Comment by bansalvks** [comment]
@danhp it is not working. You can try it yourself. Go to the line 20 in index.js and do the following.
```

   //window.moveTo(xLoc, yLoc);
                const win = BrowserWindow.getFocusedWindow();
                win.setPosition(xLoc, yLoc);
```
```

**Comment by danhp** [comment]
You need to correctly require the `BrowserWindow` module...

**Comment by bansalvks** [comment]
many thanks... its working. Many many thanks.... @danhp

**Comment by mdanics** [comment]
@bansalvks can you post the working code?
