### ISSUE TITLE
Is there  other way to operation serial port except “node-serialport ” ?

### ISSUE THREAD

**Issue by Xiao-Yaran** [electron/electron#5780]
* Electron version: V1.1.0
* Operating system: Win7 32

“node-serialport ” is very nice,but it seems can not perfect support electron.

**Comment by zcbenz** [comment]
Electron doesn't have builtin APIs for serial port operations, you have to use third party modules unfortunately.

When a module is not working perfectly, you can usually try using it in a node process and pipes the result to Electron, i.e. using node-serialport in a script with `child_process.fork`.
