### ISSUE TITLE
webRequest.onBeforeRequest no longer able to cancel requests?

### ISSUE THREAD

**Issue by fasterthanlime** [electron/electron#5809]
* Electron version: 1.2.0
* Operating system: Mac OS

With electron 1.0.1, I'm able to use the following code:

```javascript
    // requests to 'itch-internal' are used to communicate between web content & the app
    let internalFilter = {
      urls: ['https://itch-internal/*']
    }

    session.webRequest.onBeforeRequest(internalFilter, (details, callback) => {
      callback({cancel: true})
    })
```

but on 1.2.0, the callback is never called. Did the filter syntax change? Or did the functionality broke with a Chrome update?

**Comment by fasterthanlime** [comment]
Actually: v1.0.1 also fails to cancels the (first) request — subsequent requests are cancelled correctly

**Comment by fasterthanlime** [comment]
Bug's harder to isolate than anticipated - apparently it might be my preload script throwing & thus preventing all navigation (looks as if all requests were cancelled). I'll report back when I have a smaller test.

**Comment by kjlaw89** [comment]
It's possible this may be related to the preload bugs that have been opened for 1.2.0. I think a fix has been made for them, just not released yet. Here's the stuff I found when I was looking into it - maybe it's similar to your situation? https://github.com/electron/electron/issues/5719#issuecomment-222146970

**Comment by fasterthanlime** [comment]
Definitely feels like a duplicate of #5719 — doing *some* things in a preload script break navigation + webRequest request cancelling.

(In my case, I was able to work around is by wrapping my code in an event listener for 'DOMContentLoaded')
