### ISSUE TITLE
LSOpenURLsWithRole() failed with error -10810

### ISSUE THREAD

**Issue by vojtatranta** [electron/electron#5810]
* Electron version: 1.1.2 (1.2.0)
* Operating system: Mac OSX

Hi guys, thanks for your work on Electron. It is a great tool and our company simply stands on it!
But now, we have a problem.
We updated our app to `electron-prebuilt@1.1.2` and after we create a build we cannot open it, it throws:
`LSOpenURLsWithRole() failed with error -10810 for the file /Users/vojtatranta/source/avocode/avocode/release/build/Avocode-darwin-x64/Avocode.app.`

Now, the strange parts: If I clone our repo into directory named `avocode` this error occurs. However If I create build somewhere else, let's say in a directory called `avocode-electron` build runs just fine.
Even if I just copy the build from `avocode/release/build/Avocode-darwin-x64/Avocode.app` somewhere eg. on the desktop the build also boots with no error.
This is really strange thing. It seems it has something to do with permission because I am not even able to delete old build from release dir, it requests sudo permission and even if I put them in the build is still there.
And last strange thing. If I run binary itself from the package contents `Avocode.app/contents/MacOS/Avocode` it also boots just fine.

None of this happened in `0.x` branch.
Any clues on that? Thanks!!

**Comment by zcbenz** [comment]
It looks like you had ran some commands as root, have you tried deleting the whole directory?

**Comment by vojtatranta** [comment]
@zcbenz nope, that is not the case for sure.
I even deleted whole directory from `~` and the same problem persists.
It really seems that the problem is somehow in the name of directory.
If I make build with older version of Electron it just works without any troubles.
I use the same build command for both versions.
I just want to know whether you have any idea what may cause this.

**Comment by zcbenz** [comment]
Hmm I have no idea from the information you provided.

**Comment by vojtatranta** [comment]
@zcbenz allright, after all it seems that this happens only on my machine. Let's close it.
Thank your for your time.

**Comment by creeperyang** [comment]
My colleague has the same error when try to open the app (`LSOpenURLsWithRole() failed with error -10810 for the file xx.app`).

I compress the app (with `tar xx.tar.gz xx.app` command) and send it to my colleague. All others can open the app successfully except one.

So we spend some time to debug it, And finally the reason is just **my colleage uncompress the file `xx.tar.gz` with unofficial tool (not `tar`)** 😂 

@vojtatranta maybe you could get some extra info.

**Comment by karyaevsm** [comment]
I want to add to @creeperyang 's answer. In our case a very similar problem with unofficial unpacking tool was that it clears the 'executable' flags, so the main file can not be run by the OS.
If you use the same unpacking tool but afterwards run chmod a+x for the executable file, it will run properly.
