### ISSUE TITLE
Notifications not working on Windows

### ISSUE THREAD

**Issue by KraXarN** [electron/electron#5811]
* Electron version: 1.2.0
* Operating system: Windows 7 x64

Creating a notification with `new Notification('test')` doesn't do anything on Windows, while it works fine on Linux. If it's a limitation in Windows, there should be some sort of fallback.

**Comment by enlight** [comment]
The docs say [on Windows 7 notifications are not supported. You can however send "balloon notifications" using the Tray API](https://github.com/electron/electron/blob/v1.2.0/docs/tutorial/desktop-environment-integration.md#windows).

**Comment by KraXarN** [comment]
Oh, sorry, missed that.
