### ISSUE TITLE
Can't reload BrowserWindow when calling remote function from preloaded script

### ISSUE THREAD

**Issue by lastmjs** [electron/electron#5816]
* Electron version: electron-prebuilt v1.2.0
* Operating system: Ubuntu 14.04 LTS

What's happening is that when I load a file into an Electron BrowserWindow from a local server, and if in a preload script I call a remote function on the main process from the renderer process, I can't reload the BrowserWindow. This issue didn't seem to happen until v1.2.0, and doesn't seem to be a problem when loading over the filesystem. There is also no problem if I include the script directly from the index.html file instead of preloading it. I'm including the simplified version of what I'm trying to accomplish:

```
// main.js
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;
const path = require('path');

let mainWindow = null;

app.on('ready', () => {
    mainWindow = new BrowserWindow({
        show: true,
        webPreferences: {
            preload: path.resolve(__dirname, 'config.js')
        }
    });

    mainWindow.getFilename = () => {
        return 'index.html';
    };

    mainWindow.loadURL(`http://localhost:5050/index.html`);

    mainWindow.webContents.openDevTools();
});
```

```
// config.js
const filename = require('electron').remote.getCurrentWindow().getFilename();
```

```
<!--index.html-->
<!DOCTYPE html>

<html>
    <head>
    </head>

    <body>
        Hello
    </body>

</html>
```

**Comment by lauer3912** [comment]
> VM174:1 Uncaught ReferenceError: **require** is not defined

**Comment by zcbenz** [comment]
I can verify this had been fixed by #5768, it will be included in the next release.

**Comment by trunks023** [comment]
@lastmjs  thanks, your answer resolved my issue..

**Comment by lastmjs** [comment]
@trunks023 You're welcome. Can you post a link to the docs you're describing? We might want to look into that and suggest a change
