### ISSUE TITLE
Which Debian/Ubuntu packages does Electron strictly require?

### ISSUE THREAD

**Issue by feross** [electron/electron#5821]
When packaging an Electron app as a `.deb` file, **which OS packages are required dependencies?**

Atom depends on [many packages](https://github.com/atom/atom/blob/57c17fb2a4e7bc6a7a97772562d8574d0d599344/resources/linux/debian/control.in#L3) but most of these shouldn't be required. There's a bit of debate going on in [this PR](https://github.com/feross/webtorrent-desktop/pull/601) to WebTorrent Desktop, and I'm not sure how to figure out which dependencies are actually required.

(Pardon the discussion question -- but I don't expect to get an authoritative answer from the discuss site.)

**Comment by zcbenz** [comment]
You can find the list of linked libraries of Electron at:
https://github.com/electron/brightray/blob/master/brightray.gyp#L4

There are a few more optional libraries, e.g.

* `libnotify` for notifications
* `libspeechd` for spell checking
