### ISSUE TITLE
Cannot access files inside asar archive

### ISSUE THREAD

**Issue by srivignes** [electron/electron#5822]
* Electron version: 1.2
* Operating system: Windows

Cannot able to access the files inside asar archive using readFileSync:

var fs = require('fs');
var SQL = require('sql.js');
var filebuffer = fs.readFileSync('asar:'+ __dirname + './app/data/sample.db');

I've also tried using 
trial 1 :    readFileSync('D:/Sample-App/app.asar/app/data/sample.db'); 

trial 2 :     readFileSync('./app/data/sample.db');

trial 3 :    process.noAsar= true;
               readFileSync('./app/data/sample.db');

None of the trials worked out. If I try without using app.asar, I was able to access the db file. So Please help me resolve this issue.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by srivignes** [comment]
Actually, I've figured it out. I am able to access the files inside asar archive now using 

    fs.readFileSync('./resources/app.asar/app/data/Softbot.db');


Thanks @zcbenz
