### ISSUE TITLE
[BUG]input the captcha in taobao.com's login page will always be wrong. but nw.js is working well

### ISSUE THREAD

**Issue by ppoo24** [electron/electron#5825]
* Electron version: v1.1.1
* Operating system: Windows 7 x64

Steps to reproduce:
1.just use the codes in `Docs -> tutorial -> Quick Start` to create a test app and modify a bit like below:
```js
const electron = require('electron');
// Module to control application life.
const {app} = electron;
// Module to create native browser window.
const {BrowserWindow} = electron;

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let win;

function createWindow() {
  // Create the browser window.
  win = new BrowserWindow({width: 500, height: 600,webPreferences:{nodeIntegration:false}}); //【must adding the "nodeIntegration" option to prevent errors in login page】

  // and load the index.html of the app.
  win.loadURL('http://myseller.taobao.com'); //【here i jump to taobao.com's backend page】

  // Open the DevTools.
  win.webContents.openDevTools();

  // Emitted when the window is closed.
  win.on('closed', () => {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    win = null;
  });
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed.
app.on('window-all-closed', () => {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (win === null) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```
the window will automatically jump into the login page: `https://login.taobao.com/member/login.jhtml?redirectURL=http%3A%2F%2Fmyseller.taobao.com%2Fseller_admin.htm`

2.then i input any username & password (just an wrong account "test1" and pass "test1") in login page:
![image](https://cloud.githubusercontent.com/assets/1631659/15703367/7184c45a-2817-11e6-997d-0aa7302f46f2.png)
then submit and it will alert that what you have input is not right, try `type & submit` more times, it will show the captcha as below:
![image](https://cloud.githubusercontent.com/assets/1631659/15703481/178908b6-2818-11e6-9c4d-561db1b4c34a.png)
he will tell us to press & move the button to the right, then we will see the actual captcha:
![image](https://cloud.githubusercontent.com/assets/1631659/15703497/37b7497c-2818-11e6-9cff-ae1b635576b6.png)
At this time, whatever you click on in the image, the result is fail.

I have tested many times in `nw.js`, these faults will not occur.
And i tried to add the "plugins" option, `enable npapi` and `disable http2` by using `app.commandLine.appendSwitch`, nothing works.
I have no idea about this problem, our site has been bleeding users with this problem. OR we are unfortunately to switch to `nw.js`?
Thanks for helping! Deeply appreciate!

**Comment by zcbenz** [comment]
Can you have a try of v1.2.1? It seems to work when I tried.

**Comment by ppoo24** [comment]
I have tried v1.2.1 x64 and ia32 versions, the same problem occured.
Is it that i'm on the internet of China?

**Comment by zcbenz** [comment]
I'm not sure, I don't think the behavior would depend on the IP address, I'm seeing the exact same login page with yours. Have you tried cleaning up all app data?

**Comment by ppoo24** [comment]
@zcbenz Hey buddy, you are truly a man with lucky, i just had a try, and it worked strangely. I mean this problem has troubled us for a long time, just because of your words, it's gone.
Now the v1.2.1 v1.1.1 and v0.35.0(we're working on) are all ok, may the Taobao have changed something, never to be known.
Thank u @zcbenz
