### ISSUE TITLE
( Electron-Intent )Android-Like intent in electron. Would be really helpful -> folks. 

### ISSUE THREAD

**Issue by thomasdola** [electron/electron#5828]
* Electron version:
* Operating system:
I wouldn't be bad if we had something like android intent way of handling new activity (new page/ component) in electron.!!! 
Because building an app with multiple pages is quite challenging to some of the us (beginners).
i d really love that .
i wish i could that the initiative yet again a am Beginner in Javascript...

**Comment by paulcbetts** [comment]
It sounds like you want something like React and React-Router, maybe have a look at that! I don't think Electron wants to be so prescriptive about how you build your apps
