### ISSUE TITLE
Dump and restore cookies

### ISSUE THREAD

**Issue by albinekb** [electron/electron#5836]
* Electron version: `1.2.1`
* Operating system: `OS X 10.11.5`

I'm trying to load cookies from a site that sets some cookies to `hostOnly: true` and then close down electron, open it up and reset all cookies to the state they were in when i saved them.

According to https://github.com/electron/electron/blob/master/docs/api/session.md#sescookiesgetfilter-callback i can get whether the cookie is `hostOnly` or not.

but according to: https://github.com/electron/electron/blob/master/docs/api/session.md#sescookiessetdetails-callback
there's no way to set this when Im setting the cookies back?

Saving and restoring cookies works in phantom.js 🎱

**Comment by kevinsawicki** [comment]
It looks like `hostOnly` isn't persisted, but inferred when you read the cookie, https://github.com/electron/electron/blob/4948bcc80666ba51b411643eb1b380f5bb390f93/atom/browser/api/atom_api_cookies.cc#L45

So I'm unsure whether `hostOnly` should be available when setting a cookie.

> Saving and restoring cookies works in phantom.js

Could you provide a snippet that shows this? I'm not seeing the `hostOnly` option listed on http://phantomjs.org/api/webpage/method/add-cookie.html

**Comment by LinusU** [comment]
Hmm, I've been trying to do this as well and for some reason I'm having trouble with dumping all cookies and then restoring them.

Basically, I'm doing `win.webContents.session.cookies.get({}, (err, cookies) => {/* Save them */})` to save all cookies to redis, and then the following code to load them back in.

```js
for (let cookie of cookies) {
  const scheme = cookie.secure ? 'https' : 'http'
  const host = cookie.domain.startsWith('.') ? cookie.domain.substr(1) : cookie.domain

  cookie.url = `${scheme}://${host}`

  win.webContents.session.cookies.set(cookie, (err) => {/* ... */})
}
```

For some reason something is not loading quite right with regards to `hostOnly` and the domain. It seems like the leading `.` is being striped from the domain and thus `hostOnly` always evaluates to `true`...

**Comment by albinekb** [comment]
What she said ^

**Comment by albinekb** [comment]
As @LinusU are describing, I'm also trying to dump cookies with `win.webContents.session.cookies.get` and save them in redis, then loading them back using `win.webContents.session.cookies.set`. 

This is not working as expected, as you can't just take the cookies you saved with `win.webContents.session.cookies.get` aren't the same as `win.webContents.session.cookies.set` wants.

More specifically I'm using https://github.com/segmentio/nightmare, but that shouldn't matter because we're writing against the electron API.

**Comment by kevinsawicki** [comment]
@LinusU @albinekb would you be able to provide a cookie value obtained from `cookies.get` that is failing to restore back via `cookies.set`? I'll use that to write a failing spec and then look into this further, thanks.

**Comment by albinekb** [comment]
@kevinsawicki sorry for the delay,
here is an example cookie that does not set correctly
```{
  name: 'TestCookie',
  value: '1234',
  domain: 'info.cern.ch',
  hostOnly: true,
  path: '/',
  secure: false,
  httpOnly: false,
  session: true
}```

Both `session` and `hostOnly` is not being set to the same value as i loaded them as.

**Comment by zcbenz** [comment]
`session` and `hostOnly` are not meaningful when setting cookie, if you don't set `expirationDate`, the cookie will have `session: true`, and if you the `domain` doesn't start with a leading `.`, `hostOnly` will be `true`.

**Comment by zcbenz** [comment]
I'm closing this since this seems to be a misunderstanding of cookies API.

**Comment by flyingcong** [comment]
This should opening? I got problem with following code:
r=require('electron').remote;	wwc=r.getCurrentWebContents();  ses=wwc.session;
ses.cookies.get({},(error,lastCks) =>{
	ses.clearStorageData({storages:['cookies','localstorage']},	function ()	{
		for(var	c	in lastCks)	{
			var k=lastCks[c];
			var x={
				url: "https://"+k.domain,
				name:k.name,
				value:k.value,
				domain:k.domain,
				path:k.path,
				secure:k.secure,
				httpOnly:k.httpOnly,
				expirationDate:k.expirationDate
			};
console.log('set cookie:', x);
			ses.cookies.set(x,	function (error) {
				ses.cookies.get({},	(error,cks) =>	{ 
console.log(cks[0].domain);
				});
			});
		}
	});
});
