### ISSUE TITLE
Disable Javascript in renderer process

### ISSUE THREAD

**Issue by dude8** [electron/electron#5838]
Is it possible to temporarily disable javascript in a renderer process, with the option to reenable it?
Like the deactivate javascript checkbox in chromeDevTools.

something like this:

```javascript
//main.js
var win = new BrowserWindow(...);
win.loadURL(...);
setTimeout(function() {
    win.deactivateJavascript();
}, 1000);
setTimeout(function() {
    win.enableJavascript();
}, 5000);
```

**Comment by zcbenz** [comment]
There is a `javascript` option in `webPreferences`.

**Comment by dude8** [comment]
Yes, but can they be set after the initialisation?
I don't want to deactivate js for the entire lifetime of that renderer process.

**Comment by zcbenz** [comment]
No, Chromium doesn't provide such ability.
