### ISSUE TITLE
Notification API without BrowserWindow

### ISSUE THREAD

**Issue by dreambottle** [electron/electron#5843]
Hi!

I have a tray app which doesn't have any BrowserWindows during its normal operation. On some events I want to show Notifications to the user, but the Notification API is only available in a browser window. And I don't want to show any windows.

So, it would be great if we could simply access to the Notification API from the main thread. Is it possible to implement this? It is especially needed on OSX, because Windows platforms at least have balloons for that purpose.

**Comment by paulcbetts** [comment]
Create a hidden window or use `electron-remote`'s `requireTaskPool` method: https://github.com/paulcbetts/electron-remote
