### ISSUE TITLE
tray displayBalloon does not work well

### ISSUE THREAD

**Issue by horious** [electron/electron#5844]
- Electron version: after 1.1.2
- Operating system: Windows

It works well up to version 1.1.1.
Since version 1.1.2 `displayBalloon` does not work well. Especially when multiple asynchronous operations are made at the same time `displayBalloon` often ignored.

``` javascript
        setInterval(function(){
            tray.displayBalloon({
                title:'hello',
                content:'world'
            });    
        },3000);
```

**Comment by zcbenz** [comment]
Did you pass icon to the balloon? And have you tried v1.2.1?

**Comment by horious** [comment]
I found new information.
If I run with electron `--debug` option. `displayBalloon` does not work well
It occurs in version 1.2.1 too.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by dataich** [comment]
Same things on 1.1.3 😢

**Comment by djpereira** [comment]
@zcbenz I have the same issue.
I am using Windows 10 and electron 1.2.5.
Here's a very simple example: https://github.com/djpereira/electron-quick-start/tree/tray-balloon-issues
The weird thing is that it works at the beginning, however as you switch to other windows back and forth and keep trying, at some point the notifications stop showing up. 
I am not sure about the exact pattern, but after switching around and resizing a few windows, the issue happens.

**Comment by djpereira** [comment]
An additional thing that I noticed is that if I set the icon either via a string or a nativeImage, it just never works.

```
  ipcMain.on('display-balloon', (event, title, content) => {
    const nativeImage = require('electron').nativeImage;
    let image = nativeImage.createFromPath('icon.ico');
    tray.displayBalloon({ title: title, content: content, icon: image });
    console.log(`displaying balloon ${title} ${content}`);
  });
```

The code executes with no errors, but nothing happens.

I don't know if it is relevant but my screen is set to 150% DPI.

**Comment by wangxiexe** [comment]
I also found this issue, it stopped work after showing 5 messages on my win10.

**Comment by zcbenz** [comment]
Hmm I don't know why but I can not reproduce this on either Windows 10 or 8.1.

**Comment by djpereira** [comment]
@zcbenz let me see if I can put together more consistent repro steps.

**Comment by sloom** [comment]
I also confirm this on 1.2.6 on Windows 7 (64bit)

**Comment by sloom** [comment]
An additional thing that I noticed is that if I set the icon via a string with *.ico(I don't know this is related or no, ico includes multiple images) nothing happens but via *.png works well.

**Comment by wangxiexe** [comment]
this bug hold my upgrade to latest eletron, any plan when it will be fixed? 

thanks!

**Comment by wangxiexe** [comment]
I tested this module and seems works well

https://github.com/hankbao/electron-notify

so for these who want to upgrade to the latest electron version,  you may use this instead of displayBalloon

**Comment by prime-ralph** [comment]
Confirmed this in Electron 1.3.5 and Windows 10 64-bit ver 1607. 
Setting the tray icon to an .ico renders the app unable to display notifications, while setting it to a .png renders the first notification unable to display until a second one is received.

I made the mistake of setting my app icon a .png file while consequent displayBalloons calls were using an .ico file. Setting them all to use .png fixed notifications for me.
`appIcon = new Tray(__dirname + '/images/icon.png');`
`appIcon.displayBalloon({
      icon: __dirname + '/images/icon.png',
      title: data.title,
      content: data.message,
    });`

If it's any help, I initialized my Tray instance during the app ready event, and displayed tray balloons when an event from my renderer process was received by ipcMain.

A thing to note is that even as the balloon icon was set, somehow notifications aren't consistently provided an icon: 
![image](https://cloud.githubusercontent.com/assets/15341353/19026558/f0d7155c-8959-11e6-8c7b-53a064c19920.png)

**Comment by Good4m** [comment]
displayBalloon getting ignored with Electron 1.4.2 when returning from a Promise:

`Utilities.cp(to, from).then(() => {
    tray.displayBalloon({
      icon: null,
      title: 'Import',
      content: 'Imported successfully.'
    });
  }).catch(error => {
    tray.displayBalloon({
      icon: null,
      title: 'Import',
      content: 'Sorry, there was an error while copying the file.'
    });
  });`

**Comment by gaving** [comment]
Just to confirm @prime-ralph's solution sorted this for me. Thanks!

**Comment by Apteryx0** [comment]
For me changing my .ico files to .png did not work, however, calling setImage immediately before displayBalloon does....

**Comment by kczx3** [comment]
I can confirm that this still does not function when a .ico file is used for the icon.  If I omit that, the balloon works and actually uses the application's icon, albeit a horrendously pixelated version of it.  Using Windows 10.

**Comment by JerryGoyal** [comment]
I'm on electron 1.8.1 and tray balloon doesnt work from async calls. tried setting the icon to png/ico but no balloon.

**Comment by insideGen** [comment]
I'm using `eletron 1.8.1`.

The following code works correctly: when a click event is detected, the balloon appears.
``` javascript
appTray.on("click", function (event, bounds) {
  appTray.displayBalloon({
    title: "Tray icon",
    content: "Click event"
  });
});
```
The following code works incorrectly: when an update event is detected, `log.info()` works but `appTray.displayBalloon()` don't.
``` javascript
autoUpdater.on("update-available", function (info) {
  log.info("update-available", info);
  appTray.displayBalloon({
    title: "Update",
    content: "Available"
  });
});
```

**Comment by redplane** [comment]
Same to me.

I added icon in `displayBalloon` as @insideGen said and it works. Without icon, tray message cannot be displayed.

**Comment by codebytere** [comment]
Given that there exist workarounds for this, and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!
