### ISSUE TITLE
中文文档

### ISSUE THREAD

**Issue by winunet** [electron/electron#5845]
* Electron version:1.2.1
* Operating system:Windows 10 X64

你好，我是Electron的使用者，请问中文文档什么时候发布。

**Comment by yeluoqiuzhi** [comment]
看不懂你说什么
[喜欢我就点我吧](https://github.com/electron/electron/tree/master/docs-translations/zh-CN)

**Comment by zcbenz** [comment]
Thanks @yeluoqiuzhi for pasting the link.
