### ISSUE TITLE
Disallow navigations to untrusted pages w/ nodeIntegration

### ISSUE THREAD

**Issue by lefb766** [electron/electron#5846]
- Electron version: any
- Operating system: any

I can see some Electron apps on GitHub that use the API badly and vulnerable to simple MITM.
The bad usage looks like this.

``` js
const win = new BrowserWindow(...);
win.loadURL('http://example.com/');
```

Because `nodeIntegration` is `true` by default and the used protocol (http) won't verify the remote host, this leads to an arbitrary code execution when a MITM attack is employed.
The severest point in this case is that attackers have a common attack vector so they can crack any Electron apps written this way with single attack implementation.

However, this looks fairly straightforward, and even experienced web developers might find this legitimate way to do if they don't have read out the security guides.
So, why not blocking such bad usage by design?

For example, when a navigation takes place, Electron could check the following and give an error if:
- The given protocol is non-encrypted (http); and
- The `nodeIntegration` is `true`

Here's open issues.
- Should navigating to `localhost` be an exception?
- Implementation approaches?
- Compatibility thoughts?

**Comment by paulcbetts** [comment]
It should at minimum be a very loud warning printed to console

**Comment by lefb766** [comment]
I missed that point. Right, `http`  can be safe if we use it through secure tunnel.
Umm, we may end up warning in console and trusting developers.
Determing trustworthness of a network is not straightforward and may even be impossible.

**Comment by zcbenz** [comment]
I'm good warning about it in console. In Electron v2 in future we can probably disallow it and provide an option to bring it back.

**Comment by codebytere** [comment]
closing due to abandonment.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (122/100 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:34931 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dx1Ru-0018ef-Ql
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:47:45 -0500
Date: Tue, 26 Sep 2017 18:46:56 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1506476816;
	bh=XhF7jsfRcOmOntcYrYuIkWEr2ib7uha6R/clKAD+C7E=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=vSM05DCesrrXpJo0SlZTWUXcY9k+nYsX/xpNznNlCJnkALc9T/9E7HV8pcrKx7Y6U
	 29AeL6LGguqoL4H2QDaQKHLOephrrTi7MOL93Dlmi8X++j2qvcnjzgdFX55uOythPl
	 F0C58orEVpcBsLssg/xemsqsi1QUJGGLWdFMyN50=

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (123/100 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:2613)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-96d6-jcjackson=joe-jackson.net@sgmail.github.com>)
	id 1dx1Rx-0018h9-ON
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:47:48 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=sLwoY0DLdTeFQHrsFf+nEIJFaKk=; b=h+WButjP02L+0E0Y
	O+WTUe1iIMQ6a63qRO1Q/AY5W+z9cijFi775Ovq7xhDv+De6bfyufBIn6U4zGnDu
	4W0WlqxGFa7FVpVH5jdIJYLnP+zehExCWVdgdKGG6Rmb3dKN4jjul9E8PafbYXOO
	pLW7/d0ju9XlXjzYRgb3D23Te8M=
Received: by filter1086p1mdw1.sendgrid.net with SMTP id filter1086p1mdw1-5743-59CB0313-18
        2017-09-27 01:46:59.378271173 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0014p1iad2.sendgrid.net (SG) with ESMTP id LdwBQUYARG6V6UVjK2zoww
	for <jcjackson@joe-jackson.net>; Wed, 27 Sep 2017 01:46:59.397 +0000 (UTC)
Date: Wed, 27 Sep 2017 01:46:59 +0000 (UTC)
