### ISSUE TITLE
Can we integrate SPARKLE in electron application? How?

### ISSUE THREAD

**Issue by bansalvks** [electron/electron#5850]
* Electron version: 1.2.0
* Operating system: OSX 10.11.5

**What is Sparkle?**

It is an application updater used by almost all applications on mac e.g VLC. It is open source and made by an APPLE insider. It is easy to use and easier to integrate with apps.

[https://sparkle-project.org/](url)

**Question**

I want to confirm, is it possible to integrate it in electron apps made for OSX? if yes then please guide us. In case if it is not then will it ever be possible. I mean if we can not integrate into Electron current version but will we be able to do it in future Electron version?

Regards
Vikas Bansal
Lv Electron!!
Keep on making it better and better.

**Comment by danhp** [comment]
Electron already integrates with an auto-updater, namely Squirrel.
You can read more about it here: https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

**Comment by bansalvks** [comment]
@danhp is there a tutorial that can help me integrating the Squirrel as it is asking to implement the following code in the application. How to do it?  

```

#import <Squirrel/Squirrel.h>

- (void)applicationDidFinishLaunching:(NSNotification *)notification {
    NSURLComponents *components = [[NSURLComponents alloc] init];

    components.scheme = @"http";
    components.host = @"mycompany.com";
    components.path = @"/myapp/latest";

    NSString *bundleVersion = NSBundle.mainBundle.sqrl_bundleVersion;
    components.query = [[NSString stringWithFormat:@"version=%@", bundleVersion] stringByAddingPercentEncodingWithAllowedCharacters:NSCharacterSet.URLQueryAllowedCharacterSet]

    self.updater = [[SQRLUpdater alloc] initWithUpdateRequest:[NSURLRequest requestWithURL:components.URL]];

    // Check for updates every 4 hours.
    [self.updater startAutomaticChecksWithInterval:60 * 60 * 4];
}](url)
```

**Comment by paulcbetts** [comment]
@bansalvks You don't have to do any of that stuff, Electron has already done it for you.

**Comment by bansalvks** [comment]
@paulcbetts Great!! it would be really kind of you if you can provide the steps and guidance for doing the same.

My concerns:

- I can manage only  an FTP server where I can put my project distribution `.app` file. I hope a VM is not needed for the update.

- There can be 3 scenarios of update
1. A few files in my project has been changed so I would certainly like to change only those files instead of pushing the whole package
2. Only Asar file(my project) is changed
3. Electron version of the new update is changed so I will need to update the Electron package as well.

How will it be managed?


Many many thanks for the reply and paying attention to this discussion.

**Comment by paulcbetts** [comment]
@bansalvks You should read the auto-updater instructions. Squirrel on Mac does require a server, so the FTP server will not be sufficient.
