### ISSUE TITLE
Icon not showing building to asar

### ISSUE THREAD

**Issue by mitchellsimoens** [electron/electron#5852]
* Electron version: 1.2.1
* Operating system: Ubuntu 14.04 x64
* Electron Packager version: 7.0.3

The icon shows fine in my `BrowserWindow` in dev and if built however if I build the app into an asar file the icon no longer shows. I'm not sure if this is an electron issue or an electron packager issue so please keep that in mind.

Using the `fs` module, in all three scenarios the icon file exists (`require('fs').existsSync(icon)`) even when built to an asar file so I'm not sure why it's not showing the icon in Ubuntu's launcher.

My simple test is:

    var electron      = require('electron'),
        BrowserWindow = electron.BrowserWindow,
        Path          = require('path'),
        fs            = require('fs'),
        icon          = Path.resolve(__dirname, 'resources', 'foo.png');

    electron.app.on('ready', function() {
        var win = new BrowserWindow({
            width  : 400,
            height : 400,
            title  : 'Test',
            icon   : icon
        });

        win.loadUrl('file://' + Path.resolve(__dirname, 'foo.html'));

        win.openDevTools();

        //for dev
        console.log(fs.existsSync(icon));  //reports true
    });

As a test, I moved `foo.png` outside of the asar file and pointed the `icon` var to it but that did not matter. `foo.png` is a PNG file at 256x256. I tried 32x32 and 64x64 but that did not help.

I'm not sure what is wrong here and some help would be appreciated.

**Comment by zcbenz** [comment]
On Linux you have to provide a [`.desktop`](https://wiki.archlinux.org/index.php/Desktop_entries) for your packaged app to make the desktop environment pick its icon.

**Comment by dudisitchy** [comment]
When I was using the electron 0.36.10, only this line on my main.js file did solve the Linux icon problem on my build:
`mainWindow = new BrowserWindow({width: 800, height: 600, icon:__dirname + '/app/img/icon.png'});`

But now with this update to 1.2.1, the icon is not working anymore.

**Comment by Autre31415** [comment]
I've done a lot of testing with this and found out icons can work under certain conditions. #6205
