### ISSUE TITLE
Dragging image on top of elect

### ISSUE THREAD

**Issue by stanfieldr** [electron/electron#5853]
* Electron version: 0.37.8
* Operating system: Ubuntu 16.04 LTS / Linux

When you drag an image over a browser window does not behave correctly. Instead of being able to drop the file on the web page, it redirects to the file you dropped.

**Comment by mnquintana** [comment]
You have to handle this yourself in an event handler for `will-navigate` on your `BrowserWindow`'s web contents and `preventDefault` – see: http://electron.atom.io/docs/api/web-contents/#event-will-navigate

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Electron message board](https://discuss.atom.io/c/electron) or the [Electron Slack channel](http://atom-slack.herokuapp.com/) is where you'll probably be able to find answers faster.

**Comment by stanfieldr** [comment]
Okay, thanks for the quick response. Thanks for the resources, I will keep this in mind moving forward :)
