### ISSUE TITLE
addDevToolsExtension does not return extension name as advertised

### ISSUE THREAD

**Issue by bengotow** [electron/electron#5854]
The docs for `BrowserWindow.addDevToolsExtension` say it returns the name of the extension. In Electron 1.2.1, this function prints the name of the extension to the console but returns `undefined`.

Test case:

```
      var reactPath = path.resolve('./static/devtools-extensions/react-devtools-0.14.11');
      var name = BrowserWindow.addDevToolsExtension(reactPath);
      console.log(name)
```

`name` is always undefined, but on the console I can see `react-developer-tools` is printed when the extension is loaded.

**Comment by felixrieseberg** [comment]
This might be a simple fix: If you're anything like me, you probably missed that extensions are persisted. In this case, `addDevToolsExtension` will return nothing, which is confusing. If you add an extension for the first time, everything is fine.

I added a `console.warn` to make this more obvious.

**Comment by bengotow** [comment]
Oh cool—persisted through restart? Didn't realize that... we'll definitely change the way we're enabling this then! Cheers—
