### ISSUE TITLE
Calling `fetch` inside a webview when using a custom http protocol crashes the content page

### ISSUE THREAD

**Issue by victorporof** [electron/electron#5855]
* Electron version: 1.2.1
* Operating system: Mac OS X

See also https://github.com/electron/electron/issues/5714

STR:

1. Start a webserver on localhost:port that serves a dummy index.html

2. Register a custom http protocol.
  ```js
  electron.protocol.registerStandardSchemes(['foobar', 'http', 'https']);
  
  app.on('ready', function() {
    electron.protocol.registerHttpProtocol('foobar', (request, callback) => {
      const redirectPath = `http://localhost:port/index.html`;
      callback({ method: request.method, referrer: request.referrer, url: redirectPath });
    }, e => { if (e) { console.log(e); } });
  });
  ```

3. Either through devtools, or via some js in our index.html, have a single line that does `fetch('http://localhost:port/index.html')` or anything else from our server.

Results: as soon as `fetch` is called, the webview becomes black, and the devtools crash if they were open. No other visible error or stdout.

If devtools were open, they show this message: "Devtools was disconnected from the page.
Once page is reloaded, DevTools will automatically reconnect."

**Comment by deepak1556** [comment]
The problem is with `electron.protocol.registerStandardSchemes(['foobar']);` 

```
[31081:0604/095501:VERBOSE1:resource_dispatcher_host_impl.cc(317)] Killed renderer for illegal origin: foobar://
[31081:0604/095501:ERROR:bad_message.cc(18)] Terminating renderer for bad IPC message, reason 95
```

seems like we didnt get registering custom schemes as standard schemes quite right.

**Comment by victorporof** [comment]
Thanks @zcbenz
