### ISSUE TITLE
app.makeSingleInstance()

### ISSUE THREAD

**Issue by wesleywesley** [electron/electron#5856]
When using this code: 

```
const shouldQuit = electron.app.makeSingleInstance(function(commandLine, workingDirectory) {
  // Someone tried to run a second instance, we should focus our window.
  if (win) {
    if (win.isMinimized()) win.restore();
    win.focus();
  }
});
```

Code is supposed to be executed by second instance only. But the callback seems to be executed for the first instance too (on first run). I know because my app is normally hidden and only shown later, but due to the win.focus() call here it already shows earlier. 

Is there a way to differentiate between which nr instance I'm running?

**Comment by robertfirespotter** [comment]
The callback code for makeSingleInstance is run on the first instance.

**Comment by MarshallOfSound** [comment]
The docs are wonderful things

https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback

> callback will be called with callback(argv, workingDirectory) when a second instance has been executed

The callback is executed on the **first** instance to run.  The variable `shouldQuit` will be `false` on the first instance and `true` on all following instances.

**Comment by stanleyxu2005** [comment]
I'm confusing, if I create two different Electron application. I want the first application to launch only one single instance, but I dont want to block the second application from being started, when the first application is running.
