### ISSUE TITLE
support for encrypted updates?

### ISSUE THREAD

**Issue by wesleywesley** [electron/electron#5857]
Can we have support for DSA signatures? Similar to sparkle for mac.

**Comment by paulcbetts** [comment]
Both Squirrel for Mac and Squirrel for Windows rely on HTTPS to authenticate that updates are legitimate. In addition Squirrel for Mac checks the code signature of your binary

**Comment by wesleywesley** [comment]
But that's not a replacement. Someone could break into the server and place other update files. However, if there were DSA signatures, he'd have to have those too (which are only on the local machine, normally). So it gives extra security.
