### ISSUE TITLE
Font smoothing has changed

### ISSUE THREAD

**Issue by dperetti** [electron/electron#5858]
* Electron version: 1.2.1
* Operating system: OS X 10.11.5

I've noticed an obviously Chrome-related change in font smoothing in recent builds. I'm jumping from an old version so I haven't figured out when it happens yet.

I have tried different `-webkit-font-smoothing` values but I cannot restore the old rendering, which I think looks better.

![electron font smoothing](https://cloud.githubusercontent.com/assets/845612/15791050/662dfa94-29d5-11e6-90ec-31b09189d8c7.png)

0.36.2 vs 1.2.1

**Comment by zcbenz** [comment]
Can you try whether the font rendering is the same with Chrome 51? If it is a Chrome change we are not able to fix this.

**Comment by joshaber** [comment]
https://github.com/atom/atom/commit/683bef5b9d133cb194b476938c77cc07fd05b972 may be relevant.

**Comment by zcbenz** [comment]
Closing until more information is provided.
