### ISSUE TITLE
Speech Synthesis: No Voices

### ISSUE THREAD

**Issue by ghost** [electron/electron#586]
Trying theses [examples](http://html5-examples.craic.com/google_chrome_text_to_speech.html) in the `0.15.7` version of atom-shell on a Mac with OS X Mavericks doesn't produce any speech but also no error is thrown.

However, there's one sign, that something went wrong. Logging `speechSynthesis` into the console, the flags `speaking` and `pending` are `true`.

The problem is, as far as I know, that there are no voices available. `speechSynthesis.getVoices()` returns an empty array.

**Comment by Iansamit** [comment]
On electron-v0.34.0-linux-x64, I'm still getting an empty array from
 `speechSynthesis.getVoices()`
Do the voices still need to be added?

**Comment by Iansamit** [comment]
I think YuriSolovyov may be correct. I just downloaded Chromium, and it seems the same - speechsynthesis is implemented, but .getvoices returns an empty array.

**Comment by nlocnila** [comment]
Just received word about this issue from a chromium developer:
> If you're using Chromium a lot of features, including this one, will be missing unless you install an API key or use Google Chrome:
https://www.chromium.org/developers/how-tos/api-keys
For speech synthesis in particular, your alternative is to install a TTS extension from the Chrome Web Store.

**Comment by glcohen** [comment]
I have Chromium API keys set up properly (can make request to APIs successfully), however still have an empty array of voices when using speechSynthesis. Any ideas?

**Comment by kurisubrooks** [comment]
@glcohen It seems to be a bug with Chromium/Chrome in general. I'm having the same problem in Chrome 54.

**Comment by kurisubrooks** [comment]
Take a look here for a workaround:
http://stackoverflow.com/questions/21513706/getting-the-list-of-voices-in-speechsynthesis-of-chrome-web-speech-api

**Comment by Iansamit** [comment]
I've never had problems using speechSynthesis with Chrome itself, but in
Chromium/Node-js, the voices do not load.

I'm sorry, I don't have the references any more, but a few months ago, I
spent a couple of days tracking down the problem and finally found that the
relevant functions have been deactivated for some reason, and that there
are no plans to reintroduce them. If you're interested, I'd suggest
searching Chromium's Bugzilla - I'm pretty sure that's where I finally
found that info.

I ended up using the http://responsivevoice.org/ service. It's free for
non-commercial use and pretty good. There can be a slight delay depending
on your Internet speed.

The only other alternatives I can think of:

   1. if your coding is way better than mine, build your own version of
   electron with the speechSynthesis functionality restored.
   2. There are a few plugin voices that work with Chromium, but they are
   all rather poor quality.

Hope this helps.

Cheers,
Ian

**Comment by guest271314** [comment]
@ghost Google API keys are not necessary. You can install `espeak`, which should provide voices to the speech dispatcher. Have not tried electron, though would also need to launch chromium with `--enable-speech-dispatcher` flag, see https://askubuntu.com/a/924473/

**Comment by guest271314** [comment]
@ghost  If you are at *nix you can install `espeak` which should populate voices array with `espeak` voices. Have not tried electron, launching chromium with `--enable-speech-dispatcher` flag set at chromium results in audio output, without installing api keys.

**Comment by guest271314** [comment]
@kynan fwiw see https://github.com/guest271314/SpeechSynthesisRecorder

**Comment by AMontagu** [comment]
Hello !

Just want to do the same than you. Any new on this side ? Don't want to use any online third party.
The only way is to build a new chromium or there is an other possibility ?

**Comment by Iansamit** [comment]
I think it's possible IF you can find a decent voice module to install.

When you use speech synthesis in Chrome, you're actually using online 3rd
party voices most of the time anyway - albeit from Google. The modules that
are downloaded depend on your location and language settings.

Google seems very protective of this technology - you can find voice
modules as Chrome plug-ins, but last time I checked, they were all LQ.

It's a while since I played with this, so you might want to check my
findings by starting Chrome offline and seeing what voices are available.

**Comment by AMontagu** [comment]
Thank you for the responses. But actually even online speechSynthesis.getVoices() return an empty array in my electron.

**Comment by guest271314** [comment]
@AMontagu Have you tried using `.onvoiceschanged` event handler to set `.voice` of `SpeechSynthesisUtterance` instance?

**Comment by AMontagu** [comment]
@guest271314 This is how I do : 

```
window.speechSynthesis.onvoiceschanged = () => {
    this.voices = speechSynthesis.getVoices();

    console.log('this.voices: ', this.voices);

    this.voices.forEach((voice, index) => {
	console.log(voice.lang);
    })

    this.voicesReady = true;
};
```

Inside a VueJs component (explain the this instance). But this.voices is an empty array.

**Comment by guest271314** [comment]
@AMontagu Is `.getVoices()` called outside of `.onvoiceschanged` handler?

**Comment by AMontagu** [comment]
no

**Comment by guest271314** [comment]
@AMontagu 

Not sure why the  pattern requires calling `.getVoices()` twice at Chromium/Chrome though that is the case - once outside of `.onvoiceschanged` and within `.onvoiceschanged` handler, see the description at Examples at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/onvoiceschanged#Examples)

```
window.speechSynthesis.onvoiceschanged = e => {
  const voices = window.speechSynthesis.getVoices();
  console.log(voices);
}
window.speechSynthesis.getVoices();
```

**Comment by brycemonster** [comment]
@guest271314 that works for me. Thanks!

**Comment by AMontagu** [comment]
@guest271314 It's not working for me.

I use electron on debian stretch (9). I installed espeak (apt-get install espeak) and launch electron with  --enable-speech-dispatcher flag ( app.commandLine.appendSwitch('enable-speech-dispatcher'); ).

The new code:
```
window.speechSynthesis.onvoiceschanged = () => {
        this.voices = window.speechSynthesis.getVoices();

	console.log('this.voices: ', this.voices);

	this.voices.forEach((voice, index) => {
		console.log(voice.lang);
	})

	this.voicesReady = true;
};

window.speechSynthesis.getVoices();
```

But the array is still empty. Can you confirm me it's working on your side with this configuration ?

**Comment by AMontagu** [comment]
I try with https://github.com/mdn/web-speech-api/tree/gh-pages/speak-easy-synthesis

The select for lang is empty so the problem is not from my code.

**Comment by guest271314** [comment]
@AMontagu Have not tried electron, cannot verify all of the code that you have tried. The new code at https://github.com/electron/electron/issues/586#issuecomment-354731932 lists the installed voices at Chromium. What does `$ espeak --voices` print at stdout at `terminal`?

**Comment by AMontagu** [comment]
```
user@computer:~$ espeak --voices
Pty Language Age/Gender VoiceName          File          Other Languages
 5  af             M  afrikaans            other/af      
 5  an             M  aragonese            europe/an     
 5  bg             -  bulgarian            europe/bg     
 5  bs             M  bosnian              europe/bs     
 5  ca             M  catalan              europe/ca     
 5  cs             M  czech                europe/cs     
 5  cy             M  welsh                europe/cy     
 5  da             M  danish               europe/da     
 5  de             M  german               de            
 5  el             M  greek                europe/el     
 5  en             M  default              default       
 2  en-gb          M  english              en            (en-uk 2)(en 2)
 5  en-sc          M  en-scottish          other/en-sc   (en 4)
 5  en-uk-north    M  english-north        other/en-n    (en-uk 3)(en 5)
 5  en-uk-rp       M  english_rp           other/en-rp   (en-uk 4)(en 5)
 5  en-uk-wmids    M  english_wmids        other/en-wm   (en-uk 9)(en 9)
 2  en-us          M  english-us           en-us         (en-r 5)(en 3)
 5  en-wi          M  en-westindies        other/en-wi   (en-uk 4)(en 10)
 5  eo             M  esperanto            other/eo      
 5  es             M  spanish              europe/es     
 5  es-la          M  spanish-latin-am     es-la         (es-mx 6)(es 6)
 5  et             -  estonian             europe/et     
 5  fa             -  persian              asia/fa       
 5  fa-pin         -  persian-pinglish     asia/fa-pin   
 5  fi             M  finnish              europe/fi     
 5  fr-be          M  french-Belgium       europe/fr-be  (fr 8)
 5  fr-fr          M  french               fr            (fr 5)
 5  ga             -  irish-gaeilge        europe/ga     
 5  grc            M  greek-ancient        other/grc     
 5  hi             M  hindi                asia/hi       
 5  hr             M  croatian             europe/hr     (hbs 5)
 5  hu             M  hungarian            europe/hu     
 5  hy             M  armenian             asia/hy       
 5  hy-west        M  armenian-west        asia/hy-west  (hy 8)
 5  id             M  indonesian           asia/id       
 5  is             M  icelandic            europe/is     
 5  it             M  italian              europe/it     
 5  jbo            -  lojban               other/jbo     
 5  ka             -  georgian             asia/ka       
 5  kn             -  kannada              asia/kn       
 5  ku             M  kurdish              asia/ku       
 5  la             M  latin                other/la      
 5  lfn            M  lingua_franca_nova   other/lfn     
 5  lt             M  lithuanian           europe/lt     
 5  lv             M  latvian              europe/lv     
 5  mk             M  macedonian           europe/mk     
 5  ml             M  malayalam            asia/ml       
 5  ms             M  malay                asia/ms       
 5  ne             M  nepali               asia/ne       
 5  nl             M  dutch                europe/nl     
 5  no             M  norwegian            europe/no     (nb 5)
 5  pa             -  punjabi              asia/pa       
 5  pl             M  polish               europe/pl     
 5  pt-br          M  brazil               pt            (pt 5)
 5  pt-pt          M  portugal             europe/pt-pt  (pt 6)
 5  ro             M  romanian             europe/ro     
 5  ru             M  russian              europe/ru     
 5  sk             M  slovak               europe/sk     
 5  sq             M  albanian             europe/sq     
 5  sr             M  serbian              europe/sr     
 5  sv             M  swedish              europe/sv     
 5  sw             M  swahili-test         other/sw      
 5  ta             M  tamil                asia/ta       
 5  tr             M  turkish              asia/tr       
 5  vi             M  vietnam              asia/vi       
 5  vi-hue         M  vietnam_hue          asia/vi-hue   
 5  vi-sgn         M  vietnam_sgn          asia/vi-sgn   
 5  zh             M  Mandarin             asia/zh       
 5  zh-yue         M  cantonese            asia/zh-yue   (yue 5)(zhy 5)
```

**Comment by guest271314** [comment]
What is output of `$ dpkg --get-selections | grep speech-dispatcher`?

**Comment by AMontagu** [comment]
```
user@computer:~$ dpkg --get-selections | grep speech-dispatcher
speech-dispatcher				install
speech-dispatcher-audio-plugins:amd64		install
speech-dispatcher-espeak-ng			install
```

**Comment by guest271314** [comment]
Did you build `speech-dispatcher-espeak-ng`? Is `speech-dispatcher-espeak-ng` or `speech-dispatcher` the default speech dispatcher? You can try installing `spd-conf` then running `$ spd-conf -d`, if Espeak tests succeed you can create a configuration file within user home directory and set espeak as default module.

**Comment by AMontagu** [comment]
Actually I just run apt-get install espeak speech-dispatcher

The test are not passing:
```
Speech Dispatcher configuration tool

Testing Speech Dispatcher using spd_say
Failed to connect to Speech Dispatcher:
Error: Can't connect to unix socket /run/user/1000/speech-dispatcher/speechd.sock: Aucun fichier ou dossier de ce type. Autospawn: Autospawn failed. Speech Dispatcher refused to start with error code, stating this as a reason: 
Can't execute the spd-say binary,
it is very likely that Speech Dispatcher is not installed.

Speech Dispatcher isn't running or we can't connect to it (see above),
do you want to proceed with other tests? (They can help to determine
what is wrong) [yes] :
>yes
Testing whether Python Speech Dispatcher library is in path and importable


Diagnostics results:
Speech Dispatcher not working through spd-say
Synthesizers that were tested and seem to work: []
Audio systems that were tested and seem to work: []
Python Speech Dispatcher module is importable
End of diagnostics results
```

This is really strange it say to me that speech dispatcher refused to start.
Did I need to do something more than just apt-get install for speech dispatcher ?

**Comment by guest271314** [comment]
What occurs when `speech-dispatcher-espeak-ng` is uninstalled?

**Comment by Hugobox** [comment]
Hi! I had the same problem and ended up using Amazon Polly

**Comment by guest271314** [comment]
@Hugobox It is not necessary to use an external service. You can run a local server and make system calls to `espeak` or `spd-say` from the server and return the result  to the client.

**Comment by AMontagu** [comment]
```
user@computer:~$ dpkg --get-selections | grep speech-dispatcher
speech-dispatcher				install
speech-dispatcher-audio-plugins:amd64		install

user@computer:~$ spd-conf -d

Speech Dispatcher configuration tool

Testing Speech Dispatcher using spd_say
Failed to connect to Speech Dispatcher:
Error: Can't connect to unix socket /run/user/1000/speech-dispatcher/speechd.sock: Aucun fichier ou dossier de ce type. Autospawn: Autospawn failed. Speech Dispatcher refused to start with error code, stating this as a reason: 
Can't execute the spd-say binary,
it is very likely that Speech Dispatcher is not installed.

Speech Dispatcher isn't running or we can't connect to it (see above),
do you want to proceed with other tests? (They can help to determine
what is wrong) [yes] :
>yes
Testing whether Python Speech Dispatcher library is in path and importable


Diagnostics results:
Speech Dispatcher not working through spd-say
Synthesizers that were tested and seem to work: []
Audio systems that were tested and seem to work: []
Python Speech Dispatcher module is importable
End of diagnostics results
```

**Comment by AMontagu** [comment]
When I run : 
```
espeak --stdout "this is a test" | aplay
```
It's working

**Comment by guest271314** [comment]
What is the output of `$ cat /run/user/1000/speech-dispatcher/log/speech-dispatcher.log`?

**Comment by guest271314** [comment]
Technically you can create a local server and pass options to the server using `POST`, call `espeak` with the options, if any, and return the response or play the audio.

**Comment by AMontagu** [comment]
```
[Mon Jan  8 14:58:16 2018 : 488284] speechd:   Speech Dispatcher Logging to file /run/user/1000/speech-dispatcher/log//speech-dispatcher.log
[Mon Jan  8 14:58:16 2018 : 488867] speechd:  Configuration has been read from "/etc/speech-dispatcher/speechd.conf"
[Mon Jan  8 14:58:16 2018 : 488977] speechd:  Initializing output module dummy with binary /usr/lib/speech-dispatcher-modules/sd_dummy and configuration /etc/speech-dispatcher/modules/dummy.conf
[Mon Jan  8 14:58:16 2018 : 488988] speechd:   Output module is logging to file /run/user/1000/speech-dispatcher/log//dummy.log
[Mon Jan  8 14:58:16 2018 : 489424] speechd:  Module dummy loaded.
[Mon Jan  8 14:58:16 2018 : 492765] speechd:  Module dummy started successfully with message: 
---------------
Everything ok so far.
---------------

[Mon Jan  8 14:58:16 2018 : 503647] speechd:  Error: Module reported error in request from speechd (code 3xx): 300-Opening sound device failed. Reason: Couldn't open pulse plugin. 
300 UNKNOWN ERROR
.
[Mon Jan  8 14:58:16 2018 : 503674] speechd: ERROR: Can't initialize audio in output module, see reason above.
```
I see the error i will try to install pulse audio. 

Yes this is what I am actually do with gtts in python but create a local server for something that can work out of the box is not optimal.

**Comment by AMontagu** [comment]
After installing pulseaudio spd-say and spd-conf-d was working.
But for testing the web I have to update a program and reboot and since the reboot all the speaker configuration are broke I can't even use aplay anymore. 

This is because I used alsa with personal configuration. So I will investigate further but I think installing pulseaudio was doing the job.

**Comment by AMontagu** [comment]
So I succes to make pulse the sound working the command `spd-say "test test test" | aplay` work but still an empty array in the web.

Is there is a config or a command to tell electron/chromium to use espeak or spd-say ?

**Comment by guest271314** [comment]
@AMontagu How is `spd-say` related to `window.speechSynthesis.getVoices()`? You can set the default module for `speech-dispatcher` either within `/etc/speech-dispatcher/speechd.conf` or by running `spd-conf` which should provide the option to create a user configuration folder within `~/.config` where you can set `DefaultModule to `espeak` or other speech synthesis module.

**Comment by guest271314** [comment]
@AMontagu How is `spd-say` related to `window.speechSynthesis.getVoices()`? 

You can set the default module for `speech-dispatcher` either within `/etc/speech-dispatcher/speechd.conf` or by running `spd-conf` which should provide the option to create a user configuration folder within `~/.config` where you can set `DefaultModule` to `espeak` or other speech synthesis module.

**Comment by nextlevelshit** [comment]
> Hi! I had the same problem and ended up using Amazon Polly

How does this comment help on trying to solve this problem? Mitigating a problem is mitigation and not a solution. We want to get native speech synthesis working and not fallback on some crappy commercial crap crap.

_I am having huge problems understanding people like you adding such non-sense -.- This is not facebook or reddit or any other anti-social media platform._

**Comment by Bagnall** [comment]
Same. Version 136.0.7103.114 (Official Build) (64-bit)
