### ISSUE TITLE
How do we get the shortcut target arguments?

### ISSUE THREAD

**Issue by Dillybob92** [electron/electron#5863]
I am sorry but I have searched extensively about this and have no idea.

I have a electron app on my desktop. And it's a shortcut, the target location points to my electron app folder:

`C:\electron\electron.exe ./MyElectronApp --customargument=xxxx`

How can I access the `--customargument` inside electron? I have tried `process.argv` but it doesn't show, is this possible?

If it's not, I am suggesting (if it is possible) -- maybe adding this as a feature to access shortcut target arguments :)

**Comment by zcbenz** [comment]
Were you using `process.argv` in the main process?

**Comment by Dillybob92** [comment]
@zcbenz Oh oops. Nope, I was using it in the browser process

I did this inside the main process

![image](https://cloud.githubusercontent.com/assets/10387670/15809445/43c7b838-2b46-11e6-8729-b63f4f101fe1.png)


.. And now I can access them!:
![image](https://cloud.githubusercontent.com/assets/10387670/15809447/4c552daa-2b46-11e6-8b43-56725f36d089.png)


Haha, my bad @zcbenz  Thanks for help!!!!
