### ISSUE TITLE
Don't download updates automatically?

### ISSUE THREAD

**Issue by wesleywesley** [electron/electron#5865]
I'd like to let the user control whether or not to download the update. User may be using a mobile connection for all we know (tethered), so downloading automatically is not something that should happen without user consent. (same for installing automatically)

**Comment by wesleywesley** [comment]
it appears both squirrel.mac and squirrel.windows have this option, so will this be integrated? 

https://github.com/Squirrel/Squirrel.Mac/issues/173
https://github.com/Squirrel/Squirrel.Windows/issues/721

**Comment by zcbenz** [comment]
This is a duplicate of #4587.
