### ISSUE TITLE
Add `paste-and-match-style` MenuItem role

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#5866]
There's already one for `Paste` and `Paste and Match Style` is just as common, so would be nice to have a `role` for it.

I'm aware I can use `win.webContents.pasteAndMatchStyle();`, but this will be especially useful when https://github.com/electron/electron/issues/2812 is fixed, as we wouldn't have to localize the label manually or manually specify the accelator for each OS. I'm trying to reduce all the boilerplate in my menu.

http://electron.atom.io/docs/api/menu-item/

-

* Electron version: 1.2.1
* Operating system: OS X 10.11.5

**Comment by miniak** [comment]
https://github.com/electron/electron/pull/5880
