### ISSUE TITLE
Remove leading and trailing Menu separators

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#5869]
OS X does this for us, but Windows and Linux does not. There's absolutely no reason to have leading and trailing separators and it's difficult to not introduce leading/trailing separators in complex context menus where multiple actors modify it. Especially when using the `visible` option to toggle items as the separator is not connected to that. I think Electron should handle this for us.

``` js
const electron = require('electron');

electron.app.on('ready', () => {
    electron.Menu.setApplicationMenu(electron.Menu.buildFromTemplate([{
        submenu: [{
            type: 'separator'
        }, {
            label: 'Foo'
        }, {
            type: 'separator'
        }]
    }]));

    (new electron.BrowserWindow())
        .loadURL(`https://github.com`);
});
```
#### OS X

<img width="89" alt="screen shot 2016-06-04 at 14 29 49" src="https://cloud.githubusercontent.com/assets/170270/15799559/fb6a624c-2a60-11e6-9600-de1338d02b1d.png">
#### Windows

<img width="84" alt="screen shot 2016-06-04 at 14 29 22" src="https://cloud.githubusercontent.com/assets/170270/15799560/02ffc1f0-2a61-11e6-98fe-ac1ea800a525.png">
## 

This includes cases like this, which is annoying to have to handle manually:

``` js
[ { label: 'Unicorn' },
  { type: 'separator' },
  { label: 'Cut', role: '', visible: false },
  { label: 'Copy', role: '', visible: false },
  { label: 'Paste', role: '', visible: false } ]
```

<img width="109" alt="screen shot 2016-06-04 at 15 22 54" src="https://cloud.githubusercontent.com/assets/170270/15799784/3d0387ae-2a68-11e6-875a-f0502e88b5ed.png">
## 
- Electron version: 1.2.1
- Operating system: OS X 10.11.5

**Comment by zcbenz** [comment]
I'm not opposed to this, but I'm not sure if there are use cases that do need leading and trailing separators.

**Comment by sindresorhus** [comment]
@zcbenz OS X removes them, so if there are any use-cases, which I find extremely unlikely, it wouldn't work cross-platform anyways.

**Comment by Scazzino** [comment]
If the visible attribute also worked on separators then it would be trivial for us to hide them when we are hiding other items in the menu, which is often why we end up with leading/trailing separators. Just a thought.

**Comment by abhigyank** [comment]
This seems to have come back in Windows and Linux, can we re-open this?

**Comment by codebykat** [comment]
As far as I can tell it's not documented that the `visible` property doesn't work on separators, would be great to get that in the docs if it is the intended behavior and not a bug. Also, you can use `visible` to remove an entire submenu from OSX, but Windows does not respect that.

**Comment by MoConWu** [comment]
This seems to have come back in Windows and Linux, can we re-open this?
Electron，v28.2.0
