### ISSUE TITLE
Throw an error if setting the tray fails

### ISSUE THREAD

**Issue by TheDoctorsLife** [electron/electron#5872]
It would be helpful for if you were using an application that closed to tray by default but in environments without a tray you'd rather just have it close. (an example where this might happen is in tiling WM's)

**Comment by zcbenz** [comment]
There is no reliable way to detect whether current desktop environment supports Tray icon as far as I know, I think the only solution is to make your app also work even when the tray icon does not show.

**Comment by TheDoctorsLife** [comment]
So electron doesn't get any feedback at all from setting the tray? I would think that something gets sent back to the application from setting it, or am I wrong?

**Comment by zcbenz** [comment]
No, we can only know whether libappindicator is supported, if not we will fallback to use GTKStatusIcon, but GTK+ doesn't reports whether the status icon is successfully created.
