### ISSUE TITLE
[FEATURE] More information on the BrowserWindow close event

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#5874]
* Electron version: 1.2.1
* Operating system: OSX

It would be great to have more information about why the window is trying to close when you have `BrowserWindow.on('close', ...`. Example use cases are....

* Quit via window close button
* Quit via dock right click & quit
* OS shutdown

**Comment by zcbenz** [comment]
The `app.quit` is called when users click "Quit", and there are a few events in `app` module handling it.

The shutdown event is tracked at #230.

**Comment by bughit** [comment]
@zcbenz

the close event does not differentiate between OS (window closing), Electron (BrowserWindow#close) and DOM (Window#close)

Is it not useful to know this, at least is some use cases?
