### ISSUE TITLE
Symbols server: inspectable_web_contents_impl.cc not found

### ISSUE THREAD

**Issue by bennyn** [electron/electron#5875]
* Electron version: 1.2.1
* Operating system: Windows 10 Home

Today my Electron app crashed I tried to load the symbols from the symbols server but Visual Studio reported: "inspectable_web_contents_impl.cc not found". What can I do now to debug the issue?

**Screenshot**

![screenshot](https://cloud.githubusercontent.com/assets/469989/15805619/53069a1e-2b30-11e6-9cf8-29eba3046c2c.png)

**Call Stack**

![call stack](https://cloud.githubusercontent.com/assets/469989/15805625/87176fcc-2b30-11e6-90e1-e05ac4cf52cb.PNG)

**Comment by enlight** [comment]
That file is from (Brightray)[https://github.com/electron/brightray/blob/master/browser/inspectable_web_contents.cc]. You'll need to clone the Electron source from the (v1.2.1 tag)[https://github.com/electron/electron/tree/v1.2.1]. Then when VS prompts you to locate the source file browse to `vendor/brightray/browser` and press the `Open` button.

**Comment by zcbenz** [comment]
Thanks @enlight for answering it! I'm closing this issue now.
