### ISSUE TITLE
where can i get electron.exe.pdb or node.dll.pdb symbol file that has release electron version?

### ISSUE THREAD

**Issue by chensy123** [electron/electron#5876]
* Electron version:
  v0.37.8
* Operating system:
window 8

where can i get electron.exe.pdb or node.dll.pdb symbol file that has release electron version?

**Comment by zcbenz** [comment]
We have symbols server for them:
http://electron.atom.io/docs/development/setting-up-symbol-server/

But note that the symbols server is not working for < 1.0.0.
