### ISSUE TITLE
DownloadItem.getSavePath

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#5877]
* Electron version: 1.2.1
* Operating system: OSX

When a user downloads an item I've been trying to get the location that they've saved it to. It's not documented, but I noticed on the downloadItem there is a `getSavePath` function. This always returns an empty string when I call it.

Was wondering if it's not documented for a reason / not working. Or is there a better way to get the location that a user selects?

**Comment by danhp** [comment]
Right now, `getSavePath` doesn't do anything useful as it just returns the path that the user passed in `setSavePath(path)`. This is probably the reason why it's undocumented.
It currently returns `null` if you bypass the setter with the system's dialog.

**Comment by Thomas101** [comment]
I had a feeling that's what it did :-(

**Comment by EternallLight** [comment]
Just faced the same issue while developing on Linux. I tried to implement "Open downloaded file" functionality, and it would be great if getSavePath() returned the full path chosen by a user in the saving dialog window. Hope this is gonna be implemented.
