### ISSUE TITLE
Flash of white content, even after did-finish-load event

### ISSUE THREAD

**Issue by wesleywesley** [electron/electron#5878]
I'm instantiating my BrowserWindow with show:false parameter and wait for did-finish-load to show the window. However, on windows, I still get a split second of white page before content is shown. Why is that? Is did-finish-load same as document.ready or same as window.onload (should be the second really). 

I even added a small timeout of 25ms but that wasn't enough either.

**Comment by zcbenz** [comment]
You can solve this by setting a background color for your window with `backgroundColor` option, for example `backgroundColor: '0FFF'`.

**Comment by wesleywesley** [comment]
How is that solved? It's not really about the background color, it's about the fact that the content is missing (instead, we only see a white, empty space), until some fraction of a second later. Is there an event that shows the real loading completion of a page instead of did-finish-load?

**Comment by zcbenz** [comment]
Chromium renders the page by first drawing the background color and then the actual page, and the rendering only starts when the page shows for the first time. So no matter how long you wait you will still see the white flash, the only solution is to set a background color for your app, which can effectively remove the flash.
