### ISSUE TITLE
Export/import webview navigation history

### ISSUE THREAD

**Issue by pfraze** [electron/electron#5885]
* Electron version: 1.2.0
 * Operating system: OSX 10.11.4

I'd like to be able to save a webview's nav history, either to memory or disk, and import that nav history into a new webview. I tried using a session partition (with the persist prefix, and without), but that didn't work. Is this possible?

**Comment by zcbenz** [comment]
Electron doesn't keep navigation history, you have to hook the DOM to provide your own solution.

**Comment by pfraze** [comment]
I'll need an API to set the history, won't I?
