### ISSUE TITLE
Calling minimize() for hidden window does not put it into minimized state

### ISSUE THREAD

**Issue by fab1an** [electron/electron#5887]
Is it possible to show a browserwindow created with `show: false` initially minimised in OSX?

If I call `show()` first, then `minimize()` it's displayed normale, then mimized. If I call `minimize()` first and `show()` after, it's just displayed normally, if I don't call `show()` it's not displayed at all.
- Electron version: 1.2.1
- Operating system: OSX 10.11.5

**Comment by zcbenz** [comment]
I'm afraid it is not possible on OS X, the window doesn't really have a minimized state, it is either placed in screen list (normal state), or removed from screen list and placed in Dock (minimized state), there doesn't seem to be a way to directly put a window in Dock without putting it into screen list.

**Comment by fab1an** [comment]
There must be a way, because other applications can do it. They start up and the minimized window appears in the dock without being opened first.

I would like to reopen this bug.

**Comment by zcbenz** [comment]
@fab1an Can you show which application can do that? If it is an open source project then we can reference how it is implemented.

**Comment by fab1an** [comment]
Textmate 2 can do it, it's open-source: https://github.com/textmate/textmate.

Keep in mind, that most application are designed in such a way that if there's no active window, they will restore at least one minimized window. So you actually have to open two window, minimize one, then quit the application to see it in effect.

Thank you for looking into this.

**Comment by codebytere** [comment]
closing due to abandonment.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (116/100 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:58498 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dx1Re-0018Vn-9J
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:47:29 -0500
Date: Tue, 26 Sep 2017 18:46:39 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1506476799;
	bh=PupR9QBTHlmD3S65mzxyyt7cwnbdEx5cN8g902o4TK8=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=bLB4JeoKw2UwI0HBCLBT/Cl6My0FbuZIUXh2rr2m6FvoawRo2PFYchCz4mYJLGCal
	 R/oq1VIra4lVbNj3OG0kgdKjug4F0G3p3vzx0q1PkxntI4Dk4s6v+BjlfRJZ2N0PYZ
	 IgE6AwMw7/COVC09CFGTG+n2hi9itWTUNm6FAk6A=

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (120/100 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:41809)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-96d6-jcjackson=joe-jackson.net@sgmail.github.com>)
	id 1dx1Ro-0018aI-FQ
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:47:39 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=P1m2fraF77BhoO6LD9Rrgt80u0I=; b=GuMZ18m05eiq3z0p
	iOtfFxHeNbUdRIG7ULy7lus0UA+WG0gyMtzrHc6i8Pf6cIuu98elM6k0I3Otw3+d
	PdMJXaLXgztFVOxo0q9MpD4WaXaXuxz+vlXbV4IoyGoTkYiMOpo7vPgbftvA3uh0
	JpRg8rgTjfloFAWO+uWtRx/UXFA=
Received: by filter0452p1mdw1.sendgrid.net with SMTP id filter0452p1mdw1-14336-59CB0309-11
        2017-09-27 01:46:49.37403314 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0023p1iad2.sendgrid.net (SG) with ESMTP id J3wTACoLSiOJ02NxU8cVmw
	for <jcjackson@joe-jackson.net>; Wed, 27 Sep 2017 01:46:49.334 +0000 (UTC)
Date: Wed, 27 Sep 2017 01:46:49 +0000 (UTC)
