### ISSUE TITLE
app.quit() dont work if app have a window with window.closable = false

### ISSUE THREAD

**Issue by karacas** [electron/electron#5891]
* Electron version: 1.2.1
* Operating system: win 10 x64

``
function createWindow () {
  mainWindow = new BrowserWindow({width: 800, height: 600, closable:false})
  mainWindow.loadURL("file://${__dirname}/index.html" )
  mainWindow.on('closed', function () {
    mainWindow = null
  })
  app.quit() // < Not Work
}

function createWindow () {
  mainWindow = new BrowserWindow({width: 800, height: 600, closable:true})
  mainWindow.loadURL("file://${__dirname}/index.html" )
  mainWindow.on('closed', function () {
    mainWindow = null
  })
  app.quit() // < Works Ok
}

``

**Comment by danhp** [comment]
This is by design, `app.quit()` will request that all windows be closed before exiting the app. You should call [`app.exit(exitCode)`](https://github.com/electron/electron/blob/master/docs/api/app.md#appexitexitcode) when using unclosable windows.

**Comment by karacas** [comment]
Tnxs
