### ISSUE TITLE
Windows Printing: Input elements rendered in margin.

### ISSUE THREAD

**Issue by Billiam** [electron/electron#5892]
- Electron version: Tested with 1.1.3 and 1.2.1
- Operating system: Tested with Win 8 and 10
- Printing: Tested with PDFCreator (under win8), Print to PDF (under win 10), actual HP printer/driver (under win 10).

Issue did not occur in linux build. Mac not tested.

If a page is printed (via `webContents.print`) which contains input elements (tested with select, text, checkbox and radio), those elements will also be rendered, tiny, in the page margins (see screenshot):

![PDF Screenshot](https://cloud.githubusercontent.com/assets/242008/15830904/535b8514-2be0-11e6-8860-95ea768d41aa.png)

Screenshot is from my own application, but also occurs with a printing example here (after adding input elements to the page).
https://github.com/hokein/electron-sample-apps/tree/master/printing

I have not seen this occur with the `webContents.printToPDF()`

**Comment by codebytere** [comment]
closing due to abandonment.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (118/100 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:34391 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dx1Rk-0018Y7-2y
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:47:35 -0500
Date: Tue, 26 Sep 2017 18:46:44 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1506476805;
	bh=Y89pYNmzTPkZAoMrGNGJpvcsj27BxzWMhVVP0YuluJE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LnZHztuDzp/aPZxicP2VJ2UCD8hQORzkYEaMbKzohpbHlPmnb10Gp2igYsFn33VXq
	 4skN6UHPP8IdARvct9lodPw4gvGEYhLubjTGPNG/eU9uTNPrgY6p1CBl8sdAUE1qoI
	 2leDrYN4QacVYwVBAyDG1gOnNEP4f6x8Fk4pEm8M=

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (119/100 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:51065)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-96d6-jcjackson=joe-jackson.net@sgmail.github.com>)
	id 1dx1Rm-0018Zm-OY
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:47:37 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=dKCgL8tvMZqDD2hdT9nefdUdkRI=; b=YcLj78JRCtB5e5mk
	tB4S+/LgTJXjqd+lJQSi9QBKLMajVoTv7vQxxr9QbAoGodzuJF/ExLsDpT1NztAu
	IDDjlBrgSJIIEUGul8ChzC6+ii9UlgQODWL7f4TUUIrDMYp1DpH5lxrwgzkH8xlh
	2wY20ojb/0axgo5Wb27j7Hp2ErU=
Received: by filter0422p1mdw1.sendgrid.net with SMTP id filter0422p1mdw1-18926-59CB0308-1
        2017-09-27 01:46:48.033390295 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id 72MccU4GRCqtJhF2-FB8Tg
	for <jcjackson@joe-jackson.net>; Wed, 27 Sep 2017 01:46:47.988 +0000 (UTC)
Date: Wed, 27 Sep 2017 01:46:48 +0000 (UTC)
