### ISSUE TITLE
Electron <webview> elements do not retain input focus between BrowserWindow blur/focus 

### ISSUE THREAD

**Issue by bnookala** [electron/electron#5900]
- Electron version: 1.1.1
- Operating system: 10.11.3

**Background**:
This is a bug @felixrieseberg and I noticed while attempting to [fix an issue](https://github.com/TryGhost/Ghost-Desktop/issues/116) on Ghost Desktop. 

**Working case:** 
When a `BrowserWindow` instance loses and regains focus (a `blur`, followed by a `focus`), it automatically refocuses, and gives input focus to any input-like elements within the application. This is expected.

**Not working case:**
When a `BrowserWindow` instance contains a `<webview>`, which itself contains an input-like element, a `blur`, followed by a  `focus`, does not retain input focus on the input elements. This is not expected.

**Video/Code**:
- [Here's a video in gif form of what I'm trying to demonstrate is an issue.](https://gist.githubusercontent.com/bnookala/818785874346f7b6775df4fcc1d4cd5c/raw/9264bafb2258b7300606d652e5f0bcda25d9114d/electron-focus.gif)
- [And here's the code used in the video above.](https://gist.github.com/bnookala/818785874346f7b6775df4fcc1d4cd5c)

**Comment by paulcbetts** [comment]
Yeah, we fix this up in the Slack app by-hand, it's a bummer

**Comment by bnookala** [comment]
@paulcbetts can you share how Slack gets around this? I've tried a few things, but none appear to work definitively.

**Comment by paulcbetts** [comment]
Basically it's just:

```js
window.addEventListener('focus', () => theWebViewElement.focus())
```

**Comment by bnookala** [comment]
@paulcbetts thank you! I'd somehow ended up taking the long route around getting the webview to focus properly.

**Comment by astoilkov** [comment]
Interestingly we can replicate the same issue with a simple `<textarea>` element under Windows 10 x64 but it happens just 30% of the time. I hope this will also resolve our issue.

**Comment by akashnimare** [comment]
Any progress on this? Following soultion does not work with textarea. 
``` javascript
window.addEventListener('focus', () => theWebViewElement.focus())
```
You need to click twice to get the focus on textarea.

**Comment by sofianguy** [comment]
Thanks for contributing!

This is an old version that we are no longer releasing bug fixes for. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.

**Comment by pushkin-** [comment]
@sofianguy This is still an issue in Electron 2.0. Can this be reopened, or is there another issue tracking this?

**Comment by pashvin** [comment]
I have similar issue but I am using BrowserView instead of web view and I think BrowserView does not have focus function so How I can set focus on BrowserView when main BrowserWindow get the focus?

**Comment by pashvin** [comment]
Found the focus function which I can use with BrowserWindow.
webView.webContents.focus();

**Comment by pushkin-** [comment]
still an issue in Electron 4.0.4. Also broken when using BrowserViews instead of webviews.

**Comment by pushkin-** [comment]
@sofianguy Hi, this is still a bug in Electron 8.0.1. Thanks

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by pushkin-** [comment]
Hm, I actually can't repro with webview anymore in Electron 12.0.1:

![focusretain](https://user-images.githubusercontent.com/6374473/110991918-d92ed900-833a-11eb-8678-96878f4bb9d7.gif)

I can however with a BrowserView. Will create a separate issue for that and update this comment with it.
