### ISSUE TITLE
Electron + Flux + React-Router-Component Structure Desktop App - Routing not working properly

### ISSUE THREAD

**Issue by ctsbala4587** [electron/electron#5902]
* Electron version: 0.37.8
* Operating system: Windows 7; 32 Bit
* React Version: 0.13.3
* Flux Version: 2.1.1
* React-router-component Version: 0.25.4

Here we are using React-router-component for routing functionality. This is routing functionality code. 

```javascript
<Locations hash>
	<Location  path="/"	handler={
		<div>			
		<Login/>
		</div>
	}
	/>	
	<Location path="/dashboard" handler=
		{
			<div>						
			<Navbar/>
			<Dashboard/>
			</div>
		} />
		
</Locations>
```

After successful login user should navigate to dashboard page. But navigation not working immediately.

Once reload or refresh the page manually, then its navigate to dashboard page.

For navigation we using,
```javascript
this.navigate('#/dashboard');
```
Any help would be greatly appreciated.

**Comment by zcbenz** [comment]
I suggest seeking help from [the community](https://github.com/electron/electron#community), the issues list is for bug reports and feature requests.
