### ISSUE TITLE
Could not call remote function 'quit'.

### ISSUE THREAD

**Issue by vojtatranta** [electron/electron#5908]
* Electron version: 0.37.6
* Operating system:

This error:
https://github.com/avocode/avocode/issues/902

Stack:
```
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: avocode.min.js:23:3830.
Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: avocode.min.js:23:3830.
    at callFunction (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:237:11)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:318:12)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:176:13)
    at remoteMemberFunction (/Applications/Avocode.app/Contents/Resources/electron.asar/renderer/api/remote.js:110:18)
    at t.quit (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:6011)
    at React.createClass._handleShortcut (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:7:11660)
    at module.exports.React.createClass._handleShortcuts (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/component/shortcuts.js:138:25)
    at _fireCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-shortcuts/node_modules/mousetrap/mousetrap.js:610:17)
    at Mouset
```
Code that fires it:
``` coffee
handleShortcut: (type) ->
    switch type
      when 'APP:QUIT'
        require('electron').remote.require('app').quit()

```

That is really odd. Why would be an app instance released? There still must be a reference. I have no information about reloading a window or anything like this.
Any clues guys?
Thank you!!

**Comment by MarshallOfSound** [comment]
That syntax is really strange.  I'm not surprised something went wrong somewhere.

Try this instead

```js
handleShortcut: (type) ->
    switch type
      when 'APP:QUIT'
        require('electron').remote.app.quit()
```

**Comment by zcbenz** [comment]
You should not create application menu in renderer process if your app can create multiple windows, suppose you first created `win1` and then `win2`, the click handlers of application menu will be ran in `win2`, once you closed `win2` the click handlers will also be gone, but `win1` is still there and none of the menu items will work.

**Comment by vojtatranta** [comment]
@MarshallOfSound this is not the real code it is a bit more complicated. I pasted simplified.

@zcbenz I did not expect that this has anything to do with Menu. Since I just call `app.quit()`.
Why do you think that this has anything to do with menus?

**Comment by zcbenz** [comment]
@vojtatranta Hmm it looks exactly the same with a common error of setting menu in renderer process, can you provide a minimal reproducible example?

**Comment by vojtatranta** [comment]
@zcbenz I fear I can't. This bug came to us over sentry. I just wanted to know whether you have any suggestion.
We do render Menu in renderer process, that is true. Honestly, it would be very difficult for us to move creating of Menu into the main process.
We add disposing of Menu when window refreshes, but I don't think it will help anyhow.

**Comment by zcbenz** [comment]
@vojtatranta I just noticed you are using 0.37.6, then you probably encountered a bug of `remote` which had been fixed in 0.37.7. I suggest updating to at least 0.37.8, which includes a few important fixes and is smooth to update.

**Comment by vojtatranta** [comment]
@zcbenz great, thanks for advice

**Comment by vojtatranta** [comment]
I have to reopen this issue, because we received similar issues: 
```
Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Cannot read property 'getDisplayMatching' of null Error: Could not call remote function 'quit'. Check that the function signature is correct. Underlying error: Cannot read property 'getDisplayMatching' of null at callFunction (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:235:11) at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/rpc-server.js:342:5) at emitMany (events.js:127:13) at EventEmitter.emit (events.js:201:7) at WebContents.<anonymous> (/Applications/Avocode.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13) at emitTwo (events.js:106:13) at WebContents.emit (events.js:191:7)javascript
```

which happens here:
```
 getPath(pathName) {
    return this._electronApp.getPath(pathName)
  }
  quit() {
    this._electronApp.quit()
  }
}
```

I should mention that we do some stuff when is quiting the app so in the.

So the user hits quit, we hide the main window, and then the app loads this callback:
```
window.addEventListener('beforeunload' () => {
// doing stuff here
})
```
May this be the cause of error above?
