### ISSUE TITLE
Is there any way to have sticky notifications?

### ISSUE THREAD

**Issue by lipis** [electron/electron#5909]
At the moment the notifications are disappearing after a certain time out. Is there any way to have to keep certain notifications until user is going to interact with them?

**Comment by MarshallOfSound** [comment]
According to the API spec https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification a `sticky` option is in the spec.  But is not currently supported by any browser (including Chromium).

You probably need to wait until Chromium implements sticky notifications upstream

**Comment by zcbenz** [comment]
I'm merging this to #3359, which would enable us to use advanced notification features without waiting for browser engine.

**Comment by lipis** [comment]
@zcbenz What about the [`requireInteraction`](https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification):

> requireInteraction:  Indicates that on devices with sufficiently large screens, a notification should remain active until the user clicks or dismisses it. If this value is absent or false, the desktop version of Chrome will auto-minimize notifications after approximately eight seconds. The default value is false.

Not standard but it's supported in 47+
