### ISSUE TITLE
Electron crash when using spell checker

### ISSUE THREAD

**Issue by KynoYang** [electron/electron#5912]
* Electron version: 1.2.1
* Operating system: OS X  EI Captain 10.11.4
* SpellChecker version: 3.2.3 or 3.3.1

After I upgrade electron to 1.2.1 from 0.37.4, I found it crash all the time when I was typing. I think it's because of using spellchecker. 

I create a clean demo about this. Please check it out [here](https://github.com/KynoYang/ElectronSpellCheckerDemo)

**Comment by zcbenz** [comment]
Can you paste the crash report?

**Comment by KynoYang** [comment]
@zcbenz  Thank you so much for replying.

I can see nothing at all. It makes the electron window become white screen, and there is no output in the console. You can try the demo. It's quite easy to reproduce.

![image](https://cloud.githubusercontent.com/assets/2586026/15880915/4a6ae9ec-2d64-11e6-90ca-c1b70977c868.png)

**Comment by paulcbetts** [comment]
What happens if you load the spellchecker outside of the callout

**Comment by KynoYang** [comment]
@paulcbetts Thank you for you tip.

I try to call spellchecker outside the SpellCheckProvider. 
```
console.log(require('spellchecker').isMisspelled("text"));
```
And I found an exception in the console caused by requiring spellchecker.
```
ELECTRON_ASAR.js:158 Uncaught Error: Module version mismatch. Expected 48, got 47.
module.(anonymous function)	@	ELECTRON_ASAR.js:158
Module._extensions..node	@	module.js:568
module.(anonymous function)	@	ELECTRON_ASAR.js:158
Module.load	@	module.js:456
tryModuleLoad	@	module.js:415
Module._load	@	module.js:407
Module.require	@	module.js:466
require	@	internal/module.js:20
```

**Comment by paulcbetts** [comment]
Yep, you need to rebuild native modules

**Comment by KynoYang** [comment]
👍 @paulcbetts You're right! Thanks.
