### ISSUE TITLE
`getPosition()` return inconsistent values when compared to `screen.getAllDisplays()`

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#5914]
* Electron version: `1.1.0`
* Operating system: OS X

`window.getPosition()` appears to return impossible values in some screen configurations on OS X.  With the screen configuration below.

![screencapture-at-tue-jun-7-13_08_22-edt-2016](https://cloud.githubusercontent.com/assets/6634592/15867486/ec1f06da-2d26-11e6-85e8-afa05eb6a344.png)

The following outputs are noted.

```js
// Calling window.getPosition()
// When the window is in the top left of the left screen
[-2321, 23]

// When the window is in the top right of the left screen
[-1196, 23]

// When the window is in the top left of the right screen
[3, 23]

// When the window is in the top right of the right screen
[642,23]
```

Below is the output for `screen.getAllDisplays()`

```js
[
  {
    "id":69677376,
    "bounds":{
      "x":0,
      "y":0,
      "width":1280,
      "height":800
    },
    "workArea":{
      "x":0,
      "y":23,
      "width":1280,
      "height":709
    },
    "size":{
      "width":1280,
      "height":800
    },
    "workAreaSize":{
      "width":1280,
      "height":709
    },
    "scaleFactor":1,
    "rotation":0,
    "touchSupport":"unknown"
  },
  {
    "id":188906641,
    "bounds":{
      "x":-1920,
      "y":0,
      "width":1920,
      "height":1080
    },
    "workArea":{
      "x":-1920,
      "y":23,
      "width":1920,
      "height":1057
    },
    "size":{
      "width":1920,
      "height":1080
    },
    "workAreaSize":{
      "width":1920,
      "height":1057
    },
    "scaleFactor":1,
    "rotation":0,
    "touchSupport":"unknown"
  }
]
```

As you can see, based on the `workArea` values for the two screen the first two position values are impossible / incorrect for where they actually are on the screen.  The x values appear to be offset by the width of the screen.

This is causing issues with restoring a windows location as we are restoring a window to a location that doesn't actually exist.

**Comment by danhp** [comment]
This seems to be behaving correctly as the origin for the coordinate system is at the lower left of the main screen. In this case:
![untitled](https://cloud.githubusercontent.com/assets/3745612/15875464/04f82ffc-2cd6-11e6-8a4e-3f0c01078f0e.png)

**Comment by OlsonDev** [comment]
@danhp If the origin was there, I don't see how the coordinates could be `[-2321, 23]` -- his monitor is only 1920px wide. From what I can tell, it should be `[-1920, 23]`.

**Comment by danhp** [comment]
@OlsonDev That would be if the top corners were exactly aligned.

**Comment by MarshallOfSound** [comment]
@danhp Let's assume that the origin is where you say it is (bottom left of the main screen).

Given the screen dimensions the following values would be expected values

```js
// Top left of left monitor
[-1920, 709]

// Top right of left monitor
[0, 709]
```

However, as you can see, those values are nothing like what we actually get.

> That would be if the edges were exactly aligned.

I'm not sure what you mean by this, it doesn't matter whether the edges are aligned or not.  You can see the `getAllScreens()` returns a workarea for the left screen of `x = -1920` which means it's x range is `-1920 --> 0`.

**Comment by danhp** [comment]
You're allowed to stick the window further than the edge of the screen.

**Comment by MarshallOfSound** [comment]
> You're allowed to stick the window further than the edge of the screen.

That might explain the interesting `getPosition` values but it doesn't explain why the `getAllScreens()` output doesn't match those values.

> Why would top right be 0? it should be 0 - window.width which is in the ball park of what you have.

If the origin is `[0, 0]` the top right of the left monitor is **directly above** the origin.  Therefore `dX` is 0 and `dY` is the height of the right monitor.

Hence
`[0, 709]`

**Comment by danhp** [comment]
Made a mistake earlier, the origin is actually at the top left and the y axis is inverted. But it doesn't change the reasoning as we're dealing in `x`.
`getAllScreens()` is outputting the correct values as those are the dimensions of the visible sections.

> If the origin is [0, 0] the top right of the left monitor is directly above the origin. Therefore dX is 0 and dY is the height of the right monitor.

The window's origin is also on the left, therefore to get an `x = 0` it would need to be on the right screen given the current configuration.

Went through the code and it is improbable that the coordinate system is not implemented correctly as we're simply making a native call.
https://github.com/electron/electron/blob/fe4b957587104b0ce138cdf9315933f96fd8f570/atom/browser/native_window_mac.mm#L683

**Comment by MarshallOfSound** [comment]
> The window's origin is also on the left, therefore to get an x = 0 it would need to be on the right screen given the current configuration.

I thought we were working with approximations. 😄   If the origin is on the **left** of the **right** monitor, 
then if the window is on the far **right** of the **left** monitor the `dX` should be more or less 0.  (It might be `-1`).  On windows the change between monitors is indeed 1.

The main point being it shouldn't just jump `1196`.

## The main point for this issue

Given a multi monitor set up, when we try and restore the window to a previously saved location, that location might not be there anymore.  With the current electron API this is not blocked, the window is simply moved off screen and the user can't do anything to bring it back.  To solve this we introduced code to check if the position was valid before hand.  However with the method outputs on OS X this is impossible.

Let me present you with this sample code to determine if a given x and y coordinate pair is inside a screen

```js
position = getAPositionSomehow();

let inBounds = false;
if (position) {
  screen.getAllDisplays().forEach((display) => {
    if (position[0] >= display.workArea.x &&
        position[0] <= display.workArea.x + display.workArea.width &&
        position[1] >= display.workArea.y &&
        position[1] <= display.workArea.y + display.workArea.height) {
      inBounds = true;
    }
  });
}
```

This code works correctly on all platforms EXCEPT OS X due to the irregularities in `getAllDisplays()` and the possible outputs of `getPosition()`.  Surely you can see that this inconsistency causes issues.

**Comment by danhp** [comment]
Instead of doing bound checks with just the origin point you can do it by getting the screen which holds the most of the window (greatest area).

**Comment by MarshallOfSound** [comment]
@danhp The main issue of using https://github.com/electron/electron/blob/master/docs/api/screen.md#screengetdisplaymatchingrect is this.

Given the overlap that looks like this 

![overlap](https://cloud.githubusercontent.com/assets/6634592/15893181/7b733366-2dc1-11e6-888f-172e655fb03b.png)

It would return the blue screen, when that window is in fact unusable as the only way to move the window is the top bar which is off screen?

**Comment by danhp** [comment]
Then set legal values to the window, you have access to those.

**Comment by MarshallOfSound** [comment]
That is the entire point of this issue 😕 

Given the scenario where you have two monitors, positioned vertically let's say.  When you close the electron application I store the the position the window was at just before we closed.  

Then you unplug the top display, and reopen the application.  Although the last saved position was valid when it was saved, it is no longer valid and somehow we need to test for this.  The expected way to test for this is to compare the origin coordinate of the window with the known workAreas of the screens.

![config3](https://cloud.githubusercontent.com/assets/6634592/15893554/cee305b0-2dc3-11e6-87e2-65858b981ef3.png)

Image above^^

The problem with this methodology is that on OS X the work areas do not match up with the return values of `getPosition()`.

**Comment by zcbenz** [comment]
@MarshallOfSound The APIs are just returning the values given by OS X, I don't think we can do anything on Electron's side to improve the situation.

**Comment by MarshallOfSound** [comment]
@zcbenz Is there a native API that can be provided in the `screen` module then to do this test at a native level.

Something like  `display.containsPoint(point)`

Usage would be something like
```js
import { screen } from 'electron';

const point = [-100, 27];

let validPoint = false;
screen.getAllDisplays().forEach((display) => {
    validPoint = validPoint || display.containsPoint(point);
});
```

On a side note aswell
> The APIs are just returning the values given by OS X

Does that mean OS X is bugged 😖

**Comment by MarshallOfSound** [comment]
@zcbenz Implementing this exact Chromium API but returning `null` instead of returning the Primary Screen by default would be perfect

**Mac**
https://chromium.googlesource.com/chromium/src.git/+/44.0.2403.88/ui/gfx/screen_mac.mm#141

**Win**
https://chromium.googlesource.com/chromium/src.git/+/44.0.2403.88/ui/gfx/screen_win.cc#138

**Comment by andymartinwork** [comment]
@MarshallOfSound 

If you guys in Electron want to do something about this, there is an API in OSX available that displays the visible frame from the current screen. For example:


```
        // Retrieve information for the display that contains the window.
        NSScreen* screen = [window screen];
        if (screen == nil)
            screen = [NSScreen mainScreen];
        NSRect frame = [screen frame];
        NSRect visibleFrame = [screen visibleFrame];
```

Then you can calculate how to modify the frame of the window appropriately.

Unfortunately, there is no way to get this in Electron right now, causing me a lot of trouble at the moment...
