### ISSUE TITLE
Blank line is written to stdout on program start

### ISSUE THREAD

**Issue by bontibon** [electron/electron#5917]
* Electron version: 1.2.1
* Operating system: Windows 10 x64

I am trying to allow for the output of my program (XML) to be piped into other programs. However, electron seems to be printing a blank line before my program output:

```
% ./my-app

<?xml version="1.0"?>
...
```

Whitespace before the XML declaration is forbidden, therefore, this is causing issues.

You can reproduce this by simply running electron and looking at the output:
```
% ./node_modules/.bin/electron | xxd
00000000: 0d0a                                     ..
```

**Comment by zcbenz** [comment]
This behavior is introduced by #3056 to make the output easier to read under cmd.

And you should not rely on the stdout of Electron anyway, apart from your own output, it is possible for Electron and Chromium to print their own error messages into console. I'm closing this as won't fix.
