### ISSUE TITLE
fullscreen:true should ignore/override max-width

### ISSUE THREAD

**Issue by paulmolluzzo** [electron/electron#5918]
* Electron version: 1.2.0
* Operating system: OSX

When you set a `maxWidth` inside a new `electron.BrowserWindow` and keep `fullscreen` allowed, the `max-width` is preserved in the fullscreen state and you wind up with a colored BG:

![](https://cloud.githubusercontent.com/assets/737065/15396941/3d65cbee-1dac-11e6-8c7a-8844d3806f4a.png)

From https://github.com/sindresorhus/anatine/pull/54#issuecomment-220410067:

> I thought that going full screen would have ignored any width you set on the window or that setting a max width (or height) would disable the fullscreen option. The two seem mutually exclusive by definition.

In the [anatine](https://github.com/sindresorhus/anatine) project there is [a workaround](https://github.com/sindresorhus/anatine/blob/562e06e64ca31f95dcdcf8882440cfc3880428aa/index.js#L81-87) that changes the `maxWidth`. This workaround allows both a `maxWidth` and a fullscreen that play nicely.

I think that if you've explicitly set `fullscreen` then you've decided to ignore `maxWidth` in that state.

**Comment by zcbenz** [comment]
This is a feature of OS X, it allows an app to enter fullscreen without sizing to the size of screen. As a neutral framework standing in the middle between users and the system, Electron should not prevent users from making use of a platform-specific feature, even though it is sometimes not expected.

I'm closing this as won't fix.

**Comment by paulmolluzzo** [comment]
Thanks for the feedback @zcbenz. Any chance you have a link to some documentation from Apple about this? Is there some best practice to ease the effect for users?

**Comment by sindresorhus** [comment]
@zcbenz I agree with your argument, but it would be nice if we could achieve the expected result without having to resort to dirty hacks like:

```js
win.on('enter-full-screen', () => {
	win.setMaximumSize(2147483647, 2147483647);
});
```

Maybe an option like `fullscreenFill`? That ignores maxWidth/maxHeight settings in fullscreen.

**Comment by zcbenz** [comment]
@sindresorhus If we implement it in Electron, it would use the exact same dirty hack with your code, plus a new option that only few people use. It is probably better to keep the dirty hack where people want it.
