### ISSUE TITLE
An Electron window will load certain resources when the user drags and drop them.

### ISSUE THREAD

**Issue by jviotti** [electron/electron#5919]
This issue was reported by one of our users (Etcher): https://github.com/resin-io/etcher/issues/430

If you drag an image (and probably other resources, like an HTML file, etc) to the Electron window, the WebView will load it up. I know this is the default behaviour from web browsers, but I believe it makes no sense in the context of a desktop application, and degrades the overall experience.

The user provided a fix, but before applying it to our codebase, I'm interested to hear if you think I'd be worth committing to Electron itself, as a way to make Electron experience more "desktop-like".

* Electron version: v1.1.1, but probably happens in all of them.
* Operating system: All.

**Comment by bnookala** [comment]
@jviotti Hey! Just wanted to share our (Ghost-Desktop's) experience working with this. The Ghost editor allows a user to drag and drop content to embed it. We still allow drag and drop to occur, but prevent the default behavior of navigating away by adding an event listener for the `will-navigate` event:

```mainWindow.webContents.on('will-navigate', (event) => event.preventDefault());``` 

Above line from: https://github.com/TryGhost/Ghost-Desktop/blob/master/main/entry.js#L61

Hope that helps :)

**Comment by MarshallOfSound** [comment]
The simple solution is to simply `preventDefault` on drag and drop events

```js
document.addEventListener('dragover', (event) => {
  event.preventDefault();
  return false;
}, false);

document.addEventListener('drop', (event) => {
  event.preventDefault();
  return false;
}, false);
```

**Comment by zcbenz** [comment]
The `will-navigate` event is designed exactly for this purpose, thanks for all your answers, I'm closing this issue.

**Comment by jviotti** [comment]
Awesome, thanks for the quick answers!

**Comment by nicoschmitt** [comment]
This should be by default IMHO.
