### ISSUE TITLE
Many windows bug

### ISSUE THREAD

**Issue by Valeriy-Zainullin** [electron/electron#5920]
* Electron version: v1.2.1
* Operating system: Linux Mint 17.3 Rosa x64
* Graphical shell : Unity 7.2.6

1. Many windows opened. You can run `npm install && npm start` to see. Supposed only one window.
![2016-06-07 22 04 51](https://cloud.githubusercontent.com/assets/16137770/15871215/7b686584-2d04-11e6-932c-8b38f3a1a846.png)
[electron bug.zip](https://github.com/electron/electron/files/303331/electron.bug.zip)

2. Will you add native error popups? If my application can`t continue work, it will call a function to throw a fatal error and a error popup will be displayed.

**Comment by zcbenz** [comment]
> Many windows opened. You can run npm install && npm start to see. Supposed only one window.

It is your code opening a second window by calling `window.open`.

> Will you add native error popups? If my application can`t continue work, it will call a function to throw a fatal error and a error popup will be displayed.

Please view the docs of `dialog` module.
