### ISSUE TITLE
addDevToolsExtension and React Developer Tools

### ISSUE THREAD

**Issue by epsitec** [electron/electron#5931]
* Electron version: 1.2.1
* Operating system: Windows 7 x64

I was excited to try out _React Developer Tools_ (v0.14.11) in electron, since there should be support for it as of version 1.2.1.

I added this to my `main.js` file:

```javascript
app.on ('ready', function () {

  BrowserWindow.addDevToolsExtension ('./chrome-extensions/react-dev-tools/');

  rootWindow = new BrowserWindow({
    width: 960,
    height: 600,
    center: true,
    autoHideMenuBar: true,
    icon: 'app-icon.png',
    'auto-hide-menu-bar': true,
    'use-content-size': true
  });

  rootWindow.on ('closed', function () {
    rootWindow = null;
  });

  rootWindow.toggleDevTools ();
  // ...
});
```

I see the `react-developer-tools` message displayed on the console, so I'd expect to see the **React** tab show up in the _Developer Tools_ window. No chance, it does not:

![github](https://cloud.githubusercontent.com/assets/3872435/15883284/102d8568-2d47-11e6-909b-36e80c1651e9.png)

#5854 points out that `BrowserWindow.addDevToolsExtension()` does not return any value if the extension is already registered. But since the message gets displayed in the console, the tools should be loaded OK.

What did I miss here?

**Comment by epsitec** [comment]
Ah, and I still get the message:

> Download the React DevTools for a better development experience: https://fb.me/react-devtools

every time I start my application.

**Comment by felicienfrancois** [comment]
https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md#how-to-load-a-devtools-extension

**Comment by felicienfrancois** [comment]
`BrowserWindow.addDevToolsExtension` may need an absolute path.

```javascript
BrowserWindow.addDevToolsExtension(require('path').join(__dirname, 'chrome-extensions', 'react-dev-tools'))
```

**Comment by zcbenz** [comment]
Are you loading the extension from the one downloaded by Chrome, or the repo of react-devtools?

**Comment by MarshallOfSound** [comment]
@zcbenz I'm having this isse as well.  I am downloading the extension from [here](https://clients2.google.com/service/update2/crx?response=redirect&x=id%3Dfmkadmapgofadopljbjfkapdkoienihi%26uc&prodversion=32)

That is the exact download URL from the Chrome WebStore.

`BrowserWindow.addDevToolsExtension(path)` correctly returns `"React Developer Tools"` but the tab does not appear in the developer tools.

**Comment by zcbenz** [comment]
Can you see whether the FAQ of react-devtools can solve your problem?
https://github.com/facebook/react-devtools#the-react-tab-doesnt-show-up

If you are sure you are using a up-to-date version of React, can you also try inspecting existing React sites like http://todomvc.com/examples/react?

**Comment by MarshallOfSound** [comment]
@zcbenz OK, so on further examination the dev tools load correctly in the top level renderer process (and work).  However when you inspect a WebView the devtools load incorrectly (`.addDevToolsExtension` returns `undefined`) and does not show the tab.

My initial report was based on a log from the top renderer process and the devtools of the webview 😆 

Is there any reason why the extension wouldn't load inside a WebView's devtools?

**Comment by zcbenz** [comment]
@MarshallOfSound It is a bug and being fixed at #5913.

**Comment by MarshallOfSound** [comment]
Well that's my problem sorted then 👍 😆 

On a somewhat related topic though I wrote this module to help people with installing Chrome DevTool Extensions.

https://github.com/GPMDP/electron-devtools-installer

It's quite a bit less hassle than the "download, find, unzip, copy path" process 😆

**Comment by bengotow** [comment]
Hi folks,

For others stumbling across this—you might also find that React appears but says "Connecting to React..."  forever. In your page Content Security Policy, you need to whitelist "chrome-extension://" as a source.

**Comment by epsitec** [comment]
I am still stuck, but this might be caused by some basic misunderstanding of where I should load the devtools from.

* I've used the very same devtools than those which I installed in Chrome (and which work just fine there).
* I've made sure that this is not an issue with the _path_. Setting an invalid path will produce an error.
* I'm using the most recent React.

I am loading the devtools from the **main process** but I expect them to show up in the **renderer** devtools window. Is my approach correct? What did I miss?

**Comment by MarshallOfSound** [comment]
@epsitec based on DevTron you can't install extensions from the main process

https://github.com/electron/devtron/blob/master/api.js#L5

**Comment by kevinsawicki** [comment]
> based on DevTron you can't install extensions from the main process

You should be able to install them from both processes, I opened https://github.com/electron/devtron/pull/80 to support this in Devtron.

**Comment by kevinsawicki** [comment]
@epsitec can you try Electron 1.2.3 and see if you still have issues getting the react devtools workign?

**Comment by citycide** [comment]
I'm having this same issue with the Vue dev tools. `addDevToolsExtension()` returns `Vue.js devtools` but no tab is added. The extension was downloaded directly from the Chrome store.

For what it's worth, I also have Devtron installed and it appears as expected. 

Electron 1.2.3

**Comment by MarshallOfSound** [comment]
@citycide Try electron `1.2.1`

**Comment by citycide** [comment]
@MarshallOfSound No change.

**Comment by epsitec** [comment]
@kevinsawicki I've upgraded to version 1.2.3 of electron. It is still not working...

The code below logs `addDevToolsExtension: React Developer Tools` to the console,
which should be the proof that the tools got found (and loaded). But they do not show
up in the developer tools (inspector window).

```javascript
'use strict';

var app           = require ('electron').app;
var BrowserWindow = require ('electron').BrowserWindow;
var Menu          = require ('electron').Menu;

var rootWindow = null;
var menu       = null;

app.on ('window-all-closed', function () {
  app.quit ();
});

app.on ('ready', function () {

  console.log ('addDevToolsExtension: ' + BrowserWindow.addDevToolsExtension ('./chrome-extensions/react-dev-tools/'));

  rootWindow = new BrowserWindow ({
    width: 960,
    height: 600,
    center: true,
    autoHideMenuBar: true,
    icon: 'app-icon.png',
    'auto-hide-menu-bar': true,
    'use-content-size': true
  });

  rootWindow.on ('closed', function () {
    rootWindow = null;
  });

  rootWindow.toggleDevTools ();
  console.log ('Opening: ' + process.argv[2]);
  rootWindow.loadURL (process.argv[2]);
  rootWindow.focus ();
  // ...
}
```

**Comment by kevinsawicki** [comment]
@epsitec do they show up if you call `rootWindow.loadURL('http://todomvc.com/examples/react')` ?

**Comment by MarshallOfSound** [comment]
@kevinsawicki As per #6101 react dev tools don't work on any electron version above `1.2.1`

**Comment by epsitec** [comment]
@kevinsawicki I've been finally able to make the React DevTools work on my setup. No idea why it did not work previously, and no idea why it works now. But at last, it works...

**Comment by rimatla** [comment]
@epsitec  Could you pls provide a working copy? I'm a beginner on electron, and am currently having the same issues that you previously had. Thank you.

**Comment by epsitec** [comment]
@rimatla My snippet is all I do now for the `react-devtools` to show up.
