### ISSUE TITLE
It doesn't work when it packages all app files for one with Enigma Virtual Box since v1.1.1

### ISSUE THREAD

**Issue by hypocenter** [electron/electron#5933]
* Electron version:1.1.1 or higher
* Operating system:Window 32bit

But 1.0.2 work well.

**Comment by hypocenter** [comment]
I have used those settings to packaged all Electron files into one executable file, with 1.1.1 or higher version, the generated .exe file couldn't open, but v1.0.2 worked well.
To be precise, it had ready opened, but no window showed, after a few seconds it automatically quited.
![a617295f-3846-4ed7-b22b-ecd67755145f](https://cloud.githubusercontent.com/assets/14862661/15888603/15a958b6-2d9a-11e6-82a5-8e020a1d057b.png)

**Comment by paulcbetts** [comment]
I suspect you need to file an issue with Enigma Protector

**Comment by MarshallOfSound** [comment]
I think you might have to update your config.  Don't forget that as of `1.1.0` we use VS2015 files.

This change note is relevant

> Link statically with Visual C++ libraries. #5538, #5602 

You probably just need to change which DLL's you are including 👍

**Comment by kevinsawicki** [comment]
Closing this out since it seems very likely related to the change @MarshallOfSound mentioned.

Please comment if you are still experiencing this.

**Comment by ertee** [comment]
I can't figure out what needs to be packed to support version 1.1.0 and beyond of Electron for executable packaging apps.  Prior to 1.1.0, we were just able to package everything in the Electron distribution along with our application into an executable using something like Enigma VB mentioned above.  Now if we pack the entire distribution it no longer launches.

Are there a separate set of .dlls now not shipped with Electron that need to be downloaded and packaged?
