### ISSUE TITLE
mainWindow.loadUrl Error on Startup

### ISSUE THREAD

**Issue by KillaByte1110** [electron/electron#5935]
* Electron version: 1.2.0
* Operating system: Windows 10 Home 64-Bit

Sorry, I'm new to electron and coding, so please forgive me for my mistakes but whenever I try opening my code it comes up with mainWindow error, and I don't know what's wrong, so please help find my mistakes.

```
const electron = require('electron')
const {app} = electron
const {BrowserWindow} = require('electron')

app.on('ready', function() {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  })
  mainWindow.loadUrl('file://' + __dirname + '/index.html')
})

````

P.S I took most code from a around 1 year old video, so the commands could be out of date, new commands etc.

Thanks in advance!

**Comment by danhp** [comment]
You're correct, the API has changed since then.
I recommend having a look over [electron-quick-start](https://github.com/electron/electron-quick-start) to see how to setup a minimal app.
