### ISSUE TITLE
connect to symbol server timeout

### ISSUE THREAD

**Issue by chensy123** [electron/electron#5936]
* Electron version:
v1.0.2
* Operating system:
windows 8

i  often download electron.exe.pdb fail(download timeout) ;
is there other way download electron.exe.pdb and node.dll.pdb for electron v1.0.2?
thanks;

**Comment by zcbenz** [comment]
If you use windbg you can turn on noisy mode and it will print the download links of PDB symbols, you can then try to use some download tools to download them.
