### ISSUE TITLE
Cookies not getting removed.

### ISSUE THREAD

**Issue by Bigmacbook** [electron/electron#5937]
* Electron version: 1.2.1
* Operating system: Windows 10

I'm using twitch.tv oauth login in a different BrowserWindow than my main app. I wanted to add a function to allow the user to logout of twitch by clearing the cookies set by twitch.tv but its not working at all.

Code:
```
electron.session.defaultSession.cookies.get({
        url: 'http://twitch.tv'
    }, function(error, cookies) {
        var array = Object.keys(cookies)
        for (var i = 0; i < array.length; i++) {
            console.log(cookies[array[i]].name)
            electron.session.defaultSession.cookies.remove('http://twitch.tv', cookies[array[i]].name, function(){})
        }
    })
```

Now when I go back to check if the cookies are there with "electron.session.defaultSession.cookies.get" there are none listed, but I'm still logged into twitch.

I then go to the appdata folder with local storage, cache files, etc. I delete the Cookies file and all of sudden I'm logged out and the cookies are cleared.

So cookies aren't really being removed?!

**Comment by zcbenz** [comment]
Can you open devtools and see if the url actually matches the one in cookies?

**Comment by Bigmacbook** [comment]
It appears that is the problem. 

When I tried to get the cookies by the domain property ".twitch.tv"  instead of the url property "http://twitch.tv" I was able to get the extra cookies that were missing.

 Now the only problem is I can't delete them because the remove cookie function doesn't support the domain property that is included in the get cookies function.

I would try and delete it by its url but the url is the same as shown in the inspector 
![](http://i.imgur.com/UGYVqv9.png)

**Comment by zcbenz** [comment]
Have you tried calling `remove('http://www.twitch.tv', ...)` and `remove('https://www.twitch.tv', ...)`? Chromium doesn't provide the ability to delete cookie by domain, you have to pass URL.

Or you can simply choose to remove all cookies with `ses.clearStorageData`:
http://electron.atom.io/docs/api/session/#sesclearstoragedataoptions-callback
