### ISSUE TITLE
Export file with Electron - temporary file in download folder

### ISSUE THREAD

**Issue by jechazelle** [electron/electron#5938]
Hi,
I use Electron and AngularJS.

In my project, I try to export a configuration file with simply code in my function :

```
$scope.exportProject = function () {
var blob  = new Blob(['my content'], {type: 'text/json'}),
 event = document.createEvent('MouseEvents'),
 file  = document.createElement('a');

// Name file
file.download = 'my_config';

// Create link
file.href = window.URL.createObjectURL(blob);
file.dataset.downloadurl = ['text/json', file.download, file.href].join(':');

// Init event
event.initEvent('click', true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);

// Dispatch event
file.dispatchEvent(event);
}
```

But when I submitted my app on the MAS, Apple return an error after validation :

```
The application accesses the following location(s):

'~/Downloads/.org.chromium.Chromium.2YmTp9'

The user did not select to export to the ~/Downloads folder.


The majority of developers encountering this issue are opening files in Read/Write mode instead of Read-Only mode, in which case it should be changed to Read-Only.

The user did not select to export to the ~/Downloads folder.

The app should not be writing in a location the user did not select.
```

I have a window to choose the destination, but there is a temporary file.. How can I don't use a temporary file or export file without error please ?

I use in my sandbox config on iTC, com.apple.security.files.user-selected.read-write. If I use com.apple.security.files.user-selected.read-only, my app freeze because the window to choose the destination doesn't show.

* Electron version: 1.2.2
* Operating system: Mac

**Comment by zcbenz** [comment]
This is how Chromium's download feature is designed, if you want to avoid having temporary files you have to use Node's `fs` module or other features to directly write the file to filesystem.

**Comment by jechazelle** [comment]
@zcbenz thx for your answer, but how can I use fs in AngularJS ?

Use fs in the main it's easy but my function is in function from AngularJS

**Comment by zcbenz** [comment]
I don't know how you setup your project but usually you can just call `require('fs')`. Another choice is to hook the `will-download` event in the main process.

For more questions I suggest seeking help from [the community](https://github.com/electron/electron#community).
