### ISSUE TITLE
New Headless Chromium

### ISSUE THREAD

**Issue by rickmed** [electron/electron#5939]
The chromium team is developing a way to run headless chromium natively. https://bugs.chromium.org/p/chromium/issues/detail?id=546953#c54

AFAIK the way to implement it now would be: https://chromium.googlesource.com/chromium/src/+/master/headless/README.md

Any plans to integrating into electron. It would be an invaluable addition IMO.

**Comment by zcbenz** [comment]
I'm merging this to #228.
