### ISSUE TITLE
Setting window position with decimal values fails

### ISSUE THREAD

**Issue by jdfwarrior** [electron/electron#5940]
* Electron version: 1.2.2
* Operating system: Mac OS X 10.11.5

I was tinkering with some code and while attempting to position a child window based on the position of the parent, if the resultant position (x,y) results in a decimal values, setting the x,y coords of the child window fails and it will fall back to centering (default). 

Didn't know if you guys wanted to handle wrapping the x,y coordinates in parseInt or if you wanted to leave that to the user. If it's left to the user, it should probably at least be listed in the documentation that specifying a decimal value will fail.

**Comment by zcbenz** [comment]
It is documented in that the type of `x` and `y` is Integer.

**Comment by johnryan** [comment]
@zcbenz should the documentation for `setBounds` and the like be updated as well? [Rectangle](https://github.com/electron/electron/blob/master/docs/api/structures/rectangle.md). This throws a pretty unhelpful javascript error on windows:

> Error processing argument at index 0, conversion failure from [object Object]
