### ISSUE TITLE
Tray icon disappearing 

### ISSUE THREAD

**Issue by nickdima** [electron/electron#5941]
* Electron version: 0.37.8
* Operating system: Mac OS X 10.11.4 

I'm creating a tray icon which seems to disappear after exactly one minute on every run.
What could it be?

**Comment by MarshallOfSound** [comment]
That's a garbage collection issue.  You need to maintain a reference to the tray object.

**Comment by nickdima** [comment]
OK, I was thinking it might be that. Thanks!
