### ISSUE TITLE
How to load mainWindow.loadUrl from tray menu?

### ISSUE THREAD

**Issue by akashnimare** [electron/electron#5946]
I have built a very basic app and loading a URL from mainWindow.loadUrl. The Url could be anything here. It's basically a ip-address and could be different from every users. Is it possible to use something like -
 ` mainWindow.loadUrl = userdefinedUrl`

This is the pseudo code I am using to implement this but no luck -

    var app = require('app');
     var BrowserWindow = require('browser-window');
     var ipc = require('ipc');
     var mainWindow = null;
     var settingsWindow = null;
     app.on('ready', function() {
     mainWindow = new BrowserWindow({
        frame: false,
        height: 700,
        resizable: false,
        width: 368
     });
     mainWindow.loadUrl($userdefinedUrl);
     });

     ipc.on('close-main-window', function () {
    app.quit();
    });

    ipc.on('open-settings-window', function () {
     if (settingsWindow) {
        return;
     }
    settingsWindow = new BrowserWindow({
        frame: false,
        height: 200,
        resizable: false,
        width: 200
    });

    settingsWindow.loadUrl('file://' + __dirname + '/app/settings.html');
    settingsWindow.on('closed', function () {
        settingsWindow = null;
        mainWindow.loadUrl($userdefinedUrl);
    });
    });

    ipc.on('close-settings-window', function () {
     if (settingsWindow) {
        settingsWindow.close();
     }
    }); `

<b>open-settings-window is called when user clicks on a settings menu</b>
Settings.html contains -

`<input type="text" name="url" value="">`

Now how do I get this value and put it in variable <b>userdefinedUrl</b>
I am not able to implement this. Would be a great help if you guys can provide any suggestions on this.

https://github.com/WebDevLabs-SVNIT/cyclient

**Comment by zcbenz** [comment]
This is a question on using Electron, I suggest seeking help from [the community](https://github.com/electron/electron#community) instead.

**Comment by vinkerz** [comment]
try loadURL instead of loadUrl
