### ISSUE TITLE
Feature request: much easier external links

### ISSUE THREAD

**Issue by dukedougal** [electron/electron#5947]
I really wish it was easier to include links that are loaded in the default OS browser.

**Comment by felixrieseberg** [comment]
It's currently a one-liner. What do you have in mind?

```
shell.openExternal('https://github.com');
```

**Comment by MarshallOfSound** [comment]
Not sure what @dukedougal had in mind.

But adding another target attribute (if possible) for `_external` would be really helpful.  Wrapping links with Javascript click events (although simple) can be quite tiresome.

```html
<a href="http://electron.atom.io" target="_external">Electron</a>
```

Currently I'm doing this myself with

```js
import { shell } from 'electron';

[].forEach.call(document.querySelectorAll('[target="_external"]'), (link) => {
    link.addEventListener('click', (event) => {
        shell.openExternal(link.href);
        event.preventDefault();
    });
});
```

Implementing that functionality inside Electron natively though would be useful 😄

**Comment by davej** [comment]
@MarshallOfSound I would be -1 on this. Tehcnically it could break existing webpages if they contain frames with the name 'external'. Also I just don't see the point of introducing a new API for something that can be trivially done in javascript (as you've shown).

**Comment by MarshallOfSound** [comment]
@davej Yeah, I remembered the code being a lot more annoying than it is :laughing: 

Adding an API for what is a one off 7 liner is a bit overkill I agree.  Adding this 7 liner (or something similar) to the `openExternal` docs might help a few people.

**Comment by davej** [comment]
@MarshallOfSound Or just create a module and put it on npm 😄

**Comment by MarshallOfSound** [comment]
@davej Woo hoo, module all the things 😆

**Comment by sindresorhus** [comment]
There's an easier solution. Just listen to new window events.

```html
<a href="http://electron.atom.io" target="_blank">Electron</a>
```

```js
win.webContents.on('new-window', (e, url) => {
	e.preventDefault();
	electron.shell.openExternal(url);
});
```

**Comment by dukedougal** [comment]
@sindresorhus where exactly in my electron application would I put the win.webContents.on function?

**Comment by MarshallOfSound** [comment]
@dukedougal You can put it in main or renderer it doesn't matter

```js
// Main
import { shell } from 'electron';

mainWIndow.webContents.on('new-window', (e, url) => {
    e.preventDefault();
    shell.openExternal(url);
});


// Renderer
import { remote, shell } from 'electron';

remote.getCurrentWindow().webContents.on('new-window', (e, url) => {
    e.preventDefault();
    shell.openExternal(url);
});
```

**Comment by zcbenz** [comment]
Thanks for all the solutions on this, I'm closing this issue now.
