### ISSUE TITLE
Array constructor doesn't have the identity of Array

### ISSUE THREAD

**Issue by avoidwork** [electron/electron#5948]
* Electron version: 1.2.2
* Operating system: OSX 10.11.5

Hi,

I've run into an issue of a third party script relying on `[].constructor === Array` for tests, which return `true` on the desktop browser, but `false` in Electron 1.x; the code works in 0.37.x.

Is this intentional with 1.x?

**Comment by zcbenz** [comment]
I can't reproduce this with following steps:

1. open default app and open devtools in it
2. run `[].constructor === Array` in console

**Comment by avoidwork** [comment]
<img width="916" alt="screen shot 2016-06-08 at 9 53 00 pm" src="https://cloud.githubusercontent.com/assets/369698/15918380/78dfdaa8-2dc3-11e6-8d57-712ad45f2ada.png">

**Comment by avoidwork** [comment]
The window is created with the following:

```
new BrowserWindow({
	frame: true,
	height: settings.size[1],
	width: settings.size[0],
	minWidth: 480 + (!osx ? 20 : 0), // scroll bar + theme
	minHeight: 580 + (!osx ? 40 : 0), // menu + theme
	resizable: true,
	show: !hidden,
	title: 'Adobe Hub',
	webPreferences: {
		preload: preload
	}
})
```

Our builds on the 0.37.x code base function correctly, only ones in 1.x seem to get this constructor property wrong. I'm not sure what the cause could be, possibly some config found in our app is triggering this?

**Comment by avoidwork** [comment]
This is from the default app:

<img width="916" alt="screen shot 2016-06-08 at 10 05 01 pm" src="https://cloud.githubusercontent.com/assets/369698/15918563/223a15ea-2dc5-11e6-988c-d9b5dc6e012d.png">

So, it appears that there's something going wrong with my app.

**Comment by avoidwork** [comment]
Would you like the script that launches the app, or a zip of the app? I can't post either on here, but I could email it over, considering the issue is blocking a release I believe this would be ok.

**Comment by avoidwork** [comment]
I just removed all of the third party scripts from the app and the expected result happens. I'll post anything interesting I find while I dig into this.
