### ISSUE TITLE
Grabbing file path from input=file

### ISSUE THREAD

**Issue by ErraticFox** [electron/electron#5949]
* Electron version: 1.2.2
* Operating system: Win10

Is it possible to upload a file via input file method and put the path of the file into a var?

**Comment by zcbenz** [comment]
Try:

```js
document.getElementsByTagName('input')[0].files[0].path
```

More about Electron's extension to `File` can be found at:
http://electron.atom.io/docs/api/file-object/

Currently there is no way to add a path to input tag, which is tracked at #749.

**Comment by foreshadow** [comment]
I am using electron with angular and the TS compiler does not recognize the extra `path` attribute, what should I do?
```
error TS2339: Property 'path' does not exist on type 'File'.
```

**Comment by foreshadow** [comment]
I managed by `(input.files[0] as unknown as { path }).path`.
