### ISSUE TITLE
ctrl+w closes my app

### ISSUE THREAD

**Issue by farzher** [electron/electron#5951]
* Electron version: "electron-prebuilt": "^1.2.0"
* Operating system: Windows 10

I know ctrl+w is the standard hotkey to close tabs, but isn't that up to me to handle, and not an OS thing? Is electron supposed to exit my app when I press ctrl+w? How can I stop this.

This happens to me with the default `electron-quick-start` code

**Comment by OlsonDev** [comment]
[Change or remove](http://electron.atom.io/docs/api/browser-window/#winsetmenumenu-linux-windows) the default [menu](http://electron.atom.io/docs/api/menu/). Note the default menu has `Window > Close    Ctrl+W`.

**Comment by farzher** [comment]
The app I'm working on has all the toolbars hidden which is why I had no idea what was causing this.
I ran the `electron-quick-start` real quick to confirm it wasn't just my app but I didn't notice the header menus... I'm dumb. Thanks!
