### ISSUE TITLE
installedDevToolsExtensions() API

### ISSUE THREAD

**Issue by davej** [electron/electron#5960]
Libraries like `electron-debug` programatically add a devtools extension (https://github.com/sindresorhus/electron-debug/pull/36). This works fine but on subsequent loads it prints the following to console:

```
Attempted to load extension "devtron", but extension was already loaded!
```

No big problem but it clutters up the console. A suggested alternative would be to check if the devtool already exists before trying to install it. Here are two possible APIs which could work:

```js
BrowserWindow.installedDevToolsExtensions(); // -> ['devtron', 'React Developer Tools'];
// or
BrowserWindow.isDevToolExtensionInstalled('devtron'); // -> `true`
```

* Electron version: 1.2.2

**Comment by kevinsawicki** [comment]
> BrowserWindow.isDevToolExtensionInstalled('devtron')

👍 Sounds good, added in https://github.com/electron/electron/pull/5965
