### ISSUE TITLE
Function of autoUpdater - what version is the "latest" ?

### ISSUE THREAD

**Issue by mzmousa** [electron/electron#5961]
* Electron version: Latest
* Operating system: Mac/Windows

I have autoUpdater implemented in my app. It checks for updates and works fine, but I'd like to know more about how it works. I am using Nuts to host my github releases. From my understanding, we need to provide the feedUrl `http://myDownloadurl.com/download/latest` so that we get the latest version of our app to update. However, I'm confused as to how the "latest" version is determined. Is it by the latest github release? Is it the release of the app that has the highest numerical value for version? If it _doesn't_ go by that, is there a way to "change" what the latest release of my app is before checking for updates, so that it gets the "latest" one I would like?

Also, what if I didn't want to update to the latest version? Is there a way to checkForUpdates, but set the feedUrl to get an update on a version of the app that is not the latest?

Any information / knowledge of autoUpdater's functionality is appreciated.

**Comment by MarshallOfSound** [comment]
The latest version is determined by nuts as the highest [semver](http://semver.org/) tagged release on GitHub.

The feed URL you need to set is actually

```js
import { app, autoUpdater } from 'electron';

let platform = 'win';
if (process.platform === 'darwin') {
  platform = 'osx';
}

autoUpdater.setFeedURL(`https://myDownloadurl.com/update/${platform}/${app.getVersion()}`);
```

The autoUpdater will always search for the latest version so you can't get a version that is not "latest".  If you want to do something like that I would suggest looking into the beta/stable streams that nuts supports or try hosting multiple nuts servers (one for beta and one for stable).

**Comment by mzmousa** [comment]
I get the same results when setting my feedUrl to contain `update` and `download`. Is there a major difference and should I be worried about it?

**Comment by MarshallOfSound** [comment]
@mzmousa `download` will never download `.nupkg` files on windows so you will always reinstall from the setup exe as opposed to updating from a `nupkg` or a `-delta.nupkg`.  (As far as I know)

**Comment by mzmousa** [comment]
autoUpdater has been working for me with `download` in my feedUrl, but I only had `-full.nupkg` in my releases. I'll try to generate a `-delta.nupkg` and then try with both `download` and `update` tomorrow  to see if there's a difference, and get back to you :smiley:

**Comment by MarshallOfSound** [comment]
@mzmousa It might be that something has changed or they are just mirrors of each other.  I'm using a reasonably old version of nuts.  I don't want to update the server while it still works out of fear that thousands of people will end up with version locked programs 😨

**Comment by zcbenz** [comment]
Thanks @MarshallOfSound for answering this, I'm closing this issue since it is a question.

**Comment by mzmousa** [comment]
Yes, thank you @MarshallOfSound .

**Comment by damianobarbati** [comment]
@zcbenz @MarshallOfSound what is the correct feedURL for a public GitHub repository with releases?

I tried `https://github.com/username/reponame/releases/latest` with no success.
