### ISSUE TITLE
Cannot read property name of undefined loading invalid devtools extension path

### ISSUE THREAD

**Issue by Mercieral** [electron/electron#5962]
* Electron version: 1.2.2
* Operating system: OS X El Capitan 10.11.15
* Ember Inspector 1.10.0 (downloaded through chrome extensions)

I am having issues trying to get Ember Inspector to show up in Dev Tools. I followed the directions as described [here](https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md).

![screen shot 2016-06-09 at 10 38 41 am](https://cloud.githubusercontent.com/assets/10813646/15934302/179332e0-2e31-11e6-9656-3f2f00912213.png)

Here is my main file, line 15 as indicated in the error message is the line calling addDevToolsExtension(...).
```javascript
const electron = require('electron');
const {app} = electron;
const {BrowserWindow} = electron;

let win;

function createWindow() {

    win = new BrowserWindow({width: 800, height: 600, "node-integration": false});
    win.maximize();
    win.loadURL(`file://${__dirname}/index.html`);

    BrowserWindow.addDevToolsExtension("~/Library/Application Support/Google/Chrome/Default/Extensions/bmdblncegkenkacieihfhpjfppoconhi/1.10.0_0");

    // Open the DevTools
    win.webContents.openDevTools();

    win.on('closed', () => {
        win = null;
    });

}


app.on('ready', createWindow);

// Quit when all windows are closed.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    if (win === null) {
        createWindow();
    }
});
```
I have not tried an earlier version of Ember Inspector but may try that soon. The link above states that " Following Devtools Extensions are tested and guaranteed to work in Electron:" and lists Ember Inspector.

**Comment by enlight** [comment]
Get rid of the `~` in the extension path, use an absolute path. And if that doesn't fix it try using https://github.com/GPMDP/electron-devtools-installer

**Comment by kevinsawicki** [comment]
I'm going to open a pull request that throws a better error in this case instead of reading property of undefined.

**Comment by Mercieral** [comment]
@enlight Using the absolute path fixed it, thank you so much. That was not as difficult as I was imagining. I do feel like that should be made more obvious in the docs in [the link that I mentioned earlier](https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md).
