### ISSUE TITLE
Webview tag resizes to wrong size when transformed

### ISSUE THREAD

**Issue by gerhardberger** [electron/electron#5968]
* Electron version: **v.1.2.2**
* Operating system: **Mac OSX 10.11.6**

When I render a `<webview>` in a webGL scene with [gl-css3d](https://github.com/deathcap/gl-css3d), it resizes differently, when I render an `<iframe>`.
For example, here is two iframe with the same size as the Electron window and as can be seen, though it is 3D transformed with CSS and thus has an actual smaller size (as the `getBoundingClientRect` shows), the iframe window's size is the same (as the page's text and the `clientHeight/Width` shows):
![screen shot 2016-06-09 at 8 49 25 pm](https://cloud.githubusercontent.com/assets/1059699/15942477/dbf63cd8-2e84-11e6-8cc7-c65ea69ad7f6.png)

But when I use a `<webview>` instead of an `<iframe>`, it seems, that the `<webview>` is always resizing to the `boundingClientRect`, not the true size of the element:
![screen shot 2016-06-09 at 8 47 48 pm](https://cloud.githubusercontent.com/assets/1059699/15942582/48316a44-2e85-11e6-8221-da0de45a6ef0.png)

I  tried to dig up, how the new size of the `<webview>` is calculated and got to [this](https://cs.chromium.org/chromium/src/content/renderer/browser_plugin/browser_plugin.cc?q=didresizeelement&sq=package:chromium&l=381&dr=C) call, perhaps it is here, where it gets wrong size.

**Comment by zcbenz** [comment]
Chromium is known to have problems with calculating webview's size when the transform style is applied, I'm merging this to #2168 since they are very likely the same problem.

I suggest also reporting this to Chromium's issues list, since we are not able to fix this on Electron's side.
