### ISSUE TITLE
Use non random ID for trayIcon

### ISSUE THREAD

**Issue by wa4557** [electron/electron#5969]
* Electron version: All
* Operating system: Ubuntu 16.04

Looking at the source code, https://github.com/electron/electron/blob/e05804848f98959d63337aacd9047cd579c5b23f/atom/browser/ui/tray_icon_gtk.cc#L30 it seems that for the AppIndicator tray icon uses a randomly generated ID for the tray icon. This number changes everytime the app starts. This creates problems, because the ID is used in Ubuntu for changing order of tray icons, which is impossible if the ID changes everytime the app starts. 

Is there a reason why a Random number is used as AppIndictor ID? Is it possible to change that to let's say the app name, or at least to something that is not random?

**Comment by zcbenz** [comment]
I think we can change the ID to something like `app_name_1`.

**Comment by wa4557** [comment]
Great! Would you accept a PR with a fix?

**Comment by zcbenz** [comment]
Sure, a PR would be awesome.

**Comment by wa4557** [comment]
Alright, pushed a fix. seems to be working :)
