### ISSUE TITLE
.NET Docs

### ISSUE THREAD

**Issue by mcole1976** [electron/electron#5973]
* Electron version:
* Operating system:
Is there a basic demo or documentation on how to get this working with Visual Studio?

**Comment by kevinsawicki** [comment]
> Is there a basic demo or documentation on how to get this working with Visual Studio?

Could you be a little more specific on what you mean by this? What are you trying to do?

**Comment by mcole1976** [comment]
I am brand new to this i have seen some further docs and that gives me something to work with, I just saw some basic docs in another area bout VS! I need no help on this excuse the incursion!

**Comment by kevinsawicki** [comment]
You might want to start with the quick start guide, http://electron.atom.io/docs/tutorial/quick-start/

If you have further questions you might want to try the message boards, https://discuss.atom.io/c/electron and the slack channel, http://atom-slack.herokuapp.com/

Closing this out.

**Comment by mcole1976** [comment]
wilco it was the build page and me misreading some stuff thanks for the help
