### ISSUE TITLE
How debug the project

### ISSUE THREAD

**Issue by ray26** [electron/electron#5976]
* Electron version:1.3
* Operating system:osx10.11.6
I want ot know how to debug the electron project , my project site is :https://github.com/geeeeeeeeek/electronic-wechat

**Comment by callmewhy** [comment]
It's github not stackoverflow.

**Comment by zcbenz** [comment]
For debugging an Electron app, just open the devtools, for debugging Electron itself, it is basically the same with debugging Chromium browser and you can find guides on http://dev.chromium.org/Home.
