### ISSUE TITLE
jQuery not outputting file path.

### ISSUE THREAD

**Issue by ErraticFox** [electron/electron#5981]
* Electron version: 1.2.2
* Operating system: Win10

Hello. For some reason, jQuery is not taking the path. But if I log my variable before it goes to the jQuery block it's fine.

```
/* this console log displays the path */
        function button() {
            var dir = inputFile.files[0]
            console.log(dir);
        }

        $("document").ready(function() {
            $("#inputFile").change(function() {
                $("#fileDir").animate({
                    opacity: '1'
                });
                $("form").animate({
                    top: "70px"
                });
                $(".black-text").text(dir);
                console.log(dir);
            });
        });
/* this console log displays undefined */
```

**Comment by jpittner** [comment]
dir is defined in the scope of button function, which incidentally doesn't get called anywhere in your code. This doesn't have anything to do with electron.

**Comment by zcbenz** [comment]
Thanks @jpittner for answering it, I'm closing this issue now. For further questions I suggest seeking help from [the community](https://github.com/electron/electron#community).
