### ISSUE TITLE
Webframe error.

### ISSUE THREAD

**Issue by ahgan84** [electron/electron#5982]
Hi guys, I'm using win10 and electron-prebuilt 1.1.1. I encounter error when trying to use a zoom in function from webframe. Is the below code correct?
`
const electron = require('electron'); const {app} = electron; const {BrowserWindow} = electron; let win; var settings = require('./settings'); const {ipcMain} = require('electron'); const {webFrame} = require('electron'); webFrame.setZoomFactor(2);`

The error is :
`Cannot read property 'setZoomFactor' of undefined.`

I call the function at the top of the page. Is it correct?
If it is wrong then where should I put the webframe function in my code?

**Comment by ahgan84** [comment]
I use another approach and it worked. I put in web-preference.

`win = new BrowserWindow({ fullscreen: true, webPreferences: { zoomFactor: 2 }`

**Comment by zcbenz** [comment]
`webFrame` is only available in renderer process.
