### ISSUE TITLE
Mute Notifications when Webview is muted

### ISSUE THREAD

**Issue by HaNdTriX** [electron/electron#5983]
* Electron version: v1.2.2
* Operating system: OS X El Capitan 10.11.5

When `<webview>.isAudioMuted() === true` [Notifications](https://developer.mozilla.org/de/docs/Web/API/notification) from the Webview still make sounds.

**Comment by zcbenz** [comment]
This looks good to me, does Chrome have this behavior?

**Comment by HaNdTriX** [comment]
Chrome doesn't use default notification sounds so far i know.

**Comment by saenzramiro** [comment]
Hi @zcbenz,

Are you planning to add this enhancement in a future release?

Thanks!

**Comment by MarshallOfSound** [comment]
@zcbenz Chrome's notifications are actually silent by default.  Perhaps Electron should adopt that approach.

**Comment by zcbenz** [comment]
I'm 👍 with this, but macOS doesn't seem to provide an API for it.

**Comment by MarshallOfSound** [comment]
@zcbenz The `slient` attribute of the HTML5 Notification API works on macOS.

https://developer.mozilla.org/en-US/docs/Web/API/Notification/silent

Users can manually implement this with a wrapper similar to the one below

```js
import { remote } from 'electron';
const NativeNotification = window.Notification;

class SilentNotification extends NativeNotification {
    constructor(title, opts) {
        if (!opts.silent) {
            opts.silent = remote.getCurrentWebContents().isAudioMuted();
        }
        super(title, opts);
    }
}

window.Notification = SilentNotification;
```

**Comment by zcbenz** [comment]
Ah I forgot we already have `silent` implemented.

**Comment by MarshallOfSound** [comment]
Hmmm @zcbenz would you want this implemented in brightray somehow (I'm not sure that's possible). Or patched here?

**Comment by akashnimare** [comment]
@MarshallOfSound @zcbenz  Is it possible to hide/mute native notifications when the app is in foreground? It's kind of annoying 😭

**Comment by MarshallOfSound** [comment]
@akashnimare That would be down to app creators to implement functionality like that 👍

**Comment by akashnimare** [comment]
@MarshallOfSound I'm not so sure on this. If I open the app in chrome, notifications are not shown while the app is in the foreground. That's why I was wondering it's possible to implement same functionality on electron app as well 🤔   The dirty hack would be to kill the notifications while the electron window is focused but I don't how to do this 😸

**Comment by MarshallOfSound** [comment]
@akashnimare As mentioned before this would probably be up to the app creators to implement this functionality, you could probably use code similar to the sample I pasted above and simply not call `super` if the window is focused.

**Comment by akashnimare** [comment]
> simply not call super if the window is focused

@MarshallOfSound I don't get it. I just want to kill/hide the notifications if the window is in foreground/focused. I could get the window-focus event via IPC but I'm not sure how would I kill the notification then.

**Comment by KagamiChan** [comment]
you may check your conditions before `new Notification`
