### ISSUE TITLE
Spell check works wrong with German

### ISSUE THREAD

**Issue by mk213** [electron/electron#5985]
* Electron version: 1.1.0
* Operating system: Win8.1, OS X
 
We set up webFrame.setSpellCheckProviderw(language, autoCorrectWord, provider) to check German language. For German texts it works well. But when you  type English text - correct English words are marked as misspelled.

**Comment by jlord** [comment]
My guess is that spell check will only check against one language at a time. So if it's expecting German words, English words will be marked misspelled. Looking at the documentation for the OS X spellchecker that `node-spellchecker` uses:

> Returns the current language used in spell checking.

So I believe you can only be checking spelling in one language.

**Comment by mk213** [comment]
The problem is - we try to check only One language - German. But it start to check English text too.

With 'ru-RU'  everything works fine - webFrame.setSpellCheckProvider underlines wrong russian words and doesn't underlined English words at all:
_webFrame.setSpellCheckProvider('ru-RU', true, {
         spellCheck: function (text) {
             //this code is performed only when user input text in Russian, when Eng - no  
             return !customSpellChecker.isMisspelled(text);
         }
});_ 

So I guess the issue is not in custom spell-check provider, but in webFrame.setSpellCheckProvider.

**Comment by zcbenz** [comment]
@mk213 The `webFrame.setSpellCheckProvider` only deals with iterating words and reporting wrong words, it doesn't know which language the word belongs to. The spell checker under `ru-RU` probably just discards all non-russian words, while when language is German it is hard to distinguish English words.
