### ISSUE TITLE
node version

### ISSUE THREAD

**Issue by tejohnso** [electron/electron#5987]
What's the purpose of the .node-version [file](https://github.com/electron/electron/blob/master/.node-version)

It's indicating a version that is inconsistent from the changelog.

**Comment by danhp** [comment]
It used to be there so that http://electron.atom.io/ could simply check that file to determine what node version was used, but it's not relevant anymore.

**Comment by jlord** [comment]
FWIW the website uses [this JSON](https://github.com/electron/electron.atom.io/blob/gh-pages/script/versions#L7) to get the version information for the site.
