### ISSUE TITLE
Maximized frameless window causes Windows' auto-hide task bar to not show

### ISSUE THREAD

**Issue by wenkaili** [electron/electron#5990]
* Electron version: 37.8
* Operating system: Windows 10

I have my Windows 10 OS setup to auto-hide the taskbar. Now, if I maximized a frameless browser window, and I moved the mouse cursor to the bottom of the screen, the Windows taskbar doesn't slide up (and it should slide up). Is this an known issue?

Couple of other observations:
- This only happens on a frameless browser window. A framed browser window doesn't block the taskbar.
- This only happens when the browser window is maximized.
- This only happens when the browser window is the foreground app. If there's another app that is in the foreground, then taskbar will show up even if my frameless browser window is maximized.

**Comment by zcbenz** [comment]
Unfortunately this is a bug (or expected behavior) of Windows 10, you can reproduce by writing a native win32 program. I suggest reporting this to Microsoft's issues channel instead.

**Comment by wenkaili** [comment]
I was able to reproduce the issue on Windows 8 machine as well - do you know if it's been the same issue since then?

**Comment by zcbenz** [comment]
I can also reproduce on Windows 8, it is probably just an expected behavior of Windows.
