### ISSUE TITLE
Unknown Issue with IPC Renderer/WebFrame

### ISSUE THREAD

**Issue by Meadowcottage** [electron/electron#6000]
* Electron version: 1.2.2
* Operating system: Windows 10 x64

Using Webview ".executeJavascript" to execute some JQuery code and returns the error:
"Uncaught SyntaxError: missing ) after argument list"
 > "electron.ipcRenderer.on @ F:\Development\Web\Electron\Devrant.io\app\node_modules\electron-prebuilt\dist\resources\electron.asar\renderer\init.js"

Issue located here: https://github.com/electron/electron/blob/master/lib/renderer/init.js#L40

Any support would be appreciated. Not sure if my error or bug with Electron.
(Source file: https://github.com/Meadowcottage/Devrant.io/blob/master/app/index.html#L37,L38)

**Comment by MarshallOfSound** [comment]
It is your code.

See this line

```js
var add_Btn_iOS = "$('.menu-modal.modal-base > ul').append('<li><a target=_blank href=https://itunes.apple.com/us/app/apple-store/id1067512973?pt=117770459&ct=web_landing&mt=8><span class='icon-apple-logo1 icon'></span>Download for iOS</a></li>');";
```

Pay close attention to your use of quotes, you use single quotes to wrap your HTML to `$('HTML')` but then use single quotes inside your HTML to wrap attribute values.  You end up with something like this

```js
$('<a href='www.google.com'>Test</a>')
```

As you can probably see from syntax highlighting the first quote on the parameter closes the quote in the jquery function call.  You fix this by escaping the single quotes.

```js
$('<a href=\'www.google.com\'>Test</a>')

```

**Comment by Meadowcottage** [comment]
Ah okay, my error. Sorry. 
Thanks for the support.

**Comment by MarshallOfSound** [comment]
@Meadowcottage Not a problem, you should probably close this 👍

**Comment by Kulbear** [comment]
Hi,
I am meeting a similar problem.

```
import { ipcRenderer } from 'electron'

ipcRenderer.on('color-picker-reply', (event, arg) => {
  $("#colorpicker .body").colpickSetColor(arg)
})

const _ipcRenderer = ipcRenderer
const _isElectron = '0.5.0'
process.once('loaded', () => {
  global.ipcRenderer = _ipcRenderer
  global.isElectron = _isElectron
})

```

This is my preload script and after I start my application, there is an error log in my console.
    
    VM90:1 Uncaught SyntaxError: Invalid or unexpected token

And I clicked it, it shows

![image](https://cloud.githubusercontent.com/assets/14886380/24449054/bf054fb4-14a8-11e7-9554-90648e7d1edb.png)


Would you please help me to figure it out, I am confused why this happen...

**Comment by BeatriceThalo** [comment]
@Kulbear looks like you are missing quotes for your console.log argument. Thank you for pointing out that I could click on the VM error to see the incorrect js syntax it was attempting to execute!
