### ISSUE TITLE
electron not in process.versions

### ISSUE THREAD

**Issue by farfromrefug** [electron/electron#6001]
Recently i started having issues with my  native modules using ```node-pre-gyp```.
The issue was that node-pre-gyp was requiring the wrong binary.
After a lot of searching i figured out that there was no ```electron``` in my ```process.versions```.
```
{ 
http_parser: '2.7.0',
  node: '6.1.0',
  v8: '5.1.281.47',
  uv: '1.9.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '48',
  openssl: '1.0.2h' 
}
```
This happens while using electron-prebuilt, electron 1.2.1 / 1.2.2

Am doing something wrong

**Comment by zcbenz** [comment]
Generally if there is no `electron` in `process.versions` then the code is not ran in Electron's environment.  This happens when the script is ran in `child_process.fork`, or just Node.js.

**Comment by farfromrefug** [comment]
It s run using electron prebuilt
```
var electron = require('electron-prebuilt');
childProcess.spawn(electron, ['./' + PATHS.BUILD], {
        stdio: 'inherit',
        env: {
            NODE_ENV: 'development'
        }
    })
        .on('close', function () {
            // User closed the app. Kill the host process.
            process.exit();
        });
```
That's electron process, right?

**Comment by zcbenz** [comment]
The simplest way to verify is to run it without arguments, and see if the default app shows.

**Comment by farfromrefug** [comment]
yes it does

**Comment by zcbenz** [comment]
Can you provide a simple test script to show this problem?

**Comment by farfromrefug** [comment]
Actually it's not that easy to reproduce :s
Just package my app with electron-builder and i got an error telling me that node-pre-gyp was trying to load my binary for ```nodev48``` and not ```electron-v1.2```
```
Error: Cannot find module 'C:\Users\mguillon\dev\aryballe\script-tester\dist\win-unpacked\resources\app.asar\node_modules\aryballe-camera\lib\binding\Release\node-v48-win32-x64\aryballe_camera.node'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\mguillon\dev\aryballe\script-tester\dist\win-unpacked\resources\app.asar\node_modules\aryballe-camera\index.js:8:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```
Though i dont' really always see it :s
Still trying to make it easy to reproduce

**Comment by farfromrefug** [comment]
Actually i think i might have found the issue :s
I was spawning an electron process with ```ELECTRON_RUN_AS_NODE=1``` ....
I just removed it and it works

Sorry!
