### ISSUE TITLE
nwdisable nwfaketop ? 

### ISSUE THREAD

**Issue by kunkinkan** [electron/electron#6002]
Does electron have these or what is the alternative?

I have, in my HTML, an iframe, for nwjs it looked like this: 

`    <iframe id="server" src="about:blank" frameBorder="0" nwdisable nwfaketop></iframe>
`
What is the electron alternative?

**Comment by ClementNerma** [comment]
Have you found the solution for your problem ? I'm very interested too because I have the same problem...

**Comment by mnquintana** [comment]
You'll want to take a look at the [`<webview>` element](http://electron.atom.io/docs/api/web-view-tag/)

For future questions on writing apps, I suggest seeking help from [the community](https://github.com/electron/electron#community). The GitHub Issues list is only for bug reports and feature requests.

**Comment by ClementNerma** [comment]
But the `<webview>` element doesn't allow to access its HTML content...
