### ISSUE TITLE
DownloadItem.setSavePath() does not work on windows

### ISSUE THREAD

**Issue by kenan2002** [electron/electron#6009]
* Electron version: 1.2.2
* Operating system: Windows 10 64bit

I called DownloadItem.setSavePath() in the session 'will-download' callback but the save dialog still prompts and the path passed to setSavePath() affects nothing.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by kenan2002** [comment]
```html
<a href="data:text/plain,hello%20world" download="a.txt">click to download</a>
<script>
  const {remote} = require('electron');
  const {session} = remote.require('electron');

  session.defaultSession.on('will-download', (event, item, webContents) => {
    // This line *sometimes* doesn't work
    item.setSavePath('C:\\temp\\b.txt');
  });
</script>
```

This does not always trigger the bug. Try multiple times.

**Comment by kenan2002** [comment]
What I want to do is to call ```dialog.showSaveDialog()``` before setSavePath(), which will cause the app to prompt save dialog twice. I do this to achieve what #5877 should fix.

**Comment by kenan2002** [comment]
I think the default save dialog should prompt **after** the whole "will-download" callback ends to avoid this issue. Or the "will-download" event can be split into two events, say "before-download" and "will-download". In "before-download" we can set the save path and in "will-download" we do the rest. For example:
```
session.defaultSession.on('before-download', (event, item, webContents) => {
    item.setSavePath('C:\\temp\\b.txt');
});
session.defaultSession.on('will-download', (event, item, webContents) => {
    // other stuff...
});
```
In addition, with the "before-download" event, if the default dialog is cancelled or event.preventDefault() is called, the "will-download" should never trigger. This gives us a chance to prevent the download happen without calling item.isDestroyed().

**Comment by zcbenz** [comment]
You have to listen to the event in the main process if you want to call `setSavePath`. This API has to be called immediately when `will-download` event is emitted, while the event is sent to the renderer process asynchronously.

**Comment by vanowm** [comment]
> You have to listen to the event in the main process if you want to call `setSavePath`. This API has to be called immediately when `will-download` event is emitted, while the event is sent to the renderer process asynchronously.

I'm doing exactly that, however no download dialog shown, no file is saved and `item.getState()` returns "canceled".
If I remove `item.setSavePath('C:\\temp\\b.txt');` it shows the prompt.
Any ideas?

Windows 10
Electron v11.5.0
Chromium v87.0.4280.141
Node v12.18.3
v8 v8.7.220.31-electron.0
