### ISSUE TITLE
Documentation (Spanish)

### ISSUE THREAD

**Issue by matudelatower** [electron/electron#6011]
* Electron version: master
* Operating system: 

The code example in https://github.com/electron/electron/blob/master/docs-translations/es/tutorial/quick-start.md

Does not match with master version.

https://github.com/electron/electron/blob/master/docs-translations/es/tutorial/quick-start.md#escribe-tu-primera-aplicación-electron

index.html and main.js

**Comment by zcbenz** [comment]
The translated documentations are maintained by community so sometimes they are out of date, pull requests to update the translated documentations will be appreciated.
