### ISSUE TITLE
Pepper Flash works only in "npm start", not after building

### ISSUE THREAD

**Issue by effektsvk** [electron/electron#6014]
* Electron version: So far I've tried 1.2.0, 1.2.2 and 1.0.0   
* Operating system: Windows 7 64-bit   
Hello, I'm trying to put Pepper Flash from Chrome (version 21.0.0.242) to Electron. I'm creating Deezer player which requires Flash Player. I have this in my index.js:
`app.commandLine.appendSwitch('ppapi-flash-path', 'pepflashplayer.dll');
app.commandLine.appendSwitch('ppapi-flash-version', '21.0.0.242');`   
When I run my app from command prompt with `npm start` it works well.   
![](http://image.prntscr.com/image/bb5675d4b5c942a586f156066cc9a601.png)   
This is output:   
```
    C:\Users\Erik\deezer\deezer-client>npm start
    
    > deezer-client@1.0.0 start C:\Users\Erik\deezer\deezer-client
    > electron .
    
    
    NOT SANDBOXED
    Vector smash protection is enabled.
```   
When I build it using electron-packager-interactive it doesn't work. [Adobe](http://www.adobe.com/software/flash/about/) spits out "Couldn't load plugin." I tried out both 32 and 64 bit builds on versions mentioned at the beginning, nothing worked.    
![](http://image.prntscr.com/image/80a711a096694ac78c289186da1c8356.png)

**Comment by zcbenz** [comment]
You have to pass an absolute path to `ppapi-flash-path`, otherwise Electron will try to load it from current working directory, which can be anywhere.

**Comment by effektsvk** [comment]
Is this how you meant it?
`app.commandLine.appendSwitch('ppapi-flash-path', __dirname + '/pepflashplayer.dll');`
Because it doesn't work :disappointed:

**Comment by zcbenz** [comment]
On Windows the path delimiter has to be `\`.

**Comment by effektsvk** [comment]
`app.commandLine.appendSwitch('ppapi-flash-path', __dirname + '\\pepflashplayer.dll');
app.commandLine.appendSwitch('ppapi-flash-version', '21.0.0.242');` worked! Thank you so much, I was so angry at this :smile: By the way in the end I used 64 bit build even though my .dll file was in Program Files (x86). Thank you again! :heart:

**Comment by SerikITSTEP** [comment]
Sorry i'm beginner in electron and nodejs. How you install paper flash plugin to your project?  npm.........?

**Comment by effektsvk** [comment]
Check out this https://github.com/effektsvk/deezer-client/blob/master/index.js

**Comment by effektsvk** [comment]
Unfortunately, the Deezer player didn't work for some reason, it still threw an error that I'm missing flash player but Adobe site was okay with it so maybe for your project it will work. Good luck.
