### ISSUE TITLE
linux设置icon无效

### ISSUE THREAD

**Issue by strongant** [electron/electron#6020]
* Electron version:1.1.1
* Operating system:ubuntu
var iconPath = __dirname + '/app/assets/img/appledisk.png';

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 1000,
    icon: iconPath
  });

  mainWindow.loadURL(`file://${__dirname}/app/index.html`);

  mainWindow.webContents.openDevTools();

  mainWindow.on('closed', function() {
    mainWindow = null;
  });
}

app.on('ready', createWindow);

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', function() {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow();
  }
});

为什么启动后没有图标？

**Comment by zcbenz** [comment]
On Linux you have to provide a [`.desktop`](https://wiki.archlinux.org/index.php/Desktop_entries) for your app to make the desktop environment show the icon, the `icon` option is just a hint and many desktop environments just ignore it.

**Comment by strongant** [comment]
thank you,let me try.
