### ISSUE TITLE
Does session.webRequest support custom protocols?

### ISSUE THREAD

**Issue by pfraze** [electron/electron#6021]
* Electron version: 1.2.0
* Operating system: OSX 10.11.4

I need to use [session.webRequest](http://electron.atom.io/docs/api/session/#seswebrequest) to intercept requests to a custom protocol, so I can modify some behaviors. But, the request seems to be triggering for http/s, but not my protocol (which is a buffer protocol handler). Is that expected? Can I get the interceptor to work?

**Comment by zcbenz** [comment]
I can verify webRequest only works for http/s, but for now I'm not sure whether it is a limitation of Chromium's network stack, or a bug of Electron.

**Comment by deepak1556** [comment]
The lifecycle events `beforeStart`, `responseStarted`, `redirect`, `Completed` are emitted, only those events related to HTTP headers are not.

**Comment by pfraze** [comment]
Confirmed that `onBeforeRequest` fires, which should give me what I need (redirects). It might still be handy to modify headers? But I dont have a pressing need for that atm, so I'm good to close.

**Comment by zcbenz** [comment]
Thanks @deepak1556 for looking into it, I'm closing this now.
