### ISSUE TITLE
make electron run form portable flash drive

### ISSUE THREAD

**Issue by brody182** [electron/electron#6028]
* Electron version: 1.x

* Operating system:MacOS

is there a function to make electron framework run from a portable flash drive?

**Comment by kevinsawicki** [comment]
You can use `app.setPath` API to control where Electron writes files, http://electron.atom.io/docs/api/app/#appsetpathname-path

What specific issues or problems are you seeing with running electron from a portable drive?

**Comment by kevinsawicki** [comment]
Closing this out for now, please comment with more details and an minimal example app that reproduces the issues, thanks.
