### ISSUE TITLE
Enable shared library/debug builds of libchromiumcontent locally

### ISSUE THREAD

**Issue by tomotvos** [electron/electron#6031]
- Electron version: 1.2.2
- Operating system: Windows

While we can now trigger a build of libchromiumcontent as a part of a larger Electron build, there is no way to make that build include debug symbols. Since the point of building locally is, presumably, to include local changes, debugging seems an essential step. It also facilitates changes to Electron that are affected by libchromiumcontent, and stepping through that code is greatly beneficial to figuring those things out.

**Comment by tomotvos** [comment]
Using the --build_libchromiumcontent switch on bootstrap.py does, in fact, generate PDB files that can be used for debugging, although linking is extremely slow because static libraries are being generated. Shared library builds fail (#6065), but I think it is still useful to have a debug version of libcc to avoid having to deal with code optimizations during debugging.

**Comment by tomotvos** [comment]
Note that #6065 was Closed due to merging with this ticket, but the comments have not come over. That ticket reports an error when the "shared_library" build of chromium is triggered, not necessarily a debug build.

**Comment by codebytere** [comment]
This is actually now possible on `master`, since we build with GN and thus everything is built in debug mode. I'm going to close this in that event, but you can take a look at [current build instructions](https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md) for how you can go about this.
