### ISSUE TITLE
Poor rendering performance since Electron 1.1.x (Windows)

### ISSUE THREAD

**Issue by mikecao** [electron/electron#6032]
* Electron version:1.2.2
* Operating system:Windows 7 x64
* CPU: i7 3770K
* GPU: GTX 770

I've been experiencing very poor rendering performance since upgrading to Electron 1.1+. Running on 1.0, I would get a consistent 60 fps. But with 1.1+ there is an excessive amount of jank. In the below screenshot, I am running the exact same codebase in two windows. The left window is running 1.0.2 and right window is running 1.2.2. But the issue occurs with anything above 1.0.

![jank](https://cloud.githubusercontent.com/assets/477975/16023082/e442f456-316f-11e6-90be-27cb24358aad.png)

Using Chrome's timeline tool, I can see that my code is completing well with the frame length and the CPU is spending 75% of the frame time idle. Since release 1.1 introduced Chrome 50 and 1.2 introduced Chrome 51, I suspect it's Chromium related but I am not sure. Unfortunately my app can't run in a regular browser window because of all the node dependencies. I have tried paring down the code to a simple render loop that does nothing and still the issue occurs. Note that this seems to only occur on Windows. I've tried the same code on OSX with release 1.2.2 and it ran fine at 60 fps.

I also see this error in the console if I leave the app running for a while:

```
[14232:0613/122257:ERROR:gles2_cmd_decoder.cc(14683)] [.CommandBufferContext.DisplayCompositor-00000000030DCD10]GL ERROR :GL_I
NVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[14232:0613/122257:ERROR:gles2_cmd_decoder.cc(7857)] [.CommandBufferContext.DisplayCompositor-00000000030DCD10]RENDER WARNING:
 texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

**Comment by paulcbetts** [comment]
Can you open `chrome://gpu` on both and see if there are differences?

**Comment by mikecao** [comment]
In 1.0.2, there is a table for *GpuMemoryBuffer Status* with the following:
```
ATC	Software only
ATCIA	Software only
DXT1	Software only
DXT5	Software only
ETC1	Software only
R_8	Software only
RGBA_4444	Software only
RGBX_8888	Software only
RGBA_8888	Software only
BGRX_8888	Software only
BGRA_8888	Software only
YUV_420	Software only
YUV_420_BIPLANAR	Software only
UYVY_422	Software only
```
In 1.2.2, there is no table and this entry under *Graphics Feature Status*:

```
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
```

Also under *Problems Detected*, there are two additional entries:

```
Native GpuMemoryBuffers have been disabled, either via about:flags or command line.
Disabled Features: native_gpu_memory_buffers
```

and

```
Direct composition flashes black initially on Win <10: 588588
Applied Workarounds: disable_direct_composition
```

**Comment by zcbenz** [comment]
Can you try setting a non-transparent `backgroundColor` for `BrowserWindow` and see if there is any difference?

**Comment by marwanhilmi** [comment]
This is probably not very helpful but I suspect there are significant changes to how hardware acceleration is handled in Chromium 50+ on Windows. I had significant issues getting hardware acceleration to even work on Windows until I reformatted my system and reverted to an older ATI driver. Have you tried updating your drivers?

See https://github.com/electron/electron/issues/5998

**Comment by mikecao** [comment]
@marwanhilmi Yes, I'm using the latest drivers from Nvidia.

@zcbenz My app has always had a solid `backgroundColor` so that's not the issue. I've also tried running with frame/frameless, using a bunch of gpu related command line switches, and tweaking the code. All had no effect.

I am pretty sure it's related to the Chromium update. The problem is I can't pinpoint exactly what the issue is. I'm trying to put together a barebones example that mimics what my app is doing, but so far it seems to run fine. The issue is only with my app and only on Windows. Very frustrating. I'll keep digging and see what I can find.

**Comment by jakubzitny** [comment]
Hi, we're having similar problems. We've updated Electron to `1.2`, everything works great on OSX and even on Linux, but Windows is terribly slow. We'll try to build 64-bit version on Windows and see if it helps.

We'll keep digging as well, worst case we downgrade to older Electron.

**Comment by mikecao** [comment]
Ok, I figured out the issue. In my case I had a div that used CSS animations to serve as a loading indicator. It also used `::before` and `::after` psuedo-elements for styling. Despite setting the style for the div to `display: none` until it was needed, Chrome continued to process the CSS animations for the psuedo-elements causing the lag. As soon as I removed the element, performance went back to 60 fps.

**Comment by zcbenz** [comment]
@mikecao Looks like a Chromium bug, can you report it to [Chromium's issues list](https://crbug.com)?

**Comment by mikecao** [comment]
I was mistaken about one thing. Instead of `display: none` I was actually using `visibility: hidden` and that was causing Chrome to continue animating the element despite it being hidden. But it seems to definitely be a Chrome issue with animating the element itself. It runs poorly in Chrome 50+.

I've created a test page here, https://gist.github.com/mikecao/a2999c6c3a1fd4df6e4f8b7012bd08e0

And a live demo here, https://jsfiddle.net/qa7htbdg/

I'd be great if someone else could verify the issue before I submit a bug to Chromium.

**Comment by tejohnso** [comment]
@mikecao The FPS indicator is more costly than the spinner.
With FPS indicator I get two chrome processes at about 3.5% cpu each.  And removing the spinner barely changes anything.
Without FPS indicator (remove render function) I get two processes at about 1.5% each.  And removing the spinner drops them off completely.

In either case, I'd say it's not running poorly.  
Chromium 51.0.2704.84 (Developer Build) (64-bit)

**Comment by mikecao** [comment]
@tejohnso Thanks for testing it out. The issue however is not with the cpu, but with dropped frames. The FPS display is just to show that it's not running at a consistent 60 FPS. If you run a timeline capture in the devtools you should see something like this:

![image](https://cloud.githubusercontent.com/assets/477975/16239037/f1bb3c78-3797-11e6-84f3-eec5fbf8e907.png)

All the red squares are long running frames (jank) causing it to drop below 60 FPS. If you look at the summary you can see that all the scripting, rendering, and painting combined is a tiny portion of the entire time, yet there are frame drops.

![image](https://cloud.githubusercontent.com/assets/477975/16239201/a9cf5088-3798-11e6-88a9-09fba77e8086.png)

Once you remove the spinner completely, the timeline looks like this:

![image](https://cloud.githubusercontent.com/assets/477975/16239290/03979c2e-3799-11e6-83d9-4b1eee5b7bd1.png)

And the summary looks similar to the previous one:

![image](https://cloud.githubusercontent.com/assets/477975/16239324/2bc25266-3799-11e6-8f37-466851cbb66f.png)

If you run the same example in Chrome 49 (Electron 1.0), it runs smoothly as well. I'm trying to see if this issue is present on other Windows builds or if it's just my system. But at least now I can consistently reproduce it.

**Comment by tejohnso** [comment]
![jank](https://cloud.githubusercontent.com/assets/1511535/16241192/98797594-37ba-11e6-8f18-3a08e61a566e.png)

I'm not getting that kind of jank - with or without the fps indicator.

**Comment by mikecao** [comment]
@tejohnso Thanks for confirming. It's strange though. I just tested on another machine, Windows 10, different GPU and it had the same problems, so I'm not sure what to make of it.

**Comment by zcbenz** [comment]
I'm closing this because this seems to be an issue of Chromium's rendering, and since Electron is using Chromium's rendering code directly, we are not able to fix this on Electron's side.
