### ISSUE TITLE
Some window operations not working when window is in fullscreen state

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#6033]
- Electron version: 1.2.2
- Operating system: OS X 10.11.5

Make a `BrowserWindow`.
Override its `close` event handler to hide the window and cancel the close event.
After the window is shown, set it to full-screen.
`Cmd-W` or `Window > Close` if you have a menu item with the close selector.

Expected: the window would be hidden.
Actual: a black screen is rendered instead.

Video: http://cl.ly/182Z2Z1L3C1c

**Comment by kevinsawicki** [comment]
@CharlieHess would you expect it to leave fullscreen mode when the window was hidden? Similar to how when you close a window in a full screen app?

**Comment by CharlieHess** [comment]
@kevinsawicki yeah, that makes sense (tried some other apps and they exhibit the same behavior).

**Comment by liusy182** [comment]
In Mac, if an app is in full screen, the 'hide' function is disabled by default (take Finder for example). 'hide' is available ONLY after the app exits full screen. To me, client code should honour this behaviour by not calling "hide()" when the app is in full screen.

**Comment by wenkaili** [comment]
I'm running into a similar issue where calling hide in fullscreen mode renders a black screen. I tried calling setFullScreen(false) right after the hide call, but the setFullScreen call causes the window to be shown again. Is there a way to mimic the "close and leave full screen" behavior, similar to other mac apps, but have it "hide and leave full screen" instead?

**Comment by smithalan92** [comment]
@wenkaili , One way to work around this is to listen for the `leave-full-screen` event once before calling `setFullScreen(false);` and when that event is triggered then hiding the Window. See example code

``` javascript
window.on('close', function (e) {
	e.preventDefault();
	if(window.isFullScreen()){
		window.once('leave-full-screen', function () {
			window.hide();
		})
		window.setFullScreen(false);
	}
	else{
		window.hide();
	}
});
    
```

**Comment by codebytere** [comment]
closing due to abandonment.
