### ISSUE TITLE
Starting in fullscreen then toggling to windowed mode results in black screen (1.2.x)

### ISSUE THREAD

**Issue by marwanhilmi** [electron/electron#6036]
- Electron version: 1.2.0, 1.2.1, 1.2.2
- Operating system: Windows

If you start an browser window in fullscreen and then attempt to toggle to windowed mode, the window will just black out and become unresponsive. Attempting to toggle back again still results in a black screen.

However, if you start the window in windowed mode and then toggle to fullscreen, it works as expected.

This maybe related to the fixes made to the fullscreen API in 1.2.x. It only occurs on Windows. It does not happen on 1.1.3.

You can reproduce easily with the `electron-api-demos` application and 1.2.2.
https://github.com/electron/electron-api-demos

Update `window-options` to set `fullscreen: true`
https://github.com/electron/electron-api-demos/blob/master/main.js#L22

```
var windowOptions = {
      width: 1080,
      minWidth: 680,
      height: 840,
      title: app.getName(),
      fullscreen: true
    }
```

Start the application and hit F11 to switch to windowed mode and you'll get a black screen.

**Comment by jeremyrajan** [comment]
This is pretty much happening for us as well. With a windowed application if we minimise it to task-bar and then click the icon, results in the black screen. Once we alt-tab it, works fine. 

Electron: 1.2.5
OS: Windows

**Comment by CharlieHess** [comment]
Probably the same as #6033?

**Comment by kevinsawicki** [comment]
> Probably the same as #6033?

I don't think so, this issue is only reproducible on Windows and the window becomes unusable.

**Comment by HUN73R13** [comment]
@kevinsawicki thanks you and sorry about the duplicate.
to narrow down the bug, it seem to occur when fullscreen is called before the window is shown, as I mentioned I was able to start in full screen if I set it to true after `win.show()`

**Comment by greggman** [comment]
This is happening for me as well in 1.4.5

**Comment by greggman** [comment]
BTW: I wasn't calling `win.setFullScreen(true)` I was just setting passing in `{fullscreen: true}` as an option to `new BrowserWindow`

My workaround ATM is to instead pass on `{fullscreenable: true}` and then use something like

```
  webContents.on('dom-ready', () => {
      window.setFullScreen(true);
  });
```

Note that if I don't pass in `{fullscreenable: true}` then `window.setFullScreen(true)` has no effect even though the docs say `{fullscreenable: true}` is the default

**Comment by jeremyrajan** [comment]
I didn't try this one. Will give it a shot and see if helps us :)

Thank you 👍

**Comment by HUN73R13** [comment]
to confirm, my issue was fixed with 1.4.10 update. 
setting full screen while creating the window works as expected now.
if it fixed your issues we can close this issue.

**Comment by George35mk** [comment]
can i have fullscreen window but with frame enable i want on the launch of the app to be  full but the frame is missing why

**Comment by MaherFa** [comment]
@George35mk you mean maximize?

**Comment by KoenLav** [comment]
Same issue here.

I can confirm that setting the window to fullscreen after the domready event solves the issue. For meteor-desktop as follows:

        eventsBus.on('windowCreated', (window) => {
            window.webContents.on('dom-ready', () => {
              window.setFullScreen(true);
            });
        });

**Comment by dharders** [comment]
I just submitted PR #9645 that hopefully fixes this issue. After it's merged you won't need any of the above workarounds and can just use `{ fullscreen: true }` and avoid the two step startup animation of normal->fullscreen. It should just render straight to fullscreen.

FYI: The `WS_VISIBLE` flag wasn't being set for the `GWL_STYLE`, thus the window couldn't receive any OS events and thus appeared unresponsive.

**Comment by dharders** [comment]
Fix: upgrade your electron dependency, fix now released in `"electron": "1.7.4 beta"`

**Comment by lishoulong** [comment]
Hi, @dharders , I also encounter this same question, the version of electron is 2.0.10.

I have two browserWindows, jump from A browserWindow to B browserWindow.  Full screen the B browserWindow, and then click the x icon(close B window), my logic is to hide the B browserWindow, and show A browserWindow.

But at this time, I find the B BrowserWindow is black, and the A browserWindow shows normal.

Looking for your help!

**Comment by lishoulong** [comment]
I solved this question using isFullScreen method, mentioned in this issue https://github.com/electron/electron/issues/6033.

**Comment by meetDeveloper** [comment]
If I construct a browser window with window options as,
```
var windowOptions = {
      width: 1080,
      minWidth: 680,
      height: 840,
      title: app.getName(),
      show: false
      fullscreen: true
    }
```
and then do window.show(), window does not go to full screen mode. @dharders
