### ISSUE TITLE
Electron takes a long time to exit after showing an openFile dialog

### ISSUE THREAD

**Issue by HitomiTenshi** [electron/electron#6040]
* Electron version: 1.2.2
* Operating system: Windows 10 x64

Triggering the openFile dialog only once and closing electron after that will cause electron to still be active in the background for about one minute, sometimes even longer, before it finally exits.

Triggering the openFile dialog twice (or more times) won't make electron hang after closing the main window.

**How to reproduce:**

- Start your electron app
- Open the openFile dialog, make sure to select a file and press "Open". (Pressing "Cancel" in the dialog won't trigger the bug)
- Close the main electron window by pressing the X on the top right corner.
- Watch electron still being open in the background for a minute or so

**Renderer Thread:**

```
$('#browse-button').click(function () {
    ipcRenderer.send('dialog');
});

ipcRenderer.on('dialog-reply', function (event, selection) {
    if (selection) {
        $('#location-input').val(selection);
    }
});
```

**Main Thread:**

```
ipcMain.on('dialog', function (event) {
    if (mainWindow != null) {
        dialog.showOpenDialog(
            mainWindow,
            {
                title: 'Import',
                filters: [
                    { name: 'Media', extensions: ['import'] }
                ],
                properties: ['openFile']
            },
            function (selection) {
                event.sender.send('dialog-reply', selection);
            }
        );
    }
});
```

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem? I put the code into an empty app but could not reproduce, I probably missed something.

**Comment by HitomiTenshi** [comment]
I found the culprit. It happens when you define one `filter` with only one extension in the `extensions` array.

Here's a minimal example.
[app.zip](https://github.com/electron/electron/files/315612/app.zip)

**How to trigger the bug:**

- npm install first
- > npm start
- click browse, select some file, the package.json in the same folder would be the quickest choice
- press open, textbox gets filled
- close electron now by pressing the X button on the top left corner
- look at your cmd.exe / taskmanager, electron should still be running

**Comment by HitomiTenshi** [comment]
I made a quick recording

[electron.zip](https://github.com/electron/electron/files/315642/electron.zip)
There's a mp4 inside this zip that shows my struggle. I can't end the electron.exe task once it starts hanging. Access denied.

**Comment by zcbenz** [comment]
I'm unable to reproduce on both Windows 10 and Windows 8.1, can you install [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) and inspect electron.exe to see what it is doing?

Steps:

<img width="284" alt="screen shot 2016-06-16 at 1 07 33 pm" src="https://cloud.githubusercontent.com/assets/639601/16105217/609c3c92-33c3-11e6-8ebd-6550e1e3ed96.png">

<img width="527" alt="screen shot 2016-06-16 at 1 07 47 pm" src="https://cloud.githubusercontent.com/assets/639601/16105222/63659e28-33c3-11e6-81c6-11f4bdf1cf75.png">

<img width="815" alt="screen shot 2016-06-16 at 1 07 57 pm" src="https://cloud.githubusercontent.com/assets/639601/16105224/64c7976c-33c3-11e6-9e25-bd8fe0b0717b.png">

**Comment by HitomiTenshi** [comment]
I just updated to `Electron 1.2.3` and the bug disappeared. I think my problem was somewhat related to #4261 even though I didn't open devtools. Not sure though, it's fixed now. Thanks for helping me out! 👍
