### ISSUE TITLE
mousemove event fires when touchscreen connected

### ISSUE THREAD

**Issue by krokofant** [electron/electron#6041]
* Electron version: 0.36.11
* Operating system: Windows 7

Using this to track activity (jQuery included)
```
        $(window).on("mousemove", resetIdle);
        $(window).on("touchstart", resetIdle);
        $(window).on("touchmove", resetIdle);
```

The mousemove event is constantly fired when:
* The mouse is pointer is placed over the window
* The touch screen is connected

Notable:
* The problem occurs without an external mouse connected
* The touchstart/touchmove events does not trigger

**Comment by zcbenz** [comment]
Does it happen for latest versions like v1.2.2? And does it happen in Chrome browser?

**Comment by krokofant** [comment]
It did not happen in a recent Chrome browser when I tested. I'll try to find another screen to test this on otherwise the next test will be in august.

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by krokofant** [comment]
Could not reproduce on latest Electron.
