### ISSUE TITLE
Detect os platform version x64 vs. ia32 [Linux, Win]

### ISSUE THREAD

**Issue by vojtatranta** [electron/electron#6044]
Hi and thank you,
we were releasing our product just as 32bits version. Now we want to ship x64 too.

We want to notify users with x64 capable computer that they should rather use x64 app.
However, it seems it is really complicated to detect PC architecture in Electron.
Since `require('os').arch()` cares about node version we have no other way to reliably determine whether user's computer is x64 capable or not, because Electron runs it's own nodejs. So on x64 capable machine I get from `require('os').arch() -> //ia32`, because Electron runs 32bits nodejs (build is done with 32bits, we would like to notify user that x64 is available).

Is there any way how can I detect it? Something like:
`const arch = require('electron').arch()`?

Thanks

**Comment by MarshallOfSound** [comment]
Windows you can do

```js
process.env.PROCESSOR_ARCHITECTURE
```

That will return `AMD64` on x64 systems.


As for linux, I think `os.arch()` returns the correct values

**Comment by vojtatranta** [comment]
@MarshallOfSound yea I noticed that `PROCESSOR_ARCHITECTURE` returns something useful.
But I was not sure whether it is really credible. If you say so :)

**Comment by zcbenz** [comment]
It is a bug of Node that `os.arch()` returns wrong value: https://github.com/nodejs/node-v0.x-archive/issues/2862.

To work around this, you can use the [node-uname]() module (or any module calls `uname`) on POSIX systems, and the `PROCESSOR_ARCHITECTURE` environment variable on Windows.

**Comment by Topppy** [comment]
> It is a bug of Node that `os.arch()` returns wrong value: [nodejs/node-v0.x-archive#2862](https://github.com/nodejs/node-v0.x-archive/issues/2862).
> 
> To work around this, you can use the node-uname module (or any module calls `uname`) on POSIX systems, and the `PROCESSOR_ARCHITECTURE` environment variable on Windows.

PROCESSOR_ARCHITECTURE  still got 'x86'  on x64 windows 。Our Electron build is done with 32bits. 

Is there any way to detect x64 system when running x32 Electron?

Thanks
