### ISSUE TITLE
Unable to use --build_libchromiumcontent switch in bootstrap.py

### ISSUE THREAD

**Issue by tomotvos** [electron/electron#6045]
* Electron version: 1.2.2
* Operating system: Windows 10

When attempting to build libchromiumcontent locally using the --build_libchromiumcontent switch on bootstrap.py, the following error is thrown:

```
P:\electron\script\build-libchromiumcontent.py -v --target_arch x64
Traceback (most recent call last):
  File "script\bootstrap.py", line 262, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 45, in main
    build_libchromiumcontent(args.verbose, args.target_arch, defines)
  File "script\bootstrap.py", line 204, in build_libchromiumcontent
    execute_stdout(args + ['--target_arch', target_arch])
  File "P:\electron\script\lib\util.py", line 174, in execute_stdout
    subprocess.check_call(argv, env=env)
  File "F:\Python27\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "F:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "F:\Python27\lib\subprocess.py", line 710, in __init__
    errread, err write
  File "F:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

```
I have Python 2.7 installed, and this error shows up regardless of whether I trigger bootstrap.py from the VS 2015 Command Shell, the normal Windows command shell, or the Git Bash shell.

I can execute the build-libchromiumcontent.py command directly and it executes without the same error, so it appears to be tied to the way bootstrap.py is calling build-libchromiumcontent.py. My initiating command line is:

`P:\electron>python script\bootstrap.py --build_libchromiumcontent -v`

**Comment by kevinsawicki** [comment]
@tomotvos does it work if you omit the `-v` option?

**Comment by tomotvos** [comment]
I am in the middle of a very long build that I triggered manually, so I cannot check, but I see you made a change. I will test the ```-v``` and your change (which looks more likely) when the build is done.

**Comment by tomotvos** [comment]
I can confirm that removing ```-v``` did not fix the issue, but your one-line change to the build script did. Thank you! Now if I can just convince someone to allow me to get a component and/or debug build to be invokable without hacking build scripts.
