### ISSUE TITLE
Sending mouse events with webContents.sendInputEvent

### ISSUE THREAD

**Issue by kalharbi** [electron/electron#6047]
* Electron version: 1.0.1
* Operating system: OS X 10.10.5

Not sure why sending mouse events with [webContents.sendInputEvent](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentssendinputeventevent) is not working.
In the main process, I have:

```javascript
mainWindow.webContents.sendInputEvent(
    {type: 'mouseMove' x: 10, y: 10});
mainWindow.webContents.sendInputEvent(
     {type: 'mouseDown', x: 10, y: 10, button: 'left', clickCount: 1});
mainWindow.webContents.sendInputEvent(
     {type: 'mouseUp', x: 10, y:10, button: 'left', clickCount: 1});
```
I've tried passing the event object with all possible properties but could not get it to work.

**Comment by zcbenz** [comment]
The simply way to verify whether it works is to catch all mouse events, for example:

```javascript
document.onmousemove = (event) => { console.log(event) }
remote.getCurrentWebContents().sendInputEvent({type: 'mouseMove', x: 10, y: 10})
```

However for emulating certain actions you have to carefully construct every event in sequence, in your case you probably missed some necessary events.

Also there is no documentation on how to make certain actions work though, the `sendInputEvent` is only a simple wrapper around Chromium's interface, there is no guarantee on how the behavior should be.

**Comment by kalharbi** [comment]
Thanks for the example! I used it and it does log the mouse event but the mouse cursor is not moving in the client window. I'm testing mouseMove at the moment and the cursor is not moving locally nor globally.
It's probably worth adding a note to the docs regarding the unpredictable behavior of `sendInputEvent `.

**Comment by datdinhquoc** [comment]
I find the x,y properties in event object hard to use, any work-around for just current mouse cursor location? For example just to click there?
