### ISSUE TITLE
Add dialog.showMessageBox checkbox option

### ISSUE THREAD

**Issue by coreybutler** [electron/electron#6048]
- Electron version: 1+
- Operating system: All

I'd love to see support for a checkbox with a custom label within message box. In my app, users can delete items from a menu. I want to warn them they're deleting an item. After a little bit of use, this can get obnoxious, so I'd like to have a checkbox labeled "Don't show this again."

**Comment by atdrago** [comment]
@coreybutler I understand you're requesting a feature, and you've probably thought of this, but you could just create your own "dialog" from a `BrowserWindow` that has a checkbox, rather than using the built-in `dialog.showMessageBox` :)

**Comment by coreybutler** [comment]
@atdrago Sure have. I'm really trying to leverage native message boxes. Luckily, I have a great data management library with rollback support, so my current solution is actually to just delete the item and give the user a notification to "undo" it in the case of a mistaken removal. That may, ultimately, be a better workflow anyway... but I would still love to have a checkbox option since I think this is still applicable in many other scenarios.
