### ISSUE TITLE
Passing the same callback to main process for multiple times will make the callback stop working after the remote callback gets GCed in main process

### ISSUE THREAD

**Issue by mgparrish** [electron/electron#6050]
* Electron version: 1.2.1+ possibly 1.0+
* Operating system:Windows 10 - others?

nativeImage now has possible bug. When using "electron-canvas-to-buffer" it was working 100% reliable in Electron 0.37.2. 
It is broken now in Electron 1.2.1 +, possibly in Electron 1.0 + 

https://github.com/mattdesl/electron-canvas-to-buffer

This module is fairly simple but very convenient and makes use of Electrons built in nativeImage.

Details:

1. After a few series of changing Canvas elements and saving the canvas the file is no longer saved. When the file is not written,  However the file dialog is presented, and it appears that the file is saved, But it doesn't really save the file.

2. Happens saving either .jpg or .png.

3. May save OK a few times, eventually it will fail.

4. Once it fails it will not ever save canvas again until app is restarted again.

5. Tested many many canvas edits and files saves, never fails in Electron 0.37.2 Rock Solid.

6. I am using fabric.js for canvas manipulation.

7.The initial canvas save to file always works.

8.When the file save fails there is no error generated. The app does not generate an error when the write fails, But it does not generate a "Write of',filePath,'was successful' in the console during the failure. So lack of "success" is the actual error indication. See the saveCallback function in "canvastest.js" in the zip files or as below. "throw err" doesn't present itself when the file doesn't write.

function saveTheFile(){
dialog.showSaveDialog({title:'Testing a save dialog',defaultPath:'image.png'},saveCallback);
}

function saveCallback(filePath){
// as a buffer
var buffer = canvasBuffer(canvas, 'image/png')
// write canvas to file
fs.writeFile(filePath, buffer, function (err) {
//throw err
if(err)throw err;else console.log('Write of',filePath,'was successful');
})

9.Using Windows 10 x64, Windows 32 bit version of Electron

You can test good (made on Electron 0.37.2) vs. bad (made on Electron 1.2.1) app. Zip files are too big to attach here. I have it on my website. Just load a photo on the canvas and save. Both apps are the same code, just made minor changes to allow the new version 1.2.1 Electron to work, for example removing "dashes" in require statements, as you had to do in electron-canvas-to-buffer V 2.0.

Apps can be launched just click "Electron.exe" in root of the zip file.

Using Electron V 0.37.2
http://www.mgparrish.com/FabricSaveCanvasGood.zip

Using Electron V 1.21
http://www.mgparrish.com/FabricSaveCanvasBug.zip

**Comment by zcbenz** [comment]
Can you add a `console.log` call in the callback to see whether the callback is executed at all?

**Comment by mgparrish** [comment]
Thanks. I added the callback as you can see below. I updated the zip file "FabricSaveCanvasBug.zip in the link above as well.

When the error occurs the function "saveCallback(filePath) is not executed. When the file is written successfully the console log indicates "Callback Executed".

function saveTheFile(){
dialog.showSaveDialog({title:'Testing a save dialog',defaultPath:'image.png'},saveCallback);
}

function saveCallback(filePath){

 
// as a buffer
var buffer = canvasBuffer(canvas, 'image/png')
console.log('Callback Executed'); //mgp added 
// write canvas to file
fs.writeFile(filePath, buffer, function (err) {
 //throw err
 if(err)throw err;else console.log('Write of',filePath,'was successful');
})



}

**Comment by zcbenz** [comment]
This turns out to be a bug of the `remote` object, thanks for providing the test case.
