### ISSUE TITLE
Stop Debugger On First Line of BrowserWindow Code

### ISSUE THREAD

**Issue by francoislaberge** [electron/electron#6051]
* Electron version:
v0.37.4
* Operating system:
OSX 10.11.1 (El Capitain)

Is there a way to force a BrowserWindow debugger to pause the debugger on the first line of an BrowserWindow's include scripts?

**Comment by zcbenz** [comment]
I'm afraid not, if you want to open devtools, you have to have a page opened, but since the page is opened, you will not be able to catch the debugger call. That's the design of Chrome devtools.

The common solution is to open devtools and then refresh the page.
