### ISSUE TITLE
build project for target arch arm

### ISSUE THREAD

**Issue by miladsajjadi** [electron/electron#6055]
I am beginner in electron packager. i want to build my project for target arch arm v7. what should i do?
running this:
> electron-packager . MYPROJECT --platform=linux --arch=armhf --overwrite --prune
will cause in:
Unsupported arch armhf; must be one of: ia32, x64

my host machine is windows. does electron packager add support for arm build?

**Comment by MarshallOfSound** [comment]
Electron packager issues should be raised at their repository (electron-packager is not maintained by the electron team)

You can track arm support in electron-packager with

https://github.com/electron-userland/electron-packager/issues/106

**Comment by miladsajjadi** [comment]
ok, thats right.
but is there any way so as i can build my project for arm architecture (regardless of electron-packager)?

**Comment by MarshallOfSound** [comment]
@miladsajjadi I'm not sure what you mean, there are pre-built electron arm builds in the releases section?

https://github.com/electron/electron/releases

**Comment by miladsajjadi** [comment]
@MarshallOfSound i'm just wanted to run my compiled application on raspberry pi. 
my host machine is windows 10. i can package and distribute my Electron app for windows and linux. but i need to get executable version of my project for raspberry pi (which has arm v7)
is there any way to build my app for arm arch target?

**Comment by zcbenz** [comment]
Closing since it is not an issue of Electron itself.

**Comment by develar** [comment]
Not clear for me why it is not Electron issue. `armv7l` build of electron is provided, but `armhf` doesn't. So, we got error "package architecture (armv7l) does not match system (armhf)" https://github.com/electron-userland/electron-builder/issues/1230

**Comment by MarshallOfSound** [comment]
@develar For increased ARM support I believe it is being tracked over at #5706
