### ISSUE TITLE
Getting Render Process Gone  error when tried to bundle my app as electron app

### ISSUE THREAD

**Issue by mageshb** [electron/electron#6060]
* Electron version: 1.2.2
* Operating system: Ubuntu 12.04

I'm trying to bundle JS app developed using GHCJS as electron application.

Here is source of app that reproduces the error
https://db.tt/apH28NHQ

Am I missing something here? Or is this is a bug?

**Comment by zcbenz** [comment]
This is because your app is calling `process.exit`.
