### ISSUE TITLE
The Update Framework

### ISSUE THREAD

**Issue by kunkinkan** [electron/electron#6062]
Would be nice if electron auto-update would follow "The Update Framework" specification as it is much more secure than what is used now. 

`In order to securely download and verify target files, TUF requires a few extra files to exist on a repository. These are called metadata files. TUF metadata files contain additional information, including information about which keys are trusted, the cryptographic hashes of files, signatures on the metadata, metadata version numbers, and the date after which the metadata should be considered expired.
`

https://theupdateframework.github.io/
https://github.com/theupdateframework/tuf
https://github.com/theupdateframework/tuf/blob/develop/SECURITY.md
https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt

**Comment by felicienfrancois** [comment]
Electron update framework is based on [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac) and [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows).
You should also post an issue in thoose projects.

Then, for the creation and host of the TUF additional files, you may also post an issue on each [Electron build tools and update servers](https://github.com/sindresorhus/awesome-electron#tools)

**Comment by zcbenz** [comment]
Thanks @felicienfrancois for answering it, I'm closing this issue now.
