### ISSUE TITLE
Multi-window apps, performance and "forked windows"

### ISSUE THREAD

**Issue by davej** [electron/electron#6063]
**This is intended as a discussion thread, feel free to close this if it's impossible or out-of-scope for Electron though.**

Problem Statement
--------------------------

I'm working on an app that makes liberal use of new windows. Those who have worked on multi-window electron apps before know that opening a new window with non-trivial amounts of JS/CSS/DOM can be very slow compared with a native experience of opening a window.

Current Workarounds
-----------------------------

One common approach is to load all potential windows on launch of application but keep them hidden, when the user "opens" the window then it is simple a case of calling `win.show()`. This approach works quite well when there are only a handful of windows that need to be loaded. When trying to scale this approach it quickly starts to effect both startup performance and resource usage. Also it feels like a very sub-optimal solution when windows often share 80% of CSS/JS code (because of shared libs/frameworks).

I know that Chrome's "snapshot" feature was explored before (https://github.com/electron/electron/issues/169#issuecomment-33667112) but it sounds like it's not going to work.

Forked Windows
-----------------------

I have no idea if this is possible (or reasonable) but a possible approach might to create forked windows instead.

Currently, a new window is a new renderer process and a new document is rendered from scratch. Could there be an electron feature that allows us to re-use the existing webpage that we currently have loaded and somehow make new windows a fork from that state. The new window would just resume from the existing window's state but perhaps with a different hash-param in the URL. This would mean we could build fast multi-window apps by simply responding to the `onhashchange` event.

As I said already, I've no idea if this is even technically possible using current Chromium builds, so feel free to close this if it's impossible or something that Electron isn't likely to attempt in the future. 😃

**Comment by zcbenz** [comment]
Implementing something like "forked windows" requires the ability to dump and restore the current state of the web engine, which neither node, blink, or v8 supports, and I don't think it will ever be supported in future.

For POSIX systems it is possible to use `fork` call to copy the entire process, and in Chromium each renderer process has very complex connection with the main process, simply fork the renderer process will not work.

The closest thing I can think of is to save the HTML of current window and load it in new window, and then dynamically update the HTML file. But it is very hard to achieve, and I don't know whether it can make things better.

**Comment by davej** [comment]
Thanks for the explanation.

**Comment by luguoeryi** [comment]
I also have this problem，hope that the electron can support multi-window solutions， thank!
