### ISSUE TITLE
can't use npm module `markdown'

### ISSUE THREAD

**Issue by zchrissirhcz** [electron/electron#6064]
* Electron version:1.2.2
* Operating system:windows10, 64bit

I want to use use `markdown'  library in my own projects, which is published on https://github.com/evilstreak/markdown-js.

I have already installed `markdown' via npm, with it's newest version.

When I run the electron app, this code doesn't work:
```
var gg = require('markdown').markdown;
```

Anyone can help me?

**Comment by mnquintana** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Electron message board](https://discuss.atom.io/c/electron) or the [Electron Slack channel](http://atom-slack.herokuapp.com/) is where you'll probably be able to find answers faster. Hope that helps!
