### ISSUE TITLE
Ability to subscribe to local notifications in systemPreferences

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#6066]
* Electron version: 1.2.2
* Operating system: OS X 10.11.5

Add a listener for [`NSUserDefaultsDidChangeNotification`](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSUserDefaults_Class/#//apple_ref/c/data/NSUserDefaultsDidChangeNotification):
```
systemPreferences.subscribeNotification('NSUserDefaultsDidChangeNotification', () => {
  // never gets here :(
});
```

Pop open System Preferences and change something under text (spelling, substitutions, or smart quotes). The notification never arrives. Have I misunderstood this API? Example usage [here](https://github.com/CharlieHess/electron-text-substitutions/blob/master/src/index.js#L46).

**Comment by zcbenz** [comment]
`NSUserDefaultsDidChangeNotification` has to be subscribed to `NSNotificationCenter`, while the `systemPreferences.subscribeNotification` subscribes to `NSDistributedNotificationCenter`.

We probably need a new `systemPreferences.subscribeLocalNotification` API.

**Comment by CharlieHess** [comment]
Unfortunately `subscribeLocalNotification` isn't firing either (same steps, but v1.2.4). :cry:

**Comment by zcbenz** [comment]
For what change are you trying to get subscribed?

**Comment by CharlieHess** [comment]
NSUserDictionaryReplacementItems or the smart quotes / smart dashes, anything under System Settings | Keyboard | Text.

**Comment by zcbenz** [comment]
I think the API is implemented correctly, you are just using the wrong notification for what you want. You can try subscribing to `NSSystemColorsWillChangeNotification`, which can be correctly triggered when you change system color.

**Comment by CharlieHess** [comment]
Hmm, they're all values under `NSUserDefaults` (global domain). `defaults read -g` to see them. I'll do some more research though.

**Comment by CharlieHess** [comment]
@zcbenz you're right, the proper notifications for these items are:
```
const textSubstitutionsChangedKey = 'IMKTextReplacementDidChangeNotification';
const smartQuotesChangedKey = 'NSAutomaticQuoteSubstitutionEnabledChanged';
const smartDashesChangedKey = 'NSAutomaticDashSubstitutionEnabledChanged';
```
