### ISSUE TITLE
Clearing browserWindow cache upon autoUpdate

### ISSUE THREAD

**Issue by mzmousa** [electron/electron#6067]
* Electron version: 1.2.2
* Operating system: Wanting this to work for windows (and then osx)

When my app updates via autoUpdater, I get everything installed fine. However, when I run my app again, the code for the previous version of my app is stored in a cache and is reused. I wanted to know if there was a way to clear this cache upon doing an update. I think I should be using the `session.clearCache` API, but I don't know where to add this  snippet of code. It seems to work fine on its own if I run this every time the app is ready (my browser window is called nextWindow). 

One idea I had was to run this right before `autoUpdater.quitAndInstall()`,
```
autoupdater.on('update-downloaded' ...
...
    var ses = nextWindow.webContents.session;
    nextWindow.webContents.session.clearCache(function() {
        autoUpdater.quitAndInstall();
    });
...
````
and another idea I had was to run this right before my `squirrel` event handling
```
switch (squirrelEvent) {
			case '--squirrel-install':
			case '--squirrel-updated':
				// Install desktop and start menu shortcuts
				var ses = nextWindow.webContents.session;
				nextWindow.webContents.session.clearCache(function() {
					executeSquirrelCommand(["--createShortcut", target], electron.app.quit);
				});
				return true;
```

If anyone can lead me in the right direction, or if they have done something similar, I'd appreciate some help :)

**Comment by zcbenz** [comment]
Either cleaning cache before `quitAndInstall` or after the first launch is the right way to go. For more questions, I suggest seeking help from [the community](https://github.com/electron/electron#community).
