### ISSUE TITLE
Renderer process crash @ electron.exe!atom::AtomRendererClient::WillReleaseScriptContext

### ISSUE THREAD

**Issue by juturu** [electron/electron#6069]
* Electron version: 1.2.2
* Operating system: Windows 10

We are seeing inconsistent (no straight repro) crash in the app with crash dump pointing to callstack like below. Any ideas? We haven't seen this with electron v0.37.8.

Thread 0 (crashed)
 0  electron.exe!atom::AtomRendererClient::WillReleaseScriptContext(v8::Local<v8::Context>,content::RenderFrame *) [atom_renderer_client.cc : 287 + 0x0]
    eip = 0x000beb84   esp = 0x03efe49c   ebp = 0x03efe4a8   ebx = 0x394a26f0
    esi = 0x00000000   edi = 0x4f908a70   eax = 0xfffffffe   ecx = 0x04258f04
    edx = 0x030dcacc   efl = 0x00210282
    Found by: given as instruction pointer in context
 1  electron.exe!atom::`anonymous namespace'::AtomRenderFrameObserver::WillReleaseScriptContext [atom_renderer_client.cc : 87 + 0xe]
    eip = 0x000beb6c   esp = 0x03efe4b0   ebp = 0x03efe4b8
    Found by: call frame info
 2  electron.exe!content::RenderFrameImpl::willReleaseScriptContext(blink::WebLocalFrame *,v8::Local<v8::Context>,int) [render_frame_impl.cc : 3990 + 0x83]
    eip = 0x0094d040   esp = 0x03efe4c0   ebp = 0x03efe4e0
    Found by: call frame info
 3  electron.exe!blink::FrameLoaderClientImpl::willReleaseScriptContext(v8::Local<v8::Context>,int) [frameloaderclientimpl.cpp : 213 + 0x16]
    eip = 0x0034d273   esp = 0x03efe4e8   ebp = 0x03efe4f4
    Found by: call frame info
 4  electron.exe!blink::WindowProxy::disposeContext(blink::WindowProxy::GlobalDetachmentBehavior) [windowproxy.cpp : 112 + 0x19]
    eip = 0x01e96a20   esp = 0x03efe4fc   ebp = 0x03efe518
    Found by: call frame info
 5  electron.exe!blink::WindowProxy::clearForNavigation() [windowproxy.cpp : 144 + 0x9]
    eip = 0x01e96589   esp = 0x03efe520   ebp = 0x03efe53c
    Found by: call frame info
 6  electron.exe!blink::WindowProxyManager::clearForNavigation() [windowproxymanager.cpp : 56 + 0x8]
    eip = 0x01d00243   esp = 0x03efe544   ebp = 0x03efe558
    Found by: call frame info
 7  electron.exe!blink::ScriptController::clearWindowProxy() [scriptcontroller.cpp : 265 + 0xa]
    eip = 0x01d283f8   esp = 0x03efe560   ebp = 0x03efe574
    Found by: call frame info
 8  electron.exe!blink::LocalFrame::setDOMWindow(blink::LocalDOMWindow *) [localframe.cpp : 418 + 0xb]
    eip = 0x01fbcb46   esp = 0x03efe57c   ebp = 0x03efe584
    Found by: call frame info
 9  electron.exe!blink::DocumentLoader::ensureWriter(WTF::AtomicString const &,blink::KURL const &) [documentloader.cpp : 457 + 0x1d]
    eip = 0x0203b471   esp = 0x03efe58c   ebp = 0x03efe614
    Found by: call frame info
10  electron.exe!blink::DocumentLoader::finishedLoading(double) [documentloader.cpp : 286 + 0x1c]
    eip = 0x0203b9e4   esp = 0x03efe61c   ebp = 0x03efe678
    Found by: call frame info
11  electron.exe!blink::DocumentLoader::maybeLoadEmpty() [documentloader.cpp : 618 + 0x12]
    eip = 0x0203bf38   esp = 0x03efe680   ebp = 0x03efe89c
    Found by: call frame info
12  electron.exe!blink::DocumentLoader::startLoadingMainResource() [documentloader.cpp : 629 + 0x11]
    eip = 0x0203cbe9   esp = 0x03efe8a4   ebp = 0x03efeb9c
    Found by: call frame info
13  electron.exe!blink::FrameLoader::startLoad(blink::FrameLoadRequest &,blink::FrameLoadType,blink::NavigationPolicy) [frameloader.cpp : 1413 + 0x8]
    eip = 0x01fb6f19   esp = 0x03efeba4   ebp = 0x03efec78
    Found by: call frame info
14  electron.exe!blink::FrameLoader::load(blink::FrameLoadRequest const &,blink::FrameLoadType,blink::HistoryItem *,blink::HistoryLoadType) [frameloader.cpp : 961 + 0x10]
    eip = 0x01fb4a0c   esp = 0x03efec80   ebp = 0x03efee64
    Found by: call frame info
15  electron.exe!blink::ScheduledURLNavigation::fire(blink::LocalFrame *) [navigationscheduler.cpp : 124 + 0x5]
    eip = 0x0203eb21   esp = 0x03efee6c   ebp = 0x03eff198
    Found by: call frame info
16  electron.exe!blink::NavigationScheduler::navigateTask() [navigationscheduler.cpp : 397 + 0x7]
    eip = 0x0203ec4c   esp = 0x03eff1a0   ebp = 0x03eff1bc
    Found by: call frame info
17  electron.exe!WTF::PartBoundFunctionImpl<1,std::tuple<blink::CrossThreadWeakPersistentThisPointer<blink::NavigationScheduler> &&>,WTF::FunctionWrapper<void ( blink::NavigationScheduler::*)(void)> >::operator()() [functional.h : 275 + 0x32]
    eip = 0x0203dd77   esp = 0x03eff1ac   ebp = 0x03eff1bc
    Found by: call frame info
18  electron.exe!scheduler::WebTaskRunnerImpl::runTask(std::unique_ptr<blink::WebTaskRunner::Task,std::default_delete<blink::WebTaskRunner::Task> >) [web_task_runner_impl.cc : 68 + 0x8]
    eip = 0x01811efb   esp = 0x03eff1bc   ebp = 0x03eff1bc
    Found by: call frame info
19  electron.exe!base::internal::Invoker<base::IndexSequence<0>,base::internal::BindState<base::internal::RunnableAdapter<void (*)(std::unique_ptr<blink::WebTaskRunner::Task,std::default_delete<blink::WebTaskRunner::Task> >)>,void ,base::internal::PassedWrapper<std::unique_ptr<blink::WebTaskRunner::Task,std::default_delete<blink::WebTaskRunner::Task> > > >,base::internal::InvokeHelper<0,void,base::internal::RunnableAdapter<void (*)(std::unique_ptr<blink::WebTaskRunner::Task,std::default_delete<blink::WebTaskRunner::Task> >)> >,void >::Run(base::internal::BindStateBase *) [bind_internal.h : 362 + 0x54]
    eip = 0x01811cdf   esp = 0x03eff1c4   ebp = 0x03eff284
    Found by: call frame info
20  electron.exe!base::debug::TaskAnnotator::RunTask(char const *,base::PendingTask const &) [task_annotator.cc : 51 + 0x8]
    eip = 0x0028da17   esp = 0x03eff28c   ebp = 0x03eff2e0
    Found by: call frame info
21  electron.exe!scheduler::TaskQueueManager::ProcessTaskFromWorkQueue(scheduler::internal::WorkQueue *,scheduler::internal::TaskQueueImpl::Task *) [task_queue_manager.cc : 289 + 0x1d]
    eip = 0x01819eda   esp = 0x03eff2e8   ebp = 0x03eff3bc
    Found by: call frame info
22  electron.exe!scheduler::TaskQueueManager::DoWork(base::TimeTicks,bool) [task_queue_manager.cc : 201 + 0xc]
    eip = 0x018196f3   esp = 0x03eff3c4   ebp = 0x03eff504
    Found by: call frame info
23  electron.exe!base::internal::Invoker<base::IndexSequence<0,1,2>,base::internal::BindState<base::internal::RunnableAdapter<void ( scheduler::TaskQueueManager::*)(base::TimeTicks,bool)>,void ,base::WeakPtr<scheduler::TaskQueueManager>,base::TimeTicks,bool>,base::internal::InvokeHelper<1,void,base::internal::RunnableAdapter<void ( scheduler::TaskQueueManager::*)(base::TimeTicks,bool)> >,void >::Run(base::internal::BindStateBase *) [bind_internal.h : 362 + 0x47]
    eip = 0x0181a39f   esp = 0x03eff50c   ebp = 0x03eff528
    Found by: call frame info
24  electron.exe!base::debug::TaskAnnotator::RunTask(char const *,base::PendingTask const &) [task_annotator.cc : 51 + 0x8]
    eip = 0x0028da17   esp = 0x03eff530   ebp = 0x03eff584
    Found by: call frame info
25  electron.exe!base::MessageLoop::RunTask(base::PendingTask const &) [message_loop.cc : 479 + 0x11]
    eip = 0x00247dad   esp = 0x03eff58c   ebp = 0x03eff6cc
    Found by: call frame info
26  electron.exe!base::MessageLoop::DoWork() [message_loop.cc : 600 + 0xb]
    eip = 0x00247413   esp = 0x03eff6d4   ebp = 0x03eff750
    Found by: call frame info
27  electron.exe!base::MessagePumpDefault::Run(base::MessagePump::Delegate *) [message_pump_default.cc : 33 + 0x9]
    eip = 0x0028fcb7   esp = 0x03eff758   ebp = 0x03eff774
    Found by: call frame info
28  electron.exe!base::MessageLoop::RunHandler() [message_loop.cc : 443 + 0x9]
    eip = 0x00247aa1   esp = 0x03eff77c   ebp = 0x03eff7a4
    Found by: call frame info
29  electron.exe!base::RunLoop::Run() [run_loop.cc : 35 + 0x7]
    eip = 0x002947e8   esp = 0x03eff788   ebp = 0x03eff7a4
    Found by: call frame info
30  electron.exe!base::MessageLoop::Run() [message_loop.cc : 295 + 0x8]
    eip = 0x00247a7d   esp = 0x03eff7ac   ebp = 0x03eff7c8
    Found by: call frame info
31  electron.exe!content::RendererMain(content::MainFunctionParams const &) [renderer_main.cc : 199 + 0xc]
    eip = 0x0095b54e   esp = 0x03eff7d0   ebp = 0x03eff8e8
    Found by: call frame info
32  electron.exe!content::RunNamedProcessTypeMain(std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,content::MainFunctionParams const &,content::ContentMainDelegate *) [content_main_runner.cc : 422 + 0xd]
    eip = 0x0039aec0   esp = 0x03eff8f0   ebp = 0x03eff908
    Found by: call frame info
33  electron.exe!content::ContentMainRunnerImpl::Run() [content_main_runner.cc : 789 + 0x6]
    eip = 0x0039ad65   esp = 0x03eff910   ebp = 0x03eff95c
    Found by: call frame info
34  electron.exe!content::ContentMain(content::ContentMainParams const &) [content_main.cc : 19 + 0x7]
    eip = 0x00397e53   esp = 0x03eff964   ebp = 0x03eff96c
    Found by: call frame info
35  electron.exe!wWinMain [atom_main.cc : 115 + 0x9]
    eip = 0x000b098b   esp = 0x03eff974   ebp = 0x03effa20
    Found by: call frame info
36  electron.exe!__scrt_common_main_seh [exe_common.inl : 264 + 0x1a]
    eip = 0x0251fd3d   esp = 0x03effa28   ebp = 0x03effa6c
    Found by: call frame info
37  kernel32.dll + 0x162c4
    eip = 0x74ea62c4   esp = 0x03effa74   ebp = 0x03effa80
    Found by: call frame info
38  ntdll.dll + 0x61c22
    eip = 0x774e1c22   esp = 0x03effa88   ebp = 0x03effac8
    Found by: previous frame's frame pointer
39  ntdll.dll + 0x61bed
    eip = 0x774e1bed   esp = 0x03effad0   ebp = 0x03effad8
    Found by: previous frame's frame pointer

Thread

**Comment by zcbenz** [comment]
I'm merging this to #6017.
