### ISSUE TITLE
webview tag has all custom functions missing

### ISSUE THREAD

**Issue by frozeman** [electron/electron#6079]
* Electron version: 1.2.2
* Operating system: OSX 10.11.5

Since this version the `webview` tag has all its custom functions like `.reload()` etc missing.

This breaks it completely

<img width="518" alt="screen shot 2016-06-16 at 12 22 02" src="https://cloud.githubusercontent.com/assets/232662/16113636/6d5db38a-33bd-11e6-80f4-42e2f3834e53.png">

**Comment by kevinsawicki** [comment]
Are you seeing this as well on `1.2.3`?

I'm having a little trouble reproducing, could you provide a sample app that is failing?

<img width="794" alt="screen shot 2016-06-16 at 9 12 50 am" src="https://cloud.githubusercontent.com/assets/671378/16124159/9852f534-33a2-11e6-8a6a-2424363e64a4.png">

**Comment by frozeman** [comment]
I will try that in 1.2.3 thanks.

**Comment by frozeman** [comment]
I tried in 1.2.5 now and it is still missing:
<img width="1059" alt="screen shot 2016-06-27 at 13 53 04" src="https://cloud.githubusercontent.com/assets/232662/16378829/7fd5b92c-3c6e-11e6-9209-4d2f45f42122.png">

**Comment by frozeman** [comment]
And another screenshot using your selector:

<img width="1059" alt="screen shot 2016-06-27 at 13 54 58" src="https://cloud.githubusercontent.com/assets/232662/16378879/cbd866d0-3c6e-11e6-8391-bf3d9e865b81.png">

**Comment by kevinsawicki** [comment]
@frozeman could you include a minimal application that exhibits this issue?

**Comment by luclu** [comment]
This seems to be caused by PR https://github.com/electron/electron/issues/3943 introduced in `1.1.1` (*Disable webview when node integration is off*).

**Comment by frozeman** [comment]
Ah, thanks @luclu i will enable node-integration then

**Comment by frozeman** [comment]
Hm the problem is that with enabling node integration, it breaks Meteor because of the require from the node integration.

Is there a way to enable the web view, while disabling node-integration?

**Comment by frozeman** [comment]
I figured removing the `module` and `require` object from the `window` works.

**Comment by zcbenz** [comment]
You can enable the node integration, and then remove the symbols in preload script.
