### ISSUE TITLE
question: <webview>.url is undefined

### ISSUE THREAD

**Issue by zhuangya** [electron/electron#6080]
* Electron version:
1.2.3
* Operating system:
- OS X 10.11.5
- window 7

and i also created a minimal project to reproduce this: https://github.com/zhuangya/electron-webview-url

 [the undefined line](https://github.com/zhuangya/electron-webview-url/blob/c5a2f0fc27853803a63933652e73e2fda840bb8d/index.html#L12)

i can not get <webview> tag's `url` any longer now.

deleted intended?

should i just use `<webview>.getURL()` instead?

thank!

**Comment by kevinsawicki** [comment]
Did `.url` used to work? If so, which version?

I thought `.src` and `getURL()` were the two APIs for this.

**Comment by zhuangya** [comment]
yes @kevinsawicki you're right.

i got something wrong.

`getURL()` works perfectly

closing this :)
