### ISSUE TITLE
Windows - Links open only in background

### ISSUE THREAD

**Issue by kunkinkan** [electron/electron#6081]
`electron.shell.openExternal(url);`

Internet Explorer will open behind the app. Is it not possible to activate it?

**Comment by zcbenz** [comment]
Refs #4349.

**Comment by kevinsawicki** [comment]
>  Is it not possible to activate it?

From my testing on Windows 10 it will activate if you call `shell.openExternal` from the main process instead of from the renderer process.

**Comment by zcbenz** [comment]
Electron is telling Windows to open the link in foreground, whether the link will be opened in foreground is depended on Windows itself and there does not seem to be a way to change this. so I'm closing this as won't fix.
