### ISSUE TITLE
Warning! Trojan Dropper inside node modules

### ISSUE THREAD

**Issue by space-curiosity** [electron/electron#6086]
I found couple Trojan and Trojan Dropper inside node modules when you do npm install on projects and here is details:

`node_modules\core-js\client\core.min.js` -> `TrojanDropper.VBS.f`
 `node_modules\electron-winstaller-fixed\vendor\winterop.dll`  ->  `Trojan.Win32.Dropper.bgbb`
`node_modules\electron-winstaller-fixed\vendor\Setup.exe`  -> `TrojanDropper.VBS.f`and  `Trojan[:HEUR]/Win32.AGeneric`

Please fix those issues.

**Comment by kevinsawicki** [comment]
The paths listed are not part of this project and are not distributed with it.

You should report this issue against the application that provided you those files or the modules themselves.

https://www.npmjs.com/package/electron-winstaller-fixed

https://www.npmjs.com/package/core-js

**Comment by space-curiosity** [comment]
Ok cool, thanks
