### ISSUE TITLE
protocol missing all its methods

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#6093]
* Electron version: 1.2.3
* Operating system: Any

`protocol` seems to only have `registerStandardSchemes` in Electron 1.2.3, previous versions have the methods I expect (i.e. `interceptXYZProtocol` et al)

**Comment by kevinsawicki** [comment]
Closing in favor of #6094 which I noticed first.

**Comment by paulcbetts** [comment]
Uhhhh what? I edited the title and it created a new issue?

**Comment by kevinsawicki** [comment]
> Uhhhh what? I edited the title and it created a new issue?

![](http://s3-ec.buzzfed.com/static/enhanced/terminal05/2012/7/16/15/anigif_enhanced-buzz-15282-1342465300-4.gif)

**Comment by paulcbetts** [comment]
![](http://i.giphy.com/s5uIHJUlZNQFq.gif)
