### ISSUE TITLE
protocol missing all its methods in Electron 1.2.3

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#6094]
* Electron version: 1.2.3
* Operating system: Any

`protocol` seems to only have `registerStandardSchemes` in Electron 1.2.3, previous versions have the methods I expect (i.e. `interceptXYZProtocol` et al)

**Comment by kevinsawicki** [comment]
I wonder if this might be related to https://github.com/electron/electron/pull/5904 /cc @deepak1556

**Comment by paulcbetts** [comment]
This looks to still be an issue in 1.2.4 :(

**Comment by kevinsawicki** [comment]
@paulcbetts can you provide repro steps for what you are seeing?

I'm not able to reproduce from the renderer side:

<img width="799" alt="screen shot 2016-06-22 at 5 25 42 pm" src="https://cloud.githubusercontent.com/assets/671378/16288211/6bbf870c-389e-11e6-97ae-75ca3401d868.png">

**Comment by paulcbetts** [comment]
@kevinsawicki Try to open any app with `electron-prebuilt-compile@1.2.4`, you'll get:

![](http://f.cl.ly/items/053w2T2g270Q10371U2Z/Image%202016-06-22%20at%205.19.11%20PM.png)

```sh
md foo && cd foo
npm install electron-prebuilt-compile@1.2.4
./node_modules/bin/electron path/to/default_app
```

**Comment by SebastianEdwards** [comment]
Glad to see this has been fixed - believe this is the root cause of what has stopped my secure cookies from being persisted in nightmare.js.
