### ISSUE TITLE
Windows: Folders open with tree sidepane when it's disabled in explorer

### ISSUE THREAD

**Issue by notatestuser** [electron/electron#6098]
After setting Windows Explorer to not show the folder tree sidepane on the left, which is toggleable from Organize / Layout / Navigation pane, it continues to appear each time a `shell` method is used to display a folder.

The electron version I tried is pre-v1.0 but I scanned over the changelog for patches that may have fixed this and saw nothing!
- Electron version: 0.37.2
- Operating system: Windows

**Comment by notatestuser** [comment]
Possibly related to #4092

**Comment by zcbenz** [comment]
I can reproduce with `shell.openItem`.

**Comment by codebytere** [comment]
closing due to abandonment.
