### ISSUE TITLE
electron command doesn't redirect console.log to powershell but does in cmd

### ISSUE THREAD

**Issue by towertop** [electron/electron#6100]
* Electron version: 1.2.0
* Operating system: Windows 8.1 x64

I was using gitshell which based on powershell. Electron ran silently in powershell and I cannot check the output from console.log invocations. But it works well under cmd terminal.

![powershell](https://cloud.githubusercontent.com/assets/1001699/16139904/bf40abb4-347e-11e6-9867-784ddefbf6d9.png)

![cmd](https://cloud.githubusercontent.com/assets/1001699/16140085/5386e74c-3480-11e6-90c5-0737d2ce21c2.png)

There were relative discussions before. But this looks confusing at the latest version. I think it deserves fix or mention in document:

https://github.com/electron/electron/issues/3032
https://github.com/electron/electron/issues/683

**Comment by zcbenz** [comment]
This had been fixed by #5776 in v1.2.1.

**Comment by dperetti** [comment]
I'm experiencing this in 1.4.15 :-(

**Comment by choidamdam** [comment]
I have same issue, but both on cmd and powershell. only on git bash it seems to be working.
- Electron v1.6.2
- Windows 10 Pro 64bit 1607 (14393.693)

**Comment by pauldorn** [comment]
Should this be re-opened?  I have this same behavior.  printf from a c++ (native nodejs) module makes it to the command line shell in bash shell, but not in powershell.

**Comment by fcastilloec** [comment]
I see this issue on Windows 8.1 with electron `v1.8.4`
