### ISSUE TITLE
Chromium on ARMv6

### ISSUE THREAD

**Issue by kusti8** [electron/electron#6102]
I've searched a lot but I have not found an answer. Electron uses Chromium to render and I would like more information on how that is integrated. I assume it uses the Blink engine? Chromium cannot compile on ARMv6 and I wonder if there are any patches that you applied to get it work on ARMv6. It already compiles on ARMv7 but not v6. Just looking for a short explanation. Thanks!

**Comment by zcbenz** [comment]
We never tried to compile Electron for ARMv6, so sorry we can not help you.

**Comment by kusti8** [comment]
Sorry, under the impression that it was.

**Comment by WebReflection** [comment]
if I might ask, why is armv6 present as toolchain option ?
https://github.com/electron/electron/blob/78193a0608b5fa55161e95b7b3845b6bd85af377/toolchain.gypi#L71-L91

**Comment by abejfehr** [comment]
@kusti8 did you ever get this working on ARMv6?

**Comment by kusti8** [comment]
No I just gave up on it. The Pi has had Chromium compiled for it with a
patch that I've used to build it for them and the changes just for ARMv6
are relatively minor, but they would still need to be patched for electron.
