### ISSUE TITLE
Clicking on links causes screen to flash white on non-white backgrounds.

### ISSUE THREAD

**Issue by Mercieral** [electron/electron#6104]
* Electron version: 1.2.2
* Operating system: OS X El Capitan 10.11.5

Currently clicking on any link for me using the standard `<a href="...">` tag causes the screen to flash white when the pages both have a non-white background. I've seen other issues, such as  #1055, #1397, and #193 to name a few, that involve the white flash specifically on start up (#1055 pertains to webviews which I am not using). I am not sure if this is an issue with how my site is set up, electron, or chromium, but the flash does not occur when the same page is loaded on google chrome (see gifs below).The background color to each page is simple CSS loaded in the header as such,
```CSS
.simple-page {
  background: #51514c;
}
```

I have tried setting the browerWindow's backgroundColor setting to the same background color which had no impact. 

## In electron
![screen_flash_on_page_change](https://cloud.githubusercontent.com/assets/10813646/16153769/b5081460-3475-11e6-9af7-5a9cf101644a.gif)

## In Google Chrome
![screen_flash_on_page_change_chrome](https://cloud.githubusercontent.com/assets/10813646/16154250/fa1f7a32-3477-11e6-81e9-a354a68543a9.gif)

Any ideas/thoughts/suggestions?

**Comment by zcbenz** [comment]
Electron restarts render process for every navigation, that should be the reason of the white flash.

**Comment by Mercieral** [comment]
@zcbenz So is the only solution to convert to a SPA with angular or ember? This wouldn't fix the issue of it also flashing white on startup however.  It seems like #4996 was done to fix this issue but I am not certain on how to get rid of it properly (if there is a way to get rid of it).

**Comment by zcbenz** [comment]
@Mercieral For removing the flash on startup, you can follow the guide in:
https://github.com/electron/electron/blob/master/docs/api/browser-window.md#showing-window-gracefully

**Comment by zcbenz** [comment]
I just realized there is an upstream issue for this:
https://bugs.chromium.org/p/chromium/issues/detail?id=470669

I'm closing this issue since it is a well known issue of Chromium and there is not much meaning also tracking it in Electron.

**Comment by ankane** [comment]
Hey Cheng,

Thanks for all your great work on Electron. 😃 

You mentioned that "Electron restarts render process for every navigation."  Does the Chrome browser do something different to prevent flashes on page navigation?

**Comment by jontro** [comment]
Any updates on this?

**Comment by dglozic** [comment]
+1 on the question - as of Oct 2018 it is not fixed yet, and every time a new page is opened in Electron window, it flashes.

**Comment by jerry1100** [comment]
@ankane it looks like Chrome keeps the same renderer process when navigating (within the same domain) and Electron creates a new one.

Does anyone know why Electron creates a new renderer process for each navigation? I tried looking through the docs/google but couldn't find anything.

### Chrome (Version 71.0.3578.80 (Official Build) (64-bit)
![chrome](https://user-images.githubusercontent.com/18181641/49672560-6bd7c380-fa20-11e8-8b6a-50edc83af045.gif)

### Electron v3.0.10 | Chromium v66.0.3359.181 | Node v10.2.0 | v8 v6.6.346.32
![electron](https://user-images.githubusercontent.com/18181641/49672825-3aabc300-fa21-11e8-805e-32c861a81c37.gif)

**Comment by dglozic** [comment]
You can also tell it does that as each link click in Chromium is repainting the entire screen white before rendering, whereas Chrome transitions are much smoother.

**Comment by tomchomiak** [comment]
Bump

**Comment by robatwilliams** [comment]
This really should be reopened IMO. I'm seeting `StartProcessWithAccess` events of type `renderer` taking ~700ms every time a page navigation happens.
