### ISSUE TITLE
OSX EXC_CRASH (SIGABRT) in CrBrowserMain

### ISSUE THREAD

**Issue by mnp** [electron/electron#6108]
* Electron version: 1.21
* Operating system: OS X 10.11.2 (15C50)

Electron is called by VMD:
```
$ vmd --versions
vmd:       1.26.2
electron:  1.2.1
node:      6.1.0
chrome:    51.0.2704.63
v8:        5.1.281.47
openssl:   1.0.2h
zlib:      1.2.8
```

I'm having trouble reproducing it outside my environment for you.  The short version is, Emacs has a VMD preview mode, which ultimately shells out to VMD, which calls Electron like this:

```
/usr/local/lib/node_modules/vmd/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron  /usr/local/lib/node_modules/vmd/main/main.js /tmp/vmd-preview
```

I'm hoping the stack trace is enough to identify the issue:

[crash.txt](https://github.com/electron/electron/files/320799/crash.txt)

**Comment by zcbenz** [comment]
This is a duplicate of https://github.com/nodejs/node/issues/6563, there is already a fix in Node but it is not in any public release yet, we need to wait for a release of Node and then update to it.

**Comment by mnp** [comment]
@zcbenz : thanks for the note.  I'll close as dup | upstream.
