### ISSUE TITLE
Remote `Promise.reject` treated as unhanded rejection in main process

### ISSUE THREAD

**Issue by swashcap** [electron/electron#6113]
* Electron version: 1.2.2
* Operating system: OS X 10.11.5

_I made a sample app that shows this bug: https://github.com/swashcap/electron-reject-promise._

Electron treats `Promise.reject` responses in a remotely invoked call as unhandled rejections in the main process.

As an example, here’s the validation function, which lives in the main process:

```js
function validateWithPromise(name) {
  if (!name || name.length < 4) {
    return Promise.reject(new Error('Name must have at least 4 characters'));
  }

  return Promise.resolve(name);
}
```

And here’s the validation, which lives in the render process.

```js
const validateWithPromise = require('electron').remote.require('./path/to/validate-with-promise');

validateWithPromise(myName)
  .then(() => console.log('myName is valid!'))
  .catch(error => console.error('myName is invalid:', error.message));
```

Unfortunately, an invalid `myName` causes an `unhandledReject` in the _main_ process. I expect the RPC server serialize the rejection for handling in the remote process, _not_ in the main process.

**Comment by kevinsawicki** [comment]
Thanks for the detailed reported, much appreciated 👍
