### ISSUE TITLE
Unlock .asar files while the app is running

### ISSUE THREAD

**Issue by lordminor** [electron/electron#6117]
* Electron version: 1.2.3
* Operating system: WIN

Hi,

I was trying without success, to rename or delete the app.asar file while the application is running. I saw a lot of issues related with it, also a possible solution with modifyng the electron source code.

this: https://github.com/electron/electron/issues/3949

but didn't work :( 

How can I unlock the files, so I can rename or delete it? (for example for autoupdate the application). 

I'll appreciate your help! Thanks in advance! :)

**Comment by zcbenz** [comment]
No, it is not possible in Electron for now, and even you patched Electron to allow that, we would still strongly advice against that, Node.js is not designed to allow hot-patching loaded components, and it is definitely going to cause troubles for you.

**Comment by lordminor** [comment]
Hi. Thanks for the reply! 

I know that isn't the better way to update the App but what about download the asar file in another director and once the App is closed replace the App.asar..? It wont cause troubles. I'm trying to execute the script before unload the App but the file still locked. It is possible with node ? For example run a background service to apply the update or an event in electrón to execute code after the App was closed ? Thanks for the help.
