### ISSUE TITLE
icon size of MenuItem is wrong and unconfigurable

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#6121]
- Electron version: 1.2.2.0
- Operating system:  Win10-x64
- Issue: icon size of MenuItem is wrong and unconfigurable
- Expect: icon size of menu item is correct and configurable

When add an _ico_ icon which contains multiple sizes of icon (16x16, 32x32, 64x64, 128x128, 256x256), the menu icon looks very large.

```
const menu = Menu.buildFromTemplate([
     //... items
     {
          label: 'Test',
          icon: __dirname + '\\app.ico'
     }
]);
```

![electron-menu-icon-size-wrong](https://cloud.githubusercontent.com/assets/1104492/16170215/cb6b5ce0-357d-11e6-8370-fcbcfa408b15.png)

**Comment by kutu** [comment]
Have the same issue
electron version 1.7.4

![electron-menu-icon-too-large](https://user-images.githubusercontent.com/228802/28260880-0710e12e-6aee-11e7-867f-7060763712c5.png)

So I use png 16px icon for MenuItem.
It happens with MenuItem in app itself and in tray right click menu.
Windows 7 SP1 64bit

Even if I attach ico file with largest image of 32px, it will stretch it anyway to 256px

**Comment by codebytere** [comment]
closing due to abandonment.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (115/100 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:44186)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-96d6-jcjackson=joe-jackson.net@sgmail.github.com>)
	id 1dx1RI-0018JG-Ov
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:47:07 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=pjjdEruPfFpqRRtwnXzaw8e/YO4=; b=c0HR4Sd9x++kpNX6
	OSfAuUxi1+Ctl8aRxm9bhFdMqYOwDnePKkoUZD8zFa1m+lveLjAziZ+6nfsQwKiP
	dBn289xeR+f5I0oQHtSAzba9cXw4/aGErC1kpkuot0f0oamv0NJoxlv7sP8nvd89
	U06nDm311gLnweA0hYTHPeVpDAA=
Received: by filter0565p1mdw1.sendgrid.net with SMTP id filter0565p1mdw1-7035-59CB02EA-1
        2017-09-27 01:46:18.269773487 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0013p1iad2.sendgrid.net (SG) with ESMTP id gWYxNNskRiWeRM0iyZpiGA
	for <jcjackson@joe-jackson.net>; Wed, 27 Sep 2017 01:46:18.060 +0000 (UTC)
Date: Wed, 27 Sep 2017 01:46:18 +0000 (UTC)

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (117/100 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:41590)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-96d6-jcjackson=joe-jackson.net@sgmail.github.com>)
	id 1dx1Re-0018Vf-4B
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:47:29 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=t31EXJcBdA11fpxtxUSLG1fsS3k=; b=e/XDaxlaHztzTIGb
	IEoL6UTEwzixSoNLXppu+V8Rv/E26nJjAEvuWTuo4/4GWfIYlAFfG2GMguJfvgGA
	eyA0+MOZ7jLJpUnlFOVzEZtXk9bPtSHqSRa0vZbZUQPSEqRAmaQD5dPR7qVzyU0u
	9EylVzhoryNXj88ZRkuFaqoskIU=
Received: by filter0515p1mdw1.sendgrid.net with SMTP id filter0515p1mdw1-30246-59CB02F1-45
        2017-09-27 01:46:25.851955242 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0009p1iad1.sendgrid.net (SG) with ESMTP id br0zqUBZR-a1iDAigN6KhA
	for <jcjackson@joe-jackson.net>; Wed, 27 Sep 2017 01:46:25.812 +0000 (UTC)
Date: Wed, 27 Sep 2017 01:46:25 +0000 (UTC)

**Comment by benjaminadk** [comment]
Just to update this thread...
Electron 3.0.0
Windows 10-x64
Using an `ico` file still creates a large image
Instead I created a 16x16 `png` and that seems to work fine.

**Comment by PragmaticEd** [comment]
Any solution for this?

**Comment by ZsgsDesign** [comment]
@PragmaticEd Manually resize to 16*16 could fix the problem, if you don't want to open your Photoshop here is the solution I use:
```js
{
    label: 'Open-Source',
    icon: nativeImage.createFromPath(__dirname + '/resources/icons/github.png').resize({width:16}),
    click: async () => {
        //
    }
},
```
