### ISSUE TITLE
Remote fails to set maximum size when combined with synchronous calls to other remote functions

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#6122]
* Electron version: `1.2.3`
* Operating system: `Windows`

```js
remote.getCurrentWindow().setMaximumSize(300, 300);
remote.getCurrentWindow().setMinimumSize(50, 50);
console.info('No Errors');
```

When combining remote Minimum and Maximum size calls the maximum size fails to set.

If you change the sample code to be

```js
setTimeout(() => remote.getCurrentWindow().setMaximumSize(300, 300), 200);
remote.getCurrentWindow().setMinimumSize(50, 50);
console.info('No Errors');
```

So we wait a bit (make the two calls not at the same time) then the maximum size is set as expected

**Comment by zcbenz** [comment]
I can reproduce this, seems to be a Windows only bug.

**Comment by Deryllium** [comment]
I am receiving the same bug, however, when I make a call to set the maximum size, the minimum size is unset, and when I set the minimum size, the maximum size is unset. I have logged the results of the following code:

    mainWindow.setMinimumSize(320, 320);
    console.log(mainWindow.getMinimumSize());
    console.log(mainWindow.getMaximumSize());

    mainWindow.setMaximumSize(1280, 768);
    console.log(mainWindow.getMinimumSize());
    console.log(mainWindow.getMaximumSize());

This produces the following output:

    [ 320, 320 ]
    [ 0, 0 ]
    [ 0, 0 ]
    [ 1280, 768 ]

Using the workaround stated above to set the maximum window size after a timeout results in the same output.

**Comment by MarshallOfSound** [comment]
So it appears that you can either set minimum or maximum, but not both.

I looked more into my scenario and @Deryllium it correct 😢

**Comment by kevinsawicki** [comment]
I was able to reproduce this on Ubuntu 14.04 as well:

<img width="181" alt="screen shot 2016-07-11 at 5 08 01 pm" src="https://cloud.githubusercontent.com/assets/671378/16750920/15a50036-478a-11e6-9dbf-9b6cfa878f3f.png">

**Comment by MarshallOfSound** [comment]
I think I have a solution for this but I'm not at a windows machine at the moment.  Can someone test this patch?

```diff
diff --git a/atom/browser/native_window.cc b/atom/browser/native_window.cc
index c084f44..d718bcf 100644
--- a/atom/browser/native_window.cc
+++ b/atom/browser/native_window.cc
@@ -243,6 +243,9 @@ extensions::SizeConstraints NativeWindow::GetContentSizeConstraints() {
 void NativeWindow::SetMinimumSize(const gfx::Size& size) {
   extensions::SizeConstraints size_constraints;
   size_constraints.set_minimum_size(size);
+  if (GetContentSizeConstraints().HasMaximumSize())
+    size_constraints.set_maximum_size(
+        GetContentSizeConstraints().GetMaximumSize());
   SetSizeConstraints(size_constraints);
 }

@@ -253,6 +256,9 @@ gfx::Size NativeWindow::GetMinimumSize() {
 void NativeWindow::SetMaximumSize(const gfx::Size& size) {
   extensions::SizeConstraints size_constraints;
   size_constraints.set_maximum_size(size);
+  if (GetContentSizeConstraints().HasMinimumSize())
+    size_constraints.set_minimum_size(
+        GetContentSizeConstraints().GetMinimumSize());
   SetSizeConstraints(size_constraints);
 }


```

**Comment by kevinsawicki** [comment]
@MarshallOfSound thanks for the patch, that helped me track things down.

I went with a slightly different approach in #6455 that changes `NativeWindow::SetSizeConstraints` to reuse the current constraints.

**Comment by MarshallOfSound** [comment]
@kevinsawicki Lol, I always try to fix things higher up than they need to be 😆 

At least this will be fixed now 👍
