### ISSUE TITLE
Support for macOS Sierra's native tabs

### ISSUE THREAD

**Issue by leo** [electron/electron#6124]
The latest version of Apple's macOS (which will be released in the fall) introduces tabs for all apps. To me, it seems like a great idea if we could provide some kind of API interface for managing these.

For more details, scroll to "Tabs" on [this page](http://www.apple.com/macos/sierra-preview/).

**Comment by zcbenz** [comment]
The "tabs" feature is only meaningful when there is a toolbar above, however in Electron we don't have a way to set native toolbar, even if we added support for "tabs", users would only get it with empty titlebar, which is useless.

So I'm closing this as won't fix due to Electron's limitation for native UI.

**Comment by tommoor** [comment]
I'm not sure what you mean by it only being useful with a toolbar? This is a picture from the actual presentation:

![image](https://cloud.githubusercontent.com/assets/380914/16974276/cd4dae16-4def-11e6-976f-fbb25dfae0c5.png)

**Comment by leo** [comment]
@tommoor Yea, exactly

**Comment by TimNZ** [comment]
Pretty much describing how all Browsers (Chrome) tab support works, which is not what Electron is about replicating.

http://www.macworld.com/article/3088342/macs/how-to-use-tabs-in-macos-sierra.html

The ability to drag/move content (webview for example) between/from/to existing or new  renderer processes/BrowserWindow would enable a lot of similar scenarios in a cross-platform way as you can wrap your own HTML tab management around it, and there are plenty of good Tab libraries.

**Comment by matthewdias** [comment]
Perhaps this would be better as a third-party module?

**Comment by steverandy** [comment]
On sierra I'm seeing a new menu item "Show Tab Bar" under View which is never defined in my code.

I took a screenshot from slack beta app.

<img width="444" alt="screen shot 2016-09-22 at 10 43 19 am" src="https://cloud.githubusercontent.com/assets/525332/18735611/b65e490a-80b1-11e6-9263-5709c2b27b66.png">

**Comment by TimNZ** [comment]
Apparently needs to be explicitly disabled via code

http://stackoverflow.com/questions/39399553/how-do-i-disable-the-show-tab-bar-menu-option-in-sierra-apps

**Comment by ovanschie** [comment]
We'd like to use native tabs in our application. It already works quite nice actually (see screenshot), if you set the dock setting to always use tabs. It even works with titlebar hidden (not hidden-inset). 

![schermafbeelding 2016-09-23 om 21 48 05](https://cloud.githubusercontent.com/assets/3015449/18799598/b5fc180c-81d8-11e6-986d-3ba82f07fed0.png)

It would be nice to force the usage of tabs, so the user doesn't have to change its dock preference.

Also the menu items @steverandy mentioned were not present in my app, but they are in the Api Demo's app though.

**Comment by baconface** [comment]
I am not an OSX guy so I am unsure if I am completely understand this issue. But tabs are extremely easy to implement via HTML5/JavaScript with many third party libs serving this purpose. You can even style them to replicate the native look. What would be the advantage of supporting this over using web technologies?

**Comment by ovanschie** [comment]
@baconface it's about the behavior of the tabs; re-order animations (with preview window), drag and release tab to open in separate window, possibility to show tabs only in fullscreen mode (in stead of separate windows), menu items and shortcuts for navigating between tabs.

Most of this would be possible with web technologies of course, but may take some more time to implement for devs.

With this we can assure that Electron application behave the same as other applications (as the user would expect).

**Comment by davibe** [comment]
"show tab bar" works if you use system window decorations. It is not compatible with `frameless-window`

**Comment by bpasero** [comment]
Is there a way to put the menu item to a different location? I am thinking that there should be a role for the menu item that represents this item and I can put it somewhere less prominent.

**Comment by kevinsawicki** [comment]
In order to prevent the "Show Tab Bar" menu item from being unintentionally enabled for existing Electron apps on macOS Sierra, it is being hidden in #7415 using the same approach Chrome has implemented in https://bugs.chromium.org/p/chromium/issues/detail?id=642155

Please comment there if this would negatively impact your app in which case we can look into other possible solutions.

**Comment by bpasero** [comment]
Maybe we should still allow to bring it back by introducing a new menu item role on Mac.

**Comment by bkniffler** [comment]
This has been bothering me for quite some time now, with VS Code tabs not working and the VS Code team not able to fix it. Whats wrong with adding a something alike a config option "useNativeMacTabs" until a proper API has been figured out?

**Comment by paulcbetts** [comment]
> Whats wrong with adding something alike a config option "useNativeMacTabs" until a proper API has been figured out?

Because the tabs that Cocoa renders don't actually work in any usable way with Electron right now. This menu item is basically, "Please draw incorrect crap on my window".

**Comment by davibe** [comment]
Why don't they work in any usable way ?

**Comment by bkniffler** [comment]
I'm wondering the same. I've rolled back vscode to a version where electron doesn't kill the tabs and I find it very stable und usable from an end-user view.

**Comment by teamon** [comment]
> Because the tabs that Cocoa renders don't actually work in any usable way with Electron right now. This menu item is basically, "Please draw incorrect crap on my window".

UNLESS you open two (or more) folders using command line `atom .` and have atom in fullscreen - then there are pretty useful native tabs that just work: 

![](https://dl.dropboxusercontent.com/s/ynjbdtmqtc4rbpi/2017-02-15%20at%2011.36.png)

**Comment by simurai** [comment]
In Atom's case (and probably most other apps too) it only would make sense to have the tab bar if the native title bar is also shown. Otherwise when using a dark theme, the dark text of the tabs is not legible. And also when the window is not focused, the inactive tab gets a grey background:

![screen shot 2017-02-16 at 12 00 32 pm](https://cloud.githubusercontent.com/assets/378023/23005527/0d21528a-f440-11e6-9b04-1328b10ada23.png)

So if any of these [frameless window options](http://electron.atom.io/docs/api/frameless-window/) are set:

- `frame: false`
- `titleBarStyle: 'hidden'`
- `titleBarStyle: 'hidden-inset'`

then don't allow the tab bar, otherwise (with the native title bar) it should be fine.

**Comment by Wolfr** [comment]
Just wanted to drop in and applaud the work here, supporting native tabs well is also a wish from my POV.

**Comment by CestDiego** [comment]
I'm also here to applaud the work here and support you supporting native tabs :)

**Comment by narin** [comment]
Would love it if you could please reenable this feature.

**Comment by bpasero** [comment]
One idea could be that there is a setting in Electron that brings back native tabs. That way a user can after all decide if tabs should be on or off (surfaced via some kind of user setting).

@kevinsawicki is there any pointers for a similar case of a setting that I could use as starting point to look into?

**Comment by tonyganch** [comment]
I'm starting work on that issue 🐙
