### ISSUE TITLE
Node's ES module support and its impact on Electron.

### ISSUE THREAD

**Issue by jdalton** [electron/electron#6127]
I'm working on a [draft proposal](https://twitter.com/jdalton/status/743823031483564032) with @bmeck for an alternative to the current `.mjs` ES module loading proposal.

Would Node restricting ES modules to those having at least an `import` or `export` affect Electron if the browsers decided not to have that restriction? Whose module rules would be followed?

\cc @ofrobots and @caitp for more V8 insight.

**Comment by paulcbetts** [comment]
That depends on how import and export are implemented in V8, do you have any specs on that?

**Comment by jdalton** [comment]
\cc @ofrobots for more V8 insight.

**Comment by jdalton** [comment]
\cc @caitp too

**Comment by caitp** [comment]
@aklein and recently @jugglinmike are probably the most knowledgable about the module side of the frontend.

**Comment by jdalton** [comment]
As a follow up, I imagine for Node to even restrict ES modules to having an `import` or `export` that it would require work on V8's part to enable. Is that a fair assumption?

**Comment by paulcbetts** [comment]
Maybe! It depends on how they implement it

**Comment by jdalton** [comment]
The follow up was for the V8 folks :P

**Comment by bmeck** [comment]
For the case of `export {};` most likely we would need some sort of buy in from the parser, we can detect if there are imports or exports of other forms if the parser exposed import/export entries upon parsing (I would presume this to be the case).

**Comment by zcbenz** [comment]
I think the biggest challenge is Node and browsers may have differences on from where to `import`, browsers will load files from web urls, while Node is going to load from filesystem, I don't know if there is a way to support both ways inside one page in Electron.

**Comment by codebytere** [comment]
As this issue hasn't seen any action in a long time and is neither an enhancement request nor a bug, i'm going to go ahead and close it.
