### ISSUE TITLE
Crashes when while using a native addon

### ISSUE THREAD

**Issue by facekapow** [electron/electron#6129]
* Electron version:
Electron v1.2.x
* Operating system:
Mac OSX El Capitan 10.11.4

Electron crashes while using a native add-on. I'm not really sure what's going on.
Specifically, I'm using [this add-on](https://github.com/facekapow/node-libspotify), and Electron crashes when I try to login. It works perfectly fine in other Electron versions (`<1.2.x`). This is holding me back from updating to the newest Electron version in my app.

![screen shot 2016-06-18 at 8 04 47 pm](https://cloud.githubusercontent.com/assets/11756574/16174445/2a1fc714-3590-11e6-9c03-c8150d808aeb.png)
![screen shot 2016-06-18 at 8 04 57 pm](https://cloud.githubusercontent.com/assets/11756574/16174448/2c826228-3590-11e6-8f8d-58719a11042b.png)
![screen shot 2016-06-18 at 8 06 08 pm](https://cloud.githubusercontent.com/assets/11756574/16174449/2de95374-3590-11e6-92a7-65f777623db3.png)

**Comment by enlight** [comment]
Did you follow [the guide](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) to build your native module?

**Comment by facekapow** [comment]
Thanks for the quick reply, I'll check in the morning.

**Comment by facekapow** [comment]
Thanks! I had completely overlooked that, rebuilding for Electron solved the problem! I'll have to remember to add it to my app's readme.
