### ISSUE TITLE
ipc parse  json bug 

### ISSUE THREAD

**Issue by zaaack** [electron/electron#6132]
* Electron version:1.2.3
* Operating system:deepin15.2(debian )

I find that if the data object passed though ipc has sub properties reference to same object,  only the first property has value and others are null.

some thing like this 
```
let a={bb:123}
event.sender.send("msg", [
{aa:a},
{aa:a}

])

```

the second aa would be null when received. I had to use JSON.parse or  use independed object.

**Comment by zcbenz** [comment]
This is actually expected behavior, explanations can be found in #3598.

**Comment by zaaack** [comment]
why not just use JSON.parse?@zcbenz
