### ISSUE TITLE
Rebuild unsuccess. masters, please help me

### ISSUE THREAD

**Issue by Xiao-Yaran** [electron/electron#6142]
sys:windows7-32
node:v4.4.4
npm:2.15.1
electron:v1.2.3

---------------------------
Masters,I am new to node.js and electron ,If electron-rebuild rebuild native module successfully,which folder is the rebuilding native module in? 
----------------------------

For trying to rebuild native module in electron . I did the following:
(1)npm install -g node-gyp

(2)npm install node-pre-gyp -g

(3)npm install electron-prebuilt -g

(4)npm install --save-dev electron-rebuild

(5)installing a module(npm install mqtt)

 I run ".\node_modules\.bin\electron-rebuild.cmd" ,It did not work.The error message:Unable to find electron-prebuilt's version number.Then I run "npm install electron-prebuilt --save-dev" to install electron-prebuilt,".\node_modules\.bin\electron-rebuild.cmd"  works,but rebuild fail.

the log:

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>.\node_modules\.bin\electron-rebuild.cmd

> electron-prebuilt@1.2.3 postinstall C:\Users\Administrator\node_modules\electr
on-prebuilt
> node install.js

> nslog@3.0.0 install C:\Users\Administrator\node_modules\electron-rebuild\node_
modules\nslog
> node-gyp rebuild

C:\Users\Administrator\node_modules\electron-rebuild\node_modules\nslog>if not d
efined npm_config_node_gyp (node "C:\Users\Administrator\node_modules\electron-r
ebuild\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-g
yp.js" rebuild )  else (node "" rebuild )
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
  main.cc
  nslog_win.cc
  win_delay_load_hook.c
C:\Users\Administrator\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-
1.2.3\Release\iojs.lib : fatal error LNK1106: �ļ���Ч����������: �޷����ҵ� 0xF507
4 [C:\Users\Administrator\node_modules\electron-rebuild\node_modules\nslog\build
\nslog.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\node_modules\e
lectron-rebuild\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\WorkProgram\\nodejs\\node.exe" "C:\\Users\\Administrator\\
node_modules\\electron-rebuild\\node_modules\\npm\\node_modules\\node-gyp\\bin\\
node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\node_modules\electron-rebuild\node_modules\n
slog
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\WorkProgram\\nodejs\\node.exe" "C:\\Users\\Administrator\\nod
e_modules\\electron-rebuild\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--ru
ntime=electron" "--target=1.2.3" "--arch=ia32"
npm ERR! node v4.4.4
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE
npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\node_modules\npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (C:\Users\Administrator\node_modules\electron-re
build\lib\spawn.js:55:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by MarshallOfSound** [comment]
Opening an identical on another repository will unlikely land you much help 😆 
electron/electron-rebuild/issues/78

You posted a massive error message which is very generic, very long and doesn't help anyone fix your problem.

Basic debugging step, have you tried deleting `node_modules` and starting again :/  Sometimes that fixes things

**Comment by zcbenz** [comment]
Closing since it has been tracked in the correct repo.
