### ISSUE TITLE
Recursive promises internal error

### ISSUE THREAD

**Issue by paul321** [electron/electron#6143]
* Electron version: 1.2.2
* Operating system: Windows

I get the following error when i call a recursive promise function

internal/process/next_tick.js:103 GET file:///D:/devel/work/js/null net::ERR_FILE_NOT_FOUND_tickCallback @ internal/process/next_tick.js:103
overview.js:79

Any ideas?

Thank you

**Comment by enlight** [comment]
Please provide minimal sample code that reproduces the error.

**Comment by paul321** [comment]
Unfortunately the app is very complex to figure out the minimal code required, a simple recursive function doesn't fail

**Comment by kevinsawicki** [comment]
Closing this out for now, please comment if you can provide more details and reproduction steps or a minimal example app, thanks.
