### ISSUE TITLE
Support redux devtools extension

### ISSUE THREAD

**Issue by sergeysova** [electron/electron#6148]
- Electron version: v1.2.3
- Operating system: OSX 10.11.5

https://github.com/zalmoxisus/redux-devtools-extension

Extension can't open windows

steps:
1. `npm install electron-devtools-installer`
2. `require('electron-devtools-installer').default('lmhkpmbekcpmknklioeibfkpmmfibljd')`
3. `electron .`
4. in electron console `devToolsExtension.open('left')`

**Comment by Draivin** [comment]
As of version 2.2.0 of redux-devtools-extensions, [it uses](https://github.com/zalmoxisus/redux-devtools-extension/commit/3adb4874ca6a5be6b931abb837c5a5a8d7300b37) `chrome.storage.local`, which electron apparently doesn't support, so it won't work even without opening other windows.

Previously it would work normally when using it from inside the devtools window.

**Comment by kevinsawicki** [comment]
@LestaD @Draivin  is this still an issue on Electron 1.3.2? If it is, what is still not working properly? Thanks.

Refs https://github.com/zalmoxisus/redux-devtools-extension/pull/143

**Comment by jhen0409** [comment]
@kevinsawicki currently redux-devtools-extension is only supported for devtools panel, so I think open('left') (popup window) isn't supported yet on Electron.

**Comment by codebytere** [comment]
Given the pull request referenced above, I believe this extension is now supported and this issue may be closed.
