### ISSUE TITLE
Uncaught Exception: TypeError: mainWindow.addDevToolsExtension is not a function

### ISSUE THREAD

**Issue by craigcosmo** [electron/electron#6149]
* Electron version: 1.2.3
* Operating system: macOS

I followed the guy to install react dev toll by electron. Adding the addevtoolextrion, then run the app and git this error.

Here is code of main.js

```js
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;
let mainWindow;

function createWindow() {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        width: 1028,
        height: 768,
        transparent: false,
        titleBarStyle: 'show',
        frame: true
    });
    mainWindow.addDevToolsExtension('~/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/0.14.11_0');
    mainWindow.loadURL(`file://${__dirname}/dist/html/index.html`);
    mainWindow.webContents.openDevTools();
    mainWindow.on('closed', function() {
        mainWindow = null
    })
}
app.on('ready', createWindow);
app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
        app.quit()
    }
});
app.on('activate', function() {
    if (mainWindow === null) {
        createWindow()
    }
});
```

**Comment by kevinsawicki** [comment]
Extensions are installed on all windows, not on an individual window so you need to call `BrowserWindow. addDevToolsExtension` as a class method instead of `mainWindow.addDevToolsExtension` as an instance method.

Closing this out.

**Comment by craigcosmo** [comment]
Can you give an example?

**Comment by kevinsawicki** [comment]
> Can you give an example?

Sure:

```js
BrowserWindow.addDevToolsExtension('~/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/0.14.11_0');
```

**Comment by craigcosmo** [comment]
Thanks. Where would that code go to in my main.js?

**Comment by kevinsawicki** [comment]
> Where would that code go to in my main.js?

Anytime after `ready` fires on the `app`, so at the top of `createWindow` would work

**Comment by craigcosmo** [comment]
that's cool, big kiss

**Comment by 99755Ajay** [comment]
`BrowserWindow.addDevToolsExtension('/Users/ajay.NEUROSPEECH/AppData/Local/Library/Application Supoort/Google/Chrome/User Data/Default/Extensions/mboefdeomkdlbekljcecbfimmecffgje/1.85_0')
`
This is what my url is.
But I am getting the error
BrowserWindow.addDevToolsExtension is not a function.

Please help
