### ISSUE TITLE
Empty Buffer returned when calling `nativeImage.createFromBuffer` with scaleFactor != 1

### ISSUE THREAD

**Issue by atdrago** [electron/electron#6155]
- Electron version: 1.2.3
- Operating system: macOS 10.11.5

Passing a `scaleFactor` other than `1.0` to `nativeImage.createFromBuffer(buffer[, scaleFactor])` results in an empty Buffer.

Code:

``` javascript
const bounds = _window.getBounds();

_window.capturePage((image) => {
    const size = image.getSize();
    let buffer = image.toPng();

    // On high-pixel-density displays, window's bounds will be smaller
    // than the image's size.
    if (bounds.width < size.width) {
        const scaleFactor = bounds.width / size.width;

        // ** Resulting buffer is empty **
        buffer = nativeImage.createFromBuffer(buffer, scaleFactor).toPng(); 
    }

    fs.writeFile(`myImage.png`, buffer);
});
```

**Comment by mattgalvin** [comment]
Does anyone know a workaround to this issue? I'm working on a project where window capture is an integral piece of functionality and it's basically useless on retina display computers because of this bug.

**Comment by pronebird** [comment]
You should probably pass scale factor of your display? Do you have retina mac?

**Comment by sofianguy** [comment]
Thanks for contributing!

This is an old version that we are no longer releasing bug fixes for. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.
