### ISSUE TITLE
Using webview in BrowserWindow with nodeintegration disabled

### ISSUE THREAD

**Issue by chandrachivukula** [electron/electron#6157]
* Electron version: 1.2.2
* Operating system: Win/Mac

While reviewing the docs for [WebView](https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md), I ran into this statement and wanted to know why we cannot use webview in a browserwindow without nodeintegration enabled. I want to have a locked down BrowserWindow (nodeintegration: false) but also want to show some web sites (internet/intranet) in a webview so we can show the sites in a secure fashion (dont want to use iframes due to hijacks etc.)

> 
_For security purpose, webview can only be used in BrowserWindows that have nodeIntegration enabled._

**Comment by zcbenz** [comment]
You can choose to enable node integration, and then remove all node symbols except for `WebView` later, a similar example can be found at: http://electron.atom.io/docs/api/process/#event-loaded

**Comment by chandrachivukula** [comment]
Thanks for the info @zcbenz, however this comment on the [webview page](https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md#nodeintegration) is confusing. Does it mean I can use webview in my browserwindow (nodeintegration disabled) and have the webview inherit that setting automatically? I remember seeing a PR which make sure webview node integration inherits the BrowserWindow.

Could you please clarify?

> nodeintegration
> 
> <webview src="http://www.google.com/" nodeintegration></webview>
> If "on", the guest page in webview will have node integration and can use node APIs like require and process to access low level system resources.
> 
> Note: Node integration will always be disabled in the webview if it is disabled on the parent window.
>
