### ISSUE TITLE
Leveldb support

### ISSUE THREAD

**Issue by marcbachmann** [electron/electron#616]
Currently I'm using files & sqlite3 as storage.
Leveldb would be a nicer option as it's already embedded in chromium.
Is it possible that `brightray`, `libchromiumcontent` or `atom-shell` can expose a simple interface somewhere. That way it would be supported in all environments.
Or is it better to just use a node module?

**Comment by nlhkh** [comment]
This sounds like a stupid question but I could not find the answer else where. Is IndexedDB in Electron persistent through app restart? Under what circumstances will the data be wiped? Can I backup the data?
