### ISSUE TITLE
Parent and child windows not working

### ISSUE THREAD

**Issue by Vietnd34** [electron/electron#6162]
* Electron version:1.2.3
* Operating system:Mac Osx El Capitan 10.11.5

i try to make a child window follow guideline but not working.
`let child = new BrowserWindow({parent: top, modal: true, show: false})
child.loadURL('https://github.com')
child.once('ready-to-show', () => {
  child.show()
})`

i also can click on main window. could anybody help?

**Comment by enlight** [comment]
Did you build Electron from source? The parent/child API changes were only committed yesterday.

**Comment by Vietnd34** [comment]
I updated version 1.2.3 today. Maybe do i have mistake?

**Comment by zcbenz** [comment]
This feature has not been released yet, you will be able to use it in next release.

**Comment by Vietnd34** [comment]
yes. thanks!
