### ISSUE TITLE
Could you tell me why the webview occasionally crash on Windows

### ISSUE THREAD

**Issue by yumaogushi** [electron/electron#6163]
* Electron version: 1.2.x
* Operating system: win 10 x64

I develop on OS X 10.11.5, running on win 10 x64。

**Comment by jlord** [comment]
What are you doing before the crash happens?

**Comment by MarshallOfSound** [comment]
Minimum sample code that causes the crash?

Literally any information about the crash would be helpful 😆

**Comment by felixrieseberg** [comment]
We're using WebViews all the time (sometimes on Windows, we're Microsoft after all), but if there's something wrong, I'm happy to work on it.

**Comment by yumaogushi** [comment]
My program is a similar to chrome browser, seems to be a page open include some images will crash, especially when containing larger images.

I'm very sorry, my English is not very good, hope you can understand this.

**Comment by zcbenz** [comment]
Closing until more information is provided.
