### ISSUE TITLE
Can't load another ASAR from command line if app.asar is in the resources folder

### ISSUE THREAD

**Issue by baconface** [electron/electron#6167]
* Electron version: 1.2.3
* Operating system: Windows 8.1
* Issue: If app.asar is present in the resources folder the executable can no longer load a different ASAR via command line.

What we are looking to do have our main project in app.asar. But have it be able to download additional ASAR's if needed and launch from them. Ideally we would like multiple ASARs instead of multiple builds of Electron to reduce file size and so we only need to maintain one Electron install.

We wish to load them in something along the lines of:
```javascript
app.relaunch({
  args: 'resources/another_app.asar'
});
app.exit(0);
```
From our testing we have found the above works _only_ if there is no app.asar present. If there is it loads in app.asar by default. Without it the behavior works as expected.

**Comment by zcbenz** [comment]
The `resources/another_app.asar` is passed as command line parameter to your app, if you want to start from it you should restructure your app to behave like default app:
https://github.com/electron/electron/blob/master/default_app/main.js#L331

**Comment by baconface** [comment]
I don't understand your response.

My ASARs are structured like default apps. The problem is I purposely want multiple ASARs. So while we have a default app.asar that is the main program we wish to have multiple completely isolated programs. Ones we can launch using the same Electron build from our default app. (We don't care about starting up `resources/another_app.asar` as the default app.)

So what I am asking is shouldn't passing `resources/another_app.asar` as a command line parameter work if their is already an app.asar in your resources folder? For me this behavior doesn't work. And to me it doesn't make since it shouldn't.

**Comment by baconface** [comment]
Aside from what I am trying to do maybe this makes a little more since about the issue.

What I expect to work:
- Place `app.asar` in resources folder
- Place `another_app.asar` in resources folder
- Run executable and it loads `app.asar`
- Run executable with `another_app.asar` as a command line parameter and it loads `another_app.asar`

How it currently works:
- Place `app.asar` in resources folder
- Place `another_app.asar` in resources folder
- Run executable and it loads `app.asar`
- Run executable with `another_app.asar` as a command line parameter and it loads `app.asar`

From what I see this is broken behavior.

**Comment by zcbenz** [comment]
Whenever there is a `app.asar`, Electron will always load from it. A simple example is Atom editor, when you run `atom some_file`, Electron will still run Atom editor and use it to open `some_file`, instead of starting `some_file` as an app.

**Comment by baconface** [comment]
Ah, I see. So it thinks `another_app.asar` is a file you wish to open within `app.asar`. Makes sense.

So would there be a way to do what I want to achieve? Or is there a way we can programmatically allow an Electron app to reload a different ASAR instead of `app.asar` even if `app.asar` exists?

**Comment by zcbenz** [comment]
You can just call `require`, like what the default app did.

**Comment by baconface** [comment]
Wow, I was really overthinking this. I was able to achieve what I wanted to do with:
```javascript
win.loadURL(path.dirname(process.execPath) + '/resources/another_app.asar/index.html');
```
Thanks for clearing this up. I appreciate it.

**Comment by Anil8753** [comment]
> Wow, I was really overthinking this. I was able to achieve what I wanted to do with:
> 
> ```js
> win.loadURL(path.dirname(process.execPath) + '/resources/another_app.asar/index.html');
> ```
> 
> Thanks for clearing this up. I appreciate it.

Is it necessary to keep another_app.asar in the resources directory or it can be placed any where?
I am not able to load the index.html of another app from the asar.

**Comment by baconbrad** [comment]
@Anil8753 This is a bit dated so I am unsure if this method still works. But based off when it did work you could load it from anywhere as long as you fed it a proper location to index.html to `win.loadURL()`. For us at the time it made since to keep it in the same folder as all the other ASAR files. I can't verify if/how it works anymore because we merged everything into one ASAR and let Squirrel handle updates now.
