### ISSUE TITLE
webview ipc-message can not work in guest page ,because `require` is undefined

### ISSUE THREAD

**Issue by foolishchow** [electron/electron#6176]
```javascript
// In guest page.
var ipcRenderer = require('electron').ipcRenderer;
ipcRenderer.on('ping', function() {
  ipcRenderer.sendToHost('pong');
});
```

I was try to make a broswer with Electron ,  now I was working on Menu ,  I was trying to make a MenuItem to refresh iframe instead refresh whole page .  is there something wrong with my code ?

**Comment by kevinsawicki** [comment]
@foolishchow do you have the [nodeintegration](http://electron.atom.io/docs/api/web-view-tag/#nodeintegration) attribute set on your `<webview>` tag?

**Comment by foolishchow** [comment]
thanks , i have resolve the problem with `nodeintegration`
