### ISSUE TITLE
How to test electron autoUpdate

### ISSUE THREAD

**Issue by Feelnoobskill** [electron/electron#6177]
I'm trying to build auto-update mac application but I don't understand how to test everything.
My app.js:
```javascript
'use strict';
const {app, BrowserWindow, autoUpdater} = require('electron');
const appVersion = require('./package.json').version;

let mainWindow = null;


autoUpdater.setFeedURL('http://localhost:3000/updates/latest?v=' + appVersion);

autoUpdater.checkForUpdates();

autoUpdater.on('update-downloaded', function () {
    autoUpdater.quitAndInstall()
});

app.on('ready', function () {
    mainWindow = new BrowserWindow({width: 1500, height: 900, show: true});
})
```

I packed my app with ```electron-packager``` and created ```.dmg``` file with [appdmg](https://www.npmjs.com/package/appdmg) npm package.

Right now I want create 0.0.2 release version and update my app. I packed new ```.app``` application and placed it to my release-server, so whenever I start my installed app it send the request to ``` http://localhost:3000/updates/latest?v=0.0.1``` and I'm getting response ```{"url":"http://localhost:3000/updates/releases/darwin/0.0.3/MyApp.zip"}``` that means that new update available.
 [autoUpdater](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md) documentation says that update would be automatically downloaded and ```quitAndInstall``` method will install everything for me. But seems like something went wrong and my updates not installed. So maybe there are some tools to debug this process? 

UPD
I just found out that my updates are installed, but it takes too long time, but anyway is there any tool or tutorial to debug everything?
* Electron version: 1.0.0
* Operating system: OSX

**Comment by kevinsawicki** [comment]
> I just found out that my updates are installed, but it takes too long time

So it looks like this is no longer an issue then? It is working but just taking longer than expected?

If you open the Console app on Mac while your test is running, you should see update messages logged like:

```
6/22/16 9:53:43.669 AM Atom[82113]: Download completed to: file:///Users/kevin/Library/Application%20Support/com.github.atom.ShipIt/update.JLLR2vh/atom-mac.zip
```

Closing this out.

**Comment by gmcdev** [comment]
I'm also having trouble with auto-updater, when I check for updates, the electron.autoUpdater.error event gets fired with this message: `Error: Update check failed: (null)`

I've checked and re-checked my server setup, and I'm out of ideas -- what I really need is more information. How can I get more info out of the autoUpdater module and/or squirrel.mac?

The Console app was a great suggestion, but unfortunately, I'm not seeing any activity logged there...is there a switch I need to set in Electron or my shell?

**Comment by Feelnoobskill** [comment]
@kevinsawicki sorry for stupid question. But how can I open Console app? It would be great if you can share a link where I can read about it. Thanks

**Comment by gmcdev** [comment]
It's a Mac OSX app, `~/Applications/Utilities/Console`

**Comment by kevinsawicki** [comment]
@Feelnoobskill here is a screenshot where you can see the auto update events being logged:

<img width="1278" alt="screen shot 2016-06-22 at 12 00 22 pm" src="https://cloud.githubusercontent.com/assets/671378/16279677/f48c9f08-3870-11e6-9b2f-9560f0661c59.png">

**Comment by biroplane** [comment]
Hi, How did you create your server?
Do i need to make it with node (and deploying it to a node.js server) or can i make an endpoint on my own linux server?
did you find any example?
Thx

**Comment by Feelnoobskill** [comment]
@biroplane I used https://github.com/ArekSredzki/electron-release-server for deploying

**Comment by biroplane** [comment]
as a newbie, i've been trying with that, but i've never used postgresql. Once installed on my mac, it still throws me errors over errors :/
