### ISSUE TITLE
Error: ChromeDriver did not start within 5000ms

### ISSUE THREAD

**Issue by FranAguiar** [electron/electron#6179]
* electron-builder: "^4.2.6",
* electron-packager: "^7.0.3",
* electron-prebuilt: "^1.2.2",
* spectron: "^1.37.0"

* Operating system: linux

Hello I'm been fighting with this error for a few days, this is what I have and I don't know what I'm doing wrong.

```
"use strict";
require("co-mocha");
var Application = require('spectron').Application;
var assert = require('assert');

const webdriver = require('selenium-webdriver');

//const driver = new webdriver.WebDriver;
const driver = new webdriver.Builder()
  .usingServer('http://127.0.0.1:9515')
  .withCapabilities({
    chromeOptions: {
      binary: "./appPath/app"
    }
  })
  .forBrowser('electron')
  .build();

describe('Application launch', function () {
  this.timeout(100000);
  var app;
  beforeEach(function () {
    app = new Application({
      path: "./appPath/app"
    });
    return app.start();
  });

  afterEach(function () {
    if (app && app.isRunning()) {
      return app.stop();
    }
  });

  it('click a button', function* () {
    yield driver.sleep(5000);
    yield driver.findElement(webdriver.By.css(".classSelector")).click();
  });
});
```

Before that I start the chromedriver but I can't make it work. This is the console output:

> Application launch "before each" hook for "shows an initial window":
>      Error: ChromeDriver did not start within 5000ms
>       at Error (native)
>       at node_modules/spectron/lib/chrome-driver.js:58:25
>       at Request._callback (node_modules/spectron/lib/chrome-driver.js:116:45)
>       at Request.self.callback (node_modules/spectron/node_modules/request/request.js:200:22)
>       at Request.<anonymous> (node_modules/spectron/node_modules/request/request.js:1067:10)
>       at IncomingMessage.<anonymous> (node_modules/spectron/node_modules/request/request.js:988:12)
>       at endReadableNT (_stream_readable.js:913:12)
>       at _combinedTickCallback (internal/process/next_tick.js:74:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by kevinsawicki** [comment]
> const webdriver = require('selenium-webdriver');

Is there a particular reason you are using `selenium-webdriver`?

**Comment by FranAguiar** [comment]
No, is just a familiar way to e2e testing and simulate the user's behaviour.

If I can do the same without it and just with spectron, is fine for me. But I don't see how I can do it

**Comment by kevinsawicki** [comment]
I'm not sure using `selenium-webdriver` with `spectron` is currently supported.

Can you try just using spectron by itself?

Also the path to your application probably needs to be absolute, not relative (`"./appPath/app")`.

**Comment by FranAguiar** [comment]
Yes it's supported, I'm just following this tutorial:
https://github.com/electron/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md

**Comment by kevinsawicki** [comment]
> Yes it's supported, I'm just following this tutorial:

That tutorial shows using either, but not both together, so perhaps just try to use one and see if you can get it working then.

**Comment by kevinsawicki** [comment]
Closing this out for now, please feel free to open issues on the spectron repo if you hit problems using it
