### ISSUE TITLE
Question: Timed out error

### ISSUE THREAD

**Issue by ccnokes** [electron/electron#6188]
* Electron version: 0.37.8
* Operating system: OSX 

Note: This is a question, probably not an issue, about Electron.

My app loads our web app as a remote URL. When a user wakes their computer (on the powerMonitor.resume event) I refresh the page they're on. Occasionally, doing this causes loading the URL to fail with a -7 code (a system related error meaning "timed out"). Before I reload, I always first verify that our remote web app can be reached via an HTTP request from the main process. Despite that sometimes it fails with that -7 (and not -118, connected timed out, interestingly). 

Why could this be happening and how do you mitigate it? Is the "-7 TIMED_OUT" error related to network connectivity or is it something more internal to Chromium?

**Comment by zcbenz** [comment]
I think this is a internal bug of Chromium, since Electron just uses it to load pages. Maybe you can try whether newer versions of Electron still have this problem.

**Comment by zcbenz** [comment]
Closing until more information is provided.
