### ISSUE TITLE
Question: how to uninstall electron prebuilt from CLI ? 

### ISSUE THREAD

**Issue by c1ngular** [electron/electron#6193]
* Electron version:
* Operating system:
i have tried the install command to force reinstall , but failed !(Error: read ETIMEDOUT)

**Comment by mnquintana** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Electron message board](https://discuss.atom.io/c/electron) or the [Electron Slack channel](http://atom-slack.herokuapp.com/) is where you'll probably be able to find answers faster.

**Comment by c1ngular** [comment]
@mnquintana sorry!
