### ISSUE TITLE
how to package with native module?

### ISSUE THREAD

**Issue by phevose** [electron/electron#6194]
I used electron with sequelize & sqlite3 to my app,i already rebuild sqlite3 in node_modules,now i want publish the app,but the node_modules to large,the sqlite3 over to 30M,and many other modules.so how to minimize the dependency modules for package?
* Electron version:1.2.4
* Operating system:win10 x64

**Comment by mnquintana** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Electron message board](https://discuss.atom.io/c/electron) or the [Electron Slack channel](http://atom-slack.herokuapp.com/) is where you'll probably be able to find answers faster.

**Comment by phevose** [comment]
@mnquintana i can't open whole page with https://discuss.atom.io/c/electron and atomio.slack.com, because some domain is blocked by government,so github is my only hope now.please!
