### ISSUE TITLE
It's set taskbar invalid

### ISSUE THREAD

**Issue by kirakiray** [electron/electron#6196]
* Electron version:1.2.4
* Operating system:Win10x64, Win7x64

It's use `win.setSkipTaskbar(false)` invalid,It will still be display window in the taskbar

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by kirakiray** [comment]
When I am ready to write a small program to you, I found that `win.setSkipTaskbar(true)` is the effect I want,There is a problem with the Chinese translation of the document.
Thank you very much for the Electron.
