### ISSUE TITLE
Built Electron app I made wont run on other Linux PC's

### ISSUE THREAD

**Issue by gameslayer** [electron/electron#6199]
Hi I need some help I built a Application that works fine on my desktop and built it for all platforms but was testing the Linux 64bit version I made on my notebook that also runs Xubuntu 14.04 64bit but when I open it all that I get is a blank page on my application instead of what suppose to come up. is there dependencies or something needing to be installed to make the app I made run?

Electron v0.35.6

**Comment by zcbenz** [comment]
Can you try whether newer versions work?  v0.35.6 is too old, and we had fixed issues with some Linux distributions in later versions.

**Comment by gameslayer** [comment]
I tired using a new version and now my application will not run and gives me fragmented error, I had to remove and change some stuff to make it work with the newest version but I still am stuck on that error. I agree it is old the only reason of that is because I got it when electron started and been on and off learning and got onto it a lot more and finally built some applications after testing them with npm start command.

**Comment by zcbenz** [comment]
The v1.2.4 had some crashing problems on Linux, and v1.2.5 should be working.

**Comment by gameslayer** [comment]
alright ill try v1.2.4 and report back

**Comment by gameslayer** [comment]
I tired the newest version and got a javascript error about it missing module NativeImage, I tried removing it but than it wouldn't run 

Uncaught Exception:
/home/corey/stuff/apps/built-apps/Google-Play-Music/GooglePlayMusic-linux-x64/resources/app/main.js:23
  mainWindow = new BrowserWindow ({'width':1200,'height':900,)});
                                                             ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Object.<anonymous> (/home/corey/stuff/apps/built-apps/Google-Play-Music/GooglePlayMusic-linux-x64/resources/electron.asar/browser/init.js:183:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)

**Comment by zcbenz** [comment]
As the error says, it is a syntax error in your code.

**Comment by gameslayer** [comment]
i've fixed some stuff but stuck on this error and don't know how to fix it.

Uncaught Exception:
TypeError: Cannot read property 'on' of null
    at EventEmitter.<anonymous> (/home/corey/stuff/apps/built-apps/Google-Play-Music/GooglePlayMusic-linux-x64/resources/app/main.js:28:13)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)

**Comment by zcbenz** [comment]
For questions on writing apps, I suggest seeking help from [the community](https://github.com/electron/electron#community). The issues list is only for bug reports and feature requests.

**Comment by gameslayer** [comment]
Issue was solved using the newest version I'll just have to fix my code.
