### ISSUE TITLE
Detect if application is hidden on launch

### ISSUE THREAD

**Issue by sam-jay** [electron/electron#6202]
* Electron version: 1.2.3
* Operating system: OSX 10.11.3

On OSX there is an option to hide an application that's launched automatically on login ```Users & Groups > Login Items```. Electron app does not respect this option and displays the main renderer window when launched at login. 

Is there a way to detect either
- that the app was launched at login, or
- that the app was hidden at launch

?

**Comment by zcbenz** [comment]
Currently there is no API to do that, but should be easy to add.

Refs https://cs.chromium.org/chromium/src/base/mac/mac_util.h?sq=package:chromium&dr=C.

**Comment by sam-jay** [comment]
Where should it be added?

**Comment by zcbenz** [comment]
Probably just the `app` module.
