### ISSUE TITLE
Modules loaded as CommonJS/nodeJS when expecting Regular Browser behaviour

### ISSUE THREAD

**Issue by aaroncalderon** [electron/electron#6204]
# Background

* Electron version: 1.2.x
* Operating system: Windows 7 x32
* I run my app SPA (single page app) with the `file://` protocol. 

# Issue

I have found some issues when loading modules that use a `Universal Module Definition` loader technique; some libraries get loaded with the `CommonJS/nodeJS loader` code block when a `Regular Browser` (no loader) behaviour is expected.

Say if you load/include a javascript library/file with the `<script>` tag, but the UML code block evaluates to be loaded as `CommonJS/nodejs`.

Thus, braking other components that depend on a global/window instance of the module that was loaded. 

I have had this issue specifically with [`showdown.js`](https://github.com/showdownjs/showdown/issues/269) when trying to use it with AngularJS and `angular-markdown-filter`. Please note that this library does not use any of the specific methods referenced in the [UML](https://github.com/umdjs/umd) repository. The UML link is only for reference.

# UML at fault?

Is the issue with the UMD method used by the library mantainer? 

The UMD methods seem pretty common, so since that is kind of the norm, is there something electron can do to address this?

I tryed to create the BrowserWindow witht the ~~`'node-integration': false` parameter but it made no difference~~ `nodeIntegration: false` and behaviour was as expected, but (_see comment below_)...

Any ideas?

# Update

see the [electron-uml-issue](https://github.com/aaroncalderon/ea-todo/tree/electron-uml-issue) repo to reproduce issue

**Comment by kevinsawicki** [comment]
> I tryed to create the BrowserWindow witht the 'node-integration': false parameter but it made no difference.

This probably needs to be `nodeIntegration`, not `node-integration`.

**Comment by aaroncalderon** [comment]
@kevinsawicki You are right, I tryed with 'nodeIntegration: false` and hell broke lose. 

I do depend on `nodeIntegration` on my current app. I created the branch [electron-uml-issue-node-int-off](https://github.com/aaroncalderon/ea-todo/tree/electron-uml-issue-node-int-off) to test the behaviour of the renderer process, and indeed it now works as expected. But, we face the dilema that I rely on `nodeIntegratin` functionality and cannot turn it off.

Besides rewriting the whole application to work with `nodeIntegration: false` does anyone have any ideas?

Thanks

**Comment by kevinsawicki** [comment]
> Besides rewriting the whole application to work with nodeIntegration: false does anyone have any ideas?

You might want to use the `preload` option in `BrowserWindow` to tweak the global variables so that modules your page pulls in detect it as browser instead of a nodejs env.

You might want to see https://github.com/electron/electron/issues/254 which has information about this regarding jQuery which exhibits this issue.

Closing this out.

**Comment by aaroncalderon** [comment]
@kevinsawicki Oh, man, you read my mind.

Thanks for the input.

**Comment by AlifArnado** [comment]
I'll call javascript that's in directory using elctron

    <script>window.$ = window.jQuery = require('asset/bootstrap/dist/js/bootstrap.min.js');</script>
    <script>window.$ = window.jQuery = require('asset/js/wow.min.js');</script>
    <script>window.$ = window.jQuery = require('asset/js/script.js');</script>
i have used that tecnic, but it was fail, how can i solve that's problem?

**Comment by aaroncalderon** [comment]
@AlifArnado Follow __kevinsawicki__'s https://github.com/electron/electron/issues/6204#issuecomment-228392185 suggestion. You do need to account for all the integrations your app will need on the preload script.
