### ISSUE TITLE
setting the app's icon for linux is very quirky

### ISSUE THREAD

**Issue by Autre31415** [electron/electron#6205]
* Electron version: 1.1.2+
* Operating system: ubuntu 16.04

I've seen a lot of closed issues about icons not properly working in ubuntu and I've spent a great deal of time trying to figure out exactly what's going on. This is the fruit of that effort, which should hopefully disprove the requirement for a .desktop file to make icons work in ubuntu:

I've packaged apps in each version of Electron past 1.0 and discovered the icon issue appears in 1.1.2 and onward.

In any version of Electron prior to 1.1.2 it's possible to set any png as your icon and have it display in the Unity dock using this method:

```
let win = new BrowserWindow ({ icon: __dirname + '/path/to/icon.png' });
```
But once you move into 1.1.2+ territory the icon will not display. There have been a few past issues opened on this and they were closed when it was mentioned a .desktop file is required, but I've discovered that it is possible to still display an icon under specific conditions. (This is where things get quirky)

I tested a few different icons, with different file names, file sizes and resolutions and discovered that the icon will display in ubuntu if:

1. The filename is icon.png (I've tried other file names and it would break, but perhaps others work)
2. The image is 128x128 or less (Sometimes 256x256 works, but in most cases it doesn't)

I can't really explain how or why this is the case but it's definitely quirky.

Looking at the changelog for 1.1.2 I noticed there are some tweaks to icons, so I can imagine it was something there.

Also of note, this was without using nativeImage. I wasn't able to get icons working as native images in 1.1.2+ either.

Hopefully this information will be helpful in resolving the issue, and for now at least 128x128 icons will work in ubuntu without any substantial tweaks to the development or build process.

**Comment by zcbenz** [comment]
Thanks for locating the starter version of wrong behavior, it might be related to #5624.

**Comment by webarchymeta** [comment]
I am having the same issues, thanks for the tips ...

**Comment by hugolpz** [comment]
Same issue on ubuntu 16.04, for the reccord.

**Comment by galusben** [comment]
Hi, 
I have tried the above 2 requirements and it still did not work.
I am packaging on mac with electron-forge. Do you think it is related?

**Comment by avilapedro** [comment]
Hi, thank you!

- OS
  deepin 15.4.1
- Electron
  1.7.6

Converting to 128x128 worked just fine, it also worked with other file names and using nativeImage.

**Comment by galusben** [comment]
Hi, packaging on ubuntu virtual machine and inside an ubuntu docker container have helped. 

My conclusion is to pack on the target platform. 
Thanks!

**Comment by YuhApps** [comment]
It does not work with me, either. The default electron icon is always shown.

**Comment by challenger532** [comment]
I'm packing on Ubuntu, It didn't work, I got those logs from the ```/var/logs/syslog``` file

 ```22091 Jan 10 13:26:37 challenger org.gnome.Photos[1885]: (gnome-photos:9436): GLib-GIO-CRITICAL **: g_file_new_for_path: assertion 'path != NULL' failed
22092 Jan 10 13:26:37 challenger org.gnome.Photos[1885]: (gnome-photos:9436): GLib-GIO-CRITICAL **: g_file_icon_new: assertion 'G_IS_FILE (file)' failed````

**Comment by YuhApps** [comment]
Okay. I have the problem solved.

First of all, while you run the project in developer mode, I mean you call "$ electron ." from Terminal or Command Prompt, the app icon might not be used. If you desperately need the app icon in your Dock/Taskbar, try to call the electron excutable file from "node_modules" folder of your project.

To have your app icon applied in the built app, you can follow my steps:
1. You need electron-builder (https://github.com/electron-userland/electron-builder).
2. Create a folder named "build" in your project folder and put your app icons for different operating systems there with the name "icon": "icon.icns", "icon.ico", "icon.png".
3. Build your app using electron-builder. App icon will be there for sure.
