### ISSUE TITLE
uv_idle/check/prepare fail to function in C++ addon when loaded by Electron App

### ISSUE THREAD

**Issue by gschmottlach** [electron/electron#6208]
- Electron version: electron-prebuilt v 0.36.7
- Operating system: Ubuntu 14.04 (also seen on Windows 7)

I have a Node.js C++ addon module which uses the primitive libuv functions uv_idle/check/prepare to schedule a function to be called on the next main-loop tick. The code looks something like this:

```
void onHandleClose(uv_handle_t* hnd)
{
  delete hnd;
}

void onCallback(uv_prepare_t* hnd)
{
  printf("onCallback called.\n");
  uv_prepare_stop(hnd);
  uv_close((uv_handle_t*)hnd, onHandleClose);
}

void scheduleCallback()
{
  int rc;
  uv_prepare_t* hnd = new uv_prepare_t();
  rc = uv_prepare_init(uv_default_loop(), hnd);
  assert( rc == 0 );

  rc = uv_prepare_start(hnd, onCallback);
  assert(rc == 0 );
}
```

At some point a button click on the Electron app will trigger a call into the C++ addon function 'scheduleCallback'. Under Node.js this code works as expected (for uv_prepare/uv_check/uv_idle etc...). The 'onCallback' function is executed as expected. When the addon is loaded by Electron,  this callback code does **not** execute although 'scheduleCallback' is called and all return codes are zero (0). As a last resort, I switched to using the uv_async mechanism that can be used to call a callback on the uv_default_loop thread. Using uv_async_send() I was able to get the 'onCallback' function to execute under Electron. I thought perhaps the 'scheduleCallback' function was being executed from a different thread but printing pthread_self() in both functions (scheduleCallback/onCallback) indicates they are both running in the same thread. So, I cannot reconcile why the C++ addon works properly under Node.js with uv_prepare/uv_check/uv_idle/uv_async but fails (except for uv_async) under Electron. Can anyone suggest an explanation for this behavior?

Any insights would be appreciated . . .

**Comment by zcbenz** [comment]
It seems like a bug of Electron's node integration.

**Comment by gschmottlach** [comment]
So, what do you anticipate being the next step? Unfortunately, it is difficult for me to move forward to a new Electron release to see if this issue has already been addressed due to some incompatibilities we've encountered making the transition from electron-prebuilt v 0.36.7 to the latest release. I was just wondering if anyone has seen the same behavior as I observed. Also, I'm new to the structure/layout of the Electron code-base. Can you point me to the file where the node-integration occurs and where you believe the problem might exists?

Thanks for the help . . .

**Comment by gschmottlach** [comment]
I managed to update my application to Electron 1.2.5 prebuilt (Node.js 6.1.0) and can confirm that this bug exists in that version as well.

**Comment by nmoinvaz** [comment]
I have also encountered the same issue. With Electron, uv_idle/uv_prepare do not work inside of a native node module. When loading the same native node module with NodeJS they do work. I am able to get around the issue by using uv_async to call code on the default loop as the author of this bug suggests.

**Comment by codebytere** [comment]
closing due to abandonment.

**Comment by nmoinvaz** [comment]
I think this should remain open since the bug still exists.

**Comment by codebytere** [comment]
alright, that's totally fine! we're just weeding out the old dead ones at the moment :)

**Comment by codebytere** [comment]
@nmoinvaz does this occur on `2.0.0`?

**Comment by nmoinvaz** [comment]
Yes

**Comment by codebytere** [comment]
Given that this will be expensive and somewhat complex to fix, and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!

**Comment by leozzyzheng** [comment]
It still exist in 5.0.2... and the workaround is call process.activateUvLoop() in js to active the event loop of uv library.
