### ISSUE TITLE
`cookies.set` doesn't allow you to use value of > 256 in length

### ISSUE THREAD

**Issue by aaronfrost** [electron/electron#6209]
* Electron version: 1.2.4
* Operating system: OSX

I have been dorking around with cookies for a few days now. For the site I am working with, we use JWTs for our session. We stick the encoded token in a cookie. That JWT sometimes will range in length from 250 chars to 270 chars, depending on the variable data in the JWT. When the server responds with a value that has a length larger then 256, everything works. However, when I use the `webContents.session.cookies.set` API to set a value > 256 in length, it fails. It will let me set a cookie with a value from 0 - 256 in length. But, if I try to set a value that is 257 in length or higher, it fails. The only error I get is "Error: failed". 

Because the browser natively allows the server to set a value that is larger than 256 in length, I would like to see Electron also allow me to set a value that is larger than 256 in length. 

Do you need more info on my issue?

**Comment by zcbenz** [comment]
I tried to inject following code to quick start, and it seems to work fine?

```js
  mainWindow.webContents.session.cookies.set({
    url: 'http://www.google.com',
    name: 'name',
    value: 'value'.repeat(100)
  }, (error) => console.log(error))
  mainWindow.loadURL('http://www.google.com')
```

**Comment by aaronfrost** [comment]
Let me try to investigate what the diff is between your sample here, and what I am trying to do. I have it isolated so that if the cookie is <= 256, it works, but not if larger. I will investigate and then return and report.

**Comment by aaronfrost** [comment]
OK. So... if I set the cookie to `"hello".repeat(1000)` it works. If I set it to the base64 encoded string that I have, it doesn't work. I am out of ideas. Will keep trying and let you know.

**Comment by aaronfrost** [comment]
Sorry! It turns out that the value of the cookie I was trying to set ended in a linebreak. This caused the error. Would be nice to have had some better feedback than "Error: failed". Either way... thanks @zcbenz  for giving me the determination to keep going.

**Comment by kevinsawicki** [comment]
> Would be nice to have had some better feedback than "Error: failed". 

Unfortunately the `CookieMonster::SetCanonicalCookie` in Chromium returns a boolean and does not provide more details on failures when they occur.

https://cs.chromium.org/chromium/src/net/cookies/cookie_monster.h?l=519

Closing this out, I will update the error message to at least be something more like "Setting cookie failed", instead of just "failed".
