### ISSUE TITLE
IPC reliablity

### ISSUE THREAD

**Issue by lasryaric** [electron/electron#6215]
* Electron version: 1.2.5
* Operating system: Mac OS X el capitan

When sending IPC messages between the renderer and the main process, I think we sometimes get duplicate messages.

What kind of reliability is ensured by Electron? Should we handle de-duplication ourselves in the case of the same messages being re-sent?

I don't know if that's the right place for that question but I tried to post it on the discussion forum of Electron a few days ago and nobody answered so I am trying here.

Thanks

**Comment by MarshallOfSound** [comment]
@lasryaric 

>What kind of reliability is ensured by Electron?  Should we handle de-duplication ourselves in the case of the same messages being re-sent?

Electron won't send duplicate messages or re-send a message unless you tell it to.  So yes, if you are sending the same message twice, you need to handle that message twice.

**Comment by zcbenz** [comment]
Closing until more information is provided.
