### ISSUE TITLE
Enter causes window to reload?

### ISSUE THREAD

**Issue by Jom4nJi** [electron/electron#6217]
* Electron version: 1.2.3
* Operating system: Mac OS X 10.11.5
 
I've noticed that pressing the enter / return key while in a text field causes the window (not the app) to reload. This only happens one time per app launch, once it has happened once, it doesn't repeat. (until the next time you launch the app).

**Comment by MarshallOfSound** [comment]
FWIW can't replicate on Windows.  Do you have any sample code that causes the issue?

**Comment by Jom4nJi** [comment]
I'm using mdl's textfield like this:
    `<!-- Simple Textfield -->`
    ` <form action="#">`
      `<div class="mdl-textfield mdl-js-textfield">`
        `<input class="mdl-textfield__input" type="text" id="sample1">`
        `<label class="mdl-textfield__label" for="sample1">Text...</label>`
     ` </div>`
    `</form>`
Can you see the issue? Exactly, the form has a `#` action. Which causes the page to redirect to itself. Weirdly tho, I can't replicate the issue on my webserver, however, I now know that the `<form>` was the issue. I'm sorry for being uninformed and for waisting everyone's time.
