### ISSUE TITLE
Is there any official electron application style guide?

### ISSUE THREAD

**Issue by adriatic** [electron/electron#6219]
The title says it all - most developers I talk to treat electron as if it is a web application and try to apply design ideas like "mobile first", typical web app reaction on resize events etc,

**Comment by kevinsawicki** [comment]
There isn't one currently, it would be great to have a guide or sample stylesheet that adds some recommended native resets (like removing link underlining on hover).

There is this great video by @bengotow that includes some really helpful details about applying native styles: https://www.youtube.com/watch?v=JIRXVGVPzn8

**Comment by adriatic** [comment]
Thanks, Kevin - this video seems great (only watched few first minutes), so I will definitively use it. Given the fact that we are opening a completely new world of development tools for [aurelia](http://aurelia.io/) community using electron, I am hoping to get more hints from you :-)

**Comment by felixrieseberg** [comment]
It's not a bad idea. I'd be happy to take a look at our best-in-class Electron apps to collect some smart CSS basics.

**Comment by adriatic** [comment]
Maybe I managed to initiate a "movement" that could help many. As I am a direct beneficiary of this, I will do all I can to encourage, criticize and applaud to any information that might be created

**Comment by upicik** [comment]
@adriatic I'd really like to help you in this, if it is still open issue

**Comment by adriatic** [comment]
@upicik while this is still open issue, you should realize, only two people responded with interest in 8 months since this issue was created. I am already leading two projects with one or two team members and simply to not have the time for another such effort 😏

**Comment by aredfox** [comment]
I think it is needed, but it also depends on the technologies involved in your electron app..
e.g. angular + electron, react + electron etc..
this complicates things, and the styleguide as such should be agnostic to the specifics of the other tech-styleguides I think...
