### ISSUE TITLE
Incorrect size when maximized frameless window 

### ISSUE THREAD

**Issue by f111fei** [electron/electron#6223]
* Electron version: 1.2.1
* Operating system: windows 7

Steps to Reproduce:

1. Download  https://github.com/f111fei/test-files/raw/master/electron/frameless-window.zip

2. run `electron .`

3. My window resolution is `1920 * 1080`. But this window is
```
Current Window Size is: 
width = 1924
height = 1052
```

`width > 1920`  is an incorrect size.

**Comment by zcbenz** [comment]
I'm merging this to #5267.
