### ISSUE TITLE
Problem with Auto update on OSX 

### ISSUE THREAD

**Issue by epezhman** [electron/electron#6224]
* Electron version: 1.2.5
* Operating system: OSX El Capitan

 Hey, I'm trying to implement auto update on my app, it's working fine on Windows but on OSX I get `Update Check Failed`. here is my code:

```
var initDarwinWin32 = () => {

    if (process.platform === 'darwin') {
        feedURL = config.AUTO_UPDATE_OSX_BASE_URL
    }
    else if (process.platform === 'win32') {
        feedURL = config.AUTO_UPDATE_WIN_BASE_URL + (os.arch() === 'x64' ? '64' : '32')
    }

    autoUpdater.on(
        'error',
        (err) => log.error(`Update error: ${err.message}`)
    )

    autoUpdater.on(
        'checking-for-update',
        () => log('Checking for update')
    )

    autoUpdater.on(
        'update-available',
        () => log('Update available')
    )

    autoUpdater.on(
        'update-not-available',
        () => log('Update not available')
    )

    autoUpdater.on(
        'update-downloaded',
        (e, notes, name, date, url) => log(`Update downloaded: ${name}: ${url}`)
    )

    feedURL += '?v=' + config.APP_VERSION
    autoUpdater.setFeedURL(feedURL)
    autoUpdater.checkForUpdates()
}

```
The  `feedURL` is like `http://188.166.160.83/update_server/updates/latest/osx?v=0.1.14` and the server response is `{"url":"https://s3.eu-central-1.amazonaws.com/demand-manager-resources/updates/latest/osx/TUM Demand Manager-0.1.15-mac.zip"}` , I used the `electron-builder v5.7.0` to build and sign the code and I don't get any errors withcode signing, where do you think the problem is? thanks

**Comment by kevinsawicki** [comment]
Can you provide more details about the error you are getting?

Is the `autoUpdater` `error` event firing and can you provide the stack trace for it?

You might also want to look at the Console.app on Mac since it will log out update events there as well:

<img width="1278" alt="screen shot 2016-06-22 at 12 00 22 pm" src="https://cloud.githubusercontent.com/assets/671378/16344301/cbbfeb9e-39f0-11e6-8be5-267a24d08416.png">

**Comment by epezhman** [comment]
Thanks for the response, 
I have problem getting the detailed stack trace info, with `error.stack` all I get is this : 
```
Error: Update check failed
    at Error (native)
```
and with `console.trace()` I get: 

```
Error
    at EventEmitter.autoUpdater.on (/Users/epezhman/Desktop/Thesis/demand-manager-app/dist/mac/TUM Demand Manager.app/Contents/Resources/app/main/updater.js:78:21)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

my Console.app on Mac also contains this log (TUM Demand Manager is my app):

```
6/27/16 11:27:18.000 AM kernel[0]: gfx: surf 11a2bbf: SetIDMode: id=298084518 mode=0x24
6/27/16 11:27:18.000 AM kernel[0]: gfx: surf 11a2bbf: clientClose: 
6/27/16 11:27:19.845 AM TUM Demand Manager Helper[2353]: <<<< VTVideoEncoderSelection >>>> VTSelectAndCreateVideoEncoderInstanceInternal: no video encoder found for 'avc1'
6/27/16 11:27:19.846 AM TUM Demand Manager Helper[2353]: [11:27:19.845] VTSelectAndCreateVideoEncoderInstanceInternal signalled err=-12908 (err) (Video encoder not available) at /Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-1731.15.204/Sources/VideoToolbox/VTVideoEncoderSelection.c line 1308
6/27/16 11:27:19.846 AM TUM Demand Manager Helper[2353]: [11:27:19.846] VTCompressionSessionCreate signalled err=-12908 (err) (Could not select and open encoder instance) at /Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-1731.15.204/Sources/VideoToolbox/VTCompressionSession.c line 1003
6/27/16 11:27:19.000 AM kernel[0]: gfx: surf fffffffffdb1bdbf: SetIDMode: id=277354839 mode=0x24
6/27/16 11:27:19.000 AM kernel[0]: gfx: surf fffffffffdb1bdbf: clientClose: 
6/27/16 11:27:19.938 AM TUM Demand Manager[2352]: CVCGDisplayLink::setCurrentDisplay didn't find a valid display - falling back to 60Hz
6/27/16 11:27:20.000 AM kernel[0]: gfx: surf 1220fbf: SetIDMode: id=276569001 mode=0x24
6/27/16 11:27:20.000 AM kernel[0]: gfx: surf 1220fbf: clientClose: 

```
BTW since I'm working on PC I'm using the OS X El Capitan on VMware Workstation 12 Player

**Comment by kevinsawicki** [comment]
> I have problem getting the detailed stack trace info, with error.stack all I get is this :

Does the error have a `message`?

**Comment by kevinsawicki** [comment]
That message appears to be when your server returns a non-200 response:

https://github.com/Squirrel/Squirrel.Mac/blob/e9e2188cda3efb4bc08b1719bdef71880f9dc9b1/Squirrel/SQRLUpdater.m#L186

What is the server response you are sending?

**Comment by kevinsawicki** [comment]
Closing this out here since it is also over on https://github.com/Squirrel/Squirrel.Mac/issues/179
