### ISSUE TITLE
Webview preload script can't inject jquery

### ISSUE THREAD

**Issue by Sjael** [electron/electron#6230]
* Electron version: 1.2.4
* Operating system:Windows 10

I get and error of `Unable to load preload script` in the webviews DevTools pointing to `\node_modules\electron-prebuilt\dist\resources\electron.asar\renderer\init.js:130`

The page still loads, however.

When I remove the line `window.$ = window.jQuery = require('./jquery.min.js')` and all the depending jquery code, the errors are gone.

**Comment by kevinsawicki** [comment]
> I get and error of Unable to load preload script in the webviews DevTools pointing to \node_modules\electron-prebuilt\dist\resources\electron.asar\renderer\init.js:130

Is there a stack trace or message printed out after this message that you can include here?

**Comment by Sjael** [comment]
I forgot, the other error is: `TypeError: Cannot read property 'createElement' of undefined` pointing at `\node_modules\electron-prebuilt\dist\resources\electron.asar\renderer\init.js:131`

It goes on to throw:

```
    at ia (jquery.min.js:2:7251)
    at jquery.min.js:2:22006
    at jquery.min.js:2:22707
    at c (jquery.min.js:2:99)
    at Object.<anonymous> (jquery.min.js:2:212)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

Also, this is all resolved if I revert to my previous electron version 1.1.1

**Comment by kevinsawicki** [comment]
@Sjael can you include the contents of your `preload` script and the options you are passing to `new BrowserWindow`? Thanks.

**Comment by Sjael** [comment]
```
var electron = require('electron');
var shell = electron.shell;
var ipc = electron.ipcRenderer;

//inject jquery to page
window.$ = window.jQuery = require('./bootstrap/jquery.min.js');

// page data that is sent to host process
$(window).load(function() {
  console.log("loaded");
  var docData = {
    url: window.location.href,
    title: document.title,
    domain: document.domain,
  };

  setTimeout(function(){
    ipc.sendToHost("startLoad", docData);
  }, 1000);
});


function to open IN the program)
$(document).on('click', 'a[href]', function(event) {
  event.preventDefault();
  shell.openExternal(this.href);
});

```

There's the preload script. If I remove everything except the first 3 lines, it works fine.

```
  mainWindow = new BrowserWindow({
    width: 1600,
    height: 800,
    minWidth: 800,
    minHeight: 600,
    titleBarStyle: 'hidden',
    frame : false,
    webPreferences: {
    'plugins': true
    }
  });
```

And there's my BrowserWindow from my main process.

**Comment by MarshallOfSound** [comment]
jQuery attempts to hook into things on the document object.  In this case I believe `document.createElement`, I didn't think the document object was available in the preload script?

Try this script (it does the save thing)

```js
var electron = require('electron');
var shell = electron.shell;
var ipc = electron.ipcRenderer;

window.addEventListener('load', ()  => {
  //inject jquery to page
  window.$ = window.jQuery = require('./bootstrap/jquery.min.js');

  console.log("loaded");
  var docData = {
    url: window.location.href,
    title: document.title,
    domain: document.domain,
  };

  setTimeout(function(){
    ipc.sendToHost("startLoad", docData);
  }, 1000);

  $(document).on('click', 'a[href]', function(event) {
    event.preventDefault();
    shell.openExternal(this.href);
  });
});
```

**Comment by zcbenz** [comment]
Closing since the original question seems to have been solved.

**Comment by DarkSynx** [comment]
https://github.com/electron/electron/issues/21437#issuecomment-1478235645
