### ISSUE TITLE
Show menu bar when app is not in the dock (OSX)

### ISSUE THREAD

**Issue by rafajaques** [electron/electron#6231]
I know that this is the default in OSX system, but I just want to know if there are any way to show menu bar for the application even if it's not in the dock.

I ask that because I'm developing a tray application and I want to use some of the top menu bar functions.

If that's not possible, I'll try to figure out another way.
Thanks in advance!

**Comment by zeke** [comment]
You may want to check out https://github.com/maxogden/menubar, which enables you to create applications that work entirely from the menubar, without a dock icon.

**Comment by rafajaques** [comment]
That's not exactly what I meant. 
I need to enable the menu bar even if the application is not in the dock.

**Comment by zeke** [comment]
Can you elaborate on what you mean by "enable the menu bar"?

**Comment by MarshallOfSound** [comment]
@zeke I believe he means the application menu, I.e. the "File", "Edit", "Window" style menu that is associated with open windows / applications on OS X.

I believe the answer is no :laughing:

**Comment by rafajaques** [comment]
Yes. This is it. 
I thought that was not possible, but decided to ask.

**Comment by MarshallOfSound** [comment]
@rafajaques That menu only appears when a window of your application has focus.  You could technically trick OS X into thinking your window was in focus by making a frameless, transparent 1x1 window when you want that menu to appear.  But that is both hacky and bad practice.

Up to you though :laughing:

**Comment by zcbenz** [comment]
On OS X the application menu is tied to the dock icon, the app has to have a dock icon to be able to show application menu, there is no way to work around this.

I'm closing this issue since it is impossible.
