### ISSUE TITLE
Cannot find module shell

### ISSUE THREAD

**Issue by kunkinkan** [electron/electron#6234]
So I define electron at the top of my code: 

`const electron         = require("electron");
`

Then, I use electron.shell somewhere in the code, as this: 

`electron.shell.openExternal("http://google.com");
`
It will crash, claiming "Cannot find module shell".

However, when I add this statement to the top, below the const electron;

`const shell    = electron.shell;
`
And adjust the previous statement to 

`shell.openExternal("http://google.com");
`
Everything works just fine and dandy.

Why is that? Is that normal?

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by zcbenz** [comment]
Closing until more information is provided.
