### ISSUE TITLE
Remove the OS X 10.10+ limitation for using titleBarStyle window option

### ISSUE THREAD

**Issue by miniak** [electron/electron#6236]
* Electron version: 1.2.5
* Operating system: OS X 10.9.5

As the NSBorderlessWindowMask is not being used to implement frameless windows on OS X, but rather making sure that the webview covers the whole window, it should be possible to implement at least  titleBarStyle: 'hidden' by not hiding the standard window buttons and z-ordering them on top of the webview. Hidden-inset could be achieved by repositioning the standard window buttons.

**Comment by zcbenz** [comment]
It is very hard to correctly implement repositioning window buttons, I don't think it deserves the efforts to just make `hidden-inset` work on an old OS X version.

For making `titleBarStyle: 'hidden'` work, it should be straightforward.

**Comment by zcbenz** [comment]
After looking int this, the same code we used for 10.10+ does not work for 10.9, so this is a operating system limitation that we can not overcome, so I'm closing this as won't fix.
