### ISSUE TITLE
Electron Async/Promise Error Handling And Stack Traces

### ISSUE THREAD

**Issue by francoislaberge** [electron/electron#6237]
* Electron version:
1.0.0+
* Operating system:
OSX/Mac

hey all,

I've been trying to improve our logging/stack traces, and error handling best practices in Electron. I thought I had a handle on getting async stack traces using longjohn (when running in pure node) and just using the 'Async' flag when running in a renderer process. But when you want promises to give you async stack traces and have everything working in concert it's starting to make my head spin with all the choices and considerations.

What kind of tooling do you guys use. Do you tend to stay away from Promises, any recommendations on a library that would get you async stack traces for Promises and any other classic async code, ensuring that the stack traced files/functions are clickable in the console and jump to the original source (not transpiled versions).

I scheduled 2 days to come up with a new library and strategy and I'm definitely going over time on this one as I still don't have it quite right, any pointers and thoughts would be appreciated.

**Comment by darrrk** [comment]
I wanted to create issue "Electron devtools should support async stack traces, at least for Promises".
But found this and write it here.
Because node.js support it in nightly builds and chrome a long time ago.

**Comment by francoislaberge** [comment]
@darrrk Did you find some flags that were interesting in node.js or chrome's nightly builds? Best option I've found for Promise async stack traces is to just use [bluebird](https://npmjs.org/bluebird) which provides a great implementation of it.

**Comment by darrrk** [comment]
*bluebird* doesn't provide a great implementation of it.
Because you can see variables state in current stack only, not for prev stacks.
Also you need inject *bluebird* everywhere in your project.
Also, this glitch and not work with *co*
Need to have same functionality, that is **Promise Async** in **v8_inspector** of node.js master branch.

**Comment by francoislaberge** [comment]
Do you have any links to more information (docs/source/articles) about that?

I don't mind the idea of replacing `window.Promise=require('bluebird')`, but then I haven't tried it yet, not sure how well that would just work or if it would likely have glitches.

**Comment by darrrk** [comment]
You can do `global.Promise = require('bluebird')`, but your long stack will be simply logged in console and affected:
> Because you can see variables state in current stack only, not for prev stacks.

**Comment by francoislaberge** [comment]
Write, gotcha. Yes, that is the case. I'm finding using the combination of the Async flag in DevTools and instrumenting using bluebird for promises and longjohn/stacktrace.js/trace/clarify for our test suites has been a decent experience.

Let's keeping the good fight and find a good solution, hopefully a proper one using the underlying mechanisms as you mention.

**Comment by darrrk** [comment]
*trace* module in electron broken for me
https://github.com/electron/electron/issues/5835

**Comment by francoislaberge** [comment]
That explains the issue I was having with trace when I took a quick crack at using. Things were acting weirdly, I just moved on to something else. Thanks for the information.

**Comment by darrrk** [comment]
Unexpectedly for me, *bluebird* works some good with devtools async checkbox and *co*.
It find last *co* generator execution in prev stacks, remains only to find error inside it generator.
Sorry for my prev messages, I was wrong.

**Comment by francoislaberge** [comment]
No worries. Thanks for correcting this, I hadn't followed up further on my explorations, good to know. We won't be using generators much for the short term or long term, we're likely to use Promises through out and be prepared for using async/await soon enough, maybe we'll even transpile them in now rather than wait.

**Comment by zcbenz** [comment]
The devtools in Electron should just behave the same with current stable version of Chrome, if you want a feature in beta/dev channels Chrome, you only need to wait for Electron to upgrade the Chrome version.

**Comment by francoislaberge** [comment]
@darrrk Can you be very explicit as to what you were saying here:

> I wanted to create issue "Electron devtools should support async stack traces, at least for Promises".
> But found this and write it here.
> Because node.js support it in nightly builds and chrome a long time ago.

Because I see no async related flags for the [latest node.js docs on master](https://github.com/nodejs/node/blob/master/doc/api/cli.md#synopsis). Is there some flag I'm not seeing?

Canary of Chrome as of today doesn't have any new Async flags, just the one that's been around for a long time:
![canary-chrome](https://cloud.githubusercontent.com/assets/1845/16522120/a92d3860-3f69-11e6-9611-498ba4a43613.png)
Do you know of some other flag/setting I should be using to improve Promises or regular Async stack traces?

ps. I did find out a way to programmatically set it by calling into the DevTools frontend code, but it's not pretty. I'm adding it to our internal Electron/Mocha tester, if it works consistently I'll likely wrap it up and add it to my [debugger](http://npmjs.org/debugger) module.

**Comment by darrrk** [comment]
@francoislaberge

> Electron devtools should support async stack traces, at least for Promises
Because node.js support it in nightly builds

node.js nightly build have built-in chrome debugger (`node --inspect index.js`) and devs say, that it support async stack traces for native promises.
https://github.com/nodejs/node/pull/6792
Electron doesn't have this feature, but you can use *bluebird*

> Canary of Chrome as of today doesn't have any new Async flags

I think, it mean, that stack traces always async.

> Do you know of some other flag/setting I should be using to improve Promises

I use *bluebird* for this. *trace* module doesn't work for me.

**Comment by francoislaberge** [comment]
@darrrk Thanks. I'm trying this out to see if adds anything interesting to DevTools. Looks like @zcbenz is already all over getting any improved DevTools/v8_inspector into Electron asap. See:
https://github.com/nodejs/node/pull/6792#issuecomment-225768661

**Comment by francoislaberge** [comment]
@darrrk I built master of https://github.com/nodejs/node, and tried out the `node --inspect script.js` workflow, it's great that this is going to be built into node.js and not require using node-inspector and such now (thought [devtool](http://npmjs.org/devtool) is my tool of choice). It doesn't add anything that I could tell to Promise stack traces, hell it barely did async stack traces very well.

**Comment by darrrk** [comment]
@francoislaberge, if node.js master branch doesn't support native Promise async stack traces now, it should support it, when 7 version released.

**Comment by zcbenz** [comment]
I'm closing this since there is nothing we can do in Electron. For improving the devtools, I suggest doing the discussion in Chrome devtools mailing list:
https://groups.google.com/forum/#!forum/google-chrome-developer-tools
