### ISSUE TITLE
setContentSize seems to have no effect on windows.

### ISSUE THREAD

**Issue by kunkinkan** [electron/electron#6241]
Works on Mac, but not on windows;

`      electron.remote.getCurrentWindow().setContentSize(600, parseInt(document.documentElement.scrollHeight, 10), false);
`

(No error, just no change).

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem? I'm unable to reproduce with your code.

**Comment by zcbenz** [comment]
Closing until more information is provided.
