### ISSUE TITLE
Why shipping FFmpeg by default?

### ISSUE THREAD

**Issue by pombredanne** [electron/electron#6242]
* Electron version: any
* Operating system: any

I understand that FFMpeg comes likely with Chromium but why and how would this be needed in the majority of Eclipse-based apps? This is extra cruft and size for no benefits in most cases, unless I miss something?

**Comment by zcbenz** [comment]
Chromium doesn't provide flags to turn off most of its features, we are only using a subset of Chromium browser and unfortunately ffmpeg is one of the minimal requirements.

**Comment by pombredanne** [comment]
@zcbenz Thanks for the quick reply!

**Comment by TekSiDoT** [comment]
@zcbenz Thank you, do you know of any long term plans by the Chromium team to improve this situation as a result of the increasing popularity of Electron?
