### ISSUE TITLE
version doubt when build native modules 

### ISSUE THREAD

**Issue by ylyxf** [electron/electron#6245]
* Electron version:1.2.4
* Operating system:win7 32-bit

 the code <code>document.write(process.versions.node)</code> print <code>6.1.0</code> 

but i build an nativae module using npm by set npm_config_target=1.2.3, it download the <code>iojs</code> in path  C:\Users\myname\.node-gyp\iojs-1.2.4

does the nodejs 6.1.0 == iojs 1.2.4 ?

what's the relationship between them ?

**Comment by enlight** [comment]
iojs-1.2.4 is not actually io.js, a more appropriate name for it is electron-1.2.4 but the name is what it is to keep `node-gyp` happy. This exact same question was answered in #6214 two days ago.
