### ISSUE TITLE
BrowserWindow set height problem

### ISSUE THREAD

**Issue by hahamed** [electron/electron#6246]
![electron-resize-problem](https://cloud.githubusercontent.com/assets/7124577/16440812/93ad3bce-3dda-11e6-954d-8b48017dcae9.png)
* Electron version: 1.20.0
* Operating system: Windows 7

Hello,
When i setsize or setbounds browserwindow to height below 65, then my win become this:
[electron-resize-problem](http://imgh.us/electron-resize-problem.png)
Why?
it is not real height.
thanks

**Comment by abdihaikal** [comment]
Could you show the options you've defined for BrowserWindow instance?

```javascript
var options = {
    ...
};
var mainWindow = new BrowserWindow(options);
```

**Comment by hahamed** [comment]
`var  mainWindow = new BrowserWindow({ 'web-preferences': { 'web-security': false }, resizable: true, transparent: true, width: 420, height:90, skipTaskbar: true, frame: false, closable: true, fullscreenable: false, maximizable: true, minimizable: false });
`

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by zcbenz** [comment]
Closing until more information is provided.
