### ISSUE TITLE
app.on initialization

### ISSUE THREAD

**Issue by Jumperlow** [electron/electron#6248]
* Electron version: / 
* Operating system: Windows and Mac

I'm trying to show a window before the initialization but I don't really know how to do it.

**Comment by abdihaikal** [comment]
Could you please be more spesific..

**Comment by kevinsawicki** [comment]
You cannot show a window until the `app` `ready` event fires.

You may want to look at the quick start for code examples: http://electron.atom.io/docs/tutorial/quick-start/

Closing this out.
