### ISSUE TITLE
Asar files getting locked when read via fs APIs

### ISSUE THREAD

**Issue by bpasero** [electron/electron#6251]
- Electron version: any >= 0.37.7
- Operating system: Windows

Having a folder open (either VS Code or Atom) with *.asar files causes these files to be locked, making it impossible to delete/rename them unless the editor is closed.

![image](https://cloud.githubusercontent.com/assets/900690/16371627/0b788292-3c48-11e6-98b7-51626c174706.png)

**Comment by abdihaikal** [comment]
I think, it's all about (almost) all IDE common behaviour.

**Comment by MarshallOfSound** [comment]
An `asar` is just a read only archive.  If you compare this behavior to just opening a `zip` file in preview mode in Windows explorer it is the same behvior.

I.e. Opening the zip file in Windows Explorer locks the zip file so you can't rename it

I'm pretty sure most other IDE's behave this way aswell when looking inside archives.

**Comment by bpasero** [comment]
To be clear, all I do is `fs.stat()` on the asar and maybe a `readdir`. I do not leave any file handles open.

**Comment by kevinsawicki** [comment]
> To be clear, all I do is fs.stat() on the asar and maybe a readdir. I do not leave any file handles open.

Does it still happen if you use `require('original-fs')` instead of `require('fs')` for these calls?

**Comment by bpasero** [comment]
@kevinsawicki thanks, thats a good workaround for me. Does not block using `original-fs`.

**Comment by zcbenz** [comment]
Currently all asar files are cached during app's lifetime, since the original design was to only use it for app's files. We should probably make the cache ref-counted.

**Comment by codebytere** [comment]
Given the conversation above, it appears that the actionable issues in this have been addressed. In that event, i'm going to go ahead and close this, but please feel free to @ me if something else arises!

**Comment by localip** [comment]
Could this be re-opened? I have an addon system which focuses on using asars to package the addons. However when trying to delete the addon through a UI, I cannot due to them being locked by electron's cacher.

**Comment by leoFitz1024** [comment]
> Could this be re-opened? I have an addon system which focuses on using asars to package the addons. However when trying to delete the addon through a UI, I cannot due to them being locked by electron's cacher.


Do you have a solution?

**Comment by localip** [comment]
> > Could this be re-opened? I have an addon system which focuses on using asars to package the addons. However when trying to delete the addon through a UI, I cannot due to them being locked by electron's cacher.
> 
> Do you have a solution?

Unfortunately, no. The project has since been abandoned.
