### ISSUE TITLE
Can't open empty tab in default OS browser using Shell.openExternal

### ISSUE THREAD

**Issue by jwheare** [electron/electron#6252]
* Electron version: 1.1.1
* Operating system: macOS 10.11.5
* Default browser: Chrome 51.0.2704.103

`Shell.openExternal('about:blank')` and `Shell.openExternal('')` don't do anything. It would be nice if the behaviour of [`window.open()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) in javascript was maintained:

> If strUrl is an empty string, then a new blank, empty window (URL about:blank) is created

We need this feature in our app (which is a wrapper for a web app) to ease transition for people who are used to e.g. the `Cmd-T` shortcut in their browser opening a new tab.

**Comment by abdihaikal** [comment]
You might want to use somekind of blank HTML as a "bootstrap",
and load this with [BrowserWindows Instance].webContents.loadURL("...").
Something like:
```javascript
var childWindow = new remote.BrowserWindow([options]);
childWindow.webContents.loadURL('[path/to/bootstrap-html-page]');
```
And in "bootstrap" page
```javascript
var ipcRenderer = require('electron').ipcRenderer;
var remote = require('electron').remote;
ipcRenderer.once('something-to-listen', function(ev, somethingToLoad) {
    remote.getCurrentWebContents().loadURL('[somethingToLoad]');
});
```
It’s just a thought.

**Comment by zcbenz** [comment]
`shell.openExternal` opens the URL with its registered application, instead of opening the URL in current browser.

I'm merging this to #4815.

**Comment by jwheare** [comment]
I'm working around this with https://www.npmjs.com/package/open now, which I've tested working on Windows and Mac with Chrome as the default browser

```
const open = require('open');
open('http://');
```

**Comment by jwheare** [comment]
I debugged this a bit. The reason 'http://' won't open using `openExternal` is due to the `NSURLWithGURL` call here:

https://github.com/electron/electron/blob/4627311c34ec2ac636e54e8448b72d3d87344328/atom/common/platform_util_mac.mm#L133

A bare URL scheme on it's own isn't valid according to GURL so that returns nil. That's probably expected validation for this particular API, but it might be nice to have an API that does allow opening other protocol handlers. For instance, typing `spotify://` into Chrome launches the app.
