### ISSUE TITLE
`delete` menu item role doesn't do anything

### ISSUE THREAD

**Issue by mnquintana** [electron/electron#6256]
* Electron version: 1.1.3
* Operating system: macOS 10.11.5

It seems that the `delete` menu item role I added awhile ago doesn't do anything on macOS, at least in a webview 😕  – can anyone else repro?

**Comment by kevinsawicki** [comment]
> at least in a webview

Does it work in a non-webview? And have you tried it working in the webview on 1.2.5?

**Comment by danhp** [comment]
I get it to work in non-webview in 1.2.5
Ref [Caprine](https://github.com/sindresorhus/caprine/blob/master/menu.js#L207)

**Comment by kevinsawicki** [comment]
@mnquintana can you include a small reproduction example? Thanks.

**Comment by mnquintana** [comment]
@kevinsawicki Yup! Sorry, I'll get a minimal repro going later

**Comment by zcbenz** [comment]
Closing until more information is provided.
