### ISSUE TITLE
Problems registering custom protocol

### ISSUE THREAD

**Issue by kjlaw89** [electron/electron#6258]
* Electron version: 1.2.5
* Operating system: Windows 10

My application has a custom "res://" protocol. It appears to register correctly (no errors or anything) but as you can see from the picture I'm getting the error **net::ERR_UNKNOWN_URL_SCHEME**. This is working in version 1.2.4.

![image](https://cloud.githubusercontent.com/assets/4183007/16391832/d5fa3c80-3c76-11e6-9f7a-c7d746149f25.png)

**Comment by kevinsawicki** [comment]
Can you include a reproduction app that demonstrates this behavior? Thanks.

**Comment by kjlaw89** [comment]
I can't get it to duplicate with my test application, but I did find _some_ sort of cause in my main application. It appears that me loading in AWS-SDK and initializing it at any point (before or after registering my protocol) seems to cause the problem. Unfortunately it doesn't duplicate in the test application despite my best attempt to duplicate how everything was loading.

The process in my main application works like this:

1. app.on ("ready") occurs, which calls App.Ready
2. App.Ready loads in all application modules, starting with update first (in case a critical problem occurs in the application I want the update process to start before everything else)
3. Update initializes AWS.S3 (which causes issues on main app), then checks for updates
4. After update check is done, it calls App.Begin, which setups up the "res://" protocol and then creates the main window to start displaying things

There's a lot of fluff in this test application, sorry about that. I was trying all sorts of different things that our application does or has setup to duplicate it, but nothing would...

[test.zip](https://github.com/electron/electron/files/340104/test.zip)

**Comment by zcbenz** [comment]
I'm unable to reproduce with your app, I saw lots of `Failed to load resource: net::ERR_FILE_NOT_FOUND` errors but they are expected.

**Comment by jwu** [comment]
I can confirm this problem in both 1.2.5 and 1.2.6 in one of my app. But strangely it doesn't happen in my other projects. The thing is it needs the App to be as complicate as it can before it running a window. I am trying to write simple code to reproduce the problem.

**Comment by paulcbetts** [comment]
Loading aws-s3 is probably big enough that it will finish post-ready on some machines

**Comment by kjlaw89** [comment]
Post-ready as in after app "ready" fires? In the example app I provided I only attempt to load the aws-sdk post-ready, but everything appears to load fine in that case. It's been a few days, but I don't think the aws-sdk require was even the problem - it was creating a new instances of aws.s3.

I'll try to move both of those to the very beginning of my application today and see if that helps. I can tell you if I keep restarting the application eventually everything will load once. Like 1/20 attempts will work.

**Comment by jwu** [comment]
Hi @zcbenz, @kevinsawicki,

I finally find a way to 100% reproduce this problem. Here is the repo for this bug: https://github.com/jwu/electron-custom-protocol-bug, just follow the README in this repo you will see the error.

It seems like a large amount of calculation during init code of Electron will broke the custom protocol registry. And if you switch to v1.1.3 of Electron in my code, the error will gone.

Anyway, hope this code can help you locate the problem.

**Comment by zcbenz** [comment]
@jwu I can reproduce with it, thanks for working out the test case.

**Comment by Aerlinger** [comment]
I've been trying to narrow the source of the bug down using a "bisect" approach with different versions of Electron. It looks like the bug in question was first introduced in version v1.2.4, most likely as an unexpected side-effect resulting from a fix for a prior bug introduced in v1.2.3 as described here: https://github.com/electron/electron/pull/6095.

**Electron v1.2.2** and earlier: Works fine
**Electron v1.2.3** => Launching Electron fails with following error:
![image](https://cloud.githubusercontent.com/assets/604138/17272692/4e054414-566b-11e6-8536-949e5462385b.png)
**Electron v1.2.4** Fails with error described in original post

**Comment by Aerlinger** [comment]
Could it be related this this addition https://github.com/electron/electron/pull/6195? This is the only change between v1.2.4 and 1.2.5 that seem to change anything related to protocol handlers.

**Comment by Aerlinger** [comment]
It seems to be a race condition where the protocol is called before it's registered with Electron. Interestingly, if I modify your example to define the window outside of the watcher callback, it works:

Demo App: https://github.com/jwu/electron-custom-protocol-bug

**This works: (main.js)**
Electron.app.on('ready', () => {

  // register protocol app://
  Electron.protocol.registerFileProtocol('app', (request, cb) => {
    if ( !request.url ) {
      cb (-3); // ABORTED
      return;
    }

    let url = decodeURIComponent(request.url);
    let uri = Url.parse(url);

    let relativePath = uri.hostname;
    if ( uri.pathname ) {
      relativePath = Path.join( relativePath, uri.pathname );
    }

    let file = Path.join( __dirname, relativePath );
    cb ( { path: file } );
  }, err => {
    if ( err ) {
      console.log( 'Failed to register protocol app, %s', err.message );
      return;
    }
    console.log( 'protocol app registered' );
  });

  // If this is defined within the `watcher.on('ready')` the error will return
  let mainWindow = new Electron.BrowserWindow({
    title: 'Main',
    width: 800,
    height: 600,
  });

  // Defined outside the chokidoar callback
  let watcher = Chokidar.watch([__dirname], {
    ignoreInitial: true,
    persistent: true,
  });

  watcher.on('ready', () => {
    // create main window and show it
    mainWindow = new Electron.BrowserWindow({
      title: 'Main',
      width: 800,
      height: 600,
    });

    mainWindow.loadURL(`file://${__dirname}/index.html`);
    mainWindow.show();
    mainWindow.openDevTools();
  });
});

**Comment by TimNZ** [comment]
Has this been verified as fixed?  I'm getting  ERR_UNKNOWN_URL_SCHEME in a webview

main.js
```
app.on('ready', async() => {

    protocol.registerFileProtocol('ext', (request, callback) => {
        const url = request.url.substr(6)
        let callbackPath = path.normalize(`${appOptions.approotpath}/external/${url}`)
        console.log(callbackPath)
        callback({path: callbackPath })
    }, (error) => {
        if (error)
            console.error('Failed to register protocol')
        else
            console.log('EXT scheme registered')
    })
   ....
```

webview preload script, nodeintegration NOT ENABLED:

```
window.onload = function() {
    const {webFrame,remote} = require('electron')
    webFrame.registerURLSchemeAsSecure('ext')
    var appOptions = remote.getGlobal('app_options')
    var script = document.createElement("script");
    script.src = "ext://jquery/jquery-3.1.0.min.js";
    script.onload = script.onreadystatechange = function() {
        jq = $.noConflict(true)
        console.log(jq)
        jq(document).ready(function() {
            setInterval(() => {
                console.log('Searching for Dashboard link')
                var a = jq('a[id=Dashboard]')
                if (a.length)
                    a.text('Tim')

            },1000)
        });
    };
    document.body.appendChild(script);
};
```

Error in webview dev tools console:

<img width="751" alt="google chrome - - screen shot 7-08-2016 8 32 42 pm" src="https://cloud.githubusercontent.com/assets/1051701/17461357/1c5ea242-5cde-11e6-8f4c-ed211002024a.png">

**Comment by Aerlinger** [comment]
The issue as I encountered it (described above) was fixed on Electron 1.3.2

**Comment by yanlee26** [comment]
not fixed still..

**Comment by mkamran67** [comment]
2024, still occurs.
