### ISSUE TITLE
how to close chromium sockets?

### ISSUE THREAD

**Issue by lasryaric** [electron/electron#6259]
* Electron version: 1.2.5
* Operating system: mac os x 10.11.1

I use several BrowserWindow objects in serial to browse different host. Sockets to each host stay open for 5 to 10 minutes before closing, which bring my total number of opened sockets higher than the limit allowed by the system.

Is there a way I can force Electron / Chromium to close the sockets faster? I know I don't need them as soon as I call BrowserWindow.close().

Thanks.

**Comment by zcbenz** [comment]
The sockets are closed when you call `close` on them.

**Comment by lasryaric** [comment]
And in the context of Electron, any hint on how to close them faster?
