### ISSUE TITLE
Remote event handler attached in webview causes crash

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#6264]
* Electron version: 1.2.5
* Operating system: macOS

Use `systemPreferences.subscribeNotification` to attach an event handler:
``` js
import {remote} from 'electron';
const {systemPreferences} = remote;

// open System Preferences > Keyboard > Text and change any substitution to trigger this
systemPreferences.subscribeNotification('IMKTextReplacementDidChangeNotification', () => console.log('got a change'));
```

* If this handler is attached in a renderer, you'll receive notifications as expected.
* But if this handler is attached in the preload script of a `webview`, you'll crash with:
```
Attempting to call a function in a renderer window that has been closed or released
at node_modules/electron-prebuilt-compile/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js 
callIntoRenderer line 189, column 19
```

I confirmed that the `webview` is not being disposed. Any ideas? I can use the main process and `ipc` the notifications across, but from documentation I think this is a supported scenario.

**Comment by zcbenz** [comment]
I can not reproduce with a simple page like this:

```html
<webview src="http://google.com" preload="preload.js"></webview>
```

```js
const {systemPreferences} = require('electron').remote
systemPreferences.subscribeLocalNotification('NSSystemColorsWillChangeNotification', () => console.log('got a change'))
```

Can you provide a minimal app that can reproduce this problem?

**Comment by CharlieHess** [comment]
I spent some more time investigating this and it was on our end after all. Seems we were in a situation where some of our `webview`s were running their preload script twice (the first time without a `src` attribute).
