### ISSUE TITLE
BrowserWindow .setSize(), .setContentSize() and .center() behavior in fullscreen

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#6267]
Setting the browser window size via `.setSize()` or `.setContentSize()` while in fullscreen will force the *webContents* view to a specific size in fullscreen ([screenshot](https://cloud.githubusercontent.com/assets/797899/16403227/b28afb68-3d25-11e6-9e02-3b677d9eca12.png)) and will not remember that new size for the browser window when exiting fullscreen.

`.center()` is also affected by this in a way (ignored if set while in fullscreen, and not remembered when leaving fullscreen).

`.setAspectRatio()` is also affected if set while not in fullscreen, then it is still enforced while in fullscreen (meaning content is cropped).

Is that the intended behavior?

Here is a behavior suggestion that would make sense in my case:
- `BrowserWindow` or *WebContents* size/position in fullscreen can not be set/forced (it will always fill the entire screen).
- When using `.setSize()`, `.setContentSize()` or `.center()` on a BrowserWindow that is currently in fullscreen, it should set size/center to the window without applying it to fullscreen (so when leaving fullscreen, the window has the new size/position)

----

* Electron version: 1.2.5
* Operating system: OSX 10.11.5

**Comment by zcbenz** [comment]
It is undefined behavior, to keep consistency with Windows and Linux, I think we should just ignore the calls in fullscreen.
