### ISSUE TITLE
Click the menu  item couldn't popup file select window

### ISSUE THREAD

**Issue by zenglzh** [electron/electron#6268]
* Electron version:electron-v1.2.2-win32-x64
* Operating system:win7 

`<input id="fileselect" type="file" nwworkingdir="/" style="visibility:false" />`
`const menu = new Menu();`
`		menu.append(new MenuItem({`
`			label : 'File',`
`			click:function(){`
    `				$('#fileselect').click();`
    `			}`
`		}));`

**Comment by fdelayen** [comment]
I think it is part of a security-related limit of javascript in browser.

Small example in this [fiddle](http://jsfiddle.net/L858sz7y/1/).

You can trigger it from a user click event but not directly from the code. May be it can be bypassed that in Electron...

**Comment by zenglzh** [comment]
Thanks @fdelayen .I can click a button to pop file selector. But click the menu item is useless.
`<a href="#" onclick="$('#fileselect').click();">O</a>  `//OK

**Comment by abdihaikal** [comment]
@fdelayen , maybe you can try this code:
```html
<button id="fileselect_button">Click this</button>

<input id="fileselect" type="hidden" value="SOME_VALUE" />

<script type="text/javascript">
(function() {
  var remote = require('electron').remote;
  var Menu = remote.Menu;
  document.getElementById('fileselect_button').addEventListener('click', function(ev) {
    ev.preventDefault();
    Menu.buildFromTemplate([{
      label : 'File',
      click : function() {
        var inputValue = document.getElementById('fileselect').attr.value;
        DO_SOMETHING_HERE with your "inputValue"
      }
    }]).popup(remote.getCurrentWindow());
  });
})();
</script>
```

**Comment by zcbenz** [comment]
You can use `webFrame.executeJavaScript` API to execute the code with user gesture:
http://electron.atom.io/docs/api/web-frame/#webframeexecutejavascriptcode-usergesture

**Comment by zenglzh** [comment]
Use `dialog.showOpenDialog([browserWindow, ]options[, callback])`
 [http://electron.atom.io/docs/api/dialog/](url)
@fdelayen @zcbenz
