### ISSUE TITLE
Can't Increase Stack Trace Limit

### ISSUE THREAD

**Issue by francoislaberge** [electron/electron#6271]
I'm trying to increase the default stack trace limit from 10 to something higher. I'd expect the following to work:
```js
app.commandLine.appendSwitch("js-flags", "--stack_trace_limit=100");
```

In DevTools console:
```js
Error.stackTraceLimit
10
```

Any pointers on how properly to do this?

**Comment by francoislaberge** [comment]
Closing this. I had another issue that was silently throwing an exception before this code was being hit.

**Comment by dongyuwei** [comment]
`app.commandLine.appendSwitch("js-flags", "--stack_trace_limit=100");` seems not work. How did you increased the limit? @francoislaberge

**Comment by francoislaberge** [comment]
I don't recall anymore. Sorry. Code is proprietary at my previous job, so I can't review
