### ISSUE TITLE
Growing memory when displaying images

### ISSUE THREAD

**Issue by bpasero** [electron/electron#6275]
This might be more an issue with Chrome than Electron but in VS Code we notice that opening a large image (e.g. BMP) in the editor adds a lot of memory to the process. Now, when we close the editor we release the DOM elements from the document but the memory does not go down instead it just stays. So you can get into an out of memory situation by continuing to open the image and closing it.

Is this known already by other users? Is there a programmatic way to release the image and free it?

Btw I am seeing this in the same way in Atom and can make it crash by closing and opening a tab with a large image:

![image](https://cloud.githubusercontent.com/assets/900690/16422055/53f0a5a8-3d57-11e6-89c2-fa2359463122.png)

**Comment by bpasero** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=625168

**Comment by elboletaire** [comment]
The issue was closed in chromium side due to "lack of user feedback". Were you able to resolve it @bpasero?

**Comment by bpasero** [comment]
No, as I am not working for Chrome. If someone wants to chime in, feel free.

**Comment by alecperkey** [comment]
Please allow user preference for max file preview size. Seems chromium works fine enough:

https://bugs.chromium.org/p/chromium/issues/detail?id=805655

**Comment by alecperkey** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=805655

https://github.com/Microsoft/vscode/issues/42122
