### ISSUE TITLE
Binding context menu item visibility to main window visibility

### ISSUE THREAD

**Issue by hawkins** [electron/electron#6277]
* Electron version: v1.2.5
* Operating system: Windows 7 UItimate (64 bit)

I'm attempting to bind the `visible` property of a `MenuItem` to my `mainWindow.isVisible()` function, but the `isVisible()` does not appear to 'refresh' or be re-evaluated after hiding `mainWindow`.

What is the correct way to bind `MenuItem.visible` to `mainWindow.isVisible()`?

## More details

My Electron application builds a tray icon with a context menu.

This context menu should: 
- Have options to show or hide the main window of my application.
- Only show one of the options at a time (i.e., if `mainWindow` is visible, show the `Hide Window` option in context menu, but not `Show Window`).
- To the end user, seem like a toggle for window visibility, but the labels change to represent the next action more clearly.

To accomplish this, I've created `contextMenu` as such:

    var contextMenu = Menu.buildFromTemplate([
        {
            label: 'Show Window',
            visible: !mainWindow.isVisible(),
            click: function () {
                mainWindow.show()
            }
        },
        {
            label: 'Hide Window',
            visible: mainWindow.isVisible(),
            click: function () {
                mainWindow.hide()
            }
        }
    ]);

>Note: `mainWindow` is defined as per the [electron-quick-start](https://github.com/electron/electron-quick-start/blob/master/main.js#L13) tutorial)

The app runs and the context menu is added to my tray icon successfully. The `Hide Window` option is visible initially, as `mainWindow` is visible at startup. However, after clicking to hide the window, `mainWindow.isVisible()` does not appear to 'refresh' the visibility of the context menu items, and thus the `Show Window` option does not appear as I expected it to.

What is the correct way to bind `MenuItem.visible` to `mainWindow.isVisible()`?

**Comment by hawkins** [comment]
While not nearly as convenient as I had originally hoped, I've come up with a workaround for the time being.

Using [BrowserWindow's show and hide events](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-show), I was able to listen for these events and manually adjust the `visible` property for both items.

Menu definition: 

    var contextMenu = Menu.buildFromTemplate([
        {
            label: 'Show Window',
            visible: false, // Hidden at startup
            click: function () {
                mainWindow.show()
            }
        },
        {
            label: 'Hide Window',
            visible: true, // Visible at startup
            click: function () {
                mainWindow.hide()
            }
        }
    ]);


    // And later in the same function that created this menu...
    // Allow mainWindow events to change menu item visibility
    mainWindow.on('show', function () {
        contextMenu.items[4].visible = false;
        contextMenu.items[5].visible = true;
    });
    mainWindow.on('hide', function () {
        contextMenu.items[4].visible = true;
        contextMenu.items[5].visible = false;
    });

**Comment by zcbenz** [comment]
Listening to the show/hide events is the best solution for now. A more general solution is tracked at #528.

**Comment by amig** [comment]
When implementing the above on the tray menu, the only way this worked for me is by re-setting the menu via the `tray.setContextMenu(contextMenu);` i.e.,

```
mainWindow.on('show', function () {
    contextMenu.items[0].visible = false;
    contextMenu.items[1].visible = true;
    tray.setContextMenu(contextMenu);
});
mainWindow.on('hide', function () {
    contextMenu.items[0].visible = true;
    contextMenu.items[1].visible = false;
    tray.setContextMenu(contextMenu);
});
```
