### ISSUE TITLE
Hiding the dock icon prevents the app from appearing in the app switcher

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#6283]
* Electron version: `1.2.5`
* Operating system: macOS

When using this API  
https://github.com/electron/electron/blob/master/docs/api/app.md#appdockhide-macos

```js
app.dock.hide();
```

If you try and switch to your window with "Command + Tab" the app does not appear in the switcher.  Is this a limitation of macOS?

**Comment by zcbenz** [comment]
Yeah it is a limitation of macOS that we are not able to work around.
