### ISSUE TITLE
Can I embed a electron app into a native OS X App's webView ?

### ISSUE THREAD

**Issue by sunuslee** [electron/electron#6284]
* Electron version: N/A
* Operating system: N/A

Can I embed a electron app into a native OS X App's webView ? because right now we have two apps, one is native OS X app and the other is electron based app. we want to marge them into one app. so i'm wondering if there is a way to put electron-based app into a native app's webview or something like that.
any suggestion is welcomed! thanks!

**Comment by mnquintana** [comment]
No, this isn't possible. You might be able to, however, embed whatever you have embedded in an OS X webview in an Electron webview, though you would need to swap any and all native APIs you were accessing from the OS X webview for Electron APIs.

In the future, for questions on writing apps, I suggest seeking help from [the community](https://github.com/electron/electron#community). The issues list is only for bug reports and feature requests.
