### ISSUE TITLE
mainWindow.loadURL should really warn about invalid file names or throw.

### ISSUE THREAD

**Issue by envygeeks** [electron/electron#6285]
* Electron version: electron-prebuilt@1.2.5
* Operating system: Ubuntu 16.10 x64

When mainWindow (BrowserWindow) is given an invalid URL it will simply continue on as if nothing has happened happily telling the user nothing is wrong, telling the developer nothing is wrong, yet it'll load and show a blank page as if everything magically worked out, but that is not the case.

It would be great if Electron's `BrowserWindow#loadURL` threw or warned when a file doesn't include a protocol like `file://` that way users don't spend time debugging everything but that, or spend time trying to figure out why Electron is logging nothing yet the app is not loading properly.

**Comment by zcbenz** [comment]
You can listen to the `did-fail-load` event for such errors.

**Comment by pushkin-** [comment]
According to [this](https://cs.chromium.org/chromium/src/net/base/net_error_list.h) page, an error should be thrown if the file was not found (FILE_NOT_FOUND). However, that doesn't appear to happen.

I'm passing a url that points to a file that doesn't exist (http://localhost:1234/asd/asd/asd), but `did-fail-load` doesn't fire.
