### ISSUE TITLE
opening modal window changes window title on Mac

### ISSUE THREAD

**Issue by cbfiddle** [electron/electron#6286]
* Electron version: 1.2.5
* Operating system: Mac 10.10.5

When I open a modal browser window, the title in the title bar changes to the name of the document that I originally loaded into the parent browser window. I had used setTitle() to change the window title to something else.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem? I'm unable to reproduce with your description.

**Comment by cbfiddle** [comment]
That is a worthy challenge. In trying to come up a minimal example, I discovered that the changing of the window title is not related to Electron browser windows. Instead, it is a consequence of clicking on and navigating a link with href=`"#"`. Although that does not change the display, apparently Chromium makes an upcall saying that the document title has changed. Perhaps it should not do that, or perhaps Electron should ignore a change that duplicates the original file-based title when the application has replaced that title. In any case, suppressing the link navigation solved my problem.

**Comment by zcbenz** [comment]
To prevent the title of window from changed, you can subscribe to the `page-title-updated` event:
http://electron.atom.io/docs/api/browser-window/#event-page-title-updated
