### ISSUE TITLE
modal window's height is 20px shorter than specified on macOS

### ISSUE THREAD

**Issue by cbfiddle** [electron/electron#6287]
* Electron version: 1.2.5
* Operating system: Mac 10.10.5

When I converted my dialog browser windows to modal windows, I needed to make them taller to show the entire content. Electron should perform this compensation for me, as it is an artifact of using sheets, which is an Electron implementation decision.

**Comment by mnquintana** [comment]
Would you mind attaching some screenshots?

**Comment by cbfiddle** [comment]
I have already updated my dialog windows to be about 20 pixels taller, so now they look right on 1.2.5 but have extra blank space at the bottom on 1.2.3.

<img width="646" alt="screen shot 2016-06-28 at 9 40 59 pm" src="https://cloud.githubusercontent.com/assets/6628505/16440689/115f091a-3d79-11e6-8c6e-4ba862cc36c5.png">
<img width="649" alt="screen shot 2016-06-28 at 9 40 39 pm" src="https://cloud.githubusercontent.com/assets/6628505/16440690/1160301a-3d79-11e6-8a25-fc66bbde1ff7.png">

**Comment by zcbenz** [comment]
The window's height includes the titlebar by default, you should probably set `useContentSize: true` in your case.

**Comment by cbfiddle** [comment]
I respectfully disagree. I created the window with frame: false, so as an application developer I have no reason to think that there will be a title bar whose height I must account for. It is an implementation decision of Electron to use a sheet, and if that means adding a title bar contrary to the instructions of the application, then Electron should compensate for it.

**Comment by aabuhijleh** [comment]
> The window's height includes the titlebar by default, you should probably set `useContentSize: true` in your case.

@zcbenz 

I just checked with 9.0.4. `useContentSize: true` does not fix this issue. The frameless modal window on macOS is still shorter than it is on Windows even with that flag set to true.

My workaround is to manually add 20px to the height if the app is running on macOS.

**Comment by aabuhijleh** [comment]
With macOS 11, I have to add 25px because 20px was not ok...

This is really terrible hack on my part but I don't see an alternative

**Comment by ym13349140** [comment]
@zcbenz I have the same problem with Electron@11.3.0 on MacOS 10.14.6. Even though I  set useContentSize: true in my case, it doesn't work at all.My subWindow's height was shorter 22px.SO does Electron plan to fix this error?

**Comment by erikjalevik** [comment]
Experiencing this issue too in Electron 13.6.9. The window seems to be 28px smaller on MacOS Monterey.

I set the height to 400px, and get a 372px tall modal window.

**Comment by richardo2016x** [comment]
Same issue on Electron 22.0.0, modal window's height is 28px shorter on macOS Ventura (13.0.0).
