### ISSUE TITLE
Knowing when webContents.sendInputEvent completes

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#6291]
`webContents.sendInputEvent()` is an asynchronous operation. Is there any way to be notified when the `sendInputEvent` operation completes?

I've tried adding a listener to `ipc-message` on webContents but it does not seem to be catching sendInputEvents from `electron.remote.getCurrentWindow().webContents.sendInputEvent`.

Interestingly enough, a test has been written for this and appears to be working:

https://github.com/electron/electron/blob/master/spec/webview-spec.js#L704

This test in `webview-spec.js` is on a `webview` though and not `webContents`.

Thanks!

* Electron version: 1.2.5
* Operating system: macOS

**Comment by zcbenz** [comment]
`webContents.sendInputEvent` sends the event to renderer process asynchronously, and Chromium doesn't provide a way to know when it completes.

The only way to test it is to listen to events in the page, and the use IPC to tell the main process, and we took this approach in our tests.

**Comment by kirkouimet** [comment]
I started an issue with Chromium to see if I can help contribute and have Chromium provide a way to know when the operation completes:

https://bugs.chromium.org/p/chromium/issues/detail?id=625193#

**Comment by kirkouimet** [comment]
@zcbenz it looks like when using `webContents` instead of a `webview` I don't get any `ipc-message` events containing input event data. However, when I listen to `webContents.on('ipc-message-sync')` I am getting events that have the input event data. Is this the proper way to listen for these events from webContents?

**Comment by zcbenz** [comment]
You have to manually capture the DOM events and then send it via IPC:
https://github.com/electron/electron/blob/master/spec/fixtures/pages/onkeyup.html

**Comment by kirkouimet** [comment]
Ah, I see! Forgot to check the test page. Thank you for pointing me to that.

Do you think I am getting the event after it has happened (in other words, at the correct time) if I listen on `webContents.on('ipc-message-sync')`? I am getting an event on that event listener that has the details of the mouse event (the x, y, etc.).
