### ISSUE TITLE
Showing sync message box immediately after closing modal window hangs

### ISSUE THREAD

**Issue by cbfiddle** [electron/electron#6293]
* Electron version: 1.2.5
* Operating system: macOS 10.10.5

I am experience a hang in my Electron application that does not occur in 1.2.3. My application creates a modal browser window. In response to a button click, the modal browser window is closed. Then, I try to quit the application using Cmd-Q. I handle before-quit and in the process I try to open a message box dialog.The dialog is never displayed. The Quit menu item is grayed out. The application is behaving as if the modal browser window had not been closed (but I closed it).

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by cbfiddle** [comment]
I have an app that demonstrates this problem as well as issue #6292.

To demonstrate this problem, click the Continue button on the sheet. The application hangs when I try to show a message box after closing the modal dialog. Apparently, even though the modal dialog is reported closed, the application is behaving as if it were still open.

To demonstrate #6292, try to Quit without clicking the Continue button.

The app will be at this URL for seven days:

https://we.tl/CbZpXyUPaX

**Comment by zcbenz** [comment]
Thanks for the test app, here is the minimal code to reproduce:

```js
const {app, dialog, BrowserWindow} = require('electron')

app.once('ready', () => {
  let p = new BrowserWindow()
  let c = new BrowserWindow({parent: p, modal: true, width: 400, height: 400})
  c.once('closed', () => {
    console.log('closed')
    dialog.showMessageBox(p, {buttons: ['OK']})
  })
  c.close()
})
```

**Comment by zcbenz** [comment]
> To demonstrate #6292, try to Quit without clicking the Continue button.

With 1.3.2, I can not reproduce the crash, there is a JavaScript exception though.

**Comment by cbfiddle** [comment]
I have also gotten an exception, object destroyed…

It may be timing dependent at what level the problem is encountered.
