### ISSUE TITLE
Allow to run Electron apps without ASAR support

### ISSUE THREAD

**Issue by bpasero** [electron/electron#6295]
Since VS Code is not leveraging ASAR at all, we would like to completely run without ASAR by setting `process.noAsar = true;`

However, it seems that electron.asar is always being looked for on startup of an Electron app so I cannot just go and unzip this file and put it somewhere (https://github.com/electron/electron/blob/0c53317eeaca0f6a1ae246acd23f037e8947e74e/atom/common/node_bindings.cc#L164 is suspicious).

Any reason behind this? Would it be possible to first see if the electron.asar exists at all?

**Comment by miniak** [comment]
Why don't you use asar?

**Comment by baconface** [comment]
> Why don't you use asar?

A big downfall to an ASAR file is that once it is in use it is basically write protected and cannot be deleted/modified. Which is documented in Code's issue manager. It might be unrelated but they were unhappy with the modification to the FS module when ASAR was first introduced.

**Comment by paulcbetts** [comment]
Uhhhh why would you want to be rewriting your own app's code at runtime

**Comment by bpasero** [comment]
We are not leveraging ASAR because most of our code is AMD and bundled into single large JS files via build step. For node_modules we are investigating into solutions like https://webpack.github.io/

**Comment by baconface** [comment]
> Uhhhh why would you want to be rewriting your own app's code at runtime

In the case of VS Code it is not a matter of modifying the app.asar but other third party ASARs where the end user expects to be able to delete or modify an ASAR file.

**Comment by paulcbetts** [comment]
Dunno, can you submit a PR to this effect @bpasero?

**Comment by cookiengineer** [comment]
> Why don't you use asar?

Basically every single issue opened in the [asar repository](https://github.com/electron/asar/issues) is a valid reason to skip the format. It's the definition of reinventing a binary concat format that is error prone, untested and does not work for everything non-UTF8.

So why not just use tar / bsdtar with a simple electron.json file (as header replacement) inside?
Runs on every single machine on the planet, is failsafe and does not lock out japanese or chinese users (or every other language that is not English and UTF-8).

**Comment by paulcbetts** [comment]
@cookiengineer but like, maybe just use UTF-8 and ASAR?

**Comment by cookiengineer** [comment]
@paulcbetts C'mon you can't be serious? ASAR has exactly zero specifications. The README is a joke and has basically no documentation at all. No examples and nothing to test against.

You are currently ignoring the reason why the RFC and IETF exists. Where's the spec for ASAR then? How can people implement it? Where are the tests? Is there a plan to make an RFC for the ASAR archive format so that the ASAR issues can be resolved?

**Comment by miniak** [comment]
@cookiengineer Since when is having non-ascii filenames a good idea?

**Comment by cookiengineer** [comment]
@miniak: Since there are people existing that do not speak English as a native language? Like literally, most of the people on the planet?

**Comment by miniak** [comment]
@cookiengineer Having the contents of the file in any language does not mean that the filename has to be localized. And as far as I know, UTF-8 can handle any language. And when only using the ASCII subset, you don't have to pay the price as with UTF-16.

**Comment by miniak** [comment]
@cookiengineer Also tar is an ancient format originally designed for tape archives with 512 byte blocks. Why not create something new considering today's requirements.

**Comment by cookiengineer** [comment]
@miniak If you want to go the new better-invention route, why not use brotli or zopfli or gzip container?

Your format is incomparable to even gzip deflate. It's literally just a concat, so you can't argue with tar being legacy here - because tar has the identical feature set AND is cross-platform, available everywhere. ASAR isn't and is not supported by any today's archive GUI tools and probably never will if the spec is missing.

**Comment by miniak** [comment]
@cookiengineer it's not my format :) let's agree to disagree, I don't want to argue.

**Comment by YurySolovyov** [comment]
I'd say we should rather fix asar and how electron handles it.
@paulcbetts 
>Uhhhh why would you want to be rewriting your own app's code at runtime

Well, to have browser-like F5-fix-F5 experience

**Comment by YurySolovyov** [comment]
@cookiengineer you can find some reasoning behind asar [`here`](https://github.com/electron/electron/issues/251#issuecomment-56289392)

**Comment by baconface** [comment]
Correct me if I am wrong but ASAR is completely optional in use. If you don't like it you don't have to use it. In the case of this issue Microsoft VS Code doesn't use an ASAR but the code in Electron still treats ASAR files like an archive. As a result their editor does too. Whereas they want them to be treated like any other editor would treat them.

And the idea of ASAR wasn't to reinvent an archive format but to create a new one that met the purposes specific to Electron. And other archive formats didn't meet this. I think NW.js is evidence that using a widely used archive format (zip) just doesn't work out especially with bigger and more complex programs.

**Comment by bpasero** [comment]
Another problem is that if you fork a process from electron, this process also gets ASAR support without asking for it. In our case we spawn node processes from electron (we do not ship our own node.js executable) for extensions that run in VS Code. These extensions use the fs module as usual but run into the ASAR issues as well. The only workaround is to ask each extension to set `process.noAsar = true; `in their start script which is bad because this couples extensions to the runtime (electron).

**Comment by bpasero** [comment]
Maybe `asar.js` could also check for an environment variable to be defined in addition to `process.noAsar` (close to https://github.com/electron/electron/blob/932b6dc0cf0c077dfc84a43cac49756f183769fd/lib/common/asar.js#L37)? @zcbenz @kevinsawicki would you accept such a PR or do you see issues? This would allow to fork a process where the environment asks to have asar support disabled and does not require the code that gets executed to set it.

**Comment by kevinsawicki** [comment]
> would you accept such a PR or do you see issues? This would allow to fork a process where the environment asks to have asar support disabled and does not require the code that gets executed to set it.

Yeah, an environment variable or command line flag sounds good to me 👍

**Comment by bpasero** [comment]
@kevinsawicki see https://github.com/electron/electron/pull/7479

**Comment by codebytere** [comment]
This has been done, closing!

**Comment by elimisteve** [comment]
This worked for me: https://github.com/electron-userland/electron-builder/issues/428#issuecomment-220810092
