### ISSUE TITLE
Spdy protocol error using fetch api to certain SSL API endpoints

### ISSUE THREAD

**Issue by sickboy** [electron/electron#6296]
* Electron version: 1.2.5
* Operating system: Windows 10 x64

The error occurs on some calls within a Webview, the Webview loads external content

Happened after upgrading from Electron 1.2.3, suspect is the Chromium update.

**Comment by mnquintana** [comment]
Can you paste the error and provide a minimal app that reproduces the issue? Thanks!

**Comment by sickboy** [comment]
Apologies, seems to have been a network related issue on my end..
