### ISSUE TITLE
Electron Installer Opening the Application Window Twice

### ISSUE THREAD

**Issue by ShivangiGa** [electron/electron#6300]
* Electron version:0.36.7
* Operating system:Windows

When I am generating windows installer using electron builder, Application window is opening twice.

My Main.xml is :

var app = require('app');
var BrowserWindow = require('browser-window');
var win = null;
app.on('ready', function() {
    win = new BrowserWindow({webPreferences: { nodeIntegration: false} });
    win.loadUrl('https://enterprisesearch.ultimatix.net/enterprisesearch/');
	win.on('closed', () => {
     win = null;
  });
});

// Quit when all windows are closed.
app.on('window-all-closed', () => {
   if (process.platform !== 'darwin') {
    app.quit();
  }
});

development package.json is:
{
  "devDependencies": {
     "electron-installer-squirrel-windows": "^1.3.0",
    "electron-packager": "^5.1.1",
    "electron-prebuilt": "0.36.7"
  },
  "build": {
    "win": {
      "iconUrl": "https://eatodo.s3.amazonaws.com/icon.ico"
    }
  },
  "scripts": {
    "dist": "build --platform win32 --arch x64"
  }
}

App package.json is:

{
  "name":"EnterpriseSearch",
  "version":"0.1.0",
  "main":"main.js",
  "author":"TCS",
  "description": "This is a desktop app for my space."
}

I am running command npm run dist

Installer gets generated properly. On clicking the exe window loads two times.

Please suggest.

**Comment by MarshallOfSound** [comment]
Please read the README and raise the issue on the correct repository...

https://github.com/electron/windows-installer#handling-squirrel-events

**Comment by kevinsawicki** [comment]
Closing this out, your application needs to handle the squirrel events in the link provided by @MarshallOfSound

**Comment by ShivangiGa** [comment]
Thanks for the response. It worked!!

**Comment by METASHONGKONG** [comment]
I have also encountered this problem. What I have done is to remake an electron app, re-package and re-make and installer. Then, no problem at all. There may be some problem if we always replace the same exe.

**Comment by juanpasolano** [comment]
I am adding 
```
```
