### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by violinner** [electron/electron#6303]
* Electron version: 1.2.2
* node v5.0.0
* npm v3.3.6
* Operating system: Windows 7 Enterprise v 6.1.7601 SP1 Build 7601

I am trying to install spectron on a host behind a corporate firewall.

I have set "npm config set registry [my local repository]".

Using the command "npm install --save-dev spectron",
the download of electron-chromedriver@1.2.0 fails with connect ETIMEDOUT.

The reason appears to be that in the script: download-chromedriver.js, 
var config contains "baseUrl: 'https://github.com/atom/electron/releases/download/' ...

Direct access to github is not allowed, and resources must be retrieved from local git repositories.
How can I install spectron on a Windows PC behind a firewall without direct access to https://github.com?

**Comment by kevinsawicki** [comment]
Thanks for bringing this up, I've added support for customizing the location of the URL used to download ChromeDriver in https://github.com/electron/chromedriver/pull/3

I've published new builds so if you use Spectron `3.2.4` or later, you should be able to set the `ELECTRON_MIRROR` environment variable to configure where it gets downloaded from and use a localhost URL or something else.

Please see https://github.com/electron/chromedriver#custom-mirror for more details.

**Comment by violinner** [comment]
Thank you for help installing behind a firewall, which works now.

On Windows 7, electron-chromedriver fails to start.
I have posted the details in another issue:
https://github.com/electron/electron/issues/6350

Does anyone have advice on how to start electron-chromedriver on Windows 7?
Thanks again.
