### ISSUE TITLE
Cannot build from tarball due to lack of .git directory

### ISSUE THREAD

**Issue by ftoledo** [electron/electron#6304]
* Electron version: 1.2.5
* Operating system: Linux Debian 64bits

Hi all i try to make a debian package for electron, i use pbuilder as my build system (for packaging)

fist, I can compile/build from *master* git clone without problem.

But if i try to build a specific version (such 1.2.5),  that do not have the .git directory insede of the tarball that downloaded from github, the bootstrap script fail when try get submodules: 

"Not a git repository (or any of the parent directories): .git"

make[1]: Entering directory '/tmp/buildd/electron-1.2.5'
python script/bootstrap.py -y -v
fatal: Not a git repository (or any of the parent directories): .git
Running in verbose mode
git submodule sync --recursive
None
Traceback (most recent call last):
  File "script/bootstrap.py", line 263, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 37, in main
    update_submodules()
  File "script/bootstrap.py", line 126, in update_submodules
    execute_stdout(['git', 'submodule', 'sync', '--recursive'])
  File "/tmp/buildd/electron-1.2.5/script/lib/util.py", line 177, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'sync', '--recursive']' returned non-zero exit status 128

any workaround to get it work? maybe a git init before run the bootstrap script?

thanks!

**Comment by kevinsawicki** [comment]
> any workaround to get it work? maybe a git init before run the bootstrap script?

I don't think `git init` will help since each submodule needs to be at a specific SHA-1 and that information is stored in `.git` and would be missing in a newly initialized repository.

I'm not sure there is a way to build from the tarball currently. It would require modifying the bootstrap script to initialize the submodules to have the correct commit checked out in each.

**Comment by jean-emmanuel** [comment]
You could also clone the repository at a specific version tag instead by doing `git clone <url> --branch <tag>` . Adding `--depth 1` would also avoid downloading the entire git history.

**Comment by zcbenz** [comment]
This is not possible with GitHub's tarball feature, the generated tarball doesn't include submodules, making it useless.
