### ISSUE TITLE
GNU/Linux: `dialog.showOpenDialog()` changing result extensions based on filters

### ISSUE THREAD

**Issue by jviotti** [electron/electron#6305]
I'm encountering a very weird issue, only in GNU/Linux.

Consider the following gist that shows an open dialog and presents the resulting filename in the screen: https://gist.github.com/jviotti/b8358165f1694228fbc31e400dbadab6, which you can run by `npm install && npm start`.

Now create a file with a `.img.gz` extension, like `foo.img.gz`. Using the `touch` command is enough.

Try to select it using the gist application. The `.img.gz` extension is replaced by `.zip` (or whatever is the first item of the extensions filter) for some strange reason.

The issue only seems reproducible with files containing multiple extensions, and when a dialog filter is present.

* Electron version: 1.2.5
* Operating system: GNU/Linux (Ubuntu 14.04 and Arch Linux)

**Comment by zcbenz** [comment]
I can reproduce with Ubuntu 14.04.

**Comment by jviotti** [comment]
@zcbenz Do you have an idea on what is causing this? Since you put the "beginner" tag on it, I'd love to give it a shot myself.

**Comment by zcbenz** [comment]
I'll create a pull request, it is quicker than explain it.

**Comment by jviotti** [comment]
Awesome, thanks a lot for the quick fix!
