### ISSUE TITLE
responseCallback is not supported

### ISSUE THREAD

**Issue by jtlindsey** [electron/electron#6307]
* Electron version: "electron-prebuilt": "^1.2.5"  
* Operating system: Ubuntu 14.04LTS  
* Node -v: 5.10.1  
* npm -v: 3.8.6  

When I run a basic electron app I get this message in the console:
`responseCallback is not supported`

My package.json
```
{
  "name": "my-electron-app",
  "version": "1.0.0",
  "description": " another app ",
  "main": "main.js",
  "scripts": {
    "start": "electron main.js"
  },
  "devDependencies": {
    "electron-prebuilt": "^1.2.5"
  }
}
```

**Comment by kevinsawicki** [comment]
What dev tools extensions do you have installed in that app?

That message is logged when an unsupported parameter is specified to a devtools extension API: https://github.com/electron/electron/blob/19d8a366b35536681cb77e634cb1e7dd387a1cc0/lib/renderer/chrome-api.js#L124

**Comment by jtlindsey** [comment]
`// Open the DevTools.`
 `mainWindow.webContents.openDevTools();`

**Comment by jtlindsey** [comment]
Sorry....another newbie making noise. Here is what caused the issue:
My package.json problem:
```
  "scripts": {
    "start": "electron main.js"
  },
```
Solution was to change it to:
```
  "scripts": {
    "start": "electron ."
  },
```
And the error is gone.

**Comment by Aerlinger** [comment]
Having the same issue, but the fix above doesn't work. Does anyone know the underlying source of this error? Also, why would specifying `"start": "electron ."` fix the problem vs. `"start": "electron main.js"`. It seems as though the error message could be improved.

**Comment by kevinsawicki** [comment]
@Aerlinger do you have any dev tools extensions installed? If so, which ones?

**Comment by Aerlinger** [comment]
@kevinsawicki Yup, I'm using Redux and React dev tools.

Redux DevTools 2.2.1.1 (lmhkpmbekcpmknklioeibfkpmmfibljd)
React Developer Tools 0.14.11 (fmkadmapgofadopljbjfkapdkoienihi)

They're being managed with `electron-devtools-installer` (1.1.5) (https://github.com/GPMDP/electron-devtools-installer):

```javascript
const installExtensions = async () => {
  if (process.env.NODE_ENV === 'development') {
    const installer = require('electron-devtools-installer'); // eslint-disable-line global-require
    const extensions = [
      'REACT_DEVELOPER_TOOLS',
      'REDUX_DEVTOOLS'
    ];
    const forceDownload = !!process.env.UPGRADE_EXTENSIONS;
    for (const name of extensions) {
      try {
        await installer.default(installer[name], forceDownload);
      } catch (e) {} // eslint-disable-line
    }
  }
};
```

**Comment by kevinsawicki** [comment]
> Yup, I'm using Redux and React dev tools.

So one or both of them is calling the `sendMessage`  devtools API which isn't currently supported by Electron and that is why the message is being logged.

**Comment by jtlindsey** [comment]
@Aerlinger I've removed that feedback as it wasn't intended to suggest a "fix" for the error. I was just posting to @kevinsawicki the results of the last change that I made for a project I was experimenting with. Trying to figure out why the error went away after my last change would require a lot more information than what i've posted.

**Comment by tomasro27** [comment]
I am trying to use Augury extension with electron, and I am getting the same error.  Are there any updates on how to make this work?

Thanks

**Comment by bluEEil** [comment]
I am experiencing the same problem as @tomasro27 with 1.4.6. I could really use a fix as well

**Comment by bluEEil** [comment]
Can anyone reopen the issue?
