### ISSUE TITLE
Displaced WebView incorrectly responds to touch events

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#6308]
* Electron version: All
* Operating system: Windows

When using a touch screen on Windows (or even remotely controlling a normal computer through teamviewer on a touch screen) users reported strange hitboxes on certain elements.

This issue was tracked down to the WebView using the same origin position as the main window for it's hitbox calculations.  A diagram illustrates this below.

![touchissue](https://cloud.githubusercontent.com/assets/6634592/16512533/a0dbb938-3fb0-11e6-85b6-e97734e3b9e7.png)

In this example, touching position A will respond as if you touched position B.

Downstream Issue: MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/875

If users disable my custom window borders (so the webview is now 100% width and 100% height of the actual window) then the touch events respond correctly.

**Comment by MarshallOfSound** [comment]
Relevant comment

> Track seek bar and volume sliders - the grab point on these seem to be above the actual UI element. I have to aim almost a centimetre above the orange dot to drag it successfully but otherwise works as expected. In chrome this works fine.

**Comment by zcbenz** [comment]
It looks similar to #5098, but it is in Flash. Can you try whether this problem occurs in Chrome apps? It can be tested in [this Chrome app](https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/webview-samples/browser).

**Comment by MarshallOfSound** [comment]
This [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=603133#c9) mentioned in your mentioned issue #5098 is exactly the issue that people were having.  I tested on latest Electron and looks like this bugfix made it into the `1.2.X` stream of electron 😄
