### ISSUE TITLE
Custom protocol on OS X does not include the url when launching the app

### ISSUE THREAD

**Issue by friksa** [electron/electron#6310]
* Electron version: 1.2.5
* Operating system: OSX 10.11.5

We are defining a custom protocol per:
http://electron.atom.io/docs/api/app/#appsetasdefaultprotocolclientprotocol-macos-windows

This is added to package.json when using electron-builder
````
  "build": {
    "protocols": [{
      "name": "GP6Launcher",
      "schemes": ["gp6"]
    }],
````

The app works as expected on Windows.  When you click on the custom link gp6://1234567, the app is launched and argv[1] contains gp6://1234567

On OS X, when you click on the same custom link, the app is launched.  However, argv[1] is absent.  The link launches the app, but there is no way to detect the actual custom link that was clicked on.

Please add the custom link to the argument list when launching the app so that electron.proces.argv includes the custom link as argv[1].

Thanks!

**Comment by zcbenz** [comment]
On macOS you have to subscribe to the `open-file` and `open-url` events, this is because macOS handles URL opening in a different way with other platforms.

**Comment by friksa** [comment]
Thanks so much! `open-url` did the trick.
