### ISSUE TITLE
Can't Load Pepper Flash on any Electron Version 1.2.5

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [electron/electron#6316]
* Electron version: 1.2.5 (x64 and x32 )
* Operating system: Windows

I had an application using Electron 0.36.8 running Flash perfectly using the code below:

```
app.commandLine.appendSwitch('--enable-npapi');

var ppapi_flash_path = null;
if(process.platform  == 'win32'){
  ppapi_flash_path = path.join(__dirname, 'pepflashplayer64_22_0_0_192.dll');
} else if (process.platform == 'linux') {
  ppapi_flash_path = path.join(__dirname, 'libpepflashplayer.so');
} else if (process.platform == 'darwin') {
  ppapi_flash_path = path.join(__dirname, 'PepperFlashPlayer.plugin');
}

app.commandLine.appendSwitch('ppapi-flash-path', ppapi_flash_path);
app.commandLine.appendSwitch('ppapi-flash-version', '22.0.0.192');
```

I was running version x64 of Electron and, therefore using the x64 version of the pepperflash dll.
Since most of my users still uses x32 computers, I downloaded the newest version of Electron (1.2.5), x32, changed the dll to pepflashplayer32_22_0_0_192.dll and BOOM, no Flash (Can't Load Plugin Message)

I wasted 2 days looking for informations, forums, sample codes and other Issues and didn't get any solution to the newer version not running Flash. At the end, I downloaded Electron version 1.2.5 x64 and kept my code with pepflashplayer64_22_0_0_192 and it also didn't work.

Same code, same DLL.
Electron 0.36.8 x64 runs it, Electron 1.2.5 x64 doesn't.

**Edited:** Tried another newer version (not so new), electron-v0.37.4-win32. PepperFlash worked fine.

**Comment by zcbenz** [comment]
When updating from < v1.0, you need to migrate from some deprecated APIs:
http://electron.atom.io/blog/2015/11/17/electron-api-changes

In your case I believe you should replace `web-preferences` with `webPreferences`. Please leave your complete code creating window if you have already migrated to new APIs and still see this problem.

**Comment by Marcelo-Petrucelli** [comment]
Actually I noticed some messages and errors from the old API, and changed some "requires" and the deprecated calls to the new ones. But my problem still persists. (I get no errors from the electron console when running on debug, also no errors. Neither my App nor Electron show any errors.)

```
'use strict';

const electron = require('electron');
const app = electron.app;  // Module to control application life.
const BrowserWindow = electron.BrowserWindow;  // Module to create native browser window.

app.commandLine.appendSwitch('--enable-npapi');

var ppapi_flash_path = null;
if(process.platform  == 'win32'){
  ppapi_flash_path = path.join(__dirname, 'pepflashplayer32_22_0_0_192.dll');
} else if (process.platform == 'linux') {
  ppapi_flash_path = path.join(__dirname, 'libpepflashplayer.so');
} else if (process.platform == 'darwin') {
  ppapi_flash_path = path.join(__dirname, 'PepperFlashPlayer.plugin');
}

app.commandLine.appendSwitch('ppapi-flash-path', ppapi_flash_path);
app.commandLine.appendSwitch('ppapi-flash-version', '22.0.0.192');

app.on('ready', function() {
  var size = electron.screen.getPrimaryDisplay().workAreaSize;
  mainWindow = new BrowserWindow({
      width: size.width,
      height: size.height,
      webPreferences: {plugins: true, webgl: true, webSecurity: false},
      minWidth: 800,
      minHeight: 600,
      frame: true,
    });

  mainWindow.loadURL('file://' + __dirname + '/index.html');
  app.on('window-all-closed', function() {
    // On OS X it is common for applications and their menu bar
    // to stay active until the user quits explicitly with Cmd + Q
    if (process.platform != 'darwin') {
      app.quit();
    }
  });
});
```

**Comment by zcbenz** [comment]
Can you try whether this file works for you? I copied it from Chrome 51 and it works for me.
[pepflashplayer.dll.zip](https://github.com/electron/electron/files/344576/pepflashplayer.dll.zip)

Also the code you pasted can not run. If you can still not get it working, please provide a minimal app that can actually run, because the problem is very likely in other parts of your code.

**Comment by Marcelo-Petrucelli** [comment]
Actually, I'll be only able to give you the correct, updated and complete code (and also run with the dll you just gave me), on Monday. I thank you for you reply, and I also ask you if you could send me the example that worked for you, with that given dll, so I can track where's my mistake :)

Keep it close and if, in any cases, my problem persists, I'll let you know ^_^

Thank you again @zcbenz

**Comment by zcbenz** [comment]
The code I used for testing is:

```js
const path = require('path')
const {app, BrowserWindow} = require('electron')

app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, 'pepflashplayer.dll'))
app.commandLine.appendSwitch('ppapi-flash-version', '22.0.0.192')

app.on('window-all-closed', function() {
  app.quit()
})

let mainWindow = null
app.on('ready', function() {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      plugins: true
    },
  })
  mainWindow.loadURL('http://www.adobe.com/software/flash/about/')
})
```

The arch of the plugin file is x64.

**Comment by Marcelo-Petrucelli** [comment]
Hello zcbenz,

I'm really sorry for taking your time. Your example worked perfectly with 1.2.5 and x32. There must be something really wrong with my code.... I'll fix it!

Thanks again for your help!

**Comment by czl1378** [comment]
Thank you, @zcbenz !I love you!
