### ISSUE TITLE
require c++ addon failure？

### ISSUE THREAD

**Issue by iptop** [electron/electron#6317]
* Electron version: 1.2.5 (ia32 and x64)
* Operating system: windows 7 x64

I create a nodejs c++ addon,use nodejs(v6.1.0) can require  this addon, using electron require this addon will fail.

Excuse me,If there is a difference between electron and nodejs require c + + addon? #

**Comment by kevinsawicki** [comment]
> If there is a difference between electron and nodejs require c + + addon?

There are differences. For native node modules to run in Electron they need to be compiled against Electron's v8 headers instead of node's v8 headers.

You can read more about it here: http://electron.atom.io/docs/tutorial/using-native-node-modules/

**Comment by iptop** [comment]
@kevinsawicki thank ！
