### ISSUE TITLE
OSX Notification not displaying app name correctly 

### ISSUE THREAD

**Issue by ccnokes** [electron/electron#6319]
* Electron version: 1.2.4
* Operating system: Mac OSX 10.11.5

When you receive multiple notifications on OSX while your computer is idle, it rolls them up into a single notification that looks like this: 

![lwscreenshot 2016-06-30 at 5 00 54 pm](https://cloud.githubusercontent.com/assets/1610343/16532063/c0f86c8a-3f8c-11e6-81be-ccc419437396.png)

Rarely, in my app, the name isn't being put in there--it's grabbing some number instead (see below). It looks like an old version of electron is being put there instead. 

![image](https://cloud.githubusercontent.com/assets/1610343/16532136/30f6af4c-3f8d-11e6-8632-4c78a04e7753.png)

My understanding is the Info.plist in the .app is responsible for providing that name (specifically the CFBundleDisplayName and CFBundleExecutable). I've verified that my app name is there and not 0.36. 

Any ideas on what might be happening or where I could look for the underlying source of this data? Let me know if you need any more details. Thanks!

**Comment by zcbenz** [comment]
How do the notifications sidebar and the notifications preference panel show your app's name? I can not think of any reason for this, except for wrong values in `Info.plist`.

**Comment by ccnokes** [comment]
So Notification Center does in fact show "0.36". Must have been an old configuration issue. However, the user's Info.plist (from more recent builds) showed the correct value. Strange that it doesn't update itself automatically. Thanks!
