### ISSUE TITLE
Canvas elements larger than 256x256 disappear after minimize-restore on Windows

### ISSUE THREAD

**Issue by MkFoster** [electron/electron#6320]
* Electron version: 1.2.5
* Operating system: Windows 7 (64-bit)

Canvas elements larger than 256x256 disappear on Windows when you set a minWidth and minHeight for the containing browser window, run the app, minimize, and then restore.  I was unable to duplicate on a Mac.  If you use the mouse to make the window considerably wider than the minWidth value, the problem does not duplicate.

Note: The problem may not manifest if dev tools are docked to the side.

Before minimizing the window:
![before-minimize](https://cloud.githubusercontent.com/assets/6801366/16534134/86f8945a-3fab-11e6-8e3d-a9e72480b6b9.jpg)

After restoring the window:
![after-minimize](https://cloud.githubusercontent.com/assets/6801366/16534141/8dbe7aa2-3fab-11e6-8932-94d270ec6e9a.jpg)

Duplication steps:

* Use the package.json, main.js and canvas.html code below to duplicate on Windows
* npm install & npm start
* Note the two canvas elements render OK
* Resize the window to the smallest allowed
* Minimize the window (Ctrl-M)
* Restore the window
* Note that the larger canvas on the left is no longer displayed

package.json:
```javascript
{
    "name": "electron-canvas-issue",
    "version": "1.0.0",
    "description": "Demo of canvas issue",
    "main": "main.js",
    "scripts": {
        "start": "electron ."
    },
    "devDependencies": {
        "electron-prebuilt": "^1.2.5"
    }
}
```

main.js:
```javascript
const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow
app.on('ready', function () {
    mainWindow = new BrowserWindow({
        title: 'Electron Canvas Issue',
        width: 850,
        height: 600,
        minWidth: 850,
        minHeight: 600
    });
    mainWindow.loadURL('file://' + __dirname + '/canvas.html');
});
```

canvas.html:
```javascript
<!DOCTYPE html>
<html>
<body>
<canvas id="myCanvas" width="500" height="500" style="border:1px solid #000;"></canvas>
<script>
    var c = document.getElementById("myCanvas");
    var ctx = c.getContext("2d");
    ctx.fillStyle = "#FF0000";
    ctx.fillRect(10,10,480,480);
</script>
<canvas id="myCanvas2" width="256" height="256" style="border:1px solid #000;"></canvas>
<script>
    var c2 = document.getElementById("myCanvas2");
    var ctx2 = c2.getContext("2d");
    ctx2.fillStyle = "#FF0000";
    ctx2.fillRect(10,10,230,230);
</script>
</body>
</html>
```

**Comment by zcbenz** [comment]
This is an upstream bug of Chromium, it seems to have bugs on drawing canvas, I created a Chrome app and the canvas does not even show in it:
[dialog-element.zip](https://github.com/electron/electron/files/344391/dialog-element.zip)

I'm closing this since we are not able to fix it on Electron's side, I suggest reporting this to Chromium's issues list instead.

**Comment by MkFoster** [comment]
In case anyone else runs across this... this appears to be a GPU related problem.  Apparently Chromium doesn't kick in GPU 2d acceleration until you get over a 256x256 canvas size which explains why this bug only manifests with larger canvas sizes.  Disabling hardware acceleration seems to be an effective work around for now.  Use the app.disableHardwareAcceleration(); method before app is ready.

**Comment by maxetime** [comment]
Hi, I've had a similar issue in browser Chrome/Opera, here is what I did which seems to fix the issue.
```
var refreshCanvas = function() {
    var canvasEls = document.getElementsByTagName('canvas');
    for(var i = 0; i < canvasEls.length; i++){
        canvasEls[i].width -= 1;
    }
    setTimeout(function(){
        for(var i = 0; i < canvasEls.length; i++){
            canvasEls[i].width += 1;
        }
    },0);
};
document.removeEventListener("visibilitychange",refreshCanvas, false);
document.addEventListener("visibilitychange",refreshCanvas, false);
```

Hope this can help :)
