### ISSUE TITLE
Install electron as a system-wide dependence package?

### ISSUE THREAD

**Issue by Menci** [electron/electron#6321]
* Electron version: *
* Operating system: *

It's too large to take a full electron build with my app. Imagine in the future all apps are built with electron, the duplicated electrons cost too much space.

I think it's better to offer a way to install electron as a system-wide dependence package. It can contain node.js and Chromium. Like Java, people can install it and run any electron apps.

On Linux, electron can be packaged as .deb, .rpm and .tar.xz for different distributions. And our developers can release packaged app that depand the electron package. Another idea is snappy packages, but only for Ubuntu.

I don't know much about windows and OS X, but I think a system-wide package may be not very difficult.

**Comment by MarshallOfSound** [comment]
This is being discussed in #673
