### ISSUE TITLE
Cannot include GLHelper header file

### ISSUE THREAD

**Issue by gerhardberger** [electron/electron#6325]
* Electron version: v1.2.5
* Operating system: OS X 10.11.6

I want to make some optimization for the `FrameSubscriber` class, and I need this `GLHelper` class for it located here: `content/browser/compositor/gl_helper.h`.
But when I try to build I get this error:
```
In file included from ../../atom/browser/api/frame_subscriber.cc:13:
In file included from /Users/gerhard/dev/electron/vendor/brightray/vendor/download/libchromiumcontent/src/content/browser/compositor/gl_helper.h:13:
/Users/gerhard/dev/electron/vendor/brightray/vendor/download/libchromiumcontent/src/gpu/command_buffer/client/gles2_interface.h:8:10: fatal error: 'GLES2/gl2.h' file not found
#include <GLES2/gl2.h>
         ^
1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by zcbenz** [comment]
You need to add `third_party/khronos/` to `include_dirs` of `direct_dependent_settings` in brightray:
https://github.com/electron/brightray/blob/master/brightray.gyp#L22-L34

And ship the headers in `libchromiumcontent`:
https://github.com/electron/libchromiumcontent/blob/master/script/create-dist#L202-L248
