### ISSUE TITLE
Security : Webview accessing from parent

### ISSUE THREAD

**Issue by ClementNerma** [electron/electron#6326]
* Electron version: v1.2.2
* Operating system: Windows 10 (Home Premium), Ubuntu 14.04 LTS/15.10, XUbuntu 15.10/16.04 LTS (64-bits for all)

I'm currently creating an application which have to run unsafe JavaScript content. This content must have access to an HTML DOM but must **NOT** access to the HTML page, only to an iframe or a webview for example.

For security reason, the unsafe content is runned under a VM to allow only some variables and prevent from using **window** or **document**.

**Problem :** When I create an iframe (sandboxed or not), any JavaScript code into the iframe can access to the parent frame by using *window.top*
When I create a webview, *window.top* returns the webview's window *but* I can't get the webview DOM Tree. And because webview will contain unsafe HTML content, I can't use IPC anymore.

Here is my code :

**main.html**

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Application</title>
</head>
<body>
  <webview src="iframe.html" id="unsafe_page"></webview>

  <script type="text/javascript">
    var frame = document.getElementById('unsafe_page');

    frame.addEventListener('console-message', (e) => {
      console.log(e.message);
    });

   // Now I want to get the webview's DOM Tree to modify it...
  </script>
</body>
</html>
```

**iframe.html** contains any HTML code, but **must** be able to run some scripts.

How can I do to solve this problem ?
Thanks by advance !

**Comment by zcbenz** [comment]
The webview is completely isolated from the host page, you can think it as an embedded BrowserWindow. So the only way to run code in webview is with Electron's APIs, e.g. webview.executeJavaScript or sending IPC messages.
