### ISSUE TITLE
AudioContext.decodeAudioData is providing incorrect results

### ISSUE THREAD

**Issue by darwingrosse** [electron/electron#6327]
* Electron version: 1.2.5
* Operating system: OS 10.11.5

Initially ran into this reading .aif files which produced horrible results. Created a test application (attached) that shows the inconsistent behavior when comparing reads/decodes of .aif, .mp3 and .wav files. The .aif file is worst, .wav is best, with mp3 in the middle (probably due to inconsistencies in decoding).

[AudioFileReader.zip](https://github.com/electron/electron/files/344586/AudioFileReader.zip)

**Comment by zcbenz** [comment]
Can you try if the same problem shows in the Chrome browser?

**Comment by darwingrosse** [comment]
Sorry, but I'm not sure how to write local code to perform this inside a browser.

**Comment by zcbenz** [comment]
You can just request the file directly:

```js
var audioctx = new AudioContext();
var request = new XMLHttpRequest();
request.open('GET', 'file:///tmp/test.mp3', true);
request.responseType = 'arraybuffer';

request.onload = function() {
  audioctx.decodeAudioData(request.response, function(buffer) {
    console.log("File read properly");
    console.log("Channels: " + buffer.numberOfChannels);
    console.log("Length: " + buffer.length);
    console.log("Sample Rate: " + buffer.sampleRate);
    console.log("Duration: " + buffer.duration);
  });
};

request.onerror = function(e) {
  console.log("Error on file read.");
};

request.send();
```

**Comment by darwingrosse** [comment]
Thanks for the example code!

Doing the above in Chrome 51.0.2704.106 64-bit produces the exact same output as the Electron example that I included in the OP: .wav read is correct, .mp3 off slightly (as expected for a decoded compressed format), .aif with incorrect number of channels, length and duration.

**Comment by zcbenz** [comment]
@darwingrosse Thanks for trying with it, can you report this to [Chromium's issues list](https://crbug.com) instead? This is an upstream bug that we are not able to fix on Electron's side.

Closing since it is an upstream issue.
