### ISSUE TITLE
doc: wrong link href in the quick-start

### ISSUE THREAD

**Issue by vsemozhetbyt** [electron/electron#6328]
I'm not sure how to fix this in the PR, so I'll just mention this.

In the [Differences Between Main Process and Renderer Process](https://github.com/electron/electron/blob/master/docs/tutorial/quick-start.md#differences-between-main-process-and-renderer-process) part of the **Quick Start** there is a link to FAQ part [How to share data between web pages?](https://github.com/electron/electron/blob/master/docs/faq/electron-faq.md#how-to-share-data-between-web-pages). Inside GitHub docs it is OK. However, in the site doc the FAQ address differs and after the redirection the hash disappears, so a user just sees the top of the FAQ page. May be http://electron.atom.io/docs/faq/electron-faq#how-to-share-data-between-web-pages should be replaced by http://electron.atom.io/docs/faq/#how-to-share-data-between-web-pages there.

**Comment by jlord** [comment]
Dang, yeah, this makes sense, another 🐛 tied to us moving the location of the FAQ on the website. I'll copy this issue to the website repo.
