### ISSUE TITLE
Strange interaction with Windows shell

### ISSUE THREAD

**Issue by vsemozhetbyt** [electron/electron#6329]
* Electron version: 1.2.5
* Operating system: Windows 7, standart shell (cmd)

1) After Electron launches from a Windows shell, an extra line break is added to the shell, so it seems as if Electron had not returned:

![1](https://cloud.githubusercontent.com/assets/10393198/16541269/2e580920-4087-11e6-8e8d-edf6cb31b0b6.gif)

2) However, Electron do returns: shell is responsive and the common prompt is restored after the first command:

![2](https://cloud.githubusercontent.com/assets/10393198/16541282/7237c2fc-4087-11e6-955f-cac375f47a9c.gif)

3) However, if I close the shell, the Electron window disappears, as if Electron had not returned before.

![3](https://cloud.githubusercontent.com/assets/10393198/16541299/ea0adbd4-4087-11e6-8f1a-1b04fa050c37.gif)

The app is very simple:

`package.json`
```json
{
  "name": "electron-test",
  "main": "main.js"
}
```
`main.js`
```js
/******************************************************************************/
'use strict';
/******************************************************************************/
const { app, BrowserWindow } = require('electron');
let mainWindow;
/******************************************************************************/
app.on('ready', createWindow).on('window-all-closed', app.quit);
/******************************************************************************/
function createWindow() {
  mainWindow = new BrowserWindow({ width: 400, height: 300 });
  mainWindow.on('closed', () => { mainWindow = null; });
  mainWindow.loadURL(`file://${__dirname}/main.html`);
}
/******************************************************************************/
```
`main.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='UTF-8'>
    <title>Electron Test</title>
    <style>
      body { font-family: monospace; white-space: pre; }
    </style>
    <script>
      window.addEventListener('load', () => {
        document.body.textContent = JSON.stringify(process.versions, null, '  ');
      });
    </script>
  </head>
  <body></body>
</html>
```

**Comment by zcbenz** [comment]
This is because Electron attaches itself to the console, otherwise it would not be able to print the output to console. To turn off this behavior, you can set the `ELECTRON_NO_ATTACH_CONSOLE` environment variable.
