### ISSUE TITLE
Support for proprietary codecs

### ISSUE THREAD

**Issue by GeorgS** [electron/electron#633]
I am trying to stream mp4 videos in my atom shell application.
I've tried the [Using MP3 & MP4 (H.264) using the video & audio tags](https://github.com/rogerwang/node-webkit/wiki/Using-MP3-%26-MP4-%28H.264%29-using-the--video--%26--audio--tags.) instructions from node-webkit.
When overwriting the `ffmpegsumo.so` from atom-shell with the `ffmpegsumo.so`  from chrome I get the following result at http://html5test.com.

![screen shot 2014-09-06 at 18 20 24](https://cloud.githubusercontent.com/assets/827885/4175708/4365383a-35e2-11e4-8049-813ecaec012b.png)

**Comment by ali** [comment]
Would love to have FLAC support in Electron.

I'm currently using `electron-prebuilt` (and `$ electron .`) to run my apps, so I'm still figuring out what I'd have to replace if I want `<audio>` elements and the Web Audio API to handle FLACs.

**Comment by LukasBombach** [comment]
What is the status on video codecs for electron? Googling this is very confusing as there are a lot of tickets for this and each one references the other. I have tried to play various videos, some work, some don't, feels like 50/50. I stumble upon people saying you need to compile ffmpeg.so or copy it from chrome. as for the first option: This is kind of hard and i am wondering why nobody distributes their compiled .so files. Ultimately i did have no luck with this yet (and oh btw i wanna do an open source projwct so i have no licensing issues). The second option just dis not work at all. 

So is there a way to get (most) videos working? Even stuff like mpeg-4 and other odd but commonly used codecs?

**Comment by well0nez** [comment]
any news?
