### ISSUE TITLE
Add API to trigger share menu on macOS

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#6330]
- Electron version: 1.2.5
- Operating system: macOS 10.11

So I can let users share content from my app.

I'm thinking an API that lets you popup a share menu from wherever you like and specify the content:

<img width="464" alt="screen shot 2016-07-02 at 23 10 07" src="https://cloud.githubusercontent.com/assets/170270/16542472/241c2540-40aa-11e6-8bdb-e4b3520df131.png">

_(Notes.app)_

And a `share` MenuItem role that you can just add to your menu:

<img width="395" alt="screen shot 2016-07-02 at 23 04 03" src="https://cloud.githubusercontent.com/assets/170270/16542462/ab9d4dd8-40a9-11e6-8af1-113e46964efa.png">

_(Desktop)_

**Comment by kevinsawicki** [comment]
Looks like Chrome is considering adding this:

https://bugs.chromium.org/p/chromium/issues/detail?id=465302
https://codereview.chromium.org/1105143005

**Comment by jordansteeves** [comment]
Would we also be able to use the Windows Share Data (https://msdn.microsoft.com/windows/uwp/app-to-app/share-data) to get it to work cross platform?

**Comment by ramaprasanna** [comment]
Hey guys, What is the status of this issue? I am planning to implement share feature in my electron app. Any pointers?

**Comment by Dexwell** [comment]
@ramaprasanna I filed that Chromium suggestion linked above; looks like it will finally be implemented in Chrome 60 which should release within a few weeks. After that I believe the Electron team can make it available to us.

**Comment by ramaprasanna** [comment]
Awesome. Thanks for the update :) .

**Comment by komplexb** [comment]
Very nice. How do I keep track of new Electron releases?

________________________________

**Comment by codebytere** [comment]
i'm gonna start into this feature soon

**Comment by dukewan** [comment]
Seems Chromium 64.0.3265 support share menu in the File menu. But it causes like 80ms delay in rendering the thread. I tested in 64.0.3282.186 and the share menu is not there, instead, "Email page location" replaced it. So maybe they **removed** it in the latest build. Electron 2.0.0-beta 1 is only upgrading Chromium version to 61, a long way to go.

![share menu](https://00e9e64bac305a555f65692145e731b9685d4ccc54c867ea74-apidata.googleusercontent.com/download/storage/v1/b/monorail-prod.appspot.com/o/16%2Fattachments%2F3b7ed730-d04e-4801-8ead-2330324f4ddd?qk=AD5uMEtmWS32h17xPjqDWRF2Mh593od2dKZOfOowluQsElsJNkP2B_z5inflPqFF21ECoYVxAHYf4l0cUfsz6z-MeDuixRIHC0i8CM2hAKrdjFzfSbYQii1Ou4_q6Ptxd0jGszsX1RCHyFTLozvQXb5plaU6YqzHOxUBVt6bWnJlIrNa4hHiKEt7WiYzHMRmoCqi5rDoLPNrvjlrOlxz4R9Dui-4gtz1Qt-FkunUILML6tr44bRdJj8nP99gWC3jiQT_I89lq22g_vAONnXNCyP5oCC9JSmPJZcykTMAIuDzC4np4CfVN9Wml8487WMunVOpqE3jyhqhE8VbuQ9eOc70dMCQHqxij403nLCOrXl6Gb4XXMWDbv4wt29HrH8-LqdRbewdT_DD8tKLWHya0DCJUTa3QeYsDQIk3twOAYctiwRjquJuuSCRii_fiQ_PcWq_o2pDGX_CbCabuY2Biee-qEU0CbEnucJpWCQ4jofbxsrCge-39N2XLXtjF3Pj2zE5OmkbRinRBdgCx5epzC93RJAn5D7sl8dTwW-nawBxbggV89JiswbjlKejxEJCQxhYDftjV5_qZMUfTthgGOZOPOmkM-8zcWdEc4MuOAXxIvydMV3PNUXDpwtZ2JCovCadROd9v3t-X0HTOYoxPaubSY9XKvIt4u1T_QRy4Mc0UbItfA49StcXcZtKUOdBTrw-r2YIxyODq3DcH7MxjJT-y-P5LM0keICzMRPEaeN1zwa8ow8Vxwn4v8SXHb0zbdXK6yxIef3mw3rQpigSZBk7NwbAHl7FnA)

Refs:
https://bugs.chromium.org/p/chromium/issues/detail?id=465302

**Comment by koalalorenzo** [comment]
Up? Any update? @Dexwell

**Comment by robinwassen** [comment]
Worth mentioning is that there is an experimental [Web Share API](https://www.chromestatus.com/feature/5668769141620736) standard which has been implemented in Chrome for Android.

The progress for implementing this in Chromium can be followed here: https://bugs.chromium.org/p/chromium/issues/list?q=component:Blink%3EWebShare

**Comment by dukewan** [comment]
Any update on this?

**Comment by codebytere** [comment]
@dukewan actually, i was just looking at Chrome's impl for this to see how feasible it would be for us. I can't make any promises but i've added it to my backlog and can try to get to it within the next month.

**Comment by dukewan** [comment]
@codebytere Thanks for the update and looking forward to hearing good news from you! ;D

**Comment by secit-pl** [comment]
Any update on this?

**Comment by Legio1221** [comment]
Been a few pretty days, any updates?

**Comment by codebytere** [comment]
hey! ok, so i spent some time playing around with this recently and got an mvp building locally.

This is possible conceptually, but there are a series of confounding factors here. For example, Chrome unilaterally assumes that you'll be sharing a URL, which is an assumption that a mac can't make: this throws out our ability to directly use Chrome and means we'd need to implement our own share menu controller.

Additionally, performing the share action is something that's typically implemented at the app level, and that requires knowledge in advance of what exactly is doing the sharing. For example, let's say you've got three windows open and you want to perform a URL-based share. Share services expect a url and sometimes title; from whence do we get the url? Is it the focused webContents' url? something else?

I'd love to hear more about what you all imagine this taking shape as before i proceed further.

**Comment by sindresorhus** [comment]
I would like the declare the types of things to share upfront, like URL and image, and then if the user clicks a share item, it would call a callback function I have provided that let's me return the thing to share, which could be from the active window or not. That's up to my app to decide. This would allow for the most flexibility.

**Comment by macta** [comment]
As an end user of an app using Electron, it is frustrating that we don't have a solution to this problem (which is a shame, as there are some great electron based app out there that would work so much better if they could share data more easily)

**Comment by LDubya** [comment]
Is there anything we can do to get this feature more traction? Can we post a bounty?

**Comment by ericpardee** [comment]
@felixrieseberg Slack needs this 👍

**Comment by LDubya** [comment]
@ericpardee @felixrieseberg if Slack does this, can it please be open source? This feature could single-handedly make Electron apps more appealing to users and developers. Easy sharing of data and documents might not be sexy rocket science, but it is so key to the end user.

**Comment by cawa-93** [comment]
In general, there is a [Web Share API](https://www.w3.org/TR/web-share/). However, Chrome supports it on smartphones only ([Can i use](https://caniuse.com/#feat=web-share)).

For example, if you open [Web Share API demo](https://web-share.glitch.me) in Safari you will then be able to get the "Share" dialog typical for your platform.

<img width="568" alt="Знімок екрана 2020-03-25 о 12 08 49" src="https://user-images.githubusercontent.com/1662812/77525251-64e0f880-6e91-11ea-8eef-672e3e235df4.png">

However, this will not work in Google Chrome on macOS. 

It also exists [Web Share Target API](https://wicg.github.io/web-share-target/). Але його розробка і підтримка на ще більш ранньому етапі.

**Comment by LDubya** [comment]
@cawa-93 this has been mentioned previously. Doesn’t look like we can expect Chrome to implement that on Desktop. Looks like browser developers are just keeping it on mobile.

However, MacOS already has native share menu functionality that any app can tap into. All the Electron app would need to do is to tap into the native MacOS API for triggering a share menu and interacting with it.

API:
https://developer.apple.com/design/human-interface-guidelines/macos/extensions/share-extensions/

**Comment by aabuhijleh** [comment]
The share **submenu** and the [share **extension**](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/share-extensions/) are two different things. The share extension requires dealing with native macOS APIs and unfortunately there's no easy way to implement this in an Electron app.

Looking at this [stackoverflow question](https://stackoverflow.com/questions/45612515/how-to-embed-a-mac-app-extension-in-an-electron-app), it looks like there's a "hacky" way to implement this. I wish there was a better way or at least a clear guide explaining how to do this...
