### ISSUE TITLE
Keyboard events sent with webContents.sendInputEvent work on macOS but not Windows

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#6331]
I've been working with sendInputEvent all weekend on macOS and jumped over to Windows 10 to try things out. Turns out keyboard events sent like this:

```
webContents.sendInputEvent({
	type: 'char',
	keyCode: key,
});
```
aren't working on Windows 10 but work perfectly on macOS.

I was, however, able to get these events working on Windows 10:

```
webContents.sendInputEvent({
	type: 'keyDown',
	keyCode: ...,
});
webContents.sendInputEvent({
	type: 'keyUp',
	keyCode: ...,
});
```

I haven't dug deep into the issue so I don't have more to report... hopefully it is an easy fix.

* Electron version: 1.2.5
* Operating system: Windows 10

**Comment by kirkouimet** [comment]
I was able to get the `keypress` event to fire on Windows if I do all of these events in this order:

```
webContents.sendInputEvent({
	type: 'keydown',
	keyCode: key,
});
webContents.sendInputEvent({
	type: 'keyup',
	keyCode: key,
});
webContents.sendInputEvent({
	type: 'char',
	keyCode: key,
});
```

Not sure why it is firing with just the `char` event on macOS but not on Windows...

**Comment by zcbenz** [comment]
You can reference how nightmare implements this:
https://github.com/segmentio/nightmare/blob/c61d5cf426754afa0416a7d9bbb5efdf8dc610e3/lib/runner.js#L350

Each platform handles keyboard events differently, so for some platforms wrong sequence may also work.
