### ISSUE TITLE
globalShortcut  not support register Pause

### ISSUE THREAD

**Issue by iloveyo123u1** [electron/electron#6332]
node 6.1.0, 
Chrome 51.0.2704.103
 Electron 1.2.5.
win 10 x64

```
  const hotKeyPause = globalShortcut.register('Pause', function () {
            console.log(1111111111111);
    });
```

**Comment by zcbenz** [comment]
I think you need to use `MediaPlayPause`. Also the global shortcut only works when the shortcut has not been taken by other apps, if the operating system or other app is listening to the shortcut, it will also not work.
