### ISSUE TITLE
Set application to open specific file type

### ISSUE THREAD

**Issue by T-Specht** [electron/electron#6335]
* Electron version: 1.2.5
* Operating system: Mac OS X 10.11.5

I would like my app to be able to open .txt straight from Finder (double click the file and the app opens up and loads the file).
All the ways on how to do it that I found didn't really work.

I would be really grateful if somebody could help me to find a solution for the problem.

**Comment by zcbenz** [comment]
You need to edit the `Info.plist` to add supported file types for your app, for more information please read Apple's documentations or search for existing discussions.
