### ISSUE TITLE
offsetWidth TypeError in console log

### ISSUE THREAD

**Issue by imasood** [electron/electron#6336]
* Electron version: 1.2.5
* Operating system: Ubuntu 16.04

i have full screen mode in my electron app and when enter and leave to full screen, i got bellow error in console.
where is wrong?
`Uncaught TypeError: Cannot read property 'offsetWidth' of null`

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by zcbenz** [comment]
Closing until more information is provided.
