### ISSUE TITLE
Some questions about electron-rebuild

### ISSUE THREAD

**Issue by Xiao-Yaran** [electron/electron#6339]
* Electron version:V1.2.3
* Operating system:WIN7-32

Masters,I am new to node.js and electron ,If electron-rebuild rebuild native module successfully,which folder is the rebuilding native module in? The modules which  I rebuild is global modules(npm install XX -g) ?

**Comment by MarshallOfSound** [comment]
`electron-rebuild` rebuilds the native modules in place.  I.e. The Build directory (or wherewhere the compiled code ends up nomally) inside your module folder inside your node_modules folder.
