### ISSUE TITLE
Is there any way to know about the system state?

### ISSUE THREAD

**Issue by Furqankhanzada** [electron/electron#6343]
* Electron version: latest
* Operating system: Linux, Windows, Mac

Any way through which an event fires when system goes to IDLE.

**Comment by MarshallOfSound** [comment]
What do you mean by "IDLE"

If you mean when the system goes into suspend mode

https://github.com/electron/electron/blob/master/docs/api/power-monitor.md#event-suspend

If you mean when the user is **inactive** I.e. Doesn't use the system for a certain amount of time, you would have to implement that yourself

**Comment by enlight** [comment]
Use https://github.com/paulcbetts/node-system-idle-time

**Comment by zcbenz** [comment]
Thanks @enlight for pasting the module, I'm closing this since there is existing node module doing the work.
