### ISSUE TITLE
node-groove errors on electron >= 0.36.8

### ISSUE THREAD

**Issue by johnmuhl** [electron/electron#6346]
* Electron version: >= 0.36.8
* Operating system: Ubuntu 16.04

After the upgrade from 0.36.7 node-groove returns `open file failed` for any file access. Did something change with file system access that could cause this? The same code runs in plain nodejs v4, 5 & 6.

**Comment by zcbenz** [comment]
Have you tried rebuilding the module with electron-rebuild?

**Comment by johnmuhl** [comment]
Not with electron-rebuild (it never works for me) but with whatever the electron bundled version of node is. So for 0.36.x I built with 5.1.1; 1.2.5 w/ 6.1.0 etc.

**Comment by zcbenz** [comment]
You have to follow [Using Native Node Modules](http://electron.atom.io/docs/tutorial/using-native-node-modules/) to build modules, because the V8 version shipped in Electron is not always the same with Node.

**Comment by johnmuhl** [comment]
None of the methods on that page change anything but building the module is not the problem.

For example 0.36.7 and 0.36.8 use the exact same versions of node, chrome and v8; everything works well with 0.36.7 but 0.36.8 shows "open file failed" when trying to open a file; other parts of the module also work fine in 0.36.8 it's only trying to open files that fails.

**Comment by johnmuhl** [comment]
I think the problem is with one of (from the 0.36.8 changelog):

> - Link with ffmpeg dynamically.
> - Provide prebuilt binaries of ffmpeg which do not include proprietary codecs.

Increasing the logging verbosity I see:

~~~
No URL Protocols are registered. Missing call to av_register_all()?
./test.wav: unrecognized format
~~~
