### ISSUE TITLE
Could the checkbox be used in dialog ?

### ISSUE THREAD

**Issue by dtysky** [electron/electron#6348]
* Electron version:

0.37.2

* Operating system:

OSX

Hi, I want to use the checkbox in dialog for my application as follows:  

![6fcbc578-ad88-45e3-887e-62454201824f](https://cloud.githubusercontent.com/assets/7337763/16574913/69e6e430-42b6-11e6-866c-7d314df3c0d6.png)

Are there any ways to make it possible ?

Thanks.

**Comment by zcbenz** [comment]
No, it is not supported in Electron. Adding checkbox to file dialogs is a platform-specific feature that can not be implemented on Windows and Linux, so I'm closing this as won't fix.
