### ISSUE TITLE
electron-chromedriver fails on Windows 7 with ENOENT

### ISSUE THREAD

**Issue by violinner** [electron/electron#6350]
* Electron version: v1.2.2
* Operating system: Windows 7

Running the following command:
     node_modules\.bin\chromedriver --url-base=wd/hub --port=9515 --verbose
Results in an error:
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn C:\[my-path]\electron\node_modules\electron-chromedriver\bin\chromedriver ENOENT
    at exports._errnoException (util.js:860:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:450:9) ...

Following similar reports, it is confirmed that "C:\Windows\system32" is on the path,
and that the problem still exists running cmd under as system admin.

Any advice on how to proceed on Windows 7 would be appreciated.

**Comment by kevinsawicki** [comment]
It looks like `chromedriver` does not exist which means perhaps the install failed or the file was removed somehow.

Can you delete `C:[my-path]\electron\node_modules\electron-chromedriver` and try reinstalling and verify afterwards that `C:[my-path]\electron\node_modules\electron-chromedriver\bin\chromedriver`?

If you still have issues after this please open a new issue on https://github.com/electron/chromedriver

**Comment by violinner** [comment]
The google-apis chromedriver is not downloadable due to a firewall.
    ( http://chromedriver.storage.googleapis.com/2.21/chromedriver_win32.zip )
Is there an environment variable or configuration that will allow a local repository to relay or mirror it?

**Comment by kevinsawicki** [comment]
> Is there an environment variable or configuration that will allow a local repository to relay or mirror it?

@violinner yes there is, see https://github.com/electron/chromedriver#custom-mirror for more details, closing this out.

**Comment by violinner** [comment]
Using the custom mirror setting or settings, electron-webdriver gets farther along, but does not install the google-apis chromedriver.  

To get to testing without necessarily solving all the automation,  I can manually download google-apis chromedriver and unpack chromedriver.exe  It runs.

How can I do what was intended so that it runs with the electron-webdriver (or is that the same thing)?

**Comment by violinner** [comment]
@kevinsawicki Apparently on Wiindows, Application takes path : an absolute path to the location of electron.cmd, and args: array containing an absolute path to the location of the application under test (directory containing main.js?)

**Comment by kevinsawicki** [comment]
> Apparently on Wiindows, Application takes path : an absolute path to the location of electron.cmd, and args: array containing an absolute path to the location of the application under test (directory containing main.js?)

Which library are you referring to that takes a path? Are you using spectron to run your tests?
