### ISSUE TITLE
desktopcapturer should include size/location of sources

### ISSUE THREAD

**Issue by friksa** [electron/electron#6351]
- Electron version: 1.2.5
- Operating system: OSX 10.11 and Windows

When using desktopcapturer.getSources, you get a list of screens and windows that can be captured with thumbnails.  However, you have no idea what the size of the original window is.

When calling navigator.webkitGetUserMedia with no dimensions or max dimensions, the image tends to be smaller than the actual window.  So the strategy is for the constraints to use large values for the max dimensions.  This works for the most part, however, smaller windows are captured larger than their actual size.  The result is that small windows might be captured at 200% of the actual size.

If desktopcapturer.getSources included the width and height, then you can capture the window at the correct size and know that you are screen sharing the window at the actual size.

**Comment by Quramy** [comment]
👍

**Comment by winneon** [comment]
How would I go about getting these dimensions from `.getSources`?

**Comment by sbosell** [comment]
@winneon did you find a solution to this?

**Comment by winneon** [comment]
@sbosell No I did not. I eventually abandoned the project for a different language and framework because I couldn't get it working correctly within Electron's own limitations.

**Comment by PerfectionCSGO** [comment]
getSources reports the following sources: 
```[{"id":"screen:0:0","name":"Screen 1","thumbnail":{}},{"id":"screen:1:0","name":"Screen 2","thumbnail":{}}]```

I have Screen 2 on the left and Screen 1 on the right. I'm using Jimp to merge these images side by side for fullscreenshots. But there is no way of telling the order of screens or their screen locations...

**Comment by codebytere** [comment]
Given that there aren't any clear solutions to this, and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!

**Comment by perf2711** [comment]
Any update on this?

**Comment by pavlobu** [comment]
I don't know if it helps, but you can get original window size from stream created by navigator.mediaDevices.getUserMedia(...)

so first you get your stream with something like this

```javascript
navigator.mediaDevices.getUserMedia({
      audio: false,
      video: {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore: fine here, mandatory does not exist, it's a problem with types
        mandatory: {
          chromeMediaSource: 'desktop',
          chromeMediaSourceId: sourceID, // a sourceID string

// !!! note NO size constrains here !!!

          15, // minFrameRate
          60, // maxFrameRate
        },
      },
    });
```


then you can work with your stream object to get window size like this:

```javascript
navigator.mediaDevices.getUserMedia({ ... }).then((stream) => {
  stream.getVideoTracks()[0].getSettings().width
  stream.getVideoTracks()[0].getSettings().height
});


```

that is what I'm doing in one of my projects

**Comment by friksa** [comment]
The issue is when you have multiple displays where one is a HiDPI display.  When you capture a feed with no dimensions on the HiDPI monitor, it could be 3 times larger than expected when streamed and displayed on a standard remote monitor.

If you knew what monitor it was captured on, you can determine the scaling and adjust the dimensions so it will not look larger than life on the remote side.

**Comment by pavlobu** [comment]
Got it. When for me that functionality is enough for others may need more precision.
Quiting @PerfectionVR 


> getSources reports the following sources:
> `[{"id":"screen:0:0","name":"Screen 1","thumbnail":{}},{"id":"screen:1:0","name":"Screen 2","thumbnail":{}}]`
> 
> I have Screen 2 on the left and Screen 1 on the right. I'm using Jimp to merge these images side by side for fullscreenshots. But there is no way of telling the order of screens or their screen locations...
> 
> P.S. This is in electron 1.7.11

and electron documentation https://www.electronjs.org/docs/api/structures/desktop-capturer-source
In newer versions of electron you indeed get display ID which corresponds to exact Dsiplay object id from screen API
https://www.electronjs.org/docs/api/structures/display

that Display object includes information you may need such as: scaleFactor, size, bounds, rotation etc.

You would have to use a setInterval with some delay, to constantly check the window location in real time and do calculations accordingly with scale factor of that display.

This is a suggestion, I haven't tried that myself

**Comment by Sgt-Tesla** [comment]
Correct me if I'm wrong, but currently there is still no way to determine the location of the window (not just its width and height, but its coordinate of its top left corner).

**Comment by friksa** [comment]
> In newer versions of electron you indeed get display ID which corresponds to exact Dsiplay object id from screen API

@pavlobu thanks for pointing that out.  That will solve the scaling issue for me.

@Sgt-Tesla nothing I am aware of, but it would be super useful to have.

**Comment by tym3515** [comment]
Can the new version of desktopCapturer get the size and position of the window in the future?

**Comment by spi96** [comment]
> Can the new version of desktopCapturer get the size and position of the window in the future?

Is there any update regarding this? Or does anybody have a workaround to get the location of the `window` sources, including native solutions?
