### ISSUE TITLE
spectron and chromedriver installation fails on Windows 7

### ISSUE THREAD

**Issue by violinner** [electron/electron#6352]
* Electron version: 1.2.2
* Operating system: Windows 7 (6.1.7601 SP1)

Using an alternate repository configuration in .npmrc, 
and running the command:  
    "npm install spectron --verbose"

download-chromedriver.js defaults to the wrong version of electron-chromedriver, and fails.

A log extract showing the error is below.  The version requested changed from 1.2.1 to 1.2.0:
(start)
npm info lifecycle electron-chromedriver@1.2.1~install: electron-chromedriver@1.2.1
&gt; electron-chromedriver@1.2.1 install C:\Users\[my-id]\[my-workspace]\node_modules\electron-chromedriver
&gt; node ./download-chromedriver.js
Downloading http://my/local/artifactory/.../electron/1.2.0/chromedriver-v2.21-win32-x64.zip failed: Non-200 response (404)
(end)

**Comment by kevinsawicki** [comment]
The Electron ChromeDriver builds are only available in the first release of each minor electron version, so 1.1.0, 1.2.0, etc.

So there is no 1.2.1 version available from https://github.com/electron/electron/releases/tag/v1.2.1

It is instead available from the 1.2.0 release at https://github.com/electron/electron/releases/tag/v1.2.0

So if you are using a custom mirror, you need to make sure they are available at the `1.X.0` URLs in your custom repository.

**Comment by violinner** [comment]
The 1.2.0 version does not work behind a firewall, as the download URL is hard-coded.
Version 1.2.1 adds configuration, with the original as a default:

var baseUrl = process.env.NPM_CONFIG_ELECTRON_MIRROR ||
  process.env.ELECTRON_MIRROR ||
  'https://github.com/electron/electron/releases/download/v'

So this fix will not be available until version 1.3.0?
Is there a manual way to put the pieces together behind a firewall so testing can begin?

Thanks!

**Comment by kevinsawicki** [comment]
Hmm, you should be able to get version 1.2.1 working if you make the URL ` http://my/local/artifactory/.../electron/1.2.0/chromedriver-v2.21-win32-x64.zip ` available to it can download the Electron assets from there.

**Comment by violinner** [comment]
Great - thanks for the help.
