### ISSUE TITLE
Electron throws if package.json is in UTF-8 with BOM

### ISSUE THREAD

**Issue by vsemozhetbyt** [electron/electron#6353]
* Electron version: 1.2.5
* Operating system: Windows 7

An error dialog with the `Unexpected token in JSON at position 0` message appears.

Electron properly strips BOM from `.js` and `.html` files, why not to do so for `package.json`? Node.js, npm, eslint, NW.js  strip BOM from `package.json` in UTF-8.

**Comment by vsemozhetbyt** [comment]
@kevinsawicki I still get this exception in prebuilt 1.2.6 for Win x64 despite of changelog.

**Comment by kevinsawicki** [comment]
>  I still get this exception in prebuilt 1.2.6 for Win x64 despite of changelog.

@vsemozhetbyt How are you launching your app? Are you calling `electron` with a path?

**Comment by vsemozhetbyt** [comment]
Yes. I've tried two ways.

![1](https://cloud.githubusercontent.com/assets/10393198/16635160/b60dca44-43d9-11e6-97de-aff329449366.png)

![2](https://cloud.githubusercontent.com/assets/10393198/16635161/b60f4360-43d9-11e6-8601-d209cefe4267.png)

Should I test another launching commands?

**Comment by kevinsawicki** [comment]
> Should I test another launching commands?

The pull request that originally closed this issue addressed the issue of launching a packaged app with a BOM in the `package.json`.

Launching from the command line was not addressed, I will fix it now, apologies for the confusion.

**Comment by vsemozhetbyt** [comment]
Oh, I'm also sorry for not to be clear enough. Thank you.
