### ISSUE TITLE
PPAPI - Registering pepper plugins

### ISSUE THREAD

**Issue by kjpou1** [electron/electron#6358]
* Electron version: 1.2.5
* Operating system: Windows 10 

More a question than an issue/enhancement right now as may not understand the process fully and am missing something.

Right now to use plugins we have to register them via `app.commandLine.appendSwitch('register-pepper-plugins', 'XXXXXX;application/x-ppapi-hello');`

We then need to activate the plugins when creating the browser windows with:  
```
'webPreferences': {
                'plugins': true
            }
```

Then we specify in the `<embed> `tag type 'application/x-ppapi-hello' which tells the embedded object that for this `<embed>` tag to used the plugin registered above.

This is working fine but was wondering if there was a more transparent way to do this with a configuration file of some sort.

Is there an existing way where we can specify the plugin type and the plugin module to load when the type is loaded from the `<embed>` tag.  Basically it would automatically load and register those modules bypassing the `appendSwitch` and `webPreferences` configurations.

Thanks in advance for any information.

**Comment by zcbenz** [comment]
Unfortunately that's how Chromium's plugin system works, you have to register the plugins before loading the page, there is no way to dynamically load a plugin on request.
