### ISSUE TITLE
Start electron App on CD/DVD fails

### ISSUE THREAD

**Issue by chuenniger** [electron/electron#6361]
* Electron version: 1.2.5
* Operating system: darwin-x64, Linux x64

Hi

I try to burn one app to CD/DVD. 

> ➜  dvdtemplate tree -L 1
> .
> |-- README
> |-- app
> |-- autorun.inf
> |-- autorun.sh
> |-- electron-v1.2.5-darwin-x64
> |-- electron-v1.2.5-linux-x64
> |-- electron-v1.2.5-win32-x64
> |-- index.html
> |-- linux.sh
> |-- osx.sh
> `-- win.bat

> 4 directories, 7 files

`➜  dvdtemplate tree -L 1
.
|-- README
|-- app
|-- autorun.inf
|-- autorun.sh
|-- electron-v1.2.5-darwin-x64
|-- electron-v1.2.5-linux-x64
|-- electron-v1.2.5-win32-x64
|-- index.html
|-- linux.sh
|-- osx.sh
`-- win.bat

4 directories, 7 files`

I get an error If i try start the app (burned on CD/DVD)

`electron-v1.2.5-darwin-x64/Electron.app/Contents/MacOS/Electron app/
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Volumes/dvdtemplate/electron-v1.2.5-darwin-x64/Electron.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
	/Volumes/dvdtemplate/electron-v1.2.5-darwin-x64/Electron.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
[1]    77665 trace trap  electron-v1.2.5-darwin-x64/Electron.app/Contents/MacOS/Electron app/`

`pwd
/Volumes/dvdtemplate`

But if I try this in the directory it works fine

`electron-v1.2.5-darwin-x64/Electron.app/Contents/MacOS/Electron app/ 
`

Do you have an idea or a solution for me?

Regards,
Christian

**Comment by zcbenz** [comment]
Does the app start on Windows and Linux? And what will happen if you burn the Chrome browser into the DVD?

**Comment by chuenniger** [comment]
> Does the app start on Windows and Linux? And what will happen if you burn the Chrome browser into the DVD?
The app starts on Windows correctly, Linux won't work too. 

I've not tested to burn the browser directly to the dvd.

**Comment by zcbenz** [comment]
DVD usually has no difference with normal disks, especially on Linux. I suggest reporting this to the disk burner software instead.
