### ISSUE TITLE
Accelerator is not working without combination key

### ISSUE THREAD

**Issue by Gloridea** [electron/electron#6362]
* Electron version: 1.2.5
* Operating system: OS X 10.11.5

Accelerator is not working without combination key (e.g., 'H') since 1.2.4 (at 1.2.3, it works fine.)
It works well if accelerator is combinated key (e.g., 'CmdOrCtrl+T')

[accelerator-not-working.zip](https://github.com/electron/electron/files/349634/accelerator-not-working.zip)

**Comment by kevinsawicki** [comment]
Thanks for reporting this, I believe this is a regression due to #6068, I've pushed up a fix for it in #6370
