### ISSUE TITLE
Setting up localization in Electron 

### ISSUE THREAD

**Issue by epezhman** [electron/electron#6365]
* Electron version: 1.2.5
* Operating system: All

Hi, I need to provide my app in different languages (based on OS Locale) but I couldn't find anything in the documentations, is there any clean way supported by Electron? what's the suggestion? thanks

**Comment by PauloLira** [comment]
+1

**Comment by MarshallOfSound** [comment]
I don't believe there is a built in way in electron to handle this.  But I ended up doing some JS magic with JSON files to get localization into my app.

For strings used in JS we have https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/_locales/_provider.js

For strings used in HTML we have https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/inject/generic/translations.js

This allows us to do things like

```html
<h4 is="translation-key-h4">modal-confirmTray-title</h4>
<span is="translation-key">button-text-dont-tell-me-again</span>
```

And the appropriate translations are injected into the DOM.  Not sure if this is the kind of thing you are looking for, but it works well for us 👍

**Comment by baconface** [comment]
To do what you are specifically looking to do detect the language from the OS using a package like [os-locale](https://www.npmjs.com/package/os-locale) and set the translations programmatically using [your own means](http://stackoverflow.com/a/228879/2223704) or a [third parties](http://i18next.com/).

**Comment by zcbenz** [comment]
You can call `app.getLocale()` or `navigator.language` to get the locale of current system, but there is no built-in API to provide a localization solution.

If you want to reference how other projects implement i18n, [VS Code](https://github.com/Microsoft/vscode) is also a good example.
