### ISSUE TITLE
Cannot load url "about:gpu"

### ISSUE THREAD

**Issue by remss** [electron/electron#6366]
* Electron version: 1.2.3
* Operating system: Windows 7 amd64

I got a blank page trying to load url "about:gpu"

**Comment by paulcbetts** [comment]
Try chrome://gpu

**Comment by remss** [comment]
Ok my bad, typing "about:gpu" in Chrome address bar will resolve to `chrome://gpu`
My other mistake was to try a `window.location.href = "chrome://gpu"` that is not supported. Only `mainWindow.loadURL( "chrome://gpu")` works.
Thanks
