### ISSUE TITLE
The --disable-webgl does not work

### ISSUE THREAD

**Issue by remss** [electron/electron#6367]
* Electron version: 1.2.3
* Operating system: Windows7 amd64

Using --disable-webgl seems to have no effect. The http://webglreport.com/ says webgl is supported.

How to disable webgl/gpu to force CPU rendering with [SwiftShader](http://blog.chromium.org/2016/06/universal-rendering-with-swiftshader.html)?

**Comment by zcbenz** [comment]
You can call the `app.disableHardwareAcceleration` API:
http://electron.atom.io/docs/api/app/#appdisablehardwareacceleration

**Comment by remss** [comment]
Thanks it has disable GPU rendering, but now `chrome://gpu` says WebGL is unavailable so ithe SwiftShader seems not been enabled. How to enable WebGL rendering with SwiftShader ?

**Comment by ChugunovRoman** [comment]
Same issues.
I take the SwiftShader libraries from installed Google chrome, from /opt/google/chrome/swiftshader folder and put it in swiftshader folder the root app folder. And now chrome://gpu says WebGL is software only. And app works is very slow, but works... If put the prebuild binary files from [here](https://drive.google.com/drive/folders/0B8_BlOx5-97CVTAyVDc4eGctaDA) in the swiftshader folder, than Electron can not find the SwiftShader libraries and says that WebGL is unavailable.
How to fix the slow work of app, If using the SwiftShader?

**Comment by ChugunovRoman** [comment]
(https://youtu.be/PH72OEnLfSk)[Video] about my problem.
