### ISSUE TITLE
defaultPath does not work in dialog.showOpenDialog when called from renderer process

### ISSUE THREAD

**Issue by seanzer** [electron/electron#6371]
* Electron version: 1.2.3 32-bit
* Operating system: Windows 10 64-bit

It seems like when using the proxied dialog via electron.remote, defaultPath doesn't work. Is that intentional?

The same code called from the main process does work as expected.

**Comment by zcbenz** [comment]
Can you show how you are calling the API?

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by zaggino** [comment]
@zcbenz I can confirm that `defaultPath` is not being respected, calling it like this from the renderer process.

https://github.com/zaggino/brackets-electron/blob/0389d27b8f744397ba0a2f23c3a7466c897931d8/app/appshell/fs-additions.ts#L108-L139
