### ISSUE TITLE
Is pdf.dll still needed?

### ISSUE THREAD

**Issue by vsemozhetbyt** [electron/electron#6373]
* Electron version: 1.2.6
* Operating system: Windows 7 x 64

`pdf.dll` is mentioned in the `webContents` doc:

> Note: On Windows, the print API relies on pdf.dll. If your application doesn’t need the print feature, you can safely remove pdf.dll to reduce binary size.

and in the "Windows Store Guide" doc (package file tree).

However, in the last precompiled versions for Windows x64 there is no `pdf.dll`. And `webContents.printToPDF` seems to work without it. Are these mentions some legacy fragments?

**Comment by zcbenz** [comment]
It is actually not needed anymore, I'll update the docs.
