### ISSUE TITLE
Supporting more video formats

### ISSUE THREAD

**Issue by greggman** [electron/electron#6374]
* Electron version: ??
* Operating system: all

Chrome is bound by browser standards but Electron is not (like reading files).

Is there any reason to limit Electron to mp4 and webm only? IIRC chromium is using ffmpeg. It seems like Electron could relatively easily enable all the ffmeg supported formats. In particular .flv, .avi, .mkv etc..

Would that be an acceptable pull request?

**Comment by zcbenz** [comment]
Adding support for more formats requires writing code to recognize them, Electron just inherits what Chrome has. Pull requests to add support for more formats will be appreciated.
