### ISSUE TITLE
Web Notification Support

### ISSUE THREAD

**Issue by ghost** [electron/electron#638]
I'm wondering if [Web Notifications](http://www.w3.org/TR/notifications/) are supported and the API is broken in `0.16.1` or the API is not supported.

```
Notification.requestPermission(function(val) { console.log(val); });
// --> nothing happens
console.log(Notification.permission);
// --> "granted"
new Notification("Hello Atom");
// --> nothing happens
```

This example works in Google Chrome. It asks the user for permission to post notifications, and then posts the notification. `"granted"` means, that the website is allowed to post notifications. However, the notification `"Hello Atom"` isn't displayed and no error is thrown.

Is there another possibility to post notifications (UserNotifications on OS X for example)?

**Comment by reggi** [comment]
Web notifications still don't work I'm getting:
```
App throwed an error when running [ReferenceError: Notification is not defined]
```

**Comment by reggi** [comment]
The alternative is https://www.npmjs.com/package/node-notifier?

**Comment by kevinSuttle** [comment]
Same error still. Maybe it's a doc issue.
http://electron.atom.io/docs/v0.36.8/tutorial/desktop-environment-integration/

`ReferenceError: Notification is not defined`
