### ISSUE TITLE
Remote requiring lodash breaks it

### ISSUE THREAD

**Issue by frontierpsycho** [electron/electron#6380]
* Electron version: 1.2.3 & 1.2.6 (tried with both)
* Operating system: Debian jessie

I'm writing an electron + angular2 app, and I'm trying to use lodash on the angular side. I've installed the latest lodash via npm, and so I thought I could do this:

`const _ = electron.remote.getGlobal("lodash");`

Then, I try to use `_.find`, a standard lodash function, and it doesn't work properly. Two examples of how it malfunctions:

- `_.find([1, 2, 3], function(item) { return item === 2; })` returns `undefined`.
- using `_.find` on a list containing objects created using my own prototypes, returns plain JS `Objects` with the same properties.

The exact same code, if I fetch the same version of lodash from a CDN, returns the expected values. 

In the developer console, if I print `_.find`, I get an electron function (I presume it's some kind of proxy that tries to call the actual function). 

I read the [documentation for remote](http://electron.atom.io/docs/api/remote/), but I couldn't figure out what's going on. I read the section about callbacks, but this doesn't seem to apply here, as the function I pass to `_.find` isn't a callback, and I presume is called synchronously by lodash. 

Am I doing something wrong? Is this a bug?

**Comment by MarshallOfSound** [comment]
@frontierpsycho Why can't you `require('lodash')` from the renderer process?

**Comment by zcbenz** [comment]
This is unfortunately an expected behavior due to the limitation of the `remote` module, you can read more of it at:
http://electron.atom.io/docs/api/remote/#passing-callbacks-to-the-main-process

**Comment by frontierpsycho** [comment]
Right, I hadn't read the callback section carefully enough. Thanks.

@MarshallOfSound I can, and I will, after all. It's just that it seemed convenient to simply require via electron.
