### ISSUE TITLE
auto-updater-win.js checks updateAvailable before restarting

### ISSUE THREAD

**Issue by sbuller** [electron/electron#6386]
* Electron version: 1.2.6
* Operating system: Windows

Once 'update-downloaded' has been emitted from an AutoUpdater, if checkForUpdates() is called before quitAndInstall(), updateAvailable is set back to false and the app throws an ugly error message instead of restarting.

**Comment by zcbenz** [comment]
`updateAvailable` would only be set to `false` when there is no update, can you provide a minimal app that can reproduce this problem?

**Comment by sbuller** [comment]
That's a bit more than I can undertake at the moment. Looking through the code, ultimately the behaviour ends up dependent on that of Update.exe. I would set up a test of its behaviour if I could, but I can't do even that at the moment since it only runs on Windows. For now I have to rely on my experience with my complete app.

What would happen is I would make an update to my app, and publish the RELEASES file and .nupkg files on my webserver. The app, running on the users' computers, would then present a notification of an update (once it had been discovered by autoUpdater.checkForUpdates()). Later when they would click the presented restart button, the app would throw an uncaught exception from autoUpdater.quitAndInstall(). Since there's only one way for this to happen, I have to assume that Update.exe --download only reports results that it has downloaded during its immediate execution, and not the sum total of elapsed updates since the currently running version. Which makes sense, since it's not being passed the version of the currently running program. Why would it report versions that are already installed?

**Comment by zcbenz** [comment]
@paulcbetts might have some ideas here.

**Comment by ahallicks** [comment]
I see this too in my app. It was fine (as far as I can tell) in 1.2.5. It also doesn't run `quitAndInstall()` at all. After manually quitting the app and opening again `checkForUpdates()` works as normal.

**Comment by zcbenz** [comment]
I'm merging this to #6647 since #6647 provides more details on this problem.
