### ISSUE TITLE
Possible typos in the remote.md

### ISSUE THREAD

**Issue by vsemozhetbyt** [electron/electron#6387]
* Electron version: 1.2.6
* Operating system: Windows 7 x 64

The code example [here](https://github.com/electron/electron/blob/master/docs/api/remote.md#passing-callbacks-to-the-main-process) seems to have two typos:

1. `return exports.mapNumbers(x => x + 1);` should be `return [1,2,3].map(x => x + 1);` (for now it just throws `...exports.mapNumbers is not a function...`)

2. `[true, true, true]` should be `[undefined, undefined, undefined]` according to the output I get with first typo fixed.

If I do get it right, I could make a PR for this fix.

**Comment by zcbenz** [comment]
I think you are right on this, a pull request will be appreciated. 👍
