### ISSUE TITLE
Session is lost between app restarts

### ISSUE THREAD

**Issue by bensie** [electron/electron#6388]
* Electron version: 1.2.6
* Operating system: macOS 10.11.5, Windows 10 (issue verified in both)

Up to and including v1.2.2, closing an Electron application and reopening it would restore the session/cookies as it was previously. 

As of v1.2.3 (and still verified as an issue in v1.2.6), this is no longer the case. In our case users login to our application and get a cookie that allows them to continue using the app for a few weeks.

This may be tangental, but it seems that if the session was created by v1.2.2 or older, upgrading to v1.2.3+ retains that session. But as soon as it is cleared by v1.2.3+ and you try to login again, closing the app and reopening will always present the login screen, tossing the session that was created by the previous app instance.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by jeroenseegers** [comment]
I think I'm encountering the same issue.

```javascript
const electron = require('electron');

const {app, session} = electron;

let currentSession = null;

app.on('ready', function() {
    'use strict';

    currentSession = session.fromPartition('persist:sessionName').cookies;

    currentSession.get({}, function(error, cookies) {
        console.dir(cookies);
        if (error) {
            console.dir(error);
        }
    });

    currentSession.set({
        name: 'someCookie',
        url: 'http://www.example.com',
        value: 'myValue',
        expirationDate: 1531036000
    }, function(error) {
        console.log('Cookie set');
        if (error) {
            console.dir(error);
        }
    });

    currentSession.get({}, function(error, cookies) {
        console.dir(cookies);
        if (error) {
            console.dir(error);
        }
    });
});
```

Will always return in the following output between restarts:

```javascript
[]
Cookie set
[ { name: 'someCookie',
    value: 'myValue',
    domain: 'www.example.com',
    hostOnly: true,
    path: '/',
    secure: false,
    httpOnly: false,
    session: false,
    expirationDate: 1531036000 } ]
null
```

**Comment by jeroenseegers** [comment]
Could this have anything to do with the changes made in #5904?

It seems to me that https://github.com/electron/electron/blob/master/lib/browser/api/session.js#L19 should read:

```javascript
if (partition === '') return Session.defaultSession
```

**Comment by bensie** [comment]
Thanks @zcbenz!

**Comment by jeroenseegers** [comment]
Thanks @zcbenz! Any idea when this will be released?

**Comment by stephane317** [comment]
Thanks @zcbenz !!! I'm waiting too for the released :)

**Comment by TimNZ** [comment]
I've spent all day playing with this in a webview as that is of interest to me, and was experiencing things I couldn't understand at first glance.

Tried on URLs:
* inbox.google.com
* go.xero.com

My findings with 1.3.1, OS X

* Session data IS retained, with and without partitions
* Chance of session data not being persisted if a webview is loaded and then the app is quickly closed e.g. a few seconds 
* Chrome can persist **session** cookies between browser sessions depending on browser settings.  Electron does not. This was tripping me as I kept on having to re-login on Xero when I expected the session to stay active after restart not realising the cookies were session (i.e. dropped on close)

Ideally a test framework can be created (or perhaps exists) to test session persistence, would be straight forward to make.

**Comment by blueoctopus** [comment]
I'm still having this problem when quitting the app after a few seconds a cookie is set (up to about 20 seconds in my tests). The cookie won't be saved when the app is reopened. It looks like this is the same behavior mentioned by @TimNZ above.

I'm able to see when the cookie data is actually saved to disk by inspecting the Cookies file:

`sqlite3 ~'/Library/Application Support/Electron/Cookies' 'select * from cookies'`

There is a delay between when the cookie is set and when it's written to disk. That means quitting the app is not writing the most recent state of the cookie DB into the Cookies file.

i.e. data is lost because it's not being written to disk on quit.

This issue was verified in v1.3.2 and v1.3.5.
v1.3.2 was tested on Windows 10, Ubuntu and OS X.
v1.3.5 was tested on OS X.
