### ISSUE TITLE
Some omissions in the docs/README.md

### ISSUE THREAD

**Issue by vsemozhetbyt** [electron/electron#6389]
* Electron version: 1.2.6

These four docs are omitted in the [docs/README.md](https://github.com/electron/electron/blob/master/docs/README.md) TOC:

[Accelerator](https://github.com/electron/electron/blob/master/docs/api/accelerator.md)
[DownloadItem](https://github.com/electron/electron/blob/master/docs/api/download-item.md)
[Frameless Window](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md)
[Possible Values of app.getLocale()](https://github.com/electron/electron/blob/master/docs/api/app-locales.md)

**Comment by zcbenz** [comment]
These pages are not public modules themselves, they are actually parts of other APIs, so users usually don't want to get knowledge of them unless they are using a specific API.

**Comment by vsemozhetbyt** [comment]
@zcbenz I see. Then maybe the electron.atom.io team should remove them from the site TOC too:

http://electron.atom.io/docs/
http://electron.atom.io/docs/api/
