### ISSUE TITLE
No feedback when NTLM login with wrong credentials is performed

### ISSUE THREAD

**Issue by fokusferit** [electron/electron#6394]
* Electron version: v.1.2.5
* Operating system: mac OS 10.11.3 (El Capitan ^^)

### Description 
I'm developing an intranet application for time tracking. For this purpose, I've developed a Electron / Polymerjs application. For time tracking, a user needs to login with his/her Win-Domain Account which is than authenticated via HTTP-NTLM.

This feature works just fine when users are entering correct credentials. Now, I want to show users some feedback if they enter wrong credentials but neither Electron nor Chromium are offering here any possibility to catch such error. It is not possible to catch 401 responses if the user enters wrong credentials. I've also looked into the default behaviour in Chrome browser which is also not showing such 401 HTTP errors instead it is just showing a Login window again and again (infinite loop). 

It would be good to have the possibility to react on login errors, e.g. with a second event ("error-login") or a second optional callback which is only fired when the login fails. 

Here is an example of the HTTP calls state before the user enters credentials:
![screen shot 2016-07-08 at 10 58 02](https://cloud.githubusercontent.com/assets/1215719/16682418/e335eb88-44fa-11e6-9e43-451b09d75c5f.png)

After the user enters some wrong credentials, the HTTP Calls are still pending:
![screen shot 2016-07-08 at 10 51 20](https://cloud.githubusercontent.com/assets/1215719/16682430/f68010d8-44fa-11e6-99e4-660f1f972e41.png)

It would be also possible to add some timeouts, but I don't want to trigger all the HTTP Calls again. I would prefer the current approach, where chrome is just waiting for the user credentials (which is working fine for proper credentials).

In the main process I've the login event handler which is receiving the user credentials from the renderer process via ipc messaging.

main.js:
```
app.on('login', (event, webContents, request, authInfo, callback) => {
  event.preventDefault();
  if(request.url.indexOf('timecontrol') !== -1 && request.method === 'GET') {
  /*
   * Add event listener for the login screen in the renderer Process
   * this asynchronous behaviour allows all "early" HTTP calls made from the app to wait for the credentials before authenticating
   */
  ipcMain.on('update-credentials', (event, arg) =>{
    username = arg.username;
    password = arg.password;
    callback(username, password);
  });
  }
});
```

I've tried to catch HTTP calls via the webContents Object but it looks like the only way to catch the HTTP calls fired from polymerjs components is to use the webContents.debugger API to access Chrome devTools via remote protocol.

Here is an example how it should/could look like (in Firefox), when a user enters wrong credentials:
<img width="1271" alt="screen shot 2016-07-08 at 11 00 54" src="https://cloud.githubusercontent.com/assets/1215719/16682528/52d82b0e-44fb-11e6-83d0-501298b93f36.png">

The server responds with 401 as long as the client sends proper credentials.

**Comment by zcbenz** [comment]
The login API of Electron has already exposed what we can get from Chromium, and unfortunately the login interface of Chromium does not allow us to provide an API for your case. I suggest reporting this to Chromium to ask for more correct behavior.
