### ISSUE TITLE
Taskbar icon looks pixelated in 125% scaling environment on Windows

### ISSUE THREAD

**Issue by yuya-oc** [electron/electron#6396]
* Electron version: 1.2.6
* Operating system: Windows 10 x64

When using 125% scaling, the taskbar icon looks pixelated. It looks fine in 100% and 150%.

I tried three apps, electron-prebuilt@1.2.6, electron-api-demos@1.1.0 and atom@1.8.0. I think that Atom should have same problem, but it looks fine in all environment. I'm not sure the reason why atom has no problem.

100%: ![100](https://cloud.githubusercontent.com/assets/1412057/16688067/1f7802a0-4557-11e6-852a-1fad65e0e186.png)
125%: ![125](https://cloud.githubusercontent.com/assets/1412057/16688069/20184b16-4557-11e6-8f5c-6df044e3357b.png)
150%: ![150](https://cloud.githubusercontent.com/assets/1412057/16688072/21c8e506-4557-11e6-8ebe-956be176c592.png)

Dialog for 125%:
![2016-07-08 21 38 36](https://cloud.githubusercontent.com/assets/1412057/16688111/58cf37a8-4557-11e6-8dd8-50cd157b77f2.png)

**Comment by zcbenz** [comment]
Can you try what will happen if you do not set `icon` property in `BrowserWindow`?

**Comment by yuya-oc** [comment]
At the first post, I just executed `./node_modules/.bin/electron` without any args.
Then, I have tried with [the quick start example in docs](https://github.com/electron/electron/blob/v1.2.6/docs/tutorial/quick-start.md#write-your-first-electron-app), but results are same.

**Comment by be5invis** [comment]
Maybe just missing a 30×30 icon

**Comment by zcbenz** [comment]
Electron sets the window icon with size of `SM_CXICON`, which should be 40 on 125% DPI, but somehow we are getting a value of 64.

**Comment by Pettor** [comment]
For my Electron app is finally made the tray icon look great in all resolutions and scaling by creating an icon (.ico) that contains sizes for 64x64 and 16x16 (do NOT include 32x32!!!). Windows will choose the 64x64 icon for >100% scaling and always look good for any scaling. For 100% scaling a regular 16x16 will look perfect but downscaling the 64x64 will make it look jagged.

**Comment by yuya-oc** [comment]
I tried removing 32x32 from my app, but it still pixelated. And explorer.exe also shows pixelated icon when using small rows.
The icon contains following sizes, 16, 32, 48, 64, 128, and 256.

**Comment by Pettor** [comment]
Test once more with the following (this is the exact that makes it work for me):
1. Download Junior Icon Editor (http://www.sibcode.com/junior-icon-editor/). This isn't a very advanced editor but works for this test purpose.
2. Create a 64x64 `.ico` of you image (for tray this size is enough). You can just drag n drop it in the editor and choose the size.
3. Create a 16x16 icon in the current project by right clicking in the work area to the right (the editor will automatically create the downsized icon for you).
4. Save as a new icon in `.ico` format.

One very important thing to remember is that if you switch from 100% scaling to 125% or vise versa you have to logout and login to get the actual result. The icon can look jagged until you have done this! My experience is that if you scale from 125% and above you don't have to do this.

**Comment by yuya-oc** [comment]
`GetSystemMetrics(SM_CXICON)` properly returns 40 in `Window::SetIcon()` on 125% DPI. So I checked the icon embedded into `electron.exe`, and it dones't contain 40x40 icon. As far as I read [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742485(v=vs.85).aspx), 40x40 and 48x48 icons should be included.


Then I tested `npm run pack-win` of `electon-api-demos` with the `.ico` which includes 16x16-64x64 icons.

![all_ico](https://cloud.githubusercontent.com/assets/1412057/17177534/ce8a23be-544c-11e6-9a06-eacf9d30a959.png)

I get a fine icon in the taskbar, but 40x40 is used at top left of the window. `BrowserWindow.setIcon()` correctly sets 20x20 icon here.

![taskbar_on_125](https://cloud.githubusercontent.com/assets/1412057/17177592/1ce70bd0-544d-11e6-95da-2a2969556b9a.png) ![small_icon_on_125](https://cloud.githubusercontent.com/assets/1412057/17177597/21ef6e4c-544d-11e6-8da2-87374b3a4d7c.png)

As the result, I think we have to write about that 40x40 and 48x48 icons should be included into the `.ico`.

**Comment by DeltaStudioApp** [comment]
I can reproduce this issue in windows with both .ICO and .PNG
They're both 256x256.
Can you please answer this clearly?

**Comment by DeltaStudioApp** [comment]
![imagen](https://user-images.githubusercontent.com/46191980/91242882-d1b23480-e748-11ea-88ae-b53e828c9f5b.png)

**Comment by imvenx** [comment]
fixed it by converting png to .ico here:

https://convertio.co/png-ico/

now download and rename the file to icon.ico and drag it into your project

idk how unoptimized this solution is but at least works
