### ISSUE TITLE
Allow fetching chrome://fileicon/<path> endpoint or expose it via API.

### ISSUE THREAD

**Issue by YurySolovyov** [electron/electron#6397]
- Electron version: 1.2.5
- Operating system: All

It would be useful for some types of applications to have the ability to get "resolved" icon for file or just file extension, meaning that you get icon of an app associated with this extension or mime type.

![image](https://cloud.githubusercontent.com/assets/2168518/16689837/7f745e9e-452d-11e6-9c50-75b9618d6112.png)

when I try to do this in Electron, I get:

```
GET chrome://fileicon/%2Fhome%2Fuser%2FDocuments%2FOTChET.docx?scale=1x net::ERR_INVALID_URL
```

**Comment by YurySolovyov** [comment]
I should add that using this type of URL outside of `chrome://downloads` in chrome gives
```
Not allowed to load local resource: chrome://fileicon/%2Fhome%2Fuser%2FDocuments%2FOTChET.docx?scale=1x
```

**Comment by YurySolovyov** [comment]
Same goes about `chrome://favicon/<url>`

**Comment by YurySolovyov** [comment]
I may be wrong, but it seems like implementation is [somewhere here](https://cs.chromium.org/codesearch/f/chromium/src/chrome/browser/ui/webui/fileicon_source.h?cl=0)

**Comment by simonhochrein** [comment]
+1

**Comment by YurySolovyov** [comment]
@zcbenz I'm trying to implement this here https://github.com/YurySolovyov/electron/tree/image-from-icon, but I have a lot of questions, it would be great to have some guidance via email or here.
Or I can submit a  WIP PR and discuss there.

**Comment by deepak1556** [comment]
>  can submit a WIP PR and discuss there.

:+1: .Just had a look at the branch, its good.

**Comment by YurySolovyov** [comment]
@deepak1556 thanks, but did you actually tried building it?
I have some linking issues there, that's why I didn't submitted it yet

**Comment by deepak1556** [comment]
Nope havn't , will try now.
