### ISSUE TITLE
Always on bottom functionality?

### ISSUE THREAD

**Issue by JimmyBoh** [electron/electron#6399]
I know that with `BrowserWindow` there is an `alwaysOnTop` option that forces the window to stay above all the rest. Is there an equivalent for `alwaysOnBottom`, to ensure that all windows open above this one?

Ideally implementing `type: desktop` on Windows would handle this case and complete the platform implementations.

Is this feasible? I'd be happy to take a whack at it, but wanted to see if a technical restriction was already found preventing it.

**Comment by zcbenz** [comment]
It is possible to make it work on Windows, but it can not work correctly, you can fine more at:
https://blogs.msdn.microsoft.com/oldnewthing/20040224-00/?p=40493

**Comment by rpodgorny** [comment]
the link is no longer valid. :-( ...any current known way to get the "always on bottom" functionality? thanks!

**Comment by jimbuck** [comment]
Here is the article: https://devblogs.microsoft.com/oldnewthing/20040224-00/?p=40493

But the comments are missing which might have had some additional useful info. Web Archive has the comments still: https://web.archive.org/web/20190216193947/https://blogs.msdn.microsoft.com/oldnewthing/20040224-00/?p=40493
