### ISSUE TITLE
Blank loadURL page after playing video

### ISSUE THREAD

**Issue by green7ea** [electron/electron#6400]
* Electron version: 1.2.6
* Operating system: Linux

When Electron loads a page that contains a <video> element, new pages that are loaded with the loadURL function aren't fully visible (only the background colour seems to show up). The bug may be present on platforms other than Linux but that was not tested.

I have created sample code to reproduce the bug:
https://github.com/green7ea/electron-bug

The sample code switches between google, bing and a page with video in a loop changing pages every 5 seconds. The initial page loads work fine but as soon as we have loaded the page with the video, further page loads are blank. Once we have made a complete loop and are back to the page with the video, we can hear sound which indicates that the page has loaded but is not being displayed. If we remove the page with the video we can see that page loads work as expected.

**Comment by zcbenz** [comment]
I'm not able to reproduce on Ubuntu 14.04, it is probably related to the machine or Linux distribution. Can you test whether the same problem occurs in Chrome browser?

**Comment by green7ea** [comment]
This problem doesn't occur in chromium. I tested it on different hardware configurations all running ArchLinux and up to date. The bug doesn't appear in systems with an nvidia proprietary driver and an intel driver. I would guess that this bug affects systems using the open source amdgpu driver.

**Comment by MarshallOfSound** [comment]
@green7ea @zcbenz This sounds suspiciously similar to #6139

**Comment by green7ea** [comment]
@MarshallOfSound It seems to be the same bug. I can reproduce the bug using his example as well but only on my amdgpu setup. I would guess the problem comes from a chromium compile flag and the amd linux drivers.

**Comment by MarshallOfSound** [comment]
Does the `--disable-gpu` workaround fix your issue?

**Comment by green7ea** [comment]
Sorry I forgot to mention it but yes it does.

**Comment by zcbenz** [comment]
I'm merging this to #6139 since they are essentially the same problem.
