### ISSUE TITLE
What does `autoCorrectWord` do? (as passed to `webFrame.setSpellCheckProvider`) (2/follow-up)

### ISSUE THREAD

**Issue by Aluxian** [electron/electron#6401]
* Electron version: Any
* Operating system: Any

Follow-up from https://github.com/electron/electron/issues/4371:

> The documentation for webFrame.setSpellCheckProvider does not say.
> 
> Looking at the code, it seems that it is meant to automatically correct swapped-letters misspellings like "wiht" (to "with"), except that in my testing it does not do that.

So it was supposed to do this:

```
    // Make decision: if only one swap produced a valid word, then we want to
    // return it. If we found two or more, we don't do autocorrection.
```

But the code that did that was removed in commit https://github.com/atom/electron/commit/5fae63a2f5d030ddb49d032bab7c50cc25d20d05.

So now `webFrame.setSpellCheckProvider` does nothing. What's up with that?

**Comment by paulcbetts** [comment]
If the actual parameter was removed, it would be a breaking change, but no-op'ing it lets existing code work correctly

**Comment by Aluxian** [comment]
I understand. Are there any plans to implement this feature or add back that code that was removed?

**Comment by zcbenz** [comment]
This feature had been removed from Chromium completely, so I think we will never add it back.

Refs https://bugs.chromium.org/p/chromium/issues/detail?id=519012.

**Comment by Aluxian** [comment]
I see, thanks!
