### ISSUE TITLE
System console access from a renderer

### ISSUE THREAD

**Issue by vsemozhetbyt** [electron/electron#6402]
* Electron version: 1.2.6
* Operating system: Windows 7 x64

Is there a way to get this access? If I add this to my renderer html:
```html
    <script>
      const NodeConsole = require('console').Console;
      const nodeConsole = new NodeConsole(process.stdout, process.stderr);
      nodeConsole.log('renderer: console.log');
      nodeConsole.error('renderer: console.error');

      process.stdout.write('renderer: process.stdout.write\n');
      process.stderr.write('renderer: process.stderr.write\n');
    </script>
```
and call `electron_path app_folder_path`, there are no messages in the system console, nor errors in the DevTools.

**Comment by kevinsawicki** [comment]
On Windows you need to set the `ELECTRON_ENABLE_LOGGING` env var to `true` to see renderer process logs in the console.

Also, you can just call `console.log` in the renderer process, you don't need to `require` console first.

http://electron.atom.io/docs/api/environment-variables/#electronenablelogging

**Comment by vsemozhetbyt** [comment]
Thank you. I've tested all the three ways with `ELECTRON_ENABLE_LOGGING` and there are some findings.

1. Only simple `console.log` works (not `process.stdout.write` or `require('console').Console` object).
2. The output is extra verbose.
3. An error from a C++ interface happens after the window with logging is closed.

```html
      const NodeConsole = require('console').Console;
      const nodeConsole = new NodeConsole(process.stdout, process.stderr);
      nodeConsole.log('renderer: nodeConsole.log');
      nodeConsole.error('renderer: nodeConsole.error');

      process.stdout.write('renderer: process.stdout.write\n');
      process.stderr.write('renderer: process.stderr.write\n');

      console.log('renderer: console.log');
      console.error('renderer: console.error');
    </script>
```

![1](https://cloud.githubusercontent.com/assets/10393198/16700925/6db41a54-4565-11e6-9ad6-d670c62f3c14.png)

After window closing:

![2](https://cloud.githubusercontent.com/assets/10393198/16700924/6db3e8d6-4565-11e6-8746-f65ac5083b18.png)
