### ISSUE TITLE
webFrame.setZoomLevelLimits doesn't prevent smart zoom on macOS

### ISSUE THREAD

**Issue by mnquintana** [electron/electron#6406]
* Electron version: 1.1.3
* Operating system: macOS 10.11.5

### Steps to reproduce

1. Put `webFrame.setZoomLevelLimits(1, 1)` as early as you can in your main renderer file
1. Try pinch-zooming – it shouldn't work
1. Try double-tapping anywhere in the window – it probably won't work
1. If you're using an external display, try changing it (ie. open your connected machine's screen)
1. Make sure Smart Zoom is enabled under System Preferences > Trackpad > Scroll & Zoom
1. Try pinch-zooming – it still shouldn't work
1. Try double-tapping anywhere in the window – it'll zoom

### Expected
`webFrame.setZoomLevelLimits(1, 1)` should prevent smart zooming (double-tapping to zoom)

**Comment by zcbenz** [comment]
I'm unable to reproduce on 1.2.6, can you try with the new version?

**Comment by kevinsawicki** [comment]
@mnquintana are you able to reproduce this on 1.3.2?

**Comment by mnquintana** [comment]
I can reproduce it on 1.2.7 – I'll try again on 1.3.2 and report back

**Comment by kevinsawicki** [comment]
I was unable to reproduce this today on 1.3.2 by adding `webFrame.setZoomLevelLimits(1,1)` to the first `<script>` tag in `default_app/index.html`.

Without the limits set it did double tap to zoom.

**Comment by mnquintana** [comment]
Seems to be fixed in 1.3.2! 🎉
