### ISSUE TITLE
Non-primitive objects do not maintain properties through IPC callback chain

### ISSUE THREAD

**Issue by vsemozhetbyt** [electron/electron#6407]
* Electron version: 1.2.6
* Operating system: Windows 7 x64

`webContents` doc [says nothing](http://electron.atom.io/docs/api/web-contents/#webcontentsexecutejavascriptcode-usergesture-callback) about `result` argument of `webContents.executeJavaScript` callback. If the evaluated script returns primitive values, there is no confusion. However, what about DOM objects? It seems they are returned as empty objects with all the properties stripped away.

```js
  mainWindow.webContents.once('did-finish-load', () => {
    mainWindow.webContents.executeJavaScript(
      `Object.keys(document.location)`,
      false, res => {
        console.log(res);
      }
    );
    mainWindow.webContents.executeJavaScript(
      `document.location`,
      false, res => {
        console.log(Object.keys(res));
      }
    );
  });
  mainWindow.loadURL(`about:blank`);
```
```
[ 'replace',
  'assign',
  'hash',
  'search',
  'pathname',
  'port',
  'hostname',
  'host',
  'protocol',
  'origin',
  'href',
  'ancestorOrigins',
  'reload' ]
[]
```

**Comment by MarshallOfSound** [comment]
In this particular case (`document.location`), after a bit of research I thought it was actually a bug so I went ahead and tackled it in #6758 

/cc @zcbenz @mnquintana @vsemozhetbyt

**Comment by vsemozhetbyt** [comment]
@MarshallOfSound Thank you. It is a very useful fix.

**Comment by MarshallOfSound** [comment]
As discussed in #6758 

> The current IPC implementation can send the `document.location` object correctly.

> ```js
require('electron').ipcRenderer.on('foo', console.info.bind(console));
require('electron').remote.getCurrentWebContents().send('foo', document.location)
```

> The issue appears to be that somewhere between 
https://github.com/electron/electron/blob/master/lib/browser/api/web-contents.js#L113
and
https://github.com/electron/electron/blob/master/lib/browser/rpc-server.js#L185  

> The object becomes empty.

**Comment by kevinsawicki** [comment]
> The current IPC implementation can send the document.location object correctly.

It looks like the properties on `document.location` are failing this check: https://github.com/electron/electron/blob/99ec841a8e4fe21182e2dfa7a1f085d70b80d6cf/atom/common/native_mate_converters/v8_value_converter.cc#L356-L357

Which is why they aren't getting serialized.

From the issue it does mention:

> It appears that the crash occurs when the V8ValueConverter is passed an object that has a named callback (v8::Object::HasRealNamedCallbackProperty()) that is an internal property (something that is not defined in JS, but intercepted by the c++ side).

> Something like a DOM input element is a good example of this.

So it looks like this might be expected given how the `Location` class is implemented.

**Comment by MarshallOfSound** [comment]
@kevinsawicki If `Object.assign` can fetch those properties and assign them to a new object though, why can't we fetch them during our serialization.

Also, they do get serialized in that example code (the object flows through to the main process then back to the renderer process and remains intact so I'm still not convinced that is what is going on.

**Comment by kevinsawicki** [comment]
> Also, they do get serialized in that example code (the object flows through to the main process then back to the renderer process and remains intact so I'm still not convinced that is what is going on.

I think your example isn't replicating the error exactly since you are using the `remote` module which serializes things a bit differently than raw IPC:

Try this:

```js
require('electron').ipcRenderer.send('foo', document.location)
```

Then in the main process:

```js
require('electron').ipcMain.on('foo', (event, location) => {
  console.log(location)
})
