### ISSUE TITLE
'did-fail-load' getting -138 error code

### ISSUE THREAD

**Issue by prnkmr** [electron/electron#6410]
* Electron version:1.2.5
* Operating system:Windows 8.1

The electron app is getting -138 error code when a remote url is loaded.
How to avoid the electron app from being blocked by firewall.

**Comment by zcbenz** [comment]
You have to configure your firewall to not block your app's connection, it is impossible for the app to turn off the firewall.

**Comment by prnkmr** [comment]
Is there any api available to request user to allow firewall for the particular electron application.

**Comment by MarshallOfSound** [comment]
You can spawn a process and run `advfirewall` commands to add a firewall rule.  It requires Admin permissions

https://technet.microsoft.com/en-us/library/dd734783(v=ws.10).aspx
