### ISSUE TITLE
Request:  Make the titleBarStyle changeable with an API on the BrowserWindow class

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#6413]
* Electron version: All
* Operating system: macOS

Just came across a use-case for the same window to need to switch between different `titleBarStyle`'s.  I'm looking into adding an API for this but raising this issue in case it's not possible before I start looking into it.

**Comment by zcbenz** [comment]
Changing between `hidden` and `hidden-inset` is very easy, but changing between normal window and frameless window, would be super hard to get right. So it is not impossible, but it really doesn't deserve efforts involved.
