### ISSUE TITLE
Upgrade to Node v6

### ISSUE THREAD

**Issue by steelbrain** [electron/electron#6414]
Just like the title says, opening an issue so people can subscribe. Close when it's done :)

**Comment by MarshallOfSound** [comment]
Ummm... Electron is up to node version 6.1

https://github.com/electron/electron/blob/master/.node-version

**Comment by steelbrain** [comment]
Oops, nevermind 😅 
I saw `v5.1.1` in Atom and forgot that Atom is not running the latest version of Electron
