### ISSUE TITLE
Allow input in the webview to remember last user input (username/passwd) 

### ISSUE THREAD

**Issue by wangxiexe** [electron/electron#6422]
* Electron version: 1.1.1
* Operating system: win 10

The same page ( use login ) can remember username/password in chrome , but when I use webview to embeded it in electron, it does not remember last time input any more.

**Comment by zcbenz** [comment]
You have to implement this feature yourself, you can reference how Brave browser implemented their autofill feature.

Electron doesn't ship the autofill feature of Chrome browser because only very few cases need it, and it takes lots of efforts to provide a programming interface. I'm closing this as won't fix.

**Comment by alexstrat** [comment]
For reference, that's how brave seems to have ported autofill APIs into muon (their fork of electron): https://github.com/brave/muon/pull/40.

**Comment by sentialx** [comment]
It would be great if Electron had this implemented

**Comment by alexstrat** [comment]
https://github.com/electron/electron/pull/9535 might provide a solution for several situations. For the others, it is a good base to start from to add a "global autofill" API to Electron.

**Comment by amn** [comment]
Electron is fat enough already. It needs to have fewer features, with features split into components one can explicitly deploy and enable. Any other progress is just the usual walking on the feature-creep road. It'd be nice to have this and that and wheels, a jet-engine, and propellers and everything. But I don't want to ship all that as part of my application, if not for size constraints, then for attack surface. Strip it down. You want autofill, write a module and link it to Electron, one way or another. My two cents.
