### ISSUE TITLE
Chrome Dev Tools/Inspector in Production Build

### ISSUE THREAD

**Issue by ArtisanCodesmith** [electron/electron#6424]
How do I go about enabling/toggling the Chrome Dev Tools/Inspector in the production build as I have a bug that only appears in the production build and not in the development one?

Thank you!! :)

**Comment by MarshallOfSound** [comment]
You could try `--auto-open-devtools-for-tabs` on the command line (not sure if that would work but it is a chromium flag.

If you aren't using an ASAR you could also just edit some of your JS and add `window.openDevTools()` somewhere in your main file.

**Comment by zcbenz** [comment]
You can use the `--remote-debugging-port` command line switch for this purpose, another common solution is to add an environment variable in your app that can open devtools.

**Comment by ArtisanCodesmith** [comment]
@MarshallOfSound @zcbenz Thank you both! :)

@MarshallOfSound Your ``window.openDevTools()`` solution worked beautifully for me! 👍

**Comment by pinalbhatt** [comment]
window.openDevTools() solution worked for me as well! 👍
