### ISSUE TITLE
Thumbnail Toolbars will NOT be displayed after exit fullscreen

### ISSUE THREAD

**Issue by codehz** [electron/electron#6425]
* Electron version: v0.37.8
* Operating system: Windows 10 x64

It seems that exiting from full-screen will recreate window...
Recall setThumbarButtons does not work too.

**Comment by MarshallOfSound** [comment]
Appears to extend #4514

@zcbenz Do we have any idea what's causing this?

**Comment by zcbenz** [comment]
I'm unable to reproduce on either Windows 10 or Windows 8.1, can you try with latest version?

**Comment by codehz** [comment]
[https://github.com/codehz/electron-test](Some Electron Test For Desktop Environment Integration)
@zcbenz
