### ISSUE TITLE
Add "painted" event in which can safely call capturePage

### ISSUE THREAD

**Issue by vsemozhetbyt** [electron/electron#6426]
- Electron version: 1.2.6
- Operating system: Windows 7 x64

I've made a simple app that gets a file with URL list, load every URL in the main window, make a full screenshot and save it in the `img` subdirectory as PNG. Here is all the test code:

`package.json`

``` json
{
  "name": "electron-screenshots",
  "main": "screenshots.win.js"
}
```

`screenshots.urls.txt`

```
http://json.org/json-de.html
http://json.org/json-en.html
http://json.org/json-fr.html
```

`screenshots.win.js`

``` js
/******************************************************************************/
'use strict';
/******************************************************************************/
const fs = require('fs');
const path = require('path');
const rl = require('readline');
const { app, BrowserWindow } = require('electron');
/******************************************************************************/
const imgPath = path.join(__dirname, 'img');
const urls = [];
const timeoutFromLoad = 100;
const timeoutFromResize = 100;

let   mainWindow;
let   i = 0;
/******************************************************************************/
app.disableHardwareAcceleration();
if (!fs.readdirSync(__dirname).includes('img')) fs.mkdirSync(imgPath);
app.once('ready', createWindow);
/******************************************************************************/
function createWindow() {
  mainWindow = new BrowserWindow({
    enableLargerThanScreen: true,
    webPreferences: {
      nodeIntegration: false,
    },
  });
  mainWindow.setMenu(null);
  mainWindow.webContents.on('did-finish-load', () => {
    setTimeout(saveDoc, timeoutFromLoad);
  });
  getURLs();
}
/******************************************************************************/
function getURLs() {
  rl.createInterface({
    input: fs.createReadStream(
      path.join(__dirname, 'screenshots.urls.txt'), { encoding: 'utf8' }
    ),
  }).on('line', line => {
    line = line.trim();
    if (line) urls.push(line);
  }).on('close', getDoc);
}
/******************************************************************************/
function getDoc() {
  if (urls.length) mainWindow.loadURL(urls.shift());
  else console.log('All done.');
}
/******************************************************************************/
function saveDoc() {
  mainWindow.webContents.executeJavaScript(
    `[document.documentElement.scrollWidth, document.documentElement.scrollHeight]`,
    false, result => {
      mainWindow.setContentSize(result[0], result[1]);
      setTimeout(() => {
        mainWindow.capturePage(img => {
          fs.writeFileSync(path.join(imgPath, `${++i}.png`), img.toPNG());
          console.log(`${mainWindow.webContents.getURL()} saved.`);
          getDoc();
        });
      }, timeoutFromResize);
    }
  );
}
/******************************************************************************/
```

This code works fine. Here are some found verifiable issues:
1. If I does not disable hardware acceleration, I get an empty window after resize and empty images after screenshots saving. To verify: comment out `app.disableHardwareAcceleration();`.
2. If I does not add timeout after `setContentSize`, I get the first image with distorted proportions (other images are OK because they do not need resize after the first resize). To verify: set `timeoutFromResize` to `0`.
3. If I does not add timeout after `did-finish-load` fired, I get images with lacunas (no page `img` elements, aborted text an so on). Sometimes I get PNG with 0 bytes. It seems that for `capturePage` to work properly, a user need an event like `document-painted` or `document-rendered`. To verify: set `timeoutFromLoad` to `0`, comment out `app.disableHardwareAcceleration();`, comment out or delete all the resize code, i.e. just make `saveDoc()` like this:
   
   ``` js
   function saveDoc() {
     mainWindow.capturePage(img => {
       fs.writeFileSync(path.join(imgPath, `${++i}.png`), img.toPNG());
       console.log(`${mainWindow.webContents.getURL()} saved.`);
       getDoc();
     });
   }
   ```

**Comment by zcbenz** [comment]
Closed with #6524.

**Comment by sffc** [comment]
+1

**Comment by goooseman** [comment]
The PR under the link was reverted 1 month after?

Swill isn't there any way to `captureImage` without relying on random timeouts?

**Comment by weilonge** [comment]
Hello, I have a similar issue about the painted timing before capturing a page. My solution is to listen `paint` event and call `webContents.invalidate()`. `webContents.invalidate()` is for triggering painting forcibly. Hence, this method can ensure that there should be a following `paint` event triggered.

```ts
    webContents.invalidate();
    await new Promise<void>(resolve => {
      webContents.once('paint', () => {
        resolve();
      });
    });
    webContents.capturePage(...);
```

Let me know if this solution makes sense before `view-painted` event implemented. Thanks.

**Comment by nornagon** [comment]
The `paint` event should be fine for this.
