### ISSUE TITLE
Using ready-to-show event,but the window is not show

### ISSUE THREAD

**Issue by AngrryRabbit** [electron/electron#6427]
* Electron version:1.2.0
* Operating system:windows 10

hello , this is my codes

`const electron = require('electron');`
`const { app } = electron;`
`const { BrowserWindow } = electron;`
`let win;`

`function createWindow() {`
 `   win = new BrowserWindow();`
  `  win.once('ready-to-show',function(){`
   `     win.show();`
    `});`

    `win.loadURL(`file://${__dirname}/views/login.html`);`
    `win.webContents.openDevTools();`

    `win.on('closed', function() {`
        win = null;`
    `});`
`}`

`app.on('ready', createWindow);`

`app.on('window-all-closed', function() {`

 `   if (process.platform !== 'darwin') {`
  `      app.quit();`
   ` }`
`});`
`app.on('activate', function() {`
 `   if (win === null) {`
  `      createWindow();`
   ` }`
`});`

**Comment by zcbenz** [comment]
This event was introduced from v1.2.3.
