### ISSUE TITLE
MongoDB connection error on linux

### ISSUE THREAD

**Issue by darrrk** [electron/electron#6439]
* Electron version: 1.2.6
* Operating system: Linux (Kubuntu 16.04)

Very often (not all times), when I connect to MongoDB via electron on linux (on OS X all fine), I get error like: `MongoError: failed to connect to server [localhost:27017] on first connect`.

Helps connection configuration: 

```javascript
"server": {
  "socketOptions": {
    "connectTimeoutMS": 1000
  }
}
```

But it dirty hack, need to detect, what wrong with electron on linux.

*P.S. Also, similar error I get, when try to ping Elasticsearch. Seems http/net connection wrong on linux.*

**Comment by zcbenz** [comment]
Did the connection fail because of timeout? And which mongoDB client library are you using?

**Comment by darrrk** [comment]
> Did the connection fail because of timeout?

Yes

> And which mongoDB client library are you using?

Any, I catch this on `1.x.x` and `2.x.x`. You can try latest (`2.2.1` at this moment)

**Comment by zcbenz** [comment]
I'm merging this to #1833 since they are essentially the same problem.
