### ISSUE TITLE
App.setAsDefaultProtocolClient for Linux

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron/electron#6440]
What is the reason `App.setAsDefaultProtocolClient()`is not available for Linux? I was under the impression this is possible, but requires different solutions for different distros.

**Comment by paulcbetts** [comment]
On Linux this is declared in your .desktop file, which is something you set up at install-time, not something you can toggle. I could be full of it on this though, there might be a way to register for this dynamically

**Comment by zcbenz** [comment]
It can be done with [xdg-settings](https://portland.freedesktop.org/doc/xdg-settings.html), and Chromium uses it in `shell_integration_linux.cc`:
https://cs.chromium.org/chromium/src/chrome/browser/shell_integration_linux.cc?sq=package:chromium

**Comment by atypicalprogrammer** [comment]
@paulcbetts For windows it should be done on install too.. But that doesn't mean this API call shouldn't be available. Right now we just do it on first run.

**Comment by paulcbetts** [comment]
@atypicalprogrammer I'm not saying what people _should_ do, I'm saying what I (incorrectly) believed was _possible_

**Comment by baconface** [comment]
@zcbenz  @atypicalprogrammer A possible solution might be checking for gnome-open, exo-open, xdg-open, gvfs-open, or kde-open and using which ever is available. You could never guarantee support for all Linux distros but you can hopefully target common desktop environments.

**Comment by bengotow** [comment]
Hust as a sidenote, we've been using `xdg-mime default` to make N1 the default mail client on Linux and it's been working fairly well for folks. Would definitely be nice to push it upstream. https://github.com/nylas/N1/commit/43e9b4cf49978506d7e2d5bc4dc080aa8337cec3

**Comment by baconface** [comment]
@bengotow Mime type handlers and protocol handlers are two different things.

**Comment by atypicalprogrammer** [comment]
Any updates on this by anyone?

**Comment by Eugeny** [comment]
This can also be done by editing the file directly: https://askubuntu.com/questions/514125/url-protocol-handlers-in-basic-ubuntu-desktop

**Comment by hron84** [comment]
@baconbrad  Not neccessarily. On Linux, proto handlers are also handled via - special - MIME types.

**Comment by codebytere** [comment]
This is now in master 🎉
