### ISSUE TITLE
js window.open 

### ISSUE THREAD

**Issue by pilosof** [electron/electron#645]
I use window.open in the loaded page, yet nothing happens... also how to capture target="_blank" events etc...

**Comment by xtyler** [comment]
The traditional browser API of window.open() provides a direct reference between new window and ownerWindow and their documents. This seems a valuable approach for communication and data sharing without needing an ipc client->browser->client loop. Please advise on why this is extremely unrecommended or what is wrong with my above assumptions. Thank you!

**Comment by lipis** [comment]
@xtyler I'm guessing we'll never find out.. :confused:

**Comment by nathansobo** [comment]
@zcbenz Even with your suggested arguments, no window actually displays.

**Comment by johnryan** [comment]
@nathansobo did you ever figure this out, still seeing the same behavior, no window shows.

**Comment by nathansobo** [comment]
I honestly don't remember what ended up happening. It's no longer an issue for me though. 😄

**Comment by jacwright** [comment]
I had this same problem and got it figured out finally. Leaving info here for posterity.

Calling `window.open()` will open a new BrowserWindow with the same configuration options as the window calling it. In my case, I had this code:
```
var mainWindow = new BrowserWindow({ show: false });
mainWindow.loadURL(`file://${__dirname}/files/index.html`);
mainWindow.once('ready-to-show', mainWindow.show);
```

Which has the window initially hidden. This means when calling `window.open` the new window is hidden initially, appearing to not work. Removing the `{ show: false }` fixes the issue. I'd still like to figure out how to keep that option but not have it apply to new windows.

**Comment by MarshallOfSound** [comment]
@jacwright See the docs on the `new-window` event

https://electron.atom.io/docs/api/web-contents/#event-new-window

This code sample appears to be exactly what you are looking for 👍 

```js
myBrowserWindow.webContents.on('new-window', (event, url) => {
  event.preventDefault()
  const win = new BrowserWindow({show: false})
  win.once('ready-to-show', () => win.show())
  win.loadURL(url)
  event.newGuest = win
})
```

**Comment by jacwright** [comment]
@MarshallOfSound you are most excellent! Thank you.

**Comment by felipemullen** [comment]
@MarshallOfSound 
What about when trying to send a POST request?

An example of this is when trying to create a form on the DOM and submit it via JS. The resulting window does not issue the POST since `loadURL` performs a GET load (as expected)
