### ISSUE TITLE
Online web page How to require local module

### ISSUE THREAD

**Issue by iptop** [electron/electron#6450]
* Electron version: 1.2.5
* Operating system:  windows 7

My page on the server,Through a url load,This page How to require local module

**Comment by MarshallOfSound** [comment]
Well IMO the first response here should be **you shouldn't**.  Allowing a remote page to require a local module is like giving a stranger the keys to your kingdom...  You probably shouldn't do it....

Warnings aside, you can request the URL on the server either inside a BrowserWindow or inside a WebView and have `nodeIntergration` enabled for the `require` method to be available globally.

**Comment by kevinsawicki** [comment]
@MarshallOfSound thanks for the answer, closing this out.

Also including a few doc links here that might be helpful:

- http://electron.atom.io/docs/tutorial/security/
- http://electron.atom.io/docs/api/synopsis/
- http://electron.atom.io/docs/tutorial/quick-start/
