### ISSUE TITLE
Is there a way to get the app Version from package.json?

### ISSUE THREAD

**Issue by Bratkartoffl** [electron/electron#6451]
Is there a simple way to get the application version of my app from package.json?
Just like this example with the electron version: https://github.com/electron/electron/issues/5127

```
 var electronVersion = process.versions.electron;
 var appVersion = ??
```

Thanks!

* Electron version: 1.2.3
* Operating system: OSX

**Comment by thomasjo** [comment]
Yes; [`app.getVersion()`](http://electron.atom.io/docs/api/app/#appgetversion).

**Comment by Bratkartoffl** [comment]
@thomasjo Thanks, calling it from my main.js shows me the version number in my terminal.
Now i want to write it into my localstorage, but this isn't working from my main.js. Any Idea?

**Comment by MarshallOfSound** [comment]
@Bratkartoffl `localStorage` is only available from the renderer process

**Comment by Bratkartoffl** [comment]
Solution in AngularJS Controller:

`  var appVersion = require('electron').remote.app.getVersion();
`

**Comment by 1-14x0r** [comment]
if your using react with a hot code development server you need to make sure to prepend 'window.' before require.. such as 

`const appVersion = window.require('electron').remote.app.getVersion()`

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (108/100 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:34203 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dx1Pq-0017T3-CN
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:45:37 -0500
Date: Tue, 26 Sep 2017 18:44:47 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1506476687;
	bh=qPQYucdqyH78JgpoHNMGlnY+eTgov00T8/F+njBRCpc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=WdVFubzixayD7rpG1GjRrVCjkbmfMpBgZw86KXs/AZqn3rvTwBpoNNNprMV6Xth/k
	 ZHlGAWQ7nO1ukfQ89u5ssjEADfqrb1nDLTulQW3tE9iPmlVVuO7OQvCb6V9KPxH/U2
	 /CacZ2x63wOqM2+DgO0mEtMYB2wAGHMo6UlAGByY=

**Comment by Codefans-fan** [comment]
export const environment = {
    production: true,
    version: require('../../../../package.json').version
};

**Comment by 3DAlgoLab** [comment]
> Yes; [`app.getVersion()`](http://electron.atom.io/docs/api/app/#appgetversion).
I found that the link is changed like this. Thanks.
https://www.electronjs.org/docs/latest/api/app#appgetversion
