### ISSUE TITLE
Add getFeedURL API to autoUpdater

### ISSUE THREAD

**Issue by mzmousa** [electron/electron#6454]
* Electron version: 1.2.6
* Operating system: osx yosemite

Do the autoUpdater objects on osx and windows have different properties? On windows, when i do ```console.log(JSON.stringify(autoUpdater));```
I see the properties `domain`, `_events`, `_eventsCount`, and `updateURL`. However, doing the same thing on osx only allows me to see the properties `_events` and `_eventsCount`. 

I want to access `updateURL` in my code but I'm wondering whether that property is accessible. Maybe I should submit a PR for a `getFeedURL` method?

**Comment by kevinsawicki** [comment]
> I want to access updateURL in my code but I'm wondering whether that property is accessible. 

It is not currently part of the API.

> Maybe I should submit a PR for a getFeedURL method?

That seems useful 👍

**Comment by mzmousa** [comment]
The windows version of `getFeedURL` is trivial. However, I just took a look at the files auto_updater_mac.mm and auto_updater.[cc|h], and it seems that adding a `getFeedURL` method for osx may be well beyond my ability 😆 

I will find a workaround for this in my app, but I'll keep watch here in case this ever gets implemented / once I brush up on my C++ :)

**Comment by mzmousa** [comment]
Wow, so quick. Thank you so much :heart:
