### ISSUE TITLE
Segmentation fault when creating NativeImage from broken/invalid path.

### ISSUE THREAD

**Issue by YurySolovyov** [electron/electron#6460]
* Electron version: 1.2.5
* Operating system: Windows 10

Happens when trying to create NativeImage in main process.

Looks something like this.
```js
nativeImage.createFromPath(path.join(icoPath, 'app.ico'));
```
where result of `path.join(icoPath, 'app.ico')` return broken or non-existing path.

It is perfectly ok to throw exception in this case, but segmentation fault just makes app die silently.

**Comment by kevinsawicki** [comment]
Have you tried this in `1.2.6`?

I think this may have been addressed by https://github.com/electron/electron/pull/6278

**Comment by YurySolovyov** [comment]
yes upgrading to 1.2.7 (and probably 1.2.6) helps.
