### ISSUE TITLE
process.config.target_defaults is undefined

### ISSUE THREAD

**Issue by davej** [electron/electron#6462]
* Electron version: 1.2.5
* Operating system: OS X 10.10.5

I'm a bit outside the normal use-cases for electron but I'm trying to install and build native modules from within Electron (instead of using the system node). I'm running into an issue because `process.config.target_defaults.default_configuration` is `undefined`. This may be intentional so feel free to close this if what I'm trying to do is out of scope.

```
➜  node -e 'console.log(process.config.target_defaults.default_configuration)'

Release

➜  export ELECTRON_RUN_AS_NODE=1

➜  ./Electron.app/Contents/MacOS/Electron -e 'console.log(process.config.target_defaults.default_configuration)'

[eval]:1
console.log(process.config.target_defaults.default_configuration)
                                          ^
TypeError: Cannot read property 'default_configuration' of undefined
```

**Comment by zcbenz** [comment]
The `process.config` is only generated when using the `configure` script to build Node, since Electron is using Node as a component, it is empty in Electron.

**Comment by davej** [comment]
@zcbenz Does it not make sense to polyfill it though? Some node scripts rely on it and it is available in every node version whether built manually or using a pre-built binary.

**Comment by xzyfer** [comment]
Fixed upstream in node-sass
