### ISSUE TITLE
Question: how setAsDefaultProtocolClient works?

### ISSUE THREAD

**Issue by gch1p** [electron/electron#6463]
* Electron version: 1.2.6
* Operating system: OS X

Hello. I don't understand, how to intercept my custom protocol calls when the app is already running. Documentation says that the uri will be passed as a command-line argument, but when the app is already running this is not the case, it just focuses app's window.

**Comment by zcbenz** [comment]
On OS X you need to use `open-url` event of `app` to get notified.

**Comment by nidhir-systango** [comment]
Hi,i have just added 
setAsDefaultProtocolClient('test') to main.js electron app, by hitting the browser with protocol it opens my app,
but always open an new instance of app,even if it is already running1
should i need to maintain session for this?

**Comment by MarshallOfSound** [comment]
@nidhir-systango Use `app.makeSingleInstance`

GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by nidhir-systango** [comment]
@MarshallOfSound :
very sorry for that and thank you very much for the help!
