### ISSUE TITLE
powerSaveBlocker export does not exist

### ISSUE THREAD

**Issue by amilajack** [electron/electron#6464]
* Electron version: 1.2.6
* Operating system: macOS El Capitan, Sierra

```js
console.log(require('electron').powerSaveBlocker); // undefined
```

It seems like `powerSaveBlocker` is not being exported from electron.

**Comment by MarshallOfSound** [comment]
Are you running this code from the main process or the renderer process?

If you are running it in the renderer process you need to use

```js
console.log(require('electron').remote.powerSaveBlocker);
```

**Comment by amilajack** [comment]
Works fine now. Thanks!

**Comment by Perchusha** [comment]
Faced the lack of this module.

electron: 17.0.0
node: 16.9.1

Calling powerSaver in worker main index file.

```
import { powerSaveBlocker } from 'electron';
import Logger from '../Logger';

class PowerSaver {
  init = async () => {
    this.id = powerSaveBlocker.start('prevent-display-sleep');
    Logger.log(`Enabled (id: ${this.id})`, 'powersaver');
  };
}

export default new PowerSaver();
```

Log from worker console. 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'powerSaveBlocker')
```
