### ISSUE TITLE
Bypassing CSP API does not support all CSP policy directives

### ISSUE THREAD

**Issue by asaschachar** [electron/electron#6465]
Currently, it seems you can only register certain schemes (i.e. https, file) as bypassing a <webview> page's CSP policy with `webFrame.registerURLSchemeAsBypassingCSP(scheme)`

Is there any plan to support finer control over bypassing a page's CSP policy with things like [CSP Source Lists](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#Source_lists). That way, a developer could bypass the pages CSP policy with a policy such as scripts coming from a url which matches `http://*.example.com` instead of opening up the CSP policy to any script with an `https` scheme.

Thanks!
- Electron version: 0.37.8
- Operating system: Mac OSX 10.11.3

http://electron.atom.io/docs/api/web-frame/#webframeregisterurlschemeasbypassingcspscheme

**Comment by zcbenz** [comment]
> Currently, it seems you can only register certain schemes (i.e. https, file) as bypassing a page's CSP policy with webFrame.registerURLSchemeAsBypassingCSP(scheme)

This API is supposed to work for all schemes, can you provide a minimal app that can reproduce this problem? And have you tried latest version?

> Is there any plan to support finer control over bypassing a page's CSP policy with things like CSP Source Lists.

The public interface of blink doesn't provide such ability, so we are unable to add it.

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by asaschachar** [comment]
Here is a minimal app that reproduces the problem that I'm describing: https://github.com/asaschachar/electron-csp-test

Hopefully that helps. Thanks!
