### ISSUE TITLE
Open file dialog hangs background functions

### ISSUE THREAD

**Issue by meron1122** [electron/electron#6468]
* Electron version: 1.2.6
* Operating system: Linux.

When I open dialog for save file, all background tasks, like setInterval just hangs up.
How to solve this?

**Comment by zcbenz** [comment]
You can pass a callback to the API to make it asynchronous.

**Comment by meron1122** [comment]
@zcbenz  Can you provide simple example?
I want download file from remote server, with save dialog, without handling application.
Currently i have a normal link to file in HTML, and save dialog open automatically.
