### ISSUE TITLE
multiSelections not working in open file dialog under Mac

### ISSUE THREAD

**Issue by yishn** [electron/electron#6472]
* Electron version: v1.2.6 and v1.2.7
* Operating system: Mac OS X El Capitan

When specifying `multiSelections` in the open dialog properties, it's not possible to select any files at all. All files are greyed out. I also tried specifying `filters` but that didn't work with `multiSelections` either.

```js
dialog.showOpenDialog(remote.getCurrentWindow(), {properties: ['multiSelections']});
```

**Comment by kevinsawicki** [comment]
> When specifying multiSelections in the open dialog properties, it's not possible to select any files at all. All files are greyed out. I also tried specifying filters but that didn't work with multiSelections either.

You need to include the `openFiles` option to open files an the `openDirectories` option to open directories.

There is a example of using them at the top of http://electron.atom.io/docs/api/dialog/#dialog
