### ISSUE TITLE
OS Notifications aren't removed on app Quit (is there a Clear All API?)

### ISSUE THREAD

**Issue by z-ax** [electron/electron#6475]
Hi. Is there any option to clear all OS notifications for the app (on quit)?
Just noticed, I have all of them from several recent launches available in Notification Centre.
On click it just opens default prebuilt Electron app.

Also, have bug report that it was reproduced during app uninstall (quit & remove all related files).
What happens on click not sure now, can check & update this info if required.

Thank you in advance for reply.

* Electron version: 1.2.6
* Operating system: OS X 10.11.5

**Comment by zcbenz** [comment]
Can you verify you are actually using the v1.2.6? I can not reproduce with following steps:

1. Open default app
2. Run `new Notification('test')`
3. Quit the default app

**Comment by z-ax** [comment]
Yes, v1.2.6. The code we use looks like this:

```jsx
    static addToOS(notification) {
        let model = Notify.getModelOS(notification),
            params = {
                body: model.message,
                requireInteraction: true,
                sticky: true,
                tag: model.uuid
            },
            osNotification;

        osNotification = new Notification(
            'The App Title',
            params
        );

        osNotification.addEventListener('click', () => {
            // ...
        });

        osNotification.addEventListener('close', (e) => {
            return false;
        });
        osNotification.addEventListener('error', () => {
            // ...
        });

        Notify.list[model.uuid] = osNotification;
    }
```

Ones received yesterday are still in the Notification Centre, and there's no Electron in Activity Monitor.

**Comment by MarshallOfSound** [comment]
Even using your params object.

```js
const params = {
  body: 'Fake Body',
  requireInteraction: true,
  sticky: true,
  tag: 'Fake UUID'
}

new Notification('test', params);
```

The notification immediately disappears from the Notification Centre when I close Electron (using 1.2.6).  Are you doing anything inside your app to affect the Notifications at all?  Possibly using native modules to integrate with the Notification Center?

**Comment by z-ax** [comment]
No, it's just like `Notification` HTML5 object usage.

Is there a nice way to clear all Notification from the Center (Mac/Win)?

**Comment by zcbenz** [comment]
The problem is very likely in other parts of your code, like crash on exit,  can you provide a minimal app that can reproduce this problem?

**Comment by z-ax** [comment]
Yes, can do that later (or will update this issue if will figure out).
Btw, also use Gulp task with `electron-connect` to launch the dev env and reload it when sources are updated (maybe, there's something better yet?).

@zcbenz: the main question is actually like I wrote: to be able to clear all Notifications from the Centers on Mac/Win via API. Is that even possible? Some time ago we researched the issue and didn't see the solution.

**Comment by zcbenz** [comment]
There is no API to manually clear the notifications, they are automatically cleared on exit.

**Comment by z-ax** [comment]
Looks like have 2 cases when OS notifications remain: after app force termination (during update launched), and when renderer window was destructed (seems only for OS X).

We have workarounds for that, will also try to find the time to make minimal app for you as well to get things done easier - at this point have release date soon, can't spend more time these days.

**Comment by z-ax** [comment]
Okay, so here it is. Steps: launch Electron app via, for example, `gulp-run-electron`, create Notification on OS X and terminate process (like ^C in Terminal or via Activity Monitor). Seems like it reproduces only on Mac.

Workaround looks like this for me.
Node.js part:
```js
        // Before the application starts closing its windows.
        app.on('before-quit', (event) => {
            if (mainWindow) {
                event.preventDefault();
                mainWindow.webContents.send('clear-os-notifications');
                mainWindow.destroy();
                mainWindow = null;
                app.quit();
            }
        });
```

Renderer: subscribe to IPC event `clear-os-notifications`, maintain list of Notifications and clear all of them on this event like this:
```js
    static removeByTagFromOS(tag) {
        if (!tag || !Notify.list.hasOwnProperty(tag)) {
            return false;
        }

        let osNotification = Notify.list[tag];
        if (typeof osNotification === 'object') {
            osNotification.close();
        }

        delete Notify.list[osNotification.tag];

        return true;
    }

    static clearAllFromOS() {
        for (let tag in Notify.list) {
            if (Notify.list.hasOwnProperty(tag)) {
                Notify.removeByTagFromOS(tag);
            }
        }
    }
```

If you have better idea how to work with this - please let me know.

**Comment by zcbenz** [comment]
When you force terminating the app, there is no chance for Electron to clear the notifications, because the process is killed and the code did not run.

On platforms other than macOS, the system clears the notifications automatically when the process exits. But this is a platform-dependent feature.

**Comment by z-ax** [comment]
In any case, this workaround cancels termination to clear OS Notifications through IPC.
But there might be no active window.
So, I'd prefer at least to have API to clear all of them.
Anyways, hope it helps someone.
