### ISSUE TITLE
Clarification on `path/to/electron.exe`

### ISSUE THREAD

**Issue by rohanpai** [electron/electron#6477]
Hi, quick question: what does `path/to/electron.exe` refer to on https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process.md#6-start-the-node-inspector-server-using-electron

I am on Mac OS X.

Does this mean my specific electron app or the installed electron framework node module?

Thanks

**Comment by paulcbetts** [comment]
In this case it's `./path/to/Electron.app/Contents/MacOS/Electron`

**Comment by rohanpai** [comment]
Thanks

**Comment by rohanpai** [comment]
@paulcbetts is there anyway to run the debugger without building the app first?

**Comment by paulcbetts** [comment]
`./node_modules/electron-prebuilt/dist/Electron.app/...`
