### ISSUE TITLE
Docs should state that .setThumbarButtons method becomes meaningful only after main window was shown

### ISSUE THREAD

**Issue by YurySolovyov** [electron/electron#6478]
* Electron version: 1.2.7
* Operating system: Windows 10

If title is correct, and this is intended then I'll do a PR.

**Comment by zcbenz** [comment]
We should make it work when it is called for hidden window. I'm merging this to #4514 since they are essentially the same problem: we need to make Electron remember the call of `setThumbarButtons` and reapply it when window adds an icon to taskbar.
