### ISSUE TITLE
Tray icons do not show up in elementary OS

### ISSUE THREAD

**Issue by GreyAsteroid** [electron/electron#6479]
* Electron version: 1.2.7
* Operating system: elementary OS 0.4 Loki Beta 1

To get tray icons working I have to set the environment to Gnome or Unity. Ideally electron should support Pantheon as an environment with working appindicator support.

**Comment by zcbenz** [comment]
Elementary OS stops supporting tray icons from 0.4:
http://blog.elementary.io/post/145881464631/loki-beta

**Comment by GreyAsteroid** [comment]
@zcbenz elementary OS 0.4 beta currently does not support indicators out of the box which is a decision currently being discussed internally https://plus.google.com/+DanielForé/posts/QN2vSoAEzPt

However, regardless of the decision, ayatana tray icons are still supported on elementary OS 0.4 with their ayatana Wingpanel plugin https://launchpad.net/wingpanel-indicator-ayatana

Also, the current stable release of elementary OS, 0.3 Freya, supports them out of the box.

**Comment by zcbenz** [comment]
We are not able to fix problems with all plugins, since the tray icons of Electron work fine in all Linux distributions except for the wingpanel-indicator-ayatana, I think the problem is on the plugin's side.

For the support on Elementary OS 0.3, I don't see much meaning supporting an old version when the new versions will drop the feature.

**Comment by GreyAsteroid** [comment]
@zcbenz Ayatana indicators work fine with elementary OS 0.3 and 0.4. 

The difference is that 0.4 might not include the capability by default and will require the installation of the wingpanel-indicator-ayatana package.

I'm using wingpanel-indicator-ayatana right now on 0.4 beta 1 and and indicators are working fine but require applications to be launched with the environment set to another desktop like Gnome or Unity.

**Comment by GreyAsteroid** [comment]
@zcbenz As of today, http://blog.elementary.io/post/147507276666/loki-beta-2-is-here
The newest version of elementary OS, currently in beta, now supports ayatana app indicators by default.

Please open this issue back up so that electron can display appindicators by default on the Pantheon desktop.

**Comment by zcbenz** [comment]
Thanks for the update, I'm reopening #5050.
