### ISSUE TITLE
Electron problems 

### ISSUE THREAD

**Issue by nilsgarland** [electron/electron#6481]
* Electron version: 1.2.7
* Operating system: mac osx

So I tried to run my simple electron file and it didn't work. It gave me the error **a JavaScript error occurred in the main process** And this is what I get.

Uncaught Exception:
/Users/myname/Desktop/desktop-app/main.js:5 let win = new BrowserWindow(width:800,height: 600);

Here is my JavaScript code:
`const electron = require('electron');
const {app, BrowserWindow} = electron;

app.on('ready', () => {
  let win = new BrowserWindow(width:800,height: 600);
  win.loadURL(`file://${__dirname}/index.html`);
})`

and here is my json code:
`{
  "name": "desktop-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
      "start": "electron main.js"
  },
  "author": "",
  "license": "ISC"
}`

Please help me! If this is very obvious then I understand since I'm just a html, css and JavaScript front end developer xD Thanks for all help I get!

**Comment by kevinsawicki** [comment]
> let win = new BrowserWindow(width:800,height: 600);

That line should be `let win = new BrowserWindow({width:800,height: 600});` instead.
