### ISSUE TITLE
Cannot read property 'object' of undefined (v1.2.4 and v1.2.6)

### ISSUE THREAD

**Issue by rchoudhary** [electron/electron#6483]
* Electron version: 1.2.4
* Operating system: Windows

I'm experiencing this issue inconsistently. Sometimes running the app goes well, other times I get:

```
C:\electron\resources\electron.asar\renderer\api\remote.js:178 Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (C:\electron\resources\electron.asar\browser\objects-registry.js:44:28)
    at EventEmitter.<anonymous> (C:\electron\resources\electron.asar\browser\rpc-server.js:324:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at EventEmitter.<anonymous> (C:\electron\resources\electron.asar\browser\api\web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```
When I remove the following code from my renderer process, I never see the issue again:

```
window.onload = function() {
   
    .
    .
    .

    // The code below is the source of the issue
	const {Menu, MenuItem} = remote
	const menu = new Menu()
	const clipboard = electron.clipboard
	menu.append(new MenuItem({
		label: 'Copy',
		click: function() { 
			clipboard.writeText(window.getSelection().toString())
		},
		accelerator: 'Ctrl+C'
	}));
	menu.append(new MenuItem({
		label: 'Select All',
		click: function() { 
			let range = document.createRange()
			range.selectNode(document.getElementById('content'))
			window.getSelection().addRange(range)
		}
	}));

	window.addEventListener('contextmenu', (e) => {
		e.preventDefault();
		menu.popup(remote.getCurrentWindow());
	}, false);

    .
    .
    .

}

```

Moving that chunk of code out of `window.onload` doesn't do anything either. I still get the errors, and I still get them inconsistently.

**Comment by zcbenz** [comment]
I'm unable to reproduce with your code, can you provide a minimal app that can reproduce this problem?

**Comment by rchoudhary** [comment]
@zcbenz I tried to make a minimal app, but now I can't reproduce the error. I guess somewhere in my code something _else_ is causing that segment above to throw an error. I'll try upgrading to the latest version of electron, maybe that will solve my problem.

**Comment by rchoudhary** [comment]
@zcbenz Ok so I ran 15 trials with v1.2.4, and 6 of them failed (40% error rate). I ran 30 trials with v1.2.6 and the first 12 went fine, however trial 13 failed. In the end 4 of the 30 trials gave the error above (13.3% error rate), but clearly the problem got better with v1.2.6.

**Comment by rchoudhary** [comment]
Another update: So I ran 30 trials again with v.1.2.6, but this time I didn't pass the `--debug` flag to my app, and all 30 times it started up successfully! There's a 98.6% chance that the `--debug` flag is causing this issue for me. Will run more tests and hone in on the cause.

**Comment by rchoudhary** [comment]
## Conclusion ##
(I'm gonna describe my problem in case anyone else in the future is also having this issue and stumbles upon this. Basically they shouldn't experience [this](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png))

So I had 2 windows, `splashScreen` and `contentWindow`. When a button in `splashScreen` was clicked, it would call `createContentWindow()` which would construct `contentWindow` with the `hide` property set to `true`, set the menu bar to `null`, and then, if the app was running in debug mode, open the dev tools.

The content window would perform it's `window.onload` work, then send a message back to main process saying it was done. Then the main process would show `contentWindow` and close `splashScreen`.

**The problem:** It seems that calling `contentWindow.openDevTools()` before `contentWindow.show()` was the issue. When I moved the offending line to the right place, I was able to successfully run my app 30 times in a row. Given my earlier data that 4 in 30 trials failed, there is a 98.6% chance that this is the reason I was having issues.

@zcbenz This issue has been resolved!
