### ISSUE TITLE
Restore support for <webview> without Node integration

### ISSUE THREAD

**Issue by poiru** [electron/electron#6484]
* Electron version: 1.2.7

After #5559, the following scenario is no longer possible:

* You have a `BrowserWindow` without `nodeIntegration` that loads potentially unsafe content from `https://foo.com`.
* `https://foo.com` uses `<webview>` to load other potentially unsafe content in a separate process.

The suggested workaround is to enable `nodeIntegration` and use a preload script to get rid of the unsafe globals. However, doing so will make the bypass in #5173 possible again.

How about reverting #5559 and introducing a`webviewPreload` option to `BrowserWindow.webPreferences`? If defined, all `webview`s under that `BrowserWindow` would unconditionally use the `BrowserWindow.webPreferences.webviewPreload` script instead of the `webview`'s own `preload` script.

See also [browserhtml#1179](https://github.com/browserhtml/browserhtml/issues/1179)

cc @zcbenz

**Comment by paulcbetts** [comment]
If the browser window already has nodeIntegration disabled, why would you want to double-frame it? You can just use an `iframe` for this

**Comment by poiru** [comment]
@paulcbetts Our use case effectively boilds down to:
* `BrowserWindow` contains a remote webapp with tabs
* The content of each tab is in a `webview`. The tab content may be expensive/slow to compute.

We have to use a `webview` to keep `BrowserWindow` responsive even during these slow computatations.

**Comment by paulcbetts** [comment]
@poiru Enable node integration in the outer BrowserWindow? If you're only loading trusted content there, it should be fine, no?

**Comment by zcbenz** [comment]
I don't know how browserhtml works, but if you don't trust the page to use node integration, you shouldn't trust it to use webview neither. Regardless whether we allow using `preload` attribute, merely having `<webview>` tag is going to cause security problems, it basically allows people to read everything on system.

**Comment by poiru** [comment]
>Enable node integration in the outer BrowserWindow? If you're only loading trusted content there, it should be fine, no?

@paulcbetts It is presumably trusted content, but it also contains remote user data so XSS is a concern.

>I don't know how browserhtml works, but if you don't trust the page to use node integration, you shouldn't trust it to use webview neither. Regardless whether we allow using preload attribute, merely having <webview> tag is going to cause security problems, it basically allows people to read everything on system.

@zcbenz Interesting, I wasn't aware of that. Could we devise a way to limit the `src` and `preload` of a `webview` to a safe subset based on some `BrowserWindow` option? E.g. a callback function checks whether or not the `webview` `preload`/`src` values should be allowed. I would be happy to do the implementation work.

**Comment by TimNZ** [comment]
@zcbenz If nodeintegration is not enabled on the browser window, and am using a preload script, what is the security issue? All I know the Chromium sandbox is disabled in Electron

**Comment by zcbenz** [comment]
> E.g. a callback function checks whether or not the webview preload/src values should be allowed. I would be happy to do the implementation work.

Sounds good to me, we can probably add 2 events to `WebContents`: `webview-created` and `will-create-webview`. The `will-create-webview` event can be used to strip out the `preload` option, and `webview-created` event can be used to add a listener to the `will-navigate` event of webview's WebContents to decide whether to navigate to a page.

I'm merging this to #2749.

> @zcbenz If nodeintegration is not enabled on the browser window, and am using a preload script, what is the security issue?

It should be as safe as running an un-sandboxed page in Chrome browser.

**Comment by TimNZ** [comment]
I just realised since you don't support nested <webview> (#1130) a lot of this discussion is not relevant for my scenario.  Only applies to BrowserWindow pointing directly to URL that you may not control content of.

Perhaps the webview/security doc pages could be updated to be clearer around the scenarios for webview?
