### ISSUE TITLE
Problems with building native modules due to not working dist-url

### ISSUE THREAD

**Issue by GreLI** [electron/electron#6485]
* Electron version: 1.2.7
* Operating system: Windows 8.1

[Using Native Node Modules](/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#using-native-node-modules) suggests using command like
```
HOME=~/.electron-gyp node-gyp rebuild --target=1.2.3 --arch=x64 --dist-url=https://atom.io/download/atom-shell
```
However, since yesterday https://atom.io has problems with HTTPS certificate which is issued only for Github domains, and, if turn off HSTS and accept the certificate, responds 404 on every url.

I guess that `--dist-url` should be changed to somenthing electronish. However, I haven't realize what url it should be.

`electron-rebuild` fails as described in electron/electron-rebuild#15.

**Comment by MarshallOfSound** [comment]
@GreLI Can you post the SSL issues you are having with `https://atom.io`.  I just checked locally and used a service to check for me and the cert appears to be 100% valid.

https://www.sslshopper.com/ssl-checker.html#hostname=https://atom.io

**Comment by GreLI** [comment]
Thanks for quick response! You're right, it seems that was incorrent DNS entry for atom.io. Works now after I've fixed that.
