### ISSUE TITLE
Add support for Windows 10 windows & title bar api

### ISSUE THREAD

**Issue by pavelzaruba** [electron/electron#6487]
I'd like to see API for colored title bar parts and extended view to title bar. Possibly new options in BrowserWindow.

See http://blog.thomasnigro.fr/2015/02/11/exploring-w10-apis-windows-and-titlebar/

* Electron version: 1.x
* Operating system: Windows 10

**Comment by MarshallOfSound** [comment]
@kevinsawicki These API's are UWP API's only, win32 applications can't integrate with them.

https://msdn.microsoft.com/library/windows/apps/windows.ui.viewmanagement.applicationview.titlebar.aspx?cs-save-lang=1&cs-lang=cpp#code-snippet-1

It's a similar issue to #6250

**Comment by zcbenz** [comment]
I'm closing this as won't fix since it is a limitation of Windows.
