### ISSUE TITLE
Let multiple applications share core files without installing multiple copies of Electron

### ISSUE THREAD

**Issue by joshas** [electron/electron#6488]
With electron getting more popular, there's an issue when user installs several apps using electron - each application will have same duplicate codebase, except actual app part.
I'd like to suggest to find a solution to this issue. E.g. provide electron core as separate library, so multiple apps could use it without eating a lot of disk space.

**Comment by enlight** [comment]
See existing issue #673

**Comment by kevinsawicki** [comment]
Closing as duplicate of #673 which is where the current discussion about this is happening.
