### ISSUE TITLE
Make the callback of session.clearStorageData optional

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#6491]
Docs:
https://github.com/electron/electron/blob/master/docs/api/session.md#sesclearstoragedataoptions-callback

I was running into a strange error when calling the `clearStorageData` method. It was saying it was unable to process the argument at index 1, which I was not passing. After some research I found that the callback is currently required, but in my case I did not care to provide one. To fix it, I supplied an empty function. Here is my code:

```
Electron.remote.getCurrentWebContents().session.clearStorageData(
	{
		storages: [
			'appcache',
			'cookies',
			'filesystem',
			'indexdb',
			'localstorage',
			'shadercache',
			'websql',
			'serviceworkers',
		],
		quotas: [
			'temporary',
			'persistent',
			'syncable',
		],
	},
	function() {} // <--- I shouldn't have to do this
);
```

* Electron version: 1.2.7
* Operating system: macOS

**Comment by zcbenz** [comment]
Closed with #6502.
