### ISSUE TITLE
Issues when redirecting from a custom (http) protocol

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#6492]
* Electron version: 1.2.7
* Operating system: OSX 10.11.4

I have a custom standard http protocol, `dat://`, which I want to have redirect to another custom standard http protocol, `view-dat://`. Here is the code I run:

```js
res.writeHead(302, 'Found', { 'Location': 'view-dat://'+archiveKey+urlp.path })
res.end()
```

This results in a crash. Crash report: https://gist.github.com/pfraze/6501e4eb46a5297415249d5daa257599

To learn more, I tried changing the redirect to a non-custom protocol:

```js
res.writeHead(302, 'Found', { 'Location': 'https://google.com' })
res.end()
```

This loaded google.com, but didn't update the webview's URL, causing the subrequests to fail:

![screen shot 2016-07-14 at 3 28 17 pm](https://cloud.githubusercontent.com/assets/1270099/16854676/a481fd50-49d7-11e6-8d47-638667d1edb9.png)

**Comment by pfraze** [comment]
I was able to solve this for myself by using `<meta http-equiv="refresh">` instead

**Comment by zcbenz** [comment]
I can't see what's going wrong from your description, a reproducible example will be helpful.

**Comment by pfrazee** [comment]
A reproducible example is on my todo list. Sorry for the delay.

**Comment by zcbenz** [comment]
Closing until more information is provided.
