### ISSUE TITLE
trigger crashReporter on uncaught Javascript exceptions

### ISSUE THREAD

**Issue by rohanpai** [electron/electron#6496]
I'm currently running:

```
const {crashReporter} = require('electron');
crashReporter.start({
  productName: 'YourName',
  companyName: 'YourCompany',
  submitURL: 'http://localhost:1127/post',
  autoSubmit: true
});
```
It seems that the crash reporter does not get triggered by uncaught Javascript exceptions. I looked through the API for the crashReporter but didn't see an obvious way to force a crashReport. To solve this, I wanted to force submit a crash report inside a ` process.on 'uncaughtException' ` or maybe a better solution is to post crash reports on uncaught exceptions in JS.

**Comment by MarshallOfSound** [comment]
By definition I don't feel an `uncaughtException` is a crash.  I get quite a few `uncaughtException` error reports on GitHub (I catch and ask the user to raise an issue) and they report the app runs perfectly fine ever after the `uncaughtException`.

You should be able to handle this yourself if you want the a report to end up in the same place with simple code like this.

```js
import electron, { app } from 'electron';
import request from 'request';

const packageJSON = require('./package.json');
const deps = packageJSON.dependencies;

process.on('uncaughtException', (err) => {
  request.post('http://localhost:1127/post', {
    form: {
      ver: deps['electron-prebuilt'],
      platform: process.platform,
      process_type: electron.remote ? 'renderer' : 'main',
      _version: packageJSON.version,
      _productName: packageJSON.productName,
      prod: 'Electron',
      _companyName: 'Your Company Name Here',
      upload_file_minidump: err.stack,
    }
  });
});
```

Just FYI that code is untested but it should do the job

**Comment by kevinsawicki** [comment]
Yup, @MarshallOfSound is right, the crash reporter API is for crashes, not uncaught exceptions.

You can use `process.on('uncaughtException', function () {})` or `window.onerror` to get uncaught JavaScript exceptions.

Closing this out.
