### ISSUE TITLE
Noticeable lag when clicking menu items in OSX

### ISSUE THREAD

**Issue by mikecao** [electron/electron#6498]
* Electron version: 1.2.7
* Operating system: OSX 10.11.5

When clicking a menu item in OSX, there is some lag (about half a second) before the click handler is executed. Even a simple console.log is delayed. I've tried using both the `buildFromTemplate` method and manually building menus. In Windows, the menu action is executed immediately.

**Comment by kevinsawicki** [comment]
Can you include some example code that shows the issue?

If you just run the default Electron app and click something like the Edit > Select All menu, does that feel slow?

Does it only happen in 1.2.7, or also earlier versions?

**Comment by mikecao** [comment]
So it seems that when you click on a menu item (in any OSX application), it plays a little flashing animation, the menu disappears, and then the action takes place (thus the delay). It's something I never really noticed before. If you run the accelerator via the keyboard then the action executes immediately because there is no animation to display. I guess it's just an OSX quirk.
