### ISSUE TITLE
decode DER encoded serial number

### ISSUE THREAD

**Issue by darkdh** [electron/electron#6500]
* Electron version: 1.2.7
* Operating system: OSX 10.11.5

I tried to decode the serial number from [`serial_number()`](https://cs.chromium.org/chromium/src/net/cert/x509_certificate.h?sq=package:chromium&rcl=1468495044&l=186) by [`ReadTag()`](https://cs.chromium.org/chromium/src/net/der/parser.h?dr=CSs&q=parser&sq=package:chromium&l=134) just like [`parsing_certificate.cc`](https://cs.chromium.org/chromium/src/net/cert/internal/parse_certificate.cc?sq=package:chromium&l=252) does. However, I always get false returned form `ReadTag()`. 

Is there any steps required that I missed? Thanks.

**Comment by deepak1556** [comment]
Should use methods from [parse_values.h](https://cs.chromium.org/chromium/src/net/der/parse_values.h?sq=package:chromium&l=44) to decode primitive values.

**Comment by darkdh** [comment]
Thanks @deepak1556 . It works now.
