### ISSUE TITLE
webview preload does not fire

### ISSUE THREAD

**Issue by caperavensoftware** [electron/electron#6503]
* Electron version: latest
* Operating system: OSX

We are using node 6.1.0, Chromium 51.0.2704.106, and Electron 1.2.7.

I put `console.log('testing tools loaded');` into a js file called test.js
using
`
<webview id="foo" src="https://www.github.com/" style="display:inline-flex; width:640px; height:480px" preload="./test.js"></webview>
`

it does nothing, and I am not sure how I can debug this script either.
one thing is fore sure, no console.log happens

**Comment by MarshallOfSound** [comment]
I just confirmed that `preload` scripts run on Electron 1.2.7

Where are you looking for the logs.  `console.log` appears in the chrome dev tools when you use it inside a preload script.   But it appears in the WebView's preload script.

Use

```js
document.querySelector('webview').openDevTools()
```

To open the webview DevTools

**Comment by christoth** [comment]
@caperavensoftware Are you listening to the webview 'console-message' event? Console logging in the webview will trigger that event and the you can see it in the console for the BrowserWindow (in DevTools).

Or just open DevTools for the webview as MarshallOfSound suggested.

**Comment by kevinsawicki** [comment]
Closing this out until more information is provided.
