### ISSUE TITLE
Renaming folder safe?

### ISSUE THREAD

**Issue by nilsgarland** [electron/electron#6505]
* Electron version: 1.2.7 
* Operating system: MAC osx

I know this isn't really an "issue" but is it okay to rename my electron project folder? It's currently called "desktop-app" and I wan't to change that. Will it screw everything up? Thanks.

**Comment by MarshallOfSound** [comment]
Assuming your project doesn't have a hard coded absolute path including `desktop-app` it shouldn't break anything.

Non-issues should be asked on https://discuss.atom.io/
