### ISSUE TITLE
Add API to set thumbnail image on Windows

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#6508]
Pull request #6497 added support for showing a specific region of the window as the thumbnail image in the taskbar.

Some applications may want to use a static image instead as the thumbnail so that case should also be supported.

https://msdn.microsoft.com/en-us/library/dd389410(v=vs.85).aspx

https://msdn.microsoft.com/en-us/library/windows/desktop/dd562320(v=vs.85).aspx

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
