### ISSUE TITLE
Window shadow, minWidth and minHeight not working in Linux

### ISSUE THREAD

**Issue by 0x00A** [electron/electron#6512]
* Electron version: 1.2.7
* Operating system: Linux Mint (#37-14.04.1-Ubuntu SMP x86_64)

![image](https://cloud.githubusercontent.com/assets/136109/16886660/92297922-4aa3-11e6-9638-a1bca50846ed.png)

These features work fine on macOS.

**Comment by MarshallOfSound** [comment]
@0x00A What window manager are you using?

**Comment by 0x00A** [comment]
I've tried with Cinnamon and with Unity (no tweaks), both don't seem to honor `minHeight` and `minWidth`, but I do see a shadow on the box running Unity. (these are both out-of-the-box, Mint 17.3 and Ubuntu 16.04).

**Comment by zcbenz** [comment]
On Linux the window shadow depends on the desktop environment you use, many window managers would ignore shadow when the window is frameless, and there doesn't seem to have hint to turn it off.

For the minWidth/minHeight issue, I can not reproduce, can you provide a minimal app that can reproduce this problem?

**Comment by 0x00A** [comment]
So, I found the cause of this issue. I was experimenting with improving the perceived performance of the load time by not immediately showing the window. When i removed this code, the resize rules worked. Here is the code...

```
mainWindow.loadURL('file://' + __dirname + '/static/index.html')
mainWindow.hide()

setTimeout(() => {
  mainWindow.show()
}, 350)
```
