### ISSUE TITLE
Electron packaging

### ISSUE THREAD

**Issue by nilsgarland** [electron/electron#6513]
* Electron version: 
* Operating system:

Hi, so I started finishing up the first version of my app, so when I try to npm run buil, it works. No issues there, but when I open the folder it is in I se the .app file and 2 txt files. And when I click to open the app it opens the program but not any windows. I also want to add that there are no other files in the folder. 

npm script:
"build": "electron-packager . MyApp --platform=darwin --arch=x64 --version=0.27.2"

**Comment by sbruchmann** [comment]
This is an issue regarding [electron-packager](https://github.com/electron-userland/electron-packager/), not electron itself.

**Comment by MarshallOfSound** [comment]
@nilsgarland This is a question / issue for the `electron-packager` repo.

Though FWIW that electron version looks scarily old (0.27.2). You should probably update as a LOT of issues have been fixed since then
