### ISSUE TITLE
shell.showItemInFolder has no effect on Windows 10

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#6514]
* Electron version: 1.2.5
* Operating system: Windows 10

On Windows 10, open a console and try:
```
shell = require('electron').shell;
shell.showItemInFolder(process.cwd());
shell.showItemInFolder('C:\\anything\\goes\\here.jpg');
```

Whether it's a folder or an item, the call fails silently.

**Comment by 0x00A** [comment]
The exact same issue on `Linux Mint/Ubuntu` with electron `1.2.7`.

**Comment by zeke** [comment]
I wasn't able to reproduce this on Windows 10 with electron-prebuilt 1.2.7 (or 1.2.5)

One thing I did notice is that if the given directory is already opened in the Windows Explorer, it "seems like" nothing happens.

![screen shot 2016-07-15 at 2 51 04 pm](https://cloud.githubusercontent.com/assets/2289/16889677/f41fe46a-4a9c-11e6-88f3-0c32b7ca5489.png)

**Comment by CharlieHess** [comment]
An interesting thing I found is that if I go through `remote`, everything works as expected:
```
remote = require('electron').remote;
remote.shell.showItemInFolder(process.cwd()); //works!
```
Doing some archaeology it looks like this may have happened before... 🔮 
See https://github.com/electron/electron/pull/3215.

**Comment by 0x00A** [comment]
fwiw, `shell. showItemInFolder(p)` works perfectly for me on osx.

**Comment by zeke** [comment]
> Electron version: 1.2.5

@CharlieHess are you able to try 1.2.7?

**Comment by zcbenz** [comment]
@CharlieHess Have you tried running the code in the console of default app?

**Comment by CharlieHess** [comment]
@zcbenz Hm, I'm not able to reproduce from the default app console. FWIW in our scenario, we are calling `shell` from the preload script of a `webview`, but it _also_ fails when required in the main renderer. I'll dig into what could be different.

**Comment by 0x00A** [comment]
@CharlieHess perhaps whatever your solution is, its the same for linux? do you mind posting your resolution?

**Comment by lixiaohulee** [comment]
@CharlieHess  did you resolve this problem
