### ISSUE TITLE
Widevine plugin detected only after referencing it in console

### ISSUE THREAD

**Issue by XanderEmu** [electron/electron#6516]
- Electron version: 1.2.7
- Operating system: Mac OSX El Capitan
- Widevine CDM version: 1.4.8.885

I'm trying to build an app which play widevine-encrypted video. My prototype works only if I type `navigator.plugins` in console or if I execute `console.log(navigator.plugins);` (with console open). Otherwise it won't work.

I tried it with shaka player demo page and with local dashjs-based player.

**Comment by XanderEmu** [comment]
I played around with it a bit more and I managed to make it work with following workaround:
`navigator.plugins.item();`

It works with dev tools closed.
Seems like I just have to do something with plugins object (touch it somehow) for it to become self-aware and work.

**Comment by zcbenz** [comment]
I'm unable to reproduce, I tried with `shaka-player-demo` and the video can load without extra steps. Can you provide a minimal app that can reproduce this problem?

**Comment by XanderEmu** [comment]
Sure:
https://github.com/XanderEmu/electron-dash-test

**Comment by zcbenz** [comment]
Not sure why but I always got "Uncaught (in promise) TypeError: Illegal invocation" error in your example. Can you try whether the same problem shows in Chrome browser?

**Comment by XanderEmu** [comment]
I get this error if I don't enable my workaround. It's an exception thrown by DASH player when it cannot get DRM system to work. I never saw it in Chrome.

**Comment by zcbenz** [comment]
Hmm I have no idea of this.

**Comment by NishimuraT** [comment]
I'm trying to play widevine-encrypted video using shaka player.

It worked in the follow step, but I do not know why to work with this.
・step1: include bitdash.min.js
・step2: include shaka player of uncompile mode.

https://github.com/NishimuraT/electron-widevine-test

**Comment by godlikemouse** [comment]
I'm also having the same problem.  I can see the Widevine plugin in the console, I've added console.info(navigator.plugins[0].name) and can it output the Widevine plugin name "Widevine Content Decryption Module" however, nothing works DRM wise.  Nothing will play from any of the test pages, etc.

**Comment by sanbornhnewyyz** [comment]
Came across this thread with the same issue. Calling `navigator.plugins.item();` does seem to solve the problem for me. 

Using: 
*Shaka v2.0.1
*Electron v1.4.8
*Widevine v1.4.8.903
*macOS 10.12

If I don't include `navigator.plugins.item();` I get `6002` from Shaka: "Unable to create the CDM for the key system com.widevine.alpha."

Works correctly if I include `navigator.plugins.item();`.

**Comment by godlikemouse** [comment]
Unfortunately for me, the above doesn't work.  I can see all the plugins I reference loaded in the navigator.plugins however, I can't actually play any widevine videoes.

**Comment by Zorig** [comment]
Is this issue solved by any chance? @godlikemouse, Because I am having same problem with:

- Shaka 2.02
- Electron 1.4.13
- Electron Packager 8.4.0
- Widevine v1.4.8.903

I included widevine like this
```
app.commandLine.appendSwitch('widevine-cdm-path', path.join(__dirname, `./widevine/1.4.8.903/_platform_specific/linux_x64/libwidevinecdmadapter.so`));
app.commandLine.appendSwitch('widevine-cdm-version', '1.4.8.903');

``` 
Also added `plugins: true`. When i load `mainWindow.loadURL('https://shaka-player-demo.appspot.com/');`  to play widevine content it's disabled. I have tried `navigator.plugins` still can not play widevine content

**Comment by godlikemouse** [comment]
Not that I'm aware of.  I'm still waiting for a fix as well.

**Comment by xyal** [comment]
same problem,  same code base works on mac
not work on linux or window 8.1

console.log (navigator.plugins) will solve the "create Media key issue", but  after license is sent to the play, player cannot decrypt the content, so player hangs there forever

**Comment by xyal** [comment]
Any body can help this  out?  Electron team is not responsive. At their website, only questions, no answer

**Comment by Zorig** [comment]
@zcbenz did you figured out this one yet?

**Comment by 1egoman** [comment]
I wrote a npm package that encapsulates the fix mentioned above (namely `navigator.plugins.items()`): https://www.npmjs.com/package/widevine-initializer

**Comment by matgott** [comment]
Hi, 5 years latter I have a similar issue.

I have my website that works perfectly with shaka-palyer but when I try to use it with electron I have this problem, but instead of code 6002 I received error code 6001.
