### ISSUE TITLE
Error dialog and other things leave imprint on window

### ISSUE THREAD

**Issue by rchoudhary** [electron/electron#6517]
* Electron version: 1.2.6
* Operating system: Windows 7

In the API demos, when moving around the error dialog, it leaves a trail. Curiously, the information dialog does not leave such a trail. Furthermore, you can see that the Start Menu also left an imprint on the left side of the window!

![capture](https://cloud.githubusercontent.com/assets/4595638/16896284/b123fba2-4b54-11e6-8091-2f2603a171f7.PNG)

**Comment by MarshallOfSound** [comment]
I've seen this before with tonnes of other applications.  I personally think it's a glitch at a Windows OS level but someone might be able to prove that wrong.

And the fact that the start menu did the same thing indicates this is not Electron's fault.

I tried this on a Windows 7 machine and couldn't reproduce at all.  Can you provide the steps you took in the demo app to make this happen.

**Comment by rchoudhary** [comment]
@MarshallOfSound all I did was open up the api demos app and click the button that launches a sample error dialog. This was on my work laptop with windows 7 enterprise, that might have something to do with it.

**Comment by zcbenz** [comment]
This is a duplicate of #1821.
