### ISSUE TITLE
Cursor: pointer not working on div with display: inline-box

### ISSUE THREAD

**Issue by theo0165** [electron/electron#6518]
* Electron version: 1.2.7
* Operating system: MacOSX 10.11.5

Code:
`.close{
  cursor: pointer !important
  display: inline-block
}` <== This is not working

`.close{
cursor: pointer !important
}` <== But this does!

What i'm trying to say is that the cursor doesn't change when i hover on the first exempel but it does when i hover on the second one!

**Comment by MarshallOfSound** [comment]
`.close{ cursor: pointer !important display: inline-block }`

Is invalid CSS.

You should be using 

`.close{ cursor: pointer !important; display: inline-block }`

Or even better
```css
.close{
  cursor: pointer !important;
  display: inline-block;
}
```
