### ISSUE TITLE
Allow the response for `sendSync` to be asynchronous.

### ISSUE THREAD

**Issue by tarruda** [electron/electron#6521]
I would like to use `sendSync` to make some computation in the main process and return the result, but this computation can only be done asynchronously in the main process(which is expected or there could be a deadlock).

The documentation example for `sendSync` shows something like this:

```js
// main process
ipcMain.on('synchronous-message', (event, arg) => {
  console.log(arg);  // prints "ping"
  event.returnValue = 'pong';
});

// renderer process
console.log(ipcRenderer.sendSync('synchronous-message', 'ping')); // prints "pong"
```

This snippet suggests that the handler for a synchronous message must return the result synchronously, but what I need is for the handler to be defined like this:

```js
ipcMain.on('synchronous-message', (event, arg) => {
  console.log(arg);  // prints "ping"
  setImmediate(() => {
    event.callback('pong');
  });
});
```

Can the API be changed to allow this use case?

**Comment by MarshallOfSound** [comment]
You should be able to do

```js
ipcMain.on('synchronous-message', (event, arg) => {
  console.log(arg);  // prints "ping"
  event.sender.send('pong');
});
```

Does this fit your use?

**Comment by tarruda** [comment]
> Does this fit your use?

Are you saying that `event.sender.send` can be used to send a response to a synchronous message? If so yes, but AFAIK `event.sender.send` simply sends a new message to the `ipcRenderer` module of the window.

**Comment by tarruda** [comment]
Actually, I just tested setting `event.returnValue` in the callback and it worked as it should(sending the response when the value is set).

My mistake assuming that `event.returnValue` was a normal property, sorry for the noise.
