### ISSUE TITLE
How to set the BrowserWindow style?

### ISSUE THREAD

**Issue by longboy** [electron/electron#6526]
![0202](https://cloud.githubusercontent.com/assets/6941888/16916957/1d22179c-4d32-11e6-951e-466aafc45f35.png)

**Comment by longboy** [comment]
I want to set white background.

**Comment by zcbenz** [comment]
You can only either use the native frame, or use a frameless window and draws the chrome with your own code. Windows doesn't provide a way to change the color of native frame.
