### ISSUE TITLE
Tray icon manual highlight on OSX

### ISSUE THREAD

**Issue by tex0l** [electron/electron#6528]
* Electron version: 1.2.7
* Operating system: OSX

Hi everyone,
I'm working on a project where I have a Tray icon, and a window pops out of it when clicked, and this window is hidden when the Tray is clicked again. 
The current behaviour of the Tray when clicked is to be highlighted while clicked, but I'd like to make it stay highlighted while my window is opened.

I haven't found a way to make it work with the latest (1.2.7) version of electron. What I'd suggest is to add a Tray method 'setHighlighted' which takes a boolean, along with 'getHighlighted' which returns a boolean. Is it feasible ?

**Comment by arantes555** [comment]
+1. Would be useful for my project too :)

**Comment by davej** [comment]
Cross-referencing: #1825 & https://github.com/maxogden/menubar/issues/103
