### ISSUE TITLE
Call shell.openExternal opens blank page in Chrome

### ISSUE THREAD

**Issue by joaomoreno** [electron/electron#6531]
_from Microsoft/vscode#9225, cc @openJT_

* Electron version: 1.2.6
* Operating system: Linux

User reports that in his Linux system, when setting Chrome as the default browser, `shell.openExternal('url')` opens a blank page in Chrome. Seems to work when Firefox is the default.

**Comment by zcbenz** [comment]
@openJT Does `xdg-open url` work on your machine?

**Comment by openJT** [comment]
@zcbenz It does not work!

**Comment by zcbenz** [comment]
Electron and most GUI programs use `xdg-open` to open URLs, since it doesn't work I suggest reporting this to your Linux distribution's bugs tracker instead.

I'm closing this since it is a bug of the Linux distribution.
