### ISSUE TITLE
Dialog file filters get confused between extensions like "a" and "b.a"

### ISSUE THREAD

**Issue by craxal** [electron/electron#6532]
* Electron version: 0.34.1
* Operating system: Windows

Say I create two filters for a Save File dialog:

    [
        { name: "File Type 1", extensions: ["b.a"] },
        { name: "File Type 2", extensions: ["a"] }
    ]

Now let's say I want to save a file named `myfile.b.a`, which is "File Type 1". If I switch the file type to "File Type 2", I would expect the file name to change to `myfile.a`, but instead it remains unchanged. Even worse, if I change it back to "File Type 1", the name is modified to `myfile.b.b.a`.

As a more real-world example, let's say I want to support saving CSV files. I also want to support saving a special kind of `.csv` for address, and I want the extension to be, say, `.addr.csv`. I don't want to create a new extension like `.addrcsv`, because these address-formatted files are still valid CSV files.

**Comment by zcbenz** [comment]
This is unfortunately a limitation of the native save dialog of Windows, the only workaround is to avoid using extensions like `.b.a` on Windows.

I'm closing this as won't fix since Windows doesn't provide a way for apps for this use case.
