### ISSUE TITLE
New app.setBadgeCount() API cannot set badge to 999+ / localized numbers

### ISSUE THREAD

**Issue by bengotow** [electron/electron#6533]
Hey! Happy to see that Electron has picked up Unity support for badge counts. Unfortunately, the new API on `app` doesn't quite meet our use cases in N1 because it only allows the value to be set to an integer. We're planning to use app.dock.setBadge and fall back to app.setBadgeCount if it's available, but it'd be great to see the following use cases supported by `setBadgeCount` if possible:
 
- Some applications set the badge count to "•" when you have an indeterminate number of unread items. (e.g. Slack)

- In N1, we cap the unread count at 999 and display "999+" instead of an enormous number. This is for consistency with other Mac apps.

- We could switch to displaying large numbers (eg 1240), but the API will not insert locale-specific formatting. In most Mac apps, the number would be rendered "1,240" on US systems.

Electron Version: 1.2.7
Platform: macOS

**Comment by zcbenz** [comment]
The `app.setBadgeCount` API is a subset of the badge API on macOS and Unity, and on Unity it is only possible to set an Integer number.

To set it to arbitrary text, you can use the mac one API `app.dock.setBadge`.

**Comment by akashnimare** [comment]
@bengotow Is there any way we can implement this on Windows (specially on 7) since desktop notifications don't work there?

**Comment by jayarjo** [comment]
@zcbenz what is Unity? For some reason I thought it is a so called Unity Launcher - basically a dock in Ubuntu? Am I wrong?

For me does nothing. No badge anywhere.
