### ISSUE TITLE
Crash on macOS when using Spectron

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#6534]
* Electron version: `1.2.7`
* Operating system: macOS

Crash Dump: https://gist.github.com/MarshallOfSound/0db62521dcc41a73768017607696fcc0

Seems to occur about 4 out of 5 attempts to run Spectron tests.  Everything works fine on the 5th attempt.

**Comment by MarshallOfSound** [comment]
As an updata to this issue the crash occurs on `Linux` as well, I'll test on `Windows` when I get the chance

**Comment by kevinsawicki** [comment]
@MarshallOfSound do you have the spectron snippet you were running when this happened?

**Comment by MarshallOfSound** [comment]
Not on me right now, I'll have to scroll back through git history and find the code that was causing the crash.  I'll get it up here tomorrow  👍

**Comment by MarshallOfSound** [comment]
I'm going to close this out as although the crash is reproducible on `1.2.7` I can't make it happen on `1.3.2`
