### ISSUE TITLE
URL Scheme open-url event?

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron/electron#6537]
I do this in my index.js; 

```
electron.remote.app.on("open-url", function(event, url) {
  console.log("Open URL: " + url);
});

```

This gets triggered in Mac OS, but not in Windows. Is there another event or a different way to do it in windows?

**Comment by MarshallOfSound** [comment]
Are you using https://github.com/electron/electron/blob/master/docs/api/app.md#appsetasdefaultprotocolclientprotocol-macos-windows

If so you should read this bit of the docs.

> Once registered, all links with your-protocol:// will be opened with the current executable. The whole link, including protocol, will be passed to your application as a parameter.

So on windows you would need to use the `singleInstance` API and listen for the `argv` of the newly spawned instance

**Comment by atypicalprogrammer** [comment]
@MarshallOfSound OK, but I can't send any events to my renderer process from here.. I suppose the renderer is still from the old process? I did some logging and renderer never gets the event that I send after determining if the app should quit (before quitting, of course).

**Comment by MarshallOfSound** [comment]
Read the docs for [`makeSingleInstance`](https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback) again.

The callback is executed on the first instance (the one that stays running).  You can inside that callback exame the `argv` parameter (It's passed in as the first parameter) and send the appropriate IPC messages to your renderer process there.

**Comment by atypicalprogrammer** [comment]
Yes, I just figured that out now, sorry :-)

**Comment by remicoges** [comment]
Right now, doc says 

> callback will be called with callback(argv, workingDirectory) when a second instance has been executed. argv is an Array of the second instance's command line arguments, and workingDirectory is its current working directory. Usually applications respond to this by making their primary window focused and non-minimized.

So I have to launch a first instance of the app, and then when I open a second instance I will be able to parse argv parameter ?

**Comment by oikonomopo** [comment]
Is there any working sample code?
