### ISSUE TITLE
Question: WebAssembly support?

### ISSUE THREAD

**Issue by amilajack** [electron/electron#6539]
Do the latest versions of electron support WebAssembly?

**Comment by sedwards2009** [comment]
no.

WebAssembly has to be developed in Chrome/Chromium first before it appears in Electron.  You can follow the progress here though: https://www.chromestatus.com/features#webassembly

**Comment by MarshallOfSound** [comment]
@sedwards2009 That isn't entirely correct.  You can enable WebAssembly with a chromium flag, but I can't figure out which chromium version first supports the flag `--enable-webassembly `

**Comment by amilajack** [comment]
@sedwards2009 @MarshallOfSound Thanks!

**Comment by pannous** [comment]
Using webassembly should somehow be possible by now, right?

**Comment by ttraenkler** [comment]
+1

**Comment by jacobq** [comment]
@pannous Not entirely sure, but it appears to be ['enabled by default'](https://www.chromestatus.com/features/5453022515691520) in Chrome 57 while Electron v1.6.2 (current at time of writing) uses Chromium 56, so I would think that if it isn't already working out of the box then you could enable it via flag as mentioned earlier.

**Comment by vossad01** [comment]
@jacobq The flag should exist in the chromium being used, but [it is not one of the flags supported by electron](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md).

I tried it by passing the switch anyway and the app ultimately failed indicating there was no native wasm support detected.

**Comment by jacobq** [comment]
@vossad01  Aw, bummer :( 
Maybe we just have to wait for a future version of electron then...

**Comment by brenca** [comment]
I've tried adding `app.commandLine.appendSwitch('enable-webassembly')` with a branch based on the latest master (v.1.6.7) and this [demo](http://webassembly.org/demo/Tanks/) seems to be working if I add the flag this way.

**Comment by vossad01** [comment]
@brenca I just tried that demo it with `master` (4a9383b50bc2f15f42c027d7369e4a8129820cf1), and had it fail.  [That demo has asm.js fallback](https://github.com/WebAssembly/website/issues/84), is there any chance you ended up utilizing that?

* [This is my attempt at the tank demo](https://github.com/vossad01/electron-webassembly-tank-demo) (it excludes the asmjs fallback files).
* [This is my original test](https://github.com/vossad01/electron-webassembly-hello) which derives from the [WebAssembly.org Developer's Guide](http://webassembly.org/getting-started/developers-guide/).

**Comment by vossad01** [comment]
I opened #9235 requesting WebAssembly support and outlining what I learned in my investigation of adding it to electron.

**Comment by brenca** [comment]
Yeah, I see the problem too with your original test.

**Comment by vossad01** [comment]
WebAssembly is available as of Electron 1.7.0

**Comment by asbjornu** [comment]
Is it possible for parts of Electron apps (such as Atom and Slack) themselves to be written in WebAssembly so a reduction in CPU and RAM consumption can be achieved? Can WebAssembly be utilised in other ways to reduce the CPU and RAM footprint of Electron apps?

**Comment by adamvoss** [comment]
> Is it possible for parts of Electron apps (such as Atom and Slack) themselves to be written in WebAssembly

Technically yes, though (barring a development I am unaware of) the interop between WASM and JavaScript (i.e. the electron apis) can be a bit tedious which may factor in to how you architect your components.

> so a reduction in CPU and RAM consumption can be achieved?

WebAssembly is not a magic solution.  It would be perfectly possible to write a less efficient implementation compile it to WebAssembly and be worse off.  However, the languages that currently support WebAssembly are lower-level languages the give you greater control over memory and execution characteristics, so _in theory_ you should be able to write more efficient implementations (as always, you will need to measure your specific use case).

> Can WebAssembly be utilised in other ways to reduce the CPU and RAM footprint of Electron apps?

You have already mentioned writing parts of applications in WebAssembly, so I am not sure what else there would be.  I suppose you could use a WebAssembly component to replace some part of Electron itself if you found something that you could optimize that way.

**Comment by raphael10-collab** [comment]
Does Electron 11 support WebAssembly?
