### ISSUE TITLE
atom shell custom dock icon?

### ISSUE THREAD

**Issue by thebyrd** [electron/electron#654]
I'm trying to figure out how to create a custom OS X dock icon. The icon attribute in the BrowserWindow constructor doesn't seem to do the trick:

```
var mainWindow = new BrowserWindow({
    title: 'Blah',
    frame: true,
    width: 400,
    height: 460,
    resizable: false,
    center: true,
    show: true,
    frame: false,
    icon: path.join(__dirname, 'icon.png')
  })
```

Is this supported?

**Comment by davidmarkclements** [comment]
if anyone's having problems getting the icon to display (despite clearing finder cache) I've found that calling `setProgressBar(-1)` on any window object forces an icon update (v0.34.1)

admittedly hacky but that's how we're doing it in Deck (https://github.com/nearform/deck-app/blob/master/lib/dock-control.js)

**Comment by Albin-CR** [comment]
How to change this from code?.
