### ISSUE TITLE
hasImageContents always true

### ISSUE THREAD

**Issue by kenan2002** [electron/electron#6541]
* Electron version: 1.2.7
* Operating system: Win10 64bit

browser process
```javascript
win.webContents.on('context-menu', (event, params) => {
  // It prints "hasImageContent: undefined" no matter where you right click on the page
  console.log(`hasImageContent: ${ params.hasImageContent }`);
});
```

index.html body
```html
  <body>
    <textarea name="name" rows="8" cols="40">
      Hello world.
      Second line.
    </textarea>
    <img src="https://bearychat.com/e655795080a2258b3bc7476cf6b519ab.png"/>
  </body>
```

**Comment by kenan2002** [comment]
I found the reason: hasImageContent in [doc](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-context-menu) is misspelled which is actually hasImageContent**s**.

**Comment by kenan2002** [comment]
There is still problem: hasImageContents is always true.

**Comment by deepak1556** [comment]
@kenan2002 `hasImageContents` should be used in the context of a image node to verify its contents which may be blocked by client or server failed to load. Will update the docs and return `false` when its not an image node context.
