### ISSUE TITLE
MenuItem enabled option not working when used with role

### ISSUE THREAD

**Issue by kenan2002** [electron/electron#6545]
* Electron version: 1.2.7
* Operating system: macOS 10.11.5

MenuItem ```enabled``` option doesn't work when ```role``` presents.

```javascript
Menu.buildFromTemplate([
  // this item is not disabled.
  {
    lable: 'Copy',
    role: 'copy',
    enabled: false
  },
  // this item is disabled.
  {
    lable: 'Copy',
    enabled: false
  }
]);
```

**Comment by zcbenz** [comment]
This is unfortunately a limitation of OS X, as explained in https://github.com/electron/electron/issues/5794#issuecomment-222687713.
