### ISSUE TITLE
webContents.on callback failed?

### ISSUE THREAD

**Issue by changkun** [electron/electron#6546]
* Electron version: v1.2.5
* Operating system: macOS 10.11.6

I'm trying to create a window to display a website, and I'd like to open the website link in external web  browser. Here is my code snippet:

```js
class WebWindow {
    constructor() {
        let windowConfig = {
            maximizable: false,
            resizable: true,
            frame: true,
        }
        this.documentWindow = new BrowserWindow(windowConfig);
        this.documentWindow.loadURL(`file://${__dirname}/windows/views/web.html`);
        console.log('create window');
        // TODO: Why this call back will not be called when I click a link? 
        //       Which means the link will be open inside this window, and the log '123' will not be print in terminal.
        this.documentWindow.webContents.on('new-window', (event, url) => {
            console.log('123')
            event.preventDefault();
            shell.openExternal(url);
        });
        ....
```

I'm so confused. How can I track this info? Any suggestions?

P.S. the WebWindow is not this only BrowserWindow in this app's lifecycle.

**Comment by changkun** [comment]
Well, I think I found the reason, if we created multiple windows, somehow the url will be open inside the window, and 'will-navigate' is much better than 'new-window' in this case.

**Comment by zcbenz** [comment]
The `new-window` event is only emitted when the page requests to open a new window, like calling `window.open`. Clicking a link does not always belong to this event.
