### ISSUE TITLE
webgl insight devtools-extension can not be used in electron

### ISSUE THREAD

**Issue by chensy123** [electron/electron#6548]
- Electron version:1.2.6
- Operating system:windows 8

webgl insight devtools-extension can be used in chrome which version is 51, but can't be used in electron. Open Developer Tool can find "WebGL Insight" tab page, the tab page show nothing and background color is black when click "WebGL Insight " tab;

I refer to "http://electron.atom.io/docs/tutorial/devtools-extension/" web page and add code 
`BrowserWindow.addDevToolsExtension(process.env.LOCALAPPDATA + "\\Google\\Chrome\\User Data\\Default\\Extensions\\djdcbmfacaaocoomokenoalbomllhnko\\1.0.2_0");` 
in main.js

**Comment by kevinsawicki** [comment]
@deepak1556 can this be closed now that #6720 was merged?

**Comment by deepak1556** [comment]
@kevinsawicki #6720 only fixed the render process crash noted here, though I verified extension loading successfully its features are not working as expected, so this is still a bug. I am not working on it at the moment, so anyone can feel free to pick this up.

**Comment by DeerMichel** [comment]
Closing this issue since there has not been any recent activity. Furthermore, we don't offer support for v1 anymore. If the problem persists under current versions and is still relevant, feel free to open a new issue.
