### ISSUE TITLE
Support --enable-features

### ISSUE THREAD

**Issue by djpereira** [electron/electron#6549]
Using the latest version of Electron 1.2.7, I am trying to enable the `#enable-webrtc-h264-with-openh264-ffmpeg` flag in chromium by doing:
```
const { app, ipcMain, BrowserWindow, Tray } = require('electron')
app.commandLine.appendSwitch('enable-webrtc-h264-with-openh264-ffmpeg');
```
However, when I try to establish a call using WebRTC, H.264 (ID 107) is not available.

If you try going to the link below, connecting, and then pressing “i”, you will see the protocol being used by chrome/chromium (Video RX/TX: VP8 or H.264).
https://apprtc.appspot.com/r/653398468486?vrc=H264&debug=loopback&vsc=H264

If you use Chromium 51 (or Chrome 51) by itself (outside of Electron), it works well once you flip the switch on the flag.

I prepared a quick sample of my code here:
https://github.com/djpereira/electron-quick-start/tree/webrtc-h264-flag-issue

Again if you download Chromium 51 (same as Electron) at https://github.com/henrypp/chromium/releases/download/v51.0.2704.106-r723-win64/chromium-sync.exe and call `chrome.exe --enable-webrtc-h264-with-openh264-ffmpeg`, the call goes through using H.264.

I am not sure if the Chromium build used in electron-prebuild is any different from the current stable version (it has the same version number) or if I’m missing something when I call app.commandLine.appendSwitch.

* Electron version: 1.2.7
* Operating system: Windows 10.

**Comment by zcbenz** [comment]
This command line switch is not implemented in Electron. We need a general way to enable features in `base::FeatureList`.

**Comment by liusy182** [comment]
I am not 100% certain but it looks like this is already supported by electron. I am able to run the sample code well on Mac OS X.

From chromium src, 1content_main_runner1 used by Electron also checks for features: 
https://cs.chromium.org/chromium/src/content/app/content_main_runner.cc?sq=package:chromium&dr=CSs&l=158

**Comment by zcbenz** [comment]
@liusy182 Yeah you are right, the code seems to have been enabled since Chrome 52 upgrade, thanks for noticing this.
