### ISSUE TITLE
DownloadItem.setSavePath overrides existing files

### ISSUE THREAD

**Issue by jwheare** [electron/electron#6551]
* Electron version: 1.2.7
* Operating system: macOS 10.11.5

This can result in potentially disastrous data loss.

It's probably worth adding a prefix if the file path already exists, like Chrome does, by incrementing a ` (1)` before the file extension.

(As reported here sindresorhus/electron-dl#3)

**Comment by zcbenz** [comment]
This behavior is expected from low-level API's side. For example someone writing a script to automatically download files would not expect the file to be saved other than the specified place. And for some kind of applications the developer may actually want to show a warning dialog, instead of changing the filename implicitly.

So if you want to have a different behavior, you should implement the logic in your own app.

**Comment by jwheare** [comment]
I'm not suggesting the existing behaviour should go away, but I think preventing data loss is a general enough concern that there should at least be an option built into electron that offers protection from it.

But I respect your decision, especially given the lack of a PR or existing module that implements this independently.

**Comment by sindresorhus** [comment]
@zcbenz Defaulting to the unexpected (data loss) is never a good thing... I think Electron should do the right thing by default and instead let the user set an option to overwrite if they know what they're doing. Even I didn't realize it didn't behave like Chrome and actually silently overwrite files.

**Comment by MarshallOfSound** [comment]
Just voicing the same opinion as @sindresorhus although this should be an option and preferably it should be disabled by default.  The `download-item` API should be modified to add a `getSavePath()` method and the `done` event should be modified to add a `path` parameter to the event object. 

Does that sounds like a fair enough change @zcbenz ?

**Comment by enlight** [comment]
I agree with @zcbenz on this one, Electron is a framework, not a browser, it should provide a minimal API to allow developers to implement the desired behavior in their apps. Bloating the core API with options that can be just as easily handled by a non-core module doesn't seem like a good idea to me. I'm all for improving the docs though.

**Comment by MarshallOfSound** [comment]
Ah, I think I misread the original question.  Calling `setPath` as an API I agree should just overwrite the file and the user should use `fs.exists` or similar to provide the user with warnings.

However I do think adding a `getPath()` method would assist with this.

**Comment by sindresorhus** [comment]
@enlight I would usually agree, but when it comes to potential data loss I tend to err on the side of helping devs do the right thing. I have a strong feeling, even with docs, devs will miss it and cause data loss for users of their apps...

But yeah, improved docs are better than nothing.

I fixed it in [`electron-dl`](https://github.com/sindresorhus/electron-dl) with the [`unused-filename`](https://github.com/sindresorhus/unused-filename) module. Maybe worth showing a quick example in the docs to make it easy for the user? Something like:

```js
const filepath = unusedFilename.sync(path.join(app.getPath('downloads'), item.getFilename()));
item.setSavePath(filepath);
```
