### ISSUE TITLE
Starting in fullscreen then minimizing results in white screen

### ISSUE THREAD

**Issue by etraub** [electron/electron#6552]
* Electron version: 1.2.7
* Operating system: Windows 10 Enterprise (Version 1511, OS BUILD 10586.420)

This may be related to issue [6036](https://github.com/electron/electron/issues/6036) but the symptoms are slightly different.  On Windows when a fullscreen windows is minimized then restored it frequently renders as a blank white screen.

You can replicate it with the electron-api-demos by setting fullscreen to true in main.js.
    var windowOptions = {
      width: 1080,
      minWidth: 680,
      height: 840,
      title: app.getName(),
      fullscreen: true
    }

Start the application and then minimize the window.  (Alt-space, n).   
Then restore the windows (alt-tab or click the icon in the task bar).
If the bug isn't triggered without closing the application minimize and restore the window again. 

On my app it white screens on the first pass 100% of the time but on the electron-api-demos it's always happens on the second pass.

Alt-tabbing to a different window and back again fixes the rendering problem.

Again this sounds very similar to  [6036](https://github.com/electron/electron/issues/6036) and I can post there if that is more appropriate.

**Comment by zcbenz** [comment]
This is essentially the same bug with #6036, so I'm merging this to #6036.
