### ISSUE TITLE
Allow access to base64 data URL of media from context-menu

### ISSUE THREAD

**Issue by jwheare** [electron/electron#6553]
* Electron version: 1.2.7
* Operating system: macOS 10.11.5

I'd like to add the option to copy an image directly from a context menu, but the only ways I can see to access the data are:

1) Redownload the image srcURL, resulting in an extra HTTP request and an undefined delay before the clipboard is updated
2) Use the DOM to add the image to a canvas element and pull the base64 out of that, which won't work for cross origin urls.

Could the image data be made available from the context menu, or else provide some other way to access it from an img tag in webcontents?

**Comment by zcbenz** [comment]
Adding the data URL of image to `context-menu` is not an option, it would add the overhead of encoding image and sending the image through IPC for every right click.

To implement a copy image menu, the simplest way is to add a `webContents.copyImageAt` API, which is the way used by Chromium.

Refs:
https://cs.chromium.org/chromium/src/content/public/browser/render_frame_host.h?sq=package:chromium&l=175
