### ISSUE TITLE
Electron or Atom?

### ISSUE THREAD

**Issue by TheAifam5** [electron/electron#6554]
Please refactor code to use one name, not two.

**Comment by baconface** [comment]
For some clarity this project wasn't always Electron. It used to be Atom-Shell and development of it surrounded Atom. A lot of the retention of Atom branded APIs is backwards compatibility when it was Atom-Shell. So you will find that not only is there a `process.versions['atom-shell']` but `process.versions['electron']` as well. Both doing the same thing. Removing one would break programs and keeping both hurts nothing. Anything outward facing has been rebranded from Atom and Atom-Shell to Electron.

Under the hood as far as folder/files/functions etc in the source is still Atom. The source only makes references to Electron as a project name or if it is something Electron developers would be using on their end. So the source isn't a mix and match of Electron and Atom and uses only one name (Atom). It is pretty easy to deal with if you need to ever work on the main source. I don't know exactly why a change to it wasn't made but expect it falls under, "If it isn't broken, don't fix it."

**Comment by zcbenz** [comment]
Thanks @baconface for the excellent explanation, I'm closing this issue now.
