### ISSUE TITLE
Missing fs.access patches for asar traversal

### ISSUE THREAD

**Issue by jwheare** [electron/electron#6555]
* Electron version: 1.2.7
* Operating system: macOS 10.11.5

As noted here: https://github.com/sindresorhus/electron-config/issues/1#issuecomment-234118084

[`fs.access`](https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback) and [`fs.accessSync`](https://nodejs.org/api/fs.html#fs_fs_accesssync_path_mode) aren't patched in [asar.js](https://github.com/electron/electron/blob/a0c5749ac1731afbbb7d042f1717597d6d68ea02/lib/common/asar.js), which breaks packages like [path-exists](https://github.com/sindresorhus/path-exists/) when traversing within an asar.

**Comment by neutrinog** [comment]
I see this was closed several years ago but it seems that `fs.access` does not work on directories in the asar. e.g. given a path `my.asar/dir/file.txt` if I check the existence of `my.asar/dir` the result is false instead of the expected true.
