### ISSUE TITLE
Prevent iframes from breaking out and redirecting the BrowserWindow hosting the iframe?

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#656]
For example, if you try to create an atom-shell app that has an iframe that references github.com, Github uses an iframe breaking technique to redirect the top window to the src of the iframe.

```
<iframe src="http://www.github.com/" name="disable-x-frame-options" sandbox="none"></iframe>
```

Is there anyway to trick the iframe to make it think it is the top window?

If not, what is the best way to manage a bunch of individual BrowserWindows inside of a main window?

**Comment by TosinAdekoya** [comment]
@huntaub Thanks man.

**Comment by mb21** [comment]
From MDN:

> When the embedded document has the same origin as the main page, it is **strongly discouraged to use both allow-scripts and allow-same-origin at the same time**, as that allows the embedded document to programmatically remove the sandbox attribute. Although it is accepted, this case is no more secure than not using the sandbox attribute.

**Comment by minecraftchest1** [comment]
I tried it and the page wouldn't work anymore.
