### ISSUE TITLE
session.fromPartition race

### ISSUE THREAD

**Issue by bontibon** [electron/electron#6560]
* Electron version: 1.2.8 (also tested in 1.2.7)
* Operating system: Windows 10

I am trying to attach a `will-download` event handler to a `<webview>` session. However, the listener doesn't always get attached. The flow of the application is as follows:

1. Main process starts
2. Main process creates a new Browser Window
3. Main process adds the event listener:

        electron.session.fromPartition('persist:mysession').on('will-download', handler);

4. Renderer process is loading a page that contains a `<webview>` whose session is `persist:mysession`.
5. After the `<webview>` is loaded, trying to download something does not always trigger the handler.

Adding a delay until the `<webview>` is loaded guarantees that the event handler is registered:

```
setTimeout(() => {
    electron.session.fromPartition('persist:mysession').on('will-download', handler);
}, 6000);
```

**Comment by zcbenz** [comment]
I'm unable to reproduce by following your steps, can you provide a minimal app that can reproduce this problem?
