### ISSUE TITLE
SVG to PNG Math

### ISSUE THREAD

**Issue by matikbird** [electron/electron#6564]
I'm using Electron and it's great so far.
I've included **MathJax** and also make a repo to help bind faster.

So, when they convert the expression into a _SVG_, it does in realtime.
Now, I tried every method avaible, even the **mathjax-node** way (which's not working in Electron), and something is wrong. **svg2png** seems incompatible, and all the ways I tried to convert a _SVG math expression to PNG_ **it fails**.
svg2png it's not compatible, and honestly tried all the other ones, this is what I get:

![screenshot_2016-07-21_16-15-31](https://cloud.githubusercontent.com/assets/12424545/17035558/5fecf71c-4f5e-11e6-8032-1d4e91e07580.png)

```
 var nodes = document.getElementsByClassName("MathJax_SVG");
          var svg = nodes[0].getElementsByTagName("svg")[0];
            var w = svg.getAttribute("width"), h = svg.getAttribute("height");
          var css = svg.style.cssText+" width:"+w+"; height:"+h;
                    svg.style.cssText = ""; // this will be handled by the <img> tag instead
                    svg.setAttribute("xmlns","http://www.w3.org/2000/svg");
                    svg = [
                      '<?xml version="1.0" standalone="no"?>',
                      '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">',
                      svg.outerHTML
                    ].join("\n"); 

              var canvas = document.createElement( "canvas" );
              var ctx = canvas.getContext( "2d" );
               
              var img = document.createElement( "img" );
              img.setAttribute( "src", "data:image/svg+xml;base64," + btoa(svg) );
               
              img.onload = function() {
                  ctx.drawImage( img, 0, 0 );
                  
                       var __id = $('#projectactual').html();
                       $("#"+__id).append(canvas.toDataURL( "image/png" ));
                                       $rootScope.$broadcast('appendmath', tab);
              };
```

That has to return me a PNG in base64 from the SVG, but the **img.onload** function seems to never fire.

**Comment by dpvc** [comment]
You haven't given your MathJax configuration, but I suspect that you have not turned off the font cache, so the SVG contains `<use>` tag that reference a global SVG element for the actual path data.  That will make the SVG no be self-contained, as needed for the `<img>` tag.

Try adding

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  SVG: {useFontCache: false}
});
</script>
```

to your page just *before* the script that loads `MathJax.js` itself.  That will make each SVG be self contained, with no `<use>` tags.

If that doesn't work, attach an `onerror` handler to your `img` and see if that gets called.  

Finally, you might want to attach the `onload` handler to the `img` *before* setting the `src` attribute, just in case there is a race condition.

**Comment by zcbenz** [comment]
Closing since the original question seems to have been resolved.
