### ISSUE TITLE
<webview> 'new-window' event.preventDefault() not working

### ISSUE THREAD

**Issue by kenan2002** [electron/electron#6568]
* Electron version: 1.2.7
* Operating system: win10 64bit

<webview> 'new-window' event.preventDefault() seems not working when ```allowpopups``` on.

**Comment by bontibon** [comment]
related #5217

**Comment by zcbenz** [comment]
I'm merging this to #1378 since they are essentially the same problem: it is currently not possible to prevent synchronous events in renderer process.

**Comment by lilong7676** [comment]
#27090  The solution to this problem is here
