### ISSUE TITLE
Cursor does not update without moving it

### ISSUE THREAD

**Issue by jf908** [electron/electron#6569]
- Electron version: 1.2.8
- Operating system: Windows 10 and OS X Yosemite

Example - Put this script at the end of electron-quick-start's index.html

``` html
<script>
    setInterval(function() {
        var h1 = document.querySelector('h1');
        if (h1.style.cursor == 'none') {
            h1.style.cursor = 'default';
        } else {
            h1.style.cursor = 'none';
        }
    }, 1000);
</script>
```

The intended effect is that when you hover over the Hello World! heading, the cursor swaps between being hidden and being shown each second. If you open index.html in Chrome you can see how it is supposed to work.

Many websites use this technique to hide the cursor on video playback but because of this bug the cursor will stay shown.

**Comment by zcbenz** [comment]
I can reproduce on Windows, but not on OS X 10.11.

**Comment by rsms** [comment]
I can reproduce on macOS 10.12.3, electron 1.6.2.

I modified the repro case to make it possible to simply paste it into the console of an existing view:

```js
document.body.innerHTML = '<h1>Put cursor over me</h1>'
setInterval(function() {
  var h1 = document.querySelector('h1');
  if (h1.style.cursor == 'wait') {
    h1.style.cursor = '';
  } else {
    h1.style.cursor = 'wait';
  }
}, 1000);
```

Pasting this into a HTML page running in Chrome 57 works as expected — every second the cursor switches between "wait" and default.

However, pasting this into a `<webview>` of the Figma electron app doesn't, unless I continuously move the mouse.

Would be really really great to fix this.

**Comment by codebytere** [comment]
Does this occur on `v3.0.0`?
