### ISSUE TITLE
Is it possible to trigger menu action automatically?

### ISSUE THREAD

**Issue by haifengkao** [electron/electron#6570]
I am trying to improve a GUI of neovim by Electron. The Electron's default menu roles `copy paste cut` are perfect for vim insert mode, but they are not suitable for visual  and normal mode.
I don't want to implement `copy paste cut` again for all OSs. 
Is it possible to add some custom codes before invoking the default roles?

**Comment by sindresorhus** [comment]
Those roles just trigger the equivalent methods on the `webContents`, so you could you could just execute them directly:

- copy => http://electron.atom.io/docs/api/web-contents/#contentscopy
- paste => http://electron.atom.io/docs/api/web-contents/#contentspaste
- cut => http://electron.atom.io/docs/api/web-contents/#contentscut

**Comment by zcbenz** [comment]
Thanks for answering the question, I'm closing this issue now.

**Comment by haifengkao** [comment]
Thanks guys
