### ISSUE TITLE
screen.scaleFactor always returns 1 for 125% DPI

### ISSUE THREAD

**Issue by Mossop** [electron/electron#6571]
- Electron version: 1.2.8
- Operating system: Windows

I have a hidpi screen on my laptop and a normal main monitor that has some scaling applied through windows' display properties. In both cases the following code returns 1 even though I would expect something larger:

```
require('electron').screen.getPrimaryDisplay().scaleFactor
```

**Comment by zcbenz** [comment]
`getPrimaryDisplay()` probably didn't return the display you expected, it returns the display that the system considers primary, which may not be your laptop's screen. You should use APIs like `getDisplayNearestPoint()` to get the scale factor for current display.

**Comment by Mossop** [comment]
I've tried to use the APIs to find the current screen and it still returns a scaleFactor of 1 despite windows being set to scale to 125%. Also `screen.getAllDisplays()` returns just a single display regardless of whether I'm using my laptop screen or my external monitor (my laptop screen is disabled in that case so that is to be expected).

Is it possible that scaleFactor only supports integer values?

**Comment by zcbenz** [comment]
Thanks for the information, after testing I found that `screen.scaleFactor` returns 1 when DPI is 125%, however DPI 150% can work.

**Comment by virifi** [comment]
Chromium has this issue from two years ago, but it has been fixed a few days ago.
See [https://bugs.chromium.org/p/chromium/issues/detail?id=410696](https://bugs.chromium.org/p/chromium/issues/detail?id=410696)

**Comment by bsclifton** [comment]
Just a heads up that this is going to have a large impact

Because folks at 125% will get properly scaled content, everything will appear to be much larger for them.  If those people are upset and don't like this, it can be worked around by passing two additional flags to the base::CommandLine class (you should be able to append via the command line):
`--high-dpi-support=1 --force-device-scale-factor=1`

**Comment by zxc23** [comment]
@bsclifton I've been looking everywhere for this information, and I finally found it here. Thank you very much for that.

I got my electron app to ignore the desktop display scaling with this in the main process:

```
app.commandLine.appendSwitch('high-dpi-support', 1)
app.commandLine.appendSwitch('force-device-scale-factor', 1)
```

**Comment by sirgru** [comment]
Thanks @zxc23 for posting that solution. My application started scaling after I've npm installed electron (with global install there was no scaling). After adding those lines, the body of the application looks correct, but the top menu bar (on Windows) is scaled down. Any solution for this?

**Comment by HaulinOats** [comment]
Should these flags be added to the official documentation, since they work?

**Comment by MarshallOfSound** [comment]
@HaulinOats There are hundreds of potential chromium CLI switches.  We can't (and won't) document all of them especially as we can't guarantee there continued existence

**Comment by HaulinOats** [comment]
Ah, I follow. Wasn't aware it was that complicated. I'm still learning. Appreciate the response.

**Comment by gsbnlda** [comment]
> @bsclifton I've been looking everywhere for this information, and I finally found it here. Thank you very much for that.
> 
> I got my electron app to ignore the desktop display scaling with this in the main process:
> 
> ```
> app.commandLine.appendSwitch('high-dpi-support', 1)
> app.commandLine.appendSwitch('force-device-scale-factor', 1)
> ```

How it will work for Microsoft edge browser? edge menu tab font seems very small.

**Comment by gsbnlda** [comment]
> Just a heads up that I believe this is going to have a large impact
> 
> Because folks at 125% will finally get properly scaled content, everything will appear to be much larger for them. If those people are upset and don't like this, it can be worked around by passing two additional flags to the base::CommandLine class (you should be able to append via the command line): `--high-dpi-support=1 --force-device-scale-factor=1`

Microsoft edge browser menu tab font seems very small . How it works for ?
