### ISSUE TITLE
Mouse cursor disappears when focusing a second window

### ISSUE THREAD

**Issue by brandoncc** [electron/electron#6577]
* Electron version:
1.2.7

* Operating system: 
OSX 10.11.5

I am using Mousetrap to manage key bindings (I don't think that could have anything to do with the issue though). When I press a specific keybinding, I execute `createProfitsWindow`, which is here:

```js
function createProfitsWindow() {
  if (profitsWindow) {
    profitsWindow.restore();
    return;
  }

  profitsWindow = new BrowserWindow({
    width: 750,
    height: 434,
    center: true,
    acceptFirstMouse: true,
    resizable: false,
    show: false
  });

  profitsWindow.loadURL(`file://${__dirname}/app/profits.html`);

  profitsWindow.on('closed', () => {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multiple windows, this is the time
    // when you should delete the corresponding element.
    profitsWindow = null;
  });

  profitsWindow.once('ready-to-show', () => {
    profitsWindow.show();
  });
}
```

The first time the window is created, everything is fine. If I click back on my main window though, and hit the bound keys again, the window is focused as intended, but the mouse cursor disappears. The only way to see it is to move it around, and it will pulse very fast while moving it. If I click on the main window, then back on the second window, the problem is gone. It only occurs when electron is handling focusing the second window.

This problem was occurring on the initial window creation as well, but I managed to fix it by adding `show: false` and the `ready-to-show` handler. The only ways I have figured out to fix this is:

1. Execute `mainWindow.minimize` before `profitsWindow.restore`.
2. Execute `profitsWindow.close`, then `createProfitsWindow` again.

Either of those fix the mouse problem, but both are horrible solutions.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem? I tried to reproduce by following your steps but did not succeed.

**Comment by zcbenz** [comment]
Closing until more information is provided.
