### ISSUE TITLE
[NSCursor currentSystemCursor] returns nil when executed in renderer process

### ISSUE THREAD

**Issue by miniak** [electron/electron#6578]
* Electron version: 1.2.7
* Operating system: OS X 10.9.5

I have a node module, which calls `[NSCursor currentSystemCursor]`. When loaded into the main process, it works fine. However when loaded into the renderer process, it always returns nil, as the Cocoa environment is not initialized. Calling `[NSApplication sharedApplication]` in the module init function does the trick. However:
- sometimes the Electron Helper process appears as not responding in the Activity Monitor (no wonder, as the renderer process does not have a proper Cocoa message loop). Looks like it was only happening when I called `[NSApplication sharedApplication]` in response to a user action (button click -> call into native code).
- I am concerned about any other side-effects of doing that.

Use case: The native module is taking a screenshot (`CGDisplayCreateImage` for example works fine) and tries to paint the cursor image (getting the position via `[NSEvent mouseLocation]` works too) on top of that.

**Comment by zcbenz** [comment]
Using `[NSCursor currentSystemCursor]` has to initialize `NSApplication` because it needs to access system theme settings, it should be totally fine to call `sharedApplication` if you don't mind the small cost of calling.

The renderer process appears not responding because the message loop doesn't pump NSRunLoop.

Initializing the whole UI stuff in renderer process is bad for performance, so we will not do it.

**Comment by miniak** [comment]
The documentation `for [NSApplication sharedApplication]` says: "This method also makes a connection to the window server and completes other initialization.", which makes sense. `[NSCursor currentSystemCursor]` needs to talk to the window server.

**Comment by miniak** [comment]
@zcbenz Do you know if it's possible to somehow pump `NSRunLoop` on my own, to prevent the app from becoming not responding? Without having to patch Electron code?

**Comment by miniak** [comment]
Actually, I have incorrectly called `[NSApplication sharedApplication]` on a background thread, when doing the experiments. Calling it on the main thread works fine.

**Comment by zcbenz** [comment]
If you call `sharedApplication` on a background thread and pump `NSRunLoop` there too, it can probably also work.
