### ISSUE TITLE
app.relaunch([options]) is not working

### ISSUE THREAD

**Issue by ndkcha** [electron/electron#6579]
* Electron version: v1.2.7
* Operating system: OS X 10.11.5

I want to change userData path with path defined by user. So, I'm fetching the path from UI, storing it into a file. So that next time app launches, it changes the path.
I wanted to restart the app as soon as user has selected the path. I tried app.relaunch() function. But it didn't work, neither it returned error.

I used exact same example mentioned in documentation. http://electron.atom.io/docs/api/app/#apprelaunchoptions

I want to restart the app for both Windows and Mac platforms. Can you check if it's an issue or I'm using it wrong ?

**Comment by MarshallOfSound** [comment]
From the docs you linked.

> Relaunches the app when current instance exits.

You must call `app.relaunch()` then `app.exit()`
