### ISSUE TITLE
Electron gui refreshing when i click on a button

### ISSUE THREAD

**Issue by hash000000Beard** [electron/electron#6580]
I am using socket.io with electron to create a IM-client.
I followed this tutorial [IM-clinet Tutorial](http://socket.io/get-started/chat/)  from sockiet.io. and everything runs perfectly when i run the server and access my html file on local host. 

However, when I tried to migrate the code to Electron, i managed to Load the page in the gui(or chrome ?) of electron, however, when i write a message and click send, the page (of the gui) refreshes and does not transfer the message to the server.

My electron code:

```

const electron = require('electron');
const {app} = electron;
const {BrowserWindow} = electron;



app.on('ready', function() {

  var  mainWindow = new BrowserWindow({
        height: 600,
        width: 500,
        darkTheme: true
    });
  
     mainWindow.loadURL('http://127.0.0.1:3000/?');


   });
```

* Electron version: "electron-prebuilt": "~1.2.6"
* Operating system: Elementary OS Freya

**Comment by mnquintana** [comment]
For questions about writing apps, I suggest seeking help from [the community](https://github.com/electron/electron#community). The GitHub Issues list is only for bug reports and feature requests.
