### ISSUE TITLE
Download keeps failing on setup

### ISSUE THREAD

**Issue by vsecades** [electron/electron#6581]
This file refuses to download completely.  Starts out OK, then drops to a crawl and eventually the python script errors out:

https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/osx/x64/0b5aa7b6ca450681c58087e14f72238aab5ab823/libchromiumcontent-static.zip

trying a wget on it is not really more helpful.  It starts out well, then drops to a crawl again.

* Electron version:
Latest version of Electron
* Operating system:
Mac OS X El Capitan

**Comment by zcbenz** [comment]
It is a rather large file, so you have to have a very fast and stable network to be able to download it.

However if you are not building your own Electron distribution, you can use the minimal bootstrapping:
http://electron.atom.io/docs/development/build-system-overview/#minimal-bootstrapping

**Comment by rafaelnobrepd** [comment]
I've been trying to bootstrap electron for a week and always fail downloading this from the script 👎
