### ISSUE TITLE
Redirect request in protocol handler

### ISSUE THREAD

**Issue by retrohacker** [electron/electron#6582]
* Electron version: 1.2.8
* Operating system: All

I have a custom protocol implemented that intercepts `peer://` requests and serves back HTML documents.

Some of these documents have protocol relative URLs that should be destined for `http://` but get passed into `peer://`. It is pretty easy to identify these (they are usually in the form of `www\..*\.com`),  but I'm having trouble finding a way to pass the request back off to the default `http://` protocol handler.

Is this supported by http://electron.atom.io/docs/api/protocol/ ?

**Comment by zcbenz** [comment]
No it is not supported, I'm merging this to #4303.
