### ISSUE TITLE
How can I used the docking framework used by Atom?

### ISSUE THREAD

**Issue by vrmerlin** [electron/electron#6583]
I played with the Electron API Demos, and it looks like there is some really nice APIs and mechanics. But, I was hoping that the panel docking mechanics that are used in Atom would be available directly in Electron, for my own application. Is that not possible? I understand I could write an Atom plugin, but we are not really interested in extending an IDE, as much as writing a completely different application.

Thanks,
John

**Comment by paulcbetts** [comment]
Nope, not possible, you'll have to make your own

**Comment by sbruchmann** [comment]
@vrmerlin You might be interested in  [cocos-creator/editor-framework](https://github.com/cocos-creator/editor-framework)
