### ISSUE TITLE
Unable to use "§" in hotkey

### ISSUE THREAD

**Issue by escaton** [electron/electron#6586]
* Electron version: 1.2.8
* Operating system: macOS

Unable to use `§` in hotkey, so registering globalHotkey `CommandOrControl+§` fails.
This symbol is on `~` place on mac european keyboards.

**Comment by zcbenz** [comment]
Only system supported hot keys can be used in Electron, and there is no key code of "§" for registering hot keys on Windows and Linux, so we are not able to provide it in Electron.
