### ISSUE TITLE
Electron 1.3.0-pre: Menus are oddly spaced and have yellow highlight on Win32

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#6587]
![image](https://cloud.githubusercontent.com/assets/1396/17084998/fedc4c18-5181-11e6-862f-42fab562a962.png)

Easy to miss on the default app since it's set to hide menus by default

**Comment by MarshallOfSound** [comment]
FWIW I can't reproduce on either the 32bit or 64bit versions of Electron `1.3.0` on Windows 10.  Could something else be causing this?

**Comment by paulcbetts** [comment]
I'm using the binary from the unpublished 1.3.0 release, is that what you're grabbing from?

**Comment by MarshallOfSound** [comment]
Yep, I grabbed straight from the draft release

**Comment by zcbenz** [comment]
It is probably related to DPI settings, I can also reproduce on my Windows 8.1 machine.

**Comment by paulcbetts** [comment]
I'm at 200% on this machine, confirmed
