### ISSUE TITLE
webview.capturePage not working

### ISSUE THREAD

**Issue by syw0602** [electron/electron#6592]
* Electron version: 1.2.6
* Operating system: Win 7  64

When i try to use  document.getElementById('webHome').capturePage(function(image){console.log(image)}) 

I got an error 
VM223:1 Uncaught TypeError: document.getElementById(...).capturePage is not a function(…)
![image](https://cloud.githubusercontent.com/assets/2759752/17097318/ebf3e8c2-528f-11e6-8b6d-148e31200216.png)

How can i get an screenshot of a webview?

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by steambap** [comment]
It's added in v1.2.8 #6355

**Comment by zcbenz** [comment]
Thanks @steambap for finding the root problem, I'm closing this issue now.
