### ISSUE TITLE
How to print the contents to pdf in 'div'

### ISSUE THREAD

**Issue by dongkuo** [electron/electron#6594]
I want to print the contents to pdf in 'div', but using `contents.printToPDF(options, callback)`, I  can only print all the contents of the window, or  print selected content.
Please tell me what to do. THX!

**Comment by zcbenz** [comment]
There is no way to just print an element of the page, you can try creating a new hidden window and finding a way to show the element in it, and then print the new window.

**Comment by vsemozhetbyt** [comment]
Maybe something like `window.getSelection().selectAllChildren(div);` and then `printToPDF` the selected content?

**Comment by marcus2vinicius** [comment]
http://stackoverflow.com/questions/37627064/how-to-print-a-div-in-electronjs
