### ISSUE TITLE
Latest master fails to build on Windows 10

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#6597]
* Electron version: `master`
* Operating system: Windows 10

A few days ago I could build Electron from the master branch with no problems.  As of today when I pulled the latest master the bootstrap fails when attempting to build `utf-8-validate`.

The errors can be found here: https://gist.github.com/MarshallOfSound/6f942a9ca57bc1eadccfe6dd108ed424

Have I missed a dependency update that I now need?

Currently have:   
* `git` 2.9.0
* `node` 6.2.2
* `npm` 3.9.5
* `python` 2.7.10
* Visual Studio 2015

EDIT: A similar set of errors occurs on the `bufferutils` module version up my log

**Comment by kevinsawicki** [comment]
@MarshallOfSound can you try removing `spec/node_modules` and then re-run `npm run bootstrap` and then try building?

**Comment by zcbenz** [comment]
The `utf-8-validate` module is an optional dependency of `ws` module, failure to build doesn't affect Electron.

It fails to build because we are using V8 5.2, which doesn't seems to be compatible with the module.
