### ISSUE TITLE
Electron is not playing nice with the jsftp module

### ISSUE THREAD

**Issue by IrosTheBeggar** [electron/electron#6604]
* Electron version: 1.2.6
* Operating system: OSX

I'm loading up the [jsftp module](https://github.com/sergi/jsftp) in the renderer like so:
```
const JSFtp = remote.require("jsftp");
var ftp = new JSFtp({
  // credentials
});
```

The following functions works
```
  ftp.auth("user", "pass", function(hadErr) {
    if (hadErr){
      console.log("Something went wrong");
      return;
    }
    console.log('it worked');
  });
```

However this function fails with an error of 'ftp.raw.mkd is not a function':
```
  ftp.raw.mkd("new_dir", function(err, data) {
      if (err) return console.error(err);
  });
```

The ftp.raw.mkd works just fine when I run the code using just nodejs.  But when I try running it in electron it errors.   Is there something I'm doing wrong?

On top of that the [jsftp-mkdirp module](https://github.com/sindresorhus/jsftp-mkdirp) doesn't work in electron but works just fine with node.

**Comment by zeke** [comment]
Not sure, but this might be caused by the patched version of `fs` in electron: https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md#limitations-of-the-node-api

**Comment by enlight** [comment]
Why are you doing a `remote.require`?

**Comment by IrosTheBeggar** [comment]
I'm using remote.require because  this is being used in the renderer.  I'm setting it up like this

```
'use strict';

const remote = require('electron').remote;
const app = remote.app;
const dialog = remote.require('electron').dialog;

const JSFtp = remote.require("jsftp");

...
```

**Comment by MarshallOfSound** [comment]
@IrosTheBeggar You don't need to use `remote.require` to fetch modules in the renderer process. It just adds all sorts of problems if you aren't using it correctly.

Your code should be this.

```js
'use strict';

const remote = require('electron').remote;
const app = remote.app;
const dialog = remote.dialog;

const JSFtp = require("jsftp");
```

At least from what I can see?

**Comment by zcbenz** [comment]
This is the `remote` modules doesn't support getting new properties of the remote object, using the module in renderer process should solve it.
