### ISSUE TITLE
Remote DevTools in a webview throws error

### ISSUE THREAD

**Issue by marcelofarias** [electron/electron#6605]
Steps to reproduce the problem:
Load a remote DevTools front-end in a webview (same Electron version on both ends)

What is the expected behavior?
Remote DevTools is opened in the webview

What went wrong?
"Uncaught TypeError: Cannot read property 'extensions' of undefined".
At this point, it tries to access window.runtime.extensions("settings").
See screenshot.

Did this work before? Yes 51.0.2704.63

Chrome version: 52.0.2743.82
OS Version: OS X 10.11.4

Worked fine until Electron 1.2.0 (Chromium 51.0.2704.63) with the disablewebsecurity attribute set. Broken on 1.2.1.
Current chromium version (1.3.0): 52.0.2743.82

![screen shot 2016-07-25 at 5 36 13 pm](https://cloud.githubusercontent.com/assets/1028286/17125639/1a265cce-52aa-11e6-8413-2d75c642dbb2.png)

**Comment by marcelofarias** [comment]
@zcbenz I'm not sure whether this issue belongs here or to the Chromium project or somewhere else. Do you think it might be related to https://github.com/electron/electron/pull/5711 ?

**Comment by zcbenz** [comment]
Yeah it is very likely related.

**Comment by marcelofarias** [comment]
Any workarounds for the time being? window.runtime seems to kick in after a while under some unclear circumnstances. Not sure if there's ant trick I can do at preload time.
