### ISSUE TITLE
Cannot read property 'getSources'

### ISSUE THREAD

**Issue by I-n-d-e-r** [electron/electron#6611]
* Electron version: 1.3.0
* Operating system: Fedora 24

desktopCapturer error
Source: http://electron.atom.io/docs/api/desktop-capturer/

![Error](https://cloud.githubusercontent.com/assets/18102267/17133845/1fd0acd2-5328-11e6-9982-74a29b4f43a6.png)

**Comment by enlight** [comment]
`desktopCapturer` is only available in the renderer process, but you're attempting to access it in the main process.

**Comment by I-n-d-e-r** [comment]
Now it works, thanks and sorry for the inconvenience. To close :)

**Comment by I-n-d-e-r** [comment]
Now it works, thanks and sorry for the inconvenience. To close :)

**Comment by rohitgupta274509** [comment]
I am using in desktopCapturer in renderer process still getting error -
renderer.js:59 Uncaught TypeError: Cannot read properties of undefined (reading 'getSources')
    at appScreenshot (renderer.js:59:21)
    at HTMLInputElement.<anonymous> (index.html:17:17)

**Comment by kitety** [comment]
> I am using in desktopCapturer in renderer process still getting error - renderer.js:59 Uncaught TypeError: Cannot read properties of undefined (reading 'getSources') at appScreenshot (renderer.js:59:21) at HTMLInputElement. (index.html:17:17)

I found the link for the answer https://www.electronjs.org/zh/docs/latest/breaking-changes#planned-breaking-api-changes-170

**Comment by Moiz439** [comment]
i am getting this error plz help me to solve this 
![image](https://github.com/electron/electron/assets/71594607/e8880669-f1c5-43a5-8c01-f86b7ab5543d)
