### ISSUE TITLE
Offscreen rendering performance issues

### ISSUE THREAD

**Issue by gerhardberger** [electron/electron#6614]
* Electron version: 1.2.8-
* Operating system: macOS 10.11.6

We're trying to implement an offscreen rendering mechanism for Electron based on the approach [CEF](https://bitbucket.org/chromiumembedded/cef) uses, but ran into some performance issues, which are probably related to Electron.

Our implementation uses a custom `WebContentsView` and `RenderWidgetHostView` class to prevent the rendering of a native separate window and to hook into delegates.
When a frame needs to be sent, we create a [`CopyOutputRequest`](https://cs.chromium.org/chromium/src/cc/output/copy_output_request.h?q=copyoutputreq&sq=package:chromium&l=22) and then copy the bitmap data from the GPU with [`CropScaleReadbackAndCleanMailbox`](https://cs.chromium.org/chromium/src/components/display_compositor/gl_helper.h?q=cropscale&sq=package:chromium&l=186). We can also control the frame rate of the renderer process.

If I render one browser that has content with 60fps I get around 30-40fps and if I increase the browser count it just gets even worse. If I lower the fps it starts working fine though.

If I observe my system's load it's nowhere near full, so there could be room for speeding up, but it doesn't happen, so I suspect that maybe the Chromium processes in Electron get held back or something happens in the main Electron process that causes this. Could something like that happen?

**Comment by zcbenz** [comment]
Sorry I can't give you any advice since I never looked into it before. There is no code in Electron interacting with GPU except for `BeginFrameSubscription` and `CapturePage`, and the only code using `RenderWidgetHostView` is setting background color and switch focuses. If you are only running the code on macOS it might also be related to `NativeWindowMac` using layers.
