### ISSUE TITLE
`view-painted` event does not work as expected

### ISSUE THREAD

**Issue by vsemozhetbyt** [electron/electron#6622]
* Electron version: 1.3.1
* Operating system: Windows 7 x64
 
Here is the small test app that gets screenshots from a list of URLs.

`package.json`
```json
{
  "name": "electron-html2img-test",
  "main": "html2img.win.js"
}
```
`html2img.win.js`
```js
/******************************************************************************/
'use strict';
/******************************************************************************/
const fs = require('fs');
const { app, BrowserWindow } = require('electron');
/******************************************************************************/
const urls = [
  'http://json.org/json-de.html',
  'http://json.org/json-en.html',
  'http://json.org/json-fr.html',
];

let   mainWindow;
let   i = 0;
/******************************************************************************/
app.once('ready', createWindow);
/******************************************************************************/
function createWindow() {
  mainWindow = new BrowserWindow({ webPreferences: { nodeIntegration: false } });
  getDoc();
}
/******************************************************************************/
function getDoc() {
  if (urls.length) {
    mainWindow.webContents.once('view-painted', saveDoc);
    mainWindow.loadURL(urls.shift());
  } else {
    console.log('All done.');
  }
}
/******************************************************************************/
function saveDoc() {
  mainWindow.capturePage(img => {
    fs.writeFileSync(`${++i}.png`, img.toPNG());
    console.log(`${mainWindow.webContents.getURL()} saved.`);
    getDoc();
  });
}
/******************************************************************************/
```
Output:
```
 saved.
http://json.org/json-en.html saved.
http://json.org/json-en.html saved.
All done.
```
Issues:

1. The empty string instead of the first `getURL()` value.
2. The same string in the next calls instead of different URLs.
3. The `1.png` and `2.png` are empty images with 0 bytes.
4. The `3.png` is an image of the second URL with lacunas in places of the `img` element and text blocks.
5. The last page in the window is `http://json.org/json-fr.html`, however the `3.png` is the image of `http://json.org/json-en.html`.
6. The second app launch give another output:

  ```
   saved.
  http://json.org/json-en.html saved.
  http://json.org/json-fr.html saved.
  All done
  ```

  The `3.png` is still the image of `http://json.org/json-en.html`, but without lacunas. If I delete `electron-html2img-test` folder from `c:\Users\[username]\AppData\Roaming\`, the first and the second launches are reproducible.

**Comment by vsemozhetbyt** [comment]
It seems `view-painted` listener should be added after `did-finish-load` fired. However, the result is still unsatisfactory.

This code pruduces a more reliable flow:
```js
/******************************************************************************/
'use strict';
/******************************************************************************/
const fs = require('fs');
const { app, BrowserWindow } = require('electron');
/******************************************************************************/
const urls = [
  'http://json.org/json-de.html',
  'http://json.org/json-en.html',
  'http://json.org/json-fr.html',
];

let   mainWindow;
let   i = 0;
/******************************************************************************/
app.once('ready', createWindow);
/******************************************************************************/
function createWindow() {
  mainWindow = new BrowserWindow({ webPreferences: { nodeIntegration: false } });
  mainWindow.webContents.on('did-finish-load', saveDoc);
  getDoc();
}
/******************************************************************************/
function getDoc() {
  if (urls.length) {
    mainWindow.loadURL(urls.shift());
  } else {
    console.log('All done');
  }
}
/******************************************************************************/
function saveDoc() {
  mainWindow.webContents.once('view-painted', () => {
    mainWindow.capturePage(img => {
      fs.writeFileSync(`${++i}.png`, img.toPNG());
      console.log(`${mainWindow.webContents.getURL()} saved.`);
      getDoc();
    });
  });
}
/******************************************************************************/
```
Output is OK:
```
http://json.org/json-de.html saved.
http://json.org/json-en.html saved.
http://json.org/json-fr.html saved.
All done
```
All the images contain expected data, but lacunas still exist. Compare with pages in the browser (sometimes the image logo and text blocks are not present):

![2](https://cloud.githubusercontent.com/assets/10393198/17176155/09da7060-5414-11e6-9447-84b68034149c.png)

![3](https://cloud.githubusercontent.com/assets/10393198/17176156/09df3aa0-5414-11e6-8724-a0aa85dcccb2.png)

**Comment by zcbenz** [comment]
It seems that `view-painted` only emits when first painting command is committed, instead of after the whole page gets painted.

**Comment by liusy182** [comment]
@vsemozhetbyt As far as I have tested, `view-painted` is emitted multiple times when a page is loaded. UI is "fully" painted after the last `view-painted` event. Have you tried to capture the image after the last `view-painted` event?

**Comment by vsemozhetbyt** [comment]
@liusy182 How can I detect that a current `view-painted` emitting is the last, final one for the current page?

**Comment by liusy182** [comment]
@vsemozhetbyt Sorry I couldn't think of a 100% reliable solution. One possible way is to have a short timeout after `view-painted`. If there is not subsequent `view-painted`, it means there is not more view update.

**Comment by vsemozhetbyt** [comment]
@liusy182 Well, it seems the `view-painted` is supposed to be a mean to manage without timeouts. If we still need timeouts, why use `view-painted` at all? We can manage just with timeouts [see code sample](https://github.com/electron/electron/issues/6426).

**Comment by liusy182** [comment]
you are right. Graphical commits looks more like an intrinsic behavior of chrome. Maybe we should not expose this at all.

**Comment by vsemozhetbyt** [comment]
It would be useful, if it fired once after a final paint / repaint stage or if we had something like `XMLHttpRequest.onreadystatechange` + `XMLHttpRequest.readyState` to check a paint / repaint stage.

**Comment by liusy182** [comment]
Hmm. The difficulty I can see here is that, we can never know when a page is "graphically" ready. For example, if a page has a continuos loop running animations, browser would never know when is the "final" paint.

**Comment by vsemozhetbyt** [comment]
It's a pity.

**Comment by zcbenz** [comment]
I'm closing this issue and reopening #6426 since `view-painted` is going to be removed.
