### ISSUE TITLE
BrowserWindow 'blur' event is fired when dragging a file into it on Windows, but not on OSX

### ISSUE THREAD

**Issue by tex0l** [electron/electron#6624]
* Electron version: 1.3.1
* Operating system: Windows 10 / OSX 10.11.6

Hi,
I'm having trouble with a little difference of behaviour for the 'blur' event between windows and mac.

I have this app:
```javascript
const { app, BrowserWindow, Tray } = require('electron')
const path = require('path')
let window, tray

app.on('ready', () => {
  tray = new Tray(path.resolve(__dirname, process.platform === 'darwin' ? './icon.png' : './icon.ico'))
  window = new BrowserWindow({})
  tray.on('click', () => {
    if (window.isVisible()) {
      window.hide()
    } else {
      window.show()
    }
  })
  window.on('blur', () => {
    window.hide()
  })
})
```

When I run it on OSX, the window appears at launch, and then I'm able to drag and drop a file into the window, and then handle the 'drop-file' event or whatever, without having the 'blur' event being fired, which is great !

Howver, when I run it on Windows, the window appears at launch as well, but when I click on a file (outside of the window), the blur event is fire right away (and in my case, the window disappears), preventing me from dropping the file in my window.

I cannot think of a simple workaround, and in this case I'm forced to think of two different behaviours for my app for drag & dropping files into it.

Is it possible to change the behaviour so that the 'blur' event on windows behaves just it does on OSX, or is it too much constrained by the system APIs ?

**Comment by zcbenz** [comment]
This behavior is unfortunately defined by Windows, and we are not able to change or work around it on Electron's side, so I'm closing this as won't fix.

You might try to work around it by setting a timer in the handler, or choose a different workflow on Windows.
