### ISSUE TITLE
Electron stops repainting after maximize/restore

### ISSUE THREAD

**Issue by craxal** [electron/electron#6625]
**Electron version:** 0.34.1 (forked)
**Operating system:** Windows 10

1.  Open an Electron application.
2. Click around to make sure the UI is responding.
3. Maximize the application window.
4. Click around to make sure the UI is still responding.
5. Restore (un-maximize) the application window.
6. Click around once more.

The UI doesn't redraw to reflect user interaction. UI events are still triggered and handled, but the UI stops updating visually. Maximizing or snapping the window frees the UI. Doing some window snapping seems to free it up as well. Only the top menu appears to remain visually functional.

I realize this may be a pretty obscure issue. I'm curious to know if others may have experienced this.

**Comment by kevinsawicki** [comment]
> Electron version: 0.34.1 (forked)

This is quite an old version of Electron, are you able to reproduce on the latest release, 1.3.1?

**Comment by craxal** [comment]
That'll take time for me to verify. I'm using a fork of Electron, and I heard they only recently merged the latest changes into the forked version. I'll follow up in a few weeks...

**Comment by kevinsawicki** [comment]
> I'll follow up in a few weeks...

Okay, I'm going to close this for now then, please comment back if you are still seeing this issue on the updated forked version. Also, if you do still see this issue, providing a minimal app demonstrating the behavior would be really helpful.

**Comment by craxal** [comment]
Recently updated to 1.3.1 and the issue still repros. I'm trying to see if I can get some app together that still has the issue, but that may prove difficult.

To my knowledge, the Electron fork we're using is identical to Electron proper.

**Comment by MRayermannMSFT** [comment]
Related: #7735
