### ISSUE TITLE
Identifier 'electron' has already been declared

### ISSUE THREAD

**Issue by markushaug** [electron/electron#6632]
* Electron version: 1.1.0
* Operating system: Win 10 Enterprise

When i run the builded exe, i get this error...

![electron error](https://cloud.githubusercontent.com/assets/19834699/17206361/9c63ea9c-54af-11e6-84f0-2abc73ff0892.png)

**Comment by kevinsawicki** [comment]
Can you include the code from your app's main script?

Does your app define/assign an`electron` variable in your app's main script?

**Comment by markushaug** [comment]
It has worked for me now... But with electron-packager, not with the builder.. But I would know what i did wrong.. ![electron error](https://cloud.githubusercontent.com/assets/19834699/17239149/27209e48-5562-11e6-81b9-478e56a4e298.png)

**Comment by kevinsawicki** [comment]
> It has worked for me now... But with electron-packager, not with the builder.. But I would know what i did wrong

Can you include the full source code instead of a screenshot? That might help us identify the problem, thanks.

**Comment by kevinsawicki** [comment]
Closing this out until more information is provided.
