### ISSUE TITLE
Online/Offline Event Detection not work

### ISSUE THREAD

**Issue by joshuaChou** [electron/electron#6633]
* Electron version:v1.2.7
* Operating system:windows 10 64bit win32-x64

Hi everyone,
  in my project , i use html5 api to check network online or offline , but i find some issues . my PC  have install virtual Box , network interface get a VirtualBox Host-Only Network . 

when i close my network my application will not get offline in this example [electron]( https://github.com/electron/electron/blob/master/docs/tutorial/online-offline-events.md) 

if I remove the VirtualBox Host-Only Network , the event will work. 

Thank!

**Comment by enlight** [comment]
Try using https://github.com/sindresorhus/is-online

Please direct any further questions to the [community](https://github.com/electron/electron#community), Issues are meant for bug reports and feature requests.

**Comment by zcbenz** [comment]
Thanks @enlight for answering this, I'm closing this issue now.
