### ISSUE TITLE
v8 inspector `--inspect`

### ISSUE THREAD

**Issue by develar** [electron/electron#6634]
I understand, that this is a NodeJS feature and you will get it finally when it will be available in the stable nodejs release.

But I wonder, is it possible to integrate earlier since Electron in any case ships with own version of nodejs?

[JetBrains debugger](https://blog.jetbrains.com/webstorm/2016/05/getting-started-with-electron-in-webstorm/) (IntelliJ IDEA, WebStorm) relies on `v8debug` to inject improved v8 debugger protocol implementation. It doesn't work for Electron and currently we disabled our protocol implementation for Electron. This issue is not reported because we were informed that new v8 inspector `--inspect` will be implemented as replacement of old v8 debugger protocol.

Currently, you can debug Electron apps, including packed (ASAR fs supported) in the JetBrains IDE, but the overall user experience will be much better with new v8 inspector.

**Comment by auchenberg** [comment]
Given Node 6 has this LTS, is there anything holding back Electron upgrading Node and enabling v8_inspector?

**Comment by deepak1556** [comment]
Have added support for `--inspect` that uses the inspector agent from node, which requires the following changes.

https://github.com/deepak1556/atom-shell/commit/4be174841e8a6df3133f29ad111b4ca90db6bdf7
https://github.com/deepak1556/node/commit/25fedf2543ac16e11894457f1c76f5a00d359402
https://github.com/deepak1556/libchromiumcontent/commit/fc611b9faf6b28bda55e029b32b6c2e3c422a0f3

`v8_inspector` has already gotten into `v8` https://bugs.chromium.org/p/chromium/issues/detail?id=635948 , so should we write our own inspector agent similar to how we support `--debug` flag or use the agent from node ? @zcbenz

**Comment by roblourens** [comment]
Just wondering, what's the status of this? Do we just need those 3 changes into their respective projects?

**Comment by kevinsawicki** [comment]
> Have added support for --inspect that uses the inspector agent from node, which requires the following changes.

That is awesome @deepak1556, is it ready to start opening some pull requests for?

> so should we write our own inspector agent similar to how we support --debug flag or use the agent from node ? 

Could you elaborate on this a little more? Are there downsides to using the agent from node?

**Comment by deepak1556** [comment]
@roblourens yup those are the only changes required. The node patch can very well be avoided if there is a way in gyp to override inlcudes of a target.

>  is it ready to start opening some pull requests for?

Have verified `--inspect` flag works fine on linux, needs more testing. Was hoping to PR this after 54 upgrade.

> Could you elaborate on this a little more? Are there downsides to using the agent from node?

No downside, just I am not sure what would be followed once we have a build that contains `v8_inspector` as part of `v8`. Will we make api changes in node as patch or will we write our own inspector agent to avoid it ?

**Comment by michaelprescott** [comment]
Although I have a fair amount of experience working with NodeJS and web apps, I've just now started experimenting with Electron.  I think it's important to be able to debug an app.  I know I can use the console to debug the renderer, but the only thing I've found on how to debug main process is https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process.md and I guess that doesn't work because of the issue noted here.  What other tools and techniques are Electron developers using to debug the main process?

**Comment by bengotow** [comment]
Hey @michaelprescott! The issue noted here is actually a feature request for Node's new `--inspect` flag (which allows third party debuggers, like VSCode, to connect to a node process.) You don't need this new flag to use the existing debugging approaches in the docs. For the renderer process, you should definitely be using the Chrome Developer Tools. For the main process, my personal favorite is using node-inspector, but there are a couple different options documented here:  https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process-node-inspector.md. Hope that helps!

**Comment by secondfry** [comment]
You can't currently use `electron-inspector` with latest version of `electron-rebuild` (and this won't be reflected in docs as per #9045), so this should probably be done instead of refactoring `electron-inspector`.

**Comment by auchenberg** [comment]
@deepak1556 Have you had time to look into a PR? Need any help?

**Comment by deepak1556** [comment]
@auchenberg with the initial work there were some test failures, mostly because of my misuse of `v8::Platform` , didn't manage to look into it after that. Things have changed much with the `v8_inspector` to embed easily, it has been made available as a standalone library so most of the patches in my version shouldn't be required. It will take time before I work on PR, so feel free to work on this. Thanks!

**Comment by kevinsawicki** [comment]
This will be included in the next Electron release, 1.7.2

**Comment by bpasero** [comment]
Aweomse, can't wait to give it a try 👍

**Comment by ibash** [comment]
Is there a way to enable this at runtime? My usecase is that I want to enable for internal electron builds so that we can easily debug.

Previously I replaced the executable in the macos package with on that would run with the flag, but this breaks automatic updates.
