### ISSUE TITLE
Option to run arbitrary scripts in a render process

### ISSUE THREAD

**Issue by nathansobo** [electron/electron#6638]
```
electron --run-in-render-process ./my-script.js
```

It would be great if I could run something like the above command and run a script in an Electron window, but otherwise have things behave as close to running the script with Node as possible. That would mean that stdout and stderr would be forwarded, the exit code would be transferred from `process.exit` calls, etc.

It looks like this _is_ implemented in third-party libraries such as https://github.com/juliangruber/browser-run and https://github.com/Jam3/devtool, but it seems like something that would be nice to bake into the default `electron` command.

**Comment by zcbenz** [comment]
I'm closing this since no one seems to be interested in implementing this and too few people need this feature. But I would be happy to accept a pull request to implement this.
