### ISSUE TITLE
context-menu event doesn't get unhooked from crashed renderers

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#6643]
* Electron version: 1.2.5
* Operating system: Any

1. Clone https://github.com/paulcbetts/electron-spellchecker
2. `npm start`
3. Type some stuff, reload the page via Ctrl-R
4. Right click on something

In ContextMenuListener (https://github.com/paulcbetts/electron-spellchecker/blob/master/src/context-menu-listener.js#L31) we set up a listener for `context-menu` on a WebContents. However, when it gets trashed, it appears as if `context-menu` is still being dispatched to the old WebContents, but we have no way to unhook this message

**Comment by zcbenz** [comment]
This is the classic problem when subscribing to an event of and object in the main process, the `WebContents` is not destroyed when you refresh the page, and the remote callback is not cleaned.

You probably need to use DOM's `contextmenu` event instead, or refactor the module to send IPC messages to the page for the `context-menu` event.

**Comment by paulcbetts** [comment]
This makes the `context-menu` event almost impossible to use with WebViews in practice, and the DOM `contextmenu` event doesn't have any of the information that `context-menu`

**Comment by paulcbetts** [comment]
Alright, if anyone finds this, here's a reasonable workaround:

```js
  app.on('ready', () => {
    // NB: Work around electron/electron#6643
    app.on('web-contents-created', (e, wc) => {
      wc.on('context-menu', (ee, params) => {
        wc.send('context-menu-ipc', params);
      });
    });
  });
}
```
