### ISSUE TITLE
autoUpdater.quitAndInstall() does not work if checked for update after update-downloaded is emitted on Windows

### ISSUE THREAD

**Issue by KSKS** [electron/electron#6647]
App installed on windows.
1. App calls autoUpdater.checkForUpdates().
2. Event 'update-available' is emitted, then 'update-downloaded' is emitted.
3. App calls autoUpdater.checkForUpdates() again.
4. Event 'update-not-available' is emitted. I assume this means no newer update is available.
5. Now the app calls autoUpdater.quitAndInstall() for the first update downloaded in step 2. It gives an error "Error: No update available, can't quit and install"

Expected: The app should quit and install, even after it emitted "update-not-available", as long as it emitted "update-downloaded" at least once.

Sometimes the user might not want to quit and install an update immediately, and the app should be able to keep checking for newer update.

This works fine on Mac.

* Electron version: 1.2.6
* Operating system: Windows

**Comment by zcbenz** [comment]
I think the second call of `autoUpdater.checkForUpdates` should have the same result with the the first call, @paulcbetts might have a better idea of what the correct behavior should be.

**Comment by KSKS** [comment]
That is basically the behavior on Mac right now.
