### ISSUE TITLE
Provide a way to dynamically set GOOGLEAPIS_API_KEY

### ISSUE THREAD

**Issue by dsanvita** [electron/electron#6648]
* Electron version: 1.3.1
* Operating system: OS X 10.11.6

Follow the instructions for running the electron-quickstart.  Modify the index.html by adding this script to the bottom:

```
<script>
	window.addEventListener('load', function() {
		if (navigator.geolocation) {
			navigator.geolocation.getCurrentPosition(function(result) {
				console.log(result);
			}, function(error) {
				console.log(error);
			});
		}
	});
</script>
```

You will now see a Position Error in your console when running.  Error Code 2, 403 returned from google.  Adding a permission request handler to your session and always calling the callback with true does not eliminate this error.

**Comment by dsanvita** [comment]
I just ran the quickstart app with my geolocation script again and this time the geolocation reported success.  Maybe google servers were down for several hours earlier?  Or is there some sort of per-ip daily quota?

**Comment by davemackintosh** [comment]
I'm seeing the same. will try again shortly.

**Comment by zcbenz** [comment]
The code 403 means there are too many requests using our built-in API token, currently you have to rebuild Electron with your own API token.

I think we should provide a way to allow users to dynamically set the API token, and I'm changing this issue to track it.

**Comment by davemackintosh** [comment]
Yeah, I saw that in the code. Rolled my own request and token client side for now. Don't need it to be accurate.

**Comment by dsanvita** [comment]
How do you get an api token from Google?  Does it cost money?  And how do you set this token in the current version of electron?

**Comment by fdelayen** [comment]
@dsanvita It's here : https://developers.google.com/maps/documentation/geocoding/get-api-key
It's free of charge for a certain amount of request per day / month etc.
I'll see to provide an API to set the key in a pull request.

**Comment by MarshallOfSound** [comment]
@dsanvita  Am I missing something here or won't this check your environment variables for the required key

https://github.com/electron/electron/blob/4ec064d311275bb8d6d652b9b917c0d199b3cb19/atom/app/atom_main_delegate.cc#L113

That environment work around would appear to be available

**Comment by fdelayen** [comment]
There is another source file where this key is directly concatenated to the url of the api.

**Comment by fdelayen** [comment]
@MarshallOfSound You're wright, the environment variable is working (should be documented though).
It looks like chromium is caching those keys and does not provide any way to change it afterwards so I think it's the only api we can provide here...

@zcbenz What are those lines for ? If I remove those, the geolocation still works properly... [https://github.com/electron/electron/blob/master/atom/browser/atom_access_token_store.cc#L60](https://github.com/electron/electron/blob/master/atom/browser/atom_access_token_store.cc#60)

I'd like to propose documentation for that, but as it's still hard coded...

**Comment by zcbenz** [comment]
> @zcbenz What are those lines for ? If I remove those, the geolocation still works properly... https://github.com/electron/electron/blob/master/atom/browser/atom_access_token_store.cc#L60

It is used by the speech recognition if i remember correctly.

**Comment by fdelayen** [comment]
Okay thanks !

**Comment by daniel3d** [comment]
Im trying to set the en variables in the package main.js is this the correct place ?

```
process.env.GOOGLE_API_KEY = 'xxxx'
process.env.GOOGLE_DEFAULT_CLIENT_ID = 'xxxx-xxx'
process.env.GOOGLE_DEFAULT_CLIENT_SECRET = 'xxxx'
```

**Comment by MarshallOfSound** [comment]
@daniel3d Setting environment variables in your node script won't set them for other processes.  You need to set them at the user or system level on Windows.  Or `export` them on *nix systems

**Comment by daniel3d** [comment]
@MarshallOfSound I did that windows so i set them up under the user and the system variables no luck so far is this mean i cannot use the electron-prebuilt version and i need to compile it ?

**Comment by panga** [comment]
There's no solution for this issue?

**Comment by zeke** [comment]
I got an API key from https://developers.google.com/maps/documentation/geocoding/get-api-key and tried setting it in the environment, but I'm still getting a 403.

```sh
GOOGLEAPIS_API_KEY="MY_KEY" GOOGLE_API_KEY="MY_KEY" electron .
```

@fdelayen can you clarify what you mean by this:

> It looks like chromium is caching those keys and does not provide any way to change it afterwards so I think it's the only api we can provide here...

**Comment by MarshallOfSound** [comment]
@zeke The API key you preset to Chromium must have quite a few more API's enabled.

See the list here https://www.chromium.org/developers/how-tos/api-keys

**Comment by fdelayen** [comment]
@zeke @marshallofsound Yes, you should just enable a few apis related to geoposition (you don't have to enable everything) and then set the environment var and it will work. Tested a few month ago. My message just stated that I did not find an easier way at the moment to help devs to provide this key (like a js api)

**Comment by daniel3d** [comment]
@zeke I was not able to make it work on windows with the environment vars. I was dragged in a different project i will be looking in to this next week will report if i find something out

**Comment by zeke** [comment]
> enable a few apis related to geoposition (you don't have to enable everything)

@fdelayen. sorry but I'm not sure what you mean by this. Can you provide a working example?

**Comment by fdelayen** [comment]
@zeke, I'll look at it tomorrow ;-)

**Comment by eugirdor** [comment]
Is there an ETA on having a standard way of proving our own key?  I tried setting the environment variable workaround, but it did not work for me.  I can call the API from curl fine and I can see the environment variables set by inspecting `process.env`, but I still get a 403 from `getCurrentPosition()`

**Comment by bbondy** [comment]
Note that there's also other endpoints that work the same that are not google. 
If its of use to anyone, this env var allows you to set that as well and could be cherry-picked in:

https://github.com/brave/electron/commit/f8902043f283ac4813717f68b6261ec1b2b3f3df
https://github.com/brave/electron/commit/eb943e4690b6ee7a4d6924c58b7250062f8bd26f

**Comment by stealthanthrax** [comment]
any luck on this issue??
