### ISSUE TITLE
Error: Unable to find a valid app at Object.

### ISSUE THREAD

**Issue by Mini256** [electron/electron#6650]
* Electron version:1.3.0
* Operating system: Window10

when I run “electron ./app”  ,it‘s ok,no error. then I run this
`electron-packager ./app --out=dist --app-version=%npm_package_version% --asar --overwrite --platform=win32 --arch=x64`

it builds successfully but when I run the exe,a JavaScript error occurred in the main process.

![20160729182843](https://cloud.githubusercontent.com/assets/5086433/17246004/e9c349c4-55bb-11e6-999d-1fe194ebc3e1.png)

How can I fix it?

**Comment by zcbenz** [comment]
Please file a bug at the repo of electron-packager, or seek help from [the community](https://github.com/electron/electron#community). The issues list of Electron only deals with bug reports and feature requests.
