### ISSUE TITLE
--disable-gpu setting per BrowserWindow?

### ISSUE THREAD

**Issue by TomBZombie** [electron/electron#6651]
* Electron version: 1.2.6
* Operating system: Linux (KDE)

Transparent windows work great with some issues with nvidia drivers neding the `--disable-gpu` workaround. Obviously this has a performance hit.

I'm using a transparent window as a basic OSD that appears above all other windows on the PC. It's really basic, just displaying some information so the GPU doesn't really matter. However, the rest of my application is considerably more complex. Electron seems to start a process for each window, would it be possible to make `disableGPU` a `BrowserWindow` option?

I could write two seperate applications, one with `--disable-gpu` set and one without but this will add extra time to the development process (getting the two apps to communicate) and the build process.

**Comment by zcbenz** [comment]
Unfortunately the GPU setting is global in Chromium, we are unable to only turn off GPU acceleration for only one window. I'm closing this as won't fix since it is a limitation of Chromium.
