### ISSUE TITLE
Electron doesn`t work propertly with es6

### ISSUE THREAD

**Issue by scorpioRED** [electron/electron#6652]
* Electron version: v1.3.1
* Operating system: os X el capitan

Hi when I run electron app by npm script or build with electron-packager it doesn`t work with es6
But when I run app from console in my project by electron . everything is work fine

**Comment by sbruchmann** [comment]
You might have passed an old electron version as a cli option to [electron-packager](https://github.com/electron-userland/electron-packager). See [REAMDE#Usage (from the command line)](https://github.com/electron-userland/electron-packager#from-the-command-line).

On a side note, I guess you did not passed the [`--save`](https://coderwall.com/p/isrcca/install-npm-packages-with-save-or-save-dev) flag when installing [electron-prebuilt](https://github.com/electron-userland/electron-packager).

**Comment by scorpioRED** [comment]
I have installed electron-prebuilt as global

**Comment by zcbenz** [comment]
You can check the version of Electron by printing `process.versions.electron` in console, for questions it is recommended to seek help from [the community](https://github.com/electron/electron#community).
