### ISSUE TITLE
Angular 2 Components does not render dynamic Styles in Electron

### ISSUE THREAD

**Issue by jackesdavid** [electron/electron#6653]
* Electron version: 1.3.1
* Operating system:Windows 10

hi, i have this very strange behavior when dynamic components are loaded the app does not refresh new styles... the app wait a input touch ou click to refresh .. very very strange

https://i.gyazo.com/f1410231c7cf51a7fbe4c8056b52f27e.mp4

![Render Issue](https://gyazo.com/f1410231c7cf51a7fbe4c8056b52f27e.gif)

**Comment by jackesdavid** [comment]
maybe something wrong with web components .. shadow dom...

**Comment by jackesdavid** [comment]
someone can help me?

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem? And does the same page work correctly in Chrome browser?

**Comment by jackesdavid** [comment]
Yes Friend the same page works great in Chrome, Edge, Firefox and without this strange pause in render

**Comment by zcbenz** [comment]
Closing until more information is provided.
