### ISSUE TITLE
Allow to `childProcess.fork()` Electron from Electron

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#6656]
Currently, if you try to use `childProcess.fork()` from a script running in Electron, it will fork a new process with the [`ELECTRON_RUN_AS_NODE=1`](https://github.com/electron/electron/blob/master/docs/api/environment-variables.md) environment variable hard-coded. This is a good default as otherwise it would break a lot of existing Node.js modules. However, there should be a way to override it. I need to be able to fork a Electron process from Electron without the `ELECTRON_RUN_AS_NODE` environment variable, so `require('electron')` is available.

Previous discussion: https://github.com/electron/electron/issues/4520

-

* Electron version: 1.3.1
* Operating system: macOS 10.11.6

**Comment by zcbenz** [comment]
You can fork a script by calling `spawn(process.execPath, ['script.js'])`, it is exactly how `fork` is implemented.

**Comment by sindresorhus** [comment]
That leaves out the IPC channel, which is something I need. It's also a somewhat surprising behavior which should be documented.

**Comment by zcbenz** [comment]
The IPC channel can be added by setting a fd as `ipc`:

```js
    // Leave stdin open for the IPC channel. stdout and stderr should be the
    // same as the parent's if silent isn't set.
    options.stdio = options.silent ? ['pipe', 'pipe', 'pipe', 'ipc'] :
        [0, 1, 2, 'ipc'];
```

I agree we should document the behavior of `child_process.fork`.

**Comment by sindresorhus** [comment]
@zcbenz I'm trying to add support for Electron in [AVA](https://github.com/avajs/ava), so I can test modules for Electron (that needs `require('electron')`). I'm aware I could change the `stdio` in `spawn`, but I'm not interested in changing to use `spawn`. I think a custom option to `fork` would be much more natural, maybe `{electronRunAsNode: false}`. Electron shouldn't change the behavior of common Node.js API's without providing a super easy way to restore the original behavior.

**Comment by zcbenz** [comment]
The `fork` means executing the script with current process. However Electron doesn't really have a mode to run scripts, it is a feature of the default app. If you packaged your app and doesn't provide a way to run scripts in your app, the default way of `fork` will not work at all.

Also on macOS there two types of process, if you run the script in the main process, a new instance of your app will be started, if you run it in the renderer process, the script will be run in background. It is unclear which way would be expected.

So if we want to add `{electronRunAsNode: false}` that can really work, we have to add a new patch in Node and a mode of Electron, which is not the original behavior.

**Comment by sindresorhus** [comment]
> The fork means executing the script with current process. However Electron doesn't really have a mode to run scripts, it is a feature of the default app. If you packaged your app and doesn't provide a way to run scripts in your app, the default way of fork will not work at all.

That's fine. I'm trying to use the `electron` binary instead of `node`, not use it in a packaged app.

> Also on macOS there two types of process, if you run the script in the main process, a new instance of your app will be started, if you run it in the renderer process, the script will be run in background. It is unclear which way would be expected.

This is about running something made for Node.js in Electron using the `electron` binary, so it will always be in the main process.

-

All I want it to have the behavior of not `ELECTRON_RUN_AS_NODE=1`, with all the side-effects you mentioned.

**Comment by sincerefly** [comment]
@zcbenz I packaged with electron-builder, and `process.execPath` become my output exe, and spawn launch app again and again, then,  what should I run js script when packaged the app.

**Comment by meekaah** [comment]
indeed once built using electron-builder there is no work around... (to my knowledge...) since the exePath becomes your app... any ideas / suggestions???

**Comment by mckravchyk** [comment]
I want to spawn a child process but I don't need any Electron APIs. Will the default `ELECTRON_RUN_AS_NODE=1` flag work with electron-builder?

**Comment by Visual-Dawg** [comment]
Given the amount of issues referencing this issue, it would really be nice to have a feature like that.
I also found myself needing need it.

**Comment by clavin** [comment]
For anyone in the future looking for an equivalent to `childProcess.fork` in Electron, consider checking out the recent `utilityProcess` API: https://www.electronjs.org/docs/latest/api/utility-process
