### ISSUE TITLE
Hangs if response is HTTP 304

### ISSUE THREAD

**Issue by voidmonk** [electron/electron#6657]
* Electron version: 1.3.1
* Operating system: Ubuntu 14.04.2 LTS

Working with Nightmare.js (which uses Electron under the hood), it seems like the process doesn't gracefully end or raise an error/event after `webContents` `did-stop-loading` event if the response' HTTP status code is 304 (not modified). I simulated the HTTP 304 response using httpbin (https://httpbin.org/status/304). I raised an [issue in the Nightmare repo](https://github.com/segmentio/nightmare/issues/740) as well, since it's not clear if this problem is due to Electron.

Here's the basic test code:

```node
const { app, BrowserWindow } = require('electron')
let window

app.on('ready', () => {
  window = new BrowserWindow({show: false})
  window.loadURL('https://httpbin.org/status/304')
})
```

Sequence of events:

```
app - ready
app - web-contents-created
app - browser-window-created
webContents - did-start-loading
webContents - did-get-response-details
? - did-fail-provisional-load
webContents - did-stop-loading
```

Any clues as to why the process hangs this way. Is there a way to trace & debug this (i.e. via any other specific events) in more detail?

**Comment by deepak1556** [comment]
The behavior seems to be consistent with chrome, the only issue seems to be that devtools doesn't record the request but `log-net-log` trace captures it fine.

I am unable to understand the hang part of the issue, what event do you expect after the `did-stop-loading` event ?

**Comment by voidmonk** [comment]
@deepak1556 All HTTP responses (200, 302, 404, 501 etc.) invoke the `ready-to-show` event in Electron, where-as 304 doesn't. Chrome terminates a '304 Not Modified' request. How can this be achieved with Electron? What event can be used to detect and handle a 304 response?

**Comment by zcbenz** [comment]
> @deepak1556 All HTTP responses (informational like HTTP 100, success like 200, redirections like 302, client errors like 404, server errors like 501 etc.) invoke the ready-to-show event in Electron, where-as 304 doesn't.

The `ready-to-show` only emits when the page has been drawn, which for `304` code there is no page to show at all.

> Chrome terminates a '304 Not Modified' request. How can this be achieved with Electron? What event can be used to detect and handle a 304 response?

The request is also terminated in Electron. You can detect the response with `did-get-response-details` event.
