### ISSUE TITLE
Binary stream from webview to renderer process?

### ISSUE THREAD

**Issue by isiahmeadows** [electron/electron#6660]
I have a binary stream (generated HTML UTF-8 file of potentially large size adapted from a generator), and I was looking for the best way to send that from a webview process to the parent renderer process to be immediately compressed. Currently, I'm considering using a temp file to keep it out of memory, but considering it's just a raw binary data stream, that would be highly inefficient, and I'd prefer to avoid native modules to accomplish this.

I'm thinking allowing zero-copy Stream transfers for `send` (if they're not in object mode) would probably work best, since Node itself already has facilities for similar with Streams (TCP, HTTP, FS, etc.).

**Comment by paulcbetts** [comment]
You can't zero-copy between processes without some kind of shared memory solution which afaik Chromium doesn't provide (since it would effectively defeat the whole idea of a sandbox multiprocess model). The best you can do is stream Uint8Arrays over IPC (which tbh will probably be sufficient)

**Comment by isiahmeadows** [comment]
Are those serialized? (BTW, Buffers are Uint8Array subclasses.)

**Comment by paulcbetts** [comment]
They'll be sent directly over IPC, not converted to a JSON or other format

**Comment by zcbenz** [comment]
Thanks @paulcbetts for answering this question, I'm closing it now.
