### ISSUE TITLE
Scrolling issues after Brave browser has updated Electron to version 1.3.0

### ISSUE THREAD

**Issue by CountLesnik** [electron/electron#6666]
* Electron version:
Electron 1.3.0

* Operating system:
Windows 7 - Windows 10

Issue:
After the new so far not officially released Brave version has included that update towards Electron 1.3.0 there are rendering glitches/tearing effects when scrolling down with deactivated hardware acceleration. There are also some when activating it, but so far deactivating hardware acceleration has removed that white lines/glitches/tearings when scrolling.

This is no longer the case after that update to Electron 1.3.0

Can be avoided in other Chromium based browsers that deactivating smooth scrolling is used, which is missing in Electron. You plan to add that option? Problem is that Google will also remove that feature at one point from the flags, could you find a way to keep that in Electron somehow then?

**Comment by bbondy** [comment]
Also if it works well, could you paste in the contents of the first section of chrome://gpu/?

**Comment by CountLesnik** [comment]
@zcbenz  Chrome works without any tearing or glitches. Also Chromium portable. In both official Google products i can enable hardware acceleration without glitches.

In Brave with Electron it was usable until the Chromium 52 upgrade without hardware acceleration and now after the new Chromium version there are glitches also without hardware acceleration.

**Comment by baconface** [comment]
Can you duplicate this behavior in Electron? I am asking because Brave forks and maintains their own build of Electron.

**Comment by zcbenz** [comment]
Closing until more information is provided.
