### ISSUE TITLE
Refocus app when my window closes/hides

### ISSUE THREAD

**Issue by blainesch** [electron/electron#6669]
* Electron version: 1.3.1
* Operating system: osx el capitan

I have an app that appears/disappears based on a global shortcut. If my focus is in chrome, and I focus my app, then unfocus the window, I'd expect my focus to be back on the previous app.

**Comment by zcbenz** [comment]
On OS X you have to hide your app to move focus to other apps, in Electron it is calling `app.hide`.

**Comment by blainesch** [comment]
Thank you!
