### ISSUE TITLE
More progress bar states for .setProgressBar method.

### ISSUE THREAD

**Issue by YurySolovyov** [electron/electron#6672]
* Electron version: 1.3
* Operating system: Win7+

![image](https://cloud.githubusercontent.com/assets/2168518/17288174/536dab04-57dc-11e6-8607-bc6198965ccb.png)

Would be helpful for multimedia apps.

Not sure how this should be integrated with existing API, but I'd added a second `options` argument to `setProgressBar` method to set mode (`none/progress/paused/errored/indeterminate`) and deprecated setting mode via progress value ranges.

**Comment by felixrieseberg** [comment]
I can take this one.
