### ISSUE TITLE
error occured , when start the opencv-nodejs in electron

### ISSUE THREAD

**Issue by illfar** [electron/electron#6673]
* Electron version:0.37.8
* Operating system:win7

I am developping the web(JS,html5) electron app, want to use the opencv library.
so I have installed the following opencv js library to my electron [node_modules], but
add [const cv = require('opencv');]  to index.js and start the electron app , the following error occured.
【node-opencv】
 https://github.com/peterbraden/node-opencv

【error】
 Cannot find module
 'C:.....\node_modules\opencv\build\opencv\v5.0.0\Release\node-v47-win32-ia32\opencv.node'

**Comment by vsemozhetbyt** [comment]
@illfar How did you install the library? Did you run `npm install opencv`? It seems some modules have to be compilled during installation.

**Comment by MarshallOfSound** [comment]
`node-opencv` uses pregyp

Electron needs native dependencies to be built using it's own headers.  See here for information

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#modules-that-rely-on-node-pre-gyp
