### ISSUE TITLE
Add API to set default size for links with `target` attribute

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#6680]
* Electron version: All
* Operating system: All

Add API to set default size for new windows such as `new BrowserWindow`, `window.open`, links (`<a target="_blank"...>`)

**Comment by zcbenz** [comment]
You can use the `new-window` event to create arbitrary window.

**Comment by cuixiping** [comment]
But it's hard to detect that which way the window is opened by  in new-window event .
