### ISSUE TITLE
Issue#6050 still not fixed as claimed in issue 6218

### ISSUE THREAD

**Issue by mgparrish** [electron/electron#6681]
* Electron version: 1.0.0 +
* Operating system: Windows 10 Windows 7 

https://github.com/electron/electron/pull/6218
was supposed to fix the issue 6050, however it didn't. The same thing is still happening.
https://github.com/electron/electron/issues/6050

I checked my issue (6050) using version v 1.2.8, it still has the bug. 
The callback is never performed using the code I posted in 6050. 
I hadn't checked in V 1.2.6 but presume it wasn't working there either.

**Comment by zcbenz** [comment]
I tested by extracting the app from http://www.mgparrish.com/FabricSaveCanvasBug.zip and running it with Electron 1.3.1, and it works fine.

**Comment by mgparrish** [comment]
Works 100% in 1.3.1 !!!

I didn't check 1.3.0 but wasn't working correctly from 1.2.8 and lower.  Thanks.

**Comment by mgparrish** [comment]
Works 100% in 1.3.1 thank you! 

    On Monday, August 1, 2016 5:45 PM, Cheng Zhao <notifications@github.com> wrote:
 

 I tested by extracting the app from http://www.mgparrish.com/FabricSaveCanvasBug.zip and running it with Electron 1.3.1, and it works fine. —
