### ISSUE TITLE
Question: Which codecs are supported by electron ffempeg?

### ISSUE THREAD

**Issue by amilajack** [electron/electron#6682]
Which proprietary  codecs are supported by the electron downloads with the ffmpeg prefix?

**Comment by MarshallOfSound** [comment]
See this comment

https://github.com/electron/libchromiumcontent/issues/174#issuecomment-175297780

That information might be out of date but I don't see how much could have changed 👍

**Comment by MarshallOfSound** [comment]
Please use the discussion forums or Slack for questions as the github issues area is for bugs and issues with Electron itself
