### ISSUE TITLE
Blank screen in v1.3.0+

### ISSUE THREAD

**Issue by flytreeleft** [electron/electron#6689]
* Electron version: v1.3.0, v1.3.1
* Operating system: Arch Linux (kernel 4.4.15-2-lts)

I have tried v1.3.0 and v1.3.1, when I was running `electron .` or `electron . --disable-gpu`, I will get the following window:

![Blank Screen](https://cloud.githubusercontent.com/assets/1321315/17329779/ae08b426-58f6-11e6-9374-163f19f4013b.png)

Then I switch to v1.2.8, it looks like normal:

![Normal Screen](https://cloud.githubusercontent.com/assets/1321315/17329840/fde83070-58f6-11e6-9b94-9a7eb229dbdb.png)

I have no idea what's the problem :(

**Comment by zcbenz** [comment]
It seems that font rendering is broken, how does Chrome browser 52 work on your machine?

**Comment by flytreeleft** [comment]
I installed google-chrome v52.0.2743.91, unfortunately it's blank too :(

![Blank Chrome](https://cloud.githubusercontent.com/assets/1321315/17366310/161ed20e-59bd-11e6-900c-169698f9258c.jpg)

**Comment by flytreeleft** [comment]
@zcbenz You are right, it's font rendering problem: No suitable default fonts are specified.

I created a new file `/etc/fonts/local.conf`, and add the following configuration:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
<match>
    <test name="family"><string>sans-serif</string></test>
    <edit name="family" mode="prepend" binding="strong">
        <string>DejaVu Sans</string>
        <string>Microsoft Yahei</string>
    </edit>
</match>
<match>
    <test name="family"><string>serif</string></test>
    <edit name="family" mode="prepend" binding="strong">
        <string>Microsoft Yahei</string>
        <string>DejaVu Serif</string>
    </edit>
</match>
<match>
    <test name="family"><string>monospace</string></test>
    <edit name="family" mode="prepend" binding="strong">
        <string>YaHei Consolas Hybrid</string>
        <string>DejaVu Sans Mono</string>
    </edit>
</match>
</fontconfig>
```
The google chrome v52 or electron v1.3.1 comes back to be quite well :)

![gtkshot](https://cloud.githubusercontent.com/assets/1321315/17370181/ae55dcf6-59cd-11e6-8bde-ddbda49e3da4.png)
