### ISSUE TITLE
Windows 10 tablet pop-up keyboard does not invoke on input field focus reliably

### ISSUE THREAD

**Issue by qbunt** [electron/electron#6692]
* Electron version: 1.2.8 - 1.3.1
* Operating system: Windows 10

On Windows 10 based tablets, with the tablet in 'tablet mode' (I know, I know), when we focus on an input field, typically, the pop-up keyboard raises and you can enter text. It appears that when going between multiple fields in a form for instance, that keyboard dismisses and then intermittently appears but prevents you from finishing the form.

This appears to be related to an [upstream Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=497381) which has not yet been deployed into the stable channel. Because of the age of this issue, it doesn't seem to be a huge issue for most but definitely effects our use-case.

I wouldn't necessarily post an upstream issue, but because it does block input on essentially an entire series of devices (albeit small in number), I wanted to make sure the Electron team was aware of this, as running hardware keyboards for a tablet is not always possible.

**Comment by zcbenz** [comment]
According to the upstream Chromium issue this problem has not been completely fixed, and we are not able to fix it on Electron's side.

I think in Electron we can work around it by adding a way to force showing/hiding the popup keyboard, and I'm merging this to #6430.
