### ISSUE TITLE
Cannot load native node modules from app.asar.unpacked on windows 7

### ISSUE THREAD

**Issue by kneumei** [electron/electron#6698]
* Electron version: 1.1.1 and up
* Operating system: windows 7

I've run into a problem where electron cannot find native node modules (or at least edge-atom-shell) when the native node module is packaged in the app.asar.unpacked directory and run in windows 7. 

I've put together a sample app to demonstrate the problem here: https://github.com/kneumei/electron-quick-start.

The error message says: "The specified module could not be loaded". Some additional information:

1. The error does not happen in windows 10
2. The error seems to have started with electron 1.1.1. I tried running the sample app to reproduce on 1.1.0, but there seems to be another problem with that release that prevents the app from running at all. The error does not appear with 1.0.2

Here is a screenshot of the error

![error](https://cloud.githubusercontent.com/assets/1694376/17348269/d8718ccc-58da-11e6-91df-b14963ca8a97.JPG)

**Comment by zcbenz** [comment]
Do other native modules work? For example `runas`.

And from your screenshot it doesn't work because the path is invalid, it starts with `\\?\C:\\` which is not a valid path.

**Comment by enlight** [comment]
@zcbenz That looks like a valid [UNC path](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#win32_file_namespaces) to me. I believe Node can handle those, but I have no idea if Chromium can.

**Comment by kneumei** [comment]
Ok, after some more testing, I have only been able to reproduce with `edge-atom-shell`. Both `runas` and `win-mouse` loaded fine. 

The UNC path does not seem to be an issue...I tested with older version of electron on windows 7 (where edge-atom-shell works), manually modified the name of the .node file in the app.asar.unpacked directory, and have seen the same error: `Specified module could not be loaded \\?\C:\\...`. So this would seem to indicate the path works fine when I had not modified the file name.

Any other troubleshooting suggestions?

**Comment by zcbenz** [comment]
Please file a bug at the `edge-atom-shell` module's repo, since other native modules are working this must be caused by some special things of this module, and the maintainers there would have a much better idea on how to solve this.

**Comment by kneumei** [comment]
Solved the issue

Including msvcp120.dll, msvcr120.dll, and vccorlib120.dll in the /edge-atom-shell/build/Release folder fixed this problem. I noticed that these dlls exist in that directory for the slack app. I guess the node module needs these dlls, and since they were removed as part of https://github.com/electron/electron/pull/5602, and were not explictily installed on the windows 7 machine, that was the source of the error
