### ISSUE TITLE
How to install a native node module[opencv_nodejs] (#6673 continue)

### ISSUE THREAD

**Issue by illfar** [electron/electron#6701]
* Electron version:0.37.8
* Operating system:WIN7

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#modules-that-rely-on-node-pre-gyp

Q1:[Using npm]
# Install all dependencies, and store cache to ~/.electron-gyp.
HOME=~/.electron-gyp npm install
the [HOME=~/.electron-gyp] is not exist in my PC.
how to install it?

Q2:[Installing modules and rebuilding for Electron]
Is this command [.\node_modules\.bin\electron-rebuild.cmd] 's parameter null?
or .\node_modules\.bin\electron-rebuild.cmd opencv

Q3:  I add the[ "opencv": "5.0.0"]  In my electron project's package.json [ "dependencies"]
but after [npm install ], node_modules/electron_prebuild/path.txt and dist folder is not created.
I want to know the reason.

**Comment by zcbenz** [comment]
Please seek help from [the community](https://github.com/electron/electron#community) for questions, the issues list is only for bug reports and feature requests.
