### ISSUE TITLE
Will quit doesn't prevent closing of window

### ISSUE THREAD

**Issue by arunjoseph** [electron/electron#6702]
I am trying to create an app with electron desktop app I wanted to prevent the closing of the window i.e I have two requirement

1. The window should be frameless
2. The user should not be able to use the keyboard shortcut Alt+F4 to quit the window

This is test engine client so once the student finished the exam I can take care of the closing after the marks are submitted. I tried to use the following snippet

`app.on 'will-quit', (event) ->
  event.preventDefault()`

But it still quits the window on pressing Alt+F4 then another which I tried is `BrowerWindow.on('close')` but on using that I am not able to close the window at all.

Also I need a suggestion on how can I share variable across the index.html and and app.js? I would be using react and redux in for the index.html

* Electron version: 1.3.1
* Operating system: Ubuntu 16.04 LTS

**Comment by MarshallOfSound** [comment]
You should really ask these question on the Discussion forum or in Slack.

But have some untested code 😆 The TLDR is use IPC

```js
// app.js
import { ipcMain } from 'electron';

let canQuit = false;
ipcMain.on('test-over', () => {
  canQuit = true;
});

mainWindow.on('close', (event) => {
  if (!canQuit) event.preventDefault();
});

// index.html
// When the test is over
import { ipcRenderer } from 'electron';
ipcRenderer.send('test-over');
```

**Comment by MarshallOfSound** [comment]
Oops, missed the bit about `app.on 'will-quit', (event) -> event.preventDefault()` not working.

Can you provide a minimal app that reproduces the issue?

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by DarrenCook** [comment]
I have the same issue, so can provide a little more information. I have added this handler:

```
app.on('before-quit', (ev)=>{
   const hasUnsavedChanges = true; //Get from somewhere
   if(hasUnsavedChanges){
     //I actually show a dialog asking if they should quite
     ev.preventDefault();
     }
  });
```

If I use File|Quit menu option this works fine. But if I press Alt-F4 what happens is:

* The dialog still pops up, and I press cancel
* The main window has disappeared
* The app is still running.

I.e. Alt-F4 must be closing the main window process, and not paying attention to the before-quit event.

**Comment by DarrenCook** [comment]
In the browser window js, I tried this:

```
window.onbeforeunload = function(){
return false;
};
```

This stops alt-f4 working completely (i.e. the app never shuts, I don't get the "ok to close?" dialog any more). If I use File|Quit I get the dialog, but saying I want to quit gets ignored.

**Comment by ThibaultJanBeyer** [comment]
Here is how you can prevent the closing:

after lots of tryals I came up with a solution:

```javascript
// Prevent Closing when work is running
window.onbeforeunload = (e) => {
  var answer = confirm('Do you really want to close the application?');
  e.returnValue = answer;  // this will *prevent* the closing no matter what value is passed
  if(answer) { win.destroy(); }  // this will close the app
};
```

Found in [docs](https://electron.atom.io/docs/api/browser-window/#event-close)
