### ISSUE TITLE
Allow electron renderers to be run inside chromium sandbox

### ISSUE THREAD

**Issue by tarruda** [electron/electron#6712]
Progress on supporting sandbox in electron started in #6919, but the remaining work will be done by future PRs. This issue will be used to track progress on all relevant tasks.
- [x] Add `sandbox` option to `webPreferences` of `BrowserWindow`. (#6919)
- [x] Support chromium native `window.open` API in sandboxed renderers. (#6919)
- [x] Extract code that is not specific to node.js from `AtomRendererClient` into a base class that is also shared by `AtomSandboxedRendererClient`.
- [x] Patch libchromiumcontent to allow reuse of code that determines which navigations should spawn a new renderer. More details [here](https://github.com/electron/electron/pull/6919#issuecomment-243364062)
- [x] Add `sandbox` option to `<webview>` tag.
- [x] Expose node.js builtin modules via IPC to sandboxed renderers.
- [x] Reuse most javascript code under `lib/renderer/` and `lib/common`. The goal is to support the full electron API in sandboxed renderers.
- [x] Add documentation

**Comment by zcbenz** [comment]
This is needed by a few special projects and as far as I know some organizations are already doing this in their own forks.

But moving Electron's API stack from Node is too ambitious, a more practical way is to provide a very small set of APIs under sandbox to allow communicating with the main process.

**Comment by tarruda** [comment]
> But moving Electron's API stack from Node is too ambitious, a more practical way is to provide a very small set of APIs under sandbox to allow communicating with the main process.

Do you mean by providing an implementation of `ipcRenderer` that doesn't rely on node.js, and enabling this implementation in a new mode that completely disables node.js integration(and enables the sandbox)?

I think this would be a good start, but what would be even better is to completely decouple electron's renderer API from node.js, to make it fully useable not only with nodeIntegration enabled but also in a sandboxed renderer. In other words, nodeIntegration would simply add node.js APIs to the renderer, but it would not be required to access electron's APIs.

In any case, having a simple implementation of `ipcRenderer` without node.js would certainly help me get to what I'm trying to achieve [here](https://github.com/tarruda/electron/commit/e0dd1077cf5c8db109b6c695514118f63d8887f4#commitcomment-18483328).

**Comment by jprichardson** [comment]
@sindresorhus will you elaborate on your thumbs down? I'm curious to know your perspective here.

**Comment by ThomasMoutel** [comment]
Hi @tarruda I'm willing to get the crash-reporter working in sandboxed renderers. Is this something you've already looked into and/or planned to do in the near future?

**Comment by tarruda** [comment]
> It is not working currently, probably by design, no?

Not by design, I simply left this for later(Feel free to take this task)

**Comment by paulcbetts** [comment]
> I think this would be a good start, but what would be even better is to completely decouple electron's renderer API from node.js, to make it fully useable not only with nodeIntegration enabled but also in a sandboxed renderer. In other words, nodeIntegration would simply add node.js APIs to the renderer, but it would not be required to access electron's APIs.

I think that this will create a pretty massive maintenance burden, I'd rather enable simple IPC and leave it at that

**Comment by dregenor** [comment]
need add **access** to **webFrame** in **sandbox_renderer**, or any another way to interact with **webFrame** when used **sandbox_renderer**.

**Comment by pfrazee** [comment]
A +1 to what @dregenor said. We need the webFrame (or similar) in the preload so that we can call `registerURLSchemeAsPrivileged`. (Correct me if I'm wrong, and there's somewhere else the call can be made.)

**Comment by liliakai** [comment]
Also need access `webFrame` from a sandboxed renderer in order to `setSpellCheckProvider`.

**Comment by jack-mo** [comment]
@tarruda Hi, I'm currently working on a project using Electron where we want to render a webpage on a BrowserWindow and I'm trying to figure out which is more secure (prevent remote content from accessing Node or other APIs, plus standard security like the chromium sandbox).

 - Option 1: BrowserWindows with sandbox=true and nodeIntegration=false, loading the remote URL. Nice because it has the sandbox

 - Option 2: <webview> in a normal BrowserWindow loading the remote URL. This seems to be recommended for remote content, but the lack of sandbox isn't ideal.

Which option is more secure?
Many thanks in advance

**Comment by tarruda** [comment]
> Which option is more secure?

electron sandbox is not very secure since the renderer has full system access via IPC(plus no context isolation yet). I can't say which is more secure, but I definitely wouldn't recommend loading untrusted content into electron.

**Comment by ColinEberhardt** [comment]
@jack-mo there's actually a great documentation page about these options available here:

https://electron.atom.io/docs/api/sandbox-option/

(it's a bit buried at the moment, only accessible via a link from the `BrowserWindow` `options` doc).

**Comment by jprichardson** [comment]
> electron sandbox is not very secure since the renderer has full system access via IPC(plus no context isolation yet). I can't say which is more secure, but I definitely wouldn't recommend loading untrusted content into electron.

@tarruda what's the benefit of using `sandbox` as opposed to `nodeIntegration` set at `false`? Is it performance?

**Comment by alexstrat** [comment]
@tarruda I read there https://github.com/brave/muon/issues/165 that you have made some progress on the support of `sandbox` for `webview` (crash reported in https://github.com/electron/electron/issues/8378). Can you share more details on your findings and on the blockers? (worth re-opening https://github.com/electron/electron/issues/8378 to discuss in details?)

**Comment by tarruda** [comment]
> @tarruda I read there brave/muon#165 that you have made some progress on the support of sandbox for webview (crash reported in #8378). Can you share more details on your findings and on the blockers? (worth re-opening #8378 to discuss in details?)

The top 2 commits of this branch enable sandbox for webview as well as `window.open` from webview:
https://github.com/tarruda/electron/tree/enable-webview-on-sandbox

As far as I can see, the main problem with that branch is that it relies on chromium internals(casting ot `WebViewImpl` class), which is why I didn't open a PR yet.

**Comment by oldbam** [comment]
@tarruda According to [documentation](https://github.com/electron/electron/blob/master/docs/api/sandbox-option.md),

> One planned enhancement that should greatly increase security is to block IPC messages from sandboxed renderers by default, allowing the main process to explicitly define a set of messages the renderer is allowed to send.

Is there a dedicated issue I can track to check on the progress of this item?

Thank you!

**Comment by codebytere** [comment]
@tarruda is this still being worked on?

**Comment by tarruda** [comment]
@codebytere Not currently, these tasks still must be done. If required I can close the issue and track them somewhere else.

**Comment by usergit** [comment]
I second @mhuggins the documentation implies that sandboxing is possible for webview

**Comment by miniak** [comment]
@tarruda I ran into this issue and I am not sure if it's meant to be like that or not https://github.com/electron/electron/issues/13073

**Comment by dtaipov** [comment]
@mhuggins @usergit , `sandbox` option for webview, but without `window.open` support was implemented here: 
https://github.com/electron/electron/pull/9644
Please, correct me anybody if I’m wrong

**Comment by miniak** [comment]
I believe all this work has already been done. Feel free to create follow-up issues in case there is something missing.
