### ISSUE TITLE
App hanging on close if dialog.showOpenDialog() is used

### ISSUE THREAD

**Issue by sdussaut** [electron/electron#6717]
* Electron version: 1.3.2
* Operating system: OSX 10.11.6

It seems that as soon as we open an open dialog on OSX with `dialog.showOpenDialog()`, on quitting the app will hang for half a minute or so (if it even closes…).

I replicated this behaviour in the Electron Quick start app here (https://github.com/electron/electron-quick-start) by adding `electron.dialog.showOpenDialog({});` after the window creation. If I quit (with cmd+q or the menu item), the app is hanging for a long time.

Any ideas on what could be happening here?

**Comment by TimNZ** [comment]
Yup some new behaviour introduced with 1.3.2 (OS X at least)

In my case I launch my app via command line and Ctrl-C to kill it always resulted in killing Electron process tree.   

Now BrowserWindow stays open and dev tools becomes 'Disconnected'.  Have to kill the process(es) via Activity Monitor

**Comment by kevinsawicki** [comment]
> I replicated this behaviour in the Electron Quick start app here (https://github.com/electron/electron-quick-start) by adding electron.dialog.showOpenDialog({}); after the window creation. If I quit (with cmd+q or the menu item), the app is hanging for a long time.

Having a little trouble reproducing this, I added `electron.dialog.showOpenDialog({})` at the end of the `createWindow` function but I'm not seeing the hang.

- Does it happen every time for you?
- Are you canceling the dialog or selecting a file?

**Comment by sdussaut** [comment]
Hum. I tested again with my app and the quickstart app and it seems to have disappeared. That is really weird. Maybe my computer was going haywire :-/
Anyway sorry for the false alarm, I'll keep watching it in case it would reappear.

**Comment by kevinsawicki** [comment]
> Anyway sorry for the false alarm, I'll keep watching it in case it would reappear.

Okay, thanks for the updates, closing this out, please comment back if you start seeing it again.
