### ISSUE TITLE
Electron crashes under WSL (Bash on Windows)

### ISSUE THREAD

**Issue by kurisubrooks** [electron/electron#6722]
* Electron version: v1.3.2
* Operating system: Linux running Unity under VcXsrv (X Server)

Now, **I understand that WSL is not a supported platform**, but I thought **the bug might be relevant** on some particular Linux Distros that don't meet all package requirements. I'd be happy to provide you with any information if you'd like to setup an environment for testing this.

The given error is:
```
[15826:0804/155819:FATAL:render_sandbox_host_linux.cc(40)]
    Check failed: 0 == shutdown(renderer_socket_, SHUT_RD). shutdown: Invalid argument

#0 0x000001e038ee <unknown>
#1 0x000001e194fb <unknown>
#2 0x000001e19abd <unknown>
#3 0x00000288cfc2 <unknown>
#4 0x000002658599 <unknown>
#5 0x00000265eb5f <unknown>
#6 0x000002657c36 <unknown>
#7 0x0000011fe197 <unknown>
#8 0x0000011fcc70 <unknown>
#9 0x0000033a3350 main
#10 0x7ff453701f45 __libc_start_main
#11 0x00000056f089 <unknown>
```

Screenshot:

![image](https://cloud.githubusercontent.com/assets/6291467/17391827/9efcfa8e-5a5c-11e6-9d31-3abe2d8ae066.png)

~~inb4 "closed due to lol"~~

**Comment by zcbenz** [comment]
> [15826:0804/155819:FATAL:render_sandbox_host_linux.cc(40)]
>     Check failed: 0 == shutdown(renderer_socket_, SHUT_RD). shutdown: Invalid argument

WSL doesn't fully implement the `shutdown` system call, and it triggered an assertion in Chromium. I suggest reporting this to Microsoft instead.

**Comment by kurisubrooks** [comment]
Thanks for your comment, i've created an issue with Microsoft.

**Comment by justinmchase** [comment]
Any update on this @kurisubrooks?

I'm attempting to use nightmarejs through bash on windows and it appears to just hang. This would be very useful from a xplat perspective.

**Comment by kurisubrooks** [comment]
Haven't had the chance to check this lately. Windows 10 Fall Creators Update released today, perhaps they've fixed some bugs under WSL?

**Comment by justinmchase** [comment]
Maybe, it wasn't crashing for me but it was hanging. I definitely could be doing it wrong though. Found this while searching and was just trying to see if anyone has found the magic combination yet.

**Comment by DarthSpock** [comment]
Specific bug that prevents this from working natively has been known for quite some time in this comment in [WSL/2293](https://github.com/Microsoft/WSL/issues/2293#issuecomment-346986316) Is it possible investigate this and provide a reasonably quick solution?

**Comment by abalter** [comment]
I'm having the same problem: #13566
