### ISSUE TITLE
Soft keyboard places itself on top of the focused input on Windows 10 tablet.

### ISSUE THREAD

**Issue by strille** [electron/electron#6724]
When an input field is tapped in the lower half of our app, Windows shows the soft keyboard on top of the input, preventing you to see what you type. This actually happens in the Chrome browser on the same device as well, so it's Chromium related.

Is there any way to at least detect if the soft keyboard is showing on the screen? A show/hide event would be enough, but even better if the keyboard's bounding rectangle was available in order to know where the keyboard is on the screen.

* Electron version: 1.3.2
* Operating system: Windows 10

**Comment by zcbenz** [comment]
I suggest reporting this to Chromium instead, Electron is just using Chromium's code and we are not able to fix it on our side. For adding soft keyboard related APIs, it is tracked at #6430.
