### ISSUE TITLE
Load Header/Footer

### ISSUE THREAD

**Issue by mathishuettl** [electron/electron#6728]
Hello,

first im completly new to electron but already love it!
But i just wonder how to handle a application with different pages.
I couldn't write a single .html file for each page because when something in the header changes i have to do the change in every single .html file.

Which solutions to you prefer and do you have code-snippets?

**Comment by MarshallOfSound** [comment]
@mathishuettl Please ask questions in the discussion forum or Slack.

This question is very JS generic and solutions such as React and Angular or even server side templating through Pug or a similar tool will do what you need.

**Comment by baconface** [comment]
Most Electron applications use a [SPA model](https://en.wikipedia.org/wiki/Single-page_application) opposed to loading page by page like a traditional website.
