### ISSUE TITLE
"Ctrl+Plus" accelerator ends up as "Shift+Ctrl+="

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#6731]
- Electron version: 1.3.2
- Operating system: Ubuntu 14.04 -> 16.04. Windows 10

`Ctrl+Plus` or `CmdOrCtrl+Plus` always ends up as `Shift+Ctrl+=` on linux and windows. `Cmd+Plus` does work correctly on osx.

Also related #2458 and #1507

**Comment by yuya-oc** [comment]
FYI, when using JP 106/109 keyboard layout, `Ctrl+Plus` ends up as `Shift+Ctrl+;`. In the layout, `+` is located as `Shift+;`, so it seems to depend on the way to input `+` with keyboard.

- Electron: 1.4.0
- Operation system: Windows 10

**Comment by zcbenz** [comment]
Some thinkings on this issue:

1. How should the `Plus` show, as `Ctrl+Plus` or `Ctrl++`? The former needs localization since it is an English word while the key on keyboard shows as `+`, the latter does not even look like a valid key shortcut (does it mean pressing `Ctrl` twice? or is there something not showing between the `+`s?).

2. How should `Ctrl+Shift+=` show, should it be converted to `Ctrl+Plus`?

3. What about other keys like `Ctrl+Shift+1`, should they be converted to things like `Ctrl+!`?

**Comment by MarshallOfSound** [comment]
@zcbenz I think that any letter / number should display the "Shift" modifier and not the resultant char.  Everything else should just be the resultant char.

I.e.

`Ctrl+Shit+A` is good
`Ctrl+Shift+3` is good
`Ctrl+Shift+#` is bad
`Ctrl+_` is good
`Ctrl+Plus` is good
`Ctrl+Shift+=` is bad

Thoughts?

**Comment by yuya-oc** [comment]
I agree to @MarshallOfSound's examples other than `Ctrl+Plus`. For now, I have never seen `Ctrl+Shift+;` in menu items of other apps.

About `Ctrl+Plus`, Chrome doesn't have traditional menu bar though, other browsers show `Ctrl+Plus` as `Ctrl++`.

IE 11
<img width="358" alt="ie11-zoom" src="https://user-images.githubusercontent.com/1412057/34677282-f47a1750-f4d2-11e7-8d5d-c5a229e0d43d.png">

Firefox 57
<img width="365" alt="firefox-zoom" src="https://user-images.githubusercontent.com/1412057/34677498-b19ba16e-f4d3-11e7-8633-0ce7796632ed.png">

---

I just have an idea though, can we set desired shortcut label to menu items?

**Comment by akashnimare** [comment]
I can reproduce this on v1.7.10 as well.

**Comment by vinicentus** [comment]
+1 brave/browser-laptop#13099

**Comment by Thomas101** [comment]
Looks like it's fixed with 3...

```js
Menu.setApplicationMenu(Menu.buildFromTemplate([
    {
      label: 'Edit',
       submenu: [
        {
          label: 'Test',
          accelerator: 'CmdOrCtrl+Plus',
          click: () => {
            console.log('Test')
          }
        }
      ]
    }
  ]))
```

Comes out as `Ctrl++` which looks more like the correct behaviour
![untitled](https://user-images.githubusercontent.com/103586/45941875-0c007d80-bfd8-11e8-8a07-99166984eb53.png)

**Comment by yougotwill** [comment]
Hi @Thomas101, I'm on OSX and using electron 3.0.3. If I use the `CommandOrCtrl+Plus` accelerator it no longer works I have to press `Command+Shift` + `+` instead to trigger the event.

My current solution is using `CommandOrControl+=` which works fine. Not sure if I should make a new issue but I thought I would leave a comment here first.

**Comment by irelandlife** [comment]
> * Electron version: 1.3.2
> * Operating system: Ubuntu 14.04 -> 16.04. Windows 10
> 
> `Ctrl+Plus` or `CmdOrCtrl+Plus` always ends up as `Shift+Ctrl+=` on linux and windows. `Cmd+Plus` does work correctly on osx.
> 
> Also related #2458 and #1507

{
        label: "Zoom In",
        accelerator: "CmdOrCtrl++",
        selector: "zoomIn:"
      },
      {
        label: "Zoom Out",
        accelerator: "CmdOrCtrl+-",
        selector: "zoomOut:"
      }

This worked the best for mac

**Comment by jlindberg-oss** [comment]
@yougotwill thanks for the solution.

@MarshallOfSound this is definitely still a bug.  I am on electron 4.0.6 on OSX.
When I have `accelerator: 'CmdOrCtrl+='`, the menu shows `⌘+` and yet it does not work.
When I have `accelerator: 'CmdOrCtrl+='`, the menu shows `⌘=`, and yet typing `⌘+` works.

So something is backwards somewhere.

**Comment by loveencounterflow** [comment]
also see https://github.com/electron/electron/issues/1507 to the same effect.

**Comment by CherryDT** [comment]
The issue still exists - my keyboard is German (and the Electron app is designed for the German market) and we have a key whose primary function is `+`, yet `CmdOrCtrl+Plus` gets displayed as `Strg + Umschalttaste + =` and does not work.

**Comment by mxsrm** [comment]
Can confirm this bug on Mac 12.1!
