### ISSUE TITLE
Remote array mutation not working in render process

### ISSUE THREAD

**Issue by swashcap** [electron/electron#6734]
* Electron version: 1.3.1
* Operating system: OS X 10.11.6

Mutating a remote-retrieved array doesn’t seem to work. Here’s a boiled-down example:

```js
// Main process
module.exports = function getFromRemote() {
  return Promise.resolve({
    myArray: [],
  });
};
```

Using `Array#push` doesn’t actually mutate the array:

```js
// Render process
const { remote } = require('electron');
const getFromRemote = remote.require('get-from-remote.js');

getFromRemote().then(myObject => {
  myObject.myArray.push('my-item');
  // `myObject.myArray` doesn’t contain 'my-item'
});
```

Reassigning does work:

```js
getFromRemote().then(myObject => {
  myObject.myArray = myObject.myArray.concat('my-item');
  // `myObject.myArray` contains 'my-item'
});
``` 

Any thoughts? This doesn’t seem like planned behavior based on the [`remote` documentation](http://electron.atom.io/docs/api/remote/).

**Comment by zcbenz** [comment]
This behavior is intentional because making remote Array received by IPC would cause serious performance problems, iterating an remote 10-elements array may result in sending 20+ IPC messages.

I think we should make this clear in docs.
