### ISSUE TITLE
Expose title bar double-click preference

### ISSUE THREAD

**Issue by Zirro** [electron/electron#6735]
The Dock section in System Preferences has a preference allowing the user to choose whether windows should minimize, zoom or do nothing at all upon having their title bars double-clicked.
![Dock preferences](https://i.stack.imgur.com/zPdAN.png)
(from [https://apple.stackexchange.com/questions/110321/double-clicking-a-window-s-title-bar-to-minimize-it-in-mavericks](https://apple.stackexchange.com/questions/110321/double-clicking-a-window-s-title-bar-to-minimize-it-in-mavericks))

It would be useful for applications implementing custom title bars to find out what value this preference is set to, in order to perform the correct action on double-click.

**Comment by kevinsawicki** [comment]
I believe you can use the [`systemPreferences`](http://electron.atom.io/docs/api/system-preferences/) API for this already:

```js
require("electron").remote.systemPreferences.getUserDefault("AppleActionOnDoubleClick", "string")
```

Closing this out.
