### ISSUE TITLE
Add menubar option to BrowserWindow constructor

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#6740]
If we want to create a window without menu bar, now we must use **`win.setMenu(null)`** to hide the menu bar after the window is created.

Why not add **`menubar`** option to the `BrowserWindow` constructor ? 

`new BrowserWindow({ menubar: false });`

**Comment by zcbenz** [comment]
The default menu bar is only added when you run the app by passing it to the default app (e.g. running via command line `electron your-app`), it will be gone after you packaged your app.
