### ISSUE TITLE
Electron not support async/await? 

### ISSUE THREAD

**Issue by acterhd** [electron/electron#6747]
Hello. I tried to use "async" and "await", but not working. Not helping any flags. 
```
call electron index.html --enable-javascript-harmony
pause 
```

**Comment by kevinsawicki** [comment]
async/await has not been implemented in v8 yet which Electron  (via Chromium and Node) uses under the hood.

See https://bugs.chromium.org/p/v8/issues/detail?id=4483 for more details.

In the meantime, you need to use a transpiler like http://babeljs.io/ until it is implemented in v8.

**Comment by black-snow** [comment]
async/await has now landed in v8 (https://v8project.blogspot.de/2016/10/v8-release-55.html)

**Comment by arg20** [comment]
@kevinsawicki node v7.6 now uses v8 v5.5, is there any change required in electron before we can use it?

**Comment by kevinsawicki** [comment]
>  node v7.6 now uses v8 v5.5, is there any change required in electron before we can use it?

Electron 1.6.x includes v8 v5.6 so native async/await is now supported.

**Comment by black-snow** [comment]
Awesome!

**Comment by JasinYip** [comment]
I found that the `1.7.0` release has upgraded the version of Node.js to `7.9`, that means we can use native async/await now!
