### ISSUE TITLE
Protocol handler and webRequest should support form data

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#6749]
Currently uploadData is supported but common form data is not.
Form data is very useful to handle POST request.
We need **`formData`** just like **`uploadData`**.

```
//page js
$.post('app://my/', {field1:'value'});

//protocol handler
request.formData['field1'];  //"value"

//webRequest
webRequest.onBeforeRequest(filter, (details, callback) => {
  details.formData['field1'];  //"value"
})
```

**Comment by deepak1556** [comment]
`uploadData` will contain form data, the problem here is usage of `xhr` which explicitly only constructs post data for http(s) scheme in [blink](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/xmlhttprequest/XMLHttpRequest.cpp?l=681). Instead you can use fetch api and things should work fine.

@zcbenz should we add CORS enabling WebSecurityPolicy to `WebFrame::RegisterURLSchemeAsPrivileged` ?

**Comment by cuixiping** [comment]
fetch api only receive "https" and "http" scheme. 

If fetch a custom scheme url, one of the 2 errors will occur: 

- URL scheme "app" is not supported.
- URL scheme must be "http" or "https" for CORS request.

**Comment by deepak1556** [comment]
Use [webFrame.registerURLSchemeAsPrivileged](https://github.com/electron/electron/blob/master/docs/api/web-frame.md#webframeregisterurlschemeasprivilegedscheme) for fetch api to support the scheme. Although if you are trying to send CORS request it will error at the moment.

**Comment by cuixiping** [comment]
Thanks @deepak1556 .  fetch works after using  [webFrame.registerURLSchemeAsPrivileged](http://electron.atom.io/docs/api/web-frame/)

**Comment by zcbenz** [comment]
Closing since this question has been solved.

> @zcbenz should we add CORS enabling WebSecurityPolicy to WebFrame::RegisterURLSchemeAsPrivileged ?

I think it is already calling `registerURLSchemeAsBypassingContentSecurityPolicy`?

**Comment by deepak1556** [comment]
Blink denies cross origin requests for schemes that are not registered as CORS enabled [here](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/loader/DocumentThreadableLoader.cpp?l=277-281). The following,

```
// window.location.href = 'test://host'.
<script>
  require('electron').webFrame.registerURLSchemeAsPrivileged('app')
  fetch('app://myhost/get')
</script>
```

will give the following error:

```
Fetch API cannot load app://myhost/get. Cross origin requests are only supported for protocol schemes: http, data, chrome, https.
```

adding the WebSecurityPolicy `registerURLSchemeAsCORSEnabled` should fix this.

**Comment by zcbenz** [comment]
Didn't know that, I'm 👍 on calling `registerURLSchemeAsCORSEnabled`.
