### ISSUE TITLE
Asynchronous callback for protocol handler does not work

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#6756]
* Electron version: 1.3.1
* Operating system: Windows 10

Asynchronous callback for protocol handler does not work

Example code:

```
protocol.registerStringProtocol('app',
	(request, callback) => {
		setTimeout( ( ) => {callback('hello');} , 1000);  //does not work
	}
);
```

Request "app://x/" will not get response correctly.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by cuixiping** [comment]
Sorry I made a mistake. The callback works well. Please close this topic.
