### ISSUE TITLE
`require`  in script tags fails to find modules when run on virtual machines

### ISSUE THREAD

**Issue by zoubin** [electron/electron#6760]
* Electron version: 1.3.2
* Operating system: MacOS

I'm running [electron-quick-start] on my virtual machine (windows7) with `npm install && npm start` and get the error:
```
Cannot find module './renderer.js'
```

The error arises from the script tag in `index.html`:
```html
  <script>
    // You can also require other files to run in this process
    require('./renderer.js')
  </script>
```

After doing some tests I found that `__dirname` and `__filename` are not absolute paths when used in a script tag:
```
Shared Folders\projects\electron-quick-start
Shared Folders\projects\electron-quick-start\index.html
```
However, `path.resolve()` returns quite different absolute paths:
```
Z:\projects\electron-quick-start
Z:\projects\electron-quick-start\renderer.js
```

And the following code runs properly:
```html
  <script>
    var path = require('path')
    // You can also require other files to run in this process
    require(path.resolve('renderer.js'))
  </script>
```

So, `path.resolve(__dirname, 'renderer.js')` will return something like:
```
Z:\projects\electron-quick-start\Shared Folders\projects\electron-quick-start\renderer.js
```

I guess `require` fails to locate `renderer.js` because it looks up the module in the directory `path.dirname(parent.filename)`, which would be:
```
Z:\projects\electron-quick-start\Shared Folders\projects\electron-quick-start
```

Is there anything we can do to make `require` works in the script tag the way it does in the main process on virtual machines?

 [electron-quick-start]: https://github.com/electron/electron-quick-start

**Comment by MarshallOfSound** [comment]
I have no idea how you cloned that repository but on a **clean** Windows 10 Virtual Machine I do not get that error.  Are you sure you haven't changed any files and your VM hasn't been "damaged" somehow 😕 

Also my `__dirname` in a script tag is identical to that running in the console.

Can you provide specific reproduction steps for a clean download of a Windows 10 testing VM found here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

I am using the `Microsoft Edge on Windows 10 Stable` VM

**Comment by zoubin** [comment]
@MarshallOfSound  Thanks for your response!

I haven't changed any files in the repository. But I'm using VMWare with a normal windows7 version (not specific for VMWare). I'll get one from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and see if the error still exist.

**Comment by zoubin** [comment]
>Also my __dirname in a script tag is identical to that running in the console.

The `__dirname` in my `index.html` is
```
Shared Folders\projects\electron-quick-start
```
However, the `__dirname` in `renderer.js` is
```
\\vmware-host\Shared Folders\projects\electron-quick-start
```

After making `require('./renderer.js')` work right, `require` in `renderer.js` works as expected.
The main difference between the two `__dirname` is that the one in `index.html` is a relative path, yet the other is an absolute path.

I gave up downloading a new version from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ after failing several times due to network problems. :(

Now I'll just use the [following script](https://gist.github.com/zoubin/95f9605a7fd61c863de0a1570eaea8a6) in the `head` of the page to make things work:

```js
/**
 * convert `Shared Folders\projects\electron-quick-start`
 * to `Z:\projects\electron-quick-start`
 * See https://github.com/electron/electron/issues/6760
 *
 * Copy the source code to your page
 * or add a script tag with src refering to this module
 * **BEFORE** any module `require` takes place.
 *
 * Now you can `require` modules in HTML script tags as you do in node.
 *
 */

;(function hackModuleInHtmlForVirtualMachines () {
  const path = require('path')

  // All modules except the main module should return
  if (!module.filename || path.isAbsolute(module.filename)) return

  // Only the main module should go here

  // The root of a normal path: '' or 'Z:'
  const root = process.cwd().split(path.sep).shift()
  // Virtual machines may have 'Shared Folders' as the root
  const VMRoot = __dirname.split(path.sep).shift()

  // correct the `__dirname` and `__filename` variable provided to the page
  __dirname = root + __dirname.slice(VMRoot.length)
  __filename = root + __filename.slice(VMRoot.length)

  // Node will use the `filename` and `paths` to locate child modules
  module.filename = __filename
  if (module.paths) {
    const VMPrefixLen = path.resolve(VMRoot).length
    module.paths.forEach((p, i) => {
      module.paths[i] = root + p.slice(VMPrefixLen)
    })
  }
})()
``` 

Since you don't have this error on your virtual machine, probably it is not due to electron.
So I'm closing this issue.
Anyway, thanks for your help @MarshallOfSound
