### ISSUE TITLE
app.makeSingleInstance always true after app being signed for MAS distribution

### ISSUE THREAD

**Issue by tyv** [electron/electron#6771]
* Electron version: 0.37.x—1.2.5
* Operating system: OSX

the initial discussion: https://github.com/electron/electron/issues/3871#issuecomment-237868493

code example from here http://electron.atom.io/docs/all/#appmakesingleinstancecallback is always returns `true` the app is signed for MAS distribution and this is the reason why app quits right after launch.

**Comment by zcbenz** [comment]
I'm not sure whether it is possible to make this work under MAS, if not we should at least make it always return false.

**Comment by felixrieseberg** [comment]
My proposal: We make it always return false and document that people should just use [LSMultipleInstancesProhibited](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html). That's not practical together with Squirrel and Electron Updater, but you'll upgrade with the MAS anyway.

@zcbenz: Give me a :+1: and I'll send you a PR!

**Comment by paulcbetts** [comment]
afaik all the Posix implementation does is create a socket, why does the MAS version have so many problems with this?

**Comment by blueoctopus** [comment]
@felixrieseberg it looks like LSMultipleInstancesProhibited doesn't do exactly what we want, though.

From https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-113300

> If true, the app runs in only one user session at a time.

`app.makeSingleInstance` doesn't prevent multiple instances across different users.

**Comment by jwheare** [comment]
If I want to workaround this, what's the best way to detect an app running in a MAS build?

**Comment by jwheare** [comment]
This does the trick:
```
'APP_SANDBOX_CONTAINER_ID' in process.env
```

**Comment by paulcbetts** [comment]
`process.mas` works too afaik

**Comment by jwheare** [comment]
Ah, completely missed that thanks. Note that non MAS apps can be sandboxed too, so both might be useful.

**Comment by eladams** [comment]
@jwheare @paulcbetts can you elaborate your workaround?

**Comment by patricksebastien** [comment]
What is the solution exactly here?
Electron v1.3.8 = still having a whitescreen when signing the app for platform mas.
I don't see the process.env or process.mas?

**Comment by jwheare** [comment]
Here's our workaround:
https://github.com/irccloud/irccloud-desktop/blob/63c1a4253f28160db0f5319b243b77ae8d95a927/app/main.js#L78-L89

`is.sandbox()` is here from the `electron-is` package:
https://github.com/delvedor/electron-is/blob/bb1b42e3f5053fcb412c0cdc46fcd2b2e9444f81/is.js#L64-L67

**Comment by paulcbetts** [comment]
This is fixed in #7566

**Comment by patricksebastien** [comment]
Upgraded to electron -v
v1.4.4

Still have the issue, when signing my app = whitescreen. @jwheare I tried your workaround, but it doesn't work (and I am not sure since #7566).

I don't have any issue with my build when not sandboxing it. How can I debug this?
