### ISSUE TITLE
-webkit-box-reflect is not working on webview

### ISSUE THREAD

**Issue by moeasy** [electron/electron#6772]
* Electron version: v1.3.2
* Operating system: mac os 10.11.6

-webkit-box-reflect is not working on webview.  
However, webview's reflection will appear when I open developer tools and hover the mouse on some elements on the elements panel.
But we should know that this reflection is just a static mode which means it can not be updated with webview repaint.
It's cool if -webkit-box-reflect can be implemented on webview and the reflection can dynamically update when webview repaint!

**Comment by zcbenz** [comment]
Can you try how does the page work in this Chrome app?
https://chrome.google.com/webstore/detail/browser-sample/edggnmnajhcbhlnpjnogkjpghaikidaa

It is using <webview> in Chrome, I want to verify whether it is an upstream problem.

**Comment by moeasy** [comment]
I'm sorry I didn't express clearly. I mean -webkit-box-reflect is not working on webview itself rather than the web contents associated with this webview. Code like this is not working:
```css
webview {
    -webkit-box-reflect: below;
}
```

**Comment by zcbenz** [comment]
I suggest reporting this to Chromium instead, both implementations of `webview` and `webkit-box-reflect` are inside Chromium, and we are not able to solve this on Electron's side.
