### ISSUE TITLE
webview.loadURL keeps reloading

### ISSUE THREAD

**Issue by paulsutherland** [electron/electron#6774]
* Electron version: 1.3.2
* Operating system: macOS Sierra 10:12 Beta

When I listen for the 'dom-ready' event on a webview and then call webview.loadURL() to load a url, the browser loads the page but then keeps refreshing in a loop.

Here is the example code to recreate the issue:
```
 <script>
  onload = () => {
    const webview = document.getElementById('azure-login')
    webview.addEventListener('dom-ready', () => {
      webview.loadURL('https://portal.office.com');
    })
  }
</script>
<webview id="azure-login" src="" style="display:inline-flex; width:100%; height:100%"></webview>
```
How do I stop the page from continually refreshing?

**Comment by MarshallOfSound** [comment]
Let's think about your code for a second.  You are saying

<pre>
Load a thing --> When we have loaded that thing --> Load a thing |
                              ^----------------------------------|
</pre>

You're event listener is always there, assuming you only want it to fire once you simply have to remove your listener when it fires.

```js
  onload = () => {
    const webview = document.getElementById('azure-login')
    const loadPage = () => {
      webview.loadURL('https://portal.office.com');
      webview.removeEventListener('dom-ready', loadPage);
    };
    webview.addEventListener('dom-ready', loadPage)
  }
```

In future please ask questions like this in Slack or on the discussion forum.  The github issues section is for bugs.
