### ISSUE TITLE
dialog freezes remote desktop

### ISSUE THREAD

**Issue by unional** [electron/electron#6779]
* Electron version: 1.3.2
* Operating system: Windows 2012 R2 in remote desktop

I think this is related to https://github.com/electron/electron/issues/1821 but the effect is more serious.

Basically if the application popup a dialog (an error dialog in my case), the remote desktop is freezed.

I have to close the remote desktop session and connect again. After I re-connected, I can click on ok to close the dialog and continue working.

Here is an example dialog:
![image](https://cloud.githubusercontent.com/assets/3254987/17491632/48993b72-5d5d-11e6-8683-e89223018dde.png)

**Comment by zcbenz** [comment]
I suggest reporting this to Microsoft instead, user applications are not aware of whether they are running in a remote session, and there is no way to affect how the remote session should behave.
