### ISSUE TITLE
Non-utf8 encoding of internal client-side JavaScript files?

### ISSUE THREAD

**Issue by MartinMa** [electron/electron#678]
All of my js source files (browser and web) are encoded using utf-8 (without BOM). However, I happen to experience the following issue.

When I use "special characters" in my _web_ JavaScript files, they are somehow converted to another encoding. For example, printing `ä` to the console (DevTools) using `console.log` produces garbage. Right now, I'm getting around this problem by using the escaped versions of all special characters.

See this example program to illustrate the problem:

On browser side after `mainWindow.loadUrl`:

``` JavaScript
mainWindow.openDevTools();

mainWindow.webContents.on('did-finish-load', function () {
  mainWindow.webContents.send('test-data', {msg: 'ä'});
});
```

index.html:

``` html
<html>
<body>
  <script>
    require('ipc').on('test-data', function(test) {
      console.log(test.msg);
      console.log('ä');
    });
  </script>
</body>
</html>
```

**produces this result:**

```
ä
Ã¤
```

So, the `ä` send via ipc from node is encoded correctly, but the `ä` from index.html is garbled. Note that index.html is utf-8 encoded. It actually makes no difference, if I include the js code from a separate file.

**Tested system:** Windows 7
**atom-shell:** v0.17.1

**Comment by kostia** [comment]
I have the same issue with Version 0.33.1 on OSX 10.10.5:

```html
<!-- html.index -->

<!DOCTYPE html>
<html>
  <head><title>Test</title></head>
  <body>
    <textarea id="input"></textarea>
    <script>
      window.document.getElementById('input').value = "ä";
    </script>
  </body>
</html>
```

will produce

![bildschirmfoto 2015-09-23 um 01 48 05](https://cloud.githubusercontent.com/assets/9946/10034892/32126d98-6195-11e5-97d2-cd83df5cbdeb.png)

**Comment by zcbenz** [comment]
To show HTML pages that don't use UTF-8 encoding, you should explicitly set page's encoding like this:

```html
<head>
<meta charset="UTF-8">
</head>
```

**Comment by kostia** [comment]
Thanks @zcbenz, that worked for me!

However, "ä" is UTF-8 (http://www.utf8-zeichentabelle.de). I somehow assumed, that a document with an HTML5 doctype would have UTF-8 charset by-default. But it does not. Should the Quick-Start example include the right charset? https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md

@MartinMa Does setting the correct encoding resolve your problem?

**Comment by zcbenz** [comment]
> Should the Quick-Start example include the right charset? https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md

I think we should, you can send a pull request for that.

**Comment by MartinMa** [comment]
@kostia Thanks, I just tested this with the current version v0.33.3 (ia32) on Windows. Explicitly setting the encoding to UTF-8 resolves all problems for inline scrips and referenced scripts. :+1: 

I thought, somehow, chromium would figure out the encoding automatically or at least default to UTF-8. None of it is the case. It seems to default to another charset. On a German Windows 8.1 it seems to be *Windows-1252*.
