### ISSUE TITLE
Show open browser windows when right clicking OSX dock icon. 

### ISSUE THREAD

**Issue by tylerjames** [electron/electron#6781]
* Electron version: 1.3.2
* Operating system: OS X Mavericks

If I open a new BrowserWindow from my main BrowserWindow then click outside the new window it becomes hidden. If I right click on the dock icon it does not appear in the list of windows for my app. This actually does work when debugging the app, but not when running a packaged app. I can find the window if I select "Show All Windows" but it's not especially obvious that another window exists in the first place. 

Is there something that I need to do to get my open windows to be listed when I right click on the dock icon?

Example of what I mean: 
<img width="288" alt="screenshot 2016-08-08 16 57 37" src="https://cloud.githubusercontent.com/assets/1138573/17496048/90e01028-5d89-11e6-996c-d612d12bbdbc.png">

**Comment by kevinsawicki** [comment]
Are you using a different menu in your packaged app vs. running app?

I believe you need a menu with a role of `'window'` for open windows to be displayed there.

```js
{role: 'window'}
```

**Comment by tylerjames** [comment]
Thanks @kevinsawicki you were right.

Didn't realize it was necessary to have that for the windows to appear in the dock.

**Comment by jabez128** [comment]
@tylerjames hi，I meet the same problem after packaged electron app with electron-builder. I follow the instruction provided by @kevinsawicki and use `app.dock.setMenu` method to add dock menu, but the menu item lost prefix-icon compared to the `original` menu item.
how did you resolve this problem afterwards?
look forward some advices.

**Comment by jabez128** [comment]
![屏幕快照 2019-06-04 下午6 19 42](https://user-images.githubusercontent.com/2700425/58925500-4da61280-877a-11e9-840c-05360456432e.png)

**Comment by jabez128** [comment]
so helpful~
