### ISSUE TITLE
WebView sometimes doesn't redraw

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#6783]
- Electron version: `1.3.2`
- Operating system: Windows

An issue I have noticed with GPMDP for a while is that sometimes the WebView doesn't "redraw" itself on the screen even though the DOM updates behind it.

I have a demo video you can watch here https://drive.google.com/file/d/0B7t3t121QFG3cTJ0ZXBLUDNZQ00/view

Basically what should be happening is when I hover over the `body` element the content should transition into the window.  And this happens about 50% of the time.  However if you mess with the window a bit (resize or move) and then try again.  It mysteriously doesn't VISUALLY update.  Even though (as you can see at the end of the video) the dom elements are in fact in the correct position as things like the cursor update when over the invisible elements.

This issue appears to line up perfectly with an `app-command` event of type "unknown" appearing in the Devtron IPC inspector.  The `'unknown'` `app-command` event appears to only occur when resizing or moving the window.

Looking for any ideas as to
a) What that event is
b) How to stop this :'(

**Comment by MarshallOfSound** [comment]
After further logging I found these errors appearing whenever the WebView stops rendering

```bash
[34376:0809/123153:ERROR:latency_info.cc(164)] GpuCommandBufferStub::OnAsyncFlush, LatencyInfo vector size 122 is too big.
[34376:0809/123203:ERROR:latency_info.cc(164)] GpuCommandBufferStub::OnAsyncFlush, LatencyInfo vector size 221 is too big.
[34376:0809/123206:ERROR:latency_info.cc(164)] GpuCommandBufferStub::OnAsyncFlush, LatencyInfo vector size 111 is too big.
[34376:0809/123216:ERROR:latency_info.cc(164)] GpuCommandBufferStub::OnAsyncFlush, LatencyInfo vector size 215 is too big.
```

@zcbenz GPU stuff is a bit beyond me, thoughts?

**Comment by MarshallOfSound** [comment]
Worth noting that this error doesn't appear to occur when in frameless window mode

**Comment by zcbenz** [comment]
It seems that either there are problems with GPU rendering, or we need to send a message to webview to paint for certain window messages.

**Comment by MarshallOfSound** [comment]
@zcbenz I found some time to debug exactly what line of code triggered this.

Turns out it is

```js
// MINI_SIZE === 300
remote.getCurrentWindow().setMaximumSize(MINI_SIZE, MINI_SIZE); 
```

**Comment by zcbenz** [comment]
I'm afraid this issue is deeply related to the GPU on your system, and we are not able to fix it on Electron's side. The best hope is probably to wait for a Chrome upgrade.
