### ISSUE TITLE
DownloadItem shows save dialog on 404

### ISSUE THREAD

**Issue by alex-zhang** [electron/electron#6784]
* Electron version: 1.2.4 (May Be All Version has the issue)
* Operating system: MAC OS X 10.10.5 (May Be All OS)

i set the `DownloadItem.setSavePath` but if the target resource return 404 status from server, then the save dialog prompt.

### Steps to reproduce

Merged in from #6957

0. Disconnect from the network
1. initiate a download using mainWindow.webContents.downloadURL(url);
2. call item.setSavePath(path) in the will-download handler

Result:
The browser will show a save dialog.

Expected result:
No save dialog, just an updated or done callback on the item

It appears that the code that notices a save path has been set and prevents the dialog from coming up doesn't happen when the download fails.

**Comment by MarshallOfSound** [comment]
> then the save dialog prompt.

Then the save dialog prompt *what*?

**Comment by alex-zhang** [comment]
prompt  a window and let me choose the saving path.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?
