### ISSUE TITLE
Touchpad stop scrolling inside the app

### ISSUE THREAD

**Issue by ivomachado** [electron/electron#6785]
* Electron version: 0.37.6
* Operating system: Windows 10
After a time with the app open, scroll with the touchpad stops working and only the mousewhell keeps normal. When I try to scroll, the entire window moves a little towards to direction of scroll.
I don't know wich steps to reproduce this issue, but I experience it at least once a day in Visual Studio Code and Atom.
I'm sorry if this is not the right place to talk about this.

**Comment by zcbenz** [comment]
We do not support 0.37.6 anymore, you have to wait for both editors to update to a more recent version and then see whether it would fixed.
