### ISSUE TITLE
Crash in InspectableWebContentsImpl::WebContentsDestroyed() line 631

### ISSUE THREAD

**Issue by bennyn** [electron/electron#6786]
* Electron version: 1.2.5
* Operating system: Win 10 Home

Our Electron application crashed. I tried to debug the crash with [Electron's Symbol Server](https://github.com/electron/electron/blob/master/docs/development/setting-up-symbol-server.md) in Visual Studio but unfortunately it wasn't able to find symbols for `inspectable_web_contents_impl.cc` (`electron-win-ia32/vendor/brightray/browser/inspectable_web_contents_impl.cc`).

What should I do to get a proper stacktrace the next time this crash happens? And can somebody lookup line number 631 of `InspectableWebContentsImpl`?

I could get a screenshot of my debugging session. Maybe this helps to find the error.

**Screenshot**

![screenshot](https://cloud.githubusercontent.com/assets/469989/17519897/1d075ca4-5e4e-11e6-87a8-872b6411931e.PNG)

**Comment by kevinsawicki** [comment]
> And can somebody lookup line number 631 of InspectableWebContentsImpl?

https://github.com/electron/brightray/blob/25d39ad99a7738385af0947804261608d99765ab/browser/inspectable_web_contents_impl.cc#L631

**Comment by zcbenz** [comment]
I'm merging this to #6359.

**Comment by bennyn** [comment]
@kevinsawicki Thanks for pointing me to the code! Do you also know why Visual Studio was unable to download symbols for `inspectable_web_contents_impl.cc`? For other files (like `atom-shell`) it got the symbols.
