### ISSUE TITLE
Is it possible to make -webkit-app-region: drag work with webview?

### ISSUE THREAD

**Issue by egoist** [electron/electron#6791]
* Electron version: 0.37.7
* Operating system: X, this doesn't matter

I'm using a frameless window to load an external website via `webview` tag, so I want to make the header in the webview draggable for users.

I've found a relative issue https://github.com/electron/electron/issues/3299 , but overlapping something with the webview isn't a good idea at all.

**Comment by zcbenz** [comment]
The `-webkit-app-region` is bound to current WebContents while the webview and the host page run in separate WebContents, so it is very difficult archive with currently. I suggest creating an issue at Chromium's issues list instead, since this is essentially an architecture problem of Chromium.

**Comment by kennethlynne** [comment]
Just overlay a div over the webview:
![image](https://user-images.githubusercontent.com/390817/53274460-98ce7500-36f7-11e9-9434-8c5ca6222121.png)
