### ISSUE TITLE
webcontents.capturePage won't capture within specified rect

### ISSUE THREAD

**Issue by zalexou** [electron/electron#6795]
* Electron version: electron-prebuilt 1.3.3
* Operating system: Win10

Hello,

It looks like this method https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentscapturepagerect-callback won't take the "rect" argument.

` webview.capturePage(myRect, myCallback);` 

will throw an error: 

`Error: Could not call remote function 'capturePage'. Check that the function signature is correct. Underlying error: Error processing argument at index 0`

If I use this method without the rect parameter, then it works and captures with the current window's size.

Not sure what's wrong here.

**Comment by kevinsawicki** [comment]
What `rect` are you passing it?

This works for me on 1.3.3:

```js
require('electron').remote.getCurrentWindow().webContents.capturePage({x:0, y:0, width: 10, height: 10}, function (image) {    
  console.log(image.getSize())
})
```

**Comment by zalexou** [comment]
It looks like this: 
`var captureRect = {
    x: 0,
    y: 0,
    height: 1060,
    width: 700
};`

This is my usage:
`webview.capturePage(captureRect, function(data) {
        //fun stuff here
    });
});`

The webview is loaded like this:

`var webview = document.createElement("webview");
webview.src = url;
document.body.appendChild(webview);`

**Comment by zcbenz** [comment]
@zalexou I'm unable to reproduce with your code, can you provide a minimal app that can reproduce this problem? The problem is probably in other parts of your code.

**Comment by zalexou** [comment]
Okay, the problem is that my `captureRect` object was updated with wrong values, the height and width were updated with string values instead of int. I just use `parseInt` on these values and it seems to work now.

**Comment by zcbenz** [comment]
> Edit: Quick question: is it possible to capture an image that would be taller than the window it's rendrerd in? Say if my window is 800x600 and the content larger than that, the biggest image I can get in one go is 800x600 right?

No, the page outside the window's rect is not rendered at all, so it is not possible to capture them.

**Comment by zalexou** [comment]
Thank you, and sorry for the false alarm ;)
