### ISSUE TITLE
Not stopping at breakpoints on Visual Studio Code

### ISSUE THREAD

**Issue by EvaristoPerez** [electron/electron#6797]
Hi Guys,
By reviewing old issues I know this has been failing and fixing in past versions but as for today is not working again. Hopefully I can help with this to get it back soon.

**SYMPTOMS**: After launching the app with F5 (launch.json) break points are not pausing execution in main.js app.on('ready', createWindow). It does however when you close the app (renderer window) at app.on('window-all-closed', function ().
* Electron version:[1.3.0, 1.3.3(current)]
* Operating system: Windows 10/64B

**STEPS TO REP**: Start a electron-quick-start app by clonning at guthub, then change the lauch.json to properly run your app at F5 hit. Set breakpoints at mentioned functions on main.js file. You will see that the app runs and do not stops before creating the window or ahead. Then close the app and verify now that the breakpoint does pause the execution on the second mentioned method.

**VERSIONING RESEARCH**: If you go back to version 1.2.8 it works OK. I have done some little invetigation by down/upgrading the app to find this latest working verion:

•	Break points were failing with latest at the moment we found the issue:  Node 6.3.0, Chromium 52.0.2743.82, and Electron 1.3.0. 
•	After downgrade to 0.37.0 (npm install electron-prebuilt@0.37.0) breakpoints in VSC returned, with: Node 5.1.1, Chromium 49.0.2623.75, and Electron 0.37.0.

https://github.com/electron/electron/issues/4842

•	Went to 1.0.0 and Works fine!: Node 5.10.0, Chromium 49.0.2623.75, and Electron 1.0.0.
•	Went back to latest and fails back again: Node 6.3.0, Chromium 52.0.2743.82, and Electron 1.3.3.
•	Lastest working version is 1.2.8: Node 6.1.0, Chromium 51.0.2704.106, and Electron 1.2.8.

thank you

**Comment by zcbenz** [comment]
I'm merging this to #6608.

**Comment by EvaristoPerez** [comment]
This seems to be fixed under #7001 , still pending release version including this fix (todays' 1.3.4)
