### ISSUE TITLE
Capture URL to JPEG render a black image

### ISSUE THREAD

**Issue by Uhsac** [electron/electron#6798]
* Electron version: 1.3.2
* Operating system: Archlinux

Hello,

I have a problem using electron, it renders a black image when I tried to capture a full js website. (Maybe not the reason)

Here is a simple script to reproduce:

```
const { app, BrowserWindow } = require('electron')
const { writeFile } = require('fs')

app.on('ready', () => {
  const b = new BrowserWindow({
    show: false,
    width: 1366,
    height: 768
  })

  b.webContents.on('did-finish-load', () => {
    setTimeout(() => {
      b.webContents.capturePage(image => {
        const buf = image.toJPEG(100)
        writeFile('test.jpeg', buf, err => {
          if (err) {
            console.log('Error during process:', err)
            return
          }
          console.log('Capture saved to: test.jpeg')
          app.quit()
        })
      })
    }, 5000)
  })

  b.loadURL('http://elm-lang.org/')
})
```

If I'm replacing `http://elm-lang.org/` by `http://www.google.com` it works as expected.

Maybe I'm doing something wrong but I don't see why.

Thanks for your help !

**Comment by brenca** [comment]
I can reproduce this on Windows10 Home too.

If you open the devtools for the page you can see a ReferenceError in the console, I guess that somehow blocks the rendering of the page (if you set `show: true` you can see that the page is all white, or rather transparent, that's why you get a black JPEG).
You can fix this by setting `nodeIntegration: false` in the `webPreferences` option of the `BrowserWindow`.

**Comment by kevinsawicki** [comment]
> If you open the devtools for the page you can see a ReferenceError in the console

Yeah, I'm seeing:

```
Uncaught ReferenceError: Elm is not defined(anonymous function) @ (index):8785
```

> You can fix this by setting nodeIntegration: false in the webPreferences option of the BrowserWindow.

👍 Closing this out.

**Comment by Uhsac** [comment]
Oh thanks a lot ! Didn't think about that I just start to use electron.
