### ISSUE TITLE
Rendering bug causing "stuck" graph images with Cytoscape.js and Electron

### ISSUE THREAD

**Issue by josephst** [electron/electron#6803]
- Electron version: 1.3.3
- Operating system: OS X 10.11.6

As part of Google Summer of Code 2016 I've been working on a project using Cytoscape.js and Electron. Electron appears to have a bug where graph movement does not update properly, resulting in "ghost" images. This is most apparent with the graph but also happens with qTip2 boxes and the Font Awesome loading spinner. 

I've tested with Cytoscape.js versions 2.4 - 2.7.7 (occurs with all versions) and Electron 1.2 - 1.3. Similar code runs in Chrome 52 without issue. The issue appears Mac specific; I have been unable to recreate the issue on Windows. [The project is in this folder](https://github.com/cytoscape/cytoscape.js-tutorials/tree/master/electron_twitter) and the bug can be reproduced with `npm install && npm start`, then clicking "Start Graph" (with input box empty) and dragging the graph around.

![screen shot 2016-08-03 at 12 57 31 pm](https://cloud.githubusercontent.com/assets/1269177/17568092/d210b6f4-5f07-11e6-9134-97f25ae9efbd.png)

**Comment by zcbenz** [comment]
Can you try whether simple usages of Cytoscape.js work correctly in Electron? I would like to know whether the bug is triggered by the code of Cytoscape.js or your app.

**Comment by maxkfranz** [comment]
IIRC, the issue occurs even without Cytoscape.js on the page.  Even the Font Awesome spinner has the artefact.

The issue doesn't happen if you refresh the Electron window (command+r), which is weird...

**Comment by maxkfranz** [comment]
And the [`main.js`](https://github.com/cytoscape/cytoscape.js-tutorials/blob/master/electron_twitter/main.js) file that handles the `electron.app` doesn't do anything outside of what the Electron tutorial has.

**Comment by zcbenz** [comment]
Sorry but I don't think any of us would have time to investigate this without a minimal reproducible case.

**Comment by maxkfranz** [comment]
@zcbenz OK, the issue has been isolated a bit.  One of the necessary conditions is to use flex in the CSS.  @josephst is working on making a minimal demo for you based on a fork of https://github.com/electron/electron-quick-start with a couple small additions

**Comment by josephst** [comment]
I've made a demo for the issue [here](https://github.com/josephst/electron-quick-start). 

The application is based on a fork of the electron-quick-start app with Cytoscape.js 2.7.8 and a flexbox-based layout. The issue is most apparent when rapidly panning the graph and when using graphs with many elements. It also occurs, although less frequently, when dragging around nodes in the graph.

![picture of issue](https://cloud.githubusercontent.com/assets/1269177/17838449/9dedd35e-6793-11e6-92bf-3f90d97b4d6f.png)

**Comment by josephst** [comment]
On further investigation I'm able to reproduce the issue with both flexbox-based layouts and standard block layouts.

**Comment by josephst** [comment]
(Apologies for accidentally closing the issue)

**Comment by kevinsawicki** [comment]
@josephst Thanks for the demo app, I tried it out and wasn't able to reproduce your issue using Electron 1.4.7 on macOS 10.11.6. It may have been fixed in the Chrome 53 upgrade that shipped in Electron 1.4.

I'm going to close this out for now, please comment if you are still seeing this on 1.4.7 and we can reopen this issue.
