### ISSUE TITLE
did-navigate-in-page event triggered by IFRAME load

### ISSUE THREAD

**Issue by nikola** [electron/electron#6808]
* Electron version: 1.3.3
* Operating system: Windows

I have noticed that a `webview` will emit the `did-navigate-in-page` event when an IFRAME included in the page finishes loading.

Is this the desired behavior? The documentation implies that this event shall only trigger when the main frame's URL hash changes. In any case, a flag `isMainFrame` would be helpful here.

**Comment by MarshallOfSound** [comment]
I can't test right now but most events normally come with a `event.target` property.  Is it set on this event?

**Comment by nikola** [comment]
The `event.target` is set to the `webview`, regardless if the event was fired from the main frame or an IFRAME.

**Comment by MarshallOfSound** [comment]
@nikola Upon investigation, I can't reproduce this issue.  Can you please provide a minimal sample app the demonstrates the problem

**Comment by nikola** [comment]
Here is a live page that exhibits this behavior:

http://www.heute.de/

It has this on the page:

`<iframe src="http://rio.zdf.de/embed/short/" border="0" allowtransparency="true" frameborder="0" height="588" width="946" style="width:946" scrolling="no"></iframe>`

Loading (or completing load, can't tell which exact point in the life-cycle) the IFRAME will trigger `did-navigate-in-page` in the main frame.

Extracting this into a minimal sample app might take a while, though.

**Comment by MarshallOfSound** [comment]
@nikola I managed to reproduce the event being fired and I've raised a PR to add the `isMainFrame` attribute to the event. 👍

**Comment by nikola** [comment]
Thanks, much appreciated!

**Comment by nikola** [comment]
Small typo in the PR's change to the documentation: `isMainPage` should be `isMainFrame`.
