### ISSUE TITLE
How can I relaunch my electron app with a different custom url protocol params in OSX?

### ISSUE THREAD

**Issue by nishant09** [electron/electron#6815]
* Electron version: v0.34.1
* Operating system: 10.11.5

I have an electron app running on my Mac. Now I want to relaunch it with the deep link.

for example: if I execute my-electron-app://v=1&param1=value1&param2=value2, this should relaunch the electron app and pass those parameters(process.argv) so I can process them and redirect the user accordingly.

Current behavior: When I click on the deep link, my app window just appears on the screen, doesn't relaunch.

Currently I've below code to process the custom url params:
app.on("open-url", function(event, url) {
   (<any>global)[constants.macParams] = url;
});

**Comment by MarshallOfSound** [comment]
If you are inside the app, why do you need to launch the app through a global protocal handler?

Why not use IPC to pass new parameters to the main process?

Regardless, that won't **relaunch** the app, that would simply fire the **open-url** event.  If you want to relaunch it you need to update Electron versions and change your listener to be.

```js
app.on('open-url', (event, url) => {
  app.relaunch({
    args: url,
  });
});
```

FWIW as well, questions like this should really go on Slack or the discussion forums.  The github issues section is for bugs

**Comment by Avien** [comment]
What if I'm not inside the app anymore, but already closed it but it is still showing on the dock.
I expect that reloading the url with different paras AFTER it was closed will launch it the same way it does on first time (via protocol)
It just doesn't
