### ISSUE TITLE
Alt+Left_arrow accelerator not working on linux

### ISSUE THREAD

**Issue by akashnimare** [electron/electron#6818]
* Electron version: 1.3.1
* Operating system: Ubuntu 14.04
This is how I am using it -

``` javascript
	electronLocalshortcut.register(mainWindow, 'Alt+Left', () => {
		if (page.canGoBack()) {
			page.goBack();
		}
	 });
```
Alt+left works perfectly on OS X.

**Comment by zcbenz** [comment]
The `electronLocalshortcut` works by registering global shortcuts, and the `Alt+Left` shortcut is already registered by the desktop environment you use. I suggest using Electron's API directly or using DOM key events to handle shortcuts.
