### ISSUE TITLE
Pinch-zooming in webview elements

### ISSUE THREAD

**Issue by duncanleo** [electron/electron#6819]
- Electron version: 1.3.2
- Operating system: OS X

Hi,

Is it possible to do pinch-zooming in a `<webview>` element?

**Comment by zcbenz** [comment]
There is no way to do it as far as I know, I suggest bringing this up at [Chromium's issues list](https://crbug.com) instead, the underlying implementation of webview is in Chromium's code base and we are only able to add support for this after Chromium supports it.
