### ISSUE TITLE
Opening chrome://... in webview quits application

### ISSUE THREAD

**Issue by nikola** [electron/electron#6822]
* Electron version: 1.3.3
* Operating system: Windows 10 x64

I've tried to open chrome://gpu (or chrome://flags) in a `webview`, however, the app quits immediately, i.e. following the code flow in my application as if the last `BrowserWindow` has been closed.

Is this intentional? In any case, opening a chrome://... page in the webview should not just quit the application.

**Comment by MarshallOfSound** [comment]
@nikola I can't replicate this issue.

I tried doing

```js
document.querySelector('webview').src = 'chrome://flags'
```

And Electron did not crash or quit.

Can you provide a minimal code sample that demonstrates the problem

**Comment by nikola** [comment]
After reducing the code, I have noticed that the exit is actually due to a side-effect where the target URL is being parsed like a regular HTTP URL. So this issue can be closed.
