### ISSUE TITLE
Referrer don't get set for post request

### ISSUE THREAD

**Issue by ShivangiGa** [electron/electron#6824]
* Electron version:0.37.2
* Operating system: Windows

I am developing an electron app. On click of a link on this app, it is a form post. I am not able to get any referrer for this click.
Another chromium browser opens the link mentioned, but referrer printed is null.

**Comment by zcbenz** [comment]
Does this happen for latest versions?

**Comment by ShivangiGa** [comment]
I am using "electron-builder": "^3.27.0",
    "electron-prebuilt": "^0.37.8"

which is auto downloaded. The issue is coming with these versions.

**Comment by enlight** [comment]
Try the latest version, they don't support old versions.

**Comment by ShivangiGa** [comment]
Thanks enlight!! Could you help me out with the latest version of electron-builder and electron-prebuilt?

**Comment by zcbenz** [comment]
Closing since it a bug of old version, for other questions I suggest seeking help from [the community](https://github.com/electron/electron#community).
