### ISSUE TITLE
Problem with resetting font scaling when switching back and forth hdpi monitor

### ISSUE THREAD

**Issue by quasipedia** [electron/electron#6825]
* Electron version: I have no idea but is the version used on Atom 1.10.0-beta5 and in Slack 2.1.0
* Operating system: Fedora 24 64bit

I have a linux laptop (Fedora 24 64bit), screen resolution 3840x2160 connected to a DELL monitor 2560x1600. Via Thunderbolt 3 (USB C type connector to miniport).

Normally the laptop screen is OFF and I use the external monitor only.

When I go to a meeting and I unplug the external monitor, my atom applications get moved on the laptop monitor and they keep their correct settings, so they are perfectly sized for regular use.

However, when I get back to my desk and replug the external monitor, all of my electron apps keep the overblown font size that it set on the high pixel density monitor.  The font is simply huge.

Even using the keyboard shortcut to reduce the font size, the lower limit (the smallest font I can get) is still a lot larger than the regular font on application boot, which makes sense (as the bug seems related to font scaling rather than size) but it is also annoying, as one has to kill and re-launch all the electron-based apps to get back to normal.

**Comment by zcbenz** [comment]
Can you try whether Chromium browser has the same problem?

**Comment by quasipedia** [comment]
Tested with

    Version 52.0.2743.82 Built from source for Fedora release 24 (Twenty Four) (64-bit)

by having side-to-side windows of Atom, Slack and Chromium and unplugging/replugging the monitor.

Both Atom and Slack showed the problem, Chromium did **not**.

**Comment by zcbenz** [comment]
Can you try whether the latest Electron version has this problem? You can install it by simply running `npm install electron`.

**Comment by quasipedia** [comment]
Unless there is anything I should have done apart from:

- installing and run `electron`
- see the window with "drag your app here to..." appear on screen,
- unplug-replug the screen

...then the latest electron (1.3.3) didn't show the same problem as atom and slack did.
Problem solved?  Or should I have done something more/different?

**Comment by zcbenz** [comment]
Thanks for testing, the only solution is to urge Atom and Slack to update to latest Electron, for Atom there should be an issue or pull request for the Electron update.

**Comment by paulcbetts** [comment]
The latest release coming out this week is moving to Electron 1.2.7, and the release after that will move to 1.3.3

**Comment by quasipedia** [comment]
Thanks everybody for the quick replies/feedback/explanations. Much appreciated!
