### ISSUE TITLE
Renderer IPC events in preload script not being delivered

### ISSUE THREAD

**Issue by Roaders** [electron/electron#6828]
- Electron version: 1.3.2
- Operating system: Windows

Hi All

I have followed the example for ipc communication [here](http://electron.atom.io/docs/api/ipc-main/#sending-messages) but it doesn't seem to work.

my main process code:

```
const {ipcMain} = require('electron')
ipcMain.on('asynchronous-message', (event, arg) => {
  console.log(arg)  // prints "ping"
  event.sender.send('asynchronous-reply', 'async pong')
})

ipcMain.on('synchronous-message', (event, arg) => {
  console.log(arg)  // prints "ping"
  event.returnValue = 'sync pong'
})
```

my browser window code (inside a webview preload script):

```
const {ipcRenderer} = require('electron')
console.log(ipcRenderer.sendSync('synchronous-message', 'sync ping'))

ipcRenderer.on('asynchronous-reply', (event, arg) => {
  console.log(arg)
})
ipcRenderer.send('asynchronous-message', 'async ping')
```

I get the pings logged:

`sync ping
async ping`

but only the synchronous pong:

`sync pong`

Is this a bug or am I doing something wrong?

**Comment by TimNZ** [comment]
Try 1.3.3, works for me.

![google chrome - - screen shot 13-08-2016 10 08 24 pm](https://cloud.githubusercontent.com/assets/1051701/17642670/7e9837de-61a2-11e6-900c-784bf8c06148.png)

**Comment by TimNZ** [comment]
Sorry, didn't replicate your exact scenario.. hold on.

**Comment by Roaders** [comment]
I'll have to see if I can get 1.3.3 then. We're in a locked down environment so to get new versions I have to go through an onboarding process.

**Comment by kevinsawicki** [comment]
I was able to reproduce this using both a `preload` script on a `BrowserWindow` and `<webview>` on 1.3.3

**Comment by ahmedmohamedali** [comment]
Hello,

I'm also facing this issue in 1.3.6. 
Is there a plan to fix this bug ?

Thanks.

**Comment by stilliard** [comment]
Similar issue here, except for me in the preload script it works if I change:
`ipcRenderer.on('asynchronous-reply', (event, arg) => {`
to
`ipcRenderer.on('asynchronous-reply', (arg) => {`

Looks like the event isn't being passed in here, instead just the data of the event. 
This is on electron v1.4.4 on xubuntu 16.04

**Comment by chengxiaojiao** [comment]
Hello @stilliard,

I tested with ipcRenderer.on('asynchronous-reply', (arg) => {} 
Still reproduce the issue. It is reproduced with the following conditions:
1. IPCRenderer.send called in proload script
2. asynchronous callback comes back really fast from the other process

I debugged in the code of electron, and think the root cause is that when the message comes back from the other process too fast, document_created_ is false, so electron doesn't passes the message to the above javascript layer.

void AtomRenderViewObserver::OnBrowserMessage(bool send_to_all,
                                              const base::string16& channel,
                                              const base::ListValue& args) {
  if (!document_created_)
    return;

  if (!render_view()->GetWebView())
    return;
...
}

**Comment by MehediH** [comment]
@zcbenz any update on this issue?

**Comment by atilacamurca** [comment]
Can you test put your async code inside the listener `did-finish-load`:

```js
window.webContents.on('did-finish-load', function() {
    /* your code here */
})
```

Reference: <http://electron.atom.io/docs/api/web-contents/#contentssendchannel-arg1-arg2->

**Comment by BenLambertNcl** [comment]
I have the same issue as @stilliard.

Electron: v1.6.6
OS: Windows 7

Reverting back to Electron v1.6.3 fixed the issue. However, Windows 10 and Windows Server 2012 R2 work as expected (i.e. the event is passed to the listener) on v1.6.6.

**Comment by BenLambertNcl** [comment]
I have the same issue as @stilliard.

Electron: v1.6.6
OS: Windows 7

However, Windows 10 and Windows Server 2012 R2 work as expected (i.e. the event is passed to the listener) on v1.6.6. Reverting back to v1.6.3 caused all 3 OSs call the listener without the event (i.e. `ipcRenderer.on('asynchronous-reply', (arg) => {`)

**Comment by victorhurdugaci** [comment]
Hey folks,

Any workaround for this issue?

I'm trying to get some information from a web page embedded in the app and I don't know of any other way of passing that information to the parent window other than ipc.

Cheers!

**Comment by riccardopiola** [comment]
Had the same problem: You can easily solve it by using a synchronous ipc message

Just swap `ipcRenderer.send()` with `ipcRenderer.sendSync()`

**Comment by victorhurdugaci** [comment]
Thanks @riccardopiola , it was actually my misunderstanding of who will receive the event. I thought it will bubble up in the parent page, not in the main process. It works with both `send` and `sendSync`.

Just for future reference:
- `send` and `sendSync` will send the message to the main process
- `sendToHost` will send the message to the host `webview` and can be handled like in this example: https://electron.atom.io/docs/api/webview-tag/#event-ipc-message

**Comment by dexter0323** [comment]
If the problem is related to know when you app is ready so you can use ipcRenderer, please take a look to my answer here: https://stackoverflow.com/a/50980097/9975292

**Comment by towfiqi** [comment]
^^ `'did-finish-load'` didnt work. Still having the same issue.

**Comment by angeredbovine** [comment]
I'm having similar behavior, although my messages are being sent after DOMContentLoaded fires so it shouldn't be an issue of the window not being ready to receive events. Messages are sending from an instance of ipcrenderer to ipcmain successfully, but messages from event.sender.send and window.webContents.send in the ipcmain event handler are never received in ipcrenderer's event handler.

**Comment by johnryan** [comment]
Did anyone figure out a workaround for this other than the sync communication? still seeing the issue in 4.0.1

**Comment by amaurymartiny** [comment]
I had this in 4.0.1, and just updated to 5.0.1 and now it works

**Comment by mattbroussard** [comment]
I still observe this issue in Electron 5.0.1. For now, I'm using a similar workaround to #9741 and https://github.com/electron/electron/issues/6828#issuecomment-401644014 above

**Comment by reZach** [comment]
There is a [similar issue](https://github.com/electron/electron/issues/21437) when using ipcRenderer in a preload script. It appears this chat is more active, does someone have a good idea of what might be going on / what we can patch in the framework?

**Comment by sherzodv** [comment]
Same issue,

I'm trying to initialize db in preload, and need userData path which I was going to receive from main process (as app.getPath is not working in preload). But replies are never received on preload side.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
