### ISSUE TITLE
WebView crashing with fetch api

### ISSUE THREAD

**Issue by ncortines** [electron/electron#6830]
* Electron version: 1.3.3
* Operating system: Windows 10.0.10586

The issue is one of my webviews is crashing when using the _**fetch**_ api. I use it to handle a chunked http response.

When calling **_stream.read()_** for a second time it returns Promise.reject(NETWORK ERROR) and the webview crashes.

The issue does not occur on mac os.

I'm attaching some dump information. I failed to add the symbols but I'll try again and come back with an updated version.

Any help would be greatly appreciated.

Thanks

Juan

[electron.txt](https://github.com/electron/electron/files/415696/electron.txt)

**Comment by deepak1556** [comment]
Seems to be introduced from https://github.com/electron/electron/pull/6707

**Comment by ncortines** [comment]
Thank you @deepak1556 . I'll stick to 1.3.2 until the issue is clarified.

Juan
