### ISSUE TITLE
Passing object with methods and properties in IPC

### ISSUE THREAD

**Issue by govi2010** [electron/electron#6835]
* Electron version:1.3.3
* Operating system:Windows 10

Hello I am having javascript 
`https://www.abc.com/abc.js `  /// this script is all calling other domains

I have webview which i having url www.gmail.com

I can not direct inject that script in webview as I get following error.

`VM811:1844 Refused to load the script 'https://www.inboxsdk.com/build/platform-implementation.js' because it violates the following Content Security Policy directive: "script-src https://clients4.google.com/insights/consumersurveys/ 'self' 'unsafe-inline' 'unsafe-eval' https://mail.google.com/_/scs/mail-static/ https://hangouts.google.com/ https://talkgadget.google.com/ https://*.talkgadget.google.com/ https://www.googleapis.com/appsmarket/v2/installedApps/ https://www-gm-opensocial.googleusercontent.com/gadgets/js/ https://docs.google.com/static/doclist/client/js/ https://www.google.com/tools/feedback/ https://s.ytimg.com/yts/jsbin/ https://www.youtube.com/iframe_api https://ssl.google-analytics.com/ https://apis.google.com/_/scs/abc-static/ https://apis.google.com/js/ https://clients1.google.com/complete/ https://apis.google.com/_/scs/apps-static/_/js/ https://ssl.gstatic.com/inputtools/js/ https://ssl.gstatic.com/cloudsearch/static/o/js/ https://www.gstatic.com/feedback/js/ https://www.gstatic.com/common_sharing/static/client/js/ https://www.gstatic.com/og/_/js/".`

now what i did ,that i will added `https://www.abc.com/abc.js` script tag in my local html file in which my webview is.

By adding that I will got window.Abc object in DOM.

Abc object is having some methods and some properties. Which i want to use inside webview.

Now , For achieving this, 
I used `<webview>.send(channel[, arg1][, arg2][, ...])`  but in preload script i just got properties of that object ,

Please help.

**Comment by kevinsawicki** [comment]
@govi2010 are you able to provide a small sample app that reproduces this issue?

**Comment by kevinsawicki** [comment]
Are you able to upgrade to Electron 1.3.5 and see if you still experience this issue?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.

**Comment by govi2010** [comment]
@kevinsawicki  As in new version I did not see that bug so its fixed.

**Comment by kevinsawicki** [comment]
@govi2010 are you able to provide more details about what you are seeing? Like a small app that reproduces the issue.

**Comment by kvidzibo** [comment]
@kevinsawicki I was able to replicate that error with:

```
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

class MainProcess {
    constructor() {
        this.mainWindow = false;
        app.on('ready', this.createWindow);
    }

    createWindow() {
        this.mainWindow = new BrowserWindow({width: 950, height: 1029, x: 975, y: 0,
            webPreferences: {
                nodeIntegration: false,
                webSecurity: false
            }
        });

        this.mainWindow.loadURL('https://twitter.com');

        this.mainWindow.webContents.openDevTools();
    }
}

new MainProcess();
```
I can't see that error now, however 'Log in' button still does not work, so I assume some js is still blocked and errors were silenced.

**Comment by kvidzibo** [comment]
also if I run BrowserWindow with sanbox: true. It works fine..

**Comment by sallar** [comment]
@kvidzibo Thanks, this solved my problem :) I was trying to "authenticate" with Dropbox.
