### ISSUE TITLE
[Q] webrtc

### ISSUE THREAD

**Issue by ArmendGashi** [electron/electron#6840]
Is there a way to disable webrtc on electron !

**Comment by ArmendGashi** [comment]
found a way to do it manually, thanks

**Comment by spectral-software** [comment]
Could you explain your solution for people that discover this issue later with a similar question?

**Comment by ArmendGashi** [comment]
It maybe will not do a job for you, there is not solution yet to disable webrtc buildin in electron, but you can do it in this way if you inject js file on preload 

```
navigator.mediaDevices.getUserMedia = undefined;
navigator.webkitGetUserMedia = undefined;
navigator.mozGetUserMedia = undefined;
navigator.getUserMedia = undefined;
webkitRTCPeerConnection = undefined;
MediaStreamTrack = undefined;
RTCPeerConnection = undefined;
```
but still this is not a solution, because you cant inject this script in iframes.

for me it was a solution because i was using nightmarejs wich use electron this is why i asked this question here, but then i realized [webdriver.io](http://webdriver.io/) and i switched on this because it is using firefox and webrtc is disabled by default `i forget wich version` or you can do it.
