### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by marceloclp** [electron/electron#6841]
* Electron version: 1.3.3
* Operating system: Windows 10

It seems like my application can't load any static files. It doesn't load custom templates onto angular directives, css or images. It always receives the same error, which is ERR_FILE_NOT_FOUND. I have tried using ngtemplate-loader in order to load html templates, but was not successful.

I am new to this and I have no idea why it doesn't work, considering I can't seem to find anyone with the same problem. All the solutions I've tried have not helped =(

EDIT: I have now manage to fix the problems with not being able to load imgs and css files by using a different path and file structure. I still can't get the html templates to download though. Is that a bug?

**Comment by kevinsawicki** [comment]
@marceloclp are you able to provide a sample app that reproduces the issue?

Also, are you seeing any errors in the Console tab of the dev tools?

**Comment by kevinsawicki** [comment]
Closing this out until more information is provided, thanks.
