### ISSUE TITLE
clang-built electron white-screens on Linux kernels 4.4.x

### ISSUE THREAD

**Issue by remexre** [electron/electron#6842]
* Electron version: 1.3.3 (`ee8c429dea`)
* Operating system: Linux 4.4.x

refer https://github.com/tensor5/arch-atom/issues/34

Summary: On 4.4.x-series kernels (but not later), copies of electron built with clang get a white screen instead of starting properly. When starting atom with clang-built electron on these systems (I know, unsupported), a SIGILL is triggered. It looks like the SIGILL is coming from an inlined call to [`OS::Abort`](https://github.com/electron/node/blob/ee8c429deaee0adeeef069c3ad34c0defe53a567/deps/v8/src/base/platform/platform-posix.cc#L227) in a function that looks like:

```c
void xyzzy(void* addr, size_t len) {
     if(madvise(addr, len, MADV_FREE) != 0)
           OS::Abort(); // optimized to the `ud2` instruction
}
```

The code surrounding the `ud2` instruction looks like [`OS::Free`](https://github.com/electron/node/blob/ee8c429deaee0adeeef069c3ad34c0defe53a567/deps/v8/src/base/platform/platform-posix.cc#L101) and [`OS::Guard`](https://github.com/electron/node/blob/ee8c429deaee0adeeef069c3ad34c0defe53a567/deps/v8/src/base/platform/platform-posix.cc#L125), and there's another part that *resembles* [`OS::ProtectCode`](https://github.com/electron/node/blob/ee8c429deaee0adeeef069c3ad34c0defe53a567/deps/v8/src/base/platform/platform-posix.cc#L110), but with different values for the `prot` argument.

However, I can't find a matching call to `madvise` anywhere... Does anyone familiar with the code:

 * Recognize where `madvise` would be called with `MADV_FREE`
 * Know why this would only happen on 4.4.x kernels
 * Want to help debug?

**EDIT** To clarify, running the *same binary* on a system with a later kernel works perfectly, as does Atom.

**Comment by zcbenz** [comment]
I'm afraid the only possible way to work around this for now is to build Electron by you own, I'm merging this to #259.
