### ISSUE TITLE
nativeImage.createFromPath(path) fails silently for bad paths

### ISSUE THREAD

**Issue by KeitIG** [electron/electron#6844]
* Electron version: 1.3.3
* Operating system: all (Ubuntu in that case)

Just reporting something I've just faced. I did a release of a software based on Electron, but in the build process, the `images` folders were deleted, with the app icon inside.
Then, when running Electron, no error were thrown, and the app had no icon (ofc).

Shouldn't a warning or an error be thrown in that case ?

**Comment by zcbenz** [comment]
You can check whether the icon has been loaded by using `image.isEmpty()` API:
http://electron.atom.io/docs/api/native-image/#imageisempty

This behavior is intentional to match the other APIs of `nativeImage`, you can use strings directly if you want to get exceptions.
