### ISSUE TITLE
shell.moveItemToTrash hardcodes call to gvfs-trash

### ISSUE THREAD

**Issue by mjmvisser** [electron/electron#6847]
* Electron version: git master
* Operating system: Linux

KDE-based distros use `kioclient move <path> trash:/`.
Gnome uses `gvfs-trash <path>`.
Others  (e.g. XFCE) use `trash-put <path>` (part of the trash-cli package on freedesktop.org).

To determine which binary to execute, just check for one of gvfs-trash, kioclient and trash-put in /usr/bin and use the first found.

**Comment by 50Wliu** [comment]
This was discussed before in #637.

**Comment by zcbenz** [comment]
Closed with #7178.
