### ISSUE TITLE
How can I access DOM element via Electron?

### ISSUE THREAD

**Issue by mrmayfield** [electron/electron#6849]
I've been reading the documentation on this but it doesn't look clear for me.

I have created a BrowserWindow instance, and navigated to a URL that I do not control.

I want to access a specific value, which if I run it from my browser console, I get a value.

`document.querySelector('input[name="fb_dtsg"]').value`

How can I run this from my JS code to access that DOM element value and manipulate it in my source code? Thanks!

**Comment by kevinsawicki** [comment]
> How can I run this from my JS code to access that DOM element value and manipulate it in my source code?

You can either use a `preload` script to inject an script into the loaded page or call `executeJavaScript` on the `webContents` property of the `BrowserWindow`.

http://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions

http://electron.atom.io/docs/api/web-contents/#contentsexecutejavascriptcode-usergesture-callback

**Comment by mrmayfield** [comment]
Hm, since the code I want to execute is : 
`document.querySelector('input[name="fb_dtsg"]').value`

I can't really turn this into a single since I'm already using both single and double quotes. Do I have to inject a script then in this case?

**Comment by mrmayfield** [comment]
If I injected a script, how would I be able to have that return a value to my Electron source code?

**Comment by kevinsawicki** [comment]
You can use the `ipcRenderer` module to send a message from the renderer process to the main process.

http://electron.atom.io/docs/api/ipc-renderer/

**Comment by kevinsawicki** [comment]
> I can't really turn this into a single since I'm already using both single and double quotes. Do I have to inject a script then in this case?

You can use template strings:

```js
window.webContents.executeJavaScript(`document.querySelector('input[name="fb_dtsg"]').value`, function (result) {
  console.log(result)
})
```

**Comment by mrmayfield** [comment]
Can't believe I didn't think of that. Okay awesome, works like a charm, thanks a lot!

**Comment by vasyl-shumskyi** [comment]
Can I use `BrowserWindow.fromId(2)` here?
```
BrowserWindow.fromId(2).webContents.executeJavaScript(`document.querySelector('input[name="fb_dtsg"]').value`, function (result) {
  console.log(result)
})
```
I tried, but didn't get html back

**Comment by blurymind** [comment]
how do you pass to it an array that contains objects ?

**Comment by krishna-suwal** [comment]
> Can I use `BrowserWindow.fromId(2)` here?
> 
> ```js
> BrowserWindow.fromId(2).webContents.executeJavaScript(`document.querySelector('input[name="fb_dtsg"]').value`, function (result) {
>   console.log(result)
> })
> ```
> 
> I tried, but didn't get html back
> 
> UPD: My bad. I've tried with `document.getElementById` but not `document.querySelector`.

Try this:

```javascript
window.webContents.executeJavaScript(`document.querySelector('input[name="fb_dtsg"]').value`, true)
.then(function (result) {
	console.log(result)
})
```

**Comment by FloYoutube54** [comment]
I tried to execute function from another JS file, but I've this error while trying to set property of the element : 
`Uncaught TypeError: Cannot set properties of null (setting 'src')`

main.js :
```js
main.webContents.executeJavaScript('initLogo(\'light\');');
```

other_script.js :
```js
function initLogo(mode) {
    if (mode === 'dark') {
        document.querySelector('img[id="logo"]').src = '../assets/img/logos/icon.png';
    } else {
        document.querySelector('img[id="logo"]').src = '../assets/img/logos/icon_theme_claire.png';
    }
}
```

index.html :
```html
<html>
    <head>
        <link title="Light mode" href="../css/bootstrap-sncf.css" rel="stylesheet">
        <link title="Dark mode" href="../css/bootstrap-sncf.darkmode.css" rel="stylesheet alternate">
        <script src="../js/bootstrap-sncf.js"></script>
        <script src="../js/appareance.js"></script>
    </head>

   <body>
       <center>
           <img src="../assets/img/logos/icon.png" id="logo">
       </center>
   </body> 
</html>
```

**Comment by Eboubaker** [comment]
in my case the window was created by invoking `window.open`
by default electron NodeIntegration is disabled, so you can't access the DOM of the other window.
changing the  property `nativeWindowOpen` to true fixed my issue.
```js
// in main.ts
async function createWindow() {
  const win = new BrowserWindow({
    // ....
    webPreferences: {
      nativeWindowOpen: true,
    }
  })
```
Now i can access the window.document element when i create the window using `window.open`

**Comment by karpinski1994** [comment]
> > I can't really turn this into a single since I'm already using both single and double quotes. Do I have to inject a script then in this case?
> 
> You can use template strings:
> 
> ```js
> window.webContents.executeJavaScript(`document.querySelector('input[name="fb_dtsg"]').value`, function (result) {
>   console.log(result)
> })
> ```

For me this function doesn't work at all, the callback isn't even triggered.
I'm using it like this in the main.js file:
```
mainWindow.loadURL('http://example.com')
  
mainWindow.once('ready-to-show', () => {
  mainWindow.webContents.executeJavaScript(`document.querySelector('h1').innerHTML`, function (result) {
    console.log('=================')
    console.log(result)
  })
})

```

**Comment by karpinski1994** [comment]
> > I can't really turn this into a single since I'm already using both single and double quotes. Do I have to inject a script then in this case?
> 
> You can use template strings:
> 
> ```js
> window.webContents.executeJavaScript(`document.querySelector('input[name="fb_dtsg"]').value`, function (result) {
>   console.log(result)
> })
> ```

For me using the following method results with:
```

(node:956) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at node:electron/js2c/sandbox_bundle:57:405
    at EventEmitter.<anonymous> (node:electron/js2c/sandbox_bundle:45:375)
    at EventEmitter.emit (node:electron/js2c/sandbox_bundle:112:3752)
    at Object.onMessage (node:electron/js2c/sandbox_bundle:37:756)
```
I'm using it like this in main.js:

```
const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  })

  mainWindow.loadURL('http://example.com')
  
  mainWindow.once('ready-to-show', () => {
    mainWindow.webContents.executeJavaScript(`document.querySelector('h1').innerHTML`, function (result) {
      console.log('=================')
      console.log(result)
    })
  })
```

**Comment by Omar25py** [comment]
> > Can I use `BrowserWindow.fromId(2)` here?
> > ```js
> > BrowserWindow.fromId(2).webContents.executeJavaScript(`document.querySelector('input[name="fb_dtsg"]').value`, function (result) {
> >   console.log(result)
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried, but didn't get html back
> > UPD: My bad. I've tried with `document.getElementById` but not `document.querySelector`.
> 
> Try this:
> 
> ```js
> window.webContents.executeJavaScript(`document.querySelector('input[name="fb_dtsg"]').value`, true)
> .then(function (result) {
> 	console.log(result)
> })
> ```
that work fine, thankyou man
