### ISSUE TITLE
Custom Url scheme to launch app through link

### ISSUE THREAD

**Issue by paulbeliavskisPanviva** [electron/electron#6854]
* Electron version: 1.3.3
* Operating system: Windows 10

Hi, I am having a bit of trouble launching my electron app through a link.
The registerHttpProtocol never executes the handler but it executes the callback. So the following code would only print "here2" to the console. furthermore I get protocol undefined. Can anyone help me?
Thank you.

import { app, Menu, session, protocol } from 'electron';

var url_scheme = "custom";
protocol.registerStandardSchemes([url_scheme])

app.on('ready', function () {
    console.log(protocol);    
     protocol.registerHttpProtocol(url_scheme, (request, callback) => {
         console.log("here1");
 }, (error) => {
   console.log("here2");
   if (!error) console.error('Failed to register protocol')
});

**Comment by MarshallOfSound** [comment]
Assuming you want to launch your app using a URL scheme **form outside the app itself**.  You need to use default protocol client API.

https://github.com/electron/electron/blob/master/docs/api/app.md#appsetasdefaultprotocolclientprotocol-macos-windows

**Comment by paulbeliavskisPanviva** [comment]
Thanks for your quick reply. This now tries to launch electron but where would I put the code to handle when the app is opened from the link? Also I get the error below when I try to launch the app.
Any Idea?
![errorlaunchingapp](https://cloud.githubusercontent.com/assets/20054969/17684555/f388a12e-639f-11e6-9045-7fef7b01bb98.png)

**Comment by MarshallOfSound** [comment]
@paulbeliavskisPanviva It looks like you are setting up the protocol client from a development install of Electron.  Using `electron-prebuilt` or something similar, this will tell the OS to open `electron.exe` not your app.

In order for it to work you have to package your application.  Then the URL is parsed in on the `argv`

**Comment by srinathganesh** [comment]
is this limited to windows and mac? will it work in linux?

**Comment by Nick-lab** [comment]
@srinathganesh i would like to know this as well also is there a way we can simulate this functionality in dev environment?

**Comment by AndreasWebdev** [comment]
Is there a way to test this in current versions of electron?

**Comment by anjalithoke** [comment]
I am having error that can not find Electron app at C:\WINDOWS\system32\myclassroom:\param. Is there any solution for this?
