### ISSUE TITLE
Header Origin is always set to file:// when ajax request

### ISSUE THREAD

**Issue by enrimr** [electron/electron#6859]
* Electron version: 1.3.3
* Operating system: OS X

When make a request to a external API, the electron app set Origin header to file:// so the backend doesn't allow the request. It will be right if would send file:/// or the exact route to the resource for example file://myapp/myroute

**Comment by zcbenz** [comment]
You can use node's `http` module to send custom requests to solve this, or you can use custom protocol to load your app.

**Comment by ZissisT** [comment]
what if we use a thirdparty sdk which executes that http ajax request internally?

**Comment by enrimr** [comment]
@ZissisT I solved with the following method:
```
session.defaultSession.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
      //console.log(details);
      //details.requestHeaders['User-Agent'] = 'MyAgent';
      details.requestHeaders['Origin'] = 'http://myorigin.com';
      callback({cancel: false, requestHeaders: details.requestHeaders});
    });
```

**Comment by HypePhilosophy** [comment]
@enrimr Thank you! It took me a better part of a day to try and figure out how to solve that issue.

**Comment by camillewall** [comment]
I was happily using the onBeforeSendHeaders code by @enrimr and it worked great until I upgraded my electron version to 7.1.13. Now I am receiving 100's of 'Invalid Host/Origin header' and '[WDS] Disconnected!' errors in my console log. Is anyone else seeing this or have a solution?

**Comment by camillewall** [comment]
I was able to figure out my problem. Once I added a filter to just add the origin header to webservice calls I cared about all the errors went away and everything started working.

**Comment by jan-scorl** [comment]
> @ZissisT I solved with the following method:
> 
> ```
> session.defaultSession.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
>       //console.log(details);
>       //details.requestHeaders['User-Agent'] = 'MyAgent';
>       details.requestHeaders['Origin'] = 'http://myorigin.com';
>       callback({cancel: false, requestHeaders: details.requestHeaders});
>     });
> ```



> @ZissisT I solved with the following method:
> 
> ```
> session.defaultSession.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
>       //console.log(details);
>       //details.requestHeaders['User-Agent'] = 'MyAgent';
>       details.requestHeaders['Origin'] = 'http://myorigin.com';
>       callback({cancel: false, requestHeaders: details.requestHeaders});
>     });
> ```

@enrimr What does `session` refer to in your snippet?

If I get `session` from the current window by using `ses = win.webContents.session` then `ses.defaultSession` is `undefined`.

If I initiate `session` through `const { session } = require("electron");` then `defaultSession` is accessible but setting the parameters has no effect on the network calls.

**Comment by rbalet** [comment]
> @ZissisT I solved with the following method:
> 
> ```
> session.defaultSession.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
>       //console.log(details);
>       //details.requestHeaders['User-Agent'] = 'MyAgent';
>       details.requestHeaders['Origin'] = 'http://myorigin.com';
>       callback({cancel: false, requestHeaders: details.requestHeaders});
>     });
> ```

For the one like me that didn't understand where to put it.

You have to add the following code into the `main.js` file.
the second part of the code have to be called after the electron app is ready,

```javascript
const { session } = require('electron')

// When ready
// Modify the user agent for all requests to the following urls.
const filter = {
  urls: ['https://*.github.com/*', '*://electron.github.io']
}

session.defaultSession.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
  details.requestHeaders['User-Agent'] = 'MyAgent'
  callback({ requestHeaders: details.requestHeaders })
})
```
_it's a copy of the code found here [electronjs.org](https://www.electronjs.org/docs/api/web-request)_
