### ISSUE TITLE
visibilitychange and webkitvisibilitychange event issues

### ISSUE THREAD

**Issue by mickylad** [electron/electron#6860]
- Electron version: 1.3.3
- Operating system: Windows 7

Hi,

It seems there are a few issues with page visibility events.

The first is that the `visibilitychange` event fires twice, causing listeners to run twice. This does not occur for `webkitvisibilitychange`.

The second is that when a `visibilitychange` event listener runs for the first time, and when a `webkitvisibilitychange` listener runs, `document.visibilityState` does not contain the correct (new) state - it contains the previous state. If you check the property after the event has fired (e.g. in a timeout or manually), and also when the `visibilitychange` listener runs for the second time, it is then correct. It might also be worth noting that `document.webkitVisibilityState` is correct in all cases.

[page-visibility.zip](https://github.com/electron/electron/files/420080/page-visibility.zip)
[page-visibility-webkit.zip](https://github.com/electron/electron/files/420096/page-visibility-webkit.zip)

These are sample applications to reproduce the bug, which will log the two state properties (`visibilityState` and `webkitVisibilityState`) whenever the event fires. The first is listening to `visibilitychange` and the second to `webkitvisibilitychange`. Just do `npm install` then run with `./node_modules/.bin/electron .`.

If you minimize and restore the application, you should be able to see what I've described in the logs. If you open `index.html` in Chrome and do the same, you should see that both then behave correctly.

I'll admit I'm not sure if this is definitely an Electron bug - I can't see much relating to `visibilitystate` in the Electron code. If it is and you'd prefer the two issues to be raised separately I can do that, just let me know.

**Comment by lukeapage** [comment]
the most recent relevant PR/issues I can find is: https://github.com/electron/electron/pull/4700

**Comment by nathan5x** [comment]
This exact issue is happening on
`macOS Mojave 10.14`
`Version 83.0.4103.116 (Official Build) (64-bit)`
