### ISSUE TITLE
Problems with mdns and version mismatch in electron 1.3.1

### ISSUE THREAD

**Issue by thanpolas** [electron/electron#6862]
Hello,

I have also reported this issue on the [electron discuss forum](https://discuss.atom.io/t/problems-with-mdns-and-version-mismatch-in-electron-1-3-1/31712) but there was no answer there.

I recently upgraded to electron 1.3.1, node 6.3.0 and npm 3.10.5 on OSX.

We use [the mdns 2.3.3](https://github.com/agnat/node_mdns) , everything installs fine with npm install (after i have rm -rf node_modules) but when I launch the app mdns fails with a message:

```
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/thanpolas/Projects/work/xxx/xxx/node_modules/mdns/lib/dns_sd.js:25:20)
```

... and the stack goes on ...

This issue has also [been reported to the mdns package bug tracker](https://github.com/agnat/node_mdns/issues/172)

As per mdns' author advice I got redirected to Electrons documentation about native modules: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

In there I noticed the `./node_modules/.bin/electron-rebuild` command (which i couldn't recall invoking in pre 1.x versions that i migrated from). Once I installed the electron-rebuild package and run the command the Electron application was able to move.

However, I have two critical problems now:

1. **Cannot run tests**. In our usecase, Electron wraps around an existing Node.js application which we are not able to launch as standalone now because of another Module version mismatch. Which results in our whole existing test suite not being able to run because it cannot launch the node.js server in standalone mode.

2. **Cannot build electron application**. We bundle the electron application using a grunt script which uses `electron-packager` and `appdmg`, this is a stand-alone grunt task module which when included by grunt it now throws a similar Module version mismatch error.

Both problems get solved by me doing an `rm -rf node_modules;npm install` but then I cannot start the Electron application in dev mode with `npm start` (which translates to `node_modules/.bin/electron electron/main.js`)

I'm a bit at a loss here, i've migrated from electron 0.x and all this is new to me, I have now downgraded back to 0.x until I have a solution for this.

**Comment by MarshallOfSound** [comment]
> Cannot run tests

Use [`electron-mocha`](https://github.com/jprichardson/electron-mocha) or your test suite's equivalent.  It runs your tests using the Node runtime provided by electron.

> Cannot build electron application.

This is where you either use either the [two package JSON structure](https://github.com/electron-userland/electron-builder#two-packagejson-structure) that `electron-builder` recommends or wait patiently for my PR into `electron-rebuild` to go through https://github.com/electron/electron-rebuild/pull/98

Closing as it's basically a question that has now been answered (normally I would put some stuff here about please use slack or the discussion forums but you said you had no luck so here's your answer) 👍

**Comment by MarshallOfSound** [comment]
@thanpolas Funnily enough you have exactly the same config (mdns + appdmg) problem I had over at my project

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-

You can hit me up on Slack if you want to discuss structure a bit more 👍

**Comment by thanpolas** [comment]
@MarshallOfSound thank you for all of this, slack while cool it does not scale, so if you have a few bullet points to make please make them here for all future devs that search for this to know what to do...
