### ISSUE TITLE
Can't enable video hardware acceleration (as able in Chromium)

### ISSUE THREAD

**Issue by salmoro** [electron/electron#6864]
- Electron version: 1.3.3
- Operating system: Arch Linux

Hi,

I am unable to get electron to use the same graphics driver as I can on chromium.

I've spent countless hours using the chrome switches on both Electron and Chromium to try and get to the bottom of this but to no avail. I've tried this across several versions of Chromium and Electron (from Chromium 50 to 52 on both).

Please see the attached photos that display the chrome://gpu results and see if you have any ideas of what might be the issue here.

Is there some sort of override on some Chrome switches in Electron? Can this be turned off on build?

Thanks very much,
Sal

[chromium_1.pdf](https://github.com/electron/electron/files/420654/chromium_1.pdf)
[electron_1.pdf](https://github.com/electron/electron/files/420653/electron_1.pdf)

**Comment by zcbenz** [comment]
From the PDF it seems that video hardware acceleration is enabled?

```
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
```

And can you try how the official Google Chrome browser behave?

**Comment by salmoro** [comment]
Sorry for not clarifying:

Yes, it says "Hardware accelerated" on the top of the page but when you look further down on the page in the "Driver Information" section you'll notice that Electron is not using the same driver as Chromium and therefore it's actually not using Hardware Acceleration, in-spite of what it says on the top of the page. (It is using the MESA driver which on this system is known to be the software renderer as apposed to Mali which is know to be the hardware renderer). 

Just to clarify, I'm running them both (Chromium and Electron) on the exact same device.

Chromium by default was also using the Mesa driver but after adding the command line switches `--ignoregpublacklist` `--numrasterthreads=2`  and `--usegl=egl` It changed to `Video Decode: Hardware accelerated` and  the Mali driver. On Electron it only changed to `Video Decode: Hardware accelerated` but the driver remains the default MESA.

Regarding trying it on a Chrome browser, since this is on a Arch Linux, I can only use Chromium. So the attached PDFs include one for Electron and one for Chromium.

**Comment by zcbenz** [comment]
It is possible that some of the command line switches you passed need some extra work to activate.

**Comment by kevinsawicki** [comment]
@salmoro are you still experiencing this issue in Electron 1.6 which is using Chrome 56?

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by perf2711** [comment]
Basically it looks like `chromium` for Linux is compiled with disabled GPU acceleration, even, if the flags are set. @saiarcod895 managed to create a patch for `chromium`. However, I do not see any code in the `libchromiumcontent` package matching the patch. Is it possible to compile Electron with this?

Link to the patch:
https://github.com/saiarcot895/chromium-ubuntu-build/commit/f8bd4a884894c47f7bce04c7b4d25a714c7a2faa#diff-6d883d9541ff7f20f76cd8619af284b3

**Comment by AlinChindea** [comment]
@salmoro how did you get the gpu settings for the electron app? having a similar issue and I need to compare the settings and have no clue how to get those. thanks!

**Comment by kingio** [comment]
@zcbenz shouldn't this issue be reopenend?  @perf2711 is pointing to the fix that electron should have :S

**Comment by GitFlip** [comment]
@salmoro How did you get the results of `chrome://gpu/` for your electron app?

**Comment by salmoro** [comment]
@GitFlip It's been a while since I did that but I believe I did it using the method you reference above.
