### ISSUE TITLE
`scroll-touch-begin` and `scroll-touch-end` events don't work as expected in v1.3.3

### ISSUE THREAD

**Issue by blueoctopus** [electron/electron#6873]
* Electron version: v1.3.3
* Operating system: OS X 10.11.6

v1.3.3 broke the detection of the `scroll-touch-begin` and `scroll-touch-end` events for me within a `webview`. It looks like the pull request #6754 caused this issue. v1.3.2 works as expected.

Behavior that I'm observing on v1.3.3:

- Most of the time, the `scroll-touch-*` events are not emitted when the cursor is on top of a `webview`.
- The `scroll-touch-*` events seem to be emitted *only once* when the cursor is on a `webview` and on a scrollable element. The scrollable elements in my app have no native scrollbar set (they have the style `overflow: hidden;` set instead of `overflow: scroll;`). This is the case in which I need to receive the `scroll-touch-*` events.
- The `scroll-touch-*` events seem to work fine when the cursor is outside of the `webview` tag.

**Comment by darkdh** [comment]
@kevinsawicki I'm not 100% sure.
@blueoctopus would you mind giving me your code example to test?

**Comment by blueoctopus** [comment]
@darkdh I created a small app that reproduces this issue, based on the default Electron app: https://github.com/blueoctopus/electron-issue-6873

I reproduced it by downloading Electron v1.3.4 and running:

`./electron-v1.3.4-darwin-x64/Electron.app/Contents/MacOS/Electron electron-issue-6873`

A step-by-step is shown when running the app.

I also tested it with v1.3.2 and observed the expected behavior.

**Comment by pfrazee** [comment]
I'm experiencing the same issue. Within a webview, the events don't consistently fire. I haven't been able to isolate any specific pattern causing it.

**Comment by darkdh** [comment]
Sorry. I think this is caused by my PR. I will submit a patch to fix it. 
Could I take the assignee?
