### ISSUE TITLE
Can' t start electron app in Ubuntu with rc.local

### ISSUE THREAD

**Issue by AJPiPm** [electron/electron#6876]
* Electron version:  v1.3.3
* Operating system: Debian 3.14-1-amd64 && Ubuntu 14.04.4

when i run the following cmd
`/home/newcomer/electron/node_modules/electron/cli.js`
it **works**.
However , i add the following simple cmd in rc.local and want electron runs well after reboot, 
it **failed**.
I'm wonderring how the difference between the 2 run ways.
It would be quite helpfull if there is any way to start electron when pc boot.
Thanks in advance

**Comment by zcbenz** [comment]
You can find why it doesn't work and how to do it correctly in following links:
http://unix.stackexchange.com/questions/131503/run-a-gui-program-at-startup
https://gnomeshell.wordpress.com/2011/08/28/manage-the-startup-applications/
