### ISSUE TITLE
Embedded browser window

### ISSUE THREAD

**Issue by Feelnoobskill** [electron/electron#6878]
Is that possible to make embedded browser window? Meaning that I would like to create browser window inside of another browser window. Right now I created child window with `alwaysOnTop` and positioned `x` and `y` params. So it looks like window is "embedded" but when I move or resize the top window everything will break 

* Electron version: 1.0.0
* Operating system: OSX

**Comment by MarshallOfSound** [comment]
This is the exact purpose of the [WebView Tag](http://electron.atom.io/docs/api/web-view-tag/)
