### ISSUE TITLE
How to disable DevTools from shortcut and webContents API?

### ISSUE THREAD

**Issue by nantas** [electron/electron#6879]
* Electron version: 1.1.3
* Operating system: macOS

We are using encrypted asar package to protect source code. However it's not completely safe if user can get access to DevTools and get access to node API. 

I was searching in this repo and run into this comment https://github.com/electron/electron/issues/4359#issuecomment-184059827 

from @zcbenz  :
>you need to be careful to remove the possibility to open devtools.

I'm wondering how to achieve this in electron? Do I need to hack the webContents API to make it happen? Also is it possible to allow only certain window to be able to open DevTools?

Thanks a lot in advance!

**Comment by MarshallOfSound** [comment]
@nantas As far as I am aware, dev tools aren't disabled as such.  But access is removed.  Currently you access devtools through the default application menu.  If you override the default application menu then access to the devtools is removed.

**Comment by nantas** [comment]
@MarshallOfSound thanks for your reply.

We can disable menu access for menu and shortcut, but user can still pass a `--show-devtools` to Electron executable to make it open at launch, right?

Also if the application can run any user script, they can use `webContents.openDevTools` to bypass menu restriction.

**Comment by MarshallOfSound** [comment]
@nantas I just tested running 

```bash
electron.exe --show-devtools
```

And it does not take affect.  I believe that CLI option needs to be passed to a renderer process which is controlled from the main process who have separate args.  If this is different to what you are seeing please explain further 👍

**Comment by zcbenz** [comment]
If you don't explicitly add a "show devtools" menu item, there will be no explicitly way for users to open devtools after you packaged your app.

However users can still get access to devtools by passing `--remote-debugging-port` command line switch, currently the only to prevent this is to refuse to start when such switches are detected.

**Comment by Thalinda** [comment]
Updated to v8 now when i package it's showing developer tools

**Comment by jadhavrani123** [comment]
hello sir,
I my exe on click cntl + shoft + I open developer tool but I want to disable it ??
how it is possible

**Comment by dijux** [comment]
@jadhavrani123 you can try this 
`
new BrowserWindow({
  width: 400,
  height: 400,
  webPreferences: {
    devTools: false
  }
})
`
[ Reference is here ](https://github.com/electron/electron/pull/7096#issuecomment-245151514)

**Comment by TheZoraiz** [comment]
Use `!app.isPackaged` to enable dev tools during development and disable after packaging:
```js
new BrowserWindow({
    width: 400,
    height: 400,
    webPreferences: {
      devTools: !app.isPackaged,
    }
})
```

**Comment by evertonlperes** [comment]
> Use `!app.isPackaged` to enable dev tools during development and disable after packaging:
> 
> ```js
> new BrowserWindow({
>     width: 400,
>     height: 400,
>     webPreferences: {
>       devTools: !app.isPackaged,
>     }
> })
> ```

Adding more stuff on @TheZoraiz comment:
If you are struggling to run E2E tests with `jest` (Nuxt/Webpack + Vue project), you might add this:

```javascript
 webPreferences:  {
      devTools:           !(app.isPackaged || process.env?.NODE_ENV === 'test'), // make sure it is disabled for e2e tests
      nodeIntegration:    true,
      contextIsolation:   false,
      enableRemoteModule: process.env?.NODE_ENV === 'test'
```

**Comment by Omar25py** [comment]
you can protect code with enigma virtual box, this have an API you can use to code inside to increase security, and i test this ...i tried to read renderer.js and virtual box dont show file
