### ISSUE TITLE
Font not rendering after upgrade to 1.3.3 from 0.36.7

### ISSUE THREAD

**Issue by odubuc** [electron/electron#6883]
* Electron version: 1.3.3
* Operating system: Ubuntu 14.04.5 LTS
* Node version: 4.5.0
* npm version: 2.15.9

I have an app running fine in version 0.36.7 on a headless server inside Xvfb.
I had to move to a new machine/datacenter today so I tried the latest version 1.3.3 just for "fun" and all the font disappeared. The pages are rendering fine but without any characters.

I then reverted electron to 0.36.7 and the app is rendering font just fine again. 

Did I miss a new configuration added recently regarding fonts or might this be a bug?

Thanks for the help!

**Comment by odubuc** [comment]
I might be able to pin point a bit more between which version the font start disapearing. I'll post back in a few minute.

**Comment by odubuc** [comment]
after further testing, my font are rendering up to version 1.2.8 and stop working in 1.3.0

**Comment by kevinsawicki** [comment]
> after further testing, my font are rendering up to version 1.2.8 and stop working in 1.3.0. Hope this helps

Electron 1.3.x ships with Chrome 52, can you download and install Chrome/Chromium 52 and see if the font renders there?

**Comment by odubuc** [comment]
ha! yes how did I miss it in the release notes.. now that Chrome 52 is installed it works on 1.3.3. Thank you for your help! :)
