### ISSUE TITLE
Menu will open event & titleBarStyle: 'hidden' for Windows Systems acceptable?

### ISSUE THREAD

**Issue by reiberdatschi23** [electron/electron#6885]
Hello,

We (Gravit -> https://www.gravit.io) would want to create two pull requests:

1.) One for Menu API (each system) providing an additonal function callback similiar to "click" in MenuItem like: new Menu({open: function() {})) that gets triggered whenever that menu is opened or popped up depending on its type to give a chance for updating the menu items.

2.) Implement titleBarStyle: 'hidden' for windows as well so that we could put the menubar into the titlebar and only show the controls like it is on mac (+ the app icon like used on windows).

We'd like to know in advance as we need those features and if you don't think you'd merge those requests we'd skip implementing this and rebuild the behavior in html somewhat.

thanks

**Comment by kevinsawicki** [comment]
The first item sounds pretty similar to #528 which many people have commented would be useful 👍 

The second item sounds great too 👍 

> We'd like to know in advance as we need those features and if you don't think you'd merge those requests we'd skip implementing this and rebuild the behavior in html somewhat.

We can't say definitively what will get merged without seeing how it is implemented first but both items you mentioned seem valuable to Electron.

I'm going to close this issue out, feel free to open your pull request(s) early on in the process and we can discuss API and implementation details there, thanks for considering making these contributions 🙌

**Comment by kevinsawicki** [comment]
> Implement titleBarStyle: 'hidden' for windows as well so that we could put the menubar into the titlebar and only show the controls like it is on mac (+ the app icon like used on windows).

You may want to see https://github.com/electron/electron/issues/6823 if you haven't already.
