### ISSUE TITLE
electron-quick-start Not working on RPI2

### ISSUE THREAD

**Issue by hamdipro** [electron/electron#6886]
* Electron version:electron-v0.36.8-linux-arm.zip
* Operating system: Rasbian (Raspberry Pi 2)

i have cloned the default repository (electron-quick-start ) and install his dependencies and when i enter: 
`npm start` 
i get this error log :
![screenshot from 2016-08-17 21 18 10](https://cloud.githubusercontent.com/assets/6583410/17752011/c781326c-64c1-11e6-9a74-1ad8905be1d6.png)

**Comment by jlord** [comment]
Hi! We have a repository for the Quick Start with a similar issue, I'll merge this issue with that one. 

👉 https://github.com/electron/electron-quick-start/issues/43

Also relevant: https://github.com/electron/electron/issues/4677
