### ISSUE TITLE
Any chance of modular build?

### ISSUE THREAD

**Issue by lyssdod** [electron/electron#6887]
* Electron version: 0.36.4
* Operating system: Gentoo Linux amd64

Hi there,

Despite I see there're some troubles in using upstream v8 version (#172), I still dare to ask if there's a chance of building electron with respect of already installed dependencies? As I see from `process.versions` (for 1.2.0), there are at least few of them which can be used as a build dependancy:

```
http_parser: '2.7.0',
node: '6.1.0',
v8: '5.1.281.47',
zlib: '1.2.8',
openssl: '1.0.2h'
```

Also while building I see it also compiles `mesa3d` library. I understand that completely separating electron from its Chromium base is very unlikely in the nearest future, but what's about tweaking gyp files to allow 'em consume external dependencies?

Thanks!

**Comment by zcbenz** [comment]
Linking with system V8 dynamically is impossible, it is very unlikely the one installed in your system is compatible with the one used by Electron, even if it is, different compilation settings will still cause crashes.

For other components we are already doing the best we can, for most components Chromium is relying on a very specific version and even has its own patches.
