### ISSUE TITLE
Support callback to shell.open* APIs that don't block

### ISSUE THREAD

**Issue by gabriel** [electron/electron#6889]
- Electron version: 1.3.3
- Operating system: macOS 10.11

`shell.openExternal` is a blocking call and can hold up the calling thread for a few seconds (depending on what app is opening).

On macOS, [NSWorkspace openURLs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWorkspace_Class/index.html#//apple_ref/occ/instm/NSWorkspace/openURLs:withAppBundleIdentifier:options:additionalEventParamDescriptor:launchIdentifiers:) is thread safe and can be called from any thread (see discussion section).

It would be nice to offer an asynchronous way to open URLs with a callback:

``` js
shell.openURL('file:///Users/blah/', options, (err, opened) => {
})
```

And then in `platform_util_mac.mm` use `dispatch_async` (on a global queue) on the `[[NSWorkspace sharedWorkspace] openURLs:...]` call.

If this makes sense, I can submit a PR.

**Comment by zcbenz** [comment]
I'm 👍 with adding a callback as long as we can keep compatibility with existing API.

**Comment by kevinsawicki** [comment]
> I'm 👍 with adding a callback as long as we can keep compatibility with existing API.

This approach would be good for `shell.openItem` as well which was brought up in https://github.com/electron/electron/issues/7210

**Comment by gabriel** [comment]
I started on this a few weeks ago, but got sidetracked.. I'll see if I can resurrect it.

**Comment by gabriel** [comment]
Have a PR started here: https://github.com/electron/electron/pull/7612

**Comment by codebytere** [comment]
Closing as https://github.com/electron/electron/pull/7612 has been merged

**Comment by mdanka** [comment]
Are you planning to implement this for `openItem` as well?
