### ISSUE TITLE
Inconsistent behaviour between node fork and electron fork

### ISSUE THREAD

**Issue by tejohnso** [electron/electron#6890]
* Electron version: 1.3.3
* Operating system: Linux

It seems there's some inconsistency between forking a background process with electron vs node.  I have a sample program [fork-test.tar.gz](https://github.com/electron/electron/files/423742/fork-test.tar.gz)

If I run with `node .` it works as expected.  The background process is forked, then it starts the target electron app and the target electron app quits gracefully. 

If I use an electron app to start with, the background process is forked from electron and when it tries to start the target app I get:

`./node_modules/electron-prebuilt/dist/electron .`
>started
forking the background launcher
background launcher running
background launcher running
launching prebuilt default app
target app running
module.js:442
    throw err;
    ^
Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

**Comment by zcbenz** [comment]
Calling `fork` in Electron would run the script in a pure Node environment which doesn't have electron APIs, and spawning Electron process in the forked script would also make Electron think it should run as Node. This behavior is to match most Node modules' expectations.

To work around this, you can remove `ELECTRON_RUN_AS_NODE` from the environment variables.
