### ISSUE TITLE
Running a binary inside asar file

### ISSUE THREAD

**Issue by rafajaques** [electron/electron#6891]
* Electron version: 1.3.3
* Operating system: OSX

Hi! I don't know if it's possible, but for me this is a little tricky.

I have a binary file inside an ASAR pack that I want to run using `child_process.exec`.
Is it possible to make an "outside" call to a binary inside the package? I mean, running `/bin/sh /path/to/asar/inside/binary`, is it possible or is there any way to achieve that?

Thanks!

**Comment by kevinsawicki** [comment]
> Is it possible to make an "outside" call to a binary inside the package? I mean, running /bin/sh /path/to/asar/inside/binary, is it possible or is there any way to achieve that?

You can only use `child_process.execFile` with binaries inside an `.asar` archive.

You'll need to include the binary in your asar unpacked folder to use `child_process.exec`.

http://electron.atom.io/docs/tutorial/application-packaging/#executing-binaries-inside-asar-archive

http://electron.atom.io/docs/tutorial/application-packaging/#adding-unpacked-files-in-asar-archive
