### ISSUE TITLE
BrowserWindow.loadURL not working in macOS 10.12 (Sierra)

### ISSUE THREAD

**Issue by dtiesling** [electron/electron#6892]
* Electron version: 1.3.3
* Operating system: macOS 10.12 Beta (16A239m)

The following code is working in El Capitan but no longer works in the Sierra beta. The app launches without errors but no page is loaded. When looking at the dev tools there is no network activity and no errors in the console.

```javascript
    mainWindow = new BrowserWindow({
        width: 1230,
        height: 830,
        backgroundColor: '#000000',
        webPreferences: {
            nodeIntegration: false
        }
    });
    mainWindow.loadURL(<URL>);
```

I'm currently using electron-packager to create and sign apps that are delivered as direct download .dmg's.

**Comment by zcbenz** [comment]
Does the default app of Electron run?

**Comment by dtiesling** [comment]
Yep, the default_app runs fine (as well as the demo app from the electron home page and the slack app). To clarify, I am attempting to load an external page in the browser and not a local file.

**Comment by dtiesling** [comment]
Aha! It is actually an issue with Chrome. For whatever reason the ssl certificate for the site is deemed invalid by Chrome in macOS 10.12 and it looks like the browserWindow silently refuses to load it. Swapping the url for one with a valid cert loads without issue.

Feel free to close this unless you would like to explore it further.

**Comment by zcbenz** [comment]
Thanks for the update, I'm closing this issue now.

**Comment by jordajm** [comment]
@dtiesling - I'm having the same issue but I don't see any ssl certificate errors when I load the URL on chrome in macOS 10.12.

Did you see certificate errors when you loaded the URL in Chrome on 10.12 or was there another way that you figured the issue?  

Thanks in advance...

**Comment by PaulRBerg** [comment]
Indeed, it was an issue with the SSL certificate. I had _https://www.example.com_, whereas it should've been _https://example.com_. Some websites configured their certificates to work with www too, others didn't.
