### ISSUE TITLE
how to auto run electron app as minimized (on tray) when windows start

### ISSUE THREAD

**Issue by wangxiexe** [electron/electron#6893]
* Electron version: 1.3.3
* Operating system: windows

I do not want my app auto run as a big windows as windows start. Is there thing I can do ? ( If I can know the app is started by system restart auto run, I can then minimized. )

I noticed the 1clipboard app listed on electron main page does auto start minimized, so there should be a way.

Thanks!

**Comment by MarshallOfSound** [comment]
Currently I don't believe this is possible with the built in Electron start at login API.

Many apps use this tool.

https://www.npmjs.com/package/node-autostart

Which allows you to pass custom arguments to the app when it launches, so you can pass `--auto-start` and read that in your app to automatically minimize itself when it launches.

In the future please ask question on the discussion forum or in slack.  GitHub is for bugs and issue reports

**Comment by MarshallOfSound** [comment]
Sorry I linked the wrong module

https://github.com/Teamwork/node-auto-launch

**Comment by wangxiexe** [comment]
thanks. but actually it does not work (see issues)

**Comment by MarshallOfSound** [comment]
@wangxiexe That's a relatively small bug and can be fixed with a simple PR.

However I worked around the issue by simply `npm install es6-promise`.  Not super difficult to work around.

**Comment by MarshallOfSound** [comment]
Also in regards to it not working, you are probably using it from a development runtime of Electron.  I.e. Launching it from `electron .` or something similar.

You need to run `.enable()` from a packaged version of your electron application or it will not work.

**Comment by wangxiexe** [comment]
Thanks @MarshallOfSound 

Yes, I did npm i es-promise and it still not work (I did run electron-builder and generated a packge), that is why I opened an issue. Does it works fine for you ? (can started as minimized ?)

**Comment by MarshallOfSound** [comment]
@wangxiexe `node-auto-launch` works for me perfectly.

As for starting minimized as mentioned before, you need to implement this yourself.  I.e. Passing an argument to `node-auto-launch` and reading that argument when starting your app and choosing to launch without showing the browser window.

**Comment by wangxiexe** [comment]
Thanks for confirm, @MarshallOfSound , I will try again. Have a gr8 day!

**Comment by dpatra** [comment]
Thanks @MarshallOfSound for the pointer.
BTW, I am using [https://www.npmjs.com/package/auto-launch](url)

The **isHidden: true** adds **--hidden** argument when it starts the application, you can do something like the following.

> var startMinimized = (process.argv || []).indexOf('--hidden') !== -1;
> 
> if (startMinimized == true){
>       console.log('App is started by AutoLaunch');
> }
> else {
>       console.log('App is started by User');
> }

**Comment by Clemens-B** [comment]
@dpatra but if you do something like this
`if (startMinimized == true){
console.log('App is started by AutoLaunch');
mainWindow.hide();
}`

it will result in the main window by blinking briefly before it got hidden again.

An other solution would be to make the app lunch in system tray by default and make your app a [single instance](https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback).

```Javascript
const shouldQuit = app.makeSingleInstance(() => {
  // Someone tried to run a second instance, we should focus our window.
  if (win) {
    win.show()
  }
});

// Don't show the window and create a tray instead
app.on('ready', () => { 
  win = new BrowserWindow({ show: false }); 
  appIcon = new Tray(iconPath);
  //show window on tray icon click etc....
})
 ```

This will start the app as minimized tray when ms-windows starts. If the user clicks on a shortcut or the .exe it will show the app window.

But as a disadvantage the user has to click twice after a fresh install / downloading the .exe to open your app...

**Comment by jadhavrani123** [comment]
I want to store ElectronNet exe in tray at the time of PC restart it is possible?

**Comment by jadhavrani123** [comment]
please give me response it is must to apply in exe

**Comment by jadhavrani123** [comment]
sir I want to close my developer tool on click cntrl + shift + I
WebPreferences = new WebPreferences
{
DevTools = false
}
I am use this code........but it not work for me

**Comment by jadhavrani123** [comment]
var menu = new MenuItem[] {

                     new MenuItem
                    {
                        Label = "Open",

                Click = async () => mainWindow = await Electron.WindowManager.CreateWindowAsync(new BrowserWindowOptions
                        {
                            Width = 900,
                            Height = 700,
            }),

      },


On minimize my exe store it work properly but problem is here  in tray icon right click open option exe open multiple items

how to remove it plase help us

**Comment by jadhavrani123** [comment]
On open click I want exe open only one time

**Comment by ali-h2010** [comment]
@Clemens-B Thanks for the excellent answer but the app icon still shows in the Dock of the mac. I would like to have the app running in the tray and quitable from there only.

**Comment by ali-h2010** [comment]
@Clemens-B 
for anyone who have the same question about the app icon on the dock, you can easily hide it by calling:
`app.dock.hide();`
