### ISSUE TITLE
multipart/form-data behaviour is different between http(s) and custom scheme

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#6894]
OS: windows 10
Electron: 1.3.1

We commonly use 2 ways to upload files in web app.

Case 1:
Use html form to upload file:
```
<form method="post" enctype="multipart/form-data">
    <input type=file name=file1>
    <input type=submit value=submit>
</form>
```

Case 2:
Use `FormData` API with xhr/fetch API to upload file or blob:
```
var fd = new FormData();
fd.append('file1', new Blob(['sssssssssss'],{type:'text/plain'}));
fetch('/', {method:'POST', body: fd });
```

**In `http` or `https` scheme**, the posted data looks like: (file content is inclued in the data)

Case 1: (file content is inclued in the data)
```
------WebKitFormBoundaryXQu5gtSQP0W0iwDC
Content-Disposition: form-data; name="file1"; filename="aaaa.txt"
Content-Type: text/plain

sssssssssss
------WebKitFormBoundaryXQu5gtSQP0W0iwDC--
```

Case 2: (file content is inclued in the data)
```
------WebKitFormBoundaryXQu5gtSQP0W0iwDC
Content-Disposition: form-data; name="file1"; filename="blob"
Content-Type: text/plain

sssssssssss
------WebKitFormBoundaryXQu5gtSQP0W0iwDC--
```

  
**BUT in custom scheme protocol**, the data in `request.uploadData` looks like: (file content is **NOT** inclued in the data)

Case 1: (file path is inclued in the data)
```
------WebKitFormBoundaryXQu5gtSQP0W0iwDC
Content-Disposition: form-data; name="file1"; filename="aaaa.txt"
Content-Type: text/plain

D:\aaaa.txt
------WebKitFormBoundaryXQu5gtSQP0W0iwDC--
```

Case 2: (blob has no path,  so no path or content is inclued in the data)
```
------WebKitFormBoundaryXQu5gtSQP0W0iwDC
Content-Disposition: form-data; name="file1"; filename="blob"
Content-Type: text/plain


------WebKitFormBoundaryXQu5gtSQP0W0iwDC--
```

Is it cuased by Chrominum ?  How can I make it wokrs as same as http(s) scheme ?

**Comment by deepak1556** [comment]
For case 1, its the expected behavior that file path is only provided, users can read from it. For case 2 its a bug, should add support for blob data.
