### ISSUE TITLE
BrowserWindow propertiy "alwaysOnTop" conflicts with event "ready-to-show"

### ISSUE THREAD

**Issue by SamXChen** [electron/electron#6898]
- Electron version: 1.3.1 32bit
- Operating system: Win7 .Net3.5/.Net4.6

Hello,

I've found a serious problem in some machines running on win7.

Details:
1. create a browserWindow: alwaysOnTop: true, show: false 
2. browserWindow : add event "ready-to-show" => window.show()
3. browserWindow loads a url to open a website

In some machines running on win7 .Net4.5, win10, win8 or win7 64bit, above actions can be run correctly.

But in some machines running on win7 .Net3.5/.Net4.6, I've found the window could never be shown in the screen.

Plus:
If I remove "alwaysOnTop: true" while creating a window, the window can always be shown.

Please take a look and let me know if any problem. Thanks.

**Comment by samuelyeshua** [comment]
I have a similar problem in here...i'm using a "ready-to-show" event on window but it never occurred, except if the node integration is set to the false

**Comment by zcbenz** [comment]
What does `win.isVisible()` return for those windows?

**Comment by SamXChen** [comment]
It returns ture for those windows.

**Comment by zcbenz** [comment]
I'm merging this to #7779.
