### ISSUE TITLE
[feature request] name property of Display object

### ISSUE THREAD

**Issue by zh99998** [electron/electron#6899]
* Electron version: latest
* Operating system: windows

http://electron.atom.io/docs/api/screen/

>- display object
>  - id Integer - Unique identifier associated with the display.
>  - rotation Integer - Can be 0, 90, 180, 270, represents screen rotation in clock-wise degrees.
>  - scaleFactor Number - Output device’s pixel scale factor.
>  - touchSupport String - Can be available, unavailable, unknown.
>  - bounds Object
>  - size Object
>  - workArea Object
>  - workAreaSize Object

then there is no way to get display name now.
in C# `Screen` class there is a `DeviceName` property

https://msdn.microsoft.com/en-us/library/system.windows.forms.screen.devicename(v=vs.110).aspx

**Comment by zcbenz** [comment]
The `id` property is a hash value of the `DeviceName` and should be used instead, the `DeviceName` itself is not a meaningful string and may even not be printable.

**Comment by funwithtriangles** [comment]
So is it not the case that `DeviceName` would give use the option to displays meaningful names such as "DELL Ultrasharp" or "Built in display"? What would it take to have access to strings like this?

Right now the only identifier I have for displays is their resolution, which sometimes can be the same!
