### ISSUE TITLE
Allow settings of custom exe and arguments when using the setLoginItem API

### ISSUE THREAD

**Issue by wmnnd** [electron/electron#6901]
Hi there,

Windows does not supply an application with information on whether or not it was launched on system start. This is why on Windows, you would typically set up the automatic launch of an application in such a way that a parameter is passed to the application that notifies it of being launched in this specific way (e. g. instead of storing "/path/to/app.exe" in the registry, you’d store "/path/to/app.exe --onlogin").

Do you think Electron should support automatically appending such a parameter in order to determine `wasOpenedAtLogin` on Windows (and potentially other systems) or would this be infringing with developers’ ability to determine their own parameter structure too much?

Maybe a better way would be to allow passing custom arguments to app.setLoginItemSettings (like `app.setLoginItemSettings({loginArguments: '--onlogin'})`) so that developers can set up their own fallback solutions for systems that do not support `wasOpenedAtLogin` natively.

What’s your take on this?

**Comment by MarshallOfSound** [comment]
@wmnnd Once #6858 has been merged there will be a standard for this kinda of feature.  It was actually mentioned in that PR

https://github.com/electron/electron/pull/6858#issuecomment-240194279

I'll take this one on once my PR has been merged.
