### ISSUE TITLE
Support all standard chromium process models

### ISSUE THREAD

**Issue by krillr** [electron/electron#6903]
By default Electron appears to use the process-per-site-instance process model. It would be best to allow developers to choose between the available models, for example I would much like to use the single-process model while others would likely prefer the process-per-site model. Enabling the command-line switch for this setting in chromium would be ideal.

**Comment by sedwards2009** [comment]
Electron has a main process which is roughly just nodejs and it can create new windows which have a process each. That is the whole model. The concept of 'site' or 'per site' doesn't make much sense here as Electron isn't oriented around showing sites like a web browser.

**Comment by krillr** [comment]
From what I understood, Electron is a wrapper around libchromiumcontent, which in turn handles all the windows -- Electron just makes calls into the chromium instance to create BrowserWindows, and BrowserWindows are just nodejs objects bound to chromium windows.

Is that incorrect?

**Comment by sedwards2009** [comment]
It is windows with nodejs support and some other Electron APIs baked. But yes, you're description @krillr sounds about right.

**Comment by krillr** [comment]
So what I'm requesting is that libchromium be configurable to use any one of its many process models. In Electron's current state, libchromium uses its default process-per-site-instance model. Every time a dialog is opened, a new window is spawned, etc -- a new process is spawned to render that window. This makes sense in the context of a web browser, but leads to unnecessary memory usage in a desktop application. Making this configurable would allow those of us whose apps don't need advanced security models like process-per-site-instance to optimize our applications.

**Comment by paulcbetts** [comment]
Single process model doesn't work with node.js and is also super busted / bitrotted

**Comment by krillr** [comment]
Ok, well the process-per-site model would work just as well, and it is fully supported by chromium.

**Comment by krillr** [comment]
Huh, I guess passing the relevant chrome options to electron "just works" -- not sure why I didn't just try that. Closing this

**Comment by zcbenz** [comment]
The process model in Electron is different from any process model in Chromium, the renderer process is forced to restart for every navigation, otherwise leaks would happen. This is because Node is currently designed to have only one instance in one process, and it doesn't cleanup all the resources one JavaScript environment is destroyed.

I'm closing this as won't fix since current process model is restricted by the design of Node.

**Comment by krillr** [comment]
If that's the case, how come the flag "--process-per-site" works fine -- it
just isn't documented?

**Comment by paulcbetts** [comment]
@krillr I suspect it doesn't actually work fine - if you tried:

1. Create two windows pointed at the same site
1. require a native node module in one
1. try to require that module in the 2nd window

This would blow up

**Comment by krillr** [comment]
It doesn't blow up, but it does stop JS execution in the second window.
Interesting...

**Comment by ahmedmohamedali** [comment]
Hi @zcbenz ,

It isn't possible to have chromium process model in sandboxed renderers ?
Thanks.

**Comment by bughit** [comment]
>  the renderer process is forced to restart for every navigation, otherwise leaks would happen

@zcbenz Is that still necessary when node integration is off?
