### ISSUE TITLE
<webview> resizing is laggy

### ISSUE THREAD

**Issue by poiru** [electron/electron#6905]
When resizing a window containing a `<webview>` spanning e.g. 100% width/height, there is a noticeable delay until the `<webview>` resizes. With the example below, the red background of the page should ideally never be visible when resizing.

This happens on at least macOS and makes resizing e.g. mozilla/tofino and brave/brave-desktop windows quite janky.

@zcbenz, any thoughts?

**index.js:**
```
'use strict';

const {app, BrowserWindow} = require('electron');
const path = require('path');

app.on('ready', () => {
  const win = new BrowserWindow({
    width: 500,
    height: 500,
    webPreferences: {
      nodeIntegration: true
    },
  });
  win.loadURL('file://' + path.join(__dirname, 'index.html'))
});
```

**index.html:**
```
<!DOCTYPE html>
<html>
<style>
html, body, webview {
  flex: 1;
  margin: 0;
  width: 100%;
  height: 100%;
}

body {
  background-color: red;
}
</style>
<body>
<webview src="https://github.com" autosize="on"></webview>
</body>
</html>
```

**Comment by zcbenz** [comment]
This is determined by how webview works and you can observe the same problem in Chrome browser when writing extensions or Chrome apps, and I suggest reporting this to Chromium's issues list instead.

I'm closing this since we are unable to solve this on Electron's side.

**Comment by poiru** [comment]
Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=639867
