### ISSUE TITLE
Electron - starter problems

### ISSUE THREAD

**Issue by TSM696** [electron/electron#6909]
Hi

 Just started exploring electron - but ran into this problem:
----
> electron ./index.js

require
App threw an error during load
TypeError: core.require is not a function
    at Object.<anonymous> (/Users/m/electron-apps-ex/node_modules/app/lib/App.js:10:18)
    at Object.<anonymous> (/Users/m/electron-apps-ex/node_modules/app/lib/App.js:356:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/m/electron-apps-ex/node_modules/app/lib/index.js:3:29)
----
when executing this code: index.js:
----
var app = require('app');
var BrowserWindow = require('browser-window');

var mainWindow = Null;
app.on('ready', function(){
var mainWindow = new BrowserWindow({
 width:800, height: 600
 })

 mainWindow.loadUrl('file://Users/m/electron-apps-ex/index.html')

});
------

Several times tried re-installing a clean electron as well as electron-prebuilt (apart from node itself)
$npm install electron-prebuilt --save
----

What could be the problem? Configuration? Installation?

Many thanks in advance
(Yes, newbie to both js & electron)

* Electron version: "electron-prebuilt": "^1.3.3"
* Operating system: MacOS X El Capitan  Ver 10.11.6

**Comment by MarshallOfSound** [comment]
Hey there,

Questions and support request should go on the discussion forums or in slack.  Github is for issues only.

There are a lot of things *wrong* with your code, I've fixed a few of them below and tried to explain.

```js
// Electron modules are properties of the top level Electron module
var app = require('electron').app;
var BrowserWindow = require('electron').BrowserWindow;

// Null --> null (lowercase)
var mainWindow = null;
app.on('ready', function(){
var mainWindow = new BrowserWindow({
width:800, height: 600
})

mainWindow.loadUrl('file://Users/m/electron-apps-ex/index.html')
```

It might be a good idea for you to check out https://github.com/electron/electron-quick-start for a good place to start

**Comment by TSM696** [comment]
Thanks @MarshallOfSound 

Was following the code example used by Kyle in https://www.youtube.com/watch?v=ojX5yz35v4M
given in this: http://electron.atom.io/community/#boilerplates

Guess it is a bit dated. (request that such a caveat be added to that list of videos)

Yes, it works!  Electron rocks!
Thanks a lot for the quick response.
