### ISSUE TITLE
windows xp not running

### ISSUE THREAD

**Issue by jimtang9527** [electron/electron#691]
in windows xp.run atom.exe,message tip:not a valid Win32 program

**Comment by lygstate** [comment]
Where is the hard part to getting atom-shell to support for XP?

**Comment by lygstate** [comment]
At least, io.js still support for XP
https://github.com/iojs/io.js/commit/e8d08503c7821e8c92e9fa236ed7328e9bdfe62a

**Comment by thomasjo** [comment]
@lygstate Atom Shell is built on top of Chromium/Chrome, for which Windows XP support will cease next month (April 2015): http://chrome.blogspot.com/2013/10/extending-chrome-support-for-xp-users.html. After that point there is no guarantee that it will continue working on XP.

It simply isn't worth the effort. It's an almost 14 year old operating system. It reached *end of life* in April last year.

**Comment by lygstate** [comment]
Thanks, @thomasjo , I know the deadline, but it's worth for me, please do some help.

**Comment by paulcbetts** [comment]
At the moment Atom Shell is Win7 or higher, because it calls into Touch-specific APIs that don't exist in Vista. I don't think XP is a reasonable request in 2015, sorry.

**Comment by lygstate** [comment]
@paulcbetts  Thanks, I'v already found those API that lost, I can disable those things optionally.

**Comment by thedaniel** [comment]
I'm sorry - XP support isn't on the table. Going to lock this issue now.
