### ISSUE TITLE
Add filetype option to dialog.showSaveDialog modal

### ISSUE THREAD

**Issue by callodacity** [electron/electron#6910]
* Electron version: 1.3.3
* Operating system: macOS

**enhancement / feature-request**

For apps that save files with specific extensions, or specific filetypes, perhaps adding an option of `defaultFileName` or `defaultFileExtension` could be an option?

Right now whenever `dialog.showSaveDialog` is called, the file to save is always `Untitled`.

<img width="426" alt="screen shot 2016-08-20 at 22 48 05" src="https://cloud.githubusercontent.com/assets/1011648/17831306/35eafbe4-6728-11e6-9ecf-bb16b6503764.png">

This way the user would understand what type of file they're meant to be saving.

e.g.,  

<img width="426" alt="screen shot 2016-08-20 at 22 50 55" src="https://cloud.githubusercontent.com/assets/1011648/17831319/92a3866c-6728-11e6-823e-9248624f693e.png">

**Comment by zcbenz** [comment]
You can use the `defaultPath` option.
