### ISSUE TITLE
(reading files issue) ENOENT: no such file or dicrectory - fs:js.640

### ISSUE THREAD

**Issue by shuliandre** [electron/electron#6911]
* Electron version: 1.3.3
* Operating system: Ubuntu Linux 16.04 LTS

Hi, I am trying to read a `json` file using NodeJS's `fs` module. The path is correct, but when the app runs, it could not find the file.

Here is the block of code in a file called `index.js`:
```
// index.js
const fs = window.require('fs');
const path = window.require('path');

// get configuration file
const data = fs.readFileSync(path.join(__dirname, 'config.json'), 'utf8');
const config = JSON.parse(data);
```

Here is my app's structure:
![screenshot from 2016-08-20 19-58-49](https://cloud.githubusercontent.com/assets/19518296/17831354/9faa8c9c-6710-11e6-94a4-6743d7ee223c.png)

The BrowserWindow then responded with this:
![screenshot from 2016-08-20 20-00-59](https://cloud.githubusercontent.com/assets/19518296/17831364/de998ef8-6710-11e6-9eaa-3a123e2d9d43.png)

`fs:js.640` then pointed to this:
![screenshot from 2016-08-20 20-03-09](https://cloud.githubusercontent.com/assets/19518296/17831373/25a2b928-6711-11e6-8a5d-cc645d0033b2.png)

I know this sounds like a problem with NodeJS, but I got the same code working outside of the app.
I hope this can be fixed, thanks in advance! :)

**Comment by vsemozhetbyt** [comment]
@shuliandre Do you use the same version of Node in Electron and in outside testing? There was some [big fs fix](https://github.com/nodejs/node/pull/7899) in the last Node. BTW, is your app in somehow virtual drive? This also can cause problems for Node older than 6.4.0

**Comment by enlight** [comment]
I'm guessing `__dirname` is an empty string because you're using Webpack or something like it.

FYI, GitHub issues are for bug reports and feature requests, for everything else see the [community](https://github.com/electron/electron#community).

**Comment by shuliandre** [comment]
@vsemozhetbyt Hi, the current version of NodeJS on my machine is 6.4.0. I'm not sure how I can check its version in Electron though, can you suggest a way for me to do it? Thanks :smile:
@enlight Yes I am using Webpack, but even if I only specify the path as `path.join('config.json', 'utf8');`, it still wouldn't work :smile: And yes I knew about the Electron community, Slack is my prefered choice but I haven't used it much, I will try to use the community more often :smile: Thanks for your reply :smile:

**Comment by shuliandre** [comment]
@vsemozhetbyt Oh I checked the Node version in Electron and it's currently 6.3.0, is there a way for me to upgrade to the latest version?

**Comment by vsemozhetbyt** [comment]
@shuliandre I am afraid not untill the Electron upgrade it. But we are not sure this is the issue yet. So is your app in the virtual drive?

**Comment by shuliandre** [comment]
@vsemozhetbyt No I am not using a virtual drive, I only use `webpack-dev-server` and start the server and the app separately (through 2 Terminal).

**Comment by MarshallOfSound** [comment]
@shuliandre The issue is probably due to how webpack inlines `__dirname`

However as @enlight said

> FYI, GitHub issues are for bug reports and feature requests, for everything else see the community.

If you need help check out the discussion forums or Slack

**Comment by shuliandre** [comment]
@MarshallOfSound Okay, thanks for your support! :+1:

**Comment by MarshallOfSound** [comment]
@shuliandre FYI

https://github.com/webpack/webpack/issues/1599

**Comment by shuliandre** [comment]
@MarshallOfSound Oh so that was the issue, this is the first time I encounter it :smile: Thanks Samuel! :+1:
