### ISSUE TITLE
Use registerBufferProtocol to overwrite existing protocol schemes

### ISSUE THREAD

**Issue by markwylde** [electron/electron#6912]
**My goal:**
My goal is to implement my own protocol to replace the *http* and *https* schemes. When you goto https://www.example.com instead of actually going to example.com I would like to just return `<h1>Example</h1>`

**My working attempt with custom protocol handler:**
I almost got there by using the code from the documentation:
```javascript
protocol.registerBufferProtocol('atom', (request, callback) => {
  callback({mimeType: 'text/html', data: new Buffer('<h1>Example</h1>')})
}, (error) => {
  if (error) console.error('Failed to register protocol', error)
})
```
Really happy, but I have to use the protocol **atom:**

**My none-working attempt with replacing handlers:**
So since I got it working previously I thought I would try and use http instead of atom for the protocol handler:

```javascript
protocol.registerBufferProtocol('http', (request, callback) => {
```

But when I do this I get the following error:
```shell
Failed to register protocol Error: The scheme has been registred
    at Error (native)
```

This makes perfect sense as http and https are registered by default. So my next attempt was to unregister the http handlers. (As explained in the docs)

```javascript
protocol.unregisterProtocol('http')
```

This makes my final code look like:

```javascript
app.on('ready', () => {
    protocol.unregisterProtocol('http', () => {
        protocol.registerBufferProtocol('http', (request, callback) => {
          callback({mimeType: 'text/html', data: new Buffer('<h5>Response</h5>')})
        }, (error) => {
          if (error) console.error('Failed to register protocol', error)
        })
    })
})
```

Unfortunately it returns the error:
```shell
Failed to register protocol Error: The scheme has been registred
```

**My question:**
Is there any way I can unregister the default http/https handlers and replace them with my own?

Thank you for any help you can provide!

**Comment by deepak1556** [comment]
use `intercept[File/String/Http/Buffer]Protocol` api to setup handlers for pre-registered schemes.
