### ISSUE TITLE
[Question] JavaScript -> click() not called after in ipc.on()

### ISSUE THREAD

**Issue by StefMa** [electron/electron#6914]
* Electron version: 1.3.3
* Operating system: OS X El Capitan 10.11.6

I am a really beginner in JS overall and Electron. So I don't know if this is really a bug or just standard JS stuff.
However. My goal is to trigger a simple `<input type="file" id="test">` with the JS `click()` method from `mainRenderer`. 
For testing I've created these simple website:
```html
<!-- Header stuff -->
<body>
  <input type="file" id="test">
  <button id="myButton" >
  <script>
    window.onload = function() {

      document.getElementById("myButton").onclick = function() {
        document.getElementById("test").click();
      }

      // Listen for main events
      const ipc = require('electron').ipcRenderer
      ipc.on('clicky' , function(event , data) {
        console.log("ShouldBeCalled");
        document.getElementById('test').click();
      });
      
    }
  </script>
</body>
```
The idea was that when I send an event to the website the `<input>` gets triggered and open the file explorer. But that doesn't happen! The only thing what happen is the output to the console.

This is my code from the `mainRenderer`
```javascript
let loadingWin = new BrowserWindow({width: 250, height: 40, frame: false, x: xPosition, y: yPosition, resizable: true, moveable: false})
loadingWin.loadURL(`file://${__dirname}/upload.html`)
loadingWin.webContents.openDevTools()
loadingWin.webContents.on('did-finish-load', () => {
loadingWin.webContents.session.clearCache(function(){
  //some callback.
});
loadingWin.webContents.send("clicky", "someData")
```

I've tested it with `webContents.executeJavaScript()` too. But the `<input>` isn't triggered.

The funny (or bad? 💭) part is, that if I click manually on the `<button>` the `<input>` gets called and the file explorer open...

**Comment by MarshallOfSound** [comment]
This is a security policy inside Chromium.

A file input can't be "clicked" on through JS unless it was triggered from a user interaction.  The workaround for this inside electron is to use the `userGesture` parameter of the `webContents.executeJavaScipt` method.

https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsexecutejavascriptcode-usergesture-callback
