### ISSUE TITLE
PPAPI Flash player does not load. (Electron 1.3.3, Windows 8.1 x64)

### ISSUE THREAD

**Issue by KirillGrigoriev** [electron/electron#6917]
Electron 1.3.3, 1.0.0, 0.37.8 (x32 and x64), Microsoft Window 8.1 (x64).

"package.json":
```
{
	"main": "main.js",
	"name": "ppapi-flash-testapp",
	"version": "1.0.0"
}
```
"main.js":
```
"use strict";
const
    electron = require('electron'),
    app = electron.app,
    BrowserWindow = electron.BrowserWindow;
app.on('ready', function() {
    if (process.arch == 'ia32') {
        app.commandLine.appendSwitch('ppapi-flash-path', __dirname + '\\pepflashplayer32_17_0_0_169.dll');
    } else {
        app.commandLine.appendSwitch('ppapi-flash-path', __dirname + '\\pepflashplayer64_17_0_0_169.dll');
    }
    app.commandLine.appendSwitch('ppapi-flash-version', '17.0.0.169');

    var win = new BrowserWindow({
        height: 650, width: 900,
        'web-preferences': {'plugins': true}
    });
    win.loadURL('http://isflashinstalled.com/');
});
```
All paths is absolute. I try to use "web-preferences" and "webPreferences" option, result is the same. Also, I tried to use newer version of ppapi flash player, and it's also not working.
![-1](https://cloud.githubusercontent.com/assets/3006659/17836332/a1dc9e26-67b8-11e6-99cd-aeee5c3f42f5.jpg)
![-2](https://cloud.githubusercontent.com/assets/3006659/17836339/e7abc530-67b8-11e6-81cd-85f9ba5705b2.jpg)

**Comment by vsemozhetbyt** [comment]
[As I see here](http://electron.atom.io/docs/tutorial/using-pepper-flash-plugin/) `app.commandLine.appendSwitch` should be called before `app.on('ready')`. Could you try this way?

**Comment by KirillGrigoriev** [comment]
Yes, it's work. Big thanks. I did not think in this direction when looking for a solution.
