### ISSUE TITLE
Devtools extension: Cerebral Debugger not working

### ISSUE THREAD

**Issue by TomKaltz** [electron/electron#6918]
* Electron version: 1.3.3
* Operating system: OSX 10.11.6

https://chrome.google.com/webstore/detail/cerebral-debugger/ddefoknoniaeoikpgneklcbjlipfedbb

This devtools extension doesn't work on my machine.  I can get the extension to load but they must be using an api that is currently unsupported in Electron.

Code is here https://github.com/cerebral/cerebral-debugger

They are using ```eval``` I believe?  @christianalfoni can you provide any info regarding the chrome API you're using in the extension?

**Comment by MarshallOfSound** [comment]
@TomKaltz There should be errors in the console if the extension is attempting to use API's that do not exist.  Can you look there so we have a better idea of what API's are being used?

**Comment by TomKaltz** [comment]
I am getting no errors in console.  The extension loads but never connects to the devtools module in my electron app.

**Comment by TomKaltz** [comment]
Is there any way to open a devtools panel for this specific devtools extension?

**Comment by christianalfoni** [comment]
The only thing the Cerebral devtools module does is trigger events on the `window`. These events are picked up by the backround script of the chrome extension and passed into the debugger. So there are only a few things that can affect this I believe:

1. `window.dispatchEvent` does not work?
2. Electron does not allow chrome extensions to inject scripts?
3. Electron somehow makes `process.env.NODE_ENV === 'production'`, which is very unlikely ;-)

I would believe that second is the case, or at least the area of where the problem happens. 

One thing to check for in the debugger is `__CEREBRAL_DEVTOOLS_GLOBAL_HOOK__`. If it is not there something wrong happened injecting the script. This is the code that does it:

```js
  function initializeHook(window) {
    Object.defineProperty(window, '__CEREBRAL_DEVTOOLS_GLOBAL_HOOK__', {
      value: {
        signals: {}
      }
    });
  }

  var js = (
    ';(' + initializeHook.toString() + '(window))'
  );

  // This script runs before the <head> element is created, so we add the script
  // to <html> instead.
  var script = document.createElement('script');
  script.textContent = js;
  document.documentElement.appendChild(script);
  script.parentNode.removeChild(script);
```

**Comment by christianalfoni** [comment]
An other thing might be the `manifest` of the chrome extension. It requires some permissions: 

```js
    "permissions": [
        "tabs",
        "http://*/*",
        "https://*/*"
    ],
```

Maybe there is some other permission required for electron?

**Comment by christianalfoni** [comment]
This is also interesting: https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md

**Comment by christianalfoni** [comment]
And this: https://github.com/GPMDP/electron-devtools-installer

**Comment by TomKaltz** [comment]
Electron is now supported as of version 0.58 of the Cerebral Debugger.
[Cerebral Debugger in Chrome Web Store](https://chrome.google.com/webstore/detail/cerebral-debugger/ddefoknoniaeoikpgneklcbjlipfedbb)
[Cerebral Debugger Documentation](http://www.cerebraljs.com/documentation/the_debugger)
