### ISSUE TITLE
WebView.getWebContents is undefined

### ISSUE THREAD

**Issue by jnugh** [electron/electron#6920]
* Electron version: 1.3.3
* Operating system: Ubuntu Linux 16.04

When embedding a `WebView`, `getWebContents` returns `undefined` when being called on window load. I'm not sure if this is an actual bug or just a lack of documentation.

The [documentation](https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md#webviewgetwebcontents) does not mention anything related as far as I can tell.

To verify this issue, I used this [index.html](https://gist.github.com/jnugh/db1be12bf3f12128fd84c8468748dfaf) in `electron-quick-start`

```html
<!--[...]-->
  <script>
    window.addEventListener('load', () => {
      var webview = document.getElementById('testview');
      console.log('window load: ', webview.getWebContents()); //undefined

      webview.addEventListener('dom-ready', () => {
        console.log('webview dom-ready: ', webview.getWebContents()); //Object
      });
    });
  </script>
<!--[...]-->
```

**Comment by zcbenz** [comment]
The methods have to be used after the webview is loaded as documented:

> Note: The webview element must be loaded before using the methods.
