### ISSUE TITLE
Problem with file drag&drop

### ISSUE THREAD

**Issue by Trixt0r** [electron/electron#6921]
* Electron version: v1.3.3
* Operating system: Windows 10 x64

I installed electron via `npm install electron -g`.
Running my app with `electron myApp` causes the app to ignore `dragover`, `dragleave`, etc. events for files, i.e. I can not drop any files into my app anymore.
Executing my app with an electron executable from an unpacked zip file, dropping files into my app, works without any problems.

Would be nice if you can fix this.

-Trixt0r

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by Trixt0r** [comment]
The default electron app is one.

**Comment by MarshallOfSound** [comment]
@Trixt0r I launched the default Electron app and run the following code in devtools

```js
window.ondragover = console.warn.bind(console)
```

And then dragged a file over the main window,  my console with flooded with messages so as far as I am concerned this works.  Can you please provide an app the demonstrates this issue as the default app does not.

**Comment by Trixt0r** [comment]
@MarshallOfSound Did you run electron (installed via npm) on Windows 10 from command line?

**Comment by MarshallOfSound** [comment]
Yes.

**Comment by Trixt0r** [comment]
Looks like it has something to do with the rights. If I execute electron withtout admin rights by removing **Run as administrator** in the compatibility options of the executable, the events gets triggered.

Why is that?

**Comment by enlight** [comment]
Probably because:

> Lower-integrity processes can't pass messages to higher level ones.

Source: https://superuser.com/questions/507096/cant-drag-files-from-explorer-into-notepad-running-as-administrator-on-window

**Comment by MarshallOfSound** [comment]
Good catch @enlight 

This seems to be a "cant fix"
