### ISSUE TITLE
Dialog showSaveDialog not working

### ISSUE THREAD

**Issue by acuemor** [electron/electron#6927]
* Electron version: 1.3.3
* Operating system: Ubuntu 14.04

I want to save a XML object into a .xml file with Electron. I try this:

`const {dialog} = require("electron").remote;
 dialog.showSaveDialog(myObj)` 

A new windows is opening, I fill the name of the file but nothing has been saving.
![Error](https://cloud.githubusercontent.com/assets/9961207/17852987/65427fb4-686a-11e6-8f95-bc248cc00cac.png)

**Comment by enlight** [comment]
> but nothing has been saving

Can you show the relevant code?

**Comment by acuemor** [comment]
There is no relevant code. That is all that I have, an "myObj" object with the content I want to save in .xml file format.

Maybe showSaveDialog really does not create any file, but only displays a window to select the save path?

I need to do my own stuff ?

`dialog.showSaveDialog(
                            { defaultPath: "/home/user/" },
                            function(fileName) {
                                // Do my stuff here
                            });`

**Comment by enlight** [comment]
Yes, creating the file is your responsibility, the dialog doesn't have a clue what to put in the file (and creating an empty one would be quite pointless).
