### ISSUE TITLE
Is it possible to handle keyboard shortcut(CtrlorCommand+= and CtrlorCommand+-) to zoom in and zoom out the electron app?

### ISSUE THREAD

**Issue by nishant09** [electron/electron#6930]
* Electron version: 0.34
* Operating system: windows and mac osx

I want to have an ability in my electron app to use keyboard shortcuts(CtrlorCommand+= and CtrlorCommand+-) to zoom in and zoom out. 

Is this possible ? if so, then it would be great if you can tell how ? 

note: this should make sure when zoom in, the scroll bar appears to see the content outside of the screen display area.

Thanks !

**Comment by kevinsawicki** [comment]
There are menu item roles for this `zoomin`, and `zoomout`, and `resetzoom`, http://electron.atom.io/docs/api/menu-item/#new-menuitemoptions

They were added in `1.3.3`.

You can also implement custom zooming yourself, you might want to take a look at https://github.com/electron/electron/pull/6677 for more details.

**Comment by nishant09** [comment]
Thank you for your quick response. this is helpful
