### ISSUE TITLE
Separate each API into its own doc

### ISSUE THREAD

**Issue by zeke** [electron/electron#6931]
@kevinsawicki and I are pairing on a docs parser. The `session.md` file is quite long, and might be easier to parse/maintain/read if each API was broken out into its own file:
- `session.md` (exists already)
- `web-request.md`
- `cookies.md`

@zcbenz what do you think of this?

**Comment by felixrieseberg** [comment]
I think that's a good idea. I'd even go one step further and implement a rule for us to always use the same formatting - that way, we can easily link between them without thinking about it. It'd be nice to *know* that I can just write `[browser-window.md#show()]`.

**Comment by zeke** [comment]
> It'd be nice to *know* that I can just write `[browser-window.md#show()]`.

We are approaching a level of consistency in the docs that will allow for this, but you would still have to familiarize yourself with how GitHub generates DOM ids from headings, e.g. `win.show()` becomes `#winshow`

**Comment by zcbenz** [comment]
It is definitely a good thing, we already separated a few docs like `DownloadItem`.
