### ISSUE TITLE
Windows 10 scaling and BrowserWindow positioning behaviour

### ISSUE THREAD

**Issue by Bram-Zijp** [electron/electron#6933]
* Electron version: 1.3.3
* Operating system: Windows 10

I use 2 monitors:
4K scaled 1.5,
1080P scaled 1.0

As seen in the object below both displays appear to have a scaleFactor of 1.5. The width/height of the 4K monitor is divided by 1.5. Positioning a browser window uses native 4K bounds.

objects i get when using  screen.getAllDisplays();

```

   {
        "id": 2779098405,
        "bounds": {
            "x": 3840,
            "y": 0,
            "width": 1920,
            "height": 1080
        },
        "workArea": {
            "x": 3902,
            "y": 0,
            "width": 1858,
            "height": 1080
        },
        "size": {
            "width": 1920,
            "height": 1080
        },
        "workAreaSize": {
            "width": 1858,
            "height": 1080
        },
        "scaleFactor": 1.5,
        "rotation": 0,
        "touchSupport": "unknown"
    }
```
   ```
 {
        "id": 2528732444,
        "bounds": {
            "x": 0,
            "y": 0,
            "width": 2560,
            "height": 1440
        },
        "workArea": {
            "x": 0,
            "y": 0,
            "width": 2560,
            "height": 1400
        },
        "size": {
            "width": 2560,
            "height": 1440
        },
        "workAreaSize": {
            "width": 2560,
            "height": 1400
        },
        "scaleFactor": 1.5,
        "rotation": 0,
        "touchSupport": "unknown"
    }
```

**Comment by Bram-Zijp** [comment]
When using 'Window Spy' i measure that all my displays have a size of native*1.5.

When giving X/Y cords to position a Electron BrowserWindow it works like this:

### **monitor = 3840x2160@1.5scaling**

**Situation as if my monitor is 2560x1440** 
positions it all the way in the upper right corner. (like this: http://imgur.com/ZkBrmVg)
```
BrowserWindow({
	width:560, height:730,
	x: 2000, y: 0,
	frame: false
});
```

**situation as if my monitor is 3840x2160**
(like this: http://imgur.com/7gQZoKT)  everything in between x:2000 and x:2282 will position it in between 2 monitors. 560/2=280 so that makes sense

```
BrowserWindow({
	width:560, height:730,
	x: 2282, y: 0,
	frame: false
});
```

positioning it on the 1080p monitor that has no scaling works fine (http://imgur.com/Nc5YvUX)
```
BrowserWindow({
	width:560, height:730,
	x: 3840+1920-560, y: 0,
	frame: false
});

```

**Comment by paulcbetts** [comment]
This is because Chromium does not yet support per-monitor DPI, and is using System DPI (i.e. pre Win8.1, where all monitors had the same DPI). This is coming to Chromium soon and Electron will pick it up.

**Comment by cl4ws0n** [comment]
Is it me, or this still broken?
