### ISSUE TITLE
Support chrome.usb API

### ISSUE THREAD

**Issue by koush** [electron/electron#6937]
I noticed there was a similar issue opened to this on the desktopCapture API which was ported from Chrome. Any chance of also porting the chrome.usb APIs? Hopefully it is trivial to pull in.

https://developer.chrome.com/apps/usb

Apologies if this is not the appropriate place to request a feature.

@paulcbetts

**Comment by paulcbetts** [comment]
This is the right place - it's probably doable but I bet this API is a shitton of code :-/

**Comment by koush** [comment]
Cool. I'll give this a stab.

**Comment by onlykey** [comment]
Any luck you could also include chrome.hid it should be easier than chrome.usb https://developer.chrome.com/apps/hid

**Comment by fanchou** [comment]
I think electron need support all chrome.* API like nwjs. then we can do more things like a really desktop app

**Comment by limpkin** [comment]
would anyone know if there's a node wrapper (or electron support) for chrome.hid indeed?

**Comment by Arti3DPlayer** [comment]
+1

**Comment by zhouzr** [comment]
+1

**Comment by nedex** [comment]
+1

**Comment by nedex** [comment]
Still a problem in 3.0.0-beta.1

**Comment by codebytere** [comment]
Given that this is likely better off in userland, and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!
