### ISSUE TITLE
Ambiguous default value for nodeintegration in <webview>

### ISSUE THREAD

**Issue by nikola** [electron/electron#6939]
- Electron version: 1.3.3
- Operating system: all

In

`docs/api/web-view-tag.md`

it reads:

> `<webview src="http://www.google.com/" nodeintegration></webview>`
> If "on", the guest page in webview will have node integration and can use node APIs like require and process to access low level system resources.

The phrasing in the description implies that if the `nodeintegration` attribute is not explicitly set on the tag, then the `<webview>` won't have node integration.

However, in

`docs/tutorial/security.md`

it reads:

> WebViews: Set nodeintegration to false

This should be clarified in the documentation. Also, valid attribute values should either be `[true, false]` or `[on, off]`, not a mix as stated above. More generally, there should be exactly one way to set security properties, and all others should throw an error. As of 1.3.3, I can write `<webview nodeintegration="nada">`, this won't throw an error or warning, and it's not immediately clear if the value evaluates to truthy or not.

**Comment by andymartinwork** [comment]
It is rather confusing.

Do webviews automatically have nodeintegration set to false?
If not, how is that done?

**Comment by jainmukul** [comment]
`docs/api/browser-window.md`

Says: 
> nodeIntegration Boolean - Whether node integration is enabled. Default is true.

It means by including nodeintegration attribute, by default it will value will be ture. But we can set it to false by doing nodeintegration="false".

As there is no, on/off so it should not work.

And about <webview nodeintegration="nada">, I have a doubt how to check with nodeintegration is working or not.

I will edit and submit a pull request soon for the same.

**Comment by jainmukul** [comment]
There are many attributes which are true by default like nodeintegration, shouldn't we write a common note for all or should write a individual note for each ?
