### ISSUE TITLE
Do not convert ArrayBuffer to Array in remote module

### ISSUE THREAD

**Issue by koush** [electron/electron#6942]
* Electron version:
1.3.3
* Operating system:
OSX El Capitan

https://github.com/electron/electron/blob/master/lib/renderer/api/remote.js#L33

remote.js converts the ArrayBuffer or Buffer into an array. Not familiar with the IPC wire protocol, is it binary or JSON under the hood?

**Comment by kevinsawicki** [comment]
> is it binary or JSON under the hood?

JSON

**Comment by paulcbetts** [comment]
This is surprising to me, didn't we special-case Buffers to be sent directly via IPC?

**Comment by zcbenz** [comment]
The `ipc` modules do have the ability to send Buffers in binary format, we are not making use of it in the `remote` module.

**Comment by f3z0** [comment]
Just ran into this bug (and it hurt). Really glad this is fixed, well done :)
