### ISSUE TITLE
autoUpdater.checkForUpdates() - throws Error - Invalid JSON response

### ISSUE THREAD

**Issue by jschimmoeller** [electron/electron#6951]
* Electron version: 1.3.4
* Operating system: MacOS El Capitan 10.11.5

Electron Release Server 

Uncaught Exception:
Error: Update check failed. The server sent an invalid JSON response. Try again later.
    at Error (native)

executing call via browser returns:
{"url":"/download/2.5.1/osx_64?filetype=zip","name":"2.5.1","notes":"","pub_date":"2016-08-23T20:25:45.000Z"}

main.js code:

var {app, BrowserWindow, autoUpdater  } = require('electron');
var appVersion = require('./package.json').version;
var os = require('os');

var appArguments = process.argv.splice(1);

var platform = os.platform() + '_' + os.arch();

if (  appArguments.indexOf('--dev') === -1 ) {

  var updateFeed = 'https://PRIVATEURL/update/'+platform+'/'+appVersion;
  autoUpdater.setFeedURL(updateFeed);
  autoUpdater.on('update-available', function(){
    console.log('update available');
  }).on('update-downloaded', function(e){
    console.log('update downloaded: ', e);
    //autoUpdater.quitAndInstall();
  });
  autoUpdater.checkForUpdates();
}

app.on('ready', ()=>{
  const win = new BrowserWindow({
    width: 375,
    height: 666,
    title: "StarPhone",
    frame: true,
    resizable: false,
    transparent: false,
    'webPreferences': {
      'webSecurity': false
    }
  });

  if (appArguments.indexOf('--debug') > -1 || appArguments.indexOf('--dev') > -1 ){
    win.webContents.openDevTools();
  }

  if (appArguments.indexOf('--dev') > -1 ){
    win.loadURL('http://localhost:8080');
  } else if (appArguments.indexOf('--test') > -1 ){
    win.loadURL('https://PRIVATEURL/softphoneDesktop/');
  } else {
    win.loadURL('https://PRIVATEURL/softphoneDesktop/');
  }
});

**Comment by kevinsawicki** [comment]
> executing call via browser returns:

Is the update url behind any authentication or anything? Can you load it in an incognito browser window?

**Comment by jschimmoeller** [comment]
yes an incognito browser window does return for the update.  not behind authenicate. 

I did notice that the url is bad when it comes back from update:
{"url":"/download/2.5.1/osx_64?filetype=zip","name":"2.5.1","notes":"","pub_date":"2016-08-24T01:08:25.000Z"}

here is what it looks on a generic fresh localhost server:
{
  "url": "http://localhost/download/2.5.1/osx_64?filetype=zip",
  "name": "2.5.1",
  "notes": "",
  "pub_date": "2016-08-24T02:06:27.000Z"
}

based on this testing; I believe we should just close it; local config issue.

**Comment by pconerly** [comment]
I just hit this too, and I also have `electron-release-server` running behind an ngrok.io proxy.

So in `electron-release-server/config/local.js` I had:

```
module.exports = {
  appUrl: 'SITE_URL',
...
```

Which is invalid, and ERS smartly defaulted to a relative url.  When I set the `appUrl` to my ngrok endpoint it worked.  Thanks :)
