### ISSUE TITLE
Any way to programmatically size the devToolsWebContents window?

### ISSUE THREAD

**Issue by koush** [electron/electron#6953]
* Electron version:
1.3.3
* Operating system:
OSX El Capitan

This works on normal Browser Windows:
```javascript
bw.webContents.executeJavaScript('window.resizeTo(1000, 1000)')
```

This does not work on a detached devtools webcontents for that same browser window:

```javascript
bg.webContents.devToolsWebContents.executeJavaScript('window.resizeTo(1000, 1000)')
```

Is there any way to programmatically size the devtools window that opens? Whenever they open for me, they are tiny windows in the bottom left of my monitor screen:

![snapsink-53](https://cloud.githubusercontent.com/assets/73924/17917631/0625aace-6973-11e6-84be-3a995d1d352d.png)

**Comment by zcbenz** [comment]
Currently the devtools window is not manageable with JavaScript, I'm merging this to #2835, which would allow controlling devtools window directly with Electron API.
