### ISSUE TITLE
Enhance "About" menu role to support customized options

### ISSUE THREAD

**Issue by Mercieral** [electron/electron#6955]
* Electron version: 1.3.3
* Operating system: Mac OS X 10.11.6

Currently the MacOS "about" role maps to the `orderFrontStandardAboutPanel` action (per the docs) which may be sufficient for most people, but we would like to have more customizable options on what is shown in the about panel. 

Essentially, I would prefer to have it mapped to the `orderFrontStandardAboutPanelWithOptions` action and just pass in nil for the options if no options are set, which is what `orderFrontStandardAboutPanel` does anyway. The main reason for this is that we want the version number to be displayed as the version of our web application and not the desktop application.

Is this possible/considerable?

**Comment by zcbenz** [comment]
It can probably be a new `app.xxx` API, since the we don't have a way to set parameters for menu roles.
