### ISSUE TITLE
Save dialog appears despite setSavePath if browser is offline

### ISSUE THREAD

**Issue by Joshua-Smith** [electron/electron#6957]
* Electron version: 1.3.3
* Operating system: OS X

Steps to reproduce:
0. Disconnect from the network
1. initiate a download using mainWindow.webContents.downloadURL(url);
2. call item.setSavePath(path) in the will-download handler

Result:
The browser will show a save dialog.

Expected result:
No save dialog, just an updated or done callback on the item

It appears that the code that notices a save path has been set and prevents the dialog from coming up doesn't happen when the download fails.

**Comment by Joshua-Smith** [comment]
Note, I just found https://github.com/electron/electron/issues/6784 which is probably the same issue.

**Comment by kevinsawicki** [comment]
> Note, I just found #6784 which is probably the same issue.

Closing out, I merged your reproduction steps into that issue's body 👍
