### ISSUE TITLE
WebView zoomFactor reset on navigate

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#6958]
- Electron version: 1.3.4
- Operating system: osx, Ubuntu 16.04 LTS

It looks like the zoomFactor is reset on webview tags when the page navigates. You can replicate this by adding the following to a webview preload script...

``` js
const webFrame = require('electron').webFrame
webFrame.setZoomFactor(2)
setTimeout(function () {
    window.location.hash = '123'
}, 1000)
```

 There's also some discussion around this issue [here](https://discuss.atom.io/t/why-does-webview-reset-its-zoomfactor-on-url-navigate/27064).

Would you consider this a bug or the desired behaviour? If it is the desired behaviour is there anyway to suppress it or configure it to be more permanent? I can imagine there are plenty of instances where you would want to provide a consistent zoom level to some remote content.

Thanks :)

**Comment by zcbenz** [comment]
It is expected behavior when using `webFrame.setZoomFactor`, since it only changes current frame and current frame is gone after navigation.

The correct way is to use `webview.setZoomFactor`, which is supposed to keep the zoom factor through navigations. However when I just tried it I found the zoom factor still goes away after navigation, so this is a bug.

**Comment by MarshallOfSound** [comment]
@zcbenz I think this is the issue that I am experiencing (but never tracked down) over at MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1421

This issue didn't always exist and appears to have been introduced some time between `1.1.0` and `1.3.2`.  I'll try track it down to a specific version.

**Comment by Thomas101** [comment]
@zcbenz Didn't know you could set zoomFactor directly on the web view, is this just missing from the docs or up and coming?

@MarshalOfSound as a workaround I found you can use setZoomLevelLimits(1.5, 1.5). It's not great, but keeps it set

**Comment by zcbenz** [comment]
> @zcbenz Didn't know you could set zoomFactor directly on the web view, is this just missing from the docs or up and coming?

I think it is just missing in docs.

**Comment by Thomas101** [comment]
@zcbenz I really hate to ask cause you're already doing such great work, but can you share any info on when a fix for this might land?

**Comment by zcbenz** [comment]
@Thomas101 Usually a bug is only fixed when someone is interested in it, so if no one assigns themselves to the issue, you can assume one one is working on it.

**Comment by Thomas101** [comment]
Thanks for the update on this :)

**Comment by andymartinwork** [comment]
It looks like the zoom changes as soon as you request anything from another domain even if the window.location doesn't change.

For example, sometimes we have pages that load a twitter stream. When that happens, the zoom for the page is reset.

**Comment by andymartinwork** [comment]
Looks like Brave may have some code to fix this in its Electron fork:

https://discuss.atom.io/t/why-does-webview-reset-its-zoomfactor-on-url-navigate/27064/4

**Comment by Thomas101** [comment]
@andymartinwork I'd had a few bug reports about it changing periodically but nice find on narrowing it down!

I also found the same on setting the limits. Sorry forgot to update this thread, but had to revert that change.

**Comment by Thomas101** [comment]
I don't know if it's related but @alvarezn mentioned in #7375 that setting the zoom level started to fail between 1.2.3 and 1.2.4. I noticed that this issue has cropped up for me between 0.37.8 and 1.3.3. If it would help anyone I'm happy to test each version between those two to find out exactly which one it breaks it

**Comment by jonathon-love** [comment]
hey @andymartinwork 

i just thought i'd let you know, i tried out the brave electron fork (v1.4.22) and it has the same issue :/

jonathon

**Comment by paulcbetts** [comment]
It looks like Chromium's `ZoomController` resets the zoom level on `DidFinishNavigation`. However, trying to do this myself results in the zoom level snapping to 1x then snapping back. Still looking into this

**Comment by Fishrock123** [comment]
Heya, I keep running into this via Slack, is there any way we can help move this forward? 😬 

@zcbenz Any suggestions?

**Comment by kevinsawicki** [comment]
@Fishrock123 the workaround @paulcbetts added in #8041 has been released and can be used to correctly zoom

**Comment by jonathon-love** [comment]
hi @paulcbetts (or i expect there are others who could answer my question),

if i understand correctly, this issue is still outstanding, and there remains a bug in electron (the bug does not occur in the corresponding version of chrome), but in the mean time we can use
```
setLayoutZoomLevelLimits()
```
to prevent the zoom from changing back to one on navigation (or the like).

but i'm not sure i understand the difference between `setLayoutZoomLevelLimits()` and `setZoomLevelLimits()`. intuitively, i would expect `setZoomLevelLimits` to affect the ... zoom where the *whole* content is scaled up. and `setLayoutZoomLevelLimits()` to affect that other zoom, where only the text size is increased, (and everything reflows).

if i am correct about these different types of zooms, then does that mean this cannot be used as a work-around for retaining the zoom specified by `setZoomFactor()`?

thanks for your time.

**Comment by cuixiping** [comment]
On my machine (win10, electron until 1.4.13), the main window's zoom factor will be reset when inserting new iframe element into the body by javascript.

**Comment by jonathon-love** [comment]
yes, but here's a simple work around. set the zoom with this:

```
webFrame.setLayoutZoomLevelLimits(-999999, 999999);
webFrame.setZoomFactor(zoom);
let ezl = webFrame.getZoomLevel();
webFrame.setLayoutZoomLevelLimits(ezl, ezl);
```

**Comment by Thomas101** [comment]
Thanks @jonathon-love

**Comment by benaadams** [comment]
> On my machine (win10, electron until 1.4.13), the main window's zoom factor will be reset when inserting new iframe element into the body by javascript.

Yes; also happens if you add an rich editor like [ck](https://github.com/ckeditor) etc that prepares the content in a separate iframe compent

**Comment by mdanics** [comment]
Having this issue on electron 2.0.2. @jonathon-love 's solution is not working

**Comment by mdanics** [comment]
Im running into this issue on electron 2.0.2.  @jonathon-love 's solution isn't working for me. Are there any updates on this?
