### ISSUE TITLE
BrowserWindows that are set as Always On Top disappear in Mission Control

### ISSUE THREAD

**Issue by koush** [electron/electron#6959]
* Electron version:
1.3.3
* Operating system:
OSX El Capitan

Here's a video:
https://youtu.be/q86qIDUXJDg

**Comment by zcbenz** [comment]
Apple chooses to hide the always-on-top windows in the mission control, I'm afraid there is no way to change this behavior.

**Comment by koush** [comment]
@zcbenz 
I am porting a Chrome app to electron, and somehow the Chrome APIs work around this. I suspect they are detecting Mission Control and temporarily removing that flag.

**Comment by koush** [comment]
that's fine though, this is acceptable behavior. was just something odd I noticed in my port.

**Comment by ddamico125** [comment]
Is there a way to make it disappear? This is actually the behavior i want for my window

**Comment by ddamico125** [comment]
> Hi, @koush
> 
> For me `window.setAlwaysOnTop(true)` doesn't disappear app in Mission Control :/
> 
> macOS Catalina 10.15.4
> electron 8.2.0
> 
> Doesn't work here https://github.com/inomdzhon/keypress-shower.

@inomdzhon were you ever able to figure out how to do this?

**Comment by inomdzhon** [comment]
@ddamico125 unfortunately, I didn't :(

**Comment by niftysoftware** [comment]
Is not having an always-on-top window disappear during Mission Control expected behavior in Catalina? Or is this a bug in Catalina/Electron?

**Comment by arantes555** [comment]
It seems to be a bug in recent versions of electron. In an electron@6 app, my always-on-top window is correctly hidden from Mission Control. When updating to electron@10, the window is now shown in Mission Control.

**Comment by zquancai** [comment]
> > Hi, @koush
> > For me `window.setAlwaysOnTop(true)` doesn't disappear app in Mission Control :/
> > macOS Catalina 10.15.4
> > electron 8.2.0
> > Doesn't work here https://github.com/inomdzhon/keypress-shower.
> 
> @inomdzhon were you ever able to figure out how to do this?

I encounter the same issue on 9.4.0~~

**Comment by zquancai** [comment]
> > > Hi, @koush
> > > For me `window.setAlwaysOnTop(true)` doesn't disappear app in Mission Control :/
> > > macOS Catalina 10.15.4
> > > electron 8.2.0
> > > Doesn't work here https://github.com/inomdzhon/keypress-shower.
> > 
> > 
> > @inomdzhon were you ever able to figure out how to do this?
> 
> I encounter the same issue on 9.4.0~~

but it works on electron@5.x (macOS Catalina 10.15.4)
video: https://www.loom.com/share/fc93d7b4477f4f62814b31dd67b518f0

related issue: https://github.com/electron/electron/issues/23246

**Comment by andy-asana** [comment]
I know this may be a bug, but I'm actually trying to find a way to hide windows in Mission Control.

Now that this bug is fixed, is there any other way to hide windows in Mission Control?

**Comment by centigrade-julian-lang** [comment]
This is also my use case - I need to hide the window from mission control; obviously as of the fix, `alwaysOnTop: true` don't do the job anymore. Do we have alternatives to achieve this behavior?
