### ISSUE TITLE
Object.prototype.name gets clobbered

### ISSUE THREAD

**Issue by koush** [electron/electron#6966]
* Electron version:
1.3.3
* Operating system:
OSX El Capitan

The value of Object.prototype.name is getting clobbered by remote.js. Took me a bit to track this down, so I'm not sure I fully understand the problem here.

ELECTRON_RENDERER_CALLBACK is invoked with the following args:
https://github.com/electron/electron/blob/master/lib/renderer/api/remote.js#L241

Value of args:
```javascript
{"members":[{"id":80,"members":[],"name":"ReferenceError","proto":null,"type":"object"}],"type":"array"}
```

Here's a video to illustrate the problem.
https://www.youtube.com/watch?v=b13slql1qwc&feature=youtu.be

I think the issue is this line in remote.js:
https://github.com/electron/electron/blob/master/lib/renderer/api/remote.js#L204
```javascript
      setObjectPrototype(ret, ret, meta.id, meta.proto)
```

If meta.proto is null, then the Object prototype gets clobbered.

**Comment by kevinsawicki** [comment]
> Value of args:

Are you able to provide an example of the value of the arguments you are passing to the remote function? Like something like:

```js
myRemoteFunction([new ReferenceError('test')])
```

**Comment by koush** [comment]
From renderer process A, where "callback" is a RemoteFunction in renderer process B:

```javascript
callback(null, new ReferenceError('test')
```

So that call ends up going from renderer -> main -> renderer. This actually ended up being a bug in my code, which exposed this possible issue in Electron. I fixed my bug, but figured I'd report this anyways. I realize that going renderer to renderer ipc is not ideal :)

**Comment by kevinsawicki** [comment]
> So that call ends up going from renderer -> main -> renderer.

So is the value correct in the main process and then wrong when it goes to the second render process?

**Comment by kevinsawicki** [comment]
> So is the value correct in the main process and then wrong when it goes to the second render process?

Any updates @koush?

**Comment by kevinsawicki** [comment]
Closing this out until more information is provided.
