### ISSUE TITLE
How to get the event of app is launch twice?

### ISSUE THREAD

**Issue by hisune** [electron/electron#6967]
How to get the event of app is launch twice?

**Comment by enlight** [comment]
Use this: http://electron.atom.io/docs/api/app/#appmakesingleinstancecallback

GitHub issues are for feature requests and bug reports, questions on how to use Electron should be directed to the [community](https://github.com/electron/electron#community).

**Comment by hisune** [comment]
@enlight 
Thx. Worked perfectly!
