### ISSUE TITLE
Frameless / Framed toggle?

### ISSUE THREAD

**Issue by z-ax** [electron/electron#6968]
Hi. At the moment working on app, where window behaviour is similar to Adobe CC.
And there's one thing we can't get right - drag the window to pull off the tray and make it a regular window. At this point have to have a workaround and on Pin/Unpin toggle feature re-create the window from scratch (and re-launch all UI). But that is a terrible UX, I'd say.

I've seen the issue #6413 where @zcbenz mentioned it's not worth implementing, but I'd say there's a plenty of cases where it might be useful, especially for this kind of apps.
So, adding this ticket in case you'll reconsider it.

Thank you in advance.

**Comment by zcbenz** [comment]
For Windows we basically needs to write a new GUI toolkit from scratch to be able to switch the frame dynamically, and for Linux I don't think the X11 protocol supports this, even if it does I believe most window managers would not respect it.

So you may consider this as a impossible mission.

**Comment by z-ax** [comment]
This is sad.

**Comment by codergautam** [comment]
Very
