### ISSUE TITLE
`-webkit-app-region: no-drag` doesn't work with `biu.js`

### ISSUE THREAD

**Issue by Menci** [electron/electron#6970]
* Electron version: 1.3.4
* Operating system: Linux x86_64 (elementary OS 0.4)

I use "biu.js" (which can be installed with npm) to show a pop up message, but if I set a (title bar) element to `-webkit-app-region: drag; `, and set biu to `-webkit-app-region: no-drag; `, the biu region is still draggable.

Even when I unchecked the `-webkit-app-region: drag; ` of the title bar in the devtools, the biu is still draggable, only when I unchecked the `position: fixed` and checked it back (that means move the title bar element and move it back), it become undraggable.

I tried to create a undraggable element and append to body by myself, the problem can't be reproduced. 

I don't know much about how `biu.js` is implemented. But I think there's a bug with electron.

[Here](https://github.com/electron/electron/files/436962/menci_test.zip) is a demo to reproduce the problem, to run it, run `npm install biu.js` and  `electron ./menci_test.js` under Linux.

**Comment by Menci** [comment]
A workaround is

```js
let drags = document.getElementsByClassName('drag');

{
    // when I need to biu
    biu('QwQ', { autoHide: false, pop: true, closeButton: '<i class="fa fa-close"></i>' });
    for (let drag of drags) {
        drag.style.display = 'none';
        drag.style.display = '';
    }
}
```

**Comment by zcbenz** [comment]
The `-webkit-app-region` attribute is actually quite dumb and is not able to recognize many fancy CSS transforms, so once the element is using some complex CSS styles, errors may happen.

This is actually a bug in blink, or probably on purpose for performance issues, so I suggest reporting this to Chromium's issues list instead. I'm closing this since we are not able to fix this on Electron's side.

**Comment by Menci** [comment]
Thanks for replying, but how can I report it to Chromium? I wonder what to tell them since the problem is in Electron not Chromium.

**Comment by zcbenz** [comment]
The `-webkit-app-region: no-drag` is from Chrome extensions API, so you need to create a Chrome app that uses this style and can show the problem.

**Comment by Menci** [comment]
Thanks. I'll try that.
