### ISSUE TITLE
webview ready event

### ISSUE THREAD

**Issue by xywz** [electron/electron#6972]
To know when its methods can be used and when its `webContents` can be accessed.

**Comment by MarshallOfSound** [comment]
I'm not sure I understand what you mean, as far as I am aware as soon as the domcontentloaded event fires all methods on all DOM objects are available to be used.

If this event is not sufficient can you please explain in more depth what you want to achieve.  I've never come across the problem where a webview's methods weren't available for any reason

**Comment by xywz** [comment]
As noted in the documentation, the methods of a webview cannot be accessed until the webview is loaded. You can confirm this by trying to call a method of a webview immediately after inserting it into the DOM.

**Comment by MarshallOfSound** [comment]
Have you tried the `domcontentloaded` event I mentioned.  Pretty sure that's what I use to wait for a webview to load.  Not 100% sure on that though 😕

**Comment by MarshallOfSound** [comment]
The example actually appears to listen for the `window.onload` event in order to wait for the webview to be ready.   Can you confirm if that event fulfills your needs, I don't have access to a PC to test this atm 👍

**Comment by xywz** [comment]
That event is dispatched every time a document loads and not sure on this but `webContents` may be available a little earlier. It would be useful to have an event that is dispatched as soon as the webview is ready, and only once.

**Comment by xywz** [comment]
@zcbenz @MarshallOfSound reopen and add documentation label?
