### ISSUE TITLE
Remove remote listeners on renderer unload or crash

### ISSUE THREAD

**Issue by xywz** [electron/electron#6974]

**Comment by MarshallOfSound** [comment]
This has been discussed here #5344

As mentioned by @zcbenz in his reply to that issue.

> For unhooking the callback automatically, it is basically impossible to implement since we can never how the callback is going to be used, for example a simple case like: win.on('event', => remoteCallback).

> And I don't think failing silently is an acceptable solution, it is just ignoring the problem.
