### ISSUE TITLE
Option to disable default droppable items

### ISSUE THREAD

**Issue by xywz** [electron/electron#6975]
Items that are droppable by default should not be. This means that they should not display the dropping possible indication and should return when released.

**Comment by MarshallOfSound** [comment]
Duplicate #5919

TLDR: You need to handle the `will-navigate` event yourself and prevent these navigations.

**Comment by xywz** [comment]
This issue is not about preventing navigation. The issue is that the dropping possible indication will still be displayed, which is incorrect and misleading. It is even worse when dropping is intended to be possible in one area because it will seem that dropping is possible everywhere.

**Comment by xywz** [comment]
`preventDefault` does not prevent the cursor change for all drags. When dragging an item to a `BrowserWindow` from another `BrowserWindow`, a webview, or Google Chrome, the dropping possible indication will still be displayed.

**Comment by xywz** [comment]
@MarshallOfSound are you able to replicate the issue?
