### ISSUE TITLE
Electron app replacing the dock icon of another app

### ISSUE THREAD

**Issue by zeke** [electron/electron#6982]
Operating system: macOS 10.11.6

[Brave](https://www.brave.com/) was already installed using the installer downloaded from brave.com

I then installed [Ramme](https://github.com/terkelg/ramme) with homebrew/cask:

```
brew update && brew tap caskroom/cask && brew cask install ramme
```

The Brave dock (and cmd-tab app switcher) icon was then replaced with that of Ramme:

![screen shot 2016-08-25 at 12 40 59 pm](https://cloud.githubusercontent.com/assets/2289/17983593/4ca41526-6ac2-11e6-9313-8fa7eaadbf2d.png)

After quitting and restarting both apps, order is restored. I am no longer able to reproduce the issue.

cc @terkelg @gingerbeardman @bbondy @darkdh

**Comment by jhgg** [comment]
We've actually noticed this issue too - but assumed it was an OS X bug.

**Comment by zcbenz** [comment]
I would assume it is an OS X bug too.

**Comment by terkelg** [comment]
I'm pretty sure it's a bug in macOS. I've seen it before, but not with electron apps

**Comment by gingerbeardman** [comment]
I've had it too, but interestingly it was the official Whatsapp icon that migrated to your Electron apps.

I've also had it with various Chrome-based apps I've created.

My hunch is that OS X uses some sort of ID/PID/process to track the icon and all Electron/Chrome apps have the same one?

**Comment by gingerbeardman** [comment]
I just reported this as rdar://28030345

**Comment by zeke** [comment]
What is `rdar`?

**Comment by MarshallOfSound** [comment]
> What is rdar?

I believe is is apple's developer bug reporting system

**Comment by zeke** [comment]
Guess I'll close this out then. @gingerbeardman can you share a URL for your report so people can track the issue?

**Comment by gingerbeardman** [comment]
I can't sadly, only myself and Apple have visibility of any bug I file as the radar issue tracker system is private. 

But if you each file a bug report the issue will gain importance.
