### ISSUE TITLE
Menu disappears when mouse move over the separator

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#6987]
* Electron version: 1.3.4
* Operating system: Windows 10

![issue1](https://cloud.githubusercontent.com/assets/8194131/17992243/4e2d8c72-6b78-11e6-88ad-7a57cd871a31.gif)

As the gif shows, when I move mouse over the separator of a submenu, it disappears.

**Comment by zcbenz** [comment]
I'm merging this to #1788 since they are essentially the same problem.
