### ISSUE TITLE
Do you recommend electron for creating Restaurant POS

### ISSUE THREAD

**Issue by keerthivasan-r** [electron/electron#6990]
* Electron version: 1.3.4
* Operating system: Windows

I'm in the intial stage looking for developing Touch based POS for Restaurants. I find very interesting to know about electron.

My High level requirements would be

- Touch based App in Kiosk Mode
- Mulitiple Touch clients with server (Client server model)
- Thermal Receipt printer
- PDF creation
- Bar code scanning
- Card swipe integration
- Cash drawer integration
- Weighing scale integration

Can anyone help me out with an advice? I'm really sorry to pollute this question as an issue. Thanks for the great work.

**Comment by MarshallOfSound** [comment]
> I'm really sorry to pollute this question as an issue

Electron issues are for bugs with Electron, please use Slack or the discussion forums for questions or advice

**Comment by keerthivasan-r** [comment]
Thank you @MarshallOfSound for directing me
