### ISSUE TITLE
Ability to choose where MenuItem label overflow ellipses are positioned 

### ISSUE THREAD

**Issue by boyvinall** [electron/electron#6993]
- Electron version:  (VSCode 1.4)
- Operating system: Windows

Steps to Reproduce:

open a folder with a really long path
File / Open Recent
Currently the ellipsis is right at the end of the path, which makes it difficult to know which path you're opening if you have several long paths in the list. Ideally, the ellipsis should reduce folder names in the middle of the path. See https://blog.codinghorror.com/shortening-long-file-paths/ for inspiration.

![57509e44-6aaf-11e6-9053-658920643907](https://cloud.githubusercontent.com/assets/1652176/17997352/f2d2617a-6b65-11e6-93dd-e61354c5843a.png)

I initially created this as Microsoft/vscode#10941 but it seems VSCode is just using the menu provided by electron.

**Comment by enlight** [comment]
The `Open Recent` submenu is built up by VSCode, so it should shorten paths before adding them to the menu.

**Comment by MarshallOfSound** [comment]
This is something that VSCode need to handle themselves.  Electron shouldn't be detecting file paths in a menu and automatically shrinking them for a user.  That is beyond the scope of the API's Electron intends to provide.

Please raise this as an issue on the VSCode repository

**Comment by MarshallOfSound** [comment]
I can see you have raised this as an issue already with VSCode

Microsoft/vscode/issues/10941

I think they have incorrectly tagged it as an `upstream` issue.  Rather they need to switch to manually eclipsing the file paths.

**Comment by bpasero** [comment]
@enlight @MarshallOfSound I filed this as upstream issue because a native menu typically handles trimming of long entries by itself. For example on Mac I see the "..." being inserted in the middle:

![image](https://cloud.githubusercontent.com/assets/900690/17999450/a2e69bcc-6b79-11e6-8feb-3ea298dbe84c.png)

My understanding is that the menu in Electron on Windows is a custom Chrome one and not the native menu. I think what I really wanted to express is that it would be good to have the native Windows menu working for Electron eventually because there are many known issues and challenges with the current one.

**Comment by MarshallOfSound** [comment]
I might pass this one on to @zcbenz or @kevinsawicki as they can probably give a super duper standpoint on this.

My current understanding is that we use Chromium's menus in our implementation of Menu's on Windows and Linux and use the native implementation on macOS.

I tried to see how Atom handles this and I discovered that they steer clear of Dynamic Menus (as far as I can see).

> As for the reported issue: I have no control over the ellipsis in the menu so I cannot even do the ellipsis myself because I have no information about the valid length until the "..." 

Ah, I see what you mean.  Can't customly ellipsis it if you don't know the length to ellipsis too 😢

**Comment by MarshallOfSound** [comment]
@bpasero Update the issue title, does it more closely cover what we want to achieve here?

> Request: Ability to choose where MenuItem label overflow ellipses are positioned

**Comment by boyvinall** [comment]
@MarshallOfSound From my POV, it's not so much about being able to choose, but generally doing the truncation in the middle rather than at the end - since you're loosing less of the important context there. It looks like OSX is handling this nicely, so can the Windows implementation be made to match that?  Not checked other platforms - all my linux are cli-only :)

**Comment by MarshallOfSound** [comment]
@boyvinall In the case where you have a menu item that the label is **not** a file path eliminating the middle of the string might be (and probably is) not what you want to do.

The ability to choose is always better than forcing one way of doings things.  However I am not even sure if we have this ability to choose.

**Comment by boyvinall** [comment]
> The ability to choose is always better than forcing one way of doings things

@MarshallOfSound yeah, I know what you mean, although it's also often better not to make APIs unnecessarily complex :)  I'm not sure I agree with:

> In the case where you have a menu item that the label is not a file path eliminating the middle of the string might be (and probably is) not what you want to do.

Would appreciate any investigation you can give to this anyways. Thanks.

**Comment by bpasero** [comment]
Thanks for the update, the title makes sense 👍

**Comment by enlight** [comment]
Perhaps @bpasero could sneak a peak at the Visual Studio source (the hefty one) to see how they've implemented path compacting in the `Recent Files` submenu. Did they use the [CRecentDocumentList from WTL](https://cs.chromium.org/chromium/src/third_party/wtl/include/atlmisc.h?rcl=0&l=3209) which compacts filenames to `MAX_PATH` (260) characters before inserting them into the menu?

**Comment by bpasero** [comment]
VS must be doing something very custom, they shrink the path a lot:

![image](https://cloud.githubusercontent.com/assets/900690/18025902/c8f6193c-6c37-11e6-89b6-658bf0dd42fd.png)

**Comment by bpasero** [comment]
VS is doing something very custom. I think they just show the parent folder name and the file:

![image](https://cloud.githubusercontent.com/assets/900690/18025904/e6fa78ba-6c37-11e6-9531-4feafb60aad2.png)

VS Code could probably do something similar as a workaround.

**Comment by zcbenz** [comment]
> My understanding is that the menu in Electron on Windows is a custom Chrome one and not the native menu. I think what I really wanted to express is that it would be good to have the native Windows menu working for Electron eventually because there are many known issues and challenges with the current one.

Switching to native menu doesn't help on this, as far as I know neither win32 menu nor GTK menu supports controlling the position of ellipses, and it would actually lead us to a custom menu.

> As for the reported issue: I have no control over the ellipsis in the menu so I cannot even do the ellipsis myself because I have no information about the valid length until the "..." is being added. In some cases I would probably end up with my own ellipsis in the middle and the one added from the windows menu.

It is possible to control the behavior of ellipsis with Chromium's UI framework, but it would quite tricky since we are just reusing Chromium's code to create the menu.

**Comment by codebytere** [comment]
Given that adding this functionality is complex and expensive, and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!
