### ISSUE TITLE
Support back mouse button

### ISSUE THREAD

**Issue by Pablohn26** [electron/electron#6996]
- Electron version:1.3.1
- Operating system:Fedora 24

It seems Event: ‘app-command’ is only available in Windows. Would be possible to add Linux support of it?

**Comment by zcbenz** [comment]
There is no `app-command` on Linux, the buttons on mouses are translated to key events depending on your machine's configuration. Can you try whether the button works in Chrome browser? And if it is working can you use the `xev` tool to get what key event the button is translated to?

**Comment by MarshallOfSound** [comment]
GPMDP uses a native node module for forward and back mouse buttons on linux that we made ourselves.

https://github.com/jostrander/mouse-forward-back

Does this fulfill your needs?

**Comment by Pablohn26** [comment]
I have run `xev -event button` with next output

```
root:1@/tmp# xev -event button
Outer window is 0x6c00001, inner window is 0x6c00002

ButtonPress event, serial 25, synthetic NO, window 0x6c00001,
    root 0xd4, subw 0x6c00002, time 75696468, (46,32), root:(143,592),
    state 0x10, button 9, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x6c00001,
    root 0xd4, subw 0x6c00002, time 75696756, (46,32), root:(143,592),
    state 0x10, button 9, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x6c00001,
    root 0xd4, subw 0x6c00002, time 75697284, (46,32), root:(143,592),
    state 0x10, button 8, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x6c00001,
    root 0xd4, subw 0x6c00002, time 75697556, (46,32), root:(143,592),
    state 0x10, button 8, same_screen YES
```

button 9 is forward button and button 8 is back button. 

And yes, it is working on Google Chrome and chromium.

**Comment by jonathansampson** [comment]
I came to the same results as @Pablohn26.

https://github.com/brave/browser-laptop/issues/5620#issuecomment-291000212

**Comment by ioan-ungurean** [comment]
There is now a year and a half and no progress on this?

**Comment by jaewonha** [comment]
came here from vs code not supporting back key navigation...
please someone take care of this issue...!

**Comment by verner-lall** [comment]
Almost 2 years for something seemingly simple. Please?

**Comment by SocksPls** [comment]
Anything? This is the only thing stopping me using brave as my main browser on all of my computers.

**Comment by premek** [comment]
How should this be implemented?
- Should it emulate app-command windows event on linux? (no need to change the apps and it will start automatically working)
- use a different api for listening to mouse buttons? Apps would have to implement it differently on win/linux
- use mouse-forward-back package as suggested above? That would also have to be implemented in apps differently for linux

**Comment by Aetherall** [comment]
I am not an electron developer so maybe I am saying pure nonsense :)

but maybe it is solvable by the adapter paradigm, 
where there is an "OSX mouse event adapter",  "Linux mouse event adapter" and "Windows mouse event adapter" and the correct one is chosen on compile time?

**Comment by coreybruce** [comment]
it already is supported in Linux and it's really annoying, I keep accidentally pressing the button on my mouse, how do I disable the back button?!

**Comment by codebytere** [comment]
Given that this has bene solved in userland by modules like [mouse-forward-back](https://www.npmjs.com/package/mouse-forward-back), and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!

**Comment by coreybruce** [comment]
If you guys want to disable the back button from working on your web page in electron just use this script in the body 

onLoad="noBack();" onpageshow="if (event.persisted) noBack();"

e.g
<body onLoad="noBack();" onpageshow="if (event.persisted) noBack();" onUnload="" style="margin: 0 auto;">
</body>

**Comment by jonathansampson** [comment]
@coreybruce Your code lacks the function itself. Is `noBack` already defined as a global somewhere in Electron? Also, why would you want to do this?

**Comment by coreybruce** [comment]
> @coreybruce Your code lacks the function itself. Is `noBack` already defined as a global somewhere in Electron? Also, why would you want to do this?

I have a gaming application called Gamer World and I it is really annoying when I accidentally press the back button my mouse in the middle of a game and it goes back a page.

here is a link to the Gitlab repo

https://gitlab.com/coreybruce/Gamerworld-App

**Comment by britalmeida** [comment]
Can you communicate better and make it easier for software using electron to setup the navigate back/forwards correctly?
Currently, neither VSCode or Spotify on Linux have the functionality working.

**Comment by JoseFMP** [comment]
As @britalmeida mentioned. Why wouldn't this be used in VSCode on Linux? Would be great to propagate the achievement :)

**Comment by coreybruce** [comment]
What does VSCode have to do with Electron tho @JoseFMP?

**Comment by coreybruce** [comment]
@codebytere Oh right I see

**Comment by mikelpr** [comment]
this is crazy. why is there an API difference for something so basic between windows and linux and why should each app implement back and forward specifically for linux and not share code with windows and macos?

**Comment by Yanpas** [comment]
Seems like mac users are still lacking this.
https://electronjs.org/docs/api/browser-window#event-app-command-windows-linux

Why not introduce separate event 'navigation' or 'crossplatform-command' event? This is VERY ugly workaround.

**Comment by tyranteon** [comment]
Isn't electron supposed to make cross platform development easier? Then why suddenly separate this behavior between platforms?

**Comment by RattlingAmigo** [comment]
With some javascript and html, we can make like browsers button (<) (>)  for every platform. 
Making below lines of the code on top of the page, with some css would be the work around.

Code:
<input type=button name="back" value="Go Back" onclick="history.back();">
<input type=button name="forward" value="Go Forward"onclick="history.forward();">

**Comment by Tejeev** [comment]
Still an issue, and no, uerland does not have a fix for each electron app.  Please fix this..  It's honestly kind of ridiculous.
