### ISSUE TITLE
electron `window.open` is conflict with `window.open` in browser

### ISSUE THREAD

**Issue by lebornjose** [electron/electron#6997]
![222](https://cloud.githubusercontent.com/assets/5765408/18002763/58f62cba-6bbc-11e6-8e8c-f42a724de953.png)

`var n = window.open()`in the image above will abort the error that `n is null`
in fact, in broswer it`s a object. but when run in electron.it will conlict

**Comment by kevinsawicki** [comment]
What version of Electron are you using?

If you run `window.open()` from the Console tab in the dev tools, do you see a value returned or is it null?

**Comment by lebornjose** [comment]
electron version 1.3.4     var n =window.open()     yes   n  is null ,   electron is  window.open and javascript window.open  conflict

**Comment by kevinsawicki** [comment]
I'm having a little trouble reproducing this, this what I see when running `var n = window.open()` from the dev tools. Do you see the something different?

<img width="1039" alt="screen shot 2016-08-26 at 10 41 06 am" src="https://cloud.githubusercontent.com/assets/671378/18014837/b1ae9aec-6b79-11e6-8efe-e0f054280f10.png">

**Comment by lebornjose** [comment]
[
!(https://cloud.githubusercontent.com/assets/5765408/18014910/c4560a94-6bf7-11e6-9b28-cdf91a9a6abe.png)
]
i  am  Open other URL,  electron open other url window，  this windows  run  var n =window.open()

**Comment by lebornjose** [comment]
electron BrowserWindow  continue to open BrowserWindow run var n =window.open();  n is null,

perhaps  is iframe open BrowserWindow run   var n  = window.open()

**Comment by kevinsawicki** [comment]
> perhaps is iframe open BrowserWindow run var n = window.open()

Calling `window.open` from within an `<iframe>` is not currently supported in Electron.

See https://github.com/electron/electron/issues/6617 and https://github.com/electron/electron/issues/2644 for more details, closing this out.
