### ISSUE TITLE
window.history.go causes renderer to immediately hit about:blank

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#7004]
* Electron version: 1.3.x
* Operating system: OSX / Linux

This must be a regression in `1.3.x` because this problem did not exist prior to `1.3.0` and I've confirmed it's worked from `1.0.2` through `1.2.8`.

This is also **NOT** a bug in Chrome 52, it only happens in Electron.

In my application using `window.history.go` from inside of an `<iframe>` immediately causes the entire parent window to navigate to `about:blank` which nukes everything from the parent to the child iframe(s).

Normally invoking `window.history.go` should navigate to the entries associated only to the calling `<iframe>`.

I had also opened a *similar* issue #3734 a long time ago, but to clarify the behavior I'm seeing now is different from that issue, although the same methods: `history.go`, `history.back` and `history.forward` are all broken again.

**Comment by MarshallOfSound** [comment]
Can you provide a minumal sample application the reproduces the issue.  I'm having trouble replicating this locally.

**Comment by brian-mann** [comment]
Yah I can, give me a day or two.

**Comment by brian-mann** [comment]
I am working on a reduced example right now, and I'm finding that even `1.2.8` is broken albeit in a slightly different manner than the issue that I opened. Not quite done investigating yet though!

**Comment by kevinsawicki** [comment]
@brian-mann any updates on this one?

**Comment by brian-mann** [comment]
Not yet, I'm having a difficult time reproducing outside of Cypress so it's likely an hours long investment to figure out the exact thing that causes this to be triggered.

It's likely related to my other issue #7092

**Comment by zcbenz** [comment]
Closing until more information is provided.
