### ISSUE TITLE
Translucent window doesn't work properly on the macOs 10.10

### ISSUE THREAD

**Issue by guanyong1993** [electron/electron#7005]
- Electron version: 1.3.4
- Operating system: macOS 10.10.\* (Yosemite)

Set the translucent background color to body in a transparent window, When the cursor across the window, the cursor around the color will be deep.
This is a MacOs 10.10.\* that appears on the bug. How do ? Thanks in advance!

![3 v jv e 0 b m dhoqs](https://cloud.githubusercontent.com/assets/10172834/18025566/fe28b09c-6c5f-11e6-846f-8a13152e502d.png)

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by guanyong1993** [comment]
Of course. Prior to this, I provide some information, I'm not sure it will be useful, But I want to help you catch problems. 
I found in the size is 480x320 window or has not css hover window is difficult to reproduce this problem.
OK, The following is an attachment

[TestMiniApp.zip](https://github.com/electron/electron/files/447949/TestMiniApp.zip)

**Comment by zcbenz** [comment]
I'm unable to reproduce on 10.11, it is probably a 10.10 only problem.

**Comment by zcbenz** [comment]
I believe later Chrome versions have already fixed this.
