### ISSUE TITLE
Failed at the electron@1.3.4 postinstall script 'node install.js'

### ISSUE THREAD

**Issue by PragmaticEd** [electron/electron#7007]
* Electron version: 1.3.4
* Operating system: ubuntu 16.04 64bit
* nodejs version: 4.2.6

did:
```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
```

got:

```
> electron-prebuilt@1.3.4 postinstall /home/pragmaticed/workspace/electron-quick-start/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron-prebuilt@1.3.4 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.3.4 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

```

[npm-debug.log.txt](https://github.com/electron/electron/files/440651/npm-debug.log.txt)

**Comment by MarshallOfSound** [comment]
I can't speak for everyone, but reading through an **11 THOUSAND** line log file is not very fun.  For future reference you don't need to enable `silly` or `info` level logs.  The standard `error` level gives everything you need 99.99% of the time.

In this case the key bit is

```bash
13936 verbose stack Error: electron@1.3.4 postinstall: `node install.js`
13936 verbose stack spawn ENOENT
13936 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13936 verbose stack     at emitTwo (events.js:87:13)
13936 verbose stack     at ChildProcess.emit (events.js:172:7)
13936 verbose stack     at maybeClose (internal/child_process.js:821:16)
13936 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

Which looks like a standard "something went wrong when we installed this thing, please try again" style NPM error.

Just deleting your `node_modules` directory and rerunning `npm install` will fix issues like this 99% of the time.

Also issues to do with the `electron` and `electron-prebuilt` packages should probably be raised over at https://github.com/electron-userland/electron-packager

**Comment by PragmaticEd** [comment]
```
Just deleting your node_modules directory and rerunning npm install will fix issues like this 99% of the time.
```

except, i tried that, like 10x, and it failed 100%..

And what do You mean by:

```
Also issues to do with the electron
```

This is electron repo.

Don't understand why this is closed..

**Comment by PragmaticEd** [comment]
@MarshallOfSound Why Do you keep redirecting to other repos? Error clearly says the problem is with `electron` `post install` script..

**Comment by MarshallOfSound** [comment]
@PragmaticEd The `electron` package is an exact mirror of the `electron-prebuilt` package.  I'm directing you to the correct repository for the given NPM package.  The electron team does not maintain that package.

See http://electron.atom.io/blog/2016/08/16/npm-install-electron for more information about the naming of the NPM packages.  In particular see this line

> The electron-userland/electron-prebuilt repository will remain the canonical home of the electron npm package.

**Comment by PragmaticEd** [comment]
> Note As of version 1.3.1, this package is published to npm under two names: electron and electron-prebuilt. You can currently use either name, but electron is recommended, as the electron-prebuilt name is deprecated, and will only be published until the end of 2016.

So `electron` is  recomended, as `electron-prebuilt` is deprecated, but all issues should go to `electron-prebuilt`?

That seams weird to me, to be honest..

**Comment by MarshallOfSound** [comment]
See the repository tag and issues tag in the NPM package metadata.

https://www.npmjs.com/package/electron

They both link to `electron-prebuilt`, although a slightly strange situation, all the metadata is set correctly to point you to the right places 👍

**Comment by fighxp** [comment]
> Issues to do with `electron-quick-start` should be raised over at

I have tried your method, but without success
