### ISSUE TITLE
Memory management for complex apps (Renderer process goes low on memory and crashes eventually)

### ISSUE THREAD

**Issue by chandrachivukula** [electron/electron#7010]
* Electron version: 1.2.7, and earlier builds. Trying on 1.3.3 but initial results show below behavior.
* Operating system: Windows 7+, Mac

Our app is exhibiting an issue where, for a lot of our power-users, the renderer process keep fluctuating in memory usage but eventually reaches a point when any of the app actions results in a crash. The sequence of user/app activity that leads to a crash are not consistent, but eventually the app does crash (for those users).

I suspect memory is getting fragmented and isnt getting compacted fast enough such that even modest requests for memory (2MB request on a pc with ~4Gb free mem) are crashing the app.

How do I validate GC is being called regularly in the renderer process?
How do I force GC collection in my app (aggressively) for both browser and renderer process types?
Does GC collect opetation also compact memory in V8/Chromium?
How do I force renderer process/Chromium process to GC DOM elements (since we have a heavy UI app, we have consistently high DOM element turnover rate)?

I have seen native node modules referenced in forums, but was wondering if complex apps on Electron need to tweak/manage GC.Collect calls.

Asking since I could not find memory management optimizations/tips/pointers/documentation for (complex) Electron apps.

Based on the feedback for this issue, I am happy to collect these into a doc update.

Appreciate much, thanks.

**Comment by zcbenz** [comment]
This is usually because your app has memory leak, using a language with garbage collection doesn't prevent you from getting memory leaks.

You can use the heap profiling in devtools to investigate the memory usage in your app, and there is a small guide on that:
https://developers.google.com/web/tools/chrome-devtools/profile/memory-problems/heap-snapshots
