### ISSUE TITLE
Broken ASAR after execSync

### ISSUE THREAD

**Issue by tejohnso** [electron/electron#7011]
* Electron version: 1.3.1 
* Operating system: Windows 10 64-bit - Windows 7 32 bit - ArchLinux 64 bit

> Using electron-packager with --asar=true

If execSync throws (is called on an invalid command or a command that returns an error code), subsequent ASAR related file handling will fail.

```js
const childProcess = require("child_process"),
app = require("electron").app;

process.on("uncaughtException", (err)=>{
  console.log(err);
  app.quit();
});

app.on("ready", ()=>{
  console.log("Stat sync call...");  
  console.log(require("fs").statSync(__filename));
  try {
    childProcess.execSync("xxxx");
  } catch(e) {}
  console.log("Same statSync call as above...");
  console.log(require("fs").statSync(__filename)); //Throws with ENOENT / ENOTDIR (win/linux)
});
```

[broken-asar.zip](https://github.com/electron/electron/files/440974/broken-asar.zip)

**Comment by zcbenz** [comment]
I'm also able to reproduce on mac.
