### ISSUE TITLE
Couldn’t find preset “es2015” relative to directory

### ISSUE THREAD

**Issue by F-happy** [electron/electron#7012]
* Electron version: 1.2.8
* Operating system: macOX 10.11.6

When I use webpack in electron. I have all the dependencies installed.
the code is :
```
module: {
              loaders: [
                    {
                        test: /\.js$/, loader: 'babel-loader', exclude: '/node_modules/',
                        query: {
                            presets: ['es2015']
                        }
                    }
                ]
            },
```
 When I packed electron app and run , it throw:
```
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/fuhuixiang/fdFlow_workspace/fuhuixiang/js"
```
i  don't know whose fault it is. Please tell me, what should I do. Thanks

**Comment by MarshallOfSound** [comment]
I can say with a 99% certainty that either your webpack config is bugged or you don't have the `babel-preset-es2015` module installed.

Either way, I'm not sure how this is an issue with Electron.  Can you please explain what you see to be the Electron issue here?

**Comment by F-happy** [comment]
Start I also think that is not installed ```babel-preset-es2015``` module. but, i through install after still so. 
<img width="322" alt="qq20160828-0 2x" src="https://cloud.githubusercontent.com/assets/8241236/18031695/7660d660-6d1f-11e6-924e-39df9ca63bc4.png">
Moreover, the webspace config above in other project is can run, So, I don't know what to do.... @MarshallOfSound

**Comment by MarshallOfSound** [comment]
This isn't really a place to ask about webpack config issues.  I'll repeat what I said before

> Either way, I'm not sure how this is an issue with Electron. Can you please explain what you see to be the Electron issue here?

As far as I can see this is just a webpack config issue so I'll close it out as such.  I would suggest asking for help on Slack or the Electron Discussion Forums as some people there will probably have used webpack before.

One thing I will say though is have you checked that the module is actually installed?  

`Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/fuhuixiang/fdFlow_workspace/fuhuixiang/js"`  definitely indicates that it is not installed.  Try checking your `node_modules` folder for the preset it wants.
