### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by Ugarz** [electron/electron#7014]
* Electron version: 1.3.4
* Operating system: Windows 10 (64bits) from Bash on Ubuntu on Windows
* Node: 6.3.1
* NPM: 3.10.3

## Picture
![electronjpg](https://cloud.githubusercontent.com/assets/6050079/18035398/c5264010-6d55-11e6-98c8-c0a71aa33592.JPG)

## Exact error
```
Traceback (most recent call last):
  File "./script/start.py", line 40, in <module>
    sys.exit(main())
  File "./script/start.py", line 34, in main
    subprocess.check_call([electron] + sys.argv[1:])
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

## What I was doing
Hello, usually I don't have any issue with this repo' but this came out when I tryied to run the package throught Bash on Ubuntu on Windows 10 64bits. Usually I work on mac and I wanted to test If a same project could be ran on "Bash on Ubuntu on Windows" and a classic MacOSX envirronment.

No problem for the mac.
On windows here it is.

Any idea about it ?
Thanks :)

**Comment by nikola** [comment]
As the traceback says, it can't find the file that you are trying to execute with `subprocess.check_call([electron])`. Is `electron` really a `str`? Hard to tell from your code. Maybe you are just missing quotes around `electron`?

**Comment by Ugarz** [comment]
I'm not quite good with Python. I've never tried it out seriously, but when I try this :
```python
 try:
    subprocess.check_call([electron] + sys.argv[1:])
    #Here logging importing 'logging' on top of the file
    logging.debug('some stuff')
    print([electron] + sys.argv[1:])
  except KeyboardInterrupt:
    return -1
```
But nothing comes out, I think I'm doing it wrong ^^
By the way, I underline that I'm on windows using "bash on ubuntu on windws" (a new feature of windows 10). Reading the `start.py`, I'm wondering if it is not about the absolute path that he can not resolve.

**Comment by enlight** [comment]
Just a heads up, even if you work around this issue you'll probably run into #6722

**Comment by zcbenz** [comment]
You should use the `electron` npm package if you just want to install electron, `npm start` is for developers to run a local build.

**Comment by Ugarz** [comment]
Yeah that is what I've done.
I juste download this repo with a

```bash
git clone git@github.com:electron/electron.git
cd electron && npm i && npm start
```

**Comment by MarshallOfSound** [comment]
@Ugarz What are you trying to achieve.  Building Electron locally inside bash for windows will build the linux version of Electron in a headless CLI only environment.  In other words, entirely useless 😆 

If you want to use Electron simply `npm install electron` but again, on bash for windows that will install the linux variant.

**Comment by zcbenz** [comment]
@Ugarz `npm i` doesn't build Electron since Electron is not a node module, you have to follow the build instructions:
http://electron.atom.io/docs/development/build-instructions-linux/

**Comment by Ugarz** [comment]
Reading the readme and trying to get to bed early solved my problem.
Sorry for my weakness.
