### ISSUE TITLE
Accelerator backslash requires double press

### ISSUE THREAD

**Issue by Islandman93** [electron/electron#7015]
* Electron version: 1.3.17
* Operating system: Ubuntu 14.04

I'm working on the https://github.com/shockone/black-screen app, and the menu uses an accelerator with a backslash:
```
accelerator: "CmdOrCtrl+\\"
```

The command does not execute if I do Ctrl+\ but it does execute when I do Ctrl+\,Ctrl+\ (hold Ctrl and press backlash twice). 

I found #107 which is related, and there is a case for '\\' in the related commit but it doesn't seem to be working. My only thought is if it's looping over each element of the string and since '\' must be escaped it doesn't catch it unless it's pressed twice?

Any help or hints for where to look into why this is happening is appreciated. 

Also if there's a way to get JavaScript to let me use a single \ instead of two (even if some sort of hack) let me know and I'll try to see if that works.

**Comment by zcbenz** [comment]
I'm unable to reproduce with a simple app like this:

```js
const {app, BrowserWindow, Menu} = require('electron')

let win 
app.once('ready', () => {
  win = new BrowserWindow({width: 200, height: 200})
  win.setMenu(Menu.buildFromTemplate([
    {   
      label: 'menu',
      submenu: [
        {
          label: 'test',
          accelerator: 'Ctrl+\\',
          click () { console.log('click') }
        },  
      ],  
    },  
  ])) 
  win.loadURL('http://github.com')
})
```

**Comment by kevinsawicki** [comment]
@Islandman93 are you able to try out the sample app @zcbenz provided and see if it works correctly for you?

**Comment by Islandman93** [comment]
Sorry for this issue, I think somewhere the code is preventing the default action for Ctrl. Other apps including the simple one provided work. I should've done more testing before raising an issue.

**Comment by varun-dc** [comment]
In case anyone lands here from an internet search in the future, related issue you maybe interested in https://github.com/microsoft/monaco-editor/issues/3076
