### ISSUE TITLE
Automatically update views when db updates

### ISSUE THREAD

**Issue by rodryquintero** [electron/electron#7016]
* Electron version: 1.3.4
* Operating system: Windows 7 Professional

------------------------------------------------------
Back in the days of native apps, whenever there was an update on a table related to a view, the view would automagically update itself to display the most recent data.

Currently, I do now know of any other way to accomplish this without using some sort of polling mechanism that periodically queries the table for new information.

The application I am writing connects directly to the database (MariaDB). I do not use any kind of middleware to perform database tasks.

What do you think.

**Comment by mnquintana** [comment]
It sounds like you should take a look at a JS view framework with one-way data binding, like [React](https://facebook.github.io/react/).

However, for questions about writing apps, I suggest seeking help from [the community](https://github.com/electron/electron#community). The GitHub Issues list is only for bug reports and feature requests.

**Comment by rodryquintero** [comment]
This is more of a feature request.

I am using React and Redux for the Electron app I am writing.

**Comment by MarshallOfSound** [comment]
@rodryquintero React, Redux and a real time data store will solve your problem.

The issue as far as I can tell is that you are trying to make a real time app with a static data store (I.e. you can push into the store and then pull out), you want to push into the store and it to push it back out.

As far as I am aware RethinkDB does this for you.  It sends JSON to your connection when something inside the store updates.  Tapping this into redux will create the truly real time updating app you are looking for (I think).

http://www.rethinkdb.com/

But yeah, questions like this should head into Slack or the Community

**Comment by rodryquintero** [comment]
Thanks. This is what I am looking for. Thanks for answering.
