### ISSUE TITLE
Electron Cluster loss of connect when idle A fix that requires no messaging or reload, infusion of sails technology and PMX to vendor modules 

### ISSUE THREAD

**Issue by derfmilo** [electron/electron#7017]
* Electron version:1.3.4
* Operating system:Windows,Linux,Darwin both x64 and x86
I was getting a white screen when windows 10 now decides That on Idle it will rely on the Task Tray to keep the Cluster. So I included PMX(PM2)0.6.3, and MiniMatch 3.0.3. Not for nothing this will also allow users the ability to stream in native environments with out interuption.

**Comment by rickhall** [comment]
Not sure I fully understand. Are you saying that installing the PMX and MiniMatch modules prevents the electron renderer process from crashing after idle just by their mere presence?

**Comment by derfmilo** [comment]
they run in the background to keep Clusters from losing connectivity.

**Comment by rickhall** [comment]
Ok, sure. But I was still hoping to find some way to get a log or stack trace on the process that crashes to see what's going on. On my Mac, I can clearly see that I lose a process in the activity monitor and I'd like to know why, but I haven't seen a way to get a log or stack trace.

Is there really no way to create a basic Electron app that survives its host going to sleep?
