### ISSUE TITLE
Support default chromium context menu as a config parameters

### ISSUE THREAD

**Issue by r1si** [electron/electron#7021]
The electron context menu is buggy.. 
There are currently two open bugs:
* "Clicking outside context menu triggers click event on DOM element" https://github.com/electron/electron/issues/6770
* "Menu.popup blocks the run/render loop" https://github.com/electron/electron/issues/1854 
 
Another bug/feature is that electron context menu doesn't have chromium default behaviour: 
if I set a context menu and after I include an iframe (webview object) with a javascript context menu override, the application shows me both menu... instead of the override ones ( the webviews context menu)
 
I think that all bugs will be resolved if there is a parameter/configuration that allows electron to use chromium default context menu... (default settings will be "disable").

Elia

**Comment by zcbenz** [comment]
There is no magic switch to simply turn on Chromium's context menu, its code is very tightly bound with Chrome browser's logic and is impossible to port. The only option for us is to improve our Menu API.
