### ISSUE TITLE
Google Cast (Chromecast) in Electron

### ISSUE THREAD

**Issue by evancohen** [electron/electron#7024]
**Enhancement**
Now that Google Cast is [built into Chrome](https://chrome.googleblog.com/2016/08/google-cast-is-now-built-in-to-chrome.html) and is [a part of chromium](https://cs.chromium.org/chromium/src/media/cast/?q=cast&sq=package:chromium) it would be awesome to have this functionality baked into Electron. 

There is already an Electron wrapper for Chromecast ([GPMDP/electron-chromecast](https://github.com/GPMDP/electron-chromecast) via @MarshallOfSound in #869), so maybe the best approach would be to integrate that wrapper directly into Electron.

Having Cast functionality out of the box would be useful for a lot of electron apps in the ecosystem today, for example: 
- https://github.com/Soundnode/soundnode-app/issues/504
- https://github.com/twolfson/google-music-electron/issues/40
- [45 other electron apps](https://github.com/search?q=electron+chromecast&type=Issues&utf8=%E2%9C%93) that have issues with Chromecast

**Organized links**
- Googe Cast integration [blogpost](https://chrome.googleblog.com/2016/08/google-cast-is-now-built-in-to-chrome.html)
- Chromium Cast [source code](https://cs.chromium.org/chromium/src/media/cast/?q=cast&sq=package:chromium)
- Chrome Sender [API Reference](https://developers.google.com/cast/docs/reference/chrome/) (probably irrelevant because these APIs should stay the same)
- Existing Electron wrapper for Chromecast: [GPMDP/electron-chromecast](https://github.com/GPMDP/electron-chromecast)

**Comment by MarshallOfSound** [comment]
Thought I'd chime in here.

First of all the GPMDP/electron-chromecast module is hacky to say the least.  It is more of a polyfill than an implementation and it does the bare minimum required to "Just Work"(TM) with basic cast usage.

I would love it if the Google Cast implementation inside Chromium could be ported to Electron.  However (and this is related to #5612) there are a number of issues I came across while attempting a port previously.

1.  Google Chrome uses a built in MDNS scanner.  The MDNS spec says you must listen for and send requests from port `5353`.  Most Windows machines default firewall configuration block these requests without adding an exception to the firewall.  Adding an exception requires Admin permissions and most Electron applications aren't even installed with Admin permissions (let alone run with them).
2.  Google Chrome has a built in UI for the Chromecast selector.  We would have to implement an interface similar to `electron-chromecast` where it allows clients to implement there on device chooser.
3.  As far as I can tell, running two instances of Google Chrome's MDNS implementation **simultaneously** doesn't play nicely.  So running an Electron application with cast integration enabled and Google Chrome at the same time could cause issues.

Personally I have tried to do this implementation before and failed at these rather significant hurdles (hence the `electron-chromecast` implementation).

**Comment by Martina-Neumayer** [comment]
@evancohen In Mint or Ubuntu you can use this:
http://www.webupd8.org/2016/03/how-to-stream-audio-to-chromecast-or.html
https://github.com/masmu/pulseaudio-dlna
This adds an "system-wide-casting" support to nearly every app in the nstalled OS :)

**Comment by zcbenz** [comment]
I'm closing this issue and reopening #869 since it is the first issue on chromecast.
