### ISSUE TITLE
electron:stderr libGL error: failed to load driver: swrast

### ISSUE THREAD

**Issue by davisford** [electron/electron#7027]
Getting this error running electron in a headless env with [nightmare.js](https://github.com/segmentio/nightmare) wrapper.

node_modules:

```
$ npm ls --depth=1
print-redis@0.0.1 /home/ubuntu/git/warehouse-print
├─┬ aws-sdk@2.5.3
│ ├── jmespath@0.15.0
│ ├── sax@1.1.5
│ ├── xml2js@0.4.15
│ └── xmlbuilder@2.6.2
├─┬ bee-queue@0.3.0
│ └── redis@1.0.0
├─┬ debug@2.2.0
│ └── ms@0.7.1
├─┬ nightmare@2.6.1
│ ├── deep-defaults@1.0.4
│ ├── defaults@1.0.3
│ ├── electron-prebuilt@1.3.4
│ ├── enqueue@1.0.2
│ ├── function-source@0.1.0
│ ├── jsesc@0.5.0
│ ├── minstache@1.2.0
│ ├── mkdirp@0.5.1
│ ├── object-assign@4.1.0
│ ├── once@1.3.3
│ ├── rimraf@2.5.4
│ ├── sliced@1.0.1
│ └── split2@2.1.0
├── node-uuid@1.4.7
└── s3-upload-stream@1.0.7
```

Full log message:

`2016-08-30T01:06:54.372761 print-out[ip-172-31-19-193]: Tue, 30 Aug 2016 01:06:54 GMT electron:stderr libGL error: failed to load driver: swrast`

Seems related to nVidia drivers, but this is a headless EC2 instance? 

* https://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update
* https://www.centos.org/forums/viewtopic.php?t=56273

Is this error benign, or should I investigate a solution?  We are having some failures with this software, but I don't know that it is related to this.

**Comment by zcbenz** [comment]
It is a warning that can be safely ignored, generally we should not print such warnings by default but it came from a third party library that writes the error directly to stderr.
