### ISSUE TITLE
Electron can't catch --squirrel-install event and interrupt installation

### ISSUE THREAD

**Issue by junjunruan** [electron/electron#7033]
* Electron version: 1.2.8
* Operating system: windows

I am using [electron-packager](https://github.com/electron-userland/electron-packager) and [windows-installer](https://github.com/electron/windows-installer) to create the electron windows installer. It works well.

In the electron main.js (the main script) file, there are code to handle squirrel events. But it can't catch/fail the installation process when error happens during running exec().

Here is the sudo code describe what I need:
```
case '--squirrel-install':
  const exec = require('child_process).exec;
  exec(...); // run some commands to create a task in windows task schedule
  if (error) {make installation fail} // if there is an error during exec(), fail the installation
```

**Comment by MarshallOfSound** [comment]
I responded to your duplicate issue over at electron/windows-installer/issues/134

Please do not raise duplicate issues across incorrect repositories in an attempt to get a response.  You raised the issue in the correct place the first time, raising it a second time simply clogs up people's inbox and slows down responses.
