### ISSUE TITLE
Run operation once the application closed

### ISSUE THREAD

**Issue by lordminor** [electron/electron#7034]
* Electron version: All
* Operating system: All

Hi, I've tried for months to apply autoupdate to asar files without success. I understand that isn't security to modify files while the app is running but seriously.. would be very useful an alternative to this. For example...you can download the .asar file to the directory and when the app is closed, replace the files and relaunch the application.

Something similar to quitandAutoupdate.   Is there a way to do this? How we can execute code after the app was closed?

A nice to have: a configuration that allows our app to lock or not the files ...  we can assume our own risks.

Please, take into account this improvement, a lot of users  will be grateful.

Thanks!

Regards.

**Comment by MarshallOfSound** [comment]
I can't confirm how it works on macOS (not familiar enough with Squirrel.Mac

But on Windows this is achieved through Squirrel.Windows and the **only** way it is possible is launching a separate process (in this case Squirrel's `Update.exe` that handles the actual updating process.  On macOS I'm assuming there is some kind of Squirrel daemon that is launched to perform the update in place.

Basically my point is, we have a workable solution on macOS and linux and I'm reasonably sure the standpoint on Linux is that users should be updating their apps through an package repository not through the app itself.

And in answer to your overall question:

>  How we can execute code after the app was closed?

As far as I am aware this is impossible, it would be equivalent to me wanting to uplug my speakers but still hear the music.  Once the app has closed (I.e. has no processes left running) it can't do anything.

The best I can suggest is to do something Similar to Squirrel.Windows where you make a separate utility for each OS that handles the upgrade.  Spawn the OS specific utility, close the app and then the utility can reopen the app once it has done what it needs to do.

I'll leave this open RE: the ASAR unlocking question, but I think I've covered everything else 👍

**Comment by lordminor** [comment]
> As far as I am aware this is impossible, it would be equivalent to me wanting to uplug my speakers but still hear the music. Once the app has closed (I.e. has no processes left running) it can't do anything.

Ahaha. yes , I know. I was thinking in a background service called if for example I used a callback like : quitAndUpdate().

I though a similar solution, make an application to handle the updates..but the problem is the language to use to make that app, and to make it works on mac/linux :(

Thanks for your quick reply :)

**Comment by paulcbetts** [comment]
Squirrel.Windows does this by using a private NT API to determine the parent process's PID then waits for it to exit, Squirrel.Mac does something similar. Trying to edit an ASAR while it's live is a non-starter, sorry

**Comment by zcbenz** [comment]
The only portable solution is to ship a separate program and run it before the app is closed, it is impossible for us to provide a builtin solution since we are not able to run JavaScript code after the app is closed.
