### ISSUE TITLE
webview with empty src loads host url

### ISSUE THREAD

**Issue by nikola** [electron/electron#7035]
* Electron version: 1.3.4
* Operating system: Windows 10 64-bit

I have noticed a side-effect of an unhandled exception in the renderer process.

To reproduce, add e.g.

`throw new Error();`

to the top of the source file that you load into a new `BrowserWindow` with `loadURL()`.

If the `webContents` of the `BrowserWindow` contain a `<webview>`, the `<webview>` will now show the same content as the `webContents` of the `BrowserWindow`, with the `src` of the `webview` pointing to the file URL that was loaded with `BrowserWindow.loadURL()`. DevTools does not reveal if it's recursive, though.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem? I'm unable to reproduce by loading a simple page like this:

```html
  <script type="text/javascript" charset="utf-8">
    throw new Error();
  </script>
  <webview src="http://github.com"></webview>
```

**Comment by nikola** [comment]
Upon further investigation I have narrowed down the issue to a configuration where the `<webview>` is initialized with an empty page that isn't `about:blank` but just an empty string, like so:

`<webview src=""></webview>`

**Comment by deepak1556** [comment]
Was able to reproduce on linux with

```
<script type="text/javascript" charset="utf-8">
    throw new Error();
 </script>
 <webview src=""></webview>
```

**Comment by nikola** [comment]
As of 1.3.6, an empty `src` won't load the host URL anymore, but it won't fire the `dom-ready` event, either, which means that it's currently not possible to wait for `dom-ready` on a `<webview src="">` before calling e.g. `loadURL()` on it. Which effectively makes an empty `src` pointless.

Is this intentional, or a regression?
