### ISSUE TITLE
Backdrop filter is not enabled

### ISSUE THREAD

**Issue by yayolius** [electron/electron#7036]
* Electron version: 1.3.3
* Operating system: Mac Os X El Capitan

Backdrop filter : https://webkit.org/blog/3632/introducing-backdrop-filters/

The backdrop filter is not enabled in electron, it is ignored on developer console.

**Comment by nikola** [comment]
It's not enabled in mainstream Chromium, either.

https://bugs.chromium.org/p/chromium/issues/detail?id=497522

**Comment by yayolius** [comment]
So we need to wait until Chromium gets the feature enabled to have it in
electron?
By the way it seems that in fact it is activated in the current chromium
according to the last comments.

2016-08-30 12:22 GMT-03:00 Nikola Klaric <notifications@github.com>:

**Comment by paulcbetts** [comment]
> So we need to wait until Chromium gets the feature enabled to have it in
electron?

Yes

**Comment by zurajanai** [comment]
Well, you don't have to wait. You can enable the `experimentalFeatures` to use it in your project.
```js
mainWindow = new BrowserWindow({
  webPreferences: {
    experimentalFeatures: true
  }
})
```

**Comment by zcbenz** [comment]
Thanks @zurajanai for providing the solution, I'm closing this issue now.

**Comment by yayolius** [comment]
THANK YOU GUYS. YOU ARE AWESOME
