### ISSUE TITLE
Clean memory 

### ISSUE THREAD

**Issue by fabdelgado** [electron/electron#7038]
* Electron version: 1.3
* Operating system: Windows

My app load images every 1 minute and RAM memory is full in electronjs.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by bpasero** [comment]
Looks like https://github.com/electron/electron/issues/6275

**Comment by kevinsawicki** [comment]
Closing as duplicate of #6275
