### ISSUE TITLE
msvcr/msvcp no longer in release after v1.1.0 -- windows

### ISSUE THREAD

**Issue by leshow** [electron/electron#7039]
* Electron version: 1.1.0
* Operating system: Windows ia32

After and including release 1.1.0 these 2 dlls were no longer present in the release. the only release note says "use visual studio 2015 for building" and makes no mention of statically linking these dlls.

Are they no longer dependencies?

**Comment by kevinsawicki** [comment]
> Are they no longer dependencies?

They are not, see the following pull requests for more details, closing this out.

https://github.com/electron/electron/pull/5538
https://github.com/electron/electron/pull/5602
