### ISSUE TITLE
Build with chromium experimental

### ISSUE THREAD

**Issue by gormat** [electron/electron#7043]
* Operating system: OSX
Is it possible to build electron with this version of chromium ? 
https://chromium.googlesource.com/experimental/chromium/src/
This is experimental chromium source and not released yet.

**Comment by MarshallOfSound** [comment]
The process of upgrading the Chromium version that Electron users is var from trivial and normally involves manually editing a significant number of files to adapt to the latest Chromium changes.

As an example here is (what I consider) one of the smaller Chromium upgrade PR's #6342

So TLDR:  Possible maybe, difficult yes, supported by Electron, no 👍 

However, some Chromium experiments are released under flags in the stable version so it might be worth looking into the features you want from experimental and enabling them with flags if possible

**Comment by MarshallOfSound** [comment]
Oh and I forgot to mention the upstream changes required for each version jump.  The linked PR above pairs with these two PR's

https://github.com/electron/libchromiumcontent/pull/221
https://github.com/electron/brightray/pull/232

**Comment by gormat** [comment]
@MarshallOfSound Thank you. 
I can enable all flags that I need. 
But problem is other, in chromium_src folder are only 4 folders from chromium source that I downloaded, but there are lot of other files. I copied all these files into chromium_src folder, but In libcrhomiumcontent, I have not idea what to change.

**Comment by MarshallOfSound** [comment]
> I can enable all flags that I need. 

So why do you still need Chromium experimental?

As mentioned before it is quite a complicated process.  `libchromiumcontent` is basically a series of patch files and build scripts that pre-compiles a "slightly" modified version of Chromium.  This pre-compiled artifact is then used when building Electron.

> I copied all these files into chromium_src folder

It is no where near this simple, you can't just copy and paste a bunch of unknown heavily modified source files into Electron as all sorts of things have changed inside Chromium between the current version and the experimental version.

Also I forgot this in the first comment but all questions should be directed to the Discussion Forums or to Slack.  Github is for issues only 👍

**Comment by gormat** [comment]
Chromium experimental supports webvr, and only experimental. So I need use experimental sources. 
Ok I will ask it on slack.

**Comment by Jaysonvdw** [comment]
Would going the route of a Progressive Web App perhaps work for you?
