### ISSUE TITLE
Add filter to ignore system widgets for desktopCapturer

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#7044]
* Electron version: 1.3.4
* Operating system: Windows 7-10

On windows in sources are listed a lot of OS widgets, panels and other stuff, that can't be shared appropriate. Is it possible to filter them out, or add some flag in source object for such cases, to have ability to filter them?

**Comment by zcbenz** [comment]
The sources only include what the system considered normal windows, since the system says it is a normal window there is not much thing we can do to find out which are system widgets.
