### ISSUE TITLE
How can I have two webContent in one Window

### ISSUE THREAD

**Issue by Qquanwei** [electron/electron#7045]
* Electron version: 1.3.1
* Operating system: osx

 I want have two webContent in one Window, and I can switch one to front and the other runing in background.
 Can I do it ?

**Comment by MarshallOfSound** [comment]
Use two [`webview`](https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md) tags and use CSS to hide / show them?  Having nested webContents is something that the `webview` tag is designed for. 

In future please ask question in the Discussion Forums or on Slack.  Github issues is intended to be used for bugs.

**Comment by Qquanwei** [comment]
Thanks . 
 But I don't want to use webview tag , webview will appera two scrollbar

**Comment by MarshallOfSound** [comment]
@Qquanwei What do you mean two scrollbars.  If you use CSS similar to this

```css
webview {
  height: 100vh;
  width: 100vw;
  position: absolute;
  top: 0;
  left: 0;
}
```

The webview elements will fill the BrowserWindow completely and the only scrollbar will be the internal scrollbar inside the webview, which for all intents and purposes will look exactly as if it was the main windows scrollbar

**Comment by Qquanwei** [comment]
greet! thanks

At 2016-08-31 18:28:52, "Samuel Attard" <notifications@github.com> wrote:


@Qquanwei What do you mean two scrollbars. If you use CSS similar to this

webview {
  height: 100vh;
  width: 100vw;
  position: absolute;
  top: 0;
  left: 0;
}

The webview elements will fill the BrowserWindow completely and the only scrollbar will be the internal scrollbar inside the webview, which for all intents and purposes will look exactly as if it was the main windows scrollbar
