### ISSUE TITLE
chrome in electron  upgrade

### ISSUE THREAD

**Issue by guohailin0323** [electron/electron#7046]
* Electron version:1.3.4
* Operating system:win10 

hi dear:
I downloaded electron_1.3.4, and write a demo to view the chrome version,chrome

Version is 52.0.2743.82.  However, the latest version of the Chrome browser that can be downloaded on the Internet is 52.0.2743.116. 

Is electron going to upgrade chrome to 52.0.2743.116? When will you upgrade chrome to 52.0.2743.116?

Thank you very much.

**Comment by enlight** [comment]
This is covered in the [FAQ](http://electron.atom.io/docs/faq/#when-will-electron-upgrade-to-latest-chrome)

**Comment by guohailin0323** [comment]
OK, thank you
