### ISSUE TITLE
Electron app seemt to report Javasript being disabled, website won't load

### ISSUE THREAD

**Issue by eric-naguras** [electron/electron#7047]
* Electron version: 1.3.4 ( same in 0.37.8)
* Operating system: OSX 10.11.6 

Javascript seems to report being disabled, some websites don't load.

Suddenly a website does not load anymore in my electron app.
Something changed on the side of the web site as I did not change anything in my app.
Other web sites have no problem loading.

I downloaded Chromium (Version 55.0.2846.0 (64-bit)) to see if that website would show.
Well, it did. But when I disabled Javascript in the Chromium settings, the website did not load in Chromium.

I came across this web site that reports the user agent and some other info.
This site http://www.whoishostingthis.com/tools/user-agent/ says Javascript is disabled when I let my electron app load it.

What can I do to make this website (https://ctoption.com/trade/trading-platform/) load in my electron app (again)

Attached is a most minimal electron app showing Javascript reported as disabled and a link to a non loading web site.

I hope someone can find a work-around or a solution.

Thanks.

[Archive.zip](https://github.com/electron/electron/files/447053/Archive.zip)

Here is the content of  main.js the only other file is package.json

```
const {app, BrowserWindow} = require('electron');
let win;

function createWindow () {
    win = new BrowserWindow({width: 800, height: 600});

    //This url reports Javascript is disabled
    win.loadURL('http://www.whoishostingthis.com/tools/user-agent/',
        {userAgent: 'Chrome', webPreferences: {javascript: true}});

    //This is the web site that does not load
    // win.loadURL('https://ctoption.com/trade/trading-platform/',
    //     {webPreferences: {javascript: true}});

    win.on('closed', () => {
        win = null
    })
}

app.on('ready', createWindow);

 app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit()
    }
 });

app.on('activate', () => {
    if (win === null) {
        createWindow()
    }
});
```

**Comment by MarshallOfSound** [comment]
As far as I can tell this is a side affect of having `nodeIntergration` enabled and the site wanting to use jQuery.

With `nodeIntergration` enabled jQuery detects a commonJS environment and attempts to export itself with `module.exports`.  When you are accessing external sites you should probably disable `nodeIntergration`.

If you change your sample to be

```js
win = new BrowserWindow({width: 800, height: 600, webPreferences: { nodeIntegration: false }});
```

It detects javascript correctly.

**Comment by MarshallOfSound** [comment]
Answering the possible follow before it gets asked 😆 

If you want to use `nodeIntegration` and use this website you can use a `preload` script which has full access to node API's.

**Comment by eric-naguras** [comment]
Thanks for the swift solution.
