### ISSUE TITLE
Creating a new electron application by command line

### ISSUE THREAD

**Issue by vitya1** [electron/electron#7048]
Currently developers to create a new electron application have to make this from scratch or clone existing project.
I think it would be helpful to make possible to create the minimal electron application (https://github.com/electron/electron-quick-start) by using command line.
For example, it can be easily cloned by command:
`electron new my_app`
The same features are in ember-cli or aurelia, for ex.

**Comment by Ikana** [comment]
i would think that would have to be a separate tool, like how [ember-cli](https://github.com/ember-cli/ember-cli/releases) is separate from [ember](https://github.com/emberjs/ember.js/)

**Comment by jlord** [comment]
@vitya1 yeah, this could be a useful module separate from core. But since this isn't a bug with Electron core itself, I'll close this issue here.

**Comment by zcbenz** [comment]
This is tracked at #804.
