### ISSUE TITLE
Make webContents.create API public

### ISSUE THREAD

**Issue by Ikana** [electron/electron#7050]
- Electron version:1.3.4
- Operating system:all

When documenting webcontents.fromId I found the undocumented api webcontents.create, i think it would be useful to document it for headless rendering.

**Comment by zeke** [comment]
Sounds good to me!

**Comment by Ikana** [comment]
Should the options that you can pass to webcontents.create be documented as well?  if I am not mistaken, the options are same as webPreferences from BrowserWindow, right?

**Comment by zcbenz** [comment]
It should not be documented at least for now, the API is currently very dangerous to use and we have to make sure the default behavior is safe before actually exposing it.
