### ISSUE TITLE
Accelerators not working in current electron (prebuilt) 1.3.4

### ISSUE THREAD

**Issue by kferrio** [electron/electron#7051]
* Electron version: 1.3.4
* Operating system: Windows 10

Menu item works as expected when clicked but does nothing in response to Ctrl-Q.  Used info at [https://github.com/electron/electron/blob/master/docs/api/accelerator.md]

```
const electron = require('electron')
const {app, BrowserWindow, Menu} = electron

let menuTemplate = [
  {
    label: 'Menu',
    submenu: [
      {
        label: 'Quit',
        accelerator: 'CmdOrCtrl+Q',
        click: function () { app.quit() }
      }]
  }
]

app.on('ready', function () {
  new BrowserWindow()
  const menu = Menu.buildFromTemplate(menuTemplate)
  Menu.setApplicationMenu(menu)
})
```

**Comment by zeke** [comment]
Are you able to reproduce the issue on other versions of Electron, or is it unique to 1.3.4?

**Comment by kferrio** [comment]
@zeke - have not tried other versions of electron; believe 1.3.4 is latest; just kicking the tires and was surprised by this non-obvious behavior; a quick Google/SO search did not turn up anything relevant

**Comment by kferrio** [comment]
Aha! The accelerators work if the DevTools are open!  If the DevTools are not open, then the accelerators do *not* work.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by kferrio** [comment]
The code in this report is a minimal full program to reproduce. Invoke in
the usual way, `electron .` in the package.json directory.  (Alternatively,
take the menu example from the Menu docs, but that's far from minimal.)

**Comment by zcbenz** [comment]
You have to load a page by calling `loadURL`, the accelerators work by first sending the keyboard events to the page and then mach the accelerators table, so if there is no page at all the chain would be broken.

A better way is probably to send the keys to accelerators table directly when there is no page, but considering BrowserWindow is useless without loading a page, I'm closing this as won't fix.

**Comment by bhaveshgohel** [comment]
@kferrio @zeke @zcbenz : Loading the blank index.html solve the issue!

main.js
```js
const electron = require("electron")
const app = electron.app
const BrowserWindow = electron.BrowserWindow
const Menu = electron.Menu

let mainWindow;

app.on("ready", _=> {
	mainWindow = new BrowserWindow()
	mainWindow.loadURL(`${__dirname}/index.html`)
	const template = [
		{
			label: "Menu",
			submenu: [{
				label: 'Quit',
				click: _=> { app.quit()	},
				accelerator:'CmdOrCtrl+Q'
			}]
		}
	]
	
	const menu = Menu.buildFromTemplate(template)
	Menu.setApplicationMenu(menu)
})

**Comment by kferrio** [comment]
@zeke @zcbenz Thank you!  Where can I read about the Electron event
lifecycle? Is it in each module or If it's comprehensively documented in
one place that would be very helpful for architecting apps.

Thanks for taking time to explain this!

**Comment by kferrio** [comment]
@bhaveshgohel - Thanks for the complete working example!
