### ISSUE TITLE
Startup error: `protocol.registerStringProtocol` is not a function

### ISSUE THREAD

**Issue by craxal** [electron/electron#7052]
* Electron version: 1.2.3 (forked)
* Operating system: Windows 10

I've got a Typescript Electron application that's not loading the entire `protocol` module. In the main process:
```
import { app, protocol } from "electron";
...
app.on("ready" () => {
    console.log(protocol);
    protocol.registerStringProtocol(...);
});
```
According to the 1.2.3 documentation, `registerStringProtocol` should be there. But outputting the protocol object prints this:
```
{ registerStandardSchemes: [Function] }
```

Then the app crashes. Am I missing something?

**Comment by zcbenz** [comment]
This had been fixed in later versions of 1.2.x, you can search the changelog to find out the version that works.

**Comment by craxal** [comment]
Yes, the documentation says it was fixed in 1.2.5.

However, I created a small Electron application using v1.3.1 (the real thing, not a fork), and I still have this issue.
```js
var electron = require("electron");
var app = electron.app;
var BrowserWindow = electron.BrowserWindow;
var protocol = electron.protocol;

var mainWindow;
function createWindow() {
    mainWindow = new BrowserWindow({ width: 800, height: 600 });
    mainWindow.loadURL("file://" + __dirname + "/renderer/index.html");
    mainWindow.on("closed", function () {
        mainWindow = null;
    });
}

app.on("ready", function () {
    console.log("The 'protocol' module contains the following objects: ");
    console.log(protocol);
    createWindow();
});
app.on("window-all-closed", function () {
    if (process.platform !== "darwin") {
        app.quit();
    }
});
app.on("activate", function () {
    if (mainWindow == null) {
        createWindow();
    }
});
```

My console prints out:
```                                                                                                                                                           
The 'protocol' module contains the following objects:                                                                                                                                                           
{ registerStandardSchemes: [Function],
  getStandardSchemes: [Function] }
```

**Comment by kevinsawicki** [comment]
> console.log(protocol);

If you change this line to:

```js
console.log(protocol.registerStringProtocol);
```

What does it print out?

**Comment by craxal** [comment]
Hmm... Well, that prints out:
```
The 'protocol' module contains the following objects:
[Function]
```
Not sure why that function shouldn't appear when printing out `protocol`. I'll keeping moving from here and report back if problems occur. Thanks for the help.

**Comment by kevinsawicki** [comment]
> Not sure why that function shouldn't appear when printing out protocol.

I think that might be because that object is now a Proxy and there might be an issues with the keys and  property descriptor fetching for it.

https://github.com/electron/electron/blob/691aec701fc66608e9b076d5eab453db8eee904b/lib/browser/api/protocol.js#L18-L26
