### ISSUE TITLE
Error in  electron/docs/api/clipboard.md

### ISSUE THREAD

**Issue by thardes2** [electron/electron#7056]
I think there is an error in  electron/docs/api/clipboard.md

Here we have:
```javascript
const {clipboard} = require('electron')
clipboard.writeText('Example String')
```
,but I think it should be:
```javascript
const {clipboard} = require('electron').clipboard
clipboard.writeText('Example String')
```

**Comment by vsemozhetbyt** [comment]
@thardes2 This is not an error, see [Object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring)

**Comment by MarshallOfSound** [comment]
As @vsemozhetbyt this is not an error, rather a feature in the ES6 spec of Javascript known as [Object Destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring)

**Comment by MarshallOfSound** [comment]
And for my own sanity I ran the sample in Electron to ensure that it did actually work.  And it does 👍 

😆
