### ISSUE TITLE
Accessing the DOM tree inside a child process

### ISSUE THREAD

**Issue by ClementNerma** [electron/electron#7057]
* Electron version: 1.2.2
* Operating system: Windows 10 Home Edition, 64-bits

I have a script with turns into the renderer process and create child processes to run some special code. I need the code runned inside the child process to access the DOM.
When the process is created (with `child_process.fork()`) I send some informations using the built-in IPC channel such as the timestamp, some informations about the script which will run inside the child process...

But when I try to send an instance of a class it doesn't work at all :

```JavaScript
// main.js
const child_process = require('child_process');
const child = child_process.fork('child.js');
child.send({ready: { version: '0.0.1', dom: document }});

// child.js
process.on('message', (m) => {
    typeof m.dom.body.appendChild; // ReferenceError
});
```

I suppose that is a limitation of IPC communication that can only transmit some specific datas, but I know it's possible to send a server or a socket instance using an IPC channel, so I don't understand why it's not possible to transmit a Document.

So I was looking for a way to access the DOM from the child process but I didn't found any solution.
The code inside the child process needs to do a lot of operations on the DOM and can't use IPC communication to access it, else the performances will be too slow.

So, my question is : Is there any way to access the DOM from a child process ?

**Comment by MarshallOfSound** [comment]
> So, my question is : Is there any way to access the DOM from a child process ?

No, IPC can not support DOM objects

See #6998 for a bit more info

**Comment by ClementNerma** [comment]
Thanks for this answer. Is there a way to override the `ELECTRON_RUN_AS_NODE` variable when creating a new child process ?
Or is there a way to do that by changing the source code of Electron ?

**Comment by MarshallOfSound** [comment]
@ClementNerma Check out this answer on a similar issue

https://github.com/electron/electron/issues/6656#issuecomment-236340999

Basically use `spawn` instead of `fork`

**Comment by ClementNerma** [comment]
Using the `spawn` method doesn't permit me to access the renderer process' DOM tree. The file runned with `child_process.spawn()` is considered as the electron's main process file, so I'm only able to make a new Electron window with it.

**Comment by MarshallOfSound** [comment]
`child_process.spawn()` can use IPC just the same as `fork()`

**Comment by ClementNerma** [comment]
Yes but that doesn't solve my problem, how the `spawn()` method can permit me to access the DOM ?

**Comment by MarshallOfSound** [comment]
@ClementNerma It doesn't give direct access to DOM.  If you are trying to manipulate the DOM from another process you might need to rethink your apps architecture.

You can send and receive custom IPC events to create and remove elements though.  Just set up your own listeners and senders.

Why do you need to access the DOM from a child process?

**Comment by ClementNerma** [comment]
I'm making an application with runs like a desktop environment for Linux. It is built with Electron.
The renderer process manage the system and can also run applications. These applications needs to have a DOM access for displaying things. They are runned into a `vm` to limit their scope and the things they have access to.
The system needs to be able to stop the application, but a vm doesn't permit that. So I run it into a child process. Also that permit to have greater performances because the applications which needs the more performance will have a bigger priority than the other when they run into another processes.

If I run all applications into a single process, the performances will be very bad.

**Comment by MarshallOfSound** [comment]
It sounds to me like you are trying to do something that Electron's IPC architecture was never designed to support,

> I need to permit at leat ten thousand of operations on the DOM tree per second, else it will be so slow.

This just straight up isn't possible.  I couldn't do tens of thousands operations on the DOM per second in the same `webContents` let only over some kind of IPC wrapper...

>  I didn't find any way about synchronous IPC communications.

You can do synchronous IPC communication between `renderer` and `main` processes using `ipcRenderer.sendSync`

**Comment by ClementNerma** [comment]
> It sounds to me like you are trying to do something that Electron's IPC architecture was never designed to support

That's possible, and that's why I created this issue.

> You can do synchronous IPC communication between renderer and main processes using `ipcRenderer.sendSync`

Yes, but not between renderer process and child processes.

Thanks for your support !

**Comment by ClementNerma** [comment]
I reply here to post a way I've finally found to solve this problem :
By running the untrusted application's code into a `<webview>` tag inside the renderer's DOM tree, it's possible to allow the code to run into another process (`webview` *always* run into a new process) and access a DOM tree they can manage. The main frame cannot access to the webview's content but that's not a problem here.
When the main frame wants to stop the application, we just have to remove the `webview` element, that will stop all JavaScript code running inside it.
The only remaining problem is that the new `webview` will not be able to access any element parent to it. But that solve the biggest problem I had.
