### ISSUE TITLE
--enable-logging flag does not show beyond 1 console log argument

### ISSUE THREAD

**Issue by koush** [electron/electron#7061]
* Electron version:
1.3.4
* Operating system:
osx el capitan

https://developer.mozilla.org/en-US/docs/Web/API/Console/log

--enable-logging only shows the first argument when invoked in renderer process.

https://developer.mozilla.org/en-US/docs/Web/API/Console/log

Maybe it's assuming further arguments are always string substitutions? Can fix that by seeing if the resultant formatted string is equal to the first argument (in which case it's not a format string), and then space delimit join the arguments.

Ie, in a renderer process:
```javascript
console.log('foo', 'bar')
```
shows:
```
[30033:0901/135722:INFO:CONSOLE(15)] "foo", source:file.js (1)
```

from the main process, it shows
```
foo bar
```
as expected.

**Comment by zcbenz** [comment]
This is an upstream Chromium bug and they decided to leave it be:
https://bugs.chromium.org/p/chromium/issues/detail?id=365427
