### ISSUE TITLE
npm install electron fails on 32bit link is 404

### ISSUE THREAD

**Issue by uokios** [electron/electron#7063]
```
# npm install electron
\
> electron@1.3.4 postinstall /root/node_modules/electron
> node install.js

Downloading electron-v1.3.4-linux-x87.zip
Error: GET https://github.com/electron/electron/releases/download/v1.3.4/electron-v1.3.4-linux-x87.zip returned 404
/root/node_modules/electron/install.js:22
  throw err
  ^
```
should be: https://github.com/electron/electron/releases/download/v1.3.4/electron-v1.3.4-linux-ia32.zip

**Comment by kevinsawicki** [comment]
> Downloading electron-v1.3.4-linux-x87.zip

Did you possibly run it with `--arch x87` instead of `--arch x86`?

**Comment by kevinsawicki** [comment]
What is the output when you run `node -p 'process.arch'`?

**Comment by uokios** [comment]
```
# node -p 'process.arch'
x87
```
```
 npm install electron --arch ia32
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'ia32' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.6.0-1-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron" "--arch" "ia32"
npm ERR! cwd /root
npm ERR! node -v v4.3.1
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
```

**Comment by kevinsawicki** [comment]
> x87

`npm install` used the reported `process.arch` value to download the appropriate binary. The `arch` versions supported on Linux are `x86` `ia32` and `arm`.

If you download the `ia32` version directly does it run?

**Comment by uokios** [comment]
had to install libs and now its dosent error out but no idea if its working or how to use it
it just returns me to prompt
wanted to use it with nightmare to capture web pages
im off to bed now

**Comment by zeke** [comment]
Nightmare [includes Electron (aka electron-prebuilt) as a dependency](https://github.com/segmentio/nightmare/blob/3f8ef354cc144a70e52630bec4f508d0f6f521fe/package.json#L23), so you shouldn't have to manually install Electron to use Nightmare. 

`npm install nightmare` should do the trick.

**Comment by kevinsawicki** [comment]
> npm install electron --arch ia32

I think it needs to be this instead:

```
npm install electron --arch=ia32
```

Electron only ships binaries for two architectures right now on Linux, `ia32` and `x64`, if those options don't work for your machine then you may need to build Electron yourself.
