### ISSUE TITLE
How to  save file to specific directory 

### ISSUE THREAD

**Issue by disc9562** [electron/electron#7065]
* Electron version: 1.3.4
* Operating system: Windows 8.1
I am using spectron to test my app. I am opening dialog in my app like this:

        ipc.on('open-directory-dialog', (event, arg) => {

        let returnValue = function(directory) {

        if (typeof directory !== 'string') {

          directory = directory[0]
        }
        event.returnValue = directory
          }
          let options = {
            properties: [
             'openDirectory'
           ]
         }
          if (process.platform !== 'darwin') {
             dialog.showOpenDialog(options, (directory) => {
               if (directory) {
                 returnValue(directory)
              }
        })
        return
          }
        returnValue(dialog.showOpenDialog(BrowserWindow.fromWebContents(event.sender), options))

And I want to auto select directory in test. I am using preload to do that. But it will make my app crash.

    //preload
    if (process.env.RUNNING_IN_SPECTRON) {
          dialog.showOpenDialog = (opts, cb) => {
            if (opts.title === 'open-directory-dialog') {
              cb(['C:/Users/user/Desktop/']);
              }
           };
       }
Any ideas?

**Comment by kevinsawicki** [comment]
Moving this over to the spectron repository for further discussion, https://github.com/electron/spectron/issues/112
