### ISSUE TITLE
Local storage support on electron startup.

### ISSUE THREAD

**Issue by nuruddeensalihu** [electron/electron#7066]
* Electron version: v1.2.5
* Operating system: Mac osx.

Please i am using this wonderful tool to build my desktop app. But my problem is, my app uses browser localstorage to store few info such as authentication. However, all the example i could find on electron shows how to start the electron creating new browser instance in the process. Hence user is ofetn asked to login again when ever he start the electron app. On My electron.js file i noticed the line

```
app.on('ready', function() {

    const menu = Menu.buildFromTemplate(template);

    Menu.setApplicationMenu(menu);
    mainWindow = new BrowserWindow({
        width: 1024,
        height: 680,
    });

}
```

mainWindow = new BrowserWindow is called all the time. Please is there anyway i can bypass this and ensure the support for local storage instead? I want it to be in such a way that whenever authenticated user restart the app, he should not be asked for authentications again. Please your help would highly be appreciated.

**Comment by akashnimare** [comment]
Electron does support local storage and you don't need to relogin to any auth server. You should use the latest version of electron.

**Comment by nuruddeensalihu** [comment]
@akashnimare thank you for the prompt reply. Please with regard to 
```
mainWindow = new BrowserWindow({
        width: 1024,
        height: 680,
    });
```

Wouldn't running this on code initiate new instance of browser windows ? My authentication depend on the localstorage data from the localStorage . How to i utilise those data when user exit and reopen the app ?

**Comment by MarshallOfSound** [comment]
@nuruddeensalihu The `localStorage` session is persisted even when calling `new BrowserWindow()`.  

Read more about `webContents` sessions here http://electron.atom.io/docs/api/session/

You can demonstrate this by opening the default app and running `localStorage.setItem('foo', 'bar')` then closing and reopening and running `localStorage.getItem('foo')`

You will see that the value has been persisted

**Comment by nuruddeensalihu** [comment]
@MarshallOfSound thank you for the prompt reply. I guess i have to install latest version. Thank you .
