### ISSUE TITLE
How to modify accelerate in the running process

### ISSUE THREAD

**Issue by ordinaryXg** [electron/electron#7069]
* Electron version:1.3.4
* Operating system:window 10

I have modified the accelerate in the process of running,
![image](https://cloud.githubusercontent.com/assets/20763991/18195851/97033606-7120-11e6-8c2e-913c3f9d28cd.png)

**Comment by zeke** [comment]
Can you provide a minimal app that reproduces this problem?

**Comment by Flx455261624** [comment]
A little difficult 
 Can I ask you a question??
 I tested accelerate other attributes are OK ,  label and  and some other properties .
   Do you know what are accelerate format , string?

**Comment by Flx455261624** [comment]
@zeke

**Comment by akashnimare** [comment]
@Flx455261624 what are you trying to do? A minimal app will help us reproducing this issue. Do you want to dynamically change/modify menu item?

**Comment by Flx455261624** [comment]
@akashnimare  yes ,I want to dynamically change/modify menu items
![image](https://cloud.githubusercontent.com/assets/20763991/18244099/e557612a-7390-11e6-89f7-96ef575f7062.png)
![image](https://cloud.githubusercontent.com/assets/20763991/18244109/ebb5f522-7390-11e6-9869-c444c4b54e4a.png)

When I "set (path, the index {accelerator: 'CmdOrCtrl + E})", an error

**Comment by kevinsawicki** [comment]
You cannot update the accelerator once it has been created, if you need to change this item you'll have to create a new `MenuItem` and/or `Menu` and update the application's menu with the altered item.
