### ISSUE TITLE
Specific site throws error in Electron

### ISSUE THREAD

**Issue by scytalezero** [electron/electron#7071]
* Electron version: 1.3.5
* Operating system: Windows x64

I'm using [Nightmare](https://github.com/segmentio/nightmare), a browser automation library that is based on Electron (and Electron is awesome!). I am having a problem where a specific site, I guess maybe due to some JS they are using, is throwing an exception in Electron. I did raise this to the Nightmare team first but it seems to be a problem in Electron.

I believe this to be an Electron problem specifically because of the path referenced in the error message and also because I was able to trace the introduction of this problem to Electron 1.2.6. In other words, before 1.2.6 this exception did not occur and everything worked as usual. The problem persists at least until 1.3.5 which I tested this morning. Anyway, here is a quick snippet that will demonstrate the problem. If you comment the first goto() and uncomment the second (to google.com) then you will see typical behavior: the title of the page is logged. Running it as is will leave the Electron window visible and the Nightmare code does not continue.

```javascript
const nightmare = require("nightmare")({ show: true, width: 1000, electronPath: require('electron') })
nightmare
  .goto("https://vip.pet-records.com/users/sign_in")
  // .goto("https://www.google.com")
  .title()
  .end()
  .then(result => {
    console.log(result)
  })
```
Here is the error observed when I open the dev console in Electron (no further stack trace):
```
lib-08805c6….js:10 Uncaught SyntaxError: Invalid regular expression: /^C:\Users\bcreel\Documents\Node\muninn\node_modules\electron\dist\resources\/: \ at end of pattern
```
Thanks for this great project!

**Comment by kevinsawicki** [comment]
> lib-08805c6….js:10 Uncaught SyntaxError: Invalid regular expression: /^C:\Users\bcreel\Documents\Node\muninn\node_modules\electron\dist\resources\/: \ at end of pattern

Are you able to include the source from that line?

It looks like some code is trying to create a regular expression from an electron path and isn't properly escaping regex special characters that may exist in that path.

**Comment by scytalezero** [comment]
Sure. I'm attaching a screenshot of the error source and the zipped source file:

![2016-09-06 15_31_25-log in to apollo](https://cloud.githubusercontent.com/assets/704908/18287923/1b1655e4-7447-11e6-8b0e-d2105a1d170f.png)

[lib-08805c69390428f6bd7f2e9c7c92214a.zip](https://github.com/electron/electron/files/457601/lib-08805c69390428f6bd7f2e9c7c92214a.zip)

**Comment by kevinsawicki** [comment]
> Sure. I'm attaching a screenshot of the error source and the zipped source file:

The polyfill on that site for `String.prototype.startsWith` is definitely buggy. If you run `'\\'.startsWith('\\')` from the Console you'll see the same error.

I don't think this an Electron issue but I'm not sure why the Electron version change would impact this polyfill coming into play.

**Comment by scytalezero** [comment]
Gotcha. This does look to be some malfeasance on the part of the site. Thanks for checking it out!

Closing this issue.

**Comment by jokyme** [comment]
the same issue with electron 1.7.9
@scytalezero how did you solve this problem ?

**Comment by ASH-Bryan** [comment]
I reverted to the earlier version of electron, but eventually moved on to puppeteer.
