### ISSUE TITLE
persistent cookies should be encrypted

### ISSUE THREAD

**Issue by ccnokes** [electron/electron#7073]
This request may be unfeasible or out of scope, in which case, feel free to just close/delete. But no one seems to have brought this up before so I thought I'd mention it. 

My org's security team recently recommended that we encrypt the cookie value of our app's session cookie. They don't like that someone could open the sqlite cookies file and view the session token in plain text. Our web app uses a session cookie as it's authentication mechanism, so I'm stuck with storing that token in a cookie. Because Chrome encrypts cookie values by default, it would be nice to be able to encrypt cookie values in Electron too. If not the whole cookie store, then maybe having some middleware on `session` that gets run before `get`/`set` so that I can encrypt/decrypt it on get/set--that way it's persisted encrypted, but to the web app, it's unencrypted. 

If there's a way to do this currently that I'm overlooking, let me know 😸 .

**Comment by zcbenz** [comment]
@deepak1556 After merging the fix OS X would emit a warning dialog every time when Electron runs:

<img width="546" alt="screen shot 2016-09-19 at 4 24 21 pm" src="https://cloud.githubusercontent.com/assets/639601/18624871/af751bc4-7e85-11e6-8ffb-512e2de44284.png">

After a deep looking it seems that the change would just read and store from the same security storage with Chromium browser (and all other Electron apps), which is going to cause problems. And it also makes existing apps lose cookies after updating Electron. 

So I'm reverting the change and reopening this issue.

**Comment by deepak1556** [comment]
Should have asked for help to verify on OS X, there are two things we can do either override `CookieCryptoDelegate` with our version of encrypt and decrypt functions or provide an api in `session.cookies` to let users provide their version of the functions.

**Comment by tmaher** [comment]
[Reading over the high-level docs for Keychain](https://developer.apple.com/library/content/documentation/Security/Conceptual/keychainServConcepts/02concepts/concepts.html#//apple_ref/doc/uid/TP30000897-CH204-SW11), specifically the "Sharing Keychain Items" section, it looks like code signing is required to retain keychain access across recompiles. Specifically, the `keychain-access-group` entitlement seems to be governing. Unfortunately, this is at about the edge of my xcode experience. I did find these, which might help:

1. Walkthrough of "Configuring Keychain Sharing" in xcode: https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html#//apple_ref/doc/uid/TP40012582-CH26-SW15
1. An iOS project's experience with setting up keychain sharing: https://github.com/fastlane/fastlane/issues/4397

**Comment by yklykl530** [comment]
Excuse me, do you have the latest progress on cookie encryption? We also have this problem now

**Comment by dengyaolong** [comment]
+1

**Comment by LaynelLarsen** [comment]
+1 Is there any progress on cookie encryption?

**Comment by paulbennet** [comment]
Seems its been nearly an year since the last comment. Our app also requires this. Can someone let us know if this is possible ?

**Comment by soundar78** [comment]
We also require cookie encryption in our app. Let us know whether this will be taken up any time soon.
@zcbenz @deepak1556

**Comment by nornagon** [comment]
We should be able to do this once we switch to using the new network service in Chromium.

**Comment by paulbennet** [comment]
@nornagon can you point me somewhere to read about "new network service" you have mentioned ?

**Comment by nornagon** [comment]
It's an internal Chromium refactor, and should be largely transparent to Electron users. There's a short design doc from Chromium here: https://docs.google.com/document/d/1wAHLw9h7gGuqJNCgG1mP1BmLtCGfZ2pys-PdZQ1vg7M/edit

**Comment by paulbennet** [comment]
From what I understood from above design doc, It seems a major refactor. Should take a considerable amount of time.

Meanwhile, it is possible to workout something proposed by deepak above https://github.com/electron/electron/issues/7073#issuecomment-248217090 ?

We have an app in production with considerable user-base. We currently rely on cookies for auth as we wrap our web-app in BrowserWindow and provide native extensions ( like offline-db, filesystem management, etc ) over it. So incase there's no other solution, we have to do major refactor !

**Comment by deepak1556** [comment]
@paulbennet that comment is no longer valid, the designs have changed. We could enable cookie encryption now without the network service, but it will still be a breaking change for users because the existing cookie store for apps will be discarded and new version will be created on the system. Apps will have to perform their cookie transitions using the `session.cookies` api to retain the behaivors.

The network service will be enabled as a part of a major electron release, so it seems like the ideal candidate to make this change.

**Comment by paulbennet** [comment]
@deepak1556 @nornagon .. Any idea on when this new network service will be added to electron release ?

"We could enable cookie encryption now without the network service" - I guess you are mentioning about the PR you made earlier. Isn't it possible to make it optional via any switches ? or options ? ( https://electronjs.org/docs/api/app#appcommandlineappendswitchswitch-value )

**Comment by MarshallOfSound** [comment]
@paulbennet The Network Service work is still ongoing and cookie encryption is definitely not enabled or enable-able through a flag at this point

**Comment by craigdanj** [comment]
@MarshallOfSound Is there a version number we can expect this in? Or a rough timeline by which we will have the Network Service feature available to use? Just so we know by when we should be able to fix this issue by.

**Comment by MarshallOfSound** [comment]
This is implemented in Electron as of #27524 behind a fuse 👍

**Comment by soundar-m** [comment]
Hi @MarshallOfSound 
i tried enabling cookie encryption, and it does seem to be enabled when checking the state of the fuse as mentioned [here](https://www.electronjs.org/docs/latest/tutorial/fuses#the-easy-way) after the app is packaged
![image](https://user-images.githubusercontent.com/65405184/190950459-d6c583ad-067a-4915-8250-952b3379a7fa.png)

but the cookies are not getting encrypted and **My App Safe Storage** was not created in keychain when launching the app after enabling encryption.

My understanding from this [doc](https://www.electronjs.org/docs/latest/tutorial/fuses#cookieencryption) 
> if you enable this fuse existing unencrypted cookies will be encrypted-on-write

& this [PR](https://github.com/electron/electron/pull/27524)
> Migration paths from Un-Encrypted to Encrypted is completely handled by Chromium

is that just enabling the fuse should be enough and the migration from un-encrypted to encrypted will be handled by chromium in electron.
have i misunderstood something ? do we have to handle anything else to make cookie encryption work ?
