### ISSUE TITLE
arm version missing in releases 1.3.5

### ISSUE THREAD

**Issue by justbill2020** [electron/electron#7075]
* Electron version: 1.3.5
* Operating system: raspbian jessie

missing file
https://github.com/electron/electron/releases/download/v1.3.5/electron-v1.3.5-linux-arm.zip".

**Comment by kevinsawicki** [comment]
This file was renamed in `1.3.5` to match the naming convention of node's arm builds via #2343 and #6986 

Since downstream libraries such as `electron-prebuilt` don't support this yet, I'll upload a new asset with the old name to the `1.3.5` release shortly.

**Comment by justbill2020** [comment]
thank you...

**Comment by kevinsawicki** [comment]
@justbill2020 I copied the `*-armv7l` assets as `*-arm` and updated the release, can you verify that `npm install electron` now works for you on Electron 1.3.5 on ARM?

**Comment by En-TACT** [comment]
I just ran it and now downloading.. thanks!

**Comment by kevinsawicki** [comment]
Closing this out, will make sure future releases still have the main Electron asset available as just `arm` to prevent breakage until `electron-download`, `electron-prebuilt` and `electron-packager` have all been updated.

**Comment by zcbenz** [comment]
@kevinsawicki We can probably keep uploading both `arm` and `armv7l` for now, and then remove `arm` after 2.0 release.
