### ISSUE TITLE
How to make a window that fills the screen without being "fullscreen"?

### ISSUE THREAD

**Issue by zeke** [electron/electron#7076]
I want my new BrowserWindow instance to fill the screen, but I don't want it to be `fullscreen` in the sense that it creates a new "virtual screen" or whatever those are called on OS X where the menu bar and window buttons are hidden and the whole screen slides over.

Here's how I'm doing it now:

```js
app.on('ready', () => {
  let {width, height} = require('electron').screen.getPrimaryDisplay().size
  win = new BrowserWindow({width: width, height: height})
})
```

Is that the best way to accomplish this?

**Comment by kevinsawicki** [comment]
Would `win.maximize()` do what you want?

http://electron.atom.io/docs/api/browser-window/#winmaximize

**Comment by zeke** [comment]
Yes! Thanks.

This is how to maximize without causing a perceptible resize event on startup:

```js
win = new BrowserWindow({show: false})
win.maximize()
win.show()
```

**Comment by kanalasumant** [comment]
@zeke perfect! Just a quick I'd like to make. On windows I'm running electron 1.7.9 and win.maximize() seems to do the job. win.show() seems optional. Correct me If I'm wrong!

**Comment by ddombrowsky** [comment]
@kanalasumant at least on my installation, `mainWindow.show()` is required on OSX, and not on anything else.  The window will not show without it.

**Comment by wangxiaomo** [comment]
here's a note on OSX.
if you want it fullscreen and not resizable, you should call `setResizable(false)`  after `maximize()`, instead of putting this option in the constructor.

**Comment by krthr** [comment]
@wangxiaomo, same on linux (and, i think, Windows)
