### ISSUE TITLE
Printing Does not throw any Errors

### ISSUE THREAD

**Issue by sameel** [electron/electron#7078]
- Electron version: 1.3.4
- Operating system: Windows 10

The printing function does not return any errors if, for example. the user didn't have any printers installed, it would still give successful print even thou it sent the print job to nothing and found no printer

**Comment by codebytere** [comment]
We no longer release bugfixes for versions of Electron older than `1.6.x` so i'm going to close this but if it is still present in later versions we can look to reopen it.
