### ISSUE TITLE
Support non-detached devtools for webviews

### ISSUE THREAD

**Issue by Sh1d0w** [electron/electron#7080]
* Electron version: latest
* Operating system: Linux

I was wondering why this check is hardcoded here:

https://github.com/electron/electron/blob/46b257944113bba1c1258c485757bef421a5e110/atom/browser/api/atom_api_web_contents.cc#L944

Is there any practicular reason for developer tools to always be detached for web views and what is the problem making this configurable like it is stated in the [docs](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsopendevtoolsoptions)?

This is related to this issue here https://github.com/brave/browser-laptop/issues/3555

Thank you

**Comment by Sh1d0w** [comment]
cc @kevinsawicki

**Comment by kevinsawicki** [comment]
I'm guessing this was to make it easy to disambiguate the docked dev tools for the owner window from the webview dev tools.

Will investigate further.

**Comment by kevinsawicki** [comment]
Looks like this has come up previously and isn't possible because the webview is a plugin and the docked devtools are implemented using a native view: https://github.com/electron/electron/issues/3177

I'm going to close this out here.
