### ISSUE TITLE
[linux] HTTP-Requests, undetermined behavior

### ISSUE THREAD

**Issue by JohnnyCrazy** [electron/electron#7083]
- Electron version: 1.3.5
- Operating system: Arch Linux x86_64, Kernel: 4.6.4-1-ARCH
### Issue:

When executing HTTP-Requests with any kind of library (tested with `request` and `unirest`), the requests tend to hang up. But sometimes, one request will succeed but following ones won't. This is just happening on linux, it worked fine on Windows
### Reproduce:
- `git clone https://github.com/electron/electron-quick-start`
- `cd electron-quick-start && npm install && npm install request --save`
- Add the following to `renderer.js`:

```
var request = require('request');

request('https://google.com', function (error, result, body) {
  console.log(result.statusCode);
  request('https://github.com', function (error, result, body) {
    console.log(result.statusCode);
  });
});
```
- Executing `node renderer.js` will output `200` two times --> Correct
- Calling `npm start` will output nothing in the devtools-console --> Error

---

I thought of a misconfiguration of my machine first, but since it works in the normal `node`-env, I'm suspecting there is something wrong with the renderer process. Can anyone reproduce this?

**Comment by enlight** [comment]
Just so we're clear, you're looking for output in the DevTools console of the browser window right?

**Comment by JohnnyCrazy** [comment]
@enlight Yes.

In very rare cases one `200` will get printed to the console, you really can't determine the output at all, very strang :/

**Comment by deepak1556** [comment]
I am unable to reproduce the issue on the same distro.

**Comment by JohnnyCrazy** [comment]
@deepak1556 
Guess there is something wrong on my end then, although I don't have the slightest idea what the issue could be. Thanks tho, closing this then.

**Comment by BenoitZugmeyer** [comment]
@JohnnyCrazy Hi, you are not alone. I already opened an issue about this a while ago #1268 . I tried really hard to solve it but couldn't figure it out at the time. After a while it worked for me but I didn't do further tests because I stopped working on my project.

Now I am starting a new project with electron, the issue is still there! I reproduce with this minimal test case:

* Create a file `test.js` with the following:
```javascript
const http = require("http");

const url = "http://atom.io";

http.request(url, function () {
    console.log("END FIRST");
    http.request(url, function () {
        console.log("END SECOND");
        process.exit();
    }).end();
}).end();
```
* Execute it with `node test.js`: works without any issue (prints both messages)
* Execute it with `electron test.js`: the first message is printed, but the second request hangs. Note: this is not always the case, but usually I can reproduce after a few tries (`while true; do electron test.js; done`)

It seems to be ArchLinux related since I also use it. I'd love to know if you finally found a solution for this issue.

Electron version: v1.4.7
Operating system: ArchLinux, Linux 4.8.8-1-ARCH

**Comment by JohnnyCrazy** [comment]
Hi @BenoitZugmeyer , Woho, I'm not alone 🎉 

In my case I needed to make a continious HTTP-Request every second. Because of that I didn't care if one request was failing/never responded, I just ignored the bug for my prototype. 

---

However, I think it's somehow really an issue with the event-loop: Often, the first requests returns when you start the second one. The second one only  returns if you start a third one and so on. But sadly I'm not a NodeJS-internals pro, so I have no idea where to look at all.

**Comment by BenoitZugmeyer** [comment]
Given [the number of patches in the Arch electron package](https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/electron), the maintainer (hi @tensor5 !) seems to have a pretty good understanding of low level electron issues. Maybe he heard something about it, or we could open an issue on the Arch bug tracker.

BTW, I reproduced the issue with both the prebuilt electron binary from NPM and the one within the Arch package community/electron.

Funny enough, resizing my terminal unhangs the second request... pretty crazy!

**Comment by BenoitZugmeyer** [comment]
It seems that adding a `setInterval(() => {}, 10)` to my example above to force the event loop to wake up mitigate the issue (without having to make a HTTP request every second).

**Comment by deepak1556** [comment]
I am able to reproduce with @BenoitZugmeyer test case after a few tries, seems to be a problem with node integration You can also use the new [net](https://github.com/electron/electron/blob/master/docs/api/net.md) module as an alternative.

**Comment by zcbenz** [comment]
I'm merging this to #1833.
