### ISSUE TITLE
app.getVersion returns electron binary version instead of package.json field

### ISSUE THREAD

**Issue by oxcarga** [electron/electron#7085]
* Electron version: 1.3.3
* Operating system: OSX El Capitan (10.11.5)

Just calling app.getVersion() and i'm getting electron's binary version instead of version I set in my package.json (2-package.json structure). 

Of course, my app/package.json has the version field:

```
{
  "name": "Name",
  "version": "0.0.1",
  "productName": "ProdName",
  "description": "Desc Desc",
  "homepage": "https://github.com/oxcarga/ProdName",
  "license": ""
}
```

In Main process:

```
const {app} = require('electron')
app.on('ready', function () {
    console.log(app.getVersion())
})
```

Or, in Renderer process:

```
const {app} = require('electron').remote
console.log(app.getVersion(), app.getName())
```

In both places I get "1.3.3" (which is the version of electron I'm running) 

According to docs:

> app.getVersion()
> Returns the version of the loaded application. If no version is found in the application’s package.json file, the version of the current bundle or executable is returned.

Am I missing something?

**Comment by Kaibu** [comment]
app.app.getVersion(); works for me, might be an error in the docs, or a problem with using the 2-package.json structure

**Comment by enlight** [comment]
In development the version returned by `app.getVersion()` depends on how you launched your app. If you launched it with `electron path/to/app/package_dir` the version will match the one in your `package.json`, however, if you launched your app with `electron path/to/main.js` then you'll get the Electron version. This is because in the latter case Electron will actually read the `package.json` of the default app, which doesn't specify a version, so it will default to the Electron version. Once you package your app the version will always be read from your `package.json`.

**Comment by oxcarga** [comment]
Thanks guys. Nice to know that.

Actually these 3 ways return different values.

Will leave it here for the record.

Inside project folder (3 ):
 

1. 

`./node_modules/.bin/electron .`

2.

`./node_modules/.bin/electron ./app/`

3.

**Comment by geek4teck** [comment]
I had the same issue if i was using 

`electron index.js`

This was probably bypassing package.json and thus was showing the electron version

I then changed start script in package.json to 

`electron .`

and now it shows version from package.json

**Comment by denigada** [comment]
How can I use app.getVersion from another javascript file other than main.js ?

How am I supposed to get the "app" object from main.js ?

**Comment by Kaibu** [comment]
Just require app via remote 

`const {app} = require('electron').remote`

**Comment by Skriptach** [comment]
I have same issue when run electron with `yarn`

**Comment by kaitlynbrown** [comment]
Also seeing this happen. Is there a reason the issue was closed? It doesn't seem to be resolved at all.
I'm using electron-webpack, so the workarounds in this thread don't work for me

**Comment by twigs67** [comment]
@kaitlynbrown did you ever figure this out? I'm on the same boat.

**Comment by yanlee26** [comment]
> In development the version returned by `app.getVersion()` depends on how you launched your app. If you launched it with `electron path/to/app/package_dir` the version will match the one in your `package.json`, however, if you launched your app with `electron path/to/main.js` then you'll get the Electron version. This is because in the latter case Electron will actually read the `package.json` of the default app, which doesn't specify a version, so it will default to the Electron version. Once you package your app the version will always be read from your `package.json`.

While, how to fix it , not only walkaround it?

**Comment by robsonhermes** [comment]
I am using Electron + Typescript, so the start script in my package.json is:

`"start": "npm run build && electron ./dist/main.js"`

When doing app.getVersion with Electron 9, I get electron's version.

When using Electron 8.3.0, I get my package.json' version, which is what I expect.

**Comment by LoopsGod** [comment]
This is normal behaviour, you can check whether your in dev mode or in production, and, if you are, you can read from your native package.json file.

```javascript
    let { currentVersion } = '';

    if (process.env.NODE_ENV === 'development') {
      currentVersion = require('../../../package.json').version;
    } else {
      currentVersion = require('electron').remote.app.getVersion();
    }
```

**Comment by farin** [comment]
you can also use
`process.env.npm_package_version`

**Comment by petertorelli** [comment]
Side note: if you use `process.env.npm_package_version`, it will place a hyphen between x.y.z and anything that follows, for example: Version `1.0.0RC1` in `package.json` becomes `1.0.0-RC1`.

**Comment by writingdeveloper** [comment]
> you can also use
> `process.env.npm_package_version`

It works for me! Thanks!

**Comment by pavan-singh-iphtech** [comment]
> > In development the version returned by `app.getVersion()` depends on how you launched your app. If you launched it with `electron path/to/app/package_dir` the version will match the one in your `package.json`, however, if you launched your app with `electron path/to/main.js` then you'll get the Electron version. This is because in the latter case Electron will actually read the `package.json` of the default app, which doesn't specify a version, so it will default to the Electron version. Once you package your app the version will always be read from your `package.json`.
> 
> While, how to fix it , not only walkaround it?

just electron .  where you entry point of electron app
