### ISSUE TITLE
Right click on flash player shows TypeError: Menu.buildFromTemplate is not a function

### ISSUE THREAD

**Issue by tdtsh** [electron/electron#7086]
* Electron version: v1.3.5
* Operating system: Mac OSX: 10.11.6
* PepperFlashPlayer Version: 22.0.0.209

- problem

1. open page with flash video in webview.

	ex: http://www.adobe.com/jp/devnet/actionscript/samples/component_1.html

2. right click on the flash video

3. error dialog opened.

> A JavaScript error occurred in the main process
> 
> Uncaught Exception:
> TypeError: Menu.buildFromTemplate is not a function
>     at WebContents.<anonymous> (/Users/me/.node-gyp/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:223:23)
>     at emitTwo (events.js:106:13)
>     at WebContents.emit (events.js:191:7)

- expected 

to open flash context menu.

- Source code for  reproduction.

**Please put flash plugin to project root directory before.**

**index.js**
```
'use strict';

const {app, BrowserWindow} = require('electron');
let win;

app.on('window-all-closed', function() {
  app.quit();
});

app.on('ready', function() {
  win = new BrowserWindow({
    width: 800,
    height: 600
  });
  win.loadURL('file://' + __dirname + '/index.html');
  win.on('closed', function() {
    win = null;
  });
});

// Path to flash
let pluginName;
switch (process.platform) {
  case 'win32':
    pluginName = 'pepflashplayer.dll';
    break;
  case 'darwin':
    pluginName = 'PepperFlashPlayer.plugin';
    break;
  case 'linux':
    pluginName = 'libpepflashplayer.so';
    break;
  default:
    break;
};

const path = require('path');
app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, pluginName));
```

**index.html**
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title></title>
  </head>
  <body>
<style>
html{
 width:100%;
 height:100%;
}
body{
 margin:0;padding:0;
 height:100%;
}

</style>
    <script>
    </script>
    <webview id="main" src="http://www.adobe.com/jp/devnet/actionscript/samples/component_1.html" autosize="on" style="display:inline-flex; width:100%; height:100%" plugins></webview>
  </body>
</html>
```

**Comment by bbondy** [comment]
@alexwykoff could you triage?
