### ISSUE TITLE
Question: node-pre-gyp & NODE_MODULE_VERSION

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#7087]
* Electron version: 1.3.4
* Operating system: darwin

Hi, I'm desperately looking for some help or direction with pre-compiling some binaries. I checked that electron was using node 6.3.0 and thought that by compiling with node-pre-gyp for that version of node I would be able to include the library in electron.

When testing with vanilla node 6.3.0 I can require the script no problem, but when I try to require the script in electron I get `Error: Module version mismatch. Expected 49, got 48`. Looking around the node [previous releases](https://nodejs.org/en/download/releases/) I can see that these only go as far as 48 so I'm a little bit stuck.

* Repo: [Thomas101/nodehun](https://github.com/Thomas101/nodehun)
* Bundle: `npm install --build-from-source; ./node_modules/.bin/node-pre-gyp package`

Any help or direction would be greatly appreciated!

**Comment by MarshallOfSound** [comment]
You need to follow the building native modules for Electron instructions.

Basically you need to rebuild with Electron's header files not Node's.

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by Thomas101** [comment]
YES! Thank you so much :-)
