### ISSUE TITLE
Virus (Trojan:Win32/Nagram!rfn) detected in libEGL.dll for Windows 32 bit system

### ISSUE THREAD

**Issue by webarchymeta** [electron/electron#7091]
* Electron version: 1.3.3 and up
* Operating system: Windows 10

Our build system (Wix based) was interrupted today when build an application for Windows 32 bit system. It reported finding of a trojan virus (Trojan:Win32/Nagram!rfn) in libEGL.dll. 

It was initially found in electron 1.3.3 and then 1.3.5 was also found to have the same virus. So maybe earlier version of electron (for Windows 32 bit) also has the same problem.

Does anyone here also find such a problem?

**Comment by MarshallOfSound** [comment]
@webarchymeta From an initial investigation on my part I'm tempted to believe your system has been infected and the actual Electron files are fine.

I downloaded a fresh version of Electron from the releases section and ran the referenced file (libEGL.dll) through http://virustotal.com and it came back with 0 detections.  As you can see here:

**Comment by webarchymeta** [comment]
The program that reports the virus is light.exe which is part of Microsoft WiX (installer building system). Since the only virus scanning system here is MS Security Essentials, the source of the report should come from the later. I tried to check my version of libEGL.dll on virusportal.com, the site didn't upload the file before reporting it had already been checked (I will belief they did checked the signature of the file before making such an report). So, it is quite strange ...

I will reboot the my system to see what happens

**Comment by webarchymeta** [comment]
OK, I found a possible cause of the problem. I digitally signed (using Windows' own digital signer) the dlls and others using a code signing certificate of ours and that might confused the virus scanner. After I turned off the sign of the dlls, there is no more virus found error ...

But it's still strange
