### ISSUE TITLE
history navigations in sub-frame should be tracked by navigationController

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#7092]
- Electron version: 1.3.5
- Operating system: OSX

[I have created a reproducible repo here.](https://github.com/brian-mann/electron-iframe-history-go-bug)

There is a bug with `window.location.replace` not acting the same way real Chromium does.

In real Chromium, if you were to clone my repo and host it on a server you would see the following get logged to your console:

![screen shot 2016-09-04 at 10 38 03 pm](https://cloud.githubusercontent.com/assets/1268976/18236042/4331d09c-72f0-11e6-92b1-c66fcdfa0910.png)

What's happening here is that we initially replace `index.html` with `index2.html` using `window.location.replace`. This is where the problem is. If we switch this to `window.location.assign` or `window.location.href = ...` everything works.

After `index2.html` contents get loaded, it then inserts `iframe1` and then changes its `src` to `iframe2` and then calls `window.history.back()` which should result in `iframe1` being loaded again.

In real Chromium, this works fine.

However in Electron the final `window.history.back()` call will result in a noop, which means `iframe2` will never navigate **back** to `iframe1`. The screenshot looks like this:

![screen shot 2016-09-04 at 10 41 55 pm](https://cloud.githubusercontent.com/assets/1268976/18236105/e0f55740-72f0-11e6-8274-e492173b656c.png)

This is due to an incorrect `window.location.replace` implementation, which results in `window.history.length` having an incorrect count.

However what is strange about this bug is that it only happens **on the very first load**. If you have your Electron dev tools open, and refresh the page **it will work**. You must be sure to kill Electron between code changes else this problem will not be exhibited.
### Why does this really matter

This is a pretty serious bug for https://cypress.io users as trying to programmatically navigate the browser `forward` or `back` using `cy.go` is basically broken when running headlessly.

It will work in your regular Chrome browser though, so currently we just tell users to skip these kinds of tests when running headlessly through Electron =(

**Comment by deepak1556** [comment]
Related to https://github.com/electron/electron/issues/2644, but a separate issue to track is better since it involves refining `webContents.navigationController`

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
