### ISSUE TITLE
spectron downloading failed 【getaddrinfo ENOTFOUND】

### ISSUE THREAD

**Issue by illfar** [electron/electron#7093]
* Electron version:0.37.8
* Operating system:win7 32bit

spectron downloading failed 【getaddrinfo ENOTFOUND】
I have set the proxy in my PC as following。
proxy=http://username:password@proxy-url:8080/
https-proxy=http://username:password@proxy-url:8080/

---------------------------------------------------------------------------------------------
C:\tool\spectron-master\spectron-master>npm install

> electron-chromedriver@1.3.1 install C:\tool\spectron-master\spectron-master\no
de_modules\electron-chromedriver
> node ./download-chromedriver.js

**Downloading https://github.com/electron/electron/releases/download/v1.3.0/chrome
driver-v2.21-win32-ia32.zip failed: getaddrinfo ENOTFOUND github.com github.com:
443**
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! electron-chromedriver@1.3.1 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-chromedriver@1.3.1 install script 'node ./downlo
ad-chromedriver.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-chromedriver
 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./download-chromedriver.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\tool\spectron-master\spectron-master\npm-debug.log

**Comment by kevinsawicki** [comment]
Moved over to https://github.com/electron/chromedriver/issues/8
