### ISSUE TITLE
app.getAppPath() problem

### ISSUE THREAD

**Issue by keyiis** [electron/electron#7094]
* Electron version:1.2.6
* Operating system:win10 64
When i use  app.getAppPath() get app root dir,ex:
```
d:\work\nodejs\electron\angular2
```
next i use path.normalize()
```
let appbase = remote.app.getAppPath();
let newpath = path.normalize(appbase);
console.log(newpath);
```
will get
```
d:work
odejsangular2
```
It's obvious, "\n" to be line break.
Why app.getAppPath() can't get `d:\\work\\nodejs\\angular2` or `d:/work/nodejs/angular2`

**Comment by kevinsawicki** [comment]
I'm having trouble reproducing this on Windows 10, can you try running the following from the Console tab of the dev tools:

```js
require('path').normalize(require('electron').remote.app.getAppPath())
```

Even with a folder starting with an `n`, I still see the correct value:

<img width="372" alt="screen shot 2016-09-06 at 10 20 39 am" src="https://cloud.githubusercontent.com/assets/671378/18283756/a168cbc6-741b-11e6-8bbe-79e8cf9d0f58.png">

**Comment by keyiis** [comment]
@kevinsawicki thks reply,i used "global" to pass AppPath.

**Comment by charlesr1971** [comment]
@keyiis On a different note, where has **electron** gone in your path normalisation process?
