### ISSUE TITLE
Tray icon disappear after 1 minute

### ISSUE THREAD

**Issue by stanleyxu2005** [electron/electron#7095]
* Electron version: 1.3.5
* Operating system: Windows 7 (x64)

I created a minimal application with one browser window and a tray icon. The tray icon will disappear after roughly 1 minute. I don't have any code to hide tray icon, but it is just gone.

**Comment by enlight** [comment]
Did you read the [FAQ](http://electron.atom.io/docs/faq/#my-apps-windowtray-disappeared-after-a-few-minutes)?

**Comment by stanleyxu2005** [comment]
Aha, I just wanna to update my found -> memory management. Oh, yes. I should have read the FAQ first. Thanks. 

I think the dev team should consider change the `app` object. I think to have a `app.setTrayIcon` will make much sense rather than declaring an orphan `tray` variable, which might be recycled by the JS VM. The similar improvement is to have `app.setMainWindow`.
