### ISSUE TITLE
Listening for pressed ALT key while displaying menu

### ISSUE THREAD

**Issue by jankuca** [electron/electron#7098]
Is there a way to observe alt key press state change while displaying application menus?

I would like to update the menu items (which I am not sure is possible either) while the menu is displayed and the user is toggling the alt key.

This behavior can be seen in the OS X Finder app for instance.

**Comment by xywz** [comment]
Duplicate of #5992.

**Comment by kevinsawicki** [comment]
Closing and merging into #5992
