### ISSUE TITLE
autoUpdater setFeedUrl is undefined

### ISSUE THREAD

**Issue by alexerleo** [electron/electron#7102]
* Electron version: 1.3.5
* Operating system: windows 7

I got autoupdater broken after update from v0.38
autoUpdater.setFeedUrl is undefined (on both main and renderer process)

![error 2016-09-05 18 37 03](https://cloud.githubusercontent.com/assets/16289980/18252775/f07bcaa2-7398-11e6-9317-889c782af850.png)

there is a sample code how I use it:

var electron = require('electron');

electron.autoUpdater.setFeedUrl(serverUrl);
electron.autoUpdater.on('update-downloaded', function() {
        electron.autoUpdater.quitAndInstall();
   });
electron.autoUpdater.checkForUpdates();

**Comment by MarshallOfSound** [comment]
JS API's are case sensitive.

https://github.com/electron/electron/blob/master/docs/api/auto-updater.md#autoupdatersetfeedurlurl-requestheaders

It is `setFeedURL` <-- Notice the capitol "URL"
