### ISSUE TITLE
App-region: drag on Windows 10, blocking events

### ISSUE THREAD

**Issue by andreyavram** [electron/electron#7107]
* Electron version: 1.3.5
* Operating system: Windows 10 (on Macbook Pro)

Hi,

I noticed that on windows 10, if an element has the 
 -webkit-app-region: drag; 
no other event gets received by that element, including  click or hover. Works fine on OS X.

**Comment by MarshallOfSound** [comment]
This is an OS limitation.

See this comment for more information https://github.com/electron/electron/issues/1354#issuecomment-90315551

>The -webkit-app-region: drag is a hint to operating system that the area is a draggable area like window's titlebar, and the operating system will hijack all mouse events of the area to make it behave like titlebar.

> There is no way to work around it in both web apps and native apps, if you want to catch all events you have to move the window manually by recording how user drags and moves the mouse.

**Comment by andreyavram** [comment]
Thanks for answering, I already tried that, but when moving the app from one monitor to another, I need to also factor the different scaling of each monitor, which is wrongly returned on windows 10 #7108 .  I noticed your app, How do you handle this scenario?

**Comment by MarshallOfSound** [comment]
> I need to also factor the different scaling of each monitor, which is wrongly returned on windows 10

I can't comment on the scaling issue without some research on my end, but from memory an issue to do with this has popped up already.

Why do you need the scaling factor for the monitors to do window repsotioning?

**Comment by andreyavram** [comment]
Well, I used the win-mouse module to get the mouse position, on click down, and move the window accordingly, but when moving from one monitor to another, if the scaling was different between monitors, the window didn't follow the mouse on the second screen, unless I factored the values X,Y returned by win-mouse with scaling. Works fine if I input it manually to 1.5(when the scaling is 150% in Windows), but that's not a solution. 
However, there is no problem for scaling 125%, so I suppose that the fix mentioned in the other thread should also fix this. Hope it makes it to 1.3.6.

**Comment by MarshallOfSound** [comment]
@andrewda You don't need a native module to get the mouse position.  If you think about it, when dragging your mouse will always be over the window.  You can implement code similar to this


```js
import { remote } from 'electron';

let wX;
let wY;
let dragging = false;

$('.draggable').mousedown(function (e) {
    dragging = true;
    wX = e.pageX;
    wY = e.pageY;
});

$(window).mousemove(function (e) {
    e.stopPropagation();
    e.preventDefault();
    if (dragging) {
        var xLoc = e.screenX - wX;
        var yLoc = e.screenY - wY;

        try {
            remote.BrowserWindow.getFocusedWindow().setPosition(xLoc, yLoc);
        } catch (err) {
            console.log(err);
        }
    }
});

$(window).mouseup(function () {
    dragging = false;
});
```

Excuse the jQuery 😆 

But yeah, I've tested that on really slow machines moving the mouse stupidly fast and it has never failed me yet 👍

**Comment by andreyavram** [comment]
@MarshallOfSound 
That works very well.
Thanks a lot, mate!
Have a nice day!

**Comment by fredski02** [comment]
> @andrewda You don't need a native module to get the mouse position. If you think about it, when dragging your mouse will always be over the window. You can implement code similar to this
> 
> ```js
> import { remote } from 'electron';
> 
> let wX;
> let wY;
> let dragging = false;
> 
> $('.draggable').mousedown(function (e) {
>     dragging = true;
>     wX = e.pageX;
>     wY = e.pageY;
> });
> 
> $(window).mousemove(function (e) {
>     e.stopPropagation();
>     e.preventDefault();
>     if (dragging) {
>         var xLoc = e.screenX - wX;
>         var yLoc = e.screenY - wY;
> 
>         try {
>             remote.BrowserWindow.getFocusedWindow().setPosition(xLoc, yLoc);
>         } catch (err) {
>             console.log(err);
>         }
>     }
> });
> 
> $(window).mouseup(function () {
>     dragging = false;
> });
> ```
> 
> Excuse the jQuery 😆
> 
> But yeah, I've tested that on really slow machines moving the mouse stupidly fast and it has never failed me yet 👍

If anyone is using electron-drag npm module out there. This guy is your saviour

**Comment by prevzzy** [comment]
> @andrewda You don't need a native module to get the mouse position. If you think about it, when dragging your mouse will always be over the window. You can implement code similar to this
> 
> ```js
> import { remote } from 'electron';
> 
> let wX;
> let wY;
> let dragging = false;
> 
> $('.draggable').mousedown(function (e) {
>     dragging = true;
>     wX = e.pageX;
>     wY = e.pageY;
> });
> 
> $(window).mousemove(function (e) {
>     e.stopPropagation();
>     e.preventDefault();
>     if (dragging) {
>         var xLoc = e.screenX - wX;
>         var yLoc = e.screenY - wY;
> 
>         try {
>             remote.BrowserWindow.getFocusedWindow().setPosition(xLoc, yLoc);
>         } catch (err) {
>             console.log(err);
>         }
>     }
> });
> 
> $(window).mouseup(function () {
>     dragging = false;
> });
> ```
> 
> Excuse the jQuery 😆
> 
> But yeah, I've tested that on really slow machines moving the mouse stupidly fast and it has never failed me yet 👍

I'm using a very small browser window for my app and this approach was losing focus on dragging element very often. Basically the cursor was going out of the window bounds before position update was applied. What helped me and works like a charm is Pointer Lock API (https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API)

Here's my code:
```
let dragging = false;

  draggingElement.addEventListener('mousedown', (e) => {
    if (e.button === 0) { // Only start drag on left click
      dragging = true;
      draggingElement.requestPointerLock({ unadjustedMovement: true });
    }
  })

  draggingElement.addEventListener('mousemove', (e) => {
    if (!dragging) {
      return
    }

    e.stopPropagation();
    e.preventDefault();
    
    const win = BrowserWindow.getFocusedWindow();
    if (win && document.pointerLockElement === draggingElement) {
      const newWinX = win.getBounds().x + e.movementX;
      const newWinY = win.getBounds().y + e.movementY;
      win.setPosition(newWinX, newWinY);
    }
  });

  draggingElement.addEventListener('mouseup', (e) => {
    dragging = false;
    document.exitPointerLock();
  });
```
