### ISSUE TITLE
Scaling factor, same for all displays

### ISSUE THREAD

**Issue by andreyavram** [electron/electron#7108]
* Electron version: 1.3.5
* Operating system: Windows 10 

On Win 10, the scaling factor returned by a Display object is the same for all attached monitors. 
Also the changed-metrics event lacks the property scale, as described by the documentation.

**Comment by MarshallOfSound** [comment]
@andreyavram Can you confirm that this is either the same issue or a different issue to #6571

**Comment by andreyavram** [comment]
Yes, I strongly believe it's related. This could be closed.
