### ISSUE TITLE
Windows: "node-gyp is not recognized as an internal or external command" on `apm install .`

### ISSUE THREAD

**Issue by natevw** [electron/electron#711]
I'm trying to get a Windows build of my app going, but keep running into trouble. I was able to `apm install .` but when running the app I hit an error something like "%1 is not a valid Windows executable" when requiring a native module. Assuming it was a x64 vs x86 issue, I uninstalled 64-bit node and installed 32-bit node. Didn't change much — `apm install` still "succeeded" but same not executable error.

The package for the native module had some shenanigans to manually fetch a remote dependency _and_ to manually kick off a `node-gyp` call, so I thought maybe the latter was . So I forked the package and way simplified it to just be a AFAICT "normal" bindings.gyp deal. See: https://github.com/natevw/node-hid/blob/1ff4f7e191266d56546d76e6f94a9b11437bd334/package.json

When I `npm install` my app that includes a direct link to an `npm pack` of the forked native module, it works, the dependency compiles, it works when I `node -e "require('node-hid')`, etc. etc.

But when I `apm install .`, I get this error:

> node-gyp not recognized as an internal or external command

Are there some instructions missing from https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md for building native modules on Windows? I've seen some references to a bootstrap script and such but that seems to be for building the main Atom.exe editor from source. And normal `npm install` works, no node-gyp trouble there.

**Comment by cldwalker** [comment]
Fwiw, I encountered node-gyp not being recognized for cygwin while running script/bootstrap.py. `npm install -g node-gyp` resolved it for me.

**Comment by chancet1982** [comment]
seems it happens when node-gyp is not installed on system.
Following this guide helped me (different actions based on OS)
https://github.com/nodejs/node-gyp

**Comment by shanept** [comment]
Bumping an old issue, I know...
But I had this same issue and the solution by @cldwalker fixed this.
Maybe it's worth including in the windows building docs?
