### ISSUE TITLE
Is it possible to place hyperlink in the dialog.showMessageBox message string?

### ISSUE THREAD

**Issue by nishant09** [electron/electron#7111]
* Electron version: 0.34
* Operating system: All

Hi ,

I want to place the [**html link**](url) which will direct the user to the html page when click in my message box dialog's "message" string. Is this possible ?

dialog.showMessageBox(
            focusedWindow,
            {
                type: "error",
                message: message,
                title: title,
                cancelId: cancelId,
                buttons: buttons
            },
            resolve
);

**Comment by nishant09** [comment]
I tried below javascript but the dialog seems to be not interpreting the html tag. Hence just write it down as it is.
var productURL = `<a href='http://storageexplorer.com/'>StorageExplorer</a>`;
var message = "This query was created by a newer version of Storage Explorer. Please update to newer version at:" + productURL;

Output should be:  This query was created by a newer version of Storage Explorer. Please update to newer version at: [StorageExplorer](url)

**Comment by felixrieseberg** [comment]
Sorry to say that this is not supported. I'd recommend building your own dialog - or adding the feature to the current dialog implementation in Electron, a PR is always welcome!

**Comment by Haroenv** [comment]
I was looking here to see if it was possible. The relevant files would be: 

* https://github.com/electron/electron/blob/master/atom/browser/ui/message_box.h
* https://github.com/electron/electron/blob/master/atom/browser/ui/message_box_win.cc
* https://github.com/electron/electron/blob/master/atom/browser/ui/message_box_mac.mm
* https://github.com/electron/electron/blob/master/atom/browser/ui/message_box_gtk.cc

Where you'd need to figure out how to display links in each of the methods
