### ISSUE TITLE
Right clicking text selects word under cursor, but text highlight is not rendered until context menu is dismissed

### ISSUE THREAD

**Issue by fantasticsid** [electron/electron#7112]
* Electron version: 1.3.3
* Operating system: Mac

In a text input element, if I pop up a menu in the 'context-menu' event handler, the text under cursor is selected (as can be inspected and seen from the context-menu event argument) but the highlighting of the text is not rendered until the menu is dismissed.

Try this with the Electron API demos app: click on a word in the source text:

<img width="630" alt="screen shot 2016-09-06 at 11 50 28 am" src="https://cloud.githubusercontent.com/assets/203771/18286562/3977a188-7428-11e6-9f4d-24545c8f327d.png">

After menu is dismissed, the text is highlighted:

<img width="628" alt="screen shot 2016-09-06 at 11 50 36 am" src="https://cloud.githubusercontent.com/assets/203771/18286570/48639152-7428-11e6-8b11-1d01b50d4d2a.png">

This does not happen for Chrome.

I could delay the menu pop up with setTimeout, but a simple timeout value of 0 does not work. It seems we need to give some time for the native UI to render the highlighting. However, a large timeout (100ms e.g.) does not work well either because there's noticeable UI discrepancy.

I'd like to know if this has something to do with how node integration is implemented, and possible workarounds..

Thanks!

**Comment by kevinsawicki** [comment]
> I'd like to know if this has something to do with how node integration is implemented, and possible workarounds..

I don't think there is a workaround for this currently besides the `setTimeout` one you mentioned.

**Comment by zcbenz** [comment]
This would be solved when we have #1854, and I'm merging this issue to it.

This has also been a bug of Atom for a long time, more context can be found at https://github.com/atom/atom/issues/2991.
