### ISSUE TITLE
BrowserWindow with black corner on Windows 7 (non Aero)

### ISSUE THREAD

**Issue by cprogrammer1994** [electron/electron#7117]
- Electron version: 1.3.5
- Operating system: Windows 7 SP1 x64 Ultimate

I just created a `BrowserWindow` having black corner where it should be completely transparent.

**Settings:**
- first try: `{width: 800, height: 600}`
- second try: `{width: 800, height: 600, transparent: true}`
- third try: `{width: 800, height: 600, titleBarStyle: "default"}`

![black-corner](http://i.stack.imgur.com/6fJon.png)

Maybe related #1270

**Comment by zcbenz** [comment]
How does the window look before you call `loadURL`? And does the black corner still exist if you add `frame: false` to settings?

**Comment by cprogrammer1994** [comment]
- added `frame: false`
- with and without `loadURL` the corners are rounded

![img](https://s12.postimg.org/i9cx4trkd/fame_false_without_load_URL.png)

**Note:** Aero is disabled.

**Comment by zcbenz** [comment]
I do see some issues on rendering problems when Aero is turned off (#1821), but this one is new to me. I have no idea why this happened and I'm not sure it is even related to Electron, since the non-client area is drawn by Windows itself.

**Comment by madipor** [comment]
Hi @cprogrammer1994  
Do you found solution?

**Comment by cprogrammer1994** [comment]
**No**, but I got upgraded to Win10, cannot test anymore. 😞

**Comment by zcbenz** [comment]
I'm closing this since there is very few reports of it, and it is impossible to look into it for us.
