### ISSUE TITLE
Use node modules when set nodeIntegration is false

### ISSUE THREAD

**Issue by thiendaiac** [electron/electron#7122]
Hi guys,
How can I use node modules ( ex: fs, electron-storage ) in js files when I set nodeIntegration is false?
Thanks

**Comment by MarshallOfSound** [comment]
You can't

That is the entire point of `nodeIntegration` being `false`.  It completely disables access to the node environment

**Comment by thiendaiac** [comment]
@MarshallOfSound, thanks for your reply. I researched and finally I found solution for that issue, see that:
https://discuss.atom.io/t/with-node-integration-false-how-can-i-use-dialog-in-the-main-process/22570/7
