### ISSUE TITLE
openExternal link in electron

### ISSUE THREAD

**Issue by nuruddeensalihu** [electron/electron#7124]
* Electron version:1.3.5
* Operating system:mac osx

Please i have my hybrid app that uses an external oAuth for authentication. On the mobile , i use cordova InAppBrowser to open the auth page, listen to event and close the auth page on successful authentication like below.

```

if (window.cordova) {
        const winAuth = window.cordova.InAppBrowser.open(oAuthUrl, '_blank', 'location=no');
        winAuth.addEventListener('loadstart', e => {
            if (e.url.indexOf(delimeter') > -1) {
                const accounts = window.boot.parseUrl(e.url);
              //..dispatch actions
                //authenticateAgain(accounts[0].token);
                winAuth.close();
            }
      
```

As soon as the authentication is successful, the tokens are return from the oAuth url, i then grab the tokens and close the oAuth window. 

I am now trying to achieve the same on electron. My system should run local and the Auth from oAuth. I came across this [Here](https://github.com/electron/electron/blob/master/docs/api/shell.md). I thought i can use it but i am not sure if i can listen to the load or any event on this property. Please is there any way i can attach an event of the shell the same way i did with the cordova plugin above ? Moreover, when i try this in my main code and packed using webpack
```

const {shell} = require('electron')

shell.openExternal('https://github.com');
```

My code breaks and throw error from the ./node_modules/electron/index.js

> Uncaught TypeError: r.readFileAsync is not a function. 

Sorry for this long question. Your help would really be appreciated. thank you once again.

**Comment by MarshallOfSound** [comment]
> I am now trying to achieve the same on electron. My system should run local and the Auth from oAuth. I came across this Here. I thought i can use it but i am not sure if i can listen to the load or any event on this property. Please is there any way i can attach an event of the shell the same way i did with the cordova plugin above ? 

Most people do oAuth inside Electron by opening a new `BrowserWindow` with the oAuth URL.  This gives you event access like you have in your cordova example.

> My code breaks and throw error from the ./node_modules/electron/index.js

To use `electron` with WebPack you have to define certain things as globals, I'm not familiar with the WebPack build system but a quick issue / google search should reveal the config you need.

In the future please ask questions like this on the discussion forums or Slack.  The github issues section is primarily for bugs 👍
