### ISSUE TITLE
Web UI Bug - Cannot right click in WebUI

### ISSUE THREAD

**Issue by lifeiscontent** [electron/electron#7127]
* Electron version: electron-prebuilt: 1.2.8
* Operating system: OSX 10.11.6

I'm just going to assume this issue is something in Atom. https://github.com/vincelwt/harmony/issues/17

**Comment by kevinsawicki** [comment]
Does your app include a context menu on right click?

**Comment by lifeiscontent** [comment]
@kevinsawicki seems that was it, thanks! 👍
