### ISSUE TITLE
https://atom.io/download/atom-shell/v1.3.5/iojs-v1.3.5.tar.gz error!

### ISSUE THREAD

**Issue by keyiis** [electron/electron#7134]
How to fix?I can download it manual,but where place it?
```
d:\work\nodejs\angular\angular2-electron\node_modules\sqlite3>node-gyp rebuild --target=1.3.5 --arch=x64 --target_platform=win32 --dist-url=https://atom.io/download/atom-shell --module_name=node_sqlite3 --module_path=../lib/binding/electron-v1.3-win32-x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.11.1 | win32 | x64
gyp http GET https://atom.io/download/atom-shell/v1.3.5/iojs-v1.3.5.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 23.21.87.228:443
gyp ERR! stack     at Object.exports._errnoException (util.js:893:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:916:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
```

**Comment by duncup** [comment]
I see you make a book on github.
Do you ask this for the book?
If this is ture,why use a old version of iojs?
And this error is you'r network error,I can download this file.maybe you need a vpn to download this file.

**Comment by kevinsawicki** [comment]
> Error: connect ETIMEDOUT 23.21.87.228:443

Yeah, this timeout is the issue, are you able to hit `https://atom.io/download/atom-shell/v1.3.5/iojs-v1.3.5.tar.gz` in a browser?

You may need to configure your network settings via the [`.npmrc`](https://docs.npmjs.com/files/npmrc)` file.

Closing this out.
