### ISSUE TITLE
 How to hide the titleBar of Windows

### ISSUE THREAD

**Issue by yihuds** [electron/electron#7136]
* Electron version: v1.2.3
* Operating system: Windows

**Comment by MarshallOfSound** [comment]
Check out the [Frameless Window API](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md)

In the future please ask questions on the discussion forums or on Slack.  The GitHub issues section is meant for bugs only

**Comment by yihuds** [comment]
OK
