### ISSUE TITLE
A javascript error occurred in the main process

### ISSUE THREAD

**Issue by hasan3ysf** [electron/electron#7138]
* Electron version: 1.0
* Operating system: Windows 10, Development: Win10-x64, Testing: Win10-ia32

Hi,
I developed and tested my app at my machine, everything fine fine, I tested it in another machine, that not having anything related to nodej installed, and got this error one clicking the app.exe file, later on the error disappear and the app run smooth.
This is happening every time I run the app

![image](https://cloud.githubusercontent.com/assets/840673/18348762/f82bd29e-75d5-11e6-8467-2a9b2aae08c2.png)

**Comment by kevinsawicki** [comment]
This looks to be related to the `server.js` file in your app, not something in Electron core.

It looks like an error is thrown when listening on a specific ip/port.

You might want to post to the discussion forum for help debugging this server issue, https://discuss.atom.io/c/electron
