### ISSUE TITLE
Atom Electron Run app in background

### ISSUE THREAD

**Issue by NistorCristian** [electron/electron#7139]
* Electron version: 1.3.5
* Operating system: Windows 10

Hi,

I would like to know if there is a way to make an application with Atom Electron that runs and gets my keyboard events when the user is/isn't focused on my app.

For example if he is on Chrome and writes something, my app will store all the keys that he pressed. I searched a little but didn't find something that solves my problem.

Thank you.

**Comment by lee-dohm** [comment]
What you're describing is the functionality of a [keylogger](https://en.wikipedia.org/wiki/Keystroke_logging). While there are valid uses for such techniques, the far more common uses are nefarious (collecting passwords, stealing access to private information, etc). We don't want Electron used to violate others' privacy or worse, so we have to err on the side of caution and deny your request for assistance.

Thanks for your understanding!
