### ISSUE TITLE
Enabling the element inspector with a keyboard shortcut

### ISSUE THREAD

**Issue by zeke** [electron/electron#7147]
In MacOS Chrome, hitting <kbd>Cmd</kbd><kbd>Shift</kbd><kbd>C</kbd> or <kbd>Cmd</kbd><kbd>Alt</kbd><kbd>c</kbd> enables [inspect element mode](https://developers.google.com/web/tools/chrome-devtools/iterate/inspect-styles/shortcuts?hl=en#accessing-devtools
):

![screen shot 2016-09-08 at 10 22 28 pm](https://cloud.githubusercontent.com/assets/2289/18376321/04fb1146-7613-11e6-89e6-8df1c6e64037.png)

This doesn't seem to work in Electron, though. You have to open devtools and click the little cursor icon.

I thought this might be implemented in [electron-debug](https://github.com/sindresorhus/electron-debug#readme) but alas, no.

cc @sindresorhus 

* Electron version: 1.3.5
* Operating system: MacOS

**Comment by deepak1556** [comment]
I am not sure this has to be a default implementation in Electron, maybe the default app can provide it but would be much better in `electron-debug`, can be achieved with

```
mainWindow.webContents.on('devtools-opened', function () {
    mainWindow.devToolsWebContents.executeJavaScript('DevToolsAPI.enterInspectElementMode()')
 })
```

**Comment by zcbenz** [comment]
Do we want to add this to default app? Or does this issue belong to `electron-debug`?

**Comment by kevinsawicki** [comment]
> Do we want to add this to default app? Or does this issue belong to electron-debug?

I'd lean towards electron-debug and not the default app.
