### ISSUE TITLE
Electron API's involving `process.execPath` should use the Squirrel trampoline if it is available

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#7148]
- Electron version: All
- Operating system: Windows

This was mentioned in passing when I was talking to @paulcbetts .  Basically on Windows I think it's safe to say the majority of apps use Squirre as their install and update mechanism.

However lots of Electron API's such as the [`shortcut`](http://electron.atom.io/docs/api/shell/#shellwriteshortcutlinkshortcutpath-operation-options-windows) API assign the shortcut by default to be `process.execPath`.  Because of the way Squirrel.Windows performs an update (the new version is effectively in a different folder), it means that when the user updates, the shortcut will still be pointing to the old version of the executable so to them "the update didn't work".

The following methods face this issue:
- [`shell.writeShortcutLink`](http://electron.atom.io/docs/api/shell/#shellwriteshortcutlinkshortcutpath-operation-options-windows)
- [`app.setAsDefaultProtocolClient`](http://electron.atom.io/docs/api/app/#appsetasdefaultprotocolclientprotocol-path-args-macos-windows)
- [`app.removeAsDefaultProtocolClient`](http://electron.atom.io/docs/api/app/#appremoveasdefaultprotocolclientprotocol-path-args-macos-windows)
- [`app.isDefaultProtocolClient`](http://electron.atom.io/docs/api/app/#appisdefaultprotocolclientprotocol-path-args-macos-windows)
- [`app.setUserTasks`](http://electron.atom.io/docs/api/app/#appsetusertaskstasks-windows)
- [`app.setJumpList`](http://electron.atom.io/docs/api/app/#appsetjumplistcategories-windows)
- [`app.setLoginItemSettings`](http://electron.atom.io/docs/api/app/#appsetloginitemsettingssettings-macos-windows)
- [`app.relaunch`](http://electron.atom.io/docs/api/app/#apprelaunchoptions) <-- Not sure if this one is actually an issue though

I think we should have a JS file that proxies these functions and inserts Squirrel launch syntax if the user doesn't manually specify an executable path and Squirrel exists.

**Comment by zcbenz** [comment]
I think the root problem is we have two `exe` files, and each one should be used under different cases. An alternative way to fix this is to split `electron.exe` into `electron.exe` and `electron.dll`, and use the former as a small wrapper to find and load `electron.dll`, just like what Chrome does.

A discussion on the alternative way can be found at https://github.com/electron/electron/issues/5830#issuecomment-243706205.
