### ISSUE TITLE
Logging in console works only one out of four times.

### ISSUE THREAD

**Issue by Luciferius** [electron/electron#7149]
* Electron version: 1.3.5
* Operating system: Windows 8.1 Pro

I am using the [electron-quick-start][1] app. I have added logging statements in the main.js as follows:

    [...]

    // Keep a global reference of the window object, if you don't, the window will
    // be closed automatically when the JavaScript object is garbage collected.
    let mainWindow

    console.log("Test")

    function createWindow () {
      // Create the browser window.
    [...]

I have now started the app four times in a row without changing anything. The result can be seen in the picture below.

[![electron logging][2]][2]

Only one of the four times did I get the logging message inside my console.

  [1]: https://github.com/electron/electron-quick-start
  [2]: http://i.stack.imgur.com/5oj3f.png

**Comment by zcbenz** [comment]
Can you try starting the app by calling `.\node_modules\electron-prebuilt\dist\electron.exe .`?

**Comment by Luciferius** [comment]
If I do this it works every time. Does the `electron .` command, which is called by the `npm start` command something different?

**Comment by zcbenz** [comment]
When you run `npm start`, the output will be redirected by `npm`. I'm closing this since it is a problem of `npm` printing output from commands.
