### ISSUE TITLE
Windows: where is the app located?

### ISSUE THREAD

**Issue by PierBover** [electron/electron#7156]
After installing the app doesn't appear in the Start menu, nor when searching after pressing the windows key.

How can my users access the app easily?

**Comment by felixrieseberg** [comment]
Well, how did you install? That's probably an issue with your installer :wink:

**Comment by PierBover** [comment]
I built the app with `electron-builder`. I thought that was standard procedure.

Should I report the problem there instead?

**Comment by PierBover** [comment]
You are right @paulcbetts ...

How come this isn't any mention of this in the autoUpdater docs?

I will try to clarify this and send a PR shortly.
