### ISSUE TITLE
Questions about the window in kiosk mode

### ISSUE THREAD

**Issue by guanyong1993** [electron/electron#7168]
* Electron version: 1.3.5
* Operating system: MacOS 10.9+

    I encountered such a problem, on MacOS, there are two windows, a normal window and a kiosk mode window. Electron defined kiosk mode window will hide the taskbar and the tray, when the kiosk mode window is hidden, but the taskbar and the tray is not displayed. I think if the kiosk mode window is not displayed then the taskbar and the tray should is displayed, I do not know if this is intentional or a problem?

**Comment by zcbenz** [comment]
On Mac the kiosk mode is applied to the app, as long as your app is still showing, system would still be in kiosk mode.

It is easy to just quit kiosk mode when window hides, but it is also possible that users may want to keep the app in kiosk mode while there is no window. So I think we have to keep current behavior.

**Comment by guanyong1993** [comment]
Thanks for your answers. If this is so, then I think the kiosk mode in electron.app is more reasonable, rather than BrowserWindow. Of course, this may produce platform differences.
Thank you very much for your answers.
