### ISSUE TITLE
cmd+comma accelerator broken in 1.3.5

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#7170]
* Electron version: 1.3.5
* Operating system: osx

Hi I've noticed the `cmd+,` accelerator has stopped working between 1.3.4 and 1.3.5. You can trick it into working by holding down `cmd` then pressing any key (e.g `P`) and then pressing `,`.

**Comment by kevinsawicki** [comment]
Hmm, having a little trouble reproducing this on master, are you using it as a global shortcut or as a menu item accelerator?

**Comment by Thomas101** [comment]
Using it in the application menu under the Application menu

**Comment by Thomas101** [comment]
The exact accelerator I used is `CmdOrCtrl+,`

**Comment by kevinsawicki** [comment]
@Thomas101 if you run `electron main.js` using the following file, does pressing the cmd+, shortcut on your keyboard log the message `Clicked!`.

### main.js

```js
const {app, BrowserWindow, Menu} = require('electron')

app.once('ready', () => {
  const mainWindow = new BrowserWindow()

  Menu.setApplicationMenu(Menu.buildFromTemplate([
    {
      label: 'Electron',
      submenu: [
        {
          label: 'Prefs',
          accelerator: 'CmdOrCtrl+,',
          click () {
            console.log('Clicked!')
          }
        },
        {
          role: 'quit'
        }
      ]
    }
  ]))
})
```

**Comment by Thomas101** [comment]
Yeah that works for me. The issue is definitely sporadic. I'll close this off for now until I can make a solid use case. Do you think something could affect it like focusing on a webview element or something in a Browser Window capturing the command?
