### ISSUE TITLE
showItemInFolder() does nothing in ElementaryOS

### ISSUE THREAD

**Issue by ergose** [electron/electron#7176]
- Electron version: 1.1.3 - Newest Electron API Demos app.
- Operating system: ElementaryOS (Linux - Ubuntu based distro.)

I just fired up the Electron API Demo and the demo for "Open Path in File Manager" isn't opening a file manager. I pulled up DevTools and os.homedir() is returning the correct path. I tried to fire off shell.showItemInFolder('somepath') in DevTools console and nothing happened there either. All it returns is "undefined". ElementaryOS uses "Files" file manager. The desktop environment is Pantheon.

**Comment by kevinsawicki** [comment]
Is the `xdg-open` command installed/available? That is what `showItemInFolder` uses under the hood.

**Comment by kevinsawicki** [comment]
Closing out until more information is provided.
