### ISSUE TITLE
Dialog shown behind window when using alwaysOnTop

### ISSUE THREAD

**Issue by czl1378** [electron/electron#7177]
* Electron version: 1.3.5
* Operating system: Windows 7

When I set 'mainWindow' alwaysTop, the dialog belong it should be alwaysTop too? 
But this doesn't work...

The code:

    mainWindow = new BrowserWindow({
        alwaysTop: true,
        ...
    })
    dialog.showMessageBox({
        browserWindow: mainWindow,
        title: 'Tips',
        message: 'Reboot System?',
        buttons: ['Yes', 'No']
    }, (index) => {
        ...
    })

**Comment by zcbenz** [comment]
The parent window must be passed as an arguments:

```js
dialog.showMessageBox(mainWindow, {...})
```

**Comment by czl1378** [comment]
Yes, it works. I made a mistake, Sorry.
