### ISSUE TITLE
BSD Install problem

### ISSUE THREAD

**Issue by rosso-** [electron/electron#7179]
* Electron version: 1.3.5
* Operating system: FreeBSD 10.X

So, I got a problem, installing this software. Can you help me? It's like it trying to fetch something absent on your server.

 # npm install electron -g
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@1.3.5 postinstall /usr/local/lib/node_modules/electron
> node install.js

Downloading electron-v1.3.5-freebsd-x64.zip
Error: GET https://github.com/electron/electron/releases/download/v1.3.5/electron-v1.3.5-freebsd-x64.zip returned 404
/usr/local/lib/node_modules/electron/install.js:22
  throw err
  ^

Error: Failed to find Electron v1.3.5 for freebsd-x64 at https://github.com/electron/electron/releases/download/v1.3.5/electron-v1.3.5-freebsd-x64.zip
    at Request.<anonymous> (/usr/local/lib/node_modules/electron/node_modules/electron-download/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestResponse (/usr/local/lib/node_modules/electron/node_modules/electron-download/node_modules/nugget/node_modules/request/request.js:954:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:433:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:322:20)
    at emitOne (events.js:77:13)
npm ERR! FreeBSD 10.2-STABLE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "electron" "-g"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.6
npm ERR! code ELIFECYCLE

npm ERR! electron@1.3.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.3.5 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/ports/npm-debug.log

**Comment by enlight** [comment]
FreeBSD is not an officially supported platform at this time.

You may wish to track #3797

**Comment by anatoli26** [comment]
There's electron 4 in the ports for FreeBSD since end of May 2019 (https://www.freshports.org/devel/electron4/). Maybe this could be made to work now?
