### ISSUE TITLE
Unable to generate linux app using electron

### ISSUE THREAD

**Issue by gopi1989** [electron/electron#7180]
* Electron version: 1.3.5
* Operating system: Ubuntu 14LTS
Hi all,

       I generated **dist** files for my angularjs application,my intension is to create a **executables** for **Ubuntu environment**.I installed all the dependencies electron-prebuilt,electron-packager and node files
I used the following command to generate the linux executables using electron

`electron-packager ./dist app --platform linux --arch x64 --out ./dist/testingapp`

when i hit the above command in terminal i am getting the error below:

```
hub00085@hub00085-CQ3410IX:~/Desktop/files$ electron-packager ./dist --platform linux --arch x64 --out dist/workdesk
Packaging app for platform linux x64 using electron v1.3.5
Command failed: /bin/sh -c npm prune --production
npm ERR! Linux 4.4.0-36-lowlatency
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "prune" "--production"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path /tmp/electron-packager/linux-x64/workdesk-linux-x64/resources/app/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/tmp/electron-packager/linux-x64/workdesk-linux-x64/resources/app/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/electron-packager/linux-x64/workdesk-linux-x64/resources/app/npm-debug.log
```
Thanks in advance for the valuable help !!!

Regards,
Gopi Krishnan

**Comment by kevinsawicki** [comment]
This looks to be an issue with `electron-packager`, not electron core, could you reopen this issue against that repository? Thanks!

https://github.com/electron-userland/electron-packager/issues
