### ISSUE TITLE
High CPU usage on some machines

### ISSUE THREAD

**Issue by drFabio** [electron/electron#7181]
* Electron version: 1.3.4
* Operating system: Win 7 Ultimate on a Pentium p6100 2.0ghz

I have a application that is pretty much just a webSite saved, with very little front end js code.
On this specific machine (and a few others) the app consumes almost 100% of the cpu when maximized, and as little as 10%  when minimized. At first I thought it would be the fact that I am playing audio but if that was the case the minimized app would consume an equivalent amount of CPU.

On my machine a Windows 10 with a Intel Core i7-4510U 2 GHZ 2,6 GHZ it goes to 3% tops. Can this be something electron chromium or something else?

Thanks in advance

PS: I tested some of the buggy machines and on the same site it runs on about 5~20% on a chrome

**Comment by zcbenz** [comment]
Can you take a CPU profile with Chrome devtools?

**Comment by drFabio** [comment]
Here it is the high usage [cpu profile](http://fabiooliveiracosta.com/highUsageCPU5min.cpuprofile)

**Comment by zcbenz** [comment]
Can you try whether the problem is still there in Electron 1.4.0?

**Comment by drFabio** [comment]
So I tried with 1.4.0 And the problem still exists, funny thing is I can't save cpuprofiles anymore from devTools they all end up with 0 bytes.
Anyway I took some screenshots 
![minimized](https://cloud.githubusercontent.com/assets/2636143/18676173/1c922738-7f2b-11e6-9b2c-173d7bed564c.png)
![maximized](https://cloud.githubusercontent.com/assets/2636143/18676172/1c8e3970-7f2b-11e6-855a-d9a895d18e4f.png)

**Comment by drFabio** [comment]
It seems that is more a DOM/front end issue and how it deals with animation (there was an animation that was changing a Dom Element width causing the dom to be recalculated) and a hardware issue than anything related with electron or chromium. Don't know why the difference of performance on chrome and chromium though but is not a big issue.

Thanks for the help. The only thing I think maybe is worth a check is to see why cpuprofiles are not being saved on 1.4.

**Comment by s-a** [comment]
A user reported the same issue . [`Application takes 100% CPU and is unresponsive`](https://github.com/s-a/iron-node/issues/120)

**Comment by drFabio** [comment]
I Found out that on the page there was a playback bar that changed the width thus causing dom re rendenring and that had a impact of performance on the "crappy" machine of 30% , changing this to a css transform approach made it more usable. The page on chrome used less cpu but it's probably because it was not a foreground application and chrome put some restriction upon that.

**Comment by kevinsawicki** [comment]
> funny thing is I can't save cpuprofiles anymore from devTools they all end up with 0 bytes.

This was fixed today in #7413

**Comment by drFabio** [comment]
Should I be able to save timeline as well? It seems my problem is that the audio stops or chops on rendering when the cpu is too high. Chrome does not seem to behave the same way
