### ISSUE TITLE
bootstrap.py fails when trying to cross compile with --build_libchromiumcontent enabled

### ISSUE THREAD

**Issue by gautambt** [electron/electron#7185]
On a fresh ubuntu 14.04/16.04 docker image following instructions given in http://electron.atom.io/docs/development/build-instructions-linux/ I am seeing these errors:

FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj.host/v8/src/base/v8_libbase.functional.o.d -DU_COMBINED_IMPLEMENTATION -DUNISTR_FROM_CHAR_EXPLICIT= -DUNISTR_FROM_STRING_EXPLICIT= -DU_NO_DEFAULT_INCLUDE_UTF_HEADERS=0 -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=269902-1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_NOTIFICATIONS -DENABLE_TOPCHROME_MD=1 -DUSE_UDEV -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DV8_TARGET_ARCH_ARM -DCAN_USE_ARMV7_INSTRUCTIONS -DCAN_USE_VFP3_INSTRUCTIONS -DCAN_USE_VFP32DREGS -DCAN_USE_NEON -DV8_I18N_SUPPORT -DV8_SHARED -DBUILDING_V8_SHARED -DUSE_LIBPCI=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_EABI_HARDFLOAT=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../v8 -Igen -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -pipe -fPIC -Xclang -load -Xclang /builds/AtherEnergy/electron/vendor/brightray/vendor/libchromiumcontent/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -Xclang -plugin-arg-find-bad-constructs -Xclang check-implicit-copy-ctors -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -fcolor-diagnostics -g -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-unused-variable -m32 -fno-ident -funwind-tables  -O3 -fno-exceptions -fno-rtti -fno-threadsafe-statics -std=gnu++11 -Wno-deprecated  -c ../../v8/src/base/functional.cc -o obj.host/v8/src/base/v8_libbase.functional.o
In file included from ../../v8/src/base/functional.cc:11:
In file included from ../../v8/src/base/functional.h:13:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:55:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/tuple:39:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/array:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/stdexcept:39:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/string:52:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/basic_string.h:2815:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ext/string_conversions.h:44:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cerrno:41:
In file included from /usr/include/errno.h:35:
In file included from /usr/include/bits/errno.h:24:
/usr/include/linux/errno.h:1:10: fatal error: 'asm/errno.h' file not found
#include <asm/errno.h>

The same error is repeated for many files. 

I have installed libc6-dev-armhf-cross linux-libc-dev-armhf-cross g++-arm-linux-gnueabihf as well as linux-libc-dev

* Electron version: master
* Operating system: Ubuntu 14.04/16.04

**Comment by gautambt** [comment]
I've pushed the docker image to docker hub. The issue can be reproduced by:

1) docker run -it gautambt/electron-arm bash
2) cd root/electron
3) ./script/bootstrap.py --target=arm --build_libchromiumcontent -y

**Comment by kevinsawicki** [comment]
@gautambt do you have all of these packages installed? https://github.com/electron/electron/blob/b13bab6fae3dd5605d99f220c65693952eeb1f6e/script/cibuild#L13-L29

**Comment by Slamology2** [comment]
Documentaire dictionaire done.

**Comment by gautambt** [comment]
@kevinsawicki There seems to be a conflict between gcc-multilib and g++-arm-linux-gnueabihf. When I install g++-arm-linux-gnueabihf, gcc-multilib gets un-installed and vice versa. I've also tried installing gcc-multilib-arm-linux-gnueabihf and g++-multilib-arm-linux-gnueabihf  but the error remains.

**Comment by zcbenz** [comment]
Sorry but it is your responsibility to setup your cross-compile environment, we are unable to help you solve the dependency conflicts.
