### ISSUE TITLE
Access and modify webview history

### ISSUE THREAD

**Issue by victorporof** [electron/electron#7186]
- Electron version: 1.3.4
- Operating system: OS X

I'd be great to be able to access the history inside a webview, across multiple pages. Basically, it'd help us tremendously if we didn't have to duplicate the `history` store from https://github.com/electron/electron/blob/df3f0a45164ff990e7b94bc7aa485b4659280755/lib/browser/api/navigation-controller.js

**Comment by victorporof** [comment]
Just found out about webview.getWebContents().history, but there aren't any docs. I guess this isn't officially supported?

**Comment by kevinsawicki** [comment]
> Just found out about webview.getWebContents().history

@victorporof is this was made public, would it be enough? Or do you need any additional history APIs not currently provided/public on the `webContents` module?

**Comment by Mossop** [comment]
We're probably going to want a stable way to inject history entries into the navigation controller too for session restore like behaviours. Poking at the current internals is probably doable right now but it might be easier if there was a way to provide the session history for a webview up front.

**Comment by Mossop** [comment]
It looks like the following does work:

    webview.getWebContents().history = ["https://www.google.com", "https://www.mozilla.org"];
    webview.goToIndex(1);

**Comment by victorporof** [comment]
Is the above safe to use? Will it be standardized? There's still no documentation about it, and we're wary of using undocumented APIs that might break in future releases.

**Comment by steverandy** [comment]
Is there a function/attribute to get the current index of the webview history?

**Comment by jsantell** [comment]
@steverandy I believe `webview.getWebContents().getActiveIndex()` will report the current index

**Comment by Devhercule** [comment]
this code works : 

`webview.getWebContents().history = ["https://www.google.com", "https://www.mozilla.org"];`

but this one, does not work : 

`webview.getWebContents().history[5] = "http://wwww.google.com/about";`

The history array is accessible or not? can we modify it? Eventually, can we modify the goBack() function?

**Comment by miniak** [comment]
This is already doable with existing APIs

**Comment by flightmansam** [comment]
@miniak 
> This is already doable with existing APIs

Is e.g. ```webview.getWebContents().history = ["https://www.google.com", "https://www.mozilla.org"];``` what you mean by 'doable with existing APIs'?

**Comment by tomvonclef** [comment]
@miniak I'm sorry, I don't know what you mean by 'doable with existing APIs' either.
