### ISSUE TITLE
Unable to paste clipboard entry created with writeBookmark on Windows

### ISSUE THREAD

**Issue by jnugh** [electron/electron#7190]
* Electron version: v1.3.5
* Operating system: Windows 10

Based on issue: https://github.com/sindresorhus/electron-context-menu/issues/18

_What happens:_
1. Copy a link by using `electron.clipboard.writeBookmark`
2. Focus a text field and press `CTRL+c` - nothing happens
3. Listen to `context-menu`, do a right click on a text field: `canPaste` is false

I'm able to paste these bookmarks into the Chrome address bar (which seems to be the only place).

_What I expected:_
2. and 3. should paste the link into the text field. As it does on MacOS.

Maybe this is intended behavior - in this case this should be documented and consistent across Mac&Win I guess.

**Comment by kevinsawicki** [comment]
Looked into this a bit, I think the bookmark type is not as widely supported on Windows as it is on macOS.

I think the best thing to do in `electron-context-menu` is to use `clipboard.write` instead and write text and a bookmark at the same time for the `Copy Link` action:

```js
clipboard.write({
  text: 'http://birthday.pizza',
  bookmark: 'a website'
})
```

The above snippet seems to work correctly on macOS and Windows, you can still access the bookmark with `clipboard.readBookmark()` but apps not supporting bookmarks can still fallback to text support.

Updating this issue to update the docs to make this clearer.
