### ISSUE TITLE
Selecting files without extensions in an Open File Dialog

### ISSUE THREAD

**Issue by Cu3PO42** [electron/electron#7191]
On macOS I can select all files without an extension by using

```javascript
{
    filters: [{name: 'No extensions', filters: ['']}]
}
```

This does not work on Windows, it does not show any files as far as I can tell.  
I am currently using Electron 1.2.1. I can currently not test this behavior as I don't have access to a Linux machine, but just about a year ago it didn't work. I suspect this is a limitation of the native file opening dialogs that cannot be easily worked around. But I wanted to inquire if I was missing something.

If in fact this is a limitation of the dialogs, I may also take a stab at working around it on Windows if there's a demand for it.

**Comment by kevinsawicki** [comment]
I'm not sure this is possible using the Windows dialog path filter APIs, have you seen other apps with this type of filtering on Windows?

**Comment by Cu3PO42** [comment]
I thought I did, but after checking again, it turns out that the application just shows all files. It would be possible to extend the relevant dialog classes and implement more filters that way, however I doubt that would be worth the effort.

**Comment by zcbenz** [comment]
This is a limitation of win32 API, I tried to use `*` instead of `*.*` to filter files with win32 API, but it selects all files instead of files without extensions, so it is impossible to implement on Windows unless we draw our own file dialog.

I'm closing this as won't fix.
