### ISSUE TITLE
Mouse pointer keeps changing itself to standard pointer intermittently

### ISSUE THREAD

**Issue by screenmeet** [electron/electron#7192]
* Electron version: 1.3.5
* Operating system: Mac OSX 10.11.3

I am getting a weird behavior with the mouse in electron. I am on Mac OSX. Electron 1.3.5.

Basically, once in a while the cursor keeps resetting itself to the default cursor even when it's moused over an element which is supposed to have a different mouse pointer. For example, if I am hovering over a text input, sometimes the text-input "I" cursor turns back into a regular pointer, it will stay that way until I hover out of the text input and over some other element.

The same behavior happens with other cursor types, too, such as the "pointer" for links/buttons. Once in a while it just changes back to the regular pointer. I can reproduce this pretty consistently.

Wondering if anyone else has experienced this and if there are any fixes or work-arounds.

**Comment by albinekb** [comment]
I have noticed this in atom, but I thought it was just something with my setup 🤔

**Comment by screenmeet** [comment]
Well, at least I'm not the only one. Would love some input from the developers on this one...

**Comment by kevinsawicki** [comment]
@screenmeet can you confirm you see this on 1.4.0 as well?

**Comment by screenmeet** [comment]
I just tried this this in 1.4.0 and it looks like the issue's been fixed. Thanks!
