### ISSUE TITLE
IPC from renderer to renderer

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#7193]
* Electron version: All
* Operating system: Any

So, let's say I'm in a renderer and I'd like to send an IPC message (OK, a _lot_ of IPC messages) to a different `BrowserWindow` (the `webContents` of that window, to be precise). I know the ID of the window, so I do something like:

``` js
BrowserWindow.fromId(otherWindowId).webContents.send(aMessage);
```

Simple enough. But when I test it out, performance is terrible! Why? Well because the `webContents` I got was a remote object all along:

``` js
const BrowserWindow = require('electron').remote.BrowserWindow;
```

And that means that I'm doing an `ipc.sendSync` to an object in the main process, before I can IPC to the other renderer. If I'm trying to send a lot of messages very quickly (for example, shuttling video frames), this is untenable. 

We have worked around this by setting up a proxy in the main process:
``` js
ipcMain.on('inter-window-message', (e, windowId, ...args) => {
  let browserWindow = BrowserWindow.fromId(windowId);
  browserWindow.webContents.send('inter-window-message', ...args);
});
```
So now we're doing two _asynchronous_ IPC messages instead of one sync and another async. But it's still twice the IPC traffic. It would be great if we could get a pointer to other `webContents` _without_ creating a remote object in the main process. Is this possible / easy to do?

**Comment by MarshallOfSound** [comment]
Personally I've always used the bounce workaround that you mentioned.  Sending a wrapped version of the message to the main process that then forwards it on the target renderer process.  But I've never needed the performance your use case appears to require.

It sounds you like might be better served hosting a localhost RPC server in one renderer process and communicating with that from the other?

**Comment by zcbenz** [comment]
There is an internal `sendTo` helper:

```js

ipcRenderer.sendTo = function (webContentsId, channel, ...args) {
  if (typeof webContentsId !== 'number') {
    throw new TypeError('First argument has to be webContentsId')
  }

  ipcRenderer.send('ELECTRON_BROWSER_SEND_TO', false, webContentsId, channel, ...args)
}
```

But you have to get the ID of webContents first and the message would still be rerouted in the main process. This cost is impossible to get eliminated because `webContents` is not available in the renderer process..

**Comment by paulcbetts** [comment]
Getting the ID of the renderer is nbd, it's the actual cost of sending frames - are you saying that even sendTo will go through the browser?

**Comment by paulcbetts** [comment]
@zcbenz We might have a hack at trying to expose a native version of sendTo so that we can IPC directly (hopefully without dragging in all of `webContents`)

**Comment by zcbenz** [comment]
@paulcbetts Yeah `sendTo` still goes to the main process and it has to, it is not possible to send messages between renderer processes directly because Chromium designed so for security.

If you really want to get away from the main process you have to write IPC code from scratch, with either's Node's `net` module or Chromium's `ipc` component.

**Comment by CharlieHess** [comment]
OK thanks for the clarification @zcbenz, I'll go ahead and close this.

**Comment by raphael10-collab** [comment]
@CharlieHess would you be so kind in giving me some hints about how to correctly proceed in inter-windows communication?

In the main process main.ts I send the just opened window's ID to the mainwindow :  

    ipcMain.handle("open-type-A-window", (IpcMainEvent, message) => {
      WindowTypeA.loadURL('http://localhost:3000/main_window2');
      WindowTypeA.show();
      mainWindow.webContents.send("window-A-channel", WindowTypeA.id);
    });

    ipcMain.on('inter-window-message', (event, windowIdd, args) => {
      let browserWindow = BrowserWindow.fromId(windowId);
      browserWindow.webContents.send('inter-window-message', args);
    });


In preload.ts I defined this "api":

    contextBridge.exposeInMainWorld(
      "api", {
          electronIpcSendTo: (window_id: string, channel: string, ...arg: any) => {
            ipcRenderer.sendTo(window_id, channel, arg);
          },
          electronIpcOn: (channel: string, listener: (event: any, ...arg: any) => void) => {
            ipcRenderer.on(channel, listener);
          },
      }
    )

and defined the corresponding window "api":

    declare interface Window {
      api: {
        electronIpcSendTo: (window_id: string, channel: string, ...arg: any) => void;
        electronIpcOn: (channel: string, listener: (event: any, ...arg: any) => void) => void;
      }
    }

In the renderer of the mainwindow (window 1) I've put the electronIpcOn and electronIpcSend methods:

        window.api.electronIpcOn("window-A-channel", (event, args) => {
          console.log("App.tsx-window.api-electronIpcOn-window-A-channel-args: ", args);
          window_id = args;
        });
        window.api.electronIpcSendTo("inter-window-message", window_id, fp);

And in the renderer of the receiving window (window-A) I've put the electronIpcOn method:

      window.api.electronIpcOn("inter-window-message", (event, args) => {
        console.log("App-A-window.api.electronIpcOn-inter-window-message-args: ", args);
     });

The renderer of the mainwindow correctly gets the window_id of window-A, but nor main process neither the window-A received the data (fp) sent from the mainWindow (window 1)

What am I doing wrong? How to fix it?
