### ISSUE TITLE
Change the name of app during windows firewall alert popup?

### ISSUE THREAD

**Issue by Sid21m** [electron/electron#7198]
* Electron version: electron prebuilt 1.2.5
* Operating system: Windows 7 64 bit
![electronbug](https://cloud.githubusercontent.com/assets/13000732/18508881/be25e5d6-7a93-11e6-9df4-94a06f4cb64b.png)

**Comment by MarshallOfSound** [comment]
@Sid21m These values are determined from your `.exe` metadata on Windows.

If you are using Electron Packager you can set this metadata at build time using this option  
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#win32metadata
