### ISSUE TITLE
Can not run electron command on Arm device

### ISSUE THREAD

**Issue by sn0opr** [electron/electron#7199]
* Electron version:1.3.4
* Operating system: Debian Jessie

I have an Olimex with ARM arch, I'm not able to run electron command when for example I run ```electron .``` nothing happen, not even an error, but when I packaged my electron app with ARM as arch and run it with startx everything works as expected.

**Comment by MarshallOfSound** [comment]
Can you try with logging enabled.

```bash
export ELECTRON_ENABLE_LOGGING=true
export ELECTRON_ENABLE_STACK_DUMPING=true
electron .
```

**Comment by kevinsawicki** [comment]
@sn0opr are you on ARM 6, 7, or 8?

**Comment by sn0opr** [comment]
@MarshallOfSound after exporting those variables and running `sudo startx $(electron .)` I get this output:

```
[2610:0903/095957:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[2610:0903/095958:ERROR:browser_main_loop.cc(283)] Gtk: Locale not supported by C library.
	Using the fallback 'C' locale.
[2610:0903/095958:ERROR:browser_main_loop.cc(283)] Gtk: cannot open display: 


X.Org X Server 1.16.4
Release Date: 2014-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-0.bpo.4-armmp-lpae armv7l Debian
Current Operating System: Linux AM3352-SoM 3.12.10-ti2013.12.01 #5 Wed Feb 11 11:07:18 EET 2015 armv7l
Kernel command line: console=ttyO0 console=ttyO0,115200n8 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait cmdline=quiet init=/lib/systemd/systemd
Build Date: 11 February 2015  01:18:06AM
xorg-server 2:1.16.4-1 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sat Sep  3 09:59:58 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
```

@kevinsawicki My ARM version: armv7l

Thank's

**Comment by MarshallOfSound** [comment]
Does how Olimex have a display / a graphical output or is it a headless machine?

**Comment by sn0opr** [comment]
@MarshallOfSound by default the Olimex doesn't have a display, we plugged a touch screen on it and it's working fine and showing the terminal.
Note: that the electron app works fine if I run it in an electron package: `sudo startx ./myElectronExecutable` because I generated a package with arm architecture, the problem is that I can't run it with the electron command.
Thank's

**Comment by MarshallOfSound** [comment]
As far as I am aware, and @kevinsawicki might chime in again here.  Electron requires a GUI environment to operate, the errors you are seeing are it failing to find and attach itself to such an environment.

I honestly don't know why your built version works and the prebuilt does not (as they should be the same executable).  Perhaps it is the `sudo` permission level that is giving your built version access to something that simply running `electron .` does not.

**Comment by zcbenz** [comment]
The requirement for Electron to run is the same with other Linux GUI programs, I suggest configuring your system to at least make a simple GTK+ app run before trying Electron.

Closing since this is a Linux configuration problem.

**Comment by sn0opr** [comment]
@zcbenz  as I said, my electron app does work correctly if I run it from an electron package (which is built with arm as arch).

**Comment by zcbenz** [comment]
@sn0opr I suggest seeking help from Linux forums, it is apparently not an issue of Electron since packaged app works.
