### ISSUE TITLE
Packaged Electron-app using Node AtomInitializeICUandStartNode problem 

### ISSUE THREAD

**Issue by riccitensor** [electron/electron#7200]
* Electron version: 1.3.4 (electron-prebuilt package), (also: electron-packager 7.5.1)
* Operating system: OS X 10.11.4 (El Capitan)

My dmg-packaged app (using Node 6.2.1)  is crashing (not immediately, but after some undefined period of time). It probably happens every time. I found this https://github.com/electron/electron/issues/4299, for an old version of Electron, but that does not solve my problem.

`101 libnode.dylib                 	0x000000010596a31b 0x1052ab000 + 7074587
102 libnode.dylib                 	0x000000010596a11b v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 331
103 libnode.dylib                 	0x000000010563d237 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 535
104 libnode.dylib                 	0x0000000105392302 node::LoadEnvironment(node::Environment*) + 386
105 com.github.electron.framework 	0x0000000100ccea30 atom::NodeMain(int, char**) + 560
106 com.github.electron.framework 	0x0000000100ccb83c AtomInitializeICUandStartNode + 300
107 node                          	0x0000000100cc0ebf main + 31
108 libdyld.dylib                 	0x00007fff8fc335ad start + 1`

The dump --

`Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff9e86ef06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff926ee4ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff984db6e7 abort + 129
3   libnode.dylib                 	0x000000010538bc82 node::Abort() + 34
4   libnode.dylib                 	0x000000010538e2ba 0x1052ab000 + 930490
5   libnode.dylib                 	0x000000010562284a v8::Utils::ApiCheck(bool, char const*, char const*) + 58
6   libnode.dylib                 	0x00000001056227ee v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) + 526
7   libnode.dylib                 	0x0000000105973d97 v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) + 455
8   libnode.dylib                 	0x0000000105668344 v8::internal::ObjectLiteral::BuildConstantProperties(v8::internal::Isolate*) + 52
9   libnode.dylib                 	0x00000001056649f0 v8::internal::AstNumberingVisitor::VisitObjectLiteral(v8::internal::ObjectLiteral*) + 240
10  libnode.dylib                 	0x00000001056649c8 v8::internal::AstNumberingVisitor::VisitObjectLiteral(v8::internal::ObjectLiteral*) + 200
11  libnode.dylib                 	0x0000000105663f17 v8::internal::AstNumberingVisitor::VisitAssignment(v8::internal::Assignment*) + 151
12  libnode.dylib                 	0x0000000105663421 v8::internal::AstNumberingVisitor::VisitExpressionStatement(v8::internal::ExpressionStatement*) + 49
13  libnode.dylib                 	0x00000001056636d8 v8::internal::AstNumberingVisitor::VisitBlock(v8::internal::Block*) + 200
14  libnode.dylib                 	0x0000000105664349 v8::internal::AstNumberingVisitor::VisitIfStatement(v8::internal::IfStatement*) + 105
15  libnode.dylib                 	0x0000000105664e27 v8::internal::AstNumberingVisitor::Renumber(v8::internal::FunctionLiteral*) + 359
16  libnode.dylib                 	0x0000000105664fbf v8::internal::AstNumbering::Renumber(v8::internal::Isolate*, v8::internal::Zone*, v8::internal::FunctionLiteral*) + 303
17  libnode.dylib                 	0x0000000105832715 v8::internal::Compiler::Analyze(v8::internal::ParseInfo*) + 53
18  libnode.dylib                 	0x00000001058347c0 0x1052ab000 + 5806016
19  libnode.dylib                 	0x0000000105832bca v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) + 1034
20  libnode.dylib                 	0x0000000105bab076 v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) + 214
21  ???                           	0x0000159b8ea08ba7 0 + 23757857000359
22  ???                           	0x0000159b8ea2e03a 0 + 23757857153082
23  ???                           	0x0000159b8fd471ac 0 + 23757877178796
24  ???                           	0x0000159b8fdbe8aa 0 + 23757877668010
25  ???                           	0x0000159b8fd50c26 0 + 23757877218342
26  ???                           	0x0000159b8fd501c9 0 + 23757877215689
27  ???                           	0x0000159b8fd4f712 0 + 23757877212946
28  ???                           	0x0000159b8fd4ebf7 0 + 23757877210103
29  ???                           	0x0000159b8fd4e6eb 0 + 23757877208811
30  ???                           	0x0000159b8fd4dc73 0 + 23757877206131
31  ???                           	0x0000159b8ec12e6e 0 + 23757859139182
32  ???                           	0x0000159b8fd509f1 0 + 23757877217777
33  ???                           	0x0000159b8fd501c9 0 + 23757877215689
34  ???                           	0x0000159b8fd4f712 0 + 23757877212946
35  ???                           	0x0000159b8fd4ea68 0 + 23757877209704
36  ???                           	0x0000159b8fd4e6eb 0 + 23757877208811
37  ???                           	0x0000159b8fd4dc73 0 + 23757877206131
38  ???                           	0x0000159b8fd45f92 0 + 23757877174162
39  ???                           	0x0000159b8fd54b9f 0 + 23757877234591
40  ???                           	0x0000159b8fd61603 0 + 23757877286403
41  ???                           	0x0000159b8fdc1112 0 + 23757877678354
42  ???                           	0x0000159b8eb48258 0 + 23757858308696
43  ???                           	0x0000159b8fd514ac 0 + 23757877220524
44  ???                           	0x0000159b8fd507d3 0 + 23757877217235
45  ???                           	0x0000159b8fd501c9 0 + 23757877215689
46  ???                           	0x0000159b8fd500ab 0 + 23757877215403
47  ???                           	0x0000159b8fd4ea68 0 + 23757877209704
48  ???                           	0x0000159b8fd4e6eb 0 + 23757877208811
49  ???                           	0x0000159b8fd4dc73 0 + 23757877206131
50  ???                           	0x0000159b8fd25479 0 + 23757877040249
51  ???                           	0x0000159b8ec6627d 0 + 23757859480189
52  ???                           	0x0000159b8fd51014 0 + 23757877219348
53  ???                           	0x0000159b8fd507d3 0 + 23757877217235
54  ???                           	0x0000159b8fd501c9 0 + 23757877215689
55  ???                           	0x0000159b8fd500ab 0 + 23757877215403
56  ???                           	0x0000159b8fd4ea68 0 + 23757877209704
57  ???                           	0x0000159b8fd4e6eb 0 + 23757877208811
58  ???                           	0x0000159b8fd4dc73 0 + 23757877206131
59  ???                           	0x0000159b8feed9e9 0 + 23757878909417
60  ???                           	0x0000159b8fdd9a6e 0 + 23757877779054
61  ???                           	0x0000159b8fd51086 0 + 23757877219462
62  ???                           	0x0000159b8fd507d3 0 + 23757877217235
63  ???                           	0x0000159b8fd501c9 0 + 23757877215689
64  ???                           	0x0000159b8fd500ab 0 + 23757877215403
65  ???                           	0x0000159b8fd4ea68 0 + 23757877209704
66  ???                           	0x0000159b8fd4e6eb 0 + 23757877208811
67  ???                           	0x0000159b8fd4dc73 0 + 23757877206131
68  ???                           	0x0000159b8ec12e6e 0 + 23757859139182
69  ???                           	0x0000159b8fd509f1 0 + 23757877217777
70  ???                           	0x0000159b8fd501c9 0 + 23757877215689
71  ???                           	0x0000159b8fd500ab 0 + 23757877215403
72  ???                           	0x0000159b8fd4fc7e 0 + 23757877214334
73  ???                           	0x0000159b8fd4ea68 0 + 23757877209704
74  ???                           	0x0000159b8fd4e6eb 0 + 23757877208811
75  ???                           	0x0000159b8fd4dc73 0 + 23757877206131
76  ???                           	0x0000159b8fd45f92 0 + 23757877174162
77  ???                           	0x0000159b8fd54b9f 0 + 23757877234591
78  ???                           	0x0000159b8fd61603 0 + 23757877286403
79  ???                           	0x0000159b8ebfae87 0 + 23757859040903
80  ???                           	0x0000159b8fd5f17d 0 + 23757877277053
81  ???                           	0x0000159b8fd5eca4 0 + 23757877275812
82  ???                           	0x0000159b8fd5dd1b 0 + 23757877271835
83  ???                           	0x0000159b8fd2aba1 0 + 23757877062561
84  ???                           	0x0000159b8ec46205 0 + 23757859348997
85  ???                           	0x0000159b8ec44421 0 + 23757859341345
86  ???                           	0x0000159b8ebd6acc 0 + 23757858892492
87  ???                           	0x0000159b8ebd678d 0 + 23757858891661
88  ???                           	0x0000159b8eb50d4c 0 + 23757858344268
89  ???                           	0x0000159b8eb51012 0 + 23757858344978
90  ???                           	0x0000159b8eb5004e 0 + 23757858340942
91  ???                           	0x0000159b8eb46d4b 0 + 23757858303307
92  ???                           	0x0000159b8eb45772 0 + 23757858297714
93  ???                           	0x0000159b8eb4529d 0 + 23757858296477
94  ???                           	0x0000159b8eb3d0e6 0 + 23757858263270
95  ???                           	0x0000159b8eb3cbf0 0 + 23757858262000
96  ???                           	0x0000159b8eb3ca88 0 + 23757858261640
97  ???                           	0x0000159b8ea67fdf 0 + 23757857390559
98  ???                           	0x0000159b8ea660a1 0 + 23757857382561
99  ???                           	0x0000159b8ea45fa3 0 + 23757857251235
100 ???                           	0x0000159b8ea29f0f 0 + 23757857136399
101 libnode.dylib                 	0x000000010596a31b 0x1052ab000 + 7074587
102 libnode.dylib                 	0x000000010596a11b v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 331
103 libnode.dylib                 	0x000000010563d237 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 535
104 libnode.dylib                 	0x0000000105392302 node::LoadEnvironment(node::Environment*) + 386
105 com.github.electron.framework 	0x0000000100ccea30 atom::NodeMain(int, char**) + 560
106 com.github.electron.framework 	0x0000000100ccb83c AtomInitializeICUandStartNode + 300
107 node                          	0x0000000100cc0ebf main + 31
108 libdyld.dylib                 	0x00007fff8fc335ad start + 1
`

**Comment by kevinsawicki** [comment]
> v8::internal::V8::FatalProcessOutOfMemory

It looks like your app is running out of memory, this could be a memory leak in your app or a leak in electron core.

A minimal example app reproducing this would be really helpful if you think it is unrelated to your app and we can investigate it as a core Electron issue.

**Comment by kevinsawicki** [comment]
> v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) + 455 8 libnode.dylib 

It looks like the crash may be occurring when creating a new (possibly very large) array.

**Comment by riccitensor** [comment]
I investigated the issue and it turns out that it is indeed a memory leak in a 3rd party app that I am using. This is not related to Electron, so I am closing the issue.
