### ISSUE TITLE
White window before the actual content

### ISSUE THREAD

**Issue by Sid21m** [electron/electron#7201]
* Electron version: Prebuilt 1.2.5
* Operating system: Win 7 64 bit
![electron bug 2](https://cloud.githubusercontent.com/assets/13000732/18509334/a7437ef8-7a95-11e6-91b8-4a31b6f286d5.png)

**Comment by enlight** [comment]
Does this happen with the latest release? If so can you provide some reproduction steps and/or a minimal sample app that can be used to reproduce this issue?

**Comment by paul321** [comment]
You should manually do win.show() after all the code is loaded

**Comment by zcbenz** [comment]
You can find how to avoid the white flash in the documentation of `BrowserWindow`:
http://electron.atom.io/docs/api/browser-window/#showing-window-gracefully
