### ISSUE TITLE
Mention npm run clean in build docs

### ISSUE THREAD

**Issue by jwheare** [electron/electron#7202]
* Electron version: 1.3.6
* Operating system: macOS 10.11.6
* Node: 5.12.0
* NPM: 3.8.6
* node-gyp: 3.3.1

I'm getting errors running a build from a clean checkout of current master cfe7bfd. I've installed the Xcode 8 GM seed, but *not* the Sierra GM seed. Not sure if this setup is supported or has been tested by the core team but it's probably relatively common at the moment, so hopefully the report is useful (might of course be something else up with my environment)

I've wiped my `~/.node-gyp` directory, here's my `npm list -g` output:
https://gist.github.com/jwheare/96cf303335a2e18f8c28c8b03e670632

The first sign of trouble is during  `./script/bootstrap.py -v`, while building `bufferutil` and `utf-8-validate`:
https://gist.github.com/jwheare/00bb13d4d7c1e1ed3614c36f3de51c4e
https://gist.github.com/jwheare/8acb33ca0e0c10be7bb1d46f4280e728

The rest of bootstrap appears to run correctly and exits normally.

But then `./script/build.py -c D` fails building `inspectable_web_contents_view`:
https://gist.github.com/jwheare/11322048eb8a4279d5b87c059b86b47a

Any ideas?

**Comment by thomasjo** [comment]
Does it work if you downgrade to Xcode 7.3? That's the easiest way to rule out Xcode 8 being an issue. Skimming over the log output seems to indicate another source of this error since none of them are (as far as I can tell) caused by any changes to compiler infrastructure, libraries, etc.

**Comment by jwheare** [comment]
Huh, downgrading was easier than I had assumed.

After switching back to 7.3.1 with xcode-select, I still get the bootstrap errors, but the build completes successfully.

**Comment by thomasjo** [comment]
OK, thanks for that. I'll try to reproduce here.

**Comment by thomasjo** [comment]
I was unable to reproduce your problem, so most likely an environmental problem. I followed the [build instructions](https://github.com/electron/electron/blob/4627311c34ec2ac636e54e8448b72d3d87344328/docs/development/build-instructions-osx.md) to the dot in a completely fresh repo.

macOS 10.11.6
Node v6.5.0
npm v3.10.7

**Comment by jwheare** [comment]
The errors look possibly related to missing SDKs for various versions of OSX. I'll see if I have them all installed and try again.

**Comment by jwheare** [comment]
My Xcode 8 only has the 10.12 SDK bundled, and 7.3.1 only has 10.11.

It looks like the version of `vendor/brightray/vendor/download/libchromiumcontent/src/base/mac/sdk_forward_declarations.h` that got downloaded by the bootstrap script is quite old (at least 3 months old) and doesn't have any `MAC_OS_X_VERSION_10_12` ifdefs. Does yours have it?

Latest is here: https://chromium.googlesource.com/chromium/src.git/+/lkcr/base/mac/sdk_forward_declarations.h

**Comment by jwheare** [comment]
Oh... vendor/brightray/vendor/download is gitignored in a submodule, and I only cleaned the root working directory. I'll `git submodule foreach git clean -xfd` and try again.

**Comment by jwheare** [comment]
Well that fixed it, but only after I pulled again and resynced submodules, so maybe I was suffering from an updated submodule race condition. I seem to have submodules issues every time I try to compile electron, and I'm pretty sure I made a fresh clone when this first started happening too. Probably worth documenting a reminder to fully clean submodules on the build instructions.

**Comment by kevinsawicki** [comment]
There is a `npm run clean` helper that does explicitly remove the `vendor/brightray/vendor/download/libchromiumcontent` and `vendor/brightray/vendor/libchromiumcontent/src` folder (among others).

> Probably worth documenting a reminder to fully clean submodules on the build instructions.

Agreed, sounds good, updating the issue to refer to that 👍
