### ISSUE TITLE
update-available only called after the update has been downloaded on windows

### ISSUE THREAD

**Issue by andymartinwork** [electron/electron#7204]
* Electron version: 1.3.4
* Operating system: Windows

We allow our users to check for updates manually, so listen to the auto-updater events and respond with dialogs.

After noticing it takes a long time to get a response on update-available, we looked through charles and noticed that the event only fires after the update has been downloaded. And update-downloaded only fires once the update has been installed (which is ok with me).

**Comment by zcbenz** [comment]
I'm merging this to #4587.
