### ISSUE TITLE
Customized user-agent is not used when opening WebSocket

### ISSUE THREAD

**Issue by chris281** [electron/electron#7205]
* Electron version: 1.3.4
* Operating system: Windows 10/ Max OS X

When setting a customized user-agent via Window.WebContents.setUserAgent, this user-agent is not used when opening a WebSocket connection. Instead of this the standard user-agent is used.

**Comment by deepak1556** [comment]
Seems to be a regression since chrome 51 upgrade, but has been fixed by chrome 53 upgrade. You can use `session.webRequest.onBeforeSendHeaders` as a workaround.

**Comment by chris281** [comment]
The workaround works correctly for us.
Thanks!
I'll wait for the new Chrome version to be integrated and then we can close the ticket I think.

**Comment by deepak1556** [comment]
@chris281 can you verify if 1.4.0 fixes the problem ?

**Comment by chris281** [comment]
We tested it now and the workaround is no longer necessary i.e. the problem is fixed with 1.4.0

**Comment by chris281** [comment]
Solved with new Chrome version in Electron 1.4.0
