### ISSUE TITLE
webContents.startDrag > effectAllowed is only "copy"

### ISSUE THREAD

**Issue by bunterWolf** [electron/electron#7207]
webContents.startDrag #6333 works awesome! Thanks!!!!! :)
But the [DataTransfer.effectAllowed](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/effectAllowed) of this drag is set to "copy" only. 
And I see no way to have an influence on that?

If I drag a file form my desktop to electron the effectAllowed is "all" 
Is it possible to that set effectAllowed:"all" for webContents.startDrag too?

**This is for mouse-cursor aesthetics only, not for function.** 
On OSX the dropEffect defines how your mousecursor looks, to show the user which action will happen. If I set the dropEffect in the onDragOver event to "move", the cursor looks right. But when the user drops, OSX does the cancel animation. (Placeholder Image moves back to where it comes from). Because "move" is not allowed.
- Electron: 1.3.6
- OSX: 10.11

**Comment by zcbenz** [comment]
`DataTransfer.effectAllowed` only works for HTML5 drag inside web pages, while `startDrag` is wrap of native call that independent from web pages.

`startDrag` is more a hack around the abilities provided by Chromium, to implement what you want we have to refactor Chromium's dragging code, which we do not have resources to do. So I'm closing this as won't fix.
