### ISSUE TITLE
shell.openItem() is not async

### ISSUE THREAD

**Issue by WholeMilk** [electron/electron#7210]
- Electron version: 1.3.6
- Operating system: Windows 7 x64
- Other: Microsoft Office 2013 (will make more sense in a bit)

`shell.openItem()` is a blocking call, it would be nice if it's async or has an async version to handle synchronous external application behavior.

Reproduce: 
Open a password-protected Microsoft Excel file, `shell.openItem()` will be blocking until the Password window is submitted or dismissed. Consequently Microsoft Word does not have this issue.

Related to #2761.

**Comment by kevinsawicki** [comment]
Merging this into #6889 which had already requested something similar for `shell.openExternal`

**Comment by dominic-simplan** [comment]
@kevinsawicki could you reopen this, as it seems that #6889 has been closed without implementing async behaviour for openItem().
