### ISSUE TITLE
Network throttling only partly works, does not affect node APIs

### ISSUE THREAD

**Issue by dcposch** [electron/electron#7212]
* Electron version: 1.3.5
* Operating system: MacOS El Capitan

### Steps to reproduce:
* Write renderer code that uses Node networking APIs, for example `http`
* Enable network throttling, either manually using DevTools or via `session`:
```
electron.remote.getCurrentWindow().session.enableNetworkEmulation({offline: true})
```

### Expected result

Network conditions should be the same using browser APIs (eg XHR) and node APIs (eg `http`).

### Actual result

Browser APIs are throttled, node APIs continue at the same speed. (Also, because of a Chrome bug, WebRTC is not throttled even though it's a browser API: https://bugs.chromium.org/p/chromium/issues/detail?id=490143 )

This might be expected behavior, but in that case it should be documented.

I think it would be helpful to have a some way to put an Electron app into offline mode for testing. Expanding `enableNetworkEmulation` to cover Node APIs would work. Alternatively, we could add a new option to Electron or Spectron.

**Comment by deepak1556** [comment]
Yup this is the expected behavior, currently network throttling is tightly coupled to the network stack of chromium. If we need to implement it for node, needs work in the upstream repositories to provide certain hooks. You can get away with system network throttlers for now ?

**Comment by dcposch** [comment]
@deepak1556 yeah, I found a workaround that doesn't involve network throttling

**Comment by zcbenz** [comment]
Extending for Node APIs basically means rewriting the whole Node APIs with Chromium's networking stack, I'm afraid currently no one would have resources to do that.
