### ISSUE TITLE
Same problems reported in #6599 are still there

### ISSUE THREAD

**Issue by webarchymeta** [electron/electron#7215]
* Electron version: 1.3.5
* Operating system: Windows 10

Other related info is the same as in #6599. Chromium based browsers seem to be not capture-able by `desktopCapturer` ...

**Comment by MarshallOfSound** [comment]
Please do not raise duplicate issues.  This issue is still open and marked as `more-information-needed`.  If you have additional information regarding this issue, please add it to that thread.
