### ISSUE TITLE
Screen wrapping with getUserMedia

### ISSUE THREAD

**Issue by jf908** [electron/electron#7219]
* Electron version: 1.4.0
* Operating system: Windows 10

When using navigator.mediaDevices.getUserMedia or navigator.webkitGetUserMedia, a few pixels of the screen's right side is shown on the left side of the video.

I found [someone else](http://stackoverflow.com/questions/38286010/getusermedia-not-capturing-the-screen-correctly) with the same issue but no solution.

Example:
Actual screen: http://i.imgur.com/wRA1LWw.png
What is streamed: http://i.imgur.com/RK7JpU6.png

**Comment by zcbenz** [comment]
Electron just uses Chromium for `getUserMedia`, so I suggest reporting this to [Chromium's issues list](https://crbug.com) instead. I'm closing this because it is an upstream bug and we are unable to fix it on Electron's side.
