### ISSUE TITLE
net::ERR_INSECURE_RESPONSE errors

### ISSUE THREAD

**Issue by steverandy** [electron/electron#7221]
* Electron version: 1.4.0
* Operating system: OS X 10.11.6

After updating to electron v1.4.0, I noticed getting a lot of `ERR_INSECURE_RESPONSE` from the requests in a webview.
I have tried the same website (http://www.bloomberg.com/) on electron v.1.3.6 and not getting any error.

![screen shot 2016-09-16 at 4 32 28 pm](https://cloud.githubusercontent.com/assets/525332/18580059/e05e3826-7c2b-11e6-9744-4d240d2f4e03.png)

**Comment by deepak1556** [comment]
`net-log` trace shows connection failed with `ERR_CERTIFICATE_TRANSPARENCY_REQUIRED`. Need to fix our certificate verifier implementation.

**Comment by sleevi** [comment]
@deepak1556 See https://github.com/electron/brightray/issues/248 for the root cause and fix

**Comment by azer** [comment]
I'm getting same error for [flickr](http://flickr.com)

**Comment by kevinsawicki** [comment]
The fix for this issue was released in `1.4.1`, huge thanks to @sleevi for all the details on the underlying issue and needed changes.

**Comment by mccxiv** [comment]
So, this is suddenly happening on `1.4.2` to all users of my app. No code was changed, I have no idea how to debug this.

Console:
![](http://puu.sh/sB8zf/71d6d6219b.png)

Network tab:
![](http://puu.sh/sB8xr/d000a084f7.png)

Network tab details:
![](http://puu.sh/sB8AY/7df68353ec.png)

Sample links that cause this error (work fine in chrome):  
https://static-cdn.jtvnw.net/badges/v1/3267646d-33f0-4b17-b3df-f923a41db1d0/1  
https://www.twitch.tv/bits/config.json


Any workaround or steps I can do to investigate further?

**Comment by sleevi** [comment]
This was mentioned in https://github.com/electron/brightray/issues/248

> If you want to support CT with Chromium's policy, use net::ct::CreateLogVerifiersForKnownLogs(). However, you should only do so with a reasonable update schedule in place; the set of known logs will grow and change over time, and an outdated Electron/Brightray may result in certificates accepted by Chrome being rejected.

It's likely that your application has not been updated within 10 weeks, which is what Chromium defines as 'outdated', and as a result, certificates accepted by Chrome are being rejected by your app.

**Comment by sleevi** [comment]
The broader issue is captured in https://bugs.chromium.org/p/chromium/issues/detail?id=664177

**Comment by kevinsawicki** [comment]
> The broader issue is captured in https://bugs.chromium.org/p/chromium/issues/detail?id=664177


There is a pull request up to pull in the patch for https://codereview.chromium.org/2495583002 at https://github.com/electron/libchromiumcontent/pull/248
