### ISSUE TITLE
Resetzoom, zoomin and zoomout is not appeared

### ISSUE THREAD

**Issue by mimorisuzuko** [electron/electron#7223]
* Electron version: v1.3.1
* Operating system: OS X El Capitan v10.11.5

I read [here](https://github.com/electron/electron/blob/master/docs/api/menu.md) and implemented it. However, `resetzoom`, `zoomin` and `zoomout` is blank on `View`. What's happened?

![2016-09-17 0 34 52](https://cloud.githubusercontent.com/assets/12094729/18591753/e2b7bdb6-7c6e-11e6-8c67-7d5096024027.png)
`

**Comment by mimorisuzuko** [comment]
On `View`, the code is as below.

```javascript
	{
		label: 'View',
		submenu: [
			{
				label: 'Reload',
				accelerator: 'CmdOrCtrl+R',
				click(item, focusedWindow) {
					if (focusedWindow) { focusedWindow.reload(); }
				}
			},
			{
				label: 'Toggle Developer Tools',
				accelerator: process.platform === 'darwin' ? 'Alt+Command+I' : 'Ctrl+Shift+I',
				click(item, focusedWindow) {
					if (focusedWindow) { focusedWindow.webContents.toggleDevTools(); }
				}
			},
			{
				type: 'separator'
			},
			{
				role: 'resetzoom'
			},
			{
				role: 'zoomin'
			},
			{
				role: 'zoomout'
			},
			{
				type: 'separator'
			},
			{
				role: 'togglefullscreen'
			}
		]
	}

**Comment by kevinsawicki** [comment]
> Electron version: v1.3.1

Those roles were added in Electron 1.3.3, if you upgrade to that version or a later one you should see the correct labels for those roles.
