### ISSUE TITLE
Ability to customise webPreferences / security settings for windows opened with window.open

### ISSUE THREAD

**Issue by mz2** [electron/electron#7224]
I am hitting a nasty corner-case of Electron / Chromium security behaviour with HTTP / HTTPS and the ember-inspector being loaded in an Electron app, when attempting to use the CloudKit JS library to complete authentication with Apple's CloudKit service (a process that is unfortunately a complete black box for a developer – you simply place a login button on the page and Apple's thoroughly obfuscated JavaScript library takes care of the rest by opening a new dialog where the authentication process is completed). Namely I am seeing the following error message specifically in the context of an authentication attempt in an Electron app that loads the Ember Inspector:

```
VM107 content-script.js:85 Mixed Content: The page at 'https://idmsa.apple.com/IDMSWebAuth/auth?oauth_token=OATTKNc85079fe-1899-49…3a8f1c0fecb70af11a9f7112362317858519a9e5d68dbd61eb32db48ec741df09b74585a47' was loaded over HTTPS, but requested an insecure script 'chrome-extension://ember-inspector/scripts/in-page-script.js'. This request has been blocked; the content must be served over HTTPS.(anonymous function) @ VM107 content-script.js:85(anonymous function) @ VM107 content-script.js:110runContentScript @ /Users/mz2/Projects/Manuscripts/Manuscripts-io/node_modules/electron-prebuilt/dist/Electron.app/Con…:23g @ events.js:286emitNone @ events.js:86emit @ events.js:185
```

Issue appears to be that the ember-inspector extension loads a script that is not treated as having been securely loaded. Is there a way to either have an extension loaded script be treated as such, or to globally alter the security settings for dialogs opened with `window.open`?

**Comment by zcbenz** [comment]
You can hook to the `new-window` event of `WebContents` to create any window you want.

**Comment by mz2** [comment]
@zcbenz could you elaborate, please, if only to point me at the most relevant documentation? What I believe I am having an issue with is the dialog not being able to talk back with the main window. Is that something that is specifically disabled in Electron?
