### ISSUE TITLE
What are the plans for window.opener full support in Electron ?

### ISSUE THREAD

**Issue by hivaga** [electron/electron#7228]
* Electron version: 1.3.5
* Operating system: Win10

Hi, I am working on a multi-windows application and I need to share a object instances from the main application process with the other windows of the application. Currently in browser you can reference window.opener to achieve this. In browser window.opener (in child window) will give you the instance of the Window object form which window.open(myURL) was called. 
In Electron when I open window via (window.open(myURL)) window.opener is replaced with BrowserWindowProxy (Electron API) which does not expose the same window (Window object instance) from which the (window.open(myURL)) was called. Is there a way to access window.opener the same way it works in Browser. I need some hint do you plan to support this in the future and when ?

Using remote.sharedObject (Electron API) is not an option since it only serialize/deserialize data and can be used for passing data from one window to others but does not give access to same object instances across windows.

**Comment by kevinsawicki** [comment]
> In Electron when I open window via (window.open(myURL)) window.opener is replaced with BrowserWindowProxy (Electron API) which does not expose the same window (Window object instance) from which the (window.open(myURL)) was called

What APIs are missing on `BrowserWindowProxy` that your app needs?

**Comment by hivaga** [comment]
It is not about the concrete Window API it is more about the way to share same object instance (or shared memory access on a low level) between different Electron window. For example I have a AssetsLoaderService instance in MainProcess (Main Window) and it has already loaded a bunch of assets and I want to have access to it in other window instances so that I don't need to load the assets again. Is there a way to share same object instance from Main Window to others ?

**Comment by zcbenz** [comment]
We will enable it after adding an option to disable node integration in renderer process, and #6919 is an ongoing effort.

**Comment by jhgg** [comment]
Just out of curiosity - if you have time to reply - what is the reason for requiring the node integration from being disabled for native window.opener?

**Comment by zcbenz** [comment]
@hjgg It is not safe to have multiple Node.js instances in one process, while native window.opener needs to run multiple pages in one renderer process.

This will change when Node.js has support for multi-thread.

**Comment by Gvozd** [comment]
To correct window.opener, and work facebook(and others) logins

You need use `webPreferences.nativeWindowOpen=true`, and set same `webPreferences.affinity` for mainWindow, and opened windows(hook on `mainWindow.webContents.on('new-window')`)
https://gist.github.com/Gvozd/2cec0c8c510a707854e439fb15c561b0
