### ISSUE TITLE
Electron package update to version 1.4.0 fails on ARM

### ISSUE THREAD

**Issue by eamiro** [electron/electron#7232]
* Electron version: 1.4.0
* Operating system: Raspbian Jessie

Got an error when trying to update electron from version 1.3.5 to 1.4.0 on Raspberry Pi

**Comment by enlight** [comment]
And the error was?

**Comment by eamiro** [comment]
It was ELIFECYCLE error
I updated node to v6.6 but I got the same error

**Comment by eamiro** [comment]
The installation failed at: postinstall install.js

**Comment by enlight** [comment]
Please provide the full error output generated by NPM.

**Comment by kevinsawicki** [comment]
Tried to reproduce this on my armv7l acer chromebook but 1.4 installed and launched successfully 😕

**Comment by cjdg** [comment]
Which raspberry pi are you using?

**Comment by eamiro** [comment]
I'm using Raspberry pi 2 model B

**Comment by eamiro** [comment]
The update to version 1.4.1 was successful!
