### ISSUE TITLE
Electron 1.4.0 fails to load a page that worked on 1.3.6

### ISSUE THREAD

**Issue by scytalezero** [electron/electron#7235]
* Electron version: 1.4.0
* Operating system: Windows x64

I use NightmareJS to scrape several websites. The following login page displays fine and returns the page title when using Electron 1.3.6. If you update to 1.4.0, Electron will just show a blank white window. The promise does return an error:

```javascript
const nightmare = require("nightmare")({ show: true, width: 1000 })
nightmare
  .goto("https://secure03a.chase.com/web/auth/dashboard")
  .title()
  .then(result => {
    console.log(result)
  })
  .catch(err => console.error(err))
```

Here is the error from the console:

```
{ message: 'navigation error',
  code: -501,
  details: 'ERR_INSECURE_RESPONSE',
  url: 'https://secure03a.chase.com/web/auth/dashboard' }
```

Is there any way to override this behavior? The page works fine in Chrome browser.

**Comment by deepak1556** [comment]
Merging to https://github.com/electron/electron/issues/7221

You can temporarily workaround with commandline switch `ignore-certificate-errors`
