### ISSUE TITLE
Crash Report not sending?

### ISSUE THREAD

**Issue by MTRNord** [electron/electron#7237]
* Electron version: 1.4.0
* Operating system: Windows 7 64bit (using exe packaged by electron-builder for "win32 x64")

If the Crash reporter wants to send something it doesn't really send anything. In the Server logs nothing is there. And no crash report seems to be triggerd if I check last report. 
I call Crashreporter.start on following code:

```
  autoUpdater.on("error", (err) => {
    crashInit()
    tray.displayBalloon({
      title: 'Autoupdater',
      content: 'Ein Fehler ist aufgetreten!'
    })
  })
```

CrashInit is defined like that:
```

function crashInit() {
  crashReporter.start({
    productName: 'Lornsenschule Vertretungsplan Desktop',
    companyName: 'Nordgedanken.de',
    submitURL: 'http://ls-crash-report-server.herokuapp.com',
    autoSubmit: true
  })
  console.log(crashReporter.getLastCrashReport());
}
```
And yes I reuired all libaries  (even I haven't included the imports in these code snippets).
Also the tray notification shows up so It should be triggered.

Any Ideas what goes wrong?

**Comment by MTRNord** [comment]
By the way: Server side is my fork (optimized for Heroku) https://github.com/MTRNord/electron-crash-report-server

**Comment by kevinsawicki** [comment]
Are you calling `process.crash()` to test it? Did this work for you in older Electron versions but not in the 1.4.0 release?

**Comment by MTRNord** [comment]
with that it does work

**Comment by MTRNord** [comment]
Problem is not fixed by process.crash() on win7. Only on win 10 that works.

**Comment by MTRNord** [comment]
On win7 64bit actual master works

**Comment by symbyte** [comment]
I think I'm noticing something similar on macOS. I'm trying to set up crash reporting for the first time for our app so at first I thought I was doing something wrong, but after verifying the setup steps crash reports still don't seem to be sending. 

I have this in my main process : 

```javascript
const crashReporter = window.require('electron').crashReporter;
crashReporter.start({
  companyName: 'MyCompany',
  submitURL: 'localhost:1127',
  autoSubmit: true
});
console.log(crashReporter.getLastCrashReport());
```

as well as in my application code that runs in the render process. No matter how many times I call `process.crash()` the call to `crashReporter.getLastCrashReport())` always returns `null`.

 Is there something I am missing here?

**Comment by symbyte** [comment]
I tried the above on both version `1.3.7` and `1.4.2` of Electron.

**Comment by kevinsawicki** [comment]
>  submitURL: 'localhost:1127'

@symbyte have you tried with `http://localhost:1127` instead?

**Comment by kevinsawicki** [comment]
> On win7 64bit actual master works

@MTRNord Do you mean Electron master works for you on win7? So are you still seeing failures on the latest Electron release? 1.4.3

**Comment by MTRNord** [comment]
@kevinsawicki using the electron master the crashReporter does send on win7 x64. It seems like it is fixed in the new master. But I am not 100% sure if that is true to every device (I only got my own device so I can't really mass test it ;)

**Comment by kevinsawicki** [comment]
> It seems like it is fixed in the new master.

Thanks, going to close this out then for now, please report back if you see future issues.
