### ISSUE TITLE
Is building Node with `v8_inspector: false` intentional?

### ISSUE THREAD

**Issue by zertosh** [electron/electron#7240]
Node is currently built with `v8_inspector` disabled (see https://github.com/electron/electron/blob/v1.4.0/common.gypi#L46). Is this intentional? When that was originally introduced in #6559, the commit message read "Make use of some new Node config flags" (39e39ae91340fd5db7a14d5d14c2574ee214b268) - with no other context. So maybe it was an oversight and it can be enabled?

Not sure how you'd use this exactly to debug the main process, but it would most definitely be very useful for debugging forked child processes. For example, right now, if you attempt:

```js
child_process.fork('path/to/file.js', [], {
  execArgv: ['--inspect'],
});
```

You're met with:

```
Inspector support is not available with this Node.js build
/path/to/Electron Helper: bad option: --inspect
```

However, this works in Node 6.3.0+ (confirmed on Node 6.3.0 and 6.6.0 that `child_process.fork` can be debugged with `--inspect` - just have to capture `stderr` to grab the chrome-devtools url).

**Comment by citycide** [comment]
I've been hoping since the Node 6.3.0 update that this would make other forms of debugging & inspection obsolete, would love to hear the plans surrounding it.

**Comment by paulcbetts** [comment]
I _think_ this is intentional since Chromium already has the V8 debugger built-in (i.e. as part of DevTools), so enabling this would get us two separate copies of DevTools.

**Comment by zertosh** [comment]
@paulcbetts The debugger you're referring to is on the renderer process. This debugger would be on the node side. In theory, it should make debugging the main process a lot less [painful](https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process.md). And allow for debugging forked processes.

**Comment by paulcbetts** [comment]
@zertosh Sure, but Chrome Devtools can connect to remote processes, including the main process

**Comment by zcbenz** [comment]
Yeah it is intended. Supporting `--inspect` is tracked at #6634.
