### ISSUE TITLE
Electron file exists

### ISSUE THREAD

**Issue by ajaxboy** [electron/electron#7242]
* Electron version: 1.3.5
* Operating system: MACOSX

I've spent a good part of the day trying to figure out how to do a simple check if a file exists, I have tried literally anything I found related to the topic,  fs, path (possibly not included correctly), etc.  nothing seems to be working,  is there a straight forward solution for this?  Please note that I have been using electron only for a few days so I am not electron expert.  I am surprised I haven't found a clear example,  any help would be great,  thanks!.

**Comment by MarshallOfSound** [comment]
@ajaxboy Please direct questions / code help request to the community discussion forums or to slack.  The github issues section is intended to be only used for bugs with Electron.

I'll answer your question anyway though 👍 

To check if a file exists you want to use [`fs.stat`](https://nodejs.org/api/fs.html#fs_fs_stat_path_callback)

Sample code would be

```js
const pathToFile = '/path/to/my/file';
fs.stat((err) => {
  if (err) {
    // File does not exist
  } else {
    // File does exist
  }
});
```

And before anyone else says "you should use fs.exists", that method is deprecated so using it is a super bad idea.
