### ISSUE TITLE
modal BrowserWindow cause block

### ISSUE THREAD

**Issue by h421933728** [electron/electron#7243]
* Electron version: v1.2.5
* Operating system: OS 10.11.5

there is a problem in my app:
         A is a normal BrowserWindow, in A's  index.html  there is a `<input type="file"/>`,  A has a child BrowserWindow B,  and B is a modal BrowserWindow,  when I close B, then  I click A's  `<input type="file"/>` ,  app is block

 you can download my demo here->https://github.com/h421933728/electron-demo.git
 you can start by `electron .`

![test2](https://cloud.githubusercontent.com/assets/8063451/18613640/4cfb7224-7db1-11e6-8b31-8d7fb1618437.gif)

**Comment by kevinsawicki** [comment]
Can you check if you see the same behavior in `1.4.0`?

**Comment by h421933728** [comment]
when I run in electron 1.4.0, that's ok ,  thanks !
