### ISSUE TITLE
Spellchecker provider character sets & multiple spell check languages

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#7244]
* Electron version: 1.4.0
* Operating system: osx

I've noticed that when setting the spellcheck provider for a certain language it doesn't run spell checking over character sets not used in that language (e.g. american characters vs cyrillics). For example if you set..

```js
webFrame.setSpellCheckProvider('en-US', true, {
  spellCheck (text) {
    console.log(text)
    return false
  }
})
```

Then if you start typing in a text field you'll find the following...
* Type `english` you see `english`
* Type `français` you see `français`
* Type `русский` nothing gets logged out.

Swap the provider language to `ru` you'll see the results in reverse.

Taking this into account is it possible to...

1.) Run the spellchecker over different character sets? (I'm guessing the answer to this is going to be no as I can't imagine chrome supports it...)
2.) Provide spellchecking for multiple languages at once? I noticed that if you run the `setSpellCheckProvider` multiple times the last one wins
3.) Give any information on the character sets used for the different languages so I can build a matrix of compatible languages?

Thanks for your help :-)

**Comment by enlight** [comment]
I'm not familiar with the spellchecker implementation so I can't answer your questions, but I can point you at https://github.com/paulcbetts/electron-spellchecker which seems to support switching between multiple languages on the fly.

**Comment by Thomas101** [comment]
Thanks @enlight. I've had a look at that lib and it works around this issue by checking if there's been a [number of unchecked words by the spellchecker](https://github.com/paulcbetts/electron-spellchecker/blob/7bda47a5395f599ebcb418a1f1348e9e97f16f68/src/spell-check-handler.js#L183), then uses that to infer if it should try to re-detect language and auto change the language from there.

I was looking at getting more than one language spell checking at once though. Some users have been asking for suggestions in multiple languages as they quite often type bilingually

**Comment by MarshallOfSound** [comment]
@Thomas101 I've never tested this, but I can't imagine that Chrome or even Microsoft Words does multilingual spell checking.  For one main reason I can think of.

If a word is valid in one language and invalid in another.  Is it an error?  The spell checker would have to contextually understand what language the block of test the word is in is written in.  And even then, quoting a different language would result in errors.

Spell checking multiple languages at the same time will either result in an increase in false positives or ignoring real spelling mistakes.  I don't see how this could possible be implementing in a consistent and precise manner 😢 

> Run the spellchecker over different character sets?

This however definitely seems to be some form of a bug 😆

**Comment by Thomas101** [comment]
I agree it's a real edge case, but one that I think still has some validity. The approach I took was to setup a primary and secondary language. A correct spelling in either language falls out to a correct language and corrections can be provided for either.

After digging through the source it looks like it falls through to `spellcheck_worditerator.cc` which calls `uscript_getCode` with the language code. This is translated into a character subset which is used for optimising the detection. There's a list of locales to language codes [here](https://opensource.apple.com/source/WebCore/WebCore-7601.3.8/platform/text/LocaleToScriptMappingDefault.cpp) so I can probably build a matrix of compatible languages using that :)

**Comment by zcbenz** [comment]
The design of spellchecker API is from Chromium and currently it can only check spell for exactly only one language. Making it support multiple languages is nice but we don't have someone familiar with spellchecking to do it, and we don't have resources for that neither, so I'm closing this as won't fix.

> After digging through the source it looks like it falls through to spellcheck_worditerator.cc which calls uscript_getCode with the language code.

Yeah it is the code for iterating words, and you can start hacking from it.

**Comment by Thomas101** [comment]
Okay thanks for clarifying that :)

**Comment by lorenzhs** [comment]
I do understand that it's not a trivial issue and that you may not have the resources to implement it, but Chromium implements multi-language spell check: https://codereview.chromium.org/1258673003/, which could be a helpful pointer if somebody else wanted to implement this and needed a place to get started.

@MarshallOfSound As someone who regularly uses English and German, it really is very useful. The false positives this introduces aren't really a problem because a spell checker is always imperfect, and it still catches the majority of errors. And it's not that small of an edge case, either, a great many people use e.g. both their native language and English on the internet regularly, and would benefit from this.
