### ISSUE TITLE
Excessive ERR_CONTENT_DECODING_FAILED and ERR_CACHE_READ_FAILURE's

### ISSUE THREAD

**Issue by kaansoral** [electron/electron#7246]
* Electron version: 1.3.3 and 1.4.0
* Operating system: OSX 10.11.6
* Reproduction: Run Multiple "electron ."'s for the same project, CMD+R them one by one until the cache becomes corrupt
* Site: http://adventure.land loaded by `.loadURL`

I was experiencing a similar ERR_CACHE_READ_FAILURE issue on Chrome too, on the same webpage, loaded regularly, again, when it's accessed repeatedly (there is a CODE feature, where a page is inserted with an iframe into the existing page, sources are shared) - this started happening some weeks ago, and it was a repeating nightmare, yet, after recently updating Chrome to the latest version, I can't reproduce it on Chrome anymore

I wonder whether this was a Chromium issue that got fixed on Chrome and still lives on Electron

The alternative is the issue being a network issue or hardware issue on my part, I like to eliminate a hardware issue, I disabled Cloudflare before switching to Electron 1.4.0 - thinking it could be Cloudflare, but it wasn't, the remaining network is served from App Engine

<img width="1333" alt="screen shot 2016-09-18 at 22 56 18" src="https://cloud.githubusercontent.com/assets/170243/18618940/4fed4e88-7df9-11e6-98b8-06d79415bae2.png">

**Comment by kevinsawicki** [comment]
> this started happening some weeks ago, and it was a repeating nightmare, yet, after recently updating Chrome to the latest version, I can't reproduce it on Chrome anymore

What Chrome version are you seeing it work in?

**Comment by kaansoral** [comment]
My current chrome version is `53.0.2785.116 (64-bit)` - no issues yet

I tested various other things after reporting the issue, tested HTTPS, tested toggling Cloudflare, in all of those tests, the issue was easy to reproduce on Electron 1.4.0

**Comment by zcbenz** [comment]
You should not run multiple instances of the same app at the same time, for certain operations global locks are applied. In your case the cache database is locked by one instance and all other instances will fail to read cache.

**Comment by kaansoral** [comment]
Thanks for the info

In that case, what is the intended way of creating multiple instances of the same app?

I guess it could be adding a way/menu-button to pop up another window from the first Electron instance + As a suggestion, if it's unsafe to run multiple Electron's in parallel, it would be nice if the CLI command warned

**Comment by zcbenz** [comment]
There is no safe way to create multiple instances since Chromium doesn't support it.

> I guess it could be adding a way/menu-button to pop up another window from the first Electron instance

You can use the `app.makeSingleInstance` API.
