### ISSUE TITLE
Mac OSX auto updater doesn't work with the latest update 

### ISSUE THREAD

**Issue by paul321** [electron/electron#7251]
* Electron version: 12.6 - 1.3.5
* Operating system: OSX

Auto updater fails to install app from the zip file downloaded from the server, this was working fine. we were on Electron 1.2.6 for 2 months and when latest El Capitan update was installed, Electron couldn't install the updates anymore

**Comment by zcbenz** [comment]
Please keep the discussion in  #6345.
