### ISSUE TITLE
v1.4.0 fs.accessSync throw ENOENT testing asar file

### ISSUE THREAD

**Issue by micheletedeschi** [electron/electron#7254]
* Electron version: v1.4.0
* Operating system: macOS Sierra 10.12

I've update to the last Electron version (actually 1.4.0) and fs.acceccSync doesn't work anymore.

executing this code:
```
const path = '/path/to/file.asar';
fs.accessSync(path, fs.constants.F_OK);
```

throw:
```
ENOENT,  not found in /path/to/file.asar
       at notFoundError (ELECTRON_ASAR.js:110:19)
       at Object.fs.accessSync (ELECTRON_ASAR.js:432:9)
```

If i check file inside or outside asar file work correctly.

With Electron v.1.3.4 works fine.

**Comment by kevinsawicki** [comment]
> With Electron v.1.3.4 works fine.

I'm seeing the same behavior on 1.3.4 as 1.4.0, if you `fs.accessSync` on an `.asar` file directly, it throws a `ENOENT` error.

<img width="1009" alt="screen shot 2016-09-19 at 10 37 58 am" src="https://cloud.githubusercontent.com/assets/671378/18642387/497474b2-7e55-11e6-886d-da698c8beec4.png">

Would you be able to provide the `.asar` file you are seeing work in 1.3.4 but fail in 1.4.0? Thanks.

**Comment by micheletedeschi** [comment]
I use the cited code for several months updating the same node_modules at every Electron release and fs.accessSync works fine, after updating to v1.4.0 i've seen a change.

Reverting the code before updating to v1.4.0 with clean node_modules, fs.accessSync throw ENOENT as you tested.

I'm not able to reproduce the problem, I think that the problem is related to a combination of the Electron version and some dependency.

I've resolved changing the method I test the file.

**Comment by kevinsawicki** [comment]
Okay, thanks, closing this out.
