### ISSUE TITLE
Notification sounds linux

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#7258]
* Electron version: 1.4.0
* Operating system: Ubuntu 16.04, Xubuntu 16.04, Ubuntu 15.04

I just wanted to check the support status of Notification sounds on linux. I've tried...
```js
new Notification('test1')
new Notification('test', { silent: false})
new Notification('test1', { sound: '/path/to/sound.mp3' })
```
...but nothing seems to play a notification sound. Is there something I'm missing or are notification sounds unsupported on linux?

Thanks

**Comment by zcbenz** [comment]
Electron uses system notification so whether it has a sound depends on your system configuration.

As for `Notification.sound`, it is not supported by any browser for now.

**Comment by theuniverse** [comment]
@zcbenz Do you have any idea if this is supported now?
