### ISSUE TITLE
BrowserWindow.showInactive() has no effect on Linux

### ISSUE THREAD

**Issue by naure** [electron/electron#7259]
* Electron version: 1.3.4
* Operating system: Ubuntu 16.04
* Works on Mac, not on Ubuntu

Run Electron with any app or none at all.

Open the dev tools as a separate window. 

This does show the window and grabs the focus:

    require("electron").remote.getCurrentWindow().show()

But this has no effect at all:

    require("electron").remote.getCurrentWindow().showInactive()

Expected: the window shows up, unfocused.

Note: the same happens without the dev tools, calling showInactive() from the app's code.

**Comment by zcbenz** [comment]
`showInactive` only makes a hidden window show again, it doesn't change the z-order of windows.

**Comment by parro-it** [comment]
@zcbenz, it does on macOS (change the zOrder), but not on Linux

**Comment by naure** [comment]
@parro-it 

For the record, I've worked around this issue with the following:

                // Set "always on top" and then normal again
                // That brings the window on top reliably
                var wasOnTop = win.isAlwaysOnTop()
                win.setAlwaysOnTop(true)
                if(!wasOnTop) {
                    win.setAlwaysOnTop(false)
                }
                // Works only on mac
                // win.showInactive()

**Comment by parro-it** [comment]
@naure thank you so much, I'll using that. I'm actually using 

```js
if (is.linux()) {
    win.focus();
    remote.getCurrentWindow().focus();
 } else {
    win.showInactive();
}
```

but it is suboptimal because current page elements loose their focus....

**Comment by riccitensor** [comment]
Thank you @naure. Why is this not yet solved on Linux?
