### ISSUE TITLE
Text boxes inside <webview> gives an empty OSX services menu

### ISSUE THREAD

**Issue by sltam** [electron/electron#7260]
- Electron version: 1.4.0
- Operating system: OS X 10.11.6

Summary: Text boxes inside <webview> gives an empty OSX services menu, unless a text box outside <webview> triggered it once.

frame.html:

```
<hr><hr><hr>
Outside WebView: <input value="text"></input>
<webview id="webview" src="text.html"></webview>
```

text.html:

```
Inside WebView: <input value="text"></input>
```

main.js:

```
const { BrowserWindow, app } = require('electron')
app.on('ready', () => new BrowserWindow().loadURL(`file://${__dirname}/frame.html`))
```

STEPS:
1. Select the lower `text` and go to `Electron` -> `Services`. Got this:
![image](https://cloud.githubusercontent.com/assets/51615/18651346/9428d1c2-7e7f-11e6-8ad9-1176e3191921.png)
This is wrong.
2. Select the upper `text` and go to `Electron` -> `Services`. Got the correct menu.
![image](https://cloud.githubusercontent.com/assets/51615/18651458/2c760d64-7e80-11e6-8363-c8904761dd21.png)
3. Select the lower `text` and go to `Electron` -> `Services`. Got the same correct menu.

**Comment by sofianguy** [comment]
Thanks for contributing!

This is an old version that we are no longer releasing bug fixes for. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.
