### ISSUE TITLE
kq_init warning when launching electron

### ISSUE THREAD

**Issue by EllDoubleYew** [electron/electron#7261]
* Electron version: 1.2.5
* Operating system: macOS 10.12 GM, Xcode 7.3

Whenever I launch my electron app I get the following printed in my terminal.

```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
```

I am on the GM build of Sierra and I am not on the new Xcode beta. I am also using iTerm but I dont think that is the issue.

EDIT: After some further digging this is a [known issue related to libevent](https://github.com/libevent/libevent/issues/376). Closing the issue here.

**Comment by shinriyo** [comment]
Me too. what is the error is??
