### ISSUE TITLE
Strange argument on first launch

### ISSUE THREAD

**Issue by rgbkrk** [electron/electron#7266]
* Electron version: 1.1.3
* Operating system: OS X

This has really been a head scratcher. Only on first launch, with a packaged app, launched from Finder do we see this. Our app gets a strange arg passed to it on launch. The first is what we expect, the second less so:

```
[ '/Users/kylek/Downloads/nteract-darwin-x64/nteract.app/Contents/MacOS/nteract',
  '-psn_0_8046508' ]
```

https://github.com/nteract/nteract/issues/805#issuecomment-248219515

What is that?

**Comment by kevinsawicki** [comment]
This is added by the operating system and not Electron.

You might want to check out http://apple.stackexchange.com/questions/207895/app-gets-in-commandline-parameter-psn-0-nnnnnn-why for more details.

**Comment by rgbkrk** [comment]
Thanks @kevinsawicki! Yeah, I filtered that out from our args after reporting this. Sorry for the noise.
