### ISSUE TITLE
Error when install Electron

### ISSUE THREAD

**Issue by aishahismail** [electron/electron#7267]
* Electron version: v1.4.0
* Operating system: Windows 7 (64bit)

When I run this `npm install -g electron` in command line. It returns error with:

![image](https://cloud.githubusercontent.com/assets/14171601/18660703/85731de8-7f44-11e6-94c2-336e2946b7a4.png)

Thanks for help.

**Comment by MarshallOfSound** [comment]
This is a network issue on your end.  Check your internet connection and maybe try a proxy if it is required to access S3.
