### ISSUE TITLE
Persist cookies after app restart for browser window

### ISSUE THREAD

**Issue by nathanbertram** [electron/electron#7268]
- Electron version: 1.2.6 
- Operating system: Osx 10.11.6

I've got a simple app that loads a url and what I'm trying to do is have the cookies from the url being loaded persisted.  Is there something I'm missing where `partition: "persist:main"` wouldn't achieve this?

`main.js`

```
mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    minHeight: 600,
    minWidth: 800,
    transparent: false,
    frame: true,
    title: app.getName(),
    icon: __dirname + '/images/app-icon.png',
    webPreferences: {
        nodeIntegration: false,
        partition: "persist:main"
    }
})

mainWindow.loadURL(process.env.APP_DOMAIN)

```

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem? From your code the cookies should have been persisted.

**Comment by nathanbertram** [comment]
@zcbenz sure will do -- so what I'm seeing is if I close the window and re-open it the session persists correctly. However when I quit the app (cmd+q) and re-open it the session is lost. Should the cookies be persisted in the case or do I need to build some other way to restore the cookies after app.quit()?

**Comment by zcbenz** [comment]
The cookies are persisted by default, otherwise it would be a bug.

**Comment by kevinsawicki** [comment]
Closing out until more information is provided.

@nathanbertram please comment if you are still seeing this on the latest Electron release and we can reopen.

**Comment by fer-fullstackdev** [comment]
I create several webview and loads urls in the app. I want to restore session cookies when restarting the app and webview, so that the already logged in status can be kept in the webview. Anyone knows how to do this?

**Comment by Atlas7005** [comment]
> I create several webview and loads urls in the app. I want to restore session cookies when restarting the app and webview, so that the already logged in status can be kept in the webview. Anyone knows how to do this?

Having the same predicament.
