### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by yangxiaomin08** [electron/electron#7269]
* Electron version: 1.1.0
* Operating system:ubuntu 15.10

../.node-gyp/iojs-1.1.0/deps/v8/include/v8.h:227:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);

**Comment by zcbenz** [comment]
If you see it from the log of npm you can ignore it.
