### ISSUE TITLE
Problems with showItemInFolder() and multiple Windows users signed in

### ISSUE THREAD

**Issue by MarioHofer** [electron/electron#7271]
My Electron app shows files inside their enclosing folder using the standard command shell.showItemInFolder(fullPath). Works.

Now when two Windows users are signed in and they both use the app, the file is always shown on the Windows desktop of the user opened the app first.

In real life, it looks as if the function is broken, but actually the Windows Explorer is simply opened in the other Windows user's session in the background.
- Electron version: v1.0.1
- Operating system: Windows 7

**Comment by enlight** [comment]
I asked @MarioHofer to check if this also occurs in Chrome using the `Open Containing Folder` button in the Download List window/popup (which I suspect uses the same Windows API as Electron), but apparently Chrome doesn't have this problem.

**Comment by zcbenz** [comment]
That's weird, the code on opening a folder in Electron should be the same with Chrome.

**Comment by zcbenz** [comment]
I'm closing this as won't fix, if a program run under one user can affect the environment of another user, it is absolutely an issues of Windows itself.
