### ISSUE TITLE
autoUpdater: 'update-available' do not fires immedately, it takes like 5 mins 

### ISSUE THREAD

**Issue by wangxiexe** [electron/electron#7274]
* Electron version:1.4.0
* Operating system: Windows

I am creating an app with electron and electron-builder ,

everytime we update the seed server ( I am using simple an https server as the update seed server )  and put all the artifacts from the electron-builder output dir into the web server root dir

MicloudPC_Setup.exe
MiCloudPC-0.0.258-full.nupkg
RELEASES

and call autoUpdater like: 
autoUpdater.checkForUpdates()

it take quite a while (like 5 mins) for the 'update-available' event to be fired

it seems the updater only need to compare RELEASES and it then can know if there is update or not. 
why it take so long ? It seems the nupkg is getting downloaded and then the 'update-available' got fired.

btw, if there is no update, the 'update-not-available' event just fires immediately.

Any suggestions ? thanks a lot!

**Comment by kevinsawicki** [comment]
This is most likely because `update-available` fires after the update is downloaded which can take some time.

Merging this into https://github.com/electron/electron/issues/4587
