### ISSUE TITLE
Spell checking marks not cleared after replacing word

### ISSUE THREAD

**Issue by giancarlokc** [electron/electron#7275]
Hello, I'm working on a Electron app using a Webview. I need a spellchecker inside the Webview, so I'm running a script inside the Webview (Using the function webFrame.setSpellCheckProvider(language, autoCorrectWord, provider)). I also implemented a context menu that shows suggestions to replace the misspelled words.

If I write words that are not on the dictionary, they appear as misspelled (as expected). However, when I use the context menu to replace one misspelled word, other words that were also misspelled stop having the red underline (event thought they are still misspelled).

One other thing that I noticed is that when you paste a text into the Webview, not all misspelled words get the red underline, only the first one. But I added a log on the spellcheck provider, and the function spellCheck() is being called for each word, the only problem is that the red line does not show.
- Electron version: 1.3.3
- Operating system: Linux Mint

**Comment by vadim-ch** [comment]
:+1: have the same problem. Any suggestions?

**Comment by eddievagabond** [comment]
+1 My issue occurs only within a Draftjs rich text editor implementation. If I am using a regular textarea or content editable, spellcheck works as expected.

**Comment by vadim-ch** [comment]
@eddievagabond, i also have problem with Draft.js, but in tag "input" and "textarea" also reproduced.

**Comment by codebytere** [comment]
This should no longer be an issue now that Electron ships with Chromium's native spellchecker.
