### ISSUE TITLE
window unload event does not fire

### ISSUE THREAD

**Issue by maxbrunsfeld** [electron/electron#7278]
* Electron version: v1.3.6 and v1.4.0
* Operating system: Mac OS 10.11.6

Repro:

* Add the following code to `renderer.js` in `electron-quick-start`:

```js
window.addEventListener('beforeunload', function () {
  console.log('beforeunload');
})

window.addEventListener('unload', function () {
  console.log('unload');
})
```

* Check the `preserve log` box in the dev tools
* Reload the window with `command-r`
* See "beforeunload" in the console, but not "unload"

In Chrome 53, I can add the same event listeners in the dev tools, reload the page and see both "beforeunload" and "unload" in the console.

**Comment by bengotow** [comment]
Hey! Can you try saying `window.onbeforeunload = function() {` and see if that syntax works? We were having trouble with this in N1 too and found that only the raw assignment version was working...

**Comment by maxbrunsfeld** [comment]
We used to do this in Atom too. But in Electron >= 1.3, the `beforeunload` event appears to work. This issue is about the *`unload`* event though, not the `beforeunload` event. There appears to be a regression where the `unload` event does not even fire.

**Comment by zcbenz** [comment]
In Chrome the `unload` event is not reliable, the `unload` handler is run after the new page gets loaded, so you can not see the console output from it, and sometimes it just got optimized away, this was also why we used to use `onbeforeunload` in Atom. You can find more about it in some old issues: https://github.com/atom/atom/issues/3144 https://github.com/atom/atom/pull/3223.

If you want to have an event that fires reliable on unload, apart from `beforeunload` you can also use the `exit` event of `process`, which is guaranteed to fire before JavaScript context is destroyed, and we use it to cleanup resources internally in Electron.

**Comment by maxbrunsfeld** [comment]
@zcbenz Yeah, I think the `beforeunload` even will work fine for us. Just so I understand though: is it expected that the `unload` event does not fire at *all*? From what I'm seeing, it's not just firing too late; it's not firing, which is different than what I see in Chrome.

**Comment by zcbenz** [comment]
@maxbrunsfeld Hmm it should still fire for most cases, but you need to notice that the console output from it will not be printed to console of devtools, because it is fired after the new page gets loaded.

**Comment by bengotow** [comment]
Hey folks—just wanted to bump this. If there's a possibility that `onunload` is unreliable or doesn't fire in certain scenarios, I think we should remove it entirely so this bug doesn't get re-opened in a few months. Maybe `renderer/init.js` could override the `window.onunload` setter and throw an exception?

**Comment by maxbrunsfeld** [comment]
> but you need to notice that the console output from it will not be printed to console of devtools, because it is fired after the new page gets loaded.

Yeah, this is happening even if you enable `Preserve Log` in the console, so it's not just that it's firing later. I'm definitely seeing different behavior than Chrome in this regard. But again, it's not affecting Atom anymore.
