### ISSUE TITLE
Statically linked CRT interferes with Breakpad

### ISSUE THREAD

**Issue by miniak** [electron/electron#7281]
- Electron version: 1.4.0
- Operating system: Windows

Breakpad calls these API to intercept errors/exceptions in the app:
- `SetUnhandledExceptionFilter`
- `_set_invalid_parameter_handler`
- `_set_purecall_handler`

Due to the fact that the Visual C++ runtime is now statically linked, the last two don't apply to all Electron DLLs, as each of them has its own copy of the CRT. This can negatively impact the crash reporter.

**Comment by enlight** [comment]
#9443 went into the 1.7.4 beta, so can we close this issue now?
