### ISSUE TITLE
Not able to load custom pepper plugin

### ISSUE THREAD

**Issue by 92anurag** [electron/electron#7288]
* Electron version: 1.4.0
* Operating system: OSX 10.11.6 
chrome 53.0.2785.113
pepper version 49

I have generated .pexe from  one of sample pepper project available with pepper sdk. When I run navigator.plugins on console it shows that plugin is loaded but in browser window it says "couldn't load plugin".

I am embeding the pluging in html using following tag
<embed id="hello_tutorial"
             width=200 height=200
             type="application/x-pnacl"
             src="hello_tutorial.nmf" />

below is my hello_tutorial.nmf file
{
  "program": {
    "portable": {
      "pnacl-translate": {
        "url": "hello_tutorial.pexe"
      }
    }
  }
}

logs are enabled and no error related to plugin is shown.
[part1.zip](https://github.com/electron/electron/files/485051/part1.zip)

**Comment by deepak1556** [comment]
Electron does not support native client, it can only load pepper plugins. You can look at some issues where users have successfully loaded pepper plugins https://github.com/electron/electron/issues/3252 and https://github.com/electron/electron/issues/3794 .

Closing this out since there is no plan on adding native client support https://github.com/electron/electron/issues/3300#issuecomment-152987235

**Comment by 92anurag** [comment]
I have created plugin and then registered it, so I believe it should work after registering. You can see below code in main.js

let customPlugin_path;
customPlugin_path = path.join(__dirname,'hello_tutorial.pexe') + ';application/x-pnacl';
app.commandLine.appendSwitch('register-pepper-plugins', customPlugin_path);

**Comment by deepak1556** [comment]
@92anurag Electron cannot work with pexe or nexe files without having support for native client. See this gist for example of pepper plugin load https://gist.github.com/deepak1556/cdb701cba6a3afc29844.

**Comment by 92anurag** [comment]
Thanks @deepak1556. I got it.

**Comment by 92anurag** [comment]
@deepak1556 I tried to run example using link you have shared but its not working. I build .cpp using command you have shared and generated .so file. Then tried to load this plugin and run. 
running navigator.plugins on console is showing that one plugin is loaded but html is not able to load it. Can you please have a look why its not working. 
I am tried to run it on mac, so generate plugin on mac I ran command 
g++ ./hello.cc -shared -o libppapi_hello.so -I/Users/sinwar/Desktop/nacl_sdk/pepper_49/include -L//Users/sinwar/Desktop/nacl_sdk/pepper_49/lib/mac_host/Release -lppapi_cpp -lppapi -lpthread -Wall -fPIC
[cdb701cba6a3afc29844-e607458e7e44d54ea2c473356624f267a69ab7a4.zip](https://github.com/electron/electron/files/488326/cdb701cba6a3afc29844-e607458e7e44d54ea2c473356624f267a69ab7a4.zip)

<img width="608" alt="screen shot 2016-09-23 at 2 02 27 am" src="https://cloud.githubusercontent.com/assets/8642125/18765307/bbd24d42-8132-11e6-9316-75b3e544cc74.png">

**Comment by 92anurag** [comment]
logs on console :- 

[4542:0923/021414:VERBOSE1:child_thread_impl.cc(371)] Mojo is disabled on child
[4543:0923/021414:INFO:systeminfo.cc(82)] Available number of cores: 8
[4543:0923/021414:VERBOSE1:child_thread_impl.cc(355)] Mojo is enabled on child
[4542:0923/021414:VERBOSE1:gles2_cmd_decoder.cc(3166)] GL_EXT_packed_depth_stencil supported.
[4542:0923/021414:VERBOSE1:gles2_cmd_decoder.cc(3166)] GL_EXT_packed_depth_stencil supported.
[4542:0923/021414:VERBOSE1:gles2_cmd_decoder.cc(3166)] GL_EXT_packed_depth_stencil supported.
[4543:0923/021415:VERBOSE1:HTMLPlugInElement.cpp(485)] EMBED id="hello_tutorial" Plugin URL: <null>
[4543:0923/021415:VERBOSE1:HTMLPlugInElement.cpp(486)] Loaded URL: <null>

**Comment by 92anurag** [comment]
I am able to load plugin in chrome and run it using 

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --register-pepper-plugins="libppapi_hello.so;application/x-hello”

Then opening nacl.html in browser showing me alert as expected but not in electron

**Comment by atypicalprogrammer** [comment]
Has this been fixed for you?
