### ISSUE TITLE
Black dropdown and GL error

### ISSUE THREAD

**Issue by superjamie** [electron/electron#7289]
* Electron version: 1.4.0
* Operating system: Ubuntu 16.04
* Graphics card: AMD Radeon HD6870 (open source `radeon` driver)

I am using the [PiBakery](https://github.com/davidferguson/pibakery) Electron app. There is a dropdown which displays like so:

![Screenshot showing black square](http://i.imgur.com/z9GSCUw.png)

This series of messages is repeated each time I try to open the dropdown:

~~~
[26450:0920/230638:ERROR:gles2_cmd_decoder_autogen.h(148)] [.DisplayCompositor-0x23a1abe75e00]GL ERROR :GL_INVALID_ENUM : glBindTexture: target was GL_FALSE
[26450:0920/230638:ERROR:gles2_cmd_decoder_autogen.h(3321)] [.DisplayCompositor-0x23a1abe75e00]GL ERROR :GL_INVALID_ENUM : glTexParameteri: target was GL_FALSE
[26450:0920/230638:ERROR:gles2_cmd_decoder_autogen.h(3321)] [.DisplayCompositor-0x23a1abe75e00]GL ERROR :GL_INVALID_ENUM : glTexParameteri: target was GL_FALSE
~~~

This is only a cosmetic bug, I can still select the contents of the dropdown successfully.

This happens with and without a compositor. I tested with `compton`.

The [file in question](https://github.com/adobe/chromium/blob/master/gpu/command_buffer/service/gles2_cmd_decoder_autogen.h) actually comes from Chromium. I spoke to the `#chromium-support` community on Freenode. They said there might be relevant GL fixes in the latest Chromium (it looks like Electron is on Chromium 52, but Chromium 53 is out now) or there could be Electron-specific changes to the renderer which cause this.

**Comment by kevinsawicki** [comment]
> They said there might be relevant GL fixes in the latest Chromium (it looks like Electron is on Chromium 52, but Chromium 53 is out now) or there could be Electron-specific changes to the renderer which cause this.

Electron 1.4.0 is running Chromium 53.0.2785.113

**Comment by kevinsawicki** [comment]
Are you able to test out the HTML from that app directly in Chromium and verify the dropdown does appear correctly there?

**Comment by superjamie** [comment]
That doesn't work sorry. The application hangs and I cannot bring up the dialog in question. I guess the app needs other stuff which doesn't load when I launch it with either of:

* `chromium-browser app/index.html`
* `sudo chromium-browser --user-data-dir=./rootdata/ app/index.html`

(the app usually does require root permissions, as it writes to raw sdcard devices)

**Comment by KynoYang** [comment]
similar with https://github.com/electron/electron/issues/4322

**Comment by kevinsawicki** [comment]
Thanks @KynoYang merging into https://github.com/electron/electron/issues/4322
