### ISSUE TITLE
Antivirus software alert tamper protocol warning

### ISSUE THREAD

**Issue by changkun** [electron/electron#7301]
* Electron version: 1.4
* Operating system: Windows

App is actual signed(certificate from StartSSL, not free), antivirus software will not warn it's installation, however the protocol modification behavior still gains a warning from antivirus software (appear in most of Chinese antivirus software).

**Comment by zcbenz** [comment]
I'm afraid there is nothing we can do, you can find a discussion on this at https://github.com/atom/atom/issues/3927.
