### ISSUE TITLE
Weird Background Color

### ISSUE THREAD

**Issue by adamisntdead** [electron/electron#7304]
- Electron version: v1.4.0
- Operating system: macOS Sierra

It seems to be that when I generate a window and set the background color (via css in the window),
that it comes up as 2 slightly different colors (See Image).

![Image](http://i.imgur.com/YhG440F.png)

The image is in frameless mode, but seems to be the same with a frame...

the HTML code for the window is:

``` html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Break Time!</title>
    <style>
        body {
            background-color: #EF4836;
        }
    </style>
</head>

<body>
    <div class="break">
        <div class="message"></div>
        <a id="close">...nah, I'll just keep going on</a>
    </div>
    <script>
        require('./render.js');
    </script>
</body>

</html>

```

and the BrowserWindow settings:

``` js
        width: 800,
        height: 600,
        frame: false
```

**Comment by zeke** [comment]
Hmm. I'm unable to replicate this on macOS 10.11.6 (15G31)

![screen shot 2016-09-22 at 2 24 39 pm](https://cloud.githubusercontent.com/assets/2289/18766707/6276f6e2-80d0-11e6-9984-71ef5c6ab5a7.png)

Have you tried opening the web inspector and seeing if there's a phantom element or something? What happens if you move the window around?

**Comment by thomasjo** [comment]
Pretty sure this is the same issue reported for Atom; https://github.com/atom/atom/issues/12634

The Chromium issue is tracked at https://bugs.chromium.org/p/chromium/issues/detail?id=633805

**Comment by arifcakiroglu** [comment]
There is a possible fix using `--force-gpu-rasterization`.

Try this:  `/Applications/youtapp.app/Contents/MacOS/Electron --force-gpu-rasterization`

**Comment by thomasjo** [comment]
Just a quick a update; the underlying Chromium issue has been [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=633805#c36), and should be released in Chromium 54.

Now we just have to patiently wait for 54 to land in stable 🙄

**Comment by zeke** [comment]
> Now we just have to patiently wait for 54 to land in stable

@zcbenz is working on it :)

**Comment by darkstar238** [comment]
When Fixed?

**Comment by MarshallOfSound** [comment]
@darkstar238 Read through the comments

> Just a quick a update; the underlying Chromium issue has been fixed, and should be released in Chromium 54.

Now we just have to patiently wait for 54 to land in stable

**Comment by mika76** [comment]
One way to see this happening (or fix it) is to change your profile in your display preferences...

**Comment by thomasjo** [comment]
This issue can be closed — it has been resolved upstream.

**Comment by zeke** [comment]
Thanks, @thomasjo
