### ISSUE TITLE
Feature request: Make SSL certificate import work on Mac and Windows

### ISSUE THREAD

**Issue by i-am-jd** [electron/electron#7305]
Hi! I'm working on an app that needs to manage its own SSL client certificate. I saw that @deepak1556 implemented this for Linux in #5197, and is willing to work on support for other platforms. I can help with testing on Mac and Windows. Can @deepak1556 or someone else help me with this? Thanks!

**Comment by deepak1556** [comment]
I don't have access to OSX or windows, so I am not working it. I can gladly direct anyone who is interested to implement for those platforms. Merging this to the original issue https://github.com/electron/electron/issues/1956
