### ISSUE TITLE
Document electron's implicit use of Google services

### ISSUE THREAD

**Issue by nikola** [electron/electron#7306]
- Electron version: 1.4.0
- Operating system: any

The docs say:

> Electron includes a hardcoded API key for making requests to Google's geocoding webservice.

When do these requests happen, and for which exact purpose? This should be documented.

Also, there should be an environment flag to disable these kind of requests altogether.

**Comment by zeke** [comment]
Good idea. Would love to know more about all the APIs that require network activity.

The geocoding webservice is hit when your app uses `navigator.geolocation`. There are other Chrome APIs that will make external requests (Text to Speech?), but none of these requests are made unless you explicitly write your app to make use of them.

**Comment by nikola** [comment]
Where in the codebase is this actually performed? Looking at the [Google Geolocation API surface](https://developers.google.com/maps/documentation/geolocation/intro) it seems a lot of system information needs to be gathered and provided to the web service for this to work - is this actually implemented in electron?

A quick test in a sample app shows that electron returns an empty `GeoLocation` from `navigator.geolocation`.

**Comment by zeke** [comment]
An HTTP debugging proxy might help answer that question. We could examine the request payload.

Here's one written in Electron! https://github.com/james-proxy/james

**Comment by deepak1556** [comment]
@nikola Electron only provides the api key for the geolocation service, the actual implementation is taken care by [chromium](https://cs.chromium.org/chromium/src/device/geolocation/) , same goes for speech api.

**Comment by nikola** [comment]
@deepak1556 Can you point me to an example where accessing `navigator.geolocation` actually performs such a request? Because in my testing so far, both in the Electron API Demos app and in a sample app, no request to Google's Geolocation API is triggered when accessing `navigator.geolocation`, no network activity, no logs anywhere. So one might suspect that even though Chromium provides that facility, it's not functional from within electron.

**Comment by zeke** [comment]
@nikola sorry for my lack of clarity above. `navigator.geolocation` is just an object with method properties like `getCurrentPosition` and `watchPosition`. Try this:

```js
navigator.geolocation.getCurrentPosition(
  console.log.bind(console),
  console.error.bind(console)
)
```

**Comment by nikola** [comment]
@zeke Thanks, that's now returning a 403, probably because electron's quota are exceeded. Using my own key, I can confirm that it works on this side, too.

**Comment by DenisCarriere** [comment]
### Note

>  Solution was found after writing this comment, this comment is simply used as reference/archive.

--------


@nikola You've got the `geolocation.getCurrentPosition()` to work in Electron? I keep getting this error 403 error:

```
Network location provider at 'https://www.googleapis.com/' : Returned error code 403.
```

I'm simply adding this to my `index.html` and trying to get any response from `success()`.
```html
<script>
navigator.geolocation.getCurrentPosition(
  success => console.log(success),
  error => console.log(error)
);
</script>
```
## Solution - Add Google API Key

After adding enabling GeoLocation and adding the Google API to my `main.js` before the window is created everything worked.

https://console.developers.google.com/apis/api/geolocation.googleapis.com/

**main.js**
```javascript
process.env.GOOGLE_API_KEY = "<GOOGLE API KEY>"
```

CC: #8918 #8754 #8212

**Comment by hollenberry** [comment]
@DenisCarriere 

Thank you for posting this! You helped me solve a tricky bug on a personal project ❤️ .

**Comment by DenisCarriere** [comment]
@hollenberry 👍 Welcome, it took me forever to solve this issue, hence the in-depth explanations. In the end this was a very simple fix (however it's kinda annoying that you need to enter a Google API key for it to work).

**Comment by damianobarbati** [comment]
But is the Google API request mandatory? Any other way to use native Chromium geolocation without making external calls and having to keep track of used quota?
Or its use is intended just when calling `navigator.geolocation.getCurrentPosition` from the `main` process thus not having a real Chromium running (which means that `navigator.geolocation.getCurrentPosition` from a `renderer` process does not use the Google API request)?

**Comment by erickzhao** [comment]
Going to close this, since the hard-coded API key was removed in #15478. The fix at https://github.com/electron/electron/issues/7306#issuecomment-289846493 is now documented at https://github.com/electron/electron/blob/master/docs/api/environment-variables.md.
