### ISSUE TITLE
Getting around CSP correctly

### ISSUE THREAD

**Issue by tolmasky** [electron/electron#7311]
Our Electron app loads several external pages in webviews. We use wish to interact with them by injecting scripts (for example, scrolling, etc). Unfortunately, this does not work when pages have CSP turned on. We have successfully defeated this by doing something along the lines of:

```javascript
  electron.session.defaultSession.webRequest.onHeadersReceived(function(details, callback) {
  console.log(details.responseHeaders);
    delete details.responseHeaders['Content-Security-Policy']
    delete details.responseHeaders['X-Frame-Options']
    const response = {
      cancel: false,
      responseHeaders: details.responseHeaders,
    }
    callback(response)
  });
```

However, this seems a little heavy handed, and it would seem that there must be SOME way of allowing "just" our scripts to run right? Certainly the console allows you to run custom code, so it must have some sort of elevated privileges which we'd like to have too. Has this problem been solved?

* Electron version: 1.3.4
* Operating system: OS X 10.11.6

**Comment by MarshallOfSound** [comment]
@tolmasky How were you originally injecting scripts?

As far as I am aware a `preload` script fits your use case perfectly?

**Comment by zcbenz** [comment]
Closing until more information is provided.
