### ISSUE TITLE
MSVCR120.dll MSVCP120.dll

### ISSUE THREAD

**Issue by guohailin0323** [electron/electron#7315]
* Electron version: v1.3.2
* Operating system: win10

hello dear:
         I use the "depends.exe" tool to view the v1.0.2 version of the electron, electron will rely on MSVCR120.dll, MSVCP120.dll. In the electron1.3.2 version does not rely on MSVCR120.dll, MSVCP120.dll. I don't know why, I guess it's a static link. I want to make it clear。
  thanks very much
      
![v1 0 2-01](https://cloud.githubusercontent.com/assets/21256636/18772269/1c5833da-8178-11e6-8715-8d3aff0ae5b8.png)
![v1 0 2-02](https://cloud.githubusercontent.com/assets/21256636/18772270/1c597bbe-8178-11e6-9791-9edfb649ea2c.png)
![v1 3 2](https://cloud.githubusercontent.com/assets/21256636/18772271/1c5dc2e6-8178-11e6-8393-1843da977997.png)

**Comment by MarshallOfSound** [comment]
Somewhere around `1.3.0` Electron switched to ship VS2015 libraries instead of 2013

https://github.com/electron/electron/pull/5538/files

**Comment by guohailin0323** [comment]
@MarshallOfSound 

Thank you for your reply.
![v1 3 2](https://cloud.githubusercontent.com/assets/21256636/18772927/1dbe39fe-817d-11e6-8a99-155c80a52449.png)
![v1 3 2-01](https://cloud.githubusercontent.com/assets/21256636/18772930/22bdc35c-817d-11e6-8edd-fd1734b4f27d.png)

But I use "depends.exe" to view the v1.3.2 electron, I did not find the dependence of the msvcp40.dll

**Comment by MarshallOfSound** [comment]
@guohailin0323 There was a version somewhere that didn't ship the right `.dll` files.  It could be that version.  I don't know?

Standard response: Update to latest Electron 👍

**Comment by guohailin0323** [comment]
@MarshallOfSound 
I update electron to the latest. I use the "depends.exe" tool to view the electron, I did not find the dependent msvcp40.dll, I am ready to create a new issue。

**Comment by MarshallOfSound** [comment]
@guohailin0323 Although I'm happy to help people solve problems, I'm not actually sure what the problem is here?  You said yourself it works?
