### ISSUE TITLE
Maximized window offset

### ISSUE THREAD

**Issue by iamdriz** [electron/electron#732]
When using a frameless window, the edges of the window are offset. This is apparently due to the way in which Windows handles the border offset... But when using a frameless window there is no borders, so this feels like a bug in Atom.

To combat this, I have applied some CSS to the body when maximized:

```
body.isMaximized
{
    position:absolute;
    top:4px;
    left:4px;
    right:4px;
    bottom:2px;
}
```

Which I apply and remove using the following:

```
$(window).resize(function(){

    if( remote.getCurrentWindow().isMaximized() )
    {
        $('body').addClass('isMaximized');
    }
    else
    {
        $('body').removeClass('isMaximized');
    }

});
```

However when in aero peak mode, the window is no longer clipped... So I get white borders around my application caused by the CSS positioning fix above!

Example of the clipping (without the CSS applied):

![image](https://cloud.githubusercontent.com/assets/801252/4733997/a6d40062-59ce-11e4-8884-dfcb43aa2eec.png)

If the above fixed is applied, then it adds extra padding when seen in aero peak (because the window is white and this page is white, you can't see it, but there is 4px space above the buttons and to the right of them):

![image](https://cloud.githubusercontent.com/assets/801252/4734015/dd8335d8-59ce-11e4-93be-1a287fdbbad8.png)

Any ideas on how to fix this?

**Comment by Datta973** [comment]
(I know its odd to comment now)This comment is for the people who still have the problem..
If you are playing with margin property under body(css) then remove it,coz the browser has user agent style sheet margin set to 8px,but if u add the margin property in ur page then the user agent style sheet wont work hence you see the edges clipped 
So remove "margin" property under body if u still have the problem
