### ISSUE TITLE
Blank page with Electron Application

### ISSUE THREAD

**Issue by LovaBP** [electron/electron#7320]
I have a big issues with electron. It's seems to "Crash" when html animation's fired. So exactly electron show me a blank page (html, localstorage, scripts ecc were deleted), we have no logs in console and terminal.

Is there a way to debug verbose application?

Somebody can help me?

EDIT: i have test a lot and i found problem. I use angular-ui-router and when i use a tag `<a>` some links works, another crash app (blank screen)

**Comment by zeke** [comment]
Looks like you worked it out. If the problem persists, please comment on the issue and include a code example that reproduces the issue you're having.

**Comment by LovaBP** [comment]
The issue was tag `<a></a>`. I resolve using another tag for example `<div></div>`, but for me, is not good solution. 
Can you provide an "enhancement" or a pull request? @zeke
