### ISSUE TITLE
Dom element "OuterHTML" does not match the element rendered in webview

### ISSUE THREAD

**Issue by BenoitAverty** [electron/electron#7321]
* Electron version: 1.4.0
* Operating system: Debian (BunsenLabs linux)

Hi,

I'm working with electron and hterm, and I noticed a very strange behavior, illustrated by the following snippet : 
```javascript
// These variable are not set by me.
const text = '' // This is a unicode character.
const container = document.createElement('span') // and some container.style.... = ...

// Here is my code (not all of it but relevant part)
console.debug(container.innerHTML); //  -> When I get the container, it already contains the text. What I want is nest this text inside another span
container.innerHTML = `<span style="position: relative;">${text}</span>`; // I also tried creating the elements with createElement, with similar results
console.debug(container.innerHTML); // <span style="position: relative;"></span> -> Ok, that's what I wanted !
console.debug(container.outerHTML); // <span style="color: rgb(129, 162, 190); width: 10px; display: inline-block; overflow: visible;"><span style="position: relative;"></span></span> -> Ok, consistent with previous line and the container I had at the beginning
console.debug(container); // <span style="color: rgb(29, 31, 33); background-color: rgb(129, 162, 190); width: 10px; display: inline-block; overflow: visible;"></span> -> WTF? The nested span is missing !
console.debug(container.children[0]); // <span style="position: relative;"></span> -> This seems correct however.
```

Note that this isn't only a `console.debug` issue. The node, when rendered in the document, is also missing the nested span.

I tried to reproduce with this jsfiddle :  https://jsfiddle.net/mucvwm8g, but I haven't been able to reproduce with firefox not with chrome.

I am also looking for a reason in the code around this, but what is strange is that the two `console.debug` are side by side and telling inconsistent results. 

I'm opening this here since I can't reproduce in chrome.

If you need, I can push my entire code on a public repo.

Is electron messing with the dom methods in any way ?

**Comment by zcbenz** [comment]
Can you try whether you can reproduce it in this Chrome extension?
https://chrome.google.com/webstore/detail/browser-sample/edggnmnajhcbhlnpjnogkjpghaikidaa

It uses `<webview>` in Chrome and I want to know whether this is an upstream bug.

**Comment by BenoitAverty** [comment]
No I can't reproduce with my JSfiddle in this extension, but I can't reproduce in electron either. There must be something in `hterm` that messes with the `window` or `document` object in some way. I worked around it in my code, so you can close this issue for now (unless ou want to investigate further) and I'll re-open it if I get more information.

**Comment by zcbenz** [comment]
🆒
