### ISSUE TITLE
Scroll glitch

### ISSUE THREAD

**Issue by guillefar** [electron/electron#7328]
- Electron version: 1.3.4
- Operating system: Ubuntu 16.04 64x

When using an Electron App (Rambox), open sites and scrolling makes the page unreadable. Attached a screenshot. 

The url accessed was http://sailsjs.org/documentation/concepts/deployment

![captura de pantalla de 2016-09-23 16-26-07](https://cloud.githubusercontent.com/assets/1972792/18797339/d514708c-81cd-11e6-927c-735b5b17250f.png)

**Comment by zeke** [comment]
🎨  generative art.

Is it just on this website, or all sites? Do you see the same behavior in Chrome?

I would suggest opening an issue on the Rambox repo: https://github.com/saenzramiro/rambox/issues

**Comment by guillefar** [comment]
For now just this website, but didn't test many, really.
This doesn't happen in Chrome. 
I already opened an Issue in Rambox, and then said is likely an Electron issue and closed it.

**Comment by zeke** [comment]
Can you link to the rambox issue here?

**Comment by guillefar** [comment]
Sure https://github.com/saenzramiro/rambox/issues/359

**Comment by zcbenz** [comment]
Can you try using the app with Electron 1.4.x? This is usually upstream bugs and the Chrome upgrade can probably fix this.

**Comment by guillefar** [comment]
Sorry, no idea how to do that.

**Comment by zeke** [comment]
@guillefar it looks like rambox is already using the latest version of Electron: https://github.com/saenzramiro/rambox/blob/915a56088567406d79cac389ee37bf683b8e24c5/package.json#L93

To see if the latest (perhaps unreleased) version of rambox has fixed the bug, run this:

```sh
git clone https://github.com/saenzramiro/rambox
npm install
npm start
```

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
