### ISSUE TITLE
Windows 10 AU new emoji doesn't show properly

### ISSUE THREAD

**Issue by iNViTiON** [electron/electron#7334]
* Electron version: 1.4.1
* Operating system: Windows 10 AU

Some new emoji can't display and show up as a square. i.e. http://emojipedia.org/first-place-medal/ <- this one can display in Edge, Opera and even in notepad.

**Comment by enlight** [comment]
Do they show up in Chrome?

**Comment by iNViTiON** [comment]
@enlight Yes. It's show up properly both in address bar and in page content.
![image](https://cloud.githubusercontent.com/assets/13241662/18813391/d95ab722-8322-11e6-96b7-a3d99125ad11.png)

**Comment by zcbenz** [comment]
@iNViTiON Are you using Chrome stable channel?

**Comment by iNViTiON** [comment]
@zcbenz Yes. `Version 53.0.2785.116 m`

**Comment by kevinsawicki** [comment]
I'm having trouble reproducing this, I see that example emoji in both Electron and Chrome on Windows 10 1607.

<img width="604" alt="screen shot 2016-09-28 at 4 04 30 pm" src="https://cloud.githubusercontent.com/assets/671378/18935564/c91e6b90-8595-11e6-8372-2e6c2ea8d4aa.png">

@iNViTiON what specific Windows 10 version are you on? And can you include a screenshot of what you are seeing?

**Comment by iNViTiON** [comment]
@kevinsawicki It look like the one appear on visual studio code. It also like this on my app too.
![image](https://cloud.githubusercontent.com/assets/13241662/18943255/9dd86dec-8648-11e6-99f4-b82671e5a0be.png)

**Comment by kevinsawicki** [comment]
@iNViTiON I don't think Visual Studio Code is using Electron 1.4 yet, can you running `npm install -g electron@1.4.1` and then run `electron http://emojipedia.org/first-place-medal` and see if they show up there?

**Comment by iNViTiON** [comment]
@kevinsawicki I change package.json start script from "electron ." to "electron http://emojipedia.org/first-place-medal" to make sure that it the same version as I got with my app and it display correctly. But when I change back to "electron ." to run my app and it still show as square.
Here was it show on my app.
![image](https://cloud.githubusercontent.com/assets/13241662/18962806/7595deb0-869c-11e6-9039-433a6c5fd48b.png)
And it also can't type in Electron even it can display correctly in site content?
![image](https://cloud.githubusercontent.com/assets/13241662/18962947/07755c2a-869d-11e6-8948-deb735f3445b.png)

**Comment by kevinsawicki** [comment]
@iNViTiON can you provide a minimal app that demonstrates this issue for you to help us reproduce this?

**Comment by iNViTiON** [comment]
@kevinsawicki OK. I fork the quick start to demonstrate this here. -> <https://github.com/iNViTiON/electron-quick-start>

It should look like this.

![image](https://cloud.githubusercontent.com/assets/13241662/18972492/9d286ca0-86c3-11e6-84d6-29e3337057ad.png)

**Comment by kevinsawicki** [comment]
Thanks for the example, was able to reproduce, it is deciding to use `Arial` for those emojis instead of `Segoe UI Emoji` for some reason.

If you explicitly set the `font-family` in CSS to `Segoe UI Emoji` for those elements, they do render correctly in Electron.

**Comment by iNViTiON** [comment]
@kevinsawicki Thank for quick fix.

**Comment by kevinsawicki** [comment]
Found the related Chromium issue that added support for this, https://bugs.chromium.org/p/chromium/issues/detail?id=620419

**Comment by kevinsawicki** [comment]
An upstream Chromium fix for this has been opened at https://codereview.chromium.org/2387373003/
