### ISSUE TITLE
How to exclude react node_modules at the time of asar packaging

### ISSUE THREAD

**Issue by ganxunzou** [electron/electron#7336]
* Electron version:1.4.0
* Operating system:win64

My development environment is : Electron + React + Webpack . My page is through webpack after packaging . But because Electron Native Module and React node module share the ./node_modules directory, so when i `asar pack your-app app.asar` packaging, the React node module will be added to app.asar.

Would you please give me some help ......

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community).

**Comment by ganxunzou** [comment]
Oh Sorry ! Thank you for your help !
