### ISSUE TITLE
The docs and the style guide should contain the return value of methods when relevant

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#7337]
* Electron version: All
* Operating system: All

Currently the JSON API doesn't contain return values from methods, this makes converting the JSON to a `.d.ts` file quite difficult as we just assume that methods return `void` or `any`.

I would suggest the return standard being something like this.

```markdown
### `app.getName()`

Returns `String` - The current application's name, which is the name in the application's
`package.json` file.

Usually the `name` field of `package.json` is a short lowercased name, according
to the npm modules spec. You should usually also specify a `productName`
field, which is your application's full capitalized name, and which will be
preferred over `name` by Electron.
```

I.e. If a method has a return value, specify it in the first paragraph of the description in the following format

```markdown
Returns `[TYPE]` - Description of return value
```

/cc @zeke

**Comment by zeke** [comment]
I think this format should work.

**Comment by zeke** [comment]
What if a method doesn't return? Just don't document it?

**Comment by MarshallOfSound** [comment]
@zeke Yeah, just don't document it then the API can assume undefined / void

**Comment by enlight** [comment]
@MarshallOfSound summarized the proposed changes in #7339 as follows:
>I think the key thing here is the difference between human readable documentation and clear / accurate / formatted documentation. A think this a compromise between the two (both readable and follows an exact format).

I have a counter proposal that aims to maximize readability, some examples:

Proposal in OP:
```markdown
### `app.getName()`

Returns `String` - The current application's name, which is the name in the application's
`package.json` file.
```

VS

```markdown
### `app.getName()`

Returns a `String` with the application's name, which is the name in the application's
`package.json` file.
```

And with array types:

```markdown
#### `BrowserWindow.getAllWindows()`
 
Returns `BrowserWindow[]` - An array of all opened browser windows.
```

VS

```markdown
#### `BrowserWindow.getAllWindows()`
 
Returns an array of `BrowserWindow` instances that correspond to all the existing
browser windows.
```

And with object types:

```markdown
#### `win.getContentBounds()`

+Returns `Object`:
+* `width` Integer
+* `height` Integer
+* `x` Integer
+* `y` Integer
```

VS

```markdown
#### `win.getContentBounds()`

Returns an `Object` containing the bounds of the window's client area (e.g. the web page):
* `width` `Integer`
* `height` `Integer`
* `x` `Integer`
* `y` `Integer`
```

So the alternative format can be summarized as:

```markdown
Returns [a|an|the] [array of] [TYPE] [-] description

Returns [a|an|the] [array of] [TYPE] [-] description [:]
* `propName` `TYPE` [- description]
* `propName` `TYPE` [- description]
```

Obviously my proposal requires the parser to do more work, and I'm not the one writing the parser, so I'll be happy with whatever.

**Comment by MarshallOfSound** [comment]
@enlight Having messed around with the parser and submitted a PR RE the proposed changes over here:

https://github.com/electron/electron-docs-linter/pull/44

You have to be **REALLY** strict about allowed syntax as we currently parse the markdown into an HTML DOM structure and then parse those elements into the JSON API.  Using loose "english like" syntax adds a lot more fluff to the parser and makes it more likely that contributors will fail to follow the correct syntax.  And most importantly this won't throw an error, this will simply parse the return value as the description instead.  This is what we **really** want to avoid so I personally think a really strict syntax for docs is our best plan.  Interested in what @zeke thinks about this

**Comment by zeke** [comment]
I like @enlight's natural language idea from a reader perspective, but as an _author_ or _person writing the parser_ it sounds like more trouble than it's worth. I think the existing style is clear enough, even though it doesn't read like a sentence.
