### ISSUE TITLE
download progress events in autoUpdater

### ISSUE THREAD

**Issue by CoDanny** [electron/electron#7341]
* Electron version: 1.4.1
* Operating system: All

I would be nice to have progress events reported by the autoUpdater when a release is being downloaded by it.

**Comment by MarshallOfSound** [comment]
Duplicate #1989

> The auto updater is a thin wrapper around [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac) and [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows), you can request this feature there.

**Comment by zcbenz** [comment]
It would be possible when we have #4603.
