### ISSUE TITLE
Webview caching, unable to clear

### ISSUE THREAD

**Issue by matt3224** [electron/electron#7344]
* Electron version: 1.4.1
* Operating system: macOS Sierra

Hi maybe i'm missing something, but it seems electron is caching my styles and I need to know how I can turn off caching or clear caches. I am using the webview dom element.

Thanks for any help,

**Comment by zcbenz** [comment]
There are related methods in `session` module:
http://electron.atom.io/docs/api/session/#instance-methods

**Comment by JanMiksovsky** [comment]
I'm still hitting this issue in 2026 and found my way to this old bug. The new `--disable-http-cache` still isn't enough to disable Chromium's aggressive caching of CSS stylesheets.

What finally worked was effectively clicking the Dev Tools "Disable cache" option:

```js
  // Disable caching via Chrome DevTools Protocol
  window.webContents.debugger.attach("1.3");
  window.webContents.debugger.sendCommand("Network.enable");
  window.webContents.debugger.sendCommand("Network.setCacheDisabled", {
    cacheDisabled: true,
  });
```
