### ISSUE TITLE
I don't know where to submit the info when the info is valid in a form.

### ISSUE THREAD

**Issue by marko0925** [electron/electron#7345]
* Electron version: 1.3.4
* Operating system: Window 10

I have a problem when I submit the data, I dont't know where to send them :/
Sorry for my english, thanks in advance.
Index.html
![image](https://cloud.githubusercontent.com/assets/15986342/18818423/96e123c4-833e-11e6-9505-8e9f21df72ae.png)

index.js
![image](https://cloud.githubusercontent.com/assets/15986342/18818413/1d1574fa-833e-11e6-8ffc-8f9215854604.png)

main.js
![image](https://cloud.githubusercontent.com/assets/15986342/18818409/fe7ad88c-833d-11e6-811e-a6f0f7d99229.png)

**Comment by zcbenz** [comment]
The issues page is only for bug reports and feature requests, for question please seek help from the community: https://github.com/electron/electron#community.
