### ISSUE TITLE
Menu Accelerators and DevTools don't work without loading a URL

### ISSUE THREAD

**Issue by KeionneDerousselle** [electron/electron#7346]
* Electron version: 1.4.1
* Operating system: Windows 10

No shortcuts/accelerators or dev tools work without first loading a url for the main window. I know it's not common for someone to maybe use dev tools without setting a url for a main window, but for those just learning, it is not obvious.

I would have thought that the main window would be ready to use without html because the app.on('ready') event was fired. 

# Main.js Before Loading a URL
const {app, BrowserWindow, ipcMain, Menu} = require('electron');

const mainWindow;

app.on('ready', () => {
    mainWindow = new BrowserWindow();
    const appName = app.getName();

    const menuTemplate = [
        {
            label: appName,
            submenu:[
                {
                    label: `About ${appName}`,
                    click: () => { console.log('clicked');}
                },
                {
                    label: 'Quit',
                    click: () => {app.quit()},
                    accelerator: 'CmdOrCtrl+Q', 
                }
            ]
        }
    ];

   const menu = Menu.buildFromTemplate(menuTemplate);
   Menu.setApplicationMenu(menu);

    mainWindow.on('close', () => {
        mainWindow = null;
    });
});

# Main.js After Loading a URL (Shortcuts and DevTools now working)
const {app, BrowserWindow, ipcMain, Menu} = require('electron');

const mainWindow;

app.on('ready', () => {
    mainWindow = new BrowserWindow();
    mainWindow.loadURL(`file://${__dirname}/index.html`);

    const appName = app.getName();

    const menuTemplate = [
        {
            label: appName,
            submenu:[
                {
                    label: `About ${appName}`,
                    click: () => { console.log('clicked');}
                },
                {
                    label: 'Quit',
                    click: () => {app.quit()},
                    accelerator: 'CmdOrCtrl+Q', 
                }
            ]
        }
    ];

   const menu = Menu.buildFromTemplate(menuTemplate);
   Menu.setApplicationMenu(menu);

    mainWindow.on('close', () => {
        mainWindow = null;
    });
});

**Comment by zcbenz** [comment]
The only possible way to make devtools work without loading any URL is to always load `about:blink` by default, but it would then causes troubles for apps because when navigating to other pages white flash would happen. So I'm afraid this is something that we won't do.

For learners, the simplest way is to explore the default app, it provides many nice little features for learning Electron. You can run `electron -h` to learn more.
