### ISSUE TITLE
Webview's `goToIndex` is broken

### ISSUE THREAD

**Issue by victorporof** [electron/electron#7349]
* Electron version: 1.4.0
* Operating system: macOS

Recent electron update completely broke `goToIndex`. Navigating to http://electron.atom.io/docs/api/web-view-tag in a webview and clicking on various hash links (#webview-tag, #example etc.) to populate the history, then calling `goToIndex` with various indices produces inconsistent results, which sometimes look like an off-by-1 error, other times they're completely surprising.

**Comment by Mossop** [comment]
@victorporof Are you sure this is an electron issue? I couldn't reproduce this when calling goToIndex from the devtools but could when using our history menu.

**Comment by victorporof** [comment]
I'll look into if more.

**Comment by kevinsawicki** [comment]
> I'll look into it more.

@victorporof any updates? Is this still an issue for you?

**Comment by victorporof** [comment]
Actually this turned out to be a problem on our end! Sorry for the noise.
