### ISSUE TITLE
Add crop method for NativeImage

### ISSUE THREAD

**Issue by danburzo** [electron/electron#7352]
Would there be an opportunity here to do a performant crop operation on the NativeImage returned in the callback for the `paint` event when rendering offscreen? 

With onscreen rendering you can use the `capturePage` method to get a part of the visible page, and having a counterpart for offscreen rendering would make the two rendering methods interchangeable at whim.

(I'm also thinking the same crop method would allow one to use the `dirty` Rect to obtain the updated region of the NativeImage)

**Comment by zcbenz** [comment]
`capturePage` copies the image from an existing backing store, while there is no backing store for `paint` event, so the only solution is to add a `crop` method for `NativeImage`.

**Comment by danburzo** [comment]
Yes, that would be great. I've tried cropping based on the bitmap Buffer in Node, but the performance is abysmal, and you'd still need a way to encode that to JPEG/PNG. I'm assuming doing this at a lower level would prove much faster.

**Comment by kevinsawicki** [comment]
@zcbenz what do you think about merging this into #6523?

**Comment by zcbenz** [comment]
> @zcbenz what do you think about merging this into #6523?

Sounds good to me. 👍
