### ISSUE TITLE
showSaveDialog doesn't disable MacOS native menu

### ISSUE THREAD

**Issue by CoDanny** [electron/electron#7354]
* Electron version: 1.4.1
* Operating system: Mac OSX 10.11.6

Calling dialog.showSaveDialog shows the dialog but allows the user to select other options from the MacOS native menu. If another menu uses dialog.showOpenDialog for example, the application will throw:

2016-09-26 21:59:25.138 Electron[42232:1244634] Communications error: <OS_xpc_error: <error: 0x7fff786f8b90> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x7fff786f8f40> { length = 22, contents = "Connection interrupted" }
}>

It needs to be forced quitted after that.

Here's a walkthrough:

This option calls dialog.showSaveDialog

<img width="466" alt="screen shot 2016-09-26 at 10 08 10 pm" src="https://cloud.githubusercontent.com/assets/542760/18850072/2a2d295a-8436-11e6-9403-7758d977d909.png">

The dialog shows:
<img width="967" alt="screen shot 2016-09-26 at 10 08 20 pm" src="https://cloud.githubusercontent.com/assets/542760/18850099/4b6df2a2-8436-11e6-8d64-90c8b4fe341f.png">

Menu options are still available even when the save as... modal is on

<img width="978" alt="screen shot 2016-09-26 at 10 08 28 pm" src="https://cloud.githubusercontent.com/assets/542760/18850114/5db3e926-8436-11e6-80cb-07ba832283c0.png">

which causes the hang if the user selects another dialog.

In other platforms (Windows and Linux) the dialog is a true modal that doesn't allow the user to do anything with the app until the dialog is closed.

**Comment by zcbenz** [comment]
This is because all windows share the same menu in OS X, so if you have multiple windows having one modal dialog won't block other windows.

You basically have two choices: 1) do not pass the window to dialog, so the dialog is not modal; 2) manually disable the menu.

I'm closing this as won't fix since it is desired behavior.

**Comment by CoDanny** [comment]
Ok, that makes sense but what about the behavior of having the app freeze if the user tries to open another modal? That's hardly desired behavior...

**Comment by zcbenz** [comment]
The behavior depends on whether you pass an extra `browserWindow` parameter.

**Comment by CoDanny** [comment]
I pass that parameter in both cases:

```
    const result = dialog.showOpenDialog(
      this.mainWindow,
      {
        title: 'Select your 3D file',
        filters: [
            {name: '3D Models', extensions: ['stl','apf']},
            {name: '3D Print Files', extensions: ['gcode', 'gco', 'g', 'x3g']}
        ],
        properties: [ 'openFile' ]
      }
    );
```

and 

```
    dialog.showSaveDialog(
      this.mainWindow,
      {
        title: title,
        defaultPath: defaultName ? defaultName : null,
        filters: filters
      },
      (filename) => {
        evt.returnValue = filename ? filename : false;
      }
    );
```

so I still don't understand why they behave differently as it regards to the app native menu

**Comment by CoDanny** [comment]
@zcbenz any answer? sorry to be insistent but I don't think this is normal behaviour

**Comment by zcbenz** [comment]
When passing an extra callback, the call becomes asynchronous and macOS assumes that the app is still able to to other tasks, so it doesn't disable the menu items automatically.

**Comment by CoDanny** [comment]
@zcbenz That makes more sense. Thanks a lot. Would it be worth updating the documentation to clearly specify this?

**Comment by zcbenz** [comment]
@CoDanny This is more like a macOS behavior instead of an Electron defined behavior, but I think mentioning it in documentation would be very helpful.
