### ISSUE TITLE
allow setting http header when actually fetching binary

### ISSUE THREAD

**Issue by fantasticsid** [electron/electron#7355]
* Electron version: 1.3.3
* Operating system: Mac

from the doc https://github.com/electron/electron/blob/master/docs/api/auto-updater.md we do allow setting headers on the feedURL http request. However, after getting the update feed, squirrel does not set the same http header when it tries to fetch the actual binary.

Can we add an API for that? Or just reuse the same header both for feed request and binary download?

**Comment by zcbenz** [comment]
I'm merging this to #4603, which would provide a way to fix this.
