### ISSUE TITLE
AutoUpdater broken on read-only file system (Mac)

### ISSUE THREAD

**Issue by salomvary** [electron/electron#7357]
* Electron version: 1.4.0
* Operating system: macOS 10.11.6

If an application is started from a read-only file system (most typically the mounted "installer" .dmg file) the auto updater does the following:

1. Downloads the update
1. Tries to install it
1. Prompts for admin permissions
1. (I'm assuming installing the update fails silently, I can't see any error emitted or logged when admin permission is provided)
1. Goes back to 1. on restart

Expected behavior:

- Do not attempt to download and install updates on read-only file systems
- Instead of failing silently log or emit an error event (without attempting an install with admin permissions - which is guaranteed to fail on r/o filesystems)

**Comment by salomvary** [comment]
Workaround:

```js
fs.access(app.getPath('exe'), fs.constants.W_OK, err => {
  if (err && err.code == 'EROFS')
    console.log('Disabled automatic updates on a read-only file system.')
  else
     // start autoUpdater
})
```

**Comment by zcbenz** [comment]
I'm merging this to #4603, which would provide a way to fix this.
