### ISSUE TITLE
On windows, don't throw an exception when process.stdin is accessed.

### ISSUE THREAD

**Issue by ishamf** [electron/electron#7358]
* Electron version: 0.37.8 (Atom 1.10.2)
* Operating system: Windows 10, 64 bit

(Please tell me if this should be reported to atom/atom instead)

On windows, accessing `process.stdin` throws an exception. This is causing some problems ([1](https://github.com/ricardofbarros/linter-js-standard/issues/133), [2](https://github.com/sindresorhus/get-stdin/pull/17)).

![image](https://cloud.githubusercontent.com/assets/3515649/18867152/46e3a0c8-84cd-11e6-8a50-4e57c08ed065.png)

If it can't be implemented (#4218), maybe it can return an empty stream?

**Comment by ishamf** [comment]
Wait, I just noticed [this](https://github.com/electron/electron/commit/b5e9bb9e6a270d2d16081d54a2ed573bc714702b). Is it already fixed?

**Comment by MarshallOfSound** [comment]
Yes, this is already fixed.  I believe mostly patched back in `1.1.x` and completely patched in `1.3.x`  thanks to @kevinsawicki 👍
