### ISSUE TITLE
devTools does not hit debugger; and/or breakpoints on OSX

### ISSUE THREAD

**Issue by s-a** [electron/electron#7361]
Electron version: 1..4.1
Operating system: OSX

ref.: 
 - https://github.com/s-a/iron-node/issues/116
 - https://github.com/s-a/iron-node/issues/119
 - https://github.com/s-a/iron-node/issues/106

I can confirm that this does not impact electron prebuilds for Windows.

**Comment by kevinsawicki** [comment]
Are you experience this for the main process or the render process?

I'm able to stop on debugger keyword and manually set breakpoints in 1.4.1 from the render process on mac os:

![screen shot 2016-09-28 at 9 40 31 am](https://cloud.githubusercontent.com/assets/671378/18923126/fbd49c7a-855f-11e6-8186-a3795ae35a45.png)
<img width="804" alt="screen shot 2016-09-28 at 9 39 05 am" src="https://cloud.githubusercontent.com/assets/671378/18923125/fbce0950-855f-11e6-9f48-a38bb1087612.png">

**Comment by jefffriesen** [comment]
I posted this same problem on an old issue that may have been prematurely closed: 

I've got an example of this using electron-quick-start and electron 1.4.1:
https://github.com/electron/electron/issues/4842#issuecomment-249341646
https://github.com/electron/electron-quick-start/compare/master...jefffriesen:debugger

**Comment by kevinsawicki** [comment]
@jefffriesen The dev tools need to be open before a `debugger` statement breakpoint can be hit, if you refresh the window on your `debugger` branch after the dev tools pop open, do you see it get hit then? Here is what I'm seeing:

![screen shot 2016-09-29 at 2 40 15 pm](https://cloud.githubusercontent.com/assets/671378/18973533/d35ae184-8652-11e6-91f1-d29acc1330f3.png)

**Comment by ArnaudValensi** [comment]
I have the issue with electron 1.3.4 and 1.4.1 when I put a breakpoint in a react component for example. Even when a add the breakpoint after opening the dev tools:

![capture d ecran 2016-09-30 a 01 43 15](https://cloud.githubusercontent.com/assets/604486/18976304/31a1662e-86b1-11e6-9acc-3da56ef06c6f.png)

**Comment by kevinsawicki** [comment]
@ArnaudValensi in that screenshot you included the debugger seems to be paused, was it manually paused?

**Comment by ArnaudValensi** [comment]
@ kevinsawicki I have put a 'debugger;'

The source code in the dev tool seems not available only for my js files. The source is available for library code:

![capture d ecran 2016-09-30 a 03 05 28](https://cloud.githubusercontent.com/assets/604486/18977507/38320c50-86bb-11e6-9b17-a17f728a3bc7.png)

![capture d ecran 2016-09-30 a 03 05 46](https://cloud.githubusercontent.com/assets/604486/18977508/3a0fd0de-86bb-11e6-9c4b-d26e71ebe292.png)

In the first picture, the `render` function is in a file I wrote.
In the second picture, the `tryRender` is from react library.

It seems to be an issue with webpack.

**Comment by kevinsawicki** [comment]
> The source code in the dev tool seems not available only for my js files. The source is available for library code

Yeah, this is mostly a source map issue or a bug in the dev tools.

I'm going to close this out until more information is available.

**Comment by jefffriesen** [comment]
@kevinsawicki 
You're right. It will hit the debugger if the dev tools are already open in the electron-quick-start example I have. The issue in the other repo must be due to source maps or something else. Thanks.

**Comment by davidcoleman007** [comment]
just to add some information to this ticket, I have recently opened this ticket on electron-quick-start:
https://github.com/electron/electron-quick-start/issues/112#issuecomment-263093261

The answer for me was that the breakpoints were not being hit for the first ~500ms or so of the app life cycle. by adding this code to my main app entry point, I was able to open dev tools in main.js and all my breakpoints/debugger statements hit all the time simply by artificially waiting 1 sec before I do any of my own stuff.

```javascript
$(document).ready(
	function() {
		setTimeout(() => {
			foo = new FooService();
			spm = new SomeProcessManager();
			console.log("waiting for click");
			debugger;
			foo.onInstanceReady();
			spm.startMyStuff();
		}, 1000);
	}
);
```

hope this helps someone else who ran into the same issue as me
