### ISSUE TITLE
Native PDF Rendering

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#7366]
This is more of a general question, but how much effort would it be to port the native PDF renderer to Electron? Last time we looked, it was prohibitive because it relies on the Chrome extension framework, but now that we've implemented a fair bit of that, maybe this would be easier?

If it's not boil-the-ocean difficult, we might have a hack at doing this

**Comment by hokein** [comment]
Yeah, it is definitely possible, but it might take some time to work it out (depends on your experience). 

The PDF Rendering heavily relies on a Chrome Extension which loads a PDF pepper plugin to render the PDF.  Technically, we might need to migrate some Chrome Extension code (`chrome/browser/extensions`) and the PDF rendering Extension to electron.

From my experience, the most challenging part is to understand the code path of the Extension (There a a bunch of `*.js/html` in `chrome/browser/resources/pdf/`) and the out-of-process plugin.

The Chromium related issue: https://bugs.chromium.org/p/chromium/issues/detail?id=303491

**Comment by gerhardberger** [comment]
In the mean time, I made a little module with what you can simply add PDF viewing support to BrowserWindows with [pdf.js](https://github.com/mozilla/pdf.js): [electron-pdf-window](https://github.com/gerhardberger/electron-pdf-window)
