### ISSUE TITLE
Electron && Bluetooth

### ISSUE THREAD

**Issue by amrish7** [electron/electron#7367]
**Environment information**
   * node `v 6.5.0`
   * electron `v 1.4.1` (Chrome `v 53.0.2785.113`
   * OS X `v 10.11.6`

___

Is there a tutorial/example on connecting and streaming data from a bluetooth device? It will be great if someone could point me in the right direction. I am having trouble connecting to a device paired to my mac.

I want to connect to a bluetooth device (BLE and **non-BLE**) and stream and receive data. Here are the two things I have been trying

## 1. bluetooth-serial-port
The following code works great as node App, but **not** in electron. I am not seeing a success/error response to my `btSerial.connect` API call. I have reached out to the module developers https://github.com/eelcocramer/node-bluetooth-serial-port/issues/116, but I also  wanted to run it by the Electron community

```
var Bluetooth = require('bluetooth-serial-port');
var btSerial = new Bluetooth.BluetoothSerialPort();

const deviceEnum = (devs) => {
    console.log(`${devs.length} BlueTooth device(s) are paired.`);
    devs.forEach((dev) => {
        console.log(`Paired with "${dev.name}"`);

        if(dev.name.indexOf('<MY-DEVICE-NAME> ') === 0) {
            console.log(`Trying to connect with ${dev.name}`);
            btSerial.connect(dev.address, 1, () => {
                console.log(`CONNECTED >>> `);
            }, (e) => {
                console.error(`ERROR ON CONNECTED ${e}`);
            });
        }
    });
};
btSerial.listPairedDevices(deviceEnum);
```

I have enabled web bluetooth flag in my `main.js` as well `app.commandLine.appendSwitch('enable-web-bluetooth', true);`

I did not find https://github.com/electron/electron/issues/1943#issuecomment-146552554 helpful either (Unless I have missed something)

## 2. Web Bluetooth API's
I was not able to get the solution from https://github.com/electron/electron/issues/5565 and this [doc] (https://googlechrome.github.io/samples/web-bluetooth/device-info.html) to work either. 

Here is the code that I have and I am not getting a response back

### main.js
```
app.commandLine.appendSwitch('enable-web-bluetooth', true);
```

### index.js
```
console.log(`>>>> navigator.bluetooth.requestDevice: ${navigator.bluetooth.requestDevice}`);
    try {
        const filters = [];
        filters.push({namePrefix: 'MOB'});
        console.log(`Using filters: ${JSON.stringify(filters)}`);
        navigator.bluetooth.requestDevice({filters: filters})
            .then(device => {
                console.log('> Name:             ' + device.name);
                console.log('> Id:               ' + device.id);
                console.log('> UUIDs:            ' + device.uuids.join('\n' + ' '.repeat(20)));
                console.log('> Connected:        ' + device.gatt.connected);})
            .catch(error => {
                console.error('Argh! ' + error);
            });
    } catch(e) {
        console.log('EXCEPTION> ' + e);
    }
```

**Comment by deepak1556** [comment]
Are you running the bluetooth api code with some user gesture ? What is the error you get when using the web bluetooth api ? Does the same code work fine on chrome ?

**Comment by amrish7** [comment]
Here is the full code, I am invoking the API on button click where `initializeSdk` is a `<button>` element... Let me replace `<button>` with `<a>` and retry it as I remember someone mentioning that it only works on click event from `<a>` for some reason. 

```
const discoverDeviceBtn = document.getElementById('initializeSdk');

discoverDeviceBtn.addEventListener('click', function (event) {

    console.log(`>>>> navigator.bluetooth.requestDevice: ${navigator.bluetooth.requestDevice}`);
    try {
        const filters = [];
        filters.push({namePrefix: 'MOB'});
        console.log(`Using filters: ${JSON.stringify(filters)}`);
        navigator.bluetooth.requestDevice({filters: filters})
            .then(device => {
                console.log('> Name:             ' + device.name);
                console.log('> Id:               ' + device.id);
                console.log('> UUIDs:            ' + device.uuids.join('\n' + ' '.repeat(20)));
                console.log('> Connected:        ' + device.gatt.connected);})
            .catch(error => {
                console.error('Argh! ' + error);
            });
    } catch(e) {
        console.log('EXCEPTION> ' + e);
    }
    console.log(`#### Electron Version: ${process.versions.electron}`);
    console.log(`#### Chrome Version: ${process.versions.chrome}`);

    //require('../sdk/electronSdk');
});
```

**Comment by amrish7** [comment]
Couple of questions
  1. Do Electron's web bluetooth API's support **__non__**-Bluetooth LE devices?
  2. Is `bluetooth-serial-port` compatible with Electron? We have a bunch of code and unit testing written with bluetooth serial port and it would be nice if it worked 😃

**Comment by deepak1556** [comment]
What is the error you are receiving when using the web bluetooth api and does the code work as expected on chrome ?

> Do Electron's web bluetooth API's support non-Bluetooth LE devices?

Electron does not implement the web bluetooth api, we reuse the implementation from chromium. So if it works with chrome then it should work here otherwise its a bug in Electron. Also webkit bluetooth implementation states they perform only LE  scan https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/bluetooth/README.md . I can verify that LE scan works fine with above code.

```
[8423:0928/130906:INFO:CONSOLE(11)] ">>>> navigator.bluetooth.requestDevice: function requestDevice() { [native code] }", source: http://localhost:8000/index.html (11)
[8423:0928/130906:INFO:CONSOLE(15)] "Using filters: [{"namePrefix":"OnePlus One"}]", source: http://localhost:8000/index.html (15)
[8423:0928/130906:INFO:CONSOLE(28)] "#### Electron Version: 1.4.1", source: http://localhost:8000/index.html (28)
[8423:0928/130906:INFO:CONSOLE(29)] "#### Chrome Version: 53.0.2785.113", source: http://localhost:8000/index.html (29)
[8423:0928/130916:INFO:CONSOLE(18)] "> Name:             OnePlus One", source: http://localhost:8000/index.html (18)
[8423:0928/130916:INFO:CONSOLE(19)] "> Id:               3F/TCaINgSNxmtDXWT9Avg==", source: http://localhost:8000/index.html (19)
[8423:0928/130916:INFO:CONSOLE(20)] "> UUIDs:            ", source: http://localhost:8000/index.html (20)
[8423:0928/130916:INFO:CONSOLE(21)] "> Connected:        false", source: http://localhost:8000/index.html (21)
```

> Is `bluetooth-serial-port` compatible with Electron ?

Yes, the module is not specific to any runtime.

**Comment by amrish7** [comment]
`bluetooth-serial-port` does not work on recent versions of Electron.. It looks like it last worked with electron@1.1.2 as per this ticket https://github.com/eelcocramer/node-bluetooth-serial-port/issues/100

Regarding the web bluetooth api, Chrome team has provided a bunch of samples [here] (https://googlechrome.github.io/samples/web-bluetooth/) to interact with web bluetooth enabled devices, but it wouldn't work with any of the BLE devices that I have right now. I think most of the hardware does not fully support the web bluetooth standards as the standards is not fully finalized...

It would have been great if Electron worked fine with modules like `bluetooth-serial-port` which provides a reliable way to connect with Bluetooth devices (both Classic and BLE)

**Comment by zcbenz** [comment]
Please report to [Chromium's issues list](https://crbug.com) if Web Bluetooth API is not working for your device. For the support of `bluetooth-serial-port`, I'm afraid currently we don't have resources to look into why it doesn't work with Electron.

**Comment by amrish7** [comment]
@zcbenz We could look into fixing the issue and issuing a PR as well. Would you be able to point us in the right direction? According to https://github.com/eelcocramer/node-bluetooth-serial-port/issues/100, the issue is in the `C layer`. 

Could you/someone point us to documentations like to setting up the dev environment and tips with troubleshooting the issues in `C` code

**Comment by enlight** [comment]
@amrish7 According to your description you're not seeing any error, so why are you assuming your issue is the same as https://github.com/eelcocramer/node-bluetooth-serial-port/issues/100 ? Have you stepped through your code in a debugger to see what it's actually doing? Have you tried running your code in both the main and the renderer processes?

**Comment by gersonfa** [comment]
@amrish7 Did you manage implement web api in electron? If you didn't it, I was testing the [examples](https://googlechrome.github.io/samples/web-bluetooth/) of the chrome team in chrome and none worked until I upgrade Chrome to version 54, electron use version 53 so I think that's the reason why it does not work in electron, for who asked what was the error:
`TypeError: Can not read property 'requestDevice' of undefined`,  when I use:
`navigator.bluetooth.requestDevice` in the console
I don't know if I am activating the flags correctly with:
` app.commandLine.appendSwitch('enable-web-bluetooth', true);`

(sorry if I did not express myself well, English is not my first language)

**Comment by aalhaimi** [comment]
This is not an issue anymore.. Here's a [working example](https://github.com/aalhaimi/electron-web-bluetooth)
