### ISSUE TITLE
Parameters that are objects should declare optional properties in the docs

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#7370]
- Electron version: All
- Operating system: N/A

Currently the docs declare optional parameters to function calls by prefixing `(optional)` to the description of the parameter.  We should do the same thing for optional properties on objects that are parameters.

For instance

``` markdown
### `dialog.showOpenDialog([browserWindow, ]options[, callback])`

* `browserWindow` BrowserWindow (optional)
* `options` Object
  * `title` String - (Optional)
  * `defaultPath` String - (Optional)
  * `buttonLabel` String - (Optional) Custom label for the confirmation button, when
    left empty the default label will be used.
  * `filters` Array - (Optional)
  * `properties` Array - (Optional) Contains which features the dialog should use, can
    contain `openFile`, `openDirectory`, `multiSelections`, `createDirectory`
    and `showHiddenFiles`.
* `callback` Function - (Optional)
```

Also looking for an alternative to this, perhaps a simple `?` next to the type or a `*` to indicate required.  Adding `(Optional)` everywhere just seems messy to me

/cc @zeke

**Comment by zeke** [comment]
We can infer which top-level arguments are required by parsing the method signature: `[browserWindow, ]options[, callback]`.

As for the object properties... not sure. I kind of like the `*` idea. It's a familiar convention from GUI land. Interested to hear what others think.

**Comment by enlight** [comment]
What would the `*` variant look like exactly?

**Comment by MarshallOfSound** [comment]
@enlight Not sure tbh, maybe something like this


```markdown
### `dialog.showOpenDialog([browserWindow, ]options[, callback])`

* `browserWindow` BrowserWindow (optional)
* `options` Object
  * `title`<sup>*</sup> String
  * `defaultPath` String
  * `buttonLabel` String - Custom label for the confirmation button, when
    left empty the default label will be used.
  * `filters`<sup>*</sup> Array
  * `properties` Array - Contains which features the dialog should use, can
    contain `openFile`, `openDirectory`, `multiSelections`, `createDirectory`
    and `showHiddenFiles`.
* `callback` Function
```

Which results in 

### `dialog.showOpenDialog([browserWindow, ]options[, callback])`

* `browserWindow` BrowserWindow (optional)
* `options` Object
  * `title`<sup>*</sup> String
  * `defaultPath` String
  * `buttonLabel` String - Custom label for the confirmation button, when
    left empty the default label will be used.
  * `filters`<sup>*</sup> Array
  * `properties` Array - Contains which features the dialog should use, can
    contain `openFile`, `openDirectory`, `multiSelections`, `createDirectory`
    and `showHiddenFiles`.
* `callback` Function


I went for `<sup>*</sup>` because just `*` looked kind of silly, still up for other ideas though as even that doesn't look too flash

**Comment by enlight** [comment]
I'm definitely not a fan of `<sup>*</sup>`, that's harder to type out than `(optional)` and less readable. What if we used `[]` just like in the function signature?

```markdown
### `dialog.showOpenDialog([browserWindow, ]options[, callback])`

* `browserWindow` BrowserWindow?
* `options` Object
  * `[title]` String
  * `[defaultPath]` String
  * `[buttonLabel]` String - Custom label for the confirmation button, when
    left empty the default label will be used.
  * `[filters]` Array
  * `[properties]` Array - Contains which features the dialog should use, can
    contain `openFile`, `openDirectory`, `multiSelections`, `createDirectory`
    and `showHiddenFiles`.
* `[callback]` Function
```

**Comment by MarshallOfSound** [comment]
Yep, that looks good to me and @zeke thumbed it 👍

**Comment by zeke** [comment]
I did indeed 👍  this, but now coming back to it I feel that the square-bracket syntax for optional properties is a little confusing. It seems like it could be mistaken for some kind of array notation.

Somehow in the method signatures, it seems less confusing: `([browserWindow, ]options[, callback])`.

I guess I'm feeling that `(optional)` is the clearest way. It's more wordy, but there's no mistaking what it means:

```
* `buttonLabel` String (optional) - Custom label for the confirmation button, when left empty the default label will be used.
```

or perhaps `(required)`, if there are fewer of those overall:

```
* `[defaultPath]` String (required)
```

**Comment by MarshallOfSound** [comment]
@zeke So if `(required)` is present it indicates all other properties are `(optional)`?  And vice-versa?

**Comment by enlight** [comment]
I can't think of a good reason for turning the existing convention upside down, so I suggest marking optional parameters with `(optional)` instead of marking required parameters.

**Comment by MarshallOfSound** [comment]
PR to fix this was merged

**Comment by MarshallOfSound** [comment]
#7884

**Comment by zeke** [comment]
🤘
