### ISSUE TITLE
How use material-ui in electron

### ISSUE THREAD

**Issue by zhailei31665431** [electron/electron#7371]
version:1.4.1 (1.4.1)

My code alwasy console error in electron and same code in web browser not error;

![2016-09-28 09 37 12](https://cloud.githubusercontent.com/assets/3082395/18897713/2aa207f0-855f-11e6-847d-99da53deaaf3.png)

<img width="1072" alt="fyiyi" src="https://cloud.githubusercontent.com/assets/3082395/18897025/28c5d980-8559-11e6-86de-a469f5d37532.png">

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
