### ISSUE TITLE
Structures that are used as return types and event arguments should have a standardized format

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#7373]
* Electron version: All
* Operating system: N/A

Currently object structures such as `Display`, `Task` and `JumpListItem` are defined in an arbitrary non-standard way.  In order for these structures to be used by tools using the Electron JSON API file these structures must be defined in a standard way.

I would like to suggest either putting structure in a new folder called "structs" or something similar.  Then when the structure is referenced in the docs we simply link to that specific markdown file.

So we would have a file structure like

<pre>
- docs
     | - api
           | - structures
                 | - Display.md
                 | - JumpListItem.md
                 | - Task.md
                 | - OtherThingy.md
           | - app.md
           | - allthemodules.md
</pre>

Again, please provide alternatives to this if you think you've got one 👍 

/cc @zeke

**Comment by enlight** [comment]
Perhaps we could group these by API so we don't have to create a separate file for every struct?

<pre>
- docs
     | - api
           | - structures
                 | - app.md
                 | - common.md (shared structures?)
                 | - dialog.md
           | - app.md
           | - dialog.md
</pre>

**Comment by MarshallOfSound** [comment]
> Perhaps we could group these by API so we don't have to create a separate file for every struct?

I feel as though that isn't as logical, if that makes sense?  Like linking to a structure with the original suggesting would be

```markdown
[Display](structures/Display)
```

Whereas the alternative would look like this

```markdown
[Display](structures/common.md#display)
```

I'm also thinking about how these would be rendered on the `electron.atom.io` website.
