### ISSUE TITLE
Relaunching app without helper process in RelaunchApp implementation

### ISSUE THREAD

**Issue by brianmmorton** [electron/electron#7376]
* Electron version: 1.3.0
* Operating system: OSX El Capitan

First off, thanks for all the hard work that went into this, really appreciate it.

I have an application that is wrapped around a apple script. When the main process calls app.relaunch(), app.quit(), the applescript loses permissions after the new app is started. Basically, I've been digging around for a while now, and finally jumped into the source code to see this comment:

>  // Use the currently-running application's helper process. The automatic
>  // update feature is careful to leave the currently-running version alone,
>  // so this is safe even if the relaunch is the result of an update having
>  // been applied. In fact, it's safer than using the updated version of the
>  // helper process, because there's no guarantee that the updated version's
>  // relauncher implementation will be compatible with the running version's.
https://github.com/electron/electron/blob/4ec064d311275bb8d6d652b9b917c0d199b3cb19/atom/browser/relauncher.cc#L36

So im wondering if someone here knows if this relaunch method would work for me if it quit completely rather than leaving the helper process alone? Also, the auto update quitAndInstall method actually works for me (permissions are not lost), so thats how i got to here.

**Comment by zcbenz** [comment]
The `quitAndInstall` relies on the auto updater framework to work, which starts a new helper app to restart the app, for the same effect you can either ship a helper app or use dynamically generated bash/AppleScript scripts to do the restart.
