### ISSUE TITLE
how to capture 'Uncaught Error'

### ISSUE THREAD

**Issue by Autumn2016** [electron/electron#7378]
* Electron version: v1.3.5
* Operating system: win7

---
this is my program:
![main](https://cloud.githubusercontent.com/assets/18275891/18902574/70132b44-8586-11e6-9147-980637a961db.png)

![index](https://cloud.githubusercontent.com/assets/18275891/18902571/6fbcb8e0-8586-11e6-960a-d6e01f9a8962.png)

![render](https://cloud.githubusercontent.com/assets/18275891/18902573/6ffd4bb2-8586-11e6-918d-9696e1559060.png)

![log](https://cloud.githubusercontent.com/assets/18275891/18902595/8f6c3d0a-8586-11e6-85d4-89e3047a79b1.png)

problem:
I want '''Uncaught Error''' enter the '''process.on('uncaughtException', function(error) {})''',so that i can save the error to the local file as log.
I would appreciate it if you could help me.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

However in answer to your question.

```js
process.on('uncaughtException', (err) => {
  // Do something with err
});
```

**Comment by Autumn2016** [comment]
thanks for you reply.
I do like this：
```
process.on('uncaughtException', (err) => {
  console.log("===========enter uncaughtException===========");
});
```

but terminal show:
![1111](https://cloud.githubusercontent.com/assets/18275891/18903063/80050f10-8589-11e6-9461-fd858b34d70c.png)
the error is not enter '''uncaughtException'''

**Comment by MarshallOfSound** [comment]
@Autumn2016 As said before please ask questions on the community forums or in slack.  I will not be answering more questions here.

That uncaught error is coming from a renderer process
