### ISSUE TITLE
DeprecationWarning: 'GLOBAL' is deprecated, use 'global'

### ISSUE THREAD

**Issue by arkakkar** [electron/electron#7381]
* Electron version: "electron-prebuilt": "^1.2.7"
* Operating system: OSX 10.11.4

I get this error 'DeprecationWarning: 'GLOBAL' is deprecated, use 'global' on accessing window object from a renderer process.

Node version is 6.4.0

**Comment by kevinsawicki** [comment]
I don't think this message is coming from electron, are you able to provide the line this is being logged from when you see this message in the dev tools?

**Comment by arkakkar** [comment]
This is logged when I try to access the window object in a renderer process. Updated the electron prebuit to electron package and the issue seems to be resolved

**Comment by kevinsawicki** [comment]
> Updated the electron prebuit to electron package and the issue seems to be resolved

Okay, thanks for the update, closing out

**Comment by arkakkar** [comment]
Thanks
