### ISSUE TITLE
can't get jquery plugin chosen to work

### ISSUE THREAD

**Issue by uotw** [electron/electron#7384]
* Electron version: 1.2.0
* Operating system: OS X

Hello, I'm trying to use the jquery plugin [chosen](https://github.com/harvesthq/chosen) in my electron app.  When I look at sources in the developer panel I see the chosen js has loaded, but then when I try to invoke the code I get the following error:

> Uncaught TypeError: $(...).chosen is not a function

Here's how I'm loading it up from index.html:
```
  <script>
    window.$ = window.jQuery = require('jquery');
    require('./renderer.js')  
  </script>
<script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>
<script>if (window.module) module = window.module; var $ = require('jQuery');</script>
<script src="./chosen/chosen.jquery.min.js"></script>
```

I also tried using this line instead, but then the file doesn't even get loaded up:
`require('./chosen/chosen.jquery.min.js');`

Jquery works perfectly, BTW.

**Comment by enlight** [comment]
GitHub issues are for bug reports and feature requests, questions about writing Electron apps should be directed to [the community](https://github.com/electron/electron#community).

**Comment by nandodutra** [comment]
@uotw did you have success with this issue?

**Comment by uotw** [comment]
Nope, gave up.

**Comment by nandodutra** [comment]
I'm with a very similar issue, but think i will give up too.

**Comment by KeinWeb** [comment]
For some reason there are no solutions. Sometimes it works if you add the plugin directly under the require jquery tag, but thats not working for the most plugins. Sadly no one can help us with this problem.....

**Comment by KeinWeb** [comment]
> GitHub issues are for bug reports and feature requests, questions about writing Electron apps should be directed to [the community](https://github.com/electron/electron#community).

Just close instead of reply to this problem, just because of the wrong asking platform.....
