### ISSUE TITLE
Configurable notification duration

### ISSUE THREAD

**Issue by yuya-oc** [electron/electron#7385]
* Electron version: 1.4.1
* Operating system: Windows 10

`electron/brightray` seems not to set the `duration` attribute to toasts, so they disappear soon. I feel it's a little short to notice and click them.
How about adding `duration=long` into toasts? Or is there any chance to amend the duration?

**Comment by zcbenz** [comment]
Does Windows have a style guide on how long the toast duration should usually be? Otherwise I tend to keep the default duration.

For configuring the duration, it would require us to provide a whole new set of notification API, which belongs to #3359.

**Comment by yuya-oc** [comment]
I found [this document](https://msdn.microsoft.com/en-us/library/windows/apps/hh779727). Assuming this, `short` seems to be used.

> - Standard toast: Most developers should use the standard toast notification. This toast remains on the screen for seven seconds, playing a brief sound to alert the user when it appears. The standard toast is best for notifications such as an IM contact sign-in, or a social media update.
> - Long-duration toast: This notification looks the same as a standard toast but stays on the screen for 25 seconds and optionally can play longer, looping audio. This type of toast is used in situations where you want to grab the user's attention because there is a human waiting on the other end of the connection. This is appropriate for person-to-person communication like instant messages and VOIP calls. This type of toast can also be used for calendar reminders.

However, in some scenarios like chat clients, `long` would be helpful. So I'm glad if there is a set of notification API.

Just for example, would the API look like below?

```js
// considering only Toast notification
const {Toast} = require('electron');
const toast = new Toast({
  text: '...',
  image: 'file:///...',
  duration: 'long',
  ...
});
toast.on('click', () => {
  console.log('toast is clicked');
});
toast.on('dismiss', () => {
  console.log('toast is dismissed');
});
```

**Comment by zcbenz** [comment]
I'm merging this to #3359.

> Just for example, would the API look like below?

Yeah, it would be something similar.
