### ISSUE TITLE
electron-prebuilt postinstall script 'node install.js' failure

### ISSUE THREAD

**Issue by azmuth94** [electron/electron#7386]
* Electron version: 1.4.1
* Operating system: Linux 4.4.11-v7+
* node v4.2.1
* npm  v2.14.7

**Comment by enlight** [comment]
Please search https://github.com/electron-userland/electron-prebuilt/issues and if you don't find an existing issue that matches yours then open a new one over there with FULL details of the error you've encountered.

**Comment by azmuth94** [comment]
same issue if i try using electron:

npm install -g electron

![image](https://cloud.githubusercontent.com/assets/8680993/18928843/e5a63f3c-858f-11e6-97cf-4c8b5601aca1.png)
