### ISSUE TITLE
Can you do a webpage screen capture within a webpage loaded inside an Electron App?

### ISSUE THREAD

**Issue by jasondavis** [electron/electron#7387]
I have a Google Chrome Extension that uses the Chrome API to generate screenshots of a webpage.
- full length height screenshots
- select and drag region screenshots
- visible viewport screenshots

I then also have an Electron app which opens bookmarks links from a left side sidebar into a right side Iframe.  Click the link in the left sidebar and it opens the webpage in the right panel which is an Iframe in the Electron App.

My goal is to add the capability to my app to allow the creation of my screenshots of the webpage opened in my right panel Iframe in my Electron app.

My Google Chrome JavaScript for creating the screenshots relies on the Chrome Extension API's `chrome.tabs.captureVisibleTab()` function for creating screenshots so I am not sure if I have access to this somehow within an Electron app?  If not, is there any other way to generate a page screenshot from within an electron app?

* Electron version: Latest/Any
* Operating system:   Windows 7

**Comment by kevinsawicki** [comment]
You can use `webContents.capturePage` to take screenshots of part or all of the page.

See http://electron.atom.io/docs/api/web-contents/#contentscapturepagerect-callback for more details.

You can also use the `desktopCapturer` APIs to take screenshots outside of the current window, http://electron.atom.io/docs/api/desktop-capturer/

Closing this out.

**Comment by abnerlee** [comment]
@kevinsawicki Hi, I tried `webContents.capturePage`, but it can only capture the "visible" part of the page. If the height of your `html` node is larger than the BrowserWindow (or when there's a scroll bar), the overflow part is not included in the captured image. Is there any way to capture the whole page?

(tested in macOS 10.12, electron 1.0.2)

**Comment by li-xinyang** [comment]
I do have the similar issue as @abnerlee mentioned above. I have tried to pass the `Rectangle` obj into the `capturePage` method but it seems only changing the output image size instead of change the bound of screenshot.

**Comment by abnerlee** [comment]
I opened a new issue for the bug that only visible part can be captured in https://github.com/electron/electron/issues/8587

**Comment by jacklovepdf** [comment]
> I opened a new issue for the bug that only visible part can be captured in #8587

Can you tell me whether you have solved the problem？

**Comment by brunolm** [comment]
```ts
/**
 * Captures a full page screenshot including scrolled content
 */
async function captureFullPage(window: RedactBrowserWindow): Promise<string> {
  // set the window size to the full page size
  const dimensions = await window.webContents.executeJavaScript(
    `({
      width: Math.max(document.documentElement.scrollWidth, document.body.scrollWidth, document.documentElement.clientWidth),
      height: Math.max(document.documentElement.scrollHeight, document.body.scrollHeight, document.documentElement.clientHeight)
    })`,
  );

  window.setContentSize(dimensions.width, dimensions.height);
  await new Promise((resolve) => setTimeout(resolve, 600));
  // Capture the full page
  const screenshot = await window.webContents.capturePage();

  return screenshot.toDataURL();
}
```
