### ISSUE TITLE
Flag support / Command line

### ISSUE THREAD

**Issue by gabrielstuff** [electron/electron#7395]
- Electron version: any
- Operating system: any

As stated here : https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md not all flags are supported.

Could you explain why the list here http://peter.sh/experiments/chromium-command-line-switches/ is not supported ?

Thanks

**Comment by gabrielstuff** [comment]
@kevinsawicki thanks for the label. Could you elaborate on the answers ? Any more link in the doc ?

Thanks !

**Comment by kevinsawicki** [comment]
> Could you elaborate on the answers ? Any more link in the doc ?

Is there a flag you are trying to use that does not appear to be supported by Electron?

**Comment by jacobq** [comment]
Yes, could you please add support for `--enable-webassembly`?
See https://github.com/electron/electron/issues/6539#issuecomment-295318367

**Comment by vossad01** [comment]
@gabrielstuff From looking at the code, it appears (to me anyway) that with how electron integrates chromium, it is not just a simple matter of "passing through" the flag.  Instead the flag functionality needs to be explicitly wired to the appropriate subcomponent, meaning extra work and code for features that may not have relevance or demand in electron.  I believe that may answer your question "why the [entire] list [...] is not supported?"

**Comment by gabrielstuff** [comment]
hey @vossad01 thanks for the information. Do you have a link to a starting point. As per @kevinsawicki the thing is that it is a bit weird to run and try every flag and see if it has been implemented or not.

For instance, regarding this issue: https://github.com/electron/electron/issues/1277#issuecomment-296397800, ionphractal suggested to use: 

```
app.commandLine.appendSwitch('enable-gpu-rasterization', 'true')
app.commandLine.appendSwitch('enable-zero-copy', 'true')
app.commandLine.appendSwitch('disable-software-rasterizer', 'true')
app.commandLine.appendSwitch('enable-native-gpu-memory-buffers', 'true')
```

But looking at the documentation, [here](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md) these flags are not supported. Who should we trust (except our test 🔢 )

Also, the disambiguation over `appendArgument` and `appendSwitch` is kind of hard. Reading https://github.com/electron/electron/issues/4908, it looks like appending arguments that could be switch.

I'll be happy to help and clarify this.

**Comment by vossad01** [comment]
@jacobq WebAssembly is enabled by default as of 1.7.0, no need for the flag.

**Comment by jacobq** [comment]
Looks like 1.7.0 is still pre-release, but thanks for letting me know @vossad01. I'll look forward to trying it out.

**Comment by zcbenz** [comment]
Having a complete list of which flags are supported and which are not is an impossible task, since there are tons of them and the list changes a lot whenever Chrome is updated. So I'm closing this issue.

If you found some documented flag not working or you thought some flag should be documented, feel free to create a pull request.
