### ISSUE TITLE
How 

### ISSUE THREAD

**Issue by Luchanso** [electron/electron#7396]
* Electron version: 1.4.1
* Operating system: Win32

I use other programms in my project like this:
```js
const spawn = require('child_process').spawn
const bin = spawn('tor/tor.exe')
```

How to build it files? Or how to use other application in project?
When builded and runed, this code not work
![image](https://cloud.githubusercontent.com/assets/2098777/18931428/cc4ad1b6-85d4-11e6-9fee-e3ea9418c2ab.png)

**Comment by kevinsawicki** [comment]
You need to make sure your app is handling the squirrel installer events, https://github.com/electron/windows-installer#handling-squirrel-events

And also make sure you are shipping the `tor/tor.exe` in your app bundle and if you are using `.asar` files, make sure it is unpacked.
