### ISSUE TITLE
Application freezes when shows / closes the modal dialog repeatedly

### ISSUE THREAD

**Issue by HiroTamori** [electron/electron#7401]
* Electron version: 1.4.1
* Operating system: MacOSX 10.10, 10.12

From Electron version 1.2.4, `BrowserWindow` can accept `parent:` and `modal:` parameter.
I modified  [**electron-api-demos**](https://github.com/electron/electron-api-demos) render-process/windows/create-window.js like this:

```javascript
newWindowBtn.addEventListener('click', function (event) {
    const modalPath = path.join('file://', __dirname, '../../sections/windows/modal.html')
    const parentWindow = require('electron').remote.getCurrentWindow(); // Parent Window
    let win = new BrowserWindow({ parent: parentWindow, modal: true, width: 400, height: 320 });
    //let win = new BrowserWindow({width: 400, height: 320 }); // Original code
    win.on('close', function () { win = null })
    win.loadURL(modalPath)
    win.show()
})
```
Start api-demo and select "Create and manage windows" demo. When clicking "View Demo", a modal dialog comes down from the top edge of the application window. Then close it with clicking "Close this window" link (at this moment, the modal dialog behaves strangely in closing). 
Furthermore, click "View Demo" and "Close this window" again, then the dialog went blank. Also the application froze. It occurs 10/10 in my environment (10.10 and 10.12).

![electronmodaldialogissue](https://cloud.githubusercontent.com/assets/10972221/18944883/bdb7e5e2-8662-11e6-808d-3d435e0022c7.gif)

Once it falls in this status, the app can be terminated only by killing the process.

In Electron 1.2.5 and 1.2.6, this phenomenon happens occasionally.
(I found it tends to occur after minimized -> recover the app with some other background task like build some program)

I tried commented out a line from 1.4.1's 
`atom/browser/native_window_mac.mm` as it has the difference from 1.2.5:

```cpp
void NativeWindowMac::Close() {
  // When this is a sheet showing, performClose won't work.
  if (is_modal() && parent() && IsVisible()) {
    //[parent()->GetNativeWindow() endSheet:window_]; // Commented out this line 
    CloseImmediately();
    return;
  }
...
```
After this modification, the frequency of the phenomenon seems to be the same as 1.2.5.

**Could you tell me the workaround about this issue?**

**Comment by kevinsawicki** [comment]
@HiroTamori I think this bug is related to calling `show()` on a window that is a modal dialog causes issues. In that demo, there is a `win.show()` line but the window defaults to show as well and `NativeWindowMac::Show()` is getting called twice which is causing issues.

If I comment out the `win.show()` line the demo works fine for me, but this can be fixed in Electron by guarding against this case in `NativeWindowMac::Show()`.

**Comment by HiroTamori** [comment]
Thanks, @kevinsawicki 

Commented out `win.show()` also be fine on my side, however the status of `NativeWindowMac::Show()` would obviously better to be controlled in Electron.
I'm waiting for the fix. :+1:
