### ISSUE TITLE
Can't mkdir in .app/Contents/Resources/app/... (MacOS)

### ISSUE THREAD

**Issue by SorianoMarmol** [electron/electron#7402]
* Electron version: 1.3.5
* Operating system: MacOS

Hi all.

After packaging my app, in MacOS (latests versions like MacOS sierra 10.12) I can't create dirs in the resources/app dir when I launch the app with double click. Launching from terminal, works fine...

In older versions like "OS X 10.9.5  (Mavericks)" works fine

Log from console
`
Uncaught Error: EROFS: read-only file system, mkdir '/private/var/folders/ly/_8b675f13n38mljn304x1pkm0000gn/T/AppTranslocation/3216E139-EADB-421A-81F7-0A35905D8F66/d/DEBUG_herramienta_subida_ofertas_somacyl.app/Contents/Resources/app/projects/2016_CONNSP-1'`

Sorry if this is an issue from electron-packager, idk...

Thanks!

**Comment by MarshallOfSound** [comment]
You can't make folders and files dynamically inside running macOS applications.

Any folders or files you want to make should be placed in `app.getPath('appData')`
