### ISSUE TITLE
Path issue after electron packaging

### ISSUE THREAD

**Issue by Sam747** [electron/electron#7404]
* Electron version:1.2
* Operating system:Linux

After packaging my app with electron packager app is not able to encrypt and write files in resource folder.
Working fine without packaging.

**Comment by enlight** [comment]
Packaged apps shouldn't be writing to the installation directory, the user running the app may not always have permission to write to that location. Your application should write files to the location returned by `app.getPath('userData')`.

**Comment by Sam747** [comment]
Thanks for the followup
I am facing another issue with app.getAppPath() . Here is the error

node_modules/remote/libs/remote.coffee:8 Uncaught SyntaxError: Unexpected token >

Here is my  index.html

<script>
const remote = require('remote');
alert(app.getAppPath());
	</script>

**Comment by enlight** [comment]
You've installed the [remote](https://www.npmjs.com/package/remote) module from NPM, it is a CLI tool so I presume you've installed it by accident and what you were really after is the built-in Electron module by the same name. To access the latter you'd use `require('electron').remote`.

**Comment by Sam747** [comment]
Ok So i tailored my script this way now 

require('electron').remote;
alert(app.getAppPath());

and error is
Uncaught TypeError: app.getAppPath is not a function

Please bear with me as I am a newbie here .

**Comment by Sam747** [comment]
Thanks for the support I resolved the issue.

**Comment by scottbyrns** [comment]
@Sam747 Mind sharing how?
