### ISSUE TITLE
Click bounds on Tray icon on Linux

### ISSUE THREAD

**Issue by NelsonBrandao** [electron/electron#7412]
HI,

From what I can understand from the docs, there isn't a way to get the click bounds on Linux, just Windows and macOS, when clicking on a Tray icon. Is that right?

I wanted to do a menubar application that worked across all OS.

Thank you

* Electron version: latest
* Operating system: Linux (Arch Linux)

**Comment by douglassllc** [comment]
Any updates to this question?

**Comment by ckerr** [comment]
@douglassllc: @NelsonBrandao was correct, this feature is not supported on Linux.

I'd be happy to review a patch for this but the feature is not a priority for the core team right now.
