### ISSUE TITLE
MenuItem constructor ignores custom properties

### ISSUE THREAD

**Issue by eriedl-kiban** [electron/electron#7414]
* Electron version: 1.4.0
* Operating system: All

In reference to issue #54: Adding custom fields seems to work only when building a menu from a template. If the MenuItem constructor is used, which takes the same structure as a template as argument, custom fields are ignored/not added to the MenuItem instance.

This works:
```
let tmpl = {
  "label": "menu 1",
  "commandData": "foo",
  "submenu": [
    {
      "label" "item 1",
      "commandData": "bar"
    }
  ]
}

let mnu = new Menu.buildFromTemplate(tmpl);
console.log(mnu.commandData); // --> foo
console.log(mnu.submenu.items[0].commandData); // --> bar
```

This does not work (as expected):
```
let tmpl = {
  "label": "menu 2",
  "commandData": "foo",
  "submenu": []
}

let mnu = new Menu.buildFromTemplate(tmpl);
mnu.submenu.append(new MenuItem({
    "label" "item 1",
    "commandData": "bar"
  }));
console.log(mnu.commandData); // --> foo
console.log(mnu.submenu.items[0].commandData); // --> undefined
```

**Comment by liusy182** [comment]
This looks like a coding error.  `buildFromTemplate` only accepts Array but not Object. To access subitems, we need to use `items` e.g. `mnu.items[0].submenu.append(...)`

**Comment by enlight** [comment]
The second snippet isn't quite right, but the issue is still valid, extra properties passed into the `MenuItem` constructor are not preserved.

**Comment by jonathanGB** [comment]
I am looking into it, but this may take time because it is my first time looking into this code base!

**Comment by jonathanGB** [comment]
As @liusy182 mentionned, there were errors in the code sample. Here's the right sample:

```javascript
let tmpl = [{
  "label": "menu 1",
  "commandData": "foo",
  "submenu": [
    {
      "label": "item 1",
      "commandData": "bar"
    }
  ]
}]

let tmpl2 = [{
  "label": "menu 1",
  "commandData": "foo2",
  "submenu": []
}]

let mnu = new Menu.buildFromTemplate(tmpl);
console.log(mnu.items[0].commandData); // --> foo
console.log(mnu.items[0].submenu.items[0].commandData); // --> bar

let mnu2 = new Menu.buildFromTemplate(tmpl2);
mnu2.items[0].submenu.append(new MenuItem({
    "label": "item 1",
    "commandData": "bar2"
  }));
console.log(mnu2.items[0].commandData); // --> foo2
console.log(mnu2.items[0].submenu.items[0].commandData); // --> undefined
```

I'm looking for a fix.

**Comment by jonathanGB** [comment]
Hey, I'm going through the steps to build electron (it's my first time), but installing `pyobjc` on macOS Sierra is not working (due to this line: `Modules/_QTKit.m:6:9: fatal error: 'QTKit/QTKit.h' file not found`).

Will not be of help for this issue :/

**Comment by jtanzi** [comment]
I'm not on Sierra yet, I may give this a shot.

**Comment by jonathanGB** [comment]
@jtanzi if you find a way to install pyobjc with Sierra please let me know!

**Comment by jtanzi** [comment]
Sure thing!

**Comment by jonathanGB** [comment]
Hey, I'm pretty confident I have a fix. Only problem is that I'm not able to build electron  (#7492), so could someone test it for me?

Here's [the gist](https://gist.github.com/jonathanGB/51e645c5664316cc33d21371e8699436), so only change `/lib/browser/api/menu-item.js` with the gist and see if it the snippet I've posted earlier doesn't return `undefined` for the last parameter.

If that does the trick, I'll create a PR.
