### ISSUE TITLE
Electron app: Jquery usage

### ISSUE THREAD

**Issue by SameerKhan1406** [electron/electron#7421]
* Electron version:  1.0.0
* Operating system: Description:	Ubuntu 12.04 LTS ,Release:	12.04

Hello,

There is a problem with .hasClass() function, i want to store all div element using --var div = $('div');
with this div object i want to get to play a video if its inside my "Encrypt" class, while on the same page i have the same video but i'll play when we are inside "Decrypt" class so function are same ---- 
function Pause() 
   { 
       if(div.hasClass('Encrypt')){
       myvideo1.pause();
        }
        
       else
       { myvideo2.pause(); }
   }

same source video but with different id in variable myvideo1 and myvideo2

but i am getting the following error
Uncaught TypeError: Cannot read property 'hasClass' of undefined

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

For what it is worth though it looks like the `div` is not defined

**Comment by SameerKhan1406** [comment]
Sorry to post again but please look again i defined div in my script var div=$('div');

**Comment by MarshallOfSound** [comment]
@SameerKhan1406 As mentioned issues and support requests should go to the community or slack.

However when using jQuery in Electron you should be aware that you can't just use it in a script tag.  You have to do

```js
window.$ = require('jquery')
```

**Comment by SameerKhan1406** [comment]
Thank you i installed jquery and and require it like above....I worked ....Brilliant

**Comment by MehediH** [comment]
@MarshallOfSound I am trying to do the same thing, but it's unable to find the jquery module for some reason when packaged using electron-packager. 

I am doing `require("jquery")` from a JS file on the index.html file but it can't find jquery. If I do `npm start`, it works flawlessly but not when I package the app. 

Is this is a bug or am I doing something wrong?

**Comment by SameerKhan1406** [comment]
I resolved by installing every module by doing "--save" it will save your configuration and do this just outside of your node module folder where your main.js file is located for the current project. If something is not working get back and feel free to ask. Enjoy Coding!
