### ISSUE TITLE
App dir Error in macOS Sierra (10.12) 

### ISSUE THREAD

**Issue by alex-zhang** [electron/electron#7423]
* Electron version: Any
* Operating system: macOS Sierra (10.12)

the app can startup, but when i check the print log, the app path show `/private/var/folders/mv/........`
and the folder is readonly.

i download my app zip from a web server.  if i just run in local (not from network download) it's fine. so, is here security changed in  macOS Sierra. btw app is already code sign.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

> and the folder is readonly.

You shouldn't be writing to your apps install directory, that is what `app.getPath('userData')` is for.

You can read more about macOS Sierra's new Gatekeeper features in blog posts such as this one

http://weblog.rogueamoeba.com/2016/06/29/sierra-and-gatekeeper-path-randomization/

**Comment by alex-zhang** [comment]
@MarshallOfSound  thanks.
