### ISSUE TITLE
More control over the individual flags in RegisterURLSchemeAsPrivileged 

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#7430]
* Electron version: 1.4.1
* Operating system: -

RegisterURLSchemeAsPrivileged sets the scheme's policies to:

 - Secure
 - Bypassing CSP
 - Allowing Service Workers
 - Supporting Fetch API
 - CORS Enabled

I want all of those except Bypassing CSP. (Correct me if I'm wrong: Bypassing CSP means I couldn't enforce, say, 'object-src none', because that scheme would bypass the object-src policy. If I'm wrong, please LMK -- this may be a non-issue.)

Could we add an options argument to RegisterURLSchemeAsPrivileged for configuring which is enabled? Something like:

```js
webFrame.registerURLSchemeAsPrivileged('foo', {
  secure: true,
  bypassCSP: false,
  allowServiceWorkers: true,
  supportFetchAPI: true,
  corsEnabled: true
})
```

For backwards compatibility, the flags would default to `true`, so my usecase would be:

```js
webFrame.registerURLSchemeAsPrivileged('foo', { bypassCSP: false })
```
If 👍 , I'm happy to write a PR.

**Comment by deepak1556** [comment]
I am :+1: for removing bypassing CSP policy from `registerURLSchemeAsPrivileged` , there is a separate api to enforce it. It was added as a part of https://github.com/electron/electron/pull/2852 , didn't notice it then. Fetch, cors, serviceworkers are mutually inclusive, I don't think there is a need for options.

**Comment by pfrazee** [comment]
Sounds good, I'll submit a PR.

**Comment by deepak1556** [comment]
It would be a breaking change, so let's hear others thoughts before you work on it. Thanks!

**Comment by MarshallOfSound** [comment]
@deepak1556 It wouldn't be breaking if the syntax was 

```js
registerURLSchemeAsPrivileged(scheme[, bypassCSP])
```

And we just default `bypassCSP` to `true`

**Comment by deepak1556** [comment]
@MarshallOfSound the api sounds good to me, if possible can we deprecate bypass CSP and remove it from `registerURLSchemeAsPrivileged` in the future ?

**Comment by zcbenz** [comment]
Is it possible that someone may want to have CORS disabled but others enabled? And there will be more policies in future when fancy HTML features are being added. I think the original proposal that adds an option can save us from future pains while keep compatibility.

**Comment by pfrazee** [comment]
@zcbenz Are we a go on that approach?
