### ISSUE TITLE
Implementing dynamic notification app badge using setOverlayIcon

### ISSUE THREAD

**Issue by osamaaamer95** [electron/electron#7440]
* Electron version: 1.4.1
* Operating system: Win10 x64

I have been trying to implement an overlay badge in a chat application that should display number of unread messages. There has already been a similar issue asked at [https://github.com/electron/electron/issues/3148](url) and a solution presented at [https://gist.github.com/johnthedebs/c22a04fcd08e598e69b8](url) but setOverlayIcon does not work in the renderer process across remote since NativeImage cannot be serialized.

Is there a way to generate a dynamic overlayIcon in the main process? Or is there a way to generate in the renderer process using canvas and which doesnt generate the setOverlayIcon argument error?

**Comment by kevinsawicki** [comment]
> but setOverlayIcon does not work in the renderer process across remote since NativeImage cannot be serialized.

You should be able to pass a native image over the remote APIs.

This is what I tried from the dev tools on Windows and did see the icon update:

```js
image = require('electron').remote.nativeImage.createFromPath('C:\\electron\\default_app\\icon.png')
require('electron').remote.getCurrentWindow().setOverlayIcon(image, 'test')
```

This showed the following:

<img width="50" alt="screen shot 2016-10-03 at 2 59 54 pm" src="https://cloud.githubusercontent.com/assets/671378/19055675/12c1de70-897a-11e6-937c-0ee703a9e1a0.png">

**Comment by kevinsawicki** [comment]
Can you include more details about the error you are seeing and try the simplified example I pasted and see if that works for you?

**Comment by kevinsawicki** [comment]
Closing out until more information is received.

**Comment by michaelpeterlee** [comment]
Solution here as presented by @kevinsawicki is to re-require electron.remote.

**Comment by michaelpeterlee** [comment]
@osamaaamer95 use IPC similar to code here: https://github.com/electron/electron/issues/7325

**Comment by viktor-shmigol** [comment]
See  https://github.com/viktor-shmigol/electron-windows-badge

**Comment by tyru** [comment]
Hi, electron has supported `setOverlayIcon` on Windows 10?
I'm struggling unread notification, I want to add simple red circle icon (no unread count) dynamically.
But `setOverlayIcon` does nothing, no error.
I have tried these but nothing succeeded:

* pass asset path to `setOverlayIcon`
* write canvas content to file `fs.writeFileSync(tempPath, buffer)` and `setOverlayIcon(tempPath, "icon")`
* pass NativeImage to `setOverlayIcon`
* use @viktor-shmigol's library (electron-windows-badge)

**Comment by tyru** [comment]
In macOS, `app.dock.setBadge(' ')` succeeded.
In Windows, sending Data URI to main process via IPC, ipcMain succeeded to receive content, but `setOverlayIcon` doesn't work as I said above.
