### ISSUE TITLE
-webkit-app-region: drag not working on macOS Sierra

### ISSUE THREAD

**Issue by YannBertrand** [electron/electron#7442]
* Electron version: 1.4.1
* Operating system: macOS Sierra 10.12

It's not possible to drag an app without the native title bar.
Download [this gist](https://gist.github.com/YannBertrand/619fdb09de30df50a76fafa3354cfcce) to reproduce the issue.

**Comment by davej** [comment]
I did a bit of testing. It doesn't work when applied using inline styles but it should work if you use a css rule instead. For example:

```js
body {
  -webkit-app-region: drag;
}
```

This is more than likely still a bug though (albeit title is incorrect) because I guess inline styles should also work.

**Comment by YannBertrand** [comment]
I've tried it but it doesn't work either 😔

**Comment by YannBertrand** [comment]
I've done a few more testing:

 - drag & drop doesn't work when the dev tools are open
 - it doesn't work by setting the html style attribute -> it's mandatory to use a css rule
 - on my test, it only works on the `header` and `header h1` rules
 - even if I set a `width` and `height` on my body, it doesn't work

**Comment by davej** [comment]
All this works correctly for for me. The only thing that doesn't work is when the inline `-webkit-app-region` style is changed dynamically.

Your issues are possibly something to do with the fact that your element with content (`<header />`) doesn't have layout properties because it is absolutely positioned. It would be easier to test if you put this in a repo rather than a gist.

**Comment by YannBertrand** [comment]
You've got a button to download the gist as a zip 😉

**Comment by davej** [comment]
> You've got a button to download the gist as a zip 😉

Thanks!

As suspected it was because your elements didn't have layout. The easiest fix is to add a `width` and `height` to the body using absolute units, i.e..:

```css
body {
	font-family: -apple-system, 'Helvetica Neue', Helvetica, sans-serif;
	-webkit-app-region: drag;
	width: 100vw;
	height: 100vh;
}
```

**Comment by YannBertrand** [comment]
You're right! It's working with that `width` and `height`.

Have you tried with the dev tools opened?

**Comment by davej** [comment]
The devtools bug is tracked in #3647. It should work if you detach the devtools.

**Comment by YannBertrand** [comment]
Okey, I close this bug then! Thanks 😄
