### ISSUE TITLE
Failed at the nslog@3.0.0 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by edahlseng** [electron/electron#7445]
* Electron version: 1.4.2
* Operating system: Mac 10.12

nslog@3.0.0 install /Users/ericdahlseng/Library/Mobile Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/nslog
> node-gyp rebuild

  CXX(target) Release/obj.target/nslog/src/main.o

clang: error: no such file or directory: 'Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/electron-rebuild/lib/headers/.node-gyp/iojs-1.4.2/include/node'
clang: error: no such file or directory: 'Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/electron-rebuild/lib/headers/.node-gyp/iojs-1.4.2/src'
clang: error: no such file or directory: 'Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/electron-rebuild/lib/headers/.node-gyp/iojs-1.4.2/deps/uv/include'
clang: error: no such file or directory: 'Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/electron-rebuild/lib/headers/.node-gyp/iojs-1.4.2/deps/v8/include'
make: *** [Release/obj.target/nslog/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ericdahlseng/Library/Mobile Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/ericdahlseng/Library/Mobile Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ericdahlseng/Library/Mobile Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/nslog
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/Users/ericdahlseng/Library/Mobile Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/npm/bin/npm-cli.js" "rebuild" "--runtime=electron" "--target=1.4.2" "--arch=x64"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ericdahlseng/Library/Mobile Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/Users/ericdahlseng/Library/Mobile Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/electron-rebuild/lib/spawn.js:55:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "rebuild"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! micaDesktop@ rebuild: `electron-rebuild -f -p`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the micaDesktop@ rebuild script 'electron-rebuild -f -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the micaDesktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild -f -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs micaDesktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls micaDesktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ericdahlseng/Library/Mobile Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/npm-debug.log

**Comment by enlight** [comment]
It would appear that the Node headers weren't downloaded properly. Delete `Documents/com~apple~CloudDocs/Projects/BiLab/micaDesktop/node_modules/electron-rebuild/lib` and try again. Any further issues with `electron-rebuild` should be filed at https://github.com/electron/electron-rebuild/issues
