### ISSUE TITLE
[SOLVED] Application blocked after new BrowserWindow closed

### ISSUE THREAD

**Issue by diego-vasarelli** [electron/electron#7446]
* Electron version: 1.4.2
* Operating system: Linux 4.4.22-1-MANJARO

I'm starting now with electron and I have issue with standard navigation inside app.

What I want to do is to click to a button and open a new windows with preferences to set.
I can open the new windows but when I close it my application si blocked, this means that the button I pressed can not be pressed again, it remains "clicked" and the main application render not works, i.e. when I resize the app its content remain blocked to the previuose size (before click the button all works fine).

My code:

**index.js**

```javascript
const {app, BrowserWindow, ipcMain} = require('electron');

//settings windows
settings = new BrowserWindow(
{
width: 400,
height: 400,
show: false
})
settings.setMenu(null);

//content
settings.loadURL("file://" + __dirname + "/settings.html")
settings.webContents.openDevTools()

ipcMain.on('show_settings', function(){
settings.show();
});
ipcMain.on('hide_settings', function(){
settings.close();
//tried also settings.hide(),same problem 
});
```
_Open Settings window_
**index.html**
```html
...
<script>require('./js/LIndex.js')</script>
...
<button id="settings" class="btn btn-default">
     <span class="icon icon-key"></span>
</button>
```
**LIndex.js**
```javascript
const {ipcRenderer} = require('electron')

$(document).ready(function(){
    $('#settings').on('click',function(){
        ipcRenderer.sendSync('show_settings', null);
        });
})
```

_Close Settings Window_
**setting.html**
```html
...
<script>require('./js/settings.js')</script>
...
<button id="cancel" class="btn btn-default">
Cancel
</button>
<button id="save" class="btn btn-primary pull-right">
Save
</button>
```

**setting.js**
```javascript
const {ipcRenderer} = require('electron')

$(document).ready(function(){
    $('#save').on('click',function(){
        save()
        });
    $('#cancel').on('click',function(){
        cancel()
        });
        
})

function save(){
    ipcRenderer.sendSync('hide_settings', null);
}

function cancel(){
    ipcRenderer.sendSync('hide_settings', null);
}
```

Thanks in advance for your help

**Comment by diego-vasarelli** [comment]
Solved changing sendSync with simple send.
Maybe main app was waiting for a response from setting window

**Comment by MarshallOfSound** [comment]
@diego-vasarelli As per the documentation of `sendSync`

http://electron.atom.io/docs/api/ipc-renderer/#ipcrenderersendsyncchannel-arg1-arg2-

>  Sending a synchronous message will block the whole renderer process, unless you know what you are doing you should never use it.

You need to set `event.returnValue` in the main process, but you should never really use `sendSync`, it's quite dangerous
