### ISSUE TITLE
app.getLoginItemSettings() hangs when network drive disconnected

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#7447]
* Electron version: 1.4.1
* Operating system: osx el capitan

On osx if you have a network drive setup to connect on system launch that fails to connect, then call app.getLoginItemSettings() in an electron app it waits for osx to timeout connecting (approx a minute or so) before returning. To reproduce...

1.) Follow the steps described in the tutorial [here](https://www.tekrevue.com/tip/automatically-connect-network-drive/) to connect a network drive on boot
2.) Restart your machine
3.) Connect to a different wifi network or make the drive unavailable
4.) Launch an electron app calling `app.getLoginItemSettings()`. If you wait the whole time for osx to decide that it can't connect a dialog shows up informing you that it was unable to connect.

**Comment by zcbenz** [comment]
The `app.getLoginItemSettings` is just calling into the APIs provided by OS X, I'm afraid there is no way to implement this API while not affected by OS X's bug, so I'm closing this as won't fix.

**Comment by Thomas101** [comment]
Okay, thanks for looking into this!
