### ISSUE TITLE
Frameless transparent window on OSX draws OS shadow after receiving focus

### ISSUE THREAD

**Issue by brumm** [electron/electron#7448]
* Electron version: 1.4.2
* Operating system: OSX 10.11.6

Using the settings below for `BrowserWindow`, I'm getting an initially shadowless transparent window, which starts drawing a shadow after receiving focus.

The shadow seems to be drawn around opaque areas of the window and appears to stay behind after the content of the broser window changes, with some intermittent redraws.

Also, the default window border radius seems to still be present on a transparent window, even when the shadow is not visible.

```js
  win = new BrowserWindow({
    width: 300,
    height: 250,
    frame: false,
    transparent: true
  })
```

![transparent](https://cloud.githubusercontent.com/assets/170500/19020530/6f809c52-88ab-11e6-81a9-0415922b74d1.gif)

**Comment by lukeapage** [comment]
related: https://github.com/electron/electron/issues/6232#issuecomment-228499924

**Comment by brumm** [comment]
I had no idea that existed, thanks @lukeapage!
