### ISSUE TITLE
Frameless window still draggable

### ISSUE THREAD

**Issue by heaversm** [electron/electron#7454]
- Electron version: v 1.4.2
- Electron prebuilt: v 1.4.2
- Electron packager v7.7
- Operating system: Windows 10

Frameless window still able to be dragged by touching the very edge of the app screen. 

Am building the window with:

```
  mainWindow = new BrowserWindow({
    "width" : width,
    "height": height,
    "frame" : false,
    "web-preferences" : {
        "web-security"            : false,
        "overlay-fullscreen-video": true,
        "webaudio"                : true,
        "webgl"                   : true,
        "text-areas-are-resizable": true,
        "blinkFeatures" : "Accelerated2dCanvas, ExperimentalCanvasFeatures,FrameTimingSupport, SlimmingPaintV2, SpeculativeLaunchServiceWorker" 
    }
  })
```

Have additionally added a `-webkit-app-region: no-drag` to the body tag.

[Here is a video of the issue occurring](https://nike.app.box.com/s/r27jqr0rmg5pr3e4dhg7isdcatc28h1f)

Any other ideas that I can try to fix this? Could it be a windows issue?

**Comment by jamesa** [comment]
It looks to me that you're not dragging the window, but resizing it? Have you tried `resizable: false`?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
