### ISSUE TITLE
setZoomLevel doesn't actually scale correct zoom proportion.

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#7458]
* Electron version: 1.3.4
* Operating system: macOS Sierra

I've got completely incorrect coords for context menu event when app is zoomed in or out.
Tried to make click in right bottom corner, and get click position from event. This coords will represent approximate document size.

Without zoom have size app: 1625x1005 and with click coords all fine
With zoom 1: ~1340x830 and it's almost 82% for x coord and 80% for y coord 
With zoom 3: ~935x572 and it's almost 57% for x coord and  56% for y coord
With zoom -2: ~2135x1330 and it's almost 130% for x coord and 129% for y coord

In spec we have: **webFrame.setZoomLevel(level)**: Changes the zoom level to the specified level. The original size is 0 and each increment above or below represents zooming 20% larger or smaller to default

So document size will be: default size * (1 - zoomLevel * 0.2)

I should have with zoom 1: 1300x804
I should have with zoom 3: 650x402
I should have with zoom -2: 2275x1407

**Comment by andymartinwork** [comment]
After doing some investigation due to this bug: #6958 Webview zoomFactor reset on navigate, I found this issue too. getZoomFactor reports the "wrong" factor, but it's probably more likely that setZoomLevel is setting the wrong level.

**Comment by zcbenz** [comment]
The `setZoomLevel` API is just simply wrapper of `blink`'s `WebView::setZoomLevel` call, so we have no control of how it behaves, and from [its interface](https://cs.chromium.org/chromium/src/third_party/WebKit/public/web/WebView.h?q=setZoomLevel&sq=package:chromium&dr=CSs&l=250) there is no definition of how it should behave.

I suggest seeking help from [the blink-dev mailing list](https://groups.google.com/a/chromium.org/forum/#!forum/blink-dev) on the behavior of setZoomLevel.
