### ISSUE TITLE
Support for headphones play/pause shortcuts

### ISSUE THREAD

**Issue by pkpk2122** [electron/electron#7459]
* Electron version: 1.2.7
* Operating system: macOS Sierre

Hello,
There is support usually for keyboard play/pause global shortcuts, but for example pressing play from Apple Earpods play/pause button, triggers iTunes and cannot be registered from an Electron app.

Are there plans for these shortcuts to be supported by Electron's Global Shortcut Module ? 

Thanks.

**Comment by MarshallOfSound** [comment]
> Are there plans for these shortcuts to be supported by Electron's Global Shortcut Module ?

Can't speak to that really, don't think anyone has plans at the moment :+1: 

As for the actual implementation, I looked into this a long time ago and basically Apple make it very difficult to listen for those headphone button presses.  People normally use hacky workarounds like this https://github.com/Daij-Djan/DDHidLib

In fact I'm pretty sure that even apps like VLC and Spotify (which are built for native) don't integrate with those headphone buttons.  Community posts like [this one](https://community.spotify.com/t5/Live-Ideas/Support-for-the-headphone-play-pause-skip-buttons-Desktop/idi-p/78317) seem to confirm that.

Someone else might know some cool way of listening for these keys that I've never heard of, but I wouldn't hold any hope :cry:

**Comment by zcbenz** [comment]
Clearly Apple doesn't want to have any app except for iTunes to take the control of media keys, so I'm closing this as won't fix.
