### ISSUE TITLE
Casting to NSView* from getNativeWindowHandle()

### ISSUE THREAD

**Issue by arkenthera** [electron/electron#7460]
* Electron version: 1.4.2 x64
* Operating system: OSX Yosemite 10.10

I've been trying to get ```NSView*``` from ```getNativeWindowHandle()``` in a C++ addon, as the docs suggest the handle is ```NSView*``` on MacOS, but with no luck, I've been getting seg faults. I've seen #4369 and thought maybe the pointer returned on Mac is invalid too ? If someone did this successfully, I'd like to know how you can retrieve ```NSView*``` from ```getNativeWindowHandle()```.

Here is my code

Nodejs
```
require('some-native-module').test(browserWindow.getNativeWindowHandle())
```

C++ (compiled against electron, x64)
```
v8::Local<v8::Object> bufferObj = info[0].As<v8::Object>();	
unsigned char* bufferData = (unsigned char*)node::Buffer::Data(bufferObj);

NSView* view = reinterpret_cast<NSView*>(bufferData);

//Seg fault if you try to do anything with the NSView*
```
I've converted the buffer to hex using ```toString('hex')``` and then print hex on C++ side to verify that they are the same.

```
NSData *dataData = [NSData dataWithBytes:bufferData length:sizeof(bufferData)];
NSLog(@"%@",dataData);
```

```NSLog``` prints ```2016-10-03 03:40:33.734 node[1816:18569] <50255153 e07f0000>```,
and the developer console when you type ```require('electron').remote.getCurrentWindow().getNativeWindowHandle().toString('hex')``` prints ```50255153e07f0000```.

The same code for Windows works.

```
unsigned long handle = *reinterpret_cast<unsigned long*>(bufferData);
HWND hwnd = (HWND)handle;  //Valid
```

I'm thinking that casting to NSView* is problem,rather than the char* buffer returned from ```node::Buffer::Data```. Did anyone succesfully do this before?

**Comment by zcbenz** [comment]
I think it should be `NSView* view = *reinterpret_cast<NSView**>(bufferData)`.

**Comment by Qix-** [comment]
Sorry to necro but this doesn't work. The following test code compiles fine but segfaults.

`module/binding.gyp`

```
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "hello.mm" ],
      "include_dirs" : [
        "<!(node -e \"require('nan')\")"
      ],
      "conditions": [
        ['OS=="mac"',
          {
            'defines': [
              '__MACOSX_CORE__'
            ],
            'link_settings': {
                'libraries': [
                  '-framework CoreAudio',
                  '-framework CoreFoundation',
                ]
            },
            'xcode_settings': {
                'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
                'CLANG_CXX_LIBRARY': 'libc++',

                'OTHER_CFLAGS': [
                  '-ObjC++',
                  '-std=c++11'
                ],
            },
          }
        ],
      ],
    }
  ]
}
```

`module/hello.mm`

```objc
#include <nan.h>
#include <string>

#import <CoreFoundation/CoreFoundation.h>
#import <Cocoa/Cocoa.h>

using namespace Nan;
using namespace v8;
using namespace std;

NAN_METHOD(getTitle) {
	string result;
	NSString *title = NULL;

	v8::Local<v8::Object> bufferObj = info[0].As<v8::Object>(); 
	unsigned char* bufferData = (unsigned char*)node::Buffer::Data(bufferObj);

	// NSView *view = reinterpret_cast<NSView*>(bufferData);
	NSView *view = *reinterpret_cast<NSView**>(bufferData);

	NSWindow *win = [view window];
	if (win == NULL) goto set_ret;

	title = [win title];
	if (title == NULL) goto set_ret;

	result = [title UTF8String];

set_ret:
	info.GetReturnValue().Set(New<String>(result).ToLocalChecked());
}

NAN_MODULE_INIT(Init) {
	Nan::Set(target, New<String>("getTitle").ToLocalChecked(),
		GetFunction(New<FunctionTemplate>(getTitle)).ToLocalChecked());
}

NODE_MODULE(buffer_example, Init)
```

`module/index.js`

```javascript
const addon = require('./build/Release/addon');

module.exports = addon.getTitle;
```

`app/index.html`
```html
<!doctype html>
<html>
	<body>
		<div id="output"></div>
		<script>
			const getTitle = require('test-native');
			const remote = require('electron').remote;
			const update = () => {
				const handle = remote.getCurrentWindow().getNativeWindowHandle();
				const title = getTitle(handle);
				document.body.querySelector('#output').innerHTML = `<strong>title:</strong> ${title}`;
			};
			setTimeout(update, 100);
		</script>
	</body>
</html>
```

Note that everything works if I short-circuit the C++ function by setting the `result` and jumping to `set_ret` (meaning the result shows up in the HTML view).

How is anyone getting this to work?

**Comment by arkenthera** [comment]
I always thought like if we are creating a `BrowserWindow` on the main process' js file, then the actual pointer address will be in main process as well, thus calling it obvious.

**Comment by Qix-** [comment]
@arkenthera but like I said, it's not obvious - because that's not how pointers work. The window belongs to the child process, so referencing the window handle by pointer in the parent process shouldn't work since the window isn't in the parent process.

There's some other sort of IPC going on here.

**Comment by Lijian1122** [comment]
Hi, Has the problem been solved? If so, could you please tell me how it was solved? Thank you very much. I am looking forward for your reply.

**Comment by nornagon** [comment]
If using a module like `objc`, see https://github.com/lukaskollmer/objc/issues/16#issuecomment-1012457028:

```js
const handle = mainWindow.getNativeWindowHandle().readPointer()
const nsview = objc.wrap(handle)
nsview.window().invalidateShadow()
```

**Comment by BB-fat** [comment]
This is my solution.
```
// ts
const handle = window.getNativeWindowHandle();
testNativeWindow(handle);

// mm
auto buffer = info[0].As<Napi::Buffer<uint8_t>>();
void **handle = reinterpret_cast<void **>(buffer);
NSView* electronView = (__bridge NSView *)*handle;
```

**Comment by ZeroMax-dev** [comment]
@BB-fat Your solution gives me an `error: reinterpret_cast from 'Napi::Buffer<unsigned char>' to 'void **' is not allowed`.

In the meantime I managed with a lot of try and error to produce a solution, that works!

```
Napi::String GetWindowTitle(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  NSView** viewp = reinterpret_cast<NSView**>(info[0].As<Napi::Buffer<NSView**>>().Data());
  NSView* view = *viewp;
  NSWindow* window = [view window];
  NSString* title = [window title];
  return Napi::String::New(env, [title UTF8String]);
}
```
It should return the title of your BrowserWindow:
`console.log( nativeAddon.GetWindowTitle(window.getNativeWindowHandle()) );`

**Comment by lockieluke** [comment]
i'm trying to pass the C++ value to Swift
