### ISSUE TITLE
shadow did not adjust content with transparent=true when use setSize in macOS

### ISSUE THREAD

**Issue by catalsdevelop** [electron/electron#7462]
- Electron version: v1.4.0
- Operating system: mac os 10.11.6

when init a browserWindow with {hasShadow:true,transparent:true} config ,it worked fine.but after i set the window size , the shadow remains in default position, unless i use cmd+tab to switch the app in/out.

**Comment by catalsdevelop** [comment]
does this bug fixed

**Comment by chemzqm** [comment]
I have the same on Mac, disable hasShaow works.
![2016-11-21 23_51_51](https://cloud.githubusercontent.com/assets/251450/20490136/daabd60e-b047-11e6-98af-3e5d16099b78.gif)

**Comment by LeonBlade** [comment]
This bug is still in the game, for those that want a fix, you can respond to the `resize` event on your window and disable the shadow again.
```js
win.on('resize', () => {
    win.setHasShadow(false);
});
```

Here's an example of before and after resize:
![Before](http://i.imgur.com/dCK3pIB.png)
![After](http://i.imgur.com/SCH6ldu.png)

**Comment by sofianguy** [comment]
Thanks for contributing!

We are no longer releasing bug fixes for versions of Electron older than 1.6x. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.
