### ISSUE TITLE
After running electron packager Cannot find module 'file-encryptor' 

### ISSUE THREAD

**Issue by SameerKhan1406** [electron/electron#7463]
* Electron version:
* Operating system:

downloaded crypto module ,file-encryptor module and fs module
var encryptor = require('file-encryptor');
cleared and cleaned cache from my folder also globally -g then cloned cache of file-encryptor again and added cache using github cloned link still this error is popping when i create package but before creating it is working absolutely fine.

And my node modules is visible after creating package

**Comment by MarshallOfSound** [comment]
Electron Packager issues should be raised over at their repository

https://github.com/electron-userland/electron-packager

FWIW `electron-packager` recently defaults the `prune` option to `true` so unless you use the `--save` option when installing your dependencies they will not be present in the packaged version

**Comment by SameerKhan1406** [comment]
Thanks working fine.

**Comment by SameerKhan1406** [comment]
Just to clear doubts : i am installing any package locally to the target root folder then that package shows its dependencies in package.json file  but if i install it globally then it does not and every time i run something it shows that package not found in case of global installation. What is the problem and if it is so then what is the use of global installation and when do we need to install global packages

**Comment by MarshallOfSound** [comment]
@SameerKhan1406 
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW global modules are normally only used for CLI tools such as `gulp` or `grunt` where you want an executable to be available globally.

**Comment by SameerKhan1406** [comment]
Slack channel is Busy. Its showing "Reconnecting" all the time.
I have to call a function on closing the app then where to call and how to do it. #electron #atom

**Comment by MarshallOfSound** [comment]
http://electron.atom.io/docs/api/app/#event-will-quit

```js
app.on('will-quit', doThing)
```

**Comment by SameerKhan1406** [comment]
```
var filepath=app.getPath('home')+'/Desktop/video/count/';
	var str = "";
	var str1="";
	var txtFile = new File(["0"],filepath+'cnt', {type: "text/plain"});
```
It does nothing not even throw an error 
I want to create a file and read and write it.
I think the file creation has some issue with electron
P.S- Last line of the above code

**Comment by SameerKhan1406** [comment]
Can we use function of my js file to main.js i want some value to verify in my main window
