### ISSUE TITLE
Check if retina screen

### ISSUE THREAD

**Issue by turshija** [electron/electron#7464]
* Electron version: v1.4.2
* Operating system: MacOS

Is there possibility to check if current display is retina or not (pixel ratio > 1)? I'm rewriting an application from nwjs to Electron, and only thing I'm missing is that. Basically, my application needs to do something if it detects retina screen, so I would need to check that programmatically. In nwjs, I checked if current screen is retina using this function, but I can't use `window` in Electron:

```
isRetinaDisplay: function() {
    if (window.matchMedia) {
      var mq = window.matchMedia("only screen and (min--moz-device-pixel-ratio: 1.3), only screen and (-o-min-device-pixel-ratio: 2.6/2), only screen and (-webkit-min-device-pixel-ratio: 1.3), only screen  and (min-device-pixel-ratio: 1.3), only screen and (min-resolution: 1.3dppx)");
      return (mq && mq.matches || (window.devicePixelRatio > 1));
    }
  }
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW:
You are probably looking for the [`screen`](http://electron.atom.io/docs/api/screen/) API.  Check out the `scaleFactor` property on the display object.
