### ISSUE TITLE
Mouse down to iframe causes selecting all contents of the iframe

### ISSUE THREAD

**Issue by Rokt33r** [electron/electron#7465]
* Electron version: v1.3.6, 1.4.2
* Operating system: OS X

As soon as I click, all contents of iframe is selected. It blocks dragging.

<img width="360" alt="screen shot 2016-10-03 at 9 46 22 pm" src="https://cloud.githubusercontent.com/assets/5865853/19037751/d9f055fc-89b2-11e6-9fff-1e5ce2c34ca5.png">

It works fine on v1.2.8.

**Comment by zcbenz** [comment]
This is a bug of Chrome browser, you can wait for a Chrome upgrade in Electron to see whether it fixes this, or report this to [Chromium's issues list](https://crbug.com).
