### ISSUE TITLE
app.dock.show() is noop on macOS Sierra

### ISSUE THREAD

**Issue by erikcw** [electron/electron#7466]
* Electron version:
1.4.2

* Operating system:
macOS Sierra

So I executed `app.dock.hide()` which worked as expected.  Now I'm trying to turn the dock icon back on and `app.dock.show()` isn’t doing anything other than to toggle `app.dock.isVisible() == true`.  The dock icon is nowhere to be found.

I've tried cleaning my environment with the following to no avail.

```sh
rm -rf node_modules
npm cache clean
npm i
npm rb
npm run dev
```

**Comment by kevinsawicki** [comment]
Having a little trouble reproducing this, if I start the default Electron app and then open the dev tools and run the following from the Console tab:

```js
require('electron').remote.app.dock.hide()
```

I see the dock icon disappear, then running:

```js
require('electron').remote.app.dock.show()
```

does bring it back in the dock.

Can you try the same?

**Comment by erikcw** [comment]
Using `electron-quick-start`

The sample app launches, but the dock icon doesn't show up and of course neither does the icon in the fast app switcher (`Cmd+tab`).

Here is the output from my terminal:

```sh
 electron-quick-start@1.0.0 start /private/tmp/electron-quick-start
> electron .

/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 5
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 6
```

So, it appears that Electron is globally stuck in a no-dock-icon state on my machine.

**Comment by erikcw** [comment]
The only related issue I've been able to find from that terminal output is:

https://github.com/rhysd/NyaoVim/issues/84

**Comment by erikcw** [comment]
One more datapoint -- from within the electron-quick-start app -- I'm not able to type into the Dev Console.  It's as if I'm not really getting focus on the text area, even though the cursor is blinking and I can drag the window around.

**Comment by erikcw** [comment]
After restarting my machine.  I'm able to show/hide the dock icon and use my keyboard in the app while the dock icon is hidden.  Progress!

**Comment by kevinsawicki** [comment]
> After restarting my machine. I'm able to show/hide the dock icon and use my keyboard in the app while the dock icon is hidden.

Closing this out for now then, please comment if you are able to reproduce this again.
