### ISSUE TITLE
Accelerator for Tab key has stopped working on OS X

### ISSUE THREAD

**Issue by purplemass** [electron/electron#7467]
* Electron version: 1.4.0
* Operating system: OS X 10.10.5

I've been using the following code to send Tab key events to a webview in my project:

```js
const webContents = webView.getWebContents();
const keyEvent = {
  type: 'keyDown',
  keyCode: 'Tab'
};

webContents.sendInputEvent(keyEvent);
```
I have had no issues with this until the recent update to 1.4.0.

The last version the above code works in OS X is **1.3.7**. I've tried this with the latest versions of Electron (1.4.1 & 1.4.2) with the same results.

Am I doing something wrong here? Is this a known issue?

**Comment by kevinsawicki** [comment]
> Am I doing something wrong here? Is this a known issue?

I've not seen this issue come up before, I'm having a little trouble reproducing it on macOS 10.11.6.

Here is my sample page:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style>
      webview {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0
      }
    </style>
  </head>
  <body>
    <webview src="https://googlechrome.github.io/samples/keyboardevent-code-attribute/" />
  </body>
</html>
```

If I then open the dev tools and run:

```js
document.querySelector('webview').getWebContents().sendInputEvent({ type: 'keyDown', keyCode: 'Tab'})
```

I do see a message get logged by the page.

Is it only the `Tab` key that isn't working for you? Is your page not receiving the event or is the event data just wrong/incomplete?

**Comment by purplemass** [comment]
@kevinsawicki thanks for your reply.

> Is it only the Tab key that isn't working for you? Is your page not receiving the event or is the event data just wrong/incomplete?

Yes, it's only the tab key. The page does receive a keyboard event as expected but `keyCode: 'Tab'` seems to be ignored in 1.4.0 and above.

Basically, I have an on-screen QWERTY keyboard which allows users to input their info into 2 input fields. All keys work as expected in Electron 1.4.2 except the tab key. In 1.3.7, the tab key works.

In my project, the tab key should mimic the tab key on the physical keyboard to set the focus from one field to the next.

Taking queues from your response, I've put together a simple test to demonstrate this:

```js
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style>
      webview {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0
      }
    </style>
  </head>
  <body>
    <webview src="http://purplemass.com/temp/electron-test.html" />
    <script>
    webView = document.querySelector('webview');

    webView.addEventListener("dom-ready", function(event) {
      // webView.openDevTools();
      webViewContent = webView.getWebContents();

      webViewContent.sendInputEvent({ type: 'char', keyCode: 'A'});
      webViewContent.sendInputEvent({ type: 'char', keyCode: 'B'});

      webViewContent.sendInputEvent({ type: 'keyDown', keyCode: 'Tab'});
      webViewContent.sendInputEvent({ type: 'char', keyCode: ''});

      webViewContent.sendInputEvent({ type: 'char', keyCode: 'C'});
      webViewContent.sendInputEvent({ type: 'char', keyCode: 'D'});
      webViewContent.sendInputEvent({ type: 'char', keyCode: 'E'});

      webViewContent.sendInputEvent({ type: 'keyDown', keyCode: 'Backspace'});
    });

    </script>
  </body>
</html>
```

The above code puts **AB** into **input1** and **CD** into **input2** in Electron 1.3.7.

In 1.4.2, I get **ABCD** in **input1**.

It's interesting to note that when a key is pressed on a physical keyboard, the keyboard event contains `event.key`, `event.code` and `event.keyCode`. Using Electron's `sendInputEvent`, `event.key` and `event.code` are empty but I think this is the expected behaviour.

**Comment by kevinsawicki** [comment]
> Taking cues from your response, I've put together a simple test to demonstrate this:

Thanks so much for this example, can reproduce it now like you reported 👍 

> It's interesting to note that when a key is pressed on a physical keyboard, the keyboard event contains event.key, event.code and event.keyCode. Using Electron's sendInputEvent, event.key and event.code are empty but I think this is the expected behaviour.

I think this might be the issue, perhaps the recent Chrome upgrade caused this to stop working because the event generated by `sendInputEvent` don't have the key and code set on them.

If I set those fields locally on master then I do see your example working as it did in 1.3.7 which is good.

**Comment by kevinsawicki** [comment]
@purplemass I've pushed up a branch named `key-and-code-on-sent-input-events` that updates these values on the events, would you be able to build and try it out and see if it works as expected for your usage?

**Comment by purplemass** [comment]
@kevinsawicki thanks so much for looking into this and issuing a fix.

I've never built Electron on OSX before - doing that now but there are some very large dependencies (>2.5GB) which are being downloaded from S3. I'll get back to you with the results if the build is successful.

**Comment by purplemass** [comment]
@kevinsawicki I can confirm that your fix in the `key-and-code-on-sent-input-events` branch works as expected and the tab key behaves correctly.

The `key` and `code` parts of the event are also sent in this version.
