### ISSUE TITLE
Electron app doesn't support High Contrast mode

### ISSUE THREAD

**Issue by nishant09** [electron/electron#7469]
Electron version: 0.34
Operating system: windows, mac osx and linux

I noticed when I turn on the High Contrast mode, my electron app doesn't react accordingly. Has it been the issue in the older version ?  

We are going to adopt the 1.3.3 version soon. Has this issue been resolved in the newer version?

Is there any app out in the market(you're aware of) which is using the latest version of electron. I would like to do some accessibility testing. 

Thanks !

**Comment by kevinsawicki** [comment]
> I noticed when I turn on the High Contrast mode, my electron app doesn't react accordingly.

If you use Chrome, do you see the same behavior?

**Comment by nishant09** [comment]
Yes it's a same behavior.

**Comment by kevinsawicki** [comment]
> Yes it's a same behavior.

You can probably expect Electron to be the same then. Do you know of any browser or browser-based apps that support the behavior you are looking for?

**Comment by nishant09** [comment]
Microsoft Edge .. It works perfectly fine with High Contrast mode

**Comment by kevinsawicki** [comment]
> Microsoft Edge .. It works perfectly fine with High Contrast mode

What about on macOS and Linux?

**Comment by nishant09** [comment]
Electron doesn't support High contrast on them as well

**Comment by nishant09** [comment]
So it looks like not even the latest version of Electron supports High Contrast mode, correct ?

Are you guys planning to fix this issue ?

**Comment by kevinsawicki** [comment]
> I noticed when I turn on the High Contrast mode, my electron app doesn't react accordingly.

Which part of your app isn't reacting?

When I use `High Contrast #1` theme on Windows 10, I do see the window frame and menus react:

<img width="610" alt="screen shot 2016-10-06 at 2 58 15 pm" src="https://cloud.githubusercontent.com/assets/671378/19172202/718f96f6-8bd5-11e6-949b-307ee81c9254.png">

All the other content on your page won't restyle unless you deliberately restyle it yourself since you control your app's styles.

You could explore using/including this extension with your app to provide this functionality.

**Comment by kevinsawicki** [comment]
I've opened a pull request to add an Electron API to check if high contrast mode is enabled in #7518

**Comment by nishant09** [comment]
I do see the exact same behavior. I wasn't aware that the other content of my app won't restyle unless I style them with CSS.

I'm thinking of enabling high contrast from the menu. not depending on windows high contrast mode.

**Comment by MarshallOfSound** [comment]
@nishant09 There is a sneaky trick you can do to get a "high contrast mode" working in CSS.

```css
html {
  -webkit-filter: invert(1);
}
```

**Comment by nishant09** [comment]
@MarshallOfSound Thank you amigo. this will help
