### ISSUE TITLE
window.confirm does not work in sandbox mode

### ISSUE THREAD

**Issue by sltam** [electron/electron#7472]
* Electron version: 1.4.2
* Operating system: macOS 10.12

As titled; the function succeeds but nothing happened.

It works again as long as I switched off `sandbox` in `webPreferences`.

**Comment by kevinsawicki** [comment]
@tarruda :wave: is this expected behavior?

**Comment by tarruda** [comment]
I think `window.confirm` must have a callback in the browser process, similar to `CanCreateWindow`. For non-sandboxed windows, `window.confirm` is implemented in `lib/renderer/override.js`, which is not used by sandboxed renderers yet(see #6712 for progress on this)

**Comment by zcbenz** [comment]
I'm merging this to #6712.
