### ISSUE TITLE
onbeforeunload still blocks window closing if `event.returnValue = undefined`

### ISSUE THREAD

**Issue by sltam** [electron/electron#7473]
* Electron version: 1.4.2
* Operating system: macOS 10.12

Unlike what spec (at `spec/api-browser-window-spec.js`) wants to imply, setting `e.returnValue = undefined` is not an no-op (i.e. allow window to close).

onbeforeunload.html
```
<script>
window.addEventListener('beforeunload', (e) => e.returnValue = undefined)
window.close()
</script>
```

index.js
```
const { BrowserWindow, app } = require('electron')
app.on('ready', () => {
    win = new BrowserWindow()
    win.loadURL(`file://${__dirname}/onbeforeunload.html`)
})
```

**Comment by deepak1556** [comment]
setting `e.returnValue = undefined` will just convert it to string `"undefined"`and hence it blocks. Closing this out since its working as expected.

**Comment by sltam** [comment]
@deepak1556 Can we better document the behavior of `onbeforeunload` in the [docs] (http://electron.atom.io/docs/api/browser-window/)? Unlike what the originator of #2579 wanted to claim, I can't find anywhere mentioning that the behavior is different from what browsers usually do (they are inconsistent anyway), and hence I went on to read the [spec](https://github.com/electron/electron/blob/787bc8570382e98c4f204abff05b2af122e5a422/spec/api-browser-window-spec.js), but then they aren't indicative (say nowhere mentions the conversion-to-string you described).

**Comment by deepak1556** [comment]
I am good documenting it.

> hence I went on to read the spec, but then they aren't indicative (say nowhere mentions the conversion-to-string you described).

According to the [spec](https://html.spec.whatwg.org/multipage/browsers.html#beforeunloadevent) `onbeforeunload` returnValue is a `DOMString`. You can find more info about how blink handles webIdl types [here](https://www.chromium.org/blink/webidl). Specifically look at the `undefined and null` section.
