### ISSUE TITLE
Crash Reporter submits crash report with only minidump and no data

### ISSUE THREAD

**Issue by ramya-rao-a** [electron/electron#7474]
- Electron version: 0.37.6
- Operating system: Mac OS X

The crash reporter works well for our product in Windows and Linux.
But in Mac OS X, apart from the usual crash reports, we are seeing quite a few getting submitted with just the minidump and no other data (neither the default ones nor the extra). 

Has anyone seen such a case? 

The crash report submission is successful, which leads me to believe that crashReporter.start() was successful, as that is how the crashReporter could have gotten the submitUrl.
But why none of the other data failed to pass through is the question.

Apologies, if this is not the right place for questions on the electron crash reporter behaviors.

**Comment by kevinsawicki** [comment]
> Electron version: 0.37.6

This is quite an old version of Electron, are you able to reproduce it as well on the latest release, 1.4.2?

**Comment by ramya-rao-a** [comment]
We only recently upgraded to 1.3.7 It would still take a week or 2 for most of our users to upgrade as well. 
I can circle back to this thread by then with the numbers we see.

I was curious to see if anyone else had seen similar issues.

**Comment by kevinsawicki** [comment]
> I can circle back to this thread by then with the numbers we see.

Sounds good, I'm going to close this out until more information is available then. If you still see this on newer versions, please comment here and include any reproduction steps you have as well and we can reopen this.

**Comment by fridgerator** [comment]
I am seeing this issue on MacOS Sierra.

I have a server listening for POST requests.  I see the request come through but it is empty, no request body or form data.

I was using Electron v1.3.5, updated to 1.4.5 and same issue.

Not doing anything special outside of the documentation:
```
var crashReportUrl = 'http://localhost:3001/crashreporter/report/';

crashReporter.start({
    productName: 'Test',
    companyName: 'Test Company',
    submitURL: crashReportUrl,
    autoSubmit: true,
})
```

**Comment by ramya-rao-a** [comment]
@kevinsawicki I have a repro!

https://github.com/ramya-rao-a/electron-quick-start/tree/crash-testing is a modified version of the `electron-quick-start` example. The main process creates 2 instances of BrowserWindow, thus creating 2 renderer processes. Crash Reporter is initialized in the main process. 

- First Window
Buttons are available to initialize crash reporter, create a crash and get last crash. 

- Second Window
Buttons to crash without initializing the crash reporter.

Steps
- On the first window, click on the button that initializes crash reporter, then click on "Crash"
- Crash Report gets submitted with crash dump, product and company info
- On the second window, click on the "Crash" button
- Crash Report gets submitted with crash dump only in Mac. No Crash report gets submitted in Windows.

Now according to the docs
>Note: On macOS, Electron uses a new crashpad client, which is different from breakpad on Windows and Linux. To enable the crash collection feature, you are required to call the crashReporter.start API to initialize crashpad in the main process and in each renderer process from which you wish to collect crash reports.

But looks like, crash reports get submitted (only the dump) on Mac but none on Windows when crash reporter is not initialized from each renderer process.

**Comment by ramya-rao-a** [comment]
@kevinsawicki I have an update.

In my example (https://github.com/ramya-rao-a/electron-quick-start/tree/crash-testing), I have changed the 3rd button from "Last Crash" to "Crash in a child process". Clicking on this will run a crashing C program.
This again results in the crash reporter sending just the dump in the crash report (without any other info) in Mac. In Windows, nothing is sent

I believe this might be the reason for the mysterious crashes we have been seeing.
Crash Reporter is initialized in all of our renderer processes. These renderer processes fork new process to do certain work. If the forked processes crash, then the electron crash reporter ends up submitting crash reports with just the dump and only in Mac

**Comment by ramya-rao-a** [comment]
Added 2 more examples
- Create a forked process from where the crashing C program is executed using child_process.exec
- Create a forked process that runs a native module which crashes.

Same results.
Mac - Just the crash dump is submitted in the crash report
Windows - Nothing

**Summary:**
Crashes in a process (electron and node both) where crash reporter is not initialized get reported with just the dump and no metadata in Mac. In Windows, such crashes are ignored.

We are particularly interested in the crashes in the node processes forked from a renderer process. We would like to send different metadata from such crashes so as to identify which of our process are crashing. And this should work across platforms.

Please let me know if I can help in any way

**Comment by fridgerator** [comment]
@ramya-rao-a did you mean to close this?

**Comment by ramya-rao-a** [comment]
@fridgerator Not at all, the issue is still open. We do need a fix where we can send metadata for crashes from child processes

**Comment by fridgerator** [comment]
@ramya-rao-a I was mistaken I thought the issue was closed.

**Comment by kevinsawicki** [comment]
@ramya-rao-a Thanks for all the great investigatory work, super super helpful. It seems like there are several issues that need to be addressed to get the crash reporter behavior consistent across platforms and to ideally support crashed forked processes.

Are you interested in working further on this and fixing this in core Electron?

**Comment by ramya-rao-a** [comment]
@kevinsawicki Sorry it took a while to get back.
Yes, I am interested in working on a fix for this in core Electron.

I created a separate issue #8045 for Mac using the submit-url from the main process to report crashes from the renderer process.

We can use the current issue to track crash reporting in forked process across platforms.
Is that ok?

I'll first start working on #8045.

**Comment by ramya-rao-a** [comment]
@kevinsawicki As you mentioned in the other issue, the below from the [docs](https://cs.chromium.org/chromium/src/third_party/crashpad/crashpad/client/crashpad_client.h?q=crashpad::CrashpadClient&sq=package:chromium&dr=Ss&l=57) explain the crashes being reported from the child processes in Mac

>Exception ports are inherited, so a Crashpad handler started here will remain the handler for any child processes created after StartHandler() is called. Child processes do not need to call StartHandler() or be aware of Crashpad in any way. 

We would want each child process to call `crashReporter.start()` to set up the module annotations (metadata) to be reported along with the crash. For this to happen, the electron API should be accessible by the child processes.

As far as I could gather there is no way for a node process to access electron APIs. Do you have any insights on this?

**Comment by MarshallOfSound** [comment]
@ramya-rao-a I've never tried this but theoretically you could set up your application to work like node does.  I.e. When it has a path to a JS file it runs that JS file.  Then instead of forking with `ELECTRON_RUN_AS_NODE` just spawn your executable with a path to your node JS script.  Then you have full Electron API access.

^^ Untested and may not work but it's an idea 😆

**Comment by ramya-rao-a** [comment]
@MarshallOfSound When you say "spawn your executable" do you mean spawn electron?

**Comment by bpasero** [comment]
I do not see how spawning a full blown electron helps in this case. Our use case is to specifically run node.js through electron and not spawn a full instance of electron.

**Comment by ramya-rao-a** [comment]
@bpasero True, using a full blown electron is an overkill for us, but looks like thats the only way to access electron apis at the moment.

This has been discussed a few times. See #6656 and #4520

Our scenario is to be able to use the `crashReporter` module from each of the child node processes.

What do you think about using a stripped down version of electron (with just the modules we want) to spawn the child processes?

**Comment by bpasero** [comment]
I know it might not be a popular topic but what about adding a module that is available from the node.js side? https://github.com/electron/electron/pull/7578/files demonstrates how new methods can be added to the node.js context easily. I would prefer such a solution over spawning electron. I do not see how spawning electron is actually possible for us, so I would not think this is a direction we should push forward.

**Comment by ramya-rao-a** [comment]
@bpasero That opens up a whole new world of possibilities!

@kevinsawicki Thoughts on @bpasero's idea? I see that you had worked on adding the `log` method to the node.js context.

**Comment by ramya-rao-a** [comment]
PR #8109  is the first draft of the fix based on @bpasero 's suggestion.

**Comment by kevinsawicki** [comment]
> Thoughts on @bpasero's idea? I see that you had worked on adding the log method to the node.js context.

Sorry for the delayed response, this pattern sounds good to me.

**Comment by gerges** [comment]
While this ticket is open, it seems like in the crashpad impl `reporter.id` is the entire response-body from the server, instead of `crash_id`

**Comment by kevinsawicki** [comment]
Closing this out, #8109  has been merged.
