### ISSUE TITLE
electron.app is undefined

### ISSUE THREAD

**Issue by thosakwe** [electron/electron#7475]
* Electron version: 1.4.2
* Operating system: Mac OSX El Capitan

Running the Quick Start, save for that I am requiring babel-register before running an ES6 app. 

main.js: 

```js
const {app, BrowserWindow} = require('electron');

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed.
app.on('window-all-closed', () => {
    // On macOS it is common for applications and their menu bar
    // to stay active until the user quits explicitly with Cmd + Q
    if (process.platform !== 'darwin') {
        app.quit()
    }
});

app.on('activate', () => {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (win === null) {
        createWindow()
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let win;

function createWindow () {
    // Create the browser window.
    win = new BrowserWindow({width: 800, height: 600});

    // and load the index.html of the app.
    win.loadURL(`file://${__dirname}/index.html`);

    // Open the DevTools.
    win.webContents.openDevTools();

    // Emitted when the window is closed.
    win.on('closed', () => {
        // Dereference the window object, usually you would store windows
        // in an array if your app supports multi windows, this is the time
        // when you should delete the corresponding element.
        win = null
    })
}
```

index.html:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Mystery Dungeon</title>
    <style>
        /* 0 margin so the canvas doesn't bleed over! */

        html, body {
            margin: 0;
        }
    </style>
</head>
<body>
<div id="game"></div>
<script src="src/browser.js"></script>
</body>
</html>
```

src/browser.js:

```js
import MyGame from './lib/game';
new MyGame();
//# sourceMappingURL=main.js.map
```

`./lib/game` is just a game written with Phaser.

### The Problem

I always get this error:

    Cannot read property 'on' of undefined

Not really sure what the cause of this is. I've read previous issues about this, but none worked for me. No, I do not have electron installed in any parent directory. Yes, I have tried `require.resolve('electron')` - it is being required from the correct location.

Thanks in advance.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW It sounds like you are running your application with `node main.js`.  This is incorrect, you should be running `electron main.js`

**Comment by thosakwe** [comment]
Ah, ok, I'll put it in the Slack next time.

However, I am running it via electron.

**Comment by MarshallOfSound** [comment]
@thosakwe Which version of Electron do have installed.  Can you `console.log(require('electron'))`

**Comment by thosakwe** [comment]
```
{ clipboard: [Getter],
  crashReporter: [Getter],
  nativeImage: [Getter],
  shell: [Getter],
  app: [Getter],
  autoUpdater: [Getter],
  BrowserWindow: [Getter],
  contentTracing: [Getter],
  dialog: [Getter],
  ipcMain: [Getter],
  globalShortcut: [Getter],
  Menu: [Getter],
  MenuItem: [Getter],
  powerMonitor: [Getter],
  powerSaveBlocker: [Getter],
  protocol: [Getter],
  screen: [Getter],
  session: [Getter],
  systemPreferences: [Getter],
  Tray: [Getter],
  webContents: [Getter] }
```

I figured out the problem. For some reason, the `main.js` file was being run twice - once by the main process, and one by the renderer. Is this supposed to happen?

Anyways, I wrapped most the `main.js` in a `if (app !== undefined)` and the error went away.

Just wondering why it was run twice, though...

**Comment by MarshallOfSound** [comment]
@thosakwe You must be `require`'ing it in your `index.html` somewhere.

**Comment by thosakwe** [comment]
I didn't see it there, but I honestly wouldn't be surprised if I had been doing it inadvertently.

Anyways, thanks for your help. I had the project setup with Webpack before as a normal Web app, so I'm just using it with webpack and not using require at all in my index anymore.

**Comment by baconface** [comment]
If I had to guess you are calling `main.js` in `package.json` under the `main` property and some other place in your codebase. I have seen this to be a typical issue with new Electron users. It should only be referenced once in your project. Otherwise this would cause it to be loaded twice.

**Comment by MikePelton** [comment]
This is the exact same problem I encountered - two references to main.js in launch.json. Since I was following the instructions to the letter I'm somewhat disappointed to have wasted two hours of my morning trying to get what's laughingly described as a quickstart working. Thanks for the suggestion here or I'd have given up.

**Comment by FabianTe** [comment]
@MikePelton Do you mean ```package.json```? I still cant find it :(

**Comment by ashish701ranjan** [comment]
I was having this same issue, I am using `nodemon` to watch changes to the bundle.

I had a script something like:

    "monitor:electron": "wait-on ./dist/main.js && nodemon --watch --exec electron ."

I later figured out that this was running : `node electron .`

It turned out that I was using the `--watch` flag incorrectly, nodemon by default would watch cuurent working directory, if a --watch flag is added then you need to mention the directory you want to watch or else you can omit the `watch` flag.

**Comment by jerson-arch** [comment]
I had the same problem when I wanted to implement nodemon, it got messed up by implementing this property to `"script"` 
in the File "`package.json`".
`"nodemon":"nodemon --exec electron main.js"`
(*) needs electron installed globally `npm i -D -g electron@latest`
