### ISSUE TITLE
Bootstrap script (update.py) throws error

### ISSUE THREAD

**Issue by jonathanGB** [electron/electron#7492]
* Electron version: 1.4.2
* Operating system: Windows 10

I ran `python script/bootstrap.py -v`, and at some point it calls a script called `update.py`, which throws the following error. 

```
C:\Python27\python.exe E:\Repos\electron\script\update.py
Download directxsdk-x64     1806291  [100.0%]
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'node' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'node ./tools/atom_source_root.js' returned exit status 1 while in electron.gyp.
None
Traceback (most recent call last):
  File ".\script\bootstrap.py", line 264, in <module>
    sys.exit(main())
  File ".\script\bootstrap.py", line 65, in main
    run_update(defines, args.msvs)
  File ".\script\bootstrap.py", line 260, in run_update
    execute_stdout(args)
  File "E:\Repos\electron\script\lib\util.py", line 180, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'E:\\Repos\\electron\\script\\update.py']' returned
 non-zero exit status 1
```

I need to mention that I have **MySQL** and **Node** available through the command-line (they are in my PATH), so I really don't understand why it does that. I deleted the *electron* repo and started the installation again, and the same problem ocured again.

**Comment by zcbenz** [comment]
The scripts of Electron never invoke anything like `MySQL`, please verify your own environment is valid.

**Comment by dusan-kovacik-profiq** [comment]
I had the same problem right now. To fix it, check your PATH environment variable and put all paths with some spaces into quotes.
