### ISSUE TITLE
Infinity loop in webview blocked parent BrowserWindow

### ISSUE THREAD

**Issue by uselec** [electron/electron#7504]
- Electron version: 1.4.2
- Operating system: win10 x64

Why some Infinity Loop (like `while(true)`) in `webview` with some (intensive ?) operations blocked parent `BrowserWindow`?

code in `webview`
`while(1) 1+1; // its okay`
but, example
`while(1) console.log(1) // parent BrowserWindow will be blocked`

If this loop execute in separate BrowserWindow, then everything works fine. Only in `webview` bug.

Also, in Chromium\Chrome its not blocked other tabs.

**Comment by zcbenz** [comment]
The webview is very tightly connected to its parent window, this is a design made in Chromium and we can not change that, I suggest reporting this to [Chromium's issues list](https://crbug.com) instead.

As for the tabs in Chrome, they are actually `BrowserWindow`s instead of `<webview>`s.
