### ISSUE TITLE
Uncaught ReferenceError: require is not defined when importing 'electron-json-storage'

### ISSUE THREAD

**Issue by matjanos** [electron/electron#7506]
* Electron version: 1.3.5
* Operating system: Windows 10 x64

I've created Electron app with typescript (+Angular2). I want to use `electron-json-storage` to persist user information, so I've imported this package in my app.

```
// Vendors
import 'jquery';
import 'bootstrap-loader';

// Angular 2
import '@angular/platform-browser-dynamic';
import '@angular/platform-browser';
import '@angular/core';
import '@angular/http';
import '@angular/router';

import 'electron-json-storage'

// RxJS 5
// import 'rxjs/Rx';

// For vendors for example jQuery, Lodash, angular2-jwt import them here
// Also see src/typings.d.ts as you also need to run `typings install x` where `x` is your module
```

I don't even need to use it anywhere, just import throws this error in runtime:
`Uncaught ReferenceError: require is not defined`

 I'm using WebPack for builing my app.

What can be a reason for that?

**Comment by MarshallOfSound** [comment]
If I had to guess you're using some form of packer (webpack maybe) that historically has caussed issues like this when configured incorrectly.

Can you provide a minimal application that reproduces the problem.

**Comment by matjanos** [comment]
please find following repository! This shows the problem.

[https://github.com/matjanos/electron-typescript-example](https://github.com/matjanos/electron-typescript-example)

**Comment by kevinsawicki** [comment]
> Uncaught ReferenceError: require is not defined

Your app has `nodeIntegration` disabled and that causes node's implementation of `require` to not be available in renderer processes. This is expected.

https://github.com/matjanos/electron-typescript-example/blob/b17d8799aef74ac1184f89199ff9a6bb246c2457/src/electron.ts#L21

Closing this out.

**Comment by calidion** [comment]
I have the same problem.
