### ISSUE TITLE
How to redirect stdin inside callback of makeSingleInstance

### ISSUE THREAD

**Issue by abnerlee** [electron/electron#7509]
* Electron version: 1.3.5
* Operating system: Linux

I want to make my Electron app a single instance, but if user create a new instance and input data via stdin, for example:

```sh
echo "test" | ./electron
```

Is it possible redirect the stdin to the existing instance?

**Comment by zcbenz** [comment]
No, currently there is no way to do that with `makeSingleInstance`. You can do that by using named socket to reimplement the single instance.
