### ISSUE TITLE
How to know which screen is displaying a BrowserWindow?

### ISSUE THREAD

**Issue by eladams** [electron/electron#7510]
* Electron version:1.41
* Operating system: OS X El Capitan

**Comment by levrik** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by levrik** [comment]
But to answer your question: Take a look at the [`screen`](http://electron.atom.io/docs/api/screen/) API.

**Comment by eladams** [comment]
Thank @levrik but I don't think it answer my question/feature request.
I thought about centering a window with animation (mac os only) using `BrowserWindow.setPosition(...)` but I couldn't find a way using the screen API to get screen that currently displays the specific browser window.

**Comment by levrik** [comment]
But what if you would pass the position and size of your browser window into [`screen.getDisplayMatching(rect)`](http://electron.atom.io/docs/api/screen/#screengetdisplaymatchingrect)? Or only the position into [`screen.getDisplayNearestPoint(point)`](http://electron.atom.io/docs/api/screen/#screengetdisplaynearestpointpoint)?

**Comment by enlight** [comment]
Thanks @levrik
Closing this out.
