### ISSUE TITLE
Symbols not found

### ISSUE THREAD

**Issue by bennyn** [electron/electron#7512]
* Electron version: 1.2.8
* Operating system: Windows 10 Home

Our Electron app (`Wire.exe`) crashed but symbols couldn't be loaded.

**Screenshot:**

![unbenannt](https://cloud.githubusercontent.com/assets/469989/19159758/ddf08e5a-8bed-11e6-9e5b-58af78d8e252.PNG)

**Comment by MarshallOfSound** [comment]
Have you loaded in the symbols that you download from the releases section

https://github.com/electron/electron/releases

The filename should be `electron-v1.4.3-${platform}-${arch}-symbols.zip`

Read more about debugging inside Electron [here](https://github.com/electron/electron/blob/master/docs/development/debug-instructions-windows.md)

**Comment by zcbenz** [comment]
The symbols uploading had been broken for sometime so a few old versions can not find symbols in the symbols server. You can solve this by downloading the PDB files from the Releases page.
