### ISSUE TITLE
The app is slow to load with >100kB js files

### ISSUE THREAD

**Issue by LrsNate** [electron/electron#7516]
* Electron version: 1.3.5
* Operating system: OS X El Capitan

Hi guys,

I'm developing an app with Webpack, which means I end up with a single 544 kB js file (that's the minified size).

The problem is, with a file of that size the app takes about 10s to load from a blank window to the app itself, and in the console I get that message:

```
[BABEL] Note: The code generator has deoptimised the styling of "/path/to/bundle.js" as it exceeds the max of "100KB". 
```

Is there any way around that? I'm already using babel through webpack so `bundle.js` should contain pure ES5 code.

Thanks,
Nate

-edit- Forgot to mention, that's only for the first time the file is loaded after having been modified. From the 2nd load onwards the app is has a normal loading time (<1s).

**Comment by kevinsawicki** [comment]
You should use the Dev Tools Profiler to investigate where the time is being spent on load, https://developer.chrome.com/devtools/docs/profiles

Profiling startup will let you know where the time is being spent. Without knowing where the time is spent, it is hard to know whether it is load time or the execution time of the file causing the slowdown in your case.

Electron has built-in [require](https://nodejs.org/api/modules.html) support so you aren't required to bundle your entire app into a single file, you can separate it into multiple files and load them as needed to get startup time down to a acceptable value.

I'm going to close this out here, you might want to check out the [Electron forums](https://discuss.atom.io/c/electron) for help as well.

**Comment by LrsNate** [comment]
I can't use the Dev Tools, let alone a profiler because the window is unresponsive during those 10 seconds.

Given the fact that the loading time is only long for the first time after the js file has been modified, it is very probably load time.

Also Electron doesn't support ES6 imports, which is why I'm using Webpack.

Are you seriously implying there is nothing wrong with Electron taking 10 seconds to load a 500kB script?

**Comment by kevinsawicki** [comment]
> Are you seriously implying there is nothing wrong with Electron taking 10 seconds to load a 500kB script?

Nope, I'm not saying that, I'm saying we need more information to investigate this issue further.

> I can't use the Dev Tools, let alone a profiler because the window is unresponsive during those 10 seconds.

You can open the dev tools before your page loads, then start the profiler, and then kick off loading your page, then once the page loads you can stop the profiler and it should update with the details.

How quickly does the page load in Chrome?

**Comment by baconface** [comment]
> Are you seriously implying there is nothing wrong with Electron taking 10 seconds to load a 500kB script?

I think this is a really unfair assessment of Electron's performance. Keep in mind you are not loading a minimal application compiled to native code. You are loading an application that loads Chromium and Node.js to load _your_ application. Expect a slight bottle neck that would be impossible to resolve.

And to echo @kevinsawicki, without knowledge of your code base there is really nothing to gauge the source of the issue. You can write severely unoptimized and memory intensive code in only a handful of lines. Which isn't a fault to Electron but could be at fault of how Chromium, Node.js or even V8 handles it.

**Comment by LrsNate** [comment]
Closing the issue right away is hardly how you'd show you want to investigate further.

I got the following error while profiling:

```
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError
```

Here is the long call:
```
7885.8 ms 85.64 % ipcRenderer.sendSync ipc-renderer.js:13
7885.8 ms 85.64 % exports.getGlobal remote.js:315
7885.8 ms 85.64 % initializeRendererProcess initialize-renderer.js:19
7885.8 ms 85.64 % (anonymous function) __magic__file__to__help__electron__compile.js:1
```

7558.8ms were spent on `ipc.Renderer.sendSync > exports.getGlobal > initializeRendererProcess > (anonymous function)`.

> How quickly does the page load in Chrome?

Instantly. It also loaded instantly when the app was written in ES5 with `require` calls, and the problem started after I migrated the code to ES6 modules and Webpack.

**Comment by MarshallOfSound** [comment]
@LrsNate What are you fetching with `getGlobal`?

It uses syncronous IPC communication and is generally a bad idea

**Comment by kevinsawicki** [comment]
> Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

No need to worry about this, it was fixed in #7413 and released in Electron 1.4.3

**Comment by LrsNate** [comment]
> @LrsNate What are you fetching with getGlobal?

I'm not making that call myself; my code on the electron side isn't much more than creating a `BrowserWindow` and calling `loadURL` on it.

**Comment by kevinsawicki** [comment]
> 7885.8 ms 85.64 % initializeRendererProcess initialize-renderer.js:19

Can you include this line of code here?

**Comment by LrsNate** [comment]
Here is the function (line 19 is the line where the function is defined and exported)

```
/**
 * Called by our rigged script file at the top of every HTML file to set up
 * the same compilers as the browser process that created us
 *
 * @private
 */
export function initializeRendererProcess(readOnlyMode) {
  if (rendererInitialized) return;

  let rootCacheDir = require('electron').remote.getGlobal(magicGlobalForRootCacheDir);
  let appRoot = require('electron').remote.getGlobal(magicGlobalForAppRootDir);
  let compilerHost = null;

  // NB: This has to be synchronous because we need to block HTML parsing
  // until we're set up
  if (readOnlyMode) {
    d(`Setting up electron-compile in precompiled mode with cache dir: ${rootCacheDir}`);
    compilerHost = CompilerHost.createReadonlyFromConfigurationSync(rootCacheDir, appRoot);
  } else {
    d(`Setting up electron-compile in development mode with cache dir: ${rootCacheDir}`);
    const { createCompilers } = require('./config-parser');
    const compilersByMimeType = createCompilers();

    compilerHost = CompilerHost.createFromConfigurationSync(rootCacheDir, appRoot, compilersByMimeType);
  }

  require('./x-require');
  require('./require-hook').default(compilerHost);
  rendererInitialized = true;
}
```

Apparently this was already fixed as of 1.4.2? The call stack looks different and the load time is down to ~400ms.

**Comment by kevinsawicki** [comment]
> Apparently this was already fixed as of 1.4.2? The call stack looks different and the load time is down to ~400ms.

Electron 1.4 did upgrade Chrome versions and there have been some recent performance improvements to how objects are serialized when sent across processes.

**Comment by MarshallOfSound** [comment]
@kevinsawicki @LrsNate 

You are using `electron-compile` which transpiles code for you live on page load.  The first load takes 10 seconds as it has to transpile everything and then subsequent loads are fast because `electron-compile` uses a caching mechanism.

Using webpack and `electron-compile` simply makes your load time stupidly long, choose one or the other.  Not both 👍

**Comment by LrsNate** [comment]
@MarshallOfSound I switched from `electron-compile` to `electron`; works much faster now, thanks for the tip!
