### ISSUE TITLE
Main.js External function call from a.js script file

### ISSUE THREAD

**Issue by SameerKhan1406** [electron/electron#7521]
* Electron version:
* Operating system:

i am returning the function value to my js file how to do it

**Comment by enlight** [comment]
As has been pointed out earlier, GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community).

**Comment by SameerKhan1406** [comment]
Sorry but i have posted but i am getting reply from community. Sending you the link https://discuss.atom.io/t/main-js-external-function-call-from-a-js-script-file/34387/1
