### ISSUE TITLE
online-offline-events tutorial is misleading

### ISSUE THREAD

**Issue by andymartinwork** [electron/electron#7525]
docs/tutorial/online-offline-events.md

The docs use the `navigator.onLine()` statement and events as an indicator if a browser is on/offline. This is not a good idea, as this will only tell you if a user's computer is connected to a local network - not if they have internet connectivity.

Electron users will be using this tutorial to create offline pages, which simply won't appear in a large percentage of cases where there is no connectivity. I know because we have had lots of user reports of a blank screen where nothing can be clicked :-)

Either the tutorial article should be altered to be shown offline when the `window.loadURL` statement fails, the tutorial removed, or have a big red warning at the top saying that it will be useless in a good chunk of cases.

**Comment by MarshallOfSound** [comment]
The `navigator.onLine` property is documented quite thoroughly across the web including at my personal goto MDN.

https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine

> In Chrome and Safari, if the browser is not able to connect to a local area network (LAN) or a router, it is offline; all other conditions return true. So while you can assume that the browser is offline when it returns a false value, you cannot assume that a true value necessarily means that the browser can access the internet. You could be getting false positives, such as in cases where the computer is running a virtualization software that has virtual ethernet adapters that are always "connected." Therefore, if you really want to determine the online status of the browser, you should develop additional means for checking.

I feel the tutorial in it's current state is accurate, perhaps just copy pasting the above paragraph into the docs would alleviate any concerns you have.  But I feel we should avoid re-documenting standard web API's and stick to documenting Electron specific things.

> Electron users will be using this tutorial to create offline pages, which simply won't appear in a large percentage of cases where there is no connectivity. 

Personally I think you should always be handling the `did-fail-load` event as well to make failures smooth as you can get `did-fail-load` for non-internet connection related issues.

**Comment by andymartinwork** [comment]
I think it would help to have that paragraph in the tutorial. Lots of people moving to electron used to be former C++ devs and pretty new to javascript.

`did-fail-load` sounds good too, looks like I'm off to implement that! Thanks!
