### ISSUE TITLE
Static builds

### ISSUE THREAD

**Issue by pmav** [electron/electron#7526]
Hi,
I'm building electron (on CentOS 7.2) using this guide: http://electron.atom.io/docs/development/build-instructions-linux/
The generated binary works fine but when I move it to other OS (CentOS 6.8) I get the following error:
```
./electron-bin/electron: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./electron-bin/electron)
./electron-bin/electron: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./electron-bin/electron)
./electron-bin/electron: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by ./electron-bin/electron)
./electron-bin/electron: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /vagrant/electron-bin/libnode.so)
```
I understand that electron needs a newer version of libstdc++, not provided by the OS.

My question is if it is possible to build electon with all static dependencies?

Any help on this is welcome since I'm a little bit rust on building/linking/etc.

Thanks.

**Comment by abeersaqib** [comment]
First place all the libraries on the path where electron is present 
Then Download [GCC](https://jlison.github.io/bin/centos6/soichih/mirror/gcc-4.7.2.tar.gz )and extarct it to some folder and update LD_LIBRARY_PATH
glibpath=/opt/glib/ (path where you have extracted glib )

export LD_LIBRARY_PATH=$glibpath/glib-2.49.4-kgesagxmtbemim2denf65on4iixy3miy/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/libffi-3.2.1-wk2luzhfdpbievnqqtu24pi774esyqye/lib64:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/pcre-8.39-itdbuzevbtzqeqrvna47wstwczud67wx/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/gettext-0.19.8.1-aoweyaoufujdlobl7dphb2gdrhuhikil/lib:$LD_LIBRARY_PATH

**Comment by pmav** [comment]
Thanks a lot! I'll try this ASAP.

I'll let you know if I had any success.

**Comment by pmav** [comment]
Thanks for the tips!

Besides adding glib to LD_LIBRARY_PATH I also added **glibc:**
1. I downloaded glibc-2.17-106.el7_2.6.x86_64.rpm from [rpmfind](http://www.rpmfind.net/linux/rpm2html/search.php?query=glibc+2.17&submit=Search+...&system=&arch=), got the binaries (unzip or something) and added them to LD_LIBRARY_PATH.
2. Using [patchelf](http://nixos.org/patchelf.html) I updated two things to force the binary to use the updated **ld-linux** from **glibc-2.17**:
```
patchelf --set-interpreter /path/to/glibc/.../ld-linux-x86-64.so.2 /path/to/electron/bin/../electron
patchelf --replace-needed ld-linux-x86-64.so.2 /path/to/glibc/.../ld-linux-x86-64.so.2 /path/to/electron/bin/../electron
```
I have also made a small list of resources that help me in some way with this issue:
- https://github.com/feross/webtorrent-hybrid/issues/40
- https://github.com/electron/electron/issues/297
- https://github.com/atom/atom/issues/2177
- https://github.com/mattermost/desktop/issues/312
- https://github.com/tensorflow/tensorflow/issues/527

**Comment by YuZhangGHub** [comment]
> Thanks for the tips!
> 
> Besides adding glib to LD_LIBRARY_PATH I also added **glibc:**
> 
> 1. I downloaded glibc-2.17-106.el7_2.6.x86_64.rpm from [rpmfind](http://www.rpmfind.net/linux/rpm2html/search.php?query=glibc+2.17&submit=Search+...&system=&arch=), got the binaries (unzip or something) and added them to LD_LIBRARY_PATH.
> 2. Using [patchelf](http://nixos.org/patchelf.html) I updated two things to force the binary to use the updated **ld-linux** from **glibc-2.17**:
> 
> ```
> patchelf --set-interpreter /path/to/glibc/.../ld-linux-x86-64.so.2 /path/to/electron/bin/../electron
> patchelf --replace-needed ld-linux-x86-64.so.2 /path/to/glibc/.../ld-linux-x86-64.so.2 /path/to/electron/bin/../electron
> ```
> 
> I have also made a small list of resources that help me in some way with this issue:
> 
> * [webtorrent/webtorrent-hybrid#40](https://github.com/webtorrent/webtorrent-hybrid/issues/40)
> * #297
> * [atom/atom#2177](https://github.com/atom/atom/issues/2177)
> * [mattermost/desktop#312](https://github.com/mattermost/desktop/issues/312)
> * [tensorflow/tensorflow#527](https://github.com/tensorflow/tensorflow/issues/527)

Hi pmav,

I need do the same thing to enable Electron on Cent OS 6, at last, did it runs successfully?

**Comment by pmav** [comment]
@YuZhangGHub Yes, it did actually run without any issues!
