### ISSUE TITLE
Disabling JavaScript In WebView?

### ISSUE THREAD

**Issue by azer** [electron/electron#7529]
* Electron version: All
* Operating system: All

I've gone through the documentation but couldn't find the mention of it. Is it possible to disable JavaScript for a page opened in WebView ?

**Comment by kevinsawicki** [comment]
This is not currently possible, you can only disable it on the `BrowserWindow`.

There is a pull request (#7431) opened to expose all `webPreferences` options on the `<webview>` tag so you would be able to use that to disable JavaScript once it is merged.

I'm going to merge this into #2749, please subscribe there for updates.

**Comment by zeke** [comment]
@azer what is your use case?

**Comment by azer** [comment]
@zeke I'd like to let [Kaktüs](http://github.com/kaktus/kaktus) users enable/disable JavaScript for certain sites.

**Comment by zeke** [comment]
👍
