### ISSUE TITLE
Thrown JS error show as window left as separated process 

### ISSUE THREAD

**Issue by taboca** [electron/electron#7530]
* Electron Newbie here
* Electron version: 1.4.3 
* Operating system: Linux 4.4.0-31-generic Ubuntu 16.04 LTS

When launching my browser window, I stumbled in a error (incorrectly referenced window variable) and a JS popup was shown. 

After my sample application properly ended, the attached JS window kept there in the X screen, therefore a process was kept open. I was under the impression that electron would not initiate any UI assumptions, such as to display errors via windows, therefore I am assuming this could be a bug or not desired feature. 

![tela](https://cloud.githubusercontent.com/assets/8658/19213546/0d7e5bae-8d45-11e6-96c6-048e80b65091.png)

**Comment by taboca** [comment]
As I have mentioned, it was left open: 

![screen shot 2016-10-08 at 10 56 03 am](https://cloud.githubusercontent.com/assets/8658/19213588/f2a4cd1c-8d45-11e6-9ac0-b970f8a72294.png)

**Comment by taboca** [comment]
Sample:
```
const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow

let mainWindow

function readyApp() {
  win.blah();
}

app.on('ready', readyApp);

```

**Comment by MarshallOfSound** [comment]
> I was under the impression that electron would not initiate any UI assumptions

This is the default handler of `uncaughtException` events.  If you handle them yourself with something like:

```js
process.on('uncaughtException', () => {
  doSomething()
})
```

The error message boxes will not appear.

**Comment by taboca** [comment]
However, this bug specifically refers to the case that an open process was left, even after a CTRL+C, with Linux. In Mac, a CTRL+C in the shell kills all.

**Comment by taboca** [comment]
Would you know of a way I can inject the exception handling mechanism from outside the client code?
