### ISSUE TITLE
Support for changing Screen Refresh Rate (Hz) when in Fullscreen mode

### ISSUE THREAD

**Issue by santiagopoli** [electron/electron#7531]
* Electron version: All
* Operating system: All

Hi,

I'm currently developing a cross-platform Media Center using Electron. It would be great to be able to match the screen refresh rate with the FPS of the currently playing media when using BrowserWindow.setFullScreen(true).

For example, most TV Shows play at 24fps, and when you match them with a 24hz playback in most TVs, certain features (like MotonFlow) are enabled.

I don't know if this kind of behaviour is possible, but I'll love that feature.

**Comment by zcbenz** [comment]
Changing the refresh rate is definitely not a thing we should provide in a GUI framework, I suggest writing a native node module for this task.
