### ISSUE TITLE
An asynchronous executeJavaScript option

### ISSUE THREAD

**Issue by tolmasky** [electron/electron#7532]
My app sends arbitrary javascript to its web views which contain untrusted content (and hence only can talk through message sending via the preload script). As such, to accommodate an asynchronous executeJavaScript (that can return/throw), I do the following. In the preload script I have something like:

`function __respond(uuid, object, error)
{
     ipcRenderer.send("response", uuid, object, error)
}`

Such that in the server I have something like (Here single quotes represent template string backticks because I can't figure out how to escape a backtick):

```
var handlers = { };

ipcMain.on("response", function (_, uuid, object, error)
{
    if (error) { handlers[uuid].reject(error) };
    else { handlers[uuid].resolve(object) };
}

function executeJavaScript(aFunction)
{
    var the_uuid = uuid.v4();
    var functionString = "(" + aFunction + ")";

    return new Promise(function (resolve, reject)
    {
        handlers[the_uuid] = { resolve, reject };
        webview.executeJavaScript('(${functionString})
        (
             function (object) { __respond(${uuid}, object) },
             function (error) { __respond(${uuid}, null, error) }
        )');
   });
}
```

With these two pieces, I can now have a promise style executeJavaScript:

```
var backgroundColor = await executeJavaScript(function(resolve, reject)
{
     resolve(document.body.style.background)
});
```

However, I don't like there being a global __respond method in a third party site that sends arbitrary data back to the main process. Sure, the fact that its protected by uuid and just sending data back for a promise to resolve is OK, but I'd prefer something scope protected like I could do if it was my own page and the communication could happen solely through message passing. However, I _can't_ use message passing to get the data into the web view in question because it is third party websites that have CSP turned on, and as such sending a code string and evaling it fails. It would be nice to simply build in the promise style resolve/reject into executeJavaScript such that it could easily return values.

**Comment by MarshallOfSound** [comment]
@tolmasky Electron already has built in architecture for handling results / return values from `executeJavaScript` calls.

As per the docs: http://electron.atom.io/docs/api/web-contents/#contentsexecutejavascriptcode-usergesture-callback

> callback Function (optional) - Called after script has been executed with a single parameter "result"

So your code can be simplified to the following (assuming you want to use promises and `async`/`await`

```js
const executeJavaScript = (code) =>
  new Promise((resolve) => {
    webview.executeJavaScript(code, resolve);
  });

var backgroundColor = await executeJavaScript('document.body.style.background');
```

**Comment by tolmasky** [comment]
Sorry, I chose a bad example that didn't highlight the asynchronous nature of what I'm getting at. Here is a better example that I believe is not handled by the current architecture, hence the desire to be able to have a resolve/reject in browser code:

```
function fadeOut()
{
   await executeJavaScript(function(resolve, reject)
   {
       element = document.getElementById("whatever");
       element.style.transition = "opacity 0.5s";
       element.addEventListener("transitionend", resolve, false);
       element.style.opacity = 0;
   });
}
```

I know I could just wait 0.5s, this is just an example. The things I'm doing may take variable time.

**Comment by MarshallOfSound** [comment]
@tolmasky Ah, so you want to asyncronously return from the executed JS.  I think the only way we could standardly do that is if your code string returned a promise.  Then we can asyncronously resolve that promise, callbacks and such wouldn't work.  I'll reopen and submit a PR to allow async promise return values

**Comment by tolmasky** [comment]
That would be great! I'm more than happy to return promises, thanks!

**Comment by MarshallOfSound** [comment]
@tolmasky See #7533

**Comment by MarshallOfSound** [comment]
@tolmasky I was hoping our callback system already followed the `(err, value)` style but it doesn't and it would be a massive breaking change to implement something like that.

**Comment by tolmasky** [comment]
No worries, this is great. Out of curiosity how long do features trail released versions?
