### ISSUE TITLE
run .exe, .node can not be recognized on individual Windows 7.This is what the problem or bug?

### ISSUE THREAD

**Issue by yihuds** [electron/electron#7534]
* Electron version:
* Operating system:windows 7

Uncaught Exception:
Error:The specified module could not be found.
\\?\C:\*****\loginsdk.node

**Comment by enlight** [comment]
This is probably an issue with your app, not Electron, please seek help from the [community](https://github.com/electron/electron#community) (do mention where `loginsdk.node` came from, whether you've rebuilt it to target Electron, and whether or not you're using a module loader/bundler like Webpack).
