### ISSUE TITLE
Electron doesn't render colors correctly.

### ISSUE THREAD

**Issue by tcaer** [electron/electron#7537]
* Electron version: Most Recent As Of 02/10/16
* Operating system: Mac OSX Sierra

Hi, I set the background color `#1E252A` on my document but noticed it looks a bit off.  I used the digital color meter and found that the rendered background color was actually `#181C1F`. Can you please explain this?

Thanks

**Comment by MarshallOfSound** [comment]
> digital color meter

Is this a physical device?  Or an app of some kind?

**Comment by tcaer** [comment]
Hi, it turns out electron has correct colors, it was just me.

Thanks,
