### ISSUE TITLE
Redirect not being followed immediately

### ISSUE THREAD

**Issue by dominicbarnes** [electron/electron#7538]
I am building an electron app that interfaces with a REST API that I am also building. There are cases where I am using HTTP redirects (typically 303 See Other) and I'm getting bizarre behavior when that is encountered.

Basically, my electron app will make an initial `POST` request, which is responded to with a 303 + `Location` header. (as prescribed) However, the electron app does **not** follow up with the expected `GET` request... at least not immediately. At this stage, it feels like my application is "hanging", since it's not fetching the correct resource automatically. Oddly enough, as soon as _any_ other HTTP request is made, all of a sudden the exact `GET` request I was expecting happens as well.

# Reproduction Steps

I created as simple of a test case as possible to demonstrate this problem:

## server.js

```js

'use strict'

const http = require('http')
const request = require('request')

const srv = http.createServer(function (req, res) {
  console.log(req.method, req.url)
  const headers = { 'content-type': 'text/plain', 'access-control-allow-origin': '*' }
  if (req.method === 'POST') {
    res.writeHead(303, Object.assign({ 'location': '/' }, headers))
    res.end()
  } else {
    res.writeHead(200, headers)
    res.end('okay')
  }
})

srv.listen(3000, function () {
  console.log('listening')
})

```

Here are the expected requests and their relevant responses:
 * `POST /` :arrow_right: `303 Location: / <no body>`
 * `GET /` :arrow_right: `200 "okay"`

## client.js

```js

'use strict'

const request = require('request')

const post = {
  method: 'post',
  uri: 'http://localhost:3000',
  followAllRedirects: true
}

const get = {
  method: 'get',
  uri: 'http://localhost:3000',
  followAllRedirects: true
}

request(post, handle(body => console.log(body)))
setTimeout(() => request(get, handle(body => console.log(body))), 3000)

function handle (fn) {
  return function (err, res, body) {
    if (err) throw err
    else fn(body)
  }
}

```

This basically sets up with making the `POST` request, then 3 seconds later it kicks off a `GET` request. (which "unclogs" the queue)

## main.js

```js

const { app, BrowserWindow } = require('electron');

app.on('ready', () => {
  const win = new BrowserWindow({ width: 800, height: 600 });
  win.loadURL(`file://${__dirname}/index.html`);
});

```

This just loads a sample HTML file which runs `client.js`.

# Expected Behavior

 * `POST /`
 * `GET /`
 * 3 second delay
 * `GET /`

# Actual Behavior

 * `POST /`
 * 3 second delay
 * `GET /`
 * `GET /`

# Additional Details

At first, I thought this was just a bug in the request library, so I've tried swapping it out for other similar libraries, such as superagent, got and popsicle. However, I got the exact same behavior from all of them, without fail. In addition, I do not see this same behavior if I just run this as a plain node script, so I'm pretty confident this is an issue in Electron.

I'm very new to Electron, so I'm sure there are more steps I can take to debug this with a lot of the other exposed APIs, but I'm not entirely sure where to begin. Any help getting to the bottom of this would be appreciated!

* Electron version: 1.4.3
* Operating system: Ubuntu 16.04

**Comment by zcbenz** [comment]
I'm merging this to #3471 since they are essentially the same bug.

**Comment by deepak1556** [comment]
@zcbenz I don't think they are same issue, the problem seems to be with only node http modules, using web apis work fine.

```
// client.js
fetch('http://localhost:3000', {method: 'POST'})
```

**Comment by dominicbarnes** [comment]
@zcbenz I agree with @deepak1556, especially after I tried again recently and it still didn't work correctly. In addition, the workaround presented in #3471 does not help me at all. I think this specific issue should be re-opened in light of that.

**Comment by dominicbarnes** [comment]
Just wanted to ping on this, as I can still reproduce this problem perfectly even on the latest version of electron.
