### ISSUE TITLE
Minimum browser window height is not able to set less than 38 px

### ISSUE THREAD

**Issue by Divyanshu07** [electron/electron#7539]
![capture](https://cloud.githubusercontent.com/assets/7404167/19224356/0aeb8700-8e39-11e6-8550-48e1477ff2a4.PNG)

* Electron version: 
* Operating system: Windows 7

Not able to make the window height to 10. By default the height is 0 but when I try to set the height to 10, the height goes back to 38.

**Comment by kevinsawicki** [comment]
What options are you passing to the `BrowserWindow` constructor?

**Comment by Divyanshu07** [comment]
new BrowserWindow({x: someValue,
    y: someValue,
    width: someValue, height: 15,
    frame: false, show: false, minimizable: false,
    webPreferences: {
 
    }
  })

I guess by default, the minheight property is 0

**Comment by zcbenz** [comment]
This is unfortunately a limitation enforced by Windows itself, I'm not aware of any way to work around it, so I'm closing it as won't fix.

**Comment by acerbastimur** [comment]
Is there any way to make width for ex. 10 px ?
