### ISSUE TITLE
Turning on from standby?

### ISSUE THREAD

**Issue by 1e4** [electron/electron#7543]
I am currently planning on building an app however one of the requirements is that the app must be able to power on the laptop/pc from standby. Is this possible in Electron? I noticed you can monitor the power changes, however I couldn't find any docs on actually turning it on.

**Comment by MarshallOfSound** [comment]
@1e4 I don't believe this is possible regardless of the framework you use.  I don't think even native applications can resume a computer from standby mode.  The best you can do is prevent the computer from sleeping in the first place.

**Comment by MarshallOfSound** [comment]
Also the standard question response thing 👍 

GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

You should check out http://electron.atom.io/docs/api/power-save-blocker/
