### ISSUE TITLE
require('something_from_node_modules') does not work inside asar that is in `AppData\Roaming\MyApp`

### ISSUE THREAD

**Issue by wojtkowiak** [electron/electron#7545]
In my app, I am using some sort of plugins that are packaged to separate .asar archives
They are downloaded and copied to the user data dir (`AppData\Roaming\MyApp`).
Because of https://github.com/electron/electron/blob/master/lib/common/reset-search-paths.js when a file is requiring something from the app's node_modules it can't find it as the asar is placed outside app resources. 
Some way of setting a node_modules path for this scenario would be very useful to me because I do not want those files to reside anywhere else.
Electron 1.4.3
Windows 10 64bit

**Comment by zcbenz** [comment]
The mode search paths are being reset for security problems, otherwise your app may be kidnapped by a global module installed on user's machine.

The workaround is to manually add system module paths to `NODE_PATH` or `require('module').globalPaths`.

**Comment by wojtkowiak** [comment]
Thank you very much for your time. It indeed does the trick 👍
