### ISSUE TITLE
window-all-closed listener required?

### ISSUE THREAD

**Issue by pofallon** [electron/electron#7547]
* Electron version: 1.4.0
* Operating system: Mac / Windows

I'm building an app which, after presenting a login form, spends the rest of its time in the system tray.  In order to keep the app from exiting on Windows after the login form is processed, I commented out this boilerplate code (which fixed the problem):

```javascript
// Quit when all windows are closed.
app.on('window-all-closed', () => {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  // if (process.platform !== 'darwin') {
  //   app.quit()
  // }
})
```

Later, when cleaning up the code, I removed this listener altogether, since it's not doing anything.  However, now (on a Mac) the app just exits after the login screen is processed.  It appears I need (at least) an empty listener to keep the app running in the tray once I `.destroy()` my login window:

```javascript
app.on('window-all-closed', () => { })
```

Is this expected behavior?  Is there another preferred way to accomplish this?  Thanks!

**Comment by kevinsawicki** [comment]
> Is this expected behavior? Is there another preferred way to accomplish this? Thanks!

This is expected behavior when running your app via the `electron` command line.

https://github.com/electron/electron/blob/2efb7a12cb24bb447bfa823f34eb3eb372cab630/default_app/main.js#L39-L44

Once you package your app using something like `electron-packager` then the `default_app.asar` file is not included and this behavior should go away.

**Comment by pofallon** [comment]
Ah ok, thanks!  I did see that in default_app, but wasn't aware that was being included when I provide my own main.js on the command line.
