### ISSUE TITLE
HTTPs requests are not proxy-ed 

### ISSUE THREAD

**Issue by IonicaBizau** [electron/electron#7564]
I'm using `nightmare` to do some automation and I set up a [proxy](https://github.com/segmentio/nightmare/tree/ba193214a2ffde9b193525952822db4c3f9198cc#switches ). [Here](https://github.com/segmentio/nightmare/blob/ba193214a2ffde9b193525952822db4c3f9198cc/lib/runner.js#L46-L51)'s how Nightmare interprets the `switches` object.

I'm using a local server as a proxy.

In these pages, there are requests to Google Maps and for some reason (I think it's because of `https`) these urls are not proxy-ed, but end with `ERR_EMPTY_RESPONSE`.

Any ideas what switch I have to add to enable proxying all the urls, including the secure ones?

* Electron version: latest
* Operating system: Ubuntu 16.04

**Comment by IonicaBizau** [comment]
What I already tried is to add `'host-rules': "MAP * 127.0.0.1:8080"`, but that didn't change anything.

**Comment by IonicaBizau** [comment]
Actually, it does work for urls with `http` protocol, but not with the `https`. Any idea how to bypass that locally?

**Comment by IonicaBizau** [comment]
I reproduced this in Chrome:

![image](https://cloud.githubusercontent.com/assets/2864371/19324892/617664b0-90cc-11e6-8166-f827e4eca474.png)


I ran:

```sh
google-chrome-stable --proxy-server='http=http://localhost:8000;https=http://localhost:8000' --ignore-certificate-errors
```

I think `--ignore-certificate-errors` doesn't make any change here... :disappointed:

**Comment by IonicaBizau** [comment]
Sites served over `http` are proxied.

**Comment by IonicaBizau** [comment]
Could it be that my local proxy doesn't support HTTPs?

I tried several ones and I found this pretty nice: https://github.com/tsyd/proxy-tamper

However, I'm not sure how to enable https support in my local proxy server.

**Comment by deepak1556** [comment]
> Could it be that my local proxy doesn't support HTTPs?

Yes. 

> However, I'm not sure how to enable https support in my local proxy server.

I believe community channels are better place to ask this question. 

https://github.com/nodejitsu/node-http-proxy
https://github.com/TooTallNate/node-https-proxy-agent

Closing this out since its not a bug in Electron.
