### ISSUE TITLE
Electron won't start when offline or no internet connection

### ISSUE THREAD

**Issue by joyfementira** [electron/electron#7565]
* Electron version:
Electron version: 1.4.3

* Operating system:
Windows10 x32

Electron won't start when offline or no internet connection.
Even the Electron API Demo won't start only the installing window will show, the it will stop.

**Comment by kevinsawicki** [comment]
This looks very similar to https://github.com/electron/electron/issues/6437, closing it out as a duplicate, please subscribe there for updates.
