### ISSUE TITLE
GetUserMedia

### ISSUE THREAD

**Issue by EliuPC93** [electron/electron#7567]
- Electron version: 1.3.5
- Operating system: raspbian on Raspberry pi 3

I'm running an electron app in Raspberry pi 3 and when I try to use GetUserMedia noting happens. The console just throws me an "DevicesNotFoundError" message and when I run the same code on my pc with Firefox it works fine. I have a question: Do I need to do something for setting up the media devices on electron app and making GetUserMedia works?

**Comment by kevinsawicki** [comment]
> Electron version: 1.3.5

Are you able to try on Electron 1.4.3 and confirm it does not work there as well?

>  when I run the same code on my pc with Firefox it works fine.

Does it work for you in Chromium?

**Comment by EliuPC93** [comment]
What I want to make is to display the raspicam (respberry pi cammera) into a <video> tag in an electron app, something like a streaming but without recording it into a file. I've tried using the code as it posted on the issue #1076 ( Jan 31, 2015) about using "GetUserMedia". When I run the code in my electron app (V 1.4.3 b/c I actually just updated and tested again a few minutes ago) still not working. Electron doesn't display anything. When I run the same code in another browser it works and the webcam is displayed. But I don't know if I need to download an extra electron API so I can display what the camera is recording. 
The code I've been using for testing is the following:

 <!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <video autoplay></video>
    <script type="text/javascript">
    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
    var constraints = {audio: false, video: true};
    var video = document.querySelector('video');
    function successCallback(stream) {
      window.stream = stream; // stream available to console
      if (window.URL) {
        video.src = window.URL.createObjectURL(stream);
      } else {
        video.src = stream;
      }
    }
    function errorCallback(error){
      console.log('navigator.getUserMedia error: ', error);
    }
    navigator.getUserMedia(constraints, successCallback, errorCallback);
    </script>
  </body>
</html>

**Comment by enlight** [comment]
Does it work on the Chrome browser?

**Comment by wb2110** [comment]
Does the raspberry pi 3 have micphone? i have a pi2b and i make it work through load snd-dummy module,You can refer to this link [https://www.raspberrypi.org/forums/viewtopic.php?p=485842#](url)

**Comment by kevinsawicki** [comment]
> i think that this is none of the electron business

Closing this out then, thanks for the details.

**Comment by schrockwell** [comment]
For future visitors scratching their heads in frustration, be sure your user is part of the `audio` group (on Raspian, `sudo gpasswd -a [username] audio`). I also had to `sudo apt install pulseaudio` and reboot in order to get all the devices to enumerate properly.
