### ISSUE TITLE
when I started atom,my own app started at the same time

### ISSUE THREAD

**Issue by lizprun** [electron/electron#7569]
hi~
I got a problem about atom and my own app(developed by electron). 
when I started atom,my own app started at the same time.
I was confused. Is there any relationship between them?

my atom version:1.9.8
my electron version:1.1.3
my OSX version:10.11.2
THX!

**Comment by kevinsawicki** [comment]
> Is there any relationship between them?

There isn't a relationship between them except that Atom is built on Electron.

Are you able to provide a minimal app that reproduces this issue?

**Comment by kevinsawicki** [comment]
Closing out until more information is provided.
