### ISSUE TITLE
Fullscreen window opens new window on top of parent

### ISSUE THREAD

**Issue by JamesStidard** [electron/electron#7571]
* Electron version: 1.3
* Operating system: macOS Sierra (10.12)

I'm not sure if this is an Electron or an Atom issue - my gut feeling is it's Electron. If it's not let me know and I'll repost this on the Atom page.

Since upgrading to macOS Sierra, opening new windows while in fullscreen mode will open the new window on top of the current fullscreened window. This didn't use to happen and I assume was something to do with how macOS have changed their window management API to allow tabs in apps.

Here's a screenshot which will hopefully make more sense:
<img width="1280" alt="screen shot 2016-10-12 at 9 36 54 am" src="https://cloud.githubusercontent.com/assets/1797906/19303512/d4c9b0aa-9060-11e6-8f8a-a945926d7400.png">

Steps to reproduce:
1: open Atom
2: fullscreen application with the green button on the menu bar
3: open new window with cmd-shift-n or File > New Window

**Comment by enlight** [comment]
Please file this in the Atom repository, if they can reproduce it with the latest Electron then we can reopen this issue.

**Comment by JamesStidard** [comment]
Will do. Thanks, @enlight. Here's the Atom issue if anyone finds this and wants the follow: atom/atom#12957
