### ISSUE TITLE
webview and ng-repeat 

### ISSUE THREAD

**Issue by skullist** [electron/electron#7572]
* Electron version:v1.4.1
* Operating system:win7 x64
i want loop the webview to show,so i use the ng-repeat of angularjs,i create a ng-template like this

![qq 20161012181928](https://cloud.githubusercontent.com/assets/16385185/19306486/7947f640-90a8-11e6-89e0-10fa9fe78642.png)
then i want click the button to add some webview. the first webview is normal.when i add the second webview,the first is blank and the second  is normal.so i found the new webview is normal.other is blank and their webContents is null
![qq 20161012183533](https://cloud.githubusercontent.com/assets/16385185/19306960/bbcf61c2-90aa-11e6-9804-741672e0be94.png)
how can i solve it

**Comment by zcbenz** [comment]
The webview tag is different from other tags that it has to be attached to DOM to work, I don't know how `ng-repeat` works but this problem is very likely to be caused by that. My suggestion is to just manually create webview with DOM APIs.
