### ISSUE TITLE
Add support for controlling menu popup

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#7574]
Currently there isn't any support for controlling the menu popup after it appears. We need to know if the popup have been closed and be able to close it manually.

An API as the shown below will be suitable I think.
```js
var popup = menu.popup(remote.getCurrentWindow());
popup.isOpened(); // returns true or false
popup.close(); // closes the popup

// or a global approach

menu.hasPopupOpened(); // returns true or false
menu.closePopup(); // closes if there is an opened popup
```

**Comment by zcbenz** [comment]
I'm merging this issue to #1854, the latter blocks this issue and fixing it implies implementing a set of APIs for controlling the popup.

**Comment by CandyFace** [comment]
This is exactly the functionality I need right now, is there really no way to figure if a window is already open or to close a specific window currently? Say for example I have one window open, then when I open a second window, the first window should close. Right now when you use win.close it closes all my popup windows.
