### ISSUE TITLE
How to share a variable between two Renderer？

### ISSUE THREAD

**Issue by milu2003** [electron/electron#7582]
* Electron version:0.37
* Operating system:mac

in main:

`global.var = 1;`

in Renderer, read it like this:

`remote.getGlobal('var')`

But I would like to modify the variables, even in other renderer can also be accessed

How to do it？

**Comment by YurySolovyov** [comment]
Best way to share data is via message passing

**Comment by milu2003** [comment]
Hello, can you speak a little more?

**Comment by kevinsawicki** [comment]
> Best way to share data is via message passing

You can pass messages that get/set via the `ipcRenderer`/`ipcMain` modules, http://electron.atom.io/docs/api/ipc-renderer/

The `remote` module is also possible for this since you can call remote methods and set remote properties but this will be done synchronously which could hurt your app's performance. The IPC APIs can be done asynchronously.

Going to close this out, please check out [forums](https://discuss.atom.io/c/electron) for more app-architecture discussions.

**Comment by kevinsawicki** [comment]
You may also want to check out the `#electron` channel in [Slack](http://atom-slack.herokuapp.com/).

**Comment by milu2003** [comment]
@kevinsawicki  i try like it: 

`ipcRenderer.send('main-send-set-var', share_data);`



But there is a problem is that simple variables can be passed, complex object variables, passing over the past, unable to access their methods

That's why？

**Comment by milu2003** [comment]
> ipcRenderer.send(channel[, arg1][, arg2][, ...])
channel String
arg (optional)
Send a message to the main process asynchronously via channel, you can also send arbitrary arguments. Arguments will be serialized in JSON internally and hence no functions or prototype chain will be included.


So, how can I send to retain the object method

**Comment by AlexanderFeijoo** [comment]
Not sure if you ever got an answer, but for anybody else finding this thread, here is how you send and receive variables between renderers from the main process:

Scenario: I have a toggle that will activate a sync. This function needs to know if syncing is true or false. I want to show that a sync is active, but I'm using a separate renderer for showing the active sync page. 

In my main process I set up my ipc renderer. This listener will wait for one ipc render event (`show-syncSpinner-event`) and then trigger another one (`spin`)



  ```javascript
ipcMain.on('show-syncSpinner-event', (event, arg) => {  
     mainWindow.webContents.send('spin', arg);  //This will send the spin event to the other renderer process
});
```



Then, when I activate my sync on the toggle component I call:


  ```javascript
electron.ipcRenderer.send('show-syncSpinner-event', toggle); //Tell the ipc renderer we just set up to send the spin event
```

where `show-syncSpinner-event` is the name of the ipc renderer event I'm sending back to my main process and `toggle` is the bool I need to send across renderers

Finally, on my separately rendered component, I can set up another listener that does stuff when the 'spin' event is called.


  ```javascript
//This guy is listening for the spin event from the main process
electron.ipcRenderer.on('spin', (event, arg) => {
      //Do stuff with the arg variable you have passed to and from your main process
    });
```

**Comment by Acidic9** [comment]
How can we share classes in Electron whilst keeping all it's methods and functions?

**Comment by YurySolovyov** [comment]
Classes themselves or instances of the classes - objects? 

For classes themselves, you can put them in a separate file and require in both renderer and main. 

For objects - you can pass them in serialized form and then init new instances from serialized state.

**Comment by Nachasic** [comment]
I've been working on an RxJS-based state management lib that allows you to share your state seamlessly between multiple render processes, here's a small demo
https://github.com/Nachasic/bifrost-electron-demo

**Comment by HePingLaoSan** [comment]
> I've been working on an RxJS-based state management lib that allows you to share your state seamlessly between multiple render processes, here's a small demo
> https://github.com/Nachasic/bifrost-electron-demo

This link is not working...
