### ISSUE TITLE
Is it possible to desktop capture with cursor hidden?

### ISSUE THREAD

**Issue by rnrneverdies** [electron/electron#7584]
I need to capture the screen but not capturing the mouse pointer. I'm combining desktopCapture and getUserMedia APIs as explained in the [docs](https://github.com/electron/electron/blob/master/docs/api/desktop-capturer.md) to capture the video, but that's also capturing the cursor. 

Can you point me out on what I need to do to remove the cursor from the MediaStream?

Thanks in advance!

**Comment by zcbenz** [comment]
Currently there is no way to do that, I suggest bringing this up at [Chromium's issues list](https://crbug.com), Electron is just using Chromium for the desktop capture and we are not able to add this feature on Electron's side.

**Comment by SimplyAhmazing** [comment]
In case anyone needs this: I'm doing screenshot based testing for an electron app and I'm running this before taking a screenshot to remove the cursor,

```javascript
// Remove cursor from page before taking a screenshot
 app.webContents.executeJavaScript('setImmediate(function blur() { document.activeElement.blur(); })')
```

**Comment by rmnprt** [comment]
@SimplyAhmazing That din't work for me, on Windows 10 at least. Is there any better way of doing this, one year down the line, with electron 3.x

**Comment by CapOM** [comment]
In future https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/cursor `always`, `motion`, `never`, so you will be able to control cursor passing option to getUserMedia, see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints

**Comment by EmptyCrown** [comment]
This is enabled? How do you incorporate other MediaTrackConstraints parameters into the desktopCapturer template from the docs?
```
video: {
            mandatory: {
              chromeMediaSource: 'desktop',
              chromeMediaSourceId: source.id,
              minWidth: 1280,
              maxWidth: 1280,
              minHeight: 720,
              maxHeight: 720
            }
}
```

**Comment by munjalpatel** [comment]
> This is enabled? How do you incorporate other MediaTrackConstraints parameters into the desktopCapturer template from the docs?
> 
> ```
> video: {
>             mandatory: {
>               chromeMediaSource: 'desktop',
>               chromeMediaSourceId: source.id,
>               minWidth: 1280,
>               maxWidth: 1280,
>               minHeight: 720,
>               maxHeight: 720
>             }
> }
> ```

I am also trying to figure that out. Can't find a good documentation for it anywhere.

**Comment by CapOM** [comment]
Not yet implemented, tracking bug in chromium seems to be https://bugs.chromium.org/p/chromium/issues/detail?id=1007177

**Comment by hackers365** [comment]
any update?

**Comment by danielehrhardt** [comment]
Can you implement:
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/cursor
```
 ).mediaDevices.getUserMedia({
                                video: {
                                    cursor: 'never',
```

**Comment by alekye** [comment]
what about cursor now?

**Comment by stormappears** [comment]
> 我通过 C++ 提供的接口将鼠标指针隐藏了，但是截图 捕获的图像中还是包含了鼠标 我在想，是我调用接口的时机不对吗？但是我在用户点击截图按钮和系统开始捕获图像时都马上调用了函数并且等接口返回结果才开始进行下一步的 想不明白这里为啥不正常？


How Do You Implement In CPP Can You Share Code ?
