### ISSUE TITLE
Allow certain keyboard events to be always handled in the main process

### ISSUE THREAD

**Issue by poiru** [electron/electron#7586]
Embedding arbitrary web content is problematic when it comes to keyboard shortcuts because:
- Web content can steal app shortcuts (see e.g. brave/browser-laptop#4407)
- Blocked web content (e.g. a focused `<webview>` performing expensive computation) will also prevent app shortcuts from firing immediately

To fix this, we need a way to _always_ handle certain shortcuts in the main process. I think the most flexible solution would be something like this:

``` js
app.addProtectedShortcut('CmdOrCtrl+Tab', (event) => {
  event.preventDefault();
});
```

We could then implement:

``` cpp
bool CommonWebContentsDelegate::PreHandleKeyboardEvent(
    content::WebContents* source,
    const content::NativeWebKeyboardEvent& event,
    bool* is_keyboard_shortcut) {
  return /* event is protected shortcut and the handler called preventDefault */;
}
```

@zcbenz Thoughts? I'm happy to work on this if we come up with a reasonable approach.

**Comment by zcbenz** [comment]
It can be an event of `WebContents` instead of `app`, something like this should work:

```js
webContents.on('pre-key-event', (event, key) => {
  console.log(event.isShiftPressed, key)
})
```

**Comment by kevinsawicki** [comment]
@poiru just a heads up, your `libchromiumcontent` pull request is now on master.

**Comment by poiru** [comment]
@zcbenz @kevinsawicki What do you think of something like:

```js
webContents.on('pre-key-event', (event, key) => {})
```

... where key is:

```typescript
interface {
  type: 'keyUp' | 'keyDown'

  // Everything below is equivalent to the DOM KeyboardEvent counterpart
  key: string
  repeat: boolean
  shiftKey: boolean
  controlKey: boolean
  altKey: boolean
  metaKey: boolean
}
```

Another option is to have distinct `pre-key-up-event` and `pre-key-down-event` events. Any thoughts?

**Comment by kevinsawicki** [comment]
> webContents.on('pre-key-event', (event, key) => {})

The two event prefixes we have for things about to happen right now are `will-` and `before-`. Having them separate seems to bring some consistency with the DOM APIs which could be nice. So  my initial thoughts are two events,  `before-keydown` and `before-keyup`.

The event interface looks good otherwise though 👍

**Comment by poiru** [comment]
@kevinsawicki I just noticed that [http://electron.atom.io/docs/api/web-contents/#contentssendinputeventevent](webContents.sendInputEvent) has already defined some terminology relevant to this discussion. Should we try to be consistent with the DOM `KeyboardEvent` or with `webContents.sendInputEvent`? I'm having a hard time deciding!

**Comment by kevinsawicki** [comment]
> Should we try to be consistent with the DOM KeyboardEvent or with webContents.sendInputEvent?

Yeah, so the event would be like `pre-input-event` and the type would be `keyDown` or `keyUp`? That works for me too.

**Comment by poiru** [comment]
@kevinsawicki Could we merge electron/brightray#261?

**Comment by kevinsawicki** [comment]
> Could we merge electron/brightray#261?

I was planning to wait until we had the pull request in this repository that uses it. You should be able to use it locally by pointing your Electron fork to your Brightray fork in the `.gitmodules` file.
