### ISSUE TITLE
Does electron provide a way to automatically generate bindings for alterntive js languages?

### ISSUE THREAD

**Issue by crocket** [electron/electron#7588]
DOM provides interface definition language(.idl) files.
I wonder if the same applies to electron.

**Comment by enlight** [comment]
I'm not sure what you mean by "alternative js languages". There is an effort under way to generate a description of the [API in JSON format](https://github.com/electron/electron/releases/download/v1.4.3/electron-api.json).

**Comment by MarshallOfSound** [comment]
Pretty sure this is the intention of the JSON API file and as a bonus the outcome of the typescript definition project.

https://github.com/electron/electron/projects/3

**Comment by crocket** [comment]
Thanks... I'll keep track of https://github.com/electron/electron/projects/3
