### ISSUE TITLE
Debug webContents crashed event

### ISSUE THREAD

**Issue by nantas** [electron/electron#7591]
* Electron version: 1.3.3
* Operating system: Windows 10 64bit

In our app we have created a renderer process with `new BrowserWindow()` to do some compilation work such as browserify and JSON data process. Recently we start using Electron v1.3.3 x64 build to build our app and we experience frequent random crash from the renderer process. The command line log shows no error call stack except our own error handler.

We try to catch the crash error with:

```js
browserWindow.webContents.on('crashed', event => {
      // for (var k in event) {
      //   console.log('crashed : ' + k);
      // }

      Console.error( `Window "${this.name}" crashed: ${event}` );
    });
```

But the only properties in callback's `event` object are `sender` and `preventDefault()`, no way to get details of what's going wrong.

Then we try to use Electron Debug build to debug the process but the app failed to run due to the heavy usage of native modules. 

The crash happens randomly at the slightly different stages of our worker's process, and no error catched whatsoever on JavaScript scripting side. We are totally stuck. 

Is there anyway to debug the issue? Thanks in advance!

**Comment by kevinsawicki** [comment]
> Is there anyway to debug the issue? 

If you use the `crashReporter` module, it will report render (and main) process crashes to a remote server that can collect them.

http://electron.atom.io/docs/api/crash-reporter/

**Comment by nantas** [comment]
@kevinsawicki 
I've tried to setup a crash report server and add `crashReporter.start` in the renderer process worker but it cannot catch the crash. I've no idea why. Also only the renderer process is crashed, not electron main process.

This issue happens in Electron v1.3.x Windows x64 build only.
When we fall back to Electron v1.1.3 windows x64 works fine.

**Comment by MarshallOfSound** [comment]
@nantas On windows I believe you have to start the crashReporter from the main process (could be wrong there).

You can also use `ELECTRON_ENABLE_STACK_DUMPING=true` as an environment variable on the test machine and launch from CLI and it will spit out the crash report.

**Comment by nantas** [comment]
Hi @MarshallOfSound 

I had a `crashReporter.start` in main process, and in each renderer process, just as docs stated.

I just tried to set `ELECTRON_ENABLE_STACK_DUMPING=true` as environment variable but nothing comes out of CLI. If I add `process.crash()` to the worker process script I only got one error without stack:

```js
[11724] Error: Window "worker" crashed: [object Object]
    at WebContents.Window.nativeWin.webContents.on.event (C:\Users\nantas\fireball-x\CocosCreator_v1.js:209:15)\lib\main\window
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7)
```

As for now I'm not quite sure where's the crash exactly. Manually added crash point in the problematic process script behaves quite differently from the actual random crash.
`

**Comment by MarshallOfSound** [comment]
Without a minimal reproducible example or the crash log I can't help much more.  If a crash dump isn't coming out of the CLI I would suggest that perhaps Electron isn't crashing rather your code is terminating the process?

**Comment by johnryan** [comment]
@MarshallOfSound is there any documentation around setting up an instance of `mini-breakpad-server` which collected the crashes just fine but the stack trace just consists of memory addresses etc. I assume there's some sort of dsym that needs to happen but I haven't been able to find much direction there.

**Comment by danmo** [comment]
Same here, crashReporter doesn't catch renderer process crashes no matter where you start it (main or renderer process)

**Comment by aaomidi** [comment]
Why doesn't the crash reporter catch these? Is there any official response from the electron team?
