### ISSUE TITLE
Does electron provide a way to avoid this default event in  Windows 10?

### ISSUE THREAD

**Issue by zeusLeeJh** [electron/electron#7593]
* Electron version: 1.3.3
* Operating system: Windows 10

I created a Tray for my electron app. I bind the 'right-click' event for my tray icon to open a brower window.
when the tray icon is right clicked,  It is the common situation and what it should be:
![common](https://cloud.githubusercontent.com/assets/15540537/19337629/9160f992-9149-11e6-92ac-a3b57bb10432.png)
But sometimes:
![special](https://cloud.githubusercontent.com/assets/15540537/19337656/b4f84e3c-9149-11e6-9ea8-0f432c942d59.png)

Finally, this special situation will not appear in Windows 7.

**Comment by MarshallOfSound** [comment]
@zeusLeeJh That is the windows 10 Tray menu.  It looks like you just "missed" the tray icon and right clicked on the tray instead.  Don't forget that sometimes tray icons are left behind after an app closes so if you right click on that icon it will disappear and you will end up clicking the tray.

**Comment by zeusLeeJh** [comment]
@MarshallOfSound I don't think so.
See this screenshot. The yellow color icon is my Tray icon.
![error](https://cloud.githubusercontent.com/assets/15540537/19342039/b56c5a5c-9162-11e6-8253-0eaab450b138.PNG)
I right clicked my tray icon, my browser window & the Windows 10 Tray menu show at the same time.

**Comment by MarshallOfSound** [comment]
Can you provide a minimal sample application that demonstrates this issue.  I've tried right clicking all sorts of Electron based tray applications with no luck.  It would seem to be a Windows bug 😢

**Comment by zeusLeeJh** [comment]
[tray-example-master.zip](https://github.com/electron/electron/files/526779/tray-example-master.zip)
Here is the application!
I am a electron programing beginner.I don't know whether this situation was caused by myself or the electron.

**Comment by 1511pzz** [comment]
老哥这个问题你解决了吗
