### ISSUE TITLE
Electron :jquery module not found

### ISSUE THREAD

**Issue by SameerKhan1406** [electron/electron#7594]
* Electron version:
* Operating system: linux x64

After packaging it shows jquery module not found but when i do npm start everything is working fine.

**Comment by enlight** [comment]
GitHub issues are for bug reports and feature requests, for everything else please ask the [community](https://github.com/electron/electron#community).

**Comment by AglaiaZ** [comment]
<script>
            window.nodeRequire = require;
            angularRequire = window.require;
            delete window.require;
            delete window.exports;
            delete window.module;
        </script>

**Comment by AglaiaZ** [comment]
`<script>
            window.nodeRequire = require;
            angularRequire = window.require;
            delete window.require;
            delete window.exports;
            delete window.module;
        </script>`
