### ISSUE TITLE
[Feature] Separator in Tray

### ISSUE THREAD

**Issue by StefMa** [electron/electron#7595]
* Electron version: 1.4.3

* Operating system: macOS Sierra 10.12

* Description:
I haven't found something in issues so I created it :) Maybe it is a duplicate. Than it can be closed :D
However. It would be great if we can create separator in [Tray](https://github.com/electron/electron/blob/master/docs/api/tray.md).
Like the [menu-item type separator](https://github.com/electron/electron/blob/master/docs/api/menu-item.md). 

Current tray implementation (without separator):
![bildschirmfoto 2016-10-13 um 08 27 03](https://cloud.githubusercontent.com/assets/10229883/19338769/6f00d0d6-911f-11e6-8505-9d818621811a.png)
(Here I like separators between upload and settings and between settings and close) 

Example of macOS:
![bildschirmfoto 2016-10-13 um 08 28 29](https://cloud.githubusercontent.com/assets/10229883/19338789/8d32ed0a-911f-11e6-9e43-77edcf3980f0.png)

**Comment by MarshallOfSound** [comment]
@StefMa I just tested on macOS and separator menu item's work as expected.  Did you try the `separator` type?

**Comment by StefMa** [comment]
Oh lol. That happen when you don't read the docs correctly and just copy and paste the samples 🤦
Didn't know that we can use the same menu-items for Tray as we use in "normal" Menus... 

Maybe we have to document it better? 🤔 

However this can be closed 😀

**Comment by MarshallOfSound** [comment]
Well, I mean, the `tray` module says it uses an instance of a `Menu` which has in its documentation how to use `menuItem`'s.  I think it is already documented quite nicely.
