### ISSUE TITLE
How to launch Electron app in kiosk mode with keyboard keys disabled like switching between tabs and all

### ISSUE THREAD

**Issue by Sam747** [electron/electron#7597]
* Electron version:Linux
* Operating system:1.4

I am trying to disable all functionalities after launching my app

**Comment by thesbros** [comment]
Did you try `kiosk: true` in your `new BrowserWindow({})`?

**Comment by Sam747** [comment]
Yes I did it but I am able to swap between windows on linux as well as windows

**Comment by zcbenz** [comment]
The kiosk mode is simply implemented as fullscreen on Windows and Linux, a search of "kiosk" would tell you the reason and possible solutions:
https://github.com/electron/electron/issues?q=is%3Aissue+kiosk+is%3Aclosed

**Comment by rohithareddy** [comment]
Were you able to disable switching between tabs if so please do let me know.
