### ISSUE TITLE
I want to force my app to close other background application before startup

### ISSUE THREAD

**Issue by SameerKhan1406** [electron/electron#7599]
* Electron version:
* Operating system: linux  arch-x64

I want to force other app to quit before launching my application prompting to close

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by SameerKhan1406** [comment]
Please answer this one last time since no one answer on community. It seems to be not active.

**Comment by SameerKhan1406** [comment]
![screenshot from 2016-10-13 15 11 25](https://cloud.githubusercontent.com/assets/22536811/19344327/5e7b3700-9157-11e6-867b-74ad8f770b89.png)

**Comment by SameerKhan1406** [comment]
Always reconnecting issue
