### ISSUE TITLE
Does any one know how do I get the current open windows or process of a local machine using node js?  

### ISSUE THREAD

**Issue by Sam747** [electron/electron#7600]
* Electron version:1.4
* Operating system:Ubuntu
What I'm trying to do is: list the current open task, windows or process open, like in Windows Taskmanager

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
