### ISSUE TITLE
Last Query:I want to force my app to close other background application before startup.

### ISSUE THREAD

**Issue by SameerKhan1406** [electron/electron#7601]
* Electron version:
* Operating system:Linux arch- x64 
I want to force other app to quit before launching my application prompting to close

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by SameerKhan1406** [comment]
I won't ask next time but answer this question because your community and channel seems to be in not working condition
