### ISSUE TITLE
Render process crashes after couple of hours

### ISSUE THREAD

**Issue by LucyStarlight** [electron/electron#7604]
- Electron version: 1.3.4
- Operating system: Windows 10, Raspbian jessie

I'm running 2 applications build with Electron on Raspbian. One of them shows a bunch of numbers retrieved from the server, and the other one displays Google Maps and puts map markers on it.
The one with Google Maps turns white after a couple of hours saying the render process crashed, this does not happen on the application which retrieves the numbers

**Comment by danburzo** [comment]
I'm not sure this is the source of the problem, but you can try to prevent Electron (in fact, Chromium) from throttling a background renderer, by:

1. running Electron with the `--disable-renderer-backgrounding` [command-line switch](http://electron.atom.io/docs/api/chrome-command-line-switches/)
2. initializing your [Browser Windows](http://electron.atom.io/docs/api/browser-window/) with `webPreferences.backgroundThrottling = false` 
3. Run the [silent audio hack](https://github.com/atom/atom/pull/9485/files) in your renderer processes (web pages).

In addition, you should be able to listen to the `crashed` event on your renderer process, and try to recover from the crash if possible, regardless of the source of the problem. 

As for figuring out the source of the problem, anyone trying to help would need additional information, or a simplified test case.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by kevinsawicki** [comment]
> Can you provide a minimal app that can reproduce this problem?

Closing out until more information is provided
