### ISSUE TITLE
Location with session persist crash

### ISSUE THREAD

**Issue by damevelue** [electron/electron#7607]
Electron version: 1.4.3
Operating system: macOS 10.11.1

Electron crashes when a website wants to get location with session persist. For example go to google.com, search any query and click "use precise location" at the bottom and crashes...

**Code** 
`const {app, BrowserWindow, session} = require('electron');

app.on('ready', function(){
	var ses = session.fromPartition('persist:debug');	
	ses.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36', 'en-US');
	var win = new BrowserWindow({
		'width' : 1366,
		'height' : 768,
		'webPreferences' : {
			'session' : ses,
		}			
	});
	win.loadURL('http://www.google.com');		
});`

**Stack dump**
`
Received signal 11 SEGV_MAPERR ffffffff00000038
 [0x00010a1433b6]
 [0x7fff86cfe52a]
 [0x700005a438f0]
 [0x00010a870baf]
 [0x00010ab89420]
 [0x00010a1439cb]
 [0x00010a16479c]
 [0x00010a164aac]
 [0x00010a164e0b]
 [0x00010a1387b5]
 [0x00010a17aae1]
 [0x00010a19a02d]
 [0x00010a8a5398]
 [0x00010a8a557b]
 [0x00010a19a11f]
 [0x00010a196537]
 [0x7fff8846a9b1]
 [0x7fff8846a92e]
 [0x7fff88468385]
`

**Comment by deepak1556** [comment]
Unable to reproduce on linux.

**Comment by damevelue** [comment]
session must be persisted, first time doesn't crash.
if I remove session persist there is no problem.

**Comment by damevelue** [comment]
see screen record : https://www.youtube.com/watch?v=IGsi0vIe8Tg
