### ISSUE TITLE
VSCode doesn't reflect system font in it's menu on Fedora 24 MATE spin

### ISSUE THREAD

**Issue by rbukovansky** [electron/electron#7609]
* Electron version: N/A (issue with Visual Studio Code)
* Operating system: Fedora 24 MATE spin

Per request I'm reporting issue here as well (1st reported here: https://github.com/Microsoft/vscode/issues/13429):
I'm using Apple's San Francisco font (Display or Mono variant) for all system-wide defined font settings. But VSCode is not reflecting it in it's UI (mainly menu)... See screenshot:
![c1f8a766-8f06-11e6-912e-3ffbbc3abf36](https://cloud.githubusercontent.com/assets/1004491/19353826/f06b80b8-9164-11e6-959f-60e2dc996001.png)

Per VSCode devs it seems as issue in Electron, not in VSCode. Could you please take a look? Thanks.

**Comment by kevinsawicki** [comment]
@rbukovansky can you open the dev tools, inspect the element, go to the Computed Tab in the Elements panel and include what the Rendered Font sections says as well as the `font-family` style?

Here is a screenshot:

<img width="1280" alt="screen shot 2016-10-24 at 2 31 30 pm" src="https://cloud.githubusercontent.com/assets/671378/19634464/5ca8d28c-99f6-11e6-81b4-90a9bf867bbb.png">

**Comment by rbukovansky** [comment]
We can probably close this issue. I was need to reinstall my VM with Fedora and it seems the issue is gone with latest VSCode Insiders (or with that new VM).
And I'm not sure, but it seems to me that menu (File, Edit, View...) is not created with HTML code anyway...

Thanks and sorry!

**Comment by kevinsawicki** [comment]
> We can probably close this issue

Thanks for the update, closing this out 👍
