### ISSUE TITLE
How to close a electron dialog automatically？

### ISSUE THREAD

**Issue by EnchanterZero** [electron/electron#7613]
Hey,I am using electron dialog to show some message. 
It will disappear only when clicked button. If you do nothing, the dialog will persist al the time.
Is there any method to automatically close the dialog?
Thanks in advance.  :)

**Comment by kevinsawicki** [comment]
> Is there any method to automatically close the dialog?

There isn't one currently, please subscribe to #5577 for future updates about this.

**Comment by EnchanterZero** [comment]
OK,thank you :)
