### ISSUE TITLE
Add Tray hover event

### ISSUE THREAD

**Issue by zhangmingze** [electron/electron#7616]
- Electron version:1.3.3
- Operating system:win10/mac

the Tray instance events shold provide the tray hover event. 
`tray.setToolTip` has limitations when do more operation.

**Comment by zcbenz** [comment]
I'm closing this as won't fix since no platform provides this ability as far as I know.

**Comment by zcbenz** [comment]
Hmm reopening since it seems to be at least possible on mac.

**Comment by zcbenz** [comment]
A more general implementation is to add `mouse-enter` and `mouse-leave` events, which can also solve other problems.

**Comment by gclsoft** [comment]
https://electronjs.org/docs/api/tray#event-mouse-enter-macos
event-mouse-enter is works only on mac, not on Windows, right??
