### ISSUE TITLE
Extending shadow under scrolling area

### ISSUE THREAD

**Issue by samad-aghaei** [electron/electron#7618]
* Electron version: 1.4.3
* Operating system: MacOS Sierra
![electron-scrolling-shadow-bug](https://cloud.githubusercontent.com/assets/3668436/19376195/71363a6e-9190-11e6-83b5-ad6e3610e5c2.png)

Just set a simple shadow to html:before and put it under body which is clipped by a rounded path and looks nice, but when scrolling down the content inside body and content meets the edge of app, shadow will extending by scrolled content on top and bottom of the app's window.
By scrolling more, the extended shadow will get ticker and ticker.
This happened in MacOS not windows. 
The HTML document is very simple and as I believe that this is not related to CSS or HTML codes. I'd use css filter, transparent border, box-shadow, svg filter but the result was same. Looks like that this will happen on any Transparent-shadowd element under scrolling area.
Scroller: http://idangero.us/swiper/demos/32-scroll-container.html

In the same app, same problem will happen when user clicking on ng-material buttons.
I had another problem on same app in MS Windows, by clicking on select module of ng-material, scrollbar will show on the right side of app's window!

html:before{
shadow-box: 0 0 3px #000;
(...)
}
body{
margin: 5px;
-webkit-clip-path: inset(0px 0px 0px 0px round 10px 10px 10px 10px);
(...)
}

**Comment by MarshallOfSound** [comment]
Does this occur in Chrome on macOS?

**Comment by samad-aghaei** [comment]
Only in Electron, it does not occur in regular browsers.
It may related to GPU!

**Comment by zcbenz** [comment]
This should be related to how Chromium renderers scroll area on macOS, you don't see it in regular browsers because they are not using transparent frameless window.

I'm not sure whether it is a bug of Chromium or macOS, but unfortunately we are unable to fix this in either case, and I'm sorry I have to close this as won't fix.
