### ISSUE TITLE
Geolocation api does't work

### ISSUE THREAD

**Issue by ncorj** [electron/electron#7620]
* Electron version:1.4.3
* Operating system:Windows 10

Hi I'm developing a desktop application with electron and I need to get the current user location. 
However the geolocation API doesn't seem to work.
After building electron with my own key the geolocation API returns the current location.

I have no problem building it myself with my own google api key, but I'm wondering if there won't be any legal issues when I'll try to publish the app deployed with my custom electron build.

**Comment by MarshallOfSound** [comment]
> After building electron with my own key the geolocation API returns the current location.

Electron uses a default API key, it's quote will get overwhelmed quite quickly.  You should use your own 👍 

> but I'm wondering if there won't be any legal issues when I'll try to publish the app deployed with my custom electron build.

Electron is open-source, build it however you want 👍
