### ISSUE TITLE
Feature request : set and get active virtual desktop on macOS

### ISSUE THREAD

**Issue by lawnzapper** [electron/electron#7623]
It would be nice to get and set which active virtual desktop you are using on macOS when opening/calling you app

**Comment by kevinsawicki** [comment]
I believe this is similar to https://github.com/electron/electron/issues/5362, please subscribe to that issue for updates.

**Comment by 10SPD** [comment]
Are there any updates on this. Would love to be able to launch our app and have it open on its own in a virtual desktop.

If you know of any other options to do this it would be appreciated as cannot seem to find anything online.
