### ISSUE TITLE
Prerendering pages

### ISSUE THREAD

**Issue by davej** [electron/electron#7625]
Perhaps the [`prerender` link relation type](https://www.w3.org/TR/resource-hints/#dfn-prerender) is an opportunity to codify the pattern of pre-loading hidden windows on application launch. It seems to be a pretty common pattern for multi-window Electron apps as it improves the 'perceived performance' and 'native-feel' of an app.

For example:

```js
// main.js
const win = new BrowserWindow({
  // ...
  show: false,
});
win.loadURL(`file://${__dirname}/foo.html`);

ipcMain.on('launchFooWindow', () => {
  win.show();
});
```

If `prerender` was implemented (See #7624) and the prerendered resources were accessible across the entire application then you could do this:

```html
<!-- app.html -->
<link rel="prerender" href="foo.html">
```

```js
// main.js
ipcMain.on('launchFooWindow', () => {
  const win = new BrowserWindow({
    // ...
    show: true,
  });
  win.loadURL(`file://${__dirname}/foo.html`);
});
```

This is a more declarative and elegant solution (IMHO) but it could also define a lower priority for windows that are being prerendered ([as described here](https://www.chromium.org/developers/design-documents/prerender)) so that it doesn't degrade the loading performance of foreground windows.

**Comment by zcbenz** [comment]
I'm closing this for the same reason with https://github.com/electron/electron/issues/7624#issuecomment-255656240.
