### ISSUE TITLE
Uncaught TypeError: fs.readFileSync is not a function

### ISSUE THREAD

**Issue by AdamKyle** [electron/electron#7626]
* Electron version: 1.4.3
* Operating system: Mac OSX Seira 10.12.1 Beta(16B2548a)

So heres the issue. I have the following `.babelrc` file:

```json
{
  "presets": [
    "react",
    "stage-0",
    "stage-1",
    "es2015"
  ],
  "plugins": [
    "transform-class-properties",
    "transform-decorators-legacy",
  ]
}
```

Now I have the following gulp file:

```js
var gulp        = require('gulp');
var source      = require('vinyl-source-stream');
var browserify  = require('browserify');
var babelify    = require("babelify");
var watch       = require('gulp-watch');

gulp.task('make:game', function(){
  return browserify({
    debug: true,
    entries: [
      'index.js'
    ]
  })
  .transform('babelify', {
    sourceMaps: false,
  })
  .bundle()
  .pipe(source('index.js'))
  .pipe(gulp.dest('app/'));
});
```

Whats this all matter for? because consider the following index.js file which is then included at the bottom (after being compiled obviously) of the index.html, which is loaded as the view when electron boots up.

```js
import App   from './src/app';
import electron, {remote} from 'electron';

App('file://' + __dirname);
```

This compiles fine. But now we see the error: `Uncaught TypeError: fs.readFileSync is not a function`

So lets throw a `console.log()` in the index.js of the electron project:

(on the left is the `fs` and on the right is the `path`)

![screen shot 2016-10-14 at 12 03 10 pm](https://cloud.githubusercontent.com/assets/188563/19398197/b1b8e47e-9208-11e6-9355-e789ac8cb14c.png)

So heres my questions: why is my import failing? Why is fs empty? Whats going on?

**Comment by davej** [comment]
This isn't an electron issue. Try the [discussion forum instead](https://discuss.atom.io/c/electron).

My guess would be that browserify is overwriting `fs`, which makes sense because browserify is designed for the browser, not for node. I can't think of a reason why you would use browserify with Electron unless you have `nodeIntegration` turned off.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

As @davej said this is a browserify thing.  I think you need the `--no-builtins` option

**Comment by ericsoco** [comment]
Don't have an answer for you (yet?), @AdamKyle, but Browserify and Electron can definitely coexist:
http://maxgfeller.com/blog/2016/08/30/electron-browserify/

Still working through the details and only have it running via the `npm` `electron` module so far, not as a packaged app, but making progress. If I figure anything out relevant, I'll report back here. If you continued the discussion elsewhere (e.g. community/forum/Slack) please let me know.
