### ISSUE TITLE
Support dynamically changing a menu item's label

### ISSUE THREAD

**Issue by joshaber** [electron/electron#7627]
* Electron version: 1.4.3
* Operating system: macOS Sierra

From poking around, it looks like the menu controller supports it (https://github.com/electron/electron/blob/787bc8570382e98c4f204abff05b2af122e5a422/atom/browser/ui/cocoa/atom_menu_controller.mm#L216). We need a way of marking a `AtomMenuModel` as dynamic.

**Comment by bengotow** [comment]
It sounds like this shares the same goal as https://github.com/electron/electron/issues/528 (being able to build a menu just before display, rather than ahead of time)

**Comment by zcbenz** [comment]
I'm merging this to  #528.
