### ISSUE TITLE
globalShortcut successfully registers but doesn't trigger callback on press with `PrintScreen`

### ISSUE THREAD

**Issue by dzek69** [electron/electron#7629]
- Electron version: 1.4.3
- Operating system: Linux Mint 17.3 Cinnamon x64

So I wanted to register `PrintScreen` key as global shortcut but I'm unable to do that. I've tried disabling all Cinnamon hotkeys related to that key but no luck. Tried restarting Cinnamon, tried restarting whole OS. Both when `PrintScreen` was used by Cinnamon and now (when it's not) this code gave the same result - shortcut seems to be registered fine, but doesn't trigger a callback.

It works fine with `F12` for example

Quick example:

``` javascript
app.on('ready', () => {
    const ret = globalShortcut.register('PrintScreen', () => {
            console.log('is pressed') // never called
    })
    console.log(ret); // true
    console.log(globalShortcut.isRegistered('PrintScreen')) // true
})
```

Anyone can confirm? Any solutions?

**Comment by zcbenz** [comment]
It is because Chromium doesn't map the `PrintScreen` to actual X11 key code, we need to patch https://cs.chromium.org/chromium/src/ui/events/keycodes/keyboard_code_conversion_x.cc?&sq=package:chromium to fix this.

**Comment by codebytere** [comment]
Closing as `wontfix`, we would prefer to not patch Chromium more than necessary.
