### ISSUE TITLE
Incorrect position when restored from maximize-on-top-drag under Windows

### ISSUE THREAD

**Issue by nyz93** [electron/electron#7630]
- Electron version: 1.4.1
- Operating system: Windows 7 and 10

If you drag the window to the top edge to maximize it, and then call `restore()` or `unmaximize()` the window will move to the top, where the maximization happened, usually slightly out of view. 
With the regular Windows restore button it moves back to place before the drag started.

I'd really like to use a frameless window with my own window controls, but this problem comes out pretty often.

**Comment by zcbenz** [comment]
Closed with https://github.com/electron/electron/pull/7766.
