### ISSUE TITLE
Uncaught Exception: TypeError: mainWindow.webContents.setProxy is not a function

### ISSUE THREAD

**Issue by myfrndjk** [electron/electron#7636]
* Electron version:latest version
* Operating system:osx 

I am trying to read pac script but getting above error.
Followed this https://stackoverflow.com/questions/37393248/how-connect-to-proxy-in-electron-webview

`var app  = require('app')
var BrowserWindow = require('browser-window')

var mainWindow = null

app.on('window-all-closed', function() {
  if (process.platform != 'darwin') {
    app.quit()
  }
})

app.on('ready', function () {
  mainWindow = new BrowserWindow({ width: 1030, height: 720, frame: false })
  mainWindow.webContents.session.setProxy({pacScript:"file://"+root+"/js/pacfile.js"}, function () {
  mainWindow.loadUrl('file://' + require('path').join(__dirname, 'browser.html'))
});
  
  mainWindow.on('closed', function() {
    mainWindow = null
  })
})`

**Comment by deepak1556** [comment]
The error reported and snippet doesn't match, also seems like you got it working https://github.com/electron/electron/issues/7644 . Closing this out since its doesn't seem like a bug in Electron.
