### ISSUE TITLE
User Auth with Electron

### ISSUE THREAD

**Issue by Orbyt** [electron/electron#7639]
I've been asking around through a hodge-podge of different mediums trying to get a canonical answer, but keep getting conflicting info..so am hoping I can get an official answer here:

I'm a bit confused on how user auth with 3rd party services should be implemented in an Electron application. With a "regular" web app, I would likely look into using something like passport.js or any of the various SDKs from services like Facebook to implement user login and signup. My confusion arises from the fact that though Electron uses Node.js, it's still a client side app. Because of this, storing things like secret keys needed to authorize my app with these services in my code seems like a bad idea.

How in the world is this suppose to be done? The only article i've found on this topic is [here](http://manos.im/blog/electron-oauth-with-github/), but even then, the top comments on the article are voicing these same questions.

I've tried both SO and the electron forums with no responses.

A canonical answer is appreciated...thanks!

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

> I've tried both SO and the electron forums with no responses.

Slack will probably get you an answer
