### ISSUE TITLE
Kiosk Mode Child Window Taskbar Bug

### ISSUE THREAD

**Issue by LordOmega** [electron/electron#7640]
* Electron version: 1.4.3
* Operating system: Windows 10

If you create a child window, which has a parent in kiosk mode, the windows taskbar is shown every time when the child window is selected.
There should be an option to disable this behavior, if this is not considerd a bug in kiosk mode.

Parent in Kiosk Mode:
![screenshot 42](https://cloud.githubusercontent.com/assets/15159874/19412304/643f5bc2-9313-11e6-859f-6721b77e3005.png)
Unselected:
![screenshot 43](https://cloud.githubusercontent.com/assets/15159874/19412306/673f77da-9313-11e6-9773-2b6c255723fc.png)
Selected:
![screenshot 44](https://cloud.githubusercontent.com/assets/15159874/19412307/68a4d4da-9313-11e6-91d5-6efde5ffb69a.png)

**Comment by kevinsawicki** [comment]
Are you setting `skipTaskbar` to `true` in the created `BrowserWindow`?

**Comment by LordOmega** [comment]
Yes I am using skipTaskbar.

**Comment by LordOmega** [comment]
Yes I am using skipTaskbar.

**Comment by LordOmega** [comment]
But the same thing happens when i do not use skipTaskbar. It only doesnt show the Icon in the  taskbar.

**Comment by LordOmega** [comment]
The same thing happens if i do not use skipTaskbar.

**Comment by LordOmega** [comment]
Sorry for accidentally closing the issue.

**Comment by LordOmega** [comment]
Selected (with skipTaskbar)
![screenshot 45](https://cloud.githubusercontent.com/assets/15159874/19661611/a7f047a0-9a34-11e6-9ff4-f8e9614e33d2.png)
