### ISSUE TITLE
How to  reset proxy.pac file in middle of session

### ISSUE THREAD

**Issue by myfrndjk** [electron/electron#7644]
* Electron version:Latest
* Operating system:osx

I am using PAC to route my webview traffic, I am using following code but it doesn't reset my proxy even though the proxy.pac has changed/modified.

`const {app, BrowserWindow} = require('electron');

let mainWindow;

app.on('window-all-closed', function() {
  app.quit();
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 1024, height: 768 });
  webPreferences: {
  		webSecurity: false      
    }

   mainWindow.webContents.session.setProxy({pacScript:'file://' + __dirname + '/fun.pac'}, function () {
    mainWindow.loadURL('file://' + __dirname + '/browser.html');
});

  mainWindow.openDevTools();
});
`

**Comment by deepak1556** [comment]
`session.setProxy` will download the pac file and set the sessions' proxy. It is not aware of pac file changes, you need to call the api again..

**Comment by myfrndjk** [comment]
Thanks @deepak1556
 I tried something like this and it worked

`const {app, BrowserWindow} = require('electron');
const {session} = require('electron')

let mainWindow;

app.on('window-all-closed', function() {
  app.quit();
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 1024, height: 768 });
  session.defaultSession.allowNTLMCredentialsForDomains('*')//internal url authentication

var myVar = setInterval(myTimer, 60000);
function myTimer() {
mainWindow.webContents.session.setProxy({pacScript:'file://' + __dirname + '/proxy.pac'}, function () {return true;});
}

mainWindow.webContents.session.setProxy({pacScript:'file://' + __dirname + '/proxy.pac'}, function () {mainWindow.loadURL('file://' + __dirname + '/browser.html');});`
