### ISSUE TITLE
[Linux - GTK] Titlebar/Menu GTKRC not matching when using the Browser option 'dark-theme'

### ISSUE THREAD

**Issue by nikolowry** [electron/electron#765]
Titlebar/Menu GTKRC not matching:
![Theme Mismatch](http://f.cl.ly/items/1X1L343E0N070L3P2D0k/Screenshot%20from%202014-10-31%2017-35-12.png)
![Theme Mismatc](http://f.cl.ly/items/2f1i0l2R1v151D0b1E3p/Screenshot%20from%202014-10-31%2017-34-38.png)

---

Are there any attempts being made to package a dark GTKRC theme with Atom Shell?  I started using Linux after GTK2's heyday and I understand that legacy theming can be a nightmare.  

As an end user, I've only been able to make dark GTK themes match up by following these set of instructions http://goo.gl/V1H5Zx.

**Comment by varemenos** [comment]
:+1:

**Comment by bhack** [comment]
:+1:

**Comment by kurisubrooks** [comment]
:+1:

**Comment by nikolowry** [comment]
Building libchromiumcontent/brightray/electron with gtk3 fixes this bug:

![screenshot from 2016-05-24 02-51-28](https://cloud.githubusercontent.com/assets/597310/15494841/a0579b68-215a-11e6-96ad-1ee8547760b3.png)
![screenshot from 2016-05-24 02-51-49](https://cloud.githubusercontent.com/assets/597310/15494839/9d011bba-215a-11e6-8ead-4dd340142c15.png)

https://goo.gl/ydHspu

**Comment by kurisubrooks** [comment]
I've been aware of this "fix" for a while, but it's not included/bundled into Electron by default, hence the problem :disappointed:

**Comment by nikolowry** [comment]
@kurisubrooks I vaguely documented what you need to do in #2927.  I'm trying to decide if the best way forward is to propose a pull request (since it spans 3 repos) or just uploading a gist of a bash/node script instead.

**Comment by nikolowry** [comment]
@kurisubrooks https://github.com/nikolowry/electron-gtk3

**Comment by kurisubrooks** [comment]
Useful! Thanks a bunch!

**Comment by skewty** [comment]
has any progress been made on this?

**Comment by jhasse** [comment]
> has any progress been made on this?

Check #2927 for progress, it will fix this issue too.

**Comment by bil-elmoussaoui** [comment]
This was already fixed! Now we should wait for the apps to update to the latest electron version :+1:

**Comment by codebytere** [comment]
Closing as fixed!
