### ISSUE TITLE
Cannot call getURL because the webContents is unavailable 

### ISSUE THREAD

**Issue by myfrndjk** [electron/electron#7653]
- Electron version:1.4.3
- Operating system:osx,windows,ubuntu

How to reproduce this
Download this
https://github.com/pfrazee/electron-browser

rename  index.js --> main.js
modify main.js as below

`const {app, BrowserWindow} = require('electron');
const {session} = require('electron')

let mainWindow;

app.on('window-all-closed', function() {
  app.quit();
});
app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 1024, height: 768 });
  session.defaultSession.allowNTLMCredentialsForDomains('*')
mainWindow.loadURL('file://' + __dirname + '/browser.html')
  mainWindow.openDevTools();
});`

Replcae package.json with below content

`{
  "name": "Browser Sample",
  "version": "1.1.0",
  "main": "main.js"
}`

in browser.jsx change variable as below

`'use strict'
var remote = require('electron').remote
const {Menu, MenuItem} = remote
var urllib = require('url')
var clipboard = require('electron')`

Now give
electron /path/to/appname

1.open new tab
2.come back to tab-1

it will keep on loading and throw below error

web-view.js: 416 Uncaught Error: Cannot call canGoBack because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

I am not sure issue belongs to  electron version 1.4.3 or some dependency issue.
Same code works fine if i run as it is using [npm start]
They are other threads also for this type of issue but no fixes are given.

[1087](https://github.com/brave/browser-laptop/issues/1087)
[122](https://github.com/mchristopher/PokemonGo-DesktopMap/issues/122)

**Comment by deepak1556** [comment]
Can you provide a minimal example to reproduce the issue, its not possible to track down with another project. Thanks!

**Comment by myfrndjk** [comment]
Sure will try to reproduce this in some other way :)

**Comment by azer** [comment]
I'm hitting this error if I upgrade [my project](http://github.com/kaktus/kaktus) from 1.4.1 to 1.4.3

**Comment by ramkrk** [comment]
It might be related this https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md#css-styling-notes.  Webview may reload the contents when you have multiple webview and show, hide them using css displayproperty. Please verify this process.

**Comment by azer** [comment]
@ramkrk that's not the case

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.

If you are still experiencing this please include a small reproduction example and we'll investigate further.

**Comment by djalmaaraujo** [comment]
@kevinsawicki I can reproduce this easily like this:

Create a window and load some HTML like this:

```js
myWindow.loadURL(`data:text/html,<p>EAE</p>`);
```

Try to use anything else from webContents, etc, simply doesn't work.
