### ISSUE TITLE
TypeError: Error processing argument at index 0, conversion failure from C:\Users\root\path\to\logo.ico

### ISSUE THREAD

**Issue by tex0l** [electron/electron#7657]
* Electron version: 1.4.3
* Operating system: Windows 10 under VirtualBox 5.0.26 r108824 running on OSX 10.11.6

Hi guys,
I'm having trouble with an error that happens randomly at launch:
I have an icon located at 
```javascript
const iconPath = "C:\Users\root\path\to\logo.ico"
```
And sometimes the line 
```javascript
const trayIcon = new Tray(iconPath)
```
throws the error 
>`TypeError: Error processing argument at index 0, conversion failure from C:\Users\root\path\to\logo.ico`.

Has anyone got an idea why this line sometimes throws an error and sometimes works properly, with the ico file being strictly the same ?

**Comment by MarshallOfSound** [comment]
I've been seeing this error on Electron `1.4.3` as well.  It is very rare but for me only occurs on macOS.  Across thousands of installs it has happened 37 times in the last 24 hours.

![error](https://cloud.githubusercontent.com/assets/6634592/19461560/50060244-9531-11e6-83cc-23c67f684d84.PNG)

**Comment by arantes555** [comment]
Seeing the same thing here, on windows only.

**Comment by MarshallOfSound** [comment]
🔗 https://sentry.io/gpmdp/electron-client/issues/171064047/

**Comment by luoye-fe** [comment]
+1 .. 
But only recurrent on windows, and after updating `npm` from `3.8.5` to  `3.10.9`.

**Comment by luoye-fe** [comment]
It's so speechless ...

Just because of missing a picture ...

**Comment by zcbenz** [comment]
This error happens when the icon does not exist for any reason, throwing exception for this was a decision made on the first day and I'm still not sure whether it is a good design.

Anyway if you want to ignore this error you can use `naitveImage` to create an icon from path and then pass it to `Tray`, and it silences the error.

**Comment by MarshallOfSound** [comment]
@zcbenz I managed to get one of my users with the error being thrown to check their app directory and the file exists within the ASAR.  Is their anything else that could cause this?

**Comment by tex0l** [comment]
In my case it happens when the app isn't packaged into an asar yet.
When I run my app multiple times from the same directory (starting without rebuilding my code and resources), it sometimes works, and sometimes it doesn't. Out of 50 launches from the same directory: 30 crash with the error, 20 successfully start the app and have the icon in the tray.
I haven't had the problem with the packaged app since I ship my windows version with a PNG instead of an ICO, and it seems more stable.

**Comment by darkpixel** [comment]
I can't tell if I'm running in to this problem, or if I'm just a n00b about packaging/referencing assets.
If I create a tray icon ```Tray('favicon.ico');``` it shows up while I'm debugging and running it via ```electron main.js```.

Once I build it, I get the error ```TypeError: Error processing argument at index 0, conversion failure from ...```

If I change it to ```Tray(app.getAppPath(), 'favicon.ico'));``` and build it, it works fine, but during development the path resolves to ```/tank/code/myapp/node_modules/electron-prebuilt/dist/resources/default_app.asar/favicon.ico``` when I think it should resolve to ```/tank/code/myapp/favicon.ico```.

**Comment by isNeilLin** [comment]
You can specify an absolute path. like this:
![image](https://cloud.githubusercontent.com/assets/18683728/19801708/ee57c29e-9d32-11e6-98f6-455bbac83af8.png)

**Comment by darkpixel** [comment]
Thanks @isNeilLin .

**Comment by stop2stare** [comment]
Thanks @isNeilLin ,but it's still not working correctly even I've specified an absolute path.
Do you have any other workaround?

**Comment by limoragni** [comment]
This is happening to me also. I have around 20 users and this is happening to only one of them, but he can't even boot the app. Will try using NativeImage and see what happens.

**Comment by teterovic** [comment]
Have the same issue MACOS

**Comment by tbogard** [comment]
I was able to solve it figuring out if the file exists in the project files or not. for that I have first to verify the existence of the file, then convert the image as nativeImage. I'm using fs-jetpack to verify quickly if it is "file" the output of the console... The problem is that likely you guys are pointing to a file where the app doesn't have access....

`
const {
	app,
	Tray,
	Menu,
	ipcMain,
	nativeImage
} = require('electron');
const main       = require('../main');
const path = require('path');
const jetpack = require('fs-jetpack');
let appIcon = null;

ipcMain.on('go-tray', (event) => {
	const iconName = '16.png';
	const iconPath = path.join(__dirname,'..','assets','icons',iconName);
        console.log(jetpack.exists(iconPath)); //should be "file"
	let nimage = nativeImage.createFromPath(iconPath); 
	appIcon = new Tray(nimage);
	const contextMenu = Menu.buildFromTemplate([{
		label : 'Restore to Design Mode',
		click : () =>{
			appIcon.destroy();
			main.mainWindow.show();
		}
	}]);
	appIcon.setToolTip('app is on tray mode.');
	appIcon.setContextMenu(contextMenu);
	main.mainWindow.hide();
});

app.on('window-all-closed',() => {
	if (appIcon) appIcon.destroy();
});
`

**Comment by littletinman** [comment]
I'm having this issue on Windows 10 only after building the electron app for deployment.

Versions
```
electron 1.6.11
electron-packager 8.7.2
```

Code
```
const trayIcon = path.join(__dirname, 'icons/icon-16x16.png');
const tray = new Tray(trayIcon);
```

**Comment by tbogard** [comment]
@littletinman You have to pass the TrayIcon a native image object. what you are passing is a STRING instead of nativeImage:

```
const trayIcon = path.join(__dirname, 'icons/icon-16x16.png');
const nimage = nativeImage.createFromPath(trayIcon);
const tray = new Tray(nimage);
```

In that way the trayIcon will work

**Comment by MarshallOfSound** [comment]
@tbogard Passing a string is perfectly valid, if the string is a valid path to an image it will be correctly interpreted and loaded.

**Comment by JoeGrasso** [comment]
If you are a Windows user, the problem had nothing to do with the image path but rather the setBounds values. The short of it is you must parseInt the values for the coordinates. This works for me:

> const {app, BrowserWindow, Menu, Tray} = require('electron');
> const {join} = require('path');
> 
> let mainWindow, tray;
> 
> app.on('ready', () => {
>     mainWindow = new BrowserWindow({
>         height: 500,
>         width: 300,
>         frame: false,
>         resizable: false,
>         // draggable: true,
>         show: false
>     });
>     mainWindow.loadURL(`file://${__dirname}/src/index.html`);
> 
>     const iconName = process.platform === 'win32' ? 'windows-icon@2x.png' : 'iconTemplate.png';
>     const iconPath = join(__dirname, `./src/assets/${iconName}`);
>     tray = new Tray(iconPath);
>     const contextMenu = Menu.buildFromTemplate([
>         {label: 'Item1', type: 'radio'},
>         {label: 'Item2', type: 'radio'},
>         {label: 'Item3', type: 'radio', checked: true},
>         {label: 'Item4', type: 'radio'}
>     ]);
>     tray.setToolTip('Right Click Icon for Options.');
>     tray.setContextMenu(contextMenu);
>     tray.on('click', (ev, bounds) => {
>         // Click event bounds
>         const {x, y} = bounds;
>         // Window height & width
>         const {height, width} = mainWindow.getBounds();
> 
>         if (mainWindow.isVisible()) {
>             mainWindow.hide();
>         } else {
>             const yPosition = process.platform === 'darwin' ? y : parseInt(y - height);
>             const xPosition = process.platform === 'darwin' ? x - width / 2 : parseInt(x - (width/2));
> 
>             mainWindow.setBounds({
>                 x: xPosition,
>                 y: yPosition,
>                 height,
>                 width
>             });
>             mainWindow.show();
>         }
>     })
> });

**Comment by ue** [comment]
I have same issue WIN and OSX both of them. How can i resolve?

**Comment by joelclipperton** [comment]
When I place the icon in the same directory as main.js with new Tray('icon.png') it works. If there's a sub folder, with the icon and the path is 'folder/icon.png' it never works, regardless of using path.join(__dirname, 'folder/icon.png') or './folder/icon.png'.  

Logging __dirname prints out the root folder path, so appending a folder/file to it shouldn't be an issue, yet it appears any attempts besides my initial one with the icon in the same folder works. 

This is upsetting to say the least.

**Comment by caiobsouza** [comment]
@ue / @JoeGrasso   Had the same problem and `Math.floor`  fixed it:
```const yPosition = process.platform === 'darwin' ? y : y - height;
const bounds = {
     x: Math.floor(x - width / 2),
     y: Math.floor(yPosition),
     height,
     width
 };

**Comment by eveningkid** [comment]
In case someone ends up here without finding a solution that works, here are the steps I'd recommend:
- are you passing a *NativeImage* value to `Tray` constructor? If not:
```js
// If not already imported
// const path = require('path');
const iconPath = path.join(__dirname, 'tray-icon.png');
const trayIcon = nativeImage.createFromPath(iconPath);
const tray = new Tray(trayIcon);
```
- does your icon follow any of the [*NativeImage* supported formats](https://electronjs.org/docs/api/native-image#supported-formats)? **PNG and JPEG** are the only two formats supported on all platforms.
- remember that your icon should be **sized 16*16px**

**Comment by ssas01** [comment]
@isNeilLin very thank you!

**Comment by YellowPure** [comment]
- electron version: **8.0.0**
- platform: **macOS 10.15 x64**

 ### this problem still appear !!

`TypeError: Error processing argument at index 0, `

I tried  fs.access check the png is existed; 
i tried:
`appIcon = new Tray('icon.png');
appIcon = new Tray(path.join(__dirname, 'icon.png');
`
it's still not work, the error always here.

so said.

**Comment by dsteinman** [comment]
This is a showstopping bug, all version of Electron should be removed from NPM, and Electron Forge.

**Comment by dsteinman** [comment]
Why was this issue closed?  This bug exists in Electron 8.2.3 (macosx), the latest version released just 4 days ago.

**Comment by NtTestAlert** [comment]
This issue is extremely annoying on both windows and macos. The icon files need to be crafted with magic spells, and randomly stop working once every couple electron updates. The image handling code should be re-written. For example, if you have 1024x1024 icon in .ico it wont work - WHY? Just discard the icon you dont need and not crash the entire application during startup. I know ico should not include icon of this size but this is an unnecessary bug that has been around forever.

**Comment by bartoszhernas** [comment]
I can confirm that the issue was missing Math.floor and sending floating numbers to window
```
    window.setPosition(x, y);
```
replaced with 
```
    window.setPosition(Math.floor(x), Math.floor(y));
```

We are calculating position to put 2 windows in center next to each other, and it could happen the numbers were floating point numbers and not whole. Crashes only on Windows. Rounding the numbers fixed the issue.

**Comment by nside** [comment]
same issue with NativeImage.crop

**Comment by ArnieGA** [comment]
> I was able to solve it figuring out if the file exists in the project files or not. for that I have first to verify the existence of the file, then convert the image as nativeImage. I'm using fs-jetpack to verify quickly if it is "file" the output of the console... The problem is that likely you guys are pointing to a file where the app doesn't have access....
> 
> ```
> const {
> 	app,
> 	Tray,
> 	Menu,
> 	ipcMain,
> 	nativeImage
> } = require('electron');
> const main       = require('../main');
> const path = require('path');
> const jetpack = require('fs-jetpack');
> let appIcon = null;
> 
> ipcMain.on('go-tray', (event) => {
> 	const iconName = '16.png';
> 	const iconPath = path.join(__dirname,'..','assets','icons',iconName);
> 	console.log(jetpack.exists(iconPath)); //should be "file", otherwise you are not pointing to your icon file 
> 	let nimage = nativeImage.createFromPath(iconPath);
> 	appIcon = new Tray(nimage);
> 	const contextMenu = Menu.buildFromTemplate([{
> 		label : 'Restore to Design Mode',
> 		click : () =>{
> 			appIcon.destroy();
> 			main.mainWindow.show();
> 		}
> 	}]);
> 	appIcon.setToolTip('app is on tray icon');
> 	appIcon.setContextMenu(contextMenu);
> 	main.mainWindow.hide();
> });
> 
> app.on('window-all-closed',() => {
> 	if (appIcon) appIcon.destroy();
> });
> ```

Confirming that this solution worked for me.

**Comment by AlexStormwood** [comment]
Chiming in with another potential solution for people to try. This code was failing for me:

```js
	if (process.platform === 'win32') {
		tray.on('click', tray.popUpContextMenu);
	}
```

This code works and does not generate the error:

```js
	if (process.platform === 'win32') {
		tray.on('click', (event, bounds) => {
			tray.popUpContextMenu();
		});
	}
```

Looks like declaring the arguments matters, even if you don't use them.
