### ISSUE TITLE
Menu.setApplicationMenu() doesn't work for tray apps

### ISSUE THREAD

**Issue by davej** [electron/electron#7662]
Initially this seems reasonable as tray apps don't have an Application Menu like windowed apps do. The problem is that this makes it impossible to register application-wide accelerator shortcuts. My tray app has a menu like this:

![image](https://cloud.githubusercontent.com/assets/26971/19476577/db97c3b0-9531-11e6-9771-b56124d8d9a7.png)

The accelerators in the screenshot only work when the context menu is open. I am able to get around this by listening to the `keydown` events emitted by the browser, however I need to do this in every browser window.

My proposal is that when you do `Menu.setApplicationMenu(menu)` with a tray application then it should register the accelerators in `menu` (but do nothing else).

* Electron version: 1.4.3
* Operating system: MacOS Sierra

**Comment by davej** [comment]
This is somewhat related to #1334.

**Comment by zcbenz** [comment]
On macOS calling `Menu.setApplicationMenu` registers the accelerators of menu regardless of whether the app is a tray app, however your app must have a dock icon to make the key shortcuts work, and key shortcuts only work when your app is focused.

If you want to make key shortcuts work when your app is not focused, you can to register global key shortcuts.
