### ISSUE TITLE
Cut/Copy/Paste/etc. do not work from Application Menu

### ISSUE THREAD

**Issue by rchristilaw** [electron/electron#7663]
* Electron version: 1.4.3
* Operating system: Windows 7 Professional x64

The following steps are based on my application which has an "Edit" application menu with the following buttons (and associated default roles and accelerators) Undo, Redo, Cut, Copy, Paste, Select All.

Steps to Reproduce:
1. Enter text into a field
2. Select the text using your mouse.
3. Open Application Menu (Edit in my case) and select "Cut".

Expected Result:
Text is cut from field (text disappears) and can be pasted in another field

Actual Result:
Text remains in the field and cannot be pasted elsewhere.

Notes:
- This bug is present for all of the menu items that have a default role associated. Custom click events execute properly.
- I am able to cut and paste using keyboard shortcuts (Ctrl+X, Ctrl+V).
- Seems to be working in Electron v1.4.2

**Comment by webchef** [comment]
The same behavior is with Kubuntu Linux 

$ cat /proc/version
Linux version 4.4.0-45-generic (buildd@lgw01-34) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016

I am using a mac with macOS 10.12 Sierra with electron-builder to build for macOS, Windows (wine) and Linux. 
- npm: 3.9.5
- electron-builder: 7.14.2
- electron: 1.4.4
