### ISSUE TITLE
renderer process crash with white screen on arm-linux 

### ISSUE THREAD

**Issue by wb2110** [electron/electron#7668]
* Electron version:1.4.3
* Operating system: debian jessie lxde armv7l s5pv4418 1G RAM
I make a BrowserWindow to request a page of my nodejs express server and in the page
I use mediaRecorder API to record audio to base64 string  then post to my server
when the data less than about 11MB(about 2minutes audio) ,i posted successfully,once a little bigger than 11MB the renderer process crash`     
           var socketio = io();
            
            var mediaStream = null;
            
            socketio.on('connect', function() {
                //startRecording.disabled = false;
            });

            var startRecording = document.getElementById('start-recording');
            var stopRecording  = document.getElementById('stop-recording');
            var cameraPreview  = document.getElementById('camera-preview');
            
            var progressBar = document.querySelector('#progress-bar');
            var percentage = document.querySelector('#percentage');

			var recordAudio;
			 navigator.getUserMedia({
                        audio: true,
                        video: false
                    }, function(stream) {
                    	
                        mediaStream = stream;
                         var options = {
									      mimeType: 'audio/ogg', // or video/mp4 or audio/ogg
									     // audioBitsPerSecond: 128000,
									      //videoBitsPerSecond: 128000,
									      bitsPerSecond: 64000 ,// if this line is provided, skip above two
										   numberOfAudioChannels: 1,
										  //sampleRate: 22050
                     					//recorderType: StereoAudioRecorder			    
                         };
						recordAudio = RecordRTC(stream,options);
                        //recordAudio.startRecording();

                        //stopRecording.disabled = false;
                    }, function(error) {
                        alert( JSON.stringify( error ) );
                    });
                    
 			var a=0;
 			var interval;
            startRecording.onclick = function() {
                //startRecording.disabled = true;
               	recordAudio.startRecording();
               	
			interval=setInterval(()=>{
				console.log(a++);
			},1000);
            };

			
            stopRecording.onclick = function() {
            	clearInterval(interval);
            	console.log(a);
            	a=0;
            	
      			recordAudio.stopRecording(function() {
                    // get audio data-URL
                    try{
                    	    recordAudio.getDataURL(function(audioDataURL) {
                    	console.log(typeof audioDataURL);
                      
						$.ajax({
							type:"post",
							url:"/upload",
							async:true,
							data:{
                                type: recordAudio.getBlob().type || 'audio/wav',
                                dataURL: audioDataURL,
                       		 },
							success:(data)=>{
								console.log(data);
							},
							error:(data)=>{
								console.log(data);
							}
						});
                       // socketio.emit('message', files);
                      //  if(mediaStream) mediaStream.pause();
                    });
                    	
                    }
                    catch(err)
                    {
                    	console.log(err);
                    }
                
                 });
            };
` 
and server side `router.post('/upload', function(req, res, next) {
	console.log(req.body.dataURL);
	res.send('ok');
	return;
	
});`
there is no issue on windows 7 64bit and ubuntu 14.04 
,any one give me some tips?

**Comment by MarshallOfSound** [comment]
Use the `--disable-gpu` flag.  It helps on linux sometimes 👍

**Comment by wb2110** [comment]
it seems like that there is not enough memory lead to this ,but i don't know where use the memory out

**Comment by kevinsawicki** [comment]
> there is no issue on windows 7 64bit and ubuntu 14.04 
> it seems like that there is not enough memory lead to this ,but i don't know where use the memory out

Closing this out for now then. Please comment if you investigate further and believe this to be a memory leak in Electron.
