### ISSUE TITLE
Support IPC in webview without nodeIntegration

### ISSUE THREAD

**Issue by buremba** [electron/electron#7669]
* Electron version: 1.4.3
* Operating system: MacOs

It would be nice if we could communicate with sandboxed webview using IPC. Currently, when we don't enable `nodeIntegration`, webview can't use IPC because it needs to use `require() `call from node. As a workaround, we load a script that overrides global node objects and only allow access to `electron.ipcRenderer` using `preload` feature but we're not sure that this is safe. I believe that this is a common use-case since we may run untrusted script on webview and still be able to communicate with it like similar to `iframe`s.

**Comment by MarshallOfSound** [comment]
> As a workaround, we load a script that overrides global node objects and only allow access to electron.ipcRenderer

That's exactly what people here will recommend you do (a preload script that injects carefully scoped functions to allow access to IPC)

Just make sure you don't inject the entire require funciton, and maybe not even the entire IPC module.  Something as simple as 

```js
const { ipcRenderer } = require('electron')
window.sendThing = () => {
  ipcRenderer.send('thing')
}
```

as a preload script might be the minimum you need 👍

**Comment by buremba** [comment]
@MarshallOfSound , thanks for the quick response. Is there a simple way to override all the global node objects? Is it enough to just override the `require` object?

**Comment by MarshallOfSound** [comment]
@buremba You don't need to have `nodeIntegration` enabled for a preload script to have access to a node environment (preload scripts always have a node environment regardless of the `nodeIntegration` setting)

**Comment by buremba** [comment]
Ah, that's what I was missing. Thanks a lot @MarshallOfSound !
