### ISSUE TITLE
when i download a file from server, first time the save dialog show, when i repeat same operation the save dialog did not show。

### ISSUE THREAD

**Issue by mbigger** [electron/electron#7673]
- Electron version: 1.3.5-linux-X64
- Operating system: Ubuntu 16.04.1 LTS 64 gnome

The download action happened in the Renderer Process，if I move it to the Main Process，everything is ok.when I closed the app, the previous save dalog prompt.

The upload function(in the Renderer Process) exists the same problem in my application.

Moreover, on Windows 7, the save dialog show normally。 

I do not know how to resolve this problem，can you give me some suggestions?

additional:
i changed the desktop environment from gnome to unity, evetything is ok.

solution:
when i set window give the windows a parent ,evetything is ok ,i think i is related to the desktop environment's default action.

**Comment by kevinsawicki** [comment]
> I do not know how to resolve this problem，can you give me some suggestions?

Can you provide a minimal app that reproduces the issue? This sounds like possibly a logic issue in your app where events aren't handled correctly.

**Comment by kevinsawicki** [comment]
Closing this out until more information is provided.
