### ISSUE TITLE
Electron auto-update ignore untrusted certificate

### ISSUE THREAD

**Issue by adrianscripcariu** [electron/electron#7678]
* Electron version: 1.3.3
* Operating system: Windows 8.1

Hello 

I try to download my new version of my app from a https://example.com that has a connection not secure.

In my app I have this error webException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Is there a way to bypass this and make the download strart even if the connection is not secure?

Many thanks

**Comment by MarshallOfSound** [comment]
> Is there a way to bypass this and make the download strart even if the connection is not secure?

Use `http`?  What's the point in using an HTTPS url with an unsecure SSL certificate?

**Comment by adrianscripcariu** [comment]
My real problem is that I don't have access to the server :( so I need to find a solution but I don;t know where to start.

**Comment by MarshallOfSound** [comment]
I say again, use `http` instead of https.

If you don't have access to the server there is nothing you can do

**Comment by adrianscripcariu** [comment]
Ok understood many thanks :D

**Comment by adrianscripcariu** [comment]
I have a question 

Did you use this ... process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; 

I put it in main.js but still nothing
