### ISSUE TITLE
Chrome extension loading and Native Messaging

### ISSUE THREAD

**Issue by hss-dev** [electron/electron#7681]
* Electron version: 1.4.3
* Operating system: Windows 7, 8.1, 10

I am trying to integrate an existing chrome extension -  [https://chrome.google.com/webstore/detail/dragon-web-extension/ddaloccgjfibfpkalenodgehlhkgoahe] for use within Electron, however I am hitting a few problems with it.

Electron seems to be trying to load the extension but fails due to some potential javascript module pattern issues.
Has anyone been able to load an extension in this manner so far? 
Are there any changes required to make the standard chrome installed extension work properly?

In addition this extension requires access to some of the chrome.runtime.api.* functions, is there a plan to include functions such as connectNative to allow Chrome Native Messaging to function?

Many Thanks,

Dan

**Comment by zcbenz** [comment]
Currently we only implemented partial support for devtools extensions, so for normal extensions things may not work.

> In addition this extension requires access to some of the chrome.runtime.api.* functions, is there a plan to include functions such as connectNative to allow Chrome Native Messaging to function?

Supporting full `chrome.runtime.api.*` is never our purpose, for the Native Messaging we don't have plan to work on it.

**Comment by martinpaljak** [comment]
I don't think that extensions could be supported (different UI context) but having support for or a 3rd party module for connecting to native messaging hosts (including discovery from Chrome registry) could be beneficial.

**Comment by cleidigh** [comment]
@hss-dev 
I am also very interested in this issue which I think is related to some problems
I am seeing between Dragon and Visual Studio code - A Microsoft project I am working on
after an electron update 1.5 there seem to be several issues with electron

have you made any progress on this?
do you work on Dragon code?
I am also user of Dragon as I am disabled so this is very important to me personally
Christopher
