### ISSUE TITLE
Support different main entry points in Electron

### ISSUE THREAD

**Issue by codingfishman** [electron/electron#7683]
* Electron version: 1.4.4
* Operating system: macOS Sierra

This should be a help feature rather than a issue, but after searched the issue list, I can't find a similar one.

We have an Node project and it is designed to be a node dependency module. At the same time, it could be running in command mode with the help of Node. Thanks to Electron, now we'd like to make it an APP :)

But we want keep it an node module as well, so our users could do programing with it, and I came to the problem of the *main entry point in package.json*. As the `main` has been configured to the entry js file for node modules, and Electron looks for the same `main`. 

Can we specfy the `main` for Electron in a different keyword then, or should I keep the electron a different branch to fix the conflict? 

Thanks a lot!

**Comment by enlight** [comment]
Electron apps aren't distributed via NPM, but let's forget that for a second... Do you think users that use your module as a CLI tool or as a dependency are going to be happy to download and install an extra 100MB+ of Electron binaries/resources they have no intention of using?

The right way to do this is to create a distinct project for your Electron app, and add your module as a dependency of your app.

**Comment by codingfishman** [comment]
Thanks for pointing it out, I didn't realize the electron App project will also include many resources, that way, a seperate project is a better choice.
