### ISSUE TITLE
Electron apps hang on Windows virtual machines

### ISSUE THREAD

**Issue by nikoudel** [electron/electron#7685]
- Electron version: 1.3.6 (Visual Studio Code 1.6.1)
- Operating system: Windows 2012 R2 running on Hyper-V virtual machine

Both VS Code and Atom hang (CPU goes to 100%) after installing and restarting the editor. More info [here](https://github.com/Microsoft/vscode/issues/13882).

**Comment by bpasero** [comment]
We are using Electron 1.3.6

**Comment by enlight** [comment]
Do Chrome 52 and 53 run properly in this VM?

**Comment by nikoudel** [comment]
Yes. Chrome 53.0.2785.143 and 54.0.2840.71 run properly right now. Never had this problem in earlier versions either.

**Comment by gold** [comment]
And why would anyone be using Windows when better alternatives are freely available?

**Comment by gold** [comment]
It's a rhetorical question. No need to answer.

**Comment by zcbenz** [comment]
Can you download and open the raw Electron build and see whether the "welcome to electron" page shows?
https://github.com/electron/electron/releases/download/v1.3.8/electron-v1.3.8-win32-x64.zip

**Comment by nikoudel** [comment]
It opens fine, no hanging.

**Comment by zcbenz** [comment]
It is very likely a certain API call or some third party modules caused the hang, using a debugger to capture the stack trace of the hanged process should be able to give more information.

**Comment by nikoudel** [comment]
The issue only [appears](https://github.com/Microsoft/vscode/issues/13882#issuecomment-260454631) to happen in virtual machines with a single virtual processor.

**Comment by zcbenz** [comment]
Sorry but since the raw Electron binary works well, the bug is very likely to be caused by certain code in the app, which we do not have resources to do the debugging.
