### ISSUE TITLE
setMenuBarVisibility is not work, always return true

### ISSUE THREAD

**Issue by divefox** [electron/electron#7686]
* Electron version: 1.3.2
* Operating system: mac

I found that win.setMenuBarVisibility() function is not work for me. Whether I set true or false, it always return true (use isMenuBarVisible to test). Is anybody has the same problem? 

Pls help me! Thank you very much!

**Comment by kevinsawicki** [comment]
> Operating system: mac

`setMenuBarVisibility` is only supported on Windows and Linux, the docs should be updated to include this.

**Comment by jayarjo** [comment]
Doesn't work for me on Linux.

**Comment by NathanHawks** [comment]
Doesn't work on Windows 8.1
