### ISSUE TITLE
Profiling the main process

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [electron/electron#7687]
* Electron version: 1.4.2
* Operating system: Windows 10, OSX latest. 

Hi I am not sure how to add an issue in the help section. I am looking into profiling the electron app that we are building. We know how to profile the ui thread using chrome dev tools. Are their any similar tools to profile the main process?

Regards

**Comment by kevinsawicki** [comment]
You can use the profiler from the devtools in the main process by using node-inspector, see http://electron.atom.io/docs/tutorial/debugging-main-process-node-inspector/ for more details.
