### ISSUE TITLE
Can't run command line tool using child_process after packaged

### ISSUE THREAD

**Issue by PinkyJie** [electron/electron#7688]
* Electron version: 1.4.4
* Operating system: OSX 10.11.6

The user scenario is like this:

1. user selects a directory
2. use node's child_process to run `npm install` under this directory

The code snippets related to running command line is: (ES6)
```
import cp from 'child_process';
import { ipcRenderer } from 'electron';

export function runCommand(command, option, done) {
  const child = cp.exec(command, option);
  ipcRenderer.sendSync('newChildProcess', child.pid);
  done({
    type: 'id',
    data: child.pid
  });
  child.stdout.on('data', (data) => {
    done({
      type: 'stdout',
      data
    });
  });
  child.stderr.on('data', (data) => {
    done({
      type: 'stdout',
      data
    });
  });
  child.on('close', (code) => {
    done({
      type: 'close',
      data: code
    });
  });
}
```

In development phase, it works well. But after I package the code as dmg on Mac, the `exec` throw a "/bin/sh: npm command not found" error with an exit code 127. I'm sure I have installed `npm` on my machine.

Is there anyone know how to fix this?

**Comment by PinkyJie** [comment]
I found a note on official document, is that the reason?
![image](https://cloud.githubusercontent.com/assets/551329/19590951/1ec49cf4-97a7-11e6-8c2c-c39137956bb7.png)

Does that means if I packaged the app as `asar`, I can't use `child_process.exec` to execute command line tool in my app?

**Comment by PinkyJie** [comment]
Update:
* On Windows, this issue does not exist.
* On Mac, even I disabled the `asar` option when packaging, this issue is still there.

**Comment by PinkyJie** [comment]
I found the reason finally, but I still didn't figure out how to fix it.
The root cause is the environment variable of $PATH is wrong inside the packaged app, I run the command `process.env.PATH` on devtool, it shows `/usr/bin:/bin:/usr/sbin:/sbin`, which does not contains my `node/npm` path on my machine. 

So here comes the question: where does this `process.env.PATH` come from inside the packaged app? Is there a method to change it?

**Comment by MarshallOfSound** [comment]
@PinkyJie Just an idea here but environment variables are normally inherited from their parent shell. On macOS the path is sourced in your `.bashrc` (I believe) so when you launch your app in development from the command line the environment variable is inherited.  In production you launch it as an application and thus has no shell environment to inherit.

**Comment by PinkyJie** [comment]
@MarshallOfSound Thanks for your response. Do you know how to fix it? Is that possible that I read `.bashrc` into the application when application launched?

**Comment by kevinsawicki** [comment]
> So here comes the question: where does this process.env.PATH come from inside the packaged app? Is there a method to change it?

You might want to take a look at using something like https://github.com/sindresorhus/fix-path

Closing this out.

**Comment by PinkyJie** [comment]
@kevinsawicki  Thanks a lot!

**Comment by starriv** [comment]
Thank you for solving a big problem

**Comment by tangzhihua123** [comment]
npm install -save fix-path  It works fine when I run electron . from my-app. However, once packaged   I see "Error: Cannot find module"

**Comment by tangzhihua123** [comment]
> > So here comes the question: where does this process.env.PATH come from inside the packaged app? Is there a method to change it?
> 
> You might want to take a look at using something like https://github.com/sindresorhus/fix-path
> 
> Closing this out.

npm install -save fix-path It works fine when I run electron . from my-app. However, once packaged I see "Error: Cannot find module"  how do it ??

**Comment by maxaqquepucho** [comment]
I am using libreOffice to convert any office document to pdf, which I use this command
` var cmd = 'soffice --headless --convert-to pdf' + file.path + '--outdir' + outdir.path;`
I use the module `child_proccess` plus `exec,` when I use in development everything works very well, however when I am in development that command is not executed, it does not generate an error, I need to solve this problem to finish the project I am developing

**Comment by SalvadorDuran** [comment]
@maxaqquepucho did you find a solution? my command exec works on dev mode but is not working on production

**Comment by TongDaDa** [comment]
> @PinkyJie Just an idea here but environment variables are normally inherited from their parent shell. On macOS the path is sourced in your `.bashrc` (I believe) so when you launch your app in development from the command line the environment variable is inherited. In production you launch it as an application and thus has no shell environment to inherit.

Hi, I have another similar problem [there](https://github.com/electron-userland/electron-builder/issues/4080), Could you give me a little help?

**Comment by jithin-zachariah** [comment]
Guys even after using fix-path I am getting "npx command not found  " on packages macOS electro app. Please help https://stackoverflow.com/questions/67276969/npx-command-not-found-in-packaged-macos-electron-app

**Comment by Alexsanchez06** [comment]
> I found a note on official document, is that the reason? ![image](https://cloud.githubusercontent.com/assets/551329/19590951/1ec49cf4-97a7-11e6-8c2c-c39137956bb7.png)
> 
> Does that means if I packaged the app as `asar`, I can't use `child_process.exec` to execute command line tool in my app?

This method also not work

**Comment by dwfrost** [comment]
> > > So here comes the question: where does this process.env.PATH come from inside the packaged app? Is there a method to change it?
> > 
> > 
> > You might want to take a look at using something like https://github.com/sindresorhus/fix-path
> > Closing this out.
> 
> npm install -save fix-path It works fine when I run electron . from my-app. However, once packaged I see "Error: Cannot find module" how do it ??

do you resolve it? I met the same problem.Help
