### ISSUE TITLE
Custom protocol example doesn't work in windows

### ISSUE THREAD

**Issue by diroru** [electron/electron#7689]
* Electron version: 1.4.4
* Operating system: Windows 10 x64

Hi, the first example from the [protocol documentation](https://github.com/electron/electron/blob/master/docs/api/protocol.md) throws an `ERR_FILE_NOT_FOUND` error. I am feeding a path string in the form `atom:///path/to/index.html` and also tried registering `atom` as a standard scheme.

The error occurs at startup when calling `win.loadURL()`.

If I call `file:///path/to/index.html`, the file is loaded correctly, but no combination of `registerFileProtocol` or `interceptFileProtocol` worked for me, even if i explicitly return the string `file:///path/to/index.html` in the callback, i get the error message.

I need to hack into to the file protocol so that i can treat _absolute paths_. The code works on OS X.

**Comment by enlight** [comment]
`ERR_FILE_NOT_FOUND` probably means the path you're passing to the callback is invalid, the callback takes an absolute file system path, not a URL. So calling `callback('file:///path/to/index.html')` won't work, but `callback('C:\\path\\to\\index.html')` should work (assuming the file exists).

**Comment by diroru** [comment]
Thank you very much! This seems to solve the problem!

Now i have the issue of the variable `__dirname` behaving weirdly, but it is another topic and needs further investigation.
