### ISSUE TITLE
Can't access webContents for non focused renderer process 

### ISSUE THREAD

**Issue by arkakkar** [electron/electron#7690]
* Electron version: 1.4.1
* Operating system: MacOS

I get to see two webContents object using **webContents.getAllWebContents()**  in the main process but when I am trying to access win1.webContents it shows a **Object has been destroyed at Error (native)** error.
I am only able to access win.webContents for the current focussed window.
I need to make a communication from one renderer process to another renderer process. 

Both window object exists.

**Comment by lech-code-monkey** [comment]
I have the same problem, how do you fixed it?
