### ISSUE TITLE
cors bug!

### ISSUE THREAD

**Issue by keyiis** [electron/electron#7691]
* Electron version:1.4
* Operating system:win10 x64

**Same code work fine in nodejs and node-webkit(nwjs),but work fail in electron,so i think electron should do something.**
below is code:
```
var opt = {
            method: "POST",
            host: "api.xx.com",
            path: "/pay/micropay"
        };
        var req = https.request(opt, (res) => {
            console.log(`STATUS: ${res.statusCode}`);
            console.log(`HEADERS: ${JSON.stringify(res.headers)}`);
            res.on('data', (chunk:any) => {
                console.log(`BODY: ${chunk}`);
            });
            res.on('end', () => {
                console.log('No more data in response.');
            });
        });
        req.on('error', (err:any) => {
            console.log(`problem with request: ${err.message}`);
        });
        // write data to request body
        req.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><root><appid>wx5a1f8ba5c844fe7e</appid></root>');
        req.end();
```
get error in electron
`Response to preflight request doesn't pass access control check`

i know this is cors issues,so i already try set ("Access-Control-Allow-Origin", "*") in header and 'web-preferences': {'web-security': false} in main.js,that all no effect,but when i use node-webkit or nodejs to run the code,it work well and needn't any setting.

**Comment by zcbenz** [comment]
Using `https` module should work the same on all engines, it is very likely the other parts of your code caused the problem, can you provide a minimal app that can reproduce this problem?

**Comment by keyiis** [comment]
@zcbenz I reduce the nodejs version from 5.x to 4.6,it's work fine,that's strange!
