### ISSUE TITLE
WebView on a computer with a touch screen has a "confused" cursor :/

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#7692]
- Electron version: `1.4.3`
- Operating system: Windows 10

So this is an interesting one.  Basically I have a standard webview app structure.  I.e. Main window with a webview inside it.  If I load a site in that webview (such as youtube or google play music) the cursor appears to hover over one element and trigger the hover effects of another element at an offset position to the actual cursor location.

This is simulating "UI lag" and stuttering when in fact it appears to be a cursor rendering issue.

This can not be reproduced in Chrome 53 or 54 using a WebView element.

In can always be reproduced in Electron `1.4.x` using a WebView element.

Looking for any ideas, fwiw Electron `1.3.x` did **not** have this issue.  I'll be able to provide a video shortly

**Comment by Thomas101** [comment]
@MarshallOfSound do you see any issue when selecting text or resizing textarea elements inside the webview?

**Comment by MarshallOfSound** [comment]
@Thomas101 I've disabled text selectron inside the WebView and my text-areas aren't resizable 😆

**Comment by Thomas101** [comment]
Ah okay no worries. Was wondering if it was related to something I've been tracking

**Comment by andymartinwork** [comment]
This issue is probably related to #7655

**Comment by MarshallOfSound** [comment]
Merging into #7655
