### ISSUE TITLE
Bootstrap Modals Not Working At All

### ISSUE THREAD

**Issue by SampanVermaGreat** [electron/electron#7694]
* Electron version: Electron 1.4.4 (64 bit)
* Operating system: Windows 10 (64 bit)

I created a bootstrap modal using bootstrap css. They do work in Google Chrome Browser but they dont work when I run the page using electron.

I was not using any command line rendering, rather downloaded the zip, and dragged the page there.

**Comment by mnquintana** [comment]
For questions about writing apps, I'd suggest seeking help from [the community](https://github.com/electron/electron#community). The GitHub Issues list is only for bug reports and feature requests.
