### ISSUE TITLE
frameless window does not play well with mouse events

### ISSUE THREAD

**Issue by fantasticsid** [electron/electron#7696]
- Electron version: 1.4.1
- Operating system: Mac with retina display

Step to reproduce:
1. create a frameless window on a retina device
2. put an element at the very top, say a div, and set the cursor type to pointer
3. observe that the cursor does not always change to a 'pointer' type

I have a video here for demo purpose: https://youtu.be/yFZayteopgg

The video demonstrated the issue on Mac, but it's also reproducible on Windows, and on Windows it's worse because not only the cursor type does not change, the click event won't register either. Thus it's impossible to correctly implement close/maximize/minimize buttons with CSS.

Notice it's only reproducible on hi dpi devices, everything seems to work correctly on regular displays.

the demo in the video is made by adapting the frameless window example in the electron api demo app.

**Comment by gabval** [comment]
I would like to add, that mouseenter and mouseleave don't work properly on a frameless window on windows. If you move your mouse in and out really fast it works. Otherwise it does not.

**Comment by fantasticsid** [comment]
@gabval Maybe try 1.4.2, there's a fix for that. Closing this issue for now since the bug was not reproducible in 1.4.2 anymore

**Comment by gabval** [comment]
I am using 1.4.4

**Comment by fancyydk** [comment]
This still seems to be an issue in the latest version today, which is 1.4.14.

**Comment by zcbenz** [comment]
I'm closing this issue since it has already been tracked by #983 and #5723.

**Comment by mustafat0k** [comment]
Sad to see like these because released at 2013. There is lot of issues even at maximizing() doesn't work when the frame removed. Doesn't work correctly.

**Comment by Rigo85** [comment]
Hi, i'm using Electron 19.0.9, frameless window do not work well with click events.
