### ISSUE TITLE
Include Serial Port module by default in Electron installation

### ISSUE THREAD

**Issue by rodryquintero** [electron/electron#7698]
* Electron version: 1.4
* Operating system: Windows 7 Pro; Windows 2008 Server R2
----------------------------------------------------------------------------
Please consider including a native serial port module. Tyring to make the `serialport` module is very difficult (in my case it never worked).

Including a working version of this module in the Electron installation will save developers a lot of pain in trying to get it to work manually.

**Comment by enlight** [comment]
The Electron maintainers have more than enough work to keep them busy as is, taking up maintenance of 3rd party modules is just not going to happen.

**Comment by rodryquintero** [comment]
How about building a  new serial port module specific for electron and include it as part of the project? I did not suggest maintaining third party modules but to include this functionality "built in".
