### ISSUE TITLE
webview guestinstance attribute issue

### ISSUE THREAD

**Issue by TimNZ** [electron/electron#7700]
- Electron version: 1.4.1+
- Operating system: OS X

Since guestinstance attribute support was added in 1.4.1 I'm having inconsistent issues with content disappearing from webview.

I'm using Golden Layout as a Docking Panel container.  It wraps around components (plain,react) and when you do things it sometimes re-renders components.  And in many cases it results in the &lt;webview&gt; losing it's 'guestinstance' attribute value and becoming empty.

Regardless I expect I have to trace through the Golden Layout code to figure out what it is doing and see if I can make it less inclined to re-render content.

In any case, hooking DOM attribute modification in DevTools, I see a 'ELECTRON_GUEST_VIEW_INTERNAL_DESTROY_GUEST-XX' is triggered by something Golden Layout is doing, and the guestInstanceId is subsequently cleared by Electron code.

Does Electron need to have a different attitude to what it does with guestinstance so it doesn't result in none being specified?

I can likely reproduce this in a simple app if need be..

![electron - - screen shot 22-10-2016 12 56 03 pm](https://cloud.githubusercontent.com/assets/1051701/19615074/5cb0034a-9857-11e6-8a89-f9aa0d98209b.png)

![google chrome - github com - - screen shot 22-10-2016 12 56 23 pm](https://cloud.githubusercontent.com/assets/1051701/19615077/5fe0da6c-9857-11e6-801c-83e680379369.png)

**Comment by cmplx** [comment]
I confirm this issue, if guestinstance is not set, the contents of the webview is not displayed. In some cases, when was updated the DOM , he is lost and the content disappears. ver. 1.4.4

**Comment by kevinsawicki** [comment]
> I can likely reproduce this in a simple app if need be..

This would be really helpful, thanks.

**Comment by cmplx** [comment]
Если способ отключить эту функцию  ?

**Comment by TimNZ** [comment]
I've extracted this out into a simple app and can replicate and can confirm that the guestinstance attribute is occasionally disappearing resulting in an empty webview.  When I shift the containing Golden Layout panel a new guestinstance is normally allocated.

Now isolating steps to replicate reliably.

**Comment by TimNZ** [comment]
Example app attached.

What is happening is Golden Layout hides panels when they are stacked as tabs in the same container.

On 'show' of a tab/panel container, a 'ELECTRON_RENDERER_WINDOW_VISIBILITY_CHANGE' is triggered and code in 'web-view.js' results in the guestinstance attribute being cleared.

Tracing through the handler I can see the webview is actually being rendered fine beforehand on 'show' so it's nothing Golden Layout is doing explicitly.

To replicate:

1. npm start
2. Drag the right tab next to the left tab so they are now stacked
3. This leaves the right tab active and rendered.
4. Click the left tab - it will now be empty, with the webview no longer having a guestinstance attribute
5. In DevTools inspect the contents of the 2nd '.lm_item_container .lm_content' which is the container of the 2nd tab.  The webview still has a guestinstance.
6. Click the right tab
7. The guestinstance attribute is cleared by web-view.js after Golden Layout does a 'show' on the container.

Let me know if this is not clear.

I guess it could be simplified even more simply to doing a hide/show on a webview parent container but I haven't tested that in case it is an edge case in how Golden Layout is doing visibility changes..

![google chrome - github com - - screen shot 25-10-2016 10 27 20 am](https://cloud.githubusercontent.com/assets/1051701/19664590/a2fd9806-9a9d-11e6-86c0-66d83b3a3989.png)

[Archive.zip](https://github.com/electron/electron/files/549042/Archive.zip)

**Comment by TimNZ** [comment]
Quite possibly related a number of Electron Helper instances in memory as well with a lot of historical guestinstance id param.

**Comment by TimNZ** [comment]
There's no bug or other label on the issue - are you confirming it first?

**Comment by kevinsawicki** [comment]
> There's no bug or other label on the issue - are you confirming it first?

Yup, thanks for providing the example app, I was going to try and reproduce it today and update the labels with my findings.

**Comment by kevinsawicki** [comment]
Looks like this can be reproduced by hiding/showing a webview:

```js
wv = new WebView()
wv.src = 'http://github.com'
document.body.appendChild(wv)
wv.guestinstance // prints a valid number
wv.style.display = 'none'  // hide the webview
wv.style.display = 'block'  // show the webview
wv.guestinstance // prints undefined now
```

**Comment by TimNZ** [comment]
Sweet.  Look forward to the fix as it's a blocker to rolling out an app using latest ver.
