### ISSUE TITLE
No console output on Windows Server 2012 R2

### ISSUE THREAD

**Issue by TheNoim** [electron/electron#7704]
* Electron version: 1.4.4
* Operating system: Windows Server 2012 R2
I don't get any output with console.log() on windows server 2012 r2
I already reinstalled it. The Code works. Because I was first on Windows Server 2016 TP4 and and there i got output with the same code, and now i reinstalled windows and does not get any output.

**Comment by MarshallOfSound** [comment]
Gonna say this is probably a duplicate of #7685

**Comment by TheNoim** [comment]
My app does not hang, everything else is working.

**Comment by kevinsawicki** [comment]
I believe this is a duplicate of #6946

Have you tried setting the `ELECTRON_ENABLE_LOGGING` environment variable to `true`?

**Comment by TheNoim** [comment]
Still no output.
I used:
set ELECTRON_ENABLE_LOGGING=true

Nothing
