### ISSUE TITLE
Electron Light Boilerplate

### ISSUE THREAD

**Issue by cawoodm** [electron/electron#7705]
Just starting with Electron and noticed the basic boilerplate templates generate around 200Mb of node_modules/ - seems a bit heavy. Is there a light, basic template for Electron?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW Electron prebuilts themselves probably account for 50% of that file size and `node_modules` folders are notoriously large in general.
