### ISSUE TITLE
Calling preventDefault() on new-window event doesn't prevent window opening

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#771]
According to the [docs](https://github.com/atom/atom-shell/blob/5e99c8f280b5e396a7ba38ce8b9977eafeb9bb24/docs/api/browser-window.md#event-new-window) the following should prevent the window from being opened but the new window is still being opened.

``` js
window.webContents.on('new-window', function(event, urlToOpen) {
  event.preventDefault();
});
```

Doing the following instead seems to work though:

``` js
window.webContents.on('new-window', function(event, urlToOpen) {
  event.defaultPrevented = true;
});
```

Using `0.19.0`

**Comment by fretman92** [comment]
Related to https://github.com/electron/electron/issues/4473 which states the limitation of the remote module
