### ISSUE TITLE
How to pause download?

### ISSUE THREAD

**Issue by idododu** [electron/electron#7712]
* Electron version: 1.4.3
* Operating system: win7
* Description:

I am working on a download function using electron + angularjs. it can download file successfully.
However I do not know how to pause a download, can anyone help?

in main.js
```
ipcMain.on('dowloadFiles', function(evt, files) {
        var wc = mainWindow.webContents;
        for (var i = files.length - 1; i >= 0; i--) {
            var file = files[i];
            wc.downloadURL(file.url);
        }
        
    });

    mainWindow.webContents.session.on('will-download', function(event, item, webContents) {
      // Set the save path, making Electron not to prompt a save dialog.
      item.setSavePath('c:\\downloadTest\\test.txt');

      item.on('updated', function(event, state) {
        if (state === 'interrupted') {
          console.log('Download is interrupted but can be resumed');
        } else if (state === 'progressing') {
          if (item.isPaused()) {
            console.log('Download is paused');
          } else {
            console.log('Received bytes: ', item.getReceivedBytes());
          }
        }
      });
      item.once('done', function(event, state) {
        if (state === 'completed') {
          console.log('Download successfully');
        } else {
          console.log('Download failed: ', state);
        }
      });
    });
```
in html page
```
<li ng-click="download('http://server/a.txt')">a.txt</li>

var ipc = require('electron').ipcRenderer;
$scope.download = function(url) {
   ipc.send('dowloadFiles', [file]);
}
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

https://github.com/electron/electron/blob/master/docs/api/download-item.md#downloaditempause

**Comment by idododu** [comment]
In case that anyone have the same question, see below codes.

in main.js
```
// to store downloadItems
var downloadItems = [];

ipcMain.on('dowloadFiles', function(evt, options) {

      if(options.command === 'startDownload') {
           wc.downloadURL(file.url);
           return;
      }

      if(options.command === 'stopDownload') {
           var item = getDownloadItem(options.url);
           item.pause();
           return;
      }

    if(options.command === 'resumeDownload') {
           var item = getDownloadItem(options.url);
           item.resume();
           return;
      }
      
});

    mainWindow.webContents.session.on('will-download', function(event, item, webContents) {
      // Set the save path, making Electron not to prompt a save dialog.
      item.setSavePath('c:\\downloadTest\\test.txt');

      // store the download item, so that we can call item.pause/resume in a 
      downloadItems.push(item);

      item.on('updated', function(event, state) {
          // console.log('when updated send download progress to render process')
         mainWindow.webContents.send('updateDownload', {
                url: item.getURL(),
                progress: item.getReceivedBytes() / item.getTotalBytes()
            });
      });
    });
```

**Comment by mujtabazaidi** [comment]
@idododu  i did the same but getting item.pause() is not a function exception.
how could you call item.pause out of session.on('will-download') because it is function of item inside session.on('will-download')?

**Comment by idododu** [comment]
@mujtabazaidi we can store item object which only work in 'will-download' event to an global array, then we can call pause function in other place.

```javascript
// to store downloadItems
var downloadItems = [];

ipcMain.on('dowloadFiles', function(evt, options) {
    // ...
    if(options.command === 'stopDownload') {
           var item = getDownloadItem(options.url); // fetch item from downloadItems array
           item.pause();
           return;
      }
    // ...
});

mainWindow.webContents.session.on('will-download', function(event, item, webContents) {
    // ...

      // store the download item, so that we can call item.pause/resume in a 
      downloadItems.push(item);

    // ...
});

```

**Comment by bbf13** [comment]
"pause()"  is not defined

**Comment by sinnerman72** [comment]
> @mujtabazaidi we can store item object which only work in 'will-download' event to an global array, then we can call pause function in other place.
> 
> ```js
> // to store downloadItems
> var downloadItems = [];
> 
> ipcMain.on('dowloadFiles', function(evt, options) {
>     // ...
>     if(options.command === 'stopDownload') {
>            var item = getDownloadItem(options.url); // fetch item from downloadItems array
>            item.pause();
>            return;
>       }
>     // ...
> });
> 
> mainWindow.webContents.session.on('will-download', function(event, item, webContents) {
>     // ...
> 
>       // store the download item, so that we can call item.pause/resume in a 
>       downloadItems.push(item);
> 
>     // ...
> });
> ```

It is not possible to work with that code.

getDownloadItem(options.url); ? no such function.
 var item = getDownloadItem(options.url); what is options.url returning?

You fire a will-download session via downloadURL(file.url) but you try to access items via option.url.

I couldn't managed to make it work anyways. Any one can help on this? It's still impossible to pause a download..
