### ISSUE TITLE
Cache size flags

### ISSUE THREAD

**Issue by pywebdesign** [electron/electron#7713]
- Electron version: 1.4.4
- Operating system: windows / all

I can't see how I can modify cache size for the embedded chrome browser in electron. I would like to set a larger cache for downloaded media.

Is there any reason it is not exposed and/or should not?

thank you very much

**Comment by kevinsawicki** [comment]
I believe this can be supported by making this value configurable, https://github.com/electron/brightray/blob/a55f26ec2f53ccd961381234c941564b4fd4403f/browser/url_request_context_getter.cc#L98

**Comment by pywebdesign** [comment]
Thank you kevinsawicki,

I am not able to propose a coded solution as it is still a little bit out of my reach. I will be leaving here my use case for other to see.

I am simply working on a long running app which need a large local cache so it still work if internet connectivity is lost. I will be using nginx on the client side for now.

This flag could solve this use case pretty well without resorting to write a cache through web worker and the node file system fs or using solution like squid, nginx or varnish.

**Comment by deepak1556** [comment]
Merging this to https://github.com/electron/brightray/issues/290, please subscribe to it for updates. Thanks!
