### ISSUE TITLE
nodeIntegration not working when moving from electron-prebuilt@1.3.8 to electron@1.4.4

### ISSUE THREAD

**Issue by jaypanares** [electron/electron#7716]
* Electron version:  electron-prebuilt@1.3.8 and electron@1.4.4
* Operating system:  Windows 10 x64

Hi, currently having a problem when I moved to using `electron` instead of `electron-prebuilt`.  Before moving to `electron` (as recommended by `electron-prebuilt`) I had no problems, but when I replaced `electron-prebuilt` with `electron`, it seems like `nodeIntegration` does not work even though it is set to `true`.  `require` is not being recognized in the renderer process.

**Comment by MarshallOfSound** [comment]
Can you provide the code you are using that causes this issue

**Comment by jaypanares** [comment]
Here's how I moved to `electron` from `electron-prebuilt`:

`npm r -D electron-prebuilt && npm i -D electron` inside my development folder

`npm r -D electron-prebuilt && npm i -D electron` inside the folder where the electron app is

A simple `require('electron')` will produce the `require is not defined...` error.

So far, my app is working if I `npm i -D electron-prebuilt@1.3.8`, but since `electron-prebuilt` is only going to be published until end of 2016, this worries me.

**Comment by MarshallOfSound** [comment]
Can you provide the code you use to create the `BrowserWindow`

**Comment by jaypanares** [comment]
```
mainWindow = new BrowserWindow({
    width: defaultWidth,
    height: defaultHeight,
    fullscreen: settings.get('fullscreen'),
    kiosk: settings.get('kiosk'),
    webPreferences: {
        plugins: true,
        nodeIntegration: true
    }
});
```

**Comment by MarshallOfSound** [comment]
I can't reproduce this and your code looks correct.

Can you provide a minimal app that demonstrates the issue?

**Comment by jaypanares** [comment]
That's the thing though, it's only an issue in my current app.  When I clone the quick start app from the Electron website, everything works as intended (`require` works) even though it uses `electron` instead of `electron-prebuilt`.  Is moving from `electron-prebuilt` to `electron` just a matter of replacing one npm module with the other?

**Comment by MarshallOfSound** [comment]
>  Is moving from electron-prebuilt to electron just a matter of replacing one npm module with the other?

Yes they are identical modules just with different names.

> That's the thing though, it's only an issue in my current app

If we can't reproduce it we can't really help out 😢 I'd recommend wiping your `node_modules` folder and and rerunning `npm install`.  Sometimes funky things happen, also ensure your electron version is actually `1.4.4`
