### ISSUE TITLE
Dock bounce not working on Yosemite

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#772]
Using Atom shell `0.19.0` on Mac OS X `10.10`.

The bounce API seems to always return -1 for the request id and the icon isn't bouncing in the dock.

![screen shot 2014-11-02 at 6 35 26 am](https://cloud.githubusercontent.com/assets/671378/4875552/b572c61c-629d-11e4-99b3-8267ab3669f4.png)

**Comment by ThorstenHans** [comment]
@kevinsawicki perhaps the docs should mention tihs.
