### ISSUE TITLE
how can I integrate electron into my macOS app?

### ISSUE THREAD

**Issue by seajean** [electron/electron#7723]
* Electron version: 1.3.8
* Operating system: macOS
I am going to integrate electron into my object-c app  and replace one window's content as electron page, is there any tutorial?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW what you want to do doesn't sound easy
