### ISSUE TITLE
request for function to get current default protocol client

### ISSUE THREAD

**Issue by TanninOne** [electron/electron#7725]
- Electron version: 1.4.3
- Operating system: Windows

Electron offers the functions "setAsDefaultProtocolClient" and "removeAsDefaultProtocolClient" to set/unset the current application as the default protocol handler.
It would be nice if we could have a function that gives us the current protocol client so that we can store it and, instead of removing the protocol client completely we can restore the previous one.

So say "foreign-app" was registered as the protocol client. "our-app" stores that info away, registers itself and on deinstallation it can then offer the user to restore "foreign-app" as the handler.

**Comment by enlight** [comment]
What would happen if the "foreign-app" was uninstalled?

**Comment by TanninOne** [comment]
Well, we can check for that in the deinstallation routine and if the previously registered exe doesn't exist any more we can still clear the field completely.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
