### ISSUE TITLE
gRPC in Electron 1.4.4

### ISSUE THREAD

**Issue by eltoro** [electron/electron#7731]
* Electron version: 1.4.4
* Operating system: OSX Sierra 10.12.1
* gRPC version: grpc@^1.0.1-pre1

I can't get it to run in electron even doing a build from source.  Tried this too:

`./node_modules/.bin/electron-rebuild --pre-gyp-fix`

I did brew install openssl --force.

Is there anything else I can try?

runtime error:
```
Uncaught Error: dlopen(/srv/caliban/node_modules/grpc/src/node/extension_binary/grpc_node.node, 1): Symbol not found: _GENERAL_NAME_free
  Referenced from: /srv/caliban/node_modules/grpc/src/node/extension_binary/grpc_node.node
  Expected in: flat namespace
 in /srv/caliban/node_modules/grpc/src/node/extension_binary/grpc_node.node

```
electron-build error:
```
.././src/core/lib/security/credentials/jwt/json_token.h:38:10: fatal error: 'openssl/rsa.h' file not found
#include <openssl/rsa.h>
         ^
1 error generated.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/srv/caliban/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/srv/caliban/node_modules/grpc/src/node/extension_binary"
gyp ERR! cwd /srv/caliban/node_modules/grpc
gyp ERR! node -v v6.8.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by eltoro** [comment]
Ok, this fixed the openssl problem

`LDFLAGS=-L/usr/local/opt/openssl/lib CPPFLAGS=-I/usr/local/opt/openssl/include ./node_modules/.bin/electron-rebuild`

But now I get this error:

../src/node/ext/call.cc:616:20: error: no member named 'SetHiddenValue' in 'v8::Object'
      info.This()->SetHiddenValue(Nan::New("channel_").ToLocalChecked(),
      ~~~~~~~~~~~  ^

**Comment by enlight** [comment]
You'll need to fix `grpc` similarly to the way I've fixed `node-inspector` in [this PR](https://github.com/node-inspector/v8-profiler/pull/96).

**Comment by eltoro** [comment]
Ok. Looks like there's a pull request that's in process now. 
#8220
