### ISSUE TITLE
Native module crashes renderer but not main process

### ISSUE THREAD

**Issue by iglosiggio** [electron/electron#7732]
* Electron version: v1.4.0
* Operating system: Huayra Linux
    - Kernel: Linux huayra 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

Using v4l2camera (for managing webcams, and using their advanced controls like exposure) crashes the renderer process when it's GC'ing.

Log:
```
[3702:1025/111503:FATAL:PartitionAlloc.cpp(957)] Check failed: page->numAllocatedSlots != -1. 
#0 0x000001e3f38e <unknown>
#1 0x000001e5508b <unknown>
#2 0x000002567029 <unknown>
#3 0x00000258999d <unknown>
#4 0x7f751d30c153 v8::internal::ArrayBufferTracker::ProcessBuffers()
#5 0x7f751d30c026 v8::internal::ArrayBufferTracker::FreeDeadInNewSpace()
#6 0x7f751d318a87 v8::internal::Heap::Scavenge()
#7 0x7f751d315d13 v8::internal::Heap::PerformGarbageCollection()
#8 0x7f751d3153ce v8::internal::Heap::CollectGarbage()
#9 0x7f751d35a0cc v8::internal::ScavengeJob::IdleTask::RunInternal()
#10 0x0000005800f1 <unknown>
#11 0x000000580434 <unknown>
#12 0x00000057fa9a <unknown>
#13 0x00000057fde4 <unknown>
#14 0x000001e40056 <unknown>
#15 0x000000579197 <unknown>
#16 0x0000005782b9 <unknown>
#17 0x000001e40056 <unknown>
#18 0x000001e5b585 <unknown>
#19 0x000001e5b878 <unknown>
#20 0x000001e5bccb <unknown>
#21 0x000001e5d0aa <unknown>
#22 0x000001e7424e <unknown>
#23 0x000001e5acca <unknown>
#24 0x0000013ab40c <unknown>
#25 0x00000120840d <unknown>
#26 0x000001209507 <unknown>
#27 0x000001207fe0 <unknown>
#28 0x000003460343 main
#29 0x7f751618ab45 __libc_start_main
#30 0x000000562299 <unknown>
```

Related _Blink_ file: [PartitionAlloc.cpp:957](https://chromium.googlesource.com/chromium/blink.git/+/master/Source/wtf/PartitionAlloc.cpp#961)

The crash only happens if the renderer process gets a frame (Uint8Array) that stays on the heap an has to be GC'ed (well, at least that's my hypothesis).

When runing this code con the ``main`` context everything works.

## Example code for the renderer
```js
cam = require('v4l2camera').Camera('/dev/video0');
cam.start();
cam.capture(function loop() { cam.capture(loop); });

canvas = document.createElement('canvas');
canvas.width = 640;
canvas.height = 480;

document.body.appendChild(canvas);

c2d = canvas.getContext("2d");
imgdata = c2d.createImageData(640, 480)

function draw(screen) {
  for(var i = 0; i < 640 * 480; i++) {
    imgdata.data[i * 4 + 0] = screen[i * 3 + 0];
    imgdata.data[i * 4 + 1] = screen[i * 3 + 1];
    imgdata.data[i * 4 + 2] = screen[i * 3 + 2];
    imgdata.data[i * 4 + 3] = 255
  }
  c2d.putImageData(imgdata, 0, 0);
}

setInterval(function drawImage() {
  draw(cam.frameRaw());
}, 30);

// The image might seem buggy according to your webcam  internal format :P
// Wait some time and enjoy the crash! (or cry like i do :( )
```

## Example code for the main context (stolen from [v4l2camera examples](https://github.com/bellbind/node-v4l2camera/blob/master/examples/yuyv-stream-server.js))
```js
var http = require("http");
var v4l2camera = require("v4l2camera");

var script = function () {
    window.addEventListener("load", function (ev) {
		var rgb2rgba = function (rgb, rgba, width, height) {
		    for (var i = 0; i < width * height; i++) {
				rgba[i * 4 + 0] = rgb[i * 3 + 0];
				rgba[i * 4 + 1] = rgb[i * 3 + 1];
				rgba[i * 4 + 2] = rgb[i * 3 + 2];
				rgba[i * 4 + 3] = 255;
		    }
		    return rgba;
		};
		var cam = document.getElementById("cam");
		var c2d = cam.getContext("2d");
		var image = c2d.createImageData(cam.width, cam.height);
	
		(function load() {
		    var req = new XMLHttpRequest();
		    req.responseType = "arraybuffer";
		    req.addEventListener("load", function (ev) {
				var rgb = new Uint8Array(req.response);
				rgb2rgba(rgb, image.data, image.width, image.height);
				c2d.putImageData(image, 0, 0);
				setTimeout(load, 10);
		    }, false);
			req.open("GET", "/" + Date.now() + ".yuv", true);
			req.send();
		})();
    }, false);
};

var cam = v4l2camera.Camera("/dev/video0")
cam.start();
cam.capture(function loop() {
	cam.capture(loop);
});


var server = http.createServer(function (req, res) {
	if (req.url === "/") {
		res.writeHead(200, {
			"content-type": "text/html;charset=utf-8",
		});
        res.end([
			"<!doctype html>",
			"<html><head><meta charset='utf-8'/>",
			"<script>",
			"(" + script.toString() + ")()",
			"</script>",
			"</head><body>",
			"<canvas id='cam' width='640' height='480' />",
			"</body></html>",
		].join("\n"));
		return;
	}
	if (req.url.match(/^\/.+\.yuv$/)) {
		var buf = Buffer(cam.frameRaw());
		res.writeHead(200, {
			"content-length": buf.length
		});
		res.end(buf);
	}
});

server.listen(3000);

// Now go to localhost:3000 an look at your camera :P
```

And yes, if this works it's normal that this hacky code could lead to results like these 
![Cam looking weird](https://cloud.githubusercontent.com/assets/1154680/19691232/eee952bc-9aa9-11e6-92cd-6ebafffdd609.png)
**But this is _working_** (i can retrieve the raw frame w/o crashing everything :P)

Any help on how to track down the source of the bug? It may be the module, blink, v8 or electron.

**Comment by iglosiggio** [comment]
Well, the module used new and passed the buffer to v8 marking it as internalized. It seems that the new allocator in Renderer and Main contexts are different and that caused the double free.

I don't know if this needs to be in any wiki about how to develop native modules but i didn't found it (and got lucky resolving it via trial & error).

**Comment by zeke** [comment]
What solved the problem for you, @iglosiggio?

If there are some good take-aways, please consider opening a PR with updates to https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by iglosiggio** [comment]
The ``new`` operator has different allocators in main and renderer contexts. The module allocated memory with ``new`` and passed it to v8 with the 'internalized' flag.

The v8 GC conflicted with the blink page allocator (i'm still not sure on how) and that caused the bug (which i think it's a double free).

The solution was to have all that memory managed by v8, but it may be possible that lots of native modules have similar code.

In cases where it's not feasible to change the module it can be proxied via ipc.

I don't know if this is normal enough to modify the manual 😝

**Comment by zcbenz** [comment]
In renderer process the `ArrayBuffer` is managed by blink so you should never use raw `v8::ArrayBuffer` API in native modules, you can find more details at: https://github.com/electron/electron/issues/2601#issuecomment-135258750.

To solve this you have to change the modules to use `node::Buffer` APIs, it is hard work though.

Closing since it is something we are unable to fix.

**Comment by iglosiggio** [comment]
Thanks for the comment, now it's working well (but it's a v8::ArrayBuffer) the problem was resolved making v8 allocate the memory instead of allocating it with a ``new uint8_t[size]`` and passing it to v8.
