### ISSUE TITLE
Electron start cannot find module app (electron .package/main.js)

### ISSUE THREAD

**Issue by danpottshimself** [electron/electron#7733]
* Electron version: ^0.4.1 but have also tried versions above 1.0.0
* Operating system: Mac OSX

NOTE: This project used to work fine about 6-8 months ago but due to updates with electron and neglecting the project, it no longer runs when completing an npm start. However, it does build fine and the distributed version works fine (as a .app). When building this project, i create a .package folder directory where all concatenated files live etc, so this is base root for developing and opening.

When running npm start to start up my project I get an error of: 
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/daniel.potts/Documents/mockster/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/daniel.potts/Documents/mockster/.package/main.js:4:15
    at Object.<anonymous> (/Users/daniel.potts/Documents/mockster/.package/main.js:38:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

My package.json contains the following: 
{
  "name": "example",
  "version": "1.0.0",
  "description": "for you github people",
  "main": "main.js",
  "node-main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "electron .package/main.js",
    "build-mac": "electron-packager .package mockster --prune --ignore=node_modules/jshint --ignore=node.exe --out=.dist/osx --platform=darwin --arch=x64 --version=0.37.2",
    "build-win": "electron-packager .package mockster --prune --ignore=node_modules/jshint --out=.dist/win --platform=win32 --arch=x64 --version=0.37.2",
    "build": "npm run-script build-mac && npm run-script build-win"
  },
"dependencies": {
    "angular": "^1.5.0",
    "angular-animate": "^1.5.0",
    "angular-aria": "^1.5.0",
    "angular-material": "^1.0.6",
    "angular-messages": "^1.5.0",
    "body-parser": "^1.14.2",
    "cors": "^2.7.1",
    "express": "~4.13.3",
    "fs": "0.0.2",
    "path": "^0.12.7",
    "portastic": "^1.0.1",
    "string-format": "^0.5.0"
  },
  "devDependencies": {
    "deep-equal": "~1.0.1",
    "del": "~2.2.0",
    "electron": "^0.4.1",
    "electron-builder": "~2.6.0",
    "electron-packager": "~5.2.1",
    "gulp": "~3.9.0",
    "gulp-concat": "~2.6.0",
    "gulp-imagemin": "~2.4.0",
    "gulp-inject": "^3.0.0",
    "gulp-jshint": "~2.0.0",
    "gulp-less": "~3.0.5",
    "gulp-livereload": "^3.8.1",
    "gulp-run": "^1.6.12",
    "gulp-shell": "~0.5.1",
    "gulp-watch": "~4.3.5",
    "jshint": "~2.9.1",
    "jshint-stylish": "^2.1.0"
  }

My main.js looks like this:

(function () {
    'use strict';
    const electron = require('electron'),
        app = require('app');

    var template = require('./menu-template'),
        BrowserWindow = electron.BrowserWindow,
        Menu = electron.menu,
        mainWindow;

    app.on('ready', function () {
        var electronScreen = require('screen'),
            size = electronScreen.getPrimaryDisplay().workAreaSize;

        mainWindow = new BrowserWindow({
            width: size.width,
            height: size.height,
            minWidth: 1325,
            minHeight: 600
        });
        mainWindow.loadURLl('file://' + __dirname + '/index.html');
        mainWindow.openDevTools();
        mainWindow.on('closed', function () {
            mainWindow = null;
            app.quit();
        });

        template = new template(app, mainWindow);
        Menu.setApplicationMenu(Menu.buildFromTemplate(template));
    });

    app.on('window-all-closed', function () {
        if (process.platform !== 'darwin') {
            mainWindow.webContents.executeJavaScript('stopServerOnClose()');
            app.quit();
        }
    });
})();

I have tried uninstalling electron locally and globally. I have also tried the same for electron-prebuilt. I have tried updating my version of electron and have tried using remote to access the app/electron from the main.js.  

Thanks in advance

**Comment by MarshallOfSound** [comment]
Electron modules can no longer be required individually but are accessed as properties of Electron.

So `require('app')` should be `require('electron').app`

**Comment by ASHUTOSHSINGHND** [comment]
module.js:540
    throw err;
How to resolve this
