### ISSUE TITLE
Electron cannot find module 'remote'

### ISSUE THREAD

**Issue by danpottshimself** [electron/electron#7734]
Electron version: ^0.4.1 but have also tried versions above 1.0.0
Operating system: Mac OSX

NOTE: This project used to work fine about 6-8 months ago but due to updates with electron and neglecting the project, it no longer runs when completing an npm start. **However, it does build fine and the distributed version works fine (as a .app).** When building this project, i create a .package folder directory where all concatenated files live etc, so this is base root for developing and opening.

When running npm start to start up my project I get an error of: 
angular.js:4526 Uncaught Error: [$injector:modulerr] Failed to instantiate module Mockster due to:
Error: Cannot find module 'remote'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/daniel.potts/Documents/mockster/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at new <anonymous> (file:///Users/daniel.potts/Documents/mockster/.package/app/scripts/app.js:633:26)
    at Object.instantiate (file:///Users/daniel.potts/Documents/mockster/.package/bower_components/angular/angular.js:4619:14)
    at provider (file:///Users/daniel.potts/Documents/mockster/.package/bower_components/angular/angular.js:4433:36)
    at Object.provider (file:///Users/daniel.potts/Documents/mockster/.package/bower_components/angular/angular.js:4425:16)
    at runInvokeQueue (file:///Users/daniel.potts/Documents/mockster/.package/bower_components/angular/angular.js:4497:35)
http://errors.angularjs.org/1.5.0/$injector/modulerr?p0=Mockster&p1=Error%3…Fmockster%2F.package%2Fbower_components%2Fangular%2Fangular.js%3A4497%3A35)

My package.json contains the following: 
{
"name": "example",
"version": "1.0.0",
"description": "for you github people",
"main": "main.js",
"node-main": "main.js",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1",
"start": "electron .package/main.js",
"build-mac": "electron-packager .package mockster --prune --ignore=node_modules/jshint --ignore=node.exe --out=.dist/osx --platform=darwin --arch=x64 --version=0.37.2",
"build-win": "electron-packager .package mockster --prune --ignore=node_modules/jshint --out=.dist/win --platform=win32 --arch=x64 --version=0.37.2",
"build": "npm run-script build-mac && npm run-script build-win"
},
"dependencies": {
"angular": "^1.5.0",
"angular-animate": "^1.5.0",
"angular-aria": "^1.5.0",
"angular-material": "^1.0.6",
"angular-messages": "^1.5.0",
"body-parser": "^1.14.2",
"cors": "^2.7.1",
"express": "~4.13.3",
"fs": "0.0.2",
"path": "^0.12.7",
"portastic": "^1.0.1",
"string-format": "^0.5.0"
},
"devDependencies": {
"deep-equal": "~1.0.1",
"del": "~2.2.0",
"electron": "^0.4.1",
"electron-builder": "~2.6.0",
"electron-packager": "~5.2.1",
"gulp": "~3.9.0",
"gulp-concat": "~2.6.0",
"gulp-imagemin": "~2.4.0",
"gulp-inject": "^3.0.0",
"gulp-jshint": "~2.0.0",
"gulp-less": "~3.0.5",
"gulp-livereload": "^3.8.1",
"gulp-run": "^1.6.12",
"gulp-shell": "~0.5.1",
"gulp-watch": "~4.3.5",
"jshint": "~2.9.1",
"jshint-stylish": "^2.1.0"
}

My main.js looks like this:

**(function () {
    'use strict';
    const electron = require('electron'),
        app = electron.app;

    var template = require('./menu-template'),
        BrowserWindow = electron.BrowserWindow,
        Menu = electron.menu,
        mainWindow;

    app.on('ready', function () {
        var electronScreen = electron.screen,
            size = electronScreen.getPrimaryDisplay().workAreaSize;

        mainWindow = new BrowserWindow({
            width: size.width,
            height: size.height,
            minWidth: 1325,
            minHeight: 600
        });
        mainWindow.loadURL('file://' + __dirname + '/index.html');
        mainWindow.openDevTools();
        mainWindow.on('closed', function () {
            mainWindow = null;
            app.quit();
        });

        template = new template(app, mainWindow);
    });

    app.on('window-all-closed', function () {
        if (process.platform !== 'darwin') {
            mainWindow.webContents.executeJavaScript('stopServerOnClose()');
            app.quit();
        }
    });
})();

I have tried uninstalling electron locally and globally. I have also tried the same for electron-prebuilt. I have tried updating my version of electron and have tried using remote to access the app/electron from the main.js.

Thanks in advance

**Comment by zeke** [comment]
Versions of the `electron` package on npm prior to 1.3.1 are actually a different package entirely, and will produce unexpected results. For older versions, you'll need to install `electron-prebuilt`.  See this blog post for more info about the `electron` and `electron-prebuilt` npm packages: http://electron.atom.io/blog/2016/08/16/npm-install-electron

Perhaps the app is working/not-working for you because you have Electron installed globally on your system?

Try this:

```sh
npm rm electron --save-dev
npm install electron-prebuilt@0.4.1 --save-dev
npm start
```

or to try it out with a newer version of electron:

```sh
npm rm electron --save-dev
npm install electron --save-dev
npm start
```

See also https://github.com/electron/electron/issues/3755, which outlines a very similar issue.

**Comment by enlight** [comment]
I'd also check if you have `require('remote')` anywhere in your code, if you do you'll need to change it to `require('electron').remote`.

**Comment by zeke** [comment]
@danpottshimself note that `require('electron').remote` is the new way to require the remote module, starting at Electron version 1.0.0

**Comment by danpottshimself** [comment]
@zeke I have tried the above and still get app of undefined issue. I've uninstalled globally and installed pre-built and the new electron to no avail.

Using: 
    const electron = require('electron'),
        app = require('electron').remote.app;

**Comment by enlight** [comment]
Which process are you running this in? `require('electron').remote` will only work in the renderer process.

**Comment by danpottshimself** [comment]
@enlight 
(function () {
    'use strict';
    const electron = require('electron'),
        app = require('electron').remote.app;

    var template = require('./menu-template'),
        BrowserWindow = electron.BrowserWindow,
        mainWindow;

    app.on('ready', function () {
        var electronScreen = electron.screen,
            size = electronScreen.getPrimaryDisplay().workAreaSize;

        mainWindow = new BrowserWindow({
            width: size.width,
            height: size.height,
            minWidth: 1325,
            minHeight: 600
        });
        mainWindow.loadURL('file://' + __dirname + '/index.html');
        mainWindow.openDevTools();
        mainWindow.on('closed', function () {
            mainWindow = null;
            app.quit();
        });

        template = new template(app, mainWindow);
    });

    app.on('window-all-closed', function () {
        if (process.platform !== 'darwin') {
            mainWindow.webContents.executeJavaScript('stopServerOnClose()');
            app.quit();
        }
    });
})();

**Comment by enlight** [comment]
That code runs in the main process, where the `remote` module is not available (and is unnecessary for what you're trying to do), you just need `const app = require('electron').app`.

As for the uncaught error, `node_modules/remote/libs/remote.coffee` is not part of Electron, it's a [CLI tool](https://www.npmjs.com/package/remote). Unless you installed it on purpose you'll probably want to uninstall it, and then go to `.package/app/scripts/app.js:1028` and fix the `require('remote')` like I showed earlier.

**Comment by danpottshimself** [comment]
@enlight sorry again but i now get this issue.
I've uninstalled remote and its no longer in my node modules. I have changed the app/scripts/app.js require remote to require('electron').remote and I still get an error.
angular.js:4526 Uncaught Error: [$injector:modulerr] Failed to instantiate module Mockster due to:
Error: Cannot find module 'remote'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/daniel.potts/Documents/mockster/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at new <anonymous>

**Comment by danpottshimself** [comment]
@enlight You have enlightened me!
Cheers for the help boys! Changed all modules to be properties of electron and it all works. Had some hidden ones in my code!

**Comment by waelalameen** [comment]
I been stuck for years with this issue 
`TypeError: Cannot read property 'dialog' of undefined`

The code 
```javascript
var remote = require('electron').remote;
var dialog = remote.dialog;
```
Please help me out

**Comment by LeoLetourneur** [comment]
A little bit too late, but to help others on this question : 

`const {dialog} = require('electron').remote;`

**Comment by b0lle** [comment]
let me fix your typo, please
`const {dialog} = require('electron').dialog`
