### ISSUE TITLE
minWidth/minHeight freezing on Windows 10 touchscreen

### ISSUE THREAD

**Issue by MRayermannMSFT** [electron/electron#7735]
Reporting a bug we've found for Electron.
- Repro'd on Electron versions:
  - 1.3.1
  - 1.3.8
  - 1.4.4
- Operating system: Windows 10, touchscreen devices only (e.g. Surface Pro 4). If you use an external monitor, then it will only repro if you first sign into the device and then attach to a monitor.

Repro steps:
1. Create an Electron application.
2. When creating the BrowserWindow object, set the minWidth and/or minHeight to be >=width and/or height, ex:

``` javascript
mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    minWidth: 800,
    minHeight: 600,
});
```
1. Launch the application.
2. Maximize or snap the window to the top, left or right side of desktop either via keyboard shortcut or dragging the title bar to the edge of the screen.
3. Drag the window by the title bar to restore/unsnap it.

Expected:  the application should function normally.
Actual: the application will no longer repaint/render/appears frozen. If you move or resize the window, it will unfreeze, and all queued up mouse clicks/interactions will finally register.

**Comment by groundwater** [comment]
Can confirm on Windows 10, Surface Pro 4, Electron 1.4.15.

Updating to 1.6.1 seems to fix that. Can you confirm @MRayermannMSFT ?

**Comment by MRayermannMSFT** [comment]
I can confirm that the bug appears to be gone in 1.6.1. Thanks @groundwater. :)

**Comment by ziedhajsalah** [comment]
I have a similar issue with windows 10, Electron 1.7.2.
When pressing the screen multiple times with many fingers the app still work with the mouse but with touches did not work unless restarting the application.
I've tried to log any exception or error in the main process or the renderer process by using `process.on('error')` and `window.onerror` but nothing is logged.
