### ISSUE TITLE
macOS: Accelerator doesn't call when MenuItem visible = false

### ISSUE THREAD

**Issue by neonhomer** [electron/electron#7737]
- Electron version: 1.3.8
- Operating systems: macOS 10.12, Windows 10

If a MenuItem is not visible the keyboard shortcut doesn't fire the Accelerator in macOS.

Here's an snippet that works on Windows but not macOS:

```
{ label: 'Toggle Developer Tools',
    visible: false,
    accelerator: process.platform === 'darwin' ? 'Alt+Cmd+I' : 'Ctrl+Shift+I',
    click(item, browserWindow) {
        if (browserWindow) {
            browserWindow.webContents.toggleDevTools()
        }
    },
}
```

**Comment by zeke** [comment]
Are you seeing the same behavior on the latest version of Electron?

**Comment by neonhomer** [comment]
Just did a test with Electron 1.4.4 and the same results on macOS.

**Comment by zeke** [comment]
I wonder what the expected behavior is for an invisible MenuItem. In other words, is it a bug that the accelerator works on Windows?

Either way, we should document the expected behavior in http://electron.atom.io/docs/api/menu-item/

**Comment by neonhomer** [comment]
That's a good point.

We are doing a lot of kiosk type apps, so it's nice to be able to open up the dev tools on the fly after an app has been built. Since it worked on Windows I assumed it would be the same on macOS.

**Comment by Rokt33r** [comment]
@zeke
Is there another way to use accelerator from Browser window without adding menu?

**Comment by neonhomer** [comment]
Correct me if I'm wrong, but the only other way to use an Accelerator is via the [globalShortcut](http://electron.atom.io/docs/api/global-shortcut/). But that detects the keyboard shortcut even outside the app. I wouldn't suggest that as a best practice for something like I'm doing.

**Comment by MarshallOfSound** [comment]
@neonhomer Menu items take in accelerators as well. You even use one in your sample code

```js
    accelerator: process.platform === 'darwin' ? 'Alt+Cmd+I' : 'Ctrl+Shift+I',
```

**Comment by zeke** [comment]
> Is there another way to use accelerator from Browser window without adding menu?

Yes, there's https://github.com/parro-it/electron-localshortcut, a module to register/unregister a keyboard shortcut locally to a BrowserWindow instance, without using a Menu.

**Comment by MarshallOfSound** [comment]
> https://github.com/parro-it/electron-localshortcut

Although that works, I wouldn't recommend using it.  Hacking around the `globalShortcut` module to make it become local has side effects and other issues.

If you want to do keyboard shortcuts for a BrowserWindow just use the `keyup` and `keydown` event listeners on the `window` object inside the renderer process.  I.e. 

```js
window.addEventListener('keyup', doThingOnKeyUp, true);
```

Note the third parameter true which means the listener will **always** receive key presses before other listeners so they can't have `stopPropagation()` called on them.

**Comment by zcbenz** [comment]
This behavior is actually expected on most platforms, we may need to explicitly document it.

**Comment by zeke** [comment]
> This behavior is actually expected on most platforms

Which behavior? Why platforms?

**Comment by zcbenz** [comment]
> Which behavior? Why platforms?

Invisible menu items' accelerators should not work.

**Comment by zeke** [comment]
> Invisible menu items' accelerators should not work.

But apparently they _do_ work on Windows. Is that a bug, or expected behavior?

**Comment by zcbenz** [comment]
> But apparently they do work on Windows. Is that a bug, or expected behavior?

That should be a bug.

**Comment by poiru** [comment]
You can use [`before-input-event`](https://electron.atom.io/docs/api/web-contents/#event-before-input-event) to catch and handle custom shortcuts that are not visible in the menu.
