### ISSUE TITLE
touch event

### ISSUE THREAD

**Issue by chenshuai2144** [electron/electron#7742]
sometimes touch screen can not use the click event
Need to minimize and maximize

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW check out the `touchstart` event https://developer.mozilla.org/en-US/docs/Web/Events/touchstart
