### ISSUE TITLE
hookWindowMessage callback not called on all window messages

### ISSUE THREAD

**Issue by aknuth** [electron/electron#7746]
* Electron version: 1.4.4
* Operating system: windows / all

let's take e.g. mouse input notifications - according to the microsoft reference the following is defined:
```
#define WM_LBUTTONDOWN                  0x0201
#define WM_LBUTTONUP                    0x0202
```
I translated this into electron code:
```
 mainWindow.hookWindowMessage(513, (wParam,lParam) =>{
	var x = lParam[0]+256*lParam[1];
    var y = lParam[2]+256*lParam[3];
    console.log('mousedown:'+x+':'+y);
})
mainWindow.hookWindowMessage(514, (wParam,lParam) =>{
	var x = lParam[0]+256*lParam[1];
    var y = lParam[2]+256*lParam[3];
    console.log('mouseup:'+x+':'+y);
})
```
I would expect to get both hooks called, but only the mouseup one is called.
Do I misunderstand anything ?  

Another interesting behaviour about mousemove: 
```
#define WM_MOUSEMOVE                    0x0200
```
```
mainWindow.hookWindowMessage(512, (wParam,lParam) =>{
		var x = lParam[0]+256*lParam[1]; //& 0xFFFF;
	    var y = lParam[2]+256*lParam[3];
    	console.log('move:'+x+':'+y);
})
```
This one is called only if the mouse keeps clicked (left button, right button, anyway). I'd expect it to be called on every mouse move no matter if the mouse is clicked.

thanks a lot

**Comment by zcbenz** [comment]
This is because `WebContents` (the web page) view has hijacked those window messages, if you do not load any page in window you can observe all messages are being passed.

I'm closing this as won't fix because I don't think there is any solution to this.

**Comment by aknuth** [comment]
Thanks for your investigations and your answer. Now I know that I've to go an other way to surely receive all mouse & keyboard interactions.
