### ISSUE TITLE
Cursor can't be hidden on a webview

### ISSUE THREAD

**Issue by jbleuzen** [electron/electron#7747]
- Electron version: 1.4.4
- Operating system: macOS

Cursor can't be hidden when I'm hovering a webview. It's not working but I'm not sure it can be done...

I made a repo that show the issue : [https://github.com/jbleuzen/electron-webview-cursor](https://github.com/jbleuzen/electron-webview-cursor)

**Comment by zeke** [comment]
Thanks for creating that repo. I can confirm that the `cursor` property is not respected in the webview, regardless of the value used.

https://github.com/electron/electron/issues/1222 looks like a related issue, but no solution yet.

**Comment by zcbenz** [comment]
This seems to be an upstream Chromium issue.

**Comment by MBALOTA** [comment]
Is there any way to fix it or write a bug ticket for chromium? ._. **This bug is annoying the hell out of me.**

**Comment by jbleuzen** [comment]
Yes me too, I would to help but I dont know how to do a bug ticket on Chromium...

**Comment by MBALOTA** [comment]
It's really weird that only hidden doesn't work. The other ones work as far as I know.

**Comment by MBALOTA** [comment]
When the mouse isn't moving its visible, when I move the mouse it hides the courser for a "split second" and it shows it again. Using electron 1.4.8 on Windows 7 and yes I know it might be a chromium bug.

**Comment by fallafeljan** [comment]
Any news on this? Same issue here, Electron 1.4.7 on macOS 10.12.2. Setting the cursor to `pointer` or `none` on the container will affect only the container, but not the webview itself.

**Comment by Splder** [comment]
I found that setting the view you would like to change the cursor to:
`display: inline-block;`
or
`float: left;`
would make it work

**Comment by FibreFoX** [comment]
Is there any progress on this one? Any plans or something?

**Comment by markuslerner** [comment]
This worked best for me (overriding cursor for all elements):
```
let css = `* { cursor: ${visible ? 'auto' : 'none'} !important; }`;
win.webContents.insertCSS(css);
```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by FibreFoX** [comment]
I hate these auto-close bots ....
