### ISSUE TITLE
Installing using through NPM through Artifactory

### ISSUE THREAD

**Issue by Daz85** [electron/electron#7748]
* Electron version: 1.4.4
* Operating system: linux

Hi, I am trying to install electron through NPM which is hosted through an Artifactory remote repository.

    .nmprc:
      registry = https://myhost/artifactory/api/npm/npm

Unfortunately i am unable to use a proxy so I can only go through Artifactory, when i install i get the below error when NPM tries to download the .zip:

    electron@1.4.4 postinstall /usr/local/lib/node_modules/electron
    node install.js

    Downloading electron-v1.4.4-darwin-x64.zip
    Error: connect ECONNREFUSED 192.30.253.112:443
    /usr/local/lib/node_modules/electron/install.js:22
     throw err

Is there a way i can add the .zip to an artifactory repository and set a property in my .npmrc to download the .zip for there

Thanks, D

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

See https://github.com/electron-userland/electron-download

You can use the `ELECTRON_MIRROR` environment variable to change where Electron is downloaded from.
