### ISSUE TITLE
webKitSpeechRecognition to use process.env.GOOGLE_API_KEY

### ISSUE THREAD

**Issue by friksa** [electron/electron#7749]
webKitSpeechRecognition throws "network" error when used as part of the electron app, but works fine in the Chrome browser.

Recently this project added process.env.GOOGLE_API_KEY to support the Google Geolocation API (#7306), but it does not work for Google's webKitSpeechRecognition API.

REQUEST: Google's webKitSpeechRecognition API should use process.env.GOOGLE_API_KEY instead of hard coded GOOGLE_API_KEY.

also see:
electron-userland/electron-prebuilt#196
#7306
#7276

Thanks!

**Comment by MarshallOfSound** [comment]
`webkitSpeechRecognition` is an exception to the "use your own google API key rule"

> It is NOT possible to get additional quota for Chrome's Speech API. Look at the [Cloud Speech API](https://cloud.google.com/speech/) instead.

https://www.chromium.org/developers/how-tos/api-keys

**Comment by friksa** [comment]
Correct, I want to use our own Google API as they allow you to use the API with your own API key.
