### ISSUE TITLE
not installing properly wit Node 7.0.0

### ISSUE THREAD

**Issue by hasan3ysf** [electron/electron#7751]
* Electron version: 1.4.4
* Operating system: Windows 10
* Node version: 7.0.0

I installed electron globally like `npm install g electron`
while running the app, i got `npm WARN electron-client-app@1.0.0 No repository field.'

**Comment by MarshallOfSound** [comment]
@hasan3ysf This is not an issue, it is a warning saying that your apps package.json file doesn't have a "repository" field in it.

This doesn't affect the running of your application at all.
