### ISSUE TITLE
NPM Install Electron 0.37.8 

### ISSUE THREAD

**Issue by stefanKuijers** [electron/electron#7754]
* Electron version: 1.4.4 -> 0.37.8
* Operating system: Windows

I would like to use node-sass which I can not get to work with node ^6.x. Which makes me very very sad but hopefully node-sass will support electron at some point in the future. 

At this moment I would like to downgrade my currently installed version to 0.37.8. Cause I have another project in which I did get node-sass working with that version of electron. Now my simple question:

_How do I install that specific version?_

I've tried to run: 
```npm install electron@0.37.8```
Which resulted in:
```No compatible version found: electron@0.37.8. Valid Install Targets:1.4.4, 1.4.3, ... 1.3.1, 0.4.1, 0.4.0, 0.3.0, 0.2.0 ...```

Does the version number that process.versions.electron gives back differs from the semver used for the npm package?

Would greatly appreciate your help

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

If you want `electron` < `1.3.1` you need to use the `electron-prebuilt` package instead.

**Comment by stefanKuijers** [comment]
Thanks for the reply. ```electron-prebuild``` was the key.
