### ISSUE TITLE
Question: How to pass parameters to electron app from Mac's open command

### ISSUE THREAD

**Issue by soulbeing** [electron/electron#7755]
* Operating system: OS

Hi, I want to know if there is way to receive the parameters passes from "open" command in Mac. I want to use "Open" command open my app, and also passing some parameters to electron when doing so, like my current file path, etc. Many thanks in advance.

**Comment by kevinsawicki** [comment]
You can use the `--args` option to `open`:

```sh
open Electron.app --args --foo
```

Then log `process.argv` from the main process and you should see `--foo` in there.

See http://superuser.com/questions/180995/passing-command-line-args-to-open-on-mac for more details.
