### ISSUE TITLE
Google Cloud Speech API support for dictation

### ISSUE THREAD

**Issue by friksa** [electron/electron#7758]
It seems that Google is not supporting Chrome's Speech API anymore.  However, we still need the functionality.  It seems that they want everyone to use their Cloud Speech API instead: https://www.chromium.org/developers/how-tos/api-keys

It would be great it the Cloud Speech API could be supported in a compatible way with webKitSpeechRecognition.  Otherwise, if there could be a similar API to allow dictation in an electron app using our own Google API key.

Thanks!

**Comment by MarshallOfSound** [comment]
> It would be great it the Cloud Speech API could be supported in a compatible way with webKitSpeechRecognition

We aren't going to write you a wrapper for an existing API.  You can write this wrapper yourself.

The API reference for the Cloud Speech API can be found here https://cloud.google.com/speech/reference/rest/
