### ISSUE TITLE
BrowserWindow stays open for Tray app when other menu bar items are open

### ISSUE THREAD

**Issue by frederickk** [electron/electron#7759]
* Electron v1.4.3
* OSX 10.11.6

I've created a [Tray](http://electron.atom.io/docs/api/tray/) app, it's working great. One minor bug(?) I've encountered is that when the Tray is open (the paint palette icon in the screenshot below), and I click on another status item (e.g. [LittleIpsum](https://itunes.apple.com/us/app/littleipsum/id405772121?mt=12) or Dropbox) my app stays open.

<img width="402" alt="screen shot 2016-10-26 at 13 31 30" src="https://cloud.githubusercontent.com/assets/513134/19749425/b3d93fa8-9b9d-11e6-88a3-79e198597e6d.png">

It seems that the ```blur``` event on [BrowserWindow](http://electron.atom.io/docs/api/browser-window/) isn't firing when the user clicks on the status bar (or any items).

Here's some simplified code to show how I'm handling revealing the [BrowserWindow](http://electron.atom.io/docs/api/browser-window/) instance.

```
trayIcon.on('click', () => {
     mainWindow.show();
});

mainWindow.on('blur', () => {
    mainWindow.hide();
});
```

I wish [Tray](http://electron.atom.io/docs/api/tray/) had a ```blur``` or some kind lose focus event.

I also looked into using [Screen](http://electron.atom.io/docs/api/screen/) to track mouse movement and essentially fire a method based on mouse press and mouse position to determine whether the user is not near the icon. No dice...

(pseudo no-real code)

```
screen.on('mousemove', () => {
    if (mouse.pressed && mouse.x > (trayIcon.x + trayIcon.width) || mouse.x < trayIcon.x) {
        mainWindow.hide();
    }
});
```

I would be quite thankful for any tips on what I'm missing and/or workarounds.

Ken

**Comment by zcbenz** [comment]
This is because the default window level of a always-on-top window is lower than menus, to work around this you can pass a higher level:
http://electron.atom.io/docs/api/browser-window/#winsetalwaysontopflag-level

**Comment by frederickk** [comment]
Ok. Thanks for the tip, I hadn't noticed that in the docs. I gave it try, and perhaps I'm not understanding how to implement this, but regardless that above situation still persists.

Just to clarify, the behaviour I expect is that when I click on another status item, my status item will fire an "on blur" event, or something I can use to tell the window to close.

Here's another pseudo-code-snippet of what I've implemented, based on how I understood your note above.
```
        trayIcon = new Tray(__dirname + '/assets/TrayIconTemplate.png');
        trayIcon.on('click', () => mainWindow.show());

        mainWindow = new BrowserWindow({
            resizable      : false,
            transparent    : true,
            skipTaskbar    : true,
            maximizable    : false,
            fullscreenable : false,
            frame          : false,
            movable        : false,
            show           : false,
            webPreferences : {
                backgroundThrottling: false
            }
        });
        mainWindow.loadURL(`file://${__dirname}/index.html`);
        mainWindow.setAlwaysOnTop(true, 'dock'); // I opted for really high level to test...
        mainWindow.on('blur', () => {
            console.log('blur mainWindow.isFocused()', mainWindow.isFocused());
            mainWindow.hide();
        });
```

Ken
