### ISSUE TITLE
nodejs request module does not work properly in render process

### ISSUE THREAD

**Issue by idododu** [electron/electron#7760]
- Electron version: 1.4.3
- Operating system: win7

below is my codes, and sometime 'Pause Download' could not pause request.
I guess request module is working in a nother thread, and it could not response "request.pause()" command, which was run in render progress, immediately .

Can anyone explain?

```
<button onclick="startDownload">Start Download</button>
<button onclick="pauseDownload">Pause Download</button>

<script>
var request = require('request')
var downloader;

function startDownload() {
    downloader = request('http://path/to/file');
}

function pauseDownload() {
    // below line does not work sometimes
    downloader.pause();
}
</script>
```

**Comment by kevinsawicki** [comment]
> // below line does not work sometimes

What error are you seeing when it does not work? A full reproduction app including a `package.json`, `main.js` and `index.html` would help to reproduce this.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
