### ISSUE TITLE
How could I get webContents reference of devtools?

### ISSUE THREAD

**Issue by chemzqm** [electron/electron#7761]
* Electron version:1.4.4
* Operating system: MacOS

I'm trying to use https://github.com/rhysd/NyaoVim, it handles paste event itself, something like:
```
                    label: 'Paste',
                    accelerator: 'CmdOrCtrl+V',
                    click: () => {
                        win.webContents.send('nyaovim:paste')
                    }
``` 
The problem is I can't use paste in my devtools any more,  so  I changed the code to:

```
                    label: 'Paste',
                    accelerator: 'CmdOrCtrl+V',
                    click: (menuItem: Electron.MenuItem, win: Electron.BrowserWindow) => {
                      if (win.webContents.isDevToolsFocused()) {
                        win.webContents.paste()
                      } else {
                        win.webContents.send('nyaovim:paste');
                      }
                    }
```
But no luck, the window argument would be null when devtools focused.
According to https://github.com/electron/electron/blob/master/lib/browser/api/menu-item-roles.js#L156, there should be a way to get that reference for devtools.

**Comment by kevinsawicki** [comment]
You can access the dev tools web contents via:

```js
if (win.webContents.isDevToolsFocused()) {
  win.webContents.devToolsWebContents.paste()
}
```

You can also use `require('electron').webContents.getFocusedWebContents()` to get the focused web contents.
