### ISSUE TITLE
Document or give API to translate electron applications contents

### ISSUE THREAD

**Issue by popod** [electron/electron#7763]
Why they are no doc about translate for electron application ? What library can I use for that ? thanks

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

IMO you should follow the same methods for translating a web based application.  A cursory google search will reveal a couple of techniques.

**Comment by popod** [comment]
Yes, but why not provide a simple API to translate contents in main and render process. Now I should use two library (one for render in node.js and a second for my front end Angular). I thing it will be a good feature to add to electron because support user language is very important for an "pro" app.

Or it not an API, why not explain or give some library in doc ?

**Comment by MarshallOfSound** [comment]
> Yes, but why not provide a simple API to translate contents in main and render process

It wouldn't be "simple", there are lots of different ways to do translations and lots of different ways people will want them to work.  As mentioned before, IMO just do the same thing you would do if it was a web app.

> Or it not an API, why not explain or give some library in doc ?

We don't like to play favorites with libraries.  And most people don't use libraries they use some form of JSON file with a custom function or class specific to their use case.

**Comment by popod** [comment]
Okay, thank you for reply
