### ISSUE TITLE
app.makeSingleInstance issue in windows

### ISSUE THREAD

**Issue by arkakkar** [electron/electron#7764]
- Electron version: 1.4.1
- Operating system: Win 10

app.makeSingleInstance works fine on mac, but on windows since electron runs with multi processes (Multiple proceesses in task manager) it results in quitting of the main app.
 I need to quit the app if there is a second instance of the main process only app.makeSingleInstance returns true when I run the app for the first time in windows unlike mac where it works fine.

**Comment by zcbenz** [comment]
Can you provide a minimal app that can reproduce this problem?

**Comment by arkakkar** [comment]
app.makeSingleInstance returns true for my windows app, though I checked for the electron-api-demos it works fine on windows. Could you suggest something what could be the issue ? Probably something I am doing wrong !!

**Comment by zeke** [comment]
@arkakkar please provide a basic app to demonstrate the error you're encountering. It's difficult for us to help without it.

**Comment by arkakkar** [comment]
Hi @zeke , 
I tried reproducing the issue with a minimal app...seems to work fine in this case. I cannot share the app code where I am getting this issue on (some enterprise code) Its a large app now. That's why I am asking if you can give me any suggestions ??

**Comment by zeke** [comment]
My advice is to incrementally disable as much functionality in the real app as you can until you're able to isolate the source of the problem.

**Comment by arkakkar** [comment]
Alright I tried doing this to some extend...still upable to track what could have caused the issue. Will be of great help if you let me know any necessary requirements for the app to have makeSingle Instance api work correctly.

**Comment by zeke** [comment]
Take a look at http://electron.atom.io/docs/api/app/#appmakesingleinstancecallback, and here's some backstory on how the method was added for Windows and Linux: https://github.com/electron/electron/pull/3145

You probably shouldn't need to read that stuff though. As I said before, you should continue focusing on isolating the code in your app that is causing it to quit.

**Comment by arkakkar** [comment]
Hi,
I tried inspecting. On my task manager I see electron.exe being called twice for the renderer process for my app, whereas for the electron-api-demos it is called just once for the renderer and once for the gpu. I am uploading the snapshot. Could you suggest why this could happen
<img width="863" alt="multi-process" src="https://cloud.githubusercontent.com/assets/13099382/19917808/690eaa90-a0ec-11e6-9a92-181735753107.PNG">

**Comment by MarshallOfSound** [comment]
@arkakkar 

1. You have Electron installed globally, this is a bad plan and can cause conflicts (possible this issue I don't know)  
2. Each `webContents` is it's own process, so if you use a `webview` element it will create a new process

**Comment by arkakkar** [comment]
I tried it with electron installed locally with the issue still happening. Tried changing the package.json where I had different names for product name and name fields.

name : "abcd",
productName : "abcd "

This was the only difference. Changing it to same resolves the issue.
Closing the issue. Thanks
