### ISSUE TITLE
Not allowed to load local resource on packaged React application

### ISSUE THREAD

**Issue by mariovde** [electron/electron#7767]
* Electron version: 1.4.4
* Operating system: OS X 10.11.6

Hi, 

Currently I'm building a react application that runs great when testing with
`electron .`

Now, I've created a distribution build for the react app, and made an electron build from that.
When opening the electron build, I get "Not allowed to load local resource file:///index.html".

` // and load the index.html of the app.
    win.loadURL('file:///index.html');`

I've looked around Stackoverflow and the issues here, but none of them seem to fix the issue.

Anyone any ideas on this one?

regards

Mario

**Comment by MarshallOfSound** [comment]
@mariovde Are you using webpack?  It has produced issues like this before

**Comment by mariovde** [comment]
Yes, but I can't see how the webpack build could influence the electron build.
The react code gets bundled correctly and runs fine.
What could be the issue with the way webpack builds these files?

**Comment by MarshallOfSound** [comment]
`__dirname` and other such constants get mutilated by webpack.

You have a bit of code similar to

```js
mainWindow.loadURL(__dirname + "/index.html")
```

So `__dirnam` being overriden by webpack breaks it

**Comment by mariovde** [comment]
that's not the case in my setup.
I hardcoded the path for the window to open to: 
`function createWindow() {
    // Create the browser window.
    win = new BrowserWindow({width: 1024, height: 768});

    // and load the index.html of the app.
    win.loadURL('file:///index.html');

    // Open the DevTools.
    win.webContents.openDevTools();

    // Emitted when the window is closed.
    win.on('closed', function(){
        // Dereference the window object, usually you would store windows
        // in an array if your app supports multi windows, this is the time
        // when you should delete the corresponding element.
        win = null;
    });
}`

or is this path wrong?
If it didn't find the index.html, it wouldn't complain about access, I think.

**Comment by MarshallOfSound** [comment]
```
win.loadURL('file:///index.html');
```

That's not correct code, you want something similar to what I posted before.  That will try to load a file from the root folder of your drive.

**Comment by mariovde** [comment]
You're right... I get it now. 
I'll try to update my code and let you know if it worked.
Thanks!

**Comment by rob3c** [comment]
In case the above doesn't work for future readers, here's what I posted in a [related issue](https://github.com/electron/electron/issues/5107#issuecomment-266619279):

For me, it turned out to be a misleading error. I was getting the `not allowed to load local resource` error because webpack hadn't finished writing the file before I was trying to load it, not because it was there with the wrong permissions.

I ~fixed~wrapped it with `setTimeout` (the duct tape of javascript) so I could get on with life:
```javascript
setTimeout(() => {
  win.loadURL(`file:///${__dirname}/index.html`);
}, 2000); // 1 second wasn't enough lol
```
