### ISSUE TITLE
electron not catching ipc.messages some times

### ISSUE THREAD

**Issue by rafaelleru** [electron/electron#7768]
- Electron version: more recent
  - Operating system: linux

Im making an app in electron using webtorrent, I wantto load in HTML the contents of torrent but electron its not managin the message updatePlayList the first time I add a torrent, I am doing in the follw form:

`````` <script>
    var Updater = require('./mainWindowUpdater');
    var instance = new Updater();
    var ipc = require('electron').ipcRenderer;
    ipc.on('updatePlayList', function(event, data){
    console.log('he recibido el mensaje "updatePlayList"');
    instance.reloadList(data);
    console.log('he recargado el html');
    })
      </script> ```


this is in my index.html

``````

**Comment by MarshallOfSound** [comment]
You are probably sending a message to the renderer before it is ready.

Ensure you are listening for the event before you fire it.

**Comment by rafaelleru** [comment]
ok I discovered that message from main is send bbefore the data is ready, how I can make the event.sender.send function to wait until data is ready?

**Comment by andymartinwork** [comment]
If main is always initialised first, you could create a "ready" IPC listener event for main. After "ready" is received, you can send events to the renderer process.

In the meantime you can add main events to a queue, and send them all on "ready".

**Comment by zcbenz** [comment]
I'm merging this to #6828.
