### ISSUE TITLE
Gnome: shell.openItem() doesn't work if Nautilus isn't started

### ISSUE THREAD

**Issue by Eugeny** [electron/electron#7769]
- Electron version: 1.4.4
- Operating system: Ubuntu Gnome Xenial

With Gnome 3.20, using `shell.openItem('/home')` does nothing if there's no background file manager process running, e.g. after a reboot. If user has once opened and closed the filemanager (Nautilus), there will be a background process still running and openItem works.

`xdg-open /`, on the other hand, always works no matter whether background process is present.

UPD: same applies to `shell.openExternal('file:///home')`

**Comment by zcbenz** [comment]
That's weird, `openItem` just calls `xdg-open`.

Can try whether `env MM_NOTTTY=1 xdg-open /home` works?

**Comment by Eugeny** [comment]
Yes, it does. I'll try to build a minimal test case now.

**Comment by Eugeny** [comment]
Ok apparently it happened only because I somehow ended up using `require('electron').remote.require('electron').shell.openItem`. Pure brainfart. Case closed.
