### ISSUE TITLE
Scaling BrowserWindow causes webview to scale its inner content 

### ISSUE THREAD

**Issue by taboca** [electron/electron#7777]
- Electron version:     "electron-prebuilt": "^1.3.8",
- Operating system: Mac OS X 10.10.5 (14F1912)

I am trying to make a browser that I can run in reduced scaled size. This browser it's 1080x1920 but the window is to be 1/3 of such size. Therefore, a window that should be actually have native 360x640 size. What I do is to open a BrowserWindow: 

```
  win = new BrowserWindow({
      height : 360,
      width  : 640
  });
```

Then, I load a page and set its inner body width as 1080px and height as 1920px;

Then I apply a webview with width:100% and height:100% to this content, and load a page; 

When I transform: scale(.3) to the main browser page (the 1080px), the size of webview seems to go along fine, therefore it fits within the 360px width (in my attached image, the webview style background is green). 

However, its content shows much smaller. I made the contents of such webview, an HTML web page, to be yellow. 

![screen shot 2016-10-27 at 6 07 48 pm](https://cloud.githubusercontent.com/assets/8658/19783382/8837e45c-9c70-11e6-9d89-c18f1fb9f39c.png)

**Comment by taboca** [comment]
Added a sample here https://github.com/taboca/webview-sample-resize-browser

**Comment by zcbenz** [comment]
Can you try whether it still exists on 1.4.x?

**Comment by taboca** [comment]
Sure @zcbenz, just npm installed the local 1.4.6 and tests with Linux and Mac OS X: 

Using the sample: https://github.com/taboca/webview-sample-resize-browser, and called electron from the local node_modules/electron-prebuilt/**/Electron ./main.js (https://github.com/taboca/webview-sample-resize-browser)

```
"dependencies": {
    "electron-prebuilt": "^1.4.6"
  }
```
 
## Mac OS X 

* Same effect, notice the size of web view (green) seems goood, however actual web content is smaller. 
![screen shot 2016-11-16 at 11 06 55](https://cloud.githubusercontent.com/assets/8658/20348492/ce206670-abec-11e6-9603-b2c61d8a546d.png)

**Comment by zcbenz** [comment]
This is an upstream Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=492182.

I'm closing this since it has already been tracked.

**Comment by taboca** [comment]
Thank you very much for connecting and closing 7777!
