### ISSUE TITLE
Clipboard.readImage() not working with Windows Explorer

### ISSUE THREAD

**Issue by redhotbeani** [electron/electron#7778]
- Electron version: 1.4.4
- Operating system: Windows 10

Scenario:
I want to paste a copied image in my Electron app. But when I copy an image in Windows Explorer (png or jpg) and try to retrieve it from Clipboard, Clipboard.readImage() returns an empty NativeImage Object.

Based on the docs, I assumed it would work with all operating systems:
http://electron.atom.io/docs/api/clipboard/#clipboardreadimagetype

The same code is working fine in macOS. But the majority of our customers are using Windows.

**Comment by redhotbeani** [comment]
Note: when I copy an image inside a Windows app, like Windows Photos, Clipboard.readImage() returns usable NativeImage Object. But when I select an image in Windows Explorer and copy it, clipboard.readImage() is empty.

**Comment by zcbenz** [comment]
When you copy an image in Windows Explorer, you are copying the file instead of copying the contents of image.

This is a duplicate of #2244.

**Comment by saikksub** [comment]
Hello @redhotbeani 

Did you find any solution for this?

**Comment by pangu663** [comment]
windows用不了解决了吗

**Comment by Oleg1983** [comment]
This problem exist on Electron 9. Why this issue was closed without fix ?

**Comment by AkshayCloudAnalogy** [comment]
Any solution for this?

**Comment by chenendian** [comment]
有什么解决办法吗？
