### ISSUE TITLE
Window.opener is null Electron 1.4.4

### ISSUE THREAD

**Issue by hivaga** [electron/electron#7780]
- Electron version: Electron 1.4.4
- Operating system: Windows 10

I have updated to latest Electron, and tried the new webPreferences `sandbox` property 

Example:
`let win = new BrowserWindow({show: true, webPreferences: {sandbox: true}});
 win.loadURL('http://www.yahoo.com');`

As I have understood `sandbox` property will enable the native window.opener support in the new opened window. Unfortunately in the new window when I check the window.opener it is null. Maybe I am making some mistake, but why window.opener is null and how to activate this new feature in order to get the real window.opener. Tnx

**Comment by tarruda** [comment]
In this case the opener is null because a window created with `new BrowserWindow` is a top-level window created by the main process. `window.opener` should only be set in a child window that you create with `window.open`.

**Comment by kevinsawicki** [comment]
Closing this out since it is expected that windows created via `new BrowserWindow` won't have `window.opener` set, only windows created via `window.open` will.
