### ISSUE TITLE
process.versions.node read 6.5.0 instead of the real current Node version

### ISSUE THREAD

**Issue by hasan3ysf** [electron/electron#7782]
* Electron version: 1.4.4
* Operating system: Windows 10
* Node" 7.0.0

I was using Node 6.5.0, just installed Node 7.0.0 but the `process.versions.node` still read the old one, though I made fresh install for everything (Node and Electron)

![image](https://cloud.githubusercontent.com/assets/840673/19796018/e0530e68-9ce9-11e6-8e3b-49b807eb6885.png)

**Comment by MarshallOfSound** [comment]
> I was using Node 6.5.0, just installed Node 7.0.0 but the process.versions.node still read the old one, though I made fresh install for everything (Node and Electron)

Electron uses it's own internal Node.JS version not your system version

**Comment by hasan3ysf** [comment]
Is there a way to upgrade it from my side?

**Comment by enlight** [comment]
@hasan3ysf You'd have to build your own custom version of Electron.
