### ISSUE TITLE
Support setMessage for macOS dialog

### ISSUE THREAD

**Issue by rmccue** [electron/electron#7783]
NSSavePanel (and NSOpenPanel, as a subclass) supports a `message` (via `setMessage:message` in Obj-C), which allows a message to be displayed even when the panel is attached to a parent. Right now, `title` is useless for attached dialogs.

**Comment by rmccue** [comment]
Note: I'd _almost_ suggest defaulting to this when the BrowserWindow is set, as otherwise macOS hides the title completely. It would be nice to have full control over this field for all dialogs though, so unsure what the best behaviour would be.

**Comment by kevinsawicki** [comment]
>  It would be nice to have full control over this field for all dialogs though

After glancing at the [NSSavePanel docs](https://developer.apple.com/reference/appkit/nssavepanel?language=objc), it might be nice to support these others as well:

- `nameFieldLabel`
- `showsTagField`
