### ISSUE TITLE
Help Debugging Render Thread Crash

### ISSUE THREAD

**Issue by joncppl** [electron/electron#7784]
- Electron version: 1.4.4
- Operating system: Win 10 Pro x64

I started getting occasional crashes in the render thread of my application. At first I thought it was my JS, but it happens when literally nothing is happening and the application is sitting idle. Recently it always happens within 5 minutes of the application running.

I debugged the process and found the error: 
`Access violation executing location 0x00007FFF5ADA107C`
which seems to be happening inside ntdll.

I have no idea how to debug this any further as I have no clue what I am looking at. 

I have attached a minidump from the crashing process, so I hope someone can help me out or at least point me in the right direction.

[minidump](https://1drv.ms/u/s!AqaHTHaWAJXUhJpoM690gjNe4WYuZA)
[my application on bitbucket](https://bitbucket.org/joncppl/acc-e)

**Comment by paulcbetts** [comment]
You most likely have bad RAM, replace it

```
DEFAULT_BUCKET_ID:  SOFTWARE_NX_FAULT

PROCESS_NAME:  AnimeCommandCenter.exe

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000008

# 12  Id: 4a60.4590 Suspend: 0 Teb: 00000028`123c9000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 00000028`133ff6d8 00007fff`7c0c31dd 0x00007fff`5ada107c
01 00000028`133ff6e0 00007fff`7c0c2e65 ntdll!EtwpEventApiCallback+0xbd
02 00000028`133ff770 00007fff`7c0c555b ntdll!EtwpUpdateEnableInfoAndCallback+0xb9
03 00000028`133ff7b0 00007fff`7c0c531b ntdll!EtwpProcessNotification+0x43
04 00000028`133ff7e0 00007fff`7c0c504c ntdll!EtwDeliverDataBlock+0x8b
05 00000028`133ff840 00007fff`7c0fe210 ntdll!EtwpNotificationThread+0x6c
06 00000028`133ff9b0 00007fff`7c0e3123 ntdll!TppExecuteWaitCallback+0x8c
07 00000028`133ff9f0 00007fff`7b6c8364 ntdll!TppWorkerThread+0x923
08 00000028`133ffdf0 00007fff`7c115e91 kernel32!BaseThreadInitThunk+0x14
09 00000028`133ffe20 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```

**Comment by joncppl** [comment]
mkay.
running memtest86 on that pc now and gonna try testing on another one.

**Comment by joncppl** [comment]
rebuilt the application on a different PC, also win 10.
same exception in the same place
[dump](https://1drv.ms/u/s!AqaHTHaWAJXUhJppJH1g8MZZttQTqg)

is there any other information I can provide?

**Comment by zcbenz** [comment]
It is very likely caused by some third party native modules in your app, you can probably debug this by disabling certain modules.
