### ISSUE TITLE
Shell function 'showItemInFolder' should open top-level directory when no file is specified.

### ISSUE THREAD

**Issue by jayalfredprufrock** [electron/electron#7790]
Currently it's not possible to open up a folder using the shell function `showItemInFolder` unless you know of a file/directory within that folder. Sometimes this isn't possible, i.e. the folder is empty, but it is still useful to be able to target that folder directly.

It would be great if passing a directory to `showItemInFolder` would open that directory, instead of the folder that directory exists in. I suppose that makes the name of the function a little confusing, so I'd also welcome a new function, `showFolder`, that would allow for this use case.
- Electron version: Latest
- Operating system: OSX

**Comment by kevinsawicki** [comment]
You should be able to open a folder by passing the path to [shell.openItem](http://electron.atom.io/docs/api/shell/#shellopenitemfullpath). Is that not working as expected for you?

**Comment by jayalfredprufrock** [comment]
Ahh, well I can see now that shell.openItem does work (could have sworn I tried this...), however I think the confusion was it doesn't focus the newly opened window. Now I can see other related issues, #4349, #4951 discussing this behavior. I'll close this out and follow along with the others. Thanks!
