### ISSUE TITLE
How do I know when my electron app should get an update?

### ISSUE THREAD

**Issue by tarjei** [electron/electron#7794]
* Electron version: Na
* Operating system: ALL :)

Hi, two questions:

1. Is there a release bug or some mailinglist I can subscribe to to know if I should release a new version of my electron app due to security issues in electron?

2. What are the differences between the 1.3.x series and the 1.4.x series? The download page provides scant guidance on this. 

Again, thanks for a great project!
Tarjei

**Comment by MarshallOfSound** [comment]
1. If you watch the repository you will see when new versions are released.  
2. A minor bump in Electron (1.3 -> 1.4) indicates a major bump in Chromium,  In that case from 52 -> 53


And then this 👍 
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
