### ISSUE TITLE
Electron goes in infinite loop opening window as of v1.4.x

### ISSUE THREAD

**Issue by greggman** [electron/electron#7801]
- Electron version: 1.4.0 and 1.4.4 tested
- Operating system: macOS 10.12.1

This page was working in 1.3.8 but stopped working in 1.4.0 and 1.4.4 (didn't check in between versions)
- When the page works the window will be green and working
- When the page fails the window will be white and take no input (Cmd-Q will not close the window)

Removing almost any CSS makes the page work. The page works in Chrome

run with `./node_modules/.bin/electron main.js`
## Repo
- Download zip
- unzip
- Execute
  
  ```
   cd to electron-infinite-loop-issue
   npm install
   ./node_modules/.bin/electron main.js
  ```
## Code

main.js is just

```
"use strict";

const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

let window;
app.on('ready', () => {
  window = new BrowserWindow({});
  window.loadURL(`file://${__dirname}/app/index.html`)
  window.webContents.openDevTools();
});
```

index.html is

```
<!DOCTYPE html>
<html>
<head>
  <style>
    html, body {
      height: 100%;
      margin: 0;
      background-color: green;
    }
    .split.split-horizontal {
      height: 100%;
      float: left;
    }
    .browser {
      width: 100%;
      height: 100%;
    }
    .folders {
      width: 100%;
      height: 100%;
      position: relative;
      overflow: scroll;
    }
  </style>
</head>
<body>
<div class="browser">
  <div class="split split-horizontal"><div class="folders"></div></div>
</div>
</body>
</html>
```

[electron-infinite-loop-issue.zip](https://github.com/electron/electron/files/560570/electron-infinite-loop-issue.zip)

**Comment by greggman** [comment]
I'm sure some CSS expert can tell me what I'm doing wrong but the workaround I used was to change `<div class="browser">` to `<div class="hack-browser">` and then add the following script at the bottom

```
<script>
document.querySelector(".hack-browser").className = "browser";
</script>
```

**Comment by xywz** [comment]
Can confirm.

Reduced index.html to:
```html
<style>
  body {
    margin: 0;
    float: left;
  }
  main {
    height: 100%;
    overflow: scroll;
  }
</style>

<main>Hello, World!</main>
```

**Comment by MarshallOfSound** [comment]
Can't confirm on Windows, none of the provided HTML samples cause the given issue

**Comment by kevinsawicki** [comment]
> Can't confirm on Windows, none of the provided HTML samples cause the given issue

I can confirm on Mac, wonder if this might be https://bugs.chromium.org/p/chromium/issues/detail?id=644635
