### ISSUE TITLE
GlobalShortcut keyUp

### ISSUE THREAD

**Issue by ThariqS** [electron/electron#7802]
I would like to get an event to know when the user lets go of a global shortcut, is this possible? i.e. the equivalent of a 'keyUp' method

**Comment by kevinsawicki** [comment]
>  is this possible?

This is not possible using the `globalShortcut` APIs. Electron wraps Chrome's [global_shortcut_listener.h](https://cs.chromium.org/chromium/src/chrome/browser/extensions/global_shortcut_listener.h) API which only exposes a key press event.

You could write a native module that hooks into OS keyboard APIs and implement this that way for your app. Closing this out.
