### ISSUE TITLE
Does speech recognition work in Electron?

### ISSUE THREAD

**Issue by IonicaBizau** [electron/electron#7803]
I've made an experiment few years ago to get text from speech (http://ionicabizau.github.io/Color-Puzzle/).

While in Chromium it does work nice, in Electron I don't get any errors, but the message is not sent in the `onresult` handler.

I'm just wondering: is there a specific option I have to pass to Electron to enable speech recognition or something like that?

**Comment by MarshallOfSound** [comment]
@IonicaBizau Speech recognition is severely limited by Electron's hard coded API key.  If you want to get a larger quota just for your app you would have to build Electron yourself with your own API key or override Electron's key with the API key environment variable.

**Comment by IonicaBizau** [comment]
Thanks. But the problem is that it doesn't work at. 

How to get a new key and override the current one via an ENV variable?

**Comment by manidlou** [comment]
@IonicaBizau for getting new key, you may visit https://www.chromium.org/developers/how-tos/api-keys, and for overriding env variables https://electron.atom.io/docs/api/environment-variables/#google_api_key.
