### ISSUE TITLE
Text to speech

### ISSUE THREAD

**Issue by IonicaBizau** [electron/electron#7804]
Text to speech in Chrome sounds way better than in Chromium. Well, actually in my Chromium browser it doesn't work at all (no errors, tho), but in Electron *sometimes* it does, but it sounds robotic.

What are the steps to enable text to speech in Electron and preferably use the Chrome text to speech?

**Comment by MarshallOfSound** [comment]
@IonicaBizau More or less the same reasons as #7803

This will be limited by the API key that Electron hard codes.
