### ISSUE TITLE
Electron fails to install with npm.

### ISSUE THREAD

**Issue by kiefersmith** [electron/electron#7805]
- Electron version: ???
- Operating system: Raspbian Jessie

When trying to install MagicMirror on my RasPi I (and numerous other users) are getting the error output listed here: [pastebin](http://pastebin.com/LZLaqZFQ).

It looks like this issue is with electron/ npm and not the MagicMirror app.  Anyone on the electron side have any ideas?

Thank you!

**Comment by MarshallOfSound** [comment]
You're probably missing a few dependencies on the raspberry pi.

If you set these environment variables

```bash
export ELECTRON_ENABLE_LOGGING=true
export ELECTRON_ENABLE_STACK_DUMPING=true
```

And then run the Electron executable you should see some errors pop up about missing deps

**Comment by kiefersmith** [comment]
Do I run those commands in the command console?

I re-imaged the OS and seem to have issues downloading electron at all.

**Comment by MarshallOfSound** [comment]
@kiefersmith Issues downloading Electron we can't help with as it is a network issue on your side of things 99.999% of the time.

When you get it downloaded running

```
export ELECTRON_ENABLE_LOGGING=true
export ELECTRON_ENABLE_STACK_DUMPING=true
npm install electron
node_modules/.bin/electron
```

In a new and empty folder will produce and errors you need to fix missing dependencies

**Comment by kiefersmith** [comment]
Hey, I got it running.  Thanks for the help!
