### ISSUE TITLE
Mac minimizing issues 

### ISSUE THREAD

**Issue by daltonmenezes** [electron/electron#7806]
* Electron version: 1.4.3
* Operating system: Mac OsX

Two Yout Player users have reported me:

> Once the app is minimised (by clicking "_"), it won't open up again, when clicking on the icon on the dock. I open it, minimise it and then I can't maximise it anymore.

I'm not be able to reproduce this behavior, because I don't have a Mac. On a Virtual Machine this is not happening. Anyone knows about this behavior on mac and how to solve it? I don't think it's about any electron bug, but I believe that's about the right way to structure a minimal mac app.

If you want to test this Yout Player build, please, [download it here.](http://www.mediafire.com/file/s967gb0fmif3vpa/Yout-1.1.4-en-mac-x64.zip)

**Comment by MarshallOfSound** [comment]
@daltonmenezes You have to listen for the `activate` event an un-minimize the window yourself.

https://github.com/electron/electron/blob/master/docs/api/app.md#event-activate-macos

**Comment by daltonmenezes** [comment]
Hi @MarshallOfSound . Thanks for the answer, but I'm using it to test the fix in this way:

```
app.on('activate', (e) => {
  e.preventDefault();
  app.show();
  app.focus();
});
```
and
```
  mainWindow.on('activate', () => {
    mainWindow.restore();
    mainWindow.focus();
    mainWindow.show();
  });

```
But the issue persists. am I doing it wrong?

**Comment by MarshallOfSound** [comment]
The second one looks like it should work.  For reference the code I use it

```js
import { app } from 'electron';

app.on('activate', () => {
  const mainWindow = WindowManager.getAll('main')[0];
  if (mainWindow) {
    mainWindow.show();
  } else {
    // Something went wrong
    app.quit();
  }
});
```

**Comment by daltonmenezes** [comment]
@MarshallOfSound I've discovered the problem. It's a always on top bug. It's needed to disable it before minimize the window. So, that's solve the problem in the app level:

```javascript
  ipcMain.on('minimize-main-window', () => {
    mainWindow.setAlwaysOnTop(false);
    mainWindow.minimize();
  });

```
```javascript
app.on('activate', () => {
  mainWindow.restore();
  mainWindow.setAlwaysOnTop(true);
});
```
