### ISSUE TITLE
Electron fails with Illegal instruction on Ubuntu 32-bit (Cpu Amd)

### ISSUE THREAD

**Issue by giuliohome** [electron/electron#7808]
* Electron version: downloaded from https://github.com/electron/electron/releases/download/v1.3.8/electron-v1.3.8-linux-ia32.zip
* Operating system: Ubuntu 12.04 LTS

After unzipping
`mirko@localhost:~/Downloads/electron$ ls`

`blink_image_resources_200_percent.pak LICENSES.chromium.html
content_resources_200_percent.pak locales
content_shell.pak natives_blob.bin
electron resources
icudtl.dat snapshot_blob.bin
libffmpeg.so ui_resources_200_percent.pak
libnode.so version
LICENSE views_resources_200_percent.pak`

`mirko@localhost:~/Downloads/electron$ ./electron`

`Illegal instruction`

Info about CPU from lshw

` *-cpu product: AMD Athlon(tm) vendor: Hynix Semiconductor (Hyundai Electronics) physical id: 1 bus info: cpu@0 version: 6.6.2 size: 1250MHz width: 32 bits capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pat pse36 mmx fxsr sse syscall mmxext 3dnowext 3dnow up vmmcall`

More info about the context [here](https://github.com/Microsoft/vscode/issues/14724) and [here](http://askubuntu.com/questions/843518/visual-studio-code-on-ubuntu-12-04-32bit)

**Comment by kevinsawicki** [comment]
Are you able to reproduce with Electron 1.4.4 as well?

**Comment by giuliohome** [comment]
@ kevinsawicki Thank you for your prompt reply. Let me find a link to download Electron 1.4.4. I'll get back to you soon

**Comment by giuliohome** [comment]
Donwloaded and unzipped the 1.4.4 release

Same issue

mirko@localhost:~$ cd /home/mirko/Downloads/electron
mirko@localhost:~/Downloads/electron$ ls
blink_image_resources_200_percent.pak  LICENSES.chromium.html
content_resources_200_percent.pak      locales
content_shell.pak                      natives_blob.bin
electron                               resources
icudtl.dat                             snapshot_blob.bin
libffmpeg.so                           ui_resources_200_percent.pak
libnode.so                             version
LICENSE                                views_resources_200_percent.pak
mirko@localhost:~/Downloads/electron$ ./electron 
Illegal instruction
mirko@localhost:~/Downloads/electron$

**Comment by kevinsawicki** [comment]
Are you able to download and install Chromium 53 on that machine and verify it launches and can visit pages without issues?

**Comment by giuliohome** [comment]
I'm writing from that machine... Again, it's an old machine, so I'm installing only lightweight things. If you think it is an hardware/software limit, I'd just like to know which are the minimum requirements to run electron (and vs code)

**Comment by kevinsawicki** [comment]
> If you think it is an hardware/software limit

Not sure at this point, whether Chromium 53 runs would be a good indicator.

**Comment by giuliohome** [comment]
I suspect that a cmd simple like
`sudo apt-get install chromium-browser`
wouldn't be enough... do you know which is the procedure (a link or a wiki) for this operating system? 

Also, just out of my curiosity, don't you have the possibility  (a log or a verbose switch) to directly check to what is due that "Illegal instruction"?

**Comment by kevinsawicki** [comment]
> do you know which is the procedure (a link or a wiki) for this operating system?

Maybe just try Chrome 54 from https://www.google.com/chrome/browser/desktop/index.html

> Also, just out of my curiosity, don't you have the possibility (a log or a verbose switch) to directly check to what is due that "Illegal instruction"?

Can you try running `ELECTRON_ENABLE_STACK_DUMPING=true ./electron`?

**Comment by giuliohome** [comment]
Interesting... where is the stack dump? :-)

`mirko@localhost:~/Downloads/electron$ ELECTRON_ENABLE_STACK_DUMPING=true ./electron`
`Illegal instruction`
`mirko@localhost:~/Downloads/electron$ `

**Comment by giuliohome** [comment]
From ddd:

(gdb) run /home/mirko/Downloads/electron/electron
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x08adddf5 in tcmalloc::SizeMap::Init() ()
(gdb) (gdb) run /home/mirko/Downloads/electron/electron
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x08adddf5 in tcmalloc::SizeMap::Init() ()
(gdb)

**Comment by giuliohome** [comment]
From the [internet](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Spotify-crashes-with-error-Illegal-instruction-when-trying-to/td-p/56701), I guess I've found a similar (?) crash of spotify

A couple of comments from spotify community that could maybe apply also to my case with electron

> What stands out to me is that it looks like none of us have CPUs which support SSE2.  I have seen people with other software based on the chromium embedded framework (libcef) say that libcef requires SSE2, and therefore try to say that it isn't their responsibility to fix the bug, because it is in libcef, not in the software they write which uses libcef.

and

> I'm almost convinced these illegal instruction errors are because one of the 3rd party libraries that Spotify uses requires SSE2 enabled processor

**Comment by zcbenz** [comment]
> Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".

It seems that you are using a very old CPU, so it is very likely that the prebuilt binaries have used instructions not supported by your machine. 

I'm merging this to #259.
