### ISSUE TITLE
What version of node to test ?

### ISSUE THREAD

**Issue by yopbeast** [electron/electron#7811]
hi my question is quite stupid but when you have to make an electron client app, 

which node version do you use to build the app and which version should be the app  tested on?

I have node 6.0.0 installed and everything works great but since i have to include node_modules for the app in order to run the app on other computers,

 i am wondering how to handle the different node versions....do you have some advice?

Thanks

**Comment by kevinsawicki** [comment]
> which node version do you use to build the app and which version should be the app tested on?

Node is only used during the build of your app so any version can be used as long as the modules you use to build your app (such as `electron-packager`, `npm`, etc.) are supported by that version.

Electron currently builds on top of Node 6.5.0 so any modules that you app distributes should work support that version.

**Comment by yopbeast** [comment]
@kevinsawicki Hey thank you! i was really in doubt for it, now it's everythings clear.
