### ISSUE TITLE
Cannot debug script loaded by vm.runInNewContext()

### ISSUE THREAD

**Issue by michaelbromley** [electron/electron#7816]
* Electron version: 1.4.3
* Operating system: Windows 10 x64

I have an Electron app that runs user scripts in a sandbox like this:
```TypeScript
function runInSandbox(visPath: string): IVisualization {
    let context = {
        require: (moduleName) => {
            // I implement a custom "safe" require method here
        },
        module: {}
    };
    let filename = path.join(visPath, 'index.js');
    let options = {
        filename,
        timeout: 5000
    };
    let data = fs.readFileSync(filename);
    return vm.runInThisContext(data, options);
}
```

The problem is that it seems impossible to debug the user script in the debugger. 

The user script executes correctly, but if I put `debugger` statements in it, the devtools do not break on them as expected. 

Neither can I step into the script. If I step down through the calls in the vm module, I eventually get the the final method call which executes the script, and the devtools just skip it an move to the next part of my app code.
```JavaScript
// vm.js
Script.prototype.runInContext = function(contextifiedSandbox, options) {
  if (options && options.breakOnSigint) {
    return sigintHandlersWrap(() => {
      return realRunInContext.call(this, contextifiedSandbox, options);
    });
  } else {
    return realRunInContext.call(this, contextifiedSandbox, options); // <-- stepping into this call doesn't work
  }
};
```

Note that if I use `vm.runInThisContext()`, then debugger statements and breakpoints work as expected - but I do not want to use that method since it kinda defeats the point of a sandbox.

I have been searching around quite a bit and found a few potentially relevant issues, which may help in resolving this:

* https://github.com/node-inspector/node-inspector/issues/67
* http://stackoverflow.com/questions/21183403/debugging-code-that-is-run-in-node-jss-vm

**Comment by zcbenz** [comment]
I'm afraid this is a limitation of devtools, it can only debug the code under the JavaScript context create by blink, not the code under Node context.

I'm closing this as won't fix since it is an upstream devtools issue and we are unable to fix this on Electron's side.

**Comment by xosuperpig** [comment]
Is there any issue about this problem for devtools? 
And
Can I create another devtool instance to debug this context?

**Comment by shrinktofit** [comment]
@zcbenz  I think this is not a devtools problem since I get it worked when run with Node or within Electron main process only, but it doesn't if run in render processes.
