### ISSUE TITLE
I don't know why...

### ISSUE THREAD

**Issue by shadowcz007** [electron/electron#7819]
Electron(58611,0x7fff7d204000) malloc: *** error for object 0x7fb0b660e8f0: pointer being freed was not allocated *** set a breakpoint in malloc_error_break to debug

* Electron version:  "electron": "^1.4.3"
* Operating system:OSX EI captan 10.11.5

**Comment by zeke** [comment]
Can you provide a minimal app that reproduces this problem?

**Comment by zcbenz** [comment]
Closing until more information is provided.
