### ISSUE TITLE
webview ajax call problem

### ISSUE THREAD

**Issue by pouu69** [electron/electron#7824]
* Electron version: v1.4.3
* Operating system: MacOS, Window(all)

Using the entire website webview tag to develop a desktop app
The electron is simply wrapped.
But sometimes when the call is immediately ajax fail.
I mean no difference or not the ajax call.
The ajax header is written as follows: "provisional headers are shown"

i don't know why .ㅜㅜ

**Comment by zeke** [comment]
Please provide a minimal app that reproduces this problem.

**Comment by pouu69** [comment]
i'm sorry. i can't show you

**Comment by MarshallOfSound** [comment]
> i'm sorry. i can't show you

Without any way to reproduce the issue no one can really help you attempt to fix it.  Your app itself may be closed source but can you extract a minimal code sample from the app that demonstrates the issue without revealing the entire source code.

**Comment by zcbenz** [comment]
Closing since we are unable to solve this without more information.
