### ISSUE TITLE
node-sqlite3 rebuild error in Windows 7

### ISSUE THREAD

**Issue by Labber1900** [electron/electron#7825]
* Electron version:1.3.8
* Operating system:MacOS sierra ,window 7 pro
* node.js:7.0

hi,
In my MacOS system ,I rebuild sqlite3 it's worked:

npm install --save-dev sqlite3
npm install --save-dev electron-prebuilt
npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild
But in Windows7.It doesn't work：
【node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/electron-v1.3-win32-x64.tar.gz】

In my bower（chrome or IE），it tell me ：
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>D708B3BE1090E2BF</RequestId>
<HostId>
J5rcWvRsUCw4J47g44frDG4tacepmn9e7pmdSi7LEBgnbfwYYnZTQduEW6SRYoU/BCwF9jrG8JM=
</HostId>
</Error>

**Comment by MarshallOfSound** [comment]
@Labber1900 Looks like you fed it the wrong version `1.3` you need to be more precise and give it something like `1.3.0`

**Comment by Labber1900** [comment]
@MarshallOfSound  where set the precise electron version? in ./node_modules/electron_rebuild?

**Comment by MarshallOfSound** [comment]
Use the `--version` argument 👍

**Comment by zcbenz** [comment]
Closing since this had been answered.
