### ISSUE TITLE
[style] Blurry fonts in windows use latest electron version(v1.4.4)

### ISSUE THREAD

**Issue by divefox** [electron/electron#7826]
* Electron version: v1.4.4
* Operating system:window 7
Hi, I have the problem with the electron Rendering. When I run the electron in windows, I found that the fonts are blurry and mess up, I can't see words clearly enough.And I output the info of my electron version, here is:
{ http_parser: '2.7.0',
  node: '6.5.0',
  v8: '5.3.332.45',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '50',
  openssl: '1.0.2h',
  electron: '1.4.4',
  chrome: '53.0.2785.113',
  'atom-shell': '1.4.4' }
and below is two pictures of I can offered. 
I searched this problem in Google.It is the Chromium  bug.
Can someone help me to fix it? Or is there a stable version of electron which haven't have this Rendering fonts problem that I can use?
Thank you very much!

<img width="337" alt="2016-11-01 2 14 50" src="https://cloud.githubusercontent.com/assets/2367779/19881109/ecd43fa2-a03d-11e6-84ff-f289954063dc.png">
<img width="231" alt="2016-11-01 2 15 20" src="https://cloud.githubusercontent.com/assets/2367779/19881112/ef86fd98-a03d-11e6-93a1-4ced8670efd3.png">

**Comment by zcbenz** [comment]
This is because Chromium switched to use DirectWrite for text rendering, and I'm afraid according to Chromium's plan there will be no way to turn it off. So your only solution is to use old Chromium versions for your product.

**Comment by divefox** [comment]
@zcbenz Thank you for your reply! And as you suggest, which Chromium version is best ? And I can do as below:
1: get the Chromium
2: build Chromium to electron (version 1.4.4)
is that right?
Thank you very much!

**Comment by enlight** [comment]
@divefox I think what @zcbenz meant is that you'll have to use older versions of Electron (that are built on older versions of Chromium), you can't just swap in an older version of Chromium into the current version of Electron (at least not without doing a lot of work).

**Comment by divefox** [comment]
@enlight Get it! Thank you very much!

**Comment by Maybrittnelson** [comment]
@divefox I encountered the same problem with you, you solve it, how is the solution
