### ISSUE TITLE
Chrome Debugger Protocol version 1.2 not supported

### ISSUE THREAD

**Issue by inca** [electron/electron#7827]
* Electron version: 1.4.4
* Operating system: Mac OS X 10.11.6

```es6
webContents.debugger.attach('1.2')
```

```
Could not call remote function 'attach'. Check that the function signature is correct.
Underlying error: Requested protocol version is not supported (...)
```

Is there a plan to enable support for CDP v1.2 any time soon? Chrome docs refer to 1.2 as stable — and I see they unpublished documentation for version 1.1, so I take it as a hint of deprecation :/

**Comment by deepak1556** [comment]
The current chromium version only supports <=1.1, once we upgrade should get support for 1.2.
