### ISSUE TITLE
proxy authentication with pre-saved username and password.

### ISSUE THREAD

**Issue by kueychuj** [electron/electron#7828]
I did some research on how to set up proxy connection in electron app and I was wondering whether there is a way to login the proxy server using pre-saved username and password (which are saved in local storage).

It seems that app.login could not auto-fill the proxy authentication information. ([http://stackoverflow.com/questions/38281113/how-do-i-use-the-login-event-in-electron-framework](http://stackoverflow.com/questions/38281113/how-do-i-use-the-login-event-in-electron-framework))

**Comment by deepak1556** [comment]
> It seems that app.login could not auto-fill the proxy authentication information. 

Yup, it is not the intended behavior of the api.

**Comment by zcbenz** [comment]
You can set the proxy by putting username and password as part of proxy URL.
