### ISSUE TITLE
X11 startx with enabling touch events

### ISSUE THREAD

**Issue by sn0opr** [electron/electron#7829]
* Electron version: 1.4.3
* Operating system: Debian 8

I have a Raspberry Pi with touch screen
I launch the app using startx command, but it dosn't handle the touch event.
how to enable handing the touch events for electron.

**Comment by kevinsawicki** [comment]
@sn0opr are you able to test out if chrome/chromium handles the touch event properly on that same device?

**Comment by zcbenz** [comment]
I'm closing this since it is very likely a Chromium issue.
