### ISSUE TITLE
Offscreen rendering stops sending paint events after a while

### ISSUE THREAD

**Issue by ignjat** [electron/electron#7830]
* Electron version: 1.4.4
* Operating system: macOS Sierra

GPU acceleration is disabled. Browser window is hidden. Everything works fine for a while and then paint events stop until there are more input events (mouseMove for example). Once it's in this mode it doesn't recover so paints only come when input events are injected.

**Comment by deepak1556** [comment]
Seems more like a throttling issue, have you tried disabling `backgroundThrottling` ? There is an unconfirmed [issue](https://github.com/electron/electron/issues/7553) that `backgroundThrottling` is not working in latest version of Electron.

**Comment by ignjat** [comment]
Thanks @deepak1556 that was it.
After doing:
const powerSaveBlocker = electron.powerSaveBlocker;
powerSaveBlocker.start('prevent-app-suspension');
everything seems to be working fine.
