### ISSUE TITLE
Notifications hang entire process for 2+ minutes

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#7831]
* Electron version: `1.4.4`
* Operating system: Windows

I came across this bug with a few of my users.  It appears as though on Windows on some systems showing a native notifications hands the entire process.

Interestingly one of the workarounds to resume the process is killing and restarting the `explorer.exe` process so I'm thinking it may have something to do with download the notification icon to the local cache? (I actually have no ideas here...)

This appears to be a regression from `1.3.x` to `1.4.x` as this issue was not present when the app was driven by `1.3.6`.

**Comment by MarshallOfSound** [comment]
So after a stupid amount of digging this turned out to be an issue with some custom JS I was using to modify the `Notification` class.

```js
class SilentNotification {
  constructor(title, options={}) {
    const opts = options;
    opts.silent = true;

    this._notification = new window._Notification(title, opts);
    this.title = this._notification.title;
    this.dir = this._notification.dir;
    this.lang = this._notification.lang;
    this.body = this._notification.body;
    this.tag = this._notification.tag;
    this.icon = this._notification.icon;
    this.data = this._notification.data;
    this.requireInteraction = false;
    this.silent = true;

    // This property screws it all up
    Object.defineProperty(this, 'onclick', {
      get: () => this._notification.onclick,
      set: (fn) => { this._notification.onclick = fn; },
      configurable: true,
      enumerable: true,
    });
  }

  close() {
    this._notification.close();
  }
}
```

For some reason setting a custom setter and getter and mapping it to the `Notification` breaks things.  Still investigating

**Comment by levrik** [comment]
@MarshallOfSound I got complete process freezes on the WhatsApp desktop client and also on Whatsie (before it got unmaintained). Might be related.

**Comment by zcbenz** [comment]
I'm closing this since it seems to be caused by user's code hacking `Notification`. Will reopen if this turns out to be a bug after getting more information.

**Comment by brigadier** [comment]
I always have this issue with skypeforlinux in KDE Plasma, when skype window is not focused. 100% reproducible.

**Comment by akontsevich** [comment]
Bug still exists in both Riot and Skypeforlinux: https://github.com/vector-im/riot-web/issues/5704#issuecomment-383262904 and seems in many other applications. Please fix.

**Comment by mhnavarro** [comment]
Issue is reproducible with slack too. Using the electron app.

**Comment by jhgg** [comment]
Noticed this issue too on linux. The repro steps are pretty simple. If you are using a desktop environment without anything that is accepting libnotify notifications (in my case, minimal i3, no `notification-daemon` or `dunst` running). I think this happens because https://github.com/electron/electron/blob/master/brightray/browser/linux/libnotify_notification.cc#L141 can block if no notification daemon is running to accept the request. 

`notify_notification_show` eventually calls `g_dbus_proxy_call_sync` within libnotify... which yeah... blocks.

**Comment by DewaldDeJager** [comment]
I had the same issue with any Electron apps and solved it by installing a notification daemon (Dunst). Thanks @jhgg! I'm also running i3wm.

**Comment by akontsevich** [comment]
@DewaldDeJager, just install `Dunst` - that's all? Or need to do some setup for it?

**Comment by ckerr** [comment]
Reopening based on @jhgg's [comment](https://github.com/electron/electron/issues/7831#issuecomment-403655937) about the blocking `g_dbus_proxy_call_sync()` call.

**Comment by ckerr** [comment]
Hmmm actually I see this issue is 2 years old and was reported on Windows. On second thought I'm going to re-close this to avoid issue confusion.

Linux users, please file a new issue regarding the blocking behavior on Linux and let's track this issue there.
