### ISSUE TITLE
Undocumented method toggleDevTools

### ISSUE THREAD

**Issue by kof** [electron/electron#7832]
* Electron version:
latest

Method [toggleDevTools](https://github.com/electron/electron/blob/master/lib/browser/api/browser-window.js#L174) of browser window is not [documented](http://electron.atom.io/docs/api/browser-window/)

**Comment by sbruchmann** [comment]
[`toggleDevTools`](http://electron.atom.io/docs/api/web-contents/#contentstoggledevtools) is actually documented since it's a method of [`webContents`](http://electron.atom.io/docs/api/web-contents/).

**Comment by kof** [comment]
I think I got confused because lots of WebContents methods are also BrowserWindow methods, but they are documented only for webContents.

**Comment by kevinsawicki** [comment]
> I think I got confused because lots of WebContents methods are also BrowserWindow methods

Yeah, I think for the 2.0 API, we'll either remove the `BrowserWindow` methods that just proxy to `webContents` methods or expose all the `webContents` methods through `BrowserWindow`, right now it is a little inconsistent with what is proxied and what isn't.

Closing this out.

**Comment by kof** [comment]
From taxonomy perspective, proxying WebContents methods on BrowserWindow means BrowserWindow can  do everything WebContents can do. So why do you need WebContents then? Something is wrong with the abstractions.

**Comment by patheticcockroach** [comment]
The toggleDevTools method of BrowserWindow is also missing from the Type definitions file (`electron.d.ts`). Meaning when you want to use it in TypeScript, you need to use `myWindow.webContents.toggleDevTools();` instead of `myWindow.toggleDevTools();` to avoid an error (`error TS2339: Property 'toggleDevTools' does not exist on type 'BrowserWindow'`)

**Comment by warrenbuckley** [comment]
Yep just run into this problem with the typescript definition file myself like @patheticcockroach 
Any chance it can be updated please :)

**Comment by SimonBiggs** [comment]
A fix to get typing is to do the following:

```typescript
BrowserWindow.getFocusedWindow().webContents.toggleDevTools();
```

**Comment by ChristofferGylin** [comment]
It´s 8 years later and I´m having this problem too
