### ISSUE TITLE
Re-launch Application on Reboot

### ISSUE THREAD

**Issue by ryanpager** [electron/electron#7833]
* Electron version: 1.4.1
* Operating system: Mac OSX / Windows

Question -- is there a way to auto launch the application on restart similarly to something like Skype? (i.e. I can set a toggle in settings somewhere that says start on windows start)

I apologize if this has been answered, couldn't find anything about it after looking in the documentation & reading issues for a couple hours.

**Comment by MarshallOfSound** [comment]
See https://github.com/electron/electron/blob/master/docs/api/app.md#appsetloginitemsettingssettings-macos-windows

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
