### ISSUE TITLE
100% cpu on single cpu Windows machine when opening  WebSocket connection

### ISSUE THREAD

**Issue by coopernyc** [electron/electron#7839]
* Electron version: 1.4.5
* Operating system: Windows 7 x64 **Single** CPU
![capture2](https://cloud.githubusercontent.com/assets/11201225/19902952/203249fc-a043-11e6-86f0-5164a2cb9265.PNG)
![capture1](https://cloud.githubusercontent.com/assets/11201225/19902953/20329c0e-a043-11e6-9429-7aa77da6086c.PNG)

When opening websocket connection in electron main process, cpu gets 100% and for several minutes the whole win system becomes very slow and unresponsive.
Same websocket connect under plain node executes immediately with minimal cpu spike.

build/
 package.json
 main.js

run app as : electon build/

build/package.json:
{
  "name": "application-name",
  "version": "0.0.1",
  "main": "main.js"
}

simple build/main.js file:

const electron = require('electron');
const {app} = electron;

app.on('ready', () => {
    startup();
});

// Quit when all windows are closed.
app.on('window-all-closed', () => {
    // On OS X it is common for applications and their menu bar
    // to stay active until the user quits explicitly with Cmd + Q
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('quit', () => {    
    process.exit(0);
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (win === null) {
        startup();
    }
});

function startup() {	
	var WebSocket = require('ws');
	console.log('connecting client');
	var ws = new WebSocket('ws://core-dev-wgw01:10120');
	ws.on('open', function open() {
		console.log('ws open');
	});

	ws.on('message', function(data, flags) {
		console.log(data);
	});		
};

sample test.js run as node test.js

function startup() {
		
	var WebSocket = require('ws');
	console.log('connecting client');
	var ws = new WebSocket('ws://core-dev-wgw01:10120');
	ws.on('open', function open() {
		console.log('ws open');
	});

	ws.on('message', function(data, flags) {
		console.log(data);
	});	
}
startup();

Any help is really appreciated. Our client is using single or minimal cpu stack on virtual pcs. 
Application is running slow to 0 due to minutes of 100% on start up and opening websocket

**Comment by enlight** [comment]
Reminds me of these issues:
https://stackoverflow.com/questions/39648969/node-js-electron-applications-for-single-core-windows-7-machines-are-slow-on-fil
https://discuss.atom.io/t/electron-cpu-performance-on-windows-server-2012-r2/34573/2

**Comment by zcbenz** [comment]
I'm merging this to #1833 since they are essentially the same problem: we have bugs on message loops with node integration.

The workaround, is to use the module in a forked script via `child_process.fork`.
