### ISSUE TITLE
Use node_sqlite3 in an electron forked process

### ISSUE THREAD

**Issue by pietrovismara** [electron/electron#7841]
* Electron version: 1.4.5
* Operating system: Linux Mint
* Node version: 6.5.0

I am trying to use sqlite3 in a process forked by electron. 
When i install sqlite3 with npm it says: 
```
Success: "node-v48-linux-x64/node_sqlite3.node" is installed via remote
```
But when i fork the process with `child_process.fork` i get:
```
Error: Cannot find module '/home/user/project/node_modules/sqlite3/lib/binding/node-v50-linux-x64/node_sqlite3.node'
```
That's strange since i'm using the same nodejs version that is used by electron (6.5.0).
Can someone help me?

**Comment by zeke** [comment]
Does your sqlite3 installation work in a "non-forked" Electron process?

**Comment by pietrovismara** [comment]
Nope, for an electron process i need to launch electron-rebuild and generate a specific installation for that. I had no problem in that though.

**Comment by zeke** [comment]
I found this demo repo which may help: https://github.com/bytheway/electron-sqlite3

See also https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md for more info on using native modules with Electron.

**Comment by pietrovismara** [comment]
Thank you zeke, i read from your links and tried an approach based on https://github.com/bytheway/electron-sqlite3, BUT:
I still have the same problem. 
If i compile with nodejs target version 6.* i get the module version 48, if i compile with target version 7.* i get module version 51.
But electron forked processes needs module version 50!! This is driving me crazy litterally.
![image](https://cloud.githubusercontent.com/assets/9806520/19925951/779bc33a-a0f2-11e6-82f0-667fdb309f6a.png)

**Comment by MarshallOfSound** [comment]
You need to read the second link that @zeke posted.  Basically you need to use `electron-rebuild` and rebuild modules of Electrons node version not your systems.

**Comment by pietrovismara** [comment]
I read it many times, but i don't see how it could help.
Launching electron-rebuild just generates the `node_modules/sqlite3/lib/binding/electron-v1.4-linux-x64` module, which is useless for me since it is used only if you require sqlite3 in the main process of electron.
When, from the electron main process, i fork a process which requires sqlite3, it searches instead for `node_modules/sqlite3/lib/binding/node-v50-linux-x64/`.
Am i missing something @MarshallOfSound ?

**Comment by MarshallOfSound** [comment]
@pietrovismara Yes 👍 

You need to use the pre gyp fix argument with `electron-rebuild` as sqlite uses `pre-gyp`.  Run `electron-rebuild --help` for a list of options.

**Comment by pietrovismara** [comment]
You're right! 
Using `electron-rebuild -p` generated both electron and node-v50 modules.
Thank you for your time and patience @MarshallOfSound @zeke

**Comment by zeke** [comment]
Glad you worked it out @pietrovismara. Can you share the full commands you're using, for the sake of others who may encounter this same problem?

**Comment by pietrovismara** [comment]
Of course! Sorry if i didn't explicitly but the operation is pretty straightforward:
```
npm install sqlite3
npm install electron-rebuild
./node_modules/.bin/electron-rebuild -p
```
As `electron-rebuild --help` explains:
```
  -p, --pre-gyp-fix            Enable the ugly (and hopefully not needed soon
                               enough) node-pre-gyp path fixer

```

[More info about the node-pre-gyp fix](https://github.com/electron/electron-rebuild#node-pre-gyp-workaround)

**Comment by evshiron** [comment]
I encountered this issue recently, and the `--pre-gyp-fix` option had gone.
I solved this issue by copying `electron-v1.4-linux-x64` to `node-v50-linux-x64`, which worked pretty well.

Hope it helps.

**Comment by Sindcs** [comment]
i have solved this problem,and use sqlite3 in development evironment sucessfully, but when i use electron-package pack the app,i get the error 'can't find module 'sqlite3'” ,did anyone met this problems?

**Comment by pietrovismara** [comment]
@evshiron  Almost 2 years later, I am back at using electron with sqlite3 in a different app. The problem for which i originally opened this issue is still here, plus the fix using the option --pre-gyp-fix is gone, as you noticed. 

How broken is this ecosystem that in 2 years could only make the problem worse?

Your fix works though even if it's a hack. Thanks.
