### ISSUE TITLE
remote debugging port only works the first time

### ISSUE THREAD

**Issue by sandover** [electron/electron#7842]
* Electron version: 1.4.5
* Operating system: macOS 10.12.1

I am enabling the remote debugging port by calling (e.g.)

`electron.app.commandLine.appendSwitch('remote-debugging-port', 9222)`

1. The first time I run my application, and then open a Chrome window and connect to `http://localhost:9222`, it acts as expected.  I can use the remote debugger.
2. Run my app again (unchanged), and attempt to connect to the remote debugger again, I see "waiting for localhost" forever.

If I try a different port (e.g. 9223), this again works the first time.  The second and subsequent times, it doesn't work.

If I reboot my laptop, all ports are reset and can be used again (once).

**Comment by MarshallOfSound** [comment]
@sandover How are you terminating your application.  Smoothly or forcefully?  Struggling to repro

**Comment by sandover** [comment]
Good question.

It looks lke`win.close();` from the renderer side

**Comment by sandover** [comment]
If I do any of these:

- control-C from the terminal where I started the app
- use the mouse to select "quit" from the application's own menu
- use the mouse to click the main application window's close box 

... then I can't repro either.

**Comment by zcbenz** [comment]
It seems that you didn't actually quit the first instance of your app, you just closed all its windows.

If this is not the cause, please provide a reproducible example and I'll reopen.

**Comment by sandover** [comment]
No, the application icon disappeared from the Dock, my Terminal prompt (from which I'd started the instance) resumed, etc.  There was every evidence that the application was terminated. 

Under electron 1.4.7, I can't repro, so happy to leave this ticket closed.  But -- is there a more official way for the renderer process to ask for the app to quit than closing all its windows?

**Comment by MarshallOfSound** [comment]
@sandover `remote.app.quit()`
