### ISSUE TITLE
Printing needs more options

### ISSUE THREAD

**Issue by pablooneto** [electron/electron#7849]
* Electron version: 1.4.5
* Operating system: All

1- There are only 2 options when it comes to print: silent and printBackground, there are plenty more options, like margins, copies, etc in the print window (Ctrl+P), that could be sent using _webContents.print()_ 

2- Access to print queue, to know if the printer is printing

**Comment by baconface** [comment]
You can have a lot of control of the document with CSS using [@page](https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/).

For copies you could just loop or repeat the print function to send it as multiple jobs.

**Comment by zcbenz** [comment]
To summary, the things we need to add for better printing support:

* New options: 
  * [ ] Select printer for printing
  * [ ] Header and footer
  * [ ] Copies
  * [ ] Other things from the print dialog
* New APIs:
  * [ ] List available printers
  * [ ] Access to print queue

**Comment by ykou** [comment]
+1

**Comment by pablooneto** [comment]
A callback when printing is done could be nice, but I think this are the minimum options necessary to develop something that actually need to print stuff. 
About the margins, I was talking about Chromium printing options, not content margins

**Comment by startupfoundry** [comment]
Silent printing also doesn't let you select a printer. It just goes to the default printer (as seen here) --> https://github.com/electron/electron/issues/5572

**Comment by zeke** [comment]
The [electron-printer](https://github.com/marcopiraccini/electron-printer) package might be helpful.

**Comment by renaesop** [comment]
#8442 may helps

**Comment by SinghSatyam** [comment]
How do I pass custom margin parameter for marginsType: 4?

**Comment by destan** [comment]
> How do I pass custom margin parameter for marginsType: 4?

currently you can't. see:

* https://github.com/electron/electron/issues/8138
* https://electron.atom.io/docs/api/web-contents/#contentsprinttopdfoptions-callback

**Comment by timfish** [comment]
In electron@1.6.11, `@page {size: landscape}` does not force printing into landscape orientation. It would be good if the options included `landscape: boolean` like in pdf generation.

**Comment by DTeuchert** [comment]
Do you have any release plans for integrating these options in `webContents.print` (#9868):
```
marginsType: 0,
landscape: true
```

as well the callback function for printing in combination with `silent:true`?

**Comment by jasonfutch** [comment]
Need a way to pass data directly to printer for RAW printing to thermal and label printers. The same functionality available in node-printer call printDirect()

**Comment by renaesop** [comment]
@jasonfutch you can use [node-print](https://github.com/tojocky/node-printer) instead.

**Comment by faviovelez** [comment]
Is it possible to print HTML documents with electron? 

A friend and I are developing a POS desktop app and need to print tickets with a generic (text only) printer. We generete tickets from dynamic HTML and use: `win.loadURL("data:text/html;charset=utf-8," + encodeURI(html))` to read it and then `win.webContents.print({silent: true)`  to print it. It works well on a normal printer but with a generic printer it just white paper. 

Printint HTML pages from browser works OK but not when using Electron. We are testing on Windows 10 x64, Electron 1.7.9.

**Comment by Xadren** [comment]
@renaesop is there anyway at all to pass data directly to the printer in electron? I've been trying for hours to get node-printer to work on my Windows machine, and I'm having absolutely no luck.

**Comment by hicaro** [comment]
Is there a way to detect when the user cancelled the job, after calling `window.webContent.print`?
What I mean is, the print dialog comes up, and then user does not click on `Print` but rather clicks on `Cancel`.

This is what I have so far:

```js
const printOptions = {
  silent: false,
  printBackground: true,
  deviceName: ''
};

window.webContents.print(printOptions, (success: boolean) => {
   if (!success) {
     // deal with the error
   }
 });

```

In the situation I described above, the callback is never triggered.

**Comment by abhijithcs** [comment]
@faviovelez Were you able to find any solution?

**Comment by baconbrad** [comment]
@abhijithcs @faviovelez In our POS we have an element (`#printer-content`) with `visibility: hidden;` as part of the style.  And then with CSS settings we can dial it in for the printer we are using. Now you can take HTML content and put them in `#printer-content`. (Be sure to use promises to ensure the data is ready.) It works both in Electron and a web browser. Since we print multiple documents at a time such as a customer and merchant receipt we had to write a print queue system. But you implement that in a wide range of ways.

Depending on the type of printer we load in a style sheet with the best settings for it. Because unfortunately CSS for one printer won't work for another completely different type.

Here is one for a regular A4 printer:
```css
@media print {
  @page {
    size: A4;
  }
  body * {
    visibility: hidden;
  }
  #printer-content, #printer-content * {
    visibility: visible;
  }
  #printer-content {
    position: absolute;
    left: 0;
    top: 0;
  }
}
```

Or a Star receipt printer:
```css
@media print {
  @page {
    margin: 0;
  }
  body * {
    visibility: hidden;
  }
  #printer-content, #printer-content * {
    visibility: visible;
  }
  #printer-content {
    position: absolute;
    left: 0;
    top: 0;
    width: 71mm
    min-width: 71mm;
    max-width: 71mm;
    font-size: 12px;
    font-family: "Courier New", Courier !IMPORTANT;
    font-weight: 700;
  }
}
```

**Comment by aknuds1** [comment]
I'm wondering about the same as @hicaro does, i.e. when the user cancels the print dialog there's no callback.

**Comment by seriouz** [comment]
@JorgeHawkins Yes but this is a problem with the printing drivers.

**Comment by seriouz** [comment]
@JorgeHawkins i still don't understand fully what you are talking about exactly. Can your print a normal website with the normal chrome browser print dialogue many times on your zebra without any issues?

**Comment by baconbrad** [comment]
@JorgeHawkins Could you introduce [page breaks](https://davidwalsh.name/css-page-breaks) to solve this? This theoretically would allow you to send one job but have it print on separate pages, or in this case tags.

**Comment by Hyperblaster** [comment]
If it helps, our workaround for the issue was to printToPDF multiple pages, the merge them together as a single PDF and then print from the command line using CUPS on Mac, and an external EXE File on Windows.

**Comment by csga5000** [comment]
@zcbenz Chromium supports headers and footers via some extra arguments.  They can be used in puppeteer (googles headless node package for chrome):

```
const puppeteer = require('puppeteer');

(async() => {
	const browser = await puppeteer.launch();
	const page = await browser.newPage();
	await page.goto('file:///C:/path/page.html');
	await page.pdf({
		path: 'pageoutput.pdf',
		format: 'A4',
		displayHeaderFooter: true,
		headerTemplate: '<div></div>',
		footerTemplate: 
			'<div style="font-size: 12px; width: 100%; text-align: center; font-style: italic; padding-bottom: 0.5in; font-family: serif;">'+
				'Page <span class="pageNumber"></span>'+
			'</div>',
		margin: {
			top: '0.5in',
			bottom: '1.5in',
			left: '1in',
			right: '1in',
		}
	});

	await browser.close();
})();
```

**Comment by selabie68** [comment]
Is there any support or plan of support for the "Scale" function?

**Comment by philipparndt** [comment]
@selabie68 you can achieve scaling by using css:
```css
@media print {
    html, body {
        zoom: 150%;
    }
}
```

nevertheless, a setting would be great.

**Comment by selabie68** [comment]
Thanks @philipparndt 

I will test this method. Does it have the same effect as the Chromium scale option?

![screenshot from 2018-12-17 09-01-09](https://user-images.githubusercontent.com/5601142/50059396-6295e600-01da-11e9-9f85-f14cb8866e1c.png)

**Comment by bhaktigohel** [comment]
hello @baconbrad,

can you please let me know if I can print **multiple copies** **_without looping_** for print counts?
Is there any option for set how much copies I want to print?

Thanks in advance.
