### ISSUE TITLE
Can't alt+tab into a window with skipTaskbar enabled

### ISSUE THREAD

**Issue by darsain** [electron/electron#7850]
* Electron version: 1.4.5
* Operating system: Win 10

When `skipTaskbar` is enabled, the window is impossible to alt+tab into, i.e. it's missing from the list of windows in the alt+tab menu.

Tried enabling `focusable` whether it won't have some effect, but it made no difference.

Is this intended? If it is, is it (or can you make it) configurable?

**Comment by MarshallOfSound** [comment]
I believe this is a technical limitation of how `skipTaskbar` works.  It's similar to how `app.dock.hide()` on macOS removes your app from the Command + Tab screen.  It's a UI decision that a few OS's make 👍
