### ISSUE TITLE
inside Webview, When I leave the page, I can't see the confirm  dialog

### ISSUE THREAD

**Issue by pouu69** [electron/electron#7853]
* Electron version: 1.4.3
* Operating system: OSX

inside Webview, When I leave the page, I can't see the confirm  dialog

how can see confirm dialog ?

**Comment by MarshallOfSound** [comment]
@pouu69 What do you mean?  Are you launching a `dialog` yourself and it isn't appearing?

**Comment by pouu69** [comment]
There is no confirm on the Web running within the Webview tag.

**Comment by pouu69** [comment]
like this

![](https://code-maven.com/img/chrome_confirm_reload.png)

**Comment by MarshallOfSound** [comment]
The `beforeunload` action is different in Electron 

> Usually you would want to use the beforeunload handler to decide whether the window should be closed, which will also be called when the window is reloaded. In Electron, returning an empty string or false would cancel the close. 

See #2301 to get similar behavior to Chrome
