### ISSUE TITLE
autoUpdater cannot find updates (Nuts Server)

### ISSUE THREAD

**Issue by MrBlenny** [electron/electron#7856]
* Electron version: 1.4.4
* Operating system: Win 10.1

I'm calling `checkForUpdates` on an electron app (compiled with electron builder):

```javascript
autoUpdater.setFeedURL('https://tonvai.com:2087/update/win32/0.0.1');
autoUpdater.checkForUpdates();
```

`https://tonvai.com:2087/update/win32/0.0.1` calls a nuts server running `v 3.1.1`. The response looks fine, it includes a working download link:
```javascript
{
url: "http://tonvai.com:2087/download/version/0.0.2/windows_32?filetype=zip",
name: "0.0.2",
notes: "",
pub_date: "2016-11-02T01:52:43.000Z"
}
```

Nonetheless, the autoupdater `'update-not-available'` event is being fired. No errors, and no `'update-downloaded'`.

Any idea what is going wrong?

**Comment by andymartinwork** [comment]
I had some trouble with doing updates with a server running on a certain port.
Have you tried putting it on a server on port 80?

**Comment by MrBlenny** [comment]
Nope, only that server running on :2087. 
Unfortunately it is not so easy for me to set it to port 80. Did you find SSL was necessary also?
Any idea why other ports won't work?

**Comment by andymartinwork** [comment]
SSL wasn't necessary (though obviously you'd want that in production). You can set up a port 80 server on your local machine if you need to test the issue. I don't know why it was necessary for me, but it seemed to fix the problem.

**Comment by MrBlenny** [comment]
Just tried `http://localhost/update/win32/0.0.1` locally. Still no luck 😢

**Comment by popod** [comment]
@MrBlenny Where is `autoUpdater.checkForUpdates();` in your code ? In an app event or ?

**Comment by MrBlenny** [comment]
It was in running in electron's main thread (triggered by a button which triggered the main-thread function through IPC).

I have switched to [Electron Simple Updater](https://github.com/megahertz/electron-simple-updater) - this works perfectly (and supported Linux AppImage Autoupdate) 😄

**Comment by kevinsawicki** [comment]
> The response looks fine, it includes a working download link:

The response you included is JSON and the OS you were reporting this on is Windows so I think that is the issue. The mac and windows auto updater server format is slightly different, on mac it expects a JSON response if their is an update or a `204` response when their is no update. The windows auto updater requests a `RELEASES` plain text file and then parses that for assets to download and update to.

> I have switched to Electron Simple Updater - this works perfectly (and supported Linux AppImage Autoupdate) 😄

I'm going to close this out then since `electron-simple-updater` is working for you and it uses the Electron `autoUpdater` module under the hood.
