### ISSUE TITLE
Rendering on bad monitors leads to strange colour differences

### ISSUE THREAD

**Issue by andymartinwork** [electron/electron#7858]
* Electron version: 1.3.8
* Operating system: OSX 10.12

I'm taking screenshots from Visual Studio Code 1.6.1, but I am raising the bug here because I noticed it in my own app too.

When you have a window with a certain background colour, and you load a webpage on top of that with the same colour, on _some_ monitors this leads to some very strange artifacts as shown below.

![screen shot 2016-11-03 at 12 10 57](https://cloud.githubusercontent.com/assets/1785253/19964026/9271a986-a1bf-11e6-89b0-80d9d46c4705.png)

I used Sip to detect what the colours were, and confirmed they are different, so there is most likely a problem with the rendering (possibly alpha?).

![screen shot 2016-11-03 at 12 14 43](https://cloud.githubusercontent.com/assets/1785253/19964027/95ef70de-a1bf-11e6-8de3-2accd21c6443.png)

![screen shot 2016-11-03 at 12 14 51](https://cloud.githubusercontent.com/assets/1785253/19964032/9ca9cf6e-a1bf-11e6-83a0-d38a7b6ad4b5.png)

When I set the web page colour to the colour on the main window reported by Sip, the colours were still different.

Note, this does not happen at all on my Macbook Pro laptop screen - but it is easily reproducible on my bad TF BenQ GL2450H.

**Comment by zcbenz** [comment]
This is a Chromium issue and will be fixed after Electron gets upgraded to Chrome 54.

Closing since there is already an issue tracking this.
