### ISSUE TITLE
Requiring systemPreferences causes globalShortcut to not work

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#7859]
* Electron version: 1.4.4
* Operating system: win10

Hi,
Example described [here](https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md) works with v1.4.0 but doesn't seem to work with v1.4.4 or v1.4.5.  Method `globalShortcut.isRegistered ` returns true, but the callback isn't called. 

Thanks!

**Comment by kevinsawicki** [comment]
I'm having trouble reproducing this using `1.4.5` on Windows 10. The example from the docs works for me:

<img width="283" alt="screen shot 2016-11-03 at 1 31 03 pm" src="https://cloud.githubusercontent.com/assets/671378/19984038/ccc91ab0-a1c9-11e6-97ef-0a2a4a6b6a70.png">

> but doesn't seem to work with v1.4.4 or v1.4.5

Would you be able to try other `1.4.x` releases and find the latest release that works for you?

**Comment by clusterberries** [comment]
I tried several times using different versions and shortcuts work with v1.4.3, but don't work with v1.4.5. Actually it seems like Electron define the shortcut (e.g. ctrl+x doesn't work in other applications when Electron app is running), but the callback isn't called.

**Comment by clusterberries** [comment]
Sorry, I closed by mistake

**Comment by MarshallOfSound** [comment]
Can you provide a minimal example that reproduces the issue.  I'm struggling to repro as well

**Comment by clusterberries** [comment]
I wrote simple app and... it works. I still don't understand what in v1.4.4 affects shortcuts in our app (cause with v1.4.3 it works), but the fact is that globalShortcut isn't broken on v1.4.5. I'm sorry to bother you :)

**Comment by clusterberries** [comment]
I reopen the issue, because I found something new: if I import systemPreferences module, shortcuts stop work. I can provide sample app if it is necessary.

**Comment by MarshallOfSound** [comment]
>  I can provide sample app if it is necessary.

Please do 👍

**Comment by MarshallOfSound** [comment]
I have a bad feeling this is related to https://github.com/electron/electron/pull/7173

/cc @zcbenz

**Comment by clusterberries** [comment]
Sure, you can use this https://github.com/clusterberries/electron-sample
Clone, run `npm i && npm start`. Press ctrl+x. Result: nothing in the console.
Comment 4th line in main.js `const { systemPreferences } = require('electron');`. Run `npm start`, try ctrl+x. Result is in the console.
Hope it will help.

**Comment by kevinsawicki** [comment]
@clusterberries thanks for the example, I can reproduce this now.

> I have a bad feeling this is related to #7173

@MarshallOfSound any thoughts on how to address this one?

**Comment by MarshallOfSound** [comment]
@kevinsawicki I'm assuming we need to somehow pass the window messages being recored here

https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_system_preferences_win.cc#L163

Through to the globalShortcut accelerator listener or something, never really looked into it too much.

**Comment by clusterberries** [comment]
Hi guys! Do you plan to fix this issue?

**Comment by MarshallOfSound** [comment]
> Hi guys! Do you plan to fix this issue?

My understanding of Window's window message is not extensive enough to understand why the window is absorbing all the messages.  Someone else might know what is going on 👍

**Comment by liusy182** [comment]
I noticed that if we do `const { systemPreferences } = require('electron');` after app's ready event then we are good. I think it has something to do with[ `SystemPreferences::Create(isolate)`](https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_system_preferences.cc#L91) where it can only happen after app is ready. Not sure about the exact reason through.

**Comment by miniak** [comment]
It does not only break `globalShortcut`, but also events on `screen` stop working as well.
