### ISSUE TITLE
remote global function return scrambled object

### ISSUE THREAD

**Issue by farfromrefug** [electron/electron#7860]
* Electron version: 1.4.3
* Operating system: Mac OSX 10.12

If i do this in main :
```
var db = {
  test:function(){return {a:1, b:'test'};}
}
win.db = db;
win.open();
```

then in renderer
```
console.log(getCurrentWindow().db.test());
```
the console prints 
```
{a:[Getter/Setter], b:[Getter/Setter]}
```

when i would expect
```
{a:1, b:'test'}
```
which means that the object returned by ```db.test``` is 'transformed'.

I suppose it is because the actual ```db.test``` call is made in main and then the result is sent to the renderer?

I am not sure it is a bug yet. If not how can i fix that? Is there a way to "transform" it back to a normal object?

**Comment by MarshallOfSound** [comment]
@farfromrefug It is not a bug.  If you logged `getCurrentWindow().db.test().a` it would return the correct value.

You see `Getter/Setter` because properties sent between processes are cast to syncronous get and set functions.  If you want it to look as you expect simply log

`Object.assign({}, getCurrentWindow().db.test())`

**Comment by farfromrefug** [comment]
@MarshallOfSound Shouldn't there be an option to send results as simple 'JSON' object?
I mean it's kind of big issue, i understand the fact that the object is that way because it is referenced both side. But in most case (like a simple math function), you absolutely don't need the result to be a remote object. And i am even worried about the fact that my "result objects" are referenced on both side.

One great feature (if not essential) would be to have a flag for ```setGlobal``` to only return "non remote objects".

I think this is an issue/missing feature because there is no real way around this.
