### ISSUE TITLE
Geolocation not returning any result

### ISSUE THREAD

**Issue by farfromrefug** [electron/electron#7861]
* Electron version: 1.4.3
* Operating system: OSX 10.12

i have a simple Geolocation class:
```typescript
class GeoUpdater {
    
    cachedPosition: Position
    running = false
    constructor() {
        process.env.GOOGLE_API_KEY = 'my api key'
    }
    getCurrentPosition = () => this.cachedPosition
    update = () => {
        if (!this.running) {
            this.running = true;
            logger.debug('GeoUpdater', 'update');
            navigator.geolocation.getCurrentPosition(function (position) {
                this.running = false;
                logger.debug('GeoUpdater', 'got geolocation', position);
                this.cachedPosition = position.coords;
            }, function error(error) {
                logger.debug('GeoUpdater', 'error', error);
                this.running = false;
            }, {
                    enableHighAccuracy: true,
                    // timeout: 10000,
                    maximumAge: 60 * 60 * 1000
                });
        }
    }
}
```

```getCurrentPosition``` nevers returns a result nor an error. The only return i see is when i set  a timeout. Then i get the TimeoutError.

Am i missing something?

**Comment by MarshallOfSound** [comment]
From the docs 

> Place the following code in your main process file, before opening any browser windows that will make geocoding requests:

You need to set that environment variable in the `main` process before launching the `BrowserWindow`

**Comment by farfromrefug** [comment]
@MarshallOfSound thanks! And sorry for missing that in the docs, but to be honest i can't "find" it in the doc [here](http://electron.atom.io/docs/)

**Comment by MarshallOfSound** [comment]
@farfromrefug It's in the environment variable section.

http://electron.atom.io/docs/api/environment-variables/#googleapikey

**Comment by farfromrefug** [comment]
@MarshallOfSound thanks, was looking for a geolocation section ...

**Comment by matthiasn** [comment]
Hey, wonder how this could help. Was the problem solved? I see the same behavior, and a Google geocoding service is not related to getting a result from `navigator.geolocation.getCurrentPosition`. Or am I missing something here? Thanks

**Comment by MarshallOfSound** [comment]
@matthiasn The geolocation API uses Google's services to get your location so you need an API key
