### ISSUE TITLE
Add a way of knowing if the resize event has been triggered manually

### ISSUE THREAD

**Issue by YannBertrand** [electron/electron#7870]
* Electron version: 1.4.4
* Operating system: macOS Sierra 10.12.1

This is a feature request.

When we add or remove a display, the `resize` event is triggered by Electron. Sometimes before, and sometimes after the `display-added` or `display-removed` events, there doesn't seem to be any logic there.
It would be great to know if the `resize` event has been triggered manually by the user or programatically.

**Comment by zcbenz** [comment]
I'm afraid there is no way to do this, the APIs provided by most platform do not tell how resize events are emitted.

**Comment by YannBertrand** [comment]
Is there another way to avoid this?

**Comment by zeke** [comment]
I don't have an answer for you, but I'm curious: Why does your application need to know what triggered the `resize` event? If you had this information, how would that change the behavior of your application?

**Comment by YannBertrand** [comment]
That's an excellent question, let me explain 😄 

I'd like to save the user window bounds preferences, depending on which displays are connected. 

Here is an exemple:

- I'm working with my laptop and another display, my window is on the display that I prefer, at a set position and size
- I disconnect one display, the window resize and move to my preferred bounds for this config
- I plug back my screen when getting back from my meeting, it should get back to the first config

Hope that's clear 🤔

**Comment by singhshashi** [comment]
@yannbertrand Were you able to find a solution for this?

**Comment by yannbertrand** [comment]
Nope 😔
