### ISSUE TITLE
Preload script is not executed with newer electron versions.

### ISSUE THREAD

**Issue by akels** [electron/electron#7871]
Hello,

yesterday I started to learn javascript and electron with a target to add menu item which executes some command as argument taking a value from web page. Since I found [app](https://github.com/safl/electron-spotify) which does these things I started to learn from It. My issue is that for electron version larger than v0.37.0 my preload script does not gets executed.

I add to `main.js` prelaod script in this way
```
   mainWindow = new BrowserWindow({             // Instantiate the browser window.
        width: 1024,
        height: 768,
        preload: __dirname+'/preload.js'
    }); 
```
where in `preload.js` I simply add
```
console.log('preloading')
```
Is it a bug or I should load `preload.js` differently now?
 
* Electron version: v1.4.5 and v0.37.0
* Operating system: Ubuntu 16.04

**Comment by kevinsawicki** [comment]
The `preload` attribute on the top-level options object was deprecated pre-Electron 1.0 and removed from the 1.0 API.

It should now be set on the nested `webPreferences` object:

```js
 mainWindow = new BrowserWindow({             // Instantiate the browser window.
  width: 1024,
  height: 768,
  webPreferences: {
    preload: __dirname+'/preload.js'
  }
}); 
```

See http://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions for more details.

**Comment by akels** [comment]
Disappointing that I did not saw error message for deprecated feature :/
