### ISSUE TITLE
Input lag in text fields or in DevTool console

### ISSUE THREAD

**Issue by rottenberry** [electron/electron#7872]
The lag is in every electron app I start, even in "electron-quick-start". Although Chrome browser works fine, and other browsers too (FireFox, Opera).
* Electron version: 1.4.5
* Operating system: Windows 10

**Comment by deepak1556** [comment]
https://github.com/electron/electron/issues/6759 reports same issue. Can you verify if the problem exists after [disabling hardware acceleration](https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration) ? Similar issues in chromium had success by disabling hardware acceleration.

**Comment by rottenberry** [comment]
I disabled hardware acceleration, and now it seems working fine. But what one is supposed to do if he needs that acceleration? May be for WebGL things. Will it be still work after disabling?
