### ISSUE TITLE
will-navigate can't be prevented in child windows

### ISSUE THREAD

**Issue by callodacity** [electron/electron#7873]
I couldn't find any other issues that described this exact bug, so forgive me if I missed one!

Calling `event.preventDefault()` from within the `will-navigate` event doesn't work if the `BrowserWindow` has been created by another `BrowserWindow`.

I set up a reproducible repo to better explain this issue; https://github.com/callodacity/electron-will-navigate. Look in the `renderer.js` file.
It will open two windows, clicking on the link in the `childWindow` will cause it to navigate (not what we want, since we've called `event.preventDefault()`).

* Electron version: `1.4.1` - `1.4.5`
* Operating system: `Windows 10` and `macOS`

**Comment by deepak1556** [comment]
In your example the `will-navigate` event is handled in the render process, where `event.preventDefault` is not supported yet. You need to handle the event in the main process.
