### ISSUE TITLE
IPC converts undefined to null

### ISSUE THREAD

**Issue by Luminess** [electron/electron#7874]
* Electron version: 1.4.5
* Operating system: Windows 10

Tested by sending `undefined` from a renderer process to main.

This will cause issues with using ES6 default parameters with IPC event listener functions.

Example:

```javascript
let mainWindow = new BrowserWindow({ width: 1366, height: 768 })

const handleWindowResize = (event, width = mainWindow.getSize()[0], height = mainWindow.getSize()[1]) => {
  console.log(width, height)
  mainWindow.setSize(width, height)
}

ipcMain.on('window-resize', handleWindowResize)

ipcRenderer.send('window-resize', 300) // OK
// console.log output -> 300, 768

ipcRenderer.send('window-resize', undefined, 300) // TypeError
// console.log output -> null, 300

ipcRenderer.send('window-resize', 300, undefined) // TypeError
// console.log output -> 300, null

handleWindowResize(undefined, undefined, undefined) // OK
// console.log output -> 1366, 768

handleWindowResize(undefined, null, null) // TypeError
// console.log output -> null, null
```

**Comment by MarshallOfSound** [comment]
I believe this is a side-effect of how JSON stringification operates with arrays.

For example run this in Chrome

```js
JSON.parse(JSON.stringify([1, 2, undefined, 3]))
```

You will see

```js
[1, 2, null, 3]
```

I don't think there is much we can do to change this behavior

**Comment by Luminess** [comment]
Didn't know that messages were passed between processes using JSON. JSON doesn't support `undefined` values, only `null`.

Is it feasible to allow us to set an arbitrary value as a placeholder for `undefined` in the JSON IPC messages?

**Comment by MarshallOfSound** [comment]
@Luminess It is possible but it is something you would have to do yourself 👍 I don't think we can implement it in a standard way that wouldn't break existing things 👍
