### ISSUE TITLE
Opentok implementation within Electron crashes the app.

### ISSUE THREAD

**Issue by jocean4** [electron/electron#7877]
* Electron version: v1.4.3
* Operating system: Mac

Hi, 

Thank you for reading this. I'd like to get feedback on a bug that crashes our desktop app, built with Electron and using Opentok. 

When Opentok initiates the video connection, the desktop app crashes. When Opentok was disabled, the desktop app stopped crashing. I've uploaded the crash report and console errors. 

I'd like to put out a bounty for $100 if this can get fixed by the weekend. Please let me know what other details you might need. Thank you. 

James

[Podium App Crash Report1.pdf](https://github.com/electron/electron/files/572364/Podium.App.Crash.Report1.pdf)
![screen shot 2016-09-21 at 9 37 18 pm](https://cloud.githubusercontent.com/assets/17887560/20017775/71ee9476-a29b-11e6-96aa-f9707b6d6b19.png)
![screen shot 2016-09-21 at 10 15 42 pm](https://cloud.githubusercontent.com/assets/17887560/20017776/733e5b36-a29b-11e6-967b-251351f5227a.png)

**Comment by kevinsawicki** [comment]
> Thread	11	Crashed::	Chrome_IOThread

Are you able to try this again Electron 1.4.5? There have been some recent crash fixes.
