### ISSUE TITLE
will-finish-launching not always fired on Windows

### ISSUE THREAD

**Issue by popod** [electron/electron#7879]
* Electron version: 1.4.5
* Operating system: windows

Seems that "will-finish-launching" event will not always been fired on Windows. I do a simple init on this event and it is not always executing..

Anyone has the same issue ?

**Comment by zeke** [comment]
Please provide a minimal app that reproduces this problem.

**Comment by popod** [comment]
I don't know what is exactly the problem.

I found that on Windows 10, the first time I start my app (after install it from nsis .exe built with electron-builder) my functions that are in "will-finish-launching" are not called.

If I move them on the "ready" event, this works..

I hope this help..

**Comment by zeke** [comment]
> nsis .exe built with electron-builder

I would suggest [opening an issue on electron-builder](https://github.com/electron-userland/electron-builder/issues/new) and referencing this issue from there.

If you're able reproduce this error scenario using a fork of electron-quick-start or similar, it would be very helpful for debugging.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
