### ISSUE TITLE
Cursor position is messed up inside a WebView on high DPI displays

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#7882]
* Electron version: `1.4.5`
* Operating system: Windows

### Expected behavior

Cursor should act normally

### Actual behavior

Cursor "takes effect" in the wrong position.  It appears to be exactly offset by the DPI scale ratio.

See https://www.youtube.com/watch?v=HfmpdkQb82o&feature=youtu.be

### How to reproduce

Unfortunately I can't reproduce this even enabling DPI scaling on my machine (I might be doing something wrong but hey).  If you have a high DPI screen, just using a webview should reveal this problem.

**Comment by MarshallOfSound** [comment]
Possible related to #7362 (idrk)

**Comment by andymartinwork** [comment]
May be related to #7655

**Comment by MarshallOfSound** [comment]
Merging into #7655
