### ISSUE TITLE
Disabled menu items can be triggered with their accelerator

### ISSUE THREAD

**Issue by yishn** [electron/electron#7885]
* Electron version: v1.4.5
* Operating system: Windows 10

### Expected behavior

If disabled menu items have accelerators, they can be triggered using that accelerator. Since disabled menu items are not clickable, one would expect that they can't be triggered in any way.

### Actual behavior

You can trigger disabled menu items with accelerators by pressing the corresponding accelerator.

### How to reproduce

In the default app, just set the `enabled` property on the 'Toggle Developer Tools' menu item to `false`. Observe that by pressing 'Ctrl+Shift+I' we can still trigger the menu item.

**Comment by zeke** [comment]
Related: https://github.com/electron/electron/issues/7737

**Comment by kevinsawicki** [comment]
@yishn is this only happening for you for menu items with `role` attributes set on them?

**Comment by yishn** [comment]
No. It's also happening for the 'Toggle Developer Tools' menu item in the default app which doesn't have any `role`.

**Comment by kevinsawicki** [comment]
Fixed by #7962
