### ISSUE TITLE
能否对代码进行加密呢，譬如类似于nwjs的nwjc source.js core.bin加密方式？

### ISSUE THREAD

**Issue by guguji** [electron/electron#7886]
> nwjs使用V8 Snapshot 的方式来达到代码加密保护的目的，具体的方式是使用 /nwjs.exe 来运行 nwjc source.js core.bin命令，然后再index.html里使用require('nw.gui').Window.get().evalNWBin(null, './app/v0.0.1/core.bin');(注意这里的路径，是相对于nw.exe的位置)将代码引入到项目中

请问下electron有类似的方式吗？虽然可以打包成asar，但是asar文件可以直接查看，所以有更好的加密方式？谢谢~

**Comment by MarshallOfSound** [comment]
From what Google Translate indicates you are asking about.

No, Electron has no plans to implement source code protection at this time.  You can read up #3041 for a larger discussion on the issue.

**Comment by guguji** [comment]
Wow, your answer is very fast, I know, thank you.
