### ISSUE TITLE
inspect elemment in webview tag

### ISSUE THREAD

**Issue by htdangkhoa** [electron/electron#7887]
hi, i use webview tag in html file, and i have a problem, so how can i detect target to inspect element?

For example:
<webview src="http://github.com"/>

Thanks.

**Comment by enlight** [comment]
See #2285

**Comment by htdangkhoa** [comment]
sorry, i mean i use webview tag, example: when i right click on a button on website and open dev tools, and how to detect exactly i clicked on button tag?

**Comment by MarshallOfSound** [comment]
If you are talking about a standard mouse event you should have an `event.target` property

```js
document.addEventListener('click', (e) => {
  console.log(e.target);
});
```

**Comment by htdangkhoa** [comment]
@MarshallOfSound thanks, it worked. How to open devtools with the target just detected, the devtools auto select that target?

**Comment by MarshallOfSound** [comment]
@htdangkhoa 

http://electron.atom.io/docs/api/web-contents/#contentsinspectelementx-y

**Comment by htdangkhoa** [comment]
@MarshallOfSound how to get result form executeJavaScript()?

webview.executeJavaScript("document.addEventListener('contextmenu', (e) => {console.log(e.target)});", function(result){
                              console.log(result);
                            });

**Comment by MarshallOfSound** [comment]
@htdangkhoa Without being harsh.  Just read the docs, all I'm going to do is quote the docs or copy paste the examples from the docs.

Also:

GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by htdangkhoa** [comment]
@MarshallOfSound thanks
