### ISSUE TITLE
Add mechanism for bypassing DNS host resolver

### ISSUE THREAD

**Issue by gregnolle** [electron/electron#7890]
Currently it is possible to intercept DNS requests in the following ways:

* Add rules for mapping specific hostnames to IP addresses using the --host-resolver-rules command line switch.
 **Pros:** works for all resolutions, even those for Flash socket requests.
 **Cons:** requires mappings to be specified at startup time and cannot be changed without a restart of the application.
* Use a proxy server.
 **Pros:** allows for dynamic resolutions at connection time.
 **Cons:** doesn't work for all resolutions, particularly Flash socket requests that bypass the proxy configuration.

I would like to propose that a new callback mechanism is added that will allow one to intercept requests to Chrome's DNS resolver. My use-case here is the ability to dynamically resolve all resolutions, even those for Flash socket requests.

From my research, I understand Chrome has its own DNS resolver that detects the DNS server(s) to use from the operating system (or potentially uses Google's own server under certain circumstances?) and also reads the OS' hosts file and applies any host-resolver-rules specified in the command line. It's not clear to me how best to add an intercept at this level though. I'm happy to try and produce a PR for this if someone can give me some pointers.

**Comment by deepak1556** [comment]
You can create `AtomHostResolver` class that will behave like [net::MappedHostResolver](https://cs.chromium.org/chromium/src/net/dns/mapped_host_resolver.h?q=mapped_&sq=package:chromium&l=1) , and provide callback mechanism similar to `AtomCertVerifier`. Also need to provide a mechanism where [brightray](https://github.com/electron/brightray/blob/master/browser/url_request_context_getter.cc#L203) can accept custom host resolver from embedder. You can look at how `AtomCertVerifier` was worked out.

**Comment by diyism** [comment]
https://cs.chromium.org/chromium/src/net/dns/dns_config_service_posix.cc?l=502
... dns_config->nameservers.push_back(ipe);...
Maybe change this line to push back "127.0.0.1" or the dns server ip from "--dns-server"

**Comment by gregnolle** [comment]
Thanks both for your suggestions.

@diyism I like the idea of putting the lookup behind chromium's DNS cache as I believe your method would allow, but I would need to start a local DNS server for my use-case, which is not ideal. It's also not clear to me if there's a way of replacing/wrapping the DnsConfigService at runtime without modifying the Chromium code. Please correct me if I'm wrong here though.

I've got some way towards implementing a HostResolver hook as @deepak1556 suggests. My C++ skills are very rusty though and I've run into some pointer issues. I'll push my changes onto a branch later this weekend and maybe someone can see spot what's wrong.

**Comment by diyism** [comment]
In my opinion, modifying ns_config->nameservers.push_back(<get dns from command line arg --dns-server>) will enable us business app developers to use our company's DNS server to avoid using our users pollutted DNS. It's important not to use polluted DNS for business apps.

**Comment by diyism** [comment]
https://github.com/spark/firmware/issues/1219

**Comment by WildXBird** [comment]
It would be better to have a method to intercept DNS requests and return the IP specified by myself.

**Comment by MarshallOfSound** [comment]
With the rise of DNS-over-https I don't think this kind of feature makes as much sense as it might have years ago.

In particular the primary reasoning for supporting such a use case being flash not respecting proxy settings it no longer relevant due to flash being thankfully gone
