### ISSUE TITLE
Support native progress dialogs

### ISSUE THREAD

**Issue by popod** [electron/electron#7894]
* Electron version: 1.4.5
* Operating system: for Windows and macOS

Adding a `dialog.showProgressBox()` methode to display progress.

**Comment by zcbenz** [comment]
There is no native progress box, there are only native dialogs with custom progress bar controls. To have this we have to either provide a complete API for creating native UI components, or provide an API to create a custom dialog with a progress bar in it.

The former is not on our plan, and the latter is simply impossible to satisfy all use cases. So I'm closing this as won't fix.

**Comment by popod** [comment]
Ok, thanks for reply ! I understand your point of view. But I think that your second option "provide an API to create a custom dialog with a progress bar in it." will be useful for many use cases...

For example, it would be nice to display a progress dialog when the app is searching for update, or when it wait for a connexion, ... All this stuff shows how useful could be this new API ;)

**Comment by JohnWeisz** [comment]
@zcbenz 

 > The former is not on our plan, and the latter *[provide an API to create a custom dialog with a progress bar in it]* is simply impossible to satisfy all use cases. So I'm closing this as won't fix.

With all due respect, so is having a chrome without configurable attributes, such as color. Sure, you can roll with your own chrome using a renderer process, but the same goes for a progress bar: native progress dialog if it fits your needs, roll with your own if not.

**Comment by sqwk** [comment]
I would also love to see this, but understand that it might not be a top priority.

Has anyone got a repo showing a known workaround to make a "manual" progressbar window look as native as possible?
