### ISSUE TITLE
app.disableHardwareAcceleration() fails on Ubuntu

### ISSUE THREAD

**Issue by ignjat** [electron/electron#7896]
* Electron version: 1.4.5
* Operating system: Ubuntu 16.04.1

### Expected behavior
app.disableHardwareAcceleration() should disable GPU acceleration.

### Actual behavior
app.disableHardwareAcceleration() fails with Error: app.disableHardwareAcceleration() can only be called before app is ready although the call was made as soon as electron is available (long before appReady callback).

### How to reproduce
It happens 100% of the time for me.

**Comment by kevinsawicki** [comment]
Can you include a small sample app that reproduces this for you? I tried with the following and it did not throw an error:

```
const {app} = require('electron')

app.disableHardwareAcceleration

app.on('ready', () => {
  console.log('app ready')
})
```

**Comment by ignjat** [comment]
The same code results in error in my environment.

**Comment by kevinsawicki** [comment]
> The same code results in error in my environment.

How are you running it? This is how I ran it on Ubuntu 16.04 and didn't see the issue

- Copy file to `test.js`
- Download Electron via `npm install electron@1.4.5`
- Run `electron test.js`
- See `app ready` on the console output

**Comment by ignjat** [comment]
Ok, figured it out. Standalone this works but when I put it in my script it didn't. Figured out there's an another piece of code that runs prior to it so app is ready before it reaches my script.
