### ISSUE TITLE
Strange fs async lock issue.

### ISSUE THREAD

**Issue by mifi** [electron/electron#7899]
* Electron version: Tried both 1.3.6 and 1.4.5

* Operating system: Windows 8.1 running inside VirtualBox 5.0.28

### Expected behavior

Async calls to fs-module (on local files) should call their callback within a reasonable amount of time.

### Actual behavior

Async calls to fs-module (on local files) freeze for an indefinite time.
Sync calls work fine, example: require('fs').statSync('C:/') returns immediately and consistently with the response.

### How to reproduce

1. Download plain electron zip from releases for windows (x64)
2. Start electron.exe
3. Open developer tools: Ctrl+shift+I
4. type: require("fs").stat("C:/", (err, stat) => console.log(stat));

I also tried replacing console.log() with alert(), same problem. Also it's the same problem on every file, not just C:/. Also tried other methods than stat, like fs.open().

If I run the snipped (step 4) many times, nothing happens. Then if I click a link in the sample electron page (Like "Docs" or "Repository"), all the callbacks that have queued up fire immediately. (almost like some lock got released.)

I tried the same in plain node.js and no problems.

**Comment by MarshallOfSound** [comment]
@mifi Which version of node.js did you try.  Can you test with version `6.5.0`.

Also can you reproduce if you change your code to be:

```js
require("original-fs").stat("C:/", (err, stat) => console.log(stat));
```

I am struggling to reproduce this on my W10 or W7 machines (don't have a W8 VM anymore #ripharddrive2016)

**Comment by mifi** [comment]
Tried with node 6.5.0 too, no problems.
electron with original-fs, same problem.
I'll try on windows 8 non VM later

**Comment by mifi** [comment]
I tried on windows 8.1 on another computer (non-vm) and there are no problems, so I guess this is related to VMs/virtualbox or just something wrong with my installation.

**Comment by mifi** [comment]
I tried on a different Windows 8.1 installation running under VirtualBox on a different host computer with a different OS (Linux instead of MacOS), and it has the same problem. So at least it's reproducable under Virtualbox

**Comment by kevinsawicki** [comment]
> Then if I click a link in the sample electron page (Like "Docs" or "Repository"), all the callbacks that have queued up fire immediately. (almost like some lock got released.)

This sounds very familiar, I feel like this has come up in the past in VMs where the event loop gets stalled somehow.

**Comment by zcbenz** [comment]
A similar issue is #5186. I'm afraid this is more an issue of Virtualbox than Electron, and I'm closing this as won't fix.
