### ISSUE TITLE
Slow startup time (2 minutes!) on Windows

### ISSUE THREAD

**Issue by pistacchio** [electron/electron#7902]
Hi,
Downloading the latest version of Electron (1.4.5) for Windows, I experience an unacceptable startup time (around two minutes). I've tried both the 32 and the 64bit versions. I'm trying to run the default demo app, untouched.

 This happens on a specific computer, an HP Elite x2. The computer is brand new and quite performant.

System specs:
OS: Windows 10 Enterprise (version 1607)
CPU: Intel Core m5-6y54 CPU @ 1.10GHz
RAM: 8 GB

I don't think it's an hardware issue. On a much less performant Windows system it works all right. I've also tried running NW.js and it has the same problem. Visual Studio Code (built on Electron) won't start. It seems there's something wrong (possibly software of configuration-wise) with the whole node/javascript environment but I don't know where to look for a solution.

Thanks

**Comment by MarshallOfSound** [comment]
@pistacchio Can you see if normal node.js has this issue.  I.e. Attempt to launch the node CLI 👍

**Comment by pistacchio** [comment]
@MarshallOfSound Hi, thanks for your replay. Yes, I've tried launching the node CLI. It is not as slow as two minutes it takes for Electron to run, but still slower than I would expect (~16 seconds). Other apps (Notepad++, Edge, Mail) start up almost immediatly.

**Comment by nikola** [comment]
@pistacchio Intel's datasheet indicates that your CPU has a very low TDP of 4.5W, i.e. your CPU will throttle when exposed to excessive CPU usage. The 1.10 GHz rating obscures the fact that this is a tablet-grade CPU. I have seen similar behavior from that range of Intel CPUs when starting up projects built on some variation of Chromium, in most cases related to initial decompression of resources.

**Comment by zcbenz** [comment]
I'm closing this since it seems to be a problem of slow machine.
