### ISSUE TITLE
Error: Module version mismatch. Expected 50, got 51 with LevelDB

### ISSUE THREAD

**Issue by tzvetelin-vassilev** [electron/electron#7904]
LevelUPError: Failed to require LevelDOWN (Module version mismatch. Expected 50, got 51.).

Have tried to rebuild with:
./node_modules/.bin/electron-rebuild -f -l -p -v=1.4.3 -w=leveldown

have tried with different versions. My environment:

Electron version: 1.4.5
Operating system: OSX El Capitan 10.11.6
npm: 3.10.8
node: v7.0.0

**Comment by MarshallOfSound** [comment]
See https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

Try some of the other methods and pay attention to the reference to pre gyp workarounds.

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#modules-that-rely-on-node-pre-gyp

Lots of people have reported success with `--build-from-source` on `node-gyp`

Closing out as it isn't really an issue with Electron 👍

**Comment by tzvetelin-vassilev** [comment]
I have try all of this. I have noticed this:
https://nodejs.org/en/download/releases/ 
There is not exist node with NODE_VERSION (I assume this is abi) with version 50.
So this looks like Electron issue.

**Comment by MarshallOfSound** [comment]
> So this looks like Electron issue.

Electron uses different ABI versions to Node.JS as they are built with different V8 targets.  The version number is correct.

**Comment by tzvetelin-vassilev** [comment]
Well, I'm little confused. First number is electron ABI version. Second number is node ABI. Building process is different for electron, it tells somehow to the library to use electron ABI may be? This error shows that the library still try to use node ABI may be. I changed -- target parameter a lot of times and the result is the same. Is there version of electron with ABI 48. If there is I hope this will resolve my problem. In my testcase I have installed only electron and leveldb.

**Comment by tzvetelin-vassilev** [comment]
solution found with:

export npm_config_abi=50
node 7.1.0
npm 4.0.2

Hurray !!!

**Comment by swampthang** [comment]
> solution found with:
> 
> export npm_config_abi=50
> node 7.1.0
> npm 4.0.2

Where did you add this? I'm having a similar issue. 
```Uncaught Error: Module version mismatch. Expected 50, got 53.```

Able to run using npm start. But, package-manager package doesn't work.
