### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by paul321** [electron/electron#7905]
* Electron version: 1.4.5
* Operating system: Windows

We are using node-fetch to make some requests to a website and login automatically but we get the following error thrown in the app, here is a screenshot 
![unnamed](https://cloud.githubusercontent.com/assets/555502/20107400/1c59f08e-a5e1-11e6-8716-c609976802d6.jpg)

Any ideas?

**Comment by kevinsawicki** [comment]
> Any ideas?

Not sure, are you able to provide a sample app that reproduces the issue?

**Comment by paul321** [comment]
Not really, just one of our users reported it on win 7 and we coudn't
reproduce it

**Comment by kevinsawicki** [comment]
@paul321 Electron recently upgraded node and Chrome versions, have you seen this happen on 1.6.0?

**Comment by paul321** [comment]
The problem was changing the MacOS certificate, after we change it Electron
/ Squrrel refuse to update the app on MacOS so we don't know if it's fixex

On Feb 9, 2017 11:26 PM, "Kevin Sawicki" <notifications@github.com> wrote:

@paul321 <https://github.com/paul321> Electron recently upgraded node and
Chrome versions, have you seen this happen on 1.6.0?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/electron/electron/issues/7905#issuecomment-278778400>,
or mute the thread

**Comment by kevinsawicki** [comment]
@paul321 is this something you'll be able to look into further to provide more details or should we close this out? Right now there isn't really enough information here to make progress on.

**Comment by paul321** [comment]
I think you should close it, i will report it again if it happens
