### ISSUE TITLE
When opening a window, closing it, and reopening it old IPC listeners stay intact

### ISSUE THREAD

**Issue by reense** [electron/electron#7913]
What happens?
When you open a BrowserWindow, close it, and open it again, ipc's do not get destroyed and send twice. 
When you close the BrowserWindow two times, and then re-open the same one, it does the same thing three times. 

* Electron version: 1.4.5
* Operating system:  OS X 10.12.1 / Windows 10

### Expected behavior
When i re-open the same window, events should not fire twice.

### Actual behavior
The window fires ipc events twice which causes the alert box to show twice.

### How to reproduce
modal.html
```html
<style>
body {
  font-family: system, -apple-system, '.SFNSText-Regular', 'SF UI Text', 'Lucida Grande', 'Segoe UI', Ubuntu, Cantarell, sans-serif;
  color: #fff;
  background-color: #8aba87;
  text-align: center;
  font-size: 40px;
}

h2 {
  padding: 0;
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

#close {
  color: white;
  opacity: 0.7;
  position: absolute;
  bottom: 20px;
  left: 50%;
  transform: translateX(-50%);
  font-size: 12px;
  text-decoration: none;
}

</style>

<h2>Hello World!</h2>
<a id="close" href="javascript:window.close()">Close this Window</a>
<div id="test">Hello</div>

<script>
  const ipc = require('electron').ipcRenderer
  const asyncMsgBtn = document.getElementById('test');

  asyncMsgBtn.addEventListener('click', function () {
    ipc.send('test-message', 'ping')
  })

  ipc.on('test-reply', function (event, arg) {
    const message = "Asynchronous message reply: " + arg;
    alert(arg);
   
})
</script>
````
create_window.js
``` javascript
const BrowserWindow = require('electron').remote.BrowserWindow
const ipc = require('electron').remote.ipcMain
const path = require('path')

const newWindowBtn = document.getElementById('new-window')

newWindowBtn.addEventListener('click', function (event) {
	/**
	* Load the other file
	*/
  const modalPath = path.join('file://', __dirname, 'modal.html')
  let win = new BrowserWindow({ width: 400, height: 320 })
  win.on('close', function () { win = null })
  ipc.on('test-message', function (event, arg) {
    event.sender.send('test-reply', 'pong')
  })
  win.loadURL(modalPath)
  win.show()
})
```

**Comment by MarshallOfSound** [comment]
This is 100% expected.

Basically what you are doing is adding an event listener in the `main` process **from the renderer process**.  The `remote` module doesn't move the scope of the function call, it simply proxies the function call for you to the `main` process.  So when you add an event listener on `remote.ipcMain` you are effectively adding a listener in the main process which won't be removed like `ipcRenderer` ones would be when the `webContents` is deleted.

IMO you should **never** use `remote.ipcMain` as it just doesn't make sense, the whole point of the names is you use `ipcMain` in the main process and `ipcRenderer` in the renderer process
