### ISSUE TITLE
npm install electron appears to fail with error EINVAL

### ISSUE THREAD

**Issue by vp2177** [electron/electron#7919]
![electron-inst](https://cloud.githubusercontent.com/assets/451903/20158526/aa257bf8-a6d2-11e6-8f9d-b32d18c2f49e.PNG)

* Electron version: 1.4.6
* Operating system: Windows 10 v1607, node 7.1.0

### Actual behavior

`npm install electron` (global `-g` install or local) fail. Other npm packages install successfully

```
> node install.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (C:\Users\Peter\Desktop\Workspace\node_modules\single-line-log\index.js:12:16)
    at process.<anonymous> (C:\Users\Peter\Desktop\Workspace\node_modules\single-line-log\index.js:17:29)
    at emitOne (events.js:101:20)
```

### How to reproduce

`npm install electron`

**Comment by seanchas116** [comment]
I experienced the same problem and I commented out that line (`node_modules\single-line-log\index.js:17`) then installation worked fine.

**Comment by leejh10003** [comment]
Same here. I use windows 10 v1607, node 7.1.0 and npm 3.10.9 comes with it on nvm. I disabled my antivirus and rebooted in safe mode with network. Started all shells(powershell, git bash, cmd) as administrator. Tried global and local installation. Still not working. Everytime, installation stuck at that throw er line in event.js file.

**Comment by Luminess** [comment]
I'm pretty sure this is due to a change in Node 7.1.0. I don't think I remember experiencing this on 7.0.0. It would be great if somebody with 7.0.0 can test if it works to double-check.

**Comment by Luminess** [comment]
Just tested myself. Node 7.0.0 works perfectly. 7.1.0 broke it.

**Comment by leejh10003** [comment]
Oh, it really is @Luminess. Thank you for your hint! Try it @vp2177!

**Comment by vp2177** [comment]
Indeed node 7.0.0 works.
Regression in node.

**Comment by mischah** [comment]
I filed an issue in the Node.js repo: https://github.com/nodejs/node/issues/9542

Please head over there in case you have any additional (and useful) information to share.
Thanks :octocat:

**Comment by AbrantesMar** [comment]
Hello, on my windows 10, I uninstalled node v 7.1.0 and reinstalled 6.9.1, and it worked normally ...

The error was:

Error: This socket is closed at WriteStream.Socket._writeGeneric (net.js:683:19) at WriteStream.Socket._write (net.js:734:8) at doWrite (_stream_writable.js:334:12) at writeOrBuffer (_stream_writable.js:320:5) at WriteStream.Writable.write (_stream_writable.js:247:11) at WriteStream.Socket.write (net.js:661:40) at WriteStream.stream.write (C:\Users\m.nunes.abrantes\Documents\Projeto\react_ative\testereact\node_modules\ansi\lib\newlines.js:36:21) at Console.warn (console.js:51:16) at process.on (internal/process/warning.js:21:17) at emitOne (events.js:96:13)

**Comment by olee** [comment]
Works again with latest node version, so I guess this can be closed.
