### ISSUE TITLE
JavaScript execution from ipcRenderer or setImmediate not recorded in devtool timeline

### ISSUE THREAD

**Issue by seanchas116** [electron/electron#7920]
* Electron version: 1.4.6
* Operating system: macOS Sierra

### Expected behavior

Callbacks executed from `ipcRenderer.on` or `setImmediate` will be recorded in devtool timeline

### Actual behavior

Callbacks on `ipcRenderer.on` or `setImmediate` not recorded
(Callbacks on `setTimeout` are recorded normally)

### How to reproduce

This is a simple example that do some heavy task in `ipcRenderer.on` callback:
https://github.com/seanchas116/electron-testings/tree/master/timeline-ipc

**Comment by seanchas116** [comment]
I tried executing something on other Node callbacks such as `fs.readFile` but nothing was recorded.

**Comment by zcbenz** [comment]
We probably need to call a blink API to make devtools recognize the call in timeline.

**Comment by kevinsawicki** [comment]
Fixed by #8159
