### ISSUE TITLE
how to controll subwindow display in the same desktop in macOS

### ISSUE THREAD

**Issue by fishbar** [electron/electron#7924]
* Electron version: 1.4.3
* Operating system:  osx 10.x

### what's now

when create an subwindow with fullscreen mode,  then call: 
```
subwindow.hide();

subwindow.show();
```

the `subwindow` came to the other desktop (since my mac have two desktops)

### Expected

the `subwindow` should  show in the same desktop

**Comment by fishbar** [comment]
the same Q: https://discuss.atom.io/t/window-show-hide-and-multiple-desktops-on-mac-os/31847

**Comment by MarshallOfSound** [comment]
Merging into #5362

^^ Issue for giving more control over workspaces
