### ISSUE TITLE
how to use Notification

### ISSUE THREAD

**Issue by wpf1994** [electron/electron#7926]
* Electron version: 1.3.4
* Operating system: windows

I hope to use Notification, such as: 
`var n = new Notification("Hi! wpf", {tag: 'wpf'});`
because of in order for windows7 to use
give me a suggest, thanks very much

**Comment by enlight** [comment]
GitHub issues are for features requests and bug reports, please direct any questions about using Electron to the [community](https://github.com/electron/electron#community).
