### ISSUE TITLE
Electron canvas rotated image jagged edges

### ISSUE THREAD

**Issue by pevgeniev** [electron/electron#7927]
I've an application which uses canvas to draw rotated images.
In Google Chrome the edge of the image is smoother than in Electron.
I've tried starting the Electron App with the flags --disable-gpu and --force-device-scale-factor = 1
but that didn't help.

* Electron version: 1.4.5
* Operating system: Windows 10 Pro
* Google Chrome version: 54.0.2840.71

### Expected behavior

Rendering images in canvas in Google Chrome and Electron should be of the same quality.

### Actual behavior

The rotated image has jagged edges when rendering in Electron

### Sample screenshots
![image](https://cloud.githubusercontent.com/assets/3244968/20174004/7b870cd6-a744-11e6-9e0f-a602ddcad521.png)

The upper part of the image is rendered in Electron, while the lower one is in Google Chrome.

Are there any command line flags I could use when trying to obtain the same rendering in both Electron and Google Chrome?

**Comment by MarshallOfSound** [comment]
@pevgeniev Electron `1.4.x` is based on Chromium 53. Can you test with that browser?

**Comment by pevgeniev** [comment]
You are right, Chrome ver. 53 has the same issue. Thanks for the help.
