### ISSUE TITLE
Feature request: dock icon overal

### ISSUE THREAD

**Issue by shir** [electron/electron#7928]
* Electron version: 1.4.4
* Operating system: Mac OS X 10.12.1

May be I missed something but looks like there is no API to add custom overlay on dock icon in Mac OS X. I know that natively it may be implement via [NSDockTile.contentView method](https://developer.apple.com/reference/appkit/nsdocktile/1525995-contentview).

Any suggestions?

**Comment by kevinsawicki** [comment]
So are you looking to change the icon completely or add a badge icon to the main icon?

You can call `app.dock.setIcon(icon)` to set the icon overall. Is that what you are looking for?

http://electron.atom.io/docs/api/app/#appdockseticonimage-macos

**Comment by shir** [comment]
@kevinsawicki I want to add overlay.

For example see this image https://i.ytimg.com/vi/LssouPS25zA/maxresdefault.jpg. There is Transmission icon (at the right of the dock) with overlay with download speed. I want some similar functionality.

I expect that API will allow to set some custom image or html (processed with web view) which will be applied over icon.

**Comment by kevinsawicki** [comment]
If you can build the image you want to change the dock icon to as a `Buffer` or `data:` URL then you can create a `NativeImage` from it and set that as the icon using `app.dock.setIcon(icon)`.

So I'm not sure anything needs to be added to Electron to accomplish this as long as you can dynamically generate the image you want to set on the dock.

You can also use `app.dock.setBadge()` to apply simple text decoration.

**Comment by shir** [comment]
@kevinsawicki when I though about it more and how it may be implemented I see that I may use current API. Thanks.
