### ISSUE TITLE
[Enhancement] Safe IPC Bus

### ISSUE THREAD

**Issue by MichaelVasseur** [electron/electron#7929]
Electron is designed to handle local "trusted" content provided by the application's developer.
The IPC offered by Electron allows the application to exchange informations between the main and the renderer processes. But, this IPC is also used internaly by Electron to handle some workflows related to its features (such popup windows, file loading, remoting,  etc..)
Ex:
```
ipcMain.on('ELECTRON_BROWSER_READ_FILE', function (event, file) {
  fs.readFile(file, (err, data) => {
    if (err) event.returnValue = {err: err.message}
    else event.returnValue = {data: data.toString()}
  })
})
```

As a result, when the IPC is made available, any JS code from an untrusted page could use Electron's internal commands to compromise the application and/or the machine.

Since the IPC mechanism is required by many applications, it would be helpful to have such mechanism but fully dedicated to the application. In others words, the current IPC is a technical pipe that should only be used by Electron itself and the trusted local container code, and the new IPC (an applicative pipe) would be dedicated to the application's workflows.

This feature would offer the following benefits :
- **Simple**: The API would be similar to ipcMain/ipcRenderer
- **Dedicated** : This IPC is not used by the container (Electron and trusted container code). Only the application will define the workflows handled with this IPC.
- **Secure** : The technical IPC can be completely hidden to the application code. The application IPC does not rely at all on the technical one.
- **Fast** : The implementation would relies on existing native Chromium IPC with JS binding
- **Configurable**: Activation could be controlled by command-line switch or BrowserWindow's option

**Comment by MarshallOfSound** [comment]
I feel as though if the user exposes the entire IPC module to a remote webpage through a preload script that is kind of their fault for not following the security guidelines not Electron's responsibility to fix.

https://github.com/electron/electron/blob/master/docs/tutorial/security.md

> If your application executes code from an online source, it is your responsibility to ensure that the code is not malicious.

If you need to give a remote app IPC abilities then you should provide hard coded send methods to avoid this security issue.  For instance:

```js
// preload.js
window.sendMessage = () => {
  ipcRenderer.send('thing');
};

// or this preload.js
const whitelist = ['cmd1', 'foo', 'bar'];
window.sendMessage = (msg) => {
  if (!whitelist.includes(msg)) return;
  ipcRenderer.send(msg);
}
```

**Comment by MichaelVasseur** [comment]
From our point of view, it would better to completely hide the ipcRenderer in the sandboxed renderer to enforce the security. So, we could not use it to build an application oriented API.

**Comment by MarshallOfSound** [comment]
@MichaelVasseur If you disable `nodeIntegration` on your `webPreferences` then no node modules are available so ipcRenderer (along with all other modules) won't be available.  I'm not sure I understand your use case where:

1. You need ipcRenderer
2. It needs to be injected globally (to cause this issue)

Those 2 things should never be the case and if they are you probably need to rethink what you're doing and / or use one of the ipcRenderer protection techniques I gave above.

**Comment by ahmedmohamedali** [comment]
@MarshallOfSound,  the workaround protection you have provided is fine in the simple case. It won't scale for projects with many preloads as the code will be repeated with the needed variation. The lookup code will also be executed by all renders and the performance could be impacted depending on the number of channels in the white list and the message rate. The enhancement proposed by @MichaelVasseur, solves the scalability and the performance issues. The rendere will access a safe and specialized module. The consumer will not need to validate the message as the handler will not process unknown channel. The addition for a new preload will not need the addition of the white list. 
According to the PR #6712, other node module are not available but  ipcRenderer can be exposed in the preload .The ipcSafeRenderer could be exposed in the same way. Disabled by default in the sandboxed renderer but enablable in the pre-load. This can be either done in this enhancement or as part of the work planned in the enhancement #6712 to expose more node.js module to sandboxed renderer.

**Comment by MarshallOfSound** [comment]
@ahmedmohamedali This is still IMO but I still don't see the need for another module / IPC bus to do something that IMO the implementer should be doing.

>  the workaround protection you have provided is fine in the simple case. It won't scale for projects with many preloads as the code will be repeated with the needed variation. he lookup code will also be executed by all renders and the performance could be impacted depending on the number of channels in the white list and the message rate.

So do the inverse?  Blacklist the Electron commands with something like.

```js
if (channel.startsWith('ELECTRON_INTERNAL')) return;
```

That is a constant time comparison that would add negligible time to the IPC message.

I also would like to raise the point I made above again.  What is the use-case where you are loading remote unverifiable content and **have** to inject the `ipcRenderer` module into the global scope.  Perhaps I am missing that context.

**Comment by ahmedmohamedali** [comment]
@MarshallOfSound We do not want to inject ipcRenderer in the global scope, this is already possible via preload. The module we want to inject is new module we want to contribute. This module will have safety requirements and will have the counter part of ipcMain in the master process. There will be a clear separation between framework ipc and the ipc for the user's logic. The goal is the communication between the renderers and the master to be more safe. As explained in this enhancement there is possibility to send electron command that can be harmful via ipcRenderer.The solution we need should be scalable, with no performance impact and standard in electron so other people can benefit from it.  I already explained the issue with white list and black list is even worst. We can blacklist all the current electron commands but there is no guarantee electron will not be enhanced in the future with new commands that introduce security issues.

**Comment by paulcbetts** [comment]
I think the solution here is to be able to mark certain webContents as "untrusted" up-front, and that built-in IPC calls will be mostly ignored. This is an issue because even if a developer doesn't directly expose IPC, they are probably _using_ IPC and it means that it's subject to clever JavaScript injection - i.e. any time you use a non-constant channel name, you have potential for people doing stuff to manipulate that name to send something else

**Comment by ahmedmohamedali** [comment]
@MarshallOfSound, @paulcbetts thanks both for your help here.
I like the idea to marke certain webContents as "untrusted".  Do we need to create a PR for this ?

**Comment by MarshallOfSound** [comment]
@ahmedmohamedali It looks good to me.

I think it's the kind of thing that would be best served as a third-party NPM module, maybe `electron-safe-ipc`.  Thoughts @paulcbetts ?

**Comment by ahmedmohamedali** [comment]
@MarshallOfSound, thanks for the review and your suggestion to publlish the solution as a third-party NPM. We will do it and reference back the link here.

**Comment by YurySolovyov** [comment]
> Chromium IPC with JS binding

I think Chrome team is in process of moving APIs to Mojo IPC, if that's not what you meant by "Chromium IPC"

**Comment by MichaelVasseur** [comment]
See https://github.com/MichaelVasseur/electron-ipc-bus.

**Comment by mattbajorek** [comment]
> @MarshallOfSound, @paulcbetts thanks for your feedback. I think we have found a solution that fixes the issues I mentioned in my comments above.
> Instead of using a white list or a black list we will route all the messages in a single channel 'ipc-app'.
> The actual user channel will be encapsulated in the message itself.
> 
> ```js
> //in preload.js
> window.sendMessage = (channel, ...args) => {
>    ipcRenderer.send('ipc-app', channel, args);
> }
> ```
> 
> ```js
> //in the main process
> const {ipcMain} = require('electron')
> ipcMain.on('ipc-app', (event, ...args) => {
> 
> //1- get the channel args[0] and the data from args.splice(0)
> //2- Call the application event handler for that channel.
> 
> })
> ```
> 
> * ```
>    There will be no possibility to run electron built-in handlers. 
>   ```
> * ```
>    The channel is pre-defined and fixed. There is no need to use a white list or a black list. 
>   ```
> * ```
>    The primary channel is passed as a constant. So, this removes the potential security risk mentioned by paulcbetts
>   ```
> 
> I kept the sample code above very simple to explain the idea but the real implementation will be be based on EventEmitter for the secondary channel to use the .on('xxx') syntax.
> 
> @MarshallOfSound , please provide you feedback on this solution. If you confirm the option I described above is removing the potential security issue described in this enhancement then we can close this issue.
> Thanks.

Args should have a spread operator when using ipcRenderer:
ipcRenderer.send('ipc-app', channel, ...args);

**Comment by YurySolovyov** [comment]
I think 1. electron-internal events and user events should never use the same ipc channel, and 2. electron channel should not be exposed to userland code period.

**Comment by Anrock** [comment]
> 2. electron channel should not be exposed to userland code period.
Pls no. Half my workarounds for electron bugs depend on this.

**Comment by MarshallOfSound** [comment]
Electron internal IPC and user-facing IPC have already been separated and you should see this in the `4.0.0-beta` series.  Gonna close this out as the user-facing IPC is now isolated / separate from Electron IPC

**Comment by Anrock** [comment]
Okay. Looks like i'm never updating then ¯\_(ツ)_/¯
