### ISSUE TITLE
BrowserWindow - transparent not working

### ISSUE THREAD

**Issue by thyrrestrup** [electron/electron#7930]
* Electron version: 1.4.6
* Operating system: Windows Embedded Standard - Service Pack 1

### Expected behavior

Window is transparent and shows content like on Windows 10 / Mac OS X.

### Actual behavior

Window does not show content.

### How to reproduce
`index.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <style>
      html, body {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
        overflow: hidden;
      }
      @keyframes fade {
        from {opacity: 0.0;}
        to {opacity: 1.0;}
      }
      #frame {
        width: 100%;
        height: 100%;
        opacity: 0.0;
        animation: fade 2s infinite alternate;
        background: #FF0000;
      }
    </style>
  </head>
  <body>
      <div id="frame"></div>
  </body>
</html>
```
`main.js`
```javascript
const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow

let mainWindow

function createWindow () {

  mainWindow = new BrowserWindow({
      frame: false,
      transparent: true
  })

  mainWindow.loadURL('file://' + __dirname + '/index.html')

  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
```

**Comment by zeke** [comment]
The above code works for me on macOS 10.11.6

Haven't tried it on Windows yet.

**Comment by thyrrestrup** [comment]
Yes it works perfectly fine om OSX and Win10 but not on Windows Embedded Standard - Service Pack 1 - Direct X 11

**Comment by zcbenz** [comment]
This is because Windows Embedded Standard does not support the transparent API we used in Electron, I suggest seeking help from Microsoft support.

**Comment by zeke** [comment]
Should it be noted in this docs that the `transparent` option is not supported on Windows Embedded Standard?

**Comment by thyrrestrup** [comment]
Thanks for clarifying.
Yes maybe a good idea to put it in the docs.

**Comment by madipor** [comment]
I have the same problem
Operating system: Windows Server 2008 R2 Enterprise
Electron version: 1.4.12

any idea?
