### ISSUE TITLE
Box-shadow in browser window doubled after some hover

### ISSUE THREAD

**Issue by pierrefourgeaud** [electron/electron#7932]
I would expect the box shadow to behave as in Chrome, especially when just hovering the button on the right (any button), you can see there is an additional shadow added (nothing in the code to trigger this kind of behavior). Also, the screenshot shows on the left chrome and on the right my `BrowserWindow` after for both hovering the STOP button.

[The ScreenShot](http://builds.airtame.com/files/notification.png)

* Electron version: 1.4.5
* Operating system: OSX 10.10.5

### Expected behavior

The box shadow should just stay the same.

### Actual behavior

On the side where my buttons are located, it looks like the shadow is doubled.

### How to reproduce

Open a `BrowserWindow` with {frame: false, width: 440, height: 120} and load this: [notification.zip](http://builds.airtame.com/files/notification.zip) .

**Comment by zcbenz** [comment]
This is a known issue with Chrome 53, and will be fixed after upgrading to Chrome 54.

I'm closing this since there is already an issue tracking the Chrome 54 upgrade.
