### ISSUE TITLE
Windows notifications display application user model id if `icon` is set

### ISSUE THREAD

**Issue by ccnokes** [electron/electron#7934]
* Electron version: 1.4.5
* Operating system: Windows 10

### Expected behavior

The notification should not display the app user model id because no user cares about that.

### Actual behavior

It displays it if `icon` is set. 😦 

### How to reproduce

On Windows 10, from a renderer process:

`new Notification('test', { body: 'i dont show app id' })`
`new Notification('test', { body: 'i do show app id', icon: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'' })`

![screen shot 2016-11-10 at 11 20 40 am](https://cloud.githubusercontent.com/assets/1610343/20188873/e8f943cc-a737-11e6-9735-a0dae4852ba0.png)
![screen shot 2016-11-10 at 11 20 56 am](https://cloud.githubusercontent.com/assets/1610343/20188874/e8fa6504-a737-11e6-904a-5a09a9e1aafa.png)

If anyone knows some magic workaround to get rid of it, let me know 😸

**Comment by MarshallOfSound** [comment]
I found the workaround for this was to have a shortcut to your app in the start menu

**Comment by ccnokes** [comment]
@MarshallOfSound oh, so is this expected then when running it via `electron-prebuilt` but NOT when it's compiled/distributed? 

I just tested it and I'm seeing the same behavior when it's got the shortcut on the desktop and start menu installed via squirrel windows. Let me know if I can provide any more info to help.

**Comment by MarshallOfSound** [comment]
Are you sure your shortcut has the correct metadata set?  AppUserModelId and such?

**Comment by ccnokes** [comment]
Yeah, I set it via `app.setAppUserModelId`. Looking at my code again, I realize that I call that in the `onReady` handler, not sure if it's supposed to be before. Inspecting the shortcut properties, everything looks normal to me....

**Comment by MarshallOfSound** [comment]
@ccnokes I meant does the shortcut have the correct appUserModelID.

And I've always set my appUserModelID before the `ready` event, might be worth shuffling that around 👍

**Comment by ccnokes** [comment]
Ok, I'll change that around.

Where/how do I inspect appUserModelID on the shortcut? 

I'm not seeing it in this thing:

![screen shot 2016-11-10 at 3 53 32 pm](https://cloud.githubusercontent.com/assets/1610343/20197663/e0dc0f28-a75d-11e6-9636-a9d8aaebe891.png)

**Comment by MarshallOfSound** [comment]
@ccnokes Yeah, windows doesn't show you it by default.  I used a technique similar to 

http://winaero.com/blog/how-to-show-more-details-for-shortcuts-in-windows-8-1-windows-8-and-windows-7/

To display the appUserModelID

**Comment by ccnokes** [comment]
I figured it out. It looks like Squirrel.Windows may automatically set the appUserModelID for you (pretty sure I read that somewhere, maybe @paulcbetts can elaborate). The appUserModelID that was getting set was not the same as what I was setting in my code. Once I made them match, my app's name was displayed instead of the appUserModelID.

**Comment by AmritaKSaha** [comment]
working on a Toast notification. I do not want to use the APPID from startup apps in my script. Instead will use a different Logo.  But the problem is that it displays the Application name, for eg: Windows Powershell is getting displayed in my Notification. Is there any possibility to hide the AppID or create one of my own>

**Comment by Igwizard2002** [comment]
How to add image infront of the notification title bar like app.userModelId in front of it I want to show icon
