### ISSUE TITLE
Electron is opening WebView process so long

### ISSUE THREAD

**Issue by Sential** [electron/electron#7935]
Hello, I'm making Internet browser. If I add new tab, the process electron.exe related to WebView starts after 4-5 seconds, and loads very simple HTML file. It is very important to me to load pages very fast in my browser. I see other browsers made in electron. They are also initializing very slow the same as my browser. 

Steps to reproduce the problem:
Just use tag `<webview>` and see what happens.

My computer has SSD so probably it is not a problem from my side.

**Comment by Sential** [comment]
Problem have been solved. Just turn off antivirus in my case Avast. Closing.

**Comment by TimNZ** [comment]
This is one of the reasons I haven't run AV for years.
