### ISSUE TITLE
Electron tray.displayBalloon()

### ISSUE THREAD

**Issue by yuritk** [electron/electron#7936]
Notifications appears, but at sometime, the function dont work again,
For example: those notifications appears just for the first minute. Later dont work

**Comment by zeke** [comment]
Please provide a minimal app that reproduces this problem.

**Comment by kevinsawicki** [comment]
I think this might be a duplicate of #5844, @yuritk can you check out https://github.com/electron/electron/issues/5844#issuecomment-251018364 and see if it resolves your issue?
