### ISSUE TITLE
Permission Denied when Deploying on AWS

### ISSUE THREAD

**Issue by QuentinDela** [electron/electron#7938]
Hello,

I am trying to run NightmareJS on Elastic Beanstalk and I keep having an issue with Electron.

Error: EACCES: permission denied, mkdir '/tmp/deployment/application/node_modules/electron/electron-tmp-download-2233-1478789913678'

Here are the full logs: https://gist.github.com/QuentinDela/49e824c5889e14e899eafbe850d23055

Would you have any ideas on how to fix this? Thanks,

* Electron version: 1.4.4
* Operating system: Linux

### Expected behavior
Electron installed with nightmareJS

### Actual behavior
Electron can't be installed

### How to reproduce
Deploy an app using nightmareJS on Elastic Beanstalk

**Comment by MarshallOfSound** [comment]
I mean, that looks like you don't have permission to access your own temp directory.  If you don't have write access to that I'm not sure there is much you can do.

I would suggest raising a bug over at `electron-download` and possibly making the tmpdir configurable.

https://github.com/electron-userland/electron-download/blob/master/lib/index.js#L153
