### ISSUE TITLE
<webview>'s .focus() method gives focus to all webviews in window

### ISSUE THREAD

**Issue by rhysd** [electron/electron#7939]
* Electron version: 1.4.6
* Operating system: OS X 10.11

### Expected behavior

`webview.focus()` Gives focus only to the method's receiver webview

### Actual behavior

`webview.focus()` gives focus to ALL webviews in the browser window

### How to reproduce

I created a test app to reproduce this.

https://gist.github.com/rhysd/bf8015c0ae8e58fcb63aad6b469550ca

Please copy all files to one directory and execute `electron .` in it. It opens the window which contains one button and two webviews with DevTools.

Then please click button and see the console. Button callback calls only one webview's `.focus()` method but both two webviews are given focus.

I took a screenshot:

![tmp](https://cloud.githubusercontent.com/assets/823277/20206890/ed65f0dc-a826-11e6-9082-81c689babcf4.gif)

**Comment by xywz** [comment]
Both listeners are attached to the same webview.

**Comment by rhysd** [comment]
@xywz 

Thank you so much, it was my fault. I'll investigate my app again where my app's problem comes from.
