### ISSUE TITLE
Simple way to track electron app usage ?

### ISSUE THREAD

**Issue by popod** [electron/electron#7941]
Is their a simple way (API, library) to track some app usage and to send reports to a server in Electron ?

Fore example, I would like to know something like that :
- How many times my app had been opened each days
- How long had it been opened
- ...

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

Look into the universal analytics package on NPM.  It integrates with Google Analytics which is free

**Comment by popod** [comment]
Thanks for reply !

Yes I know their is some solution with Google Analytics, but I think it would be interesting and useful to provide an basic "activity" API (which send customs datas to an url) well integrate with Electron. With options to automatically send one request on app start, app quit, app update, ...

What do you think about that ?

**Comment by MarshallOfSound** [comment]
I think Electron provides events for all the things you mentioned and any analytics you should implement yourself.

Electron provides high level API's so you can do whatever you want with them :+1:

**Comment by mengfoobar** [comment]
@popod try [NeutrinoMetrics](https://neutrinometrics.net), it's an analytics platform designed for integrating with Electron apps.

The companion [library](https://www.npmjs.com/package/electron-analytics) lets you send events in both main and renderer process. Should help you out. 

Just a heads up, I'm a contributor to this project.

**Comment by popod** [comment]
Thanks @mengfoobar, it seems that is exactly what I wanted !

**Comment by ViniciusAugusto** [comment]
Hi, @mengfoobar, the **NeutrinoMetrics** is still running? I can not access website ...
