### ISSUE TITLE
macOS drag and drop bug when using `titleBarStyle: 'hidden-inset`

### ISSUE THREAD

**Issue by petrbrzek** [electron/electron#7942]
* Electron version:  1.4.1
* Operating system: macOS

![](https://cldup.com/7SfM7Jzygp.gif)

The example shows an Electron bug when using `titleBarStyle: 'hidden-inset'` (it works correctly with different settings). 

```
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    titleBarStyle: 'hidden-inset',
  })
  ```

Drag and drop work only if a mouse position is within the red rectangle bounds. If it's above/below it doesn't work. Also if we release the mouse when we are out of the red rectangle bounds and move back to the red rectangle bounds you can still move the blue rectangles. If we comment out the ``titleBarStyle: 'hidden-inset'`` or change it to ``titleBarStyle: 'hidden'`` it's working as expected.

### How to reproduce

You can clone this repository https://github.com/petrbrzek/electron-dnd-bug.

**Comment by poiru** [comment]
This is related to #5723.

**Comment by kevinsawicki** [comment]
Merging into #5723

**Comment by jarek-foksa** [comment]
Please reopen this issue, after two years it is still present in Electron 3.0.x and #5723 is discussing a completely different bug (although it might have the same root cause).

**Comment by wangjianio** [comment]
`-webkit-app-region: drag;` not work when devtools is open. 
> v5.0.5
