### ISSUE TITLE
Detect if (flash)plugin crashed

### ISSUE THREAD

**Issue by TimvdEijnden** [electron/electron#7943]
* Electron version: 1.4.4
* Operating system: MacOS 10.11.6 / Windows 7, 8 & 10

### Expected behavior
In Chrome you get a page with a layout like this:
![screen shot 2016-11-11 at 15 37 35](https://cloud.githubusercontent.com/assets/951290/20218404/d0898142-a824-11e6-9da7-7fb2168a496a.png)

We'd like to catch the event when the Flash plugin crashes, so we can inform our users. Or reload the page so they won't have to restart the application.

### Actual behavior
In Electron you just get a blank page when visiting http://www.timwebdesign.nl/flash/crash.html

### How to reproduce

1. Create an app with flashplayer enabled
2. Create a BrowserWindow or WebView with this url: http://www.timwebdesign.nl/flash/crash.html
3. Wait 3 seconds.
4. The Plugin crashed.

**Comment by Quacky2200** [comment]
I think this plugin event handler should work as flash is a plugin [webContents event 'event-plugin-crashed'](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-plugin-crashed)

**Comment by MarshallOfSound** [comment]
I believe the event @Quacky2200 mentioned is what you are looking for 👍
