### ISSUE TITLE
Like this layout how to do?

### ISSUE THREAD

**Issue by lifetin** [electron/electron#7949]
Like this layout how to do?
Above I want to get a row of buttons, the following is the above button to click on the page to switch the results, I do not know how to layout? This is to generate multiple browser-window?
![55](https://cloud.githubusercontent.com/assets/10474968/20235952/44cde782-a8de-11e6-8e2a-de200c128659.png)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
