### ISSUE TITLE
Support for alt tray icon.

### ISSUE THREAD

**Issue by reggi** [electron/electron#795]
Hate to reference node webkit but... 

>  Tray.alticon
>  since v0.4.2
>  Get or Set the alternate (active) tray icon for Mac. It has no effects on Linux and Win.

On select highlight tray icon switches to alt icon (white).

https://github.com/rogerwang/node-webkit/wiki/Tray#trayalticon

**Comment by yorululu** [comment]
setPressedImage is not like alticon in nw.js

my macOS theme is light. when I change the wallpaper, the tray icon will change according the wallpaper color.
nw.js works.
but Tray.setPressedImage would not help.
