### ISSUE TITLE
[Windows] Bug with open file dialog with forward slash (`file_dialog::ShowOpenDialog`)

### ISSUE THREAD

**Issue by verysimplenick** [electron/electron#7954]
* Electron version: 1.4.6. [commit](https://github.com/electron/electron/commit/7cfe1dd0af0c0b923c0878d9483b367ec45ebd54)
* Operating system: Win 10

### Expected behavior

Open file dialog return path.

### Actual behavior

Get a error

### How to reproduce
1. Create file (for example `C:\vs_slash_bug/test.txt`)
2. Run Open file dialog
3. Try open file `C:\vs_slash_bug/test.txt` (change al least one slash to forward slash for example)
4. Error 

But I can open with bad slashes in notepad, and other tools. I found this behaviour in Visual Studio Code, but after I create some easy example for reproduce this bug in electron (using `electron-quick-start`)
Code:
```js
const {dialog} = require('electron').remote
console.log(
    dialog.showOpenDialog({
        properties: ['openFile'],
        filters:[
            {name: 'All Files', extensions: ['*']}
        ]
    })
);
```
Please for animated GIF with bug visit [VS Code issue](https://github.com/Microsoft/vscode/issues/15270)

I think need something like:

```cpp
#ifdef OS_WIN
                for (int i = 0; filepath[i] && i < _MAX_PATH /* len of filepath */; ++i)
                {
                    if (filepath[i] == '/')
                        filepath[i] = '\\';
                }
#endif
```

around `base::FilePath` or in `CShellFileOpenDialog`.

Thanks for your project.

**Comment by MarshallOfSound** [comment]
You need to use nodes `path.normalize` method in your paths

**Comment by verysimplenick** [comment]
@MarshallOfSound , nope , Electron `showOpenDialog` not returned paths, callback not runned if I try open `C:\vs_slash_bug/test.txt` path. It's C++, not js bug.
Reopen please and try reproduce first.

**Comment by MarshallOfSound** [comment]
I did try to reproduce but failed at step 3.

> 3. Try open file C:\vs_slash_bug/test.txt (change al least one slash to forward slash for example)

There is no way in a windows open dialog to manually specify a file path like that (that I am aware of).  Can you provide a screenshot of exactly what you are doing during that step

**Comment by MarshallOfSound** [comment]
@verysimplenick This appears to be native windows behavior.

I tested in `notepad.exe` and attempted to open a file like you did in your GIF and got exactly the same warning.  It's an OS level limitation, any open dialog that handles the incorrect slash will be custom for the application and won't be using the OS level open dialog.

**Comment by verysimplenick** [comment]
Yep, sorry, I use `akelpad` for replacement of `notepad`, seems like he have custom dialog that can open this paths.
