### ISSUE TITLE
Error deserialization in IPC system

### ISSUE THREAD

**Issue by ziflex** [electron/electron#7956]
Hi there,

I'm experiencing a problem with a deserialization of Error object. Passed Error via IPC from one process to another one loses its message and stack trace, well it loses all information.

* Electron version: 1.4.6
* Operating system: Fedora 24

### Expected behavior

Expected to receive deserialized instance of Error object.

### Actual behavior

Actually receive plain JS object ``{ cause: {}, isOperational: true }``

### How to reproduce

Just pass Error object from a rendering process to a main one.

**Comment by MarshallOfSound** [comment]
@ziflex That is because `Error` objects in javascript do not have JSON serialization by default.  You can inject  a `toJSON` prototype yourself to serialize it how you want.

http://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify

**Comment by ziflex** [comment]
Why not to add a workaround for it?

**Comment by MarshallOfSound** [comment]
Because it is standard JS behavior, the `Error` prototype has never been serialized to contain message and stack and such.  Changing that in Electron could (and probably would) break existing code.
