### ISSUE TITLE
Using buffers as img element source

### ISSUE THREAD

**Issue by skerit** [electron/electron#7959]
Is there a way to use a buffer containing image data as an `<img>` element's source, without using a data url? Maybe using `URL.createObjectURL(blob);` somehow.

It seems kind of silly to write the image to disk first only to be able to show it inside Electron.

I'm doing it like this for now:

```js
si.getPreview(function gotPreview(err, image_buffer) {

	var image = nativeImage.createFromBuffer(image_buffer),
	    el = new Image();

	var prev = document.getElementById('preview');

	el.src = image.toDataURL();

	prev.appendChild(el);
});
```

But that seems quite wasteful. Any ideas?

**Comment by thesbros** [comment]
Try this (untested):

```js
// set `type` to the image format, e.g image/jpeg or image/png
var blob = new Blob([image_buffer], {type: "image/png"});
var url = URL.createObjectURL(blob);

var prev = document.getElementById('preview');
el.src = url;
prev.appendChild(el);
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by skerit** [comment]
No problem.

Just for future reference: The code snippet by @thesbros works
