### ISSUE TITLE
Electron's Developer Tools cannot 'Remove folder from workspace'

### ISSUE THREAD

**Issue by tudorg-telenav** [electron/electron#7960]
* Electron version: ^1.4.5
* Operating system: Windows 10@last-version

### Expected behavior

Electron's Developer Tools should be able to 'Remove folder from workspace' after successfully adding them with the 'Add folder to workspace' option.

### Actual behavior

Electron's Developer Tools cannot 'Remove folder from workspace' after successfully adding one with the 'Add folder to workspace' option.

### How to reproduce

* run a basic electron app
* open the embedded Developer Tools
* use the Add folder to workspace option in the sources' left panel
* try to remove it

**Comment by mohamed-fadl** [comment]
working on that :)

**Comment by deepak1556** [comment]
You can use `settings > workspace` panel to remove as workaround.
