### ISSUE TITLE
usb support

### ISSUE THREAD

**Issue by jdnichollsc** [electron/electron#7961]
Hi guys,

I can´t build with the following **modules**:

- https://www.npmjs.com/package/usb
- https://www.npmjs.com/package/electron-usb

What is the correct way to do work with USB devices?

Thanks in advance, Nicholls

**Comment by thesbros** [comment]
Do you have any more information? Is there an issue building the modules?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

RE building native modules: See http://electron.atom.io/docs/tutorial/using-native-node-modules/
