### ISSUE TITLE
can <webview>  support touch events?

### ISSUE THREAD

**Issue by zjy01** [electron/electron#7964]
* Electron version: 1.2.2
* Operating system: win7

### Expected behavior

I really think that webview should support **touch events**, Because something I want to use it to  simulate a _mobile browser_. 

It is more than any other framework for doing this.

### Actual behavior

It only response to the normal events as a pc borwser, but i holp that chrome can do more.

**Comment by kevinsawicki** [comment]
> Electron version: 1.2.2

Have you tried with Electron 1.4.6 yet?

**Comment by zjy01** [comment]
yes, I have just updated to `v1.4.6`.
But I don't find any configuration for this.

Thank you for your attention

**Comment by zcbenz** [comment]
Electron only supports the event that Chrome supports, we are not able to provide more support for touch events than Chrome.

**Comment by zjy01** [comment]
But chrome support touch event(when F12), So I don't know whether electron can also support it in the webview

**Comment by coderbuzz** [comment]
+1 webview currently doesn't support touch-screen. Any configuration am missing to make touchscreen work on webview?

**Comment by PinkyJie** [comment]
I have the same problem, there is a command line switch in Chrome called `--emulate-touch-events`, but it seems Electron dose not support this switch according to [the documentation](http://electron.atom.io/docs/api/chrome-command-line-switches/).

**Comment by MarshallOfSound** [comment]
@PinkyJie That is not an exclusive list, lots of CLI switches work in Electron that aren't on that list.  You might want to just try it and see if it works 👍

**Comment by ksky521** [comment]
+1 webview currently doesn't support touch-screen

**Comment by chemzqm** [comment]
I can't make webview to support touch events, please add support for it.

**Comment by ssivanatarajan** [comment]
Any update on this? i want to simulate a mobile device in electron
