### ISSUE TITLE
Warning: exited with code 3221225621.

### ISSUE THREAD

**Issue by IsmaTeddy** [electron/electron#7965]
* Electron version: Electron for last version kitematic, 
* Operating system: W10

### Expected behavior

I install kitematic for windows and exec npm install, npm start, I expected kitematic open.

### Actual behavior

Kitematic not open and finish with error:
Warning: Done, with errors: command "D:\kitematic\node_modules\electron-prebuilt\dist\electron.exe build" (target "electron") exited with code 3221225621.

### How to reproduce

Download kitematic from github, npm install and npm start but not always succed....

----------------

how solved error code 3221225621 on electron?

**Comment by kevinsawicki** [comment]
@IsmaTeddy if you download Electron and run it directly, does the default app display?

**Comment by paulcbetts** [comment]
```
0:000> .formats 3221225621
Evaluate expression:
  Hex:     00000032`21225621
  Decimal: 215304263201
  Octal:   0000000003104110453041
  Binary:  00000000 00000000 00000000 00110010 00100001 00100010 01010110 00100001
  Chars:   ...2!"V!
  Time:    ***** Invalid FILETIME
  Float:   low 5.50017e-019 high 7.00649e-044
  Double:  1.06374e-312
0:000> .formats 0n3221225621
Evaluate expression:
  Hex:     00000000`c0000095
  Decimal: 3221225621
  Octal:   0000000000030000000225
  Binary:  00000000 00000000 00000000 00000000 11000000 00000000 00000000 10010101
  Chars:   ........
  Time:    ***** Invalid
  Float:   low -2.00004 high 0
  Double:  1.5915e-314
0:000> !error c0000095
Error code: (NTSTATUS) 0xc0000095 (3221225621) - {EXCEPTION}  Integer overflow.
```

**Comment by IsmaTeddy** [comment]
@kevinsawicki I can see electron app but i have a warning:

![image](https://cloud.githubusercontent.com/assets/19637084/20383225/35e037e6-acaf-11e6-9749-1314cc98ae05.png)

**Comment by kevinsawicki** [comment]
That warning is fine to ignore, it is from npm.

Since the default app loads correctly this is most likely an issue with kitematic, have you tried reporting it there?

I'm going to close this out here for now since the default app is working as expected. Without more information it won't be possible to debug this. If you hear back from kitematic or are able to reproduce this with a small app then we can reopen this issue and look into it further, thanks.
