### ISSUE TITLE
Feature request: Please provide an AppImage for Electron

### ISSUE THREAD

**Issue by fusion809** [electron/electron#7966]
Hi,

While I suspect you will turn down this feature request, as you's already produce zip archive that do something very similar already, I would like to request an AppImage for Electron. AppImages are a type of cross-distribution (although limited to Linux systems) package format are essentially self-mounting self-contained image files (similar to the ISO files used to contain operating systems and programs). They are most similar to the disk image (file extension: `.dmg`) format of macOS. They are fairly easy to create. 

Thanks for your time,
Brenton

**Comment by MarshallOfSound** [comment]
AppImage appears to be a growing trend of sorts but I don't think it suits Electron's distribution methodology.  Applications built on Electron should be asked to provide AppImage files.  Electron itself is just a couple of pre-built binaries that can be distributed however you want.  (Could be `.deb`, `.rpm` or `AppImage`).

Your example of a `.dmg` explains this quite well I think, we provide a ZIP file of prebuilts for macOS and if an application wants to distribute a DMG then they generate a DMG and put our prebuilts inside.  The same concept should be applied to AppImage, we provide the prebuilts, applications should do whatever they want with them.

If you want to build `AppImage` files for you Application I believe the `AppImage` repository has a guide on how to do it 👍
