### ISSUE TITLE
Add API to close QLPreviewPanel after `previewFile`

### ISSUE THREAD

**Issue by bengotow** [electron/electron#7968]
In 1.4.5, Electron added a new API (`previewFile`) that allows you to open a quicklook preview panel. However, there isn't an API for closing the preview panel that is opened.

QLPreviewPanel is a subclass of NSWindow - using Mac OS X APIs, it's pretty easy to close the shared Quicklook preview panel.

We need this functionality because the panel does not close automatically when the window is blurred, or when another window is opened in the application (https://github.com/nylas/N1/issues/3021). Other user action, such as moving focus to a message that doesn't have quicklook attachments should also probably close the panel.

I'm not sure what a good name for this API would be. Maybe `dismissFilePreview` or `unpreviewFile`?

**Comment by kevinsawicki** [comment]
> Maybe dismissFilePreview or unpreviewFile?

`closeFilePreview` maybe?
