### ISSUE TITLE
Installing Augury (angular2) dev tool on electron 1.4.5

### ISSUE THREAD

**Issue by tomasro27** [electron/electron#7970]
* Electron version: 1.4.5
* Operating system: Win10

We just updated electron to 1.4.5, and one of the reasons to upgrade, was to be able to use dev extensions such as Augury.  I tried installing the dev extension, following the steps described in electron docs: https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md

### Expected behavior

Augury dev tool to work with newest version of electron

### Actual behavior

Augury was installed, and the Augury tab is visible, but the dev tool doesn't actually work.  
It throws the error: "responde callback is not supported"
https://github.com/electron/electron/blob/19d8a366b35536681cb77e634cb1e7dd387a1cc0/lib/renderer/chrome-api.js#L124

### How to reproduce
Install Augury https://chrome.google.com/webstore/detail/augury/elgalmkoelokbchhkhacckoklkejnhcd
on the latest version of electron

It would be nice to know if there is a work around for this, if this is intended to be supported in the future, or if we can help making this work.  It would be greatly appreciated, and helpful for our team.

Thanks

**Comment by MarshallOfSound** [comment]
I had a WIP implementing the response callback, if I get time I'll try resurrect it and get it working.

**Comment by MarshallOfSound** [comment]
Upon further investigation (and actually implementing the response callback)  it looks like Augury does not even use the response callback.

The relevent code from augury

```js
chrome.runtime.onMessage.addListener(function (message, sender) {
    communication_1.deserializeMessage(message);
    var cannotRespond = function () {
        throw new Error('You cannot respond through MessageHandler');
    };
    subscriptions.forEach(function (handler) { return handler(message, cannotRespond); });
    return true;
});
```

Notice how they only take in message and sender.  Whatever is causing Augury to fail it is not the response callback not being implemented.

**Comment by zh99998** [comment]
this extension still can't work under electron v1.6.5
no errors are printed in console, but also no any content.
as rangle/augury#687
