### ISSUE TITLE
MenuItem accelerator (hotkey) of F1~F12 doesn't work

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#7975]
* Electron version: 1.4.5
* Operating system: Win10

### Expected behavior

Press `F12` will open devtools.

### Actual behavior

Press `F12` has no effect.

### How to reproduce

```
let template = [
	{
		label: 'Developer tools',
		accelerator: 'F12',
		click: function(menuItem, browserWindow){
			browserWindow.openDevTools();
		}
	}
];
let menu = Menu.buildFromTemplate(template);
browserWindow.webContents.on('context-menu',  (evt)=>{
	menu.popup(evt.sender);
});
```

If I change the `F12` to `CmdOrCtrl+A`, the accelerator will work well.

**Comment by kevinsawicki** [comment]
I'm having trouble reproducing this on Windows 10 in Parallels.

If you run the default Electron app and press `F11` does it toggle full screen?

**Comment by cuixiping** [comment]
F11 always can toggle full screen even in an empty app. Maybe it's provided by OS like Ctrl+W to close the window.

I misunderstood the `accelerator` setting of menu item object. It just shows a text on the menu item, I need to listen and handle the keyboard events by myself. so you can close this issue now.

Accelerators of `MenuItem` cannot work on my Win10 PC except they are same as system shortcuts like `Ctrl+C` for copy.

I need `BrowserWindow` level hotkeys but electron only has global hotkeys. [Other issues about keyboard shortcuts](https://github.com/electron/electron/issues?utf8=%E2%9C%93&q=is%3Aissue%20shortcuts) covered my question. 

Now my solution is :  Add event listener on the page javascript and send message to app by ipc.

Page JS:
```
window.addEventListener('keyup', function (e){
	if(e.keyCode==123){ //F12
		ipcRenderer.send('F12');
	}
}, false);
```

App JS:
```
ipcMain.on('F12', function (event) {
	let win = BrowserWindow.fromWebContents(event.sender);
	win.openDevTools();
});
```

**Comment by zeke** [comment]
> I misunderstood the accelerator setting of menu item object. It just shows a text on the menu item, I need to listen and handle the keyboard events by myself. so you can close this issue now.

👍 thanks for letting us know you worked it out.
