### ISSUE TITLE
Only the root dir .tsx .js and .map files are shown as loaded in DevTools, when debugging the renderer process

### ISSUE THREAD

**Issue by tudorg-telenav** [electron/electron#7976]
* Electron version: ^1.4.25
* Operating system: Windows 10

I have this basic [Typescript + Electron + React](https://github.com/tudorg-telenav/typescript-playground) app.

### Expected behavior

Since I have mappings for all my .tsx files, I would expect Electron's embedded DevTools to load all my .tsx files along with my .js files and .map files.

### Actual behavior

Electron's embedded DevTools, only shows loaded for debugging the root directory files (.tsx, .js and .map), but doesn't show the files inside directories, even if they are loaded and mapped the same way as root dir ones.

### How to reproduce

* clone my repo
* npm install it
* debug the Electron's renderer process
* behold the app.tsx file and the Test.tsx files loaded along with their .js and .map counterparts
* see that the 'pane_components' directory files are not loaded for debugging

**Comment by MarshallOfSound** [comment]
All my files appear under the `(no domain)` category in the devtools, can you check there?

**Comment by tudorg-telenav** [comment]
Yes, the .js files appear in the `(no domain)` category, however, some of the files also appear in the `file://` category but only the root ones, not the ones in a directory.
The root .tsx files appear only in `file://` and not in `(no domain)` so I would guess this is the place to look for all .tsx.
Also, regardless of TypeScript, plain .js files appear under `file://` ONLY if they are in the root dir. So that's  weird by its own, I would say.
Anyway, this may be a TypeScript thing, I'll try without TypeScript and see. I woulnd't know if it being a TS thing means it should be posted on Electron or on Typescript issues page.

**Comment by MarshallOfSound** [comment]
@tudorg-telenav It's not just root files appearing in `file://`, its files that are requested as script URL's in an HTML file.  All files requested through `require` appear in `(no domain)`

**Comment by tudorg-telenav** [comment]
Well... It seems ONE way to do it, or maybe THE (only) way to do it (??) is to use `webpack`.

I tried to have the react app (renderer part of electron) running in the browser. The need for webpack arose. Then I discovered it also solves my "electron issue" too.

This allows me to debug the .tsx & .ts files from the `webpack://` category.

I'll close this now 😄 !
