### ISSUE TITLE
What's the difference between `window.openDevTools()` and `contents.openDevTools()` ?

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#7987]
There are some devtools relative apis like `openDevTools()` on [webContents](http://electron.atom.io/docs/api/web-contents/) documentation page and NOT on [BrowserWindow](http://electron.atom.io/docs/api/browser-window/) page.

I saw some demo code use these apis for BrowserWindow instance object.
And It works well for my testing.

What's the difference between `window.openDevTools()` and `contents.openDevTools()` ?

**Comment by enlight** [comment]
There is no difference, the `BrowserWindow` just ends up calling those methods on the `WebContents`, as you can see here: https://github.com/electron/electron/blob/9624bc140353b3771bd07c55371f6db65fd1b67e/lib/browser/api/browser-window.js#L166

In general though I would suggest avoiding undocumented methods.
