### ISSUE TITLE
Is it legal to replace LICENSE file in application?

### ISSUE THREAD

**Issue by artpol** [electron/electron#7988]
* Electron version: 1.4.5
* Operating system: Windows 10

Is it legal to replace LICENSE file in application? 
In app folder i see 2 license files: 

LICENSES.chromium.html - nesessary electron license, I do not touch it,  
LICENSE - if I understand correctly, it should be license for my application ?

Is this right? thanks.

**Comment by MarshallOfSound** [comment]
If you have legal questions you should consult a lawyer.

As far as I am aware:
`LICENSES.chromium.html` contains all of Chromium's licencing information
The `LICENSE` file in the Electron repository is the license for Electron itself.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by develar** [comment]
https://discuss.atom.io/t/list-licenses-in-app/27656 is unanswered.
