### ISSUE TITLE
Support macOS Haptic Feedback API for Force Touch Trackpad

### ISSUE THREAD

**Issue by martindsouza** [electron/electron#7994]
API to support the Haptic feedback API for Force Touch trackpads in macOS. I realize this would be for a specific set of users/hardware but could provide some very interesting opportunities.

Some examples that come to mind:

- When clicking on a disabled button
- Accessibility features for mousing over something
- Other?

I'm not an Apple developer so not sure how much help I can be but did find this API documentation: https://developer.apple.com/reference/appkit/nshapticfeedbackperformer  It also provides a good summary as to how and when to use the engine.

**Comment by zcbenz** [comment]
There is an open Chromium issue for this: https://bugs.chromium.org/p/chromium/issues/detail?id=568727, I'm closing this issue since there is not much meaning keeping the same issue opened in Electron, anyone interested in this can follow the Chromium issue instead.
