### ISSUE TITLE
Still don't have any console.* massages under Windows 8.1

### ISSUE THREAD

**Issue by wenshiqi0** [electron/electron#7995]
I have already read #3032 but it is still not worked. Under my Windows 8.1 PC, console.* does not print anything on the cmd, but it works just fine on my MacOX PC.

electron : 1.4.6
windows : 8.1
macox : 10.11.6

**Comment by wenshiqi0** [comment]
I have also write a script into the package.json

```
version: electron -v
```

and then to run ` npm run version`, and still get nothing.

**Comment by MarshallOfSound** [comment]
Have you tried using the environment variable `ELECTRON_ENABLE_LOGGING=true`

**Comment by wenshiqi0** [comment]
Still don't work

**Comment by zcbenz** [comment]
I'm merging this to #6946.
