### ISSUE TITLE
[feature request] Calling 'DevTools->Console->SaveAs'

### ISSUE THREAD

**Issue by Klestofer** [electron/electron#7997]
DevTools Console has context menu with 'Save as...' item. It would be very handy to have possibility to call it programmatically for both `BrowserWindow` and `<webview>`(or maybe for their `webContents`). Something like: `saveDevToolsConsole(pathToFile)` or maybe `saveDevToolsConsoleLog(pathToFile)`.

![image](https://cloud.githubusercontent.com/assets/13150079/20379886/55ab43e6-acea-11e6-8732-041dac9ba702.png)

And making method for calling 'Clear console' item would also be useful.

**Comment by MarshallOfSound** [comment]
I can't comment on the ability to add an API for Save As.. (I haven't looked into it).  But there is a `console` method for clearing the console

```js
console.clear()
```

**Comment by Klestofer** [comment]
Thanks. I've forget about it. This works good for clearing console:
`win.webContents.executeJavaScript('console.clear()')`

**Comment by deepak1556** [comment]
@Klestofer its not possible unless we make changes in devtools. An alternative is using [webContents.debugger](https://github.com/electron/electron/blob/master/docs/api/debugger.md) api and listen for console messages with rdp.
