### ISSUE TITLE
angularjs $emit and $on cannot work

### ISSUE THREAD

**Issue by MissCuriosity** [electron/electron#7998]
* Electron version: 1.4.6
* Operating system: windows

### Expected behavior

click a button, $window.open or   < a href="" target="_blank"    works, and emit a event to the rootScope,and rootScope will broadcast a new event,the new browser window will receive the event,and get the arguments.

### Actual behavior
the new browser window cannot get the arguments and the sessionStorage didn't work too

### How to reproduce

html:
button type="button" ng-click="order.print()">open a new window</button
js:
function openNewWindow() {
        var list = 'test';

        var urlHref = $state.href('test.open-new-window');
        $window.open(urlHref, '', 'width = 1280, height = 900');

        $scope.$emit('get_list', list);
    }
app.module.js:
$rootScope.$on('get_list', function(event, args) {
        $scope.$broadcast('_g_get_list', args);
    });

new window controller:
$scope.$on('_g_get_list', function (event, args) {
        var result = args;
        console.log(111, args);
    });

**Comment by MarshallOfSound** [comment]
Bearing in mind lots of people have no idea how angular is supposed to work.  Can you explain what `$scope` and `$rootScope` are and how they are supposed to emit events across windows.

**Comment by Moai-** [comment]
I'll pitch in here.

@MissCuriosity Angular is not aware of Electron's other windows. I created an AngularJS project that uses multiple windows. This is kind of like if you had Angular running in a webpage that opened a popup: would you expect that popup to have access to rootScope? (it does not.)

The best solution is to use the [IPC system](https://github.com/electron/electron/blob/master/docs/api/ipc-renderer.md). It works exactly like $broadcast and $on, except within Electron's ecosystem. You may be tempted to share the entire $rootScope through it, but in my experience, this makes your app unbearably slow. You'll have to narrow down the data you want to share between windows, and share only that. But this is a good starting point for you.

**Comment by enlight** [comment]
Closing this since it appears to be an issue with the OP's app, not Electron. Thanks for the explanation @Moai- 👍
