### ISSUE TITLE
executeJavaScript() returns null instead of undefined

### ISSUE THREAD

**Issue by Klestofer** [electron/electron#7999]
All this lines
`webView.executeJavaScript('', result => console.log('result:', result))
webView.executeJavaScript('undefined', result => console.log('result:', result))
webView.executeJavaScript('void 0', result => console.log('result:', result))
webView.executeJavaScript('[][[]]', result => console.log('result:', result))`
print `result: null`.

But why? Is it a bug or not? Maybe they should print `result: undefined`?

That is: this two lines print the same:
`webView.executeJavaScript('undefined', result => console.log('result:', result))
webView.executeJavaScript('null', result => console.log('result:', result))`

And another thing: this line
`webView.executeJavaScript('Number.NaN', result => console.log('result:', result))`
prints `result: 0`

This happens on  latest Electron on Windows and macOS.

**Comment by MarshallOfSound** [comment]
`undefined` can not be passed through IPC as their is no JSON representation for it.  In some cases it is casted to `null` by `JSON.stringify`.

This is expected
