### ISSUE TITLE
Feature request: support --inspect option for debug main process

### ISSUE THREAD

**Issue by chemzqm** [electron/electron#8002]
I've tried to upgrade electron to 1.4.6, but unfortunately, it's using node 6.5.0, and it looks like node-inspector no longer works with that version of node https://github.com/node-inspector/node-inspector/issues/907. node have added `--inspect` flag but I couldn't find any way to pass this flag to node from running electron.

I've also tried `electron-inspector` and failed.

**Comment by MarshallOfSound** [comment]
Closing out for https://github.com/electron/electron/issues/6634
