### ISSUE TITLE
Autoupdate without replace/remove files from app?

### ISSUE THREAD

**Issue by oscarjiv91** [electron/electron#8004]
I'm using autoupdate for newer versions of my app. I have a database inside the app and a folder with pictures that are uploaded by the user. When there is a version, and updates the app, this database is deletes, and also the pictures uploaded. The update replaces all the folders and files. Is there a way to exclude some of them? Or is this a Squirrel related thing?

**Comment by kevinsawicki** [comment]
> The update replaces all the folders and files. Is there a way to exclude some of them? Or is this a Squirrel related thing?

There is no way to exclude them, the entire app is replaced on every update. You can store generated files in other locations outside the app though so they don't get replaced.

See http://electron.atom.io/docs/api/app/#appgetpathname for more details on getting path to special locations on disk that can be used.

**Comment by oscarjiv91** [comment]
Got it, thank you!
