### ISSUE TITLE
Electron fails to install in Win10

### ISSUE THREAD

**Issue by Niwotian60** [electron/electron#8005]
I am running Win 10 with node 7.1.0 without problem.  However, electron fails to install properly with the command line:  
`  npm install electron --save-dev `

The tail of the npm_debug.log beginning with the first warn is:
"
14331 warn electron_test@1.0.0 No repository field.  
14332 verbose If you need help, you may report this error at:  
14332 verbose     <https://github.com/npm/npm/issues>  
14333 verbose stack Error: electron@1.4.7 postinstall: `node install.js`  
14333 verbose stack Exit status 1  
14333 verbose stack     at EventEmitter.<anonymous> (D:\dev\Node\bin\node_modules\npm\lib\utils\lifecycle.js:255:16)  
14333 verbose stack     at emitTwo (events.js:106:13)  
14333 verbose stack     at EventEmitter.emit (events.js:191:7)  
14333 verbose stack     at ChildProcess.<anonymous> (D:\dev\Node\bin\node_modules\npm\lib\utils\spawn.js:40:14)  
14333 verbose stack     at emitTwo (events.js:106:13)  
14333 verbose stack     at ChildProcess.emit (events.js:191:7)  
14333 verbose stack     at maybeClose (internal/child_process.js:885:16)  
14333 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)  
14334 verbose pkgid electron@1.4.7  
14335 verbose cwd D:\dev\Node\electron_test  
14336 error Windows_NT 10.0.14393  
14337 error argv "D:\\dev\\Node\\bin\\node.exe"  "D:\\dev\\Node\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron" "--save-dev"  
14338 error node v7.1.0  
14339 error npm  v3.10.9  
14340 error code ELIFECYCLE  
14341 error electron@1.4.7 postinstall: `node install.js`  
14341 error Exit status 1  
14342 error Failed at the electron@1.4.7 postinstall script 'node install.js'.  
14342 error Make sure you have the latest version of node.js and npm installed.  
14342 error If you do, this is most likely a problem with the electron package,  
14342 error not with npm itself.  
14342 error Tell the author that this fails on your system:  
14342 error     node install.js  
14342 error You can get information on how to open an issue for this project with:  
14342 error     npm bugs electron  
14342 error Or if that isn't available, you can get their info via:  
14342 error     npm owner ls electron  
14342 error There is likely additional logging output above.  
14343 verbose exit [ 1, true ]  
"

**Comment by frankhale** [comment]
See this issue: https://github.com/nodejs/node/issues/9542

New release of Node tentatively scheduled for next Tuesday

**Comment by Niwotian60** [comment]
Thanks - that answers my question perfectly. I searched for 7.1.0 with ELIFECYCLE errors and didn't find anything, but apparently EINVAL also occurs.
