### ISSUE TITLE
Cannot handle open file from desktop while app is running on Windows

### ISSUE THREAD

**Issue by lxfschr** [electron/electron#8006]
* Electron version: 1.0.2
* Operating system: Windows 10 x64

I would expect to be able to add a listener like app.on("open-file", ... is triggered Mac when the app is closed and when it is running.

On Windows, I am able to open a file from the desktop if the app is not running by looking at process.argv as the app is starting up.

However, once the app is running, and I double click a file on my desktop, the app will just focus itself and not open the file. The only event that is triggered is app.on("browser-window-focus, ... but process.argv does not contain the path to the file at this point either. 

Could someone provide some advice for how to accomplish this? I know it is possible because Atom is able to open files in the same window while the app is running on windows. I tried stepping through their source code but was unable to pin it down after 2 days of searching.

Any help would be much appreciated :)

Thanks

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

You should look into the docs of [`app.makeSingleInstance`](http://electron.atom.io/docs/api/app/#appmakesingleinstancecallback).  In particular notice that the second instances `process.argv` is passed as a parameter.
