### ISSUE TITLE
CrashReporter is not posting reports to submitUrl on Windows and Linux

### ISSUE THREAD

**Issue by Apex2apex** [electron/electron#8007]
* Electron version: 1.4.7
* Operating system: Windows 8.1 Pro, Ubuntu 16.04 64bit

### Expected behavior

A dump file automatically posted to submitUrl that is specified in CrashReporter.init()

### Actual behavior

Nothing is posted for Windows and Linux.  When look into the tempfolder/appname crashes, there is a operation_log.txt generated on Windows, but nothing (file/folder) is created for Linux

### How to reproduce

Open developer console, and crash Electron by process.crash().

CrashReporter code

const {crashReporter} = require('electron');

function init () {
  crashReporter.start({
    companyName: 'company',
    productName: 'product',
    submitURL: 'https://mycrashserver.com/crash_upload',
    autoSumbit: true
  });
}

**Same code is working on Mac 10.12**

**Comment by kevinsawicki** [comment]
@Apex2apex are you starting the crash reporter in the renderer process? If not, could you try that and see if it submits the crashes on Linux/Windows.

**Comment by Apex2apex** [comment]
Yes I am starting the crash reporter in my renderer processes.  I tried both in our class constructor and after the BrowserWindow's "ready-to-show" event fired.  Still not seeing any crashes being submitted.

**Comment by kevinsawicki** [comment]
> Yes I am starting the crash reporter in my renderer processes.

What server implementation are you using to collect them?

**Comment by Apex2apex** [comment]
Caliper, a fork of electron/mini-brekpad-server

https://github.com/rrohrer/Caliper

**Comment by kevinsawicki** [comment]
@Apex2apex I'm having trouble reproducing this locally. Are you able to create a reproduction app from a fork of https://github.com/electron/electron-quick-start that you can reproduce the issue on? Then I can just swap out the URLs and test locally.

**Comment by Apex2apex** [comment]
I was able to post crashes up to our server using electron-quick-start on both Windows and Linux.  I would have to look deeper into our setup and troubleshoot.

Thanks for all the help!
