### ISSUE TITLE
pass data by mainWindow.webContents.send not working in angularJs1.5

### ISSUE THREAD

**Issue by MissCuriosity** [electron/electron#8010]
* Electron version:1.4.6
* Operating system:all

### Expected behavior
oepn a new html width target="_blank" ,and at the same time pass data to the main progress,
when main progress receive the event,it will broadcast the data to another render

### Actual behavior
a target="_blank" ng-click='$scope.openNewWindow()'
function openNewWindow() {
    ipcRenderer.send('open_new_window', 'this is a test');
}

main.js:
ipcMain.on('open_new_window', (event, arg) => {
    mainWindow.webContents.send('_g_open_new_window', 'aaaaaaa');
});

another.js
ipcRenderer.send('_g_open_new_window', (event, arg) => {
    console.log(222,arg);
});

why mainWindow.webContents.send failed???

**Comment by enlight** [comment]
GitHub issues are for bug reports and feature requests, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community).
