### ISSUE TITLE
 Webview security and filesystem access 

### ISSUE THREAD

**Issue by zibra** [electron/electron#8011]
Hi,

when user clicks on link to e.g. pdf or exe file inside webview, new "save to" window appears and user gets access to whole filesystem through this windows. How to prevent that?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
FWIW you probably want https://github.com/electron/electron/blob/master/docs/api/session.md#event-will-download
