### ISSUE TITLE
npm & yarn stuck while installing electron 

### ISSUE THREAD

**Issue by a-eid** [electron/electron#8012]
I'm trying to install electron , but seems that neither yarn nor npm able to complete the installation . 
they hang up and they have been hung up for a while now . 

*@1.4.7
* Windows:

### Expected behavior
to complete the installation 

### Actual behavior

its stuck 

### How to reproduce

![](http://image.prntscr.com/image/1eb5ca8b04b048f3b96ccb72c7ad6c76.png)
![](http://image.prntscr.com/image/edf7d5f367f549e79cbe7d7ad793d13a.png)

**Comment by a-eid** [comment]
after being stuck for some time (( too long )) 
![](http://image.prntscr.com/image/76a6b4123fce47518daa9a2683e92cd0.png)
![](http://image.prntscr.com/image/3a8c570681bc4cfcaa81aa2022b18e70.png)

**Comment by a-eid** [comment]
I guess it either was cmder (terminal emulator) or the problem got fixed

**Comment by MarshallOfSound** [comment]
@a-eid For future reference the `ECONNRESET` error indicates a user-side network issue, your internet connection was probably unstable at the time.
