### ISSUE TITLE
electron.webFrame is undefined

### ISSUE THREAD

**Issue by httpdigest** [electron/electron#8013]
* Electron version: 1.4.7
* Operating system: Windows 7 x64

`require('electron').webFrame` should not be undefined

### Actual behavior

`require('electron').webFrame` returns undefined

### How to reproduce

In the below test case, I just create a normal BrowserWindow and register a global shortcut for Ctrl+Up, which when executed prints "undefined" (as per `console.log(webFrame)` and throws a TypeError indicating that the property `setZoomLevel` cannot be read on undefined:

```JavaScript
const electron = require('electron')
const app = electron.app
const webFrame = electron.webFrame;
const globalShortcut = electron.globalShortcut
const BrowserWindow = electron.BrowserWindow
function createWindow () {
  const window = new BrowserWindow()
  globalShortcut.register('Ctrl+Up', () => {
    console.log(webFrame)
    webFrame.setZoomLevel(2)
  })
  globalShortcut.register('Ctrl+Down', () => {
    webFrame.setZoomLevel(1)
  })
  window.loadURL('http://localhost:8080/index.html')
}
app.on('ready', createWindow)
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
```

The index.html is just a simple `<p>Hello</p>` served via Node's http-server.
It's surely me, but I cannot for the life of me figure out how to access the webFrame.

**Comment by v12** [comment]
You can't use `webFrame` in your main process - it's available only in renderer.

**Comment by httpdigest** [comment]
Thank you!

**Comment by MarshallOfSound** [comment]
@httpdigest For future reference the process in which API's are available is indicated at the top of each API

https://github.com/electron/electron/blob/master/docs/api/web-frame.md#webframe
