### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by kvidzibo** [electron/electron#8015]
Hello,

I experiencing similar issue as https://github.com/electron/electron/issues/7049 .

I raised this issue https://github.com/segmentio/nightmare/issues/894 as well. But I think it has nothing to do with nightmare, since after installing 32 bit version of electron it seems that this issue has disappeared. It's not an emergency for me or something, since I have no problem using 32bit version, just though you guys might want to know about it.

https://github.com/segmentio/nightmare/issues/894 has more description, don't want to duplicate it. If you need more information or something, let me know. Also I might mention that I didn't had this issue on debian 8, it's just after I installed linux mint 18, so it might be something with linux kernel maybe, since mint uses newest version?

Cheers

**Comment by frankhale** [comment]
One way to avoid the "white screen" is to make sure your BrowserWindow is hidden initially and then handle the "did-finish-load" event. When you get that event show your window.

**Comment by kvidzibo** [comment]
I mean it never finish to load. once it goes white there is no way back. I mean if you have a script it will continue doing stuff electron will continue to update html in developers tools however screen never get's updated. And as I said all I needed to fix that is install 32bits version, no other changes what so ever.

**Comment by frankhale** [comment]
I'm sorry, I misunderstood the issue. =(

**Comment by kvidzibo** [comment]
it's fine man, normally I don't report stuff it's just that I spent like half a day trying to figure it out. So I thought I might as well write it there so it might help for someone.

**Comment by weiway** [comment]
I just updated #7049 with the dump file. My software has this problem on all win32 bit system for now

**Comment by kevinsawicki** [comment]
> I just updated #7049 with the dump file. My software has this problem on all win32 bit system for now

Thanks, I've reopened that issue and will close this one out here.

@kvidzibo please subscribe to #7049 for updates.
