### ISSUE TITLE
Window over Dock in macOS

### ISSUE THREAD

**Issue by T-Specht** [electron/electron#8018]
Hello!

I am building an application with electron in which I would like to display a window at the bottom of the user's screen above the macOS dock when the user uses some global shortcut in a similar way to [Paste](http://pasteapp.me/) for macOS. 
I want it to look something like this
<img width="1440" alt="bildschirmfoto 2016-11-19 um 10 14 40" src="https://cloud.githubusercontent.com/assets/9967256/20454458/b7d2710e-ae41-11e6-9587-13f7bf658aca.png">

Right now I am configuring my BrowserWindow as follows, but it is positioned just over the dock.

`var {screen} = electron;
    var screenBounds = screen.getPrimaryDisplay().size;
    var height = 75;
    var main = new BrowserWindow({
        frame: false,
        width: screenBounds.width,
        height: height,
        x: 0,
        y: screenBounds.height,
        alwaysOnTop: true,
        resizable: false,
        movable: false,
        show: false,
        focusable: true,
        skipTaskbar: true,
        vibrancy: "appearance-based"
    });`

Result when showing the window:

<img width="1440" alt="bildschirmfoto 2016-11-19 um 10 26 38" src="https://cloud.githubusercontent.com/assets/9967256/20454495/c7bad448-ae42-11e6-8582-a69dd23f1606.png">

Is there a way to do this in electron right now?

* Electron version: 1.4.7
* Operating system: macOS 10.12.1

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
FWIW you are looking for http://electron.atom.io/docs/api/browser-window/#winsetalwaysontopflag-level

**Comment by T-Specht** [comment]
@MarshallOfSound Thanks, the link you provided was really helpful! I won't ask future question in the issues again, thanks for pointing that out. 😉
