### ISSUE TITLE
d3 v4.3.0 not working with Electron

### ISSUE THREAD

**Issue by Jmales** [electron/electron#8020]
I'm using Angular 1.5.8 and D3 on top of electron to draw some graphs.

Tried multiple libraries (e.g. n3-charts and angularJS-nvd3-directives) and every time I got errors including 3rd party libraries.

After many many hours I traced the problem down to the D3 version. The v4.3.0 gives many problems and if I downgrade to v3.5.3 every problem seems to disappear (for now).

Has anyone else had issues using the d3-charting library in Electron?

**Comment by enlight** [comment]
GitHub issues are for bug reports and features requests, please direct questions about using 3rd party libraries in Electron to the [community](https://github.com/electron/electron#community).
