### ISSUE TITLE
window.getPosition() doesn't return new value after moving

### ISSUE THREAD

**Issue by Rokt33r** [electron/electron#8023]
* Electron version: 1.3.9
* Operating system: 10.11.6

### Expected behavior

`window.getPosition()` returns new value after moving.

### Actual behavior

`window.getPosition()` returns same value even after moving.
The new value is returned after its size changed.

### How to reproduce

![nov-20-2016 04-42-56](https://cloud.githubusercontent.com/assets/5865853/20457998/e9192240-aedb-11e6-96c5-e09f6042e78e.gif)

```js
var electron = require('electron')
electron.remote.getCurrentWindow().getPosition()
```

Move the window

```js
electron.remote.getCurrentWindow().getPosition()
```

**Comment by Rokt33r** [comment]
This problem also causes for popup menu(context menu) to appear at a wrong place after moving a window.

**Comment by kevinsawicki** [comment]
Hmm, having trouble reproducing this on 1.4.7, are you able to see it there as well?

![get-position](https://cloud.githubusercontent.com/assets/671378/20492344/35b60242-afc9-11e6-909b-d8e8398d4878.gif)

**Comment by Rokt33r** [comment]
It seems to be a temporary bug. I couldn't reproduce the bug anymore neither. I checked v1.4.7 and v1.3.9.
I think it is good to close. I'll comment here if it happens again.
