### ISSUE TITLE
Native popovers and tooltips?

### ISSUE THREAD

**Issue by yopbeast** [electron/electron#8025]
Hello, is there any support for native popovers and tooltips ?

Popovers could be Tray like? Can I open a tray inside the app clicking on a <a> link ?

Thankks

**Comment by kevinsawicki** [comment]
> Hello, is there any support for native popovers and tooltips ?

There isn't explicit support for native popovers and the tooltip support is limited to what Chrome enables via the `title` attribute on an HTML element.

You can create, position, and customize the look and feel and behavior of arbitrary windows so you can implement popovers in your app in a way that makes sense depending on which platforms you want to support.

Electron does have modal window support as well, http://electron.atom.io/docs/all/#modal-windows

**Comment by yopbeast** [comment]
@kevinsawicki this is actually a very cool solution, thanks!

**Comment by mdings** [comment]
I created a small plugin for that https://github.com/mdings/electron-tooltip
