### ISSUE TITLE
Multiple programs with one shared electron library

### ISSUE THREAD

**Issue by saaroni** [electron/electron#8026]
* Electron version: 1.4
* Operating system: Windwos

### Expected behavior

We are developing various applications that are Electron based and should be delivered to our customers in one installation package.
We would like to name the main exe based on our application name but it seems that this approach will be size consuming as each exe will be around 80MB.

We are currently using one exe which will be our app-launcher but this is just a workaround.

### Actual behavior

We would like to be able to reuse the main Electron capabilities using a dll/shared library while the different application exe files will be smaller and will contain the items that are application specific.

**Comment by MarshallOfSound** [comment]
See https://github.com/electron/electron/issues/5830#issuecomment-243706205
https://github.com/electron/electron/issues/673

For issues discussing this generic issue that others have faced.  The TLDR is that splitting `electron.exe` into `electron.dll` and `electron.exe` is quite difficult and not in the plan at the moment.  The runtime discussion is still ongoing.  Using the same executable for multiple programs introduces a whole heap of issues though.
