### ISSUE TITLE
There was an error with webview.send ( 'ping') and webview.addEventListener ( 'ipc-message', callback)

### ISSUE THREAD

**Issue by guguji** [electron/electron#8028]
Hello, Excuse me.
I have a problem, ipcRenderer.on () did not receive a message when I executed webview.send ( 'ping'); and when I executed ipcRenderer.sendToHost ( 'pong'), webview.addEventListener ( 'ipc- Message ', callback) did not receive a message.
Here's the document I'm looking at: https://github.com/electron/electron/blob/master/docs-translations/en/api/web-view-tag.md#event-ipc-message
I do not know why, I'm confused.
So I come to seek your help, where I was wrong? In addition, the guest page refers to what page? Here is my code:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
</head>
<body>
    <webview id="foo" src="https://github.com/electron/electron"></webview>
</body>
<script>
    var webview = document.getElementById("foo");
    webview.addEventListener('dom-ready', function () {
        webview.openDevTools()
        // In embedder page.
        webview.addEventListener('ipc-message', function (event) {
            console.log(event.channel)
            // Prints "pong"
        })
        webview.send('ping')
    });


    var ipcRenderer = require('electron').ipcRenderer
    ipcRenderer.on('ping', function () {
        debugger
        ipcRenderer.sendToHost('pong')
    })
</script>
</html>
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW you appear to misunderstand the web-view API's.  `ipcRenderer.sendToHost` only works from **within** the webview.  I.e. from a preload script
