### ISSUE TITLE
Add API to get top bar height on macOS

### ISSUE THREAD

**Issue by fritx** [electron/electron#8029]
Hi,

I can't find an API to get Apple's menubar height nor window topbar's height, so I could calculate the window size well, even when I'm using `useContentSize: true` in BrowserWindow.

Maybe electron could expose it also?

http://stackoverflow.com/questions/2867503/height-of-the-apple-menubar

* Electron version: any
* Operating system: MacOS

**Comment by MarshallOfSound** [comment]
Can't you just use something like

```js
mainWindow.getSize()[1] - mainWindow.getContentSize()[1]
```

Or am I missing something here?

**Comment by fritx** [comment]
Yeah thanks for your reply @MarshallOfSound .. but I need the value when I just call `new BrowserWindow()`, where I have no idea about it, unless I have to create one before that?

**Comment by MarshallOfSound** [comment]
@fritx Why do you need the height of the menu bar before you even launch a BW?

**Comment by kenpb** [comment]
Hey @fritx , just an idea, have you tried getting the `electron.screen.getPrimaryDisplay().bounds.height` and subtract the `electron.screen.getPrimaryDisplay().workArea.height`?

**Comment by bengotow** [comment]
@fritx if you want, I think it's pretty safe to hard-code these values. Technically there are system APIs to retrieve the values (`[[[NSApplication sharedApplication] mainMenu] menuBarHeight]`), but the MacOS menubar has been 22px tall since at least Mac OS 8.

**Comment by sindresorhus** [comment]
@bengotow The menubar can now be hidden, so hardcoding would not be a good idea.

**Comment by shubham2892** [comment]
Hi @kevinsawicki, I was wondering whether it would be a good idea to add the API as one of the static methods for BrowserWindow as the bar height would not be specific to BrowserWindow instance. I am working on a PR for the issue. Many Thanks.

**Comment by kevinsawicki** [comment]
> I was wondering whether it would be a good idea to add the API as one of the static methods for BrowserWindow

I think adding it to either the `app` or `screen` modules would be a better fit.

**Comment by shubham2892** [comment]
Hi @kevinsawicki, I have made a PR with the API. Please have a look.

**Comment by kevinsawicki** [comment]
This was fixed by #9572 and released in 1.7.3
