### ISSUE TITLE
App termination via Activity Monitor

### ISSUE THREAD

**Issue by pronebird** [electron/electron#8032]
* Electron version: 1.4.7
* Operating system: macOS

I have the following code that simply hides window on OS X as opposed to killing it or closing app, and then the window appears next time user clicks on icon in dock

```js
var force_quit = false;

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

  mainWindow.webContents.on('did-finish-load', () => {
    mainWindow.show();
    mainWindow.focus();

    if (process.platform === 'darwin') {
      mainWindow.on('close', function (e) {
        if (!force_quit) {
          e.preventDefault();
          mainWindow.hide();
        }
      });

      app.on('activate', () => {
        mainWindow.show();
      });
    } else {
      mainWindow.on('closed', () => {
        mainWindow = null;
      });
    }
  });
```

Quit shortcut then looks like this:

```js
{
        label: 'Quit',
        accelerator: 'Command+Q',
        click() {
          force_quit = true;
          app.quit();
        }
      }
```

However I am not able to terminate the app from Activity Monitor. Is there any event I can use to detect that user is trying to kill the app from Activity Monitor so I can gracefully complete execution?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

> However I am not able to terminate the app from Activity Monitor. Is there any event I can use to detect that user is trying to kill the app from Activity Monitor so I can gracefully complete execution?

AFAIK Activity Monitor attempts to gracefully close your application (which you are preventing) and I don't think there is a way for your application to know who told it to quit.  

As a potential solution you could write a native module to get the focused application and if it is activity monitor make an assumption that activity monitor told you to quit.

**Comment by pronebird** [comment]
@MarshallOfSound Thanks I didn't know about Slack group.

I don't think you're right though. I tried to use 'before-quit' event and it seems to be called when activity monitor attempts to gracefully quit the app.

**Comment by MarshallOfSound** [comment]
@pronebird Yes the `before-quit` event will be fired but I don't see what is incorrect about what I said.  To summarize what I said again.

* Activity Monitor is requesting your app to close (Not forcing it)  *Therefore the normal `quit`, `will-quit` and `close` events will fire inside your app*
* I do not believe there is a way for Cocoa apps to know why they are being asked to quit / who told them to quit  
* A potential solution is you could write a native module to get the focused application and if it is activity monitor make an assumption that activity monitor told you to quit.

**Comment by pronebird** [comment]
Oh right, sorry for being ambiguous. I was looking for a way to know when the app is being asked to quit from outside. Activity Monitor is just a way I attempt to quit it (the easiest way for me).

Thanks for detailed answer!

**Comment by MarshallOfSound** [comment]
@pronebird In which case you want to use that `before-quit` event.  It's the first event in the quit chain and is emitted before it attempts to close all your windows.

http://electron.atom.io/docs/api/app/#event-before-quit

**Comment by pronebird** [comment]
Basically I hide the window when close event arrives. This way I can keep the app running even without windows open and I can always display the window on 'activate'. This seems to be pretty standard behavior on macOS.

Now in order to actually ignore close event and let the window truly close I maintain a flag.

I raise this flag in the following scenarios:

1. User hit cmd+q to quit the app
2. before-quit that seems to be arriving when I request to quit the app from activity monitor 

I did quick test and it seems to be working
