### ISSUE TITLE
 How to printting part of HTML in web page?

### ISSUE THREAD

**Issue by MissCuriosity** [electron/electron#8035]
* Electron version:all
* Operating system:all

### Expected behavior
print part of html in web page

I have already googled and searched in the community,but there is no right answer.I have no choice but to ask the question in issue.

**Comment by MarshallOfSound** [comment]
> I have no choice but to ask the question in issue.

😢 

GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW a cursory google search results in http://stackoverflow.com/questions/12997123/print-specific-part-of-webpage which appears to be what you want to do.  There are two main approaches to this.

* Take the content you want to print, put it in it's own window and print that window  
* Hide all the content you don't want to print and then print the current window (You can do this with `media="print"` stylesheets

**Comment by MissCuriosity** [comment]
Thank you so much ,why i ask questions here is because here is more active than others.

**Comment by MarshallOfSound** [comment]
> Thank you so much ,why i ask questions here is because here is more active than others

FYI although I do answer questions on here I do try to keep track of people who repeatedly ignore the "no questions in the issues section" rule and I won't answer those questions.  In the future please ask on Slack or the Community.
