### ISSUE TITLE
Enforce a aspect ratio when resizing for Windows

### ISSUE THREAD

**Issue by szymonc** [electron/electron#8036]
As in topic. API currently offers fixed ratio only for Mac but not for Windows

**Comment by Cleod9** [comment]
Possible workaround/implementation? (16:9 aspect ratio example)
```js
// 'win' as the BrowserWindow instance
win.on('resize', function () {
  setTimeout(function () {
    var size = win.getSize();
    win.setSize(size[0], parseInt(size[0] * 9 / 16));
  }, 0);
});
```

**Comment by szymonc** [comment]
@Cleod9 did you try this one? We have tried something similar but it causes blinking of window and strange behaviour as it interferes with native resize events. It worked well but just for one edge

**Comment by Cleod9** [comment]
@szymonc Yes, I did try it and it works for my purposes on Windows 7. Doesn't look pretty while resizing but not a deal-breaker for me. Also I had to account for the top/bottom windows borders using `(size[0] + 60) * 9 / 16` (which may not translate to all versions of windows, need to confirm)

**Comment by darkguy2008** [comment]
Almost 1 year and I can't believe this issue hasn't been fixed yet for Windows.

**Comment by darkguy2008** [comment]
After 1 year of nobody watching this... here's my fix. It works and it doesn't flicker, somebody please PR this :)

```

**Comment by bluntspoon** [comment]
Would be nice to see win.setAspectRatio added for Windows? Any plans for this?

**Comment by brett84c** [comment]
```
var resizeTimeout;
mainWindow.on('resize', (e)=>{
    clearTimeout(resizeTimeout);
    resizeTimeout = setTimeout(function(){
        var size = mainWindow.getSize();
        mainWindow.setSize(size[0], parseInt(size[0] * 9 / 16));
    }, 100);
});
```

**Comment by Jacobboogiebear** [comment]
Based upon the upper answers, I made a npm package for this reason!
https://www.npmjs.com/package/electron-aspectratio

**Comment by HaulinOats** [comment]
@Jacobboogiebear Cool, I'll give this a try in the next couple days and report back!

**Comment by HaulinOats** [comment]
@Jacobboogiebear Do you know if there's a way to prevent 'resize' from triggering when just moving the window? I don't want to stop the ability to move the window, but for some reason, Electron triggers a resize on move. It's bizarre.

**Comment by Jacobboogiebear** [comment]
@HaulinOats I don't know how to deal with that but I will put some time in to study it and report back

**Comment by HaulinOats** [comment]
@Jacobboogiebear Turns out doing a window move actually triggers a resize, by default, in Electron.  I opened a [separate thread](https://github.com/electron/electron/issues/18978) about this but it hasn't be resolved or addressed yet.

**Comment by Jip-Hop** [comment]
I'm using this approach to enforce 1:1 ratio on Windows. It works quite nicely for the right and bottom sides. The other two are a bit weird :P
```
mainWindow.on("will-resize", maintainAspectRatio);

function maintainAspectRatio(event, newBounds){
  const win = event.sender;
  if(newBounds.width !== newBounds.height){
    event.preventDefault();

    const currentSize = win.getSize();
    const widthChanged = currentSize[0] !== newBounds.width;
    if(widthChanged){
      win.setSize(newBounds.width, newBounds.width);
    } else {
      win.setSize(newBounds.height, newBounds.height);
    }
  }
}
```

**Comment by Jip-Hop** [comment]
This one works better for resizing from the top and left sides. Still not perfect because the window may start to move when resizing from those sides.

```
mainWindow.on("will-resize", maintainAspectRatio);
function maintainAspectRatio(event, newBounds) {
  if (newBounds.width !== newBounds.height) {
    event.preventDefault();
    
    const win = event.sender;
    const currentSize = win.getSize();
    const widthChanged = currentSize[0] !== newBounds.width;
    if (widthChanged) {
      newBounds.height = newBounds.width;
    } else {
      newBounds.width = newBounds.height;
    }
    win.setBounds(newBounds);
  }
}
```

**Comment by jaehayoo** [comment]
@nornagon @codebytere @MadfishDT  I hope https://github.com/electron/electron/pull/18306 will patch and merge to master.

**Comment by jaehayoo** [comment]
@nornagon I think you have solution since you commented #18306. Do you have any plans?

**Comment by asc0910** [comment]
After spend some time I found this solution.

`if (process.platform === 'win32') {
          let resizeDirection: Directions;

          window.hookWindowMessage(0x0214, (wParam: Buffer) => {
            resizeDirection = wParam.readUIntBE(0, 1);
          });

          window?.on('will-resize', (event, newBounds) => {
            const aspectRatio = this.getAspectRatio(data);
            if (aspectRatio && window) {
              event.preventDefault();
              let temp_width;
              let temp_height;
              const toBounds = { ...newBounds };
              switch (resizeDirection) {
                case Directions.LEFT:
                case Directions.RIGHT:
                  toBounds.height = this.getHeight(
                    aspectRatio,
                    newBounds.width
                  );
                  break;
                case Directions.TOP:
                case Directions.BOTTOM:
                  toBounds.width = this.getWidth(aspectRatio, newBounds.height);
                  break;
                case Directions.BOTTOMLEFT:
                case Directions.BOTTOMRIGHT:
                case Directions.LEFTTOP:
                case Directions.RIGHTTOP:
                  toBounds.width = this.getWidth(aspectRatio, newBounds.height);
                  temp_width = newBounds.width;
                  temp_height = this.getHeight(aspectRatio, temp_width);
                  if (
                    temp_width * temp_height >
                    toBounds.width * toBounds.height
                  ) {
                    toBounds.width = temp_width;
                    toBounds.height = temp_height;
                  }
                  break;
                default:
              }
              switch (resizeDirection) {
                case Directions.BOTTOMLEFT:
                  toBounds.x = newBounds.x + newBounds.width - toBounds.width;
                  break;
                case Directions.LEFTTOP:
                  toBounds.x = newBounds.x + newBounds.width - toBounds.width;
                  toBounds.y = newBounds.y + newBounds.height - toBounds.height;
                  break;
                case Directions.RIGHTTOP:
                  toBounds.y = newBounds.y + newBounds.height - toBounds.height;
                  break;
                default:
              }
              window.setBounds(toBounds);
            }
          });
        }`

**Comment by jaehayoo** [comment]
@asc0910 Great and Awesome!!!

**Comment by swimauger** [comment]
Plenty of great answers in here, thought I would give my two cents anyway. You could use this RatioWindow wrapper of BrowserWindow instead of BrowserWindow to maintain aspect ratio.

**RatioWindow.js**
```JavaScript
const { BrowserWindow } = require('electron');

function __handleWillResize(event, newSize) {
    event.preventDefault();
    event.sender.setSize(newSize.width, parseInt(newSize.width * this.height / this.width));
}

class RatioWindow extends BrowserWindow {
    constructor(options) {
        super(options);
        this.on('will-resize', __handleWillResize.bind(options));
    }
}

module.exports = RatioWindow;
```

**app.js**
```JavaScript
const { app } = require('electron');
const RatioWindow = require('./RatioWindow');

app.whenReady().then(function() {
    let win = new RatioWindow({
        width: 1100,
        height: 800,
        webPreferences: {
            nodeIntegration: true
        }
    });

    win.loadFile(/*.Some File */);
});
```

**Comment by antonfisher** [comment]
I've combined @asc0910 and @swimauger approaches (thanks!), added support for different screen scales on Windows (100-125-150%), and published as a drop-in replacement module for `BrowserWindow`: https://github.com/antonfisher/electron-aspect-ratio-browser-window. The most reliable workaround I've found so far for the issue.

**Comment by 698511175** [comment]
> I've combined @asc0910 and @swimauger approaches (thanks!), added support for different screen scales on Windows (100-125-150%), and published as a drop-in replacement module for `BrowserWindow`: https://github.com/antonfisher/electron-aspect-ratio-browser-window. The most reliable workaround I've found so far for the issue.

if (process.platform === 'win32') {
      this.on('will-resize', this._handleWillResize);
      this.hookWindowMessage(WM_SIZING, (wParam) => {
        this._resizeDirection = wParam.readUIntBE(0, 1);
      });
    }

Are you sure this supports Linxu and MAC OS?
