### ISSUE TITLE
Cannot open Windows 10 Touch Keyboard from Electron

### ISSUE THREAD

**Issue by conteit** [electron/electron#8037]
I'm trying to run the attached project on Windows 10 Pro (latest version available without Windows Insider Program).

Basically it is a fullscreen browser window that navigate to http://www.google.com.
I configured Windows in Tablet mode, in order to let the touch keyboard popup whenever any text field in the page (in this case the query one) gets focused.
Then, I packaged the application with [electron-windows-store](https://github.com/felixrieseberg/electron-windows-store) in order to let electron work as Windows Store application.

When I start the application and Google home page is loaded I'm not able to use the touch keyboard, because it pops up but immediately disappears, like if electron tries to acquire again focus and causes touch keyboard disposal.

I tried also to disable fullscreen mode and setup frame coordinates in order to be as it was in fullscreen, but no success.

Any suggestion?

[TestApp.zip](https://github.com/electron/electron/files/604228/TestApp.zip)

**Comment by kevinsawicki** [comment]
I believe this is very similar to https://github.com/electron/electron/issues/6692 and #6430

There is also an upstream Chrome issue that is being tracked for this in https://bugs.chromium.org/p/chromium/issues/detail?id=497381

Please subscribe to those issues for updates.

**Comment by conteit** [comment]
Since the issues you linked are referring to a bug in Chromium source base that Electron cannot workaround, I tested my issue against the latest Chromium build.

Unfortunately the touch keyboard works as expected (for my use case) both in Google Chrome and Chromium, but not in Electron: it appears when I touch a text field and disappears when I click elsewhere, while in Electron it tries to appear but it fails.

I've reported the same issue to the [electron-windows-store](https://github.com/felixrieseberg/electron-windows-store) project since I wrapped packaged Electron in a Windows Store app that could potentially interfere.

**Comment by MarshallOfSound** [comment]
@conteit Don't forget Electron is currently based on Chromium 53, latest Chromium is almost certainly much higher than that.

**Comment by conteit** [comment]
Sorry.. It is v57.. My bad.

**Comment by conteit** [comment]
Fixed the issue by updating electron dependency.
I've found that the example I've taken base project from was using an old version containing the bug. Now works like a charm.

See [TestApp Repo](https://github.com/conteit/electron-touch-test-app)
