### ISSUE TITLE
Request: Add Command-Line Interface(CLI) as of Cordova

### ISSUE THREAD

**Issue by mainalikishan** [electron/electron#804]
Hello,

It would be great feature and lot easier to work on atom-shell, if it can have CLI as of cordova: 

http://cordova.apache.org/docs/en/4.0.0/guide_cli_index.md.html#The%20Command-Line%20Interface

**Comment by mainalikishan** [comment]
any updates on this?

**Comment by reggi** [comment]
I've gone off building something to assemble my app that uses settings from my apps package.json file. I would love if this existed already. 

I've published some of the functions in this dump repo I have

* [asar](https://github.com/reggi/node-regicide/blob/master/osx-app-asar.js)
* [plist](https://github.com/reggi/node-regicide/blob/master/osx-app-plist.js)
* [icon](https://github.com/reggi/node-regicide/blob/master/osx-app-icon-update.js)
* [codesign](https://github.com/reggi/node-regicide/blob/master/codesign.js)

I have some unpublished stuff that puts it all together a bit, but it's no CLI.

**Comment by xfq** [comment]
See also: https://github.com/atom/atom-shell-starter/pull/53#issuecomment-77476966

**Comment by xfq** [comment]
IIUC the command line tool won't have subcommands similar to:
 
* `cordova platform add/rm/ls`
* `cordova emulate`
* `cordova plugin`

But it will have (let's assume that this tool is called `husk`):

* `husk create`
* `husk run`
* `husk build` (or `husk dist`?)
* `husk help`
* `husk info` (which produces a listing of potentially useful details, such as the version numbers of Chromium, Node.js , and `husk` itself)

Comments?

**Comment by Ikana** [comment]
Hi, i am working on this [sort of tool](https://www.npmjs.com/package/electron-cli), right now it only creates a new project, and I am for any comments and contributions.

**Comment by MarshallOfSound** [comment]
I totally forgot to mention I made something like this for a friend.  https://github.com/MarshallOfSound/electron-forge

```bash
electron-forge init
electron-forge start
electron-forge package
```

**Comment by Ikana** [comment]
Hey @MarshallOfSound maybe we can work together, i think there is still a need to integrate native package building for electron on the tools.

**Comment by MarshallOfSound** [comment]
@Ikana I had windows / macOS / debian package building working locally but I haven't pushed / tested yet as I got distracted by other things (exams 😢 ).

**Comment by Ikana** [comment]
@MarshallOfSound, I could help you with the testing

**Comment by codebytere** [comment]
As `electron-forge` is now the standard for this, issues related to it are probably better posted on that repo. This issue has been stale for a while, i'm going to go ahead and close it.
