### ISSUE TITLE
setAsDefaultProtocolClient on windows 7

### ISSUE THREAD

**Issue by kof** [electron/electron#8042]
The problem is reproducible using the ElectronAPIDemos package version 1.2.0, just cloned from master.

* Electron version: 1.4.7
* Operating system: Windows 7 Ultimate Service Pack 1, 32 bit, using Parallels

<img width="1275" alt="screen shot 2016-11-21 at 9 19 09 pm" src="https://cloud.githubusercontent.com/assets/52824/20499242/eb3c1ae0-b030-11e6-8bae-e08e69f15338.png">

<img width="1274" alt="screen shot 2016-11-21 at 9 30 44 pm" src="https://cloud.githubusercontent.com/assets/52824/20499443/d096b6b8-b031-11e6-9aba-20228467b3e9.png">

### Expected behavior

When clicking on the link like demo says, electron app should be opened.

### Actual behavior

Internet Explorer shows an error. 

```
Error launching app
Unable to find Electron app at \\psf\Home\Desktop\electron-api-demos:\open
Cannot find module ' \\psf\Home\Desktop\electron-api-demos:\open'
```
### How to reproduce

1. Clone the repo https://github.com/electron/electron-api-demos
1. npm i && npm start
1. go to protocol-link example in the app, it opens a page in the browser (it happens in IE11 and in Chrome with slightly different error description)
1. click on the link

**Comment by zeke** [comment]
Hi @kof. This is an issue with the API demo app. Can you please re-open this issue at https://github.com/electron/electron-api-demos/issues/new ?

**Comment by kof** [comment]
I don't believe so because I actually got that issue first in my application and then tried to reproduce it in the demo. I use the API exactly the way it is described in the docs. But yeah, I willl repost it there.

**Comment by kof** [comment]
Here we go https://github.com/electron/electron-api-demos/issues/273
