### ISSUE TITLE
browserWindow.show and focus is unable to bring app window into focus (Windows?)

### ISSUE THREAD

**Issue by MrBlenny** [electron/electron#8044]
* Electron version: 1.4.4
* Operating system: Windows 10

### Description
browserWindow.show() & focus() are unable to bring a browerwindow to the fore.
Instead, the application icon just flashes in the taskbar.
![Demo](https://i.imgur.com/fvhlS5Q.png)

In this example - I open chrome and I want to be able to bring the electron application back into focus pro grammatically. I'm not sure whether this is an electron problem or a limitation of windows?

### How to reproduce
Set a an interval that includes browerWindow.show and focus:
``` javascript
setInterval(()=>{
  browserWindow.show();
  browserWindow.focus();
},1000)
```
Open another application and you should see that the electron app will not come it focus, instead the icon will flash.

**Comment by kevinsawicki** [comment]
Can you include the options you are passing to the `BrowserWindow` constructor? Or a small reproduction app that is a fork of https://github.com/electron/electron-quick-start that showcases the issue? Thanks.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
