### ISSUE TITLE
Crash Reporter in Mac uses submit-url from the main process for crashes in Renderer process

### ISSUE THREAD

**Issue by ramya-rao-a** [electron/electron#8045]
Spawned from the investigations in #7474.

https://github.com/ramya-rao-a/electron-quick-start/tree/crash-testing-submiturl is forked from the electron quick start example with the below changes

- In the main process crash reporter is initialized on ready
- In the renderer process there are 2 buttons. 1 for initializing the crash process, the other for creating the crash
- The submit-url and metadata configured are different in the 2 processes.
- Change the submit-url to your own local crash server. Just make sure they are different.
- Now run the app, click on the button initialize renderer crash process and then click on the crash button. Do this in both Mac and Windows

In Mac, you will see a crash report submitted to the crash server configured for the main process with the metadata from the renderer process
In Windows, you will see the right behavior i.e crash report submitted to the crash server configured for the renderer process with the metadata from the renderer process.

Furthermore, now if you remove the crash reporter initialization code from the main process and try again, Mac does not do anything. Windows continuous to report crash to the right place with the right data

**Comment by ramya-rao-a** [comment]
@kevinsawicki Do you know why we start the crashed handler in Mac only in the main process?
https://github.com/electron/electron/blob/master/atom/common/crash_reporter/crash_reporter_mac.mm#L41 ?

**Comment by kevinsawicki** [comment]
@ramya-rao-a it looks like that line is from the original port of the macOS crash reporter from breakpad to crashpad, https://github.com/electron/electron/commit/4e2f242ad0209515639c406542eaabfc2f5d556f

**Comment by kevinsawicki** [comment]
> In Mac, you will see a crash report submitted to the crash server configured for the main process with the metadata from the renderer process

I'm not sure if crashpad supports different submit URLs for different processes.

> Furthermore, now if you remove the crash reporter initialization code from the main process and try again, Mac does not do anything. 

On mac you have to start the crash report in the main process if you want to report crashes in any of the render processes I believe, there is note in http://electron.atom.io/docs/api/crash-reporter/#crashreporterstartoptions about it.

**Comment by ramya-rao-a** [comment]
Yes, there is a note

>To enable the crash collection feature, you are required to call the crashReporter.start API to initialize crashpad in the main process and in each renderer process from which you wish to collect crash reports.

Now that I read it again, it does come across that we HAVE to initialize it in main process even if we are interested in crashes only from the renderer process (totally hypothetical case).

I misunderstood it to mean that we ONLY need to initialize in the process from which we wish to collect crash reports.

> I'm not sure if crashpad supports different submit URLs for different processes.

If crashpad does not support this, am ok with closing this issue.
Our scenario is not to use different submit urls for main vs renderer. Since I stumbled on it, thought I should log it.

**Comment by kevinsawicki** [comment]
> Now that I read it again, it does come across that we HAVE to initialize it in main process even if we are interested in crashes only from the renderer process (totally hypothetical case).

> I misunderstood it to mean that we ONLY need to initialize in the process from which we wish to collect crash reports.

Yeah, it is definitely confusing and needs to be rewritten to make it clear what you need to do on macOS. Please feel free to open a pull request to update the docs if you'd like.

> If crashpad does not support this, am ok with closing this issue.

I don't think it does. From the docs about why `StartHandler` is only called from the main process:

> Child processes do not need to call StartHandler() or be aware of Crashpad in any way. The Crashpad handler will receive crashes from child processes that have inherited it as their exception handler even after the process that called StartHandler() exits.

https://cs.chromium.org/chromium/src/third_party/crashpad/crashpad/client/crashpad_client.h?q=crashpad::CrashpadClient&sq=package:chromium&dr=Ss&l=59

Closing this out.
