### ISSUE TITLE
Unable to open MHTML file after save

### ISSUE THREAD

**Issue by sweinertjr** [electron/electron#8048]
Hi-

I'm having an issue when opening an MHTML file with Electron, that was originally saved via Electron. It seems to just show me a blank white page. As an example: [Here is the MHTML for geico.com](https://s3.us-east-2.amazonaws.com/cdn.formulaic.io/uploads/html/-KX9_-osY2mLtxdct5vA-0.mhtml)

Does Electron simply not support opening it's exported MHTML files, or am I missing something? It opens fine in Chrome. I'm using https://www.npmjs.com/package/electron-open to test.

Thanks

**Comment by deepak1556** [comment]
MHTML served over file scheme are only supported uptil now. You need to wait for chrome 54 upgrade in Electron, for loading mhtml files served over http(s) schemes. Related upstream CL https://codereview.chromium.org/2234543002 .
