### ISSUE TITLE
Underlying OS chrome is revealed by showMessageBox() on Ubuntu in kiosk mode

### ISSUE THREAD

**Issue by mikehall314** [electron/electron#8050]
I have an app in kiosk mode, which shows an error message with showMessageBox() if the app cannot be authenticated against the remote server.  On Windows and Mac, this is no problem.  However, on Unity on Ubuntu, when showMessageBox() is called, it reveals the title bar of the application window, and the Launcher on the left hand side.

* Electron version: 1.4.7
* Operating system: Ubuntu 16.04 LTS Desktop

### Expected behavior

Message Box rendered over the top of the kiosk app

### Actual behavior

Message Box rendered with Launcher and title bar visible

### How to reproduce
Checkout this repo on Ubuntu 16.04 LTS Desktop:
https://github.com/mikehall314/dialog-bug

run `electron app` and wait three seconds for the dialog to appear

**Comment by zcbenz** [comment]
The behavior of popup dialog is defined by the desktop environment you use, to achieve a real kiosk environment, you should replace your desktop environment with one that can be configured in kiosk mode.
