### ISSUE TITLE
Windows 10 blurry, with desktop scaling on 150%

### ISSUE THREAD

**Issue by Ciantic** [electron/electron#8062]
* Electron version: 1.4.8
* Operating system: Windows 10 Anniversary Edition (build 1607)

### Expected behavior

When dragging a window to hidpi desktop, e.g. 150% scaling, it should scale it correctly. 

### Actual behavior

It does not scale, the window remains blurry.

Google Chrome stable version (54.0.2840.99 m (64-bit)) works correctly, if I drag window (any window e.g. even the developer tools window) it changes the scaling correctly as soon as it gets to the desktop with different scaling factor.

**Comment by Palabola** [comment]
Confirmed really annoying bug!

**Comment by martinsuchan** [comment]
Google fixed the HiDPI issues in Chromium 54 as far as I know, latest Electron 1.4.12 is still based on Chromium 53.
Fixing the HiDPI issues should really be high priority, because it makes many apps unusable on screens with different DPI.
