### ISSUE TITLE
Add semicolon as an available accelerator key code

### ISSUE THREAD

**Issue by dcalhoun** [electron/electron#8066]
Is it possible to allow the use of the semicolon key as a key code? If so, would the project be open to adding it?

I ask because I previously used <kbd>Ctrl</kbd>+<kbd>;</kbd> as a hotkey to reveal iTerm2. After switching to [Hyper.app](https://hyper.is), that hotkey is no longer available, as it is not a supported [accelerator key code](https://github.com/electron/electron/blob/v1.4.8/docs/api/accelerator.md#available-key-codes).

**Comment by danhp** [comment]
<kbd>;</kbd> isn't explicitly listed as an accelerator but it is already supported. We simply didn't list all the supported punctuation and simply put in `etc.`. I would have to guess that your issue is with the Hyper app itself.

**Comment by dcalhoun** [comment]
Ah, ok. I missed the etc. Thanks for the info!
