### ISSUE TITLE
Google Blockly create variables issue (prompt() is and will not be supported.)

### ISSUE THREAD

**Issue by altjz** [electron/electron#8067]
* Electron version: v1.4.7
* Operating system: macOS 10.12.1

### Expected behavior
I have a project on Blockly + Electron.
Google Blockly use window.prompt() for creating variable on default. I know window.prompt() is not supported by Electron. Then I find Google Blockly supports to override the window.prompt() . 

This is the Google official demo [custom-dialogs](https://blockly-demo.appspot.com/static/demos/custom-dialogs/index.html). It works pretty well.

### Actual behavior

But I try to use this demo in electron. Electron still catch this. 

`Uncaught Error: prompt() is and will not be supported.`

### How to reproduce
I'm using the official [Google Blockly](https://github.com/google/blockly) + [electron-quick-start](https://github.com/electron/electron-quick-start) , And I didn't change anything on that. Except load the `demos/custom-dialogs/index.html` in main.js.

I have no idea why electron still block the window.prompt() even I override it.

**Comment by altjz** [comment]
sorry, I found out I am using the wrong version of Google Blockly. Closed.

**Comment by leandrolanzieri** [comment]
@altjz Hello, I am having the same problem. What Blockly version got it to work?

**Comment by altjz** [comment]
Hi @leandrolanzieri , Currently I'm using [node-blockly](https://www.npmjs.com/package/node-blockly) 1.0.16 to manage the blockly. So far it's working perfect.

**Comment by mojoaxel** [comment]
`window.propmt` is not supported in electron. see #472

**Comment by leandrolanzieri** [comment]
I managed to override the library function and use one of my own:
```typescript
Blockly.prompt = (a, b, c) => {
      this.promptModalDesc = a; // Message description
      this.promptCallback = c; // Callback function
      this.promptModal.show(); // Show a modal
    };
```

**Comment by eryckpedro** [comment]
@leandrolanzieri Can you please tell me how exactly do you use this code of yours provided to **rename a variable as used by Blockly**? I'm fairly new to `javascript` and certainly don't want to mess with Blockly's core files...

**Comment by OmarMoMorgan** [comment]
i still can't override this no matter what I do it still gives me the same error what could be the possible reason, I tried to make sure that I include the demo code provided after everything loads or before but neither seem to work, the functions in the demo are not invoked, any help would be greatly appreciated
