### ISSUE TITLE
app.getPath('userData') returns path based on "packageName" if present in package.json and NOT "name"

### ISSUE THREAD

**Issue by OwenBrotherwood** [electron/electron#8073]
* Electron version: "version": "1.4.9",
* Operating system: Windows 10

### Expected behavior
With reference to, [api for app.getPath('userData')](https://github.com/electron/electron/blob/b036fdfee0beb4c1fdc5d53fbad4fa113009e997/docs/api/app.md#appgetpathname)

> userData The directory for storing your app's configuration files, which by default it is the appData directory appended with your app's name.

"app's name" is expected to be "name" in package.json

ie: expected is
console.log(app.getPath('userData') returns path based on package.json "name"
In the case of electron default_app, "electron"
https://github.com/electron/electron/blob/b036fdfee0beb4c1fdc5d53fbad4fa113009e997/default_app/package.json#L2

### Actual behavior

console.log(app.getPath('userData') returns path based on package.json "productName".
In the case of electron default_app, "Electron"
https://github.com/electron/electron/blob/b036fdfee0beb4c1fdc5d53fbad4fa113009e997/default_app/package.json#L3

### How to reproduce

change and/or remove entry for "productName" in the package.json of default_app.

### Discussion

"productName" is not a "required" if one refers to npm https://docs.npmjs.com/files/package.json
"name" is required.
"productName" can contain characters that are not useable in a path: there is no reference for any criteria for any such constraint.

I suggest that electron ONLY uses "name" as a basis for the path in order to avoid unnecessary requirements for "productName" having no characters that are unsuitable for a path

**Comment by zcbenz** [comment]
`productName` is used in Electron because in most cases app would use a full capitalized name, while the `name` filed is usually a short lowercased one.

I'm closing this since this behavior has already been documented in `app.getName()`'s doc.
