### ISSUE TITLE
Improve dialog.showOpenDialog() doc with properties set to ['openFile', 'openDirectory'] on Linux or Windows

### ISSUE THREAD

**Issue by popod** [electron/electron#8075]
On Linux or Windows who don't support `dialog.showOpenDialog()` with option "property" set to `['openFile', 'openDirectory']` what is the current behavior ?

1. The dialog will always be an "openDirectory" dialog ?
    - if YES: it will be useful to provide an option to chose witch of "openFile" or "openDirectory" dialog will be used

2. The dialog will always be set with the last array string item witch in this case is "openDirectory" dialog ?
    - if YES: you should better explain this in the doc of [dialog.showOpenDialog()](http://electron.atom.io/docs/api/dialog/#dialogshowopendialogbrowserwindow-options-callback)

**Comment by enlight** [comment]
I think the docs already say too much about this, they should really just say "Don't create dialogs with `['openFile', 'openDirectory']` on Windows or Linux" and leave it at that.

**Comment by popod** [comment]
@enlight Thanks for reply ! But what is the default behavior (1 or 2) ?

And what if I want let the user select files and folders on compatible platform (with `['openFile', 'openDirectory']`) and provide a default behavior on others OS (in this case Windows and Linux)  ?

It will be more understandable to clearly write this in the doc and more better to let the developper chose this behavior. With an default dialogBox to display on unsupported platforms or by using the last item of the "property" array.

**Comment by popod** [comment]
@enlight Any updates on this ? What about my proposition in my latest post ?

**Comment by zcbenz** [comment]
Having it explicitly documented something as not supported is already enough, because any behavior may happen when using an supported combo and the final behavior depends on which platform you use  and which version if the platform, it is impractical to list all possibilities.
