### ISSUE TITLE
programmatically close a dialog.showMessageBox() modal ?

### ISSUE THREAD

**Issue by popod** [electron/electron#8076]
Is their a way to programmatically close a dialog.showMessageBox() ?

Something like that:
```
var modal = dialog.showMessageBox()

modal.close()
```

**Comment by enlight** [comment]
No, there isn't, the relevant feature request is tracked by #5577

**Comment by jairodealmeida** [comment]
Is possible use BrowserWindow and create a dialog 
[Example](https://pastebin.com/nurBwGf1)
See
