### ISSUE TITLE
Wii U USB GameCube Adapter returns NaN axes

### ISSUE THREAD

**Issue by yonicstudios** [electron/electron#8080]
* Electron version: 1.4.8
* Operating system: Windows 10 Anniversary Edition x64

This bug has also been reported on Chromium and Chrome Dev. Firefox does not experience this.

### Expected behavior
The gamepads connected should return a numerical value ranging from -1 to 1 on their axes

### Actual behavior
The gamepads' axes return NaN.

### How to reproduce
1. Connect a Wii U USB GameCube Adapter to the computer.
2. Connect a GameCube controller in the adapter's port 1.
3. Download Wii U USB GameCube Driver. If required, download as well Zading and vJoy.
4. Install Wii U USB GameCube Driver.
    a. When Zadig is prompted, replace original driver with WinUSB.
    b. When vJoy is promopted, follow vJoy's installation process with the default configuration. If vJoy installs succesfully, skip to step 5.
    c. If vJoy installation fails, run vJoy independent installer again.
    d. If the failure persists, delete folder %userprofile%/usb_driver and run the installer again. Repeat d. until installation succeeds.
5. Run Wii U USB GameCube Driver/adapter. When prompted, press Start.
6. Run Chromium or Chrome dev channel, and go to https://ericlathrop.github.io/html5-gamepad/
7. Press any of the GameCube controller buttons.

**Comment by enlight** [comment]
Closing this since it appears to be a Chromium issue tracked by https://crbug.com/668516
