### ISSUE TITLE
Browser Window SetSize to height greater then 16384 causes white screen

### ISSUE THREAD

**Issue by jimmaay** [electron/electron#8087]
* Electron version: 1.4.8
* Operating system: Windows 10 x64

### Expected behavior

 setSize on browser window to a height greater then 16384 should work

### Actual behavior

 setSize on browser window to a height greater then 16384 causes screen to go white and electron stops working

### How to reproduce

1. Open browser-window with any URL and set the maxHeight to 20000 or greater
2. setSize(100,16385)

**Comment by jimmaay** [comment]
Opening a browser-window with height>16384 has no issues though but if I call setSize or setContentSize to >16384 (even if the initial height was bigger) it stops working

**Comment by spartucus** [comment]
I tried on my PC for both electron v1.3.6 and v1.4.8, didn't reproduce.

- Electron Version: 1.3.6, 1.4.8

- OS: Windows10 Enterprise 1607.14393

**Comment by jimmaay** [comment]
What is the exact code you are running?

**Comment by jimmaay** [comment]
Sorry forgot to mention to set maxHeight to 20000 or greater on the BrowserWindow

**Comment by jimmaay** [comment]
Here are the exact 3 lines which cause it to go white:

```
win=new BrowserWindow({maxHeight:30000});
win.loadURL('http://google.com');
win.setSize(800,16385);
```

**Comment by jimmaay** [comment]
It's interesting how at exactly 16KB is crashes. So it seems like a limit or overflow issue.

**Comment by spartucus** [comment]
@jimmaay yeah, I tried your code except URL part, but i don't think that matters. window flashed white screen when start, but showed normally.
`mainWindow = new BrowserWindow({ 
      maxHeight: 30000
    });
  mainWindow.loadURL('file://' + __dirname + '/index.html');
  mainWindow.setSize(800,16385);`

**Comment by spartucus** [comment]
@jimmaay It seems that `maxHeight` is related. Try remove the `maxHeight` property, the problem disappers.

**Comment by jimmaay** [comment]
Try using http://google.com or any external URL. Mine has the issue whether it is loading an external or an internal file. If I remove the maxHeight then the actual height maxes out at around 2400 when I change the viewport.

**Comment by birdsarah** [comment]
In case it's useful, there are a couple of similar threads on the chrome headless-dev mailing list: 
https://groups.google.com/a/chromium.org/forum/?utm_medium=email&utm_source=footer#!searchin/headless-dev/16384

https://groups.google.com/a/chromium.org/d/msg/headless-dev/t0ixeHXCzK0/nQLDW8cSAgAJ

**Comment by jimmaay** [comment]
Thanks Sarah, that was extremely useful. Is there a way to increase this limit somehow? I tried using device emulation as suggested and even though I can get a emulated height bigger then 16384 the capture is of the visible screen so it basically just scales it down. Unless there is a way to take a screenshot of the emulated viewport without scaling?

**Comment by birdsarah** [comment]
Sorry I don't have more info @jimmaay. I'll let you know if I find anything more out though.

**Comment by jimmaay** [comment]
No problem, thanks for the help

**Comment by kevinsawicki** [comment]
> Opening a browser-window with height>16384 has no issues though but if I call setSize or setContentSize to >16384 (even if the initial height was bigger) it stops working

So setting the size larger than 16384 in the `BrowserWindow` constructor options does work properly?

**Comment by jimmaay** [comment]
Hi Kevin, setting height to greater then 16384 in the BrowserWindow constructor actually does not set the height to greater then the height of the height of a maximized window (height of screen minus bottom toolbar in windows). A second setSize or setContentSize is required to set it bigger up to 16384 at the moment. If it is larger then 16384 it will cause the window will go white and execution will stop working.

**Comment by kevinsawicki** [comment]
> If it is larger then 16384 it will cause the window will go white and execution will stop working.

Okay, thanks for clarifying 👍

**Comment by jimmaay** [comment]
Looks like a texture size limit - https://cs.chromium.org/chromium/src/cc/resources/resource_provider.cc?rcl=1464366759&l=448-454

Anyone know a way to increase this or a workaround?

**Comment by zcbenz** [comment]
Tested it on v1.7.x and could not reproduce this anymore.

**Comment by jimmaay** [comment]
Unfortunately on v1.7.9 the issue still occurs. To quickly test open a long page which can be generated with a for loop:

`var output='';var i=20000;while(i--){output+=i+'<br/>';}document.write(output)`

Then open the page with electron and run `setSize(800,16385);`
