### ISSUE TITLE
'console-message' listener with multiple arguments

### ISSUE THREAD

**Issue by snanke19** [electron/electron#8090]
* Electron version:  1.4.2
electron-builder@5.35.0
electron-packager@7.7.0
electron-prebuilt@1.3.9
electron-rebuild@1.4.0
* Operating system: Windows 10

### Expected behavior

In Javascript you can chain messages together in the console.log function by adding multiple arguments.  I would like to be able to capture this functionality in the webview 'console-message' listener.

<i>console.log("testing",4,new Object());</i>

### Actual behavior

When re-directing messages to the webview like so...

<i>webview.addEventListener('console-message', function(e) { console.log(e.message); });</i>

The listener event message only gets the first argument sent from the console.log in the webview. From my example, it would only print "testing".

### Things I have tried

<ul>
<li>
I looked around inside the event object to see if the other arguments had been captured in another part of the object (outside of e.message), but I didn't see anything. 
</li>
<li>
I tried sending, <i>webview.addEventListener('console-message', function(a,b,c...) </i> the extra arguments were undefined.
</li>
</ul>

### Note
I could use the + operator instead of sending multiple arguments, but the results would not be the same. For instance, sending an Object allows you to expand the Object.

**Comment by zcbenz** [comment]
This is a bug of Chromium and they decided to not fix it:
https://bugs.chromium.org/p/chromium/issues/detail?id=365427

I'm closing this as won't fix since we can not work around it on Electron's side.

**Comment by sindresorhus** [comment]
@zcbenz This also affects testing with Spectron: https://github.com/electron/spectron/issues/282 Is there really no way for Electron to work around it?

**Comment by sindresorhus** [comment]
@zcbenz @zeke @codebytere The Chromium team has said they're open to an outside patch fixing this. The referenced Chromium issue is reopened: https://bugs.chromium.org/p/chromium/issues/detail?id=365427#c18 In case you have the resources to do something about it.

**Comment by sindresorhus** [comment]
// @MarshallOfSound
