### ISSUE TITLE
Smaller apps, shared library installed

### ISSUE THREAD

**Issue by oxydron** [electron/electron#8093]
* Electron version: whatever
* Operating system: whatever

### Expected behavior
I think every electron app should be smaller. 

### Actual behavior
Every app has at least about 40mb.

### How to reproduce
Why not do like Adobe Air or .Net, that the shared lib for every electron app should be installed once, and every app uses it.

**Comment by MarshallOfSound** [comment]
See #673 for a discussion on this concept

**Comment by oxydron** [comment]
Ok, sorry, I couldn't find the topic when I created this one.
