### ISSUE TITLE
How to get profiles data

### ISSUE THREAD

**Issue by huangjianbo** [electron/electron#8094]
**can i through the way of the script？ save content profiles used for performance tests**

![image](https://cloud.githubusercontent.com/assets/5361668/20695157/f1bb6d40-b624-11e6-9610-6cf6cca15b02.png)

**Comment by kevinsawicki** [comment]
You should be able to do this by directly scripting against Chrome's dev tools API, it isn't Electron specific. From your dev tools extension you can access any of the APIs provided by the Chrome dev tools.

You may want to take a look at something like https://github.com/paulirish/automated-chrome-profiling for examples.
