### ISSUE TITLE
remote.autoUpdater.setFeedURL blocking on OSX

### ISSUE THREAD

**Issue by dustinblackman** [electron/electron#8099]
Electron version: OSX 1.4.10
Operating system: OSX 10.12.1

### Expected behavior

`autoUpdater.setFeedURL()` should call and then continue with the execution process.

### Actual behavior

`autoUpdater.setFeedURL()` blocks, however the developer console is still usable and the UI is still functioning showing that the application isn't frozen.

### How to reproduce

This issue only seems to happen on OSX, as on Windows Electron 1.4.10 the same code works perfectly. The express server I have running never logs a request, so the issue is somewhere before the request is made.

```javascript
import { remote } from 'electron';

if (process.platform === 'darwin') {
  console.log('before'); // Logs to console just fine
  remote.autoUpdater.setFeedURL('http://127.0.0.1:8000/latest');
  console.log('after'); // Is never reached
} else {
  remote.autoUpdater.setFeedURL('http://127.0.0.1:8000/releases');
}
```

**Comment by kevinsawicki** [comment]
Do you know if `remote.autoUpdater.setFeedURL` is throwing an exception? Do you get any errors logged when running it directly from the dev tools Console?

Is the `'after'` never logged or just eventually logged?

**Comment by dustinblackman** [comment]
You're right, it was throwing an exception but with no way of knowing when using `remote`. The exception was my application wasn't signed. I only found out by attempting the same logic within the index of my electron project, and seeing the error there.

I'll keep this open as the behaviour from remote doesn't seem optimal. Otherwise feel free to close. Thanks!

**Comment by kevinsawicki** [comment]
> You're right, it was throwing an exception but with no way of knowing when using remote, as the dev console tools log was empty. 

Did your application have a `window.onerror` handler and/or `process.on('uncaughtexception')` handler? It would be great to know more in case there is an issue in the `remote` module. Only uncaught errors or explicitly logged errors (`console.error`) go to the dev tools.

**Comment by dustinblackman** [comment]
Ah you're right. Winston has a `process.on('uncaughtexception')` handler, and wasn't properly passing the error to logs. With it disabled, error ended up in the dev tools just fine. Good catch, thanks for the help.
