### ISSUE TITLE
webContents.send fails when the object is large

### ISSUE THREAD

**Issue by kyssproject** [electron/electron#8101]
When trying to use 

`BrowserWindow.webContents.send('test',data)`

It fails if data is large. It doesn't when data is a small object. When it fails it doesn't throw any message, but nothing is executed beyond this instruction.

The object I am trying to pass has more than 10,000 items

* Electron version: 1.4.8
* Operating system: Win10

[stackoverflow question](http://stackoverflow.com/questions/40882314/electron-fails-when-sending-a-large-object-with-browserwindow-webcontents-send-b)

**Comment by deepak1556** [comment]
Duplicate https://github.com/electron/electron/issues/7286
