### ISSUE TITLE
Electron App Build On windows

### ISSUE THREAD

**Issue by raviranjan528** [electron/electron#8102]
Actually i m building a project in electron and i am able to build . but after building its giving me  lot of files but i want only one file that is exe file. please help

**Comment by joveth** [comment]
You can use electron-builder .
I build exe file by it

Add code to package.json like this :

  "build": {
    "appId": "you app id",
    "win": {
      "title": "you app title ",
      "version": "the version",
      "target": "nsis",
      "authors": "xxx ",
      "iconUrl": "https://raw.githubusercontent.com/electron/electron-api-demos/master/assets/app-icon/win/app.ico",
      "file":["**/*","!**/node_modules/*/{README.md,README,readme.md,readme,test}","!**/node_modules/.bin"],
    }
  }

 And then run  :
`./node_modules/.bin/build  --platform win32 --arch x64`

Well may be  different ，because I worked on mac ,and build for windows.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

You can use `electron-packager` and `electron-winstaller` to generate an installable exe file.

**Comment by raviranjan528** [comment]
Thanku @joveth . actually i am able to build exe file for my project but the problem is it is giving lots of file. if single file deleted from there its stop working . i need only exe file.  


Sorry @MarshallOfSound
