### ISSUE TITLE
CPU high usage with electron on windows 

### ISSUE THREAD

**Issue by joveth** [electron/electron#8103]
* Electron version: 1.4.4
* Operating system:windows 7

My windows 7 is a virtual machine. 2GB ,1 kernel

Well, I worked on mac with Electron,make a demo to send data to server every 60 second,write database using node-sqlite3,every thing run ok on my mac and I packed an installer of nsis with electron-builder@7.24.1.
When I installed in windows the cpu got 100% and no response for a long time .

As I download the electron-api-demo and install in windows ,It's run smoothly .
So I think may be the node-sqlite slow down the process ,I checked my code  found that only the first time need to write database ,the left will not.
May be the log4js ,so I delete all log code ,but still.

The function be called by setTimeout  every 60 second after the Ajax post send over .

So,where is the problem?

Need helps.Thanks for a lot.

Forgive my poor english.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

This sounds like an issue with your code / a module you are using not Electron itself.
