### ISSUE TITLE
Can't create window larger than display dimensions, need to resize.

### ISSUE THREAD

**Issue by mikeys** [electron/electron#8104]
* Electron version: 1.4.1
* Operating system: Ubuntu 16.04.1 (using Xvfb)

### Expected behavior

```javascript
new BrowserWindow({ width: /*<wider than display width>*/, height: /*<taller than display height>*/, enableLargerThanScreen: true })
```
should create a window with the specified dimensions (which are larger than the display dimensions).

### Actual behavior

The new window which is created is bounded to the size of the display (e.g. `1920x1080` in my case).
I then need to use `win.setSize()` in order to reach the desired window size.

### How to reproduce

Make sure you're running Xvfb and the right Display:
```bash
Xvfb  :99 -screen 0 1920x1080x24 -dpi 100 &
export DISPLAY=:99
```

Code example:
```javascript
let win = BrowserWindow({width: 5000, height: 5000, enableLargerThanScreen: true })
console.log(win.getSize())  // => [ 1919, 1079 ]

win.setSize(5000, 5000)
console.log(win.getSize())  // => [ 5000, 5000 ]
```

**Comment by danielkalen** [comment]
Able to reproduce this on MacOS 10.12.3 (without Xvfb ofcourse)

**Comment by zcbenz** [comment]
For Linux the initial size of window is only a hint passed to window manager, and some window managers may decide to not create a window that can be larger than screen initially. I'm afraid this is not something we can fix on Electron's side, and I'm closing this as won't fix.
