### ISSUE TITLE
autoUpdater.quitAndInstall() fails on macOS with "Permission Denied"

### ISSUE THREAD

**Issue by esonderegger** [electron/electron#8106]
* Electron version: 1.4.7
* Operating system: macOS 10.12.1

### Expected behavior

After successfully downloading a new version from the nuts server (the 'update-downloaded' event is emitted), the user is prompted with a modal asking if they want to quit and install the new version. When they click that button, the autoUpdater.quitAndInstall() method is called. Then, the application quits, installs the new version, and the new version of the application is started.

### Actual behavior

When the user clicks "quit and install", the application quits, and then shortly starts up again in the old version of the application.

Investigating in the ~/Library/Caches/<AppId>.ShipIt folder, the ShipIt.stderr.log file contains lines like:

    2016-11-30 12:21:51.265 ShipIt[80835:4997925] Installation error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={NSLocalizedDescription=Permission denied}

### How to reproduce

To view this issue in action, download the version of my electron app in the version 1 release older that the current release: [https://github.com/esonderegger/plaster/releases/download/v0.1.7/Plaster-0.1.7.dmg](https://github.com/esonderegger/plaster/releases/download/v0.1.7/Plaster-0.1.7.dmg)

Te see the relevant code (has not changed in the last few releases): [https://github.com/esonderegger/plaster/blob/master/appsrc/js/plaster-updater.js](https://github.com/esonderegger/plaster/blob/master/appsrc/js/plaster-updater.js)

**Comment by degif** [comment]
Confirming that this is still happening with Electron 1.4.12 on macOS 10.12.1.
The `ShipIt_stderr.log` yields the same error. At `~/Library/Caches/com.app.app.ShipIt/ `there is even a directory `update.xxx` that contains the newest app version.

**Comment by degif** [comment]
This still happens with Electron 1.4.14 building in macOS 10.12.1 and/or 10.12.2. As far as I can tell, this is not a directory/user permission issue as I've tried multiple scenarios running the app as Administrator, in "~/Applications/" and directory I own.

**Comment by zcbenz** [comment]
This is an issue of https://github.com/Squirrel/Squirrel.Mac, please report there instead.
