### ISSUE TITLE
Minimize window on fullscreen

### ISSUE THREAD

**Issue by ubaltaci** [electron/electron#8108]
* Electron version: 1.4.10
* Operating system: OS X El Capitan

```js
win.setFullScreen(false);
win.minimize();
```

### Expected behavior

It should quit from fullscreen mode and minimize the window.

### Actual behavior

While window is in fullscreen mode, calling minimize not working.

### How to reproduce

```js
// while windows is in fullscreen mode.
win.setFullScreen(false);
win.minimize();
// or just win.minimize();
```

**Comment by MarshallOfSound** [comment]
I believe this was raised at some point before and someone pointed out that `setFullScreen` is async.  Not sure what happened to that though

**Comment by kevinsawicki** [comment]
> I believe this was raised at some point before and someone pointed out that setFullScreen is async. 

I think that was brought up in #7817

**Comment by ubaltaci** [comment]
@MarshallOfSound yep calling `minimize` after ~1sec, actually minimize the window. I guess OS X waiting for the fullscreen animation. If `setFullScreen` is async, I guess it should take callback as an argument.

**Comment by zcbenz** [comment]
I'm merging this to #6033 since they are essentially the same problem.
