### ISSUE TITLE
console.error(error.stack) does not display clickable stack traces.

### ISSUE THREAD

**Issue by probablycorey** [electron/electron#811]
In Chrome, calling `console.error(error.stack)` results in a clickable calls in the stack trace. In atom-shell the stack trace isn't clickable if the error is caught and displayed this way.

![http://cl.ly/image/2K2b1a3A260u/Image%202014-11-11%20at%201.14.41%20PM.png](http://cl.ly/image/2K2b1a3A260u/Image%202014-11-11%20at%201.14.41%20PM.png)

The code that generated this behavior can be found at https://github.com/probablycorey/atom-shell/compare/stack-bug

**Comment by basarat** [comment]
Just putting it out there. I would have liked this :rose: Doesn't mean it has to be done
