### ISSUE TITLE
Logic to determine if process is main(browser) or not always returns true when run as node

### ISSUE THREAD

**Issue by ramya-rao-a** [electron/electron#8111]
* Electron version: built from source
* Operating system: Mac OS X

The below code is used in Electron in multiple places to determine if a process is main(browser) or not.

```
  std::string process_type = cmd->GetSwitchValueASCII(::switches::kProcessType);
  return process_type.empty();
```
When electron is run as node, the above code always returns true. i.e the process is always thought to be the main process.

Places where this logic is used:
- atom_main_delegate.cc
- main_delegate.cc
- crash_reporter.cc

Am sure this has no impact in the first 2 places. I am concerned about the 3rd file i.e crash_reporter.cc

In Mac, crashpad is initialized only in the main(browser) process, as the handler gets inherited by all child processes. The above logic is used to determine whether current process is main(browser) or not.

I am working on #8109 to enable the use of crash reporter by node processes. Due to the above logic always returning true for node processes, crashed gets initialized for every child process trying to use the crash reporter.

**Comment by kevinsawicki** [comment]
> Due to the above logic always returning true for node processes, crashed gets initialized for every child process trying to use the crash reporter.

If `crash_reporter` is going to be run from a node context then we can remove `is_browser` variable completely from it and instead inject the values it needs it for, process type and whether to start the crashpad handler, when it is initialized.

**Comment by kevinsawicki** [comment]
I'm going to close this out, going forward we can migrate code that uses this logic to something more explicit that is expressing its intent better and be setup/customized directly in `node_bindings` when run in the node context.
