### ISSUE TITLE
Disparity between net module headers and Node IncommingMessage headers

### ISSUE THREAD

**Issue by niik** [electron/electron#8117]
As I understand things the net module is supposed to follow the Node API as closely as possible, from [net.md](https://github.com/electron/electron/blob/master/docs/api/net.md)

> The net module API has been specifically designed to mimic, as closely as possible, the familiar Node.js API. The API components including classes, methods, properties and event names are similar to those commonly used in Node.js.

The net module version of `IncommingMessage`, however, [returns a different structure](https://github.com/electron/electron/blob/master/lib/browser/api/net.js#L42) for its header collection than its Node counterpart. Where Node returns a simple object like `{ "Content-Type": "foo", ... }` the net module returns an object where each value is an array containing any duplicate headers: `{ "Content-Type": [ "foo" ], ...}`

<img width="356" alt="screen shot 2016-12-01 at 14 55 49" src="https://cloud.githubusercontent.com/assets/634063/20796414/490139ba-b7d6-11e6-920f-d24f8e7cc036.png">

So the net module returns duplicate headers as an array whereas Node will concat duplicate headers into a single string value (comma separated list) if the header is defined as a list in the HTTP specification.

From [the Node docs](https://nodejs.org/api/http.html#http_message_headers)

> Duplicates in raw headers are handled in the following ways, depending on the header name:
>
> Duplicates of age, authorization, content-length, content-type, etag, expires, from, host, if-modified-since, if-unmodified-since, last-modified, location, max-forwards, proxy-authorization, referer, retry-after, or user-agent are discarded.
>
> set-cookie is always an array. Duplicates are added to the array.
>
> For all other headers, the values are joined together with ', '.

### Expected behavior

Duplicate HTTP response headers should be joined together if allowed by the HTTP specification or else discarded. 

### Actual behavior

Headers are returned in an array regardless of duplicates.

### Proposed solution

Node has already solved this problem once, see [_http_incoming.js#L134-L180](https://github.com/nodejs/node/blob/8264a2225628cbc32116f83a079f6024786988ab/lib/_http_incoming.js#L134-L180). Although the method is exposed on the `IncommingMessage` prototype it's an undocumented method which is subject to change so using it directly is probably #dangerzone. Since the licenses of electron and node seem compatible I propose borrowing that code and adapting it for use in electron.

cc @kevinsawicki @joshaber @shiftkey

**Comment by kevinsawicki** [comment]
> Proposed solution

Sounds good to me, thanks for bringing this up 👍

**Comment by deepak1556** [comment]
The current structure was made that way to maintain consistency with headers from `webContents#did-get-response-details` event and `webRequest` module. So if we are changing the structure, should it be reflected overall or just the net module ?

**Comment by zcbenz** [comment]
It is probably too late to change this, maybe just make this a breaking change of 2.0?

**Comment by mgbennet** [comment]
Any news on this? This is affecting version 8.0.0 of [got](https://github.com/sindresorhus/got) when setting useElectronNet to true.

**Comment by NilSet** [comment]
This is a major pain point for us, it prevents us from transparently using `net`'s proxy aware transport transparently inside `superagent`, which is forcing us to rewrite a ton of network code for a library which is supposed to be isomorphic.

**Comment by NilSet** [comment]
I believe the most complete way of fixing this would be to change it in the mate converter. https://github.com/electron/electron/blob/3748ee49ea41b4d0defb6e937d44e561352543c7/atom/common/native_mate_converters/net_converter.cc#L152-L175

**Comment by NilSet** [comment]
And also here, for the consistency concerns @deepak1556 mentioned.
https://github.com/electron/electron/blob/3748ee49ea41b4d0defb6e937d44e561352543c7/atom/browser/net/atom_network_delegate.cc#L120-L143
Interestingly, it seems like we do not normalize the case of the headers here, but do in the net module.

**Comment by sindresorhus** [comment]
@codebytere Would you accept a PR to update the documentation?

**Comment by codebytere** [comment]
@sindresorhus sorhus absolutely! I don't have a lot of bandwidth right now but when i get a little more i can prioritize this underlying issue more and see what i can do!

**Comment by codebytere** [comment]
@sindresorhus bit late on this one, i admit, but i opened a PR to fix the underlying issue so it should go out in a release soon hopefully!
