### ISSUE TITLE
Custom menu bar doesn't display

### ISSUE THREAD

**Issue by kilometers** [electron/electron#8119]
* Electron version: 1.4.10
* Operating system: OSX El Capitan 10.11.6

### Expected behavior

Running `Menu.setApplicationMenu(menu)` after the electron-quick-start app is `ready` should display my custom menu.

### Actual behavior

The menu bar is blank, save for a default menu item titled 'Electron'. The submenu for this menu item is also completely blank.

Running `console.log(Menu.getApplicationMenu())` returns a menu object which seems to be the one I want. For some reason Electron isn't displaying it.

### How to reproduce

The difference between the current code and the original quick-start app is minor.

Add this to the `createWindow()` function in main.js:
```
const template = [
    {
      label: 'File',
      submenu: [
        {
          role: 'open'
        },
        {
          role: 'save'
        },
      ]
    }
  ]

  const menu = Menu.buildFromTemplate(template)
  Menu.setApplicationMenu(menu)
```

**Comment by Kagami** [comment]
I think I get the same behavior in Gnome.

![electron-menu](https://cloud.githubusercontent.com/assets/533383/20812451/0ff4dc9e-b82b-11e6-9ea0-2367d5e84af2.png)

Both `Menu.setApplicationMenu(menu)` and `window.setMenu(menu)` set only window menu, but I wasn't able to change `Electron` title at top. I tried to search here in bugtracker regarding Gnome's Top Bar but haven't found anything similar.

**Comment by kilometers** [comment]
![github - electron](https://cloud.githubusercontent.com/assets/6674848/20820169/3cbce64c-b874-11e6-97bb-eaa4e17f5509.png)

My behavior's a little different. None of the menu items I've added appear. Also, the submenu of "Electron" is completely empty.

Perhaps this can help you: #2543

**Comment by mark-buer** [comment]
@kilometers Perhaps you're missing `label`s for the menu items?

**Comment by mark-buer** [comment]
To elaborate further, `open` and `save` are not valid roles. The full [list of valid roles can be seen here](https://github.com/electron/electron/blob/master/lib/browser/api/menu-item-roles.js).

Additionally, on OSX, the first most menu will always be labeled to match the application name (you cannot rename it to "File" or anything else). The [docs for `Menu`](https://github.com/electron/electron/blob/master/docs/api/menu.md#main-process) show how to conditionally add the application menu on OSX.

**Comment by kilometers** [comment]
That was the exact issue. Thank you for expanding on the first comment.

**Comment by kongzz311** [comment]
a solution for you
if(process.platform == 'darwin'){
  mainMenuTemplate.unshift({label:'',});
}

**Comment by chaveezy** [comment]
@kongzz311 This is fine but you still get the Electron tag in the menu bar
