### ISSUE TITLE
Touch events and scrolling

### ISSUE THREAD

**Issue by bellostom** [electron/electron#8125]
Hi

I am creating an app that will run in a touch device.
The problem is that no touch events are supported when electron runs
I have tried the --touch-events switch but with no luck
I also tried the --touch-devices switch but doing a ps afterwards it seems that the switch is not present in the list of arguments passed in the executable.

Anyone with experience in running Electron with a touch screen?
Are there any specific flags that needed in order for touch events and scrolling to work correctly?

Regards

**Comment by jean-emmanuel** [comment]
`--enable-touch-events` is the one !

**Comment by MarshallOfSound** [comment]
@bellostom Chromium flags are enabled with the name

`--enable-[flag name]`

So your `--touch-events` will become `--enable-touch-events`

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by bellostom** [comment]
Hi,
Thanks for the help
Moving the thread to
https://discuss.atom.io/t/touch-events-and-scrolling/36575
Tried the switch you mentioned with no luck however
