### ISSUE TITLE
Add option to show title text in titlebar in fullscreen when titleBarStyle: 'hidden-inset'

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#8126]
* Electron version: 1.4.10
* Operating system: macOS El Capitane

We want to show a title to our users when they are in fullscreen. However, when a window has `titleBarStyle: 'hidden-inset'` the title is not shown in fullscreen when mouse reaches the top of the screen.

We saw [this issue](https://github.com/electron/electron/issues/6715) where it is described that  it would look ugly. Is it going to look like the image provided below? Because we will be satisfied with such an appearance.

![image](https://cloud.githubusercontent.com/assets/884810/20829130/6ead42e6-b883-11e6-9158-4bcc82846e42.png)

It would be great if Electron could have an option for enabling the title to be shown when `titleBarStyle: 'hidden-inset'` is set (something like `alwaysShowTitleTextInFullscreen`). Currently we are not happy with the behavior and even thought that it was a bug.

**Comment by zcbenz** [comment]
It seems that the behavior depends on the version of OS, last time I checked the tile only took half height in titlebar. I'm good adding an option for this.
