### ISSUE TITLE
BrowserWindow "alwaysOnTop" only for current application

### ISSUE THREAD

**Issue by popod** [electron/electron#8130]
Add an option to [BrowserWindow](http://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions) to set the windows on top of all windows of the current application.. But not of all the windows of all opened applications which is what do "alwaysOnTop".

**Comment by zcbenz** [comment]
As far as I know no platform support this, I'm closing this as won't fix.

(If you want to implement an interface like Photoshop, it was done by using child windows or setting window type to toolbar.)
