### ISSUE TITLE
Add getIcon app/window API

### ISSUE THREAD

**Issue by McPo** [electron/electron#8133]
It is possible to set the icon used within the dock and the window. It would be convenient to have a method `getIcon()`, which could return the current icon.

Currently my application utilises electron-builder to package the application. As part of this process the application is given a an icon from a resource file, at build time. With no way to obtain the same icon during runtime. This requires an additional icon be bundled with the application as well, to be used in various other circumstances in which you'd want to display an icon. ie electron-notify could by default pick up the application icon without having to explicitly state it and display it in notifications for Windows 7.

**Comment by ragnerok** [comment]
Hi, this looks interesting I would like to work on this, any tips on how to get started ?
Thanks :D

**Comment by codebytere** [comment]
I do believe you can possibly use: https://github.com/electron/electron/pull/10727

**Comment by codebytere** [comment]
Closing as https://github.com/electron/electron/pull/10727 has been merged.
