### ISSUE TITLE
Different MediaDeviceInfo.deviceId's are given every time I start the application

### ISSUE THREAD

**Issue by mvladic** [electron/electron#8135]
* Electron version: 1.4.8
* Operating system: Windows 10 Version 1607 (OS Build 14393.447)

### Expected behavior

I created `BrowserWindow` with persistent session by specifying `'persist:<some name>'` partition. I'm enumerating media devices with `MediaDevices.enumerateDevices()` and I'm expecting to get every time the same `MediaDeviceInfo.deviceId` even if I restart the application.

[Here](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) it says:

**MediaDeviceInfo.deviceId**
Returns a DOMString that is an identifier for the represented device **that is persisted across sessions**. It is un-guessable by other applications and unique to the origin of the calling application. It is reset when the user clears cookies (for Private Browsing, a different identifier is used that is not persisted across sessions).

### Actual behavior

When I restart the application I get different `MediaDeviceInfo.deviceId`'s

### How to reproduce

- Create BrowserWindow like this:

```
var win = new BrowserWindow({
  width: 1024, 
  height: 768,
  webPreferences: {
    partition: 'persist:abc'
  }
});
```

- From the browser window (i.e. renderer) execute the following code to print deviceId's:

```
navigator.mediaDevices.enumerateDevices().then(function(devices) {
  devices.forEach(function(device) {
    console.log(device.kind + ": " + device.label +" id = " + device.deviceId);
  });
});
```

- Restart the application and compare deviceId's - it will be different every time.

**Comment by MarshallOfSound** [comment]
Worth noting that this occurs even if you use the default session as well.  I've been working around it for ages, didn't realise it was a bug 😆
