### ISSUE TITLE
Custom margins in marginsType when using printToPDF 

### ISSUE THREAD

**Issue by destan** [electron/electron#8138]
When using `webContents.printToPDF(options, callback)` there are only 3 options of `marginsType` available however in chrome there are actually 4 the 4th being the `custom`.

![screenshot from 2016-12-04 00-29-25](https://cloud.githubusercontent.com/assets/442813/20862338/8b1431d2-b9b0-11e6-9785-c21aa3e71bc8.png)

Can we set custom margin types with `printToPDF`? Since Chrome doesn't support [page margin boxes](https://www.w3.org/TR/css3-page/#margin-boxes) when printing (or generating pdf) this custom print margins are essential while generating pdf.

**Comment by zcbenz** [comment]
I'm merging this to https://github.com/electron/electron/issues/7849.
