### ISSUE TITLE
can not find .node file  when i use --asar

### ISSUE THREAD

**Issue by ytudt** [electron/electron#8139]
I use nan to translate c++ to .node file. 
and i use this module like 
var rcsv6 = require('./lib/v6Sdk/rcssdkv6.node');
in the Renderer Process.
I electron-packager to build an .app in mac,It can run when I don't use --asar.
but when I use --asar ,it can't find the .node module like
![image](https://cloud.githubusercontent.com/assets/16434007/20872152/491d9bf6-bad7-11e6-936b-c0d06f872654.png)

what should I do?

**Comment by enlight** [comment]
See https://github.com/electron-userland/electron-packager/issues/424
