### ISSUE TITLE
No way to catch out of memory browserwindow crashes in latest electron

### ISSUE THREAD

**Issue by mgcrea** [electron/electron#8140]
* Electron version: `v1.4.10`
* Operating system: `Ubuntu 14.04.5 LTS`

### Expected behavior

Ability to catch a memory crash somehow, electron used to log the following error on stderr (on the `v0.33.x` branch), and was catchable by parsing stderr

```
[2960:1205/093426:ERROR:atom_bindings.cc(38)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

### Actual behavior

When I try `v1.4.10`, I no longer get any indication in the cluster or stdout/err that a child browser window has crashed (window only turns white).

### How to reproduce

```
<!DOCTYPE html>
<html>
<head>
<title>Leak test</title>
<style>
body {
  background: blue;
}
</style>
</head>
<body>

<script type="text/javascript">
var output = [];
var count = 0;


setTimeout(function() {
while (true) {
  output.push(new Object());
  count++;

  if (typeof(process) !== 'undefined' && count % 1000 == 0) {
    console.log(process.memoryUsage());
  }
}
}, 2000);
</script>
</body>
</html>
```

Also I am not sure why but `--js-flags="--max_old_space_size=2048"` does not have any effect on the test above. It always crash at the same time.

**Comment by kevinsawicki** [comment]
Are you listening to the `crashed` event on the `webContents`?

http://electron.atom.io/docs/api/web-contents/#event-crashed

**Comment by mgcrea** [comment]
I'm currently listening to all of theses events:
```
  browserWindow.on('unresponsive', unresponsiveHandler);
  browserWindow.on('responsive', responsiveHandler);
  browserWindow.on('crashed', webContentsCrashHandler);
  webContents.on('crashed', webContentsCrashHandler);
  webContents.on('plugin-crashed', webContentsPluginCrashHandler);
```

No one seems to get called when I get the actual crash.

**Comment by mgcrea** [comment]
Indeed, this was the correct event to listen. Thanks!
