### ISSUE TITLE
Moving a window above the menubar doesn't work on El Capitan

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#8141]
With the following, I can move the window above the menubar on macOS Sierra, but it doesn't seem to work on El Capitan.

```js
const electron = require('electron');

electron.app.on('ready', () => {
	const win = new electron.BrowserWindow({enableLargerThanScreen: true});
	win.setAlwaysOnTop(true, 'screen-saver');
});
```

---

Electron 1.4.10

**Comment by matheuss** [comment]
Related: #7866

**Comment by MarshallOfSound** [comment]
The docs (and usage I've found) appears to indicate that in order to place the window above everything you need to use [`kcgmaximumwindowlevelkey`](https://developer.apple.com/reference/coregraphics/cgwindowlevelkey/kcgmaximumwindowlevelkey?language=objc) which strangely isn't mapped to an `NS*WindowLevel` constant.  I'm assuming we could add support for this level but my machine is on Sierra so I can't test this theory out.

**Comment by matheuss** [comment]
@MarshallOfSound we experimented with that too:
```swift
import Cocoa
import AppKit

@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {
  @IBOutlet weak var window: NSWindow!

  func applicationDidFinishLaunching(aNotification: NSNotification) {
    self.window.level = Int(CGWindowLevelForKey(.MaximumWindowLevelKey));
  }

  func applicationWillTerminate(aNotification: NSNotification) {}
}

```

We got the same results as described in the PR 😕

**Comment by MarshallOfSound** [comment]
I hate to say it but if the documented and self-named "maximum window level" doesn't work.  Then maybe it is an issue on Apple's side of things (OS bug) or straight up isn't possible.  Might be worth seeing if you can make it work in a bare bones template Cocoa app in XCode to confirm the situation.

**Comment by matheuss** [comment]
Oh, forgot to mention: with the code I posted, @sindresorhus couldn't place the window over the menubar too – so we're missing something there 🤔

**Comment by leethomas** [comment]
I don't think it's possible to do this. As a result of working on https://github.com/electron/electron/pull/8487, I tried doing absurd things like 
```js
mainWindow.setAlwaysOnTop(true, 'screen-saver', 10000);
```

and this is what happened:


![](http://mnch.in/ukCo/ue4wLAMr+)

**Comment by sindresorhus** [comment]
@leethomas Did you enable the `enableLargerThanScreen` option like in my example?

**Comment by albinekb** [comment]
Just tested this and can confirm `enableLargerThanScreen` works on *macOS Sierra* (Version: 10.12.4 (16E195))

**Comment by zcbenz** [comment]
This is a bug of macOS, please report to Apple instead.
