### ISSUE TITLE
<webview> localStorage gets cleared on page reload

### ISSUE THREAD

**Issue by ziflex** [electron/electron#8145]
* Electron version: 1.4.10
* Operating system: Fedora 25

### Expected behavior

On page reload inside webivew values from local storage and app cache should remain.

### Actual behavior

On page reload inside webview all values from local storage and app cache get cleared.

**Comment by deepak1556** [comment]
Can you provide a minimal example that can reproduce the issue ?

**Comment by ziflex** [comment]
During making example app I figured out that there is no problem in Electron. It's in a target website. 
Sorry.
