### ISSUE TITLE
Proxy Settings

### ISSUE THREAD

**Issue by notanark** [electron/electron#8150]
* Electron version: Latest
* Operating system: Windows

### Expected behavior

Proxy should be set

### Actual behavior

Proxy is set but it has a user/pass and thus the page does not load

### How to reproduce

app.on('login', function (event, webContents, request, authInfo, callback) {
    console.log("Login attempt");
    event.preventDefault();
    callback('user', 'pass');
});

   NewBrowser
        .webContents
        .session
        .setProxy(`https://${Proxy.ProxyIp}:${Proxy.ProxyPort}`, function (done) {
            console.log(done);
            NewBrowser.loadURL('https://whatmyip.net');
        });

**Comment by agrande** [comment]
Hello,

How did you solve/workaround this issue? I have a similar problem. The 'login' event doesn't seem to fire, I'm running out of options to make it run requests through an authenticated proxy.

Thanks.
