### ISSUE TITLE
Can not quit application with modal window on macOS

### ISSUE THREAD

**Issue by salomvary** [electron/electron#8154]
* Electron version: v1.4.10
* Operating system: macOS 10.11.5

### Expected behavior

Application with visible modal window should be possible to quit.

### Actual behavior

Cmd+q or Quit from the menu has no effect (other than an audible feedback probably signalling failure). The application keeps running, no window is closed.

### How to reproduce

1. Use the [quick start application](http://electron.atom.io/docs/tutorial/quick-start/) plus the following lines at the bottom of main.js / createWindow():

```js
  let win2 = new BrowserWindow({
    modal: true,
    parent: win
  })
  win2.loadURL(`file://${__dirname}/index.html`)
```

2. Try to quit with Cmd+q or from the menu.

**Comment by liusy182** [comment]
I am wondering if this is the expected behavior on Mac where modal dialog is supposed to block until current event is processed.
One example is the Terminal on Mac. Say we have 2 tabs open. Open `vi` editor in one of them and keep the focus. Pressing `cmd-w` triggers a confirmation modal dialog. Pressing `cmd-q` afterwards does not quite application.

**Comment by mathieubodin** [comment]
I'm facing a close behavior: once the modal window is displayed, any attempt to quit the application (through Command+Q or the menu item) close the modal, then the main window is still displayed and would be closed only through the red cross button.

IMHO, regardless of modal behavior, when I want to quit an application on MacOSX, I use Command+Q and expect it to work :smile:.

**Comment by tdhawan** [comment]
IMHO - the modal window is asking for an action to be performed, and should not allow quitting the app. please try this in mac:
1. open excel
2. type something
3. now try to save, you will get a modal window,
4. hit command+q
observation - nothing happens

**Comment by zcbenz** [comment]
This is the default behavior on macOS, while I'm not sure whether there is a way to change the behavior, I think we should keep it as it is because that's the behavior that most users would expect.
