### ISSUE TITLE
LevelDOWN could not locate the bindings file when using electron.js under Windows 7

### ISSUE THREAD

**Issue by 029xue** [electron/electron#8161]
I met the exactly error as this post: http://stackoverflow.com/questions/37613833/leveldown-could-not-locate-the-bindings-file-when-using-electron-js-under-window

> I created nodeJS server that uses levelDOWN module. So when I'm starting my server with node app.js everything is fine. I want to create electron desktop app that will use my app.js file. So I installed electron module and created electronApp.js file:
> 
>     var app = require('electron').app;
> 
>     app.on('ready', function(){
> 
>         // start http server
>         var server = require(__dirname + "/app");
>     });
> Now I'm trying to run my application electron electronApp.js but I'm getting next error:

`App threw an error during load
Error: Could not locate the bindings file. Tried:
 → c:\Dev\MyApp\node_modules\leveldown\build\leveldown.node
 → c:\Dev\MyApp\node_modules\leveldown\build\Debug\leveldown.node
 → c:\Dev\MyApp\node_modules\leveldown\build\Release\leveldown.node
 → c:\Dev\MyApp\node_modules\leveldown\out\Debug\leveldown.node
 → c:\Dev\MyApp\node_modules\leveldown\Debug\leveldown.node
 → c:\Dev\MyApp\node_modules\leveldown\out\Release\leveldown.node
 → c:\Dev\MyApp\node_modules\leveldown\Release\leveldown.node
 ��� c:\Dev\MyApp\node_modules\leveldown\build\default\leveldown.node
 → c:\Dev\MyApp\node_modules\leveldown\compiled\6.5.0\win32\x64\leveldown.node
    at bindings (c:\Dev\MyApp\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (c:\Dev\MyApp\node_modules\leveldown\leveldown.js:4:46)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Dev\MyApp\app\app.js:3:9)`

My environment is Node 6.5.0 on Windows 7.

Is this an LevelDown problem or an Electron related issue? Thanks.

**Comment by kevinsawicki** [comment]
I'm having trouble reproducing this on Windows 10 using Electron 1.4.12 and Node 6.9.2.

This is the `.npmrc` file I'm using:

```
runtime = electron
disturl = https://atom.io/download/electron
target = 1.4.12
arch = x64
```

<img width="1190" alt="screen shot 2016-12-13 at 9 52 33 am" src="https://cloud.githubusercontent.com/assets/671378/21152114/e8be7002-c119-11e6-92b9-32e29ba4dc25.png">


How did you compile `leveldown`?

**Comment by 029xue** [comment]
I didn't compile leveldown, instead, I'm using the prebuilt electron like below:

`npm init -y`
`npm install electron levelup leveldown`

After that, I opened the debug console of Electron API Demos, type below:

`require("C:\\test\\node_modules\\leveldown")`
`C:\test\node_modules\bindings\bindings.js:83 Uncaught Error: %1 is not a valid Win32 application.
\\?\C:\test\node_modules\leveldown\build\Release\leveldown.node`
`    at Error (native)`
`    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)`
`    at Object.Module._extensions..node (module.js:583:18)`
`    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)`
`    at Module.load (module.js:473:32)`
`    at tryModuleLoad (module.js:432:12)`
`    at Function.Module._load (module.js:424:3)`
`    at Module.require (module.js:483:17)`
`    at require (internal/module.js:20:19)`
`    at bindings (C:\test\node_modules\bindings\bindings.js:76:44)`

However, require `levelup` works fine:

`require("C:\\test\\node_modules\\levelup")`
`LevelUP(location, options, callback) {`
`  if (!(this instanceof LevelUP))`
`    return new LevelUP(location, options, callback)`

`  var error`

`  EventEmitter.call(this)`
`  this.setMaxListeners(Inf…`

BTW, if using Nodejs interpreter, both `levelup` and `leveldown` works fine.

My environment is Windows 7 + Nodejs 6.9.2 and Electron API Demos 1.2.0.

Thanks.

**Comment by enlight** [comment]
`leveldown` contains a native Node module which must be rebuilt from source to target a specific Electron version. Some libs like [`zero.mq`](https://github.com/zeromq/zeromq.js) now use [`prebuild`](https://github.com/mafintosh/prebuild) to provide prebuilt native modules for Electron (in addition to Node), but `leveldown` only has prebuilt modules for Node so you will still need to build it from source following one of the [documented approaches](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md).

**Comment by 029xue** [comment]
Rebuilt LEVELDOWN make it work, thanks!

`cd node_modules/leveldown`
`HOME=~/.electron-gyp`
`../.bin/node-gyp rebuild --target=1.2.5 --arch=x64 --dist-url=https://atom.io/download/atom-shell`
