### ISSUE TITLE
Drag-Enter not triggered when dragging image to Tray

### ISSUE THREAD

**Issue by jrodl3r** [electron/electron#8162]
If you drag an image-preview for any video on [youtube.com](http://youtube.com) (to Tray / Menubar Icon) - the `drag-enter` event doesn't fire. Seems to work just fine for text-links, or even vimeo image-previews. (darwin-only)

It does appear to focus the devTools window after a phantom-drop...

**Comment by kevinsawicki** [comment]
What version of Electron are you using? Just want to confirm this wasn't fixed by https://github.com/electron/electron/pull/8024 which came out in 1.4.10.

**Comment by zcbenz** [comment]
Closing until more information is provided.
