### ISSUE TITLE
How to block webrtc

### ISSUE THREAD

**Issue by notanark** [electron/electron#8163]
* Electron version: 1.4
* Operating system:  windows

### Expected behavior
All webrtc is stopped
### Actual behavior
webrtc is not stopped in iframes
### How to reproduce
browserleaks.com/webrtc#webrtc-disable

Also I asked this in the slack and when I asked someone to stop spamming c++ code or use code tags I got booted. Very unprofessional.

**Comment by kevinsawicki** [comment]
There are a few issues in Chrome that discuss this and the possible workarounds:

- https://bugs.chromium.org/p/chromium/issues/detail?id=333752
- https://bugs.chromium.org/p/chromium/issues/detail?id=457492

They recommend using [this extension](https://chrome.google.com/webstore/detail/webrtc-network-limiter/npeicpdbkakmehahjeeohfdhnlpdklia) which you may want to try in your app.

**Comment by notanark** [comment]
Hi, no I figured it out. Can we talk about how I was booted from your chat for asking someone to stop spamming?

**Comment by kevinsawicki** [comment]
> Hi, no I figured it out.

Glad to hear it.

>  Can we talk about how I was booted from your chat for asking someone to stop spamming?

Sure, please email electron@github.com to discuss this.

**Comment by myfrndjk** [comment]
Hi,

Is this issue fixed, I am also facing the same issue
@notanark if you already fixed this, please share the details
