### ISSUE TITLE
Setting window to fullscreen, when resizing is disabled, breaks fullscreen functionality

### ISSUE THREAD

**Issue by CodeTheory** [electron/electron#8166]
* Electron version: 1.4.8
* Operating system: OS X El Capitan (v10.11.6)

### Expected behavior
Setting a window to fullscreen via `win.setFullScreen(true)` in an event should make the window fullscreen with the window increasing its size to fill the screen.

### Actual behavior
Setting a window to fullscreen via `win.setFullScreen(true)` in an event makes a new desktop as any Mac window should when going fullscreen but the window says at its initial size when `resizable` is set to `false` upon window creation.

### How to reproduce
- Create a `BrowserWindow` at any size but define `resizable: false` in the options.
- Create a function that detects `win.isFullScreen()` and either `setFullScreen` to `true` or `false` depending on the state and make that toggle-able within the app. 
- Toggle fullscreen and see that the size of the window does not change but the window does create a new desktop.

### Additional Information
_Please ignore the title in this next screenshot. I re-utilised an app from before_
![image](https://cloud.githubusercontent.com/assets/1695613/20995095/981bd404-bcec-11e6-97ea-99ab5d1a1c70.png)
This screenshot is of a test fullscreen application with `resizable` set to `false`.
However, as a workaround I can use this:
```js
if (postRecWindow.isFullScreen()) {
  postRecWindow.setFullScreen(false);
  postRecWindow.setResizable(false);
} else {
  postRecWindow.setResizable(true);
  postRecWindow.setFullScreen(true);
}
```
But I assume this is not the expected behaviour for fullscreen when resizable is false 🤔

**Comment by sindresorhus** [comment]
Seems similar to https://github.com/electron/electron/issues/5918. I totally agree it's not the expected behavior.

**Comment by CodeTheory** [comment]
In addition to this, resizing also has to be set to `true` in order for `win.maximize()` to work as intended. I think that's just an extension of this issue, though

**Comment by sherlock1982** [comment]
For me this issue still exists. But I've found a workaround like this:

    window.on('enter-full-screen', () => {
        window?.setResizable(true);
    });
    window.on('leave-full-screen', () => {
        setTimeout(() => {
            window?.setResizable(false);
        });
    });
    window.on('enter-html-full-screen', () => {
        window?.setResizable(true);
    });
    window.on('leave-html-full-screen', () => {
        setTimeout(() => {
            window?.setResizable(false);
        });
    });
