### ISSUE TITLE
diacritics does not substitue original char on mac in webview

### ISSUE THREAD

**Issue by kwonoj** [electron/electron#8171]
* Electron version: 1.4.11
* Operating system: Mac 10.11.6

### Expected behavior
diacritics should substitute and replace original char

### Actual behavior
original char remains, diacritics are appended next to it

recordings at https://giphy.com/gifs/l0HlOrAcf1dPBypFe

I'm not entirely sure if this is electron side issue or not yet, raising to get clarification with below example code snippet, transparently bring up webview. In webview's input textfield, if user bring up diacritics and select one of them it does not substitute original char but just append right next to it.

### How to reproduce

*index.js*
```js
const {app, BrowserWindow} = require('electron')

let win

function createWindow () {
  win = new BrowserWindow({width: 800, height: 600})

  win.loadURL(`file://${__dirname}/index.html`)
  win.on('closed', () => {
    win = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (win === null) {
    createWindow()
  }
})
```

*index.html*
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>Hello World!</title>
  <style>
    body {
      background-color: #aaa;
    }

    #guest {
      border: none;
      position: absolute;
      top: 100px;
      bottom: 0;
      left: 0;
      right: 0;
      height: 100%;
      width: 100%;
      min-width: 400px;
      overflow: hidden;
    }
  </style>
</head>

<body>

  <body>
    <webview id="guest" src="https://google.com/"></webview>
  </body>
</body>

</html>
```

**Comment by mnquintana** [comment]
@kwonoj This looks like the same issue as https://github.com/electron/electron/issues/3379 – does that cover this case?

**Comment by kwonoj** [comment]
@mnquintana Oh yes, seems that's case. My searching wasn't good enough before filing new issue. Let me close this issue dupe of #3379.
