### ISSUE TITLE
Can't hits breakpoints when debugging render process with webstorm

### ISSUE THREAD

**Issue by kevin00000000** [electron/electron#8172]
Project: electron-api-demo
electron version: 1.4.11
Configuring guide: [https://blog.jetbrains.com/webstorm/2016/05/getting-started-with-electron-in-webstorm/](url)
webstorm version: 2016.2.3

Create NodeJS run\debug configuration for the Main process and Chromium remote configuration for the Render process.
Run NodeJS configuration, then Chromium remote configuration.
Main process is OK. 
Chromium remote successfully connected, but nothing happens - breakpoints are not hit, console.log message are not shown.
Why? How to fix it?

Thx.

**Comment by kevinsawicki** [comment]
I think this would be better opened on the webstorm issue tracker, https://youtrack.jetbrains.com/issues/WEB since we don't have access to webstorm or have details about its debugger implementation.
