### ISSUE TITLE
Support --prof for main process

### ISSUE THREAD

**Issue by jrieken** [electron/electron#8173]
* start an electron app with `--js-flags="--prof"`
* quit app
* two *isolate-xyz-v8.log* files are created, one for the main process and one for the renderer process
* 🐛 the log file from the main process contains no `tick`-information

**Comment by MarshallOfSound** [comment]
Can you explain what the actual issue is here.  Personally I've never used `--prof` before so I have no idea what the expected behavior is.  The issue template normally helps with this.

```markdown
* Electron version:
* Operating system:

### Expected behavior

<!-- What do you think should happen? -->

### Actual behavior

<!-- What actually happens? -->

### How to reproduce

<!-- For bugs, provide sample code or a repo URL that demos the problem -->

```

**Comment by jrieken** [comment]
Sorry, I assumed `--prof` is known. A good introduction can be found [here](https://github.com/v8/v8/wiki/V8%20Profiler) but in short `--prof` enables V8's internal profiler that samples on JavaScript and C/C++ code. The workflow goes like this:

* start nodejs with `--js-flags="--prof"`and run your program to finish
* a log file, `v8.log`, will be created. It contains low-level'ish information that can be process by other tools, like the tick processor, time line plotter etc

The problem here is that the log file from the main process doesn't contain 'tick'- information. 

![screen shot 2016-12-09 at 14 02 02](https://cloud.githubusercontent.com/assets/1794099/21049984/4f7f80ce-be18-11e6-9734-4faf053f3cb8.png)

I am unsure if this should have been covered by https://github.com/electron/electron/pull/3412 or not. Also, I read [this](https://github.com/electron/electron/issues/3767#issuecomment-164333772) which might make this a feature request

**Comment by jrieken** [comment]
@MarshallOfSound If there anything else you need to triage this?

**Comment by kevinsawicki** [comment]
@jrieken what version of Electron were you seeing this on? Can you still reproduce this with 1.7.1? I just ran with `--prof` and saw tick events from both processes. Also what platform were you on? Thanks.

**Comment by jrieken** [comment]
Nice, it does work with 1.6.6. 👯‍♂️
