### ISSUE TITLE
how can i solve this below mentioned error please help to me. 

### ISSUE THREAD

**Issue by vennilapanneer** [electron/electron#8174]
is4800@IS-S1475 MINGW64 /d/projects/electron-quick-start-master/electron-quick-start-master
$ npm install electron-spell-check-provider

> spellchecker@3.3.1 install D:\projects\electron-quick-start-master\electron-quick-start-master\node_modules\spellchecker
> node-gyp rebuild

D:\projects\electron-quick-start-master\electron-quick-start-master\node_modules\spellchecker>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: Cannot find module 'block-stream'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:469:15)
gyp ERR! stack     at Function.Module._load (module.js:417:25)
gyp ERR! stack     at Module.require (module.js:497:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\node_modules\tar\lib\entry-writer.js:7:19)
gyp ERR! stack     at Module._compile (module.js:570:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:579:10)
gyp ERR! stack     at Module.load (module.js:487:32)
gyp ERR! stack     at tryModuleLoad (module.js:446:12)
gyp ERR! stack     at Function.Module._load (module.js:438:3)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\projects\electron-quick-start-master\electron-quick-start-master\node_modules\spellchecker
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron-spell-check-provider"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! spellchecker@3.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the spellchecker@3.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spellchecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\projects\electron-quick-start-master\electron-quick-start-master\npm-debug.log

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

I also don't see how this error is related to the `electron` module.  

> npm ERR! Failed at the spellchecker@3.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs spellchecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

Indicates the `spellcheck` module failed to rebuild, check your VS2015 c++ install and try rerunning the install.

**Comment by vennilapanneer** [comment]
Hi MarshallOfSound ,

I reinstall VS2015 c++ but now also I am  getting same error, Please share to me you have any another solution?
