### ISSUE TITLE
os.homedir is not a function when using Babel

### ISSUE THREAD

**Issue by jagi** [electron/electron#8179]
Hi, I'm creating electron application using React and Babel. My problem only occurs in files being transpiled with Babel. When I call:

```js
const os = require('os');
// import os from 'os'; - same result
os.homedir();
```

it throws `TypeError: os.homedir is not a function`. The `os` property is not undefined it just lacks the `homedir()` function:

<img width="257" alt="os" src="https://cloud.githubusercontent.com/assets/1051229/21076977/a98d4546-bf3b-11e6-84af-41224a83a64d.png">

And as I said outside of the files transpiled with Babel, everything works properly. Do you know why is that?

Electron version: 1.4.11
Operating system: macOS Sierra v. 10.12.1

UPDATE: I've also noticed that same problem occurs with the `fs` package. But when I require it, then it's just an empty object.

**Comment by jagi** [comment]
Ok I've found this thread https://github.com/electron/electron/issues/1611 and solved a problem using:

```html
<script>var electronRequire = require;</script>
<script src="main.browserified.js"></script>
```

and requiring node modules in browserified files using the `electronRequire`. It would be nice if you could describe the easiest way of using React with Electron. I've spent entire day learning Browserify to just realise that it's not a good fit for Electron...

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

@jagi You don't need browserify or webpack for Electron (or anything like that) as you have a full commonjs environment.

I.e. You can just use `require` and it will work

If you want some pointers on React with Electron there is a boilerplate here that I hear good things about 👍 

https://github.com/chentsulin/electron-react-boilerplate

**Comment by jagi** [comment]
This boilerplate is using Webpack which IMHO is messy. Moreover this boilerplate is too complicated and I like simple solutions. I know that I don't need Browserify or Webpack when working with Electron but I need them for JSX transpilation.

I think it's very common that developers are using React with Electron and it would be a good idea to at least include some example in docs to make it more friendly for newcomers.

**Comment by MarshallOfSound** [comment]
@jagi You don't need Browserify or Webpack to get JSX working.

Check out one of my projects (quite large) but basically all you need to get React working Electron is.

`babel`
`babel-preset-es2015`
`babel-preset-react`

If you want to take massive shortcut you can try one of my modules that makes this infinitely more simple for you.  [`electron-forge`](https://github.com/marshallofsound/electron-forge) it's very new and not announced to the world yet 😆 but it lets you use React and other such things without worrying about transpiling.

It "Just Works"(tm)

**Comment by jagi** [comment]
Thanks, ElectronForge seems to be nice but it's still a wrapper and I don't like wrappers. I wish it would be included in pure Electron. You said that I can just use babel and presets and I can find an example in one of your projects. But which one? I want to configure everything by myself.

**Comment by MarshallOfSound** [comment]
@jagi This has a lot of stuff you probably don't need but the core babel setup is in there

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-

**Comment by jagi** [comment]
Can you tell me where I should start looking for it? There is a lot of code and I don't know if it's some kind of script that transpiles code on changes or what? Does it work with `electron-reload`?

**Comment by MarshallOfSound** [comment]
Babel config: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/package.json#L156

Babel Deps: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/package.json#L90

Gulp Transpile Task: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/gulpfile.babel.js#L196

**Comment by jagi** [comment]
So it's not like you just need only babel and presents but also gulp. I don't use gulp, so I will stick to Browserify for now. I don't want to learn a new thing that I didn't need so far.

**Comment by MarshallOfSound** [comment]
@jagi You do not need gulp, I use gulp because I like it.

You can stick to just using the babel CLI.  Using browserify is a **bad** plan with Electron as it mocks out lots of the node API's and prevents access to others.  It is also an unnecessary step as common JS `require` works in Electron with no extra tooling needed.

**Comment by jagi** [comment]
Yes I know that I could just transpile code using Babel and output it to some file and later use such a file with Electron. However, for that I would need to run babel command on each file change. And if I don't want to do so I would still need some tool to watch files for changes. So whatever I do I still need some tool. I would like to minimise configuration. I know it's not Electron's fault but React's fault that it's using jsx which on one hand is great but on the other it's frustrating that you have to install so much bloatware to just transpile code. I know that I'm whining a lot :)

**Comment by jagi** [comment]
I will probably write my own script using chokidar as it's used in the `electron-reload` package. I don't know if it's the best fit for watching files changes but I will try it. And later just transpile files. Thanks for help! :)

**Comment by MarshallOfSound** [comment]
@jagi If you want lightweight why not just use `fs.watch` in your own build script or even a lightweight tool like `nodemon`

**Comment by jagi** [comment]
I'm not specialist in watching files but from what I've heard there are several problems with performance (and not only with that) if it goes about using `fs.watch`. If it would be great then everyone would use it. I've heard about `nodemon` but I don't know how does it work in terms of performance.

**Comment by jagi** [comment]
The first article in Google about watching files: https://davidwalsh.name/node-watch-file
