### ISSUE TITLE
Accelerator's improvement

### ISSUE THREAD

**Issue by binjospookie** [electron/electron#8182]
* Electron version: 1.4.12
* Operating system: Linux

When I try to register `Shift` I have an error
```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from Shift
```
because `Shift` is modifier. But to draw a straight line usually use `Shift` (press shift and draw).
Maybe should give ability to register `Shift`  without extra keys?

**Comment by MarshallOfSound** [comment]
@binjospookie `globalShortcut` is for **global** shortcuts.  I.e. System wide, if you want to listen for keypresses inside your app to do things like

> draw a straight line

use the `keyup` and `keydown` window events.  E.g.

```js
window.addEventListener('keydown', (event) => {
  if (event.which === 16) {
    // Shift key is down
  }
});
```
