### ISSUE TITLE
On Ubuntu 16.04, openFile dialog filters do not apply to Recently Used section

### ISSUE THREAD

**Issue by graftonthethird** [electron/electron#8183]
Electron Version: 1.4.12
Operating System: Ubuntu 16.04

On Ubuntu 16.04, the openFile dialog filters do not apply to "Recently Used" files and directories. When it's displayed, the openFile dialog shows the "Recently Used" files and directories by default. If one of these directories is selected by pressing the "OK" button, it will choose the directory and append the filter extension to it (i.e. if a directory named "random_dir" is selected, the dialog callback says that the "random_dir.proj" file was selected.) On the other openFile dialog sections, the filtering does work.

Sample Code:
```
 var dialogOptions = {
    properties: ["openFile"],
    filters: [
      { name: "Projects (.projx)", extensions: ["proj", "projx"] }
    ]
  };

  dialog.showOpenDialog(mainWindow, dialogOptions, function(files) {
    if (files) {
      event.sender.send("selected-file", files);
    }
  });
```

**Comment by EliaContini-TR** [comment]
Electron version: 1.4.15
Operating System: Ubuntu 16.04.1

I have a similar problem, but everything works fine (also on Recent files) until I add the browserWindow param to obtain a modal dialog. Sample code

```
const {dialog} = require('electron').remote; // I'm in the renderer

dialog.showOpenDialog(
   //parentWindow,
   {
      filters: [
         {
            name: 'Text',
            extensions: ['txt']
         },
         {
            name: 'All files',
            extensions: ['*']
         }
      ],
      properties: ['openFile'],
      title: 'Select a file'
   },
   (filePaths) => {
      console.log(filePaths)
   }
);
```

If I remove comment from parentWindow, filters are not applied, the callback is not call and the window freeze.

**Comment by zcbenz** [comment]
This is a bug of GTK+, I'm afraid we are not able to fix this on Electron's side.
