### ISSUE TITLE
Workaround minimum mac os version support 10.9

### ISSUE THREAD

**Issue by con-ssc** [electron/electron#8184]
Is there a way to work around the version limitation of minimum mac os 10.9? My iMac is not able to upgrade past 10.7.5 because of hardware limitation.
Is there a special reason why lower versions are not supported?

**Comment by MarshallOfSound** [comment]
@con-ssc I believe it is due to Chromium only supporting `10.9` and above and we are limited by the version that Chromium supports.

Older releases of Electron may work on `10.7.5` but you would have to search through Chromium releases to determine when `10.7.5` was dropped from the supported list.

**Comment by MarshallOfSound** [comment]
For reference: https://www.google.com.au/chrome/browser/desktop/

> Mac OS X 10.9 or later

**Comment by con-ssc** [comment]
I'm getting there :) vscode guys pointing me to electron guys who point me to the chromium guys, getting to the root of this :P

**Comment by baconface** [comment]
> I'm getting there :) vscode guys pointing me to electron guys who point me to the chromium guys, getting to the root of this :P

It won't be worth mentioning to the Chromium team. It is highly unlikely they will support it again. They traditionally do not support operating systems that are no longer maintained by the developer.

> Earlier this year, we announced that Google Chrome would continue support for Windows XP through the remainder of 2015. At that time, we strongly encouraged users on older, unsupported platforms such as Windows XP to update to a supported, secure operating system. Such older platforms are missing critical security updates and have a greater potential to be infected by viruses and malware.
>
> Today, we’re announcing the end of Chrome’s support for Windows XP, as well as Windows Vista, and Mac OS X 10.6, 10.7, and 10.8, since these platforms are no longer actively supported by Microsoft and Apple. Starting April 2016, Chrome will continue to function on these platforms but will no longer receive updates and security fixes.
>
> If you are still on one of these unsupported platforms, we encourage you to move to a newer operating system to ensure that you continue to receive the latest Chrome versions and features.
>
> Posted by Marc Pawliger, Director of Engineering and Early Notifier

When they say it will continue to run they are referring to older versions, not new releases. So once it breaks, it stays broken and they raise the install requirement.

**Comment by baconface** [comment]
Additionally a tool called MLPostFactor will allow you to update your OS to 10.8 despite your hardware limitation. Updating it to a more recent OS however might make your computer run slower as it is intended for faster hardware.

**Comment by con-ssc** [comment]
Thank you, I will try that.

**Comment by andreydung** [comment]
Do you have any update on this? Were you able to make this work?

**Comment by con-ssc** [comment]
No. electron depends on chromium and the chromium ppl are constantly upgrading so it is not possible to get a version that runs with older versions so it is quite impossible to get electron running in the version below the one supported by the chromium project, other than those that were already mentioned.

**Comment by miniak** [comment]
Chromium 65 dropped support for OS X 10.9, so expect Electron 4.0 to only support macOS 10.10+ when it gets released.
