### ISSUE TITLE
Issues when using hookWindowMessage with WM_DEVICECHANGE

### ISSUE THREAD

**Issue by Inori** [electron/electron#8190]
Minimal code:
```
const electron = require('electron');
const BrowserWindow = electron.BrowserWindow;
const WM_DEVICECHANGE   = 0x0219;
const DBT_DEVICEARRIVAL = 0x8000;
const DBT_DEVNODES_CHANGED = 0x0007;

let listenWnd = null;

function onWndMsgWM_DEVICECHANGE(wParam, lParam) {
    let msgCode = wParam.readUInt32LE(0);
    console.log('Code: ' + msgCode);
}

function setOnDeviceArriveListener() {
    listenWnd = new BrowserWindow({show:false});
    listenWnd.hookWindowMessage(WM_DEVICECHANGE, onWndMsgWM_DEVICECHANGE);
}
```
when ```WM_DEVICECHANGE``` message arrival, I can only get ```DBT_DEVNODES_CHANGED``` value with ```msgCode```, but with no ```DBT_DEVICEARRIVAL```.  A native window created with Win32 API can work as expected. Any sulotions?

**Comment by zcbenz** [comment]
The UI framework of Chromium which is used in Electron has its own logics for certain window messages, if a message is filtered out by Chromium, I'm afraid we are not able to work around it on Electron's side.

Closing this as won't fix since it is a limitation of Windows.
