### ISSUE TITLE
Don't work autoUpdate with proxy basic auth

### ISSUE THREAD

**Issue by vadim-ch** [electron/electron#8194]
Don't work autoUpdate with proxy basic auth! Please, help me. I'm desperate.
Error in logs: System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.

How can I set credentials proxy basic auth???

**Comment by kevinsawicki** [comment]
This is a duplicate of https://github.com/electron/electron/issues/5020, please subscribe to that issue for updates.
