### ISSUE TITLE
require('electron') returns the path, not an object

### ISSUE THREAD

**Issue by adammeola01** [electron/electron#8200]
const electron = require('electron');

console.log(typeof electron); // returns string (path to node package)

OSX - 10.10.5

node - 7.2.1

npm - 3.10.9

electron - 1.4.12

Since it's a string, it has no properties, so electron.app.on errors out, since electron.app does not exist.

**Comment by kevinsawicki** [comment]
Are you requiring it from node or from within an Electron app?

**Comment by adammeola01** [comment]
from index.js, called with "electron index.js"

**Comment by kevinsawicki** [comment]
Can you include your `index.js`?

**Comment by MarshallOfSound** [comment]
@adammeola01 Also how are you running that command.  I.e. Through what terminal / CLI interface?

**Comment by adammeola01** [comment]
`// Original file, that worked in October.
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;
const ipc = require('electron').ipcMain;
const dialog = require('electron').dialog;
ipc.on('open-file-dialog', function(event) {
    dialog.showOpenDialog({
        properties: ['openFile', 'openDirectory']
    }, function(files) {
        if (files) event.sender.send('selected-directory', files);
    });
});
var locals = {};
var electronEjs = require('electron-ejs')(locals);
let mainWindow;
function createWindow() {
    mainWindow = new BrowserWindow({
        width: 800,
        height: 600,
		minWidth: 600,
		minHeight: 500,
		icon: __dirname + '/icon.ico'
    });
    mainWindow.loadURL(`file://${__dirname}/GUI/index.ejs`);
    mainWindow.webContents.openDevTools(); // Open the DevTools.
    mainWindow.on('closed', function() {
        mainWindow = null;
    });
}
app.on('ready', createWindow);
app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});
app.on('activate', function() {
    if (mainWindow === null) {
        createWindow();
    }
});
`

**Comment by adammeola01** [comment]
![image](https://cloud.githubusercontent.com/assets/13489145/21164435/dd59483e-c166-11e6-908c-c0a31c6d5331.png)

**Comment by adammeola01** [comment]
platfrmio-ide, but same result when I got through the actual terminal.

only real difference is that all it's text is in a JS buffer, so it maxes out, and trims the top easily.

**Comment by MarshallOfSound** [comment]
@adammeola01 You can't run `electron` in any Electron based IDE (such as atom) that hasn't been designed to handle the case of launching Electron.

Process's will be spawned with `ELECTRON_RUN_AS_NODE=true`.  If you run in the proper terminal with `npm start` it *should* work correctly.

**Comment by adammeola01** [comment]
Wow!  First time that's come up.

I guess that i've made some false assumptions on how implementing a shell front end in electron would work...

Thanks!

**Comment by enlight** [comment]
Closing as this appears to have been resolved.

**Comment by adammeola01** [comment]
yup, trying to find a way around this change though...  used to work from inside atom, and It was great, but this'll get me by...

thanks guys!

**Comment by julyL** [comment]
Can any way  to debug electron in vscode(windows x64)?  require('electron') just return a String Path
