### ISSUE TITLE
Massive CPU usage using enableNetworkEmulation

### ISSUE THREAD

**Issue by ticarex** [electron/electron#8203]
* Electron version: prebuilt 1.4.12 win32-x64 
* Operating system: Windows 8.1 x64

### Expected behavior

CPU usage should be normal

### Actual behavior

CPU usage going into 30%+ just by using enableNetworkEmulation

### How to reproduce

Listen to a media file while downloading/buffering a media file (e.g. mp4) with enableNetworkEmulation turned on and CPU usage will increase by a lot

index.html
`<audio preload="metadata" src="stream/oFCdtAQp3ss.mp4"></audio>`

main.js
```
mainWindow.webContents.session.enableNetworkEmulation({
    downloadThroughput: 6400,
  })
```

**Comment by MarshallOfSound** [comment]
Can you verify this behavior does not occur in Chromium / Chrome.  My testing does indicate small CPU spikes when I enable network emulation in Chrome but a true comparison should be done on your hardware 👍

**Comment by ticarex** [comment]
Using this website for tests: http://radio-ticarex.rhcloud.com/

On chrome, it does not increase the cpu load significantly. 

On electron, if I enable the network throttling by the Developer Tools instead of doing it programmatically, it does not increase cpu load significantly

**Comment by deepak1556** [comment]
Able to reproduce on linux with the above example.
