### ISSUE TITLE
__dirname in app.asar.unpacked points to app.asar

### ISSUE THREAD

**Issue by scholtzm** [electron/electron#8206]
* Electron version: 1.4.12
* Operating system: tested on both OSX and Windows 8.1

### Expected behavior

`__dirname` in code that is inside `app.asar.unpacked` should point to `app.asar.unpacked` and not to `app.asar`

### Actual behavior

`__dirname` in code that is inside `app.asar.unpacked`points to `app.asar`

### How to reproduce

I prepared a small repro case here: https://github.com/scholtzm/electron-asar-dirname-issue

**Comment by kevinsawicki** [comment]
Can you elaborate on what issue this is causing for you?

The unpacked area is a fallback location for things like `fs` APIs and `require` so `__dirname pointing to the packed area is intentional.

**Comment by scholtzm** [comment]
One of my critical dependencies is calling `.chdir(__dirname)` and I'd like to take advantage of `asar` (even if partially). Therefore I unpacked this specific dependency, but the `__dirname` still points to `app.asar`.

I originally described my issue [here](https://github.com/electron/asar/issues/55).

**Comment by kevinsawicki** [comment]
> One of my critical dependencies is calling .chdir(__dirname)

Can you elaborate a bit on why `chdir` is needed by this dependency?

Have you tried overriding `process.chdir` to handle this directly in your app?

**Comment by scholtzm** [comment]
> Can you elaborate a bit on why chdir is needed by this dependency?

As far as I can tell, it could be avoided:
https://github.com/seishun/node-steam-resources/blob/master/steam_language_parser/index.js

> Have you tried overriding process.chdir to handle this directly in your app?

Haven't done that yet, that would be my last resort solution though.

**Comment by kevinsawicki** [comment]
Closing this out since this is a limitation of asar.

Some options for resolving:

- Use a forked version of `node-steam-resources` that doesn't `chdir`.
- Ship `node-steam-resources` outside of both `app.asar` and `app.asar.unpacked` and access it from a child process where `chdir` would be possible.

**Comment by scholtzm** [comment]
Welp, `node-steam-resources` is an indirect dependency of my project. Using a fork would mean to fork all the other packages in the dependency chain.

I guess the only way to fix this on my end would be to monkey patch `process.chdir`?

**Comment by kevinsawicki** [comment]
> I guess the only way to fix this on my end would be to monkey patch process.chdir?

You may be able to just patch `fs.readFileSync` with something like:

```js
const originalReadFileSync = require('fs').readFileSync
require('fs').readFileSync = (filePath, ...args) => {
  if (filePath === 'steammsg.steamd') {
    filePath = '/a/crafted/path/to/wherever/this/file/is/in/your/apps/bundle'
  }
  return originalReadFileSync(filePath, ...args)
}
```

**Comment by scholtzm** [comment]
Went with your suggestion at the end and it works. Not the prettiest code, but having everything bundled is just so much better.

**Comment by GongT** [comment]
Why this issue can close? it's not fiexd.

I'm using `7zip-bin` and `require('7zip-bin').path7za` is inside `app.asar/node_modules`. but it's in `app.asar.unpacked/node_modules`

**Comment by VisiontechGitHub** [comment]
this issue is still present
in my project I can't use node-windows library for the very reason ...

**Comment by woshidamaomao** [comment]
`const pageDirectory = __dirname.replace('app.asar', 'app.asar.unpacked')`
