### ISSUE TITLE
Add § and ‡ keycodes to Electron Accelerator

### ISSUE THREAD

**Issue by mikefrancis** [electron/electron#8208]
Hi,

Just looking at the available keycodes for [Electron Accelerator](https://github.com/electron/electron/blob/master/docs/api/accelerator.md) and I could really use `§` (grave accent - 192) key support for something personal.

Would this be possible?

**Comment by codebytere** [comment]
We map against Chrome's keyboard codes, and unfortunately that key is not present [here](https://cs.chromium.org/chromium/src/ui/events/keycodes/keyboard_codes_posix.h?sq=package:chromium&dr=CSs&g=0) so it would be rather difficult for us to implement and thus is not something we feel would be best kept in core.
