### ISSUE TITLE
MenuItem click can be called with a null browserWindow in context menus

### ISSUE THREAD

**Issue by jacwright** [electron/electron#8209]
* Electron version: 1.4.12
* Operating system: OSX Sierra 10.12.2

### Expected behavior

When you right click on a window which is _not_ focused, the browserWindow argument should be set to the window you've right-clicked on. See this issue: https://github.com/sindresorhus/electron-context-menu/issues/26

### Actual behavior

When you right click on a window which is _not_ focused, the browserWindow argument is null.

### How to reproduce

Install electron-context-menu (`npm install electron-context-menu`) and require it in your main process. This will add an "Inspect Element" item to the context menu.

Open your app. Right-click and choose Inspect Element. The dev tools will open. Pop the dev tools out into a separate window if they are not already popped out. Then, while the dev tools are still focused, right-click on the main window again and choose "Inspect Element" again. It will either popup an exception (if this project has not null-checked for it yet) or it will do nothing, and not inspect the new element.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `1.6.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
