### ISSUE TITLE
Injecting jQuery script into webview returns referenceError for $ 

### ISSUE THREAD

**Issue by Beslinda** [electron/electron#8211]
I am trying to show a portion of a webpage into webview. To do this I inject a script into the body of the webpage in this way:

`webview.executeJavaScript("$('body').css({'left': '" + left + "', 'top':  '" + top + "' })" );`

But in the console log I get the following error:

`ReferenceError: $ is not defined.`

The view: 
`  <webview ng-src="{{trustSrc(webpage.url)}}" id="{{webpage.name}}" partition="persist:test" nodeintegration></webview>`

I use jquery in my project and it works fine but it does not work inside the webview. Is there a workaround for this issue.?

**Comment by kevinsawicki** [comment]
@Beslinda Is `nodeIntegration` enabled on your `<webview>`? Does it work if you disable node integration?

**Comment by Beslinda** [comment]
@kevinsawicki yes nodeIntegration is set to true

**Comment by kevinsawicki** [comment]
@Beslinda that is the issue, jQuery does not set `$` as a global if it detects it is being run in a node context.

See https://github.com/electron/electron/issues/254 for more details.

**Comment by Beslinda** [comment]
Well If I set nodeIntegration to false then 'require' and jQuery get undefined

**Comment by kevinsawicki** [comment]
> Well If I set nodeIntegration to false then 'require' and jQuery get undefined

How are you loading jQuery in your page?

**Comment by Beslinda** [comment]
`<script>window.$ = window.jQuery = require('./node_modules/jquery/dist/jquery.min.js');</script>
`

**Comment by dkfiresky** [comment]
@Beslinda, you can also include jQuery by:
```
<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script>window.jQuery = window.$ = module.exports;</script>
```

**Comment by kevinsawicki** [comment]
And at what point are you running `webview.executeJavaScript`? Are you sure if it happening after the script runs that is setting up jquery?

**Comment by Beslinda** [comment]
Yes it happens inside the webview in the dev console. I have the jquery running in my project fine.

@dkfiresky when I added jquery in that way then it complained about 'module.exports'

**Comment by Beslinda** [comment]
@dkfiresky the I added this code:

```
<script src="https://code.jquery.com/jquery-2.2.0.js"></script>
<script>window.jQuery = window.$ = typeof module === 'object' ? module.exports : jQuery</script>
```
And now my webview is blank :/

**Comment by Beslinda** [comment]
My webview does not show when nodeIntegration is set to false

**Comment by baconface** [comment]
Is your jQuery references made in the parent or the webview? jQuery must be referenced within the webview if you wish to use it in the webview. And the execution of JavaScript using $ needs to take place after jQuery has successfully been initialized.

**Comment by Beslinda** [comment]
@baconface can you tell me how do I do that? Something like this:  `webview.executeJavaScript(window.$ = window.jQuery = require('jquery');)`

**Comment by frankhale** [comment]
You can use the preload option on the webview to load a script that will inject what you need

**Comment by frankhale** [comment]
@Beslinda have a look at this: https://github.com/electron/electron/issues/2048#issuecomment-115092053
