### ISSUE TITLE
Use Unusual Unicode in :after content cause long time layout

### ISSUE THREAD

**Issue by x-yao** [electron/electron#8213]
* Electron version:1.4.12
* Operating system:MacOS 10.12.1

### behavior
when i use unusual Unicode in `:after` content like `content: "\e630"` in page style(such as iconfont). In chrome Timeline i can see the layout step cost over 1300ms time,but when i ues normal Unicode like `content: "\e400"` everything normal.In chrome 53 dosen't has this problem.
[unusual test url](http://page.kuaidadi.com/package/unicodetest/index.html)
![unusual](http://img.kuaidadi.com/cms/img/upload_751998def4c4cda57b97fe56d86d27ed.png)
[normal test url](http://page.kuaidadi.com/package/unicodetest/test.html)
![nomal](http://img.kuaidadi.com/cms/img/upload_b3122e4f8d282c1264d902025419fd91.png)

**Comment by MarshallOfSound** [comment]
@x-yao Electron is still based on Chromium 53, can you verify the behavior in that version

**Comment by x-yao** [comment]
@MarshallOfSound  I use the version 53.0.2785.89 and it fine.

**Comment by x-yao** [comment]
@MarshallOfSound can you help find out why ? I tried electron version since 1.0.0 bug all has this problem.And open my builded app with another Mac has the same problem.But in every version chrome behave well.

**Comment by x-yao** [comment]
closed because when i reboot my system and its look like behave much better than before.
sry
