### ISSUE TITLE
Certain shortcuts are not generating a keypress event

### ISSUE THREAD

**Issue by ondras** [electron/electron#8216]
* Electron version: 1.4.12
* Operating system: Linux

### Expected behavior

Ctrl+H shall result in a keypress event.

### Actual behavior

No keypress is generated. This happens for certain other key combinations as well (Ctrl+A, Ctrl+R, Ctrl+C, ...). Most letters work, though.

There is no menu: 
```js
Menu.setApplicationMenu(null);
win.setMenu(null);
```

**Comment by MarshallOfSound** [comment]
@ondras Are you sure no other applications are stealing the hotkeys you mentioned

**Comment by ondras** [comment]
@MarshallOfSound I *think* no other applications are stealing them. How can I confirm this?

**Comment by MarshallOfSound** [comment]
@ondras Idk if your version of linux has a safe mode but normally the only things that steal shortcuts are Chromium based tools.  Might be worth making sure that the shortcuts aren't still doing their original actions (Select All, Reload, Copy).  I'll try repro shortly 👍

**Comment by ondras** [comment]
@MarshallOfSound In the meantime I checked that nw.js behaves the same, not passing certain ctrl+letter combinations to userland. Also, I use several apps that have their own (local) Ctrl+H handling -- and they work fine. So I suppose there is no "global" Ctrl+H handler active in my system.

**Comment by pezholio** [comment]
I'm having this problem in OSX too

**Comment by pezholio** [comment]
I **think** this may be down to `Ctrl+H` being equivalent to backspace on Unix systems. I could be wrong though, so happy to proven otherwise.

**Comment by ondras** [comment]
> I think this may be down to Ctrl+H being equivalent to backspace on Unix systems. I could be wrong though, so happy to proven otherwise.

Even if it would, a platform-independent app shall be able to distinguish Ctrl+H for its own purposes.

**Comment by kevinsawicki** [comment]
@pezholio can you open this in Electron on macOS and see what it logs for you when you press `Ctrl-H`?

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script>
      document.addEventListener('keypress', (event) => {
        console.log(event.ctrlKey, event.key);
      })
    </script>
  </head>
  <body>
    Hello
    <input>
  </body>
</html>
```

**Comment by pezholio** [comment]
I get `true "h"`

**Comment by mcnesium** [comment]
I am experiencing a related issue which I have already described [in atom forum](https://discuss.atom.io/t/swapped-ctrl-and-alt-disables-alt-keybindings/40115). On Linux I swapped Ctrl and Alt Keys in dconf, afterwards Alt-related keyboard commands do neither in Atom, nor in Chromium.

**Comment by zcbenz** [comment]
Chromium uses X11 directly to build it UI, so if you are doing special with your keyboard key maps Chromium may not be able to handle them correctly.

I'm closing this since we are not able to fix this on Electron's side, please report this to [Chromium's issues list](https://crbug.com) instead.
