### ISSUE TITLE
Add option to enable/disable Lion style fullscreen on macOS

### ISSUE THREAD

**Issue by jalvarado91** [electron/electron#8218]
* Electron version: 1.4.X
* Operating system: macOS

### Expected behavior

 This issue came mainly from a request over at zeit/hyper#526 where we would like to add a fullscreen option similar to iTerm where the user can disable Lion style full screen behavior, which puts the app in a new space. 

The expected behavior would be that if this option is disabled, going into full screen wouldn't launch the app in a new space, but simply be on top of the content in the current space.

**Comment by codebytere** [comment]
Looks like this was implemented, so I'm going to go ahead and close this.
