### ISSUE TITLE
Tray icon disappears after aprox a minute.

### ISSUE THREAD

**Issue by reggi** [electron/electron#822]
For some strange reason the tray icon disappears after a around a minute of the app running, no errors in the console or via dialog, and since the tray is the only way to interact with the app. I have to quit the terminal process or quit the process in activity monitor.

```
var app = require('app');
var Menu = require('menu');
var Tray = require('tray');
var path = require("path");

app.dock.hide();
app.on('ready', function() {
  var tray = new Tray(path.join(__dirname, "./images/black.png"));
  tray.setPressedImage(path.join(__dirname, "./images/white.png"));
  tray.setToolTip('App');
  var contextMenu = Menu.buildFromTemplate([{
    label: 'Quit',
    type: 'normal',
    click: function() {
      app.quit();
    }
  }]);
  tray.setContextMenu(contextMenu);
});
```

Thoughts? My code is pretty straight forward.

**Comment by niftylettuce** [comment]
Same issue here

**Comment by niftylettuce** [comment]
I was able to fix it by defining `var tray = null` outside the scope like @reggi did.  We definitely need to get this in the docs.

**Comment by sh4hids** [comment]
> @paulcbetts I think you were onto something, I removed the `var` defining `tray` and added `var tray = null;` like the docs have [here](https://github.com/atom/atom-shell/blob/master/docs/api/tray.md). Seems to do the trick.

Saved my day!
