### ISSUE TITLE
PokeNurse is showing nothing but a white screen after logging in

### ISSUE THREAD

**Issue by jasonlo1000** [electron/electron#8220]
* Electron version: PokeNurse 1.6.1
* Operating system: Windows 10

### Expected behavior

 Program was working fine as of yesterday.

### Actual behavior

 Now upon logging in it's showing nothing but a big white space instead of the list.

### How to reproduce

 The problem are now happening to two of my computers.

**Comment by enlight** [comment]
Perhaps you should open an issue in the [PokeNurse](https://github.com/vinnymac/PokeNurse) repo then.
