### ISSUE TITLE
Right click menu popup will pause audio playing with Audio tag and local mp3 file

### ISSUE THREAD

**Issue by zrb0001** [electron/electron#8226]
* Electron version:
1.4.12
* Operating system:
OSX 10.12.2

### Expected behavior

The sound can playing continually.

### Actual behavior

The audio sound has been paused, when menu popup disappear, the audio sound will continue play.

### How to reproduce

create a Audio tag in renderer and play a local mp3 file.

HTML inline javascript
```javascript
var remote = require('electron').remote;
var {Menu} = remote;

var audio = document.querySelector("audio");  
audio.src = "<local mp3 file>";  
audio.play();  

window.addEventListener('contextmenu', event => {
    var template = [{
        label: "Text"
    }];
    var menu = Menu.buildFromTemplate(template);
    menu.popup();
});
```

**Comment by enlight** [comment]
I'm merging this into #1854, the workaround mentioned there should work for you, i.e. instead of using `remote` send an async IPC message to the main process and popup the menu there.
