### ISSUE TITLE
Unable to install electron, Checksum Error

### ISSUE THREAD

**Issue by dineshraj01** [electron/electron#8228]
While installing electron, I get a checksum error as shown below : 

> electron@1.4.12 postinstall /home/dinesh/Documents/nodejs/electron-quick-start/node_modules/electron
> node install.js

/home/dinesh/Documents/nodejs/electron-quick-start/node_modules/electron/install.js:22
  throw err
  ^

Error: Could not parse checksum file at line 1: 
    at ChecksumParseError.Error (native)
    at new ChecksumParseError (/home/dinesh/Documents/nodejs/electron-quick-start/node_modules/sumchecker/build.js:71:127)
    at /home/dinesh/Documents/nodejs/electron-quick-start/node_modules/sumchecker/build.js:130:20
    at Array.forEach (native)
    at /home/dinesh/Documents/nodejs/electron-quick-start/node_modules/sumchecker/build.js:125:38
    at ChecksumValidator.parseChecksumFile (/home/dinesh/Documents/nodejs/electron-quick-start/node_modules/sumchecker/build.js:121:14)
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/opt/node/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.12 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.4.12 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dinesh/Documents/nodejs/electron-quick-start/npm-debug.log

I have tried cleaning cache, but no use.

**Comment by snwFlake** [comment]
How did you fix it? Having the same issue.

**Comment by tfbirk** [comment]
I had a similar issue. Renaming the SHASUM file in my user folder's _.electron_ folder did the trick: https://github.com/electron/electron/issues/7007

**Comment by snwflake** [comment]
@tfbirk Thanks, did the trick!

**Comment by saenzramiro** [comment]
Removing node_modules folder and making `npm i` to install it again solves the problem here.

**Comment by nZeus** [comment]
`npm install electron-packager -g` didn't help, `resolutions` didn't help...
But then I switched to node 6.12.0, and I could finally install it :/
