### ISSUE TITLE
Application life cycle event handler for "--squirrel-uninstall"  is not triggered on macOS

### ISSUE THREAD

**Issue by wangxiexe** [electron/electron#8230]
* Electron version:
1.4.12
* Operating system:
macOS
### Expected behavior

Application life cycle event handler is triggered

### Actual behavior

No life cycle event handler is triggered

### How to reproduce

I am using electron-builder to create app which has Squirrel.Mac support

the build output is dmg and I can install the app by drag it into application folder

but I noticed the life cycle events (which works fine on windows) like "--squirrel-uninstall" "--squirrel-updated" are not issued, and so I can not add handlers for them

I need to clear some application data like these password in keychain before the application is moved into trash, but there the handler is not called.

Is it by design or there is something else I can do ? thanks!

**Comment by MarshallOfSound** [comment]
> Is it by design or there is something else I can do ? thanks!

This is by design, the `--squirrel-uninstall` and other such CLI args are only passed by `Squirrel.Windows`

**Comment by wangxiexe** [comment]
thx, I am a newbie to macOS, so there is no way for electron app to clear the data when the app is uninstalled ? thx
