### ISSUE TITLE
one big executable vs a small one with DLLs, does it affect startup time?

### ISSUE THREAD

**Issue by MaherFa** [electron/electron#8231]
* Electron version: All including latest (1.4.12)
* Operating system: Windows 10 64-bit

### The issue (closer to a feature request)
starting an electron app (for the first time) from a DVD-DL (8.5 GB) takes **up to ~45 seconds** to start.
I have an i7-3820 CPU @ 3.60 GHz, 16.0 of RAM and an SSD drive.
I'm using the (win32-ia32) for compatibility with both CPU structures x86 and x64.
I can't use an Installer since it's requested that the app runs from the DVD and work instantly.

### What I tried
running from local drive is fast as expected. 
I found some workarounds like a splash screen or extracting to local drive than running but both cover the issue and don't fix it. app still takes too long to start.

once I start the app the 1st time and close it, 2nd time run takes almost no time. 

### Why is this an issue?
I tried working with NW.js and didn't have this issue, but I truly believe that electron is a better option overall so I'd like to keep using it if this can be improved. 

NW.js app (same app and content) runs from DVD in less than **7 seconds** on the same machine. and even less from the 2nd run and on. 

I noticed that the electron executable (electron.exe) is **61.2 MB** and the and NW.js executable (nw.exe) is **less than 1 MB** in size. with nw.dll beside it ~62.9 MB.

could this be the problem? 
can this be improved?

**Comment by zcbenz** [comment]
It is hard to say since I did not do a profile on this, but as far as I know loading a single exe is almost always faster than loading a exe and a dll together.

I suggest doing a profile to find out why it takes longer to load.

I'm closing this since https://github.com/electron/electron/issues/5830 is discussing a similar thing.
