### ISSUE TITLE
Electron chrome version does not support backdrop-filter

### ISSUE THREAD

**Issue by morlauth** [electron/electron#8232]
* Electron version: 1.4.12
* Operating system: Mac OS Sierra 10.12.1

### Expected behavior
When I use this CSS property, the background of the element should be a blurred version of the elements behind it.

### Actual behavior
Inspector says backdrop-filter is an unkown property name.

### How to reproduce
```
background: rgba(40,43,48,.75);
background-filter: blur(10px);
```

**Comment by MarshallOfSound** [comment]
You will have to wait until Chromium implements / enables this in stable.  Currently it is behind a feature flag however so you can try enabling it through the `app.commandLine.appendSwitch` method.

http://caniuse.com/#feat=css-backdrop-filter

**Comment by morlauth** [comment]
@MarshallOfSound I tried using this line of code:
`app.commandLine.appendSwitch('enable-experimental-web-platform-features');` to enable the CSS properties. That didn't work.

A also tried this: 
```
webPreferences: {
	experimentalFeatures: true,
}
```
Which also didn't work.

Any help?

Thanks!

**Comment by jiabaoyu** [comment]
@morlauth I tried a couple of times. Finally I get the right way to achieve this by the following codes. 
In the main process:
`let win = new BrowserWindow({
        height: 600,
        width: 800,
        webPreferences: { experimentalFeatures: true}
    });`

In the render process:
` #cover {
            height:100%;
            width: 100%;
            background: rgba(0,0,0,.2);
            backdrop-filter: blur(5px)
  }`

> Note that DO NOT ADD A "-webkit-" prefix before "backdrop-filter" property.

**Comment by ViolaterZ** [comment]
This doesn't work

**Comment by VirusBLITZ** [comment]
> This doesn't work

same here

**Comment by panyiwei-home** [comment]
same here，too

**Comment by VirusBLITZ** [comment]
> 

make sure you're using a recent version of electron 👍

**Comment by VirusBLITZ** [comment]
> > > same here，too
> > 
> > make sure you're using a recent version of electron 👍
> 
> Hi can you share how achieved the blur css working?

You're probably using an outdated version of electron, updating fixed it for me. All of the new Electron versions support this since a long time

**Comment by SorryToPerson** [comment]
> > > > > same here，too
> > > > 
> > > > 
> > > > make sure you're using a recent version of electron 👍
> > > 
> > > 
> > > Hi can you share how achieved the blur css working?
> > 
> > 
> > You're probably using an outdated version of electron, updating fixed it for me. All of the new Electron versions support this since a long time
> 
> i am using electron 26.0.0 but still nothing , below is my window object init:
> 
> ` win = new BrowserWindow({ width: 1920, height: 1080, fullscreen: false, transparent: true, frame: false, webPreferences: { webSecurity: true, nodeIntegration: true, contextIsolation: true, enableRemoteModule: true, experimentalFeatures: true, preload: path.join(__dirname, "./preload.js"), }, }) ;`

same here

**Comment by ulugmer** [comment]
> > > > > same here，too
> > > > 
> > > > 
> > > > make sure you're using a recent version of electron 👍
> > > 
> > > 
> > > Hi can you share how achieved the blur css working?
> > 
> > 
> > You're probably using an outdated version of electron, updating fixed it for me. All of the new Electron versions support this since a long time
> 
> i am using electron 26.0.0 but still nothing , below is my window object init:
> 
> ` win = new BrowserWindow({ width: 1920, height: 1080, fullscreen: false, transparent: true, frame: false, webPreferences: { webSecurity: true, nodeIntegration: true, contextIsolation: true, enableRemoteModule: true, experimentalFeatures: true, preload: path.join(__dirname, "./preload.js"), }, }) ;`

+1
