### ISSUE TITLE
Support create prompt on dialog.showOpenDialog

### ISSUE THREAD

**Issue by djangosdk** [electron/electron#8236]
I have requirement where when showOpenDialog , user enters path manually and it does not exist, 
another dialog pops up and asks if path should be created automatically.

However I only see a callback at https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options-callback

and i cant capture error so I can open another dialog.Electron just htorws error its self with following message
```
Path does not exist.
Check the path and try again.
```
see here as windows supports it
https://msdn.microsoft.com/en-us/library/system.windows.forms.filedialog.checkfileexists(v=vs.110).aspx

something like will be very helpful
```
openFileDialog1.CheckFileExists = true;
openFileDialog1.CheckPathExists = true;.
```

**Comment by kevinsawicki** [comment]
@djangosdk so you are just looking for the prompt to show so it will be able to call back with a path that may not exist?

**Comment by kevinsawicki** [comment]
Looks like we could just expose a new `property` that maps to the `FOS_CREATEPROMPT` option flag to enable this.

**Comment by djangosdk** [comment]
@kevinsawicki  exactly what i need ``FOS_CREATEPROMP```
