### ISSUE TITLE
Is there a way to set a custom inset for the macos traffic lights

### ISSUE THREAD

**Issue by matt3224** [electron/electron#8237]
Hi,

I am currently using `titleBarStyle: 'hidden-inset',` to inset the traffic lights, however I would very much like to inset it further as many designs feature chunky headers. Is there a way to do this?

Screenshot to illustrate my issue using inbox as an example

![screen shot 2016-12-19 at 11 49 37](https://cloud.githubusercontent.com/assets/2401925/21311864/4c84f28e-c5e1-11e6-9824-be2159213e02.png)

Thanks,

**Comment by MarshallOfSound** [comment]
Currently this is not possible, the `hidden-inset` values are hard set at the moment I believe.

**Comment by MarshallOfSound** [comment]
Oh yeah, the good ol'

GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by matt3224** [comment]
Can we make this a feature request?

**Comment by MarshallOfSound** [comment]
> The APIs provided by macOS only allow us to set the titlebar in two styles, i.e. hidden and hidden-inset, I don't know a way to perfectly reposition the buttons to arbitrary place, and I'm closing this as won't fix since it is very difficult to implement and we will not work on this.

But it you have an idea on implement this, feel free to send a pull request and we would be happy to merge.

Referenced #6821

**Comment by margox** [comment]
You can create a frameless window by setting frame to false in BrowserWindow’s options, and then make control buttons yourself in your view layer, just some button and css, electron provided some api that you can call to close/minimize/maxmize the window

**Comment by fantasticsid** [comment]
Just throwing ideas here:

It's possible to take traffic lights out of the toolbar and put them in the content view. That way we can position them any way we like, using auto layouts etc.

The reason we need to take them out of the toolbar is that the toolbar adds extra constraints to these buttons so it's hard to position them freely 

I experimented with this idea here: https://zhenchao.li/posts/2018-07-04-positioning-traffic-lights-of-your-cocoa-app.html

Happy to work on a PR if there's no strong objections :)

**Comment by matt3224** [comment]
@fantasticsid any joy on a PR?

**Comment by fantasticsid** [comment]
Still experimenting. I've got some basic cases working, but making them work with fullscreen is hard, because the system moves the buttons in/out of title bar during the fullscreen transition, and thus adding back auto resizing constraints etc. Also my experience with hacking electron is lacking..

**Comment by philippkuehn** [comment]
Is there some progress? Would love to see this feature for our app.

**Comment by philippkuehn** [comment]
This is possible with `trafficLightPosition: {x: 12, y: 42}` in electron 8. 🥳
Can be closed now.

**Comment by codebytere** [comment]
https://github.com/electron/electron/pull/21781
