### ISSUE TITLE
webContents#beginFrameSubscription overhead / measuring frame timing

### ISSUE THREAD

**Issue by lynaghk** [electron/electron#8239]
* Electron version: 1.4.12
* Operating system: OS X 10.9.5 on a 2013 MacBook Air

I'm trying to measure frame painting: the full time it takes from my code through browser layout, painting, compositing, etc., culminating in something drawn on the screen.
I also need to measure this programmatically, so I can't just use the interactive Dev Tools Timeline stuff.

I've tried using [webContents#beginFrameSubscription](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsbeginframesubscriptiononlydirty-callback), which works perfectly from a logical perspective: I start a timer, run my code, and measure the time it takes for the frame to show up.

Here are the results for a 2000x2000 hidden browser (electron code below) doing some basic tests:

![screenshot 2016-12-18 12 21 01](https://cloud.githubusercontent.com/assets/147919/21328354/654c1be2-c5e8-11e6-8962-2b6d4af8a82b.png)

Apologies for the DIY graphic; orange/blue is javascript timing, and green is when the frame shows up.
The intervals at the bottom are spaced every 10 ms, and you can see that for nearly all the tests, the frames take about 70 ms to show up --- even for tasks as simple as drawing a single rectangle in a `<canvas>` or setting top/left position on a `<div>`.

I did some more digging, and I suspect that this slowdown is due to the `beginFrameSubscription` handler itself.
I tested this hypothesis by measuring the time between calls of `requestAnimationFrame` (each invocation sets a random body background color):

![screenshot 2016-12-19 12 10 28](https://cloud.githubusercontent.com/assets/147919/21328361/6d8e49a6-c5e8-11e6-913f-9e969ebd9959.png)

The histogram at the top corresponds to a no-op `beginFrameSubscription` callback registered and the bottom has no callback.

So my two questions are:

+ Is this a bug in `beginFrameSubscription` or is this slowdown somehow unavoidable? Perhaps the framebuffer passed to the callback is copied a handful of times?

+ If the perf slowdown is inherent in `beginFrameSubscription`, what are other ways to measure the full time it takes to render a frame?

## Electron source behind the data.
(The difference between the two histograms is simply that in the second one the client doesn't send `client-ready-for-ticks`.)

```javascript
app.on('ready', function (){
  var w = new BrowserWindow({show: false,
                             frame: false,
                             focusable: false,
                             enableLargerThanScreen: true,
                             width: 2000,
                             height: 2000,
                             webPreferences: {experimentalCanvasFeatures: true}});

  //NOTE: loadURL seems to cancel any existing frame subscriptions, so we need to load before adding listeners
  w.loadURL('file://' + __dirname + '/app.html');

  ipc.on('client-ready-for-ticks', function(e){

    w.webContents.beginFrameSubscription(function(framebuffer, dirtyrect){
      w.webContents.send("frame");
    });

    e.returnValue = null;

  });

});
```

**Comment by zcbenz** [comment]
I don't really have any experience on measuring the performance of frame painting, so you must know more than me, and I'm afraid few others may have better opinion on this.

I'm closing this because no discussion happened, so there is not much meaning keeping this opened.
