### ISSUE TITLE
Going full screen crashes display driver

### ISSUE THREAD

**Issue by ytimenkov** [electron/electron#8245]
This issue originally came from VS Code: https://github.com/Microsoft/vscode/issues/17293

- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Electron quick start app 0c71d6400a25eefb808a0919e170e1c632aa7b9f
---

Steps to Reproduce with electron-quick-start app:
1. I have Lenovo P50 workstation laptop with docking station (with NVidia Quadro M2000M and Intel 530 graphics adapters)
2. When I switch to full screen with Electron window on external display connected to the docking station display just goes dark with only cursor visible.
3. When I move Electron window to built-in display and switch to full screen all displays began flicker and then I've got system notification that display driver crashed, displays went blank).

**Comment by kevinsawicki** [comment]
Are you able to provide the stack trace from the crash?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.

**Comment by rdlaner** [comment]
Hi, I am having this same issue. Using the Electron quick start  app, every time I attempt to go to full screen, the screen goes black and I can see nothing except for the cursor. If you'd still like to see a stack trace, can you tell me how to find that? Thanks.

**Comment by rdlaner** [comment]
Any guidance on this? I'm still having this problem.

**Comment by rdlaner** [comment]
?
