### ISSUE TITLE
calling desktopCapturer.getSources() freezes all renderer processes for an instance

### ISSUE THREAD

**Issue by aredfox** [electron/electron#8246]
* Electron version: 1.4.12
* Operating system: OSX, Linux, Windows 7 & Windows 10

### Expected behavior

Smooth functioning application, thus no freeze of electron BrowserWindow (renderer process) as well as main process when calling **desktopCapturer.getSources()**. Is there an alternative call maybe?

### Actual behavior

Calling code `desktopCapturer.getSources()` e.g. example code below, or in [this repo](https://github.com/aredfox/screencapturer) with example code causes **all** screens to freeze for a moment.

```
function getMainSource(desktopCapturer, screen, done) {
    const options = {
        types: ['screen'], thumbnailSize: screen.getPrimaryDisplay().workAreaSize
    }
    desktopCapturer.getSources(options, (err, sources) => {
        if (err) return console.log('Cannot capture screen: ', err)

        const isMainSource = source => source.name === 'Entire screen' || source.name === 'Screen 1'
        done(sources.filter(isMainSource)[0])
    })
}
```

### How to reproduce

Check the repo at https://github.com/aredfox/screencapturer for a build that works.
Check comment / issue aredfox/screencapturer#1 for an ongoing discussion.

**Comment by aredfox** [comment]
Addendum: it seems like the KAP developers had problems with this too. Is this a pure libchromium problem, or an electron-specific issue? Ref: https://github.com/wulkano/kap/issues/20

**Comment by aredfox** [comment]
PS: is no one else experiencing this, or what do I need to do to make it more clear to replicate this other than providing the source code I have above?

**Comment by hokein** [comment]
I can't reproduce the frozen issue on mac, but I suspect that the reason why the main process is frozen is that the main process is busy with handling `getSources` API.

After looking your code deeply, I'm a bit of surprised about the way you use `getSources` API. 

`getSources` is a highly-expensive API, it does more stuff than you thought, and requires communication with main process although it is a renderer module. For each invoke, it firstly sends a request to main process,  main process generates results for all sources and pass the results to render process. Generally, the results are not trivial because there are including images, therefore it is not recommended to poll this API.

For your use case, I'd suggest you to seek other way to implement it rather than polling `getSources` API.  You may be interested in https://github.com/electron/electron/issues/2237.

**Comment by aredfox** [comment]
thanks, I figured it's expensive indeed - but I wonder why it's blocking the entire node application as it's not shown in the docs, nor anywhere else. I thought this was not possible given the seperation of the processes.
I'll look into #2237 and see if that offers a solution!

**Comment by aredfox** [comment]
(ps: the way I use the code, I got this from an example tutorial on how to use the electron API's)

**Comment by aredfox** [comment]
Thanks for all the help and especially issue #2237 did get me on the way @hokein! 

---

If you're wanting to capture screenshots cross platform, i'd advice using the approach below in stead of relying on the built in electron-api's. Not that they're not good, but they're not suited for taking screenshots every three seconds for example.

The solution for me was the npm-module [desktop-screenshot](https://www.npmjs.com/package/desktop-screenshot) - and a npm package called [hazardous](https://www.npmjs.com/package/hazardous), as this was needed on Windows & asar execution.

The code I ended up implementing was this - it might be a source of inspiration/example for your problem.


    /* ******************************************************************** */
    /* MODULE IMPORTS */
    import { remote, nativeImage } from 'electron';
    import path from 'path';
    import os from 'os';
    import { exec } from 'child_process';
    import moment from 'moment';
    import screenshot from 'desktop-screenshot';
    /* */
    /*/********************************************************************///
    
    /* ******************************************************************** */
    /* CLASS */
    export default class ScreenshotTaker {    
        constructor() {
            this.name = "ScreenshotTaker";        
        }
    
        start(cb) {
            const fileName = `cap_${moment().format('YYYYMMDD_HHmmss')}.png`;
            const destFolder = global.config.app('capture.screenshots');
            const outputPath = path.join(destFolder, fileName);        
            const platform = os.platform();
            if(platform === 'win32') {
                this.performWindowsCapture(cb, outputPath);
            }
            if(platform === 'darwin') {
                this.performMacOSCapture(cb, outputPath);
            }
            if(platform === 'linux') {
                this.performLinuxCapture(cb, outputPath);
            }
        }
    
        performLinuxCapture(cb, outputPath) {
            // debian
            exec(`import -window root "${outputPath}"`, (error, stdout, stderr) => {
                if(error) {
                    cb(error, null, outputPath);
                } else {
                    cb(null, stdout, outputPath);
                }
            });
        }
        performMacOSCapture(cb, outputPath) {
            this.performWindowsCapture(cb, outputPath);
        }
        performWindowsCapture(cb, outputPath) {
            require('hazardous');
            screenshot(outputPath, (err, complete) => {
                if(err) {
                    cb(err, null, outputPath);
                } else {
                    cb(null, complete, outputPath);
                }
            });
        }
    }
    /*/********************************************************************///

**Comment by aredfox** [comment]
Closing this, as for me it is solved - and no specific electron issue.

**Comment by lux-lth** [comment]
I think it's a specific Electron issue.

I have a large amount of files i'm trying to move to another folder given some rules.
Using fs.rename(), or fs.renameSync(), in a loop, freezes the application screen (a progress bar should be updated but is not until the very end, it basically jumps from 0% to 100%).

This is annoying and I have no idea on how to fix this.
