### ISSUE TITLE
Setting up proxy for webview alone [Feature request]

### ISSUE THREAD

**Issue by myfrndjk** [electron/electron#8247]
Is there any option to setup proxy only for web view.
Right now I am using pac_url to route web view  traffic via proxy, but if I want to change the proxy then I have to modify the pac_url  content.
In my use case I want to route each web view request via different proxy, results in modifying pac_url content for every request.

It would be great if we have some option like

<webview src ="www.example.com" proxy:123.45.67.89 port : 8080>

**Comment by deepak1556** [comment]
You can assign a different session for the webview using the partition attribute and set proxy using [session#setProxy](https://github.com/electron/electron/blob/master/docs/api/session.md#sessetproxyconfig-callback) api.
