### ISSUE TITLE
Issue with building exe from 1.4.13

### ISSUE THREAD

**Issue by carmalou** [electron/electron#8251]
* Electron version: v1.4.13
* Operating system: Windows 10 with Parallels

### Expected behavior

When trying to build exe, the newest platform/arch zip should download (if necessary) without issue.

### Actual behavior

Newest zip is unable to download and seeing this error:
No checksum found in checksum file for "electron-v1.4.13-win32-ia32.zip".

### How to reproduce
Seeing this error when I use `electron-packager` trying to build a 32bit exe

**Comment by kevinsawicki** [comment]
Can you try removing the `C:\Users\YOUR_USERNAME_HERE\.electron\SHASUMS256.txt-1.4.13` and trying installing again?

**Comment by carmalou** [comment]
Deleted the file and tried to build again and it was successful. Thank you!

**Comment by kevinsawicki** [comment]
Closing this out, a new shasum file was published shortly after the initial 1.4.13 release that included the missing values, sorry about this.
