### ISSUE TITLE
angular2 routing  - params are not binded

### ISSUE THREAD

**Issue by maciejsobala** [electron/electron#8253]
* Electron version: 1.4.4
* Operating system: OSX

### Expected behavior

regarding to angular2 documentation: 
https://angular.io/docs/ts/latest/guide/router.html#!#route-parameters
https://angular.io/docs/ts/latest/guide/router.html#!#optional-route-parameters

properly passed parameters should be available in code.

### Actual behavior

link is constructed correctly, but parameters are not available under Router object.

### How to reproduce

routing configuration:
```
import { Routes, RouterModule } from "@angular/router";

import { ReaderComponent } from './reader/reader.component';
import { WriterComponent } from './writer/writer.component';

const routes: Routes = [
    {path: '', redirectTo: 'reader', pathMatch: 'full' },
    {path: 'reader', component: ReaderComponent },
    {path: 'writer', component: WriterComponent },
];

export const routing = RouterModule.forRoot(routes);
```

links:
```
<a [routerLink]="['/writer', {cid: 123}]">someLink</a>
<a [routerLink]="['/writer/123']">someLink</a>
<a [routerLink]="['/writer/123', {cid: 123}]">someLink</a>
```

component:
```
export class WriterComponent {
constructor(private router: Router, private route: ActivatedRoute) {

        console.log(this.router.routerState.snapshot); //here I can see that params are passed in URL
        this.route.params.subscribe(v => {
            console.log(v); //here we got empty object
            console.log(v['cid']); //here I should get my param
        });

        this.route.queryParams.subscribe(v => {
            console.log(v); //here we got empty object
            console.log(v['cid']); //here I should get my param
        });
    }
```

**Comment by MarshallOfSound** [comment]
I'm not sure how this is an Electron issue?

AFAIK from similar questions asked before you need to be aware that you are using a `file://` URL in Electron and as such some JS based routers don't work without specific config.  I'd recommend looking around for a working example.  If this is an actual issue please clarify 👍

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
