### ISSUE TITLE
GetUserMedia stream not muting or toggling camera.

### ISSUE THREAD

**Issue by WBMI** [electron/electron#8255]
**Expected Behavior**
Stream to remote client does not display video or sound depending on toggle

The code works in the browser but fails in electron. In the local stream the camera appears off but to the other client, the camera is still on. The same follows for muting audio. The code works in latest Chromium build. OS is OSX 10.12.

**Code used**
navigator.getUserMedia({ "audio": true, "video": true }, function (stream) {
  localStreams.push(stream);
 ......
  }

cameraOff = function(mute) {
  if (mute) {
    for (var i=0; i < localStreams.length; i++) {
     localStreams[i].getVideoTracks()[0].enabled = false;
    }
  } 
  else {
    for (var i=0; i < localStreams.length; i++) {
      localStreams[i].getVideoTracks()[0].enabled = true;
    }
  }
noCamera = mute;
}

muteOn = function(mute) {
  if (mute) {
    for (var i=0; i < localStreams.length; i++) {
     localStreams[i].getAudioTracks()[0].enabled = false;
    localStreams[i].getAudioTracks()[0].muted = true;
    }
  } else {
    for (var i=0; i < localStreams.length; i++) {
      localStreams[i].getAudioTracks()[0].enabled = true;
      localStreams[i].getAudioTracks()[0].muted = false;
    }
  }
 isMuted = mute;
}

**Comment by OWMI** [comment]
Basically Electron continues to stream the non modified stream where the browser makes the modifications to the stream.

**Comment by hokein** [comment]
Could you provide a complete example? It is hard for us to reproduce the issue with your partial code.

**Comment by zcbenz** [comment]
Closing until more information is provided.
