### ISSUE TITLE
command not found: electron

### ISSUE THREAD

**Issue by hon** [electron/electron#8257]
* Electron version:
1.4.13
* Operating system:
Darwin Kernel Version 16.1.0
### Expected behavior

run electron successfully

### Actual behavior

command not found: electron

### How to reproduce

I installed electron package:

yarn global add electron
yarn global v0.18.1
warning No license field
[1/4] 🔍 Resolving packages...
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
[2/4] 🚚 Fetching packages...
[3/4] 🔗 Linking dependencies...
[4/4] 📃 Building fresh packages...
success Installed electron@1.4.13 with binaries:
- electron

I can see is it in global package list:
yarn global ls
yarn global v0.18.1
warning No license field
info electron@1.4.13 has binaries:

electron
info neon-cli@0.1.7 has binaries:
neon
info webpack-dev-server@2.1.0-beta.10 has binaries:
webpack-dev-server
info webpack@2.1.0-beta.25 has binaries:
webpack
✨ Done in 2.60s.
But, when I run electron:
electron
zsh: command not found: electron

**Comment by MarshallOfSound** [comment]
This is another `yarn` issue.  You probably have to add the `yarn` global package bin directory to your path.  

Try doing `yarn global add electron-packager` and then see if the `electron-packager` command is available globally.

**Comment by hon** [comment]
Yes, it is yarn issue. it's ok with npm.

**Comment by thomasjo** [comment]
> Yes, it is yarn issue. it's ok with npm.

Good — don't forget to close this issue.

**Comment by kevinsawicki** [comment]
Closing this out.
