### ISSUE TITLE
Spawn a new Electron instance from an Electron app

### ISSUE THREAD

**Issue by remicoges** [electron/electron#8260]
Hello,

I am writing an electron app that needs a child process to get usb events.
I wrote a node.js script that reads from my usb device and I want to spawn it inside my electron app and read on its stdout.

When I spawn it with node I get a module mismatch error because I use the usb module in my electron app as well. 

`                            const sub = child_process.spawn('/usr/local/bin/node', ['captureEvent.js']);
`

When I run the script with electron I don't get this error but I am not able to launch a new Instance of electron

`                            const sub = child_process.spawn('/usr/local/bin/electron', ['captureEvent.js']);
`

returns me

`env: node: No such file or directory`

Is it possible to spawn a CLI electron instance (No window) in an Electron app ? 

Thanks for your help

**Comment by thomasjo** [comment]
The error message clearly tells you that the `node` executable is not found in any of the directories listed in your `PATH` environment variable. You need to ensure `/usr/local/bin` is added to `PATH`, and addition you need to ensure the spawned child process is seeing the "correct" `PATH` variable as well. 

To check whether `node` is discoverable at the user/system level, run e.g. `which node` in a terminal.

**Comment by remicoges** [comment]
`echo $PATH`

returns me 

`/usr/local/php5/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

`which node`

returns me 

`/usr/local/bin/node`

`which electron`

returns me 

`/usr/local/bin/node`

Everything seems OK there, and child_process seems to access this PATH

**Comment by kevinsawicki** [comment]
> Is it possible to spawn a CLI electron instance (No window) in an Electron app ?

Yes, you have to set the `ELECTRON_RUN_AS_NODE` environment variable though.

http://electron.atom.io/docs/api/environment-variables/#electronrunasnode

You also want to call spawn with the path of `process.execPath`.

**Comment by remicoges** [comment]
Thanks ! 

I see the `ELECTRON_RUN_AS_NODE` is under Development variables, how will this work in my packaged production app ?

**Comment by kevinsawicki** [comment]
> I see the ELECTRON_RUN_AS_NODE is under Development variables, how will this work in my packaged production app ?

That is incorrect in the docs (I'll fix it), it is intended for both production and development.
