### ISSUE TITLE
customElements is not defined

### ISSUE THREAD

**Issue by hon** [electron/electron#8261]
* Electron version: v1.4.13
* Operating system: Darwin Kernel Version 16.1.0

### Expected behavior
customElement should be invoked as lasted Chrome does.

### Actual behavior
customElements is not defined

### How to reproduce
run customElements in electron -> debug tool -> console tab

**Comment by enlight** [comment]
This API was released in Chromium 54, the latest Electron release is still on Chromium 53. I don't know if there's a flag to enable this in v53.

**Comment by astoilkov** [comment]
When Electron will make a release that includes Chromium 54? It seems like this time it takes longer than usual for the update to the next Chromium version.

**Comment by thomasjo** [comment]
@astoilkov See https://github.com/electron/electron/pull/7909. If you think it's taking too long, feel free to help out.

**Comment by kevinsawicki** [comment]
>  It seems like this time it takes longer than usual for the update to the next Chromium version.

This is because Chrome 54 switched to a new build system and it is taking time to port `libchromiumcontent` to this new system.

See https://github.com/electron/libchromiumcontent/pull/239 for more details.

**Comment by kevinsawicki** [comment]
Closing this out since this can be tracked by the 54 upgrade going on in #7909
