### ISSUE TITLE
Electron desktop application leaving traces on XenApp 6.5

### ISSUE THREAD

**Issue by madipor** [electron/electron#8262]
I created simple Electron desktop application and run it with Citrix XenApp. When I try to drag the application icon or open/close the menu (click on icon button will open new window), the display application leaving traces.

any idea?

**Comment by kevinsawicki** [comment]
> the display application leaving traces.

Do you mean like visual artifacts?

Can you include an image or screen recording of what you are seeing?

**Comment by madipor** [comment]
https://youtu.be/AAc-HvbSbNE

Please see the second example, when I run the application on Citrix (first I run on my desktop and it works fine) 
In both cases, it's the same application.
thanks
