### ISSUE TITLE
Slow refresh of UI

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron/electron#8270]
Please see attached images.

![a](https://cloud.githubusercontent.com/assets/20187287/21435815/0dd3afc4-c87c-11e6-91e8-a49b580c00cd.png)

When I click the "full node" button, I hide/show certain elements via js. After that is done, I resize the window to the new size of the content via : 

`    electron.remote.getCurrentWindow().setContentSize(600, parseInt(document.documentElement.scrollHeight, 10) + parseInt(document.getElementById("footer").scrollHeight, 10), false);
`

As you can see in the image below, the window is already resized (more whitespace at the bottom), even though the elements have not yet been hidden/shown.

![b](https://cloud.githubusercontent.com/assets/20187287/21435819/0f6b2880-c87c-11e6-83eb-bb8f1a7afb74.png)

In the below images, the UI finally refreshes, but as you can see the footer is not yet attached to the bottom of the window. This even though the footer has simple CSS to absolutely position it.

```
#footer {
  position: absolute;
  bottom: 0;
  left: 0; 
  right: 0;
  padding: 20px;
  background-color: #f1f1f1;
}

```
![c](https://cloud.githubusercontent.com/assets/20187287/21435820/10f8edcc-c87c-11e6-994f-a035495b033f.png)

Finally, the footer is shown in the correct position. Note also that only now the correct, updated size is displayed in the upper right corner (developer tools were open):

![d](https://cloud.githubusercontent.com/assets/20187287/21435822/124a39a6-c87c-11e6-90d6-db2eb4a38489.png)

This of course all takes place in a split second, but it is a jarring effect and can be noticed. 

Is there anything that can be done about this? This is all done with pure javascript, so there should no library delays of any kind..

**Comment by kevinsawicki** [comment]
> electron.remote.getCurrentWindow().setContentSize(600, parseInt(document.documentElement.scrollHeight, 10) + parseInt(document.getElementById("footer").scrollHeight, 10), false);

Using the `remote` API causes a synchronous IPC call to be made between the render process and the main process. This can cause issues with redraw while the call is blocking.

Have you tried making it async and seeing if it works as expected?

You should be able to do something like:

### Renderer Process

```js
require('electron').ipcRenderer.send('set-content-size', 600, parseInt(document.documentElement.scrollHeight, 10) + parseInt(document.getElementById("footer").scrollHeight, 10))
```

### Main Process

```js
ipcMain.on('set-content-size', (event, width, height) => {
  BrowserWindow.fromWebContents(event.sender).setContentSize(width, height, false)
})
```

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
