### ISSUE TITLE
BrowserWindow ctor truncates all heights in multi-monitor setup to main monitor height

### ISSUE THREAD

**Issue by rob3c** [electron/electron#8271]
* Electron version: 1.4.12
* Operating system: Windows 8

### Expected behavior

I expect the height of a window to equal the `height` option pass into the `BrowserWindow` constructor when using multiple monitors (possibly truncated by the `maxHeight` option, but only if it is set).

### Actual behavior

What actually happens is, all initial window heights (set via the `BrowserWindow` ctor) get truncated to the height of the main monitor in a multi-monitor configuration, even when there is no `maxHeight` option set and even when the `maxHeight` option is set to a value larger than the main monitor height. This is especially a problem with external portrait monitors, where the height truncation significantly affects usage of the full window and obviates the point of the portrait orientation.

Fortunately, the windows can be resized after construction. However, this bug prevents clean restoration of saved window states, since you can't easily create and restore a window with the same size and location as in the previous session using the `BrowserWindow` constructor options.

### How to reproduce

1. Install electron on a multi-monitor system (e.g. left external 1050x1680 portrait monitor, 1920x1080 main monitor)
2. Create a window on either monitor with a height greater than 1080:
```javascript
var winMainLandscape = new BrowserWindow({
  x: 0, 
  y: 0, 
  height: 2000, // truncated to 1080 even tho no maxHeight set (should be no limit acc. to docs)
  width: 960,
  //maxHeight: anything > 1080 is ignored here and doesn't help
});

var winLeftPortrait = new BrowserWindow({
  x: -1050, // position the window at the left edge of the left external portrait monitor
  y: 30,
  height: 1650, // truncated to 1080, which is the height of the main landscape monitor
  width: 1050,
  //maxHeight doesn't help here, either
});
```

**Comment by zcbenz** [comment]
While I would like to fix this, but I'm afraid this is a bug of Windows itself and we are unable to fix this on Electron's side. So I'm closing this as won't fix.

You might try using the `enableLargerThanScreen` option to this.
