### ISSUE TITLE
BrowserWindow send keyboard input event

### ISSUE THREAD

**Issue by kvidzibo** [electron/electron#8273]
I have spent quiet some time trying to solve this, maybe I just don't know how to do it. So I though I should just write here.
 
* Electron version: 1.4.10
* Operating system: Linux

I am creating an BrowserWindow:
`win = new BrowserWindow({width: 950, height: 1029, x: 975, y: 0,
                webPreferences: {
                    nodeIntegration: false,
                    preload: 'Preload.js'
                }
            });
`
All is fine and working there.
I am focusing on an input element, by clicking it (I can see that cursor is appearing inside input so I assume focus is working.).
And I try to send keyboard input events (type any letter or anything), since I am focused on element it should just work. However it's not.
I am using:
`
        win.webContents.sendInputEvent({keyCode: 'A', type: 'keyDown'});
        win.webContents.sendInputEvent({keyCode: 'A', type: 'keyUp'});
`
I tried debugging it with my Preload.js, so I ended up having:
`
        $('html').on('keydown', (e) => {
            console.log(String.fromCharCode(e.which));
        }).on('keyup', (e) => {
            console.log(String.fromCharCode(e.which));
        }).on('keypress', (e) => {
            console.log(String.fromCharCode(e.which));
        });
`
So I figured out that this triggers keydown and keyup and I can see 'A' in console, however it does not trigger keypress. If I type manually it triggers all 3 events.

**Comment by kvidzibo** [comment]
`win.webContents.replace(text);`
does the trick, it enters the text to selected input, however it does not trigger keyboard events.

**Comment by kevinsawicki** [comment]
I think you want to use a `char` event like so:

```js
win.webContents.sendInputEvent({keyCode: 'A', type: 'char'})
```

This triggers a `keypress` event and puts the text in the `<input>`.

This was the page I tested in:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script>
      document.addEventListener('keypress', (event) => {
        console.log(event.key);
      })
    </script>
  </head>
  <body>
    Hello
    <input>
  </body>
</html>
```

Does this work for you?

**Comment by kvidzibo** [comment]
ok it does work if I do:
`
win.webContents.sendInputEvent({keyCode: 'A', type: 'keyDown'}); 
win.webContents.sendInputEvent({keyCode: 'A', type: 'char'});
win.webContents.sendInputEvent({keyCode: 'A', type: 'keyUp'});
`

but it does not work if I do:
`
win.webContents.sendInputEvent({keyCode: 'A', type: 'char'});
`
is this normal? in fact if I do the following none of events are triggered.
Thanks for help.

**Comment by kevinsawicki** [comment]
> is this normal? in fact if I do the following none of events are triggered.

Yes, I believe it is, if your code needs to receive all three events then you'll need to send all three events using `sendInputEvent`.

Closing this out.
