### ISSUE TITLE
Unpinning electron app windows at TaskBar make task menu disappear

### ISSUE THREAD

**Issue by WarmVissarutRonaldoDude** [electron/electron#8276]
* Electron version: 1.4.13
* Operating system: Windows 10 64bit

### Expected behavior

should pinning/unpinning with not affect to taskbar menus

### Actual behavior

when unpinning it's remove all of taskbar menus (including pinning menu)

### How to reproduce

1. pinning app at taskbar
2. unpinning app at taskbar

**Comment by kevinsawicki** [comment]
Can you include a small reproduction app that demonstrates this behavior?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
