### ISSUE TITLE
<webview> contents not resized automatically when <webview> made visible

### ISSUE THREAD

**Issue by TimNZ** [electron/electron#8277]
* Electron version: All
* Operating system: All

### Expected behavior

&lt;webview&gt; contents should resize automatically when parent webview goes from hidden -> visible

### Actual behavior

On resize of parent/container and hidden &lt;webview&gt; is made visible webview has been resized but contents are still sized to the old dimensions when made hidden.

### How to reproduce

* Create a page &lt;webview&gt; with 100% width/height
* Set webview hidden
* Resize window
* Show webview
* webview has new dimensions, contents not redrawn to reflect new size
* Resize BrowserWindow and contents are redrawn and sized correctly.

**Comment by frankhale** [comment]
Cannot find any test app associated with #7000

Are up using `display: inline-flex`?

`Please note that the webview tag’s style uses display:flex; internally to ensure the child object element fills the full height and width of its webview container when used with traditional and flexbox layouts (since v0.36.11). Please do not overwrite the default display:flex; CSS property, unless specifying display:inline-flex; for inline layout.`

http://electron.atom.io/docs/api/web-view-tag/

**Comment by frankhale** [comment]
This is what I typically use in on webviews that I want to fill the entire window:

>#webview {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: inline-flex !important;
}

**Comment by TimNZ** [comment]
Nope, makes no difference.  

I had another look via DevTools and see that the webview itself and the shadow root embedded object are resized and show the correct dimensions.  It is the content that hasn't also been redrawn  to reflect the resize.

There seems to be a few issues around webview and content redraws though nothing directly related.
#6783 #7375 and others

In this case I just think a redraw should be forced on visibility and isn't.

You can see in the screenshot the selected webview element has correct size but content is old size when made hidden.
I then resized container and made visible again.

<img width="909" alt="google chrome - github com - - screen shot 24-12-2016 2 16 22 pm" src="https://cloud.githubusercontent.com/assets/1051701/21464520/483cf788-c9e4-11e6-8ce8-fc6096be29b8.png">

**Comment by frankhale** [comment]
Will this work around the issue? https://github.com/electron/electron/pull/7658

**Comment by TimNZ** [comment]
Thanks.  I knew there are work-arounds, reporting it as I (still) see it as a bug.

**Comment by miniak** [comment]
@TimNZ Please re-open if it still reproduces in Electron >= 3. The `<webview>` has been re-implemented using [oop-iframes](https://www.chromium.org/developers/design-documents/oop-iframes)
