### ISSUE TITLE
Both local and global electron installation freezes in mac sierra

### ISSUE THREAD

**Issue by biks152207** [electron/electron#8282]
I tried to install electron globally and even locally but it freezes. the exact terminal logs is given below

> electron@1.4.13 postinstall /Users/bikram/.nvm/versions/node/v6.3.1/lib/node_modules/electron
> node install.js

Please help me

**Comment by MarshallOfSound** [comment]
@biks152207 Are you behind a proxy or VPN?  That step attempts to download the build artifact from GitHub releases.  Check if you can download the release file manually here

https://github.com/electron/electron/releases

**Comment by elmasse** [comment]
I have experienced the same issue. Finally, with some patience (and help from caffeinate) electron installed successfully. It seems that downloading the file from github took around 30 mins :/

**Comment by kevinsawicki** [comment]
>  It seems that downloading the file from github took around 30 mins 

Yes, depending on your location and network it can take some time since it is downloading ~45MB.

You can run `npm install electron --verbose` to get a progress bar of the download with how much is left to go.

Closing this out.
