### ISSUE TITLE
Unwanted menu items "Start Dictation" and "Emoji & Symbols" on macOS

### ISSUE THREAD

**Issue by mikecao** [electron/electron#8283]
* Electron version: 1.4.13
* Operating system: macOS 10.12.1

### Expected behavior

I'm creating a menu where I have some items under an Edit label. I expect to only see the menu items I declared to appear.

### Actual behavior

macOS is adding two additional entries, "Start Dictation..." and "Emoji & Symbols".

### How to reproduce

Create a menu with an Edit label and some items.

```
[
  {
    "label": "Edit",
    "submenu": [
      {
        "label": "Item 1"
      },
      {
        "label": "Item 2"
      }
    ]
  }
]
```

**Comment by kevinsawicki** [comment]
Looks like these can be removed using the `systemPreferences` API.

You should be able to exclude them at the very beginning of your `main.js` file.

```js
const {systemPreferences} = require('electron')

systemPreferences.setUserDefault('NSDisabledDictationMenuItem', 'boolean', true)
systemPreferences.setUserDefault('NSDisabledCharacterPaletteMenuItem', 'boolean', true)
```

https://stackoverflow.com/questions/21369736/remove-start-dictation-and-special-characters-from-menu/30046514

**Comment by kevinsawicki** [comment]
Closing this out since the macOS default is to include them and the preferences can be used to revert this behavior for application's that don't want to include them.

**Comment by onassar** [comment]
@kevinsawicki is it as simple as including the following code after the Menu is created?
I'm having trouble getting them removed..

    (...)
    const menu = Menu.buildFromTemplate(template)
    Menu.setApplicationMenu(menu)

    const {systemPreferences} = require('electron')

    systemPreferences.setUserDefault('NSDisabledDictationMenuItem', 'boolean', true)
    systemPreferences.setUserDefault('NSDisabledCharacterPaletteMenuItem', 'boolean', true)

**Comment by apurvaSynerzip** [comment]
@kevinsawicki  How can we do the same for windows environment?

**Comment by BeatriceThalo** [comment]
@onassar For mac, the `Menu` must be set within the `app.on('ready')` block, but the `systemPreferences` must be set before/outside of that block in the electron.js file.
