### ISSUE TITLE
Cursive fonts not cursive.

### ISSUE THREAD

**Issue by teleclimber** [electron/electron#8286]
If I set the style on any text in a `BrowserWindow` as such:

```
P {
   font-family: cursive;
}
```

...I would expect that text to take on a "cursive" look, much as it does when I apply the same style to a page loaded in Chrome Browser.

However in Electron 1.4.12 on Mac it looks like it's `serif`.

`cursive` is one of the W3C's five standard styles along with `serif`, `sans-serif`, `monospace`, and `fantasy` [1]. All of these work as expected in Electron except `cursive`.

It seems it should work just like the others. I presume it's just an omission somewhere?

Thanks!

[1] https://www.w3.org/wiki/CSS/Properties/font-family

**Comment by kevinsawicki** [comment]
Looking at the dev tools, it appears to be rendering using `Times New Roman` instead of `Apple Chancery`.

**Comment by kevinsawicki** [comment]
Looks like Chrome sets it defaults to be `Script` for `cursive` and `Impact` for `fantasy`.

https://cs.chromium.org/chromium/src/content/public/common/web_preferences.cc?l=232
