### ISSUE TITLE
electron require c++ module is error

### ISSUE THREAD

**Issue by fengjiannan2010** [electron/electron#8289]
* Electron version:1.4.1.3
* Operating system:linux

error   info:
Uncaught Error: Module version mismatch. Expected 50, got 48.

Error file:  Electron_asar.js

  // Override APIs that rely on passing file path instead of content to C++.
  const overrideAPISync = function (module, name, arg) {
    if (arg == null) {
      arg = 0
    }
    const old = module[name]
    module[name] = function () {
      const p = arguments[arg]
      const [isAsar, asarPath, filePath] = splitPath(p)
      if (!isAsar) {
         **return old.apply(this, arguments)      this line is error**
      }

      const archive = getOrCreateArchive(asarPath)
      if (!archive) {
        invalidArchiveError(asarPath)
      }

      const newPath = archive.copyFileOut(filePath)
      if (!newPath) {
        notFoundError(asarPath, filePath)
      }

      arguments[arg] = newPath
      return old.apply(this, arguments)
    }
  }

**Comment by MarshallOfSound** [comment]
See the docs on using native mode modules

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
