### ISSUE TITLE
The Quick Start Guide link is broken

### ISSUE THREAD

**Issue by DamnedScholar** [electron/electron#8292]
[Commit b22eb0d](https://github.com/electron/electron/commit/b22eb0d65fb103e64f154bfae3b9af207cd24728) changed the Quick Start Guide link on [About](http://electron.atom.io/docs/tutorial/about#about-electron) from absolute to relative and now the link goes to `http://electron.atom.io/docs/quick-start`, excluding the `tutorial/`.

@thorbenegberts

**Comment by thorbenegberts** [comment]
@zeke any suggestion? Pull Request was https://github.com/electron/electron/pull/8265

**Comment by zeke** [comment]
This works fine on GitHub but not the website, so I filed a new issue at https://github.com/electron/electron.atom.io/issues/646

Thanks for reporting.
