### ISSUE TITLE
No way/API to know why a window is closing

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#8293]
* Electron version: 1.4.13
* Operating system: macOS

I am explaining the problem with a real world scenario so it is easier to understand.

There is no way to implement hot exit. By hot exit I mean - store the state of multiple windows when application quits so when started again the state could be restored. Hot exit shouldn't be turned on when a user is closing a window using the close button but instead a dialog asking if they want to save or disregard unsaved changes should appear.

For hot exit to work Electron should provide a mechanism to determine if `BrowserWindow` is being closed by the user or is being closed because the application is quitting. This seems easy at first because we could subscribe to `app.before-quit` event and raise a flag if the app is quitting.

```javascript
var quitting = false;
app.on('before-quit', function () {
  quitting = true;
});
browserWindow.on('close', function () {
  if (quitting) {
    // turn on hot exit and save window state 
  } else {
    // show dialog if there are any unsaved changes
  }
});
```

This works in the typical case but not if you want to restart the app(and for sure want to restore the state) after an update have been download. Calling `autoUpdater.quitAndInstall()` makes `before-quit` event called after the windows are closed and the above code starts failing.

There seems to be no way in Electron to properly determine if the app is quitting so you could perform an action in the `browserWindow.close` event.

**Comment by kevinsawicki** [comment]
> Calling autoUpdater.quitAndInstall()

Since you are explicitly calling this in your application, could you just track this case in your app and not perform the "hot exit" when this happens?

**Comment by astoilkov** [comment]
Yes. I can. However, the code regarding hot exit is actually in a private reusable module called `electron-cache` which decides whether to save or not. I could hack it and raise a flag before calling `autoUpdater.quitAndInstall()` but this will defeat the purpose of having a module.

I could workaround this as you suggested for now and reimplement the module inside of the app but it will be great if the API provides a clean way to know the reason for the window close.

@kevinsawicki Do you know why the behaviour for `quitAndInstall()` have been chosen to not follow the same order of event firing?

**Comment by MarshallOfSound** [comment]
@astoilkov Would a potential solution to this issue be to emit an event (maybe `before-quit-for-update` or similar) specifically when `quitAndInstall()` is called?  Then `electron-cache` can be modified to listen for that event as well?

**Comment by astoilkov** [comment]
Yes. Absolutely.

**Comment by kevinsawicki** [comment]
> Would that be an acceptable solution to be merged in?

Yeah, a new event for this seems good 👍
