### ISSUE TITLE
AutoUpdater throws an error before emitting update-downloaded

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#8294]
* Electron version: 1.4.13 (started from 1.4.7)
* Operating system: macOS

### Expected behavior

The `autoUpdater` should call `update-available` then `update-downloaded`.

### Actual behavior

The `autoUpdater` triggers `update-available`, `error` and then after few seconds `update-downloaded`.

The following error occurs:

`The folder “Caret.zip” doesn’t exist.: The folder doesn’t exist.`
```
Error
    at /Users/astoilkov/Caret/release/Caret.app/Contents/Resources/electron.asar/renderer/api/remote.js:267:16
    at metaToPlainObject (/Users/astoilkov/Caret/release/Caret.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:5)
    at metaToValue (/Users/astoilkov/Caret/release/Caret.app/Contents/Resources/electron.asar/renderer/api/remote.js:213:14)
    at metaToValue (/Users/astoilkov/Caret/release/Caret.app/Contents/Resources/electron.asar/renderer/api/remote.js:203:22)
    at EventEmitter.<anonymous> (/Users/astoilkov/Caret/release/Caret.app/Contents/Resources/electron.asar/renderer/api/remote.js:282:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

This started happening after the 1.4.7 release in which Squirrel.Mac was updated to 0.3.0. If you think this should be reported to Squirrel.Mac please let me know so I could do so but please leave this issue open so this is left to remind us to update the dependency in Electron.

**Comment by joshaber** [comment]
No, this doesn't look familiar. A quick search through Squirrel.Mac didn't show any obvious source of that error. We'll need more information to be able to debug.

**Comment by astoilkov** [comment]
Ok. I caught the problem. It's not caused by Squirrel.Mac but instead by Electron. I did replicate the problem under Windows too (the error there was different).

The problem appears when you call `autoUpdater.checkForUpdates()` a second time after you already called it.

I searched through the issues and I found https://github.com/electron/electron/issues/5097. Which seems to be fixed but it seems it doesn't work anymore.

**Comment by cruzerld** [comment]
Yeah, I'm seeing this issue too on Mac.

When I check for updates after an update has already been downloaded, especially if no new update has been downloaded (IE I haven't restarted but I check for updates again) then it says no update available but when I call quitAndInstall() it errors and says there is no app available to install.

I'm using version 1.4.12. I'll check to see if the same issue is true for more recent versions.

**Comment by zcbenz** [comment]
I'm merging this to https://github.com/electron/electron/issues/7792.
