### ISSUE TITLE
Can't increase the layout size and font size of my app ?

### ISSUE THREAD

**Issue by nishant09** [electron/electron#8296]
* Electron version: 1.3.1
* Operating system: Windows,MAC osx

### Expected behavior
ctrl + plus(zoom-in) and ctrl + minus(zoom-out) should increase and decrease the layout size respectively

### Actual behavior
nothing happens

I couldn't find the option in the menu to increase the font-size also 
Are these something I've to implement on my side ? If so, then can you guide me how ?

Thank you

**Comment by kevinsawicki** [comment]
> Electron version: 1.3.1

`zoomin` and `zoomout` menu item roles were added in Electron 1.3.3 that can be used to have a default zoom behavior in the menu and keyboard shortcut.

There is an example of them at http://electron.atom.io/docs/api/menu/#examples
