### ISSUE TITLE
Hey, what's the `process.mas` meaning

### ISSUE THREAD

**Issue by WildDylan** [electron/electron#8300]
Can you explain this code:

```javascript
function makeSingleInstance() {
    if (process.mas) return false;

    return app.makeSingleInstance(function () {
      if (mainWindow) {
        if (mainWindow.isMinimized()) mainWindow.restore();
        mainWindow.focus();
      }
    });
  }
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

A: https://github.com/electron/electron/blob/master/docs/api/process.md#processmas

**Comment by WildDylan** [comment]
Thanks for your fast response.

**Comment by paulcbetts** [comment]
makeSingleInstance doesn't work in the App Store build which has a bunch of features stripped in order to be compatible with Apple's dumb checks, "mas" is the Apple abbreviation for Mac App Store
