### ISSUE TITLE
Global Shortcut broken on windows

### ISSUE THREAD

**Issue by blainesch** [electron/electron#8301]
* Electron version: 1.4.13
* Operating system: Windows 10

### Expected behavior

When I register a global shortcut it works correctly.

### Actual behavior

If I import `systemPreferences` they no longer trigger

### How to reproduce

1. Clone [this repo](https://github.com/blainesch/electron-quick-start).
1. `npm install` and `npm start` then hit `alt+space`
1. ASSERT console log occured
1. Uncomment [this line](https://github.com/blainesch/electron-quick-start/blob/master/main.js#L2)
1. `npm start` then hit `alt+space`
1. ASSERT console log did NOT occur.

**Comment by blainesch** [comment]
I did a few tests, and this appears to be working in `1.4.3` and broken in `1.4.4`

[Changelog](https://github.com/electron/electron/compare/v1.4.3...v1.4.4?expand=1)

**Comment by MarshallOfSound** [comment]
@blainesch Closing out in favour of #7859 

There is a discussion of this issue on that thread 👍
