### ISSUE TITLE
Large size http request been cut off when through protocol registerHttpProtocol API

### ISSUE THREAD

**Issue by x-yao** [electron/electron#8302]
* Electron version:1.4.12
* Operating system:macOS Sierra

### Expected behavior

When I Use registerHttpProtocol to watch http requests and let original request callback to the browser.Expected all request work find.

	protocol.interceptHttpProtocol('http',(request, callback) => {
		let postData;
		if (request.uploadData) {
			postData = request.uploadData[0].bytes.toString();
		}
		let par = {
			url:request.url,
			method:request.method
		}
		if (request.method == "POST") {
			par.session = null;
			par.uploadData = {
				contentType:'text/html',
				data: postData
			}
		}else{
			par.session = null
		}
		callback(par)
	}, (error) => {
		if (error) console.error('Failed to register protocol')
	})

Expected like this : 
![Expected](https://img.kuaidadi.com/cms/img/upload_c20a77380e92bf47faec9741cce856b9.png)

### Actual behavior
When request a large size file like huge non-compressed javascript(more than 40000 lines) it would be cut off through protocol registerHttpProtocol API and if use WebRequest API it would not be cut off.

Actual this : 
![Actual](https://img.kuaidadi.com/cms/img/upload_bf1698ffeeab55f1cfd4eced3f1d6a80.png)

**Comment by sofianguy** [comment]
Thanks for contributing!

We are no longer releasing bug fixes for versions of Electron older than 1.5. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.

**Comment by megahertz** [comment]
The same issue occurs with Electron v8.0.1 on Linux with the simple handler. 2mb gif file is always corrupted. 

```js
 function onHttpsRequest(request: Electron.Request, callback) {
    console.log(request);
    callback(request);
  }
protocol.registerHttpProtocol('https', handler);
``

**Comment by danielweck** [comment]
I'm having the same issue with a 5MB PNG image file, which gets truncated when passing through `registerHttpProtocol()`, but works fine when delivered directly via its HTTP source (a local Express server). I tried changing the way the HTTP response is generated, the problem occurs with both a fully-loaded response body (byte buffer), and a stream pipe.
I can reproduce this on Electron v`7`, `8`, and `9`.

**Comment by danielweck** [comment]
Screenshots:

![Screenshot 2020-03-27 at 20 48 42](https://user-images.githubusercontent.com/625201/77799324-72060f00-706c-11ea-8c64-92c4950a3e1b.png)

![Screenshot 2020-03-27 at 20 49 05](https://user-images.githubusercontent.com/625201/77799321-703c4b80-706c-11ea-8fd1-923acf6f78ce.png)

**Comment by danielweck** [comment]
I fixed this by using `registerStreamProtocol()` instead of `registerHttpProtocol()`: I create an HTTP request manually and I pipe the response into `stream.PassThrough` which is a `ReadableStream` (I pass the `StreamProtocolResponse` object to the result callback so that I can forward the response headers and HTTP status code)

**Comment by danielweck** [comment]
Follow-up in this open issue:
https://github.com/electron/electron/issues/21018#issuecomment-605893836

**Comment by danielweck** [comment]
PS: note that registerStreamProtocol() has its own issues, notably when piping HTTP 206 response streams (partial byte range requests). See link in previous comment above for details.
