### ISSUE TITLE
invalid WIN32 path characters

### ISSUE THREAD

**Issue by anandfingertip** [electron/electron#8304]
I am not able to install it in my computer. I have reinstalled the node and npm but it dod not help.

Error: C:\Users\Anand\AppData\Local\Temp;C:\Work\apache-maven-3.2.5-bin\apache-maven-3.2.5\bin;C:\Program Files\Java\jdk1.8.0_31\bin;.;\electron-tmp-download-14672-1483024596459 contains invalid WIN32 path characters.
    at Object.mkdirs (c:\Work\Desktop-App\electron-quick-start\node_modules\fs-extra\lib\mkdirs\mkdirs.js:16:20)
    at ElectronDownloader.createTempDir (c:\Work\Desktop-App\electron-quick-start\node_modules\electron-download\build\index.js:104:10)
    at c:\Work\Desktop-App\electron-quick-start\node_modules\electron-download\build\index.js:158:16
    at c:\Work\Desktop-App\electron-quick-start\node_modules\electron-download\build\index.js:97:9
    at c:\Work\Desktop-App\electron-quick-start\node_modules\fs-extra\lib\mkdirs\mkdirs.js:54:16
    at c:\Work\Desktop-App\electron-quick-start\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:111:15)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.4.13 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Work\Desktop-App\electron-quick-start\npm-debug.log

**Comment by kevinsawicki** [comment]
It looks like your temp directory environment variable is corrupt.

Can you check what the value of your `TMP` or `TEMP` environment variable is?

**Comment by anandfingertip** [comment]
Thanks Kevin for looking into this issue. I have checked already the TMP folder also tried clean change the folder. It did not really help.
Here is the TMP value from  "npm config list"

; globalconfig C:\Users\Anand\AppData\Roaming\npm\etc\npmrc
tmp = "C:\\Users\\Anand\\AppData\\Roaming\\npm\\tmp"

**Comment by kevinsawicki** [comment]
@anandfingertip can you try running the following from the console?

```sh
node -e 'console.log(os.tmpdir())'
```

**Comment by anandfingertip** [comment]
@kevinsawicki below is the output of the command:

command
node -e 'console.log(os.tmpdir())'

output:
/c/Users/Anand/AppData/Local/Temp;C:/Work/apache-maven-3.2.5-bin/apache-maven-3.2.5/bin;C:/Program Files/Java/jdk1.8.0_31/bin;.;

**Comment by kevinsawicki** [comment]
> output:
/c/Users/Anand/AppData/Local/Temp;C:/Work/apache-maven-3.2.5-bin/apache-maven-3.2.5/bin;C:/Program Files/Java/jdk1.8.0_31/bin;.;

@anandfingertip that is the issue, you have multiple paths configured as your temp directory which causes an invalid path to be used to download Electron to.

Switching it to be a single path (probably just `/c/Users/Anand/AppData/Local/Temp`) should fix this.

Looks like somehow the temp environment variable got `PATH` segments on it, like maven and java's bin folders.

Closing this out.

**Comment by anandfingertip** [comment]
Thanks @kevinsawicki  I'll now try to change it to a single path.
