### ISSUE TITLE
Electron crashes on large data URLs

### ISSUE THREAD

**Issue by bootstraponline** [electron/electron#8317]
* Electron version: 1.4.3
* Operating system: Windows 10

### Expected behavior

No crash.

### Actual behavior

Electron crashes.

> [13900:1231/153409:WARNING:navigator_impl.cc(301)] Refusing to load URL as it exceeds 2097152 characters.

### How to reproduce

```javascript
let url = nativeImage.createFromBuffer(debugImage).toDataURL();
let win = new BrowserWindow();
win.loadURL(url);
```

**Comment by MarshallOfSound** [comment]
@bootstraponline Can you test loading a data URL that long in Chrome?

On a side note that is one helluva long data URL 😆

**Comment by bootstraponline** [comment]
> @bootstraponline Can you test loading a data URL that long in Chrome?

Sure. If I paste the data URL into Chrome, nothing happens. Chrome probably has an internal check. I tried setting document.location as well and that didn't work either.

There must be some work around to load large images into a new window. Maybe `<img src="data:image/png;base64,...`

**Comment by bootstraponline** [comment]
```javascript
win.loadURL("about:blank");
win.webContents.executeJavaScript('document.write(\'<img src="' + url + '" />\');');
```

^ that's the work around I'm using for now. If there's a better way, let me know.

**Comment by deepak1556** [comment]
The check is something defined by the content layer and cannot be modified in Electron. I would suggest using blob instead of data URI in this scenario.
