### ISSUE TITLE
Which version of OpenGL is Electron using?

### ISSUE THREAD

**Issue by Frederick888** [electron/electron#8323]
I'm using Visual Studio Code with ArchLinux + KDE. The texts look quite blurry and I noticed the setting of *System Settings -> Display and Monitor -> Compositor -> Rendering backend* in KDE influenced it a lot. So it seems rather than trying to use the highest version of GL possible (as that in Chrome), Electron is using the same one as the user chooses for KDE. (This is only my assumption, because I had no idea on how to obtain the details of running GL in VSC like `chrome://gpu`.)

The issue was originally reported at https://github.com/Microsoft/vscode/issues/17926. Which version of GL APIs is Electron using?

**Comment by MarshallOfSound** [comment]
`chrome://gpu` works in Electron, you just need to launch VSC dev tools and run `window.location = 'chrome://gpu`

**Comment by Frederick888** [comment]
@MarshallOfSound No, it doesn't work. I once tried it before however just nothing happened.

**Comment by MarshallOfSound** [comment]
![screen shot 2017-01-03 at 11 58 43 am](https://cloud.githubusercontent.com/assets/6634592/21598188/04a6d24e-d1ac-11e6-9e62-af33a089326a.png)

Looks like it works on my machine 👍

**Comment by Frederick888** [comment]
@MarshallOfSound Which version of VSC are you using?

**Comment by Frederick888** [comment]
![screenshot_20170103_120639](https://cloud.githubusercontent.com/assets/4507647/21598238/24cc1a56-d1ad-11e6-91a3-20d3e36ecc01.png)
@MarshallOfSound Mine only returns the given string...

**Comment by paulcbetts** [comment]
Try this:

```
BrowserWindow = require('electron').remote.BrowserWindow
bw = new BrowserWindow({width: 500, height: 500})
bw.loadURL('chrome://gpu')
```

**Comment by Frederick888** [comment]
@paulcbetts Thanks, this worked. And it's using `GL 4.5.0` as well (although many GPU features are disabled)...
```
GL_VENDOR	NVIDIA Corporation
GL_RENDERER	GeForce GTX 980M/PCIe/SSE2
GL_VERSION	4.5.0 NVIDIA 375.26
```
![screenshot_20170103_205250](https://cloud.githubusercontent.com/assets/4507647/21604322/ad7d9b7e-d1f6-11e6-8d18-f143b623c0d4.png)

But then it seems to be even more mysterious to me coz the fonts in developer tools are also blurry. Here's a snapshot (left: VSC, right: Chrome).
![screenshot_20170103_205221](https://cloud.githubusercontent.com/assets/4507647/21604366/ed7e83a0-d1f6-11e6-895b-290d0a922ae2.png)
Any clue? (By the way, the texts in the toolbox panel, e.g. project explorer, are not blurry at all.)

**Comment by KagamiChan** [comment]
You may adjust display scale of devtools to ensure both displayed font size are the same, via `ctrl` + `+` / `-` and `ctrl` + `0`, so the comparison could be clearer

**Comment by Frederick888** [comment]
![screenshot_20170104_164756](https://cloud.githubusercontent.com/assets/4507647/21632773/9f9ee452-d29d-11e6-8b7d-1c714bdbefac.png)
@KagamiChan This could be a litter better... I couldn't make the line heights the same though... But conspicuously the texts in VSC are blurry (especially the filter icon... is it a UTF8 character?)

**Comment by kevinsawicki** [comment]
Closing this out, thanks @paulcbetts and @MarshallOfSound
