### ISSUE TITLE
electron not compatible with native module like kinect2

### ISSUE THREAD

**Issue by BrstDev123** [electron/electron#8327]
![image](https://cloud.githubusercontent.com/assets/24525310/21602364/2dd2d61a-d1b9-11e6-8d13-0fe80939f509.png)

On run command ' electron . ' it is always giving this error.

**Comment by MarshallOfSound** [comment]
@BrstDev123 You should check out the docs for using native modules inside Electron

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

Also if you use tools such as [`electron-forge`](https://github.com/electron-userland/electron-forge) the nuances of native modules are handled for you
