### ISSUE TITLE
Electron installation

### ISSUE THREAD

**Issue by haribabu500** [electron/electron#8328]
My npm version is 3.10.10
and node version is v7.2.1
and when I tried to install electron in ubuntu via 
sudo npm install electron --save-dev
I get error like this...

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:572:26)
npm WARN enoent ENOENT: no such file or directory, open '/home/dotmark/package.json'
npm WARN dotmark No description
npm WARN dotmark No repository field.
npm WARN dotmark No README data
npm WARN dotmark No license field.
npm ERR! Linux 3.13.0-87-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "electron" "--save-dev"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.4.13 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dotmark/npm-debug.log

**Comment by MarshallOfSound** [comment]
> Error: read ECONNRESET

This indicates a network issue when download the Electron prebuilt binaries.  Simply wiping your `node_modules` and trying again should fix the issue.

If not I would try on a different internet connection.

**Comment by haribabu500** [comment]
How can I wipe node modules??

**Comment by MarshallOfSound** [comment]
`rm -rf node_modules`

**Comment by haribabu500** [comment]
thank you
