### ISSUE TITLE
How to get default protocol url parameter on Windows

### ISSUE THREAD

**Issue by remicoges** [electron/electron#8329]
Hello all! Happy new Year !

* Electron version: 1.4.11
* Operating system: Windows 10

I want to launch my electron app on click to a custom protocol (like rtps://<string>) and get the string in my app.

It's ok for Mac OSX as the 'open-url' event is available and allows to get the url, but is that possible on Windows ?

Thanks for your help

**Comment by MarshallOfSound** [comment]
You need to use the [`app.makeSingleInstance`](http://electron.atom.io/docs/api/app/#appmakesingleinstancecallback) API and read in the URL off the `argv` of the second process.  A generic implementation is currently in a PR that you can see here:

https://github.com/electron/electron/pull/8052

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by ccorcos** [comment]
I just want to mention that this is very poorly documented on windows. `open-url` works great on mac but I'm struggling to figure out how to do this one windows...
