### ISSUE TITLE
can't call getUserMedia  from "file://" protocol

### ISSUE THREAD

**Issue by richmonkey** [electron/electron#8330]
I  call getUserMedia from "file://" protocol, 
got "getUserMedia() must be run from a secure origin: HTTPS or localhost.".

I think "file protocol" is equal to localhost, maybe electron can support getUserMedia from local file html

**Comment by kevinsawicki** [comment]
Can you include a small reproduction app or code snippet that demonstrates this issue?

I had trouble reproducing this, this worked for me:

```
 navigator.getUserMedia({ audio: true, video: false }, function (s) {console.log(s)}, function (error) { console.log(error)})
```

![screen shot 2017-01-04 at 11 42 33 am](https://cloud.githubusercontent.com/assets/671378/21656412/e69c1d78-d272-11e6-9095-e99fc9680577.png)

**Comment by richmonkey** [comment]
I mistake,
