### ISSUE TITLE
Cannot load highcharts when run inside electron

### ISSUE THREAD

**Issue by jmaicaaan** [electron/electron#8333]
I have created an angular app for my front, and I want to load it via url (localhost). Everything is working fine and good on other components but when it comes to Highcharts library for my charting, it doesn't work when I load it inside the electron using `browserWindow.loadURL()`. In my browser, google chrome, the chart is working but inside electron it is not. I've doubled check in my network panel if it's loaded and yes it is. Injected it also in my angular app correctly. 

* Electron version: v1.4.13
* Operating system: windows 10

### Expected behavior

It would load the chart normally like any browser would do.

### Actual behavior

The chart is not loading, it says `Possibly unhandled rejection: {}` when I use the Highcharts directive, `<highchart ....> </highchart>`

### How to reproduce

Here is my angular app without the web service up.
https://jmaicaaan.github.io/InventoryManagement-Beta/app/#!/

You could see that the chart is working on a browser. But when it is loaded in electron it is not. 
To reproduce it in electron, just copy & paste the above link to your electron.

My main.js file:
https://github.com/jmaicaaan/InventoryManagement-Beta/blob/master/app/main.js

**Comment by MarshallOfSound** [comment]
@jmaicaaan Normally issues like this are due to `nodeIntegration` being enabled.  Try disabling `nodeIntegration` on your browser window.

**Comment by jmaicaaan** [comment]
@MarshallOfSound it now works! Thank you! Can you explain further what's with nodeIntegration option?

**Comment by MarshallOfSound** [comment]
`nodeIntegration` enables node.js's commonjs loader in your BrowserWindow.  This injects globals such as `module.exports` and `require` which some libraries (such as highcharts and jQuery) use to determine what environment they are being loaded in.

By disabling it they think they are being loaded in a web browser and function correctly.

**Comment by jmaicaaan** [comment]
Is there any pros and cons with disabling it? Would it be no problem in the future? For example, if I added another libraries.

**Comment by mluis** [comment]
@MarshallOfSound what can one do in order to use functions like ipcRenderer from electron and highcharts at the same time? I'm in a situation I need to use both.
