### ISSUE TITLE
High CPU usage with CSS SVG filter

### ISSUE THREAD

**Issue by hariprasadiit** [electron/electron#8334]
When i load [http://www.saavn.com/play/featured/english/Weekly+Top+Songs/1](url), electron helper is using more than 50% CPU.

* Electron version: 1.4.1
* Operating system: Mac OS X El Capitan

### Expected behavior

It shouldn't take much of CPU as observed on Chrome browser

### Actual behavior

More than 50% CPU

### How to reproduce

1. Load [http://www.saavn.com/play/featured/english/Weekly+Top+Songs/1](url) into webview.
2. Observe the CPU usage.
3. Fall back to `filter: blur(42px);`, you can observe that the CPU usage drastically reduces.

**Screenshot of chrome dev tools for reference :**
![screen shot 2017-01-04 at 13 11 44](https://cloud.githubusercontent.com/assets/1260204/21634763/86d987ec-d27f-11e6-87ca-0ad3bf1e4456.png)

**Comment by kevinsawicki** [comment]
> It shouldn't take much of CPU as observed on Chrome browser

What version of Chrome did you try? Did you try it inside a `<webview>` in Chrome?

**Comment by hariprasadiit** [comment]
On chrome V55.0 using `webview` causes CPU to run at 20%. with `filter: blur(42px);` CPU is running at 7% to 9%.

**Comment by MarshallOfSound** [comment]
@hariprasadiit Please test using Chrome / Chromium 53 as that is what Electron is currently based on

**Comment by hariprasadiit** [comment]
@MarshallOfSound Did test using Chromium 53. The result is same as chrome 55. It's using 20% of CPU unlike electron.

**Comment by zcbenz** [comment]
Recent versions of Electron with newer Chrome versions should have fixed this, and I'm unable to reproduce with Electron v1.7.x.
