### ISSUE TITLE
DevTools connection failed when another debugger is already attached to this target

### ISSUE THREAD

**Issue by f111fei** [electron/electron#8336]
* Electron version: 1.4.13
* Operating system: windows7

### How to reproduce

1. open an electron app with `remote-debugging-port`.

```
electron --remote-debugging-port=9222 .
```

2. attach the port in chrome browser.  open the debugger url, example:

`http://localhost:9222/devtools/inspector.html?ws=localhost:9222/devtools/page/4a881423-fb03-4b77-90d8-8e1e5b597486 `

3. click `View - Toggle Developer Tools` menu in electron.

DevTools is opened but not contents.

### Expected behavior

![electron2](https://cloud.githubusercontent.com/assets/7069719/21639171/9daaa472-d2a9-11e6-8c9e-629f86e65817.gif)

### Actual behavior

![electron](https://cloud.githubusercontent.com/assets/7069719/21639177/a40388e8-d2a9-11e6-8bf5-f083a828211f.gif)

Here is my app demo:

index.html

```
<html>

<head>
	<title>Electron Demo</title>
	<style>
		body {
			display: block;
			margin: 0;
		}
	</style>
</head>

<body>
	<div id="button"></div>
	<script>
		window.onload = function() {
			var button = document.getElementById('button');
			button.textContent = 'Electron: v' + process.versions.electron
		}
	</script>
</body>

</html>
```

index.js

```
var electron = require('electron');
var app = electron.app;
var BrowserWindow = electron.BrowserWindow;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
	app.quit();
});

app.on('ready', function() {
	var mainWindow = new BrowserWindow({
		width: 800,
		height: 600
	});
	mainWindow.loadURL('file://' + __dirname + '/index.html');
	mainWindow.focus();
});
```

**Comment by enlight** [comment]
Actual behavior is the expected behavior, it is a limitation of the Chromium Debugging Protocol as mentioned [here](https://developer.chrome.com/devtools/docs/debugger-protocol#simultaneous).

**Comment by f111fei** [comment]
@enlight  no. Open Dev Tools will close other debug targets in chrome.  Before the electron v1.3.9 is what I expect, but v1.4.0 change the behavior.

**Comment by enlight** [comment]
Ah, I get it now. Reopening.
