### ISSUE TITLE
localStorage values are limited to 10Mb

### ISSUE THREAD

**Issue by nunomluz** [electron/electron#8337]
localStorage is still limited to 10Mb. After running a few tests, it throws a:
> DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'data' exceeded the quota.

Also reported in [issue 897](https://github.com/electron/electron/issues/897), which is closed.

* Electron version: 1.4.13
* Operating system: Windows 7

### Expected behavior

No limit/quota

### Actual behavior

Limited to 10Mb

### How to reproduce

Run `localStorage.setItem('data', (new Array(11*1024*1024)).join("x"));`

**Comment by kevinsawicki** [comment]
The total storage can be over 10MB but a single value cannot be over 10MB.

Since `localStorage` is synchronous, saving large values may hang the application, can you elaborate on why you are saving values that large?

**Comment by nunomluz** [comment]
Thanks, Kevin. I'm using the redux-localstorage enhancer, which stores part of the app state in serialized JSON as a single key-value. It's not a common case, but with the current implementation I'm working on, it can exceed 10 Mb.
The app hanging is an issue, so I'll consider another approach that doesn't rely on localStorage. However, anyone using redux-localstorage might experience this issue if the persisted slice of the app state grows over time.

**Comment by imolorhe** [comment]
I have the same use case as mentioned by @nunomluz. My app's state is stored in localstorage. The app state is rehydrated upon initialization based on the stored state.

**Comment by SmileOffline** [comment]
https://github.com/electron-userland/electron-json-storage

**Comment by SmileOffline** [comment]
You can use this library,

I worked very well in our project.

https://github.com/electron-userland/electron-json-storage

**Comment by jacobq** [comment]
Could anyone tell me how to start going about writing a patch for this in the upstream chromium package? It looks like it's related to these:

* [dom_storage README](https://github.com/chromium/chromium/blob/master/content/browser/dom_storage/README.md). 
* [`dom_storage_cached_area.cc`](https://github.com/chromium/chromium/blob/0d2d2d89910d2087788f5549806075399d1bcf84/content/renderer/dom_storage/dom_storage_cached_area.cc#L201)

**Comment by jacobq** [comment]
BTW, is the reason that `localStorage.sizeTest = new Array(5*Math.pow(2,20)).fill('X').join('')` fails (5Mi characters) even though the quota limit is 10MiB because each character is using 2 bytes ([JS strings using UTF-16](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String))?

**Comment by jacobq** [comment]
Looks like this should be fixed in master (https://github.com/electron/electron/pull/14104), no?
