### ISSUE TITLE
Failed at the electron@1.4.13 postinstall script 'node install.js'

### ISSUE THREAD

**Issue by ogadit** [electron/electron#8339]
* Electron version:
1.4.13
* Operating system:
Windows 10 64-bit

### Actual behavior

> 14409 error node v7.3.0
14410 error npm  v3.10.10
14411 error code ELIFECYCLE
14412 error electron@1.4.13 postinstall: `node install.js`
14412 error Exit status 1
14413 error Failed at the electron@1.4.13 postinstall script 'node install.js'.
14413 error Make sure you have the latest version of node.js and npm installed.
14413 error If you do, this is most likely a problem with the electron package,
14413 error not with npm itself.
14413 error Tell the author that this fails on your system:
14413 error     node install.js
14413 error You can get information on how to open an issue for this project with:
14413 error     npm bugs electron
14413 error Or if that isn't available, you can get their info via:
14413 error     npm owner ls electron
14413 error There is likely additional logging output above.
14414 verbose exit [ 1, true ]

**Comment by kevinsawicki** [comment]
Can you include the console output when running `npm install electron`?

**Comment by chenchuk77** [comment]
Hi
i got a similar problem on ubuntu 16.04 . while trying to npm install i got this

`26351 silly rollbackFailedOptional Starting
26352 silly rollbackFailedOptional Finishing
26353 silly runTopLevelLifecycles Starting
26354 silly runTopLevelLifecycles Finishing
26355 silly install printInstalled
26356 warn twitter-electron@0.1.0 No description
26357 warn twitter-electron@0.1.0 No repository field.
26358 warn twitter-electron@0.1.0 No license field.
26359 verbose stack Error: electron-prebuilt@1.4.13 postinstall: `node install.js`
26359 verbose stack spawn ENOENT
26359 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
26359 verbose stack     at emitTwo (events.js:87:13)
26359 verbose stack     at ChildProcess.emit (events.js:172:7)
26359 verbose stack     at maybeClose (internal/child_process.js:821:16)
26359 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
26360 verbose pkgid electron-prebuilt@1.4.13
26361 verbose cwd /home/chen/dev/nodejs/electron_twitter
26362 error Linux 4.8.0-30-generic
26363 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
26364 error node v4.2.6
26365 error npm  v3.5.2
26366 error file sh
26367 error code ELIFECYCLE
26368 error errno ENOENT
26369 error syscall spawn
26370 error electron-prebuilt@1.4.13 postinstall: `node install.js`
26370 error spawn ENOENT
26371 error Failed at the electron-prebuilt@1.4.13 postinstall script 'node install.js'.
26371 error Make sure you have the latest version of node.js and npm installed.
26371 error If you do, this is most likely a problem with the electron-prebuilt package,
26371 error not with npm itself.
26371 error Tell the author that this fails on your system:
26371 error     node install.js
26371 error You can get information on how to open an issue for this project with:
26371 error     npm bugs electron-prebuilt
26371 error Or if that isn't available, you can get their info via:
26371 error     npm owner ls electron-prebuilt
26371 error There is likely additional logging output above.
26372 verbose exit [ 1, true ]
`

**Comment by vdjkelly** [comment]
47652 verbose stack Error: electron@1.4.13 postinstall: `node install.js`
47652 verbose stack Exit status 1
47652 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
47652 verbose stack     at emitTwo (events.js:87:13)
47652 verbose stack     at EventEmitter.emit (events.js:172:7)
47652 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
47652 verbose stack     at emitTwo (events.js:87:13)
47652 verbose stack     at ChildProcess.emit (events.js:172:7)
47652 verbose stack     at maybeClose (internal/child_process.js:821:16)
47652 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
47653 verbose pkgid electron@1.4.13
47654 verbose cwd /home/vdjkelly/Descargas/anatine-1.1.0
47655 error Linux 4.4.0-57-generic
47656 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
47657 error node v4.2.6
47658 error npm  v3.5.2
47659 error code ELIFECYCLE
47660 error electron@1.4.13 postinstall: `node install.js`
47660 error Exit status 1
47661 error Failed at the electron@1.4.13 postinstall script 'node install.js'.
47661 error Make sure you have the latest version of node.js and npm installed.
47661 error If you do, this is most likely a problem with the electron package,
47661 error not with npm itself.
47661 error Tell the author that this fails on your system:
47661 error     node install.js
47661 error You can get information on how to open an issue for this project with:
47661 error     npm bugs electron
47661 error Or if that isn't available, you can get their info via:
47661 error     npm owner ls electron
47661 error There is likely additional logging output above.
47662 verbose exit [ 1, true ]

**Comment by kevinsawicki** [comment]
> 26363 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> 26370 error spawn ENOENT

@chenchuk77 This is because Node is installed on your machine as `nodejs` instead of node. Upgrading to npm `3.7.0` or above should address this.

https://github.com/npm/npm/releases/v3.7.0

**Comment by tonghuashuo** [comment]
Same problem here. Failed at `node install.js`.

- macOS 10.12.2 Sierra
- node 6.9.2
- npm 4.1.1 (using registry: https://registry.npm.taobao.org)

The console shows some error about permission denied to link the release package. But I did used `sudo` command. I tried to manually perform the link and then run `sudo node install.js`. It put me on hold for over 10 mins showing me nothing, until I hit `Ctrl + C` to cancel.

The release package `electron-v1.4.13-darwin-x64.zip` is found under `~/.electron` with size 42.1MB so the network should be fine. I unzipped the file and copied Electron.app to `/Applications` folder. It works just fine. Launch the app and it tells me "To run your app with Electron, execute the following command in your Console (or Terminal):" `/Applications/Electron.app/Contents/MacOS/Electron path-to-your-app`. Run it with no path and it opened up another electron window.

Guess a manually link to global CLI command is all I need to do next. But this doesn't sound like a long-term solution for future upgrade with npm.

I also tried with the latest version 1.4.1. Nothing changed. Hope the team can fixed this ASAP. thx ahead.

![electron-error](https://cloud.githubusercontent.com/assets/6594276/21961210/1c7f33d8-db3f-11e6-955f-4adce58a6b87.png)

**Comment by ricardovb** [comment]
Same here 🌵

**Comment by ouonet** [comment]
same here

**Comment by antoniodavid** [comment]
same here
win 10
node v6.9.4

**Comment by songjum** [comment]
same here  
node v7.7.2
npm  v4.1.2
macOs 10.11.6

**Comment by keith9820** [comment]
Same here:
macOs 10.12.3
node v7.7.4
npm 4.4.1

**Comment by oli18** [comment]
`7495 error Windows_NT 10.0.14393
7496 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "electron"
7497 error node v7.7.4
7498 error npm  v4.1.2
7499 error code ELIFECYCLE
7500 error electron@1.6.2 postinstall: `node install.js`
7500 error Exit status 1
7501 error Failed at the electron@1.6.2 postinstall script 'node install.js'.
7501 error Make sure you have the latest version of node.js and npm installed.
7501 error If you do, this is most likely a problem with the electron package,
7501 error not with npm itself.
7501 error Tell the author that this fails on your system:
7501 error     node install.js
7501 error You can get information on how to open an issue for this project with:
7501 error     npm bugs electron
7501 error Or if that isn't available, you can get their info via:
7501 error     npm owner ls electron
7501 error There is likely additional logging output above.
7502 verbose exit [ 1, true ]
`

Same problem. Can't get past node install.js 

Win 10 x64
node v7.7.4
npm v4.1.2

**Comment by sohibul** [comment]
anybody solved this?

**Comment by takahiro-saeki** [comment]
same here
```
npm verb node v7.9.0
npm verb npm  v4.5.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/saekitakahiro/.npm/_logs/2017-04-29T14_30_54_433Z-debug.log
```
I just did it.
`sudo npm i electron -g --verbose`

**Comment by tonghuashuo** [comment]
I've got a solution. Not the best way but should be enough if you need to install electron right now and don't have time to wait for the official fix.

Everyone here got into trouble when it comes to `postinstall script 'node install.js'`. So let's start with that. 

Run `npm install --save electron` for your project and hit `Ctrl + C` when it comes to this sentence. The download has not complete yet but we've got what we need. 

Under `YOUR_PROJECT_PATH/node_modules/electron` you can find this `install.js` file. If you open it and take a look. It's simply some javascript code to download the release package (which you can download directly from Github) and extract it. That's all. So **either something went wrong with the network so the download took too long, or the script do not have permission to extract zip file and rename it**. 

Since it crashes when running automatically, let's do it manually.

Just follow what the file says:
1. Download the zip file (from Github using any way you like)
2. extract it into `YOUR_PROJECT_PATH/node_modules/electron`.
3. Rename the extracted folder to 'dist'.
4. Create a `path.txt` file here. Write `dist/Electron.app/Contents/MacOS/Electron` and save it. (This is for mac, For Windows write `dist/electron.exe`, and for linux write `dist/electron`. You can find these in the end of 'install.js')

Now you've installed it locally. 

By running `./node_modules/electron/dist/Electron.app/Contents/MacOS/Electron .`, your project should start up. (For non-MacOS environment. the path might be a little different. I trust you can find the right one.)

Next, you can either use npm script to make a alias for that loooooooong command. Or install electron globally so you can run `electron` from the terminal. (Same process. Only this time run `npm install -g electron` and do it under `/usr/local/lib/node_modules/electron`)

**Comment by Sktbanerjee1** [comment]
facing the same issue, tried the last answer did not work, please help.

**Comment by bartektenDev** [comment]
This worked for me! Do this at your own risk.

First delete any folders called electron in (node_modules) in your project.
Then delete electron like this
`npm uninstall electron`
and lastly run this command to make sure permissions 'refresh' and you can install it correctly.
`npm install electron --save-dev`

**Comment by Sktbanerjee1** [comment]
Thanks for the reply.  Sorry, I am just a beginner, what are the potential risks of installing like this?
Thanks in advance.

**Comment by bartektenDev** [comment]
> Thanks for the reply. Sorry, I am just a beginner, what are the potential risks of installing like this?
> Thanks in advance.

Yes. The only risks involved is causing your project to not be compatible with the latest version of electron that installs. You don't need to be too worried. This will just ensure that you erase electron from your project then install all the files fresh to ensure a clean install. Give it a try! Maybe backup your project before continuing. Maybe a thanks if it works? <3

**Comment by alextomko** [comment]
tonghuashuo, I don't find where to download the package if you stop it like this. What release panel? What release package. The javascript has no direct download link in the script so am unsure what to download. Mine tries to download an armv7 package and my electron fails here like everyone else's did in this thread, this is the package "Downloading tmp-20048-0-electron-v3.1.9-linux-arm64.zip" so where can I go find this package to try this process.

**Comment by alextomko** [comment]
> I've got a solution. Not the best way but should be enough if you need to install electron right now and don't have time to wait for the official fix.
> 
> Everyone here got into trouble when it comes to `postinstall script 'node install.js'`. So let's start with that.
> 
> Run `npm install --save electron` for your project and hit `Ctrl + C` when it comes to this sentence. The download has not complete yet but we've got what we need.
> 
> Under `YOUR_PROJECT_PATH/node_modules/electron/` you can find this `install.js` file. If you open it and take a look. It's simply some javascript code to download the release package (which you can download directly from Github) and extract it. That's all. So **either something went wrong with the network so the download took too long, or the script do not have permission to extract zip file and rename it**.
> 
> Since it crashes when running automatically, let's do it manually.
> 
> Just follow what the file says:
> 
>     1. Download the release package file. (from Github, the release panel, using any way you like)
> 
>     2. Extract it into `YOUR_PROJECT_PATH/node_modules/electron`.
> 
>     3. Rename the extracted folder to 'dist'.
> 
>     4. Create a `path.txt` file here. Write `dist/Electron.app/Contents/MacOS/Electron` and save it. (This is for mac, For Windows write `dist/electron.exe`, and for linux write `dist/electron`. You can find these in the end of 'install.js')
> 
> 
> Now you've installed it locally.
> 
> By running `./node_modules/electron/dist/Electron.app/Contents/MacOS/Electron .` (don't miss the dot at the beginning & end of the line), your project should start up. (For non-MacOS environment. the path might be a little different. I trust you can find the right one.)
> 
> Next, you can either use npm script to make a alias for that loooooooong command. Or install electron globally so you can run `electron` from the terminal. (Same process. Only this time run `npm install -g electron` and do it under `/usr/local/lib/node_modules/electron/`)
> 
> This worked for me. Hope it works for you too. Happy Coding!

I can't find where to download the release packages? Where are they?

**Comment by alextomko** [comment]
Why is this issue closed

**Comment by MuneebRabaney** [comment]
**Machine Specs:**

<ins>Operating System:</ins>
macOS Big Sur v11.6

<ins>NPM version:</ins>
v6.14.13

<ins>Node version :</ins>
v14.17.0

After some digging, I found [this post](https://stackoverflow.com/a/48515453/4433536) that allowed me to get it installed globally.

**TL;TR**
Open your terminal and execute the follow command
`sudo npm install -g electron --unsafe-perm=true --allow-root`

Hope it helps!

Happy coding =)
