### ISSUE TITLE
Is webview's guestinstance able to render in a new Window?

### ISSUE THREAD

**Issue by devingfx** [electron/electron#8344]
Hi,

I dont really understand the usage of webview tag's guestinstance attribute, sorry I did'nt know where to ask the question!

I'm trying to implement windows with tab management where can drag a tab outside the window and a new window is created with this tag in it.... you know... well like every modern browsers?

If guestinstance is set with the id of a webview from another window will it do the job?

**Comment by kevinsawicki** [comment]
> If guestinstance is set with the id of a webview from another window will it do the job?

If you want to move a `webContents` between `<webview>` tags then setting the `guestinstance` attribute is the way to do that.

> I'm trying to implement windows with tab management where can drag a tab outside the window and a new window is created with this tag in it.... you know... well like every modern browsers?

Setting the `guestinstance` attribute in the new window's `<webview>` tag to the value from the originating window should do this.

http://electron.atom.io/docs/api/web-view-tag/#guestinstance
