### ISSUE TITLE
Frameless BrowserWindow: 1px gap between taskbar and window

### ISSUE THREAD

**Issue by felixrieseberg** [electron/electron#8350]
There appears to be a 1px thick "gap" between the Windows taskbar and the content of a frameless BrowserWindow.

* Electron version: 1.4.13 (and below)
* Operating system: Windows 10

### Expected behavior
There should be no gap between webContents, dev tools, and other content of the BrowserWindow and the Windows taskbar when the window is maximized.

### Actual behavior
There is a 1px between webContents, dev tools, and other content of the BrowserWindow and the Windows taskbar when the window is maximized.

### How to reproduce
Open a new frameless `BrowserWindow`. Give it a background color.

![gap](https://cloud.githubusercontent.com/assets/1426799/21694263/28040444-d339-11e6-9d59-af3c003ae959.png)

**Comment by kevinsawicki** [comment]
Could it be a window border? If you make the background color red do you see a red hue at the bottom when maximized?

Sounds similar to https://github.com/electron/electron/issues/4573

**Comment by kevinsawicki** [comment]
@felixrieseberg could you try reproducing this on master to see if it was addressed for you by #4573

**Comment by bsclifton** [comment]
I'm currently seeing a similar issue with Brave, although it's with Chromium 54.  You can follow our progress with https://github.com/brave/browser-laptop/issues/6698

**Comment by zcbenz** [comment]
I'm merging this to https://github.com/electron/electron/issues/8332.
