### ISSUE TITLE
Electron does not open itself properly to f.lux when application is not at full screen (Discord)

### ISSUE THREAD

**Issue by Bpendragon** [electron/electron#8352]
* Electron version: Version in Discord v1.8.1
* Operating system: Windows 10 Pro 10 Pro  Build 149393

### Expected behavior

The region in the screen where Discord is appears at the proper color temperature. Approximated in following image: ![desired](https://cloud.githubusercontent.com/assets/5448822/21705476/0909b584-d375-11e6-8969-d215c92f7e73.png)

### Actual behavior

Discord does not follow the rest of then screen as approximated here: ![current](https://cloud.githubusercontent.com/assets/5448822/21705475/08f7e7f0-d375-11e6-8693-931c0e3ecf60.png)

### How to reproduce

Open Discord in windowed mode and run f.lux night-time settings.

### Additional Notes

* Screen images are approximated. When a screenshot is taken with f.lux running it appears at normal color temperature as seen here: ![unedited](https://cloud.githubusercontent.com/assets/5448822/21705477/092037c8-d375-11e6-88e5-7271c22ff741.png)
* I have emailed Discord support and they sent me here believing that the issue was in Electron itself.
* I have emailed f.lux in case the problem is at their end and not Electron's 
The problem does not arise when Discord is at full screen. Or when being dragged to reposition the window.

**Comment by zcbenz** [comment]
Sorry but I'm afraid we are not able to solve this on Electron's side, this is a feature of f.lux and I'm afraid only developers of f.lux know why it does not work with Electron.
