### ISSUE TITLE
zoom relative methods only work after dom-ready?

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#8353]
* Electron version: 1.4.13
* Operating system: Windows 10

```
app.once('ready', () => {
	let win = new BrowserWindow({});
	win.loadURL(__dirname + '/index.html');

	//won't work
	win.webContents.getZoomFactor(zoomFactor=>console.log(zoomFactor));

	//will work
	win.webContents.on('dom-ready', function (){
		win.webContents.getZoomFactor(zoomFactor=>console.log(zoomFactor));
		win.webContents.setZoomFactor(4);
	});
});
```

webContents methods of `getZoomFactor / getZoomLevel / setZoomFactor / setZoomLevel`

As my test, they only work after dom-ready, but I didn't find remark in [docs](http://electron.atom.io/docs/api/web-contents/#contentssetzoomfactorfactor).

Is it a bug?

**Comment by hokein** [comment]
This is intended. Indeed, these APIs are [`webFrame`](http://electron.atom.io/docs/api/web-frame/#webframe) APIs, they work only after the frame is loaded.
