### ISSUE TITLE
Default max memory

### ISSUE THREAD

**Issue by craxal** [electron/electron#8356]
I've seen a lot of advice for increasing Electron's max memory limit by using command-line flags. However, I don't see any advice on how to increase the limit for a distributed Electron application.

Is it possible to increase the default max memory limit when re-branding the application for distribution?

Is it possible to change the default max memory limit while building Electron from source?

**Comment by craxal** [comment]
Is anyone there? This issue has been opened for two weeks.

**Comment by algv** [comment]
default values are in v8/src/heap/heap.cc: https://github.com/electron/node/blob/b1069b6dd5321a6e5cf2f7fea68a85ac4a2df24b/deps/v8/src/heap/heap.cc#L82

**Comment by craxal** [comment]
Thank you for replying!

I'm assuming this is a hard-coded value and can't be changed after Electron is built. Could this be made configurable? Allowing app authors to adjust the default max memory would be very useful. How costly would such a change be?

**Comment by zcbenz** [comment]
Electron can only provide what V8 public APIs have, you can request V8 team to add a public API to add heap size.

Closing since it is V8 issue.

**Comment by vasyl-shumskyi** [comment]
This is too bad that this value is not configurable..

**Comment by craxal** [comment]
@vasyl-shumskyi Not really, no. We ended up refactoring some old architecture in our app so that most intensive activities run in a separate process. Also, we usually only encountered problems in 32-bit Windows. Other platforms are always 64-bit, and they don't run into the same problems. Since then, we've never heard any issues.

**Comment by vasyl-shumskyi** [comment]
@craxal oh, great. Thanks for the info!
