### ISSUE TITLE
[Docs Suggestion] - Include RAM requirements

### ISSUE THREAD

**Issue by MrMashy** [electron/electron#8362]
I can't get a solid answer anywhere, Could someone create an empty app in electron and let us know what the base usage is and add it to the docs?

**Comment by baconface** [comment]
I could be wrong but I think Chromium's base RAM usage varies based on available RAM and some other factors. So that would be a hard one to get you an answer for.

**Comment by kevinsawicki** [comment]
> I could be wrong but I think Chromium's base RAM usage varies based on available RAM and some other factors. So that would be a hard one to get you an answer for.

Yeah, the system requirements at https://support.google.com/chrome/answer/95346 only include the processor and OS requirements.

**Comment by upicik** [comment]
On Windows 7(Intel Core i-5 processor) the simple electron window displaying "Hello World" takes: 
Commit(KB), Working Set(KB), Shareable(KB), Private(KB)(respectively):
![1](https://cloud.githubusercontent.com/assets/13974245/23393185/4f0b2e2c-fdab-11e6-9465-50ad99fbab81.png)

@kevinsawicki @MrMashy   Is it what is need to be included in documentation? This kind of information on every platform?

**Comment by serant** [comment]
@MrMashy I don't think it would be best to do this with a completely empty application i.e. just a blank index.js file. When I did this I only saw around 40 MB of RAM being used on macOS however the electron-quick-start app uses just under 256 MB.

**Comment by MrMashy** [comment]
@serant Well somebody stated that that it varies on available ram & such, so it's probably not practical to include ram usage in the quick start docs, BUT what I do want in the docs section is to know how minimal ram you would require for the app to work. (like could it run on a raspberry PI etc)

**Comment by baconface** [comment]
> Well somebody stated that that it varies on available ram & such

Yes. To further elaborate on it the base usage for your machine won't be the same for me or someone else if our set ups are not close or the same. Chromium appears to allocate or throttle itself based on available resources. This allows it run on really low spec machines and take advantage of higher spec machines.

**Comment by MrMashy** [comment]
@baconface That's a perfect summary, I think that should be included in the docs.

**Comment by upicik** [comment]
@MrMashy if I'm not mistaken, docs also should be pulled and merged?

**Comment by upicik** [comment]
@MrMashy @baconbrad I updated quick-start docs and added a commit (above) with citations from [The Chromium Projects](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/developer-faq)

**Comment by zcbenz** [comment]
I don't see any meaning giving a requirement of RAM for Electron, a minimal app may only use about 50MB memory but it is useless for a large app like Atom.

And since Electron is based on Chromium and doing upgrades very often, it is impossible to give an accurate information. What we can do is only to run Electron and see how much RAM it uses, and that information is different on different machines with different versions.

So I'm closing this as won't fix.
