### ISSUE TITLE
Sandbox entitlements error ITMS-90296

### ISSUE THREAD

**Issue by AhadCove** [electron/electron#8363]
I am having problems submitting my app to the app store. Where I am running into an error is sandbox not being enabled. I am adding entitlements when I sign the app, but apparently it is not working. This is the error that is coming up.

> ERROR ITMS-90296: "App sandbox not enabled. The following executables must include the "com.apple.security.app-sandbox" entitlement with a Boolean value of true in the entitlements property list: [( "com.site.app.pkg/Payload/App.app/Contents/Frameworks/App Helper EH.app/Contents/MacOS/QuizzUmmah Helper EH", "com.site.app.pkg/Payload/App.app/Contents/Frameworks/App Helper NP.app/Contents/MacOS/App Helper NP", "com.site.app.pkg/Payload/App.app/Contents/Frameworks/App Helper.app/Contents/MacOS/App Helper", "com.site.app.pkg/Payload/App.app/Contents/MacOS/App" )] Refer to App Sandbox page at https://developer.apple.com/devcenter/mac/app-sandbox/ for more information on sandboxing your app."

Here are my 2 entitlements: Parent:

`<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"> <plist version="1.0"> <dict> <key>com.apple.security.app-sandbox</key> <true/> <key>com.apple.security.application-groups</key> <string>'My team id'.com.site.app</string> </dict> </plist>`

child:

`<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"> <plist version="1.0"> <dict> <key>com.apple.security.app-sandbox</key> <true/> <key>com.apple.security.inherit</key> <true/> </dict> </plist>`

And my build script:

`electron-packager . App --identity='3rd Party Mac Developer Application: 'Company' ('My team Id')' --sign-entitlements='./entitlements.mas' --sign-entitlements-inherit='./inherit.entitlements.mas' --osx-sign --app-version='1.0.0' --build-version='1.0.100' --platform=mas --app-bundle-id='com.site.app' --helper-bundle-id='com.site.app.helper' app-category-type=public.app-category.games --arch=all --icon=icon.icns --overwrite --asar`

**Comment by saurabhsharma** [comment]
Facing same issue.

**Comment by zcbenz** [comment]
Signing an app seems to behave differently depending on your OS and Xcode's versions, I'm afraid we can not help on that.

My only suggestion is to follow how electron-api-demos signs the app: 
https://github.com/electron/electron-api-demos/blob/master/script/mas.sh
