### ISSUE TITLE
Drag and Drop Elements Don't Work Properly

### ISSUE THREAD

**Issue by Alecell** [electron/electron#8364]
* Electron version: 1.4.13
* Operating system: Mac OSX Yosemite (10.10.5)

### Expected behavior

When move a DnD element on screen it don't left any "trace" from where it were to where it is. Regardless of cursor speed.

### Actual behavior

When move a DnD element on screen it left some "trace" from where it were to where it is. With a high speed of cursor.

### How to reproduce

Creating a DnD element and moving it fast on the screen.

### This video shows the bug in my Mac

Note that sometimes when I move the DnD element slower it looks to increase the size. 

[Video of the Issue](https://www.youtube.com/watch?v=ImLfO5g6RNU)

**Comment by TimNZ** [comment]
I think all future issue videos should have an electro sound track!

**Comment by zcbenz** [comment]
This looks like a Chromium bug to me, please report to [Chromium' issues list](https://crbug.com) instead.
