### ISSUE TITLE
net::ERR_INSECURE_RESPONSE error 1.4.13 mac-only

### ISSUE THREAD

**Issue by lukeapage** [electron/electron#8366]
* Electron version: 1.4.13
* Operating system: MACOS

### Expected behavior

No network error

### Actual behavior

We are getting net::ERR_INSECURE_RESPONSE errors on a https css file used within a local html file. The error does not happen on windows, but does happen on multiple different mac machines. This is a recent thing and rolling back electron versions does not help. I suspect that means it is related to the 10 week certificate issue I found noted in other issues.

The bug does not happen in safari or chrome on mac or chrome or electron on windows

**Comment by lukeapage** [comment]
Related: https://github.com/electron/electron/issues/7221
Please let me know if i can add any loggimg. Also happy to dm a public url.

**Comment by kevinsawicki** [comment]
@lukeapage are you able to capture the net log using the `--log-net-log=FILENAME` command line flag and then import it into the `chrome://net-internals/#import` and see if there are more specific errors there?

**Comment by lukeapage** [comment]
Thanks will do that tomorrow (I'm in europe)

**Comment by lukeapage** [comment]
@kevinsawicki this is what I get back from the certificate job in that log

```
17: CERT_VERIFIER_JOB
Start Time: 2017-01-10 07:45:29.731

t=297 [st= 0] +CERT_VERIFIER_JOB  [dt=40]
               --> certificates =
                      -----BEGIN CERTIFICATE-----
                      MII...
                      -----END CERTIFICATE-----
                      
                      -----BEGIN CERTIFICATE-----
                      MII...
                      -----END CERTIFICATE-----
                      
t=337 [st=40] -CERT_VERIFIER_JOB
               --> verified_cert =
                      -----BEGIN CERTIFICATE-----
                      M...
                      -----END CERTIFICATE-----
                      
               --> cert_status = 4 (AUTHORITY_INVALID)
               --> common_name_fallback_used = false
               --> has_md2 = false
               --> has_md4 = false
               --> has_md5 = false
               --> is_issued_by_additional_trust_anchor = false
               --> is_issued_by_known_root = false
               --> public_key_hashes = ["sha1/XYjOYnGk+T/Obk4WIxCCKSsfmTo=","sha256/cRzKlKepyeonS3eGmJhLgq+aY3Kafhm57rxchART2f4="]
```

**Comment by lukeapage** [comment]
I just wondered if it was our proxy but I get the same error on a vanilla mac connected to normal wifi.

**Comment by lukeapage** [comment]
Ok, looked into it and it appears that it is a problem our side - openssl returns
"Verify return code: 21 (unable to verify the first certificate)"

and people around seem to commonly describe the symptoms as "works in the browser but not in the system". I think the problem may be that the site does not sent the intermediatory certificate.

It i strange though that electron does not fetch the intermediatory certificate when chrome does, safari does and electron windows does. Electron on windows includes an additional certificate when the certificate verifier job starts and ends with

```
               --> cert_status = 0 ()
               --> common_name_fallback_used = false
               --> has_md2 = false
               --> has_md4 = false
               --> has_md5 = false
               --> is_issued_by_additional_trust_anchor = false
               --> is_issued_by_known_root = true
               --> public_key_hashes = ["sha1/XYjOYnGk+T/Obk4WIxCCKSsfmTo=","sha256/cRzKlKepyeonS3eGmJhLgq+aY3Kafhm57rxchART2f4=","sha1/UCM4nF92oH7yVEZeTyGW+BRFtB4=","sha256/9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY=","sha1/sYEIGhmkwJQf+uiVKMEkyZs0rMc=","sha256/JbQbUG5JMJUoI6brnx0x3vZF6jilxsapbXGVfjhN8Fg="]
```

**Comment by deepak1556** [comment]
I believe you are hitting https://bugs.chromium.org/p/chromium/issues/detail?id=645629 which was fixed up in versions >=54 https://codereview.chromium.org/2368453002

**Comment by lukeapage** [comment]
Thanks for tracking it down, looks like it
