### ISSUE TITLE
Missing Text rendering

### ISSUE THREAD

**Issue by ibigpapa** [electron/electron#8379]
* Electron version: v1.4.14
* Operating system:
Centos 7.3.1611 (Core)
3.10.0-514.2.2.el7.x86_64
GDM 3.14.2
XFCE 4.12
### Expected behavior

Menus and titles should show

### Actual behavior

Icons show if i disable gpu ```--disable-gpu```

### How to reproduce
1. Install Centos 7.3 minimal from ISO - create a user as well
2. log in as root
3. ```yum install epel-release wget -y```
4. ```yum groupinstall "X Window system"```
5. ```yum groupinstall xfce```
6. ```systemctl set-default graphical.target```
7. ```reboot```
8. log in as user
9. download nvm ```wget https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh```
10. ``` chmod u+x install.sh```
11. ```./install.sh```
10. install node ```nvm install v7```
11. get electron-quick-start ```git clone https://github.com/electron/electron-quick-start```
12. ```cd electron-quick-start```
13. ```npm install```
14. ```npm start```
![electron-quick-start-tab-text-missing](https://cloud.githubusercontent.com/assets/694054/21829947/09706462-d75f-11e6-9299-4e50c607daa9.png)

#### example with vs code
https://github.com/Microsoft/vscode/issues/18365
Steps 1-8
9. download the vs code rpm
10. ```sudo yum localinstall <vscode.rpm>```
11. run ```code```
Extensions shows a blank panel
12. exit code
13. run ```code with --disable-gpu```
14. Extensions shows icons with no words
![vscode-icons-only](https://cloud.githubusercontent.com/assets/694054/21829760/c36c63b8-d75d-11e6-9496-fe20fd08ba88.png)

**Comment by zcbenz** [comment]
This is usually because the prebuilt binaries are not compatible with the free type library on your machine, it can only be solved by compiling Electron targeted with your OS.

I'm merging this to #259.
