### ISSUE TITLE
Atom not preserving window.name when testing angular app

### ISSUE THREAD

**Issue by brandonecraig** [electron/electron#838]
My team is testing an angular app using protractor. To do this, we need to delay bootstrapping angular. To do this protractor adds a defer label to window.name. When angular sees this label it is supposed to define angular.resumeBootstrap() which protractor calls to finish bootstrapping angular after it has loaded the necessary dependencies. 

When we run our tests against atom shell, the tests fail with an "angular never provided resumeBootstrap" error. After some investigation it looks like atom shell resets window.name when it loads a new page. When we run the same tests in Chrome the tests pass. Is window.name supposed to be preserved by atom shell? Is there another way to make atom shell preserve window.name?

**Comment by mkeesey** [comment]
Specifically, `window.name` does not appear to be preserved on a newly loaded page after executing `window.location.replace("http://some-web-address-here")`, so the process that protractor uses to inform angular to hold off on bootstrapping doesn't work quite right. I modified the above code to test for this more specifically. This assumes that Atom.app resides in the current working directory. The test passes when the `binary: "./Atom.app/Contents/MacOS/Atom",` line in config.js is commented out (which uses the system-installed Chrome binary) but fails when using the Atom binary.

atom-shell-spec.js
```javascript
describe('protractor with atom-shell', function() {
	it('should preserve window.name between pages', function() {
		browser.driver.get('http://www.google.com/');  //Running directly with the wrapped driver so it doesn't look for angular
		browser.executeScript(function() { window.name = "HELLO"; });
		browser.executeScript('window.location.replace("http://www.example.com")');
		expect(browser.executeScript('return window.name;')).toEqual('HELLO');
	});
});
```
config.js
```javascript
exports.config = {
	seleniumAddress: 'http://localhost:4444/wd/hub',
	specs: ['./atom-shell-spec.js'],
	capabilities: {
		browserName: "chrome",
		chromeOptions: {
			binary: "./Atom.app/Contents/MacOS/Atom",
			args: ["--test-type=webdriver"]
		}
	}
};
```

After sticking these files into a directory with Atom.app, install protractor if necessary with the steps under Setup at http://angular.github.io/protractor/#/tutorial, then just run `protractor config.js`

@zcbenz - do you have an idea of a good place for me to start looking for where this problem may be caused?

**Comment by zcbenz** [comment]
This bug seems weird to me, I don't know where could be the problem, but to solve it I would try to check if the same bug exists in Content Shell, if it does then I will check Chrome browser's code to find out what they had done, if it does not then I will check what things Content Shell may have done but we didn't.

**Comment by mkeesey** [comment]
I'll take a look at those, thanks!

**Comment by mkeesey** [comment]
So the same bug doesn't exist in Content Shell - it has been difficult so far to figure out what is being done differently in Content Shell that isn't being done in the Atom Shell. Attaching a debugger, I don't see Content Shell calling `DOMWindowV8Internal::nameAttributeSetterCallback` when navigating between pages. This makes me believe that it isn't doing anything special to persist this value, as it looks like this is the only function that can modify the name attribute on the DOM's window object. It does get called (as I would expect) whenever the value is set via javascript.

I'm in the process of rebuilding libchromiumcontent etc with debugging symbols to try to see what does it in Atom.

**Comment by mkeesey** [comment]
As you probably guessed, I haven't really had time to work on this. It wasn't really clear to me why this was happened - this property seems to get persisted with some magic down in V8 land. In any case, a workaround we found is detailed in this issue: https://github.com/angular/protractor/issues/1464 .

**Comment by zcbenz** [comment]
I'm closing this since no one is paying attention to it, and there are workarounds for it.

**Comment by evilaliv3** [comment]
This seems to be still actual and be affecting safari 12 and 13; did anyone identified a solution?
