### ISSUE TITLE
Cannot access document property

### ISSUE THREAD

**Issue by haribabu500** [electron/electron#8383]
Ive recently made an electron which has the following script in onClick event of a button in a popup.

`opener.document.forms[0].submit();window.close();'`

the code seems okay when i render it via browser but when i run it via electron it says 
Cannot read property 'forms' of undefined
any suggestions...

**Comment by zeke** [comment]
From https://github.com/electron/electron/issues/7780:

> the opener is null because a window created with `new BrowserWindow` is a top-level window created by the main process. `window.opener` should only be set in a child window that you create with `window.open`. 

How are you creating the window? Please share some example code that reproduces the issue.

**Comment by kevinsawicki** [comment]
`window.opener.document` is not supported in Electron, you can use the `ipcRenderer` and `ipcMain` modules to communicate between windows/processes.

http://electron.atom.io/docs/api/ipc-renderer/

**Comment by haribabu500** [comment]
`console.log(require.resolve('electron'))

const electron = require('electron')
// Module to control application life.
const app = electron.app
// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow

const path = require('path')
const url = require('url')

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow

function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600})

  // and load the index.html of the app.
  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))

  // Open the DevTools.
  mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
          //============================= nfc begin============================  
          // 'use strict';

          var _nfcPcsc = require('nfc-pcsc');

          var _nfcPcsc2 = _interopRequireDefault(_nfcPcsc);

          function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

          var nfc = new _nfcPcsc2.default();

          // var mod=require('nfc-pcsc');
          // var nfc=new mod.NFC();
           
          nfc.on('reader', reader => {
           
              // console.log(`${reader.reader.name}  device attached`);
           
              // needed for reading tags emulated with Android HCE 
              // custom AID, change according to your Android for tag emulation 
              // see https://developer.android.com/guide/topics/connectivity/nfc/hce.html 
              reader.aid = 'F222222222';
           
              reader.on('card', card => {
                  console.log("==================================================");
                  var cardid=card.uid;
                  console.log(cardid);
                  
                  mainWindow.loadURL('http://localhost/AA-EMR/interface/main/card_dashboard.php?card_id='+cardid);
           
              });
           
              reader.on('error', err => {
                  console.log(`${reader.reader.name}  an error occurred`, err);
              });
           
              reader.on('end', () => {
                  console.log(`${reader.reader.name}  device removed`);
              });
           
          });
           
          nfc.on('error', err => {
              console.log('an error occurred', err);
          });  
          //============================= nfc end============================
  }

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process`

And I included my project in index page by
`<script type="text/javascript">
    
    location.href="<<My project URl>>";
    </script>`
