### ISSUE TITLE
Notifications on Windows 7

### ISSUE THREAD

**Issue by alespergl** [electron/electron#8384]
#262 added support for [notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) on Windows 8 and later. We are implementing it internally for Windows 7 as well. I would like to collect opinions about whether that work would be something worth contributing to the mainline.

There is still a lot of Windows 7 users in the world:
- 48% according to [netmarketshare.com](https://www.netmarketshare.com/operating-system-market-share.aspx)
- 40% according to [statista.com](https://www.statista.com/statistics/218089/global-market-share-of-windows-7/)

Based on the discussion in #262 and [other](https://github.com/Thomas101/wmail/issues/327) [places](https://github.com/RocketChat/Rocket.Chat.Electron/issues/55), it seems to be a common issue that people face. They usually end up using a third-party Node module based solution (e.g. [node-notifier](https://github.com/mikaelbr/node-notifier), [electron-notify](https://github.com/hankbao/electron-notify)), but that's arguably not as comfortable as using the standard notification API across all supported platforms and usually adds more dependencies to the app.

We are now looking at two possible implementations:
- Port code from Chromium
- Implement from scratch (probably easier to do)

Please share your view on either the need for having this gap filled upstream, or the implementation approach.

**Comment by lightswitchr** [comment]
I would like to see this implemented, however I assume [the balloon notifications](http://electron.atom.io/docs/api/tray/#traydisplayballoonoptions-windows) do work on Windows 7?

**Comment by ColinEberhardt** [comment]
>  I assume the balloon notifications do work on Windows 7?

Yes, balloon notifications do work, and for Windows 7 the Notification API could be polyfilled to make use of them.

However, balloon notifications are pretty weak in terms of the functionality they deliver. I'd prefer to see an implementation that is more aligned with Windows >8 or OSX in terms of overall richness of experience.

**Comment by alespergl** [comment]
To give an update on this, we have the feature implemented now. The toasts look and behave similarly to those on Windows 8 and 10. We need to sort out some processes before we'll be able to contribute it.

**Comment by ColinEberhardt** [comment]
@alespergl - that's great news! Is there somewhere we can see this in action? Is it part of the VSCode codebase?

**Comment by alespergl** [comment]
Here's a short video of how it looks.
[notifications.zip](https://github.com/electron/electron/files/780767/notifications.zip)

**Comment by akashnimare** [comment]
@alespergi could you provide the gist for the same? Would be great. I'm having hard time implementing desktop notifications on windows 7 😭

**Comment by jasonpoe** [comment]
Any update @alespergl ?  Would love to see this make it in.

**Comment by alespergl** [comment]
@jasonpoe Sorry, the internal processes are taking a bit longer than expected. But we are definitely working to push this through. I'll post an update once there's more info to share.

**Comment by akashnimare** [comment]
@alespergl awesome. Waiting....

**Comment by ronjouch** [comment]
Awesome! One nit: the [Desktop Environment Integration docs](https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md#windows) still state that:

> *On Windows 7, notifications are not supported. You can however send "balloon notifications" using the [Tray API](https://github.com/electron/electron/blob/master/docs/api/tray.md#traydisplayballoonoptions-windows).*

→ Are we talking about two different things, or are the docs simply outdated?

**Comment by MarshallOfSound** [comment]
@ronjouch AFAIK docs are outdated and that disclaimer probably just needs to be modified to explain the implementation or be removed completely. 👍

**Comment by kevinsawicki** [comment]
> AFAIK docs are outdated and that disclaimer probably just needs to be modified to explain the implementation or be removed completely

@alespergl would you mind updating the `desktop-environment-integration.md` doc about the state of Windows 7 notifications? Thanks.

**Comment by gasi-signal** [comment]
We were excited to adopt this for Windows 7 but ran into an unfortunate bug with notification grouping using `tag`. When using a static `tag` on Windows 7, notifications only show up a few times and then stop. To save other people who have run into this some time, please check: https://github.com/electron/electron/issues/11189
