### ISSUE TITLE
How to replace menu items while menu is open?

### ISSUE THREAD

**Issue by averissimo** [electron/electron#8385]
Replacing menu while it is open creates an empty placeholder instead.

Reopening makes it fine.

__Is this the expected behavior, or is it a bug?__

In the example below, I forced a rendering whenever a message was received. We need to render it sometimes, as there are options being set via the menu and in some states items are disabled

![](https://cloud.githubusercontent.com/assets/211358/21829422/bf336500-d78d-11e6-8d24-08bef10f54fe.gif)

* Electron version: 1.4.13
* Operating system: Ubuntu 14.04

**Comment by zcbenz** [comment]
This is a limitation of the menu's implementation, the menus are create from models and are only updated when they show. This implementation makes it possible to pass the same menu to multiple places.

I'm closing this as won't fix since the behavior is by-design.
