### ISSUE TITLE
Detecting network activity

### ISSUE THREAD

**Issue by MPolymath** [electron/electron#8387]
Is there a way to detect if any network activity is going on in the background through electron?
If not I would like to request it as a feature.

Thank you,

**Comment by YurySolovyov** [comment]
If you're asking for a feature, at least provide the metrics you're interested in. Also, sharing your use case would be helpful too.

**Comment by MPolymath** [comment]
Yes my appologies I will provide further details by the end of tommorow.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
