### ISSUE TITLE
navigator.mediaDevices.enumerateDevices() lost some Virtual cameras

### ISSUE THREAD

**Issue by cgisky** [electron/electron#8388]
win10   win7 
In Chrome 53，navigator.mediaDevices.enumerateDevices() get  16 devices.
but in electron  it just  get 13 devices.
Lost some  virtual cameras,like "e2eSoft VCam" or "6RoomsCamV10"

I  use ffmpeg
ffmpeg.exe -list_devices true -f dshow -i dummy

[dshow @ 03ba7720] DirectShow video devices (some may be both video and audio devices)
[dshow @ 03ba7720]  "Logitech HD Pro Webcam C920"
[dshow @ 03ba7720]     Alternative name "@device_pnp_\\?\usb#vid_046d&pid_082d&mi_00#6&2b8b344&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\{bbefb6c7-2fc4-4139-bb8b-a58bba724083}"
[dshow @ 03ba7720]  "6RoomsCamV10"
[dshow @ 03ba7720]     Alternative name "@device_sw_{860BB310-5D01-11D0-BD3B-00A0C911CE86}\6RoomsCamV10"
[dshow @ 03ba7720]  "e2eSoft VCam"
[dshow @ 03ba7720]     Alternative name "@device_sw_{860BB310-5D01-11D0-BD3B-00A0C911CE86}\e2eSoft VCam"
[dshow @ 03ba7720]  "YY浼翠荆"
[dshow @ 03ba7720]     Alternative name "@device_sw_{860BB310-5D01-11D0-BD3B-00A0C911CE86}\yyvcam"
[dshow @ 03ba7720] DirectShow audio devices
[dshow @ 03ba7720]  "楹﹀厠椋?(HD Pro Webcam C920)"
[dshow @ 03ba7720]     Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{BD57E674-82CC-4B3E-A9DF-548E97BFA28B}"
[dshow @ 03ba7720]  "CB4N Analog In 1/2 (Cube4Nano WDM Audio)"
[dshow @ 03ba7720]     Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{7BB22EAB-9C50-45F4-8005-727F1B73C47A}"
[dshow @ 03ba7720]  "CB4N Virtual In 1/2 (Cube4Nano WDM Audio)"
[dshow @ 03ba7720]     Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{AD28336A-44AA-4BC7-B903-3594FF36C60D}"
[dshow @ 03ba7720]  "CB4N SPDIF In 1/2 (Cube4Nano WDM Audio)"
[dshow @ 03ba7720]     Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{B484B490-6222-4946-AA86-EA6F693DC31D}"

we can find   some devices have "@device_cm_"or "@device_pnp_" in "Alternative name"  is OK.
but   some devices have "@device_sw_" in "Alternative name" is lost

**Comment by zcbenz** [comment]
It depends on the Chrome version used in Electron and I'm afraid we are not able to fix it without enough information. I suggest trying Electron versions with newer Chrome, or wait for an upgrade of Chrome in Electron.

**Comment by mlkyo** [comment]
try 32bit electron for it.

**Comment by duanwenjian** [comment]
hi, Is this problem solved ?
