### ISSUE TITLE
pointer-events: none and touch events in webview

### ISSUE THREAD

**Issue by matthew-lang** [electron/electron#8389]
* Electron version: 1.4.14
* Operating system: Ubuntu 14.04

If there is an overlay in your app with `pointer-events: none` and you're using touch events, basic input within webviews will not work. This means scrollbars, buttons, checkboxes, `<select>`, etc.

To reproduce: 
parent.html:
```
<html>
  <head>
    <style>
      html, body {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
      .overlay {
        position:absolute;
        top:0;
        left:0;
        right:0;
        bottom:0;
        pointer-events:none;
        background-color:rgba(0,0,0,0.5);
      }
      webview {
        pointer-events: initial;
      }  
    </style>
  </head>
  <body>
    <webview src="./child.html"></webview>
    In Parent:<input type="checkbox" />
    <div class="overlay"></div>
  </body>
</html>
```

child.html:
```
<html>
  <head>
    <style>
      html, body {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 25px;
      }
    </style>
  </head>
  <body>
      <select>
        <option>test</option>
        <option>test2</option>
      </select>
      <br />
      <input type="checkbox">
    <script>
    //document.querySelector('select').addEventListener('touchstart', alert);
    </script>
  </body>
</html>
```

run: `electron --touch-events parent.html`

You will see that when using touch, you will be unable to check the checkbox or select something from the dropdown for the inputs within the webview, but the checkbox outside of the webview you can check and uncheck without a problem.
note: you need to have access to a touch screen to reproduce this. It works fine when I use the mouse

**Comment by tiemevanveen** [comment]
I'm running into a similar issue where it's not possible to interact with a basic login UI in a webview. The issue seems to only present when a user used a carousel in our main application. I'll try to add an example here as well, but it's quite hard to isolate the problem from our application.

**Comment by zcbenz** [comment]
Is it still an issue on Electron v1.7.x? Sorry I don't have a touch device to test.

**Comment by codebytere** [comment]
Closing due to abandonment.
