### ISSUE TITLE
full support for multiple webkitdirectory

### ISSUE THREAD

**Issue by jimtang9527** [electron/electron#839]
<input> file . multiple webkitdirectory in chrome can get sub files.but atom-shell can select directory,sub file set only current directory? is bug?

**Comment by appelgriebsch** [comment]
+1

**Comment by inossidabile** [comment]
+1 - quite a misleading problem really

**Comment by filipe-nunes** [comment]
+1 - only one file in the htmlElement.files and it only brings its basic info...

**Comment by camow7** [comment]
+1 I'm seeing this as well. On chrome localhost it works perfectly but once built for electron it only gets the selected folder name.

**Comment by zhangling0443** [comment]
+1 only gets the selected folder name! I need to support webkitdirectory strongly!

**Comment by dengyaolong** [comment]
duplicate of https://github.com/electron/electron/issues/9002

**Comment by dengyaolong** [comment]
+1 ！ webkitdirectory is necessary！

**Comment by DenisVuyka** [comment]
This ticket is 3+ years old already and still causes lots of issues. Are there any plans to address it?

**Comment by negamaxi** [comment]
No updates on this?

**Comment by ythvg** [comment]
the same problem, no updates ???

**Comment by schwiet** [comment]
Does anyone have a workaround for this?

**Comment by dengyaolong** [comment]
@schwiet my workaround is use dialog choose dir, and use node.js walk the dir.

**Comment by codebytere** [comment]
Given that there exist workarounds, this is something that isn't on our current roadmap and which I am thus goin to tag as `wontfix`.

**Comment by dengyaolong** [comment]
@codebytere but webkitdirectory is really important while workaround need a lot of hack code.

**Comment by MajuMadhusudanan** [comment]
need a fix to address this issue. Workaround provided require more changes and risky also

**Comment by eggerand13** [comment]
I think it would be really helpful if that issue was addressed, especially since the workaround is quite troublesome.

**Comment by fristys** [comment]
+1 on the fix. Labelling this as `wontfix` and making people use beyond hacky workarounds is completely unacceptable.
