### ISSUE TITLE
Node Tcp Server shutdown when close a BrowserWindow

### ISSUE THREAD

**Issue by Inori** [electron/electron#8393]
* Electron version: electron-v1.4.14-win32-ia32
* Operating system: Win7 SP1 X64

### Expected behavior

Node tcp server works as before when a BrowserWindow closed.

### Actual behavior

The tcp server can not receive connections after any BrowserWindow closed.

### How to reproduce

Server code:
```
const electron = require('electron');
const net = require('net');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

let server = null;

function createServer() {
    server = net.createServer((c) => {
        // 'connection' listener
        console.log('client connected');
        c.on('end', () => {
            console.log('client disconnected');

            mainWindow = new BrowserWindow({width: 800, height: 600});
            mainWindow.close();

        });
        c.write('hello\r\n');
        c.pipe(c);
    });

    server.on('error', (err) => {
    throw err;
    });
    server.listen(8124, () => {
    console.log('server bound');
    });
}

app.on('ready', createServer);
```

Client code:
```
const net = require('net');
const client = net.createConnection({port: 8124}, () => {
  //'connect' listener
  console.log('connected to server!');
  client.write('world!\r\n');
});
client.on('data', (data) => {
  console.log(data.toString());
  client.end();
});
client.on('end', () => {
  console.log('disconnected from server');
});
```

The code above modified from official [Node Documentation](https://nodejs.org/api/net.html#net_event_data)

The server can only receive the first connection, then after create and close a BrowserWindow , it won't reveive any connection again. (Not only in the server side code, anywhere I do this will result in the same behavior.)

And the client reports:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:8124
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

**Comment by TimNZ** [comment]
If you remove the two lines creating and closing BrowserWindow does it work as expected?

**Comment by Inori** [comment]
@TimNZ Yes, it is. The server works as expected.

**Comment by TimNZ** [comment]
By default Electron quits when all windows have been closed.
You didn't notice the server app has terminated after the first connection?

Add this to server.js:

```
app.on('window-all-closed',() => {

})
```

**Comment by Inori** [comment]
@TimNZ That is the reason! Thank you very much.
