### ISSUE TITLE
Ability to create circular / elliptical shaped BrowserWIndow

### ISSUE THREAD

**Issue by bakkiraju** [electron/electron#8396]
* Electron version: 1.4.13
* Operating system: mac, windows

### Expected behavior
Should be able to pass in radius (radii) to create a circular, elliptical window. 
Something like shown here  https://www.cocoawithlove.com/2008/12/drawing-custom-window-on-mac-os-x.html

### Actual behavior

Can only create rectangular / square shaped BrowserWindows

**Comment by adamjacob** [comment]
Can't you just create a frameless and transparent window and set your content of your page to whatever shape you want using CSS.

https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#transparent-window

**Comment by bakkiraju** [comment]
Ya that works

If I create a BrowserWindow without height and width and then use CSS 
var circularPrefsWindow = new BrowserWindow({
       transparent:true,
       frame  : false
   })

**Comment by kevinsawicki** [comment]
Closing this out, a transparent window seems like the right path to use here, thanks @adamjacob for mentioning this 👍

**Comment by johnnysparav** [comment]
width Integer (optional) - Window's width in pixels. Default is 800.
height Integer (optional) - Window's height in pixels. Default is 600.

from Electron BrowserWindow docs

I still get the default window size with the circle inside it despite not specifying the width and height. Sounds good, doesnt work.
