### ISSUE TITLE
openExternal take too mucho to open a browser

### ISSUE THREAD

**Issue by DracotMolver** [electron/electron#8397]
* Electron version: 1.4.12
* Operating system: Linux. Solus os

### Expected behavior

Open the default browser (in my case firefox) to see a weppage

### Actual behavior

It works, but take too much time. In windows is the same but not too much time. I'm talking about 15 seconds

### How to reproduce
```javascript
function openExternalLin() {
  e.preventDefault();
  shell.openExternal(href); // href contains any links
}
```

**Comment by groundwater** [comment]
Hi @DracotMolver. I tried this on Windows and it's near-instant. Do you know if Firefox is booted as a child process to Chromium? `$ pstree` should show you.

**Comment by deepak1556** [comment]
@DracotMolver can you test if just running `xdg-open <url>` results in similar behavior.

**Comment by DracotMolver** [comment]
@deepak1556  I use `xdg-open <url>` and it was faster. I haven't try what @groundwater suggested me, my work is comsuming too much time right now :(. But I will do it this weekend.

**Comment by DracotMolver** [comment]
Don't know what was it, but now it's opening faster.
