### ISSUE TITLE
ngRouter of Angularjs not work

### ISSUE THREAD

**Issue by fedyfausto** [electron/electron#8398]
* Electron version: latest
* Operating system: win64

### Expected behavior

Hello i'm trying to make a single page app with electron and angularjs 1 and change view with ngRouter

### Actual behavior

 the angular router seem not works with electron.. any solution to this issue?

### How to reproduce
Try to make a simple one page with angular and angular router

**Comment by fedyfausto** [comment]
possible fix:

using the hashprefix on router works

**Comment by enlight** [comment]
GitHub issues are for bug reports and feature requests, questions about using Electron should be directed to [the community](https://github.com/electron/electron#community).
