### ISSUE TITLE
OpenType CALT feature related with `*` character does not work.

### ISSUE THREAD

**Issue by be5invis** [electron/electron#8405]
Tested with Iosevka and Fira Code: `*`-related ligatures are not enabled.

**Comment by kevinsawicki** [comment]
@be5invis can you provide a minimal reproduction app that demonstrates this issue? Thanks.

**Comment by be5invis** [comment]
@kevinsawicki
```
<div style="font-family:Fira Code; font-feature-settings: 'calt' on"> &lt;*&gt; </div>
```

**Comment by kevinsawicki** [comment]
@be5invis Thanks for the sample, can you provide a screenshot of what you see renderedin Electron with this sample vs. what you see rendered in Chrome?

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/22040358/86228a74-dd3d-11e6-8241-d1d2fd496278.png)
![image](https://cloud.githubusercontent.com/assets/240091/22040385/a03be5f4-dd3d-11e6-8b2e-8c0bb1dafd1d.png)

**Comment by kevinsawicki** [comment]
@be5invis thanks, this looks to be fixed in Chrome 54, here is what I see on the Chrome 54 branch in #8406, does it look right to you?

![screen shot 2017-01-17 at 1 20 20 pm](https://cloud.githubusercontent.com/assets/671378/22040455/b6e2170a-dcb7-11e6-996e-672b51ccb24f.png)

**Comment by be5invis** [comment]
@kevinsawicki IDK. Could you please show the result in the released version on OSX? Maybe it is platform-specific...

**Comment by kevinsawicki** [comment]
Here is the 1.4.14 released version on macOS:

![screen shot 2017-01-17 at 1 22 19 pm](https://cloud.githubusercontent.com/assets/671378/22040538/04583afa-dcb8-11e6-9fc1-9503aeb20429.png)

**Comment by be5invis** [comment]
@kevinsawicki Thanks. Maybe the Chrome-v54 one fixed this.
Do you have any screenshot on Windows and Linux?

**Comment by kevinsawicki** [comment]
> Do you have any screenshot on Windows and Linux?

Sure, will take a few minutes to launch/build there.

**Comment by kevinsawicki** [comment]
@be5invis here it is on Windows 10, left is 1.4.14 (Chrome 53), right is Chrome 54 branch:

<img width="971" alt="screen shot 2017-01-17 at 1 54 47 pm" src="https://cloud.githubusercontent.com/assets/671378/22041672/95d21268-dcbc-11e6-868a-54dfc2a7590a.png">

**Comment by be5invis** [comment]
Good. Waiting for your new version.
cc. @dbaeumer @alexandrudima
