### ISSUE TITLE
BrowserWindow shows frame from when it was hidden until first render after unhiding

### ISSUE THREAD

**Issue by blixt** [electron/electron#8410]
* Electron version: 1.4.14
* Operating system: macOS 10.12.2 (16C67)

### Expected behavior

I expected to have control of what would show when the window is unhidden. E.g., a call to render the `BrowserWindow` once right after I hide it so that when it is unhidden that will show until the first rerender completes.

### Actual behavior

The content that was visible when the window was hidden was shown for up to a second as the `BrowserWindow` was rendering for the first time after being unhidden.

### How to reproduce

Have content that updates every frame (e.g., camera input). Hide the window and show it again. For a while the old camera frame will show.

Sample repo: https://github.com/blixt/electron-hidden-draw

This sample will show/hide a camera window automatically every 2 seconds. To see the issue, do something like hold up your hand to the camera until the window disappears. Then put your hand down and when the window reappears the old frame will show momentarily even though the camera has been recording the whole time.

If it's not possible to pre-render the next camera frame before the window shows, then I'd like to at least be able to clear the image after the window has been hidden so that the user doesn't see the old frame when it is unhidden again.

Note that in my actual app the issue is much more pronounced, probably because it's a more complex app. (That's why I added the CSS effects in the sample: to make the initial render slower.)

**Comment by zcbenz** [comment]
This is how Chromium's rendering works, I'm not sure if there is a way to fix this. I'm closing this since I'm afraid non of us is familiar with Chromium's rendering enough to be able to fix it.

**Comment by dougmbarcellos** [comment]
This is resolved adding the property `backgroundThrottling: false` in **webPreferences**:  <g-emoji alias="tada" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f389.png" class="emoji">🎉</g-emoji>

```js
mainWindow = new BrowserWindow({
  width: 400,
  height: 600,
  show: false,
  webPreferences: {
    nodeIntegration: true,
    backgroundThrottling: false // <----
  },
  resizable: false
})
```
