### ISSUE TITLE
HTML5 Notification API not displaying notifications on MacOS 10.10.5

### ISSUE THREAD

**Issue by wraithan** [electron/electron#8411]
* Electron version: 1.4.14 (Also tried 1.4.13 and 1.3.13 to see if it was a regression, they also failed)
* Operating system: MacOS 10.10.5

### Expected behavior

HTML5 Notification API should display a notification on the side and in the notification center.

### Actual behavior

The `Notification` object is created without but no notification is displayed.

### How to reproduce

I tried this first in my own app, but after that failed I also tried https://github.com/hokein/electron-sample-apps/tree/master/notifications as that seemed to be a good source of examples and may be a better example of it not working as it includes image and non image variants (both don't work).

**Comment by groundwater** [comment]
Hey @wraithan! Sorry for the delay. I'm working my way through the backlog.

Can you reproduce this in the latest stable `1.4.15` and/or our beta `1.6.0`?

**Comment by zeke** [comment]
Heya @wraithan. They're working for me.

![screen shot 2017-02-22 at 4 26 47 pm](https://cloud.githubusercontent.com/assets/2289/23239413/ec73ab42-f91b-11e6-9c49-b176104cde63.png)

Do you by any chance have "Do Not Disturb" enabled?

<img width="780" alt="screen shot 2017-02-22 at 4 28 07 pm" src="https://cloud.githubusercontent.com/assets/2289/23239417/f055982e-f91b-11e6-934e-33c6e472fe16.png">

**Comment by zeke** [comment]
Hey @wraithan. Pretty sure this is not a regression, so I'm going to close this. Feel free to comment here if you're still having trouble.
