### ISSUE TITLE
No Vista, right?

### ISSUE THREAD

**Issue by techtonik** [electron/electron#8413]
Running it on Vista give this:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	ElectronAPIDemos.exe
  Application Version:	1.4.1.0
  Application Timestamp:	57e3afac
  Fault Module Name:	SHELL32.dll!GetCurrentProcessExplicitAppUse
  Fault Module Version:	6.0.6002.24024
  Fault Module Timestamp:	57f7c302
  Exception Code:	c0000139
  Exception Offset:	00009f85
  OS Version:	6.0.6002.2.2.0.768.2
  Locale ID:	1033
  Additional Information 1:	9d13
  Additional Information 2:	1abee00edb3fc1158f9ad6f44f0f6be8
  Additional Information 3:	9d13
  Additional Information 4:	1abee00edb3fc1158f9ad6f44f0f6be8

Read our privacy statement:
  http://go.microsoft.com/fwlink/?linkid=50163&clcid=0x0409
 ```

Any alternatives for wrapping web app into desktop one?

**Comment by enlight** [comment]
No, only Windows 7 or later is supported.

**Comment by techtonik** [comment]
@enlight is it documented somewhere?

**Comment by dkfiresky** [comment]
@techtonik http://electron.atom.io/docs/development/build-instructions-windows/#prerequisites

**Comment by enlight** [comment]
Supported platforms are documented at http://electron.atom.io/docs/tutorial/supported-platforms/

**Comment by techtonik** [comment]
I mean that Unity development tools don't load on old systems too, but produced binaries do. It seems not the case with this framework, and `supported platforms` are not clear enough to clarify the distinction.

**Comment by enlight** [comment]
The supported platforms page I linked specifies the operating systems Electron apps can run on, you cannot run Electron apps on anything older than Windows 7 because Electron uses APIs that are only available in Windows 7 or later.
