### ISSUE TITLE
Using Google Recaptcha

### ISSUE THREAD

**Issue by alvarolb** [electron/electron#8414]
* Electron version: 1.4.13
* Operating system: Any

I want to use Google Recaptcha inside an electron APP, but it fails when trying to validate the captcha:

Uncaught SecurityError: Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "file://". The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "file". Protocols must match.

Is there any way to make that work?

Thanks! Best regards.

**Comment by KagamiChan** [comment]
By keyword seraching in embed code I find some lines which seem to me checking `file:` protocol:
```
                    d = "file:" == b.location.protocol ? "*" : b.location.protocol + "//" + b.location.host,
                    a = w(function(a) {
                        if (("*" == d || a.origin == d) && a.data == c) this.port1.onmessage()
                    }, this);
```

A [related topic](https://groups.google.com/forum/?fromgroups#!topic/recaptcha/6O4MTigYVPw) was answered by reCaptcha support saying that they would implement custom protocol support. So maybe registering a different protocol helps, if custom protocol is already supported.

**Comment by kevinsawicki** [comment]
> By keyword seraching in embed code I find some lines which seem to me checking file: protocol:

Thanks for looking into this and finding that topic thread 👍 

>  So using a different protocol may help, if custom protocol is already supported.

You can use a custom protocol using the `protocol` module in Electron to workaround the `file:` check.

See http://electron.atom.io/docs/api/protocol for more details.

Closing this out.

**Comment by KagamiChan** [comment]
To clarify, I don't know if custom protocol has been supported by reCaptcha as the support team said, because the code is uglified and I'm not developing with it. Anyone who made it work may leave a positive comment :)

**Comment by kevinsawicki** [comment]
@KagamiChan it appears it does support it, I was able to load it using this app:

```js
const {app, BrowserWindow, ipcMain, protocol} = require('electron')
const fs = require('fs')
const path = require('path')

let window

protocol.registerStandardSchemes(['test'])

app.once('ready', () => {
  window = new BrowserWindow({
    webPreferences: {
      nodeIntegration: false
    }
  })
  protocol.registerBufferProtocol('test', (request, callback) => {
    callback({mimeType: 'text/html', data: fs.readFileSync(path.join(__dirname, 'index.html'))})
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })

  window.loadURL(`test://index.html`)
})
```

![screen shot 2017-01-17 at 2 45 22 pm](https://cloud.githubusercontent.com/assets/671378/22043236/97f4cc6e-dcc3-11e6-95e3-dec29d66bc17.png)

**Comment by marcelobcortes** [comment]
@kevinsawicki can you test it again?
looks like recaptcha got another trick to block from being used in electron

**Comment by arminghm** [comment]
@marcelobcortes did you find any solution to use recaptcha in electron?

**Comment by marcelobcortes** [comment]
tried everything that i found
either i was not able to set this trick up properly (and dont even notice that i made wrong) or google might have found a way to prevent us i guess
sad history

**Comment by H4kt** [comment]
> @KagamiChan it appears it does support it, I was able to load it using this app:
> 
> ```js
> const {app, BrowserWindow, ipcMain, protocol} = require('electron')
> const fs = require('fs')
> const path = require('path')
> 
> let window
> 
> protocol.registerStandardSchemes(['test'])
> 
> app.once('ready', () => {
>   window = new BrowserWindow({
>     webPreferences: {
>       nodeIntegration: false
>     }
>   })
>   protocol.registerBufferProtocol('test', (request, callback) => {
>     callback({mimeType: 'text/html', data: fs.readFileSync(path.join(__dirname, 'index.html'))})
>   }, (error) => {
>     if (error) console.error('Failed to register protocol')
>   })
> 
>   window.loadURL(`test://index.html`)
> })
> ```
> 
> ![screen shot 2017-01-17 at 2 45 22 pm](https://cloud.githubusercontent.com/assets/671378/22043236/97f4cc6e-dcc3-11e6-95e3-dec29d66bc17.png)

Is that still working for you?
In our case it still gives `incorrect-captcha-sol` error

**Comment by singhparminder02** [comment]
For anyone stumbling on this in 2023 or later, I've tried the solution recommended by @Romain-P in at this link and it seems to work perfectly well (both in unpackaged as well as packaged mode)

https://github.com/electron/electron/issues/8414#issuecomment-530939597
