### ISSUE TITLE
XHR failed with net::ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by rico345100** [electron/electron#8419]
* Electron version: 1.3.5 prebuilt
* Operating system: MacOS

### Expected behavior
In my local MacOS, requesting xhr via fetch worked fine, but tested on another MacOS, it fails.

### Actual behavior
It fails with net::ERR_INSECURE_RESPONSE error. Even execute fetch on console directly, it still fails with same error. I googled but nothing useful information found. I reporting this because it looks like Electron issue. Because testing same code on Chrome was fine.

**Comment by kevinsawicki** [comment]
> Electron version: 1.3.5 prebuilt

Are you able to reproduce this on Electron 1.4 as well? 1.4.14 is the latest release, sounds like it could be #8366

**Comment by rico345100** [comment]
I just tested with Electron 1.4.x, still won't work. Every xhr fails with ERR_INSECURE_RESPONSE.

**Comment by kevinsawicki** [comment]
@rico345100 can you provide some example code to help us reproduce this issue?

**Comment by dkfiresky** [comment]
@rico345100 are you sending the request using HTTPS protocol?

**Comment by rico345100** [comment]
@dkfiresky  Yes, I am. How can I use a self-signed certificate on Electron? Could you tell me some more details?

**Comment by MarshallOfSound** [comment]
@rico345100 If you are using a self signed certificate you need to either add the certificate to the local machines trust store (KeyChain Access on macOS) or allow the certificate with the `certificate-error` event.

http://electron.atom.io/docs/api/app/#event-certificate-error

**Comment by rico345100** [comment]
@MarshallOfSound It works now! Many thanks!

**Comment by wangpin34** [comment]
@MarshallOfSound  I followed the instruction in [http://electron.atom.io/docs/api/app/#event-certificate-error](http://electron.atom.io/docs/api/app/#event-certificate-error) and my problem resolved. But when I tested my app behind a http proxy, it always forwarded to network error page.  Is there any change needed for this situation?

```javacript
const {app} = require('electron')

app.on('certificate-error', (event, webContents, url, error, certificate, callback) => {
  if (url === 'https://github.com') {
    // Verification logic.
    event.preventDefault()
    callback(true)
  } else {
    callback(false)
  }
})
```
Thanks.
