### ISSUE TITLE
Window height size on Windows cannot be set as low as on macOS

### ISSUE THREAD

**Issue by aredfox** [electron/electron#8420]
* Electron version: 1.4.14
* Operating system: Windows 7 SP1

### Expected behavior

setting BrowserWindow's height makes a window on the same height as the other OS'es. Now the behaviour is platform dependent, it should be platform agnostic.

### Actual behavior

setting BrowserWindow's height doesn't set real height, but constraints it to a certain given size that's at least higher. Whilst on macOS I do get the size "16" I entered, but on Windows (7 SP1) it's a lot bigger/higher.
```
const { width, height } = electron.screen.getPrimaryDisplay().workAreaSize;
    const mW = Math.round(width / 3);
    const mH = 16;
        barWindow = new BrowserWindow({
            width: mW, height: mH,
            minWidth: mW, minHeight: mH,
            maxWidth: mW, maxHeight: mH});
```

### Screenshots of "Actual behaviour"
**Windows** - where you see a gray top bar that is higher than on it's macOS variant, yet it's the same API being used
[Windows_Behaviour.png](https://postimg.org/image/ciec9hvbh/)
<img src="https://s30.postimg.org/recvh36q9/Windows_Behaviour.png"/>

**macOS** - where you see the darkgray floating bar on top is smaller, as expected and programmed to do
[macOS_Behaviour.png](https://postimg.org/image/52u1sp27b/)
<img src="https://s23.postimg.org/7k5szym3v/mac_OS_Behaviour.png"/>

### How to reproduce
using new BrowserWIndow({}) api.

**Comment by kevinsawicki** [comment]
@aredfox can you include the full set of arguments you are providing to the `BrowserWindow` constructor? Or a small reproduction app that is a fork of https://github.com/electron/electron-quick-start

**Comment by zcbenz** [comment]
Closing until more information is provided.
