### ISSUE TITLE
Mac autoupdater: pub_date in ISO 8601 with fractions of seconds is not parsed correctly

### ISSUE THREAD

**Issue by kakozu** [electron/electron#8422]
The documentation specifies, that:

> "pub_date"  if present must be formatted according to ISO 8601.

When using the project with Electron, it works correctly with a date formatted similarly as in the example: `"2017-01-17T11:37:55Z"`. However, when using it with second fractions, as in the following example: `"2017-01-17T11:37:55.932Z"`, it is not correctly reported back to the application. 

This is inconvenient, because that format is the default way of formatting time to ISO8601 in some environments (e. g. JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) 

### Expected behavior

When the update server sends an update response with pub_date formatted in ISO8601 with fractions of seconds (e.g. `"2017-01-17T11:37:55.932Z"`), it should be correctly passed back to the application with the _update-downloaded_ event.

### Actual behavior

releaseDate that is emitted with the _update-downloaded_ event is `1970-01-01T00:00:00.000Z`. 

### How to reproduce

Make your update server return update data with pub_date formatted to ISO8601 with fractions of seconds, perform an update check and observe the values emitted with _update-downloaded_.

**Comment by zcbenz** [comment]
This is a bug of https://github.com/Squirrel/Squirrel.Mac, please report there instead.
