### ISSUE TITLE
Going in to Kiosk while in FullScreen does not disable the dock. 

### ISSUE THREAD

**Issue by mikep-ll** [electron/electron#8426]
* Electron version: 1.4.14
* Operating system: OS X 10.11.6

I first noticed this in 1.4.12, but it has likely been around for a while. To reproduce:

1. Make the app fullscreen. You can do this when creating the window with fullScreen:true or just by maximizing the app to make if full screen. 
2. Put the app in kiosk mode by calling setKiosk(true). 
3. Move the cursor down to the bottom of the screen. 

Notice the dock will display allowing us to click on another application and break out of kiosk. What I've noticed is that this behavior is not there if we go to kiosk mode while **not** in full screen.

**Comment by leethomas** [comment]
As a workaround, you can call 
```js
setAlwaysOnTop(true, 'floating')
```

**Comment by zcbenz** [comment]
We have seen similar problems (https://github.com/electron/electron/issues/1054) in the past, but we have on clue why it is happening, I'm closing this since it is something we are not able to fix (probably a bug of macOS), and there is a workaround to it.
