### ISSUE TITLE
Option+F2 breaks kiosk mode on OSX

### ISSUE THREAD

**Issue by mikep-ll** [electron/electron#8427]
* Electron version: 1.4.14
* Operating system: 10.11.6

Hitting Option+F2 brings up display preferences and breaks us out of kiosk mode. This appears to only happen if we are in full screen when going in to kiosk mode. The easiest way to reproduce is to use fullScreen:true and kiosk:true when creating the window. 

The other F keys are also an issue in this scenario. Something odd is happening with full screen and kiosk.

**Comment by sofianguy** [comment]
Thanks for contributing!

We are no longer releasing bug fixes for versions of Electron older than 1.6x. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.

**Comment by nicolas-b12** [comment]
Hi @sofianguy. Could you reopen this issue ? I got this issue with Electron 10.1.3 and OSX 10.15.5

**Comment by nicolas-b12** [comment]
```
const { app, BrowserWindow, ipcMain } = require('electron')
ipcMain.on('close-me', (evt, arg) => {
  app.quit()
})

function createWindow() {
    // Cree la fenetre du navigateur.
    const win = new BrowserWindow({
        width: 800,
        height: 600,
        kiosk: true,
        webPreferences: {
            nodeIntegration: true
        }
    })

    // et charger le fichier index.html de l'application.
    win.loadFile('index.html')
}

app.whenReady().then(createWindow)

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit()
    }
})

app.on('activate', () => {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (win === null) {
        createWindow()
    }
})
```
Code used to produce the kioskWindow
