### ISSUE TITLE
Cannot find module 'seek-bzip'

### ISSUE THREAD

**Issue by 332065255** [electron/electron#8429]
* Electron version:1.4.14
* Operating system: MACOS sierra 10.12.2

**Comment by 332065255** [comment]
![ad1bc45c-db68-432f-bb54-2010e9f143e7](https://cloud.githubusercontent.com/assets/4002926/22052484/7f54fcde-dd85-11e6-8f93-c3cef0bcb23a.png)
![dc64c06d-2248-4572-949a-1cd1a1cf8f97](https://cloud.githubusercontent.com/assets/4002926/22052490/86a91d26-dd85-11e6-985e-bdf2fae6681c.png)

**Comment by 332065255** [comment]
![image](https://cloud.githubusercontent.com/assets/4002926/22052520/9e8b0616-dd85-11e6-891e-ba3b779b9df8.png)

**Comment by MarshallOfSound** [comment]
Remove `decompress` and `decompress-unzip` from the "devDependencies" section of your package.json file

**Comment by 332065255** [comment]
@MarshallOfSound Just tried, but can't

**Comment by 332065255** [comment]
@MarshallOfSound rm -rf dist && ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/" electron-packager . h5Client --platform= darwin  --arch=all --electron-version=1.4.14  --out=dist --overwrite=true --ignore=node_modules/electron --ignore=node_modules/electron-* --ignore=node_modules/.bin --ignore=.git --ignore=dist --ignore=zip/* --prune

**Comment by MarshallOfSound** [comment]
There's your issue

`--ignore=zip/*`

You are ignoring all folders that end with the word "zip".  So the folder that contains "seek-bzip" will be ignored when packaging.  You need to apply a finer ignore pattern.

**Comment by 332065255** [comment]
@MarshallOfSound Thank you, I got it, thank you very much
