### ISSUE TITLE
Latest version published on NPM should (probably) be "1.4.14", but it is "1.4.13"

### ISSUE THREAD

**Issue by Zamiell** [electron/electron#8434]
For reference, see the NPM page for the electron package:
https://www.npmjs.com/package/electron

On the right hand side of the page, we can see that "1.4.13 is the latest of 35 releases".

However, the Electron website, the Electron GitHub releases, and strangely, the image at the top of the aforementioned NPM webpage all mention that the latest version of "1.4.14". Furthermore, this release was 8 days ago, which seems long enough to indicate that it might not be some type of caching issue.

Was there a bug during the release cycle where a new version was uploaded to GitHub but skipped updating NPM?

**Comment by kevinsawicki** [comment]
This looks like an issue with the npm site.

Run `npm view electron | grep latest` shows the following:

```
'dist-tags': { latest: '1.4.14' },
```

So 1.4.14 is the latest published to npm and you can confirm this by running `npm install --save electron@latest`.

/cc @zeke any idea why this happens?

**Comment by zeke** [comment]
Yeah I noticed this last week. It's the npm website, not the registry. The website uses a follower of the real registry and it must have fallen out of sync for some reason. This is not common, however.

Maybe @bcoe or @ceejbot would know what's up.

**Comment by bcoe** [comment]
@Zamiell @kevinsawicki @zeke sorry about that, we have a follower for meta-information that has been falling on its face occasionally; we're already in the process of replacing that part of the system -- I'm excited about this, it will make package pages faster and we'll stop having little hiccups like this.

**Comment by kevinsawicki** [comment]
@bcoe Thanks for the details 👍 

Closing this out.
