### ISSUE TITLE
Crash Reporter + WebView

### ISSUE THREAD

**Issue by anaisbetts** [electron/electron#844]
How does `crash-reporter` work with the WebView tag? Should we invoke `crash-reporter` in the `preload` script?

**Comment by ragnerok** [comment]
Hi, if this is still open I would like to work on this, any tips on how to get started ?
Thanks !

**Comment by rajatsingla28** [comment]
Hi @zcbenz, could you please explain what do mean by hosting page?

**Comment by miniak** [comment]
The crashReporter no longer needs to be started in the renderer process separately.
