### ISSUE TITLE
Links for `KeyboardEvent` broken on Electron Documentation website

### ISSUE THREAD

**Issue by jacobq** [electron/electron#8440]
* Electron version: 1.4.14
* Operating system: N/A (website issue)

On the [Electron documentation website](http://electron.atom.io/docs/all/) the links to "KeyboardEvent" are broken (e.g. http://electron.atom.io/docs/api/keyboardevent returns 404). For example, when I look at the ['before-input-event' event'](http://electron.atom.io/docs/all/#event-before-input-event) the description of the `input` object properties have broken links like this.

**Comment by kevinsawicki** [comment]
I believe this was fixed by https://github.com/electron/electron/pull/8400, the docs will be rebuilt when 1.4.15 is published.
