### ISSUE TITLE
what do autoupdater checkForUpdate need?

### ISSUE THREAD

**Issue by CarlosRen** [electron/electron#8443]
### Operations 

* setup a package server by nodejs , visit url `http://localhost:3000/updates/latest?v=1.0.1&platform=win32` can get json `{"url":"http://localhost:3000/releases/1.0.3/win32/app.zip"}` back
* build a install.exe by `npm run dist` (nsis)
* install app on computer and open it 

### Expection:

* checkForUpdate get the last package url back 

### Actual:

![image](https://cloud.githubusercontent.com/assets/6012322/22095548/9218a110-de50-11e6-8078-9d491782d83e.png)

what do `autoupdater.checkForUpdate` need?  
what i am doing wrong ?

**Comment by MarshallOfSound** [comment]
On windows `checkForUpdates` only works in a packaged environment where `Update.exe` is packaged in the correct location with your application.

`electron-winstaller` sets up this Squirrel installer for you. In general testing auto update in a non-packaged state is very difficult on all platforms 👍

**Comment by MarshallOfSound** [comment]
![example](https://cloud.githubusercontent.com/assets/6634592/22099749/b64fa1b6-de80-11e6-920a-6553546d55e6.PNG)

This is what a packaged / installed Squirrel app looks like on windows

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
