### ISSUE TITLE
cannot drag file to Finder/Desktop

### ISSUE THREAD

**Issue by jsnelgro** [electron/electron#8445]
* Electron version: v1.4.14
* Operating system: OSX 10.11.6

### Expected behavior

Given a filepath, `ipcMain.on 'ondragstart'` should be able to copy the file at the given path from one location in the filesystem to another (the drop location).
### Actual behavior

Dragging a draggable item from an electron window, and supplying `ipcMain.on 'ondragstart'` with a path does not copy the file from the given path to the drop location. (for example, dragging an item to the desktop)

### How to reproduce

index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>dragging and dropping</title>
    <style>
      #dragitem {
        background: hsl(0, 50%, 50%);
        display: inline-block;
        color: white;
        padding: 15px;
      }
    </style>
  </head>
  <body>
    <div id="dragitem" draggable="true">
      drag me to the desktop!
    </div>
    <script>
      const {ipcRenderer} = require('electron')
      let dragitem = document.getElementById('dragitem')

      dragitem.addEventListener('dragstart', (ev) => {
        ev.dataTransfer.effectAllowed = 'copy'
        ev.preventDefault()
        ipcRenderer.send('ondragstart', `${__dirname}/abc.txt`)
      })
    </script>
  </body>
</html>
```

main.js
```js
const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow
const ipcMain = electron.ipcMain

ipcMain.on('ondragstart', (ev, path) => {
  ev.sender.startDrag({file: path, icon: 'dragicon.png'})
})

let mainWindow
function createWindow () {
  mainWindow = new BrowserWindow({width: 800, height: 600})
  let indexPath = `file://${__dirname}/index.html`
  mainWindow.loadURL(indexPath)
  mainWindow.webContents.openDevTools()
  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', createWindow)
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})
```

abc.txt
```txt
hello world!
```

Maybe I'm misunderstanding how the API works? Any help is much appreciated!

**Comment by kevinsawicki** [comment]
> ev.sender.startDrag({file: path, icon: 'dragicon.png'})

Have you tried giving a full path to an icon that exists?

**Comment by jsnelgro** [comment]
@kevinsawicki yes, I've tried writing the file to tmp and giving it a full path like so:
```javascript
ipcMain.on('ondragstart', (ev, name, path) => {
  let tmppath = `${os.tmpdir()}/${name}`
  fs.writeFileSync(tmppath, fs.readFileSync(path))
  ev.sender.startDrag({file: tmppath, icon: 'dragicon.png'})
})
```
still no success. 🙁

**Comment by kevinsawicki** [comment]
@jsnelgro what about using a full path that exists for the `icon:` option currently set to `dragicon.png`?

**Comment by jsnelgro** [comment]
hey @kevinsawicki, just tried icon with a full path. Still nothing. And it looks like the icon path is valid since the icon appears while dragging. Maybe the issue has something to do with the renderer process `dragstart` event's `dataTransfer` object? It looks like both the `items` and `files` properties (array-like) are empty. I tried hardcoding a new `File` object in the `dragstart` event and adding it to the `items` list, but still no luck.

**Comment by kevinsawicki** [comment]
@jsnelgro just so I understand, you are unable to drag a file out of Electron and onto the desktop?

This is what I'm seeing using your sample app, I am able to drag it out of the window and onto the desktop.

![dnd](https://cloud.githubusercontent.com/assets/671378/22315691/2ffd16d8-e31d-11e6-9d9a-d2f0a190b3e0.gif)

**Comment by jsnelgro** [comment]
@kevinsawicki mysterious... just tested the sample app again and it seems to be working correctly now with no changes. Guess we can close this for now. Thanks for looking into the issue!

**Comment by mafar** [comment]
@kevinsawicki 
I have a bit different situation here

**Comment by huzunjie** [comment]
> * Electron version: v1.4.14
> * Operating system: OSX 10.11.6
> 
> ### Expected behavior
> Given a filepath, `ipcMain.on 'ondragstart'` should be able to copy the file at the given path from one location in the filesystem to another (the drop location).
> 
> ### Actual behavior
> Dragging a draggable item from an electron window, and supplying `ipcMain.on 'ondragstart'` with a path does not copy the file from the given path to the drop location. (for example, dragging an item to the desktop)
> 
> ### How to reproduce
> index.html
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta charset="utf-8">
>     <title>dragging and dropping</title>
>     <style>
>       #dragitem {
>         background: hsl(0, 50%, 50%);
>         display: inline-block;
>         color: white;
>         padding: 15px;
>       }
>     </style>
>   </head>
>   <body>
>     <div id="dragitem" draggable="true">
>       drag me to the desktop!
>     </div>
>     <script>
>       const {ipcRenderer} = require('electron')
>       let dragitem = document.getElementById('dragitem')
> 
>       dragitem.addEventListener('dragstart', (ev) => {
>         ev.dataTransfer.effectAllowed = 'copy'
>         ev.preventDefault()
>         ipcRenderer.send('ondragstart', `${__dirname}/abc.txt`)
>       })
>     </script>
>   </body>
> </html>
> ```
> 
> main.js
> 
> ```js
> const electron = require('electron')
> const app = electron.app
> const BrowserWindow = electron.BrowserWindow
> const ipcMain = electron.ipcMain
> 
> ipcMain.on('ondragstart', (ev, path) => {
>   ev.sender.startDrag({file: path, icon: 'dragicon.png'})
> })
> 
> let mainWindow
> function createWindow () {
>   mainWindow = new BrowserWindow({width: 800, height: 600})
>   let indexPath = `file://${__dirname}/index.html`
>   mainWindow.loadURL(indexPath)
>   mainWindow.webContents.openDevTools()
>   mainWindow.on('closed', function () {
>     mainWindow = null
>   })
> }
> 
> app.on('ready', createWindow)
> app.on('window-all-closed', function () {
>   if (process.platform !== 'darwin') {
>     app.quit()
>   }
> })
> app.on('activate', function () {
>   if (mainWindow === null) {
>     createWindow()
>   }
> })
> ```
> 
> abc.txt
> 
> ```
> hello world!
> ```
> 
> Maybe I'm misunderstanding how the API works? Any help is much appreciated!

I found that you can't drag files to the Finder/Desktop in development mode, but you can drag files to the Finder/Desktop after compilation.

**Comment by jkpet** [comment]
> 

Lool this needs to be documented. Thanks for the info!

**Comment by jkpet** [comment]
> > * Electron version: v1.4.14
> > * Operating system: OSX 10.11.6
> > 
> > ### Expected behavior
> > Given a filepath, `ipcMain.on 'ondragstart'` should be able to copy the file at the given path from one location in the filesystem to another (the drop location).
> > ### Actual behavior
> > Dragging a draggable item from an electron window, and supplying `ipcMain.on 'ondragstart'` with a path does not copy the file from the given path to the drop location. (for example, dragging an item to the desktop)
> > ### How to reproduce
> > index.html
> > ```
> > <!DOCTYPE html>
> > <html>
> >   <head>
> >     <meta charset="utf-8">
> >     <title>dragging and dropping</title>
> >     <style>
> >       #dragitem {
> >         background: hsl(0, 50%, 50%);
> >         display: inline-block;
> >         color: white;
> >         padding: 15px;
> >       }
> >     </style>
> >   </head>
> >   <body>
> >     <div id="dragitem" draggable="true">
> >       drag me to the desktop!
> >     </div>
> >     <script>
> >       const {ipcRenderer} = require('electron')
> >       let dragitem = document.getElementById('dragitem')
> > 
> >       dragitem.addEventListener('dragstart', (ev) => {
> >         ev.dataTransfer.effectAllowed = 'copy'
> >         ev.preventDefault()
> >         ipcRenderer.send('ondragstart', `${__dirname}/abc.txt`)
> >       })
> >     </script>
> >   </body>
> > </html>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > main.js
> > ```js
> > const electron = require('electron')
> > const app = electron.app
> > const BrowserWindow = electron.BrowserWindow
> > const ipcMain = electron.ipcMain
> > 
> > ipcMain.on('ondragstart', (ev, path) => {
> >   ev.sender.startDrag({file: path, icon: 'dragicon.png'})
> > })
> > 
> > let mainWindow
> > function createWindow () {
> >   mainWindow = new BrowserWindow({width: 800, height: 600})
> >   let indexPath = `file://${__dirname}/index.html`
> >   mainWindow.loadURL(indexPath)
> >   mainWindow.webContents.openDevTools()
> >   mainWindow.on('closed', function () {
> >     mainWindow = null
> >   })
> > }
> > 
> > app.on('ready', createWindow)
> > app.on('window-all-closed', function () {
> >   if (process.platform !== 'darwin') {
> >     app.quit()
> >   }
> > })
> > app.on('activate', function () {
> >   if (mainWindow === null) {
> >     createWindow()
> >   }
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > abc.txt
> > ```
> > hello world!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe I'm misunderstanding how the API works? Any help is much appreciated!
> 
> I found that you can't drag files to the Finder/Desktop in development mode, but you can drag files to the Finder/Desktop after compilation.

Looool this needs to be documented. Thanks for the info!
