### ISSUE TITLE
Build App with electron and emberjs

### ISSUE THREAD

**Issue by dmtask** [electron/electron#8447]
I became the following error, when i start my desktop app with my ember app. JQuery and Bootstrap are in `ember-cli-build.js` and JQuery is the first import. I think it is a Problem with the electron modules system, but i have no idea we can fix it. I found this code `delete mainWindow.module;`, but when i insert this in my `main.js` in electron app i give the same error.

Console error:
<img width="1430" alt="7ynjt" src="https://cloud.githubusercontent.com/assets/17166931/22112499/7946c1cc-de63-11e6-80a1-12040c334615.png">

I use the follow versions (`package.json`) of electron:
```
"electron-window-manager": "^1.0.4",
"electron-window-state": "^4.0.1"
```

**Comment by kevinsawicki** [comment]
See `window.$`/`window.jQuery` as a global and it should work then.

See https://github.com/electron/electron/issues/254 for more details.

**Comment by dmtask** [comment]
Thank you.
