### ISSUE TITLE
Urls exceeding character limit of loadURL will crash the application

### ISSUE THREAD

**Issue by drumboog** [electron/electron#8448]
* Electron version: v1.4.14
* Operating system: Windows 7 Enterprise

### Expected behavior

BrowserWindow.loadURL should allow 'data:***' urls.

### Actual behavior

When certain content is passed to loadURL, the application crashes.

### How to reproduce

1. Download and execute the sample app: [app.zip](https://github.com/electron/electron/files/717283/app.zip)
2. Click the "Open from file" link.  The application opens a new windows as expected.
3. Click the "Open from content" link.  A new window is opened, then the application becomes unresponsive and crashes.

**Comment by deepak1556** [comment]
Same as https://github.com/electron/electron/issues/8317 , you can use blob URI instead. But we should not crash the application, instead warn users when the character limit is reached.

**Comment by drumboog** [comment]
The Blob works great... thanks!
