### ISSUE TITLE
Click events pass through to DOM on unfocused window when titleBarStyle is 'hidden-inset'

### ISSUE THREAD

**Issue by samiskin** [electron/electron#8450]
* Electron version: 1.4.15
* Operating system: macOS 10.12.2

### Expected behavior

When the window is unfocused, clicking anywhere on the window should simply focus it, with mouse events not being sent to the renderer

### Actual behavior

When `titleBarStyle: 'hidden-inset'` is set, even when the window is unfocused, clicking anywhere above the bottom of the traffic lights will send a click event down to the browser.  This does not happen for `titleBarStyle: 'hidden'`.

##### main.js
```js
const electron = require('electron');
const BrowserWindow = electron.BrowserWindow;

electron.app.on('ready', () => {
  let mainWindow = new BrowserWindow({titleBarStyle: 'hidden-inset'});
  mainWindow.loadURL(`file://${__dirname}/index.html`);
});
```
##### index.html
```html
<!DOCTYPE html>
<html>
  <body>
    <div style="height: 600px" onclick="alert('Click!')">
  </body>
</html>
```

Unfocus the window, then click inside it somewhere near the middle, you'll see nothing happen other than the window focusing.

Unfocus the window then click near the very top, above the bottom of the traffic lights, you'll see an alert pop up.

**Comment by poiru** [comment]
Thanks for tbhe detailed report! Merging this into #5723.
