### ISSUE TITLE
webview open new webview with opener support

### ISSUE THREAD

**Issue by cyvirus** [electron/electron#8453]
With chrome app webview tags I can set opener for new window:

```
webview.addEventListener('newwindow', function(e) {
  var newWebview = document.createElement('webview');
  document.body.appendChild(newWebview);
  e.window.attach(newWebview);
});
```

How I can do same thing with webview tab of electronjs?
This feature is very useful, it help to create web browser with UI based html.
Help me!
Thanks.

**Comment by aimergenge** [comment]
Did you solved this?
