### ISSUE TITLE
Tray mouse over (at least in mac os)

### ISSUE THREAD

**Issue by pupca** [electron/electron#8458]
I would like to have an event fired when an user puts mouseover and mouseout on the tray icon created via http://electron.atom.io/docs/api/tray/

Have you ever thought of something like that? Support (at least in MacOs) should be quite straight forward.

**Comment by groundwater** [comment]
Hi @pupca, this sounds interesting. It's more likely to get prioritized if we have a bit more information. I think I understand, but perhaps you could describe your use case, and imagined API. Any supporting reference docs from MacOS would be worth linking if you have them.

**Comment by zcbenz** [comment]
I'm merging this to https://github.com/electron/electron/issues/7616.
