### ISSUE TITLE
Modifying Menu object after setMenu can produce unregistered/dangling accelerators

### ISSUE THREAD

**Issue by rprichard** [electron/electron#846]
On Windows and Linux (but not OS X), I can modify a Menu object after passing it to a window's setMenu method, and the modified menu appears the next time the user opens the menu.  (It's not 100% clear to me that this is expected to work, because on OS X, modifying the menu passed to Menu.setApplicationMenu has no effect, but it *seems* to work.)

However, the menu accelerators are only registered (`NativeWindowViews::RegisterAccelerators`) when setMenu is called (`NativeWindowViews::SetMenu`).  Modifying the menu accelerators after `setMenu` has two problems:
 - The new accelerators aren't registered.  Typing them has no effect.
 - The old accelerators can point to non-existent menu items.  Typing them crashes atom-shell.

Test case:

package.json:

    {
        "name": "AtomMenuBug",
        "version": "0.1.0",
        "main": "main.js"
    }

main.js:

    var app = require("app");
    var Menu = require("menu");
    var MenuItem = require("menu-item");
    var BrowserWindow = require("browser-window");

    var bw = null;

    app.on("ready", function() {
        bw = new BrowserWindow({ width: 300, height: 300 });
        bw.loadUrl("about:blank");

        var fileMenu = new Menu();
        fileMenu.append(new MenuItem({ label: "Dummy1", accelerator: "Ctrl+O", click: function() {
            console.log("Dummy1");
            fileMenu.clear();
            editMenu.append(new MenuItem({ label: "Dummy2", accelerator: "Ctrl+P", click: function() {
                console.log("Dummy2");
            }}));
        }}));

        var editMenu = new Menu();
        var menubar = new Menu();
        menubar.append(new MenuItem({ label: "File", submenu: fileMenu }));
        menubar.append(new MenuItem({ label: "Edit", submenu: editMenu }));
        bw.setMenu(menubar);
    });

Steps:
1. Type Ctrl+O to clear the File Menu and populate the Edit menu.
2. Open the Edit menu and observe that "Edit -> Dummy2" is visible and has a documented Ctrl+P shortcut.
3. Type Ctrl+P.  Nothing happens.  I expected Dummy2 to appear in the console.
4. Type Ctrl+O again.  The program crashes:

    [28347:1120/210937:FATAL:simple_menu_model.cc(435)] Check failed: static_cast<size_t>(index) < items_.size() (0 vs. 0)

I'd like it if atom-shell either updated the accelerators when I modified the menu, or alternatively, ignored all modifications to the Menu object.  In any case, I shouldn't be able to crash atom-shell like this.

I've reproduced this problem on Windows 7 and Xubuntu 14.04.

**Comment by zcbenz** [comment]
I'm closing this since we don't support changing menu object after calling `setMenu`, the behavior is undefined if user does that.

**Comment by renandecarlo** [comment]
My workaround was to get mouse cursor position when the user clicks on the menu, and then show it at the coordinates after recreating it with `Menu.buildFromTemplate()` or the `Menu()` object. 
Basically like that:

```
let menuCoordinates = {};
contextMenu.on('menu-will-show', () => {
   menuCoordinates = require('electron').screen.getCursorScreenPoint();
});
```

... then rebuild it with `Menu.buildFromTemplate()` or new `Menu()`
... then reopen it at the coordinates we got:

```
contextMenu.popup({ x: menuCoordinates .x, y: menuCoordinates .y });
```

It should work with Tray too.
