### ISSUE TITLE
Question: I want to develop cross-platform desktop apps

### ISSUE THREAD

**Issue by CashCode** [electron/electron#8460]
Hey! I'm new to electron. I know only php and js.
My aim is to make cross-platfоrm desktоp аpp, but I need multiсurl support (or an alternative).
What should I use? Electron with python or electron with node.js is it possible to use multi-threading queries? Any way to hide code?
Thanks.

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, please post your question in the [forum](http://discuss.atom.io/c/electron), [Slack](http://atom-slack.herokuapp.com/), or one of the other [community](https://github.com/electron/electron#community) support channels.
