### ISSUE TITLE
Force Refresh

### ISSUE THREAD

**Issue by ev1stensberg** [electron/electron#8465]
Hi! Sorry for polluting the issue tracker. I'm used to doing (on Mac), `Command + Shift + R` to give the page a full refresh rather than partial. Is this something that is achievable at Electron's end?

**Comment by yopbeast** [comment]
@ev1stensberg if you want to refresh the view programmatically has to use maybe window.location.refresh

**Comment by ev1stensberg** [comment]
Not the point. Consistency with chrome is the main intent here.

**Comment by kevinsawicki** [comment]
@ev1stensberg have you tried using `webContents.reloadIgnoringCache()`?

**Comment by ev1stensberg** [comment]
Sorry if I've formed this request wrong, but the main intent was to provide consistency in accordance to forced refresh in Chrome. Say if this were default, as refresh is in Electron, I'd have the same option as a refresh, but with `webContents.reloadIgnoringCache()`. I'd be happy to elaborate some more.

**Comment by ev1stensberg** [comment]
Woah, that was fast! Thanks!
