### ISSUE TITLE
app.getPath('pepperFlashSystemPlugin'); throws exception on windows

### ISSUE THREAD

**Issue by sgehrman** [electron/electron#8469]
app.getPath('pepperFlashSystemPlugin'); throws exception on windows

Not usable on windows, please fix.

**Comment by enlight** [comment]
There's a template for new issues, when you open a new issue please fill it out the template instead of just deleting it, that way people might actually be able to help you.

Which version of Electron are you using and which version of Windows? What is the actual error?

**Comment by kevinsawicki** [comment]
@sgehrman do you have the stack trace available?

**Comment by kevinsawicki** [comment]
`app.getPath` throws when the path requested is unavailable, this should be guarded against when used.

On Windows, this method will throw when called with `pepperFlashSystemPlugin ` unless the `SOFTWARE\Macromedia\FlashPlayerPepper` path in the registry has a `PlayerPath` value.

Closing this out.
