### ISSUE TITLE
BrowserWindow and other classes don't fully implement EventEmitter

### ISSUE THREAD

**Issue by marshmellow1328** [electron/electron#8470]
* Electron version: 1.4.8
* @types/electron version: 1.4.31
* Operating system: Linux

### Expected behavior
BrowserWindow, Menu, ClientRequest, Session, and Tray classes should implement all the EventEmitter methods or not claim to be an EventEmitter.

### Actual behavior
They're missing methods like addListener, emit, getMaxListeners, listenerCount, listeners, once, removeAllListeners, removeListener, setMaxListeners.

### How to reproduce
I didn't setup a demo repo, but I think it's pretty easy to recreate. Let me know if you need one.

### Other Comments
I'm willing to attempt a PR for this, but want to confirm direction before I do. Are these classes really meant to be an EventEmitter and should implement all these methods? Or are they just following the pattern, but don't have a desire to implement every method? I first noticed this from using the @types/electron package which gives errors because of this issue. Even if not using TypeScript, the docs could be confusing as it claims the classes are EventEmitters.

**Comment by kevinsawicki** [comment]
>  Are these classes really meant to be an EventEmitter and should implement all these methods? Or are they just following the pattern, but don't have a desire to implement every method?

They should inherit directly from node's `EventEmitter`.

> I didn't setup a demo repo, but I think it's pretty easy to recreate. Let me know if you need one.

I'm having trouble reproducing this with `BrowserWindow` for example so can you provide a demo repo?

The prototype is set for this class here: https://github.com/electron/electron/blob/034230e2ae8c8ea5e52e955aa25400be64432d75/lib/browser/api/browser-window.js#L8

**Comment by marshmellow1328** [comment]
After looking at it more, I'm pretty sure this is a disconnect in @types versions. I've been using @types/electron v1.4.31 and @types/node v4.0.30. In @types/node v4.0.30, NodeJS.EventEmitter is an interface, not a class. After changing to @types/node v6.0.61, NodeJS.EventEmitter is a class. Do you know where I should be asking questions related to @types/electron, how it relates to @types/node, and the version of node I'm running? I tried in the electron slack channel, but didn't get any help there.

**Comment by KagamiChan** [comment]
I think #4875 may help you

**Comment by kevinsawicki** [comment]
> Do you know where I should be asking questions related to @types/electron, how it relates to @types/node, and the version of node I'm running?

You might also want to check the issue tracker on https://github.com/DefinitelyTyped/DefinitelyTyped/issues

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10977 looks similar.

Closing this out here.
