### ISSUE TITLE
Why do some translation documents have more functions than English documents?

### ISSUE THREAD

**Issue by amhoho** [electron/electron#8473]
Many documents have this situation
E.g:[docs/session.md](https://github.com/electron/electron/blob/master/docs/api/session.md#session) and [docs-translations/zh-CN/api/session.md](https://github.com/electron/electron/blob/master/docs-translations/zh-CN/api/session.md)

Why these functions do not exist in the English version of the document:
#### ses.cookies.set(details, callback)
....
#### `ses.webRequest.onErrorOccurred([filter, ]listener)`

**Comment by MarshallOfSound** [comment]
The translations are normally behind the english docs as they are translated manually by community members when they get the chance to do so in their free time.  The english docs are always kept up to date / are the most accurate.

I believe the methods to which you refer were extracted to their own docs set https://github.com/electron/electron/blob/master/docs/api/web-request.md
