### ISSUE TITLE
spawn() in combination with app.asar and app.asar.unpacked on Windows.. Doesn't look into app.asar.unpacked?

### ISSUE THREAD

**Issue by aredfox** [electron/electron#8476]
* Electron version: 1.4.14
* Operating system: Windows 7 SP1
* Electron builder: 11.2.5

### Expected behavior

path.join(__dirname) in combination with spawn() should look into app.asar and app.asar.unpacked
e.g.: `childProcess.spawn(path.join(__dirname, "bin", "nircmd.exe"), ["savescreenshot", options.output]);`
when not found in app.asar, it should default to look into app.asar.unpacked

### Actual behavior

it only looks in app.asar
e.g.: `childProcess.spawn(path.join(__dirname, "bin", "nircmd.exe"), ["savescreenshot", options.output]);`
it errors out that it couldn't find this file "nircmd.exe" in app.asar

### How to reproduce

See my issue on https://github.com/johnvmt/node-desktop-screenshot/issues/7 where to code is explained.
**Short story:**
When packaging for windows target with electron 1.4.14 and electron-builder 11.2.5 the module couldn't be found, more specifically it couldn't find nircmd.exe.

I think path.join should normally look in app.asar.unpacked, but apparantly on Windows it doesn't?

**Solution/Workaround:**
I had to change the line in win32.js from
`var nircmd = childProcess.spawn(path.join(__dirname, "bin", "nircmd.exe"), ["savescreenshot", options.output]);`
to
`var nircmd = childProcess.spawn(path.join(__dirname.replace('app.asar', 'app.asar.unpacked'), "bin", "nircmd.exe"), ["savescreenshot", options.output]);`

**Comment by aredfox** [comment]
**Other workaround**
Added the library "hazardous" to fix this issue now in my windows-specific branches, but I hope this will be fixed in node/electron code base?

**Comment by groundwater** [comment]
Just to chime in, even if this should be filed in https://github.com/electron/asar I think we should track it here until it's fixed.

**Comment by zcbenz** [comment]
I'm closing this because it is a limitation [explicitly documented](http://electron.atom.io/docs/tutorial/application-packaging/#executing-binaries-inside-asar-archive). You can find more background at https://github.com/electron/electron/issues/3512.
