### ISSUE TITLE
Feature Request: Taskbar progress bar (Windows &  Linux)

### ISSUE THREAD

**Issue by PragmaticEd** [electron/electron#8477]
Is it possible to show percent statuses of tasks in Windows Taskbar and Linux unity?
I attached images,  of what I mean. 

### Linux:
![handbrake-fixed](https://cloud.githubusercontent.com/assets/19263525/22203438/c4f18c14-e175-11e6-993a-878d65bcba39.png)

### Windows:
![progressbar3](https://cloud.githubusercontent.com/assets/19263525/22203439/c4f2766a-e175-11e6-9f4b-30d3d0308b33.png)

**Comment by MarshallOfSound** [comment]
This API has already been implemented.  See

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetprogressbarprogress-options

**Comment by PragmaticEd** [comment]
@MarshallOfSound thanks.
