### ISSUE TITLE
Text Rendering Issue

### ISSUE THREAD

**Issue by Palabola** [electron/electron#8480]
* Electron version: Any after 1.12.1
* Operating system: Win 7(64bit) ,Windows 10(64 bit)

### Expected behavior

- Smooth rendered fonts.

### Actual behavior

[](http://i.imgur.com/Nf5Fw1r.jpg)

### How to reproduce

After first run the application got Fuzzy badly rendered fonts, then I press Crtl + F5 and texts become readable, any other reaload handled by the Application keep the Fuzzy fonts!

**Comment by Palabola** [comment]
+ 1 Is there any option to Force reload the application with same result like press Crtl+F5?

**Comment by kevinsawicki** [comment]
@Palabola can you try and reproduce this with Electron 1.6.0 which upgraded to Chrome 56 to see if  the fonts are still fuzzy?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
