### ISSUE TITLE
Two webview entries in the documentation

### ISSUE THREAD

**Issue by dkfiresky** [electron/electron#8482]
### Expected behavior
Only one `webview` link should be displayed.

### Actual behavior
Two links with different anchors link to the `webview` page.

http://electron.atom.io/docs/api/web-view-tag/
http://electron.atom.io/docs/api/webview-tag/

### How to reproduce
Go to http://electron.atom.io/docs/ and scroll to `Render Process`.

<img width="304" alt="screenshot 2017-01-23 at 21 31 00" src="https://cloud.githubusercontent.com/assets/2175645/22219469/829d89b0-e1b3-11e6-826a-545b7b02d5cd.png">

**Comment by kevinsawicki** [comment]
Thanks, this is being tracked over at https://github.com/electron/electron.atom.io/issues/658, please subscribe to that issue for updates.

**Comment by dkfiresky** [comment]
@kevinsawicki thanks 👍
