### ISSUE TITLE
BrowserWindow 的frame 为 false的时候isMaximized始终返回false

### ISSUE THREAD

**Issue by seekwe** [electron/electron#8488]

**Comment by spartucus** [comment]
兄弟得说英语啊。

I think The Title is :

> isMaximized() always returns false when BrowserWindows' frame is false.

**Comment by kevinsawicki** [comment]
@seekwe what version of Electron are you using and on what platform?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available, I was unable to reproduce this using 1.6.0 on macOS.

**Comment by seekwe** [comment]
很抱歉,忘了说英语了,谢谢@spartucus ,
测试环境:win10 x64,如果frame 不等于false则没问题
