### ISSUE TITLE
Printing only selected pages fails on Windows

### ISSUE THREAD

**Issue by ci42** [electron/electron#8489]
* Electron version: 1.4.13
* Operating system: Windows 7 - fails, Windows 8.1 - fails, Windows 10 - works only at the first try, subsequent tries fail, OS X 10.11 - works, Ubuntu 16.04 - works

### Expected behavior
When printing selected pages of a web page with electron the selected pages will be printed.

### Actual behavior
The print job hangs in the print job queue until the electron app is closed.

### How to reproduce
Open a web page in electron which spreads over several pages when printed. Use `window.print()` or `webContents.print([options])` to print the page. Select some pages (e.g. `2,4,6-8` ) in the `Page Range` field inside the system print dialog. Press `Print`.

**Comment by rreimann** [comment]
I'm experiencing the same issue with the current Electron version 1.4.15 on Windows 10 while using the electron quickstart:

* setup the Quickstart as described [here](http://electron.atom.io/docs/tutorial/quick-start/#try-this-example)
* before running the app paste a lengthy text into `index.html`
* while running the app call the print dialog via dev tools console: `window.print()`
* select only a subset of the available pages and print
  * works only on first attempt
  * fails on all subsequent attempts

**Comment by rreimann** [comment]
The issue is still present in the current [1.6.0 beta release](https://github.com/electron/electron/releases/tag/v1.6.0).

**Comment by MarshallOfSound** [comment]
I tested on both `1.4.13` and `1.6.0` and I can't reproduce this issue.

I tried both super long webpages and simply duplicating the default Electron apps content 100 times and printing that.  Both cases successfully printed on Windows 10 3 times in a row.  I quickly tried a Windows 7 VM and it appeared to work as well (could only print to PDF in the VM).

Can you possibly provide an exact HTML page that causes this issue or provide exact details about your Printer setup.  Not sure how much we can actually look into this without a setup that reproduces the issue.

**Comment by ci42** [comment]
@MarshallOfSound 
Thanks for looking into this.

Did you print all pages or only a subset? The issue only occurs when you try to print only a subset of all pages, e.g. `2,4,7`.

![screen shot 2017-02-27 at 08 19 15](https://cloud.githubusercontent.com/assets/1443089/23352094/86d1a264-fcc5-11e6-8513-5d78d9e400c5.png)

**Comment by MarshallOfSound** [comment]
I tried `1-3, 4` and `1, 4` and `4` to test allscenarios

**Comment by ci42** [comment]
@MarshallOfSound 
Ok, I'll try to provide a minimal test application.

**Comment by ci42** [comment]
@MarshallOfSound 
I made a minimal test application: https://github.com/ci42/electron-issue-8489-sample-app

Detailed instructions how to reproduce the issue:

1. clone the repo
![screen shot 2017-02-27 at 10 08 25](https://cloud.githubusercontent.com/assets/1443089/23355437/f331a5a2-fcd5-11e6-88fc-f28a85539910.png)
 
2. install electron ( `npm install`)
![screen shot 2017-02-27 at 10 11 27](https://cloud.githubusercontent.com/assets/1443089/23355465/11b7ce70-fcd6-11e6-9267-f3c9fc0f6c67.png)

3. start the application (`npm start`)
![screen shot 2017-02-27 at 10 12 12](https://cloud.githubusercontent.com/assets/1443089/23355476/260743c4-fcd6-11e6-8427-2b019205d309.png)

4. scroll to the bottom of the page and press the `print page` button
![screen shot 2017-02-27 at 10 12 38](https://cloud.githubusercontent.com/assets/1443089/23355509/5208a2ce-fcd6-11e6-80e8-f6ae20ef62fe.png)

5. select a subset of all pages to print (`2,4,6`) and press the print button
![screen shot 2017-02-27 at 10 13 09](https://cloud.githubusercontent.com/assets/1443089/23355516/60eb5ad4-fcd6-11e6-9d61-ca3cc55c2a91.png)

6. open the print job queue. The print job hangs in the queue until the app is closed.
![screen shot 2017-02-27 at 10 14 09](https://cloud.githubusercontent.com/assets/1443089/23355542/8439dc54-fcd6-11e6-9950-e34936eac380.png)

7. close the app and inspect the resulting oxps file. It is an empty file (`size 0 bytes`)
![screen shot 2017-02-27 at 10 14 38](https://cloud.githubusercontent.com/assets/1443089/23355591/be782fce-fcd6-11e6-912e-60a53bbf507b.png)

I tested this on Windows 8.1 64bit with electron 1.4.15 and 1.6.1. I also tried a real printer (`Samsung ML-6060`). No success.

**Comment by metgens** [comment]
Windows 10 64x
Electron: 1.4.1

I have the same problem with printing as described by @ci42. Printing window is showing up but real printer and pdf printer cannot end job (without any errors).

**Comment by rreimann** [comment]
@MarshallOfSound could you reproduce the issue through the sample application provided by @ci42 or ist there still more information needed?

Testing on (Windows 8.1 64x) with the sample application produces the following results for me:

Electron 1.6.1
- Page range: All => hangs in state spooling (might be related to https://github.com/electron/electron/issues/8828)
- Page range: 4-6 => hangs in state spooling

Electron 1.4.15
- Page range: All => works
- Page range: 4-6 => hangs in state spooling

**Comment by hamster0406** [comment]
I am starting to learn electron and I am using samples (https://github.com/hokein/electron-sample-apps) to see how they work. When running the print sample or even my own code the printing always stays at spooling stage and no output is created / printed.  A simple web page of a couple of lines just stays in spooling stage and refuses to proceed. 

I have tried to run the app on 4 different PCs running Windows 7 (32 and 64 bit) and Windows 10 (32 and 64 bit) but the prints remain in spooling no matter if they are physical printers or xps and pdf printers.
The problem manifests only in latest versions of electron. Anything lower than 1.4.12 and prints don't get stuck at spooling stage. The problem only happens after version 1.4.12 till 1.6.13 (beta).

**Comment by kevinsawicki** [comment]
@ci42 thanks for the detailed reproduction steps, was able to verify #9044 using it 👍 👍 👍
