### ISSUE TITLE
Failed at the electron@1.4.15 postinstall script 'node install.js'.

### ISSUE THREAD

**Issue by shashank7200** [electron/electron#8490]
* NodeJS version: 7.4.0
* NPM version : 4.0.5
* Electron version: 1.4.15
* Operating system: Windows 10

### Expected behavior
Using `npm install -g electron`  in place of `npm install -g electron-prebuilt` should install electron, but it doesn't.

### Actual behavior

While installing electron using `npm install -g electron` ,  `node install.js` throws errors.
### How to reproduce

Error Shows up as:

> $ npm install -g electron
> C:\Users\AshwaMegh\AppData\Roaming\npm\electron -> C:\Users\AshwaMegh\AppData\Ro                                                aming\npm\node_modules\electron\cli.js
> 
>  electron@1.4.15 postinstall C:\Users\AshwaMegh\AppData\Roaming\npm\node_module                                                s\electron
>  node install.js
> 
> C:\Users\AshwaMegh\AppData\Roaming\npm\node_modules\electron\install.js:46
>   throw err
>   ^
> 
> Error: connect ETIMEDOUT 54.231.114.251:443
>     at Object.exports._errnoException (util.js:1022:11)
>     at exports._exceptionWithHostPort (util.js:1045:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "electron"
> npm ERR! node v7.4.0
> npm ERR! npm  v4.0.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! electron@1.4.15 postinstall: `node install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the electron package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs electron
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls electron
> npm ERR! There is likely additional logging output above.

**Comment by MarshallOfSound** [comment]
`ETIMEDOUT` means you experienced some network issues, simply trying again should resolve your issue.  The network issues are out of `electron` and `electron-download`'s control 😢

**Comment by shashank7200** [comment]
Thanks, its resolved now! 🚀

**Comment by willin** [comment]
```
npm i electron
> electron@1.4.15 postinstall /Users/willin/Documents/js.cool/hosts.js/node_modules/electron
> node install.js

^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@


^@^@^@^@^@^@^@^@^@^@^@^C
```


never success
