### ISSUE TITLE
Global shortcuts will only affect the application even if not focused

### ISSUE THREAD

**Issue by httpdigest** [electron/electron#8491]
* Electron version: v1.4.15
* Operating system: Windows 7 x64

### Expected behavior

Registering global shortcuts should only affect the current application instance.

### Actual behavior

Registering a global shortcut on (for example) Ctrl+R while having a normal Chrome application (55.0.2883.87 m (64-bit)) in focus/foreground, will always affect the electron application and not the normal Chrome application.

### How to reproduce

1. Register a global shortcut like so:
```JavaScript
const globalShortcut = electron.globalShortcut
let window = new BrowserWindow()
window.loadURL(someUrl)
globalShortcut.register('Ctrl+R', () => {
  window.webContents.reload()
})
```
2. Start the application via `electron .`
3. Start a normal Google Chrome instance and bring it into foreground/focus
4. Hit the global shortcut Ctrl+R
5. See that instead of affecting to foreground Chrome instance, it affects the background electron application

**Comment by httpdigest** [comment]
Just now I found out about https://www.npmjs.com/package/electron-localshortcut which solves this problem for me.

**Comment by MarshallOfSound** [comment]
@httpdigest `electron-localhost` in my personal opinion is not a good solution to your issue.  The core thing to understand here is that the `globalShortcut` API is by definition "global".  I.e. The shortcut will work from any application "globally" on the users machine and it will prevent the normal key events from being used.

If you want to listen for shortcuts only when a given window is in focus you have two options.

* Use `window.addEventListener('keydown', fn)` and handle key events yourself
* Add the action to a MenuItem in your window's menu with an accelerator as the shortcut

If you don't want to do manual shortcut parsing there are libraries that will do it for you such as [`mousetrap`](https://npmjs.com/mousetrap).

To clarify as to why I don't think `electron-localshortcut` is a good idea in this situation, it's literally adding `globalShortcut` handlers and removing them on `blur` of the window.  This results in some issues.

1. Other applications can get a lock on the shortcut when you lose focus, i.e. the shortcut will magically stop working when you switch back to the app later
2. Some apps can appear on screen without taking focus (spotlight I believe has this behavior) and during the app's appearance the shortcuts will still be captured by your application.
3. There's also gonna be those weird one in a thousand situations where somehow you switch focus and the shortcut is not removed.

**Comment by httpdigest** [comment]
Alright. Thanks for the detailed explanation and mentioning the alternatives!

**Comment by daaru00** [comment]
Personally I tried a different approach registering and de-registering global shortcut when application gains or loses focus:
```js
import { app, globalShortcut } from 'electron'

app.on('browser-window-focus', () => {
  globalShortcut.register('CommandOrControl+R', () => {
    win.reload()
  })
  globalShortcut.register('CommandOrControl+Shift+I', () => {
    win.webContents.openDevTools({ mode:'undocked' })
  })
})

app.on('browser-window-blur', () => {
  globalShortcut.unregisterAll()
})
```

The "deregistration" releases the bind on the shortcut (on Linux is catched from the entire OS) and in this way the (other) application with the focus can listen to their shortcut. When the application gains the focus shortcuts start working again.

**Comment by Pragadesh-45** [comment]
@daaru00, we are planning to implement the same fix to solve the system shortcut hijacking issue. Could you please share if this approach has any drawbacks? I couldn’t come up with any weird scenarios, thanks!

The fix: https://github.com/usebruno/bruno/pull/5490
