### ISSUE TITLE
Support setting numeric options from webpreferences attribute

### ISSUE THREAD

**Issue by xxsnail** [electron/electron#8492]
Hello everyone, ask a question:
        How to set the minimumFontSize property to webview ?
        like BrowserWindow ,webPreferences.minimumFontSize

**Comment by kevinsawicki** [comment]
Many preferences can be set via the `webpreferences` attribute of the `<webview>` element.

http://electron.atom.io/docs/api/web-view-tag/#webpreferences

This does not work currently for number values though so `minimumFontSize` won't work but it should be supported.
