### ISSUE TITLE
Support drag drop of virtual files (mails) into electron app

### ISSUE THREAD

**Issue by juturu** [electron/electron#8494]
I'm looking into adding support for drag n drop of virtual files into electron app. Can you guys please provide any direction on how this can be achieved in electron?

One Idea -
Expose IDataObject from dragndrop from electron to be able to parse and upload from main process.

I tried creating aura::client::dragdropdelegate and calling aura::client::SetDragDropDelegate to get access to IDataObject of drag drop operation. Drag drop methods on the delegate are not getting invoked even for a file drop. Is this a right approach to be able to support this feature? Any other ideas? 

Reference: [Chromium Issue](https://bugs.chromium.org/p/chromium/issues/detail?id=322605)

* Electron version: 1.3.6
* Operating system: Windows/Mac

### Expected behavior
Support drag drop of virtual files into Electron app

### Actual behavior
Virtual files data is not available.

### How to reproduce
Drag/Drop of mails from outlook client app into electron app.

**Comment by zcbenz** [comment]
I don't think there is any way to implement it alone in Electron, I'm closing the since there is already a Chromium issue tracking this.
