### ISSUE TITLE
Get caret position or graphic in offscreen renderer?

### ISSUE THREAD

**Issue by vulture** [electron/electron#8498]
* Electron version: 1.4.14
* Operating system: Windows

### Actual behavior

In the offscreen renderer mode, text fields for example do not have the caret blinking in the pixel data and so it is not possible to show user input location.

### Expected behavior

Would like to be able to either get the actual graphic of the caret blinking (toggleable so that OnPaint is not constantly spammed except during text input), or get the caret display info (e.g. pixel position info) in order to fake display it myself.

**Comment by gerhardberger** [comment]
Discussed in #8522
