### ISSUE TITLE
Chrome 56 will aggressively throttle background tabs

### ISSUE THREAD

**Issue by raphaelarias** [electron/electron#8502]
I just saw this article,  I believe it's going to affect Electron, too. Isn't it?

http://blog.strml.net/2017/01/chrome-56-now-aggressively-throttles.html

Chrome 56 introduces a commendable optimization to throttle background tabs' timers. From the Intent to Implement, the gist is:

Each WebView has a budget (in seconds) for running timers in background.
A timer task is only allowed to run when the budget is non-negative.
After a timer has executed, its run time is subtracted from the budget.
The budget regenerates with time (at rate of 0.01 seconds per second).

**Comment by bpasero** [comment]
I would hope that we can control this via `backgroundThrottling` in `BrowserWindow` [options](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions).

**Comment by kevinsawicki** [comment]
Closing this out, this shouldn't be an issue on 1.6.0 because of the way Electron integrates with Chrome, each `BrowserWindow` has only one "tab" and so it shouldn't be throttled.
