### ISSUE TITLE
Stream upload data with registerHttpProtocol

### ISSUE THREAD

**Issue by sedwards2009** [electron/electron#8503]
I'm looking for a way of doing a custom protocol which support uploading and downloading large files. I'm looking for streaming APIs for this.

`registerHttpProtocol()` lets you use HTTP to download large files via streaming over HTTP. But its API for uploading takes the complete buffer at the time when you call the `callback()` function with the redirect request.

`registerBufferProtocol()` on the other hand doesn't support streaming (downloading) large files. It's `callback()` function expects a complete buffer. By experimenting with uploading data, I see that my protocol handler receives the location of the uploaded file, which means I can stream it myself.

We seem to be missing an API or protocol type which supports both streaming up and down.

**Comment by deepak1556** [comment]
`registerHttpProtocol` will handle streaming large files from the redirect request, there is an issue to allow specifying headers with custom protocol responses, once that is available you can send range responses with buffer protocol. Merging this to https://github.com/electron/electron/issues/4303

**Comment by sedwards2009** [comment]
@deepak1556  I don't think #4303 covers everything. I'm also looking for streaming *uploads*.

**Comment by tarruda** [comment]
#11008 Should should allow one to intercept arbitrary http requests and stream data directly from the network(without buffering in memory like it would require with `interceptBufferProtocol`)

**Comment by codebytere** [comment]
Closing this as it appears https://github.com/electron/electron/pull/11008 addresses a solution.
