### ISSUE TITLE
Restore navigation entry PageState when using history methods

### ISSUE THREAD

**Issue by LeonidVasilyev** [electron/electron#8504]
[Comment ](https://github.com/electron/electron/blob/d0643250f717a9e5d9d4869f72fd5437c88e862f/lib/browser/api/navigation-controller.js#L14) above NavigationController states that navigation is under user control so renderer process is restarted every time:

> // JavaScript implementation of Chromium's NavigationController.
// Instead of relying on Chromium for history control, we compeletely do history
// control on user land, and only rely on WebContents.loadURL for navigation.
// This helps us avoid Chromium's various optimizations so we can ensure renderer
// process is restarted everytime.

But it looks like `void WebContents::GoBack()` [implementation ](https://github.com/electron/electron/blob/22b21d04bdbb43be52a90a3b05fdbd9b4278feea/atom/browser/api/atom_api_web_contents.cc#L952) suppresses renderer process restart:

> void WebContents::GoBack() {
>   atom::AtomBrowserClient::SuppressRendererProcessRestartForOnce();
>   web_contents()->GetController().GoBack();
> }

I found multiple issues on other projects that use Electron where people try to implement BFCache by themselves. [Populate WebView with session, bfcache](https://github.com/mozilla/tofino/issues/320)  and [Make session restore remember frame bfcache / history](https://github.com/brave/browser-laptop/issues/963) for example.

**Comment by steverandy** [comment]
I would say this feature is essential for the webview, where instant back and forward is an expected behaviour.

**Comment by deepak1556** [comment]
The BFCache needs to be implemented in chromium, you can track the progress https://bugs.chromium.org/p/chromium/issues/detail?id=511340 . The issues you linked required the ability to restore session's navigation data, we could provide api for those but I am not sure about its necessity for apps which are not browsers.

**Comment by LeonidVasilyev** [comment]
I was under the impression that Chrome already implements BFCache. Chrome leaves/refills form data after back navigation. Does it use another mechanism for this?

**Comment by deepak1556** [comment]
>  Chrome leaves/refills form data after back navigation. Does it use another mechanism for this?

Yes, the content layer sets form data and scroll as PageState in navigation entry which is used for history navigations. Its a bug in Electrons's navigation controller for not tracking and restoring those states.

**Comment by steverandy** [comment]
Hi, is the electron team considering to implement/fix this issue in the future?
