### ISSUE TITLE
How to know what app is new 

### ISSUE THREAD

**Issue by PterPmnta** [electron/electron#8506]
Hello, I would like to know how I can identify which applications are new or recently released, since with the new system everything is in order, and not as before every application that was new, was at the end.

**Comment by kevinsawicki** [comment]
@PterPmnta Thanks for bringing this up, would you mind reopening this issue over on the website repository so it can be discussed further there?

https://github.com/electron/electron.atom.io/issues/new

**Comment by kevinsawicki** [comment]
I've moved it over to https://github.com/electron/electron.atom.io/issues/662
