### ISSUE TITLE
Transparent property of BrowserWindow cannot be set/changed after it has been created

### ISSUE THREAD

**Issue by bakkiraju** [electron/electron#8512]
Cannot  set BrowserWindow property to be transparent in the middle of my program and not during the creation time ?, since css based animations on window work only if its transparent, I need the window to show up with background color and then go transparent just before my animation kicks in

* Electron version: 1.4.15
* Operating system:os x , win 

### Expected behavior

window.transparent = true,
window.setTransparent(true)

### Actual behavior

Undefined function

**Comment by MarshallOfSound** [comment]
This is by design and I don't think it is either easy or safe to change a window from non-transparent to transparent.

If you need a background colour, just set it on your HTML document.

**Comment by bakkiraju** [comment]
How do I then show a window with background color and html contents and make all of it disappear gracefully ?

Looks like CSS animations only work on a  window that is transparent from the get go
