### ISSUE TITLE
Spawn .bin/electron in windows leads to an error

### ISSUE THREAD

**Issue by Jaheraho** [electron/electron#8514]
Hi there,

thanks for electron, its awesome!

Im using the plugin electron-reload which executes via spawn the following command
`const {spawn} = require('child_process')`
`spawn('C:/Users/me/dev/htdocs/myproject/node_modules/.bin/electron', ['C:/Users/me/dev/htdocs/myproject/'])`
(**.bin/electron**)

This leads to the following error:
![2017-01-26 00_19_40-error](https://cloud.githubusercontent.com/assets/25291878/22313797/c1a3935a-e35e-11e6-8fb7-0dbd99e76123.png)

If I hack the command to
`const {spawn} = require('child_process')`
`spawn('C:/Users/me/dev/htdocs/myproject/node_modules/.bin/electron.cmd', ['C:/Users/me/dev/htdocs/myproject/'])`
(**.bin/electron.cmd**)

then it works. But this has the bad side-effect that a new Windows-CLI (CMD) with focus is opening on every reload. So Iprefer to let the command untouched. It seems that there are other Windows user which doesn't get the error.

By the way: when I'm opening a new CMD and execute the original statement (as follows), electron just opens like it should. Maybe it has something to do with the spawn command?
`C:/Users/me/dev/htdocs/myproject/node_modules/.bin/electron'`
(**.bin/electron**)

* Electron version: 1.4.15
* Operating system: Windows 10  x64
* Additional Info: I'm PHP Storm 2016.3 and have installed Git CLI (don't really thing that it has anything to do with it)

Any ideas?

**Comment by kevinsawicki** [comment]
`.cmd` needs to be appended to the path if you are trying to spawn it from `node_modules\.bin`, this is a limitation of node's spawn command.

You can confirm this by running `child_process.spawn` directly from Node with and without the `.cmd` suffix.

Closing this out, adding `.cmd` should address this or obtain the path of the running Electron instance with `process.execPath`.
