### ISSUE TITLE
Spectron Broken by Electron v1.5.0

### ISSUE THREAD

**Issue by colinskow** [electron/electron#8516]
After upgrading to Electron v1.5.0 Spectron tests are broken. The selenium driver fails to connect and Spectron launches 10 Electron windows.

Using: MacOS, Node 6.9.4, Spectron 3.4.1

It works as expected again after downgrading to Electron v1.4.15.

```
(node:2490) UnhandledPromiseRejectionWarning: 
Unhandled promise rejection (rejection id: 1): 
Error: Client initialization failed after 10 attempts: 
RuntimeError Client initialization failed after 10 attempts:
```

**Comment by MarshallOfSound** [comment]
This should be tracked in one repository only.  Let's track it in your issue in spectron.
