### ISSUE TITLE
WebGL: CONTEXT_LOST_WEBGL when switching to fullscreen with external display and two video cards

### ISSUE THREAD

**Issue by andrej2704** [electron/electron#8517]
Existing context
* Electron version: 1.4.15
* Operating system: Window 10 64-bit. build 14393
* Video card 1: Indel HD Graphics 530
* Video card 2: NVidia Quadro M2000M
* External Display connected

### Expected behavior

WebGL context shouldn't fail in fullscreen

### Actual behavior

When switching to the full sreen, existing wbgl context is lost and can'be recreated. Refreshing electron doesn't help. Electron has to be restarted.
![webglcontext](https://cloud.githubusercontent.com/assets/1634247/22336563/f5c8ecd2-e3e2-11e6-946b-1d0b5236b72c.PNG)

### How to reproduce

- Lunch any web GL content and switch to the full screen or:
1. Launch electron
2. Open dev tools
3. Run document.createElement("canvas").getContext("webgl") !== null;
4. Run require('electron').remote.getCurrentWindow().setFullScreen(true);
5. document.createElement("canvas").getContext("webgl") !== null;
6. Observe result

**Comment by kevinsawicki** [comment]
@andrej2704 are you able to reproduce this with Electron 1.6.0 as well?

**Comment by miniak** [comment]
@kevinsawicki seems to have been fixed by the GPU drivers being updated recently by Lenovo.

**Comment by kevinsawicki** [comment]
@miniak awesome to hear, thanks for the update, do you think it okay to close this out then?

**Comment by andrej2704** [comment]
@kevinsawicky, I'll double check tomorrow

**Comment by andrej2704** [comment]
@kevinsawicki I have updated driver, downloaded Electron 1.6.1. 

Context is not lost anymore. But when I go to full screen in an external display, the screen becomes black, But  I move electron to the laptop's screen and go to full screen - everything is fine.

**Comment by kevinsawicki** [comment]
> Context is not lost anymore. But when I go to full screen in an external display, the screen becomes black, But when I move electron to the laptop's screen and go to full screen there - everything is fine.

Could you check if launching with `--disable-gpu` fixes this? Sounds kind of similar to #4380

**Comment by andrej2704** [comment]
@kevinsawicki, I checked. with disabled gpu electron works fine

**Comment by kevinsawicki** [comment]
@andrej2704 thanks for letting me know, closing this issue out, please subscribe to #4380 for updates on that one.
