### ISSUE TITLE
No store found (Redux devtools)

### ISSUE THREAD

**Issue by DrYSG** [electron/electron#8518]
* Electron version: 1.5
* Operating system: Windows 7.0

### Expected behavior

I have used the electron-devtools-installer, and it successfully added both the React and Redux tools tabs to the devtools. 

### Actual behavior

React works fine. But the Redux is saying that no store is found

### How to reproduce

This is how I add the dev tools, and below that is the simple example of creating the store.

```js
app.on('ready', () => {
  let win = new BrowserWindow({
    width: 1200,
    height: 800
  })
  const options = {extraHeaders : "pragma: no-cache\n"}
  win.loadURL('http://localhost/NodeWork/window.html', options);
  installExtension.default(installExtension.REACT_DEVELOPER_TOOLS)
    .then((name) => console.log(`Added Extension:  ${name}`))
    .catch((err) => console.log('An error occurred: ', err));
  installExtension.default(installExtension.REDUX_DEVTOOLS)
    .then((name) => console.log(`Added Extension:  ${name}`))
    .catch((err) => console.log('An error occurred: ', err));
  win.webContents.openDevTools();
});
```

```js
const reducer = (state = 0, action) => {
    switch (action.type) {
        case 'INCREMENT':
            return state + 1;
        case 'DECREMENT':
            return state - 1;
        default:
            return state;
    }
}

const store = createStore(reducer)
store.subscribe(render)
```

**Comment by kevinsawicki** [comment]
> Electron version: 1.5

Just so we know if this is related to the Chrome 54 upgrade in 1.5.0, does this issue also happen for you in 1.4.15?

**Comment by DrYSG** [comment]
I stand corrected. I am currently 1.4.14, I will  try at 1.5 and get back to you.

**Comment by KagamiChan** [comment]
Seems that you need to follow the [usage instruction of redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension#usage)

**Comment by DrYSG** [comment]
*BLUSH* , Thank you @KagamiChan works fine.
