### ISSUE TITLE
Alt+{letter} shortcut key not working on windows/mac

### ISSUE THREAD

**Issue by nishant09** [electron/electron#8521]
* Electron version: 1.3.1
* Operating system: Windows/Mac

### Expected behavior

Alt+E should open Edit menu
Alt+H should open Help menu

### Actual behavior

Nothing happens

### How to reproduce

Please see below my menu template

menuTemplate.push({
label: "Edit",
accelerator: "Alt+E",
submenu: [
{
label: "Copy",
accelerator: "CmdOrCtrl+C",
role: "copy"
},
{
label: "Cut",
accelerator: "CmdOrCtrl+X",
role: "cut"
},
{
label: "Paste",
accelerator: "CmdOrCtrl+V",
role: "paste"
}
]
});

However, I've other accelerators/shortcut keys in the sub menu which seems to be working fine.

Thank you

**Comment by kevinsawicki** [comment]
The `accelerator` property on `Menu` is not supported for top level menu items.

On Windows this can be enabled by using a label of `&Edit` where the `&` sign will register an alt keybinding for the letter it precedes, in this case `Alt+E`.

I don't think this is natively supported on macOS by their menu API, you can open the menu with `fn+F2` or `fn+Control+f2`.

**Comment by nishant09** [comment]
Thank you @kevinsawicki . this helps
