### ISSUE TITLE
onblur/onfocus events should work in offscreen rendered pages

### ISSUE THREAD

**Issue by vulture** [electron/electron#8522]
* Electron version: 1.4.15
* Operating system: Windows 8.1

### Expected behavior

onblur/onfocus events (and perhaps others?) should work in offscreen rendered pages, since they work in real web browsers like Chrome and on normal non-offscreen rendered pages within Electron.

### Actual behavior

These events do not fire, except in rare (probably special case) circumstances.

Paul suggested that "focus and blur in Electron are tied to the BrowserWindow's window focus, so they're almost certainly not going to fire in an offscreen renderer". Though I'm not entirely sure what this means for me. :D  Maybe that the dummy window provides focus/blur rather than the OSR?

I was hoping for at least some way for the offscreen renderer to behave like a real browser window. I am controlling keyboard/mouse input via
```
osr->GetRenderWidgetHost()->ForwardKeyboardEvent(...);
osr->GetRenderWidgetHost()->ForwardMouseEvent(...)
```
So, there are legitimate ways for focus on some UI elements to be entered and left on offscreen rendered pages. I am okay if there's some hacky workaround I can implement myself (willing to recompile, actually somewhat vaguely familiar with the .cc codebase), but after a lot of tinkering, I couldn't get any of the blur/focus/onblur/onfocus events to fire across multiple files. And the one time I did, it seemed like an async event, so I couldn't find the source that triggered the event to simulate it from offscreen somehow. I'm not exactly sure where to start. I don't know where the underlying focus/blur events would normally come from (webkit? nativewindow?).

### How to reproduce

Sorry for bad code, it's functional though. :P
```
<html><head></head><body>

  <center>
    <font size=+3 color=#1f4fff>Change focus in and out of first text box</font><br>

    <form action="action.cgi">
      First name: <input type="text" id="fname" onfocus="doFocus();" onblur="doBlur();"><br>
      Last name: <input type="text" id="lname"><br>
      <input type="submit" value="Submit" onclick="return false;">
    </form>

  </center>

  <script>
    function doFocus() { document.getElementById('lname').value = "focused"; };
    function doBlur() { document.getElementById('lname').value = "blurred"; };
  </script>

</body></html>
```

for convenience, also available at: http://vulture.fm/x/focustest.html

**Comment by gerhardberger** [comment]
You should try sending input events with [`webContents.sendInputEvent`](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentssendinputeventevent). I've tried your example with an offscreen rendered browser window that gets input events with the method above and it's working. I'm on macOS, but I'm fairly certain it works on Windows too.

![screen shot 2017-01-27 at 5 51 31 pm](https://cloud.githubusercontent.com/assets/1059699/22379351/4a52a33e-e4b9-11e6-905f-56a03ca22a06.png)

btw the cursor blinking is working here too, regarding your other issue. #8498

How are you running your code if you are sending the input events in C++?

**Comment by vulture** [comment]
I added some code to call webContents.sendInputEvent on a timer from js land, inside the <script> block:
```
    var myVar = setInterval(myTimer, 1000);

    function myTimer() {
      var w = require('electron').remote.getCurrentWindow().webContents;
      w.sendInputEvent({        type: 'keyDown',        keyCode: 'Tab'      });
      w.sendInputEvent({        type: 'keyDown',        keyCode: 'End'      });
      w.sendInputEvent({        type: 'keyUp',          keyCode: 'End'      });
      w.sendInputEvent({        type: 'keyDown',        keyCode: 'a'        });
      w.sendInputEvent({        type: 'char',           keyCode: 'a'        });
      w.sendInputEvent({        type: 'keyUp',          keyCode: 'a'        });
      w.sendInputEvent({        type: 'keyUp',          keyCode: 'Tab'      });
    }
```
Also doesn't work (should cycle through the various elements and hit 'a', which does work, but focus/blur events never occurs). This essentially just calls down to ForwardKeyboardEvent anyway (in atom_api_web_contents.cc), so we're basically calling the same code.

I'm converting raw Windows events via e.g. WebKeyboardEventBuilder::Build (in chromium) in C++ and then sending them to ForwardKeyboardEvent on the js thread via a uv async callback. This works fine as far as keyboard/mouse/mousewheel functionality itself. If it's working for you on Mac, maybe there's some Mac/Windows difference? Still doesn't work for me in Windows (neither the onblur/onfocus events nor the caret).

**Comment by vulture** [comment]
Wrote a quick tester to use with stock Electron.exe (instead of our modded one) and got same results. 
imgur album generated from js below: http://imgur.com/a/09Jl1
If it worked, I'd expect to see focused/blurred rather than only a's in the second box.
If I change offscreen: true to false, then it works as expected (though in a live window, rather than a paint event).
Also note the lack of caret in the images (referring to that other issue, again).

Here is the updated full html:
```
<html><head></head><body>
  <center>
    <font size=+4 color=#1f4fff>Hello world!</font><br>

    <form action="action.cgi">
      First name: <input type="text" id="fname" onfocus="overlayFocus();" onblur="overlayBlur();"><br>
      Last name: <input type="text" id="lname"><br>
      <input type="submit" value="Submit" onclick="return false;">
    </form>

  </center>


  <script>
    function overlayFocus() { document.getElementById('lname').value = "focused"; };
    function overlayBlur() { document.getElementById('lname').value = "blurred"; };

    var myVar = setInterval(myTimer, 1000);

    function myTimer() {
      var w = require('electron').remote.getCurrentWindow().webContents;
      w.sendInputEvent({        type: 'keyDown',        keyCode: 'Tab'      });
      w.sendInputEvent({        type: 'keyUp',          keyCode: 'Tab'      });
      w.sendInputEvent({        type: 'keyDown',        keyCode: 'End'      });
      w.sendInputEvent({        type: 'keyUp',          keyCode: 'End'      });
      w.sendInputEvent({        type: 'keyDown',        keyCode: 'a'        });
      w.sendInputEvent({        type: 'char',           keyCode: 'a'        });
      w.sendInputEvent({        type: 'keyUp',          keyCode: 'a'        });
    }

  </script>

</body></html>
```

And the .js (slightly modified but otherwise same) :

```
const {app, BrowserWindow} = require('electron')

app.disableHardwareAcceleration();

let win

var pngcount = 0;

app.once('ready', () => {
  win = new BrowserWindow({
    //show: false,
    //frame: false,
    webPreferences: {
      offscreen: true,
      transparent: true,
    },
  })

  win.loadURL('... url to the html above ...');
  win.webContents.setFrameRate(30);

  win.webContents.on('paint', (event, dirty, image) => {
    var str = "" + pngcount;
    var pad = "0000"
    var ans = pad.substring(0, pad.length - str.length) + str
    var filename = "/temp/out" + ans + ".png";
    var png = image.toPNG()
    var fs = require('fs');
    fs.writeFile(filename, png);
    pngcount++;
  })
})
```

**Comment by gerhardberger** [comment]
I could reproduce the issue with your code and the problem is that you need to explicitly focus the window. Adding this solved the issue for me:

``` js
// ...
  win.loadURL('... url to the html above ...');
  win.webContents.setFrameRate(30);

  win.focusOnWebView(); // you could try `win.focus()` but `focusOnWebView` worked for me best

  win.webContents.on('paint', (event, dirty, image) => {
    var str = "" + pngcount;
// ...
```

**Comment by vulture** [comment]
Can confirm this fixes it for me. Thanks!
