### ISSUE TITLE
Main process crashes on fs.read/write 

### ISSUE THREAD

**Issue by EsSpricht** [electron/electron#8523]
* Electron version: 1.4.8
* Operating system: Windows 10 / Ubuntu 16.04

### Expected behavior

Run a fs.writeFile() function inside a render process. File should be placed correctly and the application should still work.

### Actual behavior

Whenever I try to write a file with fs.writeFile() the main process crashes without a error message IF the file is > ~250mb. After debugging I recognized, that electron sends the file data between the main process and the render process which is the point the app crashes . 
After outsourcing the fs.write functionality to my main.js it works, because the data won't be send between the processes anymore.

It's the same for reading files! I described that in one of my blog posts:
https://medium.com/@baerree/electron-drag-drop-maximum-file-size-8c773d4d179a#.ib7txhovh

### How to reproduce

Try to write a file bigger than 250mb with fs.writeFile() inside a render process. 

fs.writeFileSync(pathToStore, data);

**Comment by kevinsawicki** [comment]
> After debugging I recognized, that electron sends the file data between the main process and the render process which is the point the app crashes .

Are you saying you are seeing Electron sending this file over IPC when you run `fs.writeFileSync` directly?

**Comment by kevinsawicki** [comment]
@EsSpricht are you able to reproduce this via running `fs.writeFileSync` directly from the Console tab of the dev tools?

**Comment by EsSpricht** [comment]
I did not test this (devtools), since I outsourced the functions from my angular scope (app.js) to my electron scope (main.js). I can add an example repo next week, I am very busy at the moment sorry.

**Comment by kevinsawicki** [comment]
@EsSpricht can you provide a minimal example that reproduces this issue for you? Thanks.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
