### ISSUE TITLE
Electron CLI

### ISSUE THREAD

**Issue by iamclaytonray** [electron/electron#8524]
Will there be future support for a CLI concerning Electron? I'm really only interested in a minimal boilerplate for Electron, without cloning the demo Electron app. It's a real pain to go through and delete all of the files that I don't really need. Thanks!

**Comment by kevinsawicki** [comment]
> Will there be future support for a CLI concerning Electron?

Could you elaborate a bit on what you'd like the CLI to do? Would it be used to create new apps, package apps, etc.?

> It's a real pain to go through and delete all of the files that I don't really need.

Which demo Electron app did you clone? The [quick start app](https://github.com/electron/electron-quick-start) has the minimum number of files needed so it might worth checking out when you want to get a new app initialized.

**Comment by zeke** [comment]
You might want to take a look at https://github.com/electron-userland/electron-forge, a new community project for creating, publishing, and installing Electron applications.

**Comment by kevinsawicki** [comment]
Closing this out.
