### ISSUE TITLE
Object containing classes definitions accessed from remote.getGlobal

### ISSUE THREAD

**Issue by tex0l** [electron/electron#8526]
* Electron version: 1.4.15
* Operating system: OSX

Hi,

I have a setup like this in my background process (it's simplified, but the general idea):
```javascript
class MyIntermediateBrowserWindow extends BrowserWindow {
  constructor (options) {
    super(Object.assign({ show: false }, options)
  }
  
  static init () {
    return new this()
  }
}

global.windows = {
  window1: class extends MyIntermediateBrowserWindow {
    constructor () {
      super({height: 400, width: 600})
    }
  },
  window2: class extends MyIntermediateBrowserWindow {
    constructor () {
      super({height: 700, width: 200})
    }
  }
}
```

And in the chrome process I may need to do that:
```javascript
import { remote } from 'electron'

const windows = remote.getGlobal('windows')

const window1 = windows.window1.init()
```

### Expected behavior
It should construct the window properly.

### Actual behavior

The error I get is that `init`is not a function.

The workaround I have for now is not to put `window1` and `window2` as properties of `window` but directly of `global`.

I though it had been corrected in this PR: https://github.com/electron/electron/pull/4568 but obviously this resolution doesn't seem to be recursive. Am I wrong?

Thanks.

**Comment by sofianguy** [comment]
Thanks for contributing!

We are no longer releasing bug fixes for versions of Electron older than 1.6x. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.
