### ISSUE TITLE
No longer renders properly

### ISSUE THREAD

**Issue by MH15** [electron/electron#8531]
* Electron version: ^1.3.2
* Operating system: Windows 10

### Expected behavior
Electron should start and load normally, as it did in the past

### Actual behavior
When I run `electron .` anymore, it just shows a blank screen like this:
![capture](https://cloud.githubusercontent.com/assets/14988198/22408537/638490a2-e648-11e6-9219-70f9332a152c.PNG)

### How to reproduce
No idea. I didn't change versions or anything.

**Comment by sklink** [comment]
Need more context for this. Is this on a fresh application? If not, does it work with a fresh electron application?

**Comment by MH15** [comment]
This is on an application I am building. After it stopped working, I reset it to the default electron template and the error persisted.

**Comment by kevinsawicki** [comment]
@MH15 can you provide a minimal example that reproduces the issue for so we can look into this further? Thanks.

**Comment by bsclifton** [comment]
@MH15 are you able to update your Electron version? 1.3.2 is a bit old 😕 

Something else you can try: appending one of the following to your command line args to electron:
`--ignore-gpu-blacklist`
`--disable-gpu`

**Comment by guzgarcia** [comment]
FU AMD. I'm on Ubuntu 16.04 and almost all Chromium based applications suffer this. This makes Electron based applications complete unusable on AMD GPUs :(.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
