### ISSUE TITLE
Electron not per-monitor DPI aware on Windows

### ISSUE THREAD

**Issue by daguej** [electron/electron#8533]
* Electron version: 1.5.0-beta
* Operating system: Windows 10 (build 15014)

### Expected behavior

Electron should declare itself per-monitor DPI aware (ie, able to handle `WM_DPICHANGED`) since Chrome 54 introduced per-monitor DPI handling.

### Actual behavior

Electron declares itself as only System DPI aware; Windows applies ugly bitmap scaling to electron windows dragged between displays with differing DPIs.

### How to reproduce

Drag an electron window from a high-DPI display to a low-DPI display.  Windows' DWM will rescale the window using bitmap downscaling, resulting in a blurry image.  Also notice that `window.devicePixelRatio` does not change as you drag the window between displays of differing DPI.  (code from [this fiddle](https://jsfiddle.net/josh3736/kcc83e0g/) demonstrates)

### History lesson and important notes

Getting DPI scaling on Windows right is very hard because of its [legacy of gradual support for additional DPI-related features](https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266.aspx).

Applications can declare themselves DPI aware in 3 (or 4, depending on how you're counting) different levels by opting in via application manifest or by calling [`SetProcessDpiAwareness`](https://msdn.microsoft.com/en-us/library/windows/desktop/dn302122(v=vs.85).aspx):

- In the beginning (the 90s), there was no such thing as DPI awareness.  All hardware and software assumed that things render at approximately 96dpi.
- Windows XP added a "system DPI awareness": a global value at which all applications should render.  This value is calculated *once* and requires a reboot to change.  This DPI applies across all connected displays, regardless of each display's physical DPI. *(This is the level electron currently supports.)*

  Modern Windows (>8) implements bitmap scaling so that a window dragged between displays of differing DPIs look more-or-less correct.  A window that is 1000x1000px on a 200dpi display (physically 5in x 5in) will be downscaled to 500x500px on a 100dpi display (still 5in x 5in).  The application is completely unaware of this scaling; the DWM handles it transparently.

- Windows 8.1 added "per-monitor DPI awareness".  Windows sends a [`WM_DPICHANGED`](https://msdn.microsoft.com/en-us/library/windows/desktop/dn312083.aspx) message to a window as it moves to monitors of different DPIs.  It is a per-monitor DPI aware application's responsibility to process this message, resize its window (so as to maintain physical dimensions) and re-render its contents.

  Of note, the non-client area (eg titlebar and min/max/close buttons) of a per-monitor DPI aware window are **not** automatically scaled by Windows -- they *always* render at the "system DPI".  Thus, when dragged from the primary, high-DPI display to a low-DPI display, the non-client controls look oversized.

- Windows 10 Anniversary Update (build 14393) added a new API that enables automatic scaling of the non-client area, [`EnableNonClientDpiScaling`](https://msdn.microsoft.com/en-us/library/windows/desktop/mt748621.aspx).

So there are a few things that electron needs to do in order to fully support high-DPI systems:

1. Declare the process per-monitor DPI aware.
2. In `WM_NCCREATE`, call `EnableNonClientDpiScaling(hWnd)` *if it exists*.
3. Handle `WM_DPICHANGED`.
    - The `lParam` of this message contains a rect with a new suggested pixel size that causes the window to maintain its physical dimensions.  Call `SetWindowPos` with this rect.
    - Cause the web view to re-render at the new DPI.  This should ultimately result in `window.devicePixelRatio` to change.

**Comment by miniak** [comment]
This was already filed as https://github.com/electron/electron/issues/5429

**Comment by poiru** [comment]
Closing in favor of #5429.
