### ISSUE TITLE
Make the Chrome cache accessible to electron.

### ISSUE THREAD

**Issue by ericbets** [electron/electron#8534]
Hi, I've started work on a new browser project today. It fits in well with another project I'm working on at the moment, so I've decided it's time. It already looks pretty great thanks to @adamschwartz 's chrome-tabs project.
![hackable](https://cloud.githubusercontent.com/assets/49939/22411621/906218f2-e6f1-11e6-9c82-d796e5f5124e.png)
I wrote down a few of my ideas a few days ago here (and the accompanying gist):  https://news.ycombinator.com/item?id=13496660  
I was just wondering if there is an appetite on the electron team to help me implement this and the accompanying urlcache idea, as described in the gist. Looking forward to your feedback. Thanks!

**Comment by groundwater** [comment]
Hi @ericbets, we don't have a formal RFC process for proposing enhancements yet, but we'd recommend following [the rust rfc template](https://github.com/rust-lang/rfcs/blob/master/0000-template.md) to give your idea the best chance of getting reviewed.

**Comment by ericbets** [comment]
thanks for the feedback @groundwater. As suggested. 

Expose Electron Cache
18 Feb 2017

Summary:

Expose the Chrome cache to surface the ability to precisely control which assets are cached, and when.

Motivation:
The benefit cited is because will make the web faster and more efficient. Adding this feature could be the catalyst for a new era of competition among client side caching algorithms.

Detailed Design:

I propose that there are 3 relatively low hanging fruit ways to make a big improvement in browser caching:

1. Enable the opportunity for client side predicting modelling of user resource demand in the browser (eg. preloading data)
Some outside electron black box function (informed by it's own chrome ui chrome) keeps track of my history and knows that I go to example.org every day. Through it's magic, it can infer which other webpages / resources I am likely to visit at any given time, and fetch them before I do.
So electron could expose a preload(url) function to warm up the cache. 

2. Better cache control / eviction functionality
The black box somehow knows I am less likely to visit example.org/catphoto again, because I've already been and had my guffaw. So electron could expose an evict(url) function. A few other HT like functions like exists(url) and viewCache(url), keys() would makse sense too.
 
3. Better Immutable Caching (for lack of a better name, let's call this the urlcache spec)
Let's say you have a file.png that you want the browser to know with perfect knowledge if a file has changed on the server or not, and you want it to be backwards compatible with the existing web, without using a complex http header based scheme:
It's url could be: http://example.org/urlcache/path/to/file/file.mimext?hashalg=hash
eg. example.org/urlcache/file.png?sha384=9b78b27b73668784e38c8a58a8535deaaecb77709

If the browser sees the string "urlcache", it knows this url has been marked as meeting this spec, and can proceed thusly.

The benefits of this approach are as follows.
-It's filename preserving.
-It's more accessible to users than using http headers. 
-It avoids the subtle security pitfalls and usability complexity associated with using http headers for this. (see the thread I cited above for links to discussion about that)

Drawbacks
None known

Alternatives
None known

Unresolved questions
Ask away

**Comment by groundwater** [comment]
_Edit: Updated formatting_

**Comment by MarshallOfSound** [comment]
I took a quick look into the cache implementations in Chromium.  Initial thoughts are it *could* be possible to expose `CreateEntry` and `DoomEntry` in some kind of API, it would appear to be a reasonably large chunk of work to do however.

Number 3 in your detailed design is something that (AFAIK) will never be implemented in Electron as it fundamentally changes the way caching web assets works.  It could target pre-existing URL's that have "urlcache" in their path without intending to actually be cached.  It would be a breaking change not just to Electron things but to the Web in general.  That being said if we expose the Entry API's mentioned above somehow then you could feasibly implement that kind of thing yourself.

Relevant Chromium Code:  
https://cs.chromium.org/chromium/src/net/disk_cache/disk_cache.h?dr  

Good Reading RE Chromium Cache:  
http://dev.chromium.org/developers/design-documents/network-stack/disk-cache

**Comment by ericbets** [comment]
The urlcache thingy string seems low risk, could be hidden behind a build or config flag. I'm all for trying because in my value system, shipping a working impl is more important than doing what everyone else is doing. What's the barrier to exposing all those Entry APIs? If there is a quick and dirty way to do it, I'm all for it, as the process of exposing those apis would be iterative and the feedback that resulted would probably lead to a nice api in fairly short order.

**Comment by groundwater** [comment]
Hi @ericbets. I put this up for comments to our maintainer community.

**Comment by zcbenz** [comment]
It is possible to simply expose the low-level Chromium `disk_cache` APIs, but it is rather hard to use and does not have any security checks. To get something that really works, it would require considerate work to wrap the low-level Chromium APIs with high-level JavaScript ones.

I don't think we can clearly say whether we should do this or not without a working implementation of a cache API, because things we can do are highly limited to what Chromium provides. Obviously none of the maintainers is interested in implementing this, so I'm just closing this.

If anyone is still interested in this, I suggest bringing up a simple implementation of the possible API first, and then starting discussing whether we should do i.t

**Comment by ericbets** [comment]
Thanks for leaving the ticket open so long.

**Comment by sumit-kumar-adobe** [comment]
We had a similar requirement. 
We are using data from CMS in our application. 
We would like that data is cached. So that it is fast and can work while it is in offline mode.
So, it would be great if we have control over web cache.

I see that this is closed. 
Any chance it will be available in future ?
