### ISSUE TITLE
link opens an electron app that contains a webview

### ISSUE THREAD

**Issue by plainspace** [electron/electron#8535]
* Electron version: `"electron": "^1.4.15",`
* Operating system: `MacOS 10.12.3

### Expected behavior
I "expect" to be able to click a link, for instance, in an email, and open an electron app that contains a webview. E.g. this project that contains a webview of Paper by Dropbox. https://github.com/williambout/paper-for-mac

Is this a realistic expectation? I'm thinking something similar to clicking an Amazon link in iOS and having the Amazon app open instead of amazon.com in my default browser. 

### Actual behavior
I don't know because I haven't figured out if it is possible/realistic.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
FWIW you probably want the default protocol handler API's.

http://electron.atom.io/docs/api/app/#appsetasdefaultprotocolclientprotocol-path-args-macos-windows
