### ISSUE TITLE
Headset microphone doesn't work

### ISSUE THREAD

**Issue by nicolasandrieux** [electron/electron#8544]
* Electron version:v1.4.14
* Operating system:mac OS

### Using webrtc tool my microphone should works
I don't know what happens

**Comment by kevinsawicki** [comment]
> How to reproduce

Can you include a minimal example app that reproduces this issue for you? That will help us find out what is happening.

**Comment by nicolasandrieux** [comment]
Hi, 

My app is making call using webrtc.

On my Imac27, when I plug my headset (hear and microphone), my microphone doesn't work. On the same computer, when I use chrome or a chrome extension the microphone is working.

I have done more test and when I do the same on my macbook, my microphone is working in all case.

So I think this is a hardware + electron compatibility issue. 

here is my Imac configuration
https://cloud.githubusercontent.com/assets/8235807/22544197/131f1814-e934-11e6-9517-e2fde740130d.png

Regards

**Comment by MarshallOfSound** [comment]
@nicolasandrieux Can you provide the code you use to test your microphone.  We will need it in order to properly figure out what is going on 👍

**Comment by nicolasandrieux** [comment]
today it's working, may be just an hardware issue then (hope).

**Comment by zcbenz** [comment]
We are unable to fix a problem with a specific hardware, so I'm closing this as won't fix.
