### ISSUE TITLE
Frameless windows miscalculate workspace size when maximized

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#8546]
* Electron version: 1.4.x, 1.5.x
* Operating system: Windows 10, probably others

To Reproduce:

* Set your Windows Taskbar to auto-hide
* Open any Electron application that uses custom non-client area (both Slack and Discord repro this)
* Maximize the Window
* Try to get the Taskbar to show up, you can't
* Open an Electron application that uses a standard frame (Atom, VS Code, etc)
* Do the same thing, it works
* Note that the latter case leaves a 1px border on the bottom of the window, and the former case overshoots it by just a little bit, completely covering the Taskbar

Even when the Taskbar is set to show always, you can see this issue (you may have to zoom in a bit to see it, there is a ~3px grey line from where the Slack window overshoots the workspace area)

![image](https://cloud.githubusercontent.com/assets/1396/22482023/2e5638f8-e7ac-11e6-8036-c1760db2d4e9.png)

**Comment by groundwater** [comment]
Confirmed on Windows 10, Surface Pro 4.

Hey @paulcbetts do you also know how to fix this?

**Comment by zcbenz** [comment]
This is essentially because Windows 10 is feeding apps with fake data of window size, so that legacy apps can look "fine" on Windows 10.

I'm merging this to https://github.com/electron/electron/issues/4045.
