### ISSUE TITLE
Spellchecking support for sandboxed renderers

### ISSUE THREAD

**Issue by sltam** [electron/electron#8547]
From what I understand from the docs, [`webFrame.setSpellCheckProvider`](http://electron.atom.io/docs/api/web-frame/#webframesetspellcheckproviderlanguage-autocorrectword-provider) is required to enable spellchecking, but `webFrame` is a renderer-only construct and there is no way a sandboxed renderer can obtain a reference to its own `webFrame`, so it seems there is currently no way to achieve so.

**Comment by liliakai** [comment]
There are now multiple requests for webFrame support in sandboxed renderers over at #6712, though I think this particular use case would also be satisfied by allowing the main process access to `setSpellCheckProvider` via `webContents`, as is done with several other `webFrame`-specific methods [here](https://github.com/electron/electron/blob/master/lib/browser/api/web-contents.js#L109).

**Comment by dataich** [comment]
I'd like to call setSpellCheckProvider on main process too 👍

**Comment by ppontes** [comment]
@sltam , webFrame is available to be required in the preload script of a sandbox renderer since Electron 1.8, so I'm closing this issue. Feel free to reopen if something's not working.
