### ISSUE TITLE
Electron Environment

### ISSUE THREAD

**Issue by Davidzhu001** [electron/electron#8551]
Hey guys,

Here is a questions regards Child process of Electron.

Before I build into Mac App, the ruby version is 2.3.1

After Build into mac app Ruby version is 2.0.0(Systerm);

And other commands are not availible anymore.

I want to know why? and How to solve it.

Thanks so much

Is that because Chromium, Mac App Accessibility or other reason?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
@Davidzhu001 When you launch an app from Terminal (in dev mode) it inherits your environment variables from your bash environment.  I.e. Your `$PATH` variable.

When packaged and launched normally these variables are not inherited so it only uses the default known system path variable.

**Comment by Davidzhu001** [comment]
@MarshallOfSound Can you direct me to some readings or give me a direction of how to solve it?

**Comment by MarshallOfSound** [comment]
https://www.npmjs.com/package/fix-path

**Comment by Davidzhu001** [comment]
Thanks so much @MarshallOfSound
