### ISSUE TITLE
Raspberry - Flash got sound but not video

### ISSUE THREAD

**Issue by Stan92** [electron/electron#8552]
* Electron version: 1.4.15
* Operating system: Raspbian Jessie

I use a webview as described in the documentation and set all the parameters as well.
Everything works with Mac OS (video as well as sound).
But with my PI 3, I only get the sound (I've also set my memory split to 192)
From my console (PI), I have a message saying "Not sandboxed, vector smash protection is enabled"
My pepper flash version is 24.0.0.174 

My code is : 
```
let pluginName
switch (process.platform) {
    case 'darwin':
        pluginName = 'plugins/flash/mac/PepperFlashPlayer.plugin';
        break
    case 'linux':
        pluginName = 'plugins/flash/pi/libpepflashplayer.so';
        break
}
app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, pluginName));
app.on('ready', function() {
    mainWindow = new BrowserWindow(
        {
        backgroundColor: '#000000',
        fullscreen:true,
        autoHideMenuBar:true,
        webPreferences:
            {
                plugins: true ,
                webSecurity: false
            }
        });
    mainWindow.loadURL('file://' + __dirname + '/app/index.html');
    mainWindow.on('closed', function() {
        mainWindow = null;
    });
});

```
My html page
```

<webview plugins
         style="display:inline-block; width:640px; height:480px"
         id="videoWebView"
         name="videoWebView"
         disablewebsecurity
         nodeintegration
         src="http://player.canalplus.fr/site/flash/player.swf?param=itele_live&env=prod&videoId=203105&targetURL=&timecode=0targetNewWindow=false&autoplay=1">
</webview>
```

**Comment by groundwater** [comment]
Hey @Stan92 this might be a little hard to track down since we don't have PIs. I definitely appreciate the repro case however.

A quick search led me to https://bugs.chromium.org/p/chromium/issues/detail?id=257741 which may or may not be related.

We'll take a longer look, but you may also want to help us track down what's going on.

**Comment by kevinsawicki** [comment]
@Stan92 are you able to try this out using Electron 1.6.1 which has the Chrome 56 upgrade in it?

**Comment by Stan92** [comment]
Not yet tested :-(
If you did or will test it let me know if it works

Stan



Le 21 f?vr. 2017 ? 17:50, Kevin Sawicki <notifications@github.com<mailto:notifications@github.com>> a ?crit :


@Stan92<https://github.com/Stan92> are you able to try this out using Electron 1.6.1 which has the Chrome 56 upgrade in it?

-

**Comment by zcbenz** [comment]
Closing this out since no one including the op is not interested in this issue.
