### ISSUE TITLE
Mac app store build uses non-public APIs 

### ISSUE THREAD

**Issue by herrmannplatz** [electron/electron#8555]
* Electron version: 1.5.0
* Operating system: macOS

I made a test build with the electron 1.5.0 MAS version and submitted it to apple. These are the issues that apple complained about.

> Performance - 2.5.1
>
> Your app uses or references the following non-public API(s):
>
> '/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics'
>
> : CGSSetWindowBackgroundBlurRadius
>
> The use of non-public APIs is not permitted on the App Store as it can lead to a poor user experience should these APIs change.

**Comment by kevinsawicki** [comment]
Thanks for reporting this, we probably need to add a new patch to `libchromiumcontent` that patches out these function calls on the MAS build.

https://github.com/electron/libchromiumcontent/blob/master/patches-mas/no_private_api.patch

**Comment by kevinsawicki** [comment]
> I made a test build with the electron 1.5.0 MAS version and submitted it to apple. 

Did you previously submit a version of your app using Electron 1.4.x and was that one rejected?

**Comment by herrmannplatz** [comment]
No, but i can make a build an submit it.
