### ISSUE TITLE
electron build failed on windows 10

### ISSUE THREAD

**Issue by ArashAlikhani** [electron/electron#8559]
sorry if this is not an issue to post here, I don't know anywhere else to ask.
I just followed the instruction for building for windows from docs, like this:

$ git clone https://github.com/electron/electron.git
$ cd electron
$ python script\bootstrap.py -v
$ python script\build.py

but it failed in the build process with some errors that i couldn't figure out for hours.

C:\Users\Arash\Documents\ElectronProjects\electron>python script\build.py
ninja: Entering directory `out\R'
[6/625] CXX obj\vendor\brightray\browser\brightray.special_storage_policy.obj
FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\vendor\brightray\browser\brightray.special_storage_policy.obj.rsp /c ..\..\vendor\brightray\browser\special_storage_policy.cc /Foobj\vendor\brightray\browser\brightray.special_storage_policy.obj /Fdobj\vendor\brightray\brightray.cc.pdb
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(638): error C2134: 'base::TimeDelta::FromProduct': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(638): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(264): note: see declaration of 'base::TimeDelta::FromProduct'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(643): error C2134: 'base::TimeDelta::FromProduct': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(643): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(264): note: see declaration of 'base::TimeDelta::FromProduct'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(648): error C2134: 'base::TimeDelta::FromDouble': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(648): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(260): note: see declaration of 'base::TimeDelta::FromDouble'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(653): error C2134: 'base::TimeDelta::FromDouble': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(653): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(260): note: see declaration of 'base::TimeDelta::FromDouble'
[6/625] CXX obj\vendor\brightray\common\brightray.content_client.obj
FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\vendor\brightray\common\brightray.content_client.obj.rsp /c ..\..\vendor\brightray\common\content_client.cc /Foobj\vendor\brightray\common\brightray.content_client.obj /Fdobj\vendor\brightray\brightray.cc.pdb
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(638): error C2134: 'base::TimeDelta::FromProduct': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(638): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(264): note: see declaration of 'base::TimeDelta::FromProduct'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(643): error C2134: 'base::TimeDelta::FromProduct': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(643): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(264): note: see declaration of 'base::TimeDelta::FromProduct'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(648): error C2134: 'base::TimeDelta::FromDouble': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(648): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(260): note: see declaration of 'base::TimeDelta::FromDouble'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(653): error C2134: 'base::TimeDelta::FromDouble': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(653): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(260): note: see declaration of 'base::TimeDelta::FromDouble'
[6/625] CXX obj\vendor\brightray\browser\brightray.web_ui_controller_factory.obj
FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\vendor\brightray\browser\brightray.web_ui_controller_factory.obj.rsp /c ..\..\vendor\brightray\browser\web_ui_controller_factory.cc /Foobj\vendor\brightray\browser\brightray.web_ui_controller_factory.obj /Fdobj\vendor\brightray\brightray.cc.pdb
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(638): error C2134: 'base::TimeDelta::FromProduct': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(638): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(264): note: see declaration of 'base::TimeDelta::FromProduct'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(643): error C2134: 'base::TimeDelta::FromProduct': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(643): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(264): note: see declaration of 'base::TimeDelta::FromProduct'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(648): error C2134: 'base::TimeDelta::FromDouble': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(648): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(260): note: see declaration of 'base::TimeDelta::FromDouble'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(653): error C2134: 'base::TimeDelta::FromDouble': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(653): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(260): note: see declaration of 'base::TimeDelta::FromDouble'
[6/625] CXX obj\vendor\brightray\common\brightray.main_delegate.obj
FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\vendor\brightray\common\brightray.main_delegate.obj.rsp /c ..\..\vendor\brightray\common\main_delegate.cc /Foobj\vendor\brightray\common\brightray.main_delegate.obj /Fdobj\vendor\brightray\brightray.cc.pdb
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(638): error C2134: 'base::TimeDelta::FromProduct': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(638): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(264): note: see declaration of 'base::TimeDelta::FromProduct'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(643): error C2134: 'base::TimeDelta::FromProduct': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(643): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(264): note: see declaration of 'base::TimeDelta::FromProduct'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(648): error C2134: 'base::TimeDelta::FromDouble': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(648): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(260): note: see declaration of 'base::TimeDelta::FromDouble'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(653): error C2134: 'base::TimeDelta::FromDouble': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(653): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(260): note: see declaration of 'base::TimeDelta::FromDouble'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\point_f.h(25): error C3249: illegal statement or sub-expression for 'constexpr' function
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\point_f.h(24): error C2476: 'constexpr' constructor does not initialize all members
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\point_f.h(81): note: 'gfx::PointF::x_' was not initialized by the constructor
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\point_f.h(82): note: 'gfx::PointF::y_' was not initialized by the constructor
[6/625] CXX obj\vendor\brightray\browser\views\brightray.inspectable_web_contents_view_views.obj
FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\vendor\brightray\browser\views\brightray.inspectable_web_contents_view_views.obj.rsp /c ..\..\vendor\brightray\browser\views\inspectable_web_contents_view_views.cc /Foobj\vendor\brightray\browser\views\brightray.inspectable_web_contents_view_views.obj /Fdobj\vendor\brightray\brightray.cc.pdb
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(638): error C2134: 'base::TimeDelta::FromProduct': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(638): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(264): note: see declaration of 'base::TimeDelta::FromProduct'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(643): error C2134: 'base::TimeDelta::FromProduct': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(643): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(264): note: see declaration of 'base::TimeDelta::FromProduct'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(648): error C2134: 'base::TimeDelta::FromDouble': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(648): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(260): note: see declaration of 'base::TimeDelta::FromDouble'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(653): error C2134: 'base::TimeDelta::FromDouble': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(653): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\time\time.h(260): note: see declaration of 'base::TimeDelta::FromDouble'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\point_f.h(25): error C3249: illegal statement or sub-expression for 'constexpr' function
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\point_f.h(24): error C2476: 'constexpr' constructor does not initialize all members
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\point_f.h(81): note: 'gfx::PointF::x_' was not initialized by the constructor
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\point_f.h(82): note: 'gfx::PointF::y_' was not initialized by the constructor
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\size_f.h(25): error C3249: illegal statement or sub-expression for 'constexpr' function
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\size_f.h(26): error C3249: illegal statement or sub-expression for 'constexpr' function
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\size_f.h(24): error C2476: 'constexpr' constructor does not initialize all members
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\size_f.h(59): note: 'gfx::SizeF::width_' was not initialized by the constructor
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\size_f.h(60): note: 'gfx::SizeF::height_' was not initialized by the constructor
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\rect_f.h(37): error C3249: illegal statement or sub-expression for 'constexpr' function
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\rect_f.h(40): error C3249: illegal statement or sub-expression for 'constexpr' function
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\rect_f.h(38): error C3249: illegal statement or sub-expression for 'constexpr' function
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\rect_f.h(39): error C3249: illegal statement or sub-expression for 'constexpr' function
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\rect_f.h(36): error C2476: 'constexpr' constructor does not initialize all members
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\rect_f.h(188): note: 'gfx::RectF::origin_' was not initialized by the constructor
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\ui\gfx\geometry\rect_f.h(189): note: 'gfx::RectF::size_' was not initialized by the constructor
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\third_party\skia\include\private\sksemaphore.h(18): error C2134: 'SkOnce::SkOnce': call does not result in a constant expression
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\third_party\skia\include\private\sksemaphore.h(18): note: failure was caused by call of undefined function or one not declared 'constexpr'
c:\users\arash\documents\electronprojects\electron\vendor\brightray\vendor\download\libchromiumcontent\src\third_party\skia\include\private\skonce.h(22): note: see declaration of 'SkOnce::SkOnce'
ninja: build stopped: subcommand failed.

I appreciate and would be very thankful if anyone could help me.

**Comment by bsclifton** [comment]
Hi @ArashAlikhani 

This is happening because you don't have the latest service packs for Visual Studio 15.  I've had the same error before.  Please try updating and then rebuild

**Comment by groundwater** [comment]
Hey @ArashAlikhani, going to close this in case the above works. Feel free to re-open if it's still an issue.

**Comment by ArashAlikhani** [comment]
sorry for my late response.
I had to change my windows and reinstall visual studio to test it.
Thank @bsclifton it works fine.
