### ISSUE TITLE
Send messages from WebView preload to renderer

### ISSUE THREAD

**Issue by anaisbetts** [electron/electron#856]
`WebView.send` allows the renderer to send async messages to the WebView contents, but the opposite isn't possible - requiring `ipc` will send messages to the _browser_ process - while workable, this adds an extra layer of indirection

**Comment by pushkin-** [comment]
I don't quite understand how this solves the problem. `sendToHost` sends a message to the webview, not the renderer, right? Is there a way to send messages directly from the preload script to the renderer process (specifically the renderer process that "surrounds" the webview from which you're sending the message)?

**Comment by enlight** [comment]
@pushkin- While the `ipc-message` handler is attached to the `webview` element, the event handler is actually executed in the renderer process in which the webview is embedded, as can be seen in the example: https://electron.atom.io/docs/api/webview-tag/#event-ipc-message

**Comment by pushkin-** [comment]
@enlight If I put a webview in a browser window, won't the webview be in its own renderer process as well as the window? So, you're saying it'll send the message to the outer renderer process, is that right? If I do `ipcRenderer.on("ping", ...)` in the index.js of that window as well as a `webview.addEventListener("ipc-message", ...)`, and then from the preload script do `ipcRenderer.sendToHost("ping")`, it seems that the listener attached to "ping" with `ipcRenderer.on` does not catch the message, only the listener attached to the `webview` catches it. Do you know how I can get the `ipcRenderer.on` to catch it?

**Comment by Aarbel** [comment]
@pushkin- have you found a solution ?

**Comment by pushkin-** [comment]
@Aarbel Wow I totally don't remember posting that.

Looking at my code now I still use the `webview.addEventListener` and from within that callback, I call `ipcRenderer.send(...)` to send it to my main process.

I do have an `ipcRenderer.on` call, but that's for intercepting messages coming from main to renderer and then forwarding them on to the webview via `webview.send(...)`.

So... it's not solving the problem, but I guess it was acceptable to use `webview.addEventListener` in my case.

**Comment by Aarbel** [comment]
Thank you @pushkin- 

I just found this example that can maybe help you : https://github.com/kw77/electron-webview-ipc-demo

**Comment by pushkin-** [comment]
@Aarbel Re-reading what enlight said, it sounds like even though you're adding the listener to the webview, the handler is actually being executed in the outer renderer process, so the problem *is* solved... `ipcRenderer.on` is used for intercepting messages sent in the other direction
