### ISSUE TITLE
powerMonitor.on('suspend/resume') doesn't work at win10 tablet devices

### ISSUE THREAD

**Issue by Dominis13** [electron/electron#8560]
* Electron 1.4.14 (upgrade to 1.4.15 doesn't help)
* Operating system: windows 10 (only on tablets. like this one(http://shop.lenovo.com/us/en/tablets/ideapad/miix/miix-310/), wasn't checked on surface devices)

```
electron.powerMonitor.on('suspend', () => {
    console.log('GOING TO SLEEP!');
    mainWindow.send('custom-suspend');
  });
```

This code works well on the PC and laptop win10, but on the tablet with win10 it does nothing. I can't see my console.log and don't get my custom event.
I've tried to install every win10 updates - it doesn't help.
I've tried to play with tablet mode on both laptop and tablet devices - there is no differences: tablet doesn't trigger event in the both modes, laptop does trigger event in both modes...

I use https://github.com/chentsulin/electron-react-boilerplate for my project, if it matters. For out project we use two different ways to build package, and have the same behavior in both packages.

**Comment by groundwater** [comment]
Hi @Dominis13 thanks for the report.

We will attempt to verify this, and investigate further.

**Comment by groundwater** [comment]
Can confirm this - repro case here https://github.com/electron-support-cases/issue-8560

**Comment by groundwater** [comment]
Hey @kevinsawicki, I can't find any chrome plugin APIs for getting power events, only ones to [prevent the machine/screen from sleeping](https://developer.chrome.com/apps/power).

What do you think a good next step would be in narrowing this down?

# Some relevant links

- [Electron Power Monitor Source](https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_power_monitor.cc)
- [Chromium power_monitor.h](https://cs.chromium.org/chromium/src/base/power_monitor/power_monitor.h?q=base/power_monitor/power_monitor+package:%5Echromium$&l=1)
- [Chromium power event dispatch](https://cs.chromium.org/chromium/src/base/power_monitor/power_monitor_source.cc?l=47)
- [No apparent Chromium Bugs](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=PowerEvent&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids) mentioning `PowerEvent`

**Comment by kevinsawicki** [comment]
> What do you think a good next step would be in narrowing this down?

Maybe trying http://exodusdev.com/products/monitor-win32-power-management-events and see if the events are event getting fired. I haven't tried that tool before but saw it referenced from https://answers.microsoft.com/en-us/windows/forum/windows_10-desktop/windows-10-taskbar-thumbnails-preview-keep/c74dfbe8-db09-4d5f-b7a2-f7a2f0fc7da4?page=12

**Comment by mrobrian** [comment]
I've run into this same issue on a Microsoft Surface Pro 4 running the latest Windows 10 (as of this writing) and Electron v1.6.5.  The 'on-ac' and 'on-battery' events do work as expected, but the 'suspend' and 'resume' events don't fire.

I'm curious if anyone has a workaround for this issue.  I might end up using electron-edge and write a solution in C# for now, but I was hoping to avoid that.

**Comment by petrkomarek** [comment]
Seems like it's not working correctly even on OSX. If the user initiate sleep, then it works, but if the machine goes to sleep by itself, then no event are raised...

Did you guys thought about not using Chromium API for this, but write it natively?

**Comment by bengotow** [comment]
This is probably related to #1615. Honestly, it seems like this does not work as advertised on at least some subset of both Windows and macOS machines. The docs should probably be changed to note that this module is not working. To detect the system waking from sleep I'm switching to this approach (https://blog.alexmaccaw.com/javascript-wake-event), which essentially just waits for a setTimeout() to take longer than the timeout.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
