### ISSUE TITLE
Not accessible not found in win 10

### ISSUE THREAD

**Issue by binjospookie** [electron/electron#8564]
* Electron version: 1.5.0
* Operating system: Windows 10

### Expected behavior

find application

### Actual behavior

no return

### How to reproduce

click start
search application on Electron
does not return application

<img src="https://cloud.githubusercontent.com/assets/640846/22552766/4b9ae4fc-e96b-11e6-8943-45799a96faf0.png" alt="" />

**Comment by levrik** [comment]
I think that's not an issue with Electron but with [`electron-builder`](https://github.com/electron-userland/electron-builder)

**Comment by groundwater** [comment]
Hi @binjospookie can you give us information about how you are installing the Electron app? Ideally, please give us the steps you took, so that we can try to reproduce the error.

What happens when you double click the app? Does it display any kind of error message?

**Comment by binjospookie** [comment]
@groundwater Hi! I build my app with electron-builder. My <a href="https://gist.github.com/binjospookie/7358d8b0427d4af8cd5e394478ce29f7">package.json</a>. The app installed fine(without errors).

If you need more information, just ask me.

**Comment by MarshallOfSound** [comment]
@groundwater @binjospookie This sounds like an `electron-builder` issue.  I would suggest you raise it over on that repository 👍 

https://github.com/electron-userland/electron-builder

**Comment by binjospookie** [comment]
@MarshallOfSound you're right! Sorry for this.

**Comment by levrik** [comment]
@binjospookie I already wrote that, but yeah, ignore me :D
