### ISSUE TITLE
Support "spellcheck=true" attribute

### ISSUE THREAD

**Issue by tcaer** [electron/electron#8567]
* Electron version: 1.14.15
* Operating system: Mac OS X 10.12.3

### Expected behavior
Like Chromium, spellcheck='true' html attribute should highlight user input which does not have correct spelling.

### Actual behavior
Nothing happens...

### How to reproduce
<div contenteditable='true' spellcheck='true'></div>

I understand that this is actually a feature left out of electron on purpose, but please put it in. I have seen a couple of people who also wanted to use it.

**Comment by groundwater** [comment]
Hi @morlauth we will review this request. Review typically occurs within 7 days. We will try to get you an update by then.

**Comment by morlauth** [comment]
Perfect! Thanks!

**Comment by paulcbetts** [comment]
@morlauth the electron-spellchecker module is attempting to solve this problem in a very developer-friendly fashion, this probably will help you out

**Comment by morlauth** [comment]
I have looked at this module and it does seem like a good solution. But I still think that he spellchecking functionality baked-in to chromium should be used.

Thanks!

**Comment by baldwmic** [comment]
I agree with @morlauth. It would be awesome to have electron respect the [`spellcheck`](http://caniuse.com/#search=spellcheck) attribute that Chromium already ships

**Comment by codebytere** [comment]
This now works given that Electron ships Chromium's native spellchecker.
