### ISSUE TITLE
window 8 BrowserWindow.setResizable(false)，Double click window，will full screen.it's bug?

### ISSUE THREAD

**Issue by jimtang9527** [electron/electron#857]
window 8 
var window = new BrowserWindow(resizable:false,xxxx});
window can't resize,but double click window,will full screen.it's bug?

test in mac/linux it's ok.

**Comment by shawkinsl** [comment]
I'm getting this issue again in 1.7.6. I can't find the code for the fix that resolved this issue in the current codebase,,,

**Comment by oysteingr** [comment]
Also seeing this issue again on 1.8.2

**Comment by 88maomao** [comment]
Same issue on 1.8.4

**Comment by Fxlr8** [comment]
Windows treats all elements with `-webkit-app-region: drag` like the title bar. Any mouse events won't get passed to the DOM and double click event will try to maximize the window ignoring `maximazable`, `fullscreenable` and `resizable` configs.

**Comment by ifengzp** [comment]
you can fix that by  win.setFullScreenable(false);win.setMaximizable(false); win.isResizable(false);

**Comment by shion-pro** [comment]
thanks!!!

**Comment by ryz418** [comment]
> you can fix that by win.setFullScreenable(false);win.setMaximizable(false); win.isResizable(false);

works for me. 
Thanks
