### ISSUE TITLE
Please provide a compiled arm64 version of the release

### ISSUE THREAD

**Issue by jeanbruder** [electron/electron#8571]
Dear team,

Trying to install Mirror² on a Pine64 board running the Ubuntu longsleep version (arm64), but no package is provided in the 1.4.15 release section. Could you please provide such a package ? The installation script for Mirror² requests to download the following zip file : https://github.com/electron/electron/releases/download/v1.4.15/electron-v1.4.15-linux-arm64.zip !

Many thanks in advance as this may help lot of people,
Best regards,
Jean

**Comment by kevinsawicki** [comment]
arm64 support in Electron is being tracked in https://github.com/electron/electron/issues/5706, please subscribe to that issue for updates.
