### ISSUE TITLE
tray menu question

### ISSUE THREAD

**Issue by willin** [electron/electron#8577]
* Electron version: 1.4.15
* Operating system: OS X 10.12.3

### Expected behavior

<img width="132" alt="wx20170203-114812 2x" src="https://cloud.githubusercontent.com/assets/1890238/22578861/c5e49582-ea06-11e6-9ea6-b290d3bdc509.png">

Try + Menu 

### Actual behavior

<img width="110" alt="wx20170203-115025 2x" src="https://cloud.githubusercontent.com/assets/1890238/22578886/f8be2126-ea06-11e6-9524-375f9ba2eca7.png">

### How to reproduce

```js
const contextMenu = Menu.buildFromTemplate([

    {
      label: '默认',
      type: 'checkbox',
      checked: true
    },
    {
      label: '文件夹',
      type: 'normal',
      icon: path.join(__dirname, '../assets/folder.png'),
      enabled: false
    },
    {
      label: 'Remove',
      type: 'normal',
      click() {
        appIcon.destroy();
      }
    }
  ]);
```

How to change the icon position like the first image

**Comment by groundwater** [comment]
Hi @willin can you explain more about what bug you're experiencing? Or can you provide a more thorough reproduction case?

**Comment by willin** [comment]
![](https://cloud.githubusercontent.com/assets/1890238/22578886/f8be2126-ea06-11e6-9524-375f9ba2eca7.png)

look at the `folder` icon position.  there is some white space enough for a '√' symbol.  i'd like to remove the white space, how to do?

**Comment by groundwater** [comment]
Hey @zeke I think this might be a support request, but perhaps we can quickly check if it's a bug/bad-docs with the menu API?

@willin for support, we recommend asking in [discuss.atom.io](http://discuss.atom.io/). If you find a bug, or have a new feature request, you can discuss that here.

**Comment by zeke** [comment]
@willin I don't think it's possible to adjust the positioning of a MenuItem. To handle the `dev/prod` toggling option, you might consider using the `radio` type or a [`submenu`](https://electron.atom.io/docs/api/menu-item/).

There is not a way to add a popup with custom content as in your screenshot above. Your best option would be to open a BrowserWindow containing that content when the user clicks the MenuItem.
