### ISSUE TITLE
Tray icon shows a blank square with 'X' when updating icon

### ISSUE THREAD

**Issue by averissimo** [electron/electron#8582]
* Electron version: 1.4.15
* Operating system: Ubuntu 17.05 (also reported in 16.10)

### Expected behavior

Tray icon changes without an intermediate image/artifact

### Actual behavior

![outphkfc5l8rt](https://cloud.githubusercontent.com/assets/211358/22598140/5e2aa21e-ea2a-11e6-93dd-fa742397a475.gif)

### How to reproduce

Checkout https://github.com/averissimo/electron-boilerplate/tree/refresh (branch refresh)

And run electron app (it will update tray icon every second to demonstrate bug)

```
$ git clone git@github.com:averissimo/electron-boilerplate.git
$ cd electron-boilerplate
$ git checkout refresh
$ cd boilerplate
$ npm install
$ npm start
```

This is also reproducible in the renderer (where it first was reported: https://github.com/yakyak/yakyak/issues/575 )

_edit_: added npm install step

**Comment by groundwater** [comment]
Hi @averissimo I gave this a quick try in Ubuntu 16.04.1 and all I can see is a question-mark (?) icon.

I will spend some more time to review this in the next week. If you are able to help diagnose this problem in further detail, that will definitely help fix the bug sooner. We appreciate all the help we can get.

**Comment by averissimo** [comment]
just after submitting I noticed I had absolute path to an icon in `boilerpolate/index.js` -_- rookie mistake, can you confirm that's it?

a simple pull should fix this and be able to run

**Comment by groundwater** [comment]
Hey @averissimo, I tried pulling, but I don't see any changes. Still the `refresh` branch?

**Comment by averissimo** [comment]
Then I have no idea on what it is.

The code to replicate this should be very straightforward, all you need is:

- create a tray icon and set an image
- then set it again every second or so.

Code that in theory should have worked is here from line 50

https://github.com/averissimo/electron-boilerplate/blob/refresh/boilerplate/index.js#L50

ps. I'm sorry my code does not run on your system, but can't figure out why. I just tried again with a clean checkout and `npm install` and works as it should

**Comment by tonyganch** [comment]
I believe it may be somehow related to #6301

**Comment by groundwater** [comment]
Let's merge this into #6301
