### ISSUE TITLE
desktopCapturer - Recording full-screen game windows?

### ISSUE THREAD

**Issue by jacob-cross99** [electron/electron#8588]
Whenever I'm trying to record the window of a full screen game I get a black screen from the recording source.

**Comment by groundwater** [comment]
Hi @jacob-cross99, if you'd like to report a bug please follow the provided bug template. A description like this is near-impossible to help with. The more information you can provide, and the sooner we can reproduce the same error the more likely it will be that your bug is fixed. Cheers.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
