### ISSUE TITLE
Failed to record audio + screen due to error ScreenCaptureError

### ISSUE THREAD

**Issue by siman** [electron/electron#8589]
* Electron version: `electron 1.5.0`
* Operating system: `Ubuntu 14.04.3 LTS`

### Expected behavior

Successfully recorded video of a screen + **audio**.

### Actual behavior

In `handleUserMediaError` I receive an error: 

```js
NavigatorUserMediaError {name: "ScreenCaptureError", message: "", constraintName: ""}
```

### How to reproduce

My code when trying to record video + audio.
I follow instructions from the [documentation](https://github.com/electron/electron/blob/master/docs/api/desktop-capturer.md) for `webkitGetUserMedia`:

> To capture both audio and video from the entire desktop the constraints passed
to [`navigator.webkitGetUserMedia`] must include `chromeMediaSource: 'screen'`,
and `audio: true`, but should not include a `chromeMediaSourceId` constraint.

```js
navigator.webkitGetUserMedia({
  audio: true,
  video: {
    mandatory: {
      chromeMediaSource: 'screen',
      minWidth: 1280,
      minHeight: 720,
    }
  }
}, handleStream, handleUserMediaError);
```

**Comment by askucher** [comment]
+1 for mac as well

**Comment by groundwater** [comment]
Thanks for the report @siman, I have verified on Ubuntu 16.04 as well.

**Comment by siman** [comment]
@groundwater is electron's recording of audio supposed to record only webpage's sound, but not the mic?

**Comment by askucher** [comment]
@siman Please try 

```
sudo apt-get install alsa-utils
```

**Comment by siman** [comment]
I have found a solution. Read here: https://github.com/muaz-khan/RecordRTC/issues/181

Here is a code that starts to record video+audio in Electron:

```js
let recorder;
let blobs = [];

function captureScreenVideoWithAudio() {
  navigator.webkitGetUserMedia({
    audio: true
  }, function(audioStream) {
    navigator.webkitGetUserMedia({
      audio: false,
      video: {
        mandatory: {
          chromeMediaSource: 'screen',
          minWidth: 1280,
          minHeight: 720
        }
      }
    }, handleVideoStream(audioStream), handleUserMediaError);
  }, function() {});
}

function handleVideoStream(audioStream) {
  return function(videoStream) {
    if (audioStream) {
      let audioTracks = audioStream.getAudioTracks();
      if (audioTracks.length > 0) {
        videoStream.addTrack(audioTracks[0]);
      }
    }
    recorder = new MediaRecorder(videoStream);
    blobs = [];
    recorder.ondataavailable = function(event) {
      blobs.push(event.data);
    };
    recorder.start();
  };
}

function handleUserMediaError(e) {
  console.error('handleUserMediaError', e);
}
```

**Comment by kevinsawicki** [comment]
> I have found a solution.

Great thanks for the updates, closing this out 👍

**Comment by CapOM** [comment]
Does it work to stream system audio ? (so not from the microphone but from anything that goes to default output)

**Comment by DamienDoumer** [comment]
though the above solution makes it possible to record microphone sound and mix it to the video stream, It does not permit you to get **System Sound** on MacOS. I resolved this issue using Soundflower and a modified the code above to accomplish what I wanted. In case anybody wants a solution to record system audio and video on MacOS, [here is a detailed blog post about accomplishing this](https://doumer.me/record-system-sound-on-macos-with-javascript-and-soundflower/):
