### ISSUE TITLE
Calling BrowserWindow.setMenu when menu is open leads to crash

### ISSUE THREAD

**Issue by rprichard** [electron/electron#859]
Calling BrowserWindow.setMenu can leads to a crash if the window's menu is open at the time of the call.  I've noticed this problem on both Windows and Linux.

Test case:

    var app = require("app");
    var Menu = require("menu");
    var MenuItem = require("menu-item");
    var BrowserWindow = require("browser-window");
    var bw = null;
    app.on("ready", function() {
        bw = new BrowserWindow({ width: 300, height: 300 });
        bw.loadUrl("about:blank");
        function createMenu() {
            console.log("Creating menu!");
            var menubar = Menu.buildFromTemplate([
                    { label: "File1", submenu: [ { label: "Regenerate", click: createMenu } ]},
                ]);
            setTimeout(function() {
                bw.setMenu(menubar);
            }, 1000);
        }
        createMenu();
    });

Steps to reproduce:
1. Click File1, then Regenerate.
2. Quickly (less than a second later), click File1 again and hover the mouse over Regenerate.
3. A second after clicking Regenerate, the menubar redraws itself as though it weren't open, but the menu remains open.
4. Clicking File1 again sometimes crashes atom-shell, but not always.

Here's a video demonstrating the problem:  http://youtu.be/PHV7KbglbPQ

(The setTimeout call is contrived, but it imitates what's happening in my app, where the app asynchronously updates the menu from the renderer process.)

Perhaps the menu should not be updated while it is open?

**Comment by zcbenz** [comment]
Can no longer reproduce in 0.37.x.
