### ISSUE TITLE
Does not work CSS animation for svg

### ISSUE THREAD

**Issue by maksimr** [electron/electron#8591]
* Electron version: 1.4.15
* Operating system: macOs

### Expected behavior

CSS Animation should work for SVG

### Actual behavior

Animation does not work

### How to reproduce

1. Copy index.html and wow_animated.svg to the elector project [1]
2. Open index.html

[1] - [link on index.html and wow_animated.svg](https://gist.github.com/maksimr/43f6d224fa92a802225db39239b218a2)

Thanks

**Comment by groundwater** [comment]
First, I ❤️ the repro-case that I can just clone into a VM and run.

Thanks for the report. I've confirmed the behavior - despite not really knowing much about animated SVGs. I'm going to assign a reviewer who will take a deeper look, and try to figure out what should be happening.

**Comment by deepak1556** [comment]
I am unable reproduce the problem with `1.5.0` and `1.6.0` seems like it was fixed with chrome54 upgrade. @maksimr can you try the `1.5.0` ?

**Comment by maksimr** [comment]
@deepak1556 in version `1.5.0` all work as expected!

Thanks

**Comment by zeke** [comment]
Thanks, @deepak1556!
