### ISSUE TITLE
is it possible to use electron render process only with none electron based main process?

### ISSUE THREAD

**Issue by hh9527** [electron/electron#8592]
* Electron version: any
* Operating system: any

### Expected behavior

It is not a bug, it is a question.
I want to use electron renderer process only with a none electron based main process(I am using rust).
I don't know how to do this:
- how to start a render process with system spawn mechanism?
- how to communication with renderer process with IPC? (what is the protocol?)

**Comment by MarshallOfSound** [comment]
I do not believe this is possible as the main process does a lot of communication behind the scenes to manage renderer processes.  Will defer to someone else to confirm my thoughts 👍 

Your best bet would be to make a simple `main.js` that simply launches a renderer process and then pipes all messages to and from the renderer process.

**Comment by paulcbetts** [comment]
@hh9527 What's your end-goal? I suspect what you want to _do_ is possible though not perhaps in the way you're imagining at the moment

**Comment by groundwater** [comment]
Going to close this - it sounds like a question better tarted towards discuss.atom.io forum or the atomio.slack.com chat.
