### ISSUE TITLE
Sometimes, electron application disappears from the task view

### ISSUE THREAD

**Issue by Lcy-RITS** [electron/electron#8594]
* Electron version: 1.4.15 (0.37.5)
* Operating system: windows 10

### Expected behavior

After pressing Windows Key+Tab, electron application can always be displayed in the task view.
![1](https://cloud.githubusercontent.com/assets/25579512/22640348/2d714f0a-ec8d-11e6-9f71-9a009467d60e.png)

### Actual behavior

After pressing Windows Key+Tab, sometimes, electron application disappears from the task view.
Reproduction rate：>50%
![2](https://cloud.githubusercontent.com/assets/25579512/22640352/33b2fabc-ec8d-11e6-9a30-e436c532ca8b.png)

### How to reproduce

1. Create application window as follow.
`	mainWindow = new BrowserWindow({
		kiosk: true
	});`
or 
`	mainWindow = new BrowserWindow({
		fullscreen: true
	});`

2. Start up the application.

3. Keep the application in the front of all the other applications.

4. Pressing Windows Key+Tab.

### Other information
1. If the application is not fullscreen, there is no problem.
2. Other applications does not have this problem.

**Comment by dyb-lcy** [comment]
The problem can be reproduced on version 1.4.15 too.

**Comment by zeke** [comment]
I'm not able to reproduce this problem on Windows 10 with Electron 1.4.15.

Can you try [this branch](https://github.com/zeke/electron-quick-start/commits/issue-8594) and see if the problem exists there?

```sh
git clone https://github.com/zeke/electron-quick-start                
cd electron-quick-start 
git checkout issue-8594
npm install
npm start
```

**Comment by zeke** [comment]
Hi @Lcy-RITS, were you able to reproduce the problem using the steps I shared above?

**Comment by Lcy-RITS** [comment]
Hi @zeke,
Yes, I reproduce the problem using the branch.
But the reproduction rate is reduced to about 5%.

**Comment by zcbenz** [comment]
This is very likely a problem of Windows 10 because apps have no control of the task view at all, I suggest reporting this to Microsoft instead.
