### ISSUE TITLE
Error install Electron

### ISSUE THREAD

**Issue by Cienlim612** [electron/electron#8595]
cienl@DESKTOP-DAK3KLI MINGW64 ~
$ npm install electron-prebuilt -g
npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed                                                                                                                 to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-                                                                                                                install-electron
C:\Users\cienl\AppData\Roaming\npm\electron -> C:\Users\cienl\AppData\Roaming\np                                                                                                                m\node_modules\electron-prebuilt\cli.js

> electron-prebuilt@1.4.13 postinstall C:\Users\cienl\AppData\Roaming\npm\node_m                                                                                                                odules\electron-prebuilt
> node install.js

C:\Users\cienl\AppData\Roaming\npm\node_modules\electron-prebuilt\install.js:22
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cienl\\AppData\\                                                                                                                Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron-prebuilt"                                                                                                                 "-g"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.4.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@1.4.13 postinstall script 'node install                                                                                                                .js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt pac                                                                                                                kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cienl\npm-debug.log

**Comment by enlight** [comment]
Something is wrong with your connection, try again later.
