### ISSUE TITLE
Support clearing a menu

### ISSUE THREAD

**Issue by pronebird** [electron/electron#8598]
* Electron version: 1.50
* Operating system: macOS

Tray menu accumulates items internally even if `Menu.items` is being reset. `Menu.items.length` reports the right number of items, however `tray.setContextMenu` appears to append items to tray menu as opposed to replacing them entirely.

### Expected behavior

<img width="85" alt="screenshot 2017-02-06 18 51 19" src="https://cloud.githubusercontent.com/assets/704044/22661429/45489948-ec9d-11e6-879a-1f7553f2a7d0.png">

### Actual behavior

<img width="95" alt="screenshot 2017-02-06 18 47 48" src="https://cloud.githubusercontent.com/assets/704044/22661353/fbf52aea-ec9c-11e6-8bf9-cae0a25762e4.png">

### How to reproduce

```js
import { remote } from 'electron';
const { Menu, MenuItem } = remote;
const iconPath = path.join(__dirname, 'assets/trayicon.png');
const tray = new remote.Tray(iconPath);
const contextMenu = new Menu();

for(let i = 0; i < 2; i++) {
  // erase existing elements in menu
  contextMenu.items = [];
  
  // sanity check
  console.log('How many items we have? ', contextMenu.items.length);
 
  // add new items
  contextMenu.append(new MenuItem({ label: "item 1" }));
  contextMenu.append(new MenuItem({ label: "item 2" }));

  // update tray menu
  tray.setContextMenu(contextMenu);
}
```

### Workaround

Use new instance of `Menu` for each update.

**Comment by kevinsawicki** [comment]
Clearing/modifying the `items` array directly isn't currently supported.

The `items` array represents the model in the JavaScript class but there are still C++ objects as well that are still in the model after the `items` array is cleared/modified.

**Comment by kevinsawicki** [comment]
There is a `clear` API on `Menu` that isn't public and clears only the C++ side, we could update it to make it clear both the items and C++ menu model and make it public.

**Comment by pronebird** [comment]
That makes sense. Although if

**Comment by pronebird** [comment]
That makes sense. Other improvement could be to add methods for modifying menu such as insert or remove. Items array should probably be read only.

**Comment by kevinsawicki** [comment]
> Other improvement could be to add methods for modifying menu such as insert 

There is append and insert in the API already, but no remove.

http://electron.atom.io/docs/api/menu/#menuappendmenuitem

**Comment by bsclifton** [comment]
I'm guessing the root cause for this is similar to https://github.com/electron/electron/issues/527

**Comment by zcbenz** [comment]
I'm merging this to  #527.
