### ISSUE TITLE
net::ERR_REQUEST_RANGE_NOT_SATISFIABLE when playing a sound

### ISSUE THREAD

**Issue by Zamiell** [electron/electron#8603]
* Electron version: 1.4.15
* Operating system: Windows 7 Professional

### Expected behavior

Should play a sound without getting an error message in the console.

### Actual behavior

Plays a sound, but shows an error message in the console.

### How to reproduce

Nothing super extraordinary going on here. I made a new Electron project based on the `electron-quick-start` repository. Then, I played some sounds with JavaScript in the renderer process with:

```
let audio = new Audio('assets/sounds/go.mp3');
audio.play();
```

This works around 95% of the time. But occasionally, I get the following errors:

![eyq4taq](https://cloud.githubusercontent.com/assets/5511220/22668039/40fe62f6-ec8d-11e6-85c6-d56b1d10c8b4.png)

When these errors occur, the sound does appear to actually play successfully, but then I get around 12 of these "net::ERR_REQUEST_RANGE_NOT_SATISFIABLE" errors in the console window.

My first instinct was that it had something to do with the files being in an ASAR archive, but I don't see how that could be the case, as the problem happens in both development and production. (Development meaning when I'm just testing out the Electron project with "npm start" and nothing is in an ASAR archive yet.)

I did some searching and apparently there is absolutely nothing on Google about this specific error, so it seems that I have a unique one here.

**Comment by kevinsawicki** [comment]
> This works around 95% of the time. But occasionally, I get the following errors

Are you reloading your app in an open window when this happens or does it sometimes happen on first launch?

> Then, I played some sounds with JavaScript in the renderer process with

Are you able to provide the `.mp3` you are having issues with?

**Comment by Zamiell** [comment]
Sure.

[go.zip](https://github.com/electron/electron/files/791103/go.zip)

**Comment by Zamiell** [comment]
Am I reloading the app in an open window? Yes, I do that pretty often during development, since there's no need to kill the entire thing when I'm tweaking renderer-side JavaScript.

I'm not 100% sure if it happens on first launch, but I'll do a bit of testing and get back to you.

**Comment by Zamiell** [comment]
It DOES appear to be happening on a first launch.

(Probably important addendum: To confirm this, I was testing on a 2nd copy of the app - I have two copies of my application open at the same time for testing purposes. However, it is possible for the bug to appear while only using 1 copy of the app.

I'm not sure if having multiple copies of the app trying to play the same sound at the same time increases the frequency of the bug occurring. It may, or it may not.)

**Comment by Zamiell** [comment]
Oh, another thing: When testing with 2 copies of the app, the errors only appeared on one copy, and not the other one.

**Comment by Zamiell** [comment]
Yet another thing. I'm using the following code snippet to play sounds:

```
try {
    let audio = new Audio(fullPath);
    audio.play();
    log.info('Played "' + fullPath + '".');
} catch(err) {
    globals.log.info('Failed to play "' + fullPath + '":', err);
}
```

The failure message is NEVER played when the error occurs, so the try/catch block here appears to be completely useless. The try/catch block should catch the error right? Not sure if this is a separate bug, or related?

**Comment by Zamiell** [comment]
Another thing: In the OP, I said that it tries for "around 12 errors", but the amount of errors appears to be random. I just got it 21 times before it decided to give up.

**Comment by kevinsawicki** [comment]
@Zamiell can you try this out in Electron 1.6.1, I'm seeing an error get logged after lots of reloads but it is different than the one you reported.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script>
      let audio = new Audio('/Users/kevin/Downloads/go.mp3')
      audio.play().catch(function (error) {
        console.log(error.message)
      })
    </script>
  </head>
  <body>

  </body>
</html>
```

<img width="795" alt="screen shot 2017-02-21 at 4 11 29 pm" src="https://cloud.githubusercontent.com/assets/671378/23191118/bba1ff8a-f850-11e6-8a4a-07e549a1122f.png">

**Comment by Zamiell** [comment]
I upgraded to 1.6.1 yesterday but I haven't been able to reproduce the error yet. I'll keep trying and report back if I can get it to happen.

**Comment by kevinsawicki** [comment]
> I'll keep trying and report back if I can get it to happen.

Closing this out for now 👍

**Comment by AlexanderKosianchuk** [comment]
Got the same "net::ERR_REQUEST_RANGE_NOT_SATISFIABLE" in case trying to play empty media files. So please check content of media getting this.

**Comment by dattasabne** [comment]
correct
