### ISSUE TITLE
coffee-script register fails on 1.6.0 & 1.5.1

### ISSUE THREAD

**Issue by KagamiChan** [electron/electron#8611]
* Electron version: 1.6.0 / 1.5.1
* Operating system: Windows 10 x64

### Expected behavior
Coffee-script won't fail with `require('coffee-script').register()` or `require('coffee-script/register')`

### Actual behavior
Coffee-script fails to register

### How to reproduce

1. Download the `Electron-quick-start` app
2. install `coffee-script` via `npm i --save coffee-script`
2. Add a register line in `index.html`, for example,
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    <!-- All of the Node.js APIs are available in this renderer process. -->
    We are using Node.js <script>document.write(process.versions.node)</script>,
    Chromium <script>document.write(process.versions.chrome)</script>,
    and Electron <script>document.write(process.versions.electron)</script>.
  </body>

  <script>
    // You can also require other files to run in this process
    require('coffee-script').register()
    require('./renderer.js')
  </script>
</html>
```

(`require('coffee-script').register()` and `require('coffee-script/register')` will give the same result)

4. launch the app with Electron 1.5.1 / 1.6.0, error message will appear in `Console` tab
![image](https://cloud.githubusercontent.com/assets/3816900/22677722/d8d41d1c-ed2f-11e6-8ebd-3ec8407c28d4.png)

![image](https://cloud.githubusercontent.com/assets/3816900/22678152/e7876136-ed32-11e6-95f5-d255dce12f76.png)

Error message on 1.6.0:
```
C:\Users\kagami\Documents\git\electron-quick-start\node_modules\coffee-script\lib\coffee-script\coffee-script.js:254 Uncaught TypeError: Cannot read property 'length' of undefined
    at C:\Users\kagami\Documents\git\electron-quick-start\node_modules\coffee-script\lib\coffee-script\coffee-script.js:254:26
    at C:\Users\kagami\Documents\git\electron-quick-start\node_modules\coffee-script\lib\coffee-script\coffee-script.js:425:4
    at Object.<anonymous> (C:\Users\kagami\Documents\git\electron-quick-start\node_modules\coffee-script\lib\coffee-script\coffee-script.js:427:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

```

While the same app won't throw any error on 1.5.0 and previous
![image](https://cloud.githubusercontent.com/assets/3816900/22678024/0546666e-ed32-11e6-9f02-85fbd0ace08e.png)

The lines related to this error in `coffee-script` are:

```javascript
  if (require.extensions) {
    ref = this.FILE_EXTENSIONS;
    fn1 = function(ext) {
      var base;
      return (base = require.extensions)[ext] != null ? base[ext] : base[ext] = function() {
        throw new Error("Use CoffeeScript.register() or require the coffee-script/register module to require " + ext + " files.");
      };
    };
    for (i = 0, len = ref.length; i < len; i++) {
      ext = ref[i];
      fn1(ext);
    }
  }
```

`this.FILE_EXTENSIONS` becomes `undefinded` but I have no idea how it happens

**Comment by gurkerl83** [comment]
Same here!

**Comment by MarshallOfSound** [comment]
@KagamiChan Does the coffee script register logic work in normal Node.JS `7.4.0`?

**Comment by KagamiChan** [comment]
@MarshallOfSound 
Yes it works
```
C:\Users\kagami\Documents\git\electron-quick-start>node
> process.version
'v7.4.0'
> require('coffee-script/register')
{}
>
```

**Comment by MarshallOfSound** [comment]
@kevinsawicki This looks like a regression due to https://github.com/electron/node/commit/f69137383ed14ac73e5d29cb1c75f3b6a144078f

Because we now return a function from within the wrapping function the `this` scope has changed thus `this.FILE_EXTENSIONS` has changed.  I believe a simple fix would be to change our patch in that commit to be.

```js
(function (exports, require, module, __filename, __dirname, process, global) { 
  return function (exports, require, module, __filename, __dirname) {
    // code
  }.call(this, exports, require, module, __filename, __dirname);
});
```

Haven't had time to test but I think that should do the trick

**Comment by KagamiChan** [comment]
@MarshallOfSound awesome, thank you for pointing it out. 
it works by manually modifying the wrapper code for `coffee-script.js` in the dev tools.

**Comment by KagamiChan** [comment]
Wondering if we could have a spec / test for this kind of packages, if `coffee-script` is not the only one that stops working ( I'm not sure though)

**Comment by kevinsawicki** [comment]
> This looks like a regression due to electron/node@f691373

Thanks for digging into this, will work on an update to that patch.

**Comment by kevinsawicki** [comment]
> Wondering if we could have a spec / test for this kind of packages, if coffee-script is not the only one that stops working ( I'm not sure though)

Great suggestion @KagamiChan, spec added in #8618 for `coffee-script`.
