### ISSUE TITLE
Is it a way to open devtools with my custom chrome extension inside a webview, not a window

### ISSUE THREAD

**Issue by wenshiqi0** [electron/electron#8612]
* Electron version: 1.6.0
* Operating system: Mac OS X 10.11.6

### Expected behavior

I want to open devtools with my chrome extension inside a webview.

### Actual behavior

I have used webview.openDevTools api, but it opens another window. We just want a webview to load another web page for preview and devtools for debug with a custom chrome extension.

Sorry to bother you, but is there any way to do this or electron just does not support this.

**Comment by MarshallOfSound** [comment]
@wenshiqi0 For non-webview renderer processes you can "dock" the devtools so they appear in the same window.  See the `mode` option for the `openDevTools` API

http://electron.atom.io/docs/api/web-contents/#contentsopendevtoolsoptions\

You currently can't dock dev tools inside a webview, see #7080 for more information on this

**Comment by jacklovepdf** [comment]
my answer:
`const browserContents = <webview>.getWebContents()
const devtoolsContents = <webview>.getWebContents()

browserContents.setDevToolsWebContents(devtoolsContents)
browserContents.debugger.attach();

browserContents.openDevTools({
  detach: true
})`

**Comment by swati-maheshwari** [comment]
> my answer:
> 
> ```
> const browserContents = webview.getWebContents()
> const devtoolsContents = webview.getWebContents()
> 
> browserContents.setDevToolsWebContents(devtoolsContents)
> browserContents.debugger.attach();
> 
> browserContents.openDevTools({
>   detach: true
> })
> ```

@jacklovepdf --in which file u kept this code?
