### ISSUE TITLE
Loop at start

### ISSUE THREAD

**Issue by UltraDosaaf** [electron/electron#8614]
* Electron version: 1.4.13
* NodeJS version: 6.9.5
* Operating system: Win 7 x64 (latest updates)
* Installed latest Visual C++ 2015

Electron just won't start, keep shooting this over and over:

```
C:\Users\it\Desktop\electron-app>cd C:\Users\it\Desktop\electron-app\   && npm start
> app@0.1.0 start C:\Users\it\Desktop\electron-app
> electron .

C:\Users\it\Desktop\electron-app>cd C:\Users\it\Desktop\electron-app\   && npm start
> app@0.1.0 start C:\Users\it\Desktop\electron-app
> electron .

C:\Users\it\Desktop\electron-app>cd C:\Users\it\Desktop\electron-app\   && npm start
> app@0.1.0 start C:\Users\it\Desktop\electron-app
> electron .
```

**package.json**
```
{
    "name": "app",
    "version": "0.1.0",
    "main": "app.js",
    "scripts": {
        "start": "electron ."
    },
    "dependencies": {
        "electron": "latest",
        "electron-prebuilt": "latest"
    }
}
```

**app.js** has taken from default 'Hello World!'.

Any clue how to make it work?

**Comment by UltraDosaaf** [comment]
Well, it looks like this causes all errors:
`        "electron-prebuilt": "latest"`

Using this solves the problem:
`        "electron-prebuilt": "0.37.6"`

**Comment by kevinsawicki** [comment]
Looks like you have both `electron` and `electron-prebuilt` in your `package.json, you only want one of them, they are the same package just with different names.

Can you include the content of your `app.js` file?

**Comment by UltraDosaaf** [comment]
**kevinsawicki**, you are right. Thank you!
