### ISSUE TITLE
can not scroll by touch. 

### ISSUE THREAD

**Issue by rmfvz** [electron/electron#8615]
* Electron version: 1.4.15
* Operating system: Windows 10

### Expected behavior

The category (assortiment) element should be scrolling the items if we scroll by swiping the screen (touch).  

### Actual behavior

After a while we cant scroll any more, it seems like the app thinks there is still a finger on the screen. So if we swipe the screen zooms in and out.

Drag the scrollbar by mouse work fine. 

We used first app.commandLine.appendSwitch('disable-pinch'); and then setVisualZoomLevelLimits(minimumLevel, maximumLevel)

Zooming is disabled. but now after a while scolling is freezing by swiping the screen. 

Drag the scrollbar by mouse works still fine. 

![screen](https://cloud.githubusercontent.com/assets/25608142/22687423/43ba43ca-ed28-11e6-8ee7-1956b4c1ad9d.gif)

**Comment by MarshallOfSound** [comment]
@rmfvz Can you test to see if either the Electron `1.6.0` beta has this issue, it just a significant Chromium version bump that could help out.

My net's a bit slow to do a search through Chromium issues but it seems like the kind of thing that Chromium would be responsible for 👍

**Comment by rmfvz** [comment]
We tried already. We tested in chrome 53 54 55 56 and 57. Always the same problem.

**Comment by levrik** [comment]
@rmfvz If you tried it in Chrome that's a Chromium bug and not related directly to Electron. Needs to be fixed upstream then.

**Comment by felixrieseberg** [comment]
@rmfvz Sorry for your trouble - @levrik and @MarshallOfSound are completely correct here, we sadly won't be able to fix bugs that are part of Chromium itself. I'm closing this issue to keep our issues "cleanish", but feel free to ping me if I misunderstood and this is indeed a bug exclusive to Electron. Thank you for the detailed report!
