### ISSUE TITLE
'scroll-touch-end' not emitted in 1.6.0

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#8621]
* Electron version: 1.6.0
* Operating system: MacOS 10.12.2

### Expected behavior

'scroll-touch-end' emits when trackpad scrolling ends.

### Actual behavior

The begin event emits, but not the end

### How to reproduce

Example repo: https://github.com/pfrazee/electron-bug-no-scroll-touch-end

**Comment by javan** [comment]
Confirmed
