### ISSUE TITLE
BrowserWindow freezed when using chrome argument --use-gl=desktop

### ISSUE THREAD

**Issue by adahbingee** [electron/electron#8627]
* Electron version: win 1.6.0 x64
* Operating system: windows 7 64bit

For the reason I want to draw lineWidth with three.js, I need to use --use-gl=desktop argument for chrome
Instead ANGLE WebGL driver, must use native OpenGL.

`app.commandLine.appendSwitch('use-gl', 'desktop');`
Works. but there are some bugs with BrowserWindow 

Works without  bugs when using electron 1.4.15 & 1.5.1

### Expected behavior

Normal behavior move window.

### Actual behavior

The BrowserWindow freezed when trying to move them by dragging the window title bar.

### How to reproduce

**main.js**
```
const electron    = require('electron')
const app           = electron.app
app.commandLine.appendSwitch('use-gl', 'desktop');
```

**Comment by brenca** [comment]
Using the `--enable-logging` switch I got these lines (multiples of the second):
```
[20280:0309/231458.912:ERROR:mf_helpers.cc(12)] Error in dxva_video_decode_accelerator_win.cc on line 297
[20280:0309/231459.029:ERROR:gl_context_wgl.cc(77)] Could not share GL contexts.
```

**Comment by zcbenz** [comment]
This looks like a bug of Chromium, while we would like to fix it, I'm afraid non of us is familiar well enough with Chromium's GPU rendering to be able to solve this, and I'm closing this as won't fix.
