### ISSUE TITLE
Using parent property on BrowserWindow ignores explicitly set skipTaskbar

### ISSUE THREAD

**Issue by dogancelik** [electron/electron#8637]
* Electron version: 1.4.15
* Operating system: Windows 8 64-bit

### Expected behavior

I have `mainWindow` and child windows opened from *mainWindow*, I set `parent` property when creating child windows so my child windows know who's the parent.

I set `skipTaskbar: false` while creating children windows yet Electron ignores this and doesn't show anything in taskbar and when you minimize the child window, it goes to left bottom corner (because it doesn't have taskbar item) like in the screenshot below.

![min2](https://cloud.githubusercontent.com/assets/486818/22764499/b8709646-ee73-11e6-8727-3fe90009cf63.jpg)

### Actual behavior

Parent should not affect any other property other than defining who's parent. Child window should appear in taskbar when `skipTaskbar: false` is set or not (because default value is also *false*)

### How to reproduce

```js
const electron = require('electron');
const app = electron.app;

// Main window
var mainWindow;

// my custom child window
class MyBrowserWindow extends electron.BrowserWindow {
  constructor (opts) {
    let size = mainWindow.getSize();
    super({
      parent: mainWindow,
      width: size[0],
      height: size[1],
    });
  }
}

// new-window event function
var newWindow = function (e, url, frame, dis, opts) {
  e['newGuest'] = new MyBrowserWindow();
  e['newGuest'].webContents.on('new-window', newWindow);
  e['newGuest'].loadURL(url);
  e.preventDefault();
};

app.on('ready', function() {
  mainWindow = new electron.BrowserWindow({
    webPreferences: {
      nodeIntegration: false,
      webSecurity: false,
      plugins: true,
    }
  });
  mainWindow.loadURL('https://tweetdeck.twitter.com/');
  const page = mainWindow.webContents;
  page.on('new-window', newWindow);
});
```

If you want to try in a real app, you can test in my TweetDeck app: https://github.com/dogancelik/atomic-tweetdeck/releases/latest

**Comment by dogancelik** [comment]
You can produce this with/without *component/tray* so this is a BrowserWindow bug, not tray 😕

**Comment by dogancelik** [comment]
You can produce this with or without a **component/tray** so I believe it's a **BrowserWindow bug**.
Updated example with full code.
I will be happy if you can take a look @zcbenz

**Comment by zcbenz** [comment]
That's how child windows work on Windows and there is no way to change that behavior, in your case you would probably want to hide the window instead of minimizing it.

**Comment by dogancelik** [comment]
How are we going to reference child windows if we have multiple parent windows?
