### ISSUE TITLE
Is it possible to specify the userData directory for each browserwindown instance?

### ISSUE THREAD

**Issue by c517718004** [electron/electron#8639]
Is it possible to specify the userData directory for each browserwindown instance?

**Comment by kevinsawicki** [comment]
You can only set this directory application-wide by using the `app.setPath` API, not on a per renderer process basis.

http://electron.atom.io/docs/api/app/#appsetpathname-path

**Comment by TimNZ** [comment]
Would Partitions achieve the desired result?

**Comment by TimNZ** [comment]
@kevinsawicki Want to confirm if Partitions on BrowserWindow would achieve this?

**Comment by enlight** [comment]
@TimNZ I'm not sure what you're asking, as Kevin said `app.setPath` can only be used to set paths for the entire app not a given window/view, nor can you set those paths per partition.

**Comment by TimNZ** [comment]
@enlight No-one asked the issue creator why they wanted a separate userData dir.

Either for some reason they want to spread userData dir around the filesystem (why?), or they want to do it for isolated partitions between BrowserWindow instance in the same app.

I should been explicit in saying 'if scenario #2 would Partitions do the job?...'.

**Comment by TimNZ** [comment]
I have spent a long time doing BA, requirements, scoping etc and it usually pays to ask for the root reason for a question if it could be a number of reasons.
