### ISSUE TITLE
win.previewFile(path[, displayName])

### ISSUE THREAD

**Issue by Bruno-de-l-Escaille** [electron/electron#8642]
* 1.5.0:
* OSX 10.11.6:

### win.previewFile(path[, displayName])
You have introduced this function to support mac quicklook, but no reel documentation how to use it! with native mac app you must develop a quicklook plugin but with this function what must we do. Call it when a event is fired or what exactly?

**Comment by MarshallOfSound** [comment]
@Bruno-de-l-Escaille I think there's a bit of confusion here

`win.previewFile` is used to launch quicklook on a given file, not provide a quicklook plugin from your application.  I.e. Calling `previewFile` on a path will result in the quicklook window being opened for that path

Let me know if I've misunderstood what you mean
