### ISSUE TITLE
win.previewFile(path[, displayName])

### ISSUE THREAD

**Issue by elhachmi** [electron/electron#8643]
* Electron version: 1.5.0
* Operating system: OSX 10.11.6

### win.previewFile(path[, displayName])

You have introduced this function to support mac quicklook, but no reel documentation how to use it! with native mac app you must develop a quicklook plugin but with this function what must we do. Call it when a event is fired or what exactly?

**Comment by MarshallOfSound** [comment]
@elhachmi  I think there's a bit of confusion here

`win.previewFile` is used to launch quicklook on a given file, not provide a quicklook plugin from your application.  I.e. Calling `previewFile` on a path will result in the quicklook window being opened for that path

Let me know if I've misunderstood what you mean

**Comment by elhachmi** [comment]
Yes I understand now, I was looking for a solution for providing a quick look to files associated to my app with electron, but I think that is not possible, by the way, can you recommande a simple solution to create that?

**Comment by kevinsawicki** [comment]
> By the way, can you recommande a simple solution to do that?

You may want to check out https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/Quicklook_Programming_Guide/Introduction/Introduction.html

and the sample here: https://developer.apple.com/library/content/samplecode/QuickLookSketch/Introduction/Intro.html

Closing this out.
