### ISSUE TITLE
npm Install electron -g fail ，need help ！

### ISSUE THREAD

**Issue by lake2** [electron/electron#8645]
* Electron version:v6.9.5
* Operating system:win10

### Expected behavior
install electron

### Actual behavior

encounter error

**Comment by kevinsawicki** [comment]
> encounter error

What error did you encounter? Can you include the output when running `npm install electron`?

**Comment by lake2** [comment]
Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

C:\WINDOWS\system32>npm install electron -g
C:\Users\LH\AppData\Roaming\npm\electron -> C:\Users\LH\AppData\Roaming\npm\node_modules\electron\cli.js

> electron@1.4.15 postinstall C:\Users\LH\AppData\Roaming\npm\node_modules\electron
> node install.js

C:\Users\LH\AppData\Roaming\npm\node_modules\electron\install.js:46
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron" "-g"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.15 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

[npm-debug.txt](https://github.com/electron/electron/files/765483/npm-debug.txt)

**Comment by KagamiChan** [comment]
In most cases it's an error caused by your network connection when trying to download the binary from github release / amazonaws
