### ISSUE TITLE
Use Electron version in Chromedriver asset name

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#8653]
Currently the Chromedriver version used in the release asset name is hard-coded [here](https://github.com/electron/electron/blob/5d0da398bf1b664d90816a2de8570db612019e37/script/lib/config.py#L45-L46).

`electron-download` saves assets to the cache by name so having multiple releases with the same asset name but different contents causes issues with the SHASUM checker since it finds the file in the cache from a past release but the new checksum does not match. You end up with an error like:

```
Error: Generated checksum for "chromedriver-v2.21-darwin-x64.zip" did not match expected checksum.
```

All other assets like `ffmpeg` and `mksnapshot` carry the Electron version in the asset name so I'd like to propose we follow the same for `chromedriver` to prevent this issue and for consistency.

Another option would be to bump the `chromedriver` to match the current released version which is 2.25 but that would still seem to leave the chance that that version would not change across Chrome upgrades so we may still end up with this issue in the future.

/cc @zcbenz

**Comment by zcbenz** [comment]
Sounds good to me.

**Comment by ajaks328** [comment]
Is there a solution for this checksum issue if have to use 1.6.x? We are unable to install the electron-chromedriver 1.6.x because of this.
