### ISSUE TITLE
net.request to self-signed https fails silently

### ISSUE THREAD

**Issue by jamgold** [electron/electron#8656]
* Electron version: 1.6.0
* Operating system: OSX 10.11.6

### Expected behavior
When I create a request to a web site with a self signed certificate, I would expect to at least get an error, or best case to be able to tell the app to ignore the certificate like I can with curl or wget

```
import {net} from "electron";

const req = net.request({
  method: "get",
  url: "https://www.pcwebshop.co.uk/"
});
// subscribe to various req events here
req.end();
```
### Actual behavior

the request doesn't emit any events and silently fails with no way of catching an error.

**Comment by deepak1556** [comment]
Merging this to https://github.com/electron/electron/issues/8074
