### ISSUE TITLE
[macOS] Fullscreen animation of webview not as good as browserWindow

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#8658]
* Electron version: 1.4.15 (and also 1.6.0 beta)
* Operating system: macOS 10.12.3

### Expected behavior

`webview.webContent` enter/leave fullscreen animation should be the same as `browserWindow.webContent` animation *(resize for final width, then fit in current width and progressively increase to reach final size as far as I know)*.

### Actual behavior

The `webview.webContent` size doesn't animate when entering/leaving fullscreen (it waits for the final size, then resize).

### How to reproduce

Below is a screen recording showing the problem with the Brave browser:
https://www.youtube.com/watch?v=7XPLCsMJgd8

- The menu (not native, it's html/css) on the top-right animates correctly (it's in the `browserWindow.webContent`)
- The Google page doesn't (it's in a webview).

Note: The `webview` element itself DOES animate correctly though, it's the `webview.webContent` that doesn't.

I've tried playing with the webview `autosize` and `disableguestresize` properties (and setting the webview.webContent size when the parent browserWindow resizes), same issue.

**Comment by zcbenz** [comment]
This looks like a Chromium issue, I'm not sure whether we can fix this on Electron's side.

**Comment by zcbenz** [comment]
I'm closing this since it requires considerate work of Chromium's side to implement this, and we don't have resources to do that.
