### ISSUE TITLE
click event not triggered in ContextMenu

### ISSUE THREAD

**Issue by ioncodes** [electron/electron#8661]
* Electron version: v1.4.15
* Operating system: Windows 10 x64

In my createWindow function which is used from the 'activate' and 'ready' event, I initialize a Tray object which has a ContextMenu, with 1 item, which is 'Exit'. It calls app.quit() but it never quits.

### Expected behavior
It should quit the application.

### Actual behavior
It just doesn't trigger.

### How to reproduce
I use this code:
```js
function createWindow () {
    tray = new Tray(__dirname + '/icons/icon.ico')
    const contextMenu = Menu.buildFromTemplate([
        {label: 'Exit', click () {
            app.quit() // not triggered
        }}
    ])
    tray.setToolTip('Open GitSpector')
    tray.setContextMenu(contextMenu)
    // ...
```
It's taken from the Electron example page.
The full source of my main.js can be found here: https://github.com/ioncodes/GitSpector/blob/master/main.js

**Comment by kevinsawicki** [comment]
@ioncodes having a little trouble reproducing this on Windows 10:

Here is the full app I use:

```js
const {app, Menu, Tray} = require('electron')
const path = require('path')

let tray

app.once('will-quit', () => {
  console.log('quitting')
})

app.once('ready', () => {
  tray = new Tray(path.join(__dirname, 'tray.ico'))
  const menu = Menu.buildFromTemplate([{
    label: 'Quit',
    click () {
      app.quit()
    }
  }])
  tray.setToolTip('Hello')
  tray.setContextMenu(menu)
})
```

I see `quitting` logged out when I right click on the taskbar and run the `Quit` menu item.

Can you try this app or provide a more complete example including the `.ico` file being used? Thanks.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
