### ISSUE TITLE
Render process ignores IPC messages sent before document creation

### ISSUE THREAD

**Issue by poiru** [electron/electron#8663]
In #1044 (specifically 0bcc9b7), we made the render process ignore IPC messages received before document creation. This unfortunately can and does causes subtle bugs.

For example, apply this patch:

```patch
diff --git a/lib/browser/api/browser-window.js b/lib/browser/api/browser-window.js
index 6528da1ba..75ea1a11e 100644
--- a/lib/browser/api/browser-window.js
+++ b/lib/browser/api/browser-window.js
@@ -11,6 +11,11 @@ BrowserWindow.prototype._init = function () {
   // Avoid recursive require.
   const {app} = require('electron')
 
+  setTimeout(() => {
+    console.log('send ELECTRON_TEST_SEND')
+    this.webContents.send('ELECTRON_TEST_SEND')
+  }, 200)
+
   // Simulate the application menu on platforms other than macOS.
   if (process.platform !== 'darwin') {
     const menu = app.getApplicationMenu()
diff --git a/lib/renderer/window-setup.js b/lib/renderer/window-setup.js
index 21f0741a2..e7003c23e 100644
--- a/lib/renderer/window-setup.js
+++ b/lib/renderer/window-setup.js
@@ -189,4 +189,8 @@ module.exports = (ipcRenderer, guestInstanceId, openerId, hiddenPage) => {
       return cachedVisibilityState
     }
   })
+
+  ipcRenderer.on('ELECTRON_TEST_SEND', function () {
+    console.log('recv ELECTRON_TEST_SEND')
+  })
 }
```

With no timeout or a low timeout (less than around 200ms for me), I get the following:

```
$ ELECTRON_ENABLE_LOGGING=true ./out/D/Electron.app/Contents/MacOS/Electron
send ELECTRON_TEST_SEND
```

With a higher timeout, I correctly get:

```
$ ELECTRON_ENABLE_LOGGING=true ./out/D/Electron.app/Contents/MacOS/Electron
send ELECTRON_TEST_SEND
[43890:0212/140843.100029:INFO:CONSOLE(194)] "recv ELECTRON_TEST_SEND", source: electron.asar/renderer/window-setup.js (194)
```

This is an issue at least for the `ELECTRON_RENDERER_WINDOW_VISIBILITY_CHANGE` message. If it's sent before document creation, `document.hidden` and `document.visibilityState` will be wrong until the state changes again. This can have serious implications for e.g. apps that use these values to determine when to perform work.

I think we should fix this generally and not just for `ELECTRON_RENDERER_WINDOW_VISIBILITY_CHANGE` since discarding messages like this can be dangerous. Maybe we could just keep track of messages sent before document creation and replay them in `AtomRenderViewObserver::DidCreateDocumentElement`? I'm happy to write the patch, I just wanted to discuss the approach first.

cc @kevinsawicki @zcbenz

**Comment by kevinsawicki** [comment]
> Maybe we could just keep track of messages sent before document creation and replay them in AtomRenderViewObserver::DidCreateDocumentElement?

This sounds like a good approach to try out 👍 

> I think we should fix this generally and not just for ELECTRON_RENDERER_WINDOW_VISIBILITY_CHANGE since discarding messages like this can be dangerous.

👍

**Comment by kevinsawicki** [comment]
Had another thought on this, perhaps if we do implement this we could add a property to the event emitted like `receivedBeforeDocumentCreation` or `replayed` so apps will know it is being replayed but were received at an earlier time.

It might make it easier to debug/inspect any timing issues related to supporting this.

**Comment by kevinsawicki** [comment]
This looks similar to #6828, merging into that one since it has more discussion and is older.
