### ISSUE TITLE
BrowserWindow `show` and `hide` events are inconsistent between platforms

### ISSUE THREAD

**Issue by poiru** [electron/electron#8664]
For example, with this script:

```js
const {app, BrowserWindow} = require('electron')

app.on('ready', () => {
  const win = new BrowserWindow()

  win.on('show', () => console.log('show'))
  win.on('hide', () => console.log('hide'))
  win.on('minimize', () => console.log('minimize'))
  win.on('restore', () => console.log('restore'))

  setTimeout(() => win.hide(), 500)
  setTimeout(() => win.show(), 1000)
  setTimeout(() => win.minimize(), 1500)
  setTimeout(() => win.restore(), 2000)
  setTimeout(() => app.quit(), 2500)
})
```

On Linux and Windows, you get:
```
hide
show
minimize
restore
```

On macOS, you get:
```
show
hide
show
minimize
hide
restore
show
```

This is because we use the window occlusion state to drive `show` and `hide` on macOS, but tie them to `BrowserWindow.show()` and `BrowserWindow.hide()` on other platforms.

Also note that `BrowserWindow.isVisible()` does *not* use the occlusion state. So on macOS, this will confusingly print `true` when the window is occluded:
```js
win.on('hide', () => {
  console.log(win.isVisible())
})
```

That is also problematic because we use `isVisible()` to determine `document.hidden` and `document.visibilityState`. In Chrome, they *are* driven by the occlusion state on macOS (see [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=246844)) so we don't match Chrome behaviour.

To address these issues, I think we should:

* Change `show`/`hide` events on macOS to behave like they do on Windows/Linux. This could be considered a breaking change.
* Implement `occluded`/`unoccluded` events and `isOccluded()` for macOS. These can be left undocumented if we so wish.
* Change `document.hidden` and `document.visibilityState` to be driven by the new occlusion events/method on macOS.

I'm happy to write the patch, but any thoughts before I submit the PR?

cc @kevinsawicki @zcbenz

**Comment by MarshallOfSound** [comment]
I mean, IMO the current behavior isn't "wrong" in any way, excluding the fact that it is slightly different across platforms.  The events fired make sense and aren't fired at inappropriate places.

I.e. `restore` does somewhat indicate `show`

I would rather that we bring windows and linux up to speed with macOS and simply fire show and hide events on minimize and restore.  Semantically it would make sense.

Thoughts?

**Comment by poiru** [comment]
>I would rather that we bring windows and linux up to speed with macOS and simply fire show and hide events on minimize and restore. Semantically it would make sense.

I'm fine with this as well.

**Comment by kevinsawicki** [comment]
> Change show/hide events on macOS to behave like they do on Windows/Linux. This could be considered a breaking change.

I'm okay changing this in Electron 2.0 but I don't think we should change it before hand

> Implement occluded/unoccluded events and isOccluded() for macOS. These can be left undocumented if we so wish.

This seems useful and if maybe we can eventually get it supported on other platforms.

> Change document.hidden and document.visibilityState to be driven by the new occlusion events/method on macOS.

This sounds good to me as well, but I'm interpreting this a non-breaking change that just makes these values more correct on macOS.

**Comment by nickfujita** [comment]
Wanted to follow up on this issue, as I would like to know when the BrowserWindow is not visible to the user. The `isVisible` method on OSX is returning `true`, even when the BrowserWindow is not actually visible to the user, and is hidden behind other application windows. The only time that it appears to be returning `false` is when the BrowserWindow is minimized, so it's return value does not accurately match the description in the documentation: "Whether the window is visible to the user."

**Comment by ghanashyam-c-k** [comment]
What is the status of this issue?
I have a browserWindow, with a child modal window in my application.
In macOS, when the application loses focus (switched to another app) while the modal is visible, the modal window 'hide' event is fired. Is this how it works?
