### ISSUE TITLE
vimeo?

### ISSUE THREAD

**Issue by retkowski** [electron/electron#868]
![vimeo](https://cloud.githubusercontent.com/assets/6824488/5198254/f57ccc8a-754e-11e4-89fc-21d19237b097.png)

Hey guys, if I open a vimeo video in the atom shell, it displays only a dark grey area.
In this case you see the embed player (but it's also with the normal).

Example: https://vimeo.com/76979871

Flash in general seems to work, and also YouTube videos are displayed.

Do you have an idea how to fix this?

Thanks in advance.

**Comment by bahadirdogru** [comment]
For me it's not posible to close node integration. Also i cannot avoid to use vimeo. I'm stuck.
