### ISSUE TITLE
Debug DevTools window

### ISSUE THREAD

**Issue by jhen0409** [electron/electron#8681]
* Electron version: 1.4.15
* Operating system: macOS Sierra

### Expected behavior

In Chrome, you can typing Command+Option+I in devtools window to open another devtools window for inspect.

### Actual behavior

Electron seems doesn't. I saw `BrowserWindow.debugDevTools` in [history](https://github.com/electron/electron/pull/178), but it does not seem right now.

Some people are facing https://github.com/jhen0409/react-native-debugger/issues/36 (devtools blank), but currently we don't know the cause of the problem.

**Comment by deepak1556** [comment]
Merging this to https://github.com/electron/electron/issues/2835 , you can try remote debugging if that helps your case as a workaround.
