### ISSUE TITLE
net.request holds handle to cached data

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#8685]
* Electron version: 1.4.15
* Operating system: Windows 10

Running some tests on `electron-mocha` that use `net.request`. `electron-mocha` creates a temporary directory and assigns it as the user data path. When it finishes, it tries to clear the user data path to ensure a clean room. Any test that uses `net.request` prevents `electron-mocha` from clearing this directory when done. I tried working around it with `session.clearCache` or `clearStorageData`, to no avail.

![image](https://cloud.githubusercontent.com/assets/1865957/22946674/e618f600-f2ac-11e6-8be1-5416fdda29b7.png)

### How to reproduce

* Be on Windows
* Write a simple test that uses `net.request`
* Run that test in an `electron-mocha` context
* Once tests are finished, you should see the crash

**Comment by groundwater** [comment]
Hey @CharlieHess, thanks for the report.

Curious about a few things

1. Is this Windows only?
2. Any knowledge as to why `net.request` is preventing unlinking that directory?

**Comment by inukshuk** [comment]
For what it's worth, I've had similar issues with electron-mocha not being able to unlink the directory on Windows when tests opened `BrowserWindows` without closing them. My guess would be that unlinking fails because an active process still holds an open file descriptor in the user data directory (in this case `net.request` accessing the cache folder).

**Comment by CharlieHess** [comment]
@groundwater yeah it seems to be Windows only. And @inukshuk is correct; previously our tests were failing because they forgot to close some hidden `BrowserWindow`s but after going through all of those it's now just the `net.request` left.

**Comment by tex0l** [comment]
I'm currently working on https://github.com/arantes555/electron-fetch which provides a fetch polyfill over `net.request` based on node-fetch.

I get the same issue on Windows 7 64-bit (just run the test suite to reproduce).

**Comment by zcbenz** [comment]
The cache data is kept by the `Session` object, in order to solve this we need to:

1. Provide a way to manually free `Session` object.
2. Provide a way to manually destroy the request object returned by `net.request`.

**Comment by nornagon** [comment]
Closing as lots of things have changed since this was reported and it's unclear that this is still an issue.
