### ISSUE TITLE
Add event to tray notification when other item is being selected

### ISSUE THREAD

**Issue by pronebird** [electron/electron#8689]
Hi,

I build a menubar app and use Tray to display window below menubar item.

I use the following implementation:
https://github.com/kevinsawicki/tray-example

When user clicks on menubar item it highlights, i.e.:

```js
tray.on('right-click', toggleWindow);
tray.on('double-click', toggleWindow);
tray.on('click', toggleWindow);

window.on('show', () => {
  tray.setHighlightMode('always');
});

window.on('hide', () => {
  tray.setHighlightMode('never');
});
```

However if user switches between menubar items the tray item remains selected which is against how things are naturally handled on macOS. On macOS the majority of apps hide the corresponsding menus or popovers when other menubar item is being selected. I am sure that holds true for Windows as well.

Also since I am not able to track when that happens, there is nothing I can do to hide the displayed window.

The proposal is to have an event or certain capability to track when user switches between menubar items.

* Electron version: 1.5.0
* Operating system: macOS

**Comment by pronebird** [comment]
@groundwater sorry it turns out my electron updated to 1.6.0 according to `npm list | grep electron`. I tested with 1.4.15 and it's the same. 

I don't think it's regression. I think everything works fine for Tray created with context menu (`Menu`). However my Tray is quite custom since it display a BrowserWindow below menubar icon (just like Dropbox for macOS).

I looked through some samples of creating popovers on macOS and it seems that once popover is displayed a global click listener is assigned and used to track clicks outside of popover to dismiss it and potentially remove highlight from menubar icon.

It feels like it would be great to have some event for this since there is a growing number of menubar apps that are currently being built using BrowserWindows positioned below menu item.

In swift it looks as such:

```swift
self.monitor = NSEvent.addGlobalMonitorForEvents(matching: .leftMouseDown, handler: {
    statusButton.highlight(false)
    NSEvent.removeMonitor(self.monitor)
})
```

**Comment by zeke** [comment]
@pronebird I think the `blur` event is what you're looking for:

```js
window.on('blur', () => {
  window.hide();
});
```

**Comment by pronebird** [comment]
@zeke unfortunately that does not seem to work with other context menus or popovers on macOS. It works if I switch to other app though.

**Comment by pronebird** [comment]
Since I don't see how to solve that without talking to macOS, I made a simple extension to be able to work with `NSEvent` directly to dismiss `BrowserWindow` when clicks are being dispatched to other apps.

https://github.com/pronebird/NSEventMonitor

**Comment by zeke** [comment]
>   I made a simple extension to be able to work with `NSEvent` directly

Awesome that you were able to work around the problem. 👍

However this still seems like something that should be fixed in Electron. To recap, I think the fundamental issue here is that the `blur` event is not triggered on the BrowserWindow instance when _other_ tray/menubar items are clicked.

**Comment by pronebird** [comment]
@zeke I don't think it's a bug. If you have macOS handy open Finder and click on Dropbox icon in menubar which will display popover leaving Finder window active.

**Comment by zeke** [comment]
The behavior seems to vary based on the clicked app.

Google Drive, CloudUp, ScreeHero: window is blurred
Slack, DropBox, OnePassword: window stays active

**Comment by zeke** [comment]
@pronebird I discussed this issue with the team last week. Here's what we came up with: For now, let's add a note to Electron's [Tray](https://electron.atom.io/docs/api/tray/) docs describing this scenario and link to your [NSEventMonitor](https://github.com/pronebird/NSEventMonitor) module as a workaround for those who need it.

Thinking more long term, @kevinsawicki suggested that it would be nice if Electron had a general-purpose way to expose `NSEvent`s. We're not going to prioritize making this happen right now, but if you're interested in working on a PR that explores how such an API might look, we'd be happy to help make it happen.

**Comment by pronebird** [comment]
@zeke I am concerned about exposing platform dependent APIs. Electron has fair share of them already and since menubar apps aren't exactly supported (i.e. we use BrowserWindow that fakes popover).

I think native extension should cut it until Popovers are somehow added to Electron, which would be huge addition not only for menubar apps but generally for any apps.

**Comment by CydeSwype** [comment]
Somewhat related, even though blur event doesn't occur when selecting other tray icons, it DOES occur when selecting your own app's icon.  This creates a challenge when trying to handle both blur events on the window and click events on the app icon when the window is shown.  The standard behavior is to hide the window when the app icon is clicked (i.e. toggle window visibility if the user keeps clicking the app in the tray).  Depending on event order, the window may be hidden from the blur event and then immediately shown again from the tray icon click event handling.  This is a problem on Windows not just Mac and is more generally related to windows, not just "tray-only" popovers.

**Comment by pronebird** [comment]
@CydeSwype fair point, in Mullvad VPN app we use some basic heuristics to detect what's happening based on cursor and tray icon locations, but this is not 100% and I couldn't find any better way to workaround that:

```
window.on('blur', () => {
      // Detect if blur happened when user had a cursor above the tray icon.
      const trayBounds = tray.getBounds();
      const cursorPos = screen.getCursorScreenPoint();
      if (!isCursorInside(cursorPos, trayBounds)) {
        window.hide();
      }
    });
```

**Comment by codebytere** [comment]
@pronebird zeke hasn't been working on Electron for over a year now actually, sorry for not updating that. I also believe the base of the original issue can be closed: This [tray rewrite](https://github.com/electron/electron/commit/47a38daee20ef77cc98bc13bb7a7c1d690fd635c) made it such that highlighting is now automatically managed by the system. You can see that in action here, where the item to the left is the local Electron app running:

![working-tray](https://user-images.githubusercontent.com/2036040/72567571-fec16f00-386a-11ea-8026-9bc111ccd4fd.gif)

Given that behavior and no upcoming roadmapping for NSPopover implementation, i'm going to state that component as a wontfix and close this.
