### ISSUE TITLE
Integrating Google Tag Manager (gtm)

### ISSUE THREAD

**Issue by patricksebastien** [electron/electron#8691]
* Electron version: 1.4.12
* Operating system: Mac, Windows, Linux

### Expected behavior
Collecting the analytics

### Actual behavior
Not sending the datas to Google Analytics

### How to reproduce
I have a simple webpage that integrates Google Tag Manager (a container that forward the dataLayer to Google Analytics). It works when opening my webpage on my local server, but when running the exact same code in electron, http://www.google-analytics.com/collect is never called.

I was wondering if anyone have a clue of why it is happening?
Thank you

**Comment by MarshallOfSound** [comment]
Hey, Google Analytics doesn't work by default from `file://` URL's.  You either need to use HTTP or a custom protocol or use the `universal-analytics` package that can send requests directly to Google Analytics.

If you have other questions / issues about this please ask them below on this thread 👍

**Comment by apasternack** [comment]
@MarshallOfSound Does this mean that Google Tag Manager cannot be made to work with electron?  Or might a workaround be possible to adapt it to the file protocol?

**Comment by evan-coygo** [comment]
I've got the same question, is there any way to use GTM within an Electron app? @apasternack did you ever figure this out?

**Comment by hanee24** [comment]
For those who are seeking for the answer, please find the workaround on this post:
[Run Google Tag Manager And Google Analytics In Local Files](https://www.simoahava.com/analytics/run-google-tag-manager-google-analytics-local-files/)

Works perfect for me.

**Comment by prameshbajra** [comment]
Hi @hanee24 ,
Is it possible for you to verify if this still is relevant? I am not able to get it running from electron.
:(

**Comment by leohxj** [comment]
I am using [peaksandpies/universal-analytics: A node module for Google's Universal Analytics and Measurement Protocol](https://github.com/peaksandpies/universal-analytics).

**Comment by leohxj** [comment]
"Universal Analytics will no longer process new data in standard properties beginning 1 July 2023. Prepare now by setting up and switching over to a Google Analytics 4 property."
