### ISSUE TITLE
js file load error

### ISSUE THREAD

**Issue by CarlosRen** [electron/electron#8697]
Hi , i meet this error in opening app packaged by `electron-builder` and execute `electron .` in commend line

![1](https://cloud.githubusercontent.com/assets/6012322/23014862/a5fa2902-f46b-11e6-8033-9f45ee76adca.png)
![2](https://cloud.githubusercontent.com/assets/6012322/23014863/a600e5f8-f46b-11e6-899c-9d4dd548336a.png)

and there is no error on chrome browser of version 50 and 56 , it this a bug of electron?

**Comment by CarlosRen** [comment]
![3](https://cloud.githubusercontent.com/assets/6012322/23015325/5044911c-f46d-11e6-97b9-a48d1e6cee7b.png)

**Comment by MarshallOfSound** [comment]
You need to disable `nodeIntegration` on your BrowerWindow if you are going to be loading remote content that uses modules like jQuery.

Basically if you don't disable `nodeIntegration` the global `module` object is still available so jQuery treats it like a node environment.
