### ISSUE TITLE
BrowserWindow.titleBarStyle "hidden-inset" issue in 1.6.0

### ISSUE THREAD

**Issue by thegnuu** [electron/electron#8699]
* Electron version: 1.6.0
* Operating system: macOS Sierra 10.12.3

### Expected behavior

BrowserWindow.titleBarStyle "hidden-inset" is not working anymore in Electron 1.6.0.
The title bar is hidden but the traffic light buttons are not inset.

Example from Electron 1.4.15:

![screen shot 2017-02-16 at 11 15 41](https://cloud.githubusercontent.com/assets/5129086/23017106/4825c9da-f439-11e6-8843-c5a113f69a45.png)

### Actual behavior

![screen shot 2017-02-16 at 11 17 27](https://cloud.githubusercontent.com/assets/5129086/23017164/85775920-f439-11e6-844a-3ffdb4179f8c.png)

### How to reproduce

Simply set BrowserWindow.titleBarStyle to "hidden-inset"

**Comment by MarshallOfSound** [comment]
Duplicate:

https://github.com/electron/electron/issues/8629
https://github.com/electron/electron/issues/8694
