### ISSUE TITLE
在mac上，fullscreen为true但是却不能全屏显示

### ISSUE THREAD

**Issue by yuxiaoyan1205** [electron/electron#8705]
在windows系统上，new BrowserWindow({fullscreen:true}),打开的窗口是全屏的，但是在mac上，有时是全屏的，有时确是默认的宽度800，高度600，怎么让窗口一直全屏显示呢

**Comment by groundwater** [comment]
Translation here:

```
On the windows system, new BrowserWindow ({fullscreen: true}), open the window is full screen, but in the mac, sometimes full-screen, sometimes the default width of 800, height 600, how to make the window has been full-screen display
```

Hi @yuxiaoyan1205:

1. What version are you using? `$ electron -v`

**Comment by yuxiaoyan1205** [comment]
Hi， @groundwater ：
my version is 1.3.1。
--------------------------------------------------
"electron": "^1.3.1",
"electron-devtools-installer": "^1.1.4",
"electron-packager": "^8.0.0",
"electron-rebuild": "^1.1.3",

**Comment by zcbenz** [comment]
Please provide a minimal example to reproduce that can reproduce the problem, the problem is very likely caused by other parts of your code. I'll reopen this after we got a reproducible case.

**Comment by yuxiaoyan1205** [comment]
hi, @zcbenz :
ipcMain.on('asynchronous-message', (event, arg) => {
  if (win) {
    win.close()
  }
  win = new BrowserWindow({
    backgroundColor: '#000000',
    fullscreen: true,
    autoHideMenuBar: true,
    alwaysOnTop: appCfg.ALWAYS_ON_TOP,
    webPreferences: {
      plugins: true,
      javascript: true,
      webSecurity: false,
      allowRunningInsecureContent: true,
      allowDisplayingInsecureContent: true
    }
  })
  win.on('show', (event, arg) => {
    autoShow()
  })

  function autoShow() {
    event.sender.send('asynchronous-ping', 'AutoShow')

  }

  //当打开的应用自动关闭的时候，发送指令status=ok
  win.on('closed', (event, arg) => {
    win = null
    autoClose()
  })

  function autoClose() {
    event.sender.send('asynchronous-ping', 'AutoClose')
  }



  // win.setAlwaysOnTop(true)
  win.setMovable(false)
  win.setResizable(false)
  console.log(new Date() + 'open rendered window: ' + win.id)
  win.loadURL(arg)
  event.sender.send('asynchronous-reply', 'pong')
})
