### ISSUE TITLE
Bootstrap "tabs" don't work in electron

### ISSUE THREAD

**Issue by pratik-abhyankar** [electron/electron#8711]
* Electron version: 1.4.15
* Operating system: Windows

### Expected behavior
Clicking on a bootstrap tab from navbar with class "nav-tabs" should display the corresponding tab data. 
My code is 100% correct and works flawless in any browser. 

### Actual behavior
I am using bootstrap "tabs" navigation in my application. 
However, clicking on any tab has no effect at all. The other tabs don't open what so ever, even though the entire application is just 1 page HTML code.
This works perfectly fine in any other browser. 

### How to reproduce
Add twitter bootstrap to the index.html (default page) and create navigation bar with "nav-tabs" class.
Add respective <div> with "id" for each of the tab. 
Click on any tab and the content of its corresponding <div> should be loaded. However, clicking on any tab has no effect at all 

[tab-bug.txt](https://github.com/electron/electron/files/784317/tab-bug.txt)

**Comment by kevinsawicki** [comment]
If you open the dev tools and click the console tab do you see any errors?

**Comment by kevinsawicki** [comment]
I'm guessing this is related to https://github.com/electron/electron/issues/254, see that issue for more details if you are seeing console errors about `jQuery` not being loaded.

**Comment by baconface** [comment]
I have several projects with Bootstrap tabs. All work as expected. I am also guessing you are trying to load jQuery and Bootstrap in the traditional browser context and not the Node context.

**Comment by ensiform** [comment]
Strange, I am using the following just fine:

```js
        <ul class="nav nav-tabs tab-icon" role="tablist">
            <li role="presentation"><a href="#general" aria-controls="general" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> General</a></li>
            <li role="presentation"><a href="#character" aria-controls="character" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Character</a></li>
            <li role="presentation"><a href="#vehicle" aria-controls="vehicle" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-road" aria-hidden="true"></span> Vehicle</a></li>
            <li role="presentation"><a href="#currency" aria-controls="currency" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span> Currency</a></li>
            <li role="presentation"><a href="#fast-travel" aria-controls="fast-travel" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-plane" aria-hidden="true"></span> Fast Travel</a></li>
            <li role="presentation"><a href="#backpack" aria-controls="backpack" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> Backpack (0)</a></li>
            <li role="presentation"><a href="#bank" aria-controls="bank" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span> Bank (0)</a></li>
            <li role="presentation"><a href="#raw" aria-controls="raw" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> Raw</a></li>
            <li role="presentation" class="active"><a href="#about" aria-controls="about" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> About</a></li>
        </ul>

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade" id="general">General</div>
            <div role="tabpanel" class="tab-pane fade" id="character">Character</div>
            <div role="tabpanel" class="tab-pane fade" id="vehicle">Vehicle</div>
            <div role="tabpanel" class="tab-pane fade" id="currency">Currency</div>
            <div role="tabpanel" class="tab-pane fade" id="fast-travel">Fast Travel</div>
            <div role="tabpanel" class="tab-pane fade" id="backpack">Backpack</div>
            <div role="tabpanel" class="tab-pane fade" id="bank">Bank</div>
            <div role="tabpanel" class="tab-pane fade" id="raw">Raw</div>
            <div role="tabpanel" class="tab-pane fade in active" id="about">About</div>
        </div>

        <script>
            window.$ = window.jQuery = require('jquery');
            require('./js/bootstrap.min.js');
            require('./newtabs.js');
        </script>
```

the newtabs.js file uses jquery to load in the real content into each tab.

See my WIP code here: https://github.com/ensiform/bltps-edit

**Comment by pratik-abhyankar** [comment]
@kevinsawicki @baconface Yes, you were indeed correct! I tried loading jQuery like a normal browser script, which failed. I am sorry, that was my mistake. 
Luckily, I found a very very simple solution at http://stackoverflow.com/questions/32621988/electron-jquery-is-not-defined. Do check out!
Closing the issue.

**Comment by baconface** [comment]
A trick I do. I put this in the beginning  of my JavaScript:
```javascript
if (typeof module === 'object') {
  var electron = require('electron');
  var ipc = electron.ipcRenderer;
  var dialog = electron.dialog;
  var remote = electron.remote;
  var autoUpdater = electron.autoUpdater;
  var Menu = remote.Menu;
  var MenuItem = remote.MenuItem;
  // Require in any additional modules that are Node.js only
  window.module = module;
  module = undefined;
}
```

I then load in all my other JavaScript normally. This way I can load the same code base in a regular browser. If I have any additional Node context code I do a check of the useragent to see if it has an `indexOf` of `Electron`.

This is especially nifty if you are porting already complete web apps to Electron and you want `nodeIntergration` set to `true` but don't want to rewrite a bunch of it.
