### ISSUE TITLE
Impossible to detect if another instance instance has been launched on OSX

### ISSUE THREAD

**Issue by tex0l** [electron/electron#8712]
Hi everyone,

I'm making an app which has a `Tray` only (most of the time) and a `BrowserWindow` which is showed when a `click` event is emitted on the `Tray`.

I'd like to show this `BrowserWindow` programmatically when the user opens the app once again. Here is my problem on OSX:
 - The callback of `app.makeSingleInstance` is not executed on OSX if the users clicks on Myapp.app,
 - No event is emitted in the background process when this happens,
 - I don't have a dock icon to listen to since it's hidden in my app. 

Is there a way of detecting such an event I'm not aware of? If not, would it possible to emit such an event?

**Comment by groundwater** [comment]
Hi @tex0l, I labeled this as a possible bug, but we'll look into it a little closer.

What version of electron are you running? (in bash `$ electron -v`)

**Comment by tex0l** [comment]
I use electron 1.4.15.

As I understand it, this behaviour is not a bug, this is what is intended.
In the documentation it's said that for app.makeSingleInstance:

> On macOS the system enforces single instance automatically when users try to open a second instance of your app in Finder, and the open-file and open-url events will be emitted for that. However when users start your app in command line the system’s single instance mechanism will be bypassed and you have to use this method to ensure single instance.

My issue is more about triggering another event, much like open-url or open-file, that would give notice that the user has tried opening another instance of the app.

**Comment by tex0l** [comment]
Hi,

I've just discovered that the 'activate' event does the job just right. It might need a better doc than that though:
>Emitted when the application is activated, which usually happens when the user clicks on the application’s dock icon.

I'm closing the issue.
Cheers,
tex0l.

**Comment by zeke** [comment]
Thanks for following up and closing, @tex0l. I went ahead and opened PR #8746 to improve the docs for that event.
