### ISSUE TITLE
webContents.sendInputEvent({type:'char', keyCode:'Shift'}) inserts the text "Shif" into a textarea

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#8713]
* Electron version: 1.6.0
* Operating system: macOS Sierra

### Expected behavior

When focused in a `textarea` and I call `webContents.sendInputEvent({type:'char', keyCode:'Shift'})` a simulated shift key should be sent to the window and no text should be entered into the `textarea`.

### Actual behavior

The text `Shif` is appears in the `textarea`.

### How to reproduce

Make an empty textarea, focus on it, and then call `webContents.sendInputEvent({type:'char', keyCode:'Shift'})` to see it insert the text.

**Comment by groundwater** [comment]
Hi @kirkouimet, thanks for giving the 1.6.0 beta a spin. Folks trying out out helps us a lot!

First question, is this a regression? Do you get the expected behavior in the latest stable release `1.4.15`?

**Comment by kevinsawicki** [comment]
@kirkouimet I believe `Shift` can only be sent as a `keyDown` or `keyUp` event via `sendInputEvent`, similar to how `keypress` does not trigger for just a `Shift` key press, but `keydown` and `keyup` do.

Is there a reason you are trying to send a `Shift` via `char` instead of `keyDown` or `keyUp`?

**Comment by kevinsawicki** [comment]
Closing this out, just to clarify, you can send in shifted characters by using capitalized key codes such as `webContents.sendInputEvent({type:'char', keyCode:'A'})` but `Shift` alone cannot be sent as a `char` event.

**Comment by kirkouimet** [comment]
Thanks @kevinsawicki!

**Comment by denysdovhan** [comment]
Anyway, how can I send `Shift+?` for example? Neither of these examples work:

```
webContents.sendInputEvent({type:'char', keyCode:'Shift+?'});
webContents.sendInputEvent({type:'keyDown', keyCode:'Shift+?'});
webContents.sendInputEvent({type:'keyUp', keyCode:'Shift+?'});
```
