### ISSUE TITLE
how to show a popup div outside the browser window

### ISSUE THREAD

**Issue by che3vinci** [electron/electron#8716]
just like this.
the main window is always focus.

![a](https://cloud.githubusercontent.com/assets/3297310/23093703/7526b1fe-f625-11e6-9742-cfd3d91f7350.jpg)

**Comment by tommoor** [comment]
You should use a new window with the `parent` option (see: https://github.com/electron/electron/blob/master/docs/api/browser-window.md#parent-and-child-windows). It'll be difficult to make it seem native though, you're probably better off keeping it inside your original window.

**Comment by groundwater** [comment]
Hi @che3vinci, please ask here:

- [Discuss Forum](https://discuss.atom.io/c/electron)
- [Slack Chat](http://atom-slack.herokuapp.com/)

I will close this issue, but @tommoor thanks for your help! Everyone is free to keep discussing the topic here if hey like.

**Comment by che3vinci** [comment]
@tommoor if I use child browser window,the main browser can lose focus when I am editing the child window.
what I need is alway keep the main window is focus,so the popup DIV is one choice .
but I don't know how to do it .

**Comment by MarshallOfSound** [comment]
@che3vinci Check out the `focusable` property on the `BrowserWindow` class 👍
