### ISSUE TITLE
DataTransfer.files in dragenter event with http protocol

### ISSUE THREAD

**Issue by marcatec** [electron/electron#8720]
I would like to implement drag and drop into our application.
For security reasons the Filelist in event.dataTransfer.files is only exposed for a drop event.
As a feature request it would be useful, if one could get the file info from dragenter and know what file is being dragged into the window.

I tried to set the sandbox option to false, but it didn't change the behaviour.

**Comment by groundwater** [comment]
Hi @marcatec, thanks for your feedback.

We definitely use feature requests to prioritize upcoming work. If you can share more about your application, and what it's trying to accomplish that helps justify the work. No promises, but every bit of information helps.

Alternatively, we do accept community pull requests. For significant changes, we first like to discuss the proposed idea in the open, and allow community feedback. I would recommend using the [Rust RFC Template](https://github.com/rust-lang/rfcs/blob/master/0000-template.md) as a good place to start.

**Comment by marcatec** [comment]
Hello @groundwater, I further investigated my case, and am not sure any more if it's a real feature request.

What we want is similar to a feature in the app Svgsus, made with Electron.
They transform svg files via drag and drop, without dropping.
It can be seen in their video at time 0:17. http://www.svgs.us/images/svgsus_developer_video_web.mp4

My conclusion is, that is only possible loading the html page via file protocol.
In our app we use http (with a local server) and that case is restricted to provide the file info only on drop, not on dragenter or dragover.

Is that behaviour hard coded into Chromium or is there a switch or can one be implemented?
May there be a chance to solve it using a custom protocol?

**Comment by zcbenz** [comment]
I'm afraid this is a behavior hardcoded in Chromium, and since this is the only request on this, we are not going to implement it.

A pull request to optional add the behavior would be welcomed though.

**Comment by inukshuk** [comment]
@zcbenz did this behavior change between Electron 1.6 and 1.7? We were definitely accessing the files (at least the `path` property added by Electron) previously but now (on 1.7) this does not seem to work any longer (using file protocol)?

**Comment by inukshuk** [comment]
Just confirmed this: with Electron 1.6.11 I can access `dataTransfer.files` in `drag` events before the `drop` event happens. In Electron 1.7.3 I cannot. (Both on Linux and Mac)
