### ISSUE TITLE
Make async Call in main.js

### ISSUE THREAD

**Issue by loreberti89** [electron/electron#8721]
Hello, I need to do a async Call in main.js,
I tried with `require('request');` but the problem is that I need to start App at startup of Windows, and with `require('request');` the app remains in white screen.
So I thought to do async call with jQuery, with $.ajax, but my problem, is that after:
`mainwindow.$ = mainwindow.jQuery = require('jquery');`

```
$.ajax({
   //my params
});
```

it return error:

`$.ajax is not a function`, and if I tried to console.log $.ajax it return undefined.

How can I do async call in main.js?

**Comment by groundwater** [comment]
Hi @loreberti89. I would like to direct you towards a better spot for electron support.

- [discuss.atom.io](http://discuss.atom.io/)
- sign up for the [community slack](https://discuss.atom.io/t/join-us-on-slack/16638) and check out the `#electron` room
