### ISSUE TITLE
How to create a second BrowserWindow without seeing again the main BrowserWindow in foreground ?

### ISSUE THREAD

**Issue by ademcan** [electron/electron#8723]
Dear Electron community,
I am developing a new app based on Electron and I need some advices in a particular problem.
I want to use two BrowserWindow(s) (main and action).
I want to create a new BrowserWindow (action) with a globalShortcut, and be able to close that new BrowserWindow (action) with the Esc command (another globalShortcut). So far, it works well for the first call of the action BrowserWindow. However, when I close it and re-call the action BrowserWindow, the main BrowserWindow appears on the back of the action BrowserWindow. I just want the main BrowserWindow to stay where it was and not come to the front everytime I create the action BrowserWindow. Is that possible ?
Thank you very much for your time and your help.
A.

**Comment by baconface** [comment]
Please close this and repost it on https://discuss.atom.io/c/electron

This issue manager is meant for bugs and not how-to do X discussion. Thanks.

**Comment by ademcan** [comment]
Thanks, I'll do that.
