### ISSUE TITLE
desktopCapturer on Windows 10 records video of screen with offset

### ISSUE THREAD

**Issue by nuthinking** [electron/electron#8726]
* Electron version: 1.6
* Operating system: Windows 10 (build 1607)

### Expected behavior

The screen should be captured as it looks.

### Actual behavior

The video is recorded with an offset and the right side of the screen loops on the left side.

![screen shot 2017-02-21 at 11 12 18](https://cloud.githubusercontent.com/assets/163635/23162647/06cb1cfa-f827-11e6-89c8-84f40b9876c5.png)

Captured video can be seen here: https://dl.dropboxusercontent.com/u/2935618/temp/Bug%20Screen%20Recording-1487675274089.webm

### How to reproduce

I tried many variations and none worked. Below the simplest code which can be used for replicating it.
```javascript
var recorder;
var blobs = [];

function recordVideo() {
  desktopCapturer.getSources({types: ['window', 'screen']}, function (error, sources) {
    if (error) throw error;
    for (let i = 0; i < sources.length; i++) {
      let src = sources[i];
      if (src.name === document.title) {
        const contraints = {
          audio: false,
          video: {
            mandatory: {
              chromeMediaSource: 'screen',
              chromeMediaSourceId: src.id,
              maxWidth: window.screen.width,
              maxHeight: window.screen.height
            }
          }
        };
        navigator.mediaDevices.getUserMedia(contraints)
          .then(handleStream)
          .catch(handleUserMediaError);
        return;
      }
    }
  });
}

function handleStream(stream) {
  recorder = new MediaRecorder(stream);
  blobs = [];
  recorder.ondataavailable = function(event) {
    blobs.push(event.data);
  };
  recorder.start();
}

function saveRecordedVideo(){
  blobToBuffer(new Blob(blobs, {type: 'video/webm'}), function(err, buffer){
    if (err) throw err;
  
    var file = os.homedir() + '/' + document.title + '-' + (new Date()).getTime() + '.webm';
    fs.writeFile(file, buffer, function(err) {
      if (err) {
        console.error('Failed to save video ' + err);
      } else {
        console.log('Saved video: ' + file);
      }
    });
  });
}
```

**Comment by nuthinking** [comment]
(I also tested getUserMedia native API in Chrome on that specific Windows device and got no issue)

**Comment by demian85** [comment]
Did you test on latest Chrome Canary?

**Comment by groundwater** [comment]
Hi @nuthinking thanks for the report. Are you able to verify if this works in the current stable release `1.4.15`?

**Comment by nuthinking** [comment]
@groundwater yes, bug present also with `1.4.15` I am using Chrome `56.0.2924.87 (64-bit)`. Didn't test with Canary. If someone has some tips on how to easily do it (without messing with the machine), I am happy to do so (cc. @demian85)

**Comment by demian85** [comment]
In this cases, you will need to test on latest Chrome Canary to verify bug is not related to Electron.

Attaching a demo used for other reported issue #8278 & https://bugs.chromium.org/p/chromium/issues/detail?id=688490

Add as extension and try to record/play. Then see what you get.
[chrome-recorder.zip](https://github.com/electron/electron/files/794037/chrome-recorder.zip)

Also, please search for related bug in https://bugs.chromium.org/p/chromium/issues/list

**Comment by nuthinking** [comment]
@demian85 can't make that extension to work either in Canary or stable Chrome.

**Comment by demian85** [comment]
Can you be more specific? ...

**Comment by nuthinking** [comment]
@demian85 I installed the extension in developer mode as unpacked extension but the UI element of the extension seems disabled and doesn't allow me to initiate the recording. I can access its menu though. I just put the Window machine away, I can only send you screenshots tomorrow.

**Comment by nuthinking** [comment]
@demian85 this is how this extension looks like. No idea how to initiate the recording. Maybe I am missing something.

![capture](https://cloud.githubusercontent.com/assets/163635/23254102/c4e83fe6-f9ae-11e6-880f-2c966f20d3e6.PNG)

**Comment by demian85** [comment]
Yeah, just go to chrome-extension://<id>/recorder.html
Take the id from the extension manager. Enable developer mode.

**Comment by nuthinking** [comment]
@demian85 managed to test the extension. But unfortunately on Canary I can't even initiate the recording. I get TrackStartError

**Comment by zcbenz** [comment]
This looks very likely an upstream bug of Chromium. If you are still able to reproduce this on Electron v1.7.x, please try to reproduce it on the corresponding Chrome version and and report it to Chromium's issues list.
