### ISSUE TITLE
About beta releases

### ISSUE THREAD

**Issue by demian85** [electron/electron#8729]
Hi, you may know me from previous bugs, like https://github.com/electron/libchromiumcontent/issues/253 and #8325 

I've been told by a guy from Chromium project that the fix I'm looking for has been released in Chrome 58 (currently beta)
I'm seeking for any kind of help that would allow me to build my own version of Electron based on Chrome 58 and continue working on my project (it's my job and it's like hanging by a thread...)
Unfortunately, without guidance I cannot do anything because I lack knowledge of the compilation process.

So, the question is. What do you think about having a beta release based on beta versions of Chrome? 
I think that would help the community by allowing to test certain features recently added to Chrome, and of course, bunch of bug fixes (almost 99% of them are merged in master...)
For example, we currently have beta versions 1.5 and 1.6, a bit confusing. Both of them based on a stable version of Chrome.
My suggestion is to consider a roadmap including stable and beta versions based on latest stable and beta Chrome releases.

Am I asking too much?

Of course I'm willing to help by contributing to this project and make this happen. I lack C++ knowledge, but perhaps my experience as a senior full stack web developer can be useful :P

Thanks!

**Comment by paulcbetts** [comment]
Trying to keep up with beta releases of Chrome is a massive amount of work, it is not at all as straightforward as bumping a version number. Tracking release versions of Chrome is already a daunting task.

**Comment by kevinsawicki** [comment]
> Unfortunately, without guidance I cannot do anything because I lack knowledge of the compilation process.

You may want to check out https://github.com/electron/electron/blob/master/docs/development/upgrading-chrome.md for a high-level overview if you want to try upgrading now to 58 and see what happens.

**Comment by demian85** [comment]
Thanks. Will check that.
Why do you say keeping up to date with beta Chrome releases is a massive
amount of work? Which is the difference between staying up to date with
stable chrome versions? You will have to upgrade sooner or later...

**Comment by demian85** [comment]
@kevinsawicki Thanks for the guide, but unfortunately I'm having issues, as not clear enough in which order I need to complete the steps from that guide...
Would love to have a clearer guide for newbies, as I'm trying to help also, but basically you just tell me "it's too difficult" and that's it.

Can you please help me with the following?

- Do I have to download chromium myself specified in VERSION file? Where should I put it?
- I cannot find the script `libchromiumcontent/src/tools/clang/scripts/update.py`. In which project does the file reside? electron, libchromiumcontent or chromium?
- There isn't even a Node.js version using v8 version that uses Chrome 58.0.3018.3. From the logs I found out that version of Chrome is using v8 5.8.244 and latest Node.js v7.6.0 uses v8 5.5.372.40.
Can I even proceed with the build process of v8 version must match exactly the one Chromium is using?

Thanks.

**Comment by kevinsawicki** [comment]
> Do I have to download chromium myself specified in VERSION file? Where should I put it?

No, once you edit that file and boostrap/build, it will be downloaded.

> I cannot find the script libchromiumcontent/src/tools/clang/scripts/update.py. In which project does the file reside? electron, libchromiumcontent or chromium?

This file will exist after chrome is downloaded, it resides in chrome, https://cs.chromium.org/chromium/src/tools/clang/scripts/update.py

> There isn't even a Node.js version using v8 version that uses Chrome 58.0.3018.3. From the logs I found out that version of Chrome is using v8 5.8.244 and latest Node.js v7.6.0 uses v8 5.5.372.40.

Yeah, this is one of the challenges when upgrading is to get a node version compatible with the v8 version in Chrome, node may still compile and work fine though against v8 5.8.

**Comment by demian85** [comment]
Thanks, that helped me get me going, but... What should I do when patches fail to apply? 
```
Extracting...
source file is different - third_party/WebKit/Source/core/fileapi/File.idl
blink_file_path.patch failed to apply
already patched  src/ostreams.h
already patched  src/snapshot/mksnapshot.cc
source file is different - BUILD.gn
source file is different - gni/v8.gni
already patched  src/inspector/BUILD.gn
already patched  source/common/unicode/unistr.h
already patched  source/common/unistr.cpp
source file is different - BUILD.gn
source file is different - BUILD.gn
source file is different - content/browser/web_contents/web_contents_impl.cc
source file is different - content/public/browser/web_contents.h
already patched  ui/gl/gpu_switching_manager.cc
already patched  ui/gl/gpu_switching_manager.h
source file is different - sandbox/linux/services/credentials.cc
already patched  content/browser/renderer_host/input/synthetic_gesture_target_mac.mm
already patched  content/public/browser/resource_request_details.cc
already patched  content/public/browser/resource_request_details.h
source file is different - content/browser/renderer_host/render_widget_host_view_mac.mm
already patched  pdf/out_of_process_instance.cc
source file is different - content/app/content_main_runner.cc
source file is different - net/url_request/url_request_job.h
source file is different - chrome/browser/ui/libgtkui/BUILD.gn
source file is different - content/browser/frame_host/render_widget_host_view_child_frame.cc
source file is different - content/browser/frame_host/render_widget_host_view_child_frame.h
source file is different - content/browser/frame_host/render_frame_host_manager.cc
already patched  content/common/dom_storage/dom_storage_map.cc
source file is different - content/browser/renderer_host/render_widget_host_impl.cc
source file is different - content/browser/renderer_host/render_widget_host_impl.h
already patched  ui/views/widget/desktop_aura/desktop_screen_win.cc
source file is different - content/browser/compositor/gpu_process_transport_factory.cc
source file is different - ui/compositor/compositor.h
source file is different - content/browser/renderer_host/render_message_filter.cc
source file is different - content/common/render_message_filter.mojom
source file is different - content/public/browser/content_browser_client.cc
source file is different - content/public/browser/content_browser_client.h
source file is different - content/renderer/render_view_impl.cc
source file is different - build/config/BUILDCONFIG.gn
source file is different - third_party/WebKit/Source/platform/BUILD.gn
source file is different - third_party/widevine/cdm/BUILD.gn
source file is different - content/browser/renderer_host/browser_compositor_view_mac.h
source file is different - content/browser/renderer_host/browser_compositor_view_mac.mm
source file is different - third_party/WebKit/Source/web/WebLocalFrameImpl.cpp
source file is different - third_party/WebKit/Source/web/WebLocalFrameImpl.h
source file is different - third_party/WebKit/Source/web/WebRemoteFrameImpl.cpp
source file is different - third_party/WebKit/Source/web/WebRemoteFrameImpl.h
source file is different - third_party/WebKit/public/web/WebFrame.h
already patched  third_party/WebKit/Source/core/dom/DOMArrayBuffer.h
premature end of source file third_party/WebKit/Source/core/dom/DOMArrayBufferBase.h at hunk 2
already patched  third_party/WebKit/Source/core/dom/DOMArrayBufferBase.h
already patched  third_party/WebKit/Source/web/WebArrayBuffer.cpp
already patched  third_party/WebKit/public/web/WebArrayBuffer.h
source file is different - third_party/WebKit/Source/core/frame/LocalFrame.cpp
source file is different - third_party/WebKit/Source/core/fileapi/File.idl
already patched  sandbox/mac/launchd_interception_server.cc
already patched  sandbox/mac/os_compatibility.cc
already patched  sandbox/mac/pre_exec_delegate.cc
premature end of source file sandbox/mac/xpc_message_server.cc at hunk 4
already patched  sandbox/mac/xpc_message_server.cc
already patched  content/browser/accessibility/browser_accessibility_cocoa.h
source file is different - content/browser/accessibility/browser_accessibility_cocoa.mm
already patched  content/browser/accessibility/browser_accessibility_manager_mac.mm
source file is different - content/common/sandbox_mac.mm
source file is different - net/dns/dns_config_service_posix.cc
source file is different - ui/views/cocoa/bridged_native_widget.mm
source file is different - third_party/WebKit/Source/core/paint/ThemePainterMac.mm
already patched  third_party/WebKit/Source/platform/mac/KillRingMac.mm
```

I assume much of the source code have changed, but how to know which patch is really needed for my use case? I just want a plain working chromium build :/

Thanks.

**Comment by kevinsawicki** [comment]
> What should I do when patches fail to apply?

The patches need to be updated so they cleanly apply against the new Chrome version.
The easiest way is to apply them to the Chrome source tree for that version and then recreate them with the updated SHA-1 information.

> I assume much of the source code have changed, but how to know which patch is really needed for my use case?

Most patches are needed to get Electron compiling since they expose or tweak APIs that Electron ends up using.

**Comment by kevinsawicki** [comment]
> The easiest way is to apply them to the Chrome source tree for that version and then recreate them with the updated SHA-1 information.

So if you have a Chrome checkout for the version you are upgrading to, you can run:

* `git apply path/to/libcc/patches/foo.patch`
* `git diff > path/to/libcc/patches/foo.patch`

This would apply then re-generate the patch, you may have to resolve conflicts after the first step.

**Comment by demian85** [comment]
I came back from holidays and now I'm trying to build Electron with Chrome 58 but I got stuck again.

I managed to apply/fix and re-generate patches for Chrome 58, but now I'm not sure how to proceed with v8/third_party patches.
I cannot find v8 source code inside chromium, it magically appears inside `libchromiumcontent/src` folder and I would like to fix v8 patches by applying them using git. How can I clone the specific v8 version that chromium uses?

If this works, I'll be happy to send a PR!

Thanks.

**Comment by kevinsawicki** [comment]
>  How can I clone the specific v8 version that chromium uses?

Following the build instructions for your platform should produce a full chrome checkout with all the proper versions of third party libraries.

https://chromium.googlesource.com/chromium/src/+/master/docs/mac_build_instructions.md

**Comment by demian85** [comment]
Sure, but how can I just checkout the specific tag using those tools? I just cloned the full repo, checked out tag 58.0.3018.3, but dependencies are out of sync and I don't know how to proceed.
`gclient sync` produces the following error: 
```
Syncing projects:  21% (14/66) src/third_party/angle

src/native_client (ERROR)
----------------------------------------
[0:00:00] Started.
----------------------------------------
Error: Command 'git checkout --quiet ee10b35a44f89833c0048a2b242f1de734108411' returned non-zero exit status 128 in /Users/demian/www/chromium/src/native_client
fatal: reference is not a tree: ee10b35a44f89833c0048a2b242f1de734108411
```

Only third_party patches are missing.

**Comment by kevinsawicki** [comment]
> Sure, but how can I just checkout the specific tag using those tools?

`gclient sync --revision src@58.0.3018.3`

**Comment by kevinsawicki** [comment]
@demian85 you may also want to try with the `--with_branch_heads` option.

**Comment by demian85** [comment]
```
gclient sync --revision src@58.0.3018.3
Syncing projects:  22% (15/66) src/third_party/boringssl/src

src/buildtools (ERROR)
----------------------------------------
[0:00:31] Started.
----------------------------------------
Error: Command 'git checkout --quiet a7cc7a3e21a061975b33dcdcd81a9716ba614c3c' returned non-zero exit status 128 in /Users/demian/www/chromium/src/buildtools
fatal: reference is not a tree: a7cc7a3e21a061975b33dcdcd81a9716ba614c3c
```

I'm totally fucked up :(
I solved previous error by checking out that rev manually using git fetch, but that does not work with buildtools module...
```
git fetch origin a7cc7a3e21a061975b33dcdcd81a9716ba614c3c
fatal: git fetch-pack: expected ACK/NAK, got 'ERR want a7cc7a3e21a061975b33dcdcd81a9716ba614c3c not valid'
fatal: The remote end hung up unexpectedly
```

**Comment by demian85** [comment]
Did magic and patches now apply fine, but cannot build...
```
script/build -t x64
ninja: Entering directory `src/out/Release'
ninja: error: '../../net/data/ssl/wosign/wosign_domains.gperf', needed by 'gen/net/data/ssl/wosign/wosign_domains-inc.cc', missing and no known rule to make it
Traceback (most recent call last):
  File "script/build", line 56, in <module>
    sys.exit(main())
  File "script/build", line 42, in main
    subprocess.check_call([NINJA, '-C', config_dir, target], env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/demian/www/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'src/out/Release', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
```
