### ISSUE TITLE
Optimize memory footprint

### ISSUE THREAD

**Issue by pronebird** [electron/electron#8732]
* Electron version: 1.6.0
* Operating system: macOS

Hi,

Currently when I run the Electron app it spawns around 4 helper processes which in total eat up to 100M of memory. Is there any setting or option to minimize memory footprint and inspect essentially *why* it needs 4 extra processes. I have a very tiny app and I don't use any plugins, no flash nothing, and I'd like to have 1 helper process for web content processing if possible. Would be great to hear if there are any optimizations or tweaks that can be done on chromium.

**Comment by MarshallOfSound** [comment]
@pronebird Each renderer is launched as a separate process.  This means that

```
process = 1 + numberOfWindows + numberOfWebviews;
```

If this is not the case in your app can you provide an example which has the same situation.  If this is the case then the situation is totally expected 👍

**Comment by pronebird** [comment]
@MarshallOfSound thanks! 

I have single window and menubar icon when running in production mode (no devtools open). I get 1 + 4 processes up and running. I killed two of helper processes with the lowest memory usage and every seems to be working. Not sure what causes this. With dev tools open I have 1 + 5 processes. Maybe react-router causes this... not sure.

**Comment by pronebird** [comment]
I just ran Electron itself and default welcome page spins off the same 1+4 processes.

<img width="1301" alt="screenshot 2017-02-22 14 12 01" src="https://cloud.githubusercontent.com/assets/704044/23215059/f1b3b3c6-f908-11e6-9734-9795194e3296.png">

**Comment by TanninOne** [comment]
It's the same on Windows. Even a minimal electron application spawns 5 processes:
1x main
1x gpu-process
3x renderer

Two of these renderer processes appear to be useless, I have killed them and seen no problem with the application.

**Comment by pronebird** [comment]
I upgraded to recent beta (1.6.1?) and compiled electron with electron-builder today. Ran this thing and only 3 processes in task manager. Not sure why but it seems that two dummy helpers are gone and everything is back to normal.

**Comment by pronebird** [comment]
Closing this as it seems to be resolved.
