### ISSUE TITLE
Support base URL option to loadURL for data URLs

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#8735]
I do a lot of HTML generation just with JavaScript and am finding myself creating `index.html` files that have code that looks like this:

     <!DOCTYPE html><html><head><script src="index.js"></script></head><body></body></html>

It would be nice to be able to do:

     browserWindow.loadHTML('<!DOCTYPE html><html><head><script src="index.js"></script></head><body></body></html>');

It would be even more awesome to do:

     browserWindow.loadScript(pathToScript);

I tried to use the `preload` option for `BrowserWindow` and using `loadURL('about:blank')`, but this has an unintended side effect of not allowing you to reference other script or CSS files using relative paths.

What do you think about proposed feature?

**Comment by kevinsawicki** [comment]
You can load scripts and html directly with `loadURL` by specifying a data URL:

```js
browserWindow.loadURL('data:text/html,<b>HI</b>')
```

Does this option not work for you?

**Comment by kirkouimet** [comment]
Hi @kevinsawicki - very cool that this is an option. Unfortunately this isn't working:

    browserWindow.loadURL('data:text/html,<script src="index.js"></script>');

The script doesn't seem to be executing, although it does show up on the DOM.

I tried this:

    browserWindow.loadURL('data:text/html,<script src="file:///path/to/index.js"></script>');

But got `Not allowed to load local resource`.

Would love any insight you may have on this!

**Comment by deepak1556** [comment]
We need to add an option to `loadURL` that accepts the base url for the data url to be loaded https://cs.chromium.org/chromium/src/content/public/browser/navigation_controller.h?l=146 for the above situation to work.

**Comment by nitsakh** [comment]
Hello, I wish to work on this issue. I haven't contributed before.

**Comment by kirkouimet** [comment]
@nitsakh could be nice to add a new method to BrowserWindow like `browserWindow.loadHTML(htmlString, basePath)` to enable this functionality.

**Comment by kevinsawicki** [comment]
> Hello, I wish to work on this issue. I haven't contributed before.

@nitsakh There is already an `options` argument supported to `browserWindow.loadURL`/`webContents.loadURL`, it probably makes send to add this new option there.

http://electron.atom.io/docs/api/browser-window/#winloadurlurl-options

You can see how other options are mapped here: https://github.com/electron/electron/blob/b936221b6397a97a2079c1725b04ba3b7c39ef00/atom/browser/api/atom_api_web_contents.cc#L911-L913
