### ISSUE TITLE
Running Electron with 'electron index.js' vs. 'electron index.html'

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#8736]
Is there a difference in how Electron works if I execute `electron index.js` vs. `electron index.html`? There seems to be, I have noticed that if I do `electron index.html` and have an `index.html` file which contains:

    <!DOCTYPE html><html><head><script src="index.js"></script></head><body></body></html>

Then the standard streams for the Electron main process no longer work. However, if I do `electron index.js` then the standard streams in the Electron main process do work.

Additionally, if I want to enable Harmony features, with `index.html` I can do this:

    spawnChildProcess(pathToElectronExecutable, ['--js-flags=--harmony', 'app/index.html'], {});

But with `index.js` I have to specifically call out `--harmony-async-await` in order to get the Harmony feature to work:

    spawnChildProcess(pathToElectronExecutable, ['--js-flags=--harmony-async-await', 'app/index.js'], {});

Is this a bug or is this the intended behavior?

**Comment by kevinsawicki** [comment]
Running `electron index.html` uses this code for the main process since their is no main process file specified: https://github.com/electron/electron/blob/master/default_app/default_app.js

Is your `index.js` meant to be run in the main process or a renderer process?

**Comment by kirkouimet** [comment]
Ah, I see, so if you provide a .js file it will be executed in Electron's main process. Makes sense, thanks for the code reference as well for how .html files are treated.

Any thoughts on why I need to provide `'--js-flags=--harmony-async-await'` when I use a .js file instead of just being able to do `'--js-flags=--harmony`?

**Comment by kirkouimet** [comment]
Actually, after some testing, it appears the `'--js-flags=--harmony'` flag is now working for .js files in the latest release of Electron.

Thanks again @kevinsawicki!
