### ISSUE TITLE
Not enough information to implement a browser-like beforeunload handler

### ISSUE THREAD

**Issue by sltam** [electron/electron#8737]
* Electron version: 1.4.15
* Operating system: macOS

Multiple user actions can trigger a page to unload, e.g. (1) closing the window/tab, (2) reloading, (3) navigating back/forward in history, or (4) navigating to a different URL.

In browsers, the `beforeunload` event handler can choose to:
(a) ignore the event and proceed to unload, or
(b) prompt user if unload should be cancelled.
    (i) If user wants to cancel, nothing happens.
    (ii) If user wants to proceed with unload, the browser proceeds with the original action.

In electron, the `befoeunload` event handler can choose to:
(c) ignore the event and proceed to unload, or
(d) `event.preventDefault()`.
    Now the app will write its own code to prompt user if it should proceed to unload.
    (i) If user wants to cancel, nothing happens.
    (ii) If user wants to proceed with unload, now what?

Detecting the `close` event on `BrowserWindow` can distinguish (1) from the rest, but the `beforeunload` event handler never knows what user is attempting to do and the actual URL for (4) in that case.

Hence it is impossible for an electron app to simulate what a browser can do. Therefore there is a loss-of-functionality if #2579 remains unfixed (which is quite likely?).

**Comment by deepak1556** [comment]
Can you provide a test case of what you are trying to achieve, Thanks!

**Comment by sltam** [comment]
I want to implement the TODO such that all the 4 user actions work like what a browser would.

```
Random=<script>document.write(0^1000*Math.random())</script>
<hr>
<a href="http://www.example.com">1. visitng a link</a>
<button onclick="location.reload()">2. reload (or ctrl-R/cmd-R)</button>
<button onclick="history.back()">3. back (or alt-leftarrow/cmd-leftarrow)</button>
<button onclick="window.close()">4. close (or alt-F4/cmd-W)</button>
<script>
if (!location.search) {
    // make sure history has something to go back
    location.search += '?next-page'
} else {
    window.onbeforeunload = (e) => {
        if (/Electron/.test(navigator.userAgent)) {
            const electron = require('electron')
            const { dialog } = electron.remote
            dialog.showMessageBox(electron.remote.getCurrentWindow(), {
                message: 'Do you want to leave this page?',
                buttons: ['Cancel', 'Proceed'],
            }, (button) => {
                if (button === 1) {
                    // TODO
                    dialog.showMessageBox(null, { message: "Now I want to visit the link or reload or close depending on what the user triggered, but I don't know what it is." })
                }
            })
            return true // preventDefault
        } else {
            // ask user for permission the cross-browser way
            return e.returnValue = 'dialog text (deprecated)'
        }
    }
}
</script>
```

**Comment by deepak1556** [comment]
Sorry for the delay and thanks for the test case!

We can do two things here, either patch blink https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/page/ChromeClient.cpp?l=116 and bring back the old Electron behavior to determine the result of `AtomJavaScriptDialogManager::RunBeforeUnloadDialog` based on the `event.returnvalue` or the second version would be to implement the confirmation dialog as a part of Electron and use its result. The second choice sounds better and its what chrome does, but I am not sure why we weren't doing it from the beginning.

/cc @zcbenz @kevinsawicki

**Comment by pfrazee** [comment]
I'm +1 emulating the Chrome behavior for Webviews. It looks like, right now, a webpage can block navigations away using:

```js
window.onbeforeunload = function() {
  return true;
};
```

**Comment by pfrazee** [comment]
I ended up solving this with https://github.com/beakerbrowser/beaker/commit/2b722936280c1f16e5bab92eafaabc7ca040a567.

**Comment by pfrazee** [comment]
^ Note that I had to

 1. Turn `window.onbeforeunload` into a setter, to capture what the sites set it to
 2. Wrap `window.addEventListener` (oof)

So it would really be preferable to get the default Chromium behaviors.

That said, one thing that wasn't happening at all was, the `onbeforeunload` wasn't getting called when a webview is *closed*, which is unsurprising when you think about it. But, that's obviously something I need. If Electron were to provide standard behaviors for onbeforeunload, I'd need it to support the close event too, otherwise I'm still up a creek and will still need my hacks.

**Comment by miniak** [comment]
@pfrazee is this issues still relevant?

**Comment by sltam** [comment]
I no longer develop that electron app, so I'm afraid I don't even know if this is still an issue or not
