### ISSUE TITLE
Menu Accelerator Changes Depending on Keyboard Layout

### ISSUE THREAD

**Issue by Ben3eeE** [electron/electron#8741]
* Electron version: 1.4.15
* Operating system: Windows 10

### Expected behavior

The menu accelerator should stay the same regardless of keyboard layout selected in the os settings.

### Actual behavior

The menu accelerator changes depending on the selected keyboard layout.

### How to reproduce

1. `git clone https://github.com/electron/electron-quick-start `
1. `cd electron-quick-start`
1. `npm install`
1. Add the following code:
```JavaScript
const {Menu} = require('electron')

const template = [
  {
    label: 'Issue',
    submenu: [
      {
        label: 'Toggle comments',
        accelerator: 'Ctrl+/',
        click (item, focusedWindow) {
          console.log("hi")
        }
      }
    ]
  }
]

const menu = Menu.buildFromTemplate(template)
Menu.setApplicationMenu(menu)
```
5. **Expected:** The accelerator to be `Ctrl-/`. **Actual:** The accelerator is `Ctrl-/` with `English (United States) US keyboard` layout and `Ctrl-'` with `English (United States) Swedish keyboard` in the Windows 10 settings.

![electron menu](https://cloud.githubusercontent.com/assets/1058982/23234248/ba79764a-f951-11e6-87a9-457c19ad0e38.gif)

**Comment by zcbenz** [comment]
The `\` maps to `VKEY_OEM_5`, which seems to be `'` on Swedish keyboard. We should probably explicitly document which key the punctuations are mapped to.

To really solve this, we would have to deal with ICU when parsing accelerator, which goes too far. While we would like to fix this, I'm afraid it is probably an impossible task, and I'm closing this as won't fix.

A probably solution to this is to correctly show `VKEY_OEM_5` as `'` for Swedish keyboard, which is a bug of Chromium that `VKEY_OEM_5` is hardcoded to be `/`, and I suggest reporting it to Chromium.
