### ISSUE TITLE
webContents.executeJavaScript fails if no callback given

### ISSUE THREAD

**Issue by iffy** [electron/electron#8743]
* Electron version: 1.6.0
* Operating system: macOS

### Expected behavior

I think `webContents.executeJavascript('5+5').then(function(result) { console.log('result', result); })` should log `10` to the console.

### Actual behavior

The promise never fires.

### How to reproduce

```javascript
const {app, BrowserWindow, webContents} = require('electron');

app.on('ready', function() {
  win = new BrowserWindow();
  win.on('ready-to-show', () => {
    win.show();
  })
  win.on('closed', () => {
    win = null;
  });
  win.webContents.on('did-finish-load', () => {
    console.log('finished loading');
    // just promises
    win.webContents.executeJavaScript('5+5')
    .then(result => {
      console.log('result (no callback one)', result)
    })
    .catch(err => {
      console.log('error (no callback one)', err);
    })

    // promises with callback specified
    win.webContents.executeJavaScript('7+7', result => {
      console.log('callback result', result);
    })
    .then(result => {
      console.log('promise result (callback one)', result)
    })
    .catch(err => {
      console.log('error (callback one)', err);
    })

  });
  win.loadURL('data:text/html,<html><body>Hello</body></html>');
});
```

Running the above, I'd expect to see:

```
finished loading
result (no callback one) 10
callback result 14
promise result (callback one) 14
```

but instead I see:

```
finished loading
callback result 14
promise result (callback one) 14
```

### Possible solution

I suspect the problem is that [this line](https://github.com/electron/electron/blob/1f75df0253c7cee435f2783029ed26ea20ea7ad0/lib/browser/api/web-contents.js#L118) is:

```javascript
if (callback != null) callback(result)
```

when it should be

```javascript
if (callback) callback(result)
```

I think it's trying to call an `undefined` callback.  Which also means that an error is going unreported (second bug?)

**Comment by MarshallOfSound** [comment]
Looks to be a regression caused in https://github.com/electron/electron/commit/8e203592e25db081dc68db086938157d0847f169#diff-940e61f1a69c6bbbeb31968b6fc49d1cR117

**Comment by kevinsawicki** [comment]
> I think it's trying to call an undefined callback.

`undefined != null` evaluates to `false` so I don't think it is trying to to call an `undefined` callback.

**Comment by MarshallOfSound** [comment]
Hm, good point.  Will investigate further 👍
