### ISSUE TITLE
distribution on Ubuntumate

### ISSUE THREAD

**Issue by tryvy** [electron/electron#8747]
hi! I'm trying create a distribution app for ubuntu mate on a Raspberry 3 model B, only can run the app using the console with electron, Is there a way to create a distribution build app?

**Comment by groundwater** [comment]
Hi @tryvy. Can you provide more information about this. I've never used ubuntu mate.

**Comment by Kilian** [comment]
Hi @tryvy You can create releases using [electron-packager](https://github.com/electron-userland/electron-packager). I believe raspberry Pi runs arm. Electron-packager can compile to armv7l. Do read the documentation, but you can probably get quite far with `electron-packager ./ myAppName --platform=Linux --arch=armv7l`

**Comment by zcbenz** [comment]
Closing since there is a node module solving this.

**Comment by tryvy** [comment]
what module? @zcbenz
