### ISSUE TITLE
bug about  load ppapi flash under windows.

### ISSUE THREAD

**Issue by koalaylj** [electron/electron#8748]
* Electron version: 1.6.1 
* Operating system: win10 x64

### Actual behavior
I am creating a multi-window program,the HTMLs are loaded from remote http server. when you click some button in main window, it will create a new window and show other page.
flash plays well in `_mainWindow`.
but if click a link or button in main page , when it created a new window `W`, the  `W` can not play flash, the page in `W` shows `Couldn't load plugin` with a black background.
type `navigator.plugins` under devtools of `W` , it shows `ppapi flash` plugins have been loaded. 

but all this works well with electron 1.3.5. 

### How to reproduce
my code is here.
```javascript
let ppapi_flash_path;
let  ppapi_flash_ver = '24.0.0.221';

if(process.platform === 'win32' && process.arch === 'x64') {
  ppapi_flash_path = path.join(__dirname, 'plugins', 'pepflashplayer64_24_0_0_221.dll');
} else if(process.platform === 'win32' && process.arch === 'ia32') {
  ppapi_flash_path = path.join(__dirname, 'plugins', 'pepflashplayer32_24_0_0_221.dll');
} 

app.commandLine.appendSwitch('ppapi-flash-path', ppapi_flash_path);
app.commandLine.appendSwitch('ppapi-flash-version', ppapi_flash_ver);

function ready() {

  _mainWindow = new BrowserWindow({
    width: 1440,
    height: 900,
    minHeight: 600,
    minWidth: 800,
    webPreferences: {
      nodeIntegration: false,
      plugins: true
    }
  });

  _mainWindow.loadURL('http://abc.com/index.html');

  _mainWindow.on('closed', function() {
    _mainWindow = null;
  });
}

//code in http://abc.com/index.html may be like this
$(function() {
	$("#startGame").bind("click", ()=>{
		window.open("http://www.abc.com/mario.html");
	});
});
```

Any help is appreciated ~

**Comment by groundwater** [comment]
Hey @koalaylj. Big thanks for trying out 1.6.1!

I would like to narrow down where this bug might be coming from. The jump between 1.3.5 and 1.6.1 is fairly large. Can you verify if this works on the latest stable `1.4.15`?

**Comment by koalaylj** [comment]
Thanks for your reply @groundwater .
I found out this bug since v1.4.4,  v1.4.3 works well.

**Comment by kevinsawicki** [comment]
> I found out this bug since v1.4.4, v1.4.3 works well.

@koalaylj just to confirm, 1.4.4 and later do not work, but 1.4.3 does? THanks.

**Comment by koalaylj** [comment]
@kevinsawicki   yes

**Comment by kevinsawicki** [comment]
@koalaylj looks like this behavior did change in 1.4.4 via this pull request, https://github.com/electron/electron/pull/7520

Opened windows no longer inherited the full `webPreferences` settings of the parent window, only the  `nodeIntegration` value.

You can address this by adding the following to your app:

```js
_mainWindow.webContents.on('new-window', (event, url, frameName, disposition, options) => {
  options.webPreferences.plugins = true
})
```

This will enable plugins on an window opened from your main window.

**Comment by yamakasi303** [comment]
0
down vote
favorite
	

i have this code for convert website to exe file using electon js but i have problem inside the website there are .swf files and i search alot about how i can run .swf files but it's not work i was traing by plugin it's name "Pepper Flash Plugin" this is the url for this plugin

https://electron.atom.io/docs/tutorial/using-pepper-flash-plugin/

and i was searsh about "pepflashplayer.dll"

and put it on the root on prject directory and also not work

any help please

file:main.js

'use strict';

const electron = require('electron');
const path = require('path');
const app = electron.app;  // Module to control application life.
const BrowserWindow = electron.BrowserWindow;  // Module to create native browser window.



// Specify flash path, supposing it is placed in the same directory with main.js.
let pluginName
switch (process.platform) {
  case 'win32':
    pluginName = 'pepflashplayer.dll'
    break
  case 'darwin':
    pluginName = 'PepperFlashPlayer.plugin'
    break
  case 'linux':
    pluginName = 'libpepflashplayer.so'
    break
}
app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, pluginName))

var mainWindow = null;

app.on('ready', function() {
    mainWindow = new BrowserWindow({width: 1100, height: 900, webPreferences: {
      plugins: true
    }});

  // and load the index.html of the app.
  mainWindow.loadURL('file://' + __dirname + '/cd/cd/START.html');
});

**Comment by kevinsawicki** [comment]
Merging this into https://github.com/electron/electron/issues/3751 since this issue is because the options aren't inherited by new windows, see https://github.com/electron/electron/issues/8748#issuecomment-284894236 for a workaround.
