### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by pronebird** [electron/electron#8750]
Please update npm, it did stuck at 1.4.15, see: https://www.npmjs.com/package/electron

`npm outdated` gives funny output too:

```
Package           Current   Wanted  Latest  Location
electron            1.6.1    1.6.1  1.4.15
```

or are we in beta stage since 1.5?

Probably related to #8751

**Comment by watilde** [comment]
I just confirmed that electron tagged `v1.4.15` as `latest`:
```
$ npm view electron | grep latest
  'dist-tags': { latest: '1.4.15', beta: '1.6.1' },
```

I think this is because `>v1.5.0` are still under beta as you said.

**Comment by enlight** [comment]
`npm install electron@beta` if you want the 1.6 beta, otherwise wait for the stable release.

**Comment by groundwater** [comment]
I would be in favor of adding documentation around this.
