### ISSUE TITLE
Beta release tags are erroneous / beta versions shouldn't be spec'd on http://electron.atom.io

### ISSUE THREAD

**Issue by avoidwork** [electron/electron#8751]
* Electron version: ^1.5.0
* Operating system: N/A

### Expected behavior
Stable release version advertised on public website. Pre-release/beta versions would have "-beta" or "-rc$n" on the version tag so it could be understood without visiting the github releases/tags view.

### Actual behavior
Pre-release (beta) version advertised on public website & misinformation with semver tags.

### How to reproduce
Look at http://electron.atom.io & https://github.com/electron/electron/releases

An example of how tags should look with meta information (from [semver.org](http://semver.org))

![screen shot 2017-02-23 at 7 17 56 am](https://cloud.githubusercontent.com/assets/369698/23258880/4d79e92a-f998-11e6-9e1e-fd8f192415bf.png)

**Comment by groundwater** [comment]
Hi @avoidwork. Can you expand on the problem you're encountering?

We're following the dist-tags model that npm uses to distribute their CLI.

You should only end up with a beta release if you choose so, since `npm install` pulls from the `latest` tag by default. If you're experiencing other behaviors, we would consider that a bug and would like to hear about that.

**Comment by avoidwork** [comment]
Sure, I unintentionally shipped a product with a beta build of electron prior to the "pre-release" label applied to the release, which is meta that only exists in github and not in npm or anything else that uses the value in package.json.

Please use semver tags, not whatever npm is using; e.g. `-beta` or `-rc1`, this would let automated systems ignore the releases because they are not stable. My own products use these quite easily/well and it's beneficial for everyone downstream as the information is in the system that's relevant to the task at hand, and not in github.

**Comment by avoidwork** [comment]
@groundwater as far as I can tell the `dist-tag` is just another set of meta data separate; it literally sits in `"dist-tag"` which is not `"version"`. At best that is a poor bandaid for a bug in npm.

**Comment by avoidwork** [comment]
@groundwater as per this comment: "Versions and tags occupy the same namespace on the install command and dependencies object. The only way to make it predictable and reasonable is to not allow a tag that is also a valid version." I'd say that npm's approach is fundamentally wrong; versions are tags, and because they've introduced a cli that lets you mangle things further means it's not something you should base your releases on. this problem exists in npm only, not anything referencing package.json without implicit knowledge.

Quote is from: https://github.com/npm/npm/issues/6846

**Comment by groundwater** [comment]
Hi @avoidwork. Can you describe how your CI pulling and bundling the electron version?

Calling `npm install` should not pull in any beta versions be default. Are you calling the GitHub releases API directly?

**Comment by avoidwork** [comment]
No, atm the moment it's manually set to 1.4.15; for this product we do have package comparisons but electron has been moving based on the website with a validation check on release notes online; the last 2 releases being 'pre-release' were flagged as such after the fact, but if it was known at the time it could've been expressed clearly in the tag.

**Comment by groundwater** [comment]
Hey @zeke I wonder if we should mention that folks pulling from the releases API should ensure they check for the `prerelease` property? I would be in favor of some documentation around this.

**Comment by pronebird** [comment]
It's strange that you show pre-release builds on `electron.atom.io`. I mistakenly thought that 1.6.1 is stable.

**Comment by MarshallOfSound** [comment]
@pronebird I believe that was fixed in https://github.com/electron/electron.atom.io/pull/673 though it isn't applied retroactively

**Comment by zeke** [comment]
> It's strange that you show pre-release builds on `electron.atom.io`

Yeah that was a bug. My bad. Fixed it [last night](https://github.com/electron/electron.atom.io/pull/696/files).

**Comment by thompsnm** [comment]
I would second that pre-release/beta versions should have "-beta" or "-rc$n" on the version tag. You're right that `npm install` only pulls from the `latest` tag. However, I'm using `npm update` in my build process, and that command appears to pull from any tag:

    $ npm --version
    4.1.2

    $ npm install --save-dev electron

    > electron@1.6.7 postinstall /Users/nathan.thompson/Projects/tmp/electron-install-test/node_modules/electron
    > node install.js

    electron-install-test@1.0.0 /Users/nathan.thompson/Projects/tmp/electron-install-test
    └── electron@1.6.7

    npm WARN electron-install-test@1.0.0 No description
    npm WARN electron-install-test@1.0.0 No repository field.

    $ cat package.json | grep "electron"
        "electron": "^1.6.7"

    $ npm update

    > electron@1.7.0 postinstall /Users/nathan.thompson/Projects/tmp/electron-install-test/node_modules/electron
    > node install.js

    electron-install-test@1.0.0 /Users/nathan.thompson/Projects/tmp/electron-install-test
    └── electron@1.7.0

    npm WARN electron-install-test@1.0.0 No description
    npm WARN electron-install-test@1.0.0 No repository field.

While `npm update` is happy to install from any npm tag, it _will_ adhere to the node-semver `satisfies` call. So if you used a prerelease tag on your version (i.e. `1.7.0-beta`) it [would not satisfy the caret range `^1.6.7`](https://github.com/npm/node-semver/tree/8fff3050401397e99aaf7a118015c0e33884c3f8#prerelease-tags), and `npm update` should ignore it.

**Comment by zeke** [comment]
Now I remember why I stopped running `npm update` years ago.

**Comment by zcbenz** [comment]
Closing since the website shows correctly now, and we are using prerelease tag for npm releases..
