### ISSUE TITLE
navigator.geolocation.getCurrentPosition freezes thread

### ISSUE THREAD

**Issue by pronebird** [electron/electron#8754]
* Electron version: 1.6.1
* Operating system: macOS

### Expected behavior

navigator.geolocation.getCurrentPosition runs in background

### Actual behavior

the entire UI is frozen

### How to reproduce

```js
    navigator.geolocation.getCurrentPosition((pos) => {
      console.log('POS: ' + pos);
    }, (err) => {
      console.log('Geolocation error: ', err);
    }, {enableHighAccuracy: false});
```

**Comment by deepak1556** [comment]
Are you seeing the freeze only on OSX or any other platform too ? I am unable to reproduce the issue with above snippet on linux.

**Comment by pronebird** [comment]
@deepak1556 I only test on macOS at the moment, entire UI freezes until error returned (in my case I don't have GOOGLE_APIKEY set yet)

**Comment by cumajkeee** [comment]
Only on MacOS, Windows works fine.

**Comment by pronebird** [comment]
Set `process.env.GOOGLE_API_KEY = "<GOOGLE API KEY>";` before creating any windows. Location works but still freezes during request. So API key presence does not change anything.

**Comment by TheMSB** [comment]
I would like to add that I am currently experiencing a fatal crash on macOS when calling `navigator.geolocation.getCurrentPosition`

**Comment by farfromrefug** [comment]
Just found out that it was why my app was freezing!
Happening on macOs and Windows.
Also i have setup ```GOOGLE_API_KEY``` at app startup (long before i make the call to ```getCurrentPosition```
