### ISSUE TITLE
Allow to drag multiples files with contents.startDrag()

### ISSUE THREAD

**Issue by popod** [electron/electron#8755]
When use contents.startDrag(path), It would be great to allow us to drag multiple files by passing an array of paths. Is this improvement realistic ?

**Comment by kevinsawicki** [comment]
@popod have you tried passing a `files` array of string paths to `startDrag`? I think it is supported but undocumented.

https://github.com/electron/electron/blob/62f4a77755a057609cfccf6d824ed76e41a0fb57/atom/browser/api/atom_api_web_contents.cc#L1348-L1350

**Comment by kevinsawicki** [comment]
Something like `contents.startDrag({files: ['file1', 'file2'], icon: '/path/to/icon.png'}`

**Comment by popod** [comment]
I've juste tested and this works well with `files`. I've improve this doc in this pull request #8760

**Comment by popod** [comment]
@kevinsawicki `files` seem not work on Window.. Is it possible to test that and fix it if needed ? Thanks

**Comment by timfish** [comment]
@popod I'm seeing the same on Windows 10. Just a single file gets saved in Explorer. 

Before I file a bug, did you manage to get it working?

**Comment by popod** [comment]
@timfish No I've not solved this problem for now.

**Comment by timfish** [comment]
@popod I opened [a bug](https://github.com/electron/electron/issues/9019). It appears its a known issue.
