### ISSUE TITLE
Allow to open multiples files with shell.openItem()

### ISSUE THREAD

**Issue by popod** [electron/electron#8756]
With shell.openItem(), It would be great to allow us to open multiple files by passing an array of paths (or providing a function shell.openItems()). By example, if I would open many pictures with preview on macOS they will all been open in the same windows. This is not actualy the case if I call many times shell.openItem().

**Comment by groundwater** [comment]
Hi @popod. I would like to help you expand this idea to give it the best chance of being approved/implemented. More information is always better, and I've started recommending folks follow the [Rust RFC Template](https://github.com/rust-lang/rfcs/blob/master/0000-template.md) for proposing new features.

**Comment by zcbenz** [comment]
Most platforms only provide API to open one file in shell, in your case you have to manually execute the application and pass files as command line parameters.
