### ISSUE TITLE
Desktop notifications stopped working after setting UserAgent

### ISSUE THREAD

**Issue by akashnimare** [electron/electron#8759]
* Electron version: 1.4.15
* Operating system: OS X

### Expected behavior
Desktop notifications should work even after setting a new user-agent via [win.loadURL](https://github.com/zulip/zulip-electron/blob/06737ce62968d7ce938254869b410a4d61984319/app/main/index.js#L125-L128).
I have set a new user-agent via
``` js
win.loadURL(targetURL(),
{
   userAgent: "Myuseragent"
});
``` 

### Actual behavior

Desktop notifications stopped working although HTML5 type notifications do works - 
![image](https://cloud.githubusercontent.com/assets/2263909/23276980/4281522a-fa32-11e6-8a1b-21fbaddbd177.png)

## Update 
desktop notifications do works If I add this new user-agent to the default user-agent.
```js
win.loadURL(targetURL(),
{
    userAgent: "Myuseragent" + win.webContents.getUserAgent()
});

**Comment by kevinsawicki** [comment]
@akashnimare can you include an code example of how you are creating the notification that is failing to appear?

**Comment by akashnimare** [comment]
The notifications are being created by the webapp and I'm just passing that URL to electron app. The notifications are standard native notifications.
Web app - https://github.com/zulip/zulip
Electron app - https://github.com/zulip/zulip-electron

**Comment by kevinsawicki** [comment]
@akashnimare it looks like zulip checks that the user agent contains `webkit` before sending notifications, https://github.com/zulip/zulip/blob/4092aab6202d9a3ff127f19c57d2d806bf858663/static/js/notifications.js#L44-L52

Could this be causing the issue you are seeing?

**Comment by akashnimare** [comment]
cc @timabbott

**Comment by timabbott** [comment]
@akashnimare yikes, we should update `notifications.js`, but I think to avoid breaking existing servers, maybe we should add "webkit" to the list to make it do the right thing for older versions with the existing `notifications.js` code?

**Comment by kevinsawicki** [comment]
> maybe we should add "webkit" to the list to make it do the right thing for older versions with the existing notifications.js code?

Closing this out since this doesn't appear to be an Electron issue.
