### ISSUE TITLE
Compiling for ARMv6

### ISSUE THREAD

**Issue by abejfehr** [electron/electron#8765]
Is it possible to cross-compile to ARMv6? The current binaries are only ARMv7 but I'm trying to get a kiosk app running on my Raspberry Pi B+ which I'm quickly realizing is out-of-date.

Thanks!

**Comment by abejfehr** [comment]
Actually that's my mistake, apparently no one is able to help with ARMv6 according to [this past issue](https://github.com/electron/electron/issues/6102). I guess I'm screwed.

**Comment by kevinsawicki** [comment]
It may be possible but is not something we've tried and we don't publish prebuilt versions of libchromiumcontent with that architecture so it would need to be built there too.

There is still some arm 6 config in the build files, https://github.com/electron/electron/blob/d01250eceb6d567378df1de44b5631246c1a523b/toolchain.gypi#L72-L78

You may want to give it a try and see how far it gets.

**Comment by Zhairgling** [comment]
@abejfehr @kevinsawicki  Do you get it working ?

**Comment by abejfehr** [comment]
@Zhairgling Nope, I gave up. It was _far_ too much work for what I wanted to do.

**Comment by Zhairgling** [comment]
@abejfehr So I will try, does  I should know anything?

**Comment by zeke** [comment]
Hey @Zhairgling. I can't offer you much expertise in this area, but I'm curious: Did you end up giving this a try?

**Comment by Zhairgling** [comment]
so sorry I can't do it for now

2017-06-15 21:26 GMT+02:00 Zeke Sikelianos <notifications@github.com>:
