### ISSUE TITLE
Calling show() on an already open modal causes the parent to become unusable

### ISSUE THREAD

**Issue by Kangaroux** [electron/electron#8768]
Electron version: 1.4.15

Node version: 6.9.5

### How to reproduce

Create a window and a modal

```
const win = new BrowserWindow();

const modal = new BrowserWindow({
    parent: win,
    modal: true
  });

modal.on("closed", function() {
    modal = null;
});
```

Verify that the modal appears above the window as expected, you can't click past it. Once the modal is closed you can interact with the parent.

Now call `modal.show()`

```
const win = new BrowserWindow();

const modal = new BrowserWindow({
    parent: win,
    modal: true
  });

modal.show();

modal.on("closed", function() {
    modal = null;
});
```

The modal appears as it should and works, until you close it. The parent window now becomes unusable because it thinks the modal is still active.

**Comment by groundwater** [comment]
Possibly related to #8677
