### ISSUE TITLE
Where can I find native_window_views.cc file? I can't find it in my electron path

### ISSUE THREAD

**Issue by radencode** [electron/electron#8770]
* Electron version:
* Operating system:

**Comment by radencode** [comment]
Why was this closed?

**Comment by KagamiChan** [comment]
https://github.com/electron/electron/blob/master/atom/browser/native_window_views.cc
here it is
btw,
> GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the community or to the Slack Channel.
