### ISSUE TITLE
Blank page will somehow show up when webview tag loads a url at first time.

### ISSUE THREAD

**Issue by qazbnm456** [electron/electron#8771]
* Electron version: 1.6.1
* Operating system: macOS Sierra

### Expected behavior

No blank page shows when webview tag loads a url at first time.

### Actual behavior

As described [here](https://github.com/qazbnm456/lulumi-browser/issues/3).

### How to reproduce

**It happened to my project when I upgraded electron to version 1.6.1.** Never happened before when I developed with electron version 1.4.15.

Link to my project: [lulumi-browser](https://github.com/qazbnm456/lulumi-browser)

**Comment by groundwater** [comment]
Hi @qazbnm456. Thanks for trying 1.6.1! This sounds undesirable for sure.

Are you able to put together a minimized repro-case? That would help speed diagnosis along.

**Comment by qazbnm456** [comment]
@groundwater 

I've tried to replicate a minimized repro-case, but sadly I failed to create one now. Will notify you when I create one.

Besides, after browsing the issues here, I think it's highly related to https://github.com/electron/electron/issues/8505 since I got the same problem with electron version 1.5.0.

**Comment by javan** [comment]
Not sure if this is related, but I've noticed that `document.visibilityState` is always `hidden` initially in our (Basecamp's) app on Electron 1.6.1. I too have tried to reproduce with a minimal fresh app and have failed so far. Seems to be a subtle timing issue since it doesn't *always* happen.

Electron 1.6.1
![screen shot 2017-02-25 at 4 30 44 pm](https://cloud.githubusercontent.com/assets/5355/23336059/51c70742-fb78-11e6-8d25-09dae7c0f211.png)

Electron 1.4.15
![electron-1-4-15](https://cloud.githubusercontent.com/assets/5355/23336061/5df6e906-fb78-11e6-9e63-415b2289eecc.png)

**Comment by saenzramiro** [comment]
Same here, my app [Rambox](https://github.com/saenzramiro/rambox) use a lot of WebViews to load each service but if I tried to upgrade Electron to 1.6.1 (also tried in 1.5.0) the services are not rendering.

I noticed that if I reload the main page and switch to a service tab ASAP, the content of the service is displayed.

**Comment by javan** [comment]
I've worked around this by ensuring the host page is visible before add `<webview>`s:
```js
function awaitDocumentVisibility(callback) {
  if (document.visibilityState === "visible") {
    callback()
  } else {
    const handler = function() {
      if (document.visibilityState === "visible") {
        document.removeEventListener("visibilitychange", handler)
        callback()
      }
    }
    
    document.addEventListener("visibilitychange", handler)
  }
}

awaitDocumentVisibility(function() {
  // Append <webview> here
})
```

**Comment by javan** [comment]
Additional note: My app's window is initially hidden and then shown on `ready-to-show` (like https://electron.atom.io/docs/api/browser-window/#showing-window-gracefully).

**Comment by qazbnm456** [comment]
## Update

To make it more clear, the content of the web page has been loaded already, but just cannot be rendered correctly, as another attached screenshot shows below.

<img width="1180" alt="2017-03-01 10 35 43" src="https://cloud.githubusercontent.com/assets/6451933/23443615/e159848a-fe6a-11e6-90e3-ec9b40ee31f0.png">

And my temporary [workaround](https://github.com/qazbnm456/lulumi-browser/commit/938bdba761825815513b8806faf2cb165a6b338f) for this is to add `setTimeout` to defer making webview load URL.

**Comment by kevinsawicki** [comment]
Are people configuring their webviews with a style of `visibility: hidden` initially?

Wondering if this is the same as https://github.com/electron/electron/issues/8505

**Comment by kevinsawicki** [comment]
> To make it more clear, the content of the web page has been loaded already, but just cannot be rendered correctly, as another attached screenshot shows below

Yeah, this sounds super similar to #8505, merging this into that issue.
