### ISSUE TITLE
ninja: fatal: chdir to 'out\R' - No such file or directory 

### ISSUE THREAD

**Issue by radencode** [electron/electron#8772]
* Electron version: 1.4.15
* Operating system: Windows 10

### Expected behavior
Should build electron

### Actual behavior

ninja: fatal: chdir to 'out\R' - No such file or directory
ninja: Entering directory 'out\R'
### How to reproduce
python script/build.py

**Comment by groundwater** [comment]
Hi @radencode, I'd like to ensure we're not missing a build step.

Can you confirm if you're starting from this step https://github.com/electron/electron/blob/master/docs/development/build-instructions-windows.md#bootstrapping doing the bootstrap first?

**Comment by radencode** [comment]
Hello @groundwater 

Yes I do, here is what I do

1) I clone the repo from Electron
2) Run `python script/bootstrap.py -v`
3) Run `python script/build.py`

And I get the error above. I'm not sure what I am doing wrong. I have installed python from their website, I have node js and Visual Studio installed as well.

**Comment by radencode** [comment]
@groundwater I fixed the issue, you can go ahead and close this. I just deleted everything and started over and it worked. I think python was not installed properly.

**Comment by amhoho** [comment]
me too

**Comment by radencode** [comment]
You too are having the same issue or you too have fixed it?

**Comment by ssu2030** [comment]
@radencode Thank you. I had the same problem. So I will look for related problems, 
than I link to the solution I found at atom.
LINK : https://discuss.atom.io/t/build-next-step-error/27185
          https://discuss.atom.io/t/application-distribution-question/27217
