### ISSUE TITLE
Option to set webrtc ip handling policy

### ISSUE THREAD

**Issue by myfrndjk** [electron/electron#8777]
Hi,

Electron web-view is leaking original IP through webRTC even though we are in VPN/Proxy

Do we have option to disable that in electron, brave is already doing this
https://github.com/brave/browser-laptop/commit/653e4db649c1e96e55f5b2c80a60f5db49b10cb3#diff-b95013a7d2996f174fdafb3bb3cfd7cb

Third party Add-ons are blocking webrtc  by accessing this API
chrome.privacy.network.webRTCIPHandlingPolicy.set({value: 'default_public_interface_only'});

It will be helpful if  we  expose this API in electron too.

How to replicate this:
_________________________
create a simple webview
Set proxy for that session/webview
visit https://browserleaks.com/webrtc
You can see your original IP even though you are in proxy

Thanks
Jk

**Comment by jkleinsc** [comment]
I would like to work on this issue.

**Comment by myfrndjk** [comment]
@jkleinsc Thanks for working on this.
Will it be available in 1.6.3
