### ISSUE TITLE
Local Jupyter Notebook server not loaded correctly

### ISSUE THREAD

**Issue by ajasja** [electron/electron#8779]
* Electron version: v1.4.15
* Operating system: Win7 64 bit

### Expected behavior

There is a problem connecting to a local jupyter notebook server using electron. 

### Actual behavior

Blank window appears

### How to reproduce

Start jupyter notebook server: `jupyter notebook`
This sets up a server at http://localhost:8888/. Try to connect to this address from electron.
`electron http://localhost:8888/`
The home page should load.

The page loads fine with chrome:
![image](https://cloud.githubusercontent.com/assets/19926/23344026/6acdeb04-fc75-11e6-9394-de92ae676bb8.png)

and nw.js `nw --url="http://localhost:8888/"`
![image](https://cloud.githubusercontent.com/assets/19926/23344030/80517888-fc75-11e6-982d-16a26d8cc913.png)

Also, electron correctly loads other pages, `electron https://google.com` works as expected.

**Comment by ajasja** [comment]
Additional info: using the developer tools I get two errors when loading http://localhost:8888/:
![image](https://cloud.githubusercontent.com/assets/19926/23344084/769b9c50-fc76-11e6-8361-8cc1fdad9ff3.png)

**Comment by groundwater** [comment]
Hi @ajasja. You may want to look at disabling node integration in your browser window here http://electron.atom.io/docs/faq/#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron.

It sounds like `require` is overloaded between node and Jupyter.

**Comment by ajasja** [comment]
@groundwater Thanks, using
 ```JavaScript
let win = new BrowserWindow({
  webPreferences: {
    nodeIntegration: false
  }
})
```

indeed solved the problem.
