### ISSUE TITLE
Callback registry throwing weird errors on 1.4.12

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#8780]
* Electron version: 1.4.12
* Operating system: macOS

### Expected behavior

No errors 😆 

### Actual behavior

Lot's of funky errors like so.

<img width="552" alt="screen shot 2017-02-27 at 12 46 09 pm" src="https://cloud.githubusercontent.com/assets/6634592/23346055/f731c99c-fcea-11e6-917d-7056ce7d46e7.png">
<img width="554" alt="screen shot 2017-02-27 at 12 46 25 pm" src="https://cloud.githubusercontent.com/assets/6634592/23346054/f731d400-fcea-11e6-9cc7-ae86121e46e0.png">

### How to reproduce

I tried to isolate the issue but couldn't, easiest way to see it is to clone [GPMDP](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-) and simply start it (`npm install && npm run build && npm start`).  But it's quite a big app so might be hard to trace.

**Comment by MarshallOfSound** [comment]
Initial investigation shows some kind of `close` event is being emitted on a stream across processes (I'm not aware that I'm doing that so I don't know what's going on).

**Comment by MarshallOfSound** [comment]
DevTron appears to show that a buffer is being streamed through IPC :confused:

<img width="1310" alt="screen shot 2017-02-27 at 12 52 40 pm" src="https://cloud.githubusercontent.com/assets/6634592/23346156/be83496c-fceb-11e6-9c05-eeb58be31867.png">

**Comment by groundwater** [comment]
Any chance I can assign this to you?  😁

**Comment by kevinsawicki** [comment]
@MarshallOfSound is this still an issue for you or can this be closed?

**Comment by MarshallOfSound** [comment]
@kevinsawicki I figured out what is was but couldn't reliably repro, basically using `electron.remote.net` caused a whole bunch of weird errors like this.

**Comment by zcbenz** [comment]
Closing since #9389 fixed a bug may cause this, let me know if it is still happening to you with the fix.
