### ISSUE TITLE
Blink features url is changed. Electron website needs to be updated.

### ISSUE THREAD

**Issue by wenshiqi0** [electron/electron#8781]
* Electron version:
1.4.15
* Operating system:
mac osx

### Actual behavior

the wrong url is https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/RuntimeEnabledFeatures.in. 

It is under http://electron.atom.io/docs/api/browser-window

### How to reproduce

the correct url is https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/RuntimeEnabledFeatures.json5

**Comment by MarshallOfSound** [comment]
@wenshiqi0 Could you submit a quick PR for this, should be a simple edit 👍 Thanks for pointing this out

**Comment by thesbros** [comment]
@MarshallOfSound Oh, I just did :)

**Comment by CapOM** [comment]
The correct url has changed again: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/runtime_enabled_features.json5

**Comment by aabbccsmith** [comment]
Haha, and again. Anybody know the new one?
