### ISSUE TITLE
I want to use the chrome native shortcuts "alt+r" to refresh devtool. How can I do?

### ISSUE THREAD

**Issue by weihong1028** [electron/electron#8784]
I can use "alt+r" in my chrome app.But it's not work in electron app.
And the chrome version is consistent.

**Comment by weihong1028** [comment]
I can use "alt+r" in my chrome app.But it's not work in electron app.

**Comment by wenshiqi0** [comment]
Without code, no one can understand. I guess you may not register the shortcuts.
By default electron.app will do this for you, unless you do cover the default menu.
Then you need to register these shortcuts by yourself.

The api is here http://electron.atom.io/docs/api/accelerator/

**Comment by groundwater** [comment]
Hi @weihong1028.

I think @wenshiqi0 is correct, and I will close this.

If you have another error, you can re-open it. Please include enough information for us to reproduce the same error. For example, what code are you running?

**Comment by weihong1028** [comment]
Thanks, I'll try it later.
