### ISSUE TITLE
The video of the desktop that captured by using DesktopCapturer is freezed after switch to another user then switch back

### ISSUE THREAD

**Issue by AmbrielLi** [electron/electron#8785]
The video of the desktop that captured by using DesktopCapturer is freezed after switch to another user then switch back

* Electron version: 1.4
* Operating system: win10

### Expected behavior

video should keep playing.

### Actual behavior

video is freeze.

### How to reproduce
1. launch app that capture desktop using DesktopCapturer.
2. switch to another user
3, switch back
4. video is freeze.

**Comment by groundwater** [comment]
Hi @AmbrielLi. Can you provide a link to the app?

**Comment by AmbrielLi** [comment]
Sorry, It's not in the public repo, here is the code I using DesktopCapturer to get the Video.
Functions:
`getScreen: (id, resolution) => {
    return new Promise((resolve, reject) => {
      let w = resolution.width;
      let h = resolution.height;

      const screenConstraints = {
        audio: false,
        video: {
          mandatory: {
            chromeMediaSource: 'desktop',
            chromeMediaSourceId: id,
            minWidth: w,
            maxWidth: w,
            minHeight: h,
            maxHeight: h
          }
        }
      };
      navigator.mediaDevices.getUserMedia(screenConstraints).then((stream) => {
        resolve(stream);
      }).catch( (e) => {
        console.log(e);
        reject(e);
      });
    });
  },

  getScreenInfo: (deviceId) => {
    let st = new Date();
    return new Promise((resolve, reject) => {
      desktopCapturer.getSources({types: ['window', 'screen']}, (error, sources) => {
        console.info('screen source get end at ', (new Date() - st) / 1000);
        if (error) {
          reject(error);
        } else {
          console.info(sources);
          resolve(sources.filter(item => {
            return item.name === deviceId;
          }));
        }
      })
    })
  },`

Code:
`VideoSources.getScreenInfo(s[0].deviceId).then(info => {
      VideoSources.getScreen(info[0].id, screenResolution).then(stream => {
        document.getElementById(s[0].label).src = URL.createObjectURL(stream);
        window.allTracks[0] = stream;
        this.setState({vs: true});
        let tempSource = s;
        tempSource[0].id = info[0].id;
        tempSource[0].resolution = screenResolution;
      });
    })`

**Comment by groundwater** [comment]
@AmbrielLi did you mean to close this issue?
