### ISSUE TITLE
printToPDF causes window size changes

### ISSUE THREAD

**Issue by rikkertkoppes** [electron/electron#8788]
* Electron version: 1.4.13
* Operating system: win 7 64 bit

### Expected behavior

prntToPDF should not have any visible side effects

### Actual behavior

When I printToPDF, the window briefly shrinks to the print page size (539px in my case). This causes css changes if there are media queries, which may be visible if transitions are involved. It also triggers mediaquery event.

### How to reproduce

create a page:

    <div>
        <button onclick="sendipc()">pdf</button>
    </div>
    <div id="main"></div>
    <script>
        let matcher = window.matchMedia('(max-width: 1024px)');
        matcher.addListener(() => {
            console.log(window.innerWidth);
        });
        function sendipc() {
            var ipc = window.require('electron').ipcRenderer;
            ipc.send('print');
        }
    </script>

handle the ipc message in the main process:

    ipc.on('print', (msg) => {
        mainWindow.webContents.printToPDF({}, () => {});
    });

When pressing the button, observe the media query events in the console log

Note: this is probably circumvented by rendering the pdf contents in a separate, hidden window and printing that to pdf. I'll try that next.

In any case, it took me quite a while to figure out that rendering to pdf caused window resizes, which caused the media queries to fire.

I can imagine this is desired behaviour, as we need a fixed size for the pdf render process. However, some improvements could be done

- make a note in the docs that the window will be resized while printing to pdf, this is not obvious
- add an option to printToPDF to print from a separate window, for which electron takes care of creating a snapshot of the current window and rerendering that in a hidden window.

**Comment by groundwater** [comment]
Hi @rikkertkoppes. Thanks for diagnosing this. That sounds pretty undesirable.

I would be curious if this still happens in the latest stable `1.4.15` and the beta `1.6.1`. There have been lots of Chromium updates, and sometimes we get fixes for free just by updating.

**Comment by rikkertkoppes** [comment]
1.4.15: still a problem ("5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36")
1.6.1: still a problem ("5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Electron/1.6.1 Safari/537.36")

**Comment by rikkertkoppes** [comment]
Just noticed that this is also a thing if you just actuall print (using window.print())

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by Vaggal** [comment]
This happens for me also in Electron 7.1.1 when I call the webContents.print() function.
