### ISSUE TITLE
Disable zoom

### ISSUE THREAD

**Issue by pronebird** [electron/electron#8793]
* Electron version: 1.6.1
* Operating system: macOS

I am still able to zoom electron app with hotkeys or pinch to zoom on macOS.

All of the following below is broken:

```js
// in renderer process
import { webFrame } from 'electron';

// fix zoom at 100%
webFrame.setVisualZoomLevelLimits(1, 1);
```

Related issue: #3609

### Expected behavior

Zoom should be entirely blocked

### Actual behavior

Zoom works

### How to reproduce

Add the following snippet in your electron app:

```js
// in renderer process
import { webFrame } from 'electron';

// fix zoom at 100%
webFrame.setVisualZoomLevelLimits(1, 1);
```

Now try zooming with pinch and hotkeys, i.e <kbd>⌘</kbd><kbd>+</kbd> and <kbd>⌘</kbd><kbd>-</kbd>

**Comment by tex0l** [comment]
Seeing this too on 1.4.15

**Comment by arantes555** [comment]
Found a workaround, at least for pinch-to-zoom on 1.4.15 : 
```javascript
document.addEventListener('mousewheel', e => { // Preventing the pinch-to-zoom
  if (e.ctrlKey) e.preventDefault()
})
```
(found on http://stackoverflow.com/questions/29929411/disable-pinch-zoom-in-webkit-or-electron#29994607 )

**Comment by timfish** [comment]
I can confirm this on 1.4.14. The deprecated `setZoomLevelLimits` still appears to work though.

**Comment by timfish** [comment]
@groundwater This is not macOS only btw. 

<kbd>CTRL</kbd>+<kbd>-</kbd> and <kbd>CTRL</kbd>+<kbd>+</kbd> still zoom on Windows 10 with both `setZoomLevelLimits` and `setVisualZoomLevelLimits`

**Comment by fandy** [comment]
Any updates on this? I'm also unable to disable zooming with HTML meta tags.

**Comment by Dexwell** [comment]
@fandy This still allows zooming with <kbd>Cmd</kbd><kbd>+</kbd> and <kbd>Cmd</kbd><kbd>-</kbd>, doesn't it?

**Comment by fandy** [comment]
It disables the hotkey zoom but I wasn't able to disable pinch and zoom.

**Comment by timfish** [comment]
The deprecated `setZoomLevelLimits` was the only thing that disabled pinch zoom for me.

**Comment by alebo611** [comment]
For me, running electron with the --disable-pinch flag works!

**Comment by u3u** [comment]
I use the following code to disable double-click zoom and hotkey scaling: 

``` javascript
import { webFrame } from 'electron'
webFrame.setZoomFactor(1)
webFrame.setZoomLevelLimits(1, 1)
webFrame.setVisualZoomLevelLimits(1, 1)
webFrame.setLayoutZoomLevelLimits(0, 0)
```

I tested it to work properly!
Thanks @fandy

**Comment by pronebird** [comment]
I am not able to reproduce this with electron `1.6.11`. There is no need to set anything but zoom level limits in order to block zoom:

```
webFrame.setZoomLevelLimits(1, 1);
```

**Comment by timfish** [comment]
@pronebird `setZoomLevelLimits` work fine but its marked as `Deprecated in v2`, so how will we achieve it then?

**Comment by pronebird** [comment]
@timfish  Ah true, I forgot it was marked deprecated. It's been a while since I revisited this issue.

**Comment by codebytere** [comment]
currently, when running on

Electron 1.7.8
MacOS Sierra 

with the following renderer code:
```js
const {webFrame} = require('electron');

        webFrame.setZoomFactor(1);
        webFrame.setVisualZoomLevelLimits(1, 1)
        webFrame.setLayoutZoomLevelLimits(0, 0)
```

i'm not able to pinch to zoom or use the hotkeys. Is this still an issue for others on Mac. And for WIndows users, is this still an issue if you're running the latest version of electron?

**Comment by JosephusPaye** [comment]
On Windows 10, using Electron 1.8.0 (beta).

The following doesn't disable zooming:

```js
// renderer.js
import { ipcRenderer, webFrame } from 'electron';

webFrame.setZoomFactor(1);
webFrame.setZoomLevelLimits(1, 1);
webFrame.setVisualZoomLevelLimits(1, 1);
webFrame.setLayoutZoomLevelLimits(0, 0);
```

It's still possible zoom with `Ctrl` and `+`/`-`/`0` hotkeys.

**Comment by poiru** [comment]
@JosephusPaye Do you have those shortcuts in your menu (maybe in the View menu)?

**Comment by JosephusPaye** [comment]
Hi @poiru,
 
The app doesn't have a menu. When it is built (using `electron-builder`), it doesn't zoom when pressing the hot keys.

However, when running using pre-built electron, it still allows for zooming (perhaps it's due to pre-built electron having a default menu with zoom shortcuts).

**Comment by bambooCZ** [comment]
If you are looking for a way how to prevent zoom from main process, you can use:

```javascript
let webContents = win.webContents;
webContents.on('did-finish-load', () => {
  webContents.setZoomFactor(1);
  webContents.setVisualZoomLevelLimits(1, 1);
  webContents.setLayoutZoomLevelLimits(0, 0);
});
```

**Comment by codebytere** [comment]
Since there appears to be a sufficient working solution for this in the main process, i'm going to go ahead and close this.

**Comment by kishe89** [comment]
@bambooCZ why this working? please tell me about it. i don't understand it.

```javascript
webContents.on('did-finish-load', () => {
    webContents.setZoomFactor(1);
    webContents.setVisualZoomLevelLimits(1, 1);
    webContents.setLayoutZoomLevelLimits(0, 0);
  });
```
why ZoomFactor set after did-finish-load event?

**Comment by bambooCZ** [comment]
@kishe89 I haven't ever said that it is the best nor the only possible solution. It is just a working solution. I haven't access to the app where I've used it, so I can not provide any more details. Feel free to improve it :).

My guess is that the zoom can change during the page load.

**Comment by Vamoss** [comment]
var app = require('electron')
    app.commandLine.appendSwitch('disable-pinch');

Solution found by mixing these two links:

1 - https://github.com/electron/electron/issues/8793#issuecomment-289791853

2 - https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

**Comment by theLMGN** [comment]
Sorry for necro'ing a 3 year old post, however since this is the first Google result for "Disable zooming electron", I couldn't disable the keyboard zooming shortcuts. I had to add a key handler to prevent Ctrl + minus or plus key presses. Here's an example:
```js
window.onkeydown = function(evt) {
    // disable zooming
    if ((evt.code == "Minus" || evt.code == "Equal") && (evt.ctrlKey || evt.metaKey)) {evt.preventDefault()}
}
```

**Comment by nickretallack** [comment]
@codebytere you seriously think these jank solutions are acceptable?

**Comment by fandy** [comment]
@nickretallack what is janky about these solutions?

**Comment by maxktz** [comment]
> Sorry for necro'ing a 3 year old post, however since this is the first Google result for "Disable zooming electron", I couldn't disable the keyboard zooming shortcuts. I had to add a key handler to prevent Ctrl + minus or plus key presses. Here's an example:
> 
> window.onkeydown = function(evt) {
>     // disable zooming
>     if ((evt.code == "Minus" || evt.code == "Equal") && (evt.ctrlKey || evt.metaKey)) {evt.preventDefault()}
> }

thanks man

**Comment by gitagogaming** [comment]
Attempting to disable zoom in 2025 and it is not working after trying the 'solutions' above I have gotten no where

```
  windows.mainWindow.on('did-finish-load', () => {
    windows.mainWindow.webContents.setZoomFactor(0.85);

    windows.mainWindow.webContents.setVisualZoomLevelLimits(1, 1);
    windows.mainWindow.webContents.setLayoutZoomLevelLimits(0, 0);
    });

```


The only thing that works is the mighty jank solution if disabling the keys via window.. 

```
window.onkeydown = function(evt) {
    // disable zooming
    if ((evt.code == "Minus" || evt.code == "Equal") && (evt.ctrlKey || evt.metaKey)) {evt.preventDefault()}
}
```

**Comment by leonardsimonse** [comment]
To add to comment by @gitagogaming:

If you don't need a menu and have already hidden it, you can just use .removeMenu() on the BrowserWindow instead
