### ISSUE TITLE
Webview in message dialog box

### ISSUE THREAD

**Issue by davej** [electron/electron#8794]
This is a feature request. I would like to be able to add webviews to a message dialog box so that I can achieve something similar to screenshot below.

![image](https://cloud.githubusercontent.com/assets/26971/23413897/1093e158-fdd2-11e6-9e29-ac14675746ac.png)

* Electron version: v1.4.15

**Comment by MarshallOfSound** [comment]
@davej This is something that I don't believe is possible and is very platform specific RE implementation.   I believe your best option is to make a modal browser window and add your own custom UI in their.  Let me know if I have misunderstood your request.
