### ISSUE TITLE
systemPreferences.subscribeNotification not triggered

### ISSUE THREAD

**Issue by inukshuk** [electron/electron#8796]
* Electron version: 1.6.1
* Operating system: macOS 10.11.6

### Expected behavior

I can't seem to receive any system preference notifications on Electron 1.6.1. For example, given something like this:

         const id = systemPreferences.subscribeNotification(
           'AppleShowScrollBarsSettingChanged', () => {
              this.broadcast('scrollbars', !hasOverlayScrollBars())
           })

I would expect the event to be fired when the scroll bar preferences change. This works fine with Electron 1.4.15 on macOS 10.12.3.

### Actual behavior

The callback does not fire when I change the scroll bar preferences. This is true for other events like `AppleAquaColorVariantChanged`, too -- changing the preference does not trigger the callback.

### How to reproduce

Interestingly, when I run the `default-app` and change aqua color variant in the preferences, I notice that the buttons in the Electron window do not update (other apps pick up the change immediately) -- this may be the same or a related issue.

**Comment by kevinsawicki** [comment]
I'm having a little trouble reproducing this, this is the example app I used:

```js
const {systemPreferences} = require('electron')

systemPreferences.subscribeNotification('AppleShowScrollBarsSettingChanged', () => {
  console.log('changed?')
})
```

Then ran `electron prefs.js` with this file and I see `changed?` get logged out each time I change the system preferences.

Can you verify this fails for you?

**Comment by inukshuk** [comment]
I cannot reproduce this anymore with Electron 1.6.3 (I didn't check 1.6.2) -- so this seems to be fixed already, thanks!

(I can still reproduce it with 1.6.1 / OS X 10.11, in case you would like me to debug this further)
