### ISSUE TITLE
Electron npm install AND node-gyp builds timeout on link

### ISSUE THREAD

**Issue by tyduptyler13** [electron/electron#8797]
Electron install is timing out due to the download url. I believe this is the case for all versions.

Ex: https://atom.io/download/electron/v1.4.15/iojs-v1.4.15.tar.gz

* Electron version: (none, can't get it installed)
* Operating system: Windows
* Method: Node and browser

### Expected behavior

I expect to get electron installed via `npm install -g electron`

I also expect `node-gyp configure --runtime=electron --target=1.4.15 --arch=x64 --dist-url=https://atom.io/download/electron` to download the headers and whatever else is required for building.

### Actual behavior

The link times out.

### How to reproduce

I have tested this several times via node-gyp, npm, and manually via the browser. They all timeout.

**Comment by kevinsawicki** [comment]
Sorry about this, it is due to S3 being down, https://status.aws.amazon.com/

https://twitter.com/githubstatus/status/836637202683678720

Will leave this open until it is resolved.

**Comment by tyduptyler13** [comment]
Cool. Thanks!

**Comment by tyduptyler13** [comment]
Looks like amazon resolved the issue.
