### ISSUE TITLE
`fetch` in preload script with context isolation crashes

### ISSUE THREAD

**Issue by jingyu9575** [electron/electron#8802]
* Electron version: 1.6.1
* Operating system: openSUSE Leap 42.2 (Linux 4.4.49, x86-64); also reproducible on Windows Server 2016 14393.

### Expected behavior

In BrowserWindow or webview with context isolation enabled, calling `fetch` in preload script should work.  

### Actual behavior

The page crashes and becomes blank. Devtools shows "Devtools was disconnected from the page".

### How to reproduce

Download electron-quick-start, add `webPreferences: {preload: path.join(__dirname, 'index.js'), contextIsolation: true}` to the BrowserWindow options in main.js. 

Create index.js: `console.log(fetch('http://example.com'))`

Run `electron .` and it crashes. If started without preload script, calling `fetch('http://example.com')` in Electron Isolated Context of devtools also causes crash.

----

I think the problem may be related with the Isolated Context's security origin. In my local electron build I add the following to CreateIsolatedWorldContext() in atom/renderer/atom_renderer_client.cc to enable cross origin requests, which can make `fetch` work.

    static auto universalOriginURL = blink::WebURL(GURL("app://universal"));
    static auto universalOrigin = []() {
        auto result = blink::WebSecurityOrigin::create(universalOriginURL);
        for (const char* scheme : {"http", "https"}) {
            blink::WebSecurityPolicy::addOriginAccessWhitelistEntry(universalOriginURL,
                blink::WebString::fromUTF8(scheme), blink::WebString(), true);
        }
        return result;
    }();
    render_frame_->GetWebFrame()->setIsolatedWorldSecurityOrigin(
        World::ISOLATED_WORLD, universalOrigin);

**Comment by kevinsawicki** [comment]
Thanks for reporting this with create details 👍

**Comment by kevinsawicki** [comment]
@jingyu9575 I've opened a pull request to address this in #8804, would you be able to try it out and see if it addresses the issue for you? Thanks.

**Comment by jingyu9575** [comment]
It works. Thanks!
