### ISSUE TITLE
Ambient light sensor

### ISSUE THREAD

**Issue by Exelord** [electron/electron#8803]
Hey,
Is it possible to access ambient light sensor on mac to determine the level of light? Of corse in the context of an electron because I want to implement a package for Atom which will relay on the level.

**Comment by kevinsawicki** [comment]
Looks like their are a couple node modules you can use to do this:

* https://www.npmjs.com/package/ambient-light
* https://www.npmjs.com/package/ambientlight

Closing this out.

**Comment by Fohlen** [comment]
With the [Ambient Light Sensor API ](https://developer.mozilla.org/en-US/docs/Web/API/Ambient_Light_Sensor_API) increasingly becoming a thing it would be good to know:

- can we enable experimental chrome modules in our electron build
- if so, how?
