### ISSUE TITLE
app.commandLine.appendSwitch('ignore-gpu-blacklist') creates huge visual bug (even the devtools)

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#8807]
* Electron version: 1.6.0, 1.6.1 and 1.6.2
* Operating system: OS X 10.9 Mavericks (inside a VM)

### Expected behavior

Using this command line switch doesn't create any bug with electron version 1.4.15, 1.5.0 or 1.5.1.

### Actual behavior

Screenshot of the bug running `electron-quick-start`:

<img width="1440" alt="screen shot 2017-03-02 at 4 57 24 am" src="https://cloud.githubusercontent.com/assets/797899/23481215/9cc60ed8-ff05-11e6-86ec-ef3400f83f5b.png">

When trying to interact (click on stuff) in the devtools, more visual bugs appear.

### How to reproduce

Not sure if it's OS X 10.9 related, or VM related, but OS X 10.9 inside a VM will have this problem.

Can't reproduce on the same machine with latest Sierra outside of a VM.

**Comment by MarshallOfSound** [comment]
Isn't the whole point of this being behind a flag in Chromium indicative of the fact it isn't stable?  If Chromium doesn't consider it stable I don't think we can declare problems with the flag a bug in Electron ❓

**Comment by romaincointepas** [comment]
@MarshallOfSound As this was a new bug and not happening in Google Chrome 56, I thought it was worth mentioning. However, I'm not sure what I did wrong the first time, but retrying again with Google Chrome 56 and it has indeed the same bug. Closing then :)

**Comment by Kagami** [comment]
Getting the same on Sierra. I guess macOS should be ok without that flag because there is only a tiny number of GPUs available on that platform and they all should be pretty decent.
