### ISSUE TITLE
After upgrade to 1.4.x, dev tools window blocks for several seconds on load

### ISSUE THREAD

**Issue by maxbrunsfeld** [electron/electron#8809]
Atom is in the process of [upgrading from Electron 1.3.13 to 1.4.15](https://github.com/atom/atom/pull/12696). We're seeing a significant performance regression in the dev tools. They're unresponsive for a long time after loading a window.

* Electron version: 1.4.15
* Operating system: MacOS 10.12

### How to reproduce

1. Build [this branch](https://github.com/atom/atom/pull/12696) of Atom.
2. Open an Atom window
3. Open the dev tools.
4. See that the dev tools are unresponsive for up to 10 seconds.

@nathansobo Was able to get a flame graph of the slow dev tools process using the `--remote-debugging-port` flag. Here is the graph:

![image](https://cloud.githubusercontent.com/assets/326587/23486915/b043a1b4-fe97-11e6-97f7-9bfd206ca322.png)

The `WebInspector.ProjectStore.addUISourceCode` method is being called a lot. We inspected the arguments passed to that method in the dev tools by doing this:

```js
const addUISourceCode = WebInspector.ProjectStore.prototype.addUISourceCode;
WebInspector.ProjectStore.prototype.addUISourceCode = function() {
  console.log(arguments);
  return addUISourceCode.apply(this, arguments);
};
```

We can see that this method is called for every source file in Atom.

/cc @iolsen

**Comment by nathansobo** [comment]
It's also worth noting that inline source map generation was disabled at the time of that capture, and I inspected some of the calls to `addUISourceCode` via monkey patching to confirm to inline source maps were present in the sources it was being called with. Source maps were also disabled in the dev tools.

**Comment by kevinsawicki** [comment]
@nathansobo @maxbrunsfeld can this be closed or are you still seeing this on Electron 1.6.x?

**Comment by maxbrunsfeld** [comment]
I'm not seeing this on Electron 1.6, so I think we can close it! Thanks!
