### ISSUE TITLE
Are there any limitations of Web Speech API ?

### ISSUE THREAD

**Issue by iidaapp** [electron/electron#8810]
* Electron version: newest
* Operating system: Mac / Windows

Are there any limitations of Web Speach API ?
(upper limit per day, text size, and whatnot)

I want to use Web Speech API (especially speech synthesis) for reading text on BrowserWindow.
And I checked below links:
https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html
https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API
https://github.com/electron/electron/blob/master/chromium_src/chrome/renderer/tts_dispatcher.h

But I can't find any answers for that...

**Comment by timfish** [comment]
You should probably set you own [google_api_key](https://electron.atom.io/docs/api/environment-variables/#google_api_key) as the default included in electron often gets 403 errors for too many requests.

**Comment by groundwater** [comment]
I think @timfish's answer is 👍

**Comment by iidaapp** [comment]
ok, I'll try it. thanks!

**Comment by thesbros** [comment]
I believe *speech synthesis* simply uses the operating system's TTS engine. There should be no limits on that. *Speech recognition* however, uses the Google API.

**Comment by iidaapp** [comment]
@thesbros 
I think so, too. I found the below topic and conversation in `blink-dev - Google Groups`.

> Yes, we use native operating system APIs to implement text-to-speech on Mac, Windows, and Android.
> https://groups.google.com/a/chromium.org/d/msg/blink-dev/l_dEtVp7lT0/ApifcBvuAiIJ

**Comment by mscreenie** [comment]
Really interested in the Speech API but looks like the current limits imposed by Google make it unusable in my case. There needs to be a really good offline ASR but that probably wont happen anytime soon.

**Comment by ceyxasm** [comment]
Hey, sorry if this question is not related directly to electron but I am unable to find any reference for the usage limits on of Web Speech API anywhere. Does anyone have a concrete idea??
All I find are users citing person experience with not mention of the same in any documentation.
