### ISSUE TITLE
setBadgeCount has no effect on Ubuntu with Unity

### ISSUE THREAD

**Issue by anatoli26** [electron/electron#8812]
### Intro
`const bindings = process.atomBinding('app')`
`bindings.unityLauncherAvailable` doesn't exist. It looks like the code from b22ce93 (issue #4193) is not executed.

### Versions:
* Electron version: 1.6.1
* Operating system: Ubuntu 16.04

### Expected behavior

The app should set the badge on the launcher item for the app.

### Actual behavior

Nothing happens.

### How to reproduce

`electron-quick-start/main.js` at line 29 place:
```
console.log(util.inspect(process.atomBinding('app'), false, null));
console.log("isUnityRunning? " + app.isUnityRunning());
console.log("setBadgeCount(" + 5 + ") returned: " + app.setBadgeCount(5));
console.log("getBadgeCount returned: " + app.getBadgeCount());
```
Output:
```
{ App: [Function: App],
  app: 
   App {
     getAppPath: [Function: getAppPath],
     setAppPath: [Function: setAppPath],
     setApplicationMenu: [Function: setApplicationMenu],
     getApplicationMenu: [Function: getApplicationMenu],
     commandLine: 
      { appendSwitch: [Function: appendSwitch],
        appendArgument: [Function: appendArgument] },
     launcher: 
      { setBadgeCount: undefined,
        getBadgeCount: undefined,
        isCounterBadgeAvailable: undefined,
        isUnityRunning: undefined },
     allowNTLMCredentialsForAllDomains: [Function],
     _events: 
      { login: [Function],
        'certificate-error': [Function],
        'select-client-certificate': [Function],
        quit: [Function],
        'web-contents-created': [Function],
        'session-created': [Function],
        'will-quit': [Function],
        ready: [ [Function: createWindow] ],
        'window-all-closed': [ [Function], [Function] ],
        activate: [Function] },
     _eventsCount: 10 },
  appendSwitch: [Function],
  appendArgument: [Function] }
isUnityRunning? true
setBadgeCount(5) returned: true
getBadgeCount returned: 5
```

**Comment by anatoli26** [comment]
Any update on this? Could it be that there are some issues with the included libraries?

**Comment by akashnimare** [comment]
Looks like `app.getBadgeCount()` is not supported on Linux. This works perfectly on macOS.

**Comment by anatoli26** [comment]
It should work, this is specified in the documentation and there's all the code needed for it to work. There's just some problem that needs to be fixed.

**Comment by akashnimare** [comment]
@deepak1556 could you please show some light on this? How do I make it work on Linux?

**Comment by anatoli26** [comment]
@groundwater, @deepak1556 should we expect any progress on this issue or it's in abandoned state? Just to know if to wait for the fix or implement own solutions in the apps using electron.

**Comment by zcbenz** [comment]
`setBadgeCount` is supported, but you have to have a `.desktop` file with your app to make it work:
https://electron.atom.io/docs/tutorial/desktop-environment-integration/#unity-launcher-shortcuts-linux

And even if it is a bug, I'm afraid we are not going to fix since Unity is a discontinued project.

**Comment by anatoli26** [comment]
Yes, I have an desktop file for the app. The badge is just not working, a bug IMO. Unity was discontinued by Canonical, but will be supported at least till 2021 and there are teams working on Unity, a lot of people will continue using it, so why not to check what's going on with this bug? This issue already contains some technical information about the problem.

**Comment by akashnimare** [comment]
Can you tell us what to add in that desktop file?

**Comment by owais** [comment]
Looks like Canonical will continue to support the unity launcher and appindicator API in the version of Gnome-Shell they ship. It would be great if we could get this working.

https://didrocks.fr/2017/08/23/ubuntu-gnome-shell-in-artful-day-7/

**Comment by lojmax** [comment]
Is there any progress on this? 
I use electron-builder and tried packaging `deb` which creates `.desktop` file in `usr/share/applications` and `appimage` that creates `.desktop` in `/home/${userName}/.local/share/applications. 
Tried using latest versions: 
electron-builder: 20.26.0
electron: 3.0.0-beta.3
As well as older ones. 
 But to no avail counter just doesn`t show up.

**Comment by digitalstaub** [comment]
did you try to set the desktopName according to the desktop file in the path?
I found it by trying the c api (because i don't wanted to rebuild while testing )
this is a simple c snippet to test the badge:
`
#include <unity.h>

int main(int argc, char **argv)
{
	g_type_init();

	UnityLauncherEntry* entry =
	unity_launcher_entry_get_for_desktop_id ("appimagekit-yourAppname.desktop");
	unity_launcher_entry_set_count (entry, 12);
	unity_launcher_entry_set_count_visible (entry, TRUE);

	GMainLoop *ml = g_main_loop_new (NULL, FALSE);
	g_main_loop_run (ml);

	return 0;
}
`
modify unity_launcher_entry_get_for_desktop_id, compile with 
`
gcc -o test test.c `pkg-config --cflags --libs unity`
`
and run.

if you found the right desktopName, put it into desktopName in package.json (the one of your app, not your build environment)

I'm using electron 1.8.7 / builder 20.14.7 and it works like a charme

**Comment by JMarteF** [comment]
Hey guys, I'm trying to use electron to package whatsapp and help me implement the counter option on Ubuntu 18.04 I would really appreciate it!

**Comment by jayarjo** [comment]
@zcbenz @anatoli26 What do you mean Unity is discontinued? Is a toolbar in the Ubuntu 18.04 based on some other technology/project?

**Comment by owais** [comment]
Unity is discontinued but the indicator and dock API exists in Gnome Shell, i.e, the shell used by Ubuntu now.

**Comment by jayarjo** [comment]
@owais then why it doesn't work, it clearly doesn't. Are you able to display a badge on the icon in the toolbar in Ubuntu 18.04?
