### ISSUE TITLE
navigator.geolocation.getCurrentPosition() call block UI on MacOS

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#8813]
* Electron version: 1.6.1
* Operating system: MacOS Sierra 10.12.3 (16D32)

### Expected behavior
Async request not block UI

### Actual behavior
Async request completely block UI 

### How to reproduce
navigator.geolocation.getCurrentPosition() call block UI on MacOS. On Windows everything works fine.
[geolocaiton block ui.zip](https://github.com/electron/electron/files/813394/geolocaiton.block.ui.zip)

**Comment by enlight** [comment]
Duplicate of #8754
