### ISSUE TITLE
Service workers can't require() modules

### ISSUE THREAD

**Issue by pronebird** [electron/electron#8814]
Service workers do not have `require` available. Is it a bug?

* Electron version: 1.6.0
* Operating system: macOS

### Expected behavior

service workers can include other libraries.

### Actual behavior

Well they can't

### How to reproduce

app.js

```js
var sw = __dirname + 'service.js';
navigator.serviceWorker.register(sw).then(function(registration) {
      // Registration was successful
      console.log('ServiceWorker registration successful with scope: ', registration.scope);
    }).catch(function(err) {
      // registration failed :(
      console.log('ServiceWorker registration failed: ', err);
    });
```

service.js:

```js
var path = require('path');
self.addEventListener('install', function(event) {
    console.log("Installing Service Worker"); // whatever
});
```

**Comment by tonyganch** [comment]
As far as I know, service workers are registered in a browser on client side, the code is not processed with Node, so there is no `require` available, hence this is expected behaviour.

**Comment by pronebird** [comment]
@tonyganch so like service workers are different from code running in renderer which is able to require() anything it wants?

**Comment by MarshallOfSound** [comment]
@pronebird AFAIK node.js is not thread safe so it does not operate inside service workers.  @zcbenz might be able to explain this better 😆

**Comment by pronebird** [comment]
OK I figured they use `importScripts` but it's not an alternative. I am closing this since I think it's limitation and is by design.

**Comment by redders6600** [comment]
For anyone else visiting this issue and getting disheartened, it ***is*** actually possible for you to require from within a webworker by setting `nodeIntegrationInWorker` to `true` for the `webPreferences` of your browser window. [See here](https://electronjs.org/docs/api/browser-window)

**Comment by trusktr** [comment]
I am setting `nodeIntegrationInWorker` to `true`, but no luck. I get `Uncaught ReferenceError: require is not defined` from the worker.

Do you have a working example?

**Comment by trusktr** [comment]
Nevermind, `require` inside a Worker works!

I made a bare minimal example here: https://github.com/trusktr/electron-web-worker-example.

There must be something wrong in my actual project (which is huge compared to that example, and is doing some custom TypeScript transpilation).
