### ISSUE TITLE
Privacy and chromium

### ISSUE THREAD

**Issue by sonicou** [electron/electron#8818]
I am looking for general information about the electron framework and privacy issues, especially regarding the use of chromium.

Since the google brower is well known for spying on its users, it would be great to know what the implications for electron based apps are. There have been some questions regarding this on the net but I did not find any official information about this. 

How exactly does electron deal with controversal features of chromium regarding privacy and connections to google in general?

**Comment by hackjutsu** [comment]
@sonicou Just curious, can you elaborate on "the google browser is well known for spying on its users"?

**Comment by sonicou** [comment]
I do not think this is the place for a general discussion about this and I believe the privacy issues of google (services) and their browser are well known. User tracking is basically their business model...

I would like to focus on thoses issues in regards to the use of chromium in electron.

**Comment by KagamiChan** [comment]
I'm just wondering which parts of chrome features make you feel like spying on you. It would be better to discuss on explicit and definite functionalities beacuse people may hold different understandings of "spying"

**Comment by tarruda** [comment]
@sonicou electron is not chromium, it is a framework for desktop applications that mainly uses the [content module](https://www.chromium.org/developers/content-module)(chromium component that abstracts the multi process model and blink web rendering) plus some extra handpicked chromium features(extensions and spell checking for example).

**Comment by sonicou** [comment]
@KagamiChan
That would be everything that transmits private data to external services and by extension even every functionality that connects to external network services at all. When I open my sligtly configured firefox, there is not a single bit that is transmitted until I open an url and then only the requsted webserver will see any connection. Therefore I would never use chromium, but this issue is about its use in electron and if I need to worry about its use of chromium.

@tarruda: the question is if the chromium components used in electron contain functionality that transmits data to google or has any other questionable functions regarding privacy

**Comment by zcbenz** [comment]
Merging this to https://github.com/electron/electron/issues/7306.
