### ISSUE TITLE
Application is reloading itself when I fire autoUpdater.checkForUpdates();

### ISSUE THREAD

**Issue by bjdash** [electron/electron#8819]
I have a app built as win64 with squirrel. When I fire autoUpdater.checkForUpdates(); ro check for updates, my application reloads (not restart) itself (the window stays open, in reloads the index.html). Then it fires all remaining events like **update-available**, **update-downloaded** etc . If I restart my application then I can see that its updated to the new version. But reloading itself while checking for update is not a good user experience.

**Comment by kevinsawicki** [comment]
@bjdash can you include some detailed steps and sample code to reproduce this issue? THanks.

**Comment by kevinsawicki** [comment]
This sounds very similar to https://github.com/electron/electron/issues/8943 so I'm going to merge it into that one since that one has more details provided.

Please subscribe to that issue for further updates.
