### ISSUE TITLE
Application is crashing after  upgrading electron to 1.6.1 

### ISSUE THREAD

**Issue by myfrndjk** [electron/electron#8821]
I upgraded my electron to 1.6.1 after that my app is getting crashed.
Situation: Once I click the button it is suppose to  make ajax call, but application is getting closed without any message
It is working fine with  the version 1.4.13.

Since there is no error message, I cant debug this.

"devDependencies": {
  "chai": "^3.5.0",
  "chai-as-promised": "^6.0.0",
  "chai-jquery": "^2.0.0",
  "electron": "^1.6.1",
  "electron-builder": "^7.14.1",
  "mocha": "^3.2.0",
  "spectron": "^3.6.0"
},

if I check electron version electron -v it gives 1.6.1
OS : Mac -sierra

If i do 'npm i electron-prebuilt' [This is installing 1.4.13 ] again application starts to work fine.

**Comment by deepak1556** [comment]
Can you provide a minimal example to reproduce the issue, thanks!

**Comment by myfrndjk** [comment]
Hi,

I am trying to create a small sample to reproduce this issue.
In the mean time I found this error by enabling log in command switch

`[41116:0303/234253.133759:ERROR:mach_port_broker.mm(43)] bootstrap_look_up: Unknown service name (1102)`

Thanks

**Comment by myfrndjk** [comment]
Hi,

Electron 1.6.1 is not supporting JQuery's  syntax.

How to replicate:

install electron 1.6.1

HTML:

`  <webview class="personal" id='manager' allowpopups webpreferences='allowRunningInsecureContent' autosize minwidth="1100" minheight="790" plugins disablewebsecurity src="" ></webview>`


once page is loaded in devtools try - `$('#manager')`
This is suppose to give you an object but in electron 1.6.1 it is  giving error.
`$('#manager').attr('src','www.example.com')`  -  if you try to insert src then application is getting closed without any warning , same syntax works well in electron version 1.4.15

However if you try `$('#manager')[0] ` it is giving a proper object.
In electron 1.4.13 --- $('#manager') --this is giving result
In electron 1.6.1 --- $('#manager')[0] --this is giving result

document.getelementbyId('manager') is working fine in both the electron version.

I tried with JQuery version 1.12.4 and 3.1.1 same error.

Thanks
Jk

**Comment by zcbenz** [comment]
Sorry but we are unable to fix this without a minimal reproducible case.
