### ISSUE TITLE
Electron doesn't respect win10 scaling factor.

### ISSUE THREAD

**Issue by kirilloid** [electron/electron#8823]
Reproduced not on bare Electron engine, but on the Slack app, the Grammarly app and "Electron API Demos" app so I consider that a bug in the Electron itself.

* Electron version:
Various, including the latest (just downloaded demo app)

* Operating system:
win10

### Expected behavior
Zoom to be considered, default font size should be normal.

### Actual behavior
Fonts and other elements become too small

### How to reproduce
Set zoom to non-100% level in display settings, see all desktop application resized, but not Electron apps. They keep their (most importantly) font-sizes at the same size in _hardware_ pixels.
By zoom I mean "Change the size of text, apps, and other items".

### Screenshot
Here's an illustration of a site opened in Chrome and a desktop electron app to give a perspective:
![app-example](https://cloud.githubusercontent.com/assets/296571/23547957/56680a60-0016-11e7-81ce-95cb89f9788e.png)

### Technical insight
In Chromium, win10 zoom setting affects `devicePixelRatio` property and works correctly contrary to Electron.
Keep in mind, that win10 supports different levels of zoom on different displays.

While the bug definitely have a workaround: E.g. VS Code (which is Electron-based AFAIK) handles that correctly and even allows changing level of zoom with `Ctrl`+`+`/`Ctrl`+`–`, it's about good defaults so app would work properly OOTB.

**Comment by kirilloid** [comment]
Wow, cool.

**Comment by kevinsawicki** [comment]
@kirilloid can you confirm if this is fixed for you in Electron 1.6.7?

**Comment by kirilloid** [comment]
I've installed 1.6.7 beta and everything seems OK.
Then I installed 1.6.6 into different folder and it also seems OK %-)

**Comment by kirilloid** [comment]
Both 1.6.6 and 1.6.7 seems OK in multi-monitor, moreover, the current slack app is also OK.
