### ISSUE TITLE
Updating tray.setImage while tray active overwrites pressedImage

### ISSUE THREAD

**Issue by anthonybruno** [electron/electron#8832]
* Electron version: 1.4.15
* Operating system: macOS Sierra 10.12.3

### Expected behavior

If `tray.setImage()` is updated while the tray is active, it should not display until the tray is inactive.

### Actual behavior

If `tray.setImage()` is updated while the tray is active, it will display and "overwrite" whatever has been pre-defined as `tray.setPressedImage()`.

### How to reproduce

Update `tray.setImage()` while the tray is currently "active".

**Comment by anthonybruno** [comment]
I believe that this issue might be related to #8831. I wasn't sure if they should be separated so I did just in case. Happy to roll into one. 😄

**Comment by zcbenz** [comment]
Closing for the same reason with https://github.com/electron/electron/issues/8831#issuecomment-308065373.
