### ISSUE TITLE
Always on top window should move as primary screen changes

### ISSUE THREAD

**Issue by pierretasci** [electron/electron#8835]
* Electron version: 1.4.15
* Operating system: macOS

### Expected behavior

When a browser window is set to be always on top ala

`new BrowserWindow({
   alwaysOnTop: true
});`

one would expect that when the user changes the primary display (ie they switched to a different desktop on macOS), it makes sense that the window should follow. This can either be implemented in electron itself or by adding an event to the screen class to notify when the primary screen changes. I believe the latter solution would easily allow developers to create their own desired response when the user switches displays/screens.

### Actual behavior

No movement of the primary browser window when the screen changes.

**Comment by zjxpcyc** [comment]
+1

**Comment by MarshallOfSound** [comment]
@zjxpcyc Please don't "+1" bump issues, it just adds to notification spam, you can use the 👍 reaction on the original comment to indicate the same thing

**Comment by krokofant** [comment]
Any workaround for this? I haven't found a good way to detect screen change and move the browser.

**Comment by zcbenz** [comment]
You pass a level to `win.setAlwaysOnTop` API to change how the window floats.

**Comment by robsontenorio** [comment]
@zcbenz and what should be that level? On OSX i have all levels , but the Electron App does not stay on top over other fullscreen apps

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetalwaysontopflag-level-relativelevel
