### ISSUE TITLE
Creating BrowerWindows with a parent always makes them show

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#8836]
* Electron version: 1.6.1
* Operating system: macOS Sierra

When you do this from a renderer process:

    new electron.remote.BrowserWindow(
        parent: parentBrowserWindow,
        show: false,
    );

The browser window always shows even though the `show` option is `false`. If you do not provide a parent, the browser window respects the `show` option.

**Comment by xaviergonz** [comment]
Just adding to this, it happened to me when modal was false under osx. Did not test windows

**Comment by ionphractal** [comment]
'ready-to-show' is also not triggered.
It works properly for me under Windows and Linux.

**Comment by xaviergonz** [comment]
@kevinsawicki just created a pull request to fix this issue
https://github.com/electron/electron/pull/9343

**Comment by xaviergonz** [comment]
PS: It also fixes a bug where if a child window is hidden and then re-shown it looses its child window status.
