### ISSUE TITLE
Failure in GitHub's OAuth web application flow

### ISSUE THREAD

**Issue by hackjutsu** [electron/electron#8838]
Recently, we receive an [issue report](https://github.com/hackjutsu/Lepton/issues/120) about users failing to authorize our app through the GitHub OAuth flow. After initial investigation, we notice different behavior between a browser(like Chrome) and the electron windows.

For example, when loading the link ([according to GitHub v3 API](https://developer.github.com/v3/oauth/#web-application-flow)) below in a browser, users get an Authorize button enabled. However, the button is disabled in an Electron windows.

```
https://github.com/login/oauth/authorize?client_id=[my_client_id]&scope=gist
```

![image](https://cloud.githubusercontent.com/assets/7756581/23585312/43d42af8-0130-11e7-8045-a2d269b70148.png)

I'm not sure whether this issue is on GitHub API side or Electron side.

* Electron version: v1.6.1
* Operating system: macOS 10.11.6 (15G1108)

### Expected behavior
Users are navigated to a webpage with an **enabled** Authorize button.

### Actual behavior

Users are navigated to a webpage with a **disabled** Authorize button.

### How to reproduce

This issue can be simply reproduced in [electron-quick-start](https://github.com/electron/electron-quick-start). Just update 

```javascript
mainWindow.loadURL(url.format({
   pathname: path.join(__dirname, 'index.html'),
   protocol: 'file:',
   slashes: true
}))
```
with
```javascript
mainWindow.loadURL('https://github.com/login/oauth/authorize?client_id=[my_client_id]&scope=gist')
```
in `main.js`. Please [register your application](https://github.com/settings/applications/new), and replace `[my_client_id]` with your real client id in the url above.

Thanks,

--Cosmo

**Comment by MarshallOfSound** [comment]
@hackjutsu Normally this kind of thing is due to the website seeing the global `node.js` features, ensure that `nodeIntegration` is disabled on your browserwindow 👍

**Comment by hackjutsu** [comment]
@MarshallOfSound Thanks. Does it imply there is a recent change on the server? This issue just happens recently.

**Comment by MarshallOfSound** [comment]
@hackjutsu Probably yes 👍
