### ISSUE TITLE
Webview - allow to load local resources when using data URLs

### ISSUE THREAD

**Issue by bpasero** [electron/electron#884]
- using Atom shell 0.19.5 with the webview tag
- set the src attribute of the webview to a data URL that has a reference to a local resource (e.g. image tag)
- open the app and listen to the console-message event on the webview
  => Not allowed to load local resource: file:///C:/<path>/1.jpg

It would be nice if for a webview you could bypass this security measure when you set a data URL. 

My app html:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>  
  <body>
    <h1>Hello World!</h1>
    We are using node.js <script>document.write(process.version)</script>
    and atom-shell <script>document.write(process.versions['atom-shell'])</script>.

    <webview id="foo" src="data:text/html;base64,<BASE 64 encoded>" style="width:640px; height:480px"></webview>

    <script type="text/javascript">
        document.getElementById("foo").addEventListener("console-message", function(e) {
            console.log(e.message);
        });
    </script>
  </body>
</html>
```

The base 64 encoded value is something like:

```
<img src="file:///path to app/1.jpg" />
```

**Comment by emptist** [comment]
Is there any tutorial on loading local html? I tried several times but all failed.

**Comment by Obooman** [comment]
Following code works for me.
```js
...
import demo from './demo.html'

class WVCheck extends React.Component{
  render(){
    return (
      <View style={{ height:700 }}>
        <WebView
	  source = { webapp }
	  style={{borderColor:'green',borderWidth:400,width:300,height:1200}}/>
      </View>
    )
  }
}
```

Which is interesting,the `WebView` component will not fill it's parent `View` element,it means that you have to offer height to parent `View` element
