### ISSUE TITLE
`will-navigate` event not fired when in sandbox mode

### ISSUE THREAD

**Issue by sebastianseilund** [electron/electron#8841]
Thanks for Electron! Amazing project :)

* Electron version: 1.6.2
* Operating system: macOS Sierra (10.12.3)

It happens when `BrowserWindow` is opened with `sandbox: true`. It might be on purpose, but I couldn't find any Electron/Chromium documentation that explains why. So I'm suspecting it's a bug. I can submit a PR with a failing test to this repo if you agree that it's a bug.

### Expected behavior

`webContents`' `will-navigate` event should fire when user reloads page fx.

### Actual behavior

It does not fire.

### How to reproduce

package.json:

```json
{
  "name": "electron-sandbox-will-navigate-bug",
  "version": "0.0.0",
  "main": "main.js",
  "dependencies": {
    "electron": "^1.6.2"
  }
}
```

main.js:

```js
const {app, BrowserWindow} = require('electron')
const path = require('path')

app.on('ready', function() {
  const win = new BrowserWindow({
    webPreferences: {
      sandbox: true
    }
  })

  const {webContents} = win
  webContents.on('will-navigate', () => {
    console.log('will-navigate')
  })
  webContents.on('did-navigate', () => {
    console.log('did-navigate')
  })

  win.loadURL('file://' + path.join(__dirname, 'index.html'))
})
```

index.html:

```html
<!doctype html>
<html>
  <body>
    <button onclick="window.location.reload()">Reload</button>
  </body>
</html>
```

Perform these steps:

- Run `npm install`
- Run `./node_modules/.bin/electron .`
- Click the Reload button in the browser window
- Observe the Terminal output

Expected output:

```
did-navigate
will-navigate
did-navigate
```

Actual output:

```
did-navigate
did-navigate
```

(will-navigate is not fired).

If you outcomment the line `sandbox:true` in `main.js`, then it works as expected.

**Comment by lachenmayer** [comment]
Hi there, I'm experiencing a similar issue: when the user presses `cmd-R` to reload, I expect the `will-navigate` event to fire. It currently does not.

This happens even when the `sandbox: true` flag is removed in the repro case above.

I'm currently working around this by adding a `beforeunload` listener to the main window, as such:

```js
window.addEventListener('beforeunload', e => {
  e.returnValue = false
})
```

**Comment by jviotti** [comment]
This happens in OS X only for me, without sandbox.

**Comment by lurch** [comment]
https://github.com/resin-io/etcher/pull/1219/files implements a workaround for this.

**Comment by sebastianseilund** [comment]
> https://github.com/resin-io/etcher/pull/1219/files implements a workaround for this.

Thanks for your input. I just want to point out that this is not a workaround for this specific issue. The issue here is that `will-navigate` is not fired. Not that I want to block the user from navigating.

**Comment by lurch** [comment]
Lol, whoops ;-)  My apologies for misunderstanding.

**Comment by lneir** [comment]
what is the status on a fix here?

**Comment by jamjury** [comment]
Actually `will-navigate` isn't working under linux (ubuntu 16.04) too

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by codebytere** [comment]
Great! will do, thanks for the fast response

**Comment by geakstr** [comment]
Still exists in 4.* Is there any workaround to make it works?

**Comment by geakstr** [comment]
As well as in v5 beta

**Comment by markleutloff** [comment]
I can reproduce this too, will-navigate is never fired, which makes aborting navigations for security reasons a hassle. Also nothing in the docs state that sandboxing will prevent the firing of this event.

**Comment by mike-seekwell** [comment]
you can "fix" this by doing the following:

    electron.globalShortcut.register('CommandOrControl+R', () => {
        console.log('CommandOrControl+R is pressed')
    })

but note that it disables CMD+R across all applications the user has open (e.g. they won't be able to reload a page in Chrome using CMD+R)

**Comment by mattbroussard** [comment]
We still observe this on 5.0.5. Any updates?

The workaround of disabling the cmd-R shortcut is not applicable for us, as we are trying to prevent link navigations for security purposes.

**Comment by markleutloff** [comment]
This is still a problem at:

- Electron v6.0.0
- Electron v6.0.1
- Electron v7.0.0-beta.1

Any news on this?

**Comment by ridesky** [comment]
same  +1

**Comment by codebytere** [comment]
No news, but i did some brief digging and it seems the sandbox codepath never invokes `OpenURLForTab` which is what causes this. Still working on the why and the fix.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by asherkin** [comment]
There are 6+ months of comments confirming it is still present in versions post-4.2, please do not close this issue again.

**Comment by aegarbutt** [comment]
I did some more in-depth digging to understand when OpenURLFromTab was called. It appears it was only called when a new process was created. I've created a pull request that fixes the tactical issue.

**Comment by aegarbutt** [comment]
Perhaps this should rely on `ShouldTransferNavigation` instead?

**Comment by b8kkyn** [comment]
Any updates on this?

**Comment by pushkin-** [comment]
FWIW, couldn't repro on Windows 10 with Electron 5.0.7

**Comment by phosphore** [comment]
The issue is reproducible in every Electron version since the introduction of the sandbox flag (in [v1.4.2](https://github.com/electron/electron/compare/v1.4.1...v1.4.2)) up to the latest stable Electron release (v8.0).

Because of this, every implementation relying on `will-navigate` to abort navigation for security reasons will stop working once `sandbox` will be enabled.  Because this behavior is dangerous and undocumented, __it should be treated as a security issue__. 

As a possible workaround in case of sandboxed apps, the `webRequest.onBeforeRequest` or `webRequest.onBeforeSendHeaders` together with `webRequest.onBeforeRedirect` functions can be used in the `app.on('ready')` handler to intercept the navigation events:
```
  const ses = session.defaultSession
  const domainToAllow = 'https://www.doyensec.com/‘

  ses.webRequest.onBeforeRequest((details, callback) => {
    if (!details.url.startsWith(domainToAllow)) {
      console.log(`blocked the request to ${details.url}`)
      callback({ cancel: true })
    } else { 
      console.log(`allowed the request to ${details.url}`)
      callback({})
    }
  })
```

It would also be possible to use `webRequest.onHeadersReceived` and `webRequest.onResponseStarted` events to prevent external content from being rendered, but that approach would nonetheless perform the request, which is undesirable. See https://www.electronjs.org/docs/api/web-request for more.
