### ISSUE TITLE
Can't disable MenuItem with a role

### ISSUE THREAD

**Issue by jbleuzen** [electron/electron#8843]
* Electron version: 1.4.15
* Operating system: OSX 10.12.2

### Expected behavior

MenuItem with role should be disabled when a set a menuItem with `enabled:false`

### Actual behavior

MenuItem with role are not disabled whereas a MenuItem without role is correctly disabled

### How to reproduce

I made a small repo that shows the bug : https://github.com/jbleuzen/electron-menu

If you have any questions... :)

**Comment by kevinsawicki** [comment]
I believe this is a duplicate of #5794, please see that issue for more details about this, closing this out.

**Comment by jbleuzen** [comment]
Sorry didn't find it while I was searching, it is a duplicate :(
