### ISSUE TITLE
Event objects are reused across listeners

### ISSUE THREAD

**Issue by dfederm** [electron/electron#8844]
* Electron version: 1.4.1
* Operating system: Windows 10

### Expected behavior
Multiple listeners to an event get a separate copy of the event object.

### Actual behavior
Multiple listeners to an event get the same event object, allowing one to affect the other by altering the object.

### How to reproduce
Minimal repro here: https://github.com/dfederm/electron-quick-start/tree/bug-8844

Basically:
1. Add 2 event listeners to the "message" event.
2. Each listener just reads event.data.args and alters it, in this example, event.data.args.unshift(5). Each also prints what it saw before and after the change.
3. Raise a message event via window.postMessage({ args: [1, 2, 3]}, "*");
4. I'd expect both listeners to see { args: [1, 2, 3]} before and change it to { args: [5, 1, 2, 3]}, however the 2nd sees { args: [5, 1, 2, 3]} from the first one and changes it to { args: [5, 5, 1, 2, 3]}.

![image](https://cloud.githubusercontent.com/assets/6445614/23621519/e9d4a142-024f-11e7-90dc-8bba05680d7c.png)

**Comment by tonyganch** [comment]
That is standard browser behaviour, you can reproduce that in Chromium, Safari and Firefox. Events are passed as references to the object, not copies.
I believe it will be unexpected from Electron to implement that in different way.

**Comment by kevinsawicki** [comment]
Agree with @tonyganch and @MarshallOfSound, the behavior for this event is defined by Chrome and is probably based on a DOM spec somewhere, this isn't something handled by Electron.

This could be raised to the Chrome issue tracker if you want to pursue it further.

Closing this out.
