### ISSUE TITLE
Electron apps can't find libcurl.so.4

### ISSUE THREAD

**Issue by loveencounterflow** [electron/electron#8853]
I'm looking for a nice Git GUI, and so I came across [gitkraken](https://www.gitkraken.com/download/linux-deb) the other day. However, it wouldn't start but fail with

```sh
/usr/lib ► gitkraken
Node started time: 1488472940858
libcurl.so.4: cannot open shared object file: No such file or directory
Error: libcurl.so.4: cannot open shared object file: No such file or directory
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/gitkraken/resources/app.asar/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:541:32)
    ...
```

I tried to fix the issue with

```sh
sudo ln -sf /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.4.0 libcurl.so.4
```

and, as recommended by nodegit:

```sh
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install libstdc++-4.9-dev
```

but to no avail. Naturally I would have thought this to be a problem with the gitkraken app, but today I chose to try and run [Cycligent Git Tool](https://www.cycligent.com/git-tool), and look what happened:

```sh
► /usr/share/CycligentGitTool/CycligentGitTool
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libcurl.so.4: cannot open shared object file: No such file or directory
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/CycligentGitTool/resources/app/cygit/server/node_modules/nodegit-electron-linux-x64/dist/nodegit.js:11:12)
```

so it would appear Electron has a problem here. The strange thing is that I *can* start Atom, and I never had a problem like that with it (well, maybe it doesn't even need libcurl, of course).

This is on Linux Mint Cinnamon:

```sh
► uname -a && cat /etc/issue
Linux enceladus 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint 18 Sarah
```

**Comment by MarshallOfSound** [comment]
If Atom launches on your machine then I doubt this is an Electron issue rather an issue with these apps not declaring their dependencies correctly.

Can you try installing raw Electron from the releases section on GitHub and see if you can launch that 👍

**Comment by loveencounterflow** [comment]
Right now my best guess is with nodegit; let's up folks over there have a clue what's going on.

**Comment by robersongomes** [comment]
@loveencounterflow
I had the same issue on Linux Mint 18 Cinnamon,
`sudo apt-get install curl libcurl3` solved the problem for me.

**Comment by Fabucci** [comment]
@robersongomes 
This worked for me.  Many thanks!!!!

**Comment by loveencounterflow** [comment]
@robersongomes YES!

I dare hereby re-open the commit to encourage adding this—`sudo apt-get install curl libcurl3`—to be added to the installation instructions where seen fit.

**Comment by matiasvarela** [comment]
@robersongomes worked for me too.! thanks

**Comment by KurtJacobson** [comment]
Yep, same issue here. Also solved by: `sudo apt-get install curl libcurl3`

**Comment by mdilg** [comment]
Same to me, solved by: `sudo apt-get install curl libcurl3`

**Comment by rabin-io** [comment]
Thanks to this issue and the comments I was able to solve my problem as well, 
I'm using gitkraken as well but run it on Fedora which the libcurl naming is a bit different.
so I created a new symlink named `libcurl-gnutls.so.4` which solved my problem.

    [/usr/lib64] # ln -s libcurl.so.4.4.0 libcurl-gnutls.so.4

**Comment by joebitcoinorg** [comment]
Thanks!  This worked for me.  I was trying to run Agama Desktop Wallet for the KomodoPlatform and when it tried to spawn komododI was seeing errors about libcurl.so.4 being missing.   This was on Ubuntu 16.04 running as a Linux Container atop a Proxmox server running Debian Stretch.  

Inside the container I ran:
sudo apt-get install curl libcurl3

Which fixed the problem.  Thanks!

**Comment by lalaithan** [comment]
I'm having a similar issue on OpenSUSE Leap 42.3 with the following:

```
7oe3:~> sudo apt-get install curl libcurl3
[sudo] password for root: 

Loading repository data...
Reading installed packages...
'curl' is already installed.
No update candidate for 'curl-7.37.0-30.1.x86_64'. The highest available version is already installed.
'libcurl3' not found in package names. Trying capabilities.
No provider of 'libcurl3' found.
Resolving package dependencies...

Nothing to do.
```

**Comment by 4ndrej** [comment]
@akontsevich this works on fedora too

**Comment by benwinding** [comment]
I'm running into this problem on **Ubuntu 18.04**, 

To solve this, I just uninstalled and used the Gitkraken _Snap_ from the Ubuntu Software Store.

**Comment by hyamanieu** [comment]
Since **Ubuntu 18.04**, installing curl & libcurl3 wont' work as curl requires libcurl4 (and that doesn't help with starting GitKraken). I didn't dig into the error as, as said by @benwinding , the snap works. Don't forget to give the right permissions in the Software Store if you keep your repos outside your home.

**Comment by jekeam** [comment]
> @loveencounterflow
> I had the same issue on Linux Mint 18 Cinnamon,
> `sudo apt-get install curl libcurl3` solved the problem for me.
> 
> Credit: http://askubuntu.com/a/893117

Reading package lists ... Done
Building a dependency tree
Read status information ... Done
Some packages cannot be installed. Perhaps what you are asking is
impracticable, or you are using an unstable version of the distribution, where
The packages you requested have not yet been created or have been removed from Incoming.
The following information may help you:

The following packages have unsatisfied dependencies:
  curl: Depends: libcurl4 (= 7.58.0-2ubuntu3.8) but it will not be installed
E: Unable to fix errors: you have broken packages.

**Comment by jekeam** [comment]
> > @loveencounterflow
> > I had the same issue on Linux Mint 18 Cinnamon,
> > `sudo apt-get install curl libcurl3` solved the problem for me.
> > Credit: http://askubuntu.com/a/893117
> 
> Reading package lists ... Done
> Building a dependency tree
> Read status information ... Done
> Some packages cannot be installed. Perhaps what you are asking is
> impracticable, or you are using an unstable version of the distribution, where
> The packages you requested have not yet been created or have been removed from Incoming.
> The following information may help you:
> 
> The following packages have unsatisfied dependencies:
>   curl: Depends: libcurl4 (= 7.58.0-2ubuntu3.8) but it will not be installed
> E: Unable to fix errors: you have broken packages.

it helped: https://askubuntu.com/questions/1014645/unmet-dependencies-when-trying-to-install-curl-on-ubuntu-16-04

`sudo apt install curl`
