### ISSUE TITLE
the typing indicator disappear when I zooming out with multi cursor option.

### ISSUE THREAD

**Issue by pixieaka** [electron/electron#8855]
https://github.com/Microsoft/vscode/issues/21974

![capture1](https://cloud.githubusercontent.com/assets/17777237/23664286/d65c9a3e-035d-11e7-9f51-8307eac9aba4.JPG)

**Comment by zcbenz** [comment]
This is a bug of Chromium's rendering, I suggest waiting for Chrome upgrade in VS Code to fix this.
