### ISSUE TITLE
New webview resets the zoom on existing webviews

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#8857]
* Electron version: 1.6.1
* Operating system: MacOS 10.12

Create a webview, set the zoom level, then create a second webview for content at the same domain as the 1st webview.

### Expected behavior

Ideally the second webview would assume the same zoom as the existing webview. At minumum, it'd be good if the first webview maintained its current zoom.

### Actual behavior

The zoom level is reset on both webviews.

### How to reproduce

https://github.com/pfrazee/electron-bug-webview-zoom Instructions on the readme

**Comment by pfrazee** [comment]
If yall can give me some direction on the correct behavior or what's malfunctioning, I can put together a PR

**Comment by deepak1556** [comment]
https://github.com/electron/electron/pull/8864 should fix this, the issue was webview inherits the parent zoom level by default. When the second webview was created it propagated the default zoom level to all webviews in the same partition instead of using its origin zoom level.

**Comment by pfrazee** [comment]
Oh awesome, really appreciate the fix
