### ISSUE TITLE
App icon on Ubuntu Unity

### ISSUE THREAD

**Issue by RedHatter** [electron/electron#8859]
* Electron version: 1.6.1
* Operating system: Ubuntu 16.04

### Expected behavior

A window with an red square as an icon should open.

### Actual behavior

A window opens with an undefined icon.
![screenshot from 2017-03-07 17-20-47](https://cloud.githubusercontent.com/assets/1530025/23686137/a9e95010-035c-11e7-95ae-bdaefd739571.png)

### How to reproduce

I have create a minimal electron example. Run the following commands on Ubuntu with the Unity desktop.

    git clone https://github.com/RedHatter/electron-quick-start.git
    npm i
    npm start

The icon is 128x128 and is named exactly `icon.png`, according to my research that is what should be needed to get an electron icon to display on Unity.

**Comment by pronebird** [comment]
Same issue. Even feeding window with an instance of nativeImage does not help.

**Comment by zeke** [comment]
Are you experiencing this issue on older versions of Electron?

**Comment by RedHatter** [comment]
I have tested my example with electron versions 1.6.1, 1.5.1, 1.4.1, and 1.3.1. Each version showed the same results.

**Comment by bil-elmoussaoui** [comment]
It seems that nativeImage.createFromPath always return an empty object :( the same things happens with tray icons too

**Comment by zcbenz** [comment]
You need to provide a `.desktop` file to your app:
https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles
