### ISSUE TITLE
Print to PDF with Xvfb randomly generates a corrupted PDF file

### ISSUE THREAD

**Issue by tinogo** [electron/electron#8860]
* Electron version: 1.6.1
* Operating system: node:7-slim Docker-Container (Debian Jessie)

### Expected behavior
When printing to PDF via `webContents.printToPDF()`, the generated should always be okay and not corrupt.

### Actual behavior
When printing to PDF via `webContents.printToPDF()`, the generated PDF file is "sometimes" corrupt.
In this case, the generated file is empty and the console prints the following line:
`../../third_party/tcmalloc/chromium/src/free_list.h:118] Memory corruption detected.`

### How to reproduce
1. Install Xvfb via apt-get into the node:7-slim docker-container
2. When starting the electron app, start Xvfb like following: `Xvfb :9.0 -screen 0 1280x1024x24 &`
3. Try to print a webpage as PDF

An example project, which has this problem can be found here:
https://github.com/tinogo/electron-pdfer

**Comment by zeke** [comment]
@tinogo are you able to reproduce this issue on older versions of Electron?

**Comment by tinogo** [comment]
Hi,
yes, I've even experienced it with Electron 1.4.*.

**Comment by zcbenz** [comment]
While we would like to fix this, I'm afraid without a reproducible case we are unable to fix it, and we also don't have enough resources to debug it. So I have to close this as won't fix.
