### ISSUE TITLE
Documentation: "maximize" implies "show", ready-to-show only on hidden window

### ISSUE THREAD

**Issue by TanninOne** [electron/electron#8861]
* Electron version: 1.4.14
* Operating system: Windows

This isn't much of a bug report but I think the documentation could be a bit clearer on a few things:

- When you call the "maximize" function on a BrowserWindow that was created with "show: false" it shows the window
- The "ready-to-show" event is only invoked if the BrowserWindow is not shown yet (so it was started with show: false and no "show" or "maximize" were called on it before). The documentation just says

> While loading the page, the ready-to-show event will be emitted when renderer process has done drawing for the first time

**Comment by zeke** [comment]
Good catch, @TanninOne. Would be willing to open a PR that updates these docs?

**Comment by dannyharding10** [comment]
For anyone with the same problem as me, something similar happens when calling `browserWindow.hide`. The issue is documented here #24855
