### ISSUE TITLE
(MacOS) Cannot listen click event when hide Menu

### ISSUE THREAD

**Issue by Riokai** [electron/electron#8865]
* Electron version:v1.4.13 ~ 1.6.1
* Operating system: MacOS

### Expected behavior

Menu hide and receive click event

### Actual behavior

Menu hide and not click event

### How to reproduce

![2017-03-08 22 38 13](https://cloud.githubusercontent.com/assets/7970372/23708444/e09c244e-0450-11e7-96e9-01c5392146d8.gif)
![Uploading 2017-03-08 22.38.13.gif…]()

![2017-03-08 22 47 28](https://cloud.githubusercontent.com/assets/7970372/23708573/52f496c0-0451-11e7-990d-2a8336e1254b.gif)

**Comment by zeke** [comment]
I didn't know about the [`monitorEvents`](https://developers.google.com/web/tools/chrome-devtools/console/events) method. That's pretty handy.

Do you see the events when you use `document.body` instead of [`$0`](https://developers.google.com/web/tools/chrome-devtools/console/command-line-reference#0_-_4)?

```js
monitorEvents(document.body, 'click')
```

**Comment by Riokai** [comment]
@zeke The situation is the same

![2017-03-09 08 55 40](https://cloud.githubusercontent.com/assets/7970372/23731080/4f4d2e24-04a6-11e7-9caa-b72cafab26e2.gif)

**Comment by Riokai** [comment]
BTW, Windows side is find.

**Comment by MarshallOfSound** [comment]
This appears to only be a bug on macOS.  After playing around in Chrome in this scenario it looks like the click event is delayed until the menu is gone and `mousedown` and `mouseup` events never get fired in this scenario.

Chrome probably has some haxy workaround for this but I couldn't find it in code 👍

**Comment by zcbenz** [comment]
This is a behavior of macOS, the click event that cancels the menu is not passed to the application. You can probably try using the `acceptFirstMouse` option to override it.

Closing as won't fix since it is a behavior of macOS.
