### ISSUE TITLE
Impossible to control redirections in net.request

### ISSUE THREAD

**Issue by arantes555** [electron/electron#8868]
* Electron version: 1.6.1
* Operating system: All

### Expected behavior

It should be possible, when using net.request, to set redirection options. The `ClientRequest` constructor options should contain a "redirect" attribute, with possible values "follow", "error" or "manual" (like window.fetch), and defaulting to "follow".

Also, when a redirection did happen, it should be possible to know it did, and at least get the URL to which we were redirect (for example as an attribute of IncomingMessage).

### Actual behavior

It is not possible to stop redirections from happening, or even to know that it happened and get the new URL.

### How to reproduce

Use net.request on any URL that does a redirect.

**Comment by AlienHoboken** [comment]
To note, it is possible to know if a net.request redirection happens. Use session and webRequest hooks. To get information on request and interact with it.

Take the following to perform some behavior on redirect.

```javascript
const {net, session} = require('electron')

var netRequest = (url, onRedirect) => {
    let sess = session.fromPartition(Date.now().toString())

    sess.webRequest.onBeforeRedirect((details) => {
        onRedirect(details)
    })

    let options = { url: url, session: sess }

    net.request(options).end()
}

netRequest("http://google.com", details => console.log('1: ' + details.url) )
```

You can also use other hooks and additional logic to perform other tasks.

That being said, it'd be great to have first class support for this in `ClientRequest`
