### ISSUE TITLE
Unable to update touch bar play/pause

### ISSUE THREAD

**Issue by kinglime** [electron/electron#8872]
* Electron version: 1.6.3
* Operating system: macOS Sierra 10.12.3

### Expected behavior

When creating a media application with electron the global touch bar play/pause button should update.

### Actual behavior

The button displays the play icon regardless as to whether or not media is playing

**Comment by kinglime** [comment]
It seems like there is some kind of global variable in macOS to indicate if media is playing or paused. Perhaps electron could toggle this as part of the touch bar API?

**Comment by MarshallOfSound** [comment]
@kinglime See #8280

This state is controlled through the `MPRemoteCommandCenter` library.  I'll probably send up implementing this feature in a native addon but for now it won't be going into Electron.

**Comment by kinglime** [comment]
@MarshallOfSound any chance you could help me with my swift file, it doesn't seem to work.

```swift
import MediaPlayer

#if available
  var media: MPRemoteCommandCenter = shared() -> MPRemoteCommandCenter.togglePlayPauseCommand()
#endif
```
