### ISSUE TITLE
Electron JS With Python 3.6 print error on npm start, downgrade python version ?

### ISSUE THREAD

**Issue by codenoid** [electron/electron#8873]
this is my first electron js installation, and I had to download and install its electron, NPM install (in the folder electron), but when at the start, failed. error on print, or if I had to do python downgrade?
screenshot https://i.stack.imgur.com/0pxKY.png  
[https://www.fyears.org/2017/02/electron-as-gui-of-python-apps-updated.html](something in internet)

**Comment by enlight** [comment]
As per https://electron.atom.io/docs/development/build-instructions-windows/ you need Python 2.7 to build Electron from source.
