### ISSUE TITLE
How can i remove buttons from frame!!!!

### ISSUE THREAD

**Issue by AvijitDutta95** [electron/electron#8874]
How can i remove only maximize and minimize button from frame???

**Comment by j-f1** [comment]
This isn’t really possible. You can either:

1. Disable those buttons (doesn’t work on Linux):
    ```js
    const bw = new BrowserWindow({
      // ...
      minimizable: false,
      maximizable: false
    })
    ```
2. Or hide all of the buttons and create your own close button.

**Comment by kevinsawicki** [comment]
@AvijitDutta95 you can use the `frame: false` option to remove all the frame's controls.

https://electron.atom.io/docs/api/frameless-window/

**Comment by vasanthdeveloper** [comment]
> @AvijitDutta95 you can use the `frame: false` option to remove all the frame's controls.
> 
> https://electron.atom.io/docs/api/frameless-window/

But that doesn't solve the problem!

**Comment by keytrap-x86** [comment]
Writing this for anytone struggling removing the close button.
I had `frame: false`, `transparent: true`, `titleBarStyle: 'hidden'`.

✅ What solved it for me was to set `titleBarStyle: 'hiddenInset'`, and ONLY then the close button dissapeared.

![image](https://github.com/user-attachments/assets/ec6b2581-2d1b-49c0-8e8c-40d2a32dd3a9)
