### ISSUE TITLE
dialog.showOpenDialog([browserWindow, ]options[, callback])

### ISSUE THREAD

**Issue by ishwarrimal** [electron/electron#8875]
* Electron version: 1.4.8
* Operating system: windows 7 32 bit

### Expected behavior

Is there any way of restricting the size of file being uploaded with dialog.showOpenDialog([browserWindow, ]options[, callback])?
I am aware of filters for selecting certain file type, but if there was a way in which we could restrict the file size it would be great.

**Comment by kevinsawicki** [comment]
> I am aware of filters for selecting certain file type, but if there was a way in which we could restrict the file size it would be great.

This would require support from the native Windows file dialog APIs, I'm not seeing anything in https://msdn.microsoft.com/en-us/library/windows/desktop/dn457282(v=vs.85).aspx that handles that.

So I don't think this will be possible, you'll just have to handle this in your application and notify the user when they select something too large and re-prompt.

Have you seen this behavior in other apps that open the Windows file dialog?

**Comment by kevinsawicki** [comment]
Closing this out since it doesn't look like their are native APIs to handle this on Windows.
