### ISSUE TITLE
BrowserWindow.unmaximize on hidden window breaks it

### ISSUE THREAD

**Issue by TanninOne** [electron/electron#8879]
* Electron version: 1.4.14
* Operating system: Windows

### Expected behavior

calling unmaximize on a hidden BrowserWindow (started with { show: false }) should either show it then unmaximize it or do nothing.

### Actual behavior

the windows shows up completely black and unresponsive. It doesn't recover from this.

### How to reproduce

create a BrowserWindow with show: false and immediately after creating the window call .unmaximize on it.

**Comment by zcbenz** [comment]
`unmaximize` actually means putting the window into restored state, the behavior is undefined if you call it on a non-maximized window. I suggest checking window's state before calling it in your app.

Closing this as won't fix since it is an undefined behavior.

**Comment by TanninOne** [comment]
I'm confused. Why would you leave this behaviour undefined? A good api is easy to use right and hard to use wrong - requiring the user to do checks before calling certain functions seems unnecessary. If you know that unmaximize is pointless on a non-maximized window, why not do the check inside electron?
