### ISSUE TITLE
Move to io.js

### ISSUE THREAD

**Issue by ghost** [electron/electron#888]
Do you plan to move to io.js instead of node.js?

**Comment by geddski** [comment]
@thedaniel might be worthwhile to try a prototype and measure to see if performance is significantly better or not.

**Comment by chicoxyzzy** [comment]
performance should be better cause of bunch of v8 improvements. also io.js brings some es6 features by default

**Comment by paulcbetts** [comment]
I'm not sure the V8 stuff applies, Atom's node.js always links to Chrome's version of V8, so we've always been running a frankenstein version of node.js. Also, raw CPU performance in a Desktop GUI app isn't really that useful (Chrome layout and rendering perf are **way** more interesting to me). 

The more interesting aspect of io.js is the improved API surface, but I'm not sure that we really need that either. The best decision atm is "the one that works with the most amount of 3rd party modules".

**Comment by mzgol** [comment]
> I'm not sure the V8 stuff applies, Atom's node.js always links to Chrome's version of V8, so we've always been running a frankenstein version of node.js.

Switching to io.js would remove the need for that as the project is going to closely follow latest stable v8 versions.
