### ISSUE TITLE
MenuItem label doesn't accept '&' but submenu label does.

### ISSUE THREAD

**Issue by austinwegner** [electron/electron#8881]
* Electron version: 1.4.3
* Operating system: Win 10 64bit

### Expected behavior

```
    menu.append(new MenuItem({
      label: 'S && R Book',
      click() {
        win.webContents.send('menu-sr')
      }
    }))
```

Should display 'S & R Book' in the menu bar.

### Actual behavior

'S R Book' displays

### Working in submenu

```
  menu.append(new MenuItem({
        label: 'Modules',
        submenu: [{
            label: 'Applicant Board',
            click() {
                win.webContents.send('menu-pb')
            }
        }, {
            label: 'S && R Book',
            click() {
                win.webContents.send('menu-sr')
            }
        }, {
            type: 'separator'
        }, {
            label: 'Exit',
            click() {
                console.log('Exit App')
                app.quit()
            }
        }]
    }))
```

This correctly displays 'S & R Book' in the submenu item.

I've tried `\&`, `&amp;`, `&#38;` and none of these work either. Whatever I seem to do, it parses the & out of the label.

**Comment by liusy182** [comment]
maybe the second `&` should not be removed. Relevant code [here](https://github.com/electron/electron/blob/master/atom/browser/ui/views/submenu_button.cc#L24)

**Comment by austinwegner** [comment]
Adding in rhe second & to any of those snippets does not work either.
