### ISSUE TITLE
Support "customizable" touchbar items

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#8888]
I have a few ideas regarding this and I'll see which of them work when I get time but the general idea at the moment is to require a user-set "id" property if you want a TouchBarItem to be customizable.

I.e.

```js
new TouchBarButton({
  customizable: true,
  id: 1,
  label: 'FooBar'
})
```

This will allow our existing logic to render the items when requested as long as the user (app) doesn't change the ID and provides that object all the time.

We will also need to add a method like `touchBar.addNonDefaultItems(items[])` to add items that can be added to the touchbar by consumers but aren't on the default touch bar the app chooses.

Not sure how feasible any of this actually is but will look into all of it 👍

**Comment by ckerr** [comment]
Next week this issue will be five years old :cake: 

@MarshallOfSound should this issue be closed, or is it still something on the long-term TODO list?

**Comment by MarshallOfSound** [comment]
Touchbar is going to be a thing of the past, the technical investment to support this is not worth it anymore IMO
