### ISSUE TITLE
[Question] MacOS: impossible to put window of top of other application in fullscreen 

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#8889]
I'd like to put my app window on top of any other open applications, even in full screen. In Apple documentation there is topic about [OS Window Layers](https://developer.apple.com/reference/appkit/nswindow/window_levels). And Electron API provide [setAlwaysOnTop](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetalwaysontopflag-level-relativelevel) method to apply this setting.

But currently no one is make possible to do so. Just a question is it some issue in API, or it impossible due to Layers are relate to one application and can't interact with other applications?

**Comment by zcbenz** [comment]
This is a limitation of macOS, I don't think there is a way to work around it.
