### ISSUE TITLE
IPC message from main process wont reach the render process when html page changes/reloaded in the render process.

### ISSUE THREAD

**Issue by ShadananaK** [electron/electron#8892]
* Electron version: 1.4.15
* Operating system: windows 8

### Expected behavior
IPC should work even when html page in render process changes/reloaded.

### Actual behavior
IPC i.e message from main process wont reach when html page in render process changes / reloaded. 

### How to reproduce
i am Opening pop-up window from main.js by sending ipc message from render process to main process. After pop-up is opened successfully, i will change /reload the html page present in render process. After some time if i close pop-up window and for that event in main.js i will send message to render process using **`mainWindow.webContents.send('pop-window-closed');`** which wont reach the render process.

Please help.

**Comment by ButzYung** [comment]
Whenever your page on render process reloads/changes, you have to register the IPC event listeners again on the page (require('electron').ipcRenderer) in order to receive message from the main process.

**Comment by ShadananaK** [comment]
@ButzYung  Thank you. But **const {ipcRenderer} = require('electron')** - this line is in the on-ready event of page only.

**Comment by MarshallOfSound** [comment]
@ShadananaK Can you provide a minimal reproduction example, it sounds like you aren't adding the IPC listener again on page load 👍

**Comment by ShadananaK** [comment]
@MarshallOfSound  your absolutely correct sir. Now its working fine.You saved my day. Thanks a lot.  :+1: :+1:

**Comment by ShadananaK** [comment]
This isn't  real issue.I'll close it in moment.
