### ISSUE TITLE
中文输入法「候选词面板」位置异常

### ISSUE THREAD

**Issue by Houfeng** [electron/electron#8894]
### 系统及 Electron 的版本信息:
Electron version: v1.6.1
Operating system: os x 10.12.2

### 问题现象
中文输入法（百度五笔），在输入中文时，时常会出来「输入法候选词面板」位置异常，会出现在整个窗口的「左上角」

### 问题截图
![image](https://cloud.githubusercontent.com/assets/1432335/23797890/025e0434-05dd-11e7-8d52-2051ea899062.png)

**Comment by Houfeng** [comment]
@zcbenz

**Comment by hokein** [comment]
Duplicate of #4539.
