### ISSUE TITLE
shell.openExternal not working when url contains double dots (..) 

### ISSUE THREAD

**Issue by jmaglasang** [electron/electron#8896]
* Electron version: v1.6.2
* Operating system: windows 10 64bit

### How to reproduce

let privacyLink = document.getElementById("privacyLink")
privacyLink.addEventListener("click", function(e){
    let url = "file:///" + __dirname + "/../assets/privacy-policy.pdf"
    url = url.replace(/\\/gi, '/')
    console.log(url)
    electron.shell.openExternal(url)
    //e.preventDefault()
})

**Comment by MarshallOfSound** [comment]
@jmaglasang This is expected behavior, the OS / application can't resolve that path you should resolve it for them.

Use `path.resolve(myPathString)` to collapses / resolve those `..` path segments 👍
