### ISSUE TITLE
Text completion support in macOS

### ISSUE THREAD

**Issue by davidhariri** [electron/electron#8902]
* Electron version:
_all_
* Operating system:
_macOS 10.12.3_ I expect all versions are affected though

### Expected behavior

Autocompletions set in **System Preferences > Keyboard > Text** in macOS should work in Electron apps. For example, in most applications on my Mac I can type `idk` and then `¯\_(ツ)_/¯` will show up in the text field I'm editing.

### Actual behavior

Nothing. I just keep on typing with no completion.

### How to reproduce

In a Mac, open **System Preferences > Keyboard > Text** and make a Replacement. See mine below:

<img width="361" alt="screen shot 2017-03-10 at 4 58 50 pm" src="https://cloud.githubusercontent.com/assets/5245670/23814778/dd67e804-05b2-11e7-8279-a9a2bb07ce61.png">

Now go to any electron app and behold the lack of working completions. This isn't a big deal for me, but for non-english typers, these completions are a core part of their accessibility on macOS. Thank you for the awesome work on Electron!

**Comment by MarshallOfSound** [comment]
@davidhariri This is supported through a third-party module

https://github.com/CharlieHess/electron-text-substitutions
