### ISSUE TITLE
CSS support in different OS's

### ISSUE THREAD

**Issue by iremlopsum** [electron/electron#8903]
Not sure if related directly to Electron, but will probably get an answer here.

On Windows position: sticky; works perfectly, but on Mac it's not supported. Any ideas?

**Comment by deprilula28** [comment]
I don't have a mac, but in my iPad the sticky position doesn't work either, maybe it's an apple system thing.

**Comment by kevinsawicki** [comment]
> On Windows position: sticky; works perfectly, but on Mac it's not supported. Any ideas?

@iremlopsum are you seeing the same behavior in standalone Chrome?

**Comment by iremlopsum** [comment]
@kevinsawicki Nope. standalone chrome works like a charm. Using electron version 1.6.0

**Comment by kevinsawicki** [comment]
> Nope. standalone chrome works like a charm. Using electron version 1.6.0

What version of Chrome did you try? Looks like there are several sticky issues on mac that fixed and still open, https://bugs.chromium.org/p/chromium/issues/list?can=1&q=sticky+OS%3DMac+&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids

Can you include a small reproduction example that shows the issue you are seeing? Thanks.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
