### ISSUE TITLE
Unable to copy text from PDF preview in Google Inbox when embedded in webview

### ISSUE THREAD

**Issue by TimNZ** [electron/electron#8908]
* Electron version: 1.x
* Operating system: All

### Expected behavior

* Preview PDF in Google Inbox
* Select/highlight text from PDF
* Trigger copy - OS keyboard shortcut or menu.
* Selected text is in clipboard

### Actual behavior
Selected text is not copied to clipboard when https://inbox.google.com embedded in a webview

Works fine when src for a BrowserWindow.

### How to reproduce
Run attached simple app and follow expected steps in both windows.

I've inspected the PDF preview in DevTools and Google are definitely doing some magic as the selected text in the PDF preview is 'fake' selected.  I can only presume they are doing a hook into the copy/clipboard mechanism to stuff the actual selected text into the clipboard.

Did a quick attempt to inspect event listeners for 'copy' but I quickly went beyond my pay grade.

Interested as to opinions as to whether this falls into Electron quirk space or not.

[google-inbox-pdf-copy.zip](https://github.com/electron/electron/files/836172/google-inbox-pdf-copy.zip)

**Comment by Thomas101** [comment]
Would love to be able to figure this out too. Also happens on https://mail.google.com.

Other things I've found whilst looking at it...
* `window.getSelection()` returns nothing sensible
* I found when inspecting the DOM the text is in there and I can find it in the DOM tree
* It looks like the text is nested within an iframe with an element over the top of it

**Comment by TimNZ** [comment]
Hey @kevinsawicki,

Who's the awesome person who can help with this? 
The issue responding rules aren't clear.

If something works in BrowserWindow and doesn't work in webview, is it safe to initially point finger at Electron, if we have disabled nodeintegration?

**Comment by kevinsawicki** [comment]
> If something works in BrowserWindow and doesn't work in webview, is it safe to initially point finger at Electron, if we have disabled nodeintegration?

It really depends, it could be a `<webview>` bug in Chromium or an Electron bug.

Usually we try to reproduce it in a `<webview>` tag in a chrome extension and see if it works there. If it doesn't then we open an issue upstream with reproduction steps that don't involve Electron.

Would you be able to give it a try in a `<webview>` based chrome extension?

**Comment by TimNZ** [comment]
Is there a starter kit for me to use to make this easy?

**Comment by kevinsawicki** [comment]
> Is there a starter kit for me to use to make this easy?

Yeah, I usually just install and modify https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/webview-samples/webview

**Comment by TimNZ** [comment]
Sweet.  

Will give it a go today. 

Thanks.

**Comment by TimNZ** [comment]
Broken in webview in Chrome app.  Other Inbox wrappers have the same problem.

Likely won't get anywhere given Google's dropping of Chrome Apps, but will post into Google forums and see if I get anywhere.  Might also play with user agent strings.
