### ISSUE TITLE
Rendered Html (colors, fonts) look different than in same Chrome standalone Version

### ISSUE THREAD

**Issue by reiberdatschi23** [electron/electron#8909]
* Electron version: 1.6.1
* Operating system: macOS Sierra
* Chrome Version (Standalone) for comparison: 56.0

### Expected behavior

Rendered content's colors should look exactly the same as on the same standalone chrome browser on the same operating system and version.

### Actual behavior

Colors and fonts are differently rendered.

### How to reproduce

Simply compare the online version at https://app.designer.io and the download version for mac on https://app.designer.io/_downloads/mac/GravitDesigner.zip and you will see a clear difference.

Also attach a sample screenshoot, in the background you see the app running in chrome standalone in foreground its running in Electron.

<img width="1459" alt="screen shot 2017-02-25 at 10 33 44 am" src="https://cloud.githubusercontent.com/assets/11421426/23832005/e12216ce-072c-11e7-95e0-1b21c92c0c32.png">

**Comment by ChrisFan** [comment]
+1

**Comment by afc163** [comment]
+1

**Comment by MarshallOfSound** [comment]
@afc163 Please do not "+1" issue threads, it adds needless email spam 😄 

You can instead use the reactions feature to react to the issue with 👍

**Comment by zcbenz** [comment]
Tested with Electron v1.7.x and Chrome 59, they were showing the same color with following page:

```html
<body style="background-color:#31375a">
</body>
```

It is interesting that Safari showed a different color.
