### ISSUE TITLE
beforeunload event not called on subsequent reloads

### ISSUE THREAD

**Issue by inukshuk** [electron/electron#8911]
* Electron version: 1.6.3
* Operating system: Linux

### Expected behavior

When registering a `beforeunload` handler which cancels unloading, I would expect the handler to be called for every `BrowserWindow.reload()`.

### Actual behavior

On 1.6.3, the `beforeunload` handler is called for the first `reload` but not on subsequent calls. Even after removing the event handler, `reload` will not reload the window anymore.

### How to reproduce

```javascript
const cancelUnload = e => {
   console.log('cancelUnload called')
   e.returnValue = false
}

window.addEventListener('beforeunload', cancelUnload)

remote.getCurrentWindow().reload()  // [1] -> cancelUnload called
remote.getCurrentWindow().reload()  // [2] -> cancelUnload called

remote.getCurrentWindow().close()   // [3] -> cancelUnload called
remote.getCurrentWindow().close()   // [4] -> cancelUnload called

window.removeEventListener('beforeunload', cancelUnload)

remote.getCurrentWindow().reload()  // [5] -> reloads window

remote.getCurrentWindow().close()   // [6] -> closes window
```
I would expect `cancelUnload` to be printed to the console four times and the step at `[5]` to actually reload the window. This is works up to Electron 1.6.2.

On Electron 1.6.3 `cancelUnload` is not printed at step `[2]` (nor on any subsequent calls to reload). What's more, event after removing the `beforeunload` handler, `reload` does not work anymore: at step `[5]` the window does not reload (but closing the window at `[6]` works).

**Comment by 22222** [comment]
I've been running into this problem too in v1.6.6.  

It looks this was caused by the changes in #8724.  I don't run into the issue with the v1.6.3 code if I revert the changes from dead1ae1ba5a1374bf6f41a0a79b92da82d7263f (or even just comment out one [return statement]( https://github.com/electron/electron/blob/dead1ae1ba5a1374bf6f41a0a79b92da82d7263f/atom/browser/api/atom_api_web_contents.cc#L1003)).
