### ISSUE TITLE
Possible to copy plaintext and html to clipboard at same time?

### ISSUE THREAD

**Issue by paulshapiro** [electron/electron#8914]
* Electron version: 1.5.0
* Operating system: MacOS Sierra

Hi all,

I have an HTML string (has links) that I need to put on the clipboard so it can be pasted e.g. into an email by user to send to a contact. Using the clipboard's `writeHTML` function works well for that as I have been able to paste the clipboarded content into an html-ready input such as Mail.app. 

But when I go to paste the same copied HTML into my code (plaintext) editor, it appears that whatever plaintext I copied from long before the HTML gets pasted instead of the HTML.

I figured I could circumvent this by calling both `writeText` and `writeHTML` but it appears to display similarly unexpected behavior… If I call `writeText` and then `writeHTML`, I can paste the HTML… but do not get the plaintext paste at all and instead get something from the past. But if I instead call `writeHTML` then `writeText` I get only the plaintext. 

So… tracing it out a little, I checked `chromium/scoped_clipboard_writer.h`, but couldn't see a multiple-type clipboard write function that might be hooked into…

I know in MacOS/`NSPasteboard` you can set data for different types simultaneously. Could this be a chromium limitation and is there any way we can work around it?

Many thanks

**Comment by kevinsawicki** [comment]
@paulshapiro have you tried `clipboard.write` and specifying both text and html like the example here: https://electron.atom.io/docs/api/clipboard/#clipboardwritedata-type

**Comment by paulshapiro** [comment]
No idea how I missed that. No, thanks, I will give it a shot.

**Comment by paulshapiro** [comment]
@kevinsawicki works, of course. Thanks :) *puts on cone of shame*

**Comment by kevinsawicki** [comment]
>  works, of course.

Glad to hear it, closing this out 👍
