### ISSUE TITLE
Geolocation using native OS APIs

### ISSUE THREAD

**Issue by jauhenk** [electron/electron#8918]
As I can see current geolocation mechanism uses google api with default GOOGLE_API_KEY. It's also  affects https://github.com/electron/electron/issues/8754
MacOS has location api https://developer.apple.com/reference/corelocation and there are a lot of different ways to implement it in general.
Same for Windows. It has Sensor API https://msdn.microsoft.com/en-us/library/windows/desktop/dd318953 and looks like it works for Windows 7 also.
What do you think about it? When it can be implemented?

Added: However looks like location sensor should be installed and enabled http://www.techsupportalert.com/content/how-enable-or-disable-location-sensing-windows-7-and-8.htm

**Comment by Janneman84** [comment]
No one stops you from using Node modules that do this. For Windows for example there is NodeRT which allows you to use UWP APIs in Electron. I tried getting my location this way last week, it works :).

**Comment by kevinsawicki** [comment]
Yeah, Electron builds on top of the support in Chrome so native node modules are a good way to go to add any additional functionality that builds directly on top of OS APIs.

Closing this out.

**Comment by epieddy** [comment]
For anyone finding this after a google search, I've lost many hours on the same problem : **I have a windows device WITH a hardware GPS but impossible to use it with electron / chromium by default.**

> No one stops you from using Node modules that do this. For Windows for example there is NodeRT which allows you to use UWP APIs in Electron. I tried getting my location this way last week, it works :).

@Janneman84 you are right, but chromium itself directly comes  with such WinRT implementation : https://github.com/chromium/chromium/blob/86.0.4226.1/services/device/geolocation/win/location_provider_winrt.cc

So why bother with building NodeRT for electron (not a simple task, It was my first solution before finding the "real" one) when it's already there. The weird thing is that chromium WinRT Location Provider is disabled by default. You have to explicitly enable it yourself @jauhenk :
- by using chrome://flags/#enable-winrt-geolocation-implementation 
- by using app.commandLine.appendSwitch('enable-features', 'WinrtGeolocationImplementation'); in your electron main process before the ready event (https://www.electronjs.org/docs/api/command-line)

Only then, the navigator.geolocation JS API will use your hardware GPS.

Hope this will help.

**Comment by 1mike12** [comment]
FYI, on the mac side, there is also a super simple flag to get native location working. This is true for electron 28 but I know at some point chromium removed the above windows and below mac flags in lieu of a different flag (`LocationProviderManager:LocationProviderManagerMode/PlatformOnly`)

```js
  if (process.platform === 'darwin') {
    enabledFeatures.push('MacCoreLocationBackend');
  }
```
