### ISSUE TITLE
Add clean script that only removes build files

### ISSUE THREAD

**Issue by babanesma** [electron/electron#8919]
* Electron version: 1.6.3
* Operating system: Windows 7

### Expected behavior

`npm run clean ` should only deletes the out directory as said in the docs https://electron.atom.io/docs/development/build-instructions-windows/#cleaning . 

### Actual behavior

It deleted the node_modules ( no real problem here because npm packages are cached on my system ) and `vendor/brightray/vendor/download/libchromiumcontent` & 
`vendor/brightray/vendor/libchromiumcontent/src` ( around 2 GB ) .

I should have checked `script/clean.py` before running , but I depended on the documentation . 
Is this the right behavior to delete what is downloaded from the bootstrap command ?

**Comment by kevinsawicki** [comment]
> Is this the right behavior to delete what is downloaded from the bootstrap command ?

Yeah, `npm run clean` is a pretty comprehensive reset that will require a full re-bootstrap afterwards.

We could have two separate clean scripts, one to do a full clean when you want a full reset (often needed after a chrome upgrade or `node_modules` corruption) and a clean that just cleans the build folders so a `npm run build` will do a full recompile.

**Comment by babanesma** [comment]
@kevinsawicki I made a pull request #8955 to add a new command `npm run clean-build` , it will only remove `out` and `dist` directories
