### ISSUE TITLE
Linking a library with an addon

### ISSUE THREAD

**Issue by toly-k** [electron/electron#892]
I am writing an addon that wraps a C++ library. Unfortunately I am having difficulties loading that library with atom-shell.
This is my binding.gyp:

```
{
    "targets": [{
        "target_name": "addon",
        "sources": ["test.cc"],
        "include_dirs": [
            "Headers",
        ],
        "link_settings": {
            "libraries": [
                "-lmylib.lib",
            ],
            "library_dirs": [
                "Lib",
            ],
        },
    }]
}
```

It works for tests with `node test.js`

```
//test.js
var addon = require('./build/Release/addon');
```

However when I do the same with `atom.exe test.js` it throws an exception "The specified module could not be found". Removing dependency on the library fixes the error, so I assume it is looking for mylib.lib in the wrong place?
A lot of the answers I found have an absolute path to a library i.e. /usr/lib
Is it possible to keep the library file locally?

**Comment by dougludlow** [comment]
@paulcbetts thanks for the suggestion to use Dependency Walker. I figured out the module I was importing was missing a `.dll`:  http://stackoverflow.com/questions/41253450/error-the-specified-module-could-not-be-found/
