### ISSUE TITLE
Feature Request: Detect if user is on metered connection

### ISSUE THREAD

**Issue by simonwjackson** [electron/electron#8921]
Id like to check if the system is on a metered connection.

In the UWP enviroment you can use something like [Windows.Networking.GetConnectionProfiles()](https://docs.microsoft.com/en-us/uwp/api/windows.networking.connectivity.networkinformation#Windows_Networking_Connectivity_NetworkInformation_GetConnectionProfiles) to get the data.

**Comment by MarshallOfSound** [comment]
@simonwjackson This functionality can be provided through the `nodert-win10` modules.

https://www.npmjs.com/package/@nodert-win10/windows.networking.connectivity

**Comment by simonwjackson** [comment]
This is great, thanks!
