### ISSUE TITLE
Make docs clearer about updating existing application menu

### ISSUE THREAD

**Issue by swashcap** [electron/electron#8928]
* Electron version: v1.6.2
* Operating system: OS X 10.12.3

### Expected behavior

Expected Electron’s default `Menu` to show an added `MenuItem`. The [`Menu` docs](https://electron.atom.io/docs/api/menu/) don’t mention anything about menus being immutable or `Menu.getApplicationMenu` returning an readonly instance.

I‘d be happy to PR the docs with info if this is the case!

### Actual behavior

No `MenuItem` added.

### How to reproduce

Distilled example:

```js
const { app, BrowserWindow, Menu, MenuItem } = require('electron')

let win

function createWindow () {
  win = new BrowserWindow({width: 800, height: 600})

  const menu = Menu.getApplicationMenu();

  menu.append(new MenuItem({
    label: 'Test menu item'
  }))

  win.on('closed', () => {
    win = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (win === null) {
    createWindow()
  }
})
```

Steps for running:

1. Save this as _example.js_
2. Install electron: `npm install electron`
3. Run the example: `node_modules/.bin/electron example.js`
4. Observe no mutated application menu

**Comment by changkun** [comment]
Runtime dynamic menu is not supported yet, see https://github.com/electron/electron/issues/7455.
You could rebuild the entire menu to archive this.

**Comment by kevinsawicki** [comment]
>  The Menu docs don’t mention anything about menus being immutable or Menu.getApplicationMenu returning an readonly instance.

The menu doesn't support adding/removing, but you can edit the "dynamic" properties of the menu items in the menu, https://electron.atom.io/docs/api/menu-item/#instance-properties

> I‘d be happy to PR the docs with info if this is the case!

That would be appreciated 👍 📝
