### ISSUE TITLE
.svg images doesn't render with GoPro VR Player installed

### ISSUE THREAD

**Issue by johnsenpeder** [electron/electron#8929]
* Electron version: 1.6.2
* Operating system: Ubuntu 16.04

### Expected behavior

`Type` of images in `Network` tab should be `svg+xml` and images should load normally.

### Actual behavior

`Type` shows as `goprovrplayer` in `Network` tab and images shows as broken in app.

![Broken images](http://i.imgur.com/0O3IH8n.png?1)

### How to reproduce

Use an `.svg` image in a `<img>` element. Have GoPro VR Player (http://www.kolor.com/gopro-vr-player/download/) installed then run electron app. All `<img>` elements using .svg files will be broken and `Type` of images in `Network` tab shows as `goprovrplayer`

![Wrong type](http://i.imgur.com/8sncWbp.png?1)

**Comment by enlight** [comment]
Can you reproduce this in Chrome 56?

**Comment by johnsenpeder** [comment]
Is that the version used in the 1.6.3 beta of Electron?
Just tested with that version and the problem persists.

As a side note, this issue is not happening in Chrome itself outside of Electron :thinking:

**Comment by deepak1556** [comment]
Can you provide a minimal example to reproduce the issue, the reproduction steps aren't clear. I have goproplayer installed and ran a page that displayed svg file, there wasn't any issue. I tested on `archlinux-4.10.1-1-ARCH`. Thanks!

**Comment by johnsenpeder** [comment]
@deepak1556 Here's a basic electron app with the issue present if the GoPro VR Player is installed https://github.com/johnsenpeder/electron_test

**Comment by johnsenpeder** [comment]
Ok, did some more testing, and figured out this DOES happen in Chrome (`Version 57.0.2987.98 (64-bit)`) too. However it only happens "locally". So opening the `index.html` file in Chrome from the repo I linked also results in the same issue..

**Comment by deepak1556** [comment]
Thanks for the test case, but unfortunately I am not able to reproduce either on MacOS or archlinux. I installed go pro player form the link provided and open the test app. The image was rendered with the right mimetype. Will defer to someone else who could reproduce the issue.

**Comment by rlatapy-gpsw** [comment]
@johnsenpeder 
Could you update the player to the new stable version (2.3.0) ?
http://www.kolor.com/gopro-vr-player/download/
This may be resolved as we change our management of MIME type association.
Thank you

**Comment by johnsenpeder** [comment]
@rlatapy-gpsw just tested with (2.3.0) and the issue is no longer there :+1:
