### ISSUE TITLE
Maximize frameless window goes out of screen on Windows 

### ISSUE THREAD

**Issue by paul321** [electron/electron#8932]
* Electron version: 1.4.15 - 1.6.3
* Operating system: Windows

In our app if the users are maximizing the app which is a frameless window, few pixels around the borders go out of screen, if i inspect the width of the window it says 1930 on a 1920 resolution, same for height.

**Comment by kevinsawicki** [comment]
I believe this is a duplicate of #8728

**Comment by paul321** [comment]
Yes it is :)
