### ISSUE TITLE
Ability to render using screen media (instead of print) when printing

### ISSUE THREAD

**Issue by ediweissmann** [electron/electron#8933]
By default `print` media is used when calling [webContents.printToPDF()](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsprinttopdfoptions-callback)

It would be useful to me to be able to override this and render the page using `screen` media so wysiwyg in the exported PDF.

Thanks for reading!

**Comment by zcbenz** [comment]
While this is a nice feature to have, it requires work on Chromium's side to provide the ability to specify media for printing. I suggest reporting this to Chromium to add that ability first, and then we can implement this on Electron's side.
