### ISSUE TITLE
Bootstrap issue

### ISSUE THREAD

**Issue by deprilula28** [electron/electron#8934]
* Electron version: Latest
* Operating system: Windows 10

This happends when I try to run the bootstrap with python 27:

> Unable to checkout 'a6663598aa78832e7955cb93c51a098eac787abb' in submodule path 'vendor/node'
> None
> Traceback (most recent call last):
>   File "script\bootstrap.py", line 264, in <module>
>     sys.exit(main())
>   File "script\bootstrap.py", line 34, in main
>     update_submodules()
>   File "script\bootstrap.py", line 128, in update_submodules
>     execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
>   File "..\electron\script\lib\util.py", line 180, in execute_stdout
>     raise e
> subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1

(After other stuff, if you need that I can post it here)

**Comment by deprilula28** [comment]
I got the latest version of Git and done everything the quide at https://electron.atom.io/docs/development/build-instructions-windows/ told me to do.

**Comment by kevinsawicki** [comment]
Sorry about this, it was because the commit the submodule was referencing was on a branch that had been deleted without merging.

It should now be available and able to be cloned successfully, closing this out.

**Comment by deprilula28** [comment]
It's still happening...

**Comment by kevinsawicki** [comment]
@deprilula28 can you try running `npm run clean` and trying again?

**Comment by deprilula28** [comment]
Seems to be working now, thanks for the support.

**Comment by kevinsawicki** [comment]
> Seems to be working now, thanks for the support.

Great to hear, thanks for the update 👍
