### ISSUE TITLE
White line (border) on the right side on the HiDPI screen

### ISSUE THREAD

**Issue by yustnip** [electron/electron#8935]
* Electron version: 1.4.15, 1.4.6
* Operating system: Ubuntu 16.04.2

### Expected behavior

 An app window doesn't have a white line on the right side when it runs on the HiDPI screen.

### Actual behavior

An app window has a white line on the right side when it runs on the HiDPI screen.

### How to reproduce
Install for example the lastest version of VS Code or Keeweb (dark theme). Try to change a window size by the mouse. VS Code in my case have the white line in the expanded mode.

Screen resolution: 3840x2160, scaling factor: 2.5 or 2.

![screenshot from 2017-03-16 01-06-32](https://cloud.githubusercontent.com/assets/9950871/23972925/d9c7b2ca-09e4-11e7-8c7f-3c6f8a08409c.png)

**Comment by yonson2** [comment]
I' m also getting this issue with [hyper](https://github.com/zeit/hyper)

I think that it's probably related to the chrome version being used by the electron app, as of chrome v54 this bug [_should_ be fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=478133)

**Comment by JPenuchot** [comment]
Same here using Atom

**Comment by yustnip** [comment]
@yonson2 Yes, it is. After last update of VS Code (Electron version 1.6.6) the problem is gone.

**Comment by zcbenz** [comment]
Closing since it seems to have been fixed in 1.6.x.
