### ISSUE TITLE
Sources don't reloaded into debug electron window

### ISSUE THREAD

**Issue by alexey2baranov** [electron/electron#8936]
hello! 

We debug our sources into electron debug window. When we change some source file on hard disk this file don't changed inside electron debug window. The workaround for this is to close and reopen electron window, then open this file again and continue debugging.

We are interesting Is it lack of debug process or maybe we do something wrong?

**Comment by zcbenz** [comment]
I suggest testing your app in Chrome browser first, it would be a bug if Electron behaves differently on this from Chrome.
