### ISSUE TITLE
[Touchbar] Ability to switch between "Exit Fullscreen" button and "ESC" key

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#8937]
Safari replaces the `esc` key by an exit fullscreen button when playing a video fullscreen.

Safari playing a Youtube video not fullscreen:
![touchbar-safari-windowed](https://cloud.githubusercontent.com/assets/797899/23996579/de4ce1f4-0a88-11e7-9605-59136fe843e0.png)

Safari playing a Youtube video fullscreen:
![touchbar-safari-fullscreen](https://cloud.githubusercontent.com/assets/797899/23996596/e9b70a74-0a88-11e7-90ce-0eb13487d047.png)

Note: When putting the Safari app in fullscreen (with no video involved), they keep the ESC key.

I've also stumbled this issue for chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=690611

This would be useful for Electron apps embedding videos.

cc @MarshallOfSound @kevinsawicki

**Comment by MarshallOfSound** [comment]
Reference docs: https://developer.apple.com/reference/appkit/nstouchbar/2787731-escapekeyreplacementitemidentifi
