### ISSUE TITLE
Unable to use a custom protocol to load main HTML in rendererer process

### ISSUE THREAD

**Issue by bendemboski** [electron/electron#8940]
* Electron version: all
* Operating system: all

#### Summary

When using a custom protocol handler to load an HTML file out of the filesystem, the renderer process should still be able to include dependencies out of `node_modules`.

#### Details

Exposing custom protocol handlers is awesome, and very helpful for building out apps that can easily run under both electron and in a browser. We do this over in `ember-electron` by setting up a `serve:` custom protocol handler that maps URIs to filesystem URIs, and then loading our `index.html` using a `serve:` URL so that all of our absolute resource paths (`/images/foo.jpg`) will end up being handled by our custom protocol handler, rather than becoming absolute filesystem paths that clearly won't point to the right place.

This seems like a valuable use case (re-mapping filesystem paths using a custom protocol handler) for electron to support.

#### Summary

In such a case, the renderer process cannot include dependencies out of `node_modules`.

#### Details

Unfortunately, a side-effect of the setup described above is that [this](https://github.com/electron/electron/blob/5200b1a1ab6f76f5944c6d5f728bc51827101b31/lib/renderer/init.js#L106) code can't find the filesystem path to `index.html` and can't set up the module search paths, so the renderer process can't include any dependencies out of `node_modules`.

### How to reproduce

I've put together a demo app [here](https://github.com/bendemboski/electron-protocol-bug). To run it:

```
$ git clone git@github.com:bendemboski/electron-protocol-bug.git
$ cd electron-protocol-bug
$ npm install
$ <path to electron> . # can require dependency
$ <path to electron> . serve # cannot require dependency
```

Launching the app with no command-line argument will load `index.html` via a `file:` URL, and it will be able to require a dependency out of `node_modules` (as indicated on the page). Launching it with the `serve` argument will load `index.html` using a URL with a custom protocol (`serve://`), and it will be unable to require a dependency out of `node_modules`.

### Thoughts on a fix

I can think of two fixes, but I'm not sure if the first one is possible:

1. If [this](https://github.com/electron/electron/blob/5200b1a1ab6f76f5944c6d5f728bc51827101b31/lib/renderer/init.js#L106) code has access to the registered protocol handlers, then perhaps it could check if the protocol of `window.location` matches a custom file protocol handler, and if so, call it to get the filesystem path to the HTML file being loaded?
2. Provide a command-line argument to Electron allowing the caller to specify what they want the path to their "main module" to be which, if set, would override the logic that tries to discover it using `window.location`.

**Comment by zcbenz** [comment]
It is impossible to know whether and where the web page is on filesystem in renderer process, even when we know the protocol handler serves files, so it is impossible to correctly set the module search path.

This is a limitation of Chromium's networking stack, and we are unable to work around it in Electron. So I'm closing this as won't fix.

A popular solution to this problem is to set module search paths in `preload` scripts.
