### ISSUE TITLE
Controlling keyboard and mouse with electron

### ISSUE THREAD

**Issue by ilmam** [electron/electron#8941]
I'm quite new to electron and node.js in general, and trying to learn it via real but small projects.
I don't konw if my question is stupid or valid here, but can I create an app that controls the input interface of my mac.
For example can I disable keyboard or trackpad temporarily. Can I intercept certain key event to disable it? Is it possible to do that even when the app is not under focus?
My first app was with file system and it was pretty straight forward, but I am not sure I can achieve more complex operations with electron. 
Any thoughts?

**Comment by kevinsawicki** [comment]
> Can I intercept certain key event to disable it?

There are some APIs to send and intercept keyboard/mouse events:

* https://electron.atom.io/docs/api/web-contents/#event-before-input-event
* https://electron.atom.io/docs/all/#winsetignoremouseeventsignore
* https://electron.atom.io/docs/all/#contentssendinputeventevent

You can also extend Electron with C++ modules so it is feasible to add additional features to your app that access these platform APIs even if Electron does not currently expose it.

Closing this out.
