### ISSUE TITLE
Child process not receiving messages when created with an `--eval` argument to `child_process.fork`

### ISSUE THREAD

**Issue by nathansobo** [electron/electron#8944]
* Electron version: 1.6.3
* Operating system: macOS 10.12.3

In [this example repository](https://github.com/atom/electron-child-process-test), I'm creating two child processes via `child_process.fork`, one using `--eval` and the other via a module path to a file containing essentially the same source as I'm evaling in the first case. The code is as follows:

```js
const sourceToEval = `
  console.log('starting child process 1')
  process.on('message', m => console.log('child 1 got message', m))
  console.log('waiting for messages in child process 1...')
`

const {fork} = require('child_process')

console.log('forking child process 1 (using --eval)')
const child1  = fork('--eval', [sourceToEval])
console.log('done forking child 1, sending message')
child1.send('hello from your parent')

console.log('forking child process 1 (using module path)')
const child2  = fork('./child')
console.log('done forking child r, sending message')
child2.send('hello from your parent')
```

### Expected behavior

I would expect to see output from *both* child processes on `stdout` of the parent when they receive messages.

### Actual behavior

I only see output from the process forked with a module path.

### How to reproduce

Run the app at https://github.com/atom/electron-child-process-test

**Comment by nathansobo** [comment]
Worked around this in Atom by converting `task-bootstrap.coffee` to vanilla JS and thereby avoiding the use of `--eval`, in case that affects its priority.

**Comment by kevinsawicki** [comment]
I was able to reproduce this using standalone node, appears to work in Node 7.0.0, but no version past that.

Reported upstream at: https://github.com/nodejs/node/issues/11948

**Comment by bpasero** [comment]
Looks like node.js 7.8.0 fixes this. We are currently blocked on this issue for the VS Code adoption and would benefit from a node.js update within Electron if possible.
