### ISSUE TITLE
ready-to-show not emitted if window height is too small to show the content

### ISSUE THREAD

**Issue by hkuclion** [electron/electron#8946]
* Electron version: 1.6.2
* Operating system: Windows 10

### Why this happened

I'm using window state manager and for some reason, the width and height falls to 0 when saving the state. The next time I open the app, nothing shown.

### Expected behavior

emit `ready-to-show` event and show the window in the callback

### Actual behavior

event not emitted, so no window shown
webContents `did-finish-load` emitted and write callback there did show the window

### How to reproduce

```
var electron = require('electron')
var window = null;
const url = require('url');
const path = require('path');

electron.app.once('ready', function () {
  window = new electron.BrowserWindow({
    width: 100,
    height: 50,
    show: false,
  })

  window.loadURL(url.format({
	pathname:path.join(__dirname, 'test.html'),
	protocol:'file:',
	slashes:true
  }));

  window.once('ready-to-show', function () {
    window.show();
  });
});
```

height 50 on my win10 is only half the height of the menu, so no content is in sight.
as long as the height is enough to show any content, the `ready-to-show` event is emitted.

**Comment by zcbenz** [comment]
Merging this to #7779 .
