### ISSUE TITLE
<input type='file' /> and special folders

### ISSUE THREAD

**Issue by arusakov** [electron/electron#8948]
* Electron version: 1.6.2
* Operating system: macOS 10.12.3

### Actual behavior
I faced with strange behaviour of `<input type='file' />` in Electron.
You can select special Macs' folders - app folders (for example `/Applications/Calculator.app`).
In Finder it looks like file, but it's directory!

### Expected behavior
There are two possible ways.

1. `Chrome`way (and Safari). In real Chrome you can select `Calculator.app` from `<input type='file' />`. But Chrome transparently created `Calculator.app.zip` and attached this archive to input.
2. `Firefox` way. In Firefox you can not select any folders from `<input type='file' />`

### How to reproduce
I have created simple fiddle for that https://jsfiddle.net/s7c7k33b/ for testing in different browsers and Electron

**Comment by shubham2892** [comment]
I have proposed a fix where the file packages are treated as directories, but IMHO it would be great if there could be a flag which when enabled would treat them as file and attach the `.zip` version of them to the input.
