### ISSUE TITLE
After logging into gmail, a white screen is displayed.

### ISSUE THREAD

**Issue by Binom777** [electron/electron#8950]
OS: Linux mint 18.1 KDE Edition (64)
Electron: v1.6.2

![electron-1](https://cloud.githubusercontent.com/assets/5434754/24049337/c0ddfd10-0b3c-11e7-8722-67cf959033c0.png)

After logging...

![electron-2](https://cloud.githubusercontent.com/assets/5434754/24049338/c0e02568-0b3c-11e7-9038-89c880839aa4.png)
 
A simple code for repetition:

test.js:

```

const electron = require ('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

let mainWindow;

function createWindow () {
    mainWindow = new BrowserWindow ({
        Width: 1224,
        Height: 768,
    });
    mainWindow.webContents.openDevTools ();
    mainWindow.loadURL ("https://gmail.com")
}
app.on ('ready', createWindow);
app.on ('window-all-closed', function () {
    if (process.platform  == 'darwin') {
        App.quit ()
    }
});

```

P.s.

If you use webview as a preloader, there is no bug, but such a crutch does not fit

test.html:

```
<! DOCTYPE html>
<Html>
<Head>
    <Title> ok </ title>
</ Head>
<Body style = "overflow: hidden;">
<Webview id = "webview" src = "https://gmail.com" style = "position: absolute; width: 100%; height: 100%;"> </ webview>
</ Body>
</ Html> 
```
 
test.js:
```
  ..
var fs = require ('fs');
mainWindow.loadURL ('file: //' + __dirname + '/test.html');
 .. 
```

 

There is a possibility that this is a bug of the system, but I very much hope that you will tell me what to do about it.

**Comment by MarshallOfSound** [comment]
@Binom777 You probably have to disable `nodeIntegration` on your BrowserWindow to stop the node.js globals affecting gmail's website 👍

**Comment by Binom777** [comment]
@MarshallOfSound  If we talk about this code

```
   MainWindow = new BrowserWindow ({
         Width: 1224,
         Height: 768
         , WebPreferences: {
             NodeIntegration: false

         }

     });
```

That did not help :(

 
Addition to the above bug:

If you restart the application and you are already authorized, then gmail is displayed correctly.

**Comment by MarshallOfSound** [comment]
@Binom777 That's not quite the correct syntax for disabling node integration.  Try this

```js
mainWindow = new BrowserWindow ({
  width: 1224,
  height: 768,
  webPreferences: {
    nodeIntegration: false,
  },
});
```

**Comment by Binom777** [comment]
@MarshallOfSound 

Capital letters are the autocorrector.
Using the same code as you.
The problem is not solved.

**Comment by timfish** [comment]
![image](https://cloud.githubusercontent.com/assets/1150298/24214662/8105a7a8-0f36-11e7-827b-77ab0b8e2d48.png)

Whats the error in the console?

**Comment by Binom777** [comment]
@timfish  The bug you are asking about:

`notifications.google.com/u/0/widget?sourceid=23&hl=ru&origin=https%3A%2F%2F…578207532&parent=https%3A%2F%2Fmail.google.com&pfname=&rpctoken=27847995:1 XMLHttpRequest cannot load https://accounts.google.com/ServiceLogin?passive=1209600&osid=1&continue=ht…=https://notifications.google.com/u/0/_/NotificationsOgbUi/idv/&authuser=0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://notifications.google.com' is therefore not allowed access. `

**Comment by zcbenz** [comment]
Looks like a bug of GPU rendering, you may try using Electron with GPU acceleration disabled.

I'm closing this since none of us in Electron team is familiar with Chromium's GPU rendering enough to be able to fix bugs with GPU rendering,
