### ISSUE TITLE
Add option to ignore tray double-click events

### ISSUE THREAD

**Issue by pronebird** [electron/electron#8952]
Tray icon does not process any clicks after first click/double-click until after certain timeout. You can see that system highlight still appears and disappears, but no events are dispatched. This is super annoying because the timeout is around a second or so. Quite frequently I spot that the click on tray icon did nothing however visual feedback was provided.

I think something is up in here: https://github.com/electron/electron/blob/master/atom/browser/ui/tray_icon_cocoa.mm#L219

I don't have popup menu since I have a menubar with improvised popover displayed down under tray icon. I think Tray menu should check if menu controller exists and let clicks go through otherwise. Right now it seems that it attempts to handle standard context menu in the same fashion even if there is none.

* Electron version: 1.6.3
* Operating system: macOS

### Expected behavior

Expected clicks or double-clicks being dispatched repeatedly.

### Actual behavior

No clicks received after first double click.

### How to reproduce

In order to reproduce that create a tray icon and add two handlers to it:

```js
var tray = new Tray(nativeImage.createEmpty());
tray.on('double-click', () => {
  console.log('tray.double-click');
});
tray.on('click', () => {
  console.log('tray.click');
});
```

Now start clicking like crazy non-stop, you can keep clicking forever and will not receive any event after click/double-click are dispatched. You have to wait over 1 second in order to get next click.

Your console log should look like this:

```
tray.click
tray.double-click
```

**Comment by romaincointepas** [comment]
I think this behavior is required in order to detect the `double-click` event.

Maybe an option or method to disable listening (and waiting) for double-click events could solve this issue? (Personally, I've never seen a menubar icon that listen specifically for double-click on macOS.)

**Comment by pronebird** [comment]
@romaincointepas not the case with any other icons, i.e Dropbox

**Comment by romaincointepas** [comment]
@pronebird All those menubar apps probably don't handle double-click events so they don't have any waiting logic to handle double-clicks, so they fire click events as they come.

**Comment by mattiascaricato** [comment]
is there anyway to disable listening and waiting for `double-click` event?

**Comment by mkhalilOblong** [comment]
Yeah, I think it would be really useful to be able to disable listening for a double-click event for trays. 

Otherwise, I think the 'double-click' event might just be something that the application developer should have to worry about, versus electron actually handling the logic. Seems like a rare use case to have to support double click events for trays.

**Comment by insideGen** [comment]
The `click` event should be ignored when `double-clicking` on tray. There is not this behaviour at this moment. It is interesting to have two types of clicking sequences (`click` and `double-click`) to do different actions.
Any improvement?

**Comment by pronebird** [comment]
I don't know a single app using double click on tray icon. It seems quite esoteric to support that.

**Comment by mtaa** [comment]
disable double-click!!! +1
