### ISSUE TITLE
Open new BrowserWindow in the same renderer process

### ISSUE THREAD

**Issue by seanchas116** [electron/electron#8959]
## Idea

It would be great if Electron can open new BrowserWindow with the same renderer process. It would make it easier to use subwindows in Electron, like native desktop apps.

## Example

```js
// Add function `popupBrowserWindow` that opens a BrowserWindow
// with the same renderer process
// like native window.open supported in sandboxed mode,
// but has full control of BrowserWindow
const popup = popupBrowserWindow("popup.html", {
  width: 800,
  height: 400,
  parent: remote.getCurrentWindow(),
  modal: true,
});
popup.window // => Window object of new window
popup.browserWindow // => Remote BrowserWindow of new window
popup.window.document.body.innerHTML = "<h1>Hello</h1>" // You can access its DOM directly
```

## Benefits

* It becomes easier to open DOM-based dialogs or floating windows in native way
  * You'll have direct DOM access to subwindows
  * For example, you could use https://github.com/JakeGinnivan/react-popout
* Less resource consuming when opening many subwindows, as you don't need new processes

## Node integration

I'm not sure if newly opened windows can have Node integration, but it wouldn't be needed in use cases for dialogs or popups.

**Comment by tarruda** [comment]
Why not use `sandbox: true` if you want native `window.open` API?

**Comment by seanchas116** [comment]
> Why not use sandbox: true if you want native window.open API?

Because I also want to use full Node.js support including native addons in the renderer process.
Probably you can proxy it via IPC but I think it would reduce convenience of Electron.

**Comment by tarruda** [comment]
Right now sandbox mode supports the `remote` module, so you can probably use most node.js modules without much effort(`require('electron').remote.require('module')`). The `fs` module proxy is already available directly as `require('fs')` from the renderer, but we may add more modules.

**Comment by seanchas116** [comment]
Using all Node modules through `remote.require` would be bothersome. For example if you add callbacks to remote objects and reload the window later, you'll have dangling callbacks and Electron will throw errors.
