### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by alexey-baranov** [electron/electron#8961]
Hello! I find many issues about this error but i have done all recepts and get this error anyway

> 
> [Window Title]
> Error
> 
> [Main Instruction]
> A JavaScript error occurred in the main process
> 
> [Content]
> Uncaught Exception:
> Error: Could not locate the bindings file. Tried:
>  → W:\termilocal-js\app\node_modules\serialport\build\serialport.node
>  → W:\termilocal-js\app\node_modules\serialport\build\Debug\serialport.node
>  → W:\termilocal-js\app\node_modules\serialport\build\Release\serialport.node
>  → W:\termilocal-js\app\node_modules\serialport\out\Debug\serialport.node
>  → W:\termilocal-js\app\node_modules\serialport\Debug\serialport.node
>  → W:\termilocal-js\app\node_modules\serialport\out\Release\serialport.node
>  → W:\termilocal-js\app\node_modules\serialport\Release\serialport.node
>  → W:\termilocal-js\app\node_modules\serialport\build\default\serialport.node
>  → W:\termilocal-js\app\node_modules\serialport\compiled\7.4.0\win32\x64\serialport.node
>     at bindings (W:\termilocal-js\app\node_modules\bindings\bindings.js:88:9)
>     at Object.<anonymous> (W:\termilocal-js\app\node_modules\serialport\lib\bindings.js:3:35)
>     at Object.<anonymous> (W:\termilocal-js\app\node_modules\serialport\lib\bindings.js:36:3)
>     at Module._compile (module.js:571:32)
>     at Module._extensions..js (module.js:580:10)
>     at Object.require.extensions.(anonymous function) [as .js] (W:\termilocal-js\app\node_modules\babel-register\lib\node.js:152:7)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
> 
> [ОК]

first off all i did 
1. npm install --global --production windows-build-tools
2. npm install --save serialport
3. npm install --save-dev electron-rebuild
4. ./node_modules/.bin/electron-rebuild
everithing done successfully . 

after that i do `npm run dev` and get error like this. By the way i have ./node_modules/serialport/build/Release/serialport.node file.

I'm looking what should else i do to start serialport inside electron? 

Windows 7 64bit
node.js v7.4.0
electron v1.6.2

**Comment by crystalOrigin** [comment]
I just posted the same problem [here](https://github.com/railsware/bozon/issues/40). I am using the bozon boilerplate. At least your paths look appropriate. I am getting paths that are missing a big section out of the middle of them. I even copied the ```build/Release``` dir from ```app/node_modules/serialport``` to one of the paths it says it is trying and it still didn't work.

Did you see [this post](https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/538)? 

This is very frustrating.

**Comment by alexey-baranov** [comment]
@crystalOrigin 
as I can understand from this long discussion Electron is stupid enough with native modules. So I desided to leave Electron 
https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/538

**Comment by MarshallOfSound** [comment]
@alexey-baranov A quote from that linked issue that caused it to be closed

> I think this issue should be closed, right? This is not an issue, haven't been for a long time cause node-serialport works just fine with Electron.

> The main problem is that of Electron, everyone who starts using Electron will have issues with native modules, and most issues in this thread is about getting native modules to work.

`node-serialport` works just fine, I know because I've used it 😆

**Comment by crystalOrigin** [comment]
@MarshallOfSound Yes, serialport works great. My situation is figuring out how to properly configure a cross platform dev setup (on OS X for Windows) for a project that (1) uses a native module and (2) is built on an electron boilerplate (bozon) that (3) uses webpack. And it's my first electron app. I've got it working great on OS X, but trying to get it to work on Windows has been very frustrating.

**Comment by yanlee26** [comment]
Uncaught Exception:
Error: Could not locate the bindings file. Tried:
 → /



still exist
