### ISSUE TITLE
Invalid access to memory location. in edge\lib\native\win32\x64\6.4.0\edge_nativeclr.node

### ISSUE THREAD

**Issue by Sindcs** [electron/electron#8966]
when i use edge.js in electron ,i got this wrong mes "Invalid access to memory location. in edge\lib\native\win32\x64\6.4.0\edge_nativeclr.node",pleace tell me the  reason,thanks!!

**Comment by kevinsawicki** [comment]
Can you provide instructions for how to reproduce this? Thanks.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
