### ISSUE TITLE
On windows - closing an unsaved file cannot be dismissed with a keystroke

### ISSUE THREAD

**Issue by elis** [electron/electron#8967]
I'm using windows 10, and one of the most annoying things in this operating system is that it's extremely hard to identify the keys you need to press to dismiss various dialogs and modals.

When trying to close a bunch of "unsaved files", often happens when switching branches with files that exist on the previous branch but are missing from the new branch, it's very tedious to go over closing the tabs and having to manually go with the mouse to the "Don't Save" button in the regular windows dialog.

Can we address this somehow? Can we create a "close all and dismiss" function? Is there anything we can do to mitigate this annoyance?

Cheers.

**Comment by MarshallOfSound** [comment]
@elis Is this the intended repository for this issue, might be wrong here but looks like it's more intended for `atom/atom` or `Microsoft/vscode`

**Comment by kevinsawicki** [comment]
> Can we address this somehow?

This is application specific, access keys are supported to the `dialog.showMessageBox` API so apps could do this:

```js
dialog.showMessageBox({title: 'hello', buttons: ['&Yes', '&No']})
```

That would make `Yes` selectable with `Alt-Y` and `No` selectable with `Alt-N`.

>  Can we create a "close all and dismiss" function?

Applications should manage this type of behavior, Electron only provides raw dialog APIs that should be used with good user experience in mind.

> Is this the intended repository for this issue, might be wrong here but looks like it's more intended for atom/atom or Microsoft/vscode

👍 Closing out here.
