### ISSUE TITLE
how to use ffmpeg libopenh264 in electron v1.6.2

### ISSUE THREAD

**Issue by Klchan-me** [electron/electron#8968]
how to use ffmpeg libopenh264 in electron v1.6.2

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW Electron `1.6.2` supports H264 content
