### ISSUE TITLE
Menu popup options will only work with `async`

### ISSUE THREAD

**Issue by subwaymatch** [electron/electron#8973]
* Electron version: 1.6.2
* Operating system: Windows 7

Electron's doc for `menu.popup()` mentions that `async` option is not required. 
<br />

![image](https://cloud.githubusercontent.com/assets/1064036/24130087/f210308e-0e29-11e7-82ba-a87ae4cf81de.png)

However, when an option object is passed to `menu.popup()`, `async` seems to be required. 

<br /><br />

### Expected behavior

**Pass an empty option object** - should work
```
userMenu.popup(remote.getCurrentWindow(), {});
```
<br />

**Setting only `x` and `y`** - should work
```
userMenu.popup(remote.getCurrentWindow(), { 
	x: openPosition.x, 
	y: openPosition.y
});
```
<br /><br /><br />

### Actual behavior

**Pass an empty option object** - throws an error
```
userMenu.popup(remote.getCurrentWindow(), {});
```
![image](https://cloud.githubusercontent.com/assets/1064036/24130307/14c93c96-0e2b-11e7-8aaa-d3f2239f2b74.png)
<br />
**Setting only `x` and `y`** - throws an error
```
userMenu.popup(remote.getCurrentWindow(), { 
	x: openPosition.x, 
	y: openPosition.y
});
```
![image](https://cloud.githubusercontent.com/assets/1064036/24130179/667f8b7c-0e2a-11e7-85a9-6b79c8804600.png)
<br />

**No option object passed** - works fine
```
userMenu.popup(remote.getCurrentWindow());
```
<br />

**Setting `x`, `y`, `async`** - works fine
```
userMenu.popup(remote.getCurrentWindow(), { 
	x: openPosition.x, 
	y: openPosition.y, 
	async: true 
});
```
<br />

**Setting only `async` (no `x` and `y`)** - works fine
```
userMenu.popup(remote.getCurrentWindow(), { 
	async: true 
});
```
<br /><br />

### How to reproduce

```
const electron = require('electron'); 
const remote = electron.remote; 
const Menu = remote.Menu;

var userMenu = Menu.buildFromTemplate([
	{
		label: "Test",
		accelerator: "Ctrl+T",
		enabled: true, 
		click: function(item, focusedWindow) {
			// do nothing
		}
	}
]); 

userMenu.popup(remote.getCurrentWindow(), { 
	x: 100, 
	y: 100
});
```

**Comment by kevinsawicki** [comment]
Thanks for reporting this 👍
