### ISSUE TITLE
"unresponsive" event is incorrectly fired when calling synchronous version of `dialog` methods

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#8975]
* Electron version: 1.6.3
* Operating system: 10.11 and 10.9.5

This is a regression bug. The initial description and fix are detailed [here](https://github.com/electron/electron/issues/6146)

**Comment by kevinsawicki** [comment]
> This is a regression bug.

@astoilkov do you know the last version this worked for you in?

**Comment by astoilkov** [comment]
@kevinsawicki I don't know. However, if this information is important to you I could manually perform a binary search for the version it started happening.

**Comment by zcbenz** [comment]
I can reproduce this and I'm reopening #6146.
