### ISSUE TITLE
Share Files Between Different O.S Packages

### ISSUE THREAD

**Issue by ricky2k7** [electron/electron#8978]
I've created an app and build packages for Windows and MacOS using electron-packager. The app data is stored in a JSON file inside the resources folder and i'm using fs to perform file I/O tasks in the app.

What i would like to do is store the JSON file in a folder that could be accessed by both packages (Win and Mac). This way my client could use both versions of the app and the data source will be the same, thus, the data always updated.

Since i'm a Electron newbie, is there a way to "merge" both packages and share the same data file?

**Comment by timfish** [comment]
how are you going to run both packages on any one platform?

**Comment by ricky2k7** [comment]
The idea isn't to make the app portable. Both versions (Win and Mac) will be stored in an usb drive, and the user would chose the packaged based on their OS.

**Comment by ricky2k7** [comment]
Thanks to @kevingelion and @revln9 from the Slack Electron discussion, i was able to solve my issue.
All i need to use is getAppPath() and from there go to the parent folder where the data file is located:

```

**Comment by MarshallOfSound** [comment]
Issues sounds like it was solved :+1:
