### ISSUE TITLE
executeJavaScript does not take an external variable

### ISSUE THREAD

**Issue by Binom777** [electron/electron#8979]
OS: Linux mint 18.1 KDE Edition (64)
Electron: v1.6.2

**A simple code for repetition:**

test.js:

```
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;
let mainWindow;

function createWindow (  ) {
    mainWindow = new BrowserWindow({ width: 1024,  height: 768, });
    mainWindow.webContents.openDevTools();
    mainWindow.loadURL("https://google.com");

    mainWindow.webContents.on('did-finish-load', function() {
        let pac = {test:"is ok!"};
        mainWindow.webContents.executeJavaScript( `console.log( "ok?" ,  ${pac}   ) ` );

    });


    mainWindow.focus();
    mainWindow.on('closed', function() {
        mainWindow = null;
    });
}

app.on('ready', createWindow);
app.on('window-all-closed', function () {
    if (process.platform !== 'darwin') {
        app.quit()
    }
});

```

**Expect in browser console:**
`ok? Object {test: "is ok!"}`

**In fact, the console error:**

```
Uncaught SyntaxError: Unexpected identifier
    at EventEmitter.electron.ipcRenderer.on (/home/binom/WebstormProjects/electron_beta/node_modules/electron/dist/resources/electron.asar/rende…:51)
    at emitMany (events.js:127)
    at EventEmitter.emit (events.js:201)
```

**Line on which error:**

![bug-executejavascript](https://cloud.githubusercontent.com/assets/5434754/24161582/dfb81338-0e75-11e7-8070-bf740c0cc648.png)

P.s.

Of course, maybe I do not understand something, but in my opinion the code above should work correctly.

**Comment by binux** [comment]
```
mainWindow.webContents.executeJavaScript( `console.log( "ok?" ,  ${JSON.stringify(pac)}   ) ` );
```

**Comment by Binom777** [comment]
@binux Thank you
Yes, this is like solving a problem for passing parameters.
But I thought this should be done automatically.

**Comment by kevinsawicki** [comment]
> But I thought this should be done automatically.

The `executeJavaScript` API takes a string parameter so you must pass it valid JavaScript, closing this out. String interpolation runs `toString` on the object which generates invalid JavaScript in this case.

Thanks @binux for the correct usage example.
