### ISSUE TITLE
Feature request: Implement macOS (private) notification APIs

### ISSUE THREAD

**Issue by Dexwell** [electron/electron#8981]
Specifically, support the `identityImage` property in notifications for Electron apps not published on the Mac App Store. This allows notifications to show an image on the left, and is used by Apple for iMessage profile pictures and iTunes album art. Example:

![screen shot 2017-03-22 at 12 52 37](https://cloud.githubusercontent.com/assets/521176/24196556/75390f9c-0efe-11e7-9e6c-d544ed993c8b.png)

Per [indragiek/NSUserNotificationPrivate](https://github.com/indragiek/NSUserNotificationPrivate) this is implemented as follows:

```objectivec
NSUserNotification *n = [NSUserNotification new];
[n setValue:self.identityImage forKey:@"_identityImage"];
```

Other private notification APIs include: ignoring Do Not Disturb, only posting to lockscreen, managing the poof animation, and creating alternative action menus. See the repo linked above. 

Additionally, support for the inline notification reply (public) API would be really appreciated.

**Comment by dkfiresky** [comment]
Why these private APIs should be implemented in Electron's core?

**Comment by Dexwell** [comment]
@dkfiresky I'm new to Electron, so I figured native private APIs could not be called?

**Comment by MarshallOfSound** [comment]
@Dexwell Notifications are currently implemented in a native HTML5 Notification compatible way.  I.e. We implement the HTML5 Notification spec

Extra stuff like this doesn't have a place in the spec yet so most people use modules like [this one](https://github.com/CharlieHess/node-mac-notifier) that implement more extensive API's for system level notifications.

**Comment by Dexwell** [comment]
@MarshallOfSound Gotcha, thanks. Might be better to suggest it there then.

**Comment by dkfiresky** [comment]
@Dexwell I believe that it's better to try to find a module that implements your functionality than asking a community to develop such, when it will not be possible to use the implementation for published to App Store apps.
