### ISSUE TITLE
No icon on window.open()

### ISSUE THREAD

**Issue by linux-man** [electron/electron#8982]
System: Linux Mint 18.1
Electron: 1.6.2
I can't define a icon of a windows created with javascript window.open() command inside a webview.
\<link rel="shortcut icon" href="favicon.png" /\> has no effect.
The window shows the ugly "no icon" icon at the windows list.

![icon](https://cloud.githubusercontent.com/assets/1733538/24199717/9cb827de-0f02-11e7-8668-94ccf19a592f.png)

**Comment by Surya-06** [comment]
Cross check the location of the icon it may be in some other directory and the path may not be given correctly. It is mostly due to this that the icon is not showing up. If possible add the line of the code where this error is occurring.

**Comment by linux-man** [comment]
The location is correct (it can open as an image).
There are no errors.
I was hopping that "shortcut icon" could do the trick, but no browser uses the page icon as app icon. That's what I need, and since Electron on Linux don't have an app icon definition, I guess the only way is to define the icon on "new BrowserWindow", but there are times when it's not possible.
Like this one.

**Comment by enlight** [comment]
@linux-man You can override the default attributes of the window created by `window.open` by subscribing to the [`window-open` event](https://electron.atom.io/docs/api/web-contents/#event-new-window) and creating a `BrowserWindow` manually.

**Comment by linux-man** [comment]
@enlight Very useful information, I'll probably use it one day.
Doesn't work with popups from webview. If I create a window on webview new-window event I don't have connection to webview.
I'll leave the problem for now.

**Comment by kevinsawicki** [comment]
> Doesn't work with popups from webview. 

You can use the `browser-window-created` event to get notified of all windows opened from anywhere.

https://electron.atom.io/docs/api/app/#event-browser-window-created

Closing this out.

**Comment by linux-man** [comment]
Another useful link, but there is currently no API to change window icon dynamically, so my problem remains.

**Comment by kevinsawicki** [comment]
@linux-man is `BrowserWindow.setIcon` not working for you? https://electron.atom.io/docs/api/browser-window/#winseticonicon-windows-linux

**Comment by linux-man** [comment]
I guess I was confusing App icon and Window icon, or setIcon is a recent function, or I didn't noticed it.  :blush: :blush: :blush: 
Gonna try that.
