### ISSUE TITLE
autoupdate semver version error when checking for updates

### ISSUE THREAD

**Issue by tjoye20** [electron/electron#8985]

**Comment by timfish** [comment]
Firstly `electron-updater` is not part of this repository. It is located at [electron-userland/electron-builder](https://github.com/electron-userland/electron-builder)

This is also not a bug, it's a support question. Ask support questions in the [Discuss](https://discuss.atom.io/c/electron) forum or the [Slack](http://atom-slack.herokuapp.com/) channel.

**Comment by tjoye20** [comment]
Oops, sorry. Thank you.
