### ISSUE TITLE
https support for crashReporter

### ISSUE THREAD

**Issue by snene** [electron/electron#8986]
* Electron version: 1.3.2 and 1.4.15
* Operating system: MacOS El Capitan 10.11.16

Does Electron's crashReporter support submitURL starting with https? I am successfully able to user crashReporter with http url. But when I try https it fails? Is this known? Is there any workaround?

This is not working:
  crashReporter.start({productName: 'QuickBooks',
    companyName: 'Intuit',
    submitURL: 'https://localhost:1127/post',
    autoSumbit: true,
    uploadToServer: true});
};

**Comment by MarshallOfSound** [comment]
The crash reporter works with HTTPS URLs.  From the looks of that URL you won't have a valid SSL cert for localhost.  This means the requests will fail as the SSL cert isn't valid.

Try a domain with a valid SSL cert and it will work 👍

**Comment by snene** [comment]
Oh yes, that's what must be happening! Thanks a lot!
