### ISSUE TITLE
WebRtc audio input level 

### ISSUE THREAD

**Issue by bil88** [electron/electron#8991]
* Electron version: 1.6.1
* Operating system: Win 10

### Expected Behavior

Currently webrtc once we look at the audio stages of the audio imptu level should always have a numbering since if we see through the browser the api of chrome: // webrtc-internals / lo devuleve.

### Real Behavior

It only sends 0, so that the statistics are not coming, in the previous versions they arrived without problem

### How to play

Creating a webrtc system with calls when calling from one end to the other and picking up can observe this behavior.
Once we analyze the statistics we will see the error.

**Comment by bil88** [comment]
logs: 

ERROR:audio_send_stream.cc(90)] Failed to set up send codec state.
ERROR:stunport.cc(89)

**Comment by deepak1556** [comment]
Can you provide a minimal example to reproduce the issue, its unclear from the description. Thanks!

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by BlueAirRL** [comment]
same question: Sometimes windows pc audioInputLevel=1, It lasts for a while and doesn't recover.
