### ISSUE TITLE
[WIN10] -webkit-app-region: drag; suppresses all other js events.

### ISSUE THREAD

**Issue by rcosnita** [electron/electron#8992]
* Electron version: 1.5.0
* Operating system: Windows 10 - Red Stone (14393.953)

### Expected behavior

The user must be able to click on the inner button and must see the alert message. This works on Mac.

### Actual behavior

Because of the frameless window combined with the style, all js events targetting the inner button are suppressed.

### How to reproduce

Create a new frameless window. Inside it, place a div with style "-webkit-app-region: drag;"
Inside the div, place a button and add onclick="alert(1);".

**Comment by dkfiresky** [comment]
Does it work when you add `-webkit-app-region: no-drag;` on a button?

**Comment by rcosnita** [comment]
Sorry for not mentioning it: indeed I ended up adding -webkit-app-region: no-drag; style on the nested button.

I've just seen a note in the https://github.com/electron/electron/blob/master/docs/api/frameless-window.md page.

Thank you so much for the quick reply.
