### ISSUE TITLE
Upgrade to Chrome 57

### ISSUE THREAD

**Issue by httpdigest** [electron/electron#8993]
Are there any current plans to upgrade Electron to Chromium 57?
Currently, we are already using the CSS Grid layout, introduced with Chrome 57, to build form-based dialogs and would like to deploy that as a standalone desktop application with Electron.

Thanks!

**Comment by MarshallOfSound** [comment]
Please our FAQ re when we try update to Chrome versions

https://github.com/electron/electron/blob/master/docs/faq.md#when-will-electron-upgrade-to-latest-chrome

**Comment by jsnar** [comment]
The FAQ said one or two weeks. but it's more than two weeks now since Chrome 57 was released on Mar 9th: https://chromereleases.googleblog.com/2017/03/stable-channel-update-for-desktop.html

Is there anything wrong with the Electron development?

**Comment by jsnar** [comment]
This issue should remain open until an Electron version based on Chrome 57 is released.

**Comment by MarshallOfSound** [comment]
@jsnar The FAQ also says

> This estimate is not guaranteed and depends on the amount of work involved with upgrading.

**Comment by httpdigest** [comment]
Are there any issues related to the update to Chromium 57 that we could track and see the progress?
Just closing this issue with the response: "See the FAQ", and the FAQ basically saying nothing, because nothing is guaranteed, is not really helping.

**Comment by jsnar** [comment]
@httpdigest I don't think the Electron team has any plan on it currently. But at least this issue should be kept open to track it. CC @kevinsawicki

**Comment by kevinsawicki** [comment]
> Are there any issues related to the update to Chromium 57 that we could track and see the progress?

There has been some initial work done on this via https://github.com/electron/libchromiumcontent/pull/276

**Comment by zcbenz** [comment]
How does everyone think of skipping 57 and upgrading to 58 instead? The Chrome 58 is only about 4 weeks to be stable.

**Comment by bbondy** [comment]
If it helps speed it up, we've done upgrades to C57 and C58 beta already
https://github.com/brave/muon/tree/chromium57
https://github.com/brave/muon/tree/chromium58

I assume a lot can be cherry-picked.

Could I ask when something > C53 will be an official release instead of pre-release? Or is everyone just running off of pre-releases these days?

**Comment by jsnar** [comment]
At least the FAQ document should be fixed. It creates incorrect exceptions. It should reflect the fact that Electron skips Chromium releases and delay longer than 2 weeks.

**Comment by frankhale** [comment]
@jsnar to piggyback off of fixing the FAQ the Node section should also be updated. 

> When a new version of Node.js gets released, we usually wait for about a month before upgrading the one in Electron. So we can avoid getting affected by bugs introduced in new Node.js versions, which happens very often.

Node 7.4 was released in January and we are a long way from a one month upgrade. This has happened in the past as well. It would be extremely nice to have a one month turn around but this just hasn't been the case.

**Comment by kevinsawicki** [comment]
> Could I ask when something > C53 will be an official release instead of pre-release?

Electron 1.6.2 is an official release against Chrome 56.

**Comment by cifratila** [comment]
@zcbenz I would go for upgrading directly to Chromium 58 and skip the 57 one.

**Comment by bbondy** [comment]
> Electron 1.6.2 is an official release against Chrome 56.

I see thanks, I was confused by this Latest Release tag (because it was published after the 1.6.2 one):

<img width="440" alt="screenshot 2017-03-30 19 26 36" src="https://cloud.githubusercontent.com/assets/831718/24530267/df40de98-157e-11e7-8e6e-9b275eba29cb.png">

**Comment by sedwards2009** [comment]
> Electron 1.6.2 is an official release against Chrome 56.

I had a look at the releases page the other day and saw 1.6.2 without a beta tag. It was in the middle of a sequence of 1.6.x betas, and I just assumed that someone had forgotten to mark 1.6.2 as being a beta too.

In other words, the new stable release was not communicated very well. (But I'm still happy to hear that there is a stable release!)

**Comment by enlight** [comment]
@sedwards2009 The latest stable release can be found on the front page of https://electron.atom.io/

**Comment by rreimann** [comment]
Is there a reason why [chromium_src](https://github.com/electron/electron/tree/master/chromium_src)  utilises duplicated/modified sources to adapt chromium code instead of using patches like libcromiumcontent does?

I'm asking because while working on #9044 i noticed several deviations between the original sources for [Chromium 56.0.2924.87](https://chromium.googlesource.com/chromium/src.git/+/56.0.2924.87/chrome/browser/printing/) and the corresponding Electron `chromium_src` that don't seem to be necessary/intentional but just have evolved over time. Wouldn't it be less tedious or at least less error prone to upgrade if the intended deviations would be maintained as patches instead?

**Comment by teleclimber** [comment]
@zcbenz I would love to get an upgrade to Chrome 57 because of CSS Grid. Grid makes creating UIs so much easier. I have been holding off writing features because I want to write their UI with Grid.

Just my 0.02. Thanks.

**Comment by Ted-Mohamed** [comment]
@teleclimber you don't need to hold off your development, you can use CSS Grids right now just make sure to turn on  `experimentalFeatures`

```javascript
win = new BrowserWindow({ 
  width: 800,
  height: 600,
  webPreferences: {
     experimentalFeatures: true
  }
})
```

**Comment by teleclimber** [comment]
@Ted-Mohamed thank-you, that resolves my immediate issue.

Having said that I do hope Electron returns to tracking Chromium releases as closely as can be done given resource constraints.

**Comment by Brahmasmi** [comment]
@zcbenz, Chrome 58 seems to have landed. We may want to upgrade electron's dependency. Thanks.

**Comment by setpixel** [comment]
I saw the 1.7 / chrome 58 build passes! congrats! pre-release soon? :D

**Comment by janklosowski** [comment]
Any updates on upgrading to Chrome 58?

**Comment by janklosowski** [comment]
Any updates on upgrading to Chrome 58?

**Comment by vossad01** [comment]
@janklosowski It is available: https://github.com/electron/electron/releases/tag/v1.7.0
