### ISSUE TITLE
child processes in electron

### ISSUE THREAD

**Issue by caperavensoftware** [electron/electron#8997]
electron 1.6.2
npm 4.1.2

I am running npm commands in a electron app using child processes.

```
const exec = require('child_process').exec;

return new Promise((resolve, reject) => {
    const ls = exec(task.command, {
        cwd: this.path
    }, (error, stdout, stderr) => {
        if (error) {
            reject(error);
        }

        console.log(stdout);
    });

    ls.on('close', _ => {
        console.log(`done with: ${task.description}`);
        resolve();
    });
});
```

the command I am running is 
```
npm init -y
```

When running the app using .electron from webstorm it works fine, no problem.

I build a application for all platforms.
Running the built application on windows works with out any issues.
When running it on mac though I get a error that the command is not a valid command.

```
says that npm: command not found.
```

when I run the same command on the same folder using the terminal it works fine.

Why would this child process not work on mac after being packaged? 

The package command I am using is:
```
"package": "electron-packager ./ WebProjectAssist --all --out ~/Desktop/WebProjectAssist --electron-version 1.6.2 --overwrite --x64"
```

**Comment by caperavensoftware** [comment]
out of interest, if I run electron and drag the folder into the app and run it i get the same issue

**Comment by dkfiresky** [comment]
@caperavensoftware I think you need to run your command out of the shell, so specifying the `env` option and setting the `PATH` within your exec call should fix the problem.

Example:
```
exec('command', {
   env: { PATH: '/usr/local/bin/' }
}, (error, stdout, stderr) => {});
```

**Comment by caperavensoftware** [comment]
i tried that, but it does not help.
the path /usr/local/bin is in my environment variables so i can run npm commands anywhere in terminal and in other node projects. it only gives a issue when packaging the electron app.

**Comment by webarchymeta** [comment]
I had the same issue in our remote build scripts for MacOS, which behave differently from linux based systems. The way we solve it is prepend `export PATH=/usr/local/bin &&` to the command to be run (`npm init -y` here). This will guarantee the path will be available not only to the command but also to the sub-commands contained inside of it ...

**Comment by MarshallOfSound** [comment]
@caperavensoftware The issue is GUI apps on macOS don't inherit environment variables when packaged / distributed / not run from Terminal.

There is a module that fixes this for you however

https://www.npmjs.com/package/fix-path

**Comment by caperavensoftware** [comment]
aaah ty

**Comment by Nashorn** [comment]
> @caperavensoftware The issue is GUI apps on macOS don't inherit environment variables when packaged / distributed / not run from Terminal.
> 
> There is a module that fixes this for you however
> 
> https://www.npmjs.com/package/fix-path

Down to an hour before official release and realized spawn not working. Fix-path npm saved me, thank you 👍

**Comment by Sectaur** [comment]
Same problem with Windows build :(
