### ISSUE TITLE
Support menuDidClose/menuWillOpen

### ISSUE THREAD

**Issue by smith-kyle** [electron/electron#8999]
* Electron version: 1.6.2
* Operating system: macOS

### Expected behavior
Allow users to register a callback for menu open and close events.
```javascript
const menu = new Menu()

menu.onOpen(() => { /* Do something when the menu opens */ })
menu.onClose(() => { /* Do something when the menu closes */ })
```

### Actual behavior

Not supported

NSMenuDelegate exposes these events: https://developer.apple.com/reference/appkit/nsmenudelegate

Not sure about Windows or Linux

**Comment by shubham2892** [comment]
`MenuWillOpen` and `MenuDidClose` events are already implemented [here](https://github.com/electron/electron/blob/master/atom/browser/ui/cocoa/atom_menu_controller.mm#L273), I wonder why they are not documented. 🤔

**Comment by codebytere** [comment]
i'll try to get to this this week

**Comment by codebytere** [comment]
@shubham2892 @smith-kyle PR is in flight, will be merged pending review
