### ISSUE TITLE
Some area have incorrect background color while use a external monitor in macOS

### ISSUE THREAD

**Issue by foisonocean** [electron/electron#9000]
This issue only happens when use a external monitor, use build in monitor is okay.

Both `Atom` and `VS Code` have this issue, so I guess this is cause by `electron`.

![2017-03-24 10_30_45](https://cloud.githubusercontent.com/assets/15059605/24278411/a3e584b6-107e-11e7-9c84-8f39420b2d91.gif)
![2017-03-24 10_53_14](https://cloud.githubusercontent.com/assets/15059605/24278670/21d67c26-1080-11e7-8b94-8ecc0622354d.gif)

* Operating system: macOS 10.12.3
* Atom version: 1.15.0
* VS Code version: 1.10.2

**Comment by bpasero** [comment]
This is https://github.com/electron/electron/issues/7304

**Comment by kevinsawicki** [comment]
Merging into #7304
