### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by nutakukimochi** [electron/electron#9003]
Hello Guys,

I'm having this annoying error

I'm building an electron application that includes an iframe
inside the iframe there is a javascript call which produces this error

Failed to execute 'postMessage' on 'DOMWindow': The target (iframe url ) Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://www.xyz.net') does not match the recipient window's origin ('file://').

The setup is the following 
node v6.9.2
npm 4.0.5
electron: 1.4.15
electron-builder: 12.2.2

Code (tried different combinations to make this work but nothing happened, I'm including all the options i tried)

mainWindow = new BrowserWindow({
    show: false,
    width: 1280,
    height: 850,
    frame: false,
    nodeIntegration: false,
    webFrame :{
      registerURLSchemeAsSecure:'file://',
      registerURLSchemeAsBypassingCSP: 'file://',
      registerURLSchemeAsPrivileged : 'file://'
    },
    webPreferences: {
        webSecurity :false,
        allowRunningInsecureContent : true,
        allowDisplayingInsecureContent: true,
        plugins: true
        }
  });

  mainWindow.loadURL(`file://${__dirname}/app.html`);

any idea how we can fix this 

Thank you

**Comment by kevinsawicki** [comment]
@nutakukimochi are you able to provide a small app that reproduces this issue? That would make it easier to investigate and help troubleshoot, thanks.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
