### ISSUE TITLE
shell.openItem doesn't work after sandboxing the app

### ISSUE THREAD

**Issue by alexey-sh** [electron/electron#9005]
shell.openItem(require('path').join(__dirname, src));
where src is something like "../pics/main.jpg"
the pics folder is placed in Resources 

* Electron version: 1.1.3
* Operating system: mac os 10.12.3

### Expected behavior

Open in default app

### Actual behavior

Absolutely nothing

### How to reproduce
Just sign app for mac os app store

**Comment by njbmartin** [comment]
So I can confirm I've run into the same issue now that my app has been rejected many times for the same reason. Finally stumbled on this workaround @kevinsawicki used for the demo available in the App Store: https://github.com/electron/electron-api-demos/pull/232

Will update with confirmation if this workaround gets me past review.

**Comment by njbmartin** [comment]
@kevinsawicki Perhaps this could be added to the MAS docs under **known issues** until a fix is found?

**Comment by kevinsawicki** [comment]
> Perhaps this could be added to the MAS docs under known issues until a fix is found?

Yeah, sounds good 👍 Want to take a pass at adding it?

**Comment by njbmartin** [comment]
Looking through the electron code for openItem, it appears to be using an AppleEvent which isn't supported by the sandbox. https://github.com/electron/electron/blob/f5a75c4e87a73a802c41e9fb3608e10772dbe600/atom/common/platform_util_mac.mm#L127

Reference: https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/AppSandboxTemporaryExceptionEntitlements.html#//apple_ref/doc/uid/TP40011195-CH5-SW3

If we are confident in `openExternal`, perhaps we should move away from Apple Events and update `openItem` to build the protocol url from the path?

**Comment by njbmartin** [comment]
Can confirm that `openExternal` was not rejected 🎉

**Comment by codebytere** [comment]
...turns out i fixed this a while ago in https://github.com/electron/electron/pull/10552 and forgot
