### ISSUE TITLE
Do electron support RTMP now?

### ISSUE THREAD

**Issue by stellar2016** [electron/electron#9013]
My PC environment
System: Win 7
Electron: 1.4.3
Node.js: 6.7.0
Flash: pepflashplayer64_25_0_0_127.dll

It surely caused by flash. After load flash plugin, simply flash works well, but streaming media using RTMP does't work, It seems the .swf has no permissions.
I have also tried this:
https://github.com/szwacz/nw-flash-trust
But still not work, it may be because I'm using an internet .swf file, rather than the one on my computer, this really confuse me.

ps: relation issue: https://github.com/electron/electron/issues/7727

**Comment by zcbenz** [comment]
Does it work in 1.7.x?

**Comment by codebytere** [comment]
Closing due to abandonment.

**Comment by 18124772589** [comment]
I have encountered the same problem. Do you have any solution?

**Comment by manman0512** [comment]
> I have encountered the same problem. Do you have any solution?

Do you have any solution?
