### ISSUE TITLE
Multi-tags

### ISSUE THREAD

**Issue by tkggusraqk** [electron/electron#9016]
When can I support multiple tags?

**Comment by MarshallOfSound** [comment]
@tkggusraqk I don't quite understand your issue, what do you mean by "multi-label" and "tags" in terms of Electron?

**Comment by tkggusraqk** [comment]
@MarshallOfSound I'm sorry, wrong。Multi-tag is the same as the chrome browser。

**Comment by MarshallOfSound** [comment]
@tkggusraqk Maybe I'm missing something but I still don't get what you mean by multi-tag 😆 Can you link to the docs or maybe give an example of what you are referring to

**Comment by tkggusraqk** [comment]
@MarshallOfSound http://chuantu.biz/t5/52/1490439753x2890171413.png，Is this effect。

**Comment by sbruchmann** [comment]
@tkggusraqk These are called **tabs** and are implemented in HTML, CSS and JavaScript. See [chrome-tabs](https://github.com/adamschwartz/chrome-tabs).

**Comment by MarshallOfSound** [comment]
As @sbruchmann said these are tabs and are a browser concept not an Electron concept, the linked module will give you a good start at implementing a UI similar to this 👍

**Comment by tkggusraqk** [comment]
@MarshallOfSound @sbruchmann Thank you, it is so. But this requires webview, and I want to use the browserwindow.

**Comment by MarshallOfSound** [comment]
@tkggusraqk A browser window is literally a window, you can't use it to make tabs.  WebView's have exactly the same API's as a browser window's web contents but they can be placed inside an existing browser window 👍

**Comment by tkggusraqk** [comment]
@MarshallOfSound thank you,But webview has a lot of bugs, so I wanted to use browserwindower。
