### ISSUE TITLE
No support for Overlay icon for Tray [Linux]

### ISSUE THREAD

**Issue by Lplenka** [electron/electron#9020]
* Electron version: 1.4.15
* Operating system:Linux Mint 18.1

For Mac OS
Electron provides `setBadgeIcon()`
For Windows
It provides `win.setOverlayIcon()`

I am working on a chat application and want an overlay icon in Tray icon to show the unread count but couldn't find any support for overlay Icon in Linux Environment.

**Comment by Lplenka** [comment]
@zcbenz  @paulcbetts   @kevinsawicki  I couldn't found any information about this in Electron docs

**Comment by kevinsawicki** [comment]
@Lplenka would `app.setBadgeCount` work for you?

https://electron.atom.io/docs/api/app/#appsetbadgecountcount-linux-macos

**Comment by Lplenka** [comment]
@kevinsawicki  Thanks! for responding.
Sorry but `app.stBadgeCount` doesn't work. It has been mentioned in the docs that it requires `Unity Launcher` which I don't have.

**Comment by zcbenz** [comment]
The only solution is to dynamically generate an image with badge count, and then set it as tray icon. That's how other apps do since the native API does not provide this ability.
