### ISSUE TITLE
webkitSpeechRecognition

### ISSUE THREAD

**Issue by ccj242** [electron/electron#9022]
I would deeply appreciate any advice on this --  I’ve attached an electron project - super simple, one button, it should activate speech recognition but alas, it does not. If you run index.html independently or on a local server, it works just fine, but somehow I’m getting an error:”network”…. Since it’s being compiled using chromium I was hoping it would work, and indeed it does seem to support webkitSpeechRecognition... any ideas? Thank you so much!
[STT_Test_WebSpeechAPI.zip](https://github.com/electron/electron/files/871182/STT_Test_WebSpeechAPI.zip)

**Comment by zcbenz** [comment]
It is possible that we have exceeded the quota of Google API calls, you can try setting a custom Google API key:
https://github.com/electron/electron/blob/master/docs/api/environment-variables.md#google_api_key
