### ISSUE TITLE
[BUG] Rendering bug kernel freezes Electron App on Raspberry Pi

### ISSUE THREAD

**Issue by AndreaSpan** [electron/electron#9026]
Hi everyone, 

I'm actually building an Electron application running on Raspberry Pi 2 and I'm facing a big problem. 

My Electron version is 1.3.14 

The application is a main window that instantiate a new window to show something and then close it to come back to the main window. 

The app is working most of the time for 5 to 15 days without problems and then randomly the app freezes and all the os is frozen too.

My application logging system doesn't throw any software error but I found some Error log in the system log: 

Here here the part of the log with the errors. We can see a first error is related to the **CompositorTileW** process. 
[syslog.txt](https://github.com/electron/electron/files/871964/syslog.txt)

Does it speak to someone? Any track to look out?
I'm not able to reproduce the bug and I need to if I want to be able to solve it asap. If you have any idea to hard test the system, please feel free to tell me.

Thank you!

**Comment by kevinsawicki** [comment]
> My Electron version is 1.3.14

Are you able to try a newer version, like 1.6.2, to see if you still experience the issue?

**Comment by AndreaSpan** [comment]
I'm currently trying with the 1.6.2 version, I'll let you know if the bug occurs again.

**Comment by zcbenz** [comment]
Closing since it seems to work fine now.
