### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by ghost** [electron/electron#903]
I think Atom Shell has no i18n/l10n API. It would be nice Atom Shell would have this API, so you could translate Atom editor and any other Atom Shell based application into another languages.
Thank you for Atom Shell.
Related to: [https://github.com/atom/atom/issues/4441]

**Comment by black-snow** [comment]
@zcbenz I see a directory called *locales* with many 0 KB `*.pak` files but I can't find any docs on localization in electron. Is there still no built-in l18n? What's the *locales* folder for then?
