### ISSUE TITLE
Support searching in native PDF rendering

### ISSUE THREAD

**Issue by rreimann** [electron/electron#9030]
Electron 1.6.4 beta added support for native PDF rendering #8435

It would be nice if the native PDF viewer would support text searches via `CmdOrCtrl+F` keyboard shortcut like it does in Chromium.

**Comment by rreimann** [comment]
@deepak1556 is there a way to disable or suppress the native plugin? 

I need to stick to PDF.js as long as advanced features like searching an printing are not supported by the plugin but triggering PDF.js via `will-download` handler doesn't work anymore since the plugin is on by default and seems to prevent `will-download` events from being fired.

**Comment by deepak1556** [comment]
> is there a way to disable or suppress the native plugin?

There is no way to disable the plugin, but you can workaround it either by using iframes to display the pdf resource where `will-download` event will fire or you can intercept `chrome` protocol and render with pdf.js

**Comment by rreimann** [comment]
Thanks for the suggestions but i had no luck in applying them in my scenario. Can you think of a workaround that works where the PDF should render in a new `BrowserWindow` while the contents of the main `BrowserWindow` keeps intact?

- i can't introduce iframes for all the places in the application that might contain links to a PDF document. 
- i tried to cancel requests to `chrome://pdf-viewer/index.html...` in `onBeforeRequest` but that seems to be to late in the game to preserve the main window. I can open a new window that renders fine with pdf.js but the content of the main window vanishes.
- i don't see a method in [protocol](https://electron.atom.io/docs/api/protocol/) that would let me intercept the `chrome` scheme in a way that i could render the PDF in a new window instead of just redirecting the existing main window.

**Comment by deepak1556** [comment]
> Can you think of a workaround that works where the PDF should render in a new BrowserWindow while the contents of the main BrowserWindow keeps intact?

Its not possible with the current implementation. https://github.com/electron/electron/issues/9412 should provide a way for your scenario.

**Comment by codebytere** [comment]
This appears to have been made possible by https://github.com/electron/electron/pull/9507, so i'm going to go ahead and close this.

**Comment by rreimann** [comment]
@codebytere could you please reopen the issue? #9507 does not address the missing search support in any way.

**Comment by JonMarbach** [comment]
Electron's native PDF support is pretty sweet! But searching in a PDF is really fundamental to the PDF experience... What would it take to get this added?

**Comment by thibaultmol** [comment]
Now that [Obsidian](https://obsidian.md/) has implemented proper PDF embedding in their notes, the main thing that's missing is still this issue of being able to search in pdfs. This a very critical part!

**Comment by rushikb** [comment]
Hardest possible plus one to @thibaultmol 's point— Being able to search for PDF's will basically win you the swarm of people currently trying to escape the all consuming disaster that is evernote 10

**Comment by tobiasbueschel** [comment]
> Now that [Obsidian](https://obsidian.md/) has implemented proper PDF embedding in their notes, the main thing that's missing is still this issue of being able to search in pdfs. This a very critical part!

Absolutely, this would be a game-changer for my personal knowledge management if I could search through all my PDFs directly from within an Obsidian vault!

Has anyone already looked into building this? Would be keen to contribute!

**Comment by BluBloos** [comment]
+1 on having search functionality in PDFs within the Electron PDF viewer

**Comment by thezanderlv** [comment]
Being able to have all your pdf's indexed and searchable will make this app 200x more powerful

**Comment by waltermelow** [comment]
+1 support PDF search

**Comment by nornagon** [comment]
Seems to work fine with [webContents.findInPage](https://www.electronjs.org/docs/latest/api/web-contents#contentsfindinpagetext-options). We don't implement a Cmd+F-style dialog in Chromium, that's up to apps to build.

![Screen Shot 2022-10-31 at 4 58 25 PM](https://user-images.githubusercontent.com/172800/199131053-be93ac7c-fbd6-4893-be87-aafe2ea74444.png)

**Comment by leonheess** [comment]
@nornagon 

>  We don't implement a Cmd+F-style dialog in Chromium

what? That functionality is already part of Chromium. Electron is actively disabling it after not doing that in the past.

**Comment by nornagon** [comment]
@leonheess that is untrue. Electron wraps a subset of Chromium, and the Cmd+F dialog is not part of that subset, and never has been.

**Comment by TylerIllman** [comment]
+1 for this idea
