### ISSUE TITLE
Electron fails to display web pages where d3 zooming is involved

### ISSUE THREAD

**Issue by alebo611** [electron/electron#9032]
* Electron version: 1.4.15
* Operating system: Windows 7, Linux Debian Jessie

### Expected behavior

Electron should be able to show all kind web pages using d3.

### Actual behavior

While working with the well known d3 javascript library, I discovered that Electron often has problem to render the pages. 
For example, when opening d3zoom.html (attached here inside d3zoom.zip), electron just shows a blank page. A normal chrome, explorer and also nw.js all display the page correctly.
### How to reproduce
Open d3zoom.html in electron.
[d3zoom.zip](https://github.com/electron/electron/files/872706/d3zoom.zip)

**Comment by renambot-uic** [comment]
By default Electron enables Nodejs integration which provides 'require' and can conflict with libraries.

Either:
  - disable Nodejs integration in your ap. You need to create a js file with something like:
    new BrowserWindow({webPreferences: { nodeIntegration: false }});

 - or load d3 with 'require':
      npm install d3@3
     and put 'var d3 = require("d3");' at the top of your script tag and remove the script tag loading d3.

Luc

**Comment by kevinsawicki** [comment]
Thanks @renambot-uic for the tips, closing this out.
