### ISSUE TITLE
Going fullscreen doesn't update browserWindow fullscreen API

### ISSUE THREAD

**Issue by nt1m** [electron/electron#9036]
* Electron version: 1.6.2
* Operating system: macOS sierra

### Expected behavior
- Fullscreen API methods should be in sync with actual fullscreen state
https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

### Actual behavior
- They are not in sync

### How to reproduce

  $ git clone https://github.com/nt1m/media-player
  $ npm install
  $ npm start

Click app fullscreen button
Click native fullscreen button to quit fullscreen

Fullscreen API not in sync with actual fullscreen state.

Note that I do not want to use browserWindow.isFullscreen(), because I want my app to be web compatible

**Comment by zcbenz** [comment]
The native fullscreen state of window is independent from the HTML5 fullscreen state, binding the two states together would cause problems when there are multiple WebContents inside one window. So I'm closing this as won't fix.

In your case you can override the behavior of HTML5 fullscreen with `preload` scripts.
