### ISSUE TITLE
Global Shortcuts

### ISSUE THREAD

**Issue by usernamevalis** [electron/electron#9038]
Hi hi

I know this isn't technically the correct place but im not sure where else to ask this.

when setting up global shortcuts, is it possible to allow the key presses to be sent to what ever application you are busy with when you press them?

e.g. when i press a key combo whilst my electron app is in the background and i am busy in a text editor, those key presses register with my electron app - as per the global shortcut- but they don't register with the text editor.

Is there a way to register this global shortcut whilst still allowing the key presses to pass through to what app you are busy with?

thank you

* Electron version:
* Operating system:

**Comment by kevinsawicki** [comment]
> Is there a way to register this global shortcut whilst still allowing the key presses to pass through to what app you are busy with?

I don't think this is possible with the `globalShortcut` module, Electron registers and gets notified when the event happens but it cannot control if the key event still goes to the active application or not.

Closing this out.
