### ISSUE TITLE
Electron + leaflet on vpn

### ISSUE THREAD

**Issue by ckristhoff** [electron/electron#9040]
Hi,
Mi application should run on a VPN, the vpn has a company proxy. When the application tries to get an resource (map) from google it does not load, I get 407 (authenticationrequired) error.

* Electron version: *
* Operating system: Windows 10, Windows 7

### Expected behavior

Show online leflet map from Google Maps.

### Actual behavior

Get 407 error (authenticationrequired)

**Comment by ckristhoff** [comment]
I had tried this https://github.com/electron/electron/issues/4858 but not works for me

**Comment by ckristhoff** [comment]
Anyone know how to show popup when authentication for proxy is required? :(
Or how can the app get data from browser configuration?

**Comment by deepak1556** [comment]
> I had tried this #4858 but not works for me

Can you elaborate ? How are you using the login event of app module ?

> Anyone know how to show popup when authentication for proxy is required? 

Electron does not implement the UI for accepting login credentials, its upto the users to implement if required based on the login event of app module.

**Comment by ckristhoff** [comment]
> Can you elaborate ? How are you using the login event of app module ?

yep, I put the next code in my main.js
`function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow({icon: 'img/icon.ico', width: 1024, height: 768 , maximizable : true, minWidth : 1024 , minHeight : 768,  title : 'My App'})  

  // and load the index.html of the app.
  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'www/index.html'),
    protocol: 'file:',
    slashes: true
  }))
mainWindow.webContents.session.setProxy({
                proxyRules: this.proxyUrl,
                pacScript: undefined,
                proxyBypassRules: 'localhost' // localhost? or proxy ip?
            }, () => {
                this.browser.loadURL(url);
            });
private onLogin(event: Event,
            request: Electron.LoginRequest,
            authInfo: Electron.LoginAuthInfo,
            callback: (username: string, password: string) => void): void {
                callback(agentUsername, this.proxyPassword); // my proxy credentials?
                event.preventDefault();
        }
`
at end of main.js I put
`app.on('login', (event, webContents, request, authInfo, callback) => {
  event.preventDefault()
})`

**Comment by deepak1556** [comment]
@ckristhoff the sample code is bit unclear, can you provide a minimal app to reproduce the issue ? Thanks!

**Comment by ckristhoff** [comment]
Hi, there is a repo with demo project
https://github.com/ckristhoff/demo-electron-leaflet
On vpn with proxy the image does not load.

**Comment by marwenlandoulsi** [comment]
Hi 
@ckristhoff did you fined any solution because i have the same issue

**Comment by ckristhoff** [comment]
hi @marwenlandoulsi I don't have solution actually. Just download your map tiles to local storage and configure the path.

**Comment by zcbenz** [comment]
Copying the code snippets does not make your app automatically authenticated proxy... You have to actually pass your username and password.
