### ISSUE TITLE
/usr/local/bin not in path with macOS Sierra

### ISSUE THREAD

**Issue by justechn** [electron/electron#9047]
* Electron version: v.1.4.15
* Operating system: macOS Sierra 10.12.3

### Expected behavior

/usr/local/bin should be in the path

### Actual behavior

/usr/local/bin is not in the path I only see PATH=/usr/bin:/bin:/usr/sbin:/sbin

Do I need to add this manually to the path? This directory seems like it should be included by default.

### How to reproduce

Create an electron app and include these lines
```
const { spawnSync } = require('child_process');
console.log(String(spawnSync('printenv').stdout));
```

**Comment by MarshallOfSound** [comment]
@justechn GUI applications on macOS do not inherit the expected environment from terminal / bash.  They are given a default set of environment variables.

To load in your expected environment PATH variable you should use a module like.

https://www.npmjs.com/package/fix-path
