### ISSUE TITLE
I am getting an error while install electron in my machine (npm install -S electron)

### ISSUE THREAD

**Issue by VPageDevelopment** [electron/electron#9050]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron" "--save-dev"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install electron as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\codepanda\Desktop\electron\ims\npm-debug.log

**Comment by VPageDevelopment** [comment]
I find a solution myself and the real problem is I had a folder called electron and I try to install electron inside an electron folder i.e like this C:\Users\codepanda\Desktop\electron\ims\ .. to overcome this create a folder called electronIms on my desktop and then I install electron successfully... Thanks

**Comment by enlight** [comment]
Closing since the OP has resolved his issue.
