### ISSUE TITLE
Console.log doesn't work in windows 8.1

### ISSUE THREAD

**Issue by Blindkiller12** [electron/electron#9051]
Hello,

When I do a `console.log('Hello');` in my index.js and I start my project with `electron . --enable-logging`. I've set `ELECTRON_ENABLE_LOGGING` but nothing appear in the windows console.

Thank you

Windows version : 8.1
Electron version : 1.6.2
Node version : v6.10.1
NPM version: 3.10.10

**Comment by JonMarbach** [comment]
Same or similar issue to https://github.com/electron/electron/issues/6946 but really annoying (and hurts productivity.) Maybe we can get someone's attention on this...?

**Comment by kevinsawicki** [comment]
Merging into #6946
