### ISSUE TITLE
Install electron fail on ubuntu 14.04

### ISSUE THREAD

**Issue by Cphilo** [electron/electron#9055]
* Electron version: 1.6.2
* Operating system: Ubuntu 14.04.5 LTS
* node verstion: v7.8.0
* pm version: 4.4.0

I install electron fail.

vagrant@vagrant-ubuntu-trusty-64:~$ npm install electron --save-dev

> electron@1.6.2 postinstall /home/vagrant/node_modules/electron
> node install.js

/home/vagrant/node_modules/electron/install.js:46
  throw err
  ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1120:19)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
npm WARN enoent ENOENT: no such file or directory, open '/home/vagrant/package.json'
npm WARN vagrant No description
npm WARN vagrant No repository field.
npm WARN vagrant No README data
npm WARN vagrant No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.6.2 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2017-03-29T16_58_08_575Z-debug.log

**Comment by Cphilo** [comment]
Add the log attachment link: https://gist.github.com/Cphilo/c0404ecef2a991cd5387b2dfefb788d3

**Comment by kevinsawicki** [comment]
> Error: socket hang up

Looks like a (possibly intermittent) connection issue, are you able to download it directly from https://github.com/electron/electron/releases/tag/v1.6.2 and are you still having this issue?

**Comment by kevinsawicki** [comment]
Closing this out since it looks like a local networking issue.
