### ISSUE TITLE
Native Wayland Compatibility 

### ISSUE THREAD

**Issue by dakrawczyk** [electron/electron#9056]
Hello, 

I am wondering if there are plans to introduce Electron with native Wayland compatibility (not x-wayland). Or if it already exists using something like [Chromium's Ozone](https://github.com/01org/ozone-wayland.git)

We are running electron on a samsung module that has hardware GPU acceleration provided by MALI drivers, which supports only wayland, and not X11 or X-Wayland.

**Comment by kevinsawicki** [comment]
> I am wondering if there are plans to introduce Electron with native Wayland compatibility

No formal plans, but any pull requests regarding it would be appreciated and reviewed.

**Comment by zcbenz** [comment]
Electron would get it automatically once Chromium has the support, you only have to wait for Chromium supporting ozone and wayland on Linux desktop.

You can find more about current state of ozone at:
https://chromium.googlesource.com/chromium/src/+/master/docs/ozone_overview.md

Closing since we can do nothing on Electrons's side.

**Comment by bmentink** [comment]
On this issue. Is there any bitbake receipies available for Yocto? I would like to build electron for a custom Yocto port to a Rock64 board which has accelerated graphics for Wayland.
But regardless of the graphics would like to build for x11 as well ..

**Comment by LongChair** [comment]
@bmentink : i'm trying to achieve something similar on wayland & rock64. and i have been facing the following issues :

- libchromiumcontent (in the `update-to-chromium-61` branch) builds chromium with GTK3 support which should be fine on wayland. Although it also references /chrome/browser/ui/libgtkui which has strong bindings on X11 and therefore cannot be built on wayland only.
- using wayland with chrome requires ozone afaik, and libchromiumcontent currently doesnt build with ozone. this can be adjusted in the GN files though.

I am not sure if electron really uses the chromium libgtkui module and what for, so unsure whether it could work without this one. I will try to give it a go but i suppose it's going to be needed.

**Comment by bmentink** [comment]
@LongChair
It seems Yocto for the Rock64 does have a Chromium build for wayland. Here is part of the bitbake receipe:

> DEPENDS += "wayland libxkbcommon"
> 
> SRC_URI += "\
>         file://chromium-wayland/add_missing_stat_h_include.patch \
>         file://0003-pdfium-fix-build-with-gcc7.patch \
>         file://0003-Remove-hard-coded-values-for-CC-and-CXX.patch \
>         file://0004-Create-empty-i18n_process_css_test.html-file-to-avoi.patch \
>         file://0005-Override-root-filesystem-access-restriction.patch \
>         file://chromium-wayland/remove-armv7-a-from-options.patch \
>         file://chromium-wayland/0007-Workaround-for-glib-related-build-error-with-ozone-w.patch \
>         file://chromium-wayland/0011-Replace-readdir_r-with-readdir.patch \
>         file://chromium-wayland/remove-Werror.patch \
>         file://chromium-wayland/guard-x11_desktop_handler-inclusion.patch \
>         file://chromium-wayland/fix-non-x11-build-when-use_xkbcommon-1.patch \
>         ${@bb.utils.contains('PACKAGECONFIG', 'component-build', 'file://component-build.gypi', '$
>         ${@bb.utils.contains('PACKAGECONFIG', 'ignore-lost-context', 'file://chromium-wayland/000$
> "
>

**Comment by LongChair** [comment]
This will build chromium but might not build chromium libgtkui which causes the build issue.
it mainly depends on wether electron really needs that module or not.

https://github.com/electron/libchromiumcontent/blob/master/chromiumcontent/BUILD.gn#L37

**Comment by stalkerg** [comment]
I think you should try use alternative branch https://github.com/Igalia/chromium/tree/ozone-wayland-dev

**Comment by hedgepigdaniel** [comment]
See https://github.com/electron/electron/issues/10915 for more recent progress
