### ISSUE TITLE
Make electron version available in childProcess.fork

### ISSUE THREAD

**Issue by bcomnes** [electron/electron#9058]
* Electron version: 1.6.2
* Operating system: macOS / All

In efforts to solve https://github.com/electron/electron/issues/8727 for `node-pre-gyp`, I need to find out which version of electron called `childProcess.fork` when testing for `process.env.ELECTRON_RUN_AS_NODE` in order to help pick out the correct bindings for `node-pre-gyp`.  

The version of electron doesn't show up in `process.versions` inside of the fork as it does in a normal electron process, and isn't exposed through an environmental VAR.  In my current attempt to fix this problem for `node-pre-gyp` I do a [require('electron/package.json').version and hope for the best](https://github.com/mapbox/node-pre-gyp/pull/279/files#diff-314ae8d53157a25e4458ced25e711105R253), but this seems like this approach could be error prone.

Is the version of electron that called the fork available in the fork somewhere currently and I just missed it?

If not, would it be possible to make it available somewhere?  Maybe by adding it to `process.versions` or set `process.env.ELECTRON_RUN_AS_NODE` to the version number of electron that calls the fork?

EDIT: Related PR https://github.com/mapbox/node-pre-gyp/pull/279

**Comment by kevinsawicki** [comment]
> Is the version of electron that called the fork available in the fork somewhere currently and I just missed it?

It is not

> If not, would it be possible to make it available somewhere? Maybe by adding it to process.versions or set process.env.ELECTRON_RUN_AS_NODE to the version number of electron that calls the fork?

Yeah, should be straight-forward. One concern with setting `process.versions.electron` would be breaking any libraries out there that are assuming a full Electron environment when this is available which wouldn't be the case with forked processes.

The code to expose variables to a forked process is in https://github.com/electron/electron/blob/57edc28b0d26934aba91a903f549188ea3e7c48f/atom/app/node_main.cc#L59

**Comment by bcomnes** [comment]
Would it be better to overload ELECTRON_RUN_AS_NODE with the version number? Or add a new ENV var with the electron version number?

**Comment by bcomnes** [comment]
Looking through the C++ now.  Its a bit over my head.  Any tips or examples of how I might achieve this?

**Comment by VivekBhatt007** [comment]
@kevinsawicki anyone still working on this issue? Looking forward to start contributing with this issue.

**Comment by bcomnes** [comment]
Its been stale for a while.  🤞 someone picks it up

**Comment by VivekBhatt007** [comment]
@bcomnes , Please let me know if you have any reference of similar issue so that i can study that to solve this issue.

**Comment by zhihongsun51** [comment]
Is anyone working on this right now? I'm looking to start contributing.

**Comment by JakeRadMSFT** [comment]
Resolved?

**Comment by bcomnes** [comment]
I believe https://github.com/electron/electron/pull/16450 resolved this, however I have not tested that.  Closing since it looks like this would be resolved.
