### ISSUE TITLE
Compile against v1.6.2 produces linking error

### ISSUE THREAD

**Issue by pmoleri** [electron/electron#9059]
* Electron version: 1.6.2
* Operating system: Windows 10

### Actual behavior

I get this error compiling `electron-edge` against `v1.6.2`
```
utils.obj : error LNK2022: metadata operation failed (8013119F) : A TypeRef exists which should, but does not, have a corresponding TypeDef: (PrivateData): (0x01000021). [C:\Work\repos\test-build\node_modules\electron-edge\build\edge_nativeclr.vcxproj]
```

### Attempt to identify the cause
`utils.cpp` includes `v8.h`, which has a reference to `PrivateData` type, but it seems that iojs.lib doesn't have a definition for it.
`v8.h` file comes from the headers tarball: https://atom.io/download/electron/v1.6.2/iojs-v1.6.2.tar.gz

Replacing that `v8.h` file with the one in `node v7.4.0` solves the problem.

### How to reproduce

1. Create a new project
```bash
npm init
npm install electron@1.6.2 electron-edge@6.5.4
```

2. Edit build file
edit `./node_modules/electron-edge/tools/build.bat`
and update: `--target=1.6.2`

3. Build `electron-edge`
```bash
./node_modules/electron-edge/tools/build.bat release "7.4.0"
```
Note: ignore the `7.4.0` version, this build process is actually using `node-gyp` with `v1.6.2` and electron dist url.

Copy `~\.node-gyp\7.4.0\include\node\v8.h` to `~\.node-gyp\iojs-1.6.2\deps\v8\include` and build again to solve the problem.

**Comment by radencode** [comment]
@pmoleri  I get the error `Uncaught Error: The edge module has not been pre-compiled for node.js version v7.4.0. You must build a custom version of edge.node.` 

How can I fix that?

**Comment by pmoleri** [comment]
You can ignore that. I think it's a post install validation to let you know you should build manually, which is what we want to do.

We could build from source repo, but for repro steps I thought this would be simpler like this, given that the npm package has the necessary pieces to build.

In the end you should get the linking error I posted.

Thanks for looking into this.

**Comment by radencode** [comment]
@pmoleri yeah this may not be related to this issue but how do I use electron-edge with node v7.4.0. That's what I need?

**Comment by pmoleri** [comment]
@radencode , for node use `edge` module, not `electron-edge`. Then [install and configure node-gyp](https://github.com/nodejs/node-gyp) and follow [edge build instructions](https://github.com/tjanczuk/edge#building-on-windows).

Please, let's keep this issue about electron linking problem.

**Comment by radencode** [comment]
@Pmoleri I tried to replicate your issue but I am not getting your error.
Are you still getting it? For me it worked.

**Comment by pmoleri** [comment]
Hi @radencode,
Yesterday I switched my PC to a new one. Now I can't reproduce the issue, I guess something was wrong in my old PC.
Thanks, I'll close the issue now.

**Comment by radencode** [comment]
Hello @pmoleri
Okay I'm glad you fixed and thank you very much for helping me fix my issue
eventhough it wasn't related to yours.
