### ISSUE TITLE
Unexpected Token - Raspberry Pi 3/Raspbian

### ISSUE THREAD

**Issue by SCProductions** [electron/electron#9064]
* Electron version: 1.6.2
* Operating system: Raspbian

### Expected behavior

Electron should start and show it's usual "drag your app/web-page here" window.

### Actual behavior

Electron might start, and then on every attempt after the next reboot, just fails to run with exit code: 1.

On navigating to the binary itself, in node_modules/electron/dists/

And running node electron (because I know no other way to get more output from it), I get:

```
/home/pi/electron/electron:1
(function (exports, require, module, __filename, __dirname) { ^ELF
                                                                                                 ^
SyntaxError: Unexpected token ^
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
```

There is a strange character between: ^ and Elf, on the console, which doesn't appear to copy with the text. What is weird is that, it will work, sometimes, until the next reboot. Running NPM Install for the app I'm working with, appears to just break it across the system.

### How to reproduce

I've only been able to test this on a closed project I can't share, but it happens on every pi I install on. The electron install always breaks. I believe other projects using electron might experience the same issue. I've seen one or two other references to very similar vm.js issues leading to a crash/failure to run.

1. Download an app that uses npm start and electron, on a raspberry pi. Grab a slightly older version.
2. Install the latest node release (not in Raspbian repos, have to get directly)
3. npm install/node start. App probably works, right?
4. Update it, over-write the files you have.
5. npm install to apply any new modules
6. npm start - might crash/fail to run.

I am not sure where the problem is arising. The app I'm working on calls Electron exactly as it says to in the docs... and trying to run electron stand-alone always crashes. 

Googling the vm.js token problem lead me to: https://github.com/gotwarlost/istanbul/issues/777
So I don't know if they're related, but I wanted to provide that reference if it was.

I was able to get electron to run once afterward by  running: node npm_modules/electron/install.js manually, and then on the very next attempt to run electron, it didn't run.

**Comment by kevinsawicki** [comment]
What arguments are you passing Electron when you start it?

This type of error could occur if you started electron with a path to a executable file instead of a JavaScript or HTML file.

**Comment by SCProductions** [comment]
In my case, it doesn’t work when run from a node app or when run without arguments.


node electron


I believe that, usually launches an electron window which says “drag your app/html here.” I can’t even get it to do that. It instead produces the errors I provided before.


In the node app I’m working on, we’re launching with:


```javascript

 var app = electron.app
  // Module to create native browser window.
  var BrowserWindow = electron.BrowserWindow
  var url = require('url')

  // Keep a global reference of the window object, if you don't, the window will
  // be closed automatically when the JavaScript object is garbage collected.
  var mainWindow;

  function createWindow () {

    // Create the browser window.
    mainWindow = new BrowserWindow();


    // and load the index.html of the app.

    if (startMode == 'controls') {
   mainWindow.loadURL('http://localhost:3000/login');

    } else {
   //mainWindow.setFullScreen(true);
   mainWindow.loadURL('http://localhost:3000/video');
    }


    // Emitted when the window is closed.
    mainWindow.on('closed', function () {
      // Dereference the window object, usually you would store windows
      // in an array if your app supports multi windows, this is the time
      // when you should delete the corresponding element.
      mainWindow = null
    })
  }

  // This method will be called when Electron has finished
  // initialization and is ready to create browser windows.
  // Some APIs can only be used after this event occurs.
  app.on('ready', createWindow)

  // Quit when all windows are closed.
  app.on('window-all-closed', function () {
    // On OS X it is common for applications and their menu bar
    // to stay active until the user quits explicitly with Cmd + Q
    if (process.platform !== 'darwin') {
  process.env.NODE_ENV = null;
      app.quit()
    }
  })

  app.on('activate', function () {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (mainWindow === null) {
      createWindow()
    }
  })
}

```


I can usually get Electron to work the first time I set up the app (node install/electron-rebuild), but then not again after that. I usually end up needing to re-image the SD Card, which makes no sense.

**Comment by kevinsawicki** [comment]
> In my case, it doesn’t work when run from a node app or when run without arguments.
> node electron

This is most likely the issue, you should just run `electron`. `node electron` tries to parse the `electron` executable as a JavaScript file which fails with the error you are seeing.

**Comment by SCProductions** [comment]
Ok. What do I have to change in my app to make it work?

In our app, when I do npm start… it fails as well.

**Comment by kevinsawicki** [comment]
> Ok. What do I have to change in my app to make it work?

Run `electron` with the path to your app's main JS file as the first argument, or use  https://github.com/electron-userland/electron-packager to package your app up and then just run the executable it generates.

**Comment by SCProductions** [comment]
That… doesn’t work either. I installed electron globally to make it easier:

Sudo npm install electron -g

Run:
Electron


No output occurs. Not the default output or anything. It just goes to a new line.

**Comment by SCProductions** [comment]
Well, that didn’t work.

Electron, just running the command itself, it won’t run. I did a global install:


Electron

{3-5 seconds passes)

New line. No output.




I ran npm rebuild once, and it worked… and now I’m back to square one.

**Comment by kevinsawicki** [comment]
> (function (exports, require, module, __filename, __dirname) { ^ELF

Closing this out, this looks like an issue where the electron executable was passed to node as a script to run and failed because it wasn't a JavaScript file.

`npm install electron` installs an `electron` command that can be used to launch apps via `electron /path/to/my/app`. You can run `electron -h` for more information.
