### ISSUE TITLE
executeJavaScript does not work in sandbox mode

### ISSUE THREAD

**Issue by aight8** [electron/electron#9073]
* Electron version: 1.6.4
* Operating system: macOS

### Expected behavior

executeJavaScript should return the result in callback or resolve/reject the promise
It works in not-sandbox mode

### Actual behavior

The callback is never called. The returned promise is never resolved

### How to reproduce

In did-finish-load:
```JS
webContents.executeJavaScript('123', false, res => {
   // never called
})
```
or
```JS
const res = await webContents.executeJavaScript('123')
// never resolved
```

Same if the js code is a promise or some other value.

**Comment by codebytere** [comment]
Looks like this is both related to and blocked by https://github.com/electron/electron/issues/6712

**Comment by rhendric** [comment]
Also seeing this on Linux, version 1.8.2.

**Comment by steverandy** [comment]
Is there any update on this? Recently tried with v2.0.0-beta.4 and can confirm `executeJavaScript` still does not work for `<webview>` with sandbox enabled.

**Comment by nornagon** [comment]
Confirmed, this is still happening on 2.0.x. I'll take a look.
