### ISSUE TITLE
Minimize is not a function

### ISSUE THREAD

**Issue by eduardodallmann** [electron/electron#9075]
* Electron version: v1.3.14
* Operating system: windows 10, v1607, build 14393.953

I hid the title bar of the system and created a my title bar.
`frame: false`

The close button works.
` var remote = require( 'electron' ).remote;
 var window = remote.getCurrentWindow();
$( "#bx" ).on( "click", function () {
	window.close();
} );`

But the minimize button does not work.
`$( "#bm" ).on( "click", function () {
	window.minimize();
} );`
Return error "window.minimize is not a function"

### my main.js attached
[main.txt](https://github.com/electron/electron/files/886508/main.txt)

**Comment by kevinsawicki** [comment]
Are you able to provide an example app that reproduces this behavior? I'm unable to reproduce this from the Console tab of the dev tools:

```js
window = require('electron').remote.getCurrentWindow()
window.minimize()
```

**Comment by eduardodallmann** [comment]
Apparently when I changed the name of the 'window' variable everything worked, I think 'window' was a constant somewhere.

Thanks

**Comment by ItsYanko** [comment]
`window` is a constant in HTML / JS, it means the whole window, so it can't be used anywhere else
