### ISSUE TITLE
Not allowed to load local resource in onBeforeRequest redirect

### ISSUE THREAD

**Issue by tejohnso** [electron/electron#9077]
* Electron version: 1.6.2
* Operating system: Linux 4.10.6-1-ARCH

### Expected behavior

onBeforeRequest handler should redirect remote url request to local html file

### Actual behavior

Not allowed to load local resource

### How to reproduce
``` bash
  $ git clone https://github.com/tejohnso/web-request-test
  $ npm install
  $ npm start
```

**Comment by deepak1556** [comment]
This is by design of file protocol in chromium, there is nothing we can do about it. You can workaround by using custom protocols to serve local files and redirect to them.

**Comment by huangzuizui** [comment]
You can try turn off webSecurity in webPreferences to enable it.

**Comment by yangheng** [comment]
@tejohnso  
You can register a custom protocol587 that resolves those URLs the way you want.
I had resloved it as the code below

```javascript

protocol.registerHttpProtocol('dawn', (request, callback)=>{
        request.url = request.url.substr(7)
        // the new url is ='D:\\yunshipei\\dawn\\override\\sgoutong.baidu.com\\main.css'
         callback(request)
     })
session.defaultSession.webRequest.onBeforeRequest(function (details, callback) {

       if (details.url == 'http://www.sawmac.com/stylesheets/styles.css') {
            callback({redirectURL:'dawn://D:\\yunshipei\\dawn\\override\\sgoutong.baidu.com\\main.css'})
        } else {
            callback({ cancel: false })
        }
        
    })
```

**Comment by yangheng** [comment]
I want to learn Englisth !!! Haha

**Comment by zeybar** [comment]
> ```js
> http://www.sawmac.com/stylesheets/styles.css
> ```

this can't work if details.url is from https(https://www.sawmac.com/stylesheets/styles.css) will be blocked.
