### ISSUE TITLE
EPERM Rename Error

### ISSUE THREAD

**Issue by Lplenka** [electron/electron#9081]
Electron version: 1.4.15
Operating system: Windows 10

`const conf = new Configstore('AppName-Desktop')

 	win.on('resize', function () {
		const size = this.getSize();
		conf.set({
			width: size[0],
			height: size[1]
		});
	});

	// on osx it's 'moved'
	win.on('move', function () {
		const pos = this.getPosition();
		conf.set({
			x: pos[0],
			y: pos[1]
		});
	});
`

### Expected behavior

There should not be any other, the config file should be updated seamlessly.

### Actual behavior

Moving or resizing the electron window creates this error
![screenshot 33](https://cloud.githubusercontent.com/assets/13533873/24574529/dc5c7e42-16b1-11e7-82ba-55793baee6f8.png)

I might be doing this wrong, but why is Windows not allowing the electron to change the config file the app created itself?

**Comment by MarshallOfSound** [comment]
This won't be an issue with Electron persay, it could be any number of things stopping the rename occurring.  If any other process has a file lock on that file then it won't be permitted.

The most common causes are AV programs or even your own code attempting to read from the file while attempting to rename it.  If you use a module like `fs-extra` it will be nice and retry a few times in case it's a temporary file lock issue.

You also might get better results using the async version of the `fs` methods.

Closing out as it's not an issue with Electron itself 👍

**Comment by Lplenka** [comment]
I am using [configstore](https://www.npmjs.com/package/configstore) npm package to store my app data.
fs is nowhere used.

**Comment by MarshallOfSound** [comment]
@Lplenka `configstore` uses `fs` behind the scenes.  It actually appears to already use a wrapper `graceful-fs`.

https://github.com/yeoman/configstore/blob/master/index.js#L4

**Comment by Lplenka** [comment]
@MarshallOfSound  Thanks! just saw that, But any possible solution you can suggest to remove this error.
This error doesn't appear in Mac or Linux. Only happens in Windows 😞

**Comment by Lplenka** [comment]
Found a fix,
Use `electron-config` npm package instead of this. That works perfectly fine :smiley:
