### ISSUE TITLE
Issue with keyup event handling and popclip app interference

### ISSUE THREAD

**Issue by otakustay** [electron/electron#9082]
* Electron version: 1.4.13
* Operating system: macOS 10.12.4

### Expected behavior

No event reported in console

### Actual behavior

2 keyup events reported in console (C and Meta)

### How to reproduce

1. Have [popclip](http://pilotmoon.com/popclip/) installed and enabled
2. Clone repository: `git clone https://github.com/otakustay/electron-quick-start.git -b popclip-issue`
3. Run app: `electron .`
4. Switch to console panel in devtool
5. Use trackpad / mouse to select some text in window
6. Notice there are 2 keyup events logged in console

Tried the same steps in Chrome but no events are logged, popclip may use clipboard to get selected text, but what is the reason it could only be reproduced in electron but not Chrome?

**Comment by kevinsawicki** [comment]
> but what is the reason it could only be reproduced in electron but not Chrome?

What versions of Chrome did you try and what versions of Electron? Can you reproduce this with 1.6.x as well?

**Comment by otakustay** [comment]
electron v1.6.6 has the same behavior, my Chrome 58.0.3029.68 has no issue with popclip

**Comment by zcbenz** [comment]
Apps like popclip usually have its own hacks around Chrome, and not for Chrome-based apps, I'm afraid this is an issue can only be solved by popclip developers.
