### ISSUE TITLE
Webview vuejs devtool | plugins problem

### ISSUE THREAD

**Issue by Banou26** [electron/electron#9089]
* Electron version: 1.6.2
* Operating system: Windows 10

### Expected behavior
Vuejs devtool should load in a webview with plugins attribute

### Actual behavior
The Vuejs devtool isn't loaded in the `webview` console opened via `webview.openDevTools`, even though it is loaded in the `BrowserWindow `console that contains the webview

![electron_2017-04-02_14-03-42](https://cloud.githubusercontent.com/assets/5209149/24587084/e88056c2-17af-11e7-903d-edfc3f1a70a5.png)

Top console is the `webview` console openend with `webview.openDevTools` without vue
Bottom console is the `BrowserWindow` that contains the `webview` with vue

### How to reproduce
Load `BrowserWindow.addDevToolsExtension("./node_modules/vue-devtools")` and create a `BrowserWindow`, in this `BrowserWindow`, add a `webview` tag with plugins attribute and open the webview console with `webview.openDevTools()`

**Comment by zcbenz** [comment]
Unable to reproduce by running following code in devtools:

```js
var w = new WebView
w.src = 'https://vuejs.org'
document.body.appendChild(w)
```

then

```js
w.openDevTools()
```

Please provide a minimal reproducible case if it is still a problem on your side.
