### ISSUE TITLE
Broken event: page-title-updated

### ISSUE THREAD

**Issue by vishalwy** [electron/electron#9090]
According to https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-page-title-updated doing preventDefault() on the event should prevent the title from updating. However due to https://github.com/electron/electron/pull/3645 the event delivery becomes async and calling preventDefault() does nothing.

* Electron version: v1.6.2
* Operating system: Mac OS X 10.12.3

**Comment by deepak1556** [comment]
I am unable to reproduce the issue, can you provide a minimal example. Thanks!

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.

**Comment by x4080** [comment]
Yes, I confirmed that e.preventDefault() in page-title-updated cannot stop webpages title to change window title (in windows at least)

**Comment by jakerobb** [comment]
I am also experiencing this issue.
