### ISSUE TITLE
ajax bug

### ISSUE THREAD

**Issue by tkggusraqk** [electron/electron#9091]
In the HTML page, call the jQuery Ajax request and operate electron API, for example, minimize the window, close the window, there will be no response. Form is no longer caused by action

**Comment by kevinsawicki** [comment]
@tkggusraqk can you include a sample reproduction app/code that demonstrates the issue you are seeing?

**Comment by tkggusraqk** [comment]
@kevinsawicki I have no problem upgrading to 1.6.2, before version 1.4.5, I check the code carefully, follow-up questions and feedback. Thank you。

**Comment by kevinsawicki** [comment]
> I have no problem upgrading to 1.6.2


@tkggusraqk so are you still having issues?

**Comment by tkggusraqk** [comment]
@kevinsawicki Currently is no problem。

**Comment by kevinsawicki** [comment]
Okay, thanks, closing this out.
