### ISSUE TITLE
.isMaximized() always returns false even when window is maximized.

### ISSUE THREAD

**Issue by FullstackDevsYT** [electron/electron#9092]
* Electron version: v1.6.2
* Operating system: win 10

### Expected behavior
.isMaximized(); should return true

### Actual behavior
.isMaximized(); returns false;

### How to reproduce
```
const $ = require('jquery');
const {remote} = require('electron');
var win = remote.getCurrentWindow();

$('body').dblclick(function(){
  console.log('double clicked!');
});

$('#minimize').click(function(){
  win.minimize();
});

$('#close').click(function(){
  win.close();
});

$('#maximize').click(function() {
  if(win.isMaximized()){
      win.unmaximize();
      console.log('unmaximized');
  }else{
      win.maximize();
      console.log('maximized');
  }
  console.log(win.isMaximized());
});

```

**Comment by FullstackDevsYT** [comment]
it seems to be working now

**Comment by yjlintw** [comment]
I still have the same problem on Win10.
```electron version: v1.6.5```
I'm using frameless window. Is that the issue?

**Comment by stanleyxu2005** [comment]
When I set `frame=false` and also `transparent=true`, it always return false. Once the window is maximized, it will never unmaiximzed.

**Comment by ileler** [comment]
@stanleyxu2005 +1,frameless window set `transparent=true` -> .isMaximized(); always returns false;
electron: v1.7.5

**Comment by tbogard** [comment]
@stanleyxu2005 +1: if frameless window is set to `transparent:true`, win.isMaximized() will return always false. Electron 1.7.0

**Comment by AndreColli** [comment]
@stanleyxu2005 +1
Same issue here.
w10 | electron v1.7.9

**Comment by MeinLieblingsmensch** [comment]
@stanleyxu2005  @FullstackDevsYT  Same issue

Windows 10 | Electron 1.7.x and 1.8.x

**Comment by DannyFeliz** [comment]
I ended with a similar solution as @MeinLieblingsmensch I hope someone fix this.

**Comment by stanleyxu2005** [comment]
@fullstackdevsyt please reopen this ticket, as it is actually not working.

**Comment by Trackhe** [comment]
I have the same issue too. it sucks. and your Workaround is not complete. What is when you max the windows and you resize it from the border?! than you have a non maxi window with TMP = true. but that is wrong! We need a fixed function please.

**Comment by MeinLieblingsmensch** [comment]
I agree with @Trackhe there needs to be a fix to this

However, you can determine the maximum resolution size of the application and let that determine if your window needs to be maximized or minimized/unmaximized.

**Comment by abalad** [comment]
In the previous version I used the following code:
```javascript
  ipcMain.on('APPLICATION-MAXIMIZE', () => {
    mainWindow.isMaximized() ? mainWindow.unmaximize() : mainWindow.maximize()
  });
```
But in the current version it does not work anymore :(
The code `mainWindow.isMaximized()` always returns FALSE

**Comment by bibichuan** [comment]
electorn:4.0.0+win10，new BrowserWindow({ width: 800, height: 600,frame: false,titleBarStyle: 'hidden',titleBarStyle: 'customButtonsOnHover',
  transparent:true,hasShadow:false}).Still having problems.

**Comment by KyzaGitHub** [comment]
It has been over 2 years and this issue has still not been fixed.

**Comment by GeekDenCode** [comment]
Still issue in my app. I hope they fix it whenever.

**Comment by delanolima** [comment]
I have the same problem when I set:
`resizable: false`
**Question:** Why can I maximize and can not minimize?

**Comment by Feuerhamster** [comment]
Same issue here:
`new BrowserWindow({width:1240, height: 820,icon: 'favicon.ico', frame: false, webPreferences: {nodeIntegration: true, webviewTag: true}});`

But additionally the functions `win.unmaximize()` is not working.
So i can maximize the window but can not unmaximize it.
I do not have this problem in the electron version `4.1.3`.
But on every following version i have this issue.

**Comment by JustGogoing** [comment]
version 6.0.0 
Still issue in my app

**Comment by JohnGagliardi** [comment]
Broken for me as well. The IsMaximixed() issue is causing unmaximize to not run from what I can tell;

I have a static window size so I have the following work around:

 `    if (this.state.WindowMaximized)
    {
      remote.getCurrentWindow().setBounds({x: 0, y: 0, width: 1600, height: 1000});
      remote.getCurrentWindow().center();
    }
    else
    {
      remote.getCurrentWindow().maximize();
    }`

Currently looking into saving the (x,y) coordinates as well

**Comment by KyzaGitHub** [comment]
One of the problems with this not being fixed might be because of this issue being closed. The issue is _definitely not_ resolved. I'd say that this issue should be reopened.

**Comment by zouye** [comment]
Electron: 6.0.10
这个是是我的版本，依旧没有解决。但是在4.x版本中是好的。官方什么时候修复

**Comment by Darkzarich** [comment]
The problem still persist

**Comment by Nerlin** [comment]
Found the same problem with Electron 9.2.0 -- after you specify the `transparent` flag to true, isMaximized method starts to return false for every call.

**Comment by Darkzarich** [comment]
This is what I ended up with for my case:

```js
  mainWindow.minimizedState = false;

  mainWindow.on('minimize',event => {
    event.preventDefault();
    mainWindow.minimizedState = true;
    mainWindow.minimize();
  });

  mainWindow.on('restore',event => {
    event.preventDefault();
    mainWindow.minimizedState = false;
    mainWindow.restore();
  });

```

I defined my own property which I placed in `mainWindow` and access it like that in my app:

```js
remote.BrowserWindow.getAllWindows()[0].minimizedState
```

**Comment by DannyFeliz** [comment]
cc @codebytere

**Comment by zhangxuelian** [comment]
version 10.1.1
Still issue in my app

**Comment by snowInCloudy** [comment]
version 10.1.3
The problem still persists

**Comment by OldManMeta** [comment]
This is still and issue.

**Comment by DannyFeliz** [comment]
> It has been over 2 years and this issue has still not been fixed. Hopefully, we will get one by 5.0.

Your comment just turned 4 years old and this is still a problem 😄

**Comment by OldManMeta** [comment]
I'm still having issues getting a reliable value back in terms of maximised state, but I found that creating a stored local state can get around this, instead of relying on the function returning something correct.

From there, I  just call the window.setSize and window.setPosition functions to actually restore a window - spent way too long messing around with something that should be so simple and built in.
