### ISSUE TITLE
Regression in #1562: loading a large image will cause a renderer crash

### ISSUE THREAD

**Issue by MrSaints** [electron/electron#9093]
* Electron version: 1.6.5
* Operating system: Debian 8.7

### Expected behavior

The page should load without resulting in a renderer crash.

### Actual behavior

Any page with a large image will result in a renderer crash unless enough memory is given.

### How to reproduce

This appears to be a regression in https://github.com/electron/electron/issues/1562 (seeing as the last comment indicates that it is no longer a problem).

The example mentioned (https://github.com/electron/electron/issues/4639), occasionally results in a 
renderer crash when the `/dev/shm` size is set to 64m.

This could just be _normal_ behaviour seeing as 64m might be too low to load such a large image. Nevertheless, I've noticed that this isn't an issue on Electron 1.3.x despite having a low shared memory setting. So, this might be a Chromium issue.

I'm currently testing this via: 

```
docker run --rm -v $(pwd):/converted/ arachnysdocker/athenapdf athenapdf -S https://blog.arachnys.com
```

It contains a Dockerized Electron application. It is running on 1.6.5.

```
docker run --rm -v $(pwd):/converted/ arachnysdocker/athenapdf:2.7.1 athenapdf -S https://blog.arachnys.com
``` 

The above is running on Electron 1.3.x, and it works fine.

They both rely on a standard set up like so:

```
const BrowserWindow = electron.BrowserWindow;
bw = new BrowserWindow();
bw.loadURL(uri);

bw.webContents.on("crashed", () => {
    console.error(`The renderer process has crashed.`);
});
```

**Comment by zcbenz** [comment]
It is probably because Chromium did some change that require a larger shared memory, while we would like to fix this, I'm afraid this is how Chromium works fundamentally and we are unable to work around on Electron's side.

So I'm closing this as won't fix, pull requests to fix it would be welcomed though.
