### ISSUE TITLE
macOS Sierra tabs: control if new window opens inside tab group or separate

### ISSUE THREAD

**Issue by bpasero** [electron/electron#9094]
* Electron version: 1.6.5
* Operating system: macOS Sierra

If you have a window with native tab bar to the top and you open a new window, it will open as separate window. But if you are in fullscreen mode, that new window will be attached as tab. Would it make sense to have API to force a window to open into an existing tab group or not? This would make it possible to give the user the choice of wether a window should open as tab or not independent from being in fullscreen mode or not.

Not even sure such API exists on macOS though.

/cc @tonyganch

**Comment by tonyganch** [comment]
@bpasero, could you please try my test repo for that?
I run the app, the main window gets open.
I click the green button to put the window into fullscreen mode, then I click on "Create a new window in a new tab group" and a new fullscreen window appears, not a tab.

**Comment by bpasero** [comment]
@tonyganch good test case! Here are the problems I can see:
* I can avoid having a window open as tab when in fullscreen by using a different tab identifier but then this new window can never be grouped together as a consequence which seems weird
* I can not force a new window to open in the same tab when I am not in fullscreen mode

So imho it boils down to having a way of telling a new window to open:
* into an existing tabbing group
* into a separate tabbing group
* into a separate window

I think todays API does not allow that.

**Comment by bpasero** [comment]
Maybe I am also not fully understanding how a mac user would use this feature, I am seeing this more like Chrome tabs work: I can open a new window or I can open a new tab but I can always move a window into another window to produce a tab and I can also always drag out a tab to make a new window. I think that is what I was expecting for sierra tabs too.

**Comment by bpasero** [comment]
@tonyganch I just found out about this setting, I guess this is user controlable and maybe should be like that without override from the app:

![image](https://cloud.githubusercontent.com/assets/900690/24899871/2f205232-1ea2-11e7-84dd-96c2c334bf41.png)

**Comment by djalmaaraujo** [comment]
How can we open a new tab? I know that the new-window-for-tab even is available now, but can we force the event to be called? Right now we can't create a shortcut like cmd+t, correct? Is this one of the things this PR will solve?
