### ISSUE TITLE
allowDisplayingInsecureContent missing in the docs

### ISSUE THREAD

**Issue by aight8** [electron/electron#9103]
allowDisplayingInsecureContent missing in the documentation

**Comment by kevinsawicki** [comment]
> missing in the documentation

Where in the docs should this be included? There is a doc for `allowRunningInsecureContent`.

**Comment by aight8** [comment]
Arn't those two different options?

**Comment by kevinsawicki** [comment]
This `allowRunningInsecureContent` option was removed in Chrome 56, https://github.com/electron/electron/commit/2e0780308c7ef2258422efd34c968091d7cd5b65

**Comment by aight8** [comment]
Okey then it's solved. If we already here, what's about a options validator? with vjs or so.
