### ISSUE TITLE
Electron does not start on window with no information.

### ISSUE THREAD

**Issue by benjaminfresh** [electron/electron#9107]
* Electron version: 1.6.2
* Operating system: Windows 10 x64

### Expected behavior
I am new to electron and I have followed the quick start quide https://electron.atom.io/docs/tutorial/quick-start/

Nothing happens when I run the following commands

electron .  (when I installed globally).
.\node_modules\.bin\electron . (when I installed locally)

When i use the following version i get npm error.

# Clone the repository
$ git clone https://github.com/electron/electron-quick-start
# Go into the repository
$ cd electron-quick-start
# Install dependencies
$ npm install
# Run the app
$ npm start

![screenshot 3](https://cloud.githubusercontent.com/assets/26137487/24657046/d0f60bee-193c-11e7-8fc9-aa8e09240c0b.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/26137487/24657047/d0f61f44-193c-11e7-8f60-1d1609e39c2f.png)

please I need help to get started quickly.

**Comment by MarshallOfSound** [comment]
@benjaminfresh Running Electron from inside an Electron app (Atom) historically has issues if the terminal emulator is implemented poorly.  (They forget to unset `ELECTRON_RUN_AS_NODE`)

Try from normal command prompt and see what happens 👍

**Comment by benjaminfresh** [comment]
OMG. It just worked from the normal command prompt. @MarshallOfSound, thank you very much.
