### ISSUE TITLE
discussion: What native modules are you using with Atom-Shell?

### ISSUE THREAD

**Issue by bwin** [electron/electron#911]
And how do you compile them (apm, node-gyp, **edit:** grunt-build-atom-shell, npm, ...)?
**Edit:** But I'm more interested to hear what modules you're using.

Thnx

**Comment by maxkorp** [comment]
@lygstate It's been a few months, but I just stumbled on this by accident, figured I'd respond for the off chance you still needed help. Master branch builds on atom-shell (current npm release wont without manual rebuild), but we should be live soon. If you need help. hop into the gitter on the repo and we can help you out.

**Comment by atrauzzi** [comment]
Bit of necro here, but @lygstate - did you ever manage to get nodegit working?

**Comment by lygstate** [comment]
sorry I've never tried
