### ISSUE TITLE
[Help] How to make Finder Sync integration ?

### ISSUE THREAD

**Issue by Necmttn** [electron/electron#9114]
I am currently developing a Dropbox-like mac application. The application is syncing files in a folder placed in "~/AppFolder" on my mac. I'd like to add badges showing sync status on the files managed by my application.

has anyone done this before ? any suggestion for how to do it ?

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by ilyaLibin** [comment]
@Necmttn Did you find how to do that?

**Comment by ilyaLibin** [comment]
@enlight This is actually a feature request because Electron doesn't support that now.

**Comment by Necmttn** [comment]
@ilyaLibin it's not impossible but you would need to pack your app within Xcode. which requires MacOs development expertise... (and certification => macOs doesn't allow 3rd party apps to be aware of file changes unless they been certified.) 
personally, I didn't implement.

**Comment by coconutbox** [comment]
Is there any news about this topic?
