### ISSUE TITLE
Log Devtools console output to a file

### ISSUE THREAD

**Issue by sn0opr** [electron/electron#9115]
Is it possible to get the Devtools console output to write it to a log file ?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
FWIW you can intercept all `console.*` methods and send their args to a file if you want to.  Something like this would do a simple / hacky job 👍 

```js
const originalConsoleLog = console.log.bind(console)
console.log = (...args) => {
  writeArgsToFile(args);
  originalConsoleLog(...args);
}
```

**Comment by sn0opr** [comment]
@MarshallOfSound  Thank you, but I want to get all the output of the console, like error logs et exceptions etc...

**Comment by MarshallOfSound** [comment]
@sn0opr You can catch uncaught exceptions like so

```js
window.onerror = (err) => {
 // Do something
}

process.on('uncaughtException', (err) => {
  // Do something
})
```

**Comment by remss** [comment]
@MarshallOfSound With this override in the devtools console each entry will have the file were is the console.log override, and not the real file origin.
A solution is put your override in a dedicated file like "console.js" and then [blackbox](https://developer.chrome.com/devtools/docs/blackboxing) it. You will see the real origin of logs.

**Comment by bartektenDev** [comment]
Can you write an example like where the file will be written and how you execute the console.log to a string form?
