### ISSUE TITLE
<webview> printToPDF window content scales down in relation to page size if screen Display text/apps setting is greater than 100% 

### ISSUE THREAD

**Issue by midweststudios** [electron/electron#9118]
Using `<webview>.printToPDF()`
* Electron version: 1.6.5 (upgraded in case latest version fixed issue)
* Operating system: Windows 8 & Windows 10 (only when screen Display text/apps setting is scaled from 100%)

### Expected behavior
PDF content fills entire height/width of print page size (i.e. ratio 1:1)

#### Example for screen display scale set at 200% on a Windows Surface Pro 3:
- `var options = {marginsType: 1, pageSize: "Letter"}`
  - I also tried `height` and `width` in microns for the pageSize

PDF exports at correct Letter size (8.5in x 11in) but the target content is scaled down 50% (4.25in x 5.5in) on the page.

**Comment by midweststudios** [comment]
I think this can be resolved by making all of the key's assigned in `const defaultPrintingSetting = {}` available options within `WebContents.prototype.printToPDF = function (options, callback) {...}`. Then in my project file I can check for the screen's scaleFactor and/or it can be as simple as changing `fitToPageEnabled: false` to `fitToPageEnabled: true`. Won't know for sure until I run tests though. 

Please reference: [https://github.com/electron/electron/blob/master/lib/browser/api/web-contents.js](https://github.com/electron/electron/blob/master/lib/browser/api/web-contents.js)

Note: I need to wrap up the project that's having this issue and would prefer just modifying the file from my local install, but I haven't been able to find the Electron `.js` source files. If anyone can point me in the right direction, I would greatly appreciated it!

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by Alecyrus** [comment]
I set page rule like this
```css
@page { 
     size A4 portrait;
}
```

but every page of printed PDF by `webContent.printToPDF` always overflow.

<img width="1014" alt="截屏2019-10-0514 02 40" src="https://user-images.githubusercontent.com/13865581/66250733-ce9d0700-e778-11e9-8ec5-fce177b49320.png">

And `letter` will be fine. `A4`、`A5` always overflow, which will cause another blank page being printed

**Comment by Alecyrus** [comment]
`fitToPageEnabled` is available, I can not find it in official document.

**Comment by Alecyrus** [comment]
#20436
