### ISSUE TITLE
Electron desktop capturer and graphic adapters.

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#9119]
**Problem**: Desktop capturer shares black screen when try to share entire screen.

**Reason**: If you are using a laptop, you may run into capture issues (black screen). This is because most laptops have more than one graphics adapter. Why do they have more than one graphics adapter? Because one is used for saving power (desktop / windows), and the other is used for performance (gaming). This is done to minimize power usage on the laptop, as laptops are designed to run on batteries.

Because of this fact, it can often cause capture issues. Your laptop may be drawing one image to the power saving GPU, and another to the performance GPU. However, in order for App to capture efficiently, App itself must be running on the same GPU as that you wish to capture. If App is running on adapter A, and an image is being drawn on adapter B, you will get a black screen when trying to capture it.

**Question** Comparing to chrome it always use built-in video adapter, which also used by OS and most part of applications. But Electron app, from very beginning, was set to use external video adapter (If it available) and the issue comes. Does it some how configurable?

**Comment by zcbenz** [comment]
Electron just calls into Chromium's API to capture the screen, I'm not sure why there is any difference, maybe it is related to Chrome versions?

Anyway to find out why it happened requires debugging into Chromium's desktop capturing code, which we do not have resources to do, so I'm closing this as won't fix.

**Comment by cumajkeee** [comment]
The problem according screen sharing is knows issue for whole world, here you have nothing to do. My issue mostly relates to question: why chrome by default is using built-in GPU, and electron app - external? I believe the root of this is part of framework.
