### ISSUE TITLE
Frameless non resizable window keeps decreasing in size on Windows taskbar height or position change.

### ISSUE THREAD

**Issue by mzmiric5** [electron/electron#9120]
* Electron version: 1.6.2
* Operating system: Windows 10 x64

### Expected behavior

When a window is set to resizable false, no external sources should be changing the window width and height.

### Actual behavior

On Windows, when moving or resizing the Windows taskbar causes the window to keep decreasing in size on every taskbar change.

### How to reproduce

https://github.com/mzmiric5/Electron-Frameless-FixedSize-Win-Repro

Run the provided repo on Windows. Resize the windows task bar a few times. Notice the window viewport reducing in size every time.

Interestingly enough setting the minWidth and minHeight for the BrowserWindow resolves this issue.

Possible solution would be to automatically set the min width and height when resizable is false.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
