### ISSUE TITLE
dialog.showSaveDialog does not set default filename

### ISSUE THREAD

**Issue by Sharim** [electron/electron#9127]
* Electron version:
"electron-builder": "13.3.1",
"electron-prebuilt": "1.4.13",
* Operating system:
Windows 10

### Expected behavior

Should set also defualt filename

### Actual behavior

I cannot set default filename, however defaultPath is set, but filename not.
I tried path like
C:\Patryk\Pictures\21467.jpg *for this i got console error that dir does not exist
and
C:\Patryk\Pictures/21467.jpg  *for this just window show but without filename

### How to reproduce

```
let options = {
     title: "Select photo folder:",
     defaultPath: "C:\Patryk\Pictures\21467.jpg",
}

return dialog.showSaveDialog(options);
```

**Comment by kevinsawicki** [comment]
Hmm, having trouble reproducing this, tried with the following:

```js
options = {
     title: "Select photo folder:",
     defaultPath: "C:\\Users\\Kevin\\Pictures\\test.png",
}

require('electron').remote.dialog.showSaveDialog(options);
```

<img width="885" alt="screen shot 2017-04-25 at 4 00 20 pm" src="https://cloud.githubusercontent.com/assets/671378/25411225/609db21c-29d0-11e7-957d-2981b29c1907.png">

Your example code did not have the backslashes escaped in the string, could that be your issue?

**Comment by Sharim** [comment]
Looks like the problem was unescaped backslashes. Thanks for your time & help :)
