### ISSUE TITLE
APPCRASH on Windows 2008 SP2, thanks

### ISSUE THREAD

**Issue by 18911816776** [electron/electron#9130]
dxgi.dll!CreateDXGIFactory1

问题事件名称: APPCRASH
应用程序名: da.exe
应用程序版本: 0.2.1.0
应用程序时间戳: 58b7058f
故障模块名称: dxgi.dll!CreateDXGIFactory1
故障模块版本: 6.0.6002.18005
故障模块时间戳: 49e03824
异常代码: c0000139
异常偏移量: 0006f04e
OS 版本: 6.0.6002.2.2.0.274.10
区域设置 ID: 2052
其他信息 1: 9d13
其他信息 2: 1abee00edb3fc1158f9ad6f44f0f6be8
其他信息 3: 9d13
其他信息 4: 1abee00edb3fc1158f9ad6f44f0f6be8

**Comment by 18911816776** [comment]
Maybe it's not support Windows 2008

**Comment by cifratila** [comment]
Yes, Vista and Server distros are not supported: https://github.com/electron/electron/issues/3263
