### ISSUE TITLE
Error: tunneling socket could not be established, statusCode=403 

### ISSUE THREAD

**Issue by WinnerNeverQuits** [electron/electron#9138]
C:\Electron\electron-quick-start>npm install

electron@1.6.2 postinstall C:\Electron\electron-quick-start
\node_modules\electron
node install.js
C:\Electron\electron-quick-start\node_modules\electron\instal
l.js:46
throw err
^

Error: tunneling socket could not be established, statusCode=403
at ClientRequest.onConnect (C:\Electron\electron-quick-st
art\node_modules\tunnel-agent\index.js:166:19)
at ClientRequest.g (events.js:291:16)
at emitThree (events.js:116:13)
at ClientRequest.emit (events.js:194:7)
at Socket.socketOnData (_http_client.js:394:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (stream_readable.js:134:10)
at TCP.onread (net.js:551:20)
npm WARN Error: EPERM: operation not permitted, lstat 'C:\Ele
ctron\electron-quick-start\node_modules\mkdirp\node_modules'
npm WARN { Error: EPERM: operation not permitted, lstat 'C:
Electron\electron-quick-start\node_modules\mkdirp\node_modules'
npm WARN errno: -4048,
npm WARN code: 'EPERM',
npm WARN syscall: 'lstat',
npm WARN path: 'C:\Electron\electron-quick-start\node
modules\mkdirp\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.2 postinstall: node install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.2 postinstall script 'node install.js'.

**Comment by kevinsawicki** [comment]
This looks to be a network issue when downloading from npm, are you behind a firewall or using a proxy? 

It may also have been an intermittent network issue since `npm install` downloads Electron directly from github.com, are you still experiencing it?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
