### ISSUE TITLE
Passing --trace-warnings flag to node to print stack of unhandled promise rejections

### ISSUE THREAD

**Issue by jlongster** [electron/electron#9139]
* Electron version: 1.6.2
* Operating system: OSX

### Expected behavior

I should be able to use the `--trace-warnings` flag in node by passing it like this:

```js
app.commandLine.appendSwitch('trace-warnings')
```

This enables stack traces for unhandled promise rejections. Right now, node will print "possibly unhandled promise rejection: <err>" but not print a stack trace, which is incredibly frustrating.

### Actual behavior

Passing the flag to node enables stack traces for unhandled promise warnings.

### How to reproduce

Run this code within `index.js` of the electron app:

```js
new Promise((resolve, reject) => reject(new Error("foo")))
```

**Comment by jlongster** [comment]
I completely understand the difficulty of keeping up with issues on an active project, but can anyone talk about if this is valid, and if so what kind of timeline to expect on issues like this? Even better, point me to where I could implement this myself and contribute it?

**Comment by deepak1556** [comment]
Yup this is definitely good to have feature, Electron by default doesn't parse all node related flags in the normal mode as most of them don't apply.

> if so what kind of timeline to expect on issues like this?

Not sure, mostly based on community interest I guess. Unless someone assigns themselves to work an issue, you can feel free to pick it up. Would be great to leave a comment to avoid duplications.

> Even better, point me to where I could implement this myself and contribute it?

You can check how `debug-brk` flag https://github.com/electron/electron/blob/master/atom/common/node_bindings.cc#L202 is supported, `trace-warnings` should also be implemented in a similar way. Hope that helps!

**Comment by jlongster** [comment]
Thanks! Would something like this work?

```patch
diff --git a/atom/common/node_bindings.cc b/atom/common/node_bindings.cc
index f469677..e397a04 100644
--- a/atom/common/node_bindings.cc
+++ b/atom/common/node_bindings.cc
@@ -198,16 +198,20 @@ node::Environment* NodeBindings::CreateEnvironment(
   process.Set("helperExecPath", helper_exec_path);
 
   // Set process._debugWaitConnect if --debug-brk was specified to stop
   // the debugger on the first line
   if (browser_env_ == BROWSER &&
       base::CommandLine::ForCurrentProcess()->HasSwitch("debug-brk"))
     process.Set("_debugWaitConnect", true);
 
+  if (browser_env_ != BROWSER &&
+      base::CommandLine::ForCurrentProcess()->HasSwitch("trace-warnings"))
+      process.Set("traceProcessWarnings", true);
+
   return env;
 }
 
 void NodeBindings::LoadEnvironment(node::Environment* env) {
   node::LoadEnvironment(env);
   mate::EmitEvent(env->isolate(), env->process_object(), "loaded");
 }
 ```

If I look at the top of the function BROWSER is either a browser, renderer, or worker process. What I'm wanting to debug is the main process. I'm skeptical that this is the wrong place for that. Chrome's devtools already give you the stack for unhandled exceptions in the renderer process (I think). But debugging the main process is harder because you don't have chrome's devtools.

I'm trying to get a dev build of electron locally to test this but it's taking a long time.

**Comment by jlongster** [comment]
So it turns out that I probably shouldn't be doing as much work as I am in the main process. I didn't realize it could still block the render process, so I'm probably going to move all my backend code to its own process which, I think, I could open the Chrome devtools on. I guess most people haven't hit this issue because you don't usually do much work in the main process?

In that case I'm not as interested in landing this. I *think* that Chrome's devtools will already have this turned on and I'll see stacks in the devtools.

**Comment by milahu** [comment]
> What I'm wanting to debug is the main process.

same

its confusing that the terminal says ``Use `electron --trace-warnings ...` to show where the warning was created``

but when i add the `--trace-warnings` flag, then it only affects the first electron process,
but not the second electron process (type=renderer)

```
$ electron --trace-warnings path/to/app
$ ps -AF | grep electron
/usr/bin/electron --trace-warnings path/to/app
/usr/bin/electron --type=renderer --app-path=path/to/app
```

devtools is not working in my case

**Comment by martpie** [comment]
@milahu did you manage to append the flag to the renderer process?
