### ISSUE TITLE
buildFromTemplate Is Not A Function? 

### ISSUE THREAD

**Issue by vKepler** [electron/electron#9141]
* Electron version: 1.6.2
* Operating system: Microsoft Windows 10 Pro

### Expected behavior

For the menu to be created from a template correctly as it's copied straight from documentation.
Code (only including relevant code):
```
//Required imports
const electron = require('electron');
const {app, BrowserWindow, Menu, MenuItem} = require('electron');
const path = require('path');
const url = require('url');

//Global win variable to be assigned to windows
let win;

function setupTopMenu() {
  win.setMenu(null);

  var topMenu = new Menu();

  const template = [
  {
    label: 'File',
    submenu: [
      {role: 'Open...'},
      {role: 'Exit'}
    ]
  },
]

  topMenu.buildFromTemplate(template);
  win.setMenu(topMenu);
}

function createParentWindow(height, width) {
  win = new BrowserWindow({height, width, icon: __dirname + '/public/img/ha-logo.png'});

  setupTopMenu();
}
```

### Actual behavior

"Uncaught Exception: TypeError: topMenu.buildFromTemplate is not a function"

**Comment by kevinsawicki** [comment]
>  topMenu.buildFromTemplate(template);

I think this should be:

```js
topMenu = Menu.buildFromTemplate(template);
```

**Comment by vKepler** [comment]
@kevinsawicki OMG you're a genius.. Why must it be like this if I've already instantiated topMenu above and set equal to new instance of menu? Sorry for crap question, please close it.. Also I see you in here all the time you're a real GitHubber Hero bro..

**Comment by kevinsawicki** [comment]
`buildFromTemplate` is a helper class method that is meant to convert an entire raw object of items to a root `Menu` instance filled with `MenuItem` instances.

`new Menu()` should be used when you manually want to add `MenuItem` instances using things like insert, append, etc., https://electron.atom.io/docs/api/menu/#menuappendmenuitem
