### ISSUE TITLE
Windows Event Log

### ISSUE THREAD

**Issue by datnordstrom** [electron/electron#9142]
Is there a way to log events to the Windows Event Log? (windows 10)

I've attempted to use winston-winlog2 but have not been able to get it to work? has anyone else been successful?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW you can check out modules such as this one 👍 

https://github.com/jfromaniello/node-windows-eventlog
