### ISSUE TITLE
我详细翻译了比zh-cn更丰富的docs文档,如何分享给更多人?

### ISSUE THREAD

**Issue by amhoho** [electron/electron#9146]
我在[electron-cn-docs](https://github.com/amhoho/electron-cn-docs/)这个项目中详细的翻译了全部的英文docs文档,并基本保持实时的更新.如何分享给更多中国用户,或者上传到Electron中?

**Comment by LitoMore** [comment]
pull request

**Comment by LitoMore** [comment]
为 electron 贡献翻译可以给项目提交 pull request

文档的中文翻译在 https://github.com/electron/electron/tree/master/docs-translations/zh-CN

文档的排版可以参考 [中文文案排版指北](https://github.com/mzlogin/chinese-copywriting-guidelines)

**Comment by kevinsawicki** [comment]
Looks like this question was answered, thanks @LitoMore, closing this out.

Translations live in this repository and we are working on a better system to allow easier translations, https://github.com/electron/electron.atom.io/issues/686
