### ISSUE TITLE
Option to set process.env.TZ from render process 

### ISSUE THREAD

**Issue by myfrndjk** [electron/electron#9150]
Hi,

I am trying to set time zone using `process.env.TZ = 'America/Managua' `in my app
if I give that in main process it is properly setting up timezone but if I give that in render process no effect, is there any way to set timezone from render process.

Thanks

**Comment by MarshallOfSound** [comment]
They are two distinct processes so setting it in one does not set it in the other.  You would have to set it in both if you want it available in both.  You can change the main process env from a renderer process though through `require('electron').remote.process.env`

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by myfrndjk** [comment]
@MarshallOfSound : Sorry for the false alarm.Thanks for your clarification
