### ISSUE TITLE
Drag'n'Drop in macOS Sierra

### ISSUE THREAD

**Issue by stek29** [electron/electron#9153]
* Electron version: 1.4.1 and 1.6.5 (VK Messenger and Wavebox)
* Operating system: macOS 10.12.4

### Expected behavior
If application can't handle drag'n'drop, nothing should happen. Maybe cursor should change to `X`

### Actual behavior
If Application doesn't handle drag'n'drop or it was dropped too fast, dragged file (image) opens (at 1.4.1 at least)

### How to reproduce
Just drag'n'drop some image on Electron app.
Even if app handles drag'n'drop, you still can reproduce this if you're fast enough -- that's what I did in [video](https://youtu.be/lQlg1oxlhts).

**Comment by zcbenz** [comment]
It seems like a Chromium bug, please report this to [Chromium's issues list](https://crbug.com) instead. Closing since it is a Chromium bug that we can not fix on Electron's side.
