### ISSUE TITLE
How to use native OpenGL to render on the Electron Window?

### ISSUE THREAD

**Issue by BentleyBlanks** [electron/electron#9161]
* Electron version: 1.6.2
* Operating system: Windows 7

### Expected behavior

I want to make a 3d editor and use Electron to do the UI staff, and keep some region for native OpenGL to render some contents on it. But it seems hard to use OpenGL in Node.js(not WebGL), just like this
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/134486032@N03/33842172981/in/dateposted-public/" title="electronWithOpenGL"><img src="https://c1.staticflickr.com/3/2894/33842172981_6e17b5d62d_z.jpg" width="640" height="309" alt="electronWithOpenGL"></a>

What now I'm doing is use offscreen rendering sending dirty buffer to the C++ program, and display as a texture on the it. But it is quite inconvenient to handle so many UI messages from Electron. So is there any probablity to use native OpenGL to render on the Electron app?

**Comment by levrik** [comment]
I think CEF (https://bitbucket.org/chromiumembedded/cef) would be a better choice for something like that. But that's only my opinion.

**Comment by BentleyBlanks** [comment]
It seems CEF is similar to the Electron's offscreen. 

Actually I tried to use Three.js to simulate the same thing native OpenGL does. But I find it hard to put the UI label (HTML+CSS+JS) draw on the Three.js, just like this

<a data-flickr-embed="true"  href="https://www.flickr.com/photos/134486032@N03/33162957753/in/dateposted-public/" title="electronWithThreeJS"><img src="https://c1.staticflickr.com/4/3727/33162957753_b3d6243661_z.jpg" width="640" height="309" alt="electronWithThreeJS"></a>

I find it not that easy to implement……Maybe it is more convenient to use ImGui to make a 3d editor I think ?

**Comment by Zerocjx** [comment]
@BentleyBlanks Any new progress？

**Comment by biluncloud** [comment]
@BentleyBlanks Any progress for this?

**Comment by 4nte** [comment]
I have an identical use case, has anyone made this work?

**Comment by UnrealDoggie** [comment]
Create a native OpenGL and make it the child of the chrome browser window?

**Comment by SimantoR** [comment]
If avoiding javascript to make the GL calls, then might I add that `emscripten` is an alternative. It makes OpenGL ES 2 calls but atleast you get the C++ execution times and upto 2gb ram while still being on web land.

**Comment by Thaina** [comment]
There is mention about hwnd around `getMediaSourceId` API. Would you think native opengl would be satisfied with that hwnd pointer?

**Comment by UnrealDoggie** [comment]
Not sure about that. U mean create an opengl context using this native window handle? The problem is this is the top-level window which probably has other inner child windows. You probably need to create a child window.

In my case(very Windows-specific, specific use case, not generalized), what I did was to overlay the transparent electron browser window(background transparent, allow mouse event to fall through transparent area) with ui controls over a native glfw3 opengl window (note this is a separate process) & make this opengl window a child of the electron browser window. The disadvantage is the communication has to be via REST or some other electron to native c++ protocol.
In the below snapshot, the 3D scene is using glfw3 (in another process)  & the widgets are in html5 , Vuejs.
![nativeopenglbelowelectron](https://github.com/electron/electron/assets/67040097/b0dde6d8-b4c5-4407-a5ec-58e4c1de5781)

**Some code snippets** see comments

```javascript

//Javascript
// Get native window handle ID => HWND
function getNativeWindowHandleInt(win) {
  const hbuf = win.getNativeWindowHandle()
  if (os.endianness() === 'LE') {
    return hbuf.readInt32LE()
  }
  return hbuf.readInt32BE()
}
``` 
```c++

// Intermediate Chrome browser window we must find
HWND  chrome D3DWindow = nullptr;
// top level browser native window handle
// Pass in as int using getNativeWindowHandleInt from electron
HWND parent;
// Native window handle of glfw3 window
HWND nativeHwnd = glfwGetWin32Window(pWindow3D);

// Enumerate & find the first D3D Window under parent
static BOOL CALLBACK EnumChromeWindowsProc(HWND hwnd, LPARAM lParam) {
        char buf[256];
        if (GetClassNameA(hwnd, buf, sizeof(buf) / sizeof(*buf))) {
                if (strstr(buf, "Intermediate D3D Window")) {
                        chromeD3DWindow = hwnd;
                }
        }
        return TRUE;
}
```
```c++
        // This will find  chromeD3DWindow as we need change window styles
	(void)EnumChildWindows(parent, EnumChromeWindowsProc, (LPARAM)NULL);
	LONG_PTR parentStyle = 
        GetWindowLongPtr(chromeD3DWindow, GWL_STYLE);
        if ((parentStyle & WS_CLIPCHILDREN) == 0)
	     parentStyle |= WS_CLIPCHILDREN;
        if ((parentStyle & WS_CLIPSIBLINGS) == 0)
             parentStyle |=  @WS_CLIPSIBLINGS;
        // Change styles on chromeD3DWindow otherwise overlay will not work
	SetWindowLongPtr(chromeD3DWindow, GWL_STYLE, parentStyle);
	parentStyle = GetWindowLongPtr(chromeD3DWindow, GWL_STYLE);
        if ((parentStyle & WS_CLIPCHILDREN) == 0)
	{
            parentStyle |= WS_CLIPCHILDREN;
            SetWindowLongPtr(parent, GWL_STYLE, parentStyle);
	}
        // Make native glfw3 window borderless etc
	LONG_PTR style = GetWindowLongPtr(nativeHwnd, GWL_STYLE);
	style &= ~WS_POPUP;
	style &= ~WS_MINIMIZEBOX;
	style &= ~WS_SYSMENU;
	style |= WS_CHILDWINDOW;
	//style |= WS_CLIPSIBLINGS;
	//style &= ~(WS_EX_APPWINDOW);
	SetWindowLongPtr(nativeHwnd, GWL_STYLE, style);
	
	//Setting to child of intermediate d3d chrome window MAY NOT WORK FOR SOME MACHINES! So we abandon this
	// Instead set glfw window as child of parent and force z-order to bottom most
	HWND successHWND = SetParent(nativeHwnd, parent);
	if (successHWND) glfwSetWindowPos(pWindow3D, 0, 0);
	else
            MessageBox(NULL, "FAILED TO ADD OPENGL AS CHILD OF ELECTRON", "WINDOW", MB_OK);

```
