### ISSUE TITLE
Window not correctly drawn after repositioning to other screen

### ISSUE THREAD

**Issue by capc0** [electron/electron#9163]
* Electron version: 1.4.12
* Operating system: Win 7 Home Premium 64 bit (Windows CLASSIC design active)

### Expected behavior

The window should be drawn correctly / window contents should be redrawn

### Actual behavior

The electron window is not being updated after moving the window (or just a half of it) to another screen. As soon as I focus another window (e.g. cmd prompt) the electron window refreshes and is drawn correctly again.

### How to reproduce

1) Install electron globally
2) Open CMD and type 'electron'
3) Move the window to another screen

Example of a distorted window - left part is on my left 1920x1080 screen, right part is on my right 1920x1080 screen (moved from the right screen to the left)
![eb](https://cloud.githubusercontent.com/assets/27284008/24908926/4d2ebb04-1ec2-11e7-9420-974cf1b50a93.png)

**Comment by capc0** [comment]
I found a workaround for this issue:
Using 'electron --disable-gpu' fixes the problem.

I currently dont know the downsides of disabling gpu (guess performance?), but a real fix would still be handy.

**Comment by zcbenz** [comment]
This is bug of GPU rendering, which I'm afraid none of us in Electron team are familiar with Chromium's GPU rendering code to be able to fix this, and your best hope is to wait for Chrome upgrades to fix this. So I'm closing this as won't fix.
