### ISSUE TITLE
Symbol information for breakpad

### ISSUE THREAD

**Issue by snene** [electron/electron#9165]
We have an Electron(version 1.4.15) based app that we package using electron-builder for mac and windows platforms.

We also use crash reporter that is supported by Electron. In order to look at the minidumps sent by the crash reporter, we need to generate symbol information for the executables to be placed on the breakpad server.

When I try to extract symbol information from the exe for windows, symupload utility(provided by breakpad) fails to read the symbol information from the file.

Also when I tried to generate symbols for mac exe, it generated only following two symbols:
PUBLIC 0 0 _mh_execute_header
PUBLIC f00 0 main

I am already aware about the symbols that Electron provides with each new release.

So my question is how do I get symbol information for the exes that I can use with the mini breakpad server. Please let me know if I am not clear and you have further questions.

**Comment by baldwmic** [comment]
I am also encountering the same problem when trying to generate symbols. It would be superb if there was a helpful guide on how to get human readable stack traces when crash reporting!

**Comment by zcbenz** [comment]
You can follow how crash reports are symbolized in the mini-breakpad-server project:
https://github.com/electron/mini-breakpad-server/blob/master/src/reader.coffee

**Comment by johnryan** [comment]
@baldwmic @snene did you guys figure this out? I tried putting the darwin `electron.breakpad.syms` folder inside `/pool/symbols/app` But still not seeing any symbolicated crashes.

**Comment by baldwmic** [comment]
@johnryan I ended up going with this repo instead: https://github.com/acrisci/simple-breakpad-server

**Comment by johnryan** [comment]
@baldwmic thanks for the tip...did you figure out which "sym" files need to be uploaded from the release page? When I try to upload the whole `.syms` folder with curl (as mentioned in the simple-breakpad-server) I get an error.

**Comment by baldwmic** [comment]
@johnryan to be honest, I don't think I ever figured it out. We set up the server to report electron crashes, but we gave up trying to get more readable stack traces because of the difficulty in generating these symbols.

Please let me know if you figure it out!

**Comment by snene** [comment]
Even I haven't figured out yet. After crash reporter integration, I am able to send the crash dumps to the server. But they are not readable. :-(

**Comment by baldwmic** [comment]
@snene @johnryan looks like there is similar confusion about how to generate the symbols here: https://github.com/electron/mini-breakpad-server/issues/9

**Comment by johnryan** [comment]
@baldwmic yea there isn't really any good documentation. I tried adding all the electron symbols as mentioned in the instructions there but it's still not getting symbolicated correctly.
