### ISSUE TITLE
alwaysOnTop window disappears when restored from the application icon

### ISSUE THREAD

**Issue by jschimmoeller** [electron/electron#9170]
* Electron version: 1.6.2
* Operating system: Mac OS Serra 

### Expected behavior

Restoring browser window with always on top should restore 

### Actual behavior

with always on top set and minimze window into application icon window restoring a minimized window will show and then disappear and lost forever. 

### How to reproduce

  $ git clone https://github.com/jschimmoeller/app-icon-consolidate.git
  $ npm install
  $ npm start 

make sure Minize windows into application icon is set 
![image](https://cloud.githubusercontent.com/assets/1423536/24940597/107d6b60-1f12-11e7-8dec-149593c70edc.png)

steps:  
1.  minimize app
2.  click on electron icon in dock to restore 
3.  window will restore and then disappear

**Comment by kevinsawicki** [comment]
I can reproduce this, thanks for the detailed reproduction.

Looking at the docs at https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/WinPanel/Concepts/WindowLevel.html I do see the following mentioned:

> if you assign a window to a floating level, you must ensure that you also set it to hide on deactivation of your application or reset its level when your application is hidden. Cocoa automatically takes care of the latter aspect for you if you use default window configurations.

So I'm thinking here we need to remove the custom level when `windowWillMiniaturize` fires and then restore it when `windowDidDeminiaturize` fires.
