### ISSUE TITLE
setAsDefaultProtocolClient process.argv not updated when app is already started

### ISSUE THREAD

**Issue by nicolasandrieux** [electron/electron#9172]
* Electron version: 1.4.14
* Operating system:windows 10

Hi,

I'm using setAsDefaultProtocolClient to launch the app and performing action like that

myprotocol://action1
myprotocol://action2

So 
if the app is closed I get in `process.argv` `myprotocol://action1` or `myprotocol://action2` as expected.
If the app is already launched, I'm using the event `browser-window-focus` to detect the app is called but the `process.argv` is not updated, still the same as the start of the app.

I'm doing something wrong?

(BTW, look like the tel protocol is not able to use in electron app, when I try to set it doesn't works)

**Comment by MarshallOfSound** [comment]
@nicolasandrieux On windows when the app is already open and it is launched as a protocol handler you need to listen for the new processes arguments through the `makeSingleInstance` callback.

For an example check out my rather old PR at this point for standardizing this 👍

https://github.com/electron/electron/pull/8052

On macOS you can use the [`open-url` event](https://electron.atom.io/docs/api/app/#event-open-url-macos)

**Comment by nicolasandrieux** [comment]
@MarshallOfSound Thx a lot I got what I expect with my custom scheme protocol.

Should I open another issue for the tel protocol? For that one that open a popup offering to open the link using apps like skipe
