### ISSUE TITLE
Questionable props on debuggers Network.loadingFailed event (if resource is canceled)

### ISSUE THREAD

**Issue by aight8** [electron/electron#9174]
* Electron version: 1.6.x
* Operating system: macOS

### Expected behavior

Not sure why this is the behavior, because it makes not much sense.
The ```canceled``` and ```blockedReason``` props in the props of ```Network.loadingFailed``` should be set in my opinion.

### Actual behavior

Debugger on ```Network.loadingFailed``` event:

**errorText:** ```net::ERR_BLOCKED_BY_CLIENT```
**canceled:** ```false```
**blockedReason:** ```undefined```
*...other props...*

The fields **canceled** is always ```false```, this makes no sense...
Furthermore the field **blockedReason** is always ```undefined```.

### How to reproduce

Cancel any resource loading via:
```JS
webRequest.onBeforeRequest(/*...*/, (details, callback) => {
   callback({ cancel: true })
})
```
*this code is just a snippet to point where the cancelation should occure.*

**Comment by deepak1556** [comment]
Have verified that chrome 56 reports the right value for `Network.loadingFailed` canceled but blockedReason is undefined though. The reason for different values of canceled is because we reject the requests with `ERR_BLOCKED_BY_CLIENT` but chrome rejects with `ERR_ABORTED`. Need to get some clarity from upstream on this.

**Comment by zcbenz** [comment]
Hmm Chrome also rejects with `ERR_BLOCKED_BY_CLIENT` in its webRequest API, honestly I don't know `Network.loadingFailed` should look like for cases like this, but it is probably too late to change the behavior. Closing this as won't fix.
