### ISSUE TITLE
Feature request: webRequest module = resource size

### ISSUE THREAD

**Issue by aight8** [electron/electron#9175]
### Expected behavior

Provide the **resource size** somewhere in the webRequest module.
In the debugger module it is present as ```encodedDataLength``` in the following events:
- Network.loadingFinished -> encodedDataLength

(source: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/)

### Actual behavior

In the webRequest module (https://electron.atom.io/docs/api/web-request/) there **real** resource size is nowhere passed. The only way to get more information about the resource size is to use the **debugger** module - this works great however the debugger module is has known downside:
Debugger must be attached - cannot use devtools in parallel - maybe performance downsides. Furthermore the webRequest module should be provide this basic information too.

**Comment by deepak1556** [comment]
Can you expand on how the resource size attribute will be utilized ? Currently there is no means to retrieve the response content with webRequest module unlike debugger module.

**Comment by aight8** [comment]
I don't know, I'm not familiar with the chrome internals and on which parts this feature would depend on. I report this issue from the user perspective.

Meanwhile I found the chrome JS network API on which this feature somehow depend on.
https://developer.chrome.com/extensions/webRequest

The content size could be used for basic data transfer statistics. Indeed the Content-Length header could be used but it's everything else than trustable.

**Comment by deepak1556** [comment]
I am good with adding this attribute but it will be better to add once https://github.com/electron/electron/issues/8374 gets support.

**Comment by zcbenz** [comment]
Merging this to #8374.
