### ISSUE TITLE
Feature request: webContents::executeJavascript - Better syntax error handling

### ISSUE THREAD

**Issue by aight8** [electron/electron#9176]
* Electron version: 1.6.x
* Operating system: macOS

### Expected behavior

Several things:
- The promise which is returned by executeJavascript should be rejected
- The error and stack trace should be more meaningful (how? = what's possible?)
- Furthermore if you listen of global errors with the debugger trough the ```Runtime.exceptionThrown``` event - there is currently no way to locate where exactly the error happened. By the way the below error output is captured by this event. There must be a way to identify the script somehow or even better return the source to create a code frame. (compile a named code or so? don't know exactly how it works...)

### Actual behavior

When call webContents.executeJavascript and the passed javascript has a syntax error.
There are several problems which make it difficult to debug:
- The stack trace is useless (see screenshot)
- The returned promise from ```executeJavascript``` hangs in the ```pending``` state
- No identification to which injected JS it belongs to (can be skipped if the previous point is solved smart)

### How to reproduce

```JS
webContents.executeJavascript('just some syntax error')
```

## Appendix

<img width="997" alt="bildschirmfoto 2017-04-12 um 19 26 47" src="https://cloud.githubusercontent.com/assets/1138623/24971037/c5449510-1fb6-11e7-8b89-086ae5d40db1.png">

```JS
{ columnNumber: 4,
  exception: 
   { className: 'SyntaxError',
     description: 'SyntaxError: Unexpected identifier\n    at EventEmitter.electron.ipcRenderer.on (/Users/xxx/yyy/js_package_nightmare-service/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/init.js:52:28)\n    at emitMany (events.js:127:13)\n    at EventEmitter.emit (events.js:201:7)',
     objectId: '{"injectedScriptId":1,"id":1}',
     preview: 
      { description: 'SyntaxError: Unexpected identifier\n    at EventEmitter.electron.ipcRenderer.on (/Users/xxx/yyy/js_package_nightmare-service/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/init.js:52:28)\n    at emitMany (events.js:127:13)\n    at EventEmitter.emit (events.js:201:7)',
        overflow: false,
        properties: 
         [ { name: 'stack',
             type: 'string',
             value: 'SyntaxError: Unexpected identifier\n    at EventEmi…27:13)\n    at EventEmitter.emit (events.js:201:7)' },
           { name: 'message',
             type: 'string',
             value: 'Unexpected identifier' },
           [length]: 2 ],
        subtype: 'error',
        type: 'object' },
     subtype: 'error',
     type: 'object' },
  exceptionId: 1,
  executionContextId: 1,
  lineNumber: 0,
  scriptId: '112',
  stackTrace: 
   { callFrames: 
      [ { columnNumber: 27,
          functionName: 'electron.ipcRenderer.on',
          lineNumber: 51,
          scriptId: '65',
          url: '/Users/xxx/yyy/js_package_nightmare-service/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/init.js' },
        { columnNumber: 12,
          functionName: 'emitMany',
          lineNumber: 126,
          scriptId: '30',
          url: 'events.js' },
        { columnNumber: 6,
          functionName: 'emit',
          lineNumber: 200,
          scriptId: '30',
          url: 'events.js' },
        [length]: 3 ] },
  text: 'Uncaught' }
```

**Comment by MarshallOfSound** [comment]
Closing in favor of your own issue #9102

Please don't raise duplicate issues 👍
