### ISSUE TITLE
getUserMedia HD

### ISSUE THREAD

**Issue by LoganArnett** [electron/electron#9177]
* Electron version: 1.6.2
* Operating system: Ubuntu 16.04
* Webcam: Logitech 4k BRIO

### Expected behavior
I am trying to record audio and video within my app at 1920x1080 at at least 30fps. Using getUserMedia like the WebRTC demos [here](https://webrtc.github.io/samples/src/content/getusermedia/resolution/) at full HD in chrome as a web app I am able to accomplish this resolution at 60fps

### Actual behavior
Currently in electron I get the correct resolution by the fps is roughly 10fps

### How to reproduce
Plugin a webcam with at least 1920x1080 and 30fps capabilities and try something like this:
```js
return navigator.mediaDevices.getUserMedia({ video: { deviceId: devices.webcam, width: {exact: 1920}, height: {exact: 1080}, frameRate: {exact: 30} }}).then(stream => {
         video.src = window.URL.createObjectURL(stream);
         return video.play();
 })
```

**Comment by LoganArnett** [comment]
I am running a react application within Electron, would I be able to make a very simple express app that just handles the webcam video and recording and use a `<webview>` tag to place it into my react view?

**Comment by zcbenz** [comment]
Hmm I don't know why it happens, but I'm afraid we are unable to fix this since it is related to your specific hardware, even though it might be Electron's bug. Closing this as won't fix.
