### ISSUE TITLE
Documentation for VSCode is faulty.

### ISSUE THREAD

**Issue by rafoid** [electron/electron#9181]
* Electron version: latest
* Operating system: Mac OS Sierra

### Expected behavior
On https://electron.atom.io/docs/tutorial/debugging-main-process-vscode/ page it states:
1. Open an Electron project in VSCode.
$ git clone git@github.com:electron/electron-quick-start.git

git cloning should proceed without a problem

### Actual behavior

git clone git@github.com:electron/electron-quick-start.git
Cloning into 'electron-quick-start'...
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

### How to reproduce
try cloning the mentioned repo.

**Comment by poiru** [comment]
You probably have something wrong with your SSH key setup, see: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

You could also use the HTTPS URL:
```
git clone https://github.com/electron/electron-quick-start.git
```
