### ISSUE TITLE
Confusion over syntax

### ISSUE THREAD

**Issue by iamdriz** [electron/electron#9182]
I'm looking to upgrade an old Electron app (built in atom-shell) to the latest version of Electron, but reading through the docs I see variations in the syntax.

What's the difference between:

`const {BrowserWindow} = require('electron')`

and

`const BrowserWindow = require('electron').BrowserWindow`

**Comment by MarshallOfSound** [comment]
No difference at all, it's purely a style choice.

Personally I prefer the first one :)

**Comment by iamdriz** [comment]
@MarshallOfSound What is the first one? I've never seen that syntax before but presume it's part of ES6... do you have a link to a doc that explains: `{THING}`, as to me those braces were always for creating hashes/objects. Thanks pal.
