### ISSUE TITLE
Documentation for webview and nodeIntegration suggests an insecure option

### ISSUE THREAD

**Issue by tejohnso** [electron/electron#9186]
In the [webview](https://electron.atom.io/docs/api/webview-tag/) section:

>For security purposes, webview can only be used in BrowserWindows that have nodeIntegration enabled.

Wouldn't it be more secure to have *nodeIntegration* **disabled**?

This is reinforced in the [security section](https://electron.atom.io/docs/tutorial/security/).

>Disable the Node integration in all renderers that display remote content (setting nodeIntegration to false in webPreferences)

**Comment by MarshallOfSound** [comment]
@tejohnso WebViews are used to host remote content in their own renderer process.  This effectively creates a nested WebContents inside your top level BrowserWindow for every webview you have.  WebView's give access to webcontents API's, preload scripts and a whole load of other stuff that you should have have access to if `nodeIntegration` is enabled.

The trick here is that `nodeIntegration` **inside** the WebView is disabled, this means that you can have your browserwindow with nodeIntegration hosting remote content in a safe way.  This fulfills both the quoted pieces of documentation.

1. The WebView which is hosting the remote content will have `nodeIntegration` disabled
2. The renderer hosting the WebView will have `nodeIntegration` enabled

**Comment by tejohnso** [comment]
>...access to webcontents API's, preload scripts and a whole load of other stuff that you shouldn' have access to if nodeIntegration is not enabled.

@MarshallOfSound can you elaborate further on how having nodeIntegration improves security when those features are present?

**Comment by MarshallOfSound** [comment]
@tejohnso I think you are getting confused between available features and security levels.  The point I was making is that if you have access to the WebView element then by definition you can create a renderer process with `nodeIntegration` enabled.  This would be very bad if a renderer process without `nodeIntegration` could create itself a new renderer process with `nodeIntegration` enabled.

As such it is only safe for processes with `nodeIntegration` already enabled to create WebView's.

> having nodeIntegration improves security when those features are present

Having `nodeIntegration` doesn't improve security technically, having more node API's is **less** secure so it is only allowed when the parent renderer process also has `nodeIntegration`.  This grid might explain it a bit better.

| Parent Renderer `nodeIntegration` | Can use Node API's | Can use WebView | Can use Node API's through WebView |
|------------------------------------|--------------------|---|---|
| Enabled | Yes | Yes | Yes |
| Disabled | No | No | No |

You should be able to see that having a row in that table `"Disabled | No | Yes | Yes"` would be ridiculously unsafe

**Comment by tejohnso** [comment]
@MarshallOfSound I think I understand the situation.  Since the subordinate has privilege X, the superordinate must clearly indicate and expose its privilege X so as not to mask the existence of that privilege in the subordinate.

However, I think the row I would expect is `"Disabled | No | Yes | No".  In fact, I think that's the **only** row I would expect.  A more flexible option would be to prevent nodeIntegration in a WebView whose parent does not also have nodeIntegration.  In the current state, we're prevented from the most secure option of ensuring nodeIntegration is disabled in the parent BrowserWindow as well as the child WebView.

**Comment by MarshallOfSound** [comment]
@tejohnso `nodeIntegration` is not the only problem, the webview element gives the parent page complete control over the renderer webview page.  That kind of power should not be given out lightly.  Imagine a random website X being rendered in Electron just throwing up a webview for the google sign in screen but injecting JS to capture the password.  Entirely possible if they access to the webview element.  The current model is safe and I don't think it should change.

**Comment by tejohnso** [comment]
@MarshallOfSound I appreciate your time and I'm not looking to change anything, just trying to understand.  In your above scenario, how would the embedder's `nodeIntegration:true` help prevent password capture?

**Comment by MarshallOfSound** [comment]
I think you got it backwards again.  `nodeIntegration: true` doesn't prevent it, it is an explicit way of allowing it.  `nodeIntegration: false` explicitly prevents the current renderer creating a webview and therefore prevents it from accessing node APIs through the webview APIs.

I can only explain this so many times, I'd what I'm saying doesn't make sense for some reason I'd suggest asking on slack and seeing if someone else can explain it to you.

The easiest thing to say here.  Having a webview gives a renderer access to node APIs through a preload script on that webview.  If an existing renderer has node disabled giving it access to a webview allows it to bypass the disabling of node.  This is neither safe nor secure, hence only webviews with node enabled can use webviews

**Comment by tejohnso** [comment]
Thanks @MarshallOfSound

**Comment by tejohnso** [comment]
Looks like webviews can now be used with nodeIntegration disabled via https://github.com/electron/electron/pull/9397
