### ISSUE TITLE
Native PDF rendering should be supported inside sub-frames and embed tags

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#9192]
* Electron version: 1.6.6
* Operating system: macOS 10.12.2 Sierra

### Expected behavior

Be able to render PDFs in a similar way to chrome

### Actual behavior

* Works for opening a pdf online, e.g. `http://www.pdf995.com/samples/pdf.pdf`. Doesn't work across Microsoft online services. outlook, office 365, oneDrive.

* Sharing a document from one drive and setting the source of a browser window results in an AssertError which looks like it comes out of electron rather than the hosted page

![screen shot 2017-04-14 at 08 03 00](https://cloud.githubusercontent.com/assets/103586/25035995/fcb968b2-20e8-11e7-88ca-f45f4a996d5b.png)

```
AssertionError: path must be a string
    at Module.require (module.js:497:3)
    at require (internal/module.js:20:19)
    at d (https://onedrive.live.com/?cid=7a8be9037c2aa5d8&id=7A8BE9037C2AA5D8%218874&ithint=file,pdf&authkey=!AIYcKlIuVkXRlTM:12:5177)
    at https://onedrive.live.com/?cid=7a8be9037c2aa5d8&id=7A8BE9037C2AA5D8%218874&ithint=file,pdf&authkey=!AIYcKlIuVkXRlTM:28:86
```

* Outlook & Office 365 use an embed tag for the actual PDF, but this fails to load. No information in Developer Tools, but I suspect is related to the logs above...

### How to reproduce

Here's a modified version of electron-quick-start that opens two browser windows. One opens the working PDF, the other opens one hosted on oneDrive (with the assert error).

```
$ git clone https://github.com/wavebox/electron-quick-start -b pdf_rendering_bug
$ npm install
$ npm start
```

To see the embed version failing is a bit more effort...
* Point a BrowserWindow at `outlook.live.com` & Sign in
* Email yourself a PDF
* Try to view it in the browser. The webpage displays a failed to load error, but there are no logs or more information for this one

**Comment by deepak1556** [comment]
Yes the current pdf rendering implementation will not work inside sub-frames and embed tags. Will use this issue to track it, also can you update the repo to reproduce the assertion error. I don't see any test case in the `pdf_rendering_bug` branch, thanks!

**Comment by LesterU** [comment]
Is there any chance this is going to be fixed? Its a real killer for me when using Outlook.

**Comment by Thomas101** [comment]
@deepak1556 I've just updated the quick-start repo and also retested with 1.7.1 https://github.com/wavebox/electron-quick-start/tree/pdf_rendering_bug

Thanks!

**Comment by Thomas101** [comment]
Also seeing the following if we try to load one from asana which punches through to aws.

![screen shot 2017-06-30 at 09 13 40](https://user-images.githubusercontent.com/103586/27726963-6dd5960c-5d74-11e7-81a1-a0b1c0dbfcbd.png)

**Comment by gerges** [comment]
In my case, it turns out the application I was using had fallback viewer support, but the fact that a there was the presence of a value in `navigator.mimeTypes` that claimed to support pdf existed was causing it to avoid this path. I was able to hack around this with the following, which made PDFs viewable again, using the fallback viewer provided by the site I was navigating

```
// Workaround electron#9192
Object.defineProperty(navigator, 'mimeTypes', {
  enumerable: true,
  configurable: false,
  writable: false,
  value: new Proxy(navigator.mimeTypes, {
    get: function(target, name) {
      if (name in target) {
        let val = target[name];
        if (val instanceof MimeType) {
          let isPdf = val.suffixes.split(',').includes('pdf');
          if (isPdf) {
            return {
              type: '',
              description: '',
              suffixes: '',
              enabledPlugin: false};
          }
        }
        return val;
      }
    }
  })
});
```

**Comment by Thomas101** [comment]
It looks like https://github.com/electron/electron/pull/10008 in 1.7.6 has fixed some of the failing cases where the querystring caused it to fail. The original test case with the assertion error still fails

**Comment by f4n** [comment]
@gerges how to use that code?

**Comment by gerges** [comment]
@f4n I've added that at the bottom of the preload script (webview or BrowserWindow)

**Comment by ahmedmohamedali** [comment]
Hi electron team,
I have a fix that needs changes in electron but also in chromium for PDF in sub frames.

**Comment by ahmedmohamedali** [comment]
@deepak1556,
Do you mean I should create one PR for electron and the other for google team in chromium.googlesource.com or do you have a chromium content fork ?
Thanks.

**Comment by deepak1556** [comment]
@ahmedmohamedali you can create a PR for the chromium patch at https://github.com/electron/libchromiumcontent.

**Comment by ahmedmohamedali** [comment]
This is the PR for libchromiumcontent
https://github.com/electron/libchromiumcontent/pull/374

**Comment by ahmedmohamedali** [comment]
And this the PR for the electron part https://github.com/electron/electron/pull/10793

**Comment by ahmedmohamedali** [comment]
The PRs  #374 and #10793 fixe the issue for sub frames but not for embed tag.
The message "Couldn't load plugin" is displayed for embed tag navigation. 
In my opinion, this issue should be spitted in two issues: one for sub frames and the other for embed tags

**Comment by ahmedmohamedali** [comment]
Hi @deepak1556,
Is there anything missing for going forward with this PR ? Thanks.

**Comment by riyazudheen** [comment]
@ahmedmohamedali #11064 is an issue raised by me. Do you see it related with the issue for <embed> tag that you mention above?

**Comment by ahmedmohamedali** [comment]
hi @riyazudheen ,
Not sure if this is the same issue or not. Can you provide a modified electron-quick-start that reproduces the issue you mentioned in  #11064 ?  Thanks.

**Comment by codebytere** [comment]
We support PDF viewing insofar as https://github.com/electron/electron/pull/21794 enables it.
