### ISSUE TITLE
Frameless window overlaps Windows taskbar when auto-hide is active

### ISSUE THREAD

**Issue by sla89** [electron/electron#9193]
* Electron version: We are using node 7.4.0 , Chromium 56.0.2924.87 , and Electron 1.6.2 .
* Operating system: Win 7 64 bit

### Expected behavior
A frameless window shall not overlap the hidden taskbar when it is maximized.

### Actual behavior
The frameless window uses the whole space of the screen. So when the taskbar is hidden and the frameless window is maximized you cannot access your taskbar anymore.

### How to reproduce

1. Set frame = false
2. Activate auto-hiding of your taskbar (right click taskbar -> properties -> check auto-hide the taskbar)
3. Maximize window
4. Try to access the taskbar --> not possible

**Comment by arjndr** [comment]
Have you tried it on an earlier version of electron? I was able to reproduce it on Windows 7 x64 with electron 1.6.2 maybe this is a bug?

**Comment by poiru** [comment]
Possibly fixed by #9167.

**Comment by sla89** [comment]
I have tested it with the sources of the master branch (code from today) and everything works like a charm. This can be closed. :+1:

**Comment by jbmonroe** [comment]
Actually, in a kiosk-mode application (running on a kiosk), this is desirable.  How would I make this happen if this is "fixed?"

**Comment by Acrivec** [comment]
So, any way to get autohidden taskbar to work, when on top? It's really driving me nuts when I try to get to taskbar when for example Discord is maximized. The only way is to either minimize it or use win key.
