### ISSUE TITLE
Is possible to check if electron is launched from command line?

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#9196]
I want to check if electron is launched from command line.
If yes, I will output some detail log files.
Otherwise, do not wirte log files.
Is it possible?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

There are quite a few userland tricks for doing this kind of thing, the most common is a simple

```js
// Simple
if (process.execPath.includes('electron'))

// Safer
if (/\/electron\/.test(process.execPath))
```

There is no built-in way in Electron to determine this

**Comment by MarshallOfSound** [comment]
Good additional reading as well https://github.com/electron/electron/issues/7714
