### ISSUE TITLE
No way to create a new minimized window

### ISSUE THREAD

**Issue by xyyaya** [electron/electron#9198]
I found that there is no way to create a minimized window with the API, if I do this on win7:
`
win = new BrowserWindow();
win.show();
win.minimize();
`

The window sometimes flush on the screen and then minimized with an animation.

So, is there any way to create a minimized window just like:
`
win = new BrowserWindow({
  minimized: true
})
`

**Comment by MarshallOfSound** [comment]
@xyyaya Maybe try

```js
win = new BrowserWindow({ show: false });
win.minimize();
win.on('ready-to-show', () => win.show());
```

**Comment by xyyaya** [comment]
@MarshallOfSound It works thank you very much
