### ISSUE TITLE
Reason for renderer crash?

### ISSUE THREAD

**Issue by herrjemand** [electron/electron#9199]
Hey there. So I am trying to debug my electron app. I have a big(over 400 tests) http api mocha test suit, that has to be run as HTML app. For some reason after about 100 tests, renderer(webContents) crashes. I catch an event, and killed variable is false.

How do I debug such situation? Is there a way to get an error message? I have googled a lot, and found no helpful info on this regard.

Cheers. Yuriy

**Comment by MarshallOfSound** [comment]
Try running it with `ELECTRON_ENABLE_STACK_DUMPING=true` and `ELECTRON_ENABLE_LOGGING=true` and see what it spits out 👍

**Comment by herrjemand** [comment]
@MarshallOfSound nothing new in the console *(

**Comment by herrjemand** [comment]
@MarshallOfSound Ref: #7591

**Comment by herrjemand** [comment]
I can't write code to reproduce the issue, as it is not specific to the event.

**Comment by herrjemand** [comment]
@MarshallOfSound Is there a way to get log of what render doing?

**Comment by andymartinwork** [comment]
I have added a hook to renderer crashes in our app, and it happens rather frequently for users. Is there any way to detect the reason for renderer crashes in the JS callback?

**Comment by herrjemand** [comment]
Ok. So I've build electron with debug log, and here is what I am getting:

```
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7f5f5acc9d07 <unknown>
#1 0x7f5f48ecffe0 <unknown>
#2 0x7f5f6012f39c <unknown>
#3 0x7f5f6043d713 <unknown>
#4 0x0ac4032883a6 <unknown>
  r8: 00000000beeddead  r9: 00000000beeddead r10: 000009af72c938f0 r11: 00000000beeddead
 r12: 000009af72c92000 r13: 000009af72bc1ff0 r14: 00007ffc8c970d68 r15: 00007ffc8c970d98
  di: 00007ffc8c970c70  si: 000000000000000a  bp: 00007ffc8c970d58  bx: 00007ffc8c970c70
  dx: 0000000000000001  ax: 0000000000000001  cx: 000009af72c92000  sp: 00007ffc8c970c40
  ip: 00007f5f6012f39c efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
```

**Comment by herrjemand** [comment]
cc: @MarshallOfSound @andymartinwork

**Comment by MarshallOfSound** [comment]
@andymartinwork Nope, if it's a native crash (not a JS error) then the only way to get the stack AFAIK is through the crash reporter.

**Comment by creatist** [comment]
I got the same problem on my arm linux board ,does it have been resolved?

**Comment by AndreColli** [comment]
I have that same problem too!
w10 | node 8.9.1 | electron 1.7.9
