### ISSUE TITLE
globalShortcut event - Super+<keys> not working as documented, on Windows 10

### ISSUE THREAD

**Issue by sancarn** [electron/electron#9206]
Code Example:

```
globalShortcut.register('Super+Space', function(){
	mainWindow.show()
})
```

The above code should trigger on the `Windows+Space` keyboard shortcut. However from my testing it does not.

I can clarify however that super corresponds correctly to command on Mac.

**Comment by MarshallOfSound** [comment]
@sancarn The issue template is there for a reason 😄 Can you please share the Electron version you are experiencing this on 👍 

Also have you tested with other combinations or just `Super+Space`, would recommend testing out a few others like `Super+Control+A`, `Super+A` and `Super+1`

**Comment by sancarn** [comment]
Hi Marshall,

Apologies:

`We are using Node.js 7.4.0, Chromium 56.0.2924.87 and Electron 1.6.2`

I have indeed tried other combinations:

`Super+Z`

It is my understanding that `Super+1` won't work anyway as `Win+1` is reserved by the windows OS.

**Comment by kevinsawicki** [comment]
> globalShortcut.register('Super+Space', function(){

This method returns a boolean on whether it was successful or not and with your example it returns `false` for me on Windows 10. This suggests that this key combination is reserved by Windows and so applications cannot use it.

I'm not sure if a list exists of all thereserved hot keys, but http://stackoverflow.com/questions/11767458/how-do-you-register-a-custom-winv-hotkey-on-windows-8 has some interesting discussion.

The Windows docs only state:

> Either WINDOWS key was held down. These keys are labeled with the Windows logo. Keyboard shortcuts that involve the WINDOWS key are reserved for use by the operating system.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309(v=vs.85).aspx

I was able to get a super combination to register and fire though so it does seem possible, you just need to pick one that is allowed by the OS, the one that worked for me was:

```js
app.once('ready', () => {
  const ret = globalShortcut.register('super+control+b', () => {
    console.log('pressed!')
  })

  if (!ret) {
    console.log('registration failed')
  }
})
```

So I'm going to close this issue out since this seems to be a limitation of Windows where only certain super shortcuts are allowed to be registered.

**Comment by sancarn** [comment]
Just curious... Why doesn't electron have use Low level event hooks, ultimately allowing it to overwrite reserved keyboard shortcuts (except ctrl+alt+delete, windows will still restrict this)?

**Comment by kevinsawicki** [comment]
> .. Why doesn't electron have use Low level event hooks, ultimately allowing it to overwrite reserved keyboard shortcuts (except ctrl+alt+delete, windows will still restrict this)?

Do you have links to the documentation of these hooks? Electron currently uses the `RegisterHotKey` API which seems like the right API to use for this.

**Comment by kevinsawicki** [comment]
>  Why doesn't electron have use Low level event hooks, ultimately allowing it to overwrite reserved keyboard shortcuts (except ctrl+alt+delete, windows will still restrict this)?

Also for context, Electron currently uses the code from Chrome to do this: https://cs.chromium.org/chromium/src/chrome/browser/extensions/global_shortcut_listener_win.cc

**Comment by sancarn** [comment]
This is what I was talking about:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms644990(v=vs.85).aspx

And see [here](http://stackoverflow.com/a/454503/6302131) for a C++ example.

**Comment by kevinsawicki** [comment]
Thanks for passing those along, if you are interested in re-implementing global shortcuts in Electron to use these APIs please feel free to open up a pull request and we can discuss more there.

**Comment by sancarn** [comment]
I would but I honestly have no idea how GITHub pull requests work xD

**Comment by MarshallOfSound** [comment]
FWIW I have low level hooks implemented in a node module for use in my app but i don't think using them should be default.  Lots of anti virus apps think that programs using low level hooks are suspicious and we don't want to force that onto users.

**Comment by sancarn** [comment]
It could always be an option...

**Comment by MarshallOfSound** [comment]
@sancarn Most AV apps work by scanning for signatures of known threats, basically static analysis to determine if a file potentially has bad code in it. It would still be picked up by AV programs regardless of whether or not it is activated.  It would not be a good idea to implement low level hooks in Electron as it would cause basically all apps to be picked up by AV.

**Comment by sancarn** [comment]
Riight so that's why you didn't implement it.

You say you have implemented such things in the past though. How did you go about doing this in a node module might I ask? Is it a completely customised thing. I haven't found any native node modules that wrap the SetWindowHookEx command, except ffi - which I haven't been able to get working as of yet...

**Comment by MarshallOfSound** [comment]
@sancarn This is my module to do this 👍 

https://github.com/MarshallOfSound/node-lowlevel-keyboard-hook-win
