### ISSUE TITLE
Default TouchBar button size with icon is massive

### ISSUE THREAD

**Issue by charlex** [electron/electron#9207]
* Electron version: 1.6.6
* Operating system: macOS 10.12.3

### Expected behavior

Padding around buttons to be uniform, regardless of if there is an icon, an icon with a label, or just a label.

### Actual behavior

Buttons with just an icon occupy a large space.

<img width="1085" alt="touch bar shot 2017-04-16 at 11 15 09 am" src="https://cloud.githubusercontent.com/assets/1542740/25073217/8feb4aca-2296-11e7-8801-5479da576e18.png">

### How to reproduce

This is the icon I'm using:

https://raw.githubusercontent.com/encharm/Font-Awesome-SVG-PNG/master/white/png/128/compress.png

```
const electron = require('electron');
const TouchBar = electron.TouchBar;

const app = electron.app

const BrowserWindow = electron.BrowserWindow

const url = require('url')

var path = require('path');

var BASE_URL = url.format({
  pathname: path.join(__dirname, 'index.html'),
  protocol: 'file:',
  slashes: true
});
var ICONS = path.join(__dirname, '/src/app/styles/images/');

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow;

let fullscreen_touchbar_btn = new TouchBar.TouchBarButton({
  label: '',
  icon: path.join(ICONS, 'expand.png'),
  click: function() {
    if(mainWindow.isFullScreen()) {
      mainWindow.setFullScreen(false);
      fullscreen_touchbar_btn.icon = path.join(ICONS, 'expand.png');
    } else {
      mainWindow.setFullScreen(true);
      fullscreen_touchbar_btn.icon = path.join(ICONS, 'compress.png');
    }
  }
});

const touchBar = new TouchBar([
  fullscreen_touchbar_btn,
  new TouchBar.TouchBarButton({
    label: '⚡️ Home',
    // backgroundColor: '#4591b8',
    click: function() {
      mainWindow.loadURL(`${BASE_URL}`);
    }
  }),
  new TouchBar.TouchBarButton({
    label: '✚ Liveblog',
    // backgroundColor: '#45B865',
    click: function() {
      mainWindow.loadURL(`${BASE_URL}#/liveblogs/new`);
    }
  }),
  new TouchBar.TouchBarButton({
    label: '✚ Card',
    save: 'flexible',
    // backgroundColor: '#45B865',
    click: function() {
      mainWindow.loadURL(`${BASE_URL}#/liveblogs/unknown/card/new`);
    }
  }),
  new TouchBar.TouchBarSpacer({ size: 'flexible' }),
  new TouchBar.TouchBarButton({
    label: '💾',
    // backgroundColor: '#FF5443',
    click: function() {
      mainWindow.loadURL(BASE_URL);
    }
  }),
]);

function createWindow () {
  mainWindow = new BrowserWindow({width: 800, height: 600});
  mainWindow.setTouchBar(touchBar)
}

app.on('ready', createWindow)

```

**Comment by MarshallOfSound** [comment]
@charlex I can't find the docs now but basically an NSButton will always have the width of the original image regardless of scaling applied to it.  Your initial image is quite large so the button that is made inherits that width.

The touchbar then scales down the image but due to the way the button was sized it is exceedingly big.  If you resize your images to be the correct size for a touch bar then the button will be the correct size as well 👍

**Comment by charlex** [comment]
Ah I thought it might have been that. Thank you! @MarshallOfSound it might be a "nice to have" if we put the correct size of images in the docs.

**Comment by MarshallOfSound** [comment]
@charlex Apple have nice docs for this kind of thing 👍 

https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/Icons.html#//apple_ref/doc/uid/20000957-CH107-SW1

**Comment by charlex** [comment]
Very fair! Thanks for that link.
