### ISSUE TITLE
[Query] How does electron generate its docs?

### ISSUE THREAD

**Issue by saikrishnadeep** [electron/electron#9210]
Hi, I was just wondering how electron generates the docs from the `.md` in the folder `/docs/`?  Does it use a standard tool like `pandoc`, `mkdocs` or does it use something else? I apologize for opening this as an issue. 

Their generated docs: https://electron.atom.io/docs/

**Comment by MarshallOfSound** [comment]
The website is actually just fancily rendered versions of those markdown files 👍 

We do parse our docs into structured JSON though through https://github.com/electron/electron-docs-linter

**Comment by MarshallOfSound** [comment]
The generated JSON file is attached to each release 👍 

https://github.com/electron/electron/releases/download/v1.6.6/electron-api.json
