### ISSUE TITLE
Electron-based app fails to start when xml-stream library is used

### ISSUE THREAD

**Issue by paulbrzeski** [electron/electron#9212]
* Electron version: 1.6.2
* Operating system: Windows 10 64 bit and Mac OSX (Capitan? Latest..)

### Expected behavior

The app should start normally when running with 'electron .'

### Actual behavior

In Windows, 

App threw an error during load
Error: The module '\\?\C:\git\scriptomente\node_modules\node-expat\build\Release\node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (C:\git\scriptomente\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\git\scriptomente\node_modules\node-expat\lib\node-expat.js:4:32)

In MacOS the error is similar but obviously not about a DLL.

### How to reproduce

1. Start with any basic Electron application.
2. Install xml-stream, npm install xml-stream --save
3. Instantiate in your app, const XmlStream = require('xml-stream');
4. Start your app

This is a really bizarre issue... I've tried everything from Windows Build Tools to Electron Rebuild/Prebuilt. My next thought it to just drop the xml-stream library but that's going to force me to do some fancy XML taijutsu and I'd rather just keep things simple if I can...

**Comment by brenca** [comment]
This is an error related to another dependency (probably of xml-stream), node-expat. This module is compiled against an older version of electron, hence the error.

Generally speaking this error means that a native c++ module is compiled against a different version of electron. I'm closing this since this is not an electron bug.

**Comment by MarshallOfSound** [comment]
Relevant module to fix these things --> https://github.com/electron/electron-rebuild
