### ISSUE TITLE
生成exe问题  build package (exe)

### ISSUE THREAD

**Issue by crylg** [electron/electron#9220]
electron-packager ./ --all --out ./build-app --version 1.0.0 --overwrite --icon=./logo/logo.ico --platform win32

WARNING: The version parameter is deprecated, use electronVersion (or --electron-version in the CLI) instead

... and 1 more
connect ETIMEDOUT 54.231.81.200:443
为什么会去连接美国服务器
有没有办法绕开这一步?

**Comment by crylg** [comment]
> electron-packager ./ --all --out ./build-app --overwrite --icon=./logo/logo.ico --platform win32


... and 1 more
connect ETIMEDOUT 54.231.81.200:443

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "package"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-electron-quickstart@1.0.0 package: `electron-packager ./ --all --out ./build-app --overwrite --icon=./logo/logo.ico --pl
atform win32`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-electron-quickstart@1.0.0 package script 'electron-packager ./ --all --out ./build-app --overwrite --icon=
./logo/logo.ico --platform win32'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-electron-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager ./ --all --out ./build-app --overwrite --icon=./logo/logo.ico --platform win32
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-electron-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-electron-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\angular2-electron-quickstart\npm-debug.log

**Comment by MarshallOfSound** [comment]
@crylg It looks like you are failing to connect to S3, if you are behind a proxy or firewall and can't hit S3 you should use the `ELECTRON_MIRROR` environment variable to specify a mirror to get the electron binaries from 👍 

Chinese mirror for instance: https://npm.taobao.org/mirrors/electron

**Comment by MarshallOfSound** [comment]
^^ Reached that conclusion as `54.231.81.200` is an S3 IP address 👍

**Comment by KagamiChan** [comment]
use command like `ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/ npm i electron` works, note that the ending `/` cannot be omitted
