### ISSUE TITLE
Minimized window of secondary monitor isn't properly restored when using Remote Desktop

### ISSUE THREAD

**Issue by yuya-oc** [electron/electron#9223]
* Electron version: 1.6.2, 1.6.6
* Operating system: Windows 10 Pro

### Expected behavior

Minimized window should appear properly on the remote desktop console.

### Actual behavior

The window didn't appear when restoring.
Other native apps like cmd.exe or mspaint.exe were correctly restored.

### How to reproduce

1. Connect the secondary monitor.
2. Start electron.
3. Move the BrowserWindow to the secondary monitor.
4. Minimize it.
5. Start Remote Desktop session from another computer.
6. Try to restore the window by clicking taskbar icon on the console.

**Comment by yuya-oc** [comment]
For this problem, our app uses a workaround by using `restore` event and `screen` module.

The concept is below. 

```javascript
win.on('restore', () => {
  const isOffScreen = offScreenValidation(win);
  if(isOffScreen) {
    win.setPosition(0, 0);
  }
}
```

**Comment by zcbenz** [comment]
Does chrome browser have this problem?

**Comment by yuya-oc** [comment]
No. I tested this problem again with Electron 1.7.4 and Chrome 59.0.3071.115.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
