### ISSUE TITLE
Images drawing badly when having environment variable LANG=pl_PL

### ISSUE THREAD

**Issue by bpasero** [electron/electron#9225]
* Electron version: 1.6.6
* Operating system: macOS 10.12.4

### Expected behavior

Images are drawing nicely.

### Actual behavior

Images are drawing badly:

![image](https://cloud.githubusercontent.com/assets/900690/25145212/d12834a4-2470-11e7-9ec1-689316c97e5d.png)

### How to reproduce

* `export LANG=pl_PL`
* `./Electron`

Reported to us via https://github.com/Microsoft/vscode/issues/24820

**Comment by patrys** [comment]
`LC_NUMERIC` is enough to reproduce so it's likely related to parsing numbers using locale-aware functions where generic ones should be used instead.

**Comment by kevinsawicki** [comment]
Sounds a bit similar to #8825

**Comment by bpasero** [comment]
Yup, looks like it is the same issue.

**Comment by bpasero** [comment]
Is this https://bugs.chromium.org/p/chromium/issues/detail?id=711683 ?

**Comment by kevinsawicki** [comment]
> Would a backport be possible?

The patch looks super small so I would think so, will queue up some libcc builds with it and verify it goes away.

**Comment by bpasero** [comment]
A workaround seems to be to set `process.env.LC_NUMERIC = 'C'` very early in the `main.js` script. I think we will go with that, given we plan a new release already next week using Electron 1.6.6.

**Comment by bpasero** [comment]
This also happens when `LC_ALL` is set, so you also need to unset `LC_ALL` if defined to not run into this issue.
