### ISSUE TITLE
OS level user defined keyboard shortcuts do not execute when Electron app is focused on macOS

### ISSUE THREAD

**Issue by ccnokes** [electron/electron#9226]
* Electron version: 1.6.2
* Operating system: macOS 10.12.4

### Expected behavior

Hotkey should execute.

### Actual behavior

Hotkey doesn't execute.

### How to reproduce

1. Go to Preferences > Keyboard > Services and change one of the service hotkeys to Ctrl+Cmd+M. (I reproduced this with Pictures > Take Screenshot service).
2. Focus Electron app
3. Execute the hotkey
4. 😢  because it doesn't work

Even if you're showing the "Services" menu (like Atom does), the hotkey doesn't work, but clicking on the menu item does (see below). 

![image](https://cloud.githubusercontent.com/assets/1610343/25151501/0e188d60-2443-11e7-8075-62d4b65a8d12.png)

Maybe this is because Electron doesn't have any kind of Services integration? I'm not sure exactly what the Services shortcuts thing does really, but I have some users that basically leverage that feature for custom, system-wide shortcuts and they get blocked from using them when our Electron app is open.

**Comment by kevinsawicki** [comment]
@ccnokes Having trouble reproducing this on 1.6.2, if I load the default Electron app and press `cmd-ctrl-m` I do see the popup and am able to take a screenshot.

I am able to reproduce this in Atom but that is still using an old Electron version, 1.3.x.

Are you able to reproduce this using the default Electron app?

**Comment by ccnokes** [comment]
Hmm I can't reproduce in the default app either. I'll have to dig around more and see what's going on. I'll reopen or open a new one then.
