### ISSUE TITLE
Electron error, cannot execute binary file

### ISSUE THREAD

**Issue by liuzhen2008** [electron/electron#9228]
`electron:stderr /Users/liuzhen/Documents/forfun/node_modules/electron/dist/electron: /Users/liuzhen/Documents/forfun/node_modules/electron/dist/electron: cannot execute binary file +0ms
`
I got this error when running the command line below on Mac.

`  electron:stderr /app/node_modules/electron/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory +0ms
`
and This error when running the command line on a ubuntu virtual box.

`DEBUG=nightmare:*,electron:*  node --harmony test.js`

test.js is as follows:

```
var Nightmare = require("nightmare"),
    nightmare = Nightmare({show: true});

nightmare
    .goto('https://duckduckgo.com')
    .type('#search_form_input_homepage', 'github nightmare')
    .click('#search_button_homepage')
    .wait('#zero_click_wrapper .c-info__title a')
    .evaluate(function () {
        console.log("diablo");
        return document.querySelector('#zero_click_wrapper .c-info__title a').href;
    })
    .end()
    .then(function(result) {
        console.log(result);
    })
    .catch(function(error) {
        console.error('Search failed:', error);
    });

```

I am using mac, 10.12.3.
NPM: 3.10.10
node: v6.9.4

**Comment by MarshallOfSound** [comment]
@liuzhen2008 This would seem to be a Nightmare issue, potentially due how they spawn Electron.  Have you raised this with them before raising here?

**Comment by liuzhen2008** [comment]
@MarshallOfSound Yes I have. I duplicated this issue on nightmare side!

**Comment by MarshallOfSound** [comment]
@liuzhen2008 These errors look like you are trying to run Nightmare on a linux server with a display.  If you are running on a server without a display you need to have `xvfb` running.

The first error looks like the electron executable doesn't have `+x` on it so can't be executed, fixing these two things should get you running

**Comment by kevinsawicki** [comment]
Closing this out, thanks @MarshallOfSound for helping out 👍
