### ISSUE TITLE
navigator.storage.persist() not working

### ISSUE THREAD

**Issue by andymartinwork** [electron/electron#9229]
* Electron version: 1.6.1
* Operating system: OSX

Only tested in a webview so far.

### Expected behavior

Chrome clears local storage [under storage pressure](https://developers.google.com/web/updates/2016/06/persistent-storage). I'm not sure if Electron does this as there seems to be no documentation about it. A new API has been released which will make the contents of local storage persistent.

### Actual behavior

When running `navigator.storage.persist();`, nothing seems to happen.

### How to reproduce

Run these to see how much of your site is in temporary storage (which may be cleared in low disk space situations if Electron works like Chrome):

```
navigator.webkitTemporaryStorage.queryUsageAndQuota ( 
    function(usedBytes, grantedBytes) {  
        console.log('we are using ', usedBytes, ' of ', grantedBytes, 'bytes');
    }, 
    function(e) { console.log('Error', e);  }
);

navigator.webkitPersistentStorage.queryUsageAndQuota ( 
    function(usedBytes, grantedBytes) {  
        console.log('we are using ', usedBytes, ' of ', grantedBytes, 'bytes');
    }, 
    function(e) { console.log('Error', e);  }
);
```

Now run this to try to persist the site contents:

```
navigator.storage.persist();
```

Note that the quotas are the same as before, with everything in temporary storage.
However, running this code seems to indicate that the storage is persistent:

```
if (navigator.storage && navigator.storage.persist) 
  navigator.storage.persisted().then(persistent=>{
    if (persistent)
      console.log("Storage will not be cleared except by explicit user action");
    else
      console.log("Storage may be cleared by the UA under storage pressure.");
  });
```

So what is the truth? Is the storage persistent or not?

**Comment by deepak1556** [comment]
> When running navigator.storage.persist();, nothing seems to happen.

Can you expand on what you expect to happen ? 

> Note that the quotas are the same as before, with everything in temporary storage.

The spec doesn't state that quotas have to be increased when a storage has been made persistent, its just the storage will not be evicted unless there is an action performed by user explicitly. 

> So what is the truth? Is the storage persistent or not?

Yes by default all origins in Electron are granted durable storage, so they are not evicted automatically under storage pressure.

**Comment by andymartinwork** [comment]
>Can you expand on what you expect to happen ?

I would expect the `navigator.webkitTemporaryStorage.` to report zero, and the `navigator.webkitPersistentStorage` to report the size of the stored data.

>The spec doesn't state that quotas have to be increased when a storage has been made persistent

The quota is already the entirety of my drive's free space, I just thought it would move from "temporary" to "persistent".

>Yes by default all origins in Electron are granted durable storage, so they are not evicted automatically under storage pressure.

If you're sure about this, then there should be no issue.

**Comment by deepak1556** [comment]
> I would expect the navigator.webkitTemporaryStorage. to report zero, and the navigator.webkitPersistentStorage to report the size of the stored data.

I believe its mostly because we grant unlimited storage by default to all origins. Anyway those apis are going away soon after `navigator.storage.estimate` becomes stable https://storage.spec.whatwg.org/ .

> If you're sure about this, then there should be no issue. I just wonder why navigator.webkitPersistentStorage is telling me otherwise.

Yes I am sure, if it doesn't work then its definitely a bug. There is no easy way to test on user land, I can only verify that the origins storage are not evicted following chrome's policy similar to https://cs.chromium.org/chromium/src/storage/browser/quota/quota_database_unittest.cc?l=146

**Comment by andymartinwork** [comment]
Thanks for explaining how Electron behaves. I feel a lot happier about our local storage now.

I'll see if I can force my computer to zero disk space to test, and if there's a problem I will reopen.

**Comment by vuamitom** [comment]
I'm facing similar issue. Chrome wipe out indexeddb data under storage pressure. Event though `navigator.storage.persist` callback returns a value of 'persisted'. Probably the persistent option is currently only applicable to Cache API storage. Is there any ticket that I can track progress of persistent Indexeddb?

**Comment by inexorabletash** [comment]
I don't know how Electron modifies the behavior of storage systems and the interaction with quota. In Chrome itself, though: when an origin has the "persistent" permission (`navigator.storage.persisted()` resolves to `true`) then that origin is exempt from storage pressure; this affects all storage APIs managed by storage (AppCache, Cache API, IndexedDB, Service Worker, WebSQL, FileSystem).

And re: previous questions: the `navigator.webkitPersistentStorage()` is an obsolete mechanism that applies only to the (Chrome-only) FileSystem API. You can think of there being two "boxes" of storage per origin in Chrome. The first box is the normal one where all storage APIs listed above dump their data, which is managed by quota, and which can be observed/modified by `navigator.storage.estimate()`/`persist()`/`persisted()` (see [spec](https://storage.spec.whatwg.org)); this box can be "best effort" or "persistent" depending on the permission granted by the browser, and behaves similarly to other browsers. The second box is available only on request, can optionally - but only - used by the FileSystem API, has quota limits but is not subject to eviction, and is not present in other browsers. For historical reasons, the first box is called "temporary" in the Chrome-only APIs that talk to it and the second is called "persistent", even though the first box can now be granted "persistent" permission.

Again, this applies to the browser's behavior; I'm not sure what Electron may modify/enforce/allow here.
