### ISSUE TITLE
rel="noopener" crashes app on preventing 'new-window' event

### ISSUE THREAD

**Issue by rhysd** [electron/electron#9230]
* Electron version: 1.6.7-beta
* Operating system: Windows 8.1 (but Windows 10 also reproduce this)

### Expected behavior

Prevent event properly

### Actual behavior

App crashes

### How to reproduce

I created a small app which can reproduce this bug.

https://gist.github.com/rhysd/1dcf61cf42b822e2044372e353d3519f

1. Download electron-v1.6.7-win32-x64.zip and unarchive it
2. Create `app` in `resources` directory
3. Copy all files from the Gist URL into the `app` directory
4. Double click electron.exe
5. Click 'link' in window
6. 'App crashed' dialog will be shown

I confirmed that this bug also occurs with Electron v1.6.2 and v1.6.5

**Comment by rhysd** [comment]
I also confirmed removing `rel="noopener"` does not make app crash.

**Comment by rhysd** [comment]
Some people reported this issue occurs also in Linux. And I could reproduce this bug with Ubuntu 16.04.

**Comment by deepak1556** [comment]
Thanks for the sample app, I am able to reproduce the crash. https://github.com/electron/electron/pull/9113 should fix this.
