### ISSUE TITLE
WebContents#insertCSS does not work when 'sandbox: true'

### ISSUE THREAD

**Issue by rhysd** [electron/electron#9232]
* Electron version: 1.6.7-beta
* Operating system: macOS 10.12

### Expected behavior

CSS inserted with `insertCSS` should be reflected

### Actual behavior

CSS inserted with `insertCSS` is not reflected

### How to reproduce

I made a small app for this issue in Gist.

https://gist.github.com/rhysd/68e3006d3c192faea22bb6e5106c81c5

1. Download and unarchive the Gist
2. Enter the unarchived directory and run `npm install`
3. Run `./node_modules/.bin/electron .`
4. Text in `<body>` is not red (CSS was not inserted).

**Comment by rhysd** [comment]
If `sandbox: true` is not set, inserted CSS is reflected. So this behavior may be intentional.

**Comment by zcbenz** [comment]
I'm merging this to #9073 since they are essentially the same bug.

**Comment by dusansimic** [comment]
@zcbenz, the issue you mentioned about `webContents.executeJavaScript()` function and it was fixed, but function `webContents.insertCSS()` still doesn't work. So this issue is still not resolved.

**Comment by nornagon** [comment]
@dusansimic, this issue is resolved in master but it looks like the fix didn't make it to 2.0.x. I've opened a PR to backport it: https://github.com/electron/electron/pull/13076
