### ISSUE TITLE
scrollBounce only bounces once for <webview>s

### ISSUE THREAD

**Issue by javan** [electron/electron#9233]
* Electron version: 1.6.7
* Operating system: macOS 10.12.4

https://github.com/electron/electron/pull/9134 restored the `scrollBounce` preference (🎉), but it seems to only work *once* for `<webview>`s. Works ∞ times for browser windows. :)

![scroll-bounce-once](https://cloud.githubusercontent.com/assets/5355/25193142/070ca2f6-2504-11e7-9927-c4abdb720609.gif)

To reproduce, apply these changes to the electron-quick-start app:
```diff
diff --git a/index.html b/index.html
index d9161f3..03f0b32 100644
--- a/index.html
+++ b/index.html
@@ -10,6 +10,8 @@
     We are using Node.js <script>document.write(process.versions.node)</script>,
     Chromium <script>document.write(process.versions.chrome)</script>,
     and Electron <script>document.write(process.versions.electron)</script>.
+
+    <webview src="https://github.com" webpreferences="scrollBounce" style="width:760px; height: 400px;"></webview>
   </body>
 
   <script>
diff --git a/package.json b/package.json
index 845fe01..27a55a0 100644
--- a/package.json
+++ b/package.json
@@ -17,6 +17,6 @@
   "author": "GitHub",
   "license": "CC0-1.0",
   "devDependencies": {
-    "electron": "~1.6.2"
+    "electron": "1.6.7"
   }
 }
```

/cc @kevinsawicki

**Comment by kevinsawicki** [comment]
Weird, not sure why this is happening, can reproduce.

**Comment by javan** [comment]
Quick update: This issue is still present in Electron 1.7 and 1.8.

**Comment by steverandy** [comment]
I've just tried v2.0.0-beta.3 and the scrollBounce now works as expected for webview.

**Comment by codebytere** [comment]
Seems like this is fixed, closing it out!

**Comment by steverandy** [comment]
@codebytere seems there is a regression on Electron v3.0.2.
The scroll bounce only works once for the webview.
