### ISSUE TITLE
Help needed with box notifications

### ISSUE THREAD

**Issue by DracotMolver** [electron/electron#9234]
* Electron version: 1.6.5
* Operating system: Windows 10

Hi there. Well, this is not an issue. I was just wondering if there's a way to the the example of the image using electron or something else. I'd like to manage some features of my app in a similar way. And if also this can be accomplish for linux like the control MPRIS and for Mac.  Any help, thanks :).

![ejemplo_win](https://cloud.githubusercontent.com/assets/13334764/25201891/c6513184-2529-11e7-8ec3-ccfc037abcec.gif)

**Comment by MarshallOfSound** [comment]
That box is created the the windows media transport controls.

You can use the @noderrt modules on NPM to use the correct APIs to make this appear.  Be warned you should only use it as a media player or people get mad.  😆 

My implementation can be seen here https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/baa6647e724d9d901180e04ba1ef0ed09d62ef8e/src/renderer/windows/GPMWebView/playback/systemMediaService/win10.js

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by DracotMolver** [comment]
Thanks a lot for this 😄
