### ISSUE TITLE
Feature Request: WebAssembly Support

### ISSUE THREAD

**Issue by vossad01** [electron/electron#9235]
### Expected behavior

WebAssembly modules loaded in either any electron context (ex, server process or render process) are usable within Electron.

### Actual behavior

WebAssembly modules fail to load/run.

### How to reproduce

* [This repository provides a simple test](https://github.com/vossad01/electron-webassembly-hello) and derives from the [WebAssembly.org Developer's Guide](http://webassembly.org/getting-started/developers-guide/).  If I remember to, I will try to add a WebAssembly call in the `main.js` as well, but right now I don't have a nodejs version compatible with the binary version of any of my wasm files to verify I wire things together correctly.
* [This repository contains the tank demo minimally packaged for electron](https://github.com/vossad01/electron-webassembly-tank-demo).  [The live version of the tank demo can be found here](http://webassembly.org/demo/Tanks/).

### Details

The dependency versions currently included electron support behind flags.  `--expose-wasm` for nodejs and `--enable-webassembly` for chromium.  In theory, web assembly support could be enabled in electron now by respecting/exposing these flags.

However, it will be less of a moving target if this waits until electron updates to [Node.js v8.0](https://github.com/nodejs/node/pull/11752) and [Chrome[ium] 57](https://www.chromestatus.com/feature/5453022515691520).  Since [WebAssembly has achieved cross-browser consensus/minimum viable product](http://webassembly.org/roadmap/#changes-since-the-browser-preview), things are converging on the `0x1` version of the binary format, and supporting it in electron with the current dependency versions would probably lead to frustration and [version mismatches](http://stackoverflow.com/q/43503981/1072626).

Since both Chrome 57 and Node 8 will expose WebAssembly without a flag, _in theory_ this will just work once electron updates its dependencies, but it would still be good to confirm.

#### Related
#6539 First raised the question of whether WebAssembly was supported in electron and has some discussion concerning the chromium flag.
https://github.com/electron/electron/issues/7395#issuecomment-295324915 Requests the chromium flag be respected to enable WebAssembly with the current dependency.
#8993 Tracks the update to Chromium 57 (or 58)

**Comment by ramirezd42** [comment]
@vossad01 https://github.com/vossad01/electron-webassembly-hello/pull/1 Got your example working and submitted a pull request! 

Just had to upgrade electron to 1.7 and register the "file" url scheme as privileged to allow the wasm file to be loaded via fetch.

**Comment by vossad01** [comment]
@ramirezd42 Thanks!  That was my finding earlier today as well.  Per #3922, I'm not sure if changing file to be privileged should be needed.  I'm waiting to see if anyone responds to the old issue before opening a new one.

**Comment by kevinsawicki** [comment]
So should this issue be closed now that Electron supports Chrome 58 or are there other changes needed in Electron for this to be supported?

**Comment by vossad01** [comment]
@kevinsawicki It is a somewhat tangential issue, but my opinion is that other changes are desired before this is closed.  Specifically, #9474.

The WebAssembly piece is functional.  You can test yourself with the [tank demo](https://github.com/vossad01/electron-webassembly-tank-demo), However, because of #9474, the [other demo originally presented](https://github.com/vossad01/electron-webassembly-hello) does not work unmodified.  A user wishing to use WebAssembly must work around the issue; by either modifying the generated bootstrap code to use XMLHttpRequest, or by changing scheme privileged with electron.  Since that utilizes the default bootstrap generated by emscripten, this issue is likely to be encountered by users.

I don't know if anyone would take it up, but I suppose there could also be the question of whether any tests should be added demonstrating WebAssembly works so it  would be less likely to break on a future update.

**Comment by vossad01** [comment]
@kevinsawicki #9474 is only going to be a documentation task for the time being, so unless tests need to be added, this can be closed for working as of 1.7.0.

**Comment by crossle** [comment]
Fetch API can not load app://./xxx.wasm. URL schema "app" it not supported.

How to resolve?

**Comment by camhart** [comment]
@crossle did you figure that out?  I'm looking for an answer too.
