### ISSUE TITLE
Selecting multiple files dialog box is not working in OSX

### ISSUE THREAD

**Issue by pkgajulapalli** [electron/electron#9245]
I'am able to select multiple files from the dialog box in Ubuntu. But the same code is not working in OSX.

**Comment by kevinsawicki** [comment]
@pkgajulapalli can you provide the code you are running and the version of macOS you are on?

This is the code I tried on 10.12.4 and I was able to select multiple items:

```js
const {dialog} = require('electron')
console.log(dialog.showOpenDialog({properties: ['openFile', 'openDirectory', 'multiSelections']}))
```

**Comment by pkgajulapalli** [comment]
@kevinsawicki  Thank you. Your code worked for me.
