### ISSUE TITLE
Get fine-grain locale information

### ISSUE THREAD

**Issue by joshaber** [electron/electron#9247]
`app.getLocale` exists, but locale has more nuance than a single setting.

For example, an international user could have `en-US` as their language but a localized numeric setting. It'd be great if Electron could expose those.

https://bugs.chromium.org/p/chromium/issues/detail?id=120473 and https://bugs.chromium.org/p/chromium/issues/detail?id=33413 seem to be relevant Chromium bugs.

**Comment by bundyo** [comment]
I can relate to that - the difference in locale and formats is very common in the non-English countries.

**Comment by iAmWillShepherd** [comment]
👋 

Curious if any progress on this issue has been made?

**Comment by zeke** [comment]
@iAmWillShepherd not that I know of, but here are a few related things that have landed since this was opened:

- https://github.com/electron/electron/pull/12967
- https://github.com/electron/electron/pull/11469
- https://github.com/electron/electron/pull/12419

**Comment by shiftkey** [comment]
I'll also cross-reference the new TC39 discussion about this https://github.com/tc39/ecma402/issues/257

**Comment by codebytere** [comment]
Closing this for now as it's not possible at present per Chromium's roadmapping nor does it seem to be something they're planning to address anytime soon. Should something change, we can definitely look back into implementing this downstream once it becomes available or enters consideration upstream.
