### ISSUE TITLE
Redirect in WebView causes any new WebViews to not render.

### ISSUE THREAD

**Issue by JOT85** [electron/electron#9251]
I have tested this is both electron 1.6.2 and 1.6.5, both of them having the same problem.
I have tried it on Windows 10 (creators update just installed) x64, Linux x64 (Debian Jessie) and Linux armv7l (raspberry pi 3, Raspbian).
This is only a problem on Linux x64 out of the ones I tested, both windows x64 and Linux arm worked as expected, however with Linux x64 I had the issue I will describe.
I was running on Debian Jessie.

If you open this in a browser window:
```
<html>
<head>
<title>
WebView test
</title>
</head>
<body>
	<div ID="views"></div>
	<style>
		
		html,body {
			
			margin: 0px;
			padding: 0px;
			background-color: #333;
			
		}
		
		#views {
			
			position: absolute;
			height: 100vh;
			width: 100vw;
			top: 0px;
			left: 0px;
			z-index: 500;
			
		}
		
		.view {
			
			display: flex;
			width: 100%;
			height: 100%;
			position: absolute;
			top: 0px;
			left: 0px;
			background-color: white;
			
		}
		
	</style>
	<script type="text/javascript">
		
		let views = document.getElementById("views") ;
		
		function newView(url) {
			
			let view = document.createElement("webview") ;
			view.partition = "persist:test" ;
			view.autosize = true ;
			view.plugins = true ;
			//view.addEventListener("new-window",e=>newView(e.url)) ;
			view.classList.add("view") ;
			views.appendChild(view) ;
			view.src = url ;
			
		}
		
		newView("https://www.google.co.uk/") ;
		
	</script>
</body>
</html>

```
And try doing something that involves redirects, for example logging in to google (via gmail fails every time), or going to a link that redirects you, such as one of the latest Node Weekly E Mail newsletter (how I discovered the issue), around 90% of the time the WebView will stop rendering, however all the events are fires, page title updates etc, the cursor will change & links are clickable - yet the WebView appears blank.
Also, any other WebViews that are created after this will never start to render however will allow clicks etc. If you inspect any of these WebViews there are no errors and they are loaded, you just can't see them.
It might not be the redirecting however from the rather extensive testing I have done that appears to be the problem. I have also attempted to figure out the cause however was unsuccessful (I'm not quite that good :( ).

I have uploaded a zip which contains an app directory that will allow you to recreate the issue.
[app.zip](https://github.com/electron/electron/files/947974/app.zip)

I hope this helps and I really need a fix for my personal project :(
Thanks,
Jacob

**Comment by zcbenz** [comment]
Looks like a bug of GPU rendering, you may try using Electron with GPU acceleration disabled.

I'm closing this since none of us in Electron team is familiar with Chromium's GPU rendering enough to be able to fix bugs with GPU rendering, you may have to wait for a Chrome upgrade to fix this.
