### ISSUE TITLE
Fatal error, cant open .url files with all files filter

### ISSUE THREAD

**Issue by Brain-Gamer** [electron/electron#9259]
I am trying to open the game shortcuts from steam with electons showOpenDialog function.
When you have the ``All Files [*.*]`` filter and try to open a `.url` file, it wont work.
If you do the exact same thing with a filter for ``.url`` endings it works fine.

* Electron version: v1.6.5
* Operating system: Windows 10

### Expected behavior

Open any files selected

### Actual behavior

Only works with special filter for `.url` files
With `*.*` filter a error message gets displayed: `{filename} Fatal error`

### How to reproduce

> $ git clone https://github.com/Brain-Gamer/electron-quick-start.git
> $ electron .

Then follow the instructions in the fork to reproduce the issue

**Comment by kevinsawicki** [comment]
> With *.* filter a error message gets displayed: {filename} Fatal error

I see a slightly different error:

<img width="380" alt="screen shot 2017-04-25 at 4 50 02 pm" src="https://cloud.githubusercontent.com/assets/671378/25412401/42d07a6a-29d7-11e7-841a-72ec4736949f.png">

But I also see that same dialog if I try to open the file in others apps like Chrome or Notepad.

Can you try opening it from the open dialog in those apps?

**Comment by Brain-Gamer** [comment]
The different error message is probably because I tried to translate it (my system language is german).
![image](https://cloud.githubusercontent.com/assets/17144010/25449030/c52f2cde-2aba-11e7-94bd-2b79dda2afff.png)
And you are right. If I try to open it in nodepad++ it wont work. Seems like its more a windos issue then?
But I can edit the file in atom (when opening the complete folder). 
![image](https://cloud.githubusercontent.com/assets/17144010/25448941/773351e0-2aba-11e7-96c6-27262e95315b.png)
So it's just the selection and not the file itself that causes this issue.

**Comment by kevinsawicki** [comment]
> Seems like its more a windows issue then?

Yeah, it does seem like a windows dialog issue so I don't think this is something we can address directly in Electron so I'm going to close this issue out.

Might be worth reporting to Windows support and see if they suggest any possible workarounds.
