### ISSUE TITLE
Rpi with Raspbian (Jessie) Silent Print

### ISSUE THREAD

**Issue by burak1489** [electron/electron#9260]
Hi guys,

i started with electron a few days ago. I use the latest version on Rpi with Raspbian (Jessie) installed.

I wanted to try out the silent printing mode. I tried to activate it with "silent: true". I wasn't able to print without the dialog in the webview and as well in the main.js itself.

Can u help me with this issue?

**Comment by kevinsawicki** [comment]
@burak1489 can you include a code snippet of how you are using the API?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
