### ISSUE TITLE
clipboard.readImage() error on the one png image.

### ISSUE THREAD

**Issue by simpzan** [electron/electron#9264]
* Electron version: v1.3.15

* Operating system: Mac 10.11.6 (15G1217)

### Expected behavior

No error log, and the output image should be same copy of the source image.

### Actual behavior

Error log, the output image is far from the same copy of the source image.

### How to reproduce

<img width="536" alt="font" src="https://cloud.githubusercontent.com/assets/366578/25311447/c802fafa-2833-11e7-8d5c-d276b3b65725.png">
I copied this image file in Finder. then I run `electron index.js` to read and write image. This is the index.js file.

```js
const {clipboard} = require('electron')
const fs = require("fs")

const image = clipboard.readImage()
console.info("image", image, image.getSize())
fs.writeFileSync("test.png", image.toPNG());
```

I got this output.

```
Apr 23 14:47:00  Electron[24132] <Error>: CGBitmapContextCreate: unsupported parameter combination: set CGBITMAP_CONTEXT_LOG_ERRORS environmental variable to see the details
Apr 23 14:47:00  Electron[24132] <Error>: CGContextGetType: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
2017-04-23 14:47:00.077 Electron[24132:1353852] It does not make sense to draw an image when [NSGraphicsContext currentContext] is nil.  This is a programming error. Break on void _NSWarnForDrawingImageWithNoCurrentContext() to debug.  This will be logged only once.  This may break in the future.
image NativeImage {} { width: 535, height: 309 }
```

And this is the output image.
![test](https://cloud.githubusercontent.com/assets/366578/25311489/d7475104-2834-11e7-8057-1068c07a7743.png)

**Comment by kevinsawicki** [comment]
> Electron version: v1.3.15

Can you try this on Electron 1.6.7+? I'm having trouble reproducing this on the latest version. It may have been fixed by changes in Chrome.

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.

**Comment by simpzan** [comment]
@kevinsawicki I just tried this on 1.6.10. It is truly fixed. Thanks!
