### ISSUE TITLE
Windows Tray and Toolbars 

### ISSUE THREAD

**Issue by tolgaergin** [electron/electron#9267]
I created an application for Mac users. It shows some currencies that you select in the menu bar. 

When I tested on Windows and used the same way (NativeImage -> Tray) I think Windows forces the image to square shape while showing in the tray bar.

I'm not a Windows user for years. Is it possible to show NativeImage in a rectangle shape in Windows tray bar. I only tested on Windows 7. I'm not sure that Windows may not limit the shape of Tray icon in some versions. 

![Mammon app on Mac](https://teamfox.co/mammon/intro/mammon.png)

Alternatively, there is a space before tray bar which is called Toolbars. Here is an example toolbar usage by the BatteryBar application. It is possible to reach the Toolbars by Electron API.

![BatteryBar on Windows Toolbar](http://1.bp.blogspot.com/-YIPTjjmzAaM/Ubh93QcEOrI/AAAAAAAABCA/YdKHBJwsihg/s1600/BatteryBar1.jpg)

* Electron version: 1.6.7
* Operating system: Windows

### Expected behavior

Showing custom size image in tray bar on Windows.

### Actual behavior

It forces image to square shape.

### How to reproduce

Maybe, finding a way add applications in Toolbars.

![Windows Toolbars](https://www.tenforums.com/attachments/tutorials/14308d1485950093-add-remove-quick-launch-toolbar-windows-10-a-quick_launch-1.png)

**Comment by zcbenz** [comment]
Icons in notification area can only show as squared since it is a limitation of Windows, to implement what you want we have to introduce a whole new set of API to create taskbar toolbars, which I think is beyond Electron's scope.

For your case I suggest writing a native module to create taskbar toolbars.
