### ISSUE TITLE
API to get dock icon position

### ISSUE THREAD

**Issue by shellscape** [electron/electron#9268]
While I'm not an Objective-C developer, I did some digging on the webs and it looks like getting the coordinates/position of the Dock Icon for a particular app is possible. Please see [this response](http://stackoverflow.com/a/6684646/416845) and the [subsequent comment](http://stackoverflow.com/questions/6684278/getting-the-position-of-my-applications-dock-icon-using-cocoas-accessibility-a#comment7930301_6684646) with an update to the method. I verified [here](https://developer.apple.com/reference/appkit/nsrunningapplication) that the API still exists and is valid, and the method appears to be sound still.

I investigated using various plists on the machine to determine dock icon size (which doesn't appear to be possible anymore) and the index of a dock icon, but unfortunately that's not possible unless the app has been pinned to the dock.

I think that would add significant benefit for developers if that info was available to `app.dock`. My particular use case is that I'm rewriting an old app I wrote for windows which makes use of taskbar window thumbnail grouping, something I'm duplicating using a BrowserWindow, but I have no way of knowing how to align the window as I don't have access to the location of the dock icon. At the moment I can only query `defaults read com.apple.dock` through the shell to glean the position of the dock on the screen, which unfortunately isn't specific enough for my window alignment needs.

* Electron version: 1.6.5
* Operating system: MacOS 10.12.4

### Expected behavior

n/a

### Actual behavior

n/a

### How to reproduce

n/a

**Comment by sumedhguha** [comment]
Python seems to have more capabilities when it comes to getting information and tweaking the dock, try to see what this guy has done: 
https://github.com/kcrawford/dockutil/blob/master/README.md

**Comment by deezy136** [comment]
Can I work on this please

**Comment by yagnyaPatel** [comment]
Hey, I'd like to work on this. This would be my first PR.

**Comment by miniak** [comment]
Considering that there is no public API to get this information, I don't think this should be expose as a core Electron API. You can always create a native node module with this functionality.

**Comment by miniak** [comment]
You are always welcome to create a PR in case you manage to implement it in a reasonable way that could be considered being added to Electron core.
