### ISSUE TITLE
Removing menu items

### ISSUE THREAD

**Issue by iamdriz** [electron/electron#927]
Apologies if I have missed this in the docs, but when running the app on OS X I have the following menu items shown in the menu bar:

File
Edit
Format
View
Window
Help

However I don't want some of those to appear... e.g. the View menu with options to reload the page and show the developer tools... How do I remove them?

**Comment by kakyoism** [comment]
What if I want to remove a single item form the default menu?
I've tried various ways and none worked for me, such as this

```
    var menu = Menu.getApplicationMenu();
    for(var i=0; i<menu.items.length; i++) {
        var role = menu.items[i].role;
        console.log(`menu.role: ${role}`);
        if(role == 'help') {
            menu.items.splice(i, 1);
            console.log('remove help');
            break;
        }
    };
    var items = menu.items;
    for(var i=0; i<menu.items.length; i++) {
        var role = menu.items[i].role;
        console.log(`menu.role: ${role}`);
    };
    Menu.setApplicationMenu(menu);
```

After relaunching the app, the help menu is still here.

**Comment by tylerlong** [comment]
Deleting a single item directly simply won't work.  

That's why I created this project: https://github.com/tylerlong/electron-application-menu-template
You create a brand new menu template, delete the target menu item, then recreate a new menu.
