### ISSUE TITLE
cookies.get() value is decoded, but cookies.set() value will not be encoded automatically.

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#9270]
cookies.get() value is decoded automatically, so I think cookies.set() value should be encoded automatically, or cookies.get() value should not be decoded.

for example:

cookie raw value (from http response headers):   
`set-cookie: test=x%3B%20y%3B; ......`

### Actual behavior

```
//get cookie
session.defaultSession.cookies.get({url: 'http://domain', name:'test'}, (error, cookies) => {
  console.log(cookies[0].value == 'x%3B%20y%3B');  //false
  console.log(cookies[0].value == 'x; y;');  //true
})

//set cookie failed
session.defaultSession.cookies.set({url: 'http://domain', name:'test', value:'x; y;'}, (error) => {
  console.log(error);  //"Error: Setting cookie failed"
})

//set cookie success
session.defaultSession.cookies.set({url: 'http://domain', name:'test', value: encodeURIComponent('x; y;')}, (error) => {
  console.log(error);  //null
})
```

### Expected behavior

cookies.get() and cookies.set()  should have unified behaviour.
get `'x%3B%20y%3B'` and set `'x%3B%20y%3B'`, otherwise get `'x; y;'` and set `'x; y;'`

**Comment by deepak1556** [comment]
It is not required by the RFC to encode the values by default. We can follow the behavior of chrome to parse till the first terminator `'x; y;' -> 'x;'`. Also `cookie.get` values aren't decoded by default, with your example I get `x%3B%20y%3B`.

Related links:
* https://cs.chromium.org/chromium/src/net/cookies/parsed_cookie_unittest.cc?l=46
* https://bugs.webkit.org/show_bug.cgi?id=16699
* https://bugs.chromium.org/p/chromium/issues/detail?id=12361

**Comment by html5gamer** [comment]
As my testing on electron 1.6.3+,  cookies.get() value is same as cookies.set(). I will do further testing with other versions.

**Comment by zcbenz** [comment]
I can also confirm in 1.7.x that `cookies.get` behaves the same with `cookies.set`, I didn't test other versions though.

Closing since it is no longer an issue.
