### ISSUE TITLE
event.preventDefault() doesn't work in 'new-window' event

### ISSUE THREAD

**Issue by zetsin** [electron/electron#9271]
* Electron version: 1.6.5
* Operating system: macOS 10.12.3

### Expected behavior

Calling event.preventDefault() will prevent Electron from automatically creating a new BrowserWindow.

### Actual behavior

A new BrowserWindow will be created as usual.

### How to reproduce

In renderer process:
```js
let electron = require('electron')
let win = electron.remote.getCurrentWindow()

win.webContents.on('new-window', (event, url) => {
  console.log(url)
  event.preventDefault()
})
```

**Comment by enlight** [comment]
This is expected behavior, you need to assign the callback in the main process in order for `event.preventDefault()`to have the desired effect. See https://github.com/electron/electron/issues/2770#issuecomment-140065309 for details.
