### ISSUE TITLE
Option for sheet-less modal dialogs/windows in OSX

### ISSUE THREAD

**Issue by xaviergonz** [electron/electron#9272]
* Electron version: 1.6.6
* Operating system: OSX 10.12.4 (Sierra)

Sometimes showing a modal dialog/window in a sheet is desirable in OSX, but sometimes it is not (for example showing a custom frameless window that blocks the parent (modal) such as a custom message box for a game, a login window, etc)

The suggestion is to add to BrowserWindow an option called ```sheetModal: true/false``` that defaults to true, as well as to the dialog calls (showOpenDialog, etc.)

And whenever this option is set to false it won't use a sheet to present them.

**Comment by codebytere** [comment]
Given that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!
