### ISSUE TITLE
Symbol not found when using v8::internal functions from C++ Node addon

### ISSUE THREAD

**Issue by JoseExposito** [electron/electron#9275]
* Electron version: 1.6.5
* Operating system: macOS 10.11.6 El Capitán

Hi all,

I'm not sure if this is the right place to ask, but I hope someone can help me.

I'm developing a Node.js C++ addon that allows you to "compile you JS code" (i.e., use v8 caches) so you can distribute it without sources.
At the moment works on Node.js but I'm trying to get it working with Electron as well before publishing it. 

In order to archive this, I need to use some v8 internal functions, so at compile time I download the v8 source code and reference it in the "include_dirs" section of my gyp file.

In Node.js I can use without any problem the functions in the v8::internal namespace, however, when loading it with Electron I'm getting a "Symbol not found. Expected in: flat namespace" error.

Checking how Electron is compiled, I saw that it builds Node as a shared library and I guess that's the problem -the internal symbols are not exported-.

Is compiling Electron with Node/v8 as a static library the only solution? Is this even possible?
Or does someone know a way to workaround this limitation?

Ideally, I'd like to avoid to patch Electron as I archived with Node so the addon is easy to use.

I hope someone with a better knowledge of how Electron is built can help me to fix this,
Jose

**Comment by TimNZ** [comment]
@JoseExposito  Please update this issue when you've released

**Comment by JoseExposito** [comment]
@TimNZ You can find the source code here:
https://github.com/JoseExposito/v8-compiler

It is on npm, but I didn't have time to add node-pre-gyp stuff, so better clone and download it as explained in the documentation. Have a look to the examples folder to see how it works... But I don't recommend you to use it in production yet, it is still in beta.

**Comment by kevinsawicki** [comment]
> Symbol not found. Expected in: flat namespace

Which symbol is it complaining about?

**Comment by JoseExposito** [comment]
Hi @kevinsawicki 

Thank you very much for your answer. 

The addon compiles without problems, the error happens at run time:

```
$ electron bin/v8-compiler.js compile --in electron-quick-start/build/bundle.js --out electron-quick-start/build/electron-quick-start.jsc
App threw an error during load
Error: dlopen(/Users/jose/Devel/v8-compiler/build/Release/v8-compiler.node, 1): Symbol not found: __ZTVN2v88internal12DeserializerE
  Referenced from: /Users/jose/Devel/v8-compiler/build/Release/v8-compiler.node
  Expected in: flat namespace
 in /Users/jose/Devel/v8-compiler/build/Release/v8-compiler.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jose/Devel/v8-compiler/bin/v8-compiler.js:22:18)
    at Object.<anonymous> (/Users/jose/Devel/v8-compiler/bin/v8-compiler.js:69:3)
```

This symbol is:

```
$ c++filt __ZTVN2v88internal12DeserializerE
vtable for v8::internal::Deserializer
```

It complains about that symbol because it is the first one the addon tries to use, but if I remove it, it will complain about any other symbols in the v8::internal namespace.

Thank you very much in advance,
Jose

**Comment by kevinsawicki** [comment]
> Is compiling Electron with Node/v8 as a static library the only solution? Is this even possible?
Or does someone know a way to workaround this limitation?

I'm guessing the fix here will be exporting these symbols through Electron somehow, v8 is built in Electron through Chromium and these symbols are probably stripped/not included currently.

**Comment by JoseExposito** [comment]
Yes, that'd be the ideal solution. I found this post and it looks like `chromiumcontent.gypi` is the file I'm looking for:
https://electron.atom.io/blog/2016/08/08/electron-internals-using-node-as-a-library

This weekend, I'll try to compile Electron with those symbols enabled, hopefully that'll fix my problems.
Could Electron be interested in merging this patch into master?

**Comment by kevinsawicki** [comment]
> Could Electron be interested in merging this patch into master?

Yeah, would definitely be interesting to see what you find out, I imagine the only major concern with shipping these symbols would be an increased binary size.

**Comment by TimNZ** [comment]
BTW https://twitter.com/zeithq/status/858385347377455105

**Comment by JoseExposito** [comment]
@TimNZ It looks like an open source fork of enclosejs.com. I started v8-compiler because Enclose was closed source and for some users and/or customers applying unknown patches to Node.js is just not acceptable.
I'm very happy to see that they decided to make it open source, even thought if that means that v8-compiler doesn't make sense any more.

@kevinsawicki After many tests this weekend -Chromium takes a *long* time to compile in my old laptop- and trying to change the visibility in the GN configuration, my conclusion is that it's not possible to do it that way.

A solution could be patching v8 to use V8_EXPORT (https://github.com/v8/v8/blob/master/include/v8.h#L51) in the classes we want to make available from the outside... But patching doesn't look ideal.

Other solution could be compile the C++ addon as part of Node: ["Embedding a native module" section]

http://www.jedi.be/blog/2013/05/14/Compiling%20-%20packaging%20a%20nodejs%20project%20as%20a%20single%20binary/

If the Electron team is interested in this feature, I believe this is the right way. Just a couple of extra APIs in libnode and a well integrated JS command line tool rather than a third-party plugin+patches... But it is up to you.

**Comment by levrik** [comment]
@JoseExposito Yep if you look at the commits of pkg it's the same guy who created enclose.js

**Comment by TheWailingLou** [comment]
I'm fairly new to cpp and node-gyp so I'm not sure this is fully related, but because I get a very similar error perhaps it's worth mentioning:

`Uncaught Error: dlopen(/Users/louis/Music_Maker/soundGenerator/build/Release/soundGen.node, 1): Symbol not found: __ZN11audio_setup15Get_Sample_RateERKN2v820FunctionCallbackInfoINS0_5ValueEEE
  Referenced from: /Users/louis/Music_Maker/soundGenerator/build/Release/soundGen.node
  Expected in: flat namespace
 in /Users/louis/Music_Maker/soundGenerator/build/Release/soundGen.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)`

It compiles with no errors. 

The thing that's odd is that in my main file if I change my #include statements to reference my source code instead of the corresponding header file, the error goes away and runs in electron just fine. It's only in the main file though. In other files I include via the header, and have no problems. I've triple checked my headers and source code and I can't see any reason why it would be happening.

Anyway, not sure if this is related to the v8::internal namespace or if it's a separate issue entirely, but maybe someone more knowledgeable can gleam something from it.

**Comment by zcbenz** [comment]
A proper fix would be patching libcc to expose V8's symbols by default.

**Comment by divan** [comment]
Any good explanation of the nature of this error?

I'm getting exactly the same error simply calling a C++ addon's function from JS using node.js. Also have the same odd behaviour with headers as @TheWailingLou — when I remove header from native code, it runs ok.

Any glues/hints?

**Comment by DeerMichel** [comment]
Closing this issue since there has not been any recent activity. If your request is still relevant under current Electron versions, feel free to open a new issue.
