### ISSUE TITLE
preload script cannot be loaded if Content Security Policy is enabled

### ISSUE THREAD

**Issue by rhysd** [electron/electron#9276]
* Electron version: 1.6.5
* Operating system: macOS

### Expected behavior

Preload script can be loaded even if CSP is enabled

### Actual behavior

Preload script is prevented from being loaded by CSP

### How to reproduce

I could not prepare server with CSP, so let me show the sequence to reproduce with my app...

1. Download v0.2.2 from https://github.com/rhysd/Mstdn/releases
2. Unarchive it and copy [this config.json](https://gist.github.com/rhysd/9f656d4e93f40fe2e41752dfbe08cdc5) to `~/Application Support/Mstdn/config.json`
3. Open app with `$ NODE_ENV=development /path/to/Mstdn.app/Contents/MacOS/Mstdn`
4. It will open DevTools for browser window. Console tab should show the error.

In my app, browser window is opened with `nodeIntegration: false` and `preload: '...'` web preferences for external URL https://mstdn.jp where CSP is enabled.

Above sequence show following error.

<img width="800" alt="2017-04-25 0 53 55" src="https://cloud.githubusercontent.com/assets/823277/25346121/b8e7cf7c-2951-11e7-92bd-1b6c12193461.png">

It says that `eval` cannot be used because of CSP. The `eval` is used at VM28:784 for loading preload script specified with `preload: '...'` option on creating `BrowserWindow` instance.

Following is a screenshot of the code:

<img width="912" alt="2017-04-25 0 57 17" src="https://cloud.githubusercontent.com/assets/823277/25346295/2f126c98-2952-11e7-8186-9d4f5756a630.png">

Preload script is loaded with `eval()` function but it is blocked. Is it possible to remove the check by CSP while loading preload script?
Preload script is a way for loading some user script even if Node integration is disabled for external browser AFAIK. So, if it is blocked by CSP, preload script can no longer used for injecting some code to external page safely.

**Comment by kevinsawicki** [comment]
Just to confirm, you have the `sandbox` option enabled right?

**Comment by rhysd** [comment]
Thank you for quick response. Yeah, I enabled `sandbox` option to `true`, and when setting it to `false`, this error was not reported.

**Comment by tarruda** [comment]
> Preload script is loaded with eval() function but it is blocked. Is it possible to remove the check by CSP while loading preload script?

I need to investigate, but even if it is not possible to remove the check, it should still be possible to expose another eval-like function from C++ to allow loading the script.

**Comment by bpasero** [comment]
This I think blocks sandbox support for webviews where we set the following CSP: 

```html
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src http: https: data:; media-src http: https: data:; script-src 'none'; style-src file: http: https: 'unsafe-inline'; child-src 'none'; frame-src 'none';">
```

**Comment by PalmerAL** [comment]
@tarruda Any updates on this? We'd really like to enable sandboxing support in our application, but this bug is preventing us from doing so.
