### ISSUE TITLE
ipcMain.removeAllListeners fails

### ISSUE THREAD

**Issue by tejohnso** [electron/electron#9277]
According to the documentation the [channel] parameter is optional but it looks like that's incorrect.

From the documentation

----
```
ipcMain.removeAllListeners([channel])
channel String (optional)
Removes all listeners, or those of the specified channel.
```

From ipc-main.js

----
```
emitter.removeAllListeners = function (...args) {
  if (args.length === 0) {
    throw new Error('Removing all listeners from ipcMain will make Electron internals stop working.  Please specify a event name')
  }
  removeAllListeners(...args)
}
```

**Comment by rajatsingla28** [comment]
Hi @tejohnso. I am new towards contributing to open source projects. I want to help resolve this issue. Just wanted to confirm if the change needs to be made to ipc-main.md to remove the optional keyword for channel. Please correct me if i am wrong.

**Comment by tejohnso** [comment]
@rajatsingla28 I think that's correct, and you'd also want to change the description to "Removes listeners of the specified channel" so that it no longer suggests all listeners can be removed.
