### ISSUE TITLE
Webview Flickering on Resize

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#9280]
From: https://github.com/Microsoft/vscode/issues/24643

* Electron version: 1.6.6
* Operating system: MacOS 10.11.6

### Expected behavior
In Electron 1.4.6, Webviews remained visually stable when page reflows caused them to be resized.

### Actual behavior
Since 1.6.6, Webview flickers when its element is resized

### How to reproduce
Here's a repo with a small demo project: https://github.com/mjbvz/electron-1.6-webview-resize-flicker-demo

```bash 
git clone https://github.com/mjbvz/electron-1.6-webview-resize-flicker-demo.git
cd electron-1.6-webview-resize-flicker-demo
npm install
npm start
```

Drag the text area to expand and contract the webview. Notice the flickering:

![flicker](https://cloud.githubusercontent.com/assets/12821956/25365362/0ebc9e9e-291d-11e7-80db-284bb3922ece.gif)

Source code for the page: https://github.com/mjbvz/electron-1.6-webview-resize-flicker-demo/blob/master/index.html

**Comment by deepak1556** [comment]
I am able to reproduce the issue with 1.6.x but it seems fixed with chrome 58 branch.

**Comment by TimNZ** [comment]
It would be sweet if there was an Electron roadmap page giving us a rough idea of major milestones e.g. Chrome/Node version updates.

**Comment by kevinsawicki** [comment]
This should be fixed in 1.7.0 via the Chrome 58 upgrade, closing out.

**Comment by steverandy** [comment]
I'm still seeing the flickering on v1.7.2.

**Comment by TimNZ** [comment]
So am I.  
OS X
