### ISSUE TITLE
electron.remote.getCurrentWindow().restore() inconsistency Linux/Windows

### ISSUE THREAD

**Issue by t3chguy** [electron/electron#9281]
if a window was Maximized then Minimized, then restored using the restore() method from the Renderer it will be no longer maximized in Linux. This is not the case in Windows where it remains, correctly, maximized.

Node 7.40
Chrome 56.0.2924.87
Electron 1.6.2

### Actual behavior
Window gets restored but is no longer maximized

### Expected behavior
In Windows it stays maximized as it should

### How to reproduce
1. Run (almost) any electron app in Linux
2. Maximize its window
3. Open Developer Tools
4. Run `setTimeout(require('electron').remote.getCurrentWindow().restore, 3000)`
5. Minimize it before the 3 seconds
It will be restored 3 seconds after enter but it will also be unmaximized.

**Comment by zcbenz** [comment]
To unmaximize the window you have to call the `unmaximize` method, the `restore` should be called for a minimized window.

Calling `restore` for a maximized window is undefined behavior, which may behave differently on different platform and versions. So I'm closing this as won't fix.

**Comment by t3chguy** [comment]
@zcbenz this is about a **minimized** window
One that was first maximized, then later on minimized, so then it gets restored (unminimized) it should come back in a maximized state.
So your diagnosis seems unrelated.

To reiterate, for a window that is both maximized and then minimized `restore` ignores that it was earlier maximized *in Linux, but not in Windows*
 Which means that the definition of `restore` is inconsistent between Windows and Linux.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
