### ISSUE TITLE
Electron clean cache when restart.

### ISSUE THREAD

**Issue by cjld** [electron/electron#9282]
* Electron version: 1.6.2
* Operating system: Ubuntu 16.04

after opening some pages, electron cache some content in ~/.config/myapp/cache, here is the disk usage:

```
└─[0] <> du -h
40K     ./GPUCache
8.0K    ./Local Storage
525M    ./Cache
525M    .
```

but when I close Electron and restart it, it delete the whole cache directory, here is what left

```
└─[0] <> du -h
44K     ./GPUCache
8.0K    ./Local Storage
1.9M    ./Cache
2.0M    .
```

### Expected behavior

Is there any configuration that can preserve the cache files?

**Comment by deepak1556** [comment]
The disk cache will delete old entries when it exceeds the allocated space but deleting such large amounts of data is really weird. Are you able to create a minimal example to reproduce the issue, thanks!

**Comment by zcbenz** [comment]
Closing until more information is provided.
