### ISSUE TITLE
requireInteraction parameter in Notification is not working

### ISSUE THREAD

**Issue by Klestofer** [electron/electron#9283]
* Electron version:
v1.6.6
* Operating system:
Windows 10 version 1607

I'm trying to show Notification that will not be closed automatically after some time. So it needs to be closed only by user. I've tried:
```
new Notification('Title', {
  body: 'Body',
  requireInteraction: true,
})
```
and also:
```
new Notification('Title', {
  body: 'Body',
  sticky: true,
})
```
but notification is closed anyway after about 7 seconds. It would be nice to have possibility to create notifications that will not be closed automatically.
In Chrome version 58.0.3029.81 this code works good and shows notification that is not closed automatically:
```
new Notification('Title', {
  body: 'Body',
  requireInteraction: true,
})
```
So it looks like Chrome is aware of `requireInteraction` parameter but Electron ignores it.

**Comment by MarshallOfSound** [comment]
@Klestofer Because Electron uses system level implementations of Notifications (Toasts on W10, NSUserNotification on macOS, Etc.) the sticky concept isn't supported on all platforms, that said I have it on the todo list in #9269 but that implementation will only affect the new API in the main process

**Comment by Klestofer** [comment]
So it is not possible to show HTML5 notification with Electron?
Maybe code like  `new Notification(...)` should create HTML5 Notification, just like in browser?
And notifications from OS should be created with some other class, like `new SystemNotification(...)`?

**Comment by MarshallOfSound** [comment]
@Klestofer I think you are confused between the HTML5 Notification spec and Chromium's implementation of their Notification UI.  The current implementation of `Notification` inside Electron renderer processes already follows a large portion of the HTML5 Notification spec but the UI is implemented through system notifications.

From my own research macOS and W10 support a prop on their notifications to persist the notification until user interaction W7, W8 and LibNotify (linux) do not support this concept.

**Comment by Klestofer** [comment]
OK Thanks for explanation.

**Comment by zcbenz** [comment]
We can make `requireInteraction` work on macOS and Windows 10 and ignore it on other platforms.

**Comment by MarshallOfSound** [comment]
@zcbenz I looked into this a bit more and it's not possible to implement this on Windows 10 without also implementing actions. On windows the way to implement this is through `scenario="reminder"` which does nothing unless their is also an action (a button or a dropdown or something) in the notification.

**Comment by naheller** [comment]
@zcbenz How were you able to make `requireInteraction` work on macOS?

With this code, the notification still disappears after 7-8 seconds:
![screen shot 2017-07-17 at 3 06 43 pm](https://user-images.githubusercontent.com/18204925/28291930-b3dd0032-6b01-11e7-83b2-8f5d0cd1a236.png)

**Comment by rdp** [comment]
You may be able to work around it (for now) 
with some funky "re show" hacks, viz: https://bugzilla.mozilla.org/show_bug.cgi?id=875114

**Comment by blingenau** [comment]
Any update on this? Would really like notifications that don't go away for things like download progress

**Comment by cumajkeee** [comment]
Hi @zcbenz, any chance to have it in near future?

**Comment by Pagebakers** [comment]
I was actually wondering the opposite, how can i make sure notifications are automatically hidden, like Chrome. They are now always displayed with a close button.

**Comment by codebytere** [comment]
Given that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!

**Comment by pronebird** [comment]
@codebytere Can this be re-opened? Looking for a way to make notifications sticky.
