### ISSUE TITLE
npm error for electron

### ISSUE THREAD

**Issue by psingl** [electron/electron#9284]
I have tried several times to install electron both globally and in a particular project using npm. But at last it hangs over to `node install.js` As shown
![image](https://cloud.githubusercontent.com/assets/13885706/25402732/4dc74648-2a17-11e7-8829-7b3e174c228f.png)

**Comment by sbruchmann** [comment]
Have you tried `npm install electron --save --verbose`? I’m guessing it’s downloading the prebuilt electron binary on installation and not showing a progress bar.

**Comment by kevinsawicki** [comment]
> Have you tried npm install electron --save --verbose? I’m guessing it’s downloading the prebuilt electron binary on installation and not showing a progress bar.

@sbruchmann is right, the progress bar option should help diagnose this.

The `node install.js` script downloads ~50 MB and which can take some time depending on your network conditions.

Closing this out.
