### ISSUE TITLE
Windows Creator's Update: Focus broken

### ISSUE THREAD

**Issue by felixrieseberg** [electron/electron#9291]
We're seeing tons of reports of `BrowserWindow` focus operations no longer working with the Window's Creators Update (which is build 15000 and up). Interestingly, `blur()` still works.

Edit: This also affects other APIs that intend to focus the window - like `show()`, `restore()`, etc.

* Electron version: 1.4.x - 1.6.x
* Operating system: Windows 10, Creator's Update (Build > 15000)

### Expected behavior
`browserWindow.focus()` should focus the window
`browserWindow.isFocused()` should report correct focus state

### Actual behavior
`browserWindow.focus()` does not focus window
`browserWindow.isFocused()` incorrectly reports that the window is focused

### How to reproduce
<details>
On Windows, run this code in the devTools:

```js
win = require('electron').remote.getCurrentWindow()
setTimeout(() => {
	win.focus()
	console.log(win.isFocused())
}, 1500)
```

Then, focus another window.
</details>

![focus](https://cloud.githubusercontent.com/assets/1426799/25410128/e666851a-29c9-11e7-8cf4-4f7027135b93.gif)

![focus2](https://cloud.githubusercontent.com/assets/1426799/25410868/254cd5d2-29ce-11e7-8f1d-3c09ba0583dc.gif)

**Comment by zcbenz** [comment]
I'm not sure if we can do anything on this 😞 .

**Comment by weiluenju** [comment]
You can try to call the `app.disableHardwareAcceleration()` at the program start.

**Comment by robsonhermes** [comment]
While we wait for a fix, sharing the code I used to work around the issue:

`//This is how I show the window`
`win.setAlwaysOnTop(true);`
`win.show();`
`win.setAlwaysOnTop(false);`

`//But the window is not focused, even if I call win.focus(). The below did the trick`
`app.focus();`

Not the best solution, but at least solved my problem meanwhile...

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
