### ISSUE TITLE
Strange behavior after Electron v1.3.5

### ISSUE THREAD

**Issue by igogo5yo** [electron/electron#9296]
* Electron version: >= 1.3.6
* Operating system: Windows 7 and 8, macOS 10.12.4 

### Expected behavior
See previous view
![See previous view](https://hsto.org/files/808/025/47c/80802547cf214201be2091d14aaa97f4.gif)

### Actual behavior
Still on current view
![Still on current view](https://hsto.org/files/d5d/36c/a20/d5d36ca207f34e47a7d203c2e5436bb0.gif)

### How to reproduce:
1) Enter your username/email then click "Next"
2) Click "Back"
___

I took this issue on large project and I tried to reproduce it and I got!
This issue works only after electron 1.3.6
On 1.3.5 and below or in in last versions of Chromium I don't get this behavior.

For reproducing this issue I used this simple application:
```javascript
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

app.on('ready', () => {
  const win = new BrowserWindow({
    'title'           : app.getName(),
    'width'           : 800,
    'height'          : 600
  });

  win.loadURL('https://login.live.com/');
  win.openDevTools();
  win.on('closed', app.quit);
});
```

**Comment by kevinsawicki** [comment]
Looking at the changes in 1.3.6, it seems like this one might be affecting it: https://github.com/electron/electron/pull/7175

**Comment by igogo5yo** [comment]
@kevinsawicki maybe but I not sure because after my investigation I didn't find in OneDrive any logic which depends on window.history or window.navigator. 
They are using knockout.js for switching this view. And only after 1.3.6 knockout.js don't switch this view.
