### ISSUE TITLE
Open external links in browser open's multiple tabs

### ISSUE THREAD

**Issue by Meadowcottage** [electron/electron#9297]
* Electron version: 1.3.15
* Operating system: MacOS

### Expected behavior
Added method for opening all external links in browser.
When clicked, should open 1 new tab in browser pointing to url of link in app.

### Actual behavior
Open's hundreds of tabs to that url in your browser, to the point where the browser crashes and is forced to restart.

### How to reproduce
I have been using the following method for the past few months without issue:
 [github.com/Meadowcottage/generator-electron-boilerplate](https://github.com/Meadowcottage/generator-electron-boilerplate/blob/master/generators/app/templates/app/_main.js#L93-L97).
Unless the `new-window` event has been deprecated that I was unaware of, I'm not sure about what's causing the issue.

Any help would be much appreciated ❤️

**Comment by kevinsawicki** [comment]
> Electron version: 1.3.15

Can you reproduce this as well on Electron 1.6.x?

**Comment by kevinsawicki** [comment]
> Open's hundreds of tabs to that url in your browser, to the point where the browser crashes and is forced to restart.

What browser is it opening in?

**Comment by Meadowcottage** [comment]
Issue does also occur in version `1.6.x` yes.
Also browser is Google Chrome. Issue is not OS based. It happens on both MacOS and Windows.

**Comment by kevinsawicki** [comment]
Can you try opening the default Electron app, opening the dev tools, and running the following from the Console tab:

```js
require('electron').shell.openExternal('https://github.com')
```

Does this example open lots of tabs or just one?

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by krizzzly** [comment]
i experience the same issue with Chrome on Mac OS

**Comment by spandan1234** [comment]
I am also experiencing opening of multiple tabs with shell.openExternal. Why is the thread closed without any additional info?
