### ISSUE TITLE
removing space between TouchBar buttons

### ISSUE THREAD

**Issue by kinglime** [electron/electron#9298]
How can I make TouchBar buttons smaller and or remove the space between buttons?

**Comment by MarshallOfSound** [comment]
Sounds like you're looking for segmented controls

https://github.com/electron/electron/blob/master/docs/api/touch-bar-segmented-control.md

It's effectively a button group with different modes for separation of buttons.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by kinglime** [comment]
not quite what I'm looking for. I don't have a group of buttons where only one should be selected. I have a group of buttons that are all just normal buttons, meant to be pressed, but I need them closer together to save space. Seems like something worth adding to electron? The ability to change button sizes/spacing.

**Comment by MarshallOfSound** [comment]
@kinglime We can't do that, the gap between the button can only be made bigger not smaller.  I'm not even sure if we can add a mode to the NSSegmentedControl to allow them to act as normal buttons instead of single select

**Comment by MarshallOfSound** [comment]
Looks like this might be possible through `trackingMode` https://developer.apple.com/reference/appkit/nssegmentswitchtracking?language=objc

**Comment by MarshallOfSound** [comment]
@kinglime PR up to add a prop to change the trackingMode 👍

**Comment by kinglime** [comment]
@MarshallOfSound thanks man! What will the implementation look like?
