### ISSUE TITLE
Cannot load module preload script from .asar Windows

### ISSUE THREAD

**Issue by premitius** [electron/electron#9300]
* Electron version: 1.4 - 1.6.2 (happened on both versions)
* Operating system: Windows

### Actual behavior

Seemingly at random, every fifth or sixth start of the packaged application on Windows, it throws an error: cannot load preload script, with a follow-up error that it cannot find the file for node-sqlite3 in the .asar file. I need at least a way to catch this error and tell the user to restart the application. When the user restarts, it works fine. I cannot seem to figure out why this happens, because it happens randomly. 5/6 or 7/8 or 9/10 times, it works fine, but that last time it throws this error, and nothing else in the preload script is able to load.

### How to reproduce

Build an app for windows and include node-sqlite3, package it using electron-builder into an .asar

**Comment by kevinsawicki** [comment]
>  it cannot find the file for node-sqlite3 in the .asar file.

Which file is it complaining it cannot find? Is that file the `.node` file that is unpacked?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
