### ISSUE TITLE
Support sandbox bookmarks in Windows Store build

### ISSUE THREAD

**Issue by fancyydk** [electron/electron#9302]
* Electron version: 1.6.2
* Operating system: Windows 10

### Expected behavior

When the app is running as a Windows Store app, i.e. when process.windowsStore returns true, app.getPath('appData') should return the sandboxed app data folder, e.g. %USERPROFILE%\AppData\Local\Packages\PackageName\LocalCache\Roaming\

### Actual behavior

It still returns %APPDATA%

### How to reproduce

Package an electron app as a Windows Store app using a tool like [electron-windows-store](https://github.com/felixrieseberg/electron-windows-store) and call app.getPath('appData').

**Comment by felixrieseberg** [comment]
Hmmm, I'm not sure why you would want that. Here's my reasoning:

:one: Read operations will still have to be made against `%APPDATA%`. The system will automatically merge the sandboxed and "real" location.
:two: Write operations into the package folder aren't allowed ("Writes under C:\Program Files\WindowsApps\package_name are not allowed.")
:three: This is something that is and should be handled by Windows - you as the developer shouldn't worry about the redirection. See:

> In order to contain app state, the bridge attempts to capture changes the app makes to AppData. All write to the user's AppData folder (e.g., C:\Users\user_name\AppData), including create, delete, and update, are copied on write to a private per-user, per-app location. This creates the illusion that the converted app is editing the real AppData when it is actually modifying a private copy. By redirecting writes this way, the system can track all file modifications made by the app. This allows the system to clean up those files when the app is uninstalled, thus reducing system "rot" and providing a better app removal experience for the user.

@fancyydk What is your use case? It's always possible that I missed something.

**Comment by fancyydk** [comment]
Thanks Felix for the response. In my use case, I call `shell.openItem(file)` in which file is some file that exists in %APPDATA%. The system doesn't seem to redirect this path to %LOCALAPPDATA%\Packages\_AppName_ and instead still tries to read from that location.

Writing to that location is different however. The system automatically redirects the write operation to the sandboxed location in %LOCALAPPDATA%.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
