### ISSUE TITLE
Running on linux server

### ISSUE THREAD

**Issue by wormen** [electron/electron#9305]
Tell me, is it possible to start electron.io in a server environment, without an interface?
If so, how can I launch?

PhantomJS is certainly better suited for this, but it has problems that can not yet be circumvented

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

That said to run any GUI application in a server environment you need to set up XVFB

**Comment by wormen** [comment]
@MarshallOfSound 
thanks
