### ISSUE TITLE
Crash when double tap input (Windows)

### ISSUE THREAD

**Issue by lowki** [electron/electron#9308]
* Electron version: 1.6.6
* Operating system: Windows 7 and 8

### Actual behavior

When selecting content of a text input using a touch device on Windows (double tap), electron crash.
This will not happen using pointer device.

### How to reproduce

I've made a super simple test available in [this repo](https://github.com/lowki/electron-input-crash)

**Comment by kevinsawicki** [comment]
I believe this is a duplicate of https://github.com/electron/electron/issues/9197 and was fixed in 1.6.7, can you confirm?

**Comment by lowki** [comment]
I DO confirm, thanks a lot, was looking for a fix since weeks.
