### ISSUE TITLE
Box shadows don't on electron 1.6.0 onwards

### ISSUE THREAD

**Issue by KoJoVe** [electron/electron#9309]
* Electron version: 1.6.6
* Operating system: macOS 10.12

### Actual behavior

I simply try to use box shadow to style some elements and they do not appear when I run electron

### How to reproduce

Just added "box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);" to any element. When I open the index.html file in my browser, the shadow shows just fine, but when I run electron, no shadow appear.

I've created a repository with the problem:

https://github.com/KoJoVe/boxshadowelectron

**Comment by KoJoVe** [comment]
Just tested an inset box-shadow (box-shadow: inset 10px 10px 5px 0px rgba(0,0,0,0.75)) and it worked. The bug only happens with regular box-shadow

**Comment by KoJoVe** [comment]
That's really odd. 0px 5px 9px 0px rgba(0, 0, 0, 0.75) , seems to work, but if I drop the blur below 9px without droping the spread, it doesn't.

This:
0px 5px 9px 0px rgba(0, 0, 0, 0.75) -> Work
0px 5px 9px 0px rgba(0, 0, 0, 0.75) -> Dont Work
0px 5px 8px -1px rgba(0, 0, 0, 0.75) -> Work

**Comment by KoJoVe** [comment]
Here's how it looks in electron:

(Notice the strange small shadow on the corner)

<img width="1000" alt="captura de tela 2017-04-27 as 16 20 50" src="https://cloud.githubusercontent.com/assets/1348140/25500481/8ba46866-2b65-11e7-9d53-8f51de1175a9.png">

Here's on the safari/chrome browser:

<img width="1278" alt="captura de tela 2017-04-27 as 16 21 00" src="https://cloud.githubusercontent.com/assets/1348140/25500511/ab590e14-2b65-11e7-89d6-a33bfceb016c.png">

**Comment by KoJoVe** [comment]
Downgraded to electron 1.5.1 and the box-shadows work again. The issue started in electron 1.6.0!

**Comment by kevinsawicki** [comment]
@KoJoVe do you have the `LANG` environment variable set? Can you confirm what locale you are using?

It looks correct on my machine using a US locale:

![screen shot 2017-05-01 at 11 40 20 am](https://cloud.githubusercontent.com/assets/671378/25589840/ff7377dc-2e62-11e7-9a1b-b56951891e33.png)


But using `LANG=fr_FR.UTF-8` I'm seeing it not work correctly as you've reported:

![screen shot 2017-05-01 at 11 40 45 am](https://cloud.githubusercontent.com/assets/671378/25589858/0ea8d3f0-2e63-11e7-933a-afe22cf741a8.png)

**Comment by kevinsawicki** [comment]
Seems somewhat similar to #8825 and #9225

**Comment by kevinsawicki** [comment]
This appears to be fixed via https://github.com/electron/libchromiumcontent/pull/299, closing this out.
