### ISSUE TITLE
How to access desktopCapturer in sandboxed renderer

### ISSUE THREAD

**Issue by lneir** [electron/electron#9312]
I would like to be able to use desktopCapturer in a sandboxed renderer process.  What are the options?

I have posted one soln here...  yes, this soln **is not kosher/stable**... https://discuss.atom.io/t/use-desktopcapturer-in-sandboxed-renderer-process/41536

Other ideas?  Or possible future enhancement to electron?

Thanks.

**Comment by kevinsawicki** [comment]
@tarruda do you want to keep this as a separate issue or add it as a checkbox to https://github.com/electron/electron/issues/6712 ?

**Comment by tarruda** [comment]
keep it separate, as it is easier for me to prioritize it.

**Comment by nornagon** [comment]
It looks like this already works: be0e3d9555
