### ISSUE TITLE
executeJavaScript does not return a promise

### ISSUE THREAD

**Issue by gabrielstuff** [electron/electron#9313]
The simplest code from the doc says : 

```
contents.executeJavaScript('fetch("https://jsonplaceholder.typicode.com/users/1").then(resp => resp.json())', true)
  .then((result) => {
    console.log(result) // Will be the JSON object from the fetch call
  })
```

I expect to read a JSON in the terminal console.

Instead, I see this error poping : 
<img width="423" alt="screen_shot_2017-04-28_at_00_47_59" src="https://cloud.githubusercontent.com/assets/285033/25507466/85be3764-2bac-11e7-81cd-88f62a6c7966.png">

Here is the code.
```
const electron = require('electron')
  let printWindow = new electron.BrowserWindow({
    width: printWindowWidth,
    height: printWindowHeight,
    show: true,
    alwaysOnTop: true
  })
  printWindow.loadURL(args.url)
  printWindow.webContents.on('did-finish-load', function (event) {
  
  printWindow.webContents.executeJavaScript('fetch("https://jsonplaceholder.typicode.com/users/1").then(resp => resp.json())', true)
  .then((result) => {
    console.log(result) // Will be the JSON object from the fetch call
  })
})
```

**Comment by kevinsawicki** [comment]
@gabrielstuff what version of Electron are you using?

**Comment by kevinsawicki** [comment]
This method returned `undefined` until 1.4.6 when it started returning a `Promise`.

**Comment by gabrielstuff** [comment]
I'm using `1.3.15` from https://github.com/electron-userland/electron-prebuilt.  The callback is always empty as well.

**Comment by gabrielstuff** [comment]
Ok going on `1.4.6` fixed it.
