### ISSUE TITLE
Turning on webPreferences.nodeIntegration breaks PepperFlash Plugin.

### ISSUE THREAD

**Issue by epiqueras** [electron/electron#9316]
* Electron version: 1.6.6
* Operating system: Mac OSX

With this flash works:

```js
webPreferences: {
  nodeIntegration: false,
  plugins: true,
},
```

With this it fails. I can still see it added in `navigator.plugins`, and I don't get any errors, but flash content does not load.

```js
webPreferences: {
  nodeIntegration: true,
  plugins: true,
},
```

**Comment by deepak1556** [comment]
Can you provide a minimal example to reproduce the issue, thanks!

**Comment by zcbenz** [comment]
Closing until more information is provided.
