### ISSUE TITLE
customize the style of the tray menu

### ISSUE THREAD

**Issue by amhoho** [electron/electron#9317]
The current tray menu is very simple and ugly,How to customize the style of the tray menu?
now:
like this:
![image](https://github.com/amhoho/electron-cn-docs/raw/master/demo/images/03.png)

**Comment by MarshallOfSound** [comment]
You can use a BrowserWindow positioned next to your tray icon to get this effect

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
