### ISSUE TITLE
OSX: Non-modal child windows ignore show: false parameter

### ISSUE THREAD

**Issue by xaviergonz** [electron/electron#9318]
* Electron version: 1.6.6
* Operating system: macOs 10.12.4

### Expected behavior

When opening a BrowserWindow with a parent, modal: false and show: false the window should start hidden.

### Actual behavior

The window shows nevertheless

### How to reproduce

Create a first (main) window.
Create a second (child) window with:
{
  parent: mainWindow,
  modal: false,
  show: false
}

**Comment by kevinsawicki** [comment]
I believe this is a duplicate of #8836, please subscribe to that issue for updates.
