### ISSUE TITLE
Linux: File drop from gvfs shares onto electron causes wrong behaviour

### ISSUE THREAD

**Issue by mofux** [electron/electron#9319]
* Electron version: 1.6.7 (any)
* Operating system: Linux (Gnome 3)

### Expected behavior

Dragging a file from a mounted `gvfs` share from `Nautilus` onto an electron app that is listening for `drop` events should populate `evt.dataTransfer.files` with the path to the mounted file (e.g. `/run/usr/1000/gvfs/<gvfs-share-name>/path/to/file`)

```javascript
document.addEventListener('drop', (evt) => {
  // should log the actual path of the file being dropped
  // e.g. /run/usr/1000/gvfs/<gvfs-share-name>/path/to/file
  console.log(evt.dataTransfer.files[0].path)
})
```

### Actual behavior

Instead of populating `evt.dataTransfer.files`, `evt.dataTransfer.items` is populated, which contains the url to the file (e.g.: `sftp://user@my-server:22/path/to/file`). This doesn't make much sense, as we cannot consume the file that way.

```javascript
document.addEventListener('drop', (evt) => {
  // will log 0
  console.log(evt.dataTransfer.files.length);

 // will log the url to the file
 // e.g. sftp://user@my-server:22/path/to/file
 for (let item of evt.dataTransfer.items) item.getAsString((uri) => console.log(uri));
})
```

### How to reproduce
On any Gnome 3 based distribution, open Nautilus and connect to a remote server by entering the url into the location bar (e.g. sftp://user@my-server). Nautilus will show the contents of the remote file system. Take any folder and drag it onto atom, nothing will happen. Do the same with Sublime Text and it will open the folder from the underlying mount, e.g `/run/usr/1000/gvfs/<gvfs-mount-name>/path/to/folder`

Any electron based app, and even Chromium seems to suffer from this problem:
Dragging a folder from a mounted `gvfs` share onto `atom` does nothing
Dragging an image from a mounted `gvfs` share onto the chromium browser will cause chromium to open the url (sftp://user@my-server:22/path/to/file)

**Comment by zcbenz** [comment]
Can you report this to [Chromium's issues list](https://bugs.chromium.org/p/chromium/issues/list) instead? I'm closing this since it is an upstream Chromium issue that we are not able to fix on Electron's side.

**Comment by mofux** [comment]
For reference, I have created a chromium issue here:
https://bugs.chromium.org/p/chromium/issues/detail?id=734959#

**Comment by mofux** [comment]
FYI: This issue will be resolved with the next release of Gnome via https://gitlab.gnome.org/GNOME/nautilus/commit/03b540dbe9b59016e4392b710023aa675ffbc382
