### ISSUE TITLE
Blank window by using socket.io in BrowserWindow

### ISSUE THREAD

**Issue by Frahmer** [electron/electron#9320]
* Electron version: 1.6.6 (and 1.6.7)
* Operating system: Windows

### Expected behavior
Use socket.io websocket connection in BrowserWindow.

### Actual behavior
Window becomes blank, Developer Tools is disconnected with no console error.

### How to reproduce
`var socket = io("host", {
  forceNew: true,
  reconnection: true,
  transports: ['websocket'] /* only websocket as transport is the problem */
});`

### Note
It works with Electron 1.4.16

**Comment by kevinsawicki** [comment]
@Frahmer can you include more steps on how to reproduce? Perhaps you could fork https://github.com/electron/electron-quick-start and create a branch that demonstrates the issue, thanks.

**Comment by Frahmer** [comment]
@kevinsawicki I have found my mistake, I use the method protocol.registerBufferProtocol() to load my files, but I didn't know that protocol.registerStandardSchemes() is necessary for socket.io (since electron 1.6.x ?).
