### ISSUE TITLE
build electron error

### ISSUE THREAD

**Issue by CaiHuan** [electron/electron#9321]
os: win10
visual studio 2015
when i typing python script\build.py -c D the compiler post below error
1>  [694/1292] CXX obj\vendor\brightray\browser\win\brightray.windows_toast_notification.obj
1>  FAILED: obj/vendor/brightray/browser/win/brightray.windows_toast_notification.obj
1>  ninja -t msvc -e environment.x86 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\vendor\brightray\browser\win\brightray.windows_toast_notification.obj.rsp /c ..\..\vendor\brightray\browser\win\windows_toast_notification.cc /Foobj\vendor\brightray\browser\win\brightray.windows_toast_notification.obj /Fdobj\vendor\brightray\brightray.cc.pdb
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(152): error C2220: warning treated as error - no 'object' file generated
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(152): warning C4003: not enough actual parameters for macro 'max'
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(156): warning C4003: not enough actual parameters for macro 'max'
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(159): warning C4003: not enough actual parameters for macro 'min'
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(160): warning C4003: not enough actual parameters for macro 'max'
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(161): warning C4003: not enough actual parameters for macro 'min'
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(152): error C2059: syntax error: ')'
1>  e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(163): note: see reference to class template instantiation 'base::internal::NarrowingRange<Dst,Src>' being compiled
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(152): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(163): error C2143: syntax error: missing ')' before ';'
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(163): error C2059: syntax error: ')'
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(163): error C2238: unexpected token(s) preceding ';'
1>e:\git\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\numerics\safe_conversions_impl.h(163): fatal error C1201: unable to continue after syntax error in class template definition
1>  ninja: build stopped: subcommand failed.
1>E:\git\electron\electron.vcxproj(460,5): error MSB3073: The command "call ninja.exe -C out\Debug\ electron" exited with code 1.

**Comment by kevinsawicki** [comment]
> 1> [694/1292] CXX obj\vendor\brightray\browser\win\brightray.windows_toast_notification.obj

Any thoughts on this one @alespergl?

**Comment by alespergl** [comment]
Yes, this looks like the classic conflict of the Windows SDK's `min`/`max` macros with code which tries to use those tokens for its own purposes. There should be a `-DNOMINMAX` option on the command line (or in the `.rsp` file). Not sure why it's not in this case, because [it is specified](https://github.com/electron/brightray/blob/master/brightray.gypi#L158) in the `Common_Base` configuration in the `brightray.gypi` file.

**Comment by CaiHuan** [comment]
@alespergl
this error just post in visual studio 2015 compile
everything is fine if i typing below command step by step
1: python script\bootstrap.py -v --target_arch=ia32
2: python script\build.py

visual studio 2015 will post error when compile sln which generated by python script\bootstrap.py --msvs

**Comment by CaiHuan** [comment]
@alespergl 
it look likes the sln named electron and electron_lib file setting error, 
the out put directory is out\Debug not out\D, the electron_lib.ninja has NOMINMAX macro but electron_lib.ninja which in out\Debug exclude DNOMINMAX macro

**Comment by CaiHuan** [comment]
the build guide recommend output directory is out\D

**Comment by alespergl** [comment]
I'm not sure to what extent the `--msvs` option is supported by Electron. I wouldn't rely on it for building the code. It's safer to stick to the command line.

**Comment by CaiHuan** [comment]
thanks a lot
