### ISSUE TITLE
Failed at electron@1.6.2 postinstall: `node install.js`

### ISSUE THREAD

**Issue by syaifuri** [electron/electron#9323]
issue with 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! polyonic@1.0.0 postinstall: `cd src && npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the polyonic@1.0.0 postinstall script 'cd src && npm install'

* Electron version:
1.6.2
* Operating system:
windows 7 64 bit

### Actual behavior

tried many times repo, always got error.
download manual git files is fine, no issue on network

### How to reproduce
01 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
402 error node v6.10.2
403 error npm  v3.10.10
404 error code ELIFECYCLE
405 error polyonic@1.0.0 postinstall: `cd src && npm install`
405 error Exit status 1
406 error Failed at the polyonic@1.0.0 postinstall script 'cd src && npm install'.

**Comment by ericlathrop** [comment]
I'm getting the same error with 1.6.6. I can reproduce it by running `npm install electron` in an empty folder.

The output is:
```
> electron@1.6.6 postinstall /home/eric/lets-start-coding/lets-start-coding-electron/node_modules/electron
> node install.js

/home/eric/lets-start-coding/lets-start-coding-electron/node_modules/electron/install.js:47
  throw err
  ^

Error: ENOENT: no such file or directory, realpath '/home/eric/lets-start-coding/lets-start-coding-electron/node_modules/electron/dist/resources'
    at Error (native)
npm ERR! Linux 4.9.8-040908-generic
npm ERR! argv "/home/eric/packages/node-v6.2.1-linux-x64/bin/node" "/home/eric/packages/node-v6.2.1-linux-x64/bin/npm" "i" "electron"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eric/lets-start-coding/lets-start-coding-electron/test/npm-debug.log
```

**Comment by DevCubeHD** [comment]
**Upvote! Same here when trying to install electron**

E:\CloudSystem.IO\Webpanel>npm install -g electron
C:\Users\Felix-PC\AppData\Roaming\npm\electron -> C:\Users\Felix-PC\AppData\Roaming\npm\node_modules\electron\cli.js

> electron@1.6.6 postinstall C:\Users\Felix-PC\AppData\Roaming\npm\node_modules\electron
> node install.js

C:\Users\Felix-PC\AppData\Roaming\npm\node_modules\electron\install.js:47
  throw err
  ^

Error: ENOENT: no such file or directory, lstat 'C:\Users\Felix-PC\AppData\Roaming\npm\node_modules\electron\dist\resources'
    at Error (native)
- ansi-styles@2.2.1 node_modules\electron\node_modules\ansi-styles
- escape-string-regexp@1.0.5 node_modules\electron\node_modules\escape-string-regexp
- generate-function@2.0.0 node_modules\electron\node_modules\generate-function
- graceful-readlink@1.0.1 node_modules\electron\node_modules\graceful-readlink
- commander@2.9.0 node_modules\electron\node_modules\commander
- has-ansi@2.0.0 node_modules\electron\node_modules\has-ansi
- xtend@4.0.1 node_modules\electron\node_modules\is-my-json-valid\node_modules\xtend
- is-property@1.0.2 node_modules\electron\node_modules\is-property
- generate-object-property@1.2.0 node_modules\electron\node_modules\generate-object-property
- jsonpointer@4.0.1 node_modules\electron\node_modules\jsonpointer
- is-my-json-valid@2.15.0 node_modules\electron\node_modules\is-my-json-valid
- supports-color@2.0.0 node_modules\electron\node_modules\supports-color
- chalk@1.1.3 node_modules\electron\node_modules\chalk
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "electron"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\CloudSystem.IO\Webpanel\npm-debug.log

E:\CloudSystem.IO\Webpanel>

**Comment by cristianobarros** [comment]
Same error here.

$ npm install electron

> electron@1.6.6 postinstall C:\node_modules\electron
> node install.js

C:\node_modules\electron\install.js:47
  throw err
  ^

Error: ENOENT: no such file or directory, lstat 'C:\node_modules\electron\dist\resources'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Cristiano\AppData\Roaming\npm-cache\_logs\2017-04-29T22_13_24_628Z-debug.log

**Comment by ir-fuel** [comment]
Same issue here

https://github.com/electron/electron/issues/9326

**Comment by DevCubeHD** [comment]
Maybe rencent update with mistakes? o.o I am confused of this error. I tried everything I could find.. 

- Reinstalling npm
- Updating npm
- Deleting node_modules

etc

**Comment by johannesjo** [comment]
Same issue on Ubuntu 16.04 with node v6.9.2.

**Comment by ericlathrop** [comment]
It's really weird because 1.6.2 worked for me last week, but doesn't work now. I'm not sure how an npm package can suddenly break whilst staying the same version number.

**Comment by DevCubeHD** [comment]
node -v
> v6.9.4

npm -v
> 4.5.0

electron -v
> module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Felix-PC\AppData\Roaming\npm\node_modules\electron\cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by ir-fuel** [comment]
node 7.9.0 and npm 4.0.2 here

Same issue

**Comment by DevCubeHD** [comment]
Okay obviously an electron error

**Comment by furkansa** [comment]
node 6.10.2
npm 3.10.10
windows10 x64 creators update
same issue

**Comment by dolanmiu** [comment]
> node 6.10.2
npm 3.10.10
windows10 x64 creators update
same issue

Exactly same specs as you, same issue

**Comment by felipeferreirah** [comment]
node v7.8.0
npm 4.2.0
Ubuntu 17.04 unity

same problem...

**Comment by sbruno81** [comment]
node v6.10.1
npm 3.10.10
windows10 x64 Anniversary Update

**Comment by dfbaskin** [comment]
You can reproduce this error (at least on Windows) by adding the electron package, then after npm/yarn fails, do the following:

```
cd node_modules\electron
erase dist\electron.exe
node install.js
```

`install.js` fails, but if you do the following it does not fail:

```
erase dist\electron.exe
md dist\resources
md dist\locales
```

**Comment by malept** [comment]
From what I can tell, this is due to a regression in `extract-zip` between 1.6.0 and 1.6.1. I'm reaching out to the maintainer of that module to see how to fix this.

In the meantime, I think we've established that it's a problem, so it would be appreciated if everyone can refrain from "me too" comments. That way, the people who are subscribed to the issue gets less notification spam while this gets worked out. Thanks!

**Comment by codekraft-studio** [comment]
### (Linux) Env
```bash
node -v
v6.10.2
npm -v
4.4.4
```
for me It does not work either with sudo, but it works locally
```
sudo npm install -g electron

> electron@1.6.6 postinstall /usr/lib/node_modules/electron
> node install.js

/usr/lib/node_modules/electron/install.js:47
  throw err
  ^

Error: ENOENT: no such file or directory, lstat '/usr/lib/node_modules/electron/dist/resources' at Error (native)
```

but this command:
```
npm install --save-dev electron
```
works great

**Comment by dfbaskin** [comment]
Yeah, I can confirm that 1.6.0 of `extract-zip` allows the `install.js` to work correctly.

**Comment by puzrin** [comment]
@malept good catch, thanks for info! If dependency will be broken for a long time - [js-zip](https://github.com/Stuk/jszip) is another alternative.

Temrorary fix for all - add `"extract-zip": "=1.6.0",` to your project dependencies in the same place where `electron` placed.

**Comment by johannesjo** [comment]
@puzrin that's an even better solution! Thanks for sharing!

**Comment by renevanderlende** [comment]
@johannesjo your global solution works fine on W10 home on x64
@puzrin your local solution works fine too.

Both after fresh (re)install of nodejs (7.9.0) and npm@latest (4.5.0)

Thanks to the both of you, by noobie me!

**Comment by ChannelOne** [comment]
`node v7.9` on Windows 10 Creators Update, install with `Yarn v0.23.2`

```
yarn global add electron
````

same issue

````
error C:\Users\cdzos\AppData\Local\Yarn\config\global\node_modules\electron: Command failed.
Exit code: 1
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c node install.js
Directory: C:\Users\cdzos\AppData\Local\Yarn\config\global\node_modules\electron
Output:
C:\Users\cdzos\AppData\Local\Yarn\config\global\node_modules\electron\install.js:47
  throw err
  ^

Error: ENOENT: no such file or directory, lstat 'C:\Users\cdzos\AppData\Local\Yarn\config\global\node_modules\electron\d
ist\resources'
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by malept** [comment]
I'm going to lock this thread until `extract-zip` has been fixed, since the cause has been identified.

**Comment by malept** [comment]
`extract-zip` 1.6.5 has been released, I've verified that if you update that dependency (or wipe out `node_modules` and reinstall dependencies), you should be able to install the `electron` module again.
