### ISSUE TITLE
Modal BrowserWindow , parent window Flicker when close child Window

### ISSUE THREAD

**Issue by hxkuc** [electron/electron#9325]
just like this :

in main process

let mainWindow = new BrowserWindow({width: 800, height: 600})
......
.........
...........

app.on('ready', function(){
  createWindow();
  let child = new BrowserWindow({parent: mainWindow, modal: true, show: false})
  child.loadURL('https://www.baidu.com')
  child.once('ready-to-show', () => {
    child.show()
  })
})

when close child window parent window Flicker

just use model:true cause this problem

**Comment by hxkuc** [comment]
const modalPath = path.join('file://', __dirname, '../../sections/windows/modal.html')
  const nowwindow = BrowserWindow.getFocusedWindow()
  let win = new BrowserWindow({ width: 400, height: 320, parent: nowwindow,modal:true })
  win.on('close', function () { win = null })
  win.loadURL(modalPath)
  //win.show()

same

**Comment by zcbenz** [comment]
Please report your OS version along with a minimal app to reproduce the problem. Closing until more information is provided.

**Comment by hxkuc** [comment]
win7 and  win10 all have this problem，
1: open one modal window name win1  on the parent window name win 
like this --> let win1 = new BrowserWindow({ width: 400, height: 320, parent: win, modal: true })
2:open one window name win2 on the parent window name win1
like this --> let win2 = new BrowserWindow({ width: 400, height: 320, parent: win1, modal: true })
the problem is win hidden when open win2 
and win show when close win2
bug ?????????????

**Comment by Matix-Media** [comment]
I have the exact same problem. Would be nice to see a solution to this very old problem...
