### ISSUE TITLE
How to hide the window when you click outside the window?

### ISSUE THREAD

**Issue by amhoho** [electron/electron#9327]
How do this? Thank  you.
BTW, @Electron I have a suggestion to add the mouse event API

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
Listen for the blur event on the window and then call window.hide()
