### ISSUE TITLE
Error: electron@1.6.6 postinstall: `node install.js`

### ISSUE THREAD

**Issue by cryptoshrimpi** [electron/electron#9328]
* Electron version: 1.6.6
* Operating system: Debian 8.7
* Node JS Version: v7.9.0 (same issue with v7.4.0)
* NPM Version: v4.2.0

### Expected behavior
> npm install electron

Successful installation of Electron

### Actual behavior

Installation fails

19414 verbose stack Error: electron@1.6.6 postinstall: `node install.js`
19414 verbose stack Exit status 1
19414 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
19414 verbose stack     at emitTwo (events.js:106:13)
19414 verbose stack     at EventEmitter.emit (events.js:194:7)
19414 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
19414 verbose stack     at emitTwo (events.js:106:13)
19414 verbose stack     at ChildProcess.emit (events.js:194:7)
19414 verbose stack     at maybeClose (internal/child_process.js:899:16)
19414 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

### How to reproduce
node v7.9.0 (npm v4.2.0)
> npm install electron

I tried a lot of stuff but I cannot get Electron working on my system :(

Same behavior with node v7.4.0

**Comment by MarshallOfSound** [comment]
See #9323
