### ISSUE TITLE
Augmenting IPC callback wrapper functions between browser and renderer

### ISSUE THREAD

**Issue by TimNZ** [electron/electron#9330]
I'm passing renderer based callbacks into the browser via your IPC proxy support, which are wrapped here:

https://github.com/electron/electron/blob/3c1a3721571566664f201f6e5cfa699456ca6eab/lib/browser/rpc-server.js#L218

When a BrowserWindow instance has been 'closed', a browser based WindowManager emits an event which tries calling a listener that may no longer be alive as the containing BrowserWindow is dead, resulting in removeRemoteListenersAndLogWarning() being called in rpc-server.js

Would it be reasonable to add a 'sender' property to the callIntoRenderer() dynamically created function so I can query whether it is remote or local?
You are currently adding a 'length' property.

Example:
```
Object.defineProperty(callIntoRenderer, 'sender', { value: sender });
```

This may also be useful in the other direction - renderer -> browser, detecting a remote function.
Possibly have a property indicating the containing process type e.g. 'browser','renderer' would be great.

I would use this to do this this pseudo code:
```
if (listener.sender)
{ 
   if (window.webContents.id != listener.sender.getId() )
       listener.emit(...);
}
```

I could do a PR but want your thoughts first.

**Comment by zcbenz** [comment]
I'm 👍 on this.

**Comment by TimNZ** [comment]
@zcbenz Alternatively instead of non-standard augmenting of function wrappers with additional properties, what about extending 'ipcMain' and 'ipcRenderer' modules to get more hooks into the rpc/ipc pipeline?

More complicated, but provides a better foundation for monitoring and control over rpc/ipc flow.

**Comment by miniak** [comment]
@TimNZ is this ask still relevant?

**Comment by TimNZ** [comment]
I'm not currently doing Electron dev, so unless there's appetite for it by others, can close this.

**Comment by miniak** [comment]
The `remote` module was removed from Electron core, it would have to be addressed in https://github.com/electron/remote
