### ISSUE TITLE
Trying to install electron on Ubuntu fails with error code 1-

### ISSUE THREAD

**Issue by toshovski** [electron/electron#9332]
* Electron version: 1.6.6
* Operating system: Ubuntu 16.04 LTS

### Expected behavior

Trying to install electron using

sudo npm install -g electron fails.  Any ideas how to solve that issue? I tried to delete npm cache and also the .electron and .npm folder, but it didnt work.

### Actual behavior

I get the following error:  ENOENT: no such file or directory, lstat '/usr/lib/node_modules/electron/dist/resources'

terminal error:
> /usr/lib/node_modules/.staging
> 13455 silly rollbackFailedOptional Starting
> 13456 silly rollbackFailedOptional Finishing
> 13457 silly runTopLevelLifecycles Finishing
> 13458 silly install printInstalled
> 13459 verbose stack Error: electron@1.6.6 postinstall: `node install.js`
> 13459 verbose stack Exit status 1
> 13459 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
> 13459 verbose stack     at emitTwo (events.js:106:13)
> 13459 verbose stack     at EventEmitter.emit (events.js:191:7)
> 13459 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> 13459 verbose stack     at emitTwo (events.js:106:13)
> 13459 verbose stack     at ChildProcess.emit (events.js:191:7)
> 13459 verbose stack     at maybeClose (internal/child_process.js:886:16)
> 13459 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 13460 verbose pkgid electron@1.6.6
> 13461 verbose cwd /home/aleksandar
> 13462 error Linux 4.8.0-49-generic
> 13463 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "electron"
> 13464 error node v6.10.2
> 13465 error npm  v3.10.10
> 13466 error code ELIFECYCLE
> 13467 error electron@1.6.6 postinstall: `node install.js`
> 13467 error Exit status 1
> 13468 error Failed at the electron@1.6.6 postinstall script 'node install.js'.
> 13468 error Make sure you have the latest version of node.js and npm installed.
> 13468 error If you do, this is most likely a problem with the electron package,
> 13468 error not with npm itself.
> 13468 error Tell the author that this fails on your system:
> 13468 error     node install.js
> 13468 error You can get information on how to open an issue for this project with:
> 13468 error     npm bugs electron
> 13468 error Or if that isn't available, you can get their info via:
> 13468 error     npm owner ls electron
> 13468 error There is likely additional logging output above.
> 13469 verbose exit [ 1, true ]

npm debug log:
```
13454 verbose unlock done using /home/aleksandar/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
13455 silly rollbackFailedOptional Starting
13456 silly rollbackFailedOptional Finishing
13457 silly runTopLevelLifecycles Finishing
13458 silly install printInstalled
13459 verbose stack Error: electron@1.6.6 postinstall: `node install.js`
13459 verbose stack Exit status 1
13459 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
13459 verbose stack     at emitTwo (events.js:106:13)
13459 verbose stack     at EventEmitter.emit (events.js:191:7)
13459 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13459 verbose stack     at emitTwo (events.js:106:13)
13459 verbose stack     at ChildProcess.emit (events.js:191:7)
13459 verbose stack     at maybeClose (internal/child_process.js:886:16)
13459 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13460 verbose pkgid electron@1.6.6
13461 verbose cwd /home/aleksandar
13462 error Linux 4.8.0-49-generic
13463 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "electron"
13464 error node v6.10.2
13465 error npm  v3.10.10
13466 error code ELIFECYCLE
13467 error electron@1.6.6 postinstall: `node install.js`
13467 error Exit status 1
13468 error Failed at the electron@1.6.6 postinstall script 'node install.js'.
13468 error Make sure you have the latest version of node.js and npm installed.
13468 error If you do, this is most likely a problem with the electron package,
13468 error not with npm itself.
13468 error Tell the author that this fails on your system:
13468 error     node install.js
13468 error You can get information on how to open an issue for this project with:
13468 error     npm bugs electron
13468 error Or if that isn't available, you can get their info via:
13468 error     npm owner ls electron
13468 error There is likely additional logging output above.
13469 verbose exit [ 1, true ]

```

**Comment by MarshallOfSound** [comment]
See #9323
