### ISSUE TITLE
postMessage between windows missing fields when contextIsolation enabled

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#9340]
* Electron version: 1.6.6
* Operating system: All

### Expected behavior

`postMessage` over a `window.open` window or `window.opener` should contain all the standard event fields.

### Actual behavior

Event is missing `data`, `source`, and `origin` when `contextIsolation` is enabled. This is because the event is manually created and the secure proxies for built-ins such as `Event` prevent additional properties from hopping across contexts.

### How to reproduce

* Open a window with `contextIsolation` enabled
* Open a window from the page from the main context using `window.open`
* Post a message to the window, `event.data` will be missing, also other fields from https://github.com/electron/electron/blob/f84c75aa1aaa903d893a87a2111517ffdfec5cc1/lib/renderer/window-setup.js#L152-L154

**Comment by shubham2892** [comment]
@kevinsawicki What in your opinion would be the best way to approach this.

**Comment by kevinsawicki** [comment]
> What in your opinion would be the best way to approach this.

I'm not sure there will be a straight-forward way to address this based on the current implementation since the proxy objects used by `contextIsolation` deliberately prevent added properties from being accessible across contexts.

I think the best path forward it to make the `nativeWindowOpen` option as solid as can be and then eventually we can remove the custom `window.open`, `window.postMessage`, etc. implementation from `window-setup` and just rely on Chrome's support for this.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by asnow003** [comment]
Can we reopen this issue.  We are using the latest versions of Electron (2.0.10) and when we turn on context isolation the issue still exists.  Just wondering if this is something that will be fixed soon?  Looks like the suggested fix would be to remove the open/postMessage from the window-setup.js.

**Comment by alexeykuzmin** [comment]
Reopening per the comment above.

**Comment by alexeykuzmin** [comment]
@asnow003 Is using the [`nativeWindowOpen`](https://electronjs.org/docs/api/window-open#using-chromes-windowopen-implementation) an option for your task?

**Comment by asnow003** [comment]
@alexeykuzmin I did try the nativeWindowOpen but still have the issue.  Also, with that switched on my child windows no longer will center on the screen (might be something fixable).

**Comment by asnow003** [comment]
@kevinsawicki I know its been awhile for this one but in doing some testing from the comment you made previously...
You mentioned that added properties to the event would be removed when contextIsolation is enabled.  I tried creating a CustomEvent and adding information to the detail property.  I thought this was working but the result was that with contextIsolation on the detail property is being set to null...if I turn contextIsolation off my detail comes through.  I was trying to do this below in window-setup.js thinking it might fix it.  Just wondering what/who is stripping out this data?

`
  ipcRenderer.on('ELECTRON_GUEST_WINDOW_POSTMESSAGE', function (event, sourceId, message, sourceOrigin) {
    // Manually dispatch event instead of using postMessage because we also need to
    // set event.source.

    var source = getOrCreateProxy(ipcRenderer, sourceId);
    var event = new CustomEvent('message', {
      detail: {
        data: message,
        origin: sourceOrigin,
        source: source
      } 
    });

    // When contextIsolation is enabled these values will not persist
    // Users should transition to always using the detail of the event.
    event.data = message
    event.origin = sourceOrigin
    event.source = source

    window.dispatchEvent(event);
  })
`

**Comment by alexeykuzmin** [comment]
> With `contextIsolation` and `nativewindow` both enabled at the same time I send messages to the child window but it never receives them.

If `sandbox` is disabled on a parent window, messaging works for both same- and cross-origin pages.

**Comment by miniak** [comment]
This issue does not reproduce anymore with Electron >= 4. It also only reproduces with `nativeWindowOpen: false`.
