### ISSUE TITLE
Use Existing Chrome Application Instead of Bundling Chromium

### ISSUE THREAD

**Issue by alexanderepstein** [electron/electron#9345]
Quite honestly the only thing that makes electron tough to work with for smaller projects is how memory intensive chromium is and how big the binary file size is due to bundling chromium. I think to circumvent this if somehow you could utilize the existing installation of chrome (that almost everyone has anyways) and run the framework through there.This would decrease the size of electron projects immensely.

**Comment by paulcbetts** [comment]
Not possible, sorry!

**Comment by aramodi** [comment]
Sorry if I'm too late, just discovered this issue. Could you please say why this is not possible?
