### ISSUE TITLE
at dev env disable "Not allowed to load local resource"

### ISSUE THREAD

**Issue by eisneim** [electron/electron#9347]
Hi, sorry to post an issue, I just wondering if there is a way to allow load local resource while the page is load via http?
at dev env, i use webpack-dev-server, so I load index page via http, but in my app, there's a HTML5 video player, so i need to access local video file, but Electron won't allow that.
```
"web-preferences": {
      "web-security": false,
  }
```
won't work
thanks for anyone who helps

**Comment by eisneim** [comment]
i solved issue by create ObjectURL for video and static images

**Comment by milu2003** [comment]
怎么解决的？
