### ISSUE TITLE
Add support for Touch Bar typing suggestions

### ISSUE THREAD

**Issue by LitoMore** [electron/electron#9349]
* Electron version: v1.6.7
* Operating system: macOS 10.12.4

### Expected behavior

**Make sure you have checked** `Touch Bar typing suggestion`

![](http://photo1.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0d/y2/55_465444.jpg)

English input source expected behavior

![](http://photo.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0d/y2/3g_465241.jpg)

Chinese input source expected behavior

![](http://photo3.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0d/y2/3k_465242.jpg)

### Actual behavior

English input source actual behavior

![](http://photo3.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0d/y2/8f_465038.jpg)

Chinese input source actual behavior

![](http://photo3.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0d/y2/3q_465238.jpg)

### How to reproduce

Add Chinese `Pinyin - Simplified` to your Input Sources

![](http://photo.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0d/y2/44_465413.jpg)

![](http://photo2.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0d/y2/4j_465403.jpg)

Open your Atom or any other Electron Apps (Google Chrome can reproduce this bug too), then just type something

![](http://photo.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0d/y2/9c_465069.jpg)

This first time you switch to Chinese input, type `nihao`, you may see this

![](http://photo1.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0d/y2/9d_465068.jpg)

You can switch to English input, now you see there is nothing on the Touch Bar

![](http://photo3.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0d/y2/8f_465038.jpg)

Now switch to Chinese input again, you can see this

![](http://photo3.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0d/y2/3q_465238.jpg)

**Comment by MarshallOfSound** [comment]
Not sure if this is possible because Chromium doesn't use native text views for inout.

**Comment by LitoMore** [comment]
I created the same issue on Chromium.
> [Chromium Issue #717553 - Add support for Touch Bar typing suggestions](https://bugs.chromium.org/p/chromium/issues/detail?id=717553)

**Comment by zcbenz** [comment]
Electron will automatically get his when Chromium add it, so I'm closing this since there is already an upstream issue tracking this, and we do not need to do anything in Electron.

**Comment by guidobouman** [comment]
I also asked this to the Chromium team, but is there a way to turn these suggestions off?

Something like `autocomplete="off"` does not work on a textarea.

Usecase:
VS Code suffers from text suggestions that override their debug state controls on the touch bar.

**Comment by bancona** [comment]
@guidobouman did you find an answer eventually? I am also looking to turn these suggestions off

**Comment by guidobouman** [comment]
Yes, it was fixed after Chromium, Electron and then VS Code made tiny changes:
https://github.com/microsoft/vscode/issues/84692
