### ISSUE TITLE
MenuItem: click() should forward browser event

### ISSUE THREAD

**Issue by bpasero** [electron/electron#935]
It would be nice to get access to the browser event that triggered the click on a MenuItem to inspect its properties. This would allow to change the behavior of an action based on modifier keys.

**Comment by bpasero** [comment]
@zcbenz trying latest, not sure I get the behavior I described. Does the click() function on a menu item now carry the browser event (mouse event)? I dont get it from either the top level menu, nor a context menu.

**Comment by zcbenz** [comment]
Oops, I thought the browser event meant `BrowserWindow` object, reopening now.

**Comment by bpasero** [comment]
@zcbenz thanks. what I really want to access is the state of keyboard modifier keys pressed at the time a menu item is pressed. I dont think I would expect to get access to the full browser event.

**Comment by xywz** [comment]
Related: #5992.
