### ISSUE TITLE
Copy keyboard shortcut has randomly no effect

### ISSUE THREAD

**Issue by alexstrat** [electron/electron#9352]
_I have been tracking this bug for weeks, it appears _a priori_ randomly. Can't determine if it's a bug on Electron-side or on my side. I'm posting the description here with the hope it rings someone's bell._

* Electron version: 1.6.6 - 1.7.1
* Operating system: MacOS 10.12.4

### Expected behavior
Select some text and hit <kbd>Cmd+C</kbd>
=> the selected text should be in clipboard, **everytime**

### Actual behavior
The <kbd>Cmd+C</kbd> shortcut works fine, but at some point, a priori randomly, the shortcut stops working (clipboard is not updated with the selected text):
- every following attempt fails until the app is restarted. Close/reopen the window has no effect.
- however if you use `copy` via the contextual menu, 1/ it actually copies and 2/ ~the keyboard shortcut start working again~ (not constantly)
- you can see the shortcut is triggered (can see the Edit menu "popping")
- other shortcuts (like <kbd>Cmd+V</kbd> paste) work fine during the moment <kbd>Cmd+C</kbd> does not work

### How to reproduce

I haven't found a way to constantly reproduce the bug.
My app is made of several `webviews` stacked on top of each other, and getting the focus alternatively with the appropriate z-index.
The afftected users are on OSX but I don't have users on other platform for now, and since I don't have consistent way to reproduce, i could not verify on other platforms.

The `applicationMenu` has a copy item of this kind:
```js
 {
        label: 'Copy',
        accelerator: 'Command+C',
        role: 'copy'
}
```
and the contextual menu:
```js
{
      id: 'copy',
      label: 'Copy',
      role: 'copy'
}
```

**Update:** I previously used `selector` for menu item declaration. I fixed this, but the problem remains. 
**Update (5/26):** Same behavior on 1.7.1.

**Comment by hungys** [comment]
Maybe the latest version of VS Code, which just upgraded its Electron to 1.6.6, also experienced the same issue...

https://github.com/Microsoft/vscode/issues/24112

**Comment by rebornix** [comment]
@alexstrat are you using English keyboard layout or others?

**Comment by alexstrat** [comment]
I'm using a U.S. keyboard, some of my users are using French keyboard. I have not noticed that keyboard layout makes a deterministic difference.

**Comment by tborychowski** [comment]
I have the same issue. "Copy" (using keyboard shortcut) randomly stops working.
I have one webview with a web-app loaded and need to copy the text from that app.

**Comment by alexstrat** [comment]
@tborychowski 👍  is that with https://github.com/tborychowski/github-browser ?

**Comment by k207899** [comment]
@alexstrat yes, it is :-)

**Comment by tborychowski** [comment]
@alexstrat, yes it is 😄

**Comment by dewyze** [comment]
I recently updated to Sierra, and once I tried my electron app after that, copy and paste stopped working entirely. I have the menus correctly set up. I am not sure if it is related to this, but I am seeing similar behavior and all other issues I can find reference needing to set up the menus (which I have set up correctly).

**Comment by dewyze** [comment]
Okay, my issue was related to kicking off the `npm start` inside a tmux on a mac. Running that outside of a tmux solves my problem. Sorry for the distraction.

**Comment by rebornix** [comment]
@dewyze what you run into is https://github.com/electron/electron/issues/916 :)

**Comment by hungys** [comment]
This issue also occurred on VS Code randomly, and I found that the copy/paste keyboard shortcuts were actually rebound to `control+option+command+c/v` (https://github.com/Microsoft/vscode/issues/28046), anyone found this on applications other than VS Code?

**Comment by zcbenz** [comment]
Does this ever happen to you in Chrome browser?

**Comment by tborychowski** [comment]
It never happened to me in Chrome.

**Comment by alexstrat** [comment]
Me neither

**Comment by guillaumearm** [comment]
I confirm this bug exists in `Electron v2.0.2` too

**Comment by miniak** [comment]
Does it still reproduce in Electron >= 3? The `<webview>` implementation has changed in Electron 3 and it might solve these issues.

**Comment by alexstrat** [comment]
I still have some reports of such bugs with Electron>=4. Though I realize now that, personally, I haven't experienced it for some time.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
