### ISSUE TITLE
webRTC leaks local ip address

### ISSUE THREAD

**Issue by albjeremias** [electron/electron#9355]
* Electron version: Any using webrtc
* Operating system: Any

### Expected behavior
My ip should not be leaked if i am behind a proxy or a vpn.

### Actual behavior
My ip addr from local network is leak

### How to reproduce
https://browserleaks.com/webrtc

**Comment by kevinsawicki** [comment]
Can you try using https://electron.atom.io/docs/api/web-contents/#contentssetwebrtciphandlingpolicypolicy with a value of `disable_non_proxied_udp`?

**Comment by Binom777** [comment]
@kevinsawicki Please pay attention to the end and possibly merge to #8866

**Comment by kevinsawicki** [comment]
Closing this out
