### ISSUE TITLE
The window can not be displayed when set both alwaysOnTop and transparent to true

### ISSUE THREAD

**Issue by amhoho** [electron/electron#9357]
```
new BrowserWindow({
//Can not be true at the same time
transparent: true,
alwaysOnTop:true
})
```
The window can not be displayed.

btw:
The window also can not be displayed when BrowserWindow set backgroundColor

**Comment by orlandoxu** [comment]
me too. windows 7. Don't know how to fix it.

**Comment by orlandoxu** [comment]
But, I have another plan.
set transparent: true
when the window created, set alwaysOnTop: true
It's work.

**Comment by zjxpcyc** [comment]
My problem is  the front window can't refresh or redraw when i change to other windows

**Comment by codebytere** [comment]
@amhoho what version and OS are you on? this issue will be easier to diagnose with this info :)

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/9357#issuecomment-333708056). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
