### ISSUE TITLE
shell openExternal() and openItem() hangs the app on Windows

### ISSUE THREAD

**Issue by vivekdaramwalwy** [electron/electron#9359]
shell.openExternal() and shell.openItem() with local file path hangs the app on Windows 10. It works fine on Mac though. Is there any solution for this on Windows?

This is what I am doing:

`shell.openExternal('file://' + this.filePath, (error) => {
    console.log("file opening error");
    console.log(error);
});`

Same thing happens if I try to open the file using shell.openItem().

**Comment by zcbenz** [comment]
Can you install VS Code and test whether its "Open in Explorer" feature hangs?

**Comment by codebytere** [comment]
Closing due to abandonment.
