### ISSUE TITLE
printToPDF custom pageSize ignored if width/height are not integers

### ISSUE THREAD

**Issue by logidelic** [electron/electron#9361]
This one drove me bonkers and took me a while to figure out:

* Electron version: 1.6.5
* Operating system: Windows 10

### Expected behavior

printToPDF, when accepting a custom pageSize object width/height, should allow for floating point numbers (and truncate to integer if needed).

### Actual behavior

If a non-integer value is specified for width or height, the values are silently ignored (in my tests, uses Letter sized paper instead of custom values).

### How to reproduce

```
var MICRONS_PER_IN = 25400;
var w = 3.5;
var h = 1.1
var opts = {pageSize:{width:(w*MICRONS_PER_IN), height:(h*MICRONS_PER_IN)}};
winPrint.webContents.printToPDF(opts, function(err, data) {
});
```

To make it work correctly, we can simply add parseInt:

```
var opts = {pageSize:{width:parseInt(w*MICRONS_PER_IN), height:parseInt(h*MICRONS_PER_IN)}};
```

**Comment by drulm** [comment]
Verified this behavior also.

**Comment by abhijithcs** [comment]
Is there a way we can set the width or height dynamically, say by passing a variable from the renderer process to the main process? #14293

**Comment by codebytere** [comment]
Given that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!
