### ISSUE TITLE
Linux/Mac OS support for `shell.writeShortcutLink` et al.

### ISSUE THREAD

**Issue by taktoa** [electron/electron#9362]
It would be nice and probably not too hard to have cross-platform support for [`shell.writeShortcutLink`][writeShortcutLink] and [`shell.readShortcutLink`][readShortcutLink].

On Linux, the comparable format is a [Desktop Entry][fdo-desktop] file. This is well-specified and can be parsed and printed using [libxdg][] (specifically with [this module][xdgapp.h]). Desktop Entry files support a lot of features that aren't supported by Windows `.lnk` shortcuts, so presumably we'd pick the lowest common denominator of features to support.

On Mac OS, the comparable format is an [alias file][alias-wiki], though it seems poorly specified (though it has been somewhat reverse-engineered) and feature-impoverished compared to its Linux/Windows equivalents. Might be able to use [this API][alias-manager] to create one, although it seems to be deprecated in favor of a semantically completely different API.

[writeShortcutLink]: https://electron.atom.io/docs/api/shell/#shellwriteshortcutlinkshortcutpath-operation-options-windows
[readShortcutLink]: https://electron.atom.io/docs/api/shell/#shellreadshortcutlinkshortcutpath-windows
[fdo-desktop]: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
[libxdg]: https://github.com/LiquidFM/libxdg
[xdgapp.h]: https://github.com/LiquidFM/libxdg/blob/master/src/desktop/xdgapp.h
[alias-wiki]: https://en.wikipedia.org/wiki/Alias_(Mac_OS)
[alias-manager]: https://developer.apple.com/reference/coreservices/alias_manager

**Comment by zcbenz** [comment]
On Linux the desktop files are usually created by package managers, none app I know writes the desktop file on the run, because it would require root privilege to put it to the right place.

For POSIX platforms you can just create symbol links with `fs` module.

**Comment by taktoa** [comment]
That's not true, since you can put a `.desktop` file in `~/.local/share/applications`. There are in fact applications that do this; for instance, Chromium does this when you install some Chrome Apps.

**Comment by zcbenz** [comment]
@taktoa I didn't know that, thanks for sharing.

The problem is `.desktop` is a complete different thing from shortcut links on Windows, `.desktop` has to be put in certain paths and it is desktop environment's responsibility to decide where to show the app's icon, while shortcuts links are just files that can be put anywhere like symbol links.
