### ISSUE TITLE
bootstrap from-group form-control email popover not show

### ISSUE THREAD

**Issue by oom-** [electron/electron#9363]
* Electron version: 3.3.7
* Operating system: Windows 10 x64 Pro

### Expected behavior

The popover from bootstrap should appear if the email not conains '@'.

Here : [BootStrap Forms](https://v4-alpha.getbootstrap.com/components/forms/#form-controls)

Like this : 
![issuegifok](https://cloud.githubusercontent.com/assets/11071671/25666369/a99a373c-3020-11e7-8575-898eb0928add.gif)

### Actual behavior

The popover from bootstrap does not appear.
![issuegifnotok](https://cloud.githubusercontent.com/assets/11071671/25666414/c8b8d772-3020-11e7-9fb2-c945742195aa.gif)

### How to reproduce

* Creation of new nodejs project in visual studio community
* Npm Commands : 
   * `npm install electron --save-dev`
   * `npm install electron --save-dev`
   * `npm install electron --save-dev`
* Go to Propertys of project
   * Set node.exe path to : `\node_modules\electron\dist\electron.exe`
* Copy pasta :
    * `main.js` in `app.js` from [https://github.com/electron/electron-quick-start](https://github.com/electron/electron-quick-start)
* Create index.html file : 

```html

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <title>Issue test</title>
</head>
<body>

    <form>
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <script>
        window.$ = window.jQuery = require('jquery');
        require('bootstrap');
    </script>
</body>
</html>
```

* Run

**Comment by MarshallOfSound** [comment]
Merging into #1043

**Comment by oom-** [comment]
Thank you
