### ISSUE TITLE
getUserMedia capturing same webcam streams

### ISSUE THREAD

**Issue by MPolymath** [electron/electron#9368]
* Electron version: 1.6.6
* Operating system: Ubuntu 16.04

### Expected behavior

On macintosh while connecting to two logitech BRIO.

The first logitech BRIO has the label: 
logitech Brio (####)

And the second has the label:
logitech Brio #2 (####)

This allows me to connect to two same model devices using the label variable from getUserMedia.

### Actual behavior

On Ubuntu 16.04 I am getting the first device named:

logitech BRIO (####)

The second device is named:

logitech BRIO (####)

### How to reproduce

Here is the repository in question:

Make sure that two of the same webcam models are connected to your computer:

git clone https://github.com/soixantecircuits/snapjerk/tree/dev
cd snapjerk
nvm use
yarn
yarn start

A chrome console will pop up with the labels of all webcams connected.

Did anyone encounter my problem, did you happen to find a solution?

**Comment by zcbenz** [comment]
Can you try whether Chrome browser has the same problem?

**Comment by codebytere** [comment]
Closing due to abandonment.
