### ISSUE TITLE
Update Menu Items

### ISSUE THREAD

**Issue by iamdriz** [electron/electron#937]
How can I update a Menu Item depending on an event?

For example I have two items for entering and leaving fullscreen:

```
{
    label: 'View',
    submenu: [
    {
        label: 'Enter Fullscreen',
        accelerator: 'Control+Command+F',
        click: function() {
            BrowserWindow.getFocusedWindow().setFullScreen(true);
        }
    },
    {
        label: 'Exit Fullscreen',
        accelerator: 'Control+Command+F',
        click: function() {
            BrowserWindow.getFocusedWindow().setFullScreen(false);
        }
    }
}
```

But I want to hide and show them depending if I'm fullscreen or not.

My idea was to create a menu for each state and then change the whole menu like:

```
mainWindow.on('enter-full-screen', function() {

    Menu.setApplicationMenu(menu);  
});

mainWindow.on('leave-full-screen', function() {

    Menu.setApplicationMenu(menu);
});
```

But this seems really bad and I'm not sure if you can change the Application Menu afterwards...

Plus I want to be able to enable and disable certain menu items depending on other events and context... is their a way to handle this?

**Comment by samueleaton** [comment]
Can someone add the "menu" label to this issue. It would have helped me find it earlier. Thanks

**Comment by fcoury** [comment]
How can one change a menu item label?

**Comment by niftylettuce** [comment]
See <https://github.com/atom/electron/issues/4097> I can't change `type` since it's readonly.
