### ISSUE TITLE
Error when building xde from source

### ISSUE THREAD

**Issue by rrjanbiah** [electron/electron#9371]
* Electron version: 1.6.7
* Operating system: Ubuntu 16.04.2 LTS (Ubuntu MATE) 32 bit

### How to reproduce

* Tried to build Xde from source based on https://github.com/expo/xde#build-from-source as for 32 bit Linux they didn't provide binary
* Came across some errors https://github.com/expo/xde/issues/97 (log files attached)
* Xde team suggested to check with Electron
* Initially posted in forum, but there is no response https://discuss.atom.io/t/error-when-building-xde-from-source/42250

Any hints about the error is highly appreciated. TIA

**Comment by kevinsawicki** [comment]
Are you able to successfully install Electron via `npm install electron` and run the sample app via `./node_modules/.bin/electron`?

**Comment by rrjanbiah** [comment]
@kevinsawicki Many thanks for your note.

Yes, I'm able to install electron like above and able to run this app https://github.com/hokein/electron-sample-apps/tree/master/file-explorer/main.js without any issue.

Does it mean that I'm doing anything wrong for xde?

**Comment by zcbenz** [comment]
I noticed that you were using `yarn` when building, can you try using `npm`?

**Comment by codebytere** [comment]
Closing due to abandonment.
