### ISSUE TITLE
multiple <input> focus problem

### ISSUE THREAD

**Issue by QuinDennis** [electron/electron#9375]
* Electron version:   v1.6.8
* Operating system: ubuntu 17.04

### Expected behavior

this example has four <input>s in a vertical table.  while you can <TAB> from one to another, you can't click to select the 4th, and can hardly select the 3rd

### Actual behavior
can't click input #4 to select it and enter

**Comment by kevinsawicki** [comment]
> How to reproduce

Can you provide a sample application that demonstrates this issue? Thanks.

**Comment by zcbenz** [comment]
Closing until more information is provided.
