### ISSUE TITLE
Electron should emit an event on Windows when the active user is switched

### ISSUE THREAD

**Issue by brandonwamboldt** [electron/electron#9376]
It would be great if Electron emitted an even when the currently logged-in user has changed (e.g. via fast-user switching). An example use case would be to disable intensive operations when the user isn't currently active.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
