### ISSUE TITLE
Click on a menu item programmatically

### ISSUE THREAD

**Issue by ivandroid** [electron/electron#9379]
I'm using electron 1.6.2 with macOS. Is there any possibility to click on a menu item programmatically? I need to start dictation this way. There is a "Start dictation" menu item in the edit menu.

Thanks in advance.
Ivan

**Comment by ivandroid** [comment]
I'm using electron 1.6.2 with macOS. Is there any possibility to click on a menu item programmatically? I need to start dictation this way. There is a "Start dictation" menu item in the edit menu. 

Thanks in advance.
Ivan

**Comment by zcbenz** [comment]
The "start dictation" menu is inserted by macOS automatically, it would be only possible with some Cocoa Accessibility API, which I'm afraid would be way too much work for a simple feature. Your best try is probably to write an AppleScript and then execute it.
