### ISSUE TITLE
Suggestion list flickers when using Chinese IME

### ISSUE THREAD

**Issue by alexandrudima** [electron/electron#9380]
* Electron version: 1.6.8 and 1.6.6
* Operating system: OS X El Capitan 10.11.3
* Extracted from https://github.com/Microsoft/vscode/issues/356

### Expected behavior

On a second use of Chinese IME the suggestion list should not flicker.
For example, it does not flicker in Chrome (tested with Chrome v58) in an `<input>` field. e.g. at https://jsfiddle.net/v1gz5c5m/1/

I am pressing <kbd>s</kbd>, <kbd>1</kbd>, <kbd>s</kbd>, <kbd>2</kbd>, <kbd>s</kbd>, <kbd>4</kbd>, <kbd>s</kbd>, <kbd>2</kbd>:

![good-chrome](https://cloud.githubusercontent.com/assets/5047891/25738375/fef1ff46-317c-11e7-971f-4ea63767f81e.gif)

### Actual behavior

On a second use of Chinese IME the suggestion list is positioned at the top left corner of the screen and then jumps to the correct location.

I am pressing <kbd>s</kbd>, <kbd>1</kbd>, <kbd>s</kbd>, <kbd>2</kbd>, <kbd>s</kbd>, <kbd>4</kbd>, <kbd>s</kbd>, <kbd>2</kbd>:

![bad-electron](https://cloud.githubusercontent.com/assets/5047891/25738471/9b6c3882-317d-11e7-8b05-53f8e8280aff.gif)

![bad-code](https://cloud.githubusercontent.com/assets/5047891/25738549/120c5f8a-317e-11e7-945a-9ff9d44512d7.gif)

### How to reproduce

* add an `<input>` to any Electron app. I can provide a full repro if you wish, but adding an `<input>` is trivial enough. 
* configure the keyboard preferences on OSX to use "Pinyin - Simplified"
* focus on the `<input>`.
* press <kbd>s</kbd>
* press <kbd>1</kbd> to accept the first suggestion (doesn't really matter which one AFAICT)
* press <kbd>s</kbd> again
* observe the suggestion list is positioned in the top left corner

**Comment by rebornix** [comment]
In addition to what @alexandrudima described, I found two interesting behaviors, especially the second one

**Pressing any character which doesn't require composition will help with popup positioning**
* Press <kbd>s</kbd>
* Press <kbd>1</kbd> to accept the first suggestion
* Press <kbd>1</kbd> to insert `1`
* Press <kbd>s</kbd> again
* Observe the suggestion list is positioned correctly, perfect.

any non-compositing character helps with the positioning

**if the page contains webview, then everything is good**
* add both `<input>` and `<webview>` to any Electron app.
* Try above all steps, everything is good.

**Comment by wangweixuan** [comment]
It seems solved in latest beta 1.7.3. I can't reproduce it any longer.
