### ISSUE TITLE
Copying OSX .app on Windows makes it non-executable on a Mac

### ISSUE THREAD

**Issue by mk010101** [electron/electron#9382]
I'm working on Builder project that creates Electron apps for both Mac and Windows.
If Builder is run on a Mac, both resulting .exe and .app work fine on the respective operating systems. However, if Builder is run on Windows, the Mac .app fails to launch with "The application “start.app” can’t be opened." message.

It if I then manually copy start.app/Contents/MacOS/Electron and start.app/Contents/Frameworks from the working app  to the non-working one, everything works fine.

I tried to manually set chmod +x for start.app/Contents/MacOS/Electron but it didn't solve the problem.

**Comment by MarshallOfSound** [comment]
@mk010101 The issue is linux'ish symlinks to not work on windows, if you need to transfer a mac app through a windows machine, ensure you zip it up first.

This isn't an Electron issue, it's an OS "feature" 👍

**Comment by mk010101** [comment]
Wow, that was really quick! 👍 
Thanks, I'll try that.
