### ISSUE TITLE
Paypal popup blocked

### ISSUE THREAD

**Issue by lowki** [electron/electron#9384]
* Electron version: 1.6.7
* Operating system: linux

### Expected behavior

Display the payment popup

### Actual behavior

Payment popup is blocked

### How to reproduce

Click the paypal button, popup window doesn't display.
Error in console : 
`Uncaught PopupOpenError {message: "Can not open popup window - blocked"}`

Here is a [repo](https://github.com/lowki/electron-test) for the test

**Comment by MehediH** [comment]
As far as I am aware Electron doesn't support popups. You will have to setup another window to open the popup url and then communicate with main window using ipc

**Comment by lowki** [comment]
This is not a real popup but a *lightbox*

**Comment by zcbenz** [comment]
I don't think PayPal API works for pages with `file://` protocol, you might try using a custom protocol.
