### ISSUE TITLE
clipboard.clear() does not clear primary (middle-click) clipboard in linux

### ISSUE THREAD

**Issue by adatum** [electron/electron#9386]
* Electron version: v1.4.15
* Operating system: Ubuntu 16.04 32-bit

### Expected behavior

`clipboard.clear()` should clear both primary (highlight/middle-click) and secondary (Ctrl-C/Ctrl-V) clipboards.

### Actual behavior

Only secondary clipboard is cleared.

### How to reproduce

Issue is observed in KeeWeb's desktop app, with Github issue filed here: https://github.com/keeweb/keeweb/issues/620

KeeWeb is a password manager made with Electron. It contains a setting (Settings -> Clear clipboard after copy) to clear copied passwords/text after a time delay. However, the primary clipboard is never cleared. 

The app contains a demo password database for easy testing.

**Comment by stekern** [comment]
Are there any updates on the status of this issue?

**Comment by codebytere** [comment]
This is an upstream issue in that Chromium does not monitor the middle-click keyboard at present and so [`Clear`](https://github.com/electron/electron/blob/e77d065875793418c58112e2e38b729f63e62234/atom/common/api/atom_api_clipboard.cc#L191-L193) only clears the secondary click board. I'd recommend you file an issue at crbug.com, and if something changes we'll of course return to this issue.
