### ISSUE TITLE
Ramping CPU Usage with Frameless Windows

### ISSUE THREAD

**Issue by simon-robertson** [electron/electron#9391]
When a BrowserWindow instance is created with the `frame` option set to `false`, the CPU usage of one of the Electron processes continuously ramps up to ~50% and then drops to ~10%. The ramping to ~50% takes about 30 seconds. None of the other available options appear to have an impact on the CPU ramping so I assume it is strictly related to frameless windows (possibly an aggressive GC cycle and/or memory leak).

The web content of the window was an empty HTML file, no CSS and no JS. None of the other running processes were causing the ramping.

````
Electron:  1.6.6
Processor: 1.50 GHz AMD E1-7010 APU with AMD Radeon R2 Graphics

Windows 10 64-bit
````

![ramp](https://cloud.githubusercontent.com/assets/20401399/25772897/275645ce-326c-11e7-9d3d-a33b2caf1d6a.png)

**Comment by CharlieHess** [comment]
We're also seeing some reports of increased CPU usage while idle on our latest release, which shipped with `1.6.3`. Reports are sporadic – will update here as we get more information.

**Comment by LukePulverenti** [comment]
Is this window also marked as transparent?

**Comment by simon-robertson** [comment]
@LukePulverenti - Yes and no. I tried numerous configurations, including both transparent and opaque windows, and the only thing that appeared to cause the heavy CPU ramping was the `frame` option.

**Comment by codebytere** [comment]
Closing due to abandonment.
