### ISSUE TITLE
Option to load index.html relative paths without file:// prefix

### ISSUE THREAD

**Issue by bertyhell** [electron/electron#9393]
* Electron version: 1.6.6
* Operating system: Window 10 x64

### Expected behavior

When you get a site working with http-server locally, you would expect it to easily work with electron as well. Unfortunately you need to prefix all the relative URLs to scripts, styles and asset files with file:// so that they load correctly.

### Actual behavior

Relative URLs in the index.html throw an error: file://styles.css wasn't found

### How to reproduce

* Clone the example electron repository
* Add a web folder that contains your website that works with http-server
* Run electron
* Bathe in errors

## Proposed solution:

Add an option to the loadUl options to specify the relative url folder.

```js
  mainWindow.loadURL(url.format({
    pathname: 'index.html',
    protocol: 'file:',
    slashes: true,
    baseUrl: 'wwwroot'
  }));
```

This would then trigger an extra file interceptor to be added to electron that modifies relative paths to that folder.

example:
```js
function createWindow() {
  const WEB_FOLDER = '';
  const PROTOCOL = 'file';

  electron.protocol.interceptFileProtocol(PROTOCOL, (request, callback) => {
      // // Strip protocol
      let url = request.url.substr(PROTOCOL.length + 1);

      // Build complete path for node require function
      url = path.join(__dirname, WEB_FOLDER, url);

      // Replace backslashes by forward slashes (windows)
      // url = url.replace(/\\/g, '/');
      url = path.normalize(url);

      console.log(url);
      callback({path: url});
  });

  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: false
    }
  });

  // and load the index.html of the app.
  mainWindow.loadURL(url.format({
    pathname: 'index.html',
    protocol: PROTOCOL + ':',
    slashes: true
  }));
```

**Comment by MarshallOfSound** [comment]
I think this is something that can (and really should) be solved in userland, either using a workaround like you described or by modifying your hrefs and srcs in your HTML files to work with relative paths instead of absolute "/" paths.

**Comment by bertyhell** [comment]
i disagree

Having a working website work inside of electron out of the box would be very helpful for people that are trying out electron for the first time.

**Comment by zcbenz** [comment]
While I think it might be a good optional feature to have, I'm afraid this is impossible with Chromium, logics handling `file:` are hardcoded everywhere and there is no single flag to change the behavior.

As a workaround you can use custom protocol in your app.

I'm closing this as won't fix.

**Comment by ChrisCates** [comment]
For anyone who uses build tools such `gulp` or `webpack` not only is this cumbersome and demands the user to specify directly to the filesystem for specific builds... It requires us to change our webpack build files to support specific protocols required by electron.

I would be happy to make a pull request and add a flag or an option when serving urls (maybe an overloaded function might be better) to support this feature.
