### ISSUE TITLE
What is stupid problem with PepperFlash - I don't understand - no success...

### ISSUE THREAD

**Issue by sourceskyboxer** [electron/electron#9395]
Please don't force me!

I always read Pepperflash for Electron already - no success
And suggestion by Japanese user but it looks old. made in Japan. But Japanese Languages - I already read code from Japanese Forum.
But I have already tried. Why does Electron 1.6.6 / 1.6.7 and 1.6.8 for Win 64 Bit.

I have copied from System32 for 64 Bit and SysWow64 for 32 Bit into app directory or root directory of electron.exe - It shows always "Couldn't load plugin"

Stop scamming me! I already write correctly. But it won't work?
```
 const electron = require('electron')
 const app = electron.app
 const BrowserWindow = electron.BrowserWindow
 
 const path = require('path')
 const url = require('url')
 let mainWindow
 function createWindow () {
   mainWindow = new BrowserWindow({width: 800, height: 600})
   mainWindow.loadURL(url.format({
     pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
     slashes: true
   }))
 
   mainWindow.on('closed', function () {
     mainWindow = null
   })
 }
 
 app.on('ready', createWindow)
 
 app.on('window-all-closed', function () {
   if (process.platform !== 'darwin') {
     app.quit()
   }
 })
 let ppapi_flash_path;
 
 if(process.platform  == 'win32'){
   ppapi_flash_path = path.join(__dirname, 'pepflashplayer64_25_0_0_148.dll');
 } else if (process.platform == 'linux') {
   // No tested I will edit later
   ppapi_flash_path = path.join(__dirname, 'libpepflashplayer.so');
 } else if (process.platform == 'darwin') {
   ppapi_flash_path = path.join(__dirname, 'PepperFlashPlayer.plugin');
 }
 
 app.commandLine.appendSwitch('ppapi-flash-path', ppapi_flash_path);
 app.commandLine.appendSwitch('ppapi-flash-version', '25.0.0.148');

 app.on('activate', function () {
   if (mainWindow === null) {
     createWindow()
   }
 })
```
electron is Windows 64 Bit 1.6.8

How do I fix? I already tried but not success.....

 ```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <webview src="http://www.adobe.com/software/flash/about/" width="100%" height="100%" plugins></webview>
    <!--<webview src="TestExternalInterface.html" autosize="on" plugin></webview>-->
  </body>

  <script>
    // You can also require other files to run in this process
    require('./renderer.js')
  </script>
</html>
```
It shows always "Couldn't load plugin"

**Comment by eyarz** [comment]
> I have copied from System32 for 64 Bit and SysWow64 for 32 Bit into app directory

System32 needs the 32 Bit version and SysWow64 needs the 64 Bit version

**Comment by sourceskyboxer** [comment]
Hello yes I know But System32 is 64 Bit and SysWow64 is 32 Bit - Please check correct flash player dlls different size 64 Bit is bit bigger than 32 Bit

**Comment by zcbenz** [comment]
I suggest copying the plugins from Chrome instead.

For future questions please seek help from [the community](https://github.com/electron/electron#community).
