### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by shyam1992** [electron/electron#9399]
Hi,
I guess my problem is very recurring, most of the first timers would have faced this.
I followed the build instructions for windows 32 bit architecture and getting this error on last step.
I googled for a day and got nothing, Please help this newbie to build first electron app.
![capture](https://cloud.githubusercontent.com/assets/6847851/25778492/a837cd88-331c-11e7-9316-f0a94baf1eed.PNG)

* Electron version: 1.6.6
* Operating system: windows 32 bit

### Expected behavior

###the build should have created the files in out folder

**Comment by MarshallOfSound** [comment]
>Please help this newbie to build first electron app.

You don't need to build Electron yourself to make an Electron application.  We ship prebuilts through the `electron` package on NPM.

FWIW fixing this should be as easy as running the bootstrap.

```bash
python script/bootstrap.py -v --dev
```

**Comment by shyam1992** [comment]
Thanks,

Now am getting an error which i could figure out what to do.
![capture1](https://cloud.githubusercontent.com/assets/6847851/25811095/bb246e1a-342f-11e7-9c81-6f98ee8401d0.PNG)

Trying to fix this.
Thanks again :)

**Comment by kevinsawicki** [comment]
Looks like you did not install the Visual C++ component.

Make sure you select to install it from the Visual Studio 2015 installer.

**Comment by shyam1992** [comment]
I couldn't complete it on windows due to some reasons. 
But i followed the steps mentioned for macOS in my mac it worked completely fine.
