### ISSUE TITLE
Need help on my sendcontact.php not functioning

### ISSUE THREAD

**Issue by charliemenruna** [electron/electron#9402]
<?php

// Define some constants
define( "RECIPIENT_NAME", "John Doe" ); //UPDATE THIS TO YOUR NAME
define( "RECIPIENT_EMAIL", "john@example.com" ); //UPDATE THIS TO YOUR EMAIL ID
define( "EMAIL_SUBJECT", "Website Visitor Message" ); //UPDATE THIS TO YOUR SUBJECT

// Read the form values
$success = false;
$senderName = isset( $_POST['name'] ) ? preg_replace( "/[^\.\-\' a-zA-Z0-9]/", "", $_POST['name'] ) : "";
$senderEmail = isset( $_POST['email'] ) ? preg_replace( "/[^\.\-\_\@a-zA-Z0-9]/", "", $_POST['email'] ) : "";
$original_message = isset( $_POST['message'] ) ? preg_replace( "/(From:|To:|BCC:|CC:|Subject:|Content-Type:)/", "", $_POST['message'] ) : "";
$message = 'Name: '.$senderName.'<br/>Email: '.$senderEmail.'<br/>Message: '.$original_message;

// If all values exist, send the email
if ( $senderName && $senderEmail && $message ) {
  $recipient = RECIPIENT_NAME . " <" . RECIPIENT_EMAIL . ">";
  $headers = "From: " . $senderName . " <" . $senderEmail . ">\n";
  $headers .= "MIME-Version: 1.0\n"; 
  $headers .= "Content-Type: text/HTML; charset=ISO-8859-1\n";
  $success = mail( $recipient, EMAIL_SUBJECT, $message, $headers );
}

if ( $success )
{
?>
	<script>
		window.location='thanks.html';
	</script>
<?php
}
else
{
	echo "<h1>There was a problem sending your message. Please try again.</h1>";
}
?>

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

I don't see the Electron issue here or even the relevance.  If you wish to use PHP in Electron you will need to set up your own back end to run your code

**Comment by charliemenruna** [comment]
@MarshallOfSound : I have a problem with my contact form every time I click the send button, that message will appear. I don't know how to fix this one, I have been trying my best but I really do need.
