### ISSUE TITLE
How to show popup menu on window icon click?

### ISSUE THREAD

**Issue by vivekdaramwalwy** [electron/electron#9403]
I want to hide default app menu on Windows and show it as popup menu on click of Window icon (left-top icon). I saw Slack for Windows is doing it. Is there a way I can achieve it or can I make window icon at top-left clickable?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

Slack do their window UI through a bit of custom CSS and custom dropdown logic in a frameless browserwindow.  If you want to replicate that you'll have to do something similar
