### ISSUE TITLE
I would like to ask why the official does not provide a real available debug version?

### ISSUE THREAD

**Issue by hbgong** [electron/electron#9410]
I was running my program using the official debug version of the electron and it ran well. but later I found it was not really debug version when i ran it in windbg , 
by looking at the official debug version of electron compilation options I found its runtime Library compilation option is using muti-threaded dll (/MD), 
so I modified the runtime library compilation option to muti-threaded dll debug (/MDd), 
I've compiled a new debug version of the electron from the new "MDd" option, and the underlying dependency of node and chromium also uses the new "MDd" option, the bad news is that the recompiled debug version simply can not run.
I would like to ask why the official does not provide a real available debug version?

**Comment by zcbenz** [comment]
Current Debug version of Electron is more like a version that builds quickly so it should be probably called "Development" version. To provide a real Debug version we would need to provide Debug versions of prebuilt binaries of libchromiumcontent, which we wouldn't like to do but haven't done yet.

Pull requests are welcomed if you are interested in working on this.
