### ISSUE TITLE
PDF plugin ignores webPreferences: { plugins: false }

### ISSUE THREAD

**Issue by rreimann** [electron/electron#9412]
* Electron version: 1.6.6
* Operating system: macOS 10.12.4

### Expected behavior

When creating a new `BrowserWindow` the [PDF plugin](https://github.com/electron/electron/pull/8435) should respect the BrowserWindow `webPreferences.plugins` option as stated in the [API documentation](https://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions):
> plugins Boolean (optional) - Whether plugins should be enabled. Default is false.

### Actual behavior

The plugin is always enabled. Even if `plugins` is explicitly set to `false` like that:
```
    mainWindow = new BrowserWindow({
      webPreferences: {
        plugins: false  // set it explicitly to false even if it should be the default
      }
    })
```

### How to reproduce

  $ git clone https://github.com/rreimann/electron-quick-start.git -b pdf-plugin-always-enabled
  $ npm install
  $ npm start || electron .

See that "Chromium PDF Viewer" is contained in the listed plugins and the PDF link opens the PDF Viewer instead of downloading the PDF as it would be the case if the plugin was not enabled.

**Comment by rreimann** [comment]
See https://github.com/electron/electron/issues/9030#issuecomment-299882777 for the current state of potential workarounds.

**Comment by deepak1556** [comment]
This was intended to avoid having users specify the option in enabling the PDF viewer. We can provide this as a temporary workaround until some of the pdf features are implemented. Instead of disabling the plugin I would recommend to stop intercepting pdf resource when this option is available, so that users can use `will-download` event. The option has to be respected [here](https://github.com/electron/electron/blob/master/atom/browser/atom_resource_dispatcher_host_delegate.cc#L127)

**Comment by rreimann** [comment]
> We can provide this as a temporary workaround until some of the pdf features are implemented.

IMHO there is a need for a permanent way to opt-out from using the PDF plugin. Either because an application want's to simply download PDFs instead of viewing them in place or because there is always _one more feature_ (e.g. displaying a TOC) that might require the usage of an alternative renderer like PDF.js.

**Comment by deepak1556** [comment]
> IMHO there is a need for a permanent way to opt-out from using the PDF plugin

Sounds good. Feel free to send a PR, thanks!
