### ISSUE TITLE
Geolocation not returning position

### ISSUE THREAD

**Issue by Vikaton** [electron/electron#9420]
* Electron version: v1.6.6
* Operating system: OSX
### Expected behavior

Return the position object usually return by `navigator.geolocation.getCurrentPosition`

### Actual behavior

Nothing is returned, yet this works on a regular chrome browser

### How to reproduce

this code in my `index.html` file

```js
function initMap() {
      let location;
      if("geolocation" in navigator) {
        console.log('Location services available')
        navigator.geolocation.getCurrentPosition(function(position) {
          console.log(position)
          location = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          }
          console.log(location)
          let map = new google.maps.Map(document.getElementById('map'), {
    				center: location,
    				scrollwheel: false,
    				zoom: 7
    			});
        });
      }
      else {
        document.getElementById('status').innerHTML = "Location Services not available!"
        return 0
      }
}
```

I have forked the quick start and added geolocation code, same set up to run: https://github.com/Vikaton/electron-quick-start

Am I missing something? Thanks!

**Comment by zeke** [comment]
How are you setting the GOOGLE_API_KEY environment variable?

Are you seeing any errors in the console? A 403, perhaps?

**Comment by Vikaton** [comment]
I didnt set the global API key before, but then added https://github.com/electron/electron/blob/master/docs/api/environment-variables.md#google_api_key to my main.js file, ran it again, and same results, no such luck :/

I'm not getting any errors at all in the console, does that fork I made work for you?

**Comment by zeke** [comment]
Are you sure your API key is configured to allow geocoding requests? Visit https://github.com/electron/electron/blob/master/docs/api/environment-variables.md#google_api_key for details.

**Comment by Vikaton** [comment]
Yup, didnt read all the way through, thanks!

**Comment by zeke** [comment]
👍

**Comment by avidas** [comment]
@zeke @Vikaton I have followed all those steps and I still have undefined getting returned.

**Comment by salmanSOFTECH** [comment]
I am not able to get the current location. I have set the GOOGLE_API_KEY variable as well. But all in vain

**Comment by svijaykoushik** [comment]
Hi, does Electron only support the Google Location Service API, or can we use other geolocation APIs for the browser window?

**Comment by ralyodio** [comment]
I don't think this works anymore.
