### ISSUE TITLE
Cannot install behind corporate firewall

### ISSUE THREAD

**Issue by egauci** [electron/electron#9424]
Windows 7:

```
C:\electron\project\node_modules\electron\install.js:47
  throw err
  ^

Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

```

**Comment by kevinsawicki** [comment]
Are you  using a proxy? Are you able to download it directly using https://github.com/electron/electron/releases/tag/v1.7.0 ?

**Comment by egauci** [comment]
Yes, there is a proxy. Environment variables for it are set. I'm able to install other things with npm and git. Node programs that make https connections out through the proxy will fail with this "local issuer certificate" message due to the proxy. They need to either disable certificate checking or use http. I have no control over this.

**Comment by abarajasmdo** [comment]
Hello, I have the same situation installing Electron... The situation is that I use to install it before, so I had a version working, but this week we try to install it a couple of times in diferent PCs and the problem is the same.  I even try to install old versions, and the same happen.

**Comment by pabloleban** [comment]
Did you try `npm config set strict-ssl false`?

**Comment by egauci** [comment]
@pabloleban Yes, that is the only way npm will work in my environment. However, this issue is not the npm cli itself, it is the post-install script. It should be fixable in that script, perhaps allowing non-strict ssl based on an environment variable.

**Comment by charles2359** [comment]
Exact same issue I am facing here. npm packages and git work fine. But the postinstall script failed due to certificate issues. Developing behind a company firewall has been such a challenge for me as a newer developer. And because our team doesn't work directly in IT, it's even more difficult. Any solution for this postinstall script?

**Comment by codebytere** [comment]
We recommend you utilize external tools available to you to properly configure your proxy, or do something like `npm config set strict-ssl false`. At present, this isn't something for which the optimal solution presents itself as a change to Electron itself.

**Comment by egauci** [comment]
@codebytere - thank you, we have moved away from trying Electron and went with nwjs. It is just not possible to use Electron in our environment.

To specifically address your suggestions: 1) I can't change the proxy configuration. It is configured correctly as required by corporate policy. 2) npm works just fine because I have the strict-ssl setting. The issue is the **Electron post install script** and it cannot be addressed by npm.

**Comment by MarshallOfSound** [comment]
@egauci Electrons postinstall script respects npms `strict-ssl` setting.  It does however download things Not From NPM.  It downloads zip files from GitHub releases, it's possible that your proxy is specifically blocking those requests rather than electrons postinstall script not working.

**Comment by egauci** [comment]
@MarshallOfSound Perhaps something has changed in the two years since I filed this issue, but it was definitely not the case before. The specific error message indicated that the strict-ssl setting was ignored by the script and I was able to manually download the github releases. As I said we had to move on to something that worked.

**Comment by howManyLevels** [comment]
Is there somewhere that clearly shows the steps to install electron from a binary download?

**Comment by ravivit9** [comment]
> npm config set strict-ssl false

The above didn't fixed issue. 

Anyone managed to get the electron installed ok?  This is only happening in my work computer but in my personnel computer it works fine and both on Windows.

**Comment by H3llsing** [comment]
Also for me it's not fixed.
trying to download electron 9.0.2
specified an cafile and set the strict-ssl option to false.
always getting the electron post install error
`
> node install.js                                                                                                                                                                                                                                                                                                                 RequestError: unable to get local issuer certificate                                                                                                                 at ClientRequest. (C:\Users\userName\Downloads\projectName\packager-test\node_modules\got\source\request-as-event-emitter.js:178:14)          at Object.onceWrapper (events.js:422:26)                                                                                                                         at ClientRequest.emit (events.js:327:22)                                                                                                                         at ClientRequest.origin.emit (C:\Users\userName\Downloads\projectName\packager-test\node_modules\@szmarczak\http-timer\source\index.js:37:11)            at TLSSocket.socketErrorListener (_http_client.js:432:9)                                                                                                         at TLSSocket.emit (events.js:315:20)                                                                                                                             at emitErrorNT (internal/streams/destroy.js:84:8)                                                                                                                at processTicksAndRejections (internal/process/task_queues.js:84:21)
--


`

**Comment by codecracker2020** [comment]
i just turned of my http_proxy and https_proxy and tried installing electron, its installing successfully.

**Comment by the-constant** [comment]
I also have the same issue behind our corporate firewall using our internal artifactory for the mirror. All correct proxy variables set. No other packages having issues. We are not allowed to access github from our work PC's.

I'd like to adopt electron into our development but I might have to use nwjs if this can't work out.

My error:

> `RequestError: self signed certificate in certificate chain`

This could be resolved if we `set NODE_TLS_REJECT_UNAUTHORIZED=0` but it's very insecure and not truly advisable. If we were able to pass certs into agentOptions into request, that'd be better, but I don't think electron exposes doing so. Either way, does electron _really_ need to go back to the web outside of npm? Why can't the binaries just be packaged up as an npm package and then installed through the repo?

**Comment by wdtracy** [comment]
Yep, we have to switch to nwjs as well.  Can't get this working =(

**Comment by dmadan86** [comment]
export NODE_TLS_REJECT_UNAUTHORIZED=0
Worked for me

**Comment by 0x53A** [comment]
just using `NODE_TLS_REJECT_UNAUTHORIZED` DIDNT'T work for me. I did manage to install electron with these variables:

```cmd
set ELECTRON_GET_USE_PROXY=1

set GLOBAL_AGENT_HTTPS_PROXY=http://localhost:8888
set GLOBAL_AGENT_HTTP_PROXY=http://localhost:8888

set http-proxy=http://localhost:8888
set proxy=http://localhost:8888
set HTTP_PROXY=http://localhost:8888
set HTTPS_PROXY=http://localhost:8888
```

----

## There is already the convention to use ``http_proxy`` and ``https_proxy``, can you please respect that instead of this ``ELECTRON_GET_USE_PROXY`` and ``GLOBAL_AGENT`` shit?

**Comment by jkleinsc** [comment]
@0x53A your comment was deleted as a violation of [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). You may consider this an official warning.

**Please do not interact with the project for 24 hours.** After that, please look through your open issues and edit them to ensure they're entirely on-topic, and we can continue the discussion here about the best way to go forward.

**Comment by scottfield** [comment]
> export NODE_TLS_REJECT_UNAUTHORIZED=0
> Worked for me

**Comment by jacany** [comment]
> export NODE_TLS_REJECT_UNAUTHORIZED=0
> Worked for me

Works.

**Comment by viningd45** [comment]
`export NODE_TLS_REJECT_UNAUTHORIZED=0`
Did not work for me. 

I still get the following: 
![image](https://user-images.githubusercontent.com/41274342/112687685-d6a5a680-8e45-11eb-96f7-1d8175559972.png)

**Comment by 0x53A** [comment]
Can you try

```
ELECTRON_GET_USE_PROXY=1

GLOBAL_AGENT_HTTPS_PROXY=http://localhost:8888
GLOBAL_AGENT_HTTP_PROXY=http://localhost:8888

http-proxy=http://localhost:8888
proxy=http://localhost:8888
HTTP_PROXY=http://localhost:8888
HTTPS_PROXY=http://localhost:8888
NODE_TLS_REJECT_UNAUTHORIZED=0
```

Not all of them might be required.

ref https://www.electronjs.org/docs/tutorial/installation#proxies

(replace ``http://localhost:8888`` with your own proxy)

**Comment by viningd45** [comment]
@0x53A 

Now I'm getting this error: 

`warning ..\package.json: No license field
info No lockfile found.
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
(node:15836) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests in
secure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[2/2] ⡀ electron
[2/2] ⠄ electron
error C:\Users\vininda\Desktop\projects\Test\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: C:\Users\vininda\Desktop\projects\Test\node_modules\electron
Output:
(node:23508) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests in
secure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
RequestError: write EPROTO 7540:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record
\ssl3_record.c:332:

    at ClientRequest.<anonymous> (C:\Users\vininda\Desktop\projects\Test\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.origin.emit (C:\Users\vininda\Desktop\projects\Test\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
`

all proxy environment variables are set to (using fiddler): `http://127.0.0.1:8888`
`ELECTRON_GET_USE_PROXY=1`
`NODE_TLS_REJECT_UNAUTHORIZED=0`
`$ node --version
v14.15.4`

Can't find many references on that error.

**Comment by samuelneff** [comment]
The above solutions didn't work for me. Oddly, clearing Electron's cache does (doesn't make sense why that would fix a connection issue).

```
rm -rf ~/Library/Caches/electron/*
```

**Comment by princ09** [comment]
Why closed? this issue hasn't been resolved. I am still getting same issue.

**Comment by KevBosch** [comment]
I face the same issue. It doesn't matter which settings i change the result is still the same:

error ...\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: C:\DATA\node\your-project-name\node_modules\electron
Output:
RequestError: write EPROTO 9060:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
    at ClientRequest.<anonymous> (C:\DATA\node\your-project-name\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.emit (node:domain:475:12)
    at ClientRequest.origin.emit (C:\DATA\node\your-project-name\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.emit (node:domain:475:12)

my settings are:
`ELECTRON_GET_USE_PROXY=1
GLOBAL_AGENT_HTTP_PROXY="myProxy(http....)
GLOBAL_AGENT_HTTPS_PROXY="myProxy(http....)
NODE_TLS_REJECT_UNAUTHORIZED=0
"`
i am able to download any other npm package the only problem is electron. Can somebody help me?

**Comment by DFG-kjtroll** [comment]
For anyone who is still struggling with this issue, I found a workaround on Windows:

- run `npm install electron` on a computer which is not behind the problematic proxy/firewall.
- copy the 'electron' folder from node_modules and transfer it to the computer with your electron project. store it somewhere safe and easy to get to as you may need it more than once.
(this may raise eyebrows with your IT department, but the fact that VSCode, Microsoft Teams, and Slack are all built on electron should put them at ease - mine trusts me.)
- in your electron project, run `$env:ELECTRON_SKIP_BINARY_DOWNLOAD=1; npm install`. This will install everything except it won't try to download the electron binary. at this point your project will crash when electron tries to start.
- drag your stashed electron folder into the node_modules folder and overwrite the incomplete one in there. Then your project works.

The problem now is, each time I run `npm install` or `npm add` even just for a single new package, it crashes on the reinstall. So I have to set `$env:ELECTRON_SKIP_BINARY_DOWNLOAD=1` but then it will overwrite my electron installation with an incomplete one and I have to replace the electron folder again.

So now I'm looking for a workaround for that. I may have to split my web app into its own project and have electron in a separate project that just imports everything and bootstraps the web app in an electron window...

**Comment by Loga-Shanmugam** [comment]
Thanks @DFG-kjtroll. It worked. For some weird reason set NODE_TLS_REJECT_UNAUTHORIZED was not working. When I included a $env like you did, it worked like a charm. Thanks a lot

**Comment by chladnefazole** [comment]
Everyone, this is not an Electron issue. NPM/Electron cannot connect to some external URL through your corporate proxy server, because it doesn't trust your corporate proxy's root certificates. If you are on a team then probably they already have a guide for how to set it up, ask your IT or team leader about it.

DO NOT set NODE_TLS_REJECT_UNAUTHORIZED=0 this is insecure. You should not be connecting to servers with untrusted CAs. This setting is there to protect you from downloading insecure or unverified packages. Everyone has heard this a million times and still people do it because it's easier. If you're using this, every time you install or update a package it puts your project at risk.

@h3llsing You need root CA certificates...someone in IT or sth will know what they are. You can maybe check them in your Windows cert store (Trusted Root Certification Authorities) but it's probably easier to ask some senior team member. From Windows cert store you can export each root cert as .crt (not PEM or DER) and then proceed as below. We have several root CAs for different levels of security, so I setup NPM to trust all of them:

Windows command line:
```
type rootCA1.crt > C:\Users\YOUR_USER\AppData\Roaming\npm\corpCAchain.crt
type rootCA2.crt >> C:\Users\YOUR_USER\AppData\Roaming\npm\corpCAchain.crt
type rootCA3.crt >> C:\Users\YOUR_USER\AppData\Roaming\npm\corpCAchain.crt
set NODE_EXTRA_CA_CERTS="C:\Users\YOUR_USER\AppData\Roaming\npm\corpCAchain.crt"
```
If you have VS Code open, close and re-open after changes (need to do this for PATH setting)

At this point everything should work, because NPM and Electron will trust your corporate certs defined in NODE_EXTRA_CA_CERTS variable.

If it doesn't work, you can try defining your corporate proxy URLs for Node to use:
```
http_proxy=http://proxy-url
https_proxy=http://proxy-url
HTTP_PROXY=http://proxy-url
HTTPS_PROXY=http://proxy-url
no_proxy="some-company-url,some-company-url-2" (necessary if you will be installing packages from company servers)
NO_PROXY="some-company-urls,some-company-url-2" (necessary if you will be installing packages from company servers)
registry=https://registry.npmjs.org/
```

If you connect manually to a corporate VPN, when you are connected/disconnected you will need to CHANGE your http_proxy & https_proxy to use the required URL.

So ex. we have locally installed proxy with one URL, and VPN proxy with another URL. If you have static URL set in Windows proxy settings, this is probably the URL you want. If you have a script in there then you'll need a different proxy URL at different times, based on some conditions the script is checking (ie. if you're connected to VPN or not). Make sure you don't copy the proxy script address and try to use it as the proxy URL.

If, after everything, it still doesn't work, maybe your corporate proxy is blocking the traffic. Make sure you as a user have the rights to use NPM.

**Comment by cwellsx** [comment]
I fixed it as described here:

- https://stackoverflow.com/a/44726189/49942
- https://stackoverflow.com/a/77893401/49942

The problem is:

- Electron binaries are downloaded from github.com
- Npm might not have the root certificate of the Authority which signed GutHub's certificate

The fix is:

- Navigate to GitHub using Chrome
- Export the page's root certificate, to a file on your machine
- Add the path to the file, to npm's `cafile` configuration

**Comment by XavierTheCreator** [comment]
Posting just in case there's still people experiencing this " Error: unable to get local issuer certificate" within a corporate dev environment

You can set node to use your company's certificate's using 
`$env:NODE_OPTIONS="--use-system-ca` 
`$env:NODE_USE_SYSTEM_CA="1"` 
inside of powershell. 

You can ensure that the command worked by doing `ChildItem env:NODE_OPTIONS`

In my case it allowed me to make my electron application using electron-forge without disabling security  

Note that im using node version v22.19.0
