### ISSUE TITLE
Cannot preventDefault event for BrowserWindow when this window is created via remote.BrowserWindow

### ISSUE THREAD

**Issue by EricTiger1986** [electron/electron#9428]
* Electron version: 1.4.16
* Operating system: Windows 7

### Expected behavior

In render process which the browser is created from, event can preventDefault.

### Actual behavior

event cannot preventDefault.

### How to reproduce

In render process:
const remote = require('electron').remote;
const {BrowserWindow, screen, ipcMain} = remote;
let browser = new BrowserWindow({
            x: _opts.x || 0,
            y: _opts.y || 0,
            width: 0,
            height: 0,
            frame: false,
            show: true,
            webPreferences: {
                webSecurity: false
            }
        });
browser.on('close', function(event) {
  event.preventDefault();                        // the browser still closed
});

**Comment by MarshallOfSound** [comment]
This is simply not possible as preventDefault has to be called synchronously inside the event listener, but event listeners attached through the remote module are always called asynchronously through IPC, you should really create your window in the main process and minimise usage of remote.
