### ISSUE TITLE
Disable BrowserWindow resizing dimensions from showing in top right of window?

### ISSUE THREAD

**Issue by frankhale** [electron/electron#943]
When resizing a frameless Browser Window the window dimensions show in the top right of the window. It would be great if this this could be disabled. It makes the window look different than a native windows.

**Comment by mhuggins** [comment]
Thanks for your follow-up comment, I didn't realize that's the only time it happens either. 😅

**Comment by johnzhu12** [comment]
I almost submitted same issue as you,LOL

**Comment by zandargo** [comment]
Another Electron beginner with the same "problem"... 😅
Thanks

**Comment by smartguy1196** [comment]
Another experienced Electron programmer with the same "problem" ... 🤡🤡🤡
Thanks

**Comment by BroJenuel** [comment]
haha oh men,, electron beginner, thanks to this
