### ISSUE TITLE
1.7.0 could not start with --debug / -debug argument

### ISSUE THREAD

**Issue by KagamiChan** [electron/electron#9434]
* Electron version: 1.7.0
* Operating system: macOS

### Expected behavior
Electron works with `--debug` or `-debug` argument

### Actual behavior
Electron won't run with arguments above.

### How to reproduce

I've tried the standalone .app and the npm modules:

- for standalone .app it shows an error and returns a non-zero
(with "IOVARendererID property not found" the welcome window appears and I've manually close it)
![image](https://cloud.githubusercontent.com/assets/3816900/25955449/e4d09a72-369b-11e7-894b-415231293022.png)

- for npm module it just won't start and no error returns
![image](https://cloud.githubusercontent.com/assets/3816900/25955695/84b36dee-369c-11e7-9d19-6014f13d9a50.png)

I can confirm the `--debug` works with previous versions including 1.6.9 beta

**Comment by kevinsawicki** [comment]
It looks like node has removed support for this flag in https://github.com/nodejs/node/pull/12197

I'm not sure this will still be supportable in v8 5.8 without #6634

**Comment by KagamiChan** [comment]
we use `--debug` argument just to set up a debugging/info printing flag of our own app, and I did not realize this relationship with nodejs before. We're OK to switch to another argument but I think it's better to get fixed. 

Besides (and maybe off topic), the `-debug` argument also hits this bug, is this something related to Electron's argv processing?

**Comment by kevinsawicki** [comment]
> Besides (and maybe off topic), the -debug argument also hits this bug, is this something related to Electron's argv processing?

Probably, it uses Chrome's argv parser, https://github.com/electron/electron/blob/190c9c916e7802a873f6469a74b1963014d1ea83/atom/browser/node_debugger.cc#L41 so both probably trigger this case.

**Comment by christoth** [comment]
--debug-brk which is always added by VS Code when debugging Electron (even with protocol="inspector") also causes Electron to crash.
Electron 1.7.0
Win10 x64
VS Code 1.12.1

**Comment by kevinsawicki** [comment]
Fixed by #9436
