### ISSUE TITLE
app.getpath('documents') returns wrong path

### ISSUE THREAD

**Issue by manndave** [electron/electron#9438]
* Electron version: 1.4.13
* Operating system: Windows 10

### Expected behavior

`app.getPath("documents")` should return the actual path to the user's "My Documents" folder, even if that location has been moved.

### Actual behavior

The path returned is always **\Users\<name>\Documents**.  In my case, I've used the properties window of Windows folders to move "My Documents" to **D:\My\Docs**.

### How to reproduce

1. Create a new electron project
2. Add code to write app.getpath("documents") to the console.
3. Run
4. See the output, then shut down the electron app
5. From Windows Explorer, right click your "My Documents" folder and select Properties
6. In the Properties window, select Location then click the Move button
7. Select a different location for your My Documents folder
8. Re-run the Electron app
9. Console app will still point to old location (even after rebooting)

**Comment by pseigo** [comment]
I tested this on the latest release of electron on Windows 10 and was **unable to reproduce the bug**. I moved the "Documents" folder using the "Move..." button in Windows explorer to different locations on the same drive as well as another drive. Each time I ran the electron project, the path written to the console was updated accordingly. I did not restart my computer between attempts.

## Versions
- Electron release v1.7.5
- Windows 10 v1607 build 14393.1593

**Comment by sofianguy** [comment]
Thanks for contributing!

We are no longer releasing bug fixes for versions of Electron older than 1.6x. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.
