### ISSUE TITLE
Let's link the dynamic VC runtime again

### ISSUE THREAD

**Issue by alespergl** [electron/electron#9443]
#5602 switched to static Visual C++ runtime, but there are issues with that:

- The runtime is unnecessarily duplicated in `node.dll` and `electron.exe`.
- #7281 reports that Electron-wide native exception handling is broken because exception handlers are applied per runtime instance.
- `node.dll` exports some symbols of the runtime, and when a native node module uses the dynamic runtime, it can mistakenly bind to those symbols instead of the ones from `msvcp140` and friends. This ends up causing crashes when an object is initialized using one instance of the runtime and destroyed using the other instance.
- Wrapper functions had to be [introduced](https://github.com/electron/electron/pull/5602/commits/e609a5bee290eb32d99278e9863ea48d77792a46) to make even Electron itself run correctly with the statically linked runtime.

The reason why it was decided to link the runtime statically was to "remove" a dependency on the Universal CRT (UCRT). That argument is weak, because the dependency is not actually removed, but merely UCRT is also statically linked and duplicated. Therefore the real argument is to not have to redistribute the UCRT binaries for non-updated Windows 7 systems and that is not a strong enough reason to justify the above problems.

So I am suggesting we move back to linking the VC runtime dynamically and redistribute it together with UCRT. I will prepare and submit a PR in the coming days.

**Comment by alespergl** [comment]
One more reason for doing this:
https://github.com/electron/libchromiumcontent/commit/7e7f7b93f25bfb4afe1099d8d9863709460f8db3#commitcomment-22137180

**Comment by computerquip-streamlabs** [comment]
> node.dll exports some symbols of the runtime, and when a native node module uses the dynamic runtime, it can mistakenly bind to those symbols instead of the ones from msvcp140 and friends. This ends up causing crashes when an object is initialized using one instance of the runtime and destroyed using the other instance.

This is actually blocking my current use case. If there's anything I can do to speed up a fix for this, that would be great. I can build myself but it complicates application distribution heavily (plus I'm not sure how to repackage the electron build since documentation on that seems to have been left out).

**Comment by alespergl** [comment]
Fixed, closing.
