### ISSUE TITLE
Unexpected token import!!!seems like i cannot use es6 syntax in the main process of electron

### ISSUE THREAD

**Issue by dandingol03** [electron/electron#9444]
electron version:v1.6.7
this is my main.js:
```js
import { registerHandlers, } from './src/handlers'
```
and this is the error:
```
import { registerHandlers, } from './src/handlers'
^^^^^^
SyntaxError: Unexpected token import

```

**Comment by tonyganch** [comment]
`import` is not currently implemented in Chromium or Node, to use it in your code you will need a transpiler.
Please see MDN for reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by enlight** [comment]
To expand on what @tonyganch said, you can use https://github.com/electron/electron-compile to transpile your code.
