### ISSUE TITLE
MenuItem click event

### ISSUE THREAD

**Issue by 99755Ajay** [electron/electron#9446]
I am new to electron. I want to know how to use menuItem in electron using vs code
I have written some code `const Menu = electron.Menu const remote = electron.remote
const MenuItem = electron.MenuItem  
const menu = new Menu()
const menuItem = new MenuItem()({
label: 'Inspect Element',
click: ()=> {
   remote.getCurrentWindow().inspectElement(rightClickPosition.x, rightClickPosition.y)
}
 

})

menu.append(menuItem)

window.addEventListener('contextMenu', (e) => {
  e.preventDefault()
  rightClickPosition = { x:e.x,y:e.y }
  menu.popup(remote.getCurrentWindow())
},false)
`

But I am getting error that **'Can not read property 'click of undefined''**

**Comment by hovancik** [comment]
Styling your post would help. See https://guides.github.com/features/mastering-markdown/

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
