### ISSUE TITLE
tray tooltip wont get updated/visible after app.hide() on macOS

### ISSUE THREAD

**Issue by hovancik** [electron/electron#9447]
* Electron version: 1.6.7
* Operating system: macOS

### Expected behavior

1. start app set tooltip - it is shown correctly
2. update tooltip every 10 seconds
3. open app window - tooltip is shown correctly
4. close the window and do `app.hide()` to get focus on last used app
5. update tooltip - it is  shown

### Actual behavior

1. start app set tooltip - it is shown correctly
2. update tooltip every 10 seconds
3. open app window - tooltip is shown correctly
4. close the window and do `app.hide()` to get focus on last used app
5. update tooltip - it is **not** shown

### How to reproduce
```
  $ git clone https://github.com/hovancik/electron-bug.git
  $ npm install
  $ npm start
```
Behavior in `Actual behavior` is done in app via timers, so all one does need to do is watch the tray tooltip: 

App starts, after 20 seconds window get opened, then closed after 5 seconds and so on.

**Comment by hovancik** [comment]
Any chance someone will look into it? It's still issue with `1.7.9`, I've updated repo.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by hovancik** [comment]
@codebytere the issue is still there with version 3, please reopen the issue

**Comment by hovancik** [comment]
@codebytere could you please also reopen? thanks ;]

**Comment by Ubadub** [comment]
@codebytere please reopen lol

**Comment by codebytere** [comment]
whoops lol sorry all! added the label and forgot the important reopening part

**Comment by hovancik** [comment]
still the same on electron 5

**Comment by codebytere** [comment]
This is a [system limitation](https://developer.apple.com/documentation/appkit/nsview/1483369-hidden?language=objc) we can't work around unfortunately :(

> A hidden view disappears from its window and does not receive input events. It remains in its superview’s list of subviews, however, and participates in autoresizing as usual. AppKit also disables any cursor rectangle, tool-tip rectangle, or tracking rectangle associated with a hidden view.

**Comment by hovancik** [comment]
@codebytere  I am not macOS dev but the documentation you links seems to be about different kind of tooltip - a tooltip for a defined area of the view, not a tooltip for tray (https://developer.apple.com/documentation/appkit/nsview/1483541-tooltip). 

We are not event talking about "A hidden view" mentioned in the Apple docs. Or am I missing something?
