### ISSUE TITLE
 help me to understand the scenario based on callstack (Teams!base::WaitableEvent::WaitMany)

### ISSUE THREAD

**Issue by psh0628** [electron/electron#9449]
hi

The renderer process tried to send a message to main process and it took more than 1 min at Teams!base::WaitableEvent::WaitMany. Basically, we have a monitoring thread to watch unresponsive state like below. If the thread below takes more than 1 min (consider as unresponsive state) we crash the app and restart it again.

questions
1) what kind of scenario generated such callstack below?
2) any idea why main process took more than 1min to give any signal?
3) any suggestion to fix this?

 # Child-SP          RetAddr           Call Site
00 000000b5`8ab38d48 00007ffd`b9acc2cf ntdll!ZwWaitForMultipleObjects+0x14 [d:\rs1.obj.amd64fre\minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 907] 
01 000000b5`8ab38d50 00007ffd`b9acc1ce KERNELBASE!WaitForMultipleObjectsEx+0xef [d:\rs1\minkernel\kernelbase\synch.c @ 1551] 
02 000000b5`8ab39050 00007ff6`5a594f26 KERNELBASE!WaitForMultipleObjects+0xe [d:\rs1\minkernel\kernelbase\synch.c @ 1403] 
03 000000b5`8ab39090 00007ff6`5b1ed69c Teams!base::WaitableEvent::WaitMany+0xf6 [c:\jenkins\workspace\libchromiumcontent-win\src\base\synchronization\waitable_event_win.cc @ 91] 
04 000000b5`8ab393f0 00007ff6`5b1ed220 Teams!IPC::SyncChannel::WaitForReply+0x6c [c:\jenkins\workspace\libchromiumcontent-win\src\ipc\ipc_sync_channel.cc @ 524] 
05 000000b5`8ab39440 00007ff6`5ae3dd2b Teams!IPC::SyncChannel::Send+0x210 [c:\jenkins\workspace\libchromiumcontent-win\src\ipc\ipc_sync_channel.cc @ 506] 
06 000000b5`8ab39540 00007ff6`5af1ee7d Teams!content::RenderThreadImpl::Send+0x5b [c:\jenkins\workspace\libchromiumcontent-win\src\content\renderer\render_thread_impl.cc @ 976] 
07 (Inline Function) --------`-------- Teams!content::ResourceDispatchThrottler::ForwardMessage+0x1f [c:\jenkins\workspace\libchromiumcontent-win\src\content\renderer\scheduler\resource_dispatch_throttler.cc @ 151] 
08 000000b5`8ab39570 00007ff6`5d780611 Teams!content::ResourceDispatchThrottler::Send+0x4d [c:\jenkins\workspace\libchromiumcontent-win\src\content\renderer\scheduler\resource_dispatch_throttler.cc @ 90] 
09 000000b5`8ab395d0 00007ff6`5d79c7e3 Teams!content::ResourceDispatcher::StartSync+0xf1 [c:\jenkins\workspace\libchromiumcontent-win\src\content\child\resource_dispatcher.cc @ 556] 
0a 000000b5`8ab39ab0 00007ff6`5d79cb6c Teams!content::WebURLLoaderImpl::Context::Start+0x743 [c:\jenkins\workspace\libchromiumcontent-win\src\content\child\web_url_loader_impl.cc @ 540] 
0b 000000b5`8ab3a770 00007ff6`5cd39b41 Teams!content::WebURLLoaderImpl::loadSynchronously+0xcc [c:\jenkins\workspace\libchromiumcontent-win\src\content\child\web_url_loader_impl.cc @ 1105] 
0c 000000b5`8ab3ac50 00007ff6`5cd39da0 Teams!blink::ResourceLoader::requestSynchronously+0xc1 [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\fetch\resourceloader.cpp @ 242] 
0d 000000b5`8ab3ad60 00007ff6`5cc6dd9b Teams!blink::ResourceLoader::start+0xa0 [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\fetch\resourceloader.cpp @ 86] 
0e 000000b5`8ab3adb0 00007ff6`5caf949c Teams!blink::Resource::load+0xfb [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\fetch\resource.cpp @ 352] 
0f 000000b5`8ab3ae40 00007ff6`5ccdcd19 Teams!blink::ResourceFetcher::requestResource+0x6ac [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\fetch\resourcefetcher.cpp @ 499] 
10 000000b5`8ab3b000 00007ff6`5cba19fa Teams!blink::RawResource::fetchSynchronously+0xd9 [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\fetch\rawresource.cpp @ 43] 
11 000000b5`8ab3b100 00007ff6`5cba39fb Teams!blink::DocumentThreadableLoader::loadRequest+0x3ba [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\loader\documentthreadableloader.cpp @ 925] 
12 (Inline Function) --------`-------- Teams!blink::DocumentThreadableLoader::dispatchInitialRequest+0xa2 [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\loader\documentthreadableloader.cpp @ 256] 
13 000000b5`8ab3bde0 00007ff6`5cba1e48 Teams!blink::DocumentThreadableLoader::start+0x5ab [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\loader\documentthreadableloader.cpp @ 249] 
14 000000b5`8ab3c1a0 00007ff6`5cbebac7 Teams!blink::DocumentThreadableLoader::loadResourceSynchronously+0x68 [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\loader\documentthreadableloader.cpp @ 129] 
15 000000b5`8ab3c1e0 00007ff6`5ccac4be Teams!blink::ThreadableLoader::loadResourceSynchronously+0x57 [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\loader\threadableloader.cpp @ 62] 
16 000000b5`8ab3c220 00007ff6`5ccaff73 Teams!blink::XMLHttpRequest::createRequest+0x68e [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\xmlhttprequest\xmlhttprequest.cpp @ 948] 
17 000000b5`8ab3c4a0 00007ff6`5ccb080f Teams!blink::XMLHttpRequest::send+0x343 [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\xmlhttprequest\xmlhttprequest.cpp @ 742] 
18 000000b5`8ab3c530 00007ff6`5c8c9f66 Teams!blink::XMLHttpRequest::send+0x11f [c:\jenkins\workspace\libchromiumcontent-win\src\third_party\webkit\source\core\xmlhttprequest\xmlhttprequest.cpp @ 687] 
*** WARNING: Unable to verify checksum for node.dll
19 000000b5`8ab3c560 00007ffd`8fa86572 Teams!blink::XMLHttpRequestV8Internal::sendMethod+0x126 [c:\jenkins\workspace\libchromiumcontent-win\src\out\release_x64\gen\blink\bindings\core\v8\v8xmlhttprequest.cpp @ 427] 
1a 000000b5`8ab3c620 00007ffd`8f90405f node!v8::internal::FunctionCallbackArguments::Call+0x152 [c:\jenkins\workspace\libchromiumcontent-win\src\v8\src\api-arguments.cc @ 17] 
1b 000000b5`8ab3c6f0 00007ffd`8f8e3faa node!v8::internal::`anonymous namespace'::HandleApiCallHelper+0x52f [c:\jenkins\workspace\libchromiumcontent-win\src\v8\src\builtins.cc @ 4737] 
1c (Inline Function) --------`-------- node!v8::internal::Builtin_Impl_HandleApiCall+0x4e [c:\jenkins\workspace\libchromiumcontent-win\src\v8\src\builtins.cc @ 4754] 
1d 000000b5`8ab3c830 00000231`54808bab node!v8::internal::Builtin_HandleApiCall+0x6a [c:\jenkins\workspace\libchromiumcontent-win\src\v8\src\builtins.cc @ 4751] 

Thanks

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
