### ISSUE TITLE
Spurious scroll gesture in 1.7.0 (macOS)

### ISSUE THREAD

**Issue by omarkilani** [electron/electron#9452]
I can't reproduce this, but I've seen it a couple of times and so I just wanted to put it here in case someone else runs into it.

Every once in a while after using the trackpad to scroll content, the webView will receive a spurious scroll gesture that moves the content all the way to the bottom.

Never seen this happen in 1.6.x. Does not happen in Chrome 58. Seems to be a 1.7.x thing.

**Comment by codebytere** [comment]
We haven't gotten more information for this so i'm going to go ahead and close it.
