### ISSUE TITLE
nativeWindowOpen option

### ISSUE THREAD

**Issue by snene** [electron/electron#9453]
https://github.com/electron/electron/blob/master/docs/api/window-open.md#use-native-windowopen

The above documentation talks about nativeWindowOpen available as webPreference. I tried the Electron pre-release version 1.7.0 but it doesn't seem to support it. Which version has support for it?

Thanks,
Shilpa

**Comment by kevinsawicki** [comment]
This is on master and hasn't been released yet, it will be included in 1.7.1 which should be out next week.

**Comment by snene** [comment]
Thank you @kevinsawicki ! Will wait for that release....
