### ISSUE TITLE
BrowserWindow isClosable returns true even if there is modal pop-up

### ISSUE THREAD

**Issue by tdhawan** [electron/electron#9454]
* Electron version:1.6.7
* Operating system: Mac OS 10.12.4

### Expected behavior

 browser window should return isClosable() as false, which is not expected.
Window close menu is getting disabled, which is expected.

### Actual behavior

 browser window is returning isClosable() as true

### How to reproduce
1. Open Your Electron App
2. Open a modal pop-up
3. Check for window.isClosable()

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
