### ISSUE TITLE
Windows/ARM support

### ISSUE THREAD

**Issue by TheBrokenRail** [electron/electron#9456]
### Why?

_This would be useful for things such as the Windows 10 IoT core or a jail broken Windows RT device._

**Comment by kevinsawicki** [comment]
> Build for Windows ARM?

There is not one today, Electron on provides ARM builds on Linux.

I don't believe Chrome runs on Windows ARM yet so support there would need to happen first.

There might be a better Chrome issue that requests this, but I found https://bugs.chromium.org/p/chromium/issues/detail?id=489037 which discusses ARM a bit, you may want to subscribe to that issue for updates.

Closing this out here, this can be revisited if/when Chrome adds support for Windows ARM.

**Comment by Ecnassianer** [comment]
Thanks for the info!

**Comment by MikeFarrington** [comment]
This looks to be a better Chromium development thread to track: [Enable Chromium support for Windows 10 ARM64 ](https://bugs.chromium.org/p/chromium/issues/detail?id=893460)

Someone has been hard at work on adding ARM64 support to Chromium.  I think it may be time to re-open this.

**Comment by nornagon** [comment]
We discussed this in a recent meeting and we're happy to support Electron on Windows on ARM as soon as Chromium does :)

**Comment by compnerd** [comment]
@nornagon seems that chromium support is now enabled for Windows ARM64 (and is being tested).

**Comment by richard-townsend-arm** [comment]
Now that #20244 has been merged  (hopefully the documentation will go onto the website shortly) and 6.0.9 has been released, this should be done for now. We’ll continue to improve node-gyp etc to make sure it’s as easy as possible to port electron apps to Windows on Arm.

**Comment by zcbenz** [comment]
I'm closing this issue since Windows on ARM had already been supported.
