### ISSUE TITLE
StartCom and WoSign certs still trusted by Electron (node update required for Electron 1.6.x)

### ISSUE THREAD

**Issue by ikkisoft** [electron/electron#9457]
_As discussed via email, opening a public issue so that we can discuss this issue further._

While analyzing the changelog of Node.js, I've noticed a security update that hasn’t been ported to Electron since February 2017. 

On 2017-02-21, Node.js 7.6.0 release included the following pull request:
[https://github.com/nodejs/node/pull/9469](https://github.com/nodejs/node/pull/9469)

This change was made to distrust SSL certificates issued after Oct. 21, 2016 by StartCom and WoSign. As you may remember, these CAs issued unauthorized certs for major sites - see [theregister.co.uk article](https://www.theregister.co.uk/2016/11/02/google_punts_wosign_startcom_from_good_guy_certificate_club/)

Since Electron 1.6.x is still on Node 7.4.0, certificates issued by StartCom and WoSign are still trusted thus can be used for MiTM. I’ve verified this by looking at libnode.dylib in the pre-compiled Electron.

* Electron version: < 1.7 (beta)
* Operating system: All

### Next steps

While the latest Electron beta (1.7.0) ships with Node 7.9, it could make sense to backport this change to the 1.6.x family. I am not aware of abuses in the wild using those certificates, but it seems like the most prudent course of action.

**Comment by kevinsawicki** [comment]
Fixed by #9499
