### ISSUE TITLE
why the titleBar is hidden in setting fullScreen

### ISSUE THREAD

**Issue by evildancer** [electron/electron#9458]
* Electron version: 1.6.7
* Operating system: win  x64

**Comment by kevinsawicki** [comment]
> Operating system: win x64

What version of Windows are you on?

> How to reproduce

Can you include the options you are passing to the `BrowserWindow` constructor or more instructions to reproduce the issue you are reporting?

**Comment by faststare** [comment]
win = new BrowserWindow({
		width: 1050,
		height: 650,
		fullscreen: true,
		frame: true
});

titlebar app was missing with this kind of paramaters/arguments/options.

**Comment by codebytere** [comment]
Closing due to abandonment.
