### ISSUE TITLE
BrowserWindow ignores Session option

### ISSUE THREAD

**Issue by NekoDragonica** [electron/electron#9461]
![ignores_session](https://cloud.githubusercontent.com/assets/18134406/26034495/5d029e4c-38f8-11e7-9939-ce2488650ed6.JPG)

The very same thing happened to proxy settings too, so it's not exclusive to cookies.

**Comment by deepak1556** [comment]
The session property should be specified as a part of [webPreferences](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions) 

```
win = new BrowserWindow({
    webPreferences: {
        session: ses
    }
})
```

Closing this out, thanks!
