### ISSUE TITLE
Installing electron with root user

### ISSUE THREAD

**Issue by hosseinamin** [electron/electron#9463]
### Setup
```
$ npm -v
4.2.0
$ node -v
v7.9.0

```
### Error
```
module.js:472
    throw err;
    ^

Error: Cannot find module '/home/<user>/whatsapp-web-operator/node_modules/electron/install.js'
```

When i tried with `root` user i was getting this error. After some attempts to fix it. I did found that it will work if user is not `root`.

This setup for for an aws ec2 server.

Maybe I'm wrong.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
