### ISSUE TITLE
Get Frame Menu on frameless BrowserWindow?

### ISSUE THREAD

**Issue by Bizarrus** [electron/electron#9464]
Is the `BrowserWindow` `frameless`, the `Menu` don't shows, thats is the default behavior.

For `frameless` window, i wan't to render it over JavaScript/HTML.

How i can get the Menu, when it's set over `Menu.buildFromTemplate` to iterate the entries?

My first try was this:

    const win = Remote.getCurrentWindow();
    const men = Remote.Menu;
    console.log({
        modal:	win.isModal()
    });
    console.log(men);

But the result shows only native code like `function Menu() { [native code] }`.

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
