### ISSUE TITLE
TypeError: BrowserWindow.addDevToolsExtension is not a function

### ISSUE THREAD

**Issue by 99755Ajay** [electron/electron#9466]
`const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow
const Menu = electron.Menu
const path = require('path')
const url = require('url')
const remote = electron.remote
const MenuItem = electron.MenuItem
//const remote = require('remote')
let mainWindow

let rightClickPosition = null

function createWindow () {
  mainWindow = new BrowserWindow({width: 800, height: 600})

  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))
}

app.on('ready', createWindow)

BrowserWindow.addDevToolsExtension('/Users/ajay.NEUROSPEECH/AppData/Local/Library/Application Supoort/Google/Chrome/User Data/Default/Extensions/mboefdeomkdlbekljcecbfimmecffgje/1.85_0')
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})

`
This is the above code.But I am facing the error that BrowserWindow.addDevToolsExtension is not a function.What I am doing wrong.Please someone suggest.

Thanks

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

The docs for `BrowserWindow.addDevToolsExtension()` state:
> This API cannot be called before the ready event of the app module is emitted.

You're attempting to call it before the `ready` event is emitted.
