### ISSUE TITLE
JIRA can`t be opened by electronjs

### ISSUE THREAD

**Issue by avengerweb** [electron/electron#9467]
https://issues.apache.org/jira/secure/Dashboard.jspa when try to open from chromium no problems
When I try to use electronjs a have a lot of JS errors.

**Comment by MarshallOfSound** [comment]
@avengerweb Disable `nodeIntegration` on your BrowserWindow 👍

**Comment by avengerweb** [comment]
Thx https://electron.atom.io/docs/all/#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron
