### ISSUE TITLE
[typescript definition] wrong signature for NativeImage.createFromDataURL

### ISSUE THREAD

**Issue by farfromrefug** [electron/electron#9469]
I am using electron 1.6.9.beta

Within electron.d.ts, the signature for createFromDataURL is:
```typescript
    static createFromDataURL(dataURL: string): void;
```
when it should be
```typescript
    static createFromDataURL(dataURL: string): NativeImage;
```

**Comment by MarshallOfSound** [comment]
@farfromrefug PR is up to fix the return type, thanks for picking up on this 👍

**Comment by farfromrefug** [comment]
@MarshallOfSound thank YOU, that was fast!
