### ISSUE TITLE
browserWindow.setPosition(x,y) changed window size (windows/linux) with non default scaleLevel (125% for example)

### ISSUE THREAD

**Issue by dregenor** [electron/electron#9477]
* Electron version: 1.6.5
* Operating system: windows/ kubuntu(probably also ubuntu, i not checked)

### Expected behavior

SetPosition should change only position, not size

### Actual behavior

when i change window position, windows size also changed

### How to reproduce

on windows:
1) setup scale level 125% 
![image](https://cloud.githubusercontent.com/assets/1700057/26071588/4e3c6276-39b1-11e7-9479-5f91df65cde2.png)

2) create new BrowserWindow with size (400x400 for example)
3) call window.setPosition several times (with different coordinates)
on every position changing window size will be increasing on 1-2 or 3 pixels

Same problem for kubuntu with scaling between 1 and 1.5

**Comment by dregenor** [comment]
text example
https://github.com/dregenor/electron-quick-start

**Comment by guanyong1993** [comment]
Has this problem been solved？ I recently discovered the problem, on windows x86 Electron 1.7.5.
Only in the HD screen(window scale 125%)。But I solved him with a stupid way:

`
win.setPosition(x, y);
win.setSize(width, height);
`

I hope Electron Team Fix it as soon as possible! Thanks!

**Comment by Polunom** [comment]
As referenced by @danailbd,
```
win.setBounds({
    width: win.getSize()[0],
    height: win.getSize()[1],
    x: x,
    y: y
});
```
works flawlessly. Perhaps Electron can change the implemention of `setPosition()` to call `setBounds()` instead, with implied width and height.

**Comment by erguotou520** [comment]
Not work for frameless window on win10 electron@2.0.6. It still change to size even call `setBounds`.

**Comment by parkerholladay** [comment]
Same issue with electron 3.0.8 on windows 10

**Comment by kepi0809** [comment]
issue from last year and still nothing? :/ that's sad, because for me sent contentsize didn't solve the problem because it had a "shaking" effect in result which isn't optimal ux

**Comment by sfatihk** [comment]
setBounds() works fine for me.
OS: Windows 10

```js
const W_WIDTH = 380;
const W_HEIGHT = 300;

window = new BrowserWindow({
  width: W_WIDTH,
  height: W_HEIGHT,
  show: false,
  frame: false,
  fullscreenable: false,
  resizable: false,
  useContentSize: true,
  transparent: false,
  alwaysOnTop: true,
  webPreferences: {
    backgroundThrottling: false
  }
});

//...

const changePosition = ()=>{
  const position = calculateWindowPosition();
  window.setBounds({
      width: W_WIDTH,
      height: W_HEIGHT,
      x: position.x, //always changes in runtime
      y: position.y //always changes in runtime
    });
}
//...
```

**Comment by tinyAdapter** [comment]
Still not fixed in electron 4.0.3 :(

**Comment by codebytere** [comment]
The issue here seems to be that `getSize` returns incorrect values, because `setPosition` is currently implemented with `setBounds` as seen [here](https://github.com/electron/electron/blob/9439ac108dff65ceadb1f5237a2e9c635cb2b809/atom/browser/native_window.cc#L191-L193).

**Comment by fgeller** [comment]
I'm still seeing this issue: I'm trying to change only the height of a window.
If I'm just trying to maintain window height and position, I need to apply the following:

```javascript
  let bounds = win.getBounds();
  bounds.x = bounds.x + 1;
  bounds.y = bounds.y + 1;
  bounds.width = bounds.width - 2;
  bounds.height = bounds.height - 2;
  win.setBounds(bounds);
```

So if I want to change the height, I need to apply it as follows:

```javascript
  let bounds = win.getBounds();
  bounds.x = bounds.x + 1;
  bounds.y = bounds.y + 1;
  bounds.width = bounds.width - 2;
  bounds.height = height - 2;
  win.setBounds(bounds);
```

I'm seeing this on Linux Electron v10.1.2 for a frameless window with a text scale level of 0.75.

Is there any less hacky way to get around this issue?

**Comment by Fental** [comment]
Still not fixed in electron 11.1.1 :(

**Comment by mikekreeki** [comment]
I have a customer reporting what looks like the same bug. He is on Windows 10 and the app runs on Electron 13.

**Comment by liuyike98** [comment]
still not fix on 15.3.0!!!!!!! only change the position, but the size will be larger!

**Comment by pjmattingly** [comment]
Still not fixed in Windows 11 Electron 17. =/

**Comment by oinochoe** [comment]
Still not fixed in Windows 11 Electron 19.  : (

**Comment by Jakentop** [comment]
Still not fixed in Windows 10 Electron 22.3. :( :(

**Comment by fzf404** [comment]
Still not fixed in Windows 11 Electron 26.2.1

**Comment by Mero-Plaform** [comment]
What a pun, still an issue through 6 years...

@sfatihk option works for me, just don't forget to provide not just the coords (x, y) but the sizes (width/height)
>
>```
>window.setBounds({
>      width: W_WIDTH,
>      height: W_HEIGHT,
>      x: position.x, //always changes in runtime
>      y: position.y //always changes in runtime
>    });
>```

**Comment by PieceOfFall** [comment]
Is any electron's developer here???

**Comment by richardwang001** [comment]
> What a pun, still an issue through 6 years...
> 
> [@sfatihk](https://github.com/sfatihk) option works for me, just don't forget to provide not just the coords (x, y) but the sizes too (width/height)
> 
> > ```
> > window.setBounds({
> >      width: W_WIDTH,
> >      height: W_HEIGHT,
> >      x: position.x, //always changes in runtime
> >      y: position.y //always changes in runtime
> >    });
> > ```

This works for me, except that the window is a little shaky ！ o(╥﹏╥)o

**Comment by kisamahigashi** [comment]
35.0.1
Still an issue.

this may help:
```
let size=win.getSize();
win.setPosition(x,y,true); 
win.setSize(size[0],size[1],true);
```

**Comment by kisamahigashi** [comment]
> 35.0.1 Still an issue.
> 
> this may help:
> 
> ```
> let size=win.getSize();
> win.setPosition(x,y,true); 
> win.setSize(size[0],size[1],true);
> ```

If used for dragging windows, you can turn off animations to improve performance, I hope it can help you.
