### ISSUE TITLE
ReleaseNotes windows

### ISSUE THREAD

**Issue by ksuwala** [electron/electron#9482]
Referring to https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

How do you handle releaseNotes on windows, when only releaseName is available?

**Comment by kevinsawicki** [comment]
Release notes are not available from the auto updater library used on Windows, they are only available on macOS.

You can download them another way like making a HTTP request directly to an endpoint that serves your release notes or using the GitHub releases API if that is an option for you.

Closing this out.
