### ISSUE TITLE
execFile got Error: spawn EACCES under asar

### ISSUE THREAD

**Issue by altjz** [electron/electron#9490]
* Electron version: v1.6.6, v2.0.8
* Operating system: 10.12.4 (16E195)

### Expected behavior
According to the [documentation](https://electron.atom.io/docs/tutorial/application-packaging/#extra-unpacking-on-some-apis), Electron asar support `execFile`

### Actual behavior
But I got this error, when I try to use execFile.
```
Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at exports.execFile (child_process.js:160:15)
    at module.(anonymous function) (ELECTRON_ASAR.js:219:18)
    at Object.<anonymous> (/Users/alex/temp/electron-vue/electron-quick-start/dist/mac/electron-quick-start.app/Contents/Resources/app.asar/main.js:16:1)
    at Object.<anonymous> (/Users/alex/temp/electron-vue/electron-quick-start/dist/mac/electron-quick-start.app/Contents/Resources/app.asar/main.js:80:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

### How to reproduce
Here is my Code of main.js. I'm using `electron-quick-start`
```javascript
const electron = require('electron')
const logger = require('electron-log')
logger.transports.file.level = true;
// Module to control application life.
const app = electron.app
// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow

const path = require('path')
const url = require('url')

const execFile = require('child_process').execFile

execFile(path.join(__dirname, 'avrdude', 'avrdude'), (error, stdout, stderr) => {
  if (error) {
    logger.error(error)
  }
  logger.info(stderr)
  logger.info(stdout)
})
```
I am using electron builder to build a bundle app in macOS. Here is my package.json
```json
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build": "build"
  },
  "build": {
    "appId": "com.example.demo",
    "files": [
      "avrdude/",
      "node_modules/",
      "package.json",
      "index.html",
      "main.js",
      "renderer.js"
    ]
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "~1.6.2",
    "electron-builder": "^17.5.0"
  },
  "dependencies": {
    "electron-log": "^2.2.6"
  }
}
```
Here is the asar directory
```shell
asar list electron-quick-start.app/Contents/Resources/app.asar
/index.html
/main.js
/package.json
/renderer.js
/node_modules
/node_modules/electron-log
/node_modules/electron-log/LICENSE
/node_modules/electron-log/index.js
/node_modules/electron-log/main.js
/node_modules/electron-log/package.json
/node_modules/electron-log/renderer.js
/node_modules/electron-log/lib
/node_modules/electron-log/lib/format.js
/node_modules/electron-log/lib/log.js
/node_modules/electron-log/lib/transports
/node_modules/electron-log/lib/transports/console.js
/node_modules/electron-log/lib/transports/log-s.js
/node_modules/electron-log/lib/transports/renderer-console.js
/node_modules/electron-log/lib/transports/file
/node_modules/electron-log/lib/transports/file/find-log-path.js
/node_modules/electron-log/lib/transports/file/get-app-name.js
/node_modules/electron-log/lib/transports/file/index.js
/avrdude
/avrdude/avrdude
/avrdude/avrdude.conf
```

**Comment by altjz** [comment]
Anybody can help?

**Comment by milmih** [comment]
I have this problem, too. Help would be much appreciated. Thanks!

**Comment by kikill95** [comment]
Hello, everyone, according to https://gist.github.com/maximilian-ruppert/a446a7ee87838a62099d discussion I wanted to run the server as a separate process. I received the same error while trying to use **execFile**.

I wrote the following:

    const exec = require('child_process').exec
    exec('node ./server.js', (error, stdout, stderr) => {
      if (error) {
        console.error(`exec error: ${error}`)
        return
      }
      console.log(`stdout: ${stdout}`)
      console.log(`stderr: ${stderr}`)
    })

So, I run server as a separate process and this process do not overload main Electron process, or its render process

This works fine for me with:
node: 7.10.0
electron: 1.6.2

**Comment by altjz** [comment]
Hi @kikill95 , did you run the file from asar package? As the Electron [documentation](https://electron.atom.io/docs/tutorial/application-packaging/#extra-unpacking-on-some-apis) mentions, it only supports `execFile`. you will get File directory not found exception with `exec` if i remember correctly

**Comment by kikill95** [comment]
@altjz no, not from asar, sorry if it was mistaken comment. For asar I have used ```child_process. fork ``` - this worked for me.
Sorry for misunderstanding, but anyways ```child_process. fork``` works on asar fine

**Comment by xp6530** [comment]
@altjz hi, Do you have a solution?

**Comment by altjz** [comment]
Hi @xp6530, not yet, I given up because no one help on this issue. May be you could try the new version Electron. 1.7.x

**Comment by tbillington** [comment]
Also getting this error with a very vanilla setup, using ver `"electron": "2.0.8"`.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by tbillington** [comment]
@codebytere Don't know if you saw my comment but I experienced this in electron 2.

**Comment by codebytere** [comment]
Missed that, thanks @tbillington!

**Comment by Vegisau** [comment]
oops, i also encountered this problem

**Comment by tbillington** [comment]
Worth noting that I do not encounter this error on windows, but I do in osx. Exact same code.

**Comment by JLaferri** [comment]
This happened to me on osx when I tried to run `execFile("/Path/App.app")` I then tried `execFile("/Path/App.app/Contents/MacOS/App")` and that seems to work fine

**Comment by mochi-co** [comment]
I have this same error on 2.0.18 and 4.0.8 on osx when using __dirname/path/bin. Even using absolute paths doesn't work. Any advice would be appreciated!

**Comment by frodoe7** [comment]
@JLaferri 

I had the same issue and your comment was the solution , thanks alot

**Comment by tmirun** [comment]
@JLaferri nice solution! thanks

someday we will have an official solution for this problem?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by tbillington** [comment]
@sofianguy  Well that's one way to reduce the number of active issues 😅 I sympathise though.

Confirming this is still occurring on `6.0.1`.

Code to reproduce:

```typescript
const notes_process: cp.ChildProcess = cp.execFile(
  "/Applications/Notes.app",
  // "/Applications/Notes.app/Contents/MacOS/Notes",
  [],
  (error: Error | null, stdout: string, stderr: string) => {
    console.log(error);
  }
);
```

Error:

```
Error: spawn /Applications/Notes.app EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn /Applications/Notes.app',
  path: '/Applications/Notes.app',
  spawnargs: [],
  cmd: '/Applications/Notes.app'
}
```

Switching to the complete path of the binary as opposed to the ".app" path (commented out string in above code) makes the program launch successfully.

I suppose launching with the complete path of the binary is a decent enough workaround for most people?? It works enough for me that I'm not really invested in this issue.

**Comment by whyboris** [comment]
Similar problem with Electron `5.0.7` with `spawn`
```ts
const spawn = require('child_process').spawn;
const allArgs: string[] = [];
const executablePath1: string = '/Applications/VLC.app'                                   // case 1
const executablePath2: string = '/Applications/VLC.app/Contents/MacOS/VLC'  // case 2
spawn(executablePath1, allArgs);
```
case 1 results in:

![image](https://user-images.githubusercontent.com/17264277/62824007-e46dc180-bb65-11e9-9f12-e111a6b55d4b.png)


case 2 runs fine.

**Comment by andyjslee** [comment]
I am trying to execute a python binary file (created via pyinstaller) through my Electron application on Mac OS. This issue persists in the latest version of Electron (7.1.4). What is the official fix for this?

**Comment by simple-YoungBadBoy** [comment]
> I am trying to execute a python binary file (created via pyinstaller) through my Electron application on Mac OS. This issue persists in the latest version of Electron (7.1.4). As mentioned above, this problem doesn't occur on my Windows machine with the same underlying source code. It only happens when I package my Electron application using electron-builder with and without asar. My Electron application is able to run the python binary file when I run the version inside the MacOS folder (MacOS/MyApp). What is the official workaround/fix for this?

hey bro,i have this problem too,Did you solve this problem?

**Comment by xxx6668** [comment]
> This happened to me on osx when I tried to run `execFile("/Path/App.app")`.
> 
> I then tried `execFile("/Path/App.app/Contents/MacOS/App")` and that seems to work fine
我使用后面的写法后，electron会不同的调用，最后溢出

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
