### ISSUE TITLE
window.history in webview does not include the "joint session history"

### ISSUE THREAD

**Issue by ikreymer** [electron/electron#9497]
* Electron version: 1.6.2
* Operating system: OS X

### Expected behavior

When accessing `window.history` inside a `<webview>`, the history should include history changes from iframes, it should be the "joint session history" as defined in the spec:

https://html.spec.whatwg.org/multipage/browsers.html#joint-session-history

To be equivalent to how the browser handles history, the `window.history` should reflect changes to history made in iframes inside the <webview> as well.

Perhaps this is something that could be enabled as an option?

### Actual behavior

The `window.history` reflects only changes to the top-frame, history changes from iframes are not added to the top-level history.

The same is true when accessing the history via `webview.getWebContents().history` so perhaps related to #7186

When running an application that provides navigation in an iframe and needs to work in both Chrome and Electron, the application does not work as expected in Electron, as the iframe navigation history added to `window.history` when running in Chrome are not added in Electron <webview> `window.history`.

**Comment by deepak1556** [comment]
Thanks for the report, Merging this to https://github.com/electron/electron/issues/7092. Please subscribe to it for updates.
