### ISSUE TITLE
 No storage quota provided in QuotaSettings

### ISSUE THREAD

**Issue by danieltrolezi** [electron/electron#9498]
Hi!

I have a question, why beta releases are versioned like it were stable?
When my application updated from 1.6.9 to 1.7.0 beta (My package.json is specifying to only make minor version updates), it began to get this warning:

```[...]:WARNING:quota_manager.cc(1590)] No storage quota provided in QuotaSettings.```

My application uses IndexedDB and the Chromium 58 made some changes in its implementation that aren't handled by Electron yet.

As you can see [here, in the official Chromiun repository](https://chromium.googlesource.com/chromium/src.git/+/10e5fc3598c9f2e1015458c814a1163680465b3e), it's says that we need to explicitly set QuotaSettings from "embedder".

I don't know how or if this is related, but the CPU usage by my app started to increase dramatically.
When I rolled back to v1.6.9 (which uses Chromium 56), everything work as usual.

**Comment by kevinsawicki** [comment]
> I have a question, why beta releases are versioned like it were stable?

We release new versions to either the `beta` or `latest` channel in NPM, releases start in beta and then get promoted to `latest` if they are deemed to be stable.

NPM should only pull the from the `latest` field by default so you should only get stable releases if you have something like `^1.6.9` in your `package.json`. 

> As you can see here, in the official Chromiun repository, it's says that we need to explicitly set QuotaSettings from "embedder".

Thank you for mentioning this, will investigate further.

**Comment by kevinsawicki** [comment]
> I don't know how or if this is related, but the CPU usage by my app started to increase dramatically.

Are you able to provide more information about this? When does it happen? Is the memory growing as well? Are you able to reproduce it in a simplified example app you could provide?

**Comment by deepak1556** [comment]
I looked into this when we were upgrading to chrome 58, the warning can be ignored it won't affect us as we provided unlimited and durable storage for all origins. In future it would be better to provide an option to users based on quotasettings as it allows tuning the storage eviction policy based on their use case.

**Comment by danieltrolezi** [comment]
Thanks for the asnwer!

> NPM should only pull the from the latest field by default so you should only get stable releases if you have something like ^1.6.9 in your package.json.

That is exactly what I have in my package.json and even so Electron was updated to 1.7.0 beta... Any thoughts?

> Are you able to provide more information about this? When does it happen? Is the memory growing as well?

I forgot to mention that I'm running the application on a Raspberry Pi 3 Model B. Sorry for that.
I don't know if the CPU usage increased on other operational systems, but [I recorded a small benchmark](https://www.dropbox.com/s/cpeb8pi98n0kg9h/Electron%20Benchmark.mp4?dl=0) comparing both 1.6.9 and 1.7.1 versions of Electron running my app. (I recommend to download the file for better visualization)  The memory usage is almost the same (1.6.9 on the left).

As you can see, the CPU usage is higher when CSS animation starts. And I know that's almost certain that this isn't related at all, but when I cleared all browser data (IndexedDB, Cache and Filesystem Storage), the warning about the QuotaSettings stoped and the CPU usage was back to normal.

> Are you able to reproduce it in a simplified example app you could provide?

I didn't have the time to provide an example yet, but I'll working on it.

> In future it would be better to provide an option to users based on quotasettings as it allows tuning the storage eviction policy based on their use case.

That's a great idea!

**Comment by codebytere** [comment]
This should no longer emit this warning in latest versions of Electron.

**Comment by tcd156** [comment]
I'm still seeing this emit in Electon 5.0.7
