### ISSUE TITLE
Cannot resolve module original-fs

### ISSUE THREAD

**Issue by AtixD** [electron/electron#9500]
When I collect the project in the release version gives an error, help me solve the problem
When I run in dev mode, it works great

module require in main.js (process electron)

ERROR in ./app/main.development.js
Module not found: Error: Cannot resolve module 'original-fs'
electron : 1.4.15
electron-builder: 12.2.2

Thanks

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

It's probably your Webpack config, I'm guessing you need to declare `original-fs` as a built-in.
