### ISSUE TITLE
Form tag Issue

### ISSUE THREAD

**Issue by Dear-Min** [electron/electron#9501]
There is a problem with form - action. e.x) <form action="http://domain.com">

when i click the submit button on html, client changed to white screen and Devtools are disabled.

what should i do?

**Comment by enlight** [comment]
There is template that you should to fill out when opening a new issue, that's the minimum information required for someone to start helping you, the template also asks to provide a minimal app that can reproduce this issue by forking https://github.com/electron/electron-quick-start

**Comment by Dear-Min** [comment]
@enlight oh, sorry. it was my first issue for electron. i will fill out next time.

**Comment by Dear-Min** [comment]
* Electron version: 1.6.6
* Operating system: Windows 10 x64

**Comment by kevinsawicki** [comment]
> when i click the submit button on html, client changed to white screen and Devtools are disabled.

This sounds like a renderer crash, can you include a small reproduction app that demonstrates the issue?

**Comment by Dear-Min** [comment]
I can't demonstrate this issue after update 1.6.10. Will keep an eye about this.

**Comment by kevinsawicki** [comment]
> I can't demonstrate this issue after update 1.6.10. Will keep an eye about this.

Thanks for the update, closing this out for now, can reopen if it comes back up.
