### ISSUE TITLE
Having problem while rebuilding electron after installing modbus-serial

### ISSUE THREAD

**Issue by rohit7209** [electron/electron#9503]
I am using
windows 10
nodejs version: 6.10.3
electron version: 1.6.8

while rebuilding electron after installing 'modbus-serial' i am getting below error...

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
VCBUILD : error : project file 'c:\ecube\app\node_modules\serialport\build\serialport.vcproj' was not found or not a valid project file. [c:\ecube\app\node_modules\serialport\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\ecube\app\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\ecube\\app\\node.exe" "c:\\ecube\\app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=serialport" "--module_path=c:\\ecube\\app\\node_modules\\serialport\\build\\Release" "--host=https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7"
gyp ERR! cwd c:\ecube\app\node_modules\serialport
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

Failed with exit code: 1

Error: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
VCBUILD : error : project file 'c:\ecube\app\node_modules\serialport\build\serialport.vcproj' was not found or not a valid project file. [c:\ecube\app\node_modules\serialport\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\ecube\app\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\ecube\\app\\node.exe" "c:\\ecube\\app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=serialport" "--module_path=c:\\ecube\\app\\node_modules\\serialport\\build\\Release" "--host=https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7"
gyp ERR! cwd c:\ecube\app\node_modules\serialport
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (c:\ecube\app\node_modules\spawn-rx\lib\src\index.js:262:84)
    at SafeSubscriber.__tryOrUnsub (c:\ecube\app\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (c:\ecube\app\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (c:\ecube\app\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (c:\ecube\app\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (c:\ecube\app\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (c:\ecube\app\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (c:\ecube\app\node_modules\spawn-rx\lib\src\index.js:236:65)
    at SafeSubscriber.__tryOrUnsub (c:\ecube\app\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (c:\ecube\app\node_modules\rxjs\Subscriber.js:185:22)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "c:\\ecube\\app\\node.exe" "c:\\ecube\\app\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ecube_app@1.0.0 rebuild: `electron-rebuild -f -w modbus-serial`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the ecube_app@1.0.0 rebuild script 'electron-rebuild -f -w modbus-serial'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ecube_app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild -f -w modbus-serial
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ecube_app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ecube_app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\ecube\app\npm-debug.log

**Comment by cifratila** [comment]
@rohit7209 Might be an issue with the way the serialport node module is compiled.

Try to have these requirement set: `https://www.npmjs.com/package/serialport#installation-special-cases `

Would recommend to have Python 2.7 and VS 2015 Update 3 on Windows in order to properly compile.

**Comment by enlight** [comment]
I suggest following the instructions at https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#environment-setup-and-configuration to ensure your machine is properly configured for building native Node modules.
