### ISSUE TITLE
Open the window. It's blank, but there are elements in DOM

### ISSUE THREAD

**Issue by CongAn** [electron/electron#9504]
### I ran macOS in the Parallels Desktop virtual machine
**The Electron sample project is used**
`git clone https://github.com/electron/electron-quick-start`

- macOS Sierra 10.12.5
- Node.js 7.4.0,
- Chromium  56.0.2924.87,
- Electron 1.6.8.

**The probable cause of this problem**
`2017-05-17 14:37:00.600 Electron Helper[460:9583] Couldn't set selectedTextBackgroundColor from default ()`
**This program has no exception error**
![electorn-issue-bug](https://cloud.githubusercontent.com/assets/16128049/26141310/d019ab8e-3b0d-11e7-8aca-9d39d183db8b.png)

**Comment by kevinsawicki** [comment]
This looks very similar to https://github.com/electron/electron/issues/9109, can you try the workaround mentioned in https://github.com/electron/electron/issues/9109#issuecomment-291671157 ?

**Comment by jarek-foksa** [comment]
This also occurs on older hardware, not just inside virtual machines. I just received a very similar bug report from MacBook Pro 2012 user and --disable-gpu flag solved the problem for him.

I think Chrome has a blacklist of untested/unsupported/legacy GPUs which is used to determine whether hardware acceleration should be enabled by default. Perhaps Electron could use the same approach?

**Comment by jarek-foksa** [comment]
I think `Couldn't set selectedTextBackgroundColor from default ()` console message is unrelated, I recall seeing it many times before.

**Comment by codebytere** [comment]
Closing due to abandonment.
