### ISSUE TITLE
Geometry support

### ISSUE THREAD

**Issue by mrichman** [electron/electron#9506]
I often need to record screencasts, and need my applications in a specific position and size on screen. 

Most X11 based application allow for a `-geometry` switch.

I realize Electron is not X11. However, is it possible to support this switch?

Perhaps as follows:

`atom --geometry 1280x720-37+50`

where the value is `[{WIDTH}][x{HEIGHT}][{+-}{XOFF}[{+-}{YOFF}]]`

**Comment by MarshallOfSound** [comment]
@mrichman It looks like this is a feature request for `atom/atom` not Electron itself, can you confirm?

**Comment by mrichman** [comment]
Would it not apply to any Electron-based application? I just used Atom as an example.

**Comment by MarshallOfSound** [comment]
@mrichman The command might be nice in all application, but it would have to be implemented in each application individually.  Each electron based application should be (and currently is) in complete control over it's own windows and their positioning.
