### ISSUE TITLE
Support ArrayBuffer over IPC

### ISSUE THREAD

**Issue by jardakotesovec** [electron/electron#9509]
* Electron version: 1.6.8
* Operating system: OS X 10.12.4

### Expected behavior
I expect that I will be able to send ArrayBuffer via ipcRenderer from the browser window to the main node process and get as buffer. I did not find clear answer whether it's possible or not. PR #6572 suggest it could work, but I was not successful.

In Browser window I do:
```
var buffer = new ArrayBuffer(8);
ipcRenderer.send('sendData', {
   data: buffer
});
```

And in node process:
```
ipcMain.on('sendData', (event, arg) => {
    console.log(arg.data)
}
```

I would expect having `Buffer` in the arg.data;

### Actual behavior

I get empty object in arg.data.

**Comment by kevinsawicki** [comment]
Right now you have to wrap it in a node `Buffer` or send it at as a `Uint8Array`.

>  PR #6572 suggest it could work, but I was not successful.

This pull request only affects buffers send over the `remote` interface, not directly over `ipcRenderer`.

**Comment by kevinsawicki** [comment]
So something like this should work currently:

```js
var buffer = new ArrayBuffer(8);
const Buffer = require('buffer').Buffer;
ipcRenderer.send('sendData', {
   data: Buffer.from(buffer)
});
```

**Comment by jardakotesovec** [comment]
@kevinsawicki Thanks a lot for the hint. This made the trick:

```
var buffer = new ArrayBuffer(8);
ipcRenderer.send('sendData', {
   data: new Uint8Array(buffer)
});

```

**Comment by miniak** [comment]
@jardakotesovec it's now fixed by https://github.com/electron/electron/pull/13055. Going to be part of Electron 3.0

**Comment by jayarjo** [comment]
So is it possible to send binary data from main to renderer now? 'cause other sources were saying that it gets serialized/unserialized on the way, which is obviously a terrible idea.

**Comment by DiegoBM** [comment]
> @miniak, @jardakotesovec So is it possible to send binary data from main to renderer now? 'cause other sources were saying that it gets serialized/unserialized on the way, which is obviously a terrible idea.

Can anyone please reply to this?

**Comment by rkdrnf** [comment]
@DiegoBM @jayarjo 
https://github.com/electron/electron/issues/6660
This should be the answer.

It says it won't get serialized / deserialized.
