### ISSUE TITLE
Acquire process id for renderer process

### ISSUE THREAD

**Issue by hackjutsu** [electron/electron#9511]
* Electron version: 1.4.15, 1.6.7
* Operating system: macOS 10.12.5, Linux Mint

### Expected behavior

Acquire the pid for the renderer process from at least one of the methods below
```javascirpt
const currentWindowsPID1 = require('remote').getCurrentWebContents().getProcessId();
const currentWindowsPID2 = require('remote').getCurrentWindow().webContents.getProcessId();
const currentWindowsPID3 = require('remote').getCurrentWindow().id;
```

### Actual behavior
We got a pretty small number like 4 or 3, which is more like an internal windows routing id other than an OS pid.  (Verified by the Activity Monitor on macOS)

### Related posts
https://github.com/electron/electron/issues/218
https://github.com/electron/electron/issues/4790

**Comment by kevinsawicki** [comment]
This is now available as `getOSProcessId()` in 1.7.1, see https://github.com/electron/electron/pull/9222 for more details.

> We got a pretty small number like 4 or 3, which is more like an internal windows routing id other than an OS pid

Yes, sorry for the confusion, the ids you mentioned are internal ids generated by chrome or electron. The new API mentioned exposes the real OS one.

**Comment by hackjutsu** [comment]
@kevinsawicki 

Thanks for the quick response. Would you like to consider a better naming for those methods above in the future? Because the terms `id`, `getProcessId()` and `getOSProcessId` sound confusing.

Besides, `id` and `getProcessId()` don't return the same values.

**Comment by kevinsawicki** [comment]
>  Would you like to consider a better naming for those methods above in the future? Because the terms id, getProcessId() and getOSProcessId sound confusing.

For sure, you are totally right, it is very confusing and is something we plan to address in the Electron 2.0 API.

**Comment by tbogard** [comment]
Since Electron now has more things than 2 years ago, you can just go over the event of your IPC call and request the BrowserWindow that triggered the call:

event.sender.getOwnerBrowserWindow() has that. It returns a BrowserWindow Object with all the properties that it could have such: minimize(), close(), etc....
