### ISSUE TITLE
nativeWindowOpen question

### ISSUE THREAD

**Issue by snene** [electron/electron#9515]
Thanks for adding the nativeWindowOpen support. I am trying it out with 1.7.1 and hope it helps with my problem which is described below.

I open a BrowserWindow which has a webview which loads various web pages. I am setting nativeWindowOpen to true when opening this window. The pages that are loaded make the following calls:
            
            var printWin = window.open("", "_blank");
            printWin.document.open();
            printWin.document.write(html);
            printWin.document.close();

But the above calls are failing with error "TypeError: Cannot read property 'document' of null"

When the window.open is called from the page, my BrowserWindow gets 'new-window' event where I create a new BrowserWindow and return it in evt.newGuest. But still looks like 'printWin' variable above is null.

I read in the documentation that "Native window.open() allows **synchronous** access to opened windows so it is convenient choice if you need to open a dialog or a preferences window."

Is there anything I am missing? Will nativeWindowOpen help in this situation? I am really struggling with this problem and really appreciate any help!

Thanks a lot!

**Comment by snene** [comment]
The web page that gets loaded in the webview is calling window.open. So my question is, will setting nativeWindowOpen to true help in this scenario? @seanchas116 Do you have any suggestions or workarounds for the problem I am facing?

**Comment by kevinsawicki** [comment]
@snene does your `<webview>` tag have `allowpopups` set on it?

Are you able to provide a small sample application that showcases the issue you are facing?

**Comment by snene** [comment]
@kevinsawicki No, at the moment webview does not have allowpopups set on it.

Sample code is as follows:
Main app:

```
const {app, BrowserWindow, ipcMain} = require("electron")

let win = null

app.on('ready', () => {
  win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nativeWindowOpen: true
    }
  });
 win.loadURL('./MyWindow.html');
  win.on("closed", () => {
    win = null
});

```
MyWindow.html:
```
<html>
  <body>
        <div class="mainView">
            <webview id="webview" style="height:100%" src="about:blank"  webpreferences="nodeIntegration=no"></webview>
        </div>
    </div>
    <script src="../src/js/ClientShell.js"></script>
  </body>
</html>
```

ClientShell.js
```
const BrowserWindowR = require('electron').remote.BrowserWindow;

 webview.addEventListener('dom-ready', () => {
    webview.loadURL('Print.html');
});

  webview.addEventListener('new-window', (evt) => {
    let nW = new BrowserWindowR();
    evt.newGuest = nW;
  });
```

Print.html has code which open a window like following
```
var printWin = window.open("", "_blank");
printWin.document.open();
printWin.document.write(html);
printWin.document.close();
```

When the window.open is called from the page, my BrowserWindow gets 'new-window' event where I create a new BrowserWindow and return it in evt.newGuest. But still looks like 'printWin' variable above is null. Anything I am missing?

**Comment by kevinsawicki** [comment]
@snene if you want to use native `window.open` on the `<webview>` then it needs to be enabled there as a `webpreference`:

```html
<webview id="webview" style="height:100%" src="about:blank"  webpreferences="nodeIntegration=no,nativeWindowOpen=yes"></webview>
```

There is currently a bug though where native `window.open` does not work from `<webview>` tags, it is being tracked in #9556 and has a proposed fix in #9568

**Comment by snene** [comment]
Thank you so much for the update @kevinsawicki ! Do you have a rough idea when the fix will be available in beta release?

**Comment by kevinsawicki** [comment]
> Do you have a rough idea when the fix will be available in beta release?

I would guess this week or next, still doing more testing on #9568 to ensure it behaves as expected from within `<webview>` tags.

I'm going close this issue out, please subscribe to #9556 for further updates.

**Comment by snene** [comment]
Thank you @kevinsawicki !
