### ISSUE TITLE
electron working on raspberry pi zero

### ISSUE THREAD

**Issue by Zhairgling** [electron/electron#9520]
Electron version: Latest
Operating system:
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.24+ #993 Wed Apr 26 17:56:54 BST 2017 armv6l GNU/Linux
```
Hi all,

I have an electron app working well on a rpy 3. 

As I work on a wearable device, the size of the device is important so when I saw the raspberry pi zero w I thought it was a boon for my IOT.
So I started trying to wear the app on the pi zero. But it does not seem supported: 
```
pi@raspberrypi:~ $ electron
/usr/local/lib/node_modules/electron/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```
Is there a way to make it work for now. Or a chance it's suported soon?

**Comment by Bones2316** [comment]
You need a raspberry pi camera Adapter is all lol

**Comment by Zhairgling** [comment]
@Bones2316 


How do you know when I read my message that I have a problem with a camera? I guess you were wrong about the thread in your answer. Otherwise you are a next level troll.

**Comment by hovancik** [comment]
based on the error I guess you should: `apt-cache search libxss1` ? 

there should be package with that name:  `sudo apt-get install libxss1`

**Comment by cifratila** [comment]
@Zhairgling As @hovancik said, you sure that all deps for electron are installed: [Build Instructions Linux](https://github.com/electron/electron/blob/master/docs/development/build-instructions-linux.md) ?

**Comment by sofianguy** [comment]
@Zhairgling if the solutions provided do not solve your issue, you can check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed.

**Comment by maxerbox** [comment]
[Armv6 build isn't available](https://github.com/electron/electron/issues/6102) , but it seems that a chronium version is available for pi0, check out https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=157049

**Comment by ckerr** [comment]
See also https://github.com/electron/electron/issues/16207
