### ISSUE TITLE
Elements with `overflow: overlay;` and a custom background cannot be seen through

### ISSUE THREAD

**Issue by WeeJeWel** [electron/electron#9521]
* Electron version: 1.6.1
* Operating system: OSX 10.12.4

### Expected behavior

Electron has partially support for the CSS property `overflow: overlay;`, but Google Chrome has (tested: 58.0.3029.110).

### Actual behavior

The background cannot be seen through.

Google Chrome:
![screen shot 2017-05-18 at 17 06 52](https://cloud.githubusercontent.com/assets/319873/26209190/69787dd0-3bec-11e7-91be-1d9fd00f90c2.png)

Electron:
![screen shot 2017-05-18 at 17 05 55](https://cloud.githubusercontent.com/assets/319873/26209198/6e621c02-3bec-11e7-967c-a45c8cb49813.png)

### How to reproduce
Visit http://jsfiddle.net/t4q7o36r/22/

**Comment by MarshallOfSound** [comment]
Electron `1.6` is only on Chromium 56, Electron `1.7` beta is currently on Chromium 58 can you test using that version of Electron instead 👍

**Comment by WeeJeWel** [comment]
Yay, it's indeed fixed in 1.7!

What's the expected / average time when 1.7 is stable?
