### ISSUE TITLE
Calling event.preventDefault in `will-prevent-unload` does not allow webview unload.

### ISSUE THREAD

**Issue by surajreddy** [electron/electron#9524]
### Environment Details:
* Electron version: 1.7.1
* Operating system: macOS Sierra 10.12.5

### Expected behavior

Calling `event.preventDefault()` in a `will-prevent-unload` event handler should allow window unloads for webviews.

### Actual behavior

It does not allow the unload to proceed, but always stops it.

### How to reproduce

Sample Repo: https://github.com/surajreddy/electron-sample-app/tree/will-prevent-unload
Code: https://github.com/surajreddy/electron-sample-app/pull/1/files

Steps to test:
1. Clone https://github.com/surajreddy/electron-sample-app/tree/will-prevent-unload
2. Run `npm install`
3. Run `npm start`
4. Click on 'Navigate to Google'
5. Click `Leave` on the prompt that pops up.

### Background:
I'm testing the `will-prevent-unload` handler introduced in https://github.com/electron/electron/releases/tag/v1.7.1

cc @22222 @kevinsawicki

**Comment by enlight** [comment]
This is expected behavior, you need to assign the callback in the main process in order for `event.preventDefault()` to have the desired effect, see https://github.com/electron/electron/issues/2770#issuecomment-140065309 for clarification.
