### ISSUE TITLE
Preventing window unload after creating a confirm prompt does not work.

### ISSUE THREAD

**Issue by surajreddy** [electron/electron#9526]
### Environment Details:
* Electron version: 1.7.1
* Operating system: macOS Sierra 10.12.5

### Expected behavior

Calling `confirm` in a `beforeunload` event handler should allow the prevention of window unload.

### Actual behavior

Calling `confirm` always allows the unload to proceed.

**Note:** This works as intended when the devTools for the webview are open, and the unload is blocked successfully.

### How to reproduce

Sample Repo: https://github.com/surajreddy/electron-sample-app/tree/confirm-and-unload
Code: https://github.com/surajreddy/electron-sample-app/pull/3/files

Steps to test:
1. Clone https://github.com/surajreddy/electron-sample-app/tree/confirm-and-unload
2. Run `npm install`
3. Run `npm start`
4. Click on 'Navigate to Google'
5. A prompt should show up. Select `OK`.
6. Wait a few seconds, and the unload will proceed, but shouldn't.

Testing this with dev tools open:
1. Uncomment the `openDevTools` line in `renderer.js`
2. Run `npm start`
4. Click on 'Navigate to Google'
5. A prompt should show up. Select `OK`.
6. Wait a few seconds, and the page will not unload.

### Potentially Related issue

https://github.com/electron/electron/issues/9525

**Comment by MarshallOfSound** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so I'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
