### ISSUE TITLE
PDF fails to render when provided as iframe src

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#9531]
* Electron version: 1.7.1
* Operating system: macOS 10.12.4

### Expected behavior

PDFs should render inside iframes using the built in pdf renderer

### Actual behavior

iframe remains blank. Electron attempts to download PDF file

### How to reproduce

```
  $ git clone https://github.com/wavebox/electron-quick-start.git -b pdf_iframe_norender_bug
  $ npm install
  $ npm start
```

Tested with local and remote PDFs. The example uses a remote PDF

Thanks!

**Comment by deepak1556** [comment]
Thanks for the test case! merging this to https://github.com/electron/electron/issues/9192 .

**Comment by Thomas101** [comment]
Did wonder if it was the same as that, but wasn't 100% sure. Thanks!
