### ISSUE TITLE
1.7.0+ broke CSS background-filter (and maybe other experimental/blink features)

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#9539]
* Electron version: 1.7.0-beta and above (works on 1.6.10-beta and below)
* Operating system: macOS 10.12.5

### Expected behavior

Using either `webPreferences.experimentalFeatures: true` or `blinkFeatures: 'CSSBackdropFilter'` as option for the `browserWindow` and standard `backdrop-filter` CSS in the code should work.

### Actual behavior

Works perfectly on 1.6.10 and below, doesn't work on 1.7.0 and above.

### How to reproduce

Load https://codepen.io/tutsplus/full/WGEYoz/ in a browser window with one of the `webPreferences` options mentioned above.

**Comment by kevinsawicki** [comment]
I tried this sample app in 1.7.2 and am not seeing the `No good, backdrop-filter is unsupported in your browser.` message when loaded:


```js
const {app, BrowserWindow} = require('electron')

let win

app.once('ready', () => {
  win = new BrowserWindow({
    webPreferences: {
      blinkFeatures: 'CSSBackdropFilter',
      nodeIntegration: false
    }
  })
  win.loadURL('https://codepen.io/tutsplus/full/WGEYoz/')
})
```

Are you seeing the not working message on 1.7.2 with this sample?

**Comment by romaincointepas** [comment]
I can't seem to reproduce with `https://codepen.io/tutsplus/full/WGEYoz`.

I didn't really try with that link myself (I should have), I had my own html/css code and I could see the backdrop-filter effect appearing/disappearing simply by switching the electron version.

Maybe Chromium changed what can be accepted as DOM hierarchy for backdrop-filter, or maybe it was something else on my side.

Thanks for checking this out, and apology for the useless issue :/.
