### ISSUE TITLE
how to new a process？

### ISSUE THREAD

**Issue by ydcoming** [electron/electron#9546]
The root directory contains node.dll，I want to have a new process about node。What should I do?
you know，the vscode has many processes，to Lifting performance。

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW `process.fork` will do this for you 👍
