### ISSUE TITLE
 electron@1.6.8 postinstall: `node install.js`

### ISSUE THREAD

**Issue by arunattupurath** [electron/electron#9549]
* Electron version: 1.6.8
* Operating system: WIndows8

Getting error while trying to install electron .
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "electron"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

I saw https://github.com/electron/electron/issues/9323 . But its closed and I am not sure of the solutions. and didnt understand how extract-zip is supposed to help.

**Comment by kevinsawicki** [comment]
Is there more output you can provide?

Can you try the install with the `--verbose` flag?

Are you using a proxy or behind a firewall?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
