### ISSUE TITLE
App quit/exit throws error / ipc

### ISSUE THREAD

**Issue by black-snow** [electron/electron#9550]
* Electron version: 1.6.8
* Operating system: Win10 x64, creators

### Expected behavior

App should quit nicely.

### Actual behavior

App crashes with `cannot read property close of null`

### How to reproduce

Alright. I don't quit know how to report this. It was a major *pita* to find the source of this evil.

My app launches a tutorial on its first start. At the end the browser window issues an ipc event to main asking it to restart the app.

```js
// renderer
ipcRenderer.send('restart-app')
if (window && window.close) window.close()

// main - on restart-app
app.relaunch()
app.quit() // BOOM
```

I logged all the quit events and they were all emitted - crash happens after that. Interestingly I found a workaround.

```js
// renderer
ipcRenderer.send('restart-app')
debug('whatever') // do whatever here
if (window && window.close) window.close()
```

Et voila, no crash. `debug` is remotly required and might issue another ipc call. I think that might be the trick because doing some void stuff (like `let x = 1`) doesn't make the crash go away.

**Comment by ToadKing** [comment]
I also experience the issue with my app. I traced the bug and it appears to have been introduced between 1.6.7 and 1.6.8.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
