### ISSUE TITLE
How to detect Failed to load resource: net::ERR_FILE_NOT_FOUND?

### ISSUE THREAD

**Issue by lynaghk** [electron/electron#9555]
I'm using Electron 1.6.8 on OS X 10.9.5, and it's not clear to me how I should detect broken references in my markup.

Such references are reported as `Failed to load resource: net::ERR_FILE_NOT_FOUND` in devtools, but these errors are not printed to stderr, nor do they show up in any events emitted by `webContents`.

I've created a full reproducible example here: https://github.com/lynaghk/reproducible-reports/tree/master/3-electron-failed-to-load-resource

I'm not sure if this is a bug in Electron or in the documentation.
Happy to contribute a fix either way, once intent is clarified by a maintainer.

In any case, thanks for your hard work on such a useful project!

**Comment by deepak1556** [comment]
You can use [session.webRequest.onErrorOccurred](https://github.com/electron/electron/blob/master/docs/api/web-request.md#webrequestonerroroccurredfilter-listener) to detect resource load failures.

**Comment by lynaghk** [comment]
@deepak1556 Confirmed, this works well for my use case. Thanks for the tip, and for your work on Electron!
