### ISSUE TITLE
Electron crashes on click of a link with target=_blank in a webview with nativeWindowOpen set

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#9558]
* Electron version: 1.7.1
* Operating system: MacOS

### Expected behavior

```
<webview src="./webview.html" webpreferences="allowDisplayingInsecureContent,contentIsolation,nativeWindowOpen"></webview>
```

Clicking the link inside `webview.html` should trigger the standard `new-window` event handling for a webview.

### Actual behavior

Electron crashes

### How to reproduce

See https://github.com/pfrazee/electron-bug-target-blank-crash

```
git clone https://github.com/pfrazee/electron-bug-target-blank-crash.git
npm install
npm start
```

**Comment by enlight** [comment]
Probably related to #9556

**Comment by kevinsawicki** [comment]
Same crash as #9556, merging into that one.
