### ISSUE TITLE
SetBounds is not working when browserwindow is minimized

### ISSUE THREAD

**Issue by juturu** [electron/electron#9559]
* Electron version: 1.7.1
* Operating system: Windows

### Expected behavior
SetBounds API should set the window bounds

### Actual behavior
SetBounds API doesn't work when browser window is minimized
### How to reproduce
git clone https://github.com/juturu/electron-quick-start -b setbounds

Run electron on this branch. App minimizes and sets bounds within 10 secs. After 10 sec/on seeing console message, click on the taskbar icon to see setbounds didn't actually set the bounds on browserwindow.

**Comment by ronwang01** [comment]
+1

**Comment by yarcub** [comment]
Is this an issue that is fixed on 2.x/3.x or is stale?

**Comment by MarshallOfSound** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so I'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by codebytere** [comment]
At present, this is resultant of Chromium's choice to only apply bounds changes to non-minimized window as seen [here](https://cs.chromium.org/chromium/src/ui/views/widget/widget.cc?sq=package:chromium&g=0&l=523). We recommend you file a bug upstream at crbug.com and if a change occurs, we're more than happy to return to this issue.
