### ISSUE TITLE
generators in browser process?

### ISSUE THREAD

**Issue by loveencounterflow** [electron/electron#956]
according to #798, atom-shell supports generators. however, that seems to be only true for the renderer process; in the browser process, i get `Unexpected token *` when trying to define a starred function.

is there any way to specify that the atom executable should be run with the `--harmony` flag? shouldn't it be always on, to prevent the irritating situation that the browser and the renderer processes run slightly different versions of JavaScript?

**Comment by mark-hahn** [comment]
When I place the code below in an atom package I'm getting the `Unexpected token *` also.  This is in javascript code escaped in coffeescript.  Any idea what I'm doing wrong?

```
`
function test* () {
  x=1
  yield
  x=2
}
`
```
