### ISSUE TITLE
Add `app.ready` Promise

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#9561]
Right now we have `app.isReady()` for checking if Electron is ready and `app.on('ready')` to be notified when it's ready. But if you're creating something that could be called at any time, you need to first check `app.isReady()`, and if `false`, subscribe to the `app.on('ready')` event.

I propose adding an `app.ready` Promise that resolves when Electron is ready. This would be especially useful with async/await, as you could just do:

```js
(async () => {
	await app.ready;

	// …
})();
```

I realize it's already possible to [do this yourself](https://github.com/sindresorhus/electron-util/blob/601f328e05a52419049c5fc83602356498b93892/index.js#L23-L29), but `app.on('ready')` is used by every app, so improving the default ergonomics can have big impact. It also results in one less level of nesting.

**Comment by DrYSG** [comment]
What about the util.promisify() in node v8, and when could node v8 arrive in electron?

**Comment by sindresorhus** [comment]
@DrYSG That's not relevant to this issue.

**Comment by sindresorhus** [comment]
@zcbenz @kevinsawicki Any thoughts? This seems to be something many would like to have. I would be willing to do a pull request if accepted.

[Browser might get something similar](https://github.com/whatwg/html/pull/1936) too for document ready.

**Comment by zeke** [comment]
> I would be willing to do a pull request if accepted.

Go for it 👍

**Comment by zcbenz** [comment]
The `app.ready` case sounds good to me.

**Comment by codebytere** [comment]
hey @sindresorhus we're actually in the early stages of adding native promises to electron :) I'm going to close this in that event, and will let you know when that might be available!

**Comment by ckerr** [comment]
@codebytere is there another issue tracking that progress? I see it in the maintainers backlog, but the last discussion there was a month ago.

I realize this is a stale ticket, but if we're adding Promises IMO we should have something in `electron/electron/issues` to track that in a transparent way

**Comment by codebytere** [comment]
i thought there was, but i might be wrong :) If not, i might defer to @MarshallOfSound to add one with his anticipated timeline since he's spearheading that.

**Comment by ckerr** [comment]
Reopening this pending some resolution on how to track all of Promisification
