### ISSUE TITLE
The electron can combine by IE browsers but not Chromium?

### ISSUE THREAD

**Issue by Sailor20** [electron/electron#9562]
I want electron run in IE browsers not Chromium,what should i do?

**Comment by thomasjo** [comment]
Electron is built on top of Chromium, so what you are proposing is not going to happen. Since Internet Explorer is not (yet) open source, this your proposal is also practically speaking impossible.

**Comment by enlight** [comment]
Thanks @thomasjo, closing this issue.

**Comment by IDrinkMoreWater** [comment]
Why not consider ie tab Chrome Extension，Can be integrated in the electron

**Comment by tcorral** [comment]
@IDrinkMoreWater Do you have any example about how to use ie tab?

I did the following...
```javascript
let ieTabPath = "/Users/<user name>/Library/Application\ Support/Google/Chrome/Default/Extensions/hehijbfgiekmjfkfjpbkbammjbdenadd/10.11.7.1_0/";
  BrowserWindow.addExtension(ieTabPath);
```
but it didn't worked it still shows the webpage being opened using chrome.

**Comment by sheltont** [comment]
I want to show some special old pages from an IoT device with IE tab. I try electron + IE tab but no luck.  
How can I archive the goal if even I accept to write a native module?

**Comment by 499689317** [comment]
> @IDrinkMoreWater Do you have any example about how to use ie tab?
> 
> I did the following...
> 
> ```js
> let ieTabPath = "/Users/<user name>/Library/Application\ Support/Google/Chrome/Default/Extensions/hehijbfgiekmjfkfjpbkbammjbdenadd/10.11.7.1_0/";
>   BrowserWindow.addExtension(ieTabPath);
> ```
> 
> but it didn't worked it still shows the webpage being opened using chrome.

Have you solved this problem? I also encountered this problem.

**Comment by EternalQuasar0206** [comment]
I am developing a framework to develop desktop applications based in IE (supporting advanced features): https://github.com/EternalQuasar0206/htapps

**Comment by VieenWang** [comment]
> I want electron run in IE browsers not Chromium,what should i do?
Have you solved this problem?
