### ISSUE TITLE
using electron on SLES11SP4

### ISSUE THREAD

**Issue by jamesja64** [electron/electron#9573]
Hello guys, by some reason I have to run electron on SUSE Linux Enterprise Server 11 SP4.
But I got some problem for using electron on SLES11SP4.
There are some issues,
1. I can't fine any version of electron for SLES11SP4.
2. I can't build electron for SLES11SP4.
Does anyone can help me to solve those?

Many Thanks,
James

**Comment by cifratila** [comment]
@jamesja64 

Why can't you run it, any errors? Could you give us more information?

**Comment by MarshallOfSound** [comment]
Merging into #9541
