### ISSUE TITLE
Event on CommandOrControl+Tab click

### ISSUE THREAD

**Issue by andrewfan** [electron/electron#9577]
I'm working on the application that should appear on the shortcut click. Once user press shortcut I'm toggling window visibility with `show\hide` methods. 

My problem is when window was hidden by shortcut and the user pressed Cmd-Tab i have no event to be able to show the window.

I found similar issue here https://github.com/electron/electron/issues/2444 it is closed but `activate` event does not solve the problem (it is simply not firing) also i fond the same issue here 
https://discuss.atom.io/t/how-to-detect-the-activation-of-an-electron-window-on-macos-via-cmd-tab/39442

**Comment by tkambler** [comment]
A follow-up post has been left in the discussion thread that you referenced. Apparently you can tap into the `browser-window-focus` event. I have not had time to test this yet, but it sounds promising.

```
app.on("browser-window-focus", () => {
    // This occurs when any window in the app gains focus.
}
```

**Comment by tkambler** [comment]
Checking the `browser-window-focus` event out, and this does _not_ appear to solve this need.

**Comment by tkambler** [comment]
@andrewfan I have the answer we've been looking for. For reference, see [this issue](https://github.com/electron/electron/issues/2640).

The trick is to not hide your application's window, but rather to hide the _entire_ application itself via `Window.sendActionToFirstResponder`:

```
    globalShortcut.register('CommandOrControl+Alt+X', () => {
        if (mainWindow.isVisible()) {
            Menu.sendActionToFirstResponder('hide:');
        } else {
            mainWindow.show();
        }
    });
```

**Comment by andrewfan** [comment]
@tkambler I'm doing exactly the same and it still does not work for me. For now, I just removed my app from the dock and it made app disappear from app switcher.

**Comment by tkambler** [comment]
@andrewfan [Here is](https://github.com/tkambler/sideline) the sample app in which I implemented this. `cd` into the `app` dir, `npm install`, then `npm start`. Shortcuts are defined in `app/lib/main/window.js`.

**Comment by codebytere** [comment]
Closing as stale and seemingly resolved.
