### ISSUE TITLE
Literal ampersands in menu item labels

### ISSUE THREAD

**Issue by javan** [electron/electron#9584]
Is `label: 'A && B'` the correct way to display `A & B` in a menu item? `label: 'A & B'` does not work (the `&` is not displayed at all). I can't seem to find any relevant documentation.

Vague references:
https://github.com/electron/electron/issues/8881
https://github.com/electron/electron/issues/1698

**Comment by kevinsawicki** [comment]
> Is label: 'A && B' the correct way to display A & B in a menu item?


@javan yeah, it was fixed in https://github.com/electron/electron/pull/8984 to allow support for it.

**Comment by javan** [comment]
Cool, thanks. What's intended behavior of a single `&`?

**Comment by kevinsawicki** [comment]
Single `&` is an accelerator on Windows, `_` is one on Linux, it allows the menu item to be selected by the character following that character by pressing `Alt` plus that letter.

So `&File` allows the `File` menu to be opened with `Alt+F`.
