### ISSUE TITLE
Center browserWindow on display returned from getDisplayMatching()

### ISSUE THREAD

**Issue by cian-w** [electron/electron#9585]
I'm trying to center my window on an external display. By passing the bounds of the window (x,y,height,width) to getDisplayMatching() I can get the display I want to show the window on. 

How do I go about centering the window on this display?
I tried it by doing: 
`display = electron.screen.getDisplayMatching(rect)`
`mainWindow.center(display)`
but it didn't work. Is there any alternative?

Thanks

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

You're probably looking for math that looks something like this.

```js
const display = electron.screen.getDisplayMatching(rect)
const size = mainWindow.getSize();
mainWindow.setPosition((display.bounds.width / 2) - (size.width / 2), (display.bounds.height / 2) - (size.height / 2));
```
