### ISSUE TITLE
win.setOverlayIcon() or nativeImage.createFromPath() seems to be broken.

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#9594]
* Electron version: 1.6.7
* Operating system: Win 10, 7

Cannot set icon overlay in windows 10.
See: [setOverlayIcon.zip](https://github.com/electron/electron/files/1031894/setOverlayIcon.zip)

**Comment by cumajkeee** [comment]
To display an overlay icon, the taskbar must be in the default large icon mode. If the taskbar is configured through Taskbar and Start Menu Properties to show small icons, overlays cannot be applied and calls to this method are ignored

**Comment by davidkhanpk** [comment]
> To display an overlay icon, the taskbar must be in the default large icon mode. If the taskbar is configured through Taskbar and Start Menu Properties to show small icons, overlays cannot be applied and calls to this method are ignored

I was working on that issue for whole day, Thanks for the relief.
