### ISSUE TITLE
Does node version need to be matched to build electron?

### ISSUE THREAD

**Issue by hackjutsu** [electron/electron#9598]
This is a general question about running building electron application.

Does to node version we use to build the electron app has to match the node version bundled in electron?
I notice a weird issue when using Node 6.10 to build the latest Electron(Node 7.x). I'm not sure whether there is anything to do with the mismatch between the versions.

**Comment by cifratila** [comment]
@hackjutsu I have been using Node 2.x, 4.x, 6.x and 7.x to build different flavors of Electron, never seen issues. The only ones that appeared were when node-gyp had some issues on Windows and VS 2015 Update 3.

**Comment by hackjutsu** [comment]
@cifratila 

Thanks for answering this question:) Unfortunately, the failure is specific to our internal test which is non-trivial to explain or reproduce here. 

If matching the node versions is not an official prerequisite for building an Electron app, I think we are good to close this ticket.
