### ISSUE TITLE
Custom protocol and cookies for subdomains

### ISSUE THREAD

**Issue by winamp** [electron/electron#9601]
* Electron version: 1.6.8
* Operating system: macOS 10.12

### Expected behavior

Cookies can be set for subdomains from the page loaded through custom protocol. Same as regular pages via http

### Actual behavior

Cookies are not set for subdomains if the page currently opened is on subdomain itself.
For example, page address: app://app.example.com, I can't set cookie for .example.com, only app.example.com and .app.example.com.

### How to reproduce

```js
const {app, protocol, BrowserWindow} = require('electron');

protocol.registerStandardSchemes(['app'], {
	secure: true
});

app.on('ready', () => {
	protocol.registerFileProtocol('app', (req, cb) => {cb('index.html');});
	let win = new BrowserWindow();
	win.loadURL('app://app.example.com');
});
```

![screen shot 2017-05-26 at 12 42 57 pm](https://cloud.githubusercontent.com/assets/996918/26510332/b9bc72b2-4211-11e7-82b4-313db8d5c52c.png)

**Comment by deepak1556** [comment]
This is not possible to fix without changes from chromium side, since it is not expected for custom schemes with subdomains, the cookie store isn't made to recognize it. Closing this as won't fix.
