### ISSUE TITLE
auto update mechanism freezes app

### ISSUE THREAD

**Issue by maikelmclauflin** [electron/electron#9604]
* Electron version: v1.7.2
* Operating system: mac osx sierra 10.12.5 (16F73)
* Node Version: v7.10.0

### Expected behavior

User should be asked if they want to update the app.
updated to the latest version of electron and i'm still having some kind of trouble.
basically I have the auto update mechanism working up to the point where i actually ask the user if they want to update the app.
have not determined if issue is in the second update-downloaded event or in the electron.remote.dialog.showMessageBox method call
### Actual behavior

I never get to ask them because the app just freezes as if it is in a loop.
When I force quit the app and reopen I am at the newly downloaded version

### How to reproduce

```javsascript
var remote = electron.remote;
var app = remote.app;
var autoUpdater = remote.autoUpdater;
var dialog = remote.dialog;
var os = require('os');
var platform = os.platform() + '_' + os.arch();
var version = app.getVersion();
if (env.name === 'development') {
    return;
}
autoUpdater.setFeedURL('https://autoupdateurl.com/update/' + platform + '/' + version);
autoUpdater.on('checking-for-update', () => console.log('checking-for-update'));
autoUpdater.on('update-available', () => console.log('update-available'));
autoUpdater.on('update-not-available', () => console.log('update-not-available'));
autoUpdater.on('update-downloaded', () => console.log('update-downloaded'));
// Ask the user if update is available
autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => {
    // this line gets hit, but beyond this is a black box of infinite loopness
    electron.remote.dialog.showMessageBox(window, {
        type: 'question',
        buttons: ['Update', 'Cancel'],
        defaultId: 0,
        message: `Version ${releaseName} is available, do you want to install it now?`,
        title: 'Update available'
    }, (response) => {
        if (response === 0) {
            autoUpdater.quitAndInstall();
        }
    });
});
// Trigger autoUpdater
autoUpdater.checkForUpdates();
```

**Comment by mmclau14** [comment]
ok. I was able to get it to work by modifying showMessageBox call to not include the window argument

**Comment by mmclau14** [comment]
just wondering if anyone has looked into this

**Comment by enlight** [comment]
The window you're supposed to pass to `showMessageBox()` (if any) should be a `BrowserWindow`, what you appear to be passing in is the DOM window object.

**Comment by mmclau14** [comment]
ah. ok. well, perhaps this should have a check for type when it is passed and should have an error or at least a warning if the user, as I was in this case, is doing it wrong. but it definitely should not go into an infinite loop. am i wrong?

**Comment by MarshallOfSound** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so I'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
