### ISSUE TITLE
DevTools, files not refreshed in Workspace

### ISSUE THREAD

**Issue by darky** [electron/electron#9605]
* Electron version: 1.7.2
* Operating system: Kubuntu 17.04

### Expected behavior

Files should be refreshed in Workspace, if it will be edited not through devtools.
For example, `git pull` action

### Actual behavior

Files not refreshed

### How to reproduce

1. Open devtools
2. Add folder to Workspace
3. Edit some file not through Workspace
4. File not refreshed.

In electron 1.6.x this will be refreshed via reload (Ctrl + R). It's not defect of original Chrome DevTools, checked.

**Comment by MarshallOfSound** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so I'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
