### ISSUE TITLE
Can I auto update my Application use patch?

### ISSUE THREAD

**Issue by dengyaolong** [electron/electron#9606]
we use auto-updater to update out Application，so we need to download at least 100M the .mac.zip or NSIS.  However, the new .mac.zip and the old one is really like. Can I use diff & patch to update my application  that reduce the download size?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

If you use `Squirrel.Windows` for your windows installer you can use delta packages (so the update is much smaller).  Deltas aren't supported in `Squirrel.Mac` yet
