### ISSUE TITLE
I cannot install electron on windows 10

### ISSUE THREAD

**Issue by zo-tahiana** [electron/electron#9607]
Hello,

When I try to install `npm install electron` on windows, It take many minutes here:
`electron-prebuilt@1.4.13 postinstall G:\My Repositories\electron\node_modules\electron-prebuilt`
`node install.js`

After there is an error which appear.

Thanks!

**Comment by enlight** [comment]
No one can help you if you don't specify what the actual error is.

**Comment by zo-tahiana** [comment]
It's the same error like the [issue ](https://github.com/electron/electron/issues/9549)
I'm currently install electron with --verbose flag.
