### ISSUE TITLE
Background color does not cover whole window on resize

### ISSUE THREAD

**Issue by levrik** [electron/electron#9608]
* Electron version: (<=)? 1.6.6 - 1.7.2
* Operating system: Windows 10 1703

### Expected behavior

The red background color (set as option on the `BrowserWindow`) covers the whole window on resize.
I remember that behaviour from the last time I worked with Electron. Also noticed that issue in the current VS Code version (1.12.2).

### Actual behavior

![2017-05-27_19-06-11](https://cloud.githubusercontent.com/assets/9491603/26523090/923f684e-430f-11e7-8d22-ace63ffd59c0.gif)

### How to reproduce

https://gist.github.com/levrik/e4a15c3a8e65ab484e9de00092fa4f43 or for example VS Code 1.12.2

**Comment by levrik** [comment]
Friendly ping.

**Comment by MarshallOfSound** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so I'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by bpasero** [comment]
@MarshallOfSound I see the same behaviour with Electron 3.0.x.

**Comment by bpasero** [comment]
![before](https://user-images.githubusercontent.com/900690/45938169-752bc500-bfc7-11e8-9f15-0c7b17849ca0.gif)

**Comment by codebytere** [comment]
thanks @bpasero, i'll update labels!

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by bpasero** [comment]
Reproduces with Electron 6.x

**Comment by CraigMason** [comment]
![image](https://user-images.githubusercontent.com/307066/65174860-a0fe5100-da49-11e9-8d59-42a9975b3e11.png)

Some additional details. When resizing quickly, I see 3 different colours:

1. The HTML body's background color
2. The `BrowserWindow.backgroundColor` color
3. Black

**Comment by AssetKid** [comment]
Still happening on `7.1.7`

![2n4MZDV0HW](https://user-images.githubusercontent.com/40426812/71447276-853bd280-273d-11ea-9b04-83d7fddd0c7c.gif)

`backgroundColor` is set to white

**Comment by MattixNow** [comment]
Up

**Comment by CrownFox** [comment]
Still happening on version 10.1.1

This issue is more than 3 years old.

**Comment by lockieluke** [comment]
I think it is the problem of chromium, try to open your chrome and resize the window and you will see the same thing.

**Comment by miniak** [comment]
I don't think we can do much about this. Both Chrome and Edge have the same issue.

**Comment by FireMapleLeaves** [comment]
Still happening on 20.0.0

**Comment by vladrasenko** [comment]
the same on electron 36.9.5 macos 15.7.1
as workaround

```js
const win = new BrowserWindow({
  // ...
  backgroundColor: nativeTheme.shouldUseDarkColors ? "#000" : "#fff",
  // ...
});

const handleThemeUpdated = () => {
  win.setBackgroundColor(nativeTheme.shouldUseDarkColors ? "#000" : "#fff");
};

nativeTheme.on("updated", handleThemeUpdated); // do not forget to unsubscribe
````
