### ISSUE TITLE
TypeScript definitions for electron are a mess.

### ISSUE THREAD

**Issue by lord-saumagen** [electron/electron#9609]
# TypeScript definitions for electron are a mess.

Dear ladies and gentlemen. 

Recently I tried to start a TypeScript project using the electron framework. For that purpose   
I started a new TypeScript / node.js project from scratch and installed the electron npm   
package as well as the electron typedefinitions.
Unfortunately the electron typedefinitions are in a disastrous state. The compiler stopped   
counting the errors in the electron typedefinitions at 99.
It appears that no one ever considered to test the type definition.   
I also figured out that the latest electron typedefinition is the one for the electron   
framework "1.4.38" while the latest electron framework shows a release number of "1.6.10".   
You should really consider to make typedefinitions an integral part of your framework.    
That way you wouldn't release a new framework version without a matching typedefinition.   
(That typedefinition should be tested of course.)    
If you want to make it perfect, make the tyepdefinition also an integral part of your npm    
package. That way no one has ever to wonder where the right typedefinition four your    
framework can be found.   

Below is a picture of the compiler output after installing the electron typedefinitions.

![VS Code Electron project](https://cloud.githubusercontent.com/assets/9468599/26523924/4cf279ee-4313-11e7-8f20-10ae8dbca47e.png)

Your framework might be a respected piece of software in the JavaScript community,    
but for a programmer who has a strong focus on code quality our framework is a    
no go. I guess most TypeScript programmers chose to use TypeScript because they    
have a strong focus on code quality like I.    
I'm not writing this to diminish your work. I haven't enough experience with your    
framework to be qualified for a meaningful opinion. But I can tell you this. If    
want to make your framework shiny, give the TypeScript integration more attention.

Kind regards, Lord Saumagen.

**Comment by MarshallOfSound** [comment]
We ship typescript definitions internally now so there is no need to install the community maintained @types package.  This is why you are getting duplicates definition errors, both the @types package you installed and the Electron module are trying to declare the same apis.

**Comment by shiftkey** [comment]
@lord-saumagen additional feedback about the TS declarations can be reported here https://github.com/electron/electron-typescript-definitions/

**Comment by lord-saumagen** [comment]
Dear ladies and gentlemen.

I want to apology for my message. I was so overwhelmed by the sheer number of errors, that I didn't event try to investigate where they came from. 
Now that you have enlightened me, I have to say that you are far ahead of what I thought you were.
Electron rocks. I guess I have to be more careful before I start an issue.

Thank you for your superior work an kind support.

Kind regards, Lord Saumagen.
