### ISSUE TITLE
Show greyed out files when setting "openDirectory" in showOpenDialog

### ISSUE THREAD

**Issue by WolfWalter** [electron/electron#9612]
* Electron version: 3.0.0
* Operating system: Windows 7

### Expected behavior

When calling showOpenDialog with the openDirectory option files should be visible but greyed out like on Linux and OSX.
![bildschirmfoto von 2017-05-29 12-20-41](https://cloud.githubusercontent.com/assets/2098069/26546325/bab1b0c4-4469-11e7-80d6-dd0a2976f23b.png)

### Actual behavior

When calling showOpenDialog with the openDirectory option on Windows, only folders are shown. 

![open_directory_win](https://cloud.githubusercontent.com/assets/2098069/26546474/6d638eae-446a-11e7-8c68-aa21c7c54e22.png)

### How to reproduce

```
let importPath = electron.remote.dialog.showOpenDialog({
  properties: ['openDirectory']
});
```
hiddenFiles and filters do not help.

Also described here:
https://stackoverflow.com/questions/42133423/show-files-in-electron-dialog-showopendialog-when-open-directory

**Comment by codycraven** [comment]
Reproduced under Windows 10.

**Comment by talmukund** [comment]
I am facing this issue too. Are we fixing it.

**Comment by WolfWalter** [comment]
Finally found a workaround to get a "Directory chooser" in Windows. Just use a html input with type="file" and the webkitdirectory property.
[https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory)

**Comment by WolfWalter** [comment]
Only tested in chrome browser. In electron still not possible. Webkitdirectory shows same dialog as electron dialog :(

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by WolfWalter** [comment]
The issue still persists in electron 3.0.0. Please reopen.

**Comment by ishowshao** [comment]
这个问题有解决吗，对用户体验非常不友好
Is this problem solved? very unfriendly to the user experience

**Comment by ishowshao** [comment]
Reproduced on 4.0.4

**Comment by codebytere** [comment]
This is a Windows limitation, as seen [here](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/4a330e26-4d52-4fce-8a89-5c56fa132688/ifileopendialog-with-fospickfolders-vs-shbrowseforfolder?forum=windowsuidevelopment). There is no [documentation setting](https://docs.microsoft.com/en-us/windows/desktop/api/shobjidl_core/ne-shobjidl_core-_fileopendialogoptions) that allows for both to be shown, nor does msft appear to plan to fix this.

**Comment by WolfWalter** [comment]
For my usecase the Windows FolderBrowserDialog would be a perfect fit, but it is not available from electron?

**Comment by felixrieseberg** [comment]
👋 @WolfWalter I'm confused about your request. You can open an "open a folder" dialog from Electron just fine (using the `openDirectory` option) – displaying files within that dialog is currently not possible, which is (as far as we know) a Windows limitation.

If you have some example C++/C# code that'd open a folder picker that _also_ displays files, we'd love to see it!
