### ISSUE TITLE
Wrong font rendering on Open File windows

### ISSUE THREAD

**Issue by SalahAdDin** [electron/electron#9616]
* Electron version: 
```bash
electron -v                                                                                               ✓  940  18:38:53 
v1.4.16
```

* Operating system:
```bash
OS: Antergos  ISO-Rolling
Kernel: x86_64 Linux 4.11.2-1-ARCH
```
![photo_2017-05-29_17-37-00](https://cloud.githubusercontent.com/assets/5034215/26555975/79cabf7e-44a0-11e7-8c04-abb9b9664277.jpg)

### Expected behavior
![seleccion_014](https://cloud.githubusercontent.com/assets/5034215/26556035/d5a64f34-44a0-11e7-8342-e25e97800341.png)

### Actual behavior

![photo_2017-05-26_12-12-23](https://cloud.githubusercontent.com/assets/5034215/26555974/79c71b44-44a0-11e7-956f-b236b93c7f4c.jpg)
![photo_2017-05-29_17-36-59](https://cloud.githubusercontent.com/assets/5034215/26555977/79cefaa8-44a0-11e7-8583-7f2ba07a5624.jpg)
![photo_2017-05-29_17-37-35](https://cloud.githubusercontent.com/assets/5034215/26555976/79cb96f6-44a0-11e7-8639-9d1581a3ffae.jpg)

### How to reproduce
Try to open files in whatever `electron` based application, like open a repository in `gitkraken` or add a file, photo or whatever in `WhatsAppDesktop`.

**Comment by KillWolfVlad** [comment]
@SalahAdDin, try rebuild your application (e.g. GitKraken) with latest electron version
see Azd325/gitkraken#39 for more details

# Expected and Actual behavior

![image](https://cloud.githubusercontent.com/assets/18448635/26679833/2f037e52-46f0-11e7-92ff-db65a426358f.png)

**Comment by enlight** [comment]
This issue appears to be fixed in Electron 1.6.X.

**Comment by hinogi** [comment]
It is still a thing I suppose.

**Comment by adamdry** [comment]
This still happens for me on Ubuntu 24 - how do I fix it please?

**Comment by i-talha** [comment]
This still happens for me on Ubuntu 24 - how do I fix it please?
