### ISSUE TITLE
Bug: <webview> ==> Invisible rendering..

### ISSUE THREAD

**Issue by etiennepinchon** [electron/electron#9618]
Hey guys!

# The problem
I am trying to render a webview using ReactJS however the page cannot be rendered (invisible elements). Sometimes it actually works maybe 1 / 20 times.
It is very strange because the page is "there" as I can click on elements but those are not visible. 
Also, as soon as I click on a link from this invisible render, the page becomes visible!

# Example
Here is my code:

```javascript
import React, { Component } from 'react';
import styles from './WebPreview.css';

export default class WebPreview extends Component {
  componentDidMount() {
    this.preview.addEventListener("dom-ready", this.previewDidLoad);
  }

  componentWillUnmount() {
    this.preview.removeEventListener("dom-ready", this.previewDidLoad);
  }

  previewDidLoad = (event) => {
    console.log("Preview DOM is ready!", this.preview.getTitle());
  }

  render() {
    return (
      <div>
        <webview ref={elem => this.preview = elem} src={this.props.src} className={styles.preview} />
      </div>
    );
  }
}

```

# Note:
If I replace ```webview```by ```iframe``` the page will be rendered. So I guess the problem must come from electron webview tag.

# Update
I tried something simpler with only html, same problem!

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Webview Demo</title>
    <link rel="stylesheet" href="./styles/app.reset.css">
  </head>
  <body>
    <webview src="http://localhost:8005" style="position:fixed; top: 0; left: 0; width: 100%; height:100%;"></webview>
  </body>
</html>
```

Unless I do this (in this case it works but I need react :( ):
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>WebviewDemo</title>
    <link rel="stylesheet" href="./styles/app.reset.css">
  </head>
  <body>
    <webview style="position:absolute; top: 0; left: 0; width: 100%; height:100%;"></webview>
    <script>
      const webview = document.querySelector('webview')
      webview.setAttribute("src", "http://localhost:8005");
    </script>
  </body>
</html>
```
Any idea of what is going on?

Thanks!

**Comment by miniak** [comment]
@etiennepinchon please specify which Electron versions are affected. You can use https://github.com/electron/fiddle to test it with different versions.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
