### ISSUE TITLE
Where to store third party node modules

### ISSUE THREAD

**Issue by JohannBlake** [electron/electron#9620]
I went to install a third party node module like this:

$ npm install -g --save electron-config

This stored it under /user/local/lib/node_modules

However, when I ran my Electron app, it could not find it. I then ran npm without -g and it stores it in the my app's folder under the node_modules folder. Electron has no problem accessing it this way. Of course, the downside to this is that the module is not global for other uses.

Is it possible to use global modules in an Electron app that are located outside of the app's project directory?

**Comment by MarshallOfSound** [comment]
> Is it possible to use global modules in an Electron app that are located outside of the app's project directory?

No, that's how node's `require` search paths work, also it would be super unsecure 👍

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
