### ISSUE TITLE
setApplicationMenu implicitly shows window on Linux

### ISSUE THREAD

**Issue by t3chguy** [electron/electron#9621]
* Electron version: 1.6.2/1.6.8
* Operating system: Linux Ubuntu 16.04 KDE Neon

### Expected behavior
BrowserWindow remains hidden

### Actual behavior
BrowserWindow gets shown

### How to reproduce
instantiate BrowserWindow with `{show:false}` and loadURL
then setApplicationMenu, at which point in my case the window gets shown

This can be worked around by doing `mainWindow.hide()` right after setApplicationMenu but is inconsistent between environments, i.e is not needed on Windows or Mac.

Use case: app has a `--hidden` flag when passed does not do .show() on ready-to-show but app gets shown anyway due to this issue.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
