### ISSUE TITLE
Improve Handoff API support

### ISSUE THREAD

**Issue by lesleyandrez** [electron/electron#9622]
* Electron version: 1.6.10
* Operating system: macOS Sierra 10.12.4 (16E195)

# Improve Handoff API support

Hi!

Today the API of Handoff provides the methods: `setUserActivity`, `getCurrentActivityType` and dispatch the event `continue-activity`

I'm using Handoff and noticed that in some circumstances the broadcast takes a long time to update its userInfo which does not happen on the native iOS client

1. To invalidate or resign the current activity we currently need to create a non-existing activity type and set it as the current activity. There's no way to handle the activity life cycle through electron.
2. When we need to update a given user activity userInfo frequently (i.e in response to a search bar's text changes), we have no efficient way. Setting a new userActivity with the updated information takes several seconds to bridge, whereas doing this on iOS native app is instantaneous.

I believe that exposing a bit more of the NSUserActivity API to Electron would help, namely `becomeCurrent`, `resignCurrent` and `invalidate` which would address point 1, and `needsSave` and a new event to allow updating an activity when needed to address point 2.
These are described in more detail in https://developer.apple.com/reference/foundation/nsuseractivity.

I'm are open to help in any way i can such as explaining how the native API work, providing sample code or testing possible implementations

Thank you!

**Comment by codebytere** [comment]
The invalidate method has been added, and i've opened a new PR to allow `resignCurrent`: https://github.com/electron/electron/pull/18659
