### ISSUE TITLE
TypeError: Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by steric85** [electron/electron#9624]
* Operating system:
macOS Seirra (10.12.5)

I am trying to use `electron-pdf` to create PDFs using Node. For doing so I used the code given by @midweststudios at [Issue #138](https://github.com/fraserxu/electron-pdf/issues/183). On doing `npm start` I am getting the following error:
```
/Users/a/makePDF/node_modules/electron-pdf/lib/index.js:45
electronApp = electron.app;
                      ^
TypeError: Cannot read property 'app' of undefined
    at start (/Users/a/makePDF/node_modules/electron-pdf/lib/index.js:45:49)
    at Object.<anonymous> (/Users/a/makePDF/index.js:7:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
```
Inshort, I am unable to import `electron`. Logging the value of electron gives a path :
`/Users/a/makePDF/node_modules/electron-pdf/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron`
You can see my code in [my github repo](https://github.com/steric85/makePDF).
I tried using `const electron = require('electron').remote` instead `const electron = require('electron')` , but that doesn't work either. Referring to other `electron` issues I uninstalled electron globally and locally, but it didn't make any difference. Please help me in fixing this.
Thanks in advance 😄

**Comment by midweststudios** [comment]
@steric85 This is not the place to log your issue. Please keep all questions and correspondence within the tool's master git repository.

**Comment by zeke** [comment]
`require('electron')` from node returns a path, and from electron it returns a module.

This is not an issue with Electron. As @midweststudios pointed out, the best place to discuss this would be: https://github.com/fraserxu/electron-pdf/issues/183

**Comment by steric85** [comment]
I am really sorry for writing this here. I felt it was some issue with electron. 
Thanks a lot for explaining.
Sorry :|

**Comment by zeke** [comment]
No worries, @steric85. Thanks for understanding!
