### ISSUE TITLE
TypeScript translation missing for Electron.SystemColor

### ISSUE THREAD

**Issue by mrfunkycold** [electron/electron#9628]
* Electron version: 1.7.2
* Operating system: all

### Expected behavior
Living in electron.d.ts
```
namespace Electron {
type SystemColor = '3d-dark-shadow' | '3d-face' | '3d-highlight' |
  '3d-light' | '3d-shadow' | 'active-border' | 'active-caption' | 'active-caption-gradient' |
  'app-workspace' | 'button-text' | 'caption-text' | 'desktop' | 'disabled-text' | 'highlight' |
  'highlight-text' | 'hotlight' | 'inactive-border' | 'inactive-caption' | 'inactive-caption-gradient' |
  'inactive-caption-text' | 'info-background' | 'info-text' | 'menu' | 'menu-highlight' | 'menubar' | 'menu-text' |
  'scrollbar' | 'window' | 'window-frame' | 'window-text';
}
```
Within code..
```
const menuText = 'menu-text' as Electron.SystemColor; // typings for all available colors.
systemPreferences.getColor(menuText);
```

### Actual behavior
```
const menuText = 'menu-text' as Electron.SystemColor; // fails since this doesn't exist
systemPreferences.getColor(menuText);
```

### How to reproduce
Update the repo to electron 1.7.2. Use TypeScript. Create a module and copy/paste the code snippet above. If using an IDE with TypeScript IntelliSense (i.e. Visual Studio Code), it will produce an error stating SystemColor doesn't exist on Electron.  

Not sure this is an actual bug.  This exists currently on the `@types/electron` definition but doesn't exist here.

**Comment by zeke** [comment]
Third-party definitions, for reference: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/21a50f928ba9a8617ff89a66faa5c39e79dce420/types/electron/index.d.ts

**Comment by zeke** [comment]
There's currently no concept of ENUM support in the markdown docs, by which I mean "strings that have a specific set of possible values".

We do have the notion of "structures", but currently this only applies to key-value objects like  [CrashReport](https://github.com/electron/electron/blob/master/docs/api/structures/crash-report.md):

```
# CrashReport Object

* `date` String
* `ID` Integer
```

We could introduce a similar concept for ENUMs, like so:

```
### `systemPreferences.getColor(color)` _Windows_

* `color` [SystemColor](enums/system-color.md)
```

And in `enums/system-color.md`:

```
# SystemColor ENUM

* `3d-dark-shadow` - Dark shadow for three-dimensional display elements.
* `3d-face` - Face color for three-dimensional display elements and for dialog
  box backgrounds.
* `3d-highlight` - Highlight color for three-dimensional display elements.
* `3d-light` - Light color for three-dimensional display elements.
* ...
```

@MarshallOfSound what do you think of this idea?

**Comment by MarshallOfSound** [comment]
We do reconigze enum's already through 😕 

https://github.com/electron-userland/electron-prebuilt/blob/master/electron.d.ts#L3446

This is a non-issue IMO, the type doesn't exist but the type checking is still there.  The enum just isn't exported, it's declared inline.

**Comment by MarshallOfSound** [comment]
I.e.

```js
import * as electron from 'electron';

const color = 'bad color'

electron.systemPreferences.getColor(color);
```

Will throw a typescript type error, we don't need to explicitly export the enum afaik

**Comment by MarshallOfSound** [comment]
Closing out as per comments above 👍
