### ISSUE TITLE
Is there any way to send push notifications to an Electron application?

### ISSUE THREAD

**Issue by tregismoreira** [electron/electron#9629]
I was looking around and saw that the Chrome Web Push Notification isn't available for Electron yet, but is there another way to send notifications for my app?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

On this topic though, see #6697

**Comment by eladnava** [comment]
For anyone still interested, [Pushy](https://pushy.me/) has just added support for sending push notifications to Electron apps using a background MQTT connection:
[pushy-me/pushy-electron](https://github.com/pushy-me/pushy-electron)

Refer to the docs for integration steps:
https://pushy.me/docs/additional-platforms/electron

Full disclosure: Pushy is a paid product that I helped found.
