### ISSUE TITLE
Cross Frame Drag-Drop making destination frame go black

### ISSUE THREAD

**Issue by oneandonlyone** [electron/electron#9632]
* Electron version: 1.7.1 beta 
(Drag-drop issues started with Electron 1.4 version, and in 1.7 drag-drop works but causes cross frame black screen issue - may be associated with new chromium restrictions)

* Operating system:
Windows (many versions including 10, Surface, etc)

### Expected behavior

Dragged information should be received by the destination window without the destination window disappearing and going black. In older versions such as 1.3.* or electron, drag-drop is handled nicely (Destination frame receives the drop and processes event.)

### Actual behavior
Consider two adjacent iframes in an electron app (with one remote and one local/remote page). 
In 1.7.1 Electron, the drop of the content onto second iframe from first, the second iframe goes black (and its contents disappear). No way to recover the second iframe at this point.

 (Note that this used to work in 1.3.* without issues.)

### How to reproduce

Let us say there are two adjacent iframes (visible at the same time) with two different domains (or one from a remote domain and one local). Drag-drop content from one iframe to the other. Upon drop, the destination frame content disappears and becomes a black frame (happens often). 

In previous versions of electron, the black window appeared on drag-over itself.

**Comment by stef-pellegrino** [comment]
The bug remains on last version 1.8.2

**Comment by leotada** [comment]
The bug remains on 2.0.0 version on Fedora Linux 28 x64 with Intel HD Graphics.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
