### ISSUE TITLE
Starting a download breaks/closes EventSource

### ISSUE THREAD

**Issue by rreimann** [electron/electron#9633]
* Electron version: 1.6.10
* Operating system: macOS 10.12.4

### Expected behavior

An existing [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) on a page should remain open and continue to receive server-sent events after a download is initiated.

See also: https://discuss.atom.io/t/starting-a-download-seems-to-break-eventsources/34765

### Actual behavior

The EventSource gets closed and does not reconnect as soon as a download-link is clicked which doesn't seem appropriate compared to the behaviour in Chrome and according to the spec at https://html.spec.whatwg.org/multipage/comms.html#dom-eventsource-closed

> CLOSED (numeric value 2)
The connection is not open, and the user agent is not trying to reconnect. Either there was a fatal error or the close() method was invoked.

### How to reproduce

  $ git clone https://github.com/rreimann/electron-quick-start.git -b download-breaks-eventsource
  $ npm install
  $ npm start || electron .

See the page rendering/receiving a new timestamp every 5 seconds. Click the download-link and observe the `EventSource.readyState` switching from `1 — open` to `2 — closed` and no more timestamp updates.

While opening [index.html](https://github.com/rreimann/electron-quick-start/blob/download-breaks-eventsource/index.html) in Chrome and performing the same steps as described above the `EventSource` keeps open and continues to receive events after downloading.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
