### ISSUE TITLE
Crash error in video streaming on a custom protocol

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#9635]
* Electron version: 1.7.1
* Operating system: MacOS 10.12.5

Rendering a `<video>` stream in a custom (http) protocol will crash Electron. The same video streamed from the http handler does not crash the process.

One notable feature is that the crash likelihood seems to be increased by reducing the range in the response to 1MB ([this line](https://github.com/pfrazee/electron-bug-video-stream-crash/blob/master/server.js#L14)).

### How to reproduce

https://github.com/pfrazee/electron-bug-video-stream-crash

```
git clone https://github.com/pfrazee/electron-bug-video-stream-crash
npm install
npm start
```

**Comment by deepak1556** [comment]
The underlying issue is same as https://github.com/electron/electron/issues/9342 , merging to it. Thanks for the report!

**Comment by pfrazee** [comment]
Yay! Yall rock as always
