### ISSUE TITLE
dialog.showMessageBox not displaying modal window in windows

### ISSUE THREAD

**Issue by tdhawan** [electron/electron#9637]
Electron version:1.6.7
Operating system: Mac OS 10.12.4

### Expected behavior

dialog.showMessageBox should show a modal window. if the action is not taken on the modal window, the other windows/ app should not close.

### Actual behavior

1. app modal works in macOS when we use this implementation : dialog.showMessageBox(options: ShowMessageBoxOptions, callback?: (response: number) => void): number;
however its NOT WORKING in win32

2. app modal works in win32 when we use this implementation: 		dialog.showMessageBox(browserWindow: BrowserWindow, options: ShowMessageBoxOptions, callback?: (response: number) => void): number;
however its NOT WORKING in macOS

So, we have to make these 2 separate calls depending on platform. ideally it should be just one call, that should create the modal window regardless of the operating systems.

### How to reproduce

1. implement a modal window with this call 
dialog.showMessageBox(options, callback);
it will work as modal window in macOS, not in win32

2. implement a modal window with this call 
dialog.showMessageBox(browserWindow, options, callback);
it will work as modal window in win32, not in macOS
-->

**Comment by codebytere** [comment]
Does this occur on newer versions such as `2.0.0`?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
