### ISSUE TITLE
checkboxLabel in dialog not working?

### ISSUE THREAD

**Issue by gielcobben** [electron/electron#9641]
This is my code:

```
  showNothingFoundDialog() {
    const dialog = remote.dialog;
    const options = {
      type: "question",
      buttons: ["OK", "Cancel"],
      message: "This is a test.",
      checkboxLabel: "Do not show this message again."
    };

    dialog.showMessageBox(options, (response, checkboxChecked) => {
      console.log(response, checkboxChecked);
    });
  }
```

And this is the result:

![image](https://cloud.githubusercontent.com/assets/2663212/26650958/73c15bae-464b-11e7-88d4-272c098acda1.png)

I use Electron v1.6.10.

**Comment by kevinsawicki** [comment]
@gielcobben are you sure `this.dialogCallback` is defined? I can only reproduce this behavior when passing in an `undefined` callback.

**Comment by gielcobben** [comment]
I updated my code, still not showing.

**Comment by kevinsawicki** [comment]
@gielcobben can you try running the following from the dev tools console?

```js
require('electron').remote.dialog.showMessageBox({
      type: "question",
      buttons: ["OK", "Cancel"],
      message: "This is a test.",
      checkboxLabel: "Do not show this message again."  
    }, function (...args) { console.log(...args) })
```

**Comment by gielcobben** [comment]
Same result.

![image](https://cloud.githubusercontent.com/assets/2663212/26651726/f4222812-464d-11e7-9795-6abd198da293.png)

**Comment by kevinsawicki** [comment]
@gielcobben what dialog appeared when you ran it?

**Comment by gielcobben** [comment]
Exactly the same as showed above.

**Comment by kevinsawicki** [comment]
Hmm, so strange, can you open the default electron app and try the same, this is what I'm seeing:

<img width="932" alt="screen shot 2017-05-31 at 1 18 41 pm" src="https://cloud.githubusercontent.com/assets/671378/26652113/af2f5bac-4603-11e7-8f63-41d36895249d.png">

**Comment by gielcobben** [comment]
Hmm I had a old version symlinked. It shows the check box now. Thanks for the awesome support!

**Comment by kevinsawicki** [comment]
> Hmm I had a old version symlinked. It shows the check box now. Thanks for the awesome support!

Glad to hear it is working now 👍
