### ISSUE TITLE
Webview redirect fails to load

### ISSUE THREAD

**Issue by lukeapage** [electron/electron#9647]
* Electron version: 
1.7.2 - OK
1.6.11  - has bug
1.6.3 - has bug
1.6.2 - does not appear to have bug, but has other instabilities
1.5.1 - OK
1.3.x and before - OK
* Operating system: Windows 8

### Expected behavior

Page should redirect ok as it used to..

### Actual behavior

At some point during redirect, the page fails to load. This shows the did-load-fail event occuring after a did-navigate.

![image](https://cloud.githubusercontent.com/assets/309321/26677670/42c48404-46cd-11e7-81e6-0990ddf3b369.png)

The bug occurs 1 time in 2, but on a different redirect each time.

As well as getting load fail, the webview does not render anything and if devtools is attached to the window, it shows a disconnected message.

According the fiddler the page that the webview emits a load fail on is fetched successfully - no network problems with the page.

I've investigated if it could be:
#8505 but changing the webview to always be visible doesn't help
#6139 but disabling hardware acceleration does not help

I've looked up the error code 0 and error status "OK" and can't find any info about what might cause it.

Any help debugging or diagnosing would be appreciated.

**Comment by lukeapage** [comment]
more events:
![image](https://cloud.githubusercontent.com/assets/309321/26678316/455098ae-46d0-11e7-8698-3e2031074161.png)

there is approximately 50 between the successfull receive of the content and the did fail load.

**Comment by lukeapage** [comment]
Same error occurs on an all https live environment. no certificate errors. no gpu crashes.

**Comment by lukeapage** [comment]
Other webview navigation bugs seem to reference 1.6.3 as when they were introduced (https://github.com/electron/electron/issues/9231#issuecomment-298318806). The most relevant change in 1.6.3 is:

https://github.com/electron/electron/pull/8724

previously also mentioned as suspicious one comment above - @kevinsawicki @deepak1556

**Comment by lukeapage** [comment]
OK so 1.7.2 works fine. I should have checked that first.

**Comment by Nashorn** [comment]
Problem still exist in Electron 5/chrome 73
