### ISSUE TITLE
crash when creating remote object in sandboxed renderer

### ISSUE THREAD

**Issue by lneir** [electron/electron#9649]
* Electron version: 1.6.11
* Operating system: MacOS Sierrra (10.12.5)

### behavior

Trying to create remote object in sandboxed renderer will fail if an Object tag (or iframe) is added to the dom then removed.  Adding Object tag to the dom causes preload to get invoked because this creates a new JS context and I presume removing appears frees up context and somehow messes up lifetime of remote.  Also this bug will happen if an iframe is loaded (with same domain as parent).

### How to reproduce

This repo demonstrates the issue...

https://github.com/lneir/electron-remote-constructor-crash

This bug seems to have been introduced in 1.6.7.  It doesn't happen right away there but will occur if repo steps are repeated a few times.  It happens first time in 1.6.11 and also 1.7.2.  This issue does not happen when sandbox is turned off for main window.

The error message seen in console is:
Uncaught Error: Cannot call constructor on missing remote object 6

The error is being produced in main process by code: https://github.com/electron/electron/blob/master/lib/browser/rpc-server.js#L303

Appears that main process is somehow removing entry in "objectsRegistry"

**Comment by lneir** [comment]
i took a look at code and don't see straightforward way to fix this, seems in renderer side there is some caching (https://github.com/electron/electron/blob/master/lib/renderer/api/remote.js#L236) and possibly interfering with ref counting in main process.   @tarruda can you please take a look, thanks.

**Comment by tarruda** [comment]
I see the problem. Right now each remote object only has 1 reference per webContents, and #9389 fixed this for multiple windows in the same process(for both `sandbox` and `nativeWindowOpen`), but it's still a problem for iframes(and possibly any other construct that creates multiple contexts in the same `webContents`).

Right now I can't think of a simple way to fix this, I guess it would involve the main process allowing 1 reference per renderer frame or context, but I don't think we currently have an API that exposes this kind of granularity. @zcbenz do you have some idea on how to fix?

**Comment by lneir** [comment]
@tarruda @zcbenz any updates on this issue?  thanks.

**Comment by tarruda** [comment]
@lneir I didn't think of anything yet, sorry. Maybe @zcbenz or @kevinsawia have a lead.

**Comment by VikasShashidhar** [comment]
@zcbenz @tarruda Any updates regarding this? Thanks.

**Comment by VishwasShashidhar** [comment]
@tarruda @zcbenz any luck on this issue please?

**Comment by VishwasShashidhar** [comment]
I can't repro this with Electron 2.0.3
Tried with the repro steps multiple times and didn't see any errors on the console.

@tarruda @zcbenz Was anything changed related to rpc-server / remote in 2.x.y that may have fixed this?

Tried with the following versions too:

Electron Version | Status
------ | ------
1.6.7 | Not Reproducible
1.6.11 | Reproducible
1.7.2 | Reproducible
1.8.4 | Reproducible
2.0.0 | Not Reproducible
2.0.1 | Not Reproducible
2.0.2 | Not Reproducible
2.0.3 | Not Reproducible

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
