### ISSUE TITLE
asar support for Tray Icon

### ISSUE THREAD

**Issue by zh99998** [electron/electron#9650]
* Electron version: 1.6.10
* Operating system: Windows

### Expected behavior

load Tray icon from asar package
### Actual behavior

![image](https://cloud.githubusercontent.com/assets/359622/26708549/036ac2fc-477f-11e7-8ee6-cb3c359e1864.png)

### How to reproduce
```javascript
new Tray('images/icon.ico')
```
in a asar-packaged app

**Comment by zh99998** [comment]
well, seems dup #1006 
it says fixed but still happens

**Comment by KagamiChan** [comment]
Using an absolute path will work, try something like `path.join(__dirname, 'images', 'icon.ico')`

**Comment by kevinsawicki** [comment]
> Using an absolute path will work, try something like path.join(__dirname, 'images', 'icon.ico')

Yes, absolute paths are required, closing this out, thanks @KagamiChan

**Comment by raphadko** [comment]
Still happening (Electron v4.1.1)
Tried 	`tray = new Tray(path.join(__dirname,'images','logo.png'));`
No success (also https://github.com/electron/electron/issues/1006) was closed with people still having the issue.

**Comment by raphadko** [comment]
Found the bug.
When packing an .asar file, the insensitive case of windows becomes now sensitive (I believe, since files are dynamically fetched, path comparison then becomes string comparison). Renamed Logo.png to logo.png and it worked.
