### ISSUE TITLE
TypeScript translation broken for BrowserWindow.setOverlayIcon

### ISSUE THREAD

**Issue by mrfunkycold** [electron/electron#9654]
* Electron version: 1.7.2
* Operating system: All (but test feature on Win 10)

### Expected behavior

```
const {BrowserWindow} = require('electron');
const win = new BrowserWindow();

win.setOverlayIcon(null, ''); // resets the overlay icon
});
```

### Actual behavior

```
const {BrowserWindow} = require('electron');
const win = new BrowserWindow();

win.setOverlayIcon(null, ''); // only allows you to set a native Image
});
```

### How to reproduce
Update the repo to electron 1.7.2. Use TypeScript. Create a module and copy/paste the code snippet above. If using an IDE with TypeScript intellisense (i.e. Visual Studio Code), null value in `setOverlayIcon` will be highlighted in red. Error indicated is: `[ts] Argument of type 'null' is not assignable to parameter of type 'NativeImage'.`

**Comment by mrfunkycold** [comment]
Work around is the following:

```
win.setOverlayIcon(null as any, '');
```

**Comment by MarshallOfSound** [comment]
Merging into electron/electron-typescript-definitions/issues/25

Could you raise any future typescript definition issues over on that repository so we have a unified group of issues 👍

**Comment by mrfunkycold** [comment]
@MarshallOfSound sounds good. will do. 👍
