### ISSUE TITLE
`window.history.go(-1)` does not always go to the previous history state

### ISSUE THREAD

**Issue by drewmacneil** [electron/electron#9655]
* Electron version: 1.6.10
* Operating system: macOS 10.12.5

### Short description

Performing `window.history.go(-1)` should always go to the prior state on the history stack, even if the URL for the prior state matches the current URL. This is best illustrated with an example.

### Example

1. `electron https://en.wikipedia.org/wiki/Electron`
2. Open the developer tools and switch to the JS console.
3. Run `window.location.href`, observe the result is 'https://en.wikipedia.org/wiki/Electron'.
4. Click the 'Composition' link in the sidebar on the right.
5. Run `window.location.href`, observe the URL is 'https://en.wikipedia.org/wiki/Particle#Composition'.
6. Run `window.history.pushState('new_state', 'title', window.location.href)`.
7. Run `window.location.href` and notice the result is the same as Step 5.
8. Run `window.history.state` and observe that 'new_state' is returned.
9. Run `window.history.go(-1)`.
10. Observe that you are back at the original URL (ie. `window.location.href` is 'https://en.wikipedia.org/wiki/Electron'). This is incorrect behavior.

Step 10 visually should not have done anything, because 'https://en.wikipedia.org/wiki/Particle#Composition' should have been in the history stack twice (once for the navigation in Step 4 and again for the manual `pushState` call in Step 6). This is what happens in Chrome 58.

Another observation is that replacing Step 6 with a call to `window.history.pushState('new_state', 'title', window.location.href + '#')` (ie. add '#' to the current URL when pushing the new state) results in Step 10 doing the right thing; you remain on the 'Composition' page.

### Expected behavior

Currently, Electron seems to go back to the most recent unique URL when performing `window.history.go(-1)`. It shouldn't do that; it should always go to the previous history state, even if it contains a URL that matches the current one.

**Comment by MarshallOfSound** [comment]
Merging into #9296

There is a PR up to fix that issue #9468
