### ISSUE TITLE
Changing devtools preferences doesn't reload the UI

### ISSUE THREAD

**Issue by jhen0409** [electron/electron#9660]
* Electron version: 1.7.2
* Operating system: macOS Sierra

### Expected behavior

In the browser devtools, it should reload the devtools when we do a one of the following items:

1. Change the devtools theme
2. Click `Restore defaults and reload`

### Actual behavior

It doesn't reload In Electron devtools, I have to manually restart the devtools.

### How to reproduce

The `Expected behavior` have explained.

It's also related to https://github.com/jhen0409/react-native-debugger/issues/87. It should be a longterm problem, but I can't found the similar issues on this repo.

**Comment by MarshallOfSound** [comment]
I reproed this myself last week while playing with chrome devtools dark mode, still occurs on `3.0.x`

**Comment by ThiagoMartinsSaraiva** [comment]
I reproduced this today while changing the devtool's theme manually to dark.
Electron Version: 4.0.7
Operation System: Windows 10

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
