### ISSUE TITLE
SVG icons support on nativeImage

### ISSUE THREAD

**Issue by bil-elmoussaoui** [electron/electron#9661]
* Electron version: v1.6.9
* Operating system: Arch Linux with Gnome as DE

### Expected behavior
NativeImage does not support SVG images :( I've to convert the images to png's and there's no easy way to doing so (use external libraries that almost every one of them requires PhantomJs...)

Every Linux distro supports using SVG icons for Tray icons. And so should nativeImage on Linux desktop.

### Actual behavior
Doesn't work as SVG icons are not supported

### How to reproduce
```javascript
const nativeImage = require('electron').nativeImage

let image = nativeImage.createFromPath('/Users/somebody/images/icon.svg')
console.log(image)
```

The reason why I need this is that I've created a simple package to look for an icon on current icon theme used by the user. This way, electron applications can look more native with tray icons that can be themed by any theme designer (without any hackish solution like extracting the user file...)
And every icon theme on Linux is using SVG icons.  I hope this convince you enough to make this happen:+1:

**Comment by bil-elmoussaoui** [comment]
It appears that's somehow a duplicate of this https://github.com/electron/electron/issues/9642

**Comment by deadcoder0904** [comment]
Hey @bilelmoussaoui did you find a solution for supporting SVG not only on Linux but alternative platforms❓
