### ISSUE TITLE
Can't register service workers for a custom protocol

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#9663]
* Electron version: 1.6.10
* Operating system: MacOS 10.12.5

Registering a service worker with a custom protocol gives this error:

`ServiceWorker registration failed:  DOMException: Failed to register a ServiceWorker: No URL is associated with the caller's document.`

This occurs despite following this process:

```js
// in index.js
electron.protocol.registerStandardSchemes(['custom'], { secure: true })

function onReady () {
  electron.protocol.registerServiceWorkerSchemes(['custom'])
  electron.protocol.registerHttpProtocol('custom', ...)
  // ...
}

// in webview-preload.js
webFrame.registerURLSchemeAsPrivileged('custom', {allowServiceWorkers: true})
```

Demonstrated with https://github.com/pfrazee/electron-bug-service-workers-failure

```
git clone https://github.com/pfrazee/electron-bug-service-workers-failure
cd electron-bug-service-workers-failure
npm i
npm start
```

**Comment by pfrazee** [comment]
I did some initial digging and found the flags are not being included in the CLI switch in https://github.com/electron/electron/blob/7d3b58aab1a894daf5bd23fb7f8ce3f65f1a4407/atom/app/atom_content_client.cc#L205. If I have time, I'll try to find out why.

**Comment by pfrazee** [comment]
It looks like [AddAdditionalSchemes](https://github.com/electron/electron/blob/7d3b58aab1a894daf5bd23fb7f8ce3f65f1a4407/atom/app/atom_content_client.h#L26) -- where the switches are acted on -- is called after [AppendExtraCommandLineSwitches](https://github.com/electron/electron/blob/7d3b58aab1a894daf5bd23fb7f8ce3f65f1a4407/atom/browser/atom_browser_client.h#L62), where the registrations are acted on.

I'm going to see if I can solve this by moving the registration to before the 'ready' event.

**Comment by pfrazee** [comment]
I had no luck. The call order of those two methods aren't controlled within electron, and I couldn't find an alternative way to register service-worker schemes that worked.

I tried using `blink::SchemeRegistry::registerURLSchemeAsAllowingServiceWorkers()` from within `RendererClientBase::RenderThreadStarted` but that didn't solve it.

**Comment by pwnsdx** [comment]
Hello, having the exact same error.. Really strange!

**Comment by raphaelrobert** [comment]
Thanks for fixing #9342! @zcbenz @zeke 

Unfortunately this bug still prevents using a custom protocol. Any chance you can fix this as well?

**Comment by RyanEwen** [comment]
I am having a similar issue. I don't get the same error, instead I see a `GET` error with the worker URL followed by `net::ERR_<unknown>`

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by pwnsdx** [comment]
@codebytere: It still happens on Electron 2 and 3. Does that mean nobody is investigating?

**Comment by Jaifroid** [comment]
Still happening with Electron 5.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by johannesjo** [comment]
8.x.x
7.x.x
8.0.0
