### ISSUE TITLE
Windows 7 notifications taking up half the screen

### ISSUE THREAD

**Issue by alexbrazier** [electron/electron#9665]
* Electron version: 1.6.10
* Operating system: Windows 7

### Expected behavior

Notification size should be smaller, similar to the one you can just see in the screenshot below that you can just see the bottom of, behind the large notification.

### Actual behavior

The new notifications for windows 7 are taking up half of the screen space as seen in the image below:
![image](https://cloud.githubusercontent.com/assets/5689874/26761521/f2eec2c4-4928-11e7-9572-6df74ddb7ad1.png)

I'm running windows in parallels on a mac, so I expect it to be a screen resolution issue (2880x1800)

### How to reproduce

Test notifications on Windows 7 with parallels on a mac, or use Windows with a high screen resolution (e.g. 2880x1800).

**Comment by kevinsawicki** [comment]
@alespergl any thoughts on this one?

**Comment by alespergl** [comment]
Hm, high-DPI should be catered for in the implementation, although I haven't tested the Parallels scenario. I'll look into it.
