### ISSUE TITLE
GamePad API accepts input when window not in focus

### ISSUE THREAD

**Issue by LukePulverenti** [electron/electron#9669]
* Electron version: 1.7.2, 1.6.11, 1.4.16
* Operating system: Windows 10, Windows 8, Windows 7

### Expected behavior

GamePad API should mimic browser behavior and only accept input when electron window is focused.

### Actual behavior

GamePad API always accepts input, even with window minimized or out of focus.

### How to reproduce

Run an input loop using requestAnimationFrame to listen for GamePad input. Or load this url into an electron browser window: 

http://html5gamepad.com

Observe that input is handled with electron not in focus. As time allows i will create a sample repository. Thanks !

**Comment by sofianguy** [comment]
@LukePulverenti 
can you give Electron version 2.0.0 a try and see if the issue persists?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by alexbuckland** [comment]
This sounds more like a feature to me. In multi window applications you may wish to anchor the input in one window whilst another window is active.
