### ISSUE TITLE
Option to keep Chromium's browser interface

### ISSUE THREAD

**Issue by Jop-V** [electron/electron#9670]
It would be helpful if there was an option to keep the user interface of Chromium, with its back/forward buttons, reload button and tabs (and theoretically even Google account history syncing). 

Would this be hard, has the codebase deviated too much?

**Comment by enlight** [comment]
Electron is built on top of the [Chromium Content module](https://www.chromium.org/developers/content-module), the browser UI/chrome you're talking about is not part of that module. Electron is meant to be a framework for building desktop apps, not browsers, so the browser UI you want will not be added to the core. You can re-implement most of the usual browser UI using HTML/CSS/JS (see #1862), but keep in mind that Electron is not as secure as Chrome (at the moment) so using it as a general purpose browser would be a **Bad Idea**.

**Comment by levrik** [comment]
@Jop-V If you want to build a browser-like app with Electron you should take a look at https://github.com/brave/muon. It's a Electron fork but with all security features included. But I don't think it includes the Chromium interface too.
