### ISSUE TITLE
Window: backgroundColor does not match CSS color

### ISSUE THREAD

**Issue by bpasero** [electron/electron#9671]
* Electron version: 1.7.x
* Operating system: macOS 10.12.5

### Expected behavior

Setting a window `backgroundColor` should produce the same visual result as setting it via CSS.

### Actual behavior

There is a slight flicker from where the background color from CSS kicks in.

### How to reproduce

* create a window with background color: `new BrowserWindow({ width: 800, height: 600, backgroundColor: '#DDDDDD' })`
* in that window set the same background color via CSS: `<body style="background-color: #DDDDDD;">`
* `loadURL` of the window with a slight timeout to see the difference
```javascript
setTimeout(function () {
    win.loadURL(url.format({
        pathname: path.join(__dirname, 'index.html'),
        protocol: 'file:',
        slashes: true
    }))
}, 2000);
```

The following video shows the difference clearly:

![panel-red](https://cloud.githubusercontent.com/assets/900690/26779427/9775cdb2-49e5-11e7-9ec3-b8dbfa600c7a.gif)

Could it be that the window `backgroundColor` somehow uses a different color space compared to the renderer one via CSS?

**Comment by javan** [comment]
Does showing the window after `ready-to-show` help? See https://github.com/electron/electron/blob/master/docs/api/browser-window.md#showing-window-gracefully

**Comment by bpasero** [comment]
@javan hard to say because when using that event, the timeout is no longer showing the window early before loading the URL.

Our interest is to show a window as fast as possible so we would not want to use this event. It seems showing the window early works, except for this color inconsistency.

**Comment by hph** [comment]
This bug has also been affecting me for some time. It's trivial to reproduce by creating a window with a `backgroundColor` option and an HTML template with the same background color value in the body (let me know if you need more). I'm using `rgb(0, 43, 54)` and it is rendered as `rgb(0, 57, 69)` (value found using the Mac digital color meter). Any idea what might be causing this?

**Comment by bpasero** [comment]
One thing I was wondering is if the colors we provide in `backgroundColor` are maybe converted to another color system which is not RGB and as such there is a slight color change compared to what was entered?

**Comment by callodacity** [comment]
I'm also encountering this issue: the `BrowserWindow`'s `backgroundColor` is set to `#252526` but actually appears as `#313132`

**Comment by teleclimber** [comment]
I don't use `backgroundColor` but I have noticed that regular CSS colors are not rendered correctly on Mac: #10732. This may account for the visual difference between `backgroundColor` and the CSS color.

**Comment by ianpaschal** [comment]
Also experiencing this issue.

**Comment by sindresorhus** [comment]
I'm still seeing this with Electron 2.0

**Comment by nehbit** [comment]
I've encountered this issue today as well, I thought I was hallucinating for a good amount of time, but it appears it's genuinely different.

**Comment by macsj200** [comment]
@gtinkham Weren't you having this issue?

**Comment by pronebird** [comment]
Perhaps Electron has to use deviceRGB instead of some generic color profile?

**Comment by codebytere** [comment]
This should be fixed on latest versions of Electron.
