### ISSUE TITLE
CSP sandbox directive still allows modals

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#9678]
Setting the `sandbox` CSP directive still allows `alert`, `confirm`, and `window.open` to be called from a `BrowserWindow`.

The `window.open` issue can be addressed by setting `nativeWindowOpen` to `true` which will show proper `Blocked opening URL in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.` errors.

`alert` and `confirm` support can be added by dropping the custom implementations from https://github.com/electron/electron/blob/53b6ee0e3ff3b5abd2f28cd52cc29e4e0d6cb570/lib/renderer/window-setup.js#L132-L138 and using Chrome's default JavaScript dialog manager.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox

**Comment by MarshallOfSound** [comment]
This custom implementations have been dropped a while back and all modals are now routed through `AtomJavascriptDialogManager` (and therefore have the same CSP protections as `nativeWindowOpen`)
