### ISSUE TITLE
BrowserWindow.openDevTools doesn't force show of hidden BrowserWindow if dev tools docked.

### ISSUE THREAD

**Issue by TimNZ** [electron/electron#9680]
* Electron version: 1.7.2
* Operating system: At least Windows

### Expected behavior
browserWindowInstance.openDevTools() on window created with { show: false } forces show of BrowserWindow if devtools are docked.

### Actual behavior
Dev tools window only opened if { show: false} and dev tools has been previously detached

### How to reproduce

If dev tools docked to BrowserWindow, window will not show on openDevTools()
If dev tools detached from BrowserWindow, DevTools window will show if BrowserWindow instance hidden. 

This was confusing the hell out of me as DevTools window was popping up on my Mac, but just a co-incidence that I had previously detached.

```
const {BrowserWindow,app} = require('electron');

app.on('ready',() => {
let browserWindow = new BrowserWindow({show:false});
browserWindow.loadURL('https://www.xero.com');
browserWindow.openDevTools(); // Won't show if docked

});
```

**Comment by MarshallOfSound** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so I'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
