### ISSUE TITLE
Touch isn't working on a specific Surface Book 

### ISSUE THREAD

**Issue by juturu** [electron/electron#9683]
* Electron version: 1.6.x or 1.7.x
* Operating system: Windows 10

### Expected behavior
Using touch, user should be able to interact.

### Actual behavior
Touch doesn't work on a Surface Book. This is happening only on one surface book and not all of them.
This issue is not repro'ing on chrome on the same Surface book.

### How to reproduce

On a surface book, launch Electron 1.7.2 or 1.6.10. Touch doesn't work. I have a surface book which is exhibiting this behavior.
Can you point me in a direction to debug this issue further? Any logs i can capture to see what is going on? Any command line args which can be passed to chromium to get touch traces?

**Comment by Augus** [comment]
+1

**Comment by MarshallOfSound** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so I'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
