### ISSUE TITLE
Protocol: Unexpected literal in error position of callback

### ISSUE THREAD

**Issue by Zyles** [electron/electron#9685]
https://electron.atom.io/docs/api/protocol/

* Electron version: 1.7.2
* Operating system: Win 10

### Expected behavior

No errors.

### Actual behavior

Errors: 

````
 https://google.com/#q=standard%2Fno-callback-literal  Unexpected literal in error position of callback
    src\main\index.js:48:5
        callback({path: path.normalize(`${__dirname}/${url}`)})
`````

### How to reproduce

Do exactly like the docs.

**Comment by MarshallOfSound** [comment]
@Zyles That is a `standard` linting error as callback's in a node.js world typically are of the format

```js
callback(error, result)
```

In this API's case it is simply

```js
callback(result)
```

and standard doesn't like it, you should either add an exception or disable that rule.  This isn't an error with Electron 👍

**Comment by disarticulate** [comment]
Incase anyone can't figure out how to ignore this:
```
  // h5p library makes ajax requests, in production, use a custom protocol
  protocol.registerFileProtocol('h5p', (request, callback) => {
    const url = request.url.substr(7)
    // eslint-disable-next-line
    callback({ path: path.normalize(`${url}`) })
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })
```
