### ISSUE TITLE
In windows multiple monitor setup with different DPIs, electron app starts out of bounds

### ISSUE THREAD

**Issue by juturu** [electron/electron#9688]
* Electron version: 1.6.8 or 1.7.1
* Operating system: Windows

### Expected behavior
In windows multiple monitor setup with different DPIs, electron app starts out of bounds

### Actual behavior
Should start at the same place where app was last opened

### How to reproduce
1. Have two monitors with 200% and 100% DPI
2. Start electron app and move the app to monitor with 100% DPI (non maximized)
3. Quit and Restart the app

App starts out of the bounds in the 100% DPI monitor.

This is a regression after #8786 . I reverted this change and this issue no longer repros.

**Comment by KagamiChan** [comment]
Seems similar to #9560

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/electron/electron/issues/9560
