### ISSUE TITLE
Can't register custom protocol

### ISSUE THREAD

**Issue by Zyles** [electron/electron#9690]
Okay after hours of work I got my last issue solved with your custom callback error on eslint.

Now to the second issue. How do I get this protocol to actually work?

I used the sample code from the docs: https://electron.atom.io/docs/api/protocol/

I can not access atom:// in Google Chrome when my app is running. I also tried registerHttpProtocol, but same problem. Is this normal? Do I need to access this url from inside the app itself?

I am using this in a ouath2 redirect fashion.

If I put a console.log() inside the function it never echoes, but neither does the error.

I tried to search the registry and I couldn't find an entry there either.

If I use it with mainWindow.loadURL(), the console.log() DOES echo but it returns to a blank page.

* Electron version: 1.7.2
* Operating system: Win 10

### Expected behavior

Register new protocol, registry changes, access through browser

### Actual behavior

Nada.

### How to reproduce

Use docs code.

**Comment by enlight** [comment]
The docs you link describe the in-app protocol module, so no you can't use that one in Chrome. If you want to register a protocol/scheme with the OS so other apps can redirect those URLs to your app you need to use [app.registerAsDefaultProtocolClient](https://electron.atom.io/docs/api/app/#appsetasdefaultprotocolclientprotocol-path-args-macos-windows) there's a demo of this functionality in the Electron API Demos app.

**Comment by goldylucks** [comment]
@enlight can you point me to the demo? I can't seem to find it, and this isn't working for me on linux. Thanks.

**Comment by quangnotes** [comment]
@Zyles Do you have the solution for this issue? thanks

**Comment by quangnotes** [comment]
after hours of work, I use this event app.on("open-url")
it works for mac os, but doesn't work for window :=))
