### ISSUE TITLE
Wrong BrowserWindow size on Hi-dpi devices

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#9691]
* Electron version: 1.6.10
* Operating system: Windows 10 (System scaling factor is 2.5)

### Expected behavior

Create a BrowserWindow and the BrowserWindow's size is the same of option.

### Actual behavior

The created BrowserWindow's size is larger than the option

### How to reproduce

Just create a BrowserWindow as below.

Seems only happens on devices that doesn't have an integer scaling factor.

![image](https://user-images.githubusercontent.com/8194131/26865110-d487d296-4b8d-11e7-8469-8a4949588201.png)

**Comment by alexdevero** [comment]
I can confirm this issue in Atom editor v1.19.0-beta0, built with electron, on Windows 10 (64bit, 1703), scaling factor 1.25.

**Comment by MarshallOfSound** [comment]
Duplciate https://github.com/electron/electron/issues/9560
