### ISSUE TITLE
window.open is opening link in default browser

### ISSUE THREAD

**Issue by RamanKharchee** [electron/electron#9692]
I have one problem. Currently i am running my application on localhost in chrome/mozilla/IE. In my application i have one js file that i get the link from the server and then i call window.open to open that link in new tab, And now i have written one main.js to run my application on electron. It starts completely good, but when it comes to window.open it opens it in my chrome browser not in electron app. I want to open it in electron app as a new Browser window or as an tab. But not in the same page. How to achieve it?

and this is my main.js where i have mentioned about open in new browser window

function(module, exports, __webpack_require__) {

‘use strict’;
 
 Object.defineProperty(exports, “__esModule”, {
 value: true
 });
 
 var _electron = __webpack_require__(14);
 
 function initContextMenu(mainWindow) {
 _electron.ipcMain.on(‘contextMenuOpened’, function (event, targetHref) {
 var contextMenuTemplate = [{
 label: ‘Open in default browser’,
 click: function click() {
 if (targetHref) {
 _electron.shell.openExternal(targetHref);
 return;
 }
 }
 }, {
 label: ‘Open in new window’,
 click: function click() {
 if (targetHref) {
 new _electron.BrowserWindow().loadURL(targetHref);
 return;
 }
 
 mainWindow.useDefaultWindowBehaviour = true;
 mainWindow.webContents.send(‘contextMenuClosed’);
 }
 }];
 
 var contextMenu = _electron.Menu.buildFromTemplate(contextMenuTemplate);
 contextMenu.popup(mainWindow);
 mainWindow.contextMenuOpen = true;
 });
 }
 
 exports.default = initContextMenu;

/***/ }

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW, by default `window.open()` in Electron will not open Chrome, so something in your code must be calling `shell.openExternal()`.

**Comment by RamanKharchee** [comment]
Thank You @enlight Ok i will use community or the slack channel. 
But before that i want know that shell.openExternal( ) i will have to add in main.js of electron. And window.open in my applications js file should be kept as it is?
