### ISSUE TITLE
max_old_space_size doesn't work when running electron as node

### ISSUE THREAD

**Issue by jrieken** [electron/electron#9693]
* Electron version: 1.6.10

### Expected behavior

I expect `--max_old_space_size` to work when electron is run as node. This was initially discussed [here](https://github.com/electron/electron/issues/2056#issuecomment-306565476) (Sorry for the double post in case you follow-up on comments in closed issues)

### How to reproduce

* Have a program that keeps allocating memory (see below, save it as `big.js`)
* Run it via `./node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --js-flags="--max_old_space_size=128" ~/Desktop/big.js` and see that the last message is `heapTotal: 139`
* Now run as node via `env ELECTRON_RUN_AS_NODE=true ./node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --max_old_space_size=128 ~/Desktop/big.js` and see that the last message is `heapTotal: 1504`
* :bug: The `max_old_space_size`-flag has no effect when running as node, the limit is always ~1.5GB and cannot be lowered nor increased. 

```js
let all = [];
let big = [];
all.push(big);
for (let i = 0; i < 1000000000; i++) {
    let newLen = big.push(Math.random());
    if (newLen % 500000 === 0) {
        big = [];
        all.push(big);
        console.log('all.length: ' + all.length);
        console.log('heapTotal: ' + Math.round(process.memoryUsage().heapTotal / 1e6));
    }
}

console.log(all.length);

```

**Comment by kikill95** [comment]
I have the same issues, too
`app.commandLine.appendSwitch('js-flags', '--max-old-space-size 8192')`
didn't work as well

**Comment by kikill95** [comment]
Thank you for comment, @ckerr 
For my case electronVersion is 2.0.0-beta.7

For reproducing this I believe you can use code provided by @jrieken

**Comment by codebytere** [comment]
@kikill95 this issue is still occurring, please track https://github.com/electron/electron/issues/12695 for details

**Comment by codebytere** [comment]
Electron doesn't accept `NODE_OPTIONS`, so i'm going to close this out but we may work to address this at a future time.
