### ISSUE TITLE
--inspect does not seem to work in forked processes

### ISSUE THREAD

**Issue by bpasero** [electron/electron#9696]
* Electron version: 1.7.2
* Operating system: macOS 10.12.5

### Expected behavior

Forked processes can be started with `--inspect` or `--inspect-brk` for debugging them.

### Actual behavior

This option does not seem to have any impact.

### How to reproduce

* `git clone https://github.com/bpasero/electron-inspect.git`
* `npm install`
* `./node_modules/.bin/electron .`

=> we fork the process in https://github.com/bpasero/electron-inspect/blob/master/fork.js#L3
=> you see a file `tempXYZ` appearing which means `script.js` was executed
=> this is unexpected because `fork.js` was forked with `--inspect-brk`

**Comment by bpasero** [comment]
@kevinsawicki sorry, my sample was not using Electron 1.7.x, I pushed a fix for that. 

Btw this is much easier to reproduce actually with bare Electron:
* `./Electron --inspect-brk`
=> this will print output that debugger is listening
=> this does not open the window because of `debug-brk`
* `export ELECTRON_RUN_AS_NODE=true`
* `./Electron --inspect-brk`
=> this shows an error where app.js is trying to be executed which prooves that inspect does not work for node in electron

**Comment by bpasero** [comment]
@kevinsawicki @deepak1556 have you had a chance to investigate the root cause of this? I assume some node-debug related initialisation code is simply not triggered when running Electron's node environment directly?

**Comment by kevinsawicki** [comment]
> have you had a chance to investigate the root cause of this? 

Not yet, but it probably needs to be wired up in https://github.com/electron/electron/blob/a6ea316a5de1964761a82d9376c23e99eff16d25/atom/common/node_bindings.cc#L151

**Comment by bpasero** [comment]
@kevinsawicki thanks, looking forward to the 1.7.4 release :)
