### ISSUE TITLE
Promisify Electron APIs

### ISSUE THREAD

**Issue by j-f1** [electron/electron#9697]
* Electron version: N/A
* Operating system: N/A

### Expected behavior

```js
// or any other async API
win.webContents.getZoomFactor().then(factor => {
 // ...
})
// This should also work:
win.webContents.getZoomFactor(factor => {
  // ...
})
```

### Actual behavior

The `Promise`-based one fails to execute, but the callback-based one works.

### How to reproduce

N/A

**Comment by zeke** [comment]
Other promise-related issues: https://github.com/electron/electron/issues/9561, https://github.com/electron/electron/issues/7532

**Comment by zeke** [comment]
See also https://github.com/electron/electron/issues/9882

**Comment by miniak** [comment]
Closing this out as the Promisification effort has been completed. 🎉 

Huge shoutout to all involved in the conversions escpecially @codebytere who did a decent amount of the conversion work.

Refs: https://github.com/electron/electron/blob/master/docs/api/modernization/promisification.md

**Comment by zeke** [comment]
Thank you @codebytere! ✨
