### ISSUE TITLE
unable to copy paste cut selectall on MAC in  Production Environment

### ISSUE THREAD

**Issue by isNeilLin** [electron/electron#9698]
In development  Environment  track 'copy', 'paste','cut' event is ok, in   Production Environment couldn't track 'copy', 'paste','cut' event . and unable to copy paste cut selectall on MAC, on windows is ok.  my electron version is 1.4.13

**Comment by codebytere** [comment]
We no longer activelt support bugfixes for `1.4.x` so i'm going to go ahead and close this, but if you see it recur on newer versions of Electron we can certainly reopen it.

**Comment by alexcroox** [comment]
@isNeilLin @codebytere this bug exists in every version of electron. Unfortunately your app has to have menu items in order for copy/paste/cut/select all functionality to work in inputs.

https://github.com/electron/electron/blob/master/docs/api/menu.md
