### ISSUE TITLE
Electron window handler didn't work with Unity on win10

### ISSUE THREAD

**Issue by Lordkodo** [electron/electron#9701]
Hello guys

I try to launch an unity exe in an electron window.

For that:
- I get my window handler ID with `win.getNativeWindowHandle()` from [electron](https://electron.atom.io/docs/api/browser-window/#wingetnativewindowhandle).
- I launch my unity exe with : `./unity/Child.exe  -parentHWND {window_handler_id} delayed` from [unity doc](https://docs.unity3d.com/Manual/CommandLineArguments.html).
- On win7 and win8 my window display the unity application, but with win10 I get a blinking window who sometime display my unity exe.

If I launch my unity exe on another window, Firefox for example, it works. But not on Slack or Atom (electron apps).

Do you got an idea ?

**Comment by chenmeng71** [comment]
I'm also having the same problem with getNativeWindowHandle() on Windows 10.  I have an app that runs as Electron add-on, takes the window handle returned by getNativeWindowHandle() and renders into it.  This worked on macOS, Windows 7, 8, but not on Windows 10.  

Some debug info: the output of getNativeWindowHandle() on Windows 10 looks like this: aa054f0000000000 (little endian), and it translates to a pointer value of 0x00000000004F05AA, which looks way smaller than what it should be.

**Comment by chenmeng71** [comment]
It turns out the windows handle is actually valid at 3 bytes, as it is not actually a pointer I guess.  However the "dwExStyle" of WINDOWINFO from this handle contains a value of "0x20000900", which doesn't match to combination of defined WS_EX_... extended window styles.  That is still curious.

**Comment by chenmeng71** [comment]
I figured out what's happening with my app.  Not sure if it applies to the unity app, but it's certainly a possibility.  What happened is on Windows 7&8, after you call CreateWinowEx() and ShowWindow() to create a child window with Electron browser window as the parent, the child window automatically comes on top; but on Windows 10, that's not the case.  On Windows 10, the child window doesn't actually show until a call to SetWindowPos(hwnd, HWND_TOP, ...).  Now the bizarre value of dwExStyle on the Electron browser window as I mentioned above is still curious, but it doesn't seem to actually affect anything.

**Comment by sofianguy** [comment]
@Lordkodo if @chenmeng71's suggestions do not solve your issue, check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

**Comment by MrAndrewMal** [comment]
@chenmeng71 Hi, have you sample with Unity and Electron, pls?
