### ISSUE TITLE
registerURLSchemeAsPrivileged does not allow service worker to use file:// scheme

### ISSUE THREAD

**Issue by leshow** [electron/electron#9705]
* Electron version: 1.6.10 ia32
* Operating system: windows 7 x64

### Expected behavior
create-react-app comes with a service worker by default that uses the fetch API to cache and load resources. I'm expecting `webFrame.registerURLSchemeAsPrivileged('file');` to allow the fetch to load with the file scheme.

### Actual behavior
When fetch is used inside of Electron from the service worker the original error is:
```
Fetch API cannot load file://.... URL scheme "file" is not supported"
```
According to,
https://github.com/electron/electron/issues/2831
https://github.com/electron/electron/issues/9474

 "You can add fetch support to file scheme in your app by using webFrame.registerURLSchemeAsPrivileged api."

So I attempted `webFrame.registerURLSchemeAsPrivileged('file');` 

Which changes the error to:

`Uncaught (in promise) TypeError: Request scheme 'file' is unsupported at service-worker.js:1`

**Comment by marcusdb** [comment]
+1

**Comment by pfrazee** [comment]
This may be related to https://github.com/electron/electron/issues/9663

**Comment by deepak1556** [comment]
@leshow we already have a spec that tests for service worker registration with file scheme https://github.com/electron/electron/blob/master/spec/chromium-spec.js#L122. Can you provide a minimal example ? thanks!

**Comment by RIAEvangelist** [comment]
a simple fetch call from a serviceworker to any file on your system will repro.

**Comment by rafalradomski** [comment]
+1

electron: 1.7.8
mac: macOS Sierra 10.12.6

**Comment by hosseinsalemi** [comment]
+1

electron 1.7.9
mac: sierra 10.12.6

**Comment by Shawson** [comment]
+1

electron: 1.7.8
pc: win 10

**Comment by kosekmi** [comment]
+1

electron: 1.6.15
pc: ubuntu 16.04 4.4.0-97-generi

**Comment by XavierLeTohic** [comment]
+1

electron: 1.7.9
pc: Windows 10

**Comment by builden** [comment]
+1

electron: 1.7.6
pc: Windows 7

**Comment by ChristianWeyer** [comment]
Do we have any update on this issue? It still bites us (currently using 1.8.6) .cc @deepak1556 
Thanks!

**Comment by fengzhongye** [comment]
i have the same issue with 1.8.6

**Comment by codebytere** [comment]
Does this occur on `2.0.0`?

**Comment by pfrazee** [comment]
@codebytere I just checked my test case for https://github.com/electron/electron/issues/9663 and it's still failing

**Comment by leshow** [comment]
Any updates on this one? @pfrazee has a reproducible test case:
```
git clone https://github.com/pfrazee/electron-bug-service-workers-failure
cd electron-bug-service-workers-failure
npm i
npm start
```
from https://github.com/electron/electron/issues/9663

So can we remove the `blocked` tag on this issue?

**Comment by mraible** [comment]
It fails for me with 2.0.2. I'm guessing the workaround is to comment out `registerServiceWorker()` in `src/index.js`?

**Comment by leshow** [comment]
@mraible If you disable `registerServiceWorker` (assuming you're using CRA) then you just aren't using service workers, it's not really a workaround.

**Comment by mhuggins** [comment]
electron: 2.0.0
os: macOS High Sierra 10.13.3 (17D102)

**Comment by DalderupMaurice** [comment]
Electron: 2.0.0
Windows 10 64-bits Pro
@codebytere @deepak1556 Could the `blocked` label be removed? There's a reproducible git repo up here in the comments

**Comment by voicebooth** [comment]
Electron: 2.0.5
Windows 10 Pro

After spending all evening looking at around posts, trying as many different hacky things as I can, I've come to realise that I'm suffering from the same problem in #13740 as is reported in here - the CRA service worker uses fetch(), which is throwing up the error mentioned at the beginning of this issue:

`Uncaught (in promise) TypeError: Request scheme 'file' is unsupported at service-worker.js:1`

I am unsure if it's possible to run the latest React without the service workers, but I'm guessing this issue will affect all React applications trying to run in Electron?

**Comment by voicebooth** [comment]
I have been experimenting a bit further this evening by upgrading to electron 3.0.0-beta.3 to see if this might have fixed the problem, with the upgrade of chromium from 61 to 66, but the problem still persists.

Something I find a bit curious is that although the CRA application I have doesn't render, and throws the Request scheme 'file' is unsupposed at service-worker.js like so:

![image](https://i.imgur.com/YJ4v6Wr.png)

The actual files it's trying to load are all loading fine, with HTTP 200, all coming from file:// protocol

![image](https://i.imgur.com/CsRTuM5.png)

And the content in those files is loading perfectly fine:

![image](https://i.imgur.com/2adRWjJ.png)

So I'm unsure why this error is coming up when fetch() is being called.

**Comment by leshow** [comment]
> I am unsure if it's possible to run the latest React without the service workers, but I'm guessing this issue will affect all React applications trying to run in Electron 

You can absolutely run react without service workers. React and create-react-app are separate projects, and service workers in CRA is optional. If you are using CRA & Electron, you just need to remove the service worker import, assuming you can live without service workers.

So far as I can tell, the issue is that the file protocol isn't supported in service workers, at least not using the fetch API.

**Comment by WesWedding** [comment]
This issue persists in the latest electron versions.  Other important Service Worker APIs appear to have not worked for years, too, such as Background Sync.

**Comment by whitemiaool** [comment]
+1
electron v7.1.14

**Comment by Jaifroid** [comment]
Issue still persists in electron v9.0.5. 😒

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by hieu-ht** [comment]
Issue still persists in electron v18.3.0.
