### ISSUE TITLE
Only the first letter will be alphabetic when input Japanese. (using Japanese IME)

### ISSUE THREAD

**Issue by Kurom96** [electron/electron#9709]
* Electron version: 1.7.2
* Operating system: mac OSX El Capitan 10.11.6
* Node version: 4.4.7, 7.2.1, 7.9.0

### Expected behavior
We should be able to input Japanese in text-input on webview, using the Japanese IME to convert alphabets to Japanese.

### Actual behavior
Immediately after application focus, and start typing Japanese input.
Only the first letter will be alphabetic.

### How to reproduce
```
$ git clone https://github.com/Kurom96/electron-quick-start.git -b  japanese-input-bug
$ cd electron-quick-start
$ npm i
$ npm start
```

See bellow.

![japanese-input-bug](https://user-images.githubusercontent.com/1531679/26962289-230ba364-4d20-11e7-9096-856d1d042432.gif)

### Others
* It does not occur under 1.7.1
* Is this fix affected? #9173

**Comment by kevinsawicki** [comment]
@Kurom96 can you test the latest 1.6.x release as well?

**Comment by Kurom96** [comment]
@kevinsawicki I tested it in 1.6.10, but this issue did not occur.

**Comment by kevinsawicki** [comment]
> I tested it in 1.6.10, but this issue did not occur.

@Kurom96 thanks, can you try 1.6.11 as well? It contains the same patch from #9173

**Comment by Kurom96** [comment]
@kevinsawicki It did not occur in 1.6.11 either.

**Comment by kevinsawicki** [comment]
Commented at https://bugs.chromium.org/p/chromium/issues/detail?id=714771#c23 asking for help from the Chrome team on this one.

**Comment by kevinsawicki** [comment]
Looks like https://codereview.chromium.org/2929543002/ may address this, needs verification though.
