### ISSUE TITLE
anyone meet this?

### ISSUE THREAD

**Issue by jinggk** [electron/electron#9710]
I am doing a project,  use  electron to do a desktop application, when I use the  nodejs fs.createWriteStream in the main process to download the file, if the program installed in the windows C drive, there will be the following mistakes, Have you met? Can you know how to avoid this problem?

![sqh ro 5c5 zx4infy ite](https://user-images.githubusercontent.com/21035344/26963554-ba1d8d5e-4d1f-11e7-82ab-1110349c0aae.png)

here is my code:
![u9y e4 4u 7 8d3grw7j_w](https://user-images.githubusercontent.com/21035344/26963611-099ddb68-4d20-11e7-8162-9cd51e424342.png)

I used chmod 777 to try to modify the file permissions, but did not work, i do not know why

**Comment by jinggk** [comment]
![g j n c axcayh1s ybnx](https://user-images.githubusercontent.com/21035344/26963655-56f77cf2-4d20-11e7-955a-7d39abb04762.png)
 and  this

**Comment by enlight** [comment]
I'm guessing you're attempting to write the file to your application installation directory, as you can see Windows doesn't like that. You should write the files to one of the location returned by [`app.getPath()`](https://electron.atom.io/docs/api/app/#appgetpathname).

**Comment by jinggk** [comment]
@enlight yes, i have try , but it did not work, It seems like I do not allow the file to download to the c disk, how should I modify the file download permissions?
