### ISSUE TITLE
Add callback to webContent.print

### ISSUE THREAD

**Issue by tim37021** [electron/electron#9712]
* Electron version: 1.6
* Operating system: Windows 10

webContent.printToPDF does have callback so that we are notified when finishing. I wish electron adding callback to webContent.print as well.

**Comment by askie** [comment]
+1

**Comment by ziedhajsalah** [comment]
+1 and
https://stackoverflow.com/questions/44500382/close-window-after-printing-electron

**Comment by renaesop** [comment]
In fact, it's not so easy to add a callback option.

**Comment by renaesop** [comment]
#10081

**Comment by renaesop** [comment]
#10081 May help

**Comment by alaj** [comment]
+1
I need it too...

**Comment by tim37021** [comment]
I seems there're many other like me need this feature.
it might not be easy to make it portable. print is an os-relative operation.

**Comment by codebytere** [comment]
This is merged, so i'm going to go ahead and close it!

**Comment by Sharcoux** [comment]
@codebytere What is merged exactly? What is the solution to this problem?
