### ISSUE TITLE
document.visibilityState is hidden in <webview>s when BrowserWindow shown on ready-to-show

### ISSUE THREAD

**Issue by javan** [electron/electron#9717]
* Electron version: 1.7.3
* Operating system: macOS 10.12.5

When a `BrowserWindow` is created with `{show: false}` and then `show`n on `ready-to-show`, its `<webview>`s will (incorrectly?) have a `document.visibilityState` of `hidden`.  Prior to https://github.com/electron/electron/pull/9178 (cc: @poiru), it would be `visible`. 

Here's a little example app: https://gist.github.com/javan/f1f5257044bfdf6f3dae47ccc2f57be4

![screen shot 2017-06-09 at 9 36 25 am](https://user-images.githubusercontent.com/5355/26977748-fa554d5e-4cf6-11e7-89d4-633969f5ac12.png)

Showing the window on `dom-ready` works and the `visibilityState` is `visible`.
```js
mainWindow.webContents.on('dom-ready', function() {
  mainWindow.show()
})
```

**Comment by kevinsawicki** [comment]
> Prior to #9178 (cc: @poiru), it would be visible.

@javan I'm definitely able to reproduce this on 1.7.3, but the behavior seems the same in 1.7.2 as well, are you not seeing this issue on releases before 1.7.3?

**Comment by javan** [comment]
@kevinsawicki, you're right. I noticed it going from 1.7.2 to 1.7.3 in the Basecamp app, which more-or-less does what the example app I gisted does. The Basecamp app does significantly more setup work though so I suspect the actual events are a red herring and the issue is instead timing related.

**Comment by javan** [comment]
Thank you!
