### ISSUE TITLE
how to pass param by shell.openItem 

### ISSUE THREAD

**Issue by crylg** [electron/electron#9718]
Invalid:
shell.openItem("d:\abc.exe arg1 arg2 arg3")
callback echo "false"

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW that isn't the intended use of that API.  To launch an exe file with arguments you should use the `spawn` API for the node.js `child_process` module.
