### ISSUE TITLE
Short blocking operations in main process freeze CSS animations in all renderer processes

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#9719]
* Electron version: 1.6.x, 1.7.x
* Operating system: macOS 10.12.5, Windows 10

### Expected behavior

Doing blocking (10ms or higher) node operations in main process or in renderer process shouldn't freeze CSS animations in an entirely different BrowserWindow/renderer processes (that only contains HTML/CSS, no JS/node, but has `noteIntegration: true`).

### Actual behavior

Long *blocking* node operations (from 10ms to higher) in the main process or in a renderer process will freeze CSS animations in ALL renderer processes.

### How to reproduce

1. Create one BrowserWindow with `nodeIntegration: true`, and rotate a green square div using CSS animation.
2. In main process or a different BrowserWindow, do anything that is blocking.
3. Even if nothing is happening in the BrowserWindow with the animation (pure html/css, no JS), the square rotating animation will be jerky when the blocking operation is happening in the main process or other renderer.

This is pretty annoying because even extremely small blocking operations will still make a fluid animation (like a infinite rotating loader) jerky.

Also, doing the same operation in another BrowserWindow will have the same effect (I'm assuming all node operations, in main or renderer process, are all in the same node thread?).

**Comment by pfrazee** [comment]
@romaincointepas Could you make a demo repo by cloning https://github.com/electron/electron-quick-start ? That would help narrow down the test case. There are some operations in the renderer threads (the BrowserWindow) which make synchronous IPC calls to the main thread, and that can cause blocking in the main thread to block the renderer thread. We'd want to make sure that's not the culprit first.

**Comment by romaincointepas** [comment]
@pfrazee https://github.com/romaincointepas/electron-quick-start/tree/9719

**Comment by pfrazee** [comment]
@romaincointepas Thanks. Someone on the electron team will triage this soon.

**Comment by rogeru** [comment]
@romaincointepas you make it sound like its related to `nodeIntegration: true`, but we see the same problem also with `nodeIntegration: false`.

Also this is not limited to CSS animations. The whole DOM is blocked.

For example writing text to a div. I added the following to your example in index.html:

`
  <div id="text"></div>

  <script>
    var i = 0;
    setInterval(() => document.getElementById('text').innerText = i++, 100);
  </script>
`

**Comment by vasyl-shumskyi** [comment]
Related https://github.com/electron/electron/issues/11694

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by cberescu** [comment]
Hi, can we reopen this. Electron 3.1.13 has the same issue.

**Comment by nukeop** [comment]
Yep this is still occurring

**Comment by welcome14** [comment]
Hi,
news about this bug?
