### ISSUE TITLE
Layout changes all happen at once after hiding/showing a BrowserWindow

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#9720]
* Electron version: 1.6.x, 1.7.x
* Operating system: macOS 10.12.5, Windows 10

### Expected behavior

A way to update the layout of a hidden window (that has been shown in the past, then was hidden) while it is hidden.

### Actual behavior

All layout changes applied while the window was hidden are all applied at once when showing the window again (and it's visible).

Setting `backgroundThrottling: false` as `webPreferences` for that window doesn't solve the problem.

### How to reproduce

1. Show a BrowserWindow with the current time in seconds that updates itself every 1 second.
2. Hide the window for a few seconds.
3. Show the window again, the time that was shown when the window was hidden will still be visible for a few milliseconds, then will be replaced by the "current" one. Same thing applies to any HTML/CSS changes (from element width/height, to background color, etc.).

**Comment by joshaber** [comment]
We battled with this for GitHub Desktop and didn't find an obviously workaround: https://github.com/desktop/desktop/pull/1416

**Comment by romaincointepas** [comment]
@joshaber Oh. Would it make sense/be possible to have a `webContents` method to *force* a visual DOM update manually, or does chromium expose a way of disabling this optimization somehow?

**Comment by joshaber** [comment]
@romaincointepas I think it'd make sense but how to go about that is an open question 😄 

I spent a little time seeing if we could use the same mechanism the `ready-to-show` event uses, but that didn't seem to have any effect. I'd guess it'll take some spelunking to figure out exactly what Chromium is doing and how to work around it.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by citrusjunoss** [comment]
Finally, how is this problem solved? 
I tried the method  `requestIdleCallback`  suggested by github,  But it does not seem to take effect 。 
![image](https://user-images.githubusercontent.com/18432488/50323300-fb4a9f80-0513-11e9-8234-5cd3a7168b5a.png)
