### ISSUE TITLE
Browser Tabs for <Webview>

### ISSUE THREAD

**Issue by Valder-Dev** [electron/electron#9722]
- **Electron version:** 1.4.13.
- **Operating System:** Windows 7.

### Question:
How create Browser Tabs as in the Google Hrome or Firefox?

**PS:** Thanks for a help.

![image](https://user-images.githubusercontent.com/28824836/27000892-911c60ea-4e07-11e7-839f-45156a3bba5a.png)
![image](https://user-images.githubusercontent.com/28824836/27000897-b01956b0-4e07-11e7-9cf3-17abd0620714.png)

**Comment by MarshallOfSound** [comment]
Electron is not a browser, if you want the tab UI that browsers have you will need to implement it yourself in HTML / CSS

**Comment by MarshallOfSound** [comment]
Their are third party modules that give you a good start on this kind of UI

**Comment by bsclifton** [comment]
@Valder-Dev for an example app which is based on Electron, see [Brave](https://github.com/brave/browser-laptop). This interface has multiple tabs and all the other browser components you may expect
