### ISSUE TITLE
ReferenceError on accessing local variable within executeJavaScript

### ISSUE THREAD

**Issue by yrahul3910** [electron/electron#9723]
I'm trying to access a variable from a function that's called in `webContents.executeJavaScript`, but I get a `ReferenceError` on trying. I use jQuery for event handling. Here's some sample code to replicate the issue.
```
let var;

const menuClick = () => {
  var = 5;
  let html = "<div id='1'><p>Some test paragraph</p></div>";
  win.webContents.executeJavaScript(`
    $("#list").append("${html}");
    $('div').click(${onDivClicked});
  `);
}

const onDivClicked = (e) => {
  console.log(var);
}
```
I expect it to show 5, but it gives me a `ReferenceError` instead. Any ideas on how to fix this?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW what you are trying to do simply isn't possible the way you are trying to do it, passing functions as a string removes all context from that function so "var" will not be accessible when that function is recreated as a string in the renderer process.  You need to use IPC to send the click event back to the main process
