### ISSUE TITLE
Tray's context menu is cut when changing resolution 

### ISSUE THREAD

**Issue by shaniAlgazi** [electron/electron#9726]
* Electron version: 1.4.13
* Operating system: Windows 10

Hey guys, 

I'm trying to add a context menu to my tray app: 

        this._tray.setContextMenu(this._contextMenu);

It's working just fine until i'm pulling my laptop out of the docking station (that has 2 screens) and open it - this causes a change in the resolution and when then trying to click again on the tray from my laptop it looks like this : 

![image](https://user-images.githubusercontent.com/25342044/27010427-c1e3cbe6-4eac-11e7-9aea-b89d7930733f.png)

I also tried : 
tray.popUpContextMenu
with the position of the current screen, but getDisplayMatching() and getPrimaryDisplay() keeps giving me the position of the docking screens.

**Comment by codebytere** [comment]
We no longer actively support bugfixes for `1.4.x` so i'm going to go ahead and close this, but if you see it recur on newer versions of Electron we can certainly reopen it.
