### ISSUE TITLE
Add the ability to completely hide the menu bar.

### ISSUE THREAD

**Issue by giuscri** [electron/electron#9728]
* Electron version: N/A
* Operating system: N/A

### Expected behavior

If properly instructed, pressing Alt should *not* show the menu bar.

### Actual behavior
It seems like there's no way to disable the listener showing the menu bar.

### How to reproduce
N/A

**Comment by miniak** [comment]
Please re-open if this is still an issue in Electron >= 3 with the appropriate "Bug report" or "Feature request" template filled out.
