### ISSUE TITLE
Windows 7: Window restores improperly after snap and minimize

### ISSUE THREAD

**Issue by bpasero** [electron/electron#9729]
* Electron version: 3.0.0
* Operating system: Windows 7

### Expected behavior

A windows restores to its previous bounds and location after restoring from being minimized.

### Actual behavior

The window restores in the center with some kind of default bounds.

### How to reproduce

* run simple Electron out of the box
* maximize the window
* press Windows-ArrowRight to snap the window to the right
* minimize the window
* restore the window

=> bounds are not the same as before

This seems to work fine on Windows 10

![panel-red](https://user-images.githubusercontent.com/900690/27018769-25ad4fa4-4f33-11e7-8815-8fff23bbe80e.gif)

**Comment by sofianguy** [comment]
@bpasero is this bug still happening in version 4.2.x or later?

**Comment by bpasero** [comment]
I no longer have a Windows 7 VM, sorry.

**Comment by sofianguy** [comment]
No worries, I will close this for now but happy to reopen if new information comes up
