### ISSUE TITLE
"moved" triggering every time when screen resolution was changed

### ISSUE THREAD

**Issue by igogo5yo** [electron/electron#9731]
* Electron version: 1.6.2, 1.6.10
* Operating system: macOS 10.12.5

### Expected behavior

When resolution was changed 'display-metrics-changed' event should be triggered first.

 Actual behavior

When resolution was changed 'moved' event was triggered first.

### How to reproduce

Run electron app and then change screen resolution.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
