### ISSUE TITLE
Add command line switch to crashpad service for full memory dump creation

### ISSUE THREAD

**Issue by igorshevach** [electron/electron#9735]
* Electron version: latest
* Operating system: windows 7/8/10

### Expected behavior

crashpad service should allow for specifying creation of a full memory dumps just as google breakpad component is designed for.
when specifying full dump option following should happen:
- minimal (PEB+TEB) dump will be uploaded to submit url (existing behavior)
- there will be created full memory dump in the the dump folder.
### Actual behavior

application passes minimal dump (PEB+TEB) flags to crashpad service
### How to reproduce

this functionality is not yet available

Pull request containing the fix can be found at:
https://github.com/electron/electron/pull/9734

IMPORTANT:
currently used version of breakpad src (33a4375) does not contain necessary fixes. therefore for pull request to work breakpad src must be synchronized with master (https://chromium.googlesource.com/breakpad/breakpad/+/7ec3caf6c7cdff0a99cd34249acfdc61f76f2d86)

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
