### ISSUE TITLE
webviewTag is not compatible with contextIsolation

### ISSUE THREAD

**Issue by pwnsdx** [electron/electron#9736]
* Electron version: 1.7.2
* Operating system: macOS Sierra

### Expected behavior

Webview appear

### Actual behavior

It don't

### How to reproduce

1. Create a browser window with contextIsolation on true and webviewTag on true
2. Inside of it, add a webview
3. Run it, webview should not appear

**Comment by hiddentao** [comment]
Just seen this myself.

**Comment by ikkisoft** [comment]
Just tested on 3.0.11. This is still an issue. 

Using
```
....
    webPreferences: {
      nodeIntegration: false, 
      contextIsolation: true,
      webviewTag: true,
```
```<webview>``` does not work.

You know how important _contextIsolation_ is for security, yet issues like this one make it impossible to use it in production. I think this issue should be prioritized.

**Comment by BinaryMuse** [comment]
Thanks for the note, @ikkisoft. We agree with you and have started work on this.

**Comment by juliuswigo** [comment]
Am I the only one who still has this problem?

I tested it with version 3.0.11, 4.0.8 and 5.0.0. The webviews are not working, when contextIsolation is set 'true'
`webPreferences: {
      nodeIntegration: true,
      contextIsolation: true,
      webviewTag: true,
    }`

I think this issue should be reopened.
