### ISSUE TITLE
When application was minimized by click on taskbar icon, some BrowserWindow API is broken

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#9744]
* Electron version:1.6.11
* Operating system: Windows

### Expected behavior
win.isFocused() and win.isVisible() should be false when window is minimized.

### Actual behavior
```
win.isFocused() // true (can be so, but I do not believe that some one expect minimized window to be focused)
win.isVisible() // true
```

### How to reproduce
```
const {app, BrowserWindow} = require('electron')

let mainWindow

app.on('ready', () => {
  mainWindow = new BrowserWindow()
  mainWindow.loadURL('about:blank')

  setTimeout(() => {
    console.log(mainWindow.isFocused(), mainWindow.isVisible());
  }, 10000)
})

app.on('quit', () => {
  app.quit()
})

```

**Comment by cumajkeee** [comment]
win.isVisible() is true even when you minimize app by click on minimize button in window toolbar

**Comment by ouqinglai** [comment]
hi guys~ use document.hasFocus() without win.isFocused()
`ipcRenderer.send("start-remind", document.hasFocus())`
`ipcMain.on("start-remind",function(event, isFocus){
     // use isFocus
})`

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
