### ISSUE TITLE
打包后的exe，如何接收外部程序调用 时，传递的参数

### ISSUE THREAD

**Issue by tkggusraqk** [electron/electron#9746]
electron 程序打包完成后，比如app.exe；需要对接一个第三方程序，在这个第三方程序里启动 app.exe，同时传递 启动参数，比如用c#调用 app.exe：
     Process proc = new Process();
     proc.StartInfo.FileName = startPath;
            proc.StartInfo.Arguments = "-name test";
            proc.Start();
如何在app.exe启动的时候 接收到这些参数 ：-name test

**Comment by pabloleban** [comment]
English please?

**Comment by KagamiChan** [comment]
Please use English

For your question, use [`process.argv`](https://nodejs.org/docs/latest/api/process.html#process_process_argv), you may be interested in packages like `yargs`

**Comment by enlight** [comment]
I'm going to assume this issue has been resolved.

GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by Seventeen0017** [comment]
> electron 程序打包完成后，比如app.exe；需要对接一个第三方程序，在这个第三方程序里启动 app.exe，同时传递 启动参数，比如用c#调用 app.exe： Process proc = new Process(); proc.StartInfo.FileName = startPath; proc.StartInfo.Arguments = "-name test"; proc.Start(); 如何在app.exe启动的时候 接收到这些参数 ：-name test

请问你解决了吗？
