### ISSUE TITLE
Feature request. Add Dragon Web extension for chrome.

### ISSUE THREAD

**Issue by alsoeric** [electron/electron#9748]
Adding the Dragon Web extension for chrome to electron might make NaturallySpeaking work better with electron based apps.

**Comment by alexstrat** [comment]
I don't think the Dragon Web extension should be added by default in electron, that's not the purpose of Electron.

You should rather try to load the extension in your electron-based application via `addDevToolsExtension` as instructed in [there](https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md).
Note though that `addDevToolsExtension` is only supposed to be used in development mode and that the support for Chrome extension is incomplete (see #1498).
