### ISSUE TITLE
Properties of ClearStorageDataOptions interface should not be required

### ISSUE THREAD

**Issue by craxal** [electron/electron#9749]
* Electron version: 1.7.2
* Operating system: Windows 10

### Expected behavior
All properties as defined by the `ClearStorageDataOptions` interface should be optional. When passing an options object to `session.clearStorageData`, I should only have to specify the options I want.

### Actual behavior
All properties as defined by the `ClearStorageDataOptions` interface are declared as required. When passing an options object to `session.clearStorageData`, Typescript requires I define all three properties.

There is an easy workaround. Just insert an `<any>` cast.

### How to reproduce
1. Create a sample Electron project using Typescript.
2. Insert the following code somewhere in the renderer process:
```ts
window.webContents.session.cleareStorageData({ storages: ["cookies"] });
```
3. Compile using `tsc`. Typescript reports an error.

**Comment by craxal** [comment]
That was an incredibly fast response. Thanks!

**Comment by zeke** [comment]
@MarshallOfSound never sleeps.
