### ISSUE TITLE
Electron 1.6.10 is not able to pass App Store verification with sbpl exceptions

### ISSUE THREAD

**Issue by kcampion** [electron/electron#9757]
* Electron version: 1.6.10
* Operating system: macOs 10.12.5

With one of the last version of Electron, I use this on parent.plist to allow Apple Sandbox to execute my application:
```
<key>com.apple.security.temporary-exception.mach-lookup.global-name</key>
<array>
  <string>com.apple.GameController.gamecontrollerd</string>
</array>
<key>com.apple.security.temporary-exception.sbpl</key>
<array>
  <string>(allow mach-lookup (global-name-regex #"^org.chromium.Chromium.rohitfork.[0-9]+$"))</string>
  <string>(allow mach-register (global-name-regex #"^com.electron.mysuperapp.rohitfork.[0-9]+$"))</string>
  <string>(allow mach-lookup (global-name-regex #"^com.electron.mysuperapp.rohitfork.[0-9]+$"))</string>
</array>
```

About **GameController**: I must use this mach-lookup exception with GameController because a Sandbox violation error appears. I don't know why, because I don't use anything for gaming.

About **rohitfork**: It's for Chromium.

The application works well on my computer after signing it, but after 1 day in review, my app was rejected by Apple:
![capture d ecran 2017-06-14 a 16 12 10](https://user-images.githubusercontent.com/507265/27136759-64c0bd94-511c-11e7-9f3e-6f77c2788dbf.png)

Someone has already deployed an Electron app with the last version on the AppStore?

**Comment by getflourish** [comment]
I also found this issue because I’ve seen GameController stuff in my app that definitely doesn’t want to access GameControllers :)

`SandboxViolation: Locally(2927) deny(1) mach-lookup com.apple.GameController.gamecontrollerd`

**Comment by kcampion** [comment]
@getflourish I tried to use `com.apple.security.application-groups`. My app is in review on the AppStore with this update. I'll tell here the answer of Apple.

**Comment by getflourish** [comment]
@kcampion What did you use as value? 

teamID.bundleID?

`M321321312.appname.domain.com` ?

**Comment by steviemo** [comment]
I am getting same issue when trying to run a sandboxed development build on my electron application - why is electron wanting access to com.apple.GameController.gamecontrollerd entitlement?

**Comment by kcampion** [comment]
@getflourish Yes I use this value for `com.apple.security.application-groups`, but better with `TEAMID.com.electron.yourappname`.

@steviemo I'm not sure it's from Electron, but from a package you and I use. What's the version of electron-osx-sign do you use?

**Comment by steviemo** [comment]
Its the version of electron-osx-sign brought in by electron-builder so it's 0.4.6.

Its turns out my app wasn't crashing because of these sandbox violations - it was closing because I had app.makeSingleInstance which as it turns out doesn't work for mas packaged apps.

**Comment by kcampion** [comment]
For the issue with app.makesingleInstance, maybe look here https://github.com/electron-userland/electron-osx-sign/issues/137#issuecomment-307626305

**Comment by steviemo** [comment]
Thanks @kcampion - I came across this :) With your sandboxed mas app did custom protocol registration work for you? When I build a mas app for testing the custom protocol doesn't get registered: for example I register myapp protocol with electron-build but if i enter myapp://test in safari nothing happens. I checked the mas app info.plist and CFBundleURLTypes is correct. Its almost like you need an entitlement to allow this in sandboxed app though don't see any mention in docs

**Comment by kcampion** [comment]
It's another issue @steviemo but I didn't have to use myapp:// for the moment, sorry.

**Comment by kcampion** [comment]
Apple approved my app with `com.apple.security.application-groups`.

My parent.plist looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.temporary-exception.shared-preference.read-only</key>
    <array>
      <string>com.apple.symbolichotkeys</string>
    </array>
    <key>com.apple.security.application-groups</key>
    <array>
      <string>TEAMID.com.electron.myappname</string>
    </array>
  </dict>
</plist>
```

(replace TEAMID and myappname)

**Comment by callodacity** [comment]
So does anyone know exactly why we're getting these SandboxViolations?

```
deny mach-lookup com.apple.GameController.gamecontrollerd
```

**Comment by JeffWinder** [comment]
I'm also getting this violation, does anyone know why?
`deny mach-lookup com.apple.GameController.gamecontrollerd`

**Comment by JeffWinder** [comment]
Ported my nwjs project to Electron and...again these violations when I open my mas signed app.
