### ISSUE TITLE
Reload doesn't work sometimes

### ISSUE THREAD

**Issue by VikasShashidhar** [electron/electron#9758]
* Electron version: 1.6.7
* Operating system: macOS Sierra (10.12.5)

### Expected behavior

When the user does a Cmd+R or reloads the page through context menu, the page should reload.

### Actual behavior

It works most of the time, but not always. Many times when it fails, a blank page appears.

### How to reproduce

Unfortunately, there are no clear repro steps. It happens so randomly that it's hard to identify a clear pattern. Will update this issue if I am able to repro this consistently.

I've observed this on a couple of apps that uses Electron.

**Comment by VikasShashidhar** [comment]
No one else facing this issue?

**Comment by alvesl** [comment]
I did, in my case I think it was related to using React-Router.
To fix it, I overrode the default behavior to call loadURL again, something like:
`mainWindow.loadURL(startUrl);`

**Comment by VikasShashidhar** [comment]
@alvesl Thanks for the input. Let me try that.

**Comment by shubham2892** [comment]
@VikasShashidhar Did that work for you?

**Comment by sofianguy** [comment]
Closing due to abandonment. We will gladly reopen if this is still an issue.
