### ISSUE TITLE
Storage Info API

### ISSUE THREAD

**Issue by YurySolovyov** [electron/electron#9759]
It would be nice to have an API to:
- enumerate logical drives (hard discs, flash drives)
- get basic info about state (label, free/used space)
- ability to get notified when new drive is added/mounted

If Chromuim has anything like that, please point me to the code, I might be able to port it, but I can't promise anything.

**Comment by KagamiChan** [comment]
How about using node packages like this one: https://github.com/sebhildebrandt/systeminformation

**Comment by YurySolovyov** [comment]
The downside is that it uses processes spawning that is costly.
Other thing is that it does not seem to provide events for mounting.

**Comment by MarshallOfSound** [comment]
This api surface doesn't have a compelling reason to be exposed as a core Electron API vs a native module.  The logic isn't super complex and there aren't easy Chromium helpers to expose anyway
