### ISSUE TITLE
app crashed when launched in AppVerifiy

### ISSUE THREAD

**Issue by everrr1025** [electron/electron#9761]
* Electron version: 1.6.1
* Operating system: win10

### Expected behavior
 Electron app should not crash when launched with AppVerifier
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/application-verifier

### Actual behavior
Electron app crashes when launched if AppVerifier is enabled with Basic + Miscellaneous checks enabled LayerName=Locks StopCode=0x211 Critical section is already initialized Module: vrfcore.dll Exc: 80000003

### How to reproduce
launch AppVerifier
with Basic + Miscellaneous checks enabled.
select a Electron app to run
see the crash happening

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
