### ISSUE TITLE
Electron will not Install

### ISSUE THREAD

**Issue by FaustianSpirit** [electron/electron#9762]
* Electron version: 1.7.3
* Operating system: Linux Mint 18.1 Serena
Python 2.7.12v
npm 5.0.3v
node 8.1.1v

### Expected behavior

Should start and run the script.

Should successfully execute 

 npm start electron
or npm install && npm start

### Actual behavior

Error Logs:
[2017-06-15T03_23_05_602Z-debug.txt](https://github.com/electron/electron/files/1076508/2017-06-15T03_23_05_602Z-debug.txt)

[2017-06-15T03_51_50_814Z-debug.txt](https://github.com/electron/electron/files/1076529/2017-06-15T03_51_50_814Z-debug.txt)
### How to reproduce
$ git clone https://github.com/electron/electron
$ cd electron
$ npm install && npm start

$ git clone https://github.com/npm/npm
$ cd npm
$ npm install && npm start

Error logs match respectively.

**Comment by MarshallOfSound** [comment]
@FaustianSpirit If you want to use electron you don't have to build from source and you definitely don't have to run `npm` from source.

If you just use `npm install electron` you will get prebuilt binaries for your OS you can use to develop.  Check out [Electron Quick Start](https://github.com/electron/electron-quick-start) for a super simple demo.

**Comment by shubham2892** [comment]
@FaustianSpirit Does that resolve your issue.

**Comment by enlight** [comment]
Since there's been no reply from the OP I'll assume this has been resolved.
