### ISSUE TITLE
Package an Electron App

### ISSUE THREAD

**Issue by broros** [electron/electron#9763]
can I Package an Electron App for all three operating systems ( macOS, linux, windows)  at once?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW you should check out `electron-packager`, `electron-forge` or `electron-builder`.  Any one of them can probably do what you're wanting to do
