### ISSUE TITLE
Reset printing settings to defaults.

### ISSUE THREAD

**Issue by Piom** [electron/electron#9770]
The default printer settings are set to portrait.
When printing documents (eg pdf), I choose the page orientation of the landscape. 
Then I try to print again and the orientation is reset to portrait.
However, in other browsers(Chrome, IE, Firefox), the orientation is preserved when reprinting.
Printing goes through the system window and directly from pdf.js

* Electron version: 1.6.10
* Operating system: Win 7/10 x64

### Expected behavior
Ability to save print settings as well as implemented in other browsers. Or the ability to manage the system printing window.

### How to reproduce
- Try to print the document.
- Change page orientation (layout)
- Repeat printing
- Check print settings

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
