### ISSUE TITLE
Drag and drop doesn't work if Electron launched from tmux

### ISSUE THREAD

**Issue by aconchillo** [electron/electron#9771]
This might be a tmux issue other than an Electron issue, I'm not really sure. So, I'm just posting it here in case you want to give it a try.

* Electron version: 1.6.11
* tmux version: 2.5 (from brew)
* Operating system: OS X 10.12.4

### Expected behavior

Drag and drop should work.

### Actual behavior

Drag and drop freezes further mouse interactions with the window.

Errors reported in the console:

    2017-06-15 15:52:12.718 Electron[61960:1420958] CoreDragCreate error: -4960
    2017-06-15 15:52:12.718 Electron[61960:1420958] error in CoreDragDispose: -1850

### How to reproduce

I just created this silly example (without tmux it should work):

    $ tmux

    $ git clone https://github.com/aconchillo/electron-dnd-test
    $ npm install
    $ npm start

**Comment by bpasero** [comment]
@aconchillo does this help https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41 (see last paragraph about `reattach-to-user-namespace`).

**Comment by aconchillo** [comment]
@bpasero Yes, it does. Thanks!

**Comment by enlight** [comment]
Looks like this particular issue has been resolved. Note that running Electron from tmux is [discouraged](https://github.com/electron/electron/issues/8479#issuecomment-306359224).

**Comment by aconchillo** [comment]
@bpasero suggestion fixed the drag and drop issue but after that I found other weird problems. So, I believe discouraged is the right word.
