### ISSUE TITLE
dialog.showErrorBox is not modal on Windows

### ISSUE THREAD

**Issue by LukePowell** [electron/electron#9773]
* Electron version:
1.6.11

* Operating system:
Windows 10

### Expected behavior

dialog.showErrorBox to display a modal error message on windows

### Actual behavior

Displays an non-modal dialog box allowing the user to interact with the app's content. These operations are not applied immediately however they are queued and applied after the fist dialog is closed. Simply spam click the error button to see this behavior. Additionally the dialog can be hidden causing the app to appear non-responsive to users.

### How to reproduce
Any code with dialog.showErrorbox see

  $ git clone https://github.com/LukePowell/electron-quick-start
  $ npm install
  $ npm start

**Comment by LukePowell** [comment]
Also reproducible on Mint Linux

**Comment by MarshallOfSound** [comment]
@LukePowell You might be better off using `showMessageBox` with a type of `"error"` and providing the parent window so that the message box becomes modal

**Comment by LukePowell** [comment]
Updated, sample code to include dialog.showMessageBox which is indeed correctly modal on Windows, macOS, and Linux so at the very least it can be worked around.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
