### ISSUE TITLE
Typescript translation incorrect for Electron.IpcRenderer.sendSync

### ISSUE THREAD

**Issue by seyfert** [electron/electron#9775]
* Electron version: 1.6.11
* Operating system: MacOS

### Expected behavior

Documentation does not define the return value for IpcRenderer.sendSync().  sendSync should be defined to return "any"

### Actual behavior

Documentation does not define a return type so the generated typescript definition for sendSync incorrectly returns void

### How to reproduce

See recent documentation and generated electron.d.ts

**Comment by MarshallOfSound** [comment]
Should be simple enough, declaring in the docs that it "Return `Object`" should map to any in the typescript defs

**Comment by abbish** [comment]
When will it be solved?

**Comment by zeke** [comment]
> "Return `Object`" should map to any in the typescript defs

That will work, but it's a bit misleading as the return type could also be a String, an Array, a Number, etc. Maybe we should introduce the notion of `any` as a return type in the docs?

**Comment by MarshallOfSound** [comment]
@zeke I think we already do in some places, `any` works for me 👍

**Comment by abbish** [comment]
`const version: any = ipc.sendSync(CHANNEL.GET_VERSION);`

I did it like is work for me, but it make the version's type not clear,
Actually, sendSync didn't care it's return value type
