### ISSUE TITLE
why the video stream is black?chrome has no problem

### ISSUE THREAD

**Issue by Hazlank** [electron/electron#9777]
Hi,all

* Electron version: 1.6.10
* Operating system: Windows 10

when i use the electron to open a new BrowserWindow，there is  no problem，the video can show the imgae,but when i open a new one，the new window of the video stream is black.  and the browser like chorme or firefox become black to。if i am not open electron to run ，the other browser is no problem 。there can  add the stream for video in local page 。Edge has the same problem too,why..?

there is the get video stream code

```
 function hasUserMedia() {
  return !!(navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia);
}
if (hasUserMedia()) {
  navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;   
  navigator.getUserMedia({
    video: true,
    audio: true
  }, function (stream) {
         var video = document.createElement('video');
                video.setAttribute('autoplay', '');
                document.body.appendChild(video)
        video.src = window.URL.createObjectURL(stream);
  }, function (err) {});
} else {
  alert("sorry,the browser is not support Webrtc");
}
```
--------------------------------------------------------------------

开了两个electron打包后的exe文件 就黑掉了，edge也是这样，只要打开一个窗口，再打开，本地的视频流创建的时候就是黑的啊。。不管再打开chrome 还是firefox 也是黑的，只用chorme 或者 firefox完全没事

**Comment by cifratila** [comment]
@Hazlank what is the encoding used on the video? could you share the stream, or at least give us more info related to the codecs being used? Chrome has different codecs that Chromium, Electron uses FFMPEG with Chromium codecs.

**Comment by Hazlank** [comment]
@cifratila thanks for reply,but I don't know  how to know the video encode,I just use webrtc api ,electron can use the vedio stream to show the image,but when i open new one ,the new window will throw the error,I submit a issue on webtrc org and somebody said cameras can only be used by a single process，I don't know how to solve it,like the chrome can run two pages.

**Comment by roy2651** [comment]
<script type="text/javascript"> 
        navigator.mediaDevices.getUserMedia({video: true, audio: false}).then(stream =>{
            $('#video').attr('src', window.URL.createObjectURL(stream));
        }).catch(err => {
            alert('获取媒体资源失败：' + err);
        });
    </script>

**Comment by eabrakov** [comment]
Hi all,
i got same issue when trying to access camera which is currently unavailable by another process (for example by Firefox). The `getUserMedia` request resolve the promise, but it should be reject it if device is not available.

Electron version: 1.7.5

**Comment by Hazlank** [comment]
@eabrakov yes...,the method can't throw the error ,I don‘t konw what happened

**Comment by zhouxun-open** [comment]
I have the same problem, it seems like electron occupying the authority of the camera and microphone

**Comment by Hazlank** [comment]
@zhouxun-open somebody say cameras can only be used by a single process...

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
