### ISSUE TITLE
npm install creating files at wrong directory for electron

### ISSUE THREAD

**Issue by azurinko** [electron/electron#9779]
* Electron version: Cloned from github today
* Operating system: Windows 10

### Expected behavior

When I performed 
npm install sqlite3 --build-from-source,
npm created directories for node js

### Actual behavior

npm didn't created directories for electron

### How to reproduce

https://github.com/electron/electron-quick-start
main.js;
added line 
const sql = require('sqlite3') 
on line 9

https://pastebin.com/J7s4iTDM

Here is what I have done, everyting, in command line.

**Comment by MarshallOfSound** [comment]
You should check out the tutorial for [Using Native Node Modules](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md)
