### ISSUE TITLE
Unresponsive event never gets triggered when `show: false` on BrowserWindow

### ISSUE THREAD

**Issue by domderen** [electron/electron#9781]
* Electron version: 1.6.11 & 1.7.3
* Operating system: macOS Sierra 10.12.5

### Expected behavior

BrowserWindow should emit `unresponsive` event when page becomes unresponsive. 

### Actual behavior

BrowserWindow never emits `unresponsive` event.

### How to reproduce

Example of an issue: https://github.com/domderen/electron-quick-start/tree/unresponsive_issue

This code loads a page that runs an infinite loop in JS. This makes the browser unresponsive, and it is not possible to interact with such a window.

When BrowserWindow is created with `show: true`, and user will try to interact with the window, it will fire the `unresponsive` event after some time.

But if the window is created with `show: false`, it is not possible to interact with the window, so `unresponsive` event never gets emitted. I tried calling `window.webContents.executeJavaScript` or using the ipcRenderer in hope that lack of response from one of those two would trigger the `unresponsive` event, but nothing worked.

So there doesn't seem to be a way to figure out that the window become unresponsive if it is not visible.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by nikwen** [comment]
Was running into a similar issue on Electron 31. While debugging, I noticed that the `unresponsive` event only seems to be emitted on user input (which will never happen for a hidden window). Without user input, even a window with `show: true` that is stuck in an infinite JS loop won't emit `unresponsive`.
