### ISSUE TITLE
globalShortcut key release

### ISSUE THREAD

**Issue by computerquip-streamlabs** [electron/electron#9783]
I don't see a way to get a key release event in globalShortcut. This is problematic if an app wants something to happen only while a key is pressed (since we can't know when to stop). Am I missing something?

**Comment by rayfranco** [comment]
Why is that issue closed ? Was it resolved ?

**Comment by computerquip-streamlabs** [comment]
@rayfranco I don't actually recall given the age of it. We ended up using a completely separate solution as well. Sorry.
