### ISSUE TITLE
Dialog on macOs are different from native apps.

### ISSUE THREAD

**Issue by yolo2013** [electron/electron#9786]
* Electron version: 1.6.11
* Operating system: macOs 10.12.5

I opened an dialog to choose image for some reasons. But I found the dialog in electron is just show in the center of screen. Then I tried 3-4 apps like twitter. The animation of twitter's dialog is very beautiful.
Someone have the same problem?

出于一些原因，我尝试在electron中选择本地文件。在开发过程中发现，electron中dialog的动画非常生硬，直接生硬地显示在屏幕中间。随后我测试了twitter、御饭等应用，发现这些应用的动画就非常自然。想确认下，有没有人和我存在同样的疑问？

**Comment by yolo2013** [comment]
I am so stupid... The reason is I should not put browserWindow to options...

**Comment by bitqiang** [comment]
What parameters have you added or changed after this question?
