### ISSUE TITLE
Running Changelog or History

### ISSUE THREAD

**Issue by gabrielcsapo** [electron/electron#9790]
I always wonder what the unreleased changes are in electron, but can never find a CHANGELOG or HISTORY file anywhere or on the site. 

Is this something that is kept internally or is there a way that it can be more transparent?

**Comment by enlight** [comment]
There's a list of changes for every release at https://github.com/electron/electron/releases

**Comment by gabrielcsapo** [comment]
@enlight I see that, but I am talking unreleased changes, so that we can get excited about stuff that is going to be released and plan for it

**Comment by KagamiChan** [comment]
You may find them in the commit history, and you can also watch this repository so that every commit and PR appear in your timeline and sent to you by email.

**Comment by gabrielcsapo** [comment]
Most of commit history contains one line doc or semantic changes that would flood my email. Is it not normal to instead of compiling a changelog at release time to have a running changelog of unreleased changes?

**Comment by KagamiChan** [comment]
Sorry for having deleted my comment. I realized my comment is not relevant to your issue just after pressing the comment button.

I‘m also interested about how electron build bot works ;-)

**Comment by gabrielcsapo** [comment]
@KagamiChan okay! Yeah I am looking for improvement in the release cycle so I can tell when things will be updated to speed up things or any new features that will be added 😄

**Comment by gabrielcsapo** [comment]
@enlight any update on this?
