### ISSUE TITLE
No LCD-text-antialiasing on macOS

### ISSUE THREAD

**Issue by vguerci** [electron/electron#9791]
* Electron version: 1.6.9 (Latest Atom version, but also Slack, GitKraken have this issue)
* Operating system: macOS Sierra 10.12.5 (Latest)

Not much describe as I just noticed the exact same behaviour as #6344, but on macOS

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
