### ISSUE TITLE
Electron Logo Usage (Documentation/Licence clarification)

### ISSUE THREAD

**Issue by stonegray** [electron/electron#9792]
The licence appears to be written in such a way that it's unclear if we can use the Electron logo. 

> When using the Electron or other GitHub logos, be sure to follow the GitHub logo guidelines.

However the [guideline documents](https://github.com/logos) only permit you to use the Github marks, and specifically ask you to contact them to use any other marks (which would include Electron)

To remove ambiguity, should we add our own logo usage policy for the Electron logo? Is this something Github should clarify?

**Comment by MarshallOfSound** [comment]
Seen this asked before in the atom.io Slack channel and can't remember who answered it 😆 

/cc @groundwater @lee-dohm

**Comment by lee-dohm** [comment]
@stonegray the idea behind linking to github.com/logos is that you may follow the same guidelines for the use of the Electron logo as for the GitHub or Octocat logo. For example, you may use the Electron logo on a website to link to your GitHub repo for your Electron-based project but you may not use the Electron logo for your application icon. If you have any questions as to whether your specific use is allowed by our logo policies, please contact us through electron@github.com.

We do intend to update github.com/logos at some point but I don't have a timeline for when that will happen.
