### ISSUE TITLE
TS definition for ClearStorageDataOptions does not match docs

### ISSUE THREAD

**Issue by kevinphelps** [electron/electron#9793]
* Electron version: 1.6.11
* Operating system: Window

### Expected behavior
The `origin`, `storages`, and `quotas` properties on the `Electron.ClearStorageDataOptions` interface should be options as specified in [the docs](https://github.com/electron/electron/blob/master/docs/api/session.md#sesclearstoragedataoptions-callback).

![image](https://user-images.githubusercontent.com/7399499/27269479-e6d909c2-547c-11e7-973c-9172cda36816.png)

### Actual behavior

None of the properties on `Electron.ClearStorageDataOptions` are optional in `electron.d.ts`.

![image](https://user-images.githubusercontent.com/7399499/27269504-1b67f0d6-547d-11e7-809d-31a53e62f463.png)

**Comment by kevinphelps** [comment]
I just checked the 1.7.3 beta version, and it's the same.

**Comment by MarshallOfSound** [comment]
@kevinphelps I fixed this 5 days ago, the last release was 10 days ago.  This will be in the next beta

https://github.com/electron/electron/commit/de066b8d1384fb89546295d0e53f0c3c8cda79ff

**Comment by kevinphelps** [comment]
Oh. Sorry for creating a new issue. I did not see the closed issue when I searched.
