### ISSUE TITLE
electron supports MOVE as drag&drop operation by default

### ISSUE THREAD

**Issue by ihalip** [electron/electron#9794]
* Electron version: 1.7.3
* Operating system: Windows 7 64-bit

Initially reported for VS Code: https://github.com/Microsoft/vscode/issues/25196

When dragging and dropping from another application, the default operation is MOVE:
![output](https://user-images.githubusercontent.com/1991437/27270663-95f90f42-54c8-11e7-89f0-4d9eeb4fe90c.gif)

This can have unintended side effects:
- Windows Explorer: as per the original report, this can lead to the original file being deleted

- Notepad++: you can drag&drop a piece of text from NPP to electron; the text is then deleted from NPP

### Expected behavior

The default operation should be COPY (or LINK?).

### Actual behavior

The default operation is MOVE.

### How to reproduce

1. Download & run the latest electron release (I used https://github.com/electron/electron/releases/download/v1.7.3/electron-v1.7.3-win32-x64.zip)

2. Open an FTP location in Windows Explorer (I used ftp://test.rebex.net/pub/example/, user: demo, pass: password)

3. Drag & drop a file from Windows Explorer to the electron window

4. You should see a message box mentioning that the file could not be deleted from the server

**Comment by epicfaace** [comment]
@codebytere this is still happening in recent versions of electron, as the aforementioned bug (microsoft/vscode#25196) is still present in VS Code.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
