### ISSUE TITLE
Uncaught Exception: TypeError: Error processing argument at index 0, conversion failure from file:///root/doc_electron/chef.ico

### ISSUE THREAD

**Issue by zombieleet** [electron/electron#9795]
Electron Version: 1.7.2
Operating System: Linux 4.4.0-kali1-amd64 #1 SMP Debian 4.4.6-1kali1 (2016-03-18)

Am currently following the electron documentation, but the Tray api is not working, it spits out this error

**Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from file:///root/doc_electron/chef.ico
    at App.app.on (/root/doc_electron/tray.js:6:10)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)**

This is the code

```javascript
const { app, Menu, Tray } = require("electron");

let tray ;

app.on("ready", () => {
  tray = new Tray(`file://${__dirname}/chef.ico`);
  const contextMenu = Menu.buildFromTemplate([
    {label: "Item1", type: "radio"},
    {lable: "Item2", type:"radio"},
    {label: "Item4", type: "radio"}
  ]);
  tray.setToolTip("This is my application.");
  tray.setContextMenu(contextMenu);
});
```

**Comment by enlight** [comment]
You need to use a file path to specify the icon, not a URL.

**Comment by zombieleet** [comment]
@enlight using a file path does not make it work either

**Comment by enlight** [comment]
Can you update the snippet you posted to show how you've specified the file path?

**Comment by MarshallOfSound** [comment]
Woo hoo, my turn to close this 😆 

https://github.com/electron/electron/blob/b09086c1b8a498c8d5184c6cb466dd3b1a668094/docs/api/native-image.md#supported-formats

> On Windows, you can also load ICO icons from file paths.

`.ico` files are not supported as native images on linux. See https://github.com/electron/electron/issues/2277 for more information

**Comment by eveningkid** [comment]
In case someone ends up here without finding a solution that works, here are the steps I'd recommend:
- are you passing a *NativeImage* value to `Tray` constructor? If not:
```js
// If not already imported
// const path = require('path');
const iconPath = path.join(__dirname, 'tray-icon.png');
const trayIcon = nativeImage.createFromPath(iconPath);
const tray = new Tray(trayIcon);
```
- does your icon follow any of the [*NativeImage* supported formats](https://electronjs.org/docs/api/native-image#supported-formats)? **PNG and JPEG** are the only two formats supported on all platforms.
- remember that your icon should be **sized 16*16px**
