### ISSUE TITLE
how can i intercept some http request fallback to custom file

### ISSUE THREAD

**Issue by hibin101** [electron/electron#9796]
i use win.loadURL('http://example.com/index.html') to load a page，and  i want to intercept this request
fallback to custom file like:
protocol.interceptStringProtocol('http', (request, callback) => {
  ...
 callback({
     data: fs.readFileSync(path.normalize(`${__dirname}/index.html`), 'utf-8')
 })
})

this will intercept all http request from this page，how can i do only intercept some http request

* Electron version:
* Operating system:

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW `callback(null)` will trigger the default response I believe

**Comment by hibin101** [comment]
@MarshallOfSound thanks all
