### ISSUE TITLE
WebGL does not work with --disable-gpu

### ISSUE THREAD

**Issue by darshanrajani** [electron/electron#9803]
* Electron version: 1.7.0
* Operating system: Windows Server 2008 R2

### Expected behavior

WebGL should work even if --disable-gpu is used by using software-based rendering. Works when Chrome is launched with --disable-gpu

### Actual behavior

WebGL context creation fails.

### How to reproduce

Clone https://github.com/zcbenz/nw-sample-apps and run the app which is under webgl directory.

**Comment by codebytere** [comment]
As this is not an officially supported command line switch, we encourage you to try some of the ones that aren't supported but we aren't currently releasing bugfixes for them.
