### ISSUE TITLE
Device Emulation Disabled after Opening/Closing Devtools

### ISSUE THREAD

**Issue by 4eveRS** [electron/electron#9805]
* Electron version: 1.6.11
* Operating system: MacOS 10.12.5

### Expected behavior

Device emulation should be kept active independently of toggling the webview devtools.

### Actual behavior

If you define a device emulation before opening the webview devtools, it will be automatically disabled, the same will happen if you close the devtools, it will disable the device emulation.

### Partial Fix

What I did to partially fix it, was define a listener to when the user close the devtools, to set the device emulation back, and, when the user opens the devtools I set the device emulation again, after calling the function for opening the devtools.

It's far from a perfect solution, since the webview keeps blinking, because of the change on the width and height.

**Comment by sintanial** [comment]
Same problem too !!

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
