### ISSUE TITLE
Webview + executeJavaScript + nodeintegration

### ISSUE THREAD

**Issue by paul321** [electron/electron#9811]
* Electron version: 1.7.3
* Operating system: MacOS

We are trying to load a remote page in webview container, the problem is when the webview has nodeintegration on the webview freezes for 30 seconds when the executJavaScript is called also the webview devtools are blank. Is this a known issue?

**Comment by paul321** [comment]
This doesn't happen in 1.6.2

**Comment by shubham2892** [comment]
@paul321 Can you provide a minimal example with steps to reproduce the issue. Thanks!

**Comment by paul321** [comment]
I'll do some tests on 1.7.4 and see if it's happening and i'll try to implement an example, if not will close it. Thanks!

**Comment by paul321** [comment]
It doesn't happen in 1.7.4 so i'll close it.
