### ISSUE TITLE
chrome is not defined

### ISSUE THREAD

**Issue by doanchu** [electron/electron#9812]
* Electron version: 1.6.1
* Operating system: Windows 10 64 bit

### Expected behavior

window.chrome should not be undefined

### Actual behavior

window.chrome is indeed undefined. 
I wanted to use some of the supported chrome.* APIs but when I tried to access window.chrome, this object is undefined.

**Comment by MarshallOfSound** [comment]
The chrome API's Electron supports are for devtools extensions only not for a normal renderer.  Most chrome API's have equivalent NPM modules that you can use instead
