### ISSUE TITLE
[Question] Change app version.

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#9813]
Hey guys, I'd like to have ability to manually and permanently change app version (app.getVersion). 

Tried to change in package.json (/.app/Content/Resources/app.asar.unpacked) and Info.plist (/.app/Contents) without luck, it still return app version that was set on build stage (electron-builder).

Is it possible?
Thanks.

**Comment by blcktqq** [comment]
When increment app version, i use  npm version patch .
after that i read it from package.json
```
require('./package.json').version
````

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
