### ISSUE TITLE
Browser history not working

### ISSUE THREAD

**Issue by saadbinsaeed** [electron/electron#9818]
I am using the **react-router v3**. My website works fine with **browserHistory**, But the same application ( with browserHistory ) not working in electron app. **hashHistory** works well but i can not use it because i have multiple applications on my web platform that are using browserHistory. This is why i can not afford any disturbance with the code base. Want to keep it same for **web** and for **electron** app.

At first browserHistory was also not working in the web app but then i changed the ngnix configuration which let the browserHistory works. I am presuming that i have to change the configurations of the electron like i did with ngnix. Any help?

* 1.6.11:
* Ubuntu 16.0.4:

### Expected behavior

It should work with the browserHistory

### Actual behavior

Not working with react-router browerHistory

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

I'm assuming you're using a `file://` protocol to server your react app locally, browser history won't work with that way of serving files.  You need to use a custom protocol to server your files so it looks like they come from an actually valid URL.

`custom://myapp/index.html`

Check out the protocol docs for the API details
