### ISSUE TITLE
WebContents.reload doesn't stop at breakpoints set at beforeunload and unload handler

### ISSUE THREAD

**Issue by jrieken** [electron/electron#982]
* start with the atom sample from here: https://github.com/dougnukem/hello-atom
* change index.html to be the code from below, also make sure to show dev tools (```
  mainWindow.toggleDevTools();```)
* set breakpoints in ```onbeforeunload``` and ```onunload```
* close the app and notice how the breakpoints are called
* start the app again and hit F5
* => the breakpoints aren't hit

```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
    <script type="text/javascript">
      window.onbeforeunload = function() {
        return 'beforeunload!';
      }
	  window.onunload = function() {
        return 'unload!';
	  };
    </script>
    <script type="text/javascript">
			(function() {
				var remote = require('remote');
				window.addEventListener('keydown', function(e) {
					 if (!e.ctrlKey && !e.metaKey && !e.altKey && !e.shiftKey && e.keyCode === 116) { // F5
						remote.getCurrentWindow().reload();
					}
				});
				
			})();
		</script>
  </head>
  <body>
    ...
  </body>
</html>

```

**Comment by zcbenz** [comment]
I tried to print something in the `unload` handler and they are successfully printed, but the script did failed to stop at the breakpoints when reloading.

```javascript
      window.onbeforeunload = function() {
        console.log('onbeforeunload');
        return 'beforeunload!';
      }
      window.onunload = function() {
        console.log('onunload');
        return 'unload!';
      };
```

I can not reproduce the same thing in Chrome, so it should be a bug to atom-shell's devtools implementation.

**Comment by deepak1556** [comment]
setting breakpoint near `window.unload` handler breaks while refreshing but also seems to run the contents of the handler. will look into this
![screenshot from 2015-03-04 18 02 34](https://cloud.githubusercontent.com/assets/964386/6483643/4daa3928-c299-11e4-8943-7075a10dd3da.png)

**Comment by deepak1556** [comment]
Not quite sure if this will help, but with the recent changes there seems to be a new warning. So tried debugging the devtools attached to atom-shell with breakpoint set at the warning line `1656` and apparently events do get fired with the right data for breakpoint indication but somewhere in the callstack the frame data becomes `undefined`.

```
$ ../atom-shell/out/Debug/Atom.app/Contents/MacOS/Atom --remote-debugging-port=8259 ./hello-app
[68664:0311/182201:INFO:renderer_main.cc(211)] Renderer process started
[68665:0311/182201:INFO:renderer_main.cc(211)] Renderer process started
[68662:0311/182207:INFO:CONSOLE(7)] "beforeunload!", source: file:///Users/dmohan/projects/github/hello-atom/hello-app/index.html (7)
[68669:0311/182207:INFO:renderer_main.cc(211)] Renderer process started
[68662:0311/182207:WARNING:CONSOLE(1656)] "ScriptsPanel paused, but callFrames.length is zero.", source: chrome-devtools://devtools/sources_module.js (1656)
```

**Comment by ppoo24** [comment]
Same boring problem under webview

**Comment by zcbenz** [comment]
Unable to reproduce in 0.37.x anymore.
