### ISSUE TITLE
logged in session

### ISSUE THREAD

**Issue by muscaiu** [electron/electron#9821]
Is there any way i could inject or set cookies so that i could get a logged in github session in a new window?

```
        let win = new BrowserWindow({
            width: 800,
            height: 600,
        })
        win.loadURL('https://www.github.com')
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
