### ISSUE TITLE
webview jquery not defined when loading website

### ISSUE THREAD

**Issue by BartNetJS** [electron/electron#9822]
* Electron version: 1.6.11
* Operating system: windows

I try to load a website that redirects to authenticate to https://login.microsoftonline.com 
In the developer tools/console there is an error jquery not defined inside the jquery library

![capture](https://user-images.githubusercontent.com/4865355/27398192-43d5b434-56b9-11e7-97ac-babb577774c1.JPG)

Any idea?

**Comment by MarshallOfSound** [comment]
Please ensure that `nodeIntegration` is disabled for the webview

**Comment by BartNetJS** [comment]
I tried that, but it doesn't make a difference.

**Comment by MarshallOfSound** [comment]
@BartNetJS I just tested the URL you provided with a webview with `nodeIntegration` disabled and encountered no errors.  Additionally `window.jQuery` is defined successfully on that page.

I would suggest double checking that `nodeIntegration` is actually disabled, if the `require` function exists globally then `nodeIntegration` is still enabled somewhere.

**Comment by akashnimare** [comment]
@BartNetJS you need to disable nodeIntegration for the **webview** and make sure that you have not added `nodeIntegration: true` while creating the browserwindow.

**Comment by BartNetJS** [comment]
@MarshallOfSound it was indeed nodeIntegration.
I was using electron-tabs and when I set nodeIntegration : false in the webviewAttributes, it was still enabling nodeIntegration.
thanks

**Comment by joravkumar** [comment]
@BartNetJS Is your problem Solved? Facing exact same issue here.

**Comment by farhodN1** [comment]
> Please ensure that `nodeIntegration` is disabled for the webview

it worked for me
