### ISSUE TITLE
Memory leak when creating Menu

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#9823]
* Electron version: 1.7.3, 1.6.11
* Operating system: macOS 10.12.5

### Expected & Actual behavior

Creating a menu object then losing the reference to it should not increase memory consumption. In the below example the menu is thrown away at the end of the function, but remains in memory.

```js
const { Menu } = require('electron')
(function () {
  const menu = Menu.buildFromTemplate([{ label: 'Test' }])
})()
```

Arguably you should could call `destroy()` on the menu, but if it has submenus the leak remains as the submenus are not destroyed either.

```js
const { Menu } = require('electron')
(function () {
  const menu = Menu.buildFromTemplate([{
    label: 'Test',
    submenu: [ { label: 'Test2' } ]
  }])
  menu.destroy()
})()
```

### How to reproduce

Probably best to show this with an example :). This repo does nothing more than create lots of menus and log memory usage

```
git clone https://github.com/wavebox/electron-quick-start.git
cd electron-quick-start
git checkout menu-memory-leak
npm install
npm run broken //to see the broken behaviour
npm run fixed //to see the fixed behaviour
```

In the broken example `destroy()` is only called on the topmost created menu. In the fixed example `destroy()` is also called on the submenu

### Fixes

I guess there's arguments for either destroying automatically when references are released, or being required to call destroy to release memory. You could also argue that the `destroy` call should destroy all submenus too, but I can imagine use cases where this might not be desirable. Perhaps having a `destroyAll()` type call would be useful.

**Comment by fantasticsid** [comment]
Just to add some more details using memory profiler, I tried allocating Menu objects, comparing the cases for calling/not calling menu.destroy()

`
function reclaimMenus() { 
  var m = null;
  var i = 0; for (i = 0; i < 10000; i++) { m = new electron.remote.Menu(); m.destroy(); } }


![destroy 10000 allocations](https://user-images.githubusercontent.com/203771/36326546-4ebf0ff8-1310-11e8-8f9a-e47047bc9c8c.PNG)

`
VS

`function leakMenus() { var m = null; var i = 0; for (i = 0; i < 10000; ++i) { m = new electron.remote.Menu();} }
`

![no destroy 10000 allocations](https://user-images.githubusercontent.com/203771/36326548-4eee5a06-1310-11e8-8a48-04831ec33779.PNG)

**Comment by Thomas101** [comment]
@fantasticsid the leak only appears when there's a submenu included. My guess is there's a cyclic reference in there that causes the leak.

The profiling you've got with creating a 1-depth menu is correct and non-leaky

**Comment by fantasticsid** [comment]
There's a `MenuView` object associated with each `Menu` object that has to be manually destroyed, they are not freed as part of V8 gc because there's no reliable way to do this with V8 as far as I know. In other words, these C++ objects are not managed by V8 gc.
The implementation of `destroy` frees this object.
I added a destructor to `MenuView`, and if `destroy()` is not called, the destructor is never called.

**Comment by zcbenz** [comment]
It seems that we have some cyclic reference preventing menu to be garbage collected, can reproduce with:

1. Add some logging in `Menu::~Menu()`
2. Run Electron with `--enable-logging --js-flags="--expose_gc"`
3. Run in console:

```js
const electron = require('electron')
for (let i = 0; i < 100; ++i)
  new electron.remote.Menu
gc()
```

**Comment by zcbenz** [comment]
I confirm the way delegate methods are stored is adding cyclic reference:
https://github.com/electron/electron/blob/v1.8.2/atom/browser/api/atom_api_menu.cc#L37-L42

I think we also have similar problems with submenus referencing their parents.
