### ISSUE TITLE
Setting the renderer's zoom level before a webview is loaded causes the webview's inner content to no longer fill the frame

### ISSUE THREAD

**Issue by ccnokes** [electron/electron#9825]
* Electron version: 1.6.11
* Operating system: MacOS (Windows too probably)

### Expected behavior

The content of the webview should fill the frame.

### Actual behavior

The content gets resized smaller than the frame. See screenshot below. 

![image](https://user-images.githubusercontent.com/1610343/27402772-0ae06f5e-5685-11e7-9126-6a33c4f1c3fa.png)

### How to reproduce
See `test1` function here https://github.com/ccnokes/electron-webview-zoom-bugs/blob/master/renderer.js#L43
(Note that repository also demonstrates another bug where a webview's content does not fill the frame if the webview is hidden and then re-shown. That bug might already be adequately reported in #7375.)

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
