### ISSUE TITLE
On Windows, app.setLoginItemSettings sets "Update" and "Github" as my app's name/publisher in Task Manager > Startup

### ISSUE THREAD

**Issue by ccnokes** [electron/electron#9827]
* Electron version: 1.6.11
* Operating system: Windows 10

### Expected behavior
It should use my app's name, icon, and publisher.

### Actual behavior
It uses the generic icon, "Update", and Github as the publisher. See screenshot.

![image](https://user-images.githubusercontent.com/1610343/27409538-2ad42dae-569f-11e7-89a0-f0308f6d72bd.png)

### How to reproduce
Following the docs for Windows, I call it like so: 

```javascript
const appFolder = path.dirname(process.execPath)
const updateExe = path.resolve(appFolder, '..', 'Update.exe')
const exeName = path.basename(process.execPath)

app.setLoginItemSettings({
  openAtLogin: true,
  path: updateExe,
  args: [
    '--processStart', `"${exeName}"`,
    '--process-start-args', `"--hidden"`
  ]
})
```

Note the functionality works as expected, this is more of a visual/informational thing that seems buggy.

Let me know if you need any more details or if this is actually a Squirrel.Windows issue or something.

**Comment by levrik** [comment]
@ccnokes Windows shows the information from the executable. In this case the `Update.exe`. You can just change these information with tools like rcedit (https://github.com/electron/rcedit).

**Comment by MarshallOfSound** [comment]
This is expected behavior, you can set the metadata on `Update.exe` if you want it to look different in that display as @levrik described

**Comment by ccnokes** [comment]
Thanks! I'll look into that.
