### ISSUE TITLE
Problem with devtools - Network. Requests Display

### ISSUE THREAD

**Issue by Devhercule** [electron/electron#9830]
in index.html:
`<webview id="webview1" src="http://www.example.com/" autosize="on"></webview>`

in Renderer.js:
```
var webview = document.getElementById("webview1");
webview.addEventListener("did-start-loading", function(){ webview.openDevTools(); });
```

* Electron version: 1.6.2
* Operating system: Windows7

### Expected behavior
all requests are displayed in dev tool -> network
especially the first request (type : document) 

> Request URL:http://www.example.com/

This request is not displayed in devtools -> Network
If i press F5, it appears, but i need to display it without pressing F5

### Actual behavior
All request are diplayed, EXCEPT the first one.
The first query is never displayed

![impr](https://user-images.githubusercontent.com/29538843/27426794-180a518c-573d-11e7-86f4-68b6ddc0c8c6.png)

Can you help me to display the first sent request?

Thank you

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
