### ISSUE TITLE
Get click events in screen

### ISSUE THREAD

**Issue by TheRolfFR** [electron/electron#9838]
* Electron version: v1.6.11
* Operating system: Windows 7 x64 SP1

Is there any way to get click events in screen ? I need it to drag a browserWindow when it is not focused.

Thanks in advance.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

There is currently no API in Electron to get mouse events outside your window, you will need to write / use a native module to do this.
