### ISSUE TITLE
Adding mp3 to the patent-free ffmpeg dll

### ISSUE THREAD

**Issue by phas0r** [electron/electron#9839]
Now that mp3 decoding is patent free, will mp3 be added to the patent-free ffmpeg dll and when might that happen?

I am currently working on a project that would benefit from supporting mp3 over the web audio API.

If it will not be added, is there a documented way on how to compile the library for electron myself?

**Comment by MarshallOfSound** [comment]
That depends on Chromium setting it to be enabled by default and as Chromium currently have no plans to do that.

See https://groups.google.com/a/chromium.org/forum/#!topic/embedder-dev/qnT2A5q9soM

Then I don't believe it will make it into the alternative `ffmpeg` builds provided by Electron either
