### ISSUE TITLE
Different focus result between Mac and Window

### ISSUE THREAD

**Issue by jwu** [electron/electron#984]
Hi, 

I'm working on a new feature in our App which relate with focus behaviour. The feature is to capture if an atom-shell app is totally lost focused. Since my App can have multiple windows, I can not simply do this by using one window's `blur` and `focus` events. Instead, I try to do this by detecting if all of my windows get unfocused when a `blur` event fired. 

Here is my script to do this:

```javascript
    this.nativeWin.on ( 'blur', function () {
        if ( !BrowserWindow.getFocusedWindow() ) {
            /// none of my atom-shell windows get focused, safely send 'totally-blur' message here!
        }
    }.bind(this) );
```

Actually the above script works correctly in Mac OSX, but when I test it in Windows platform, the `getFocusedWindow()` will still return the window who fired `blur` there. What I expect is a null/undefined here.

### Another suggestion:

I think the `focus` and `blur` event can carry more information from its event. The event should known which window get lost and which one get focus to (if that is an atom-shell window). This is very similar to what we have in DOM event. The `focus-in`, `focus-out`, `focus` and `blur` event have a parameter named event.relatedTarget, which will holding the next focus or last blur element, and will become null/undefined if user just click mouse outside browser.

Besides, like what we discussed in #981 , if we have the ability to detect DevTools' window behaviour, that would be perfect for detecting totally blur in my case. 

### Test environment:

I test this under Windows 7/8, Mac OSX 10.10.1 with atom-shell v0.20.4.

**Comment by zcbenz** [comment]
On Windows the `blur` event is emitted when window is beginning to lose focus, so `BrowserWindow.getFocusedWindow()` still returns current window. Before this is fixed, you can simply do things in next tick to work around it:

```javascript
this.nativeWin.on ( 'blur', function () {
    setImmediate(function() {
      if ( !BrowserWindow.getFocusedWindow() ) {
          /// none of my atom-shell windows get focused, safely send 'totally-blur' message here!
      }
    });
}.bind(this) );
```

**Comment by jwu** [comment]
Thanks, it works!
