### ISSUE TITLE
Override menu buttons

### ISSUE THREAD

**Issue by Gunnthorian** [electron/electron#9843]
### Versions:

* Electron version: 1.4.13
* Operating system: OSX 10.12.5

Using a frameless window with a hidden titlebarstyle has made the window and its menu buttons function and look just as they were intended, however, I need the Maximize button to perform my own function and not the default. The maximize button has setFullScreenable false so it looks like the original "+" and won't try and put my app in fullscreen, great! Now Im trying to stop if from attempting to set the app to what it thinks maximize should be.

### Current

` mainWindow.on('maximize', function (event) {`
&nbsp;&nbsp;&nbsp;&nbsp;`event.preventDefault()`
&nbsp;&nbsp;&nbsp;&nbsp;`    mainWindow.setSize(`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`          600,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`          800`
&nbsp;&nbsp;&nbsp;&nbsp;`    )`
` })`

However, the `event.preventDefault()` doesn't work, or maybe Im doing it wrong.

### Suggestion

In the end I would like for app to toggle between two, three, or four different sizes. This would all be achievable if there was a way to do:

`mainWindow = new BrowserWindow({`
&nbsp;&nbsp;&nbsp;&nbsp;`    width: 300,`
&nbsp;&nbsp;&nbsp;&nbsp;`    height: 400,`
&nbsp;&nbsp;&nbsp;&nbsp;`    frame: false,`
&nbsp;&nbsp;&nbsp;&nbsp;`    titleBarStyle: 'hidden',`
&nbsp;&nbsp;&nbsp;&nbsp;`    insteadOfMaximizeRun: thisFunction(),`
&nbsp;&nbsp;&nbsp;&nbsp;`    insteadOfMinimizeRun: thatFunction(),`
`  })`

### Suggested behavior

Clicking the button should run the function that you specified

### Actual behavior

window gets thrown around the screen and when you move the window in its 'maximized' state (for my app its only 600x800, so it hardly fills the screen) and try and maximize or minimize it again it breaks and you need to relaunch.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
