### ISSUE TITLE
capturePage doesnt capture images larger then screen size

### ISSUE THREAD

**Issue by ronalb** [electron/electron#9845]
* Electron version:
1.6.11
* Operating system:
windows 10

### Expected behavior
I created an svg larger then my screen size and i'm trying 
to capturePage . the largest png i can get is the my screen size.
i tried with rect and without rect

I think if i can make a large web page I should be able to capture it.

### How to reproduce
create a page larger then your screen size,and then try to capturePage

**Comment by juliangruber** [comment]
when the rect you define is bigger than the window size, the resulting image will only be stretched to the rect size.

**Comment by ronalb** [comment]
the rect is same as window size. 
window size is 3 times bigger the actual monitor/screen resolution size. the window is rendered correctly.
captureImage doesn't work.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by danelkhen** [comment]
This is still happening to me on Electron v3.0.10, Chromium v66.0.3359.181, Node v10.2.0, v8 v6.6.346.32

**Comment by danelkhen** [comment]
@codebytere the problem persists at least on v3.0.10, can we keep it open?
