### ISSUE TITLE
In sanbox mode, BrowserWindow.reload() does not work

### ISSUE THREAD

**Issue by CptMaumau** [electron/electron#9858]
* Electron version: 1.6.11
* Operating system: darwin x64

### Expected behavior

When I hit Cmd+R or click on the menu label, the main window reloads

### Actual behavior

The window does not reload

### How to reproduce

```
mainWindow = new BrowserWindow({
    webPreferences : {
      sandbox: true
    }
  })
```

```
var appMenu = Menu.buildFromTemplate([
   {
      label: "View",
      submenu: [
        { role: "reload" }
      ]
   }
])

```

**Comment by nornagon** [comment]
Hi! 👋 Thanks for this report :) I tried this locally (on Mac), and wasn't able to reproduce the behaviour you're describing on the latest version of Electron (2.0.0-beta7). Both reload from the menu and reloading with Cmd+R work fine for me.

Would it be possible for you to try again with a more recent version of Electron? I'm afraid 1.6.x won't be supported for much longer 😞

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/9858#issuecomment-378765544). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
