### ISSUE TITLE
can not load Tary ! Exception  :conversion failure from ico2.png

### ISSUE THREAD

**Issue by xinhui-hui** [electron/electron#9859]
- Electron version:  all
- Operating system: windows10

**Expected behavior**
使用 "npm start" 启动能正确的加载到托盘图标，但是使用 “electron.exe path-to-your-app”这种方式不行,。
use "npm start" to start my app can load Tray Icon. but can not use "electron.exe path-to-your-app".

`function createTray(){
  tray = new Tray("ico2.png")
  const contextMenu = Menu.buildFromTemplate([
    {label: 'Item1', type: 'radio'},
  ])
  tray.setToolTip('Tray Test')
  tray.setContextMenu(contextMenu)
}`

#**How to reproduce**
![qq 20170626183850](https://user-images.githubusercontent.com/7787811/27535815-d5f83d08-5a9e-11e7-805d-5dd190911bc5.png)

**Comment by MarshallOfSound** [comment]
Please use an absolute path to your icon using `path.resolve()`
