### ISSUE TITLE
processes persists after closing the application on packaged

### ISSUE THREAD

**Issue by aprilmintacpineda** [electron/electron#9862]
Hi everyone, I just started using electron today, I am creating this hello world application that seems okay while in development, so if I run electron, as you would while developing it, using `npm start` that points to `electron .` I see my app which is simply a page with `<h1>hello world!</h1>`, but if I package it using [https://github.com/Urucas/electron-packager-interactive](electron-packager-interactive), I run the `[app name].exe` then if I close the application, the process (on my task manager) is not closing.

**Directory**
```
|-app
|-node_modules
|-public
|---main.html
|---app.css (bundled with webpack)
|---main.js (bundled with webpack)
|-resources
|---assets
|------scripts
|------styles
```

**scripts/entry.js**
```
import electron from 'electron';
import path from 'path';
import url from 'url';

const Browser = electron.BrowserWindow;
const App = electron.app;

let mainWindow;

App.on('ready', () => {
  mainWindow = new Browser({
    minWidth: 1024,
    minHeight: 600,
    width: 1024,
    height: 600
  });

  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'main.html'),
    protocol: 'file',
    slashes: true
  }));
});

App.on('window-close-all', App.quit);
App.on('before-quit', () => {
  mainWindow.removeAllListeners('close');
});
```

**styles/entry.sass**
```
h1
  color: gray
```

### while on dev (electron .)
**opened**
![image](https://user-images.githubusercontent.com/21032419/27542385-b051edfe-5ab9-11e7-9937-8dbec5bd6f7d.png)
**closed**
![image](https://user-images.githubusercontent.com/21032419/27542454-dfb00a68-5ab9-11e7-83e0-54336f21acbf.png)

### packaged
**opened**
![image](https://user-images.githubusercontent.com/21032419/27542504-fc3202ae-5ab9-11e7-88f7-009365fbe57d.png)
**closed**
![image](https://user-images.githubusercontent.com/21032419/27542514-064a6d30-5aba-11e7-8e93-6320a2c760f2.png)

The processes simply persist and if I open another application I get 4 total processes (2 new plus the old 2 persisting processes) and the same thing happens to those process.

### from packager
? Overwrite output directory ? Yes
? Use asar source packaging ? Yes
? Select Electron app source directory: C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-helloworld
? Select Electron app output directory: (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-helloworld\releas? Select Electron app output directory: C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-helloworld\releases
? Select Application name: 1-helloworld
? Select App Bundle Id (optional):
? Select App Version(optional): 0.0.1
? Select Electron icon file:
? Select Electron version release: 1.6.11
? Select platforms:
? Select architecture:
! No arch specified, defaulting to x64
! No platform specified, defaulting to win32
Electron packager settings:
{ dir: 'C:\\Users\\aprilpineda\\Documents\\projects\\desktop\\experiments\\1-helloworld',
  name: '1-helloworld',
  platform: null,
  arch: null,
  electronVersion: '1.6.11',
  out: 'C:\\Users\\aprilpineda\\Documents\\projects\\desktop\\experiments\\1-helloworld\\releases',
  appBundleId: '',
  appVersion: '0.0.1',
  overwrite: true,
  asar: true,
  icon: '',
  bundle_id: '',
  appname: '1-helloworld',
  sourcedir: 'C:\\Users\\aprilpineda\\Documents\\projects\\desktop\\experiments\\1-helloworld',
  ignore: 'C:\\Users\\aprilpineda\\Documents\\projects\\desktop\\experiments\\1-helloworld\\releases' }
Packaging app for platform win32 x64 using electron v1.6.11
✓ Application packaged successfully to 'C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-helloworld\releases\1-helloworld-win32-x64'

**Comment by MarshallOfSound** [comment]
`mainWindow.removeAllListeners('close');` this is almost certainly your problem, I can't verify now but Electron almost certainly internally listens for that even as well and removing all listeners removes Electron's listeners as well.

In general it is good practice to be more explicit when removing listeners, pass it the exact function you want to unregister as well as the event name to ensure no side effects.

**Comment by four-eyes-04-04** [comment]
But I use anonymous functions for listeners, like in the `app.on('ready')`. Would I be required to use named functions?

**Comment by MarshallOfSound** [comment]
@four-eyes-04-04 If you want to safely remove a listener yes, you need to keep a reference to it. You can do this through a named function `function foo () {}` or still using an arrow function `const foo = () => {}`

**Comment by four-eyes-04-04** [comment]
@MarshallOfSound Okay, but from the [docs](https://electron.atom.io/docs/all/#ipcmainremovealllistenerschannel) I saw that `removeAllListeners` only accepts one parameter, should I use `removeListener` over `removeAllListeners`? also shouldn't `app.quit()` be enough? I mean it should remove all listeners by default right since we are quitting the application.

**Comment by MarshallOfSound** [comment]
To remove a single listener you should use `removeListener`.

Calling `app.quit()` will not remove listeners, it will still emit several events while quitting the application, some of which you can call `event.preventDefault()` to stop the quitting process.

**Comment by four-eyes-04-04** [comment]
I did as you said, now the only event listener that I have is on the `app` object, and the `on ready`, now this is the only script that I have.

```
import electron from 'electron';
import path from 'path';
import url from 'url';

const Browser = electron.BrowserWindow;
const app = electron.app;

let mainWindow;

const appReadyEvent = () => {
  mainWindow = new Browser({
    minWidth: 1024,
    minHeight: 600,
    width: 1024,
    height: 600
  });

  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'main.html'),
    protocol: 'file',
    slashes: true
  }));
}

app.on('ready', appReadyEvent);

app.on('window-close-all', () => {
  app.quit();
});
```

the problem still persists.

**Comment by four-eyes-04-04** [comment]
I created a repo for it at https://github.com/four-eyes-04-04/1-helloworld-electron

**Comment by four-eyes-04-04** [comment]
After reading [https://github.com/electron/electron/issues/405#issuecomment-46930226](this comment) at issue #405, I was able to solve the problem, seems that `window-close-all` is actually `window-all-closed`, so to remove the processes hanging around when the application was closed, you need to do this.

```
app.on('window-all-closed', () => {
  app.quit();
});
```

**Comment by MadDevl** [comment]
I had the same issue for a child process that didn't exit on when app.quit() was called. 

Below was the solution that worked for me (Quick sample code)

```
import {ChildProcess} from 'child_process'
import {app, BrowserWindow} from 'electron'

let childProcess: ChildProcess | null = null // Store the childProcess to kill it later when window is closed.
let win: BrowserWindow | null = null

app.whenReady().then(()=>{
 
// initialize the electron window and add your code here to start the child process
// childProcess = startChildProcess()

// define here to kill child process
 win.on('closed', () => {
    win = null
    if (childProcess) {
      console.log('Killing backend process...')
      childProcess.kill('SIGTERM')
      childProcess= null
      console.log('Backend process killed.')
    }
    app.quit()
  })
})

```
