### ISSUE TITLE
iframe and webview not working properly

### ISSUE THREAD

**Issue by yoshifan509** [electron/electron#9866]
Hi. I am making an app using the latest (stable) version of electron and i need to use the <webview> tag
* Electron version: 1.6.11
* Operating system: macOS 10.12.5

### Expected behavior

The webview should be taking up the right amount of space on the page. Basically the webview isnt taking up the specified px.
### Actual behavior
Takes up the whole width of the window.

### How to reproduce
https://github.com/yoshifan509/Roblox-Desktop-Launcher

**Comment by MarshallOfSound** [comment]
In your code you are not declaring the width of the webview, you should use CSS to make the webview's with `100%`.

https://github.com/yoshifan509/Roblox-Desktop-Launcher/blob/master/index.html#L4

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
