### ISSUE TITLE
Support printing in landscape from API

### ISSUE THREAD

**Issue by timfish** [electron/electron#9868]
Currently there is no way to force printing into landscape. This means I have to offer my users portrait/landscape choice in the UI so I can render my print output for the correct size and then hope the user goes into their printer settings after printing has been triggered to choose landscape there too.

**Comment by enlight** [comment]
You should be able to force landscape via CSS, is it not working for you?

**Comment by timfish** [comment]
Using:
```css
@media print {  @page {size: landscape}  }
```
does actually override the orientation used for `webContents.printToPDF` but when I `webContents.print`  the content is on a portrait page. 

This is because electron is not overriding the printer default preferences:
![image](https://user-images.githubusercontent.com/1150298/27577465-0ba75d44-5b21-11e7-88a0-17a404208d71.png)

Print in Chrome and you never get to this dialog as you choose the printer in the Chrome UI.

**Comment by timfish** [comment]
Tested on macOS and its the same there too.

**Comment by timfish** [comment]
I suppose this can be duplicate of https://github.com/electron/electron/issues/9868
