### ISSUE TITLE
Component does not unmount on App Close/Before-Quit event.

### ISSUE THREAD

**Issue by akshaygore06** [electron/electron#9871]
I am working on the video player app in the electron. I want to save the progress of the video. When the user quits the app using "X" button or the CMD + Q. App closes without unmounting Video Payer Component which does not allow to save the progress of the video.

**Comment by MarshallOfSound** [comment]
@akshaygore06 This is an issue with whatever library you are using (sounds like react).  You can listen for unload event instead for when the page is being closed.

```js
window.addEventListener('beforeunload', () => {
  // Save stuff syncronously
});
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
