### ISSUE TITLE
Please add Notification usage example to main process documentation

### ISSUE THREAD

**Issue by naheller** [electron/electron#9872]
The [renderer](https://github.com/electron/electron/blob/master/docs/tutorial/notifications.md) process documentation page contains some sample code that got me up and running, but the [main](https://github.com/electron/electron/blob/master/docs/api/notification.md) process documentation contains no such samples. 

As a new developer, I can really benefit from examples, and the link to the NodeJS [Events](https://nodejs.org/api/events.html#events_class_events_eventemitter) documentation is quite verbose and I haven't been able to extract the information I need.

I've attempted to use the syntax from the renderer process construction in my main process, as shown below:

`const Notification = require('electron')`
```
let myNotification = new Notification('Title', {
      body: 'Lorem Ipsum Dolor Sit Amet'
    })
myNotification.show()
```

However this causes the error: 
`Uncaught Exception: TypeError: Notification is not a constructor`

What is the correct syntax for constructing a Notification in the main process? 
Your advice is appreciated!

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

Please note you have to be on the latest beta to get the `Notification` class in the main process.

To fix your code you simply need to use destructuring when requiring electron.

`const { Notification } = require('electron')`

**Comment by naheller** [comment]
Thank you for your reply!

I'd like to request the following feature: Notification usage example(s) in [main process](https://github.com/electron/electron/blob/master/docs/api/notification.md) documentation
