### ISSUE TITLE
app.makeSingleInstance doesn't work under linux, Electron 1.7.x

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#9880]
* Electron version: 1.7.x
* Operating system: Linux

Works in 1.6.11.

### Expected behavior

`app.makeSingleInstance` callback is called when opening an associated file from file manager and application is already opened

### Actual behavior

`app.makeSingleInstance` callback is delayed with about 30-60 seconds before being called

### How to reproduce

You could reproduce the problem by downloading [Caret 3.0 .deb](https://github.com/careteditor/caret/releases/tag/3.0.0) and then following the steps described [here](https://github.com/careteditor/caret/issues/399).

The issue stops reproducing when releasing the same code with 1.6.11.

**Comment by Thomas101** [comment]
We're seeing exactly the same issue here https://github.com/wavebox/waveboxapp/issues/284

**Comment by Thomas101** [comment]
I've just added a super simple example into git demonstrating the bug...

```
git clone https://github.com/wavebox/electron-quick-start.git
cd electron-quick-start
git checkout singleinstance-bug
npm install
npm start
```
Then in a new terminal....
```
npm start
```

**Comment by astoilkov** [comment]
@Thomas101 Thanks a lot for helping out with a simple example.

**Comment by enlight** [comment]
May be related to #9965 and #9576.

**Comment by MarshallOfSound** [comment]
Something somewhere in https://cs.chromium.org/chromium/src/chrome/browser/process_singleton_posix.cc?dlp=chromium&dlf=src/chrome/browser/process_singleton_posix.cc&dlc=d2c61e49116e9936be53e6f326cf702838ca73fa&dlr=142&dlgp=chrome/browser/process_singleton_posix.cc&dlgr=chromium/chromium/src&drp=chromium&drf=src/chrome/browser/process_singleton_posix.cc&drc=65ef3a7c2973fc9aef9a338640b52750fc82c5a1&drr=148&drgp=chrome/browser/process_singleton_posix.cc&drgr=chromium/chromium/src

**Comment by mattridley** [comment]
I am seeing the same thing in macOS. Is there a separate issue tracking that or do the labels and title of this just need updating?

**Comment by Thomas101** [comment]
@mattridley we're not seeing it with macOS or Windows only linux. Which version of electron did you see it with? Do you see the problem if you try it with the electron-quick-start above? https://github.com/electron/electron/issues/9880#issuecomment-311649579

**Comment by mattridley** [comment]
I saw it with 1.7.5 (reverting back to 1.6.11 fixes the issue). I also have the problem with the quick start (see https://youtu.be/CNFhWWF77Ms)
