### ISSUE TITLE
Support promises for all asynchronous methods

### ISSUE THREAD

**Issue by zeke** [electron/electron#9882]
Promises are a convenient alternative to callbacks, and have become increasingly popular for writing maintainable asynchronous JavaScript code. Rather than adding Promise support one method at a time, we want to enable Promises for _all_ Electron methods that take a `callback` parameter.

Using the new [util.promisify](https://nodejs.org/en/blog/release/v8.0.0/#improved-support-for-promises) in Node 8, we can make all asynchronous methods support Promises while continuing to support the existing [node-style callbacks](https://github.com/maxogden/art-of-node#callbacks). This will allow us to support Promises without the need for a major version bump.

Our current plan is to wait until Electron bundles Node 8, so we can get the built-in `promisify` method without adding any new dependencies.

## Methods

The following is a list of all methods that take a parameter named `callback`:

- [ ] [app.getFileIcon(path[, options], callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/app.md#getFileIcon)
- [ ] [app.makeSingleInstance(callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/app.md#makeSingleInstance)
- [ ] [app.importCertificate(options, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/app.md#importCertificate)
- [ ] [win.hookWindowMessage(message, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/browser-window.md#hookWindowMessage)
- [ ] [win.capturePage([rect, ]callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/browser-window.md#capturePage)
- [ ] [request.write(chunk[, encoding][, callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/client-request.md#write)
- [ ] [request.end([chunk][, encoding][, callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/client-request.md#end)
- [ ] [contentTracing.getCategories(callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/content-tracing.md#getCategories)
- [ ] [contentTracing.startRecording(options, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/content-tracing.md#startRecording)
- [ ] [contentTracing.stopRecording(resultFilePath, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/content-tracing.md#stopRecording)
- [ ] [contentTracing.startMonitoring(options, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/content-tracing.md#startMonitoring)
- [ ] [contentTracing.stopMonitoring(callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/content-tracing.md#stopMonitoring)
- [ ] [contentTracing.captureMonitoringSnapshot(resultFilePath, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/content-tracing.md#captureMonitoringSnapshot)
- [ ] [contentTracing.getTraceBufferUsage(callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/content-tracing.md#getTraceBufferUsage)
- [ ] [cookies.get(filter, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/cookies.md#get)
- [ ] [cookies.set(details, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/cookies.md#set)
- [ ] [cookies.remove(url, name, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/cookies.md#remove)
- [ ] [cookies.flushStore(callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/cookies.md#flushStore)
- [ ] [debugger.sendCommand(method[, commandParams, callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/debugger.md#sendCommand)
- [ ] [desktopCapturer.getSources(options, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/desktop-capturer.md#getSources)
- [ ] [dialog.showOpenDialog([browserWindow, ]options[, callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/dialog.md#showOpenDialog)
- [ ] [dialog.showSaveDialog([browserWindow, ]options[, callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/dialog.md#showSaveDialog)
- [ ] [dialog.showMessageBox([browserWindow, ]options[, callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/dialog.md#showMessageBox)
- [ ] [dialog.showCertificateTrustDialog([browserWindow, ]options, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/dialog.md#showCertificateTrustDialog)
- [ ] [globalShortcut.register(accelerator, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/global-shortcut.md#register)
- [ ] [protocol.isProtocolHandled(scheme, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/protocol.md#isProtocolHandled)
- [ ] [ses.getCacheSize(callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/session.md#getCacheSize)
- [ ] [ses.clearCache(callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/session.md#clearCache)
- [ ] [ses.clearStorageData([options, callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/session.md#clearStorageData)
- [ ] [ses.setProxy(config, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/session.md#setProxy)
- [ ] [ses.resolveProxy(url, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/session.md#resolveProxy)
- [ ] [ses.clearHostResolverCache([callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/session.md#clearHostResolverCache)
- [ ] [ses.getBlobData(identifier, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/session.md#getBlobData)
- [ ] [ses.clearAuthCache(options[, callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/session.md#clearAuthCache)
- [ ] [shell.openExternal(url[, options, callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/shell.md#openExternal)
- [ ] [systemPreferences.subscribeNotification(event, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/system-preferences.md#subscribeNotification)
- [ ] [systemPreferences.subscribeLocalNotification(event, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/system-preferences.md#subscribeLocalNotification)
- [ ] [contents.executeJavaScript(code[, userGesture, callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/web-contents.md#executeJavaScript)
- [ ] [contents.getZoomFactor(callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/web-contents.md#getZoomFactor)
- [ ] [contents.getZoomLevel(callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/web-contents.md#getZoomLevel)
- [ ] [contents.capturePage([rect, ]callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/web-contents.md#capturePage)
- [ ] [contents.hasServiceWorker(callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/web-contents.md#hasServiceWorker)
- [ ] [contents.unregisterServiceWorker(callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/web-contents.md#unregisterServiceWorker)
- [ ] [contents.printToPDF(options, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/web-contents.md#printToPDF)
- [ ] [contents.beginFrameSubscription([onlyDirty ,]callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/web-contents.md#beginFrameSubscription)
- [ ] [contents.savePage(fullPath, saveType, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/web-contents.md#savePage)
- [ ] [webFrame.executeJavaScript(code[, userGesture, callback])](https://github.com/electron/electron/blob/v1.6.11/docs/api/web-frame.md#executeJavaScript)
- [ ] [webviewTag.executeJavaScript(code, userGesture, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/webview-tag.md#executeJavaScript)
- [ ] [webviewTag.printToPDF(options, callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/webview-tag.md#printToPDF)
- [ ] [webviewTag.capturePage([rect, ]callback)](https://github.com/electron/electron/blob/v1.6.11/docs/api/webview-tag.md#capturePage)

For the code that generated the list above, see [zeke/find-electron-async-methods](https://github.com/zeke/find-electron-async-methods/blob/master/index.js)

**Comment by MarshallOfSound** [comment]
@zeke `util.promisify` expects a callback in the format `(err, value) => void` lots of our callbacks don't use `err` and are simply `(value) => void`.  In order to make our callbacks promisify compatible it would be a breaking change to the callback (which I think we should do anyway) but this might be something that has to go into the 2.0 bucket

**Comment by KagamiChan** [comment]
How about providing Electron's own promisify helper method for `(value) => `? We could map it to `util.promisify` when we reach 2.0

**Comment by zeke** [comment]
> lots of our callbacks don't use `err` and are simply `(value) => void`

Good point. I thought those functions generally had names other than `callback` though. I will dig in see if I can isolate a list of those functions.

**Comment by miniak** [comment]
@zeke, app.makeSingleInstance cannot be promisified as the callback is called multiple times

**Comment by parro-it** [comment]
Others functions , like the various `executeJavaScript` methods, already return promises.

**Comment by zeke** [comment]
A suggestion from @kevinsawicki:

> For 2.0, make every callback node-style with an error argument

**Comment by damianobarbati** [comment]
+999 !!! 🙏

**Comment by psychowico** [comment]
as Electron 4 is here, based on `node@10.11.0`, maybe it's time to back to the topic?

**Comment by MarshallOfSound** [comment]
Closing this out as the Promisification effort has been completed. 🎉 

Huge shoutout to all involved in the conversions escpecially @codebytere who did a decent amount of the conversion work.

Refs: https://github.com/electron/electron/blob/master/docs/api/modernization/promisification.md
