### ISSUE TITLE
Module to get mouse events in screen

### ISSUE THREAD

**Issue by TheRolfFR** [electron/electron#9884]
Hello,
I am currently looking for a module that can give mouse button stats in screen.
Do someone know one ?

Thanks in advance.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
