### ISSUE TITLE
Prevent process termination / automatically restart application on termination

### ISSUE THREAD

**Issue by basiclaser** [electron/electron#9887]
I'm not using any electron version and im going to be building for Mac.

### Expected behavior
I would like to be able to prevent the user from quitting the application / terminating the process, or at least have a mechanism of automatically restarting the application no matter the user kills it. 

### Actual behavior
I'm not sure how to achieve this or if it is even allowed on OSX!

###

Thankyou

**Comment by MarshallOfSound** [comment]
In one sense you're describing a form of malware 😆 

You can stop your app terminating with the `will-quit` event though https://electron.atom.io/docs/api/app/#event-will-quit

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
