### ISSUE TITLE
login event not emitted for WebSocket connections

### ISSUE THREAD

**Issue by nkt** [electron/electron#9897]
* Electron version: 1.6.11
* Operating system: OSX/Windows

### Expected behavior
When websocket connection requires proxy auth `login` event would be emitted.

### Actual behavior

Nothing happens, websocket fails.

### How to reproduce

Start http(s) proxy, start app using `electron app/ --proxy-server=<proxy>`, load any site which uses websockets.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
