### ISSUE TITLE
Accelerator cannot be a combination of modifier keys

### ISSUE THREAD

**Issue by thomaslule** [electron/electron#9900]
* Electron version: 1.6
* Operating system: windows 10

I can't register a combination of modifiers as a global shortcut.

When doing:  `globalShortcut.register( "Shift+Super", someFunction );` I expect to have the function assigned to the Shift + Super key combination, but I get the following error:
`TypeError: Error processing argument at index 0, conversion failure from Shift+Super`

From my experiments we get this error everytime the shortcut is a combination of modifier keys only.

I don't think it's an OS limitation because I can assign the shortcut in another software.

**Comment by parro-it** [comment]
> I don't think it's an OS limitation because I can assign the shortcut in another software.

Are you sure this software is registering a global system shortcut? 

On my elementaryOS linux, <kbd>Shift+Super</kbd> is not accepted as a global system key (by the OS, not by electron).

Applications could however detect for such shortcut. E.g. in a browser if you listen for the `keydown` event, you'll receive a KeyboardEvent object containing these properties:

```js
{
code: "MetaLeft",
shiftKey: true
}
```

**Comment by thomaslule** [comment]
> Are you sure this software is registering a global system shortcut?

Yes! But I'm on windows.

**Comment by h93xV2** [comment]
Tested this using Electron v1.6.11 on Fedora 25 and got the same error shown in the original comment. 

I am fairly certain that the reason for this error comes from Chromium since it handles global shortcuts [see here](https://github.com/electron/electron/tree/master/chromium_src/chrome/browser/extensions), but I could be wrong.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
