### ISSUE TITLE
Docs, usage examples, basic configuration guide for Native pdf viewer integration

### ISSUE THREAD

**Issue by paulbennet** [electron/electron#9901]
* Electron version: 1.6.11
* Operating system: macOS

Its really tough setting up the native pdf-viewer. Doesn't seems to work at all. Can someone post some basic guide for setting it up ? please ?

Some simple guideline questions ..

- Should "plugins: true" should be given in webPreferences ?
- Should pepper flash plugin should be added ?

cc @deepak1556

**Comment by obermillerk** [comment]
Bump.

* Electron version: 1.7.6
* OS: Windows 10

**Comment by obermillerk** [comment]
So I figured out how to get it to work, you need to have `webPreferences: { plugins: true }` in the options passed to the window when it's created and then calling `win.loadURL('file://C:/Path/To/my.pdf');` works.
