### ISSUE TITLE
Wrong showOpenDialog TypeScript declaration

### ISSUE THREAD

**Issue by pravdomil** [electron/electron#9906]
* Electron version: 1.6.10
* Operating system: macOS

### Expected behavior
electron.d.ts line 2239 should be
showOpenDialog(options: OpenDialogOptions, callback?: (filePaths: string[]) => void): string[] | undefined

showOpenDialog returns String[], an array of file paths chosen by the user, if the callback is provided or if user cancel dialog it returns undefined

### Actual behavior
electron.d.ts line 2239 is
showOpenDialog(options: OpenDialogOptions, callback?: (filePaths: string[]) => void): string[]

### How to reproduce
npm i electron

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by EthanSK** [comment]
Still returns void!!

**Comment by MarshallOfSound** [comment]
@EthanSK I checked our latest definition --. https://unpkg.com/electron-nightly@8.0.0-nightly.20190818/electron.d.ts and it appears to have the correct return types there 🤔
