### ISSUE TITLE
require('electron').webContents returns undefined

### ISSUE THREAD

**Issue by Morphexe** [electron/electron#9907]
* Electron version: 1.64
* Operating system: Windows 10

 I am trying to get all the WebContents on the current inside a React Component (  am trying  to mirror all the user inputs on a webview and send them to the other webview with the same page loaded via the sendInputEvent from webcontents, all was fine and dandy until I tried to get the webContents to catch the "before-input".

### Expected behavior

 ```
 const contents= window.require('electron').webContents;
var all =  contents.getAllWebContents(); 

```

### Actual behavior
contents is undefined and the method callfails

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by Morphexe** [comment]
I am retarded, and way too tired, 

ts= window.require('electron').remote.webContents; does work as expected -.-
Sorry about this

**Comment by thecyberd3m0n** [comment]
> I am retarded, and way too tired,
> 
> ts= window.require('electron').remote.webContents; does work as expected -.-
> Sorry about this

I was tired too. Thanks ;)
