### ISSUE TITLE
Error processing argument at index 0, conversion failure from null

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#9908]
* Electron version: 1.7.x (I think this never worked)
* Operating system: macOS Sierra

### Expected behavior

Executing a method to not throw exception when window is out of focus.

### Actual behavior

Executing `new (require('electron').remote.Menu)).popup()` in the renderer process or `new (require('electron').Menu)).popup()` in the main process while application is not focused throws `Error processing argument at index 0, conversion failure from null`.

### How to reproduce

1. Focus an Electron app and open DevTools
2. Paste the following code `setTimeout( () => (new (require('electron').remote.Menu)).popup(), 4000);`
3. Immediately blur the application and wait for 4 seconds
4. Return back - the error have been thrown

**Comment by astoilkov** [comment]
Yes, it does. I just tested in 2.0.0. Can you reopen the issue?

**Comment by MarshallOfSound** [comment]
This is actually just a documentation issue.  The `BrowserWindow` option for the `popup` window is declared optional, but it's actually required.  The only reason it's optional is that it defaults to the focused window, you've discovered that when there is no window provided and no focused window it will throw an error.

https://electronjs.org/docs/api/menu#menupopupoptions

**Comment by astoilkov** [comment]
Does it make sense to not show the popup at all when there is no focused window?

**Comment by MarshallOfSound** [comment]
@astoilkov That should be up to user code IMO, because you can manually pass an un-focused window to that API to popup the menu
