### ISSUE TITLE
Cannot find npm module

### ISSUE THREAD

**Issue by cjg125** [electron/electron#9909]
My package.json

```js
{
"scripts": {
    "start": "electron .",
    "build": "electron-packager . myapp --out=.. --platform=mas --arch=x64 --overwrite --icon=public/icon.icns"
  },
 "devDependencies": {
    "electron": "^1.6.11",
    "electron-packager": "^8.7.2",
  },
  "dependencies": {
    "user-home": "^2.0.0"
  }
}
```
execute command
```sh
$ npm run build
```

run app
Developer Tools Tips:
Cannot find module 'user-home'

**Comment by craftpip** [comment]
Did you run `npm install` after adding into your package.json ?

**Comment by cjg125** [comment]
@craftpip  thanks ~ 

test
[example](https://github.com/cjg125/electron-myapp)

**Comment by parro-it** [comment]
@cjg125 is your problem solved by this tip?

**Comment by cjg125** [comment]
@parro-it  examples of problems ~:joy:

**Comment by pierreneter** [comment]
I try run `npm install` and run your example by `npm start` but no errors occurred.

**Comment by pierreneter** [comment]
I tried run `npm install` and run your example by `npm start` but no errors occurred.

**Comment by cjg125** [comment]
@pierreneter   ~ 

have a try
```js
$ npm run build
```
run the app

**Comment by pierreneter** [comment]
`npm run build` is run okay on my Mac, can you provide more information?

**Comment by cjg125** [comment]
oh ~~~ no ~~~
I'm found the problem

I use yarn ~~

```sh
$ yarn
$ yarn run build
```
:cold_sweat:
