### ISSUE TITLE
Electron builds are not available on platform: android

### ISSUE THREAD

**Issue by dantrevino** [electron/electron#9910]
12772 verbose     <https://github.com/npm/npm/issues>
12773 verbose stack Error: electron@1.6.11 postinstall: `node install.js`                                                                12773 verbose stack Exit status 1
12773 verbose stack     at EventEmitter.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
12773 verbose stack     at emitTwo (events.js:106:13)                                                                                    12773 verbose stack     at EventEmitter.emit (events.js:191:7)
12773 verbose stack     at ChildProcess.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12773 verbose stack     at emitTwo (events.js:106:13)                                                                                    12773 verbose stack     at ChildProcess.emit (events.js:191:7)
12773 verbose stack     at maybeClose (internal/child_process.js:877:16)
12773 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)                                         12774 verbose pkgid electron@1.6.11
12775 verbose cwd /data/data/com.termux/files/home
12776 error Linux 3.4.108-g64375a4                                                                                                       12777 error argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "install" "electron"
12778 error node v6.9.3
12779 error npm  v3.10.10                                                                                                                12780 error code ELIFECYCLE
12781 error electron@1.6.11 postinstall: `node install.js`                                                                               12781 error Exit status 1
12782 error Failed at the electron@1.6.11 postinstall script 'node install.js'.                                                          12782 error Make sure you have the latest version of node.js and npm installed.
12782 error If you do, this is most likely a problem with the electron package,
12782 error not with npm itself.                                                                                                         12782 error Tell the author that this fails on your system:
12782 error     node install.js
12782 error You can get information on how to open an issue for this project with:                                                       12782 error     npm bugs electron
12782 error Or if that isn't available, you can get their info via:                                                                      12782 error     npm owner ls electron
12782 error There is likely additional logging output above.                                                                             12783 verbose exit [ 1, true ]
$

**Comment by MarshallOfSound** [comment]
Not sure what you're expected behavior is here, Electron only supports desktop OS's (mac, windows and linux)

See #9162 regarding android discussions
