### ISSUE TITLE
electron does not disable sound for incoming notifications

### ISSUE THREAD

**Issue by akashnimare** [electron/electron#9913]
Electron version - 1.6.8

How to reproduce - load `https://www.messenger.com` in the browser window and disable sound. On the other side, chrome does disable sound for incoming notifications.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
