### ISSUE TITLE
Crashing on content heavy website.

### ISSUE THREAD

**Issue by maxcr** [electron/electron#9917]
I made a video to show the error.

https://www.youtube.com/watch?v=Nn5w-z7-1V4

You don't have to set cookies for it to crash. Once you navigate to their landing page and click or do absolutely anything else it will crash electron.

```
var Nightmare = require('nightmare'),
    nightmare = Nightmare(
        { show: true,
            webPreferences: {
                webSecurity:false
            },
            openDevTools: {
              mode: 'detach'
            },
            switches: {
              'ignore-certificate-errors': true
            }
        }),
    { readFileSync, writeFileSync } = require('fs'),
    iframe = require('nightmare-iframe-manager')(Nightmare);


var credentials = readFileSync('./cookies.txt', { encoding: 'utf8' }).trim();
credentials = JSON.stringify(credentials);
var jcred = JSON.parse(credentials);
console.log(jcred);

    nightmare
      .useragent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0')
      .goto('https://www.aliexpress.com')
      .cookies.set(jcred)
      .refresh()
      .wait(10000)
      .end()
      .then(function (result) {
        console.log(result);
      })
      .catch(function (error) {
        console.error('Search failed:', error);

      nightmare.end();
```

I made a duplicate of this issue in the Nightmare repo but this seemed to be more of an electron issue than a nightmare one since this exact same code worked before.

**Comment by maxcr** [comment]
After a bunch of reading I've been able to see other users have the same problem that I do when using electron on a page that never actually 'finishes' loading or is very content heavy. I switched to the 32 bit version of electron as suggested in the other issue but it did not fix for me. Anybody have any suggestions?

**Comment by tlgreg** [comment]
Not sure how nightmare displays the page, but I tried opening your example heavy site both with `BrowserWindow.loadURL()` and in a `<webview>` and no crash.
`Electron: 1.7.4`@`OS: Windows 8.1 x64`

**Comment by cifratila** [comment]
@tlgreg looks like a Linux issue.

@maxcr I don't think loading external websites in Electron should be a good practice, plus ones that you don't control. Electron is not a browser...

CC:
@kevinsawicki @groundwater

**Comment by DeerMichel** [comment]
Closing this issue since there has not been any recent activity. Furthermore, we don't offer support for v1 anymore. If the problem persists under current versions and is still relevant, feel free to open a new issue. Although I agree on @cifratila that Electron is not a browser.
