### ISSUE TITLE
how to get the data from windows service application or some windows exe by using C# ?

### ISSUE THREAD

**Issue by w8w8w8** [electron/electron#9921]
I have some service and exe . if I use electron create app, and how to get the data from service !?

* Electron version:
* Operating system:

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
