### ISSUE TITLE
How to get System print List

### ISSUE THREAD

**Issue by zhoufeifan** [electron/electron#9922]
I can't find the function that could get print list in the docs。I think it is important for developers.could you add this function ?

**Comment by enlight** [comment]
What is a "print list"? A list of printers, a list of documents in the print queue, or...?

**Comment by zhoufeifan** [comment]
Sorry, it means a list of printers, I want to choose a printer to print  but not default printer.

**Comment by renaesop** [comment]
see #9712

**Comment by ziedhajsalah** [comment]
I think it's available only since version 1.7.2 which is still in beta.
See [here](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsgetprinters)

**Comment by enlight** [comment]
Closing since this feature was released in 1.7.2.
