### ISSUE TITLE
Process not getting destroyed in windows 7 32bit system

### ISSUE THREAD

**Issue by rishabh1403** [electron/electron#9923]
* Electron version: 1.6.8
* Operating system: Windows 7 32bit

I have an app where we open new windows and close them very frequently. Ideally On closing the window the process related to it should close/destroy. This works fine on macos as well as ubuntu while on windows 7 sometimes the process doesn't get destroyed which hangs the application eventually.

**Comment by shubham2892** [comment]
@rishabh1403 Can you provide a minimal example with steps to reproduce the issue. Thanks!

**Comment by Skizu** [comment]
I had that issue where ipc responses were not sent, simply sending back a null before closing resolved this issue for me.

**Comment by rishabh1403** [comment]
Cannot provide repo access due to company's restriction, will try your suggestion @Skizu , Thanks 👍
