### ISSUE TITLE
Question - How to launch browserWindow when webpack completes its build?

### ISSUE THREAD

**Issue by saadbinsaeed** [electron/electron#9924]
Just a question

I have posted it on stackoverflow but didn't get any response this is why posting here.

I am developing a desktop application on electron using react, redux, webpack. Sometimes electron's browser window launches when application completely compiled by webpack but sometime it launches first, shows the blank white screen while webpack builds the app. Then i have to manually refresh the app to show its content.

* Electron version 1.6.1:
* Operating system 16.0.4:

### Expected behavior

Browser Window should open when webpack completes it build

### Actual behavior

Browser window opens first shows the blank white screen while webpack building the app, have to manually refresh the app when build finished to show the application's content

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
