### ISSUE TITLE
open-file event is not fired when app is not running

### ISSUE THREAD

**Issue by jakubzitny** [electron/electron#9925]
* Electron version: 1.6.2
* Operating system: macOS Sierra 10.12.5

### Expected behavior

The `open-file` event is supposed to work for both cases when app is running and also when it's not. According to [the docs](https://github.com/electron/electron/blob/master/docs/api/app.md#event-open-file-macos), the event is:
> Emitted when the user wants to open a file with the application. The open-file event is usually emitted when the application is already open and the OS wants to reuse the application to open the file. open-file is also emitted when a file is dropped onto the dock and the application is not yet running. Make sure to listen for the open-file event very early in your application startup to handle this case (even before the ready event is emitted).

### Actual behavior

There have already been some issues (#4403) when this did not work for people, but it was always closed as they did not have proper definitions in `Info.plist` or so.

We are registering `open-file` and `open-url` very very early in the app startup. It is actually the first thing we do. `open-url` is working when the app is of but the `open-file` is not even fired. We do have proper stuff in `Info.plist` because it works for us when the app is running. In our `CFBundleDocumentTypes` we have the proper stuff, the icon even dimms when the file is dropped:

```
<dict>
  <key>CFBundleTypeExtensions</key>
  <array>
    <string>json</string>
  </array>
  <key>CFBundleTypeName</key>
  <string>JSON Data</string>
  <key>CFBundleTypeRole</key>
  <string>Viewer</string>
  <key>LSTypeIsPackage</key>
  <integer>0</integer>
</dict>
```

### How to reproduce

I will try to create a minimal repository and build where `open-url` works and `open-file` does not. I just hope that there is something that I am missing to make this work, I am following the docs precisely so if there is anything more to set up, we should add it to docs. If not, I would like to see and example of a project where this actually works, because I just ran into this for the second time.

**Comment by jakubzitny** [comment]
Allright, I managed to solve this, sorry for false alarm. The actual problem was in sending the filePath from 'open-file' event to renderer via IPC. I was doing it too early.

What I do now is that I only push the filePath from `open-file` to array. And when the app window is ready, I send the array for handling there.

**Comment by jakesyl** [comment]
When you say to early, do you mean before `will-finish-launching` was fired? We're having trouble with this on #4403

**Comment by jakubzitny** [comment]
@jakesyl We're handling it separately before app is 'ready' and after that. Before, we just push it to array in main process. After app is 'ready' that we emit ipc event to our app (with the array or subsequent file-opens.) Don't forget about having right stuff in plist.

**Comment by payitforwardnow** [comment]
I've tried putting the open-file event hook before and after the app being ready and I'm experiencing the problem as described in #4403. If I open the app from the Applications folder (or from the Dock) the open-file event never fires when I try to open a file of a type that the app supports using FileAssociations and context menu. Drag-n-drop does fire the open-file event. If I open the app by double clicking on a supported file prior to using the context menu it seems to work. I see that this issue and #4403 have been closed but I don't see a posted solution. The info.plist looks correct and in fact I am able to see my app when I use the Open With context option. The issue apparently has something to do with how the app was opened. Any assistance would be appreciated as I only have a few strands of hair remaining in my head :) Thank you in advance for your time and consideration.

**Comment by payitforwardnow** [comment]
Its August of 2018. Maybe this issue has re-appeared. Should I create a new "ticket"? Just to clarify. There is only one way I can get the open-file event to fire as explained in the documentation. If my app is NOT running and I open a file using the Open With option from the context menu the app launches and everything works going forward. I can open additional files using Open With and all is good. The problem occurs if my app was launched by a) double clicking on a file where my app is the default viewer, b) launching my app from the Applications folder, c) launching my app from the Dock or d) launching the app via drag-n-drop. If my app is launched using a-d above I can no longer use the Open With context option. I can however double click on a file where my app is the default viewer and that still works. Again, this issue appears to be related to 1) The way in which the app is launched initially and 2) the Open With context option. I hope this helps. Any assistance or additional things to try would be appreciated. Thank you in advance for your time and consideration.

**Comment by ckerr** [comment]
Yes I'd recommend opening a new ticket is filed because we're looking at a new version now and the regression may have a different cause.

When filing a new issue, would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

Thanks in advance!

**Comment by payitforwardnow** [comment]
I will create a new ticket and I will provide a sample. I'm new to github so "forking" something is not something I know how to do but I will learn :) I have found other issues so I best get "forking" busy.
