### ISSUE TITLE
showInactive() not working as expected on Windows 7

### ISSUE THREAD

**Issue by pabloleban** [electron/electron#9930]
* Electron version: 1.7.4
* Operating system: Windows 7

### Expected behavior

Show the `BrowserWindow` behind the window im working with.

### Actual behavior

It brings the BrowserWindow on top of everything, just like a `BrowserWindow.show()` but without focus which makes the application kind of annoying.

If I don't maximize the BrowserWindow, then it works as expected, so it's something related with the `BrowserWindow.maximize()` feature.

I don't know if it's only a Windows 7 issue, or it happens in any other OS. 

### How to reproduce

1. Create a new `BrowserWindow`.
2. Maximize it with `BrowserWindow.maximize()`
3. Hide it with `BrowserWindow.hide()`
4. Focus any other window.
5. Then call `BrowserWindow.showInactive()`
6. The `BrowserWindow` will be displayed on top of every other window, without focus.

**Comment by parro-it** [comment]
> Then call BrowserWindow.showInactive()
The BrowserWindow will be displayed on top of every other window, without focus.

What are you expecting here? From BrowserWindow docs:

```
win.showInactive()
Shows the window but doesn’t focus on it.
```

**Comment by pabloleban** [comment]
> It brings the BrowserWindow on top of everything

If the user is working with another thing, for instance, browse in the web, and the `BrowserView` is hidden because he closed it, **I want to show it without popping up in the top of everything**. I just want to just show it so he can have access to it whenever he wants to.

**Comment by pabloleban** [comment]
Here's a little sketch I made to understand the behaviour that occurs in Electron.

![Cases](http://i.imgur.com/Tnpfchi.png)

**Comment by parro-it** [comment]
Thank you for clarify, @pabloleban.
Anyway, on macOS I always get the situation of your second use case,  even if I don't call `maximize`.  And it was what I expected by reading the docs...

So, maybe may be more appropriate to ask for a new method?

**Comment by pabloleban** [comment]
@parro-it Thanks for your reply! I thought that this behaviour was only ocurring in Windows 7. I will close this issue and create another one for the requirement. Thank you again.
