### ISSUE TITLE
autoUpdater.setFeedURL appends latest-mac.json

### ISSUE THREAD

**Issue by sqwk** [electron/electron#9932]
* Electron version: 1.6.11
* Operating system: macOs 10.12.5

I have a nuts update server running that reads releases from a github repository. This works fine.
When using autoUpdater as follows:

    let platform = os.platform() + '_' + os.arch();
    let version = app.getVersion();
    autoUpdater.setFeedURL('http://someServer.com/update/channel/stable/' + platform + '/' + version);

The autoUpdater automatically appends `/latest-mac.json` to this url, which produces a 404 error. The output without the filename would have been something like this:

    {"url":"http://someServer.com/download/version/1.1.1/osx_64?filetype=zip","name":"1.1.1","notes":"- Implemented Auto Updates\n","pub_date":"2017-07-03T18:12:42.000Z"}

I thought that 'setFeedUrl()' would do just that, setting the feed url—appending `latest-mac.json` seems like a little too much magic? What file would it ask for on a windows machine? `latest-win.json`?

Is there a way to prevent the electron autoUpdater appending the `/latest-mac.json` filename to the feed url and would it actually be able to understand the above json format instead?

**Comment by MarshallOfSound** [comment]
The auto update shouldn't be appending that to the URL.  Can you please provide a code sample of how you are requiring and using the auto updater?

Also where are you seeing the request for `latest-mac.json`

**Comment by sqwk** [comment]
Turns out that the `electron-updater` package was still lingering in the codebase, which effectively overwrote electron's own autoUpdater. Removed it and works flawlessly.
