### ISSUE TITLE
desktopCapturer: MediaStream does not contain content matching chromeMediaSourceId

### ISSUE THREAD

**Issue by gregor** [electron/electron#9933]
* Electron version: 1.7.3 - not sure when this was introduced, works fine in latest production build based on 1.4.15
* Operating system: Windows

### Expected behavior

I have three screens connected to my computer. `desktopCapturer.getSources({types: ['screen']})` correctly identifies three sources.

I want to share my first screen and set `chromeMediaSourceId` to the matching id `screen:0:0` in the constraints when requesting the MediaStream using `navigator.mediaDevices.getUserMedia()`. I should get a MediaStream containing a video track with the content of the first screen.

### Actual behavior

The stream returned will show the  content of the second screen. If I ask for the second screen, I get the third screen. If I ask for the third screen, I get a black screen.

### How to reproduce

https://github.com/wireapp/wire-desktop

````
git clone https://github.com/wireapp/wire-desktop.git
npm install
npm run prod
````

* Log in or create a Wire account. Feel free to connect to me (@gregor)
* Start audio or video call
* Click on share your screen
* Select screen to be shared

![electron](https://user-images.githubusercontent.com/10243309/27835989-b897f902-60dd-11e7-8dfc-555b4958fc99.png)
![electron2](https://user-images.githubusercontent.com/10243309/27835988-b8943060-60dd-11e7-881c-f3dfdad6cc65.png)

**Comment by herrmannplatz** [comment]
Made a small example: https://github.com/herrmannplatz/electron-desktop-capture-bug

You can verify it by running it on windows.

**Comment by gregor** [comment]
@zcbenz @felixrieseberg Anyone taking a look? Do you need additional info to debug?

**Comment by gregor** [comment]
@zeke This issue is present in all versions 1.7.x and 1.8.x and is blocking us from upgrading. We are stuck with a 1.6.x build based on Chrome 56. which was released early this year. Is there anything we can do to help, to get this looked at, and addressed?

**Comment by zeke** [comment]
I've added this issue to our project prioritization board and we'll discuss it in our next meeting.

**Comment by zcbenz** [comment]
It seems to be completely broken on macOS.

**Comment by gregor** [comment]
@zcbenz Yes, macOS is not affected. On Windows it is blocking us completely though.

**Comment by alexeykuzmin** [comment]
@gregor Can you please check if it works with Electron 1.8.3?
Please reopen the issue if it doesn't. Thanks!

**Comment by gregor** [comment]
We updated our internal builds to the latest electron in https://github.com/wireapp/wire-desktop/pull/1324 and it seems to be working fine. We will do more testing and reopen in case we find anything. Seems like we can finally move away from electron 1.6.x builds.
