### ISSUE TITLE
Notification from main process does not show new icons

### ISSUE THREAD

**Issue by JBarna** [electron/electron#9935]
* Electron version: electron v1.7.4 beta
* Operating system: Windows 10 64bit

**This is an issue with the new Notification module from the main process which was added just in the electron v1.7.3 beta release** 

### Expected behavior
The Notifications should show different `nativeImage`s that are provided to them.

### Actual behavior

On Windows, consecutive Notifications will only show the icon that is passed to the first notification. 
This is the first notification
![notif1](https://user-images.githubusercontent.com/7936196/27841081-60d58344-60cc-11e7-9c4a-b7a22b57bd03.png)

and this is the second notification
![notif2](https://user-images.githubusercontent.com/7936196/27841083-6ec03d3c-60cc-11e7-828b-53269c81d618.png)

The `nativeImages` that are passed to the `Notification` module are different. The second notification is supposed to have a different picture, and if you run the `reproduce` code on a Mac you will see that the notifications have separate pictures/icons. 

### How to reproduce
* Clone repo `git clone https://github.com/JBarna/ElectronNotificationIssue.git`
* Download the latest release, 1.7.3 beta or after
* `/path/to/electron/exe /path/to/index.js`

You should not use `npm install` to retrieve the Electron binary as it will have a release before the addition of the Notification module.

**Comment by BrandonSmith** [comment]
I'm experiencing this limitation, as well.

**Comment by SavageCore** [comment]
Seems to be fixed in https://github.com/electron/electron/tree/v1.8.2-beta.1 :tada:

**Comment by JBarna** [comment]
I have verified that this was fixed with v1.8.2 beta.
