### ISSUE TITLE
Mac OSX keyboard input problem

### ISSUE THREAD

**Issue by l7s** [electron/electron#9936]
* Electron version: v1.6.11
* Operating system: OSX 10.10.4

### Expected behavior

When I run simple app as below:

main.js
```
const { app, BrowserWindow } = require('electron');

let mainWindow = null;

app.on('window-all-closed', () => {
  if (process.platform != 'darwin') {
    app.quit();
  }
});

app.on('ready', () => {
  mainWindow = new BrowserWindow({width: 800, height: 600});
  mainWindow.loadURL(`file://${__dirname}/index.html`);

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
});
```

index.html
```
<!DOCTYPE html>
<html>
  <head>
    <title>Application name</title>
  </head>
  <body>
    <form action="/">
      <input type="text">
    </form>
  </body>
</html
```

and click input field and start typing I would expect text I type to show up inside of input filed.

### Actual behavior

What actually happens is text shows up in terminal from which electron was started, see screencast below:

http://recordit.co/W9M9JN9OiN

### How to reproduce
On Mac computer:
```
  $ git clone https://github.com/level7systems/electron-osx-bug.git
  $ cd electron-osx-bug
  $ electron .
```

when app window opens click text field and start typing. Instead of text showing inside the field it will be printed in the terminal console.

Any suggestions how to fix this much appreciated.

Regards,
Chris

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
