### ISSUE TITLE
Is there a limit of performance in webgl mode?

### ISSUE THREAD

**Issue by kongyuan** [electron/electron#9938]
Electron version:   1.6.11
Operating system:   Windows 10 

I plan to make a game with phaser.io and electron.
I made a test game with 10000 physics bodys and collide eachother. 
I think this test will show performance of phaser.io and electron.

The game run at 8 fps and CPU is running under 20%, and GPU is under 10%.
I think that means electron didn't use all performance of my PC.
I tested without phaser.io, made a test like a huge loop, same result.

Is that any limit of performance in electron or chrome or v8 ?

Test code: 
  $ git clone git@github.com:kongyuan/electronIssue.git -b master
  $ electron .

**Comment by ButzYung** [comment]
A Web app like this is probably single threaded (assuming that no Web worker is used), so 20% of CPU could be maxed out already if your CPU has a lot of cores.

**Comment by kongyuan** [comment]
@ButzYung All my cpu core are under 20%, Even the temperature is low too.

**Comment by kongyuan** [comment]
My goal is my game use 100% of one CPU core. Then if I need more, I will use workers.

**Comment by tywang2006** [comment]
there are additional threads running in background with electron which is very pain for game development.
if your game is running with webgl, that is all depending on which gpu you are using. if you run the game in multiple windows, it will be a huge problem. each window has its own thread

**Comment by tingtingdisco** [comment]
Machine: new surface pro 
OS: Window 10
Electron: 1.7.6

I've got the same problem with a three.js app,  The same code run 60fps on Mac, but only 15fps on Windows. 

On Windows, running the app in chrome browser will use 20% cpu power, but running the app in electron only uses 5% cpu power.

**Comment by tingtingdisco** [comment]
solve the problem by adding

webPreferences: {
      backgroundThrottling: false
}

I think this is a bug that only Windows needs this.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
