### ISSUE TITLE
`compositionupdate` event is broken on Electron 1.6 (Chrome 56)

### ISSUE THREAD

**Issue by as-cii** [electron/electron#9939]
Refs: https://github.com/atom/atom/issues/14911.

On Atom 1.19 Beta (which runs on Electron 1.6), some users started reporting a weird behavior related to IME input. In particular, it looks like the `compositionupdate` event reports only the last character that has been typed as opposed to the whole string that's being composed by the user. This is causing a pretty bad user experience for people using non-latin languages.

This issue has already been reported on https://bugs.chromium.org/p/chromium/issues/detail?id=677050, and apparently it got fixed on Chrome >= 57. Upgrading Atom to use Electron 1.7 doesn't seem like a great option, though, especially because 1.7 is still in beta and we would like to roll out a hot-fix for this problem.

@kevinsawicki: do you think we could back port the relevant fix linked in the above Chromium Bug to Electron 1.6?

Thanks! 🙇

**Comment by kevinsawicki** [comment]
> do you think we could back port the relevant fix linked in the above Chromium Bug to Electron 1.6?

Looks like three commits are linked in https://bugs.chromium.org/p/chromium/issues/detail?id=620549 which may make backporting a bit difficult since the diff is pretty large and it isn't clear initially whether all or just some of the changes in the commits will address this issue in Atom.

**Comment by as-cii** [comment]
It seems like several users are hitting this issue on Atom, and the user experience is really unacceptable when using IME input. @groundwater: any chance we could prioritize this and backport the fix to 1.6?

**Comment by MarshallOfSound** [comment]
@as-cii Backporting a chromium fix that large to `1.6` would be quite challenging.

> especially because 1.7 is still in beta and we would like to roll out a hotfix for this problem.

`1.7.5` was recently marked as stable, so potentially the easiest solution is for atom to upgrade to that version of Electron and inherently get the fix from the Chromium upgrade between 1.6 -> 1.7?

**Comment by codebytere** [comment]
@as-cii did @MarshallOfSound's advice end up proving helpful?

**Comment by as-cii** [comment]
Yes, thanks for the heads up @codebytere! We have recently updated to Electron 1.7.11 and it works smoothly.
