### ISSUE TITLE
Electron and MITM Proxy

### ISSUE THREAD

**Issue by Devhercule** [electron/electron#9940]
Hi,

Is there any MITM Proxy (Man In The Middle) adapted with Electron?

I want to use a MITM proxy to intercept sent requests and display them..

Thank you

**Comment by kevinsawicki** [comment]
You may want to check out the `webRequest` and `protocol` APIs:

https://electron.atom.io/docs/api/protocol

https://electron.atom.io/docs/api/web-request

**Comment by Devhercule** [comment]
I have already checked and used both of "webrequest" and "protocol" APIs. This is not exactly what I'm looking for. I need to intercept requests after their send from the browser : 

> Electron browser --> MITM --> Web server

I have used 

In addition protocol have bugs, I can't use it :  https://github.com/electron/electron/issues/9895

I'm looking for a Man In The Middle proxy, not to modify request in the browser..

**Comment by P0oOOOo0YA** [comment]
@Devhercule if you still wonder take a look at [HTTP MITM Proxy](https://github.com/joeferner/node-http-mitm-proxy).
