### ISSUE TITLE
BrowserWindow.showInactive() should maintain the Z order of the Window

### ISSUE THREAD

**Issue by pabloleban** [electron/electron#9941]
* Electron version: 1.7.4
* Platform: Windows 7

So im looking a way to hide and show a `BrowserWindow` without bringing my Electron app to the top of the windows Z order.

So I was thinking that maybe `BrowserWindow.showInactive()` should do that.

Here is what I have now on Windows 7.

![Sample](https://learsoft.com/chat/resources/files/pleban/1499265622/fix.png)

On **Windows 7**, for some strange reason im having the behaviour I want. But it only works there and only if I don't maximize the `BrowserWindow`. For more information about this read this issue #9930.

As @parro-it stated on #9930:
> on macOS I always get the situation of your second use case, even if I don't call maximize

### So, the requirement
**A new method** or **a new parameter passed on `showInactive()`** or just **changing the standard behaviour of this method** to tell Electron to keep the windows Z order of the `BrowserWindow` instead of bringing it to the top level to achieve the first case of the picture.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!

**Comment by schontz** [comment]
@codebytere In my testing of Electron 18 and 23, `showInactive` is maintaining the z-index on Windows but not on Mac. Calling `moveTop` "fixes" the issue on Windows. I prefer the Mac behavior, and it matches the docs, but either way I just desire them to be consistent.
