### ISSUE TITLE
Dialogs don't respond to mouse input on Linux

### ISSUE THREAD

**Issue by craxal** [electron/electron#9942]
* Electron version: 1.7.2
* Operating system: Ubuntu 16.04

### Expected behavior

I expect the dialog to open as a modal window to the main application, responsive to mouse and keyboard input.

### Actual behavior

The dialog opens as a modal window to the main application, but it is only responsive to keyboard input (Linux only). All mouse clicks are blocked *system-wide*, not just within the Electron application. Pressing Esc closes the dialog and unlocks the mouse.

### How to reproduce
Call this function:
```ts
// In the renderer process:
import { remote } from "electron";
import * as q from "q";

function showOpenDialog(...) {
    return q.Promise((resolve, reject) => {
        var focusedWindow = remote.BrowserWindow.getFocusedWindow();
        ...
        remote.dialog.showOpenDialog(focusedWindow, ..., resolve);
    });
}
```
In most of my use cases, the mouse input is blocked. In some cases, it isn't.

I noticed that, if you open the dev tools window, drop a breakpoint in the function, and continue execution after hitting the breakpoint, mouse input works as expected. If the breakpoint is placed before the call to `getFocusedWindow`, the resulting dialog's parent window will be null (not modal). If placed after, the dialog will be modal as expected.

**Comment by craxal** [comment]
Anyone there? This is a serious blocking issue for us.

After some experimentation, I found that if you set `focusedWindow` to `null` instead, mouse input doesn't get blocked. I suspect two possibilities: (1) `getFocusedWindow` is somehow getting the wrong window (which can change within the function call, as proved by the debugging breakpoint), or (2) something is bugged in the implementation of `showOpenDialog` for Linux.

**Comment by kevinsawicki** [comment]
> Anyone there? This is a serious blocking issue for us.

Does it still happen if you call `dialog.showOpenDialog` from the main process instead of from the render process using `remote`?

**Comment by craxal** [comment]
It still repros from the `main` process.
```ts
// In the main process:
import { dialog, ipcMain } from "electron";

let mainWindow;

...

ipcMain.on("dialog-open", (event, options) => {
    dialog.showOpenDialog(mainWindow, options, (response) => {
        event.sender.send("did-dialog-open", response);
    });
});

// In the renderer process:
import { ipcRenderer} from "electron";
import * as q from "q";

function showOpenDialog(...) {
    return q.Promise((resolve, reject) => {
        ipcRenderer.send("dialog-open", ...);
        ipcRenderer.once("did-dialog-open", (response) => {
            resolve(response);
        });
    });
}


```

**Comment by edgarmedrano** [comment]
Hi, just to let you know that this bug is affecting VSCode "Spring Initializr Java Support extension" (by Microsoft). Please let me know if there is a workaround for users. I'm using Ubuntu 18.04 LTS.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
