### ISSUE TITLE
Tooltip from minimized window impossible to dismiss

### ISSUE THREAD

**Issue by juturu** [electron/electron#9943]
* Electron version: 1.7.1
* Operating system: Windows

### Expected behavior
Tooltip shouldn't be shown on the screen.

### Actual behavior
Minimize tooltip stays on the screen until electron app is brought into foreground

Same as - https://bugs.chromium.org/p/chromium/issues/detail?id=724538

### How to reproduce

Look into https://bugs.chromium.org/p/chromium/issues/detail?id=724538

**Comment by joshaber** [comment]
We're getting a good amount of these reports on GitHub Desktop.

**Comment by MilesRomney** [comment]
The current version of Slack on Windows 10 exhibits the problem as well.

**Comment by MilesRomney** [comment]
And this is interesting (I know this isn't a Slack-specific thread, but I mention this behavior in case it informs broader efforts to address this issue in Electron):

If I open the "About Slack" modal, then minimize the main window, then close the modal, I will never see the sticky "Minimize" tooltip again until Slack restart.

If, on the other hand, I close the modal while the main window is still open, then minimize it, I see the sticky tooltip.

**Comment by ChadTaljaardt** [comment]
@joshaber You can remove the message by opening the app up again and then minimising it again. 

Its a really annoying haha..

**Comment by MilesRomney** [comment]
@ChadTaljaardt in my experience that does not work, if you minimize it again using the icon.  Minimizing it via the keyboard shortcut, the menu, or clicking the application icon in the taskbar do not exhibit the problem.

**Comment by IainMNorman** [comment]
I can confirm what Miles says about Slack's client. The little about dialog trick is handy.

**Comment by amirsabanovic** [comment]
@MilesRomney There is a way of getting around it. If you hover over the Minimize icon, wait long enough for the tooltip to appear and **then** click, the tooltip won't get stuck on the screen.

**Comment by MilesRomney** [comment]
Ah, good to know, thanks.

**Comment by dac-xp** [comment]
Second workaround: You can also just press `Alt+F4` to minimize Slack.

**Comment by mcmonkey4eva** [comment]
... is that a joke or did slack really set it so that <kbd>ALT+F4</kbd> minimizes rather than closes?

**Comment by dac-xp** [comment]
Not sure if it's a setting, but for me on Windows 10 it minimizes.

**Comment by amirsabanovic** [comment]
@mcmonkey4eva `Alt+F4` actually closes the app window, but it doesn't end the app process, and you can easily open it up again from the tray menu.

**Comment by pomber** [comment]
Another workaround: minimize it by clicking on the task bar icon.

**Comment by brenca** [comment]
This is a bit tricky to test, but I couldn't reproduce this with the fix I posted.

**Comment by kyleboddy** [comment]
![image](https://user-images.githubusercontent.com/746351/34921633-3151ad9e-f93a-11e7-9c84-62b901c34497.png)

ETA on push? This is getting exceptionally annoying....

**Comment by ToreJuloe** [comment]
@kyleboddy if this is indeed a Chromium bug, you can go and star it and add more info[ on the Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=724538), to show that you're interested in having this bug solved.

**Comment by brenca** [comment]
I did some digging for a proper solution, and added a comment on the chromium bug tracker with possible solutions.

**Comment by spbuda** [comment]
I don't think this is just an issue with minimizing. I get it pretty consistently for the 'Sync' button tooltip, without minimizing. The popover appears and won't go away. Usually, it will go away once I refocus on Github desktop, but no such luck this morning.

Using windows 10.

I know this still isn't enough to recreate things, but at least I can show exactly what I see. Let me know if you think this is an independent issue and I can file it accordingly, but I wouldn't be surprised if the mechanism for the bug is the same in both cases.
https://gfycat.com/CavernousRashEquestrian

**Comment by mcmonkey4eva** [comment]
@spbuda you're not using GitHub Desktop, you're using GitHub-for-Windows, the precursor to GitHub Desktop. You can grab the modern client from https://desktop.github.com/

**Comment by spbuda** [comment]
@mcmonkey4eva  Oh my, I'm a dunce. Thank you so much, that should make my life much nicer.

**Comment by ikriz** [comment]
On windows 7 it helped to disable the fade in & out animations of windows via the taskbar/theme customize stuff not sure where it is in Windows 10
