### ISSUE TITLE
When will electron be updated and released with chrome version 59.0.3071.115?

### ISSUE THREAD

**Issue by poojas2288** [electron/electron#9948]
* Electron version:
1.7.3
* Operating system:
Windows

There are some fixes in chrome version **59.0.3071.115** which are **critical** for our project. May I know when will electron be upgraded with this chrome version and releaed ?

Last chrome upgrade was on 11th May : electron v1.7.0 beta, Upgraded from Chrome 56.0.2924.87 to 58.0.3029.110

**Comment by MarshallOfSound** [comment]
You can watch https://github.com/electron/electron/issues/9679 for progress on the Chromium 59 upgrade.  There are several active PR's at the moment where upgrade work is taking place.
