### ISSUE TITLE
Electron freeze completely trying to load some external meteor app

### ISSUE THREAD

**Issue by mickael-kerjean** [electron/electron#9954]
* Electron version: v1.6.11
* Operating system: OSX

### Expected behavior
Shouldn't crash while loading a url using either the loadURL or the webview tag.

### Actual behavior
The meteor web apps I am trying makes Electron freeze. The only way I can quit it is to:
```
kill -9 PID
```
Most URLS are running fine, the only issues I'm experiencing is with meteor based apps like [wekan](https://github.com/wekan/wekan) and [rocket.chat](https://github.com/RocketChat/Rocket.Chat)
Examples of external URLS: 
- https://todo.kerjean.me
- https://demo.rocket.chat if you click on the meteor login button, it will hang.

### How to reproduce
```
git clone https://github.com/mickael-kerjean/bug-electron
npm install
npm start
```

**Comment by pashka4281** [comment]
Hey,
have you got any insights about it?
Experiencing the same issue that only affects meteor apps, although some of them work fine, but most - not.
Tried electron versions 1.7.2 to latest 1.8.2-beta5 - no luck still

**Comment by pashka4281** [comment]
ok, I figured it was related to the way I start my scripts, for some reason it just doesn't work properly if run from wemux, but running it from directly form terminal fixes the problem

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
