### ISSUE TITLE
Desktop notification stopped working on Windows 8

### ISSUE THREAD

**Issue by akashnimare** [electron/electron#9956]
* Electron version: 1.6.8
* Operating system:
Windows 8

**Comment by MarshallOfSound** [comment]
Desktop notifications only work on Windows 8 if you have a shortcut in the start menu with the same `appUserModelId` as your application.  Do you have this shortcut set?

**Comment by akashnimare** [comment]
Got it. Just added `appUserModelId` in renderer process and now notification works as expected.
```` javascript
const {remote} = require('electron');
const app = remote.app;
app.setAppUserModelId('yourapp')
````

**Comment by akashnimare** [comment]
Thanks @MarshallOfSound ❤️
