### ISSUE TITLE
Notification API (HTML5) doesn't work after Mac signing

### ISSUE THREAD

**Issue by kcampion** [electron/electron#9958]
* Electron version: 1.6.10
* Operating system: macOs 10.12.5

When I use the HTML5 Notification API, the notification works well with a simple `electron .`.

But if I package and sign my application with `electron-packager` & `electron-osx-sign` for the AppStore (with my Mac Developer), the application runs perfectly except the notifications; no notification appears.

Have you got some idea or suggestion?

I created a similar issue on [electron-osx-sign](https://github.com/electron-userland/electron-osx-sign/issues/145).

**Comment by akashnimare** [comment]
@kcampion Probably need more info. Can you point to a demo app?

**Comment by kcampion** [comment]
@akashnimare The problem didn't come from electron or electron-osx-sign :( Look here [electron-osx-sign#145](https://github.com/electron-userland/electron-osx-sign/issues/145).
This issue can be deleted, it's not useful for the community. Sorry for that.
