### ISSUE TITLE
makeSingleInstance does not work on 1.7.4

### ISSUE THREAD

**Issue by amircodota** [electron/electron#9965]
We have an app that uses makeSingleInstance.

When upgrading to electron 1.7.4, when running a second instance of the app, it would hang for a while, and then kill the first instance and start the new instance.
The expected behavior is that the first instance would move to the front while the second instance would quit.

This was observed on both OSX and Ubuntu 16.04.

Tested on electron 1.6.11 and it works fine.

Thanks

**Comment by inukshuk** [comment]
See #9880

**Comment by MarshallOfSound** [comment]
Merging into #9880
