### ISSUE TITLE
Third-party code failing in Require.js

### ISSUE THREAD

**Issue by starkos** [electron/electron#9969]
* Electron version: 1.6.11
* Operating system: macOS 10.12.5

### Expected behavior

Loading the SiriusXM website into an Electron frame with `nodeIntegration: false` should succeed and work similarly to Chrome.

### Actual behavior

The site fails to complete loading. There are numerous errors in the console of the form "TypeError: Cannot read property 'toLowerCase' of undefined", all at the same location within `require.js`.

### How to reproduce

```
  $ git clone https://github.com/starkos/electron-siriusxm-issue
  $ npm install
  $ npm start || electron .
```

The example is pretty much just the quick-start example with the addition of `nodeIntegration: false` and `loadURL('https://player.siriusxm.com/');`. The error message will appear in the devtools console.

Still digging into it here, but any advice appreciated…thanks!

**Comment by jezdesilva** [comment]
is this related to this: 
https://github.com/electron/electron/pull/9095/commits/50c99e4507d3a9f06c66d52754c977d24eea347c

inside this PR:
https://github.com/electron/electron/pull/9095

**Comment by starkos** [comment]
Possibly? Though with `nodeIntegration: false` I would not have expected Node's `require()` method to get called.

**Comment by starkos** [comment]
Still an issue in Electron 1.7.5.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
