### ISSUE TITLE
Upgrade to Node 8

### ISSUE THREAD

**Issue by hhsnopek** [electron/electron#9970]
Issue Tracker for Node 8 upgrade.

For those curious about a timeframe, see  [FAQ#when-will-electron-upgrade-to-latest-nodejs](https://electron.atom.io/docs/faq/#when-will-electron-upgrade-to-latest-nodejs)
>When a new version of Node.js gets released, we usually wait for about a month before upgrading the one in Electron. So we can avoid getting affected by bugs introduced in new Node.js versions, which happens very often.
>
> New features of Node.js are usually brought by V8 upgrades, since Electron is using the V8 shipped by Chrome browser, the shiny new JavaScript feature of a new Node.js version is usually already in Electron.

**Comment by kevinsawicki** [comment]
This will be part of the Chrome 59 upgrade work which is going on in #9946

**Comment by alexeykuzmin** [comment]
@kevinsawicki There is a small problem with the Node.
Chromium 59 uses V8 version 5.9.211.38, the latest stable Node (8.1.4) has V8 version 5.8.283.41.
I'm not sure if we can use it.

The Node 8.2.0 [is coming](https://github.com/nodejs/node/pull/13744) (right now in beta) with V8 5.9.211.37. Should we wait for it to be released?

**Comment by kevinsawicki** [comment]
> But the Node 8.2.0 is coming with V8 5.9.211.37. Should we wait for it to be released?

Seems like this may happen pretty soon so I think we can just target it in the chrome 59 branch, looking into it now and applying the node patches to that version.

**Comment by kevinsawicki** [comment]
Initial Node 8.2.0 upgrade branch up at https://github.com/electron/node/pull/23

**Comment by kevinsawicki** [comment]
> Initial Node 8.2.0 upgrade branch up at electron/node#23

Switched it to 8.1.4 since the timeline and v8 version for 8.2.0 is still being decided.

**Comment by stanleyxu2005** [comment]
Node 8.9.2 is now being the LTS version already. Hope we can have it soon.

**Comment by alexeykuzmin** [comment]
@stanleyxu2005 there won't be an Electron release with the Node.js 8.9.2.
After 8.7.0 we are going to use 9.2.0.

**Comment by stanleyxu2005** [comment]
@alexeykuzmin  I don't really understand the approach of using any odd Node versions. I was heard that Node uses odd major version (7,9) for experiments and uses even versions (6,8) for stable/LTS propose.

**Comment by alexeykuzmin** [comment]
@stanleyxu2005 the only difference between odd- and even-numbered versions of the Node.js is that the latter are maintained for a longer period of time [1].
Since Electron is always trying to use the latest stable Chromium and Node.js versions we do not care about the maintenance period of any of these.

[1] https://github.com/nodejs/Release

**Comment by truefusion** [comment]
@alexeykuzmin When can we expect electron to ship with Node v9.2.0 or even v8.7.0?

**Comment by alexeykuzmin** [comment]
@truefusion I don't work at GitHub and I'm not involved in the process of Electron releases.
If you need Electron with Node.js 8, you can use the latest Electron [v1.8.2-beta.3](https://github.com/electron/electron/releases/tag/v1.8.2-beta.3), it uses Node.js 8.2.1.

**Comment by biplabmalakar** [comment]
When I am try to install electron with node 8 or 7 it will not work, but when install with node6.0 then no problem. Can any one help me what is the problem.

**Comment by alexeykuzmin** [comment]
@biplabmalakar Please create a[new issue](https://github.com/electron/electron/issues/new) with a detailed explanation what you're doing and what goes wrong.

**Comment by mividtim** [comment]
@alexeykuzmin  You should actually care a lot more about long-term support. As a business building an embedded system, we care greatly about using LTS versions of code. Electron itself may be happy with shipping odd versions, but in an embedded system, we can't be upgrading Electron often. We are using a custom version of Electron that embeds Node 6.5 right now, and were keen on waiting for Electron to embed Node 8.9 as our next upgrade. Skipping over the LTS version in favor of keeping "up-to-date" is not good strategy. We also run Node apps outside of Electron, and try to keep our outside-Electron Node version at the same exact version as our Electron-embedded version.

**Comment by alexeykuzmin** [comment]
@mividtim There is absolutely no need to spam in [every](https://github.com/electron/electron/issues/11286#issuecomment-360816756) Node-related [issue](https://github.com/electron/electron/pull/11230#issuecomment-360816501).

The next major release of Electron will be shipped with the Node.js 8.9.x.

**Comment by mividtim** [comment]
@alexeykuzmin  It's really great that you monitor the issues. I'm much more used to seeing issues generally ignored in other projects. I definitely didn't mean to be a burden, but I did hope to get a maintainer's attention. :-) It is great to hear that Node 8.9 will be embedded in Electron! Thanks for listening, and for replying!

**Comment by MarshallOfSound** [comment]
@mividtim To further clarify as well, the major release after the one with `8.9.x` will ship with `9.x`, the version of node we use must use the same v8 version as the version of chromium we use.  So when one updates the other one will update as well 👍

**Comment by Ruuv1337** [comment]
please build version for node.js 9.4.0

**Comment by codebytere** [comment]
Closing as this is no longer a bug or enhancement request, and our path forward for node versions is more clear with responses above.

**Comment by JaroslavTulach** [comment]
I beg your pardon: May I have an outsider question? I see @alexeykuzmin's comment from Jan 26:

> The next major release of Electron will be shipped with the Node.js 8.9.x.

Did that already happen? What is the name of "next major release"? Is there a way to track the progress? What are the steps to get the source? Is there a branch/tag that I can check out?

I am new to Electron and I admit I don't know where to start digging the history in its multi repo setup. Yet, I'd love to play with Electron that uses node.js version 8.9.x. Thanks in advance for any hint.

**Comment by codebytere** [comment]
@JaroslavTulach hey, happy to help! 

The current latest version of Electron is `v1.8.4`, shipped with Node `v8.2.1`. The next major release is the `2.X` line, which is in late beta stages right now. We're currently on `v2.0.0-beta.7`, which ships with Node `v8.9.3`.

You can keep track of these by looking at our [homepage](https://electronjs.org/), and there is a [project board](https://github.com/orgs/electron/projects/11) tracking our path to `2.0.0` stable :) 

Branches for release lines are tagged accordingly (ex. `1-8-x` and `2-0-x`).

The project can be downloaded via either the releases tab or by running
`$ git clone https://github.com/electron/electron`. 

Good luck!
