### ISSUE TITLE
Electron crash when add 'single-process' to command line

### ISSUE THREAD

**Issue by steem** [electron/electron#9977]
* Electron version: v1.7.4 beta
* Operating system: win10

### Expected behavior

Electron should run with single process

### Actual behavior

Electron crashed

### How to reproduce

electron.exe --single-process

or

In the main.js, add the following code:
app.commandLine.appendSwitch('single-process');

**Comment by enlight** [comment]
Electron doesn't support the single-process model, see https://github.com/electron/electron/issues/6903#issuecomment-241298639
