### ISSUE TITLE
Ampersands (&) not rendered in Menu labels.

### ISSUE THREAD

**Issue by benlancaster** [electron/electron#9978]
* Electron version: 1.6.11
* Operating system: macOS

### Expected behavior

Ampersand character should be rendered when used in Menu `label`s.

### Actual behavior

Ampersands not rendered

### How to reproduce

```js
  const menuTemplate = [{
    label: app.getName(),
    submenu: [
      {
        label: 'This & that',
        click: () => {}
      }
    ]
  }]

  const builtMenu = Menu.buildFromTemplate(menuTemplate);
  Menu.setApplicationMenu(builtMenu);
```

I have also tried unicode and html encoding the ampersand, all without success.

Result:

![missing ampersand in menu](https://raw.githubusercontent.com/benlancaster/electron-quick-start/master/Screen%20Shot%202017-07-11%20at%2011.29.57.png)

Electron Quick Start project demonstrating the issue: https://github.com/benlancaster/electron-quick-start

```
$ git clone git@github.com:benlancaster/electron-quick-start.git
$ cd electron-quick-start
$ npm start
```

I haven't done an exhaustive test, but pretty much every other non-word character I've tried works fine, it seems to literally just be ampersands.

**Comment by tlgreg** [comment]
Has been discussed here: #9584 
You can use `&&` to display an ampersand.
