### ISSUE TITLE
Textarea resizer is small

### ISSUE THREAD

**Issue by JohannBlake** [electron/electron#9979]
Not sure if this is a bug but the resize grabber located in the bottom right corner of a textarea is really small. So small that it's almost unusable. However, in Chrome, the size is much larger. This is clearly not an issue of some css in my app. Even the Electron demo app exhibits this. Is this an issue with the Chrome version used by Electron or has Electron put something in that is causing this?

* Electron version:  1.6.11
* Operating system: MacOS

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
