### ISSUE TITLE
webContents.getFocusedWebContents() Question

### ISSUE THREAD

**Issue by JackieLs** [electron/electron#9980]
* Electron version: 1.6.10
* Operating system: Mac

I use webContents.getFocusedWebContents() to get a webcontens.
but when I start the app first time and I don't click the webview the webContents.getFocusedWebContents() is just like the following
![image](https://user-images.githubusercontent.com/14228179/28065423-0d754d66-666b-11e7-8267-2158e3f5e301.png)
and I click the webview the webContents.getFocusedWebContents() is just like this
![image](https://user-images.githubusercontent.com/14228179/28065435-1deb4560-666b-11e7-98ea-8654497d4a8e.png)

the second one is what I expect

but how could I get this without click the webview

**Comment by kevinsawicki** [comment]
It looks like in your first screen shot the dev tools web contents is focused, are the devtools open at start?

**Comment by kevinsawicki** [comment]
> the "devtools" is also a webcontents?

Yes it is since it is another page that loads a `chrome-devtools://` URL.
