### ISSUE TITLE
shell.moveItemToTrash returns true even when file locks caused a failure (Windows)

### ISSUE THREAD

**Issue by jgrosso** [electron/electron#9981]
* Electron version: 1.6.11
* Operating system: Windows x32 and x64

### Expected behavior

When I call `shell.moveItemToTrash` on a file or directory that cannot be deleted due to file locks, the method should return `false` (as nothing has actually happened).

### Actual behavior

The method returns `true` even though the item was not actually moved to the Recycle Bin.

### How to reproduce

1. Lock a file or directory somehow (e.g. open it in Atom).
2. Verify that that item cannot be deleted from Windows Explorer (with a file locking issue).
2. Call `shell.moveItemToTrash` with that file path.
3. Verify that the result is `true` even though the Recycle Bin should still be empty.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by implausible** [comment]
@sofianguy This issue is still present in Electron 9.1.0
