### ISSUE TITLE
Native file and print dialogs do not scale properly when dragged between displays of differing DPI on Windows

### ISSUE THREAD

**Issue by daguej** [electron/electron#9984]
* Electron version: 1.6.11
* Operating system: Win 10 build 16199

### Expected behavior
File open, save, and print dialogs respond properly to `WM_DPICHANGED`; scale properly when dragged between displays that have different DPIs (ie from a hi-DPI display to low-DPI display).

### Actual behavior
Dialogs do not scale when moved to displays with differing DPIs, resulting in windows that render outrageously large (or small).

Compare the dialog opened by Electron (left) with the dialog opened by Notepad (right):

![electron vs notepad](https://user-images.githubusercontent.com/354349/28235818-f0024902-68ca-11e7-90ab-008d1176676b.png)

### How to reproduce

```js
electron.dialog.showOpenDialog({}); // and...
electron.dialog.showSaveDialog({}); // and...
window.print();
```
...then drag the native file/print window between monitors OR open the dialog on a monitor that has a DPI different from the System DPI.

Also happens when the file open dialog is invoked by clicking the browse button of a `<input type="file">`.

(`showMessageBox` dialogs **do** work correctly -- they resize and rerender to display appropriately.)

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by JannisX11** [comment]
I am getting the same error in Electron 4.0.3. File dialogs don't resize when moved to another screen. Message boxes work.

**Comment by snarum** [comment]
I see this issue on both Vscode and Slack. I have 200% on my laptop and 100% scaling on my external montior, and File->Open gets 
![electron1](https://user-images.githubusercontent.com/5821202/69606261-a7e5a900-1022-11ea-944e-af2af62d320d.png)
![electron2](https://user-images.githubusercontent.com/5821202/69606262-a7e5a900-1022-11ea-913b-488c6ba17293.png)

enormous on the external monitor.

**Comment by Ta-Tung** [comment]
I am getting the same error in Electron 6.0.0. File dialogs don't resize when moved to another screen.
