### ISSUE TITLE
makeSingleInstance always returns true in signed OSX apps

### ISSUE THREAD

**Issue by dpalou** [electron/electron#9985]
* Electron version: 1.6.11 and 1.7.4
* Operating system: macOS Sierra 10.12.4

### Expected behavior

The documentation of makeSingleInstance says:

This method returns false if your process is the primary instance of the application and your app should continue loading. And returns true if your process has sent its parameters to another instance, and you should immediately quit.

### Actual behavior

The first time I run the app, makeSingleInstance returns true. This only happens when I sign the app using sandbox mode.

### How to reproduce

Reproducing this isn't trivial because it requires having development certificates and provisioning profile.

Download the electron-quick-start project and add these lines at the end of the main.js:

```
var shouldQuit = app.makeSingleInstance((argv, workingDirectory) => {});
if (shouldQuit) {
    app.quit();
}
```

I also added this to the package.json:

  ```
"build": {
    "appId": "com.moodle.moodledesktop",
    "productName": "Moodle Desktop",
    "files": [
      "!desktop"
    ],
    "directories": {
      "output": "desktop/dist"
    },
    "protocols": [
      {
        "name": "Moodle Mobile URL",
        "schemes": [
          "moodlemobile"
        ],
        "role": "Viewer"
      }
    ],
    "electronVersion": "1.7.4",
    "mac": {
      "category": "public.app-category.education",
      "target": "mas",
      "extendInfo": {
        "ElectronTeamID": "MYTEAMID"
      }
    }
  }
```

Now in the console I run:

```
build

electron-osx-sign desktop/dist/mas/Moodle\ Desktop.app --type=development --platform=mas  --provisioning-profile=PATH_TO_DEV_PROV_PROF  --entitlements=desktop/assets/mac/parent.plist --entitlements-inherit=desktop/assets/mac/child.plist --identity="MY_DEV_IDENTITY"
```

You can see the contents of parent.plist and child.plist in here:

https://github.com/dpalou/moodlemobile2/tree/MOBILE-839-desktop/desktop/assets/mac

After this, if I run the app it is closed immediately because _shouldQuit_ is true.

**Comment by feens** [comment]
We just came across this issue as well.  Everything was working fine until we signed our app.  My guess is it has to do with how single instance tracking is done and what sandboxed apps have access to.

**Comment by MarshallOfSound** [comment]
This was reported and handled in https://github.com/electron/electron/issues/6771

/cc @paulcbetts Did you PR to close the linked issue regress somehow or is this a different issue? 😄

**Comment by feens** [comment]
Given this: https://github.com/electron-userland/electron-osx-sign/issues/137 (and the solution for it), and the issues described here, I'm guessing it is broken again.

If I look in my console I see this:

`SandboxViolation: AppName(69616) deny(1) network-bind /private/var/folders/19/n833n8b5429gtsbmvd1wmy900000gn/T/com.app_name.desktop/S/SS`

**Comment by Tev-work** [comment]
This bug has clearly resurfaced, we have encountered it as did many other people, see https://github.com/electron/electron/issues/9566

Workaround with electron-is's sandbox detection and using LSMultipleInstancesProhibited for the sandboxed version works fine though.

**Comment by gerges** [comment]
A bit confused by this one, the sandbox docs seem to claim this should be allowed since we specify an Application Group: 

https://developer.apple.com/library/content/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW24

I tried adding explicitly read/write entitlements to this lockfile with no luck. If possible, I think it's worth trying to move this file inside the app container.

**Comment by JakeRadMSFT** [comment]
Any updates? How can I workaround this on a Mac?

**Comment by gerges** [comment]
```
var shouldQuit = app.makeSingleInstance();
if (shouldQuit && !process.mas) {
    app.quit();
}
```

**Comment by JakeRadMSFT** [comment]
Hmm perhaps I'm hitting a different issue then. 

The issue I'm seeing is that the person holding on to the lock gets killed and a new process is started.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
