### ISSUE TITLE
shell.openExternal() Windows URL limit of 2081 characters 

### ISSUE THREAD

**Issue by andrei-cacio** [electron/electron#9987]
* Electron version: 1.4.12
* Operating system: Windows 10

### Expected behavior

Open the url given in the default OS browser

### Actual behavior

`shell.openExternal(url);` returns `false`

### How to reproduce

Call `shell.openExternal()` with an url of length greater than **2081** under a Windows OS. 

*(I only tested it on Windows 10, on MacOS works fine)*

**Comment by MarshallOfSound** [comment]
This is an OS limitation on Windows, it can only handle urls with a length of less than 2083.  I don't believe there is any way to get around this issue.

**Comment by andrei-cacio** [comment]
ok, thanks for your response!

**Comment by andreieftimie** [comment]
It would be nice to have this documented.

**Comment by andrei-cacio** [comment]
yes, agree with @andreieftimie. There isn't a single place where this limitation is mentioned.

**Comment by MarshallOfSound** [comment]
It all comes back to IE's stupid URL character limit, it would be good if someone could add this to the docs.

[Microsoft Reference](https://support.microsoft.com/en-us/help/208427/maximum-url-length-is-2,083-characters-in-internet-explorer)

**Comment by andrei-cacio** [comment]
I reopened this issue because maybe it dissevers a deeper look into. After digging around a bit I found out that electron uses under the hood `ShellExecute`[https://msdn.microsoft.com/en-us/library/windows/desktop/bb762153(v=vs.85).aspx] on Windows systems. I hope I am not mistaking. 

This native function has exception if something goes wrong, electron simply implements a `Boolean` facade over it. Should electron version of `shellExecute()` throw erros as well and not simply a `false` value?

**Comment by MarshallOfSound** [comment]
@andrei-cacio For now I believe this is a documentation issue, most electron API's return a boolean value to indicate success so it's pretty standard.

**Comment by andrei-cacio** [comment]
@MarshallOfSound ok, that sounds fair. But about the **2083** IE limitation, what does that have to do with the fact that the URLs are being opened in Chrome or other browsers? Is that limitation a de facto standard for dealing with URLs under Windows?

**Comment by cifratila** [comment]
@andrei-cacio More about this here: https://wiert.me/2010/04/20/maximum-url-lengths/ IE has limitation, but others not and can handle even up to 100k. 

IMHO there is something fishy in having support for more than 2k characters in your URL, you should probably be using POST params to obtain the wanted results.
