### ISSUE TITLE
Can't change input method using CapsLock On Sierra

### ISSUE THREAD

**Issue by yangbeom** [electron/electron#9997]
* Electron version: 1.6.11
* Operating system: macOS Sierra 10.12.5

### Expected behavior

![Imgur](http://i.imgur.com/tvuBIQd.png)

change input method when press CapsLock

### Actual behavior

focused electron application can change input method using CapsLock.

focused others applications doesn't work when running electron application. 

But can change input method using Ctrl+Space 

### How to reproduce

globalShortcut register that MediaNextTrack, MediaPreviousTrack, MediaStop and MediaPlayPause

**Comment by shubham2892** [comment]
Can reproduce the issue on Mac 10.12.5 using https://github.com/shubham2892/electron-quick-start/tree/global-shortcut-repro.

**Comment by aryyya** [comment]
I cannot reproduce this behaviour on macOS Sierra 10.12.5.

**Comment by yangbeom** [comment]
@aryyya reproduce the issue on macOS Sierra 10.12.5 using my repo

> git clone https://github.com/yangbeom/bugselectronplayer -b v1.3.0

**Comment by shubham2892** [comment]
Was able to reproduce with chrome. Reported it here: https://bugs.chromium.org/p/chromium/issues/detail?id=745211#

**Comment by yangbeom** [comment]
Can't reproduce it on Mac 10.13 High Sierra

I think it's Mac Sierra's Bug. :)
