### ISSUE TITLE
openItem and openExternal not working in Ubuntu after creating snap file

### ISSUE THREAD

**Issue by dpalou** [electron/electron#9998]
* Electron version: 1.6.11 and 1.7.4
* Operating system: Ubuntu 16.04.

### Expected behavior

shell.openItem and shell.openExternal should open the file. 

### Actual behavior

Nothing happens when I call the functions. openItem returns false, openExternal returns true, but none of them opens the file. I'm trying with openExternal because in Mac I had problems with openItem too (see [issue 9005](https://github.com/electron/electron/issues/9005)).

I'm using electron-builder to create a snap file. My app is able to open the files before creating the snap file, but once the file is created and installed it no longer works.

### How to reproduce

In Ubuntu 16.04, download the electron-quick-start project and modify the main.js file so the dev tools are opened:

`mainWindow.webContents.openDevTools();`

Run the app using "electron ." and, in the Javascript console, use the code to open a file:

```
var shell = require('electron').shell;
shell.openItem(PATH_TO_FILE);
```

Check that the file is opened.

Now add the data for electron-builder in the package.json:

  ```
"build": {
    "appId": "com.moodle.moodledesktop",
    "productName": "Moodle Desktop",
    "files": [
      "!desktop"
    ],
    "directories": {
      "output": "desktop/dist"
    },
    "electronVersion": "1.7.4",
    "linux": {
      "category": "Education",
      "target": "snap"
    }
```

After doing this, run:

```
build
sudo snap install --dangerous desktop/dist/NAME.snap
```

Once the app is installed, open it and perform the same action as before to open a file. Check that now the file isn't opened.

I tried using both openItem and openExternal. I tried adding the file:// protocol to the path. I tried calling the function from the main process and from the renderer process. None of this worked.

Example of the path to the file:

/home/dpalou/snap/moodlemobile/x3/com.moodle.moodlemobile/image.jpeg

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
