### ISSUE TITLE
webview.goForward() not working, while goBack() works

### ISSUE THREAD

**Issue by StefanSzakacs21** [electron/electron#9999]
* Electron version: 1.6.11
* Operating system: Windows 10

### Expected behavior

After navigating backward I should be able to navigate back forwards.

### Actual behavior
After I press the back button (which triggers the webview.goBack() successfully and can go back) I press the forward button (which triggers the webview.goForward()) but it wouldn't navigate forward, even though webview.canGoForward() returns true.

**Comment by FitsnerAS** [comment]
Actually we have the same issue. goForward isn't works

**Comment by hiddentao** [comment]
I have the same issue.

**Comment by codebytere** [comment]
Does this occur on `2.0.0`?

**Comment by codebytere** [comment]
Does this occur on `2.0.0` or `1.8.X` versions?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
